### ISSUE TITLE
Feature Request: Allow `Fetch This Event` for events that are part of disabled/cache-only feeds

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/MISP#10003]
### Is your feature request related to a problem? Please describe.

Currently I have a very select handful of trusted feeds that are enabled and are set to automatically ingest into my instance via the scheduled task for `fetch_feeds`. When this task is executed on an hourly basis, any feeds that are `enabled` are automatically ingested into my instance. As a result of this behavior, I also have some less-trusted/noisy feeds that are not `enabled` but do have caching turned on so I can see any correlations that may arise.

Currently, if there is a specific event in one of those less-trusted feeds that I'm interested in after browsing it via `PreviewEvent`, if I click `Fetch This Event` I'm presented with a message of `Feed is currently not enabled. Make sure you enable it.` However, I do NOT want to enable the feed because that will allow all the noisier events from that feed to populate my instance every time the `fetch_feeds` task executes.

### Describe the solution you'd like

I would like the `Fetch This Event` button to work for any event that can be viewed in the feeds cache, regardless of whether or not it is enabled. If I'm manually deciding to pull a single, specific event, I should be able to import it into my MISP instance without enabling all the other garbage that may exist on that particular feed.

### Describe alternatives you've considered

I could manually import the JSON files of the events that are saved to disk, but that's a huge hassle when I should be able to look at an event, say "that's good, save that one," and be done with it straight from the web UI.

### Additional context

In this instance I'm generating these feeds via background cronjobs with the feed-generator scripts, so I know the JSON of the events themselves are being saved to disk in the 'output' directory. If the files are there it should be trivial to say "yup, I want that one that I'm looking at right now" without having to enable the feed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheDr1ver** [comment]
I feel like it should be as simple as removing this check, no?

https://github.com/MISP/MISP/blob/bb0909a37a7bd727d35f7a60ee9a6ff10bc99852/app/Controller/FeedsController.php#L672-L675

**Comment by iglocska** [comment]
Good point indeed.
