### ISSUE TITLE
Bug: Hostnames in Custom Feed Incorrectly Identified as Filename

### ISSUE THREAD

**Issue by sva-mk** [MISP/MISP#10008]
### Actual behavior

We have encountered an issue where some hostnames of [the custom feed we are using](https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/refs/heads/master/feeds/DNSC2Domains-30day.csv) are being incorrectly identified as filenames. This issue occurs with both the CSV parser and the freetext parser used to import the feed into misp.

For example, these hostnames from the CSV feed are treated as one filename rather than two hostnames. "ns1[.]163microsoft[.]com ns2[.]163microsoft[.]com".

### Expected behavior

 The host names should be correctly identified as host names.
 Following the example above, the parser should identify the hostnames as "ns1[.]163microsoft[.]com" and "ns2[.]163microsoft[.]com".

### Steps to reproduce

1. Add [the custom feed](https://raw.githubusercontent.com/drb-ra/C2IntelFeeds/refs/heads/master/feeds/DNSC2Domains-30day.csv) to the misp instance using freetext or CSV parser.
3. Use the preview to check the parsed content.

### Version

2.4.198

### Operating System

Ubuntu using misp-docker

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spicyprogramming** [comment]
https://github.com/MISP/MISP/issues/9200#issuecomment-1642216808
