### ISSUE TITLE
There was an error with the user account

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1000]
I got this error while trying to push an event to a remote MISP instance...

resque-2016-03-03.log:[2016-03-03 15:03:54] main.ERROR: {"queue":"default","id":"04f4cadd559c715070ee774d85b39f63","class":"ServerShell","args":[{"0":"enqueuePush","1":1457017200,"2":"3","3":"1","s_time":1457016681}]} failed: There was an error with the user account. {"type":"fail","log":"There was an error with the user account.","job_id":"04f4cadd559c715070ee774d85b39f63","time":4057,"worker":"d32501c6b679:1022"} []

This error comes from Model/Event.php:

if (!isset($user['org_id'])) { ... }

But I checked the database and my user has one!?

/x

**Comment by adulau** [comment]
Could be that the user doing the sync is not a sync user or the user never logged in and accepted the terms?

**Comment by iglocska** [comment]
Which version are you on? Is this the latest one?

**Comment by iglocska** [comment]
Oh, one more question: Did you just upgrade from 2.3->2.4 and are you still in the same session as you were when you upgraded?

**Comment by xme** [comment]
Brand new setup (so last release yes).
User (on the remote side) is a sync user and already connected (terms accepted)

**Comment by xme** [comment]
Back onsite at customer with this issue... I checked again. The sync is working only in one direction: "pull". I created a test event, distribution is set to "This community only" which includes the servers which are syncing with me right? My event is created with the same organization name as on the sync user on the remote MISP... I'm lost :-/

**Comment by iglocska** [comment]
This community only will not be pushed. It can only be pulled.

Basically: 

Connected Community only events can be pushed or pulled by a remote and they will become "This community only"

Community only events cannot be pushed, but can be pulled and will become Your organisation only to the organisation that has pulled it (as that organisation itself is part of the community - they are using their own sync user on your instance).

**Comment by xme** [comment]
When I schedule a "push", I've the following line in the logs:

Id: xxxxx 
Email: "a"
Org: "a" 
Created: xxx-xx-xx xx:xx:xx

From where are coming those "a" ? Which email and org should I see?

**Comment by iglocska** [comment]
You should see the organisation and email of the user that is creating the
push, but there is indeed a bug with it after playing around with it. I'll
have a patch ready within 5 mins.

**Comment by xme** [comment]
Great! Ready for an upgrade! :)

**Comment by iglocska** [comment]
Let me know if this fixes it for you, I'll leave the ticket open until then. Was a nice catch, I kept testing by just push-ing, but the bug was with the way that scheduled pushes were queued up. Thanks!

**Comment by xme** [comment]
I rebuilt my docker container and the error is indeed gone! Tx!

**Comment by iglocska** [comment]
Excellent news, thanks :)
