### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by rahulmanoj98** [MISP/MISP#10011]
### Support Questions

installed MISP, during installation the below error was shown 
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 298

there was also an error saying incompatability between php and cakephp.
check files installed in /var/www/MISP and there was no cake directory.
i had a test instance where GUI is successfully accessible. Copied cake directory from it to this.
misp-workers.service is loaded and is shown as activating but never active and running.
when i try to manually start it using start.sh script, it shows 
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 298

Currently while tring to access GUI, it says An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### MISP version

2.4

### Operating System

ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Browser

Chrome

### Relevant log output

```shell
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 298

PHP Fatal error:  Uncaught Error: Class 'CakeRequest' not found in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php:147\nStack trace:\n#0 /var/www/MISP/app/Error/AppExceptionRenderer.php(8): ExceptionRenderer->_getController()\n#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(126): AppExceptionRenderer->__construct()\n#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(271): ErrorHandler::handleException()\n#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(214): ErrorHandler::handleFatalError()\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError()\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php on line 147

#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path()
#2 [internal function]: App::load()
#3 [internal function]: spl_autoload_call()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#8 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomking2** [comment]
Hi @rahulmanoj98, this looks like you have a partial MISP install as some aspects were not successful. I'm not sure how much has failed, so it might be a bit of work to get this up and running.

Are you certain you are on the MISP 2.4 branch? MISP now defaults to MISP 2.5 (which requires a difference PHP version) and is aimed for Ubuntu 24.04. This could be why you are having issues.

If you're on the right branch, I'd try running the following section of the install guide: https://misp.github.io/MISP/xINSTALL.ubuntu2204#4-cakephp.

If you followed the 2.5 install and want to continue down this path, you should either:
- Upgrade Ubuntu to 24.04 OR
- Find a suitable repo that offers PHP8 for Ubuntu 22.04.

**Comment by rahulmanoj98** [comment]
if i upgrade to ubuntu 24.04, i cannot find an installation script for it in https://misp.github.io/MISP/

Is it possible to provide the steps for implementing MISP in 24.04?

Also i used the below command to download the script 
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh

**Comment by tomking2** [comment]
There is an install guide for 24.04 for MISP 2.5 you can follow: https://raw.githubusercontent.com/MISP/MISP/2.5/INSTALL/INSTALL.ubuntu2404.sh. This is the recommended route, as you'll get the most recent version of MISP with long term support.

If you want to stay on the 2.4 branch (being deprecated very soon), I usually followed the 22.04 installer https://misp.github.io/MISP/xINSTALL.ubuntu2204 manually from top to bottom.

**Comment by rahulmanoj98** [comment]
@tomking2 i had installed this in September and it was error free, GUI was accessible.
i tried installing this manually using the link you provided and when i reached installation of php7.4 

```
 "deb http://ppa.launchpad.net/ondrej/php/ubuntu devel main" |sudo tee /etc/apt/sources.list.d/ondrej-ubuntu-php-devel.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
sudo apt update
installDepsPhp80 () {
  debug "Installing PHP 8.0 dependencies"
  PHP_ETC_BASE=/etc/php/7.4
  PHP_INI=${PHP_ETC_BASE}/apache2/php.ini
  checkAptLock
  sudo apt install -qy \
  libapache2-mod-php7.4 \
  php7.4 php7.4-cli \
  php7.4-dev \
  php7.4-json php7.4-xml php7.4-mysql php7.4-opcache php7.4-readline php7.4-mbstring php7.4-zip \
  php7.4-intl php7.4-bcmath \
  php7.4-gd
```
  
the above is a code snippet from the link provided, when run, the below error pops up :

```
deb http://ppa.launchpad.net/ondrej/php/ubuntu devel main
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.LX43hhWIrY/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C


gpg: keyserver receive failed: Network is unreachable
Hit:1 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu devel InRelease [24.4 kB]
Err:2 http://ppa.launchpad.net/ondrej/php/ubuntu devel InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 71DAEAAB4AD4CAB6 NO_PUBKEY 4F4EA0AAE5267A6C
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu devel InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 71DAEAAB4AD4CAB6 NO_PUBKEY 4F4EA0AAE5267A6C
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu devel InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
why was php installation successful in September and not now?
i wanted to go forth in installinh v 2.4 itself.
Manual installation is getting stuck here.
Also tried using INSTALL.sh from https://raw.githubusercontent.com/MISP/MISP/refs/tags/v2.4.199/INSTALL/INSTALL.sh

but it gives the same error for php

**Comment by tomking2** [comment]
Hi @rahulmanoj98,

From what I can observe here, you are unable to receive the GPG signing key for the PHP repository due to some network issues:

```
Executing: /tmp/apt-key-gpghome.LX43hhWIrY/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C

gpg: keyserver receive failed: Network is unreachable
```

I'm not sure why, but you can't seem to reach `keyserver.ubuntu.com`. As a result, Ubuntu hasn't loaded the signing key for the repository and can't pull the package updates for you to be able to download PHP 7.4.

Try running this line of the install script manually (I just tested locally and I was able to connect and download the key):
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
```

If that is successful, you should be able to continue downloading PHP 7.4.

**Comment by rahulmanoj98** [comment]
i worked around by manually installing php 7.4
and tried installing MISP using https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
but still the error :
``
PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 298``
persists


please provide a root cause for this error occurring so that it would be possible for me to try out MISP 2.5

**Comment by tomking2** [comment]
Hi @rahulmanoj98,
If you have php 7.4, you might just need to install the vendor packages, try the following:

```
cd /var/www/MISP
sudo -u www-data php composer.phar install --no-dev
```

This should install and dependencies under the `Vendor` folder, which includes `autoload.php`

**Comment by iglocska** [comment]
Did you end up getting it resolved? If no, let us know, but as @tomking2 noted, it looks exactly as he described - a network error reaching the keyserver followed by a partial installation. With that said, if you are still looking to start from scratch, I'd recommend going the 2.5 route on ubuntu 24.04 instead.
