### ISSUE TITLE
Bug: Wrong link for updates

### ISSUE THREAD

**Issue by erosseleth** [MISP/MISP#10023]
### Actual behavior

I have an instance of MISP 2.4.198 installed on Ubuntu 22.04.5 LTS and the link for updates in "Administration > Server Settings & Maintenance > Diagnostics" aparently points to version 2.5.1

### Expected behavior

For this version of Ubuntu the update link should point to version 2.4.199 since 2.5.1 requires Ubuntu 24.04, or am I wrong?
Which would be the correct process to update?

### Steps to reproduce

Install MISP 2.4.198 over Ubuntu 22.04.5. LTS and check the update link.

### Version

2.4.198

### Operating System

Ubuntu

### Operating System version

22.04.5 LTS

### PHP version

7.4.133

### Browser

Chrome

### Browser version

130.0.6723.92

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
You are correct in that it should point to the latest version on 2.4 - I am surprised that it does not. It will point out that 2.5.2 is the latest version, but running the update via the GUI should get you up to date to the latest release on the 2.4 branch (2.4.200 currently).

So simply run the update -> it will then get you to the latest 2.4 release, which has an updated diagnostics page. 

![image](https://github.com/user-attachments/assets/b15b7eb4-0f8f-4050-9051-110b9544fd37)


After that you can proceed with the manual upgrade to 2.5 if you wish to do so, as described here:
https://github.com/MISP/MISP/blob/2.5/INSTALL/UPGRADE.ubuntu2404.sh
