### ISSUE TITLE
windows-service-displayname

### ISSUE THREAD

**Issue by negotrucky** [MISP/MISP#1003]
Hi
I want to add this information form an IOC : 

```
<IndicatorItem id="50455b63-35bf-4efa-9f06-aeba2980f80a" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/name" type="mir" />
          <Content type="string">winlogon.exe</Content>
        </IndicatorItem>
        <IndicatorItem id="b05d9b40-0528-461f-9721-e31d5651abdc" condition="contains">
          <Context document="ProcessItem" search="ProcessItem/HandleList/Handle/Type" type="mir" />
          <Content type="string">File</Content>
        </IndicatorItem>
```

But misp tell me that "winlogon.exe" is not in the right format for "windows-service-name" or "windows-service-displayname".
Could you tell me the expected format ?

It will be good to add some sample on this page too : [https://www.circl.lu/doc/misp/categories-and-types/index.html](url)

Thx Team ^^

**Comment by iglocska** [comment]
Well that was embarrassing, thanks for the heads-up :)
