### ISSUE TITLE
Bug: What are the update procedures for 2.5 after you are already running 2.5.1 on Ubuntu 24.04? 

### ISSUE THREAD

**Issue by www-jedi** [MISP/MISP#10041]
### Actual behavior

This is how I update my MISP 2.4 instance via CLI

#Updating MISP core
cd /var/www/MISP
# Replace www-data with whoever is your webserver user (apache/httpd)
sudo -u www-data git pull origin 2.4
sudo -u www-data git submodule update --init --recursive

Then I proceed to misp modules
# Change here the path if needed
cd /usr/local/src/misp-modules
# Update misp-modules requirements
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U -r REQUIREMENTS
# Update misp-modules scripts
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .
# Restart the misp modules
systemctl restart misp-modules

#if needed I update pip 

/datadisk/MISP/var/www/MISP/venv/bin/python -m pip install --upgrade pip

Now that I am running 2.5, can someone validate or update the instructions on how to keep MISP up to date? I am not able to use the GUI way due to proxy for some reason and CLI works fine. 

I just tried to update via CLI for giggles using the above way except changing this one to 2.5

#sudo -u www-data git pull origin 2.5

misp@/var/www/MISP$ cd /usr/local/src/misp-modules

misp@:/usr/local/src/misp-modules$ sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U -r REQUIREMENTS
Traceback (most recent call last):
  File "/var/www/MISP/venv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

misp@:/usr/local/src/misp-modules$ /datadisk/MISP/var/www/MISP/venv/bin/python -m pip install --upgrade pip
/datadisk/MISP/var/www/MISP/venv/bin/python: No module named pip

Another question is why doesnt /usr/local/src/misp-modules get any updates? None of the files have been touched since 2022

/usr/local/src/misp-modules$ ls -l
total 276
drwxrwsr-x 5 www-data www-data   4096 Feb 17  2023 build
-rw-rw-r-- 1 www-data www-data 135794 Apr 17  2022 ChangeLog.md
drwxrwsr-x 3 www-data www-data   4096 Apr 17  2022 docker
-rw-rw-r-- 1 www-data www-data     42 Apr 17  2022 DOC-REQUIREMENTS
drwxrwsr-x 4 www-data www-data   4096 Oct 11  2022 docs
drwxrwsr-x 5 www-data www-data   4096 Oct 11  2022 documentation
drwxrwsr-x 3 www-data www-data   4096 Apr 17  2022 etc
-rw-rw-r-- 1 www-data www-data  34520 Apr 17  2022 LICENSE
-rw-rw-r-- 1 www-data www-data   1122 Apr 17  2022 Makefile
drwxrwsr-x 5 www-data www-data   4096 Apr 17  2022 misp_modules
drwxrwsr-x 2 www-data www-data   4096 Oct 21 10:12 misp_modules.egg-info
-rw-rw-r-- 1 www-data www-data   2599 Apr 17  2022 mkdocs.yml
-rw-rw-r-- 1 www-data www-data   1935 Oct 11  2022 Pipfile
-rw-rw-r-- 1 www-data www-data    100 Apr 17  2022 pyproject.toml
-rw-rw-r-- 1 www-data www-data  31029 Oct 11  2022 README.md
lrwxrwxrwx 1 www-data www-data      9 Apr 17  2022 README.rst -> README.md
-rw-rw-r-- 1 www-data www-data   7257 Oct 11  2022 REQUIREMENTS
-rw-rw-r-- 1 www-data www-data   1028 Oct 11  2022 setup.py
drwxrwsr-x 3 www-data www-data   4096 Oct 11  2022 tests
drwxrwsr-x 2 www-data www-data   4096 Apr 17  2022 tools
drwxrwsr-x 2 www-data www-data   4096 Apr 17  2022 var

### Expected behavior

Here is what I expect the new update procedure to be via CLI

#Updating MISP core
cd /var/www/MISP
# Replace www-data with whoever is your webserver user (apache/httpd)
sudo -u www-data git pull origin 2.5
sudo -u www-data git submodule update --init --recursive

Then I proceed to misp modules
# Change here the path if needed
cd /usr/local/src/misp-modules
# Update misp-modules requirements
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U -r REQUIREMENTS
# Update misp-modules scripts
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .
# Restart the misp modules
systemctl restart misp-modules

### Steps to reproduce

see above

### Version

2.5.1

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Just clicking the update button in the diagnostic page should do the trick. With that said, generally a `git pull origin 2.5 && git submodule update --init --recursive` should do the job. 

Python dependencies in general shouldn't change frequently - and our plan is to automate that part in the future along with composer updates and tie it into the same process that handles the DB updates.

**Comment by iglocska** [comment]
As for MISP modules - generally these are not part of the MISP core and should be updated separately. More often than not these don't reside on the same server as MISP.
