### ISSUE TITLE
Bug: Internal Server error to access 'Search Attributes'

### ISSUE THREAD

**Issue by Ghiyarandhika** [MISP/MISP#10042]
### Actual behavior

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

sudo cat /var/www/MISP/app/tmp/logs/error.log
[sudo] password for : 
2024-11-14 04:02:12 Error: [TypeError] Attribute::__construct(): Argument #1 ($flags) must be of type int, array given
Request URL: /attributes/search/results
Stack Trace:
#0 [internal function]: Attribute->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(171): ClassRegistry::init()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(204): FormHelper->_getModel()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(354): FormHelper->_introspectModel()
#5 /var/www/MISP/app/View/Attributes/search.ctp(2): FormHelper->create()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('...')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(473): View->_render()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(973): View->render()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}

### Expected behavior

showing domain,etc that contain ioc's

### Steps to reproduce

i just following the instalation script from here
https://raw.githubusercontent.com/MISP/MISP/refs/heads/2.5/INSTALL/INSTALL.ubuntu2404.sh

### Version

2.5

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.3.6

### Browser

firefox

### Browser version

132.0.1

### Relevant log output

```shell
2024-11-14 04:02:12 Error: [TypeError] Attribute::__construct(): Argument #1 ($flags) must be of type int, array given
Request URL: /attributes/search/results
Stack Trace:
#0 [internal function]: Attribute->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(171): ClassRegistry::init()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(204): FormHelper->_getModel()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/FormHelper.php(354): FormHelper->_introspectModel()
#5 /var/www/MISP/app/View/Attributes/search.ctp(2): FormHelper->create()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('...')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(473): View->_render()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(973): View->render()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
#13 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @Ghiyarandhika 
I managed to reproduce your issue only when you do a search without setting any filters, was that your use-case? 
If so you can go to the `/attributes/index` until the [fix](https://github.com/MISP/MISP/commit/3851be819fe9aac4169cf29340699fe7247a7922) gets merged.

**Comment by iglocska** [comment]
There was indeed a regression, a bad merge from 2.4 reverted the Attribute->MispAttribute renaming in the search function. Should be fixed now.
