### ISSUE TITLE
Issue with installer script for MISP 2.5 using https://raw.githubusercontent.com/MISP/MISP/refs/heads/2.5/INSTALL/INSTALL.ubuntu2404.sh

### ISSUE THREAD

**Issue by jgthornb** [MISP/MISP#10040]
https://github.com/MISP/MISP/blob/2.5/INSTALL/INSTALL.ubuntu2404.sh
This is the script that has the issue for easy reference. 

When trying to run this script on a fresh install of Ubuntu 24.04 I kept having it fail on me when installing composer. Checking /var/log/misp_install.log it seems there was an issue it thought the "installer is corrupt" and unlinks composer-setup.php. This is on line 195 of the link above. 

195      php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"  &>> $logfile

When checking what $HASH referenced, I could not find it. The only occurrence of this variable is in line 195. But, line 194 caught my eye. 

194     COMPOSER_HASH=`curl -sS https://composer.github.io/installer.sig`

Since this holds the hash to compare against, I decided to change $HASH -> $COMPOSER_HASH and ran the script again. 

This sure enough fixed the issue and allowed for MISP to be installed succesfully. 

I could be wrong, but I believe that $HASH should be changed to $COMPOSER_HASH in line 195 of https://github.com/MISP/MISP/blob/2.5/INSTALL/INSTALL.ubuntu2404.sh. 

Apologies if this is not the place for this, but the other templates did not seem to be the right fit.

**Comment by iglocska** [comment]
Nice catch indeed!
