### ISSUE TITLE
Undo option (especially on delete)

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1005]
It would be great to be able to undo a delete, especially when you remove a list of attributes but also if you delete an event.

**Comment by adulau** [comment]
Maybe quite complex. Maybe this should be more a quite of replay logs. Not sure.

**Comment by iglocska** [comment]
It is indeed a big change, but one that could be doable. We could have a deleted_attributes and deleted_events table each where we move over stuff on delete. I think that the main complexity would come from some related objects that get triggered for deletion (such as tag relations). Definitely something doable in the longer run though.

**Comment by Rafiot** [comment]
An other approach to solve my problem: could you change the background of the 'popup' (make it red for example)? so it is clearly visually different from "accept all the proposals", even if I don't read the content... :)

**Comment by iglocska** [comment]
Welp, this is basically implemented on an attribute level, but currently only admins can restore the attributes.

**Comment by adulau** [comment]
@Rafiot The restore option in the soft-delete solves the issue at the attribute level? can we close the issue or do you really want to undo of delete at event level too?
