### ISSUE TITLE
Support: Curl commands don't seem to work...

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#10050]
### Support Questions

I'm trying to get a basic bro(zeek) download working using this page - 
https://ourmisp/events/automation
Nothing was working so I put in a test event, with one attribute with a test tag "test_tag" and it still doesn't work... 
This is my curl command 

 curl -k --header "Authorization: mispauthorizationkey" --header "Accept: application/xml" --header "Content-type: application/xml" https://ourmisp/attributes/bro/download/all/test_tag

and

 curl -k --header "Authorization: mispauthorizationkey" --header "Accept: application/xml" --header "Content-type: application/xml" https://ourmisp/attributes/restSearch/returnFormat:text/tags:test_tag

Nothing seems to work, I'm not sure what I'm doing wrong?  TBH I'm not sure it isn't the big misp update we just did. 

(I understand that's not the recommended way but that is how the corelight_update service needs to grab the IOC's via that url. )

Appreciate any suggestions! 

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

24.04 

### PHP version

8.3.13

### Browser

Firefox 

### Browser version

132.02

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Not sure if you found the error - but it should be application/json in all of those cases iirc.

**Comment by mathurin68** [comment]
Got it, thank you!
