### ISSUE TITLE
Bug: Galaxy issue

### ISSUE THREAD

**Issue by rahulmanoj98** [MISP/MISP#10058]
### Actual behavior

![image](https://github.com/user-attachments/assets/390e10e7-7290-4123-a05e-0382c9967aa9)

28 custom clusters and 382 default clusters are not loading.
Tried force update also but its not working.

### Expected behavior

Galaxy should all be loaded and reimported when updated.

### Steps to reproduce

in new version 2.5.2 this issue was found in galaxies tab.

### Version

2.5.2

### Operating System

ubuntu

### Operating System version

24.04

### PHP version

8.3

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Everything is working as expected. The warning itself is new, it tells you that you have some tags that come from galaxies created on other instances that are not part of the default galaxies nor the custom ones that you have on your instance. They might be outdated, no longer included galaxy references, or custom ones that the event creators of some of your instance's events have elected not to share. 

Nothing to worry about, this is purely informational, the only reason you didn't see it before was that we never pointed these out on that page prior to the current version.

**Comment by adulau** [comment]
It’s informative and not critical.
