### ISSUE TITLE
Support: Getting a message 'Either your platform is not easily detectable or is not supported by this installer script.'  when installing New Release MISP on Ubuntu 24.04

### ISSUE THREAD

**Issue by dfe1** [MISP/MISP#10053]
### Support Questions

Trying to install MISP Major Release on Ubuntu 24.04 LTS 

`wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M`

then getting the following error:

`Next step: Setting install options with given parameters.
core
modules
    Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/`

Was using the Major Release Install instructions, does this need to be installed on an older Ubuntu version and not 24.01?

### MISP version

2.5

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

7

### Browser

Chrome

### Relevant log output

```shell
~$ wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
/tmp/INSTALL.sh: Permission denied

Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 24.04
Next step: Checking if we are uptodate and checksums match
sha1 matches
sha256 matches
sha384 matches
sha512 matches
--------------------------------------------------------------------------------------------------------------------
Next step: Setting MISP variables
Next step: Setting generic MISP variables shared by all flavours
groups: ‘misp’: no such user
The following DB Passwords were generated..

Next step: Checking for parameters or Unattended Kali Install
Next step: Setting install options with given parameters.
core
modules
    Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Are you tying to install MISP 2.4 or 2.5? The 2.4 installer doesn't support Ubuntu 24.04 iirc, so you want to use this: 

https://github.com/MISP/MISP/blob/2.5/INSTALL/INSTALL.ubuntu2404.sh

**Comment by dfe1** [comment]
I was wondering if I can still run `wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c` 

but replace 'INSTALL.SH'  with 'INSTALL.ubuntu2404.sh'

or do I have to run the install line by line

I tried running that wget line with INSTALL.ubuntu2404.sh replacing INSTALL.SH and get this:

```
Saving to: ‘/tmp/INSTALL.ubuntu2404.sh’

/tmp/INSTALL.ubuntu2404.s 100%[===================================>]  33.79K  --.-KB/s    in 0.004s  

2024-11-21 10:42:42 (9.32 MB/s) - ‘/tmp/INSTALL.ubuntu2404.sh’ saved [34606/34606]

mkfifo: cannot create fifo '/var/log/misp_install.log.pipe': Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 67: /var/log/misp_install.log.pipe: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 66: /var/log/misp_install.log.pipe: No such file or directory
rm: cannot remove '/var/log/misp_install.log.pipe': No such file or directory


███╗   ███╗██╗███████╗██████╗ 
████╗ ████║██║██╔════╝██╔══██╗
██╔████╔██║██║███████╗██████╔╝
██║╚██╔╝██║██║╚════██║██╔═══╝ 
██║ ╚═╝ ██║██║███████║██║     
╚═╝     ╚═╝╚═╝╚══════╝╚═╝     
v2.5 Setup on Ubuntu 24.04 LTS
[STATUS] Updating base system...
/tmp/INSTALL.ubuntu2404.sh: line 171: /var/log/misp_install.log: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 172: /var/log/misp_install.log: Permission denied
[ERROR] Base system update failed. Please check /var/log/misp_install.log for more details.
```
