### ISSUE TITLE
Bug: MISP Worflow Javascript bug

### ISSUE THREAD

**Issue by agrawald** [MISP/MISP#10065]
### Actual behavior

When rendering the workflows screen getting following error, verified the workflows table I can see the records '3'

```javascript
POST https://localhost:8443/workflows/view/3.json 404 (Not Found)
Uncaught ReferenceError: saveFailedMessage is not defined
    at Object.error (workflows-editor.js?v=165:1151:33)
    at c (jquery.js?v=165:2:28327)
    at Object.fireWith [as rejectWith] (jquery.js?v=165:2:29072)
    at l (jquery.js?v=165:2:80070)
    at XMLHttpRequest.<anonymous> (jquery.js?v=165:2:82499)
````
PFA the screenshot

### Expected behavior

The trigger should be rendered properly in the workflows IDE.

### Steps to reproduce

I am running docker container locally

1. Install MISP 2.5.1 with MISP Modules 2.4.198.
2. Open the MISP UI, 
3. Goto Administration -> Workflows -> List Triggers 
4. Double click any trigger

### Version

2.5.1

### Operating System

RedHat

### Operating System version

8

### PHP version

8.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by agrawald** [comment]
PFA the screenshot
![Uploading Screenshot from 2024-11-27 16-04-04.png…]()

**Comment by mokaddem** [comment]
Hello there, thanks you for opening the issue. I tried to reproduce it without success.
Could you try again on v2.5.2? Also, there is something wrong with your screenshot. I cannot open it.
Thanks!

**Comment by agrawald** [comment]
Thanks I will try again

--
Thanks
Dheeraj (DJ) Agrawal

**Comment by agrawald** [comment]
I tried with MISP Ubuntu docker image for 2.5.1 and 2.5.2 and workflow works as expected. However, my custom built RHEL image on UBI8 is not working. We have also customised the root user in docker to be apache user due to security reasons. Do you think I should be providing some permission to folders where the "https://localhost:8443/workflows/view/3.json" is stored? Any pointers will be very helpful.

**Comment by agrawald** [comment]
By the way this is the image of the error I am getting.
![Screenshot from 2024-11-27 16-03-03](https://github.com/user-attachments/assets/c47b133c-19df-49d4-8764-ba8179a6ad7f)

**Comment by agrawald** [comment]
Any updates on my issue? Any pointers or suggestion you want me to look at will help a lot.

**Comment by agrawald** [comment]
I fixed the issue, I was having wrong nginx configuration which was not allowing the json file extension resulting in 404 error code. Thanks
