### ISSUE TITLE
Support: mkfifo: cannot create fifo '/var/log/misp_install.log.pipe': Permission denied

### ISSUE THREAD

**Issue by dfe1** [MISP/MISP#10064]
### Support Questions

In reference to this support ticket. https://github.com/MISP/MISP/issues/10053 
I did try to install MISP 2.5 on Ubuntu 24.04 using this:

`https://github.com/MISP/MISP/blob/2.5/INSTALL/INSTALL.ubuntu2404.sh`

but now I get the below error. I was wondering if I can still run 

`wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh bash /tmp/INSTALL.sh -c`

but replace 'INSTALL.sh' with 'INSTALL.ubuntu2404.sh'

so it would look like this:

`wget --no-cache -O /tmp/INSTALL.ubuntu2404.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.ubuntu2404.sh bash /tmp/INSTALL.ubuntu2404.sh -c`

or do I have to run the install line by line?

I tried running that 'wget' line with 'INSTALL.ubuntu2404.sh' replacing 'INSTALL.sh' and get this (I also ran as sudo and not as sudo):

`Saving to: ‘/tmp/INSTALL.ubuntu2404.sh’

/tmp/INSTALL.ubuntu2404.s 100%[===================================>]  33.79K  --.-KB/s    in 0.004s  

2024-11-21 10:42:42 (9.32 MB/s) - ‘/tmp/INSTALL.ubuntu2404.sh’ saved [34606/34606]

mkfifo: cannot create fifo '/var/log/misp_install.log.pipe': Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 67: /var/log/misp_install.log.pipe: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 66: /var/log/misp_install.log.pipe: No such file or directory
rm: cannot remove '/var/log/misp_install.log.pipe': No such file or directory

███╗   ███╗██╗███████╗██████╗ 
████╗ ████║██║██╔════╝██╔══██╗
██╔████╔██║██║███████╗██████╔╝
██║╚██╔╝██║██║╚════██║██╔═══╝ 
██║ ╚═╝ ██║██║███████║██║     
╚═╝     ╚═╝╚═╝╚══════╝╚═╝     
v2.5 Setup on Ubuntu 24.04 LTS
[STATUS] Updating base system...
/tmp/INSTALL.ubuntu2404.sh: line 171: /var/log/misp_install.log: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 172: /var/log/misp_install.log: Permission denied
[ERROR] Base system update failed. Please check /var/log/misp_install.log for more details.`

### MISP version

2.5

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

7

### Browser

Chrome

### Relevant log output

```shell
Saving to: ‘/tmp/INSTALL.ubuntu2404.sh’

/tmp/INSTALL.ubuntu2404.s 100%[===================================>] 33.79K --.-KB/s in 0.004s

2024-11-21 10:42:42 (9.32 MB/s) - ‘/tmp/INSTALL.ubuntu2404.sh’ saved [34606/34606]

mkfifo: cannot create fifo '/var/log/misp_install.log.pipe': Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 67: /var/log/misp_install.log.pipe: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 66: /var/log/misp_install.log.pipe: No such file or directory
rm: cannot remove '/var/log/misp_install.log.pipe': No such file or directory

███╗ ███╗██╗███████╗██████╗
████╗ ████║██║██╔════╝██╔══██╗
██╔████╔██║██║███████╗██████╔╝
██║╚██╔╝██║██║╚════██║██╔═══╝
██║ ╚═╝ ██║██║███████║██║
╚═╝ ╚═╝╚═╝╚══════╝╚═╝
v2.5 Setup on Ubuntu 24.04 LTS
[STATUS] Updating base system...
/tmp/INSTALL.ubuntu2404.sh: line 171: /var/log/misp_install.log: Permission denied
/tmp/INSTALL.ubuntu2404.sh: line 172: /var/log/misp_install.log: Permission denied
[ERROR] Base system update failed. Please check /var/log/misp_install.log for more details.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dfe1** [comment]
Was able to resolve. It was permission issues.

**Comment by konidohnut** [comment]
Could you help me, how you resolved this problem?
