### ISSUE TITLE
Bug : Curl with new Feeds

### ISSUE THREAD

**Issue by hoelit0** [MISP/MISP#10066]
### Actual behavior

Hi,

I want to fetch SEKOIA.IO's MISP feed. 
I fill the feed form, put my API KEY and somes options. 
![image](https://github.com/user-attachments/assets/5253291d-a9c7-4f6f-ae8f-4bca6652a0f4)

When I try to explore the events remotely, I've an error message : 
![image](https://github.com/user-attachments/assets/820d175e-a1bc-4c14-ad0e-59aea94d0cda)

Error : _Could not fetch manifest for feed: Fetching the 'https://api.sekoia.io/v1/misp-gateway/misp/manifest.json' failed with exception: curl error 6 'Couldn't resolve host name': Could not resolve host: api.sekoia.io_

I don't understand why, maybe there is an option to select in MISP settings.
Maybe can I try to call the API from the container to debug ? Do you have any idea ?

Thanks

### Expected behavior

I want to get updated SEKOIA.IO indicators into MISP feed to implement my CTI.
Goto Home --> List Events

### Steps to reproduce

I am running docker-compose container locally
_docker version : 25.0.4_
_docker-compose version : v2.24.7_

Install MISP 2.5.2 with MISP Modules 2.4.199.

Open the MISP UI,
Goto Sync Actions --> Feeds --> Add Feed

### Version

2.5.2

### Operating System

AlmaLinux

### Operating System version

8.10

### PHP version

20220829

### Browser

Chrome

### Browser version

130.0.6723.69

### Relevant log output

```shell
2024-11-27 09:29:17 Error: Could not get new event uuids for feed 85.
[Exception] Fetching the 'https://api.sekoia.io/v1/misp-gateway/misp/manifest.json' failed with exception: curl error 6 'Couldn't resolve host name': Could not resolve host: api.sekoia.io
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(329): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(217): Feed->getRemoteManifest()
#2 /var/www/MISP/app/Model/Feed.php(1262): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#8 {main}
[SocketException] curl error 6 'Couldn't resolve host name': Could not resolve host: api.sekoia.io
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(89): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Feed.php(2196): CurlClient->get()
#2 /var/www/MISP/app/Model/Feed.php(2156): Feed->getFollowRedirect()
#3 /var/www/MISP/app/Model/Feed.php(329): Feed->feedGetUriRemote()
#4 /var/www/MISP/app/Model/Feed.php(217): Feed->getRemoteManifest()
#5 /var/www/MISP/app/Model/Feed.php(1262): Feed->getNewEventUuids()
#6 /var/www/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /var/www/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#11 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
`[SocketException] curl error 6 'Couldn't resolve host name': Could not resolve host: api.sekoia.io`

Sounds like a network issue. Check if you can resolve the host on your server.

**Comment by hoelit0** [comment]
> `[SocketException] curl error 6 'Couldn't resolve host name': Could not resolve host: api.sekoia.io`
> 
> Sounds like a network issue. Check if you can resolve the host on your server.

I know but on my server I can't resolve the host.

**Comment by adulau** [comment]
If you cannot resolve the host, it's clearly a network issue on your operating system such as incorrect DNS entries, missing network configuration or default gateway. I mean if you cannot resolve host, this has nothing to do with MISP. 

I tested on a MISP instance and a command line:

~~~
adulau@blakley:~$ curl -v api.sekoia.io
*   Trying 2.17.100.193:80...
* Connected to api.sekoia.io (2.17.100.193) port 80 (#0)
> GET / HTTP/1.1
> Host: api.sekoia.io
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html
< Content-Length: 162
< Location: https://api.sekoia.io/
< Expires: Wed, 27 Nov 2024 14:13:23 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Wed, 27 Nov 2024 14:13:23 GMT
< Connection: keep-alive
< Server-Timing: cdn-cache; desc=MISS
< Server-Timing: edge; dur=11
< Server-Timing: origin; dur=15
< Server-Timing: ak_p; desc="1732716803962_34694333_194441550_2590_4122_13_0_-";dur=1
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host api.sekoia.io left intact

~~~

Pray, consult the [arcane manuals of your system](https://www.redhat.com/en/blog/beginners-guide-network-troubleshooting-linux), and perhaps the gods of IT will grant you deliverance.
