### ISSUE TITLE
Feature Request: Bring back support for Ubuntu 22.04

### ISSUE THREAD

**Issue by tens0rcat** [MISP/MISP#10076]
### Is your feature request related to a problem? Please describe.

There is no DISA STIG for Ubuntu 24.04, yet.

### Describe the solution you'd like

Why would you drop support for 22.04 before 24.04 had a published STIG?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
2.4 is still supporting 22.04. You can still use PHP 7.4 for some months. 2.4 and 2.5 are released and aligned together. 

By the way, what is DISA STIG ? and what's exactly the reference to MISP in that standard ?

**Comment by tens0rcat** [comment]
I tried installing 2.4 on 22.04 and it threw a number of errors, I think mostly related to dependencies where it's something like  > v1.3 and < v2.0 where the older versions are not available.  Maybe it works fine without, I haven't had a chance to go back and test.

DISA STIG refers to an organization (DISA — Defense Information Systems Agency) that provides technical guides (STIG — Security Technical Implementation Guide). DISA is part of the Department of Defense (DoD).   All USG Agencies, their contractors, their subcontractors, their suppliers, etc. are required to be compliant.  At the moment, dropping 22.04 support means none of these organizations can use this product.

**Comment by adulau** [comment]
Many organisations including DoD ones are running MISP on 22.04.  If you share a detailed logs or errors log, we could help.

**Comment by tens0rcat** [comment]
Thank you for the offer, and I might have to circle back and take you up on it.  Most of the output from the install script has gone past the scroll back.

However, looking in the docs I see that you support Rocky8.4 & Rocky 8.5 and I should be able to use that in a container.
