### ISSUE TITLE
Bug: Local tagging of event report doesn't work for non site-admin members of host org

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#10079]
### Actual behavior

Local tagging of event report doesn't work for non site-admin members of host org

### Expected behavior

Local tagging of event reports works for non site-admin members of host org (like it does for events and attributes)

### Steps to reproduce

Create a non site-admin user belonging to the host org. Go to an event belonging to another org, which you can see and has an event report (if necessary, create these). View events reports of the associated event and try to add a local tag to one of them.

### Version

2.4.200

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Extra attachments
![image](https://github.com/user-attachments/assets/18e9dcc2-4902-4a78-ad94-a4f63b90f216)

Also note that you get the global tag button as well, despite the fact you can't and shouldn't be able to add a global tag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Fixed by [cba38c058d018af252e7a880ac09bc780235a065](https://github.com/MISP/MISP/commit/2f1c718d2f9f61d2facd5b993bc8a3bb8099f6fa).
Thanks for the report!
