### ISSUE TITLE
Redirect error on users/terms after first login - Debian

### ISSUE THREAD

**Issue by YOLOP0wn** [MISP/MISP#1008]
Hi guys, 

After following the debian installation guide, and have logged in with the default admin account for the first time, i'm getting redirect error. (With or without SSL, same result)

No errors seen in the log file

It seems to be the same issue than here : https://github.com/MISP/MISP/issues/746 

I have try all solution into this topic

Any solution ?

Thanks

**Comment by YOLOP0wn** [comment]
For those who Have the same issue, i have find a solution : 
In /var/www/MISP/app/Config/config.php  --> add "http://" in baseURL 

ex : http://192.168.1.2

You can close this topic

**Comment by Rafiot** [comment]
As requested by reporter, closing.
