### ISSUE TITLE
Bug: [2.4] PHP Fatal error:  Cannot declare class Attribute, because the name is already in use

### ISSUE THREAD

**Issue by juju4** [MISP/MISP#10085]
### Actual behavior

Following refresh of my ansible-role, I get this error with misp 2.4 on ubuntu 22.04 when trying to get an API key (cake userInit -q).
No problem with 2.5 on 24.04.

https://github.com/juju4/ansible-MISP/actions/runs/12216977600/job/34080652426#step:7:19491
```
     "stderr_lines": [
        "PHP Fatal error:  Cannot declare class Attribute, because the name is already in use in /var/www/_MISP/MISP/app/Model/Attribute.php on line 24",
        "PHP Stack trace:",
        "PHP   1. {main}() /var/www/_MISP/MISP/app/Console/cake.php:0",
        "PHP   2. ShellDispatcher::run($argv = [0 => '/var/www/_MISP/MISP/app/Console/cake.php', 1 => '-working', 2 => '/var/www/_MISP/MISP/app', 3 => 'userInit', 4 => '-q']) /var/www/_MISP/MISP/app/Console/cake.php:47",
        "PHP   3. ShellDispatcher->dispatch() /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:66",
        "PHP   4. ShellDispatcher->_getShell($shell = 'userInit') /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:213",
        "PHP   5. class_exists($class = 'UserInitShell') /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:262",
        "PHP   6. App::load($className = 'UserInitShell') /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:262",
        "PHP   7. include() /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php:567",
        "PHP   8. App::load($className = 'AppShell') /var/www/_MISP/MISP/app/Console/Command/UserInitShell.php:6",
        "PHP   9. include() /var/www/_MISP/MISP/app/Lib/cakephp/lib/Cake/Core/App.php:567",
        "PHP  10. require_once() /var/www/_MISP/MISP/app/Console/Command/AppShell.php:23",
        "Fatal Error Error: Cannot declare class Attribute, because the name is already in use in [/var/www/_MISP/MISP/app/Model/Attribute.php, line 24]"
```
One class declared on https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L24
When cloning, set branch to 2.4, only one match too.
No other declaration on https://github.com/search?q=repo%3AMISP%2FMISP+%22class+Attribute%22&type=code but searched 2.5 only.

I see this working about a month ago but in docker container run (above is in bare github runner which is likely more complete)
https://github.com/juju4/ansible-MISP/actions/runs/11770842624/job/32783861269#step:7:2642

### Expected behavior

cake userInit to provide API key

### Steps to reproduce

Execution of ansible roles on Ubuntu 22.04 (will automatically set for MISP 2.4) as per github action.

### Version

2.4.200

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
This sounds like an environment issue. Basically Attribute became a standard class of PHP 8.x+ - meaning that MISP 2.4 is actually trying to redeclare a standard class - this is why we moved it to "MispAttribute" in MISP 2.5.

Now php is kind of funky in a sense that you can run multiple versions of it and tell your webserver (via php-fpm for example) to use php 7.4 when serving MISP, but you need to be careful that you run PHP 7.4 on the command line too.

In ubuntu you can check via `sudo update-alternatives --config php` - this should show you running 7.4, my assumption is that you are on 8.x. Could you double check?

**Comment by adulau** [comment]
@juju4 Could you check? Thank you.

**Comment by juju4** [comment]
That's almost certainly it. github runner images comes by default with php-8.1 (https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2204.json#L304) which is not the case of my manual testing with standard base images or the docker AnsibleCI workflow.
Web side is not affected because libapache2-mod-php7.4 is specifically requested but missing the cli side to avoid this conflict too.
Will do some testing and add some controls in the role.

Note that I had a similar issue with my php hardening that initially was done only on the web side. It created inconsistencies in diagnostics page that is calling php cli for some of its checks. In the end, I applied custom php settings on both web and cli to avoid those.

Thanks @adulau !

**Comment by adulau** [comment]
and thanks to @iglocska as he knew about the issue 🎉
