### ISSUE TITLE
Support: PDO error "There is already an active transaction" after upgrade to 2.5

### ISSUE THREAD

**Issue by Benni0** [MISP/MISP#10106]
### Support Questions

Hi,
I am at a bit of a loss regarding the following problem.
My MISP instance is working without any problems with version 2.4.200.
But if I update to 2.5. I get several "There is already an active transaction" errors.
I have a dockerized setup using the NUKIB/misp docker container and an SAAS Mariadb database where I cannot modify anything.
If I use a mariadb docker container, also version 2.5. works without problems, so the reason for this issue must be the database configuration alongside with the changes between version 2.4.200 and 2.5.
It seems the reason for the issue is, that autocommit is 0 on the database, but why isn't this a problem for 2.4.x versions?

I would appreciate any ideas as to what the problem could be or how I can debug the problem further.
Thank you!

### MISP version

2.5.2

### Operating System

CentOS

### Operating System version

9.5

### PHP version

8.2

### Relevant log output

```shell
PDO error
There is already an active transaction

Error: An Internal Error Has Occurred.
Stack Trace

    APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 2430 → PDO->beginTransaction()
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 1759 → DboSource->begin()
    APP/Model/AdminSetting.php line 37 → Model->save()
    APP/Model/AppModel.php line 3056 → AdminSetting->changeSetting()
    APP/Model/AppModel.php line 2705 → AppModel->__runCleanDB()
    APP/Model/User.php line 2233 → AppModel->runUpdates()
    APP/Controller/UsersController.php line 1274 → User->init()
    [internal function] → UsersController->login()
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 500 → ReflectionMethod->invokeArgs()
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction()
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke()
    APP/webroot/index.php line 107 → Dispatcher->dispatch()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
I guess a change can be the different db engine 2.5 is configured to use, though I don't really see how this could be happening. Could you try switching to the old one?

Just edit your `database.php` file in `/var/www/MISP/app/Config` and change the `datasource` from `Database/MysqlObserverExtended` to `Database/Mysql`?

**Comment by Benni0** [comment]
I've already tried to change the datasource to Mysql and MysqlExtended, but it didn't solve the problem.
I've also tried to add the `PDO::ATTR_AUTOCOMMIT` flag with true and false.
It seems to work, if i execute `SET autocommit=1` within `DboSource.php` before returning the connection.
So I'm currently pretty sure, the reason for the problem is that the default value for autocommit is 0.
Seems that disabled autocommit was supported by the previoud cakephp/PDO version.

I asked for enabling autocommit for all db connections by default, which seems to be possible in this setup and I think this will solve the problem.
I'm going to close this issue, when I can confirm that enabling autocommit solves the problem.

Thank you, very much @iglocska!

**Comment by iglocska** [comment]
That's definitely a good thing to keep on the radar though, figuring that out must have been a pain. Let me know if they can't enable it for you, we can always just add it as a setting in the worst case in MISP directly.

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/commit/07debfd183a665c6b3aad2289712038970f6f555

Could you fetch the latest commit from 2.4 and try again?

**Comment by Benni0** [comment]
> [07debfd](https://github.com/MISP/MISP/commit/07debfd183a665c6b3aad2289712038970f6f555)
> 
> Could you fetch the latest commit from 2.4 and try again?

I guess this comment belongs to #10109

**Comment by Benni0** [comment]
I can now confirm, the reason for this issue is disabled autocommit per default on the MariaDB server. If autocommit=1, MISP runs without problems.
As this is a global setting, I hope this change doesn't have any impacts on other databases on the server - if it does I will have to look for a workaround.

**Comment by Benni0** [comment]
This issue is introduced by PHP8 as with PHP8 PDO checks, if there is already an active transaction when beginTransaction() is called. [Stackoverflow](https://stackoverflow.com/questions/79090042/pdo-changed-behaviour-for-automatic-transactions-with-pdo-in-php-8)

But I have found a simple workaround, which I want to share if someone is also facing this problem in future.
CakePHP sets all setting which are configured for the datasource in database.php. So if you add `'autocommit' => 1`to these settings, autocommit is enabled for each database connection.
TBH I'm not aware of any side effects this setting has, and I also don't know the behaviour of reconnections yet.

Working example:
```
<?php
class DATABASE_CONFIG {
    public $default = [
        'datasource' => 'Database/MysqlExtended',
        'persistent' => false,
        'host' => 'db',
        'login' => 'misp',
        'port' => 3306,
        'password' => 'misp',
        'database' => 'misp',
        'prefix' => '',
        'encoding' => 'utf8',
        'settings' => ['autocommit' => 1],
    ];
}
```
