### ISSUE TITLE
Support: Install fresh MISP 2.5 on pristine Ubuntu 24.04.1

### ISSUE THREAD

**Issue by mbell85** [MISP/MISP#10107]
### Support Questions

Not sure what I'm doing wrong. I've downloaded the install script (https://raw.githubusercontent.com/MISP/MISP/refs/heads/2.5/INSTALL/INSTALL.ubuntu2404.sh) for Ubuntu 24.04.1 but when I 'sudo bash INSTALL.sh', I'm getting the following output:

`sudo bash INSTALL.sh
INSTALL.sh: line 3: $'\r': command not found
INSTALL.sh: line 6: $'\r': command not found
INSTALL.sh: line 12: $'\r': command not found
INSTALL.sh: line 14: $'\r': command not found
INSTALL.sh: line 15: syntax error near unexpected token `$'{\r''
'NSTALL.sh: line 15: `random_string() {
`
Am I not doing something right? I used the auto-installer back when I originally installed MISP 2.4 on Ubuntu 20.04. 

### MISP version

2.5

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

8

### Browser

NA

### Browser version

NA

### Relevant log output

```shell
sudo bash INSTALL.sh
INSTALL.sh: line 3: $'\r': command not found
INSTALL.sh: line 6: $'\r': command not found
INSTALL.sh: line 12: $'\r': command not found
INSTALL.sh: line 14: $'\r': command not found
INSTALL.sh: line 15: syntax error near unexpected token `$'{\r''
'NSTALL.sh: line 15: `random_string() {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Did you by chance edit / copy paste the installer into an editor in Windows? It looks like something converted the line endings from LF to CRLF on your end, which Ubuntu won't like.

**Comment by adulau** [comment]
Obviously the install script is fucked up.

**Comment by mbell85** [comment]
> Did you by chance edit / copy paste the installer into an editor in Windows? It looks like something converted the line endings from LF to CRLF on your end, which Ubuntu won't like.

Yes. That's exactly what happened! lol. Thanks.

**Comment by mbell85** [comment]
> Obviously the install script is fucked up.

Naw! Just leave it to me to find a way to mess it up. :)

**Comment by Sirfrates24** [comment]
after you create the install.sh document, run the following codes
chmod +x install.sh
sudo ./install.sh

**Comment by amgm61** [comment]
hello every, new here
came up with this error
 bash /tmp/INSTALL.sh
mkfifo: cannot create fifo '/var/log/misp_install.log.pipe': Permission denied
/tmp/INSTALL.sh: line 67: /var/log/misp_install.log.pipe: Permission denied
/tmp/INSTALL.sh: line 66: /var/log/misp_install.log.pipe: No such file or directory
rm: cannot remove '/var/log/misp_install.log.pipe': No such file or directory
███╗   ███╗██╗███████╗██████╗ 
████╗ ████║██║██╔════╝██╔══██╗
██╔████╔██║██║███████╗██████╔╝
██║╚██╔╝██║██║╚════██║██╔═══╝ 
██║ ╚═╝ ██║██║███████║██║     
╚═╝     ╚═╝╚═╝╚══════╝╚═╝     
v2.5 Setup on Ubuntu 24.04 LTS
[STATUS] Updating base system...
/tmp/INSTALL.sh: line 171: /var/log/misp_install.log: Permission denied
/tmp/INSTALL.sh: line 172: /var/log/misp_install.log: Permission denied
[ERROR] Base system update failed. Please check /var/log/misp_install.log for more details.
