### ISSUE TITLE
Bug: Audit Logs contain TOTP Seeds

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#10116]
### Actual behavior

Creating a new TOTP will cause an audit log entry containing the seed.
Not a big security issue, since this should be visible for site administrators only.

### Expected behavior

TOTP seed should be redacted like it is done for password changes.

### Steps to reproduce

- Create a new User
- enable TOTP for it
- check Audit Log entrys

### Version

2.4.198

### Operating System

misp-docker

### Operating System version

misp-docker

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks a lot!
