### ISSUE TITLE
Set of tags configured in the user profile

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1014]
Set of tags configured in the user profile as a super tag. When the user tag an event, he sees in the list his own tag profile and just need to click on one to add all the corresponding predefined tags.

**Comment by jaegeral** [comment]
hm you mean combining stuff like "spam - detected by enduser - malicious attachement - commodity"?

A little less "intrusive" would be maybe to provide a list of last used or most used tags to choose from, if you have all tags + taxonomies activated it is getting complicated

**Comment by iglocska** [comment]
Added the possibility to "favourite" tags.
