### ISSUE TITLE
Events not pushed? (again)

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1015]
Hi *,

After diving into the code and adding some debugging output, I now know why my events are'nt pushed to a remote server. In Event.php, the following error is triggered:

$result = $this->restfullEventToServer($event, $server, null, $newLocation, $newTextBody, $HttpSocket);  
if ($result === 403) {
     return 'The distribution level of this event blocks it from being pushed.';
}

This event has a distribution level of "1" ("This community only"). According to the help: "... this includes your own organization, organizations on this MISP server and organizations running MISP servers that synchronize with this server...".

Did I miss something?

**Comment by iglocska** [comment]
Indeed, we just had a discussion about the correctness of the phrasing with @cvandeplas and he is correct, this isn't very obvious, but this community only events will never be pushed. They can however be pulled by an organisation that resides on your MISP. 

So as an example:

MISP A:
Orgs: OrgA (owner), OrgB(sync user), OrgC

MISP B: 
Orgs: OrgB(owner), OrgD

If OrgA creates an event with "This community only" on MISP A, the event will not be pushed and is visible to all organisations on MISP A (OrgA, OrgB, OrgC)

OrgB can initiate a pull on MISP B and receive the event which will become "Your organisation only" to OrgB on MISP B as he is also a member of the MISP A community.

Hope this clears it up.

**Comment by xme** [comment]
Ok, I understand now. To resume:

Events with distribution "This Community Only" will be available to remote instances which come to pull my events
Events wth distribution "Connected Communities" and "All Communities" will be pushed to defined remote instances 

Right?

**Comment by iglocska** [comment]
This is indeed correct.

Also keep in mind that "This community only" and "Connected Communities" get downgraded by one level each hop. 

When you push a Connected Communities event it will become Community only on the remote end. Same result if you pull a Connected Community event.

Community only events cannot be pushed, but if they are pulled they get downgraded to "Your Organisation Only". This ensures that only the host organisation of the instance (which has access to the origin MISP instance) will be able to see the event, as the other organisations are not part of the community.

**Comment by adulau** [comment]
I add a task for me to update the misp-book to include in the description of the distribution level. Thanks for the question ;-)

**Comment by xme** [comment]
You're welcome! :-)
My events are pushed now!

**Comment by adulau** [comment]
Thank you. We can close this issue.
