### ISSUE TITLE
Attach screenshots to events

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1016]
- Create new attribute/attachment type: screenshot
- Have a user setting to show screenshots in-line
  - display the screenshots on the event view if enabled

**Comment by truckydev** [comment]
Hi good fonctionality here

have you an exemple to do that in python ?

**Comment by jaegeral** [comment]
hm but should be careful to not mix it with malicious samples, as some JPEG can contain malcode.

**Comment by truckydev** [comment]
I thought more to do with the API on a defaced website.

**Comment by adulau** [comment]
The screenshots are now displayed in-line and added as standard sample attachment. I suppose we can close this issue and we could re-open it if we really need the new attribute type.
