### ISSUE TITLE
Possiblity to allow users to tag without tag editor roles

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1017]
It can be handy to allow users to assign tags to events without the tag editor role. This should be a server setting to allow it / block it.

**Comment by adulau** [comment]
Or a new permission called Tag setter that can be assigned in the roles ;-)

**Comment by RichieB2B** [comment]
Isn't this implemented with fea6c35140ca30a84d11a52a4f3afc16570bb86c ?

**Comment by iglocska** [comment]
Indeed, this has been implemented already.
