### ISSUE TITLE
Searching on the event level

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1021]
The ability to search on the event level, bringing pack entire event results or event IDs for the matched search would be excellent. You could search on the Description field, bringing back all results which match the particular search filter.

**Comment by adulau** [comment]
Tom, a small question. Have you tried the attribute search with the "Alternate Search Result (Events)" checked? Just wondering if this is not what you are looking for. Thanks.

**Comment by tomking2** [comment]
I had a look, and couldn't see that this satisfied my requirement. I'm looking to search for all events which the Event Info (Description) is searched against. For example, I'm looking to search and bring back all events where the Event Info contains the text "Blacklists".

However, I've currently created a workaround to this by using python to search using /events/index/searchall:Blacklists, and then using PyMISP to get each event against the Event IDs brought back.

**Comment by iglocska** [comment]
Hello there Tom,

I might have completely misunderstood but have you tried the event filters on the event index?
1. Go to the event index
2. Click the little magnifying glass icon on the left upper corner of the event list
3. Select event_info from the dropdown
4. enter the value you want to use as a filter into the text field (such as "blacklists")
5. Click add
6. Click apply

You'll get a filtered event index with the events matching the filter criteria (in your case this would be
/events/index/searcheventinfo:blacklists )

Is this what you were after? Or were you trying to fetch it via the API? If so then you are on the right track, doing 2 lookups is probably your best options (though it would make sense to switch to searcheventinfo from searchall).

**Comment by tomking2** [comment]
Hi Andras,

You've captured what I'm looking for, essentially looking to search against the event info. And yes, I'm looking to automate it through the API.

The only downside with this is that conducting the search only retrieves the Event Info, whereas I'm looking to search and then also get all attributes in the matching events. I then have to loop through each Event ID to bring back the corresponding attributes, which can take a while if I have >100 to loop through for example.

**Comment by iglocska** [comment]
Indeed, I'll look into adding a parameter to the APIs to filter on the
event info!

**Comment by adulau** [comment]
@iglocska still applicable?

**Comment by adulau** [comment]
@tomking2 Did you play with new API (2.4.96 at least.

You can now do the following:

~~~~~
{
    "returnFormat": "json",
    "eventinfo": "%forensic%",
    "limit": "1"
}
~~~~~

Does this solve this issue? if not, feel free to reopen the issue. Thanks a lot.
