### ISSUE TITLE
Failure with enabled feeds after upgrade to 2.4.27

### ISSUE THREAD

**Issue by stevengoossensB** [MISP/MISP#1022]
After upgrade to 2.4.27, I get the error:

2016-03-14 15:00:17 Notice: Notice (8): Undefined index: enabled in [/var/www/MISP/app/Model/Feed.php, line 343]
Trace:
Feed::addDefaultFeeds() - APP/Model/Feed.php, line 343
AppModel::__addNewFeeds() - APP/Model/AppModel.php, line 91
AppModel::updateMISP() - APP/Model/AppModel.php, line 72
AppModel::runUpdates() - APP/Model/AppModel.php, line 433
AppController::beforeFilter() - APP/Controller/AppController.php, line 281
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 247
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 674
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 154
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 92
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 119
[main] - [internal], line ??

It appears that on line 343 of Feed.php, there is `'enabled' => $newFeeds['enabled'],`. Changing it to `'enabled' => $newFeed['enabled'],` resolves the problem. Not sure whether this is correct or a typo.

**Comment by iglocska** [comment]
That is indeed a typo thanks for the heads-up!
