### ISSUE TITLE
Upgrade from hotfix .24 to hotfix .27 throwing errors

### ISSUE THREAD

**Issue by geudrik** [MISP/MISP#1023]
Seeing this after I checked out the .27 hotfix tag. Did I miss a schema change or something?

```
2016-03-16 07:03:15 Error: [MissingTableException] Table feeds for model Feed was not found in datasource default.
Exception Attributes: array (
  'table' => 'feeds',
  'class' => 'Feed',
  'ds' => 'default',
)
```

**Comment by iglocska** [comment]
It should be automatic, but indeed you can get that as a one time error
message, i I'll look into it. Does it go away if you refresh?

**Comment by Rafiot** [comment]
Do you still have the issue?

**Comment by geudrik** [comment]
Yep! Looks like we're good to go!

On Wed, Mar 23, 2016 at 6:04 AM, Raphaël Vinot notifications@github.com
wrote:

> Do you still have the issue?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MISP/MISP/issues/1023#issuecomment-200277648

## 

Pat Litke
Arctic Industries
001 802 598 9371
https://arcti.cc

**Comment by geudrik** [comment]
Forgot to close, my mistake
