### ISSUE TITLE
Limit in file upload (number of files)

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#1025]
Browser: Safari, others?

When uploading multiple files (for instance: 400) as attachment, only a few files are actually uploaded (ca. 20). The others are silently dropped.

**Comment by truckydev** [comment]
Hi 
have you a sample of your code to uploade file as attachement and not as "malware sample" ?

Thx :)

**Comment by iglocska** [comment]
Turned out to be a php.ini setting (max_file_uploads)
