### ISSUE TITLE
Edit server in "sync actions" will remove certificate file and auth key

### ISSUE THREAD

**Issue by grolinet** [MISP/MISP#1027]
Whenever you edit (for example change the push checkbox) a Server in the sync action (Sync Actions -> List Servers -> Edit), and hit Submit, the auth key and the certificate file (pem) will be removed.

It's not really breaking the application since you can re-upload the pem file and add the auth key again, but it's annoying. :)

Anyway, thanks for the tool and keep the good work up.

**Comment by adulau** [comment]
Thank you for the notification.

Indeed that is the case for the pem file. For the auth key, it should not be the case.

**Comment by grolinet** [comment]
Ah yeah, you're right. 
i was confused by the empty auth key field, just checked again, only the pem file is affected.

**Comment by adulau** [comment]
The bug of pem file case is there.

**Comment by iglocska** [comment]
It's fixed now.
