### ISSUE TITLE
Not possible to import feed events

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#1029]
Hi,

When I import an event from a feed (Preview > Action : save event on instance) nothing happens. 

I can see all the events in the feed, get the details etc. The event-data is coming in (seen on network capture) but it's not listed in the event list afterwards.
Tested with 2.4.27.

Any pointers where I can start looking?

thanks,

koen

**Comment by iglocska** [comment]
Hello Koen, will test it over the weekend. Weird.

**Comment by cudeso** [comment]
This boils down to an older upgrade from 2.3 to 2.4 that failed. The upgrade was missing the 'org' fields. Tested on an identical host but with different DB and everything worked flawlessly.

Will open another issue for the upgrade to see if this problem can be recovered.
