### ISSUE TITLE
Upgrade from 2.3 to 2.4 went wrong and missing org field

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#1030]
Hi,

During an -older- upgrade from 2.3 to 2.4 something must have gone wrong. I did

```
mysql -u root -p misp < /var/www/MISP/INSTALL/upgrade_2.4.sql
rm /var/www/MISP/app/tmp/cache/model/myapp*
rm /var/www/MISP/app/tmp/cache/persistent/myapp*
```

But after running the upgrade script through admin-tools the logs show

```
{"queue":"default","id":"553f22c94b5c187978697d62b41591a2","class":"AdminShell","args":[["jobUpgrade24","55480","1"]]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'org' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'org' in 'field list'","job_id":"553f22c94b5c187978697d62b41591a2","time":181,"worker":"hermes:16814"}
```

Under Organisations nothing seems unusual, both local (1) and remote (2) are listed. But none of the events have an org or owner-org. This is something similar as what I reported earlier (during FIRST-TC). I assume I didn't check enough for errors after running the 2.3->2.4 cleanup script.

The MISP db only contains a limited number of events. Are there any actions I should take when I
- export the individual events from the broken db as misp-xml
- re-init a new empty database
- import the table 'users'
- import the individual MISP-events xml data

Of course any other tips to fix this more quickly are helpful.

Thanks,

koen

**Comment by iglocska** [comment]
Hello Koen,

Not sure what happened there. The most important thing to check is whether the organisation info still exists for your events - could you check your events table if the org field was removed? 

What happens normally during the update: MISP creates org_id and orgc_id columns for all tables that have org/orgc columns, takes the strings from the old fields and creates organisation objects out of them. Once that is done, the IDs created for the organisation objects are inserted into the org_id and orgc_id fields.

Thi sis the crucial step where the admin needs to check if there were any issues and if not, the cleanup script finalises the upgrade by removing the old org fields. 

If the cleanup was not run then it is indeed possible to recover the organisations that the events belong to, so if you could run the following in mysql:

describe events; 

Does the result include an orgc and org column?

**Comment by cudeso** [comment]
It includes org_id and orgc_id

```
| org_id              | int(11)     | NO   | MUL | 0       |                |
| orgc_id             | int(11)     | NO   | MUL | 0       |                |
```

They are set to 0.

```
mysql> select org_id, orgc_id from events;
+--------+---------+
| org_id | orgc_id |
+--------+---------+
|      0 |       0 |
|      0 |       0 |
|      0 |       0 |
|      0 |       0 |
```

**Comment by iglocska** [comment]
Argh. If the org and orgc columns are removed by the cleanup script then there is no easy way to recover the organisations that they belong to... Do you have a backup of the events table from before the migration?

**Comment by cudeso** [comment]
I'm afraid not. At least not one that is easily accessible. 
Because it only consists of about 25 events I can do some manual editing. Just need to be sure what and where to edit. Normally all events should belong to the "local" org, it has not imported events from an external source.

**Comment by iglocska** [comment]
Ah ok, in that case just set all orgc_id and org_id to the it of the local org. So if local org's ID = 1 then:

update `events` set `orgc_id` = 1, `org_id` = 1;

**Comment by cudeso** [comment]
Fixed it by also setting set org_id =1 in the users table.
Doing org_id=1,event_org_id=1 in the shadow_attributes fixed feed-import for individual events.
