### ISSUE TITLE
REST add event with invalid attribute

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#104]
Bug / behavior: 
- attribute that does not validate correctly is silently dropped when added using REST API

To reproduce:
1/ Create a new event with attributes using the REST API. using /events/ as url
2/ Make sure that one of the attributes contains invalid data that will not validate based on the model.  (md5 sum with incorrect size for example)
3/ Notice that the event and valid attributes are created. The invalid attribute is not created. However there is no REST/xml message to the user/tool that one invalid attribute was dropped.

The client/tool could detect it by comparing the XML of the just created event with what it uploaded.
However the question is: do we want to keep this behavior or not?

**Comment by Rafiot** [comment]
Pretty sure this one is fixed.
