### ISSUE TITLE
Error 500 after mutliple md5 upload via API

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1043]
Hi,

I try to upload mutliple MD5 via the API in python
I use

```
for myMD5var in file:
    misp.add_hashes(event,'Payload installation',None,myMD5var)
    time.sleep(1)
```

After some upload (about 60), I have a shell error : 

```
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 408, in add_hashes
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 385, in _send_attributes
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 164, in _check_response
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://xxxxxxxxx/events/42
```

Next, when i try to view the event 42 (by web browser) I have an error 500.
I have to back and list all events and destroy it.

My apache log is 
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in ./MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 1182`

**Comment by Rafiot** [comment]
Seems that the memory limit of PHP is exhausted. Can you try to increase it?

**Comment by truckydev** [comment]
I change de default value (128M) to 256M and now it's all right.
Thx

**Comment by Rafiot** [comment]
excellent :)

**Comment by TheDr1ver** [comment]
I had a similar issue to this and just wanted to add that even once the PHP memory has been upped to a reasonable limit, if you're adding an event with a very large amount of attributes (in my case, ~5k), you'll also want to check the `max_execution_time` in php.ini and potentially set it to something like 300 (rather than the default of 30 seconds).
