### ISSUE TITLE
Undefined index for specific types

### ISSUE THREAD

**Issue by 9b** [MISP/MISP#1046]
When returning certain fields from a MISP extension, I am getting an error about an undefined index. This happens when I reference SSL or WHOIS specific types. Here's an example:

`
Notice (8): Undefined index: x509-fingerprint-sha1 [APP/View/Events/resolved_attributes.ctp, line 58]`

![screen shot 2016-03-24 at 3 47 36 pm](https://cloud.githubusercontent.com/assets/505557/14033501/11842656-f1d8-11e5-827c-a870b6d51580.png)

**Comment by klingsor83** [comment]
I have the same issue adding sha256 attributes.

**Comment by iglocska** [comment]
This one has been resolved a while ago.
