### ISSUE TITLE
Add full type support for WHOIS

### ISSUE THREAD

**Issue by passivetotal** [MISP/MISP#1047]
Within the current spec., WHOIS data is limited to email, phone, name, registrar and creation date. Ideally, there would be a type for each value inside of a WHOIS record. As a reference, anything listed here would be of value:

https://api.passivetotal.org/api/docs/#api-WHOIS-GetV2WhoisQuery

**Comment by aaronkaplan** [comment]
Wouldn't it make sense to rather support RDAP here?

Frankly speaking I am also not sure if Whois info per se is an IoC and should be stored in MISP (if I understood you correctly). Maybe just a link / UrI to some whowas service would be sufficient? 

Just thinking loud...

---

iPhone, iTypos, iSorry

**Comment by 9b** [comment]
I am not quite sure what RDAP is, but I can understand now viewing all aspects of the WHOIS record as indicators. That said, MISP currently cherry-picks a couple attributes to use as indicators and I think the following would fit/compliment what currently exists:
- Nameservers (these are great for pivots when unique)
- Updated time (good to know when things change)
- Expire time (helpful if the analyst wants to try and snag the infra)
- Consolidation of all filled in details of the record (address, country, etc.)

The last bullet is a bit relative, but given MISP already supports name, phone and email, it would also  make sense to support the full address and organization. While not always great leads (seldom they are), there have been times when those points could help shed light on who was behind an attack or at the very least act as good correlation.

**Comment by adulau** [comment]
Thank you for the idea @9b I will update the current whois object:

https://github.com/MISP/misp-objects/blob/master/objects/whois/definition.json

If you see something else feel free. The idea is to have the new object in the next version of MISP.

**Comment by 9b** [comment]
Is it better for me to submit pull requests to the misp-objects repos?

**Comment by elhoim** [comment]
@9b RDAP is [Registration Data Access Protocol](https://about.rdap.org/) which is supposed to replace whois. Some registries are already supporting it

**Comment by adulau** [comment]
Objects are now implemented in MISP 2.4.80 and a default whois object exists. Feel free to reopen if you have any issue. Or feel free to update the misp-object template for whois.
