### ISSUE TITLE
Add full type support for SSL certificates

### ISSUE THREAD

**Issue by passivetotal** [MISP/MISP#1048]
SSL certificate attributes are represented with a generic type of "ssl-cert-attributes" which does not lend themselves well to future searches. Ideally, SSL certificate types would support the following types as listed here in our API response:

https://api.passivetotal.org/api/docs/#api-SSL_Certificates-GetV2SslCertificateQuery

**Comment by elhoim** [comment]
Linked to/duplicate of #20 & #420.
Aligning those two to release-2.5-hotfix

**Comment by adulau** [comment]
It should be checked against https://github.com/MISP/misp-objects/blob/master/objects/x509/definition.json to see if we are missing some critical elements with https://api.passivetotal.org/api/docs/#api-SSL_Certificates-GetV2SslCertificateQuery

**Comment by adulau** [comment]
Objects are now implemented in MISP 2.4.80 and a X.509 object default exists.
