### ISSUE TITLE
REST add event with invalid event data

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#105]
Behavior:
- create an event with invalid data , for some fields the data will be silently ignored, for other fields an incorrect error is shown (already exists)

To reproduce:
1/ Create a new event using the REST API. using /events/ as url
2/ Make sure that the date contains invalid data that will not validate based on the model. 
3/ Notice the following incorrect error message
```
<response>
    <name>Invalid event, it already exists.</name>
    <url>/events.xml</url>
</response>
```
4/ try again with invalid data for the distribution field. The event will be created with the default value. 

Two issues:
1/ inconsistent behavior of defaulting to "valid" data in some cases, and throwing an xml error in other cases. 
2/ error thrown is incorrect.

**Comment by elhoim** [comment]
Is this handled now?

**Comment by iglocska** [comment]
invalid data will now just be thrown away but the response is still not great.
