### ISSUE TITLE
NATO.png is a JPEG file

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1051]
I'm not sure this is intended, but just in case it is not: app/webroot/img/orgs/NATO.png is actually a JPEG file:

```
$ identify NATO.png
NATO.png JPEG 50x50 50x50+0+0 8-bit DirectClass 1.23KB 0.000u 0:00.000
$ file NATO.png 
NATO.png: JPEG image data, JFIF standard 1.01, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 60"
```

The same goes for NCIRC.png which is the same exact file at NATO.png

**Comment by adulau** [comment]
Interesting. Thank you. We will check the file (just in case ;-) and update it.
