### ISSUE TITLE
Can no longer view event details since updating from v2.4.x to v.2.4.33. 

### ISSUE THREAD

**Issue by xg5-simon** [MISP/MISP#1052]
Can no longer view event details since updating from v2.4.x to v.2.4.33. 

Generates "Error: An Internal Error Has Occurred."

**Comment by cvandeplas** [comment]
I think I have the same problem, but it's not only related to the event details page.
@xg5-simon Could you activate debug output (at least for admin) and confirm you have the same issue?

```
Notice (8): Undefined index: perm_tag_editor [APP/Controller/AppController.php, line 285]
AppController::beforeFilter() - APP/Controller/AppController.php, line 285
ThreadsController::beforeFilter() - APP/Controller/ThreadsController.php, line 24
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 676
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

I guess this is because of a missing field in the db.

**Comment by iglocska** [comment]
Hmm looks like something went wrong with the update process. Could you git pull, log out and log back in again?

**Comment by cvandeplas** [comment]
nope, my git pull was done 5 minutes ago, did again now, logout/login multiple times.

**Comment by iglocska** [comment]
What the hell. Could you try the following?

rm /var/www/MISP/app/tmp/cache/models/myapp*
rm /var/www/MISP/app/tmp/cache/persistent/myapp*

**Comment by cvandeplas** [comment]
This solves the problem indeed.
Could we force the caches to be cleared after the 'update-process' ?

**Comment by xg5-simon** [comment]
Will post the logs in 12 hours or so once I'm back on site and have access
again.

**Comment by iglocska** [comment]
Git pull if you still have issues, there is a fix that will execute on the next page load. So 2 page refreshes should have the issue resolved after a git pull. 

If it doesn't solve it, there is a new cleanup function at the bottom of the diagnostic page.

I'll close the issue for now, let me know if you still have trouble.

**Comment by xg5-simon** [comment]
@iglocska confirmed working. Cheers for the quick response.

**Comment by iglocska** [comment]
Excellent news, let me know if you run into any other issues!
