### ISSUE TITLE
perm_tag_editor does not give tag editor rights

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1053]
After upgrading to 2.4.33 I (admin role) lost the ability to create new tags. /roles/admin_index shows the new perm_tag_editor flag is missing on all roles. Adding the flag using the web UI does not seem to add them to the role. There are no hints in error.log

**Comment by RichieB2B** [comment]
Looking at the roles table in MySQL toggling the "Perm Tag Editor" box in the UI does toggle the perm_tag_editor flag. But it does not show in /roles/admin_index and does not actually give tag editor rights in MISP.

```
mysql> select id,name,perm_tagger,perm_tag_editor from roles;
+----+-----------------+-------------+-----------------+
| id | name            | perm_tagger | perm_tag_editor |
+----+-----------------+-------------+-----------------+
|  1 | admin           |           1 |               1 |
|  2 | Org Admin       |           1 |               0 |
|  3 | User            |           0 |               0 |
|  4 | Sync user       |           0 |               0 |
|  5 | Automation user |           0 |               0 |
|  6 | Read Only       |           0 |               0 |
+----+-----------------+-------------+-----------------+
6 rows in set (0.01 sec)
```

**Comment by iglocska** [comment]
It is an issue with the upgrade procedure, the cache is not correctly
cleaned (or not at the right moment) - I am looking into it, for now,
please go to the site admin settings -> diagnostics and run the clean cache
script at the bottom of the page. I'll try to have something more sensible
out for it later today.

**Comment by RichieB2B** [comment]
That worked, thanks.
