### ISSUE TITLE
Adding comment to multiple attributes

### ISSUE THREAD

**Issue by amuehlem** [MISP/MISP#1055]
when trying to add a comment to multiple attributes, after updating only the loading spinner is shown, but the comments are not added to the attributes.

Tested v2.4.17 and 2.4.33

**Comment by iglocska** [comment]
Hmm, weird, it is working for me. 

Is your MISP.baseurl set correctly in your instance's settings? Also, could you check what is being returned by the AJAX query? (press F12 and check the console if the request returns an error).

**Comment by amuehlem** [comment]
seems to be the same issue as https://github.com/MISP/MISP/issues/741, will post my answer there.

**Comment by amuehlem** [comment]
Hi All

I still have the same issue, tested on a debian and centos host with MISP 2.4.42. Is there an easy way to debug why this requests are black-holed?

2016-05-06 11:15:37 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/editSelected/2
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by Rafiot** [comment]
Hi, sorry for the late answer, do you still have the problem?

**Comment by amuehlem** [comment]
Unfortunately yes, I just checked with version 2.4.47. Do you have any ideas where to look for the reason for the "the request has been black-holed"?

**Comment by iglocska** [comment]
Could you check if your instances base URL seeing is correct?
Administration - server settings - MISP tab - baseurl

**Comment by amuehlem** [comment]
Yes, the setting is correct, I'm using an alias and not the hostname. I assume this should not be a problem or could this be the root of the cause?

**Comment by iglocska** [comment]
Hmm. It could be, though not sure how. Basically MISP uses the expected
form submit URL while creating the card hash, which is based on the baseurl
vs what you are actually accessing (kind of). If your firm gets submitted
to a different URL it will blacks the request.

Do you have a trailing dash after the base URL by any chance?

**Comment by amuehlem** [comment]
No, no trailing slash.

**Comment by iglocska** [comment]
Will look at ways to debug it once I get to a PC. Maybe a thing to check if
whether the request is fired at the correct URL via the debug told of your
browser. Will have more details soon

**Comment by adulau** [comment]
We will close this issue. If this is no fixed, feel free to reopen the issue.
