### ISSUE TITLE
[Idea] make an event out of an eml

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1059]
Would like to get feedback on the following user-story:

Imagine you have an eml file, maybe with attachements, and you want to create an event for it, stuff like sender-mail adress, destination, maybe target-email, attachements, body of the mail etc could be extracted automatically.

Opinions?

**Comment by iglocska** [comment]
Definitely something we need sooner or later. Once we have the import module this could be an excellent module.

**Comment by elhoim** [comment]
Duplicate of https://github.com/MISP/MISP/issues/143
