### ISSUE TITLE
Ability to create an email alert watchlist based on tags or other attributes 

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1060]
It would be excellent if there was a further email alert capability which allowed you to select alert rules on tags and attributes (thinking Threat Actor), so that if a new event was tagged with the selected tag (or uses a particular Threat Actor name), an email alert would be sent out to the user.

This would be useful when users do not want an alert for every event published, but are only interested in particular threat actors or tags.

**Comment by iglocska** [comment]
For the alerting there are several ideas that are floating around that would cater to interesting use cases, I think what we need to do at one point is for the users to set up a series of rules when they want to be alerted.

So maybe we can start tracking them in this thread and see what everyone comes up with and then we select a sane list of settings from that. So for now what we have:
- Alert on certain tags being attached to events
- Alert on new correlations found to an event created by my organisation

**Comment by elhoim** [comment]
- Alert on IP from a list of ranges defined by the user (for example own IP ranges)
