### ISSUE TITLE
Add another distribution level

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1061]
It would be nice to have another level for distribution "This server only"

User story behind:

Imagine you have several teams working on the same misp instance but they have different tier levels.

Level 1 has to create the misp event and at a certain point they will bring it up to the next level. That way you could then create an org for every tier.

But these events shall not be shared with other servers.

The reason not to use one org for all is that tier 1 should not see every event from the past.

Ideas?

**Comment by iglocska** [comment]
There are ways to do that already:
1. The simplest solution is to use "this community only" which will stay on the instance unless someone pulls it from a remote. If you have an internal instance that you want to keep your data on, set everything to community only and have a one way synchronisation to the other instance. Community only events never get pushed. 
2. If this is not a solution, you can create a sharing group that does that. Simply set the current instance to "all orgs" and don't add anything else.

**Comment by jaegeral** [comment]
ok stupid me, sharing group is what I was looking for. Expected it to be at administrative tools instead of global actions.

**Comment by iglocska** [comment]
Not stupid at all, I really need to rearrange some of the things / document it better, it's definitely not obvious :) 

You not finding it is good feedback about it not being clear enough. I'll close the issue for now, let us know if you run into any issues/questions.
