### ISSUE TITLE
Add XMPP support for notifications (instead of emails)

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1064]
I had a meeting with a future user of the platform and they use XMPP internally and asked if we were planning to support XMPP for notification.

I guess it won't happen anytime soon, but let's keep track of it.

**Comment by adulau** [comment]
Maybe this could be part of a notification project which is plugging on the ZMQ pub-sub channel?

**Comment by Rafiot** [comment]
zmq is more appropriate.
