### ISSUE TITLE
JSON structure inconsistencies and bug

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1065]
I put both remarks in one issue as they can be both fixed at the same moment by restructuring the JSON format, and have both the same collateral damage by fixing them. The collateral damage is breaking multiple scripts using the json object.

First the small bug: the event attributes of a related event are an array in an array. To access the RelatedEvent ID of the first related event you need to: `Event['Event']['RelatedEvent'][0]['Event'][0]['id']`.
While it should have been `Event['Event']['RelatedEvent'][0]['Event']['id']`.
However this small bug will be removed if the below remark is followed.

Currently the JSON RelatedEvent object is not following the same structure as the main Event structure. 
To clarify, the main Event structure is:

```
    "Event": {
        "Attribute": [  // array of Attributes {}
        ],
        "Org": {
        },
        "Orgc": {
        },
        "RelatedEvent": [   
            {
                "Event": [{
                    "date": "2016-04-08",
                    "distribution": "0",
                    }
                ],
                "Org": {
                },
                "Orgc": {
                }
            },
            {} // next related events 
        ],
        "date": "2016-04-07",
        "distribution": "3",
        "id": "3818",
        "info": "foobar",
        ...
    }

```

Notice how the RelatedEvent subobject is not following the same structure as the Event for the elements like 'date', 'distribution'.

It should be something like this 

```
    "Event": {
        "Attribute": [  // array of Attributes {}
        ],
        "Org": {
        },
        "Orgc": {
        },
        "RelatedEvent": [   
            {
                "date": "2016-04-08",
                "distribution": "0",

                "Org": {
                },
                "Orgc": {
                }
            },
            {} // next related events 
        ],
        "date": "2016-04-07",
        "distribution": "3",
        "id": "3818",
        "info": "foobar",
        ...
    }

```

**Comment by iglocska** [comment]
I see now what you've meant, I thought it was simply a matter of Event being a list, but indeed, the "Event" object itself is either not needed within RelatedEvent, or if we have it, we should have the Org and Orgc contained within. I need to check what impact changing this would have on things such as MISPego

**Comment by Rafiot** [comment]
And PyMISP, this one will need to be fixed too

**Comment by iglocska** [comment]
Are you using the related events for anything in PyMISP?

**Comment by Rafiot** [comment]
Nevermind, not in pymisp but in viper: https://github.com/viper-framework/viper/blob/b973c3de53f220cf0218229d4f5bc1b819638d29/viper/modules/misp.py#L320

**Comment by cvandeplas** [comment]
Is there any collateral damage for the sync?

**Comment by iglocska** [comment]
None for the sync.

**Comment by tomking2** [comment]
There should be no problems with the MISPego transforms for Maltego (ones which push content up) - They don't mess around with anything under Related Attributes. Not sure about the other set of Maltego MISP transforms (ones to pull content down).

**Comment by iglocska** [comment]
Ah my bad, I've meant the other transforms :)

**Comment by adulau** [comment]
I don't see much tools currently using Related Attributes. So it should be better to update it as soon as possible before more tools rely on it. It was introduced recently for the viper module.

**Comment by tomking2** [comment]
@iglocska Ah ok :), just checked and nope; not being used for other Maltego transforms. Only searches and filters through first level, doesn't touch Related Attributes.

**Comment by iglocska** [comment]
That is excellent news, thanks for looking into it! I'll push the changes
soon!
