### ISSUE TITLE
error with tag

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1067]
I refere to this issue on pymisp : 

https://github.com/CIRCL/PyMISP/issues/35

I have a error 500 on /events/addTags

I m up to date with : 
git pull and pymisp ^^

**Comment by iglocska** [comment]
Just tested it and I can't reproduce the issue.

What I tried:

Attempt 1. Add tag via MISP's API:

POST to https://mymisp/events/addTag
body: {"request":{"Event":{"tag":"testtag", "id":2836}}}
Result: Event 2836 gets the testtag attached

Attempt 2. Add via PyMISP:

```
 event = misp.get(2835)
 misp.add_tag(event, 48)
```

 Result: Event 2835 gets tag with ID 48 attached

Could you paste the request you are passing to /events/addTags?

**Comment by adulau** [comment]
@truckydev Any feedback? Thank you.

**Comment by truckydev** [comment]
sorry for the late response.

The resolve is in the first link :)  
My "app/Config/Controler/AppControler" was not the last.  
I need to integrate this feature (kerberos auth) https://github.com/MISP/MISP/pull/976   

that's why my AppControler don't change.

I try to make this as plugin.
Have you a tutorial to dev some plugin ?
I try to do the same as CertAuth (app/Plugin/CertAuth) but bon't work.

I have open this issues too https://github.com/CIRCL/PyMISP/issues/36
^^

**Comment by elhoim** [comment]
@truckydev do you consider this fixed?

**Comment by truckydev** [comment]
Yes,

All green for me.
Thanks
