### ISSUE TITLE
[UI] Polulate using freetext in left Event Menu etc

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1068]
Found it very hard to find the options explained in:

https://github.com/MISP/misp-book/blob/9e1dfe88482183766fcec26fc828ff1a885153d9/using-the-system/README.md#add-attributes-to-the-event

![Image of Options](https://github.com/MISP/misp-book/blob/master/using-the-system/figures/attribute_tools.png)

Does it make sense to have hyperlinks below Polulate from OpenIOC, ThreatConnect etc?

At the moment it only opens a popup.

People using Misp for a shorter time asked me how to use the freetext importer, so I guess there is a need to impove Usability.

**Comment by iglocska** [comment]
Yeah that would indeed make sense. In the long run we want to remove both the OpenIOC and ThreatConnect buttons and have an "Import" button that will tie into the import modules, but temporarily I can add a button there for the freetext until then.
