### ISSUE TITLE
Message posts should keep track of the posting organisation

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1071]
Right now discussion messages are only related with the posting user and through it indirectly with the posting organisation. If the user is removed the message loses all association with the posting organsiation.

Solution: Add a new field to the messages (org_id) and have an update script auto-popupate it. org_id 0, for users that have been removed should simply show "deactivated user".

**Comment by rommelfs** [comment]
This works just fine with deactived users and can be closed.
