### ISSUE TITLE
sharing groups list in the Distribution select box

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1074]
From users-feedback it was identified that the sharing groups being in a separate list was confusing to users.

Wouldn't it be more natural to have the sharing groups in the same list as the traditional distributions? (when encoding an event / attribute)

**Comment by iglocska** [comment]
I think that the most common use-case is to still use the default
distribution settings, with sharing groups being the less frequently used
setting, so not sure. This would mean that the distribution list would be
huge for everyone.

**Comment by cvandeplas** [comment]
Having a combo box with the orignal distributions at the top, 
then a separator style `----- Sharing Groups-----` and the SG below would be great.
In our case we almost stopped using the default distributions and almost only use SGs.

**Comment by adulau** [comment]
I think this is based on the use-case of the organization. Maybe the best would be to have an option to change the standard behaviour. The default approach is nice because of promoting sharing among MISP instance should be a default behaviour.

**Comment by cvandeplas** [comment]
I'm not sure that allowing multiple views on this is a good idea. It definitely increases the complexity of the code (admin, page display, form submit processing) and thus clutters code.

I'm marking this as wontfix for now, but if further community feedback increases we might reconsider this.
