### ISSUE TITLE
Short name for tags

### ISSUE THREAD

**Issue by klingsor83** [MISP/MISP#1075]
With the inclusion of new taxonomies, the tags are too long and the visualization in the list events and the detail event isn't usable because they take too much space. Is it possible to create a short name for the tag? 

When the structure of the tag name was 

namespace:predicate="value"

Maybe, the short name could be the value of the taxonomy and, if you put the mouse over the tag, it shows in the title the complete tag... 

Regards

**Comment by iglocska** [comment]
There is a setting that hides the tag name and only shows the colour, you can change it in your MISP settings:  MISP.full_tags_on_event_index

**Comment by klingsor83** [comment]
Yes, I know but I think this isn't very usable. 

In this example, we modified the file app/View/Events/index.ctp with to show only the value of the taxonomy:

I know that this isn't a clean solution... 
You can see the example in the attached screenshot: ![tags](https://cloud.githubusercontent.com/assets/3429744/14432404/5419b23e-000a-11e6-9d1c-b0dac65e8aca.png)

As you can see, in the list you have a tag with a short name with the minimal and enough information to know the category of an event.

Thanks for your quick response.

**Comment by iglocska** [comment]
Pushed a change to the setting that does the same thing, MISP.full_tags_on_event_index now has 3 settings.
