### ISSUE TITLE
sha-2 entries incorrect under Search Attributes GUI (linked to Issue #396)

### ISSUE THREAD

**Issue by david74552** [MISP/MISP#1086]
Running MISP version 2.4.33.

There appears to be an issue with the newly created SHA-2 types within part of the GUI.

Under the "Search Attributes" drop down menu "Type",
these entries are incorrectly listed in the GUI:
'sha-224',
'sha-384',
'sha-512',
'sha-512/224',
'sha-512/256',
'filename|sha-224',
'filename|sha-384',
'filename|sha-512',
'filename|sha-512/224',
'filename|sha-512/256'

They should appear as:
'sha224',
'sha384',
'sha512',
'sha512/224',
'sha512/256',
'filename|sha224',
'filename|sha384',
'filename|sha512',
'filename|sha512/224',
'filename|sha512/256'

This bug affects the ability to search based on these attributes using the GUI.

**Comment by Rafiot** [comment]
Related - #396

**Comment by iglocska** [comment]
Good catch, thanks for the heads-up!
