### ISSUE TITLE
Unable to Enable Server Settings

### ISSUE THREAD

**Issue by yuliangchew** [MISP/MISP#1087]
Dear MISP Support, 

The above subject is referred. I installed MISP on CentOS 7. At http://localhost with the default admin user name n password that is provided, i managed to logged in. A warning was shown to me which is "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)", so I tried to follow the instruction to enable it, but i am not able to do so. 

please advise

regards,
Yu Liang

**Comment by iglocska** [comment]
Could you check the permissions on /var/www/MISP/app/Config/config.php? MISP has to be able to write to that file. Let me know if changing that doesn't solve it!

**Comment by yuliangchew** [comment]
Dear iglocska,
1. in this section right? sorry i am new to MISP. under which section to determine it has the ability to write to that file? 
2. during the installation, it asked us to do configuration for basurl, what to add there?

'MISP' =>
  array (
    'baseurl' => '',
    'footermidleft' => '',
    'footermidright' => '',
    'org' => 'ORGNAME',
    'showorg' => true,
    'background_jobs' => true,
    'cached_attachments' => true,
    'email' => 'email@address.com',
    'contact' => 'email@address.com',
    'cveurl' => 'http://cve.circl.lu/cve/',
    'disablerestalert' => false,
    'default_event_distribution' => '1',
    'default_attribute_distribution' => 'event',
    'tagging' => true,
    'full_tags_on_event_index' => true,
    'footer_logo' => '',
    'take_ownership_xml_import' => false,

Regards,
Yu Liang

**Comment by iglocska** [comment]
You don't have to do anything with it generally, all of that can be changed from MISP directly via the server settings. However the file permissions of the config file is important, make sure that your apache user can write to it.

chmod 750 /var/www/MISP/app/Config/config.php
chown apache:apache /var/www/MISP/config.php

**Comment by yuliangchew** [comment]
Dear iglocska, 

For chown apache:apache /var/www/MISP/config.php
it return "chown: cannot access ‘/var/www/MISP/config.php’: No such file or directory"
so what should i do?

so its its the following command?
chmod 750 /var/www/MISP/app/Config/config.php
chown apache:apache /var/www/MISP/config.php

or the following command?
chmod -R 750 /var/www/MISP/app/Config/config.php
chown -R apache:apache /var/www/MISP/config.php

i noticed the instruction from https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.centos7.txt 
but i do not know which directory to put in, because it only state these:-
chmod -R 750 /var/www/MISP/<directory path with an indicated issue>
chown -R apache:apache /var/www/MISP/<directory path with an indicated issue>

Thank You 

Regards,
Yu Liang

**Comment by iglocska** [comment]
Sorry my bad, the file is in /var/www/MISP/app/Config/config.php, was a copy paste issue!

**Comment by yuliangchew** [comment]
1. I am still unable to click at the MISP setting tab. attached photo for ur reference, I have already restarted my browser as well. do i have to restart anything to let the changes to take effect? 
2. Is MISP tab same as MISP Setting tab?

![capture1](https://cloud.githubusercontent.com/assets/18456644/14523443/5f9144e8-0266-11e6-94ee-eab8d6179beb.JPG)

**Comment by iglocska** [comment]
Ah ok, misunderstood the issue. Could you try this?

manually edit the config file:

vim /var/www/MISP/app/Config/config.php
for 'baseurl' enter the value 'localhost'

save the file
reload the server settings page.

Does this fix the issue for you?

**Comment by yuliangchew** [comment]
nope. after adding localhost to basurl, below are the error on every page 
![capture5](https://cloud.githubusercontent.com/assets/18456644/14524669/105a6322-026c-11e6-8549-a8aaf8a6da08.JPG)

except the page after sign in
![capture4](https://cloud.githubusercontent.com/assets/18456644/14524714/42b48eb0-026c-11e6-8ec2-0b858ec50bd0.JPG)

**Comment by iglocska** [comment]
Could you try it with http://localhost instead of localhost?

**Comment by yuliangchew** [comment]
I tried with http://localhost and http://127.0.0.1, it will automatically change to localhost or 127.0.0.1. and it is not working with https://localhost

please advise

**Comment by Rafiot** [comment]
Sorry for the late answer, do you still have the issue?

**Comment by adulau** [comment]
We will close it. Feel free to reopen if you still have the issue. Thank you.

**Comment by SurajChennoju** [comment]
Unable to Enable Server Settings Administration->ServerSettings->MISP tab->live

**Comment by AdrianCUCU** [comment]
same problem - fresh install on ubuntu server - after login  "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)", but when I try enter -I end up with " An Internal Error Has Occurred".

**Comment by whatthejay** [comment]
Same for me as @AdrianCUCU .

I found this error has been recorded in the log file "/var/www/MISP/app/tmp/logs/error.log


2019-02-03 22:55:12 Error: [MissingTableException] Table tag_collections for model TagCollection was not found in datasource default.
Exception Attributes: array (
  'table' => 'tag_collections',
  'class' => 'TagCollection',
  'ds' => 'default',
)
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('tag_collections')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#3 /var/www/MISP/app/Model/TagCollection.php(75): Model->find('all', Array)
#4 /var/www/MISP/app/Model/Server.php(2663): TagCollection->fetchTagCollection(Array)
#5 /var/www/MISP/app/Controller/ServersController.php(837): Server->loadTagCollections(Array)
#6 /var/www/MISP/app/Controller/ServersController.php(915): ServersController->__loadTagCollections()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by Firzum** [comment]
Hello,

I'm affected by this issue too, fresh install, using the auto...sh script.
Same error message about missing table, which is present into the database (tested with the misp login/password).

Error: [MissingTableException] Table tag_collections for model TagCollection was not found in datasource default.
Exception Attributes: array (
'table' => 'tag_collections',
'class' => 'TagCollection',
'ds' => 'default',
)

Branch 2.4, ip to date.

Any kind of help is welcome.

**Comment by Firzum** [comment]
Additional informations:
Ubuntu 18.10
No apparmor/selinux activated for apache

MariaDB [misp]> select value from admin_settings where setting = 'db_version';
+-------+
| value |
+-------+
| 38    |
+-------+
1 row in set (0.00 sec)

MariaDB [misp]> describe tag_collections;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| uuid        | varchar(40)  | YES  | MUL | NULL    |                |
| user_id     | int(11)      | NO   | MUL | NULL    |                |
| org_id      | int(11)      | NO   | MUL | NULL    |                |
| name        | varchar(255) | NO   |     | NULL    |                |
| description | text         | NO   |     | NULL    |                |
| all_orgs    | tinyint(1)   | NO   |     | 0       |                |
+-------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)

MariaDB [misp]>

**Comment by Firzum** [comment]
tried again after a full removal (rm folders (/var/www, /usr/local/...), mariadb and databases removal), same issue.

**Comment by Firzum** [comment]
I gave a try to all solutions in https://github.com/MISP/MISP/issues/4658 without success
Any help is welcome

**Comment by Rafiot** [comment]
Can you open an other issue, please? The issue you're having has nothing to do with the initial bug opened in 2016.

**Comment by Firzum** [comment]
Oh, you are right, my bad !

**Comment by Firzum** [comment]
Here it is https://github.com/MISP/MISP/issues/5180
