### ISSUE TITLE
Export data in ArcSight CEF format

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#109]
ArcSight CEF (Common Event Format) standard description:
http://mita-tac.wikispaces.com/file/view/CEF+White+Paper+071709.pdf

Code examples of use by two scripts to export open source feeds in CEF:
1. https://code.google.com/p/alienvault-labs-garage/downloads/detail?name=otx-arcsight.py
2. https://code.google.com/p/arcosi/source/browse/trunk/arcosi-24.py

To facilitate use of MISP with leading SIEM solutions: ArcSight, but also OSSIM and others support CEF format.

**Comment by elhoim** [comment]
Gaetan Cardinal also has some python library (CAKE?) to generate & ingest CEF log format

**Comment by adulau** [comment]
There is CEF export modules nowadays. https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/export_mod/cef_export.py Does this solve this issue? Thank you.

**Comment by adulau** [comment]
I'll close the issue. If you think the issue is not resolved, feel free to reopen.

**Comment by gecko97** [comment]
I suggest to reopen this issue. It would be really useful to automatically send CEF logs to a given IP address and port, via syslog protocol for example. Possibly this should be configured via the MISP GUI.

Thanks
