### ISSUE TITLE
Allow to sort in the alternate search results list

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1096]
Allows to sort the list of results under the alternate search results list

**Comment by cvandeplas** [comment]
what is the alternate search results list?

**Comment by elhoim** [comment]
The alternate search resulsts list is the when you tick the box _Alternate Search Result (Events)_ on the search page. You then get a list of events instead of attributes that match your search request.

**Comment by elhoim** [comment]
Duplicate of #328. Closing
