### ISSUE TITLE
Filter out organisation update storms

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1099]
When syncing takes place, there is some kind of Organisation update storm:
![image](https://cloud.githubusercontent.com/assets/178521/14608889/0e82486a-054d-11e6-9e16-c02eb64ecea4.png)

I don't think all the orgs have had an update, so I am wondering why it happens and it could be suppressed or filter out to get cleaner logs.

**Comment by iglocska** [comment]
I keep forgetting about this one, it erroneously updates the last modified timestamp. I'll look into it!
