### ISSUE TITLE
separate the title and description with new_event

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1102]
Hi team,

It will be cool to separate `info` in `titre` and `description` in new_event in PyMISP like maybe

``` python
def new_event(self, distribution=None, threat_level_id=None, analysis=None, title=None, description=None,date=None, published=False):
        data = self._prepare_full_event(distribution, threat_level_id, analysis, info, date, published)
        response = self.add_event(data, 'json')
        return self._check_response(response)
```

With PyMISP, the title created is troncate and not corespond to the event.

The title could be match with the field short_description from IOC. (idea for import function ^^ )

regards.

**Comment by Rafiot** [comment]
Hi,

Not sure I understand your question: 

``` python
def new_event(self, distribution=None, threat_level_id=None, analysis=None, info=None, date=None, published=False):
    data = self._prepare_full_event(distribution, threat_level_id, analysis, info, date, published)                
    response = self.add_event(data, 'json')                                                                        
    return self._check_response(response)                                                                          
```

The current implementation has an info parameter which is the only one you need when you create an event.

**Comment by tomking2** [comment]
If I understand it right, it'd be good to have a further detail field included, so not just the "Info", but a description.

It's something which I'd like to see also. Having the info title is good, but it's nice to have a large chunk of Text as a Description. For now, We're using the Discussion section to add further clarity.

**Comment by Rafiot** [comment]
Oh, ok, got it. This is a bigger change (as it requires to update the DB).

**Comment by truckydev** [comment]
Ok sorry, my bad.

I try to develop
when you create an avent you have only the field : 
"Event Description" 

But in this screenshot : 
https://camo.githubusercontent.com/5125afc18bb95cd75c0c714111c64cb2a88ef24e/687474703a2f2f332e62702e626c6f6773706f742e636f6d2f2d4233683078625837526a492f556674766d7130357248492f414141414141414141706f2f49304f45594f41465549342f73313630302f7265642d6f63742d312e6a7067

You van see that Event is different that the fiel info.  
It would be interesting to make 2 differents fields.

Currently , when you create an event (by API or with web interface) the title is just the start of the description (info field).

That's why I tell you about "Short_descrition" and "description" form the IOC who could be the title and the info field.

I hope I have correctly describe this time :)

Is it possible ?

**Comment by iglocska** [comment]
Actually the info field used to be a bigger description field before, but we ended up turning it into something that is closest to the short description when people started pasting their IOCs in there :) Maybe now that the freetext import makes adding indicators easier though we could consider adding a longer description field for the next non-backwards compatible version?

**Comment by adulau** [comment]
Why don't you use a specific attribute like other/text?

**Comment by truckydev** [comment]
Thank you for your answer.

I do not think this will solve the problem. 
"Title" and "description" are really specific elements in an event .

Create atribut away the problem. More information will be indexed . During a search , I do not think that this information is pertinante. 
But until an update , an attribute as "other/event_description" could be a solution.

What do you think?

**Comment by truckydev** [comment]
Ok I see the fiel Other/comment are not indexed.
