### ISSUE TITLE
automation/ansible/serverspec: cli commands missing

### ISSUE THREAD

**Issue by juju4** [MISP/MISP#1103]
Hello,

I'm working on an ansible playbook for MISP but there are still some post-install manual actions which are needed like
- changing default admin user password
- set API key
- ensure no fatal error in Server settings and diagnostics
  probably some others

after that, I will be able to add further test inside serverspec to validate install (mostly API call)
I suppose at some point, some test data would be useful. Is there such a (public) set?

https://github.com/juju4/ansible-MISP
https://github.com/juju4/ansible-MISP/blob/master/test/integration/default/serverspec/misp_spec.rb

Thanks

**Comment by adulau** [comment]
Hi Julien,
Nice to hear about some work regarding an ansible playbook for MISP.

To bootstrap a MISP installation, you can already have a look at the Travis file:

https://github.com/MISP/MISP/blob/2.4/.travis.yml

and especially:

```
 sudo -E su $USER -c 'app/Console/cake userInit -q | sudo tee ./key.txt'
```

Could have a look at the Travis file? and let us know if you miss something else for your installation process.

Thank you very much.

Cheers

**Comment by juju4** [comment]
Hello Alexandre,

Great! will review it and put my feedback here.

Thanks a lot!

**Comment by juju4** [comment]
So a first review

I reviewed pre-tasked but mostly sticking to docs walkthrough. only the bootstrap.php which is a bit different. database/core/config.php are handled with the contents of my defaults folder inside ansible role.

I added a test execution based on your travis file in the config here
https://github.com/juju4/ansible-MISP/blob/master/test/integration/default/default.yml

You have an example execution inside travis (+docker) here
before adding test https://travis-ci.org/juju4/ansible-MISP/jobs/125468611
add after https://travis-ci.org/juju4/ansible-MISP/jobs/127126947

I didn't see how to
- change default user admin@admin.test and his password? do you recommend just edit mysql users table?
- update password length/complexity?
- validate installation is functional? secure? (equivalent of diagnostics page)

still reviewing curl_tests.sh/pymisp test run inside serverspec

**Comment by juju4** [comment]
Hello Alexandre,

Role is running
https://travis-ci.org/juju4/ansible-MISP/jobs/129307736
Currently only standard travis test passed. I added serverspec test from my local kitchen CI but I have issues to get it work inside travis+docker.

Inside kitchen, i get this from test scripts

```
       Failures:

         1) Command "cd /var/www/MISP/tests && ./curl_tests.sh `cat $HOME/build/key.txt`" stdout should not match /HTTP\/1.1 500 Internal Server Error/
            Failure/Error: its(:stdout) { should_not match /HTTP\/1.1 500 Internal Server Error/}
              expected "HTTP/1.1 100 Continue\r\n\r\nHTTP/1.1 500 Internal Server Error\r\nDate: Sun, 15 May 2016 21:28:10 GMT\r\nServer: Apache/2.4.7 (Ubuntu)\r\nX-Powered-By: PHP/5.5.9-1ubuntu4.16\r\nSet-Cookie: CAKEPHP=qot42uplaf3nknc0qvirkj6ta0; expires=Sun, 15-May-2016 22:28:10 GMT; Max-Age=3600; path=/; HttpOnly\r\nSet-Cookie: CAKEPHP=qot42uplaf3nknc0qvirkj6ta0; expires=Sun, 15-May-2016 22:28:11 GMT; Max-Age=3600; path=/; HttpOnly\r\nSet-Cookie: CAKEPHP=vq9osqlso9voe4rev66r1d63s3; expires=Sun, 15-May-2016 22:28:11 GMT; Max-Age=3600; path=/; HttpOnly\r\nContent-Length: 103\r\nConnection: close\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n{\"name\":\"An Internal Error Has Occurred.\",\"message\":\"An Internal Error Has Occurred.\",\"url\":\"\\/events\"}uuid,category,type,value,comment,to_ids,date\n548847d8-01e0-4231-a739-15bb950d210b,Payload installation,md5,\"744c07e886497f7b68f6f7fe57b7ab54\",\"Regin  [...]" not to match /HTTP\/1.1 500 Internal Server Error/
              Diff:
              @@ -1,2 +1,45 @@
              -/HTTP\/1.1 500 Internal Server Error/
              +HTTP/1.1 100 Continue
              +
              +HTTP/1.1 500 Internal Server Error
              +Date: Sun, 15 May 2016 21:28:10 GMT
              +Server: Apache/2.4.7 (Ubuntu)
              +X-Powered-By: PHP/5.5.9-1ubuntu4.16
             +Set-Cookie: CAKEPHP=qot42uplaf3nknc0qvirkj6ta0; expires=Sun, 15-May-2016 22:28:10 GMT; Max-Age=3600; path=/; HttpOnly
              +Set-Cookie: CAKEPHP=qot42uplaf3nknc0qvirkj6ta0; expires=Sun, 15-May-2016 22:28:11 GMT; Max-Age=3600; path=/; HttpOnly
              +Set-Cookie: CAKEPHP=vq9osqlso9voe4rev66r1d63s3; expires=Sun, 15-May-2016 22:28:11 GMT; Max-Age=3600; path=/; HttpOnly
              +Content-Length: 103
              +Connection: close
              +Content-Type: application/json; charset=UTF-8
              +
              +{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events"}uuid,category,type,value,comment,to_ids,date
              +548847d8-01e0-4231-a739-15bb950d210b,Payload installation,md5,"744c07e886497f7b68f6f7fe57b7ab54","Regin samples collected.",1,20141210
[...]
              +5488486c-47ec-4952-8e60-15ba950d210b,Artifacts dropped,regkey,"Class\{9B9A8ADB-8864-4BC4-8AD5-B17DFDBB9F58}","",1,20141210
              +5488486c-a044-4c31-830c-15ba950d210b,Artifacts dropped,regkey,"HKLM\System\CurrentControlSet\Control\","",1,20141210              

            # /tmp/verifier/suites/serverspec/misp2_spec.rb:10:in `block (2 levels) in <top (required)>'

         2) Command "cd /var/www/MISP/PyMISP && coverage run setup.py test" stdout should match /test_create_event/
            Failure/Error: its(:stdout) { should match /test_create_event/ }
              expected "running test\nrunning egg_info\ncreating pymisp.egg-info\nwriting requirements to pymisp.egg-info/requires.txt\nwriting pymisp.egg-info/PKG-INFO\nwriting top-level names to pymisp.egg-info/top_level.txt\nwriting dependency_links to pymisp.egg-info/dependency_links.txt\nwriting manifest file 'pymisp.egg-info/SOURCES.txt'\nreading manifest file 'pymisp.egg-info/SOURCES.txt'\nwriting manifest file 'pymisp.egg-info/SOURCES.txt'\nrunning build_ext\n" to match /test_create_event/
              Diff:
              @@ -1,2 +1,12 @@
              -/test_create_event/
              +running test
              +running egg_info
              +creating pymisp.egg-info
              +writing requirements to pymisp.egg-info/requires.txt
              +writing pymisp.egg-info/PKG-INFO
              +writing top-level names to pymisp.egg-info/top_level.txt
              +writing dependency_links to pymisp.egg-info/dependency_links.txt
              +writing manifest file 'pymisp.egg-info/SOURCES.txt'
              +reading manifest file 'pymisp.egg-info/SOURCES.txt'
              +writing manifest file 'pymisp.egg-info/SOURCES.txt'
              +running build_ext

              /bin/sh -c cd\ /var/www/MISP/PyMISP\ \&\&\ coverage\ run\ setup.py\ test
              running test
       running egg_info
       creating pymisp.egg-info
       writing requirements to pymisp.egg-info/requires.txt
       writing pymisp.egg-info/PKG-INFO
       writing top-level names to pymisp.egg-info/top_level.txt
       writing dependency_links to pymisp.egg-info/dependency_links.txt
       writing manifest file 'pymisp.egg-info/SOURCES.txt'
       reading manifest file 'pymisp.egg-info/SOURCES.txt'
       writing manifest file 'pymisp.egg-info/SOURCES.txt'
       running build_ext

            # /tmp/verifier/suites/serverspec/misp2_spec.rb:17:in `block (2 levels) in <top (required)>'

        3) Command "cd /var/www/MISP/PyMISP && coverage run setup.py test" exit_status should eq 0
            Failure/Error: its(:exit_status) { should eq 0 }

              expected: 0
                   got: 1

              (compared using ==)

            # /tmp/verifier/suites/serverspec/misp2_spec.rb:18:in `block (2 levels) in <top (required)>'

       Finished in 1.83 seconds (files took 0.44097 seconds to load)
       12 examples, 3 failures

       Failed examples:

       rspec /tmp/verifier/suites/serverspec/misp2_spec.rb:10 # Command "cd /var/www/MISP/tests && ./curl_tests.sh `cat $HOME/build/key.txt`" stdout should not match /HTTP\/1.1 500 Internal Server Error/
       rspec /tmp/verifier/suites/serverspec/misp2_spec.rb:17 # Command "cd /var/www/MISP/PyMISP && coverage run setup.py test" stdout should match /test_create_event/
       rspec /tmp/verifier/suites/serverspec/misp2_spec.rb:18 # Command "cd /var/www/MISP/PyMISP && coverage run setup.py test" exit_status should eq 0

```

not dig much into for now but clearly not matching what you get https://travis-ci.org/MISP/MISP/jobs/128166085

I managed to do the first 2 points more or less. (only setting initial password, user will have to update after)
It would be nice to be able to call diagnostics pages from cli

Any way to do those tasks in cli:
- accept terms and conditions
- enable/add feeds, servers
- fetch events from feeds/server unless more recent than time
- enable scheduled tasks
- enable taxonomies and tags

Thanks

**Comment by adulau** [comment]
The enable/add feeds is now accessible via the API:

https://github.com/MISP/MISP/commit/f08ec04426e684239f36c207d1733291b04f9db6

The others will follow soon.

**Comment by Rafiot** [comment]
@iglocska: are those options already available server-side?

**Comment by iglocska** [comment]
Not yet but we should get them they make a lot of sense!

**Comment by Rafiot** [comment]
Excellent :) Then, I'll update PyMISP.

**Comment by adulau** [comment]
So maybe the best would be to re-factor all the actions (which make sense) that we have accessible them from the UI and API. @iglocska mentioned that this could take 2 or 3 weeks.

**Comment by juju4** [comment]
role updated and pass serverspec test including your unit test.
strangely execution result changes depending on platform.
I didn't include them in my travis/docker execution because of travis constraint but you can review locally with kitchen/lxd.

As for enabling feeds, how I can recover API key of admin user from command line?
After, just POST on /feeds/enable/feed_id from https://www.circl.lu/doc/misp/automation/#enable-and-disable-feeds-via-the-api, right ?

Also it would be nice if /var/www/MISP/app/Console/cake could create user and when updating password returning correct exit code.
Currently, it returns 0 all the time, even if it fails.
https://travis-ci.org/juju4/ansible-MISP/jobs/160877035#L2779

Thanks

**Comment by adulau** [comment]
User API has been introduced in #1621 

Could you verify that fit your needs for automation?

**Comment by juju4** [comment]
Thanks Alexandre! Wil try!

**Comment by juju4** [comment]
I tested and integrated in my MISP role
* adding users
* enabling/disabling feeds
Working great!

for feeds, it would be nice to have a call /feeds/list so the role can be idempotent (check status before and modify only when needed)

what about
* fetch events from feeds/server unless more recent than time
* enable scheduled tasks
* enable taxonomies and tags

Thanks a lot!

**Comment by adulau** [comment]
Everything should be fixed and the scheduled tasks are replaced by cron entries (check the last section of the automation page).
