### ISSUE TITLE
Combined attributes are forgotten in many places

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1105]
Combined attributes are forgotten in many places.
For example, the `domain|ip` consists of 2 attributes: `domain` and `ip`. 
The domain should be considered the same as the single `domain` attribute. 

If this is not done, analysts will forget that these new exist. Also other new features relying on these will not work accordingly. 

example 1: the google warning list will not work on the combined `domain|ip` attribute.  (https://github.com/MISP/misp-warninglists/blob/master/lists/google/list.json ) 
example 2: an SIEM admin integrating hostname / domain / ip-src / ip-dst rules will not have implemented the `hostname|ip`, `domain|ip` ... that already map on existing datatypes they parse. 

1/ in exports: `text`, `ids`
example: an export for `domain` should also contain the `domain` section of the combined `domain|ip` attribute
example: `file|hash`

2/ same for misp-warninglists:
Example: a warning list have a   "matching_attributes": [ "domain", "hostname" ] configuration.
The match should also be done on the sub-element of the combined attribute.

With the domain|ip it is a little bit more complex: `ip-src` and `ip-dst` definitions should also be applied on `ip`. 

We do agree that combined objects should and will disappear, however the question is how long it will take before reaching this phase and how much effort it is to implement a short-term fix.

**Comment by adulau** [comment]
Very good point. As we recently discussed, the combined objects will disappear in favour of misp-objects https://github.com/MISP/misp-objects.

Right now, the current work is on misp import/export modules and the misp-objects should be the next step. It's clearly sooner than later.
