### ISSUE TITLE
TLP:AMBER hardcoded in email subject

### ISSUE THREAD

**Issue by klingsor83** [MISP/MISP#1107]
Hi,

why is the TLP:AMBER hardcoded in the email subject for alerts? If you create an event with TLP:GREEN (for example), it could be confused if the email sended has the TLP:AMBER.

Could be possible to send in the subject the tlp tagged in the event? And if the event hasn't the tag, send the email without the TLP.

Regards

**Comment by cvandeplas** [comment]
Idea: use the TLP marking of the event, or the most sensitive TLP of the attribute. 
Or fall back on the default of the platform.
Also the distribution flag, and choose the most restrictive one.

**Comment by rotanid** [comment]
probably fixed by #1240

**Comment by iglocska** [comment]
It's a first step, but let's keep it open for now and then improve it later. Right now it's a server setting, in the future it would be nice to read the tags and look for a TLP tag - if not found fall back to the default setting, as described by @klingsor83
