### ISSUE TITLE
New category types for upcoming versions

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1108]
The idea with this issue is to have a collection of new categories that we need to describe attributes. We'll collect ideas here and we'll see what sticks for the upcoming version. The plan is to add all new types and categories in one go as it will break backwards compatibility with existing versions. 

To kick it off, an idea from @rommelfs: 

Support Tool category: scripts / tools used for the analysis (could be attachment, text, comment).

**Comment by iglocska** [comment]
New attribute type ideas from @Rafiot:

`email-dst-display-name`
`email-src-display-name`
Maybe: `email-received-path`

**Comment by adulau** [comment]
A specific category for scripts and binary for detection and remediation:

`detection-remidiation-tools`

A lot of scripts uploaded are used for detection or remediation against malicious payloads but we don't have a specific category.

**Comment by Rafiot** [comment]
`compilation-timestamp`
`original-filename`

**Comment by adulau** [comment]
https://github.com/MISP/MISP/issues/924 -> `size-in-bytes`

Many attributes type tag as "datamodel enhancement" including the generic ones for the future misp-ojects -> https://github.com/MISP/MISP/labels/datamodel%20enhancement

**Comment by adulau** [comment]
https://github.com/MISP/MISP/issues/924 -> `size-in-bytes`

Many attributes type tag as "datamodel enhancement" including the generic ones for the future misp-ojects -> https://github.com/MISP/MISP/labels/datamodel%20enhancement

**Comment by adulau** [comment]
Fixed in v2.4.57 https://github.com/MISP/MISP/tree/v2.4.57
