### ISSUE TITLE
PHP Fatal error:  Can't use method return value in write context in

### ISSUE THREAD

**Issue by jpferrero** [MISP/MISP#1109]
Since last update (2.4.37) I get this error when trying to launch 'generate cache':

PHP Fatal error:  Can't use method return value in write context in /var/www/reyes/app/Model/Server.php on line 1544

I solved the problem changing the following line:

if (empty($this->eventFilterPushableServers($event, array($server)))) {

to:

$eventFilter=$this->eventFilterPushableServers($event, array($server));
                        if (empty($eventFilter)) {

**Comment by iglocska** [comment]
What PHP version are you on? This could be caused by an unsupported PHP version.

**Comment by jpferrero** [comment]
I'm over Centos7:

> /opt/rh/rh-php56/root/usr/bin/php --version
> PHP 5.6.5 (cli) (built: Oct  5 2015 21:20:24) 
> Copyright (c) 1997-2014 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

And original PHP version from Centos:

> php --version
> PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27) 
> Copyright (c) 1997-2013 The PHP Group
> Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by iglocska** [comment]
Are both installed? Sounds like MISP might be using 5.4.

**Comment by jpferrero** [comment]
Yes, workers seems to use php 5.4 instead of php 5.6 but if I uninstall php-cli 5.4 workers doesn't work...

**Comment by jpferrero** [comment]
Hello!
I confirm that in order to launch the workers from web I need to install php-pecl-redis and it's dependences.

**Comment by Rafiot** [comment]
Good, should we consider this as fixed?

**Comment by jpferrero** [comment]
I have uninstalled all php 5.4 and workers seems to work fine, but now i can't start workers from web app. The only way is from command line (su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/reyes/app/Console/worker/start.sh') .

**Comment by iglocska** [comment]
Interesting, I'll try to look into this together with some other RH related issues.

**Comment by iglocska** [comment]
@jpferrero , I've just pushed a patch that includes a workaround for this. Please git pull and enable 'MISP.rh_shell_fix' in the server settings (Administration -> Server Settings -> MISP tab -> rh_shell_fix).

Let me know if this resolves it for you.

**Comment by jpferrero** [comment]
Workers now start from the web (the processes bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex'; are launched) but scheduled task are not executed. Redis seems to be adding the jobs:
"resque:_schdlr_"
"resque:job:06fb3d79c37c7e1ce7f2717b689f9f7c:status"

**Comment by Rafiot** [comment]
Sorry for the late answer, do you still have the issue?

**Comment by jpferrero** [comment]
Hi! Still have the issue (update to last git). With php 5.6 and rh_shell_fix set to true scheduled tasks never executed, so I had to install php 5.4-redis and it's dependencies and disable rh_shell_fix. Now works fine but I have the mix of php54 and php56.

**Comment by RichieB2B** [comment]
Did you try installing php-redis under php 5.6 using pecl as explained in the INSTALL.centos6.txt ? You really should uninstall php 5.4 as it is only complicating things.

**Comment by jpferrero** [comment]
Yes, php-redis is installed through pecl. Tasks are added to redis as I post before but never execute.

**Comment by jpferrero** [comment]
Hi! It's fixed now. The problem was permissions in file 'redis.ini'.

Thanks,

**Comment by iglocska** [comment]
Thanks a lot for letting us know!
