### ISSUE TITLE
Column 'org_id' cannot be null

### ISSUE THREAD

**Issue by pierrempr** [MISP/MISP#1111]
Hi, 

I'm reopening the issue  #814  because I still encountering the error when I want to pull new feeds.

`[2016-04-27 11:00:49] main.ERROR: {"queue":"default","id":"d52789566162e8e28ea6f24461863236","class":"ServerShell","args":[["fetchFeed","2","1","1984"]]} failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null {"type":"fail","log":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null","job_id":"d52789566162e8e28ea6f24461863236","time":13745,"worker":"BDLUBINL01:6386"} []`

I have 2 instance of MISP and each are un v2.4.38 but one is on Debian8 and the other on Centos7. The issue is on the MISP on Centos7. 

Do you think the cause could be a difference between MariaDB and MySQL ?

Thanks 

Pierre

**Comment by iglocska** [comment]
This sounds weird for sure. Is it an upgraded instance (from MISP 2.3)? If so, could you check whether you have any users that don't have an organisation attached? This should never happen unless something went really wrong with the upgrade process but just in case.

The OS version shouldn't cause this for sure.

**Comment by truckydev** [comment]
Here the result form API : 

##### json sample:

```
{'Event': 
  {'info': u'zerzerzer', 'threat_level_id': '4', 'org': '', 'date': '2016-04-28', 'timestamp': '1', 'distribution': '0', 'attribute_count': 0, 'proposal_email_lock': False, 'analysis': '0', 
  'Attribute': [
    {'category': u'External analysis', 'comment': '', 'timestamp': '0', 'to_ids': '0', 'value': 'test.exe', 'distribution': '0', 'type': u'filename'}, 
    {'category': 'Other', 'comment': u'zerzer', 'timestamp': '0', 'to_ids': '0', 'value': 'authored_by', 'distribution': '0', 'type': 'comment'},
    {'category': 'Other', 'comment': u'2016-04-28T15:09:46.108Z', 'timestamp': '0', 'to_ids': '0', 'value': 'authored_date', 'distribution': '0', 'type': 'comment'},
    {'category': 'Other', 'comment': u'zerzer', 'timestamp': '0', 'to_ids': '0', 'value': 'description', 'distribution': '0', 'type': 'comment'}]
  }
}
```

```
{u'url': u'/events/add', u'message': u'The event could not be saved.', u'errors': 
  {u'Event':
     {u'orgc_id': [u'Orgc_id cannot be empty.'], u'org_id': [u'Org_id cannot be empty.']}}, u'name': u'Add event failed.'}
```

And work in 2.4.35 but not in 2.4.37 too

**Comment by iglocska** [comment]
Which API are you using? I've just tested via the REST API and it works fine (after converting your python object to JSON).

What I did:

```
{"Event": 
  {"info": "zerzerzer", "threat_level_id": "4", "org": "", "date": "2016-04-28", "timestamp": "1", "distribution": "0", "attribute_count": 0, "proposal_email_lock": False, "analysis": "0", 
  "Attribute": [
    {"category": "External analysis", "comment": "", "timestamp": "0", "to_ids": "0", "value": "test.exe", "distribution": "0", "type": "filename"}, 
    {"category": "Other", "comment": "zerzer", "timestamp": "0", "to_ids": "0", "value": "authored_by", "distribution": "0", "type": "comment"},
    {"category": "Other", "comment": "2016-04-28T15:09:46.108Z", "timestamp": "0", "to_ids": "0", "value": "authored_date", "distribution": "0", "type": "comment"},
    {"category": "Other", "comment": "zerzer", "timestamp": "0", "to_ids": "0", "value": "description", "distribution": "0", "type": "comment"}]
  }
}
```

POSTed to http://mymisp/events/add
Headers:
Authorization: [My API key]
Accept: application/json
Content-type: application/json

Result was an event that was created for my organisation. Version used for the test: MISP 2.4.41

**Comment by truckydev** [comment]
ok all my bod,

A don't save my answer :(

As you say before, my new user don't have a default organisation.

All work fine now :)

thx again

**Comment by iglocska** [comment]
Excellent, glad it worked out! :)
