### ISSUE TITLE
View Event Throwing Error

### ISSUE THREAD

**Issue by I-am-Sherlocked** [MISP/MISP#1113]
Viewing a single event (events/view/<id>) is currently throwing the error 

> Error: [PDOException] SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'misp.ShadowAttribute.event_id' which is not in SELECT list; this is incompatible with DISTINCT

Traced back to app/Model/ShadowAttribute.php(508): Model->find('all', Array)
`$orgs = $this->find('all', array('fields' => array('DISTINCT(org_id)'), 'conditions' => array('event_id' => $id)));`

Removing "DISTINCT" from the query resolves this issue, but I haven't verified where else the function might be called.

**Comment by iglocska** [comment]
Sorry forgot to respond to this, it was fixed a few patches ago, let me know if it pops up again.

**Comment by I-am-Sherlocked** [comment]
Yes if I don't remove the "DISTINCT" the issue persists.

**Comment by iglocska** [comment]
Hmm weird, looking into it.

**Comment by iglocska** [comment]
Oh wow, looks like I never pushed the fixes for this. Give me a few minutes.

**Comment by iglocska** [comment]
OK, just pushed a fix for it, should be OK now. Let me know if you still run into the issue.

**Comment by I-am-Sherlocked** [comment]
Great. Fixed now, thanks.
