### ISSUE TITLE
Impossible to download attributes in MISP XML & JSON formats

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#1114]
Hello all,

User and OrgAdmin can't downloaded attributes in MISP XML & JSON formats (click "Download as..." -> "MISP XML" or "Download as..." -> "MISP JSON").

Error displayed (url: https://xxx.xxx.com/events/restsearch/download/false/false/false/false/false/false/false/false/false/900/true.xml

```
<response>
<name>
You do not have permission to use this functionality.
</name>
<message>
You do not have permission to use this functionality.
</message>
<url>
/events/restsearch/download/false/false/false/false/false/false/false/false/false/900/true.xml
</url>
</response>
```

I tried to do the same using the API and it works :)

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.38

**Comment by iglocska** [comment]
This was indeed a bug with an invalid capitalised action in the URL and the new ACL system. Should be fixed by now.
