### ISSUE TITLE
Free text import does not recognize email address as Payload Delivery Email-Src or Dst only URL

### ISSUE THREAD

**Issue by cbakkers** [MISP/MISP#1116]
MISP 2.4.25 version used.
Suggest to enhance free text import to automatically recognize email addresses

**Comment by iglocska** [comment]
Just checked this on a more up to date version and it seems to work as intended.

**Comment by cbakkers** [comment]
Hey Andras, what version is this working on?

**Comment by iglocska** [comment]
I've just tested it with 2.4.43

What I did: Entered my e-mail address into the freetext import tool: detected as email-src with email-dst offered as an alternative type.
