### ISSUE TITLE
Problem with osint json/taxonomy

### ISSUE THREAD

**Issue by mariuskagc** [MISP/MISP#1119]
Hi guys, 
we are working with taxonomies and found an issue.

It loaded 15 Taxonomies at first time and we got the "osint could not be installed/updated. Error: {"TaxonomyPredicate":{"2":{"TaxonomyEntry":{"6":{"value":["Value cannot be empty."]}}}}}" message in Logs tab.

Looking into osint machinetag.json we found that this entry causes the problem.

```
       {
          "value": "0",
          "expanded": "0% Impossibility",
          "description": "0% Impossibility"
        }

```

We changed "value": "0" to "value": "0.0" and now osint shows up on the taxonomies list.

Hope it helps,
best regards.

**Comment by iglocska** [comment]
Thanks for the heads-up, should be fixed now, just git pull.
