### ISSUE TITLE
View all button on event page breaks tooltip over relation

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1124]
- open an event with a relation
- hover over the related attribute, notice the very beautiful tooltip
- press the "view all" button, an ajax call is made and refreshes only the attributes list
- hover over the related attribute, notice the html tags are shown as text

**Comment by iglocska** [comment]
Hmm that is weird. For me it seems to work, which version of MISP are you on?

What I tried: 
1. Open up event with a relation
2. Hover over it, bask in the beauty of the tooltip
3. Click view all
4. Hover over a relation
5. Further bedazzling ensues

**Comment by cvandeplas** [comment]
2.4.33

upgrade is planned very soon though. sorry for the false-positive
