### ISSUE TITLE
Void Servers lines after upgrade from 2.4.42 to 2.4.44

### ISSUE THREAD

**Issue by tom8941** [MISP/MISP#1142]
Hello Everyone,

I have noticed an error after having upgrade from 2.4.42 to 2.4.44.
It looks that in servers configuration, a new void line appears every time that a synchronisation is performed.
Please find enclosed a pictures showing the problem.

Could you please investigate on that issue ?

Thanks in advance.

Thomas

![servers](https://cloud.githubusercontent.com/assets/17175204/15393018/2c0fea2c-1dcb-11e6-8683-7a663b4b0210.png)

**Comment by iglocska** [comment]
Hello Thomas, 

I cannot seem to reproduce the issue, could you give us some more details on the conditions under which that happens?

Is it a push or a pull job that causes it? Do you have background workers enabled? Is it a scheduled push/pull?

Thanks in advance.

**Comment by tom8941** [comment]
Hello,
Thanks for your quick reply.
For the moment I was not able to reproduce the error manually.
For this server, we have pull and push enabled but only pull is scheduled every hour.
Push is not used.
All workers including scheduler looks running.
I have restarted the server this morning and for the moment it appears that I don't have new empty lines but I need to wait few hours more to be sure.

**Comment by iglocska** [comment]
Sure, let me know how it goes. It is a very strange issue, I'll do some tests with the scheduler.

**Comment by iglocska** [comment]
Found the issue, it was indeed happening only with scheduled pulls. Please git pull and let me know whether you still run into issues with it!

Thanks a lot for reporting this!
