### ISSUE TITLE
dead code in rpz() in AttributesController?

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1157]
in AttributesController.php there is the method rpz().
inside, there are the following two lines:

```
        if (!in_array($policy, array('NXDOMAIN', 'NODATA', 'DROP', 'walled-garden'))) $policy = false;

        if ($policy) $policy = $rpzExport->getIdByPolicy($policy);
```

thes lines are exactly doing nothing that changes anything or am i mistaken?

**Comment by iglocska** [comment]
It is basically a filter. If the user passes along an invalid policy setting it will set policy to false (which will .

However, if it's in the valid list it will fetch the policy ID. If the policy ID doesn't get set, it will default to what the server setting default is.

**Comment by rotanid** [comment]
but the policy ID isn't used anywhere after setting/getting it with getIdByPolicy(), at least i couldn't find any usage

**Comment by iglocska** [comment]
$lookupData = array('policy', 'walled_garden', 'ns', 'email', 'serial', 'refresh', 'retry', 'expiry', 'minimum_ttl', 'ttl');
        foreach ($lookupData as $v) {
            if (${$v} !== false) $rpzSettings[$v] = ${$v};
            else {
                $tempSetting = Configure::read('Plugin.RPZ_' . $v);
                if (isset($tempSetting)) $rpzSettings[$v] = Configure::read('Plugin.RPZ_' . $v);
                else $rpzSettings[$v] = $this->Server->serverSettings['Plugin']['RPZ_' . $v]['value'];
            }
        }

Here we iterate through the array and look up the variables by name for each of the array strings (${$v}}) and feed it to rpzSettings, which is then passed on to the view. 

The view uses the RPZExport library which uses the policy setting.
