### ISSUE TITLE
Add a plugin to optionaly validate NIDS rules

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#116]
The strategy used by [snort-mode](https://github.com/BobuSumisu/snort-mode) is interesting:
generate a minimal config file and then run snort with `-c` option.

It should be quite similar with suricata.

Other sources of inspiration: 
[SnortValidator](http://doc.emergingthreats.net/bin/view/Main/SnortValidator)
[Porcus](https://code.google.com/p/porcus/)

**Comment by adulau** [comment]
There is a simple expansion modules for testing Yara rules:

https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/yara_syntax_validator.py

If someone find library to parse ruleset of NIDS, let us know and open an issue at misp-modules.
