### ISSUE TITLE
Cannot login to MISP instance

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#1160]
Team,

I am not able to login to my MISP via web interface (GUI). I am trying all the password and also admin@admin.test/admin but still not working.

appreciate all the assistance.

Regards
FL

**Comment by iglocska** [comment]
Do you get an exception when you try, or does it complain about an invalid
password?

**Comment by thirdeyeintelligence** [comment]
I get username/password invalid. Tried multiple time and got : "You have reached the maximum number of login attempts. Please wait 300 seconds and try again.
Error: The requested address '/users/login' was not found on this server."

Regards
FL

**Comment by iglocska** [comment]
You can reset the password via the command line by using: 
/var/www/MISP/app/Console/cake Password [email] [password]

Let me know if it doesn't solve it.

**Comment by thirdeyeintelligence** [comment]
thanks alot works perfectly.....

**Comment by Rafiot** [comment]
Thanks for the answer, closing :)

**Comment by mahesh557** [comment]
i am getting same error even after doing password reset with cake

**Comment by thirdeyeintelligence** [comment]
can you check the error logs and see what's it saying > /var/logs/apache

**Comment by jhbigler-pnnl** [comment]
I am experiencing the same problem and resetting the password with cake does not fix the issue. I am using a VM downloaded from https://www.circl.lu/misp-images/latest/

**Comment by freitasthiago** [comment]
I also tried resetting the [admin@admin.test](mailto:admin@admin.test) password with the commands below:

sudo /var/www/MISP/app/Console/cake Password admin@admin.test [mypassword]

I also tried:
sudo /var/www/MISP/app/Console/cake user change_pw admin@admin.test [mypassword]

as explained in https://github.com/MISP/MISP/issues/1160 and https://github.com/MISP/MISP/issues/9055, but that didn't help... reinstalling the instance isn't a good option.

Is there a new procedure?
