### ISSUE TITLE
Search for MISP event UUID

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1167]
When exporting to STIX the MISP event UUID is used as package/incident id. Some tools display this id prominently. It makes sense to be able to search for the event UUID, the most obvious place being the filter box on the main event list.

**Comment by iglocska** [comment]
Makes sense indeed, I am kind of surprised we don't have that yet.

**Comment by truckydev** [comment]
Make this search by PyMISP will be great too.

**Comment by iglocska** [comment]
Looking for my holiday patch of the day(tm) and this looked like a promising option before I run out of battery, but it looks like it's already implemented on the filter box, so closing it for now.
