### ISSUE TITLE
Rename attribute hostname to FQDN

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#117]
It is important to distinguish between domain, hostname and FQDN.

A domain (ex: _example.com_) can resolve to an ip, it is then also a hostname and a FQDN.
A hostname can be only a domain that resolves to an ip (ex: _example.com_), a subdomain (ex: _server.example.com_); but people can also interpret it as being only the hostname part of a FQDN (ex: _server_ out of _server.example.com)

Things are clearer if you start calling it a FQDN. And if you keep the meaning of the attribute type _domain_ to: anything from that domain (ex: for _domain.com_ meaning _*.domain.com_ but also _domain.com_ on its own as a FQDN).

Background information on the subject:
http://en.wikipedia.org/wiki/Hostname
http://en.wikipedia.org/wiki/Fully_qualified_domain_name

**Comment by elhoim** [comment]
Created a separate issue (#479) for the question about data types for non-A types of DNS records

**Comment by adulau** [comment]
Closed as #479 is open for this case.
