### ISSUE TITLE
Authentication adapter "ApacheSecureAuth" was not found.

### ISSUE THREAD

**Issue by rjzak** [MISP/MISP#1174]
This is similar to #960, except that the solution provided does not fix my situation, and that issue was marked as closed and for a prior version. It seems that MISP is looking in CakePHP's Lib directory in `/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/` to find the ApacheSecureAuth class, which isn't found. However, using grep, I was able to find that the code resides in `/var/www/MISP/app/Controller/Component/`. However, the clean install of MISP doesn't seem to be calling that code, from what I can tell. Yes, I was able to have a clean install of MISP 2.4.47 work on Ubuntu 16.04 LTS with Apache 2.4.18, PHP 7.0.4 before attempting external authentication. PHP's LDAP module is installed and enabled.

```
/var/www/MISP/app/Config/config.php:

> $config = array (
>  'debug' => 1,
>  'Security' =>
>  array (
>    'level' => 'medium',
>    'salt' => 'removed',
>    'cipherSeed' => '',
>    'password_policy_length' => 6,
>    'auth'=>array('ApacheSecureAuth'),
>  ),
> ....
>  'ApacheSecureAuth' =>
>    array(
>        'apacheEnv' => 'REMOTE_USER',           // If proxy variable = HTTP_REMOTE_USER
>        'ldapServer' => 'ldap://blah.mydomain.com',   // FQDN or IP
>        'ldapProtocol' => 3,
>        'ldapReaderUser' => 'user',
>        'ldapReaderPassword' => 'password',
>        'ldapDN' => 'dc=blah',
>        'ldapSearchAttribut' => 'uid',          // filter for search
>        'ldapFilter' => array(
>            'mail',
>        ),
>        'ldapDefaultRoleId' => 3,               // 3:User, 1:admin. May be good to set "1" for the first user
>        'ldapDefaultOrg' => 'MYORG',      // uses 1st local org in MISP if undefined
>    ),

/etc/apache2/sites-enabled/misp.conf:

> < Location /users/login>
>    # This works since I took it from another server
>   # which is known to work
>    AuthType Basic
>     AuthBasicProvider ldap
>     AuthLDAPBindDN "user"
>     AuthLDAPBindPassword password
>     AuthLDAPURL "ldap://blah.mydomain.com:389/ou=yup?uid?sub?(objectClass=*)"
>     AuthName "MISP"
>    Require valid-user
> <  / Location>

/var/www/MISP/app/tmp/logs/error.log:

> 2016-05-25 16:24:40 Error: [CakeException] Authentication adapter "ApacheSecureAuth" was not found.
> Request URL: /users/login
> Stack Trace:
> # 0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(689): AuthComponent->constructAuthenticate()
> # 1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
> # 2 /var/www/MISP/app/Controller/AppController.php(193):
> 
> AuthComponent->startup(Object(UsersController))
> # 3 /var/www/MISP/app/Controller/UsersController.php(31): AppController->beforeFilter()
> # 4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243):
> 
> UsersController->beforeFilter(Object(CakeEvent))
> # 5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677):
> 
> CakeEventManager->dispatch(Object(CakeEvent))
> # 6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189):
> 
> Controller->startupProcess()
> # 7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167):
> 
> Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
> # 8 /var/www/MISP/app/webroot/index.php(92):
> 
> Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> # 9 {main}
```

**Comment by truckydev** [comment]
Hi,

I have add an anwser to https://github.com/MISP/MISP/issues/960
I think in you conf.php, you d'ont need to add this link : 

``` php
 'auth'=>array('ApacheSecureAuth'), 
```

Have you try without ?

**Comment by rjzak** [comment]
Without that, I see the login page as usual. Accessing the url http://misp.local/users/login/ shows me the browser login box, but I also see the MISP login page as usual. And it doesn't accept the LDAP credentials there either (and I didn't think that would work).

It seems to me, the idea is to have Apache verify the username and password with LDAP, storing the username in the REMOTE_USER variable. Then, MISP would look up that user ID to find the corresponding email address, since MISP uses email addresses not username/ID.

**Comment by truckydev** [comment]
First, sorry for my English and late answer.

Your idea is right ^_^. ApacheSecureAuth is for kerberos authentification.
As you say : Apache verify username store in REMOTE_USER.
https://github.com/MISP/MISP/blob/2.4/app/Config/config.default.php#L96
The whole authentication part is performed by apache.
you can find in this tread some samples:
https://github.com/MISP/MISP/issues/960

you can try to fixe user like this un apache  : 
```vim
SetEnv REMOTE_USER user
```

If set, appControler try here : 
https://github.com/MISP/MISP/blob/2.4/app/Controller/AppController.php#L99
And go to the php class ApacheSecureAuthComponent who extends AuthComponent

https://github.com/MISP/MISP/blob/2.4/app/Controller/Component/ApacheSecureAuthComponent.php#L24

And next, this is this file (ApacheAuthenticate.php) who use next of the config file to find the email user.
https://github.com/MISP/MISP/blob/2.4/app/Controller/Component/Auth/ApacheAuthenticate.php

here this code do this : 
Connect to ldap and : 
If the mail (misp user mail) is found, keep it to authenticate the user:
else create user in misp  and authenticate him.

So for you,

First try to fixe SetEnv with a valid user for your ldap.
I think it's a bad configuration in your conf file.
If it work : 
try to append this after ```$envvar = Configure::read('ApacheSecureAuth.apacheEnv');```
https://github.com/MISP/MISP/blob/2.4/app/Controller/AppController.php#L100
```php
var_dump($envvar);
var_dump($_SERVER[$envvar]);
```
Now  refresh your start page, you should see the contents of variables like "REMOTE_USER" and "myUserName"

If this information are bad, the error can come from the wrong ldap configuration of the <location></location> of your apache conf

**Comment by sim0nx** [comment]
In case someone else lands here who uses php-fpm instead of the apache module and can't get this to work... The remote user variable is called "REDIRECT_REMOTE_USER" in that case.

var_dump finally helped to find this.

**Comment by Kagee** [comment]
Closed as stale/support finished.. Several users have used the module since.
