### ISSUE TITLE
Empty servers created automagically

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1175]
I've noticed that since updating to 2.4.44 there are servers created automagically under Sync Actions -> List servers. 

![screenshot from 2016-05-26 11 00 25](https://cloud.githubusercontent.com/assets/16301608/15569459/42894f26-2331-11e6-84d1-7f4094ed2790.png)

These servers are assigned to the external organisation 0x1338. I don't have more information

**Comment by iglocska** [comment]
Could you remove them and git pull? This was fixed in
https://github.com/MISP/MISP/commit/113e46a84e45074c5b52db85d71602d175175c4e
Sorry about the invoncenience.

**Comment by h122015** [comment]
thanks for the info. I just deleted them and did a pull.

**Comment by Rafiot** [comment]
Please reopen if it is not fixed :)
