### ISSUE TITLE
Intel Sources

### ISSUE THREAD

**Issue by xsallowed** [MISP/MISP#1178]
Hi
I am trying to integrate criticathreat intel feeds and OTX feeds with MISP. Is there a quick and easy way of achieving the same? Do you have a list of threat intel sources that can be integrated with MISP at the moment?

**Comment by eg132** [comment]
https://github.com/gitunique/cti-scripts

**Comment by xsallowed** [comment]
Thanks 
Do you have any other scripts for collecting different intel sources in MISP

**Comment by adulau** [comment]
You have many ways to do import intel sources in MISP like:
- Convert feeds to the existing MISP feed format (like https://www.circl.lu/doc/misp/feed-osint/) by using [PyMISP](https://github.com/MISP/PyMISP).
-  If the intel source has a lookup service, you can build an [expansion module](https://github.com/MISP/misp-modules).
- We are working on a new framework for the import (that will be based on the misp-modules approach) where generic type of import will be supported like CSV or additional format.

I hope this helps.

**Comment by xsallowed** [comment]
Thanks this is great! just a quick one. How many intel sources are normal for MISP to have for normal threat intelligence

**Comment by Rafiot** [comment]
It depends on your definition of "normal" :) You generally never have to much sources.
