### ISSUE TITLE
Error When Scheduling Tasks

### ISSUE THREAD

**Issue by I-am-Sherlocked** [MISP/MISP#1180]
As explained before in #1123 , task scheduling is currently throwing 

> Error: [PDOException] SQLSTATE[01000]: Warning: 1265 Data truncated for column 'job_id' at row 1
> Request URL: /tasks/setTask

Since the process_id returned by CakeResque.php is a hex string, but TasksController.php is trying to save it as the job_id field in tasks, which is an int.
The actual jobs (scheduled for each server) are created in ServerShell.php. That field save either needs to be dropped, or a separate job needs to be created for that process_id, and the job_id be put in the task.

**Comment by sfossen** [comment]
PDO error
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'ee345b7c8fb9cfeee43cfa561c672c5e' for column 'job_id' at row 1
Error: An Internal Error Has Occurred.

Stack Trace

APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 461 → PDOStatement->execute(array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 427 → DboSource->_execute(string, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php line 415 → DboSource->execute(string)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1917 → Mysql->update(Task, array, array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1751 → Model->_doSave(array, array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1703 → Model->save(array, array)
APP/Controller/TasksController.php line 120 → Model->saveField(string, string)
APP/Controller/TasksController.php line 85 → TasksController->_pullScheduler(integer, string)
APP/Controller/TasksController.php line 70 → TasksController->_jobScheduler(string, integer, string)
[internal function] → TasksController->setTask()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(TasksController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(TasksController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by sfossen** [comment]
Task::reQueue will also fail with a similar error,

**Comment by I-am-Sherlocked** [comment]
Seems that every spot that task->job_id is being set:
- app/Model/Task.php
- app/Controller/TasksController.php

it's the returned value from CakeResque::enqueueAt which is the process_id (MD5). So the fix might be as proposed in #1123 , the job_id should actually be changed to a varchar.

**Comment by I-am-Sherlocked** [comment]
@iglocska Any news on this? Needs to be resolved for task scheduling to work.

**Comment by Rafiot** [comment]
@iglocska any news on that?

**Comment by iglocska** [comment]
Not yet, will try to have a look at this ASAP
