### ISSUE TITLE
Can't add Elements to a newly created Template.

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1188]
Seems similar to issue : 749. Trying to add Elements to a newly created template i face:

```
Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'misp.TemplateElement.id'; this is incompatible with sql_mode=only_full_group_by
Request URL: /templateElements/add/attribute/5
```

MISP 2.4.47 - Mysql 5.7.11

**Comment by iglocska** [comment]
Indeed it is, it's a new default setting in MySQL 5.6+. Will patch it
tonight

**Comment by iglocska** [comment]
I've pushed a fix but I am kind of fixing it blind as I don't have access to a system with mysql 5.7 right now. Could you let me know if it didn't fix it? Thanks in advance!

**Comment by Kafeine** [comment]
It seems it didn't fix here. 

`2016-05-30 08:46:56 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'misp.TemplateElement.id'; this is incompatible with sql_mode=only_full_group_by
Request URL: /templateElements/add/attribute/6
`

**Comment by iglocska** [comment]
Ah alright, will try to have a look tonight am at a conf so no access to my usual environment. Will keep yu posted here!
