### ISSUE TITLE
Events without attributes - warning for users and owner

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1189]
Following the recent update to keep a consistent approach for the event without attributes (or seen without attributes), I would like to propose a simple warning in the UI and the email notification body.

From a user perspective, a warning like this:

*This event doesn't have any attributes visible to you. Either the owner of the event decided to have
a specific distribution scheme per attribute and wanted to still distribute the event alone either for notification or potential contribution with attributes without such restriction. Or the owner forgot to add the
attributes or the appropriate distribution level. If you think there is a mistake or you can contribute attributes based on the event meta-information, feel free to make a proposal".

From a member of the organization who created the event (only when the event is missing attributes):

"This event doesn't contain any attribute. It's strongly advised to populate the event with attributes (indicators, observables or information) to provide a meaningful event".

This message should appear in the UI and the notification message.

**Comment by iglocska** [comment]
Hmm maybe for now we could do this for published events only? Or do we also want the message when the user creates the event? Not sure either way..

**Comment by iglocska** [comment]
I've added it for both published and unpublished events, but we can change it later on if it makes sense, just let me know!
