### ISSUE TITLE
Tooltip for correlation includes date but not everywhere

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1190]
The tooptip of the correlations shows the date of the correlating events in the top right. But the tooltip next to each attribute doesn't display the date. It might be interesting to have it in the attribute tooltip correlation.

Reported by @rommelfs

**Comment by iglocska** [comment]
Hmm, good point. I will have a look, I remember that the attribute and the
event correlations are fetched separately, so I have probable just added
the date to the event correlations.
