### ISSUE TITLE
Add tagg by attribut

### ISSUE THREAD

**Issue by ANSSI-BSOD** [MISP/MISP#1191]
Hi team,

regardless of the specific comments on an event. It would be interesting to add more description by attribute.

Example, define a relevant, if the pattern generates false positives .

A good example would be adding a CVSS : https://www.first.org/cvss/calculator/3.0

We might as well look for example all scorers with a particular tag and a CVSS than 3 .

**Comment by iglocska** [comment]
Definitely. Attribute tagging is on our short term roadmap.

**Comment by rotanid** [comment]
duplicate of #802
