### ISSUE TITLE
Installation, backup, and restore instructions for MISP on Ubuntu 16.04 with MariaDB

### ISSUE THREAD

**Issue by infde6** [MISP/MISP#1195]
Thought I would post this, in case it helps.I know it's not an issue, but didn't know where else to put it.

Would be willing to work with someone to get this polished and into the MISP documentation.

[MISP-Ubuntu-16.04_install.txt](https://github.com/MISP/MISP/files/293301/MISP-Ubuntu-16.04_install.txt)

INSTALLATION INSTRUCTIONS
------------------------- for ubuntu 16.04-server
### but, as always:

!USE AT YOUR OWN RISK!
## 1/ Ubuntu install with LAMP and dependencies

---

Install a minimal ubuntu server system with the LAMP software:

(Adapted from https://www.howtoforge.com/tutorial/perfect-server-ubuntu-16.04-with-apache-php-myqsl-pureftpd-bind-postfix-doveot-and-ispconfig/)
### Make sure your system is up2date:

apt upgrade
### Install depenencies

apt-get install **vim curl gnupg-agent git redis-server zip gcc make sudo binutils openssl imagemagick memcached mcrypt python python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev**
### Install Postfix

apt-get install **postfix**
You will get some questions, you will probably want to set:
- Postfix Configuration: Satellite system
- postconf -e 'relayhost = your.relay.here'

/etc/init.d/postfix restart
### Install MariaDB (MySQL alternative)

apt-get install **mariadb-client mariadb-server**
### Secure the MySQL installation

mysql_secure_installation
### Install Apache2

apt-get install **apache2 apache2-doc apache2-utils apache2-suexec-pristine libapache2-mod-fcgid libapache2-mod-fastcgi libapache2-modsecurity libapache2-mod-qos**
### Enable modules, settings, and default of SSL in Apache

a2enmod ssl
a2enmod suexec rewrite ssl actions include cgi
a2enmod dav_fs dav auth_digest headers
a2enmod actions fastcgi alias
a2dissite 000-default
a2ensite default-ssl
### Install PhP and dependencies

apt-get install **php7.0 libapache2-mod-php php-dev php7.0-common php-redis php7.0-gd php-mysql php7.0-imap php7.0-cli php7.0-cgi php-pear php-auth php7.0-mcrypt php7.0-curl php7.0-intl php7.0-pspell php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xmlrpc php7.0-xsl php-memcache php-imagick php-gettext php7.0-zip php7.0-opcache php-apcu php7.0-fpm php-crypt-gpg**

--> Apply all changes with service apache2 restart
## 2/ MISP code

---
### Download MISP using git in the /var/www/ directory.

cd /var/www/
git clone https://github.com/MISP/MISP.git 
### Make git ignore filesystem permission differences

cd /var/www/MISP
git config core.filemode false
### install Mitre's STIX and its dependencies by running the following commands:

cd /var/www/MISP/app/files/scripts
git clone https://github.com/CybOXProject/python-cybox.git
git clone https://github.com/STIXProject/python-stix.git
cd /var/www/MISP/app/files/scripts/python-cybox
git checkout v2.1.0.12
python setup.py install
cd /var/www/MISP/app/files/scripts/python-stix
git checkout v1.1.1.4
python setup.py install
## 3/ CakePHP

---
### CakePHP is now included as a submodule of MISP, execute the following commands to let git fetch it:

cd /var/www/MISP
git submodule init
git submodule update
### Once done, install CakeResque along with its dependencies if you intend to use the built in background jobs:

cd /var/www/MISP/app
curl -s https://getcomposer.org/installer | php
php composer.phar require kamisama/cake-resque:4.1.2
php composer.phar config vendor-dir Vendor
php composer.phar install
### Enable CakeResque with php-redis in your php.ini file:

vim /etc/php/7.0/apache2/php.ini
### add the following line:

extension=redis.so
### To use the scheduler worker for scheduled tasks, do the following:

cp -fa /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php
## 4/ Set the permissions

---
### Check if the permissions are set correctly using the following commands as root:

chown -R www-data:www-data /var/www/MISP
chmod -R 750 /var/www/MISP
chmod -R g+ws /var/www/MISP/app/tmp
chmod -R g+ws /var/www/MISP/app/files
chmod -R g+ws /var/www/MISP/app/files/scripts/tmp
## 5/ Create a database and user

---
### Enter the mysql shell

mysql -u root -p

mysql> create database misp;
mysql> grant usage on _._ to misp@localhost identified by 'misp password';
mysql> grant all privileges on misp.\* to misp@localhost;
mysql> exit

cd /var/www/MISP
### Import the empty MySQL database from MYSQL.sql

mysql -u misp -p misp < INSTALL/MYSQL.sql
## 6/ Apache configuration

---
#### A sample vhost can be found in /var/www/MISP/INSTALL/apache.misp.ubuntu

cp /var/www/MISP/INSTALL/apache.misp.ssl /etc/apache2/sites-available/misp-ssl.conf
### If a valid SSL certificate is not already created for the server, create a self-signed certificate:

openssl req -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=Country/ST=State/L=Locality/O=Organization/OU=Organizational Unit/CN=QDN.here/emailAddress=admin@your.FQDN.here" -keyout misp.local.key -out misp.local.crt
### Otherwise, copy the SSLCertificateFile, SSLCertificateKeyFile, and SSLCertificateChainFile to /etc/ssl/private/. (Modify path and config to fit your environment)

============================================= Begin sample working SSL config for MISP
<VirtualHost (IP, FQDN, or *):80>
        ServerAdmin admin@your.FQDN.here
        ServerName your.FQDN.here
        DocumentRoot /var/www/MISP/app/webroot

```
    Redirect permanent / https://your.FQDN.here

    <Directory /var/www/MISP/app/webroot>
            Options -Indexes
            AllowOverride all
            Order allow,deny
            allow from all
    </Directory>

    LogLevel warn
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
```

</VirtualHost>

<VirtualHost (IP, FQDN, or *):443>
        ServerAdmin admin@your.FQDN.here
        ServerName your.FQDN.here
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

```
    SSLEngine On
    SSLCertificateFile /etc/ssl/private/misp.local.crt
    SSLCertificateKeyFile /etc/ssl/private/misp.local.key
    SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

    LogLevel warn
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
```

</VirtualHost>
============================================= End sample working SSL config for MISP

a2dissite default-ssl
### 000-default can be called default based on distribution, in which case run a2dissite default

a2ensite misp-ssl
### Restart apache

service apache2 restart
## 7/ MISP configuration

---
### There are 4 sample configuration files in /var/www/MISP/app/Config that need to be copied

cd /var/www/MISP/app/Config
cp -a bootstrap.default.php bootstrap.php
cp -a database.default.php database.php
cp -a core.default.php core.php
cp -a config.default.php config.php
### Change base url in config.php

'baseurl' => 'http://your.FQDN.here',
### or if using https:

'baseurl' => 'https://your.FQDN.here',
### alternatively, you can leave this field empty if you would like to use relative pathing in MISP

'baseurl' => '',
### and make sure the file permissions are still OK

chown -R www-data:www-data /var/www/MISP/app/Config
chmod -R 750 /var/www/MISP/app/Config
### Generate a GPG encryption key.

mkdir /var/www/MISP/.gnupg
chown www-data:www-data /var/www/MISP/.gnupg
chmod 700 /var/www/MISP/.gnupg
sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --gen-key
### And export the public key to the webroot

sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --export --armor YOUR-EMAIL > /var/www/MISP/app/webroot/gpg.asc
### To make the background workers start on boot

chmod +x /var/www/MISP/app/Console/worker/start.sh
sudo vim /etc/rc.local
### Add the following line before the last line (exit 0). Make sure that you replace www-data with your apache user:

sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh
### you can do this by running the following commands:

chmod -R 750 /var/www/MISP/<directory path with an indicated issue>
chown -R www-data:www-data /var/www/MISP/<directory path with an indicated issue>
## Recommended actions
- By default CakePHP exposes his name and version in email headers. Apply a patch to remove this behavior.
- You should really harden your OS
- You should really harden the configuration of Apache
- You should really harden the configuration of MySQL
- Keep your software up2date (MISP, CakePHP and everything else)
- Log and audit
### MISP has a new pub/sub feature, using ZeroMQ. To enable it, simply run the following command

pip install pyzmq
### ZeroMQ depends on the Python client for Redis

pip install redis
# 
## For backups:
# 
### Copy the MISP configuration files at:

/var/www/MISP/app/Config/*
### Copy the encryption keys at:

/var/www/MISP/.gnupg
### Copy the MISP Apache config at:

/etc/apache2/sites-enabled/misp-ssl
### Copy the Apache PhP config at:

/etc/php5/apache2/php.ini
### Copy the SSL certificate files for SSL at:

/etc/ssl/private/*
### Dump the database

mysqldump -u misp -p misp > misp_db_bkp.sql.dump
### Copy any custom information at:

/var/www/MISP/app/webroot/img/orgs
/var/www/MISP/app/webroot/img/custom
/var/www/MISP/app/files
# 
## For recovery:
# 
### Restore the Apache PhP config:

copy backup/etc/php/7.0/apache2/php.ini to /etc/php/7.0/apache2/php.ini
### Restore the SSL certificate files:

copy backup/etc/ssl/private/\* /etc/ssl/private/
### Restore the MISP Apache configuration:

cp backup/etc/apache2/sites-enabled/misp-ssl.conf /etc/apache2/sites-available/
### Restore the encryption keys:

cp backup/var/www/MISP/.gnupg /var/www/MISP/.gnupg
### Restore the MISP configuration files:

cp backup/var/www/MISP/app/Config/\* /var/www/MISP/app/Config/
### restore the database

mysql -u misp -p misp < backup/misp_db_bkp.sql.dump
### Restore any custom information at:

backup/var/www/MISP/app/webroot/img/orgs
backup/var/www/MISP/app/webroot/img/custom
backup/var/www/MISP/app/files
# 
# Additional security considerations:
- Use the latest, updated version of Ubuntu (Ubuntu 16.04 as of this writing)
- Use two-factor authentication, if possible
- Turn AppArmor ON, and tune it for Apache, MariaDB and MISP usage
- Secure the MySQL installation using industry best practices
- Set Apache to use SSL ONLY
- Use suexec in Apache
- Set MISP to use SSL ONLY
- Set MISP to use encryption for all communications (email, DB, etc.)
- Enable and configure IPTables to limit access

[Uploading MISP-Ubuntu-16.04_install.txt…]()
[Uploading MISP-Ubuntu-16.04_install.txt…]()

**Comment by Rafiot** [comment]
The best way is to make a pull request, but we can do it if you prefer.

Thank you very much for the documentation!

**Comment by infde6** [comment]
Hello Raphael,

I'm new to github, but I would like to try the pull request. Should I branch from the main MISP BRANCH to something like, "INSTALL-Ubuntu-16.04"?

Thank you for all the work on this great application!

Regards,
Dave

**Comment by Rafiot** [comment]
For the name of the branch, up to you, it doesn't matter. But be careful to create the branch from 2.4 and not master (2.4 is the default, so it should not be a problem, but still). Then add a file called `INSTALL/INSTALL.ubuntu1604.txt` and put the documentation in there. When done, push the file on your own fork of MISP and do a pull request.

There is an other way by creating the file directly from the web interface but I'm not totally sure how that work.

**Comment by rotanid** [comment]
based on your text and the ubuntu 14.04 installation instructions i created Pull Request #1276 for ubuntu 16.04.

your text contains suggestions on backup&restore, i didn't include those as they don't really belong in the install doc.
maybe they should be used to extend the existing misp backup script: https://github.com/MISP/MISP/blob/2.4/tools/misp-backup/misp-backup.sh

**Comment by Rafiot** [comment]
I think we can consider this issue to be resolved, right?

**Comment by rotanid** [comment]
i guess so, if someone wants to use th backup&restore part of this we can still grab it here for a new PR.
