### ISSUE TITLE
Posting JSON to MISP - Sharing Group Ignored

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1196]
I'm attempting to post a new event to MISP, which includes a sharing group under the distribution level. If I post the following  json:

```
{  
   "Event":{  
      "info":"TEST 123",
      "sharing_group_id":1,
      "analysis":1,
      "published":false,
      "date":"2016-06-01",
      "distribution":4,
      "threat_level_id":2
   }
}
```

I get an event created, with the Distribution of 4, but a sharing group ID of 0. Any reason why this is occurring? I can't see where this is getting dropped. 

There isn't an issue if I create the event, then follow up with an update which includes the sharing_group_id of ID 1, but this is long-winded and slows the process down considerably.

**Comment by iglocska** [comment]
Woah that is odd. Will have a look at this soon

**Comment by tomking2** [comment]
Thanks!

**Comment by tomking2** [comment]
Were you able to look into this Andras? My workaround is currently working without issue, so there isn't any rush if not.

**Comment by tomking2** [comment]
Looks like the problem is still here, although now seems to function slightly differently!
The dumped JSON of the misp_event after being returned from:
```
misp_event.set_all_values(info="Test", distribution=4, 
                         sharing_group_id=1, threat_level_id=2,
                         analysis=0, date="2017-07-27")
```
Is:
```
{"Event": {
      "distribution": "4",
      "Attribute": [],
      "published": false,
      "analysis": "0",
      "date": "2017-07-27",
      "sharing_group_id": "1",
      "info": "Test",
      "threat_level_id": "2"}
}
```

Looks good? This ends up with an event being created with the Distribution set to "Your Organisation", not tied to the Sharing Group with ID 1 :(
I'm trying to make modifications to Viper at the moment, to allow better control of distribution levels on creation of events, plus allowing defaults to be set (nothing worse than accidentally releasing sensitive information!)

**Comment by adulau** [comment]
@tomking2 I suppose it's fixed. Could you test with one of the latest version? Thank you very much. I'll close the issue for the time being.
