### ISSUE TITLE
Add attribute type url-pattern 

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#120]
Add the attribute type url-pattern to store pcre regexp for URLs.

This would be perfect to implement/auto-generate more generic NIDS rules.
For example it would really handy to implement the patterns described in http://bit.ly/maltraffic

PHP has a pcre library - http://php.net/manual/en/book.pcre.php
Snort supports pcre in rules - http://manual.snort.org/node32.html#SECTION004523000000000000000
Suricata supports pcre in rules - https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Pcre_(Perl_Compatible_Regular_Expressions)

**Comment by adulau** [comment]
It seems that we forgot to add this one after the major new types import. The only issue is the required changes to the NIDS to support the export.

# Bro

- `url_regex` - https://www.bro.org/sphinx/scripts/base/utils/urls.bro.html

# Suricata

- `http_uri; pcre:` https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Pcre_(Perl_Compatible_Regular_Expressions)

# Snort
- `pcre`

**Comment by adulau** [comment]
There is a regexp objects in MISP:

- https://github.com/MISP/misp-objects/blob/master/objects/regexp/definition.json 

But need to find a way to link this with the NIDS export module.

Maybe the object need to be updated to include the scope of the regexp? like `url` or `pattern-in-memory?`

**Comment by adulau** [comment]
Fixed in the regexp object.
