### ISSUE TITLE
Freetext Import don't work

### ISSUE THREAD

**Issue by exp0se** [MISP/MISP#1201]
Freetext import doesn't appear to work. I am pasting couple of domains and IPs(also tried this with hashes or file names as well, doesn't seem to matter.) and information is correctly identified as IP, domains and hostnames. But when you hit Submit I got a 0 attributes created message and nothing is added. This is on a fresh install.

I got some some warnings in log, but nothing else:

`
2016-06-03 18:30:25 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Controller/EventsController.php, line 2766]
Trace:
EventsController::saveFreeText() - APP/Controller/EventsController.php, line 2766
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
`
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu 14.04 |
| OS version (client) | Windows 8.1 |
| PHP version | 5.5 |
| MISP version / git hash | 557d39ee36f7cc99540518a9c90d4472a0a9d802 |
| Browser | Chrome, Explorer |

**Comment by adulau** [comment]
Fixed in e24da853bbd183832f46b2dfa5d1e6fb36dcb961 Thank you very much for the report.
