### ISSUE TITLE
d3.js: two different (outdated) versions of script in MISP

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1220]
MISP uses d3.js (https://github.com/d3/d3) but there are two different versions:
app/webroot/js/d3.min.js (added with commit 888042dbd6eaff18a90d5d581c24aac6f5483f21 in Oct 2015)
app/webroot/js/d3.v3.min.js (last change in Feb 2014)

i think there should be only one version of d3.js (and perhaps we could also update to a newer version)

**Comment by Rafiot** [comment]
Yep, and they are used there:

```
app/View/Events/view_graph.ctp:<?php echo $this->Html->script('d3.min');?>
app/View/Users/statistics.ctp:  echo $this->Html->script('d3.v3.min');
```

**Comment by iglocska** [comment]
There should be no need to use d3.v3.min.js in the statistics, think that can be safely changed. Let me have a look if it breaks anything.

**Comment by rotanid** [comment]
if you do the change, please include the version number in the filename :)

**Comment by iglocska** [comment]
Sure. Adding some additional changes in the process.

**Comment by iglocska** [comment]
Done in the latest commit.
