### ISSUE TITLE
Duplicate attributes in same event

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1221]
When bulk adding attributes to events from the ajax add attribute, i sometimes get duplicate attributes.
I am adding thousands of attributes to 3 or 4 different events, one browser tab per event and not adding attributes concurrently to the same event.

The duplicate attributes have both the to_ids flag set.

Not sure how to diagnose or reproduce this.

**Comment by elhoim** [comment]
I have unique UUIDs and unique IDs for attributes, and they are not deleted but they have duplicate value, attribute type and attribute category.

**Comment by iglocska** [comment]
Hmph. That definitely sounds like a bug. Got any idea how I can reproduce it?

**Comment by elhoim** [comment]
My useage scenario was that I was adding domain attributes in 4 events from browser using the ajax "add attributes". Each event was in the thousands of domains.
I can send you files privately but artificial ones should work too.

Browser used was: Firefox 38.8 ESR on Windows 7

**Comment by iglocska** [comment]
Hmm, so the domains had a few duplicates I guess. I'll check sounds weird -
maybe there is some weird concurrency issue that allows it to skip the
validation? No idea how this can happen. I'll look into it.

**Comment by wilson-santos-pf** [comment]
Hi,

We are also facing the same concurrent problem.
Our data set sometimes has the same hostname, but with different ports. That data is exported as a "Network activity | hostname" attribute. 
We are making concurrent requests to MISP's API using PyMISP. This causes attributes to be duplicated. Even the tags on those attributes get duplicated. Then when publishing the event we get an exception like this _"Failed validating 'uniqueItems' in schema"_.
On sequential requests MISP rejects this, and simply says that a similar attribute already exists.
We are using MISP **2.4.80**.

**Comment by iglocska** [comment]
This should now be fixed. Bulk imports now pre-validate and deduplicate before saving the data.

**Comment by elhoim** [comment]
Revisiting this one: the closing rationale (bulk imports pre-validate and deduplicate) is the `value|type|category` hash dedup in `Event::_add()` (app/Model/Event.php:5410), which only covers duplicates *within a single submitted batch on event creation*. Two things are still open:

1. `valueIsUnique()` (app/Model/MispAttribute.php:972) is a check-then-act `find()`-then-`save()` with no transaction, row lock or upsert, and `attributes` has no unique key on `(event_id, type, category, value)` — `INSTALL/MYSQL.sql:116-128` and `db_schema.json` show unique keys on `id` and `uuid` only. So the concurrent-API-call case @wilson-santos-pf reported above is still structurally possible. Properly closing that needs a DB unique index (schema migration + cleanup of existing duplicates), which is a maintainer call — I have not attempted it.

2. A concrete bug that produces duplicates without any concurrency: the `value.uniqueValue` rule is `unset()` in three places and never restored. Because CakePHP models are registry singletons, that leaks for the rest of the request/worker run — so during a pull, the first newly captured event disables the duplicate check for every event `_edit()`ed afterwards in the same job. PR for that: #10972 (application-level only, `Refs #1221`, not a claim that the whole issue is closed).

Not asking to reopen — just recording the analysis. Caveat: reasoned from code, I had no instance to reproduce against.
