### ISSUE TITLE
Feature: Confidence and Priority scores

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1248]
it would be useful to include a confidence and priority score to use against attributes (the priority could be taken from the Threat-Level of the event). This could be used to identify that when a sighting is seen, it can be quickly identified to see whether the threat is high-priority, or get an understanding as to whether it may be a false-positive or not.

**Comment by adulau** [comment]
I think it's partially related to #802 (tagging at attribute level) which is one of the feature wants to implement after the import/export modules (that should be released very soon ;-).

Regarding the confident level, do you have a specific idea? The admiralty scale (https://github.com/MISP/misp-taxonomies/tree/master/admiralty-scale) is enough or maybe you have something else in mind?

Concerning the priority score, I'm also very interested in any existing standards that we could translated into a misp-taxonomy. I recently discovered this one https://www.us-cert.gov/sites/default/files/publications/NCCIC_Cyber_Incident_Scoring_System.pdf and will be translated in the misp-taxonomy.

**Comment by tomking2** [comment]
I agree - It's definitely related to #802. Having the ability for tagging an attribute will mean that we can use the Admirality score you have mentioned, which would completely satisfy the requirement for Confidence.

With the priority score - I am not aware of any standards which may be useful for this - The NCCIC Scoring System is good, but I fear that events will remain in Green or Yellow if the particular definitions are closely followed, and this is largely focused on Incident data, not simply research into a particular threat.

**Comment by adulau** [comment]
The attribute level tagging has been implemented in MISP 2.4.60. 

We did some improvement for the confidence level too:

https://github.com/MISP/misp-taxonomies/blob/master/misp/machinetag.json#L31

Feedback welcome.

**Comment by adulau** [comment]
In MISP 2.4.66 has been extended with expiration and false-positive type. Feel free to test and provide us feedback and don't hesitate to reopen this issue.
