### ISSUE TITLE
When accessing MISP instance via hostname, redirects to /users/login constantly. Access by IP address appears to be fine

### ISSUE THREAD

**Issue by da667** [MISP/MISP#1249]
Hello! I'm unsure at this point if this is a bug or PEBKAC on my part, but I'm running into the following issue:

-I've set up MISP, utilizing SSL, with a self-signed port, running the server on a non-default web port (e.g. not 443)
-When I visit https://a.b.c.d:9443, I'm greeted with a login page. The login page works, and I'm able to access the various bits and pieces of my MISP instance.
-When I visit https://my.domain:9443, I'm greeted with a login page. I log in, and immediately I get redirected back to /users/login instead of /events/index

I check /var/log/apache2/*.log
I check syslog
and for giggles, I even check dmesg.

I don't get any useful information or any indications that there's a problem, in fact, the logs confirm that I'm able to successfully log in.

I searched previous cases that seem to indicate that CakeResque/CakePHP weren't install correctly, but I double and triple checked that I installed them correctly, that the config.php file is in the right place, that the last few lines in the file aren't commented out.

I also read the cases where it's suggested that base_url needs to be modified. I've modified base_url in /var/www/MISP/app/Config/config.php to use the following values with no success:
'https://myhost.com:9443'
'' (blank, the default setting)
neither of these settings resolved the issue. I'm at a loss at this point, so any help you can offer is appreciated. Please let me know if you need more information than what I've provided.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug(possibly?)/Support |
| OS version (server) | **uname -a**:4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 |

```
                                     UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
                                     **lsb_release -a**: Distributor ID: Ubuntu
                                     Description:    Ubuntu 16.04 LTS
                                     Release:        16.04
                                     Codename:       xenial
```

| OS version (client)       | Windows 10, Firefox 46.0.1
| PHP version               | **php -v**:PHP 7.0.4-7ubuntu2.1
| MISP version / git hash   | {"major":2, "minor":4, "hotfix":48}
| Browser                   | Firefox 46.0.1
### Expected behavior

When using my server's hostname/DNS name, to be able to login to my MISP instance
### Actual behavior

repeated 302 redirects to /users/login when I use the hostname of my MISP instance. 
### Steps to reproduce the behavior

Unknown at this time.
### Logs, screenshots, configuration dump, ...

snippet from /var/log/apache2/error.log - these logs confirm that I'm able to log in successfully or at least such that MISP things it's successful. Then I attempt to make changes (e.g. base_url, remove a couple of vhost SSL configurations, etc.) and restart the service
/var/www/MISP/app/tmp/logs/[32668]: 2016-06-09 08:59:56 Notice: User (1): deusexmachina667@gmail.com -- login
/var/www/MISP/app/tmp/logs/[32671]: 2016-06-09 09:00:21 Notice: User (1): deusexmachina667@gmail.com -- login
/var/www/MISP/app/tmp/logs/[32671]: 2016-06-09 09:01:03 Notice: User (1): deusexmachina667@gmail.com -- login
/var/www/MISP/app/tmp/logs/[32733]: 2016-06-09 09:03:54 Notice: User (1): deusexmachina667@gmail.com -- login
[Thu Jun 09 09:04:28.535606 2016] [mpm_prefork:notice] [pid 32665] AH00169: caught SIGTERM, shutting down
[Thu Jun 09 09:12:53.800782 2016] [mpm_prefork:notice] [pid 32915] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips configured -- resuming normal operations
[Thu Jun 09 09:12:53.800799 2016] [core:notice] [pid 32915] AH00094: Command line: '/usr/sbin/apache2'
/var/www/MISP/app/tmp/logs/[32921]: 2016-06-09 09:13:28 Notice: User (1): deusexmachina667@gmail.com -- login
/var/www/MISP/app/tmp/logs/[32920]: 2016-06-09 09:21:15 Notice: User (1): deusexmachina667@gmail.com -- login
[Thu Jun 09 09:23:02.764497 2016] [mpm_prefork:notice] [pid 32915] AH00169: caught SIGTERM, shutting down
[Thu Jun 09 09:23:02.866516 2016] [mpm_prefork:notice] [pid 33006] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips configured -- resuming normal operations

here's a copy of what /etc/apache2/sites-available/misp-ssl.conf looks like right now (notice the hashes/octothorpes disabling a lot of the configuration settings I have in place):
<vhostfile>
VirtualHost *:9443
        ServerAdmin me@me.local
        ServerName myserver.com

```
    DocumentRoot /var/www/MISP/app/webroot
    <Directory /var/www/MISP/app/webroot>
            Options -Indexes
            AllowOverride all
            Order allow,deny
            allow from all
    </Directory>

    #RewriteEngine On
    #RewriteCond %{HTTPS} off
    #RewriteRule (.*) https://%{HTTP_HOST}:9443%{REQUEST_URI}

    SSLEngine On
    #SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    #SSLCipherSuite EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA
    #SSLProtocol All -SSLv2 -SSLv3
    #SSLHonorCipherOrder On
    #Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
    #Header always set X-Frame-Options DENY
    #Header always set X-Content-Type-Options nosniff
    #SSLCompression off
    #SSLSessionTickets Off
    #SSLUseStapling on
    #SSLOpenSSLConfCmd Curves secp384r1
    SSLCertificateFile /etc/apache2/ssl/misp.crt
    SSLCertificateKeyFile /etc/apache2/ssl/misp.key
    #SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

    LogLevel warn
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
```

VirtualHost
# SSLStaplingCache "shmcb:logs/stapling-cache(150000)"

</vhostfile>

Please let me know if you need more information

**Comment by da667** [comment]
Just to make sure that the issue isn't PEBKAC I'm going to run through the entire install process and see if I can re-create this.

**Comment by da667** [comment]
Confirmed the issue persists in a brand new Ubuntu 16.04 server. I didn't use any special vhost configs. I followed the instructions presented in the MISP guide for 16.04 here:
https://github.com/MISP/MISP/issues/1195

-Fresh install, navigate to https://hostname.com:9443
-enter admin@admin.test/admin
-302 redirect to https://host.com:9443/users/login

So I'm not crazy.

**Comment by da667** [comment]
I had one of my friends help me look at this and we think we've narrowed down where the problem is

`192.168.1.17 - - [09/Jun/2016:15:32:33 -0400] "POST /users/login HTTP/1.1" 302 780 "https://site.com:9443/users/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"
192.168.1.17 - - [09/Jun/2016:15:32:34 -0400] "GET / HTTP/1.1" 302 297 "https://site.com:9443/users/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"
192.168.1.17 - - [09/Jun/2016:15:32:34 -0400] "GET /users/login HTTP/1.1" 200 2225 "https://site.com:9443/users/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"`

it looks like the POST request is going to going to https://site.com:9443/users/login/users/login

Something in the login script is duplicating the post-base_url content.

(special thanks to @munin on twitter for troubleshooting this with me)

**Comment by iglocska** [comment]
Very odd. I Am currently travelling and only have access to a few 14.04 dev instanes atm, but I'll try to look into this asap. I haven't looked at the install guide that you've used yet, but will make sure to give it a shot soon.

**Comment by rotanid** [comment]
today i also tested MISP on ubuntu 16.04 and did also use SSL on ports 443 and even your choice 9443. but i didn't run into the problem you report, it simply works, i also created a documentation, see https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

**Comment by adulau** [comment]
We assume the issue is fixed. If you still have the issue, feel free to reopen. Thank you.

**Comment by xme** [comment]
I'm facing also an issue (see #2152) but, by reading your description, it seems that my problem is the same. How did you solve it?

**Comment by johestephan** [comment]
Looks like I have the same problem on a fresh install from today.

Firefox: Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

Ubuntu 16.04

**Comment by JialuZhang** [comment]
@da667 

In your posted configuration,
```
    #RewriteEngine On
    #RewriteCond %{HTTPS} off
    #RewriteRule (.*) https://%{HTTP_HOST}:9443%{REQUEST_URI}
```
contains silent misconfiguration. This means adding it to your system will not change any system behavior.

"RewriteEngine off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond". (without commenting all the "RewriteRule" and "RewriteCond")

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, you can specify “RewriteEngine Off” in your confiugration.

For example, 
```
    RewriteEngine Off
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}:9443%{REQUEST_URI}
```

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
