### ISSUE TITLE
SSL client certificate fields for sync servers

### ISSUE THREAD

**Issue by koenigswinter** [MISP/MISP#1253]
Feature Request

If MISP access (web frontend & API) is protected by SSL client certificates, it would be helpful to add the appropriate fields in the MISP sync server settings (Sync actions -> List servers) like PEM file of the private key and password.

Google Groups MISP Development: https://groups.google.com/forum/?hl=en#!topic/misp-devel/M4po0Qsu7PA

**Comment by iglocska** [comment]
Very good idea. We should definitely go for this.
