### ISSUE TITLE
(re)syncing tags between MISP instances

### ISSUE THREAD

**Issue by michael-kerscher** [MISP/MISP#1258]
I had several issues with syncing some tags between two MISP instances.

The first issue is that the sync user role in my setup had no Tagger nor Tag Editor permission. It was installed initially with some 2.4.x code and upgraded several times to the most current version so permissions might have been created that way with an older version.

But nevertheless some of the tags like tlp and malware_classification but no circl:incident-classification or malware-classification have been synced (but marked exportable on the pushing server)

Another issue is that it is not possible to resync tags as adding tags do not "edit" the event. But even after manually editing the event to create some "change" and republishing it does not push the tags to the second instance. The tags have been marked as exportable but do not show up.

If you need more information feel free to ask me.

**Comment by r-anthony** [comment]
Hello,

I have exactly the same problem. I need to synchronize tags between 2 MISP instances (1 master and 1 slave), it doesn't seem to work. Is it ?

I tried to add and edit attributes, edit the event, publish, force pull/push but tags are not resynchronized.

 The only work arround I found is to delete the event on the "slave" instance and pull back the event.

**Comment by adulau** [comment]
This is indeed a known issue. We are working a fix in the short-term. Thank you for reporting.

**Comment by elhoim** [comment]
The impact is mostly low for tags that are just informative; but for tags that are giving context on information sharing policy (namely TLP tags) the impact is a higher, so adding label prio-high to this ticket.

**Comment by iglocska** [comment]
Indeed, this will need a larger change though. Maybe what we need to do is take a similar route to some other objects such as proposals (timestamps, revocations, etc), and to sync them out of bound.

**Comment by cgi1** [comment]
This issue still exists in MISP 2.4.59.

**Comment by iglocska** [comment]
It is mitigated as of 2.4.6x. Basically adding a tag to an attribute/event now unpublishes the event and sets a new timestamp, ensuring that the objects get synchronised.

**Comment by iglocska** [comment]
The above mitigation has been working well ever since, closing this for now.
