### ISSUE TITLE
Empty comments may be added to events

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#1263]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu 14.04 |
| OS version (client) | OS  X 10.10.5 |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.47 c26c0522be8338c88703e994fc962dad5b60e7ed |
| Browser | Firefox 46.0.1 |
### Expected behavior

Attempting to add an empty comment to an event should fail.
### Actual behavior

Pressing **Send** to post a comment without any comment text in the form does post the comment to the event - empty.
### Steps to reproduce the behavior
1. Create new event
2. Click **Send** button on an empty comment form

**Comment by adulau** [comment]
Thank you for the report.

**Comment by cristianbell** [comment]
I wanted to fix this issue and was thinking it'll be very fast fix. Some check at the js level and another check in the PHP and done. 

Boy was I wrong! 

I find the whole approach a little cumbersome and I'd like to do something like this:
- remove the CakePHP generation of js code - which is anyways long deprecated and removed in 3.x; 
- the js click on the Send button calls a script via jquery; 
- depending on the answer (success=true/false) a HTML container is created dynamically and added to the parent (prepend or append) OR an error message is displayed. 

Once implemented the js function can be used also when loading the page: the script just passes to it a json and the js function displays all comment entries. (create HTML element, add 2 parent) 

This will be a bigger change as the function that handles the comments also handles other cases (event, thread, post). 

Before I start anything I'd like to get some feedback.. 

Thanks!

**Comment by iglocska** [comment]
Fixed.
