### ISSUE TITLE
Sort not working while browsing feed

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1265]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.48 |
| Browser | Firefox 45.2.0 ESR |
### Expected behavior

While browsing a feed clicking on columns like Date and Timestamp should sort the rows.
### Actual behavior

No sorting occurs.
### Steps to reproduce the behavior

Sync actions --> List Feeds --> Looking glass --> Data column
### Logs, screenshots, configuration dump, ...

No indication in the logs

**Comment by adulau** [comment]
Thank you for the report.

**Comment by BenjaminJoly** [comment]
As the columns are not there anymore, and as I've no sort problem in the feed list, I close the issue. Do not hesitate to tell me if I have to reopen it !
