### ISSUE TITLE
Sort on id not working while browsing sync server

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1266]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.48 |
| Browser | Firefox 45.2.0 ESR |
### Expected behavior

While browsing a sync server clicking on columns the id column should sort the rows.
### Actual behavior

All rows disappear 
### Steps to reproduce the behavior

Sync actions --> List Servers --> Looking glass --> Id column
### Logs, screenshots, configuration dump, ...

No indication in the logs

**Comment by iglocska** [comment]
That is weird, guess something is wonky with the custom paginator.
