### ISSUE TITLE
MISP push jobs does not working

### ISSUE THREAD

**Issue by Deventual** [MISP/MISP#1267]
Hello,

Recently i found out that some of the jobs are getting stuck; furthermore they are not fully committed.
My main concern is that the push job are not even commencing. 
I'm using the latest version on all of my MISP instances.

What do you recommend to resolve this issues?

I will greatly appreciate any help on this matter,
Best regards!
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, support |
| OS version (server) | CentOS |
| MISP version / git hash | 2.4.48 |

**Comment by iglocska** [comment]
From what I can tell they are finishing fine for our instances, could you check the error logs from when they fail? Especially interesting are the following:

/var/www/MISP/app/tmp/logs/error.log
/var/www/MISP/app/tmp/logs/worker-error.log
/var/www/MISP/app/tmp/logs/worker-[date].log

Thanks in advance!

**Comment by Deventual** [comment]
I found that after i doing an pull (that was working until few weeks ago),
the jobs counter in the worker page is equal zero:  "Jobs in the queue: 0" for all workers.
It's seems that maybe there is problem with the queue list and the jobs is not submitting.
the publish is working but in the jobs page it seems that it not even starting.
What should i do to resolve this?

**Comment by elhoim** [comment]
Are your workers started?
Are the permissions correct to start the workers?
Is your redis accssible? (ie: can you connect using redis-cli?)

**Comment by Deventual** [comment]
all workers started and it's written (The worker appears to be healthy.)
the permission are as in the update guide.
and the redis is accessible.

**Comment by RichieB2B** [comment]
So when you set the push_all job to a time in the future on the Scheduled Tasks page do you see anything in the logs when they time passes?

**Comment by Deventual** [comment]
on which log exactly?

**Comment by Deventual** [comment]
This problem occur on all of the jobs.

**Comment by adulau** [comment]
We will close this issue. If the issue persists, feel free to reopen the ticket.
