### ISSUE TITLE
AutoMISP

### ISSUE THREAD

**Issue by da667** [MISP/MISP#1270]
Hello! I created a script that automatically installs MISP on ubuntu 16.04. The script handles most of the prereqs and configuration requirements (with exception to GPG and Postfix configuration), etc. I wanted to make your aware for documentation purposes.

The script handles a bunch of error conditions, verifies the majority of the commands complete successfully, logs actions taken to /var/log/misp_install.log, and if for some reason a command fails, exits the script and refers to the log file for more info.

Hopefully this helps others get set up easily :) https://github.com/da667/AutoMISP

**Comment by adulau** [comment]
Hi @da667 Thank you very much for your contribution, it looks very nice. A small thing, could you set the password as arguments? to avoid people reusing the same hard-coded password. 

It would be really great if you could make a pull-request to add the installer in the official repository of MISP in ./INSTALL.

Thanks again.

**Comment by da667** [comment]
Ah, that's actually a great idea. I'll work on it and submit soon

**Comment by cristianbell** [comment]
super work, thank you!

**Comment by cristianbell** [comment]
So I was looking at this and there are lots of packages being installed. (for example imagemagick, memcached, php7.0, mcrypt... ). 
Though not that severe can you please limit it to the packages really required by MISP? 
for Ubuntu 16 should be: libapache2-mod-php php php-cli php-crypt-gpg php-dev php-json php-mysql php-opcache php-readline php-redis
curl gcc git gnupg-agent make python openssl redis-server sudo vim zip 
But better see in the install guide: [https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt](https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt)

Or with your permission, I can change the script and add it to the repository.

**Comment by iglocska** [comment]
Python dev at least is required by the STIX/cybox package and possibly for
some other Python components.

**Comment by cristianbell** [comment]
saw that and edited the comment taking python-dev out, :)

**Comment by da667** [comment]
No problem. I'll have an update and pull request out today.

**Comment by iglocska** [comment]
Excellent, looking forward to it!

**Comment by cristianbell** [comment]
@da667 added the script for ubuntu14 (+passwords from the command prompt, less packages) to a fork of ur repo, see PR.

**Comment by r-anthony** [comment]
I just ran this script on a fresh ubuntu 16.04 : it runs perfectly, it's wonderfull, thank you very much for this work !

**Comment by cristianbell** [comment]
yep, I also tested it, and it works great. 
@da667 I can also update it as I did w/ the one for ubuntu 14 (passwords, CA info, removing... from the command prompt, no unecessary packages) and create a PR for it. Just let me know.

**Comment by iglocska** [comment]
Great job, will test it over the weekend and merge it. This will make life a lot easier for many folks out there.

**Comment by daverstephens** [comment]
Nice work! Thanks very much - I shall retire my clumsy install script in favour of this one :)

**Comment by rotanid** [comment]
reference: discussion about this goes on here: #1284
