### ISSUE TITLE
Details about the configuration file

### ISSUE THREAD

**Issue by ANSSI-BSOD** [MISP/MISP#1272]
Hi team,

We found that when using the Kerberos authentication, the user contained no organization.
The error come from a poor example in the configuration file.

https://github.com/MISP/MISP/blob/2.4/app/Config/config.default.php#L111

``` php
'ldapDefaultOrg' => 'example.com',      // uses 1st local org in MISP if undefined
```

"dapDefaultOrg" variable must contain an Int. Eg "1" for the first registered organization.
The interesting use may create an organization just for users with Kerberized authentication and to indicate in the "id" in the configuration file

For clarity could you replace this line (#L111) by : 

``` php
'ldapDefaultOrg' => '1',      // uses your local first "org_id" in MISP if undefined
```

Thx
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Support |
| MISP version / git hash | 2.4 |

**Comment by adulau** [comment]
Thank you very much.
