### ISSUE TITLE
Error: [BadRequestException] The request has been black-holed bulk-editing event attributes

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#1273]
Same issue I believe as #1055.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu 14.04 |
| OS version (client) | OS X 10.10.5 |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.47, last commit from log c26c0522be8338c88703e994fc962dad5b60e7ed |
| Browser | Firefox 46.0.1 |
### Expected behavior

Attempting to bulk edit attributes on an event should complete when form submitted.
### Actual behavior

Submitted bulk attribute edit form results in spinning "Loading" indicator and no changes to attributes on page reload.

An error is written to MISP error log (shown below).

The following is written to the browser console when selecting attributes and submitting form:

```
Empty string passed to getElementById(). jquery-2.1.0.min.js:2:23965
Empty string passed to getElementById(). jquery-2.1.0.min.js:2:23965
Empty string passed to getElementById(). jquery-2.1.0.min.js:2:23965
```

Have double-checked _MISP.baseurl_; appears to be set correctly with no trailing slash.
### Steps to reproduce the behavior
1. Input multiple attributes on an event - do not select _"for Intrusion Detection System"_
2. From Event view, select one or multiple events, and click icon at top of attributes for "Edit selected Attributes."
3. For the bulk edit form, change _"For Intrusion Detection System"_ to Yes for all selected attributes.
4. Click Submit

This occurs whether one or multiple attributes are selected.
### Logs, screenshots, configuration dump, ...

The following error is written to error.log:

```
2016-06-16 18:22:22 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/editSelected/204
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
Weird, I cannot reproduce this. I followed your step but it works fine.

Some things I've tried additionally:

Tried with several roles (site admin / publisher)

Tried it after a fresh load of the event view and right after publishing.

Not sure what is causing it.

**Comment by iglocska** [comment]
Never mind. Just reproduced it, it has to do with pagination parameters being passed along and the CSRF protection only hashing the generic URL. Looking into a fix.

**Comment by iglocska** [comment]
Have to look more into this, I was wrong about having reproduced it. I've fixed a notice error in the process, but I have yet to see what's going on. Will try more later.

**Comment by dspruell** [comment]
Seems like the root error relating to blackhole protection reason isn't totally clear from PHP code. Does debug need to be increased or is the PHP logic informative enough at all?

**Comment by giedriusramas** [comment]
I have the same issue.
Request URL: /attributes/editSelected/76
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

MISP v2.4.50

**Comment by iglocska** [comment]
This was solved a while ago and should work correctly since.
