### ISSUE TITLE
pecl/redis version issues on CentOS7 / Ubuntu 14.04

### ISSUE THREAD

**Issue by peasead** [MISP/MISP#1274]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Support |
| OS version (server) | CentOS |
| OS version (client) | 7.2.1511 |
| PHP version | 5.6.5 |
| MISP version / git hash | 2.4, 5191b283e9cc20b8b7b6214ad73098c4d87c4b87 |
| Browser | Not applicable |
### Expected behavior

`[root@localhost app]# pecl install redis`  (from line 108 of the CentOS 7 build guide)
This should install the PHP extension for interfacing with Redis
### Actual behavior

```
pecl/redis requires PHP (version >= 7.0.0, version <= 7.1.0, excluded versions: 6.0.0), installed version is 5.6.5
No valid packages found
install failed
```
### Steps to reproduce the behavior

I've followed the instructions in CentOS 7 several times, with the same result. 

I researched the error and tried to install `phpredis` using the instructions here: https://github.com/phpredis/phpredis and https://pecl.php.net/package/redis, but with no luck.

I'm not certain if it is normal, but when I ran `php composer.phar config vendor-dir Vendor` (line 104 of the CentOS 7 build guide) earlier, it just returned to the prompt vs. any output like the other `php` commands did...not sure if that's expected or related, just trying to give all the info I have

**Comment by Rafiot** [comment]
Can you please try to do `pear install redis-2.2.8`? It seems the newest version (3.0.0) requires php 7.*

**Comment by peasead** [comment]
Thanks for the response, @Rafiot 

No dice.

I ran `pear install redis-2.2.8` and I get the following:

```
[root@misp app]# pear install redis-2.2.8
No releases available for package "pear.php.net/redis" - package pecl/redis can be installed with "pecl install redis"
install failed
```

I also tried to install Redis 2.2.8 from source hoping that might close the gap, but the the issue with `pear install redis-2.2.8` and `pecl install redis` remained.

I also tried to convert to PHP 7, I was able to fight through a few issues, but stopped because I got the feeling that there would be conflicts further down the road and 5.6 to 7 was a big change.

Any other sugguestions?

**Comment by Rafiot** [comment]
Sorry, I meant `pecl install redis-2.2.8`.

**Comment by peasead** [comment]
Disco. Thanks mate.

I've forked this and am rebuilding the CentOS install instructions and will submit a pull request when it's completed.

Thanks.

**Comment by Rafiot** [comment]
Excellent, thank you very much, looking forward for the documentation update! :)

**Comment by johnfellers** [comment]
this happens on Ubuntu 14.04 as well and they above mentioned change fixes the install. you should consider updating those install instructions as well.

**Comment by rotanid** [comment]
@johnfellers could you please try to uninstall redis via pecl and afterwards install the ubuntu package:

```
pecl uninstall redis
sed -i "/redis.so/ d" /etc/php5/apache2/php.ini
apt-get install php5-redis
php5enmod redis
service apache2 restart
```

that probably won't help for centos, but for ubuntu - and is cleaner than using the pecl package and editing the php.ini

**Comment by johnfellers** [comment]
I'll give it a shot and let you know.

**Comment by johnfellers** [comment]
@rotanid - your recommendation worked as well. thank you.

**Comment by FadelChafai** [comment]
You can try to reinstall an older version of pecl/redis ( i had the same issue with Mag 1 )
pecl uninstall redis
pecl install redis-3.1.2
