### ISSUE TITLE
install docs deb8/ubu16: curl obsolete?

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1280]
the install documentation for debian8 and ubuntu16 states we have to install curl as a dependency.
i think this was only there because it was used to download composer (and directly feeding it to php).
as i replaced that with a download method that is a bit less error prone and using wget, curl might be obsolete.

but i don't know if misp itself or composer or whatever tool also needs curl, so someone who knows more about misp should check this please.

@cristianbell brought this up as he noticed it while doing a updated centos/rhel install doc.

**Comment by Rafiot** [comment]
Speaking of that, I use composer installed systemwide in the [travis install](https://github.com/MISP/MISP/blob/2.4/.travis.yml#L54) and [that file](https://github.com/MISP/MISP/blob/2.4/app/composer.json)

It is cleaner than using wget. Maybe we should change that in the documentation. Also, it would be cool to have all the PHP dependencies managed by composer. 
What do you think?

**Comment by iglocska** [comment]
Curl is only really needed for the API examples for quick tests, but we can make it obsolete and just let people test the APIs using PyMISP.

**Comment by cristianbell** [comment]
@iglocska one can also use wget for testing the APIs. And it's already pre-installed on some distributions, which makes it a slightly better choice than curl. But yes, @Rafiot 's idea is pty cool/the better way!

**Comment by iglocska** [comment]
One can do those tests using many tools, including PyMISP which comes installed with MISP. The example tests are written for cURL, so just removing them would mean that the examples themselves become obsolete. If you are willing to rewrite them then of course it is no problem.

**Comment by iglocska** [comment]
Also, a quick heads-up, before you do a PR for removing curl: after a quick search, it looks like CakeResque uses monolog which requires cURL. Just check if it causes any issues if you remove it.

**Comment by rotanid** [comment]
i didn't want to do a PR, just having a discussion.
following this conversation i'd rather close this issue as curl seems to be necessary - and even if it wouldn't be, it doesn't really hurt having it.

**Comment by iglocska** [comment]
Sounds good @rotanid, and again thanks a lot for looking into all the deprecated stuff.
