### ISSUE TITLE
Cache jobs do not update the date modified once completed

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1289]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug. |
| MISP version / git hash | 2.4.47 |
### Expected behavior
- Date modified is updated when cache job 
### Actual behavior
- date modified is not updated
### Steps to reproduce the behavior
- Create a cache update job
- make sure it runs
- wait until it's finished
- look at the 'date created' and 'date modified' ; both timestamps are always the same , even if the process took some time.

**Comment by rotanid** [comment]
PR #1315 should have fixed this.
