### ISSUE TITLE
Sort of events when remote viewing instance is not working

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1296]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| MISP version / git hash | 2.4.47 on the remote instance / 2.4.48 on the instance used to browse remotely |
### Expected behavior

Return the list of events sorted by id
### Actual behavior

Blank list of events
### Steps to reproduce the behavior

Go to _Sync Actions_ > _List Servers_ 
_Explore_ a remote server
On the list of events, sort by id (asc or desc does not change anything)

**Comment by iglocska** [comment]
Fixed in https://github.com/MISP/MISP/commit/f7f48498a46875886cd3f5c9c4e3a8c74b63104e

The remote has to be updated
