### ISSUE TITLE
Cross-events attributes

### ISSUE THREAD

**Issue by deresz** [MISP/MISP#130]
The database structure change to HABTM between events and attributes. This will 
- make a single attribute live across multiple events which allows potential performance gains and eliminate the need of correlation as it is used now.
- if there are multiple events caused by the same threats, there will be probably IOCs shared between them. In this case it will eliminate the duplication of data.
- it will allow to update a signature shared by different events

**Comment by elhoim** [comment]
Has this been changed?

**Comment by iglocska** [comment]
Nope and it most likely won't until the big datamodel rework. Pushing the milestone on this back.
