### ISSUE TITLE
Streamline installation of PHP dependencies with Composer

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#1302]
Considering current setup instructions from the Ubuntu installation guide: 

> Once done, install CakeResque along with its dependencies if you intend to use the built in background jobs: 
> `cd /var/www/MISP/app`
> `curl -s https://getcomposer.org/installer | php`
> `php composer.phar require kamisama/cake-resque:4.1.2`
> `php composer.phar config vendor-dir Vendor`
> `php composer.phar install`

The Composer 'require' and 'config' commands set up the composer.json and composer.lock file. According to documentation, these files should typically be configured by the project and stashed in version control along with the project sources. 

It seems like this may be a way to further streamline this portion of the setup. It also looks like Composer is designed to handle some of the other PEAR and PECL dependencies that the application has, which could potentially remove or simplify integration of those dependencies in the same way.

**Comment by rotanid** [comment]
it seems you used the old LTS 14.04, the newer installation documentation for debian8 or ubuntu don't contain PEAR or PECL dependencies anymore and use native packages instead, which should be always preferred to additional package managers, no matter if it is pecl,pear,pypi,composer or something else.
i don't know much about composer, but if this goes into the repository of the project we have to make sure it works for all the supported operating systems without interfering with what i wrote before.

**Comment by Rafiot** [comment]
I partially did it there: https://github.com/MISP/MISP/blob/2.4/.travis.yml#L54 (only for the redis dep). It would be nice to use composer for all of them (but I'm not sure if it is possible).

**Comment by cristianbell** [comment]
Was speaking w/ @cvandeplas the other week about this and he had a good point: why don't we try to go for a PPA package? 
I must say that I agree with him, that pb be a better solution, though would require more work/time. 

Also, we should somehow point all users to our official /INSTALL folder, rather than having different installation guides such as #1195 ..

What do you guys think?

**Comment by Rafiot** [comment]
Sure, a deb package would be cool. Do you have experience doing it? I don't and I don't think anyone in the team does.

Could you look it up, please? 

Also, I'd recommend to create a new issue specially for that.

**Comment by SteveClement** [comment]
We will eventually come back to the PPA in the future.
No one stepped up to maintain it thus no imminent need.
