### ISSUE TITLE
Undefined offset: 1 in [/var/www/MISP/app/Model/Attribute.php, line 923]

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1306]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | not applicable |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.48, hash of the commit |
| Browser | not applicable |
### Logs, screenshots, configuration dump, ...

I get a log of these lines in resque-worker-error.log :
`Notice: Undefined offset: 1 in [/var/www/MISP/app/Model/Attribute.php, line 923]`
Looking at the code inside the modifyBeforeValidation() function:

```
        public function modifyBeforeValidation($type, $value) {
                switch ($type) {
...
                        case 'email-dst':
                        case 'domain|ip':
                                $parts = explode('|', $value);
                                if (filter_var($parts[1], FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
```

This seems to be caused by an empty attribute $value so $parts gets to be an empty array. Which is strange because value1 of the attributes table is set NOT NULL.

**Comment by rotanid** [comment]
i think i see the issue and a solution, too. i caused it, i'll fix it ;-)
