### ISSUE TITLE
Whitelist broken links?

### ISSUE THREAD

**Issue by eu-pi** [MISP/MISP#1308]
Dunno why I can't delete whitelists from whitelists/admin_index menu
Delete picto and "Delete whitelist" after clicking on Edit don't work:

.../admin/whitelists/edit/1 = ok
but .../admin/whitelists/delete/1 = Method Not Allowed

Running as admin, and latest version (.48)

**Comment by iglocska** [comment]
That is weird, just tested it and it works fine for me. It should throw a method not allowed if you try to access /admin/whitelists/delete/1 directly, but if you go through the forms (so through the UI) it works fine on my end. Could you check your error.log (in /var/www/MISP/app/tmp/logs/error.log) and see what the exact exception is?

**Comment by eu-pi** [comment]
My bad, a browser plugin was not allowing me to get the pop-up indeed. Case closed
