### ISSUE TITLE
include attribute lifetime/status?

### ISSUE THREAD

**Issue by michael-kerscher** [MISP/MISP#1310]
I am thinking about how to save information like the current status of an attribute in MISP.
For example consider DGA domains which are only valid for a limited time. It might be worthwhile to save information about the status/lifetime of an attribute in the database and be able to filter only active ones which have an IDS attribute, etc. You could remove the IDS flag from outdated attributes but then there has to be a separate change to these attributes which has to be distributed. But you could automatically calculate the status for these kind of attributes based on the date and time.

Such a feature would also be interesting for temporary infected but legitimate URLs which have been cleaned after some time. Attributes often have a time context in which they are valid indicators. If you just remove the IDS flag for an attribute you loose this information (at least if you want to use filters and don't want to watch the entire history of the event).

**Comment by iglocska** [comment]
We definitely have something that would resolve this on the roadmap. The idea is to assign a decaying score to attributes, based on the type and some external factors (such as server settings) that would drop over time and "revitalised" by sightings. Then we could use this value on an export level on demand.

For example, those DGA domains might not be valid after that limited timeframe, but if you have a system that tries to connect to one of them then it becomes more interesting. So the idea would be to set different export score thresholds by the users based on what they want to use the information for.

**Comment by adulau** [comment]
Related to #445
