### ISSUE TITLE
only show API/authkey to user with API key rights

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1311]
Today the api/authkey is shown to everyone, even if he has no API key rights.

1/ Either remove the API key permission and give everyone rights to use the API key. (why wouldn't we?) 
(I'm not talking about the special sync right that allows org-spoofing)

2/ Or remove all references of the API/authkey for a user that doesn't have the rights to use one. Replace the key by a message stating who (s)he should contact to get the additional permission.

Pages include (but it might be more than this simple list)
- users/view/me
- (reset key page)

It seems that the events/automation page is already being filtered (access denied) if the user doesn't have api key access.

**Comment by iglocska** [comment]
I don't think that enabling it by default is something that we should do, in general the idea is not to modify the default behaviour unless absolutely necessary. However, hiding the sync user and instead having a message to contact the admin for API access sounds like a great idea.

**Comment by cvandeplas** [comment]
Ok, so option 2 is being chosen.
