### ISSUE TITLE
Infinite loop on login

### ISSUE THREAD

**Issue by Rasmus-Riis** [MISP/MISP#1314]
HI. 

I have installed MISP using the AutoMISP.sh install script. 

It has worked like a charm. 

But when I try to login it logs in, but the browser stops and gives me the following message: (Both chrome and firefox)

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

My cookies are enabled and i have cleared them.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | support. |
| OS version (server) | ubuntu |
| OS version (client) | Ubuntu server 16.04 |
| PHP version | 7.0.4-7ubuntu 2.1 |
| MISP version / git hash | Downloaded latest today |
| Browser | Tried with both Chrome and Firefox |
### Expected behavior

Log in 
### Actual behavior

Infinite loop
### Logs, screenshots, configuration dump, ...

![image](https://cloud.githubusercontent.com/assets/4140365/16453605/aedf2e24-3e0d-11e6-99ec-2936da337b69.png)

**Comment by Rasmus-Riis** [comment]
I reinstalled it. Now it works. Closing

**Comment by adulau** [comment]
Thank you for the feedback.
