### ISSUE TITLE
Migrate Tag to Taxonomy

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1328]
Feature request, or more a discussion point of finding the best way to do this.

For multiple things we still use the old tags for markings that are present in the taxonomies. It would be good for us to migrate from one system to the other. 

An example is for example the TLP marking. We have a TAG called "TLP: Green" , and a taxonomy "tlp:green".  How should we migrate everything cleanly? 
- external python script - removing the old tag, and adding the new
- custom dirty php code updating the tags - removing tag, adding new, updating timestamps?
- general "migrate tag functionality" 

Feedback is welcome

**Comment by iglocska** [comment]
Hmm interesting. Basically the tag system is supposed to take those over when you first load it, I guess the space in TLP: Green threw it off. (If there is a TLP:GREEN tag for example, it will change the capitalisation to match the taxonomy one). 

I think we need a tag merge functionality for this, in the end it's simply a matter of updating the tag_ids in the EventTag objects. Give me a few minutes.

**Comment by iglocska** [comment]
Actually, let's wait a little bit with this. There is another issue with tags that is somewhat related that would probably be a good idea to solve before we do this: https://github.com/MISP/MISP/issues/1258

**Comment by morallo** [comment]
A temporary workaround would be bulk tagging, as requested in #1604.
One could search all tickets with one tag, apply the new one and delete the old one.

**Comment by morallo** [comment]
I just uploaded this: https://github.com/morallo/misp-bulk-tag

It can be used to replace one tag for another.

**Comment by adulau** [comment]
@morallo Thank you. Indeed, this seems very nifty. Should we put this project under the MISP organisation?

**Comment by morallo** [comment]
Sorry for the late reply @adulau.
No problem in putting it under MISP, but I can't promise proper maintenance :-P

**Comment by adulau** [comment]
Thank you. The website has been updated to include misp-bulk-tag.
