### ISSUE TITLE
Leading spaces in search filter are not stripped

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1329]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Windows 7 |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.48 |
| Browser | Firefox 45.2.0 ESR |
### Expected behavior

When I search using the filter box I expect leading spaces to be stripped
### Actual behavior

Leading spaces are not stripped and the search fails
### Steps to reproduce the behavior

Search for any keyword/domain/ip/etc with leading spaces. The search will fail.
### Logs, screenshots, configuration dump, ...

https://example.com/events/index/searchall:%20%20%20%20.com

**Comment by iglocska** [comment]
Yeah, that's indeed annoying, thanks!
