### ISSUE TITLE
tag keywords in attribute search filter has issues with an empty newline

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1330]
| Questions | Answers |
| --- | --- |
| Type of issue | Bug, |
| MISP version / git hash | 2.4.48 |
### Expected behavior

Attribute search page should not give all attributes when an empty line is added in a field
### Actual behavior

Gives all attributes as result
### Steps to reproduce the behavior
- open the search for attributes page
- add some keywords for the "tag" search, including empty newline at the end of the keywords list
- press search
- see that all the attributes are given in the result set
- do the same for a tag keyword, without newline
- you will see the right result set is returned

**Comment by iglocska** [comment]
Thanks, fixed.
