### ISSUE TITLE
MYSQL.sql file should reflect the actual database structure

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1331]
as we have noticed, the content of MYSQL.sql doesn't reflect what actually is the database structure after setting up MISP.
some changes done to the DB via the upgrade mechanism don't seem to have made their way into the MYSQL.sql file or are even done on every update over and over again.

the upgrade mechanisms, specifically updateDatabase() shouldn't have to do stuff on fresh installs.
this affects cases in updateDatabase() like "cleanupAfterUpgrade" and "indexTables" , but more might be affected, too.
i don't think we should call these commands all the time but rather include them as a regular update to the structure and also include them in MYSQL.sql - so new setups won't run these.

that would also make it much easier to support other DBMS like PostgreSQL

**Comment by iglocska** [comment]
Just a heads-up, those are not called all the time but are ondemand. The way it currently works is that MISP will run the 2.4.xx database upgrade scripts automatically, the two that you mention are on demand administrative tasks.

**Comment by rotanid** [comment]
so there might be setups that use the changed indexes and setups that don't? :-/

but the "cleanupAfterUpgrade" should better be a "2.4.xx" update, shouldn't it? we could include it for the next release (adding it to the respective releases wouldn't help now anymore) and remove it from the backend.
same for "indexTables" or why is this only done in the backend on manual invocation and not using the update mechanism?

if we leave those two out,  there still might be other differences between the actual structure and MYSQL.sql - at least you suggested that on gitter which brought the issue up in the first place ;-)

**Comment by iglocska** [comment]
cleanupAfterUpgrade is for 2.3 -> 2.4 fresh migrations, it's not something that basically anyone out there using MISP nowadays will ever run. The migration procedure from 2.3 was running the UPGRADE.sql file to create the new tables, add some new rows and then a final in-app script did the migration of the data, removed some fields, set the new indeces. 

The indexTables tool was meant for old installations that lacked the indexing from before and it was introduced prior to when I wrote the automated upgrade procedures. It's legacy stuff by now and admins generally don't have to worry about it, if we want to change the indexing at any point we'll do it as part of an automatic upgrade script. 

Also, I have a feeling that indexing is something that operators of MISPs will tune themselves, so we'll most likely run into situations where not every MISP installation will have the same indexing as what we foresee, but that is absolutely fine.

**Comment by rotanid** [comment]
at least everything after 2.4.33 should be fixed with #1332 - i think we can close it, something similar is in a separate issue, #1333
