### ISSUE TITLE
Download Export CSV not available and cannot be generated

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1335]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| MISP version / git hash | 2.4.48 |
### Expected behavior

Going on the export page, and being able to download any up to date file.
### Actual behavior

Some files can be generarated on-demand (XML,CSV_Sig, CSV_All, Suricata, etc...) but some can't (md5, sha1, etc...).
Case 1:There is an error page if those files were not ever generated.
Case 2: If the file was ever generated before, it delivers an out of date version. And it does so silently for the second group of files (that can be generated on demand): md5, sha-1, etc...
### Steps to reproduce the behavior

Case 1:
- Go to export page on an instance where the files were never generated. 
- Click on a link to download one of the files.

Case 2:
- Go to export page on an instance where the files were generated and are now out of date.
- Click on a link to download one of the files.
### Logs, screenshots, configuration dump, ...

Case 1:
![image](https://cloud.githubusercontent.com/assets/178521/16611052/702c2a68-435f-11e6-953b-772a8643db97.png)

This is mostly to start a conversation on what would be best to handle this situation.
- Disallow download of files not generated and/or not up to date?
- Retire the downloadExport part of the API?
- Add API call to update/generate the files?

**Comment by iglocska** [comment]
The text exports can also be generated on demand in bulk, but maybe it's not obvious enough. The last thing you can generate on the list is called "TEXT" and it will generate the line separated text lists for all of the attribute types that you can then download individually below.

**Comment by iglocska** [comment]
Disallowing not generated exports makes sense though, not up to date ones - this should be up to the user, if it's a few hours old maybe it's OK for the user to just take it instead of waiting for a new export to be generated.

**Comment by adulau** [comment]
I'll close the issue. Feel free to reopen if the issue persists.
