### ISSUE TITLE
Unable to add Email address with specific characters in email address

### ISSUE THREAD

**Issue by cbakkers** [MISP/MISP#1344]
Unable to upload email address with specific character
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, |
| MISP version / git hash | 2.4.44 |
### Logs, screenshots, configuration dump, ...

![image](https://cloud.githubusercontent.com/assets/13032592/16680376/4f609cc0-44ee-11e6-807f-52175213d972.png)

**Comment by rotanid** [comment]
hi @cbakkers , thanks for reporting this.
should be fixed by my PR #1349 with commit efe31e8b07e980462160a6dfb8e775d8cadbad36
