### ISSUE TITLE
Create Event Error

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#1345]
Hi all, 

Just have this problem
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | ubuntu |
| OS version (client) | Ubuntu |
| PHP version | PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) |
| MISP version / git hash | 2.4.48 |
### Logs, screenshots, configuration dump, ...

This is  what I get in my Google Chrome

Fatal Eror
Error: Class 'CakeText' not found  
File: /var/www/MISP/app/Model/Event.php 
Line: 365
Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

Cheers,
Andreas

**Comment by iglocska** [comment]
Hello Andreas,

could you run the following commands from the command line?

git submodule init
git submodule update

We recently removed a fallback for outdated CakePHP versions and I think you are seeing the result of that. Let me know if this doesn't resolve it!

**Comment by advancedeng** [comment]
I run the above commands and the problem was not fixed @iglocska

**Comment by iglocska** [comment]
Weird, I'll revert the patch asap then.

**Comment by iglocska** [comment]
Could you git pull again please?

**Comment by advancedeng** [comment]
Yes, it is working right now. Thanks @iglocska  :)

**Comment by iglocska** [comment]
Excallent, thanks for the heads-up :)

**Comment by advancedeng** [comment]
No probs

**Comment by rotanid** [comment]
Hi Andreas,
as this problem doesnt appear for me, i'm curious how that error happened, maybe you could help with some information?
We have a suspicion, may it be that the command "tail -1 /var/www/MISP/app/Lib/cakephp/lib/Cake/VERSION.txt" still shows something like "2.7" on your server?
and therefore, the file /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/CakeText.php doesn't exist?
if yes, we might have a better fix than the temporary one.

**Comment by iglocska** [comment]
It has to be CakePHP 2.7 instead of 2.8.

**Comment by rotanid** [comment]
Hi Andreas, we think we permanently fixed the problem, if you don't want to wait for the release of 2.4.49, please do an update of MISP and it should introduce the fix to MISP itself and afterwards the submodules should update you to a newer cakephp version.
