### ISSUE TITLE
missing "expanded" values vs. NOT NULL database column constraint

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1354]
at least one taxonomy (veris) has no expanded forms of their predicates defined.
the problem with this is, the current data model of MISP says "NOT NULL"  and no default value on the "expanded" columns of taxonomy_entries and taxonomy_predicates.

should we simply remove the "not null" constraints from the "expanded" column of both tables?
or add a default empty string value?

**Comment by iglocska** [comment]
Weird that this hasn't caused issues yet. Indeed changing it to allow null would make the most sense.

**Comment by rotanid** [comment]
perhaps MySQL is more forgiving here than PostgreSQL is... fell over it when working on the latter
