### ISSUE TITLE
Web interface Vs conf file

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1358]
Hi team,

When I edit misp  configuration through web interface, my app/Config/config.php file is updated but specific config block (like ApacheSecureAuth in my case) is deleted.

| Questions | Answers |
| --- | --- |
| MISP version / git hash | 2.4.48 |

**Comment by iglocska** [comment]
Indeed, this is an issue that I forgot about that is quite high prio. Will look into it!
