### ISSUE TITLE
Errors while importing OpenIOC files 

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#136]
(the version of MISP I'm currently using is the latest from the development branch)

I tried to import some IOC files and encountered a few problem:  

Operation Troy from McAfee is not importable at all, MISP returns an error: 
http://podcasts.mcafee.com/audioparasitics/ioc/MFE_Operation_Troy_1.0.ioc.zip

APT1 of Mandiant result in a partial import (1/3 of the ICOs are not imported):
http://intelreport.mandiant.com/Mandiant_APT1_Report_Appendix.zip
It is more or less the same for the files provided by Alienvault: 
https://github.com/jaimeblasco/AlienvaultLabs/tree/master/malware_analysis

**Comment by elhoim** [comment]
Can I consider this closed since this can only be fixed if #27 is implemented?

**Comment by iglocska** [comment]
Indeed, there is no quick fix for this sadly :(
