### ISSUE TITLE
support PostgreSQL database backend

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1363]
as discussed many times, we might want to support PostgreSQL as an alternative to MySQL/MariaDB.

i've already worked on basic, experimental support which will soon be released either as a feature branch or as a pull request.

**Comment by adulau** [comment]
That's a great news. Depending of the changes required, a feature branch might be useful.  Thank you for your work.

**Comment by rotanid** [comment]
opened a PR #1364 for part of the necessary but not strictly postgres-dependent changes.

also created a feature branch https://github.com/MISP/MISP/tree/feature/postgresql (it already includes the PRs changes plus the 3 commits for postgres support itself)

**Comment by rotanid** [comment]
the PR #1364 was tested by @iglocska and merged.
i updated the feature branch to reflect this merge.

feel free to test it :-)

**Comment by rotanid** [comment]
update on the status:
- reduced 2.4 branches mysql dependency ( #1437 , #1442 , #1443 )
- feature branch is up to date again
- migration instructions from mysql/mariadb added to the install doc (tested with the misp training data)

testers needed, migration is easy!
note: no reverse migration documented, but you can always switch back to mysql easily (loosing changes you made in postgresql-db)

**Comment by rotanid** [comment]
fixed in #1485

**Comment by rotanid** [comment]
i noticed an issue:
if we do add new indexes via the update mechanism there might be a problem if the index already exists, because before PostgreSQL 9.5 (current upstream release) there was no easy way to say "create this index only if it doesn't exist yet"
the easy way wouldn't work for current Debian stable (8 / jessie) as it uses Postgres 9.4

**Comment by iglocska** [comment]
That is fine. We currently push new indexes after running __dropIndex() which first drops the existing index then creates a new one. However, we might have to update __dropIndex() to include a path for Postgres.

**Comment by rotanid** [comment]
i made a PR adding this path for Postgres to __dropIndex()
