### ISSUE TITLE
Adding New Event shows "Fatal Error"

### ISSUE THREAD

**Issue by de0bfs** [MISP/MISP#1368]
### Work environment

| Questions | Answers |
| --- | --- |
| Fatal Error | Support,Bug |
| OS version (server) | ubuntu 14.04 |
| PHP version | 5.5 |
| MISP version | 2.4.48 |

(after I upgraded to the 2.4.48) When Trying to add the new event the "Fatal Error Message Pops up:

**Fatal Error**
Error: Class 'CakeText' not found
File: /var/www/MISP/app/Model/Event.php
Line: 365

I have noticed that this is due to the usage of "CakeText" class in the new MISP env, and if I change this className to the depricated one which is "String" the issue resolves (need to change in every file). does it need a php update to 7.0?

**Comment by iglocska** [comment]
CakeText is part of CakePHP 2.8 which is a requirement now, could you run 

git submodule init
git submodule update

and let us know if it fixes the issue? PHP 7.0 should not be needed for this.

**Comment by de0bfs** [comment]
Yes it seems like it is fixed now , just some additional steps to cover other bits which it was complaining:

first it gave me some errors over the taxonomy contents, I cleared that and also ran:
git submodule foreach git stash
git submodule foreach git pull

and then the apache restart came clean and all working now again :+1:  
Thanks a lot

**Comment by iglocska** [comment]
Excellent, any idea what the complaints were? That is interesting in itself. Do you run any custom taxonomies beyond what is shipped with MISP?

**Comment by de0bfs** [comment]
No nothing in addition to those at the moment (tlp folder). when running the **submodule update**  it was complaining that the taxonomies folder is not empty and then after clearing the folder it came up with: 

_Unable to checkout <hash> in submodule path 'app/Lib/cakephp' ...._ 

then after I did the 
**git submodule foreach git stash
git submodule foreach git pull**

and an apache restart,
all resolved

**Comment by rotanid** [comment]
i'll check and fix this part of the UPDATE.txt

**Comment by rotanid** [comment]
Hi @de0bfs , we fixed the issue by changing the UPDATE.txt documentation regarding the submodule updates. Thanks for reporting the issue.

**Comment by de0bfs** [comment]
Really Appreciate the support @rotanid , great job team!
