### ISSUE TITLE
MISP Jobs stuck

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#1369]
Hi,

I've noticed that on my system, there are many outdated jobs which are stuck either at a percentage, or not being completed at all. I've attached a screenshot of these jobs. Two of which are db upgrades to 2.4, but I'm pretty sure that's already been completed. 

Is there a way to clear these jobs from the queue? Couldn't see any option to cancel a job on the front end. 
_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Support... |
| OS version (server) | CentOS |
| OS version (client) | Ubuntu |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.48 |
### Logs, screenshots, configuration dump, ...

![jobs_stuck](https://cloud.githubusercontent.com/assets/15731689/16795849/6e9d0ce4-48d7-11e6-8cff-b641d3934cbb.png)

**Comment by iglocska** [comment]
Hello there Tom,

those jobs are not actually queued anymore - it's a bit confusing but the
jobs interface is not a direct reflection of the jobs (stored in the redis
db). They are just updates sent by the job as it progresses and in the case
of a job's failure, will retain the state from before failure. Think of it
as a secondary log table, there should be no need to clear them, the jobs
are long dead already. We should in the future look into a system that can
determine whether a job is dead and update that table though!

**Comment by tomking2** [comment]
Hello Andras,

Ah okay, thanks for letting me know this, I wasn't aware! Makes sense, and good to know these things aren't still attempted to be queued from the system. 

That would be good - solely for the use of allowing an easy way to spot what's running. Ordering by % complete at the moment brings up all these failed jobs which makes it hard to see what's currently going on.

**Comment by iglocska** [comment]
Indeed, that is a very good point about being able to order on ongoing jobs. I'll think of something!
