### ISSUE TITLE
virustotal as External analysis instead of Network activity when using Freetext import

### ISSUE THREAD

**Issue by eu-pi** [MISP/MISP#1373]
Not a bug, a suggestion. 

Low priority (but easy to correct if needed) 

when using Freetext Import on URL=https://virustotal.com/..., the tool detect a Network Activity (thus add by default the IDS export) instead of an External analysis type of attribute (without IDS export).

Those who want to avoid issue (and FP if URL is exported) should change the regular expression including "www" here:
https://github.com/MISP/MISP/blob/5bd341b450100b706b854c68e1dc5bbd20cd8cf7/app/Lib/Tools/ComplexTypeTool.php
# 
# if (preg_match('/^https:\/\/www.virustotal.com\//i', $inputRefangedNoPort)) return array('types' => array('link'), 'to_ids' => false, 'default_type' => 'link', 'comment' => $comment, 'value' => $inputRefangedNoPort);

**Comment by iglocska** [comment]
Good idea, thanks!
