### ISSUE TITLE
MySQL error on users.certif_public

### ISSUE THREAD

**Issue by I-am-Sherlocked** [MISP/MISP#1378]
In users table, certif_public is defined as longtext and has a default value of '' (default changed in 2f2952c from NULL) which causes MySQL ERROR 1101 (42000): BLOB, TEXT, GEOMETRY or JSON column 'certif_public' can't have a default value.

_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | ubuntu 14.04 |
| OS version (client) | Ubuntu 14.04 |
| PHP version | 5.5 |
| MISP version / git hash | 2.4.49 |
| MySQL version | 5.7.12 |

**Comment by rotanid** [comment]
my change in the commit you referenced was simply copying the change from there:
https://github.com/MISP/MISP/blob/2.4/app/Model/AppModel.php#L353
which was introduced in 8db889ce7e80ab4765d90e7cb59d41709615cc11

please @iglocska , have a look at this :)
