### ISSUE TITLE
Publishing an event after subsequent change via API

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1379]
I noticed that after you upload a sample via the upload_sample API that it changes the Published status to "No". I subsequently noticed that you are unable to change the "Published" status via the API. Will this be included in a future revision?

**Comment by iglocska** [comment]
First of all, please git pull, I've included 2 fixes that resolve some issues with API level publishing.

It is possible to publish an event in various ways via the API, though the documentation for it is lacking and it wasn't correctly returning a response.

I've fixed the responses for the publish APIs and they should work correctly now. The usage:

The headers for all requests are:
Authorization: your_api_key
Content-type: application/json
Accept: application/json

To publish an event silently (no e-mails):
POST to /events/publish/event_id

To publish an event (with e-mails):
POST to /events/alert/event_id

It is also possible to publish an event by issuing an edit in this format:
POST to /events/edit/event_id
Payload: {"Event":{"published":1}}

Let me know if you have any other questions!

**Comment by ghost** [comment]
Thank you! This is much appreciated.

**Comment by iglocska** [comment]
My pleasure!
