### ISSUE TITLE
MISP Terms and Conditions file not found

### ISSUE THREAD

**Issue by treyka** [MISP/MISP#1381]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Debian |
| OS version (client) | 8.5 |
| PHP version | 5.6.23-0+deb8u1 |
| MISP version / git hash | tag v2.4.48 |
| Browser | Chrome |
### Expected behavior

At initial login, the admin is presented with the MISP Terms and Conditions and requested to accept them.
### Actual behavior

An error is shown: "Terms and Conditions file not found."
### Steps to reproduce the behavior

Install MISP as per the Debian install instructions, perform initial login.
### Logs, screenshots, configuration dump, ...

![image](https://cloud.githubusercontent.com/assets/630301/17051823/1b3dc290-4fea-11e6-9d0e-8789b6279f37.png)

**Comment by iglocska** [comment]
The instance's terms and conditions have to be uploaded by an admin, but indeed it doesn't make sense to require users to accept it if it doesn't exist. I'll fix this asap.

**Comment by rohit1995jangid** [comment]
IS there any sample for terms file
