### ISSUE TITLE
Unable to set category to "External Analysis" via the "Upload Sample" (upload_sample) API

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1384]
When using the upload_sample API, it doesn't appear possible to set the 'category' to "External Analysis". Is there another way to attach a file and set it as such?

**Comment by truckydev** [comment]
It's ""External **a**nalysis" not  "External Analysis".

I use it like this : 

misp.upload_sample( 
                "filename.txt",
                myfile,
                1, #id
                "0", 
                False, 
                "External analysis", 
                "my file sample",
                None,
                "1", 
                "4",
            )

**Comment by iglocska** [comment]
Nice catch!

**Comment by ghost** [comment]
Thank you.
