### ISSUE TITLE
Categories change after attaching a file to an event

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1385]
Once an attachment has been uploaded to MISP via the upload_sample API, the number of available categories increase. The initial set are as follows: Antivirus detection; Payload delivery; Artifacts dropped; Payload installation; Network activity; External analysis. 

After uploading, the available categories are now as follows: Internal reference; targeting data; Antivirus detection; Payload delivery; Artifacts dropped; Payload installation; Persistence mechanism; Network activity; Payload type; Attribution; External analysis; Financial fraud; Other.

This seems to be inconsistent behavior. Is this by design?

**Comment by iglocska** [comment]
Nice catch, those additional categories should be filtered. The initial set is indeed correct!

**Comment by iglocska** [comment]
This seems to have been fixed ever since.
