### ISSUE TITLE
Undefined index: date on CIRCL LU MISP

### ISSUE THREAD

**Issue by MichaelDwucet** [MISP/MISP#1386]
A potential bug.
Some text is redacted, as the event is TLP AMBER

When browsing
https://misp.circl.lu/events/view/853/1/77
the second attribute shows some errors in the related events column

Attribute #2
ORG - redacted

Category - External analysis

Type - text

Value - redacted 
Comment -
Related events -
Notice (8): Undefined index: date [APP/View/Elements/eventattribute.ctp, line 330]
2781
Notice (8): Undefined index: date [APP/View/Elements/eventattribute.ctp, line 330]
2701
Notice (8): Undefined index: date [APP/View/Elements/eventattribute.ctp, line 330]
1949
Notice (8): Undefined index: date [APP/View/Elements/eventattribute.ctp, line 330]
1822 
No

**Comment by iglocska** [comment]
Thanks for the heads-up!
