### ISSUE TITLE
Add Email in view event history

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1389]
Hi team,

It would be cool to add the email of the person to change an attribute.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Feature |
### Logs, screenshots, configuration dump, ...

![capture d ecran - 27072016 - 14 55 57](https://cloud.githubusercontent.com/assets/17462115/17175938/9df4f13a-540a-11e6-80c8-785a7542f2c3.png)

**Comment by truckydev** [comment]
I add in app/event_index.ctp
https://github.com/MISP/MISP/blob/2.4/app/View/Logs/event_index.ctp#L26
line 26 : 

``` php
<th><?php echo $this->Paginator->sort('Email');?></th>
```

https://github.com/MISP/MISP/blob/2.4/app/View/Logs/event_index.ctp#L43
Line 43 : 

``` php
<td class="short"><?php echo h($item['Log']['email']); ?>&nbsp;</td>
```

Next, I have add the field `, 'email'` in app/logsController.php
https://github.com/MISP/MISP/blob/2.4/app/Controller/LogsController.php#L107

This feature is interesting but I do not know if it's the best way to implement. Now, if there is a problem on a change of an attribute, we can directly contact the person.

My result:
![capture d ecran - 27072016 - 16 40 16](https://cloud.githubusercontent.com/assets/17462115/17179335/195926c6-5419-11e6-9192-85ae4324a091.png)

**Comment by iglocska** [comment]
The e-mail was removed on purpose from the event history. The idea is to keep users from being able to see the e-mail addresses of other users. 

We could show the e-mail for site admins and org admins (for org admins, as long as the e-mail belongs to an org member) - would that make sense?

**Comment by truckydev** [comment]
A good compromise might be to let the visible email addresses of persons from the same organization.

The goal is to leave a link to a person who made a change in order to ask him directly for information on a change without having to go through an admin.
