### ISSUE TITLE
download as OpenIOC error

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1393]
When you download an event as openIOC, 
the $value is in the wrong place.

To correct this replace in MISP/app/Controller/Component/IOCExportComponent.php line 95 : 

``` php
$this->__frameIndicator($this->mapping['simple'][$attribute['type']], $attribute['value'], false);
```

by : 

``` php
$this->__frameIndicator($this->mapping['simple'][$attribute['type']],$attribute['uuid'], $attribute['value'], false);
```

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, |
### Expected behavior

<IndicatorItem id="579b5fe4-1234-4b95-86c6-1f0000000000" condition="is">
        <Context document="FileItem" search="FileItem/FileName" type="mir" />
        <Content type="string">test.exe</Content>
      </IndicatorItem>
### Actual behavior

``` xml
<IndicatorItem id="test.exe" condition="is">
        <Context document="FileItem" search="FileItem/FileName" type="mir" />
        <Content type="string"></Content>
</IndicatorItem>
```
### Steps to reproduce the behavior

Just make attribut as IDS, publish the event and try to download as OpenIOC

**Comment by iglocska** [comment]
Thanks for the heads-up.
