### ISSUE TITLE
Scheduled tasks list is erroring out

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1395]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Debian |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.49, current as of 2016-08-01 14:00 |
### Expected behavior
- Display the list of scheduled tasks.
### Actual behavior
- Erroring out wiht "an internal error has occured"
### Steps to reproduce the behavior
- Go to the scheduled tasks list page.

**Comment by rotanid** [comment]
mabye there is additional information on this in MISPs error.log and/or the webservers error.log ?
that error message may appear for various reasons...

**Comment by elhoim** [comment]
In error.log:

```
 2016-08-03 10:52:37 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Task.job_id' in 'field list'
 Request URL: /tasks
 Stack Trace:
 #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
 #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Task`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `Task`.`...', Array, Array)
 #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `Task`.`...', false)
 #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Task), Array)
 #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
 #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
 #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1086): PaginatorComponent->paginate(NULL, Array, Array)
 #8 /var/www/MISP/app/Controller/TasksController.php(29): Controller->paginate()
 #9 [internal function]: TasksController->index()
 #10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
 #11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
 #12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest))
 #13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
 #14 {main}
```

**Comment by rotanid** [comment]
this seems related to the change from job_id to process_id in the tasks database table.
are you sure that your files, especially Tasks.php and TasksController.php are up to date?
what about "git status"?
and "grep -r job_id /YOUR/PATH/TO/app/ | grep Task" ?

@iglocska i'm not sure where the issue could be if his files are up to date, i found out that app/Config/Schema/schema.php is way out of date, but that would have been a problem in many other cases, if relevant...

**Comment by iglocska** [comment]
Nah, we don't use the schema system of cake PHP. Will have a look at it
after the hackathon

**Comment by cristianbell** [comment]
had the same issue last week but I just updated the db schema on my test vm. Updated today, reverted my db changes, and the issue is still there. 
Will take a look at it today.

**Comment by cristianbell** [comment]
ok, so the issue is with cakePHP caching: the job_id was still stored in my "myapp_cake_core_method_cache" under "../app/tmp/cache/persistent". One could change the cache, clean it, but the fastest option is to remove the core_method_cache file: "rm /YOUR/PATH/TO/app/tmp/cache/persistent/myapp_cake_core_method_cache".

**Comment by adulau** [comment]
There is a nice and clean way to do it via the MISP interface ;-) 

https://<yourMISP>/servers/serverSettings/diagnostics -> "Clean cache model".

**Comment by elhoim** [comment]
@adulau, thanks that fixed it.

Closing ticket and adding to misp-book (if not already there).

**Comment by iglocska** [comment]
The weird thing is that this should be executed after each upgrade. The only explanation I can see is that the upgrade got somehow interrupted / stalled before getting to the cleanup. Very odd.

**Comment by rotanid** [comment]
regarding schema, if we don't use it, it should be removed probably.

**Comment by iglocska** [comment]
Yep, it's pretty much an ancient leftover thing. I mean it doesn't do any harm and might be a nice basis if we ever want to revisit it, but might just as well remove it.

**Comment by rotanid** [comment]
the basis will always be there in the git history :P

**Comment by iglocska** [comment]
True enough.
