### ISSUE TITLE
Layout broken for org with lots of users

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1396]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu |
| OS version (client) | 14.04 LTS |
| PHP version | PHP 5.5.9-1ubuntu4.17 |
| MISP version / git hash | 2.4.49 |
### Expected behavior
- When going on all pages of list users under an organisation, show the list with the same layout.
### Actual behavior
- When going on any page after the first page of user shows a broken layout.
### Steps to reproduce the behavior
- Go to an organisation page having enough users to have more than one page in the list of users belonging to the organisation.
- Go to any page after the first one.

![screen shot 2016-08-01 at 14 41 00](https://cloud.githubusercontent.com/assets/178521/17294419/05675cf0-57f7-11e6-8332-fca3d34f52b4.png)

**Comment by adulau** [comment]
Thank you. The bug is indeed confirmed.

**Comment by iglocska** [comment]
Indeed, will try to look into it this week but will need a few days to get some time for it. The same index is reused but it loads it full page instead of inserting it in the existing page using an ajax call.

**Comment by iglocska** [comment]
Should be fixed already.
