### ISSUE TITLE
Importing from openIOC kind of fails

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1397]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Debian |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.49 |
### Expected behavior
- Using the "Populate from OpenIOC" feature imports the IOCs as attributes
### Actual behavior
- The page listing the IOCs that are successfully parsed and imported mentions that all IOCs are parsed and imported and that none failed.
- The event entry in the db is updated with the correct count of attributes but when i sort the tables of attributes by id descending, the attributes are not present.
### Steps to reproduce the behavior
- Create an event with "your organisation only" as distribution.
- Use the "populate from openIOC"
- Go to "view event"

I can send the openIOC file by email if it helps.

**Comment by iglocska** [comment]
Sure the OpenIOC file would be handy, though unless it's a simple fix I will most likely not fix it. It's time to retire the crappy OpenIOC importer and switch to something more modern using the module system very soon :)

**Comment by truckydev** [comment]
It's a better way to use python : https://github.com/MISP/PyMISP/tree/master/examples/ioc-2-misp

**Comment by iglocska** [comment]
Indeed, the idea is to use the code from that for the import module and then just delete the crappy old importer.
