### ISSUE TITLE
Queue status: Issues prevent jobs from being processed. Please resolve them below.

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#1399]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | ubuntu |
| OS version (client) | Seven |
| PHP version | PHP 7.0.9 |
| MISP version / git hash | 2.4.49 |
| Browser | Firefox |
### Expected behavior

Restart of the workers via the Server Settings page.
### Actual behavior

I get the following error:

Queue status: Issues prevent jobs from being processed. Please resolve them below.

See screenshot below:

![image](https://cloud.githubusercontent.com/assets/8973767/17302955/830d8a8e-5816-11e6-8042-26f55c0a84ae.png)

**Comment by rotanid** [comment]
which ubuntu version are you running? and did you upgrade to MISP 2.4.49 from an older version or is this a fresh setup?
php 7.0.9 doesn't seem to be an ubuntu-php, as xenial (16.04 lts) is using 7.0.8 at the moment.
so maybe you're missing some php module that would have been installed and enabled by following the install guide for ubuntu? maybe php-redis is missing or it's not up-to-date?
just guessing though...

**Comment by advancedeng** [comment]
You are absolutely right. php-redis was missing ;)

Thanks a lot, your help is much appreciated!

Cheers,
Andreas

**Comment by adulau** [comment]
Thank you for the feedback.

**Comment by Batata-ops** [comment]
I have the same issues but I run Kali Linux 2020.1
