### ISSUE TITLE
Lots of Notice: Notice (8): Undefined index: perm_delegate in [/var/www/MISP/app/Controller/AppController.php, line 311]

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1401]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Debian |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.49 current as of 03 AUG 13h16 |
### Expected behavior
- No notice about an undefined index
### Actual behavior
- Notices about an undefined index

Full trace from debug.log

```
2016-08-03 11:15:11 Notice: Notice (8): Undefined index: perm_delegate in [/var/www/MISP/app/Controller/AppController.php, line 311]
Trace:
AppController::beforeFilter() - APP/Controller/AppController.php, line 311
ShadowAttributesController::beforeFilter() - APP/Controller/ShadowAttributesController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 676
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

[Line 311](https://github.com/MISP/MISP/blame/2.4/app/Controller/AppController.php#L311) was added with commit ca2fb7d

**Comment by rotanid** [comment]
this too (like #1395) looks like there went something wrong with your update to the latest version - or the update process has an error.
first, you could check if "perm_delegate" column exists in your "roles" database table, like it should have been added: https://github.com/MISP/MISP/blob/2.4/app/Model/AppModel.php#L423
and if your file Role.php is really up to date ( https://github.com/MISP/MISP/blob/2.4/app/Model/Role.php#L77 )

**Comment by elhoim** [comment]
It seems to be finished now. It might have been resolved by my earlier use today of the _clean model cache_
