### ISSUE TITLE
Applying warning lists for the API (not only the UI)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1404]
At the current stage, warning-lists are only applied at the user-interface level. It would be nice to have it at API level to avoid getting the attributes present in a warning-list.

**Comment by adulau** [comment]
Maybe something to implement for one of the next releases. (got many feedback on this)

**Comment by iglocska** [comment]
sure. Should be doable.

**Comment by adulau** [comment]
Implemented in 2.4.57
