### ISSUE TITLE
first login doesn't work; can't change password

### ISSUE THREAD

**Issue by cherylresch** [MISP/MISP#1405]
My first login on MISP with admin@admin.test/admin isn't working.  I get invalid username or password.  When I try to change the password with "cake Password admin@admin.test admin" I get Class PasswordShell could not be loaded.  I can't figure out why I can't get PasswordShell to run.  I've changes the directory I'm running it in many times.  Why aren't any of the shells in the directory "available"????

**Comment by rotanid** [comment]
which OS, PHP, MISP versions are you using? the "new issue" template here asks for that for a reason ;-)
did you do the installation in one session or started a while back and continued later?
have you tried it from scratch and ran into the same problem again?

**Comment by cherylresch** [comment]
I dropped the misp database and recreated it.  That did the trick. Username/password  admin@admin.test/admin worked.  I wonder what I did to make the username/password not work the first time?

**Comment by rotanid** [comment]
it could be related to the "salt" generation...
i'll close this though until we can reproduce it.
