### ISSUE TITLE
Proposal add-delete cycles cause sync delay and massive logs

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1407]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, support |
| OS version (server) | CentOS |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.49 |
| Browser | not applicable |
### Actual behavior

When I add two sync servers misp.circl.lu and misppriv.circl.lu syncing becomes very slow.
Syncing with misp.circl.lu adds 10k proposals which takes 100+ minutes. After this syncing with misppriv.circl.lu removes all these 10k proposals again. This also quickly fils the logs MySQL table and eventually the file system.
### Expected behavior

Syncing with both misp.circl.lu and misppriv.circl.lu should result in the combined contents of these two MISP instances, not a ping-pong between what is in one and then the other.
### Steps to reproduce the behavior

Simply add both misp.circl.lu and misppriv.circl.lu as pull sync servers and enable the pull_all scheduled task.
### Logs, screenshots, configuration dump, ...

Available upon request.

**Comment by RichieB2B** [comment]
In 4 months this issue resulted in about 1M delete + 1M add log entries. Can I safely purge those and leave the other logs?
```
mysql> select model, action, count(*) as count from logs group by model,action order by count desc limit 10;
+-----------------+---------+--------+
| model           | action  | count  |
+-----------------+---------+--------+
| ShadowAttribute | delete  | 974483 |
| ShadowAttribute | add     | 973070 |
| User            | auth    |  87677 |
| Attribute       | add     |  67497 |
| Server          | pull    |  16568 |
| Attribute       | edit    |   6688 |
| Event           | edit    |   5753 |
| User            | email   |   5463 |
| Server          | warning |   2614 |
| Attribute       | delete  |   2256 |
+-----------------+---------+--------+
10 rows in set (4.20 sec)
````

**Comment by RichieB2B** [comment]
This is still an issue with MISP 2.4.59. In 1 month 500k delete + 500k add log entries were added.
```
mysql> select model, action, count(*) as count from logs group by model,action order by count desc limit 10;
+-----------------+---------+--------+
| model           | action  | count  |
+-----------------+---------+--------+
| ShadowAttribute | add     | 517483 |
| ShadowAttribute | delete  | 512531 |
| User            | auth    | 116483 |
| Attribute       | add     |  84994 |
| Server          | pull    |  20036 |
| Attribute       | edit    |   8055 |
| Event           | edit    |   7198 |
| User            | email   |   6307 |
| Server          | warning |   3717 |
| Attribute       | delete  |   2756 |
+-----------------+---------+--------+
10 rows in set (2.43 sec)
```

**Comment by RichieB2B** [comment]
It seems this was recently fixed (somewhere between 2.4.60 and 2.4.63). Thanks!

**Comment by iglocska** [comment]
yay, so it worked! You might still have issues with it when syncing with outdated instances, but new to new should be fast.

**Comment by RichieB2B** [comment]
A full sync cycle (6 server) went down from 100+ mins to just 2! :+1:

**Comment by iglocska** [comment]
Those are the kinda gains I want to see across the board!

/drill sergeant
