### ISSUE TITLE
[Documentation] Define Roles

### ISSUE THREAD

**Issue by kalyparker** [MISP/MISP#1418]
For updating the misp-book (Administration), Could you please define the missing roles:
- Perm Sharing Group
- Perm Tag Editor
- Perm Delegate
- Perm Template

And have a look to the definition of the other (if there is any modification):
- **Perm Admin:** Gives the user limited administrator privileges, this setting is used for the organisation admins.
- **Perm Audit:** Grants access to the logs. With the exception of site admins, only logs generated by the user's own org are visible.
- **Perm Tagger:** Allows the user with this permission to create custom tags and assign them to events.
- **Perm Site Admin:** Gives the user full administrator privileges, this setting is used for the site admins.
- **Perm Auth:** This setting enables the authentication key of the role's users to be used for rest requests.
- **Perm Sync:** This setting allows the users of the role to be used as a synchronisation user. The authentication key of this user can be handed out to the administrator of a remote MISP instance to allow the synchronisation features to work.
- **Perm Regexp Access:** Allows the users with this permission enabled to edit the regular expression table. Be careful when giving out this permission, incorrect regular expressions can be very harmful (infinite loops, loss of data, etc.).

Thanks

**Comment by adulau** [comment]
Perm Sharing Group Editor: Grant access to edit or create sharing groups.
Perm Tag Editor: Grand access to edit or create new local tags or from taxonomies.
Perm Delegate: Grant access to delegate the publication of an an event to a third-party organization.
Perm Template Editor: Grant access to create or modify templates.

Perm Tagger (has been updated): Allow user to assign tags to events.

**Comment by kalyparker** [comment]
Ok, thanks

**Comment by adulau** [comment]
Thank you too. Cheers.
