### ISSUE TITLE
Do not apply regexp for path to pdb attribute type

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1420]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| MISP version / git hash | 2.4.49 (misppriv as of 08 AUG) |
### Expected behavior
- PDB path attributes are not generified using regexps.
### Actual behavior
- PDB path attributes are generified using regexps (**C:\Users\mr.tekide\Documents\** becomes **%USERPROFILE%\Documents\**).
### Steps to reproduce the behavior
- Add a PDB path attribute to a stock install of MISP.
  - For example: _C:\Users\mr.tekide\Documents\Visual Studio 2013\Projects\paccrypt11njratmalii\paccryptalipnahzade\obj\Debug\LManager.pdb_ from [here](https://citizenlab.org/2016/08/group5-syria/).

The whole point of PDB paths is to preserve unique/identifying informations such as the user-names.

**Comment by elhoim** [comment]
Looks like it is soled in 2.4.56.

**Comment by iglocska** [comment]
Wait, it shouldn't be!

**Comment by elhoim** [comment]
Opened https://github.com/MISP/MISP/pull/10968 against `2.5`: adds `pdb` to `RegexpBehavior::EXCLUDED_TYPES` (`app/Model/Behavior/RegexpBehavior.php:12`), so the default type-`ALL` `%USERPROFILE%\` regexps shipped in `INSTALL/MYSQL.sql` no longer rewrite debug-symbol paths. Also covers the duplicate #2823.
