### ISSUE TITLE
misp-modules script not starting from rc.local

### ISSUE THREAD

**Issue by infde6** [MISP/MISP#1424]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu 16.04 |
| OS version (client) | Windows 8 |
| PHP version | PHP 7.0.8 |
| MISP version / git hash | 2.4.49, hash of the commit |
| Browser | not applicable |
### Expected behavior

From MISP-modules page;
"sudo vi /etc/rc.local, add this line: `sudo -u www-data /usr/bin/python3 /usr/local/src/misp-modules/bin/misp-modules`"
- Reboot
- misp-modules should load all identified modules and be available on localhost for querying
### Actual behavior
- Follow installation instructions
- Reboot
- misp-modules python script does not start
- command "`sudo -u www-data /usr/bin/python3 /usr/local/src/misp-modules/bin/misp-modules`" starts misp-modules, but no extensions are detected.

Stdout message is, "misp-modules - INFO - MISP modules server started on localhost port xxxxxx" but no modules loaded.
### Steps to reproduce the behavior

Follow installation instructions and reboot
### Logs, screenshots, configuration dump, ...

N/A
### Possible work-around

Running the command from the main misp-modules directory starts and loads modules. (e.g. sudo --u www-data /usr/bin/python3 bin/misp-modules)

Stdout message is;
"misp-modules - INFO - Helpers loaded cache.py
misp-modules - INFO - MISP modules <module name> imported"

Would it be possible to define a misp-modules home_dir instead of using relative path directives for helpersdir and modulesdir in the script?

**Comment by Rafiot** [comment]
Does it works if you do `sudo -u www-data misp-modules -s` ? If yes, I'll update the documentation.

**Comment by Rafiot** [comment]
I'll merge upstream if it fixes your issue.

**Comment by cristianbell** [comment]
Tested on ubuntu 16.04 and it looks ok, the misp-modules works even after reboot.

**Comment by Rafiot** [comment]
excellent, thank you very much

**Comment by p3tr0v** [comment]
Don't worked on Debian 9.
I followed installation instructions; added `sudo -u www-data misp-modules -s` in /etc/rc.local; and rebooted the system... didn't work. Should i open a new issue?
