### ISSUE TITLE
populate from EML

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#143]
Feature request:

functionality should be:
- populate from EML > user uploads EML mail
- uploads EML as malware sample
- generates attributes from email header (from, to, subject, User-agent, x-headers)
- extracts attachments, uploads attachments as "malware sample"

**Comment by adulau** [comment]
There is an email/eml parsing module in Viper that should be quite straight to extend the Viper misp to support the export to MISP. @Rafiot what do you think?

**Comment by cvandeplas** [comment]
I'm not sure if I understand it correctly, but I wouldn't put a dependency on Viper for a user to import an eml/msg into MISP.

**Comment by adulau** [comment]
It most likely Viper will be along with the next releases of MISP to support the plug-in architecture.

**Comment by advancedeng** [comment]
Hi gents, just to let you know that this capability would be very useful for the organisations that use MISP since one could easily populate MISP events , since email is the most common attack verctor out there..

**Comment by adulau** [comment]
@rommelfs Could we use your email parser to generate MISP JSON files easilt?

**Comment by Rafiot** [comment]
See: https://github.com/MISP/misp-modules/pull/62

**Comment by seamustuohy** [comment]
Just saw this. I didn't see an obvious way to send back the attachments as files to be uploaded. If this is possible I'd happily add that.  Also, if there are other things you would like extracted (user agent, etc.) I'd be happy to add them if you point out the appropriate values to use for them. (for example which ip and hostname related components to use for the addresses listed in the `received` headers.)

**Comment by adulau** [comment]
The import module done by @seamustuohy is covering the majority of the functionality requested. Feel free to reopen if this is not the case.

https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/import_mod/email_import.py
