### ISSUE TITLE
JSON export contains duplicate responses

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1439]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.50, a30fdba05a50d60752db5cfaba951accabb664c0 |
| Browser | not applicable |
### Expected behavior

The JSON export should contain all events just once
### Actual behavior

The JSON export contains multiple "response" sections that each contain the complete MISP export
### Steps to reproduce the behavior

Enable the cache_exports schedules task, observe the huge files in tmp/cached_exports/json
### Logs, screenshots, configuration dump, ...

Not applicable

**Comment by iglocska** [comment]
Oh wow, that definitely sounds bad. Looking into it.
