### ISSUE TITLE
wrongly used references for variables?

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1472]
in these lines linked below, there is an ampersand used to reference the original content.
as far as i can tell, this is not necessary:
https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L37
https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L45
https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L424
https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L451

https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/HidsExport.php#L20
https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/HidsExport.php#L21

if this is like i said, the PR #1465 also has to be changed as it copied some parts of these files.

**Comment by iglocska** [comment]
Some of those are counter-productive, such as NidsExport L45, L424, L451 and HidsExport L21, some productive but not needed NidsExport L37 and HidsExport L20.

They can all be removed.

**Comment by rotanid** [comment]
reopen to make sure it isn't reintroduced in the Bro export #1465

**Comment by rotanid** [comment]
looks like it wasn't reintroduced, closing.

**Comment by iglocska** [comment]
;)
