### ISSUE TITLE
Support : Table cake_sessions for model Session was not found in datasource default

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1474]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Support |
| OS version (server) | Ubuntu 16.04 |
| PHP version | 7.1. |
### behavior

When opening misp i get this error : 
`Table cake_sessions for model Session was not found in datasource default`
I read that 
[https://github.com/MISP/MISP/issues/232](https://github.com/MISP/MISP/issues/232)
but couldn't fix.
### actions before :

Yesterday I couldn't log (timeout after posting credentials)
I noticed that the cake_sessions table was 20Gb (_i've been told that this is fixed with version 2.4.50 - table emptied upon admin login or via <url>/servers/serverSettings/diagnostics settings_ )

I created a temp one "like" cake_sessions then
`drop table cake_sessions;`
`Query OK, 0 rows affected (12 hours 4 min 57.98 sec)`
 i then renamed temp to cake_sessions

As i got that error i drop the table again and recreated it (using 

`CREATE TABLE IF NOT EXISTS`cake_sessions`(
`id`varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
`data`text COLLATE utf8_bin NOT NULL,
`expires`int(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX`expires`(`expires`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
`
from /var/www/MISP/INSTALL/MYSQL.sql

Same error.
I double checked  database config.

 show tables;
+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| admin_settings                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
[etc]

describe cake_sessions;
+---------+--------------+------+-----+---------+-------+
| Field   | Type         | Null | Key | Default | Extra |
+---------+--------------+------+-----+---------+-------+
| id      | varchar(255) | NO   | PRI |         |       |
| data    | text         | NO   |     | NULL    |       |
| expires | int(11)      | NO   | MUL | NULL    |       |
+---------+--------------+------+-----+---------+-------+

Any hints on what i am missing here ?

**Comment by Kafeine** [comment]
...not sure to understand what happened. Doing nothing specific other than working on something else and checking back : now fixed.

**Comment by iglocska** [comment]
What happened probably was that the table's model cache had to be recreated, it probably worked on the second page load after dropping and recreating the table.
