### ISSUE TITLE
Unable to run Export (JSON,XML,etc...)

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1480]
The issue that I'm is that when I click on Export and try to click Generate or Export nothing happens. When I click download, I get the following error: The requested file was not found
Error: The requested address '/events/downloadExport/json' was not found on this server.

On the main export page, the progress shows N/A and when I click on generate nothing happens.

Unable to resolve issue and can't figure out what the issue is.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Suport |
| OS version (server) | CentOS 7 |
| OS version (client) | CentOS 7 |
| PHP version | PHP Version (>5.6.0 recommended): 5.6.5 (Up to date) |
| MISP version / git hash | Currently installed version..... v2.4.49  Latest available version..... v2.4.50 Status..... Outdated version |
| Browser | Chrome, FireFox, IE |
### Expected behavior

Export xml, JSON and download the files
### Actual behavior

Not working. When I click generate it doesn't show and progress and it states N/A. Unable to download as nothing was generated

**Comment by iglocska** [comment]
Could you check if your background workers are running? Administration -> Server settings -> workers.

Also could you update to the latest version? It includes better error reporting for failed background jobs (basically the export cache generation is handled by background processes - with the latest version you can view the exact reason why they fail in the administration -> jobs view).

**Comment by gra55h0pp3r** [comment]
I just loaded it based on the CentOS documentation. I'm looking for the upgrade documentation, so I can upgrade it. I know one issue when I loaded MISP was when I went to add and event I got and error. I read a message board about modifying the Event.php with the date.timezone and that fixed it. The installation documentation instructions for date.timezone doesn't work, but that if fixed for now.

So I check the workers and everything has Okay and running except for Scheduler. It has the following error message: 95365  root    Unknown The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or not.

**Comment by iglocska** [comment]
If it's only the scheduler that is broken then it is most likely an issue with php-redis not being installed correctly. 

Could you check if it's installed? 
pecl install redis-2.2.8

For updating MISP, simply do the following:

cd /var/www/MISP
git pull origin 2.4

**Comment by gra55h0pp3r** [comment]
Okay. I tried running pecl install redis-2.2.8, but I'm guessing it's not installed since I get bash: pecl: command not found.

I also ran the upgrade command, so I'm on the current version now.

**Comment by gra55h0pp3r** [comment]
So I just checked the installation documentation and I see you were supposed to run yum install php-redis.  It was on a commented line, so I ran that command. I was able to generate and download files, now, but the scheduler work is still not working. Is this still and issue?

**Comment by iglocska** [comment]
Well it depends, the scheduling can be handy if you want to schedule
regular pulls from other instances for example, but otherwise it's not
crucial. However it would be nice to debug it still. Does it still say
" Unknown
The worker was started with a user other than the apache user" ?

**Comment by gra55h0pp3r** [comment]
I definitely want to try to get all the bugs fixed, because I plan on using this platform for Army CPB. We have an issue of trying to collect information and where to store it. This platform seems to be exact what we will need to allow collection of IOC's and intel to be in one single location where all CPT's can get threats and signatures from. Right now, our plan was to extract all types, hostname, IP address, domains, and etc... and store them in plain text files. Not sufficient, so I've been messing around with MISP since last night.

Yes, it still shows the same error. I was looking around and found someone else had the same issue. They mentioned the following change: https://github.com/MISP/MISP/commit/c9bf8105e625eeab7b16593d8af76d62a2838c9a

Original Issue: https://github.com/MISP/MISP/issues/685

**Comment by gra55h0pp3r** [comment]
Based on the error it looks like scheduler is running as root and not apache like all the others. Is it supposed to run as root? I tried making the change in the issue forum, but it didn't work for me.

**Comment by iglocska** [comment]
You can try to kill all the workers manually from the command line:

/var/www/MISP/app/Console/cake CakeResque.CakeResque stop 

then just kill the schedule worker (5 by default).

After this you should be able to start it again from the interface (Administration -> Server settings -> workers -> Schedule worker)

Let me know how it goes!

**Comment by gra55h0pp3r** [comment]
I command, but I'm only showing 4 worker list. I don't see the Schedule Worker in the list.

I stopped the four workers in list, but when I try to start the worker in the interface it doesn't seem to work for some reason. If I run su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh' it bring up the four workers again.

At the end it tells me that the scheduler workers is already running.
Creating the scheduler workers
The scheduler worker is already running

**Comment by iglocska** [comment]
Interesting, let's see if the following fixes it:

`cp -fa /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php`

This will copy over the config.php file that enables the scheduler worker in the first place in case.

`/var/www/MISP/app/Console/cake CakeResque.CakeResque stop --all`

The above command kills all the workers.

For the following, only run this is you are not running any other services on the same server that use redis:

`redis-cli`
`flushall`
`exit`

After this go to the worker interface and click on restart all.

**Comment by gra55h0pp3r** [comment]
Okay. So I followed the fix and everything worked. The only issue is that I can restart all workers from the interface for some reason. I even tried restarting on worker with no luck. So what I had to do is run start.sh script for it to start all the works. After doing this, I check the interface and everything is showing okay now.

Wonder why I can't start them from the interface.

**Comment by iglocska** [comment]
That is indeed weird, but it happens for several users under RHEL/CentOS. Not really sure why, there is a small fix I tried to use for it: in server settings -> MISP tab there is a setting called "MISP.rh_shell_fix", turning that to true attempts to use a small workaround, but it works on some installations and not on others. I'll try to look into it in the near future, but we only use Ubuntu installations so will have to spin up a CentOS machine to test it.

Maybe some other CentOS / RHEL users can chip in?

**Comment by gra55h0pp3r** [comment]
Thanks. I will try that setting to see if that helps out. Maybe you can help me out, but I was wondering if there was a way for attributes can be marked with a classification? Also, what a snort rules and yara rules. I would like to insert them to an event as a signature that was develop. I.E. list all the attributes, domain, IP, hostname, filename, hashes, but then list a snort or yara signature that was developed based on the information in a report. I know tagging is one way, but I looking at individually tagging attributes as we have things are considered classified while other attributes are considered unclassified. I thought about creating two different events, but I would like to see if there is a way I can add in a column for classifying attributes.

Thanks for all your help. At least everything is up and running. I did run into some problems during the installation like setting up the mysql, because creating the user misp@localhost the password was 'XXXXXX', but I didn't know I had to enter my own password until I looked at other installation guides and saw I was supposed to enter a password. They should put 'XXENTERYOUROWNPASSOWRDXX' or put a comment to change XXXXXX to a password of the users choice.

Another question I have is about import STIX reports. I don't see the an option for import STIX.

Another question, who updates the free-text tool? I was looking at the Complex...php and I saw the regexs they were using to determine IP address, url and etc... I have a couple regex queries I wrote for my python script to pull snort and yara rules from a text file I read in. I would like to see if there is a way to integrate a regex to try to pull SNORT and YARA rules from the text.

**Comment by RichieB2B** [comment]
I have the same issue that I cannot restart the workers from the web interface. So I just run the start.sh manually. I'll check if have the MISP.rh_shell_fix set tomorrow.
