### ISSUE TITLE
issues with commit 7e05350 (check remote server version)

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1483]
possible issues with commit 7e0535035285f9a8a07478ca640310c3ed1b89cf "fix: Added internal convenience method to check remote server version"

wrong description:
https://github.com/MISP/MISP/commit/7e0535035285f9a8a07478ca640310c3ed1b89cf#diff-5043d40040a721280ed4c0c7fb144ecbR2907

wrong return of a non-existent variable
https://github.com/MISP/MISP/commit/7e0535035285f9a8a07478ca640310c3ed1b89cf#diff-5043d40040a721280ed4c0c7fb144ecbR2933

**Comment by rotanid** [comment]
nope, only partly fixed.

**Comment by rotanid** [comment]
@iglocska what about the 2nd part of this issue?

**Comment by iglocska** [comment]
Ah indeed, nice catch. Fixed in https://github.com/MISP/MISP/commit/ab606d779d6b5fe4faf72662406ae2298061f642
