### ISSUE TITLE
Unable to access MISP after installation

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1488]
After installing MISP on CENTOS7, I'm able to access the webpage, but I get the following error message: 

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

I've tried restarting service, but no luck. Any ideas what may be wrong

**Comment by iglocska** [comment]
Could you check the error log? It's located in /var/www/MISP/app/tmp/logs/error.log - all errors should be captured in there.

**Comment by gra55h0pp3r** [comment]
Thanks! I see in the log I was getting accessed denied to the database. I enter the password again in the database.php and it resolved my issue. This issue can be closed.

**Comment by rotanid** [comment]
thanks for the feedback.
