### ISSUE TITLE
Unable to login after running Upgrade.txt

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1490]
I was upgrade my system and after upgrade I'm unable to login with the admin@admin.test. I know the password, but it keeps telling invlaid username and password.

Looks like the request is getting black-holed.

2016-08-31 14:38:19 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(UsersController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by Rafiot** [comment]
Are you upgrading from 2.3?

**Comment by iglocska** [comment]
It looks like you got black holed - this can be caused by the CSRF protection if you tried to reuse the same form more than once (basically after failing a login going "back" in your browser and using the same form again). Make sure that you refresh the form before attempting to log in.

Alternatively if you would like to reset your password, you can do so using the command line:

/var/www/MISP/app/Console/cake Password your@email.address your_new_password

**Comment by gra55h0pp3r** [comment]
I tried reloading everything all over again, but now I'm getting the following message:

PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28
PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php): failed to open stream: No such file or directory in /var/www/MISP/app/Console/cake.php on line 27
PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php' for inclusion (include_path='/var/www/MISP/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Console/cake.php on line 27
PHP Fatal error:  Could not locate CakePHP core files. in /var/www/MISP/app/Console/cake.php on line 28

**Comment by gra55h0pp3r** [comment]
I tried following this answer:

there are some instructions in the UPGRADE.txt to get this working -- from memory thats what i used to get mine working;

Enabling background jobs via CakeResque 
(assuming /var/www/MISP as your installation directory)

Enable CakeResque in MISP

vim /var/www/MISP/app/Config/bootstrap.php
set Configure::write('MISP.background_jobs', false); to Configure::write('MISP.background_jobs', true);
uncomment CakePlugin::load('CakeResque', array('bootstrap' => true));
start the background workers

cd /var/www/MISP/app/Console/worker/
./start.sh Make sure you configure your OS to start this script as boot time !

But the unable to start. :-|

**Comment by gra55h0pp3r** [comment]
So I checked the directory '/var/www/MISP/app/Lib/cakephp' and it's empty. I pulled the repo down using git, so why isn't the folder content being download?

**Comment by iglocska** [comment]
Could you run the following?

git submodule init
git submodule update

Also, UPGRADE.txt should never be needed. When you have a working installation just run "git pull" to update.

*Exception new major versions (so once we move to MISP 2.5 / 3.0)

**Comment by gra55h0pp3r** [comment]
Okay. I ran the command and ran some of the commands after that and it's finally up and working...... Thanks a lot for you help.

**Comment by iglocska** [comment]
Excellent, glad that it worked out! Closing the issue for now!
