### ISSUE TITLE
SSL Setup CENTOS 7

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1496]
MY site is currently setup with http, but I would like to change it to SSL (HTTPS). I was looking at the apache.misp.centos7  and apache.misp.ssl files, but no truely understand what I need to do. This is my first time working with MISP, so is their a guide on how to do?

**Comment by cristianbell** [comment]
make sure you install mod_ssl: `yum install mod_ssl`. 
This should install mod_ssl, enable it and create certificates, key. 
If this doesn't happend you need to: 
add some certificates to your server. You can get one from a signing authority or you can generate one for yourself. More info here: https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian8.txt#L138 
or just use the following commands: 
- `openssl genrsa -out mydomain.key 1024`
- `openssl req -new -key mydomain.key -x509 -out mydomain.crt`
- `mkdir /etc/httpd/`
- `mkdir /etc/httpds/`
- copy the keys to the above created folders;
- **SSL conf file:** use the built-in and add the MISP location and other settings or easier just use the one provided with MISP as an example. 
- make sure the the `LoadModule mod_ssl` directive is loaded; 
- Since you probably have SELinux enabled check if the server is accessible on port 443; if not make sure it is. 

**RECOMMENDED:** configure SSL protocol to TLS, select a better cypher suite.. ;

This should be it more or less, hope I haven't missed anything. But if in doubt look here: https://wiki.centos.org/HowTos/Https 
good luck!

**Comment by iglocska** [comment]
Please don't suggest the creation of or use 1024 bit rsa keys. It has been insecure and disallowed for a long time now.

https://www.keylength.com/en/4/

**Comment by gra55h0pp3r** [comment]
I'm lost with the make sure the the LoadModule mod_ssl directive is loaded. I installed mod_ssl, generated all the keys, and copied the apache.misp.ssl to /etc/httpd/conf.d/misp-ssl.conf. Of course, when I restart the httpd.service I get an error.

**Comment by gra55h0pp3r** [comment]
I can't get SSL to working no matter what I try...

**Comment by adulau** [comment]
Could you share the Apache error?

**Comment by iglocska** [comment]
I am currently a bit strapped for time as I am travelling in a few hours and I am not a CentOS user, but something like this should work:

```
<VirtualHost *:443>
    ServerAdmin me@me.local
    ServerName misp.local
    DocumentRoot /var/www/MISP/app/webroot
    <Directory /var/www/MISP/app/webroot>
        Options -Indexes
        AllowOverride all
        Order allow,deny
        allow from all
    </Directory>

    <IfModule !mod_php5.c>
        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
        DirectoryIndex /index.php index.php
        <FilesMatch \.php$>
            SetHandler "proxy:fcgi://127.0.0.1:9000"
        </FilesMatch>
    </IfModule>

    SSLEngine On
    SSLCertificateFile /etc/pki/tls/certs/misp.local.crt
    SSLCertificateKeyFile /etc/pki/tls/private/misp.local.key
    SSLCertificateChainFile /etc/pki/tls/private/misp-chain.crt

    LogLevel warn
    ErrorLog /var/log/httpd/misp.local_error.log
    CustomLog /var/log/httpd/misp.local_access.log combined
    ServerSignature Off
</VirtualHost>
```

Also, make sure that enable listening on port 443 in your apache config (it most likely has a line that says "Listen 80", change that to "Listen 443"). As for the above, there are 3 file paths for your keys, basically SSLCertificateChainFile is optional, make sure that you copy the certificate files to the correct locations.

Once you are done  just throw the .conf file in your httpd directory and it should work after a restart of apache.

I am not 100% certain that the above is correct, it's just something I tried to write up from memory, I'll try to find some time over the weekend to spin up a CentOS VM and give it a shot if you are still stuck after trying the above.

**Comment by gra55h0pp3r** [comment]
So I think I finally got it working. Below is my misp.conf that I modified:

```
Listen 443 https

<VirtualHost *:80>
#       ServerAdmin me@me.local
        ServerName misp.local
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        <IfModule !mod_php5.c>
                SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
                DirectoryIndex /index.php index.php
                <FilesMatch \.php$>
                        SetHandler "proxy:fcgi://127.0.0.1:9000"
                </FilesMatch>
        </IfModule>

#       Redirect permanent /https://MYDOMAINTHATIAMUSING/

        LogLevel warn
        ErrorLog /var/log/httpd/misp.local_error.log
        CustomLog /var/log/httpd/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
<VirtualHost *:443>
        ServerAdmin me@me.local
        ServerName misp.local
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>


        <IfModule !mod_php5.c>
                SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
                DirectoryIndex /index.php index.php
                <FilesMatch \.php$>
                        SetHandler "proxy:fcgi://127.0.0.1:9000"
                </FilesMatch>
        </IfModule>


        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.local.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.local.key
#       SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

        LogLevel warn
        ErrorLog /var/log/httpd/misp.local_error.log
        CustomLog /var/log/httpd/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
```

The problem I'm having now is login back into the interface. After trying to get SSL working I'm now unable to login. I put in another issue for that, because I tried using the cake Password admin@admin.test admin to reset the password, but I get an error message.

PHP Fatal error:  Can't use function return value in write context in /var/www/MISP/app/Model/User.php on line 736
Fatal Error Error: Can't use function return value in write context in [/var/www/MISP/app/Model/User.php, line 736]

**Comment by iglocska** [comment]
Hmm that is weird. It sounds like you're actually not going through the correct SCL php 5.6 version but instead the standard EOL CentOS version (5.3?) that doesn't support using function returns directly.

**Comment by iglocska** [comment]
Ah indeed, you are running the password reset via the command line. Make sure you type this beforehand: 

scl enable rh-php56 bash
cake /var/www/MISP/app/Console/cake Password your@email.address new_password

**Comment by gra55h0pp3r** [comment]
Thanks! I looked at how to make is globally available, so I don't have to do that all the time. It worked, but still giving me an error invalid username and password, please try again.

Do I need to clear the cache or something on the server?

**Comment by iglocska** [comment]
It should work, that is definitely weird.

Just testing it on one of my systems and it seems to work correctly. Sure it's not a typo?

**Comment by gra55h0pp3r** [comment]
It's telling me that it's updated my password, but when I try to login through the UI it tells me my username and password is invalid and to try again.

I even tried changing it to a totally different password, clearing my cookies, and last ditch effort restarting the server.

**Comment by iglocska** [comment]
Hmm, one thing you could try is this:

mysql -u misp -p misp
<enter your mysql password for the misp user>
delete from bruteforces;

If you try more than 5 times in close succession you get locked out for 5 minutes by the bruteforce protection. This should clean out the previous attempts so you don't have to wait.

**Comment by gra55h0pp3r** [comment]
After clearing out the bruteforces and setting a new password it worked. Thanks! I'm learning so much about MISP and hopefully I can get it approved for our network. I took off the SSL, so I'm going to try to integrate SSL again.

Thanks for everyone help and support.

**Comment by iglocska** [comment]
Excellent news! :) Let us know if you run into any issues or have any questions! I'll close this issue for now.
