### ISSUE TITLE
Unable to reset password with cake

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1499]
I was able to login in previous, but when I was trying to setup SSL it's not longer working. I tried running the following command: /var/www/MISP/app/Console/cake Password admin@admin.test admin to reset it back to the default, but I get the following error below:

PHP Fatal error:  Can't use function return value in write context in /var/www/MISP/app/Model/User.php on line 736
Fatal Error Error: Can't use function return value in write context in [/var/www/MISP/app/Model/User.php, line 736]

Need some assistance.

**Comment by RichieB2B** [comment]
You are on CentOS and need to enable php56 first:
`scl enable rh-php56 bash`

**Comment by gra55h0pp3r** [comment]
Okay. Once I did that it change my password, but now I'm still get Invalid Username and password try again. Is there something I can clear that maybe is causing it to not work.

**Comment by rotanid** [comment]
related to #1496
