### ISSUE TITLE
XML inside STIX JSON export

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1505]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.51 |
| Browser | not applicable |
### Expected behavior

When requesting http://misp.local/events/stix/download.json a JSON response is expected.
### Actual behavior

The returned data contains the STIX XML header with JSON following it. At the end the document is closed with `</stix:STIX_Package>`
### Steps to reproduce the behavior

Request http://misp.local/events/stix/download.json
### Logs, screenshots, configuration dump, ...

No errors in the logs

**Comment by RichieB2B** [comment]
Problem is due to always calling misp2stix_framing.py introduced by https://github.com/MISP/MISP/commit/734df040008c4ac40bcf3c275a090626b2857460

**Comment by iglocska** [comment]
Ah damn completely forgot about the stix json
