### ISSUE TITLE
STIX export leaves temporary files in app/files/scripts/tmp

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1509]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.51 |
| Browser | Not applicable |
### Expected behavior

Temporary files should be deleted after the export
### Actual behavior

It looks like `$tempFile->delete();` and `$stixFile->delete();` is never called when the export is successful at https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2500
Related to #1505
### Steps to reproduce the behavior

Export an event (or entire collection) in STIX format
### Logs, screenshots, configuration dump, ...

None

**Comment by rotanid** [comment]
$tempFile could be deleted within the stix() function, but not the $stixFile, because the functions doesnt return that file or data itself but only the path to the file - so you can't delete it in this function...

**Comment by RichieB2B** [comment]
Yes, this was changed in 2.4.51. Before Event->stix() returned the data and removed the temp files. Now it returns the file name and the $stixFile is never deleted. I'm not sure why the previous behaviour of returning the data was changed.

**Comment by iglocska** [comment]
Please let me know if you into any issues with this, I literally fell asleep half way through patching it :)
