### ISSUE TITLE
Add attribute type to track whois registrant email address

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#151]
Some campaign use the same email to register a couple of domains.

Category network activity seems the most appropriate

**Comment by dspruell** [comment]
Is this one complete? We have Category: *Attribution*, Type: *whois-registrant-email* in 2.4. (Attribution seems most appropriate as Network Activity appears to relate mostly to malware network communications/etc.).

**Comment by adulau** [comment]
The attribute 'whois-registrant-email' is there in 2.4. Regarding the classification, maybe we should add it in Network Activity too. If everyone agree, I'll add the whois-* series in Network Activity.

**Comment by iglocska** [comment]
Sure, sounds good!

**Comment by Rafiot** [comment]
Done.
