### ISSUE TITLE
Error: Database connection "Mysql" is missing, or could not be created

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#1516]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | support |
| OS version (server) | ubuntu Description:    Ubuntu 14.04.5 LTS , Release:        14.04, Codename:       trusty |
| OS version (client) | Seven |
| PHP version | PHP 7.0.10-2+deb.sury.org~trusty+1 |
| MISP version / git hash | MISP 2.4.51 |
| Browser | FF |
### Expected behavior

Sync with external servers and store/publish events
### Actual behavior

Jobs -> Publish events are failing (only the external ones)
Jobs -> Pull jobs are queued 

![screenshot](https://cloud.githubusercontent.com/assets/8973767/18271694/5fa858cc-742b-11e6-9123-b1ccf537b3a3.png)
### Logs, screenshots, configuration dump, ...

[2016-09-06 11:50:47] main.ERROR: {"queue":"default","id":"7f2ebce4b1bd5fabd446b63f36d42e2a","class":"ServerShell","args":[["pull","7","1","full","79458"]]} failed: Database connection "Mysql" is missing, or could not be created. {"type":"fail","log":"Database connection \"Mysql\" is missing, or could not be created.","job_id":"7f2ebce4b1bd5fabd446b63f36d42e2a","time":41,"worker":"misp-prod:18298"} []

Failed at: Tue Sep 06 11:34:55 BST 2016
Exception: MissingConnectionException
Error: Database connection "Mysql" is missing, or could not be created.
(Click to hide stack trace)
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3626): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3653): Model->setSource('logs')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1387): Model->getDataSource()
#5 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(275): Model->schema()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('User', Array)
#9 /var/www/MISP/app/Model/AppModel.php(31): Model->__construct(NULL, 'default')
#10 [internal function]: AppModel->__construct(Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#12 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(271): ClassRegistry::init('User')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(Event), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('Event', Array)
#16 /var/www/MISP/app/Model/AppModel.php(31): Model->__construct(NULL, 'default')
#17 /var/www/MISP/app/Model/Event.php(252): AppModel->__construct(Array, NULL, NULL)
#18 [internal function]: Event->__construct(Array)
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init('Event')
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel('Event')
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#23 /var/www/MISP/app/Console/Command/AppShell.php(31): Shell->initialize()
#24 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#25 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#26 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#27 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#28 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('prio', 1, Object(MonologInit\MonologInit), '5')
#29 {main}

**Comment by valworbli** [comment]
The run.sh script does not replace the database name with the one from the environment, hence the problem. Fix your run.sh script.
