### ISSUE TITLE
"Internal Error Has Occurred" and error.log not populating

### ISSUE THREAD

**Issue by iamtmehdi** [MISP/MISP#1517]
Hello,
When I log into MISP i get the following:
"An Internal Error Has Occurred"
This same page pops up when I go to complete other tasks, such as going to settings "Administration -> Server Settings" and adding events "Event Actions -> Add Event".

I went into /var/www/MISP/app/tmp/logs/error.log but the log is not populating with the new events. I have made sure that the file is writable via the "apache" user.

Any advice?
Thank you

**Comment by iglocska** [comment]
That is definitely weird. Could you temporarily enable debug mode in /var/www/MISP/app/Config/config.php? 'debug' => 2 should do the trick.

Make sure that your MISP is not visible externally during this as the debug is quite verbose.

**Comment by iamtmehdi** [comment]
Hello,
Really sorry for the late reply. Will need to look into getting email notifications.

Fatal Error
Error: Class 'SysLog' not found 
File: /var/www/MISP/app/Controller/UsersController.php  
Line: 854

Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

**Comment by iglocska** [comment]
Could you run git 

`rev-parse HEAD`

and paste the returned commit hash here? The error message is strange, SysLog should be available via /var/www/MISP/app/Plugin/Syslog/Lib/Syslog.php

**Comment by iamtmehdi** [comment]
This returns, `751bad65bbf7c0a68087e306481c124275cc9f6f`

**Comment by adulau** [comment]
We will close this issue. If the issue persists, feel free to reopen the ticket.
