### ISSUE TITLE
MISP behind a reverse proxy?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1518]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug? Configuration? |
| OS version (server) | Ubuntu 14.04 |
| OS version (client) | Seven |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.48 |
| Browser | Firefox |
### Expected behavior

I just moved a MISP instance behind a reverse-proxy (nginx).
The SSL connection is terminated by the nginx, MISP is accessed through port 80.
BaseURL is set to "https://misp.tld" in config.php
### Actual behavior

nginx connects to the MISP instance but the Apache server returns a 302 with a location http://misp.tld/. This URL is returned to the browser who can access MISP on port 80.
### Steps to reproduce the behavior

Sniff the network traffic between NGING & MISP

**Comment by iglocska** [comment]
Indeed this is an issue. Right now MISP uses relative redirects which causes this, the protocol is automatically detected. I think your best bet until we change this is using rewrite rules for now, I'll try to refactor the internal redirects to resolve this as this keeps popping up quite often.

**Comment by xme** [comment]
Tx Andras! Just to clarify things, you'd implement the rewrite rule at Apache (MISP) or NGING (reverse proxy) level?

**Comment by iglocska** [comment]
I'd do it on apache level but not sure if that's the correct answer here :)

**Comment by xme** [comment]
After some googling, I changed in nginx.
For the MISP virtual host, I added:

proxy_redirect http:// https://

It seems to be fine now!

/x

**Comment by iglocska** [comment]
Excellent news B-) I'll close the ticket for now, feel free to open a new one if you run into any other issues with it!

**Comment by ag-michael** [comment]
Please re-open this issue, the problem is still here. even though OP resolved it by redirecting to https, in my issue the upstream MISP host is not accesible by the browser, MISP needs to use the base url not relative redirects.

**Comment by ag-michael** [comment]
@iglocska 

Consider this nginx config for MISP UI:

```
 location / {
            auth_request /authenticateusers;
            error_page 401 =200 /loginform;
            proxy_pass http://10.0.6.2:8080/;
        }
```
Regardless of what the baseurl is set to, MISP would redirect to http://10.0.6.2:8080. However, that subnet would be on a segregated vlan and VM. How can I resolve this?
