### ISSUE TITLE
Updated event alert E-mail do not indicate new attributes

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1521]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.51 |
| Browser | Not applicable |
### Expected behavior

The E-mail body says "Attributes (\* indicates a new or modified attribute)" so it should do that.
### Actual behavior

None of the attributes have a \* indicator.
### Steps to reproduce the behavior

Update an attribute, publish the event, observe the alert E-mail body
### Logs, screenshots, configuration dump, ...

None

**Comment by iglocska** [comment]
I've tried this a while ago but it seemed to work ok. The \* was at the start of the line with the indicator that is newer than the previous publish timestamp of the event. I've changed it slightly so it's a bit more obvious.

**Comment by RichieB2B** [comment]
I've just updated our MISP instances but the issue persists. You added a \* at the end of the line in https://github.com/MISP/MISP/commit/3ad8422df0c8391589be48ba5a748413f428077d but I think the problem is with publish_timestamp often being larger than the new attributes timestamp.

I think there is a race condition in the _edit() function where sendAlertEmailRouter() is called that creates a new job to send the E-mail and right after publish() updates the publish_timestamp. By the time sendAlertEmail() fetches the event publish_timestamp is already updated.

**Comment by iglocska** [comment]
You are indeed correct, just checked it in the code and indeed, if the sending of the alert email is delayed then it will not pick up on it. Interesting issue, I'll look into a possible fix.
