### ISSUE TITLE
User without sync rights cannot download MISP JSON & XML

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1525]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | ubuntu |
| MISP version / git hash | 2.4.51 |
### Expected behavior
- A user without sync rights would still be able to export using the Download as MISP JSON & Download as MISP XML options from an event
### Actual behavior
- Since those two options are now using the API, the user cannot download.
### Steps to reproduce the behavior
- Create or use an existing user without API rights
- Try to download MISP JSON or MISP XML from any event

**Comment by iglocska** [comment]
Thanks for the heads-up!
