### ISSUE TITLE
Importing custom-defined fields from a CSV.

### ISSUE THREAD

**Issue by tanakra** [MISP/MISP#1526]
| Questions | Answers |
| --- | --- |
| Type of issue | Question, Feature Request |
### Expected behavior

Would it be possible to custom-define fields of a CSV spreadsheet so that data stored in the spreadsheet can easily be imported into MISP? E.g. a spreadsheet containing columnar artifacts, meta-data and IOCs such as **date**, **time**, **target**, **source**, **strings**, **x-mailer**, etc.

**Comment by iglocska** [comment]
Do you mean for fields that don't directly exist in MISP and how to map them? Or how to actually ingest CSVs? For the former, we can have a look at the various points of data that aren't an obvious match and see if we have something that matches it, or if not we can look into adding the missing types in a future release.

For ingesting CSVs, the best way to move forward is probably an import module or a PyMISP script (both options should be pretty easy with a few lines of python).

**Comment by tanakra** [comment]
Hi iglocska,

I was looking into the latter (ingesting a CSV) as the fields we are looking to import are pretty generic and exist in MISP. As per your suggestion, I will look into an import module or into putting together a PyMIST script.

Thank you!

**Comment by Rafiot** [comment]
Closing, please open an other issue if you have a problem.
