### ISSUE TITLE
Related events in event display from own org

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1528]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| MISP version / git hash | 2.4.51 |
### Expected behavior
- Related events from same source org are displayed in red.
### Actual behavior
- Only related events from the same member org are displayed in red.
### Logs, screenshots, configuration dump, ...
- I think the problem is [here](https://github.com/MISP/MISP/blob/43dc19ca737baf0fe51b1c77057eb1e8a5f9e146/app/View/Events/view.ctp#L184) where orgc id should be checked instead of org id.

**Comment by iglocska** [comment]
Woah nice catch.
