### ISSUE TITLE
Problem exporting yara

### ISSUE THREAD

**Issue by jpferrero** [MISP/MISP#1529]
Hello, 

I'm having some trouble exporting certain yara rules: in the meta section if there is defined a key-value parameter which value is a large string then the yara rule never get exported (using PyMISP). For example the following rule never exported:

rule silent_banker : banker
{
meta:
description = "This is just an example"
thread_level = 3
in_the_wild = true
param = "ffb0b9b5asdf23g232fd23242234ff23"
} 

If I change param key to a smaller string, for example:

param = "ffb0b9"

then the yara rule exports succesfully. 

Thanks ,

_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question, Feature Request, support... |
| OS version (server) | Debian, ubuntu, CentOS, RedHat, ... |
| OS version (client) | XP, Seven, 10, Ubuntu, ... |
| PHP version | 5.4, 5.5, 5.6, 7.0, 7.1... |
| MISP version / git hash | 2.4.XX, hash of the commit |
| Browser | If applicable |

**Comment by adulau** [comment]
Have you tested with a recent version of MISP and PyMISP?

**Comment by Rafiot** [comment]
Closing this issue. This is supposed to be supported over the search interface, or will be in a near future.
