### ISSUE TITLE
First Login - Error: The requested address '/users/login' was not found on this server.

### ISSUE THREAD

**Issue by ventz** [MISP/MISP#1532]
Followed instructions for Ubuntu 16.04 install:
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

Whenever I start everything and go to the URL, the first time I get:

```
The request has been black-holed
Error: The requested address '/users/login' was not found on this server.
```

This is with the salt changed at the correct step.

The flow seems to be:
1.) start services (check mysql "misp" db, "users" table is empty
2.) go to url (check db -> users table is populated)
3.) login - get error above
4.) delete users "id=1" entry
(alternatively: /var/www/MISP/app/Console/cake Password 'admin@admin.test' somepassword")
5.) now login with "admin@admin.test" and "admin" works

I've look around, and I can't find a solution to this. I found one bit somewhere that mentioned it being a cakephp security issue -- but it seems like the right password is not being set initially/is somehow colliding with cakephp, and it's blocking the initial user/pass permanently.

Any help would be greatly appreciated.

Similar issues reported:
https://github.com/MISP/MISP/issues/1160
and
https://github.com/MISP/MISP/issues/1513

**Comment by ventz** [comment]
_If you would like to report a bug, please fill the template bellow_

### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug? (possibly support) |
| OS version (server) | Ubuntu 16.04 LTS |
| OS version (client) | OS X (multiple versions) |
| PHP version | 7.0.8-0ubuntu0.16.04.2 |
| MISP version / git hash | Latest commit (as of now: d0041f155dcc70a76d0d6e36343a514e9540cbd3) |
| Browser | Chrome |

### Expected behavior

On initial install, after changing the salt, the user "admin@admin.test" and password "admin" should work.

### Actual behavior

```
The request has been black-holed
Error: The requested address '/users/login' was not found on this server.
```

### Steps to reproduce the behavior

Following install doc for Ubuntu 16.04 LTS:
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

Using Ubuntu 16.04 LTS (docker):
docker run -it --rm ubuntu

Using self generated cert -- if that plays a role.

### Logs, screenshots, configuration dump, ...

Using default:
000-default.conf
and
default-ssl.conf

When testing at "localhost", 000-default.conf contains:

```
<VirtualHost *:80>
ServerName localhost
Redirect permanent / https://localhost
LogLevel warn
ErrorLog /var/log/apache2/misp_error.log
CustomLog /var/log/apache2/misp_access.log combined
ServerSignature Off
</VirtualHost>
```

and

default-ssl.conf contains:

```
<VirtualHost *:443>
ServerAdmin admin@localhost
ServerName localhost
DocumentRoot /var/www/MISP/app/webroot
<Directory /var/www/MISP/app/webroot>
Options -Indexes
AllowOverride all
Order allow,deny
allow from all
</Directory>
SSLEngine On
SSLCertificateFile /etc/ssl/private/misp.crt
SSLCertificateKeyFile /etc/ssl/private/misp.key
#SSLCertificateChainFile /etc/ssl/private/misp-chain.crt
LogLevel warn
ErrorLog /var/log/apache2/misp_ssl_error.log
CustomLog /var/log/apache2/misp_ssl_access.log combined
ServerSignature Off
</VirtualHost>
```

Similar issues reported:
https://github.com/MISP/MISP/issues/1160
and
https://github.com/MISP/MISP/issues/1513

**Comment by adulau** [comment]
Do you still have the issue with any recent versions?

We will close this issue. If this is no fixed, feel free to reopen the issue.

**Comment by ventz** [comment]
@adulau I built a Docker container, which at first worked around it by doing:
```
/var/www/MISP/app/Console/cake Password 'admin@admin.test' 'SomePasswordHere'
```

I can't remember exactly when, but I think at some point this was fixed by another update to MISP.

Here is the Docker container for MISP:
https://hub.docker.com/r/harvarditsecurity/misp/

And the linked github repo:
https://github.com/harvard-itsecurity/docker-misp

I am keeping it updated as things change upstream to the install directions/files/etc.
