### ISSUE TITLE
STIX XML download from MISP

### ISSUE THREAD

**Issue by CQRuu** [MISP/MISP#1543]
Hi,

When I used the "Download as..." function in MISP and selected "STIX XML" as the format, i realized the STIX Package formatting is slightly different than that of a STIX package produced by Soltra or OTX AlienVault etc.

For comparison purposes:
1. From MISP
<stix:STIX_Package 
    xmlns:http://192.168.56.50="MISP"
    xmlns:http://cybox.mitre.org/common-2="cyboxCommon"
    xmlns:http://cybox.mitre.org/cybox-2="cybox"
1. From Soltra:
   <stix:STIX_Package 
   xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
   xmlns:cybox="http://cybox.mitre.org/cybox-2"
   xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2"
   xmlns:FileObj="http://cybox.mitre.org/objects#FileObject-2"
   xmlns:marking="http://data-marking.mitre.org/Marking-1"
   xmlns:edge="http://soltra.com/"
2. From OTX AlienVault:
   <stix:STIX_Package 
   xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
   xmlns:cybox="http://cybox.mitre.org/cybox-2"
   xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2"
   xmlns:URIObj="http://cybox.mitre.org/objects#URIObject-2"
   xmlns:indicator="http://stix.mitre.org/Indicator-2"
   xmlns:stixCommon="http://stix.mitre.org/common-1"
   xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1"
   xmlns:stix="http://stix.mitre.org/stix-1"

I was wondering if STIX XML download from MISP can have the same format as the standard STIX packages? Which means "xmlns:<namespace>="url" instead of "xmlns:url="<namespace>". eg:
<stix:STIX_Package 
    xmlns:MISP="http://192.168.56.50"
    xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
    xmlns:cybox="http://cybox.mitre.org/cybox-2"

Changing the arrangement would allow direct uploading of the files onto Soltra, which will be very helpful in the communication between MISP and SoltraEdge platforms.

Thank you!

**Comment by iglocska** [comment]
Thanks for the heads-up, indeed, not sure how that happened. Just git pull and it should be fixed.

**Comment by CQRuu** [comment]
Hi Andras Iklody,

Thanks for the fixes! Unfortunately, I'm currently using MISP in a virtual environment (via misp-training.ova file); is there any way for me to sync the updates?

**Comment by iglocska** [comment]
Log into the VM via SSH / directly via virtualbox/vmware, make sure you
have an internet connection and do the following:

cd /var/www/MISP
git pull && git submodule init && git submodule update

This should get you to the latest version always.

Let me know if you run into any issues!

**Comment by CQRuu** [comment]
Hi Andras Iklody,

It worked! YOU ARE AWESOME :D

Thank you so much! [😃]

**Comment by RichieB2B** [comment]
This is weird, I am running MISP version 2903919fcd2cef8ee4ee30c283df84c8272bd56d and just ran into this issue. If I back out commit c7414d9e56266c4cb6c2141701a753334d704ab3 the xmlns have the right syntax though. Diagnostics reports:

```
STIX: 1.1.1.4
CyBox: 2.1.0.12
```

What's going on here?
