### ISSUE TITLE
Regex for replacing part of path with environment variable

### ISSUE THREAD

**Issue by jeff3877** [MISP/MISP#1552]
When you fill an attribute with a path:
C:\Users{username}\AppData\Local\temp{myfolder}{myfilename}

You obtain:
%LOCALAPPDATA%\Temp{myfolder}{myfilename}

However the desired result would be:
%TMP%{myfolder}{myfilename} or %TEMP%{myfolder}{myfilename}

**Comment by iglocska** [comment]
That is indeed weird and that shouldn't happen. Did you alter your regex tables?

With the default regex entries I get:

Input: C:\Users\Iglocska\AppData\Local\temp\foo\bar.exe

Output: %TEMP%\foo\bar.exe

To check your regex rules, navigate to input filters -> import regexp

The rule that converts 
`/.:.Users\\(.*?)\\AppData.Local.Temp./i`to `%TEMP%\\`

Should be above the one that converts
`/.:.Users\\(.*?)\\AppData.Local./i` to `%LOCALAPPDATA%\\`

**Comment by jeff3877** [comment]
For the alteration of the regex, I need to see with my colleagues.

We have these two rules below:

29      /.:.Users\(._?)\AppData.Local.Temp./i     %TEMP%\    ALL 
31      /.:.Users\(._?)\AppData.Local./i      %LOCALAPPDATA%\    ALL

However I have tried with your example and i have obtained:

Input: C:\Users\Iglocska\AppData\Local\temp\foo\bar.exe
Output: %LOCALAPPDATA%\Temp\foo\bar.exe

Could it be that regexp 31 is used before 29? Is the ID used to sort the regexp before running them in a specific order?

**Comment by iglocska** [comment]
Indeed, it should run 29 before 31, so it is weird what is going on here. Do you have a type restriction for 29 perhaps? You should be able to see it on the right of the replacement value on the regex list.

**Comment by elhoim** [comment]
It says ALL for both 29 & 31.
We can try re-importing the data to see if it was not a temporary fluke.

**Comment by iglocska** [comment]
temporary fluke sounds even worse :)

**Comment by elhoim** [comment]
So, definitely not temporary fluke. Still happening the same.
Are the regexp loaded in a sorted order by id desc from the DB?

**Comment by iglocska** [comment]
It should be ID ASC by default, but I checked and it's not actually enforced. I've just tightened it, could you give it a shot?
