### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by tanakra** [MISP/MISP#1577]
Hello Iglocka and fellow MISP users,

I am using curl to POST to my MISP server in order to create a generic test event as follows:

curl -k -X POST -H "Authorization: ***" -H "Accept: application/xml" -d '<Event><date>2016-09-22</date><threat_level_id>1</threat_level_id><info>This is a test parser event.</info><published>1</published><analysis>1</analysis><distribution>1</distribution><Attribute><type>other</type><category>Artifacts dropped</category><to_ids>1</to_ids><distribution>1</distribution><comment>This is an Attribute</comment><value>Some_attribute</value></Attribute></Event>'-v https://XXX.XX.XX.XXX/events/

The error that I get is:

<?xml version="1.0" encoding="UTF-8"?>
<response>
  <name>**The request has been black-holed**</name>
  <message>The request has been black-holed</message>
  <url>/events/</url>
</response>

I read that this has something to do with a CSRF token. In this case, I am not sure how the CSRF token comes into play? Any ideas/suggestions?

Thank you in advance!

**Comment by iglocska** [comment]
It looks like you are missing a header, try to add 

`-H "Content-type: application/xml"`

**Comment by tanakra** [comment]
Hi Iglocska,

Thank you for the quick reply. Looks like I am able to connect, but I do not get a reply from the server and no event is created. Below is the verbose output of the curl command:

> POST /events HTTP/1.1
> Host: XXX.XX.XX.XXX
> User-Agent: curl/7.50.3
> Accept: _/_
> Authorization: ***
> Content-type: application/xml
> Content-Length: 387
> - upload completely sent off: 387 out of 387 bytes
> - STATE: DO => DO_DONE handle 0x80048558; line 1654 (connection #0)
> - STATE: DO_DONE => WAITPERFORM handle 0x80048558; line 1781 (connection #0)
> - STATE: WAITPERFORM => PERFORM handle 0x80048558; line 1791 (connection #0)
> - HTTP 1.1 or later with persistent connection, pipelining supported
>   < HTTP/1.1 302 Found
>   < Date: Wed, 28 Sep 2016 15:01:37 GMT
> - Server Apache/2.4.18 (Ubuntu) is not blacklisted
>   < Server: Apache/2.4.18 (Ubuntu)
>   < Location: https://XXX.XX.XX.XXX/users/login
>   < Content-Length: 0
>   < Content-Type: text/html; charset=UTF-8
>   <
> - STATE: PERFORM => DONE handle 0x80048558; line 1955 (connection #0)
> - multi_done
> - Curl_http_done: called premature == 0
> - Connection #0 to host XXX.XX.XX.XX left intact

Here is the entry in the **misp.local_access.log**

XXX.XX.X.XXX - - [28/Sep/2016:11:01:37 -0400] "POST /events HTTP/1/1" 302 2600 "-" "curl/7.50.3"

Thank you in advance!
