### ISSUE TITLE
Adding EventInfo attribute to event

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1579]
Is there any means to which we can add the EventInfo (Event Title) attribution to an existing event using the MISP API. Attempting to do so results in the following error message:

{"name":"Invalid attribute.","message":"Invalid attribute.","url":"\/attributes\/2309"}

I also tried: attributes/add/event_id

**Comment by RichieB2B** [comment]
The event title (info field) is actually part of the event properties and not an attribute. I'm not sure you can set it using the methods you describe.

**Comment by iglocska** [comment]
Indeed, event info is a field on the event object, you could edit the event itself if you wanted to edit the info field: 

POST to `/events/edit/event_id`

Body: `{"Event":{"info":"My new event info"}}`

(assuming your user has rights to edit the event)

**Comment by ghost** [comment]
Thank you.
