### ISSUE TITLE
STIX XML and JSON show inline on Safari 10

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1586]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | ubuntu |
| OS version (client) | macOS sierra |
| PHP version | 7.0 |
| MISP version / git hash | 2.4.51, 77a0efdc549f3a1f1d93adc71b4c2598f7124480 |
| Browser | Safari 10 |
### Expected behavior

STIX XML and JSON should be saved to disk
### Actual behavior

STIX XML and JSON are rendered by Safari and shown to the user
### Steps to reproduce the behavior

Open an event as select "Download as..." STIX XML or STIX JSON
### Logs, screenshots, configuration dump, ...

None

**Comment by adulau** [comment]
Is it still the case?

**Comment by RichieB2B** [comment]
Yes it is. I tested this again last Friday.

**Comment by adulau** [comment]
@rommelfs Could you test in your favourite OS and browser?

**Comment by iglocska** [comment]
:hankey: :hankey: :hankey:

**Comment by BenjaminJoly** [comment]
The problem should be fixed, so I close the issue. Do not hesitate to tell me if you want me to reopen it !
