### ISSUE TITLE
Authentication failed: missing API key?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1587]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Question |
| OS version (server) | Ubuntu |
| OS version (client) | Ubuntu |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.51 |
| Browser | Chrome |
### Expected behavior

Sync with remote MISP is failing for a few days...
### Actual behavior

Checking my log files, I saw this:

2016-09-30 13:26:26 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /jobs/getGenerateCorrelationProgress/8155
Stack Trace:
#0 /var/www/MISP/app/Controller/JobsController.php(16): AppController->beforeFilter()
#1 [internal function]: JobsController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
### Steps to reproduce the behavior

n/a
### Logs, screenshots, configuration dump, ...

n/a

**Comment by iglocska** [comment]
That error isn't related to the sync, could you git pull just in case? There was an issue with 2.4.51 that caused issues with the sync, but it has been resolved since.

**Comment by xme** [comment]
Tx! Updated my MISP from the repository. The sync starts but not all events are synced... Only one then it stops...

**Comment by iglocska** [comment]
hmm that is weird.
Could you check the error log right after it stops?

**Comment by xme** [comment]
And any idea the error message about the API. No idea what may trigger it.

**Comment by xme** [comment]
Nothing special in the logs...

**Comment by xme** [comment]
Ok, the only error found is:

[2016-09-30 14:00:03] main.ERROR: {"queue":"default","id":"cce70fcca102f573dc14b1b45c1c2f86","class":"ServerShell","args":[{"0":"enqueuePull","1":1475236800,"2":"1","3":"2","s_time":1475233202}]} failed: SQLSTATE[22001]: String data, right truncated: 1406 Data too long fo
r column 'description' at row 1 {"type":"fail","log":"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'description' at row 1","job_id":"cce70fcca102f573dc14b1b45c1c2f86","time":2808,"worker":"misp:680"} []

**Comment by iglocska** [comment]
OK that is new...

**Comment by iglocska** [comment]
Could you check two things for me? Via the command line, log into mysql and run the following:

describe logs;
describe organisations;

What I am interested in is the type of the "description" field in each (should be text).

**Comment by xme** [comment]
mysql> describe logs;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | NO   |     | NULL    |                |
| model       | varchar(20)  | NO   |     | NULL    |                |
| model_id    | int(11)      | NO   |     | NULL    |                |
| action      | varchar(20)  | NO   |     | NULL    |                |
| user_id     | int(11)      | NO   |     | NULL    |                |
| change      | text         | YES  |     | NULL    |                |
| email       | varchar(255) | NO   |     | NULL    |                |
| org         | varchar(255) | NO   |     | NULL    |                |
| description | varchar(255) | NO   |     | NULL    |                |
| ip          | varchar(45)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

mysql> describe organisations;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| name          | varchar(255) | NO   | MUL | NULL    |                |
| date_created  | datetime     | NO   |     | NULL    |                |
| date_modified | datetime     | NO   |     | NULL    |                |
| description   | text         | YES  |     | NULL    |                |
| type          | varchar(255) | YES  |     | NULL    |                |
| nationality   | varchar(255) | YES  |     | NULL    |                |
| sector        | varchar(255) | YES  |     | NULL    |                |
| created_by    | int(11)      | NO   |     | 0       |                |
| uuid          | varchar(40)  | YES  | MUL | NULL    |                |
| contacts      | text         | YES  |     | NULL    |                |
| local         | tinyint(1)   | NO   |     | 0       |                |
| landingpage   | text         | YES  |     | NULL    |                |
+---------------+--------------+------+-----+---------+----------------+

**Comment by iglocska** [comment]
| description | varchar(255) | NO | | NULL | | 

that should be text, no idea how that happened...

**Comment by xme** [comment]
I'll adapt the schema...

**Comment by iglocska** [comment]
Thanks, no clue how that happened. Let me know if it still fails!

**Comment by xme** [comment]
Schema adapted, seems better, events are coming in!
But I got another one:
[2016-09-30 16:13:44] main.ERROR: {"queue":"default","id":"4c92536ddbb49747b1617f4f25d2af1f","class":"ServerShell","args":[{"0":"enqueuePull","1":1475244000,"2":"1","3":"2","s_time":1475240404}]} failed: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'org_id' at row 1 {"type":"fail","log":"SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'org_id' at row 1","job_id":"4c92536ddbb49747b1617f4f25d2af1f","time":821817,"worker":"misp:680"} []

**Comment by iglocska** [comment]
Let's try something. Pushed another change, hopefully this helps.

**Comment by Rafiot** [comment]
Assuming it is fixed now, @xme please reopen if you still have it.
