### ISSUE TITLE
pagination on members list of organisations/view/<id> broken

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1598]
| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| MISP version / git hash | 2.4.51 |
### Expected behavior

When clicking on the next page of the members tab of the organisations/view/<id> page the next list is shown within the same view. (using ajax)
### Actual behavior

The whole new page is loaded to users/index/1/page:2. Resulting in a white stylesheet less page.

**Comment by adulau** [comment]
I can reproduce this on the HEAD at the following commit 3cc484dcaf1cfcc5a0b747f05d0f7fe4dd63a920
