### ISSUE TITLE
Does MISP integrate with any of the Information Sharing and Analysis Center (ISAC) groups

### ISSUE THREAD

**Issue by Xelsior** [MISP/MISP#1599]
Hi,

I'm new to MISP and I am just wondering if it can integrate and sync events from any of the Information Sharing and Analysis Center (ISAC) groups.

My understanding is that in order for MISP to automatically sync events from any of these groups they must either have a MISP instance of their own that they can allow us to connect to OR they must have open source feeds available that anyone can pull down? and if they have neither of these then our only other option is to manual create events and import the IOCs that will create attributes that we can associate with the event.

I am just looking for confirmation that I'm understanding this correctly and there isn't another option that would allow us to automatically pull events from any of these groups.

**Comment by adulau** [comment]
MISP is very flexible. You can import different feeds from existing MISP OSINT feed, external feed or even using the new flexible feature called freetext feed import.  We know some ISAC groups or trusted groups that are using MISP with private feeds in MISP format but also other formats for export and import.

**Comment by Danko90** [comment]
Hello @adulau ,
I'm interested in this topic and I would like to know if there is a taxi client that I can configure (setting username, password, certificate) in order to connect it to the taxi repository for pulling data from that and insert the data into MySQL DB, or do I should write a taxi client and integrate it on MISP?
Unfortunately I didn't find what I was looking for in the documentation.

Many Thanks,

Danilo

**Comment by Rafiot** [comment]
There is a connector for EclecticIQ's OpenTAXII implementation available there: https://github.com/MISP/MISP-Taxii-Server

**Comment by Danko90** [comment]
@Rafiot thanks a lot for replying.
As far as I understood MISP-Taxii-Server sets up a taxii server and a new database on the same machine of MISP and you can push stix files to it. I was looking for a taxii client which pull the data from a remote taxii server and push that data into MISP Database, without creating any other DB and/or taxii server. Is it possible to do this?
Thanks

**Comment by adulau** [comment]
MISP-Taxii-Server is supporting both and this is considered as an external module for MISP.

We will close this issue. If the issue persists, feel free to reopen the ticket.
