### ISSUE TITLE
Attributes not being conditionally populated based on category choice since 2.4.52 update

### ISSUE THREAD

**Issue by jdubp** [MISP/MISP#1603]
After updating to 2.4.52, when choosing an attribute category, the attribute choices are not being filtered based on category choice. Example: choosing Internal Reference category offers a list of ALL attributes instead of the filtered options in 2.4.51. 

If this is not being observed by others, any recommendations into troubleshooting is greatly appreciated.

_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question, Feature Request, support... |
| OS version (server) | Debian, ubuntu, CentOS, RedHat, ... |
| OS version (client) | XP, Seven, 10, Ubuntu, ... |
| PHP version | 5.4, 5.5, 5.6, 7.0, 7.1... |
| MISP version / git hash | 2.4.XX, hash of the commit |
| Browser | If applicable |

**Comment by iglocska** [comment]
Indeed, a change was missing for the new function handling this. Thanks for the heads-up!
