### ISSUE TITLE
Pull icon on list server when not activated

### ISSUE THREAD

**Issue by mariuskagc** [MISP/MISP#1608]
Hi there,
I recently saw a little bug in the server's list.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Debian |
| PHP version | >5.6 |
| MISP version / git hash | >2.4.30 |
| Browser | Chrome, Firefox, Internet Explorer |
### Actual behavior

When just pull sync is active, only pull icon shows up.
When just push sync is active, both icons show up on the list. Although trying to make pull gives a warning "Pull setting not enabled for this server", I think it should have the same behavior as pull sync.

I attach the screenshots:

![onlypull](https://cloud.githubusercontent.com/assets/8927685/19340330/ae281112-9128-11e6-9a3a-4abcd4b0362f.jpg)

![onlypush](https://cloud.githubusercontent.com/assets/8927685/19340331/ae2c8f94-9128-11e6-9978-76398d3a1284.jpg)

Thank you all in advance.

**Comment by iglocska** [comment]
Thanks for the heads-up, should be fixed now.

**Comment by mariuskagc** [comment]
Thanks!
