### ISSUE TITLE
Issue regarding importing events from csv

### ISSUE THREAD

**Issue by MxResearch** [MISP/MISP#1611]
Hi,
I am facing issue while importing csv file which contains events data. I am using phpmyadmin to import this csv file into events table. When I import the csv file getting error:
INSERT INTO  `events` (  `info` ,  `analysis` ,  `distribution` ,  `threat_level_id` ) 
VALUES (

'''info''',  '0',  '0',  '4'
)
MySQL said: Documentation
#1062 - Duplicate entry '' for key 'uuid'

what is the issue with uuid, the hole events table data is empty but still getting this error ? 

_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question, Feature Request, support... |
| OS version (server) | Debian, ubuntu, CentOS, RedHat, ... |
| OS version (client) | XP, Seven, 10, Ubuntu, ... |
| PHP version | 5.4, 5.5, 5.6, 7.0, 7.1... |
| MISP version / git hash | 2.4.XX, hash of the commit |
| Browser | If applicable |

**Comment by iglocska** [comment]
Each event has to have a uuid, this is something that is generated automatically by MISP. Generally you should never go directly through MySQL as you are bypassing a lot of the internal mechanisms of MISP and you will end up with a lot of corrupt / invalid data. 

I highly suggest going through the REST api / PyMISP instead.

(for the uuid error in particular, each value you enter using the method described above will create a null value uuid, the field however is unique, meaning the second entry will already cause a collision)

**Comment by MxResearch** [comment]
As per misp user guide uuid is :  In order to avoid collisions between events and attributes (during for example a sync) a Uuid is assigned that uniquely identifies each of them and  Unique identifier.:If you want to share organisation between MISP multi-instance, use the same Uuid. Apart from this Can you also tell me apart from this what else uuid is required for ?
So how can I import list of events in automated way misp using REST api or PyMisp ? rather than creating event individually or directly importing through csv file in mysql which is a wrong way. 
Note: I have read: https://github.com/MISP/PyMISP/tree/e70cc7a985b84605145cbe7a760304c86bcdef1b

**Comment by iglocska** [comment]
The org uuid is a slightly different matter, what is meant is that you
should reuse the same organisation uuid that you use when you ask for a new
account in a different misp community.

I am currently traveling and only have access to my phone, but I'll try to
whip up an example asap

On Oct 14, 2016 2:30 PM, "MxResearch" notifications@github.com wrote:

As per misp user guide uuid is : In order to avoid collisions between
events and attributes (during for example a sync) a Uuid is assigned that
uniquely identifies each of them and Unique identifier.:If you want to
share organisation between MISP multi-instance, use the same Uuid. Apart
from this Can you also tell me apart from this what else uuid is required
for ?
So how can I import list of events in automated way misp using REST api or
PyMisp ? rather than creating event individually or directly importing
through csv file in mysql which is a wrong way.
Note: I have read: https://github.com/MISP/PyMISP/tree/
e70cc7a985b84605145cbe7a760304c86bcdef1b

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/MISP/MISP/issues/1611#issuecomment-253786514, or mute
the thread

**Comment by MxResearch** [comment]
ok iglocska, thank you for your support.

**Comment by iglocska** [comment]
Example via PyMISP:

`from pymisp import PyMISP`
`misp = PyMISP('https://mymisp', 'my_auth_key', True, 'json')`
`misp.new_event(0, 4, 0, 'test')`

Alternatively, example via MISP's REST API: 

POST the following to https://mymisp/events:
`{"Event": {"info": "info", "analysis": "0", "distribution": "0", "threat_level_id":"4"}}`

using the following headers:
`Authorization: your_api_key`
`Content-type: application/json`
`Accept: application/json`

Let me know if you have any questions!

**Comment by MxResearch** [comment]
Hi

Yes these scripts are working and I am able to insert events through pymisp.Thank you for your response.

 I have one more query regarding pymisp that now by default we are able to pass 4 parameters which are: info,analysis,distribution,threat_level_id,date(by default today if none), now I want to add one more parameter in it so in order to add this new parameter I did changes in api.py file of pymisp:
_create_event(self, distribution, threat_level_id, analysis, info, new_parametername) and also added this newparameter argument in other sections of new event of api,py but when I run my script this newparameter value is not getting inserted in my misp database. I am able to see this newparameter value on my console where I run my script. how to map this newparameter to my json object 
Example:
The value is getting printed properly as you can see below but not getting inserted in misp db:
{'Event': {'info': u'New', 'new_parameter': u'value', 'analysis': 1, 'published': False, 'date': '2016-10-19', 'distribution': 0, 'threat_level_id': 1}}

So this new_parameter is not getting inserted into my misp database nor I am able to see here as you can see below:
{u'Event': {u'orgc_id': u'1', u'info': u'New', u'locked': False, u'uuid': u'580768bb-1c28-4e84-923d-099ec0a8011e', u'sharing_group_id': u'0', u'timestamp': u'1476880571', u'attribute_count': None, u'org_id': u'1', u'analysis': u'1', u'Attribute': [], u'ShadowAttribute': [], u'Orgc': {u'uuid': u'57bae90b-caa0-454f-88f3-0715c0a80114', u'id': u'1', u'name': u'namevalue'}, u'published': False, u'date': u'2016-10-19', u'Org': {u'uuid': u'57bae90b-caa0-454f-88f3-0715c0a80114', u'id': u'1', u'name': u'namevalue'}, u'distribution': u'0', u'RelatedEvent': [], u'proposal_email_lock': False, u'id': u'683', u'threat_level_id': u'1', u'publish_timestamp': u'0'}}

Can you guide me on how do I insert this value in my misp db ?
Note: I have also created a new column in mysql misp database .So that this newparameter value gets stored here.
Also this new parameter column I have not added on my misp web interface (http://mymisp/events/index) as I only want it to be stored in my misp db

**Comment by adulau** [comment]
Maybe you are on the wrong track. Modifying the underlying database schema is clearly sometime you are not recommended to do as you would need to update the overall logic behind MISP too. 

If I understand your use-case (based on your example above), you want to add additional meta-data to your event. The recommended approach is to use tagging or specific attributes (other/text).

**Comment by MxResearch** [comment]
Hi adulau,
To avoid duplicate entries for events I wanted to add this new extra field in events table which would be an unique constraint.
For example: 
1.  Scenario 1: Using pymisp I created multiple events with some attributes added to each one of them, If I try to recreate these events then this duplicacy should not happen i.e these insertion should get skipped notificing the events and its attributed already exists.
2. Scenario 2: As ID is primary key in misp database, so while importing meta data from suppose cuckoo sandbox and inserting it into attributes table for that particular ID gets difficult. How would I find the same event ID in misp and import meta data into its attribute whose analysis is done by cuckoo? 

So I was trying to add a column, for e.g. md5 making it as unique constraint and then searching particular event ID from this md5 field , additionaly this would also prevent entry for duplicate records in events table  as it is an unique constraint it will raise exception and add entry if record is not present.
Later I have set info column for events table as unique constraint.

**Comment by MxResearch** [comment]
Hi iglocska,

I am able to create events using pymisp now but not understanding how do I also create attributes for this event ? Also referred to examples which are present in pymisp.

Logic:
I need to get the event ID and update it .
I know how to update event attribute manually by its ID, if the event 1 already exists then:
event = misp.get(1)
misp.add_hashes(event, category="Payload delivery", md5='md5value')
misp.update(event)
But at the time of event creation how do i get that event ID and update it or any other logic you can suggest to get event ID and add its attributes.

**Comment by Delta-Sierra** [comment]
If I'm not mistaken, misp.new_event() returns the created event, so you don't need to use misp.get() if you add the attribute right after it. This way you don't need to know the id of the event, as shown below:

``` python
event = misp.new_event(distribution, threat_level_id, analysis, info)
misp.add_hashes(event, category="Payload delivery", md5='md5value')
```

But if you really need to get the id of the returned event, you get it in:  

``` python
event['Event']['id']`
```

Btw, as add_hashes() (and basically all functions used to add attributes) ends up calling misp.update() to add the attribute, you don't need to use it after.

Hope this explanation was not too confusing

**Comment by MxResearch** [comment]
Hi Delta-Sierra ,
Yes by using this method I am able to create both event as well as it attribute. But the md5 value should be mentioned in add_hashes function i.e. the value should be specified by me. I want to automate the process of event and attribute creation. So earlier I had written a python script to automatically create events:
from pymisp import PyMISP
from keys import misp_url, misp_key
import argparse
import os
import sqlite3
db = sqlite3.connect('/home/dbname.db')
cursor = db.cursor()
cursor.execute('SELECT md5 FROM malwaretable')
for row1 in cursor:
    dist= 0
    analys=1
    threat=1
    count=0
    try:
        input = raw_input
    except NameError:
        pass
    def init(url, key):
        return PyMISP(url, key, True, 'json', debug=True)
    misp = init(misp_url, misp_key)
    event = misp.new_event(dist,analys,threat,row1[count])
    count=count+1
    print(event)
This would create records for events. So by adding this misp.add_hashes(event, category="Payload delivery", md5='md5value') function in this script how can I pass runtime md5 value to md5 field of the function? , I cannot manually specify md5 value each time I create event .

**Comment by MxResearch** [comment]
Hi again,

I updated pymisp to new version v2.4.53 and made this changes to my code : 
misp.add_hashes(event, category="Payload delivery", md5=row1[count])
This worked now I am able to create event & its attribute.

Thank you for your support: @iglocska , @adulau , @Delta-Sierra
