### ISSUE TITLE
Attributes - rating and expiration date

### ISSUE THREAD

**Issue by certeu** [MISP/MISP#1612]
Two new fields are needed at attribute level

**Rating (or Scoring)**
Format: numeric value from 0 to 100
Use: value 100 means high quality (actionable) - value 0 means poor quality (non actionable). Intermediate values to be used as required by interested organisations

**Expiration date**
Format: date
Use: date when the attribute should stop being used for detecting threats

Note: we use already these two field in our internal tool (CTI platform), and we need to pass this data through MISP for our constituents
Thanks

**Comment by rotanid** [comment]
i think the rating/scoring could be achieved by the coming attribute tagging feature (#802), maybe in combination with the planned feature for variable elements in tags.
maybe it is also related to the attribute scoring project: https://github.com/MISP/MISP/projects/2

**Comment by iglocska** [comment]
Indeed, the plan is to use variable value attribute level tags for these
and as pointed out, we are working on a composite scoring system.

**Comment by certeu** [comment]
Hi,

Thank you for the info, this looks promising.

I think the key is to provide something flexible enough. Indeed different MISP (sub-) communities might have different approaches to scoring/rating and expiration date.

Krgds

Frédéric

**Comment by adulau** [comment]
For the scoring/rating, there are also some taxonomies of interest:

https://github.com/MISP/misp-taxonomies/blob/master/misp/machinetag.json#L31

Feedback is more than welcome

**Comment by certeu** [comment]
Hi Alexandre,

Thank you for the feedback.

The 'confidence-level' is close to what we need (by the way, is it implementable at attribute level?

However I have a clear preference for a true 'scoring/rating' field.

Indeed we are going to plug on this field a sophisticated mechanism made a several quality checks, so I really want to use a field which is 100% appropriate.

This scoring/rating field at attribute level is becoming very high priority for us.

So we would be very grateful if it could be implemented as soon as possible.

Do you have an estimate for this implementation?

Kind regards

Frédéric

**Comment by adulau** [comment]
FYI, the new [MISP 2.4.60](https://www.misp.software/2017/01/17/MISP.2.4.60.released.html) includes attribute level tagging. So you can apply any tags at attribute level. We hope this helps.

**Comment by adulau** [comment]
With the recent 2.4.66 release, expiration is now implemented in the sighting. Testing and feedback is welcome
