### ISSUE TITLE
Correlation Graph Requests

### ISSUE THREAD

**Issue by georgewerbacher** [MISP/MISP#1619]
I am requesting the ability to see the 'Event Info' instead of the 'Event_ID' within the correlation graph. 

I am using MISP a unique type of way to work with our intel process and having this feature will easily allow me to send these graphs to other members of the team and having the event ID does not provide the context that I need.

![screen shot 2016-10-19 at 2 11 06 pm](https://cloud.githubusercontent.com/assets/20704551/19531610/28b0e10c-9606-11e6-8db0-3a0fb3c9f93c.png)

**Comment by iglocska** [comment]
Just pushed a commit that changes this, I've currently gone with the first 32 characters of the event info, if you need the full event info let me know and I'll turn this into a toggle.
