### ISSUE TITLE
LDAP authentication using Apache2 authnz_ldap

### ISSUE THREAD

**Issue by frennkie** [MISP/MISP#1620]
I want to use Apache2 to authenticate my users against a LDAP server using the authnz_ldap module. This is my `misp.ssl.conf`:

```
<Location />
  AuthType Basic
  AuthBasicProvider ldap
  AuthLDAPBindDN "user"
  AuthLDAPBindPassword password
  AuthLDAPURL "ldaps://ldap.example.com:636/dc=example,dc=com?uid?sub?(objectClass=*)"
  AuthName "Please provide credentials to log in to MISP."
  Require valid-user
</Location>
```

In this setup Apache2 will forward the `REMOTE_USER` header to the MISP application. When I  put `REMOTE_USER` into CustomAuth -> Plugin.CustomAuth_header it does not seem to work as expected.

Any ideas?!
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question, Feature Request, support... |
| OS version (server) | Ubuntu 14.04 |
| OS version (client) | any |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.54 |
| Browser | any |

**Comment by frennkie** [comment]
Now working after commit https://github.com/MISP/MISP/commit/0695efe81b4763caed88cc3704a72ceb312f80bc Thanks!
How and where will documentation on this need to be added? I could easily create a screenshot (or two)...

**Comment by SHSauler** [comment]
Thanks for providing the plugin! Allow me two questions that arose during my tests and looking at the source:

- The user is only added according to the group membership at that specific time? If the membership changes, e.g. the user gets assigned another role in LDAP, this is not propagated to MISP?
-  If users gets deleted from the LDAP-role, they apparently still have access to MISP according to my tests. So far we plan to mitigate this by requiring a specific role in Apache first before allowing access to MISP at all.

**Comment by zeroq** [comment]
Did you also manage to have the API and sharing with other MISP instances still working with LDAP authentication enabled? I tried to set the Location in the Apache config to /users/login but that does not work.

**Comment by frennkie** [comment]
I enabled an additional VirtualHost for this... So the LDAP Authenticated Users go to https://misp and the API calls are made to https://misp:8443/ ..

**Comment by zeroq** [comment]
Ah thanks for workaround, that works!

**Comment by SHSauler** [comment]
Alternatively you can leverage `ApacheSecureAuth` in MISP Config. Then both certificate authentication and regular accounts work.

**Comment by RaulSokolova** [comment]
Can someone please elaborate a bit more or post the steps for the LDAP authentication ? I'm clearly missing an important step but I cannot get my head around which one is.

**Comment by trolldbois** [comment]
Go check #6189
