### ISSUE TITLE
We really need a way to create users via the API

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1621]
Another use-case popped up where user creation via the API would be crucial.
- The idea specifically here is to use the customauth plugin for LDAP authentication, but to create users in bulk via an external script based on LDAP lookups.

**Comment by frennkie** [comment]
+1
We would really like to see this implemented. 
We not only get the Username (uid) and email address from LDAP but also the S/MIME certificate for each MISP user.

**Comment by adulau** [comment]
Might also fix some parts from #1103

**Comment by adulau** [comment]
Fixed in 39ae6bce6d67c305c8549458b053a5d7b694c905 and [documented in misp-book](https://www.circl.lu/doc/misp/automation/#user-management)

PyMISP now supports the API too. Cf. https://github.com/MISP/PyMISP/commit/0b462404de246579992a37892161cd30107d65ef

**Comment by juju4** [comment]
So I did some testing here. works great!

Little bug for add_user.py: exit code is not matching what happened, especially if failed. always 0.

No option to provide a password with or without mandatory change at next login? eventually the gpg key.

Thanks a lot.
