### ISSUE TITLE
Support for OpenID Connect

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#1623]
It would be very useful if you could support OpenID Connect to use a centralized user management.

**Comment by adulau** [comment]
There is an option to use OpenID connect with MISP [with mod_auth_openidc](https://github.com/pingidentity/mod_auth_openidc). The approach is to pass  REMOTE_USER back to MISP via Plugin.CustomAuth_header.

https://github.com/MISP/misp-book/blob/master/appendices/README.md#appendix-a-external-authentication

In the recent 2.4.53 version, we also updated some aspect of the authentication.

https://github.com/MISP/MISP/commit/0695efe81b4763caed88cc3704a72ceb312f80bc

Let us know if this helps for your case.

**Comment by thomai** [comment]
@adulau Nice! Thanks for the hint. I'll try that.

**Comment by pettai** [comment]
this issue should be closed, the above suggestion (https://github.com/MISP/MISP/issues/1623#issuecomment-255542586) works well
