### ISSUE TITLE
max_allowed_packet error when updating warning lists

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1625]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | CentOS 6 |
| OS version (client) | Seven |
| PHP version | 5.6 |
| MISP version / git hash | 2.4.53 |
| Browser | Not applicable |
### Actual behavior

When updating the warning lists (for the first time) this error occurs:

```
2016-10-24 12:47:21 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /warninglists/update
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Warninglist.php(91): Mysql->insertMulti('warninglist_ent...', Array, Array)
#2 /var/www/MISP/app/Model/Warninglist.php(58): Warninglist->__updateList(Array, Array)
#3 /var/www/MISP/app/Controller/WarninglistsController.php(37): Warninglist->update()
#4 [internal function]: WarninglistsController->update()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(WarninglistsController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(WarninglistsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

The MySQL connection uses a socket (no TCP port 3306 listening). The max_allowed_packet is set to the default of 1048576:

```
mysql> show global variables like 'max_allowed_packet';
+--------------------+---------+
| Variable_name      | Value   |
+--------------------+---------+
| max_allowed_packet | 1048576 |
+--------------------+---------+
1 row in set (0.01 sec)
```

The solution is to increase this value in my.cnf:

```
max_allowed_packet=10485760
```

Should we document this somewhere?

**Comment by adulau** [comment]
Good point. A lot of users use TCP socket for MySQL instead of Unix socket. So I suppose that's why it's the first time we got the feedback (or they never updated the warning list ;-).

Maybe we should start a MySQL configuration README as a lot of orgs run the default settings from the distribution which is sometime very low compared to the available memory of a machine.

Especially innodb_buffer_pool_size, read_buffer_size, sort_buffer_size, read_rnd_buffer_size, key_buffer, max_allowed_packet and key_buffer.

**Comment by iglocska** [comment]
Yeah we seem to get more and more similar questions, this one I've never heard from anyone in particular yet, so definitely an interesting find!

**Comment by cristianbell** [comment]
I guess a sample mysql cnf, or just the values that are recommended to be changed would pb be a nice add to the INSTALL directory. 
I played around with different settings and got better results after talking to you, reading online and testing and re-testing. 
Pb the values just need to be general - x % of your available RAM or if u have x GB RAM, should use this value. 
I know @certeu had some performance issues but they fixed them by tweaking the settings files and changing to a different php implementation. Would really be great if they could share them with the community. We have just the extra settings for innodb_buffer_pool_size, read_buffer_size, key_buffer_size, sort_buffer_size and max_allowed_packet. 

Also setting the innodb_thread_concurrency, innodb_write_io_threads and innodb_read_io_threads and innodb_flush_log_at_trx_commit + innodb_doublewrite might be interesting (and improved performance in some tests) but all of them should not be necessary for versions > 5.7 afaik.

**Comment by rotanid** [comment]
be sure to not recommend settings that may impact consistency, like at least one of the parameters in @cristianbell s last paragraph could. (i don't know all of them, maybe it's not only one)

**Comment by cristianbell** [comment]
why not? 
the last two of the settings do impact consistency/the full ACID compliance, but they will improve speed. 
Those are just some recommendations and as long as each of them have a short description of what they do, the users can choose to implement them or not. 
Though as stated, all parameters from the last paragraph should not impact performance much on systems with version 5.7 or newer. 

The document can state the parameters listed by Alex+recommended settings, and after that the "more risky" parameters - to use if needed.

**Comment by iglocska** [comment]
Weird, looks like my message from yesterday didn't go through. Anyway:

We should never recommend anything that can hurt data integrity. Not even with caveats.

**Comment by iglocska** [comment]
We should never recommend anything that can hurt data integrity. Not even
with caveats.

**Comment by iglocska** [comment]
This should be resolved since then, a lot of refactoring has gone into removing massive queries and responses and instead chunking the data. If any new messages like this exist, please let us know!
