### ISSUE TITLE
Support/Usage of MISP

### ISSUE THREAD

**Issue by MiF0** [MISP/MISP#1627]
Hi all,
just started by installing MISP, Now i have some basic questions, for example I add and event, which could be an incident..

To this I allocate different kinds of "indicators", lets say MD5, Domains, IPs, etc. and maybe I even want to upload files etc. 

So I created the event
I added a MD5 hash for a file, what I would like to do is to add additional information to that file, for example attribution, where it was picked up etc. and/or any other circumstances or information that would be valuable to share, some of this info might be only for my org and some of it for all ... 

Thoughts around this?  

Please

Regards
Michael

**Comment by jaegeral** [comment]
Hi Michael,

you can add the different findings you have as different attribute types, like:

"Attrifacts dropped" ... and then add what you found and e.g. add the MD5 of the original file to the comment to have the "relation"
You can also of course add your analysis as plaintext as "Other - Text"
Attribution can be done using: "Attribution - Threat actor" etc.

Hope that helps.

A

**Comment by MiF0** [comment]
Hi A and thanks,
might help, just seems a bit backwards to me, maybe a new object/attribute should be created and then linked, but again how to do that? You wouldnt want to miss the possibility to actually search and/or correlate on either type of attribute, file location, attribution, hash etc. 
will do some more testing

Regards
Michael

**Comment by adulau** [comment]
MISP 2.4.80 added a complete object model and relationship. I would recommend to review the current features and let us know if this is covering your use-cases. I'll close the issue but feel free to reopen if you have any issues.
