### ISSUE TITLE
file attachments not readable anymore since commit

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1629]
| Type of issue             | Bug, Question, Feature Request, support...
| MISP version / git hash   |a52457ad85a65f54bec58bb31c81fd3446bef668
### Actual behavior

the link of the attachment is not visible, caused by the class="white" that was added in commit a52457ad85a65f54bec58bb31c81fd3446bef668

![image](https://cloud.githubusercontent.com/assets/1073662/19691690/5fde2a62-9ad5-11e6-8e71-d2e0b5a692b1.png)
### Steps to reproduce the behavior

update to commit, and add a file attachment.

**Comment by cristianbell** [comment]
fixed by 97512bd0923ef14729a4bb0e542b8f8d28fea08a
