### ISSUE TITLE
Warning lists not providing warnings in UI

### ISSUE THREAD

**Issue by jdubp** [MISP/MISP#1638]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

There may be an issue with warning lists functionality in the UI. If I am not understanding the usage correctly, please let me know. See the bug template below for details.

_If you would like to report a bug, please fill the template bellow_
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug, Question |
| OS version (server) | RedHat |
| OS version (client) | 7.2 |
| PHP version | 5.6.5 |
| MISP version / git hash | 2.4.53 |
| Browser | If applicable |
### Expected behavior

After enabling the "List of known google domains" and adding an attribute for domain "www.google.com" using the UI, i expect to see a warning thrown
### Actual behavior

The attribute of "www.google.com" is added to the event with no warning
### Steps to reproduce the behavior

1) Enable "List of known google domains" from List Warninglists
2) In an event add a new attribute of domain "www.google.com" (which is listed in the "List of known google domains" warning list

**Comment by iglocska** [comment]
Is the attribute marked as "to_ids"? Basically the warninglist only fires if it would be included in your IDS/HIDS/etc exports (which requires the flag to be set). 

An example of a valid use case: 

Malware checks internet connectivity by querying www.google.com - this is something that you might want to convey to other analysts using the system, but you wouldn't want to feed www.google.com to your IDS.

**Comment by jdubp** [comment]
That was it. I did not realize it only fired if the "to_ids" was set. Thank you for the clarification.

**Comment by iglocska** [comment]
No problem at all! I'll close the issue for now, feel free to open a new one if you run into any issues or have any questions.
