### ISSUE TITLE
Populate via Template as Link

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1639]
It would be handy to have alink on the left side on an event near to 

"
Edit Event
Delete Event
Add Attribute
Add Attachment
Populate via Freetext Import
Populate from OpenIOC
Populate from ThreatConnect
"

With 
"**Populate using Template**"

I got questions on a regular base from people looking for the template button.

**Comment by iglocska** [comment]
That sounds looks like an outdated MISP. On the newer ones all of those options starting with "Populate" are gone and instead you have a single "Populate from..." button that brings up a popup with all import options, including templates.

**Comment by jaegeral** [comment]
hm indeed, you are right
