### ISSUE TITLE
Display export file-size in Export Panel

### ISSUE THREAD

**Issue by Maijin** [MISP/MISP#1640]
In the Export panel, after generating the STIX or any other export it could be interesting to know the file size of the data generated:

![image](https://cloud.githubusercontent.com/assets/1408600/19889570/d045659e-a035-11e6-819b-233a5b4205ed.png)

**Comment by iglocska** [comment]
Nice, digging the idea, thanks!

**Comment by Maijin** [comment]
That was fast ;)

**Comment by adulau** [comment]
@iglocska be careful @Maijin might ask for a full radare2 API from/to MISP at some point ;-)

**Comment by iglocska** [comment]
No more feature creep! At least none for the rest of the day ;)
