### ISSUE TITLE
Add an option "without_email" in the "Sync Server" configuration

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#1643]
Hello all,

Could you tell me if it's possible to add an option "without_email" in the "Sync Servers" configuration page [1] to publish the events ("Push" and "Pull") without emails ?

[1]: Click on "Sync Actions", next "List Servers" and "Edit" button.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question, Feature Request
| OS version (server)       | Debian
| PHP version               | 5.4
| MISP version / git hash   | 2.4.53

### Expected behavior

Have an option to select if you want to automatically published with or without email of all the events "Pushed" and "Pulled" via the "Sync Servers".

### Actual behavior

All the events "Pushed" and "Pulled" via the "Sync Servers" are automatically published with email.

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
Good idea.

**Comment by cert-orangecyberdefense** [comment]
+1

I tried to sync a MISP instance with around 100k events and it basically crashed my email box :-)

**Comment by iglocska** [comment]
The tricky part will be of course that it won't control what will happen to those events on the next hop after. So maybe what we need is an automatically applied / automated tag on events (do not alert). 

Would that make more sense?

So my worry with the idea on having a sync level disabling of e-mails:

MISP A -> MISP B
MISP B doesn't send mail out if an event comes from MISP A
MISP B -> MISP C
MISP C sends out e-mail bomb of the beyond to all users

So instead what we could have, if MISP B would have the option to automatically tag anything coming from MISP A as "do not alert" and that tag could be propagated to MISP C.

**Comment by RichieB2B** [comment]
It depends if we view sending alert emails or not something that is determined by the MISP instance providing the event or the MISP instance receiving the event (and actually sending this e-mail). 

I think the latter makes most sense. The admin of MISP C knows best if an event coming from MISP B should trigger alert emails. If the admin of MISP B intends to flood MISP C with events she should alert the admin of MISP C beforehand. It should be a rare enough, hopefully.

**Comment by iglocska** [comment]
Good point!

**Comment by cert-orangecyberdefense** [comment]
We could also maybe add a true/false option in the settings to have one behavior by default and admin changing it if he wants?
"When synchronizing with a new instance, send notification emails with events" = false by default

**Comment by devnull-** [comment]
Hello all, 

I pushed a [quickly & unclean PR](https://github.com/MISP/MISP/pull/1809) to add 2 options in the Sync Server functionality [1]:

* UnpublishEvent: Unpublish new event (working with Pull event). Might be interesting to review the events before publishing them.
* PublishWithoutEmail: Publish new event without email (working with Push event).

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

[1]: Click on "Sync Actions", next "List Servers" and "Edit" button.
