### ISSUE TITLE
CSRF error, only one logon!

### ISSUE THREAD

**Issue by santi10** [MISP/MISP#1645]
Hi,

I have an issue with MISP. Misp is working but I can do only one access. If I try login from another device, MISP says me error, such us: You have tripped the cross-site request forgery protection of MISP. CSRF error: This happens usually...bla, bla, bla, etc.

the behavior is that Misp not permit two logons. I'me trying from another device I can't do logon only from the first device that I was logged

Do you help me, please? 

Thanks

**Comment by iglocska** [comment]
That shouldn't happen, MISP allows as many logons as you want. CSRF error on login usually happens if the login screen was loaded and it took too long for the form to be submitted (CSRF tokens expired).

Can you try to load up the login page from scratch and login?

**Comment by bambenek** [comment]
I am having a similiar issue... it's so bad that I can't even type in username and password to login without getting CSRF error several times in a row.

**Comment by iglocska** [comment]
@bambenek, this reminds me, we should have a debug session sometime soon! 

Very odd, something is definitely fishy there. Which MISP version are you on?

**Comment by bambenek** [comment]
Re: Debug, yeah was going to ask next week.

I just upgraded to latest version.  I changed the limits from 100 to 10000 here and it seemed to help (and seemed excessive)

app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php

Never mind, it didn't help... :(

**Comment by iglocska** [comment]
This is really weird, haven't come across the csrf issues yet that would prevent login except for when the sessions table became obscenely large (but this was prior to 2.4.40ish when we got a fix for garbage collection for the sessions).

Could you check the number of rows in your cake_sessions table just in case? 

As for next week, sure, let's set something up and solve those issues!

**Comment by bambenek** [comment]
Only 1 row, rebooted and not getting CSRF error but sessions deauthenticate after a few minutes now and API calls are taking really long.  Still have a login and the ssh key?

**Comment by iglocska** [comment]
I don't sadly, would love to have a look at it though if you could send it to me. http://pgp.circl.lu/pks/lookup?op=index&search=andras.iklody&fingerprint=on for my address / pgp key.

**Comment by enkidunolinux** [comment]
Hi @iglocska 

finally after installing MISP on RHEL7, im getting the same error, from different browsers:

'You have tripped the cross-site request forgery protection of MISP

CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed. 

Alternatively, click here to continue to the start page'
 

some error messages from the log file might help?
````
2017-09-03 01:54:03 Warning: Warning (2): Unknown: open(/var/opt/rh/rh-php56/lib/php/session/sess_fea6s6625sbirfhqske03liic5, O_RDWR) failed: Permission denied (13) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-03 01:54:03 Warning: Warning (2): Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/opt/rh/rh-php56/lib/php/session) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??
``` `

**Comment by iglocska** [comment]
That is interesting. So php cannot write/read sessions from file, which is really odd by itself. Nevertheless, we don't advise people to use file sessions anyway as they're slow as hell, could you edit your php.ini and add these?

```
session.save_handler = redis
session.save_path = 'tcp://localhost:6379'
```

**Comment by enkidunolinux** [comment]
@iglocska 

i have added the 2 lines ad the end of the file, but the same! happy to provide the while log trace?

```
2017-09-03 07:29:11 Error: [BadRequestException] csrf
Request URL: /users/login
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-09-03 07:29:11 Warning: Warning (2): Unknown: open(/var/opt/rh/rh-php56/lib/php/session/sess_5ncvhs1cfam8627lme18f1mbc3, O_RDWR) failed: Permission denied (13) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-03 07:29:11 Warning: Warning (2): Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/opt/rh/rh-php56/lib/php/session) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??
```

**Comment by iglocska** [comment]
Are you sure that was the correct php.ini that you've updated? It is still trying to save it to file.

**Comment by adulau** [comment]
I'll close the issue. Feel free to reopen if the issue persists.

**Comment by stansecurecom** [comment]
The issue still persists. CSRF error prevent's  me from login in.

It works fine one or two times after reboot and then I get this error every time, no matter which device/browser.

**Comment by iglocska** [comment]
In your sever settings, security tab, which session handler is currently configured?

**Comment by stansecurecom** [comment]
Please, reopen the issue

**Comment by iglocska** [comment]
Could you open a new issue? It might be something different than what prompted the opening of this issue, especially considering that it's a two year old one. Please include the details that I've asked for above.
