### ISSUE TITLE
Correlation graph for attribute(s)?

### ISSUE THREAD

**Issue by tanakra** [MISP/MISP#1646]
Hello Iglocka et al.,

Just a quick feature request. The ability to visualize event relationships through a Correlation Graph is very beneficial. I was wondering if the ability to visualize **attribute** relationships might be on the roadmap? That is, to be able to pick an attribute and see other related attributes would allow is to see trends in potential attacks, etc.

Thank you!

**Comment by iglocska** [comment]
If you view an event click view correlation graph in the left upper corner - is this what you had in mind? :)

**Comment by tanakra** [comment]
Indeed. But the graph correlates and visualizes one or more events. My organization would be really interested in visualizing particular attributes. For example, I would like to know who is targeting a specific user. So, if I can generate a Correlation Graph based on an e-mail address (or a location, or any other attribute), that would be very helpful. 
Under Event Actions->List Attributes, it would be great to click on a particular attribute Value and to generate a Correlation Graph. Is this realistic?

Thank you!

**Comment by iglocska** [comment]
Very interesting, indeed that would make sense. Let's keep this in mind, we
have a bunch of high prio tasks that come first but this could definitely
be cool.

**Comment by SteveClement** [comment]
@mokaddem is this one we can close?

**Comment by mokaddem** [comment]
For me we can close it.
As long as all the data is in the event, the `eventGraph` can be used for this task.
If we want to span multiple events, we have to implement something else.
What do you think @iglocska

**Comment by iglocska** [comment]
Let's close it then.
