### ISSUE TITLE
Added attachment returns in invalid URL when trying to download

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#1647]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | OSX
| PHP version               | 5.5
| MISP version / git hash   |  2.4.53

### Expected behavior
Adding an attachment via "Add Attachment" (Payload Delivery) to an event. Trying to download the attachment by clicking on the attachment link in the "value"-column of the event.

### Actual behavior
Some attachments (JPG) return the correct URL : X.be/attributes/download/300
Other (scr, pdf, pptx) return faulty URL (missing / between baseURL and attributes) : X.beattributes/download/299

### Logs, screenshots, configuration dump, ...
MISP.baseurl is set correctly.

**Comment by iglocska** [comment]
Thanks for the heads-up, should be fixed now!
