### ISSUE TITLE
Simple way to view all organisations on an instance + tab with infovis

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1648]
With #1013, the convenient list of seeing all orgs in one shot is gone. It would be nice for a user to see at a first glance who are the organisations on the instance.  Maybe it could be an opportunity to add some additional visualization tab like the tags used in MISP ;-)

Some experiments were performed by @Delta-Sierra https://github.com/MISP/PyMISP/tree/master/examples/situational-awareness - treemaps were not too bad.

**Comment by cristianbell** [comment]
good idea. 
side question, does this not cover #1557 as well? maybe we should put all info in one issue?
