### ISSUE TITLE
Pulling Event Information (Without Attributes)

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1649]
Is there way to export all events without their associated attributes?

I was attempting a .CSV export but alas, this doesn't appear to be possible:

https://.../events/csv/download/false/false/null/event_info/null/true/2016-11-02/2016-11-02/null/false

I want to pull statistics by day, so I can say... we've seen X family each day. I can do this by looking at the event_info field, but how would I export a file with this limited set of information?

Thank you for your assistance.

**Comment by iglocska** [comment]
Simply run a GET request (using the JSON headers) against:

`/events/index/searchDatefrom:2016-11-02`

Or alternatively just a GET request without the headers to:
`/events/index/searchDatefrom:2016-11-02.json`

You should get a JSON back with a list of all event metadata based on the filters.

However, keep in mind that just like the CSV export this uses the date field in the event. I've just pushed some changes so you can now also use the following:

`/events/index/searchtimestamp:1478179950.json`

`/events/index/searchpublishtimestamp:1478179950.json`

Let me know if this doesn't work for you!

**Comment by ghost** [comment]
Okay,

This item gives me some of what I want:
`/events/index/searchDatefrom:2016-11-02`

The documentation explains why:

> searchDatefrom:
> Filters on the date, anything newer than the given date in YYYY-MM-DD format is taken - non-negatable

I want just 2016-11-02, the above will give me 11-02 and 11-03. I also want it in exportable form... JSON, CSV, or XML. Is that possible?

Thanks again.

**Comment by iglocska** [comment]
For JSON just append .json at the end of the url and you'll get JSON instead of HTML :) 

As for limiting it further:

`/events/index/searchDatefrom:2016-11-02/searchDateuntil:2016-11-02.json`

should work fine.

**Comment by ghost** [comment]
OMG! That's awesome! Exactly what I needed!! Thank you.

**Comment by iglocska** [comment]
Excellent! B-)
