### ISSUE TITLE
Apache Error

### ISSUE THREAD

**Issue by Quietiger** [MISP/MISP#1650]
Hey Everyone, I am getting this error in Ubuntu 16.04 LTS for apache
Job for apache2.service failed. See "systemctl status apache2.service" and "journalctl -xe" for details.

after i do configuration changes for MISP
sudo cp /var/www/MISP/INSTALL/apache.misp.ssl /etc/apache2/sites-available/misp-ssl.conf

can anyone help me to fix it..,

Thank you

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by cristianbell** [comment]
and if you type in `systemctl status apache2.service` what do you see? or you can look to the apache logs - /var/log/apache2/, the error should be there.

**Comment by iglocska** [comment]
Did you change the settings in misp-ssl.conf after copying over the file from the INSTALL directory? It's only a template, you still need to set the virtualhost up for your own environment and create the SSL certificates yourself.

**Comment by Quietiger** [comment]
This is the error:
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since Thu 2016-11-03 14:28:43 EDT; 26s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 21194 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 21220 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]:  \* The apache2 configtest failed.
Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: Output of config test was:
Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: AH00526: Syntax error on line 13 of /etc/apache2/sites-enabled/misp-ss
Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: SSLCertificateFile: file '/etc/ssl/private/misp.local.crt' does not ex
Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: Action 'configtest' failed.
Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: The Apache error log may have more information.
Nov 03 14:28:43 mvsgroup-VirtualBox systemd[1]: apache2.service: Control process exited, code=exited status=1
Nov 03 14:28:43 mvsgroup-VirtualBox systemd[1]: Failed to start LSB: Apache2 web server.
Nov 03 14:28:43 mvsgroup-VirtualBox systemd[1]: apache2.service: Unit entered failed state.
Nov 03 14:28:43 mvsgroup-VirtualBox systemd[1]: apache2.service: Failed with result 'exit-code'.

**Comment by Quietiger** [comment]
Sorry everyone i am new to this and i want to learn this tool,
and now there is new one showing up, this is new i didnt got this earlier,

**sudo -u www-data php composer.phar install**
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [Composer\Downloader\TransportException]  
  Content-Length mismatch                   

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by Quietiger** [comment]
i am following this file **INSTALL.ubuntu1604.txt**

**Comment by iglocska** [comment]
No problem at all, let's see if we can get it sorted out!

For the certificate: It complains because you do not have the certificate files created.

`Nov 03 14:28:43 mvsgroup-VirtualBox apache2[21220]: SSLCertificateFile: file '/etc/ssl/private/misp.local.crt' does not ex`

What's the plan for the MISP that you are spinning up, just to experiment with it locally or is it meant to be deployed operationally? 

If it's the former, you could go with HTTP instead of HTTPS to ease the setup. However, if you want to deploy it operationally, make sure you use HTTPS.

For a free certificate from a recognised CA that works really well: https://letsencrypt.org

There are quite a few guides out there that describe how it works (such as https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04)

So once you have your certificates in place, you just have to point misp-ssl.conf towards them and set up the virtualhost correctly (for your FQDN). 

For the installation itself, if you already have MISP set up you won't need to run php composer.phar install again.

**Comment by Quietiger** [comment]
I am a student and i am doing it locally, i am using cuckoo for malware analysis and want to integrate MISP with cuckoo in a single virtual machine.

**Comment by cristianbell** [comment]
Then using [http](https://github.com/MISP/MISP/blob/2.4/INSTALL/apache.misp.ubuntu) or [https ](https://github.com/MISP/MISP/blob/2.4/INSTALL/apache.misp.ssl)with self-signed certificates should be ok. 
Is it working now?

**Comment by Quietiger** [comment]
Nope i am having problem with cake php after i did apt-get update and upgrade for ubuntu16.04

**Comment by cristianbell** [comment]
what is the error message?

**Comment by Quietiger** [comment]
sudo -u www-data php composer.phar install
Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)

[Composer\Downloader\TransportException]

**Content-Length mismatch**

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] []...

**Comment by Quietiger** [comment]
Hi,

I fixed the error regarding the Cakephp and ,

SSLCertificateFile /etc/ssl/private/misp.local.crt i changed the location to my certificate which i created using openssl

SSLCertificateKeyFile /etc/ssl/private/misp.local.key which is my private key i saved in my local folder

SSLCertificateChainFile /etc/ssl/private/misp-chain.crt-------i don't know about this....

can you guys give some advice...

i tried lets encrypt and it prompted that i cannot create certificate to local system (i used misp.local)

Thank you

**Comment by cristianbell** [comment]
good news! 

regarding the `SSLCertificateChainFile` - for a local test installation you can leave out the chain file. 
Just comment out the line with `#`. 
Also, since it is just a local installation, you could just not use SSL at all, and then you can just use the misp.conf file. 

Letsencrypt provides signed SSL certificates for domains you own. This means you go and buy a domain - quietiger.com for example - and then get a SSL certificate for it with letsencrypt. 

Note: Alternatively you could try using DynDns/No-IP managed DNS providers. But as far as I know creating certificates for such names is limited by letsencrypt and other similar companies.

**Comment by Quietiger** [comment]
This is what i did in my new installation to disable the certificate issue.. and reinstalled apache2 on my system:
<VirtualHost 192.168.1.1:443>
        ServerAdmin me@me.local
        ServerName misp.local
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

```
    #SSLEngine On
    #SSLCertificateFile /etc/ssl/private/misp.local.crt
    #SSLCertificateKeyFile /etc/ssl/private/misp.local.key
    #SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

    LogLevel warn
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
```

</VirtualHost>

and apache started without any error and when i started localhost... its just showing apache start page

and YES!!i have a domain quietiger.com which i am planning to use it for information sharing ...

**Comment by iglocska** [comment]
Just copy paste the following (and replace yourmail with your e-mail address)

```
<VirtualHost *:443>
        ServerAdmin yourmail@quietiger.com
        ServerName quietiger.com
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.local.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.local.key
        #SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
```

Make sure that you put your certificate file in /etc/ssl/private/misp.local.crt and your key in /etc/ssl/private/misp.local.key.

Either follow the guide on letsencrypt.org or follow the instructions described in here: https://github.com/MISP/MISP/issues/951 by @Watnegutten to get your certificate and key.

**Comment by Quietiger** [comment]
Thank you for the file... and this is new in browser:
**dispatch(new CakeRequest(),new CakeResponse(array('charset'=>Configure::read('App.encoding'))));**

**Comment by Quietiger** [comment]
apache is starting fine now

**Comment by Quietiger** [comment]
**Internal error in browser,

error log:**

2016-11-12 12:11:38 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:18:04 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:19:22 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:20:41 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:21:53 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:23:33 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2016-11-12 12:26:17 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1698] Access denied for user \'db login\'@\'localhost\'',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(83): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by iglocska** [comment]
Sounds like you've skipped a few steps in the installation instructions. Make sure you full out your database config file located in

'/var/www/MISP/app/Config/database.php' 

If you have already done this then make sure that MISP has access to the file.

**Comment by Quietiger** [comment]
Thank you there are no more error logs... but still one more message 

http://localhost/users/login

Not Found

The requested URL /users/login was not found on this server.
Apache/2.4.18 (Ubuntu) Server at localhost Port 80

I checked the configuration and permissions everything is as per the installation file.

Thank you for your support. i know you people have more important things to do.. but sorry i am too new to this and also to ubuntu.

**Comment by cristianbell** [comment]
which apache configuration file did you end up using? Because I thought you will use the https `<VirtualHost *:443>` and you should then try to access http**s**://localhost/users/login not http.. 
Also, it you are running Ubuntu in a vbox vm make sure you can access it from your host - bridged adapters, NAT/NAT+ port forwarding..

**Comment by Quietiger** [comment]
I didnt enabled the SSL for second installation and changed document root in apache conf file.

**Comment by CheYenBzh** [comment]
What do you write in the 'baseurl' item, in app/Config/config.php?

**Comment by Quietiger** [comment]
127.0.0.1

**Comment by cristianbell** [comment]
can you get to https://gitter.im/MISP/MISP and we can chat about this? It might be faster than here.

**Comment by Rafiot** [comment]
Should we consider it fixed?

**Comment by Rafiot** [comment]
yes.
