### ISSUE TITLE
GFI files import fails

### ISSUE THREAD

**Issue by cristianbell** [MISP/MISP#1654]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu, CentOS, RedHat
| OS version (client)       | XP, Seven, 10, Ubuntu
| PHP version               | 5.6, 7.0.8
| MISP version / git hash   | 2.4.54, e763e7646f7bbae5183ab93df840501d88c47119
| Browser                   | not applicable

After commit 468947307262a8750f6a17a269d34041f842ffed 

### Expected behavior
Create an email and attaching a GFI zip file should create the event and all attributes from the archive

### Actual behavior
Uploading a GFI file fails with error "An error has occured while attempting to zip the malware file". 

### Steps to reproduce the behavior
Create a new event and select a GFI file for upload.

### Error 
An error has occured while attempting to zip the malware file.
Error: An Internal Error Has Occurred.

Stack Trace

APP/Controller/EventsController.php line 2222 → Attribute->uploadAttachment(string, string, boolean, string, null, string, string, string, boolean)
APP/Controller/EventsController.php line 2043 → EventsController->_readGfiXML(string, string)
APP/Controller/EventsController.php line 1072 → EventsController->_addGfiZip(string)
[internal function] → EventsController->add()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(EventsController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by iglocska** [comment]
Not sure I follow:

"Create an email and attaching a GFI zip file should create the event and all attributes from the archive"

**Comment by cristianbell** [comment]
ah, sorry, "create an event" not e-mail damn auto-correct.

**Comment by iglocska** [comment]
Could you send me (encrypted via e-mail) a gfi archive to test? I don't have any to test the issue with anymore.
