### ISSUE TITLE
Question about API - Pulling of events

### ISSUE THREAD

**Issue by MichaelDwucet** [MISP/MISP#1659]
A question by one of our analysts:

Up to now I pulled new events from a MISP server via a URL of the form events/xml/download/false/false/false/false/false/800m
(by keeping a timestamp of the last time I pulled events from that server and providing the time-interval since then).

Prior to version 2.4.54 this worked fine.
Is there a change in the API? Or should I use a different API?

**Comment by iglocska** [comment]
I've just tried it on the latest commit and it seems to work fine, what's going wrong for you guys? Are you getting an error? If so, could you check your error log right after getting the error when querying that API? (it's located in /var/www/MISP/app/tmp/logs/error.log)

**Comment by MichaelDwucet** [comment]
I found several error messages that matched our tries
They all look the same:
`2016-11-10 08:03:00 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 253280256 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeResponse.php, line 541]
2016-11-10 08:03:00 Error: [InternalErrorException] Internal Server Error
Request URL: /events/xml/download/false/false/false/false/false/1141m
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 541)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 541, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4  {main}`

Looks like some memory exhaustion in cakephp. 
MISP runs on a virtual machine with 4GB Ram (nothing else on that machine), 1GB free. Yesterday that server started with an empty database and had pulled all events from connected MISPs, like the CIRCL one, over night. So today, the first pull via API might be too big.
I have to check with my admins, where we can change the limit.

**Comment by cristianbell** [comment]
You can change the limit in your php.ini look for `memory_limit = ...` line. You probably have 0.5G there. 

But you should also consider adding a little more RAM to the machine, 4Gb might be a little too little.

**Comment by iglocska** [comment]
Ah I see. The xml export probably hasn't gotten the memory tuning treatment yet, it's a deprecated API that hasn't gotten the newer fixes. 

4GB should be enough, I generally use 2-6GB on my dev VMs and I use a pulled CIRCL dataset too.

My dev VM (Ubuntu desktop, also running eclipse):

![vms](https://cloud.githubusercontent.com/assets/3668672/20179554/b1e0c454-a724-11e6-8579-d20445b1b106.PNG)

**Comment by iglocska** [comment]
Could you try this API instead?

https://mymisp/events/restSearch/download/false/false/false/false/false/false/false/false/800m

**Comment by MichaelDwucet** [comment]
After a reboot it worked. 
In addition we now have changed from using the XML API to the restSearchAPI. The restSearch API works without any problems so far. Thanks for your support

**Comment by iglocska** [comment]
Perfect, let me know if you run into any other issues!
