### ISSUE TITLE
can not edit OSINT feed in v2.4.54

### ISSUE THREAD

**Issue by 0x20c24** [MISP/MISP#1664]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | -
| PHP version               | -
| MISP version / git hash   | v2.4.54
| Browser                   | chrome

### Expected behavior
Edit feeds to enable them.

### Actual behavior
Can not modify feeds. Clicking on the save button results an error message.

### Steps to reproduce the behavior
Install a fresh v2.4.54 instance and try to modify the CIRCL or Botvrij.eu OSINT feeds.

### Logs, screenshots, configuration dump, ...
Unfortunately can't access them right now, but a workaround was to overwrite the app/Controller/FeedsController.php file with the v2.4.53 one:
https://raw.githubusercontent.com/MISP/MISP/2f39b4494c6d45e0d5e5abb1a53a2bfcf48fd606/app/Controller/FeedsController.php

**Comment by adulau** [comment]
Bug confirmed. Thank you for your report.
