### ISSUE TITLE
Add details for edits in View Event History

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#167]
Add previous and new values for edited attributes in the View Event History

**Comment by adulau** [comment]
`abcd@circl.lu  	edit  	Attribute  	Attribute (1051910) from Event (8295): Network activity/ip-dst 1.2.3.5  	2017-06-17 13:14:49`

to

`abcd@circl.lu  	edit  	Attribute  	Attribute (1051910) from Event (8295): Network activity/ip-dst 1.2.3.5  (previous value:1.2.3.4)	2017-06-17 13:14:49`

Like this?

**Comment by adulau** [comment]
I will close the issue as we didn't receive any feedback. Feel free to reopen. Thank you.
