### ISSUE TITLE
Default Feeds: Fetch the events not working

### ISSUE THREAD

**Issue by gossykid** [MISP/MISP#1671]
I have setup the two default feeds (circl and botvrij). I push the button the fetch the events - nothing happens.
In the logfile 
[root@mispserver logs]# tail -f resque-worker-error.log
#7 /u01/data/CEN/httpd24/html/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(48): MonologInit\MonologInit->__construct('RotatingFile', '/u01/data/CEN/h...')
#8 {main}
PHP Fatal error:  Can't use function return value in write context in /u01/data/CEN/httpd24/html/MISP/app/Model/Server.php on line 1343
PHP Fatal error:  Can't use function return value in write context in /u01/data/CEN/httpd24/html/MISP/app/Model/Server.php on line 1343

Any hint that points me in the right direction is higly appreciated.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug ?
| OS version (server)       | RedHat
| OS version (client)       | EL7
| PHP version               | 5.6.5
| MISP version / git hash   | 2.4.54
| Browser                   | IE11 & Firefox

**Comment by iglocska** [comment]
It sounds like you are using the incorrect version of PHP, make sure that you are using the scl supplied version instead of the default version that comes with RedHat. "Can't use function return value in write context" is an error thrown for example when trying to access array elements of a function's return value directly in PHP versions < 5.5.

**Comment by adulau** [comment]
I suppose this issue can be closed. If you feel that there is still an issue, feel free to reopen it.
