### ISSUE TITLE
Workers running but reported as "not running" in the GUI?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1672]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug?
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.5
| MISP version / git hash   | 2.4.54
| Browser                   | -

### Expected behavior
My workers are running but they are reported as "non running" in the GUI

### Actual behavior
All processes are running but not listed in the GUI. A "Restart all workers" works (they are restarted) but do not solve the problem.

### Steps to reproduce the behavior
Don't know what trigered the bug...

**Comment by xme** [comment]
So, while debugging here, I see that only 4 workers are started when I click on "restart all":

# ps ax|grep worker

  470 ?        S      0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='default'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14793082056044'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
  490 ?        S      0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='prio'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14793082059927'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
  510 ?        S      0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14793082063767'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
  530 ?        S      0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='email'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14793082067673'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
  557 ?        S+     0:00 grep --color=auto worker

**Comment by xme** [comment]
Any idea where to start to investigate this issue? I'm diving in the code but it's not clear how the app checks for workers' health...

**Comment by xme** [comment]
After 2 days, I found the issue! 
The redis.so module was not properly loaded in /etc/php5/cli/php.ini
It could be a good idea to increase the logging level to "see" this error somewhere?

/x

**Comment by iglocska** [comment]
Indeed, let's keep this issue open and have some way of diagnosing this!

**Comment by iglocska** [comment]
Added a check for it in the diagnostics, should help in the future if anyone runs into this issue.

**Comment by krypto29s** [comment]
What exactly did you do to fix this issue? I have the same problem. Starting the workers via cli reports all are good. The gui says all are down.

/cake CakeResque.CakeResque stop --all
Stopping workers
Stopping 5970 ... Done
Stopping 5934 ... Done
Stopping 5952 ... Done
Stopping 5988 ... Done
Stopping 7532 ... Done

Console]# ./cake CakeResque.CakeResque stop --all
Stopping workers
Stopping 17686 ... Done
Stopping 17735 ... Done
Stopping 17650 ... Done
Stopping 17757 ... Done
Stopping 17668 ... Done
Stopping 17788 ... Done
Stopping 17704 ... Done

Console]# ./cake CakeResque.CakeResque stop --all
Stopping workers
   There is no workers to stop ...
]$ sudo su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'
 
Stopping workers
Stopping 17867 ... Done
Stopping 17844 ... Done
Stopping 17911 ... Done
Stopping 17889 ... Done
Stopping 17933 ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
The scheduler worker is already running
