### ISSUE TITLE
Support for McAfee Data Exchange Layer (DXL)

### ISSUE THREAD

**Issue by martclau** [MISP/MISP#1673]
Feature request: implement integration with McAfee's Data Exchange Layer (DXL) application framework. This would make it more efficient to distribute and implement new IOCs.

http://www.mcafee.com/hk/solutions/data-exchange-layer.aspx
https://github.com/opendxl/

**Comment by adulau** [comment]
Looking at the DXL standard, it seems to be a kind of publishing fabrik. Can the current code used for the ZMQ pub-sub channel being reused for DXL too?

**Comment by mohlcyber** [comment]
We integrated MISP / IntelMQ with McAfee Data Exchange Layer (DXL) and build multiple use cases around Threat Intelligence Sharing across multiple DXL fabrics as well as the automated IOC import into MISP from the McAfee Advanced Threat Defense (ATD). Will publish information in re to the integration soon.

**Comment by mdtro** [comment]
@mohl1 Ah, this is awesome! I'd love to see that! We were starting on some early designs to get this exact integration done as well.

**Comment by adulau** [comment]
@mohl1 Let us know when it's published. We can add to the MISP project website or even do a blog post about it.

**Comment by martclau** [comment]
Great news - thanks for the update.

**Comment by adulau** [comment]
For more information: https://securingtomorrow.mcafee.com/business/optimize-operations/expanding-automated-threat-hunting-response-open-dxl/ 

I'll add the references in the MISP website. Feel free to add the MISP logo on the McAfee pages.
