### ISSUE TITLE
Updating comment of an attribute via API

### ISSUE THREAD

**Issue by cybermung** [MISP/MISP#1674]
### Expected behavior
Update/overwrite comment of an attribute via MISP/PyMISP API

### Actual behavior
Returns 405 (MethodNotAllowedException()) via AttributesController.php - editField() function

### Steps to reproduce the behavior
Using custom PyMISP function (att_id = {attribute id}):
```
    def update_attribute_comment(self, att_id, comment):
        session = self.__prepare_session()
        url = urljoin(self.root_url, 'attributes/editField/{}'.format(att_id))
        to_post = {'Attribute':{u'comment':comment}}
        response = session.post(url, data=json.dumps(to_post))
        return self._check_response(response)
```

or MISP API call:
`curl -i -H "Accept: application/xml" -H "content-type: text/xml" -H "Authorization: secret" --data "Testing" -X POST http://misp.com/attributes/editField/{attribute id}`

### Logs, screenshots, configuration dump, ...
```
Request URL: /attributes/editField/{attribute id}
Stack Trace:
#0 [internal function]: AttributesController->editField('{attribute id}')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

### Extra Notes
This could be a future enhancement request.  I can bypass this if I comment out the check on line 776 of app/Controller/AttributesController.php

```
        public function editField($id) {
                --->if ((!$this->request->is('post') && !$this->request->is('put')) || !$this->request->is('ajax')) throw new MethodNotAllowedException();
```

Curious as to why you placed a restriction here.

**Comment by iglocska** [comment]
editField was not really meant to be used via the API (/attributes/edit was), but I've made some changes and opened it up to it. Let me know if you run into any issues.

**Comment by cybermung** [comment]
Thanks!  I'll take a look at attributes/edit, I only saw the ability to change the comment by using Firebug and not seeing documentation on being to edit the comment of an attribute.  I'll re-read, but thanks for the fix regardless!

**Comment by iglocska** [comment]
No worries, it's a good point, no real reason not to allow it to be used via the API.
