### ISSUE TITLE
Immidiate push of event

### ISSUE THREAD

**Issue by donatasiv** [MISP/MISP#1675]
Hi,

We are dealing with sensitive fraud data which needs to be pushed to external MISP instance ass soon as it gets on system.  Is it possible to make a push of individual event immediately when it is created? Scheduled task is not the option in this case.

**Comment by iglocska** [comment]
How do you create the event? Using the API? If so, simply set the publish flag to 1 and it should automatically propagate it immediately after the creation is done.

**Comment by donatasiv** [comment]
Yes, event is created via API, but idea is not just PUBLISH event but to PUSH immidiate to external instance.

**Comment by iglocska** [comment]
Publishing involves a push, it should be pushed. If it's not then it sounds like a bug. 

So just to recap:

You create an event using /events/add with the published flag set and it doesn't propagate it automatically?

**Comment by donatasiv** [comment]
Yes, seems that everything is fine. 
Thanks!
