### ISSUE TITLE
After Fetching Feed Failed, job is stuck in Queued state

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#1676]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu 14.04
| OS version (client)       | macOS Sierra
| PHP version               | PHP 7.0.13-1+deb.sury.org~trusty+1 (cli) ( NTS )
| MISP version / git hash   | 2.4.54, ccde617c9709c3c6b5422c4471d7daa9b44388f8
| Browser                   | n/a

### Steps to reproduce

1. Download latest MISP VM
2. Fetch CIRCL feed (and make sure it fails ;)
3. Update to latest 2.4 version of MISP (2.4.54)
4. Log back in and fetch feed again

And with a bit of luck you will see it stuch like this:

From - http://192.168.56.50/jobs/index

142 	2016-11-17 15:38:42 	2016-11-17 15:38:42 	5c8d4fa7b036440b5d3f40950f43c736 	default 	fetch_feed 	Feed: 1 	Fetching event manifest. 	SYSTEM 	Failed	0 	
Queued

**Comment by adulau** [comment]
I suppose the bug has been fixed. If the issue persists, feel free to reopen this issue.
