### ISSUE TITLE
Can not access misp-modules from training MISP VM

### ISSUE THREAD

**Issue by rgraf** [MISP/MISP#1678]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu 
| OS version (client)       | Windows 7
| MISP version / git hash   | september training VM
| Browser                   | Firefox

### Expected behavior

Get misp-modules view 

### Actual behavior

Error related to port 6666

### Steps to reproduce the behavior

Install VM, start MISP server, call main MISP instance, call MISP-moduels URL

### Logs, screenshots, configuration dump, ...

I've prepared a new MISP module and would like to see - how MISP modules work in MISP in general, before I submit my module.

I've installed MISP via VM (https://circl.lu/services/misp-training-materials/) from september training. It works fine. When I go to the service settings page - I see that Enrichment_services_url and port are enabled for: http://127.0.0.1:6666/modules.

But if I call http://127.0.0.1:6666 URL - I get error message that connection to this port is not possible. I believe misp-modules are running in VM. If I try to start them by the command: python3 misp-modules (in VM) - I get message that port is already in use. And I see it in processes.

Port 6666 is enabled for my PC and also in Firefox I've added it to the setting:

network.security.ports.banned.override

I found description about MISP modules binding to the core MISP program: https://circl.lu/assets/files/misp-training/3.1-MISP-modules.pdf 

It is not clear - how should I come to the view from  page 7.

Could you please give me a hint - how to use MISP-modules from core MISP? Apparently I miss some information.

Thank you in advance,

Best regards,

Roman

**Comment by iglocska** [comment]
Sorry for the very late response, there was an issue with an earlier version of the VM, should work fine with the latest. Apologies again.
