### ISSUE TITLE
Setup Issue's

### ISSUE THREAD

**Issue by v0idif** [MISP/MISP#1679]
Hello Everyone,

I been trying to setup the MISP on my server Ubuntu 16.04 but different issues appear every time. Does anyone manage to make a fresh installation that can help me out ? If yes it will be really appreciated if you can help me out on this :) ( Since there are a variety of issues i didnt post anything related).

Regards,

Thanks

**Comment by iglocska** [comment]
Sure, what's the issue?

**Comment by v0idif** [comment]
Hello iglocska

Replied via email. (Gmail)

Thanks,

Regards

**Comment by v0idif** [comment]
At the end of each command i am describing  if i "DONE it or NOT DONE" . Incase i haven't done it you will see a long writting with the issue . There are some steps i didn't perform because i didnt know how to move on .Any help will be appreciated thanks. 

INSTALLATION INSTRUCTIONS
------------------------- for Ubuntu 16.04-server

1/ Minimal Ubuntu install
-------------------------

# Install a minimal Ubuntu 16.04-server system with the software:
- OpenSSH server

# Make sure your system is up2date:
sudo apt-get update - DONE
sudo apt-get upgrade - DONE

# install postfix, there will be some questions.
sudo apt-get install postfix - DONE
# Postfix Configuration: Satellite system
# change the relay server later with:
sudo postconf -e 'relayhost = example.com' - DONE /*(However on this one i left it example.com since i dont want to deliver mail from my droplet directly or relay through another provider) /* - 
sudo postfix reload - DONE


2/ Install LAMP & dependencies
------------------------------
Once the system is installed you can perform the following steps:

# Install the dependencies: (some might already be installed)
sudo apt-get install curl gcc git gnupg-agent make python openssl redis-server sudo vim zip - DONE

# Install MariaDB (a MySQL fork/alternative)
sudo apt-get install mariadb-client mariadb-server - DONE

# Secure the MariaDB installation (especially by setting a strong root password)
sudo mysql_secure_installation - DONE --> Database [Password: BNBiUjlksd78998*] - Anonymous Users Removed - Removed Test DB that anyone can access


# Install Apache2
sudo apt-get install apache2 apache2-doc apache2-utils - DONE

# Enable modules, settings, and default of SSL in Apache
sudo a2dismod status - DONE DISABLED
sudo a2enmod ssl - DONE ENABLED
sudo a2enmod rewrite -DONE ENABLED
sudo a2dissite 000-default - DONE DISABLED
sudo a2ensite default-ssl - DONE

# Install PHP and dependencies
sudo apt-get install libapache2-mod-php php php-cli php-crypt-gpg php-dev php-json php-mysql php-opcache php-readline php-redis - DONE

# Apply all changes
sudo systemctl restart apache2 - DONE


3/ MISP code
------------
# Download MISP using git in the /var/www/ directory.
sudo mkdir /var/www/MISP - DONE DIRECTORY CREATED

sudo chown www-data:www-data /var/www/MISP - NOT DONE - ( I haven't apply this change with the permissions because i had issues at later stage so i left the permissions as it is)

cd /var/www/MISP - DONE

sudo -u www-data git clone https://github.com/MISP/MISP.git /var/www/MISP - DONE ( Without sudo -u www-data)

sudo -u www-data git checkout tags/$(git describe --tags `git rev-list --tags --max-count=1`) - DONE ( Without sudo -u www-data) - Tag Created :  checking out 'tags/v2.4.54'.

# if the last shortcut doesn't work, specify the latest version manually
# example: git checkout tags/v2.4.XY
# the message regarding a "detached HEAD state" is expected behaviour
# (you only have to create a new branch, if you want to change stuff and do a pull request for example)

# Make git ignore filesystem permission differences
sudo -u www-data git config core.filemode false - DONE (Without sudo -u www-data)

# install Mitre's STIX and its dependencies by running the following commands

sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev python-setuptools - DONE

cd /var/www/MISP/app/files/scripts - DONE

sudo -u www-data git clone https://github.com/CybOXProject/python-cybox.git DONE - ( Without sudo -u www-data)

sudo -u www-data git clone https://github.com/STIXProject/python-stix.git DONE -( Without sudo -u www-data)

cd /var/www/MISP/app/files/scripts/python-cybox - DONE

sudo -u www-data git checkout v2.1.0.12 - DONE ( Without sudo -u www-data)

sudo python setup.py install - DONE - ( Finished processing dependencies for cybox==2.1.0.12)

cd /var/www/MISP/app/files/scripts/python-stix - DONE

sudo -u www-data git checkout v1.1.1.4 DONE - WITHOUT ( sudo -u www-data)

sudo python setup.py install - DONE -(Finished processing dependencies for stix==1.1.1.4)


4/ CakePHP
-----------
# CakePHP is included as a submodule of MISP, execute the following commands to let git fetch it:
cd /var/www/MISP - DONE
sudo -u www-data git submodule init - DONE
sudo -u www-data git submodule update - DONE

# Once done, install CakeResque along with its dependencies if you intend to use the built in background jobs:
cd /var/www/MISP/app
sudo -u www-data wget https://getcomposer.org/download/1.2.1/composer.phar -O composer.phar - DONE (Without sudo -u www-data)
sudo -u www-data php composer.phar require kamisama/cake-resque:4.1.2 - DONE (Without sudo -u www-data)
sudo -u www-data php composer.phar config vendor-dir Vendor - DONE (Without sudo -u www-data)
sudo -u www-data php composer.phar install - - DONE (Without sudo -u www-data)

# Enable CakeResque with php-redis
sudo phpenmod redis - DONE

# To use the scheduler worker for scheduled tasks, do the following:
sudo -u www-data cp -fa /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php - - DONE (Without sudo -u www-data)


5/ Set the permissions ( I haven't set any permissions since through the installation i haven't set any permissions for www-data) - iwasnt sure here if this gonna have any conflict
----------------------

# Check if the permissions are set correctly using the following commands:
sudo chown -R www-data:www-data /var/www/MISP
sudo chmod -R 750 /var/www/MISP
sudo chmod -R g+ws /var/www/MISP/app/tmp
sudo chmod -R g+ws /var/www/MISP/app/files
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp


6/ Create a database and user
-----------------------------
# Enter the mysql shell
sudo mysql -u root -p - DONE

MariaDB [(none)]> create database misp; - DONE
MariaDB [(none)]> grant usage on *.* to misp@localhost identified by 'XXXXdbpasswordhereXXXXX'; - DONE - grant usage on *.* to misp@localhost identified by 'BNBiUjlksd78998*(';
MariaDB [(none)]> grant all privileges on misp.* to misp@localhost; - DONE
MariaDB [(none)]> flush privileges; - DONE
MariaDB [(none)]> exit - DONE

# Import the empty MISP database from MYSQL.sql
sudo -u www-data sh -c "mysql -u misp -p misp < /var/www/MISP/INSTALL/MYSQL.sql" - DONE ( Without sudo -u www-data)
# enter the password you set previously


7/ Apache configuration
-----------------------
# Now configure your Apache webserver with the DocumentRoot /var/www/MISP/app/webroot/

sudo cp /var/www/MISP/INSTALL/apache.misp.ssl /etc/apache2/sites-available/misp-ssl.conf - DONE

# Be aware that the configuration files for apache 2.4 and up have changed.
# The configuration file has to have the .conf extension in the sites-available directory
# For more information, visit http://httpd.apache.org/docs/2.4/upgrading.html

# If a valid SSL certificate is not already created for the server, create a self-signed certificate: - DONE - (Certificated Created - writing new private key to '/etc/ssl/private/misp.local.key')
sudo openssl req -newkey rsa:4096 -days 365 -nodes -x509 \
-subj "/C=CY/ST=NICOSIA/L=NICOSIA/O=mispdel/OU=MLDL/CN=MISP/emailAddress=admin@v0idif.com" \
-keyout /etc/ssl/private/misp.local.key -out /etc/ssl/private/misp.local.crt

# Otherwise, copy the SSLCertificateFile, SSLCertificateKeyFile, and SSLCertificateChainFile to /etc/ssl/private/. (Modify path and config to fit your environment) CHECK: ? ( i didnt perform this since i created the certificates)

============================================= Begin sample working SSL config for MISP
<VirtualHost <IP, FQDN, or *>:80>
        ServerName <your.FQDN.here>

        Redirect permanent / https://<your.FQDN.here>

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>

<VirtualHost <IP, FQDN, or *>:443>
        ServerAdmin admin@<your.FQDN.here>
        ServerName <your.FQDN.here>
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.local.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.local.key
#        SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
============================================= End sample working SSL config for MISP

# activate new vhost
sudo a2dissite default-ssl - DONE DISABLED
sudo a2ensite misp-ssl - DONE Enabled - ( However when i try to reload apache to apply the changes i got this error: Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.


# Restart apache
sudo systemctl restart apache2 ( NOT DONE - Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.)

Log File : 

Nov 20 08:52:34 MISP apache2[15468]:  * The apache2 configtest failed.
Nov 20 08:52:34 MISP apache2[15468]: Output of config test was:
Nov 20 08:52:34 MISP apache2[15468]: AH00526: Syntax error on line 15 of /etc/apache2/sites-enabled/misp-ssl.conf: --> should we remove SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

Nov 20 08:52:34 MISP apache2[15468]: SSLCertificateChainFile: file '/etc/ssl/private/misp-chain.crt' does not exist or is empty --> this file doesnt exist , dont know why i thought to remove this file line from misp-ssl.conf
Nov 20 08:52:34 MISP apache2[15468]: Action 'configtest' failed.
Nov 20 08:52:34 MISP apache2[15468]: The Apache error log may have more information.
Nov 20 08:52:34 MISP systemd[1]: apache2.service: Control process exited, code=exited status=1
Nov 20 08:52:34 MISP systemd[1]: Failed to start LSB: Apache2 web server.
Nov 20 08:52:34 MISP systemd[1]: apache2.service: Unit entered failed state.
Nov 20 08:52:34 MISP systemd[1]: apache2.service: Failed with result 'exit-code'.


8/ MISP configuration
---------------------
# There are 4 sample configuration files in /var/www/MISP/app/Config that need to be copied
sudo -u www-data cp -a /var/www/MISP/app/Config/bootstrap.default.php /var/www/MISP/app/Config/bootstrap.php - DONE ( Without sudo -u www-data)

sudo -u www-data cp -a /var/www/MISP/app/Config/database.default.php /var/www/MISP/app/Config/database.php - DONE ( Without sudo -u www-data)

sudo -u www-data cp -a /var/www/MISP/app/Config/core.default.php /var/www/MISP/app/Config/core.php - DONE ( Without sudo -u www-data)

sudo -u www-data cp -a /var/www/MISP/app/Config/config.default.php /var/www/MISP/app/Config/config.php - DONE ( Without sudo -u www-data)

# Configure the fields in the newly created files:
sudo -u www-data vim /var/www/MISP/app/Config/database.php - DONE - You can confirm your self if i left something behind
# login, port, password, database

# Important! Change the salt key in /var/www/MISP/app/Config/config.php - (I DIDNT APPLY THIS CHANGE HERE I WASNT SURE )
# The salt key must be a string at least 32 bytes long.
# The admin user account will be generated on the first login, make sure that the salt is changed before you create that user
# If you forget to do this step, and you are still dealing with a fresh installation, just alter the salt,
# delete the user from mysql and log in again using the default admin credentials (admin@admin.test / admin)

# Change base url in config.php (I DIDNT APPLY THIS CHANGE HERE I WASNT SURE )
sudo -u www-data vim /var/www/MISP/app/Config/config.php
# example: 'baseurl' => 'https://<your.FQDN.here>',
# alternatively, you can leave this field empty if you would like to use relative pathing in MISP
# 'baseurl' => '',

# and make sure the file permissions are still OK - (I DIDNT PERFORM THIS STEP HERE)
sudo chown -R www-data:www-data /var/www/MISP/app/Config
sudo chmod -R 750 /var/www/MISP/app/Config

# Generate a GPG encryption key.
sudo -u www-data mkdir /var/www/MISP/.gnupg (I DIDNT PERFORM THIS STEP HERE)
sudo chmod 700 /var/www/MISP/.gnupg (I DIDNT PERFORM THIS STEP HERE)
sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --gen-key (I DIDNT PERFORM THIS STEP HERE)
# The email address should match the one set in the config.php / set in the configuration menu in the administration menu configuration file

# And export the public key to the webroot (I DIDNT PERFORM THIS STEP HERE)
sudo -u www-data sh -c "gpg --homedir /var/www/MISP/.gnupg --export --armor YOUR-KEYS-EMAIL-HERE > /var/www/MISP/app/webroot/gpg.asc"

# To make the background workers start on boot (I DIDNT PERFORM THIS STEP HERE)
sudo chmod +x /var/www/MISP/app/Console/worker/start.sh
sudo vim /etc/rc.local
# Add the following line before the last line (exit 0). Make sure that you replace www-data with your apache user:
sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh

# Now log in using the webinterface:
# The default user/pass = admin@admin.test/admin

# Using the server settings tool in the admin interface (Administration -> Server Settings), set MISP up to your preference
# It is especially vital that no critical issues remain!
# start the workers by navigating to the workers tab and clicking restart all workers

# Don't forget to change the email, password and authentication key after installation.

# Once done, have a look at the diagnostics

# If any of the directories that MISP uses to store files is not writeable to the apache user, change the permissions
# you can do this by running the following commands:

sudo chmod -R 750 /var/www/MISP/<directory path with an indicated issue>
sudo chown -R www-data:www-data /var/www/MISP/<directory path with an indicated issue>

# Make sure that the STIX libraries and GnuPG work as intended, if not, refer to INSTALL.txt's paragraphs dealing with these two items

# If anything goes wrong, make sure that you check MISP's logs for errors:
# /var/www/MISP/app/tmp/logs/error.log
# /var/www/MISP/app/tmp/logs/resque-worker-error.log
# /var/www/MISP/app/tmp/logs/resque-scheduler-error.log
# /var/www/MISP/app/tmp/logs/resque-2015-01-01.log // where the actual date is the current date


Recommended actions
-------------------
- By default CakePHP exposes its name and version in email headers. Apply a patch to remove this behavior.

- You should really harden your OS
- You should really harden the configuration of Apache
- You should really harden the configuration of MySQL/MariaDB
- Keep your software up2date (OS, MISP, CakePHP and everything else)
- Log and audit


Optional features
-------------------
# MISP has a new pub/sub feature, using ZeroMQ. To enable it, simply run the following command
sudo pip install pyzmq
# ZeroMQ depends on the Python client for Redis
sudo pip install redis

**Comment by iglocska** [comment]
Hello there,

sorry for the late response, trying to figure out what's going on there.

Nov 20 08:52:34 MISP apache2[15468]: AH00526: Syntax error on line 15 of
/etc/apache2/sites-enabled/misp-ssl.conf: --> should we remove
SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

Nov 20 08:52:34 MISP apache2[15468]: SSLCertificateChainFile: file
'/etc/ssl/private/misp-chain.crt' does not exist or is empty --> this file
doesnt exist , dont know why i thought to remove this file line from
misp-ssl.conf

This looks like apache2 couldn't start up correctly, indeed, if you don't
use a full chain with intermediaries you can comment out that line. Does
that fix the issue?

Best regards,

Andras

**Comment by v0idif** [comment]
Hello Andras,

Well it fix the part with SSL , rest issues still there unfortunately couldn't find any solution.

Let me know how we can proceed :)

Thanks,

Regards,

**Comment by adulau** [comment]
I will close the issue as I suppose this installation issue has been fixed. If this is not case, feel free to reopen the issue. Thank you.

**Comment by shehreyarahmedkohati** [comment]
Can anyone state the solution? I have the same issue
