### ISSUE TITLE
Scheduled push fails

### ISSUE THREAD

**Issue by donatasiv** [MISP/MISP#1680]
Local version: 2.4.54
Remote version: 2.4.48
Status: Remote outdated, notify admin!
Compatiblity: Compatible

I can browse remote instance from local, also PULL local<remote works fine, but PUSH local>remote not work and job keeps in Queued condition. 
log: 	Warning: Sync to Server ('3') initiated, but the remote instance is a few hotfixes behind. 

Is that problem with version compatibility?

**Comment by iglocska** [comment]
That is weird, it should work. You will get a warning entry in the logs, but that's purely informational - 2.4.x should be compatible with 2.4.x regardless.

**Comment by donatasiv** [comment]
Log from MISP:
[2016-11-21 08:41:00] main.INFO: Processing ID:544939a0bda79d4c1fdc35fb1a06efc7 in default {"type":"process","worker":"cc2bb91d676a:1129","job_id":"544939a0bda79d4c1fdc35fb1a06efc7"} []
[2016-11-21 08:41:01] main.ERROR: {"queue":"default","id":"544939a0bda79d4c1fdc35fb1a06efc7","class":"ServerShell","args":[["push","3","full","5956","1"]]} failed: Unable to perform enableCrypto operation on CakeSocket {"type":"fail","log":"Unable to perform enableCrypto operation on CakeSocket","job_id":"544939a0bda79d4c1fdc35fb1a06efc7","time":386,"worker":"cc2bb91d676a:1129"} []

**Comment by donatasiv** [comment]
From tcpdump seems that it is proxy problem. But I don`t have proxy settings on MISP at all.
    <LI id=L_dt_3>Error Code: 502 Proxy Error. The host was not found.(11001)\r\n

**Comment by iglocska** [comment]
Woah, ok that is weird. If you check your server settings -> proxy settings, what do you see?

**Comment by donatasiv** [comment]
All green, because there are no values set. I used proxy earlier for other configuration, but now I removed it. Seems that these proxy settings is cashed somewhere, because from .pcap I see call to proxy server with all credentials.
Hypertext Transfer Protocol
    CONNECT misp.xxxxxx.com:443 HTTP/1.1\r\n
    Host: xxx.xxxx.net\r\n
    User-Agent: php proxy\r\n
    Proxy-Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n
        Credentials: xxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxx
    \r\n
    [Full request URI: misp.xxxxx.com:443]
    [HTTP request 1/1]
    [Response in frame: 49]

**Comment by iglocska** [comment]
Hmm that is weird, it shouldn't be cached.

**Comment by donatasiv** [comment]
Can`t explain roots, but jsut restarted apache server and workers, no issues with push anymore.
Can be closed.

**Comment by iglocska** [comment]
Very odd, let us know if it pops-up again!
