### ISSUE TITLE
Synchronization between 2.3 and 2.4

### ISSUE THREAD

**Issue by ost89** [MISP/MISP#1681]
#feature request
Dear,

In the version 2.3 there were no Organisation and no Organization ID fields. If you do the manual export from 2.3 and import in 2.4 it  does not work, because there is not Organization ID field in the export.
Is it possible to add the Organisation ID automatically, based on the user (Organization) that is doing the import? 

Kind regards,
Anna

**Comment by iglocska** [comment]
It should still work and create an organisation based on the string (without a UUID, that needs to be added by an admin) - though I haven't tested this feature in a long time, haven't heard of any 2.3 instances still being out there in over 6 months.

If you import a 2.3 event, does it fail for you?
