### ISSUE TITLE
Synchronization question

### ISSUE THREAD

**Issue by ost89** [MISP/MISP#1682]
#Question

While having two MISP platform and on MISP 1 having Organization ABC with OrgID 123 and on MISP 2 having organization XYZ with OrgID123, how the synchronization will work? Only OrgID is taken into account in order to synchronize the events? Or ID and name should fully match?

**Comment by iglocska** [comment]
The Organisation UUID is used to match organisations across instances.

**Comment by elhoim** [comment]
Considering it as answered. Closing. Feel free to re-open if you need more info/details.
