### ISSUE TITLE
API search with uuid 

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1683]
Hi team,

It would be interesting to be able to search by uuid :)

### Expected behavior
sample post to : 
http[s]://misp.instance/events/restSearch/download

sample POST message payload (json):
```json
{"request": {"uuid":"57575757-0000-4242-8c13-0a0b0c0d0e0f"}}
```

**Comment by truckydev** [comment]
You are really too fast ^^

Thank you very much, this will really simplify some work :)

**Comment by iglocska** [comment]
Perfect, let me know if anything's broken with it ;)

**Comment by truckydev** [comment]
I try this : 
```python
import requests,json
url = 'http://misp.test/events/restSearch/download'
parameters = {"request": {"uuid":"57575757-0000-4242-8c13-0a0b0c0d0e0f"}}
head= {'Authorization': "APIKey", "Accept":"applicaiton/json", 	"Content-type": "application/json"}
r = requests.post(url,headers=head,data=json.dumps(parameters))
print r.text
```

The response is an HTML page ?
Is my code wrong ?

**Comment by truckydev** [comment]
Ok I see a mistake :(

"Accept":"applicaiton/json"
replace to 
"Accept":"application/json"

But the answer is : 
```
req.status_code : 404
req.text : {"name":"Not Found","message":"Not Found","url":"\/attributs\/restSearch\/download"}
```
I have the same response when my uuid is an Event or an Attribut.

**Comment by truckydev** [comment]
With this feature, it will be cool to add this in pymisp.

Maybe like misp.get_uuid(uuid)
I can write this but when it work first :)

**Comment by truckydev** [comment]
Ok,
Now it's work.
I think it was a cache probleme.

I try to add : 
```
,"searchall":1
```
in : 
```
parameters = {"request": {"uuid":"57575757-0000-4242-8c13-0a0b0c0d0e0f","searchall":1}}
```
and the result with a little ```print(r.json())``` return all event :(

next I remove searchall and the script retrun the right answer ...

**Comment by iglocska** [comment]
OK that's weird! I'll try to have a look at this soon, at the moment we're
doing the end-of-year-training-hackathon-marathon, but as soon as things
start to calm down I'll start working through some of the issues, so stay
tuned :)

**Comment by truckydev** [comment]
Ok,
Thx :)

**Comment by truckydev** [comment]
I think you can close this. ^^

maybe make a todo for pymisp :)

**Comment by truckydev** [comment]
I have make an update to pymisp for this feature :)

**Comment by Rafiot** [comment]
Fixed! thanks
