### ISSUE TITLE
CVS export with the 'info' field?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1687]
Not an issue but I'm looking for some advice...
In the scope of automating the detection of IOC's and enhancing alerte, I'm looking for a way to export some IOC's from my MISP (src ip, dst ip, domain, ...) but also to add the "info" field from their corresponding events. 
Ex:
ip,info
1.2.3.4,"Locky Campaign"

My goal is to use lookup tables in Splunk to add a field with event info. Any tip?
In the same way, a 3rd field could by also interesting: the URL of the event to directly point & click from Splunk.

Note: replace "Splunk" with your favorite tool ;-)

/x

**Comment by iglocska** [comment]
Hello there,

Are you fetching the CSV via the API? You can use the includeContext
parameter to add the event metadata fields to each row.

```
/events/csv/download/[eventid]/[ignore]/[tags]/[category]/[type]/[includeContext]
```

Let me know if you meant something else!

**Comment by xme** [comment]
Tx Andras, I'll check this!
Honestly, I should RTFM :)

**Comment by iglocska** [comment]
Sorry, never saw your response and forgot about this issue, will just close it for now ;)
