### ISSUE TITLE
Just followed the MISP install instructions and none of my workers are running 

### ISSUE THREAD

**Issue by abaykal** [MISP/MISP#1688]
When I start the workers by running the command /var/www/MISP/app/Console/worker/start.sh
they all say 
Creating workers
Starting worker ..................... Fail

this is what I found in resque-worker-error.log
Error: DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
#0 /var/www/MISP/app/Vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(50): DateTime->__construct('tomorrow')
#1 [internal function]: Monolog\Handler\RotatingFileHandler->__construct('/var/www/MISP/a...')
#2 /var/www/MISP/app/Vendor/kamisama/monolog-init/src/MonologInit/MonologInit.php(110): ReflectionClass->newInstanceArgs(Array)
#3 [internal function]: MonologInit\MonologInit->initRotatingFileHandler(Array)
#4 /var/www/MISP/app/Vendor/kamisama/monolog-init/src/MonologInit/MonologInit.php(83): call_user_func(Array, Array)
#5 /var/www/MISP/app/Vendor/kamisama/monolog-init/src/MonologInit/MonologInit.php(63): MonologInit\MonologInit->createHandlerInstance('RotatingFileHan...', '/var/www/MISP/a...')
#6 /var/www/MISP/app/Vendor/kamisama/monolog-init/src/MonologInit/MonologInit.php(38): MonologInit\MonologInit->createLoggerInstance('RotatingFile', '/var/www/MISP/a...')
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(48): MonologInit\MonologInit->__construct('RotatingFile', '/var/www/MISP/a...')

**Comment by standarduserllc** [comment]
I'm having this same issue.

has this been addressed yet?

I'm running Centos 6.7

Thanks.

**Comment by adulau** [comment]
Did you check the current timezone set for your CentOS installation? 

https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos6.txt#L112
https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt#L117

I hope this helps.

**Comment by standarduserllc** [comment]
I double checked that, same error.

Any other suggestions?

Thanks.

**Comment by adulau** [comment]
I suppose you did restart Apache? Maybe running a simple PHP test script from php-cli to see if the timezone is properly set?

**Comment by standarduserllc** [comment]
i ran the time check and am getting the same error. 

script:
<?php
echo 'date_default_timezone_set: ' . date_default_timezone_get() . '<br />';
?>

error:
PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function.

Not sure WTF is going on. Thanks for the help.

**Comment by standarduserllc** [comment]
figured it out.

operator error. my php.ini file was improperly set.

changed the setting outlined here:
https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings

Thanks for the help.
