### ISSUE TITLE
Q&A: Update an attribute based on its UUID using API

### ISSUE THREAD

**Issue by s6930064** [MISP/MISP#1690]
I would like to ask if it is possible to update an attribute based on the UUID from the API.
If yes what are the correct steps?

**Comment by iglocska** [comment]
Sadly this wasn't possible which sounds quite dumb, so I've added the functionality to the API just now in https://github.com/MISP/MISP/commit/8c3b26c2a66692559b6cd4c9d5a5205a7151ee3e

To edit an attribute, simply POST to:

```
https://mymisp/attributes/edit/[my_attribute_uuid]
```

With the following headers:

```
Authorization: [my_api_key]
Content-type: application/json
Accept: application/json
```

The body of the POST request should be a JSON describing the desired changes, such as:

```
{"value":"8.8.8.8", "comment":"google dns"}
```

You only need to set the fields that you want to edit. Let me know if you run into any issues with it.

**Comment by iamshleya** [comment]
Is this still a valid method for updating an attribute? Are there any other ways to complete this via the API?

**Comment by iglocska** [comment]
Yes, it's still absolutely valid. 

Alternatively you can update the full event instead of individual attributes or just use PyMISP (https://github.com/MISP/PyMISP) to do either in a pythonic way.
