### ISSUE TITLE
(MISP training) Add viper to the VM

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1692]
This issue is just here to remind us that we should add viper to the training VMs.

**Comment by adulau** [comment]
@SteveClement Could you have a look at it? Thanks a lot.

**Comment by SteveClement** [comment]
Done.

Added viper-web, on port 8888
Password for admin: Password1234

Added viper-cli to PATH
Added various tools to make viper more useful

Populated ~/.viper/viper.conf with local misp instance config (url/key)
