### ISSUE TITLE
Issue with bro export

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1696]
From gitter: 

"I thought a month or so ago you guys released a fix for the Bro Intel export formatting issue. I am using 2.4.55 and the export is still only writing with a single : instead of :: and the header is not all tab delimited there are two that are still single spaced and these throw errors in the reporter.log"

As discussed with @iglocska, there might be some cases where the "::" is not correct.

**Comment by adulau** [comment]
Sample event 5526addb-a21c-4024-b3d6-5bf3950d210b 

~~~~
10g2hqjqk1frpo1v0rgncx7.ilahilerindir.org Intel:DOMAIN XXX XXXX (5526addb-a21c-4024-b3d6-5bf3950d210b) - CthulhuSPRL.be https://xxx.xxx.xxx.xxx/events/view/838 T -
~~~~

**Comment by Jdi99y515** [comment]
I dont know if this makes a difference or not however it seems to be related to the caching when generating a new cache. It is not generating a new one it is saying that it is complete but the outdated is still set as yes. Also, this is the only job that is running as a different Org Name "SYSTEM" the rest of them are running as my Org Name

**Comment by adulau** [comment]
Fixed in recent releases. If the issue persists, feel free to reopen the issue.
