### ISSUE TITLE
PUSH error between two internal MISP instance

### ISSUE THREAD

**Issue by Mokatani** [MISP/MISP#1702]
Hi everyone,
i have installed two MISP instance for testing purposes, i want to push a feed from my first MISP to second MISP therefore i have added the second MISP server to the first MISP server. "Test Connection" works fine and i can explore the second MISP instance. I have created a feed in my first MISP with tag "PUSH-to-MISP2" and define a rule for pushing with this tag. I have tried to push feed but in log i will see "0 events pushed or updated. 1 events failed or didn't need an update."
I have tried with different distribution level and different tags but i receive the same error.
Can you please help me to achieve this task?

Thanks and best regard

**Comment by donatasiv** [comment]
I had same issue. Maybe it will help: 
https://github.com/MISP/MISP/issues/1680

**Comment by Mokatani** [comment]
Hi,
thanks for your reply, i have restart all workers and restart apache in two instances that i have but i see the same error message in log.

**Comment by Kagee** [comment]
There are several things that can stop an event beeing pushed, like publish status, blocklist, etc. Closing as old, not enough info.
