### ISSUE TITLE
Sightings Visibility

### ISSUE THREAD

**Issue by liz-cullen** [MISP/MISP#1704]
Hi everyone,

Are sightings input via the UI synced between MISP instances? I have a test setup with 2 instances of MISP and users can see sightings from users on the local MISP bit not from users on the remote MISP.

**Comment by iglocska** [comment]
Indeed, sightings are currently local only. We might open it up in the
future for the sync but we still have to consider the (non-technical)
impact.

**Comment by adulau** [comment]
We are doing some work (still a very early experiment) to share IOC information using privacy-preserving data structure:

https://github.com/charly077/thesis/tree/master/encrypted_rules_implem/encrypt_backend

This is basically based on the following paper

> van de Kamp, T., Peter, A., Everts, M. H., & Jonker, W. (2016, October). Private Sharing of IOCs and Sightings. In Proceedings of the 2016 ACM on Workshop on Information Sharing and Collaborative Security (pp. 35-38). ACM.

We would like to extend it for Sighting too and allow the sync. Feedback and idea more than welcome.

**Comment by xme** [comment]
AFAIK, the current API allows to create a new sighting entry for an attribute but there is no way to get Sightings previously defined. My goal is to automatically add sightings from external detection tools when a match is found against a MISP attribute. Then, I'd like to have a (daily|monthly) reporting about what was detected. What do you thing?
In the meantime, I wrote a quick Python script to extract existing sightings:
https://github.com/xme/toolbox/blob/master/misp_sigthings.py

**Comment by adulau** [comment]
The sighting API has been updated recently and also sync of the sighting. Feel free to test and reopen the issue if this is not fixed.

~~~~
API info
Description:
Search MISP sightings using a list of filter parameters and return the data in the JSON format. The search is available on an event, attribute or instance level, just select the scope via the URL (/sighting/restSearch/event vs /sighting/restSearch/attribute vs /sighting/restSearch/). id MUST be provided if context is set.
ReturnFormat:
json
xml
csv
Mandatory:
returnFormat
Optional:
id
type
from
to
last
org_id
source
includeAttribute
includeEvent
Params:
context
~~~~
