### ISSUE TITLE
Erreur 500 with pymisp.update

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1706]
Erreur when i try to update an event with pymisp

Here my quick python script : 
```pyhton
from pymisp import PyMISP
misp = PyMISP('http://misp.test/', '***myApiKey***')
testEvent = misp.get(42)
testevent['Event']['timestamp'] = int(testevent['Event']['timestamp']) + 1
for attr in testevent['Event']['Attribute']:
	if attr['value'] == "valueTest":
		print(attr['timestamp'],attr['comment'])
		attr['timestamp'] = int(attr['timestamp']) + 1
		attr['comment'] = {'test' : attr['comment']}
		print(attr['timestamp'],attr['comment'])
		break
req = misp.update(testevent)
print(req)
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | Debian, ubuntu
| PHP version               |  5.6
| MISP version / git hash   | 2.4.55
| API key  | I try with admin and attribut owner

### Expected behavior
update my Event['comment']

### Actual behavior
It does not take anything

### Steps to reproduce the behavior
try to update a comment in a event by using a python/python3 script with pymisp

### Logs, screenshots, configuration dump, ...
```bash
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    req = misp.update(testevent)
  File "pymisp/api.py", line 328, in update
    return self.update_event(eid, event)
  File "pymisp/api.py", line 277, in update_event
    return self._check_response(response)
  File "pymisp/api.py", line 175, in _check_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 825, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
```

apache **error.log** say but I user admin api key : 
```bash
authorization result of Require all granted: granted
```
apache2 **access.log** with 500 error : 
```bash
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "GET /servers/getVersion.json HTTP/1.1" 200 367 "-" "PyMISP 2.4.53 - Python 3.4.2" 
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "GET /attributes/describeTypes.json HTTP/1.1" 200 10561 "-" "PyMISP 2.4.53 - Python 3.4.2" 
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "GET /events/42 HTTP/1.1" 200 93964 "-" "PyMISP 2.4.53 - Python 3.4.2" 
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "GET /servers/getVersion.json HTTP/1.1" 200 367 "-" "PyMISP 2.4.53 - Python 3.4.2" 
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "GET /attributes/describeTypes.json HTTP/1.1" 200 10561 "-" "PyMISP 2.4.53 - Python 3.4.2" 
127.0.0.1 - - [01/Dec/2016:16:03:33 +0100] "POST /events/42 HTTP/1.1" 500 658 "-" "PyMISP 2.4.53 - Python 3.4.2"
```

**Comment by iglocska** [comment]
That should work, though this:

```
attr['comment'] = {'test' : attr['comment']}
````

Comment has to be a string not an object. The internal error is thrown by MISP and returned to PyMISP, probably due to the validation failing (you can get more info on that in /var/www/MISP/app/tmp/logs/error.log)

```
attr['comment'] = 'test'
```
The above should work at a first glance.

**Comment by FloatingGhost** [comment]
Yep, tested.

It worked provided you give it a string

**Comment by FloatingGhost** [comment]
also you've got capitalisation inconsistency between `testEvent` and `testevent`

**Comment by truckydev** [comment]
Yes,

Well see.
Thanks all :)
I replace
attr['comment'] = {'test' : attr['comment']}
by 
attr['comment'] = str({'test' : attr['comment']})

^^
