### ISSUE TITLE
RH/CentOS Update & Upgrade Files

### ISSUE THREAD

**Issue by jhopp1e** [MISP/MISP#1707]
I'd like to recommend including a RH/CentOS version of the Update.txt & Upgrade.txt files. I took the liberty of creating an Update.Centos.txt and Upgrade.CentOS.txt wherein I replaced the www-data user name with apache (see below).

https://gist.github.com/jhopp1e/2e13e7ac87c8042ff9c0464fac025f89
https://gist.github.com/jhopp1e/b56d99bad54a5c8136cdcc5341364cd1

**Comment by Rafiot** [comment]
2.3-2.4 related
