### ISSUE TITLE
Recommended Correction to xINSTALL.centos7.txt

### ISSUE THREAD

**Issue by jhopp1e** [MISP/MISP#1708]
This is in reference to lines 33-34 of xINSTALL.centos7.txt

rh-php56-bcmath should be replaced with rh-php56-php-bcmath.x86_64

**Comment by jhopp1e** [comment]
Disregard, I just saw issue #1689 "Added and Updated Dependencies". I'll go back to my corner.

**Comment by BenjaminJoly** [comment]
I just close this issue, as this is cleared by now.
