### ISSUE TITLE
PGP Key error / error thrown at Server Diagnostic page

### ISSUE THREAD

**Issue by cvdsouza** [MISP/MISP#1710]
Hi, 
I'm having an issue with  PGP key in MISP. 

I've installed a new instance of MISP (2.4.55) on Ubuntu 14.04 
Followed these install instructions for the PGP generation portion: 

# Generate a GPG encryption key.
mkdir /var/www/MISP/.gnupg
chown www-data:www-data /var/www/MISP/.gnupg
chmod 700 /var/www/MISP/.gnupg
sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --gen-key

# The email address should match the one set in the config.php / set in the configuration menu in the administration menu configuration file

# And export the public key to the webroot
sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --export --armor YOUR-EMAIL > /var/www/MISP/app/webroot/gpg.asc

I then edited the config.php file 
'GnuPG'            =>
                array(
                        'onlyencrypted'     => false,
                        'email'             => 'emailaddress_used@keycreation',
                        'homedir'           => '/var/www/MISP/.gnupg',
                        'password'          => 'passphrase_used',
                        'bodyonlyencrypted' => false,
),

However, I keep hitting this error when attempting to reach the Server Diagnostics page : 

2016-12-04 15:48:14 Error: Fatal Error (64): require_once() [<a href='http://php.net/function.require'>function.require</a>]: Failed opening required 'Crypt/GPG.php' (include_path='.:/usr/share/php:/usr/share/pear') in [/var/www/MISP/app/Model/Server.php, line 2618]
2016-12-04 15:48:14 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'require_once() ...', '/var/www/MISP/a...', 2618)
#1 [internal function]: ErrorHandler::handleError(64, 'require_once() ...', '/var/www/MISP/a...', 2618, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'require_once() ...', '/var/www/MISP/a...', 2618, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

Could someone please point me in the right direction as to how I could resolve this error? 

Any pointers would be appreciated. 

Thanks 
Clinton

**Comment by us3r** [comment]
any update on this? We have the same issue.

**Comment by adulau** [comment]
Did you install php-crypt-gpg ?

**Comment by hyptus** [comment]
We also have this issue on RHEL 7.2.

**Comment by enkidunolinux** [comment]
same, any update?

**Comment by cvandeplas** [comment]
A user having the same issue reports his solution:

>  Problem is solved. The problem is with defined path for php binary in MISP source code. It is hardcoded as `/usr/bin/php` in most of MISP's php scripts. When PHP is installed from SCL repo on a RHEL/CentOS distro, you must create a softlink in `/usr/bin` and then everything works ok.

**Comment by ITServ-DE** [comment]
My solution to the problem was like this:

1. install gpg: `pear install Crypt_GPG`
2. Check if it's installed: `pear list`
3. make sure the `include_path` in `/etc/php/7.0/apache2/php.ini` is **at least** set to `.:/usr/share/php`. **do not rely on default settings.**
4. Restart apache2

Tested on Debian 9.9.

**Comment by SteveClement** [comment]
Thanks for all the solutions.

For further debugging, there is a test.php that also tests PGP.

https://github.com/SteveClement/misp-test/
