### ISSUE TITLE
Customizable session timeout?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1718]
Hello *,

I found the issue #1287 which was related to the same topic, I also found some references on the Google group but no solution right now.
Is there a way to change the default session timeout in the GUI? Even if it's hardcoded, where?

/x

**Comment by iglocska** [comment]
Yep, it's in /var/www/MISP/Config/Core.php - maybe it would be a good idea
to move it to the normal settings too. But you can absolutely edit it via
the file. Also you can enable auto session regeneration to stop the
annoying timeout after x minutes even if the user is active.

**Comment by xme** [comment]
Tx! Implemented on my MISP but indeed, this could be promoted as a real setting.

**Comment by iglocska** [comment]
Yeah, it's one of those things that predates the MISP config file, so it
keeps being forgotten :) Will open an issue.
