### ISSUE TITLE
Event received by organisation not in sharing group distribution

### ISSUE THREAD

**Issue by liz-cullen** [MISP/MISP#1720]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug 
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.55
| Browser                   | If applicable

### Expected behavior

I have 4 MISP instances M1, M2, M3 and M4 each with a single organisation. 

I create pull/push server connections at M2, M3 and M4 to 1 and a sharing group at M2, containing org1, org2 and org3 but not org4 and with roaming enabled.  
I then create an event using this sharing group as its distribution and push it to M1.  

I expect M3 to able to pull the event from M1 but not M4.

### Actual behavior

Both M3 and M4 can pull event.

**Comment by iglocska** [comment]
What is the organisation of the sync user for M4 on M1? It should be org 4.

**Comment by liz-cullen** [comment]
I haven't created any servers at M1. They are all setup at the other end (M2, M3, M4).

**Comment by iglocska** [comment]
That's fine. However you need sync users on m1. Which org are the sync
users?

**Comment by iglocska** [comment]
Basically the other misps log in as the sync users and fetch anything they
can see, if m4 has an org 4 sync user on m1 it should not be able to see
any sharing groups that don't include org 4

**Comment by liz-cullen** [comment]
Ok I see - I was using an org1 sync user because org4 doesn't exist on M1.

**Comment by iglocska** [comment]
Ok, then it makes sense, I'll look into adding some warnings about this in the ui as it can be a bit confusing at first, which especially considering the potential impact can be quite dangerous. 

I'll close the issue for now, let me know if you run into anything else that looks weird.
