### ISSUE TITLE
Class 'CakeResque' not found

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1723]
Hello all,

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | Ubuntu 16.04
| PHP version               |  7.0.8
| MISP version / git hash   | 2.4.55,e9aa3b3bc804599656fb739d98d84499e4e2a7df

### Actual behavior
After a git pull for some reasons (most probably something dumb I did)
-  i can't publish event: I get the error 
> Class 'CakeResque' not found
![Publish Event - Debug error message](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/OwTMoHKy0yFyq66/upload.png)

- i can't go in Administration > Server Settings
![Server Settings - Debug error message](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/fcjKnITsa5NUUCW/upload.png)

I tried multiple things to fix this without success
- checked /var/www/MISP/app/Config/bootstrap.php

> CakePlugin::loadAll(array(
        'CakeResque' => array('bootstrap' => true)
));

- Reinstall CakeResque (following instructions from /var/www/MISP/INSTALL/INSTALL.ubuntu1604.txt)

Tried this as well :  
- /var/www/MISP/app/Console# ./cake CakeResque start
>Error: Plugin CakeResque could not be found.

Any idea / advice on what i could do to fix this ?

**Comment by FloatingGhost** [comment]
```bash
cd /var/www/MISP
sudo -u www-data git submodule init
sudo -u www-data git submodule update
```

**Comment by FloatingGhost** [comment]
try that

**Comment by Kafeine** [comment]
Thanks @FloatingGhost for your reply. In fact, already done as part of the operation seen in /var/www/MISP/INSTALL/INSTALL.ubuntu1604.txt

![CakePHP - INSTALL.ubuntu1604.txt](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/SaOp6BtpeHI9IKY/upload.png)

I gave it another try. But that did not fix.

**Comment by FloatingGhost** [comment]
and you ran the composer install?

**Comment by iglocska** [comment]
That is weird, could it be a permission issue for the files CakePHP files? app/Vendor/kamisama IIRC

**Comment by Kafeine** [comment]
So for the composer install. I did that part:

> Once done, install CakeResque along with its dependencies if you intend to use the built in background jobs:
cd /var/www/MISP/app
sudo -u www-data wget https://getcomposer.org/download/1.2.1/composer.phar -O composer.phar
sudo -u www-data php composer.phar require kamisama/cake-resque:4.1.2
sudo -u www-data php composer.phar config vendor-dir Vendor
sudo -u www-data php composer.phar install

> Enable CakeResque with php-redis
sudo phpenmod redis

> To use the scheduler worker for scheduled tasks, do the following:
sudo -u www-data cp -fa /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php


For the permission :
- /var/www/MISP/app/Vendor# (showing only the corresponding folder to make it shorter)
4 drwxr-x---  6 www-data www-data 4096 May 28  2016 kamisama

And in that Folder : 
- /var/www/MISP/app/Vendor/kamisama# ls -lsa
total 24
4 drwxr-x--- 6 www-data www-data 4096 May 28  2016 .
4 drwxr-x--- 7 www-data www-data 4096 Dec  7 11:39 ..
4 drwxr-x--- 3 www-data www-data 4096 May 28  2016 monolog-init
4 drwxr-x--- 7 www-data www-data 4096 May 28  2016 php-resque-ex
4 drwxr-x--- 5 www-data www-data 4096 May 28  2016 php-resque-ex-scheduler
4 drwxr-x--- 4 www-data www-data 4096 May 28  2016 resque-status

I noticed (not sure if it's related) that installer was complaining about rights on : 
/home/usernamehere/.composer/   
see : 
> Cannot create cache directory /home/usernamehere/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache

**Comment by Kafeine** [comment]
I made a git pull.
It seems i am now on 2.56 541b7a6f107b7b395b210b512c0146ca20be3d07
Fixed.


[got other error tied to Galaxy and DB after that

>SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

which got fixed adding in /etc/mysql/my.cnf : 

>[mysqld]
sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

and restarting mysql service
]
