### ISSUE TITLE
How to disable owner org in event index?

### ISSUE THREAD

**Issue by MichaelDwucet** [MISP/MISP#1724]
Via the MISP GUI we set in Server settings -> MISP settings -> Optional |  MISP.showorgalternate to "false"
But we still get in the event index two columns "Org" and "Owner Org".
Is there another switch we are missing, or is this a bug?

Our MISP verison: 2.4.55

**Comment by iglocska** [comment]
As a site admin you should always be able to see it, for normal users, showorgalternate set to false will only show a single column.

Let me know if it doesn't work as described above for you!

**Comment by MichaelDwucet** [comment]
Thank you Andras, that was it. I was logged in as site admin, so I did not see the effect. Issue closed.
