### ISSUE TITLE
warninglists? How?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1729]
This is (again) a stupid question but I'd like to implement some warninglists...
Where to start?
I see that there is a directory app/files/warninglists (empty in my case).
I created a json file but nothing shows up in the GUI.
Any tip? 

/x

**Comment by iglocska** [comment]
So first of all, if your warninglist directory is empty make sure to initialise and update your submodules:

```
git submdule init
git submodule update
```

After that just click update warninglists in MISP and it should fetch all of the warninglists from the files into the db.
Also, take a peek at the structure of the warning, here is a brief intro:

https://github.com/MISP/misp-warninglists

Just create a new json file, drop it in there and re-run the updater from within MISP.

**Comment by xme** [comment]
Hmmm...
root@misp:/var/www/MISP# git submodule update
root@misp:/var/www/MISP# git submodule
 3a2414bc8c01687290245f186cfa72d29b99d09e PyMISP (v2.2-2-g3a2414b)
 4de92123fa453f5e5eedd001a8918ad2976436af app/Lib/cakephp (2.7.8-7-g4de9212)
 41af89ae44321ca15947a58cc5ce9d9090fff487 app/files/taxonomies (41af89a)

Any idea?

**Comment by iglocska** [comment]
Did you try `git submodule init` first?

**Comment by xme** [comment]
Yep! :(

**Comment by iglocska** [comment]
Will have a look once in on solid ground, will update you here

**Comment by adulau** [comment]
@xme  Here is a list of the submodule that should be in for a recent MISP version

~~~~
 8cec9377c1c4e2ea756282e9bfee7701200c94b6 PyMISP (v2.4.54-29-g8cec937)
 73dcbf2aa33b79512373baa63b39adf3fb838608 app/Lib/cakephp (2.8.9)
 088c04e2f261c33bed6ca5245491cfca69195ccf app/Lib/random_compat (v2.0.2)
 65b83f7305fc50d2d51f159f51d67e603704aae3 app/files/misp-galaxy (heads/master)
 1d957da2245203f9fa9f4d01b71d6f62c11b4442 app/files/taxonomies (remotes/origin/HEAD)
 338241e4999fa618909241e7e413c9fab5debca5 app/files/warninglists (remotes/origin/HEAD)
~~~~

Could you just do a `git submodule init` in the root of MISP?

**Comment by iglocska** [comment]
@RichieB2B is having similar issues, trying to find out what's going on. Very odd!

Edit: Never mind, issue was unrelated.

**Comment by cudeso** [comment]
@xme Because "root@" ... Are files still readable/update as the web-user? Re-applying ownership of files after git submodule x fixed my problem.

**Comment by xme** [comment]
Based on Alex's comment, I added manually the missing submodules and it's ok now...
Impossible to get them via a "git submodule init"

/x

**Comment by adulau** [comment]
I'll close it but we still don't exactly know the origin of the issue.
