### ISSUE TITLE
Stix Export no longer working with latest build

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#1730]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04LTS
| PHP version               | 5.5.9
| MISP version / git hash   | 2.4.56
| Browser                   | NA

### Expected behavior
Expect STIX export to export stix format

### Actual behavior
Throws an error on the server when requested:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/stix\/download\/5944.json"}

### Steps to reproduce the behavior
Try an export

### Logs, screenshots, configuration dump, ...
![stixerror](https://cloud.githubusercontent.com/assets/14302946/20999360/fbec3506-bce1-11e6-9b76-71fdf0417f67.png)

Log Output:
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/misp2stix_framing.py", line 2, in <module>
    from misp2cybox import *
  File "/var/www/MISP/app/files/scripts/misp2cybox.py", line 16, in <module>
    from stix.extensions.test_mechanism.snort_test_mechanism import *
  File "build/bdist.linux-x86_64/egg/stix/__init__.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/stix/base.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/stix/utils/__init__.py", line 342, in <module>
  File "build/bdist.linux-x86_64/egg/stix/utils/nsparser.py", line 309, in <module>
AttributeError: 'module' object has no attribute 'NS_LIST'

Also noted that RPZ does not always return the results but a second request will then return the results as expected. If that behavior continues I'll try and get a screenshot of that as well. 

Have a great day!

**Comment by adulau** [comment]
I tried on a recent a version 4801b47a8a0b29458a0a92424f5800b75f1b0c4f and it works (XML and JSON). Can you check the diagnostic of the STIX version used?

**Comment by FloatingGhost** [comment]
>AttributeError: 'module' object has no attribute 'NS_LIST'

Ah yes, this error. I love this one. 

It's either the pip or the apt version of stix that has this bug in it, if I remember correctly.
Should be fixed by updating :)

**Comment by jigsawsecurity** [comment]
This is what the issue was:
https://github.com/STIXProject/python-stix/issues/291

Thank you for the tip. Was able to uninstall cybox with pip and then recompiled and it's fine.
