### ISSUE TITLE
galaxy issues 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1731]
MISP version / git hash   | 2.4.56 
User permissions;
- Permission level Manage and Publish Organisation Events	  
- Delegate Yes	  
- Sync No	  
- Auth Yes	  
- Audit No	 
- Admin No	  
- Site Admin No	  
- Regexp Access No	  
- Tagger Yes	  
- Template No	  
- Sharing Group No	  
- Tag Editor Yes	 

Here are some issues encountered:
- user permissions: 
  - /galaxies/index : the list of the 2 galaxies is visible
  - galaxies/view/2 : shows the description, but not the content (the list of entries) 
  - /galaxy_clusters/view/60:  results in permission error

- update galaxies link: This causes to have the galaxy IDs change.  (old IDs are lost, and replaced by new IDs) 

- pivot from Event to other events in the same galaxy : when you are on the event page, you cannot pivot to the page with the galaxy details or other events in the same galaxy.

- the misp-galaxy taxonomy is still listed in the tags list; but is empty.  

- (feature request) Ideally adding something to a galaxy should also be possible with the normal tagging principle. The reason for this is keeping the same workflow for the analyst.

**Comment by iglocska** [comment]
Will have a look at the permissions once i am on solid ground, sounds odd.
Editing galaxies is not supported in the current release.

For the ID, it's kind of intended for now, galaxies are dropped and
reloaded fully until the second iteration.

Will look at the other issues asap.

**Comment by adulau** [comment]
@cvandeplas Related to the taxonomies, do you want me to update the taxonomy tool for generating the tags? The new galaxy system can work with both but we did some minor changes into the format. Cheers.

**Comment by iglocska** [comment]
The taxonomy is no longer needed

**Comment by cvandeplas** [comment]
Also permission issues result in an user being able to add a Cluster to an event that's not his. It should behave the same as a tag.

**Comment by iglocska** [comment]
Hmm interesting. Internally it should, so we may have the same issues with
tags via the API (the same functionality is reused)

**Comment by adulau** [comment]
@iglocska So we get rid of the galaxy taxonomy as is? @cvandeplas

**Comment by iglocska** [comment]
Yup

On Dec 8, 2016 4:08 PM, "Alexandre Dulaunoy" <notifications@github.com>
wrote:

@iglocska <https://github.com/iglocska> So we get rid of the galaxy
taxonomy as is? @cvandeplas <https://github.com/cvandeplas>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/MISP/MISP/issues/1731#issuecomment-265762847>, or mute
the thread

**Comment by adulau** [comment]
Fixed.
