### ISSUE TITLE
tags hidden from being used when tagging

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1733]
Today a tag is automatically created and usable once an external event contains this tag or taxonomy entry.

However you might not want to have users to be able to use these. (as they might be confusing)

This feature request is about being able to have tags/taxonomies visible in the event, but not actually usable by the user when tagging new data.   You could compare it with some Sharing Groups that exist but are not usable.

**Comment by cvandeplas** [comment]
Edit: this is a bad idea and will break things
> An identified workaround is to restrict the tagging to one (dummy) organisation.

**Comment by iglocska** [comment]
Indeed, though that is a bit of a hacky workaround, I will add a local override flag so that you can remove it from the UI (similar to the sharing groups).

**Comment by cvandeplas** [comment]
All tags pushed by external orgs (events) should be marked by default as "hidden". (like the sharing groups). This way the instance admin doesn't need to hide tags on a regular base

**Comment by iglocska** [comment]
Yep, makes sense!

**Comment by cvandeplas** [comment]
Thinking about it, the workaround is not a good idea: it will break things when receiving external events.
