### ISSUE TITLE
galaxy UI issue with actor and tool 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#1734]
### Actual behavior
UI issue where the Threat actor is on the same line as the tool.

![image](https://cloud.githubusercontent.com/assets/1073662/21016453/e18cd45c-bd65-11e6-993e-af04c1f334b6.png)

### Steps to reproduce the behavior
Create an event, add cluster for threat actor + tool.

**Comment by iglocska** [comment]
That indeed looks ugly, will add the proper line break.

**Comment by cvandeplas** [comment]
this was resolved some time ago
