### ISSUE TITLE
MISP CSRF For Large Import

### ISSUE THREAD

**Issue by mgeorgy** [MISP/MISP#1735]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | CSRF When attempting large MISP Import
| OS version (server)       | Ubuntu 14.04 LTS
| OS version (client)       | Mac OS
| PHP version               | 5.5.9-1
| MISP version / git hash   | 2.4.55
| Browser                   | Chrome/FF

### Expected behavior
Import MISP Events

### Actual behavior
Browser Error: You have tripped the cross-site request forgery protection of MISP

### Steps to reproduce the behavior
From Source Server: Export MISP XML (generate 100M File)
To Dest Server: Import to MISP Server

### Logs, screenshots, configuration dump, ...
2016-12-08 08:56:26 Error: [BadRequestException] csrf
Request URL: /events/add_misp_export
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#3 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(242): SecurityComponent->blackHole(Object(EventsController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(EventsController))
#5 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /mnt/MISP/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /mnt/MISP/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by iglocska** [comment]
Make sure that the upload of large files is allowed in your php.ini. PHP
will automatically strip uploads above the size specified there and MISP
will consider the missing field as tampering with the form and trigger the
CSRF error.

**Comment by mgeorgy** [comment]
upload_max_filesize = 200M

File being uploaded = 112M

Anything else I should be looking for?

**Comment by iglocska** [comment]
Yeah, it's not too convenient but you also need 

```
post_max_size
```

(because PHP...)

**Comment by mgeorgy** [comment]
Thank you.  That fixed it.

**Comment by iglocska** [comment]
Excellent! This came up recently for attachments as an issue too, I'll
think about a nice way of displaying potential such issues directly in the
upload views.

**Comment by shivang-1252** [comment]
Hi I am new to MISP so I facing the same issue in MISP version 2.4.158. I want to make the above-mentioned changes, but I didn't find the php.ini file. So could you please specify the path? In which file do we have to change.
