### ISSUE TITLE
galaxy/cluster UI - Behavior on click

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1738]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Enhancement
| MISP version / git hash   | 2.4.56,541b7a6f107b7b395b210b512c0146ca20be3d07

I understand it's early integration and maybe this is on the road-map...if so sorry for the noise.

### Current Behavior
![OneEvent](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/PyXYgWMPfUbAEL7/upload.png)
Right now, from the event list, when we click on a galaxy (1 in the image) or cluster (2 in the image) we are sent to the page describing that galaxy : 
![Galaxy Description](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/xchk7bmTE2vEgB7/upload.png)

or that cluster 

![Cluster Description](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/6C2wFQqmpTytJW7/2016-12-08_21h39_39.png)

Then clicking on the associated events (Link 3) you get the list of events tied to this cluster.
(i guess soon list of attributes as well)

Right now inside an event there is no link on the Galaxy name (4 in the image)
And the link (5 in the image) on the cluster expand it. 
![Inside Event](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/XcTeQARaofU8Te5/2016-12-08_22h25_31.png)

### Alternative behavior

Here i would find it more useful if behavior was like for tags. So, from the events list view, clicking on the cluster (link 2) bring directly to the  list of associated Events.
And maybe clicking on the galaxy end-up with all event falling in that galaxy.

And maybe moving that direct link to the cluster ( 5) or galaxy  (4) description inside the event and add a collapse/expand + (6 in the image) near the cluster.
![Inside Event](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/5OZQWZ6KEgLKmRC/2016-12-08_22h21_13.png)

Side proposition : 
- being able to add color to Cluster/Galaxy would be great

**Comment by iglocska** [comment]
Looks good, let's go for these!

**Comment by iglocska** [comment]
It's not exactly as described but a lot closer now. Let me know if you have any other ideas for it!
