### ISSUE TITLE
NIDS Rules Export optimisation

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#174]
When generating NIDS rules for a domain (e.g.: evil.com), don't generate rules for matching subdomains (e.g.: really.evil.com).

Is related to #126 (if it gets implemented) since it would the same case for ip-src/ip-dst and ip ranges

**Comment by SteveClement** [comment]
I think @cvandeplas is right ;)
And if this wants more traction, open a new issue and perhaps already suggest a practical implementation on how to enable/disable such a feature.
