### ISSUE TITLE
File Attachement in Template - Possible bug

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1743]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, (or support?)
| OS version (server)       | Ubuntu 16.04
| PHP version               | 7.08
| MISP version / git hash   | 2.4.56,541b7a6f107b7b395b210b512c0146ca20be3d07

>I am quite bad at sysop. So this might be a problem specific to my system.

### Expected behavior
Adding file via template working same way as via "Add Attachement" manually.

### Actual behavior
Attaching a file (Artifact Dropped) via a template result in a 9kb file looking like : 
![zip_via_template](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/pU5A9YvvTBr9V0C/2016-12-09_11h45_26.png)

### Steps to reproduce the behavior
Create a template.
Add an element type : File.
Category Artifact Dropped (not sure it matters)
![Template Creation - adding file](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/1zgnhQ8KmejO7lE/2016-12-09_11h42_32.png)
Fill an event using this template
![Filling_Event_With_Template](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/PfpDIjYnSppQF6n/2016-12-09_11h43_55.png)
Download the zip.

--
Note : adding the same file using "Add Attachment" is working as expected which is why i think this might be a bug.
![Add Attachement](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/EnP5sKffqYmS1UM/upload.png)

**Comment by iglocska** [comment]
Thanks for the heads-up was indeed a bug introduced a while back. Should be fixed now if you git pull.
