### ISSUE TITLE
Port not accepted in url for links

### ISSUE THREAD

**Issue by Te-k** [MISP/MISP#1745]
Hi,

I have some internal servers on a non standard web port, any link (for internal reference for instance) having a non standard port is refused by MISP.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu
| PHP version               | unknown
| MISP version / git hash   | 2.4.49
| Browser                   | Firefox

### Expected behavior

An url like http://domain:1000/stuff should be accepted as a valid link.

### Actual behavior

If the url contains a port, it is not accepted by MISP

### Steps to reproduce the behavior

Example value : http://test:80/toto
Type : link
Error message : Value not in the right type/format. Please double check the value or select type "other".
Tested on MISP version  MISP 2.4.49 (I did not find any other bug related to this)

**Comment by iglocska** [comment]
Thanks for the heads-up this was indeed silly. Just git pull and it should work.
