### ISSUE TITLE
Password recovery not working

### ISSUE THREAD

**Issue by minslay** [MISP/MISP#1746]
Hello,

I lost my user/pass and I tried to recover a new password, so in command line I used:

/var/www/MISP/app/Console/cake Password my@verified.mail my_new_passwd

and I got this error:

======================================================

Welcome to CakePHP v2.8.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Could not update account for User.id = 1
Array
(
    [newsread] => Array
        (
            [0] => numeric
            [1] => numeric
        )
 
)
 
Updated

================================================

Any idea?
I searched about "newsread" in documentation, but I didn't found anything. I think "newsread" needs to be an int value, but I'm not sure.

Thanks in advance!

**Comment by iglocska** [comment]
Hmm, weird, it works for me. Could you list your MISP, PHP and MySQL versions?

```
root@Iglocska-dev:/var/www/MISP/app/Console# ./cake Password admin@admin.test Password1234

Welcome to CakePHP v2.8.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Updated 
```

**Comment by minslay** [comment]
I noticed that it doesn't work because the type of that column (newsread) is "date".
When I changed type to "int", it worked fine. Has been that column always "int" type? I don't know why that column changed the type.
Where can I get some info about "users" table?

**Comment by iglocska** [comment]
Weird, it changed in May. The upgrade script to 2.4.44 should have changed it to an int field (when we started using the newsread field again).

**Comment by minslay** [comment]
Well, I see that database changed at version v2.4.45, so column "newsread" become "int" from "date" type. I had v2.4.33 and I'm trying to update to v2.4.54, but I didn´t change database, so it keeps wrong type for "newsread" column.

I guess I need to run some script that changes database

**Comment by iglocska** [comment]
It should run automatically on your first login. Basically once you log in with a user it triggers the upgrade scripts to run - but I guess you're in a catch-22 situation since you needed to reset your password.

Since you manually fixed the user field the password reset should execute, after that just log into MISP and it should upgrade all the tables automatically.

It's an interesting issue for sure though, I'll look into changing the password reset script to not affect any of the other fields (that way we can avoid similar issues in the future.

**Comment by minslay** [comment]
Thank you for your tips.
It worked!
