### ISSUE TITLE
Possible memory issue when dealing with numerous attributes in a single event 

### ISSUE THREAD

**Issue by gbossert** [MISP/MISP#1747]
With a 'memory_limit = 512M', MISP fails to display an event made of 5797 attributes highly correlated.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian
| PHP version               | 5.6.22
| MISP version / git hash   | 2.4.48
| Browser                   | n/a

### Expected behavior

Page /events/view/$id_event shows the list of attributes of event $id_event

### Actual behavior

Error is reported with the following message : 
```An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.
```

### Logs, screenshots, configuration dump, ...

In logs, the following message in printed

```
[Mon Dec 12 10:45:26.945439 2016] [:error] [pid 20588] [client xx.xx.xx.xx:43412] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /var/www/MISP/app/Model/Event.php on line 589, referer: https://xxxxxxxx/
```

This memory issue seems to come from the following snippet:

```
public function getRelatedAttributes($user, $id = null, $sgids, $shadowAttribute = false) {

[...]

foreach ($correlations as $correlation) {
    $current = array(
        'id' => $correlation[$settings[$context]['correlationModel']]['event_id'],
        'org_id' => $correlation[$settings[$context]['correlationModel']]['org_id'],
        'info' => $correlation[$settings[$context]['correlationModel']]['info'],
        'value' => $correlation[$settings[$context]['correlationModel']]['value'],
    );
    if (empty($relatedAttributes[$correlation[$settings[$context]['correlationModel']][$settings[$context]['parentIdField']]]) || !in_array($current, $relatedAttributes[$correlation[$settings[$context]['correlationModel']][$settings[$context]['parentIdField']]])) {
        $relatedAttributes[$correlation[$settings[$context]['correlationModel']][$settings[$context]['parentIdField']]][] = $current;
    	}
    }
return $relatedAttributes;

```

with sizeof($correlations) = 144309

**Comment by forgettableEgg** [comment]
I am also having this issue

**Comment by iglocska** [comment]
@jaysig112 - how big is the event that you're viewing (nr of attributes) that causes this?

**Comment by forgettableEgg** [comment]
I usually create events with about 8000-15000 attributes

**Comment by kk0m4k** [comment]
I'd had the same problem, but I've solved it by increasing the memory from 512M to 1G within php.ini.

root@191761d0b039:/etc/php/7.2/apache2# cat php.ini | grep 1024
memory_limit = 1024M
