### ISSUE TITLE
Cannot list users in own org

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1749]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.56

### Expected behavior
- Being able to see the users in own org.

### Actual behavior
- Cannot see users in own org based on the list of members on the org page and error message: _An error has occured, please reload the page_.

### Steps to reproduce the behavior
- Navigate to the list of orgs (_/organisations/index_)
- Go to the org page of your own org.
- Click on the members tab to see a list of members.

**Comment by cristianbell** [comment]
actually this is a permission issue. 
The called snippet points to `admin/users/index/searchorg:$id` which is only visible to admins/org admins. 
If the user list should be available for everyone in an org, a simple list w/o edit/delete.. should be displayed. else the `Members` button should be hidden.

**Comment by iglocska** [comment]
It's a visual bug as stated by @elhoim. Generally users cannot see other users, only admins/org admins can, the button should simply not be visible.
