### ISSUE TITLE
Can't enable warning lists one after another

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1751]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win-7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.56, aaaaaa0523b691b30b4431ffff5d2dd97d57d7df
| Browser                   | IE11

### Expected behavior
Enable all warning lists by clicking on all the checkboxes present in the page

### Actual behavior
If I enable one warning list, I'm not able to enable another one after having enabling the previous one. 
I get the message "Request failed due to an unexpected error"
I have to click on Home, and then come back to the warning lists (Input Filters -> List Warninglists) in order to be able to enable another warning list.

### Steps to reproduce the behavior
Mentioned above

### Logs, screenshots, configuration dump, ...

2016-12-12 14:28:39 Error: [BadRequestException] csrf
Request URL: /warninglists/toggleEnable
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(WarninglistsController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(WarninglistsController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(WarninglistsController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(WarninglistsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by iglocska** [comment]
Very odd. Do you have any browser extensions running that could be blocking scripts? It works for me, what MISP does is POST a request to enable a warninglist and on success sends a GET request to refresh the CSRF tokens for the enable/disable form.

**Comment by h122015** [comment]
No, I don't have any browser extensions. This is weird.

**Comment by h122015** [comment]
I've updated the description of my issue. I wasn't using Ubuntu + FF for this problem

**Comment by adulau** [comment]
Can I close this issue? or the issues persists? Thank you.

**Comment by BenjaminJoly** [comment]
Since there is no response, I assumed that the issue does not persist. Do not hesitate to tell me to reopen it if there is still a problem.
