### ISSUE TITLE
Notice (1024): Element Not Found: Elements/galaxyelements.ctp

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1752]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win-7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.56, aaaaaa0523b691b30b4431ffff5d2dd97d57d7df
| Browser                   | IE11

### Expected behavior
No errors, no notices

### Actual behavior
I'm seeing a notice in the logs

### Steps to reproduce the behavior
Whenever I click on some link under the column Clusters, I see the message displayed below in debug.log

### Logs, screenshots, configuration dump, ...

2016-12-12 14:50:00 Notice: Notice (1024): Element Not Found: Elements/galaxyelements.ctp in [/var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php, line 425]
Trace:
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 425
include - APP/View/GalaxyClusters/view.ctp, line 49
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by iglocska** [comment]
Nice catch, completely missed this, thanks!
