### ISSUE TITLE
Log security related events to syslog

### ISSUE THREAD

**Issue by rmarsollier** [MISP/MISP#1756]
Currently, MISP logs most of its events to either db or text files under app/tmp.

It can be relevant to forward some events who are interresting security-wise to i.e. a SIEM to analyse them.

The best way to do it is to use syslog that will ease the forwarding process and is native to most product (either OS to run MISP on ; and SIEMs).

Important event for SIEM are:
- auth events (failed/suceed, including api)
- user management events (creation, etc.)
- other security events (csrf etc.)

Tagging these syslog lines with a particular syslog tag (see man 5 logger, -t) would be perfect.

**Comment by packet-rat** [comment]
**[RFI]** Where does implementation of this feature officially stand as of today?  

Enabling Security.syslog* does nothing

* _Enable this setting to pass all audit log entries_ directly to syslog. Keep in mind, this is verbose and will include user, organisation, event data.

**Comment by iglocska** [comment]
It seems to work for me - though it's not nearly verbose enough. We already differentiate between the different log levels as described in the original POST with everything generating an info event, except for a few that generate warnings and errors:

```
    public $warningActions = array(
        'warning',
        'change_pw',
        'login_fail',
        'version_warning',
        'auth_fail'
    );
    public $errorActions = array(
        'error'
    );
```

The syslog entries look like this:
![image](https://user-images.githubusercontent.com/3668672/78190312-107edf80-7474-11ea-9329-f51d0f6b2a40.png)

**Comment by iglocska** [comment]
I've pushed a change that results in the above syslog entries - before we were missing the explanation for each entry.

**Comment by RichieB2B** [comment]
Nice! That commit is c6739b7659320784ee3b556a5eb0b1d4e971e40d
