### ISSUE TITLE
Nothing append when warning liste enable

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1759]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| MISP version / git hash   | 2.4.56

### Expected behavior
detect attribut with warning match

### Actual behavior
No attrubuts detected

### Steps to reproduce the behavior
 - update your warning list here : warninglists/index
 - enable 'List of known hashes for empty files' (it's the same with others)
create a sample event and next an attribut with the empty hash 'd41d8cd98f00b204e9800998ecf8427e'

After creating it, clic to "warnings" in the top bar of your attributs liste.

if working, you will see your attribut with empty hash.

Next, it will be great to add number of attrubut with warninglist match in warninglists/index :)

**Comment by iglocska** [comment]
Warnings only show up if you have the "to_ids" flag checked on the attribute that should generate the warning. Also make sure you git pull to the latest commit there was a warninglist bug that was fixed 1-2 days ago.

**Comment by truckydev** [comment]
Yes I'm up to date :)

Thank you for that clarification.
And indeed, it works fine when the tags is correct ^^

Why when only "to_ids" flag checked. 
The information could be interesting also otherwise?

**Comment by iglocska** [comment]
The idea is that it's basically a warning if you're about to flood your IDS with something that will most likely create false positives.

**Comment by truckydev** [comment]
Ok thanks again for the speed of your response :)

**Comment by iglocska** [comment]
No worries! I'll close the issue for now, let me know if you have any other questions ;)
