### ISSUE TITLE
adding attributes for events with distribution = 4 (sharing group) does not work

### ISSUE THREAD

**Issue by cristianbell** [MISP/MISP#1761]
Easy to test, just by using the add_named_attribute.py, if the event has 4 as distribution - sharing group, the pymisp throws `pymisp.exceptions.NewEventError: 4 is invalid, the distribution has to be in 0, 1, 2, 3` adding the attribute to the existing event. 
If the distribution is changed from 4 to 3 on the database level then add_named_attribute.py will work fine. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request
| OS version (server)       | Ubuntu, RHEL, CentOs.. 
| OS version (client)       | all supported
| PHP version               | 5.6 and above
| MISP version / git hash   | 2.4.56 

### Expected behavior
New attribute is added to the event;

### Actual behavior
Attribute is not added to the event, the pymisp throws `NewEventError('{} is invalid, the distribution has to be in 0, 1, 2, 3'.format(self.distribution))`

### Steps to reproduce the behavior
use `add_named_attribute.py` for an event with sharing group distrubution.

**Comment by Rafiot** [comment]
That should be fixed, can you give a try?

**Comment by cristianbell** [comment]
yep, great, thanks !
