### ISSUE TITLE
How to get only get new & changed attributes via API

### ISSUE THREAD

**Issue by MichaelDwucet** [MISP/MISP#1764]
We have an issue with the MISP API. When pulling last events, the API serves all events that got published in the specified timeframe.

The problem is that if an attribute is added in a current event (e.g. domain: bad.invalid), which already existed in an older event, both attributes will get correlated and both events will got served by the API with the last published command.

So, when we pull the current events from MISP to our sensors, we often get a lot of older events reported. But when we review the older events, all attributes are already known. So with one new event, we could get like 10 events reported and have to review all 10 events for new IOCs, but we mostly find out that only the new event having new IOCs.

Is there a way to just get new added attributes (IOCs) since a specified timeframe via the API?

**Comment by truckydev** [comment]
with pymisp, when you use seach you can define spécific laps

https://github.com/MISP/PyMISP/blob/8cec9377c1c4e2ea756282e9bfee7701200c94b6/pymisp/api.py#L749

            :param date_from: First date
            :param date_to: Last date

maybe if you search * ?

**Comment by truckydev** [comment]
more,

It will be interesting to be able to say to the API to not add the relative element. and send just raw attribut 
without : 
 "ShadowAttribute": [],
  "RelatedEvent": [],
  "Galaxy": [],
 ....

ids d'ont care about this :) and just need raw value in  attribut

**Comment by BenjaminJoly** [comment]
As there is no answer for this issue, I close it. Please, do not hesitate to reopen it, or ask me to do so if there is anything to add.
