### ISSUE TITLE
How to integrate Cyber Security Analysis tool in MISP modules?

### ISSUE THREAD

**Issue by rgraf** [MISP/MISP#1770]
Hi,

I would like to provide part of our Cyber Security tool to MISP as a MISP module. In the module I'm going to provide analysis for data stored in MISP events and attributes.

What is the best way to integrate tool parts in MISP? Currently it is embedded in Django and using PostgreSQL. Should I provide our Django modules, or could I access MISP MySQL database using PyMISP or MISP search from MISP modules? Or what would you suggest in this case?

Thanks,

Roman

**Comment by FloatingGhost** [comment]
>cyber security tool

hm, this is about as descriptive as one could hope for.

What does the tool do? What does it need to access misp for? What is this "analysis" and where do you plan for it to go?

**Comment by rgraf** [comment]
Tool employs cs feeds, performs correlation and statistical analysis between incident reports or events, finds similar objects using different methods (and explains why these objects are similar) and makes other analysis. I would like to use events and attributes e.g. from MISP feeds or simply from MISP events. Currently I exported MISP feed in JSON file and create objects from this file. I would like to merge analysis know how of the tool with MISP community to improve analysis tehniques.

**Comment by iglocska** [comment]
One of the main questions is how you want this to be triggered. Basically
MISP allows for the following types of connectors for enrichment:

Triggered by a user when looking for enrichment / trying to add data:
- modules:
  - Use the enrichment modules to call a python script that takes as input
MISP attribute value/type combinations and returns additional attributes
based on external analysis

Triggered externally by the user via an external script, or automated:
- PyMISP: Access the MISP APIs, retrieve MISP data using a host of filters,
add data to MISP events or create new events altogether directly via a
convenient python library
- MISP API: Same scope as PyMISP but using MISP's APIs - use anything that
can make http(s) requests. If Python's your poison I'd highly recommend
PyMISP instead as it makes your life easier.

Triggered whenever an event is published (for example, if you want
automatic enrichment each time a MISP event is published):
- ZMQ interface, if your tool can subscribe to the ZMQ Pub/sub model you
can receive any newly published MISP event and trigger the enrichment. Use
PyMISP or the MISP API to return the enriched data to MISP.


Hope this helps.

**Comment by adulau** [comment]
In addition to @iglocska comments, you can also have a look at [misp-workbench](https://github.com/MISP/misp-workbench) which could give you another approach to do detached analysis from MISP.

There is also a [presentation about the misp-workbench](https://www.circl.lu/assets/files/misp-training/switch2016/4.1-Workbench.pdf).
