### ISSUE TITLE
Export ssdeep hashed as STIX/CyBOX Fuzzy_Hash_Value

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1771]
When exporting an SSDEEP hash to STIX, this is encoded as a cyboxCommon:Simple_Hash_Value element of cyboxCommon:Type _other_. It would make more sense to use a Fuzzy_Hash_Value with cyboxCommon:Type _ssdeep_.

See also http://stixproject.github.io/data-model/1.1.1/cyboxCommon/HashType/

**Comment by Rafiot** [comment]
Need to be changed there: https://github.com/MISP/MISP-STIX-Converter/blob/a102a99c56747e1315fcb6e41198ad1a52b4e734/misp_stix_converter/converters/buildSTIXAttribute.py#L129

**Comment by iglocska** [comment]
Was just about to update misp2cybox.py, but was a bit puzzled as that should be detected automatically based on the type (so SSDEEP should automatically be a fuzzy hash type), but then I noticed this:

https://github.com/CybOXProject/python-cybox/blob/master/cybox/common/hashes.py#L86

huehuehuekillme

**Comment by RichieB2B** [comment]
OMG. No wonder this bug felt familiar. I thought I had already fixed this, now I recall why I didn't. :-(

**Comment by iglocska** [comment]
rm \*stix\* && rm \*cybox\*

fixed.

**Comment by RichieB2B** [comment]
Oh well, the request to fix this is only 2 years old: https://github.com/CybOXProject/python-cybox/issues/166
Give them some time..

**Comment by iglocska** [comment]
You are right ##comma## all they need is some motivation ALONGWITH some time.
