### ISSUE TITLE
CSV download via API

### ISSUE THREAD

**Issue by koenigswinter** [MISP/MISP#1772]
Type of issue: Bug
API call is requesting "/var/www/MISP/app/View/Events/json/csv.ctp", but the current path of the file is "/var/www/MISP/app/View/Events/csv.ctp"
### Work environment
OS version (server): Ubuntu 16.04.1 (64-Bit)
OS version (client): Ubuntu 12.04.5 (64-Bit)
PHP version: 7.0
MISP version: 2.4.56

### Expected behavior
Event download via API in CSV format

Demo HTTP requests:

1) curl -H "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H "Accept: application/json" -H "Content-Type: application/json" https://misp.example.com/events/csv/download  -k  -d '{"request": {"eventid":"4711"}}'

2) curl -H "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H "Accept: application/json" -H "Content-Type: application/json" -k "https://misp.example.com/events/csv/download/4711"

### Actual behavior
Reply for HTTP request 1)
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has 
Occurred.","url":"\/events\/csv\/download"}

Reply for HTTP request 2)
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has 
Occurred.","url":"\/events\/csv\/download\/4711"}

### Logs: /var/www/MISP/app/tmp/logs/error.log
2016-12-19 14:11:27 Error: [MissingViewException] View 
file "Events/json/csv.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/json/csv.ctp',
)
Request URL: /events/csv/download/4711
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/JsonView.php(107): 
View->_getViewFileName('Events/json/csv')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): 
JsonView->render(NULL, NULL)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): 
Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): 
Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): 
Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

### Workaround
cp -a /var/www/MISP/app/View/Events/csv.ctp /var/www/MISP/app/View/Events/**json**/csv.ctp

**Comment by iglocska** [comment]
It should work fine without passing the "Accept" header. Basically it tells MISP that you expect a json as a reponse and MISP will look for a view file in the json subdir. Omitting that header will make it work fine.

**Comment by koenigswinter** [comment]
It works :+1: Thank you for the clarification!
