### ISSUE TITLE
Disable Correlation Globally

### ISSUE THREAD

**Issue by bdecotes-pl** [MISP/MISP#1773]
Is it possible to globally disable correlation against all events (not just for visibility)?

**Comment by iglocska** [comment]
Not at the moment. We are currently looking into implementing a selective exclusion (per event or tag) from the correlation. But if you want we can also implement am optional global correlation block too, it was one of the things we considered anyway.

**Comment by bdecotes-pl** [comment]
Thank you for the quick reply! An optional global correlation block would be ideal for our situation, as we currently utilize other backends for performing ad hoc correlations.

As a stopgap, would it be stable to modify [getRelatedEvents](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L518) or [getRelatedAttributes](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L567) to preclude retrieving all correlating events/attributes? Or is there another location where I should be looking to achieve this?

**Comment by iglocska** [comment]
Indeed that would be a quick fix, but the target for the new release to
remove correlations is tomorrow, so if you can that would of course be
preferable.

**Comment by bdecotes-pl** [comment]
Fantastic! Thank you for the information and assistance.

**Comment by bdecotes-pl** [comment]
Sorry to bump this issue I closed.

Has there been progress on enhancements to globally remove correlations? Thanks for all the great work on this project!

**Comment by iglocska** [comment]
Slight delays, but mostly done. Will have an official release tomorrow,
sorry about the delays.

**Comment by iglocska** [comment]
Just a heads-up, the feature's there now in the latest release!

**Comment by bdecotes-pl** [comment]
Many thanks @iglocska! Cheers!

**Comment by bdecotes-pl** [comment]
This addition has been incredibly useful for my organization! Thank you so very much for the hard work in getting it released.

**Comment by iglocska** [comment]
Glad it was useful! Let me know if you run into any other issues.
