### ISSUE TITLE
filter tags on pull seems not to be working correctly

### ISSUE THREAD

**Issue by cristianbell** [MISP/MISP#1775]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug 
| OS version (server)       | any
| OS version (client)       | any
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.57

### Expected behavior
Use a pull rule on a server to block a tag, => Events with such a tag should be blocked. 
### Actual behavior
Events with the blocked tag are still being pulled. 

### Steps to reproduce the behavior
add rules on a server for example "Events with the following tags blocked: DDoS"
this will result in the following db entry: 
`{"tags":{"OR":[],"NOT":["DDoS"]},"orgs":{"OR":[],"NOT":[]}}`

but the call to the API is:
url: https://url/events/index 
body: {"tag":"DDoS"} 

in https://github.com/MISP/MISP/blob/2.4/app/Model/Server.php#L1577 changing the `if ($operator === 'NOT') $elements[$k] = '!' . $element;` to `if ($operator === 'NOT') $element = '!' . $element;` should fix the issue.

**Comment by iglocska** [comment]
Makes sense, fixed.
