### ISSUE TITLE
Freetext import is slow - twice

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#1781]
The freetext import is a superb tool to mass-import attributes to an event.
However, importing attributes takes a lot of time for different documented reasons.

### Expected behavior
Going from point 1 to 4 should be without any measurable waiting time for the user:
1. paste free text with attributes
2. get the attributes extracted and show the one-side correlation
3. de-select the attributes you don't want to import or modify the comments/attribute type
4. Do the actual import

### Actual behavior
Going from point 1 to 4 has significant waiting time for the user:
1. paste free text with attributes
2. get the attributes extracted and show the one-side correlation
3. de-select the attributes you don't want to import or modify the comments/attribute type
4. Do the actual import

### Steps to reproduce the behavior
Take 100 or more URLs and paste them into the freetext import tool.

### Proposal:
a) Use Redis backend for correlation in step 2 
b) Do step 4 as a background task

**Comment by iglocska** [comment]
Makes sense. a) is a bit tricky due to access control, but we'll need to solve this one way or another anyway. b) good idea!

**Comment by jloehel** [comment]
@rommelfs Why have you closed this issue? It is still a problem. I would love to see step 4 as a background task/job and `similar attributes` optional. It would be an amazing timesaver. :-)
