### ISSUE TITLE
Blank page -- dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding')))); 

### ISSUE THREAD

**Issue by hendejos** [MISP/MISP#1782]
### Work environment

| Questions                  | Answers
|------------------------|--------------------
| Type of issue             | Support
| OS version (server)    | Ubuntu 16.04
| OS version (client)     | Win 7/
| PHP version               | 7.0.8
| MISP version             | 2.4.56
| Browser                     | Firefox, IE11

### Story

Hi there, 

I am new to Ubuntu, CakePHP and MISP and need some help. I followed the guide for MISP ubuntu 16.04 mariadb install.

Vhost is VirtualHost _default_:443

I am using SSL, when I access site I get "dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding')))); " blank page. This is part of webroot index.php final line.

Does anyone know specifically what causes this, and what the fix is?

Thanks!

**Comment by FloatingGhost** [comment]
Sounds like you haven't enabled PHP!

```
sudo a2enmod php7.0 && sudo service apache2 reload
```

**Comment by hendejos** [comment]
Thanks so much for your prompt response! That fixed it. 

Now I get a "An Internal Error Has Occurred. Error: An Internal Error Has Occurred." I'll check this problem out.

**Comment by FloatingGhost** [comment]
Likely you haven't got a php module enabled or something, make sure you follow the entire guide

**Comment by hendejos** [comment]
I just checked the misp error.log:

"MissingConnectionException - Database connection "Mysql" is missing."

I'll have to make sure permissions and configs are proper
