### ISSUE TITLE
Mass financial indicators (i.e. IBAN attribute) UI upload

### ISSUE THREAD

**Issue by cert-orangecyberdefense** [MISP/MISP#1783]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.57
| Browser                   | If applicable

### Expected behavior
When adding attribute=IBAN through the UI, impossible to mass import (i.e. through Freetext import) and/or using multiple IBANs with one entry per line (ps: haven't checked for other Financial indicators yet, but expect same behavior)

Not convenient at all using the UI, when you have multiple entries to create (API should be ok, just multiply the number of requests...) 

### Actual behavior

When providing 2+ IBANs (with one per line), entries are regrouped, giving a warning, as it's not the good format anymore (verified by regex it seems) 

PS: it does work with other attribute types (i.e. url)

### Steps to reproduce the behavior

Ex:
GB51HLFX1108271008XXXX
FR283000208902000000XXXXXXX
gives:
GB51HLFX1108271008XXXXFR283000208902000000XXXXXXX
=> giving a warning

**Comment by iglocska** [comment]
Weird, I just tried copy pasting 

```
GB51HLFX1108271008XXXX
FR283000208902000000XXXXXXX
```

into an add attribute form with the batch import checked and it works fine for me, I get two attributes out of it.

**Comment by cert-orangecyberdefense** [comment]
Yes Andras, you can close it. I forgot to tick the Batch import!

Sorry ;-)

Have nice holidays

**Comment by iglocska** [comment]
No worries, happy holidays to you too! :)
