### ISSUE TITLE
Pull broken after update to MISP 2.4.57

### ISSUE THREAD

**Issue by daanraman** [MISP/MISP#1789]
After updating to MISP 2.4.57 (and experiencing issues with the DB - see https://github.com/MISP/MISP/issues/1776) I now noticed that we are no longer receiving automatic pulls from connected instances.

I just forced a manual pull, but also no new events in our interface - below is the output of the Jobs overview (note how the update to the DB schema was stuck, it might still be linked to that?):

<img width="1414" alt="screen shot 2016-12-28 at 10 42 49" src="https://cloud.githubusercontent.com/assets/2312803/21518959/16ce9810-ccea-11e6-80e3-b7581e47c6ab.png">

Thanks in advance,
Daan

**Comment by iglocska** [comment]
Upgrade_24? What version are you upgrading from?

**Comment by adulau** [comment]
Did you trigger an upgrade from 2.3 to 2.4? There is no more need for this as stated in the legacy old tools page.

"Click the following button to go to the legacy administrative tools page. There should in general be no need to do this unless you are upgrading a very old MISP instance (<2.4), all updates are done automatically with more current versions."

If this is a classical upgrade in 2.4, it's done automatically at first login.

**Comment by daanraman** [comment]
Thanks for the response! We were already on 2.4. We followed this update script for the upgrade: https://github.com/MISP/MISP/blob/2.4/INSTALL/UPDATE.txt

**Comment by adulau** [comment]
We will close this issue. If the issue persists, feel free to reopen the ticket.
