### ISSUE TITLE
STIX Download No Longer Works via Version 2.4.57

### ISSUE THREAD

**Issue by jump3rz** [MISP/MISP#1790]
You use to be able to download the STIX version of an event like so:

https://misp_url/events/stix/download/...

This no longer works for us via version 2.4.57

Is there an alternate way to download the STIX version of an event?

**Comment by FloatingGhost** [comment]
I can't reproduce this on 2.4.57 - do you have an error at all?

**Comment by jump3rz** [comment]
I'm getting the following via the Web UI:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

**Comment by FloatingGhost** [comment]
Ok, that's slightly odd.

Anything going on in `/var/www/MISP/app/tmp/logs/error.log` or `/var/www/MISP/app/tmp/logs/debug.log`?

**Comment by jump3rz** [comment]
This is from `/var/www/MISP/app/tmp/logs/error.log`

2016-12-29 12:50:30 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download/7337
Stack Trace:
#0 [internal function]: EventsController->stix('download', '7337')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-12-29 12:51:29 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download/7337
Stack Trace:
#0 [internal function]: EventsController->stix('download', '7337')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by FloatingGhost** [comment]
did you install stix?
If you type
```bash
python
>>> import stix
>>> import cybox
```

is it ok?

**Comment by jump3rz** [comment]
Someone apparently didn't install the stix module during an upgrade. After installing it, that did fix the issue. Thank you so much!
