### ISSUE TITLE
MISP incorrectly complains about MISP.baseurl

### ISSUE THREAD

**Issue by daanraman** [MISP/MISP#1791]
In my server settings, I have a critical warning on MISP.baseurl, saying it does not match the URL from where I visited the page. However, I can confirm the URL specified in the config is exactly the one I see in the URL (over HTTPS).

Is this a known issue? Anything I can do to fix this?

Thank you,
Daan

PS the format of my MISP.baseurl variable is https://aaa.bb.cc.dd

**Comment by iglocska** [comment]
Weird haven't seen that happen yet. Do you have anything funky going on with a proxy that terminates https for example?

**Comment by daanraman** [comment]
no proxy

**Comment by iglocska** [comment]
Very curious, that shouldn't happen.

**Comment by yannw** [comment]
I have the same issue:
reachable via: https://misp.domain.tld 
MISP.baseurl: https://misp.domain.tld
no proxy
everything works but red MISP.baseurl setting with error:
"The currenty set baseurl does not match the URL through which you have accessed the page. Disregard this if you are accessing the page via an alternate URL (for example via IP address)."
(BTW: Typo in "currentLy")

**Comment by iglocska** [comment]
Could you git pull to get the latest commit?

**Comment by w4sp00** [comment]
Same issue here. Is there any workaround?
Thanks

**Comment by iglocska** [comment]
Are you on MISP 2.4.68?

**Comment by w4sp00** [comment]
No, 2.4.67

**Comment by iglocska** [comment]
The latest version fixes this issue that was introduced briefly with 2.4.67.

**Comment by w4sp00** [comment]
Ok. I'll upgrade it. Thank you

**Comment by iglocska** [comment]
No worries, let us know if the issue persists.

**Comment by w4sp00** [comment]
I've updated to 2.4.69. It works.
Thank you!
