### ISSUE TITLE
Make delete async

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1797]
When you have large events to delete, it might take time. It would be nice to make the delete async.

**Comment by truckydev** [comment]
maybe easyer with api ?

something like : 

```python
for i in range(350,427):
    misp.delete_event(i)
```

**Comment by adulau** [comment]
Sure but the objective is to support the users/analysis using the UI too ;-)

**Comment by adulau** [comment]
Improvements were made for the bulk delete via the UI.
