### ISSUE TITLE
ubuntu 14.04 install note issue

### ISSUE THREAD

**Issue by w1mp1k1ng** [MISP/MISP#1802]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior
Following instructions in install notes verbatim under '6/ Create a database and user'

### Actual behavior

     ubuntu@ip-10-51-223-78:/var/www/MISP$ mysql -u misp -p misp < INSTALL/MYSQL.sql
     Enter password: 
     ERROR 1214 (HY000) at line 74: The used table type doesn't support FULLTEXT indexes

**Comment by w1mp1k1ng** [comment]
RESOLVED.  Definitely the same issue as https://github.com/MISP/MISP/issues/292.  I had to adjust four table creations ('events', 'correlations', 'organisations', 'tags') from InnoDB to MyISAM to support full text indexing.

**Comment by iglocska** [comment]
True it's an issue with older MySQL versions. I'll look into something more clever to resolve this for older versions.

**Comment by cudeso** [comment]
On Ubuntu 14.04 you can get MYSQL 5.6 with 
```
apt-get install mysql-server-5.6
```
