### ISSUE TITLE
Import large MISP import fails

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1806]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | MISP 2.4.59
| Browser                   | If applicable

### Expected behavior

Import should be okay

### Actual behavior

Tried to import a fairly large MISP export (~1gig)

.htaccess
```
php_value max_execution_time 300000
php_value memory_limit 2512M
php_value upload_max_filesize 1500M
php_value post_max_size 1500M
```

Tried to enable debug mode, but no success:
```
An error has occured while attempting to access file "".

Error: The requested address '/events/add_misp_export' was not found on this server.
Stack Trace

    APP/Lib/Tools/FileAccessTool.php line 15 → FileAccessTool->__checkForFalse(boolean, string)
    APP/Controller/EventsController.php line 2177 → FileAccessTool->readFromFile(string, integer)
    APP/Controller/EventsController.php line 1199 → EventsController->_addMISPExportFile(string)
    [internal function] → EventsController->add_misp_export()
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(EventsController, array)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
    APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```
(syncing between the servers is not an option)

Is there any other way to push an export using a script to the API in smaller chunks?

**Comment by iglocska** [comment]
You could use the feed system which handles such cases much better. Generally the interactive import is meant for smaller packages.

On the MISP that you are exporting from, simply generate a feed with the data you want moved (you can use the feed generator script in PyMISP) and then simply throw it on a webserver that your MISP can see and let it ingest it.

Alternatively you'd have to write a small python script that takes the package, splits it into individual events and pushes them to MISP one by one. Using PyMISP this should be pretty simple.

**Comment by Rafiot** [comment]
Old issue, closing, please open a new one if needed.

**Comment by angarod** [comment]
i'm facing the same issue. How did you solve this size problem ?

**Comment by Rafiot** [comment]
There were lots of fixes on the syncing recently, if you're on the latest release and still have the problem, please open a new issue.
