### ISSUE TITLE
(Re-)Pulling of old, deleted events

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#1807]
### Work environment
| Type of issue             | Potential bug
| OS version (server)       | Ubuntu Server 16.04.1 LTS
| OS version (client)       | Windows 7
| PHP version               | 7.0.8
| MISP version / git hash   | 2.4.59

### Expected behavior
I recently deleted all events on one of our instances through the API with the method delete_event().
Now I want to pull the same events again from another internal instance.

### Actual behavior
None of the deleted events are pulled again. The pull job gets queued for a long time but then finishes without an error.
Recent events that have been added after the removal of all the other ones are pulled. So the sync itself works.

### Logs, screenshots, configuration dump, ...
![image](https://cloud.githubusercontent.com/assets/20771149/21683046/e6672fe2-d357-11e6-88d5-066b30c49e01.png)

**Comment by iglocska** [comment]
There is a setting called MISP.enableEventBlacklisting, make sure it is disabled. When that setting is enabled, each event's UUID gets put in a blacklist preventing it to be synced again.

**Comment by ghost** [comment]
Well that was an easy fix. Works now, thank you.

**Comment by iglocska** [comment]
Excellent, no worries.
