### ISSUE TITLE
pymisp add_event error 500

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1808]
Here is my python sample for add event with pymisp : 
```python
misp = PyMISP('http://misp.test/', 'mykey')
attribute = {
	"category": 'Internal reference',
	"type": 'text',
	"value": 'Test test test',
	"timestamp": "0",
	"to_ids": "0",
	"distribution": "0",
	"comment": str({'sample':'test'})
}
event = {"Event": {"info": 'API event add ',
	"timestamp": "1",
	"attribute_count": 0,
	"analysis": "0",
	"date": time.strftime("%Y-%m-%d"),
	"org": "",
	"distribution": "0",
	"Attribute": [],
	"proposal_email_lock": False,
	"threat_level_id": "4",
	}
}
event["Event"]["Attribute"].append(attribute)
r = misp.add_event(event)
print(r.status_code)
print(r.text)
```

Return : 
```bash
500
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events"}
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | Debian
| OS version (client)       | Debian (local)
| PHP version               | PHP 5.6.29-0+deb8u1
| MISP version / git hash   | 2.4.59
| Browser                   | all work with chrome FF

### Expected behavior
new avent 

### Actual behavior
500 error

### Steps to reproduce the behavior
try to add event with pymisp

### Logs, screenshots, configuration dump, ...
tailf app/tmp/logs/error.log  : 
```sh
2017-01-05 16:09:27 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'
Request URL: /events
Stack Trace:
#0 MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('INSERT INTO `mi...', Array)
#2 MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1026): DboSource->execute('INSERT INTO `mi...')
#3 MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(Attribute), Array, Array)
#4 MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 MISP/app/Model/Event.php(1990): Model->save(Array, Array)
#6 MISP/app/Controller/EventsController.php(1065): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#7 [internal function]: EventsController->add()
#8 MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

app/tmp/logs/debug.log
```sh
Trace:
implode - [internal], line ??
DboSource::create() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1023
Model::_doSave() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1940
Model::save() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1758
Event::_add() - APP/Model/Event.php, line 1990
EventsController::add() - APP/Controller/EventsController.php, line 1065
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by FloatingGhost** [comment]
you might just be missing a required field with your little manual JSON

the api has ways to create events without you having to create the JSON by hand.

try:
```python
from pymisp import PyMISP
misp = PyMISP('url', 'key')

event = misp.new_event(
               info = "API event add",
               analysis = 0,
               distribution = 0,
               threat_level_id = 4
            )

misp.add_named_attribute( 
               event = event, 
               type_value = "text", 
               value = "Test test test", 
               comment = "Some comment"
             )
```

**Comment by truckydev** [comment]
Yes but when I have for example 100 attribut,for 1 event and next you loop in 100 event ...

I prefere do 1 request whith a formated event.

(sorry for my bad english)

**Comment by FloatingGhost** [comment]
I'm afraid I don't follow.

If you're doing it manually, you're playing with fire - little things like the `timestamp` field can screw everything over.

It'll be much easier to use the API as it was designed, and not generate JSONs manually. This also means that if the schema changes in the future, your JSON won't be rejected as invalid.

**Comment by truckydev** [comment]
I understand and I agree.

The python code in this  issue is just a sample.
I prefer to create a dictionary. The information I get comes from different sources.
I build my dictionary according to these sources and in the end I add my event.

Here a sample a do before.
https://github.com/MISP/PyMISP/blob/master/examples/ioc-2-misp/ioc2misp.py#L111

If you make a request for each attribute you want to add, the addition becomes very long.

And next, error message is really not explicit ...

**Comment by FloatingGhost** [comment]
You're doing far more work than you actually need to then.

How do you build your JSON? At some point you'll have a value and a type, right?

**Comment by truckydev** [comment]
I don't build a json, it's a dict because in misp.add_event data is converted to json.
https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L273

Ok, I have found : 

I miss on event : 
```python
"disable_correlation": False,
```
now it's wotk

Here minimal dictionnary to create event with PyMISP.add_event(event)
```python
attribute = {
			"category": 'Internal reference',
			"type": 'text',
			"value": 'Test test test',
			"comment": "{'comment':'un test'}",
			}

event = {"Event": {
	"info": 'un test API event',
	"disable_correlation": False,
	"Attribute": [],
	}}
event["Event"]["Attribute"].append(attribute)
misp.add_event(event)
```

**Comment by FloatingGhost** [comment]
You do realise JSON and dict are basically the same, right? Except in special cases, they can be assumed to be the same.

Also I don't know how to respond to this post, I can't make much sense of it

**Comment by truckydev** [comment]
don't be affraid :)

maybe, you can add ```"disable_correlation": False,``` here ? (or I can make a pull/request)

https://github.com/MISP/PyMISP/blob/0511bd44867f5f7f74cb54d61b0df7d99b719118/examples/ioc-2-misp/ioc2misp.py#L133

without this, there is a 500 error to use it ^^

**Comment by iglocska** [comment]
I've just tried this:

```
misp = PyMISP('http://misp.test/', 'mykey')
attribute = {
	"category": 'Internal reference',
	"type": 'text',
	"value": 'Test test test',
	"timestamp": "0",
	"to_ids": "0",
	"distribution": "0",
	"comment": str({'sample':'test'})
}
event = {"Event": {"info": 'API event add ',
	"timestamp": "1",
	"attribute_count": 0,
	"analysis": "0",
	"date": time.strftime("%Y-%m-%d"),
	"org": "",
	"distribution": "0",
	"Attribute": [],
	"proposal_email_lock": False,
	"threat_level_id": "4",
	}
}
event["Event"]["Attribute"].append(attribute)
r = misp.add_event(event)
print(r)
```

And it works fine for me on my dev VM, the event gets created. With that said, I agree with @FloatingGhost, adding hardcoded timestamps calls for a disaster. You can ommit all of those fields anyway, this is valid too:


```
misp = PyMISP('http://misp.test/', 'mykey')
attribute = {
	"category": 'Internal reference',
	"type": 'text',
	"value": 'Test test test',
	"to_ids": "0",
	"distribution": "0",
	"comment": str({'sample':'test'})
}
event = {"Event": {"info": 'API event add ',
	"analysis": "0",
	"date": time.strftime("%Y-%m-%d"),
	"distribution": "0",
	"Attribute": [],
	"threat_level_id": "4",
	}
}
event["Event"]["Attribute"].append(attribute)
r = misp.add_event(event)
print(r)
```

**Comment by truckydev** [comment]
heu ok,
It's work now ... very veird.

This is not the first time I've encountered this kind of problem.
I think of a cache problem because it occurred just after a version upgrade.

Otherwise, for the timestamp, it's was just a sample code. ^^
