### ISSUE TITLE
Implement return of error codes in REST-API

### ISSUE THREAD

**Issue by cgi1** [MISP/MISP#1810]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request
| OS version (server)       | All
| OS version (client)       | All
| PHP version               | All
| MISP version / git hash   | 2.4.59
| Browser                   | All

### Expected behavior

REST-API returns error if the misp event could not been created or modified due to an error. 
Errors are (for example):

- Invalid JSON format in input data
- One or more field names are not known to the system

### Actual behavior
- Every request return `200 OK`

### Steps to reproduce the behavior

`POST` to `https://<your_misp>/events/1` with invalid JSON. E.g.:

```
{
    "Event":{
        "distribution":"4",
        "sharing_group_id":"5",,,,,
        
    }
}
```

### Logs, screenshots, configuration dump, ...
![inv_json](https://cloud.githubusercontent.com/assets/18695252/21714835/602f126e-d401-11e6-9499-5bb3a1245686.png)

**Comment by jaegeral** [comment]
hm not sure if that is still valid....
