### ISSUE TITLE
Apache redirect too many times after initial MISP login

### ISSUE THREAD

**Issue by espressobeanies** [MISP/MISP#1813]
Hi, 

I'm getting redirect error messages from Apache after I log into the MISP homepage and I'm directed to change my password.

https://xxx.xxx.xxx.xxx/users/change_pw

The xxx.xxx.xxx.xxx page isn’t working
xxx.xxx.xxx.xxx redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

## Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 7
| PHP version               | 7.0
| MISP version / git hash   | Latest as of 1/6/2017
| Browser                   | Chrome/Firefox

### Expected behavior
Password change form

### Actual behavior
(Above)

**Comment by FloatingGhost** [comment]
Can you post your apache configuration file? There might be something weird in there

**Comment by espressobeanies** [comment]
You're asking for apache2.conf or misp-ssl.conf?

**Comment by FloatingGhost** [comment]
misp-ssl.conf (probably)

**Comment by espressobeanies** [comment]
```
<VirtualHost *:443>
        ServerAdmin xxxxxxxx
        ServerName xxx.xxx.xxx.xxx
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.local.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.local.key
        ##SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
```

The original apache2.conf log wasn't changed. I'm not sure if it's a permissions issue somewhere.

**Comment by espressobeanies** [comment]
I was able to get past it from redoing it from scratch. May have been a permissions issue somewhere along the line that wasn't resolvable.Thanks!

**Comment by adulau** [comment]
Thanks for the feedback.

**Comment by charleypking** [comment]
I'm having this same error. Not sure if it's a cert thing. 

<VirtualHost *:443>
        ServerAdmin xxx@xxxx.xxx
        ServerName x.x
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Require all granted
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.local.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.local.key
        ##SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
        Header set X-Content-Type-Options nosniff
        Header set X-Frame-Options DENY
</VirtualHost>
