### ISSUE TITLE
Upgrading 2.4.54 to 2.4.59

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#1814]
Upgrading from 2.4.54 to 2.4.59, no errors but after I try to login it just spins,... I tried three ways of updating this 

Would it be easier just to build Ubuntu 16 from scratch and move over the mysql database?

I don't think this is a bug, I think I'm just doing something whacky.

**Comment by iglocska** [comment]
Could you do the following?
```
mysql -u misp -p misp
drop database cake_sessions;
CREATE TABLE IF NOT EXISTS `cake_sessions` (
  `id` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `data` text COLLATE utf8_bin NOT NULL,
  `expires` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `expires` (`expires`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

and see if it works?

**Comment by mathurin68** [comment]
I will try it first thing when I get into the,office on Monday.

**Comment by mathurin68** [comment]
Hmmm, same thing just sits there and spins...

I did  run drop table instead of database(kept getting error) - 
mysql> drop table cake_sessions;
Query OK, 0 rows affected (0.69 sec)

mysql> CREATE TABLE IF NOT EXISTS `cake_sessions` (   `id` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',   `data` text COLLATE utf8_bin NOT NULL,   `expires` int(11) NOT NULL,   PRIMARY KEY (`id`),   INDEX `expires` (`expires`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
Query OK, 0 rows affected (0.67 sec)

**Comment by mathurin68** [comment]
Looks like I can upgrade it one version at a time up to 2.6...2.7 just sits there and spins after I upgrade.

**Comment by mathurin68** [comment]
Also we've been using this as an IOC database so the number of events is huge.  The events can all be blown away,but we'd like to keep the tags, users,e tc.

**Comment by iglocska** [comment]
Do you get anything in your error log during the upgrade? 

```
/var/www/MISP/app/tmp/logs/error.log
````

**Comment by iglocska** [comment]
Ok, looking at the upgrade scripts, it's 2.4.57 that fails right? It's reindexing the full correlation table, if your correlation table is massive then maybe this is what's causing issues. Is your MySQL completely stock or did you tune it at all? 


Could you just paste your my.cnf so we could have a look at your settings?

**Comment by mathurin68** [comment]
Hah, I don't think we have modified anything... at least I don't remember doing it --
Here's the last few errors - 
2017-01-11 09:47:38 Error: [InternalErrorException] Internal Server Error
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 277)
#1 [internal function]: ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 277, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Allowed memory ...', '/var/www/MISP/a...', 277, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-01-11 10:40:24 Error: [BadRequestException] csrf
Request URL: /users/login
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

[my.cnf.txt](https://github.com/MISP/MISP/files/699789/my.cnf.txt)

**Comment by mathurin68** [comment]
Also, clearing the events table is not off the table

**Comment by iglocska** [comment]
I wouldn't do that (that sounds like a "nuclear" option) - however your mysql could definitely use some tuning. The default settings are crazy memory limited, the task that fails for you is basically a reindexing of your correlations (2.4.57) - so if that fails it's very likely a memory issue. 

So what I'd try to do: 

- Raise the memory limits across the board for MySQL
- check and raise the memory limits for PHP (you should have some guidance in the diagnostics tool)

**Comment by mathurin68** [comment]
Alright, I did everything you suggested, ran the upgrade script again and just left it alone over night with mysqld buzzing along... and this morning vioila!  It's up to 2.4.59 looks good, thanks for all the help!!!
