### ISSUE TITLE
Display tooltip for tags

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1817]
Display tooltip for tags in the list of events and in the details of an event.
Content of the tooltip could be the expanded field of tag entries.

For example for _admiralty-scale_ taxonomy, for the entry _a_ under the predicate _source-reliability_, the tooltip could be _Completely reliable_.

Most of the tags from taxonomies are self explanatory, but some like admirality scale are a bit more cryptic and deserve some more details.

**Comment by JakubOnderka** [comment]
Already done :)
