### ISSUE TITLE
Authentication options for feeds

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#1823]
Add the capability to authenticate for the individual feeds.

**Comment by adulau** [comment]
Potential authentication scheme:

 - Basic-Auth Username/Password
 - X.509 client-side certificate authentication

**Comment by adulau** [comment]
We got a request for the PhishMe service called ThreatHQ where the authentication is set by header. Seems to be basic auth (so we should be fine with the standard auth).

**Comment by adulau** [comment]
Related to #2658

**Comment by treed593** [comment]
Example Schema for PhishMe ThreatHQ Stix

[phishMeschema.txt](https://github.com/MISP/MISP/files/1643279/phishMeschema.txt)

**Comment by adulau** [comment]
@treed593 Could you test the current HEAD? We added authentication header https://github.com/MISP/MISP/commit/96cea0b057967286bc63d2ed6229abc09913dc65 and let us know if this is covering your case.

**Comment by adulau** [comment]
I suppose we can close the issue as this is now implemented. Feel free to reopen it if there is some missing part in the implementation. We tested the auth against a basic auth MISP feed and it works as expected.
