### ISSUE TITLE
Bulk tagging

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1829]
Adding tags to multiple events at once on the web interface.

**Comment by RichieB2B** [comment]
+1 for this feature!

**Comment by morallo** [comment]
I just uploaded this, in case it's useful until this feature is implemented in the core.

https://github.com/morallo/misp-bulk-tag

**Comment by RichieB2B** [comment]
Is this planned? Seems we just need to port the attributes bulk tagging to events?

**Comment by iglocska** [comment]
It's a tiny bit trickier, but yes, would be nice. The only difference is
that tags have to be local for some events, even if we choose global
(depending on ownership).

**Comment by github-germ** [comment]
Would also be real helpful to provide bulk tagging in PyMISP, e.g. see https://github.com/MISP/PyMISP/issues/337, not sure of we can package these together somehow.

**Comment by enjeck** [comment]
Duplicate of https://github.com/MISP/MISP/issues/1604
