### ISSUE TITLE
SMIME problems

### ISSUE THREAD

**Issue by cederom** [MISP/MISP#1835]
Hello! We have noticed that SMIME does not seem to work correctly on CIRCL MISP 2.4.59..

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.59

### Expected behavior

SMIME works as expected - I get an encrypted SMIME email from MISP to my Outlook, doubleclick the message, read the message.

### Actual behavior

I do get an email from CIRCL MISP encrypted with SMIME but I am not able to open/read it.

### Steps to reproduce the behavior

Send SMIME email.

**Comment by Keisial** [comment]
Are you able to open other S/MIME messages?

**Comment by cederom** [comment]
Yup. S/MIME + Outlook works fine. It was problem of a **local token software client** (Ingenico in my case), required an update :-)
