### ISSUE TITLE
Failing to import empty database from MYSQL.sql on CentOS7

### ISSUE THREAD

**Issue by mdtro** [MISP/MISP#1839]
[misp_centos7_install.txt](https://github.com/MISP/MISP/files/702949/misp_centos7_install.txt)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | CentOS 7.3.1611
| OS version (client)       | Win 7 (putty)
| PHP version               | 5.6.25
| MySQL/MariaDB version | mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1
| MISP version / git hash   | 2.4.59, b68a37ec793e0aef124faf8a24f35bf93760d3b7

### Expected behavior
Successful loading of the empty tables into the 'misp' database.

### Actual behavior
[root@misp2lab MISP]# mysql -u misp -p misp < INSTALL/MYSQL.sql
Enter password:
ERROR 1214 (HY000) at line 74: The used table type doesn't support FULLTEXT indexes

### Steps to reproduce the behavior
From a base CentOS7 Minimal install, follow each step in sequence of the xINSTALL.centos7.txt file.

My database skills are very subpar, but from my research, this might be an issue with using InnoDB as the engine in combination with the FULLTEXT index and the specific MariaDB version? I was able to get a successful table import when I changed FULLTEXT INDEX to FULLTEXT KEY. Are key and index synonymous? Is there any foreseen impact to using MyISAM as the engine?

I'm going to load MariaDB (the newest available stable release) directly from their RPM and retry this to see if I have different results. I'll comment back later to let you know what's come of that.

### Logs, screenshots, configuration dump, ...
Putty log attached.

**Comment by mdtro** [comment]
It also looks like Ventz Petkov's maintained docker image doesn't have FULLTEXT INDEX anywhere in the .sql file. Small sample below.

**From Petkov's harvarditsecurity/misp:**
```
CREATE TABLE IF NOT EXISTS `correlations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` text COLLATE utf8_bin NOT NULL,
  `1_event_id` int(11) NOT NULL,
  `1_attribute_id` int(11) NOT NULL,
  `event_id` int(11) NOT NULL,
  `attribute_id` int(11) NOT NULL,
  `org_id` int(11) NOT NULL,
  `distribution` tinyint(4) NOT NULL,
  `a_distribution` tinyint(4) NOT NULL,
  `sharing_group_id` int(11) NOT NULL,
  `a_sharing_group_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `info` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id` (`event_id`),
  INDEX `1_event_id` (`1_event_id`),
  INDEX `attribute_id` (`attribute_id`),
  INDEX `1_attribute_id` (`1_attribute_id`),
  INDEX `org_id` (`org_id`),
  INDEX `sharing_group_id` (`sharing_group_id`),
  INDEX `a_sharing_group_id` (`a_sharing_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**From MISP/MISP MYSQL.sql:**
```
CREATE TABLE IF NOT EXISTS `correlations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` text COLLATE utf8_bin NOT NULL,
  `1_event_id` int(11) NOT NULL,
  `1_attribute_id` int(11) NOT NULL,
  `event_id` int(11) NOT NULL,
  `attribute_id` int(11) NOT NULL,
  `org_id` int(11) NOT NULL,
  `distribution` tinyint(4) NOT NULL,
  `a_distribution` tinyint(4) NOT NULL,
  `sharing_group_id` int(11) NOT NULL,
  `a_sharing_group_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `info` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `value` (`value`),
  INDEX `event_id` (`event_id`),
  INDEX `1_event_id` (`1_event_id`),
  INDEX `attribute_id` (`attribute_id`),
  INDEX `1_attribute_id` (`1_attribute_id`),
  INDEX `org_id` (`org_id`),
  INDEX `sharing_group_id` (`sharing_group_id`),
  INDEX `a_sharing_group_id` (`a_sharing_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by RichieB2B** [comment]
MISP now requires MySQL/MariaDB 5.6 as a minimum for exactly the reasons you mention. You can install it on CentOS using the RedHat software collections.

**Comment by mdtro** [comment]
You are correct. Thank you!

I removed mariadb, installed 10.1.20 from the mariadb repo, and then ran a mysql_upgrade. Importing the tables into the database worked flawlessly after that. 

Thanks again! :)
