### ISSUE TITLE
table log 'change' field displayed in event history

### ISSUE THREAD

**Issue by cristianbell** [MISP/MISP#1840]
Why is the `change` field not shown in the event history view? It is fetched from the database but not displayed in the view. 
Is there a reason to not display it? (user is allowed to see the event history so why not display this field..?)

### Expected behavior
see `change` as one of the columns in MISP_URL/logs/event_index/EVENT_ID

### Actual behavior
the `change` field is not displayed.

**Comment by iglocska** [comment]
Because it can contain field changes that normal users shouldn't see, such
as e-mail addresses.
