### ISSUE TITLE
events/upload_sample upload an attachment

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1843]
Posting a file on `events/upload_sample` add an attachment to the event instead of a malware-sample.

**Comment by iglocska** [comment]
The upload_sample api allowed uploading malware-samples and attachments, decided by the IDS flag. Not setting it defaulted to an attachment.

I've removed this functionality as it's indeed confusing and we can upload attachments via /attributes/add anyway.

**Comment by Rafiot** [comment]
Oh, right, I'll update PyMISP accordingly

**Comment by iglocska** [comment]
No need, removed it so it should only create samples now no matter what ;)
