### ISSUE TITLE
Modify custom css - delete default styles

### ISSUE THREAD

**Issue by minslay** [MISP/MISP#1846]
Hello,

I'm trying to modify MISP look&feel with my own css file since MISP v2.4.48 allows load a custom css.
( - Added the option to load a custom css after the default css.  [Iglocska])

I guess my custom css loads over default css so if I change or add styles, MIPS applies my styles. But what if I only want to remove a default style?

e.g.: MISP default style has a padding-top:20px, but I don't want any padding-top.

Do you know if I can manage that?

Thank you. Best regards.

**Comment by FloatingGhost** [comment]
CSS has an !important directive to override rules

```css
some style {
  my_override: value !important;
}
```

So in this case

```css
body (or wherever the rule is) {
  padding-top: 0px !important;
}
```

Should help :)

**Comment by minslay** [comment]
Oh, thanks FloatingGhost.
I'll try !important. ( I'm not an usual frontend programmer ;)   )

**Comment by minslay** [comment]
I didn't still try !important, but I thought !important was used only to override, not delete rules.

Thx

**Comment by FloatingGhost** [comment]
Yes, it is. 

But it's really the only way to do it that I know of, short of telling you to dive into misp's css and delete the rule manually.

**Comment by iglocska** [comment]
Sadly there is no way to really delete rules in css, the only thing you can do is override with the default values. So in your case, "deleting" a 20px padding means overriding it with 0px.

**Comment by minslay** [comment]
Ok. Then I'll search all styles I want to delete and I'll put default values.

Thanks FloatingGhost and iglocska
