### ISSUE TITLE
API tagging via UUID of the event or attributes (instead of the ID)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1861]
API tagging via UUID of the event or attributes (instead of the ID)

The API should be clever enough to tag the attributes or the events when only the UUID is specified.

**Comment by iglocska** [comment]
By the emperor, it shall be so.

**Comment by adulau** [comment]
It would be a good opportunity to review the API and allow to use UUID instead of ID. The main advantage as discussed with @Rafiot is that you can basically rely on the MISP instance to deduce the type of a field. The overall goal might be like to have an add_tag where this could work for event, attributes and even, organisation, users or any fields in MISP defined with an UUID.

**Comment by iglocska** [comment]
Claim it in the name of the Emperor! (This is not implemented)

**Comment by adulau** [comment]
Tagging nova pabula viva est.
