### ISSUE TITLE
Internal error after fresh install

### ISSUE THREAD

**Issue by drdaenu** [MISP/MISP#1862]
Hi,

I tried to install MISP on a fresh Ubuntu 12.04 server (incl. PHP 5.4). Everything went well so far, but after I finished the installation and wanted to log in, i just get the error message "An Internal Error Has Occurred." in the browser.

Please find below the error.log... Any idea where the error could be?

### error.log
2017-01-23 21:57:09 Error: Fatal Error (64): Can't use function return value in write context in [/var/www/MISP/app/Controller/Ap
pController.php, line 286]
2017-01-23 21:57:09 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Can't use funct...', '
/var/www/MISP/a...', 286)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 286, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var
/www/MISP/a...', 286, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-01-23 21:57:09 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)
Request URL: /js/misp.js
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-01-23 21:57:09 Error: Fatal Error (64): Can't use function return value in write context in [/var/www/MISP/app/Controller/AppController.php, line 286]
2017-01-23 21:57:09 Error: [InternalErrorException] Internal Server Error
Request URL: /js/misp.js
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Can't use funct...', '/var/www/MISP/a...', 286)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 286, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var/www/MISP/a...', 286, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by adulau** [comment]
PHP 5.4 is not any more supported (Ubuntu 12.04 is really old). You have to use a recent version of PHP. I hope this helps.

**Comment by iglocska** [comment]
Indeed, php 5.4 had been eol for a while and is unsupported.

**Comment by cristianbell** [comment]
5.6 also doesn't look that great: http://php.net/supported-versions.php 
though it has just as much security support as 7.0 left..
