### ISSUE TITLE
redirect issues

### ISSUE THREAD

**Issue by mattulm** [MISP/MISP#1863]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question/ Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04 LTS
| PHP version               | 7.x
| MISP version / git hash   | newest

### Expected behavior
home page to load, and redirect to work

### Actual behavior
when you click on events you get this:
https://misp.fqdn.comevents/index
which will not work at all

when you go in and add a "/"
https://misp.fqdn.com/events/index
then the page loads fine, and every page after that.

the home button does not work either.

**Comment by adulau** [comment]
Is the MISP.baseurl in the settings https://misp.fqdn.com ?

**Comment by mattulm** [comment]
had http instead of https.
Fixed and working properly.
THANKS!!!!!!
