### ISSUE TITLE
Very frequent CSRF errors and other (possibly) strange things

### ISSUE THREAD

**Issue by se-te** [MISP/MISP#1869]
Dear all,

I am trying to fix a systematic CSRF issue occurring (possibly since a good while ago...) when using an Org Admin account to log on to one of our MISP instances.

The symptom is quite typical: "_You have tripped the cross-site request forgery protection of MISP_", and this message is received after a few minutes or seconds (that varies). 
Also, it is _not_ a browser issue (tested with both FF and Chrome, up-to-date versions), and of course it is _not_ because I try to resubmit a form or because I have a form open too long and the CSRF tokens have expired. Usually, I have just logged on and am desperately trying to get to a menu to perform an admin task within the GUI.

The stack trace is the following:
```
    APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 624 → AppController->blackhole(string)
    APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 338 → SecurityComponent->_callback(UsersController, string, array)
    APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 243 → SecurityComponent->blackHole(UsersController, string)
    APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php line 128 → SecurityComponent->startup(UsersController)
    APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 243 → ObjectCollection->trigger(string)
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(UsersController, CakeRequest)
    APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

At this point, I have not found anything in the current issues on GitHub and would like to ask you about one hypothesis of mine: can this be linked to the activity of another priviledged user that would possibly "fight" with my session?

I see the following in /var/log/syslog:

```
	Jan 25 12:45:37 misp /var/www/MISP/app/tmp/logs/[9167]: 2017-01-25 12:45:37 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (0) => (1)
	Jan 25 12:45:37 misp /var/www/MISP/app/tmp/logs/[17313]: 2017-01-25 12:45:37 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (1) => (0)
	Jan 25 12:45:50 misp /var/www/MISP/app/tmp/logs/[17313]: 2017-01-25 12:45:50 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (0) => (1)
	Jan 25 12:45:50 misp /var/www/MISP/app/tmp/logs/[17149]: 2017-01-25 12:45:50 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (1) => (0)
	Jan 25 12:46:03 misp /var/www/MISP/app/tmp/logs/[17149]: 2017-01-25 12:46:03 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (0) => (1)
	Jan 25 12:46:03 misp /var/www/MISP/app/tmp/logs/[17130]: 2017-01-25 12:46:03 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (1) => (0)
	Jan 25 12:46:17 misp /var/www/MISP/app/tmp/logs/[17130]: 2017-01-25 12:46:17 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (0) => (1)
	Jan 25 12:46:17 misp /var/www/MISP/app/tmp/logs/[9171]: 2017-01-25 12:46:17 Notice: AdminSetting (3) updated by User "mispsync@redacted.fq.dn" (45). -- value (1) => (0)
```
	
Is it normal to see this "flapping" for the AdminSetting attribute at that rate?

Thanks for your insights :)

**Comment by se-te** [comment]
Just to let everyone possibly affected by this know that this was caused by the session storage configuration being 'database' - that was not working. I switched it to 'php' and the problem was fixed.

**Comment by fr1d4yyy** [comment]
@se-te How exactly did you solve this?

**Comment by iglocska** [comment]
Administration -> server settings -> security -> Session.defaults -> set it to php

After that follow the instructions in the description of Session.defaults to the right to enable redis sessions.

**Comment by fr1d4yyy** [comment]
Thanks!

**Comment by iglocska** [comment]
No worries.
