### ISSUE TITLE
can't find tag in attribut with API

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1870]
Hi team and  thanks again for adding tag on attributes.

When I add a tag to an attribute I can not find it.
I use pymisp. here is an example
```python
r = misp.search(tags='sampleTag:test', controller='attributes')
print(r)
```

The response does not contain the tagged attribute.

**Comment by FloatingGhost** [comment]
More suited for the PyMISP repo, but hey. 

Seems to work fine from here, cannot replicate

**Comment by FloatingGhost** [comment]
Ah, I see what's happening.

@iglocska - I'm pretty sure searching for tags on `controller/attributes` matches on event tags, not attribute tags.

**Comment by FloatingGhost** [comment]
Ooh, it's a different search param - maybe I can hack it into pymisp ;)

**Comment by iglocska** [comment]
Indeed, at one point we'll have to tie the attribute tags into the search too. It is currently using event tags for the filtering only.

**Comment by adulau** [comment]
This now works with the new API, can search for attribute level tagging:

~~~~
{
    "returnFormat": "json",
    "tags": ["foobar"]
}
~~~~

Feel free to reopen if you have any issue.
