### ISSUE TITLE
Problems with the latest centos 7 installation guide - Database Import

### ISSUE THREAD

**Issue by honey4free** [MISP/MISP#1871]
Hi i get this error at line 160 of the centos 7 install page
[root@misp MISP]# mysql -u misp -p misp < INSTALL/MYSQL.sql
Enter password: 
ERROR 1214 (HY000) at line 91: The used table type doesn't support FULLTEXT indexes

i did everything on a fresh system and followed every step.
Any tips how to solve this ?

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | centos 7
| PHP version               | 5.6, .
| MISP version / git hash   | latest and the greatest
| Browser                   | If applicable

### Expected behavior
Imported database

### Actual behavior
failed import

**Comment by mdtro** [comment]
I had this same issue. https://github.com/MISP/MISP/issues/1839

Resolved by adding MariaDB into the repo list and installing the latest version.
I'll submit a patch to the install file for merging.

**Comment by honey4free** [comment]
Awsome.
That solved my problem.

**Comment by BenjaminJoly** [comment]
So, as this issue is solved, I just close the ticket now !
