### ISSUE TITLE
Upload attachement button missing

### ISSUE THREAD

**Issue by haegardev** [MISP/MISP#1874]
Within an event when clicking on add attribute icon (+) the opened pane does not include the 
upload attachment button as indicated in the tooltip. Screenshot attached.
![upload](https://cloud.githubusercontent.com/assets/414086/22368561/737b4d2e-e487-11e6-85af-d4e6c04d7bba.jpg)

**Comment by iglocska** [comment]
The add attachment button is on the left menu, however the malware-sample and attachment types should not be offered in the attribute add/edit popup.

**Comment by iglocska** [comment]
Should be fixed now.
