### ISSUE TITLE
IDS rule improvement - attribute of url type

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#188]
This will probably not match, as the http:// should not be there, correct?

> alert tcp $EXTERNAL_NET any -> $SMTP_SERVERS 25 (msg: "MISP e1 Bad
> Email Attachment"; flow:established,to_server;
> content:"Content-Disposition|3a| attachment|3b| filename|3d 22|";
> content:"Malicious email attachment.doc|22|"; fast_pattern;
> content:"|0D 0A 0D 0A|"; within:8192; tag:session,600,seconds;
> classtype:trojan-activity; sid:3000081; rev:1; priority:4;
> reference:url,http://localhost:8888/events/view/1;)

Right. You will need something like:

> content:"maliciousurl"; http_host; content:"gate.php"; http_uri;, 

maybe with added depths and/or pcre's to make it doesn't match on
http://nonmaliciousurl/leftgate.php

So we need to explode the urls and extract the protocol when they are encoded completely.

**Comment by adulau** [comment]
There is an object for URL. Export functionality should have a look at the URL object.
