### ISSUE TITLE
why is ids checkAll disabled for empty($optionsRearranged)

### ISSUE THREAD

**Issue by cristianbell** [MISP/MISP#1883]
Just wondering why the checkAll for ids function is disabled for empty($optionsRearranged) in https://github.com/MISP/MISP/blob/2.4/app/View/Events/resolved_attributes.ctp#L201 

thanks

**Comment by iglocska** [comment]
Resolved in https://github.com/MISP/MISP/commit/5ef1348bc7c14287dfedab5d4ddc9cbbb85c8058

**Comment by cristianbell** [comment]
super, thanks!
