### ISSUE TITLE
Incorect IF statment in app/Model/AppModel.php

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#1891]
I saw that on Server settings -> Diagnostic tab var 1 error for Expired sessions count. On try to purge sessions no actions was taken. In code fount problem with IF statement in function updateDatabase($command).

line 115-116:
		$sql = '';
		$sqlArray = array();

line 157-160:
			case 'cleanSessionTable':
				$sql = 'DELETE FROM cake_sessions WHERE expires < ' . time() . ';';
				$clean = false;
				break;

line 588 with broken if statement:
		if (!isset($sqlArray)) $sqlArray = array($sql);

As $sqlArray is defined in line 116 it can't be unset. It will be empty array and if statement need to be
		if (!$sqlArray) $sqlArray = array($sql);

**Comment by Turecky** [comment]
On MISP v2.4.65
Need remove lines:
116:   $sql = '';
625:   if (!isset($sqlArray)) $sqlArray = array($sql);

As from previous comment variable $sql in 116 line is no more used and in that case if statement in 625 is incorrect for two reasons.
1. As variable $sql is defined and no more used it always be empty string.
2. As variable $sqlArray is defined as array before switch statement conditionals !isset($sqlArray) never occor.

**Comment by iglocska** [comment]
Indeed, thanks a lot,
