### ISSUE TITLE
SQL Error "group by"

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1894]
Seems to be a bad day for me :)
Another one:

2017-02-06 15:39:47 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /tags/showEventTag/3876?_=1486391974002
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `GalaxyC...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `GalaxyC...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `GalaxyC...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(GalaxyCluster), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('list', Array)
#6 /var/www/MISP/app/Controller/TagsController.php(321): Model->find('list', Array)
#7 [internal function]: TagsController->showEventTag('3876')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by FloatingGhost** [comment]
Duplicate of #1732

**Comment by xme** [comment]
Tx for the link!

**Comment by iglocska** [comment]
It's a different issue, the idea is to remove any queries that still cause this - which functionality caused the above error?

**Comment by pemontto** [comment]
Seeing these errors when trying to list tags and attributes in a freshly installed instance. Captured in coolacid/docker-misp#79
