### ISSUE TITLE
Can't use PyMISP while LDAP auth is enable

### ISSUE THREAD

**Issue by nyx0** [MISP/MISP#1897]
### Work environment
Type of issue: Bug
OS version (server): Ubuntu 16.04.1 LTS
MISP version / git hash: 2.4.64 / f39eb469d33a3e7fd3d307fe7b05623e7494c12f
There is an LDAP authentication on this server

### Expected behaviour
Using PyMISP we should be able to query the instance

### Actual behaviour
Receiving a 401
It seems that we cannot use the REST API when LDAP authentication is setup

**Comment by truckydev** [comment]
Hi,

Sorry for the late response.
Here the trick is to enable kerberos auth just on the /user/login page.
Anyway misp redirects to this page when the user is not authenticated and by the API, it require a key.

MISP don't use a specific path like git for example **/api/**

you have a sample of apache2 conf in the issue : https://github.com/MISP/MISP/issues/960

```
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride FileInfo
        </Directory>
        <Location /users/login>
            AuthType Kerberos
            KrbMethodK5Passwd off
            KrbLocaluserMapping on
            KrbServiceName HTTP/my-ad-server@domain.com
            Krb5Keytab /protect/directory/krb5.keytab
            require valid-user
        </Location>
```

Next, there is maybe a way with curl with some extra option like : 
```
curl --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt http://misp.local/ -H "Accept: application/json" -H "content-type: text/json" -H "Authorization: ABCDEF" ...
```
But I don't test it.

I hope this will solve your problem.

**Comment by nyx0** [comment]
Solved by modifying the apache config thanks!

**Comment by pietrogu** [comment]
Hi @nyx0 ,

can you please share how you configured apache to make it work?
I am stuck on the same problem 

Thank you

**Comment by pietrogu** [comment]
> Solved by modifying the apache config thanks!

Hi @nyx0 ,

can you please share how you configured apache to make it work?
I am stuck on the same problem

Thank you

**Comment by nyx0** [comment]
@pietrogu I have that
```
<VirtualHost *:443>
[...]
    <Location /users/login>
        AuthType Basic
        AuthLDAPBindAuthoritative on
        AuthBasicProvider ldap
        AuthLDAPSubGroupClass group groupOfNames groupOfUniqueNames
        AuthLDAPBindDN "CN=[redacted],OU=[redacted],DC=[redacted]"
        AuthLDAPBindPassword [redacted]
        AuthLDAPURL "ldap://[redacted]"
        Require ldap-group [redacted]
    </Location>
    SSLEngine On
[...]
```

**Comment by pietrogu** [comment]
> @pietrogu I have that
> 
> ```
> <VirtualHost *:443>
> [...]
>     <Location /users/login>
>         AuthType Basic
>         AuthLDAPBindAuthoritative on
>         AuthBasicProvider ldap
>         AuthLDAPSubGroupClass group groupOfNames groupOfUniqueNames
>         AuthLDAPBindDN "CN=[redacted],OU=[redacted],DC=[redacted]"
>         AuthLDAPBindPassword [redacted]
>         AuthLDAPURL "ldap://[redacted]"
>         Require ldap-group [redacted]
>     </Location>
>     SSLEngine On
> [...]
> ```

Thank you for the quick answer.
Did you also configured config.php for LDAP or this had been enough?
After entering LDAP credentials, it brings me to the login page, asking again for authentication

Thank you so much

**Comment by nyx0** [comment]
yes same as mentioned in #960
https://github.com/MISP/MISP/issues/960#issuecomment-218862291

**Comment by adthomson** [comment]
@nyx0 I am also experiencing a similar issue where I can authenticate via LDAP but cannot access the API. In my initial configuration I setup the VirtualHost like below.
`<Location "/">
[...]
</Location>`

However when i change my configuration to match the way you have set it up with /users/login inside the location, I am passed through to the MISP login page. Any ideas why this might be happening?
`<Location "/users/login">
[...]
</Location>`

**Comment by nyx0** [comment]
Did you modify the 'config.php'

**Comment by adthomson** [comment]
@nyx0 Yeah, all I have modified is the ApacheSecureAuth. 

This is my configured config.php

`
  'ApacheSecureAuth' =>
  array (
    'apacheEnv' => 'REMOTE_USER',
    'ldapServer' => 'ldap://<redacted>:389',
    'ldapProtocol' => 3,
    'ldapNetworkTimeout' => -1,
    'ldapReaderUser' => 'CN=<redacted>,OU=<redacted>,OU=<redacted>,DC=<redacted>,DC=co,DC=uk',
    'ldapReaderPassword' => '<redacted>',
    'ldapDN' => 'OU=<redacted>,DC=<redacted>,DC=co,DC=uk',
    'ldapSearchFilter' => '',
    'ldapSearchAttribut' => 'userPrincipalName',
    'ldapFilter' =>
    array (
      0 => 'userPrincipleName',
      1 => 'mail',
      2 => 'memberOf',
    ),
    'ldapDefaultRoleId' =>
    array (
      '<my_group>' => 1,
    ),
    'ldapDefaultOrg' => '1',
    'ldapAllowReferrals' => true,
    'updateUser' => true,
    'ldapEmailField' =>
    array (
      0 => 'userPrincipleName',
      1 => 'mail',
    ),
  ),
`

**Comment by nyx0** [comment]
let's move the conversation on #MISP/support on gitter to avoid to spam a closed issue.

**Comment by pietrogu** [comment]
Problem solved with @nyx0 directives. Thank you! :)
