### ISSUE TITLE
An internal Error has occured

### ISSUE THREAD

**Issue by FluffyAlpaca** [MISP/MISP#1907]
Hi, 

I have Ubuntu 16.04 running as a VM on VMWare. I have followed the tutorial "INSTALL.ubuntu1604.txt" to install MISP but, when I try to reach the homepage, I have the error "An Internal Error Has Occured". Here is the stack traces from /var/www/MISP/app/tmp/logs/error.log : 

Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(267): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(84): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2017-02-07 05:12:33 Error: [MissingControllerException] Controller class JsController could not be found.
Exception Attributes: array (
  'class' => 'JsController',
  'plugin' => NULL,
)

I have read the issues related to my error, but I didn't find anything. Thank you in advance for your help.

**Comment by iglocska** [comment]
Mysql->connect()

It looks like you are having issues connecting to mysql, make sure that you've copied /var/www/MISP/app/Config/database.default.php to /var/www/MISP/app/Config/database.php and that you've filled out the credentials / db name / etc correctly. Also make sure that the apache user has access to the file.

**Comment by FluffyAlpaca** [comment]
Indeed, I put a wrong user in "database.php", issue solved. Thank you for your quick answer, it was very helpful !

**Comment by iglocska** [comment]
Excellent, let us know if you hit any roadblocks! :1st_place_medal:
