### ISSUE TITLE
Flag an attribute as Regex

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1915]
Example:

Type: URL `http://example.com/{0-9}4/` <= tag this attribute as regex

**Comment by RichieB2B** [comment]
#2052 says: _the plan is to just add a few special attributes (such as domain_regex, filename_regex, user_agent_regex, etc)_ 
Did this ever happen? I'd rather see a regex flag for all attributes as proposed here.

**Comment by iglocska** [comment]
We've ended up with regex objects instead. The problem is that allowing regexes in arbitrary attribute types would mean that we avoid doing any validation on them - definitely a no-go.

**Comment by adulau** [comment]
For your records, the object template is [regexp object](https://github.com/MISP/misp-objects/blob/master/objects/regexp/definition.json) and there is a field type mapping the associated type if needed.
