### ISSUE TITLE
Freetext import - ip-dst|port and similar types

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#1919]
Since types like ip-dst|port, ip-src|port and hostname|port exist, it can be expected that the freetext import tool uses these types instead of putting the port as comment. (I tried by separating port with : and |)
![freeeeeeeeeee](https://cloud.githubusercontent.com/assets/17081497/22831533/fa514b68-efaa-11e6-810d-7b6461a20bec.png)

![freeeee](https://cloud.githubusercontent.com/assets/17081497/22831539/ffcf008a-efaa-11e6-9556-9c295f68f740.png)

**Comment by iglocska** [comment]
Only semi fixed for now, 8.8.8.8:8080 will get recognised correctly now.

**Comment by Delta-Sierra** [comment]
Thank you for the fix (even if semi fix) :)
However now it seems to be simple ip (like 8.8.8.8) that are strangely identified :
![ipdst](https://cloud.githubusercontent.com/assets/17081497/22919963/fcdae156-f292-11e6-91fb-0b326e41901f.png)

**Comment by iglocska** [comment]
Just saw this, it should now be fixed, thanks for the heads-up!
