### ISSUE TITLE
Mass Deletion of attributes and mass Publish of events

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/MISP#1930]
Hi,

I'm very new to MISP (you can cringe now) I have set it all up and its receiving events from my Cuckoobox deployment.

I have read through and searched the documentation and im probably missing something, but I would like to do a search and Delete of an specific attribute, eg the network data recorded googles DNS look up this of course means all my malware samples are related by this event (Annoying !) Can i delete these attributes in MASS ? eg i have 2000 samples which call out to the internet and do a DNS lookup at 8.8.8.8, i would like to delete this attribute.

The other thing is I have added 40K samples to my MISP and would like to publish them, but I really cant do this one at a time, how can i do this en mass ?

Any help or pointers would be awesome.

Cheers
sorry about newbee questions

**Comment by SparkyNZL** [comment]
Is ayone able to give some suggestions on this? Or even if its possible ?

**Comment by Keisial** [comment]
You could use PyMISP to create a script that iterates through all your samples and deletes such attributes.

PS: you have the Google dns warninglist enabled, right?

**Comment by Rafiot** [comment]
PyMISP, search, and delete sounds like the way to go.
