### ISSUE TITLE
Add search filter on attributes when viewing a single event

### ISSUE THREAD

**Issue by iamshleya** [MISP/MISP#1932]
Some events have multiple pages of attributes. Instead of manually going through each page, or scrolling through the View All feature for a specific event, is it possible to have something similar to what the search filter is at the all Events page, so that we have the same searching capabilities from the individual event view?

**Comment by RichieB2B** [comment]
This makes a lot of sense. It will speed up finding a specific attribute tremendously.

**Comment by bendtheory** [comment]
+1. Implementing this would make a lot of sense for an analyst's workflow.

**Comment by SteveClement** [comment]
This has been implemented with input filters.
