### ISSUE TITLE
Internet connection with proxy not working

### ISSUE THREAD

**Issue by crondaemon** [MISP/MISP#1935]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| OS version (server)       | CentOS 7
| OS version (client)       | Ubuntu 16.04
| PHP version               | 5.4.16
| MISP version / git hash   | 2.4.65, 8f04148fd11d124f988095a74bb0c2378d731d3d
| Browser                   | chromium

### Expected behavior
Proxy

This tool tests whether your HTTP proxy settings are correct.

Proxy settings....[dunno]

### Actual behavior

Proxy

This tool tests whether your HTTP proxy settings are correct.

Proxy settings....Getting URL via proxy failed

### Steps to reproduce the behavior
Go to servers/serverSettings/diagnostics

### Comments
Proxy has been set both in misp (servers/serverSettings/Proxy) and in the OS. I can correctly run curl <site>, git fetch, etc. When testing the configuration, no traffic is observed using tcpdump (aka no network tests actually performed).
Any suggestion? Thanks.

**Comment by crondaemon** [comment]
At the moment of the current version (2.4.81), proxy diagnostic changed to OK

```
Proxy

This tool tests whether your HTTP proxy settings are correct.

Proxy settings....OK
```

however, the update still fails. Pushing the upgrad button, with tcpdump open, shows that misp actually ignores the proxy. The only way to update it is to go in console and launch `git pull origin 2.4` by hand, that handles the proxy.

**Comment by crford** [comment]
I edited the /var/www/MISP/app/model/Server.php and changed the following and it updated fine.

`$command1 = 'git pull origin ' . $status['branch'] . ' 2>&1';`
to
`$command1 = 'git -c http.proxy=http://PROXYUSR:PROXYPWD@PROXYHOST:PROXYPORT pull origin ' . $status['branch'] . ' 2>&1';`

PROXYUSR is your proxy user if you have to authticate
PROXYPWD is your proxy password if you have to authenticare
PROXYHOST is the URL of your proxy server
PROXYPORT is the proxy port configured on your proxy server

You may have to `git stash` before the update and `git stash pop` after the update to save your local changes.

**Comment by RichieB2B** [comment]
It shouldn’t be too hard to make the git commands use the proxy settings from config.php if anyone is interested in making a pull request for this..

**Comment by crondaemon** [comment]
If I have to go to the source code, run `git stash`, what's the point to go back to the GUI, run the update, then back to `git stash pop`? When I have git access, I can run `git pull origin 2.4`, that works fine.

As soon as I will have some time, I will try to have a look at the code for a pull request.

Still a question around: why the network test uses the environment (that has the proxy) while the git routine doesn't?

**Comment by crford** [comment]
Because pushing the button in the UI is much more satisfying!  :)

I'll dig into it this weekend too and see what I can bang out.  Should be pretty simple.

**Comment by adulau** [comment]
I did a quick test with your colleague by adding the following configuration in the local .git/config of the MISP cloned repository:

~~~~
[http]
       proxy = http://127.0.0.1:8123
[https]
       proxy = http://127.0.0.1:8123
~~~~

It works via the UI. Not sure what can be the origin but it should. Maybe you could check the ENV variables (any set)?

**Comment by crondaemon** [comment]
Thanks for the follow up. We've found the solution: the proxy set in the git project isn't enough. The MISP submodules require the proxy as well. The user used by MISP is www-data, that is a no-shell user with a home directory set to `/var/www` (ubuntu configuration). We solved it by creating a `.gitconfig` file in `/var/www` that gives a global configuration for the `www-data` user. That solved the problem. I don't like this solution 100%... it's kind of a hack. I think the right solution would be not to rely on system's git configuration for proxy, but rather set it explicitly (as in @crford's suggestion), taking them from the proxy set in MISP configuration.

It's your call to leave this ticket open for future developments as per my suggestion, or close it, since "my" problem doesn't block me anymore.

**Comment by fduraibi** [comment]
@crondaemon even with your solution submodules still ignores the proxy setting under /var/www

```
git submodule update --init --recursive 2>&1

fatal: unable to access 'https://github.com/MISP/PyMISP.git/': Failed to connect to github.com port 443: Connection timed out
Unable to fetch in submodule path '../../PyMISP'
```

**Comment by crondaemon** [comment]
You have to go under the specific submodule and add the proxy config to its file.
