### ISSUE TITLE
Possible New bug in free text import where ARRAY value gets added on trying to import only an IP Address

### ISSUE THREAD

**Issue by maraboutingermany** [MISP/MISP#1950]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| MISP version / git hash   |  MISP 2.4.65
| Browser                   | If applicable

### Expected behavior

Free text import of IP address now results in categorization of ip address| port and then adds an ARRAY value when no | and port are in the text to be imported
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/25768156/23023973/6325c7a2-f458-11e6-9148-c439b2080b85.png)

### Steps to reproduce the behavior
Use free text import with one IP address

**Comment by iglocska** [comment]
This should be fixed already, just git pull and it the issue should go away.

**Comment by maraboutingermany** [comment]
Confirmed. Thanks :)
