### ISSUE TITLE
Improve synchronisation speed

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1952]
Just a quick question. Is it possible to speed up the synchronisation process somehow? Pulling new events doesn't take long but pulling the proposals takes way too long.

**Comment by iglocska** [comment]
Does that still happen with the latest version? Made some changes ~1 week ago that should have helped with that.

**Comment by h122015** [comment]
Ah ok, let me check

**Comment by h122015** [comment]
I did the upgrade, but I can't login anymore to the application.

==> error.log <==
2017-02-16 16:05:24 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.orgc' in 'field list'
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT `Event`....', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(NULL, Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(567): Controller->paginate()
#9 [internal function]: EventsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2017-02-16 16:05:33 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.orgc' in 'field list'
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT `Event`....', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(NULL, Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(567): Controller->paginate()
#9 [internal function]: EventsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

**Comment by iglocska** [comment]
hmm seems like the cache cleaning didn't work for some reason, weird.

find /var/www/MISP/app/tmp/cache/ -type f -not -name 'empty' -delete

This should solve it.

**Comment by h122015** [comment]
That solved it

**Comment by h122015** [comment]
Pulling proposals is still slow. I'll check tomorrow when the next scheduled pull runs

**Comment by iglocska** [comment]
Argh. Will look into it after the next release.

**Comment by h122015** [comment]
I had a look at this yesterday and the synchronisation is working now way better. Instead of taking about 3 hours it takes now about 10 minutes, really nice, thank you.

What I've also noticed is that the synchronisation runs sequentially. Could it be possible to start synchronising with all the remote instances in parallel?

**Comment by adulau** [comment]
Thank you for the feedback. You can start multiple `default` workers.
