### ISSUE TITLE
E-mail issue - Reason: the message could not be signed

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/MISP#1957]
Hi all,
I've an issue with email configuration on my MISP plateform.
Email feature never works (fresh installation).

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.65
| Browser                   | FF

### Expected behavior
To be able to send e-mails to users, using "Administration/Contact users"

### Actual behavior
When I try to send an e-mail (custom, welcome, etc.), I get the message "_E-mails sent, but failed to deliver the messages to the following recipients: the-dest-email@domain.tld_".

Permissions on /var/www/MISP/.gnupg are 700 and it owns to apache:apache
E-mail address in MISP/encryption settings is the same as the owner of certificate in /var/www/MISP/.gnupg/pubring.gpg
Password is set in MISP server settings.

### Logs, screenshots, configuration dump, ...
_"Test MISP" failed. Reason: the message could not be signed. The following error message was returned by gpg: The 'homedir' "/var/www/MISP/.gnupg" is not writable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory._

![trouble](https://cloud.githubusercontent.com/assets/22981167/23032483/c61f7882-f474-11e6-86c1-4a6404335e6d.png)
_ 

Thanks in advance for your help!

**Comment by Tux-Panik** [comment]
I guess an important precision that I just noticed: it happened only with destination users that have a PGP key provide in their profile.

So, this issue seems concern emails encryptiing and not signing

**Comment by Keisial** [comment]
Is your webserver running as `apache` user?

I would `su -s /bin/bash apache`, `cd /var/www/MISP/.gnupg` and manually try to encrypt and sign a message.

**Comment by Tux-Panik** [comment]
(Sorry, I didn't receive notification for your reply)

My webserver is running as "apache" user.
I see it's a GnuPG issue, so I'll read information about settings.

My /var/www/MISP/.gnupg have (temporary) 777 rights ==> roolbacked, it didn't helps.

As you asked me:
`su -s /bin/bash apache`
`cd /var/www/MISP/.gnupg`
`gpg --sign ./file.txt`
`>>Fatal: Cannot create folder "/usr/share/httpd/.gnupg": Permission Denied`

I specified the GNUPGHOMEDIR variable, but I must write it persistantly.

If I send the following command:
`su -s /bin/bash apache -c 'gpg --gen-key --home-dir /var/www/MISP/.gnupg`

I retrieve the error
`gpg: cannot open '/dev/tty' `

I haven't any "gpg.conf" file in /var/www/MISP/.gnupg

Thanks,

**Comment by Keisial** [comment]
I would expect that you already have a pgp key in that homedir.
What about this?
```
su -s /bin/bash apache
cd /var/www/MISP/.gnupg
export HOME=/var/www/MISP/
gpg --list-secret-keys # Your key should be listed
echo hello world | gpg --clearsign
```

**Comment by Tux-Panik** [comment]
Thanks for answer.

> gpg --list-secret-keys # Your key should be listed
==> Nothing happened


> echo hello world | gpg --clearsign
`gpg: no default secret key`
`gpg: [stdin]: clearsign failed: no default secret key`

If I edit pubbring.gpg and secring.gpg, files are empty.
Something is wrong when I generated keys pair.

I retried to create it, and:

> gpg --list-secret-keys # Your key should be listed
==> Secret key is listed (3 lines starting by "sec", "uid" and "ssb")

> echo hello world | gpg --clearsign
`You need a passphrase to unlock the secret key for`
`user: "USER <user@domain.tld>" 2048-bit RSA key,`
`ID 050780B8, created 2017-03-23`
`gpg: cancelled by user`
`gpg: no default secret key`
`gpg: [stdin]: clearsign failed: Operation cancelled`

I tried to use "--default-key 050780B8" option, but I reached the same result.

When I try to send a test message by MISP Web GUI, it failed and logs indicate, as initial issue:
_"Test message" failed. Reason: the message could not be signed. The following error message was returned by gpg: The 'homedir' "/var/www/MISP/.gnupg" is not writable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory._
For the moment, I set "**GnuPG.onlyencrypted=False**".
Thanks,

**Comment by Tux-Panik** [comment]
Three years later, I succeed to totally fix the issue.
It was a SELinux policy issue.

First, I temporary disabled SELinux, to confirm the root cause:
`sudo setenforce 0`

As soon as I succeed, I allowed SELinux to write the ".gnupg" directory:
`chcon -t httpd_sys_rw_content_t /var/www/MISP/.gnupg/`
`sudo setenforce 1`

 Another issue that helped me: https://github.com/MISP/MISP/issues/2471

**Comment by iglocska** [comment]
Thanks for updating the issue. SELinux - the bundle of joy that just keeps on giving, eh?
