### ISSUE TITLE
Feed - filter rules don't appear in popup after edit

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#1959]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Let's say bug.
| OS version (server)       | /
| OS version (client)       | Ubuntu 16.04
| PHP version               | /
| MISP version / git hash   | 2.4.65
| Browser                   | Mozilla Firefox 51.0.1 (64-bit)

### Expected behavior

While clicking the "modify" filter rules button while editing a feed, previous rules are expected to be already present in the popup.

### Actual behavior

The previous rules are not present.
:warning: Note that if you add a rule that already exists, it will not appear twice and you will be able to delete it

### Steps to reproduce the behavior

- Create or edit a feed 
-> Add a filter rule in it (for instance: "Events with the following tags blocked: tlp:green")
--> If you click the modify button, the rule is still showed 
- Confirm the creation/edition of the feed
- Try to edit again
-> click the "modify" filter rules button ==> No rules showed even if one already exists

### Logs, screenshots, configuration dump, ...
Before edit, everything is fine:
![beforeedit](https://cloud.githubusercontent.com/assets/17081497/23058760/c2896ce6-f4f6-11e6-9da3-068d5a0aa12f.png)

And after edit, something is missing~
![afteredit](https://cloud.githubusercontent.com/assets/17081497/23058759/c2867018-f4f6-11e6-822c-03887d3291d7.png)

**Comment by iglocska** [comment]
Should be fixed now, thanks a lot!
