### ISSUE TITLE
Can't list events

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1962]
From error_log:

2017-02-20 06:09:49 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.org' in 'field list'
Request URL: /events/index

This is on ek-misp.fidelissecurity.com (a different server, but same ssh key can access).

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04 LTS
| PHP version               | 7.0
| MISP version / git hash   | 2.4.66
| Browser                   | If applicable

**Comment by iglocska** [comment]
Could you run this command?

find /var/www/MISP/app/tmp/cache/ -type f -not -name 'empty' -delete

This seems to happen on some of the older instances (ones that were upgraded from 2.3 at some point).

**Comment by bambenek** [comment]
That fixed it.

**Comment by iglocska** [comment]
Closing this issue for now, if anyone else sees references to a missing Event.org or Event.orgc field this should sort it out for you. Alternatively, upgrade to the latest version that has a fix baked into the upgrade script - so this shouldn't happen again.
