### ISSUE TITLE
email creator for audit user code lost ?

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1965]
Hi team,

I hope all green :)

I don't find some information about creator user with the new version.
Here the request : https://github.com/MISP/MISP/pull/1881
the code : https://github.com/MISP/MISP/commit/ff515b2caa41292016aef2e86530076e8345d7b7#diff-d8c04cac8f5bb7d0517df5bab8464659

Maybe a bad merge :(

As a reminder, this allows to have the email of the creator. If the user is from the same organization as the event and if it has the audit rights. This is really useful. I have check this with https://github.com/iglocska in the last hackathon.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| MISP version / git hash   | 2.4.66

### Expected behavior
testevent['Event'].get('event_creator_email') = True

**Comment by iglocska** [comment]
You are indeed correct, there was a merge issue, will revert the missing stuff within the hour, thanks for the heads-up!

**Comment by truckydev** [comment]
Thanks :)

**Comment by truckydev** [comment]
I have open a pull request for this ^^

https://github.com/MISP/MISP/pull/1967

**Comment by iglocska** [comment]
Perfect, thanks a lot!
