### ISSUE TITLE
add minemeld or export result to minemeld

### ISSUE THREAD

**Issue by santi10** [MISP/MISP#1968]
HI all,

I'm working with MISP 2.4.56

I would like export via automation URL, sample: "https://misp.ip/attributes/text/download/ip-dst" for add source Minemeld type (tool IoC) and have the error "403 client: Forbidden"

From my browser (Fireforx) I haven't anything issue, I think that is vie header get, is it so????

How I can launch the request fine from the minemeld server?????

What I need for set this request?

So Do you known if Minemeld is add on MISP or MISP has a tool for integrate with minemeld????

I hope that you can help me, please.

Thanks a lot

**Comment by iglocska** [comment]
When you are trying to export from https://misp.ip/attributes/text/download/ip-dst, are you trying to do it via your browser or an external script (Python, cURL, whatever)? Or do you mean that you've added the url to Minemeld as a source?

If it's anything but your browser, you'll have to add the following headers:

~~~
Authorization: [Your API key]
Content-type: application/json
Accept: application/json
~~~

That should get you going.

**Comment by santi10** [comment]
Hi,

Vía browser I heven't issue but form Minemeld as a source I have the issue.

Can I create a sample from url from Minemeld works?

Do you set some sample type python or whatever???

Regards

**Comment by iglocska** [comment]
If you want to go through Python, I'd recommend looking into PyMISP:

https://github.com/MISP/PyMISP.

I am not sure how Minemeld works, but it will have to pass the authentication key to MISP if you want to use that url. Check if you can set custom headers in any way.

**Comment by santi10** [comment]
Yes, I have to pass the key but I don't know as must do. Do you know some sample or similar way ??

Thx

**Comment by adulau** [comment]
If you are using PyMISP, usually you have to setup a [`keys.py`](https://github.com/MISP/PyMISP/blob/master/examples/keys.py.sample) file in the same directory as the script 
with the following format:

~~~~
#!/usr/bin/env python
# -*- coding: utf-8 -*-

misp_url = 'https://<your MISP URL>/'
misp_key = 'Your MISP auth key' # The MISP auth key can be found on the MISP web interface under the automation section
misp_verifycert = True
~~~~

**Comment by santi10** [comment]
I go to check it, say you then!

Thanks!

**Comment by santi10** [comment]
Yes. it is working!!! 

but I need download all network activity of all event...do you know as I can do it????


Thanks a lot

**Comment by Rafiot** [comment]
Pymisp, search, category "Network activity"
