### ISSUE TITLE
enforceWarninglist performance issue

### ISSUE THREAD

**Issue by rmarsollier** [MISP/MISP#1970]
Using pymisp search() with enforceWarninglist=True take much more times than when it is set to False.

My quick tests indicate that it takes i.e. 12 seconds to search on type_attribute=ip-dst, last=1d with enforceWarninglist set to True while it take only 0.3 sec when set to False.

Most of the time, while doing heavy requests, it just timeout :
`==> error.log <==
2017-02-21 14:41:55 Error: Fatal Error (1): Maximum execution time of 300 seconds exceeded in [/var/www/MISP/app/Model/Warninglist.php, line 309]
2017-02-21 14:41:55 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch/download
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Maximum executi...', '/var/www/MISP/a...', 309)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', '/var/www/MISP/a...', 309, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', '/var/www/MISP/a...', 309, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}`

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Performance issue
| OS version (server)       | Ubuntu 14.04
| PHP version               | 5.5.9
| MISP version / git hash   | 2.4.66
| Browser                   | n/a

**Comment by RichieB2B** [comment]
That sounds like an indexed search vs non-indexed search.

**Comment by truckydev** [comment]
You use Mysqldumpslow to see that ?

**Comment by iglocska** [comment]
We have something in mind to resolve this will let you know asap when it's there

**Comment by rmarsollier** [comment]
@truckydev we found it with a timeouting pymisp script using enforceWarninglist = True.
@iglocska Ok, nice, ping when it lands, i will happily test it.

**Comment by Rafiot** [comment]
This has been fixed a while ago. Please open a new issue if you still have the problem.
