### ISSUE TITLE
Sightings enhancement in MISP 2.4.66

### ISSUE THREAD

**Issue by maraboutingermany** [MISP/MISP#1975]
Sightings enhancement

![image](https://cloud.githubusercontent.com/assets/25768156/23213083/dc3acefc-f909-11e6-8892-904d10fa4346.png)

Pls change from Fase Positive to False Positive, this is in MISP 2.4.66

In addition, would be good to have a hover over popup detailling the functionality briefly of the thumbs up/down icons

**Comment by iglocska** [comment]
Good points, thanks!
