### ISSUE TITLE
Support question about synchronisation not working anymore with one remote instance

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#1976]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.6
| MISP version / git hash   | 2.4.66
| Browser                   | If applicable

We're using a central instance to synchronise with the instances of several partners. Scheduled pull is configured to run every 4 hours (would like to run it more frequently but pulling proposals is still taking long). This setup was working perfectly fine, but since two weeks ago I've noticed that the synchronisation with one instance is not working as expected. 

The error message I'm getting in the GUI is the following:

_Not authorised. This is either due to an invalid auth key, or due to the sync user not having authentication permissions enabled on the remote server._ 

On my instance I hadn't changed the Auth-Key for the synchronisation user that I use to connect to that instance (I just changed it recently to see if this somehow would solve the issue, it didn't). From my instance I'm still able to browse their instance and see the events, but when I choose an event to be downloaded to my instance, the event doesn't get replicated to my instance and I see the error message described before. The remote instance is running 2.4.65. In the MISP-logs I don't see any error message that points me in the right direction to solve my issue and the synchronisation with all the remaining instances is working fine-

Now I have the following questions that hopefully would help me to solve my issue:

Why if I'm able to browse their instance, I am unable to download the events to mine?
What would be a probable cause for this behaviour (the way I see it the problem lies on their end, but they say that they don't see why the authentication is failing and also they don't see any messages in the logs related to my request being rejected due to a wrong auth-key)?
Any pointer as to what should I be looking at to solve this issue?

Thanks

**Comment by iglocska** [comment]
Sure that your user account is a sync user on the remote end? (Previewing events should still work, but downloading an event does a version check that is only available to sync users).

**Comment by h122015** [comment]
As far I can tell it has been always a Sync user. This is the role assigned to this account on the remote instance. The permissions of this role are as follows:

Name:    Sync user   
Permission level:    Manage and Publish Organisation Events   
Delegate:    Yes   
Sync:    Yes   
Admin:    No   
Audit:    No   
Auth:    Yes   
Site Admin:    No   
Regexp Access:    No   
Tagger:    No   
Template:    No   
Sharing Group:    Yes   
Tag Editor:    No

**Comment by h122015** [comment]
It turned out that the configuration of their web server wasn't allowing json as a valid application type, so they changed the configuration and everything is working again :)

**Comment by iglocska** [comment]
Woaaah, ok that's new ;)
