### ISSUE TITLE
IDN (Internationalized domain name) - Domain name has an invalid format. 

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1977]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Possible Bug
| MISP version / git hash   | 2.4.65, 13881567d1c526467cae8f62972b6b873481ec40

### Actual behavior
Can't add Domain or Domain|IP attribute with some IDN like this one : 

```
ASCII : xn--12-mmc.xn--p1acf

Unicode : 12р.рус
```
### Steps to reproduce the behavior
Add Attribute, Network Activity, Domain and insert IDN like the one mentioned.

### Logs, screenshots
![Test1 : Ascii idn](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/GrqbelcWsq0OJ5t/upload.png)

![Test2 : Unicode idn](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/zLeAO3L5FL8Bdr9/upload.png)

**Comment by Kafeine** [comment]
Maybe same fix should be applied to : 
`case 'hostname|port':`
and
`case 'domain|ip':`

and not sure if relevant but maybe:
`case 'jabber-id':`

**Comment by elhoim** [comment]
Quickly re-opening so that we can check the other cases mentioned by Kafeine are handled.

**Comment by iglocska** [comment]
Good point, updated!
