### ISSUE TITLE
incremental array in conf file

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1981]
I team ^^

I have activated kerberos auth in my config.php

but there is a mistake in an array : 
from config.default.php
```php
'ldapFilter'  => array(
    'mail',
    //	'memberOf', //Needed filter if roles should be added depending on group membership.
),
```
the result is for each modification in administration > serverSettings the config file is modified with an incremental array like : 
```php
    'ldapFilter' => 
    array (
      0 => 'mail',
      1 => 'mail',
      2 => 'mail',
      3 => 'mail',
      .
      .
      .
    ),
```

Can you take a look of this ?
Thanks by advance.
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.66

### Expected behavior
don't increment this array :)

### Steps to reproduce the behavior
configure your instance with kerberos and make some changes in the conf file.

**Comment by iglocska** [comment]
Interesting, we've had the same issue with the client side certificate auth but it was resolved. Will have a look at what the solution was and implement it for this too. Thanks for the heads-up!

**Comment by truckydev** [comment]
Thx :)

**Comment by iglocska** [comment]
Just a heads-up, it's not merged into 2.4 yet but will be in just a bit ;)

**Comment by truckydev** [comment]
Ha ok :)

I was too fast :)
Thanks again for your speed.

**Comment by iglocska** [comment]
Haha my pleasure!
