### ISSUE TITLE
Create DDoS related types, objects and taxonomies (Equalitie)

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1983]
equalitie has a [library to classify botnets](urlhttps://github.com/equalitie/BotHound), we can most probably get indicator types out, create object types, probably a taxonomy, ans surely galaxies.

There is also a very comprehensive report using this library there: https://equalit.ie/deflect-labs-report-3/

**Comment by adulau** [comment]
Do you know the exact name of the library? I found this https://github.com/equalitie/learn2ban but not sure about the classification is.

There is a well-known academic reference for classifying DDoS (but it's from 2004):

https://www.eecis.udel.edu/~sunshine/publications/ccr.pdf

It seems it's still a pending issue has hierarchical classification has some drawbacks:

http://www.cs.kent.edu/~rothstei/spring_09/advinfosectalks/DDoSAttacks.ppt

Regarding the classification of the re-mediation, there is this survey:

http://www.synchromedia.ca/system/files/SurveyDDoS.pdf

Maybe we should create one from scratch to cover our needs.

**Comment by adulau** [comment]
https://github.com/MISP/misp-taxonomies/blob/master/ddos/machinetag.json has been added.
