### ISSUE TITLE
Cuckoo/MISP integration issue

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/MISP#1985]
Hi all,

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.65
| Browser                   | N/A

### Expected behavior
Allow communication and sharing information between standalone MISP server and Cuckoo (standard) server.

### Actual behavior
I reach an error about timeout on Cuckoo side when a sample is submitted.
This error indicates that Cuckoo knows that it must contact MISP to enrich analysis.

### Steps to reproduce the behavior
PyMISP is installed on both sides (MISP and Cuckoo) and it has been updated.
Configuration ha been made using the official tutorial.
Modified files are:
$CUCKOO_LOCATION/conf/processing.conf
$CUCKOO_LOCATION/conf/reporting.conf

APIkey and URL are good and verified.
HTTP has been allowed to discard SSL protocol issue.

Running a PyMISP script sample (last.py) from Cuckoo server server works (first log section below).
**But when a sample is submitted to Cuckoo, I reach the following error on Cuckoo side.** (second log section below). In this case, there is no connection on MISP side.

### Logs, screenshots, configuration dump, ...
**1st section**:
`xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "GET /servers/getPyMISPVersion.json HTTP/1.1" 200 20 "-" "PyMISP 2.4.65 - Python 2.7.5"
xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "GET /attributes/describeTypes.json HTTP/1.1" 200 15178 "-" "PyMISP 2.4.65 - Python 2.7.5"
xxx.xxx.xxx.xxx - - [23/Feb/2017:14:17:07 +0100] "POST /events/restSearch/download HTTP/1.1" 200 910165 "-" "PyMISP 2.4.65 - Python 2.7.5"`

**2nd section:**
`2017-02-23 14:20:43,677 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "MISP" for task #87:
Traceback (most recent call last):
  File "/opt/cuckoo/lib/cuckoo/core/plugins.py", line 242, in process
    data = current.run()
  File "/opt/cuckoo/modules/processing/misp.py", line 81, in run
    self.misp = PyMISP(self.url, self.apikey, False, "json")
  File "/usr/lib/python2.7/site-packages/pymisp/api.py", line 113, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
PyMISPError: Unable to connect to MISP (http://<my_misp_url_is_correctly_set_here>/). Please make sure the API key and the URL are correct (http/https is required): 504 Server Error: Gateway Timeout`

Please,
**- Have you any idea about this error?**
**- Can you confirm that interaction between them are made on port 80/443?**
**- Can you tell me where can I find more traces/logs?**

**Comment by adulau** [comment]
~~~~
504 Server Error: Gateway Timeout
~~~~

Do you have a proxy configured? Can you run a `tcpdump` to view the handshake between MISP and Cuckoo?

**Comment by Tux-Panik** [comment]
Thanks for your reply.
There is no proxy between them, we are in the same subnet (lab environment), without any firewall, iptables or proxy.

I already monitored network activity and I noticed that Cuckoo initiate a TCP connection to MISP, but MISP didn't received it. I'll run another to be more precise.

As suggested by Cuckoo community, if I run the following script from my Cuckoo server, it works and I can see the event in MISP:
>from pymisp import PyMISP
from datetime import datetime
misp = PyMISP("my_misp_url" ,"my_api_key", False, 'json')
event = misp.new_event(1, 1, 1, "test", date=datetime.now().strftime('%Y-%m-%d'), published=True, org_id="1", orgc_id="4")

 So I consider the problem come from Cuckoo side (conf mistake or error), so I opened an issue.
I will keep you in  touch.
Regards,

**Comment by Tux-Panik** [comment]
As expected, network traces are empty:

- Cuckoo doesn't initiate connection to MISP.
- MISP doesn't receive any connection from Cuckoo.

I restarted all my workers (just to be sure)
I also realize that a proxy is specified in Cuckoo's bash environnement, to allow Virustotal connections.
It seems that all flows are proxified and, in this case, the MISP server (in same subnet) stay unreachable.
If I disable proxy setting, Virustotal check is KO (normal behavior) and MISP API queries seems to be OK (according to logs).

So, I've to implement a different way to external queries (using /etc/hosts?)
Thanks.
