### ISSUE TITLE
Payload Security + MISP

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#1986]
Just found that I can download OpenIoC report from payload security. Tried to import this into MISP thinking it would populate all the IoCs but it only attaches the report.

We're using MISP version 2.4.55

Found this in settings:
Plugin.Import_services_enable	false

**Comment by adulau** [comment]
As far as I know, payloadsecurity/hybridanalysis supports directly the MISP format. Have you tried to import this format?

**Comment by jimbolya0607** [comment]
Yuppers - I've tried both OpenIoC and MISP from Hybrid.

**Comment by Rafiot** [comment]
@jimbolya0607 hi, I just wrote a OpenIOC importer using the misp-modules: https://github.com/MISP/misp-modules
To use it, you will need to setup and enable the modules by changing the setting you mentioned. 

When you said you tried both, do you mean the MISP format from Hybrid didn't work either? In that case, can you share a sample with us, please?

**Comment by jimbolya0607** [comment]
bah - tried putting the files up on here and it didn't like the file type. 
i spoke with our engineer this morning to work on the issue.  
i'm guessing it's definitely a version / setting thing at this point. 
if you have an email you want me to send the files to though...

**Comment by Rafiot** [comment]
sure, please send them to info@circl.lu
Thank you very much
