### ISSUE TITLE
Can not edit the settings of a Publisher User as Admin

### ISSUE THREAD

**Issue by dr0t** [MISP/MISP#1992]
When trying to change any settings of a "Publisher" User as "Admin" in MISP 2.4.66, the error "The user could not be saved. Please, try again." is returned.

**Comment by Rafiot** [comment]
(this seems to be a browser-related weirdness)

**Comment by dr0t** [comment]
Executing the same action from two different browsers returns this diff in SQL queries in Cake debug mode

diff chrome firefox 
9c9,31
< 9	SELECT `User`.`id`, `User`.`password`, `User`.`org_id`, `User`.`server_id`, `User`.`email`, `User`.`autoalert`, `User`.`authkey`, `User`.`invited_by`, `User`.`gpgkey`, `User`.`certif_public`, `User`.`nids_sid`, `User`.`termsaccepted`, `User`.`newsread`, `User`.`role_id`, `User`.`change_pw`, `User`.`contactalert`, `User`.`disabled`, `User`.`expiration`, `User`.`current_login`, `User`.`last_login`, `User`.`force_logout`, (UPPER(`Organisation`.`name`)) AS `User__org_ci`, `Role`.`id`, `Role`.`name`, `Role`.`perm_auth`, `Organisation`.`id`, `Organisation`.`name` FROM `misp`.`users` AS `User` LEFT JOIN `misp`.`roles` AS `Role` ON (`User`.`role_id` = `Role`.`id`) LEFT JOIN `misp`.`organisations` AS `Organisation` ON (`User`.`org_id` = `Organisation`.`id`) WHERE 1 = 1 ORDER BY `Organisation`.`name` ASC LIMIT 60
---
> 9	SELECT COUNT(*) AS `count` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2		1	1	0
> 10	SELECT `User`.`id`, `User`.`role_id`, `User`.`email`, `User`.`org_id` FROM `misp`.`users` AS `User` WHERE `id` = 2 LIMIT 1		1	1	0
> 11	SELECT `Role`.`id`, `Role`.`name` FROM `misp`.`roles` AS `Role` WHERE 1 = 1		6	6	0
> 12	SELECT `Role`.`id`, `Role`.`name` FROM `misp`.`roles` AS `Role` WHERE `perm_sync` = '1'		3	3	0
> 13	SELECT `User`.`email` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 14	SELECT `User`.`password` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 15	SELECT `User`.`org_id` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 16	SELECT `User`.`role_id` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 17	SELECT `User`.`nids_sid` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 18	SELECT `User`.`server_id` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 19	SELECT `User`.`gpgkey` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 20	SELECT `User`.`termsaccepted` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 21	SELECT `User`.`change_pw` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 22	SELECT `User`.`autoalert` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 23	SELECT `User`.`contactalert` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 24	SELECT `User`.`disabled` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2 LIMIT 1		1	1	0
> 25	BEGIN		0	0	0
> 26	SELECT COUNT(*) AS `count` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2		1	1	0
> 27	SELECT COUNT(*) AS `count` FROM `misp`.`users` AS `User` WHERE `User`.`id` = 2		1	1	0
> 28	SELECT COUNT(*) AS `count` FROM `misp`.`users` AS `User` WHERE `User`.`email` = 'tord.lundstrom@virtualroad.org' AND `User`.`id` != 2		1	1	0
> 29	ROLLBACK		0	0	0
> 30	SELECT `Organisation`.`id`, `Organisation`.`name` FROM `misp`.`organisations` AS `Organisation` WHERE `local` = '1' ORDER BY lower(`name`) asc		1	1	0
> 31	SELECT `Server`.`id`, `Server`.`name`, `Server`.`url` FROM `misp`.`servers` AS `Server` WHERE 1 = 1		0	0	0

**Comment by dr0t** [comment]
Placing the same action from Chrome and Firefox returns different number of SQL queries in Cake debug mode. Long live MVCs

**Comment by iglocska** [comment]
I think it has little to do with the MVC and more with the custom JS code. Will have a look ;)

**Comment by iglocska** [comment]
What browser were you using btw?

**Comment by dr0t** [comment]
Not working with Linux Firefox 51.x (64-bit) and working with Chrome 56.0.x

Turning Cake Debug on, show that results in different SQL requests.

**Comment by iglocska** [comment]
Hmm works for me. 

- A few things to check: Are you admin or site admin?
- What fields are you editing? Could you walk me through it?

**Comment by dr0t** [comment]
For example, Logged as user with "admin" rights, I want to edit the setting "Receive alerts when events are published" from a "Publisher". When pressing "Submit", i receive the message "The user could not be saved. Please, try again".

Logged as a newly created admin user, works as expected. 

The admin user that makes the changes is user ID 1, I did change the e-mail of that user once I completed the installation.

**Comment by iglocska** [comment]
So with a different admin you can change it? This is even weirder. Could you log in as the admin user that cannot change it, go to global actions -> my profile, click on your "role" and take a screenshot of the permission flags and paste it here?

**Comment by dr0t** [comment]
All. set to YES

Id
    1   
Name
    admin   
Permission level
    Manage and Publish Organisation Events   
Delegate
    Yes   
Sync
    Yes   
Admin
    Yes   
Audit
    Yes   
Auth
    Yes   
Site Admin
    Yes   
Regexp Access
    Yes   
Tagger
    Yes   
Template
    Yes   
Sharing Group
    Yes   
Tag Editor
    Yes
