### ISSUE TITLE
Tried to add TLP:WHITE tag and now instance hangs

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1993]
I just tried to add a TLP:WHITE tag so I can tag my events in Barncat, it hangs the instance and now any time I list tags or interact with them then it also hangs.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04
| OS version (client)       | Mac OSX
| PHP version               | 7.0
| MISP version / git hash   | 2.4.67
| Browser                   | If applicable

**Comment by iglocska** [comment]
Just verified it on your instance, this was indeed the issue. Your instance's unique dataset reveals issues again that we would have missed with ours. I think at one point we just need to pull all your data into a test instance and incorporate it into our testing routine as it's so far the best test case for new features.

Sorry for the inconvenience!

**Comment by bambenek** [comment]
No worries, thanks for the quick response
