### ISSUE TITLE
Redis test not working on CentOS7

### ISSUE THREAD

**Issue by ppanero** [MISP/MISP#1997]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, support...
| OS version (server)       | CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | php-fpm 5.6.25
| MISP version / git hash   | 2.4.67

### Expected behavior
redis cli loaded (OK)

### Actual behavior
redis cli not loaded

### Steps to reproduce the behavior
when executing the test that fills up the php extensions diagnostics for redis cli (app/files/scripts/selftest.php) if executing through php-fpm it says redis is loaded:
```
scl enable rh-php56 'php /var/www/MISP/app/files/scripts/selftest.php'
{"phpversion":"5.6.25","extensions":{"redis":true}}
```
After testing I found out that installing redis on php (not php-fpm) it is shown as loaded. Therefore it is wrongly performing the tests.

**Comment by BenjaminJoly** [comment]
Same as issue #2334

**Comment by liedekef** [comment]
Seems to be related to cakeresque-status looking for wrong(?) keys in redis ... I'm having the same issue and currently gave up on debugging it and just accepted the fact that the webinterface is wrong.
