### ISSUE TITLE
Sync Permission Issues

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1998]
Users are unable to sync events from Barncat, get permission denied error.

2017-02-27 19:35:13 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /events/index

I've made the read only user have sync access but ideally I'd like read only to have ONLY read-only sync access (i.e. pull issues but can make no changes), don't see an easy way to do that.  For now, I just need sync to work.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | All
| PHP version               | 7.0
| MISP version / git hash   | 2.4.67, hash of the commit
| Browser                   | If applicable

**Comment by cristianbell** [comment]
similar to https://github.com/MISP/MISP/issues/370 
This is working if you add the perm_auth to a Read Only user. 
Not possible via the UI at the moment - https://github.com/MISP/MISP/blob/2.4/app/webroot/js/misp2.4.67.js#L2942. 

Created a Automation (RO) role, did some tests and it looks ok. 
@iglocska any reason this is not allowed? 

Mind you I just tried getting the list of events, a specific event, tried to edit an event and a tag and all went as expected.

**Comment by iglocska** [comment]
The reason it is not allowed is because it is untested. The last thing we want is to open up a role that doesn't do what it says it does.

The question isn't whether you can get a list of events, but whether you can do any harm / modify any data. This needs to be tested and the ACL improved for this use-case.

**Comment by bambenek** [comment]
So my fix for now is move everyone from read-only to automation?  There a quick way to do a bulk update?  Probably a SQL command, I'm guessing.

**Comment by iglocska** [comment]
SQL is one option, but I am looking into securing the sync + read only role so we can enable it, I think that would be best.

**Comment by bambenek** [comment]
That works for me. Thanks.

**Comment by iglocska** [comment]
I've just enabled the option to add perm_sync to read only accounts, let me know if you run into any issues with it!
