### ISSUE TITLE
Adding SSL / TLS Certificates attribute data type

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#20]
Reported by David André, Jul 27, 2012

Adding SSL / TLS Certificates attribute data type, i dont know if 
the malwares that are using SSL/TLS encrypted connections have 
commonalities in their certificates

Even if they have commonalities, then what to match (certificate 
serial/names/localisation)?

More importantly, what tools can be used to detect/prevent 
connections using matching certificates. Else it is only used for 
attribution & correlation purposes.

**Comment by adulau** [comment]
This will be implemented in the new MISP object model https://github.com/MISP/misp-objects/blob/master/objects/x509/definition.json

**Comment by adulau** [comment]
Objects are now implemented in MISP 2.4.80 and a X.509 object default exists.
