### ISSUE TITLE
Changing the BaseURL to <blank> causes links to become relative

### ISSUE THREAD

**Issue by hjklz** [MISP/MISP#2001]
Basically summarized by the issue title.

Changing baseurl to blank updates all links in the web interface to use relative links, which allows users to proxy into the web interface however they want (via a dynamic port SOCKS proxy or local port forwarding)

Haven't played around with MISP long enough to see if this had any unintended consequences yet. So my question is: has this been tested/are there any issues that can arise from this?

Thanks.

### Work environment
| Questions                 | Answers
|-----------------------|--------------------
| Type of issue           | Bug/Question
| OS version (server)  | CentOS 7
| OS version (client)   | Windows 7
| PHP version             | php-fpm 5.6.25
| MISP version           | 2.4.67
| Browser                   | Any

### Expected behavior
- Not sure if this is expected behavior or not, as I could not find documentation indicating one way or another

### Actual behavior
- all links became relative links, which solved issues I had with users using proxies to access MISP

### Steps to reproduce the behavior
change baseurl to ""
- by editing the config.php file at /var/www/MISP/app/Config
or
- by editing the value from the Web interface under Administration->Server Settings -> MISP Settings tab

**Comment by iglocska** [comment]
This is indeed intended. There are some use-cases where this was a requirement. It was tested and haven't seen any unintended consequences reported from it - though it is advised to set the baseurl. If set, MISP will use absolute paths.

**Comment by hjklz** [comment]
Ok, excellent, thanks for the prompt reply!

**Comment by iglocska** [comment]
No worries and please let us know if you have any other questions / notice something fishy!

**Comment by hjklz** [comment]
Actually for a follow-up on this, how would I go about connecting to another server if the base URL is blank? As per the docs https://www.circl.lu/doc/misp/using-the-system/index.html#setting-up-a-connection-to-another-server I need to populate the Base URL field with something. 

Thanks.

Oh never mind, I figured it out, just had to configure the http proxy.
