### ISSUE TITLE
Issue on MISP Installion on fresh server 

### ISSUE THREAD

**Issue by abdulshemeer166** [MISP/MISP#2003]
I got an error while doing the installation 

[root@misp MISP]# mysql -u misp -p misp < INSTALL/MYSQL.sql
Enter password:
ERROR 1214 (HY000) at line 94: The used table type doesn't support FULLTEXT indexes
[root@misp MISP]# mysql -u misp -p misp < INSTALL/MYSQL.sql
Enter password:
ERROR 1214 (HY000) at line 94: The used table type doesn't support FULLTEXT indexes
[root@misp MISP]#

[root@misp MISP]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@misp MISP]#

Your MariaDB connection id is 10
Server version: 5.5.52-MariaDB MariaDB Server

**Comment by abdulshemeer166** [comment]
Any updates

**Comment by iglocska** [comment]
Sounds like you have an old MySQL/MariaDB version (<5.5). Could you update it to 5.6+?

**Comment by abdulshemeer166** [comment]
is there any specific commands to update it

**Comment by iglocska** [comment]
Guide on how to do it is here:

https://mariadb.com/resources/blog/installing-mariadb-10-centos-7-rhel-7

Make sure that you back anything up that's currently in your database first.

**Comment by abdulshemeer166** [comment]
How do I benefit from MISP when I have Splunk as SIEM and Cuckoo Sandbox machine

If somebody can give me some guidance it will be well and good

**Comment by abdulshemeer166** [comment]
Is the feeds are automatically updated or can i schedule the update time

**Comment by abdulshemeer166** [comment]
Some body can help me How many feeds supported by MISP

Did MISP support all the feeds
