### ISSUE TITLE
Import error - MISP JSON or XML file

### ISSUE THREAD

**Issue by mkoelewijn** [MISP/MISP#2008]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Issue
| OS version (server)       | Ubuntu 16.04.2 LTS
| PHP version               | 5.6.30-6
| MISP version / git hash   | 2.4.67
| Browser                   | Firefox

### Expected behavior
Import MISP JSON or XML file in events

### Actual behavior
"An Internal Error Has Occurred."
"Error: An Internal Error Has Occurred."

### Steps to reproduce the behavior
list events > "Import from MISP Export" > JSON or XML file

### Logs, screenshots, configuration dump, ...

2017-03-02 13:45:04 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'attribute_count' doesn't have a default value
Request URL: /events/add_misp_export
Stack Trace:
#0 /var/www/html/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/html/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/html/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1026): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/html/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(Event), Array, Array)
#4 /var/www/html/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/html/app/Model/Event.php(2147): Model->save(Array, Array)
#6 /var/www/html/app/Controller/EventsController.php(2235): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#7 /var/www/html/app/Controller/EventsController.php(1209): EventsController->_addMISPExportFile('json', false, '1')
#8 [internal function]: EventsController->add_misp_export()
#9 /var/www/html/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/html/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/html/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by mkoelewijn** [comment]
Anyone?

**Comment by iglocska** [comment]
Will have a fix ready today, sorry for the delay.

**Comment by mkoelewijn** [comment]
Seems to work fine now, thanks!
