### ISSUE TITLE
MISP.baseurl setting is (wrongly) critical after upgrade from 2.4.65 to 2.4.67

### ISSUE THREAD

**Issue by se-te** [MISP/MISP#2016]
Hello,

We upgraded from 2.4.65 to 2.4.67 and immediately the MISP.baseurl setting reports a critical state. Previously the value was the same, was correct and was seen as correct. Now it is seen as not matching the URL (but it is!). The string and the URL both start with https:// and are a copy-paste of one another.

This regression is reproduced easily on several instances: we just upgrade to 2.4.67.

The upgrade to v2.4.67 is done the following way:

1. git fetch
2. git checkout tags/v2.4.67
3. git submodule update --init --force

Do you have any suggestion?
Thanks a lot ;)

**Comment by iglocska** [comment]
Don't worry about it, it's a display bug with 2.4.67, if you just pull the latest commit on HEAD it is resolved already!

**Comment by se-te** [comment]
Awesome! Thank you so much :)
