### ISSUE TITLE
Limit to concurrent connections for same user

### ISSUE THREAD

**Issue by ddurvaux** [MISP/MISP#202]
In order to install a public open-source MISP (will be hosted on MISP.be), we have slightly modified MISP to allow the user public/public to read events through the web UI.

There is only one issues remaining: it seems that user 'public' can only have a limited amount of concurrent connections.  We would like to raise that limit to a high number.

Where could this be changed in the code?

Thanks!

David

**Comment by elhoim** [comment]
Is this (still) the case?
Can we close?

**Comment by Rafiot** [comment]
must be fixed by now.

**Comment by elhoim** [comment]
Considering handled, closing.
