### ISSUE TITLE
misp.logrotate: no such file

### ISSUE THREAD

**Issue by Ibrahimous** [MISP/MISP#2020]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | N/A
| OS version (client)       | Ubuntu
| PHP version               | 7.0.15
| MISP version / git hash   | 2.4.66 commit d1e2703ae76f1c6015991b576fb3e45ee1ebb42a

### Expected behavior
From INSTALL.ubuntu1604.txt :

8/ Log rotation
---------------
[...]
sudo cp INSTALL/misp.logrotate /etc/logrotate.d/misp

### Actual behavior

cp: impossible d'évaluer '/var/www/MISP/INSTALL/misp.logrotate': Aucun fichier ou dossier de ce type
(for non french speaking guys: <=> ..misp.logrotate': No such file)

### Steps to reproduce the behavior

Just enter that : sudo cp INSTALL/misp.logrotate /etc/logrotate.d/misp

**Comment by iglocska** [comment]
It has been added in a later commit, please git pull origin 2.4.

**Comment by muyenzo** [comment]
I am getting the same error too. Kindly assist please.
