### ISSUE TITLE
using ansible install on ubuntu 16.04 / php7 leads to blank page

### ISSUE THREAD

**Issue by 0xmilkmix** [MISP/MISP#2024]
Hello,

I tried to deploy MISP using the ansible configuration on the github on a freh ubuntu 16.04. I changed references to php5 to php or php7 to make it work under Ubuntu 16.04. I also modified the nginx config for php-fpm.sock to point to:
   /var/run/php/php7.0-fpm.sock

However, when accessing the website I get a blank page. FPM is running and no error trying to access the .sock file in nginx error.log. Any idea on what went wrong?

Regards

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | OSX
| PHP version               | 7.0
| Browser                   | Safari / Chrome

### Expected behavior
Login page

### Actual behavior
Blank page

**Comment by xitation** [comment]
I'm having the exact same issue as described.

**Comment by SteveClement** [comment]
Dear

Can you enable logging: https://nginx.org/en/docs/debugging_log.html

And also create a test.php: <?php phpinfo(); ?>
Does it return the usual test page?

If anything is in the log, please share.

**Comment by alpal** [comment]
I had the same issue. I have it working (not fully tested, only just spun up in a dev environment), I didn't fully record my changes, sorry. The attached diff I think is everything ... I will try and test again when I get a chance. From memory I had a few other issues - like one of the dependencies installing the first run but no the second. 

HTH
Al

[patch.txt](https://github.com/MISP/MISP/files/1571938/patch.txt)

**Comment by ghost** [comment]
Just ran into the same issue, had deployed the ansible role on a near-stock Debian 9 image. Upon visitng the webpage, a blank page came up. No error messages anywhere. Turned out that changing 'include fastcgi_params' to 'include fastcgi.conf' resolved the issue 100%
