### ISSUE TITLE
Two file elements can only handle 1 file upload 

### ISSUE THREAD

**Issue by jymcheong** [MISP/MISP#2028]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Bug - As per the title

Environment based on MISP Training VM but upgraded MISP to 2.4.67

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------3
| Type of issue             | Bug, 
| OS version (server)       | Ubuntu 14.04
| OS version (client)       | macOS Siera 10.12. 
| PHP version               | PHP 7.0.14-2
| MISP version / git hash   | 2.4.67
| Browser                   | Safari

### Expected behavior

Two distinct files should be added into distinct attribute.

### Actual behavior

Only 1 file was able to upload

### Steps to reproduce the behavior

1. Create a template with two file elements (both **without** Batch option checked)
2. Create an event
3. Use template created in step 1
4. Upload 1 file for each template element
5. At 'Populate From Template Result' you will only see one file
6. Click 'Finalise' from step 5
7. View Event page will show only 1 file uploaded

**Comment by jymcheong** [comment]
After looking at the sample Malware Report template, I noticed there's a Batch option on the 2nd file element. After checking Batch option for the 2nd File Element, it is able to upload 2 files. Is that the right way to use Batch option for File Template Element?

**Comment by jymcheong** [comment]
From https://github.com/MISP/misp-book/blob/master/using-the-system/README.md, the description under **File Element** says "Batch import element: Ticking this checkbox allows users to upload several files using this element."

**Comment by jymcheong** [comment]
To illustrate the observation:
https://cdn-images-1.medium.com/max/2000/1*9xY_trEJ68GiihCG3fLVDQ.gif

**Comment by BenjaminJoly** [comment]
So it seems that everything works and is documented. So I close the issue. Do not hesitate to tell me if I have to reopen it for any reason !
