### ISSUE TITLE
Import cuckoobox reports

### ISSUE THREAD

**Issue by mkorman90** [MISP/MISP#203]
Many organizations use Cuckoobox. There should be a way of importing some format of Cuckoobox reports to MISP.

**Comment by advancedeng** [comment]
Hi all, any update on this one?

**Comment by elhoim** [comment]
Tracked under #465 now with a cross-reference to a ticket in cuckoo's issues list.

The update is basically: slowly ongoing. If you can contribute something (custom reporting module for cuckoo or parsing code on MISP side) this could be nice.
