### ISSUE TITLE
REST API: How to add an attachment (which is NOT a malware sample)?

### ISSUE THREAD

**Issue by govcert-ch** [MISP/MISP#2037]
I did not find any documented way how to add an attachment to an event. Actually not even a way to add a normal attribute, but latter one can be worked around by adding a shadow attribute and then accept it (still, adding an attribute directly would be nice). I tried 2 workarounds:

Variant 1: Upload API:
```
        url = urljoin(self.url, "events/upload_sample/%d"%eventID)
        jsonReq = json.dumps({"request": {"files":  [{"filename": filename, 
                                                     "data": base64.b64encode(data)
                                                    }],
                                          "info": "Info",                                          
                                          "category": "External analysis",
                                          "distribution": 5,
                                          "to_ids": toIds, 
                                          "comment": "mycomment"
                                         }})
```
This basically works, but uploads like a sample (with hashes). This is not appropriate if you, for instance, upload a config file downloaded by a malware, which is not by itself malicious.

Variant 2: Adding a "data=" tag to a Shadow attribute:
```
        url = urljoin(self.url, "shadow_attributes/add/%d"%eventID)
        jsonReq = json.dumps({"request": {"ShadowAttribute": {"value": filename, 
                                                                  "to_ids": toIds, 
                                                                  "type": "attachment", 
                                                                  "category": "External analysis", 
                                                                  #"event_id": eventID,
                                                                  "data": base64.b64encode(data)
                                                                 }}})
```
This returns an error
```
u'{"name":"Invalid event id.","message":"Invalid event id.","url":"\\/events\\/view"}'
```
This looks like a bug to me, as just adding the "data" element seems to change the URL to /events/view. If the "data" tag is left out, a normal attribute is added as expected. If the (commented out) '"event_id": evendID' is  activated in above fragment, the call if successful, but behaves like viewing the event (a proof that the given url was modified to the view url internally).

All in all, I can't figure out a way to add an attachment to an event via REST API. PyMISP is no option neither, as this messes up all timestamps of the event (I opened an issue there about this).

**Comment by iglocska** [comment]
Interesting, looking into it!
