### ISSUE TITLE
Pull All works through proxy, Push All doesn't

### ISSUE THREAD

**Issue by combobulator** [MISP/MISP#2039]
EDIT: GitHub search failed me, but google brought up issue #1631 which has the same network layout and symptoms, as far as I can tell.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Support?
| OS version (server)       | Ubuntu 16.04.1 LTS
| OS version (client)       | Ubuntu 16.04.1 LTS
| PHP version               | 7.0.13
| MISP version / git hash   | 2.4.67; updated from https://github.com/harvard-itsecurity/docker-misp; original hash 8530a25dc8b2f7730e43fbab0c39612a15619bbd
| Browser                   | N/A

### Expected behavior
Given two servers, A and B, with a proxy between them allowing HTTP & HTTPS (port 80 & 443) from A to B, but preventing connectivity from B to A; also given a sync user (with full priviledges) on server B, whose authkey is used on server A:

On server A: by clicking 'Pull All' for server B ('Sync Actions' > 'List Servers' page), all eligible remote events should be pulled to the local server (A from B).
Os server A: By clicking 'Push All' for server B ('Sync Actions' > 'List Servers' page), all eligible local events shoud be pushed to the remote server (B from A).

### Actual behavior
Clicking 'Pull All' for server (B) pulls all eligible events to server (A) (as expected).
Clicking 'Push All' for server (B) adds the action to the job queue and executes without error on server (A). The events never appear on server (B).
This is regardless of the distribution level used (first I tried sharing groups, working my way up to 'All Communities').

tcpdump shows data flowing between the servers as expected whether pushing or pulling (the connections are established, packets of varying length are passed between them, but nothing appears on server B).

publishing the event on server A does not propogate the event to server B (same result as when trying to push).

I'm not sure if this is relevant, but server A has a self-signed certificate, and server B has a letsencrypt certificate.

### Steps to reproduce the behavior
1) Install the harvard-itsecurity MISP docker image on two servers
2) Update to MISP 2.4.67
3) Provide a self-signed certificate to one (server A), and a trusted certificate to the other (server B)
2) Set up a proxy to connect the two, allowing connectivity in one direction only (A to B)
3) Set up sync user on server B
4) Use the sync users' authkey on server A to create a connection to server B
5) Attempt to pull and push all events

### Logs, screenshots, configuration dump, ...
Server B: /var/www/MISP/app/tmp/logs/resque-2017-03-10.log: Empty for time period
Server A: /var/www/MISP/app/tmp/logs/resque-2017-03-10.log:
[2017-03-10 15:29:00] main.INFO: got {"queue":"default","id":"ee7d05d4de5d21588de25e63f1f53ad7","class":"ServerShell","args":[["push","1","full","3769","2"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"ee7d05d4de5d21588de25e63f1f53ad7\",\"class\":\"ServerShell\",\"args\":[[\"push\",\"1\",\"full\",\"3769\",\"2\"]]})","worker":"862a1ceb3472:190"} []
[2017-03-10 15:29:00] main.INFO: Processing ID:ee7d05d4de5d21588de25e63f1f53ad7 in default {"type":"process","worker":"862a1ceb3472:190","job_id":"ee7d05d4de5d21588de25e63f1f53ad7"} []
[2017-03-10 15:30:10] main.INFO: done ID:ee7d05d4de5d21588de25e63f1f53ad7 {"type":"done","job_id":"ee7d05d4de5d21588de25e63f1f53ad7","time":69842,"worker":"862a1ceb3472:190"} []

**Comment by combobulator** [comment]
I meant to correct this post earlier but it slipped my mind sorry.
This issue was actually due to incorrect sync settings restricting the distribution, the connection works fine via a proxy as expected.

**Comment by adulau** [comment]
Thank you for the feedback.
