### ISSUE TITLE
Logging for attribute edition

### ISSUE THREAD

**Issue by jeff3877** [MISP/MISP#2044]
When an attribute is edited, add the details of what has been changed with the attribute edition (IDS Flag, comment, category, tags, etc...).

**Comment by cristianbell** [comment]
The changes are logged, in the table logs, see change. The change field is only visible to users with perm_audit in the Audit -> List Logs. 

The change field is not displayed in the View Event History though. 
@iglocska: Maybe it could be shown for users with perm_audit? 

also related to #167
