### ISSUE TITLE
Include attribute level tags in the search APIs

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#2053]
Currently it only matches against event level tags, but they should ideally also include any event that has at least one attribute tagged with the searched tag.

**Comment by TheDr1ver** [comment]
I just noticed this as well, while trying to search for attribute tags via PyMISP. I had considered making some changes to AttributesController.php to fix it, but wasn't sure what the best method would be. 

Should `attributetags` be added as a parameter to the restSearch function (/app/Controller/AttributesController.php#L1652) as well as the simplefalse and paramArray arrays? Or should something be added to the param loop along the lines of:
 `if (isset($data['request'][$p]) and $p=='tags') ${'attributetags'} = $data['request'][$p]` ?

If the latter, I wasn't sure if something else would need to change in the following section where it sets the tag conditions.

**Comment by neok0** [comment]
should be fixed with #2212

**Comment by adulau** [comment]
Tested with recent restSearch API (version 2.4.96) and it works as expected (returning attributes level tagged attributes) with query such as:

~~~~
{
    "returnFormat": "csv",
    "tags": ["foobar"]
}
~~~~
