### ISSUE TITLE
Freetext import: tune the detection of filename vs domain

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#2061]
.com doesn't offer filename as an option

**Comment by keram79** [comment]
Seems to be differently broken by now in 2.4.84.  
Importing "mail.google.com" defaults to Payload delivery - filename, the same applies for e.g. APT indicator domains from the APT10 CloudHopper Report from PWC.

**Comment by keram79** [comment]
Seems to be solved by enabling the WarningList "TLDs" :)

**Comment by iglocska** [comment]
It was a nice catch - we indeed had a bug. The default should be to use a
hard-coded list if no warninglist exists for TLDs - however, this scenario
is only activated if the currently loaded set has no values. As of recently
we force fed .onion as an additional value so the set was never empty ;)
