### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by ics** [MISP/MISP#207]
Implement CSP as described in http://www.w3.org/TR/CSP/

**Comment by Rafiot** [comment]
Status?

**Comment by jloehel** [comment]
Any news about this? 6 years with high prio?

**Comment by cvandeplas** [comment]
This was actually implemented quite some time ago and can be turned on/off with the `Security.csp_enforce` parameter.
For details see https://github.com/MISP/MISP/commit/8a3144f112aab80b0dcc6bd533810d251173d8f5
