### ISSUE TITLE
Attribute fields: value and value1,value2

### ISSUE THREAD

**Issue by deloittem** [MISP/MISP#2070]
Hello,

I have a question related to attribute fields: value and value1,value2.

I'd like to add NIDS rules for the new attribute[type] = IP-SRC|PORT and IP-DST|PORT but how should these fields be managed in NidsExport() since we currently only receive the virtual field = attribute[value] ?

I could split the virtual value again to value1 and value2 in NidsExport() but what about updating the fetchAttributes() function to directly retrieve value1,value2 instead of value ?

Regards

**Comment by iglocska** [comment]
Changing fetchAttributes to retrieve value1 and value2 separately would break all existing functionality that expects value (such as the synchronisation) so it's definitely out of the question - however, just running explode('|', $attribute['value']) on composite attribute types should do the trick for you.

Edit: I was wrong about the synchronisation, it only relies on fetchAttributes(). However, other exports will rely on the same functionality, so running the explode is still highly prefered.

**Comment by deloittem** [comment]
We could still retrieve value+value1+value2 (3 fields) in fetchAttributes() to prevent breaking functionalities but ok I will do the split again using explode()

**Comment by iglocska** [comment]
Indeed, retrieving all 3 would work, though keep in mind it would inflate the returned data size for all attribute based exports with a bunch of duplication. CPU time is cheap, I'd just go with that ;)
