### ISSUE TITLE
Event Tag add/remove UI doesn't refresh in training VM 2.4.69

### ISSUE THREAD

**Issue by jymcheong** [MISP/MISP#2074]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | macos sierra
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.69
| Browser                   | safari & chrome 

### Expected behavior

tag should appear immediately after add.

tag should disappear immediately after confirm remove.

### Actual behavior

noted tag message after operations but need to do a browser refresh to reflect the changes.

### Steps to reproduce the behavior

- downloaded https://www.circl.lu/assets/files/misp-training/MISP_v2.4.69.ova
- install into vmware fusion
- adjust base url via console
- use browser to login
- edit any event 
- click + to tag
- click on tag [x] to untag

**Comment by SteveClement** [comment]
This is fixed in latest. @jymcheong if this persists after an update, please let us know.
