### ISSUE TITLE
email template or sample

### ISSUE THREAD

**Issue by santi10** [MISP/MISP#2078]
Hi,

I set MISP 2.4.56 version. I'm configuring the email right now and I see that the mail is send with all atributes.

Can I create some template????

I want to send the mail with out attributes, is it possible?

Thanks a lot

**Comment by RichieB2B** [comment]
Setting `GnuPG.bodyonlyencrypted` to `true` will only send out a link without any further details in the E-mail. You can find this setting in the _Encryption settings_ tab of the _Server Settings_ page.

**Comment by santi10** [comment]
Yeah! Thanks very muchs!
