### ISSUE TITLE
MISP cannot sync to TLS 1.2 only MISP servers

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2080]
Because of https://github.com/cakephp/cakephp/issues/10445 MISP cannot sync to MISP servers only accepting TLS 1.2 connections.

**Comment by RichieB2B** [comment]
CakePHP just merged a fix for this with https://github.com/cakephp/cakephp/commit/0a378021a0f2141c999fdc807e265729c4eff55c
So if we update MISP to use this CakePHP version or newer it should fix this issue.

**Comment by adulau** [comment]
Great! Thank you very much for the follow-up with CakePHP. @iglocska for the next release, we should do the update and mentions it in the release blog post.

**Comment by sim0nx** [comment]
Is there any news on this issue? We strangely have the situation where we need to do TLS1.2 and this effectively breaks the syncronisation :-/

Thnx

**Comment by iglocska** [comment]
I've just pushed a new commit that updates cakephp to the current version including @RichieB2B fixes, this should resolve it. Let us know if it still persists!

**Comment by sim0nx** [comment]
Great, thanks a lot!

I just applied the update and confirm that it fixes my TLS1.2 issue!

**Comment by iglocska** [comment]
Perfect, thanks for the heads-up and thanks to @RichieB2B for fixing it!

**Comment by adulau** [comment]
Great news. Thanks @sim0nx for the reminder and @RichieB2B for the patch with CakePHP.
