### ISSUE TITLE
Managing Delegation Request - Discarding an event

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2081]
### Expected behavior
After discarding a delegation request, the client should return to the event list or even the list of delegated events (delegation_index)

### Actual behavior
The client come back on the same event which is no more accessible (distribution = organisation only)

### Steps to reproduce the behavior
- Receive a delegation request
- Discard the request

### Logs, screenshots, configuration dump, ...
![discardevent](https://cloud.githubusercontent.com/assets/17081497/24299400/63ce18e0-10a9-11e7-8648-18cc43e1adbb.png)

**Comment by iglocska** [comment]
Woops, nice catch. Should be fixed now.
