### ISSUE TITLE
Sync Error: Server Unreachable

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#2083]
So I tried to follow the guide (https://www.circl.lu/doc/misp/book.pdf) pg. 48 for setting up a connection to another server. 

I enter in the base URL of the server I want to connect to.
I give it a name.
Enable Push, Pull, and Self Signed (don't have a public cert just the one I made during install)
I put in the authorization key from the instance I'm adding the server on. 
Click submit and then run the test connection.  
I receive error: Server Unreachable during test. 
I cannot manual push or pull.
I did ping on both port 80 and 443 to see if it was a possible network issue.  Servers responded to ping. 
I looked in the bootstrap file but did not see anything that related to the organization name. 
I am entering in the new server as admin so I have sync, read, and write privileges.

**Comment by adulau** [comment]
Did you check if you can connect to TCP port 80 or 443 from the server (using telnet mispserver 80 or using curl/openssl s_client)? ping will only send an ICMP packet and will not test for TCP.

**Comment by jimbolya0607** [comment]
no i did not check that - will test that out

**Comment by jimbolya0607** [comment]
telnet 45.55.74.212 80
Trying 45.55.74.212...
Connected to 45.55.74.212.

so that appears to have connected?

**Comment by jimbolya0607** [comment]
telnet 45.55.74.212 443
Trying 45.55.74.212...
Connected to 45.55.74.212.

**Comment by jimbolya0607** [comment]
doesn't look like telnet is open...

# netstat -ntlp | grep LISTEN
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN                                                                                                                                                                   13116/python3
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN                                                                                                                                                                   19480/mysqld
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN                                                                                                                                                                   21118/redis-server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                                                                                                   1633/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN                                                                                                                                                                   16560/master
tcp6       0      0 :::80                   :::*                    LISTEN                                                                                                                                                                   14167/apache2
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                                                                                                   1633/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN                                                                                                                                                                   16560/master
tcp6       0      0 :::443                  :::*                    LISTEN                                                                                                                                                                   14167/apache2

**Comment by jimbolya0607** [comment]
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN      13116/python3
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      19480/mysqld
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      21118/redis-server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1633/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      16560/master
tcp6       0      0 :::80                   :::*                    LISTEN      14167/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1633/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      16560/master
tcp6       0      0 :::443                  :::*                    LISTEN      14167/apache2

**Comment by jimbolya0607** [comment]
Solved - this can be closed...
It needed an entry into /etc/hosts file...
