### ISSUE TITLE
Template unable to upload file at all

### ISSUE THREAD

**Issue by jymcheong** [MISP/MISP#2084]
### Work environment

Using the training VM 2.4.69.

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       | ubuntu
| OS version (client)       | macOS
| PHP version               | PHP within Training VM
| MISP version / git hash   | 2.4.69
| Browser                   | macOS Safari & Chrome 

### Expected behavior
A file pop-up dialog should appear to select file for upload.

### Actual behavior
Nothing happens

### Steps to reproduce the behavior
1. Use any existing event or create a new one
2. Click the event id to display event
3. Click Populate From...
4. Drill into the default Malware Report 
5. Click 'Upload File'

**Comment by jymcheong** [comment]
We are extending MISP for automated payload testing. Template is useful to provide a structure way to upload sample rather than remember which tag to use.

https://medium.com/@jym/extending-misp-for-automated-testing-726214c2e928#.o82zftdhc

**Comment by jymcheong** [comment]
<img width="1376" alt="screenshot 2017-03-27 11 23 04" src="https://cloud.githubusercontent.com/assets/11232021/24339696/ed7cbece-12df-11e7-9d23-d6fc6be4c5ef.png">

**Comment by jymcheong** [comment]
<img width="1373" alt="screenshot 2017-03-27 11 40 36" src="https://cloud.githubusercontent.com/assets/11232021/24340106/5c32b330-12e2-11e7-9882-ecce8840a23c.png">

Looks like somewhere in the template it is referencing specific js (misp2.4.68.js) instead of the misp.js within ..webroot/js. I did a quick hack to copy misp.js to misp2.4.68.js & the upload button works.

**Comment by iglocska** [comment]
Interesting, will have a look

**Comment by jymcheong** [comment]
Thanks.

**Comment by iglocska** [comment]
Should be fixed now, thanks for the heads-up!

**Comment by jymcheong** [comment]
Thanks!
