### ISSUE TITLE
Free text import not allowing to change .top, .win domains to network activity type during buld upload

### ISSUE THREAD

**Issue by maraboutingermany** [MISP/MISP#2085]
I still have issues with the free text importing not being able to recognize some of the domain types such as .top or .win, the worst part is that I cannot convert them during the bulk free text import as the network activity type is not presented to me

![image](https://cloud.githubusercontent.com/assets/25768156/24347045/4588bb26-12d7-11e7-92ca-b02e620ea450.png)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| MISP version / git hash   | MISP 2.4.67
| Browser                   | Chrome

**Comment by iglocska** [comment]
Hello, in case you don't see the response on gitter I'll paste it here too:

you need to update your warninglists and enable the IANA list and then it will use all entries from in there
I've just pushed a patch that will make the freetext import use it even if the list isn't enabled (as long as you have it loaded)
so just go to input filters as a site admin -> warninglists -> update
if the list doesn't get populated, make sure your submodules in git are up to date
~~~
git submodule update && git submodule init
~~~
after that redo the previous steps
then you have two options:
Either update to the latest MISP commit from the 2.4 branch, or enable the IANA warning list
