### ISSUE TITLE
Undefined index: user in /var/www/MISP/app/Model/Server.php

### ISSUE THREAD

**Issue by rubenrodr-versia** [MISP/MISP#2086]
Hi,

We have updated from 2.4.59 to 2.4.70 and from php56 to php70  on Centos 7 and now when selecting Administration - Server Settings we get Service Unavailable.

Logs:

debug.log

2017-03-27 10:50:43 Notice: Notice (8): Undefined index: type in [/var/www/MISP/app/Model/Server.php, line 2939]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Server::workerDiagnostics() - APP/Model/Server.php, line 2939
ServersController::serverSettings() - APP/Controller/ServersController.php, line 843
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-03-27 10:50:43 Notice: Notice (8): Undefined index: type in [/var/www/MISP/app/Model/Server.php, line 2939]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Server::workerDiagnostics() - APP/Model/Server.php, line 2939
ServersController::serverSettings() - APP/Controller/ServersController.php, line 843
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-03-27 10:50:43 Notice: Notice (8): Undefined index: user in [/var/www/MISP/app/Model/Server.php, line 2940]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Server::workerDiagnostics() - APP/Model/Server.php, line 2940
ServersController::serverSettings() - APP/Controller/ServersController.php, line 843
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

error.log

2017-03-27 10:50:43 Error: [MethodNotAllowedException] Non numeric PID found.
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(843): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

Thanks in advance.
Best regards.

**Comment by rubenrodr-versia** [comment]
Hi,

If we use php56 instead php70 it works fine.
php7 package list:
rh-php70-runtime-2.3-1.el7.x86_64
rh-php70-php-fpm-7.0.10-2.el7.x86_64
rh-php70-php-common-7.0.10-2.el7.x86_64
rh-php70-php-mbstring-7.0.10-2.el7.x86_64
rh-php70-php-process-7.0.10-2.el7.x86_64
rh-php70-php-cli-7.0.10-2.el7.x86_64
rh-php70-php-ldap-7.0.10-2.el7.x86_64
rh-php70-php-pear-1.10.1-3.el7.noarch
rh-php70-php-devel-7.0.10-2.el7.x86_64
rh-php70-php-zip-7.0.10-2.el7.x86_64
rh-php70-php-mysqlnd-7.0.10-2.el7.x86_64
rh-php70-php-xml-7.0.10-2.el7.x86_64
rh-php70-php-7.0.10-2.el7.x86_64
rh-php70-scldevel-2.3-1.el7.x86_64
rh-php70-2.3-1.el7.x86_64
rh-php70-php-bcmath-7.0.10-2.el7.x86_64
rh-php70-php-json-7.0.10-2.el7.x86_64
rh-php70-php-pdo-7.0.10-2.el7.x86_64

Thanks.
Best regards.

**Comment by iamshleya** [comment]
We also just updated from php56 to php70 and are experiencing the same issue when accessing the Server Setting tab. Are you getting the same error, or were you able to fix this? Thanks!

**Comment by rubenrodr-versia** [comment]
No, we keep using php56.

**Comment by vasiloiuadrian** [comment]
Same issue on our MISP instance. Updated to 2.4.75 and PHP70. Is there a way to resolve this problem? I had another MISP instance updated to 2.4.75 but with php56 and it says that PHP is unsupported and it doesn't load redis php and cli

**Comment by iglocska** [comment]
Could you check the error output with php 7? Should be in /var/www/MISP/app/tmp/error.log

The original post in the thread is rather old and the code has changed since.

Also, PHP 5.6 is not officially supported but should work fine, it probably doesn't load redis because you only have phpredis installed for 7.0.

**Comment by vasiloiuadrian** [comment]
![non numeric pid](https://user-images.githubusercontent.com/29433891/27139965-08e8cb68-512d-11e7-89b8-b88abff613f6.JPG)
I have centos 6.8 and php 7.0.10 - I get thi error when trying to enter the Server Settings tab.
Thank you.

**Comment by iglocska** [comment]
That sounds like you don't have php-redis loaded and you use the Redisent fallback connector which causes that specific issue. 

Since you've moved to php 7, you need the equivalent of this:


pecl install redis-2.2.8
echo "extension=redis.so" > /etc/opt/rh/rh-php56/php-fpm.d/redis.ini
ln -s ../php-fpm.d/redis.ini /etc/opt/rh/rh-php56/php.d/99-redis.ini
systemctl restart rh-php56-php-fpm.service

With that said, PHP 5.6 should work just fine, for now.

**Comment by vasiloiuadrian** [comment]
pecl install redis 
pecl/redis is already installed and is the same as the released version 3.1.2 - install failed.
So I belive that I have redis installed. I did installed another instance of MISP but this time with php 7.0.20 and it seems it works fine, the only problem is below:
![php720](https://user-images.githubusercontent.com/29433891/27170371-54963e36-51b6-11e7-95fe-5283bd425269.JPG)
How can I resolve this? the php cli version is:
![phpcli](https://user-images.githubusercontent.com/29433891/27170442-90322630-51b6-11e7-87e9-4b6053e19010.JPG)
Thank you!

**Comment by iglocska** [comment]
Ah ok, the CLI version check is flawed on CentOS, don't worry about that, my apologies, I misunderstood what was wrong ;)

As long as Redis works you should be fine. Do you have any functionality not working?

**Comment by vasiloiuadrian** [comment]
No, everything seems to be working. I had something with Failed to Load GPG and STIX (in the tutorial there is no command for installing Mixbox ) but now it's ok.
Thank you!

**Comment by iglocska** [comment]
Yeah the mixbox stuff was missing from the install guide, it should be there as of yesterday :) If you run into anything else that's broken let us know! Will close the issue for now, but feel free to open a new one!
