### ISSUE TITLE
Template Upload Files Issues

### ISSUE THREAD

**Issue by lowson** [MISP/MISP#2087]
After a fresh install I found issues using the "Upload Files" buttons when using a template.

The "Add Attachment" on the main event page does work tho.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Support
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 16.04
| PHP version               | 7.0.15-0ubuntu0.16.04.4
| MISP version / git hash   | v2.4.70 (1936ee961dc514c608493a8fdf3bdf7e6f65331d)	
| Browser                   | Chromium

### Expected behavior
"Upload Files" button allows uploads

### Actual behavior
Nothing happens

### Steps to reproduce the behavior
Fresh install following 16.04 installation instructions.

### Logs, screenshots, configuration dump, ...
Console logs when using the button:

Uncaught ReferenceError: templateFileUploadTriggerBrowse is not defined
    at HTMLSpanElement.onclick (yes:3)

I slso found this maybe unrelated issue: 
Failed to load resource: the server responded with a status of 404 (Not Found) /js/misp3.js

**Comment by iglocska** [comment]
Could you do a git pull again? This issue should have been fixed early this morning :)

**Comment by lowson** [comment]
Confirmed working :) Thanks

**Comment by iglocska** [comment]
Sweet, thanks for the feedback! :-)
