### ISSUE TITLE
Display - height of popup "Add Attribute"

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2101]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Let say Bug
| OS version (client)       | Ubuntu 16.04
| MISP version / git hash   | 2.4.70
| Browser                   | Firefox 52.0.2 (64-bit)

:warning: Issue linked to screen resolution (1366x768) 
(And no, buying a bigger screen is not an option here :P)

### Expected behavior
Being able to interact with the popup to move it or whatever after a failed input. 

### Actual behavior
Error messages make the popup higher and the submit/cancel buttons are not reachable

### Steps to reproduce the behavior
- Try to add an attribute using the popup but forget to choose the category/type/other options...
- Submit
- Cry

### Logs, screenshots, configuration dump, ...
![beforevalidating](https://cloud.githubusercontent.com/assets/17081497/24611619/085be316-1883-11e7-86f9-f5ad3c24b6fd.png)  
![aftervalidation](https://cloud.githubusercontent.com/assets/17081497/24611629/0ca9a642-1883-11e7-8646-432e5cd0f1f7.png)

(By the way the "Value not in the right type/format. Please double check the value or select type "other"." message seems a bit out of place since no type is selected)

**Comment by iglocska** [comment]
It should behave better on low res screens now. 
![resolution](https://cloud.githubusercontent.com/assets/3668672/24648056/993777f2-1922-11e7-990d-465eb118d124.jpg)
