### ISSUE TITLE
Infinite loading when adding an attribute fails

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2102]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Let say Bug
| OS version (client)       | Ubuntu 16.04
| MISP version / git hash   | 2.4.70
| Browser                   | Chromium Version 56.0.2924.76 

### Expected behavior
Get the add attribute popup back after failing a submission

### Actual behavior
The page keeps loading foreveeeer~

### Steps to reproduce the behavior
- Try to add an attribute using the popup but forget to choose the category/type/other options...
- Submit
- Waiiiiiit

### Logs, screenshots, configuration dump, ...
![beforevalidating](https://cloud.githubusercontent.com/assets/17081497/24612178/c864b1c8-1884-11e7-9e23-16f88801b4af.png)
![looooooaaaaaadiiiiing](https://cloud.githubusercontent.com/assets/17081497/24612182/ca7d5cee-1884-11e7-91fe-37b865a9b482.png)

**Comment by iglocska** [comment]
Hmm this works for me. Do you have noscript running? Could you check what error you get in your browsers dev console? (f12)

**Comment by Delta-Sierra** [comment]
I don't think I even have noscript or an equivalent installed nor running on chromium.
And I guess this screen should answer the second question: 
![script](https://cloud.githubusercontent.com/assets/17081497/24613651/34d742e0-1889-11e7-926a-0e96d814a466.png)

**Comment by iglocska** [comment]
Very odd, I can't reproduce it.. Just tried it on misp beta with the same input and it gets me the popup with the failing fields.

**Comment by Keisial** [comment]
I have seen actions occasionally fail (not sure why), which indeed leaves the spinner indefinitely, forcing the operator to reload the page.

**Comment by FloatingGhost** [comment]
+1 confirmed - 9e5b55b, chrome. Will poke around in the JS
