### ISSUE TITLE
add possibility to remove tags from Active Tag list 

### ISSUE THREAD

**Issue by yannw** [MISP/MISP#2103]
When adding taxonomies from the Taxonomies List, you can finetune by adding only single Tags from the full Taxonomy list instead of "enable all".
But once you went that far, you can't remove a Tag from the taxonomy even if the Tag was never used.
Example:
TLP Taxonomy Lib contains 5 Tags: tlp:red; tlp:amber; tlp:green; tlp:white and tlp:ex:chr
Once the taxonomy enabled and the 5 tags added with the + (plus sign), you can't remove tlp:ex:chr anymore from the list of used tags.
Now creating a new event and opening the tags selection menu to "All Tags" will always display the tlp:ex:chr tag, even that I don't want to use or see it.

please make unused tags removable

**Comment by iglocska** [comment]
Just a heads-up, this is now possible in the latest commit. You can now hide tags in the taxonomy view.

**Comment by yannw** [comment]
works perfectly!! Forgot to close the issue.
Thanks a lot!
