### ISSUE TITLE
MISP login issue

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#2107]
Currently facing issue in able to login to MISP instance

Credentials are correct, still cant login. No error message. Page just refreshes.

Tried changing password 
/var/www/MISP/app/Console/cake password [email][password] but getting following error

App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Could not update account for User.id = Notice Error: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 20]

2017-04-04 18:18:29 Notice: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 20]

i am still using admin@admin.test as email.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Which version of MISP are you on? I've just tried it on my end and the tool should work fine.

**Comment by thirdeyeintelligence** [comment]
Version is 2.4

Regards
Kunal M.

**Comment by iglocska** [comment]
2.4 is the minor version, more interested in the exact version number. You can find it in /var/www/MISP/VERSION.json

**Comment by thirdeyeintelligence** [comment]
2: major
4: minor
Hotfix:28

however i can see hotfix:70 is out - how can i upgrade my 28 to 70?

Regards
Kunal M.

**Comment by iglocska** [comment]
That version is ancient, could you update it to the latest version?

cd /var/www/MISP
git pull origin 2.4
git submodule init && git submodule update

**Comment by thirdeyeintelligence** [comment]
True that hotfix 70 is out :)

Regards
Kunal M.

**Comment by thirdeyeintelligence** [comment]
Updated and still the same issue. 
root@ubuntu:/var/www/MISP# cat VERSION.json 
{"major":2, "minor":4, "hotfix":70}

I will try the VM on other systems.

error : Could not update account for User.id = Notice Error: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 21]

2017-04-06 16:27:05 Notice: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 21]

**Comment by iglocska** [comment]
Could you check the valid e-mail addresses for existing users? 

```
mysql -u misp -p misp
select email from users;
```

**Comment by thirdeyeintelligence** [comment]
email address is admin@admin.test

`mysql> select email from users;
+------------------+
| email            |
+------------------+
| admin@admin.test |
+------------------+
1 row in set (0.00 sec)
`

**Comment by ndhambi** [comment]
I am facing the same problem, im using Major 2 Minor 4 and hotfix 78. I even checked the valid email addresses for existing users, they all valid but I still get the error:

error : Could not update account for User.id = Notice Error: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 21]

2017-09-07 15:04:05 Notice: Undefined index: id in [/var/www/MISP/app/Console/Command/PasswordShell.php, line 21]

**Comment by iglocska** [comment]
Just updated the tool to give you better feedback on the issue. Please git pull and try it again.

**Comment by thirdeyeintelligence** [comment]
For me I also perform a git checkout to be able to perform git pull

Regards
Kunal M.

**Comment by adulau** [comment]
Could you test with a recent version of MISP? I'll close the issue. Feel free to reopen the issue if required. Thank you.

**Comment by Afewedi** [comment]
I have issues to log in to MISP from my kali linux? can you please help. thank you

**Comment by iglocska** [comment]
> I have issues to log in to MISP from my kali linux? can you please help. thank you

Difficult to help you with the lack of details. Also, you've posted in an old closed thread. Please open a new issue, describe the exact issue you're having, the installer you chose, the OS version, MISP version, output from logs, etc.
