### ISSUE TITLE
Filename|Hash correlation occurs even when the hash is different

### ISSUE THREAD

**Issue by nicksoy** [MISP/MISP#2108]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| MISP version / git hash   | 2.4.70, hash of the commit

### Expected behavior

Based on my understanding of the indicator, filename|sha256 should correlate only if the filename AND hash values of the attribute coincides with a similar attribute in another event. 

### Actual behavior
![Uploading misp_correlation_filenameSHA.png…]()

I have noticed several events where filename|sha256 attributes are shown as correlating, even when the SHA256 values are different. 

### Steps to reproduce the behavior

1. Create an event with Payload delivery -> filename|sha256:         
malicious1.exe|f7eb7f98a55d6b40ae62c7c6904e1c2b1c2be3f53469290bba275435ee5b1105
2. Create another event with attribute Payload delivery -> filename|sha256:
malicious1.exe|eb7f98a55d6b40ae62cf7c6904e1c2b1c2be3f53469290bb5a275435ee53a83c
3. Submit the attributes
4.  The correlation column shows matching events. 
5.  View Correlation graph

6. For example, in the screenshot, Event 72 is supposed to correlate with Event 15 on the filename|sha256: 1.exe|ad9c2655dfef4076f74df4f0b797beab7ea21fcda73f0c33beb04e86191bfeba.

However, when checked, the value of the filename|sha256 attributes are: 
exe1.exe|24935c9fc491439fe7024a5061fb3faa7284f2c272e8f353a276394aac8be7dd, 
exe1.exe|3a345668f7f83513248b6099174176b7a4e4b90aa17e6f8a3bbd0d7e0533d415, 
exe1.exe|6f10ccd05b9b6c2beb8128c2cb08e7ef202f398c42493e82ce4c6a951042dfb7

Should they correlate?

**Comment by Rafiot** [comment]
Yes, it might be confusing, but the correlation is made on the filename OR on the hash.
As it is a very old comportment, I don think we will change it. @iglocska thought?

**Comment by iglocska** [comment]
Something we could change. Would it make sense to correlate only on the
hash if we are dealing with a filename|hash? Can there be any situation
where we'd want to keep the filename correlation with a mismatched hash?

**Comment by nicksoy** [comment]
The way I see it, if i want to correlate just on a file name OR hash, I would create two attributes, example, 1.exe and "6f10ccd05b9b6c2beb8128c2cb08e7ef202f398c42493e82ce4c6a951042dfb7". So any matches would be directed independently to either of those two attributes. 

Using filename|hash, I would like to see if the exact same named binary is being used by multiple campaigns (e.g. Fedex and UPS ransomware campaigns), thereby possibly indicating the same actors at play. 

However, I could just fall back to using  file name and hash as separate attributes and look for correlations individually. Perhaps that's a better practice.
