### ISSUE TITLE
API to get attributes filtering by criteria of event

### ISSUE THREAD

**Issue by Gunstick** [MISP/MISP#2113]
The current api allows filtering on events or attributes but no combination.

I would like to retrieve all attributes (or a certain type of attibute) from all events matching a search criteria.
Typically: all md5 attributes of all events of threat level high from the last 4 hours (and specify the output format: json/xml/openioc)

**Comment by Gunstick** [comment]
Seems nobody is taking on this task. I'm now looking into doing a python script downloading today's "high" events and for each event download the corresponding attributes. I will post here when that's done. That will be around end of May. Slow developer is slow.

**Comment by iglocska** [comment]
In this case the best would be to add additional filters to the /attributes/restSearch api. Should be pretty straight forward, just have a look how all of the filters are taken from url and request parameters and passed to the fetchAttributes() function in Models/Attribute.php. Let me know if you get stuck!

**Comment by adulau** [comment]
The API has been reworked in 2.4.96. The restSearch API now works with any output format supported by MISP.

Format such as the following works out of the box:

~~~~
{
    "returnFormat": "csv",
    "threatlevelid": "1d",
    "last": "2d",
    "threat_level_id": 1
}
~~~~

Don't hesitate to reopen the issue if this is not solving you request Thanks a lot.
