### ISSUE TITLE
Internal Server Error cake app.php

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2114]
I am getting an Internal Server error. Here are the logs. RHEL 7.

[root@LNP-SOLT-PAPP2 Core]#  cat /var/www/MISP/app/tmp/logs/error.log
2017-04-05 14:54:10 Error: Fatal Error (64): Can't use function return value in write context in [/var/www/MISP/app/Controller/AppController.php, line 291]
2017-04-05 14:54:10 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(64, 'Can't use funct...', '/var/www/MISP/a...', 291)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 291, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var/www/MISP/a...', 291, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Sounds like you are using an outdated version of PHP. Please upgrade to a
newer version or use the instructions from the installation guide to use
PHP 5.6 via SCL.

**Comment by syloktools** [comment]
Fixed with updated PHP

**Comment by adulau** [comment]
Thank you for letting us know. I'll close the issue.
