### ISSUE TITLE
Document password requeriments

### ISSUE THREAD

**Issue by Keisial** [MISP/MISP#2117]
The pages where the user is asked to change his password should display the requisites imposed to it:
* The minimum password length (Security.password_policy_length)
* Explain textually Security.password_policy_complexity at least when it is the default one. Some common regex could receive a description, too.

Currently, it doesn't even state them when they fail, eg. «Password length requirement not met»

**Comment by adulau** [comment]
Indeed, this is a very good point. We need to update MISP to show the policy currently applied. Another thing that we are working is ensure that NIST SP 800-63-3 is followed in MISP.

We will update MISP to allow simpler passphrase in replacement to complex rule composition for longer password used. (to match [Appendix A: Strength of Memorized Secrets](https://github.com/usnistgov/800-63-3/blob/6e5a6c566898ae579ff84d863dd303681978ac94/sp800-63b/appA_memorized.md))

**Comment by Keisial** [comment]
Sorry @iglocska This issue wasn't about the description shown to the admin being wrong (I was unaware of that) but about showing the password requisites to MISP users, so they don't have to guess how to create an acceptable password.

**Comment by iglocska** [comment]
Just added the changes for that, there is a new hover over element that will reveal the password requirements!
