### ISSUE TITLE
FireEye MPS Integration

### ISSUE THREAD

**Issue by myntric** [MISP/MISP#212]
Feature request for the ability to somehow integrate reports and auto-population of events from the FireEye Forensic Analysis as an alternative to GFI Sandbox.

**Comment by elhoim** [comment]
[This project](https://github.com/BechtelCIRT/fe2stix) has an example FireEye notification in JSON, and the code to convert it to STIX.

**Comment by adulau** [comment]
There is a tool doing FireEye to MISP:

https://github.com/deralexxx/FireMISP

**Comment by 00willo** [comment]
> There is a tool doing FireEye to MISP:
> 
> https://github.com/deralexxx/FireMISP

FYI, this project had its last commit on 12 Jun 2017.

**Comment by adulau** [comment]
It could be indeed an old plugin. It's difficult to know and follow exactly what FireEye product is available in 2022. 

There is a specific plugin available on the market place of FireEye https://fireeye.market/apps/235984

If I need to update the tools page of MISP, let me know.
