### ISSUE TITLE
restSearch API returns invalid json when multiple events are found

### ISSUE THREAD

**Issue by robinlandstrom** [MISP/MISP#2125]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS, Linux 3.10.0-514.6.1.el7.x86_64
| OS version (client)       | curl 
| PHP version               | 5.6.25
| MISP version / git hash   | MISP 2.4.70

### Expected behavior
A valid json response containing two events
`
{ "response":[ { "Event":{ ... } }, { "Event":{ ... } } ] }
`
### Actual behavior
Invalid json with event objects following directly on each in a list without a separating ","
`{
   "response":[
      {
         "Event":{ ... }
      }      { 
         "Event":{ ... }
      }
   ]
}`

### Steps to reproduce the behavior

Make a query to the restSearch API for anything that returns more  than one result

`$curl -H  "Authorization: MY-APIKEY" https://192.168.0.3/events/restSearch/download/evildomain/domain/null/null/null/null/null/null/null/null/null/null/null.json > invalid.json`

**Comment by FloatingGhost** [comment]
Cannot confirm.

`curl -H "Authorization: <key." http://localhost:81/events/restSearch/download/aaa.prop/domain/null/null/null/null/null/null/null/null/null/null/null.json | jq`

returns 2 results in a valid JSON on b3cfca1

**Comment by iglocska** [comment]
It was indeed a bug briefly but has been fixed a few days ago, please make sure you git pull.

**Comment by robinlandstrom** [comment]
Ok, thanks for checking it out, will update! 👍
