### ISSUE TITLE
CTI Toolkit help

### ISSUE THREAD

**Issue by Mokatani** [MISP/MISP#2130]
Hello everyone,
i am trying to use the CTIToolkit from CERT Australia to process STIX file and output to our local MISP. I have installed the package as it mentioned in CTI Toolkit Documentation.
Wenn i try to run the given command in Examples section: 
stixtransclient.py --file CA-TEST-STIX.xml --stats

I see the following error:
stixtransclient.py: error: argument -s/--stats: not allowed with argument -m/--misp

What should i do?

Thanks and best regards,
Mohammad

**Comment by david74552** [comment]
This looks like an issue that could have been submitted to https://github.com/certau/cti-toolkit.
Did you by any chance create a static configuration file "/etc/ctitoolkit.conf" or "~/.ctitoolkit" as per the instructions of https://cti-toolkit.readthedocs.io/en/latest/configure.html ?
That could be where the -m argument is coming from.
