### ISSUE TITLE
BUG/QUESTION with Galaxies/Clusters

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2131]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Changing threat-actor.json values
I've would like to change the naming scheme of some threat-actors so instead of Sofacy it shows up as BADGUY1 (for example) doing this and reimporting the galaxies untags that event and it has to be retagged.. and even having the tags already changed and importing an event doesn't tag it with the new tag either.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Question
| OS version (server)       | Fully up up date CentOS 6.8
| OS version (client)       | Firefox on Windows 10
| PHP version               | 5.6.25
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior

event's with the old name get changed to the new name

### Actual behavior

it just removes the threat-actory galaxy tied to the event

### Steps to reproduce the behavior

edit your json and change the name of something and then reimport it.

**Comment by iglocska** [comment]
The problem with that is that internally, threat actors are bound to events via tags. These tags use the primary value (so in this case Sofacy) as the "glue" via tags.

So `misp-galaxy:threat-actor="Sofacy"` is the actual tag. By changing the Value from Sofacy, a new tag has to be created.

**Comment by ghost** [comment]
Yes I noticed that and built a script to go through and rename that in the xml and json files.. though it would be a nice if that did work somehow.. maybe a feature in the future..? what happends when a group splits or two merge? does everyone have to go through and retag everything?

**Comment by ghost** [comment]
I'm going to close this ticket as my question has been answered and I've build a simple perl script to help me. :) Thank you.
