### ISSUE TITLE
MISP version Error

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#2132]
With the actual version 2.4.71, on diagnostics tab, when we are looking for the version we got the following message:
***********************
Currently installed version..... v2.4.71 (b024c69a1249d618d994a6843d862f8039f5fb56)
Latest available version..... v2.4.71 (b024c69a1249d618d994a6843d862f8039f5fb56)
Status..... OK
Current branch..... 2.4.59

git pull origin 2.4.59 2>&1

From https://github.com/MISP/MISP
 * branch            2.4.59     -> FETCH_HEAD
Already up-to-date.

=================================

git submodule init && git submodule update 2>&1
***********************

Best regards,

**Comment by iglocska** [comment]
OK, now that is weird. Are you on the 2.4.59 branch? Could you git checkout 2.4 and the git pull origin 2.4?

**Comment by FafnerKeyZee** [comment]
Ok, 
my bad, sorry the file was locked in read only since an old issue ./

**Comment by iglocska** [comment]
Ah ok :)
