### ISSUE TITLE
Freetext import not working

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#2133]
Hello,

with the latest version, the freetext import is not working. When we try to validate the choices on the 'Freetext Import Results' page, nothing happens when clicking on Submit button.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 8
| PHP version               | 5.6.30-0+deb8u1
| MISP version / git hash   |  v2.4.71 (b024c69a1249d618d994a6843d862f8039f5fb56) 
| Browser                   | chrome/IE/Firefox

### Expected behavior
Adding the attributes in the Event

### Actual behavior
Doing nothing

### Logs, screenshots, configuration dump, ...
No log ./

**Comment by iglocska** [comment]
Sorry we're having some issues with an experimental JS replace gone wrong, reverting it now, best is to git checkout cc57e0eca4220c98376d16a4a5b7de6c779b1f32

in the meanwhile. Sorry for the inconvenience.

**Comment by iglocska** [comment]
2.4 should again be cleaned up. Could you git pull?

**Comment by FafnerKeyZee** [comment]
It is working (and by the way fix an other problem when trying to delete attribute) 
so it's solve :)

**Comment by iglocska** [comment]
Excellent news and sorry :)
