### ISSUE TITLE
Unable to add a user via the rest API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#2134]
It always fails at that line (and returns a full HTML page instead of an error message in JSON: https://github.com/MISP/MISP/blob/2.4/app/Controller/UsersController.php#L407

==> `if ($this->request->data['User']['notify']) {`

**Comment by iglocska** [comment]
Thanks for the heads-up, should now be fixed.

**Comment by Rafiot** [comment]
Thanks!

**Comment by iglocska** [comment]
My pleasure <3
