### ISSUE TITLE
Bug: Ip-dst attribute should not be able to include a "/"

### ISSUE THREAD

**Issue by CERT-Bund** [MISP/MISP#2138]
### Work environment

| MISP version  | 2.4.72

### Expected behavior
- IP address attribute should not be able to include a "/". 

### Actual behavior
We had one event, where an analyst managed to include a "/" in the ip-dst attribute.
It looked liked "1.2.3.4/"

We found this bug, as this IP-DST attribute is getting correlated with a lot of others IP attributes which are completely different, e.g. "1.2.3.4/" was correlated with "2.5.7.8".
See screenshot

### Steps to reproduce the behavior
1. Create IP-DST attribute 1.2.3.4
2. Edit attribute. Change 1.2.3.4 to 1.2.3.4/
We have one MISP where this works and the attribute is getting changed to include the "/", but on our second MISP server (also on 2.4.72), only an error is getting thrown:  Error: An Internal Error Has Occurred.

### Logs, screenshots, configuration dump, ...

![misp bug](https://cloud.githubusercontent.com/assets/10919077/25170764/f124b8d8-24eb-11e7-8c98-a7432b021a2d.jpg)

**Comment by iglocska** [comment]
Thanks a lot, should be fixed now.
