### ISSUE TITLE
Q: Why are there two different ways to add an attribute to an event?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2140]
(subject says it all)

Sorry if this is obvious but why is there both an "Add Attribute" option in the side menu as well as the small "+" symbol? I see that both are, e.g., being used within the MISP book but can't seem to find any differences between the two...

**Comment by iglocska** [comment]
It's a matter of preference which one you use, the + will load the attribute add form as an overlay whilst the add attribute button redirects. It's the same form though internally.

**Comment by StefanKelm** [comment]
Thanks, Andras, for the swift clarification.

**Comment by iglocska** [comment]
No worries!
