### ISSUE TITLE
ip|port correlation occurs when port is the same (80/443/8080 included)

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#2141]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| MISP version / git hash   | 2.4.72, b9bdcd013247cf5b518635ad3682777c47cb1859

### Actual behavior
Using : 
Network activity > ip-dst|port correlation is made on the port (including 80/443 and 8080)
( I guess the same would happen with ip-src|port )

### Screenshots
Kovter config correlating with 2 events containing ip-dst|port from Kelihos config
![Kovter config correlating with 2 event containing ip-dst|port from Kelihos config](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/izvLMHGz1SWchiF/upload.png)
But no overlapping in fact as correlation is made on tcp port : 
![Correlation on tcp 80](https://s3.amazonaws.com/uploads.hipchat.com/164777/2603869/pEltRhHevju48me/upload.png)

**Comment by iglocska** [comment]
That is indeed plain wrong, will fix it asap!

**Comment by droe** [comment]
Any progress on this? I'm seeing this behaviour too, common ports cause correlation of events that are completely unrelated to each other. Correlation on the port does not seem to be very useful in practice.

**Comment by droe** [comment]
Awesome, thank you Andras!

**Comment by iglocska** [comment]
Thanks for the reminder, have completely forgotten about this ;)
