### ISSUE TITLE
Dealing with third part Intel Feeds 

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#2143]
Hi, I have a question about how to deal with third party intel feeds.
We subscribe to a well known threat intel provider for intel and they provide indicators via an API.
I'm struggling with figuring out how to import this into MISP. I thought about using the feeds option.

The API this vendor provider doesn't use the concept of 'events' so I was wondering if anyone has any suggestions about how to import and intergrate this feed into MISP.

The output of the API is a JSON based feed with indicators, relations, reports, labels. etc.

Appreciate any feedback that people may have.

Thanks.

**Comment by iglocska** [comment]
If they are using a custom JSON format then I think your best bet is writing a mapping and feeding the data to MISP via the API using PyMISP. Do you happen to know what format they use? Is it documented anywhere?

**Comment by jezkerwin** [comment]
Yes it is documented (I can't share it because it's commercial in confidence) so I am aware that I'll have to map the fields.

What I'm struggling with is the MISP concept of 'events' and how to integrate this feed of indicators that doesn't have an event associate with it. There are some indicators that have a 'report' number associated with it, I suppose I could use that as an event.

**Comment by iglocska** [comment]
Indeed, MISP events are basically loose containers for indicators. An event can be an actual security event, it can be a report, or it can simply be an indicator collection with some common traits that made the information producer bundle it.

In the case of feeds, we generally either have a single event that is updated over time with all of the indicators over time (so removals and additions) or alternatively we take snapshots of the feed every day or so and store those as a separate event (though this will create a bunch of unnecessary correlations). This is of course just one possible approach, splitting the feed by reports makes total sense.

**Comment by jezkerwin** [comment]
Thanks, I think your explanation of Events as just containers of indicators has helped me with the mental block I had in getting past the concept of an event.
