### ISSUE TITLE
[QUESTION] Implementation of new schema

### ISSUE THREAD

**Issue by jdubp** [MISP/MISP#2144]
Hi,

We are currently on version 2.4.70. I saw the MISP schema recently underwent a fairly significant rewrite and was wondering if these changes are in 2.4.71/2.4.72 or are geared toward the next larger MISP release? We utilize several scripts in conjunction with PyMISP for automating communications with MISP and the new schema would require some modifications to those, so I wanted to know if this was implemented yet to better plan when we take the next MISP update.

Thanks for your hard work!

**Comment by Rafiot** [comment]
The schema has been rewritten to make it more readable, but it doesn't change the way it works and the old exports will still validate.

**Comment by jdubp** [comment]
Ok, thank you for the clarification. I was thinking that using a REST call (PyMISP or otherwise) to return an event would send back JSON differently. For instance:

New schema
"event": {
   "properties": { 
        "id" : { 

Old schema
"Event" : {
    "id" : "123

Meaning if i was parsing an event id with a script, i would need to look for [event][properties][id] instead of [Event][id]. If it doesn't affect any kind of JSON being returned from REST calls, I'm good to go, but just wanted to be sure.

**Comment by iglocska** [comment]
Definitely not, ['Event']['id'] is what MISP expects.

**Comment by Rafiot** [comment]
It is not what the schema mean. 

You can lookup some examples here: http://json-schema.org/examples.html

**Comment by jdubp** [comment]
Thank you!
