### ISSUE TITLE
Slow deletion of events with many related events

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/MISP#2145]
Long story short, one of my automated feeds blew up last night and created 5500+ events with the same MD5. Now, all of these events are related to each other. I've since fixed the problem with the script that handles the automated feed, but I'm currently trying to clean up the mess it made via the API (per PyMISP's delete_event()). 

The problem is, it's taking roughly 8 seconds to successfully delete each of the ~5500 events. I'm assuming this is because it has to process something to delete each of the relationships in the db for every event/attribute...? Is this normal behavior and, if so, is there a better way to go about deleting this large amount of events that are all related to each other?

MISP 2.4.69

**Comment by syloktools** [comment]
I am having the same issue. I am trying to delete all the events add by a certain ORG and it is taking that same amount of time or longer.

**Comment by hel10wor1d** [comment]
Yes I had the same issue at some point as well. It took a weekend for the script to clean up the mess (just left it running in the background). I think it takes that long because of all the correlations between all the duplicate events, as result of the exact same attributes existing in each one. It also bogged my entire MISP system down terribly when trying to access any event (via the API/GUI), but once all the duplicate events were deleted from the MISP instance, the entire GUI/event loading was more responsive.

Would be great if there was a way that correlations for the same IOC in different events, were automatically disabled when its from the same source/feed, to avoid these kind of problems.

**Comment by TheDr1ver** [comment]
Well, it's been a good run, but after almost 4 years it's happened to me again. (Considering this old issue suddenly got labeled 15 hours ago, I'm thinking I'm not the only one affected by this particular org haha)

A connected org decided to share out ~25k events of what appear to be sandbox reports. In this instance, 1 event = 1 file, and all the sandbox details for that file (like AV detections) are included as attributes to the event. They also managed to check the "correlate" box for every single one of those attributes, so things like AV vendor names, number of AV detections, and important text attributes like "number of detections" are all correlated.

Fortunately, my MISP instance got hosed pretty quickly and I managed to stop it from adding more events after about 1700 had been loaded, but now I've got 1700 events and each one has about 1700 correlations. I'm trying to run a PyMISP script to delete all of them, but it once again is taking an insane amount of time to delete a single event.

If anyone has a faster way to put out this dumpster fire that got dumped in my lap overnight your input would be greatly appreciated!

**Comment by TheDr1ver** [comment]
https://www.circl.lu/doc/misp/faq/#how-can-i-deal-with-a-misp-instance-that-has-pulled-in-feeds-over-and-over-into-new-events-generating-hundreds-of-gbs-of-junk-correlations-rendering-the-instance-unusable

`completely_disable_correlation` was ultimately was the solution to nuking all the nonsense that came in. Set to True, run a PyMISP script that nukes everything from the offending org, then after it runs for a few minutes and deletes everything, set `completely_disable_correlation` back to False. 

It took maybe 20-30 minutes to repopulate ~600k correlations across the entire database, whereas trying to delete all the garbage events while correlations were enabled was taking close to 5 minutes PER EVENT.

This can probably be closed.
