### ISSUE TITLE
Unable to access Server settings, Jobs, or Publish Events after PHP 7.0 upgrade on CentOS/RH 7

### ISSUE THREAD

**Issue by jdubp** [MISP/MISP#2146]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

This may be related to issue 2086, but we just upgraded from php56 to php70 as php56 is below the recommended php version for MISP. As part of the update, the process for installing CakeResque was duplicated for php70 (which also required using pecl redis-3.1.2 rather than 2.2.8). We are using an older version of redis server 2.8 currently and have not used php-redis as it is not available in our repos.

After the update we receive "Service Unavailable" when accessing Server Settings, Jobs, and when trying to Publish an event. All other areas of MISP work fine and these three areas worked fine with PHP 5.6. Details are below, but the only error we can find is php-fmp keeps exiting on signal 11 when attempting to perform the above tasks. Disabling CakeResque returns "An Internal Errors Has Occurred".

I'm wondering if there is some compatibility issue with CakePHP/CakeResque and PHP 7.0? Any tips in troubleshooting or has anyone else successfully loaded PHP 7.0 on Cent OS 7 and had no issues?

It's looking like we may have to downgrade back to PHP 5.6 unless I'm missing something.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, support
| OS version (server)       | RedHat 7.2
| OS version (client)       |  Seven
| PHP version               | 7.0
| MISP version / git hash   | 2.4.7.2
| Browser                   | If applicable

### Expected behavior
Ability to access Server settings, Jobs, and Publish events

### Actual behavior
**With CakeResque enabled** (in bootstrap.php, bootstrap => true and MISP.background_jobs, true ; in core.php, /Vendor/autoload.php uncommented), we receive "Service Unavailable" error. There are no errors found in /var/www/MISP/app/tmp/logs related to this and no errors found in /var/log/redis. There are however errors in /var/log/httpd/misp.local_error.log (proxy_fcgi:error) and it appears php-fpm is being killed and restarted when attempting to access Server settings, Jobs and Publish Events. 

**With CakeResque disabled**, (above steps ignored), we receive "An Internal Error Has Occurred." instead of the Service Unavailable error. The only error found is in /var/www/MISP/app/tmp/logs/error.log and php-fpm does not exit and restart as it does when CakeResque is enabled.

2017-04-22 05:04:55 Error: [Error] Class 'ResqueStatus\ResqueStatus' not found
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(843): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

### Steps to reproduce the behavior
Clicking on Server settings or Jobs within the Administration menu in MISP.

**Comment by iglocska** [comment]
There shouldn't be any compatibility issue, however, it sounds like your php extensions are gone after the install. Could you make sure you retrace those steps from the installation, especially the ones that touch cakeresque.

**Comment by jdubp** [comment]
I finally found the time to do a fresh install on another device with CentOS/RH7 and PHP7.0. All steps were followed and permissions checked. Below are the errors I am able to get. Any ideas?

/var/log/httpd/misp.local_error.log
[Sat May 20 10:50:57.056709 2017] [proxy_fcgi:error] [pid 21024] (104)Connection reset by peer: [client <IP>:52847] AH01075: Error dispatching request to :, referer: http://<MISP URL>/users/view/1


/var/opt/rh/rh-php70/log/php-fpm/error.log
[20-May-2017 10:50:57] WARNING: [pool www] child 28382 exited on signal 11 (SIGSEGV) after 472.271011 seconds from start
[20-May-2017 10:50:57] NOTICE: [pool www] child 28409 started


/var/www/MISP/app/tmp/logs/error.log
2017-05-20 07:50:57 Warning: Warning (2): fopen(/var/www/MISP/app/tmp/logs/test.txt): failed to open stream: Permission denied in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/File.php, line 136]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fopen - [internal], line ??
File::open() - APP/Lib/cakephp/lib/Cake/Utility/File.php, line 136
File::write() - APP/Lib/cakephp/lib/Cake/Utility/File.php, line 228
Server::writeableDirsDiagnostics() - APP/Model/Server.php, line 2847
ServersController::serverSettings() - APP/Controller/ServersController.php, line 827
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-05-20 07:50:57 Warning: Warning (2): unlink(/var/www/MISP/app/tmp/logs/test.txt) [<a href='http://php.net/function.unlink'>function.unlink</a>]: Permission denied in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/File.php, line 282]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
unlink - [internal], line ??
File::delete() - APP/Lib/cakephp/lib/Cake/Utility/File.php, line 282
Server::writeableDirsDiagnostics() - APP/Model/Server.php, line 2849
ServersController::serverSettings() - APP/Controller/ServersController.php, line 827
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-05-20 07:50:57 Error: [MethodNotAllowedException] Non numeric PID found.
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(843): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by jdubp** [comment]
I ended up reinstalling PHP 56 on CentOS/RHEL 7 and now everything works, so it appears there is some compatibility somewhere with PHP 70. I know the MISP Server Settings area complains about the PHP version being below 7 (which is recommended), but appears doesn't work. Is there any reason why PHP above 56 is being recommended? We have not tried PHP71 as it's not available in our repos currently.

**Comment by onekriach** [comment]
I have the same issue to after upgrade php56 to PHP70 on Centos7 (x64).

**Comment by BenjaminJoly** [comment]
Is this issue is still relevant ? 

I've tried to upgrade php on my CentOS 7 (x64). I've done two tests, one with php 7.1 and another php 7.0, and each has worked.   

To let you know what I've done, just a `yum remove rh-php56*`, and just followed point 2 (installation of dependencies) and 4 (installation of dependencies) from the CentOS 7 Install tuto ( https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt ), by replacing all `php56` with `php70` or `php71`.
Of course, I've also done a git pull on my MISP instance to have it up to date. 

Hope this will help people at least.

**Comment by adulau** [comment]
Based on the test of @BenjaminJoly and the feedback of the user, we will close the ticket. If the issue persists, feel free to reopen the ticket.

**Comment by RichieB2B** [comment]
I just attempted to upgrade from rh-php56 to rh-php70 and I have the same issues as described in this original bug report. It looks like MISP can't read/interpret the information about the workers and bails. Only the workers and `/servers/serverSettings` are broken. MISP works fine otherwise. Reverting back to rh-php56 fixes the issue.

Is there an easy way to flush the worker-pool info from redis?

**Comment by RichieB2B** [comment]
Ok, the data inside redis is not the issue. I narrowed this down to a nasty bug in 7.0.10 which is the initial version of PHP shipped by Ret Hat Software Collections for RHEL-6. There is an update to 7.0.27 which fixes the issue.

**Comment by iglocska** [comment]
Wow, really?

**Comment by RichieB2B** [comment]
Yep, I can confirm that upgrading to rh-php70 7.0.27 fixes this issue. I’m very interested to see which PHP bug this is, but can’t find it right now. It was corrupting variables inside the getWorkers() function.
