### ISSUE TITLE
postgrey missing table

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2149]
I have this error when I try to initiate postgrey table

Here the error when you try to execute initial data (psql -U misp -d misp -f INSTALL/POSTGRESQL-data-initial.sql -h localhost -W) :
```bash
psql:INSTALL/POSTGRESQL-data-initial.sql:213: ERREUR:  la relation « org_blacklists » n'existe pas
LIGNE 1 : INSERT INTO org_blacklists (id, org_uuid, created, org_name,...
                      ^
psql:INSTALL/POSTGRESQL-data-initial.sql:214: ERREUR:  la relation « org_blacklists » n'existe pas
LIGNE 1 : ...VAL('org_blacklists_id_seq', (SELECT MAX(id) FROM org_blackl...
```

The request seems to correct the problem.
```sql
CREATE TABLE IF NOT EXISTS org_blacklists (
  id bigserial NOT NULL ,
  org_uuid varchar(40) NOT NULL,
  created timestamp NOT NULL,
  org_name varchar(255) NOT NULL,
  comment TEXT,
  PRIMARY KEY (id));
 create index org_uuid on  org_blacklists(org_uuid);
 create index org_name on org_blacklists(org_name);
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | correction
| OS version (client)       | Debian
| PHP version               | 7.0
| MISP version / git hash   | 2.4.72
| Postgres                | 9.4

Have you try to work with postgrey ?

**Comment by adulau** [comment]
We recent PR fixed this issue: https://github.com/MISP/MISP/commit/699be1ed3007610c0a57dc9c553a0b5c1b25ab4f Could you try the latest HEAD? thank you.

**Comment by BenjaminJoly** [comment]
As the issue should be corrected by now, I close the issue. If you want me to reopen it, please, do not hesitate to ask me.
