### ISSUE TITLE
Proposal: display # of attributes from within an event

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2151]
Currently, the home screen lists "#Attr." per event.

Would it make sense to also have the # of attributes available while viewing an event? 

If yes, the # of attributes could be displayed either at the info section (e.g., close to 'Sightings'), or as part of the 'Filters' tab, e.g., bracketed after the 'All' tab - such as _All (23)_

**Comment by iglocska** [comment]
Nice idea, went with option 2.

**Comment by iglocska** [comment]
Option 2 is really describing the number of entries though (attributes + proposals + soon objects), so to also have the actual attribute count and the paginated element total count there was only one solution when picking an option:

![whynotboth](https://cloud.githubusercontent.com/assets/3668672/25485209/5c6c5f70-2b5d-11e7-9c5d-3aa24440bc6f.jpg)

**Comment by StefanKelm** [comment]
Awesome! Now that was fast, thanks so much.

However, the GUI output now is slightly garbled:

![misp-screenshot](https://cloud.githubusercontent.com/assets/25325656/25487214/d41746a6-2b63-11e7-99d7-9d2c636b1851.jpg)

**Comment by iglocska** [comment]
Interesting, on it!

**Comment by iglocska** [comment]
Ah indeed, forgot to push one of the files, should be fine now :)

**Comment by StefanKelm** [comment]
Almost: the GUI now is fine but when I now filter for certain attribute types the bracketed number changes after the filter has been applied. E.g., _All (7)_ becomes _All (4)_ when I select the 'Network' filter and the event contains 4 network related attributes.

**Comment by iglocska** [comment]
Well that's annoying - should be better now. Let me know if it still acts up!

**Comment by StefanKelm** [comment]
Thanks, Andras, it works fine now.

**Comment by iglocska** [comment]
Excellent news, thanks for the heads-up! Will close the issue now, feel
free to open new ones if you run into issues ;)

Edit: Never mind if was closed already
