### ISSUE TITLE
Events with List Warnings

### ISSUE THREAD

**Issue by zoni171** [MISP/MISP#2153]
Folks,

Not sure if this exists already. I was not able to find it on the UI.

Input Filters > List Warnings

Would be nice to have a choice for "View events with warnings". On that all possible warnings and an option to select all or just a few.

Use case: user wants to know all events that have alexa top 1k domains, all events with url shortners, etc.
It may be a way to control / reduce FPs. Being able to list events with list warnings would be a nice thing to have IMO.

**Comment by adulau** [comment]
It's indeed a very good point. We will have a look how we could do it efficiently.
