### ISSUE TITLE
Discrepancy between INSTALL instructions and GUI Critical Settings for MISP.baseurl

### ISSUE THREAD

**Issue by se-te** [MISP/MISP#2157]
In the https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt file we can read:

```
# Change base url in config.php
sudo -u www-data vim /var/www/MISP/app/Config/config.php
# example: 'baseurl' => 'https://<your.FQDN.here>',
# **alternatively, you can leave this field empty if you would like to use relative pathing in MISP**
# 'baseurl' => '',
```

Since indeed I would like to use relative pathing in MISP (to be allowed to connect to the same instance with 2 different URLs), I was interested and did exactly that.

But then, leaving 'baseurl' empty as suggested in the INSTALL document triggers an error in the Critical Settings of the GUI:

```
Value not set.
The base url of the application (in the format https://www.mymispinstance.com). Several features depend on this setting being correctly set to function.
```

It seems that the INSTALL document and the Server settings need to be aligned.

On a side note, is it possible to use 2 different URLs to access the same MISP instance?
Thank you!

**Comment by adulau** [comment]
Documentation updated
