### ISSUE TITLE
Proposal notification failures for "at least one recipient"

### ISSUE THREAD

**Issue by Keisial** [MISP/MISP#2158]
When making a proposal to another org, MISP tries to alert its members by email.
However, it may find it is not able to notify everyone, in which case the proposer receives this message:
«The proposed Attribute has been saved but sending out the alert e-mails has failed for at least one recipient.»

However, I am more concerned on whether *anyone* received the notification than if *everybody* did. If someone received it, it will (hopefully) be handled internally, but if nobody did, I may need to bug them through different means.

Incidentally, ShadowAttribute::sendProposalAlertEmail() should be returning a boolean, but if the event has an email lock, it calls "return;", with no parameter, which will return a null, and then the above message would be shown as it is weakly compared (==) to false. So it ends up doing the right thing for the wrong reasons. An explicit return false would be in order imho.

**Comment by iglocska** [comment]
Nice finds, absolutely correct. Could you open a PR for this?

**Comment by Keisial** [comment]
Sure. I can prepare a patch. Should it only differentiate between "Not sent to anyone" and "Sent to someone" or should it keep a "Sent to some people" notification?

Best

**Comment by iglocska** [comment]
Not sent to anyone is indeed more interesting, I think differentiating
between no one and someone as you mentioned makes the most sense.

Thanks a lot!
