### ISSUE TITLE
Unable to cancel a sync job

### ISSUE THREAD

**Issue by BurntToast-DFIR** [MISP/MISP#2162]
Feature request / question

Would it be possible to have a way of cancelling running tasks.  I have a sync job running to another server with many events.  This is generating a huge number of emails which my organisation have asked to have stopped.  I have removed the remote server from my list of synced servers but the tasks continue even after a complete reboot.  Being able to cancel the task would be very useful.

Regards
Andy Dove

**Comment by iglocska** [comment]
Reboot should definitely have killed the job, basically if you flush redis and restart the workers it should be enough. Are you sure it's not just the job progress that is still present in the table?

**Comment by BurntToast-DFIR** [comment]
The emails are still coming through in a steady stream.  How do you flush redis?  I'll try a reboot again.

**Comment by RichieB2B** [comment]
If all you wanted to do was stop the E-mail flow while the sync job finished, there is a setting for that: `MISP.disable_emailing`
