### ISSUE TITLE
Attribute correlations re-appear

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2166]
I'm running the MISP Virtual Machine with everything (including OS) updated to the latest, greatest version (MISP v2.4.72).

When toggling correlations off on a single attribute the correlations sometimes re-appear, e.g., after making subsequent changes to the attribute (such as adding a tag). Re-loading the event/refreshing the browser windows does not help:

![correlation-screenshot](https://cloud.githubusercontent.com/assets/25325656/25809625/de9d54b4-340d-11e7-9947-5ae7afe06c5a.png)

**Comment by SteveClement** [comment]
@StefanKelm This is fixed in latest. Please re-open if still an issue.
