### ISSUE TITLE
Provide CLI to update taxonomies / warninglists / galaxies

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2168]
After updating MISP it is required to manually update the taxonomies / warninglists / galaxies using the web UI. It would be much easier if there would be a command line way of doing this. Especially since updating the warning lists can easily take longer than the PHP timeout permits. Possibly related to #1831

**Comment by adulau** [comment]
It seems that I was slower to add the labels than @iglocska implementing it.

**Comment by iglocska** [comment]
You were faster with responding then me writing a commit message though ;)))
