### ISSUE TITLE
Attribute warning: This event doesn't have any attributes visible to you.

### ISSUE THREAD

**Issue by LegitUsername** [MISP/MISP#2171]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug?
| OS version (server)       | Debian jessie 8.8
| OS version (client)       | Seven
| PHP version               | 7.0.18-1~dotdeb+8.1
| MISP version / git hash   | 2.4.73
| Browser                   | Chrome

### Expected behavior
My MISP instance is synchronised with the main one from the CIRCL and I should be pulling all attributes from the events that are share with "all communities" (provided that the attributes have the right sharing seeting in their field "distribution").

### Actual behavior
I do not pull the attributes, even when they are set as "all" or "inherit".
 - Exemples of events from which I pull attributes as expected: 7604 (Event="all communities" & attributes="inherit") , 7776 (same parameters)
 - Exemples of events I pull but they do not present any attributes: 7799, 7800, 7801 ... and all of them have Event="all communities" and attributes="all" or "inherit"

And when browsing these "empty" events I get the error message "_Attribute warning: This event doesn't have any attributes visible to you. Either the owner of the event decided to have a specific distribution scheme per attribute and wanted to still distribute the event alone either for notification or potential contribution with attributes without such restriction. Or the owner forgot to add the attributes or the appropriate distribution level. If you think there is a mistake or you can contribute attributes based on the event meta-information, feel free to make a proposal_"

This issue seem to be a few days old (first "empty" event is 7770 and most of them are empty since).

### Steps to reproduce the behavior
Unknown

**Comment by adulau** [comment]
I was able to reproduce the bug. We will have a look asap. Thank you.

**Comment by iglocska** [comment]
Nice catch, could you git pull and check if it still happens for you? Will keep the issue open until then.

**Comment by LegitUsername** [comment]
Sorry for the delay.
I pulled and all the events were properly populated with their attributes.

Thanks again !

You guys may close the ticket :)

**Comment by iglocska** [comment]
Excellent news, thanks for the feedback! B-)
