### ISSUE TITLE
UPGRADE.SH script - dangerous behaviour 

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#218]
Hi,

We quickly reviewed the upgrade process and found something that seems a bit dangerous to do on production systems:

curl -s https://getcomposer.org/installer | php

Not only executing code before reviewing it but especially if something goes wrong with the communication you won't know the state of its execution.

Maybe the UPGRADE.SH is just for documentation and not to be run ;-) In this case, this is fine.

Cheers.

**Comment by Rafiot** [comment]
fact.

**Comment by iglocska** [comment]
UPGRADE.SH has been removed a while back.
