### ISSUE TITLE
STIX download returning An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by jdubp** [MISP/MISP#2181]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, support
| OS version (server)       | RedHat 7.2
| OS version (client)       | Windows
| PHP version               | 7.0
| MISP version / git hash   | 2.4.72
| Browser                   | If applicable

### Expected behavior
Download event as STIX XML/STIX JSON

### Actual behavior
When attempting to generate a STIX download from a MISP event within the GUI, I receive

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <response><name>An Internal Error Has Occurred.</name><message>An Internal Error Has Occurred.</message><url>/events/stix/download/1138.xml</url></response>

In looking at /var/log/messages on the server, below is the error returned

May 11 05:29:17: detected unhandled Python exception in '/var/www/MISP/app/files/scripts/misp2stix_framing.py'
May 11 05:29:18: Executable '/var/www/MISP/app/files/scripts/misp2stix_framing.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'
May 11 05:29:18: 'post-create' on '/var/spool/abrt/Python-2017-05-11-05:29:17-22335' exited with 1
May 11 05:29:18: Deleting problem directory '/var/spool/abrt/Python-2017-05-11-05:29:17-22335'

In looking at /var/www/MISP/app/tmp/logs/error.log, below is the error returned
2017-05-11 05:33:59 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download/1138.xml
Stack Trace:
#0 [internal function]: EventsController->stix('download', '1138')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

I've followed the steps in https://github.com/MISP/MISP/issues/1669 and it is not a permissions issue
sudo -H -u apache bash -c 'python /var/www/MISP/app/files/scripts/stixtest.py'
{"cybox": "2.1.0.14", "stix": "1.2.0.4", "success": 1}

Any ideas in troubleshooting, particularly the misp2stix_framing.py python error?

### Steps to reproduce the behavior
Within an Event choose, Download as and then STIX XML

**Comment by jdubp** [comment]
EDIT: I fixed the error to enable handling of unpackages software by abrt-server
May 11 05:29:17: detected unhandled Python exception in '/var/www/MISP/app/files/scripts/misp2stix_framing.py'
May 11 05:29:18: Executable '/var/www/MISP/app/files/scripts/misp2stix_framing.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'

Although I'm still getting An Internal Error has Occurred though with minimal info to go off of in the error.log file.

**Comment by jdubp** [comment]
I found another error log that may be of some meaning:

id 3025e6f7b1326ec30a41a16922605873f09f73cb
reason:         **misp2stix_framing.py:93:main:AttributeError: 'module' object has no attribute 'idgen'**
time:           Thu 11 May 2017 06:12:55 AM PDT
cmdline:        python /var/www/MISP/app/files/scripts/misp2stix_framing.py http://<mispserver> xml
uid:            48 (apache)
count:          1
Directory:      /var/spool/abrt/Python-2017-05-11-06:12:55-25679
Run 'abrt-cli report /var/spool/abrt/Python-2017-05-11-06:12:55-25679' for creating a case in Red Hat Customer Portal

**Comment by FloatingGhost** [comment]
Right you are!

STIX moved idgen to the mixbox project a while back, but I think they had backwards compatibility (until recently I guess ;))

I'm gonna put in a PR that *should* fix this, I hope.

Here's where we hope stix properly uses mixbox.

**Comment by iglocska** [comment]
Stix, the gift that keeps on giving

**Comment by jdubp** [comment]
Thanks for looking into this! I found that by downgrading to Stix 1.1.1.7, the functionality will work as currently coded. Any version newer than that has errors.

**Comment by intoro** [comment]
Has attempting to generate a STIX download from a MISP event within the GUI been fixed or worked on? I am receiving the error described above.
