### ISSUE TITLE
Clear mysql database?

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#2184]
Is there a way to clear the mysql MISP database without deleting the whole database and recreating the database. For example, I added a couple test events and deleted them, but of course the eventid starts with the next number vice starting back at 1. I would like to have clear the database information, so the eventid will start back at 1.

| Type of issue             | Question
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 5.6
| Browser                   | If applicable

**Comment by FloatingGhost** [comment]
See tools/misp-wipe :)

**Comment by gra55h0pp3r** [comment]
Thanks for the help. I looked at the bash script, but I only want to truncate the events that were added only and not clear the whole database as I have all the settings set and all users created.

**Comment by FloatingGhost** [comment]
misp-wipe doesn't wipe settings, but it does wipe users.

just remove lines 48+ from misp-wipe.sql and it won't do anything with users;

**Comment by gra55h0pp3r** [comment]
Thanks! I made a few other changes and everything worked. Thanks!
