### ISSUE TITLE
Feed overlap analysis matrix broken

### ISSUE THREAD

**Issue by alexgoedeke** [MISP/MISP#2185]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)      |  Ubuntu 16.04.2 LTS
| OS version (client)       |  Windows 7
| PHP version               | 7.1.4-1
| git hash   | 81141ed4e0a03403089f14f6c76a7c1f37175c2c
| Browser                   | Chrome

### Logs, screenshots, configuration dump, ...

![bug](https://cloud.githubusercontent.com/assets/14151646/25987773/a45fa924-36f5-11e7-8941-64b09f2d1ccc.PNG)

**Comment by iglocska** [comment]
Did you click cache all on the feed index.first? The feeds also have to be
set to enable.

**Comment by alexgoedeke** [comment]
@iglocska yes feeds are cached

but seems a problem on chrome, in IE it works

**Comment by alexgoedeke** [comment]
Problem was fixed by restarting the server after updating MISP via git

now everything is working also in chrome

**Comment by adulau** [comment]
Ok perfect. We will close the issue. Feel free to reopen it if required.
