### ISSUE TITLE
Baseurl / rewrite Problems

### ISSUE THREAD

**Issue by t-sec-cons** [MISP/MISP#2192]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.2 LTS
| OS version (client)       | Seven
| PHP version               | 7.0
| MISP version / git hash   | v2.4.71
| Browser                   | Chrome

### Expected behavior
Misp should use the 'baseurl' config to calculate all links.

### Actual behavior
If you try to use a subdirectory of a domain for baseurl, or the relative path (let the 'baseurl' variable empty) it works for some urls and links, but on some urls the subdirectory is missing and not rewritten.
I have an apache setup where the MISP-instance is running as an alias ( /misp/ pointing to /var/www/xyz/) on my virtual host (using /var/www/html as root directory).
For example if you try to use a filter on the event list, you get "**Not Found
The requested URL /events/index/searchall:wannacry was not found on this server.**".
Correct URL is /**misp**/events/index/searchall:wannacry , which is working if you try it manually.

### Steps to reproduce the behavior
- add an alias directory to the apache vhost (ie: Alias /misp /var/www/html/MISP/app/webroot )
- set the baseurl to the alias ( 'baseurl' => 'https://xyz.com/misp/' ) or to relative ('baseurl' => '')
- try to add a filter to the event list

**Comment by t-sec-cons** [comment]
I looked into it and it seems the baseurl is not writen into every view.
For example the quicksearch button in View/Events/index.ctp Line 43 is hardcodet as /events/index.
You can add <?php echo $baseurl;?> before, to fix this issue. Looks like this is the case in multiple files.

**Comment by t-sec-cons** [comment]
In addition baseurl is completely missing in webroot/js/misp.js, so no javascript buttons are working.

**Comment by t-sec-cons** [comment]
Found the same issue in #1431, sorry for the duplicate. Its not only in javascript, so maybe you take this as an addition to #1431.

**Comment by 1inkman** [comment]
Good day! I have this problem too, is it not fixed?

**Comment by SteveClement** [comment]
bump @iglocska

**Comment by SteveClement** [comment]
Dear all, if possible just leave the Base URL empty for the time being.

**Comment by iglocska** [comment]
Please make sure that you get the absolute latest version (as of writing this message) before doing that from HEAD. Basically before that, the baseurl setting had several uses: It is indeed used to pre-pend URLs in MISP to enforce absolute paths, but it was also used as an "announce" URL in sharing groups.

What this means: If you left it empty, your sharing groups would not include a URL through which other MISPs can share back to you.

I've added a new setting that will allow you to set an external baseurl - this is the URL announced to other instances via sharing groups and used for inclusion in e-mails sent out by MISP. Make sure you set the external baseurl and leave the regular baseurl empty.
