### ISSUE TITLE
correlation active when disabled in admin

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2206]
in /servers/serverSettings/MISP.

my option is : 

| Setting      |     Value     |   
| ------------- | -------------   | 
| MISP.completely_disable_correlation      |     true     |
| MISP.allow_disabling_correlation       |    false     |

when I add 2 events with the same attribute, attribute continue to be correlated.

I want to disable this function for better perf.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| OS version (server)       | Debian, ubuntu
| OS version (client)       | Ubuntu, debian, 
| PHP version               | test with  5.5.9 and  7.0
| MISP version / git hash   | Currently installed version..... v2.4.73

### Expected behavior
Disable all related event function.
Improve performance when massive event creation
add event with this greate feature by api take more than 20s by events :(
### Actual behavior
The correlation is still active even after it has been deactivated in the configuration

### Steps to reproduce the behavior
set completely_disable_correlation to 'True'
create 1 event with 127.0.0.1 (for exemple) as attribute
create a new event with again 127.0.0.1 as attribute.

You will see that the correlation is still active.

**Comment by truckydev** [comment]
Correlation is active  when I add a tag on an attribute too :(

**Comment by SteveClement** [comment]
@iglocska this becomes somewhat of a priority as more and more people have the need to disable correlation and seem to be unable to do so.
Also those seem to be dependencies: https://github.com/MISP/MISP/issues/3207 https://github.com/MISP/MISP/issues/2241

**Comment by mokaddem** [comment]
Hi,
We recently fixed a bug preventing the edit of ``disable_correlation``. Feel free to re-open if this issue is not solved.
