### ISSUE TITLE
2FA for users

### ISSUE THREAD

**Issue by przemekzn** [MISP/MISP#2220]
Hello,
Does MISP support 2FA for MISP's users?
I would like to run 2FA (client x.509 certificate and password) for MISP's users which are connecting to GUI. Can I run 2FA in MISP settings or should I change Apache configuration?

**Comment by adulau** [comment]
You can indeed use a reverse-proxy to handle the 2FA/OTP authentication and pass the parameters as an HTTP header.

`https://<YOURMISP>/servers/serverSettings/Plugin`
`https://www.circl.lu/doc/misp/appendices/#undefined`

This works with LDAP, AD and HTOP authentication scheme.

**Comment by bpavesi** [comment]
Hello,
it's also possibile to integrate google Authenticator? If yes, how? It's necessary to develop an authentication plugin or use a reverse proxy?
Somewhere it's avaiable a guide regarding this topic?
