### ISSUE TITLE
SSL server certificate installation

### ISSUE THREAD

**Issue by fabrimagic72** [MISP/MISP#2228]
Hello,
i have installed MISP with docker and i now need to install a SSL certificate on my server in order to get rid of browser warnings. What is the correct procedure?
Thanks in advance,
Fabrizio

**Comment by iglocska** [comment]
Have a look here on how to do it:

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

**Comment by adulau** [comment]
I suppose the support is solved. Then we will close the issue. Feel free to reopen if the issue persists.
