### ISSUE TITLE
ElasticSearch Integration - Performance improvement

### ISSUE THREAD

**Issue by subscape** [MISP/MISP#223]
Has there been any consideration for using ElasticSearch for performance improvement?

**Comment by elhoim** [comment]
Any update on this?

**Comment by cvandeplas** [comment]
I started to look into using Elasticsearch to store the data.
However it will not be that easy. My hope is to try and get (free) support by the company to be able to use their expertise and give advice.

The biggest issue so far is that elasticsearch does not support arrays in the data.
Well it does, but as far as I understood it mixes everything. As an example says more than a thousand words, imagine you have a json object that contains:
```
Event
  - Attribute 1 : type = type_a, category = cat_i, value =value_1
  - Attribute 2 : type = type_b, category = cat_j, value = value_2
```
The association type/category/value is lost. So all the type, category and values from all the attributes are mixed together in a pool.
This means that when you search for something like "where type=type_a and value=val_2" , you will get this event as a result. 

A workaround for this would be to store all the attributes separately. 
And either embed the event-data in each attribute (and creating huge redundancy), or create another index with all event-data (but that's not good as this is doing relational-database stuff on a non-relational database)

So this needs more investigation to be successful.

**Comment by adulau** [comment]
With the [ZMQ pub-sub channel](https://www.circl.lu/doc/misp/misp-zmq/), users can easily integrate with ELK. Regarding the ELK format, PR are welcome.

**Comment by adulau** [comment]
FYI, a functionality has been introduced to log to ElasticSearch in additional to ZMQ in the MISP version 2.4.94.

**Comment by moshemal** [comment]
@cvandeplas you don't have to store the data on elasticsearch. It is possible only to index the data and retrieving it on the current database
