### ISSUE TITLE
MISP feeds

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#2233]
Does it make sense to configure my barncat MISP as a MISP feed?

How do I get my DGA feeds (osint.bambenekconsulting.com/feeds) as a MISP feed?

**Comment by adulau** [comment]
For the first question, Indeed this makes a lot of sense as the cache lookup is done in Redis. Have you tried to generate a feed from your whole dataset? https://github.com/MISP/PyMISP/tree/master/examples/feed-generator But in this case, we won't recommend to import it but just use the caching of feed. Maybe we will have an option to fully disable the MISP import and keep only the cache ( @iglocska what do you think?) .

For your second question, I just added two of your feed in the default MISP feed: 

https://github.com/MISP/MISP/blob/96a23e45894bc542b416ebabe6cac91d61a7b189/app/files/feed-metadata/defaults.json#L803

If you want to add some more, it's easy. Add them in your MISP, export the JSON of the feed and add it in the defaults.json array. We will gladly accept the PR ;-)

**Comment by bambenek** [comment]
Will take a look at generating a feed from Barncat. Will review the second to see what feeds make sense.

**Comment by adulau** [comment]
Resolved as @bambenek proposed PR was merged.
