### ISSUE TITLE
hvae you running this system for public?

### ISSUE THREAD

**Issue by zhongdi** [MISP/MISP#2235]
have you running this system for public to share the Malware information or you just share the code of the platform？

**Comment by iglocska** [comment]
This is the github page for the software/data-format/classifications and the MISP ecosystem itself, though most of us run or are involved with sharing communities. 

For more information have a look at http://www.misp-project.org/communities/

**Comment by iglocska** [comment]
Closing the issue for now, feel free to open new topics if you have any other questions.
