### ISSUE TITLE
Move data to a new MISP instance?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#2237]
Here is the scenario:
- I've a MISP instance running, connected to other instances
- Users defined, local warning lists etc...
version: 2.4.67

I've setup a new instance (2.4.74) and I'd like to migrate all the data to decommission asap the old one. Is there a procedure to follow? Best practices? Tips?
Any experience (good or bad)

I checked the database schemas and they are not the same. Using mysqldump will not work.

**Comment by RichieB2B** [comment]
I think mysqldump will work just fine. Embedded in the schema is the MISP schema number, so MISP 2.4.74 will notice the schema is outdated and upgrade it. Try it, if it doesn't work just put back the 2.4.67 mysqldump you saved as backup.

**Comment by iglocska** [comment]
indeed, mysqldump will work, just make sure you also move your attachment/sample repository from /var/www/MISP/app/tmp/files

**Comment by xme** [comment]
The mysqldump technique did it. I had to recreate some indexes (just checking the logs).
Also, I had to use the previous salt! (in config.php).
Tx for your comments!

**Comment by iglocska** [comment]
Excellent, thanks for the feedback! Will close the issue for now.
