### ISSUE TITLE
"disable_correlation" does not work as intended at attribute addition/edition through the API

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#2241]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| PHP version               | 7.0
| MISP version / git hash   | v2.4.74 (6fad375685b07e560820918d7ffbf52054029630) 

### Expected behavior

At attribute addition/edition through the API ("/attributes/add", "attributes/edit"), the correlation of the given attribute must only be calculated if the "disable_correlation" is set to "true" in the transmitted JSON object. 

### Actual behavior

The "correlate" checkbox of the attribute appears unchecked in the UI, but the list of correlating events still appear in the corresponding column. 

### Steps to reproduce the behavior

POST a JSON-formated attribute to /attributes/add passing "disable_correlation" => "true". Of course, be sure that your attribute will get some correlations in your existing events.

**Comment by StefanKelm** [comment]
This may be related to https://github.com/MISP/MISP/issues/2166 ?

**Comment by truckydev** [comment]
related to this too https://github.com/MISP/MISP/issues/2206

**Comment by iamshleya** [comment]
I am also running into this issue. Has there been any update or workaround for this?

**Comment by iglocska** [comment]
Interesting, will try to have a look

**Comment by mokaddem** [comment]
Should be fixed by now.
Feel free to re-open if needed.
