### ISSUE TITLE
Setting redis in bootstrap.php overrides config.php upon login

### ISSUE THREAD

**Issue by ppanero** [MISP/MISP#2246]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       |7
| PHP version               |  5.6
| MISP version / git hash   | 2.4 latest
| Browser                   | If applicable

### Expected behavior
Not override config.php file

### Actual behavior
setting up redis in bootstrap.php as:
```php
Cache::config('default', array(
        'engine' => 'Redis', //[required]
        'duration'=> 3600, //[optional]
        'probability'=> 100, //[optional]
        'prefix' => Inflector::slug(APP_DIR) . '_', //[optional]  prefix every cache file with this string
        'server' => '127.0.01', // localhost
        'port' => 6379, // default port 6379
        'timeout' => 0, // timeout in seconds, 0 = unlimited
        'persistent' => true, // [optional] set this to false for non-persistent connections
));
```
upon login the config.php file get changed from full configuration to:
```php
<?php
$config = array (
  'debug' => 0,
  'MISP' =>
  array (
    'uuid' => '<uuid>',
  ),
  'GnuPG' => NULL,
  'SMIME' => NULL,
  'Proxy' => NULL,
  'SecureAuth' => NULL,
  'Security' =>
  array (
    'level' => 'medium',
    'salt' => '<default_salt>',
    'cipherSeed' => '<cipherseed>',
  ),
  'Session.defaults' => 'database',
  'Session.timeout' => 1440,
  'Session.autoRegenerate' => true,
  'site_admin_debug' => NULL,
  'Plugin' => NULL,
  'CertAuth' => NULL,
  'ApacheShibbAuth' => NULL,
  'ApacheSecureAuth' => NULL,
);
```

Not that I have edited the cipherseed, salt and uuid of the instance for public purposes. Logs do not show anything (empty). Except a warning
```
Warning: User organisation 105 changed.
```

**Comment by iglocska** [comment]
Using cakephp's own caches isn't too useful, we've started using our own redis caching for certain functions as of recently which gives us much more flexibility than the simple read/write/increment system.

**Comment by iglocska** [comment]
Will close this for now, I think the best solution is to not fiddle with bootstrap.php, all configuration should happen through config.php. Also, the framework caching isn't really suitable for us ;)

**Comment by ppanero** [comment]
True. Tho its a bit confusing having bootstrap.php there with configs that can be achieved in another manner. But thanks a lot for the help :D issue solved ;)

**Comment by iglocska** [comment]
Yeah, maybe we should clean out bootstrap.php. It used to be where we set settings before the config.php system, it's the default place to do it in the framework, but not in MISP any longer.
