### ISSUE TITLE
MISPego

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#2247]
mtz file recognized by maltego, but do not have the option to run transform against something like a hash. 
updated the file to have base URL and key.

all files should be there:

![image](https://cloud.githubusercontent.com/assets/23529336/26756009/3cf5ef72-4867-11e7-898d-c9e43588b3b3.png)

here's the config of the transforms:

![image](https://cloud.githubusercontent.com/assets/23529336/26756013/5db3bf00-4867-11e7-8df1-a30f814a8639.png)

here's what it looks like when i try to run transform against a hash...
![image](https://cloud.githubusercontent.com/assets/23529336/26756017/77f82900-4867-11e7-8baf-28e71026ee11.png)

Even after expanding the All Transforms there's still no option to run the MISPego transforms...

Jimbo

**Comment by jimbolya0607** [comment]
Anyone - anyone? hellooooooooooooooooo!

=)

**Comment by FloatingGhost** [comment]
Paging @tomking2 - this is your thing, right?

**Comment by jimbolya0607** [comment]
my thing?
you mean my instance and whatnot?

**Comment by FloatingGhost** [comment]
I was paging in Tom, it's his project I think :P

**Comment by jimbolya0607** [comment]
ha - yea - realized that after i posted...
i'm such a newb =)

**Comment by jimbolya0607** [comment]
Fixed - closing issue. 
Found that there was some misconfiguration on my end, which I expected.  Also was missing the selectevent.py file.  Looked at the other .py files and copied one to test.  Renamed it appropriately and it worked. 

Jimbo
