### ISSUE TITLE
Feed autoimport

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#2249]
We use MISP as a IOC correlation database(works awesome)... is there a way to turn the feeds on automatic so that we get all the intel automatically flowing into the Events?

Thanks for all the great work on this...

**Comment by CheYenBzh** [comment]
I think there is now no possibly to it from the UI now. 
But you can script using PyMisp and the fetch_feed(id_feed) function to automatically pull events from feeds. 

Hope this will solve your problem, at least for a while.

**Comment by iglocska** [comment]
yeah need to tie it into the scheduler one day, however, we have a new and better thing in the pipe so not too keen on touching the existing crappy scheduler before scrapping it anyway. Would an API solution as hinted by @CheYenBzh be something you could live with while we get the new system up and running?

**Comment by mathurin68** [comment]
Thanks guys, I'll look into the fetch_feed(id_feed) function, we are already using the api to pull the IOC's out anyway.
