### ISSUE TITLE
Upgrade v2.4.72 -> v2.4.74 Error

### ISSUE THREAD

**Issue by KorayAgaya** [MISP/MISP#2250]
My Server Details

OS version (server)      :  Ubuntu 16.04.2 LTS
OS version (client)       : Ubuntu 
PHP version                 : PHP 7.0.18-0ubuntu0.16.04.1 (cli)
MISP version               : v2.4.72

I clicked update button on web interface than  give me bellow error information

====ERROR=======

Current branch..... 
git pull origin  2>&1

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

=================================

git submodule init && git submodule update 2>&1

**fatal: unable to access '/var/www/MISP/.git/modules/app/Lib/cakephp/config': Permission denied
Unable to find current revision in submodule path '../Lib/cakephp'**

**Comment by iglocska** [comment]
1. Sounds like you are in detached mode / you are on a different branch. Simply type:
```
cd /var/www/MISP
git checkout 2.4
```
2. Also, you seem to be having some permission issues. The following should solve it (change it as long as you accept the additional risks that an updater via the UI poses):
```
cd /var/www/MISP
chown -R www-data:www-data .git
```
(assuming you use ubuntu with www-data being your apache user)

**Comment by KorayAgaya** [comment]
Thank you for your help. it's works

cd /var/www/MISP
chown -R www-data:www-data .git
git pull
git checkout 2.4

**Comment by KorayAgaya** [comment]
My Mip version is below I clicked button than error 
Currently installed version..... v2.4.71 
Latest available version..... v2.4.84 
Status..... Outdated version	
Current branch..... 2.4	

ERROR -1 
=================
clicked update button

git pull origin 2.4 2>&1

error: cannot open .git/FETCH_HEAD: Permission denied

=================================

git submodule init && git submodule update 2>&1


ERROR 2
==================
change permission 

chown -R www-data:www-data .git/FETCH_HEAD

than clicked UPDATE button

git pull origin 2.4 2>&1

From https://github.com/MISP/MISP
 * branch            2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/composer.json
Please, commit your changes or stash them before you can merge.
Aborting
Updating 406415b..6420b69

=================================

git submodule init && git submodule update 2>&1


===========

How can  I upgrade misp 2.4.71  to 2.4.84 Can You help me please ?
