### ISSUE TITLE
Service Unavailable error when accessing Server Settings and Jobs

### ISSUE THREAD

**Issue by shravaka** [MISP/MISP#2252]
This error appears only when I try to enable CakeResque. Once disabled both in bootstrap.php and config.php - server settings become available. Any ideas what might be the cause?

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, support...
| OS version (server)       | Debian 8.8
| OS version (client)       | Debian 8.8.
| PHP version               | 5.6
| MISP version / git hash   | 2.4.74
| Browser                   | If applicable

### Actual behavior
"An Internal Error Has Occurred." when accessing these section

### Steps to reproduce the behavior
Navigate to Administration => server settings or Jobs

### Logs, screenshots, configuration dump, ...
here's the /var/www/MISP/app/tmp/logs/error.log entry:

2017-06-07 12:58:11 Error: Fatal Error (1): Class 'ResqueStatus\ResqueStatus' not found in [/var/www/MISP/app/Model/Server.php, line 3048]
2017-06-07 12:58:11 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Class 'ResqueSt...', '/var/www/MISP/a...', 3048)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'ResqueSt...', '/var/www/MISP/a...', 3048, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Class 'ResqueSt...', '/var/www/MISP/a...', 3048, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by SyGulmah** [comment]
How did you resolve this? I have the same error. Thank you!
