### ISSUE TITLE
Scheduled Tasks does not work 

### ISSUE THREAD

**Issue by giedriusramas** [MISP/MISP#2254]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       |  ubuntu, 
| OS version (client)       | Ubuntu,
| PHP version               | 7.0.15-0ubuntu0.16.04.4
| MISP version / git hash   | v2.4.72 (a6f13540bbcac898a17d7d7b2d75f96309ad2d5f)	
| Browser                   | If applicable

### Expected behavior
I need push_all scheduled task to run every hour. 

### Actual behavior
push_all scheduled task runs only once after I set up it.  
However I have pull_all scheduled task that runs every 6 hours as I expected . 
How could I debug why push_all task wont run ? All workers are up and working. I do not see errors on scheduler worker's logs. Strange thing that on push_all task Next Run is not being updated automatically as on pull_all task I have.

**Comment by ccpptt** [comment]
How have you managed to get the 'pull_all' task to run every 6 hours?

**Comment by giedriusramas** [comment]
I have made it by following the steps below:
Administration -> Scheduled Tasks -> edit `pull_all`  changed `frequency` time to 6, edited `scheduled time` to some future , changed `next run` to current day.

**Comment by ccpptt** [comment]
As far as I understand, the push_all scheduled task should work in the same manner. If you have configured it to run every x hours beginning in a future time, it should work.

What do you see at:

Administration -> Jobs -> 'Default' tab

**Comment by giedriusramas** [comment]
Here you go:




10265 	2017-06-13 05:33:05 	2017-06-13 05:34:26 	Part of scheduled pull 	default 	pull Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10262 	2017-06-12 23:33:04 	2017-06-12 23:34:09 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10261 	2017-06-12 17:34:08 	2017-06-12 17:34:08 	Part of scheduled push 	default 	push 	Server: 1 	Push to server 1 complete. 	orgname 	Unknown	0 	Completed
10255 	2017-06-12 17:33:03 	2017-06-12 17:34:08 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10254 	2017-06-12 11:52:07 	2017-06-12 11:52:07 	Part of scheduled push 	default 	push 	Server: 1 	Push to server 1 complete. 	orgname 	Unknown	0 	Completed
10253 	2017-06-12 11:50:16 	2017-06-12 11:50:16 	Part of scheduled push 	default 	push 	Server: 1 	Push to server 1 complete. 	orgname 	Unknown	0 	Completed
10250 	2017-06-12 11:33:06 	2017-06-12 11:34:11 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10238 	2017-06-12 05:33:05 	2017-06-12 05:34:30 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10237 	2017-06-11 23:33:06 	2017-06-11 23:34:09 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10236 	2017-06-11 17:33:04 	2017-06-11 17:34:10 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10235 	2017-06-11 11:33:04 	2017-06-11 11:34:08 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done. 	orgname 	Unknown	0 	Completed
10234 	2017-06-11 05:34:17 	2017-06-11 05:35:18 	Part of scheduled pull 	default 	pull 	Server: 2 	Job done.        orgname 	Unknown	0 	Completed




As you can see pull_all job is executed as expected every 6 hours. There is some push_all jobs on the log it is because when I changed `next run` date to the current date or future , but it run only once.

**Comment by iglocska** [comment]
Will have a look, but generally the push all job is pretty pointless (events are pushed automatically when you publish an event)

**Comment by giedriusramas** [comment]
What is strange that I have it working some time ago. However it once stopped working . 

"events are pushed automatically when you publish an event", Does it mean that if I have one remote sever to pull events and another one to push events to, once events are pulled from remote server they are automatically pushed to remote server as well ?

**Comment by iglocska** [comment]
That is indeed correct. Pulling will auto-publish the events on your instance and pass it on, as long as the distribution levels allows for it, to any instance that you are pushing to*.

*Unless you've set the "unpublish" setting in your sync server object.
