### ISSUE TITLE
SQL database corruption?

### ISSUE THREAD

**Issue by carnak** [MISP/MISP#2256]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Seven
| PHP version               | 7.0.18
| MISP version / git hash   | v2.4.74 (8722c5bb160b981920eed316ed02e30a0061a061) 
| Browser                   | firefox

### Expected behavior

I expect to be able to submit new attributes

### Actual behavior

When submitting new attribute, included stack trace results in /var/www/MISP/app/tmp/logs/error.log

### Steps to reproduce the behavior

adding any attribute produces this behavior now

### Logs, screenshots, configuration dump, ...

2017-06-09 07:12:58 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '__inet_to_bits' at line 1
Request URL: /attributes/add/2911
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('__inet_to_bits', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('__inet_to_bits', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(616): DboSource->fetchAll('__inet_to_bits', Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(834): DboSource->query('__inet_to_bits', Array, Object(Attribute))
#5 /var/www/MISP/app/Model/Attribute.php(1334): Model->__call('__inet_to_bits', Array)
#6 /var/www/MISP/app/Model/Attribute.php(1393): Attribute->__ipv6InCidr(']_a}', '2604:45d0::/28')
#7 /var/www/MISP/app/Model/Attribute.php(1424): Attribute->__cidrCorrelation(Array)
#8 /var/www/MISP/app/Model/Attribute.php(553): Attribute->__afterSaveCorrelation(Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#12 /var/www/MISP/app/Controller/AttributesController.php(174): Model->save(Array)
#13 [internal function]: AttributesController->add('2911')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#17 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}

**Comment by onekriach** [comment]
I have gor the same error when create a new attribute Category Network Activity and type IP...

**Comment by onekriach** [comment]
2017-06-09 13:56:48 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your
 MariaDB server version for the right syntax to use near '__inet_to_bits' at line 1
Request URL: /attributes/add/950
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('__inet_to_bits', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('__inet_to_bits', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(616): DboSource->fetchAll('__inet_to_bits', Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(834): DboSource->query('__inet_to_bits', Array, Object(Attribute))
#5 /var/www/MISP/app/Model/Attribute.php(1332): Model->__call('__inet_to_bits', Array)
#6 /var/www/MISP/app/Model/Attribute.php(1332): Attribute->__inet_to_bits('\x05\xBB\x03\x18')
#7 /var/www/MISP/app/Model/Attribute.php(1391): Attribute->__ipv6InCidr('5.187.3.24', '2803:d890::/28')
#8 /var/www/MISP/app/Model/Attribute.php(1422): Attribute->__cidrCorrelation(Array)
#9 /var/www/MISP/app/Model/Attribute.php(552): Attribute->__afterSaveCorrelation(Array)
#10 [internal function]: Attribute->afterSave(true, Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): call_user_func_array(Array, Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#14 /var/www/MISP/app/Controller/AttributesController.php(174): Model->save(Array)
#15 [internal function]: AttributesController->add('950')
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#19 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#20 {main}

**Comment by onekriach** [comment]
Is it bug of new release?

**Comment by onekriach** [comment]
Also the same error I have got during fetch all events from feed.
My env 
Centos7 x64 
MISP v2.4.74 
MariaDB 10.2.6
PHP 5.6.25

[2017-06-09 14:02:51] main.INFO: got {"queue":"default","id":"1c1f04d81c7253c1be5c04c612fa9d5a","class":"ServerShell","args":[["fetchFeed","1","26","968"]]} {"type":"got","args"
:"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"1c1f04d81c7253c1be5c04c612fa9d5a\",\"class\":\"ServerShell\",\"args\":[[\"fetchFeed\",\"1\",\"26\",\"968\"]]})","worker":
"misp-issp:24479"} []
[2017-06-09 14:02:51] main.INFO: Processing ID:1c1f04d81c7253c1be5c04c612fa9d5a in default {"type":"process","worker":"misp-issp:24479","job_id":"1c1f04d81c7253c1be5c04c612fa9d5
a"} []
[2017-06-09 14:06:58] main.ERROR: {"queue":"default","id":"1c1f04d81c7253c1be5c04c612fa9d5a","class":"ServerShell","args":[["fetchFeed","1","26","968"]]} failed: SQLSTATE[42000]
: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near
'__inet_to_bits' at line 1 {"type":"fail","log":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds
to your MariaDB server version for the right syntax to use near '__inet_to_bits' at line 1","job_id":"1c1f04d81c7253c1be5c04c612fa9d5a","time":247335,"worker":"misp-issp:24479"}
 []

**Comment by iglocska** [comment]
Investigating now!

**Comment by carnak** [comment]
Thank you!

Thanks,
Alan

**Comment by iglocska** [comment]
Let me know if it isn't resolved through the patch!
