### ISSUE TITLE
Api:9000Controller

### ISSUE THREAD

**Issue by jstnk9** [MISP/MISP#2258]
I'm experiencing an issue with CakePHP.

In the /var/www/MISP/app/tmp/logs/error.log file I get this error.

2017-06-09 14:08:45 Error: [MissingControllerException] Clase del controlador Api: 9000Controller no se encontró.
Atributos de excepción: array (
   'Class' => 'Api: 9000Controller',
   'Plugin' => NULL,
)
URL de solicitud: / api: 9000 / modules
Rastro de la pila:
# 0 /var/www/MISP/app/webroot/index.php(92): Dispatcher-> dispatch (Object (CakeRequest), Object (CakeResponse))
# 1 {main}

**Comment by iglocska** [comment]
It sounds like you have used an invalid url. If you want to use port 9000 use the format:

```
protocol://hostname:port/controller/action/parameters
```

**Comment by iglocska** [comment]
I'll close this issue for now, if you still encounter the issue when using a properly formatted url, let us know in a new issue please!

**Comment by panzertime** [comment]
I think this may be a bug in pymisp.  That's how we're doing our API accesses right now and we're seeing the same thing.  Will investigate further.
