### ISSUE TITLE
Add mixbox to the INSTALL documentation

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2261]
The subject says it all...

**Comment by iglocska** [comment]
Yep, running into issues with just that now too.

**Comment by FloatingGhost** [comment]
Can we just create a new standard to purge STIX once and for all?

It's nothing but trouble for all involved.

**Comment by RichieB2B** [comment]
https://xkcd.com/927/

**Comment by iglocska** [comment]
Solved by https://github.com/MISP/MISP/commit/1db9f8c0744ae6804c51a67cfec1d6981c2e26f9
