### ISSUE TITLE
Missing install documentation of mixbox

### ISSUE THREAD

**Issue by newdominic** [MISP/MISP#2262]
I was trying to get a fresh build on Ubuntu 16.04 today.
The diagnostics page keeps showing "STIX or CyBox or mixbox library not installed correctly"
By running stixtest.py, found out that mixbox is not installed yet.
Currently, I used these commands to pass the diagnostic.

`cd /var/www/MISP/app/files/scripts/`
`git clone https://github.com/CybOXProject/mixbox.git`
`cd /var/www/MISP/app/files/scripts/mixbox`
`git checkout v1.0.2`
`python setup.py install`

**Comment by iglocska** [comment]
Thanks a lot, adding it to the install guide!
