### ISSUE TITLE
Some of the attachments failed to upload. 

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#2268]
Get this error lately when trying to upload documents.  However, those documents aren't in the system.  Happens on instances that have never had this doc as well. 

Exact error: 
Some of the attachments failed to upload. The failed files were: Kittyhawk Intel Governance and Process Guide v1.4.pdf - This can be caused by the attachments already existing in the event.

**Comment by FloatingGhost** [comment]
It's probably worth checking in your php.ini that upload_max_filesize is larger than the file you want to upload - it's only set to 2MB by default, PDFs can easily go over that

**Comment by jimbolya0607** [comment]
FloatingGhost - you rock!
You always get to my issues asap lol. 
I can't check the box now, but will this weekend for sure. 

Thanks!

**Comment by jimbolya0607** [comment]
As a side - did you write this?
https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/export_mod/cef_export.py

**Comment by FloatingGhost** [comment]
Yeah that was me~

**Comment by jimbolya0607** [comment]
Ahh cool - mind if i pick your brain about some stuff?
I'm trying to get MISP to push things to a SIEM and what not now. 

I got MISPego working the other day.  I think I closed that issue.  Everything working just fine now =).

**Comment by FloatingGhost** [comment]
I can't say I've ever actually used any SIEMs, I just knew that our SOC used CEF as their format so wrote that little thing - so I don't think I can help here :< 

(I'll close this issue, but feel free to comment on)

**Comment by jimbolya0607** [comment]
ha - but you wrote it...
that's far more than i could do at this point =)
i think i'm gonna try some integration with splunk first.
found a splunk CEF app.
would like to be able to take new MISP data and send over to something like splunk to generate an email alert for our SOC folks. 
I've worked with SIEMs but never at the engineering level.  mostly for rules and hunting.

**Comment by jimbolya0607** [comment]
also - how do you become a MISP member?
are there like secret meetings and what not?

**Comment by FloatingGhost** [comment]
>are there like secret meetings and what not?

Have you not been invited to the MI.lluminaty yet? Dissapointing.

>how do you become a MISP member? 

Probably by submitting so many PR's as to annoy adulau enough to just go "screw it we'll add you"

 >ha - but you wrote it...

I did indeed - doesn't mean I use it though!

**Comment by jimbolya0607** [comment]
MI.Iluminaty - never heard of it
Where do I send requests to?

**Comment by adulau** [comment]
@jimbolya0607 could you send your details to info@circl.lu? if you want to join the CIRCL MISP community.

**Comment by jimbolya0607** [comment]
Ghost I was able to find the php.ini files and changed the size.  Actually changed the size on all four files. 
See image:
![image](https://user-images.githubusercontent.com/23529336/27248651-bff675be-52d4-11e7-8cd5-b0d6dbc7c7f8.png)


However, that didn't solve the issue...

**Comment by jimbolya0607** [comment]
restarted apache and rebooted the box - still no change...

**Comment by iglocska** [comment]
There are actually 2 settings that you need to change, upload_max_filesize and post_max_size (the latter always has to be at least the size of upload_max_filesize) ;) 

Let us know if it's still not working!

**Comment by jimbolya0607** [comment]
change upload max file size to mirror max file size.  did this on all four php.ini files that i could find. 
no change. 

![image](https://user-images.githubusercontent.com/23529336/27264682-c9346dba-5451-11e7-8ff4-39afe5ebdf13.png)

**Comment by jimbolya0607** [comment]
So the error states that the file already exists.  I'm wondering if maybe the max number of uploads needs to be changed.  Found this while browsing around in MISP issues. 

Please ignore. After further troubleshooting and other errors in the "Attachments" section it turned out that these errors were caused by the limits in the default php.ini configuration (post_max_size, upload_max_filesize, **max_file_uploads**).

Will check and see if that's the issue.  I'm wondering if it's counting the number of times I've tried to upload.  Though that wouldn't make sense since I received the same error on an empty instance.  However, the php.ini might not have been adjusted on the other instance.  I'll have to back track.  Will posts updates when I can.

**Comment by jimbolya0607** [comment]
I'm a freakin' idiot.  
I was working on dev and trying to upload to master.  
*sigh*
Made changes to master, restarted apache2, works just fine now...

**Comment by iglocska** [comment]
That's bound to happen every now and then, been there done that... 😉

Glad you've figured it out!

**Comment by adulau** [comment]
I'll close the issue. Don't hesitate to reopen it if the issue persists. Thank you very much.
