### ISSUE TITLE
Problem with 2 instances of MISP communicating each other

### ISSUE THREAD

**Issue by vasiloiuadrian** [MISP/MISP#2271]
Hi,
   I have 2 instances of MISP 2.4.75 (Running on CentOS 6.9 and PHP 7.0.20) that are named **Our Organization** and **Other Organization** that are connected as remote Organizations (for testing purpose). 
1. If I add a new event on **Our Organization** and the publish it, it appears on **Other Organization** , but If I add an attachment on the same event, from **Other Organization** and then publish it, it doesn't appear in **Our Organization**. So **Our Organization** -> **Other Organization** works  but to respond from **Other Organization** - > **Our Organization** on the same event it doesn't work.
2. If I add a new event from **Other Organization** and publish it, it appears on **Our Organization**, so the connection is bi-directional. So **Other Organization** -> **Our Organization** works for a new event but to respond/add attribute from **Our Organization** -> **Other Organization** it doesn't work.
It appears that I cannot "respond" on a event that I have not initiated (from both instances), although the instances seem to communicate each other.
Are there any settings to be done in order to add/respond to a event that I do not own but I received from another instance?
![event](https://user-images.githubusercontent.com/29433891/27287185-8e2b744c-550b-11e7-8be0-1b41471bcc88.JPG)

Thank you,
Adrian 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | CentOS
| OS version (client)       | 6.9
| PHP version               | 7.0.20
| MISP version / git hash   | 2.4.75
| Browser                   | Chrome

**Comment by iglocska** [comment]
For 1, that is intended. Are you editing the event on Other Organisation as a site admin? You are breaking the trust by doing that, only the creating organisation is allowed to modify the event. On the remote side, make sure you use **proposals** to make changes to the event.

For 2, it's the same issue, MISP's tampering protection is kicking in and protecting the data from 3rd party tampering. 

I'll close the issue for now, feel free to open a new one if you have issues with the proposal system.

**Comment by vasiloiuadrian** [comment]
I tried like you said but it doesn't work. If I create an event on Instance1(as an Org. Admin) and publish it, it appears on Instance2(logged on as an Org. Admin) and If I try to propose an attribute, I can't see it in the Instance1. Do I have to approve the proposal? on what instance?
![instance1](https://user-images.githubusercontent.com/29433891/27328846-3a9f00ee-55bc-11e7-8ea9-2e96db525afa.JPG)
![instance2](https://user-images.githubusercontent.com/29433891/27328847-3c0a89c6-55bc-11e7-8250-6bd5d81706eb.JPG)
Is there a manual where this is explained? what are the steps to follow?

**Comment by RichieB2B** [comment]
Did you perform a pull on the first MISP server, pulling data from the second server? This is when the proposals are transferred.

**Comment by vasiloiuadrian** [comment]
That was the problem. I thought that the pull is done automatically...is there a way to make it like that? I have to pull all the time?
