### ISSUE TITLE
An internal Error has occured

### ISSUE THREAD

**Issue by mtaufikak** [MISP/MISP#2273]
Hi,

I have Ubuntu Server 14.04.05. I have followed the tutorial "INSTALL.ubuntu1404.txt" to install MISP but, when I try to reach the homepage, I have the error "An Internal Error Has Occured". Here is the stack traces from /var/www/MISP/app/tmp/logs/error.log :

2017-06-20 13:29:28 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[28000] [1045] Access denied for user \'server\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(84): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2017-06-20 13:29:43 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /index
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-06-20 13:29:52 Error: [MissingControllerException] Controller class PhpmyadminController could not be found.
Exception Attributes: array (
  'class' => 'PhpmyadminController',
  'plugin' => NULL,
)
Request URL: /phpmyadmin
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-06-20 13:29:58 Error: [MissingControllerException] Controller class MysqlController could not be found.
Exception Attributes: array (
  'class' => 'MysqlController',
  'plugin' => NULL,
)
Request URL: /mysql
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

I have read the issues related to my error, but I didn't find anything. Thank you in advance for your help.

**Comment by adulau** [comment]
As you can see in your log above, I have extracted the relevant information:

~~~~
 Access denied for user 'server'@'localhost' (using password: YES)'
~~~~

Your MySQL configuration and user permissions are not properly setup. Thank you.
