### ISSUE TITLE
Issue with attribute additions caused by correlation errors

### ISSUE THREAD

**Issue by kx499-zz** [MISP/MISP#2277]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16
| OS version (client)       | 7
| PHP version               | 7.0.
| MISP version / git hash   | 2.4.76
| Browser                   | If applicable

### Expected behavior
Add Attributes through Web and API reliably 

### Actual behavior
Errors out on random attributes after I pushed upgrade from 5.6 to 7.0

### Steps to reproduce the behavior
Add Attribute -> Network/Domain -> Spins forever (if done through API gives a 500)

### Logs, screenshots, configuration dump, ...
2017-06-20 22:05:39 Error: [PDOException] SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
Request URL: /attributes/add/15251
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(1535): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /var/www/MISP/app/Model/Attribute.php(554): Attribute->__afterSaveCorrelation(Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#6 /var/www/MISP/app/Controller/AttributesController.php(174): Model->save(Array)
#7 [internal function]: AttributesController->add('15251')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by kx499-zz** [comment]
maybe loosely related to this one: https://github.com/MISP/MISP/issues/2146

**Comment by kx499-zz** [comment]
Here is the error message associated with the same through the API:
2017-06-20 22:03:57 Error: [PDOException] SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
Request URL: /events/5949d40c-3a78-4aec-b52f-2c7ec0a8419c
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(1535): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /var/www/MISP/app/Model/Attribute.php(554): Attribute->__afterSaveCorrelation(Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Attribute->afterSave(true, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1968): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#6 /var/www/MISP/app/Model/Event.php(2388): Model->save(Array, Array)
#7 /var/www/MISP/app/Controller/EventsController.php(1350): Event->_edit(Array, Array, '15251')
#8 [internal function]: EventsController->edit('15251')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by truckydev** [comment]
Do you have all the modules php7.0 installed with ```php -m``` ?
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

maybe 1 miss ...

**Comment by kx499-zz** [comment]
These are the modules from your list that I don't have:
apcu
bz2
curl
gd
imagick
ldap
pdo_pgsql
pgsql

Also my output has this for Zend modules:
[Zend Modules]
Zend OPcache

**Comment by kx499-zz** [comment]
I added all the missing ones with the exception of these and still getting the same errors:
ldap
pdo_pgsql
pgsql

**Comment by kx499-zz** [comment]
uninstalled php7 and reinstalled php5.6 - issue still persists. php7 does not appear to be the issue. 

Further digging an it appears only some attributes wont submit, those attributes so far appear to exist in other events. If I delete the attribute than I can add it without issue - It appears to be an issue with correlation some how. My only guess now.  Any ideas?

**Comment by kx499-zz** [comment]
Validated it appears to be the correlation is borked. Disabled correlation on an event - and attribute added just fine. with correlation enabled it fails.

**Comment by kx499-zz** [comment]
Just to close the loop on this. Resolution entailed forcing a manual re-correlation by setting the Server Setting "Correlation Disabled" to True, what for completion, then set it back to False. Afterwards the error went away. 

I'm open to any ideas as to what could cause this type correlation hiccup so I can avoid going forward. Leaving this issue open for a few days to see if I can get any suggestions and renaming the issue appropriately.

**Comment by iglocska** [comment]
Woah ok, this definitely sounds weird. Maybe some weird orphaned
attributes? Could you check your diagnostics page, it has a tool to check
for orphaned attributes - if you have any use the other tool below it to
get rid of them.

**Comment by kx499-zz** [comment]
Thanks for the suggestion. I did check for orphaned attributes (figured that may have been the case) and there were none. I also cleaned the model cache - neither of those had any affect.

**Comment by iglocska** [comment]
There is also a recorrelation tool if you ever need it again, it's well hidden though in the legacy tool kit (server settings -> diagnostics -> legacy tools)

**Comment by adulau** [comment]
I'll close the issue. Don't hesitate to reopen it if the issue persists. Thank you very much.
