### ISSUE TITLE
New apache directive with apache 2.4

### ISSUE THREAD

**Issue by ninSmith** [MISP/MISP#2278]
### Description

By following https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt
the apache conf file is: https://github.com/MISP/MISP/blob/2.4/INSTALL/apache.misp.ssl

The apache conf file uses:

```
                Order allow,deny
                allow from all
```

Those directives should be replace with ```Require all granted``` for apache 2.4 (which is the version installed if following the install guide):

```
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
#                Order allow,deny
#                allow from all
                Require all granted
        </Directory>

```
Otherwise, access to the WEB UI is denied:

```
AH01630: client denied by server configuration: /var/www/MISP/app/webroot/
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 1604
| OS version (client)       | N/A
| PHP version               | N/A
| MISP version / git hash   | 2.4.76
| Browser                   | N/A

### Expected behavior

Access to the Web interface.

### Actual behavior

Access denied.

### Steps to reproduce the behavior

Follow https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt on a fresh installed server.

**Comment by FloatingGhost** [comment]
In which patch does that change?

As of `Apache/2.4.18 (Ubuntu)` the install directives work just fine. Do they break backwards compat at some point?

**Comment by iglocska** [comment]
Oh boy, hope they don't. 2.2 -> 2.4 was painful enough.

**Comment by ninSmith** [comment]
FYI I followed http://httpd.apache.org/docs/2.4/upgrading.html#access

**Comment by FloatingGhost** [comment]
```bash
apt-cache showpkg apache2
[snippy snip]
Provides: 
2.4.18-2ubuntu3.2 - httpd-cgi (= ) httpd (= ) 
2.4.18-2ubuntu3 - httpd-cgi (= ) httpd (= ) 
```

Latest version on ubuntu 16.04 is 2.4.18, on which the install docs work just fine!

Going by semver, config files shouldn't break until 3.x.x (or 2.5.x if they're being weird about it)\

So I think it's fine for now

**Comment by iglocska** [comment]
@ninSmith, indeed, looking at the documentation you are indeed correct. Hannah does your conf contain    `Order allow,deny` ? I remember something vaguely about it causing issues and `Require all granted` should work for 2.4 either way.

@ninSmith, could you open a pull request with the ssl conf split into two files, one for 2.2 (same as it is now) and one for 2.4 (with your suggested changes)? If not I'll do it later on, no worries ;)

**Comment by FloatingGhost** [comment]
```
<Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
</Directory>
```

Yep it has it~

**Comment by iglocska** [comment]
Oh wow. That is perplexing.

**Comment by ninSmith** [comment]
@iglocska done, I added two conf files for 2.2 and 2.4 and changed ```INSTALL.ubuntu1604.txt```:

```
# If the apache version is 2.2:
sudo cp /var/www/MISP/INSTALL/apache.22.misp.ssl /etc/apache2/sites-available/misp-ssl.conf

# If the apache version is 2.4:
sudo cp /var/www/MISP/INSTALL/apache.24.misp.ssl /etc/apache2/sites-available/misp-ssl.conf
```

However I don't know if this is needed for the other OS...

**Comment by iglocska** [comment]
Ubuntu is there target os, i am sure someone will complain to us if it doesn't work on another OS. We can revisit it then 😉
