### ISSUE TITLE
populate from OpenIOC does not find any indicators to mapped and saved

### ISSUE THREAD

**Issue by maisenhe** [MISP/MISP#2287]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | OpenIOC does not find any indicators
| OS version (server)       | ubuntu
| OS version (client)       | OS X
| PHP version               |7.1
| MISP version / git hash   | v2.4.76 (1d4bc510bd3e065d0eb1cc6532b083357d136bc4)	
| Browser                   | If applicable

### Expected behavior
Event populated with IOC's from the provided document imported with OpenIOC import.

### Actual behavior
Results of the import:
1 attributes created successfully, 0 indicators could not be mapped and saved.

nothing other than the document is shown as being part of the event.

### Steps to reproduce the behavior
attempt to populate event with any of the documents I have with IOC's in them

### Logs, screenshots, configuration dump, ...

2017-06-26 14:16:53 Warning: Warning (2): simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 139]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
simplexml_load_string - [internal], line ??
IOCImportComponent::readXML() - APP/Controller/Component/IOCImportComponent.php, line 139
EventsController::_addIOCFile() - APP/Controller/EventsController.php, line 2243
EventsController::addIOC() - APP/Controller/EventsController.php, line 1197
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by RichieB2B** [comment]
What OpenIOC document are you trying to import? Is it in fact in the OpenIOC XML format?
