### ISSUE TITLE
Importing Cisco AMP ThreatGrid Feeds

### ISSUE THREAD

**Issue by aqartah** [MISP/MISP#2288]
Hi, 

I'm trying to to import Cisco ThreatGrid feeds into MISP. Is there any easy to do it?

**Comment by adulau** [comment]
I suppose so but I don't have any sample file of Cisco ThreatGrid feeds. Can you share some sample files to us?

If there is a simple textual format (free-text or CSV), you can use the [MISP feed](https://www.circl.lu/doc/misp/managing-feeds/) functionality out-of-the-box.

If the format is a custom Cisco format, you can write a small Python script and use [PyMISP](https://github.com/CIRCL/PyMISP) to import the file into MISP. The [examples directory](https://github.com/CIRCL/PyMISP/tree/master/examples) is full of sample code.

If you want to update the MISP import functionality, you can write an [import module](https://www.circl.lu/assets/files/misp-training/luxembourg2017/4-misp-modules.pdf) to support the format from Cisco in the MISP UI directly.

I hope this helps.
