### ISSUE TITLE
Fresh Install Ubuntu 16.04  - Internal Server Error

### ISSUE THREAD

**Issue by droik123** [MISP/MISP#2289]
Hi, 

This is a tool that I have been looking forward to work with the potential that something like this can do help the Security people is awesome, I really appreciate all the effort and I look forward to using this tool. 

This is my first time at installing this application and I am unsure of what is causing the issue.   I receive an error while accessing the URL stating 'Internal Server Error'

OS: Ubuntu 16.04

The error logs are pasted below 
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-06-27 17:28:04 Error: Fatal Error (16): Exception thrown without a stack frame in [Unknown, line 0]
2017-06-27 17:28:04 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2017-06-27 17:43:11 Error: [ParseError] syntax error, unexpected ''database'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Controller/AppController.php(91): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2017-06-27 17:53:05 Error: [MissingControllerException] Controller class MISPController could not be found.
Exception Attributes: array (
  'class' => 'MISPController',
  'plugin' => NULL,
)
Request URL: /MISP
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-06-27 17:53:05 Error: Fatal Error (16): Exception thrown without a stack frame in [Unknown, line 0]
2017-06-27 17:53:05 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(16, 'Exception throw...', 'Unknown', 0)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(16, 'Exception throw...', 'Unknown', 0, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

Would really appreciate if anyone can guide me in resolving this. 

Regards 

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by droik123** [comment]
PHP Version 
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Browser Chrome

**Comment by FloatingGhost** [comment]
Sounds like you've got an invalid `database.php`!

Can you check that the all the quotes and commas are present in `/var/www/MISP/app/Config/database.php`?

**Comment by iglocska** [comment]
Sounds like a typo in your database.php file when you were filling it out.
Could you sanitise it and paste it?

**Comment by iglocska** [comment]
Damn, I was too slow ;)

**Comment by droik123** [comment]
Here is the database config
************************************************************************
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                //'datasource' => 'Database/Postgres',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'misp',
                'port' => 3306, // MySQL & MariaDB
                //'port' => 5432, // PostgreSQL
                'password' => '********'
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}

**********************************************************************
Unsure of where the error could be

**Comment by iglocska** [comment]
you have a missing "," after the password, could just be a copy paste issue with the sanitisation of course ;)

**Comment by droik123** [comment]
Silly me.. Missed that one :)

**Comment by iglocska** [comment]
No worries, did it get you going or still getting errors? :)

**Comment by droik123** [comment]
Got it going ...  Thanks a Ton :)

**Comment by iglocska** [comment]
Excellent, let us know if you run into any other trouble! ;)

Closing the issue for now, but feel free to open new ones whenever needed!
