### ISSUE TITLE
Import events from an MISP export

### ISSUE THREAD

**Issue by Piosec** [MISP/MISP#2290]
Hi, 

When I try to import events through the web interface it didn't works and no errors are returned. 
All I have is the "Add From MISP Export Result" page, with an empty array below. 

Could you solved it ? 

Thanks.

**Comment by iglocska** [comment]
Any chance you can share the failing export with us? We can do it out of bound if you'd prefer that.

**Comment by Piosec** [comment]
Of course, 
This is the screen after import data 
![screen](https://user-images.githubusercontent.com/26251854/27588313-0f89a670-5b48-11e7-9621-4939f4a29b9e.png)

My log file print this line : 
[Tue Jun 27 14:54:48.406905 2017] [:error] [pid 23070] [client @IP:PORT] PHP Warning:  POST Content-Length of 205130957 bytes exceeds the limit of 104857600 bytes in Unknown on line 0, referer: https://FQDN/events/add_misp_export

I know there is a max size of 100M bytes, do you know how to increase it ?

**Comment by iglocska** [comment]
Ah ok, so that explains the empty result. 

You need to change two directives in php.ini:

upload_max_filesize = 250M
post_max_size = 250M

should do the trick for that particular file.

**Comment by Piosec** [comment]
I changed both directives in "/etc/php/7.0/apache2/php.ini"

I restart php and apached services but now I get a blank page. 

 Should I changed directives into these files too ? 
"/etc/php/7.0/apache2/php.ini.ucf-dist
/etc/php/7.0/cli/php.ini
/etc/php/7.0/fpm/php.ini
/usr/lib/php/7.0/php.ini-development
/usr/lib/php/7.0/php.ini-production
/usr/lib/php/7.0/php.ini-production.cli
/usr/lib/php/7.1/php.ini-development
/usr/lib/php/7.1/php.ini-production
/usr/lib/php/7.1/php.ini-production.cli"

**Comment by iglocska** [comment]
I've just pushed a tiny change, if you git pull the latest version and navigate to server settings -> diagnostics, it will tell you which php.ini it is using ;)

**Comment by Piosec** [comment]
I have pulled the lasted version but into diagnostics the path isn't given: 
![path](https://user-images.githubusercontent.com/26251854/27625699-c564eae8-5be5-11e7-9f70-8c62f0e23ad4.png)

I changed directives about "/etc/php/7.0/apache2/php.ini" file and values are set at 500Mb(For testing). But, when I download a large file I get a blank page, I think this is about the timeout. 
A small file  gave this error : 
![error_smal](https://user-images.githubusercontent.com/26251854/27625888-627ee87e-5be6-11e7-9739-173bcc97aa10.png)

**Comment by iglocska** [comment]
Could you share one of the failing events?

**Comment by JulienVilsalmon** [comment]
This is the json export of this failing event :
![failing_event](https://user-images.githubusercontent.com/26251854/27627725-1f85d580-5bed-11e7-8aec-fc554887fede.png)

**Comment by adulau** [comment]
We don't expect to run OCR on the image ;-) Could you paste the JSON directly? Thank you.

Even if the event is empty (without attributes), the import from the UI should work. I did some tests and it works for me on recent MISP version.

**Comment by Piosec** [comment]
{"response":[{
    "Event": {
        "id": "1",
        "orgc_id": "1",
        "org_id": "1",
        "date": "2017-06-27",
        "threat_level_id": "3",
        "info": "Test",
        "published": false,
        "uuid": "59528811-ab5c-473d-b0ce-632eac1a050e",
        "attribute_count": "0",
        "analysis": "0",
        "timestamp": "1498581009",
        "distribution": "1",
        "proposal_email_lock": false,
        "locked": false,
        "publish_timestamp": "0",
        "sharing_group_id": "0",
        "disable_correlation": false,
        "event_creator_email": "z@x.com",
        "Org": {
            "id": "1",X",
            "uuid": "594bc39a-4cbc-46f7-a632-0a3dc0a83832"
        },
        "Orgc": {
            "id": "1",
            "name": "X",
            "uuid": "594bc39a-4cbc-46f7-a632-0a3dc0a83832"
        },
        "Attribute": [],
        "ShadowAttribute": [],
        "RelatedEvent": [],
        "Galaxy": []
    }
}]}

Do you configure import plugin ? 
Do you add the submodule 'misp-modules' ?

I've tried both, maybe my configuration isn't correct..

**Comment by Piosec** [comment]
I have installed the 'misp-modules' and allow import into "plugin settings" : 
![import](https://user-images.githubusercontent.com/26251854/27639901-0195b772-5c18-11e7-945f-e5bbe2dbf23b.png)

I configured plugin settings like that : 

![plugin_settings](https://user-images.githubusercontent.com/26251854/27641596-9bddbe98-5c1c-11e7-84bb-cd8a9372c793.png)

MISP import didn't works with data extracted by Misp 
![import_misp](https://user-images.githubusercontent.com/26251854/27641660-cbd643fe-5c1c-11e7-9071-58a856e8f690.png)

**Comment by iglocska** [comment]
The misp import has nothing to do with the misp modules. The two are completely different systems. Could you check if you have the uuid of the event blocked by any chance?
Admistraton -> manage event blacklists -> look for the UUID there (59528811-ab5c-473d-b0ce-632eac1a050e)

**Comment by Piosec** [comment]
Thank you, my events are in the blacklist. 
So I disable "MISP.enableEventBlacklisting" : "false"
Now the import works. 
It is possible to keep "MISP.enableEventBlacklisting" to "true" and import events ? 
Is it possible to change event UUID ? 
For exemple, if I import a MISP export with an UUID = 3 and I already have an UUID =3, it will not works. 
I would like to increase ID number automatically, it is possible ?

**Comment by iglocska** [comment]
No, please don't change the uuid (this is tampering with the integrity of the data). You can remove entries from the blacklist by clicking the little trash icon in the list. Blacklisting happens if you manually delete an event on your instance, to avoid it being pushed back to you if you chose to delete it.

**Comment by Piosec** [comment]
My import works for small file(less than 50Mo), but when I try to import large file like (300Mo) I get a blank page. 
I changed the two directives whose we have discussed at the beginning and I restarted apache but it didn't works either. 
How can I import large file ? (API , misp-modules --> Import ) ?

**Comment by iglocska** [comment]
after a git pull, could you go to the administration->server settings->diagnostics page and have a look at the php_ini diagnostic? I have a feeling you didn't change the directives in the php.ini actually used by your php.

**Comment by Piosec** [comment]
I got this path : 
![path_php](https://user-images.githubusercontent.com/26251854/27681250-e94fc66a-5cbe-11e7-8d78-12fa88898466.png)

I've made modifications into this file that didn't works.

After restarting apache, it works.

**Comment by Piosec** [comment]
Thank you for your help ! :)
