### ISSUE TITLE
Enabling Feeds - Noob Query

### ISSUE THREAD

**Issue by droik123** [MISP/MISP#2301]
Tottaly New to MISP. 

Got it installed successfully and have enabled 2 feeds on MISP 

TOR Exit Nodes 
Binary Defense Systems 

However I am unsure if I am doing it right.   Also where can I view the data that the feed is collecting (if it is collecting data)

Would really appreciate some guidance.   

Is there any comprehensive guide that can help me. 

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  Question,  
OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 16.04
| PHP version               | 7.1
| MISP version / git hash   | 2.4.
| Browser                   | Chrome

**Comment by adulau** [comment]
When caching or collecting the feeds, you can see the job evolving with the number of elements cached or imported.
