### ISSUE TITLE
API to extract filtering by tags 

### ISSUE THREAD

**Issue by reswob10** [MISP/MISP#2304]
I have a usage/syntax question and if there is a user forum or email list that is more appropriate, please point me in that direction.  A quick google search did not turn up anything along those lines.

For completeness, my question is this:  I inherited access to a MISP installation that uses tags with colons, dashes, quotation marks, and equal signs.  fictional example:  malware:blue-ivy="SMB1"

This format seems to break the API. 
Using the following call:
curl -H "Authorization:  xxxxxxxxx" 'hxxps://misp/events/csv/false/false/malware:blue-ivy="SMB1"/Network%20activity/false' 

Returns nothing but the header row.
However, if I use a tag that has none of the above characters:

curl -H "Authorization:  xxxxxxxxx" 'hxxps://misp/events/csv/false/false/OSINT/Network%20activity/false'

that works and I get results.
Do any or all of those special characters break the API request?
If so, does this mean we need to recreate all of our tags to use the API?  Or is there a way to use wildcards in the curl statement?

curl -H "Authorization:  xxxxxxxxx" 'hxxps://misp/events/csv/false/false/malware*/Network%20activity/false'

Again, if there is a better place to ask these questions, please let me know.

Thanks.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | CentOS 6.9
| OS version (client)       | CentOS 6.5
| PHP version               | ?
| MISP version / git hash   | 2.4.69
| Browser                   | N/A

### Expected behavior
Using the API make a request to download a csv with a certain tag.
curl -H "Authorization:  xxxxxxxxx" 'hxxps://misp/events/csv/false/false/malware:blue-ivy="SMB1"/Network%20activity/false' 

should return a list of indicators with that tag.

### Actual behavior

Returns only the header row.

### Steps to reproduce the behavior

Create tags with colons, dashes, equal signs, and quotation marks.  Perform curl using API.

**Comment by BenjaminJoly** [comment]
Hi !

I've probably missed the action, but I can give you an answer to your problem. Hoping this will help you, or help people who try to google it at least. 

So, you do not have to redo everything, and you can call the API in three different manner to get the result that, I guess, you want. 

Firstly, the proper manner to do it, on a POST request.  

On your example, this will be : 
```bash
curl -H "Authorization: xxxxxxx" -H "Content-type: application/json" -X POST -d '{"tags":["malware;blue-ivy=\"SMB1\""],"category":"Network Activity"}' hxxps://misp/events/csv/download
``` 

As you can see, the colons `:` should be replaced by the semicolons `;`. The side effect of that point is that you can't call a tag with semicolons inside his name. In the same way, you can't call tag with `&&`.
Also, you should be warned that except if you add `"ignore":true` in your request (the second parameter), you will only have attachments that are flagged "to_ids". 

The POST method is the one which is recommended. But if you really want to have it through a GET method, you will have two different options to deal with those special characters. 

```bash
curl -H "Authorization: xxxxxxx" 'hxxps://misp/events/csv/download/false/false/malware;blue-ivy="SMB1"/Network%20activity/false'
```

Again, all colons should be replaced by semicolons.
Or with an encoded URL

```bash
curl -H "Authorization: xxxxxxx" hxxps://misp/events/csv/download/false/false/malware%3Bblue-ivy%3D%22SMB1%22/Network%20activity/false
```

If you want more details, I can invite you to read [MISP book](https://github.com/MISP/misp-book). You can find more details on the [CSV Export](https://github.com/MISP/misp-book/tree/master/automation#csv-export)

Hope I could help you a bit !
