### ISSUE TITLE
Documentation (master) lists non-existent API's

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/MISP#2309]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Hi,

Ive been trying to get my python script to add a tag to an event but its not working, turns out that the documentation for 2.4.50 https://media.readthedocs.org/pdf/pymisp/master/pymisp.pdf lists a number of API;s which are missing

misp.tag
misp.untag

Ive had a look at api.py for version 2.4.50 , 56  and these calls do not exist. :(

Perhaps an edit of the documentation ? or change the  version number on the doco ?

Anyhow since Im using 2.4.56 what command do i use to add a custom tag to an event ? 

currently im using using

misp.add_tag(event, 130) which is fine, but i would like to specify an actual name not a number, is this possible ? 

eg 
misp.add_tag(event, 'MyTag')

Cheers

**Comment by SparkyNZL** [comment]
Ill move this to pymisp :)  sorry :)

**Comment by adulau** [comment]
Looks like the version number of the documentation is incorrect. I just fixed and it will be updated in the next release. https://github.com/MISP/PyMISP/commit/10d5d629f4f67a187fbaec00e9c0d31b0b83b8a4

Add tag API works with the name too. If the tag doesn't exist, it will be created.

Thank you very much for the feedback.

**Comment by SparkyNZL** [comment]
cheers thanks for that.

im using

add_tag(event, 'mytag')

but it never actually add "mytag" to the event, if i use add_tag(event,
130)

this will add the tag associated with tag item 130 to the event. I just
cant see what im doing wrong :(

Any hits would be gracious

Thanks
