### ISSUE TITLE
Apache service start

### ISSUE THREAD

**Issue by Mudamara** [MISP/MISP#2319]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Hi, 

I am having an issue getting the apache server running. I am a complete noob to this and am following word for word the installation instructions for Ubuntu 1604. 

I believe I know what the issue is, but done know how to rectify it: that the misp-chain.crt file is missing from the /etc/ssl/private folder. 

1. Does this sound right? 
2. How do I create the file. 

I have looked on similar issues on here and nothing resolves the issue. 

Many thanks for your help

**Comment by tomking2** [comment]
Hi Mudamara,

So, when you create a self-signed certificate, you actually shouldn't need the misp-chain.crt file present, as there is no chain.
Depending on your Apache install, edit the misp-ssl.conf file, probably located in:
```/etc/apache2/sites-available/```

Replacing the line 
```SSLCertificateChainFile /etc/ssl/private/misp-chain.crt```
with 
```#        SSLCertificateChainFile /etc/ssl/private/misp-chain.crt```
This will comment out using a chain file, which you don't need.
Then, do:
```sudo service apache2 restart```

**Comment by Mudamara** [comment]
I totally forgot about this issue as I believe I was celebrating actually getting this working. I can't remember what did it in the end. But thanks for taking the time.
