### ISSUE TITLE
CakeObject not found

### ISSUE THREAD

**Issue by dewiestr** [MISP/MISP#2320]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Since my upgrade from 2.4.61, I am no longer able to sync any of my configured external MISP DBs. Any ideas where I can look for next ? 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| PHP version               | 7.0.18
| MISP version / git hash   | 2.4.76, commit b544bd6f2021e9c8f66b8efd5b52e6b4ca996725
| Browser                   | n/a 

### Expected behavior

No errors

### Actual behavior

==> app/tmp/logs/resque-worker-error.log <==
PHP Fatal error:  Class 'CakeObject' not found in /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php on line 31
Fatal Error Error: Class 'CakeObject' not found in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 31]

### Steps to reproduce the behavior

Sync actions > List servers >Click any sync servers

**Comment by dewiestr** [comment]
This seems to be similar to https://github.com/MISP/MISP/issues/2094 .

**Comment by dewiestr** [comment]
@iglocska this issue can be closed. rebooting the workers solved it.

**Comment by iglocska** [comment]
Perfect, thanks for the heads-up!
