### ISSUE TITLE
Sync sightings between MISP instances

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2323]
It makes sense to be able to enable this per sync server and per push/pull direction.

**Comment by iglocska** [comment]
Agreed. We've just discussed this on Tuesday this week, it will definitely happen soonish ;)

**Comment by adulau** [comment]
Yeah!

**Comment by cgi1** [comment]
Is there some update on this? It would be very useful supporting the main idea of sharing!

**Comment by iglocska** [comment]
Kind of. Sightings are synced when you publish an event, but not out of bound yet, we need a new separate sync process / have some smarter triggers to sync sightings for already published events.

**Comment by cgi1** [comment]
So the sigthings are getting synced if I unpublish, sight an attribute and then re-publish the event?

**Comment by iglocska** [comment]
Yep, they should get pushed then!

**Comment by zeroq** [comment]
I checked that and the sighting information are in the JSON that is pushed to attached servers, however it is not processed and added to the events. I started to work on this problem and created a separate branch for that: https://github.com/zeroq/MISP/tree/sync_sightings_on_publish

**Comment by infosec-intern** [comment]
Can a setting be added to toggle the out-of-bound sighting sync? We prefer the current method of only syncing on publish

**Comment by zeroq** [comment]
currently it is as you like it, data is only synced on publish.

**Comment by cgi1** [comment]
Solved after approved pull request imo
