### ISSUE TITLE
Workers Script Permission Issues

### ISSUE THREAD

**Issue by mikeesparza** [MISP/MISP#2326]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support...
| OS version (server)       | CentOS ...
| OS version (client)       | 7 ...
| PHP version               | 5.6.25...
| MISP version / git hash   |  v2.4.76 (1d4bc510bd3e065d0eb1cc6532b083357d136bc4)
| Browser                   | Chrome

### Expected behavior
su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'

Should start workers after it is made executable

### Actual behavior
/var/tmp/sclCswlBn: line 8: /var/www/MISP/app/Console/worker/start.sh: Permission denied

### Steps to reproduce the behavior
Clean OS Install of CentOS7 with SELinux enforcing & AD Authentication (I have a feeling this may be the issue). 

Everything has been completed as described in the XInstall.centos7.txt up to Line 273. 

### Logs, screenshots, configuration dump, ...
ls -la /var/www/MISP/app/Console/worker/start.sh
-rwxr-x--x. 1 root apache  559 Jul  6 09:04 start.sh

**Comment by RichieB2B** [comment]
Have you mounted /var/www with the "noexec" flag? A solution could be to use bash -c:
su -s /bin/bash apache -c 'scl enable rh-php56 bash -c /var/www/MISP/app/Console/worker/start.sh'

**Comment by mikeesparza** [comment]
That was my exact problem, @RichieB2B 

Figured it out this morning while I was troubleshooting another custom script issue on a different server.

**Comment by enkidunolinux** [comment]
Hi, I have the same issue. i tired both but no luck, any idea?
_### [root@xxxxx ~]# su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'
/var/tmp/sclaPcqKl: line 8: /var/www/MISP/app/Console/worker/start.sh: Permission denied_
!
_[root@XXXX ~]# su -s /bin/bash apache -c 'scl enable rh-php56 bash -c /var/www/MISP/app/Console/worker/start.sh'
Unable to open /etc/scl/conf/bash!_


also i'm unable to login from the webpage (not sure if it for the same reason), I'm getting this error

You have tripped the cross-site request forgery protection of MISP
