### ISSUE TITLE
POSTGRESQL-structure.sql out of date

### ISSUE THREAD

**Issue by kralca** [MISP/MISP#2328]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | N/A
| PHP version               | 7.0
| MISP version / git hash   | 2.4.76, 1d4bc510bd3e065d0eb1cc6532b083357d136bc4
| Browser                   | N/A

### Expected behavior

Should work with Postgres.

### Actual behavior

Error suggests Postgres table creation script is out of sync with MariaDB/MySQL (missing column sightings.uuid).

### Steps to reproduce the behavior

Initialise postgres tables using POSTGRESQL-structure.sql and try to log in.

### Logs, screenshots, configuration dump, ...

Extracted from /var/www/MISP/app/tmp/logs/error.log:

```
2017-07-08 10:19:57 Error: [PDOException] SQLSTATE[42703]: Undefined column: 7 ERROR:  column "uuid" does not exist
LINE 1: ..." FROM "public"."sightings" AS "Sighting"   WHERE "uuid" = '...
                                                             ^
HINT:  Perhaps you meant to reference the column "Sighting.id".
Request URL: /users/login
```

**Comment by adulau** [comment]
Indeed we don't actively maintain the Postgres one and we recommend to rely on MariaDB. But if you could update it according to the latest version of the MySQL/MariaDB scheme and make a pull-request. It would be wonderful!
