### ISSUE TITLE
python-importlib for RHEL7 and Centos 7

### ISSUE THREAD

**Issue by smiggs** [MISP/MISP#2331]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  Missing RPM
| OS version (server)       |  RHEL7
| OS version (client)       |  Windows 7
| MISP version / git hash   | 2.4.76

### Expected behavior

python-importlib installs from a yum command as per https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt  

### Actual behavior

Unable to to find this package in the Centos or Red Hat software collections, googling around it only seems to exist for RHEL6

We're just going to plow on for now, but for reference what is the function of this package?

**Comment by jakubrybar89** [comment]
+1 < I am currently facing the same issue on CentOS 7 and I am looking for the same answer as I cannot now analyze whole source code from the scratch :)

**Comment by iglocska** [comment]
It's a dependency for the STIX python library according to Mitre, so depends on how important that is to you guys. 

Could you try 
```
pip install importlib
```
?

**Comment by jakubrybar89** [comment]
Thank you for a quick resolution of my issue and for explanation of STIX Python library dependency!

I was obviously too tired that I haven't used pip - don't see it for the first time. :)

I have just introduced myself to STIX by reading through the webpage **(https://stixproject.github.io/)** and it seems as function I have to implement into my project, so thanks for that friendly kick! 

Log:

```
# pip install importlib
Collecting importlib
  Downloading importlib-1.0.4.zip
Installing collected packages: importlib
  Running setup.py install for importlib ... done
Successfully installed importlib-1.0.4
```

**Comment by smiggs** [comment]
That sorted it, I can see why Red Hat dropped the linux package for it if there is a pypi package.

**Comment by ViolatorDM** [comment]
Might be having more or less the same issue (https://github.com/MISP/MISP/issues/6702), but on my System, I'm unable to install the importlib library for some reason. Can someone please help?
