### ISSUE TITLE
Logo cannot be uploaded to org with space in its name

### ISSUE THREAD

**Issue by DominoTree** [MISP/MISP#2333]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior
Upload a logo to an organization with spaces in its name, and expect it to function.

### Actual behavior
No logo is stored, and no error is thrown.

### Steps to reproduce the behavior
Create an org with spaces in its name and upload a logo.

### Logs, screenshots, configuration dump, ...
Around OrganisationsController.php#L102, no action is taken if the org name has spaces (or certain other characters), nor is any error thrown.

**Comment by DominoTree** [comment]
I might make a quick PR to make the "space" case work, but others will require more changes

**Comment by BenjaminJoly** [comment]
Do this issue is still relevant ? 
I've just tried some special chars (most that I can have on my keyboard), and I've got no problems with that.
