### ISSUE TITLE
rh-php56-php-cli @ CentOS 7: php-cli is not working properly + Workers are not restarting with no entries in the logs

### ISSUE THREAD

**Issue by jakubrybar89** [MISP/MISP#2334]
Hi,

I am trying to fix all issues addressed by 'Server Settings' - 'Diagnostics' on CentOS 7, when followed the install guide for the OS (https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt). I do have some valuable remarks regarding the procedure of deployment on CentOS 7 incl. ongoing process of upgrading PHP from 5.6.x to PHP 7.

Right now I am still trying fix php-cli related issue described below as it's not properly working in my environment.

Any help would be highly appreciated!

Howgh,

Jakub

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | CentOS 7 (Linux 3.10.0-514.26.2.el7.x86_64 x86_64)
| OS version (client)       | -
| PHP version               | 5.6.25 (cli) (built: Oct 21 2016 18:00:07)
| MISP version / git hash   | v2.4.76 (1d4bc510bd3e065d0eb1cc6532b083357d136bc4) 
| Browser                   | -

### Expected behavior

{MISP}/servers/serverSettings/diagnostics >

PHP CLI Version (>7.0.16 recommended): 5.6.25 (Update highly recommended)

PHP Extensions

Cli
OK

--

Workers restarted, action logged to /var/www/MISP/app/tmp/logs/resque...

### Actual behavior

{MISP}/servers/serverSettings/diagnostics >

PHP CLI Version (>7.0.16 recommended): Unknown (Issues determining version)

PHP Extensions

Cli
Issues reading PHP settings. This could be due to the test script not being readable. 

--

Workers doesn't restart, but they do start when OS boots up.

### Steps to reproduce the behavior

{MISP}/servers/serverSettings/diagnostics

### Logs, screenshots, configuration dump, ...

**/var/log/audit/audit.log (for restarting the workers)**

type=AVC msg=audit(1499707320.972:169): avc:  denied  { open } for  pid=4109 comm="python" path="/usr/lib/python2.7/site-packages/weakrefmethod-1.0.3-py2.7.egg" dev="dm-1" ino=9082048 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file
type=SYSCALL msg=audit(1499707320.972:169): arch=c000003e syscall=2 success=no exit=-13 a0=7ffca96907a0 a1=0 a2=1b6 a3=24 items=0 ppid=2208 pid=4109 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="python" exe="/usr/bin/python2.7" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1499707320.972:170): avc:  denied  { open } for  pid=4109 comm="python" path="/usr/lib/python2.7/site-packages/ordered_set-2.0.2-py2.7.egg" dev="dm-1" ino=9082051 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file
type=SYSCALL msg=audit(1499707320.972:170): arch=c000003e syscall=2 success=no exit=-13 a0=7ffca96907a0 a1=0 a2=1b6 a3=24 items=0 ppid=2208 pid=4109 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="python" exe="/usr/bin/python2.7" subj=system_u:system_r:httpd_t:s0 key=(null)

**/var/www/MISP/app/tmp/logs/error.log (for Server Settings' - 'Diagnostics')**

2017-07-10 19:23:08 Warning: Warning (2): fread(): SSL: Connection reset by peer in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 415]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fread - [internal], line ??
CakeSocket::read() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 415
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 381
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 466
ServersController::__checkVersion() - APP/Controller/ServersController.php, line 907
ServersController::serverSettings() - APP/Controller/ServersController.php, line 764
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by saeeda12** [comment]
Was anyone able to resolve this issue? Currently experiencing the same issue with PHP CLI, however my PHP version is up to date and showing as 7.1.8

**Comment by SteveClement** [comment]
fixed in latest documentation
