### ISSUE TITLE
IP-DST|Port attribute gets correlated by port

### ISSUE THREAD

**Issue by MichaelDwucet** [MISP/MISP#2336]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug

We have 2 events with the followings attributes:
Event1:  
122.49.215.108|80
	
Event2:
182.255.5.201|80 

| MISP version / git hash   | 2.4.74

### Expected behavior
The attributes should not get correlated just by sharing port 80.

### Actual behavior
The attributes  get correlated.

### Logs, screenshots, configuration dump, ...
![misp-error_correlation_event1a](https://user-images.githubusercontent.com/17084146/28066332-d4b03f78-663c-11e7-84a4-234ba295e3d4.jpg)
![misp-error_correlation_event1b](https://user-images.githubusercontent.com/17084146/28066335-d4b6d068-663c-11e7-8b50-23e28dd891c9.jpg)
![misp-error_correlation_event2a](https://user-images.githubusercontent.com/17084146/28066333-d4b29778-663c-11e7-8d4f-247c5e036324.jpg)
![misp-error_correlation_event2b](https://user-images.githubusercontent.com/17084146/28066334-d4b337e6-663c-11e7-9acd-0e3032067428.jpg)

**Comment by StefanKelm** [comment]
Seems like this is related to https://github.com/MISP/MISP/issues/2141

**Comment by MichaelDwucet** [comment]
Thanks for the info. I searched only the open issues. Seems it is fixed in the newest version. We will update our MISP
