### ISSUE TITLE
Add cookie data type

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#2347]
Is _cookie_ a supported attribute type today? Wanted to suggest ability to track HTTP cookie names explicitly could be very useful (for tracking malicious traffic distribution, etc.). Would use `text` or `pattern-in-traffic` today but don't feel that either is quite right.

**Comment by adulau** [comment]
Good idea. We will add it.

**Comment by truckydev** [comment]
Hi team,

It would be better to have the distinction between "cookie-value" and "cookie-name".

I can make the PR.

**Comment by dspruell** [comment]
Can this (if not already) also be added to Payload Delivery? Cookies play
significantly in a lot of traffic distribution as well.
