### ISSUE TITLE
Add support for OAuth to authenticate users

### ISSUE THREAD

**Issue by tweemeterjop** [MISP/MISP#2348]
I would be nice if MISP added support for OAuth 2.0 as an authentication mechanism to authenticate users. It should be an additional option so you can let users authenticate with a local account or by using OAuth.

Only users from our own organisation can be authenticated using OAuth. External users should authenticate using their local misp account.

**Comment by adulau** [comment]
Indeed, there is no direct OAuth authentication in MISP.

There are some MISP users using the CustomAuth plug-in https://<yourmisp>/servers/serverSettings/Plugin
where you can pass authentication header back to MISP. So you can integrate OAuth and MISP via a reverse-proxy and use CustomAuth. 

https://www.circl.lu/doc/misp/appendices/#appendix-a-external-authentication

I hope this helps.

**Comment by tweemeterjop** [comment]
Thanks Alexandre, i will look into this. Although, I would still prefer a direct integration in MISP.

**Comment by adulau** [comment]
Sure. I'll keep the issue open to see if we have more request regarding a direct OAuth integration.

**Comment by RichieB2B** [comment]
+1 for OAuth support in MISP.

**Comment by czechnology** [comment]
+1 for OAuth.
Only found this 2 years old ticket here, has there possibly been some progress?

**Comment by garritschroeder0001** [comment]
+1 for OAuth.

**Comment by nyx0** [comment]
+1

**Comment by adulau** [comment]
Thanks to @JakubOnderka it has been merged in develop branch and it will be released tonight 

https://github.com/MISP/MISP/blob/af4e248690b05e0d319c87ef46ae6313d76933a1/app/Plugin/OidcAuth/README.md

**Comment by adulau** [comment]
Implemented in MISP.
