### ISSUE TITLE
Update MISP behind SSL Intercept

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#2353]
Hoping someone on here can help me, trying to add our corporate root cert to MISP server so I can update, we are behind a corporate ssl intercept. 

I added the cert 
$ sudo cp corp.crt /usr/share/ca-certificates/corp.crt
644 permissions for the file
$ sudo dpkg-reconfigure ca-certificates
This doesn't show my certificate under it, just the ones under the mozilla folder.
$ sudo update-ca-certificates
This doesn't show any as updated

And then trying to update - 
root@misp:/var/www/MISP# !142
git pull origin 2.4
fatal: unable to access 'https://github.com/MISP/MISP.git/': server certificate                                     verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

I don't want to disable SSL verification, and I know the certificate is good... is there anything else I can try?

Thanks!

root@misp:/var/www/MISP# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

**Comment by kallix** [comment]
Have you tried putting your .crt in `/usr/local/share/ca-certificates/` and then calling `update-ca-certificates` ?

If I recall correctly, certs added in `/usr/share/ca-certificates/` are only used if declared in `/etc/ca-certificates.conf`(and will cause issues when the ca-certificate package is updated)

**Comment by mathurin68** [comment]
Ugh note to self, crt, cer, and pem are not the same.  I thought I had them named crt in both.

**Comment by mathurin68** [comment]
I take that back (slightly)  if I update MISP from the command line call git etc., seems to work fine.  But under Server Settings, Diagnostics can't seem to 'pull from git'  to alert me if there is a new version or not.  Not a big deal and still totally functional, just curious.

**Comment by mathurin68** [comment]
Still nothing, is there anyplace else I can put our company SSL cert?  

![image](https://user-images.githubusercontent.com/5932961/31615181-c566082a-b256-11e7-96cb-0b5f2d02868c.png)

**Comment by mirktmirkt** [comment]
Hello,

Adding cert to /app/Lib/cakephp/lib/Cake/Config/cacert.pem helps..

Found the answer here:
https://github.com/MISP/MISP/issues/3299

Regards,
mirkt
