### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by mtaufikak** [MISP/MISP#2354]
Team,

I've successfully installed the MISP but when I go to the menu (Administration -> Server Settings) I found a report like this. 
![error 2](https://user-images.githubusercontent.com/29562499/28540320-297b2be2-70df-11e7-816a-c332a64a34c8.JPG)
then I checked in menu **/var/www/MISP/app/tmp/logs** and this is what I found
![error 1](https://user-images.githubusercontent.com/29562499/28540322-2caa6af8-70df-11e7-8f7b-220c3b336d02.JPG)

What should I do ?

Appreciate all the assistance.

Regards

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu Server 16.04
| OS version (client)       | Windows 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.77
| Browser                   | Google Chrome

**Comment by adulau** [comment]
If the issue is not resolved, feel free to reopen this issue. I suppose it was an issue with the installation and the baseurl.
