### ISSUE TITLE
add missing x509 type

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2356]
Some X509 type missing : 

- x509-fingerprint-MD5
- x509-fingerprint-SHA256
- x509-issuer

Here a sample (cf - wikipedia ^^) : 

> Issuer: C=BE, O=GlobalSign nv-sa, CN=GlobalSign Organization Validation CA - SHA256 - G2

**Comment by StefanKelm** [comment]
Recommend to also add things like:

- x509-subject
- x509-validity
- x509-not-before
- x509-not-after

**Comment by truckydev** [comment]
https://github.com/MISP/MISP/pull/2357 ^^

**Comment by StefanKelm** [comment]
Cool, thank you.

**Comment by adulau** [comment]
As you know MISP 2.4.80 now includes objects and the x509 one. https://github.com/MISP/misp-objects/blob/master/objects/x509/definition.json I'll close the issue. If you think, it's not resolved. Feel free to reopen.
