### ISSUE TITLE
Possible Bug: REST Search API

### ISSUE THREAD

**Issue by melegar** [MISP/MISP#2365]
When performing a search using the MISP API misp.search(controller='attributes',value='XXX') I continually receive 500 errors from my server.  Looking at my server stats while its running, memory utilization reaches over 10GB before settling and then I receive an error sending a packet to MariaDB:  

```
2017-07-31 18:49:55 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /attributes/restSearch/download
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1522): DboSource->fetchAll('SELECT `Attribu...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1356): DboSource->_fetchHasMany(Object(Attribute), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1215): DboSource->queryAssociation(Object(Attribute), Object(AttributeTag), 'hasMany', 'AttributeTag', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource-read(Object(Attribute), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model-_readDataSource('all', Array)
#8 /var/www/MISP/app/Model/Attribute.php(2276): Model->find('all', Array)
#9 /var/www/MISP/app/Controller/AttributesController.php(1773): Attribute-fetchAttributes(Array, Array)
#10 [internal function]: AttributesController->restSearch('download')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod-invokeArgs(Object(AttributesController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller-invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher-_invoke(Object(AttributesController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
 2017-07-31 18:49:55 Warning: Warning (2): Error while sending QUERY packet. PID=26347 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 436
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 673
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1184
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
User::getAuthUserByUuid() - APP/Model/User.php, line 597
```
I would try raising the max_allowed_packet size but I believe I have maxed it out at 1GB.  I don't understand how the variable being passed to mysql could be so large, this should be a relatively simple query, I could replicate it with a single Select statement.  To amplify that point, when I try to perform the same query through the web interface on the search attributes page, the search works just fine and returns results.  Also, I have tried running this search with multiple values and had the same result.  Also, I believe I was able to run this same search prior to the latest update... I have changed a number of things since patching so it may be unrelated, but I thought I would add that as well.  

In case it matters, I'm running MISP on RHEL7, using PHP5.6 and MariaDB10 from the software collections as well as MISP 2.4.77.  If you need any additional information to replicate, let me know. It should just be a matter of running the PyMISP.search() command out of PyMISP on attributes.

**Comment by SHSauler** [comment]
I think the parameter you are looking for is `values` not `value`. Please refer to [this](https://github.com/MISP/PyMISP/blob/394c312d0d5acf1295ab921602c42647c4ad76ff/pymisp/api.py#L915). Try to update your PyMISP as well, since @Rafiot implemented [an alert when using an illegal parameter](https://github.com/MISP/PyMISP/blob/394c312d0d5acf1295ab921602c42647c4ad76ff/pymisp/api.py#L994).

**Comment by melegar** [comment]
You were absolutely right...  A simple typo caused quite an error :).  I will update my PyMISP as well.  Thanks for the help!!
