### ISSUE TITLE
MISP web interface

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2366]
How do I access the MISP web interface, is there a specific URL address to that i have to use?

**Comment by iglocska** [comment]
Did you do a fresh installation? It depends on what you've set up in your apache conf.

**Comment by ndhambi** [comment]
Yes it is a fresh installation, I am following the instructions on https://github.com/MISP/MISP/issues/1195 , I am on instruction 7. where it says : 

"  Now log in using the webinterface:
The default user/pass = admin@admin.test/admin"

**Comment by iglocska** [comment]
It depends on the ip address / hostname of your machine. For example, if I have a system with the IP address 1.1.1.1 and with the associated domain name mymisp then I would reach MISP via either:

http://1.1.1.1
http://mymisp
https://mymisp

depending on my apache settings.

**Comment by ndhambi** [comment]
Thanx, It takes me to the APache2 Ubuntu Default Page when i try to reach it via my IP address or hostname

**Comment by iglocska** [comment]
Did you follow the part of the instructions where you need to copy the .conf file to the apache directory and restart apache?

**Comment by ndhambi** [comment]
Yes, I did that on step 6, "A sample vhost can be found in /var/www/MISP/INSTALL/apache.misp.ubuntu

cp /var/www/MISP/INSTALL/apache.misp.ssl /etc/apache2/sites-available/misp-ssl.conf "

Then i created a self signed certificate before restarting apache.

**Comment by iglocska** [comment]
OK, then you should try to reach it via https://mymisp (or whatever your FQDN is). Alternatively https://1.1.1.1 (or whatever your IP is, though the former is recommended).

**Comment by ndhambi** [comment]
It did take me to the login page , but it says " Invalid user name or password, try again" when i log in with the default user and pass.

**Comment by iglocska** [comment]
Hmm weird. It should work. 

However, you can reset the password via the CLI

/var/www/MISP/app/Console/cake Password admin@admin.test your_new_password

**Comment by ndhambi** [comment]
Thanks, i managed to get the log in right. The web interface has a range of settings that are critical and have to be set, Is there a specific guideline on how one can set these settings?

**Comment by ndhambi** [comment]
My redis settings are all critical, I dont know what settings are required to be set for these fields. could you kindly assist on this.

**Comment by iglocska** [comment]
Critical can simply mean that you need to confirm it. It's not the most obvious way to show it but our UI designer is horrible.

Basically, MISP warns you that those settings are not set and it's using the default values shown - which may be applicable to you unless you have custom redis settings set up. So to get rid of the warnings simply edit the settings and accept the default settings.

**Comment by ndhambi** [comment]
Cool Thanks, i managed to sort out most of the issues except for the Workers tab issues, I have started the apache and then started the background workers and i keep getting this error "The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or not."
![er](https://user-images.githubusercontent.com/30654371/28914879-8560e2de-783d-11e7-9e56-274f175dc831.JPG)

**Comment by iglocska** [comment]
Ah ok, generally the workers should be started from within MISP, or externally using the apache user. To kill them via the command line first (since a different user started the processes and MISP doesn't have access to manipulate them), simply run:

```
/var/www/MISP/app/Console/cake CakeResque.CakeResque stop --all
```

After that just open your worker tab in misp and click restart all.

**Comment by ndhambi** [comment]
I tried that and it now shows me the error below
" Worker not running!"
![screenshot from 2017-08-03 11-26-16](https://user-images.githubusercontent.com/30654371/28915218-b7c4cf00-783e-11e7-9a1a-d4fe691d2544.png)

**Comment by iglocska** [comment]
If you click restart all at the bottom, does it start the workers?

**Comment by ndhambi** [comment]
it still gives the same error when i click restart at the bottom

**Comment by iglocska** [comment]
Could you run the following?

```
chmod 755 /var/www/MISP/app/Console/workers/start.sh
chown www-data:www-data /var/www/MISP/app/Console/workers/start.sh
```

Try again after that, see if it works.

**Comment by ndhambi** [comment]
still gives the same error "worker not running"

**Comment by iglocska** [comment]
Hmph. How about this?

```
sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh
```

**Comment by ndhambi** [comment]
It looks like this command does start the workers but it now gives an error saying " The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or not."

**Comment by iglocska** [comment]
What the hell. Is this on Ubuntu? Are you using a non-standard apache user?

**Comment by iglocska** [comment]
```
ps aux | egrep '(apache|httpd)'
```

To see your apache user

**Comment by ndhambi** [comment]
yes its on Ubuntu 16.04 , the command you gave me above resulted in the image below, i am not sure of which one is my apache user because it gives out multple .
![apache](https://user-images.githubusercontent.com/30654371/28916731-85a2ae98-7843-11e7-91de-72e8cc86f5c0.JPG)

**Comment by ndhambi** [comment]
The blue higlighted name is the other user which gives me an error "The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or no" when i start the workers

**Comment by ndhambi** [comment]
the workers dont start at all when i start them with the user "www-data"

**Comment by iglocska** [comment]
Wait, but before it worked? You wrote this:

```
It looks like this command does start the workers but it now gives an error saying " The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or not."
```

So the workers don't start with www-data via the command line either? What's the exact output?

**Comment by ndhambi** [comment]
It only starts when i use the other  user that i highlighted in blue on my last post, but gives an error "The worker was started with a user other than the apache user. MISP cannot check whether the worker is alive or not."

This is what i get on the command line when I use the www-data user.

user2@user2:/var/www/MISP$ sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh
Stopping workers
Stopping 4530 ... kill: (4530): No such process
Stopping 4494 ... kill: (4494): No such process
Stopping 4512 ... kill: (4512): No such process
Stopping 4548 ... kill: (4548): No such process
Stopping 4476 ... kill: (4476): No such process

Creating workers
Starting worker ..................... Fail

Creating workers
Starting worker ..................... Fail

Creating workers
Starting worker ..................... Fail

Creating workers
Starting worker ..................... Fail

Creating the scheduler workers
Starting scheduler worker ..................... Fail

**Comment by iglocska** [comment]
OK, this is more interesting. Sounds like a permission issue then, probably with the log files since the workers were started with the wrong user and the log files cannot be accessed by the correctly starting workers anymore - so they fail. To remedy it run this:

```
find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP
chown -R www-data:www-data /var/www/MISP
```

**Comment by ndhambi** [comment]
Thanks it did work now :), all the workers have started properly now

**Comment by iglocska** [comment]
Excellent B-) Let us know if you run into any other issues, will close this one for now!

**Comment by ndhambi** [comment]
i have got to the part where i have to check the diagnostics, i have 5 critical warning there.I am getting an error saying "STIX and Cybox libraries....STIX or CyBox or mixbox library not installed correctly"
