### ISSUE TITLE
GnuPG 

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2367]
I have successfully started all workers then after i get an error on the diagnostics, The error that i get says " GnuPG installation and settings....FAIL: Issues with the key/passphrase"

**Comment by CheYenBzh** [comment]
What's your error? cause the title and your message are two different errors.

First for STIX or CyBox or mixbox -> have you install python-stix,python-cybox and mixbox in /var/www/MISP/app/files/scripts?
Morevoer you've to got the right versions : 
STIX: 1.1.1.4
CyBox: 2.1.0.12
mixbox: 1.0.2

to check it, in each directory -> sudo -u www-data git checkout /*versions*/ -> sudo python setup.py install

Secondly for the gpg error, have you configure correctly the password in the server settings? (servers Settings -> Encryption settings)

**Comment by ndhambi** [comment]
Sorry i made an error on the title, im getting an error on GnuPG.

I have successfully started all workers then after i get an error on the diagnostics, The error that i get says " GnuPG installation and settings....FAIL: Issues with the key/passphrase"

**Comment by FloatingGhost** [comment]
I'm just going to quote the exact answer you literally just got

"Secondly for the gpg error, have you configured the password correctly in the server settings? (servers Settings -> Encryption settings)"

**Comment by ndhambi** [comment]
This is the error that i get when i generate the GPG encryption key through command line.

"Change (N)ame, (E)mail, or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: agent_genkey failed: Permission denied
Key generation failed: Permission denied"

**Comment by FloatingGhost** [comment]
That means you're not running the command under sudo.

Because both of your questions would have been answered by the install document, I'm going to close this issue and tell you to go and follow that.

**Comment by RichieB2B** [comment]
I think all these issues come from using a random install.txt doc from a github issue instead of the current https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

**Comment by ndhambi** [comment]
i have followed the MISP install instrutions and yes i did use Sudo and still get the error, below is a copy of my terminal.


mapetla@mapetla:/var/www/MISP$ sudo -u www-data mkdir /var/www/MISP/.gnupg
mkdir: cannot create directory ‘/var/www/MISP/.gnupg’: File exists
mapetla@mapetla:/var/www/MISP$ sudo chmod 700 /var/www/MISP/.gnupg
mapetla@mapetla:/var/www/MISP$ sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --gen-key
gpg (GnuPG) 2.1.15; Copyright (C) 2016 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Note: Use "gpg --full-gen-key" for a full featured key generation dialog.

GnuPG needs to construct a user ID to identify your key.

Real name: mapetla
Email address: mapetla.users@gmail.com
You selected this USER-ID:
    "mapetla <mapetla.users@gmail.com>"

Change (N)ame, (E)mail, or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: agent_genkey failed: Permission denied
Key generation failed: Permission denied
