### ISSUE TITLE
Could not add an event through http post call - get 405 error

### ISSUE THREAD

**Issue by ravneetSodhi29** [MISP/MISP#2369]
I am trying to add an event by http post call to <misp-url>/events - I get 405 Method not allowed error
Object I try to post 
{
            "Event":
            {
                "date": "2015-04-10", "threat_level_id": 1,
                "info": "test event",
                "analysis": 0,
                "distribution": 0,
                "orgc": "Iglocska"
            }
        }

Headers:
Authorization: auth key
Accept: application/json
Content-Type: application/json

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Woah, that's a very outdated format. orgc doesn't exist any longer, simply remove that and it should work (it will automatically use your organisation as the creator org).

**Comment by ravneetSodhi29** [comment]
I tried sending the data without orgc but it still does not works 
{name: "No valid event data received.", message: "No valid event data received.", url: "/events"}
message
:
"No valid event data received."
name
:
"No valid event data received."
url
:
"/events"

But the same thing works with Postman(with and without orgc).
Can you please give me the parameters used to add an event

**Comment by ravneetSodhi29** [comment]
I am trying to post below mentioned event object, still it gives 405 error

 {
            "Event":
            {
                "date": "2015-04-10",
                "threat_level_id": 1,
                "info": "test event - Trial",
                "analysis": 0,
                "distribution": 0
            }
        }

**Comment by iglocska** [comment]
Hmm, just tried that and it works fine for me. If you log into the interface with the account that you've used to POST the request (make sure you check the auth key that it matches!) - could you click on the role of your user (global actions -> my profile -> click the role name) and append .json at the end of the url? This should create a JSON with your permissions, just paste that here.
