### ISSUE TITLE
app/Config/config.php is not writeable

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/MISP#2371]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.77 (hash of the commit: ab7aadb924e0977836ee89d06ca2ac40a49616b2)
| Browser                   | N/A

### Actual behavior
I just updated from 2.4.72 to 2.4.77.
In "Administration / Server Settings", I reach a red header that mentioned:
"**Warning: app/Config/config.php is not writeable. This means that any setting changes made here will NOT be saved**"

As requested in the installation documentation, current file and directories permissions are the following:
`drwxr-x---. 15 root apache  4096  3 août  18:16 app`
`drwxr-x---.   2 root   apache     223  4 août  09:11 Config`
`-rw-r-----. 1 apache apache  4360  3 août  18:02 config.php`

To fix the issue, I tried to change them temporary, but it didn't work:
`chmod 770 /var/www/MISP/app`
`chmod 770 /var/www/MISP/app/Config`
`chmod 777 /var/www/MISP/app/Config/config.php`

So, I rollback permission to initial rights:
`chmod 750 /var/www/MISP/app`
`chmod 750 /var/www/MISP/app/Config`
`chmod 640 /var/www/MISP/app/Config/config.php`

Any idea about what can be wrong?
Thanks in advance,
Kind regards,
Julien

**Comment by iglocska** [comment]
SELinux being SELinux, could you try:

```
chcon -t httpd_sys_rw_content_t /var/www/MISP/app/Config/config.php
```

?

**Comment by Tux-Panik** [comment]
It works... congratulations!
Thanks.

**Comment by PurePackets** [comment]
I have same problem !? what did you did to resolve problem ? (CENTOS7) thanks

**Comment by iglocska** [comment]
```
chcon -t httpd_sys_rw_content_t /var/www/MISP/app/Config/config.php
```

**Comment by RenatoMG** [comment]
I have MISP in Ubuntu and when i try to correct Server Settings & Maintenance i got this:

Warning: app/Config/config.php

Im using Ubuntu Server 18.04.4 LTS and i tried: 

chcon -t httpd_sys_rw_content_t /var/www/MISP/app/Config/config.php 

and got this:

chcon: can't apply partial context to unlabeled file **'/var/www/MISP/app/Config/config.php**


I´ve installed SELINUX, edit the config file to SELINUX to:

SELINUX=enforcing

And i keep getting this error

**Comment by killtr0** [comment]
@RenatoMG 

You must go to the following route:

**var/www/MISP/app/Config/**

the problem is that the config.php file is assigned to root user.

then we must assign the user www-data with the following command:

**sudo chown www-data:www-data config**

**Comment by simillo01** [comment]
@killtr0 solution works also on freshly installed MISP 2.5 on Ubuntu 24.04
