### ISSUE TITLE
Adding multiple tags at once on the Instance

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#2374]
Feature Request

In Misp under Event Actions ---> Add Tag.

Here we can Add tag on the system which than can be later to tag events/attribute.

Would like to request to have option to Add multiple tags. Currently you can only add : 

Name | Color | Restrict Tagging to - Can we have multiple rows of the same.
Name | Color | Restrict Tagging to
Name | Color | Restrict Tagging to

**Comment by mokaddem** [comment]
Hi!
This feature is now live on the latest version of MISP.
Enjoy!
