### ISSUE TITLE
MISP synchronisation don't update tags

### ISSUE THREAD

**Issue by Piosec** [MISP/MISP#2378]
Hello, 

I have two MISP a master and a slave, the slave is synchronised to the master. But when I delete some tags and I try to pull them back with "Sync actions --> List servers --> Pull updates on events that already exist locally"
My issue is that don't work. 

The connection between these MISP is working.

Thank you for your help !

**Comment by maraboutingermany** [comment]
Does your sync user have tagging rights?

**Comment by Piosec** [comment]
No, it doesn't. 
I have add Tagger and Tag editor. 
I have try again but it don't work, I have only received my new events.

The rights of sync user are now "Tagger, Tag editor, sync actions, auth key acess, sighting creator"

Have I to add some other rights ?

**Comment by RichieB2B** [comment]
MISP only pulls data when it is needed, so it compares the event timestamp on the remote server with the local event timestamp. When you remove (or add) a tag locally the event locally is newer than the event on the remote server. So a pull will not update that local event unless the event on the remote server is also updated after you updated the local event.

**Comment by Piosec** [comment]
I have add a new tag on my master MISP and it don't work either.

**Comment by iglocska** [comment]
Did you republish it after adding the tag?

**Comment by Piosec** [comment]
When I publish it, it works. 
But all my events are published. 
I can't go on all my events and add a new tags for receiving all my losts tags.

**Comment by iglocska** [comment]
The workflow should be like this:
MISP1:
Create event1
add tag1
publish

MISP2 gets:
event1 with tag1

MISP1:
add tag2 to event1
event1 becomes unpublished
publish event1 again (since it got modified)

MISP2 gets:
tag2 for event1

**Comment by Piosec** [comment]
Yes I understand it, but if the tag2 is removed on MISP2, I can't get it back ?

**Comment by iglocska** [comment]
Tag 2 removed by whom? The tag not being attached to the event or the tag removed completely?

**Comment by Piosec** [comment]
The tag removed by a user. 
The tag2 is attached to event1 on both MISPs. But a user deleted the tag2 attached to event1 on the MISP2. I need to get this tag back attached to the event1.

**Comment by Piosec** [comment]
I have try to delete an event and reimport it, but it doesn't works without republished it.
Do you have an other solution ?
Should I modify the timestamp of events ?

**Comment by iglocska** [comment]
I am not really sure what you are trying to do. Could you walk me through it step by step what exactly happened and what you would like as an end result?

**Comment by Piosec** [comment]
MISP1:
event 1: tagA, tagB
event2 : tagA, tagB
Events 1 and 2 are published
MISP2: 
event 1: tagA, tagB
event2 : tagA, tagB
MISP2 received events 1 and 2

Above, that is what I had. Now it's like that : 

MISP1:
event 1: tagA, tagB
event2 : tagA, tagB
Events 1 and 2 are published but I don't republished them
MISP2: 
event 1: 
event2 : 

What I am expecting for is to get back my MISP2 tags, like that : 
MISP2:
event 1: tagA, tagB
event2 : tagA, tagB

**Comment by iglocska** [comment]
So someone on MISP 2 removed the tags - that looks like it's something intended no? I mean the version on MISP2 is newer than on MISP1. 

If you want to get the tags back you have a few options:

1. Republish the events on MISP1
2. Decrement the timestamps of the events on MISP2 and pull from MISP1 / push from MISP 1 -> MISP 2
3. Delete the events on MISP2 and just re-push them from MISP1 (make sure you disable event blacklisting so your MISP won't block the events from being re-added)
4. Re-add the tags manually / via an external script

But this seems like intended behaviour to me.

**Comment by iglocska** [comment]
ahhh I see what's going on, misunderstood. So you had a user that is a tag editor just delete the tag. That is indeed an issue (not the EventTag, so the association from the tag -> event). 

For now fixing this is a bit tricky, the options I've listed above should work. For the future: I'll update it so that only site admins can actually delete tags.

**Comment by Piosec** [comment]
So the best option for me is to decrease timestamp on MISP2, what do you advice me ? 
A script which make modification on the database ?

**Comment by Piosec** [comment]
Hi, 
I have updated the timestamp of each event to an older and it works all deleted tags are back.
Thank you for your help ! :)
