### ISSUE TITLE
Cannot get automatic export based on tag

### ISSUE THREAD

**Issue by orbital-github-user** [MISP/MISP#2383]
Here running MISP 2.4.78,

when I go to http://192.168.56.50/attributes/text/download/ip-src/test where "test" is a tag I assigned to one event, I just get a blank txt file.

http://192.168.56.50/attributes/text/download/ip-src/tlp;white returns a blank file as well.

With:
http://192.168.56.50/attributes/text/download/ip-src/tlp:white
http://192.168.56.50/attributes/text/download/ip-src/tlp:red
http://192.168.56.50/attributes/text/download/ip-src/
I receive exactly the same file, the whole list of src-ips

is tag filtering not working or am I doing something wrong?

**Comment by jaxre** [comment]
I have the same issue on 2.4.92
I'm unable to export attributes when I include a tag in my filter

However I think if you try using a semicolon instead of a colon in your tlp tags, it might work.
From the docs:

> Please be aware the colons (:) cannot be used in the tag search. Use semicolons instead (the search will automatically search for colons instead).

**Comment by iglocska** [comment]
Please use post requests with the filters in json objects, url parameter filters are dirty and can fail in all sorts of ways.

**Comment by jaxre** [comment]
Thanks for the suggestion! Unfortunately, it looks like I get a list of all the indicators when I do the below (regardless of what I specify as type):

``curl -H "Authorization: [APIKey] "
-X POST 
-d {"type":"domain", "tags":"my_tag"} 
https://my.misp.instance/attributes/text/download ``

Maybe I'm doing it wrong? I'm trying to get a text export of all my indicators of a specific type with a specific tag.

**Comment by EdAtt** [comment]
jaxre,
Did you ever get a fix for this issue?  I'm having the same type of problem at the moment.
~Ed

**Comment by geekscrapy** [comment]
Does this work in the latest versions?

**Comment by iglocska** [comment]
Yes, please use the restSearch apis instead though.

/attributes/restSearch

Payload:

```
{
  "returnFormat": "text",
  "tags": ["mytag", "myothertag"]
}
```

Please use the rest client via the ui to generate the curl queries to avoid mistakes.

**Comment by andrew134598** [comment]
@iglocska : Your proposal doesn't work. You should use "csv" instead of "text" as a returnFormat
