### ISSUE TITLE
Recommended key type: RSA (sign only)

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#239]
Why does the installation procedure recommends to use RSA (sign only)? 

https://github.com/MISP/MISP/blob/master/INSTALL/INSTALL.txt#L119

**Comment by elhoim** [comment]
@iglocska any reason why there is this recommendation?
If not then we should remove it since it is best users decide for themselves.

**Comment by iglocska** [comment]
Agreed, no clue why it's there.

**Comment by cvandeplas** [comment]
The reason I wrote this in the recommendation is that the MISP server GPG key has no need to do encryption, only signing. 

However it can indeed be argued that we should be careful with making cryptographic recommendations. (and keeping them up-to-date)

For me it can be removed by integrating elhoim's pull-request.

**Comment by elhoim** [comment]
Handled with commit  7d3f53e.
