### ISSUE TITLE
MISP Server Sync

### ISSUE THREAD

**Issue by RCPMAD** [MISP/MISP#2395]
Hello,

I am having some issues with syncing two MISP instances I own. What I have is the following...

MISP-CORPORATE
This instance has a self signed certificate from my own CA. They are named misp-corporate.cer (public) and misp-corporate.key (private)
MISP-DMZ
This instance has a self signed certificate from my own CA. They are named misp-dmz.cer (public) and misp-dmz.key (private)

HTTPS access has been opened one way from the firewall (source MISP-CORPORATE to MISP-DMZ destination) and I am trying to sync data from MISP-DMZ to MISP-CORPORATE. This is done by adding the MISP-DMZ server to MISP-CORPORATE to pull information from MISP-DMZ. I am unsure if I need to open traffic both ways and also add the MISP-CORPORATE server to MISP-DMZ with the push option enabled. I will open the HTTPS access both ways.

I am well aware that the following need to be ticked when adding a server:
Internal instance
Self Signed
Server certificate file (*.pem): Not set.
Client certificate file: Not set.

I've taken misp-dmz.key (private) and renamed it to misp-dmz.pem (private) and uploaded in the "Server certificate file (*.pem): Not set.".  I've also taken misp-dmz.cer (public) and renamed it to misp-dmz.pem and uploaded in the "Client certificate file: Not set." (the original file name "misp-dmz.cer" would not upload).

These sections are not very specific of what exact certs needs to be uploaded and I am not sure what is going wrong here.

I am getting the following error when I am trying to test the connection...

Uploaded private key in "Server certificate file (*.pem): Not set." and public key in "Client certificate file: Not set."
Error: Connection test failed. Reason: "no valid certs found cafile stream: `\/var\/www\/MISP\/app\/files\/certs\/1.pem'\nstream_socket_client(): Failed to enable crypto\nstream_socket_client(): unable to connect to ssl:\/\/misp-dmz.some.domain:443 (Unknown error)" 

Uploaded the other way around.
Error: Connection test failed. Reason: "stream_socket_client(): Unable to set local cert chain file `\/var\/www\/MISP\/app\/files\/certs\/1_client.pem'; Check that your cafile\/capath settings include details of your certificate and its issuer\nstream_socket_client(): Failed to enable crypto\nstream_socket_client(): unable to connect to ssl:\/\/misp-dmz.some.domain:443 (Unknown error)"

**Comment by RCPMAD** [comment]
Any advice on this?

**Comment by enkidunolinux** [comment]
RHEL7 on AWS

**Comment by iglocska** [comment]
it looks like a simple certificate issue. Basically you need the entire certificate chain (root CA, intermediary CAs - if any exist, server certificate) in the .pem file that you are uploading and it needs to be a valid .pem file. (so first you need to convert the key using openSSL and then create a combined certificate chain file in pem format - this can be a bit painful, there are some tools out there that do that, or you can do it manually but watch out for the order of the certificates in the file as it matters...).

**Comment by RCPMAD** [comment]
Thanks that worked.

**Comment by iglocska** [comment]
Excellent, thanks for the feedback! Will close the issue, feel free to open a new one if you run into any other issues.
