### ISSUE TITLE
Suricata export turns url attributes into tls_cert_subject rules

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2396]
When exporting MISP events to Suricata format the code at https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsSuricataExport.php#L138 turns an HTTPS url into a tls_cert_subject rule. This is not at all the same thing and causes a lot of false positives. This type of conversion should really be avoided when exporting from MISP.

**Comment by xme** [comment]
I'm facing the same issue (many FP's)

**Comment by iglocska** [comment]
Makes sense, removed it.
