### ISSUE TITLE
ReadOnly Events view is not showed properly

### ISSUE THREAD

**Issue by georgyana** [MISP/MISP#2397]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 9.
| OS version (client)       | All
| PHP version               |  7.0, 
| MISP version / git hash   | 2.4.78
| Browser                   | All

### Expected behavior
For users with ReadOnly we expect to see the table of events, correctly arranged.

### Actual behavior
The header of the table which shows the events has 13 columns (th tags) but the content of the table has only 12 columns (td tags). Therefore the table heading start with an empty th, followed by the Published th and the table lines data are starting with Published td.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/30806442/29331565-8994c074-8205-11e7-95cb-ce3cf97e5d2c.png)

**Comment by iglocska** [comment]
Thanks for the heads-up, should be fixed now.
