### ISSUE TITLE
View Taxonomy doesn't show all Tags

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#2399]
I have an issue with seeing the tags of a taxonomy when selecting View Taxonomy. It is not possible to see more than approximately the half of the listed tags.
Has anybody experienced the same problem?

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, support
| OS version (server)       | Ubuntu 16.04.1
| OS version (client)       | Win 7, Ubuntu 16.10
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.77 and 2.4.78
| Browser                   | Chrome, Firefox

### Expected behavior
Seeing all tags when selecting List Taxonomies --> View

### Actual behavior
When choosing a taxonomy with more than one page of tags, the latter half of the pages are empty. The middle page is interrupted, so that just a few tags are shown.

### Steps to reproduce the behavior
This behaviour applies to all Taxonomies with more than one page of tags. It occurs on all our MISP instances and from all clients.

### Logs, screenshots, configuration dump, ...
Empty page:
![view taxonomy](https://user-images.githubusercontent.com/31033198/29353767-9f717aac-826b-11e7-994e-c4953cbbc4bc.png)

Mid page:
![view taxonomy 2](https://user-images.githubusercontent.com/31033198/29353774-a3ea67c4-826b-11e7-8ae3-377c4afb40af.png)

**Comment by iglocska** [comment]
Thanks for the heads-up, indeed, introduced a bug recently that truncated the data twice, causing all sorts of weird results. Should be fixed now.
