### ISSUE TITLE
SALT KEY

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2400]
On the installation instructions where it says "# The salt key must be a string at least 32 bytes long." does this mean the 32 bytes can be any 32 bytes of my choice or there is a specific way in which I have to generate the 32 bytes.

**Comment by iglocska** [comment]
32 bytes of your choice. The point is simply not to have a salt too short or too long.

**Comment by ndhambi** [comment]
Thanks, it worked :)

**Comment by iglocska** [comment]
Perfect, will close this issue for now, feel free to open a new one if you run into any other issues!
