### ISSUE TITLE
Users cannot login after upgrading to MISP 2.4.78

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2401]
After upgrading to 2.4.78 (from 2.4.75) users with the old password system cannot log in. Only after resetting their password (and thus upgrading them to Blowfish) they can log in, but then they can not change their password, see #2394 

This issue is that the old 40 bytes hash is fed into the cakephp BlowfishPasswordHasher::check() function which failes because those 40 bytes are not a valid blowfish format.
```
2017-08-16 10:10:01 Warning: Warning (512): Invalid salt: {40xHEX} for blowfish Please visit http://www.php.net/crypt and read the appropriate section for building blowfish salts. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Security.php, line 323]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Security::_crypt() - APP/Lib/cakephp/lib/Cake/Utility/Security.php, line 323
Security::hash() - APP/Lib/cakephp/lib/Cake/Utility/Security.php, line 115
BlowfishPasswordHasher::check() - APP/Lib/cakephp/lib/Cake/Controller/Component/Auth/BlowfishPasswordHasher.php, line 45
BaseAuthenticate::_findUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php, line 138
FormAuthenticate::authenticate() - APP/Lib/cakephp/lib/Cake/Controller/Component/Auth/FormAuthenticate.php, line 79
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 771
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 611
UsersController::login() - APP/Controller/UsersController.php, line 769
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by iglocska** [comment]
Hmm it shouldn't be fed into that. The system should log users that have a
40 byte hash in using the old password hasher and then silently convert the
password immediately after to a blowfish hash. This is utterly strange as
it worked on all communities that we've upgraded.

So, what could be different in your case? Could it be some CentOS odditiy?

**Comment by iglocska** [comment]
Setting up CentOS now, will get back with a fix if I can reproduce it ;)

**Comment by RichieB2B** [comment]
Thanks. I know CentOS has its quirks but I doubt taking an entirely different php code path is one of them.

**Comment by RichieB2B** [comment]
I can confirm that the code in https://github.com/MISP/MISP/blob/2.4/app/Controller/UsersController.php#L766 is hit and `authenticate['Form']['passwordHasher']` is unset, yet still Blowfish is being used according to the error.log. Setting it to `Simple` does not help either.

**Comment by iglocska** [comment]
I don't get this. So what I did: Installed a fresh installation of CentOS7 using the install instructions of 2.4.75, with 2.4.75 in detached mode checked out, added 3 users with the same password (Password1234). I've snapshotted the VM afterwards. Users could log in just fine.

Upgraded MISP to HEAD, ran the upgrade scripts, logged in as the admin user. Logged out, logged back in all worked fine. The password hashes in the meanwhile looked like this:

![blowfish](https://user-images.githubusercontent.com/3668672/29366186-9f112b4c-8299-11e7-9464-552fd22dfeca.PNG)

No idea what's happening over there.

**Comment by iglocska** [comment]
By the way, just an FYI, something I've noticed that was giving me trouble: On a brand new installation under CentOS config.php is not writeable. Since we don't have a default salt anymore, it is created on first login (unless manually set), this means that MISP cannot save the salt. I have resolved this on my end by changing the privileges to config.php - I wonder if this could in some weird way affect you though...
