### ISSUE TITLE
An internal error has occurred on web interface

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2403]
I tried logging into the web-interface of MISP after completing the install instructions. I get an error that says:

" An Internal Error Has Occurred.
Error: An Internal Error Has Occurred."

**Comment by iglocska** [comment]
Could you paste the stack trace from /var/www/MISP/app/tmp/logs/error.log?

**Comment by ndhambi** [comment]
" 2017-08-17 08:44:47  Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
 Exception Attributes : array (
      'class' => 'Mysql',
      'message' => 'SQLSTATEMENT[HY000] [1045] Access denied for user \'misp\'@\'localhost\' (using password: YES)',
'enabled' => true,
) 
Request URL:/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/Cakephp/lib/Cake/Model/ConnectionManager.php(105): DBoSource->_construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventController.php(33):: AppController->beforeFilter()
#4 /var/www/MISP/app/lib/cakephp/lib/Cake/Event/CakeEvent Manager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www//MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
"

**Comment by iglocska** [comment]
> Access denied for user 'misp'@'localhost' (using password: YES)',



mysql credentials are wrong. Please fix it in /var/www/MISP/app/Config/database.php

**Comment by ndhambi** [comment]
I have opened the config.php file but i am not sure which paramters have to be set or fixed ,

![img_8573](https://user-images.githubusercontent.com/30654371/29407538-feb2ffc0-8344-11e7-9ea8-21baf5acd91f.JPG)

**Comment by FloatingGhost** [comment]
You opened the wrong damn file.

Please re-read the comment above.

**Comment by ndhambi** [comment]
I opened the right one, is it not /var/www/MISP/app/Config/config.php , check at the top on the image i posted

**Comment by FloatingGhost** [comment]
One of these filenames is not like the other
one of these filenames just doesn't belong
![2017-08-17-113031](https://user-images.githubusercontent.com/4086403/29408305-92753bac-833f-11e7-974e-b6d51af23652.png)

**Comment by ndhambi** [comment]
Im sorry about that , i made a reading error

**Comment by ndhambi** [comment]
I Have opened the right file now, see the attached image, i am not sure of which parameters i have to change
![img_8574](https://user-images.githubusercontent.com/30654371/29408871-2d1a3374-834a-11e7-9ebf-6cbdaf16bc23.JPG)

**Comment by iglocska** [comment]
The error was on my end, I wrote config.php first and then corrected it, the email was wrong. ;)

**Comment by ndhambi** [comment]
On step 9 of installation onstruction , there is a part that say "# delete the user from mysql and log in again using the default admin credentials (admin@admin.test / admin)"

So i deleted the user MISP on that step, so i now dont know what to change the 'login'paramter to since i Dropped that user as said on step #9

**Comment by RichieB2B** [comment]
Which installation instructions are you using? They sound very wrong.

**Comment by ndhambi** [comment]
Got it sorted out , Thanks guys :)

**Comment by adulau** [comment]
Great news. What kind of coffee are you drinking?

**Comment by adulau** [comment]
@WakandaKing Curious because seeing the reflection of the picture on your desk ;-)

**Comment by nagharaaj** [comment]
i  have Error: An Internal Error Has Occurred. while  connect web services

**Comment by TracesOfNuts** [comment]
> Great news. What kind of coffee are you drinking?

Asking the right questions
