### ISSUE TITLE
GnuPG installation and settings....FAIL: Issues with the key/passphrase

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2408]
On the web-interface under diagnostics , on the GnuPG , i get an error that says "GnuPG"installation and settings....FAIL: Issues with the key/passphrase". I have followed the install instructions and created the Gpg key according to the instructions.

Does anyone have an idea on how to fix this?

**Comment by iglocska** [comment]
Make sure that you have correctly filled out the GnuPG.x in administration->server settings ->encryption.

**Comment by ndhambi** [comment]
I have checked that, the password filled was not filled . I filled it in  but i still get the same error on the web-interface

**Comment by ndhambi** [comment]
Finally solved it, turns out that somehow somewhere MISP was changing the GnuPG.x homedir on the administration->server settings ->encryption to /var/www/MISP/**,gnupg** instead of /var/www/MISP/**.gnupg** , it was changing the dot infront of gnupg to a comma.
