### ISSUE TITLE
MISP feeds

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2413]
I have installed MISP and set its settings and no critical issues remain. I wanted to know on what i have to do inorder to start getting feeds and events from outside, I have checked on the List feeds tab under Sync Actions, it just lists the the defaults feeds but i cant enable them. scree
<img width="947" alt="feeds" src="https://user-images.githubusercontent.com/30654371/29555230-469c274a-8722-11e7-8678-b9729df6b3be.PNG">

**Comment by adulau** [comment]
Enabling and caching is on the right side of the feed.

**Comment by iglocska** [comment]
Right side* ;)

**Comment by ndhambi** [comment]
Got it, Thanks :)
