### ISSUE TITLE
Add False Positive Trought MISP API 

### ISSUE THREAD

**Issue by Piosec** [MISP/MISP#2417]
Hi, 

I don't find function for add some False Positive with MISP API. 
Sighting functions only add positive sighting. 

Do you know how to add a false positive with MISP API ?

Thank you.

**Comment by Piosec** [comment]
For add false positive, I must specify the type. 
0 --> Positive
1 --> False Positive 

Ex : 
misp.set_sightings({'values':['test.com'],'type':'1'})

**Comment by iglocska** [comment]
Yep, you can set false positive sightings by POSTing a JSON object with the appropriate values, though I checked our documentation is not up to date. In the JSON you have some additional attributes such as:

type (0|1|2) where 0 = sighting, 1 = false-positive, 2 = expiration
source (string)

So something like 

`{"type":1, "values":["http://programming-motherfucker.com/"], "source":"My IDS"}`

should work

**Comment by iglocska** [comment]
You were too fast ;)
