### ISSUE TITLE
Twitter feed to pastebin to MISP

### ISSUE THREAD

**Issue by ater49** [MISP/MISP#2420]
Hello,

Is it possible to create a new type of feed ?

In order to obtain IOC from Twitter reverser's account, we do some specific search and download all pastebin or ghostbin they publish or retweet and import them into MISP as FreeText Import.

Is there a way to doing this in a better way ?

Regards,

**Comment by SteveClement** [comment]
The [AIL Framework](https://github.com/CIRCL/AIL-framework) might help.
