### ISSUE TITLE
User can't login after reset password / new users can't login

### ISSUE THREAD

**Issue by amuehlem** [MISP/MISP#2421]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

User can't login after resetting the password. I tried to reset an existing user password with the automatical option and also tried to manually set a password. The user can't login afterwards. Existing users can login without any problems, new or changed users have the same issue.

debug.log shows the following error

2017-08-25 12:49:30 Notice: Notice (8): Undefined offset: 0 in [/xxx/MISP/app/Controller/UsersController.php, line 762]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::login() - APP/Controller/UsersController.php, line 762
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue            | Bug
| OS version (server)  | CentOS 
| OS version (client)   | 7.3
| PHP version             | 5.6
| MISP version / git hash   | 2.4.78 / b0ac802
| Browser                   | Chrome / FireFox

### Expected behavior
User can change the password and login

### Actual behavior
User password is changed, user can't login afterwards

### Steps to reproduce the behavior
log in as admin, reset userpassword or create new user
user can't login, error is shown in debug.log

**Comment by iglocska** [comment]
Could you git pull the latest commit on head? Alternatively we'll release
2.4.79 today anyway.

**Comment by adulau** [comment]
I suppose we can close this one following the gitter discussion. Feel free to reopen if you think that is not solved.
