### ISSUE TITLE
No Worker Active !!!!!! 

### ISSUE THREAD

**Issue by SivaPrem** [MISP/MISP#2423]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question,
| OS version (server)       | Ubuntu 16.04.3 LTS.
| PHP version               | PHP 7.0.22-0ubuntu0.16.04.1 (cli)
| MISP version / git hash   |MISP 2.4.78
| Browser                   | chrome

#### Did these Steps
Stop workers: /var/www/MISP/app/Console/cake CakeResque.CakeResque stop --all
Access Server Settings web UI >> Workers
Click Restart all workers
No immediate change indicated in web UI
But even i refresh the workers are still inactive

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/3869254/29775289-ed7ec22a-8c04-11e7-9d7e-30946d4cea76.png)
![image](https://user-images.githubusercontent.com/3869254/29775294-f521ade4-8c04-11e7-9eed-c313429133fe.png)

**Comment by adulau** [comment]
Maybe the workers were started with a user different than the web server user? and then the permissions of files were changed?

**Comment by SivaPrem** [comment]
@adulau : Thank you very much , it works good now !!!!!!!!!!!!!!!!!!
