### ISSUE TITLE
API authentication failed

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2424]
Hi.

I'm having an issue with accessing the API.
I only get authentication errors, and this in the logs, even though I do pass a key in the URL.
Like this for example: 

`curl -H "Authorization: wOIkclYRY98aAw5ij7eUOuPkEEKVJPHteFwvMIwC" -H "Accept: application/json" http://<url_of_server>/events/xml/download/2
`
And the error.log

```
2017-08-28 16:37:01 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
Request URL: /events/xml/download/2
Stack Trace:
#0 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#1 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

```

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | RedHat
| OS version (client)       | 7.3
| PHP version               | 5.6
| MISP version / git hash   | v2.4.78-74-gad60bdd (ad60bddc2d44f12c1b7bf2f8f70464d849a5d5e3)
| Browser                   | If applicable

### Expected behavior
Get the data requesteds via API

### Actual behavior
Get an authentication error:
`{"name":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","message":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","url":"\/events\/xml\/download\/2"}
`

**Comment by ghost** [comment]
Answering my own question here just in case someone else stumbles on this problem.
After digging around a bit, and debugging the old fashioned way, i discovered that Apache was just not sending the authorization header to php.

Added the following to /etc/httpd/conf.d/misp.conf and things started working:

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by Moorocks** [comment]
Hwllo @hcp123 , 

Thanks for your post. 
I encountered the same problem, but i was not able to find misp.conf file. This is hosted as docker in our dev environment.

Can you suggest what could be the issue?

**Comment by ghost** [comment]
Hi,
Not really an expert on docker :-) But usually the webserver (apache for
instance) would be in a separate container from the MISP backend. So the
apache config file would be somewhere in that container.
I have usually seen the config files being stored on some kind of
persistent storage, eiter just a directory on the host thats running the
docker containers or on some kind of storage backend (ceph maybe)
The file is probably not called misp.conf, as that is something I added,
but somewhere in the Apache config.

Sorry I cant be of more help.



tir. 6. aug. 2024 kl. 05:56 skrev Moorocks ***@***.***>:
