### ISSUE TITLE
Regex location

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2425]
Where are is location of the regexes that the open text box uses for extracting IOCs? I would like to modify them for our location and events.

**Comment by adulau** [comment]
https://github.com/MISP/MISP/blob/2.4/app/Lib/Tools/ComplexTypeTool.php#L184

**Comment by BenjaminJoly** [comment]
I assume, as the question been answered, that I can close the issue. Feel free to tell me if I should reopen it.
