### ISSUE TITLE
Event table sorted by?

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2429]
Quick question: 
What determines how the event table is being sorted?

Whenever i browse to our MISP (or any other) the events are neither sorted by event id nor by date. 

![screenshot](https://user-images.githubusercontent.com/20771149/29860782-7328327c-8d67-11e7-93cb-10329d55e40b.JPG)

This makes it difficult to spot new events first. On the other side if i sort the table by date, i might not see updates on older events because the column "date" only shows the published date, correct?

What is your best practice on this? Would it maybe make sense to have two columns, one with the "published date" and one with the "updated date"?

_________________________

For example:
1. Once an event is created (let's say on august 31st 2017) the dates could be like this:
Published on: 31.08.2017 | Updated on: 31.08.2017

2. Once an event gets updated (let's say on september 20th 2017) the dates would be like this:
Published on: 31.08.2017 | Updated on: 20.09.2017

So if i was to sort the table by the "updated date" i would spot all new events and in addition the updated attributes right away.

_________________________

I am not sure if i just got confused or whether this was actually worth a question. :)

**Comment by iglocska** [comment]
Timestamp, so last edit. This is a field that is internal and not shown on
the event index itself. The date field is the arbitrary date set by the
analyst, for example, for a sandbox analysis result the user would put the
date of the analysis which would be different from the last edit date if
the user inputs the event after waiting a week.

**Comment by ghost** [comment]
Check. Thank you, makes sense.
