### ISSUE TITLE
Distribution in a VM?

### ISSUE THREAD

**Issue by ericbl** [MISP/MISP#243]
Hello!
I am just trying Misp and fighting with the installation on my Debian stable (trouble with CakePHP). I am trying to install it on a fresh Ubtuntu server VM, so that it can be reused by my colleagues.
But wondering: could you maybe directly distribute MISP stable on a VM, which will work fine out of the box?  It seems to become the standard for such security environments...

**Comment by elhoim** [comment]
A user has contributed a script on the MISP mailing list to automate most of the install for an ubuntu.
I asked if he is ok to share it on github.

Anybody up for creating a docker template?

**Comment by elhoim** [comment]
Docker recipe available for easy setup: https://registry.hub.docker.com/u/eg5846/misp-docker/

Might be worth mentioning at some places, for example by adding notes or a file in INSTALL directory.

**Comment by elhoim** [comment]
Just noticed that the date for the file is " 2014-07-19 07:43:57" which means it might still be v2.2 not v2.3.
Details of the docker file are available at https://registry.hub.docker.com/u/eg5846/misp-docker/dockerfile/

**Comment by elhoim** [comment]
Tracked under #524 now, closing this one.
