### ISSUE TITLE
Description mistake for Export setting

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#2433]
# Typo mistake in the description of Plugin.Export_timeout setting

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Text mistake.
| MISP version / git hash   | 2.4.79

### Expected behavior
Server Settings -> Plugin settings -> Export -> Plugin.Export_timeout setting -> Description = "Set a timeout for the import services"

### Actual behavior
Description should be "Set a timeout for the export services"

### Steps to reproduce the behavior
Look at the setting description

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/1122246/29925074-7f567704-8e5f-11e7-989e-c8e84c6fbf59.png)

**Comment by iglocska** [comment]
Cough, copy pasta fail. Thanks for the heads-up!

**Comment by BenjaminJoly** [comment]
As the typo error is now correct, I close the issue. Do not hesitate to tell me if you want that ticket opened again.
