### ISSUE TITLE
Add attachement per API

### ISSUE THREAD

**Issue by itsab** [MISP/MISP#244]
Is it possible to add an attachment and upload a file, for example a malware-sample, automaticly without having to upload it manually over the webinterface?

If it is already possible, could you give me an example on how to forge the request to do so, otherwise would it be hard to implement into MISP?

**Comment by elhoim** [comment]
@iglocska Does it work to add attachments via REST API?
I could not find anything in the user guide or in pymisp indicating it is possible, and I don't get where in the MISP code the REST calls are handled.

**Comment by iglocska** [comment]
It is kind of possible. You have to add it in an attachment / malware
sample attribute in the "data' field, base64 encoded.

**Comment by elhoim** [comment]
So it is answered, closing the issue.

**Comment by iglocska** [comment]
Just a heads-up, since 3abbae90cf23ee93123481ead0e229ae32e239ca you now have a new API that should make uploading malware samples much easier. Check out the automation documentation!
