### ISSUE TITLE
main page login issue

### ISSUE THREAD

**Issue by enkidunolinux** [MISP/MISP#2440]
Hi 

I have an issue logging to the main  misp page after a fresh install on RHEL7:
### You have tripped the cross-site request forgery protection of MISP

CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.

Alternatively, click here to continue to the start page."

I get this error regardless of the credentials I use, so I guess its ever before authenticating me!

Here below the errors that I can see
```
`2017-09-04 07:31:38 Warning: Warning (2): session_start(): open(/var/opt/rh/rh-php56/lib/php/session/sess_m804tuavs5pqp2tai21s3ur887, O_RDWR) failed: Permission denied (13) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 708]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_start - [internal], line ??
CakeSession::_startSession() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 708
CakeSession::start() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 204
CakeSession::check() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 233
AuthComponent::user() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 669
SysLogLogableBehavior::setup() - APP/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php, line 277
BehaviorCollection::load() - APP/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php, line 145
BehaviorCollection::init() - APP/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php, line 66
Model::__construct() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 781
AppModel::__construct() - APP/Model/AppModel.php, line 34
ReflectionClass::newInstance() - [internal], line ??
ClassRegistry::init() - APP/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php, line 169
Controller::loadModel() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 742
AppController::beforeFilter() - APP/Controller/AppController.php, line 111
UsersController::beforeFilter() - APP/Controller/UsersController.php, line 29
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2017-09-04 07:31:38 Error: [BadRequestException] csrf
Request URL: /users/login
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-09-04 07:31:38 Warning: Warning (2): Unknown: open(/var/opt/rh/rh-php56/lib/php/session/sess_m804tuavs5pqp2tai21s3ur887, O_RDWR) failed: Permission denied (13) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2017-09-04 07:31:38 Warning: Warning (2): Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/opt/rh/rh-php56/lib/php/session) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??
`
```
```
[root@blabla php]# ls -l
total 0
drwxrwxrwx. 2 root apache 6 Sep  6  2016 session
drwxrwx---. 2 root apache 6 Sep  6  2016 wsdlcache

```

**Comment by iglocska** [comment]
The issue is this:

```open(/var/opt/rh/rh-php56/lib/php/session/sess_m804tuavs5pqp2tai21s3ur887, O_RDWR) failed: Permission denied (13)```

I think we've had someone else with this issue recently, for some reason php can't write the session files in the default path. No problem though, you shouldn't be using the file handler in the first place.

By default MISP relies on PHP's session handling, so the best approach is to switch that to redis sessions by adding the following two lines to your php.ini:

```
session.save_handler = redis
session.save_path = 'tcp://localhost:6379'
```

Just make sure you're editing the actual php.ini used by scl!

**Comment by enkidunolinux** [comment]
Hi @iglocska 
thanks for the quick response!

I have added these lines to the php.ini and still get exactly the same results!

I just need to clarify couple of things tho:

1- there were two php.ini files before I edited (the second)
```
./etc/php.ini
./opt/rh/rh-php56/register.content/etc/opt/rh/rh-php56/php.ini

```
after I edit (the second file) i can see there are three files now
```
./etc/opt/rh/rh-php56/php.ini
./etc/php.ini
./opt/rh/rh-php56/register.content/etc/opt/rh/rh-php56/php.ini

```
so I'm sure its related to your note "Just make sure you're editing the actual php.ini used by scl!" , I Just dont know how to make sure which one?

2- you mentioned "you shouldn't be using the file handler in the first place." I just followed the installation instructions, not sure If there is something not right there?

**Comment by iglocska** [comment]
You are indeed correct, the default installation is using the file handler, I mean that it's not the recommended way (but the recommended session handler takes some extra steps beyond the installation instruction's scope sadly). 

Any of RHEL users out there that can confirm which php.ini is actually being used and why the setting isn't taking? My guess would be the /etc/opt/rh/rh-rhphp56/php.ini but I could be horribly wrong.

In the meanwhile, what you can do to get going until someone with RHEL tests it (I can do it in a few days too): 

You can change the MISP session handler to not delegate it to php but instead enforce database sessions (this isn't the most performant option but should get the job done) by editing:

```/var/www/MISP/app/Config/config.php```

and changing the 'Session.defaults' directive to 'database' from 'php'.

Let me know if that works for now!

**Comment by enkidunolinux** [comment]
I'll do test it first thing in the morning, its getting a bit late here in Melbourne :).
I'm not really a linux person but this project landed on me and trying to get it going. eventually it will be one of the big setups of MISP im guessing, so Ill keep my notes and will let you know of the changes I've done to get it working so you can update "the installation guide" if you like. cheers

**Comment by iglocska** [comment]
Sure thing! Any ideas you have for improving the install guide are more than welcome, we ourselves use ubuntu so generally are a bit out of touch with potential issues on the RHEL side, luckily @RichieB2B normally comes to our rescue ;) But generally we highly recommend using Ubuntu.

Sleep tight and poke us anytime you have questions!

**Comment by enkidunolinux** [comment]
@iglocska changing the 'Session.defaults' directive to 'database' from 'php'. worked and for the first time after 6 attempts to install MISP i was able to login and see how it looks like actually, lots of red warnings tho!
will keep you posted, the next challenge will be all the integrations

**Comment by enkidunolinux** [comment]
Hi Guys 
checking again if anyone got misp working properly on RHEL7? and how they get redis handler working properly? @iglocska @RichieB2B hope you have some ideas for me?

**Comment by RichieB2B** [comment]
The core problem 
```
open(/var/opt/rh/rh-php56/lib/php/session/sess_m804tuavs5pqp2tai21s3ur887, O_RDWR) failed: Permission denied (13)
```
could be caused by SELinux. Check that `semanage fcontext -l` contains:
```
SELinux fcontext                                   type               Context

/var/lib/php/session(/.*)?                         all files          system_u:object_r:httpd_var_run_t:s0

SELinux Local fcontext Equivalence

/var/opt/rh/rh-php56 = /var
```

If it does, check that the security context on the filesystem is correct:
```
# ls -ldZ /var/opt/rh/rh-php56/lib/php/session/
drwxrwx---. root apache system_u:object_r:httpd_var_run_t:s0 /var/opt/rh/rh-php56/lib/php/session/
```
If not, fix it with:
```
restorecon -Rv /var/opt/rh/rh-php56/lib/php/session/
```

What are your current issues with the "redis handler" exactly?
