### ISSUE TITLE
Will be nice to have PE signed  certificate ioc

### ISSUE THREAD

**Issue by Th4nat0s** [MISP/MISP#2445]
Besides the SHA1 Certificate...

Will be nice to cut / paste the PEM and "voila" :) 

At least in "dropped artefact"  subject, issuer, email , serial, hash sha256 fingerprint , dates,

**Comment by Rafiot** [comment]
Do you mean a script that would get a PEM as input, and generate a MISP object x509 out of it? 

Is this object definition relevant? https://github.com/MISP/misp-objects/blob/master/objects/x509/definition.json

That make sense, and yeah, could be automated on MISP side, but in the mean time, a standalone script would make sense.

If you want to write it yourself, this is a relevant piece of code to get some inspiration: https://github.com/MISP/PyMISP/blob/objects/pymisp/tools/fileobject.py

If not, I'll implement it myself soon-ish. Potentially, it could be triggered by the peobject module so you just give the PE to the script and magic happen.

**Comment by adulau** [comment]
Does the new objects in MISP 2.4.80 solved your issue? You can link an X509 object to a file object with a relationship. Let us know.
