### ISSUE TITLE
Password resed does not reset the API key

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#245]
It would be great to change the API key automatically when a user change his password, making sure that is case of compromising, all the access are revoked.

**Comment by SteveClement** [comment]
The checkbox could be as easy as: if "first time registration" is checked, also refresh the API key.
Would make sense IMHO, plus easy to add ;)

**Comment by iglocska** [comment]
Definitely falls into the bad idea category, why would we reset it on an initial registration? 

However, for password resets it might make sense, but considering that users will often want to reset passwords without breaking any scripts that use their API keys I would not make it the default. Perhaps simply having a warning that it will not reset the API key would be better.
