### ISSUE TITLE
Scheduled tasks can't be executed

### ISSUE THREAD

**Issue by ssl-t** [MISP/MISP#2452]
Hi team.

I tried to be scheduled tasks  but Scheduled tasks couldn't be executed.

I set NextRun and Frequency but MISP ignore scheduled setting.

Now always can not be executed,It can be executed or can not be executed.

I can't understand that why can't be executed and when can't be executed.

Please teach me that how to setting for scheduled tasks.

My MISP version is  v2.4.79 (4730549f7ca68862704015a5d302da884d9c0cdf)

**Comment by iglocska** [comment]
Hello, 

@panzertime just pushed a fix for the issue, could you git pull and give it another shot?

**Comment by panzertime** [comment]
Ensure that you have CakeResque set up and that you have workers running

**Comment by maraboutingermany** [comment]
We upgraded to 2.4.79 a few days back and ran into the same issue, workers working fine, does 2.4.79 not have the fix or does it? It wasnt clear from the PR notes

**Comment by panzertime** [comment]
If you have commit 131f2cbf2ef12e6aa2ec8c3a12ec527a9b84267f or later, you should have the complete working code for this feature
