### ISSUE TITLE
The "cache_feeds" scheduled task is always requeued as a "pull_feeds" task

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#2458]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.0
| MISP version / git hash   | 2.4.79 latest commit on 2017-09-12

### Expected behavior
After the "cache_feeds" scheduled task is executed a first time, it should be re-scheduled to be executed in the same conditions as the first time. 

### Actual behavior
When it is executed after the defined period (cf. frequency), a "pull_feeds" is executed instead of a "cache_feeds". 

### Steps to reproduce the behavior
1. Define a schedule for the "cache_feeds" task. 
2. The first time, the "cache_feeds" task is executed correctly. 
3. Wait for the frequency you have defined (let's say 1 hour). 
4. All enabled feeds will be pulled instead of being cached. 

### Logs, screenshots, configuration dump, ...
The problem is in app/console/command/ServerShell.php, line 200, when Task::requeue is called. The $action parameter (0=pull, 1=cache) is ignored by Task::reQueue.

**Comment by panzertime** [comment]
I'll work on a fix for this

**Comment by panzertime** [comment]
PR incoming

**Comment by iglocska** [comment]
Implemented by @panzertime - thanks a lot!
