### ISSUE TITLE
MISP not connecting to internet & IP changing

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2459]
Hi.

I'm hoping you could assist me. I have MISP installed on a VM with Ubuntu server 16.04 and we have a DHCP server. Previously, it worked without the DHCP server. I have followed the intructions from the steps in issue #1195.

I am able to get past the login page to Home, but afterwards, it returns "There was a temporary DNS error: code: INET_E_RESOURCE_NOT_FOUND."

I thought it was an error on Microsoft Edge but no solutions seem to work. When I ping ubuntu, it returns a different IP address than the one on which the logon went through, and my Windows Host is not returning an IP address for my VM.

Any suggestions or assistance will be appreciated.

**Comment by DerFips** [comment]
Hey,

I had the same issue and as the misp user over SSH can't access the configuration you have to change the IP address manually.
Here's how to do it:

1. Connect to MISP with your own IP.
2. Login with admin user account.
3. Open the following link: http://<changeIPhere>/servers/ServerSettings/MISP
4. You see on Setting "MISP.baseurl" that there is the default IP (192.168.50.56).
5. Double click on the IP and you'll see the possibility to change the IP.
6. Do it and confirm it with the check button.
7. Reload the website and all links should be now with your "new" ip address.

Please let me know if this solved your problem, too!

Cheers, Philipp

**Comment by BenjaminJoly** [comment]
Any news on this issue, with a MISP up to date ?
