### ISSUE TITLE
Enforce sharing of events based on taxonomies

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#2461]
For example TLP

**Comment by iglocska** [comment]
The idea is that we should have a filter that requires a tag of a taxonomy to be set before it is synchronised.

**Comment by RichieB2B** [comment]
How is this different from the push/pull rules in the Sync Servers settings?

**Comment by iglocska** [comment]
For example: If a community only wants data that has a TLP marking set, then you could set the filter on a taxonomy level not on a tag level (pull anything with a tag from the tlp namespace).
