### ISSUE TITLE
Search Attributes page returning too many results

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2467]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| MISP version / git hash   | 2.4.79

### Expected behavior
When searching for attributes using the search attributes page from the web interface, some queries are not supposed to return any results since they are non-sensical or match 0 attributes.

### Actual behavior
All the attributes are returned.

### Steps to reproduce the behavior

- Example 1:
   - Search for a non-existing org (e.g.: NSA.gov).
   - You get results that contain all the attributes visible to the user.
- Example 2:
   - Search for an existing org (e.g.: CIRCL)
   - Add another condition for something not existing in one of the following fields:
        1. _Being an attribute matching the following tags_
        1. _Being attributes of the following event IDs, event UUIDs or attribute UUIDs_
        1. _Being an attribute of an event matching the following tags_
   - You get results that contain all the attributes visible to the user.

**Comment by RichieB2B** [comment]
This is a search using the API?

**Comment by elhoim** [comment]
It is using the web interface. I edited my comment to clarify.

**Comment by tosto92** [comment]
I've noticed the same behaviour when searching for an **existing** attribute tag.
I've an attribute tagged with "mytag" and when I search for attributes tagged with "mytag" I get as result the list of all the attributes.

**Comment by iglocska** [comment]
Fixed by 4d89a769605a734b84735d110e14a669be498d31
