### ISSUE TITLE
Exporting a big list of events ends in Internal Error

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#247]
If you try to export a big list of events (100+) , it simply fails with the following error:
{u'message': u'/events/restSearch/download/null/null/null/null/!OSINT', u'name': u'An Internal Error Has Occurred.'}

As it is quite huge, it is understandable. What I would like to do is to get a list of events ID in order to export them individually afterwards.

**Comment by elhoim** [comment]
Has it been fixed?
