### ISSUE TITLE
[Objects Final Tests] No confirmation message when deleting a reference

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2475]
### Expected behavior
When deleting a reference, MISP should tell the user that the action worked (or not) and the reference should not be visible even if the user does not refresh the page. Plus it could be expected that MISP warns the user if he tries to delete a reference that does not exist anymore  

### Actual behavior
Delete the reference without confirmation and needs a refresh to be visible.

### Steps to reproduce the behavior
Action :
Adding then deleting a reference to an object.

- When clicking on the bin associated with a reference, a popup asks if the user really wants to delete the reference. 
- Clicking "Yes" on this popup does not trigger any confirmation message and the reference is still visible (refreshing the page prouves that the reference is deleted)
- While not refreshing the page, user can still click on the bin and will again see the popup asking if he really wants to delete the reference. Clicking "Yes" on this popup will not show any message warning that the reference is already deleted. (Can be repeated)

**Comment by iglocska** [comment]
Hmm this is weird. This seems to work fine on my end - could you ctrl+f5 and see if the issue persists?

**Comment by BenjaminJoly** [comment]
Not relevant anymore.
