### ISSUE TITLE
[Objects Final Tests] References to deleted objects/attributes shoud be deleted or raise a warning

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2477]
### Expected behavior
References to objects/attributes that do not exist anymore should be deleted or raise a warning.

### Actual behavior
References to deleted objects/attributes still exist

### Steps to reproduce the behavior
- Create an first object (A)
- Create a second object or an attribute (B)
- In A, add a reference to B
- Delete B
>> B is still referenced in A

**Comment by iglocska** [comment]
Nice finds, thanks a lot!

**Comment by iglocska** [comment]
Thanks a lot, this was a nasty one. Fixed in the above commit.
