### ISSUE TITLE
MISP returns error when empty STIX update is requested

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2478]
When retrieving data in STIX format (either XML or JSON) when there is no (new) data to export, MISP will throw an `HTTP 500: Internal Server Error`. One example is:
```
http://misp.local/events/stix/download/false/false/false/false/false/1d
```
when there are no event less than 1 day old.

The error.log shows:
```
2017-09-15 13:58:35 Error: [Exception] No matching events found to export.
Request URL: /events/stix/download/false/false/false/false/false/1d
Stack Trace:
#0 [internal function]: EventsController->stix('download', false, false, false, false, false, 1505390315)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

The reason is that [in](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2889) [several](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2894) [places](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2976) the stix() function returns with success=0. Setting success=1 fixes the issue and returns HTTP 200 with a 0 bytes body. I'm not sure if that is the correct CakePHP way to handle this though.

**Comment by RichieB2B** [comment]
The real reason is the [unhandled exception](https://github.com/MISP/MISP/blob/2.4/app/Controller/EventsController.php#L3381) in the EventsController.

**Comment by iglocska** [comment]
Nice catch, i feel a disturbance in the force: must be the pr you want to
push 😉

Jokes aside, will fix it over the weekend (unless you do push one).

**Comment by RichieB2B** [comment]
There it is, straight from the dark side..

**Comment by RichieB2B** [comment]
Reopened by https://github.com/MISP/MISP/commit/23937eebb9c8295daee7eec512e80b2ffeaf4bee
