### ISSUE TITLE
[Objects Final Tests] "Referenced by" count does not increase

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2479]
### Expected behavior
"Referenced by" count should increase for each reference (or object referencing it)

### Actual behavior
The count is stuck the value "1" even when there are several reference from different objects.
However it disappears when it is suppose0d to reach 0.

### Steps to reproduce the behavior
- Create three objects (A, B, C)
Three possibilities :
- Reference A several times in B 
- Reference A in B and C
- Reference A several times in B and C
>> "Referenced by" count in A stays at "1"

### Logs, screenshots, configuration dump, ...

![screenshot from 2017-09-15 14-52-09](https://user-images.githubusercontent.com/17081497/30483878-d567247a-9a28-11e7-88b0-987996de213b.png)

**Comment by iglocska** [comment]
Fixed in the above commit.
