### ISSUE TITLE
[Objects Final Tests] Creation of Email object

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#2481]
### Expected behavior
Being able to save the object if at least one of the following attributes is set: email-src, 
email-src-display-name, email-dst, email-dst-display-name, email-subject, email-attachment, email-message-id, email-reply-to, send-date, url, email-mime-boundary, email-thread-index, email-header, x-mailer

### Actual behavior
Only able to save the object is one of the following attributes is set:
- url:url
- x-mailer:email-x-mailer
- send-date:datetime 

### Steps to reproduce the behavior
Try to create an email object with only one of the following set:
- From :: email-src 		
- Reply-to :: email-reply-to 		
- To-display-name :: email-dst-display-name 		
- Subject :: email-subject 		
- To :: email-dst 		
- From-display-name :: email-src-display-name 		
- Mime-boundary :: email-mime-boundary 		
- Thread-index :: email-thread-index 		
- Message-id :: email-message-id 		
- Attachment :: email-attachment 		
- Header :: email-header 	

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/17081497/30486150-ea8cdbea-9a2f-11e7-932d-763dfc4b1255.png)

**Comment by iglocska** [comment]
This one is actually an issue with the object itself: 

The object lists this as the required one of set:

```
email-src,
email-src-display-name, email-dst, email-dst-display-name, email-subject, email-attachment, email-message-id, email-reply-to, send-date, url, email-mime-boundary, email-thread-index, email-header, x-mailer
```

However, these are the attribute `types`, not the attribute relation names, meaning the only 3 it actually checks are the ones where the attribute object relation name and the attribute type overlap.

Solution: Need to rework the object.
