### ISSUE TITLE
[Objects Final Tests] required values not displayed when creating an object

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2485]
If there are required values on the object, I cannot select them while creating an object:

![image](https://user-images.githubusercontent.com/3309/30510193-8fa3f796-9abf-11e7-8d78-0f29a47cdc94.png)

![image](https://user-images.githubusercontent.com/3309/30510208-a9ea5bea-9abf-11e7-833b-b62c747ba7fc.png)

**Comment by iglocska** [comment]
This is fixed now.
