### ISSUE TITLE
Can't define Category through Free Import Tool

### ISSUE THREAD

**Issue by debernal** [MISP/MISP#2487]
Hi, 

I am trying to add the category of an attribute through the FreeText Import Tool in MISP v 2.4.79. 
If I provide the following, MISP correctly detects the type (md5) and value and offers me to select the Category.

md5,84c82835a5d21bbcf75a61706d8ab549

However when I provide the Category (Artifacts dropped), by supplying an additional attribute in any of the following ways:

md5,84c82835a5d21bbcf75a61706d8ab549,Artifacts dropped
Artifacts dropped,md5,84c82835a5d21bbcf75a61706d8ab549
md5,Artifacts dropped,84c82835a5d21bbcf75a61706d8ab549

MISP does not detect the category. When I select submit it through the Free Text Import Tool, it maps it to Payload Delivery instead of the desired category (Artifacts dropped).  This is easy to change in the provided drop down list for a single artifact, but inconvenient when adding hundreds. How can I import the category through Freetext Import tool?

Thanks.

**Comment by iglocska** [comment]
I am not sure I understand, the freetext import tool doesn't know context based on what else is on a line.
The way it works is simple, by inputting the following:
```
md5,84c82835a5d21bbcf75a61706d8ab549,Artifacts dropped 
```
The freetext import tool will break that line apart based on separator characters (such as space, comma, period, etc) and end up with an array of parsed phrases:
```
[
 "md5",
 "84c8 2835a5d21bbcf75a61706d8ab549",
 "Artifacts",
 "dropped"
]
```

Out of the above, the freetext import tool will run it's detection algorithm on each parsed phrase and end up with the following results:

```
[
 "md5": false,
 "84c82835a5d21bbcf75a61706d8ab549": {
   "categories": ["Payload delivery", "Artifacts dropped", ...],
   "types": ["md5", "imphash"],
   "to_ids": true,
   ...
 },
 "Artifacts":false,
 "dropped":false
]
```

Out of that it will generate the final form and offer the user a chance to choose between the possible options (such as the 4 categories, 2 types). Whatever is picked there is stored. The lists are populated based on the defaults for the parsed phrase.

Hope this clears it up!
