### ISSUE TITLE
workers not starting, " Issues prevent jobs from being processed. Please resolve them below."

### ISSUE THREAD

**Issue by enkidunolinux** [MISP/MISP#2488]
Hi MISP champions

i have installed few instances of MISP in RHEL7 and all of them have the same issue. the workers are not starting 

![image](https://user-images.githubusercontent.com/31463354/30519752-1be52406-9be1-11e7-8e8f-dbacf8494af1.png)

when I start the through the CLI i get better response

```
su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'
Stopping workers
Stopping 16164 ... Done
Stopping 16219 ... Done
Stopping 16201 ... Done
Stopping 16183 ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
Starting scheduler worker ..................... Fail

```
and when i check the error logs I get only this
```
2017-09-17 09:44:56 Error: [MissingControllerException] Controller class Api:9000Controller could not be found.
Exception Attributes: array (
  'class' => 'Api:9000Controller',
  'plugin' => NULL,
)
Request URL: /api:9000/modules
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
```

any idea whats going wrong?

**Comment by enkidunolinux** [comment]
Hi Guys

any thoughts on this?

**Comment by SparkyNZL** [comment]
I have the same issue, this seems to have occured with over to Ubuntu 17.04 from 16.04LTS has anyone else ?

**Comment by SparkyNZL** [comment]
Weird, mine just SPRUNG to life .... about 2 hours later

**Comment by SparkyNZL** [comment]
OK so mine will not restart unless i reboot the box and then click restart, if i then try and restart them again they will not restart, I have killed all the workers, and when i run start.sh to restart the workers I get the following

-----------------------------------------------------------------------

Stopping workers
Stopping 1883 ... kill: (1883): No such process
Stopping 1901 ... kill: (1901): No such process
Stopping 1864 ... kill: (1864): No such process
Stopping 1919 ... kill: (1919): No such process
Stopping the Scheduler Worker ... kill: (1937): No such process

root@misp:/var/www/MISP/app/Console# ./cake CakeResque.CakeResque stop -vvv --all
Stopping workers
Stopping 1883 ... kill: (1883): No such process
Stopping 1901 ... kill: (1901): No such process
Stopping 1864 ... kill: (1864): No such process
Stopping 1919 ... kill: (1919): No such process
Stopping the Scheduler Worker ... kill: (1937): No such process

root@misp:/var/www/MISP/app/Console# ./cake CakeResque.CakeResque stop -f --all
Stopping workers (force)
Stopping 1883 ... kill: (1883): No such process
Stopping 1901 ... kill: (1901): No such process
Stopping 1864 ... kill: (1864): No such process
Stopping 1919 ... kill: (1919): No such process
Stopping the Scheduler Worker ... kill: (1937): No such process


--------------------------------------------------------------------------------------

There actually are no processes on these PIDs, So I was wondering where MISP is getting these from 

Cheers

**Comment by SparkyNZL** [comment]
Is anyone going to look into this ? This is still on going :(

**Comment by arnydo** [comment]
Still occuring with the latest release? I had a similar issue that was resolved when I updated my MISP.

**Comment by SparkyNZL** [comment]
yeah if i stop them i cant restart them, which means i have to bounce the box to get them to start again :( 




Sent from Pixel 2







On Fri, Oct 20, 2017 at 5:16 PM +1300, "arnydo" <notifications@github.com> wrote:












Still occuring with the latest release? I had a similar issue that was resolved when I updated my MISP.

**Comment by iglocska** [comment]
@SparkyNZL, did you start them with the root user? If so the log files
created in /var/www/MISP/app/tmp/logs are only writeable by the root user
and MISP won't be able to launch workers itself. Make sure you run a "chown
-R www-data:www-data /var/www/MISP/app/tmp/logs" and then try again.

**Comment by SparkyNZL** [comment]
No they arent started as root, they are started as www-data and im still
having the same issue.

**Comment by SparkyNZL** [comment]
all of the logs are owned by www-data, it seems to be an issue when i upgraded to Ubuntu 17.04, so im still trying to track it down, but seems that MISP thinks its starting services on specific PIDS, but when it checks they arent there so makes them as not started, on the other hand, when it trys to also stop these PIDs they also fail as they also dont exist ...

**Comment by SparkyNZL** [comment]
I have finally sorted out this issue ! It looks like when Ubuntu upgrade it did some funcky stuff with Redis, this partitally stuffed redis up, it worked enough to make it look like there was nothing wrong. I removed refdis including the database, and reinstalled it and this solved everything !, Oh, keep a copy of your redis.conf files in the /etc/redis directory, as when you install it, it does not create a new conf file !

Hope this helps someone else out. :)

**Comment by forgettableEgg** [comment]
@SparkyNZL how much did you remove of redis? Do you remember the commands you used? I think I am running into the same issue but after installing redis I got the index.php page whenever i visit my site.

**Comment by torelab** [comment]
I got rid of the issue just by flushing db on redis-cli.

**Comment by SparkyNZL** [comment]
agreed, this also works ! :)

**Comment by dmolina213** [comment]
I am having the same issue. What are the step by step instructions to fix?

I did this:
Questions | Answers
-- | --
Type of issue | Bug, Question,
OS version (server) | Red hat 7
OS version (client) | 10,
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.104hash of the commit
Browser | Chrome


### Expected behavior
Workers started

### Actual behavior
Workers not started

![image](https://user-images.githubusercontent.com/42444130/57406001-659f6c00-71a5-11e9-8e31-6043d652ee37.png)


I run this from the CLI as instructed from the Admin Guide
[root@vansmmispdev ~]# su -s/bin/bash apache
bash-4.2$ /var/www/MISP/app/Console/worker/start.sh 
Stopping workers
Stopping 9234 ... Done
Stopping 9180 ... Done
Stopping 9256 ... Done
Stopping 9212 ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
Scheduler Worker is not enabled

**Comment by SparkyNZL** [comment]
Essentially i found it to be redis, so check to make sure that redis is
operating correctly as your first point of call.

**Comment by dmolina213** [comment]
what do i look for in Redis? Whether if the process is running?

**Comment by SparkyNZL** [comment]
yes, you need to ensure its running and there are no errors so check
var/log for issues.

Cheer.
