### ISSUE TITLE
No logs of REST queries

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#249]
There is no logging of the connections via the REST API in the web interface.

That would be a nice enhancement.

**Comment by SteveClement** [comment]
This is already implemented:

> MISP.log_auth | true | If enabled, MISP will log all successful authentications using API keys. The requested URLs are also logged.

**Comment by iglocska** [comment]
Please use this with care, this is incredibly verbose and not meant to be run 24/7.
