### ISSUE TITLE
API not encrypting attachments with "to_ids" flag

### ISSUE THREAD

**Issue by c-goes** [MISP/MISP#2491]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Win10/PyMISP master branch
| PHP version               | 7.0
| MISP version / git hash   | 2.4.79 MISP Training VM
| Browser                   | n.a.

### Expected behavior

MISP API should encrypt the attachment when "to_ids" flag is set to True on the PyMISP function add_attachment()

### Actual behavior

API does neither encrypt nor calculate hashes

### Steps to reproduce the behavior

```python
from pymisp import PyMISP

url = "http://192.168.56.101/"
key = "..."

misp = PyMISP(url, key, True, 'json', debug=True)

event = misp.new_event(info = "eventINFO")
misp.add_attachment(event, "../a.txt", to_ids=True)
``` 

### Logs, screenshots, configuration dump, ...

MISP Log:

```

176213 | admin@misp.training | MISP | 2017-09-18 18:23:07 | Attribute | 172988 | add | Attribute (172988) from Event (763): Artifacts dropped/attachment a.txt
-- | -- | -- | -- | -- | -- | -- | --


to_ids () => (1), distribution () => (5), deleted () => (0), type () => (attachment), category () => (Artifacts dropped), event_id () => (763), uuid () => (59bff2eb-3b24-4d6e-a72c-05eec0a83865), value1 () => (a.txt) 
```

**Comment by Rafiot** [comment]
The type `attachment` is meant for PDFs of vendors for example.

If you want to add a malware, you need to use this method: https://github.com/MISP/PyMISP/blob/6eb807381dfa3d2a9dd2a42fdd219d6f3cdfd1ff/pymisp/api.py#L726
