### ISSUE TITLE
Current commit hash disappears in Diagnostics page

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#2499]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | OS X
| PHP version               | 7.0
| MISP version / git hash   | 2.4.80, 54df7b9259e4c1157425429b03d3423ebf1cd5cb
| Browser                   | NA

### Expected behavior
Expected to see `2.4.80 (54df7b9259e4c1157425429b03d3423ebf1cd5cb)` in Diagnostics page

### Actual behavior
Only saw `2.4.80 ()`

### Steps to reproduce the behavior
1. Update MISP
2. Navigate to Settings > Diagnostics

### Logs, screenshots, configuration dump, ...
![capture](https://user-images.githubusercontent.com/15183688/30658011-a473a6d2-9df6-11e7-9640-28eaf9337ff4.PNG)

**Comment by iglocska** [comment]
What the hell. Will have a look, that is weird.

**Comment by iglocska** [comment]
Just had a look, sounds like you have a permission issue with /var/www/MISP/.git

Try this:

```
chown -R www-data:www-data /var/www/MISP/.git
```

**Comment by infosec-intern** [comment]
That worked, thanks!
