### ISSUE TITLE
Proposal to set by default "for Intrusion Detection System" and add a  "Source of False-Positive"

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#250]
Hi Guys,

After a small discussion internally on our use of "for Intrusion Detection System" flag when creating an attribute, we have a proposal that could ease analyst work while improving the overall usefulness of the exported attributes.

As you know, Intrusion Detection System are usually a broad term including network intrusion detection systems, local intrusion detection systems or even sometime some A/V products having similar functionalities. Functionalities depend of the technology you use, as example "pattern-in-memory" can now be used by some local intrusion detection system and MD5 hashes can be extracted by network intrusion detection system.

So the flag meaning is different between instances of MISP or even between member of a MISP community. So we propose the following:
- The "for Intrusion Detection System" is assigned by default to all structured attributes can be used for detection (basically every attributes except the ones when a machine cannot parse it e.g. reference to report or alike). So the option is checked by default.
- When there is very common attribute, there is a specific "might generate False-Positives" unchecked by default.

This will ease the work of the analyst while feeding the system (default is for IDS) except if this is generating false-positive. And then the data feed can be easily imported by various IDS.

What do you think? This is just a proposal.

Cheers.

**Comment by elhoim** [comment]
AFAIK, this has been implemented, can I close?

**Comment by adulau** [comment]
The default categories solved partially this old proposal and a new feature for the sighting is also solving this.
