### ISSUE TITLE
Statistics -> Attribute Histogram not working in 2.4.80

### ISSUE THREAD

**Issue by mike1703** [MISP/MISP#2501]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu-16.04
| PHP version               | 7.0
| MISP version / git hash   | 2.4.80

### Expected behavior
See the attribute histogram

### Actual behavior
No histogram is shown, the spinner is spinning forever

### Steps to reproduce the behavior
1) Open the statistics page
2) Click on 'Attribute histogram'

### Logs, screenshots, configuration dump, ...
/var/www/MISP/app/tmp/logs/error.log:

    2017-09-21 16:46:39 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    Request URL: /users/histogram/?_=1506005198804
    Stack Trace:
    #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
    #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Event`....', Array)
    #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Event`....', Array, Array)
    #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Event`....', Array)
    #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Attribute), Array)
    #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
    #6 /var/www/MISP/app/Controller/UsersController.php(964): Model->find('all', Array)
    #7 [internal function]: UsersController->histogram()
    #8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
    #9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
    #10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
    #11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
    #12 {main}

**Comment by adulau** [comment]
Could you test on recent version of MISP? I will close the ticket. Feel free to reopen the ticket if you still have the issue.

**Comment by mike1703** [comment]
works again in at least 2.4.84
