### ISSUE TITLE
MISP Objects GUI issue

### ISSUE THREAD

**Issue by FlorianRupp** [MISP/MISP#2504]
Hello MISP Team,

I tried out the new object feature. Tu fulfill my needs I created a custom object category by adding the JSON structure to the MISP/app/files/misp-objects/objects directory. Everything was fine when I updated the categories in the "List Object Templates" section. After I did some reworks on my custom object I deleted and updated the object templates again. Afterwards I was getting the misbehaviour described below. I also had a look ad the corresponding database tables for any NULL attributes, but there weren't any showy rows. 

I hope you can help me with this issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.4.3
| OS version (client)       | Windows 10
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.80 b526a43
| Browser                   | Firefox 52.2.0

### Expected behavior
Open the Web GUI dialog box for selecting an object category by clicking on the "Add Object" link in an event context.

### Actual behavior
Dialog box is not opened. GUI freezed.

### Steps to reproduce the behavior
see above.

### Logs, screenshots, configuration dump, ...
- JS console output in browser: TypeError: text[0] is undefined  jquery.js%20line%20343%20%3E%20eval:41:7

**Comment by iglocska** [comment]
Hmph that is weird, but a bit difficult to debug. Could you instead of using the JS console look at the response from MISP via the network tab in your dev tools in the browser once you click on add object?

**Comment by FlorianRupp** [comment]
Thank you for your fast answer. This is the answer from the MISP Server. I hope this will help.

<div class="popover_choice">
	<legend>Select Object Category</legend>
	<div class="popover_choice_main" id ="popover_choice_main">
		<table style="width:100%;" id="MainTable">
			<tr style="border-bottom:1px solid black;" class="templateChoiceButton">
				<td role="button" tabindex="0" aria-label="All meta-categories" title="All Objects" style="padding-left:10px;padding-right:10px; text-align:center;width:100%;" onClick="objectChoiceSelect('all');">All Objects</td>
			</tr>
		</table>
	</div>
	<div role="button" tabindex="0" aria-label="Cancel" title="Cancel" class="templateChoiceButton templateChoiceButtonLast" onClick="cancelPopoverForm();">Cancel</div>
</div>
<script type="text/javascript">
	var choice = "categories";
	var eventId = "67";
	var templates = {"all":[{"id":"31","name":null,"description":null,"org_id":"2","org_name":"My Company"},{"id":"34","name":"My-Department","description":"An object containing attributes handling false-positive and false-negative events.","org_id":"2","org_name":"My Company"},{"id":"1","name":"ail-leak","description":"An information leak as defined by the AIL Analysis Information Leak framework.","org_id":"2","org_name":"My Company"},{"id":"2","name":"cookie","description":"An HTTP cookie (web cookie, browser cookie) is a small piece of data that a server sends to the user's web browser. The browser may store it and send it back with the next request to the same server. Typically, it's used to tell if two requests came from the same browser \u2014 keeping a user logged-in, for example. It remembers stateful information for the stateless HTTP protocol. (as defined by the Mozilla foundation.","org_id":"2","org_name":"My Company"},{"id":"35","name":"credit-card","description":"A payment card like credit card, debit card or any similar cards which can be used for financial transactions.","org_id":"2","org_name":"My Company"},{"id":"4","name":"ddos","description":"DDoS object describes a current DDoS activity from a specific or\/and to a specific target. Type of DDoS can be attached to the object as a taxonomy","org_id":"2","org_name":"My Company"},{"id":"5","name":"domain|ip","description":"A domain and IP address seen as a tuple in a specific time frame.","org_id":"2","org_name":"My Company"},{"id":"6","name":"elf","description":"Object describing a Executable and Linkable Format","org_id":"2","org_name":"My Company"},{"id":"7","name":"elf-section","description":"Object describing a section of an Executable and Linkable Format","org_id":"2","org_name":"My Company"},{"id":"8","name":"email","description":"Email object describing an email with meta-information","org_id":"2","org_name":"My Company"},{"id":"9","name":"file","description":"File object describing a file with meta-information","org_id":"2","org_name":"My Company"},{"id":"10","name":"geolocation","description":"An object to describe a geographic location.","org_id":"2","org_name":"My Company"},{"id":"11","name":"http-request","description":"A single HTTP request header","org_id":"2","org_name":"My Company"},{"id":"12","name":"ip|port","description":"An IP address and a port seen as a tuple (or as a triple) in a specific time frame.","org_id":"2","org_name":"My Company"},{"id":"36","name":"ja3","description":"JA3 is a new technique for creating SSL client fingerprints that are easy to produce and can be easily shared for threat intelligence. Fingerprints are composed of Client Hello packet; SSL Version, Accepted Ciphers, List of Extensions, Elliptic Curves, and Elliptic Curve Formats. https:\/\/github.com\/salesforce\/ja3","org_id":"2","org_name":"My Company"},{"id":"13","name":"macho","description":"Object describing a file in Mach-O format.","org_id":"2","org_name":"My Company"},{"id":"14","name":"macho-section","description":"Object describing a section of a file in Mach-O format.","org_id":"2","org_name":"My Company"},{"id":"15","name":"passive-dns","description":"Passive DNS records as expressed in draft-dulaunoy-dnsop-passive-dns-cof-01","org_id":"2","org_name":"My Company"},{"id":"16","name":"pe","description":"Object describing a Portable Executable","org_id":"2","org_name":"My Company"},{"id":"17","name":"pe-section","description":"Object describing a section of a Portable Executable","org_id":"2","org_name":"My Company"},{"id":"18","name":"person","description":"An person which describes a person or an identity.","org_id":"2","org_name":"My Company"},{"id":"19","name":"phone","description":"A phone or mobile phone object which describe a phone.","org_id":"2","org_name":"My Company"},{"id":"20","name":"r2graphity","description":"Indicators extracted from files using radare2 and graphml","org_id":"2","org_name":"My Company"},{"id":"21","name":"regexp","description":"An object describing a regular expression (regex or regexp). The object can be linked via a relationship to other attributes or objects to describe how it can be represented as a regular expression.","org_id":"2","org_name":"My Company"},{"id":"22","name":"registry-key","description":"Registry key object describing a Windows registry key with value and last-modified timestamp","org_id":"2","org_name":"My Company"},{"id":"23","name":"tor-node","description":"Tor node (which protects your privacy on the internet by hiding the connection between users Internet address and the services used by the users) description which are part of the Tor network at a time.","org_id":"2","org_name":"My Company"},{"id":"24","name":"url","description":"url object describes an url along with its normalized field (like extracted using faup parsing library) and its metadata.","org_id":"2","org_name":"My Company"},{"id":"37","name":"victim","description":"Victim object describes the target of an attack or abuse.","org_id":"2","org_name":"My Company"},{"id":"25","name":"vulnerability","description":"Vulnerability object describing common vulnerability enumeration","org_id":"2","org_name":"My Company"},{"id":"38","name":"whois","description":"Whois records information for a domain name.","org_id":"2","org_name":"My Company"},{"id":"27","name":"x509","description":"x509 object describing a X.509 certificate","org_id":"2","org_name":"My Company"},{"id":"28","name":"yabin","description":"yabin.py generates Yara rules from function prologs, for matching and hunting binaries. ref: https:\/\/github.com\/AlienVault-OTX\/yabin","org_id":"2","org_name":"My Company"}],"misc":[{"id":"1","name":"ail-leak","description":"An information leak as defined by the AIL Analysis Information Leak framework.","org_id":"2","org_name":"My Company"},{"id":"10","name":"geolocation","description":"An object to describe a geographic location.","org_id":"2","org_name":"My Company"},{"id":"18","name":"person","description":"An person which describes a person or an identity.","org_id":"2","org_name":"My Company"},{"id":"19","name":"phone","description":"A phone or mobile phone object which describe a phone.","org_id":"2","org_name":"My Company"},{"id":"21","name":"regexp","description":"An object describing a regular expression (regex or regexp). The object can be linked via a relationship to other attributes or objects to describe how it can be represented as a regular expression.","org_id":"2","org_name":"My Company"},{"id":"23","name":"tor-node","description":"Tor node (which protects your privacy on the internet by hiding the connection between users Internet address and the services used by the users) description which are part of the Tor network at a time.","org_id":"2","org_name":"My Company"},{"id":"37","name":"victim","description":"Victim object describes the target of an attack or abuse.","org_id":"2","org_name":"My Company"}],"network":[{"id":"2","name":"cookie","description":"An HTTP cookie (web cookie, browser cookie) is a small piece of data that a server sends to the user's web browser. The browser may store it and send it back with the next request to the same server. Typically, it's used to tell if two requests came from the same browser \u2014 keeping a user logged-in, for example. It remembers stateful information for the stateless HTTP protocol. (as defined by the Mozilla foundation.","org_id":"2","org_name":"My Company"},{"id":"4","name":"ddos","description":"DDoS object describes a current DDoS activity from a specific or\/and to a specific target. Type of DDoS can be attached to the object as a taxonomy","org_id":"2","org_name":"My Company"},{"id":"5","name":"domain|ip","description":"A domain and IP address seen as a tuple in a specific time frame.","org_id":"2","org_name":"My Company"},{"id":"8","name":"email","description":"Email object describing an email with meta-information","org_id":"2","org_name":"My Company"},{"id":"11","name":"http-request","description":"A single HTTP request header","org_id":"2","org_name":"My Company"},{"id":"12","name":"ip|port","description":"An IP address and a port seen as a tuple (or as a triple) in a specific time frame.","org_id":"2","org_name":"My Company"},{"id":"36","name":"ja3","description":"JA3 is a new technique for creating SSL client fingerprints that are easy to produce and can be easily shared for threat intelligence. Fingerprints are composed of Client Hello packet; SSL Version, Accepted Ciphers, List of Extensions, Elliptic Curves, and Elliptic Curve Formats. https:\/\/github.com\/salesforce\/ja3","org_id":"2","org_name":"My Company"},{"id":"15","name":"passive-dns","description":"Passive DNS records as expressed in draft-dulaunoy-dnsop-passive-dns-cof-01","org_id":"2","org_name":"My Company"},{"id":"24","name":"url","description":"url object describes an url along with its normalized field (like extracted using faup parsing library) and its metadata.","org_id":"2","org_name":"My Company"},{"id":"25","name":"vulnerability","description":"Vulnerability object describing common vulnerability enumeration","org_id":"2","org_name":"My Company"},{"id":"38","name":"whois","description":"Whois records information for a domain name.","org_id":"2","org_name":"My Company"},{"id":"27","name":"x509","description":"x509 object describing a X.509 certificate","org_id":"2","org_name":"My Company"}],"file":[{"id":"34","name":"My-Department","description":"An object containing attributes handling false-positive and false-negative events.","org_id":"2","org_name":"My Company"},{"id":"6","name":"elf","description":"Object describing a Executable and Linkable Format","org_id":"2","org_name":"My Company"},{"id":"7","name":"elf-section","description":"Object describing a section of an Executable and Linkable Format","org_id":"2","org_name":"My Company"},{"id":"9","name":"file","description":"File object describing a file with meta-information","org_id":"2","org_name":"My Company"},{"id":"13","name":"macho","description":"Object describing a file in Mach-O format.","org_id":"2","org_name":"My Company"},{"id":"14","name":"macho-section","description":"Object describing a section of a file in Mach-O format.","org_id":"2","org_name":"My Company"},{"id":"16","name":"pe","description":"Object describing a Portable Executable","org_id":"2","org_name":"My Company"},{"id":"17","name":"pe-section","description":"Object describing a section of a Portable Executable","org_id":"2","org_name":"My Company"},{"id":"20","name":"r2graphity","description":"Indicators extracted from files using radare2 and graphml","org_id":"2","org_name":"My Company"},{"id":"22","name":"registry-key","description":"Registry key object describing a Windows registry key with value and last-modified timestamp","org_id":"2","org_name":"My Company"},{"id":"28","name":"yabin","description":"yabin.py generates Yara rules from function prologs, for matching and hunting binaries. ref: https:\/\/github.com\/AlienVault-OTX\/yabin","org_id":"2","org_name":"My Company"}],"":[{"id":"31","name":null,"description":null,"org_id":"2","org_name":"My Company"}],"financial":[{"id":"35","name":"credit-card","description":"A payment card like credit card, debit card or any similar cards which can be used for financial transactions.","org_id":"2","org_name":"My Company"}]};
	var template_categories = ["all","misc","network","file","","financial"];
	$(document).ready(function() {
		resizePopoverBody();
		populateObjectChoiceList(choice);
	});

	$(window).resize(function() {
		resizePopoverBody();
	});

	function populateObjectChoiceList(choice) {
		$("#MainTable").empty();
		if (choice == "categories") {
			template_categories.forEach(function(category) {
				$("#MainTable").append(createObjectChoiceRowCategories(category));
			});
		} else {
			templates[choice].forEach(function(element) {
				$("#MainTable").append(createObjectChoiceRow(eventId, element));
			});
			$("#MainTable").append(createObjectChoiceRowCategories('categories'));
		}
	}

	function createObjectChoiceRow(eventId, data) {
		var html = '<tr style="border-bottom:1px solid black;" class="templateChoiceButton">';
		var html = html + '<td role="button" tabindex="0" aria-label="' + data["description"] + '" title="' + data["description"] + '" style="padding-left:10px;padding-right:10px; text-align:center;width:100%;" onClick="window.location=\'/objects/add/' + eventId + '/' + data["id"] + '\';">' + data["name"].charAt(0).toUpperCase() + data["name"].slice(1) + '</td>';
		var html = html + '</tr>';
		return html;
	}

	function createObjectChoiceRowCategories(data) {
		var text = data;
		if (text == 'categories') {
			text = 'Back to categories';
		}
		var html = '<tr style="border-bottom:1px solid black;" class="templateChoiceButton">';
		var html = html + '<td role="button" tabindex="0" aria-label="' + (text[0].toUpperCase() + text.slice(1)) + '" title="' + (text[0].toUpperCase() + text.slice(1)) + '" style="padding-left:10px;padding-right:10px; text-align:center;width:100%;" onClick="populateObjectChoiceList(\'' + data + '\');">' + (text[0].toUpperCase() + text.slice(1)) + '</td>';
		var html = html + '</tr>';
		return html;
	}
</script>

**Comment by iglocska** [comment]
What was the name of your object template?

**Comment by FlorianRupp** [comment]
Name is: My-Department
ID: 34

**Comment by iglocska** [comment]
Hmmm that is weird. Trying to figure out why it pops up twice. It should be unique - when you created the new version of the template, did you keep the UUID and increment the version number?

**Comment by FlorianRupp** [comment]
Yes I think I did so. That might let it crash now. How would you approach to solve this? Would it be the best to delete the concerning rows out of the database?

**Comment by iglocska** [comment]
well it shouldn't work that way but it also shouldn't crash it ;) So I'll try to fix the issue - it should simply only offer you both options then instead of puking. 

Meaning the correct way to update it should be to keep the uuid, raise the version number - however not doing so shouldn't crash it.

**Comment by FlorianRupp** [comment]
yeah that's right. Thank you very much, keep on with the great work :)

**Comment by adulau** [comment]
@FlorianRupp Did you test with recent version of MISP? Feel free to reopen the issue if the issue is still there. Thank you very much!

**Comment by FlorianRupp** [comment]
I did not test it on any version > 2.4.80 as I could resolve this inconvenience by manually deleting a complete NULL row from the database. Now I always increase the version number. I don't know if this issue is in any newer version.
