### ISSUE TITLE
IP|Port in Gui

### ISSUE THREAD

**Issue by randomname13** [MISP/MISP#2505]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 14.04/16.04
| OS version (client)       | All
| PHP version               | 5.5, 7.0
| MISP version / git hash   | 2.4.80 / 501206ac7e337bded4a3810616e53803491f6cfd
| Browser                   | All

### Expected behavior
Displaying IP|Port => 111.2.3.4|111

### Actual behavior
Displaying IP|Port wrong =>  :1.2.3.4|111

**Comment by adulau** [comment]
We can reproduce it on the attribute level. The object ip-port doesn't have the bug.

**Comment by cocaman** [comment]
Might be a larger issue, same can be observed with filename|sha256 on an instance.

**Comment by iglocska** [comment]
Interesting, guess my view rework messed a few things up. Will fix it today still.

**Comment by iglocska** [comment]
Should be fixed now, filename|sha256 looks fine for me though. @cocaman, could you post a picture of the issue?

**Comment by cocaman** [comment]
@iglocska sure, here you go

![screen shot 2017-09-25 at 15 52 44](https://user-images.githubusercontent.com/59089/30811842-9e38c43e-a209-11e7-8576-d0f62ba4aa05.png)
![screen shot 2017-09-25 at 15 53 15](https://user-images.githubusercontent.com/59089/30811866-abce97e0-a209-11e7-9190-6ec653c8f133.png)

`putty.exe|81de431987304676134138705fc1c21188ad7f27edf6b77a6551aa693194485e`

**Comment by cocaman** [comment]
Same for md5
![screen shot 2017-09-25 at 16 05 13](https://user-images.githubusercontent.com/59089/30812552-569585d4-a20b-11e7-8fe0-f6f2b9b381b1.png)

![screen shot 2017-09-25 at 16 05 27](https://user-images.githubusercontent.com/59089/30812561-5ef52af4-a20b-11e7-9c79-6c753f4a4308.png)

![screen shot 2017-09-25 at 16 06 11](https://user-images.githubusercontent.com/59089/30812598-7a447e9a-a20b-11e7-8d77-4bacc5d511ab.png)

check the <br> before the filename, maybe that helps

**Comment by iglocska** [comment]
Oh I see. What the hell! On it.

**Comment by iglocska** [comment]
Has been fixed for a while now.
