### ISSUE TITLE
Automatic feeds download

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2511]
Is there a way to download feeds automatically from a subscribed feed into my MISP instance, instead of going to Sync Actions and downloading manually all the time.

**Comment by ater49** [comment]
Yes, since version 2.4.80, you can use a "Scheduled Tasks" named "pull_feeds". Refreshing interval feeds by feeds are not implemented at this time. You can do it with a script and the REST API.

**Comment by iglocska** [comment]
yeah what @ater49 said. I'd recommend REST API is the cleanest.

```
mymisp/feeds/fetchFromFeed/[id]
```

**Comment by ater49** [comment]
cURL syntax: curl --header "Authorization: XXXXXXXXXXXXXXXX" --header "Accept: application/json" --header "C-type: application/json" https://[MISP-URL]/feeds/fetchFromFeed/[Feed-ID]

**Comment by ndhambi** [comment]
Thanks guys , but does it not mean that i need to know the event ID in order to use the REST API , referring back to what @iglocska said "mymisp/feeds/fetchFromFeed/[**id**]" . What i am tying to achieve is that if i am subscribed to feed/community  "SpyTracker", whenever "SpyTracker" adds a new event I want this new update/event to also be added to my MISP instance. In other ways i want to always be updated with the new events logged by the communities i am subscribed to

**Comment by iglocska** [comment]
You need the feed ID, not the event ID ;)
