### ISSUE TITLE
Adding Object Reference not working

### ISSUE THREAD

**Issue by imereau** [MISP/MISP#2512]
Dear MISP team,

I recently deployed version 2.4.80. I was looking forward to the Objects relationships.
Triyng to add references to Objects doesn't seem to work on my instance. See below behaviour.

thanks a lot for the support!

BR's
Irving

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)   |    ubuntu
| OS version (client)      | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.80X, 1154b55e27af53afd9c1f5febdeb8bb021754f83
| Browser                   | IE11

### Expected behavior
Add Object Reference pop-up window:
I would expect the reference to be created
I would expect Target details to be filled in the pop-up window when inputing the UUID. 
Also, is it the idea to link only one single attribute of the object? Is it not possible to link objects themselves?

### Actual behavior
Add Object Reference pop-up window:

1. Upon clicking the submit button, the "loading wheel" keeps on turning and objects references are not added. there are no error messages in the log files
2. Upon inserting the UUID of the target attribute, I would also expect Target details to be filled on the Add Object references pop-up. 
3. Also, is it the idea to link only one single attribute of the object? Is it not possible to link objects themselves?

### Steps to reproduce the behavior
- Navigate to Event view
- Create an object by importing a file e.g.
- Click "+" References from the view event screen, on the newly created object
- Choose relationship type
- Put comment
- input Target UUID (any UUID fetched from another existing attribute for testing purposes)
- Click Submit**

### Logs, screenshots, configuration dump, ...
nothing logged as error message
![image](https://user-images.githubusercontent.com/8105737/30864841-26fbb13e-a2d5-11e7-8883-213dd1f7a530.png)

**Comment by iglocska** [comment]
Could you check which commit you are on? You should be able to see it in
administration -> server settings -> diagnostics.

Also, please git pull to the latest commit!

**Comment by iglocska** [comment]
My bad, I didn't see it. Checking if I can reproduce it!

**Comment by iglocska** [comment]
Could you also try to git submodule update?

```
git submodule init
git submodule update
```

**Comment by imereau** [comment]
Hi actually did that alraedy, applied the below update procedure:

# Option 1: To update to the latest commit from the 2.4 branch simply pull the latest commit
cd /var/www/MISP
git pull origin 2.4
git submodule update --init --force

**Comment by iglocska** [comment]
Could you check the following things?

1. Dev console output (f12 -> console)
2. Response from MISP (f12 -> network)
3. Error log entry after a failed request in /var/www/MISP/app/tmp/logs/error.log

**Comment by imereau** [comment]
I did already, unfortunately, it's like nothing happens. I see nothing in the console output and nothing in the error.log when I input the UUI or click the submit button.. weird..
I do not have direct access to the machine right now, but I'll reproduce and provide you with the log file and screenshot of the console as soon as I have my hands on

**Comment by imereau** [comment]
![snagit1](https://user-images.githubusercontent.com/8105737/30903836-6a09dbea-a370-11e7-82e3-9260e09afce8.png)
Hi again,

Please find some more info in the screenshots attached. It looks like the POST to /objectsReferences/add/1 returns a HTTP 404
![image001](https://user-images.githubusercontent.com/8105737/30903819-617eb888-a370-11e7-8c3f-3f5f6f71bebf.jpg)

**Comment by iglocska** [comment]
Anything popping up in your error.log right after?

**Comment by imereau** [comment]
nope, nothing at all in the error.log

**Comment by imereau** [comment]
Log files don't get updated when the error happens.
Here's what I see in the response:

       <h2>Invalid target.</h2>
       <p class="error">
              <strong>Error: </strong>
              The requested address <strong>'/objectReferences/add/1'</strong> was not found on this server.       </p>

**Comment by imereau** [comment]
And it appears the problem isn't there in FF 47.0.1; I guess it's IE related.

**Comment by infosec-intern** [comment]
I've been getting the same error in Chrome and Edge lately. Still trying to figure out the exact cause
My MISP:  v2.4.81 (501206ac7e337bded4a3810616e53803491f6cfd)

**Update**: It looks like new object references aren't getting generated. I only have one event from ~1 month ago that has its references. Any new ones aren't getting added. Checking to see if it's a permissions issue on my end

**Comment by infosec-intern** [comment]
Follow-up on my end. I could never figure out a root cause for this, but it looks like the v2.4.82 update fixed my issue

**Comment by iglocska** [comment]
Great, must have been some bug that we caught (perhaps by accident ;))
