### ISSUE TITLE
MISP Interface Blank, Unable to Login

### ISSUE THREAD

**Issue by RCPMAD** [MISP/MISP#2516]
We've had to stop and start one of our MISP instance to move it to a different hypervisor.

Apache starts and Cake workers start without any issues however whenever I try to access the interface I get a blank white screen. I can even see the SSL certificate.

I believe there is something wrong with Apache but I cannot seem to put my finger on it.

Any takers on this?

**Comment by RCPMAD** [comment]
This is a snippet from misp.local_error.log.

`[Thu Sep 28 09:15:05.681201 2017] [ssl:warn] [pid 8219] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:15:05.710160 2017] [ssl:warn] [pid 8219] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:17:52.042462 2017] [ssl:warn] [pid 8246] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:17:52.068661 2017] [ssl:warn] [pid 8246] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:18:20.643394 2017] [ssl:warn] [pid 8265] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:18:20.670405 2017] [ssl:warn] [pid 8265] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:19:54.926431 2017] [ssl:warn] [pid 8305] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name
[Thu Sep 28 09:19:54.952143 2017] [ssl:warn] [pid 8305] AH01909: RSA certificate configured for misp.local:443 does NOT include an ID which matches the server name`

Above shows whenever I try to access the interface.

**Comment by adulau** [comment]
Reading the logs, it seems your Apache configuration is incorrect and missing the matching server name with the X509 certificate.

**Comment by RCPMAD** [comment]
I've checked that and it seems to not be the case. Certificate has the right name as the server and as the misp configuration.

**Comment by adulau** [comment]
Did you restart Apache?

**Comment by RCPMAD** [comment]
Yes

**Comment by thirdeyeintelligence** [comment]
I am having the same issue

**Comment by adulau** [comment]
It's just a CN mismatch. An approach for debugging is to extract the CN from the X.509 certificate (assuming the certifcate is called server-certificate.crt):

`openssl x509 -in server-certificate.crt -noout -subject`

and then use the returned value in the ServerName directive used for the TLS configuration.

**Comment by ankitdhere** [comment]
I am having the same issue
