### ISSUE TITLE
Mysql Database Issues

### ISSUE THREAD

**Issue by chunderstruck** [MISP/MISP#252]
I've been able to verify that I can connect to the MySql Database with the provided creds but I keep running into an issue where it looks like Misp/Cake is not connecting to the database.

Anyone have any ideas what could be causing these issues.

Missing Database Connection
Database connection "Mysql" is missing, or could not be created.
Error: An Internal Error Has Occurred.

Stack Trace

APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php line 105 → DboSource->__construct(array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3476 → ConnectionManager::getDataSource(string)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1126 → Model->setDataSource(string)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3498 → Model->setSource(string)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 2902 → Model->getDataSource()
APP/Lib/cakephp/lib/Cake/Model/Model.php line 2874 → Model->_readDataSource(string, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/Session/DatabaseSession.php line 94 → Model->find(string, array)
[internal function] → DatabaseSession->read(string)
APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php line 628 → session_start()
APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php line 197 → CakeSession::_startSession()
APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php line 224 → CakeSession::start()
APP/Lib/cakephp/lib/Cake/Controller/Component/SessionComponent.php line 95 → CakeSession::check(string)
APP/Controller/AppController.php line 102 → SessionComponent->check(string)
APP/Controller/EventsController.php line 36 → AppController->beforeFilter()
[internal function] → EventsController->beforeFilter(CakeEvent)
APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 247 → call_user_func(array, CakeEvent)
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 674 → CakeEventManager->dispatch(CakeEvent)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 182 → Controller->startupProcess()
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 160 → Dispatcher->_invoke(EventsController, CakeRequest, CakeResponse)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by yehias** [comment]
still not working with me and same issue debian jessie

**Comment by adulau** [comment]
Could you verify that you have the php5 MySQL module in your installation?

~~~~
dpkg -l | grep php5-mysql
~~~~

Thanks.

**Comment by yehias** [comment]
Yes I have php5-mysql and mysql module for php5 and this drive to the crazy
I dropped dB and create it more than a once and nothing working still same
issue
