### ISSUE TITLE
RHEL 7.4 minimal - 503 Service Unavailable when accessing Diagnostic page

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#2521]
I've just installed MISP on a RHEL 7.4 minimal install using the CentOS 7 instructions provided with the download, making changes where relevant to RHEL.

I've gone through the 'Settings' tab and corrected everything that was Red. 
When clicking on the 'Diagnostic' tab, the browser will think about things for a while and then give the 503 service unavailable.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat Enterprise Linux 7.4 - 3.10.0-693.2.2.el7.x86_64
| OS version (client)       | Windows 7 Enterprise
| PHP version               | rh-php5.6-scl
| MISP version / git hash   | 2.4.80,
| Browser                   | Firefox 52.3.0 ESR

### Expected behavior

Results of the diagnostic tests

### Actual behavior

503 Service Unavailable error

### Steps to reproduce the behavior

{MISP}/Administration/Server Settings/Diagnostics

### Logs, screenshots, configuration dump, ...

Could not find any errors in the logs.
![503 service unavailable - mozilla firefox_2017-09-29_10-52-07](https://user-images.githubusercontent.com/1779665/30996450-5082494c-a504-11e7-941a-68a21370e1f1.png)

**Comment by SHSauler** [comment]
Did you check the MISP-specific logs under `{MISP}/app/tmp/logs` as well?

**Comment by jezkerwin** [comment]
Yeah, I've 'tail -f' the logs when clicking the diagnostics tab, nothing gets recorded.

I did noticed this error:
==> resque-scheduler-error.log <==
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/rh-php56/root/usr/lib64/php/modules/redis.so' - /opt/rh/rh-php56/root/usr/lib64/php/modules/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0

But the file does exist

 ls /opt/rh/rh-php56/root/usr/lib64/php/modules/redis.so
/opt/rh/rh-php56/root/usr/lib64/php/modules/redis.so

**Comment by jezkerwin** [comment]
I found the following error in the logs.

[Fri Oct 27 12:10:03.383791 2017] [proxy_fcgi:error] [pid 1635] (70007)The timeout specified has expired: [client 192.168.72.1:49493] AH01075: Error dispatching request to :, referer: http://<FQDN>/servers/serverSettings

**Comment by jezkerwin** [comment]
I'm going to close this issue, as I think the issue is relating to my MISP server not having access to the Internet, so it fails when checking Github for updates.
