### ISSUE TITLE
Bug: MISP-Export doesn't escape ampersands resulting in invalid XML

### ISSUE THREAD

**Issue by x0phspecial** [MISP/MISP#2522]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 8.9
| OS version (client)       | Ubuntu 
| PHP version               | 5.6.30
| MISP version / git hash   | 2.4.80
| Browser                   | curl, firefox

### Expected behavior
The API-Export should escape every instance of `&` as `&amp;`

### Actual behavior
`<info>Test for a Bug in MISP XML export:  & test</info>`

### Steps to reproduce the behavior
1) Create event with an info containing `&` 
2) Export it via API
`curl -k -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: $MISP_API_key" "https://$MISP_server/events/xml/download/$event_id" > "$event_id.xml"
`
-> This results in an invalid XML with an unescaped ampersand.
MISP doesn't except this broken XML file. To see this:
3) Import this XML file via "Import From MISP Export" in the MISP GUI. You'll see:
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
```

### Logs, screenshots, configuration dump, ...
Content of "$event_id.xml"
```
<Event><id>10359</id><orgc_id>342</orgc_id><org_id>342</org_id><date>2017-09-29</date><threat_level_id>3</threat_level_id><info>Test for a Bug in MISP XML export:  & test</info><published>0</published><uuid>59ce0b15-4384-43a4-80f8-2bd30a2b115a</uuid><analysis>0</analysis><timestamp>1506675477</timestamp><distribution>0</distribution><publish_timestamp>0</publish_timestamp><sharing_group_id>0</sharing_group_id><disable_correlation>0</disable_correlation><event_creator_email>xxxxx@yyyyy.zz</event_creator_email><Org><id>342</id><name>XXXXX</name><uuid>5847f7ce-6884-44a1-9fe1-3d210a2b115a</uuid></Org><Orgc><id>342</id><name>XXXXX</name><uuid>5847f7ce-6884-44a1-9fe1-3d210a2b115a</uuid></Orgc><Attribute/><Object/><ShadowAttribute/><RelatedEvent/></Event>
</response>
```

**Comment by x0phspecial** [comment]
That was quick! Thanks guys! :-)

**Comment by iglocska** [comment]
Thanks a lot for the heads-up! :)
