### ISSUE TITLE
OTX- MISP integration 

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2526]
I have been trying to intergrate MISP and OTX so i can import Alienvault OTX pulses to a MISP instance. The documentation that i got does not explain in detail on how you do this ( https://otx-misp.readthedocs.io/ ). Are there any other resources that maybe explain the steps in detail.

**Comment by adulau** [comment]
We don't maintain this software nevertheless the usage of `otx-misp` is described in the documentation:

https://otx-misp.readthedocs.io/en/latest/usage.html

~~~~
usage: otx-misp [-h] [-o OTX] [-s SERVER] [-m MISP] [-t TIMESTAMP] [-c CONFIG]
                    [-w] [-a] [-u] [-n] [-d] [-v] [--no-tlp] [--discover-tags]
                    [--to-ids] [--distribution DISTRIBUTION]
                    [--threat-level THREAT_LEVEL] [--analysis ANALYSIS]
                    [--author-tag] [--bulk-tag BULK_TAG] [--dedup-titles]
                    [--stop-on-error]
~~~~

If you carefully Read The Fair Manual, you might find all your need to feed data from OTX to MISP ;-)
