### ISSUE TITLE
Populating new user with CertAuth from userDefaults fields broken

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2538]
We create MISP users on the fly using the CertAuth plugin. We use userDefaults to populate the fields and not the more popular restApi method. Since the [security fix](https://github.com/MISP/MISP/commit/be111a470204a974c50682054c9c7d4b94396ed9 ) this no longer works because getRestUser() is not allowed to return NULL anymore.

**Comment by iglocska** [comment]
Argh. Any chance you could do a PR? The problem is that I'd have to fix it blindly...
