### ISSUE TITLE
Unable to delete feed via GUI

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2542]
The latest, greatest MISP version (2.4.80 with a fresh git pull) doesn't delete feeds but appends them at the end of the feed list.

E.g., I was trying to delete both the openbl and the trustedsec feeds:

![bildschirmfoto_2017-10-05_14-00-46](https://user-images.githubusercontent.com/25325656/31226349-18eab3d0-a9d6-11e7-83e9-39d3edaf2668.png)

**Comment by iglocska** [comment]
It deletes them, but the index re-creates all default feeds by default  -
however they come back disabled.

**Comment by StefanKelm** [comment]
Ah, understood...

**Comment by packet-rat** [comment]
Is there a clean way yet to delete Feeds?  Adding them back disabled cause the Feed list to remain multiple pages.  Every time you do any operation the Feed List resets to default Sort/View,  this is a REAL PAIN when you are trying to work on Feed Lists, especially if the feeds your trying to work on are on the 2nd page of Feed Lists.

Another big issue is reappearance of default Feeds after you've renamed them.  We have to rename the "This is a realllllllly long description of what this feed does or did or will do, unlike the other feed that does nothing..." as the full text of Feed name is added to EVERY SINGLE ATTRIBUTE in the Correlations Table.  So we rename them to short names (e.g. DGA Domains).

**Comment by github-germ** [comment]
This is somewhat related to https://github.com/MISP/MISP/issues/5374 as if we change a feed URL from `http` to `https` b/c our firewall only allows https, then will that setting "stick"?
