### ISSUE TITLE
Multiple issues wrt objects

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2543]
Using the latest, greatest MISP version (2.4.80 with a fresh git pull) I've added an object containing md5 and other attributes:

![bildschirmfoto_2017-10-05_14-10-05](https://user-images.githubusercontent.com/25325656/31226709-6680cb1a-a9d7-11e7-9564-d7c36ca80f06.png)

However, searching for that md5 (or other attributes from within the object) gives 0 results:

![bildschirmfoto_2017-10-05_14-10-32](https://user-images.githubusercontent.com/25325656/31226715-6b35b1fc-a9d7-11e7-9a56-b9002bad21dc.png)

**Comment by iglocska** [comment]
Ha interesting. So the search only searches outside of the object level?

**Comment by StefanKelm** [comment]
Yes, searching for "plain" attributes (outside the object) works as expected

**Comment by StefanKelm** [comment]
This may be related - in the home screen it says that that particular event has 25 attributes (which is correct):

![bildschirmfoto_2017-10-05_14-27-29](https://user-images.githubusercontent.com/25325656/31227301-a18a24ac-a9d9-11e7-9f0c-622c5d1a5837.png)

while within the event only the attributes outside any objects are being counted:

![bildschirmfoto_2017-10-05_14-27-57](https://user-images.githubusercontent.com/25325656/31227320-b7d0a9d4-a9d9-11e7-8403-05e2772280d9.png)

**Comment by StefanKelm** [comment]
Also, trying to edit an attribute within an object by double-clicking on the value (such as md5) only shows the rotating "Loading" icon:

![bildschirmfoto_2017-10-05_16-02-06](https://user-images.githubusercontent.com/25325656/31231248-982e1974-a9e6-11e7-9c20-d36c3a45fc33.png)

UPDATE (Dec. 07): this now works (2.4.84).

**Comment by StefanKelm** [comment]
MISP v2.4.81 (have not been able to test against a more recent version) sends out empty mails when events contain objects (well, not completely empty but an empty message which is signed and encrypted)

UPDATE (Dec. 05): when we tell MISP to send events **unencrypted** those mails look fine...

**Comment by StefanKelm** [comment]
Importing an event containing objects (created on another 2.4.81 instance) fails w/o reason.
![1](https://user-images.githubusercontent.com/25325656/32447108-57e02e0a-c30b-11e7-89a9-8d02e34d73fb.png)
The event is attached:

[misp.event.7108.59d5f620-12d4-45d3-bec7-26bcc25ed030.json.txt](https://github.com/MISP/MISP/files/1446611/misp.event.7108.59d5f620-12d4-45d3-bec7-26bcc25ed030.json.txt)

UPDATE (Dec. 07): this now works (2.4.84).

**Comment by StefanKelm** [comment]
Trying to query or add an enrichment on an attribute within an object doesn't do anything except very briefly displaying _"Could not fetch the given PGP key."_ at the bottom of the event page.

UPDATE (Jan. 08): _error.log_ contains

```
2018-01-08 14:31:34 Error: [MethodNotAllowedException] Attribute not found or you are not authorised to see it.
Request URL: /events/queryEnrichment/1416334/ShadowAttribute?_=1515421887491
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment('1416334', 'ShadowAttribute')
#1 /services/inst/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /services/inst/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by StefanKelm** [comment]
When syncing events containing objects between two (2.4.82) instances only the "plain" attributes are being synced on pull, not the objects, e.g.:

source MISP:

![source](https://user-images.githubusercontent.com/25325656/33717992-38684d8c-db5c-11e7-96b8-db583e301116.png)

dest MISP:

![dest](https://user-images.githubusercontent.com/25325656/33718008-3fd22bb0-db5c-11e7-95e4-4e4e5cc8d3fc.png)

**Comment by iglocska** [comment]
What the hell. Testing.

**Comment by iglocska** [comment]
Hmm, works for me on 2.4.84 :|

**Comment by StefanKelm** [comment]
Have made a few updates to the comments above. Some things now work, other issues are still there.

**Comment by adulau** [comment]
@StefanKelm Thank you. Could you tell us the remaining issue after 2.4.86 upgrade? I'll close the issue but feel free to reopen if there are open issues.

**Comment by StefanKelm** [comment]
Just did a fresh git pull but these issues still remain:

https://github.com/MISP/MISP/issues/2543#issue-263103187
https://github.com/MISP/MISP/issues/2543#issuecomment-334450476
https://github.com/MISP/MISP/issues/2543#issuecomment-349341037

However, can this be related to some other system component such as Apache?

PS: @adulau I'm still too stupid to re-open issues... #
