### ISSUE TITLE
Listing tags generates max_allowed_packet error

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#2544]
I have set max_allowed_packet everywhere I can figure out to be 256M on the server too, but it never seems to "take" in the actual running config.

From error.log in MISP:

2017-10-05 14:13:04 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /tags
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(671): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1120): DboSource->fetchAll('SELECT `Event`....', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Controller/TagsController.php(90): Model->find('all', Array)
#7 [internal function]: TagsController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2017-10-05 14:13:04 Warning: Warning (2): Error while sending QUERY packet. PID=80500 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468]
Trace:
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 434
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 671
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1120
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
AppModel::__runCleanDB() - APP/Model/AppModel.php, line 1050
AppModel::runUpdates() - APP/Model/AppModel.php, line 1009
AppController::beforeFilter() - APP/Controller/AppController.php, line 253
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.80, latest
| Browser                   | All

**Comment by iglocska** [comment]
Yeah keep forgetting about this. It's a shitty series of SQL calls that's purely down to some short-sighted decisions back then. Will try to fix this one soon as it's embarrassing.

**Comment by bambenek** [comment]
No worries. We all have code we're embarrassed by :)

--
John Bambenek

**Comment by iglocska** [comment]
As long as you don't look at the OpenIOC import I'm happy.

**Comment by bambenek** [comment]
Any update on this?

**Comment by iglocska** [comment]
Should be fixed will do a release tonight still (the fix is already on the 2.4 branch).

**Comment by adulau** [comment]
@bambenek Is this one solved?

**Comment by bambenek** [comment]
Yes

--
John Bambenek
