### ISSUE TITLE
Problem of Duplicating feeds (events)

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2549]
Every time i fetch events from a feed it also results in fetching old events  that have already been added to MISP. This causes multiple duplicate of events on the MISP instance and results in flooding of notifications of emails with old events.

Is there a way to fetch new events only and ignore the old one that have already been added into MISP?

**Comment by ndhambi** [comment]
Is there anyone to help with this?

**Comment by adulau** [comment]
The `delta-merge` is doing that along with a fixed event. This is part of the feed configuration. Feel free to reopen if this is not solving your issue.

**Comment by ndhambi** [comment]
Thanks @adulau , but how about  Feeds like the CIRCL OSINT Feed which does not have the "delta-merge " and fixed event option.?

**Comment by adulau** [comment]
It's in MISP format. This doesn't apply as the MISP events are unique ;-)

PS: Will you join us for the training in Prague?

**Comment by ndhambi** [comment]
Thanks, I wont be joining the training  because i'm on the different side of the world (continent)
