### ISSUE TITLE
Feed Pull Scheduling

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#2550]
I'm sure this is an id10T error on my behalf, but I can't seem to get the feeds to pull at timed intervals. 

Is this not possible?

Jimbo

**Comment by jimbolya0607** [comment]
anyone...anyone?
=)

**Comment by adulau** [comment]
There is indeed a bug in the feed scheduling, in the mean time, you can feed pull using curl in a crontab:

https://www.circl.lu/doc/misp/automation/#enable-disable-and-fetching-feeds-via-the-api

**Comment by jimbolya0607** [comment]
So the command would look like this after installing cron?

5 * * * * curl https://malware.kittyhawk-msp.com/feeds/cacheFeeds/all

I'm assuming this command would run an 'all' enabled feed pull every five mintues?

Jimbo

**Comment by iglocska** [comment]
Correct. That is the caching not the pulling though, depends what you are
after.

**Comment by jimbolya0607** [comment]
@iglocska i'm trying to run a feed(s) pull on a timer, much like the scheduled tasks for instances.  

i'm guessing the command would look like this if i didn't want to cache the data?

5 * * * * curl https://malware.kittyhawk-msp.com/feeds/all

The above would run all enabled feeds every five minutes?

Jimbo

**Comment by jimbolya0607** [comment]
so i changed the statement to the following:

1 * * * * curl https://malware.kittyhawk-msp.com/feeds/fetchFromFeed/40

technically, by the way the feed is set up i should get a new event every time it's run...

however, nothing is happening...

my guess is that i have the wrong curl statement. 

jimbo

**Comment by jimbolya0607** [comment]
so i ran that curl statement from the command line and got a cert error...
ran curl -k and then the statement.  received no error, but did not get a new event from feed...
so, still not working.

**Comment by cygnetix** [comment]
My understanding of cron (not MISP specifically) is that `5 * * * *` would run the job at 5 minutes past the hour every hour. To run a job every 5 minutes you'd usually use `*/5 * * * *`.

Maybe give the above a try just in case that's your issue.

**Comment by Nymeria1** [comment]
Hi all,
same problem for me with MISP version v2.4.91.  Is it possible the problem persists also in this version
I added the command in crontab at this moment. At the end have you solved in this way?
Many thanks

**Comment by jimbolya0607** [comment]
I use cron exclusively for feed scheduling.  When I get back home I'll send
over what mine look like.

Jimbo

**Comment by Nymeria1** [comment]
Any news Jimbo or others?
Unfortunately, the problem persists also with 
/feeds/cacheFeeds/all  
adding in crontab.

At this moment the only solution is to force the operation via GUI.

Thanks

**Comment by jimbolya0607** [comment]
Yea sorry man - here's my crons that i put in crontab
I sill need to adjust them.  I think they are colliding because they
basically are running at the same time.

Feed #1 CIRCL OSINT Feed
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here" "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/1"

Feed #2 The Botvrij.eu Data
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/2"

Feed #3 inThreat OSINT Feed
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/3"

Feed #4 cybercrime-tracker.net -
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/11"

Feed #5 Phishtank online valid phishing
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/12"

Feed #6 Ransomware Tracker CSV Feed
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/21"

Feed #7 CoinBlockerLists - This list contains all IPs - A additional list
for administrators to prevent mining in networks
0 * * * * curl -i -k --insecure -H "Accept: application/json" -H
"Content-Type: application/json" -H "Authorization: auth key goes here " "
https://feeds.labyrinth-cis.com/feeds/fetchFromFeed/49"

**Comment by Nymeria1** [comment]
Do not worry Jimbo.
Thanks, I added the header to my curl.
So I used this to fetch all feed.
`curl --header "Authorization:xxxxxxxxxxxxxxxxx" --header "Accept: application/json" --header "Content-Type: application/json" misp_url/feeds/cacheFeeds/all
`

**Comment by jimbolya0607** [comment]
sounds good sir -
i got stuck on the right headers to use.  Alexandre helped me walk through
it and it's now a permanent place in my notes lol.

Jimbo

**Comment by adulau** [comment]
All good then Thank you for the feedback. Let me know if the documentation part is incorrect or needs update, we can fix it.  https://www.circl.lu/doc/misp/automation/#enable-disable-and-fetching-feeds-via-the-api

**Comment by jimbolya0607** [comment]
Looks good Aleandre - thanks for all the work sir!

Jimbo

**Comment by Nymeria1** [comment]
The calling seems to work but the job in MISP GUI has the queued state.

**Comment by jimbolya0607** [comment]
reboot your server?

**Comment by Nymeria1** [comment]
I restarted the server but the jobs were queued yet.
Do you restart your server after the API call?

**Comment by jimbolya0607** [comment]
typically no i don't
I just let it run
sometimes things get stuck in that status, but that doesn't mean other
sessions won't run
unfortunately i don't know how to take things out of that status
sometimes i've deleted the worker associated with the status and created a
new one
that does the trick sometimes as well
if your cron job is set up right maybe kill that worker and create a new one

jimbo

**Comment by ilyaglow** [comment]
Probably we should mention somewhere about useful `/feeds/fetchFromAllFeeds` API call.
