### ISSUE TITLE
Feature Request - Ability to hide, delete attributes and/or tags in correlation view.

### ISSUE THREAD

**Issue by Andy-Dove** [MISP/MISP#2558]
I have many events with similar tags and also some imported events which have filenames that I would prefer not to see correlated.  Would it be possible to have an option to remove them from the correlation view, in order to make it clearer?

I realise that you can go into the attributes themselves and choose to not correlate on a specific instance but that means going into dozens of individual events.  I would like to do it in one hit.

**Comment by adulau** [comment]
Does the disable correlation at attribute level help you in this case? It's an option in the MISP setting (set false by default):  `MISP.allow_disabling_correlation` then you can disable correlation at attribute level or event level.

**Comment by Andy-Dove** [comment]
I shall try this and see how it performs. Tags appearing on the correlation screen are definitely a nuisance tho. Particularly as you start to expand out related events. I can see how they can be useful but I’d definitely like an option to remove them.

**Comment by adulau** [comment]
I'll close the issue. Feel free to reopen if the you have any issue. Cheers.
