### ISSUE TITLE
MISP file object not exported to STIX 1.x or 2.x output

### ISSUE THREAD

**Issue by david74552** [MISP/MISP#2561]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug or Expected behaviour
| OS version (server)       | ?
| OS version (client)       | Ubuntu
| PHP version               | ?
| MISP version / git hash   | 2.4.80, ?
| Browser                   | Mozilla Firefox 56

### Expected behavior
Adding a MISP file object to an event will result in a STIX file object when exported to either STIX 1.x (xml) or 2.x (json) format.

### Actual behavior
The STIX json and xml output does not contain the file object or the member attributes.
The object does however appear in the MISP xml export format.

### Steps to reproduce the behavior
Create an event
Create a file v3 (688c46fb-5edb-40a3-8273-1af7923e2215) object
Fill out some of the attributes
Submit and approve the preview
Publish the event
Download as...
STIX XML     or    STIX JSON

### Logs, screenshots, configuration dump, ...
xml
[misp.stix.event6478.xml.zip](https://github.com/MISP/MISP/files/1381434/misp.stix.event6478.xml.zip)

json
[misp.stix.event6478.json.zip](https://github.com/MISP/MISP/files/1381435/misp.stix.event6478.json.zip)

(working, included for comparison) MISP xml export
[misp.event.6478.5899572e-1cf4-4b27-ac58-6d7a0a182083.xml.zip](https://github.com/MISP/MISP/files/1381436/misp.event.6478.5899572e-1cf4-4b27-ac58-6d7a0a182083.xml.zip)

**Comment by RichieB2B** [comment]
I can reproduce the issue.. looking into it (for STIX 1 export).

**Comment by iglocska** [comment]
Cheers @RichieB2B !

**Comment by RichieB2B** [comment]
The STIX 2 export is fairly incomplete, so I don't think we need to keep this issue open on that account.

**Comment by iglocska** [comment]
It's getting there, @chrisr3d is working hard at it, just pushed something.

**Comment by RichieB2B** [comment]
Looking at https://github.com/MISP/MISP/commit/dbad853a168fb473213c6907c5763c2419033eab file objects should be handled now in STIX 2 as well... eventually (not all object types are exported just yet).
