### ISSUE TITLE
New MISP Install: An Internal Error Has Occurred.  Error: An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by trismegistusX** [MISP/MISP#2567]
New MISP install, access to MISP portal in browser shows error:
"An Internal Error Has Occurred.  Error: An Internal Error Has Occurred."

| Type of issue             | Support
| OS version (server)       | ubuntu 16.04.1 LTS
| PHP version               | PHP 7.0.22
| MISP version / git hash   | 2.4.81

var/www/MISP/app/tmp/logs/debug.log 
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

AND

/var/www/MISP/app/tmp/logs/error.log 
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

Next steps to troubleshoot/fix?

**Comment by zeroq** [comment]
Did you check that the MySQL Server ist running?

**Comment by trismegistusX** [comment]
Yes, output of running services:
**tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      27462/mysqld**    
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1680/redis-server 1
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      6949/sshd       
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      9630/cupsd      
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      6886/master          
tcp6       0      0 :::80                   :::*                    LISTEN      4548/apache2    
tcp6       0      0 :::22                   :::*                    LISTEN      6949/sshd       
tcp6       0      0 ::1:631                 :::*                    LISTEN      9630/cupsd      
tcp6       0      0 :::443                  :::*                    LISTEN      4548/apache2    
udp        0      0 0.0.0.0:55271           0.0.0.0:*                           1522/avahi-daemon: 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1522/avahi-daemon: 
udp        0      0 0.0.0.0:631             0.0.0.0:*                           9631/cups-browsed
udp6       0      0 :::5353                 :::*                                1522/avahi-daemon: 
udp6       0      0 :::59766                :::*                                1522/avahi-daemon:

**Comment by arnydo** [comment]
Did you check the user/pass are correct for connecting to the MySQL database?

**Comment by iglocska** [comment]
Yep, sounds like a credential issue. Make sure that you can log into mysql
with your user from /var/www/MISP/app/Config/databse.php

**Comment by trismegistusX** [comment]
Have to login as root in order to access DB:

root@hostname:mysql -u root

`MariaDB [mysql]> SELECT user,plugin FROM user;

+------+-------------+

| user | plugin      |

+------+-------------+

| root | unix_socket |
| misp |             |

+------+-------------+
`

AND

root@hostname:mysql -u misp (Login allowed but not DB privileges)
ERROR 1044 (42000): Access denied for user 'misp'@'localhost' to database 'mysql'

user@hostname: mysql -u root OR sudo mysql -user misp (logins fail)

Output from database.php:

`'datasource' => 'Database/Mysql',

                //'datasource' => 'Database/Postgres',

                'persistent' => false,

                'host' => 'localhost',

                'login' => 'db login',

                'port' => 3306, // MySQL & MariaDB

                //'port' => 5432, // PostgreSQL

                'password' => 'XXXXXXXXXXXXXX',

                'database' => 'misp',

                'prefix' => '',

                'encoding' => 'utf8',
`

So, how should the privileges for each user be set correctly as in the DB table and config above?

**Comment by arnydo** [comment]
This is in the documentation...try this:

```
6/ Create a database and user
-----------------------------
# Enter the mysql shell
sudo mysql -u root -p

MariaDB [(none)]> create database misp;
MariaDB [(none)]> grant usage on *.* to misp@localhost identified by 'XXXXdbpasswordhereXXXXX';
MariaDB [(none)]> grant all privileges on misp.* to misp@localhost;
MariaDB [(none)]> flush privileges;
MariaDB [(none)]> exit
```

**Comment by trismegistusX** [comment]
Ok, I solved it by removing misp user and database and redoing mysql_secure_installation for root.

Applied commands for adding misp user and misp database again.

Updated database.php with correct login and password for misp user.
(I neglected to change the 'dblogin' and password was not set for misp user correctly)

Thanks for the guidance!

**Comment by trismegistusX** [comment]
Ok, issue has returned again. (MISP TAXII install - can create separate issue thread if required)

Output from ```
tail -f /var/www/MISP/app/tmp/logs/error.log:

#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

Output from ```
tail -f /var/www/MISP/app/tmp/logs/debug.log:

View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??
```


Was finishing the MISP server settings configuration and checked the Diagnostics for Stix/Cybox libraries in order to proceed with installing MISP TAXII Server:
```
sudo -H -u www-data bash -c 'python /var/www/MISP/app/files/scripts/stixtest.py'
{"cybox": "2.1.0.12", "stix": "1.2.0.2", "success": 1, "mixbox": "1.0.2"}
```

Moved on to install MISP TAXII Server: (python version 2.7.12 as an FYI)
git clone --recursive https://github.com/MISP/MISP-Taxii-Server (Note didn't specify var/www/MISP as path)
sudo pip install libtaxii==1.1.111
cd MISP-Taxii-Server/
sudo python setup.py install

Resultant error was:
Error:
EnvironmentError: mysql_config not found

Proceed to install but required some dependencies meeded to be installed such as: 
```
sudo apt-get install libmysqlclient-dev
The following additional packages will be installed:
  python-cffi-backend
The following NEW packages will be installed:
  libmysqlclient-dev
The following packages will be upgraded:
  python-cffi-backend
Setting up python-cffi-backend (1.10.0-0+certbot~xenial+1) ...
Setting up libmysqlclient-dev (5.7.19-0ubuntu0.16.04.1) ..
```

Checked MISP Portal and received the dreaded Internal Server Error again!

I purged   libmysqlclient-dev &&   python-cffi-backend but still "Internal Server Error"

Login to the MISP DB fails:
Database is corrupted as a result (cannot login as root or misp user):
```
sudo mysql -u root -p
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
```

What are the next steps?
(Rebuild MISP DB for misp & root user access)?
(Do I install MISP-TAXII-Server in /var/www/MISP/)?

**Comment by RichieB2B** [comment]
The error message is saying your MySQL server is not running.

**Comment by trismegistusX** [comment]
Checked to see if MySQL service was running and nothing there, 

/etc/init.d/mysqld status
bash: /etc/init.d/mysqld: No such file or directory

previously it ran as below:
service mysql restart 
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      27462/mysqld

**Comment by RichieB2B** [comment]
Perhaps reinstall your MySQL server software?

**Comment by trismegistusX** [comment]
Reboot of the server did the trick.

Any tips to install MISP-TAXIi-Server cleanly without affecting the MISP setup?

**Comment by trismegistusX** [comment]
Finished the setup for installing MISP. Some observations:

Memory of server had to be increased due to MariaDB crashing when any interaction with it such as import events:
[ERROR] mysqld: Out of memory

Use python3 as dependencies will come into play, had to upgrade Stix and Cybox against recommended versions for MISP. (For MISP-TAXII reasons)
{"cybox": "2.1.0.13", "stix": "1.2.0.2", "success": 1, "mixbox": "1.0.2"}
