### ISSUE TITLE
Installation not working, CakeResque not found

### ISSUE THREAD

**Issue by ericbl** [MISP/MISP#257]
Hello,
I would like to evaluate the MISP platform.
I installed a fresh Ubuntu 12.04 server on a VM, on which I followed all steps to install MISP, according to 
https://github.com/MISP/MISP/blob/master/INSTALL/INSTALL.txt

I check everything twice, tried also with uncommenting  CakePlugin::loadAll('CakeResque at the end of /var/www/MISP/app/Config/bootstrap.default.php

But on the last step, 
cd /var/www/MISP/app/Console/worker/
- ./start.sh

I always get "Error: Plugin CakeResque could not be found."

How can I make this working?

I did not got other errors during the install, especially, on the CakeResque folder, the following step worked fine
curl -s https://getcomposer.org/installer | php
php composer.phar install

What am I missing?

**Comment by thirdeyeintelligence** [comment]
I have followed the instructions but I am still getting An internal Error has occured.

Looked at the error log : 

2016-02-24 23:09:47 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[28000] [1045] Access denied for user \'admin@admin.test\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)

please verify database config

class DATABASE_CONFIG {

```
    public $default = array(
            'datasource' => 'Database/Mysql',
            'persistent' => 'false',
            'host' => 'localhost',
            'login' => 'admin@admin.test',
            'port' => '3066',
            'password' => 'admin',
            'database' => 'misp',
            'prefix' => '',
            //'encoding' => 'utf8',
    );
```

and when i go to localhost:3306 i get following :+1: 

5.5.47-0ubuntu0.14.04.1�)���=65GEb?T�ÿ÷�€����������f'+BJ/Lne2g3�mysql_native_password�!��ÿ„#08S01Got packets out of order

I have tried changing the above information but seems nothing is working for me.

**Comment by elhoim** [comment]
@makflwana,  your database_config says 3066 while it should probably be 3306.

**Comment by thirdeyeintelligence** [comment]
ahhhh let me try that and update. Thanks again @elhoim

**Comment by Dharmik8478** [comment]
@makflwana, I got same issue and please tell me any solutions.
I am also using 3306 port for mysql database.

Thanks.

**Comment by iglocska** [comment]
Using the settings that you have in the database.php line, can you log in to mysql and see the tables in the misp db?

**Comment by thirdeyeintelligence** [comment]
Mine is working perfectly - may be in your database.php change the username to root and than try...if not please tail the logs see the error messages - you can paste the config which is showing error....
