### ISSUE TITLE
BaseURL settings/access MISP on alternative port

### ISSUE THREAD

**Issue by frennkie** [MISP/MISP#2571]
As discussed with @iglocska:

I have two virtual hosts that provide access to one MISP instance:
* https://misp.example.com
* https://misp.example.com:8443

BaseURL setting: https://misp.example.com

When I access MISP via the :8443 URL then all links redirect to :443 (because of the BaseURL).
A workaround would be to remove the BaseURL setting - but according to @iglocska this has an impact on the community sharing (because this re-uses the BaseURL setting) -> might be a good idea to separate these settings.

**Comment by arnydo** [comment]
Are you able to add the port to the "Base URL"? @frennkie

**Comment by arnydo** [comment]
Looks like someone else is looking for this feature on issue #2525

**Comment by arnydo** [comment]
I believe you would need to go into your apache2 config and update the virtual hosts. You may also want to add a new DNS record to the MISP IP so that you can bind the virtual host via the ServerName option.

```
<VirtualHost *:8443>
	ServerAdmin me@me.local
	ServerName misp.local
	DocumentRoot /var/www/MISP/app/webroot
	<Directory /var/www/MISP/app/webroot>
		Options -Indexes
		AllowOverride all
		Order allow,deny
		allow from all
	</Directory>

	LogLevel warn
	ErrorLog /var/log/apache2/misp.local_error.log
	CustomLog /var/log/apache2/misp.local_access.log combined
	ServerSignature Off
</VirtualHost>
```

**Comment by frennkie** [comment]
As mentioned in #1620 I use this because I have LDAP authentication (done by Apache) on :443 and do API Call (with MISP internal authentication) on :8443.

The reason for this issue is that when I access MISP on :8443 all links ignore this and go to :443 (due to the BaseURL setting). I personally discussed this with @iglocska at Hack.lu and he wanted to look into it.

**Comment by iglocska** [comment]
Yeah, will give it a bash soon to just adding a second function that is reused for sharing groups only that is separate from the baseurl directive. This will allow users to use relative paths without all of the associated issues we have today.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/fede678d5df8d90c02e9a12e5380603a99651974

**Comment by paulboben** [comment]
I do have the same issue and i am pretty new to MISP. when i am trying to access misp via 10.100.X.X:8443 couldn't able to connect and url is changing to 10.100.X.X/users/login stripping the port from the url. And i set my base url as 10.100..X.X:8443. @adulau
