### ISSUE TITLE
Bundling expiration sighting in attribute (via API and UI)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2579]
Bundling expiration sighting in attribute (via API and UI)

**Comment by liviuvalsan** [comment]
On a related note, while expiration sightings can be added per organisation and attribute, I believe that the expiration date is not currently being taken currently into account for the IDS export. It would probably make sense to remove expired attributes from the export to IDS.

**Comment by mokaddem** [comment]
@liviuvalsan This feature is currently being implemented see [this comment](https://github.com/MISP/MISP/issues/4429#issuecomment-480172346).
