### ISSUE TITLE
Cant restart scheduller worker

### ISSUE THREAD

**Issue by zoni171** [MISP/MISP#2583]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | Debian 3.16.0-4-amd64
| OS version (client)       | N/A
| PHP version               | 7.0.16-1~dotdeb+8.1 (Up to date)
| MISP version / git hash   | 2.4.81 (latest as of now)
| Browser                   | Chrome

### Expected behavior

Be able to restart the scheduler worker. 

### Actual behavior

Scheduler worker wont start through "Start Worker" nor through the "Restart all workers" buttons in the "Workers" tab in the Server Settings.

### Steps to reproduce the behavior

Don't know / "Worker not running!"

**Comment by truckydev** [comment]
Have you forget to do this ?
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian9.txt#L105

**Comment by zoni171** [comment]
Hey truckydev 

I think I did. That took care of it. Thanks a lot
