### ISSUE TITLE
Broken URL in "Related Feeds" navigation

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#2598]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | OS X
| PHP version               | 7.0
| MISP version / git hash   | 2.4.81, 11b7e8e8081d0f35f56c16798ce83bb6f3bb6bd8
| Browser                   | If applicable

### Expected behavior
Navigation between feeds. URL would point to
https://misp.mydomain.com/feeds/view/1

### Actual behavior
A missing "/" in the URL results in a "site can't be reached error" since ".comfeeds" isn't a valid TLD
https://misp.mydomain.comfeeds/view/1

### Steps to reproduce the behavior
1. Set up a MISP with two feeds that correlate
2. Open one of the feed events and click on a link in the Related Feeds section

### Logs, screenshots, configuration dump, ...

<img width="408" alt="screen shot 2017-10-26 at 16 30 10" src="https://user-images.githubusercontent.com/15183688/32075724-a243f790-ba6b-11e7-8376-0db83c02645e.png">

**Comment by infosec-intern** [comment]
Closing this issue. Looks like it was fixed by 285fe47d5b170fc9f575f32f8e72cdb880d03374
Thanks @iglocska!

**Comment by iglocska** [comment]
Thanks for the follow up, I'm pretty bad with hunting down issues for stuff
that I fix! ;)
