### ISSUE TITLE
Events not pushed to sharing group

### ISSUE THREAD

**Issue by marcnil815** [MISP/MISP#2601]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Ubuntu 16.04
| PHP version               | PHP 7.0.22-0ubuntu0.16.04.1
| MISP version / git hash   | 2.4.81
| Browser                   | N/A

### Expected behavior
Two instances M1 and M2.
**M1:**
ORG1 (local)
ORG2 (remote)
Sync Server -> M2 (push) /w Sync User ORG2_sync auth key
Sharing Group "TEST_SG" -> ORG1 as local, ORG2 as remote, M2 as server ("Events are automatically pushed to M2"
**M2:**
ORG2 (local)
Sync user -> ORG2_sync (local)

1. Create event on M1. Set distribution Sharing Group "TEST_SG"
2. Publish event.
3. Initiate push (manual or scheduled)

Event gets pushed to M2

### Actual behavior
Event is not pushed.
Logs on M1 state: 
"Push to M2" "0 events pushed or updated. 0 events failed or didn't need an update.".

Creating same Sharing Group on M2 and republish event: no effect.
Enable roaming on Sharing group on M1 and republish event: no effect.
Enable "all orgs" on M2 in sharing group and republish event: no effect.
Change ORG2 on M1 from remote to local (and edit sharing group accordingly) and republish event: no effect.
Add ORG1 on M2 as local and republish event: no effect.
Change syn AUTH key to local sync user on M2 and republish event: no effect.

The event just never makes it out of M1 (push).

Depending on above setting M2 can _pull_ the event, but it should be pushed.

### Steps to reproduce the behavior
Create two MISP M1 (ORG1) and M2 (ORG2)
Create a Sharing Group XYZ on one M1
Add the remote M2 org as remote
Add M2 as eligible server.
Save Sharing Group
Create event with distribution XYZ.
Push.

**Comment by iglocska** [comment]
Thanks for the heads-up, pushed a potential fix. I've managed to reproduce the issue and indeed 2.4.80 seems to have been the culprit - could you give it a shot and let me know if you still have issues? Thanks!

**Comment by marcnil815** [comment]
Upgraded two MISPs to 2.4.82.
I did a quick check. Unfortunately it seems the problem persists.

Same result: "0 events failed or didn't need an update"

**Comment by marcnil815** [comment]
Wait. Hold on. Let me check again. The logs apparently aren't correct.

**Comment by marcnil815** [comment]
Ok. It actually works.
New event gets pushed immediately on publish, which I did not realize, so I did a manual PUSH and merely checked the logs.
Since the event was already pushed the logs, correctly, stated "nothing to push", which threw me off.

**Comment by iglocska** [comment]
Excellent - thanks for reporting it and for the rapid tests! Let me know if you run into anything else that's broken!
