### ISSUE TITLE
Default GUI User ID & Password

### ISSUE THREAD

**Issue by cicakdinding01** [MISP/MISP#2602]
Hi,

What is the default GUI User ID and Password for the automatically generated VMware images and VirtualBox in the latest MISP core commit? The credentials stated in the documentation admin@misp.training (which I believe is for the training image?) does not work.

Regards,

**Comment by iglocska** [comment]
admin@admin.test / admin

if I remember correctly.

**Comment by RichieB2B** [comment]
Nope, it’s admin@misp.training / Password1234

**Comment by adulau** [comment]
For the [automatically generated virtual machines](https://www.circl.lu/misp-images/latest/) at each commit, please find the credentials:

~~~~
For the MISP web interface -> admin@admin.test:admin
For the system -> misp:Password1234
~~~~

Sorry for the confusion, I'll update those on the website.

https://github.com/MISP/misp-vagrant/blob/master/bootstrap.sh#L401

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/misp-website/commit/481ea61617ab33262eabb902eb59a5c1740fdfaa 

Thank you for the notification.
