### ISSUE TITLE
Published events no longer publish to ZMQ

### ISSUE THREAD

**Issue by kx499-zz** [MISP/MISP#2604]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | WIN7
| PHP version               | 7.0
| MISP version / git hash   | 2.4.81
| Browser                   | If applicable

### Expected behavior
When an event is published it should be published to zmq

### Actual behavior
As of the .81 update when an event is published it no longer published to zmq without explicitly publishing to zmq from the menu. 

### Steps to reproduce the behavior
enable zmq, publish event.

**Comment by kx499-zz** [comment]
I'm still struggling with this one, so if anyone has some insight I'd love to hear it.

**Comment by iglocska** [comment]
Should still work, will test it tomorrow at work.

**Comment by adulau** [comment]
I tested with 2.4.82 and it works. Feel free to reopen the issue if the recent release (including major improvement in the ZMQ) doesn't solve your issue. Thank you!
