### ISSUE TITLE
STIX export errors with ASCII control codes

### ISSUE THREAD

**Issue by jaccol** [MISP/MISP#2605]
When exporting STIX from MISP, I get errors when I try to import it in another program:

PCDATA invalid Char value 31, line 235, column 22 (<string>, line 235)

I found three such occurrences so far. Each with different characters, all below ASCII 0x20.
In every case the text with the invalid char is inside <incident:Journal_Entry> tags.
I suspect there should be some escaping for these characters.

I got these errors from different MISP installations with recent versions (2.4.79+)

**Comment by chrisr3d** [comment]
This should have been fixed long time ago since we made sure files are open in utf-8, but let me know if it is not the case. I'll close the issue for the moment.
Thank you
