### ISSUE TITLE
"Roles" endpoint spins unless you're admin

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#2606]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Win10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.81
| Browser                   | Chrome

### Expected behavior
"Access Forbidden" page or some other kind of HTTP error

### Actual behavior
"redirected too many times" error from Chrome

### Steps to reproduce the behavior
1. Click on **Administration** > **List Roles** as a non-admin user (tried with regular admin, User, and Org Admin)
OR
2. View the organization you're part of (https://mymisp.domain.com/organisations/view/7) and click on **Role Permissions**
OR
3. Go directly to https://mymisp.domain.com/roles

### Logs, screenshots, configuration dump, ...
![capture](https://user-images.githubusercontent.com/15183688/32250507-65f309e4-be52-11e7-99cc-44cf75796248.PNG)
![capture](https://user-images.githubusercontent.com/15183688/32250517-732fdfd8-be52-11e7-9ec3-4ae99f4975ff.PNG)

**Comment by iglocska** [comment]
Thanks for the heads-up!
