### ISSUE TITLE
Adding user problem

### ISSUE THREAD

**Issue by NoamIchnr** [MISP/MISP#2607]
Hello, we have recently installed MISP and we face some issues adding users. We keep get an error note saying that the user credentials are not valid. On other trials we received a note that credentials were sent, yet no email arrived. Could you help please? :(

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Do you have e-mailing and encryption set up correctly?

> We keep get an error note saying that the user credentials are not valid.

Do you get this on login or when changing a user's password?

**Comment by NoamIchnr** [comment]
Hi, Thanks. I believe we set it right. The all process of adding a user seems ok and the new user is on list, yet  when we try to send a password/ welcome email an error massage appears saying that credentials are incorrect.  In second trial it says that the credentials were sent, yet no such email is received. 
I tried it with adding pgp and without pgp and it was the same :(

**Comment by iglocska** [comment]
Very odd. Will try to reproduce it, could you send a screenshot with the
exact error message?

**Comment by NoamIchnr** [comment]
It is a bit odd, since anything else seems to work fine. We are checking the emailing and encryption set up again to make sure nothing went wrong there. I will send a screen shot once we will make sure of it! Thanks!
