### ISSUE TITLE
Phishtank feeds doesn't work

### ISSUE THREAD

**Issue by Mokatani** [MISP/MISP#2609]
Hi,
After enabling the Phishtank feed in MISP tries to cache the feeds and then fetch it, it only create an event but doesn't fetch the attributes from CSV file. The CSV file from Phishtank is accessible through browser.
  
Thanks

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.0,
| MISP version / git hash   | 2.4.81
| Browser                   | If applicable

### Steps to reproduce the behavior
Enable the Phistank feed, cache the feed, fetch all event

**Comment by adulau** [comment]
This seems related to the redirect to the CDN. I suppose maybe the feed fetcher is not supporting the redirect. @iglocska what do you think?

**Comment by StefanKelm** [comment]
I'm having the same issue both with the Phishtank feed as well as the Ransomware Tracker one.
Caching the feed doesn't do anything (although the job status says "completed"), fetching all events creates the event (with no attributes at all) and leads to the following line in error.log:

`2017-11-13 10:42:38 Warning: Invalid argument supplied for foreach() in [/services/inst/misp/app/Model/Feed.php, line 644]`

**Comment by StefanKelm** [comment]
BTW, the "...Invalid argument..." error line disappeared when I disabled the Ransomware Tracker

**Comment by StefanKelm** [comment]
Just for the sake of completeness: this issue applies to the feeds from osint.bambenekconsulting.com as well.

...and "exploring the events remotely" doesn't work on those feeds either (if that helps at all)...

**Comment by adulau** [comment]
This should be fixed now in https://github.com/MISP/MISP/commit/a5ceed1522c5cd41a8a5a9661f159aef3eb49ca3 Feel free to reopen if the issue persists.
