### ISSUE TITLE
Bash script to automate MISP upgrades

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/MISP#2611]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 5.6
| MISP version / git hash   | 2.4.81

### Expected behavior
Automate core upgrades

Hi,
_Not familiar with pull requests, so I post here. Do not hesitate to move it in the relevant section._

I wrote a Bash script to automate MISP core upgrades in our production environment.
Feel free to test and contribute to improve it:

[misp_upgrade.txt](https://github.com/MISP/MISP/files/1439500/misp_upgrade.txt)

Thanks,
Best regards,
Julien

**Comment by adulau** [comment]
Thank you for the contribution. The script is indeed very interesting. Maybe we should add in the ./INSTALL directory? @iglocska what do you think? Some parts of the script deals with SELinux installation too.

**Comment by Tux-Panik** [comment]
Hi,
I updated the script version to correct a little bug (line 129).
[misp_upgrade.txt](https://github.com/MISP/MISP/files/1611618/misp_upgrade.txt)

Regards,
Julien

**Comment by SteveClement** [comment]
testing now…

**Comment by SteveClement** [comment]
Script might want to ignore:
	modified:   app/composer.json

**Comment by SteveClement** [comment]
Here is a partial output from a debian stable perspective:

http://pastebin.lu/zosobaworu.sql
@Tux-Panik I suppose you tested on centos only.

A more generalized script would be better, I will put the script on a branch for experimental external scripts.
