### ISSUE TITLE
Internal error on opening event

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#2614]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue:                | support
| OS version (server)       | ubuntu
| OS version (client)         | Ubuntu
| PHP version                  | 7.0.22
| MISP version / git hash   | v2.4.81 (4b339751ee101a97ffda1a7e9c72398c689cc1f1)
| Browser                         | Chrome

On opening event get Internal error. In Error log have record:
```
2017-11-03 15:21:55 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.object_id' in 'field list'
Request URL: /events/view/620
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1522): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1356): DboSource->_fetchHasMany(Object(Event), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1215): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Event), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#8 /var/www/MISP/app/Model/Event.php(1538): Model->find('all', Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1039): Event->fetchEvent(Array, Array)
#10 [internal function]: EventsController->view('620')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

If switch to version v2.4.79 (8725821a5ae69592cae434e3e46572341ac4d436) then no errors occurs.

**Comment by iglocska** [comment]
Could you try to clean the model caches?

administration -> server settings -> diagnostics -> clean model cache button

and see if it resolves it?

**Comment by Turecky** [comment]
I clean model cache but error still remains.

**Comment by iglocska** [comment]
ok, could you run this mysql query?

```
UPDATE `admin_settings` SET `value` = '2.4.79' WHERE `setting` = 'db_version';
```

and afterwards check the upgrade log? (Audit Log - > MISP Update results tab)

**Comment by Turecky** [comment]
Thanks for tip. In audit logs was list off issue with queries. Grand mysql misp user with permission and all queries run as expected. Now events opens as expected.

**Comment by iglocska** [comment]
Perfect, thanks for the feedback B-)

**Comment by criptk** [comment]
I have the same issue, tried doing the same thing but got the following error 
Error: The requested address '/events/cleanModelCaches' was not found on this server.
When i can do that how can i be certain about the specific version to be inserted into the sql statement ? 

Thanks
