### ISSUE TITLE
Add ability to use custom regex with Freetext Import

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#2616]
I would like to be able to add custom regex and map it to an attribute type in MISP, especially for things like internal references and targets. Instead of the "regexp + replace" feature that currently exists, this would apply to the freetext import tool in a similar way to how the CVE regex works now

For example, a regex that validates internal company usernames and maps to target-user

I think the best fit is adding a section to the ComplexTypeTool.php (thanks to SHSauler's help) that takes a map of regexp => attribute_type and loops through each regexp. This route would require an extra form similar to the "Import Regexp" one that users can add to

---
CVE Regex I was referring to
```
// check for CVE
if (preg_match("#^cve-[0-9]{4}-[0-9]{4,9}$#i", $input)) return array('types' => array('vulnerability'), 'categories' => array('External analysis'), 'to_ids' => false, 'default_type' => 'vulnerability', 'value' => $input);
```

**Comment by infosec-intern** [comment]
Currently revisiting this and coming up with a plan. @iglocska, would it be heresy to add a new database table for `attribute_validators` and pull the regexp in the [Attribute->runValidation](https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L815) method from the database instead of hardcoding it in a select statement?

That way we can add a view for custom validators and allow a user to simply add to that table

EDIT: There are some cases where regexp isn't applied to types, so the select would still have to stay to accommodate those

**Comment by iglocska** [comment]
I would not move the runValidation methods in there because some of them are not regexes but algorithms (look at the painful financial ones ;)) - however, having a new table for custom regex rules for the freetext import wouldn't be a bad idea.

**Comment by infosec-intern** [comment]
Good point. Then a hybrid approach may work better? The validate & return cases like 'mac-address' would essentially be duplicating code anyway, so these simpler cases could be treated the same as the custom regex

**Comment by iglocska** [comment]
we could run the custom ones before the others - if there's a hit, return immediately, if not, go through the normal function.

**Comment by infosec-intern** [comment]
Sounds good. I'll work on it, thanks!

**Comment by iglocska** [comment]
Excellent, thanks B-)

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
