### ISSUE TITLE
Freetext import of a list of domains

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2619]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, (Question?)
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 7
| PHP version               | 7.x
| MISP version / git hash   | 2.4.82

### Expected behavior
I would like to import a list of domains with the freetext import and have MISP suggest:
Category = Network activity
Type = domain

### Actual behavior
MISP suggests the following and changing those suggestions (especially the type) is not possible:
Category = Payload delivery
Type = filename

I understand this is hard to filter because it matches the schema of a filename, but at least it would be very helpful to have the option to change the category or type. This is recently not possible so a bulk import of domains through the freetext import is not possible.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/20771149/32447102-5557ce9a-c30b-11e7-84c6-3dcb9a5b93fd.png)

**Comment by adulau** [comment]
It works for me. 

I have the impression the TLDs list from the warning-list is maybe not working in your case. Could check if you have "TLDs as known by IANA" in the warning list?

**Comment by ghost** [comment]
Yeah, for some reason the warning-list "TLDs as known by IANA" was disabled. Enabling it fixed the issue. 
Thanks a lot.
