### ISSUE TITLE
Error 500 while connecting to web interface

### ISSUE THREAD

**Issue by Spj28** [MISP/MISP#2622]
I newly installed MISP following the guide INSTALL.ubuntu1604.txt on a brand new linode but unable to connect to the interface over ssl. Keep getting the following error:

This page isn’t working
misp_server is currently unable to handle this request.
HTTP ERROR 500

misp.local_error.log shows the following:

[Tue Nov 07 10:22:27.055998 2017] [:error] [pid 11565] [client 97.105.241.94:58180] PHP Fatal error:  Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261\nStack trace:\n#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[MissingPluginE...', '/var/www/MISP/a...', 138)\n#1 [internal function]: ErrorHandler::handleError(256, '[MissingPluginE...', '/var/www/MISP/a...', 138, Array)\n#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[MissingPluginE...', 256)\n#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::handleException(Object(InternalErrorException))\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFat in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 261

Please help. I saw a similar issue raised but there was no resolution posted.
### Work environment

OS version (server) 	Ubuntu 16.04.3 LTS
OS version (client)         Macbook Sierra
PHP version                    7.0.22
MISP version                  2.4.81
Browser                          Chrome/ Firefox/ Safari

### Expected behavior
Should be able to see login page

### Actual behavior
This page isn’t working
misp_server is currently unable to handle this request.
HTTP ERROR 500

**Comment by PaoloVecchi** [comment]
It seems to complain about missing plugins.
I've just installed it and I didn't get those errors.

Any odd message you got during the setup?

Could you go through section 4 of the setup process again just in case you missed a bit?

**Comment by adulau** [comment]
Maybe one of the plug-ins is missing. Could you review if the following steps don't have any errors?

https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt#L86

**Comment by Spj28** [comment]
I tried a fresh reinstall and followed the install document but getting the same 500 error. 

Here is the error from /var/log/apache2/misp.local_error.log:
[Mon Nov 13 11:34:16.467408 2017] [:error] [pid 3429] [client IP:53114] PHP Warning:  include(/var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php): failed to open stream: No such file or directory in /var/www/MISP/app/webroot/index.php on line 81
[Mon Nov 13 11:34:16.467489 2017] [:error] [pid 3429] [client IP:53114] PHP Warning:  include(): Failed opening '/var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php' for inclusion (include_path='.:/usr/share/php') in /var/www/MISP/app/webroot/index.php on line 81
[Mon Nov 13 11:34:16.467520 2017] [:error] [pid 3429] [client IP:53114] PHP Fatal error:  CakePHP core could not be found.  Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php.  It should point to the directory containing your /cake core directory and your /vendors root directory. in /var/www/MISP/app/webroot/index.php on line 86

Per the INSTALL document, I have followed these steps:
9/ MISP configuration
---------------------
# There are 4 sample configuration files in /var/www/MISP/app/Config that need to be copied
sudo -u www-data cp -a /var/www/MISP/app/Config/bootstrap.default.php /var/www/MISP/app/Config/bootstrap.php
sudo -u www-data cp -a /var/www/MISP/app/Config/database.default.php /var/www/MISP/app/Config/database.php
sudo -u www-data cp -a /var/www/MISP/app/Config/core.default.php /var/www/MISP/app/Config/core.php
sudo -u www-data cp -a /var/www/MISP/app/Config/config.default.php /var/www/MISP/app/Config/config.php

But  based on the error, it seems to be looking for bootstrap.php in another path that does not exist. I am not an expert at this hence any help is appreciated.

**Comment by Spj28** [comment]
I re-ran some steps from the INSTALL doc and no longer getting the error.

**Comment by adulau** [comment]
Good news. Thank you for the feedback.
