### ISSUE TITLE
File Object TLP marking not correct in STIX export

### ISSUE THREAD

**Issue by imereau** [MISP/MISP#2623]
Dears,

I am running into the below issue:

When an attribute is flagged with some TLP marking, it is correctly set in the STIX export.
However, for an object (file object in this case), I don't see how to mark the object itself. Instead I am marking all its attributes with some TLP. In that case, it is not correctly reflected in the STIX export (keeps on showing as TLP: Amber whatever the TLP level I set).

I have attached 2 screenshots showing it works fine for standalone attributes and 2 screenshots showing the issue with objects.

Would you have any advice or workaround for this? It is quite a problem since it prevents from sharing from our TAXII server based on the TLP marking...

many thanks in advance.

Irving

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.81, 564deaa
| Browser                   | FF 47.0.1

### Expected behavior
TLP marking for objects in STIX export reflects the TLP marking of its attributes.

### Actual behavior
All objects are marked as TLP: Amber whatever the tagging of their attributes.

### Logs, screenshots, configuration dump, ...
![misp_screenshot_att_tlp_green_ok](https://user-images.githubusercontent.com/8105737/32552577-b142e2b4-c494-11e7-902a-f942c18ba2f6.jpg)
![misp_screenshot_obj_tlp_green_nok](https://user-images.githubusercontent.com/8105737/32552579-b15a63b2-c494-11e7-9203-df242144f9b8.jpg)
![stix_export_att_tlp_green_ok](https://user-images.githubusercontent.com/8105737/32552581-b1c60388-c494-11e7-8ce6-a7ce9608e271.jpg)
![stix_export_obj_tlp_amber_nok](https://user-images.githubusercontent.com/8105737/32552582-b20ee5b2-c494-11e7-97f6-2941cd2a9d1a.jpg)

**Comment by imereau** [comment]
I am actually realising that the event distribution is marking the evnt in the STIX export (e.g. Distribution = "Community" will mark the event as TLP:Green). Now if inside I have an object marked as TLP:red, it will correctly be marked in the STIX export.
However, if an event is TLP:Amber (Distribution = "Organisation"), then this will overwrite the TLP marking of an object within this event if it has a lower TLP level (e.g. GREEN)(but apparently not the TLP marking of a standalone attribute, which still seems to be a bug or an inconsistency). 

Could you please confirm my understanding is right?

Thanks a lot again and sorry for confusion.

irving

**Comment by adulau** [comment]
Could you check the version 2.4.82? Just to be sure.

**Comment by adulau** [comment]
Could you check the latest version which includes the updates https://github.com/MISP/MISP/commit/7236bc712495e2f944de0e3f9db6eeb419df79d1 made by @chrisr3d ?

**Comment by chrisr3d** [comment]
Yep, should have fixed your issue.
I tested with multiple examples and the marking of each object is the one of the most restrictive of its own attributes, if they have any TLP marking, otherwise it is set to the event marking.
