### ISSUE TITLE
Request - Complete LDAP Configuration Example

### ISSUE THREAD

**Issue by Amorik** [MISP/MISP#2624]
Hello,

The information regarding LDAP integration seems to be limited to the default config.php file and a handful of relevant github issues. I am currently using the later version of MISP alongside php71 and attempting to integrate MISP into our AD/LDAP system. As far as i can tell one only needs to ensure that the php-ldap module is enabled and update the settings per the config.default.php file. Unfortunately doing so seems to have no effect. Looking into the known log files provides no feed back so I am assuming i am missing something that is not clear.

Does anyone have a complete setup example of using the LDAP integration?

Thankyou

~Regards

**Comment by truckydev** [comment]
hi,

just for help : 
I don't use ldap but kerberos not only ldap for identification/authentifiation.
I have made this PR, maybe will be useful : 
https://github.com/MISP/MISP/pull/976
 and clear here : 
https://github.com/MISP/MISP/pull/1137
