### ISSUE TITLE
Not Able to View Galaxy Description Values

### ISSUE THREAD

**Issue by maddog317** [MISP/MISP#2625]
When MISP has over a million IOCs, there seems be be an issue when loading the Galaxy Description Page loads. 

### Expected behavior
Typically the page is supposed to look like this:

![screen shot 2017-11-08 at 1 32 10 pm](https://user-images.githubusercontent.com/22180532/32567530-86829804-c489-11e7-8ff6-d369e77d3be2.png)

### Actual behavior
Currently, the request is taking **so long** that the page is stuck looking like this for hours:

![screen shot 2017-11-08 at 1 27 52 pm](https://user-images.githubusercontent.com/22180532/32567575-a04966fa-c489-11e7-85d9-1ddb4c883d15.png)

The data is not loading onto the page. I am assuming there is either a timeout issue or the there is so much information that the values need oodles amount of time to calculate the activity and the number of events for each value. Is this a SQL Query update that needs to be performed? How can this be fixed?

### Steps to reproduce the behavior
1. Go to List Galaxies under the upper Galaxies tab
2. Then click on any galaxy by clicking it's description over on the far right
3. Wait for the values to load

### Work environment
MISP version 2.4.81
Chrome Browser
Ubuntu 1604

### Error Log
```
2017-11-01 18:26:46 Error: Fatal Error (1): Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1295]
2017-11-01 18:26:46 Error: [InternalErrorException] Internal Server Error
Request URL: /galaxy_clusters/index/130
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1295)
#1 [internal function]: ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1295, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Allowed memory ...', '/var/www/MISP/a...', 1295, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-11-01 18:26:49 Error: Fatal Error (1): Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1295]
2017-11-01 18:26:49 Error: [InternalErrorException] Internal Server Error
Request URL: /galaxy_clusters/index/130
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1295)
#1 [internal function]: ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1295, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Allowed memory ...', '/var/www/MISP/a...', 1295, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

**Comment by adulau** [comment]
Could you increase the `memory_limit` of the PHP configuration?

**Comment by iglocska** [comment]
It's the same issue as with the tag index. Will fix it tomorrow before the
release.

**Comment by adulau** [comment]
@iglocska  Cool thanks a lot!
