### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by guy3145** [MISP/MISP#2634]
Hi
i just completed a new installation.
when i try to login with default user and password i get an error:
"The request has been black-holed"
"Error: The requested address '/users/login' was not found on this server."
how can i solve it?

**Comment by guy3145** [comment]
sometimes i get:

This page isn’t working

ec2-54-93-231-80.eu-central-1.compute.amazonaws.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by guy3145** [comment]
2017-11-12 15:01:33 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(UsersController), 'auth')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by adulau** [comment]
I suppose this has been fixed in your installation. I'll close the issue. Feel free to reopen if the issue persists.

**Comment by mgaulton** [comment]
After having a working instance for the past week, suddenly i'm getting this same issue and as far as I know, nothing has changed.
After git pulling and restarting apache, no change.
After force setting the user password to something known, no change.
Any suggestions?

**Comment by dawid-czarnecki** [comment]
I installed second MISP instance on the same server. Different database, different path, different cake cache preffix.
Each login attempt result with '_The request has been black-holed_'. Even providing incorrect credentials.
Here is a stack trace:
```
2018-06-13 19:24:34 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login
Stack Trace:
#0 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(UsersController), 'secure', Object(SecurityException))
#3 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))
#4 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/second_misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/second_misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2018-06-13 19:24:34 Warning: Warning (2): session_start() [<a href='http://php.net/function.session-start'>function.session-start</a>]: open(/var/lib/php/session/sess_cc18378ff18323798214dbf8c50e1904, O_RDWR) failed: No such file or directory (2) in [/var/www/second_misp/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_start - [internal], line ??
CakeSession::_startSession() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743
CakeSession::start() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 219
CakeSession::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 404
SessionComponent::read() - APP/Lib/cakephp/lib/Cake/Controller/Component/SessionComponent.php, line 69
AppController::beforeFilter() - APP/Controller/AppController.php, line 233
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??
```

**Comment by annetteshajan** [comment]
@SteveClement @adulau 


> 2017-11-12 15:01:33 Error: [BadRequestException] The request has been black-holed
> Request URL: /users/login
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): AppController->blackhole('auth')
> #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
> #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(UsersController), 'auth')
> #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
> #8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #9 {main}

Getting this same error
No matter what I type as my password it always returns a page with "The request has benn black-holed"
Please suggest a fix

**Comment by RichieB2B** [comment]
Black holed means the anti-XSRF token expired. Reload the login page before entering your credentials.
