### ISSUE TITLE
downloadSample: No hits with the given parameters

### ISSUE THREAD

**Issue by imereau** [MISP/MISP#2636]
Dears,

I am constantly getting that message when I try to download a sample: "No hits with the given parameters". If I print the parameters, the hash is correctly set. eventID and allSamples parameters are set to null (download_samples(sample_hash=my_sample_hash, event_id=None, all_samples=False)).
I get back the hash by searching all objects of type "malware-sample", then I pass the hash part of the value key in the response. Searching on that same hash through the UI brings back the expected results. 

Could you please advise? I'm out of idea's..

Thanks a lot!
Irving

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.81, 564deaa
| Browser                   | FF 47.0.1

### Expected behavior
sample found and downloaded

### Actual behavior
no hits

### Steps to reproduce the behavior
just use the downloadSamples API function with a valid md5 hash

**Comment by Rafiot** [comment]
Good catch, I can reproduce with those calls:

```
POST - https://mispbeta.circl.lu/attributes/downloadSample  
{"request": {"hash": "6e230bb92d2721efc5971f9b887cf5dc"}}   
```

```
POST - https://mispbeta.circl.lu/attributes/downloadSample                                     │
{"request": {"hash": "6e230bb92d2721efc5971f9b887cf5dc", "eventID": null, "allSamples": false}}│
```

@iglocska: do you have an idea?

**Comment by Rafiot** [comment]
Confirmed fixed by https://github.com/MISP/MISP/commit/f19a3a7c1b65f9c1b01f29017166d0517e338512
