### ISSUE TITLE
Sort events by date

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#2637]
Is it possible to configure the web interface to always sort the events by latest date (earliest date) on the List Events Tab? so that i do have to manually do it by clicking the Date heading when i open the List Events page

**Comment by iglocska** [comment]
`https://yourmisp/events/index/sort:date/direction:desc`    <- bookmark
this.

Keep in mind this is the arbitrary date set by users. By default the events
are sorted by the timestamp of last edit.
