### ISSUE TITLE
Cannot create cache directory var/www/.composer/cache , or directory is not writable

### ISSUE THREAD

**Issue by picodulce01** [MISP/MISP#2646]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  Bug
| OS version (server)       | Debian 9
| PHP version               |  php 7.0
| MISP version / git hash   | 2.4.82

Hello!

I am installing MISP following this guide:

https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian9.txt

But I have a problem on line 97.

`sudo -u www-data php composer.phar require kamisama/cake-resque:4.1.2`

When I write this command, it gives me a error:

sudo -u www-data php composer.phar require kamisama/cake-resque:4.1.2
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
./composer.json has been updated
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

All the previous steps indicated in the guide were carried out without problem

I'm confused, because I don't have and there isn't a folder. "var/www/. composer"

xxx@misp:/var/www$ ls -blah
total 16K
drwxr-xr-x  4 root     root     4.0K Nov 16 17:39 .
drwxr-xr-x 12 root     root     4.0K Nov 16 17:37 ..
drwxr-xr-x  2 root     root     4.0K Nov 16 17:37 html
drwxr-xr-x 13 www-data www-data 4.0K Nov 16 17:40 MISP

What am I doing wrong? Or is it a problem with the installation guide?

Thanks!

**Comment by RichieB2B** [comment]
You are running the command as www-data but /var/www is owned by root. Make it owned by www-data using the chown command.

**Comment by picodulce01** [comment]
¡Thanks! Work perfect! :+1:
