### ISSUE TITLE
can't assigne galaxy

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2648]
When you create new role with "tagger" but not "tag editor", user can't assigne a galaxy to an event.

It would be interesting, as for taxonomies, to create all the corresponding tags during an update.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| MISP version  | 2.4

**Comment by adulau** [comment]
I suppose this was fixed long time ago. Feel free to reopen if needed.
