### ISSUE TITLE
OpenIOC import issue with multiple layers

### ISSUE THREAD

**Issue by dewiestr** [MISP/MISP#265]
While importing OpenIOC, it seems that MISP does not import beyond one layer of AND/OR. 

I used this ioc as an example: 
http://iocbucket.com/iocs/fba1534f03a74e43b7aa64774278edbc6c9b507a

**Comment by mgeorgy** [comment]
I believe I've run into this issue recetnly trying to import FireEye's APT30 IOC list (https://github.com/fireeye/iocs/blob/master/APT30/eeffc8e8-caee-4fe1-8ace-7a994b5d893f.ioc) and receiving several error, all appear to be within embedded AND/OR tags.  Is this issue still under review or shall I accept this as an acknowledged limitation of MISP?

**Comment by Rafiot** [comment]
Status?

**Comment by adulau** [comment]
As discussed, we should made the default OpenIOC import (available in PyMISP) the default one instead of the old version to make it accessible to all users.

**Comment by iglocska** [comment]
This is more of a misp modules question at this point, closing.
