### ISSUE TITLE
Caching not working properly on some feeds

### ISSUE THREAD

**Issue by rmeghnagi** [MISP/MISP#2652]
Hi,

i have installed the last version (v 2.4.82) of MISP Vmware Virtual Image. When i try to start cache feed on some feed, the job resulted "Completed" but feed show "Not cached" and in "Feed overlap analysis matrix" i don't view this feed. 

Could you help me?

Thanks in advance!
R.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Support.
| OS version (server)       | Ubuntu .
| OS version (client)       | 10.
| PHP version               | 7.1.
| MISP version / git hash   | 2.4.82
| Browser                   | IE and Chrome.

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/33800950/32989194-1b0e2d54-cd12-11e7-8fee-2910bd5bc0e7.png)

![image](https://user-images.githubusercontent.com/33800950/32989197-26c37456-cd12-11e7-8ed5-903dc1caa34d.png)

![image](https://user-images.githubusercontent.com/33800950/32989198-2d2370bc-cd12-11e7-9c26-73bedbc657ec.png)

**Comment by adulau** [comment]
This should be fixed now in https://github.com/MISP/MISP/commit/a5ceed1522c5cd41a8a5a9661f159aef3eb49ca3 Feel free to reopen if the issue persists.

**Comment by dmolina213** [comment]
I have similar issue but in RHEL7. Is that fix also in RHEL ?
