### ISSUE TITLE
MISP Intel Feed

### ISSUE THREAD

**Issue by MarkWard123** [MISP/MISP#2658]
I am trying to feed Intel into MISP from a popular paid intel provider. This intel is being extracted in JSON format but it is not accepted by MISP due to it not being in MISP JSON format. Does anyone know of a way I can convert the data into MISP JSON?

**Comment by cvandeplas** [comment]
If you can provide us with an export of this vendor's JSON file, we might be able to look into it.

**Comment by adulau** [comment]
@MarkWard123 Any news on this? We would be glad to help if you could provide the original format. Feel free to reopen the issue when you'll get the data. Thank you.
