### ISSUE TITLE
"batch tagging" not working properly

### ISSUE THREAD

**Issue by imereau** [MISP/MISP#2675]
Dears,

Minor bugs:
- When selecting multiple attributes for tagging, the tags are sometimes "hidden" in the UI until the page is F5'd. 
- Removing a tag reveals another one hidden behind. 
- Also, when playing with tag, sometimes a login screen is displayed in the middle of the UI. Refreshing the page fixes the issue, so this is all minor, but not very user-friendly.

Feature request:
- It would also be very handy to be able to select multiple tags at once to add to a set of attributes. Currently, you need to re-select all your attributes you want tagged again when you want to add multiple tags.

Thanks a lot in advance!

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)   |    ubuntu
| OS version (client)      | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.82, f19a3a7c1b65f9c1b01f29017166d0517e338512
| Browser                   | FF 47.0.1

**Comment by mokaddem** [comment]
Hi!
This feature is now live on the latest version of MISP.
Enjoy!
