### ISSUE TITLE
Failing to run Sync Test behind SSL proxy

### ISSUE THREAD

**Issue by cgi1** [MISP/MISP#2677]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  Support
| OS version (server)       | Ubuntu ([VmWare Image](https://www.circl.lu/misp-images/latest/MISP_v2.4.82@ff5a8ac80283d395203ca7b95a986158fe33e3c3-vmware.zip))
| OS version (client)       | *
| PHP version               | ?
| MISP version / git hash   | 2.4.82
| Browser                   | *

### Expected behavior

Synchronization Test is running behind HTTP/s proxy

### Actual behavior

Synchronization Test fails behind HTTP/s proxy

### Steps to reproduce the behavior

- Install MITM SSL proxy (e.g. mitmproxy)
- Configure proxy in MISP --> Server settings --> Proxy
- Configure a sync server --> Run Connection Test 
- Log is showing `Unable to perform enableCrypto operation on Cakesocket`

### Logs, screenshots, configuration dump, ...

- proxy check in Diagnostics is OK
- Download of events from pre-configured feeds are working as expected (so the proxy configuration is correct)
- Looking into tcpdump we see that the certificate chain is getting delivered, but the 'Host' field is set to the hostname of the proxyserver (not the hostname of the server). Is MISP validating if it is identically?

**Comment by adulau** [comment]
Is this issue solved? I'll close the issue but feel free to reopen if the issue persists with recent version.
