### ISSUE TITLE
last don't work

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#2681]
try to grab last event created/modified don't work.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | last https://github.com/MISP/MISP/commit/f9de35ddf656bf62d43794602552d8494c186844
| Browser                   | curl, pymisp

### Expected behavior
return last event created or modified

### Actual behavior
return nothing
```bash
{
    "response": []
}
```

### Steps to reproduce the behavior
create a new event or edit an old

### Logs, screenshots, configuration dump, ...
No error displayed :(

**Comment by truckydev** [comment]
I try to debug in Event model / resolveTimeDelta for **last='5d'**
```php
		$return = time() - ($delta * $multiplier);
		CakeLog::write('debug', print_r($return, true));
		return $return;
```
the result seems to be correct _1511087830_

**Comment by 0xffca** [comment]
I had the same issue with PyMISP, maybe it helps:
https://github.com/MISP/PyMISP/issues/140

**Comment by iglocska** [comment]
Will take a peak after lunch!

**Comment by iglocska** [comment]
Just tested it, works on my end just fine. Are the events that you are trying to match published? "last" uses the last publish timestamps.

**Comment by iglocska** [comment]
Should have looked at @0xffca's link first ;)

**Comment by truckydev** [comment]
Ho ok it's all my bad 
I misunderstood the function: (
for me (and other ^^)
'last' should return new event or edited event

but here last is for **latest published** event ...

When I play with published it work
Maybe change last to last_publish or add latest something like that ...

**Comment by iglocska** [comment]
The reason why it uses the publish timestamp is simple: If I get a new event into my instance that I haven't had before via the sync, the timestamp might be old and my daily "last":"24h" filter rule would never export it. This way we can make sure that recurring incremental fetches will get ALL published data into your SIEM/IDS/etc ;)

**Comment by truckydev** [comment]
I understand :)

Thanks for you comment ^^
