### ISSUE TITLE
Adding proposal to different org event couses error

### ISSUE THREAD

**Issue by dawid-czarnecki** [MISP/MISP#2685]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       | RedHat
| OS version (client)       | 7
| PHP version               | 7
| MISP version / git hash   | 2.4.82
| Browser                   | Firefox 55.0

### Expected behavior
HTTP 200 with html code of form

### Actual behavior
```
HTTP 404
Invalid attribute
...
The requested address <strong>'/attributes/fetchEditForm/123123/to_ids'</strong> was not found on this server.
```

### Steps to reproduce the behavior
If you try to propose edition to other's organization attribute it will return an error:
[https://localhost/attributes/fetchEditForm/123123/to_ids](url)

**Comment by iglocska** [comment]
Nice catch, the event attribute UI rework has a copy pasta error. It's
directing you to the attribute edit form which you are not allowed to use
as a user of a different org. Will push a fix today, thanks for the
heads-up ;)
