### ISSUE TITLE
Import from MISP Export fails

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2686]
Using the latest, greatest MISP version (2.4.82 w/ a fresh git pull) I'm trying to import a large JSON file, exported from another MISP instance. The JSON file size is 1475541995 bytes (1.4G) but no events are being imported at all. After some 30 seconds the GUI shows:

![1](https://user-images.githubusercontent.com/25325656/33269562-6ec16374-d381-11e7-8572-87f9ee3bb0f6.png)

and there's no clues whatsoever within app/tmp/logs/

Is there a max file size for importing JSON files?

**Comment by Rafiot** [comment]
So yeah, PHP has a upload_max_filesize value. You can find it here: https://<URL>/servers/serverSettings/diagnostics
The default recommended value is 50M.

You could make it 2G, and hope for the best, but first of all: the huge JSON file, is it one single event, or many? If it is many, I'd recommend you to export them as individual events as json file and use a script to add them on the new instance.
If it is one single event, please let us know and we will find an other solution.

**Comment by StefanKelm** [comment]
Thanks a lot, @Rafiot, for the quick reply. Apologies for the noise, I should have checked the serverSettings myself...

BTW, the JSON file contains a few thousand events. It was created using MISP's export functionality (generate JSON file, then download).

**Comment by Rafiot** [comment]
Ok, makes sense. It is generally not recommended to export/import this way because the file is huge and it will take forever to import. 

If it is an option, using either the sync server option, or exporting all the event with a script and reimporting them one by one via the API is better.

**Comment by iglocska** [comment]
The MISP export functionality is crap for ingesting it this way. The feed
generator is much better, I'll look into including that format directly in
the application so we don't have to use the external script.

**Comment by StefanKelm** [comment]
Agreed, thanks for the feedback. I was just testing this functionality and do not intend to sync servers that way... ;-)

However, it might make sense to alert the user if she tries to import a file larger than upload_max_filesize.
