### ISSUE TITLE
ssdeep computation on attachment upload

### ISSUE THREAD

**Issue by imereau** [MISP/MISP#2690]
Dears,

When uploading an attachment to an event as e.g. "Payload Delivery", it automatically computes md5, sha1 and sha256 of the attached file, which is great.
I was wondering if there was a way to add ssdeep to the list of automatically computed hashes. I had a look at the file object definition, but it doesn't seem to be a setting. I guess it's in the code itself (I didn't really crawl the code to find out).
If there is no such feature, would you consider it as a feature request?

Thanks for your advice!

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)   |    ubuntu
| OS version (client)      | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.82, f19a3a7c1b65f9c1b01f29017166d0517e338512
| Browser                   | FF 47.0.1

**Comment by iglocska** [comment]
Install dependencies for the advanced attachment import and you'll get ssdeep, PE information etc ;)

**Comment by imereau** [comment]
Hello,

Yes, I know :-)
All dependencies for advanced attachment handler are installed. But when I upload an attachment with "advanced extraction" option, I still don't get ssdeep. Most probably I am missing something but I am  not sure what exactly.. If you could point me to it, it would be great.
Couldn't find any indication in the log files either.

Many thanks again!

![adv_attach_1](https://user-images.githubusercontent.com/8105737/33363906-98e16ebc-d4e2-11e7-9f6c-14ee0cfd6283.png)
![adv_attach_2](https://user-images.githubusercontent.com/8105737/33363907-99078b60-d4e2-11e7-9456-466e4c3e95d8.png)
![adv_attach_3](https://user-images.githubusercontent.com/8105737/33363908-99267106-d4e2-11e7-9804-88739c8c4b88.png)
![adv_attach_4](https://user-images.githubusercontent.com/8105737/33363909-9948aafa-d4e2-11e7-9a27-9f1d67a26ecd.png)

**Comment by imereau** [comment]
Dears,

Would you have any news on this one? I would just like to understand whether there is something wrong with my setup or if this is a bug (and if so, if it is going to be fixed).

I know you have a lot to do, really appreciate your time.

thanks a lot in advance!

BR's
irving

**Comment by iglocska** [comment]
The advanced attachment upload is for executables, it can't extract stuff
from a png ;) Give it a shot with an executable.

**Comment by iglocska** [comment]
OK, my bad, it might not be that at all. But could you try with an
executable just in case? It might be that we hand back control to the
default attachment handler if it's not an executable too early without
getting the ssdeep - or alternatively the additional extractions aren't
working at all on your end.

**Comment by imereau** [comment]
OK. I tried with an exe file, it also doesn't work for me.
Besides, ssdeep is just the hash of the file, it shouldn't matter whether it's an executable or not; malware can be embedded in a wider set of extensions than only executables and these are also IOC's you may want to share.

**Comment by iglocska** [comment]
The reason I asked was that the advanced extraction extracts everything from PE headers to a bunch of additional information - if it was only ssdeep that was broken or something on your setup. I need to check why the diagnostics is reporting it incorrectly.

**Comment by imereau** [comment]
ok, I understand. Just let me know if you figure it out..:-)

Thanks a lot!

**Comment by iglocska** [comment]
Will do!

**Comment by wroersma** [comment]
so I installed these packages via pip but I still don't have them showing up in misp? any hints to what's wrong there?

**Comment by SteveClement** [comment]
@wroersma is this still an issue for you?
@imereau I guess you might have moved on :)

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
