### ISSUE TITLE
Improvement Visual: Graph for objects relationships

### ISSUE THREAD

**Issue by c-goes** [MISP/MISP#2696]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.0
| MISP version / git hash   | 2.4.82
| Browser                   | If applicable

### Expected behavior

Similar to *View Correlation Graph* there could be another graph that shows how the objects are related to each other.

**Comment by iglocska** [comment]
Yeah this one is on the roadmap and a pretty big deficiency until we have
it ;)

**Comment by adulau** [comment]
Released in 2.4.89
