### ISSUE TITLE
email import module gives issues with malware-sample

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2698]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | MISP training VM.
| MISP version / git hash   | 2.4.82
| Browser                   | If applicable

### Actual behavior
- populate from > email import
- chose an email eml file containing mail + attachments
- upload
- on the triage screen leave as it is, press "submit"
- the small "please wait circle" appears, it disappears again, but stays on the same page
- the attributes are imported
- the malware-sample is NOT imported

**Comment by cvandeplas** [comment]
The error log reports "invalid filename" , however I believe this is not the only problem preventing the malware-sample to be uploaded.

**Comment by adulau** [comment]
If you are using the misp-modules on the MISP training VM, did you update the modules? 

~~~~
sudo apt-get install python3-dev python3-pip libpq5 libjpeg-dev
cd /usr/local/src/
sudo git clone https://github.com/MISP/misp-modules.git
cd misp-modules
sudo pip3 install -I -r REQUIREMENTS
sudo pip3 install -I .
sudo vi /etc/rc.local, add this line: `sudo -u www-data misp-modules -s &`
misp-modules #to start the modules
~~~~

By the way, the new VMs are available there and automatically generated at the following location:

https://www.circl.lu/misp-images/latest/

Credentials are https://www.misp-project.org/download/#virtual-images

Could you test with recent version?

**Comment by cvandeplas** [comment]
This was with the VM MISP_v2.4.82@5f293912fc677ebf93696a5c94fff5b5f316e437.  (14 Nov)
I have manually updated the misp-modules with the latest git.
MISP 2.4.82

the behavior is the same

**Comment by adulau** [comment]
@cvandeplas Thank you for the test. I will investigate.

**Comment by cvandeplas** [comment]
If you remove the malware sample from the triage window, import works fine.
I believe there is something wrong with the malware-sample processing, as I encountered this issue with a new module I'm working on, using the same code to import a malware-sample.
