### ISSUE TITLE
Allow boolean conditions between attributes

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#27]
Reported by David André, Jul 10, 2012

AND/OR/NOT operators

Would allow more complex detection logic, and syntax to filter out a 
part of False Positive in one of the patterns is something common.

For NIDS generated, it would allow to create mini rules-sets using 
flowbits

Related to Issue 10 and Issue 8 (openIOC import/expot).

Downside is that it might need some heavy 
re-engineering/modification.

Comment 1 by David André, Jul 10, 2012

It would also allow export to rules that can be easily imported 
& applied in SIEMs

Comment 2 by Andrzej Dereszowski, Jul 26, 2012

Good suggestion but this could be a bigger piece of work. You want 
to create something like OpenIOC editor. It might require 
re-modeling the database to implement tree structured data ...

Comment 3 by David André, Jul 26, 2012

If MAEC (Malware Attribute Enumeration and Characterization - 
http://maec.mitre.org/) export/import is also considered, the same 
kind of re-engineering would also be required.

**Comment by iglocska** [comment]
Semi resolved via objects. We'll keep it as it is for now and see if we ever need more.

**Comment by adulau** [comment]
Indeed. Maybe [relationships](https://github.com/MISP/misp-objects/blob/master/relationships/definition.json) could be reviewed to cover specific cases.
