### ISSUE TITLE
UI Feedlist Link Broken

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#2703]
A look at the latest release when the feed list populates for an event the URL is missing the slash in the URL link under related feeds. Very minor but wanted to let you know. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | NA
| PHP version               | 7.0
| MISP version / git hash   |  v2.4.82 (840b79e6415c8207c3237df5f36e0b7ae30f938e)	
| Browser                   | If applicable

### Expected behavior
Expect link to point to the feed

### Actual behavior
Link is not the correct link to view feed data

**Comment by iglocska** [comment]
Nice catch, thanks!

**Comment by iglocska** [comment]
Fixed a while back, thanks again.
