### ISSUE TITLE
Improvement on Event Blacklist (Bulk delete option request)

### ISSUE THREAD

**Issue by maraboutingermany** [MISP/MISP#2705]
Currently running Version 2.4.82, and having dealt with some distributions setting issues on a larger data set which caused a lot of data to be sent while it should not have, I think it would be useful to add a bulk edit option on the Event blacklist to delete multiple Blacklisted events at the same time, right now this is manually deleting one by one line

**Comment by eCrimeLabs** [comment]
I would also love to see this feature as well :)
