### ISSUE TITLE
freetext import incorrectly assigns domains/hostnames as filenames when TLD warninglist does not exist

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2708]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       | ubuntu, 
| PHP version               | training VM
| MISP version / git hash   | MISP 2.4.82

### Expected behavior
The triage screen shows as category "network activity" > "hostname" as default.

### Actual behavior
The triage screen shows "Payload delivery" as default category and some other file-related categories as options and the type is fixed to "filename"

### Steps to reproduce the behavior
- make sure the TLD warninglist does not exist
- open an existing event
- click on the "freetext import tool button"
- type "www.helloworld.be" as text
- see it's recognised as filename
- update the warninglists to have the TLD there, try again, you will see it's working as it should

Potential solution:
- make sure warning lists are automatically pre-filled at first use of MISP.
- or update the freetext code to correct the behavior

**Comment by adulau** [comment]
@iglocska Reminder from the training in Prague.

**Comment by adulau** [comment]
Fixed in 0df15f03e1f1f8f9f865d5ca469b579faaa68fe2
