### ISSUE TITLE
GPG Key in user profile not accepted

### ISSUE THREAD

**Issue by coenemichel** [MISP/MISP#271]
Hello all,

Since the upgrade to MISP version 2.2, it looks like GPG key's are no longer accepted, also the ones that were already validated before the upgrade are no longer accepted. The MISP platform is recently updated applying the newest bug fixes, but this did not resolve the issue.

Is anyone else experiencing the same issue?

Kind regards

**Comment by elhoim** [comment]
Is it fixed?
