### ISSUE TITLE
How MISP can I translate it into Czech?

### ISSUE THREAD

**Issue by jpm7** [MISP/MISP#2710]
Please, Misp will also be available in Czech localization? 
If not, how can I translate it into Czech?

**Comment by adulau** [comment]
@jpm7 We have an ongoing translation project. @SteveClement is working on it. There are some work needed in MISP regarding the string value type. It would be great to one in Czech too ;-)

**Comment by SteveClement** [comment]
Dear @jpm7 we have merge our i18n branch today.

Here you see the PO Templates: https://github.com/MISP/MISP/tree/2.4/app/Locale
The most widely used PO editor seems to be this one: https://poedit.net/

A first read would be this:

https://book.cakephp.org/2.0/en/core-libraries/internationalization-and-localization.html

More details about translations under the hood: https://book.cakephp.org/2.0/en/core-libraries/behaviors/translate.html (FYI only)

For the sake of completeness here is more documentation about the cake i18n shell: https://book.cakephp.org/2.0/en/console-and-shells/i18n-shell.html

Important: Please add a translation file to the misp-book repository.
Here are some instructions: https://github.com/MISP/misp-book/tree/master/translation

Thanks for your future contribution.
/cc @adulau
