### ISSUE TITLE
Sync User Explore Remote Server

### ISSUE THREAD

**Issue by cipherlock** [MISP/MISP#2713]
From Sync Actions->List Servers->Server Name->Explore, a user can use the Explore Remote Server feature to view all of the data on the remote MISP instance and not just what is allowed as part of a sharing group.

Is there a way within MISP to restrict what a user is able to view from the Explore Remote Server feature?

**Comment by iglocska** [comment]
Is the remote user the correct organisation and role? It sounds like the remote user is not the right org or a site admin. (Just tested with a correctly set up sync connection and it's not possible to see events remotely that I am not supposed to see)

**Comment by cipherlock** [comment]
Thanks! I only had one org setup but after creating a second sync user org and moving the sync users into that org I was no longer able to remotely browse the events.

**Comment by iglocska** [comment]
Perfect ;) Thanks for the feedback!
