### ISSUE TITLE
Warninglist contains no values

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2717]
Using 2.4.82 I'm having this strange issue that one (and only one) of the warninglists is displayed as being empty:

![auswahl_002](https://user-images.githubusercontent.com/25325656/33723031-cef344c8-db6b-11e7-841f-2658f4fa7efb.png)
![auswahl_001](https://user-images.githubusercontent.com/25325656/33723036-d20e54d6-db6b-11e7-844c-a124d92d6898.png)

However, on the file system level everything at .../app/files/warninglists/lists/... is exactly as on github. Enabling/disabling that particular warninglist doesn't lead to any changes.

error.log contains **many** of the following entries:

```
2017-12-06 10:59:57 Warning: Warning (2): in_array() expects parameter 2 to be array, null given in [/services/inst/misp/app/Model/Warninglist.php, line 238]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
in_array - [internal], line ??
Warninglist::checkForWarning() - APP/Model/Warninglist.php, line 238
Event::__prepareGenericForView() - APP/Model/Event.php, line 3379
Event::__prepareAttributeForView() - APP/Model/Event.php, line 3239
Event::rearrangeEventForView() - APP/Model/Event.php, line 3413
EventsController::viewEventAttributes() - APP/Controller/EventsController.php, line 829
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by adulau** [comment]
Hmmm interesting. I tried to reproduce it but without luck.

Could you do the following (just to be sure):
~~~~
cd app/files/warninglist
git reset --hard
cd ../../..
git submodule update
~~~~
and then update the warninglist.

Let me know if you have any strange error.

**Comment by adulau** [comment]
Did you try?

**Comment by StefanKelm** [comment]
We just did try. There we no changes on the file system level, so updating the warninglists didn't change anything either...

**Comment by StefanKelm** [comment]
We're still having problems with this single warninglist, even after having upgraded to 2.4.84 and rebooted the system...

Since the corresponding _list.json_ file is by far the largest of any warninglist can this be a memory problem? Hints anyone?

**Comment by iglocska** [comment]
Sorry missed this issue completely. It sounds like something failed while import, so you've ended up with an empty warninglist. It could indeed be a memory issue, timeout, etc. The biggest issue we have is we don't have a delete button for the empty list - I'll look into adding that so you can reload it. 

In the meanwhile simply go to mysql and run the following:

```
delete from warninglists where id ='9';
```

Assuming it's still on ID = 9.

Update the warninglists again after.

**Comment by StefanKelm** [comment]
Thank you! We successfully deleted the warninglist (it disappeared from the GUI). However, when updating via the GUI the browser displayed a strange error message (didn't make a screenshot unfortunately).

_error.log_ shows

```
2017-12-22 10:06:22 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /warninglists/update
Stack Trace:
#0 /services/inst/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /services/inst/misp/app/Model/Warninglist.php(96): Mysql->insertMulti('warninglist_ent...', Array, Array)
#2 /services/inst/misp/app/Model/Warninglist.php(62): Warninglist->__updateList(Array, Array)
#3 /services/inst/misp/app/Controller/WarninglistsController.php(37): Warninglist->update()
#4 [internal function]: WarninglistsController->update()
#5 /services/inst/misp/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(WarninglistsController), Array)
#6 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /services/inst/misp/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(WarninglistsController), Object(CakeRequest))
#8 /services/inst/misp/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}


2017-12-22 10:06:22 Warning: Warning (2): Error while sending QUERY packet. PID=14214 in [/services/inst/misp/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 470
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 436
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 673
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1184
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3038
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3010
AppModel::__runCleanDB() - APP/Model/AppModel.php, line 1058
AppModel::runUpdates() - APP/Model/AppModel.php, line 1017
AppController::beforeFilter() - APP/Controller/AppController.php, line 253
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

```

Afterwards the warninglists shows up again on the GUI w/ a new id but still empty...

Perhaps _max_allowed_packet_ is a clue?

**Comment by iglocska** [comment]
It is indeed. Insertmulti will create a single query with a large number of values - this seems to be too large for your max allowed packet directive for mysql. Will look into a way of cutting it down.

**Comment by iglocska** [comment]
Just pushed a potential fix for it. 

1. It now chunks the insert into 1k values at a time
2. You can delete warninglists from the UI
3. Some pretty massive performance gains too

**Comment by adulau** [comment]
The nameserver warning-list is now split between ipv4 and hostname representation. don't forget to do a git submodule update too ;-)

**Comment by iglocska** [comment]
And do it again please for some further changes ... ;)

**Comment by StefanKelm** [comment]
Once again, you're awesome guys! All warninglists are now up and running. :-)

**Comment by iglocska** [comment]
Excellent, thanks for the feedback B-)
