### ISSUE TITLE
Pdfexport always creates empty PDF files

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2718]
...the subject says it all (2.4.84 w/ a fresh git pull)

debug.log contains

```
2017-12-07 16:03:22 Notice: Notice (8): Undefined index: data in [/services/inst/misp/app/Model/Event.php, line 3597]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Event::export() - APP/Model/Event.php, line 3597
EventsController::exportModule() - APP/Controller/EventsController.php, line 4319
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

```

**Comment by adulau** [comment]
PDF export? This is a new feature that doesn't know in the current version of MISP.

Is this an external MISP module?

Thank you

**Comment by StefanKelm** [comment]
Well, I just set _Plugin.Export_pdfexport_enabled_ to true and then tried to export as pdf:

![pdfexport](https://user-images.githubusercontent.com/25325656/33724956-16157a7e-db71-11e7-89de-e66b3f34f7f7.png)

:-)

**Comment by iglocska** [comment]
Uhhhhhh. When did we get that? Awesome!

**Comment by adulau** [comment]
It seems I overlooked the recent update from @Rafiot in the modules.

https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/export_mod/pdfexport.py

It seems a very alpha module. But I suppose you are missing `asciidoctor` and `asciidoctor-pdf`. Have you installed it?


`gem install asciidoctor`
`gem install asciidoctor-pdf`

**Comment by StefanKelm** [comment]
not yet...  ;)

**Comment by StefanKelm** [comment]
This has been resolved. :+1:
