### ISSUE TITLE
XML exports do not validate against the DTD file anymore.

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#272]
Example:

`from lxml import etree                       
tree = etree.parse("event.xml")    
etree.DTD(open('misp_xml_format.dtd', 'rb'))
print dtd.validate(tree)
False`

**Comment by Rafiot** [comment]
Not sure the XML export is particularly maintained nor if we want to spend time on it.

**Comment by iglocska** [comment]
The more people switch to json the better

**Comment by Rafiot** [comment]
we will have to close it or fix it by 2.5, or move the Milestone :)

**Comment by yohonet** [comment]
Another note: the generated XML can get invalid if you have manually entered values representing XML data or characters. Characters < and > are replaced by "& l t ;" and "& g t ;" from time to time but not always. I would consider using CDATA when exporting manually entered values (if XML export is not declared deprecated).

**Comment by iglocska** [comment]
That sounds indeed like a much more sane option. I'll look into converting the string fields to CDATA.

**Comment by yohonet** [comment]
Some little update: the XML appears to be valid again in 2.4.51. When an attribute is using "<" for instance, it's correctly translated to "& l t ;" (without the spaces). It was not the case before everytime, I've been able to compare an example side to side. However, it's not using CDATA.

**Comment by yohonet** [comment]
hmm, my comment doesn't show up as it's intended to. I meant that "<" is correctly translated to "& l t ;" (without the spaces)

**Comment by iglocska** [comment]
XML is deprecated, unless there is an actual bug with them we don't care too much - especially for validating against the schema.
