### ISSUE TITLE
Reverse sort order in Event List view

### ISSUE THREAD

**Issue by keram79** [MISP/MISP#2723]
Currently clicking on the table header e.g. in the Event List view creates an ascending view, i.e. when clicking on "date" the oldest event is on top, when clicking on event ID the event with the lowest ID is on top.

I propose to switch the behaviour, so that by default the newest events are displayed first, because they are usually the most interesting.

**Comment by SparkyNZL** [comment]
I think it would be nice to be able to set a sort order, at the moment when ever im in the event list view i have to click the date field twice (every time) and if i edit an event, i have to click it twice again. Is there any way to set this to sort on date by default ?

It seems super trivial , but DAMN its annoying ! :)

**Comment by adulau** [comment]
It's indeed a very good point. I'm sure our Q&A engineer @rommelfs will agree on this? ;-)

**Comment by iglocska** [comment]
Yeah, it was frustrating as hell.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/3d8e8039fa7920a96f65a89de2dd141382e22fe0

**Comment by SparkyNZL** [comment]
Youre awesome ! :)
