### ISSUE TITLE
Double clicking settings, gets spinning 'loading' wheel

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#2727]
## Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL 7.4
| OS version (client)       | Windows 7
| PHP version               | 5.6,
| MISP version / git hash   | 2.4.82,
| Browser                   | Firefox 52.5.0 ESR, Google Chrome 61.0.3163.100

### Expected behavior
Able to double click a server setting and be able to change it.

### Actual behavior
Just get a spinning 'loading' wheel and not able to change the settings.

### Steps to reproduce the behavior
Double click any setting within the server settings window.

### Logs, screenshots, configuration dump, ...

![2017-12-11 10_06_21-clipboard](https://user-images.githubusercontent.com/1779665/33810621-132cbbd2-de5b-11e7-9736-1fe5761b72b0.png)

**Comment by bluebiscuitz** [comment]
I'm having the exact same issue running on rhel 7.4 and MISP 2.4.84. 
Double clicking any setting results in a loading spinning wheel.

If it would help the devs at all, my /var/www/MISP/app/tmp/logs/error.log has the following:

```
2017-12-11 22:44:33 Error: Fatal Error (1): Call to undefined function opcache_reset() in [/var/www/MISP/app/Controller/ServersController.php, line 950]
2017-12-11 22:44:33 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettingsEdit/MISP.host_org_id/3?_=1513032255402
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 950)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 950, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 950, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

```

**Comment by jezkerwin** [comment]
@bluebiscuitz what version of PHP are you using? I'm using PHP 7.1 from SCL. I'm wondering if the opcache_reset() isn't in 7.1

**Comment by bluebiscuitz** [comment]
@jezkerwin I followed the centos7 install guide without any changes so I should be running 5.6

**Comment by jezkerwin** [comment]
Hmmm.... scratch that idea then. Must of been something that came with the latest update.

**Comment by jezkerwin** [comment]
I think I've figured it out.

Since I'm using Software Collections I think I fixed my issue by the following and restarting.

`yum install rh-php71-php-opcache`

If you're using the EPEL repository, perhaps the following might work.

`yum install php-opcache`

I can edit the settings now.

**Comment by bluebiscuitz** [comment]
Hey! Looks like that did it! In my case

`yum install rh-php56-php-opcache`

fixed the issue.

**Comment by iglocska** [comment]
Thanks for the heads-up, will have a fix for future occurances of this
issue momentarily.
