### ISSUE TITLE
Cannot edit server settings 

### ISSUE THREAD

**Issue by zachsis** [MISP/MISP#2738]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS7 
| OS version (client)       | Tested on Fedora 25 and windows 10
| PHP version               | 5.6.25
| MISP version / git hash   | 2.4.84
| Browser                   | If applicable

### Expected behavior
Should be able to edit the settings .

### Actual behavior
Loading graphic just spins and stack trace error is dumped to error.log

### Steps to reproduce the behavior
Follow the install here: https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt
Then go into server settings, and try to edit a setting in there. 

### Logs, screenshots, configuration dump, ...
```
==> error.log <==
2017-12-13 14:03:04 Error: Fatal Error (1): Call to undefined function opcache_reset() in [/var/www/MISP/app/Controller/ServersController.php, line 950]
2017-12-13 14:03:04 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettingsEdit/MISP.live/1?_=1513198934505
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 950)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 950, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 950, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

```

**Comment by adulau** [comment]
You are missing the opcache module or/and it's not enabled. 

Maybe installing the opcache module (depending of your version of PHP) would help.

`yum install rh-php71-php-opcache`
`yum install php-opcache`
`yum install rh-php56-php-opcache`

I'll close the issue but don't hesitate to reopen it if this is not solving the issue.
