### ISSUE TITLE
LIEF installation on RHEL

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#2740]
I'm going through the diagnostic page on my RHEL 7 instance. I'm getting the following error

"lief:..... Please install lief, documentation here: https://github.com/lief-project/LIEF"

Following the documentation on the lief website. I installed the package by executing 

"pip install lief" 
 
which was successful.

The error still remains when running the diagnostics again.
Any idea how to resolve this?

**Comment by syloktools** [comment]
sudo pip3 install lief


Thanks,
Robert

**Comment by jezkerwin** [comment]
I'm using Python2.7, not Python3

**Comment by syloktools** [comment]
I believe that most of the modules require 3. Could be wrong but that was my problem.

**Comment by StefanKelm** [comment]
Same over here. Even successfully using _pip3 install lief_ doesn't change the message on the diagnostics page.

UPDATE: I had to upgrade pip on my system: `pip install --upgrade pip`
Afterwards the diagnostics page doesn't complain anymore (I'm running Ubuntu 16.04.03 though).

**Comment by syloktools** [comment]
Try sudo pip2 install lief, to force it to use Python 2.7

 

I had to add –trusted-host github.com also since I am behind a SSL intercepting, pain in the rear, proxy

 

Robert

**Comment by jezkerwin** [comment]
The issue with me, isn't the installation. The installation works fine. It's the fact that the diagnostic page in MISP doesn't recognise that it's installed.

**Comment by RichieB2B** [comment]
@jezkerwin Can you share how you solved this?

**Comment by jezkerwin** [comment]
Sure can @RichieB2B .

I was going to write the instructions in a different issue.

**Comment by jezkerwin** [comment]
@RichieB2B Here are the instructions I wrote.

#2743 Install steps for LIEF on Red Hat Enterprise 7.4

**Comment by RichieB2B** [comment]
Great, thanks!
