### ISSUE TITLE
Install steps for LIEF on Red Hat Enterprise Linux 7.4

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#2743]
These are the steps that I took to install the lief library under Red hat Enterprise Linux 7.4.

0) Assumptions
Red Hat Enterprise Linux 7.4 (can be adapted for CentOS)
Python 2.7
SCL Repository 

1) Install Dependencies
* Enable the SCL repository
`subscription-manager repos --enable rhel-server-rhscl-7-rpms`
* Install git cmake3 devtoolset-7
`yum install devtoolset-7 cmake3 git`
*Enable SCL devtoolset-7
`scl enable devtoolset-7 bash`

2) Set some environment variables and download LIEF source code
```
mkdir -p /tmp/LIEF
mkdir -p /tmp/LIEF_INSTALL
export LIEF_TMP=/tmp/LIEF
export LIEF_INSTALL=/tmp/LIEF_INSTALL
export LIEF_BRANCH=master
cd $LIEF_TMP
git clone --branch $LIEF_BRANCH --single-branch https://github.com/lief-project/LIEF.git LIEF
```
3) Compile LIEF and install
```
cd $LIEF_TMP/LIEF
mkdir -p build
cd build
scl enable devtoolset-7 'bash -c "cmake3 \
-DLIEF_PYTHON_API=on \
-DLIEF_DOC=off \
-DCMAKE_INSTALL_PREFIX=$LIEF_INSTALL \
-DCMAKE_BUILD_TYPE=Release \
-DPYTHON_VERSION=2.7 \
.."'
make -j3
cd api/python
python setup.py install || :
cd $LIEF_TMP/LIEF/build
make install
make package
```

4) Testing
* Open a Python interpreter
* Import the lief library, if no errors, assuming the library installed.
`import lief`
* Run MISP diagnostics and confirm that lief is reported as installed.

**Comment by jezkerwin** [comment]
#2740

**Comment by adulau** [comment]
Great feedback! Thank you very much.

Do you think it would be interesting to update the current [CentOS 7 install guide](https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt) with your procedure?  or would it be better to make a new one for RHEL?

**Comment by jezkerwin** [comment]
I'm in the process of creating one for RHEL which I'll submit a PR in the coming days, which I'll include this as well.

**Comment by jezkerwin** [comment]
I've included the lief installation steps in my PR to add the RHEL 7.x installation documentation, so I'll close this off.

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by lostInSpaceSomewhere** [comment]
im getting an error on the following step:
```
[ .... build]# scl enable devtoolset-7 'bash -c "cmake3 \
> -DLIEF_PYTHON_API=on \
> -DLIEF_DOC=off \
> -DCMAKE_INSTALL_PREFIX=$LIEF_INSTALL \
> -DCMAKE_BUILD_TYPE=Release \
> -DPYTHON_VERSION=2.7 \
> .."'
-- Could NOT find cppcheck (missing:  CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
fatal: No names found, cannot describe anything.
-- Tagged: 0
-- Current branch: master
CMake Error at cmake/LIEFGit.cmake:53 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)


CMake Error at cmake/LIEFGit.cmake:54 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)


CMake Error at cmake/LIEFGit.cmake:55 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:17 (include)


CMake Error at CMakeLists.txt:21 (project):
  VERSION ".." format invalid.


-- Configuring incomplete, errors occurred!
```

**Comment by mingwandroid** [comment]
Install `git`.
