### ISSUE TITLE
Export Stix from Misp.

### ISSUE THREAD

**Issue by MickeyAl** [MISP/MISP#2747]
Hi all,

I'm just getting started with misp.
All is runnig very well, so well that i want to export STIX from my misp instance to my Qradar.
Allready downloaded the OpenTaxii and set it up but thats it, i couldn't find any instruction on how to perceed.

And advice?

Thanks in advance!

**Comment by adulau** [comment]
I suppose you found a way ;-)

**Comment by TiagoSantos84** [comment]
Hi MickeyAl,

Did you get it to work?

Best Regards!
