### ISSUE TITLE
Allow to accept/refuse from proposals list

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#275]
Allow to accept from proposals list since pivoting to a big event with hundreds of attributes, and locating a single proposal can be cumbersome.

The most user-friendly way i can think of to solve this, is to offer the option to accept or refuse from the proposals list and only allow optionally to pivot to the event.

**Comment by Rafiot** [comment]
Fixed.

**Comment by elhoim** [comment]
Not fixed.

**Comment by Rafiot** [comment]
ok, didn't got the issue then. It is possible to reject/accept multiple propositions at once.

**Comment by elhoim** [comment]
Not from the proposals list. I opened this one because I did not have a good computer at work (only 2GB of RAM) and opening big events with "View all" in order to accept a bunch of proposals was really slow.

Could end up as wontfix, I am trying to move backward on my [featuritis curve](https://signalvnoise.com/posts/3781-kathy-sierras-featuritis-curve-helps)... :)

**Comment by Rafiot** [comment]
oh, I understand :)

**Comment by elhoim** [comment]
#667 is much easier.
