### ISSUE TITLE
csv-export with headerless flag not working properly

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#2761]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Win 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.84

### Expected behavior
When downloading a csv export via url or python request, the option "headerless" should exclude the header row from the export.

### Actual behavior
The option "headerless" set to "true" doesn't make a difference. The header will still be exported.

### Steps to reproduce the behavior
Use the url to download the csv export and set the headerless-flag to true:
https://yourMISP.org/events/csv/download/false/false/false/false/false/false/false/false/false/true

The other flags work as expected. Has anyone experienced a similar behavior?

**Comment by Rafiot** [comment]
Confirmed with the JSON query too.
