### ISSUE TITLE
resque-worker-error.log: "sh: git: command not found"

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2763]
Okay, this is super-unimportant and it is a question rather than an issue...

On our 2.4.84 instance the file _...app/tmp/logs/resque-worker-error.log_ contains many, many of the following entries

`sh: git: command not found`

...and I haven't been able to find out why (no, _git_ is not on our system...). Anyone able to clarify what's causing this, please? Thanks!

**Comment by adulau** [comment]
Could it be the diagnostic page? It's using `git` to fetch the current commit id.

https://<URL>/servers/serverSettings/diagnostics

**Comment by StefanKelm** [comment]
I don't think so; at least `resque-worker-error.log` is not being touched when I access the Diagnostics page (or any other page I've tried...).

**Comment by StefanKelm** [comment]
Okay, perhaps more clues: it appears that `resque-worker-error.log` on our 2.4.85 instance is only written upon either _scheduled pull_ or _scheduled feed fetch_. Everytime an event is

1. pulled/fetched
2. published internally
3. sent out via e-mail

one line of `sh: git: command not found` is written to `resque-worker-error.log
`
Does that make sense?

**Comment by racco42** [comment]
This log line is produced from the following line in Models/Feed.php:

$commit = trim(shell_exec('git log --pretty="%H" -n1 HEAD'));

**Comment by StefanKelm** [comment]
Interesting, thanks a lot. I guess we have to live with this message since `git` is not installed on our instance...

**Comment by StefanKelm** [comment]
Somewhat silly follow-up question: would I break anything if I just create a symbolic link from `/usr/bin/git` to `/dev/zero` in order to get rid of these messages?

**Comment by racco42** [comment]
Not sure what happens when you execute /dev/zero, but maybe linking /bin/true would be safer :-)

**Comment by StefanKelm** [comment]
Yes, of course, thank you! :-)
