### ISSUE TITLE
Collapsed view of correlations

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#2764]
For better overview and visibility, view on correlations should be changed. If there is a large number of correlations, the view should be collapsed on only show a preview of the correlations like:

9733 9408 9342 9322 (42 more) [+]

A click on the preview should expand the view.

**Comment by iglocska** [comment]
Will do this today as I'm touching that anyway currently.

**Comment by rommelfs** [comment]
This is obviously fixed. Closing. And thanks ;)
