### ISSUE TITLE
Changes to the feed at https://www.circl.lu/doc/misp/feed-osint/ 	?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2768]
Using 2.4.85 and a fresh git pull I'm no longer able to fetch or remotely explore the feed at https://www.circl.lu/doc/misp/feed-osint/ 	

Exploring remotely leads to an empty PreviewIndex and error.log shows

```
2017-12-27 14:45:59 Warning: Warning (2): Invalid argument supplied for foreach() in [/services/inst/misp/app/Lib/Tools/CustomPaginationTool.php, line 49]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
CustomPaginationTool::sortArray() - APP/Lib/Tools/CustomPaginationTool.php, line 49
FeedsController::__previewIndex() - APP/Controller/FeedsController.php, line 376
FeedsController::previewIndex() - APP/Controller/FeedsController.php, line 344
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

```

Fetching all events just displays "Failed" in the jobs section.

**Comment by iglocska** [comment]
Will have a look

**Comment by iglocska** [comment]
Looks like it's a misconfiguration of the file permissions on the feed (https://www.circl.lu/doc/misp/feed-osint/manifest.json = 403). Poke @adulau ;)

**Comment by adulau** [comment]
The OSINT feed is updated ;-) @StefanKelm fine for you?

By the way, it would be nice to have a better output of error from the MISP side when a feed is giving a 403 or 404 on the manifest file.

**Comment by StefanKelm** [comment]
Awesome, guys, thanks for the swift reply. Everything's fine now.

**Comment by adulau** [comment]
Thanks for the quick feedback.
