### ISSUE TITLE
No Vagrantfile

### ISSUE THREAD

**Issue by krionbsd** [MISP/MISP#2770]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

~ git clone https://github.com/MISP/MISP.git
Cloning into 'MISP'...
remote: Counting objects: 48200, done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 48200 (delta 107), reused 144 (delta 97), pack-reused 48011
Receiving objects: 100% (48200/48200), 37.67 MiB | 4.97 MiB/s, done.
Resolving deltas: 100% (35535/35535), done.
~ ls -la MISP/misp-vagrant
total 0
drwxr-xr-x   2 krion  staff   68 Dec 29 22:40 .
drwxr-xr-x  25 krion  staff  850 Dec 29 22:40 ..

as described in misp-vagrant/README.rst

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by adulau** [comment]
It's a git submodule, you need to do the following in the MISP repository:

`git submodule init`
`git submodule update`

**Comment by adulau** [comment]
I'll close the issue. Feel free to reopen if you have other issues.
