### ISSUE TITLE
Fetch feeds via https instead of http

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2775]
Many (not all) of the pre-installed feeds still point to http. Suggest to change this to https.

**Comment by adulau** [comment]
Good question. I remember discussing some pro/cons about it:

Pro for HTTP only

- HTTP feeds are cacheable with proxies.
- HTTP feeds don't break if certificate is expired, self-signed or whatever.

Pro for TLS

- Better for security (avoiding MiTM changes of the feeds)
- (partially) better to avoid leaking of what feeds you are getting from passive interception
 
We basically use the official link mentioned by the feed provider. 

Feedback welcome.

**Comment by StefanKelm** [comment]
I see. That's indeed an interesting discussion. I guess, there's no universal answer then since it depends on one's infrastructure as well as the threat model (and indeed some of the https alternatives are self-signed...).

For our instance we've changed all the feeds we're interested in to https but I guess there's no need for you guys to change anything.
