### ISSUE TITLE
Synchronisation Connection test 

### ISSUE THREAD

**Issue by dewiestr** [MISP/MISP#2786]
*If you would like to report a bug, please fill the template bellow*
Hi so the situation is the following: I have two MISP instances set up one collecting as mush as possible where I tag the interesting items and push the more interesting events through to a second instance. Unfortunately, I just updated to 2.4.85 on both systems and I am unable to push any longer from the first one to the second one. The connection test is giving me the reply 'Server Unreachable', however I can grab the server certificate with openssl's s_client when going over the terminal perfectly. 

Additionally when attempting my push, I'm seeing a non-object error in the resque-worker-error.log, which leads me to believe the second server is replying something non expected back. Could anyone assist debugging this issue with me ? Or point me to the right direction ? I feel like the logs are not covering enough in this case.

Thanks for the assistance

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  ubuntu
| OS version (client)       | 
| PHP version               | PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
                                       Copyright (c) 1997-2017 The PHP Group
                                        Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
                                        with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
| MISP version / git hash   | 2.4.85

### Expected behavior
Sync working or get any debugging in the logs

### Actual behavior
I'm just getting a server unreachable when trying to run the 'connection test' on the servers list. A push also just gives the following error (pull is not configured):

==> /var/www/MISP/app/tmp/logs/resque-worker-error.log <==
Notice Error: Undefined variable: response in [/var/www/MISP/app/Model/Server.php, line 2846]

==> /var/www/MISP/app/tmp/logs/debug.log <==
2018-01-07 03:52:09 Notice: Undefined variable: response in [/var/www/MISP/app/Model/Server.php, line 2846]

==> /var/www/MISP/app/tmp/logs/resque-worker-error.log <==
2018-01-07 03:52:09 Notice: Undefined variable: response in [/var/www/MISP/app/Model/Server.php, line 2846]
Notice Error: Trying to get property of non-object in [/var/www/MISP/app/Model/Server.php, line 2846]

==> /var/www/MISP/app/tmp/logs/debug.log <==
2018-01-07 03:52:09 Notice: Trying to get property of non-object in [/var/www/MISP/app/Model/Server.php, line 2846]

==> /var/www/MISP/app/tmp/logs/resque-worker-error.log <==
2018-01-07 03:52:09 Notice: Trying to get property of non-object in [/var/www/MISP/app/Model/Server.php, line 2846]

### Steps to reproduce the behavior
have absolutely no idea.

**Comment by adulau** [comment]
Could you share your server connection parameters? I did some test with two 2.4.85 instances upgraded from previous versions and it works as expected.

**Comment by dewiestr** [comment]
Hi @adulau, thanks for taking the time. 

I'm actually also synced with CIRCL's MISP and that one ( also on 2.4.85) works perfectly, so its is definitely in my setup. Unfortunately there are not many connection parameters I could share. which ones are you interested in ? Besides the domain, sync user and the certificate (which did not change), what would be interesting ?

Would you have any tips on where I could start looking for the issue, because the ajax Connection test run just returns status 2.

**Comment by dewiestr** [comment]
I believe I found the issue... : certificate has expired.

#facepalm... thanks for the troubles guys this can be closed. 

Will put in a feature request: if their is an issue with the self signed certificate, clarify in the logs or in the connection run.

**Comment by iglocska** [comment]
Thanks for the heads-up, I've added some better logging to the issue for the future. The audit logs will now show the exception message if no HTTP error code was returned.
