### ISSUE TITLE
Need install instructions modified to add sudo a2enmod headers

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2788]
Install instructions for Ubuntu, possibly others, needs instruction to enable headers mod in Apache2 if sample config file is used.

sudo a2enmod headers

Otherwise the services will not start and will give an error:

Jan 07 09:10:00 ubuntu apache2[70748]: Output of config test was:
Jan 07 09:10:00 ubuntu apache2[70748]: AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/misp-ssl.conf:
Jan 07 09:10:00 ubuntu apache2[70748]: Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration

Works fine after the mod is enabled.

**Comment by adulau** [comment]
Thank you for the feedback. Interesting. Which distribution are you using? To know which version of README to update.

**Comment by syloktools** [comment]
Ubuntu Server 16.04
