### ISSUE TITLE
Error: Call to undefined function opcache_reset()

### ISSUE THREAD

**Issue by juju4** [MISP/MISP#2792]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS,
| OS version (client)       | 7
| PHP version               | 5.6, 7.2
| MISP version / git hash   | HEAD

### Expected behavior

Since about 2 weeks, I have my automated travis build for my MISP ansible role failing for centos7.
https://travis-ci.org/juju4/ansible-MISP/builds

looking at it today, It seems to be similar to #2727 but for https://github.com/MISP/MISP/blob/9c17b11ab0d9e98a6d89725dcd78d487d66c7c6a/app/Model/Server.php#L2624
and fixed like https://github.com/datenstrom/yellow/issues/258
even if opcache_reset() is a base function https://secure.php.net/manual/fr/function.opcache-reset.php

I tried with php56 and php72 from remi yum repository with same result
https://api.travis-ci.org/v3/job/326519049/log.txt
https://api.travis-ci.org/v3/job/326505894/log.txt

Ubuntu 16.04 is normal
https://api.travis-ci.org/v3/job/326519050/log.txt
(search for /var/www/MISP/app/Console/cake userInit -q)
even if
```
----------------------------------------------------------------
  Ubuntu 16.04.1 LTS                          built 2016-12-10
----------------------------------------------------------------
Last login: Mon Jan  8 20:40:14 2018 from 10.0.2.2
vagrant@vhost:~$ grep -rin opcache.enable_cli /etc/php/*
/etc/php/7.0/cli/php.ini:1770:;opcache.enable_cli=0
/etc/php/7.0/apache2/php.ini:1770:;opcache.enable_cli=0
```

on centos7
```
[vagrant@vhost ~]$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[vagrant@vhost ~]$ grep -rin opcache /etc/php* /etc/httpd/*
/etc/httpd/conf.d/php.conf:51:    #php_value opcache.file_cache   "/var/lib/php/opcache"
grep: /etc/httpd/logs: Permission denied
Binary file /etc/httpd/modules/libphp7-zts.so matches
Binary file /etc/httpd/modules/libphp7.so matches
grep: /etc/httpd/run: Permission denied
```
same result if I force it
https://github.com/juju4/ansible-MISP/commit/96231aaf129b1171382e7f0f026974ecb99c62cb

L2624 seems to be recent and from commit
https://github.com/MISP/MISP/commit/6e7a9da729030683e46c7e79aaf3334bb7932a36#diff-5043d40040a721280ed4c0c7fb144ecb
I suppose that a if function is needed too but unsure

comment?

Thanks

**Comment by RichieB2B** [comment]
MISP works fine with php56 from SCL with the php56-php-opcache package installed as well.

**Comment by RichieB2B** [comment]
That is rh-php56 and rh-php56-php-opcache from SCL.

**Comment by juju4** [comment]
you win! seems remi reviewed recently the split of their php packages. works fine adding php-opcache. Thanks!

**Comment by iglocska** [comment]
Thanks for the heads-up, even though you've fixed it by installing the package - we should check whether the function exists before trying to execute it. Fixed in case others run into the same issue.

**Comment by juju4** [comment]
Thanks @iglocska
