### ISSUE TITLE
Hover expansion works via attributes alone but not when embedded in an object

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2793]
Hover expansion works via attributes alone but not when embedded in an object as in the example below:

![hover-object](https://user-images.githubusercontent.com/3309/34714715-98f9670c-f52a-11e7-91b7-ae5c454d46fa.png)

**Comment by StefanKelm** [comment]
Cross-referencing #2543 here since there's still a few issues with respect to objects.
