### ISSUE TITLE
First Login + You have tripped the cross-site request forgery protection of MISP

### ISSUE THREAD

**Issue by rrodstein** [MISP/MISP#2795]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by rrodstein** [comment]
Fresh single server install on Ubuntu 17.04 following the INSTALL.ubuntu1604.txt steps. 
Upon first login using Firefox we see "You have tripped the cross-site request forgery protection of MISP", using Chrome we see "ERR_TOO_MANY_REDIRECTS". 

cat VERSION.json
{"major":2, "minor":4, "hotfix":85}

We have seen other posts, but no resolutions, i.e.
https://github.com/MISP/MISP/issues/2440 (we made the changes to the following php.ini file as suggested, no love, i.e.)
php -i|grep 'php.ini'
Configuration File (php.ini) Path => /etc/php/7.0/cli
Loaded Configuration File => /etc/php/7.0/cli/php.ini
https://github.com/MISP/MISP/issues/1645

Logs:
==> /var/www/MISP/app/tmp/logs/error.log <==
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))

Thank you in advance for your support!


Questions | Answers
-- | --
Type of issue | Bug, Question, Feature Request, support...
OS version (server) | Debian, ubuntu, CentOS, RedHat, ...
OS version (client) | XP, Seven, 10, Ubuntu, ...
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

**Comment by iglocska** [comment]
Both of those got resolved by changing to the php session handler. Could you check what the session handler is set to currently? 

`/var/www/MISP/app/Config/config.php`
`'Session.defaults' => 'php'`

**Comment by rrodstein** [comment]
Hi,

Thank you for your support!

We get the same results with both php and batabase in /var/www/MISP/app/Config/config.php file.
tested both, i.e. made the change, restarted services, and tested. 
'Session.defaults' => 'php'
'Session.defaults' => 'database'
made the changes:
sudo service apache2 restart
sudo service redis-server restart
sudo -u www-data /var/www/MISP/app/Console/worker/start.sh

try a login, and then see the bloackhole in the logs, and You have tripped the cross-site request forgery protection of MISP with firefox.

**Comment by iglocska** [comment]
Hmph, OK, that is weird. If you switch it to Session.defaults = file, do
you get the same thing?

**Comment by rrodstein** [comment]
With file we get a blank page in both firefox, and chrom. The logs:
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeSessionExc...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeSessionExc...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeSessionExc...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(CakeSessionException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2018-01-09 08:01:04 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2018-01-09 08:01:04 Warning: Warning (2): ini_set() [<a href='http://php.net/function.ini-set'>function.ini-set</a>]: session.name cannot be a numeric or empty '' in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 553]
2018-01-09 08:01:04 Warning: Warning (2): ini_set() [<a href='http://php.net/function.ini-set'>function.ini-set</a>]: session.name cannot be a numeric or empty '' in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 553]
2018-01-09 08:01:04 Warning: Warning (2): ini_set() [<a href='http://php.net/function.ini-set'>function.ini-set</a>]: session.name cannot be a numeric or empty '' in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 553]
2018-01-09 08:01:04 Error: Fatal Error (256): [CakeSessionException] Unable to configure the session, setting session.name failed.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php(588): CakeSession::_configureSession()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php(599): CakeSession::_cookieName()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php(233): CakeSession::_hasSession()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/SessionHelper.php(134): CakeSession::check('Message.flash')
#4 /var/www/MISP/app/View/Layouts/error.ctp(46): SessionHelper->flash()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/var/www/MISP/a...', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(546): View->_render('/var/www/MISP/a...')
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(481): View->renderLayout('<h2>An Internal...', 'error')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(328): View->render('error500', 'error')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(309): ExceptionRenderer->_outputMessageSafe('error500')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(260): ExceptionRenderer->_outputMessage('error500')
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error500(Object(InternalErrorException))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::handleException(Object(InternalErrorException))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#18 [internal function]: App::shutdown()
#19 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]

**Comment by rrodstein** [comment]
Hi,

Thank you again for your support!

Is it possible to disable cross-site request forgery protection, just so we can evaluate MISP?

Respectfully,

**Comment by iglocska** [comment]
It isn't really a CSRF issue, your php is having issues creating a session for some reason. What is the baseurl set to in /var/www/MISP/app/Config/config.php ?

**Comment by rrodstein** [comment]
Currently the FQDN, but we have also tested localhost, and the IP address, all have the same results.

**Comment by rrodstein** [comment]
Not sure how I got there, but I removed the base URL in the /var/www/MISP/app/Config/config.php file, and now I'm up and running!

**Comment by BenjaminJoly** [comment]
As it's now all good, I'll close this issue. 
If you have any problem, do not hesitate to open another one.
