### ISSUE TITLE
Trying to publish event with attribute with sharing group 

### ISSUE THREAD

**Issue by AssafCompie** [MISP/MISP#2796]
### Work environment

| Questions                  | Answers
|-----------------------------|--------------------
| Type of issue             |   Bug 
| OS version (server)   |  Ubuntu 16.04
| OS version (client)     |  Ubuntu 16.04
| PHP version               |  7.0.22-0 ubuntu0.16.04.1 (cli) ( NTS )
| MISP version             |   2.4.84
| Browser                     | google chrome
|-----------------------------|---------------------

*it's a new system we just installed*
*we copied the database from our old system to the new one but this bug was already before*

### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

### Steps to reproduce the behavior

click Add Event -> fill in the "Event Info" -> click "Add"
click on Add attribute ( plus sign ) -> on Distribution choose "sharing group" -> fill in some value at the textarea -> click "Submit" -> click "Publish Event" -> click "Yes"

### Logs
Error: [Error] Call to a member function checkIfAuthorised() on null
Request URL: /events/alert/187
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(2185): Event->__buildAlertEmailAttribute(Array, '===============...', '', Array, true, '0')
#1 /var/www/MISP/app/Model/Event.php(2074): Event->__buildAlertEmailBody(Array, Array, '0', Object(SharingGroup))
#2 /var/www/MISP/app/Model/Event.php(2017): Event->sendAlertEmail('187', Array, '0')
#3 /var/www/MISP/app/Controller/EventsController.php(1737): Event->sendAlertEmailRouter('187', Array, '0')
#4 [internal function]: EventsController->alert('187')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(95): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by BenjaminJoly** [comment]
I've tried to reproduce the bug (On my CentOS 7, with php 7.1.11 and MISP 2.4.85), and it worked without any issues. Is it still the case with an up-to-date MISP instance ?
