### ISSUE TITLE
Modify Free-Text import Regex

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2797]
Is there documentation on how to change the free text import to say always see a link from hybrid analysis as a Category: External Analysis and Type: Link?

It does this for VirusTotal but not many other sandboxes. Just point me in the right direction or to the file to modify.

**Comment by syloktools** [comment]
Or is that done by Object Templates?

**Comment by iglocska** [comment]
Just pushed a fix with an example - just dig around in that area if you want to add more :)
