### ISSUE TITLE
Outgoing URL export not filling in suricata_ values

### ISSUE THREAD

**Issue by dewiestr** [MISP/MISP#2798]
Hi guys, 

I've noticed that a few of my OUTGOING URLs suricata rules, generated by visiting /events/nids/suricata/download/ are showing the following behavior:

Expected syntax: 

alert **http $HOME_NET any -> $EXTERNAL_NET any** (msg: "MISP e.... [] Outgoing URL: https|3a|//evil.com/blabla?i=param";  tag:session,600,seconds; classtype:trojan-activity; _content:"evil.com"; content:"blabla?i=param"_; sid:XXXXXXX; rev:1; priority:3; reference:url,https://misp/events/view/...;) 

What I am getting: 
alert       ->    (msg: "MISP e.... [] Outgoing URL: https|3a|//evil.com/blabla?i=param";  tag:session,600,seconds; classtype:trojan-activity; sid:XXXXXXX; rev:1; priority:3; reference:url,https://misp/events/view/...;) 

Regards,

**Comment by 0xmilkmix** [comment]
If it's https you won't be able to get the uri, only the hostname and cert's info.
the code for https protocol rules is commented-out in the src code. We just discussed it w/ @iglocska

**Comment by iglocska** [comment]
Indeed, this should now be fixed. It was a partially removed rule generator that ended up still generating rules but missing half of the inserted variables.
