### ISSUE TITLE
Potential issue with Suricata rules generated by MISP

### ISSUE THREAD

**Issue by nicksoy** [MISP/MISP#2801]
Hi all,

A MISP user of ours noted a potential problem with the Suricate rules generated by MISP (Noted the Suricata rules do carry a disclaimer with them).

They provided an example using the following rule, which is supposed to detect outbound traffic for the url - http / 181 [.] 214 [.] 87 [.] 240 /res / kworker [.] conf.

alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg: "MISP e2139 [] Outgoing HTTP URL: http|3a|//181.214.87.240/res/kworker.conf";
flow:to_server,established;
content:"http|3a|//181.214.87.240/res/kworker.conf"; nocase; http_uri; tag:session,600,seconds; classtype:trojan-activity; sid:6837982; rev:1; priority:2; reference:url,https://misp.auscert.org.au/events/view/2139;)

Should the suricata rule rather have:

content:"GET"; http_method;
content:"181.214.87.240"; http_host;
content:"/res/kworker.conf"; http_uri;

Appreciate if you could look into this.

### Actual behavior

MISP Suricata rule generated has content:

content:"http / 181 [.] 214 [.] 87 [.] 240 /res / kworker [.] conf"; http_uri

### Steps to reproduce the behavior

1. Add a payload delivery url attribute:
    http / 181 [.] 214 [.] 87 [.] 240 /res / kworker [.] conf.
2. Export as Suricata rule.

**Comment by adulau** [comment]
I just tested but it works as expected on current HEAD:

~~~~
# MISP export of IDS rules - optimized for suricata
#
# These NIDS rules contain some variables that need to exist in your configuration.
# Make sure you have set:
#
# $HOME_NET	- Your internal network range
# $EXTERNAL_NET - The network considered as outside
# $SMTP_SERVERS - All your internal SMTP servers
# $HTTP_PORTS   - The ports used to contain HTTP traffic (not required with suricata export)
# 
alert http $HOME_NET any -> 181.214.87.240 $HTTP_PORTS (msg: "MISP e10021 [] Outgoing URL http|3a|//181.214.87.240/res/kworker.conf"; flow:to_server,established; content:"181.214.87.240"; fast_pattern; nocase; http_header; content:"/res/kworker.conf"; nocase; http_uri; tag:session,600,seconds; classtype:trojan-activity; sid:11971854; rev:1; priority:3; reference:url,https://misppriv.circl.lu/events/view/10021;) 
# 
~~~~

Just a side note, defanging happens at the level of the free-text import but attributes are in defanged form by default. I suppose your attribute is clean and defanged.

**Comment by nicksoy** [comment]
Hi Alexandre,

Thanks for checking that out. We’ll investigate further at our end.

Kind regards,

Nicholas Soysa
Senior Information Security Analyst
AusCERT
Australia's premier cyber emergency response team.
m: 0431 643469 t: 61 7 3365 4417 e: nsoysa@auscert.org.au
w: www.auscert.org.au

**Comment by adulau** [comment]
@nicksoy Do you have any feedback on this issue? I'll close the ticket but feel free to reopen if the issue persists. Thank you very much.
