### ISSUE TITLE
Hide organisations of passive users

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#2803]
We need to hide the list of organisations who didn't create any data on a MISP instance.

Usecase: company sharing indicators with customers which doesn't want the customers to see each other.

**Comment by adulau** [comment]
Ok it makes sense but I would make it optional as in a community seeing each others is often must.

**Comment by Rafiot** [comment]
Yes, absolutely

**Comment by iglocska** [comment]
Implemented now.
