### ISSUE TITLE
Cannot install 'pydeep' on MISP Docker container

### ISSUE THREAD

**Issue by infracritical** [MISP/MISP#2808]
Am having difficulties with installing 'pydeep'.  Have installed Ubuntu 16.04.3, and loaded official Docker container release 2.4.85.  Upon performing diagnostics, found out that 'pydeep' was not installed.  Tried installing it via either method, and get an error message similar to this:

root@localhost:/var/www/MISP# **pip install pydeep**
Collecting pydeep
  Downloading pydeep-0.2.tar.gz
Building wheels for collected packages: pydeep
  Running setup.py bdist_wheel for pydeep ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ttysc9m/pydeep/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp5kdx9b68pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'pydeep' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c pydeep.c -o build/temp.linux-x86_64-3.5/pydeep.o
  **pydeep.c:2:19: fatal error: fuzzy.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**
  
  ----------------------------------------
  Failed building wheel for pydeep
  Running setup.py clean for pydeep
Failed to build pydeep
Installing collected packages: pydeep
  Running setup.py install for pydeep ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ttysc9m/pydeep/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nfopqtrw-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pydeep' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c pydeep.c -o build/temp.linux-x86_64-3.5/pydeep.o
    **pydeep.c:2:19: fatal error: fuzzy.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**
    
    ----------------------------------------
**Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ttysc9m/pydeep/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nfopqtrw-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_ttysc9m/pydeep/**

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by infracritical** [comment]
Ubuntu 16.04.3 (patched); PHP 7.0.22; MISP 2.4.85 (Docker image); Docker 1.12.1, build 23cf638.

**Comment by adulau** [comment]
Have you installed libfuzzy-dev? https://packages.ubuntu.com/search?keywords=libfuzzy-dev

**Comment by infracritical** [comment]
Man...do I feel like an idiot.  Yes...that fixed the problem.  DOH!

For those checking, enter this command: "**apt-get -y install libfuzzy-dev**"; if you're using the MISP Docker, this must be performed **WITHIN** the container.

**Comment by adulau** [comment]
No worries, glad it works! Thanks for the feedback.
