### ISSUE TITLE
objects and object-attributes are not removed from the tables in multiple use-cases

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2810]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| MISP version / git hash   | 2.4.85

### Actual behavior
Objects are not removed from the ```objects``` table in a number of specific use-cases:
- event deletion => attributes are removed, but object is still in the object table
- removal of the object in the event view => nor the objects, nor attributes are removed from their respective tables 

### Steps to reproduce the behavior
- create an event
- add an object
- remove the event or object
- ```SELECT * FROM objects; ```

**Comment by iglocska** [comment]
Nice catch, thanks!
