### ISSUE TITLE
Attributes mistakenly flagged by warning list 

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2813]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.85

### Expected behavior
-Not flagging hostnames and domains that are not 2nd level TLDs as per Mozilla file

### Actual behavior
- Domains and hostnames that are not 2nd level TLDs as per Mozila file **are** flagged by that warning list 

### Steps to reproduce the behavior
- User hostnames adfs.senate.group / adfs.senate.qov.info / adfs-senate.services
OR
- Check event 10036 on MISPpriv

Checked the warning list at https://github.com/MISP/misp-warninglists/blob/master/lists/second-level-tlds/list.json and I dont really see what could trigger this since none of the values are there.

**Comment by iglocska** [comment]
Indeed, the current warninglist is using the "substring" algorithm whilst the "domain" one would make a lot more sense.

**Comment by adulau** [comment]
Fixed in f8ff7589c28851baaf3e2cfeba9ec4601a59f09c
