### ISSUE TITLE
MISPObject constraints not followed when creating via pymisp/API

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2815]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | 2.4.85,

### Actual behavior
Some MISPObjects have constraints, like the requirement to have at least one of the following misp attributes. These are enforced via the webinterface, but not via the API

### Steps to reproduce the behavior

Create an object of 'whois' , butnot compliant to the requirements
- Required: domain
- Required one of: registrant-email, registrant-phone, creation-date, registrant-name, registrar

Code sample
```python
misp = PyMISP(keys.misp_url, keys.misp_key, keys.misp_verify, 'json')
misp_event = MISPEvent()
# adding params
misp_event.threat_level_id = 2      # PyMISP.threat_level.medium
misp_event.analysis = 1             # PyMISP.analysis.ongoing
misp_event.info = "test event"
misp_event.set_date(datetime.datetime.today().strftime('%Y-%m-%d'))
# creating the object with the attribute
o = MISPObject(name='whois')
o.add_attribute('text', category='Other', value='foobar', distribution=5)
o.distribution = 5
o.sharing_group_id = 0
misp_event.add_object(**o)
online_event = misp.add_event(misp_event.to_json())
print(online_event)
```

### Logs, screenshots, configuration dump, ...
You notice the event is created:
![image](https://user-images.githubusercontent.com/1073662/34946650-fb8ce600-fa07-11e7-8d35-948cb48139e0.png)

**Comment by cvandeplas** [comment]
it seems this is a feature...

**Comment by iglocska** [comment]
"It's not a bug it's a feature" strikes again ;)
