### ISSUE TITLE
object row on event view page has incorrect layout when sightings is disabled

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2820]
I believe this was fixed before, but it seems it's not.

### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | 2.4.85

### Steps to reproduce the behavior
- create an event
- create an Object
- enabled/disable sightings

### Logs, screenshots, configuration dump, ...
With sightings disabled the layout is incorrect: notice the width of the blue part is too large
![image](https://user-images.githubusercontent.com/1073662/34977439-cb9c43e4-fa9a-11e7-8d07-dd6396cf9e73.png)

With sightings enabled it's correct
![image](https://user-images.githubusercontent.com/1073662/34977512-153f3286-fa9b-11e7-8321-f6fcf5b79862.png)

**Comment by iglocska** [comment]
Wait, sightings can still be disabled? I think that's the real bug in there ;)

**Comment by cvandeplas** [comment]
if you remove the option, make sure it's enabled where it is disabled today :-)

**Comment by iglocska** [comment]
yep, the idea is to remove all the checks and just always have it enabled. It started out as an experimental feature but we should consider it a core functionality. Will try to do it today.
