### ISSUE TITLE
Category attribution cannot be selected for x509 fingerprints.

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2821]
When doing freetext import, it is not possible to select the category attribution and  thus to stick some md5/sha1/sha256 as corresponding x509-fingerprint-md5/x509-fingerprint-sha1/x509-fingerprint-sha256.

For sha1, it is possible to mass-convert from sha1 to x509-fingerprint-sha1 but for md5 & sha256, it is not possible.

Those two enhancements would be really useful when importing full-text reports.

**Comment by iglocska** [comment]
This is actually a bigger limitation as it first seems. Basically the list of categories is pre-selected based on the default type. This however isn't really correct as some types have different category mappings - meaning that we're missing out on some categories for some types.

This worked fine initially when the freetext import tool was more experimental and limited, but it's becoming a serious burden now. I'll look into making it a bit smarter.
