### ISSUE TITLE
Additional re-fanging for freetext import of IOCs

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2822]
Following "seen in the wild" type of IOC de-fanging have been observed:
evil@domain[.]com
evil[@]domain.com

It would be useful to add them to the re-fanging algorithm used in the freetext import

**Comment by iglocska** [comment]
Sure, also WTF at the second one.

**Comment by iglocska** [comment]
Should be fixed now!

**Comment by elhoim** [comment]
Thanks!
