### ISSUE TITLE
PDB paths getting generified via regexp

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2823]
PDB paths sometimes contain directories that can be (and are) generified via the regexps;
for example: 
`c:\Users\USA\Documents\Visual Studio 2008\Projects\New folder (2)\kasper\Release\kasper.pdb` (from [here](https://www.threatconnect.com/blog/kasperagent-malware-campaign/) ) is generified to:
`%USERPROFILE%\Documents\Visual Studio 2008\Projects\New folder (2)\kasper\Release\kasper.pdb `
because of the regexps; while values to be useful for rules are to be exact and un-modified.

Food for thought:
- The easiest way would be to not apply the regexps to attributes of type PDB.
- If there are more attribute types where regexp should not be applied to, then it might be more future-proof to add a flag per attribute types to disable application of regexps to those.

**Comment by iglocska** [comment]
We already have that - the default regex dataset needs revising simply. Currently they apply to all types, but that is completely optional. Feel free to tune it!

**Comment by adulau** [comment]
@elhoim PR is accepted. I'll close the issue until we received the PR. Thank you!

**Comment by elhoim** [comment]
Opened https://github.com/MISP/MISP/pull/10968 against `2.5` for this and the earlier duplicate #1420: `pdb` is added to `RegexpBehavior::EXCLUDED_TYPES` (`app/Model/Behavior/RegexpBehavior.php:12`). The PR body explains why a code-level exclusion was chosen over retuning the shipped regexp dataset — the guarantee needs to hold on instances that have added their own type-`ALL` path-normalising regexps, and it follows the precedent already set by `sigma`/`float`/etc. The `INSTALL/*.sql` datasets are untouched.
