### ISSUE TITLE
enrichment not working with MISPObject attributes

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2825]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.85, 2.4.86

### Steps to reproduce the behavior
- create event
- create attribute
- press the enrich button, notice everything works
- create MISP object (whois for example)
- press the enrich button (on the right) on the domain field
- notice the window becomes grey, an error at the bottom appears ```Could not fetch the given PGP key.```

### Logs, screenshots, configuration dump, ...

The logs say: 
```
==> error.log <==
2018-01-16 15:21:25 Error: [MethodNotAllowedException] Attribute not found or you are not authorised to see it.
Request URL: /events/queryEnrichment/6576/ShadowAttribute?_=1516116000468
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment('6576', 'ShadowAttribute')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

**Comment by StefanKelm** [comment]
=> https://github.com/MISP/MISP/issues/2543#issuecomment-349341037

**Comment by iglocska** [comment]
Fixed, thanks!
