### ISSUE TITLE
duplicate entries are possible with MISPObjects within same event

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2826]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | 2.4.85, 2.4.86

### Steps to reproduce the behavior
- create event
- create object
- create object with identical entries as first object
- notice the two identical entries exist

This is not consistent with the unique attributes within a same event.

**Comment by github-germ** [comment]
+1

We are experiencing the same issue with duplicate `MISPObjects` being ingested into a `MISPEvent`. We deem this as a duplicate as all encapsulated `MISPObjectAttributes` are identical with same values.

In the case of `MISPAttributes` these dups are not allowed (related issue to not error (perhaps optionally) those dup rejections: https://github.com/MISP/MISP/issues/5257).

Is it possible to have the same result to disallow dup `MISPObjects`?

Our use case is appending objects into large events, and for performance reasons, our client does not pull down the full event to remove dups on the client side. We've found it much more time efficient to let the server side dedup with `MISPAttributes`, and are hoping for the same in `MISPObjects`.

**Comment by Rafiot** [comment]
If it is actually doable: check a (sorted) list of every single attribute value within an object against the same list in every other objects (of the same type) in the event. On huge events with many attributes, it will be a very heavy task on the server side.

An alternative would be to hash that list for every object and check for duplicates (would be less heavy to process).

**Comment by github-germ** [comment]
> If it is actually doable: check a (sorted) list of every single attribute value within an object against the same list in every other objects (of the same type) in the event. On huge events with many attributes, it will be a very heavy task on the server side.
> 
> An alternative would be to hash that list for every object and check for duplicates (would be less heavy to process).

Indeed, a hash cache is how i dedup attribute triplets (cat, type, value) in my client apps -- works well. If we could get that on the server side for objects, that'd be cool.

**Comment by Rafiot** [comment]
It won't be implemented before at best end of Q1 2020 at best (again, depends on urgent/paid feature requests we receive).

**Comment by github-germ** [comment]
was this fixed as per 2.4.121 https://www.misp-project.org/Changelog.txt ?
`- [object] object deduplication fixed. [iglocska]`

**Comment by Rafiot** [comment]
So, you should give it a try. 
It will bounce if object relation, category, type, and value are the same: https://github.com/MISP/MISP/commit/55385e6ca6f2ea818d9cd985438073135a2f01c5

**Comment by iglocska** [comment]
Only when the correct flag is set. It was added here:

https://github.com/MISP/MISP/commit/4ea3612dfc23f9a97818d539c82604b9b1d869f2

**Comment by chrisinmtown** [comment]
I would like to reopen this, if that's allowed; otherwise I will create a new issue. 

I am using a 2.4.133 server.  I wrote a script (below) to test rejection of duplicate objects when creating/modifying an event. I tried to set the breakOnDuplicate flag to trigger the new code but no luck.  I think maybe it's not possible to pass this parameter from PyMISP right now? 

This is the critical line on the server:
https://github.com/MISP/MISP/blob/ca5043a184b8eec53fb4093377fc4a727d4345cf/app/Controller/ObjectsController.php#L224

Please see below for a self-contained code example:
```
#!/usr/bin/env python3

import sys
import urllib3
from pymisp import PyMISP, MISPAttribute, MISPEvent, MISPObject
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def check_misp_response(resp: dict, msg: str):
    """Check a MISP response for error; show error and exit if found"""
    if isinstance(resp, dict) and 'errors' in resp:
        print('{} failed: {}'.format(msg, resp['errors']), file=sys.stderr)
        raise Exception('check_misp_response exiting')

def add_phishing_obj(misp_client, event):
    """Create an object on an event with a single attribute"""
    obj = MISPObject(name='phishing', strict=True)
    obj.breakOnDuplicate = True
    obj.add_attribute(object_relation='url', simple_value='https://simple.tld/')
    response = misp_client.add_object(event.id, obj, pythonify=True)
    check_misp_response(response, 'add_object')
    print('added obj on evt: {}'.format(obj.to_json(sort_keys=True, indent=4)))
    return obj

misp_client = PyMISP(url='https://misp:48752', key='keykeykey', ssl=False)
if not misp_client:
    print('PyMISP() failed\n', file=sys.stderr)
    sys.exit(1)

event = MISPEvent()
event.distribution = 0  # internal
event.published = False
event.info = 'Test event for dupes'
event = misp_client.add_event(event, pythonify=True)
check_misp_response(event, 'add_event')
print('created event:\n{}'.format(event.to_json(sort_keys=True, indent=4)))

obj1 = add_phishing_obj(misp_client, event)
obj2 = add_phishing_obj(misp_client, event)

response = misp_client.delete_object(obj2)
check_misp_response(response, 'delete_object')
print('deleted obj {}'.format(obj2.uuid))

response = misp_client.delete_object(obj1)
check_misp_response(obj1, 'delete_object')
print('deleted obj {}'.format(obj1.uuid))

response = misp_client.delete_event(event)
check_misp_response(response, 'delete_event')
print('deleted evt {}'.format(event.uuid))
```
