### ISSUE TITLE
New fetchFromAllFeeds path bug

### ISSUE THREAD

**Issue by rmkml** [MISP/MISP#2829]
Hello,
Happy New Year Everyone first,
I found a bug on fetchFromAllFeeds path bug: app/View/Feeds/index.ctp
 -<a href="feeds/fetchFromAllFeeds" class="btn btn-primary qet"...
 +<a href="fetchFromAllFeeds" class="btn btn-primary qet"...
Best Regards
@Rmkml

**Comment by iglocska** [comment]
Thanks a lot, should be fixed now.
