### ISSUE TITLE
Export search results as CSV does not work

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2837]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |RedHat
| MISP version / git hash   | 2.4.85

### Expected behavior
- Export all the results in CSV.

### Actual behavior
- Only receives the headers of the CSV. JSON and XML export are working though.

### Steps to reproduce the behavior
- Do a search for a string that will match multiple attributes.
- Try to export the CSV from the list of results.

**Comment by git-kitty** [comment]
The behavior is reproducible on our instance where the CSV contains the headers only. The exports to JSON and XML are functional.

This is not ideal as most of our users utilize the UI versus the API. 

**Current Workaround**
-The CURL command below exports the data (in this case domains) to a CSV.

`curl --header "Authorization: <MISP AUTH KEY>" --header "Accept: application/json" --insecure --header "Content-Type: application/json" https://localhost/attributes/text/download/domain/null/null/null/2018-07-01/null/null/null/true > domain-test.csv`

**Comment by adulau** [comment]
The CSV export has been rewritten along with the restSearch API.

You can now do flexible queries in the API and choose any supported MISP output:

~~~~
{
    "returnFormat": "csv",
    "threatlevelid": "1d",
    "last": "2d",
    "threat_level_id": 1
}

Feel free to reopen if this doesn't solve the issue.
~~~~

**Comment by git-kitty** [comment]
Excellent! Thank you very much.
