### ISSUE TITLE
Search Attributes

### ISSUE THREAD

**Issue by randomname13** [MISP/MISP#2849]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 14.04 / 16.04
| OS version (client)       | Any
| PHP version               | 5.5.9 / 7.0.22
| MISP version / git hash   | 2.4.86, e2add67c8939ffe39f7fad3333d1fa025689320e
| Browser                   | Chrome/Edge/IE/Firefox

### Expected behavior
Menu -> Search attributes -> "any string" -> Display connected attributes

### Actual behavior
Menu -> Search attributes -> "any string" -> 500 Internal Server error

### Steps to reproduce the behavior
This happens only as a NON-admin role user

**Comment by iglocska** [comment]
Woah, nice catch. Should be fixed now, thanks!
