### ISSUE TITLE
Common issue with full XML download? Execution time exceeded (over 30 or 1 minute)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#285]
I'm wondering if you ever encounter the following problems with MISP if you tried to download the full XML dump via the API:

https://<YOURMISP>/events/xml/download

"2014-09-01 07:25:14 Error: Fatal Error (1): Maximum execution time of 60 seconds exceeded in"

Debugging the MySQL server shows that the queries are taking place quite fast, I even logged all the queries and the total execution time is below 1 second for the whole set of queries on a properly tuned MySQL with around 100000 attributes. Doing an strace on the Apache processes give that it's waiting indefinitely for something...   

Have you already encounter such issue?

**Comment by Rafiot** [comment]
Fixed, isn't it?

**Comment by iglocska** [comment]
Indeed the background workers were implemented partially to resolve this.

**Comment by Rafiot** [comment]
\o/
