### ISSUE TITLE
Error: "organisations" table already exists

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#2856]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question, Bug
| OS version (server)       | Ubuntu
| OS version (client)       | OS X
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.86 (28a4036ae321f2b20c014d47bd3d6e7713fa916a) 
| Browser                   | N/A

### Description
I've been working on a new table for issue #2616. When trying to update my dev MISP by rerunning the MYSQL.sql script I encountered an error when it tries to create the organisations table. Instead of `CREATE TABLE IF NOT EXISTS` it just uses `CREATE TABLE`. 
Likewise with sharing_group_orgs and sharing_group_servers.

If this is the intended behavior then feel free to close this. If not, I can submit a PR.

### Expected behavior
Rerunning the MYSQL.sql script on an existing database won't try to create tables that already exist

### Actual behavior
SQL script errors out and stops parsing commands

### Steps to reproduce the behavior
Rerun the `INSTALL\MYSQL.sql` script on a MISP instance that already has a database

### Logs, screenshots, configuration dump, ...
```
root@misp:/var/www/MISP/INSTALL# sudo -u www-data sh -c "mysql -u misp -p misp < /var/www/MISP/INSTALL/MYSQL.sql"
Enter password:
ERROR 1050 (42S01) at line 569: Table 'organisations' already exists
```

**Comment by iglocska** [comment]
Woaah mysql.sql should never be executed on an already running misp
instance.
