### ISSUE TITLE
sort modules list alphabetically in Server Settings > Plugin Settings

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2858]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request,

In server settings > Plugin Settings the lists in the Expansion and import/export modules is not sorted alphabetically. This makes it difficult to find the right item when you need to enable/disable or configure a specific misp-module

![image](https://user-images.githubusercontent.com/1073662/35145777-52d256a8-fd09-11e7-9788-e8cda95a2680.png)

**Comment by iglocska** [comment]
Will not fix, a reworked interface for module configuration is on the way (similarly to the feed index / adding feeds) ;)
