### ISSUE TITLE
Error with no further message while importing blacklisted event 

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#2859]
Hey guys,
found a little issue today.

### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| MISP version   | 85

### Expected behavior
When importing a blacklisted event using a MISP-JSON file, I expect it to fail with a corresponding error message.

### Actual behavior
Error message is empty.

### Steps to reproduce the behavior
Import a blacklisted event (due to prior deletion) using a misp-json file.

**Comment by iglocska** [comment]
Thanks for the heads-up!
