### ISSUE TITLE
Could not locate PGP/GPG public key

### ISSUE THREAD

**Issue by TheManInTheSuit** [MISP/MISP#286]
Hello guys,
After installing a new instance of MISP (v2.2), it doesn't seem to be willing to read the freshly created PGP keypair.   All GnuPG settings have been set in the bootstrap file, and a gpg --list-keys shows the keypair correctly.
However, when going to the web interface, in the bottom left, the MISP installation keeps saying that it couldn't locate the PGP/GPG public key.
Known issue? Any suggestions on how to troubleshoot? 
Cheers!

**Comment by rpmcglon** [comment]
what was the fix for this. I don't see where this is in the manual

**Comment by seanthegeek** [comment]
It's not documented anywhere that I can find, but MISP expects a public key file to be at `/var/www/MISP/app/webroot/gpg.asc`.

**Comment by sara931** [comment]
what was the fix for it as i am its not mentioned in documented anywhere.

**Comment by LintStalker** [comment]
> It's not documented anywhere that I can find, but MISP expects a public key file to be at `/var/www/MISP/app/webroot/gpg.asc`.
 
Is gpg.asc a folder or a file?  I don't see a folder called that.  How do I generate the key?

**Comment by LintStalker** [comment]
I've installed MISP on a RHEL 9 server and when I browse out to the server I get the following message:

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Keyboard shortcuts for this page:
L: Go to event list
E: Go to add event page
?: Show this help
Could not locate the PGP public key.

What do I do?
