### ISSUE TITLE
enrich using all sources 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2860]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |\ Feature Request,

This is to request a button to allow enrichment of an attribute using all sources.

So to the list below, add as first entry "Enrich using all sources".
![image](https://user-images.githubusercontent.com/1073662/35152775-0b38ddd8-fd24-11e7-8b52-836ff861fff0.png)

**Comment by adulau** [comment]
Nice idea!

**Comment by cvandeplas** [comment]
This feature has been implemented some time ago. 
Now you can check boxes to enrich the multiple modules at once
