### ISSUE TITLE
[Feature]API for Warninglists

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#2861]
It would be pretty handy to have a way to query the warninglist list via API.

**Comment by iglocska** [comment]
You mean to fetch the data? It's fully exposed to the API.

`/warningslists/index`
`/warninglists/view/<id>`

etc

**Comment by jaegeral** [comment]
hah indeed it is, but not documented, made a PR to document it as well ;)

https://github.com/MISP/misp-book/pull/86

**Comment by iglocska** [comment]
Docuwhatnow? Thanks a lot! ;)
