### ISSUE TITLE
CSV Import Module

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#2862]
Currently, we have only 4 options to populate the event with the attributes

- Freetext import
- OpenIOC import
- Threat connect import
- Populate using a template

Would suggest to have CSV import. Having an option of importing CSV will help in bulk import of different types of attributes. 

We can initially have mandatory fields  - Category, Type, Distribution, Value, Contextual comment

**Comment by neo609** [comment]
I also wanted this function.

We're plan to release a python-based CSVimport tool soon. 
This tool may be helpful to this feature request.

**Comment by LAC-Japan** [comment]
We have released a tool to import CSV files into MISP, which we created.
If its helpful then im happy.
https://github.com/LAC-Japan/MISP-CSVImport

**Comment by thirdeyeintelligence** [comment]
looks really good. However, I was hoping to get import function via GUI, under populate from option.

**Comment by adulau** [comment]
@makflwana there is a new CSV import module in MISP modules https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/import_mod/csvimport.py Feel free to test it ;-)
