### ISSUE TITLE
Option "Advanced extraction (if installed)" Modifies Distribution Level of Attachment

### ISSUE THREAD

**Issue by cocaman** [MISP/MISP#2865]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 14.04 / 16.04
| OS version (client)       | Microsoft Windows
| PHP version               | 5.5.9 / 7.0.22
| MISP version / git hash   | MISP 2.4.86 cea61bf61fddcab0f84ffb48a088009eab0428cb 
| Browser                   | Tested with Firefox

### Expected behavior
Event -> Add Attachment -> Distribution "Inherit" -> select "Advanced extraction (if installed)"
Uploaded attachment/sample is shared for "inherit"
Event was created for "This Community only"

Correct behaviour was observed on a MISP instance version f106b303b1159247926403f0c3d95e082dbb9b3f

### Actual behavior
Uploaded attachment/sample is actually shared for "Organisation", not inherit

**Comment by iglocska** [comment]
Thanks for the heads-up!
