### ISSUE TITLE
CakeResque not properly working

### ISSUE THREAD

**Issue by TheManInTheSuit** [MISP/MISP#287]
Having a new installation with MISP, and the following issue (after following all instructions).   Indeed when the last 3 lines are commented in bootstrap.php, it complains that the CakeResque plugin could not be found (Error: Plugin CakeResque could not be found.).

However, after having everything in place, and commenting out the 3 lines to activate the CakeResque plugin in bootstrap.php, I'm getting another error (and the GUI goes down saying internal error occurred):
# ./start.sh

PHP Fatal error:  require_once(): Failed opening required '' (include_path='/var/www/MISP/lib:.:/usr/share/php:/usr/share/pear') in /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php on line 103
PHP Stack trace:
PHP   1. {main}() /var/www/MISP/app/Console/cake.php:0
PHP   2. ShellDispatcher::run() /var/www/MISP/app/Console/cake.php:33
PHP   3. ShellDispatcher->__construct() /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:65
PHP   4. ShellDispatcher->_initEnvironment() /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:54
PHP   5. ShellDispatcher->_bootstrap() /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:98
PHP   6. require() /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php:136
PHP   7. Configure::bootstrap() /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php:175
PHP   8. include() /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php:92
PHP   9. CakePlugin::loadAll() /var/www/MISP/app/Config/bootstrap.php:235
PHP  10. CakePlugin::load() /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php:128
PHP  11. CakePlugin::bootstrap() /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php:99
PHP  12. CakePlugin::_includeFile() /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php:167
PHP  13. include() /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/CakePlugin.php:247
PHP  14. CakeResque::init() /var/www/MISP/app/Plugin/CakeResque/Config/bootstrap.php:23

Any ideas on what I missed? 

Cheers,
TMITS

**Comment by sbilly** [comment]
ubuntu 14.04 installation documents do not updated?
