### ISSUE TITLE
Problems updating MISP from the GUI

### ISSUE THREAD

**Issue by dndlion** [MISP/MISP#2870]
When I try to update from Server Settings > Diagnostics, I get the following message:

git pull origin  2>&1

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

=================================

git submodule init && git submodule update 2>&1

Pretty sure I followed the installation instructions https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian9.txt completely.

What's the best way to fix this?

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian
| OS version (client)       | 9
| PHP version               | 7.0.27-0+deb9u1
| MISP version / git hash   |  v2.4.84 (ced7db17e9418e9033053f18bc91323a840d08ef)	
| Browser                   | Chrome

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/18151769/35282726-22778760-004e-11e8-8bda-eb8193164866.png)

**Comment by iglocska** [comment]
Run the following commands to resolve it:

```
cd /var/www/MISP
git checkout 2.4
```

After that it should work fine.

**Comment by dndlion** [comment]
Thanks very much for your help.
