### ISSUE TITLE
Unable to make GET request for /tags

### ISSUE THREAD

**Issue by alecisec** [MISP/MISP#2873]
MISP version 2.4.86 - In some environments I'm unable to make a mispdomain.com/tags XML request with appropriate authorization in a curl command. Both /events and /attributes return the correct XML however. I could probably provide additional information if were to know more about where in the code these calls are processed and what differentiates /tags from the other two requests.

**Comment by alecisec** [comment]
Have determined this is due to memory issues - Apache will log events such as "[Wed Jan 24 03:23:55.120205 2018] [mpm_prefork:error] [pid 1064] (12)Cannot allocate memory: AH00159: fork: Unable to fork new process"
note this does not occur with calls to /events or /attributes
restarting apache2 service tends to resolve temporarily

**Comment by iglocska** [comment]
Interesting. How much memory do you have on your server and what is the max_memory that PHP can use?

**Comment by alecisec** [comment]
Resolved by increasing memory - as @iglocska indicated the /tag function uses too much memory

**Comment by adulau** [comment]
Thank you for the feedback.
