### ISSUE TITLE
OVA demo image broken?

### ISSUE THREAD

**Issue by mino98** [MISP/MISP#2874]
Hi,
just to let you know that the latest (2.4.86, as of writing) demo OVA from [here](https://www.circl.lu/misp-images/latest/) seems to throw "internal server error" if you simply download and run it.

Am I missing any required step?
Thanks.

<img width="801" alt="screen shot 2018-01-24 at 08 45 19" src="https://user-images.githubusercontent.com/27546434/35322732-39d00c08-00e3-11e8-81a3-6a35283c96b6.png">

**Comment by iglocska** [comment]
Woah, ok need to test that.

**Comment by adulau** [comment]
Mmm it could happen especially that VMs are generated on-the-fly at each commit ;-)

**Comment by adulau** [comment]
But you can take a previous version if needed:

https://www.circl.lu/misp-images/

**Comment by Th4nat0s** [comment]
I do confirm, I downloaded the last one,  I had to relauch the SQL script to inilialize the db,  and tha'ts it.

**Comment by adulau** [comment]
It's now fixed (multiple updates in [misp-vagrant](https://www.github.com/MISP/misp-vagrant)). 

https://www.circl.lu/misp-images/latest/

Feel free to reopen if you have any issues.
