### ISSUE TITLE
BASEURL protocol is not used in constructing 302 redirects

### ISSUE THREAD

**Issue by alecisec** [MISP/MISP#2876]
This is possibly a lack of understanding on my behalf of how the software is supposed to react, but when navigating to the base URL my browser will receive a 302 redirect to http://example.com/users/login however my BASEURL in the config.php is set to https://example.com/. given that port 80 isn't available this results in the browser hanging.

**Comment by iglocska** [comment]
Hmph. If the baseurl is set to https://example.com then it should redirect you to https://example.com/users/login so that sounds weird.

**Comment by alecisec** [comment]
Configs as follows - 

/etc/apache2/sites-enabled/misp.conf

<VirtualHost *:80>
        ServerAdmin me@me.local
        ServerName example.com
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
        Header set X-Content-Type-Options nosniff
        Header set X-Frame-Options DENY
</VirtualHost>


config.php - 

<?php
$config = array (
  'debug' => 0,
  'MISP' =>
  array (
    'baseurl' => 'https://example.com',
    'footermidleft' => '',
    'footermidright' => '',
    'org' => 'ORGNAME',
    'showorg' => true,
    'threatlevel_in_email_subject' => true,
>
etc....


apologies for the formatting, not sure how to avoid that....


note that this instance sits behind a load balancer which performs TLS so the apache server is configured to listen on port 80 without SSL...



I suspect I may require customizations to the .htaccess file in /webroot/ in order to support this implementation...

**Comment by alecisec** [comment]
The following test makes this clearer


**~$ curl -k https://example.com -D header**
**~$ cat header**
HTTP/1.1 302 Found
Date: Thu, 25 Jan 2018 02:04:32 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Server: Apache/2.4.18 (Ubuntu)
Location: http://example.com/users/login
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

**Comment by alecisec** [comment]
Standard 'CakePHP' force-HTTPS changes to app/webroot/.htaccess do not resolve this, suspect the 302 is constructed by MISP/app/Controller/AppController.php or elsewhere, I'm no expert so I can't be sure.

**Comment by alecisec** [comment]
Workaround for --

add to etc/apache2/sites-enabled/misp.conf

RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-Proto} =http
RewriteRule . https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]

and then open port 80 on load balancer

**Comment by iglocska** [comment]
It looks like your misp.conf is misconfigured. You are listening on port 80, make sure you use the ssl sample config file.

**Comment by alecisec** [comment]
Deliberately listening on 80, SSL is done on the load balancer in front. The solution I posted is actually the correct process

**Comment by ghost** [comment]
I just spent time a few hours fighting with this same setup:

AWS load balancer on 443 terminating SSL and forwarding to a MISP server on port 80, but the redirect after a form submission returns an http URL.  For example, `POST /admin/organisations/edit/1` returns 302 with `Location: http://servername/admin/organisations/view/1`.

Adding this to `bootstrap.php` fixed the form result redirect problem for me:

```php
if (Configure::read('MISP.baseurl')) {
        Router::fullBaseUrl(Configure::read('MISP.baseurl'));
}
```

The load balancer is not listening on port 80, and doesn't need to since the redirects are correctly going to `https` now.  I have removed all the various apache configurations I found and everything still appears to work.

**Comment by stephen-oleary** [comment]
@asaba-gl brilliant, thanks for that, I was in the exact same situation and this has resolved my issue!

**Comment by garvsd** [comment]
@iglocska this fix for router does work but this further blocks so much more like the cake console workers don't spin up. Am on tag 2.4.144 and have nearly same scenario with MISP running behind proxy handling SSL.

Am unable to figure the right solution to this, and have two environments where in one there is a successful 302 to 301 for managing the http to https but it fails after 302 in another. Both have security force-https enabled. Any thoughts would be appreciated.
