### ISSUE TITLE
attribute count on event view page is incorrect with object

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#2878]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| MISP version / git hash   | 2.4.86

### Actual behavior
An event containing objects will show an incorrect amount of attributes on the event view page. However the count is correct on the event list page.

Event list:
![image](https://user-images.githubusercontent.com/1073662/35393154-766efdfc-01e4-11e8-9979-3af2f3cc8d85.png)

Event view page:
![image](https://user-images.githubusercontent.com/1073662/35393181-87f31c34-01e4-11e8-8013-c2b449d95b08.png)

### Steps to reproduce the behavior
- create event with object containing object-attributes
- open the event page to see the content of the event, notice the discrepancy between the amount of attributes and the count.

**Comment by iglocska** [comment]
Probably an old event, new events do this correctly. Give it a shot, create a new event, add an object with 2 attributes, it will show 2 on the event index. Will close it for now, but feel free to reopen it if you still have the issue with new events.

**Comment by cvandeplas** [comment]
I just created my event 15 minutes ago

**Comment by iglocska** [comment]
Well crap.

**Comment by iglocska** [comment]
How did you create the object? Add object?

**Comment by cvandeplas** [comment]
yes manually, or via the API.

**Comment by StefanKelm** [comment]
Weird... I had reported this one earlier (https://github.com/MISP/MISP/issues/2543#issuecomment-334450476) but it now works fine for us...

**Comment by iglocska** [comment]
Yeah, I am surprised that it's broken, tried to reproduce it now and it behaves as expected...

**Comment by cvandeplas** [comment]
rebooted my VM and now it's OK.

**Comment by iglocska** [comment]
If only all issues would go away this easily...
