### ISSUE TITLE
remove the news page (and related features)

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#288]
It seems that the news page is not really used and completely outdated.
Perhaps it's a good idea to remove that hardcoded page ?

**Comment by Rafiot** [comment]
Gone, right?

**Comment by iglocska** [comment]
It's still there and unused, but it's not the default landing page anymore.
I'll remove it and I'll reimplement it in a smarter way if we want it again.

**Comment by Rafiot** [comment]
yeah, so closing.

**Comment by geekscrapy** [comment]
Still there?! 😆

**Comment by iglocska** [comment]
It's there but no longer a static page. You can add messages at an admin and have your own news messages there :)
