### ISSUE TITLE
MISP Redis Issues with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by serrastusbear** [MISP/MISP#2885]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Error
| OS version (server)       | Ubuntu 16.04 LTS
| OS version (client)       | <any>
| PHP version               | 7.0
| MISP version / git hash   | v2.4.86 (04c89499a234da5d6596a711fb65522b5c793a23)	
| Browser                   | N/A

### Expected behavior
Automated worker start and /var/www/MISP/app/Console/worker/start.sh return with no errors.

### Actual behavior
Continue to receive the following error:
Error: Redis server went away
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(450): CakeResqueShell->startup()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('stop', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)

### Steps to reproduce the behavior
Install MISP following INSTALL instructions on new Ubuntu Server 16.04 LTS instance.

### Logs, screenshots, configuration dump, ...

Relevant logs:

2018-01-27 19:36:16 Error: [RedisException] Redis server went away
Request URL: /jobs/cache/csv_all
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(123): Resque::redis()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(76): Resque::push('cache', Array)
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(169): Resque_Job::create('cache', 'EventShell', Array, true)
#7 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(140): Resque::enqueue('cache', 'EventShell', Array, true)
#8 /var/www/MISP/app/Model/Job.php(65): CakeResque::enqueue('cache', 'EventShell', Array, true)
#9 /var/www/MISP/app/Controller/JobsController.php(127): Job->cache('csv', Array)
#10 [internal function]: JobsController->cache('csv_all')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(JobsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2018-01-27 19:42:21 Error: [RedisException] Redis server went away
Request URL: /servers/restartWorkers
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(3285): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(1126): Server->workerRemoveDead(Array)
#6 [internal function]: ServersController->restartWorkers()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

Checked existing issues for Redis problems - these did not appear to be the same, as Redis is active/listening (redis-cli returns expected results, Redis service is running, no network issues such as FW settings blocking traffic). Permissions are all for www-data user in relevant areas, no permission issues encountered.

**Comment by adulau** [comment]
I remember one or two similar issues with others users (#2104). Could it be that the firewall rules only apply for IPv4 and not IPv6 (or the reverse)? Maybe a `tcpdump` on the local network for TCP port 6379 could give some info?

**Comment by serrastusbear** [comment]
Interesting! So my IPv4 FW settings were set up to allow this, but my IPv6 settings are (generally) very restrictive - and this seemed to clear things up. 

Redis is up and detected now via both IPv4 and v6 and I'm able to start workers - but strangely enough, it only worked manually at first. That's an issue I can debug on my own though. This seems a very silly sort of mistake on my end, but thank you for pointing me in the right direction!
