### ISSUE TITLE
Bug in the API for managing sharing groups

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2888]
~~~~
​​​​
Just an update. The same two issues exist in 2.4.87.

Thank you for the 2.4.86+ release since it gave us the much needed sharing groups API, now we just need to make sure that we can remove teams from sharing groups via the API. (adding orgs into sgs seems to work)

To add some more details. In both cases, the response is a normal 200, misp happily accepts the request. It just ignores any changes to the organization fields other than the "name" and also doesn’t remove an organization from a sharing group if it is missing from the updated version that we send to it.

~~~~

**Comment by kyr-stefanidis** [comment]
1. Cannot update the organizations that belong to a sharing group (SharingGroupOrg). Once we create a sharing group with some organizations in it, we cannot remove organizations from the sharing group via the api.

2. Cannot update the fields of an organization apart from the name. Nationality, Sector and Description cannot be updated

In both cases, the response is a normal 200, misp happily accepts the request but doesn't do the update

**Comment by iglocska** [comment]
This is now tackled by a list of new APIs, have a look at the commit message, it should be pretty straight forward. Let us know if you have further issues with this!
