### ISSUE TITLE
/attributes/restSearch/ API large slowdown on enabling enforceWarninglist

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#2889]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug/Optimization
| OS version (server)       | Debian 9
| OS version (client)       | Debian 9
| PHP version               | 7.0
| MISP version / git hash   | 2.4.85
| Browser                   | Curl

### Expected behavior
The expected behavior is a bit faster response 

### Actual behavior
Slow response when enabling "enforceWarninglist" on the "/restSearch" API

### Steps to reproduce the behavior
I've enabled all the Warninglists that a published

The timestamp "1514567505" = search data one month backwards

```
time curl -H "content-type: application/json" -H "Authorization: [REDACTED]" -H "Accept: application/json" "https://misp.[REDACTED].dk/attributes/restSearch/json/" -X POST -d '{"timestamp":1514567505,"type":["ip-src","ip-dst"]}' > /dev/null 2>&1

real	0m2.612s
user	0m0.024s
sys	0m0.012s

```
-------

```
time curl -H "content-type: application/json" -H "Authorization: [REDACTED]" -H "Accept: application/json" "https://misp.[REDACTED].dk/attributes/restSearch/json/" -X POST -d '{"timestamp":1514567505,"published":"true","type":["ip-src","ip-dst"]}' > /dev/null 2>&1

real	0m0.233s
user	0m0.024s
sys	0m0.012s

```
-------

```
time curl -H "content-type: application/json" -H "Authorization: [REDACTED]" -H "Accept: application/json" "https://misp.[REDACTED].dk/attributes/restSearch/json/" -X POST -d '{"timestamp":1514567505,"published":"true","type":["ip-src","ip-dst"],"enforceWarninglist":"false"}' > /dev/null 2>&1

real	0m0.179s
user	0m0.024s
sys	0m0.008s

```
--------

*Massive time increase*

```
time curl -H "content-type: application/json" -H "Authorization: [REDACTED]" -H "Accept: application/json" "https://misp.[REDACTED].dk/attributes/restSearch/json/" -X POST -d '{"timestamp":1514567505,"published":"true","type":["ip-src","ip-dst"],"enforceWarninglist":"true"}' > /dev/null 2>&1

real	1m18.422s
user	0m0.032s
sys	0m0.012s

```
-------

If I disable the two large warninglists:

- List of known IPv4 public DNS resolvers
- List of known public DNS resolvers expressed as hostname

```
time curl -H "content-type: application/json" -H "Authorization: [REDACTED]" -H "Accept: application/json" "https://misp.[REDACTED].dk/attributes/restSearch/json/" -X POST -d '{"timestamp":1514567505,"published":"true","type":["ip-src","ip-dst"],"enforceWarninglist":"true"}' > /dev/null 2>&1

real	0m12.849s
user	0m0.024s
sys	0m0.012s

```
--------------------------------------
The reason looks to be due to the match of amount of a combination of returned values and amount of data in warninglists

Pseudo code:
```
foreach ($values as $value){
   foreach ($warninglists as $warninglist){
      if($warninglist == $value){
         
      }
   }
}

```
This will growth exponential when more data and/or warninglist, I don't know if it could be optimized if there were an "array_diff", meaning a simular function to the below, but will match entire array to array of warninglists

Model/Warninglist.php
```
public function filterWarninglistAttributes($warninglists, $attribute) {
                foreach ($warninglists as $warninglist) {
                        $result = $this->__checkValue($warninglist['values'], $attribute['value'], $attribute['type'], $warninglist['Warninglist']['type']);
                        if ($result !== false) {
                                return false;
                        }
                }
                return true;
}
```

**Comment by iglocska** [comment]
Issue identified and should be fixed now. The warninglist performance overhead is near 0 now :) Let us know if it persists!
