### ISSUE TITLE
POST /tags/add adds a tag with empty "name" field

### ISSUE THREAD

**Issue by kyr-stefanidis** [MISP/MISP#2897]
### Work environment

MISP version 2.4.85

### Input
Adding a new tag via the POST /tags/add API
{
   "name":"new_tag",
   "colour":"#a4f124",
   "exportable":true,
   "org_id":false,
   "hide_tag":false
}

### Expected behavior
Should create a new tag and return:
{
    "id": "1",
    "name": "new_tag",
    "colour": "#de4f78",
    "exportable": true,
    "org_id": false,
    "hide_tag": false,
    "user_id": "0",
    "count": 0,
    "attribute_count": 0
}

### Actual behavior
It creates a new tag but the field "name" is an empty string. The POST request responses with:
{
    "id": "1",
    "name": "",
    "colour": "#de4f78",
    "exportable": true,
    "org_id": false,
    "hide_tag": false,
    "user_id": "0",
    "count": 0,
    "attribute_count": 0
}

**Comment by iglocska** [comment]
Thanks for the heads-up, this was a slightly different issue - basically the API expected the tag object to be encapsulated into "Tag": {} - as you can see the colour value was also changed as MISP basically didn't get any valid data so it just used sane defaults.

I've changed it to not require the encapsulation, so let us know if the issue persists in any way!
