### ISSUE TITLE
Create a gene attribute type

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2900]
Create a [gene](https://github.com/0xrawsec/gene) attribute type.

**Comment by adulau** [comment]
@adulau Note to self. Create also a sysmon object template.

**Comment by iglocska** [comment]
He's talking to himself again. We need to increase the dosage of drugs.

**Comment by adulau** [comment]
Added in https://github.com/MISP/MISP/commit/65b437514398e0e2e4743db05d3bc3a9e3590cf3
