### ISSUE TITLE
Database not completely set up after installing MISP

### ISSUE THREAD

**Issue by Res260** [MISP/MISP#2901]
Im trying to understand why, but it seems `updateMISP()` in `AppModel.php` was never called and now I get errors because of that. 

I think I followed the INSTALLubuntu.txt file pretty well.

I need to know what triggers the `updateMISP()` function, can anyone help me?

**Comment by iglocska** [comment]
Could you run a git pull and try it again? I think I found what's going wrong.

**Comment by iglocska** [comment]
I mean try again logging in, not setting it up from scratch of course.

**Comment by Res260** [comment]
Actually I started from scratch because I messed up somewhere else (I'm bad with git), but now it works! Thanks :+1:

**Comment by iglocska** [comment]
Great news, thanks for the feedback!
