### ISSUE TITLE
WebUI Error under Ubuntu 17.10

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/MISP#2903]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

I have just upgraded (a little late) from 17.04 -> 17.10 and this seems to have broken MISP
When i try and visit the URL all i get in the browser is the following

dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding')))); 

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | bug
| OS version (server)       | Ubuntu 17.10
| OS version (client)       | Windows 10, IE, Chrome, FireFox
| PHP version               | 7.1.11-0ubuntu0.17.10.1
| MISP version / git hash   | Latest commit
| Browser                   | IE , Chrome, FireFox

### Expected behavior
WebGUI loging screen

### Actual behavior
this is displayed in the browser.

dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding')))); 

### Steps to reproduce the behavior
Restore from snapshot of 17.04 and do upgrade again, and i get the same result.
followed through the install docs and this did not resolve the issue.

### Logs, screenshots, configuration dump, ...

Nothing changes with MISP , only the OS upgrade

**Comment by adulau** [comment]
I cannot reproduce it. FYI, the [default VM](https://www.circl.lu/misp-images/latest/) are using Ubuntu 17.10 with PHP 7.1.11. 

Could you remove the files from the cache model in MISP tmp? Not sure if this is the origin of your issue.

**Comment by SparkyNZL** [comment]
Hi , thanks for the prompt reply, 

I have carried out and (see screen shot) this made no difference , it really is very odd. as if i revert back to 17.04 everything works as expected, the only difference is the upgrade.

**Comment by SparkyNZL** [comment]
![screenshot from 2018-02-04 11-28-13](https://user-images.githubusercontent.com/17818264/35772222-daca14fa-099e-11e8-9358-ae4249a1272f.png)

**Comment by SparkyNZL** [comment]
I have also reissued the permissions as per the installation just in case i have missed something.

**Comment by SparkyNZL** [comment]
Looking at the source 

-------------------------------------------------------------------------------------
/**
 * Editing below this line should NOT be necessary.
 * Change at your own risk.
 *
 */
if (!defined('WEBROOT_DIR')) {
	define('WEBROOT_DIR', basename(dirname(__FILE__)));
}
if (!defined('WWW_ROOT')) {
	define('WWW_ROOT', dirname(__FILE__) . DS);
}

if (!defined('CAKE_CORE_INCLUDE_PATH')) {
	if (function_exists('ini_set')) {
		ini_set('include_path', ROOT . DS . 'lib' . PATH_SEPARATOR . ini_get('include_path'));
	}
	if (!include ('Cake' . DS . 'bootstrap.php')) {
		$failed = true;
	}
} else {
	if (!include (CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'bootstrap.php')) {
		$failed = true;
	}
}
if (!empty($failed)) {
	trigger_error("CakePHP core could not be found.  Check the value of CAKE_CORE_INCLUDE_PATH in APP/webroot/index.php.  It should point to the directory containing your " . DS . "cake core directory and your " . DS . "vendors root directory.", E_USER_ERROR);
}

App::uses('Dispatcher', 'Routing');

$Dispatcher = new Dispatcher();
**$Dispatcher->dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding'))));**
-------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
OK so after snapshotting and reproducing this error reliably I can say this, when upgrading from 17.04 -> 17.10 and you click "Remove" obsolete packages, this will break MISP, Even if you follow the installation process for MISP again it does not fix the issue. 

I hope this helps others out

Cheers

**Comment by ancailliau** [comment]
We experienced the same issue. The PHP file is not executed as it should be but is displayed by Apache as a text file. 

Check if php module is enabled in Apache. 

For us, the module mpm_event prevented the module php7.2 to be loaded. 

    a2dismod mpm_event

solved the problem.

**Comment by jimanderles** [comment]
I had the same issue!

 I solve it with this Url:

https://yonedev.com/snippet/ubuntu-16-04-instalar-php-5-6-php-7-0/
