### ISSUE TITLE
Get attributes in ranges 

### ISSUE THREAD

**Issue by shiraGoldman** [MISP/MISP#2904]
I'm quite new to MISP and I couldn't find a solution to my following problem.
I have lots of attributes and I don't want to get them all at once, but in ranges (something like Range header in HTTP).
Is there any option to do it with any API, using headers or request body, or maybe in another way? I thought to use RESTful search API but if there is another way (even not through the APIs) I'm not picky.
Thanks

**Comment by adulau** [comment]
This has been implemented in the API (2.4.96 and upper). You can now do such query via restSearch (events or/and attributes level):

~~~~
{
    "returnFormat": "json",
    "last": "1d",
    "page": 1,
    "limit": 5
}
~~~~

Documentation is the following (available via MISP):

- `limit` Limit the number of results returned, depending on the scope (for example 10 attributes or 10 full events).
- `page` If a limit is set, sets the page to be returned. page 3, limit 100 will return records 201->300).
