### ISSUE TITLE
Config mismatch from servers/serverSettings/MISP versus config files

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#291]
Another interesting bug? from 2.2. to 2.3 upgrade. 

I have a bootstrap.php config file containing the configuration and that's the one used and read by MISP. 

On the other hand, the web interface servers/serverSettings/MISP is showing complete different settings.

As an example, I have in the bootstrap.php config:

Configure::write('MISP.showorg', 'true')

On the other hand the serverSettings panels shows the opposite.

But the server is running with the proper configuration.

Is that intended?

**Comment by Rafiot** [comment]
Probably fixed.

**Comment by iglocska** [comment]
Indeed, as long as you use a 2.3+ bootstrap.php the correct file will be
read. config.php contains all of the settings that are configurable via the
UI as an array.

**Comment by Rafiot** [comment]
And if you have anything <2.3, you have other problems anyway.
