### ISSUE TITLE
Strange UI issue

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#2913]
Using a 2.4.87 instance (and a fresh _git pull_) there's this quite strange UI error which I'm unable to reproduce (and explain, actually).

One some attributes the UI shows:
![1](https://user-images.githubusercontent.com/25325656/35974938-3fbdbbe8-0cdb-11e8-9866-2ba162bc0e32.png)

while a click on "more" leads to the expected UI output:
![2](https://user-images.githubusercontent.com/25325656/35974960-58d1bf58-0cdb-11e8-9db3-beed85b696be.png)

Thoughts anyone?

**Comment by iglocska** [comment]
What the hell.
