### ISSUE TITLE
Deletion of multiple attributes is logged as events modification.

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#2914]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.87

### Expected behavior
- Deletion of multiple attributes are logged as such. Either one log entry with all the attribute IDs and values deleted or one log entry per attribute deleted.

### Actual behavior
- Deletion of multiple are logged as events modification

### Steps to reproduce the behavior
- Create an event.
- Create multiple attributes.
- Select them with the checkbox for deletion.
- Click the delete icon on top of the column.
- Check the event history, the log display that the event was modified but does not show that attributes were deleted.

**Comment by adulau** [comment]
It's correct. Delete are soft-delete which a modification of a flag ;-)
