### ISSUE TITLE
Integration from MISP to Qradar

### ISSUE THREAD

**Issue by rmeghnagi** [MISP/MISP#2915]
Hi all,

I would like to integrate my MISP Platform with IBM Qradar (To permit at Qradar to get the IoCs from MISP) but i saw on IBM xforce website that was developped an app to allowed this integration only with a Taxii Server.

Has Someone developped an API to permit the integration from MISP to Qradar?

Any suggestion is welcome!

Best Regards
R.

**Comment by adulau** [comment]
Good question. We would be glad to have a connector for IBM QRadar but as far as I know all the modules are proprietary (as some integrators do their business that way ;-(). 

There were some old STIX import for QRadar (where you could export from STIX in MISP but the format of MISP contains much more information than STIX):

https://github.com/ibm-security-intelligence/data-import/tree/master/stix-import

The best would be a clean integration like the ones existing for Splunk [https://github.com/remg427/misp42splunk](https://github.com/remg427/misp42splunk) and [ta-misp](https://github.com/stricaud/TA-misp).

**Comment by rmeghnagi** [comment]
Thank you for your answer. I found an IBM App but is necessary to have an Taxii Server for integrate it with Qradar... I wrote on github hoping someone having developed an API for this integration...

**Comment by TiagoSantos84** [comment]
@rmeghnagi 
Hi, did you already integrate MISP with qradar?

Best regards,

**Comment by adulau** [comment]
You might be interested by the following work:

https://github.com/robertnixon2003/QRadar_MISP_Integration

**Comment by TiagoSantos84** [comment]
@adulau 

Thank you for your sharing.

However, I would like to integrate with native Taxii Feed in SIEM.

I would like to know if its possible to push IoC from MISP to TAXII server and then pull them from SIEM.

Thank you for your help. It will be my second option.

**Comment by adulau** [comment]
Do you really want to use TAXII? QRadar has a good ReST API.

https://github.com/ibm-security-intelligence/api-samples

Maybe it's cleaner and easier.

**Comment by rmeghnagi** [comment]
Hi Tiago,

I use Minemeld to push the Misp events inside a Feed Stix and than pull them from Qradar.

Let me know if you want more details.

Regards!
R.

**Comment by TiagoSantos84** [comment]
@rmeghnagi 

If it's to put IoC from MISP in Qradar I will appreciate your help!

1) Installation of Minemeld;
2) Feed Stix
3) Is in the Qradar feed Taxii config that you configure the IoC feed to build reference set?

Thank you in advance!

**Comment by ghost** [comment]
@adulau 
https://github.com/robertnixon2003/QRadar_MISP_Integration

This link is not working

**Comment by adulau** [comment]
It seems he recently changed the repository:

https://github.com/robertnixon2003/MISP-QRADAR-REFERENCE-SET-BUILDER

**Comment by ghost** [comment]
Thank you. 
Do you also  have a link with MISP-arcsight and MISP-ELK integration?

**Comment by ghost** [comment]
Hello @adulau 
Which SIEM platforms we can integrate with MISP?

**Comment by adulau** [comment]
Any ;-) You should have a look the existing implementation for Splunk like https://github.com/stricaud/TA-misp or https://github.com/remg427/misp42splunk .

http://www.misp-project.org/tools/

You should also have a look at the presentation about the MISP integration: https://circl.lu/assets/files/misp-training/luxembourg2017/integration.pdf and especially the ZMQ pub-sub channel.

**Comment by ghost** [comment]
@adulau  Thank you for a confirmation and sharing of very useful resources.

**Comment by ghost** [comment]
@adulau 
Hello,
I didn't understand relation between of ZMQ pub-sub channel  and opentaxii in MISP?

**Comment by pasket** [comment]
MISP + Minemeld + QRadar sounds as a good combination. It will solve the integration with MISP and will allow you to integrate other feeds following the same strategy. 

1. Misp + Minemeld Integration (https://github.com/PaloAltoNetworks/minemeld-misp)
2. Minemel + QRadar Integration (https://live.paloaltonetworks.com/t5/MineMeld-Articles/Integrating-MineMeld-with-IBM-QRadar/ta-p/143293)

My concer is with Threat Intelligence app for QRadar (https://exchange.xforce.ibmcloud.com/hub/extension/IBMQRadar:ThreatIntelligence). I've tried to install it but there is something wrong and it appears as installed with errors.
