### ISSUE TITLE
incident correlation ?

### ISSUE THREAD

**Issue by adhamai** [MISP/MISP#2918]
Hello,

One of the Technical investigations that you provide is Incident correlation. and I am doing a research on what operations we can apply to the shared cyber threat information. 

What are the main algorithms/methods you are considering for the Incident correlation? 

Thank you,
Adham

**Comment by RichieB2B** [comment]
String matching, mostly.

**Comment by adulau** [comment]
String matching and CIDR block matching in advanced correlation. The correlation is automatic and can be disabled on request at attribute level.
