### ISSUE TITLE
Freetext import is removing backslashes in file path

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2926]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04.3
| PHP version               | 7.0
| MISP version / git hash   | v2.4.87 (e651052634eec2f7f0dbf15d7d9a7c51ed1de97a)

### Expected behavior
Free-text import pulls out filename and file paths 

### Actual behavior
It is extracting file names with the full path but it is removing the backslashes causing the file path to be one long string.

### Steps to reproduce the behavior
See screenshot below.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/20773170/36151407-1b5e18ca-1095-11e8-8256-1ef0aff9151f.png)

![image](https://user-images.githubusercontent.com/20773170/36151423-25406b86-1095-11e8-8274-a2b02ac7ede7.png)

**Comment by iglocska** [comment]
Well that was pretty stupid. Thanks for the heads-up and for the reproduction of the issue!
