### ISSUE TITLE
ZMQ Error Address already in use

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#2929]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04.3
| OS version (client)       | Windows 10
| PHP version               | 7.0
| MISP version / git hash   | v2.4.87 (e651052634eec2f7f0dbf15d7d9a7c51ed1de97a)	

I am getting the following error for the MISP ZQM:
Any ideas?
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 103, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 71, in main
    socket.bind("tcp://*:%s" % settings["port"])
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

```

![image](https://user-images.githubusercontent.com/20773170/36174708-12c89168-10db-11e8-9024-35886117b723.png)

![image](https://user-images.githubusercontent.com/20773170/36174731-31ff696c-10db-11e8-9a65-fcf39838ae91.png)

**Comment by syloktools** [comment]
I had some rouge ZMQ processes running that I had to kill -9. They were related to getting the MISP Dashboard working. I exited the processes but they actually never died. I found they and exterminated them and then everything was right in the world again.

**Comment by iglocska** [comment]
Burn the heretic. Kill the mutant. Purge the unclean.
