### ISSUE TITLE
Merge overhead work and inconsistencies

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#2931]
Related to #2930:

Scenario part I:
- Add local org with a random UUID.
- Get notified that the org is remotely known.
- Try to change the UUID to the given remote one.
- MISP fails (see #2930) to update the org.

Scenario part II:
- Merge organisations - local into external
- Relationship between local users and remote org are not shown in org view
- change the merged organisation
- change the name (-> icon is lost)
- change from remote to local

All of that could be proposed in the case of Scenario part I.

**Comment by iglocska** [comment]
This has been resolved last week.
