### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#2935]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 8 RedHat 7
| OS version (client)       | Windows 7
| PHP version               | PHP 5.6.33-0+deb8u1 and Redhat PHP 7.1.8
| MISP version / git hash   | {"major":2, "minor":4, "hotfix":87}
| Browser                   | Chrome

### Expected behavior
No errors 

### Actual behavior
PDO error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Error: An Internal Error Has Occurred.

Stack Trace
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 470 → PDOStatement->execute(array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 436 → DboSource->_execute(string, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 673 → DboSource->execute(string, array, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 1184 → DboSource->fetchAll(string, boolean)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3038 → DboSource->read(Tag, array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3010 → Model->_readDataSource(string, array)
APP/Controller/TaxonomiesController.php line 31 → Model->find(string, array)
[internal function] → TaxonomiesController->index()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(TaxonomiesController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(TaxonomiesController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

### Steps to reproduce the behavior
Login into a fresh installation of MISP choose "Event Actions" -> "List Taxonomies" and click update

### Logs, screenshots, configuration dump, ...
![2018-02-14 14_52_57-errors - misp google chrome](https://user-images.githubusercontent.com/14878613/36207642-db262f1a-1196-11e8-9114-5fc2dbdd20b5.jpg)

**Comment by eCrimeLabs** [comment]
Seems after an:
```
git checkout 2.4
M       PyMISP
M       app/Console/worker/start.sh
M       app/composer.json
M       app/files/misp-galaxy
M       app/files/misp-objects
M       app/files/taxonomies
Previous HEAD position was f6b9e07... chg: version bump
Switched to branch '2.4'

```

Everything seems to work again

**Comment by eCrimeLabs** [comment]
Seems after an:
```
git checkout 2.4
M       PyMISP
M       app/Console/worker/start.sh
M       app/composer.json
M       app/files/misp-galaxy
M       app/files/misp-objects
M       app/files/taxonomies
Previous HEAD position was f6b9e07... chg: version bump
Switched to branch '2.4'

```

Everything seems to work again

**Comment by Alaa-HIjazi** [comment]
Same issue on List of feed only : Column not found: 1054 Unknown column 'Feed.orgc_id' in 'on clause'
![image](https://user-images.githubusercontent.com/54832687/80723477-f848c180-8b00-11ea-92c9-df6d1aaf70a8.png)

**Comment by mokaddem** [comment]
@Alaa-HIjazi are you update to date with the latest version?
Did you run into issue while updating?
Can you check the output of the db diagnostic in the `diagnostic` tab?
Thanks

**Comment by Alaa-HIjazi** [comment]
Yes, and it's solved, the issue was that i gived permission to another user to access the db, and it got all messed up, so i changed the db password in misp config files and fixed my db again,
Thank you !
