### ISSUE TITLE
Strange behaviour when approving the proposed attribute

### ISSUE THREAD

**Issue by LilaLipetti** [MISP/MISP#2943]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug ?
| OS version (server)       | MISP_v2.4.87@b341dc4843291dbe37c0da98ad8b4a83520dadf4.ova
| OS version (client)       | Ubuntu 16.04 LTS
| PHP version               | ...
| MISP version / git hash   | MISP_v2.4.87@b341dc4843291dbe37c0da98ad8b4a83520dadf4.ova
| Browser                   | firefox 58.01 64bit

Not so sure, but the user might not know that the approved attributes won't be synced.
By mistake this happened a lot to me while trying to understand how the sync works.

It was frustrated to figure out that I've approved attributes, but not published the event again as it was supposed to be done.

### Steps to reproduce the behavior
Find an event with proposal
![image](https://user-images.githubusercontent.com/10400146/36261286-8ecc0672-126c-11e8-8b58-8ada6b998b95.png)

Go to the event
![image](https://user-images.githubusercontent.com/10400146/36261336-ae15917e-126c-11e8-8cad-c2056346e18d.png)

Approve the proposal, note that the "publish event" will be shown
![image](https://user-images.githubusercontent.com/10400146/36261356-be27fc8c-126c-11e8-8633-ee72854d0445.png)

Change back to the event list page, or any other page than the event.
Then go back to the event.

![image](https://user-images.githubusercontent.com/10400146/36261395-db68fddc-126c-11e8-98f3-73209b43d805.png)

The "Publish Event" has been disappeared. And user won't know that the approved data won't synced at all.

**Comment by iglocska** [comment]
Accepting a proposal unpublishes the event, not sure I understand what the issue here is. Anything that modifies data unpublishes the event, be it an accepted proposal, edited attribute, added object, removed tag, etc.

**Comment by LilaLipetti** [comment]
Well I tried again and the based on the gui the status is still "published"..

**Comment by iglocska** [comment]
Ah, you mean the published flag doesn't get updated?

**Comment by LilaLipetti** [comment]
I suppose so....

**Comment by LilaLipetti** [comment]
So the publish flag doesn't change to "unbublished" as it should?

**Comment by iglocska** [comment]
Ah I see, ok was worried that it actually doesn't unpublish the event which would be a critical bug ;)

**Comment by LilaLipetti** [comment]
Hmmm.... Should I able to see on logs the change of the status flag?

**Comment by LilaLipetti** [comment]
![image](https://user-images.githubusercontent.com/10400146/36264730-38ea728e-1276-11e8-98b9-c8010d6fee95.png)

**Comment by iglocska** [comment]
No, definitely not, that shouldn't show up in itself. It is implied that any change to the event unpublishes it.

**Comment by LilaLipetti** [comment]
I suppose this should happen if I understand the sync correctly
- Org 1 is proposing an attribute
- org2 is accepting it (the way I describe it)
- in next sync the accepted attribute should be synced back to the org1
![image](https://user-images.githubusercontent.com/10400146/36265613-46b2caea-1278-11e8-8118-2b0eaf0ceaa1.png)

**Comment by LilaLipetti** [comment]
So if  I understood correctly
- org 1 is proposing attribute
-org2 is accepting (the way I did it)
- in next sync the data is synced back to org1
![image](https://user-images.githubusercontent.com/10400146/36265694-725476b2-1278-11e8-93a3-dcab80a94d0e.png)

**Comment by LilaLipetti** [comment]
![image](https://user-images.githubusercontent.com/10400146/36266846-2b93da80-127b-11e8-8cad-efba02eebb3b.png)

**Comment by LilaLipetti** [comment]
So the org1 doesn't see the approved attributes. Only way to get them is to edit the event on org2 and republish it.

**Comment by LilaLipetti** [comment]
I'm still pretty sure that approving the proposed attribute the way I do it, doesn't unpublish the event.

**Comment by LilaLipetti** [comment]
It might be easier to seen on video : [https://www.youtube.com/watch?v=uvbm3HIEvic](https://www.youtube.com/watch?v=uvbm3HIEvic)

**Comment by iglocska** [comment]
Thanks a lot, back at the office now and did some more testing - you are indeed correct it's a bug. Basically it only happens if you accept a proposal to add a new attribute and I've only tested with accepting an edit, something that didn't have the same symptoms.

Nice catch!
