### ISSUE TITLE
Search for an exact value 

### ISSUE THREAD

**Issue by claragpalacios** [MISP/MISP#2946]
Hi, 

We are having some troubles when we search for attributes in MISP.  The issue is that we need an exact match of what we are looking for, but we are having similar results instead. There are two examples of this below:

We look for the domain “as.com” and we have as a result all the domains that contain “as.com” for example: “madrid.as.com” “today.as.com” “cortas.com”.

We look for the IP address “123.25.26.22” and the results that we have are all the IP addresses that contain “123.25.26.22” even if they are not exact matches, for example “123.25.26.224” “123.25.26.228”.

Is there any way to have only exact matches?

Thank you in advance.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by RichieB2B** [comment]
Whoa, I’ll need to notify all MISP users when I install this update. A checkbox for substrIng searches would be much appreciated.

**Comment by iglocska** [comment]
This is the ui only search and there is a description of the new behavior above the search boxes.

**Comment by claragpalacios** [comment]
Hello,

as you recommended in the last post we updated the MISP version to 2.4.89. However, we found out that it is still not possible to make exact searches via API. (It is only possible through web interface)

Is there any way in which we could make exact searches or any intention of implement this feature any time soon?

Thank you in advance.
