### ISSUE TITLE
RFI:  Properly doing a backup

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#2951]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Help
| OS version (server)       | Debian
| OS version (client)       | Stretch
| PHP version               | 7.0
| MISP version / git hash   | 795a91bf9e347121d1961229a855eb9a1b453309
| Browser                   | Chrome

I'd like to know how to properly backup the install and db for my MISP instance.  Can someone point me in the right direction on a solid backup/restore method please?  Thank you much.

**Comment by iglocska** [comment]
Did you have a look at this yet?

https://github.com/MISP/MISP/tree/2.4/tools/misp-backup

**Comment by DigiAngel** [comment]
OMG...those MISP folks thought of everything..thanks so much!

**Comment by iglocska** [comment]
Haha, let us know if it doesn't work as expected ;)
