### ISSUE TITLE
MYSQL error

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/MISP#2952]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Hi,

Im getting the following error when changing over from y TEST environment to my Prod environment

-------------------------------------------------------------------------------------

2018-02-18 11:01:27 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip' in 'field list'
Request URL: /users/logout
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1090): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(Log), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/UsersController.php(1186): Model->save(Array)
#6 /var/www/MISP/app/Controller/UsersController.php(1008): UsersController->__extralog('logout')
#7 [internal function]: UsersController->logout()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
 
-------------------------------------------------------------------------------------

I understand the error but, what i dont understand is why ? 

all i am doing is swapping out my current prod front end with my test front end (New Prod), both are on the same build. Im just now pointing my test (new Prod) to the prod database. I have checked that i can login into mysql from my new prod environment and checked the privileges all look fine, It appears from the error that there is a colum IP in the field list on the prod database , but the old prod doesnt have any issues with that. I have copied over the exact PHP files from the /Config directory onto the new prod system. 

Any ideas or hints would be great ?

Thanks .

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
It is probably the IP logging setting. Normally when you flip it to on , it creates the additional table field. If you use the same database for a different instance where this was set already it might fail, first unset the setting, then switch DBs, then re-enable it to create the field.

**Comment by SparkyNZL** [comment]
your awesome, Ive been trying to track this down, but this makes sense.

Ill check this out

Cheers.

**Comment by iglocska** [comment]
I'll also add it to the default table list, it's silly to only create it on demand for the reasons you've described.

"Sure seemed like a good idea at the time!..."

**Comment by SparkyNZL** [comment]
This indeed fix the issue, but i cant turn it back on, so I think this may be a bug, but ill play around with this a bit more tomorrow. Thanks for your help

**Comment by iglocska** [comment]
Interesting! Let me know how it goes, I'll look into it on my side. My guess is that the request is utterly long if you have a big log table (it adds a field and sets a default for each row...)

**Comment by SparkyNZL** [comment]
Yeah I think the SQL query times out, i can't renable it as it still exists even when I turn it off , but I'll jump into the database more tomorrow.




Have a great day, MISP is an awesome product, keep up the great work, this is my guts to my threat stack.




Cheers




sent from my Space Ship...







On Sun, Feb 18, 2018 at 9:21 PM +1300, "Andras Iklody" <notifications@github.com> wrote:












Interesting! Let me know how it goes, I'll look into it on my side. My guess is that the request is utterly long if you have a big log table (it adds a field and sets a default for each row...)
