### ISSUE TITLE
Misleading failure message when failing to create Attributes

### ISSUE THREAD

**Issue by AJohnDoe** [MISP/MISP#2955]
A failure to create Attribute(s) will display a message at the top of the page with a [hardcoded](https://github.com/MISP/MISP/blob/2.4/app/Controller/EventsController.php#L3636) failure reason

    0 attributes created. 1 attributes could not be saved. This may be due to attributes with similar values already existing.

The same message is displayed when the attributes cannot be created because of validation error(s). Perhaps we could do something with `$this->Event->$objectType->validationErrors` when saving fails?

Here are two possible values of `validationErrors`:

    {"value":["Domain name has an invalid format. Please double check the value or select type \"other\"."]}
    {"value":["A similar attribute already exists for this event."]}

**Comment by iglocska** [comment]
Yeah that was a silly shortcut for batch adding attributes (showing 50 different sets of validation errors would be nasty) - I'll look into reintroducing the validation errors if only one attribute couldn't be saved.
