### ISSUE TITLE
Tags Page: An Internal Error Occurred on Page 2 and Page 6

### ISSUE THREAD

**Issue by faustus25** [MISP/MISP#2956]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.87
| Browser                   | If applicable

### Expected behavior
Load page with tags

### Actual behavior
Page 2 and page 6 don't load with tags, remaining pages load as expected

### Steps to reproduce the behavior
Running on 2048MB, browse to mispurl/tags/index/page:2 and page:6

### Logs, screenshots, configuration dump, ...
#4 {main}
2018-02-20 15:22:56 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 277]
2018-02-20 15:22:56 Error: [InternalErrorException] Internal Server Error
Request URL: /tags/index/page:2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 277)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 277, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by adulau** [comment]
Could you test with recent version of MISP? And let us know if you have still the issue. Thank you.
