### ISSUE TITLE
FreeText importer

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#296]
Also allow to change the type in case the identification is not perfect

**Comment by Rafiot** [comment]
fixed, right?

**Comment by iglocska** [comment]
Yup.

**Comment by Rafiot** [comment]
\o/

**Comment by iglocska** [comment]
Sorry for not closing them myself last night, replied from the plane and the connection speed was too bad to actually load the github page, but yay for "mile-high-club" of ticket handling :)))

**Comment by Rafiot** [comment]
heh, no problem :)
