### ISSUE TITLE
MISP.correlations table no foriegn key constraint with attributes table

### ISSUE THREAD

**Issue by FurqanKhan1** [MISP/MISP#2963]
@iglocska 
@adulau 

Hi all ,

Just skimming through the size of my dB ,i realised that the size of the correlations table has hit around 40 million  ,whereas my attributes table has a size of around 2 million.

As i understand it ,i think there is no foreign key relation between the tables ,as of which even if some attributes are removed form attributes table ,a copy of them would always remain in the correlations table ,leading to unnecessary consumption of more space.

I just want to know ,what impact would it have if we have a cascade delete relationship between the tables,such that only correlations of currently active attributes remain in the table.

Can u kindly tell me if i define my own constraint on the local instance  ,will it break anything.

I don't want correlations table to take up space unless those attributes are actually present in db.

Appreciate your help

Regards
Furqan

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
They are being cascaded though. The problem with doing it on a database level is that we soft delete attributes, which also trigger a deletion of the correlations - if this doesn't work for you then we're facing a weird bug, would love to see how to reproduce it.

**Comment by FurqanKhan1** [comment]
Thanks for the prompt reply.
Let me try it through the API and get back to you ,i think it should work that way.

Just to seek clarification ,can u kindly help me with the following questions :

1) What happens when the attributes come from the feed source with delta merge as enabled (free text ,csv ) ,if the new set of attributes are different from the existing ones ,will it delete the correlations.
2) Is there a specific reason as to why there is a soft delete in place rather then doing a complete delete.


Thanks and appreciate your help

**Comment by iglocska** [comment]
1. yes, any edit or delete should automatically purge existing correlations.
  - in case of a hard delete: https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L651
  - for edits and soft deletes: https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L572
2. Because a hard delete would prevent the syncing of revocations. Basically, if you soft-delete an attribute on MISP A, MISP B needs to know about the revoked attribut. MISP A will soft-delete the attribute and whenever the event gets synced to MISP B, the attribute that was soft-deleted there will get an edit with the delete flag set.

**Comment by FurqanKhan1** [comment]
Well ,thanks a lot for the explanation ,i did not think in that direction for point 2 .
Really appreciate your help always.
:+1:

**Comment by iglocska** [comment]
No worries at all! If you find any place where the correlations are not purged correctly let me know - that's definitely a bug then. You're the second person with a rapidly growing correlations table lately, so there might be a bug there!

**Comment by FurqanKhan1** [comment]
I would test it out and would certainly get back to u over it.
