### ISSUE TITLE
Not Found HTTP Error 404. The requested resource is not found.

### ISSUE THREAD

**Issue by spexboy** [MISP/MISP#2965]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Actual behavior
i am running MISP in my virtualBox after server starts i can able to login but after i cannot view any other service.
If i click is showing **Not Found HTTP Error 404. The requested resource is not found.** on 127.0.0.1/

Please help me if i am missing in configuration.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/13061021/36654614-e2db4654-1ae3-11e8-92fa-fa9483720ccb.png)

**Comment by SHSauler** [comment]
Are you using the training VM from [here](https://www.circl.lu/misp-images/latest/)? Probably not, since the VM has no GUI and you access 127.0.0.1? Check logs in `/var/www/MISP/app/tmp/logs`.

**Comment by spexboy** [comment]
Yes, im using MISP_v2.4.88@501b933a56ac7c11fef3d7ea2b4e9f140f69f305.ova .

log details shown below,
![image](https://user-images.githubusercontent.com/13061021/36664650-53dc4002-1b0b-11e8-95de-79bea354a600.png)

**Comment by iglocska** [comment]
are you forwarding port 80 of your guest?

127.0.0.1/ will be basically port 80 of your host. By being able to log in, you mean via your browser into MISP, or via the command line / virtualbox console into the server itself?

**Comment by spexboy** [comment]
I didnt configured Port Forwarding, 

i configured in Bridged Adapter mode. MISP from browser!!!

Screenshot shown below,
 
![image](https://user-images.githubusercontent.com/13061021/36666155-ca7cfb62-1b0f-11e8-8185-48dd7b847674.png)

**Comment by iglocska** [comment]
Then make sure you update the baseurl in MISP. Via the console run the following command:

```
/var/www/MISP/app/Console/cake Baseurl http://127.0.0.1
```

Let us know if that works.

**Comment by spexboy** [comment]
sorry @iglocska 

Still im getting same error,

![image](https://user-images.githubusercontent.com/13061021/36667541-3afc78dc-1b14-11e8-85dc-52aacdc2577b.png)

**Comment by SHSauler** [comment]
What works for me: Host-Only adapter network, automatic DHCP via VirtualBox. Then MISP is at 192.168.56.101 per default. Second NIC can be configured for external network access (e.g. NAT).

**Comment by spexboy** [comment]
@SHSauler 
Can you please share the screenshot of your network setting for my better understanding especially in Second Adapter (NAT Configuration).

Thank you in advance.

**Comment by SHSauler** [comment]
Hope this helps:

![snag_eb18a1](https://user-images.githubusercontent.com/8420509/36671007-73f96416-1afa-11e8-8d96-d2b18ef719e6.png)
![snag_eb7eed](https://user-images.githubusercontent.com/8420509/36671030-83512f02-1afa-11e8-8893-621d20f00936.png)
![snag_eba810](https://user-images.githubusercontent.com/8420509/36671038-8a1fe1b6-1afa-11e8-9ea7-1e2c43fa2556.png)

**Comment by spexboy** [comment]
My VirtualBox NAT asked for,

Host IP:                 <192.168.56.1>
Host Port:                80
Guest IP:                  
Guest Port:

**Comment by spexboy** [comment]
Sorry Guys,

If i configure with your given sitting management IP itself not connecting.

On Host IP : 192.168.56.1
Host port : 80

Guest IP : 
Guest Port : 
<i left blank>

Is that correct ?

**Comment by SHSauler** [comment]
Have you setup the Host Network in File > Host Network Manager as per my third screenshot?

Here again, with DHCP for it:
![snag_12a2438](https://user-images.githubusercontent.com/8420509/36673744-13316354-1b04-11e8-9b27-f607e2669231.png)
![snag_129e5c7](https://user-images.githubusercontent.com/8420509/36673726-0918da96-1b04-11e8-903b-4bbdaaf24b45.png)

**Comment by spexboy** [comment]
Hello Everyone.

Sorry for the delay!

Still i am facing same issue.

Can you please confirm whether i need to configure Port Forwarding ?
May be this issue is occurring in Apache2 ?

Regards,
Sathish.

**Comment by adulau** [comment]
Are you really using the latest version of the VM? If you do the port forwarding, don't forget to unset the base_url like mentioned by @iglocska.

~~~~
/var/www/MISP/app/Console/cake Baseurl http://127.0.0.1:YOURPORTFORWARDED
~~~~

**Comment by spexboy** [comment]
Hello @adulau 

Thanks for quick response.

I am using VM Box Version 5.2.6.

I run the command still i unable to see the service running. I guess i am making mistake in Port Forwarding.

Can you please help me on this.


Thanks.
Sathish

**Comment by adulau** [comment]
It's really easy. When you are on the network configuration of the VM, you have a specific advanced configuration called port forwarding:

![port-forwarding](https://user-images.githubusercontent.com/3309/37286121-5bf425f6-2601-11e8-8711-4b71a98fe9f6.png)
and then you can set a rule like this (where 8889 is your local port and 80 the port of the VM):

![forwarding2](https://user-images.githubusercontent.com/3309/37286120-5bd39778-2601-11e8-95b3-035eb30816aa.png)
