### ISSUE TITLE
[API] GET /events/addTag gives wrong error message

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#2973]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.88
| Browser                   | If applicable

### Expected behavior

A more accurate error message, as it is not an right issue but the method is not implemented 

### Steps to reproduce the behavior

curl --header "Authorization: your API KEY" --header "Accept: application/json" --header "Content-Type: application/json" -X GET https://mispURL/events/addTag
Result:
{"saved":false,"errors":"You don't have permission to do that."}

**Comment by iglocska** [comment]
Should be fixed now. Thanks!
