### ISSUE TITLE
bug in freetext with xml format

### ISSUE THREAD

**Issue by sebdraven** [MISP/MISP#2978]
Hi, 

when i put xml data in free text, no data was imported, and if replace < and >,all data are imported correctly. 

Following the data which i used to test it
`
<mcconf>
<ver>1000133</ver>
<gtag>tt0002</gtag>
<servs>
    <srv>212.14.51.43:449</srv>
    <srv>212.14.51.56:449</srv>
    <srv>206.255.220.53:449</srv>
    <srv>185.224.215.224:443</srv>
    <srv>83.220.170.165:443</srv>
    <srv>195.133.147.153:443</srv>
    <srv>194.87.92.162:443</srv>
    <srv>80.87.193.138:443</srv>
    <srv>194.87.238.70:443</srv>
    <srv>80.87.193.69:443</srv>
    <srv>194.87.239.7:443</srv>
    <srv>83.220.172.100:443</srv>
    <srv>83.220.172.148:443</srv>
    <srv>217.107.219.78:443</srv>
    <srv>195.161.41.115:443</srv>
    <srv>83.220.172.118:443</srv>
    <srv>83.220.173.116:443</srv>
    <srv>82.202.236.229:443</srv>
    <srv>92.53.67.77:443</srv>
    <srv>83.220.172.248:443</srv>
</servs>
<autorun>
<module name="systeminfo" ctl="GetSystemInfo"/>
<module name="injectDll"/>
</autorun>
</mcconf>`

Thanks !

**Comment by iglocska** [comment]
Added < and > as delimiters for the freetext parser, can't think of a valid reason not to have it for now - might have to revert if something pops up, but doubt it.

Thanks a lot!

**Comment by sebdraven** [comment]
Nice !
