### ISSUE TITLE
URLs navigate to localhost instead of remote IP

### ISSUE THREAD

**Issue by leagueherald** [MISP/MISP#2983]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 17.04 (?)
| OS version (client)       | Windows 10
| MISP version / git hash   | MISP_v2.4.88@2a44d2303b26ca919e08ad9a70fc2962e50c2b73
| Browser                   | Chrome

### Expected behavior
All URLs properly navigate accounting for remote machine rather than using localhost.

### Actual behavior
When navigating to the MISP instance via IP address (ex: 192.168.1.2), the GUI prompts login. After entering creds and redirecting to main GUI, all links function as 127.0.0.1 [localhost] rather than accounting for remote URL 192.168.1.2. 

### Additional Information
I am using the OVA image on VMWare Workstation 12 downloaded via the MISP repo. I have the connection bridged so I can access it on my local network. NAT does no justice as well, as the machine does not navigate to the VM adapter's localhost. Sorry for the trouble, I couldn't find a solution anywhere... Thank you in advance

**Comment by iglocska** [comment]
Make sure you set the baseurl up correctly. 

```
/var/www/MISP/app/Console/cake Baseurl http://192.168.1.2
```

**Comment by leagueherald** [comment]
Oh wow, I would of never figured that out, and I must of missed it in the documentation. Thanks!

**Comment by iglocska** [comment]
No worries, the issue is that the VMs are hardcoded for an IP address, normally a fresh installation uses relative pathing (baseurl = ""). Let us know if you run into any other oddities!
