### ISSUE TITLE
[Bug][Kinda important] Can't add new tags

### ISSUE THREAD

**Issue by Res260** [MISP/MISP#2989]
So we just upgraded to the latest version of MISP and we can't create tags anymore. I'm looking into the problem atm.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| PHP version               | 7.0
| MISP version / git hash   | 2.4.88, https://github.com/MISP/MISP/commit/f44628c31f19de8080c07f3daeb9a34265be5761
| Browser                   | Chrome/FF/IE

### Expected behavior

The tag is saved.

### Actual behavior

![image](https://user-images.githubusercontent.com/14599855/36864330-5bd00eaa-1d5a-11e8-8708-e2dfbd951e1f.png)

### Steps to reproduce the behavior

1. Go to add tag
2. Populate name, color
3. Submit

EDIT: Tested on our production instance and on my local instance.

**Comment by Res260** [comment]
So when removing this rule, it works:

![image](https://user-images.githubusercontent.com/14599855/36865426-7fcf1c12-1d5d-11e8-9389-3b0b4bc7d4fd.png)

**Comment by Res260** [comment]
@iglocska You added this rule 2 days ago in this commit, did it work for you? https://github.com/MISP/MISP/commit/b2f0787d15bf6af9976d2d9355486c31b9fef483

**Comment by Res260** [comment]
Found a fix, opening a pull request

**Comment by adulau** [comment]
Strange, it worked for me on the HEAD.

**Comment by Res260** [comment]
This would be my change:
![image](https://user-images.githubusercontent.com/14599855/36865986-10c3e76a-1d5f-11e8-9dfc-828eff6d292a.png)
This is strange that it works for you. Right now, with `notBlank`, I get the expected behaviour...

**Comment by Res260** [comment]
Ok I read a bit on `required`, it seems it only applies to other rules as seen here:

https://book.cakephp.org/2.0/en/models/data-validation.html#required

So putting only `'required' => true` should not work, it needs to come with another rule, such as `notBlank`.

**Comment by iglocska** [comment]
Indeed, good catch! Surprised that this went under the radar.

**Comment by adulau** [comment]
Good catch! Still don't know why it wasn't reproducible on recent versions. Thank you.

**Comment by iglocska** [comment]
it's very new, introduced 1-2 days ago afaik

**Comment by Res260** [comment]
Np, so if we run the update again on our production instance, it should fix the issue?

**Comment by iglocska** [comment]
yeah, git pull and it should work

**Comment by Res260** [comment]
Alright thanks for the fast response. And well we went from MISP 2.4.82 to MISP 2.4.88, and now I can add tags (I couldnt before, permission-wise), is that a normal behavior with the new version?

**Comment by iglocska** [comment]
what does your role say?

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/36870358-d453134c-1d6c-11e8-8faf-579daa11b490.png)

**Comment by iglocska** [comment]
Yes, you should be able to add tags!
