### ISSUE TITLE
Unable to Export Events

### ISSUE THREAD

**Issue by souti2006** [MISP/MISP#2998]
Hello,

I am unable to export events using the features listed under Automation section. In fact, other than Home -> Export -> Generate -> Download, rest all are throwing errors (including last.py).

For instance, if I browse hxxps://misp/events/csv/download/ it says "An Internal Error Has Occurred. Error: An Internal Error Has Occurred."

Screenshot:
![image](https://user-images.githubusercontent.com/27813676/36931075-c6f69de0-1ed4-11e8-8bb7-90b76a1314bf.png)

Now, I have observed a behaviour; if the exportable feed size is <11.5MB, then the desired export is happening without any hiccups.

Please note, I have configured MISP instances several times to just to make sure if everything is at per with the installation [instructions](https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.ubuntu1604.txt). 

I am currently using VMware 14.1.1 and Ubuntu 16.04.4 LTS (x64) to host my MISP platform v2.4.88 (e44abe301bb8137b9b772132b4d343d1a6ac41b0).

I am planning a big project based on MISP platform and if I am unable to perform this basic task (exporting events/IOCs), then I may never establish the fact that how MISP can enhance visibility and bring agility in threat hunting. So, please help.

If any further details are needed, please let me know.

Thanks.

**Comment by iglocska** [comment]
Could you check the error output in /var/www/MISP/app/tmp/logs/error.log ?
Also, check the diagnostics (administration -> server settings ->
diagnostics) to see whether you've given php enough memory.

**Comment by souti2006** [comment]
Hi iglocska,

You just saved me and my efforts and my project. I'm very new to PHP, Apache and didn't have a clue that memory exhaustion of PHP can lead to all these issues. Wasn't aware that allocating gigs of memory only to the MISP instance is not enough.

As advised, I jumped into Diagnostics and found that the PHP memory and few other associated values were set to way lower than its recommended values; so, I quickly changed the limits and voila, the export works like never before. In fact, it boosts the overall performance of the instance. So basic, yet so impactful.

Thank you for your quick response with an effective solution. Much appreciated. If you have any further suggestions to run the MISP instance sound and healthy, please share.
