### ISSUE TITLE
Unable to Configure Scheduled Tasks

### ISSUE THREAD

**Issue by souti2006** [MISP/MISP#2999]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu 16.04.4
| OS version (client)       | NA
| PHP version               | 7.0.25
| MISP version / git hash   | v2.4.88 (e44abe301bb8137b9b772132b4d343d1a6ac41b0)
| Browser                   | NA

### Concern
I have configured the Scheduled Tasks in the following manner, however, they nither got executed nor the status message changed:
![image](https://user-images.githubusercontent.com/27813676/36942937-a002db3c-1fa5-11e8-8afc-887fc0d30cd2.png)

All the 'Workers' are up and running and necessary feeds are enabled, If I run it in API mode `/fetchFromFeed/<feedID>` the same stays as inactive. Not sure why the job scheduling through the web interface isn't functioning and respective API commands are not executing.

It will be great if you can let me know if I am missing something.

Further, if you can give me a brief understanding on fetching and caching of feeds, it will be very much helpful.

Thank you.

**Comment by souti2006** [comment]
Just found... double click on the values will do the job. Closing this issue.

**Comment by souti2006** [comment]
Please note, speed is the essence and automation is the key. Hence, any inputs in this regard will be highly appreciated.

**Comment by iglocska** [comment]
Could you show us the list of your running workers form the administration -> server settings -> worker tab?

Keep in mind, the API call that you described does NOT affect the scheduler. You can initiate a pull yourself or via the scheduler, pulling it yourself. If it doesn't do that, could you send me your error logs?

**Comment by AJohnDoe** [comment]
You may want to update your MISP instance to grab 29d502ef7d87e85189f3d01152e6624b953f9feb. I was debugging the same issue as you and so far I think jobs run even though it says "Not scheduled yet"

**Comment by souti2006** [comment]
Hello @iglocska and @AJohnDoe,

Many thanks for your inputs.

Please be informed that all the workers are active and working flawlessly. However, after following the suggestion made by @AJohnDoe I can now able to see the schedule confirmarion for `fetch_feeds`. Please refer the screenshot below:
![image](https://user-images.githubusercontent.com/27813676/37145696-8ec6aaa2-22e7-11e8-8433-46a1274462f3.png)

But still this has a small catch. The status of the second task, `cache_feeds` is still unchanged.

Now, coming back to @iglocska, I am aware that API requests and schedulers aren't related, however, the below command seems to be ineffective in my case:
`curl -H "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -k "https://mymisp/feeds/fetchFromAllFeeds"` or `curl -H "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -k "https://mymisp/feeds/cacheFeeds/all"`

Kindly note, if I run `https://mymisp/feeds/fetchFromAllFeeds` or `https://mymisp/feeds/cacheFeeds/all` in the browser under the active login, the same gets successfully executed.
![image](https://user-images.githubusercontent.com/27813676/37146660-66658940-22ea-11e8-9878-2195798690f0.png)

Please let me know if I am missing something here.

Further, in regards to sharing the error logs with you, could you please confirm from the below screenshot, contents of which file should I share with you:
![image](https://user-images.githubusercontent.com/27813676/37146404-9bc9ea5a-22e9-11e8-94ce-b5b7f1e08238.png)

Thanks.

**Comment by iglocska** [comment]
Everything starting with resque- would be great.

**Comment by souti2006** [comment]
Sure. Please find them here...

[resque-2018-03-08.log](https://github.com/MISP/MISP/files/1795817/resque-2018-03-08.log)
[resque-2018-03-09.log](https://github.com/MISP/MISP/files/1795818/resque-2018-03-09.log)
[resque-scheduler-2018-03-08.log](https://github.com/MISP/MISP/files/1795819/resque-scheduler-2018-03-08.log)
[resque-scheduler-2018-03-09.log](https://github.com/MISP/MISP/files/1795820/resque-scheduler-2018-03-09.log)
[resque-worker-error.log](https://drive.google.com/file/d/1g7pCirFVRv3VpXYSCRLTk30mS6pTSoSF/view?usp=sharing)

**Comment by souti2006** [comment]
Hello @iglocska and @AJohnDoe,

This is to inform you that both the scheduled tasks (i.e. `fetch_feeds`, `cache_feeds`) got executed and based on the given configuration the next run is auto-calculated. Please refer the below screenshot:
![image](https://user-images.githubusercontent.com/27813676/37193042-5c4a1d96-238e-11e8-96a4-5f8a43303f85.png)

The other issue with API still persists.

@iglocska: Got any chance to explore the logs? Please let me know if you need any additional logs.

Thanks.

**Comment by chrisinmtown** [comment]
Please forgive a naive question, since this issue has been open 2.5 years, does this mean that MISP scheduled tasks still have a problem? Or was the undesired behavior observed by @souti2006 caused by a local configuration problem and this issue should be closed? Thanks.

**Comment by enjeck** [comment]
Schedule tasks are deprecated. CRON Jobs are being used instead, I think. I believe this issue can be closed now. Feel free to reopen if need be.

**Comment by knightian** [comment]
@enjeck seeing this issue remains and the advice is switch to cron jobs, is there any sample crons for things like fetch all feeds? I have only seen example to fetch a single feed and saw a suggestion to iterate it with feed ids but that seems like a poor way to do it if there exists a fetch all way

**Comment by knightian** [comment]
For anyone who encounters this looking to fix, if you are using the new background workers they do not work with Scheduled Tasks and you must use a cron job instead.

For the cron job you create an API key for your user to access the API, and then for an hourly cron job you can do it like this:

```0 * * * * /bin/curl -i -k -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Paste_Your_API_Key_Here" "https://mispurlhere.com/feeds/fetchFromAllFeeds"```
