### ISSUE TITLE
Empty events are created when pulling empty feeds

### ISSUE THREAD

**Issue by crossbowerbt** [MISP/MISP#3008]
Empty events are created when pulling empty feeds

**How to reproduce:**

1. An empty feed must be fetched (example:  longtail.it.marist.edu, ID: 44)
2. Fixed event ID is NOT used

**Fix**

Just check if the $data array is empty before creating a new event.

In "app/Model/Feed.php", in method "saveFreetextFeedData()", add a check:

```
		if (!$event) {
			if (empty($data)) { // check: do not create empty event (Emanuele Acri 07-Mar-2018)
				return true;
			}
			$this->Event->create();
```

In this way the databse is not filled with useless events.

**Comment by iglocska** [comment]
Interesting. Nice catch, thanks.
