### ISSUE TITLE
Can´t change admin password

### ISSUE THREAD

**Issue by supertxango** [MISP/MISP#3010]
Hi all!

Recently I have installed MISP in Ubuntu server (17.10.1) following all the steps in the INSTALL file. All works fine, but when I access to my new MISP instance using admin@admin.test and admin I´m redirected to users/change_pwd and also I have the following message: Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)

I´ll try to change the password (With different lengths and complexities) but always I get the message:

The password could not be updated. Make sure you meet the minimum password length / complexity requirements.

I have read all the messages related with this issues but I can´t solve my problem... Probably it´s related with the salt but I have deleted it some times 

Also I have tried reset the password using:

sudo /var/www/MISP/app/Console/cake Password admin@admin.test password

And I get:

Welcome to CakePHP v2.9.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Could not update account for User.id = 1
{"password":["Password length requirement not met."]}
Array
(
    [password] => Array
        (
            [0] => Password length requirement not met.
            [1] => Password length requirement not met.
        )

)
Updated 

But nothing happens...

I don´t know how to follow and any help is welcome. If you need more information, please tell me.

Thank you very much!

**Comment by iglocska** [comment]
With the default complexity anyting > 16 characters should work, or alternatively 12 with 3/4. It shounds like your password was too short, try this just to see if it works:

```
sudo /var/www/MISP/app/Console/cake Password admin@admin.test Password1234
```

**Comment by supertxango** [comment]
Yes, it works fine
sudo /var/www/MISP/app/Console/cake Password admin@admin.test Password1234

Welcome to CakePHP v2.9.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Updated 

I have selected a 16 characters password an also works really good. I have tried from the web interface and now it´s ok. 

I´m going to solve the other message:

MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)

Thank you very much for your help and four your fast response!

**Comment by jmgnc** [comment]
Please state what the requirements are.  Just saying that a password doesn't meet the minimum requirements gives the user no actionable information on how to make it happen.  I just ran into this myself.

**Comment by iglocska** [comment]
We cold display the regex used for the validation - however, since the password policy is admin defined, this would mean that any "humanly readable" explanation of the policy would potentially be invalid. Perhaps it would make sense to display it if the policy is kept at the default setting.
