### ISSUE TITLE
Unable to access MISP modules on VMware image

### ISSUE THREAD

**Issue by ZaneHintzman** [MISP/MISP#3013]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 17.10
| OS version (client)       | Windows 10
| PHP version               | 7.1.11
| MISP version / git hash   | MISP_v2.4.88@6e1528db1a9e0afb3f889b76c40780402e014243
| Browser                   | Chrome

### Expected behavior

When navigating to MISP modules via URL to live VM image (ex. `192.168.229.128:6666/modules`), should be able to see installed modules.

### Actual behavior

Get message saying "This site can't be reached," even though it is possible to navigate to other parts of MISP application.

### Steps to reproduce the behavior

1. Install latest VMware image from [https://www.circl.lu/misp-images/latest/](https://www.circl.lu/misp-images/latest/) (latest version may have different MISP version and git hash).
2. Open VM image in VMware Workstation Pro 12.
3. Login to the system with VM credentials (see [http://www.misp-project.org/download/](http://www.misp-project.org/download/).)
4. Find the machine's IP using `ifconfig`.
5. Configure the base URL using `/var/www/MISP/app/Console/cake Baseurl http://<machine's IP>`. May require `sudo`.
6. Navigate to machine's IP on browser to make sure main app working.
7. Navigate to `<machine's IP>:6666/modules`, which should give message "This site can't be reached."

### Additional Information

I am using the latest VMware image from `https://www.circl.lu/misp-images/latest/` on VMware Workstation Pro 12.

**Comment by AJohnDoe** [comment]
Can you access misp-modules from the actual vmware image itself? misp-modules listens only on localhost by default and by design because MISP makes a local request to misp-modules. Try curl or wget if you don't have a web browser.

**Comment by ZaneHintzman** [comment]
Yes, I am able to curl to the URL on the VM itself. How can I tell if a particular module is working? I'm new to MISP and trying to understand how modules work.

**Comment by AJohnDoe** [comment]
You need to enable the category of plugin that you want to use under Administration > Server Settings & Maintenance > Plugin Settings, then enable the individual plugins that you want to use.

Once you do that, the different categories of plugins will be usable from different parts of the UI eg for enrichment modules, you'll see a asterisk beside each attribute, for import modules, you'll see options in the Event view > Populate from...

I found documentation for many parts of MISP a little..lacking so no worries.

**Comment by adulau** [comment]
Maybe a good start is the misp-modules slide deck from the training: https://www.circl.lu/assets/files/misp-training/luxembourgnov2017/4.0-misp-modules.pdf

**Comment by ZaneHintzman** [comment]
@AJohnDoe Thanks for the details. I think I now see how enrichment and import modules work. How do export modules modify the UI? Just a comment: I think the VM could be improved by providing the defaults for each module in order for them to work. I tried to use asn_history, but I don't know what database to use in the config.

**Comment by SteveClement** [comment]
Dear @ZaneHintzman 

We will enable some of the modules by default very soon.
In the meantime the most noticeable difference for you will be when you view and event and select "Download as"
If all went well you will see your enabled Export Module in that list.
