### ISSUE TITLE
Main page doesn't load properly on new install

### ISSUE THREAD

**Issue by ZaneHintzman** [MISP/MISP#3016]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 15.10
| PHP version               | 5.6.11
| MISP version / git hash   | MISP_v2.4.88@22ded998d80250006e0a339053d99ec20efaec56
| Browser                   | Firefox

### Expected behavior

After completing installation steps in INSTALL.ubuntu1404.txt, should be able to open browser and see main login page on localhost.

### Actual behavior

Navigating to localhost brings up a MISP page that says "An Internal Error Has Occurred."

### Steps to reproduce the behavior

1. Install requirements specified in INSTALL.ubuntu1404.txt.
2. Open web browser and navigate to localhost page.

### Logs, screenshots, configuration dump, ...

`debug.log` Logs:

2018-03-09 14:36:03 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Layouts/default.ctp, line 106]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 106
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

**Comment by iglocska** [comment]
Could you also paste the output of error. Log?

**Comment by ZaneHintzman** [comment]
I looked at error.log, and realized I hadn't changed the MySQL username in the database.php config file. Once I set that value, I tried to login using the default admin account, but then I got "The page isn't redirecting property". The URL had "localhost/users/change_pw", but no page was displayed. By the way, here's what was in error.log before I fixed the MySQL error:

2018-03-09 14:36:03 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[28000] [1045] Access denied for user \'db login\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

**Comment by iglocska** [comment]
The localhost error seems to be a badly set baseurl, simply run:

`/var/www/MISP/app/Console/cake Baseurl [your_base_url]`

for example if I had my MISP accessible via localhost:27015, I'd run:

`/var/www/MISP/app/Console/cake Baseurl http://localhost:27015`

Let us know if it hasn't solved the issue!

**Comment by ZaneHintzman** [comment]
It worked for me when I set Baseurl to `http://localhost`. Thanks.

**Comment by stansecurecom** [comment]
> The localhost error seems to be a badly set baseurl, simply run:
> 
> `/var/www/MISP/app/Console/cake Baseurl [your_base_url]`
> 
> for example if I had my MISP accessible via localhost:27015, I'd run:
> 
> `/var/www/MISP/app/Console/cake Baseurl http://localhost:27015`
> 
> Let us know if it hasn't solved the issue!

I had a similar issue but the error message is 
`Error: [MissingConnectionException] Database c
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
`

What can it be?
