### ISSUE TITLE
Error type with free text import

### ISSUE THREAD

**Issue by sebdraven** [MISP/MISP#3018]
Hi !

the free text import transform a path of file C:\FRSRAMSOMWARE\READ_ME_HELP_ME.png in a file name 

C:FRSRAMSOMWAREREAD_ME_HELP_ME.png

Thanks for your feedback 

Sebastien

**Comment by BenjaminJoly** [comment]
Hi there !

This issue as already been reported in issue #2926 and should be corrected. Is your MISP instance is up to date ? 

If it persists even with an up-to-date MISP, thanks to fill the template below, to let us know a little more about your configuration and your environment so we could see what's wrong !

```
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior


### Actual behavior


### Steps to reproduce the behavior


### Logs, screenshots, configuration dump, ...

```

**Comment by sebdraven** [comment]
Hi,

my version of misp is 2.4.88 and I've the problem yet.

I can reproduce that on the all path of file with my instance

**Comment by BenjaminJoly** [comment]
Interesting, I've just tried on my VM which I just put up to date (2.4.88 `eadae41` ), but I do not have this problem anymore. 
Could you give us some information about your environment by filling the bug template I've just sent in my last message, so we can help you more ? Thanks in advance.

**Comment by sebdraven** [comment]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug.
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               |  PHP 7.0.25-0ubuntu0.16.04.1
| MISP version / git hash   | 2.4.88

![capture du 2018-03-13 15-48-04](https://user-images.githubusercontent.com/1478484/37349234-3d54c256-26d6-11e8-831b-b41198b06511.png)
![capture du 2018-03-13 15-47-28](https://user-images.githubusercontent.com/1478484/37349235-3d7b6992-26d6-11e8-819c-8294f437a466.png)

**Comment by adulau** [comment]
I just tested 75366dce10254d684768fedc9b5cbc19579766d1 but it works for me. What is the commit-id?

**Comment by sebdraven** [comment]
the commit id is e44abe301bb8137b9b772132b4d343d1a6ac41b0

**Comment by adulau** [comment]
So `git pull origin 2.4` and test again. Just want to be sure that you are on a latest version ;-)

**Comment by sebdraven** [comment]
Hummm Ok thanks Alex ! My bad :( and I retry it ;)

**Comment by adulau** [comment]
Let us know. Just to be sure. Thank you.

**Comment by sebdraven** [comment]
You're alright Alex ! It's fixed it by the git pull ;) Thanks a lot !

**Comment by adulau** [comment]
Cool Thanks for the feedback.
