### ISSUE TITLE
User cannot login

### ISSUE THREAD

**Issue by makakin** [MISP/MISP#3019]
Hi all, 

I am new to MISP, we built the MISP and tried to use for few weeks. Today a user reported that he cannot log into the system with below error message.

**User report suddenly cannot log in and shows the message below:**
"You have tripped the cross-site request forgery protection of MISP
CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.
Alternatively, click here to continue to the start page."

**In the error.log**
Error: [BadRequestException] csrf
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(624): AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(338): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(243): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**After pressing the URL "here" and log in again:**
You have reached the maximum number of login attempts. Please wait 300 seconds and try again.
Error: The requested address '/users/login' was not found on this server.

**In the error.log**
Error: [ForbiddenException] You have reached the maximum number of login attempts. Please wait 300 seconds and try again.
Request URL: /users/login
Stack Trace:
#0 [internal function]: UsersController->login()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

Questions | Answers
-- | --
Type of issue | Support
OS version (server) | Ubuntu
OS version (client) | 16.04.4
PHP version | 7.0.25
MISP version | MISP_v2.4.88
Browser | Chrome 64.0.3282.186 (Official Build) (64-bit)

**I had tried below methods to solve the problem**
1. Wait for 300 seconds and try again n times
2. Clean up browser cache
3. Reset the password from the GUI

4. sudo /var/www/MISP/app/Console/cake Password user@domainname.com Password1234
> Welcome to CakePHP v2.9.9 Console
> ---------------------------------------------------------------
> App : app
> Path: /var/www/MISP/app/
> ---------------------------------------------------------------
> Updated 

5. copy other user's password hash and update database directly

However, still no luck. The user still cannot login to the system. Is there any cache mechanism is used?

Thank you very much!!!

**Comment by mahesh557** [comment]
hi, i had same problem, what is the resolution?

**Comment by duzvik** [comment]
check  config.php, I bet it changed.
Rename config.php.bk  to config.php and it works.
