### ISSUE TITLE
Really strange (TM) GUI issue: "Log out" not visible

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#3021]
Using our 2.4.88 instance the "Log out" option disappeared from the GUI a while ago (am not sure as to at which version exactly):
![logout](https://user-images.githubusercontent.com/25325656/37285295-e87b8bf2-25fe-11e8-882a-9a34c9fe06c3.png)

Also, the _countrycode_ enrichment just disappeared from the _Enrichment_ settings although it cleary is installed.

Any ideas as to what's causing this? I see nothing in any log files so I have no idea how to investigate. Could this be related to our instance running on PHP5?

**Comment by iglocska** [comment]
The logout button disappearing is a setting in server settings, what authentication method are you using? Weird thing is that part of the code didn't change in > 1 year afaik...

As for the enrichment - it should work, could you run the introspection as described on the misp-modules github repo's readme.md and see if it shows up there?

PHP 5 should work fine, we still have a server running php 5 so we'd notice too if something broke ;)

**Comment by StefanKelm** [comment]
OMG, I didn't even know that setting existed (and I have no idea why it was set to "true" on our instance). Apologies.

Glad to hear PHP 5 shouldn't be a problem.

Thanks for the introspection hint - will try...
