### ISSUE TITLE
"An internal Error Has Occurred " on web interface.

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#3022]
I always get an error that says "An Internal Error Has Occurred" when i try log into MISP web interface.

I have attached an image sowing the error logs.

![error](https://user-images.githubusercontent.com/30654371/37286155-d4facc72-2609-11e8-89cf-b5c554c555e2.PNG)

**Comment by adulau** [comment]
It seems related to your installation. Have you installed PHP PDO MySQL? if yes, is it enabled in your php.ini?

**Comment by ndhambi** [comment]
I had fully done the isntallation and it was working fine, this problem only started when there was a Electricity failure and the computer running MISP server did not shut down properly.

I have opened the php.ini file but i am not sure where the PHP PDO MYSQL has to be enabled.

**Comment by ndhambi** [comment]
I had fully done the isntallation and it was working fine, this problem only started when there was a Electricity failure and the computer running MISP server did not shut down properly.

I have opened the php.ini file but i am not sure where the PHP PDO MYSQL has to be enabled.

**Comment by redbiker-svg** [comment]
Hey @WakandaKing - did you manage to find a resolution to this error? I've run into the same one and can't login to the Web GUI..
