### ISSUE TITLE
Add some types

### ISSUE THREAD

**Issue by blade3** [MISP/MISP#3023]
I'm looking to add some types to MISP:
Network activity:
* hostname|ip-src
* hostname|ip-dst
* hostname|port

Payload delivery:
* hostname|ip-src
* hostname|ip-dst
* domain|ip-src
* domain|ip-dst
* domain|port

Any idea where I need to look up for this / thinks to consider when adding types?

thanks

**Comment by adulau** [comment]
The best would be to create new object templates:

https://github.com/MISP/misp-objects/ - 
https://www.misp-project.org/objects.html 

Or even use the existing like the Passive DNS object https://www.misp-project.org/objects.html#_passive_dns

**Comment by blade3** [comment]
Whats about the background validation on the specific validation type?

**Comment by adulau** [comment]
Objects template are just combine object using standard MISP attributes types. As an example, if you use ip-src as an attribute within an object, the validation will be exactly the same as MISP does (in this case, a valid IPv4/IPv6 address).
