### ISSUE TITLE
Error when adding regkey|value attribute

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#3025]
When adding an attribute to an event (specifically Artifacts Dropped -> Regkey|Value), if you enter only ONE value, it simply hangs, versus saying that it expects two values in a pipe delimited form. (i.e. enter: cbb6b1fdb155da1809c293f787749119 instead of Some Key|cbb6b1fdb155da1809c293f787749119.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| PHP version               | 7.0
| MISP version / git hash   | 2.4.88

### Expected behavior

Return an error and exit gracefully.

### Actual behavior

Hangs.

**Comment by iglocska** [comment]
Very good point. Should be fixed now, thanks!
