### ISSUE TITLE
Deletion button on references in object

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#3041]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.0
| MISP version / git hash   | 2.4.88, 33f9c99205d616b1316841fb8b521ed619f05e61
| Browser                   | Chrome

### Expected behavior
When clicking the delete icon on an object reference, it should be removed, but nothing happends

### Actual behavior
Nothing

### Steps to reproduce the behavior
I've created to objects a file object and a virustotal object and then created a reference from the file object to the virustotal object. Hereafter tried to delete.

### Logs, screenshots, configuration dump, ...
N/A

**Comment by adulau** [comment]
Confirmed in latest version.
