### ISSUE TITLE
csv' format for the module csv import

### ISSUE THREAD

**Issue by di-iode** [MISP/MISP#3048]
Hello,

I have two questions :

I just install module, and I want to use the module csv import, but what is the format of the csv ?

The description is "Customizable CSV import module." so , i need to customize the module ? How can i do that ?

thank's you for your attention

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | CentOS
| OS version (client)       | Seven
| PHP version               | 5.4
| MISP version / git hash   | 2.4.8.8
| Browser                   | If applicable

**Comment by cvandeplas** [comment]
I'm not familiar with this module, looking at the code and testing a bit I'm not much further. Maybe @chrisr3d  (the author) can tell more or give examples. 


As far as I understand you'll need to specify the header line of the CSV in the MISP server settings: Plugin.Import_csvimport_header |   | Set this required module specific setting.
It's however not clear to me what actually is needed to make it work.

**Comment by di-iode** [comment]
hello, thank you for your response, i'll will test that.

**Comment by chrisr3d** [comment]
Sorry for my late answer, I should check my notifications more often...

As @cvandeplas said, yes the header is needed at the moment, since we cannot be sure it is included in all the csv files people want to import, and I did not spend time on trying to find automatically if there is a header yet.

Let me know if you have any issue

**Comment by di-iode** [comment]
You can find below an example of the csv i have used for importing some information : 

| MD5 | SHA1 | to-ids | comment
|------|-------|-------|-----------|
| DF...EF |    |  1  |  a smart comment |
| F2...E6 | DE4...G6 | 0 | a weird comment | 

SHA1, MD5 and ids options are properly imported from csv, however comments have a strange behaviour during import.
For example, `A smart comment` is imported as a value with the type `comment`.
For your information, i put in the form Header `md5,sha1,to_ids,comment`

**Comment by di-iode** [comment]
Ok after read the code of module, i find the type `attrComment`. So I remplace `comment` by `attrComment`.
