### ISSUE TITLE
REST API for adding attachment into an event in MISP

### ISSUE THREAD

**Issue by hweichou** [MISP/MISP#3056]
Hi, 

I am attempting to add a file attachment onto an event on MISP using curl command. I could not find any information on how to do so. Do anyone knows how to perform the mentioned task using curl command?

Thanks

**Comment by waaeh** [comment]
Hi hweichou,
I'm not from the project but [these examples work great for adding attachments to your own event (or create a new event if no misp event ID is provided)](https://www.circl.lu/doc/misp/automation/#upload-malware-samples-using-the-upload-sample-api). I didn't attempt it in cURL so far, but if I succeeded in VBA it should be easy to do in cURL ;-)

**Comment by jaegeral** [comment]
See: 
https://misp.gitbooks.io/misp-book/content/automation/

"Upload malware samples using the "Upload Sample" API"

```json

{"request":{"files": [{"filename": "test1.txt", "data": "dGVzdA=="}, {"filename": "test2.txt", "data": "dGVzdDI="}], "distribution": 1, "info" : "test", "event_id": 15}}```

**Comment by hweichou** [comment]
Thank you waaeh and deralexxx. Through your assistance, I managed to upload an attachment to MISP.

However, how can I specify the options for IDS and Advanced Extraction when adding attachment through curl command?

The following are the options available via the MISP web interface.

![image](https://user-images.githubusercontent.com/22009651/37756523-c42132c8-2de4-11e8-8253-2120dba3ba95.png)

**Comment by hweichou** [comment]
Oh. Resolved. Thanks for all the assistance!
