### ISSUE TITLE
No Clear Documentation/Process for External Authentication Configuration

### ISSUE THREAD

**Issue by ropetin** [MISP/MISP#3059]
Checking through the MISP book and the various pieces of documentation and issues listed here in Github, I can't find any clear directions on enabling external authentication in MISP.   The various settings documented in the example configuration file provided don't seem to work as expected, the GUI configuration menus don't offer any pointers, and there does not appear to be any useful logs of note to help with troubleshooting.

I'd assume using external authentication (OpenLDAP, Active Directory, whatever) is a pretty standard practice for a tool of this type.  While it might be obvious to developers and/or people who have spent an amount of time working with MISP, securing the tool is likely one of the first steps someone will do when deploying MISP, so any level of knowledge outside of what is documented cannot be assumed.

Ultimately, I believe documentation related to authentication configuration, as well as other significant portions of the tool, should be documented clearly and concisely, in such a way that a 'smart newbie' can follow them and be successful.

**Comment by francesco-ficarola** [comment]
Any news about this issue?

I'm trying to configure MISP using external authentication through a LDAP server, but with no success yet.

This is my Apache configuration:

    <VirtualHost *:443>
            ServerAdmin my@email.com
            ServerName mymisp.mydomain
            DocumentRoot /var/www/MISP/app/webroot
            <Directory /var/www/MISP/app/webroot>
                    Options -Indexes
                    AllowOverride all
                    AuthType Basic
                    AuthBasicProvider ldap
                    AuthName "LDAP Auth"
                    AuthUserFile /dev/null
                    AuthLDAPURL "ldap://mydomain/OU=myou,O=test,C=local?mail"
                    AuthLDAPBindDN "CN=myuser,OU=myou,O=test,C=local"
                    AuthLDAPBindPassword "mypassword"
                    require valid-user
                    RewriteEngine On
                    RewriteCond %{LA-U:REMOTE_USER} (.+)
                    RewriteRule .* - [E=RU:%1]
                    RequestHeader set REMOTE_USER %{RU}e
                    #RequestHeader set X-Remote-User %{REMOTE_USER}s ---> Maybe this is has to be used in Apache 2.4.x ????????
            </Directory>
            SSLEngine On
            SSLCertificateFile /etc/ssl/private/misp.crt
            SSLCertificateKeyFile /etc/ssl/private/misp.key
            #SSLCertificateChainFile /etc/ssl/private/misp-chain.crt
            LogLevel debug
            ErrorLog /var/log/apache2/misp_ssl_error.log
            CustomLog /var/log/apache2/misp_ssl_access.log combined
            ServerSignature Off
    </VirtualHost>

Below, just the CustomAuth Plugin enabled (no specific configuration adopted so far, since I don't know what I need to change):

![image](https://user-images.githubusercontent.com/1279595/53640856-94411980-3c2d-11e9-9c7f-e8974e46ab2e.png)

Eventually, I created a simple user with external authentication checkbox selected.

![image](https://user-images.githubusercontent.com/1279595/53641800-572a5680-3c30-11e9-922b-ed71428cbc3a.png)

**The issue**
When visiting MISP, a basic authentication appears and, after entering my credentials, the LDAP user is granted. However, after the basic authentication succeeded, the MISP login page (`/users/login`) appears, asking for login.

**Comment by francesco-ficarola** [comment]
Ok, after debugging all the authentication code, finally I understood as to configure the External Authentication.

**SYSTEM CONFIGURATION**
Ubuntu 18.04.1 LTS
MISP  v2.4.103
Apache v2.4.29

**APACHE CONFIGURATION**

    ~# vim /etc/apache2/sites-enabled/default-ssl.conf
    
    <VirtualHost *:443>
            ServerAdmin email@yourdomain.com
            ServerName yourserver.yourdomain.com
            DocumentRoot /var/www/MISP/app/webroot
            <Directory /var/www/MISP/app/webroot>
                    Options -Indexes
                    AllowOverride all
            </Directory>
            <Location /users/login>
                    AuthType Basic
                    AuthBasicProvider ldap
                    AuthName "LDAP Authentication"
                    AuthUserFile /dev/null
                    AuthLDAPURL "ldap://url_ldap/OU=your_ou_if_exists,O=your_O_if_exists,C=your_C?username_field"
                    Require valid-user
                    RequestHeader set X-Remote-User %{REMOTE_USER}
            </Location>
            SSLEngine On
            SSLCertificateFile /etc/ssl/private/misp.crt
            SSLCertificateKeyFile /etc/ssl/private/misp.key
            #SSLCertificateChainFile /etc/ssl/private/misp-chain.crt
            LogLevel debug
            ErrorLog /var/log/apache2/misp_ssl_error.log
            CustomLog /var/log/apache2/misp_ssl_access.log combined
            ServerSignature Off
    </VirtualHost>

Please note that `username_field` can be one of the following: `uid`, `mail` (if exists), `samaccountname` (if your authenticator system is an Active Directory), and so on... That depends on which field you want to map the credentials the user must enter.

**CUSTOMAUTH PLUGIN**

    Plugin.CustomAuth_enable                  true
    Plugin.CustomAuth_header                  X_REMOTE_USER
    Plugin.CustomAuth_use_header_namespace    true
    Plugin.CustomAuth_header_namespace        HTTP_
    ...

**USER CONFIGURATION**
![image](https://user-images.githubusercontent.com/1279595/54107153-9ac35400-43d8-11e9-8d80-c5c2f141f152.png)

1) Enable _External Authentication user_ checkbox
2) Copy and paste the `username_field` you have mapped on `HTTP_X_REMOTE_USER` into _External Auth Key_ input field. For instance, as shown above, the _External Auth Key_ can be the email address since my `username_field` mapped by the LDAP url is `mail`.

**SECURITY ENHANCEMENT**
If you leave _External Auth Key_ as clear text, that could be a security issue, since an attacker could send an HTTP request with the victim username into `HTTP_X_REMOTE_USER` to access to his MISP platform.
This could be solved by mapping a hashed value to `HTTP_X_REMOTE_USER`. For instance:

    RequestHeader set X-Remote-User expr=%{md5:%{REMOTE_USER}_saltpassword}

Obviously, you should replicate the same hashed value in the _External Auth Key_ input field. To obtain that value you could use OS utils, for instance:

    ~$ echo -n foobar@yourdomain.com_saltpassword | md5sum | awk '{print $1}'
    a65fb2be657fc3e94922b830a42dfc30

![image](https://user-images.githubusercontent.com/1279595/54111619-99982400-43e4-11e9-922a-b8a700ef78a9.png)

**Comment by pietrogu** [comment]
Hi @francesco-ficarola,

can you please describe all the steps for setting LDAP authentication? 
I'm trying to replicate what you did but with no luck.
I'm stuck on this error:

Unrecognized header format %

**Comment by trolldbois** [comment]
Some documentation in #6189 related to LDAP/Active Directory

**Comment by francesco-ficarola** [comment]
> 
> 
> Hi @francesco-ficarola,
> 
> can you please describe all the steps for setting LDAP authentication?
> I'm trying to replicate what you did but with no luck.
> I'm stuck on this error:
> 
> Unrecognized header format %

Hi @pietrogu,

in order to help you, please describe step-by-step what you did. The configuration is described in my previous post.

Best,
Francesco

**Comment by pietrogu** [comment]
> > Hi @francesco-ficarola,
> > can you please describe all the steps for setting LDAP authentication?
> > I'm trying to replicate what you did but with no luck.
> > I'm stuck on this error:
> > Unrecognized header format %
> 
> Hi @pietrogu,
> 
> in order to help you, please describe step-by-step what you did. The configuration is described in my previous post.
> 
> Best,
> Francesco

I solved the problem, I need to add an "e" to %{REMOTE_USER}

Now i'm facing this issue: after inserting credentials in a popup, i see the login page and I been asked to login again. If i insert the LDAP user and password, it gives me a wrong credentials error.

Did you face this problem and solved it?

Thank you

**Comment by francesco-ficarola** [comment]
> I solved the problem, I need to add an "e" to %{REMOTE_USER}
> 
> Now i'm facing this issue: after inserting credentials in a popup, i see the login page and I been asked to login again. If i insert the LDAP user and password, it gives me a wrong credentials error.
> 
> Did you face this problem and solved it?
> 
> Thank you

The login page should not appear. You have to login by using BASIC AUTH only. Did you properly set the authentication plugin in MISP?

**Comment by pietrogu** [comment]
Below all the steps:

I setted apache in this way:

<VirtualHost *:80>
    ServerAdmin serveradmin@misp.local
    ServerName MYSERVER
    Header always unset "X-Powered-By"
    RewriteEngine On
    RewriteCond %{HTTPS}  !=on
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

    ServerSignature Off
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin serveradmin@misp.local
    ServerName MYSERVER

    DocumentRoot /var/www/MISP/app/webroot
    <Directory /var/www/MISP/app/webroot>
        Options -Indexes
        AllowOverride all
    </Directory>
    <Location /users/login>
        AuthType Basic
        AuthBasicProvider ldap
        AuthName "LDAP authentication"
        AuthLDAPBindDN BIND_DN
        AuthLDAPBindPassword BIND_DN_PWD
        AuthLDAPURL "ldaps://MYLDAP/MYDN?samaccountname?sub?(objectclass=user)"
        AuthUserFile /dev/null
        Require valid-user
        RequestHeader set X-Remote-User %{REMOTE_USER}e
    </Location>
    SSLEngine On
    SSLCertificateFile /etc/ssl/private/misp.local.crt
    SSLCertificateKeyFile /etc/ssl/private/misp.local.key
    LogLevel debug
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
</VirtualHost>

Then i setted config.php in this way:

 'ApacheSecureAuth' =>
  array (
    'apacheEnv' => 'REMOTE_USER',
    'ldapServer' => 'ldaps://MYLDAP',
    'ldapProtocol' => 3,
    'ldapNetworkTimeout' => -1,
    'ldapReaderUser' => 'BASEDN',
    'ldapReaderPassword' => 'BASEDN_PWD',
    'ldapDN' => 'MYDN',
    'ldapSearchFilter' => '(objectClass=user)',
    'ldapSearchAttribut' => 'sAMAccountName',
    'ldapFilter' =>
    array (
      0 => 'mail',
    ),
    'ldapDefaultRoleId' => 6,
    'ldapDefaultOrg' => '1',
    'ldapAllowReferrals' => false,
    'ldapEmailField' =>
    array (
      0 => 'mail',
    ),
  ),

Then i setted CustomAuth in MISP in this way

![InkedUntitled picture_LI](https://user-images.githubusercontent.com/52070642/92599082-06c29900-f2aa-11ea-973f-4dd7d99a6c41.jpg)

**Comment by pietrogu** [comment]
> > I solved the problem, I need to add an "e" to %{REMOTE_USER}
> > Now i'm facing this issue: after inserting credentials in a popup, i see the login page and I been asked to login again. If i insert the LDAP user and password, it gives me a wrong credentials error.
> > Did you face this problem and solved it?
> > Thank you
> 
> The login page should not appear. You have to login by using BASIC AUTH only. Did you properly set the authentication plugin in MISP?

Below all the steps:

I setted apache in this way:

<VirtualHost *:80>
    ServerAdmin serveradmin@misp.local
    ServerName MYSERVER
    Header always unset "X-Powered-By"
    RewriteEngine On
    RewriteCond %{HTTPS}  !=on
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

    ServerSignature Off
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin serveradmin@misp.local
    ServerName MYSERVER

    DocumentRoot /var/www/MISP/app/webroot
    <Directory /var/www/MISP/app/webroot>
        Options -Indexes
        AllowOverride all
    </Directory>
    <Location /users/login>
        AuthType Basic
        AuthBasicProvider ldap
        AuthName "LDAP authentication"
        AuthLDAPBindDN BIND_DN
        AuthLDAPBindPassword BIND_DN_PWD
        AuthLDAPURL "ldaps://MYLDAP/MYDN?samaccountname?sub?(objectclass=user)"
        AuthUserFile /dev/null
        Require valid-user
        RequestHeader set X-Remote-User %{REMOTE_USER}e
    </Location>
    SSLEngine On
    SSLCertificateFile /etc/ssl/private/misp.local.crt
    SSLCertificateKeyFile /etc/ssl/private/misp.local.key
    LogLevel debug
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined
    ServerSignature Off
</VirtualHost>

Then i setted config.php in this way:

 'ApacheSecureAuth' =>
  array (
    'apacheEnv' => 'REMOTE_USER',
    'ldapServer' => 'ldaps://MYLDAP',
    'ldapProtocol' => 3,
    'ldapNetworkTimeout' => -1,
    'ldapReaderUser' => 'BASEDN',
    'ldapReaderPassword' => 'BASEDN_PWD',
    'ldapDN' => 'MYDN',
    'ldapSearchFilter' => '(objectClass=user)',
    'ldapSearchAttribut' => 'sAMAccountName',
    'ldapFilter' =>
    array (
      0 => 'mail',
    ),
    'ldapDefaultRoleId' => 6,
    'ldapDefaultOrg' => '1',
    'ldapAllowReferrals' => false,
    'ldapEmailField' =>
    array (
      0 => 'mail',
    ),
  ),

Then i setted CustomAuth in MISP in this way

![InkedUntitled picture_LI](https://user-images.githubusercontent.com/52070642/92599082-06c29900-f2aa-11ea-973f-4dd7d99a6c41.jpg)

**Comment by pietrogu** [comment]
Problem solved! sorry for the spam, i had to rename X-Remote-User in X_REMOTE_USER

**Comment by bpavesi** [comment]
Hello,
it's also possibile to integrate google Authenticator? If yes, how? It's necessary to develop an authentication plugin or use a reverse proxy?
Somewhere it's avaiable a guide regarding this topic?

**Comment by serafyn** [comment]
Hola a todos, se que este es un post antiguo pero después de logra la autenticación externa a través de AD y usando LDAP:
tengo un problema que no puedo ni establecer un tiempo de máximo para una sesión inactiva ni tampoco puedo cerrar la sesión a mi voluntad, es decir el botón de logout no funciona. 
No se si alguien que ya paso por esto tiene una manera de hacerlo.
Gracias.

**Comment by serafyn** [comment]
Hi all, I know this is an old post but after achieving external authentication through AD and using LDAP: I have a problem that I can neither set a maximum time for an inactive session nor can I close the session at my will, that is the logout button does not work. I do not know if someone who already went through this has a way to do it. thanks.

**Comment by adulau** [comment]
We will update the default config to clearly state it's with the headers in upper cases.

**Comment by allamiro** [comment]
> Problem solved! sorry for the spam, i had to rename X-Remote-User in X_REMOTE_USER

where did you change this ?
