### ISSUE TITLE
Adding tags without publishing again?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3061]
In one of the organizations where MISP is used, we would like to start tagging specific events to process them in a different way (automation). Ex: to perform retro-hunting on some IOCs.
When a tag is added to the event, the 'published' status is gone and we need to publish it again. What about an option to allow tagging events without having to publish them again? (added tags are not exportable). Or, anybody has a better way to handle such events?

**Comment by iglocska** [comment]
We have a project for this called local tags in the works. Basically you should not be able to tag/republish someone else's event, but to allow for local filtering we want to attach a special type of tag called a local tag. These wouldn't be exported out and don't modify the event directly, but allow you to tag it for sync filtering / API filtering.

**Comment by xme** [comment]
Exactly what I'm looking for! Great!

**Comment by xme** [comment]
Any idea when the project will be available/released?

**Comment by enjeck** [comment]
@xme Local tags have been implemented. I believe this issue can be closed
