### ISSUE TITLE
Unable to Fetch feeds / Sync to servers

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#3065]
When I try to fetch a feed or sync to an external server, the job immediate fails. In error log, I see this:
2018-03-23 17:15:49 Warning: ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 553]

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| PHP version               | 7.1
| MISP version / git hash   | 2.4.89

### Expected behavior

It fetches data

### Actual behavior

Immediate fails

### Steps to reproduce the behavior

Sync any feed

**Comment by iglocska** [comment]
Interesting. Which session handler are you using in MISP? Could you check under your security settings in the server settings?

**Comment by bambenek** [comment]
Database

**Comment by iglocska** [comment]
Could you switch it to php and switch to redis sessions? The description should be in the setting itself.

**Comment by bambenek** [comment]
2018-03-26 17:41:36 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)

**Comment by iglocska** [comment]
Hmm is the /var/www/MISP/app/Config/database.php file properly filled?

**Comment by bambenek** [comment]
All looks like it was there... was working last night.

**Comment by bambenek** [comment]
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => '127.0.0.1',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		// 'port' => 5432, // PostgreSQL
		'password' => 'STIXSucks!!', (not really my password)
		'database' => 'misp',
		// 'prefix' => '',
		'encoding' => 'utf8',
		'unix_socket' => '/run/mysqld/mysqld.sock',
	);
}

**Comment by bambenek** [comment]
I switched to redis, same error... can't log in now either

**Comment by iglocska** [comment]
Damn. Is it the same server as before? I think I still have access to it, if you want I can have a look!

**Comment by bambenek** [comment]
Nope. I left Fidelis. Setting up MISP at Threatstop. Had an idle instance. Upgraded it and upgraded os to ubuntu 16.04

--
John Bambenek

**Comment by iglocska** [comment]
Ah, could you check if the mysql credentials work and you can log in after the upgrade? Could also be the php upgrade that removed the mysql connector.

**Comment by bambenek** [comment]
Password works (well not STIXsucks, but the actual one)... that's what I
was thinking about with the connector, I'm going to try to remove every
version of PHP except the latest and see if that helps. Or at least
limits what I have to look at.

**Comment by iglocska** [comment]
I remember I had a lot of weird stuff happening when I went from 14.04 -> 16.04, mostly because it wipes all PHP extensions (oh joy) - just make sure you run the setup for all of the required extensions:

`apt-get install php-cli php-crypt-gpg php-dev php-json php-mysql php-opcache php-readline php-redis php-xml` 

hopefully that solves it!

**Comment by bambenek** [comment]
Was missing php7.1-mysql... ugh. Fixed

**Comment by dmolina213** [comment]
is this the same as this  rh-php72-php-mysqlnd \ for redhat?
