### ISSUE TITLE
PostgreSQL Error on Delete Event

### ISSUE THREAD

**Issue by david-freistrom** [MISP/MISP#3066]
Hi,

I changed the postgres SQL scripts for data initialisation and schemata but there is also an issue in your php code.

I will send you an pull request for the up to date postgresql scripts when it is clear that this error is not coming from there.
Can you double check that please?

Best regards

David

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Archlinux
| PHP version               | 7.0
| MISP version / git hash   | 2.4, c2667e340ee124c00f1e41fa004cf6ff4516550b
| Browser                   | Firefox

### Expected behavior
Deleted Event

### Actual behavior

An Internal Error Has Occurred.

### Steps to reproduce the behavior

Delete an Event

### Logs, screenshots, configuration dump, ...

==> /var/www/MISP/app/tmp/logs/error.log <==
2018-03-23 17:47:17 Error: [PDOException] SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "_event_id"
LINE 1: DELETE FROM correlations WHERE 1_event_id = $1
                                        ^
Request URL: /events/delete/3
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/QueryTool.php(17): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Event.php(1247): QueryTool->quickDelete('correlations', '1_event_id', 3, Object(Event))
#2 /var/www/MISP/app/Controller/EventsController.php(1740): Event->quickDelete(Array)
#3 [internal function]: EventsController->delete('3')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

**Comment by adulau** [comment]
The recommended database for MISP is MySQL/MariaDB. 

The PostgreSQL was a kind of experiment and we are pretty sure it's broken. We would be glad to have someone looking into it and proposing pull-request. Thank you.

**Comment by 4ekin** [comment]
So error in column name 1_event_id
In postgresql you need to wrap this field in QueryTool.php this way:
$query = $connection->prepare('DELETE FROM "' . $table . '" WHERE "' . $field . '" = :value');
and it successfully delete event
And I will create PR later if it really needs someone, @adulau ?
