### ISSUE TITLE
SQL Syntax Error on add SharingGroup

### ISSUE THREAD

**Issue by david-freistrom** [MISP/MISP#3067]
Hi,

I found a second issue on insert SharingGroup. My PostgreSQL Script for creating Table lokks like the origin MYSQL Script.  The second Value '' is underscored.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Archlinux
| PHP version               | 7.0
| MISP version / git hash   | 2.4, c2667e340ee124c00f1e41fa004cf6ff4516550b
| Browser                   | Firefox

### Expected behavior

Create an SharingGroup

### Actual behavior

An Internal Error Has Occurred.

### Steps to reproduce the behavior

Add an minimal SharingGroup just with an name filled out

### Logs, screenshots, configuration dump, ...

2018-03-23 17:57:36 Error: [PDOException] SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
LINE 1: ...rg_id", "uuid", "created", "modified") VALUES (0, '', 'test'...
                                                             ^
Request URL: /sharing_groups/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('INSERT INTO "pu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1090): DboSource->execute('INSERT INTO "pu...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1940): DboSource->create(Object(SharingGroup), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/SharingGroupsController.php(72): Model->save(Array)
#6 [internal function]: SharingGroupsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SharingGroupsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SharingGroupsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by Rafiot** [comment]
Same comment as https://github.com/MISP/MISP/issues/3066#issuecomment-375856676
