### ISSUE TITLE
Feature request for new Event Graph visualization

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#3070]
Now I know this is a more want more but, would possible to "right" click on attributes or object an choose hide.
The usecase would be to describe e.g. an infection or a compromise through the object relations, but if there are information not relevant to the visual objective it should be possible to hide
these. 
As shown in the attached even the "VT" part could be nice to hide.

Also the Object should if there is one contain the objects comment.

![2018-03-24 20_01_14-events - misp](https://user-images.githubusercontent.com/14878613/37867826-2ba6aef4-2f9e-11e8-9167-f4de1d25d271.png)

**Comment by LilaLipetti** [comment]
Just thinking, I suppose there could be a flag "show in event graph" for each attribute, which could be edited in attribute list view

**Comment by SteveClement** [comment]
@mokaddem please review and close if https://github.com/MISP/MISP/pull/3154 covers this issue.

**Comment by mokaddem** [comment]
#3449 also fixed an issue, should be working by now.
