### ISSUE TITLE
Event graph: Edit button vanishes on cancelled delete

### ISSUE THREAD

**Issue by SHSauler** [MISP/MISP#3074]
*Please excuse if this has been raised before.*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 17.10
| OS version (client)       | Yucky Windows 10
| PHP version               |  7.1.15-0ubuntu0.17.10.1
| MISP version / git hash   | 2.4.89, d547726faae57ada0924f0a54514d74527c635fe
| Browser                   | Chrome

### Expected behavior

Exiting out of deleting relationships should allow to edit again.

### Actual behavior

Edit button vanishes

### Steps to reproduce the behavior

In the event graph, press on a relationship. Press on `delete selected`. Select `no`. The edit button is no longer there. If you select to delete the relationship, the edit button is still there.

### Logs, screenshots, configuration dump, ...

Edit-button, where art thou?
![image](https://user-images.githubusercontent.com/8420509/37905236-8117b548-30fe-11e8-84f0-66145ccfaf73.png)

**Comment by mokaddem** [comment]
Hi,
Thanks for the report, will be fixed in my next PR.

**Comment by SHSauler** [comment]
Thanks a bunch @mokaddem!
