### ISSUE TITLE
error when upgrading via gui | permission denied

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [MISP/MISP#3080]
Upgrading from the 2.4.88 to 2.4.89 via gui

Trying to understand where the permission issue may be so i can advise our linux admins or set permissions accordingly.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Redhat 7.4
| OS version (client)       | 10
| PHP version               |  7.1
| MISP version / git hash   | 2.4.88
| Browser                   | chrome

### Expected behavior
?  update successful

### Actual behavior
failed upgrade 
```
git pull origin  2>&1

error: cannot open .git/FETCH_HEAD: Permission denied


=================================

git submodule init && git submodule update 2>&1

```

### Steps to reproduce the behavior

Navigate to system and maintenence > MISP version
click upgrade

### Logs, screenshots, configuration dump, ...
No logs showing in GUI - let me know which logs you want and i can send them over

**Comment by adulau** [comment]
I would recommend to reset the permission of your repository with the access right of the webserver.
