### ISSUE TITLE
Disallow proposals that match an already existing attribute

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#312]
Disallow proposal that already have an attribute that match on the triplet type/value/ids so that there is no possible duplicate.

**Comment by elhoim** [comment]
Might need to check on quadruplet type/value/ids/comment since it might be an update to a comment that is proposed.

**Comment by iglocska** [comment]
Closing this one for now as there can be valid use-cases for this (such as creating a proposal before pulling an update etc). For traceability reasons we don't want to block a "duplicate" proposal on sync for example.
