### ISSUE TITLE
IDS flag not set when editing attribute

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3126]
When editing an attribute using the edit button in the event view (ie. https://misp.local/attributes/edit/343619) the IDS flag is not taken from the existing value but always set to "no/off/not checked/0". If the current value is "yes" it should be set to "yes" when editing the attribute.

I'm running 2.4.89 patch level 348858dadcced093d177c6ffa307b6bb38b63044 right now.

**Comment by iglocska** [comment]
Thanks, after a long travel day issues like this are perfect. Github streak maintained! B-)
