### ISSUE TITLE
OpenIOC export missing

### ISSUE THREAD

**Issue by Keysuke** [MISP/MISP#3128]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu 17.10 (MISP VM)
| PHP version               | 7.1.15
| MISP version / git hash   | 2.4.88, 000bbdeccabfb4e16267246f4adb54fddcea2624

### Expected behavior
According to the README, MISP should be able to export events to the OpenIOC format.

### Actual behavior
There is button for OpenIOC exporting.

### Steps to reproduce the behavior

- Go to _/events/export_.
OpenIOC export is not listed.
- Go to _/events/view/`eventnumber`_ and click on _Download as..._ 
OpenIOC download is not listed.

### Screenshots
![image](https://user-images.githubusercontent.com/12009081/38138905-5fa2a15c-342d-11e8-87e2-baaf64e56130.png)
![image](https://user-images.githubusercontent.com/12009081/38138927-7dd35d24-342d-11e8-94b3-32a58a1a5ffb.png)

**Comment by iglocska** [comment]
If an event is not published, MISP by default will only allow you to download events in formats that allow it to convey if data is not ready for consumption.

Just publish the event and you should see something like this:

![image](https://user-images.githubusercontent.com/3668672/38139367-68592026-342f-11e8-83b7-852381f0d818.png)

**Comment by Keysuke** [comment]
Thank you, is there any way to download the whole list of events that have been published using the OpenIOC format?

**Comment by buztheflash** [comment]
@adulau : It seems that the request has been added to the TODO list right?
@Keysuke and @adulau : Do you know if is any other way to download the whole list of events that have been published using the OpenIOC format via MISP APIs or using converters? 
Thank you for support.

**Comment by iglocska** [comment]
Afaik this should work, let me know if not:

POST to url: /events/restSearch/openioc
Payload:
```
{"published": 1}
```

**Comment by buztheflash** [comment]
@iglocska : Thank you. It worked perfectly :-)
I have now a big file between 1 pair of "ioc" tags.  Do you see any issue to have such a big file? Is there any way to split the ioc file per ioc item?

**Comment by iglocska** [comment]
yeah you can use any of the filtering strategies to split it. You could even create a small script that fetches the data on an event per event basis, or use time frames via the timestamp/publish_timestamp/last parameters, etc.

**Comment by buztheflash** [comment]
@iglocska I just wrote and tested the script. Worked well! Thank you for your support.

**Comment by iglocska** [comment]
Excellent, thanks for the feedback!
