### ISSUE TITLE
MISP Event Graph - Attributes and Objects

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#3129]
With the new feature Event Graph it is now possible to visualize objects and attributes of an event. However, there are some minor adjustments we can do to show bit more context.

Currently:
When events have multiple objects and attributes the event graph shows "URL" and "File" as object that are referenced to attributes. However, displaying just type of object does not provide meaningful information about an object. One can press X to expand the nodes but if the attributes are in numbers it overlaps.

See the screenshots below:
![withref](https://user-images.githubusercontent.com/12878182/38142909-e9b253cc-3489-11e8-8056-477d48ff3373.PNG)
![nodesexp](https://user-images.githubusercontent.com/12878182/38142911-ec583e34-3489-11e8-8631-1109398ffba2.PNG)

First Screenshot shows Objects without nodes expanded and second with nodes expanded. Multiple tries in re-arranging the graph still left some attributes overlapping.

Solutions/workaround:

- Have a functionality to delete attribute entry ONLY from the graph.
- Have a functionality to expand based on type of attribute you want to see from that graph - #2863 - Something similar
- Have a "Primary Key" type of feature for user to select when creating an object and that primary will be shown when an object is expanded.

**Comment by mokaddem** [comment]
Hi! Thanks for the great description. 
I'm currently working on the feature to delete (ONLY from the graph) attribute.
Also, the feature to select what kind of information to display as the object label is already implemented and should be out for the next release.
As soon as the "Primary Key" will be implemented, It will be used by default.

**Comment by mokaddem** [comment]
This is fixed. Feel free to open a new issue for a specific feature request.
