### ISSUE TITLE
GET /events should return first 100 results

### ISSUE THREAD

**Issue by AverageS** [MISP/MISP#3132]
GET request ro MISP API returns all results that leads to MISP DoS, if there are too many. I think that all search requests should return only first 100 results and take an offset as a parameter.

**Comment by adulau** [comment]
This has been implemented in the API (2.4.96 and upper). You can now do such query via restSearch (events or/and attributes level):

~~~~
{
    "returnFormat": "json",
    "last": "1d",
    "page": 1,
    "limit": 5
}
~~~~

Documentation is the following (available via MISP):

- `limit` Limit the number of results returned, depending on the scope (for example 10 attributes or 10 full events).
- `page` If a limit is set, sets the page to be returned. page 3, limit 100 will return records 201->300).
