### ISSUE TITLE
Correlations table grows exponentially

### ISSUE THREAD

**Issue by MattCarothers** [MISP/MISP#3142]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| PHP version               | 7.0
| MISP version / git hash   | 2.4.89
| Browser                   | If applicable

### Expected behavior

Correlation table should grow linearly.

### Actual behavior

For N correlated events, the number of table rows is N^2 - N.  For example, we have 2205 events with the same AS number attribute.  There are nearly 5 million rows in the correlations table for those events.

On another MISP instance, we're unable to add any new events if the attributes correlate because the ID field in the correlations table is a signed integer, and we've exceeded 2^31 entries.

Recommendation: rather than storing correlations as pairs of events, store them as pairs of attributes and event ids.  E.g. for two events 10 and 20 with common attributes 1000 and 2000, the current table looks something like this:

```
+----+-------+----------+--------------+------------+----------------+
| id | value | event_id | attribute_id | 1_event_id | 1_attribute_id |
+----+-------+----------+--------------+------------+----------------+
|  1 | X     |       10 |          100 |         20 |            200 |
|  2 | X     |       20 |          200 |         10 |            100 |
+----+-------+----------+--------------+------------+----------------+
```
To store it linearly, construct the table more like this:

```
+----+-------+----------+--------------+
| id | value | event_id | attribute_id |
+----+-------+----------+--------------+
|  1 | X     |       10 |          100 |
|  2 | X     |       20 |          200 |
+----+-------+----------+--------------+
```

Each new event with an attribute value "X" would just be one additional row in the table.  To find the events correlated with event_id 10, join the correlations table to the attributes table on the value column.  Something along these lines:
```
SELECT DISTINCT(c.event_id) AS correlated_event_id 
    FROM attributes a 
    INNER JOIN correlations c ON a.value1 = c.value 
    WHERE a.event_id = 10;
```
Add an additional key to the value column of the correlations table because the existing fulltext key won't be used in the join.

### Steps to reproduce the behavior

Add events with matching attributes.

### Logs, screenshots, configuration dump, ...

```
MariaDB [misp]> select count(distinct(event_id)) from correlations where value = '<redacted>'; 
+---------------------------+
| count(distinct(event_id)) |
+---------------------------+
|                      2205 |
+---------------------------+

MariaDB [misp]> select count(*) from correlations where value = '<redacted>';
+----------+
| count(*) |
+----------+
|  4859820 |
+----------+
```
```
2018-04-04 17:51:36 Error: [PDOException] SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
Request URL: /events
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(898): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(1768): Mysql->insertMulti('`misp`.`correla...', '`value`, `1_eve...', Array)
#2 /var/www/MISP/app/Model/Attribute.php(605): Attribute->__afterSaveCorrelation(Array)
```
```
MariaDB [misp]> INSERT INTO `misp`.`correlations` (`value`, `1_event_id`, `1_attribute_id`, `event_id`, `attribute_id`,>
ERROR 167 (22003): Out of range value for column 'id' at row 1
MariaDB [misp]> show create table correlations\G
*************************** 1. row ***************************
       Table: correlations
Create Table: CREATE TABLE `correlations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
[snip]

MariaDB [misp]> select max(id) from correlations; 
+------------+
| max(id)    |
+------------+
| 2147483619 |
+------------+
```

**Comment by adulau** [comment]
Whoaaaaa it's indeed a lot. Aren't you importing all feeds into a new event at each run? This would explain such number of correlation.

**Comment by iglocska** [comment]
You have the same data 2205 times in the example above, it sounds like you're pulling in the same data over and over. Are you pulling in feeds into new events each time or something?

**Comment by MattCarothers** [comment]
We've run into this in a couple of places, both of which were received from partners rather than from MISP feeds.  In the first case, the partner was putting things like TLP markings into attributes instead of tags, so we had hundreds of millions of correlation table entries for attributes like "GREEN."  That's a case of receiving bad data, but of course I didn't expect it to crash MISP. :)  The second case, which is the 2205 events above, are events generated from the DHS Automated Indicator Sharing program.  One of our partners imports the STIX packages and turns them into MISP events.

**Comment by iglocska** [comment]
Argh. That is indeed bad, need to look at some solutions for crazy
situations like that (Perhaps limit the number of correlations loaded
beyond a given size as it becomes unmanageable anyway...).

**Comment by LilaLipetti** [comment]
.. just my thinking...
Maybe an option in Server Settings to allow/disallow correlation based on tags set on the attributes?
So that correlation on tags are only on event level..
... but if it's the values which are correlated ...

**Comment by combobulator** [comment]
Just ran into this issue, our correlations table was eating up all our disk too.

Dropping and re-creating the table freed up ~37GB of a 50GB partition and solved other issues we were having.
I followed the statements [scrubllulz posted](https://github.com/MISP/MISP/issues/3719#issuecomment-425221300) and everything seems OK now.

A way to selectively enable correlations via the UI would be useful.
I'm aware it's possible to use `disable_correlation=True` when interacting with PyMISP, but this doesn't help with data we don't own :(

**Comment by iglocska** [comment]
That is indeed a good point. Disabling the correlation should be something
that can happen decoupled from the normal event ownership. Hmph. Let's
think about some solutions for this.

**Comment by SteveClement** [comment]
Please open a new issue to track this feature change.
