### ISSUE TITLE
Search triggers 'Undefined variable: blockedAttributeTags' error if debug is enabled

### ISSUE THREAD

**Issue by neok0** [MISP/MISP#3145]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       |10
| PHP version               | 7.x.
| MISP version / git hash   | 2.4.89

### Expected behavior
Return of json output of matching events.
Using pymisp to search for matching Events, triggers internal error.
This behavior only appears if 'Debug ON' setting is enabled.

### Actual behavior
Error is thrown: 
Undefined variable: blockedAttributeTags [APP/Controller/EventsController.php, line 3039]

### Steps to reproduce the behavior
1. Create Event
2. Enable Debug ON
3. Use Pymisp test code (edit url and key, and event name):

class Bla:
    def __init__(self):
        self.misp_url = '<url>'
        self.misp_key = '<key>'
        self.misp = misp_api.PyMISP(url=self.misp_url,
                                    key=self.misp_key,
                                    ssl=False)
    def test(self):
        event_name = "<Event Name>"
        res = self.misp.search_all(event_name)
        print(res)

if __name__ == '__main__':
    b = Bla()
    b.test()

### Logs, screenshots, configuration dump, ...
Notice (8): Undefined variable: blockedAttributeTags [APP/Controller/EventsController.php, line 3039]
Code Context
EventsController::restSearch() - APP/Controller/EventsController.php, line 3039
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

{"response":[{ "Event": { "id": "1", "orgc_id": "1", "org_id": "1", "date": "2018-04-10", "threat_level_id": "1", "info": "testevent", "published": true, "uuid": "XXXXXX", "attribute_count": "1", "analysis": "0", "timestamp": "1523347945", "distribution": "1", "proposal_email_lock": false, "locked": false, "publish_timestamp": "1523347963", "sharing_group_id": "0", "disable_correlation": false, "event_creator_email": "admin@admin.test", "Org": { "id": "1", "name": "ORGNAME", "uuid": "XXXXX" }, "Orgc": { "id": "1", "name": "ORGNAME", "uuid": "XXXX" }, "Attribute": [ { "id": "1", "type": "filename", "category": "Artifacts dropped", "to_ids": false, "uuid": "XXXX", "event_id": "1", "distribution": "5", "timestamp": "1523347945", "comment": "", "sharing_group_id": "0", "deleted": false, "disable_correlation": false, "object_id": "0", "object_relation": null, "value": "test.sh", "ShadowAttribute": [] } ], "ShadowAttribute": [], "RelatedEvent": [], "Galaxy": [], "Object": [] } }]} )

**Comment by github-germ** [comment]
i also experienced this as reported in the now closed/dup https://github.com/MISP/MISP/issues/3165

**Comment by iglocska** [comment]
This should be fixed already.
