### ISSUE TITLE
Could not import STIX document

### ISSUE THREAD

**Issue by zacharycheng** [MISP/MISP#3146]
when I try to upload some STIX xml files to misp, it keeps telling me that 'Could not import STIX document: Issues executing the ingestion script or invalid input. Check whether the dependencies for STIX are met via the diagnostic tool.' However, when I  to Diagnostics in Server Settings & Maintenance, it says it's OK in the STIX and Cybox libraries box. Can anybody have me to figure out where the problem is? Thanks.

<img width="1000" alt="2018-04-11 3 38 22" src="https://user-images.githubusercontent.com/17289377/38602904-bd893540-3d9e-11e8-91d1-fefed4ae3c03.png">

**Comment by iglocska** [comment]
Interesting, could you share any of the STIX files that causes this with us?

**Comment by zacharycheng** [comment]
sure, I am using a sample from the MISP-STIX-Converter for testing and here is the file 

`<stix:STIX_Package 
	xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
	xmlns:cybox="http://cybox.mitre.org/cybox-2"
	xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2"
	xmlns:AddressObj="http://cybox.mitre.org/objects#AddressObject-2"
	xmlns:example="http://example.com"
	xmlns:coa="http://stix.mitre.org/CourseOfAction-1"
	xmlns:stixCommon="http://stix.mitre.org/common-1"
	xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1"
	xmlns:stix="http://stix.mitre.org/stix-1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
	http://cybox.mitre.org/common-2 http://cybox.mitre.org/XMLSchema/common/2.1/cybox_common.xsd
	http://cybox.mitre.org/cybox-2 http://cybox.mitre.org/XMLSchema/core/2.1/cybox_core.xsd
	http://cybox.mitre.org/default_vocabularies-2 http://cybox.mitre.org/XMLSchema/default_vocabularies/2.1/cybox_default_vocabularies.xsd
	http://cybox.mitre.org/objects#AddressObject-2 http://cybox.mitre.org/XMLSchema/objects/Address/2.1/Address_Object.xsd
	http://stix.mitre.org/CourseOfAction-1 http://stix.mitre.org/XMLSchema/course_of_action/1.2/course_of_action.xsd
	http://stix.mitre.org/common-1 http://stix.mitre.org/XMLSchema/common/1.2/stix_common.xsd
	http://stix.mitre.org/default_vocabularies-1 http://stix.mitre.org/XMLSchema/default_vocabularies/1.2.0/stix_default_vocabularies.xsd
	http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.2/stix_core.xsd" 
	id="example:Package-495c4c04-b5d8-11e3-b7bb-000c29789db9" 
	version="1.2">
    <stix:Courses_Of_Action>
        <stix:Course_Of_Action id="example:coa-495c9b28-b5d8-11e3-b7bb-000c29789db9" xsi:type='coa:CourseOfActionType' version="1.2">
            <coa:Title>Block traffic to PIVY C2 Server (10.10.10.10)</coa:Title>
            <coa:Stage xsi:type="stixVocabs:COAStageVocab-1.0">Response</coa:Stage>
            <coa:Type xsi:type="stixVocabs:CourseOfActionTypeVocab-1.0">Perimeter Blocking</coa:Type>
            <coa:Objective>
                <coa:Description>Block communication between the PIVY agents and the C2 Server</coa:Description>
                <coa:Applicability_Confidence>
                    <stixCommon:Value xsi:type="stixVocabs:HighMediumLowVocab-1.0">High</stixCommon:Value>
                </coa:Applicability_Confidence>
            </coa:Objective>
            <coa:Parameter_Observables cybox_major_version="2" cybox_minor_version="1" cybox_update_version="0">
                <cybox:Observable id="example:Observable-356e3258-0979-48f6-9bcf-6823eecf9a7d">
                    <cybox:Object id="example:Address-df3c710c-f05c-4edb-a753-de4862048950">
                        <cybox:Properties xsi:type="AddressObj:AddressObjectType" category="ipv4-addr">
                            <AddressObj:Address_Value>10.10.10.10</AddressObj:Address_Value>
                        </cybox:Properties>
                    </cybox:Object>
                </cybox:Observable>
            </coa:Parameter_Observables>
            <coa:Impact>
                <stixCommon:Value xsi:type="stixVocabs:HighMediumLowVocab-1.0">Low</stixCommon:Value>
                <stixCommon:Description>This IP address is not used for legitimate hosting so there should be no operational impact.</stixCommon:Description>
            </coa:Impact>
            <coa:Cost>
                <stixCommon:Value xsi:type="stixVocabs:HighMediumLowVocab-1.0">Low</stixCommon:Value>
            </coa:Cost>
            <coa:Efficacy>
                <stixCommon:Value xsi:type="stixVocabs:HighMediumLowVocab-1.0">High</stixCommon:Value>
            </coa:Efficacy>
        </stix:Course_Of_Action>
    </stix:Courses_Of_Action>
</stix:STIX_Package>
`

**Comment by chrisr3d** [comment]
I updated the STIX import, can update your MISP and try it again ?
If the problem is still here, it should come from somewhere else and we will check with @iglocska

**Comment by zacharycheng** [comment]
How can I update the MISP and which branch I should try? using git pull??  I installed using the command and it still does not work for me after git pull.

**Comment by iglocska** [comment]
Before you try to update it ensure that you are currently on the right branch and you don't have any local modifications, simply type the following:

```git status```

in your /var/www/MISP directory.

This should tell you what branch you're on and whether there are any changes to be committed. 

If you are on 2.4 run the following command:

```git pull origin 2.4```

This will get you to the latest version of MISP.

If you are on a different branch or no branch, first run this:

```git checkout 2.4```

Let us know if it doesn't work.

**Comment by zacharycheng** [comment]
no, it still does not work after updated the MISP

**Comment by arcsector** [comment]
This seems to be an issue inherent with the STIX validator... An issue needs to be made on their repo.

**Comment by kara-1234** [comment]
Does this not work because they're doing a STIX 1.2 import? I am running into the same issue trying to import 1.2, stix 1.1.1 works fine.

**Comment by chrisr3d** [comment]
@kara-1234 could you by any chance share any of the STIX files you are trying to import and that is not working ?
