### ISSUE TITLE
Org search should include domain for lookup

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#3147]
(1) If searching for cert.abc in the List Org search field and the org is named cert-abc, despite the fact that the users have cert.abc email addresses and the 'restrict users to domain cert.abc' is set.
Only if contact users are added, the search returns results. (user@cert.abc).

(2) Btw., the field 'restrictions' in the org list is not showing what it should.

**Comment by iglocska** [comment]
Fixed, thanks!
