### ISSUE TITLE
Propose to delete an attribute

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#315]
Add the feature to create a proposal to delete an attribute.

**Comment by cvandeplas** [comment]
Can you confirm this will be included within the 2.4 release?

**Comment by iglocska** [comment]
It's not implemented yet, but sure, can make it a priority to have this.

**Comment by iglocska** [comment]
Christophe, you are so slow with replying that it was faster to just implement it! :) It's available on the 2.4 (feature/sg) branch.

**Comment by cvandeplas** [comment]
thank you !
Is this also propagated in the sync mechanism? If yes, Is this just managed by the updated timestamp of the event?

**Comment by iglocska** [comment]
It is, and it's not. Proposals are propagated on a separate mechanism and
they all have their own timestamps.

They are propagated on:
1. creation
2. full push/pull, regardless of the event's own timestamp.

**Comment by Rafiot** [comment]
Fixed.
