### ISSUE TITLE
 Support Target Threat Index (TTI)

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#317]
https://targetedthreats.net/media/2.1%20Extended%20Analysis-SMDA.pdf

Add TTI (Targeted Threat Index) values as attributes for an event.
An alternative is to add as an optional part of an event.

**Comment by adulau** [comment]
@elhoim the TTI is now a MISP taxonomy https://github.com/MISP/misp-taxonomies/blob/master/targeted-threat-index/machinetag.json
