### ISSUE TITLE
Long term improvement: Pivoting on time

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3176]
It would be nice to have to pivot on a timeline. Connecting events based on the time they occurred. 

Maybe using the sightings?

**Comment by iglocska** [comment]
This was something we've been discussing for a long time - pivoting on time is definitely something we need, but I think it will only become really feasible once we decouple the sightings to start getting more substantial amounts of data points into the system first.

**Comment by Rafiot** [comment]
WiP, closing this one
