### ISSUE TITLE
Force use of tags at instance level, org, or sharing group

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3179]
It is currently not possible to require at least one tag from a specific taxonomy to be set on an event (or an attribute).

For example, requiring to set a TLP tag on every event created on an instance, by an org, or by a sharing group.

**Comment by matthias-seitz** [comment]
That would be very useful!

In our use case we are using the RSIT and TLP taxonomy, so I want to make sure that for new events, the user selects one tag from the RSIT taxonomy and one tag from the TLP taxonomy.

There are two views to the problem:
- We need both tags to ensure that we can use the data in automated tasks.
- Second point: It would also support the user (user experience) if he/she forgets to set the taxonomy. So an error/warning message would be a very useful reminder.

**Comment by matthias-seitz** [comment]
The feature has been implemented
https://github.com/MISP/MISP/issues/4321
https://twitter.com/Iglocska/status/1108427448696401921

**Comment by iglocska** [comment]
Indeed, thanks for pointing it out :)

**Comment by iglocska** [comment]
(I really suck at hunting down old issues when implementing stuff)
