### ISSUE TITLE
STIX Export - Stix Package empty?!

### ISSUE THREAD

**Issue by jhemp** [MISP/MISP#318]
When I export a MISP event to stix (Save to STIX XML), I find that the main stix package is empty and the informations about the event are actually stored in a referenced package.

However STIX States: 'Characterizes one or more relationships to other Packages.'[1]

I would suggest to change to the following:

the event you are downloading should be in the mainPackage and the related events should be found in the referenced packages, if you want to export them too.

Some example without relations
events = loadEvent(args, pathname)
if len(events) > 1:
    raise Exception('Not supported yet')
else:
     event = events[0]
     package = generateEventPackage(event)
     saveFile(args, pathname, package)
     print json.dumps({'success' : 1, 'message' : ''})

[1]http://stixproject.github.io/data-model/1.1.1/stix/STIXType/

**Comment by adulau** [comment]
I suppose we can close this old issue. If you still have the issue, feel free to reopen.  Thank you.
