### ISSUE TITLE
Session.cookie_timeout value removed after set

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#3182]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 18.04
| PHP version               | PHP 7.0.28-0ubuntu0.16.04.1
| MISP version / git hash   | v2.4.90 (2d4535aeac64a5cf5cd8bab275205b87d69b0160)
| Browser                   | Chrome 66.0.3359.117

After update at section Server Settings & Maintenance tab Securrity settings row:
Critical | Session.cookie_timeout
unable to set cookie_timeout value. Value is removed. Event try write in config.php directly. After refresh in browser from config.php cookie_timeout ir removed. No actions in logs.

**Comment by BenjaminJoly** [comment]
Just to let you know, I've also met the same bug. This also the same issue as #3171.

**Comment by iglocska** [comment]
Reproduced on my end too, not quite sure what's going on there. Will
investigate it tomorrow.
