### ISSUE TITLE
STIX - Everything is related!?

### ISSUE THREAD

**Issue by jhemp** [MISP/MISP#319]
This ticket is related to #318

Further investigation showed that the export is completely done by related_indicators, related_incidents, etc...

Why did you do this? Is the event which you want to download only a relation to the event it self?

**Comment by FloatingGhost** [comment]
Ach, this is a frustrating one - syncronising between MISP and a STIX-only platform doesn't really work -- some of the stuff referenced in the export package isn't actually included in it.

You end up with situations in which you have millions of RelatedPackages, but the stuff they refer to isn't actually there; has anyone made any progress with this one?

**Comment by iglocska** [comment]
Interesting, what platform is it that cannot ingest it?

**Comment by FloatingGhost** [comment]
[SOLTRA](https://soltra.com/)

It's purely STIX-based, but when I do a straight export/import without changing the data, I get something that looks a bit like this:

[Without Editing the data](https://gyazo.com/0a64ee928b5fdb59153fd62c0a4bf7c6)

[When extracting related packages](https://gyazo.com/0a64ee928b5fdb59153fd62c0a4bf7c6)

It seems as if all indicators just get dropped somehow

**Comment by iglocska** [comment]
Hmph, interesting. Haven't heard of this issue with Soltra before, I'll look into it.

**Comment by jhemp** [comment]
It's perhaps that, the indicators are part of the incident object.
MISP creates the objects as follows

Package -> Incident -> Indicators

Perhaps soltra uses the following structure

Package -> Indicator

**Comment by FloatingGhost** [comment]
I'm looking over misp2stix.py now, my god PEP-8 is crying with this one.

Call me out if I'm wrong, but aren't incidents gonna be for the whole "Sightings" thing? Surely plain MISP events should be packaged up like

```
Export:
  Package for event:
    Indicators [From event attributes]
   Incidents:
     Any sightings
```

That makes sense to me, but I don't know if it's how MISP is meant to be used -- or rather, it's appropriate for our internal MISP usage, but the wider idea might be different.

**Comment by jhemp** [comment]
sorry there is a mistake from my part the misp stix is

Package:
    Related_Packages
        Incidents
            Indicators

For the "Sightings" thing,  the IndicatorType has sightings to represent, when / where it was seen etc. (My understanding of these Stix elements). 

I guess it it easier to look at both exports (Soltra / MISP) and spot the differences. I really be that the relatedPackets element is the issue.

**Comment by FloatingGhost** [comment]
Yeah, I'm attempting to rework the export script a little -- less reliance on related

**Comment by iglocska** [comment]
Oh excellent, if you could do a PR with the changes that would be great. Also, in the near future we'll rework the STIX export once the export modularity in MISP is ready, so we can just migrate your changes to that once it's time. Thanks in advance!

**Comment by iglocska** [comment]
@jhemp is indeed correct, sightings are represented on an indicator level.

**Comment by FloatingGhost** [comment]
This might take a few days, this generation script is... interesting. 

Non-existent documentation yay <3

**Comment by iglocska** [comment]
Sorry about that!

**Comment by athiasjerome** [comment]
Just FYI, STIX v2.0 (aka STIX JSON) would come in a near future (where the Data Model changed, and the Relationships are "open")

**Comment by iglocska** [comment]
Indeed, the goal is to move to STIX v2.0 as soon as it makes sense. We're waiting for the finalisation of the spec.

**Comment by FloatingGhost** [comment]
"Near future" for STIX could mean anywhere from next year to the heat death of the universe

**Comment by iglocska** [comment]
Yep. I am not expecting bindings / an API this year to be honest.

**Comment by FloatingGhost** [comment]
[Much better](https://gyazo.com/db389137286faebcacbb9bb93112fe31)

Now just a few more types of object and we should be cool

**Comment by iglocska** [comment]
Hmm, I've just set up Soltra and tried to import some events from MISP and it seems to work as intended... Which version of Soltra are you running?

What I tried (Soltra Edge 2.8.0): 

Upload STIX XML export of an event to MISP -> import it in Soltra Edge as a STIX 1.1.1 document.

![soltra](https://cloud.githubusercontent.com/assets/3668672/16978674/65cacd28-4e5d-11e6-93a8-f03772037797.PNG)

**Comment by FloatingGhost** [comment]
We're on 2.8.1 -- were there no broken ID links on your instance?

**Comment by iglocska** [comment]
It looks OK to me, Which export were you using in MISP? Going through the download as button on an event? Or the API?

**Comment by iglocska** [comment]
Would it be possible for you to share the export that fails?

**Comment by FloatingGhost** [comment]
yeah sure, I had to export something that wasn't restricted, this shows it off -- directly exported from MISP, then to SOLTRA

[The XML file from MISP](https://a.pomf.cat/ipgmvn.xml)
[It seems to know the package titles, so that's good](https://waa.ai/jv8K)
[But alas, external reference](https://waa.ai/jv8R)

**Comment by FloatingGhost** [comment]
I do apologise, that was the wrong file

[here is the proper one](https://a.pomf.cat/aufqar.xml)

**Comment by iglocska** [comment]
Interesting, I'll try to have a look over the weekend. So the relation type between the incident and the container package being a related to as opposed to a contains is causing the issues? Or is it also an issue for the objects attached to the incident (Indicators, Observables, etc)?

**Comment by FloatingGhost** [comment]
I'm not sure, I'll try to mess with it a bit and get back to you

**Comment by iglocska** [comment]
Feel free to open PRs for any changes you make. If you end up diverging too much from the original export scripts we can also just duplicate it and offer both options in MISP separately to keep things intact for those that rely on the old format. 

Thanks a lot for looking into it!

**Comment by Rafiot** [comment]
Let's continue the conversation over there: https://github.com/MISP/MISP-STIX-Converter
