### ISSUE TITLE
/feeds/add API doesn't work

### ISSUE THREAD

**Issue by allenxian** [MISP/MISP#3194]
import requests
import json
import os

url = 'http://192.168.247.150/feeds/add'
body = {"source_format": "freetext","url":"\/home\/misp\/critica\/tes.txt","name": "1312","input_source": "local","provider": "12312"}
headers = {'Authorization': '7g9EyeoTPfVmLJkB1ZrJ3fXEUBEg9Ft1uXQCMDoa', 'Accept': 'application/json','Content-Type': 'application/json'}

response = requests.post(url, body, headers = headers)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       |  ubuntu
| OS version (client)       |  Ubuntu, ...
| PHP version               | 7.1
| MISP version / git hash   | 2.4.9
| Browser                   | If applicable

**Comment by adulau** [comment]
Just tested on a recent version of MISP, it should work. 

Here is the description of the API:

~~~~
{
    "name": "\/feeds\/add API description",
    "description": "POST a MISP Feed descriptor JSON to this API to add a Feed.",
    "mandatory_fields": [
        "source_format",
        "url",
        "name",
        "input_source",
        "provider"
    ],
    "optional_fields": [
        "enabled",
        "caching_enabled",
        "lookup_visible",
        "delete_local_file",
        "headers",
        "fixed_event",
        "target_event",
        "settings",
        "publish",
        "override_ids",
        "delta_merge",
        "distribution",
        "sharing_group_id",
        "tag_id",
        "pull_rules",
        "rules",
        "event_id"
    ],
    "url": "\/feeds\/add"
}
~~~~
