### ISSUE TITLE
Custom Sighting Source not working

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#3199]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16
| OS version (client)       | Windows 10
| PHP version               | 7.0
| MISP version / git hash   | v2.4.90 (5f0b92e799e728f24eeaaa25b47f7a83f2e44566)	
| Browser                   | Chrome 66

### Expected behavior
Input a sighting via the gui with a custom source such as "User Reported Phishing" or "IPS"

### Actual behavior
Interface locks up and doesn't process the request. Only thing you can do is cancel.

### Steps to reproduce the behavior
Try to place a sighting in where you add the Source in the text box. 

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/20773170/39385007-b7f0c896-4a3c-11e8-828c-bb66dea39ef7.png)

**Comment by adulau** [comment]
![test](https://user-images.githubusercontent.com/3309/39393116-84031dec-4ac1-11e8-8bac-0e1711250aec.png)

I did a quick test but I cannot reproduce the bug. Could you check the error log?

**Comment by syloktools** [comment]
It is working now.
