### ISSUE TITLE
Export of tags via the API

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#320]
It would be nice to have the tags exported from the ReST API.

**Comment by adulau** [comment]
I think the export of tag is quite important via the API. At least to see the tags associated to an event, as a first step.

**Comment by elhoim** [comment]
Re to this, https://github.com/MISP/MISP/commit/01398b3aded744d557f2cf12ccd40098b0b25ffe added the capability of adding & removing tags to events

**Comment by Rafiot** [comment]
Fixed
