### ISSUE TITLE
/servers/add via REST API does not work

### ISSUE THREAD

**Issue by felixpk** [MISP/MISP#3202]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu (VM)
| OS version (client)       | Ubuntu
| MISP version   | 2.4.90, Latest VM

#### Header
| Key | Value
|---|---
|Authorization| API_KEY
|Accept|application/json
|Content-Type|application/json

#### Body

```
{	
	"json":{
		"id":"0"
	},
	"url":"http://sample.server",
	"name":"ANAME",
	"organisation_type":"0",
	"authkey":"40 CHARACTERS"
	
}
```

### Expected behavior
A new server added to the MISP instance

### Actual behavior

- 403 Forbidden error
or
- 500 Internal Server error

both with no further explanation about what went wrong

### Steps to reproduce the behavior

- POST request to **BASE_URL/servers/add**

### Further Information

The GET request gives the expected 

```
{
    "name": "/servers/add API description",
    "description": "POST an Server object in JSON format to this API to add a server.",
    "mandatory_fields": [
        "url",
        "name",
        "organisation_type",
        "authkey",
        "json"
    ],
    "optional_fields": [
        "push",
        "pull",
        "push_rules",
        "pul_rules",
        "submitted_cert",
        "submitted_client_cert"
    ],
    "url": "/servers/add"
}
```
All other POST and GET requests like adding a user or an organisation work like expected.

**Comment by iglocska** [comment]
Thanks for the heads-up, it was indeed broken. Please check the updated list of mandatory fields, should work with the new rules described there. Example:

```
{
  "url": "https://misppriv.circl.lu",
  "name": "misppriv",
  "remote_org_id": 1,
  "authkey": "1111111111111111111111111111111111111111"
}
```
