### ISSUE TITLE
PDF export via JS - interesting library (following discussion)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#3206]
PDF export via JS - interesting library (following discussion with @mokaddem)

* https://github.com/RelaxedJS/ReLaXed

**Comment by iglocska** [comment]
How will this work with your noscript?

/trololo

**Comment by adulau** [comment]
@iglocska I'm not the target audience ;-) All fine.

**Comment by iglocska** [comment]
Jokes aside, best would be not to do it through JS. Either PHP or Python - otherwise we can't get PDF output via the API ;)

**Comment by RichieB2B** [comment]
*cough* node.js *cough*

**Comment by iglocska** [comment]
Short answer: No.
Longer answer: \*\*\*\* No.

**Comment by adulau** [comment]
I'll close the issue.
