### ISSUE TITLE
MISPObject - Disable correlation not working

### ISSUE THREAD

**Issue by Vince147** [MISP/MISP#3207]
Hi MISP dev,

I am trying to disable correlation on specific fields of the MISP object. I tried two thing but none of them are working.

* adding the field "disabling_correlation" in the MISP object json :: didn't work. [from MISP documentation]
* setting the object attribute property disable_correlation to true :: didn't work

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug 
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 16, Windows 10, Windows 7
| PHP version               | 7.0
| MISP version / git hash   | 2.4.82
| Browser                   | Chrome, FireFox

### Expected behavior

![image](https://user-images.githubusercontent.com/23407126/39456542-3b649ffc-4cb5-11e8-9f0b-8ccde34b1365.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/23407126/39456554-4f35d622-4cb5-11e8-9bdb-ca63eb8f81ca.png)

### Steps to reproduce the behavior

* Added the following MISP object

``` python
{
	"version": 1,
	"description":  "My custom object.",
	"meta-category": "CUSTOM",
	"uuid":  "93a0a1ac-5c23-4270-31a1-eee8dc2a8b67",
	"name":  "CustomObject",
	"required":  [
		"value",
		"date_creation",
		"author",
		"reference"
	],
	"attributes":  {
		"value":  {
			"description" : "The value field.",
			"ui-priority" : 0,
			"misp-attribute" : "text"
		},
		"date_creation": {
			"description": "The creation date.",
			"ui-priority": 1,
			"disable_correlation": true,
			"misp-attribute": "datetime",
			"categories": ["Other"]
		},
		"author": {
			"description": "The author name.",
			"ui-priority": 1,
			"disable_correlation": true,
			"misp-attribute": "text",
			"categories": ["Internal reference"]
		},
		"reference": {
			"description": "The reference number.",
			"ui-priority": 1,
			"disable_correlation": true,
			"misp-attribute": "text",
			"categories": ["Other"]
		}
	}
}
```
When I realized that the field "disable_correlation" was doing nothing, I created a custom function to disable the correlation on the attribute level, but there still related events displayed on the event page (actual behaviour printscreen). That is a real bug.

Because MISP is keeping doing correlation in the background, each event added is making the process slower and this have a huge impact on performance because MISP become unusable until it finish the job (for instance, adding 1000 objects can take 5-10 minutes).

### Logs, screenshots, configuration dump, ...

When looking at the database, the table seem suspicious, like a typo or something .

![image](https://user-images.githubusercontent.com/23407126/39456314-b7d26dd2-4cb3-11e8-94ce-3aa2d6d611c9.png)

![image](https://user-images.githubusercontent.com/23407126/39456350-eacfddbe-4cb3-11e8-9074-568a56c907d7.png)

Thanks for the help.

**Comment by StefanKelm** [comment]
Maybe related to #2166

**Comment by Vince147** [comment]
Agree this is the same bug. However, there is more details here. Still no answer from the dev.

**Comment by SteveClement** [comment]
@Vince147  @StefanKelm #2166 is fixed.
Can you confirm if this. issue is fixed too.

**Comment by StefanKelm** [comment]
@SteveClement thank you! Over here it looks partly fixed: the _Related Events_ correctly disappear but the _Feed hits_ are still being displayed:

![feed](https://user-images.githubusercontent.com/25325656/42443303-603cd972-836d-11e8-8262-02910ca2ef29.png)

**Comment by iglocska** [comment]
Yeah indeed, feed hits aren't disabled - on the other hand they're also
"free" as opposed to correlations :)

**Comment by iglocska** [comment]
Unless I misunderstood, if it disables it for attributes outside of objects
but not for objects it's a bug.

**Comment by StefanKelm** [comment]
No, you got it right @iglocska

**Comment by p3tr0v** [comment]
@SteveClement Still not working
I created an object, set 'disable correlation' true but MISP are correlating yet.

My object
![config](https://user-images.githubusercontent.com/28512249/44112964-fba19b42-9fdc-11e8-8118-88718ed71b96.png)

The object populated
![capturar](https://user-images.githubusercontent.com/28512249/44112990-0cb8c6bc-9fdd-11e8-93b1-6b69c066e864.PNG)

But in the graph MISP correlate them, I think they didn't have to correlate, this make the graph visual poluted
![correlacao](https://user-images.githubusercontent.com/28512249/44112998-13f2aa74-9fdd-11e8-986a-fbc2bac6d5d2.png)

MISP version 2.4.94
Thanks

**Comment by mokaddem** [comment]
Hi @p3tr0v, we recently fixed a bug preventing correct saving of the ``disable_correlation`` field. Your problem should now be fixed.
If it's not the case, feel free to reopen the issue.
