### ISSUE TITLE
Need assistance with errors

### ISSUE THREAD

**Issue by abermommy** [MISP/MISP#3208]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat
| OS version (client)       | 7.4
| PHP version               | rh-php71-1-1.el7.x86_64
| MISP version / git hash   | 2.4.89
| Browser                   | N/A

### Expected behavior
Access to the web UI

### Actual behavior
I receive a 404

### Steps to reproduce the behavior
I'm trying to access the web UI but I've obviously done something incorrectly. I followed the instructions explicitly when installing.

### Logs, screenshots, configuration dump, ...
2018-05-01 08:36:56 Error: [MissingControllerException] Controller class MispController could not be found.
Exception Attributes: array (
  'class' => 'MispController',
  'plugin' => NULL,
)
Request URL: /misp/users/login
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-05-01 08:36:56 Error: Fatal Error (64): Can't use function return value in write context in [/var/www/MISP/app/Controller/AppController.php, line 311]
2018-05-01 08:36:56 Error: [InternalErrorException] Internal Server Error
Request URL: /misp/users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(64, 'Can't use funct...', '/var/www/MISP/a...', 311)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 311, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var/www/MISP/a...', 311, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by adulau** [comment]
It seems something is incorrect in the install process. Could you review the config of your MISP (such as MySQL database config), permission and alike?

**Comment by iglocska** [comment]
It sounds like you've been trying to access MISP via the wrong URL.

You've tried to access https://myurl/MISP instead of https://myurl

What MISP is telling you that whilst you're as expected hitting the application, but you're requesting the wrong end-point (/MISP).

**Comment by abermommy** [comment]
@adulau - I went back over the instructions for setting permissions, and I checked that the database, user, and password were correct in the php config. Is there anything specific I should check for that might not be in the instructions doc?
@iglocska - If I just go to https://myurl I get the Apache test page. That's not right!

**Comment by iglocska** [comment]
Misconfigured apache .conf file?

**Comment by SteveClement** [comment]
Dear @abermommy

Is this issue still ongoing?

In case it is please re-open.

Closing after 2 Weeks of inactivity.
Sincerely.
