### ISSUE TITLE
download STIX2 format json file is empty

### ISSUE THREAD

**Issue by cathy927** [MISP/MISP#3209]
Hi,

I installed STIX2 library by using:  pip3 install stix2
But when I wanted to download the event information as STIX2 format on the view event page, the json file was empty. The other formats work very well.

Did I do something wrong?

Thank you!

**Comment by SteveClement** [comment]
@cathy927 that is practically what needs to be done.

Have you tried the latest code? We did fix some stix2 issues there.
Please re-open if still an issue for you.
