### ISSUE TITLE
GUI enhancement request: different color for flash notifications and errors

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#321]
Currently, all notifications using Session->setFlash() in the GUI are shown as red. This is pretty confusing when most of the time these are mere notifications. It would be much clearer if only errors and warnings are colored red, and notifications use a more neutral color like blue or green.

**Comment by adulau** [comment]
I think this one has been recently fixed in 68b8266584fe055f2f34060a1fb0f17b764250de
