### ISSUE TITLE
Add Sync Server Fails

### ISSUE THREAD

**Issue by felixpk** [MISP/MISP#3210]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu VM
| OS version (client)       |  Ubuntu
| MISP version   | 2.4.90 (latest VM)
| Browser                   |  Chrome

As I follow this #2595 I ran into a problem I didn't had with MISP Version 2.4.89:

When I try to create the syncServer with AuthKey from remote SyncUser it tells me:

> Couldn't save the new organisation, are you sure that the uuid is in the correct format?.

I am not even entering a UUID.

I it possible that #3202 is related to that? Maybe just the webinterface is not updated correctly?

**Comment by makakin** [comment]
I have the same issue [#3204](https://github.com/MISP/MISP/issues/3204)

**Comment by iglocska** [comment]
Could you get the latest version and try again? It should be fixed.

**Comment by makakin** [comment]
Updated the latest version fix the problem! Thanks a lot!

**Comment by iglocska** [comment]
Great news, let us know if you run into any other issues!
