### ISSUE TITLE
Extending an event does not fill in the "Extends" field

### ISSUE THREAD

**Issue by WaryWolf** [MISP/MISP#3211]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Ubuntu 17.10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.90, 47df2d5c61e5a86920051297fd4d74df8b18304f
| Browser                   | Firefox 59

### Expected behavior

After editing an event to add an "Extends Event" value, The browser redirects back to the event, with the "Extends" field referring to the parent event.

### Actual behavior

After editing an event to add an "Extends Event" value, The browser redirects back to the event, but the "Extends" field is empty.

### Steps to reproduce the behavior

1. Either add a new event, or edit an existing event
2. On the information page, insert the UUID of the proposed event to extend from
3. Click Submit
4. The page should be redirected back to the event, where the extends field is blank

### Notes

This issue is occurring on our production instance, but not on our testing/sandbox instance. Both instances are running the same version of MISP, same operating system and general setup. The development instance was installed more recently and has been upgraded fewer times, and this may have created some inconsistencies between the two instances.

I have checked the following:

1. MISP error log.
2. HTTP traffic sent via browser developer console.
3. Updating both instances to the latest git commit (as of yesterday).
4. Comparing SQL schemas and permissions between the two instances and fixing inconsistencies - some indexes and fields were missing but the issue was not fixed by remediating this.
5. Sniffing SQL traffic via tcpdump and pt-query-digest - This gives the biggest clue so far - see below
6. Enabling debug mode on the sandbox instance - our production instance is accessible via external members so enabling debug mode is not an option without a service outage.
7. Reading through the source code. I'm not overly familiar with cakephp, though, so this is a slow process for me and I haven't turned on a debugger yet in order to trace the codepath being used.

### Logs, screenshots, configuration dump, ...

On the sandbox instance, the following SQL statements take place during the event update. On the production instance, there are no equivalent SQL statements in the logs.

UPDATE `misp_dev`.`events` SET `date` = '2018-04-23', `info` = 'REDACTED', `published` = '0', `analysis` = 2, `timestamp` = 1525231820, `distribution` = 3, `sharing_group_id` = 0, `threat_level_id` = 2, `extends_uuid` = '5ae832b7-a710-4b9b-883a-4c4202de0b81'  WHERE `misp_dev`.`events`.`id` = '21218';

INSERT INTO `misp_dev`.`logs` (`model_id`, `description`, `action`, `change`, `title`, `model`, `user_id`, `email`, `org`, `created`) VALUES (21218, 'Event (21218) updated by User \"anthony@REDACTED\" (7).', 'edit', 'extends_uuid () => (5ae832b7-a710-4b9b-883a-4c4202de0b81)', 'REDACTED', 'Event', 7, 'anthony@REDACTED', 'REDACTED', '2018-05-02 13:30:20');

In my opinion this indicates that there is some logic inside of MISP that is deciding not to push the update.

If you have any advice or steps that I can take to narrow down this issue, please let me know. I can try using xdebug to trace the code but hopefully there is a simpler or quicker solution.

**Comment by iglocska** [comment]
Could you go to the diagnostic page in the server settings and click on
clean model cache and see if the issue persists?

**Comment by WaryWolf** [comment]
That solved the issue, completely, thanks @iglocska ! I'll have to remember that option in the future.

Closing this issue now.

**Comment by WaryWolf** [comment]
That solved the issue, completely, thanks @iglocska ! I'll have to remember that option in the future.

Closing this issue now.

**Comment by iglocska** [comment]
Perfect, thanks for letting us know!
