### ISSUE TITLE
Question about generating the STIX file

### ISSUE THREAD

**Issue by cathy927** [MISP/MISP#3219]
Hi,

When I try to download one event, the related events are shown in MISP format but not in STIX format.

What should I do if I need the related events information in the STIX file?

Thank you!

**Comment by SteveClement** [comment]
You could do "Download as":

Select the event and on the left hand side you will see this:

![Download as in event view](https://user-images.githubusercontent.com/362025/40159425-9007201a-59a9-11e8-9df8-36a9ffea89b6.jpg)

Then chose your format:

![Download as](https://user-images.githubusercontent.com/362025/40159427-9044a4d0-59a9-11e8-839b-5de2697afc48.jpg)

Hope this helps.

Steve
