### ISSUE TITLE
Grabbing feeds via scheduled task stops at 50% and produces no error

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#3220]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.90

### Expected behavior
Scheduled task for fetching feeds completes or produces error logs if it fails.

### Actual behavior
Scheduled task stops at 50%, produces no error logs (in web ui and `app/tmp/logs`), event generated has about half of the expected attribute count.

### Steps to reproduce the behavior
Use the scheduled job `fetch_feeds` with urlhaus feed enabled.

### Logs, screenshots, configuration dump, ..
![screen](https://user-images.githubusercontent.com/2846609/39615772-3c533070-4f78-11e8-9352-0480d1e16271.png)

**Comment by SteveClement** [comment]
@3c7 is this still an issue with the latest release?

**Comment by 3c7** [comment]
Will check and report back this week.

**Comment by 3c7** [comment]
@SteveClement Yes, todays feed fetch still stopped at 50% on v. 2.4.93. No info beside added attributes and published event in the logs.

Edit: nothing in the resque log, too.

**Comment by iglocska** [comment]
How much memory do you give php?

**Comment by SteveClement** [comment]
This will be difficult to debug but let's give it a try :)

Let me first double check on my side what the expect behaviour is and how to tickle the logs.

**Comment by 3c7** [comment]
@iglocska 4G

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
