### ISSUE TITLE
howto create PyMISP.new_event with orgc_id set

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3224]
i'm trying to create a new event with PyMISP.new_event() and setting org_id=2 and orgc_id=21 (both valid). the event gets created, but the event is set with both orgc_id and org_id at 2.

what's the trick to this? thx...

**Comment by iglocska** [comment]
MISP will not allow you to override the orgc_id unless you are  a sync user and will never allow you to override the org_id. The one from the API key's account is always used.

**Comment by github-germ** [comment]
thanks for the swift reply. i will try a sync user.
are these type of details documented anywhere (or do we have to browse the code)?

**Comment by github-germ** [comment]
i changed the user to a 'sync user' and still orgc_id is not being set as called in new_event(). what am i missing? THANKS.

**Comment by github-germ** [comment]
hoping to get further insight into this. thanks...

**Comment by github-germ** [comment]
still looking for help overriding orgc_id. thx.

**Comment by SteveClement** [comment]
Are you sure you set the correct orgc_id?

Can you provide debug output.

For your reference:

*orgc_id*
orgc_id represents a human-readable identifier referencing an Orgc object of the organisation which created the event.

The orgc_id and Org object MUST be preserved for any updates or transfer of the same event.

orgc_id is represented as a JSON string. orgc_id MUST be present.

Source: https://github.com/MISP/misp-rfc/blob/master/misp-core-format/raw.md

**Comment by github-germ** [comment]
PLEASE re-open this issue. I just didn't have time to get back to it until now. Thanks!!

We are running MISP `2.4.91` + `deadlockfix` branch; pymisp `2.4.90`.

Here is my test case. Let me know what I might be doing incorrectly as even though the new event is requested with `orgc_id=2` and `org_id=21`, the resulting event sets both to `21`.

Excerpt from test script with the call to `PyMISP.new_event`:
```
    57     start = timer()
    58     sys.stdout.write('call new_event()\n')
    59     event = misp.new_event(
    60         distribution     = 0,        # our org only
    61         threat_level_id  = 2,        # medium
    62         analysis         = 0,        # initial
    63         info             = 'testing new_event mbg',
    64         date             = None,
    65         published        = False,
    66         orgc_id          = 21,       # iSIGHT
    67         org_id           = 2,        # TIARE
    68         sharing_group_id = None)
    69
    70     sys.stdout.write('new_event() returned (secs=%.1f): %s\n'
    71                      % (timer()-start, str(event)))
```

This is the output showing both `orgs` set to `21`:
```
call new_event()
new_event() returned (secs=0.1): {'Event': {'id': '11582', 'orgc_id': '21', 'org_id': '21', 'date': '2018-05-31', 'threat_level_id': '2', 'info': 'testing new_event mbg', 'published': False, 'uuid': '5b105354-74f8-416e-b8c4-2be5496a006a', 'attribute_count': '0', 'analysis': '0', 'timestamp': '1527796564', 'distribution': '0', 'proposal_email_lock': False, 'locked': False, 'publish_timestamp': '0', 'sharing_group_id': '0', 'disable_correlation': False, 'extends_uuid': '', 'Org': {'id': '21', 'name': 'iSIGHT', 'uuid': '5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Orgc': {'id': '21', 'name': 'iSIGHT', 'uuid': '5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Attribute': [], 'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [], 'Object': []}}
```

This are the two `orgs`:
```
MariaDB [misp]> select id,name from organisations where id in (2,21);
+----+--------+
| id | name   |
+----+--------+
|  2 | TIARE  |
| 21 | iSIGHT |
+----+--------+
```

Btw, no output when executing my test script in `/var/www/MISP/app/tmp/logs/` `error.log` nor `debug.log`

**Comment by Rafiot** [comment]
Yes, as @iglocska said (https://github.com/MISP/MISP/issues/3224#issuecomment-386706072), MISP **never** let you set the `org_id`. The sync user trick only works for `orgc_id`.

**Comment by github-germ** [comment]
Yes, the user in `org` `21`,  creating this new event is a `sync user` and I've tried setting either `orgc_id` or `org_id` as code above to `2` and it always is set to `21`.

What am I missing. Thanks!!

**Comment by Rafiot** [comment]
You cannot overwrite `org_id`. The only way to go is to create as a user in org 2 (setting `org_id` to 2), and force the `orgc_id` to 21.

**Comment by github-germ** [comment]
I must be missing something. I've tried `PyMISP.new_event()` passing `orgc_id=21, org_id=2` and also `orgc_id=2, org_id=21` (I think from https://github.com/MISP/MISP/issues/3224#issuecomment-393887057 this is the one that should work -- 2 and 21 are reversed as that's the way it is in my setup) and in both cases the created event has `orgc_id=21, org_id=21`.

here's the config:
```
two orgs: 2, 21
user creating the event is in org 21 which has this role:
  Permission level Manage and Publish Organisation Events
   Delegate=Yes,Sync=Yes,Admin=No,Audit=No,Auth=Yes,Site Admin=No,
   Regexp Access=No,Tagger=Yes,Template=No,Sharing Group=Yes,
   Tag Editor=Yes,Sighting=Yes,Object Template=No
```

**Comment by Rafiot** [comment]
In which organisation is the user/key you're using?

**Comment by github-germ** [comment]
`user creating the event is in org 21`

**Comment by Rafiot** [comment]
Well then the answer is still https://github.com/MISP/MISP/issues/3224#issuecomment-393887057, because of what @iglocska said here: https://github.com/MISP/MISP/issues/3224#issuecomment-386706072

**Comment by github-germ** [comment]
He wrote:
`MISP will not allow you to override the orgc_id unless you are a sync user`
So I'm confused. this user in org 21 is a sync user role, `Sync=Yes` and it's trying to override `orgc_id`.

**Comment by iglocska** [comment]
That is indeed correct, but I was wrong about it being as simple as setting the orgc_id. Basically this feature is there for sync users to be able to push events on behalf of others when synchronising, but you can indeed replicate the functionality with a sync user - however the format is a bit trickier. You need to push the actual Orgc object along with the event, so something like this would work:

```
{
  "info": "foo",
  "Orgc": {
    "name": "TIARE",
    "uuid": "11111111-1111-1111-1111-111111111111"
  }
}
```

**Comment by github-germ** [comment]
OK, almost there. I ran this script: 
[issue3224.zip](https://github.com/MISP/MISP/files/2085722/issue3224.zip)
and the output looks right (as below). However, the WebUI still shows both `Org` and `Org Owner` as 21.
```
$ python3 ./issue3224.py
python3 ./issue3224.py | fold -s -w 60
new_event:
  {'id': '12149', 'orgc_id': '21', 'org_id': '21', 'date':
'2018-06-08', 'threat_level_id': '2', 'info': 'germ test
trac 10912', 'published': False, 'uuid':
'5b1ad52c-6fb4-4fb0-b786-277e496a006a', 'attribute_count':
'0', 'analysis': '0', 'timestamp': '1528485164',
'distribution': '0', 'proposal_email_lock': False,
'locked': False, 'publish_timestamp': '0',
'sharing_group_id': '0', 'disable_correlation': False,
'extends_uuid': '', 'Org': {'id': '21', 'name': 'iSIGHT',
'uuid': '5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Orgc':
{'id': '21', 'name': 'iSIGHT', 'uuid':
'5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Attribute': [],
'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [],
'Object': []}

requesting BEFORE update_event:
  {'id': '12149', 'orgc_id': 2, 'org_id': '21', 'date':
'2018-06-08', 'threat_level_id': '2', 'info': 'germ test
trac 10912', 'published': False, 'uuid':
'5b1ad52c-6fb4-4fb0-b786-277e496a006a', 'attribute_count':
'0', 'analysis': '0', 'timestamp': '1528485164',
'distribution': '0', 'proposal_email_lock': False,
'locked': False, 'publish_timestamp': '0',
'sharing_group_id': '0', 'disable_correlation': False,
'extends_uuid': '', 'Org': {'id': '21', 'name': 'iSIGHT',
'uuid': '5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Orgc':
{'id': 2, 'name': 'TIARE', 'uuid':
'5a6a4161-b2e0-46b6-b12e-1bca0a6b037c'}, 'Attribute': [],
'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [],
'Object': []}

changed to AFTER update_event:
  {'id': '12149', 'orgc_id': 2, 'org_id': '21', 'date':
'2018-06-08', 'threat_level_id': '2', 'info': 'germ test
trac 10912', 'published': False, 'uuid':
'5b1ad52c-6fb4-4fb0-b786-277e496a006a', 'attribute_count':
'0', 'analysis': '0', 'timestamp': '1528485164',
'distribution': '0', 'proposal_email_lock': False,
'locked': False, 'publish_timestamp': '0',
'sharing_group_id': '0', 'disable_correlation': False,
'extends_uuid': '', 'Org': {'id': '21', 'name': 'iSIGHT',
'uuid': '5aec9d46-e47c-49f2-aace-06480a670c7f'}, 'Orgc':
{'id': 2, 'name': 'TIARE', 'uuid':
'5a6a4161-b2e0-46b6-b12e-1bca0a6b037c'}, 'Attribute': [],
'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [],
'Object': []}
```

**Comment by iglocska** [comment]
But that's an update. You can never change the orgc / org of an existing event, that gets locked when the event is created. You could create a new event with a spoofed orgc.

**Comment by github-germ** [comment]
ok, so how do i do that with `new_event()` since it appears to only take `orgc_id` as input. (excuse me as I am still a newbie)

**Comment by iglocska** [comment]
I am not sure, PyMISP related questions are for the master of all things PyMISP, @Rafiot :)

**Comment by github-germ** [comment]
then wait we will for the guru to shed more light. thanks!

**Comment by github-germ** [comment]
@Rafiot -- would like to revisit this issue when you get a chance. Thx.

**Comment by Rafiot** [comment]
Right now, there is no easy way to do it unless you manually add keys/values to the JSON output. 

I'm creating an other issue for that particular issue, because it will require more work.

**Comment by github-germ** [comment]
OK, I will wait until this feature is available. Thanks for working on it. I'll be happy to test on this side when you want.
