### ISSUE TITLE
Search Attributes - Possible regression (?)

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#3227]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.0
| MISP version / git hash   | 2.4.90, 329e41d0d764142f704d8f3f3bf58ebdf071c21a

Note: I don't know for sure if the issue came with the last update or if something is broken on my side.

### Expected behavior
Searching for a string contained in the value of an attribute should give you as result all the attributes containing that string

### Actual behavior
When searching for a string 0 results are found.

### Steps to reproduce the behavior
Searching for an IP that is known to be present in an Event :
![image](https://user-images.githubusercontent.com/1312794/39663061-3b985952-5064-11e8-8d80-ab559a780811.png)
will provide you the expected result:
![image](https://user-images.githubusercontent.com/1312794/39663065-5488ea8a-5064-11e8-83e7-cc463fb11568.png)

But, here ( 2.4.90 ) searching for a subset of this IP:
![image](https://user-images.githubusercontent.com/1312794/39663067-653e2e12-5064-11e8-9eef-b81b51075aee.png)
won't give you result (it used to work):
![image](https://user-images.githubusercontent.com/1312794/39663078-80530ae2-5064-11e8-90d1-172ac2643095.png)

The same happen for any substring of a value of an attribute.
I used to search for rc4key from documented config, or string contained in documented http inject and it was working smoothly

**Comment by adulau** [comment]
Ah I see. I was changed recently as some analysts wanted perfect match. If you want the old behaviour, just a `%` such as `31.184.192%` should do the job.

**Comment by Kafeine** [comment]
Oh ok ! Merci ! And in fact...it's explained   :S

"If you want a substring match encapsulate the lookup string between "%" characters."

**Comment by adulau** [comment]
No worries. We might need to update some other docs about it too ;-)
