### ISSUE TITLE
Login to web Interface

### ISSUE THREAD

**Issue by UET-HDCien** [MISP/MISP#3228]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

I can not login to web interface with admin@admin.test/admin. I Select all record from table users of database misp but the result is null. Please help me.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by SteveClement** [comment]
Do you use the VM?

Do you do a fresh install?

Also please properly use the Work environment template.

Re-open once you have answers to the following:

OS version (server)
OS version (client)
PHP version
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

Sincerely.

**Comment by UET-HDCien** [comment]
Yes, I have used the VM and I was successful. Thank you so much.

2018-05-17 13:34 GMT+07:00 Steve Clement <notifications@github.com>:
