### ISSUE TITLE
Install of ZeroMQ.

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#3229]
This is going to be such a basic question. How do I install/config ZeroMQ.
I know I'm missing something, but I can't seem to find the instructions on how to get it up and running.

Is it a matter of just enabling it within the MISP settings? Where are the requirements documented.

Thanks.

**Comment by mkorycinski** [comment]
I would like to ask for the answer as well. In my case in the diagnostic section I see 

> ZeroMQ settings…Python ZeroMQ library not installed correctly.

**Comment by SteveClement** [comment]
@jezkerwin sorry for not having gotten back in due time.
Is this still an issue for you?

A good place is always our: Gitter https://gitter.im/MISP/MISP

Please re-open if still a concern.
