### ISSUE TITLE
PyMISP.delete_event() and WebUI delete yield 'An Internal Error Has Occurred.'

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3230]
running 2.4.88. when i attempt PyMISP.delete_event() it returns an error dict, e.g.

{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/3843', 'errors': [{'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/3843'}]}

after that the client code can no longer talk with the server -- strace shows it hanging on a read.

on the webui for same event id, get internal error displayed.

(1) what's the cause and what can be done to delete these type of events?
(2) what's the proper reaction in python to this error to continue to talk to the server?

thanks!!

**Comment by iglocska** [comment]
Could you update to the latest version and see if it persists?
Also, could you check your error log what the exception's stack trace is? (/var/www/MISP/app/tmp/logs/error.log)

**Comment by github-germ** [comment]
retesting now on 2.4.90 -- still fails

```
-> d = misp.delete_event(eid)
(Pdb) print(eid)
3843
(Pdb) n
CRITICAL [api.py:215 - _check_response() ] Something bad happened on the server-side: {'name': 'An Internal Error Has Occurred.', 'message': 'An Internal Error Has Occurred.', 'url': '/events/3843'}
> /home/xxx/src/misp/test/mispDeleteIsightReportIdDups.py(96)<module>()
-> if 'errors' in d.keys():
(Pdb) ev = misp.get_event(3843)
(Pdb) print(json.dumps(ev, indent=2))
{
  "Event": {
    "id": "3843",
    "orgc_id": "21",
    "org_id": "21",
    "date": "2018-05-04",
    "threat_level_id": "2",
    "info": "KWAMPIRS Malware Profile 'PySight' 18-00007311",
    "published": false,
    "uuid": "5aecec55-1980-42a3-a8bf-0e29496a006a",
    "attribute_count": "1",
    "analysis": "0",
    "timestamp": "1525476437",
    "distribution": "0",
    "proposal_email_lock": false,
    "locked": false,
    "publish_timestamp": "0",
    "sharing_group_id": "0",
    "disable_correlation": false,
    "extends_uuid": "",
    "Org": {
      "id": "21",
      "name": "iSIGHT",
      "uuid": "5aec9d46-e47c-49f2-aace-06480a670c7f"
    },
    "Orgc": {
      "id": "21",
      "name": "iSIGHT",
      "uuid": "5aec9d46-e47c-49f2-aace-06480a670c7f"
    },
    "Attribute": [],
    "ShadowAttribute": [],
    "RelatedEvent": [],
    "Galaxy": [],
    "Object": []
  }
}
(Pdb) 
```

excerpt from error.log

```
2018-05-11 11:47:26 Error: [InternalErrorException] Delete of event file directory failed. Please report to administrator.
Request URL: /events/3843
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Event->beforeDelete(false)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2694): CakeEventManager->dispatch(Object(CakeEvent))
#2 /var/www/MISP/app/Model/Event.php(1256): Model->delete('3843', false)
#3 /var/www/MISP/app/Controller/EventsController.php(1817): Event->quickDelete(Array)
#4 [internal function]: EventsController->delete('3843')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by iglocska** [comment]
Sounds like a permission issue with the local attachment store in MISP?

**Comment by github-germ** [comment]
what should i look for?

**Comment by iglocska** [comment]
/var/www/MISP/app/files -> make sure everything is read/write/execute to the apache user, it's just a hunch, but have a feeling that that's the issue here ;)

**Comment by github-germ** [comment]
well, there were some that were not apache rwx, so i did

```
<root>: chmod -R +rwx /var/www/MISP/app/files/
<root>: chgrp -R apache /var/www/MISP/app/files/
<root>: 
```

no change :-( same error

**Comment by SteveClement** [comment]
As per install document, where www-data is whatever User/Group pair you use on your server.

sudo chown -R www-data:www-data /var/www/MISP
sudo chmod -R 750 /var/www/MISP
sudo chmod -R g+ws /var/www/MISP/app/tmp
sudo chmod -R g+ws /var/www/MISP/app/files
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp

**Comment by gitnorty** [comment]
Hi Steve, for the RedHat instructions, the permissions weren't the same as you mentioned:

https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt

+----------------------------+
|   5/ Set file permissions  |
+----------------------------+

5.01/ Make sure the permissions are set correctly using the following commands as root:
chown -R root:apache /var/www/MISP
find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP
chown apache:apache /var/www/MISP/app/files
chown apache:apache /var/www/MISP/app/files/terms
chown apache:apache /var/www/MISP/app/files/scripts/tmp
chown apache:apache /var/www/MISP/app/Plugin/CakeResque/tmp
chown -R apache:apache /var/www/MISP/app/tmp
chown -R apache:apache /var/www/MISP/app/webroot/img/orgs
chown -R apache:apache /var/www/MISP/app/webroot/img/custom

So which are correct?

**Comment by SteveClement** [comment]
The ones you pasted are correct. By now I guess all of this is fine.
