### ISSUE TITLE
howto: with PyMISP best method to get event that has a specific attribute

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3231]
PyMISP newbie question ...

if i have the value, which is a URL, of a category='Internal reference', type='link' attribute, how can i see if there is an event with that and get the event_id?

i believe below will get the event_id, but i am wondering if there is a more efficient method via the API (i.e. search_all() seems to be performance expensive):

`
PyMISP.search_all(url_str)['response'][0]['Event']['id']
`

**Comment by github-germ** [comment]
ah, this works. is this the most efficient method?

`
PyMISP.search(values=url_str, controller='attributes', type_attribute='link', to_ids=False)['response']['Attribute'][0]['event_id']
`

and can i assume that there can actually be more than one match in the 'Attribute' list?

**Comment by SteveClement** [comment]
Dear @github-germ 

This is certainly the way to go. Bare in mind the pyMISP API is under constant improvement and better ways are bound to be developed.


If you have more support questions please feel free to join Gitter: https://gitter.im/MISP/MISP

Sincerely,

Steve
