### ISSUE TITLE
Bug: adding attribute via AJAX then deleting it directly

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#324]
When i add an attribute via AJAX and then i delete it, the screen goes black without the pop-up asking to validate if I want to delete attribute "#X".
Just in case it is browser specific, I am running Chrome 38.0.2125.122

Steps to reproduce:
1. Open an event where you can insert attributes.
2. Add an attribute using AJAX.
3. Try to delete the attribute after the message popping up says that the attribute is added correctly.

**Comment by elhoim** [comment]
Looks solved on two instances I tested, closing

**Comment by iglocska** [comment]
Yup this should be solved indeed, thanks for looking into all of the older tickets!
