### ISSUE TITLE
/attributes/restSearch/json/ Broken

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#3241]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Curl
| PHP version               | PHP 7.0
| MISP version / git hash   | 2.4.90, f52fbf54d17080036927c36d68882a56e547fbbf
| Browser                   | curl

### Expected behavior
JSON Output data of the searched data

### Actual behavior
`{"name":"The request has been black-holed","message":"The request has been black-holed","url":"\/attributes\/restSearch\/json\/"}`

**In the error log the blow trace**
`2018-05-09 10:24:00 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/restSearch/json/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(AttributesController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))`

### Steps to reproduce the behavior
curl -i -H "Authorization: <REDACTED>" -H "Content-type: application/json" -H "Accept: application/json" -d '{"timestamp":1525851889,"to_ids":"true","enforceWrninglist":"true"}' -X POST https://misp.REDACTED.net/attributes/restSearch/json/

**Comment by iglocska** [comment]
Should be fixed now, thanks!
