### ISSUE TITLE
Attribute Filters in Event View malfunctioning

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#3247]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16
| PHP version               | 7.0
| MISP version / git hash   | v2.4.91
| Browser                   | If applicable

### Expected behavior
Filter attributes based on type

### Actual behavior
Shows no attributes if anything other than All is selected

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/20773170/39932642-b40efe14-550e-11e8-9f19-a7b1a34834a5.png)

![image](https://user-images.githubusercontent.com/20773170/39932660-bd94a650-550e-11e8-9d1f-54e65d12fd01.png)

**Comment by syloktools** [comment]
Any updates on this one?

**Comment by dawid-czarnecki** [comment]
Same for me. MISP v2.4.91, RedHat 7.4, php 7.1.14

**Comment by iglocska** [comment]
Should be fixed now, thanks.
