### ISSUE TITLE
Unable to export file using API

### ISSUE THREAD

**Issue by zacharycheng** [MISP/MISP#3248]
I want to export some event into stix format, but this is what I got when using API

`<?xml version="1.0" encoding="UTF-8"?>
<response><name>An Internal Error Has Occurred.</name><message>An Internal Error Has Occurred.</message><url>/events/stix/download</url></response>`

Here is the command I use to export:

`curl --header "Authorization:<API_key>" --header "Accept: application/xml" --header "Content-Type: application/xml" https://<MISP_url>/events/stix/download`

OS version | Ubuntu 16.04.4
PHP version | 7.0.28-0ubuntu0.16.04.1
MISP version / git hash | v2.4.90
Browser | curl, Chrome

What should I do?

**Comment by SteveClement** [comment]
@zacharycheng can you please check the logs?

If anything goes wrong, make sure that you check MISP's logs for errors:
$PATH_TO_MISP/app/tmp/logs/error.log

(and other log files there)

**Comment by zacharycheng** [comment]
Here are what I got in the error.log when I encountered the above message

`2018-07-23 16:05:31 Error: [Exception]
Request URL: /events/stix/download
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}`

**Comment by SteveClement** [comment]
This should be fixed... Sorry for the delay :(

Feel free to re-open with updated content.
