### ISSUE TITLE
MISP not load the IoC from Feed - Certificate Error

### ISSUE THREAD

**Issue by rmeghnagi** [MISP/MISP#3249]
Hi guys,

i've trying to fetch the IoC from a Feed (Simple CSV Feed) that was created by me on my lab through Minemeld. I receive this error when I try to fetch the IoC from Feed:

stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://192.168.180.130:443 (Unknown error)

How is possible to set "verifyssl false" on MISP Feed side?

Whitout HTTPS, MISP load correctly the IoC.

@adulau Can you help me?

Regards,
R.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question, support
| OS version (server)       | ubuntu,
| OS version (client)       | Ubuntu
| MISP version / git hash   | 2.4.81
| Browser                   | Internet Explorer, Chrome

### Logs, screenshots, configuration dump, ...

stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://192.168.180.130:443 (Unknown error)

**Comment by iglocska** [comment]
Interesting issue, let me think of some clean solution for this!

**Comment by rmeghnagi** [comment]
Thank you!!

Le me know please.
Regards,
R.

**Comment by rmeghnagi** [comment]
Dear @iglocska ,

do you have any news?

I setting up the HTTPS on my Feed with a Public CA but i've the same error...

How can I add the Godaddy CA to be recognized by MISP?

I've this issue on Customer Production environment.
Waiting for your feedback.
Regards,
R.

**Comment by rmeghnagi** [comment]
Hi all,

i resolved the issue.

The workaround applied to bypass the cert validation is there:

on this file /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php
set **'ssl_verify_peer' => false** 

Then, restart apache2 and workers:
1. service apache2 restart
2. sudo su -l www-data -s /bin/bash "/var/www/MISP/app/Console/worker/start.sh" 

Thank you for your support.
Regards
Rafy

**Comment by adulau** [comment]
@JakubOnderka do you think we could have an option per feed to bypass certificate validation if required?
