### ISSUE TITLE
attribute deletion fails when regexp matches attribute

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3251]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 

### Expected behavior
- removal of the attribute results in a shadowattribute

### Actual behavior
- removal fails

### Steps to reproduce the behavior
- add attribute
- add an import regexp matching this attribute (replace to nothing)  (this prevents future attributes to be created)
- remove the existing attribute
- removal fails

**Comment by SteveClement** [comment]
Confirmed second step, this needs to yield a better error, issue #3451

The removal does not fail anymore on my side.

Please re-open if this still fails.
