### ISSUE TITLE
Cannot fetch all the feeds by PyMISP or Automation

### ISSUE THREAD

**Issue by cathy927** [MISP/MISP#3256]
When I try 

python3 fetch_events_feed.py -f all           
in PyMISP/examples

or

MISP/app/Console/cake Server fetchFeed 1 all

the Job is completed like

![image](https://user-images.githubusercontent.com/23722191/40171032-c13926da-59fc-11e8-8b03-1e32363a95bd.png)

But nothing happens to the event list.

How can I fetch all the feeds using  PyMISP or Automation?

Thank you!

**Comment by SteveClement** [comment]
Dear @cathy927 as this is a little older issue, can you please update to latest MISP/PyMISP and try again?

If it still fails, please check the Audit Logs and see if you see some "movement" there.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
