### ISSUE TITLE
should 'MISP4' be 'MISP' in a  path for file_put_contents() in app/Console/Command/EventShell.php

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3257]
2.4.90

i am seeing an error from this line referring to `MISP4` within the path to `file_put_content()`

```
2018-05-17 18:48:20 Warning: file_put_contents(/var/www/MISP4/app/tmp/test): failed to open stream: Is a directory in [/var/www/MISP/app/Console/Command/EventShell.php, line 483]
```
should `MISP4` be `MISP`?

see https://github.com/MISP/MISP/blob/fd24429e715db98b5dfdd56c6692845f8549ac04/app/Console/Command/EventShell.php#L483

**Comment by adulau** [comment]
Good catch! It seems to be a left-over of debugging. @iglocska what do you think? ;-)

**Comment by github-germ** [comment]
ok, that's what i figured (-:
i'll fix locally in my instance.
i assume we can just remove the whole line as it was just a way to see if that code was called?
