### ISSUE TITLE
[QUESTION] Move to remote MySql database on GCP?

### ISSUE THREAD

**Issue by thormanrd** [MISP/MISP#3263]
Does anyone have experience moving the database configuration to a remote MySQL server?  I have a running instance of mariaDB on localhost but would like to move to a remote server on Google Cloud Platform.  

I have a MySQL instance running in GCP with the misp database created and initialized from the INSTALL/MYSQL.sql script.  I know how to move my current data to this new instance as well.  What I'm trying to figure out, is what config/scripts do I need to adjust to point my existing MISP server to this new MySQL server?

Any help and guidance is appreciated.

**Comment by thormanrd** [comment]
Looks like I will just have to change the /var/www/MISP/app/Config/database.php script to point to my GCP MySQL server...

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => '<my-gcp-server>',
		'login' => 'misp', // grant usage on *.* to misp@my-gcp-server
		'port' => 3306,
		'password' => '*********', // identified by 'XXXXdbpasswordhereXXXXX';
		'database' => 'misp', // create database misp;
		'prefix' => '',
		'encoding' => 'utf8',
		
	);
}

**Comment by SteveClement** [comment]
Yes, that is correct. You want to be sure that the connection is secured though.
Bare in mind that a misp instance has nearly always sensitive data and you want to protect the data.
Also, in some countries you are obliged by law to protect the data and a plain text connection might get you into troubles.

**Comment by thormanrd** [comment]
Where and how do I enable SSL connection to my remote db server?

**Comment by thormanrd** [comment]
Looks like I just set 'ssl_key', 'ssl_cert', and 'ssl_ca' in the database.php $default array.
