### ISSUE TITLE
MISP, synchronisation between minor versions 

### ISSUE THREAD

**Issue by dsever** [MISP/MISP#3265]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support...
| OS version (server)       | CentOS
| OS version (client)       | Windows 10
| PHP version               | 7.0.29
| MISP version / git hash   | 2.4.89, hash of the commit

Hi, 
we are trying to establish synchronisation between two misp instances, and only want to use pull from upstream server. We are getting Remote outdated version. Out local installation is 2.4.89 and remote version is 2.4.54, as far I understand in case of minor version differences It should be possible to make synchronisation.  

![misp](https://user-images.githubusercontent.com/7211879/40304008-4f4464a8-5cf5-11e8-848c-876b2559c7a7.png)

p.s We don't have control over the remote instance.

**Comment by adulau** [comment]
Pulling will work and you'll get what your version supports.

But, having such old version is obviously not recommended (especially security wise). Updating MISP is really easy as you usually just need to `git pull` and login one time. We strongly recommend to update and always have the latest version.
