### ISSUE TITLE
Double click settings don't work...

### ISSUE THREAD

**Issue by elk2** [MISP/MISP#3266]
I downloaded last version of MISP from https://www.circl.lu/misp-images/latest/
( MISP_v2.4.91@32b6ce70089313e5972be2707e520264755ae940-vmware.zip )

Double click seems don't work in Server Settings & Maintenance..
I tried with different browser and I have stopped and restarted the virtual machine but without success.

I work behind proxy and I would like to set proxy settings

**Comment by iglocska** [comment]
It's probably a baseurl issue. Could you set the baseurl on the instance correctly? There's a command line tool to do it:

```
/var/www/MISP/app/Console/cake Baseurl https://base.url.of.my.instance
```

**Comment by elk2** [comment]
Yes it's it. Thanks!

**Comment by iglocska** [comment]
Excellent, thanks for the feedback. I also added the command to the
automation page, so should be easier to find it in the future as it was
pretty obscure.
