### ISSUE TITLE
Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.

### ISSUE THREAD

**Issue by thormanrd** [MISP/MISP#3270]
I moved the database to a remote server and configured database.php as follows, where xx.xx.xx.xx is the actual IP of my remove MySQL server on GCP:

	public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'xx.xx.xx.xx',
		'login' => 'misp',
		'port' => 3306,
		'password' => '********',
		'database' => 'misp',
		'ssl_key' => '/ect/ssl/private/mykey.pem',
		'ssl_cert' => '/etc/ssl/private/mycert.pem',
		'ssl_ca' => '/etc/ssl/private/myca.pem',
		'prefix' => '',
		'encoding' => 'utf8',
	);

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, support...
| OS version (server)       | Debian
| OS version (client)       | Mac OS X El Capitan
| PHP version               | 7.0
| MISP version / git hash   | 2.4.88
| Browser                   | FF

### Expected behavior
When I use mysql client I can connect to my remote server just fine.  I imported all the MISP tables and data successfully:

mysql -h xx.xx.xx.xx -u "misp" -p --ssl-ca=/etc/ssl/private/myca.pem --ssl-cert=/etc/ssl/private/mycert.pem --ssl-key=/etc/ssl/private/mykey.pem --ssl misp
Enter password: 

MySQL [misp]> show tables;
+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| admin_settings                |
| attribute_tags                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_blacklists              |
| event_delegations             |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| fuzzy_correlate_ssdeep        |
| galaxies                      |
| galaxy_clusters               |
| galaxy_elements               |
| galaxy_reference              |
| jobs                          |
| logs                          |
| news                          |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| org_blacklists                |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightings                     |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| whitelist                     |
+-------------------------------+
55 rows in set (0.00 sec)

MySQL [misp]> 

### Actual behavior

When I browse to the web page I get a 'internal error' page.  And the following exception in the tmp/logs/error.log file:

2018-05-21 23:44:51 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] ',
  'enabled' => true,
)
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/UsersController.php(29): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): UsersController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

### Steps to reproduce the behavior
Modified database.php as shown above.
Browse to URL.

### Logs, screenshots, configuration dump, ...
![screen shot 2018-05-22 at 3 20 14 pm](https://user-images.githubusercontent.com/7852536/40387924-b2cae00e-5dd3-11e8-93bf-7a89621cdd9d.png)

**Comment by adulau** [comment]
It seems to be your MySQL parameters are incorrect. Maybe the certificate are not accessible? or the CNAME of the certificate is not matching the host (as you specified an IP)? 
 
Maybe testing with `MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT` would help for debugging.

**Comment by thormanrd** [comment]
@adulau 

How can that be the case?  That same cert, key, ca file works with the 'mysql' command at the OS prompt.  I pasted the output of that command under "Expected Behavior" and it shows the re-dacted IP with the same files.  Works perfectly.

What I suspect is that cakePHP is not configured correctly for remote connections or apache2 is not.  I don't not have SELinux extensions so there not an httpd flag involved.  There is no OS firewall as the GCP compute engine uses an "external" firewall at the VPC level and there is no logging at the VPC firewall or the remote MySQL server showing the connection failure.  So I'm very sure its not making it past apache server.    

I will try the MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT and see what happens.

**Comment by thormanrd** [comment]
Using the MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT = false I get past the SQLSTATE[HY000] [2002] exception.  But now I'm stuck in user authorization exception below.  I did grant the misp user privilege and usage on the database.  And I can connect with the mysql command as shown above.  So how to I fix this?

2018-05-23 13:26:34 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created:
    SQLSTATE[HY000] [1045] Access denied for user 'misp'@'xx.xx.xx.xx' (using password: YES)
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'misp\'@\'xx.xx.xx.xx\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by thormanrd** [comment]
I wrote this php script and it works fine...
<?php
try {
	$db_ext = new PDO( 'mysql:host=xx.xx.xx.xx;
		port=3306; 
		dbname=misp', 
		'misp', '************',
		array(
			PDO::MYSQL_ATTR_SSL_KEY => '/path/to/client-key.pem',
			PDO::MYSQL_ATTR_SSL_CERT => '/path/to/client-cert.pem',
			PDO::MYSQL_ATTR_SSL_CA => '/path/to/server-ca.pem',
			PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
		));
	$db_ext->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	$stmt = $db_ext->query('SELECT * FROM misp.threat_levels');
	while ($row = $stmt->fetch())
	{
		echo $row['name'] . "\n";
	}
}
	catch( PDOException $e ){
	print $e->getMessage();
	die();
}
?>

when I run it with php <file> it produces the correct output...
root@misp-3:~# php my-connect.php 
High
Medium
Low
Undefined

**Comment by thormanrd** [comment]
Problem solved...

It was all about the certificate, key and server ca pem files.  I had to move them to /var/www/MISP directory and give www-data read access to them.  Then the Mysql.php could provide them to the PDO connection object.  Worked.

**Comment by adulau** [comment]
@thormanrd Thank you for the feedback. X.509 certificates can be painful sometime ;-)

**Comment by esryanoakley** [comment]
I know it's years later -- but there's a typo in your path for the SSL cert for 'etc'. This is likely why it failed
`'ssl_key' => '/ect/ssl/private/mykey.pem',`
Should be:
`'ssl_key' => '/etc/ssl/private/mykey.pem',`
