### ISSUE TITLE
MISP Web-interface not working as accepted 

### ISSUE THREAD

**Issue by naina-emmanuel** [MISP/MISP#3272]
I have deployed MISP on my server ubuntu 18.04 and followed the steps using guide from  https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1804.txt after installation when i log in to the webinterface using admin@admin.test/admin, it logged in and asked for changing pwd (I changed it) and privileges by following Administration-> server setting -> MISP -> Live. After logging in when I navigate tabs and try to do anything it gives:

```
This site can’t be reached
misp’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN
```

What can be the issue? 
#3268

**Comment by iglocska** [comment]
Sounds like your Baseurl isn't set correctly, could you run the following command?

```
MISP/app/Console/cake Baseurl [baseurl]
```

**Comment by naina-emmanuel** [comment]
It is working fine my setting baseurl field empty in `/var/www/MISP/app/Config/config.php file`.

**Comment by iglocska** [comment]
That works too (basically the console command is an overlay over that) - however, leaving it empty is not recommended when using sharing groups (basically your instance will be added without a URL, so sharing via a sharing group means people can't share back to you). If you're using it as an internal instance for research / feeding tools it's not a problem though.

**Comment by ghost** [comment]
Still it is not working. After configuring the Vbox, what should we do to access web interface?
