### ISSUE TITLE
OTX MISP integration can't connect to MISP instance

### ISSUE THREAD

**Issue by elk2** [MISP/MISP#3274]
When I use otx-misp command from MISP instance shell this is the result:
```
WARNING [abstract.py:19 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
WARNING [mispevent.py:26 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
WARNING [api.py:31 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
Connection to MISP instance: http://192.168.28.130
Error: <urlopen error [Errno -2] Name or service not known>
```
I downloaded last version of MISP from https://www.circl.lu/misp-images/latest/
( MISP_v2.4.91@32b6ce70089313e5972be2707e520264755ae940-vmware.zip )

I work behind proxy and I have this environment variable:
declare -x http_proxy="http:\\proxyelk.local:8080"
declare -x https_proxy="http:\\proxyelk.local:8080"
declare -x no_proxy="”127.0.0.1,localhost,192.168.28.130”"

**Comment by SteveClement** [comment]
Dear

Have you entered the proxy here too: http://localhost:8080/servers/serverSettings/Proxy

Also, I am not a huge proxy specialist but it seems: "http:\…" is very wrong.

**Comment by elk2** [comment]
Thanks Steve,

I solved with this environment:
declare -x http_proxy="http://proxyelk.local:8080"
declare -x https_proxy="http://proxyelk.local:8080"
declare -x no_proxy="127.0.0.1,localhost,192.168.28.130,127.0.1.1"

All otx events are uploaded on my organization events. If I close the terminal, process otx-misp stop to work. How can I maintain active otx-misp process in background?

**Comment by SteveClement** [comment]
Dear @elk2 

Depending on your use-case and criticality of this system you could simply run a "screen" or "tmux" session and detach from it.

Another more old-school method would be to use "nohup" but especially early-on for debugging screen/tmux is better.

**Comment by elk2** [comment]
Ok thanks Steve!
