### ISSUE TITLE
Event with distribution "Your organization" does not appear in zmq "misp_json"

### ISSUE THREAD

**Issue by kyr-stefanidis** [MISP/MISP#3276]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.88

### Expected behavior
event shows in the "misp_json" topic when it is published

### Actual behavior
event does not appear in the "misp_json" topic when it is published

### Steps to reproduce the behavior
subscribe to zqm "misp_json" topic
create an event
choose "your organization only" as distribution
publish event
check zmq output

###comments###
the same event will appear in zmq if the distribution is changed to not "your organization"

**Comment by adulau** [comment]
Thank you for the feedback. Could you test with 2.4.91-latest?

**Comment by adulau** [comment]
@kyr-stefanidis Did you test with the recent version?

**Comment by kyr-stefanidis** [comment]
Long overdue reply. Yes, it works on 2.4.92+

**Comment by adulau** [comment]
@kyr-stefanidis Great! Thank you for the feedback. We will close the issue.
