### ISSUE TITLE
Adding object references with many objects, view issue.

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3282]
MISP version https://github.com/MISP/MISP/commit/4e41aa940ca8394dbadff84ee222cb5ec021a4a9

### Actual behavior

When adding an object reference where a lot of objects are present, it becomes a guessing game which is the one you want to select.

![screen shot 2018-05-28 at 16 13 06](https://user-images.githubusercontent.com/362025/40600118-88182172-6293-11e8-86f6-b96f01508521.jpg)

### Expected behavior

It would be favorable to see some value that makes sense perhaps in an abbreviated form if necessary.

**Comment by mokaddem** [comment]
This is solved since the introduction of the ``generic_picker`` feature.
