### ISSUE TITLE
No events from feed

### ISSUE THREAD

**Issue by elk2** [MISP/MISP#3284]
It is possible to view all the events from default feed in my listed events? I enabled all default feed and I fetched and stored all feed but no events appear

**Comment by SteveClement** [comment]
@elk2 I am not sure what your issue might be, here is a sample of how to enable and fetch feeds. It also shows how to check for progress and whether everything is queued: https://my.mixtape.moe/fctdfv.webm

Audit / List Logs -> A good place to see if everything gets pulled.
Administration / Jobs -> Here you can see what is queued-up.

**Comment by SteveClement** [comment]
@elk2 I assume you are ok now.
Please reach out if any other relate issues arise.
