### ISSUE TITLE
Be consistent with time ranges on all time filters

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#3296]
Allow time ranges / pseudonyms via the following filters:

timestamp
publish_timestamp
date

**Comment by garanews** [comment]
Hello @iglocska any news about this? XD

**Comment by Rafiot** [comment]
It should be fixed: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L514

If you tried it, can you please give us the queries?

**Comment by iglocska** [comment]
Yeah forgot to close the issue, this should have been fixed aeons ago.

**Comment by mokaddem** [comment]
Can the issue be closed then?
