### ISSUE TITLE
STIX and Cybox libraries incorrect versions

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#3298]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 9
| OS version (client)       | Ubuntu
| PHP version               | 7.1
| MISP version / git hash   | 2.4.91 / a875d3046574cc5b1bb49553ff8dd8270b875ae9
| Browser                   | If applicable

The Cybox libraries have not been updated 

### Actual behavior
```
STIX and Cybox libraries
Mitre's STIX and Cybox python libraries have to be installed in order for MISP's STIX export to work. Make sure that you install them (as described in the MISP installation instructions) if you receive an error below.
If you run into any issues here, make sure that both STIX and CyBox are installed as described in the INSTALL.txt file. The required versions are:
STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
Other versions might work but are not tested / recommended.

STIX and Cybox libraries…OK
STIX library version…OK
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.17, expecting 2.1.0.18.dev0
MIXBOX library version…OK
```

**Comment by RichieB2B** [comment]
If you follow https://github.com/MISP/MISP/blob/2.4/INSTALL/UPDATE.txt it tells you to checkout the latest version of python-cybox and install it. You might have to "pip3 uninstall cybox" first though.

**Comment by matt-saunders** [comment]
I have been working on the [docker-misp ](https://github.com/harvard-itsecurity/docker-misp) version and I have ran into this same issue (on a clean install).  Looking at the [MISP code](https://github.com/MISP/MISP/blob/daa8d750c3a05d4888ecde9c30f594f16b531434/app/Model/Server.php) it looks like version 2.1.0.18.dev0 is expected, but according to the [python-cybox](https://github.com/CybOXProject/python-cybox/releases) release page it is still at Version 2.1.0.17.  Cloning cyboxproject repo, as described in the update link above, pulls down 2.1.0.17.  Would someone be able to inform us which version should be installed?  I'm thinking the check is looking for a version that hasn't been released yet or the latest version hasn't been made available yet when it should have.

**Comment by RichieB2B** [comment]
@matt-saunders a `git clone https://github.com/CybOXProject/python-cybox.git` does in fact pull down the latest development version:
```
$ cat cybox/version.py
# Copyright (c) 2017, The MITRE Corporation. All rights reserved.
# See LICENSE.txt for complete terms.

__version__ = "2.1.0.18.dev0"
```
Did you run `pip3 uninstall cybox` to uninstall the pip managed version?

**Comment by matt-saunders** [comment]
Well sure enough that was my issue.  Thanks for the quick response.  We are incorporating the fix in docker-misp.

**Comment by gulsoomro** [comment]
hello guys i am having some problem in mapping stix2 logs,to convert from common format logs to stix2 formate logs. Stix2 provide SDO object for attack type Malware if we occur some other type of attack like (Sip type, Brute force,db,recon) then how to map that type of logs?
