### ISSUE TITLE
Sync server fails with untrusted certificate

### ISSUE THREAD

**Issue by crondaemon** [MISP/MISP#3299]
I'm experiencing problems syncing my server with CIRCL's private instance. The problem looked like the one in #178, but the it turned out a different thing. The instance is https://misppriv.circl.lu that shows a valid certificate. 

Running the connection test from `https://misp.local/servers/index` shows 

```
server unreachable
```

Monkey patching the code solves the problem

```diff
root@misp:/var/www/MISP/app/Lib/cakephp# git diff
diff --git a/lib/Cake/Network/Http/HttpSocket.php b/lib/Cake/Network/Http/HttpSocket.php
index 1643bcb..f5dbf63 100644
--- a/lib/Cake/Network/Http/HttpSocket.php
+++ b/lib/Cake/Network/Http/HttpSocket.php
@@ -93,7 +93,7 @@ class HttpSocket extends CakeSocket {
                'protocol' => 'tcp',
                'port' => 80,
                'timeout' => 30,
-               'ssl_verify_peer' => true,
+               'ssl_verify_peer' => false,
                'ssl_allow_self_signed' => false,
                'ssl_verify_depth' => 5,
                'ssl_verify_host' => true,
```

and the test works fine

```
Local version: 2.4.91
Remote version: 2.4.91
Status: OK
Compatiblity: Compatible
POST test: Received sent package
```

Looks like the php certificate storage doesn't include the CA used by CIRCL. Any suggestion?

**Comment by IanGabes** [comment]
Hi @crondaemon, i recently ran into this problem as well. 

CakePHP uses a local copy of the mozilla CA bundle, which can be found here: https://github.com/cakephp/cakephp/blob/master/config/cacert.pem

The fix for me was to manually add in my CA into this file,  and leave the `HttpSocket` file in its original state. I assume this will also work for the CIRCL root CA too?

I also had the idea of symlinking this `ca-cert.pem` file to the system wide CA bundle i have in `/etc/ssl/certs/ca-certificates`, which also works since I had previously imported my CA here previously.

**Comment by iglocska** [comment]
The CIRCL instance's root CA should be in the default CA store of cakephp. What the hell.

**Comment by crondaemon** [comment]
Well... the solution would be pretty easy, wouldn't it? A PR with the CIRCL cert added to the keystore should solve the problem. I'm trying to do it myself and if it works, I'll make the PR.

**Comment by iglocska** [comment]
It shouldn't be needed at all. I've just retested it and it work just fine with the defaults.

**Comment by crondaemon** [comment]
It doesn't for me. Which branch are you working on? I'm on `v2.4.81-1981-gdf31ae1` and I see those lines in `app/tmp/logs/error.log`.

```
2018-06-14 14:32:09 Warning: Warning (2): stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
stream_socket_enable_crypto - [internal], line ??
CakeSocket::enableCrypto() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490
CakeSocket::connect() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 247
CakeSocket::write() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 386
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 377
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 466
Server::runConnectionTest() - APP/Model/Server.php, line 2864
ServersController::testConnection() - APP/Controller/ServersController.php, line 1278
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by iglocska** [comment]
Yikes, 81. That's like a year old almost, if you update the cert store gets updated too, I am on the 2.4 branch too but on the latest version (92).

**Comment by crondaemon** [comment]
That's what I get when I (pseudo-)automatically update MISP. Should I manually switch to 2.4.93 with `git checkout 2.4.93`?

**Comment by iglocska** [comment]
nono, always stay on the 2.4 branch. 2.4.93 branch is us working on the next release and isn't stable ;)

**Comment by SteveClement** [comment]
@crondaemon I suppose by now you updated you cert-store.
Bypassing the verification of known good Certificates is Bad(tm) some evil MITM magic might happen if you just ignore warnings.
