### ISSUE TITLE
MISP XML export produces invalid XML

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3303]
When an event contains an ATT&CK galaxy on the attribute level, exporting that event in the MISP XML format produces invalid XML.

For example (indents are mine):
```
<GalaxyCluster>
  <id>14731</id>
  <uuid>fb2242d8-1707-11e8-ab20-6fa7448c3640</uuid>
  <type>mitre-enterprise-attack-attack-pattern</type>
...
  <tag_id>1081</tag_id>
  <meta>
    <0>https://attack.mitre.org/wiki/Technique/T1041</0>
    <1>https://arxiv.org/ftp/arxiv/papers/1408/1408.1136.pdf</1>
  </meta>
  <meta>
    <0>User interface</0>
    <1>Process monitoring</1>
  </meta>
...
```
The problem is with the `<meta><0>` tag since XML tag names cannot start with a number. 
xmllint trips over this with:
```
misp.event.11438.5b0c8007-4334-4dbb-9ddf-47a0950d210f.xml:11: parser error : StartTag: invalid element name
/cti</source><authors></authors><version>3</version><tag_id>1081</tag_id><meta><
                                                                               ^
```
I did my testing with event UUID [5b0c8007-4334-4dbb-9ddf-47a0950d210f](https://misp.circl.lu/events/view/11438)

**Comment by iglocska** [comment]
MISP XML is kind of deprecated, are you guys actually using that stuff?

**Comment by RichieB2B** [comment]
We're not, but one of our constituents is. I know MISP XML is _kind of_ deprecated but they'll need a firm statement of that to justify the work they'll need to do to switch to JSON.

**Comment by iglocska** [comment]
I think the firm statement would be:

1. It is deprecated
2. We don't use/test it internally
3. If anything goes wrong we will fix reported issues though for now, so will look into fixing it.

**Comment by RichieB2B** [comment]
`<oper="thanks" comment="we appreciate it" />`

**Comment by RichieB2B** [comment]
It seems that this is not just caused by ATT&CK galaxy tags on the attribute level. Here is GalaxyCluster on an event that also has the `<0>` XML tag:
```
<GalaxyCluster>
  <id>16756</id>
  <uuid>0d821b68-9d82-4c6d-86a6-1071a9e0f79f</uuid>
  <type>tool</type>
  <value>Necurs</value>
  <tag_name>misp-galaxy:tool=&quot;Necurs&quot;</tag_name>
  <description>The Necurs botnet is a distributor of many pieces of malware, most notably Locky.</description>
  <galaxy_id>32</galaxy_id>
  <source>MISP Project</source>
  <authors></authors>
  <authors></authors>
  <authors></authors>
  <authors></authors>
  <authors></authors>
  <version>61</version>
  <tag_id>162</tag_id>
  <meta><0>https://en.wikipedia.org/wiki/Necurs_botnet</0></meta>
</GalaxyCluster>
```
which is caused by multiple meta refs in [app/files/misp-galaxy/clusters/tool.json](https://github.com/MISP/misp-galaxy/blob/master/clusters/tool.json#L1533):
```
      "meta": {
        "refs": [
          "https://en.wikipedia.org/wiki/Necurs_botnet",
          "https://www.bleepingcomputer.com/news/security/worlds-largest-spam-botnet-finds-a-new-way-to-avoid-detection-for-now/"
        ]
      },
```
Please note that the second ref to bleepingcomputer is not exported. Not in MISP XML nor in MISP JSON format. Should I open anther issue for that?

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
