### ISSUE TITLE
broken javascript - broken functionality with IE11 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3306]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| Browser                   | Internet Explorer 11

### Actual behavior
Some links / buttons / functionality does not work when Internet Explorer 11 is used:
- filter eventlist - `executeFilter is undefined`
- add object button (left menu) - `getPopup is undefined`
- populate from - `getPopup is undefined`
- ...

Investigation shows:
- JS errors appear when clicking the links
- when loading the page many JS errors are present; in event-distribution-graph.js, contextual_menu.js, action_table.js, event-graph.js, misp.js, keyboard-shortcuts.js

### Steps to reproduce the behavior
- open the developer console when loading the event index page and the event details page.

(pull-request coming soon)

**Comment by iglocska** [comment]
Woah, that is weird. Wonder why it behaves so much differently from Chrome/FF. Will try to give it a shot on a windows machine.
