### ISSUE TITLE
hard delete attributes when event was never published

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3311]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request, 

### Steps to reproduce the behavior
Today, when you remove an attribute the attribute is still there but marked as deleted.
The reason for this is to prevent issues with syncing.

There are numerous use-cases where you automate feeding data in MISP and leave the event not published to allow manual/human review.
A human will then review the data, remove bad entries (pollution or sensitive) and then publish the event.
This process requires a double removal per attribute (one soft delete, one hard delete).

This feature request is to ask for the functionality to immediately hard-delete the attribute if the event was never published. This would allow much less work for the user reviewing events (and less risk of unwanted information disclosure), while not causing issues for sync.

An event that was never published has `"published": false AND  "publish_timestamp": "0"`

thank you

**Comment by iglocska** [comment]
Good idea, thanks ;)

**Comment by cvandeplas** [comment]
Thank you for the prompt action and feedback.
There is a small discrepancy with the batch-delete functionality on the event view page that does not support this behavior yet. Would you also be able to modify this?

**Comment by iglocska** [comment]
Ah indeed, forgot about that completely.
