### ISSUE TITLE
Table 'misp.correlations' doesn't exist in engine

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#3313]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

MariaDB [misp]> describe correlations;
ERROR 1932 (42S02): Table 'misp.correlations' doesn't exist in engine

First time we have seen this. 

MariaDB [misp]> describe events;
+---------------------+------------------+------+-----+---------+----------------+
| Field               | Type             | Null | Key | Default | Extra          |
+---------------------+------------------+------+-----+---------+----------------+
| id                  | int(11)          | NO   | PRI | NULL    | auto_increment |
| org_id              | int(11)          | NO   | MUL | NULL    |                |
| date                | date             | NO   |     | NULL    |                |
| info                | text             | NO   | MUL | NULL    |                |
| user_id             | int(11)          | NO   |     | NULL    |                |
| uuid                | varchar(40)      | NO   | UNI | NULL    |                |
| published           | tinyint(1)       | NO   |     | 0       |                |
| analysis            | tinyint(4)       | NO   |     | NULL    |                |
| attribute_count     | int(11) unsigned | YES  |     | 0       |                |
| orgc_id             | int(11)          | NO   | MUL | NULL    |                |
| timestamp           | int(11)          | NO   |     | 0       |                |
| distribution        | tinyint(4)       | NO   |     | 0       |                |
| sharing_group_id    | int(11)          | NO   | MUL | NULL    |                |
| proposal_email_lock | tinyint(1)       | NO   |     | 0       |                |
| locked              | tinyint(1)       | NO   |     | 0       |                |
| threat_level_id     | int(11)          | NO   |     | NULL    |                |
| publish_timestamp   | int(11)          | NO   |     | 0       |                |
| disable_correlation | tinyint(1)       | NO   |     | 0       |                |
| extends_uuid        | varchar(40)      | YES  | MUL |         |                |
+---------------------+------------------+------+-----+---------+----------------+
19 rows in set (0.00 sec)

MariaDB [misp]> describe correlations;
ERROR 1932 (42S02): Table 'misp.correlations' doesn't exist in engine
MariaDB [misp]> describe logs;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| title       | text         | YES  |     | NULL    |                |
| created     | datetime     | NO   |     | NULL    |                |
| model       | varchar(80)  | NO   |     | NULL    |                |
| model_id    | int(11)      | NO   |     | NULL    |                |
| action      | varchar(80)  | NO   |     | NULL    |                |
| user_id     | int(11)      | NO   |     | NULL    |                |
| change      | text         | YES  |     | NULL    |                |
| email       | varchar(255) | NO   |     |         |                |
| org         | varchar(255) | NO   |     |         |                |
| description | text         | YES  |     | NULL    |                |
| ip          | varchar(45)  | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
12 rows in set (0.00 sec)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04LTS
| PHP version               |  PHP 7.0.30
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by jigsawsecurity** [comment]
Here's some additional information to assist: 
Looks like correlation table is corrupt

PDO error
SQLSTATE[HY000]: General error: 1712 Index correlations is corrupted
Error: An Internal Error Has Occurred.

Stack Trace

APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 470 → PDOStatement->execute(array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 436 → DboSource->_execute(string, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 673 → DboSource->execute(string, array, array)
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 1184 → DboSource->fetchAll(string, array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3038 → DboSource->read(AppModel, array)
APP/Lib/cakephp/lib/Cake/Model/Model.php line 3010 → Model->_readDataSource(string, array)
APP/Model/Event.php line 497 → Model->find(string, array)
APP/Controller/EventsController.php line 672 → Event->attachCorrelationCountToEvents(array, array)
[internal function] → EventsController->index()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(EventsController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by jigsawsecurity** [comment]
Temporarily disabled display correlation on the main event's page to get back working for now. Just letting you know that this was an issue.

**Comment by iglocska** [comment]
Woah, that should never happen. Did your correlations table get corrupted?

**Comment by jigsawsecurity** [comment]
Appears that way but we are trying to figure out why. It's still not resolved. Not sure how to proceed to be honest. I think the InThreat feed added an event with 55000 attributes and that's what cause the issue. The feed included in the configuration. They should really split that up into smaller events.

**Comment by jigsawsecurity** [comment]
Can you tell me how to manually remove that one event manually. I believe if I can get that event out of the database that it will resolve the issue. I had the command to do this somewhere else but can't remember where I wrote it down.

**Comment by iglocska** [comment]
To be honest I doubt it's the event. 55k is a massive event indeed, but it shouldn't cause any issues - the corruption is something on a mysql or even more scary on a hardware level. However, luckily what you seem to have lost is your correlation table - not the end of the world. You can just recreate the table with the following command:

```
DROP TABLE `correlations`;
CREATE TABLE IF NOT EXISTS `correlations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` text COLLATE utf8_bin NOT NULL,
  `1_event_id` int(11) NOT NULL,
  `1_attribute_id` int(11) NOT NULL,
  `event_id` int(11) NOT NULL,
  `attribute_id` int(11) NOT NULL,
  `org_id` int(11) NOT NULL,
  `distribution` tinyint(4) NOT NULL,
  `a_distribution` tinyint(4) NOT NULL,
  `sharing_group_id` int(11) NOT NULL,
  `a_sharing_group_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `info` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `value` (`value`(255)),
  INDEX `event_id` (`event_id`),
  INDEX `1_event_id` (`1_event_id`),
  INDEX `attribute_id` (`attribute_id`),
  INDEX `1_attribute_id` (`1_attribute_id`),
  INDEX `org_id` (`org_id`),
  INDEX `sharing_group_id` (`sharing_group_id`),
  INDEX `a_sharing_group_id` (`a_sharing_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

After that you can recorrelate the full database by navigating to:

`/pages/display/administration`

and clicking on `Recorrelate attributes`.

Also, make sure you upgrade to the latest version on HEAD, performance is massively improved as of the past few commits.

**Comment by jigsawsecurity** [comment]
That worked. Thank you sir.

**Comment by iglocska** [comment]
My pleasure!
