### ISSUE TITLE
Please, help me!)

### ISSUE THREAD

**Issue by RabbitNamedNoragami** [MISP/MISP#3317]
Hello, when I try to go to the site admin site on WordPress, I get this error. What to do?

`Fatal error: Uncaught exception 'Exception' with message 'API auth fail' in /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/vendor/lis-dev/nova-poshta-api-2/src/Delivery/NovaPoshtaApi2.php:172 Stack trace: #0 /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/vendor/lis-dev/nova-poshta-api-2/src/Delivery/NovaPoshtaApi2.php(241): LisDev\Delivery\NovaPoshtaApi2->prepare('{"success":fals...') #1 /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/vendor/lis-dev/nova-poshta-api-2/src/Delivery/NovaPoshtaApi2.php(464): LisDev\Delivery\NovaPoshtaApi2->request('Address', 'getAreas', Array) #2 /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/classes/NovaPoshtaApi.php(55): LisDev\Delivery\NovaPoshtaApi2->getAreas(NULL, NULL, NULL, NULL, NULL) #3 /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/classes/DatabaseSync.php(64): plugins\NovaPoshta\classes\NovaPoshtaApi->__call('getAreas', Array) #4 /home/ambr in /home/ambra/ambra.in.ua/www/wp-content/plugins/woo-shipping-for-nova-poshta/vendor/lis-dev/nova-poshta-api-2/src/Delivery/NovaPoshtaApi2.php on line 172`

**Comment by FloatingGhost** [comment]
Think you might have the wrong repo.

MISP doesn't use wordpress in any way.

**Comment by Rafiot** [comment]
What she says.
