### ISSUE TITLE
more general exception handling with PyMISP api.py calls to PyMISP.__prepare_request()

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3318]
Originally in #3293 an issue with HTTP 503 errors back when `PyMISP.add_hashes()` was called was fixed inside `PyMISP._send_attributes()` by catching any exceptions thrown from `PyMISP.__prepare_request()` (see MISP/PyMISP@8c4889c). That fix caused the caller to `add_hashes()` to now check the returned value as a `dict` indicating that the MISP server replied, and also for `str` meaning something not from the MISP server occurred, e.g. an HTTP 503, e.g.
```
...
r = misp.add_hashes(...)
if r:
    if isinstance(r[0], str):
        # likely an http error, e.g. HTTP 503
        errorStr = r[0]
    elif isinstance(r[0], dict):
        # error from add_hashes()
        if 'name' in r[0] and 'error' in r[0]['name'].lower():
            errorStr = str(r[0])
        elif 'errors' in r[0] and 'already exists' in str(r[0]).lower():
            # ignore case where this hash exists for this event
            errorStr = None
        else:
            errorStr = 'UNKNOWN ERROR: %s' % (str(r[0]))
...
```

Being that we are still having issues with HTTP 503 (see #3305), we now see other PyMISP API calls experiencing 503s and throwing JSON exceptions back, e.g. just observed in `PyMISP.delete_event()`.

So this begs the question if there is a need for a general method of handling HTTP errors back to PyMISP API clients. For example, this could include `try:except` wrapping all calls to `PyMISP.__prepare_request()`.

**OR...** should all PyMISP API calls in client code start catching JSON exceptions to detect HTTP errors?

**OR...** ???

**Comment by Rafiot** [comment]
Let's go for a generic answer. I'll avoid implementing something nasty in the lib.

1. `__prepare_request` returns a [requests.Response](http://docs.python-requests.org/en/master/api/#requests.Response)
2. `_check_response` try to make sense of the response, and blow up in your face if there is a 500, because 500 means the server barfed: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L210

[requests.Response](http://docs.python-requests.org/en/master/api/#requests.Response) contains a  [PreparedRequest](http://docs.python-requests.org/en/master/api/#requests.Response.request), which contains everything that has been sent to the server.

What do you want from PyMISP **exactly**. Don't bother looking at the code, just tell me what you want from me and I'll see what I can do with that.

As an example, I can return in the error key the URL and the json blob that has been sent.

**Comment by Rafiot** [comment]
In the mean time, I did some changes, so you get a detailed exception when the server is unable to give you a reasonable answer: https://github.com/MISP/PyMISP/commit/558c6929208412d0c92b0d9d5e5af0b6fef6049f

**Comment by github-germ** [comment]
Didn't forget. Got some other thingies to get done and then will revisit this one. THANKS!

**Comment by github-germ** [comment]
Sorry about the delay. My experience with this issue were the 503's occurring in `PyMISP.add_hashes()`.

I'm still a newbie with `MISP` and `PyMISP`, so here some ideas, but I am eager to see your feedback.

1. Interestingly, it appears that `add_hashes()` might be the only function that does not use `_check_response()` which is where you made that some changes with  MISP/PyMISP@558c692. Should it be used there also?
2. `_check_response()` is catching `ValueError`; however, I'm wondering if it should also include `simplejson.errors.JSONDecodeError` which I can reproduce here in `_send_attributes()` as called by `add_hashes()` when an HTTP 503 occurs:
```
512             resp = self.__prepare_request('POST', url, json.dumps(data, cls=MISPEncode))
513             try:
514                 responses.append(resp.json())
515             except Exception:
516                 # The response isn't a json object, appending the text.
517                 responses.append(resp.text)
```
3. That said, I think every `PyMISP` API function that can encounter a lower-level HTTP (and perhaps OS), should probably throw an exception vs. having to test the return value type (e.g. `dict` v. `str`). This does grow the code with clients having to wrap every `PyMISP` call in a `try:except`. So I am open to your thoughts here.
4. I imagine for HTTP errors, e.g. 500s, perhaps a new exception, e.g. `PyMISPHTTP` _(ugly)_ might be good. And there might be others exception classes also?
5. Need to decide on the content of the exception construction, e.g. `str` or `dict`.
6. I believe when adding an attribute that already exists for an event, there is an HTTP 403, and the `dict` returned from `add_hashes()` must be parsed for an `errors` key that has a value containing `already exists` -- maybe that should be an exception also, e.g. `PyMISPDuplicate`.
7. And I wonder if the way other errors are returned from `add_hashes()` as handled in my original code version was because `_check_response()` wasn't used.
8. Example client: See the code in https://github.com/MISP/MISP/issues/3318#issue-329952692 which could not become:
* ORIGINAL
```
if r:
    if isinstance(r[0], str):
        # likely an http error, e.g. HTTP 503
        errorStr = r[0]
    elif isinstance(r[0], dict):
        # error from add_hashes()
        if 'name' in r[0] and 'error' in r[0]['name'].lower():
            errorStr = str(r[0])
        elif 'errors' in r[0] and 'already exists' in str(r[0]).lower():
            # ignore case where this hash exists for this event
            errorStr = None
        else:
            errorStr = 'UNKNOWN ERROR: %s' % (str(r[0]))
```
* REVISED
```
try:
    r = misp.add_hashes(...)
except PyMISPHTTP as e:
    # http error, parse e, and act
    ....
except PyMISPDuplicate as e:
    # duplicate hashes
    pass
except PyMISPError as e:
    # process error
    ....

...
```

**Comment by Rafiot** [comment]
Before tackling all the problems at once, let's take a few steps back: most of the errors you get are due to the massive multiprocessing script you're using and it is causing a massive range of problems that, as you say, go from a mix of types that don't make sense in the Python responses, to Apache just failing to handle the load.

Did you try my PR here : https://github.com/deralexxx/PySight2MISP/pull/6

**Comment by github-germ** [comment]
Good question: ```Did you try my PR here:``` deralexxx/PySight2MISP#6

I wanted to reply to this issue since it was older. The new method of aggregating all attributes in an in-memory event before committing to the server is on my ToDo list this week also. I will try that script as is, but I suspect it won't work out-of-the-box as the original did not. So, I will refactor my version with this method, and that will take a bit more time. Thanks so much for showing me the say. Soon...

**Comment by github-germ** [comment]
i mistakenly closed this ticket. Still need to work on dealing with lower level exception experienced in PyMISP back to the client code: https://github.com/MISP/MISP/issues/3318#issuecomment-398163042

**Comment by github-germ** [comment]
@Rafiot ... Now that the original cause of many HTTP 503 errors has been mitigated via https://github.com/deralexxx/PySight2MISP/pull/6 let me know when we want to revisit this issue to enhance PyMISP exception handling for clients perhaps by once again looking at https://github.com/MISP/MISP/issues/3318#issuecomment-398163042

Thanks.

**Comment by Rafiot** [comment]
The 503 are raised by the web server, with no indications on what went wrong on MISP side, so there is no way to do anything else than hard failing. 

When the response contains error messages, yes, we should handle it in a different way and I'll open a new issue for that.

**Comment by github-germ** [comment]
Hi @Rafiot 

planing out my dev roadmap for my next release internally for my project. wondering if i will include client changes as per possible improvements to `PyMISP` client interaction when "external/unexpected" exceptions, e.g. HTTP errors, occur. do you think you will have time to revisit my first ideas on https://github.com/MISP/MISP/issues/3318#issuecomment-398163042 sometime "soon"?

Thanks!!

**Comment by github-germ** [comment]
@Rafiot 

> When the response contains error messages, yes, we should handle it in a different way and I'll open a new issue for that.

Is there a new issue for this? Just want to stay connected on this so when there's something new I can adjust my client apps. Thx...

**Comment by Rafiot** [comment]
It is this issue: https://github.com/MISP/PyMISP/issues/248

I didn't have time to handle it yet.

**Comment by github-germ** [comment]
Thx !!

**Comment by github-germ** [comment]
@Rafiot -- see 
https://github.com/MISP/PyMISP/issues/248#issuecomment-441298879 -- Thx!!
