### ISSUE TITLE
MySQL Tuning

### ISSUE THREAD

**Issue by gitnorty** [MISP/MISP#3319]
Can you please point me to any documentation for recommendations to tune the performance of MySQL in support of MISP?  Is there a standard set of configurations you can recommend?

Thanks in advance!

### Work environment

| Questions                 | Answers
|---------------------------|-------------------
| Type of issue             | Question
| OS version (server)       | CentOS/RedHat
| OS version (client)       | N/A
| PHP version               | 7.1.8
| MISP version / git hash   | 2.4.91 deadlock fix, 1ddb33b6fdc981b1467d2f5d13aa95a974350876
| Browser                   | N/A

**Comment by SteveClement** [comment]
We are working on a general performance chapter in @MISP/misp-book
Will let you know as soon as we make progress.

**Comment by seamustuohy** [comment]
+1 Would also be interested in seeing documentation for tuning MySQL for different common use-cases. For example, something along the lines of "here are recommendations on how you should configure on a very powerful machine; here is what you should do if you are going to have a LOT of correlations, what you should do if you are going to have a lot of different users, etc."

**Comment by github-germ** [comment]
+1

**Comment by SteveClement** [comment]
As this is an ongoing request and we are not possibly able to do it all, we have 2 solutions, well actually 3.

1. Document it yourself and push it to https://github.com/MISP/misp-book
2. Try and find someone who does it for you, maybe with $$$ this is easier (remember the tool is Free and Open Source so certainly there are some savings done somewhere to put the food where the mouth is)
3. Wait for us to do it in exactly 337 urgent issues to be resolved

I am a big fan of Number 2, if you are too , please reach out to: info@circl.lu
And obviously this counts for anything that is note "core" enough to be solved in a timely fashion ;)

Keep sharing and enjoy the Platform.
