### ISSUE TITLE
Automation stall when tag filter contains punctuation mark colon ( : ) 

### ISSUE THREAD

**Issue by lucamemini** [MISP/MISP#3325]
Hello =)
I will try to download suricata rules in automation mode with this URL
https://misp.local/events/nids/suricata/download/false/false/malware_classification:malware-category="Adware"/
But php race max execution time (600 sec!)

With another tag (without mark colon) the process work as well

**Comment by iglocska** [comment]
url parameters are evil. What is happening is MISP sees this:

request to: https://misp.local/events/nids
nids type = suricata
download/key = download
parameters: false, false
named parameter: "malware_classification": "malware-category=\"adware\""

Make sure you use post requests instead!

That would look like this:

POST to:
`https://misp.local/events/nids/suricata/download`
POSTed body:
```
{
  "tags": ["malware_classification:malware-category=\"Adware\""]
}
```

**Comment by lucamemini** [comment]
OK !
You win. =)

**Comment by iglocska** [comment]
;)
