### ISSUE TITLE
edit button disappear for Object in last v2.4.92 ?

### ISSUE THREAD

**Issue by rmkml** [MISP/MISP#3328]
Hello,
First, Big Thx You for Very good MISP Project,

but could you check if edit button dissapear for object in last v2.4.92 please ?
(blue line, top right just before trash)

Best Regards
@Rmkml

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Yep, it was a bug that was fixed the other day, just git pull to the latest commits to fix it!
