### ISSUE TITLE
Don't know how to properly set up VM instance of MISP

### ISSUE THREAD

**Issue by Aisik00** [MISP/MISP#3329]
Hello,
I am trying to make working the VM instance of MISP, but I don't know what to set properly.
First of all, am I writing to the right spot, or is there any other question forum, email or something?

From the tutorial in the docs I do not understand what everything should be set up in VirtualBox or how does this instance work. I should set up two network adapters, which first is NAT and second is host only. The second one requires the name, which i configured in Virtual Box preferences (i filled 192.168.56.50 address??). 

Now how am I supposed to run the instance and connect to it via browser? Just run the image and than?
Can anyone help me, because I think I am missing big part of know-how here.

Thanks for every help and answer.

**Comment by adulau** [comment]
All the ports on the VM are locally redirected to the home OS, so you can reach MISP via http://127.0.0.1:8080/ and the dashboad http://127.0.0.1:8001

I hope this helps.

**Comment by Luc13n** [comment]
Thank you adulau

**Comment by Aisik00** [comment]
Yea, now it works, that's all i needed. 
Thank you very much for help.
