### ISSUE TITLE
MariaDB / MySQL CPU Spikes

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#3331]
So this is my red-headed step child.  None of my other MISP servers do this.  However, this is the only server facing the public that's hidden behind an Apache based reverse proxy. 

What's basically happening is that when observing processes through htop I see MySQL spikes way over 100.  The rest of the server is fine.  I have 4 CPU's on the VM and 6GB RAM.  The symptoms are basically slow login, and sometimes the page just dies.  I can always open a new tab and get back to work.  It's really odd.  I've checked the configs and as far as I can tell there's nothing wrong with the server.  I've even gone so far as to disable HUGE PAGES in redis.  

Really lost on this one.  

Jimbo

**Comment by jimbolya0607** [comment]
So here's another caveat.  It seems to happen when I'm trying to access the events page; which, comes right after you initially log in.  I've tried to bounce from say the Galaxies page back to events and get the same kind of lag out.

**Comment by jimbolya0607** [comment]
So another difference.  The other MISP servers don't have the DB locally installed with MISP.  They point to a separate database server on a different network.

**Comment by adulau** [comment]
Which version of MISP is running on the MISP behind the reverse proxy?

**Comment by jimbolya0607** [comment]
2.4.92

**Comment by jimbolya0607** [comment]
My other master server is also on 2.4.92 and I have no issues with that.  

You will typically eventually log into the box.  However, it takes a really long time.  I have noticed some spikes going to and from the event's page.  I'm not sure if that is the issue or not.

**Comment by iglocska** [comment]
What session handler are you using?

**Comment by jimbolya0607** [comment]
you mean this?
https://httpd.apache.org/docs/2.4/mod/mod_session.html

Sorry I'm don't know that much about proxies and whatnot...

Or do you mean this?

https://mariadb.com/resources/blog/maxscale-and-transparent-session-handling

**Comment by iglocska** [comment]
MISP's session handler administration -> server settings -> security -> sessionhandler

it should be php and php.ini should get the settings to use redis as explained in the setting's description.

**Comment by jimbolya0607** [comment]
Critical | Session.defaults | php
-- | -- | --

**Comment by iglocska** [comment]
ok, that's a good start. Check your php.ini if it's set up to use redis sessions - otherwise it reverts to file sessions which is blergh.

**Comment by jimbolya0607** [comment]
where do i put those in php.ini file?
at the bottom?

**Comment by jimbolya0607** [comment]
So i found session.save_handler
Mine says:  session.save_handler = files

**Comment by jimbolya0607** [comment]
So I changed those settings and nothing changed...still hangs at logging in.  Not sure if this helps...
![image](https://user-images.githubusercontent.com/23529336/41363440-ebe7d9fc-6f01-11e8-8cff-b4b84cb24f58.png)

**Comment by iglocska** [comment]
So it ONLY happens on the event index? Other pages are fine?

**Comment by jimbolya0607** [comment]
It mainly happens at login.  It will either hang and you will eventually log in, or you will get a 502 unable to process /GET...

**Comment by jimbolya0607** [comment]
Ok - if i edit with the setting you suggested it doesn't get to the site or says internal error occurred...

**Comment by SteveClement** [comment]
@jimbolya0607 how did you edit the settings? Like what value did you use?
