### ISSUE TITLE
Extend event not working with event ID

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3332]
On the /events/add page the "Extend event" form field says "Event UUID or ID" however only when an UUID is entered this actually works. When entering an event ID a "Matched event" preview is shown but when saving the event MISP says "The event could not be saved. Please, try again." and "Please provide a valid UUID"

Saving should also work when providing an event ID.

**Comment by iglocska** [comment]
Have a local fix for this, will push it together with some other stuff soon.
