### ISSUE TITLE
Can't use Cortex?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3333]
I'm trying to enable the Cortex plugin on a MISP instance.
The following request is sent to Cortex:
GET /modules 
(with the correct auth-key etc)

Cortex response is:
400 Bad Request
A client error occurred on GET /modules: Invalid Json: No content to map due to end-of-input at ...

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug / Question?
| OS version (server)       | Ubuntu 16.04-LTS
| OS version (client)       | Seven
| PHP version               | 7.0
| MISP version / git hash   | 2.4.92
| Browser                   | Firefox

**Comment by iglocska** [comment]
Cortex 1 or Cortex 2?

**Comment by xme** [comment]
2.0.4

**Comment by iglocska** [comment]
Forgot about it, apparently the API key is not being passed correctly. Will poke you back today once it works, need to set it up to test it!

**Comment by xme** [comment]
Hi Andras,
Were you able to reproduce the error?

**Comment by iglocska** [comment]
Yep, The guys over at the hive have a fix ready, I just need to update
something to be compatible on our end and it should then work fine with the
latest version of cortex. Hang on a minute!

**Comment by iglocska** [comment]
Just pushed a fix, could you try it with the latest version of Cortex?

**Comment by xme** [comment]
Implemented the fix ('bearer' -> 'Bearer') but same issue.
When I click on "Admin -> Server Settings & Maintenance", MISP makes an HTTP request to Cortex:

Content-Type: application/json
Authorization: Bearer <apikey>
User-Agent: CakePHP
GET /modules HTTP/1.1

If I use a bad API key, I'm getting the same error...

**Comment by iglocska** [comment]
interesting. Checking.

**Comment by xme** [comment]
Testing with curl from the MISP server console, it works (ex: "GET /api/job")
Do you know the purpose of the "GET /modules"? I don't find any reference in the Cortex API documentation.

**Comment by iglocska** [comment]
/modules is the misp-modules introspection interface. Cortex has a
misp-modules compatible interface, but cortex2 was lacking it at first -
the latest build from github should have it working again.

**Comment by xme** [comment]
Ok, let's see if I need to upgrade my Cortex too!
