### ISSUE TITLE
attachTagToObject fails

### ISSUE THREAD

**Issue by tokoivun** [MISP/MISP#3334]
I'm trying to add a tag to an attribute, as per the Automation API documentation.

If I do:

curl -vkX POST https://xxx.com/tags/attachTagToObject/ --header "Authorization: key " -d "{"uuid"="d9ded541-182b-025a-ab9e-d371d6791a0e" "tag"="fluffy"}" --header "Accept: application/json" --header "Content-Type: application/json"

It fails: {"name":"Invalid object uuid","message":"Invalid object uuid","url":"\/tags\/attachTagToObject\/"}r

However, if I do:

curl -vkX POST https://xxx.com/tags/attachTagToObject/d9ded541-182b-025a-ab9e-d371d6791a0e/fluffy --header "Authorization: key " --header "Accept: application/json"

it works. I would love to know what goes bonkers in the first attempt as the data should be exactly like in the examples, and since the latter attempt works it shows that the problem is not in the uuid itself.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 16.04.1 LTS
| PHP version               | 7.0.30-0ubuntu0.16.04.1
| MISP version / git hash   | 2.4.92, 82cd3ef4a572f53f9dd09d173f75822484510552

### Expected behavior

For the tag adding to work :)

### Actual behavior

It doesn't :)

**Comment by iglocska** [comment]
Try it with 

```
{"uuid":"d9ded541-182b-025a-ab9e-d371d6791a0e", "tag":"fluffy"}
```

Cough ;)

**Comment by tokoivun** [comment]
Well, crap. That worked :) Any hints on how to do it by pushing it from file. If I do have this in a file (foo.json, for example):
{"uuid":"b29a39d7-d1d2-7036-5959-62010c2158e1", "tag":"confidence-level-95"}

when using curl with -d "@foo.json" (with or without the @ character) it fails with the same error message

**Comment by iglocska** [comment]
Something like this should work:

```
curl -vX POST https://URL/tags/attachTagToObject/ --header "Authorization: API_KEY" -d @foo.json --header "Accept: application/json" --header "Content-Type: application/json"
```

**Comment by tokoivun** [comment]
as@funk:/opt/AptMispDaemon# curl -k -POST https://xxx.com/tags/attachTagToObject/ --header "Authorization: xxx " -d @foo.json --header "Accept: application/json" --header "Content-Type: application/json"

{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/tags\/attachTagToObject\/"}

as@funk:/opt/AptMispDaemon# cat foo.json
{"uuid":"adad2a74-4a51-3d6e-544a-21e3c59760a0", "tag":"misp-galaxy:threat-actor=\"Iron Tiger\""}
as@funk:/opt/AptMispDaemon#

I've verified there is an attribute with the "adad2a..." uuid in the db.

Can't find any log entries anywhere that would explain the error

**Comment by iglocska** [comment]
Try with this as payload?

```
{"uuid":"adad2a74-4a51-3d6e-544a-21e3c59760a0", "tag":"misp-galaxy:threat-actor=\"Iron Tiger\""}
```

**Comment by tokoivun** [comment]
Same, Internal error :(

**Comment by tokoivun** [comment]
Hum, I think I've actually tracked the root cause down. I'll do a few tests and post more info

**Comment by tokoivun** [comment]
The root cause was non-RFC 4122 compliant UUID's. For some reason the attributes with faulty UUID's will import fine, tag adding goes bonkers as the UUID is validated. So I reckon attribute adding needs UUID validation as well.
