### ISSUE TITLE
correlation search on login

### ISSUE THREAD

**Issue by mscox42** [MISP/MISP#3335]
When logging into MISP a correlation search appears to run for every event on the first page of the events list. If this first page has large events with many attributes, there is a noticeable delay. It is even possible to completely lock yourself out of the UI if it takes so long for this correlation search to run that your session times out before it completes (or so I hear from a friend). No doubt there are some tuning and sizing issues to deal with on my end, but maybe a helpful option would also be the ability to set the home page to some other screen to avoid this initial correlation search. Thanks.

The search I see going against the DB when logging in is, for example:

EXPLAIN SELECT `Correlation`.`1_event_id`,
count(distinct(`Correlation`.`event_id`)) as count FROM
`misp`.`correlations` AS `Correlation` WHERE `Correlation`.`1_event_id`
IN (19069, 19068, 19066, 19067, 19063, 19064, 19065, 19062, 19059,
19060, 19061, 19058, 19056, 19057, 19055, 19054, 19053, 19052, 19047,
19048, 19049, 19050, 19051, 19045, 19046, 19034, 19035, 19036, 19037,
19038, 19039, 19040, 19041, 19042, 19043, 19044, 19033, 19031, 19032,
19030, 19027, 19028, 19029, 19025, 19026, 19016, 19017, 19018, 19019,
19020, 19021, 19022, 19023, 19024, 19012, 19013, 19014, 19015, 19011,
19010) GROUP BY `Correlation`.`1_event_id`:

**Comment by iglocska** [comment]
Just turn the feature off via Administration -> Server settings -> MISP tab -> MISP.showCorrelationsOnIndex

:)
