### ISSUE TITLE
python2 vs python3

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3337]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request,

Today some (optional?) MISP features require python3, and some other are still using python2.
This results in packages that need to be installed using pip and others pip3. 

This issue is to track the evolution to i) full python3 compatibility, and ii) a full switch to python3. (or allow a server setting to choose python2 or 3 if it's feasible without issues)

TODO list:
- [x] migrate all python scripts to python3 compatible scripts
- [x] identify if full python3 switch is possible
- [ ] switch to python3 or allow choice between python2/3 as server setting

**Comment by cvandeplas** [comment]
Some remarks from the chat:
the zmq code should work in Python3 as-is.
yep, ZMQ should work fine
Maybe the encoding (enforce) on the Redis would need to be set as it will b'' by default.

**Comment by Rafiot** [comment]
For redis itself, passing `decode_responses=False` to the constructor (`redis.Redis` or `redis.StrictRedis`) will automatically decode to `utf-8`.

**Comment by bioteseo** [comment]
I don't write code in python.
I installed misp on a fresh ubuntu server 16.04, then on a fresh ubuntu server 18.04 and I tried ubuntu server 17.10 (misp vm). All these use python 2.7 as default. There are many issues when you decide to use pip or pip3 to install a package.

For instance you can use only pip install pyzmq. If you try pip3 you will find this:
-sudo -u www-data python /var/www/MISP/app/files/scripts/mispzmq/mispzmqtest.py will fail, so zmq don't run. This is the test to check pyzmq library installation
-if you solve that, sudo -u www-data python /var/www/MISP/app/files/scripts/mispzmq/mispzmq.py /var/www/MISP/app/tmp/logs/mispzmq.log  /var/www/MISP/app/tmp/logs/mispzmq.error.log don't run. you'll receive this error "TypeError: list indices must be integers, not float". The description is here: https://stackoverflow.com/questions/13355816/typeerror-list-indices-must-be-integers-not-float
So zmq run only on python2

In the Administration->Server Settings & Maintenance->diagnostics page there are many check about "optional" library. Misp suggests you, for failed checks, to solve that by pip install. After their installation, if you check /var/log/apache2/error.log you'll find:
WARNING [abstract.py:19 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
WARNING [mispevent.py:26 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
WARNING [api.py:31 - <module>() ] You're using python 2, it is strongly recommended to use python >=3.5
But the diagnostics is ok. This is true for python-magic, pymisp, and maec library

I used pip uninstall then pip3 install and the errors are gone but checks in the diagnostics page are failed

**Comment by ktneely** [comment]
I'm running through the install steps on a fresh Ubuntu 18.04 server.  This doesn't have pip(2), by default, but from this thread, I'm guessing I'd need to install pip so I can get the necessary python2 modules added.

**Comment by SteveClement** [comment]
@ktneely no, please just use pip, this will install the python3 modules. If you have any install issues doing that, please report it back.

**Comment by Rafiot** [comment]
The zmq script is broken in python3, I have a fix here: https://github.com/MISP/MISP/pull/3405

This PR will port everything it touches to python 3.6 (there will be no backward compatibility to python2, and no way to choose on the web interface, because this is a pain).

**Comment by Rafiot** [comment]
I think it is all sorted, and we force >=python3.5 now.
