### ISSUE TITLE
Cannot edit my own object?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#3338]
Running 2.4.92 I have this strange error that after creating and saving an object (have tried different ones) I cannot edit it afterwards. The button is simply missing:

![object1](https://user-images.githubusercontent.com/25325656/41408912-aaefca58-6fd4-11e8-9f18-430e9ca4b868.png)
![object2](https://user-images.githubusercontent.com/25325656/41408913-ab070a2e-6fd4-11e8-9d3a-b948d38aaae7.png)

Hints anyone? Is this a new configuration option I've accidently activated?

**Comment by iglocska** [comment]
grab the latest commit, was fixed a few days ago ;)

**Comment by StefanKelm** [comment]
Awesome, thanks @iglocska !
