### ISSUE TITLE
Failed Jobs

### ISSUE THREAD

**Issue by gitnorty** [MISP/MISP#3340]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | CentOS/RedHat
| OS version (client)       | N/A
| PHP version               | 7.1.8
| MISP version / git hash   | 2.4.92, 56af0c4297ba136fe65ae25bb172cd863832061c
| Browser                   | If applicable

We've noticed in our setup that some jobs (not all) are failing (never completing) but aren't being reported as failed.  Currently the jobs we've seen that have failed are MISP to MISP pull failures.  From what we've seen in the logs, there are no indications that the pull failed; just that the job never finishes; the progress hangs at the percentage it had completed.

- Is there a recommended way to terminate failed jobs?  

- Additionally, I'm not sure if this functionality exists or not; but are there timers, where if a job doesn't complete within a specified time frame, that the job will report as failed?

**Comment by SteveClement** [comment]
Once way to terminate jobs is via the Web UI.
Or kill it on the CLI.

If you need "timers" you want to look into a crontab job.

Feel free to re-open with updated content.
