### ISSUE TITLE
Feature: encrypt database password stored in database.php

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3342]
Feature Request
2.4.92

Would you consider optionally offering encrypting the db password in `database.php`, which is currently stored in clear text as per https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt#L276 and then decrypting when accessing the `DATABASE_CONFIG` class in the php code at runtime? Perhaps a setting in the WebUI to enable this for those who don't require this feature, and backwards compatibility.

In our corporate production data center we will fail an audit with any password in the clear.

**Comment by RichieB2B** [comment]
What security would that add? The encryption password for the db password will need to be stored somewhere in plain text as well..

**Comment by github-germ** [comment]
What we've done before is write a CLI tool and python module that can:

- Create a file set containing app and user credentials along with an encrypted representation of the password
- Allow an application to decrypt and obtain the actual password based on app domain and user name, and use those credentials as part of the app's authentication process
- The encryption method uses pycrypto. In particular, a base64 AES cipher with a random initialization vector (iv) along with the plaintext password are used to encode the password. The generated iv and encoded password are stored in the credential file pair

**Comment by adulau** [comment]
@github-germ From the description, it seems more obfuscation than encryption.  If you want to create such model in MISP, we will welcome a pull-request with such feature as an option for the users needing obfuscation to pass audit.
