### ISSUE TITLE
choices for event distribution across orgs when creating events with PyMISP

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3343]
2.4.92

- Is it true that the only choices for the `distribution` argument to `PyMISP.new_event()` are as follows?
```
'options' => array('0' => 'Your organisation only', '1' => 'This community only',
'2' => 'Connected communities', '3' => 'All communities'),
```
- Or is there another way when creating a new event to set the `distribution` to a `sharing_group` (by `name` or `id`).
- Or must `PyMISP.change_sharing_group()` be called after `PyMISP.new_event()`?
- Or ...
- And are there other ways to restrict distribution for events as they are created, for example, in an ingestion script?

**Comment by github-germ** [comment]
Any feedback appreciated.

**Comment by github-germ** [comment]
Hoping someone can educate us better on best-practices for user access to events via `distribution`, `sharing-groups`, etc. We are at the point where we need to design how we will implement this. Thank you.

**Comment by iglocska** [comment]
Ping @Rafiot

**Comment by Rafiot** [comment]
Pong @iglocska: what is the minimal keys/values I need to pass in order to set/change a sharing group? 

Then, I'll add a helper in MISPEvent/MISPAttribute

**Comment by iglocska** [comment]
Will have a look tomorrow for creating sharing groups, this one is trickier - don't think the sharing group additions have self-describing APIs so that kind of sucks.


As for just setting a sharing group, sharing_group_id should work as long as the distribution level is set to 4 so this should be super straight forward.

**Comment by Rafiot** [comment]
Noted, I'll had this option and sanity checks asap. I'm not sure what would be the nice way to make user's life easy.

**Comment by iglocska** [comment]
hmm the best would probably be to query the sharing groups from MISP.

**Comment by Rafiot** [comment]
Well, yes (that works already), but when you automate, you want the proper ID, or you want to use the name? What about UUID?

**Comment by SteveClement** [comment]
@github-germ I suppose this answered all your questions.
Please re-open if needed and an actual bug emerges.
