### ISSUE TITLE
Freetext Feeds do not download

### ISSUE THREAD

**Issue by ScottyAU** [MISP/MISP#3344]
We are trying to make use of the Feeds functionality - but cannot get a freetext/csv based (ie not a MISP JSON) feed to work.  

Type of issue: Bug
OS version (server): Ubuntu server 16.04.4 LTS
PHP (settings from MISP UI):
   PHP ini path:… /etc/php/7.0/apache2/php.ini
   PHP Version (>7.0.16 recommended): 7.0.30-0ubuntu0.16.04.1 (Up to date)
   PHP CLI Version (>7.0.16 recommended): 7.0.30-0ubuntu0.16.04.1 (Up to date)
MISP version / git hash:
  Currently installed version…	v2.4.92 (169da86545fe4abf8087297fc46bc6f552d83956)	
  Latest available version…	v2.4.92 (84b5989fb30731cb8d44817125d6b926f701b719)	
  Status…	OK	

### Expected behavior
We should be able to create a csv or freetext based feed and have it pulled and populated into MISP

### Actual behavior
The job is created and marked as complete, however no data is added to MISP.  Doing a tcpdump on the server shows no attempt to even request the URL hosting the csv/freetext file.  Only a single error message in /var/www/MISP/app/tmp/logs/resque-wroker-error.log:

2018-06-17 22:36:03 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 776]
Job done.

### Steps to reproduce the behavior
Create a new freetext/csv based feed - or just enable one of the provided ones and attempt to pull the feed.

### Logs, screenshots, configuration dump, ...
As mentioned in /var/www/MISP/app/tmp/logs/resque-worker-error.log:

2018-06-17 22:36:03 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 776]
Job done.

tcpdump shows no attempt to retrieve the resource from the URL specified in the config for the feed.

**Comment by ScottyAU** [comment]
Solved this as soon as I raised the ticket.  Was a proxy config issue on the host.

**Comment by young2112129** [comment]
> Solved this as soon as I raised the ticket. Was a proxy config issue on the host.

I also have this problem.
How to modify proxy config to fix this problem?
