### ISSUE TITLE
Number of attributes not shown correctly

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#3346]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, support...
| OS version (server)       |  ubuntu
| OS version (client)       | Win 7
| PHP version               | 7.0.30
| MISP version / git hash   | 2.4.92, ba7662e6a01726b452997a2e4d1641b49aaeb593
| Browser                   | Firefox

### Expected behavior
You see the correct number of attributes for all events on the 'List Events' page.
This number is identical to the number shown on the 'View Event' page.

### Actual behavior
We have some feeds with thousands to hundred thousands attributes which are frequently updated. The shown number of attributes of those on the 'List Events' page differs from the actual (and correct) number of attributes in the detailed 'View Event' page.
In one example, we even removed all attributes, but it still says that there are some thousands left.
As far we can tell, it only occurs with feeds and/or Events with a lot of attributes and changes.

### Steps to reproduce the behavior
Activate a feed with thousands of attributes and let it update from time to time.

Is there a way to clean such events up properly? I already tried to remove orphaned attributes.

Best regards

**Comment by SteveClement** [comment]
@Kahuna01 some more questions:

The activated feed, is it fetching a CSV feed?
If so, I suppose the target event will be a Fixed Event ID?

Perhaps you update to 2.4.93 there were some improvements in that area.

**Comment by iglocska** [comment]
It is indeed buggy atm, will rework the way the counting works.

**Comment by Kahuna01** [comment]
@SteveClement 
You're right, in that case it is a CSV feed with a fixed Event ID. It still occurs with 2.4.93

**Comment by iglocska** [comment]
Correct, it has to do with a rather wonky way of keeping track of the attribute count. Was trying to cut some massive corners and it has some side effects. Will try to have a look this week.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
