### ISSUE TITLE
Add multiple organisation events to a new feed

### ISSUE THREAD

**Issue by tr4shitter** [MISP/MISP#3348]
Hey, i have thousands of events saved in the misp to one organisation, but not a feed! Now i want to add all events from the organisation "org1" to a new feed named "org1-feed" . How can i accomplish that?

My main goal is to use the feed overlapping matrix to compare some different sources, which only works on feeds...

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | missing feature?
| OS version (server)       |centos7
| OS version (client)       | centos7
| PHP version               | PHP 5.4.16 (cli) (built: Mar  7 2018 13:34:47) 
| MISP version / git hash   | latest
| Browser                   | chromium/firefox

### Expected behavior
select the organisation and create feed

### Actual behavior
cannot find a way to accomplish that

### Steps to reproduce the behavior
add 2 events to a new organisation and try to build one feed of all events

### Logs, screenshots, configuration dump, ...
not needed

**Comment by SteveClement** [comment]
Dear @tr4shitter you can use: https://github.com/CIRCL/PyMISP/tree/master/examples/feed-generator

Join us on https://gitter.im/MISP/MISP to get support if it doesn't work out of the box for you.
