### ISSUE TITLE
PyMISP User Rate Limits

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3351]
I see there was some discussion about user rate limiting in #1176. Are there any ways to limit client PyMISP API usage in MISP or one of the underlying technologies? If not, are there any plans for rate limiting support on the future release roadmap? Thanks...

**Comment by github-germ** [comment]
Any feedback appreciated.

**Comment by github-germ** [comment]
As we continue to roll-out MISP to in-house data consumers, we may need to the ability to throttle automated client access. Any insight on how to do this with an existing MISP feature or approaches that others may have used to control access. Thanks...

**Comment by adulau** [comment]
There is a functionality per role where you can limit the memory usage and/or time of execution.

**Comment by Rafiot** [comment]
This is a complex problem. There is no way to control it on PyMISP side without writing a wrapper around the class. The next question will be what do we want to rate limit? Insert? Search? Export? How gracefully does it need to be handled? Can the server just fail and the client needs to retry later?

AFAIK, this isn't a priority on our side.

**Comment by adulau** [comment]
@Rafiot Maybe the rate-limit should be on the side of a reverse proxy or alike?

**Comment by iglocska** [comment]
I could try to do something on MISP side too, but don't really think it's something we actively want, as @Rafiot said. If we do implement something I have a gut feeling that it should be tied to role settings.

**Comment by github-germ** [comment]
Thx... Good points. Let me bring it back to the folks on my side who are interested in this rate limiting feature to see if we can refine with more details on what we'd looking for.

**Comment by SteveClement** [comment]
Well it could be done on Firewall level, this assumes DPI and some SSL-Certificate bending…
But yes a MISP DDoS might be a concern.

**Comment by SteveClement** [comment]
This is considered in the other ticket as well and we have reference back.
Closing for now.
