### ISSUE TITLE
Attach tags as sync user

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#3354]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question, support
| OS version (server)       | ubuntu 16.04
| OS version (client)       | Win 7
| PHP version               | 7.03
| MISP version / git hash   | 2.4.92, ba7662e6a01726b452997a2e4d1641b49aaeb593
| Browser                   | Firefox

### Expected behavior
Sync users can attach/detach tags from shared events.

### Actual behavior
Since 2.4.92 only admins can attach/detach tags from shared events. Others can only edit events from their own organisation.
We created a user account and gave him all permissions except admin-rights. That user was not able to attach tags on such an event. 

### Steps to reproduce the behavior
Login as a Sync user and try to edit tags of a shared event.

**Comment by Kahuna01** [comment]
Furthermore it is possible for non-admins to tag single attributes but not the event itself.
Is that supposed to be that way?

**Comment by SteveClement** [comment]
Dear @Kahuna01 have you tested on 2.4.93 already? Please let us know if this is still an issue.

**Comment by Kahuna01** [comment]
Just tested it with the latest version, still the same problem.

Here is how it looks. The "+"Button in the event view is simply missing:
![misp1](https://user-images.githubusercontent.com/31033198/42431774-abae9c40-8347-11e8-8732-a5f284a1d4dd.png)

**Comment by iglocska** [comment]
That looks correct, only the creator org of the event can add tags - I am
more surprised by the + button on the attribute level, that looks like a
bug. Can you actually add tags to attributes using that or is it just a UI
issue?

**Comment by Kahuna01** [comment]
Ah, if that's the case, then it's fine. One more reason to look forward for the implementation of local tags ;-)

Yes, tagging the attribute is possible for that user. Just the publishing afterwards has to be done by an admin.

**Comment by iglocska** [comment]
Exactly - local tags are becoming the holy grail for a lot of use-cases :) 

The tag edit on an attribute level is bad news, will fix it asap!

**Comment by SteveClement** [comment]
@iglocska closing time?

**Comment by iglocska** [comment]
"The tag edit on an attribute level is bad news, will fix it asap!"

**Comment by LeanVel** [comment]
@iglocska Plase correct me if I am wrong but, if it is should not possible to tag events coming from feeds, why can Admins do it? The ability to tag an event use to work just fine for a "reviewer" rol. It feels like the real issue here has to do with the way rols are being enforced.

> That looks correct, only the creator org of the event can add tags - I am more surprised by the + button on the attribute level, that looks like a bug. Can you actually add tags to attributes using that or is it just a UI issue?

**Comment by SteveClement** [comment]
@iglocska so this is fixed? Has asap arrived?

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
