### ISSUE TITLE
PyMISP folder empty on fresh install MISP {"major":2, "minor":4, "hotfix":92}

### ISSUE THREAD

**Issue by HachimanSec** [MISP/MISP#3359]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Unable to install PyMISP
| OS version (server)       | Linux ecs-6c50 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
| MISP version / git hash   | 2.4.92

### Expected behavior
Installing PyMISP

### Actual behavior
When I check out the latest version (as of today), the PyMISP folder is empty. Of course this breaks the installation step:
# install PyMISP
cd /var/www/MISP/PyMISP
sudo python3 setup.py install

Is this something problematic with my usage of Git?
Installation via git is done as described:
sudo -u www-data git clone https://github.com/MISP/MISP.git /var/www/MISP
sudo -u www-data git checkout tags/$(git describe --tags `git rev-list --tags --max-count=1`)

Thank you in advance. I hope this is not some obvious I am missing here, otherwise please point me in the right direction.

Cheers
Tom

**Comment by HachimanSec** [comment]
What seemed to help was following the next steps in the manual:
```
sudo -u www-data git submodule init
sudo -u www-data git submodule update
# Make git ignore filesystem permission differences for submodules
sudo -u www-data git submodule foreach git config core.filemode false
```

After that a 
```
cd /var/www/MISP/PyMISP
sudo python3 setup.py install
```
is possible.

However it throws an error:
```
ERROR [mispevent.py:52 - <module>() ] Cannot import jsonschema
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 50, in <module>
    import jsonschema
ImportError: No module named jsonschema
```

**Comment by SteveClement** [comment]
@TomHubGit this error is non-blocking and fixed in the latest version of pymisp.
