### ISSUE TITLE
HTTP 503 with many Event Deletions

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3361]
2.4.92

HTTP 503s with both WebUI and PyMISP deletions of a large set of events were experienced in
* https://github.com/MISP/MISP/issues/3305#issuecomment-395443896 -- simple single-threaded loop calling `PyMISP.delete_event()` can generate HTTP 503. To reproduce: https://github.com/MISP/MISP/files/2080890/mispDeleteEvents.zip
* https://github.com/deralexxx/PySight2MISP/pull/6#issuecomment-398592875 -- simply deleting many selected events in the WebUI, in this case 60 events selected with a filter on the `List Events` page, can cause an HTTP 503, and then when reloading the list, 48 were deleted with 12 remaining, could then delete the final 12 without error.

**Comment by github-germ** [comment]
@iglocska ... Howdy, when you get some time, I'm still curious as to why a simple PyMISP API loop to delete events in series (no concurrency) can yield HTTP 503  errors or why deleting multiple events from the WebUI doesn't fully complete (likely related). Thanks.

**Comment by SteveClement** [comment]
@github-germ is still still an issue?
Also: **large set of events** can you put a number on that please so I can reproduce and check my logs?

**Comment by SteveClement** [comment]
Couldn't reproduce.
Steps taken:

- Pull in OSINT Feed into vanilla MISP
- Run:

```bash
counter=$((counter+1))
while [ true ]; do
    echo $counter |./mispDeleteEvents.py
done
```
