### ISSUE TITLE
MISP Login issue

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [MISP/MISP#3369]
MAC OS 10.13 - virutalbox Ubuntu 16.04
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | ubuntu 16.04
| OS version (client)       | 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | firefox

### Expected behavior

misp login success
### Actual behavior
Web interface : invalid user name and password 

Database config: 
+------+-----------+-------------------------------------------+
| User | Host      | Password                                  |
+------+-----------+-------------------------------------------+
| root | localhost | *xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
| misp | localhost | *xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => 'admin',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
	);
}

config.php
$config = array(
	'debug'            => 0,
	'Security'         =>
		array(
			'level'      => 'medium',
			'salt'       => 'L8kF>v[ME Fym 35>wdkZdX/TA=&iVCy@=1@A/d&%NBO|kdk|Sw2J.UW.fOEJ?k12',
			'cipherSeed' => '',
			//'auth'=>array('CertAuth.Certificate'), // additional authentication methods
			//'auth'=>array('ShibbAuth.ApacheShibb'),
		),
array(
			'baseurl'                        => 'http://mymisp',
			'footermidleft'                  => '',
			'footermidright'                 => '',
			'org'                            => 'ORGNAME',
			'showorg'                        => true,
			'threatlevel_in_email_subject'   => true,
			'email_subject_TLP_string'       => 'TLP Amber',
			'email_subject_tag'              => 'tlp',
			'email_subject_include_tag_name' => true,
			'background_jobs'                => true,
			'cached_attachments'             => true,
			'email'                          => '',
			'contact'                        => '',
			'cveurl'                         => 'http://cve.circl.lu/cve/',
			'disablerestalert'               => false,
			'default_event_distribution'     => '1',
			'default_attribute_distribution' => 'event',
			'tagging'                        => true,
			'full_tags_on_event_index'       => true,
			'attribute_tagging'              => true,
			'full_tags_on_attribute_index'   => true,
			'footer_logo'                    => '',
			'take_ownership_xml_import'      => false,
			'unpublishedprivate'             => false,
			'disable_emailing'               => false,
			'Attributes_Values_Filter_In_Event' => 'id, uuid, value, comment, type, category, Tag.name',
		),
	'GnuPG'            =>
		array(
			'onlyencrypted'     => false,
			'email'             => '',
			'homedir'           => '',
			'password'          => '',
            'bodyonlyencrypted' => false,
            'sign'              => true,
		),
	'SMIME'            =>
		array(
			'enabled'          => false,
			'email'            => '',
			'cert_public_sign' => '',
			'key_sign'         => '',
			'password'         => '',
		),
	'Proxy'            =>
		array(
			'host'     => '',
			'port'     => '',
			'method'   => '',
			'user'     => '',
			'password' => '',
		),
	'SecureAuth'       =>
		array(
			'amount' => 5,
			'expire' => 300,
		),

NOTE: I'm using misp locally hence no ssl configured. using http://mymisp.com for login in web interface. 
Unable to login with:  admin@admin.test/ admin

**Comment by adulau** [comment]
You can reset the password of the instance with:

` /var/www/MISP/app/Console/cake Password [email] [password]`

Cheers

**Comment by shehreyarahmedkohati** [comment]
@adulau it gives a mysql could not connect error
I'll post the complete error in a while

**Comment by shehreyarahmedkohati** [comment]
THIS IS THE ERROR WHEN I RUN THE PASSWORD RESET COMMAND @adulau 
-------------------------------
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3646): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(268): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#10 /var/www/MISP/app/Model/AppModel.php(40): Model->__construct(NULL, NULL, 'default')
#11 [internal function]: AppModel->__construct(Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init('User')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel('User')
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(218): Shell->initialize()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#18 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#19 {main}
-------------------------------------
I have created the mySQL database using the commands in the documentation. 
When i query the users table, it returns empty set. 
The salt also may be a issue here I dont exactly know about it much.

**Comment by SteveClement** [comment]
You mysql user/password pair is wrong.

Please double check: /var/www/MISP/app/Config/database.php

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => 'Password1234',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
	);
}
