### ISSUE TITLE
Data imported using stix2misp ignores default distribution

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3370]
Events and attributes created using stix2misp (via the _Import from..._ menu) ignore the `MISP.default_event_distribution` and `MISP.default_attribute_distribution` settings. Instead the distribution is always set to 0 (Organization Only).

When the event/attribute data goes through the [save function](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2638) no `distribution` fields are present but when it arrives at [beforeValidate](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L388) they are set to 0.

MISP Objects have their distribution set to 5 (inherit) explicitly in the JSON output of stix2misp and are created accordingly (due to [PyMISP](https://github.com/MISP/PyMISP/blob/master/pymisp/mispevent.py#L929)).

**Comment by chrisr3d** [comment]
Thank you for your feedback, I updated the import part to have both `MISP.default_event_distribution` and `MISP.default_attribute_distribution` as parameters of the python script, and set the distribution values for event, objects and attributes accordingly
