### ISSUE TITLE
chcon: can't apply partial context to unlabeled file 

### ISSUE THREAD

**Issue by PurePackets** [MISP/MISP#3374]
I have problem to allow SELINUX permission :
I am following from : https://github.com/MISP/MISP/blob/2.4/INSTALL/xINSTALL.centos7.txt

[root@mirror Config]# chcon -t httpd_sys_rw_content_t /var/www/MISP/app/files
chcon: can't apply partial context to unlabeled file '/var/www/MISP/app/files'

OS version (server) : CENTOS7

 OS version (client)  : git 22 june

**Comment by PurePackets** [comment]
[root@mirror ~]# ls -lZ /var/www/MISP/app/files                                 -rw-r----- root   apache ?                                empty
drwxr-x--- root   apache ?                                feed-metadata
drwxr-x--- root   apache ?                                misp-galaxy
drwxr-x--- root   apache ?                                misp-objects
drwxr-x--- root   apache ?                                noticelists
drwxr-x--- root   apache ?                                scripts
drwxr-x--- root   apache ?                                taxonomies
drwxr-x--- apache apache ?                                terms
drwxr-x--- root   apache ?                                warninglists

**Comment by PurePackets** [comment]
Ok problem resolved but how ?!
By default SELINUX disabled , and in installation doc dint say to enable it before set seliux permission : 
 # nano /etc/sysconfig/selinux
and set to SELINUX TO enforcing . 
SELINUX=enforcing
now running chcon command to set permission ....

**Comment by adulau** [comment]
For my understanding, which installation documentation are you talking about? Thank you

**Comment by SteveClement** [comment]
As the initial requestor noticed, SELinux was disabled.
