### ISSUE TITLE
Impossible to modify the config on IE11

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3375]
Double clicking on the fields to change a value doesn't do anything on IE11.

**Comment by RichieB2B** [comment]
I know you must be asking for a friend.. but IE11 is hardly usable on the web these days. Please let it die..

**Comment by SteveClement** [comment]
IE11 has a 9-11% market share atm, very approximate guesstimate.

https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer

**Is Internet Explorer 11 the last version of Internet Explorer?**
Yes, Internet Explorer 11 is the last major version of Internet Explorer. Internet Explorer 11 will continue receiving security updates and technical support for the lifecycle of the version of Windows on which it is installed.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
