### ISSUE TITLE
STIX download:  internal error has occured after update to 2.4.92

### ISSUE THREAD

**Issue by kanocool** [MISP/MISP#3376]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | ubuntu 16.04.4 
| OS version (client)       | windows
| PHP version               | 7.0
| MISP version / git hash   | 2.4.92
| Browser                   | If applicable

pymisp:… OK
pydeep:… OK
magic:… OK
lief:… OK
STIX and Cybox libraries

STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
maec: 4.1.0.13
PyMISP: >2.4.92

Other versions might work but are not tested / recommended.
Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
PYMISP library version…OK

### Expected behavior
When using the curl with authentication link or browser link to download events as stix output.

https://<MISP_link>/events/stix/download/XXXX

### Actual behavior
Internal error

### Steps to reproduce the behavior
update to2.4.92

### Logs, screenshots, configuration dump, ...
**error.log**
2018-06-25 13:37:25 Error: [Exception]
Request URL: /events/stix/download/XXXX
Stack Trace:
#0 [internal function]: EventsController->stix('download', 'XXXX')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

---
Looks like and issue with cakephp, however I'm not sure where the issue  can be found.

**Comment by imereau** [comment]
Exact same issue here.

**Comment by iglocska** [comment]
Ping @chrisr3d

**Comment by kanocool** [comment]
Found extra logging information after doing a pull this morning. 
when i want to stix/download it populates the following log with the stacktrace below.
**Exec-error.log**

 File "/var/www/MISP/app/files/scripts/misp2stix.py", line 1579, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 1574, in main
    stix_builder.generateEventPackage()
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 180, in generateEventPackage
    incident = self.generate_stix_objects()
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 234, in generate_stix_objects
    self.resolve_objects2parse(incident, Tags)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 313, in resolve_objects2parse
    for uuid, file_object in self.objects2parse['file'].items():
AttributeError: 'StixBuilder' object has no attribute 'objects2parse'

**Comment by chrisr3d** [comment]
Thanks for this additional information, I just found the same, but was afraid it was something else
I'll update it in a few minutes

**Comment by chrisr3d** [comment]
Pushed the update, it is working for me on the latest VM, but let me know if you still have an issue with this.

**Comment by kanocool** [comment]
Just tested it, and it works again! 

Thanks for the quick action your part :)

**Comment by iglocska** [comment]
Thanks for the quick resolution @chrisr3d  and the quick feedback @kanocool :)

**Comment by chrisr3d** [comment]
Yep, you're welcome ;-)
