### ISSUE TITLE
STIX or CyBox library not installed correctly (former #1669), 

### ISSUE THREAD

**Issue by HJBond** [MISP/MISP#3377]
AWS instance running UBUNTU 16.04

| Questions                 | Answers
|---------------------------|--------------------
| Diagnostics tab: (1) STIX or CyBox library not installed correctly;
Advanced attachment handler
(2) The advanced attachment tools are used by the add attachment functionality to extract additional data about the uploaded sample.
pymisp:… Please install pymisp: pip install pymisp
pydeep:… Please install pydeep: pip install git+https://github.com/kbandla/pydeep.git
magic:… Please install python-magic: pip install python-magic.
lief:… Please install lief, documentation here: https://github.com/lief-project/LIEF;
and (3) ZeroMQ settings…Python ZeroMQ library not installed correctly.

| OS version (Ubuntu 16.04)       
| OS version (Win 7)      
| PHP version          7.0.30    
| MISP version / git hash  2.4.91 
![logs](https://user-images.githubusercontent.com/40573007/41861997-5b4a8794-7868-11e8-9107-eb9d2af2e91c.JPG)

(1) I followed installation instructions from https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt 
No errors popped up during the install. Seemed fine.  Obviously, it's not according to diagnostics and logs (40573007/41861997-5b4a8794-7868-11e8-9107-eb9d2af2e91c.JPG)

For pymisp/pydeep/magic/and lief install was successful not sure what else to do here.
![pydeep](https://user-images.githubusercontent.com/40573007/41862278-1174680a-7869-11e8-85de-eecd5bde88ed.JPG)

![pymisp](https://user-images.githubusercontent.com/40573007/41862370-48d35c34-7869-11e8-81d8-a0dd2ccbbac3.JPG)

for magic used pip install python-magic

**Comment by HJBond** [comment]
oops... hit submit too soon... part 2 of 2

![magic](https://user-images.githubusercontent.com/40573007/41862503-adf602ce-7869-11e8-9cf4-ed8419149886.JPG)

lief: pip install lieft
![lief](https://user-images.githubusercontent.com/40573007/41862532-c7cc4866-7869-11e8-8ca5-321d92269eaa.JPG)

ZeroMQ: pip install pymzq
![pymzq](https://user-images.githubusercontent.com/40573007/41862645-261e47ac-786a-11e8-8921-f980138ddb8a.JPG)
![pymzq redis](https://user-images.githubusercontent.com/40573007/41862696-49203f94-786a-11e8-8858-d3295869f39f.JPG)

rookie at this type of stuff. Any suggestions welcomed...

**Comment by SteveClement** [comment]
@HJBond please double check your install, follow the procedures perhaps again.

**Comment by Andraaada** [comment]
I had the same problem with the cybox and stix libraries. 
You should go and check in the below folder to see to which version it points.   
cd /var/www/MISP/app/files/scripts/
python3 stixtest.py

I uninstalled all the libraries with pip3 till it pointed out to no version and then reinstalled.
cd /var/www/MISP/app/files/scripts/
rm -rf python-cybox
rm -rf python-stix

sudo -u www-data -H git clone https://github.com/CybOXProject/python-cybox.git
cd /var/www/MISP/app/files/scripts/python-cybox 
python3 setup.py install --record file-to-record-param.txt
pip3 install stix
pip3 install pymisp

**Comment by SteveClement** [comment]
Thanks @Andraaada 
That is indeed one way to see if things are going well or not.

@HJBond if this did not solve your issue, feel free to re-open.

**Comment by smclinden** [comment]
This appears to be a problem with the scripted install. It installs the python libraries in the venv/ Python but MISP appears to be using the system Python3.

Apparently this fix (Issue #3703) is not in the current Git.
