### ISSUE TITLE
Push Events from List Servers ignores rules

### ISSUE THREAD

**Issue by uiucseclab** [MISP/MISP#3378]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.92

### Expected behavior

When "push all" is pressed on list servers, it pushes all pending events that match the rules

### Actual behavior

It sends everything

**Comment by uiucseclab** [comment]
Crap, sorry this is John Bambenek, logged into the wrong github account :(

**Comment by iglocska** [comment]
Hello there John! 

Tried to reproduce it and could only partially reproduce it, so let's see if it covers what you ran into.

What I tried:

Create 3 events
```
Event1:
  tags: []
  Attributes: [
    {tags:[]}
  ]
Event2:
  tags["push"],
  Attributes:[
    {tags:["block"]},
    {tags:["push"]}
  ]
Event3:
  tags["block"],
  Attributes:[
    {tags:["block"]},
    {tags:["push"]}
  ]
```

Then I added the following tag filters: allow: "push", block "block"

The result was that only event 2 got synchronised, however, during a full push it included both attributes, which is clearly wrong. I've pushed an update that fixes this and brings it in-line with the normal publishing push.

Is this what you found too, or did you actually get an unauthorised event pushed? If so can you describe the filter rules and the applied tags / organisation restrictions?

**Comment by uiucseclab** [comment]
Figured it out… had overbroad rules… ☹

Now using an internal only tag that I don’t export to flag things we’re going to share out… now that I figured it out, will start shoving things into CW and CIRCL MISPs 😊
