### ISSUE TITLE
restSearch with timestamp (modified event) doesn't work with interval

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3379]
To reproduce:

```python
response = misp.search(timestamp=['5d', '1d'])
print(response)  # <--- Always empty 

events = []
for event in response['response']:
    me = MISPEvent()
    me.load(event)
    events.append(me)

for e in events:
    print(e)
```

HTTP debug:
```
POST - http://127.0.0.1:8080/events/restSearch/download
{"timestamp": ["5d", "1d"]}
```

**Comment by SteveClement** [comment]
@Rafiot this worked in my latest test.
I suppose @iglocska fixed it :)
Please re-open if still an issue.

Tested on: https://github.com/MISP/PyMISP/commit/8f0bbab6e1a1e1f3d9672020b5fb81159d7b35ec
MISP/https://github.com/MISP/MISP/commit/94bce3688a4f7fa1cbb731926cf00115740e4eca
