### ISSUE TITLE
Sharing groups not synced correctly

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#3380]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | ubuntu 16.04
| OS version (client)       | 10
| PHP version               | 7.0.3
| MISP version / git hash   | 2.4.92, 8ee5b37886df97c37f2e8a7c1fb205dfd51efbe9
| Browser                   | Firefox

### Expected behavior
Sharing groups stay the same when shared via internal instances.

### Actual behavior
We received an event via a sharing group to one of our MISPs. That sharing group got the sharing-group-ID 5.
That event is then shared to our second MISP (internal instance, same organisation), but the sharing group changed. On our second MISP, we now see another of our sharing groups. That one has also the ID 5.

For example:
MISP 1: 
Sharing group A - ID 1
Sharing group B - ID 2
...

MISP 2:
Sharing group X - ID 1
Sharing group Y - ID 2
...

Event with sharing group A (ID 1) is shared form MISP 1 to MISP 2, and the sharing group changed to X (also ID 1).

Is there a way to sync the sharing groups correctly?

### Steps to reproduce the behavior
Take two MISP (internal instances) with different sharing groups and sharing group IDs. Share an Event via a sharing group and compare them.

Best regards

**Comment by iglocska** [comment]
I don't seem to be able to reproduce this under normal conditions. What I've tried:

1. Two MISP instances, MISP1, MISP2
2. MISP1 and MISP2 are run by two organisations (ORG1, ORG2)
3. New sharing group -  SG1 - created on MISP1: includes MISP1, MISP2, ORG1, ORG2
4. ID of sharing group on MISP1 is "2". MISP2 already has a differnet sharing group with the ID "2"
5. ORG1 on MISP1 creates an event EVENT1 and sets the distribution as SG1
6. EVENT1 is published and pushed to MISP2
7. MISP2 gets a new sharing group SG1 at ID "5" (the next free ID)
8. EVENT1 on MISP2 gets SG1 via ID 5


Repeated the same scenario in a pull and it worked fine


Now my question here is - could you check if your sync user has sharing group editor rights? I can't think of anything else that could go wrong (if that's the case it's still a bug but I at least know where to look)

**Comment by Kahuna01** [comment]
Thanks for your answer!
In our case MISP 1 and MISP 2 are both run by our organisation, so are internal instances.
And yes, the sync user has sharing group editor rights.

When we first received the event from an external MISP (MISP 0 if you want), everything was fine too and the new received sharing groups are added with a new ID.
Just the sharing from one internal instance to another was buggy.

**Comment by iglocska** [comment]
Ah interesting. So it's an issue with the internal sync, will have another
look if I can reproduce it!

**Comment by iglocska** [comment]
Was it a push or a pull btw?

**Comment by Kahuna01** [comment]
Between the two internal instances I pulled in manually via "List Servers" --> "Pull all".

**Comment by iglocska** [comment]
Thanks, that should make debugging easier! :)

**Comment by adulau** [comment]
@iglocska can we close it?

**Comment by SteveClement** [comment]
@iglocska bump

**Comment by iglocska** [comment]
Not yet, there is probably something wrong going on, seen another report for something similar.

**Comment by Kahuna01** [comment]
I guess I found out what was wrong.
"Our" Organisation in the new sharing group had a wrong uuid. We tested it again with the right uuid and in went as how it was supposed to be. 
Should have checked that one earlier...
