### ISSUE TITLE
Freetext import fails to detect IPv6 in long form

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3383]
Detected: fe80::f2cd:7d80:3f37:52c6
Not detected: fe80:0000:f2cd:7d80:3f37:52c6

**Comment by iglocska** [comment]
Sounds like it's correct, that is indeed not a valid ipv6 address.

**Comment by iglocska** [comment]
For posterity, try fe80:0000:0000:0000:f2cd:7d80:3f37:52c6
