### ISSUE TITLE
Propose delete broken on file object level (or more)

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3385]
On the latest MISP VM, after adding an attachment, proposing a delete within a file object does not work.

The 'Yes' dialog is not responding.

 Currently installed version… v2.4.93 (77e5b7a3b195dbf4d9c87ef60f913e9c4882749c)

**Comment by Mudamara** [comment]
Hello, has this been resolved in a later version? I am having the same issue in version 2.4.94. I am unable to either soft delete nor propose delete for any attribute. 
Pressing either button simply does nothing.

I have tried this as multiple user types and from multiple different account types

**Comment by iglocska** [comment]
Confirmed, will have a look at this soon

**Comment by Mudamara** [comment]
Awesome, many thanks

**Comment by angarod** [comment]
Same problem here

**Comment by Sp-TT** [comment]
Hi Team, is this still an unsolved problem? there is no response when i proposed to delete attribute on object level
