### ISSUE TITLE
mi

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3386]

**Comment by adulau** [comment]
The error message is pretty clear:

`Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.`

As mentioned in the documentation:

https://www.circl.lu/doc/misp/automation/#automation-key

Cheers

**Comment by shimi199393** [comment]
I know the curl but i need to move the auth key in url . Sourcefire ips get
feed in url . You have soloution for this ?
Thanks

בתאריך יום ד׳, 27 ביוני 2018, 10:49, מאת Alexandre Dulaunoy ‏<
notifications@github.com>:

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/81c0fc2279583fccac879d302039c8b6f110f9ae 

We hope this helps.

**Comment by shimi199393** [comment]
Hi , how i can to serve the api with the attributes that i export in the
browser instead download the file (txt file) i try to change the apache and
.htaccess and is not work . I believe that the problem in code of misp.
Example :
https:///attributes/text/download/domain
Thank you
Ubuntu 16.04

בתאריך יום ד׳, 27 ביוני 2018, 17:40, מאת Alexandre Dulaunoy ‏<
notifications@github.com>:
