### ISSUE TITLE
MITRE ATT&CK matrix - UI issues

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3389]
The ATT&CK matrix is really cool, however it has some downsides:
- the user needs a large screen resolution, screens with 1600x900 are not sufficient to show the whole matrix, nor the submit button. Today, more than half of the screens have a height of 900 or less pixels.

- the submit button is really not on a natural place, nor is it consistent with the UI behavior of the other windows. My proposal is to move it back to the bottom next/above to the Cancel button.

**Comment by adulau** [comment]
Good point. It will be changed.

**Comment by adulau** [comment]
@cvandeplas it should be for the next 2.4.94.

**Comment by adulau** [comment]
@cvandeplas Could you check if the recent pull-request #3410 solved it? Thank you

**Comment by mokaddem** [comment]
If you have other suggestions or see other improvement, please, feel free to also share them.
Thanks!
