### ISSUE TITLE
Multiple communities on the same instance

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#339]
I would be nice to be capable of handling multiple communities on the same MISP instance.

The idea is the following, you create a specific role "super super admin" where the user can control the value of the community. By default, the value 0 is the standard community (how it works now). Each community cannot see others and are just synchronized like being remote. Users are attached to one or another community.

This would help organization that need segregation of MISP communities but keep the administration to a minimal level.

Let me know what you think.

**Comment by PakitoSec** [comment]
sorry to post on a closed issue, but is it possible in version 2.4 to have multiple communities on the same misp instance ? we would need a segregation on our misp instance. 
use case: have 2 events with same uuid which belong to 2 differents orgs... how to do that ?
