### ISSUE TITLE
possible to get users.email in error.log output

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3392]
is there a way to change what is logged to MISP/app/tmp/logs/error.log (perhaps ala Apache httpd LogFormat directive)?

e.g. would be helpful to have the users.email to trace what user transaction may have triggered an error.

**Comment by iglocska** [comment]
Definitely not possible. Not all of the executed code that can generate an
exception is aware of what the currently authenticated user is.

**Comment by github-germ** [comment]
had a feeling, but thought i'd ask. we had a similar issue in an in-house system we built, but did find a way to pass the user down thru the layers. thx for your reply.

closing since not possible.
