### ISSUE TITLE
Int

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3393]

**Comment by RichieB2B** [comment]
We can try to port it to Visual Basic?

**Comment by shimi199393** [comment]
What is virtual basic ?

בתאריך יום ה׳, 28 ביוני 2018, 08:03, מאת Richie B2B ‏<
notifications@github.com>:

**Comment by iglocska** [comment]
https://github.com/stricaud/TA-misp

https://github.com/remg427/misp42splunk

**Comment by ShimiCohen** [comment]
I know this introduction but the splunk need python 3 ? Or i can in python 2.7?
