### ISSUE TITLE
MITRE ATT&CK matrix Issue

### ISSUE THREAD

**Issue by SivaPrem** [MISP/MISP#3395]
Hello Team 

Thanks for integrating the Mitre Attack matrix , I did the update to the latest version v2.4.93  , The update was good and from the Diagnostics I can see its now upgraded to the latest version 

But surprisingly i couldn't find the attack matrix  in the GUI loaded !!! and I have only the option ATTACK Matrix which is empty only with sown bar / icon

Am I missing something for the updates 

Can you please guide me !!!

I have attached some Screen shots for your understanding 

![image](https://user-images.githubusercontent.com/3869254/42026716-2f27c8ea-7ac8-11e8-85ac-db86480d49b4.png)

![image](https://user-images.githubusercontent.com/3869254/42026819-69abbe9a-7ac8-11e8-8b9f-39984ba93a3d.png)

**Comment by mokaddem** [comment]
Hello! Thanks for your feedback.
Can you check that you have the galaxy ``Enterprise Attack - Attack Pattern galaxy`` on your MISP?
If not, can you pull and update your galaxies then, try again?

**Comment by SivaPrem** [comment]
@mokaddem : Hello !!! Thank you very much , I updated the galaxies and its working fine now

Thank you very much !!!!

**Comment by SivaPrem** [comment]
@mokaddem : The submit button has some inconsistency with the GUI  !!! may it can pushed next to cancel button !!!! Did someone report or experience the same issue  ??

**Comment by mokaddem** [comment]
The layout of the ATT&CK matrix is being reworked a bit. It will be better for the next released.
Thanks for the report anyway.

**Comment by adulau** [comment]
This has been fixed in 906bbd873a8dceb15624acd9015ec11fca21ec2c
