### ISSUE TITLE
Bu

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3406]

**Comment by SteveClement** [comment]
@shimi199393 are you using the VM or your own setup? Double check the following:
In : servers/serverSettings/Security
What value is: Session.autoRegenerate ?

If this is set you will be logged out after X requests.

On all my setups this behaviour is not reproducible.

**Comment by shimi199393** [comment]
This clean setup and its 2 misp . You try this ?

בתאריך יום ו׳, 29 ביוני 2018, 06:08, מאת Steve Clement ‏<
notifications@github.com>:
