### ISSUE TITLE
Se

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3407]

**Comment by SteveClement** [comment]
You want to be more specific on which server you enable your proxy.
It looks like your proxy is not considering the requests you make.
This is likely an issue with your Setup and not with MISP.

**Comment by shimi199393** [comment]
You can explain how to set this ? I have 2 misp . Misp A 2 interface ;
172.16.10.57
192.168.179.193
Misp B 1 interface ;
172.16.11.65
And i need to set proxy misp B:
Proxy address : 172.16.8.105
The proxy have access to network and he communicate with 2 misp in port
8080.
Thanks

בתאריך יום ו׳, 29 ביוני 2018, 06:32, מאת Steve Clement ‏<
notifications@github.com>:

**Comment by iglocska** [comment]
This has since been fixed by adding a new flag to server connections to avoid using a proxy.
