### ISSUE TITLE
cake CLI - setSettings for "Session.autoRegenerate"

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3408]
Setting Session.autoRegenerate via the CLI with the boolean keyword "false" does not get considered.

This will NOT work:

$PATH_TO_MISP/app/Console/cake Admin _getSetting_ "Session.autoRegenerate"
$PATH_TO_MISP/app/Console/cake Admin _setSetting_ "Session.autoRegenerate" **false**
$PATH_TO_MISP/app/Console/cake Admin _getSetting_ "Session.autoRegenerate"

This WILL work:
$PATH_TO_MISP/app/Console/cake Admin _setSetting_ "Session.autoRegenerate" 0

This is an inconsistency considering in other places this works fine.

**Comment by iglocska** [comment]
false, entered as a parameter, is actually "false" internally so it will not work by default. Added some logic to capture the strings though and convert them.
