### ISSUE TITLE
MISP API  GET events/index what is the limit?

### ISSUE THREAD

**Issue by Andraaada** [MISP/MISP#3411]
I have a question related to events/index limit. In the documentation is written that it is limited, but there is not mentioned any number. Can you tell what is the limit for the returned events?

Many thanks!

**Comment by SteveClement** [comment]
@Andraaada I have 60 in my memory, checking to make sure…

**Comment by iglocska** [comment]
There is no limit via the API, via the UI the default is 60. You can change that by passing the "limit" parameter.

`/events/index/limit:200/page:3`

Would be events 401->600.

**Comment by Andraaada** [comment]
Thank you very much Steve and Andras for the information. Really helpful for us.
