### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by samuelcardillo** [MISP/MISP#3414]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       | Mac OS X, Windows, ...
| PHP version               | 5.6
| MISP version / git hash   | 2.4
| Browser                   | Google Chrome, Firefox, ..

### Expected behavior
Show page correctly

### Actual behavior
Display two errors : 
1. **Undefined variable: me [APP/View/Layouts/default.ctp, line 18]**
2. **Fatal error: Can't use function return value in write context in /var/www/MISP/app/View/Elements/global_menu.ctp on line 93**

### Logs, screenshots, configuration dump, ...
[Screenshot](https://image.noelshack.com/fichiers/2018/26/5/1530273287-capture-d-ecran-2018-06-29-a-12-53-57.png)

**Comment by SteveClement** [comment]
@samuelcardillo can you please share the output of

/var/www/MISP/app/tmp/logs/ (Whatever changes there and looks like an error)
And maybe you web server log if something other/interesting is in there.
Did you follow our CentOS guide?
Centos 6 or 7?

**Comment by SteveClement** [comment]
@samuelcardillo let us know if this is still an issue.

**Comment by samuelcardillo** [comment]
Apologies for my super delayed answer and thanks for yours! The problem is sadly persisting. The server where MISP is being installed is using CentOS 7 and, yes, we used the guide but it seems that something went wrong somewhere. 

I went in the directory indicated where I have found `error.log` , `debug.log`. 

The `error.log` is showing this repeatedly : 
```
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(64, 'Can't use funct...', '/var/www/MISP/a...', 336)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't use funct...', '/var/www/MISP/a...', 336, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 64, 'Can't use funct...', '/var/www/MISP/a...', 336, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

While `debug.log` is showing an error about an undefined variable : 
```
Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 18]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 18
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
call_user_func - [internal], line ??
ErrorHandler::handleFatalError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 269
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 212
call_user_func - [internal], line ??
App::_checkFatalError() - APP/Lib/cakephp/lib/Cake/Core/App.php, line 970
App::shutdown() - APP/Lib/cakephp/lib/Cake/Core/App.php, line 943
[main] - [internal], line ??
```

The web server is not showing anything important. Maybe it is worth mentioning that before MISP was installed, NGINX was really installed  but without PHP support so I am pretty sure it could not have impacted CakePHP and so on but still felt like saying it. 

I am really lost at what is going on and if you have any ideas, that would be super great! Thanks in advance

**Comment by iglocska** [comment]
Are you sure you are using php 7 via scl there? 

`Can't use funct...`

That part looks fishy, i have a feeling that the full message would be:

`can't use function return value in write context` which is an indication that your misp is being run via php 5.3 (the default on centos7 and not compatible with misp). Make sure you double check the steps in the install guide that deal with scl and name sure that your space config is actually using it.

**Comment by samuelcardillo** [comment]
We went from PHP 5.6 to PHP 7 using SCL and adapted our DocumentRoot (we went from accessing it from a domain name to raw IP) and it appear that it solved the initial problem, showing the login page but once logging in with the default account it goes in a redirection loop from `/users/change_pw` which gets stopped by Chrome. Neither the `debug.log` or `error.log` show anything. Completely lost here :(

**Comment by shubb30** [comment]
@samuelcardillo Did you ever resolve this?  I am having the same redirect-after-login issue to /users/change_pw on my new install also.
