### ISSUE TITLE
MISP on AWS EC2 community image

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#3415]
So I've installed the AWS ec2 MISP community image

Will I run into any issues if I use this for production?

I'm new to MISP and AWS so I'm totally noobie

Thank you

**Comment by SteveClement** [comment]
Dear @casper628616 join the @MISP/misp-cloud Gitter chat: https://gitter.im/MISP/misp-cloud

You can discuss there with ppl :)

In theory if your Security Groups are set-up correctly, and you do not use a know user/pass , you will be ok.

**Comment by ghost** [comment]
thank you @SteveClement
