### ISSUE TITLE
"Sync User For" Option is not clear

### ISSUE THREAD

**Issue by felixpk** [MISP/MISP#3416]
I have a question regarding the "Sync User for" option when creating a SyncUser.

There seems to be no benefit in assigning the SyncServer to the SyncUser.
Other than that: For a one-directional share, let's say **Instance A** has a SyncServer and **Instance B** has the SyncUser. In this szenario the SyncUser cannot be bound to any server, because the instance just has no SyncServer.
Only in the szenario of a bidirectional share between **Instance A** and **Instance B** there will be a SyncUser and at the same time a SyncServer on the same instance. 

Since I already set up a working example of instance-synchronization, I am just wondering what this setting does.

**Comment by iglocska** [comment]
Basically consider this scenario: You (user of org_a) add a sync server on your instance (misp_a) to a partner's (org_b) instance (misp_b) in bi-directional mode (so you and the admin of misp_b both create users for one another).

You do not wish to push anything tlp:red or tlp:amber to misp_b, so you set those filters up. All events with the given tlp tags are no longer being pushed.

Then the site admin admin of misp_b (org_b) logs into their instance and initiates a pull - at which point the sync user of org_b on your instance starts fetching data for misp_b. The sync user of org_b does not know about the tlp restrictions and returns everything unfiltered, even the events that correctly never got pushed.

However, if you'd enforce the sync server rules on the sync user by making the sync user a sync user for misp_b, the push rules would be adhered to when the remote initiates a pull.

Hope this made it clear!
