### ISSUE TITLE
checkIfLoggedIn

### ISSUE THREAD

**Issue by randomname13** [MISP/MISP#3418]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | checkIfLoggedIn frequently logs out the user
| OS version (server)       |  ubuntu
| OS version (client)       | 14.04, 16.04
| PHP version               | 5,7
| MISP version / git hash   | 2.4.93, cc12a4a2fb375a2aac0258ad55bf7bef79c3caee
| Browser                   | FF, Chrome

### Expected behavior
Creating events, adding attributes, adding tags..

### Actual behavior
We have seen, that you have implemented a new function called checkIfLoggedIn. This logs out our users randomly. For example, if you create an event, add an attribute or even a tag you flip back to the main page or you will be logged out. 
Everything is behind a WAF. We haven't tested it without a WAF.

**Comment by iglocska** [comment]
Could you check if your Session.autoregenerate setting is set in administration -> server settings -> security?

**Comment by adulau** [comment]
Could you update to the latest version 8559af8c6a4d5b7220b046fe933722cf46aa81a3 ? This fixed various issues with the sessions.

**Comment by randomname13** [comment]
Session.autoRegenerate is false.
We have updated it no to the newest version. We will see how it works, thanks

**Comment by adulau** [comment]
@randomname13 Thank you. Let us know. I'll close the issue. Feel free to reopen if the issue persists.

**Comment by randomname13** [comment]
all right, thanks.
