### ISSUE TITLE
500 error when "perform on existing" for rexexp

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#3419]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Stretch
| PHP version               | 7.0
| MISP version / git hash   | 2.4.93
| Browser                   | Chrome

### Expected behavior
Apply regular expressions

### Actual behavior
500 error
https://<machine>/admin/regexp/clean

### Steps to reproduce the behavior
Go to Input filters -> import regexp -> click "perform on exsisting"

### Logs, screenshots, configuration dump, ...
![screenshot from 2018-06-30 03-48-22](https://user-images.githubusercontent.com/947191/42123993-b35c6be2-7c18-11e8-8867-969731f8f044.png)
![peek 2018-06-30 03-47](https://user-images.githubusercontent.com/947191/42124005-df9d992e-7c18-11e8-8dcc-a1d87ea445d0.gif)

**Comment by SteveClement** [comment]
It works in my dev environment with latest code.

Check:
/var/www/MISP/app/tmp/logs

The error 500 should be logged there somewhere, or perhaps in your server log.

**Comment by iglocska** [comment]
Bug is confirmed, tested it and it tries to load all attributes in one shot.

**Comment by DigiAngel** [comment]
Here we go:
~~~
[Sun Jul 01 08:49:02.376237 2018] [:error] [pid 5974] [client 192.168.1.2:45372] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 280, referer: https://sandbox/admin/regexp/index
[Sun Jul 01 08:49:02.387416 2018] [:error] [pid 5974] [client 192.168.1.2:45372] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Hash.php on line 65, referer: https://sandbox/admin/regexp/index
[Sun Jul 01 08:51:09.921151 2018] [:error] [pid 5973] [client 192.168.1.2:45384] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 48250880 bytes) in /var/www/MISP/app/View/Elements/eventattribute.ctp on line 216, referer: https://sandbox/events/view/386
[Sun Jul 01 08:51:36.595536 2018] [:error] [pid 2450] [client 192.168.1.2:45392] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 55844168 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php on line 974, referer: https://sandbox/events/view/386
~~~

**Comment by iglocska** [comment]
This should be fixed now, but expect to raise the execution time as it's a slow process.

**Comment by DigiAngel** [comment]
Confirmed working thank you.
