### ISSUE TITLE
'/regexp/admin_index/page:2' not found

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#3420]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Stretch
| PHP version               | 7.0
| MISP version / git hash   | 2.4.93
| Browser                   | Chrome

### Expected behavior
Get to the second page of imported regexp

### Actual behavior
'/regexp/admin_index/page:2' not found

### Steps to reproduce the behavior
Go to input filters -> import regexp -> click the 2 or >> icon

### Logs, screenshots, configuration dump, ...
![peek 2018-06-30 03-46](https://user-images.githubusercontent.com/947191/42124032-3997c102-7c19-11e8-9440-88db0c6c57fb.gif)

**Comment by SteveClement** [comment]
Looking into it, bug confirmed.

**Comment by DigiAngel** [comment]
Appreciate it Steve...here's some log info now that I know where to look for it:
~~~
2018-06-23 05:56:04 Error: [PrivateActionException] Private Action RegexpController::admin_index() is not directly accessible.
Exception Attributes: array (
  'controller' => 'RegexpController',
  'action' => 'admin_index',
)
Request URL: /regexp/admin_index/page:2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(RegexpController), Object(CakeRequest))
#2 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-06-23 05:56:16 Error: [PrivateActionException] Private Action RegexpController::admin_index() is not directly accessible.
Exception Attributes: array (
  'controller' => 'RegexpController',
  'action' => 'admin_index',
)
Request URL: /regexp/admin_index/page:2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(RegexpController), Object(CakeRequest))
#2 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
~~~

**Comment by iglocska** [comment]
This should be fixed now. Thanks for the heads-up!

**Comment by DigiAngel** [comment]
Confirming fixed...really appreciate the fast work on this..thank you!
