### ISSUE TITLE
After upgrade version 2.4.93, restapi version always 2.4.92

### ISSUE THREAD

**Issue by rmkml** [MISP/MISP#3421]
Hello,
Thx for greats products and greats features!
Could you check restapi version always 2.4.92 after upgrade to 2.4.93 ?
Best Regards
@Rmkml

**Comment by adulau** [comment]
Fixed in e8d8d80aba771bf5c99e4d8904b1ee61f9b3dec1 and PyMISP has been released as 2.4.93

Thank you.
