### ISSUE TITLE
ATT&CK matrix usage

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3423]
I just upgraded my instance to 2.4.93, updated galaxies too.
I can see the matrix but:
- Can't select elements in the matrix
- No "Submit" button displayed
(I compared with the blog's video ;-)
Any idea?

**Comment by SteveClement** [comment]
There is currently a bug being discussed in Gitter, this might relate. @iglocska will let us know once fixed.

**Comment by iglocska** [comment]
That is not related. The one on gitter has to do with incorrect namespacing on galaxies and the attack matrix not having any elements.

**Comment by iglocska** [comment]
@xme do you see anyhting funky in your browsers dev console?

**Comment by iglocska** [comment]
Also, it looks like the submit button moved to the bottom of the screen, just above the cancel button ;)

**Comment by xme** [comment]
Nothing fancy in the web console...
And no button at all (cfr pic)
<img width="1513" alt="screen shot 2018-07-02 at 13 10 03" src="https://user-images.githubusercontent.com/480944/42160959-61ccda90-7df9-11e8-8b7e-144d8685f90b.png">

**Comment by adulau** [comment]
This is the view only. To add an att&ck technique, you need to add a galaxy via the add galaxy ;-)

**Comment by xme** [comment]
OMG! Found it now... Tx! ;)

**Comment by adulau** [comment]
@xme It's good feedback. We might refactor a bit the UI to avoid the confusion ;-)

**Comment by iglocska** [comment]
Yeah, we just got the exact same feedback a few minutes ago on gitter from another experienced community member - definitely something we should address! :)
