### ISSUE TITLE
Manual / Self Created Warning Lists label:"feature request" 

### ISSUE THREAD

**Issue by Glhenn** [MISP/MISP#3425]
What's the chance of being able to create your own warning lists? Can see a use for listing your own infrastructure, or keeping static lists of things.

**Comment by iglocska** [comment]
You absolutely can. Just create a JSON file in the same format, drop it in the warninglist directory and then in MISP click on update warninglsits - it will read it from the local file. Loads of organisations already use this.

**Comment by SteveClement** [comment]
@Glhenn feel free to reopen, or even better join our Gitter Channel: https://gitter.im/MISP/MISP
To get more details.

**Comment by otgrkiss** [comment]
+1
