### ISSUE TITLE
git branch empty

### ISSUE THREAD

**Issue by liedekef** [MISP/MISP#3428]
While in the backend, when clicking on the diagnostics, I'm seeing:
Status…	Outdated version
Current branch…

So the branch is empty. I followed the EL6 (and 7) docs to get misp from git, and doing a git status I'm getting:

```
# Not currently on any branch.
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   app/composer.json
#
no changes added to commit (use "git add" and/or "git commit -a")
```
Git branch tells me:
```
* (no branch)
  2.4
```
So it seems I'm on no branch at all (while I did exactly as said in step 3.01 in https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt )
Doing a git checkout origin 2.4, I'm getting:
```$ git checkout 2.4
error: You have local changes to 'INSTALL/INSTALL.FreeBSD.txt'; cannot switch branches.
```
git status and git diff shows lots of files changed/deleted (probably due to the install of extra modules mentioned in the doc ...)
So I'm a bit lost here ... the only thing this is useful for is to be able to click "update" in the diagnostics backend of course, but it seems I'm not that good in git :-)
Could I have a clue on how to switch to branch 2.4 ?

**Comment by liedekef** [comment]
Or maybe an option in misp to tell that I'm on 2.4, so it doesn't rely on git commands to detect the branch ...

**Comment by RichieB2B** [comment]
Try:
```
git checkout 2.4
```

**Comment by liedekef** [comment]
Result from `git checkout 2.4` :
`error: You have local changes to 'INSTALL/INSTALL.FreeBSD.txt'; cannot switch branches.
`

**Comment by RichieB2B** [comment]
We have a FreeBSD install file? 🙃 Try:
```
git stash
git checkout 2.4
```

**Comment by liedekef** [comment]
Ok, after "git stash save", I needed to remove some files apparently untracked (???), then I could do git checkout and "git stash pop", after which I needed to reset some files again. Now things seem ok (allbeit after some struggling), but now this pops up in the admin interface when clicking the update:
```

git submodule update --init --recursive 2>&1

You need to run this command from the toplevel of the working tree.
```
I'm guessing that a cd-command is missing in app/Model/Server.php in the update function, before each git-command (and maybe before every git-command in that file).

**Comment by RichieB2B** [comment]
MISP is telling you to run the git command by hand. After that things should be better.

**Comment by liedekef** [comment]
I did that, but in the webinterface the output stays the same when clicking on "update". The main update seems to be ok, but for the submodules it is not working.

**Comment by RichieB2B** [comment]
Can you paste the output of:
```
git submodule update --init --recursive
```

**Comment by liedekef** [comment]
Well ... I ran it this morning and it updated some stuff, but of course now no more updates, so the command returns empty

**Comment by RichieB2B** [comment]
That is the correct output for no updates. Still wondering why the update button in the UI thinks there is something wrong..

**Comment by liedekef** [comment]
Can be easily reproduced on the commandline by e.g. going in /var/www/MISP/app and then executing that git command. If in /var/www/MISP, then it works as expected.
So it means the script behind the update button is in the wrong directory when the git command is being executed.

**Comment by liedekef** [comment]
I changed the update function to this:
```
        public function update($status) {
                $final = '';
                $output = array();
                $command1 = 'cd /var/www/MISP && git pull origin ' . $status['branch'] . ' 2>&1';
                $command2 = 'cd /var/www/MISP && git submodule update --init --recursive 2>&1';
```
So: adding the cd-command **and** also added the initial definition of the output variable.
This then seems to work correctly (I know that /var/www/MISP needs to be replaced by some variable probably).

**Comment by SteveClement** [comment]
@liedekef you permission are certainly wrong at some stage.

git does not care where you are in the directory structure. (Apart from being in .git of course or in a modules directory)
Double check your permissions please.

> www-data@misp-dev:/var/www/MISP/app$ git pull
> remote: Counting objects: 1, done.
> remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 1
> Unpacking objects: 100% (1/1), done.
> From https://github.com/MISP/MISP
>  * [new branch]        Rafiot-patch-1      -> origin/Rafiot-patch-1
>  * [new branch]        Rafiot-patch-2      -> origin/Rafiot-patch-2
>  * [new branch]        attributeFetcherFix -> origin/attributeFetcherFix
>  * [new tag]           v2.4.93             -> v2.4.93
> Already up to date.
>

**Comment by liedekef** [comment]
@SteveClement : sorry, your reply is incorrect (and a permission issue would result in issues from the toplevel too ...). I even figured it out now, by googling the toplevel thing. Seems that git required to be in the toplevel for submodule commands, this restriction was removed in git version 1.8.4 . However centos/redhat are still running older versions of git, so in order to be compatible with all git versions, a cd-command is needed for the git submodule command. See also:
https://stackoverflow.com/questions/21856214/git-submodule-update-why-from-toplevel
Btw: currently still running on EL6, due to company restrictions, so I can't claim if this is still the case for EL7 although the latest EL7 package is git-1.8.3.1-14.el7_5.x86_64.rpm (from June 22 2018), so I'm assuming it still has that issue.
So please reopen and consider the suggested fix again.
