### ISSUE TITLE
MISP virtual appliance deployed in Vmware ESXI hypervisor- Assign IP issue

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [MISP/MISP#3437]
I downloaded the MISP virtual appliance available at their website. I deployed it on my machine and it works perfectly. The machine loads  But when I deploy it on my VMware ESXI hypervisor server the machine gets an ip from the DHCP server (since the vm network settings are briged) on interface "enp0s3" for communication. However when i upload the same vm appliance to hypervisor, it does not get the ip, network settings of hyper v are same as my vmware. I tried giving it static ip address and it didn't work either. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | VMware Esxi HyperVisor

### Expected behavior
Assign a ip address to misp vm

### Actual behavior
Does not pick any ip

**Comment by SteveClement** [comment]
This sounds really tricky to debug without in-depth ESXi knowledge.

I will get a quick test-rig up tomorrow and see if I can reproduce it.

What version of ESXi you running @shehreyarahmedkohati ?

**Comment by SteveClement** [comment]
@shehreyarahmedkohati I tested our VM in esxi 6.5 it works no problem with a little tweaking.
Here are my steps to get a working copy:

- Upload the contents of the output-vmware directory onto your esxi server to some new folder.
- Register a VM from disk
- Trying to boot now will fail because it auto-detected SCSI controller for the VM, so you select IDE/master instead. (in the settings of the VM on esxi)

Then you boot no problem with networking and everything.

**Comment by shehreyarahmedkohati** [comment]
Thank you! I was away on business trip so excuse me for the late reply. 
My Version of EXSI is 5.5. 
I'll give a try using your steps. Thanks! @SteveClement

**Comment by fucgithub** [comment]
Shehreyarahamedkotami,
Would you kindly describe, did you install the complete stack, or just the virtual image of MISP?

**Comment by shehreyarahmedkohati** [comment]
@fucgithub I deployed the MISP training-VM. But to date, I have not been able to assign it an IP on the ESXI server. Using it from my local machine in Oracle VirtualBox.

**Comment by a1ext** [comment]
> @shehreyarahmedkohati I tested our VM in esxi 6.5 it works no problem with a little tweaking.
> Here are my steps to get a working copy:
> 
> * Upload the contents of the output-vmware directory onto your esxi server to some new folder.
> * Register a VM from disk
> * Trying to boot now will fail because it auto-detected SCSI controller for the VM, so you select IDE/master instead. (in the settings of the VM on esxi)
> 
> Then you boot no problem with networking and everything.

Hi @SteveClement, how did you do the third step? I'm trying to follow these steps and get the following error:
```Failed to start the virtual machine.
Module Disk power on failed. 
Cannot open the disk '/vmfs/volumes/56b8dd1d-8b0f20a5-8575-14187743c39c/MISP_TMP/VMware/disk.vmdk' or one of the snapshot disks it depends on. 
The system cannot find the file specified
VMware ESX cannot find the virtual disk "/vmfs/volumes/56b8dd1d-8b0f20a5-8575-14187743c39c/MISP_TMP/VMware/disk.vmdk". Verify the path is valid and try again. 
```
