### ISSUE TITLE
Merge events

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#344]
Hello all,

I would like to add a new feature in MISP to merge events. This "merging" functions will be particularly interesting when several events are linked to the same campaign/attack and contain duplicate attributes. Indeed, ever often several separate events are created for the same public APT or campaign for each public reports, pastbin links, tweets... 

For me, "merging" events has to resolve 2 main problems:
- Delete duplicate attributes for the same campaign/attack/APT
- Define a "merging" process: How do delete, create the events together ? I mean:
  - Delete the 2 events and create a new one with the merging information
  - Create a new event with the merging information and redirect the 2 same events to the new event
  - Create a new "effective uuids" in the event and merge all with the same "effective uuids" in the view section (like RT does)

At the moment, I don't know which solution ("merging" process) will be the best but I will try to quickly look the code of MISP to find a simple way to do it. 

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

FYI: If we find a solution for "merging" event, we might able be to fix a old issue #56.

**Comment by adulau** [comment]
There is now an option to merge attribute from another event https://<URL>/events/merge/<ID> Could you check if this solves this issue?

**Comment by adulau** [comment]
I'll close the issue as there is now a merge functionality. Feel free to reopen if this doesn't solve your issue.
