### ISSUE TITLE
Inconsistent application of warning lists

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#3441]
On a fresh 2.4.93 warning lists **are not applied** when attributes are being added through _Add Attribute_, but they **are applied** through _freetext import_...

In the following screenshot 8.8.8.8 was added via _Add Attribute_, 9.9.9.9 via _freetext import_:

![warninglist](https://user-images.githubusercontent.com/25325656/42326306-11a7643c-8069-11e8-9ff9-1b92f6d2883b.png)

**Comment by iglocska** [comment]
Is the IDS flag set for 8.8.8.8?

**Comment by StefanKelm** [comment]
No, it wasn't. It works as expected when the IDS flag is set. Thanks for the swift clarification!

**Comment by iglocska** [comment]
No worries ;)
