### ISSUE TITLE
MISP open events that contain large Attribute became very slow

### ISSUE THREAD

**Issue by allenxian** [MISP/MISP#3446]

**Comment by allenxian** [comment]
this events contain 10000 objects

**Comment by syloktools** [comment]
I agree that I am seeing this as well. Also if you try to sort the index by attribute count it is very slow. So slow that I could not wait for it to complete and gave up.

**Comment by github-germ** [comment]
i think some of my open issues are related:
- #3632 
- #3671 
- https://github.com/MISP/PyMISP/issues/276

**Comment by github-germ** [comment]
This issue persists in 2.4.97

**Comment by Rafiot** [comment]
(closing this one, duplicate)
