### ISSUE TITLE
export attributes from X events

### ISSUE THREAD

**Issue by lbrossault** [MISP/MISP#3456]
Hello,

Is there a way to export ALL attributes from specific cluster or tag ?

Regards,

**Comment by iglocska** [comment]
Yes, using the restsearch API

POST to:
`/attributes/restSearch/download`

Using the following headers:
```
Authorization: YOUR_API_KEY
Content-type: application/json
Accept: application/json
```

The following payload:
`{"tags":["mytag", "misp-galaxy:cluster=\"value\""]}`
