### ISSUE TITLE
YARA signatures context info

### ISSUE THREAD

**Issue by keithcusters** [MISP/MISP#346]
It would make sense when posting a YARA attribute that you indicate that the signature is targeting disk, memory or both. This would facilitate the automatic integration of MISP with other ecosystems using YARA as input. Right now the analyst using MISP needs to analyze the event to understand the context of the YARA signature.

**Comment by Rafiot** [comment]
Related to: https://github.com/MISP/MISP/issues/401

**Comment by adulau** [comment]
Solved with the new YARA object including context where the YARA rule can be applied:

https://github.com/MISP/misp-objects/blob/master/objects/yara/definition.json#L24
