### ISSUE TITLE
Scheduled tasks blocked in the past?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3467]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | n/a
| PHP version               | 7.1
| MISP version / git hash   | 2.4.92
| Browser                   | n/a

### Expected behavior
We run a MISP instance in a high-availability Docker environment. All containers are eligible to be moved between two nodes at any time. When MISP is failed over, the scheduled tasks remain in the past and workers do not trigger anymore.

Question: where are stored the scheduled tasks? Is is possible to re-schedule them manually or via the command line?

### Actual behavior
Scheduled time remains in the past when a container is moved and MISP restarted

### Steps to reproduce the behavior
1. The container runs on node 1 and next scheduled pull is 08:30
2. The container is moved to note 2 around 08:29 to the other node
3. MISP is available a few minutes later (let's say 08:32)
4. Workers are running but the scheduled time will remain forever at 08:30 and never trigger

### Logs, screenshots, configuration dump, ...
n/a

**Comment by iglocska** [comment]
They are stored in redis and restarting them is a bit messy - any change in the interface to the scheduled tasks should retrigger them.

However, using cron jobs is preferred all of the actions you run via scheduled tasks are API exposed

**Comment by xme** [comment]
Any link or document to describe the cron jobs method? (lazy to Google ;-)
