### ISSUE TITLE
Add ACLs

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#347]
Add ACLs for "change user data (mail/pass/gpg key)" and "use REST API".

Then it can be used to create a profile that has neither of those rights and can be used as a demo acccount without needing to modify the code to accomodate that specific use case.

This is related to a past private feature request.

**Comment by adulau** [comment]
Creation of users are now accessible via the API:

~~~~

  |  
-- | --
name | "/admin/users/add API description"
description | "POST a User object in JSON format to this API to create a new user."
mandatory_fields |  
0 | "email"
1 | "org_id"
2 | "role_id"
optional_fields |  
0 | "password"
1 | "external_auth_required"
2 | "external_auth_key"
3 | "enable_password"
4 | "nids_sid"
5 | "server_id"
6 | "gpgkey"
7 | "certif_public"
8 | "autoalert"
9 | "contactalert"
10 | "disabled"
11 | "change_pw"
12 | "termsaccepted"
13 | "newsread"
url | "/admin/users/add"

~~~~
