### ISSUE TITLE
Bro export stuck in job queue, can't click generate button

### ISSUE THREAD

**Issue by allenxian** [MISP/MISP#3472]
but worker is fine.How to stop the failed job。
![image](https://user-images.githubusercontent.com/22782166/42572468-26542f22-854c-11e8-9f7b-6d563cb7710b.png)

![image](https://user-images.githubusercontent.com/22782166/42572545-3f9b3bec-854c-11e8-8893-e5a1e8e78b8f.png)

**Comment by iglocska** [comment]
The queued message is wrong, the data is already up to date. If you modify and publish an event it will become available again for re-caching.

**Comment by allenxian** [comment]
I modify and publish an event ，it still can not be re-caching。
![image](https://user-images.githubusercontent.com/22782166/42572995-81a851b8-854d-11e8-8695-f035bc05f7a8.png)

**Comment by iglocska** [comment]
Weird, will have a look.

**Comment by PPmzp4** [comment]
Hello,

If you go to the "jobs" panel the task should still remain pending.
Could you go to "Administration" -> "server settings" -> "Workers". Are they running?
If they are not running, try to restart them. Queued jobs should resume.
