### ISSUE TITLE
OVA for esxi

### ISSUE THREAD

**Issue by zlob-bik** [MISP/MISP#3477]
Deploy from
https://www.circl.lu/misp-images/latest/MISP_v2.4.93@53f974895ee2760c4a4456b5bfd4d223ad4c67f4.ova
on esxi 5.5 report problem with platform (OVA for VirtualBox-2.2)
![1](https://user-images.githubusercontent.com/41143318/42620049-82ef5538-85c2-11e8-8a2d-e74db97226f5.jpg)
![2](https://user-images.githubusercontent.com/41143318/42620051-8705733c-85c2-11e8-91cb-08752cd84c2a.jpg)

**Comment by SteveClement** [comment]
Dear,

You need to create a new VM manually and then upload the contents of the ZIP file.

I will make a screen cast soon. But will use the web interface of esxi, which should be similar enough.

See here for a little more detail: https://github.com/MISP/MISP/issues/3437#issuecomment-403080550

**Comment by zlob-bik** [comment]
OK.
Upload all from zip
scrn_1
Add to Inventory
scrn_2 (why after copy all disks conver into 1 - I don't know)
Error
Change to IDE on 5.5 can't find, change manually. Error
scrn_4
![scrn_1](https://user-images.githubusercontent.com/41143318/42629208-4d3770ba-85db-11e8-9870-6d6533c34daa.PNG)
![scrn_2](https://user-images.githubusercontent.com/41143318/42629210-4d580b54-85db-11e8-8391-725ffdfd3df8.PNG)
![scrn_4](https://user-images.githubusercontent.com/41143318/42629212-4d783276-85db-11e8-8b18-ed6c4316b1d0.PNG)

**Comment by SteveClement** [comment]
@zlob-bik quick and dirty screencast: https://www.youtube.com/watch?v=Z4pKlp43_CM

**Comment by zlob-bik** [comment]
Solution for 6.5
I use 5.5...I can't add existing VM, only add to Inventory, but esxi 5.5.0-1331820 - don't work
If change SCSI  on IDE same problem.
https://youtu.be/LF4mnDm6XQs

**Comment by iglocska** [comment]
It looks like esxi 5.5 is going EOL very soon, do you have the possibility
to upgrade by any chance?

**Comment by SteveClement** [comment]
@zlob-bik I think you really want to think about upgrading ASAP, end of support is announced for  September 19, 2018. https://kb.vmware.com/s/article/51491

We will not further investigate this issue no this version.

For security reasons please update your system to not run into any issues.

**Comment by zlob-bik** [comment]
Servers  form 2012
Esxi 6.5 don’t support.
Try via Linux, but …will check

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by shehreyarahmedkohati** [comment]
I have a Hypvervisor ESXI 6.0. The training VM uploaded their boots properly but does not picks any IP address except loopback address. The VM is bridged. The DHCP is enabled and all other VM's on the server run perfectly. What can possibly be the issue here?
