### ISSUE TITLE
Generate yara rules from pattern-in-file and pattern-in-memory attribute types

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#348]
Automatically generate yara rules from pattern-in-file and pattern-in-memory attribute types.

Feature related to #346

**Comment by Rafiot** [comment]
Related to: https://github.com/MISP/MISP/issues/401

**Comment by adulau** [comment]
https://github.com/MISP/yara-misp/blob/master/yara_misp.py could be a good basis

**Comment by adulau** [comment]
It's implemented in the default yara export:

https://github.com/MISP/MISP/blob/2.4/app/files/scripts/yara/misp2yara.py#L179
