### ISSUE TITLE
Feed.php: memory exhaustion error when attempting to pull feed data

### ISSUE THREAD

**Issue by Zogir** [MISP/MISP#3481]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| OS version (client)       | *not applicable*
| PHP version               | 7.1 (rh-php)
| MISP version / git hash   | 2.4.93 (81c0fc2279583fccac879d302039c8b6f110f9ae)
| Browser                   | *not applicable*

### Expected behavior
"Fetch and store all feed data" from https://www.circl.lu/doc/misp/feed-osint

### Actual behavior
After waiting about a minute from having pressed the blue "Fetch and store all feed data" button in "<MISP_DOM>/feeds", the "error.log" in app/tmp/logs shows:
```
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 155648 bytes) in [/var/www/MISP/app/Model/Feed.php, line 612]
```

Looks like possibly reading a large JSON file triggers it.

No events appear in "<MISP_DOM>/events/index" (but that could be due to me having pulled the same events before under a different owner org and deleting them a day ago).

However, repeating the same steps above (but by clicking on "Fetch all events") results in exactly the same behavior.

### Logs, screenshots, configuration dump, ...

![misp_memory_bug1_edited](https://user-images.githubusercontent.com/11097316/42659888-418c11b2-85ef-11e8-87e6-11853c4b853c.png)
![misp_memory_bug2_edited](https://user-images.githubusercontent.com/11097316/42659901-485393ee-85ef-11e8-8ac0-9f7b3320e2aa.png)

**Comment by adulau** [comment]
Maybe your PHP needs some love but also some memory `Allowed memory size of 134217728 bytes exhausted` ;-) Don't forget to increase your `memory_limit` and check the recommended settings in the diagnostics page.

**Comment by Zogir** [comment]
Ah, got it. Made the appropriate changes and restarted httpd and MISP, clicked "Fetch and store all feed data", received no error, and now the event information is showing up in "/events/index". Thank you for your time.

![misp_memory_limit_default_diagnostics_page](https://user-images.githubusercontent.com/11097316/42698756-73fa8300-8684-11e8-94aa-660329b20fad.png)
![edited_php ini](https://user-images.githubusercontent.com/11097316/42698790-87cb937e-8684-11e8-928c-c58b240564b8.png)
![misp_set_memory_limit_diagnostics_page](https://user-images.githubusercontent.com/11097316/42698795-8e8c89ac-8684-11e8-9fcf-b5911b21bdb5.png)
