### ISSUE TITLE
Unable to edit events of other organizations - work around?

### ISSUE THREAD

**Issue by NandyRaja** [MISP/MISP#3485]
Hi Team,

I got an use case whereas I should be able to edit the events from other organizations(while trying to add object via API - add_object method). 

being known that the members of org / site-admins can edit this. I am using a service account and automation for certain tasks. Hence granting site admin privilege to service account is NOT OPTIMAL, in this case. 

Please suggest if I can edit other organization events by any other way / work-around for this problem?

**Comment by SteveClement** [comment]
@NandyRaja looking into it.

**Comment by iglocska** [comment]
There is no workaround - users of other organisations should not be allowed to edit events of other organisations. 

Something to consider is using the extended event functionality (so creating your own event that latches onto an existing event) instead.
