### ISSUE TITLE
Time-based attribute search based on Event date

### ISSUE THREAD

**Issue by HitHard** [MISP/MISP#3494]
Hello,

I'm using the REST API to get a list of attribute from the last 30 days.
In the results, I get an IP which is dated as 2018-03-02. The event creation was on 2018-03-02, but the last modification was on 2018/07/02.

I think the query is based on the event last modification and not on the attribute date.

Is this normal ?
Regards
------------------------------
REST query used :
https://misppriv.circl.lu/events/csv/download/false/false/false/Network%20activity/false/false/false/false/30d

Event ID: 10506

**Comment by cvandeplas** [comment]
As discussed, the search timeframe is based on the last edit time of the event (and more?), and not from the attributes.
The event you mention was edited on the 3rd of July, so it then fits the timeframe.
It however raises the discussion point on which timestamp should be used for an attribute search.

**Comment by cvandeplas** [comment]
Looking at the history of the event there might be other issues with the sync causing event timestamps to be edited.

**Comment by iglocska** [comment]
Not necessarily, getting a modified timestamp on the event level can have valid reasons. Such an example is republishing an event to sync it out again - not a great practice but happens more often than you'd think  - by just editing the event and hitting publish. The edit part will update the timestamp too.

However, in OP's case what I would recommend is to update to the latest version of MISP and to abandon the old deprecated CSV endpoint and use restSearch. You have much more control over what data you get back, such as:

To get all attributes of category network activity from the past 30 days simply run this:

URL /attributes/restSearch
payload:
```
{
   "returnFormat": "csv",
    "category": "Network activity",
    "timestamp": "30d"
}
```

This will return all attributes with edited in the past 30 days of the given type.

```
{
   "returnFormat": "csv",
    "category": "Network activity",
    "event_timestamp": "30d"
}
```
This will return all attributes OF EVENTS edited in the past 30 days of the given type.

```
{
   "returnFormat": "csv",
    "category": "Network activity",
    "publish_timestamp": "30d"
}
```
This will return all attributes PUBLISHED during the past 30 days that match the given type.

if the issue persists, please let us know!

**Comment by gela1825** [comment]
Thank you!

**Comment by gela1825** [comment]
@iglocska Thank you!
