### ISSUE TITLE
[i18n] Danish translation

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3497]
Concerns PR https://github.com/MISP/MISP/pull/3492

Uploading current PO to **crowdin** yields:

```
Imported default.pot localization file is invalid. GetText PO validation module said: 
line #117: keyword "Eventen" unknown
line #117:15: syntax error
line #118: end-of-line within string
line #129: keyword "foresl" unknown
line #129:98: syntax error
line #301:64: syntax error
line #301: keyword "Tilf" unknown
Total errors: 19
```

![screen shot 2018-07-17 at 22 23 41](https://user-images.githubusercontent.com/362025/42843372-2ed93994-8a10-11e8-8380-f14b9b629ffc.jpg)

@eCrimeLabs might be able to give a hand :)

Added Danish translation here: https://crowdin.com/project/misp/da#

**Comment by SteveClement** [comment]
PO works in MISP.

**Comment by eCrimeLabs** [comment]
I've fixed some missing " however the error on line 301 I could not see the error but tried changing \" to '

**Comment by SteveClement** [comment]
Thanks @eCrimeLabs I fixed (https://github.com/MISP/MISP/pull/3499) the rest and uploaded it to crowdin.
