### ISSUE TITLE
Data model enhancement: Allow to mark different attribute as being related

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#350]
Allow to mark different attribute as being related, for example different types of hashes for a file. Or a hostname and an IP.

Related partially to #27

**Comment by Rafiot** [comment]
This is planned, especially for the hashes.

**Comment by adulau** [comment]
MISP 2.4.80 with MISP objects and relationships should have fixed this. Feel free to reopen the issue if this is not solved.
