### ISSUE TITLE
CSRF (blackholed) is triggered on almost every request

### ISSUE THREAD

**Issue by kyr-stefanidis** [MISP/MISP#3505]
Overview

| Type of issue             | Support...
| MISP version / git hash   | 2.4.93

Since 2.4.93, the MISP instance started returning "Your request has been blackholed" on almost all non GET requests. Only the first time after login, the request goes normaly and then it is constantly blackholed until re-loggin.

the MISP instance is deployed on a docker container, with an apache reverse proxy in front and with OpenAM web agent for external user authentication. The MISP Instance is configured to accept customAuth SSO.

The same set up with cersion 2.4.88 does not blackhole the requests.

### Logs, screenshots, configuration dump, ...
[misp error log.txt](https://github.com/MISP/MISP/files/2219073/misp.error.log.txt)

**Comment by iglocska** [comment]
Is the baseurl set up correctly? Will have a look if I can reproduce it, but haven't seen this anywhere else.

**Comment by SteveClement** [comment]
@kyr-stefanidis also be careful with multiple tabs open (or even multiple browsers), that got me in such a situation in the past.
If all else fails try to clean session/cookies on browser level.

**Comment by kyr-stefanidis** [comment]
baseUrl is set up correctly as it was in 2.4.88 (by the way, some actions, like double clicking on a user, ignore the baseUrl and redirect to the internal docker container name but I that is something for another ticket)

I did the tests in new incognito as well to make sure that there are no misplaced sessions

Just an update:
Deployed 2.5.92 with the same set up (misp configuration, apache vhosts configuration, OpenAM configuration, misp users) and no blackholes are encountered. So, at least for this particular set up, something interesting happened between those two versions.

**Comment by keram79** [comment]
This might be a duplicate with issue #3454 , please check

**Comment by keram79** [comment]
As above it is written "The MISP Instance is configured to accept customAuth SSO.": we haven't deployed our system as Docker images, but in a native ubuntu environment, but we are ALSO using a custom auth (Apache, LDAP).

**Comment by adulau** [comment]
@kyr-stefanidis can you confirm that we can close this issue? Thank you very much.
