### ISSUE TITLE
Multiple instances of same Tag

### ISSUE THREAD

**Issue by neok0** [MISP/MISP#3507]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.93 
| Browser                   | If applicable

### Expected behavior
Multiple instances of same tag should only appear once on event level tags.

### Actual behavior
Same instance of tags are shown multiple times. It seems checking for duplicates is not enforced via API.

### Steps to reproduce the behavior
```
from pymisp import PyMISP
from pymisp import MISPEvent

misp_url = ''
misp_key = ''

misp = PyMISP(misp_url, misp_key)

event = MISPEvent()
event.info = "Test Event"

event.add_attribute('comment', 'comment')

event.add_tag('tlp:amber')
event.add_tag('tlp:amber')

misp.add_event(event)

```

**Comment by iglocska** [comment]
Oh wow...
