### ISSUE TITLE
ZeroMQ settings.json file is missing

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#3508]
In attempting to troubleshoot issues with ZeroMQ in Gitter, I have determined that the settings.json file is missing from ZeroMQ.

How is this file created, is there a template that I can download?
All the settings in the MISP configuration section have been set to the defaults except for the redis password option as it's not set.

**Comment by SteveClement** [comment]
As per GITTER Chat:

The /var/www/MISP/app/files/scripts/mispzmq/settings.json is created when you activate ZeroMQ in the Server Settings
https://github.com/MISP/MISP/blob/a81894f14ca74a060f4d50713c6cf64f4243f954/app/Lib/Tools/PubSubTool.php

Thanks to @patricksvgr

**Comment by jezkerwin** [comment]
Also as per gitter chat, no its not being created when the plugin is enabled

**Comment by patricksvgr** [comment]
> Also as per gitter chat, no its not being created when the plugin is enabled

Might be a permission issue with `/var/www/MISP/app/files/scripts/mispzmq`. When correctly set (writable), it's getting created.

**Comment by jezkerwin** [comment]
The problem was with selinux on the mispzmq folder and on settings.json and mispzmq.pid

Changing/restoring context to ` httpd_sys_rw_content_t ` fixed the issue

**Comment by Aisik00** [comment]
Hi, 
I might stumble upon similar problem. ZMQ is running based on diagnostics page in web interface and when I run /var/www/MISP/tools/misp-zmq/sub.py, it shows me correct ZeroMQ notifications. I run the instance in virtual box for testing purposes. When I try to run the same script (sub.py) in my host OS, it does not receive any ZeroMQ notification. Port forwading is fo course set, with 'nc -zv 127.0.0.1 50000' it shows connection succeded.

When I try to run /var/www/MISP/app/files/scripts/mispzmq/mispzmq.py it fails and the exception is **Exception: The settings file is missing.**. So probably similar error as in this issue, but from the comments I am not able to reconstruct the fix. Could you please help me? How can I create that settings.json file? Or could be the problem somewhere else?

**Comment by mokaddem** [comment]
Hey @Aisik00,
Iirc, you are not supposed to run `MISP/app/files/scripts/mispzmq/mispzmq.py`.
The script that should be run to test the notifications is `MISP/tools/misp-zmq/sub.py`.
Cheers

**Comment by Aisik00** [comment]
Thank you for reply, but my problem was based just on my silly mistake. I had in set up address '127.0.0.1' ZeroMQ host instead of '0.0.0.0', when I want to listen from host.

**Comment by highpingblorg** [comment]
Still running into the same issue, I tried the above mentioned fix but didn't work for me.

I get the following error when I try to start ZeroMQ:
```
2024-05-08 11:12:42 Error: [RuntimeException] ZeroMQ server is managed by supervisor, it is not possible to restart it.
Request URL: /servers/startZeroMQServer/?_=1715159144239
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(1821): PubSubTool->restartServer()
#1 [internal function]: ServersController->startZeroMQServer()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

Supervisord is running, restarting supervisor does not fix this issue.
