### ISSUE TITLE
Edit object - changing type of the an attribute in an existing object

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#3509]
It would be nice to be able able to change the type of an attribute within an existing object. The edit interface allows to change everything except the type of the attribute.

**Comment by iglocska** [comment]
That is for a good reason. That would break the object -> attribute
relationship.

**Comment by SteveClement** [comment]
@iglocska thus a non-issue?

**Comment by adulau** [comment]
Ok so the best option is to delete and add an attribute but if want to keep the same UUID. As example, I have people who are setting up url instead of link. Updating the type makes sense? instead of creating a new attribute.

**Comment by iglocska** [comment]
Why does the template allow both?

**Comment by adulau** [comment]
As an example (paste object), a paste url can be used for malicious use (delivering malicious payload) or used for reference as an osint source.

**Comment by iglocska** [comment]
I don't see how that would change for the paste object though. Currently the paste object has a Url::url field - editing it after the fact would break the relationship if we'd allow it. Would you allow a domain-ip object to be edited to show a filename and a hash instead of domain+ip?

**Comment by adulau** [comment]
I see the point. So It means we need to have both on the template object depending of the use of the link of the paste. I'll update it.

**Comment by iglocska** [comment]
Yup, sounds great!
