### ISSUE TITLE
MISP automation

### ISSUE THREAD

**Issue by stansecurecom** [MISP/MISP#3514]
I know that it's possible to get AUTOMATION KEY though web-interface, under Events>Automation section.

But is it possible to get this key trough API with the login:pass of the user?

**Comment by 8ear** [comment]
I don't think.
But why you want to do this?

**Comment by stansecurecom** [comment]
I'm writing a script which will be used on different configurations (MISP servers, users, fully automated).

An API KEY is one thing that I stuck with, since there is no other way exept copy-paste it into your code.

**Comment by adulau** [comment]
When you initialise a MISP with the user, you get the user API key at the same time, we are using it for the continuous integration with Travis:

https://github.com/MISP/MISP/blob/2.4/.travis.yml#L96

Let us know if this is fine, if not we can have a look at it.

**Comment by stansecurecom** [comment]
@adulau This looks like a good solution) Is there a way to do this after MISP have been initialized?

**Comment by iglocska** [comment]
I've added a new tool after you opened the issue but forgot to mention it here. You can now run this:

`/var/www/MISP/app/Console/cake Admin getAuthkey [my@email.com]`
