### ISSUE TITLE
Can't get web interface to work

### ISSUE THREAD

**Issue by jhbigler-pnnl** [MISP/MISP#3516]
Hello,

I am trying to get MISP running on an Ubuntu Server VM. I ran the instructions on the INSTALL.txt as closely as possible, but when I enter the server's IP address in a web browser on a separate Ubuntu Desktop VM, it says it is unable to connect to the server. I can ping the IP successfully so the VM's are able to talk to each other, and I know that Apache2 is running:

![image](https://user-images.githubusercontent.com/40866196/43340094-10f5cc9e-9190-11e8-9d77-3000649dcd6b.png)

Here is the misp-ssl.conf file, if that is of any help:

![image](https://user-images.githubusercontent.com/40866196/43340202-6a40a24c-9190-11e8-8136-053df3cde3ce.png)

Plus, I am able to get the workers started:

![image](https://user-images.githubusercontent.com/40866196/43340318-c8a12258-9190-11e8-8703-9f181fc6cd0d.png)

I can't seem to figure out why I can't access the web interface, it seems like it should be working. Any idea of what I might be doing wrong? Any help would be appreciated - keep in mind I am very much a noob.

Thanks!

**Comment by adulau** [comment]
Can you test locally the connection on the VM? with curl? It seems to be a routing issue or alike (or the name of your virtualhost of your apache configuration).

**Comment by jhbigler-pnnl** [comment]
This is the result of running curl on the server VM:

![image](https://user-images.githubusercontent.com/40866196/43344127-84056fe8-919d-11e8-9a8e-b6f30c945d9d.png)

Running the command on the Ubuntu Desktop VM results in a message saying "Connection refused".

Running curl from my host computer results in a message saying Timed Out.

**Comment by jhbigler-pnnl** [comment]
Turns out I'm just an idiot who doesn't make sure his VM's are on the same NAT network before posting to GitHub... :) All is good. Closing

**Comment by adulau** [comment]
Cool. Thank you. By the way, we also generate VMs at each commit for MISP including MISP, misp-modules, viper and misp-dashboard. Available at the following location: https://www.circl.lu/misp-images/latest/
