### ISSUE TITLE
Cannot add sighting if Orgc is set during automated event creation until after the event is published

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#3522]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.93 (6a1c895b0a82a4a3a665bf3ffbad1d92551032a1) 
| Browser                   | If applicable

### Expected behavior
Sighting is add to the values in the event without the event being published. This worked until we started setting the Orgc to another Org. 

### Actual behavior
Adding a sighting is blackholed.

### Steps to reproduce the behavior
Add an event using a json payload with the Orgc set to something other than the host Org.
Try to add a sighting to a value in that event through the api or gui.

### Logs, screenshots, configuration dump, ...
```
2018-07-31 13:02:38 Error: [BadRequestException] The request has been black-holed
Request URL: /sightings/add/3414741
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(SightingsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(SightingsController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(SightingsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SightingsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by syloktools** [comment]
This is working now.

**Comment by iglocska** [comment]
Perfect, thanks for the feedback!
