### ISSUE TITLE
Not able to connect to GitHub via proxy

### ISSUE THREAD

**Issue by TostyT** [MISP/MISP#3524]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| MISP version / git hash   | v2.4.92 (d1eb64446a14e5c429f973cac080e9444bdeed19)

We're unable to connect to GitHub via our proxy. Either via the update button in the GUI or via the CLI of Ubuntu. 

GUI:
I've edited the file Server.php in /var/www/MISP/Model to include our proxy:
`$command1 = 'git pull origin ' . $status['branch'] . ' 2>&1';`
to
`$command1 = 'git -c http.proxy=http://PROXYUSR:PROXYPWD@PROXYHOST:PROXYPORT pull origin ' . $status['branch'] . ' 2>&1';`

When I hit the update button on the diagnostic page in the MISP GUI the following error occurs:
> fatal: unable to access 'https://github.com/MISP/MISP.git/': Proxy CONNECT aborted

CLI:
I've followed the [normal steps](https://gist.github.com/evantoli/f8c23a37eb3558ab8765) to add the proxy settings to the .gitconfig file in /var/www/. The settings are visible in the configfile:
`[http]
      proxy = http://PROXYUSR:PROXYPWD@PROXYHOST:PROXYPORT`
`[https]
      proxy = http://PROXYUSR:PROXYPWD@PROXYHOST:PROXYPORT`

Result when I try to access GitHub:
`root@misp:/var/www/# git clone https://github.com/CybOXProject/python-cybox.git`
`Cloning into 'python-cybox'...`
`fatal: unable to access 'https://github.com/CybOXProject/python-cybox.git/': Received HTTP code 407 from proxy after CONNECT`

In both cases we see that the server is trying to connect to our proxy. But in this effort it is not adding the authentication method and credentials. The credentials and authentication method used for GitHub are also used with success for MISP itself.

Anyone any suggestions why it is not adding credentials and an authentication method? 

Thx!

**Comment by TostyT** [comment]
Solved. I didn't realise that the following command is needed to force git to send the credentials and authentication method to the proxy:

`git config --global http.proxyAuthMethod 'basic'`

Source: https://git-scm.com/docs/git-config#git-config-httpproxyAuthMethod

**Comment by SteveClement** [comment]
@TostyT thanks for the feedback.

**Comment by codthing** [comment]
@TostyT @SteveClement 
For me, your method has no effect
https://github.com/git/git-scm.com/issues/1588#issue-818219501
