### ISSUE TITLE
MISP update error

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#3528]
i am trying to update MISP using the webinterface but i get the following  error.

=================================================================================

git pull origin 2.4 2>&1

From https://github.com/MISP/MISP
 * branch            2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/composer.json
Please, commit your changes or stash them before you can merge.
Aborting
Updating aece239..ca6a40e

=================================

git submodule init && git submodule update 2>&

==========================================================================
Does anyone know how to solve this problem,

**Comment by wkleinhenz** [comment]
I am seeing this exact same issue
`git pull origin 2.4 2>&1

From https://github.com/MISP/MISP
 * branch            2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/composer.json
Please, commit your changes or stash them before you can merge.
Aborting
Updating accf52b..b723395

=================================

git submodule update --init --recursive 2>&1`

**Comment by wkleinhenz** [comment]
I was able to fix this issue by replacing composer.json with the composer.json file found here [https://github.com/MISP/MISP/blob/2.4.93/app/composer.json](url)

**Comment by iglocska** [comment]
`git checkout /var/www/MISP/app/composer.json`

should work too

**Comment by obert01** [comment]
Not exactly related, but since a few days, when updating from the GUI, I obtain the following non-fatal error:

```
git checkout app/composer.json 2>1

error: pathspec 'app/composer.json' did not match any file(s) known to git.

git pull origin 2.4 2>1

error: pathspec 'app/composer.json' did not match any file(s) known to git.
From https://github.com/MISP/MISP
 * branch                2.4        -> FETCH_HEAD
   7d0963bcb..575b29311  2.4        -> origin/2.4
Updating 7d0963bcb..575b29311
Fast-forward
 INSTALL/INSTALL.ubuntu1804.with.webmin.txt | 31 +++++++++++++++++++++---------
 app/View/Events/proposal_event_index.ctp   |  4 ++--
 app/View/ShadowAttributes/index.ctp        |  2 +-
 3 files changed, 25 insertions(+), 12 deletions(-)

```

How may I solve this issue?

**Comment by SteveClement** [comment]
@obert01 this is not an issue.
Unfortunately this looks ugly but your MISP instance is being updated correctly.

Eventually we will fix this.

**Comment by jimanderles** [comment]
I have the same problem, someone who solve the issue??

```
git checkout app/composer.json 2>&1

error: pathspec 'app/composer.json' did not match any file(s) known to git.

git pull origin 2.4 2>&1

error: pathspec 'app/composer.json' did not match any file(s) known to git.
From https://github.com/MISP/MISP
* branch            2.4        -> FETCH_HEAD
fff1e4f..a62bca4  2.4        -> origin/2.4
Updating fff1e4f..a62bca4
Fast-forward
app/files/scripts/stix2/misp2stix2.py | 15 ++++++++-------
docs/INSTALL.debian9.md               | 12 +++++-------
docs/INSTALL.ubuntu1804.md            |  2 ++
docs/xINSTALL.OpenBSD.md              |  3 ++-
docs/xINSTALL.centos7.md              |  7 ++++---
5 files changed, 21 insertions(+), 18 deletions(-)

=================================

git submodule update --init --recursive 2>&1
```
