### ISSUE TITLE
misp_json_attribut zmq json missing an galaxy add

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#3531]
Hi team : 

On an attribut when I folow all topic
add a tag :
misp_json_event
misp_json_tag
{'name': 'osint:source-type="source-code-repository"', 'colour': '#005694', 'attribute_id': '216061', 'exportable': True, 'org_id': False, 'id': '62', 'user_id': '0', 'event_id': '1240', 'hide_tag': False}
misp_json_attribute
misp_json_audit

add a galaxy :
misp_json_event
misp_json_audit
misp_json_tag
{'name': 'misp-galaxy:android="Aduru"', 'colour': '#0088cc', 'attribute_id': '216061', 'exportable': True, 'org_id': False, 'id': '409', 'user_id': '0', 'event_id': '1240', 'hide_tag': True}

^^

**Comment by SteveClement** [comment]
Dear @truckydev is this still an Issue?
I am not sure I understand exactly what is going on. How to reproduce?
Could you please develop.
