### ISSUE TITLE
Can't start workers manually, "ERROR: Plugin CakeResque could not be found."

### ISSUE THREAD

**Issue by jaxre** [MISP/MISP#3532]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | Redhat 7.5
| PHP version               | 7.1
| MISP version / git hash   | 2.4.93

### Expected behavior
Hi folks,
I'm trying to start the worker's manually via the script in '/var/www/MISP/app/Console/worker/start.sh'
Usually when I run this script, the workers get restarted normally

### Actual behavior
running the script produces the following error:

> PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(259): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(210): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}

### Steps to reproduce the behavior
run /var/www/MISP/app/Console/worker/start.sh

### Logs, screenshots, configuration dump, ...
Additional note:
Looking at my bootstrap.php I can see that CakeResque is loaded:

> CakePlugin::loadAll(array(
        'CakeResque' => array('bootstrap' => true)

Is there a way to verify that this is the case?

**Comment by SteveClement** [comment]
This is probably because cake was not installed correctly.
