### ISSUE TITLE
Additional data type: Nameserver under the category network activity

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#354]
Add a data type nameserver under the category network activity. And add specific IDS rules to trigger only if the answer is coming from those nameservers or if they are in answers as being nameservers.

**Comment by Rafiot** [comment]
Related to https://github.com/MISP/MISP/issues/460

**Comment by adulau** [comment]
This can be expressed as a passive DNS object:

- https://www.misp-project.org/objects.html#_passive_dns

The IDS rules generate would need to be updated to support the passive DNS object.

I'll close the issue.  As a more complete issue would need to be open, to link object with IDS ruleset generation.
