### ISSUE TITLE
p

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3541]

**Comment by shimi199393** [comment]
![capture3](https://user-images.githubusercontent.com/40624202/43881314-748bde82-9bb4-11e8-9446-50f960b0c557.PNG)

**Comment by adulau** [comment]
Already opened on the maintainer page of FireMISP https://github.com/deralexxx/FireMISP/issues/6 The issue is related to FireMISP (the url contains a 'None' value) ;-)

**Comment by github-germ** [comment]
Not sure if this will help you; however, I had taken the code from https://github.com/deralexxx/PySight2MISP and enhanced it quite a bit to make it work well ingesting into MISP (using PyMISP) via the FireEye iSIGHT API.

I intend to commit this code soon.
