### ISSUE TITLE
After upgrade version 2.4.94, restapi version always 2.4.93

### ISSUE THREAD

**Issue by rmkml** [MISP/MISP#3543]
Hello,
Thx for greats products and features!
Could you check why restapi version always 2.4.93 after upgrade to 2.4.94 ?
Like ticket #3421 .
Best Regards
@rmkml

**Comment by Rafiot** [comment]
It is cool, we just didn't update PyMISP significantly so it requires to bump the version.

It happens relatively often and this is nothing to be worried about.
