### ISSUE TITLE
Error when installing maec

### ISSUE THREAD

**Issue by eloyfs** [MISP/MISP#3545]
Im getting:
Command python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r8p35kst/importlib/ 
When running sudo pip3 install maec

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian
| OS version (client)       | 9.5
| PHP version               | 7.0
| MISP version / git hash   | 2.4.94

**Comment by patricksvgr** [comment]
Have you tried to run the command `pip3 install maec` again? ;-)

**Comment by Turecky** [comment]
For me that works but has version mismatch:
MAEC library version…Incorrect maec version installed, found 4.1.0.14, expecting 4.1.0.13

**Comment by patricksvgr** [comment]
Go for `pip3 install --force-reinstall maec==4.1.0.13` to reinstall the package.

**Comment by Turecky** [comment]
after running that code get this:
Collecting maec==4.1.0.13
  Downloading https://files.pythonhosted.org/packages/bb/3d/b9075416ce1dd17ad866253b7c7987e52b78bb8b8c1c6dc23f4b1a94e51f/maec-4.1.0.13.tar.gz (152kB)
    100% |################################| 153kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rxqk6rxq/maec/setup.py", line 24, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rxqk6rxq/maec/

**Comment by patricksvgr** [comment]
Do you have the latest `pip` version? Of not, `pip3 install --upgrade pip`.

**Comment by Turecky** [comment]
Just run upgrade for pip, but the same error appears
