### ISSUE TITLE
Error: no such table: auth_user

### ISSUE THREAD

**Issue by eloyfs** [MISP/MISP#3558]
Im getting Error: no such table: auth_user after running
 .# sqlite3 ~/.viper/admin.db 'UPDATE auth_user SET password="pbkdf2_sha256$100000$iXgEJh8hz7Cf$vfdDAwLX8tko1t0M1TLTtGlxERkNnltUnMhbv56wK/U="'

### Actual behavior
no such table: auth_user

### Steps to reproduce the behavior
.# sqlite3 ~/.viper/admin.db 'UPDATE auth_user SET password="pbkdf2_sha256$100000$iXgEJh8hz7Cf$vfdDAwLX8tko1t0M1TLTtGlxERkNnltUnMhbv56wK/U="'

**Comment by adulau** [comment]
@eloyfs are you sure you open the issue in the right repository? It seems related to [viper](https://github.com/viper-framework/viper) and not to MISP core software. Maybe you can an issue [there](https://github.com/viper-framework/viper/issues). Thank you.

**Comment by eloyfs** [comment]
@adulau Im using https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.debian9.txt guide and line 689 says sqlite3 
~/.viper/admin.db 'UPDATE auth_user SET password="pbkdf2_sha256$100000$iXgEJh8hz7Cf$vfdDAwLX8tko1t0M1TLTtGlxERkNnltUnMhbv56wK/U="' and it's not working

**Comment by adulau** [comment]
This is an optional framework and not directly used by MISP. It's indeed very handy if you work from viper and use the integration with MISP.  @SteveClement might help you as he added in the documentation
