### ISSUE TITLE
Can't add domain attributes with .bit extension 

### ISSUE THREAD

**Issue by carnak** [MISP/MISP#3559]
Type of issue: Can't add domain attributes with .bit extension 

Expected behavior: Trying to add following domains to an existing MISP event via Populate From -> Freetext Import:

mail-ru-stat[.]bit
mail-ru-stat-cdn[.]bit
mail-ru-stat-counter[.]bit
mail-ru-stat-counter-cdn[.]bit

Actual behavior: "Silently fails" the import, with no attributes available to be added to the event

**Comment by adulau** [comment]
Did you have the warning list enabled with all the TLDs? If not, could you give a try?

**Comment by carnak** [comment]
Thank you Alex for the quick reply.  My MISP instance did not have all warning lists enabled.  Once the warning lists were updated and enabled, it is now working!  Thanks again.

**Comment by adulau** [comment]
Thank you for the feedback, great news! Maybe we should enable it by default ;-)
