### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#356]
Stats per org with a breakdown per attribute type and per category and/or "IDS useable/not IDS useable".
Make a separate ACL right so that instance admin can decide if only org admin see the stats for their org or all the users of the org.

For org admin and instance admin, allow a breakdown per user.
Instance admin would then see stats for all orgs on the instance.
With a separate dashboard for data coming from orgs not on the instance?

Kind of related to #204

**Comment by adulau** [comment]
I'll close this issue because the statistics need to be extracted from the audit logs and can generate significant issues as it will be only the sync user. Maybe the recommended approach would be to monitor the ZMQ and create real-time statistics out of it.
