### ISSUE TITLE
STIX and Cybox libraries incorrect version numbers 0? - v2.4.94

### ISSUE THREAD

**Issue by ccpptt** [MISP/MISP#3564]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16.04.3
| OS version (client)       | macOS 10.x
| PHP version               | 7.0.22-0ubuntu0.16.04.1
| MISP version / git hash   | v2.4.94 (37cd2461a169a30529fdb1366ff655661cc53b5e) 
| Browser                   | Chrome

### Expected behavior
On the diagnostics page, after upgrading our MISP instance to the latest version, it is not detecting the installed STIX and Cybox libraries -- it should be detecting and listing them there, as they are installed and up-to-date. 

When I export an event as STIX / STIX2, it should export without error or 0byte export files. 

### Actual behavior
Upgraded from an older version (install from late last year) to the current latest, managed to get almost everything going except the additional libraries. It appears to be picking something up but reporting the versions as incorrect (v0?). 

Specifically, in the MISP diagnostics page, it's reporting that it can't find the STIX and Cybox libraries, or more accurately....

Current libraries status…Some of the libraries related to STIX are not installed. Make sure that all libraries listed below are correctly installed.
STIX library version…Incorrect STIX version installed, found 0, expecting 1.2.0.6
CYBOX library version…Incorrect CyBox version installed, found 0, expecting 2.1.0.17
MIXBOX library version…Incorrect mixbox version installed, found 0, expecting 1.0.3
MAEC library version…Incorrect maec version installed, found 0, expecting 4.1.0.13
PYMISP library version…Incorrect pymisp version installed, found 0, expecting >2.4.93

When exporting an event as STIX / STIX2, I get XML errors and 0byte output files respectively. 

### Logs, screenshots, configuration dump, ...
![screen shot 2018-08-17 at 2 31 10 pm](https://user-images.githubusercontent.com/3753357/44244886-47b26580-a22a-11e8-9723-5156fe8f1e23.png)

^Screenshot of the diagnostics page showing the library issues. 

On the MISP server, the libraries have been installed as per the instructions in 2.4/INSTALL/UPDATE.txt.

Permissions are correct AFAIK (task 8 on UPDATE.txt)

**Comment by ccpptt** [comment]
(and yes, PyMISP is also installed (v2.4.93) contrary to what that screenshot shows...)

**Comment by dexterfung** [comment]
Same issue happened on CentOS7 with PHP version 5.6 following the instructions in INSTALL/xINSTALL.centos7.txt

**Comment by iglocska** [comment]
Ping @chrisr3d

**Comment by RichieB2B** [comment]
This suggestion solved #3322 :

We had similar issues getting this to work. I agree that setting the correct path in `/etc/opt/rh/rh-php71/sysconfig/php-fpm` and setting clear_env is set to no in `/etc/opt/rh/rh-php71/php-fpm.d/www.conf` should be enough. That is how it is currently works for us, but before we had to modify `env[PATH]` as well.

**Comment by dexterfung** [comment]
> This suggestion solved #3322 :
> 
> We had similar issues getting this to work. I agree that setting the correct path in /etc/opt/rh/rh-php71/sysconfig/php-fpm and setting clear_env is set to no in /etc/opt/rh/rh-php71/php-fpm.d/www.conf should be enough. That is how it is currently works for us, but before we had to modify env[PATH] as well.

I have tried this way hoping to solve it but only stix and maec return OK, while the rest still returns found 0 error.

**Comment by patricksvgr** [comment]
Have you checked your Python permissions for the installed modules  (`python -c "import sys; print(sys.path)"`)?

**Comment by ccpptt** [comment]
@patricksvgr no I hadn't, but now that I have (and now that I've fiddled with them a bit) it's almost working now (thanks): 

> Current libraries status…Some versions should be updated:
> STIX library version…OK
> CYBOX library version…Incorrect CyBox version installed, found 2.1.0.18.dev0, expecting 2.1.0.17
> MIXBOX library version…OK
> MAEC library version…Incorrect maec version installed, found 4.1.0.14, expecting 4.1.0.13
> PYMISP library version…OK
> 
> pymisp:… OK
> pydeep:… Please install pydeep: pip install git+https://github.com/kbandla/pydeep.git
> magic:… OK
> lief:… Please install lief, documentation here: https://github.com/lief-project/LIEF

I've tried exporting an event in STIX1 with encoded attachments, and it seems to generate and output it fine. This was failing earlier. 

Now I guess my question would be -- what should the permissions for those module dirs be ideally? Why did I have to manually adjust them to get things going after an upgrade (i.e. is this problem limited to only my install which I seem to have fk'd up?). 

For reference, the file permissions were like the following (before I fiddled/fixed them); 

> /usr/local/lib/python2.7/dist-packages
> 
> -rw-r-----  1 root staff 664K Apr  4  2017 stix-1.1.1.4-py2.7.egg
> drwxr-s---  4 root staff   35 Apr  4  2017 cybox-2.1.0.12-py2.7.egg
> -rw-r-----  1 root staff  21K Apr  4  2017 functools32-3.2.3.post2-py2.7.egg
> -rw-r-----  1 root staff 6.4K Apr  4  2017 ordered_set-2.0.1-py2.7.egg
> -rw-r-----  1 root staff 4.2K Apr  4  2017 weakrefmethod-1.0.3-py2.7.egg
> drwxr-s---  4 root staff   40 Apr  4  2017 jsonschema-2.6.0-py2.7.egg
> -rw-r-----  1 root staff  30K Apr  4  2017 ConfigArgParse-0.11.0-py2.7.egg
> drwxr-s---  4 root staff   38 Apr  4  2017 libtaxii-1.1.110-py2.7.egg
> -rw-r-----  1 root staff 150K Apr  4  2017 stix_ramrod-1.1.0-py2.7.egg
> drwxr-s---  4 root staff   36 Apr  4  2017 mixbox-1.0.1-py2.7.egg
> drwxr-s---  4 root staff   38 Apr  4  2017 requests-2.13.0-py2.7.egg
> -rw-r-----  1 root staff 255K Apr  2  2017 python_dateutil-2.6.0-py2.7.egg

Changing them (e.g. making them readable by all) in the 2.7 dir only fixed a few of the packages (they then started appearing within the MISP UI). For the others I had to fiddle with things in /usr/local/lib/python3.5/dist-packages/. This seems messy, and I think I might have created the mess my self (e.g. pip vs. pip3, pip --user vs. sudo pip).

**Comment by dexterfung** [comment]
Since I have successfully installed on Ubuntu, I have switched to there instead of using CentOS. Thanks for the help though!

**Comment by ccpptt** [comment]
Permissions for the Python modules (dist-packages) weren't relaxed enough. Changed them to what I described in my previous comment, and things are working as expected now.
