### ISSUE TITLE
Type for object_template_elements.disable_correlation seems incorrect in MYSQL.sql

### ISSUE THREAD

**Issue by Lastpixl** [MISP/MISP#3565]
Hi,

While reviewing our database's schema, I think I came across a discrepancy between AppModel.php and INSTALL/MYSQL.sql

If I understand AppModel.php correctly:
* Field object_template_elements.disable_correlation has been introduced with update 2.4.80. At this time, its type was `tinyint(1) NOT NULL DEFAULT 0,`: see https://github.com/MISP/MISP/blob/8b63843299c557e864f277abab531506054fec26/app/Model/AppModel.php#L862 
* Versions 2.4.83 and 2.4.85 both changed this type to `text COLLATE utf8_bin`: see https://github.com/MISP/MISP/blob/8b63843299c557e864f277abab531506054fec26/app/Model/AppModel.php#L897
* However, MYSQL.sql still has type `tinyint(1) NOT NULL DEFAULT 0`: see https://github.com/MISP/MISP/blob/8b63843299c557e864f277abab531506054fec26/INSTALL/MYSQL.sql#L603

Current MYSQL.sql has `db_version` = 11, so updates 2.4.83 or 2.4.85 will not be applied to fresh installs.

I think MYSQL.sql should be updated to use the new type. Is that correct?

(all links pinned to current commit at 2.4, so that they remain correct even if the linked files are changed by subsequent commits)

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
