### ISSUE TITLE
Uninitialized string offset in ComplexTypeTool.php

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#3566]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.94

I am seeing this error a lot in the resque-worker-error.log:
```
2018-08-16 13:03:03 Notice: Uninitialized string offset: 0 in [/var/www/MISP/app/Lib/Tools/ComplexTypeTool.php, line 326]
Notice Error: Uninitialized string offset: 0 in [/var/www/MISP/app/Lib/Tools/ComplexTypeTool.php, line 326]
```
Tailing the log now to see if I can match up what MISP is doing at time the log is written.

**Comment by SteveClement** [comment]
@robertnixon2003 any luck?

**Comment by SteveClement** [comment]
Dear @robertnixon2003 if this didn't solve your issue feel free to re-open.
