### ISSUE TITLE
Inconsistency in the response between Event restSearch and Attribute restSearch

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3568]
The response for restSearch at event level look like that:

``` {'response': [{'Event': {<content>}}, {Event: {}}, ...]}```
```{'response': {'Attribute': [<Attribute content event 1>, <Attribute content event 2>, ...]}}```

So for the events, we have a list of events one after the other, for the attributes, we have that list in a dictionary with key `Attribute`. I was expecting something like that:
```{'response': [{'Attribute': {content}}, {'Attribute': {content}}, ...]}```

It is not a bug per-se, but it is a bit weird to process.

**Comment by iglocska** [comment]
It is weird to process but we'll break a lot of tools if we change it. We had the same issue with the event index.

**Comment by Rafiot** [comment]
Ok, I'll sanitize it in pymispng.

**Comment by Rafiot** [comment]
So still something that would be nice: if the search query doesn't returns anything, it should be

`{'response': {'Attribute': []}}` and not `{'response': []}`

**Comment by SteveClement** [comment]
@Rafiot @iglocska shoudl I stay or should I close...

**Comment by Rafiot** [comment]
Let's close, because legacy stuff. 

I sanitize on Pymisp side.

**Comment by iglocska** [comment]
Yeah it's something that we could fix, but that would break all existing tools using those APIs.
