### ISSUE TITLE
Manual export and Import of MISP event - Object References get lost 

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#3573]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian 9
| PHP version               | 7.0
| MISP version / git hash   | v2.4.94 (ed9e12c22e7eb000c80ce13c6862b440115cb036) 
| Browser                   | Chrome

### Expected behavior
When you manually export an event by choosing the download "MISP JSON (metadata + all attributes)" including attachments.

Going to the second instance and import the entire event including Object relations should be imported and created

### Actual behavior
Everything seems to be implemented, however the Object references are not imported.

### Steps to reproduce the behavior

Import the attached json as it should contain several Object references.

The two MISP instances are same ORG

### Logs, screenshots, configuration dump, ...

[misp.event.8266.5abeae24-7190-4526-bdf9-592a9f590eb0 (3).zip](https://github.com/MISP/MISP/files/2300604/misp.event.8266.5abeae24-7190-4526-bdf9-592a9f590eb0.3.zip)

**Comment by iglocska** [comment]
This is confirmed and needs a fix ASAP

**Comment by iglocska** [comment]
Thanks a million for the report and the chat today, this was a super crucial one to fix.
