### ISSUE TITLE
restSearch does not accept unix timestamp search only shorthand time descriptions

### ISSUE THREAD

**Issue by Zpa48** [MISP/MISP#3574]
### Work environment

| Questions                          | Answers
|--------------------------|--------------------
| Type of issue                    | Bug
| OS version (server)          | Ubuntu
| OS version (client)            | CentOS
| MISP version / git hash    | 2.4.94

### Expected behavior
https:// misp.url /events/restSearch/json
with POST data:
{ "timestamp": ["1534175985", "1534770822"] }

Should return list of events :
{ "response": [ { "Event": {"id": "3292", ...list of events...} } ]
### Actual behavior
Returns empty event list (it was working in version 2.4.93):
{ "response": [] }

### Steps to reproduce the behavior
Make a rest API query to ../events/restSearch/json with timestamp using unix timestamp like "timestamp": ["1534175985", "1534770822"].
It only works using shorthand time descriptions "timestamp": ["5d", "1h"]. Shouldn't it accept both forms, unix timestamp and short hand?

### Logs, screenshots, configuration dump, ...
probably related with:
[API] Updated the timestmap handling in the restSearch APIs to use the new smart-system:
https://github.com/MISP/MISP/commit/064748d87dedf4b35cc74ec31d5e8c976a404285

**Comment by iglocska** [comment]
It should for sure, that sounds like a bug. I remember we had an issue with this recently, could you also try with [1534175985, 1534770822] ?

**Comment by Zpa48** [comment]
Without double quotes like [1534175985, 1534770822] it works OK. I was using timestamps as strings (via PyMISP) and it was working in previous version. I will change it to int.
I was using search as described in this issue https://github.com/MISP/MISP/issues/1703. Thats why i was using strings. Thanks for your help.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
