### ISSUE TITLE
Cannot add a new taxonomy

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3591]
2.4.94

Followed instructions on https://www.circl.lu/doc/misp/taxonomy/#adding-a-private-taxonomy

The `machinetag.json` is valid JSON. Dir/file permissions look OK.

In the WebUI, logged in as admin, goto `Event Actions > List Taxonomies` and this new taxonomy is not listed. Then clicking on `Update Taxonomies`, which I believe is the next step, yields this in the browser:
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
```
And this in the `error.log`:
```
$ tail --lines=0 -f /var/www/MISP/app/tmp/logs/error.log
2018-08-27 16:04:33 Error: [BadRequestException] The request has been black-holed
Request URL: /taxonomies/update
Stack Trace:
#0 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(TaxonomiesController), 'blackHole', Array)
#2 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(TaxonomiesController), 'secure', Object(SecurityException))
#3 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(TaxonomiesController))
#4 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP_2.4.94/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TaxonomiesController), Object(CakeRequest))
#8 /var/www/MISP_2.4.94/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

A search of a possibly related issue, https://github.com/MISP/MISP/issues/2964, but I didn't see how to apply any solution there.

Not sure if this is our misunderstanding of the instructions, a config issue, or perhaps a bug in 2.4.94.

Help...

**Comment by Rafiot** [comment]
Not sure it is related to the taxonomy itself of MISP core, but in order to debug that, please do the following:

1. clone the misp-taxonomies directory locally
2. create the directory for your taxonomy
3. put the file in
4. add and commit the taxonomy file in the local repository
5. run `./validate_all.sh ` & fix the taxonomy if needed until it passes the tests

**Comment by github-germ** [comment]
Note: I had to hack `jq_all_the_things.sh` since we don't have `sponge` (not a big deal).

ran `validate_all.sh` using the hacked version. But, I didn't see any errors, just `diffs=14` when it ended. I also notice that the new taxonomy name is not in `MANIFEST.json`.

So, if our new `machinetags.json` isn't MISP compliant, how we do we see what to revise?

**Comment by adulau** [comment]
if you use` jsonschema -i machinetag.json schema.json` to validate the file, what's the output?

**Comment by github-germ** [comment]
in the new taxonomy subdir did this and there was no output. what does that tell us?
```
$ jsonschema -i machinetag.json ../schema.json
$ 
```

**Comment by adulau** [comment]
Looks very good ;-) Did you update the version of your file after the updates?

**Comment by github-germ** [comment]
Ha, there were no updates made to the file.  What next?

**Comment by SteveClement** [comment]
@github-germ in theory, go to list taxonomies, click on update.

**Comment by github-germ** [comment]
@SteveClement -- that's where this issue started :-) and that's where we still are.

**Comment by git-kitty** [comment]
Thanks for keeping this open. I rebuilt the JSON file from scratch with two versions - the "REF" line was apparently the issue. The file passed all prescribed validation tests, etc. Once it was removed, the ingest worked as designed. 

The issue can be closed.
