### ISSUE TITLE
Can't add ja3 signature as Network Activity

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3593]
When trying to save a ja3 object, the md5 is rejected when ja3-fingerprint-md5 has a category of Network Activity (default):
```
Could not save object as at least one attribute has failed validation (ja3-fingerprint-md5). {"type":["Options depend on the selected category."]}
```
The object can only be saved when the category is set to "External Analysis".

**Comment by adulau** [comment]
Good catch. I'll update the misp-object template.

**Comment by adulau** [comment]
Or we relax the md5 categories. What do you prefer?

**Comment by RichieB2B** [comment]
Network Activity makes more sense than External Analysis IMHO. However, without the context of the ja3 object an md5 in Network Activity can be confusing..
