### ISSUE TITLE
Snort rules as attribute

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3594]
Hi,
I've one quick question regarding Snort rules defined as attribute:
Are the Snort rule searchable?
I created a dump rule with the following msg: ”FOOBAR connection attempt”.
From "Search Attributes", I search for "FOOBAR", nothing is found.

**Comment by iglocska** [comment]
Search for:

```
%FOOBAR%
```

**Comment by xme** [comment]
"If you want a substring match encapsulate the lookup string between "%" characters."
RTFM! :-)
Thanks Andras!
