### ISSUE TITLE
How to curate disk - full disk mitigation.

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#3599]
Hello,
  Does a mechanism exist to curate the data stored? 

I am filling my test lab VM disks pretty quick and would like to know where to edit settings in order to set retention to my liking.

Thank you!

**Comment by SteveClement** [comment]
@RANGERBEE which part fills? The database? Some directory in Webroot?

There is no retention setting AFAIK.

**Comment by ghost** [comment]
Steve, I'll see if I can figure out where it's filling. I blew away the
last VM because it was so full that no services ran.

I did have many feeds selected, caching and downloading every 24hrs. I
would firstly suspect the fill is occuring whereever the feed data is
stored; I suspect the database.

Maybe a cron based script that we can enter a time duration backward and
enable from the diagnostics page?

Appreciate any help or suggestions...

**Comment by iglocska** [comment]
What probably happened was pulling the same feeds over and over into new
events. Please make sure that you select the "fixed event" option when
adding CSV/Freetext feeds!
