### ISSUE TITLE
feature request: extra hash values

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#36]
Reported by Bert XXXXX, May 31, 2012

when uploading a file attachment, have the md5,sha1,ssdeep and any 
other relevant hash auto generated as attributes for the event 
(instead of only md5)

**Comment by elhoim** [comment]
From memory, this seem to be implemented.

**Comment by iglocska** [comment]
and sha256!

**Comment by Rafiot** [comment]
Closing, will be addressed by #460
