### ISSUE TITLE
An Internal Error Has Occurred

### ISSUE THREAD

**Issue by jarmouz** [MISP/MISP#360]
Hello for all,

I have this error in GUI An Internal Error Has Occurred.

and when i run  /var/www/MISP/app/Console/worker/start.sh , i have this error 

PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 89
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/MISP/app/Config/bootstrap.php on line 92
PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 92
Stopping workers
Stopping 18219 ... Done
Stopping 18199 ... Done
Stopping the Scheduler Worker ... Done
Stopping 18239 ... Done

PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 89
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/MISP/app/Config/bootstrap.php on line 92
PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 92
Creating workers
Starting worker ... Done

PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 89
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/MISP/app/Config/bootstrap.php on line 92
PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 92
Creating workers
Starting worker ... Done

PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 89
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/MISP/app/Config/bootstrap.php on line 92
PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 92
Creating workers
Starting worker ... Done

PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 89
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/MISP/app/Config/bootstrap.php on line 92
PHP Notice:  Undefined index: SERVER_PORT in /var/www/MISP/app/Config/bootstrap.php on line 92
Creating the scheduler workers
Starting scheduler worker ... Done

**Comment by elhoim** [comment]
@jarmouz any update?

**Comment by elhoim** [comment]
No update for 23 days, closing. Feel free to re-open if it is not fixed.
