### ISSUE TITLE
Question: How to use Cortex Analyzers on MISP

### ISSUE THREAD

**Issue by joydragon** [MISP/MISP#3601]
I've been searching for the answer on how to use the MISP - Cortex integration, and I couldn't find it

The closest I've been is on this link https://blog.thehive-project.org/2017/05/17/cortex-1-1-1-two-way-misp-integration-now-a-reality/, and they explain that:

> Once this operation is completed, the Cortex analyzer list should appear in MISP’s Cortex section. 

And I don't see that section, and actually what I need is that I can select or somehow activate the analyzers for the IOCs that are on my Events.

The first thing was to check for some kind of connection errors, or authentication errors. But there's nothing to be found.

How can I do that analysis? And also, could you make the explanation of that functionality part of the MISP book?

Thanks

**Comment by SteveClement** [comment]
Dear @joydragon 

If you want a quicker answer please feel free to join the Gitter here:

https://gitter.im/TheHive-Project/TheHive
