### ISSUE TITLE
Getting a permission denied when trying to start up misp-modules via rc_local

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#3603]
**Work environment**
| Questions                 | Answers
|---------------------------|--------------------
Type of issue | Support
OS version (server) | Ubuntu
PHP version | 7.1
MISP version / git hash | v2.4.94 (b723395)

### Expected behavior
Start up misp-modules at system startup

### Actual behavior
Getting a permission denied when running the script via rc_local

### Steps to reproduce the behavior
Run the command sudo -u www-data misp-modules -l 127.0.0.1 -s &

### Logs, screenshots, configuration dump, ...
Error when running this command:
```
[1] 5015
root@misp:/# Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2571, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2663, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/misp-modules", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2607, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2573, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2601, in _build_dep_map
    for extra, reqs in split_sections(self._get_metadata(name)):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3043, in split_sections
    for line in yield_lines(s):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2262, in yield_lines
    for ss in strs:
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2621, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1404, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1400, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1512, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/cybox-2.1.0.18.dev0-py3.6.egg/EGG-INFO/requires.txt'

```

**Comment by SteveClement** [comment]
@mikemaassen can you send me the output of:

ls -la /usr/local/lib/python3.6/dist-packages/

Please.

**Comment by mik5z** [comment]
> ls -la /usr/local/lib/python3.6/dist-packages/
> total 13028
> drwxrwsr-x 159 root staff    12288 Aug  7 11:52 .
> drwxrwsr-x   3 root staff     4096 Jun  8 09:57 ..
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 aiohttp
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 aiohttp-2.3.6.dist-info
> drwxr-sr-x   8 root staff     4096 Jun  8 10:12 antlr4
> drwxr-sr-x   2 root staff     4096 Jun  8 10:12 antlr4_python3_runtime-4.7-py3.6.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 argparse-1.4.0.dist-info
> -rw-r--r--   1 root staff    89214 Jun  8 10:11 argparse.py
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 asnhistory
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 asnhistory-2.0.4.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 asnhistory-2.0.4-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 async_timeout
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 async_timeout-3.0.0.dist-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 beautifulsoup4-4.6.0.dist-info
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 bs4
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 bs4-0.0.1-py3.6.egg-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 cabby
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 cabby-0.1.20.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 certifi
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 certifi-2018.4.16.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 chardet
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 chardet-3.0.4.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 click
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 click-6.7.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 click_plugins
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 click_plugins-1.0.3-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 colorama
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 colorama-0.3.9.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 colorlog
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 colorlog-3.1.4.dist-info
> drwxr-sr-x   4 root staff     4096 Aug  7 11:52 cybox-2.1.0.18.dev0-py3.6.egg
> drwxr-sr-x   6 root staff     4096 Jun  8 10:10 dateutil
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 dateutils
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 dateutils-0.6.6.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 dateutils-0.6.6-py3.6.egg-info
> -rw-r--r--   1 root staff    15757 Nov 23  2010 distribute_setup.py
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 dns
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 dnspython-1.15.0.dist-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 dnspython3-1.15.0-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 domaintools
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 domaintools_api-0.2.2-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 domaintools_async
> -rw-r--r--   1 root staff       83 Aug  7 11:52 easy-install.pth
> -rw-r--r--   1 root staff      126 Jun  8 10:10 easy_install.py
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 ez_setup-0.9.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 ez_setup-0.9-py3.6.egg-info
> -rw-r--r--   1 root staff    15757 Nov 23  2010 ez_setup.py
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 furl
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 furl-1.1.egg-info
> drwxr-sr-x  10 root staff     4096 Jun  8 10:10 future
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 future-0.16.0.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 future-0.16.0-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 httplib2
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 httplib2-0.11.3-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 idna
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 idna-2.6.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 ipasn_redis
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 ipasn_redis-2.0.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 ipasn_redis-2.0-py3.6.egg-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 isodate
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 isodate-0.6.0.dist-info
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 jsonschema
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 jsonschema-2.6.0.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 libfuturize
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 libpasteurize
> drwxr-sr-x   6 root staff     4096 Jun  8 10:10 libtaxii
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 libtaxii-1.1.111.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 lief
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 lief-0.8.3-py3.6.egg-info
> drwxr-sr-x   6 root staff     4096 Jun  8 10:10 lxml
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 lxml-4.2.1.dist-info
> drwxr-sr-x  11 root staff     4096 Aug  2 11:16 maec
> drwxr-sr-x   2 root staff     4096 Aug  2 11:16 maec-4.1.0.13.dist-info
> -rw-r--r--   1 root staff     9661 Jun  8 10:11 magic.py
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 misp_modules
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 misp_modules-1.0-py3.6.egg-info
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 misp_stix_converter
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 misp_stix_converter-0.2.10-py3.6.egg-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 mixbox
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 mixbox-1.0.3.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 multidict
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 multidict-4.3.1.dist-info
> drwxr-sr-x   7 root staff     4096 Jun  8 10:11 nose
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 nose-1.3.7.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 oauth2
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 oauth2-1.9.0.post1.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 orderedmultidict
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 orderedmultidict-0.7.11.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 ordered_set-2.0.2.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 ordered_set-2.0.2-py3.6.egg-info
> -rw-r--r--   1 root staff     6264 Apr 19  2017 ordered_set.py
> drwxr-sr-x   6 root staff     4096 Jun  8 10:10 passivetotal
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 passivetotal-1.0.30.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 passivetotal-1.0.30-py3.6.egg-info
> drwxr-sr-x   8 root staff     4096 Jun  8 10:10 past
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 PIL
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 Pillow-5.1.0.dist-info
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 pkg_resources
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 pyaml
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pyaml-17.12.1.dist-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 __pycache__
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pydeep-0.4-py3.6.egg-info
> -rwxr-xr-x   1 root staff    35688 Jun  8 10:11 pydeep.cpython-36m-x86_64-linux-gnu.so
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 pyeupi
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 pyeupi-1.0.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pyeupi-1.0-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 pygeoip
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pygeoip-0.3.2.dist-info
> -rw-r--r--   1 root staff 11495697 Jun  8 10:11 _pylief.cpython-36m-x86_64-linux-gnu.so
> drwxr-sr-x   4 root staff     4096 Aug  7 11:39 pymisp-2.4.82-py3.6.egg
> drwxr-sr-x   4 root staff     4096 Aug  7 11:48 pymisp-2.4.93-py3.6.egg
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pyparsing-2.2.0.dist-info
> -rw-r--r--   1 root staff   231039 Jun  8 10:10 pyparsing.py
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 pypdns
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 pypdns-1.3.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pypdns-1.3-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 pypssl
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 pypssl-2.1.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pypssl-2.1-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 pytesseract
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pytesseract-0.2.2-py3.6.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 python_dateutil-2.7.3.dist-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 python_magic-0.4.15.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 pytz
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 pytz-2018.4.dist-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 PyYAML-3.12.egg-info
> drwxr-sr-x   6 root staff     4096 Jun  8 10:11 rdflib
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 rdflib-4.2.2.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 redis
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 redis-2.10.6.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 requests
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 requests-2.18.4.dist-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:10 requests_cache
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 requests_cache-0.4.13.dist-info
> drwxr-sr-x   6 root staff     4096 Jun  8 10:11 setuptools
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 setuptools-39.2.0.dist-info
> -rw-r--r--   1 root staff       39 Aug  7 11:48 setuptools.pth
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 shodan
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 shodan-1.8.1-py3.6.egg-info
> drwxr-sr-x   4 root staff     4096 Jun  8 10:12 simplejson
> drwxr-sr-x   2 root staff     4096 Jun  8 10:12 simplejson-3.15.0-py3.6.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 six-1.11.0.dist-info
> -rw-r--r--   1 root staff    30888 Jun  8 10:11 six.py
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 SPARQLWrapper
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 SPARQLWrapper-1.8.2.dist-info
> drwxr-sr-x  17 root staff     4096 Jun  8 10:10 stix
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 stix-1.2.0.6.dist-info
> -rw-r--r--   1 root staff   721269 Aug  7 11:52 stix-1.2.0.6-py3.6.egg
> drwxr-sr-x   6 root staff     4096 Jun  8 10:12 stix2
> drwxr-sr-x   2 root staff     4096 Jun  8 10:12 stix2-1.0.2.dist-info
> drwxr-sr-x   5 root staff     4096 Jun  8 10:12 stix2patterns
> drwxr-sr-x   2 root staff     4096 Jun  8 10:12 stix2_patterns-0.6.0.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 tests
> drwxr-sr-x   5 root staff     4096 Jun  8 10:11 tornado
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 tornado-5.0.2.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 tornado-5.0.2-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 url_archiver
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 urlarchiver-0.2.egg-info
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 urlarchiver-0.2-py3.6.egg-info
> drwxr-sr-x   6 root staff     4096 Jun  8 10:10 urllib3
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 urllib3-1.22.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 url_normalize
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 url_normalize-1.3.3.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:10 uwhois
> drwxr-sr-x   2 root staff     4096 Jun  8 10:10 uwhois-0.5.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 xlsxwriter
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 XlsxWriter-1.0.5.dist-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 yaml
> drwxr-sr-x   4 root staff     4096 Jun  8 10:11 yara
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 yara-1.7.7-py3.6.egg-info
> drwxr-sr-x   3 root staff     4096 Jun  8 10:11 yarl
> drwxr-sr-x   2 root staff     4096 Jun  8 10:11 yarl-1.2.5.dist-info
