### ISSUE TITLE
updating taxonomies- ifx-vetting machinetag.json error

### ISSUE THREAD

**Issue by rocio27jul** [MISP/MISP#3604]
when I tried to update taxonomies I have this error "Could not update any of the taxonomy libraries" and this happends because the new taxonomy "ifx.vetting" hasn't fill expanded field in the file machinetag.json. If I fill expanded field for example with "hello" taxonomies are update. what happens? Is the file wrong? thanks

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian8
| OS version (client)       | Debian
| PHP version               | 5.6
| MISP version / git hash   | 2.4.94
| Browser                   | If applicable

**Comment by adulau** [comment]
Indeed it was a bug. This was fixed in https://github.com/MISP/MISP/commit/c9c6f9ab332d30702e2120028a11930aaed9d7bc . Feel free to git pull the latest updates. Thank you for the report.
