### ISSUE TITLE
How to search the MISP based on one attribute

### ISSUE THREAD

**Issue by nalzaid** [MISP/MISP#3607]
I need to automate my API to make it able to do the following: 

Search my MISP instance by typing one attribute, the search results should be all the event IDs that have this attribute.. 

Example: search for IP address '127.38.37.7'  ==> results all the events that have this IP address as one of its attributes

**Comment by iglocska** [comment]
REST API or PyMISP? 

For the REST API:
url: `/attributes/restSearch/json`
body: `{"value":"127.38.37.7"}`

If it doesn't work let us know!

**Comment by nalzaid** [comment]
Thanks,, 

what about PyMISP?

**Comment by nalzaid** [comment]
@iglocska

**Comment by mokaddem** [comment]
Hello @nalzaid,
There are lots of examples in the official PyMISP repository.
This script [search.py](https://github.com/MISP/PyMISP/blob/master/examples/search.py) is probably what you want.

**Comment by nalzaid** [comment]
Thank you @mokaddem, 

It is what I want, I found it last week and I used it.

**Comment by pettai** [comment]
This should be really added to the "Automation" page in MISP + the Query Builder
