### ISSUE TITLE
Typo on serverSetting view

### ISSUE THREAD

**Issue by himynamesdave** [MISP/MISP#3612]
On server settings page (/servers/serverSettings/MISP), under setting MISP.custom_css the description reads:

If you would like to customise the css, simply drop a css file in the **/var/www/MISP/webroot/css** directory and enter the name here.

It should read:

If you would like to customise the css, simply drop a css file in the /var/www/MISP/**app**/webroot/css directory and enter the name here.

**Comment by iglocska** [comment]
Thanks a lot, should be fixed now.

**Comment by adulau** [comment]
@himynamesdave Thanks a lot for the report. Seeing that you work at anomali/threatstream, do you know if you plan to support the [standard MISP format](https://github.com/MISP/misp-rfc) in threatstream? We had the questions during some trainings.

**Comment by himynamesdave** [comment]
@adulau -- lets chat. I am the PM for integrations at Anomali and have started digging into MISP in detail this week. Can you email me so we can set up some time to talk? dgreenwood@anomali.com
