### ISSUE TITLE
Unable to import local CSV file through "Add MISP feed" web GUI.

### ISSUE THREAD

**Issue by RCPMAD** [MISP/MISP#3615]
Hi,

I am getting "For non-MISP type local feeds, please specify the file to be ingested." error whenever I try to add import a local CSV file through the "Add MISP feed" web GUI.

![image](https://user-images.githubusercontent.com/18009230/45145877-9c0d8d00-b1b9-11e8-99af-b9e9cfb0f5df.png)

Is there a specific format that I need to use?

**Comment by iglocska** [comment]
Is the apache user able to read the file? It could be a permission issue.

**Comment by iglocska** [comment]
Just to test for a potential permission issue, could you move the file to /var/www/MISP/app/tmp and make it readable by the apache user there?

**Comment by RCPMAD** [comment]
I am giving it a shot now.

**Comment by RCPMAD** [comment]
That worked.

**Comment by RCPMAD** [comment]
Ok. So I can explore the feed from the feed page and fetch the event. The event is then created but the attributes are not added or published.

**Comment by RCPMAD** [comment]
Ok, I've got the data in.

@iglocska Is there a way to also import things like attribute comments when importing CSV files? Does the CSV file need to be a specific format in order to get additional data and not just attributes?

I am exporting JSON feed from ThreatQuotient and mapping that to MISP JSON format will take some time meaning my only option is to import CSV files at the moment.

**Comment by iglocska** [comment]
Argh. Not yet, but we'll definitely do it soon. We just had a training today and it came up again, it's a recurring feature request that makes a lot of sense.

**Comment by RCPMAD** [comment]
That would be extremely useful, indicators without context and confidence level are usually pretty useless.

**Comment by SteveClement** [comment]
This seems to be solved.

For any feature requests please open a separate issue.

**Comment by chrissommer** [comment]
> 
> 
> Argh. Not yet, but we'll definitely do it soon. We just had a training today and it came up again, it's a recurring feature request that makes a lot of sense.

Do you have any news on this?
BR
Chris
