### ISSUE TITLE
Improvement on proposals

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3616]
It could be interesting to add a field on proposal to explain it (instead of putting the explanation as Contextual Comment)

**Comment by rommelfs** [comment]
Could be a duplicate of #649 and goes into the direction of #822. If so, please merge.

**Comment by SteveClement** [comment]
@Delta-Sierra please check as per @rommelfs comment.

**Comment by Delta-Sierra** [comment]
Woops, thought I closed it, since it is indeed a duplicate. Sorry for the inconvenience.
