### ISSUE TITLE
auto-syncing (pull/push) does not work anymore in 2.3 after an upgrade

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#362]
How to repeat:
 
1. install MISP pre 2.3. Find a sync server for automatic pull/push syncing. Establish it, make it work for a few times.
2. upgrade to 2.3
3. observe that the tasks table in mysql does not contain all necessary tasks 
4. even if they do, something seems to block triggering the tasks to start.

**Comment by elhoim** [comment]
Is this solved?
In the server settings panel, workers tab, are they all running?
If not, try restarting with "restart all workers".
Also try to update to the latest code, there are some problems with workers that have been fixed recently.

**Comment by mariuskagc** [comment]
Hi, I am havinig this problem too.
I can't make sync work between two servers.
All workers are running. Message in Jobs tab appears as "Job done" and progress is completed but any attribute is pulled or pushed.
Do you have any solution? 
Thanks for your work! :)

**Comment by elhoim** [comment]
Is one of the servers v2.2 or lower? From memory there were changes in the XML format used for data exchange, and I am pretty sure it was not backward compatible.

**Comment by mariuskagc** [comment]
I solved it. I think it was something about user roles. Thank you!

**Comment by elhoim** [comment]
@aaronkaplan does adding sync rights to the user you are using works?

**Comment by Rafiot** [comment]
Update?

**Comment by elhoim** [comment]
Closing, no answer. Feel free to re-open if you still have the issue.
