### ISSUE TITLE
Question: Add custom feeds through API

### ISSUE THREAD

**Issue by weslambert** [MISP/MISP#3624]
Apologies if I missed it in the documentation, but is there a way to import custom feed(s) via the API?  For example, if I have a list of threat feeds I want to add in bulk, as opposed to going the the web interface?

Thanks,
Wes

**Comment by SteveClement** [comment]
Dear @weslambert 

We are running behind our efforts of documenting every aspect of MISP, it is indeed not well documented.

Those few links should help:

Add feeds via API:
https://github.com/MISP/PyMISP/blob/master/examples/add_feed.py

Generate feeds:
https://github.com/MISP/PyMISP/tree/master/examples/feed-generator
https://github.com/MISP/PyMISP/tree/master/examples/feed-generator-from-redis

I will open an issue in misp-book to add this in the Docu!

Thanks again.

**Comment by weslambert** [comment]
Thanks, @SteveClement!
