### ISSUE TITLE
HTTP Listener with custom parser to create or enrich events

### ISSUE THREAD

**Issue by jordisk** [MISP/MISP#3629]
HTTP Listener with custom parser to create or enrich events.

As example, some security tools are able to send alerts to an specific url. Should be nice to have a way to import them into MISP as event.

**Comment by SteveClement** [comment]
Dear @jordisk 

¨some security tools¨ do you have a good example? And more importantly is it something more or less standardized the tool sends?

**Comment by mokaddem** [comment]
Feature available via the API
