### ISSUE TITLE
WebUI Event paging breaks when many attributes in the event

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3632]
2.4.94

Two related topics:
1. Issue with WebUI Paging Events with many attributes.
2. What is functional limit of attributes per event and design considerations? -- This was originally here -- spun out to #3671

**1. PAGING ISSUE**
If an event contains _many_ attributes, paging on `misphost/events/view/<event_id>` does not work. The page number links are not clickable, and pasting a page URL also doesn't work, e.g. 
`misphost/events/viewEventAttributes/<event_id>/page:<page_num>`.

In our case, _many_ attributes is 70k within this one event. I've not experimented to find the breaking threshold.

**Comment by git-kitty** [comment]
+1

I would like to also know what the limit of attributes per event is. Please and thank you!

**Comment by github-germ** [comment]
Feedback appreciated...

**Comment by SteveClement** [comment]
Dear @github-germ please consider your netiquette when it comes to a Free and Open Source Software project.

If no one answered, generally means other things are being worked on.

Also, if you have 2 issues, please open 2 issues and cross mention.
If both issues are of course very closely related, ignore my comment.

Whilst some of the details you give are really valuable, you do show at times a certain amount of impatience that is not motivating.
The core team is smaller then you think, we have over 1000 issues open and do a best effort ATM.

Rest assured that this issue will also be considered, but is low priority for now.

**Comment by github-germ** [comment]
Thx for clarifying @SteveClement Steve. My eagerness is driven by pressure from my team to deliver code for a release. I will back off. Sorry. Btw, I did spin out the 2nd part of this issue to #3671

**Comment by github-germ** [comment]
Please see a script i wrote which produces HTTP 503 when calling pymisp.add_event with a large amount of attributes --> 
https://github.com/MISP/PyMISP/issues/267#issuecomment-421624576

**Comment by github-germ** [comment]
This issue persists with MISP 2.4.96, i.e. aa event of _many_ attributes (e.g. over 100k) can load in the browser (after a few minutes); however, none of the page clicks in the page list at the bottom of the browser do anything. If I manually append `page:2` (or any other page number), that page will load (once again after several minutes).

1. Is it possible to make the page clicks active?
2. Is there any improvement possible to the load time of the first page and subsequent page loads? Just a thought... Is it taking minutes because the server-side it loading all the attributes before replying back to the browser client WebUI vs. some method to reply when the index offset and page length has been loaded?

Thanks.

**Comment by github-germ** [comment]
Issue persists with 2.4.97. Also, appears that re-sorting by clicking on Attr header titles also isn't working.

**Comment by github-germ** [comment]
@SteveClement -- Hi... Some of our MISP WebUI users are experiencing this issue and we'd like to report back on if/when this might be addressed. Any feedback, when yo have time, would be appreciated. Thanks.

**Comment by github-germ** [comment]
Any update on possibly improving performance when traversing pages for events with large sets of attributes? Thanks.

**Comment by cvandeplas** [comment]
Thank you for your report.
I understand you have issues in the very specific use-case of a slow pagination with a very large amount of attributes in one event. As mentioned before this specific use-case is unfortunately not in the top priority of the community members working on the project.
Considering this project is an open source project we also welcome any contributions in code (pull-requests) fixing the related issues. 
If this does not suffice, would you be open to paid support to help you resolve your issues?
