### ISSUE TITLE
Issue with event "Download as... MISP XML" that returns json instead of XML

### ISSUE THREAD

**Issue by l3m0ntr33** [MISP/MISP#3633]
Issue with event "Download as... MISP XML" that returns json 

### Work environment
misppriv.circl.lu

### Expected behavior
XML File format expected

### Actual behavior
JSON File format returned

### Steps to reproduce the behavior
Select any event, click download as on the left menu and select "MISP XML (metadata + all attributes) " and it returns JSON formatted output

**Comment by iglocska** [comment]
Oh wow o.O. That's annoying. Will have a look.

**Comment by vmapps** [comment]
XML content is correctly returned on previous MISP versions (tests made on 2.4.90 and 2.4.95)

**Comment by l3m0ntr33** [comment]
@vmapps you mean 2.4.90 and 2.4."**93**" ;)

**Comment by vmapps** [comment]
Update: XML content is correctly returned on previous MISP versions (tests made on 2.4.90 and 2.4.93)

**Comment by vmapps** [comment]
Update: XML content is correctly returned on MISP version 2.4.94
