### ISSUE TITLE
Get attributes with event tags

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#3638]
When using the API, I would like to get the list of attributes with the event tags. For the moment, we copy the event tag to all attributes (which more than ugly)

**Comment by iglocska** [comment]
This is now implemented via the includeEventTags parameter in the /attributes/restSearch API via the JSON and XML return formats.

**Comment by geekscrapy** [comment]
I just tested this and it works with ExpandedPyMISP however is not defined in the docs:
https://pymisp.readthedocs.io/modules.html#pymispexpanded-python-3-6-only
