### ISSUE TITLE
Override CakePHP CA File

### ISSUE THREAD

**Issue by jimbolya0607** [MISP/MISP#3653]
From MISP manual:

Certificate File: If the instance that you want to connect to has their entire own certificate chain, you can use this to import a .pem file with it and override CakePHP's standard root CA file.

Trying to connect a self-signed instance to a remote instance that uses a cert.  I can get the cert file, but how do I override?

Jimbo

**Comment by iglocska** [comment]
Just edit the sync connection, select the self signed checkbox and upload the certificate in .pem format and it should work.

![image](https://user-images.githubusercontent.com/3668672/45263043-98307380-b422-11e8-8ee2-f8fd04c42666.png)

**Comment by jimbolya0607** [comment]
Tried this - didn't work.
Having network folks double check the routes and permissions.

Jimbo

**Comment by jimbolya0607** [comment]
So haven't heard back from network folks yet, but I can reach the server that uses self-signed from the server that has it's own cert.  So I'm going to assume that the servers are talking over right network / ports. 
I just tried to push to the server and received zero events.  Not to vent, but getting beyond frustrating.  I just want to connect a pair of servers so I can parse out the information into different buckets.

**Comment by SteveClement** [comment]
@jimbolya0607 please be more specific in terms of ¨it did not work¨

WHAT exactly? Did you check the debug logs?
Have you tried openssl on the CLI?

**Comment by jimbolya0607** [comment]
So I'm thinking about putting a sync user account on the box.
I've never used those but that might fix the issue?  It looks like a sync
user bypasses certs?

Jimbo

**Comment by RichieB2B** [comment]
A sync user will change nothing about the certs. It will certainly not bypass them.

**Comment by jimbolya0607** [comment]
So far the easiest work around I've found it to simply push to the server
that uses self signed certs and then distribute from there.
I just have to keep an eye on incoming stuff to make sure the events from
push server are published; but, that would be the case for any server...
Thanks for the insights!

Jimbo

**Comment by Kagee** [comment]
Closed. Stale, old, not enough info to determine if a bug.
