### ISSUE TITLE
Broken links in v2.4.90 release post

### ISSUE THREAD

**Issue by jipegit** [MISP/MISP#3659]
There are a lot of broken links in the [v2.4.90 release post](https://github.com/MISP/MISP/releases/tag/v2.4.90) pointing to the repository instead of the website.

**Comment by rommelfs** [comment]
I'm not sure I can follow you. I checked https://misp-project.org/2018/04/20/MISP.2.4.90.released.html and it seems fine.

**Comment by jipegit** [comment]
Links are relative ones. So if you read the post from the website it's ok, but if you read the release note from Github they are broken.

**Comment by SteveClement** [comment]
Fixed. Thanks.
