### ISSUE TITLE
Mass proposals

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#366]
Allow to do mass proposals by selecting one, a subset or all attributes to propose to change:
- "to IDS";
- comment;
- category;
- type;

Main use cases:
1) change "to IDS" when a user has not been marking the events,
2) change attribute type

Related to issue #335

**Comment by iglocska** [comment]
Makes sense.

**Comment by Rafiot** [comment]
To_ids, comment and distribution can be mass-edited

**Comment by adulau** [comment]
Implemented partially.
