### ISSUE TITLE
How to add custom clusters ?

### ISSUE THREAD

**Issue by mahesh557** [MISP/MISP#3661]
Hi,

i want to remove existing clusters and have my own clusters.
i dropped the .json files to /var/www/MISP/app/files/misp-galaxy/clusters

I restarted the workers.
but i do not see them reflected in the UI.

how can implement this?

thanks,
Uma

**Comment by SteveClement** [comment]
Currently there is no UI available for that.

Ideally you do this:

* Clone the misp-galaxy repository
* Make your changes
* Point MISP to your repository
* Try to synchronize with the main repo. when needed
