### ISSUE TITLE
Can't Access Server Setting on GUI

### ISSUE THREAD

**Issue by SyGulmah** [MISP/MISP#3668]
2018-09-12 10:26:05 Error: [Error] Class 'ResqueStatus\ResqueStatus' not found
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(1020): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

When I try to run sudo -u www-data php composer.phar require kamisama/cake-resque:4.1.2 I get a file_put_contents(./composer.json): failed to open stream: Permission denied error. Please help; thank you. I am using an Ubuntu VM.

**Comment by SteveClement** [comment]
Dear @SyGulmah it seems you have permissions errors.

To reset permissions to defaults:

```
find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP/
chown -R www-data:www-data /var/www/MISP/
```

Once this is done make sure cake is correctly installed.

Feel free to re-open or join the Gitter Chat.
