### ISSUE TITLE
Database connection "Mysql" is missing, or could not be created.

### ISSUE THREAD

**Issue by zoni171** [MISP/MISP#3669]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2.
| MISP version / git hash   | v2.4.95 (e35ef26400c389f0b3e7a82bf50c1fe689608caf) 
| Browser                   | Chrome
| vSphere Client                   | V 6.0.0 Build 5112508
| VMware ESXi                   | V 6.5.0 Build 4887370

Linux <REDACTED> 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I keep getting "The CPU has been disabled by the guest  operating system. Power off or reset the virtual  machine." when trying to sync with Fidelis Barncat. Anyone has any idea on how to fix this?

When I go to Servers and hit "Pull All" it initiates the process and just halts.... I have managed to sync about 10k events only from Barncat so far..... It fails very often and I need to reset the VM in order to make MISP come back alive again.

This site can’t be reached
<myIP> took too long to respond.

I am able to Pull from CIRCL Priv instance just fine.

My last attempt I was able to get a few events only....

481 | 2018-09-12 14:59:23 | 2018-09-12 14:59:23 | 6b39410a46807192772ef4948b33c1bc | email | publish_alert_email | Event: 19219 | Sending... | REDACTED | Unknown | 0 | Queued
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
480 | 2018-09-12 14:59:23 | 2018-09-12 14:59:23 | a20c37e7c0c55c8cd9aaec11e9f63f78 | email | publish_alert_email | Event: 19218 | Emails sent. | REDACTED | Unknown | 0 | Completed
479 | 2018-09-12 14:59:22 | 2018-09-12 14:59:23 | 818d4fb5bfca05015bcacb25368bc8b8 | email | publish_alert_email | Event: 19217 | Emails sent. | REDACTED | Unknown | 0 | Completed
478 | 2018-09-12 14:59:22 | 2018-09-12 14:59:23 | 9f71bb6fda67915219a49baa17cd7071 | email | publish_alert_email | Event: 19216 | Emails sent. | REDACTED | Unknown | 0 | Completed
477 | 2018-09-12 14:59:21 | 2018-09-12 14:59:22 | 307b80caeefd63ca9ced6cc2b01954f7 | email | publish_alert_email | Event: 19215 | Emails sent. | REDACTED | Unknown | 0 | Completed
476 | 2018-09-12 14:59:21 | 2018-09-12 14:59:22 | 63ec680919b8314db510fa82de84bde7 | email | publish_alert_email | Event: 19214 | Emails sent. | REDACTED | Unknown | 0 | Completed
475 | 2018-09-12 14:59:21 | 2018-09-12 14:59:22 | f0f61e406f2e410ec8f6bccb4789cfee | email | publish_alert_email | Event: 19213 | Emails sent. | REDACTED | Unknown | 0 | Completed
474 | 2018-09-12 14:59:21 | 2018-09-12 14:59:22 | 6977d073ece29338d1e32b1175e98962 | email | publish_alert_email | Event: 19212 | Emails sent. | REDACTED | Unknown | 0 | Completed
473 | 2018-09-12 14:59:20 | 2018-09-12 14:59:22 | a30ffd56b1d23a5f074962d941f297c4 | email | publish_alert_email | Event: 19211 | Emails sent. | REDACTED | Unknown | 0 | Completed
472 | 2018-09-12 14:59:20 | 2018-09-12 14:59:22 | c433d0419d41e2418087da50a9f4b566 | email | publish_alert_email | Event: 19210 | Emails sent. | REDACTED | Unknown | 0 | Completed
471 | 2018-09-12 14:58:19 | 2018-09-12 14:58:19 | e0c1883d60952a68c06b5c716fd0330a | default | pull | Server: 2 | Pulling. | SYSTEM | Unknown | 0 | Queued
470 | 2018-09-12 14:40:40 | 2018-09-12 14:40:40 | 1eded0a2aa13bd04c73129f297f78edb | default | pull | Server: 2 | Pulling. | SYSTEM | Unknown | 0 | Queued

**Comment by SteveClement** [comment]
Did you use our generated VM?

**Comment by zoni171** [comment]
> 
> 
> Did you use our generated VM?

I did not. I followed the instructions on https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1804.txt

Oh and I see this on **/var/www/MISP/app/tmp/logs/error.log**


2018-09-12 13:29:24 Error: [MissingControllerException] Controller class ImgController could not be found.
Exception Attributes: array (
  'class' => 'ImgController',
  'plugin' => NULL,
)
Request URL: /img/orgs/REDATCTED.png
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-09-12 16:06:26 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] **Connection refused**',
  'enabled' => true,
)
Request URL: /jobs
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(109): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}


And a few errors like this on **/var/www/MISP/app/tmp/logs/debug.log**

2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 18]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 18
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 1]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/global_menu.ctp, line 1
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 46
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 10]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Elements/global_menu.ctp, line 10
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
include - APP/View/Layouts/default.ctp, line 46

**Comment by stansecurecom** [comment]
> > Did you use our generated VM?
> 
> I did not. I followed the instructions on https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1804.txt
> 
> Oh and I see this on **/var/www/MISP/app/tmp/logs/error.log**
> 
> 2018-09-12 13:29:24 Error: [MissingControllerException] Controller class ImgController could not be found.
> Exception Attributes: array (
> 'class' => 'ImgController',
> 'plugin' => NULL,
> )
> Request URL: /img/orgs/REDATCTED.png
> Stack Trace:
> #0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #1 {main}
> 2018-09-12 16:06:26 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
> Exception Attributes: array (
> 'class' => 'Mysql',
> 'message' => 'SQLSTATE[HY000] [2002] **Connection refused**',
> 'enabled' => true,
> )
> Request URL: /jobs
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
> #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
> #2 /var/www/MISP/app/Controller/AppController.php(109): ConnectionManager::getDataSource('default')
> #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
> #7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #8 {main}
> 
> And a few errors like this on **/var/www/MISP/app/tmp/logs/debug.log**
> 
> 2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 18]
> Trace:
> ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
> include - APP/View/Layouts/default.ctp, line 18
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
> View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
> Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
> ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
> ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
> ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
> ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
> [main] - [internal], line ??
> 
> 2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: debugMode in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 1]
> Trace:
> ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
> include - APP/View/Elements/global_menu.ctp, line 1
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
> View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
> include - APP/View/Layouts/default.ctp, line 46
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
> View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
> Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
> ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
> ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
> ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
> ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
> [main] - [internal], line ??
> 
> 2018-09-12 16:06:26 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Elements/global_menu.ctp, line 10]
> Trace:
> ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
> include - APP/View/Elements/global_menu.ctp, line 10
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
> View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
> include - APP/View/Layouts/default.ctp, line 46

So, did you solver the issue?

**Comment by iglocska** [comment]
Your MySQL isn't set up or the connection isn't set up correctly in /var/www/MISP/app/Config/database.php
