### ISSUE TITLE
Attribute limit per event: maximal + practical

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3671]
This was spun out from #3632 

Would be helpful if we could get some insight from the MISP team along with other folks solutions...

- We are experimenting creating events from a feed that has a long list of IOCs with hardly any context that we update hourly.
- We've been partitioning the events by IOC category which produces a large number of attributes for some events in some hourly segments (e.g. 20k).
- We believe this does not fit the MISP model or intent and are looking into some other designs, e.g.
   - We could try further partitioning these events for a time span (attributes for yyyymmdd) and then delete events that are deemed aged-out.
   - Another choice might be still using the events as we have them now, and pruning attributes that have aged-out.
   - However, on both these solutions, we would still store IOCs for the hour with the greatest count at times (e.g. that 20k I mentioned in #3632 ).

Suggestions quite welcome. Thanks...

**Comment by github-germ** [comment]
Please see a script i wrote which produces HTTP 503 when calling pymisp.add_event with a large amount of attributes --> 
https://github.com/MISP/PyMISP/issues/267#issuecomment-421624576

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
