### ISSUE TITLE
Feature : Attributes to store start time and end time of an attack

### ISSUE THREAD

**Issue by Te-k** [MISP/MISP#3675]
Hi,

Let me know if there is a better place to ask for this feature.
I am trying to store in MISP information about the start and end time of an attack. I have noticed that there is an attribute datetime in other, but there is not way to give the start and end time, or the duration.

It would be helpful either : 
1.  To add two attributes datetime-start and datetime-end in the attributes
2. To change the date of the event to start and end

I think 1) is a better option because it does not bother people who are using MISP in a different way.

What do you think ?

**Comment by adulau** [comment]
We have a branch with that (which add timestamp on attributes and objects) : https://github.com/MISP/MISP/tree/zoidberg 

The current issue we have to merge it are all the users running older version of MySQL where the precision is missing. There is also an additional time-based UI too. By the way, we need testers for this branch, if you have some time that would be really cool.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
