### ISSUE TITLE
ATT&CK Matrix improvement - description popup

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3677]
It could be nice to add a fourth button (perhaps a question mark) that will trigger a popup with the description of the cluster.
![screenshot from 2018-09-14 08-44-46](https://user-images.githubusercontent.com/17081497/45534629-15c9fa00-b7fc-11e8-82f9-f7f6591e22cb.png)

**Comment by mokaddem** [comment]
Fixed with 4daca2c
