### ISSUE TITLE
Minor GUI issue - galaxy clusters display

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3678]
It might be better if the + (plus) sign in front of galaxies switch to - (minus) when the details of the clusters are shown, and back to + when these information are collapsed.
-That's how the different parts of the event already behave.
![closedgalaxy](https://user-images.githubusercontent.com/17081497/45536690-7b20e980-b802-11e8-87f5-9119a27855a1.png)
![openedgalaxy](https://user-images.githubusercontent.com/17081497/45536691-7bb98000-b802-11e8-98c3-005021b73b16.png)

**Comment by iglocska** [comment]
failcode fixed, thanks!
