### ISSUE TITLE
Propose new attribute type "malware-configuration"...

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#3679]
...as currently there's no distinct type within the _Artifacts dropped_ category and, personally, I wouldn't use _malware-sample_ here.

**Comment by adulau** [comment]
We had some discussions sometime ago especially for the use-case of Fidelis Security (barncat MISP).  I was thinking of creating an object template with the following format:

| field  | misp-attribute-type | description|
| ------------- | ------------- | ------------ |
| config | text  | clear raw configuration of the malware |
| format  | text  | [JSON, YAML, INI, other] |
| encrypted | text | encrypted or encoded version of the configuration  |
| first-seen | datetime |  First time this configuration was seen |
| last-seen | datetime |  Last time this configuration was seen |
 
If this is fine for you, I'll do it.

**Comment by StefanKelm** [comment]
That's a great idea! Thank you.
