### ISSUE TITLE
Modify SyncTool to allow syncrhonisation from behind proxy

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#368]
Allow SyncTool to support optional arguments for connecting to MISP instances for pulling data from behing a proxy.

Restrict the configuration of this to instance admins, and only a single global value.

**Comment by RichieB2B** [comment]
I remember this being discussed before. Is this already in development? If not, I might take a look at this.

**Comment by RichieB2B** [comment]
Looks like this implementing this will be complicated by issue https://github.com/cakephp/cakephp/issues/2057 that has not been fixed just yet.

**Comment by elhoim** [comment]
I quickly checked the cakephp issue you mentionned, and it seems to be implemented in a commit mentioned in it. However I am a bit lost with the branches and I am not sure it is now present in the latest stable version of cakePHP.
If it is, can you please let me know, so that I can close this issue?

**Comment by RichieB2B** [comment]
The SSL via proxy is fixed in CakePHP 2.6.4. MISP merge request #443 also includes this fix for CakePHP. This issue can closed.

**Comment by elhoim** [comment]
Cool, thanks!
