### ISSUE TITLE
MISP search using PyMISP from server side

### ISSUE THREAD

**Issue by nalzaid** [MISP/MISP#3681]
Hi,, 

How can I search the MISP based on events attributes from the server side? 

My current solution is not practical because I use shell_exec("") in the php code that will execute search.py from the terminal (shell command)

Here is my php code: 
 ```
<?php

if (isset($_POST["query"]))
{
  $output = shell_exec('python search.py -a -p values -s' . $_POST["query"]);
  echo $output;
}
?> 
```

This code will search the MISP using the user's query, it will retrieve all the events that have this query as an attribute.
 I need another way to handle the search by not using shell_exec

**Comment by adulau** [comment]
Not sure, I understand what you try to achieve. 

Why are you running Python script within PHP/MISP for doing search queries on the server-side?

**Comment by nalzaid** [comment]
@adulau I'm building a website that have the ability to search my MISP instance. So, what I'm trying to do now is to have an API to my MISP. 

I need a way to run search.py (PyMISP) from the web page other than shell command execution (mentioned above).

**Comment by iglocska** [comment]
You could just use misp's api. Go to event actions - automation to see the available endpoints and filters, pymisp basically does the same thing and is meant to make your life easier if you work with python.

Since you are writing php coffee, might as well use the rest api.

**Comment by nalzaid** [comment]
Thank you @iglocska. 

can I use misp's api whiten my webpage? (I mean I want the query and the result to be in the same webpage)

**Comment by nalzaid** [comment]
I'm doing this webpage for end users who don't have any misp experience or knowledge. 

They want to search the misp this way: they will provide an attribute ( url, domain, ip @ ...etc) and they want to know if it is malicious or not (is it in the misp already or not) the output of their query is the list of events who have this attribute if any.

**Comment by iglocska** [comment]
Sure you can. Here is a small example on how to check if an IP exists against my dev instance:

```
	public function test() {
		$ch = curl_init('http://localhost:5000/attributes/restSearch');
		$query = array(
			'returnFormat' => 'json',
			'type' => ['ip-dst', 'ip-src'],
			'value' => '8.8.8.8'
		);
		$headers = array(
			'Authorization: WL7SHaGXeh0JDK0necAw89AASEaoML28N0uCq53k',
			'Accept: application/json',
			'Content-Type: application/json'
		);
		$query = json_encode($query);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		$result = curl_exec($ch);
		return json_decode($result, true);
	}
```

**Comment by nalzaid** [comment]
@iglocska Thank you so much.. 

This is very useful :)

**Comment by iglocska** [comment]
No worries, just have a look at the various APIs in the automation page and what you can filter on. I'll close the issue for now, feel free to open a new one if you have any more questions!
