### ISSUE TITLE
Default “CoinBlockerLists” in MISP feeds links are broken

### ISSUE THREAD

**Issue by lctrcl** [MISP/MISP#3682]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | latest training VM
| MISP version / git hash   | 2.4.95, bf59f3bca0ce2cbbc9e2badedd2c527aa0c1dc4f

### Expected behavior

“CoinBlockerLists” lists are available

### Actual behavior

“CoinBlockerLists” lists are broken (404)

### Fix

Default “CoinBlockerLists” in MISP feeds links are broken (404). Maintainer have moved them to GitLab. New valid links are:

- id 44 - “This list contains all domains - A list for administrators to prevent mining in networks” - https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list.txt?inline=false
- id 45 - “This list contains all optional domains - An additional list for administrators” - https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_optional.txt?inline=false
- id 46 - “This list contains all browser mining domains - A list to prevent browser mining only” - https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt?inline=false
- id 47 - “This list contains all IPs - A additional list for administrators to prevent mining in networks” - https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/MiningServerIPList.txt?inline=false

**Comment by adulau** [comment]
Nice finding! We updated the default feed list. Thank you for the contribution.
