### ISSUE TITLE
Instance local tags and exportable tags

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#369]
Add an option to tags to be local to the instance or exportable with events.
This can accomodate lots of different use-cases.

Related to issue #320

**Comment by iglocska** [comment]
Indeed, this is planned!

**Comment by elhoim** [comment]
Cool!

From the wording of issue 320 I thought that the tags would all be global/exportable.

**Comment by iglocska** [comment]
That was indeed the plan, sorry missed the option part :) With that said, I
see no reason why it shouldn't be an option left up to the tag creator
whether it should be exportable.

**Comment by mari0d** [comment]
+1 for exportable tags, but need the option to designate a tag as exportable.

**Comment by threatty** [comment]
+1 on exportable tags. That's basically the only thing I'm missing from a REST-perspective.

**Comment by iglocska** [comment]
It's already on the 2.4-beta branch and it's optional :) Official launch is now scheduled for the 10th of December
