### ISSUE TITLE
Feature request - View logs from Admin menu

### ISSUE THREAD

**Issue by alecisec** [MISP/MISP#3690]
Not sure how much work this would require but would it be possible to have a 'logs' screen long with the Jobs/Scheduled Tasks/Workers admin options?
The logs themselves are somewhat difficult to access for more notice users, making troubleshooting difficult.

**Comment by SteveClement** [comment]
@alecisec I am not fully sure what you are asking :(

Please feel free to re-open if this is still an issue of interest.

**Comment by alecisec** [comment]
I simply mean having the logs presented via the web, as opposed to having to log into a CLI and read the .log files off the disk. It is possible that admins may not have access to ssh to a box running misp and only be provided web and api access.
