### ISSUE TITLE
Installation error PIP3 lib

### ISSUE THREAD

**Issue by zlob-bik** [MISP/MISP#3691]
root@MISP-Deb:/MISP/app/files/scripts/python-stix# sudo pip3 install .                   Processing /MISP/app/files/scripts/python-stix
Requirement already satisfied: cybox<2.1.1.0,>=2.1.0.13 in /usr/local/lib/python3.5/dist-packages (from stix==1.2.0.6)
Requirement already satisfied: lxml>=2.3 in /usr/local/lib/python3.5/dist-packages (from stix==1.2.0.6)
Requirement already satisfied: mixbox>=1.0.2 in /usr/local/lib/python3.5/dist-packages (from stix==1.2.0.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.5/dist-packages (from stix==1.2.0.6)
Collecting importlib (from cybox<2.1.1.0,>=2.1.0.13->stix==1.2.0.6)
  Using cached https://files.pythonhosted.org/packages/31/77/3781f65cafe55480b56914def99022a5d2965a4bb269655c89ef2f1de3cd/importlib-1.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/usr/lib/python3.5/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/lib/python3.5/distutils/dist.py", line 19, in <module>
        from distutils.util import check_environ, strtobool, rfc822_escape
      File "/usr/lib/python3.5/distutils/util.py", line 9, in <module>
        import importlib.util
    ImportError: No module named 'importlib.util'

ERROR:
   File "/usr/lib/python3.5/distutils/util.py", line 9, in <module>
        import importlib.util
    ImportError: No module named 'importlib.util'

**Comment by adulau** [comment]
I just did a test and it works as expected (Python 3.6 - Ubuntu 18.04):

~~~~
adulau@dobbertin:~/git/MISP/app/files/scripts/python-stix$ sudo pip3 install . 
Processing /home/adulau/git/MISP/app/files/scripts/python-stix
Requirement already satisfied: lxml>=2.3 in /home/adulau/.local/lib/python3.6/site-packages (from stix==1.2.0.6) (4.2.2)
Requirement already satisfied: python-dateutil in /home/adulau/.local/lib/python3.6/site-packages (from stix==1.2.0.6) (2.7.3)
Collecting cybox<2.1.1.0,>=2.1.0.13 (from stix==1.2.0.6)
  Downloading https://files.pythonhosted.org/packages/8f/7e/14db0a8ae5f47d9b066a1f3cb0b6830727f68ecaeed10b9d1548903c4836/cybox-2.1.0.17-py2.py3-none-any.whl (734kB)
    100% |████████████████████████████████| 737kB 4.8MB/s 
Requirement already satisfied: mixbox>=1.0.2 in /home/adulau/.local/lib/python3.6/site-packages (from stix==1.2.0.6) (1.0.3)
Requirement already satisfied: six>=1.5 in /home/adulau/.local/lib/python3.6/site-packages (from python-dateutil->stix==1.2.0.6) (1.11.0)
Requirement already satisfied: ordered-set in /home/adulau/.local/lib/python3.6/site-packages (from mixbox>=1.0.2->stix==1.2.0.6) (3.0.0)
Installing collected packages: cybox, stix
  Running setup.py install for stix ... done
Successfully installed cybox-2.1.0.17 stix-1.2.0.6
~~~~

Could you update your pip3 to the latest version? to be sure.

**Comment by zlob-bik** [comment]
Update:
root@MISP-Deb:/var/www/app/files/scripts/python-cybox# sudo -H pip3 install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (18.0)
root@MISP-Deb:/var/www/app/files/scripts/python-cybox# sudo -H pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (18.0)
root@MISP-Deb:/var/www/app/files/scripts/python-cybox#

Same problem.
Deb 9.4
Setup guide from deb9.txt

**Comment by zlob-bik** [comment]
> I just did a test and it works as expected (Python 3.6 - Ubuntu 18.04):
> adulau@dobbertin:~/git/MISP/app/files/scripts/python-stix$ sudo pip3 install . 
> Processing /home/adulau/git/MISP/app/files/scripts/python-stix
> Requirement already satisfied: lxml>=2.3 in /home/adulau/.local/lib/**python3.6/**site-packages (from stix==1.2.0.6) (4.2.2)
> Requirement already satisfied: python-dateutil in /home/adulau/.local/lib/python3.6/site-packages
> Could you update your pip3 to the latest version? to be sure.

Python 3.6 for Debian 9 is available in the testing repository.

**Comment by zlob-bik** [comment]
And after upgrade to PY3.6:
with Python-stix - all good
with python-cybox:
root@MISP-Deb:/var/www/app/files/scripts/python-cybox# sudo pip3 install .
Processing /var/www/app/files/scripts/python-cybox
  Ignoring importlib: markers 'python_version == "2.6"' don't match your environment
Requirement already satisfied: lxml>=2.2.3 in /usr/local/lib/python3.6/dist-packages (from cybox==2.1.0.18.dev0) (4.2.5)
Requirement already satisfied: mixbox>=1.0.2 in /usr/local/lib/python3.6/dist-packages (from cybox==2.1.0.18.dev0) (1.0.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from cybox==2.1.0.18.dev0) (2.7.3)
Requirement already satisfied: ordered-set in /usr/local/lib/python3.6/dist-packages (from mixbox>=1.0.2->cybox==2.1.0.18.dev0) (3.0.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->cybox==2.1.0.18.dev0) (1.10.0)
Building wheels for collected packages: cybox
  Running setup.py bdist_wheel for cybox ... done
  Stored in directory: /root/.cache/pip/wheels/0a/02/54/081d2f31e75c0972a379c4c268be9266e507f81a4f413fae85
Successfully built cybox
### **cybox 2.1.0.18.dev0 requires importlib, which is not installed.**
Installing collected packages: cybox
  Found existing installation: cybox 2.1.0.17
    Uninstalling cybox-2.1.0.17:
      Successfully uninstalled cybox-2.1.0.17
Successfully installed cybox-2.1.0.18.dev0

**Comment by ViolatorDM** [comment]
I'm having the exact same issue as posted in https://github.com/MISP/MISP/issues/6702.

I see this issue as being closed - what is the solution?
