### ISSUE TITLE
API related bugs 

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3695]
tl;rd: all the FIXME here should pass fine, I think: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L440

Details:

- [x] getting the JSON output with attachment doesn't work. Just go on an event with an attachment, download (attachment box ticked), it won't be there. It is possible to download the attachment from the attribute.
- [x] updating a MISP event with an attribute containing a malware-sample fails when the value is `filename|md5`. Works fine when value is just the filename (it was working before, I patched pymisp)
- [x] search API: to_ids flag doesn't do anything (all the attributes are always returned)
- [x] search API: include_event_uuid, the attributes don't contain the event UUID
- [x] search API: event_timestamp doesn't do anything (I get all the event or all the attributes depending on the controller I call)
- [x] search API: searchall doesn't do anything
- [x] search API: with_attachment doesn't do anything
- [x] search API: sg_reference_only, eventinfo and searchall  aren't documented on the automation page
- [x] search API: is event_timestamp supposed to take intervals?

**Comment by iglocska** [comment]
include_event_uuid works but it's spelled includeEventUuid, but adding a catcher for the other format.

**Comment by iglocska** [comment]
to_ids was already fixed a few days ago

**Comment by Rafiot** [comment]
* [x] includeEventUuid to true doesn't return the Event UUID at attribute level
* [x] to_ids works fine except `exclude`: it does the same as `1` instead of excluding the attributes with the to_ids flag set
* [x] quickfilter returns everything

## Issue with eventinfo search

Context:
* event 1, info field == foo bar blah
* event 2, info field == foo blah

Search query: `%bar blah%`

* [x] both events are returned (edit: it returns everything on the MISP instance)

**Comment by iglocska** [comment]
Pushed several fixes.

**Comment by iglocska** [comment]
All restsearch related issues should be fixed.

**Comment by github-germ** [comment]
> All restsearch related issues should be fixed.

Hi @iglocska ... Nice to see this progress: Thanks!!

Does "All" include the recent performance issues or just the long list above?

**Comment by iglocska** [comment]
It should be much improved on the attributes controller - events controller still coming up!

**Comment by SteveClement** [comment]
@Rafiot @iglocska bump?
