### ISSUE TITLE
How to know that what relationship between event and feed？

### ISSUE THREAD

**Issue by allenxian** [MISP/MISP#3696]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by iglocska** [comment]
Errr...

**Comment by allenxian** [comment]
I mean when i pull event from feed，how can i know what feed contain this event。

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
