### ISSUE TITLE
Issue with MISP training VM Image 

### ISSUE THREAD

**Issue by robotbond** [MISP/MISP#3697]
Hello Developers, 

I have been trying to load MISP training .ova image into VMware workstation Pro but getting below error. Apparently, it doesn't seems to be a compatibility issue as I tried loading same image into VMwae player but getting same error. Can someone shed some light on this issue ? 

File name -   MISP_v2.4.95@c4a96013e2400c11bcfcdc5e5fad87e177e2bed6.ova (Lastest image downloaded yesterday) 

Error Message - 
"The import failed because C:\Users\shashank4.jain\Documents\MISP_v2.4.95@c4a96013e2400c11bcfcdc5e5fad87e177e2bed6.ova did not pass OVF specification conformance or virtual hardware compliance checks.

Click Retry to relax OVF specification and virtual hardware compliance checks and try the import again, or click Cancel to cancel the import. If you retry the import, you might not be able to use the virtual machine in VMware Workstation."

Regards,
Robert

**Comment by adulau** [comment]
Maybe you tried to download as OVF an OVA file? There is a conversion tool called 'ovftool.exe' if needed.

**Comment by robotbond** [comment]
Thanks for the comment @adulau. Using ovftool.exe, I converted downloaded OVA file to OVF but it also didn't work. Can you help me understand which file should I download from https://www.circl.lu/misp-images/latest/ ?

**Comment by adulau** [comment]
If you are using VirtualBox, the OVA works out-of-the-box.
If you are using VMware, you might want to have a look at https://www.circl.lu/misp-images/latest/MISP_v2.4.95@32a171deb36821d0bb44a78498738baa5a8b8f17-vmware.zip 

Cheers

**Comment by robotbond** [comment]
Thanks ! Appreciated
