### ISSUE TITLE
CSV export issues

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3699]
* [x] by default, the CSV export contains the attributes with the to_ids flag set to False 
* [ ] headerless=True doesn't do anything
* [x] includeContext doesn't include context

**Comment by kalyparker** [comment]
I confirm the behavior on includeContext

**Comment by devnull-** [comment]
Hello all,

I also confirm this issue. An empty file (only the header line) is returned when you want to download the attributes in CSV format (click "Download as..." -> "CSV").

For me, no export functions are working (except MISP XML and MISP Json export). All files are empty. -- I created a dedicated issue #3740 to solve all export functions.

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.95 (commit: e7ae566c408907f3f7d82fe0bad2258227ed8b91)

**Comment by SteveClement** [comment]
This seems to be solved. Please re-open if not.
