### ISSUE TITLE
Read-only API key

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#370]
Allow an API to be read-only without the possibility to insert data using that API key.

Use cases could be to allow sharing of data with some partners or with public without needing/wanting them to be able to create events.

Related to issues #352 and #347 .

**Comment by Rafiot** [comment]
What about creating a user with with RO rights?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)

**Comment by elhoim** [comment]
So for this, it is not possible to create a role with permission _Read Only_ and add other perms such as API (_perm_sync_) for example, since it is disable by default via Javascript ([here](https://github.com/MISP/MISP/blob/2.4/app/View/Roles/admin_add.ctp#L35)).

**Comment by elhoim** [comment]
I am not sure if the combination of **read only** and **perm_sync** would work.
Oh great @iglocska could you enlighten us with you wisdom? 😄

**Comment by cristianbell** [comment]
I guess this should be also closed as #1998

**Comment by iglocska** [comment]
Yes, we've had the read only API key much longer than the read only sync role
