### ISSUE TITLE
PyMISP Slow for Add Attributes

### ISSUE THREAD

**Issue by jgrosfelt** [MISP/MISP#3700]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug or Question.
| OS version (server)       |ubuntu,
| OS version (client)       | Ubuntu 18.04 Server
| PHP version               | 7.2
| MISP version / git hash   | 2.4.95
| Browser                   | If applicable

I am not sure if this is a bug or not, but I am testing MISP as a possible replacement for platforms that provide TIP like functionality. In this case, I have a commercial feed that provides a list of Suspicious/Malicious IP Addresses and Domains, when combined, this list can get well over 500k indicators. 

I have tried to import these indicators via PyMISP and using the "add_attributes" call but it is incredibly slow,  on average I am seeing about 10,000 indicators every 5 minutes. This would be about ~4 hours for the import, this wouldn't work as the list is dynamic and I would want to update/reload every 2-3 hours.

Is there a faster/better way to import this amount of indicators? Or, would this not be the intended use? Should only high-fidelity indicators go into MISP?

Please advise.

Thanks in advance
-Justin

**Comment by SteveClement** [comment]
Ingesting 10k attributes can be taxing but not impossible. (depending on your hardware)
For those volumes you need Metal.

Also, if you generate 10k events, that would be bad and ill-advised.

Using PyMISP is the best way to do this.

If this is still an issue of interest, please try with the latest MISP release and eventually pull @Rafiot into the discussion who has quite some experience with those performance questions.
