### ISSUE TITLE
Check for Python Virtualenv

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#3703]
It would be nice to be able to install ALL the Python dependencies for MISP into a VENV and then MISP just picks it up and runs python from there, see: [Run Python Script from PHP with virtualenv activated](https://stackoverflow.com/questions/9738418/activate-virtualenv-from-python-or-php-script-not-ssh)

* Have a configurable to define the path to the VENV (have a default of: /var/www/MISP/venv)
* Potentially autodetect and prefer such a setup
* Gotchas (well not really but udpates matter): How to update the venv from the UI, does that want to be included in EVERY update.

**Comment by FloatingGhost** [comment]
The `activate` step is unneeded - your best bet here would be a configurable `python` executable path - if you point that to your env executable it'll automatically "activate" 

i.e `Configure::write("python", "/var/www/MISP/venv/bin/python3")`

**Comment by SteveClement** [comment]
@FloatingGhost I implemented it. Thanks for the feedback.

PR coming soon.
