### ISSUE TITLE
Slow pulls of data use Rest and Text

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#3704]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.95 (f3e6761440c9d89a1b3e72da670c9131ae582dc5) 
| Browser                   | If applicable

### Expected behavior
Quick pulls of IOCs based on type, less than 5 mins

### Actual behavior
Pulls either take longer than 5 mins or fail completely. Seems to depend on attribute type. SHA256 works, domain does not. 

### Steps to reproduce the behavior
Do a pull in any fashion: 
```
https://<misp-url>/attributes/text/download/domain/null/null/false/null/null/1d/true/false
```
or 
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import requests
import pymisp
import json
import sys
from datetime import datetime
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

url_pull = 'https://<misp_url>/attributes/restSearch'
headers_pull = {'Authorization': '<key>', 'Content-Type': 'application/json', 'Accept': 'application/json'}
data_pull = {"requestFormat" : "json", "type": "domain", "category": "Network activity", "last": "1d", "to_ids": 1}

print(datetime.now().strftime('%Y-%m-%d %H:%M:%S') + ' Starting master_qradar_misp_domain.py...')

# Pull the list of attributes from TIA-REPO
r = requests.post(url_pull, headers=headers_pull, json=data_pull, verify=False)
r.raise_for_status() #Raise exception on HTTP errors

print("Pull from MISP complete...extracting IOCs from JSON...")

j1 = r.json()

j2 = j1['response']

if type(j2) == list:
    print('No IOCs to push...stopped at ' + (datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + '\n')
    sys.exit()
else:
    j3 = j2['Attribute']

iocs = []

for item in j3:
    iocs.append(item["value"])

iocs = list(set(iocs))
print(iocs)
number_of_IOCs = str(len(iocs))
```

### Logs, screenshots, configuration dump, ...
```
[Thu Sep 20 15:09:18.440233 2018] [php7:error] [pid 4477] [client 10.2.32.85:59185] PHP Fatal error:  Maximum execution time of 1200 seconds exceeded in /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/CakeText.php on line 241
```
```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 10055947 (char 10055946)
```

**Comment by syloktools** [comment]
If I do hostname instead of domains for last 1 hour:
```
Response code: 200
Request duration: 1775.2ms
Headers
  Date: Thu, 20 Sep 2018 19:42:23 GMT
  Server: Apache/2.4.29 (Ubuntu)
  Set-Cookie: CAKEPHP=5m6om5vg46m4folknk5l4rshpn; expires=Thu, 20-Sep-2018 21:12:23 GMT; Max-Age=5400; path=/; secure; HttpOnly
  Content-Length: 6300232
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Connection: close
  Content-Type: application/json; charset=UTF-8
```

**Comment by syloktools** [comment]
domain I get:
```
Response code: 0
Request duration: 30028.35ms
Headers
```
![image](https://user-images.githubusercontent.com/20773170/45842907-0e1ebf80-bcec-11e8-88c6-cbe6db8db1c3.png)

**Comment by adulau** [comment]
I just did a test with a production instance for 1day with your Python script:

~~~~
real	0m0.846s
user	0m0.344s
sys	0m0.037s
~~~~

How large is your dataset?

**Comment by syloktools** [comment]
![image](https://user-images.githubusercontent.com/20773170/45878661-eb35ef00-bd6f-11e8-8aa4-f6d52ac277dd.png)

**Comment by syloktools** [comment]
It only seems to happen on the domain type for some reason.

Using the REST client in the GUI:

url:
![image](https://user-images.githubusercontent.com/20773170/45878937-d86fea00-bd70-11e8-8dd5-8728d669120a.png)

vs. domain:
![image](https://user-images.githubusercontent.com/20773170/45879032-08b78880-bd71-11e8-9ef2-7ea4793f6419.png)

**Comment by adulau** [comment]
Looking at the statistics, there is obviously something wrong with this instance (the number of correlations). I'm betting you have highly correlating events. Did you enable all the feeds and create each time a new event with the same highly correlating values (the default config is not very sane ;-)? If yes, I would advise to change this config "New event at each pull" -> "Fixed event". Drop the correlation the table and re-trigger the correlation from the UI (via legacy tool).

**Comment by syloktools** [comment]
I truncated the correlations table and ran the same rest search from the GUI like pictured above. It gave the same error. Correlations right now are at 0. Running the re-correlate script now. Also I have feeds enabled but they are all set to fixed events with delta merge. 

![image](https://user-images.githubusercontent.com/20773170/45932582-51776900-bf4c-11e8-89b9-77c0d2396dea.png)
![image](https://user-images.githubusercontent.com/20773170/45932629-fd20b900-bf4c-11e8-8950-d36af3b3476f.png)
![image](https://user-images.githubusercontent.com/20773170/45932646-39541980-bf4d-11e8-9004-fcd65f3451e2.png)

**Comment by syloktools** [comment]
To add:
when I run the following statement against the db directly via the command line it takes 1.93 seconds to return almost all the domains in the instance. 

select value1 from attributes where type = 'domain' AND to_ids = 1;

**Comment by iglocska** [comment]
can you show the PHP settings from your MISP diagnostics screen? Querying the database will of course be fast, it only fetches data from one table (restSearch takes ACL into account along with tags, the event it belongs to etc)

**Comment by syloktools** [comment]
I know but I wanted to show it just in case it offered a clue to why it is only effecting domains. 

I bumped all of these up since we have been troubleshooting. They have always at least been the recommended values. 

![image](https://user-images.githubusercontent.com/20773170/45948859-a7d5bd80-bfc7-11e8-9301-23b7ad5c58d9.png)

**Comment by iglocska** [comment]
Holy cow those are indeed some pretty high numbers. I am experimenting with several improvements to get the performance down to more manageable numbers, one of which is to rework the internal pagination to align the chunk sizes with your memory limit. That should help a lot in itself, but still not sure why you're having such attrocious performance, I mean I am seeing some slowdowns but nothing to the same degree.

**Comment by syloktools** [comment]
What's weird is that it is not timing out or anything it just doesn't like the domain type. I mean that is probably the type with the most attributes but still. It seems like it is getting and error and just silently dying.

**Comment by iglocska** [comment]
could you check how many domains you have in your system? Just to have a better idea how to reproduce it.

**Comment by syloktools** [comment]
494485 total, 468149 unique. 

![image](https://user-images.githubusercontent.com/20773170/45952390-ddcd6e80-bfd4-11e8-8f8f-aa323e483f2d.png)

**Comment by syloktools** [comment]
I ended up having to delete the /var/www/MISP directory and pull it back down. Then I was able to sort events based of the number of attributes. Before I did that I disabled all feeds temporally. I deleted some feeds such as the Domain DGA feed that was apparently the source of the issue. Now that I do not have those events with 100,000 to 200,000 domains in them, the REST search for domains comes back with a 200.

![image](https://user-images.githubusercontent.com/20773170/45976400-a1216780-c014-11e8-8dd8-0e93f4f2b563.png)

**Comment by iglocska** [comment]
Oh single events with 200k domains - ok the issue makes more sense now. Will work on something sane to solve this

**Comment by github-germ** [comment]
Just linking in possibly related issues -- in my case, it's not domains, but URLs:
* #3632 
* #3671 
* https://github.com/MISP/PyMISP/issues/267
* #3563

**Comment by syloktools** [comment]
The problem was large correlations. Also new API is much faster on 2.4.96

**Comment by iglocska** [comment]
It also had to do with a really stupid query that was especially bad in your case - adding every correlation to each attribute is something we only do on the event view via the UI - but due to a dumb piece of code it tried to run that extremely expensive query for each attribute via the API - then not actually attach the results anyway.
