### ISSUE TITLE
Deterministic way to enable warning lists with the API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3706]
The Warning Lists don't have an UUID, making it impossible to enable a specific warning list without checking the ID on the instance first.

Related: https://github.com/MISP/MISP/commit/1fb239abad89ab089fa829590558d005f35c5066

**Comment by iglocska** [comment]
Added a new alternative way of finding the warninglist[s] you're after:

```
{"name": ["alexa", "iana"], "enabled": 1}
```

**Comment by Rafiot** [comment]
nice, thanks!

**Comment by Rafiot** [comment]
Hmm passing a name enables all the warnings at once (try passing `resolvers`)

**Comment by iglocska** [comment]
Woops. Fixed now, basically added support for passing a single value instead of an array and that broke things. It now works for both cases.

**Comment by Rafiot** [comment]
all good, adding the tests :)
