### ISSUE TITLE
Jobs get stuck in Queued Stage

### ISSUE THREAD

**Issue by vasiqmz** [MISP/MISP#3709]
Hi everyone,

I've got MISP deployed in our environment and whenever MISP tries to Pull Update from any MISP server the Job starts but it gets stuck at the Queued Stage without any progress.
Kindly let me know if this is an known bug or if there's any workaround for the same.
Awaiting for your kind reply.

**Comment by patricksvgr** [comment]
You may have a look at https://github.com/MISP/MISP/issues/669 and https://github.com/MISP/MISP/issues/3244. Also: What is your operating system? Are your workers running? Do you have any logs in `/var/www/MISP/app/tmp/logs`?

**Comment by vasiqmz** [comment]
Thanks for the reply.
I've checked the status of all the workers from the GUI and it shows all the Workers are running OK.

Below are the details of the deployment environment

| Questions   |      Answers   |  
|----------|:-------------:|
| Server | Ubuntu 18.04.1 |
| Php version |  7.2.7 |
| MISP | 2.4.95 |

From the logs it looks like some SQL error due to a column INF missing in the table. I've used the ISO image directly to deploy the MISP and I didn't face any issues with the installation also. Below are the logs for your reference.
`[2018-09-27 08:33:31] main.INFO: got {"queue":"default","id":"8d3158b5034f52ffbced6158b13c8da8","class":"ServerShell","args":[["pull","8","4","full","76"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"8d3158b5034f52ffbced6158b13c8da8\",\"class\":\"ServerShell\",\"args\":[[\"pull\",\"8\",\"4\",\"full\",\"76\"]]})","worker":"misp:26302"} []`

`[2018-09-27 08:33:31] main.INFO: Processing ID:8d3158b5034f52ffbced6158b13c8da8 in default {"type":"process","worker":"misp:26302","job_id":"8d3158b5034f52ffbced6158b13c8da8"} []`

`[2018-09-27 08:33:37] main.ERROR: {"queue":"default","id":"8d3158b5034f52ffbced6158b13c8da8","class":"ServerShell","args":[["pull","8","4","full","76"]]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'INF' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'INF' in 'field list'","job_id":"8d3158b5034f52ffbced6158b13c8da8","time":5939,"worker":"misp:26302"} []`

I've checked the bug #669 which is about Purging job and #3244 which is similar to the error I'm facing with MISP but the logs are showing something different, as in my case the logs showcases that there's an error in the SQL table.

Awaiting for your reply.

**Comment by patricksvgr** [comment]
Give it a try: _MISP GUI_ -> _Administration_ -> _Server Settings_ -> _Diagnostics_ -> _Clean model cache_

**Comment by vasiqmz** [comment]
I tried the following on top of what was mentioned in your last comment.

- Purged all the jobs
- Restarted the workers from MISP
- and Clean Model Cache.

Still I'm getting the same error, I've got 2 Server Instances configured - FIRST & CIRCL - and in both cases I'm getting the below error:

`[2018-09-30 08:13:00] main.ERROR: {"queue":"default","id":"68d0f5a77968306102dbc87730b5d910","class":"ServerShell","args":[["pull","8","4","full","79"]]} failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'INF' in 'field list' {"type":"fail","log":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'INF' in 'field list'","job_id":"68d0f5a77968306102dbc87730b5d910","time":3942,"worker":"misp:40694"} []
`

**Comment by vasiqmz** [comment]
Awaiting for your reply @patricksvgr

**Comment by combobulator** [comment]
I'm seeing exactly the same issue, fresh install of MISP on Ubuntu 18.04.
Tried the CIRCL instance and a few others, same issue each time.

```
# cd /var/www/MISP/app/Console && ./cake Server pull 3 4 full

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Notice Error: Undefined variable: passAlong in [/var/www/MISP/app/Model/Server.php, line 2025]

2018-10-03 14:06:26 Notice: Undefined variable: passAlong in [/var/www/MISP/app/Model/Server.php, line 2025]
Notice Error: Undefined variable: eventId in [/var/www/MISP/app/Model/Server.php, line 1883]

2018-10-03 14:06:27 Notice: Undefined variable: eventId in [/var/www/MISP/app/Model/Server.php, line 1883]
Notice Error: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1918]

2018-10-03 14:06:27 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1918]
Notice Error: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1920]

2018-10-03 14:06:27 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1920]
Notice Error: Undefined variable: eventIds in [/var/www/MISP/app/Model/Server.php, line 1920]

2018-10-03 14:06:27 Notice: Undefined variable: eventIds in [/var/www/MISP/app/Model/Server.php, line 1920]
Warning Error: count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Model/Server.php, line 1920]

2018-10-03 14:06:27 Warning: count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Model/Server.php, line 1920]
Warning Error: Division by zero in [/var/www/MISP/app/Model/Server.php, line 1920]

2018-10-03 14:06:27 Warning: Division by zero in [/var/www/MISP/app/Model/Server.php, line 1920]
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'INF' in 'field list'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('UPDATE `misp`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(424): DboSource->execute('UPDATE `misp`.`...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1926): Mysql->update(Object(Job), '`progress` = IN...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1712): Model->save(Array, Array)
#6 /var/www/MISP/app/Model/Server.php(1920): Model->saveField('progress', INF)
#7 /var/www/MISP/app/Model/Server.php(2025): Server->__pullEvents('52cbacad-33dc-4...', Array, Array, Object(Event), Array, Array, NULL, Object(Job), '10')
#8 /var/www/MISP/app/Console/Command/ServerShell.php(40): Server->pull(Array, '4', 'full', Array, '10')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('pull', Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#13 {main}
```

In /var/www/MISP/app/tmp/logs/error.log:
```
2018-10-03 14:17:29 Warning: count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Model/Server.php, line 1920]
2018-10-03 14:17:29 Warning: Division by zero in [/var/www/MISP/app/Model/Server.php, line 1920]
```

In /var/www/MISP/app/tmp/logs/debug.log:
```
2018-10-03 14:17:28 Notice: Undefined variable: passAlong in [/var/www/MISP/app/Model/Server.php, line 2025]
2018-10-03 14:17:29 Notice: Undefined variable: eventId in [/var/www/MISP/app/Model/Server.php, line 1883]
2018-10-03 14:17:29 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1918]
2018-10-03 14:17:29 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Server.php, line 1920]
2018-10-03 14:17:29 Notice: Undefined variable: eventIds in [/var/www/MISP/app/Model/Server.php, line 1920]
```

Just a thought; "INF" isn't a column name I'd expect, perhaps there's some SQL being created which contains "INFORMATION_SCHEMA" but is being clipped or malformed during processing?

EDIT: I've also taken the same steps as @vasiqmz and reviewed #669 and #3244 to no avail :( (though our object_references.deleted definition was also incorrectly tinyint(4) and has been changed to tinyint(1) now)

**Comment by vasiqmz** [comment]
Hi @combobulator 

The issue has been fixed, below are the steps I executed on MISP to resolve the issue.

1. Update the MISP repo via git - git pull 
2. Clear the cache model as mentioned earlier
3. Restarted all the workers.

**Comment by combobulator** [comment]
Great, that fixed it our end too, thanks for the update!
