### ISSUE TITLE
Include the "MISP-Dashboard" as apart of the install

### ISSUE THREAD

**Issue by Glhenn** [MISP/MISP#3710]
Is it possible to integrate the "MISP-Dashboard" as apart of the base MISP install or even as an option, opposed to a separate install/pull? Maybe have a button in "Global Actions" that links to it?

**Comment by SteveClement** [comment]
@Glhenn at this point in time misp-dashboard is ALPHA. So not ready to be included.

In an upcoming install-script misp-dashboard will be an option. (Also to be installed in existing setups)
