### ISSUE TITLE
Correlation issue with objects

### ISSUE THREAD

**Issue by CriimBow** [MISP/MISP#3718]
Hi everyone,

I have an issue similar to https://github.com/MISP/MISP/issues/3504 but not exactly the same because it happens with original objects.

![ex2](https://user-images.githubusercontent.com/28646904/46148634-cdcdbd00-c268-11e8-8489-7a9e14fb7455.PNG)

![ex1](https://user-images.githubusercontent.com/28646904/46148614-c3132800-c268-11e8-88ee-7c0449ac64ce.PNG)

![ex3](https://user-images.githubusercontent.com/28646904/46148643-d1f9da80-c268-11e8-9c4f-6f12f57d9b23.PNG)

![ex4](https://user-images.githubusercontent.com/28646904/46148747-079ec380-c269-11e8-9552-b99c0faebffc.PNG)

When I try to reinstall MISP (Debian 9), I encounter the exact same issue.

Thanks in advance.

**Comment by adulau** [comment]
Maybe you had some old events with the old templates which was not disabling the correlation by default. You can disable the correlation manually for those old attributes. Newly created ones with recent MISP object templates should not have the issue.

**Comment by CriimBow** [comment]
Yes, you are right, I just created new events and correlation was disabled.
