### ISSUE TITLE
Login failed post-2.3 upgrade

### ISSUE THREAD

**Issue by mgeorgy** [MISP/MISP#372]
I have a 2.2 installation that works well.  I've upgraded per instructions in upgrade.txt without any error.  When I attempt to login I'm presented with 'Invalid username or password, try again'.  Only relevant error is in /var/log/apache2/misp.local.error.log:

PHP Warning:  file_put_contents(/var/www/MISP/app/tmp/logs/error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /var/www/MISP/app/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php on line 142, referer: http://172.24.8.89/users/login

Thoughts?

**Comment by RichieB2B** [comment]
When you do a git pull, the new files will be created with your current user. If that is not apache/httpd you might have to do a chown or chmod to fix the permissions.

**Comment by mgeorgy** [comment]
The entire MISP subdirectory is owned by www-data.  The permission are all 750 (rwxr-x---).  Seems to be correct.  Would the permissions/ownership have an impact on authentication?

**Comment by RichieB2B** [comment]
Doesn't look like a permission problem them. Does app/tmp/logs/error.log give you any clues?

**Comment by mgeorgy** [comment]
Only thing in that log file is:

2015-01-26 09:03:26 Warning: strlen() expects parameter 1 to be string, array given in [/var/www/MISP/app/Plugin/CakeResque/vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php, line 148]
2015-01-26 09:03:29 Warning: strlen() expects parameter 1 to be string, array given in [/var/www/MISP/app/Plugin/CakeResque/vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php, line 148]

I believe this is not a critical error, right?

**Comment by iglocska** [comment]
Hello mgeorgy,

That is not a critical error, but it means that you are using Redisent
instead of phpredis, which is not recommended (you'll get those error
messages and scheduling won't work, if you'd like to use it). If you are on
a newer version of Ubuntu, just run apt-get install php5-redis and add
redis.so as an extension to your php.ini as described in INSTALL.txt.

For your main issue:

Are you using the correct salt key? It sounds like your username/password
combination is not correct and changing the salt key could cause just that.

**Comment by mgeorgy** [comment]
Thank you.  Any idea how the salt was changed?  Is there a way to retrieve the original salt to preserve my existing account?  Otherwise, any suggestions on resetting the password?  This is a new install and this is the only account.

**Comment by iglocska** [comment]
Retrieving the original salt - unless you backed up your old bootstap.php
then I am afraid it won't be possible, but if it's just one account then
the easiest thing to do is to just delete it via mysql. If there are no
accounts present, MISP will automatically create a new user. The
credentials will be:

Username: admin@admin.test
Password: admin

The config.default.php uses the default salt key, so if you used something
else on your 2.2 installation then this would have been overwritten when
you switched to the new config.php.

Let me know if this doesn't solve the issue for you, or if you'd like to
save the current user anyway.

**Comment by mgeorgy** [comment]
Andras,
  Thank you.  I was able to delete the user and regain access using the default account.
