### ISSUE TITLE
Task Scheduler seemed to be not functioning

### ISSUE THREAD

**Issue by vedd3r** [MISP/MISP#3720]
Scheduled Task doesn't seemed to be working - at least in my case for pull_all.
Last successful pull was a month ago. No further jobs/events pulled after that. It could be that other tasks are affected as well but in my case, it was the pull_all.

  | 1 job(s) completed at 28/08/2018 - 07:52:09. Failed jobs: 0/1

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04 
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 7.0,
| MISP version / git hash   | 2.4.95 (d572e262f877ffdc47e225a0de138aec67a47912) 
| Browser                   | FireFox

### Expected behavior
Scheduler would periodically pull events from another MISP instance every hour.

### Actual behavior
No pull from 28/08/2018 onwards.

### Steps to reproduce the behavior
Enable task scheduler for pull_all (and perhaps other tasks)

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/32356147/46194078-df7b9700-c332-11e8-827c-c442fa5f92e8.png)

**Comment by vasiqmz** [comment]
Hi everyone,
Any update on the above issues as I'm facing the similar issue on my end.
Awaiting for the response.

**Comment by vasiqmz** [comment]
Hi everyone,

I'm facing the similar issue. Kindly let me know if the issue has been fixed or not.
Awaiting for your reply.
