### ISSUE TITLE
Deleted admin user

### ISSUE THREAD

**Issue by stansecurecom** [MISP/MISP#3722]
I deleted the admin user by mistake. Now, I only have Org Admin.

Is it possible to create an admin user via cli?

**Comment by stansecurecom** [comment]
Should I reinstall the vm? is it the only way?

**Comment by iglocska** [comment]
You have several options:

1. Delete the org admin. MISP automatically creates a new default site admin user if no users are found in the db (mysql: truncate users;)

2. Upgrade a user to a site admin, such as an org admin user:
```
SELECT id, email from users;
```
Note down the ID you want to upgrade.  Let's say this is 2 for the example's sake.
```
SELECT id, name from roles;
```
Note down the role ID you want to upgrade. Let's say this is 1 for the example's sake.
```
UPDATE users set role_id = 1 where id = 2;
```

**Comment by SteveClement** [comment]
Added this blurb to the FAQ section of misp-book.
I suppose this is still true. @iglocska please ping if not.

https://www.circl.lu/doc/misp/faq/#i-deleted-the-admin-user-by-mistake
