### ISSUE TITLE
Error Adding Sightings

### ISSUE THREAD

**Issue by urban-moniker** [MISP/MISP#3728]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04 LTS
| OS version (client)       | All tested
| PHP version               | 7.2
| MISP version / git hash   | 2.4.95, 925e688122f955a3087e5f2ed284b9cba1e5c1e1
| Browser                   | All tested

### Expected behavior

Installed MISP as per documentation on Ubuntu 18.04 (note that you need to enable the Universe repo on a fresh build for some of the packages to be available).  When using MISP we cannot add sightings to attributes.

### Actual behavior

Error "Could not add the Sighting. Reason: {"event_id":["This field cannot be left blank"],"attribute_id":["This field cannot be left blank"]}" is displayed

### Steps to reproduce the behavior

Fresh build of MISP on Ubuntu 18.04 following all steps (plus enabling Universe repo), add test event, add attribute to event, try to add sighting of attribute.

### Logs, screenshots, configuration dump, ...
![sighting](https://user-images.githubusercontent.com/23149626/46311827-44e1b900-c5bb-11e8-9e86-a3e1a9adc88b.png)

**Comment by SteveClement** [comment]
This is fixed as of latest version.
