### ISSUE TITLE
How to install custom galaxies/clusters?

### ISSUE THREAD

**Issue by mahesh557** [MISP/MISP#3732]
Hi,

I would like to remove existing galaxies/clusters that came with misp and introduce my own galaxies/clusters custom to our organization.
i deleted existing .json files and placed my custom json files in 
    /var/www/MISP/app/files/misp-galaxy/galaxies

removing the existing .json files in that directory.
and restarted all workers
    sh-4.2# su -s /bin/bash apache -c 'bash /var/www/MISP/app/Console/worker/start.sh'

Nothing happend, i still see old galaxy/clusters only.

Can i know how to add custom galaxies?

*If you would like to report a bug, please fill the template bellow*

### Work environment
OS: RHEL 7
PHP 5.4.16
MISP 2.4

### Expected behavior
Remove existing Galaxy/Cluster settings and New custom Galaxy/Clusters

### Actual behavior
Despite removing json files in /var/www/MISP/app/files/misp-galaxy/galaxies
MISP still shows existing clusters only

### Steps to reproduce the behavior
Delete existing .json files /var/www/MISP/app/files/misp-galaxy/galaxies
and Add only few of them 
and restart workers

**Comment by Crimson18** [comment]
I am having the same issue.  Does MISP allow you to make custom galaxy and clusters?

**Comment by adulau** [comment]
Did you update  the galaxy via the UI? The JSON files are imported into MISP when doing the update or force update.
