### ISSUE TITLE
Export issues

### ISSUE THREAD

**Issue by randomname13** [MISP/MISP#3733]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04/14.04
| PHP version               | 7/5
| MISP version / git hash   | 2.4.95, d8d5031c80e615641f01c5696998158cece8613d
| Browser                   | Any

### Expected behavior
Generating any kind of exports in the GUI

### Actual behavior
Generating exports fill up the resque-worker-error.log

### Logs, screenshots, configuration dump, ...
2018-10-03 06:06:25 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Attribute.php, line 2913]
Notice Error: Undefined variable: results in [/var/www/MISP/app/Model/Attribute.php, line 2966]
2018-10-03 06:06:25 Notice: Undefined variable: key in [/var/www/MISP/app/Model/Attribute.php, line 2966]
Notice Error: Undefined variable: results in [/var/www/MISP/app/Model/Attribute.php, line 2968]
2018-10-03 06:06:25 Notice: Undefined variable: results in [/var/www/MISP/app/Model/Attribute.php, line 2968]

**Comment by smclinden** [comment]
I'm having the same issue. v2.4.95 (2e95ccecc27f3e181910cb8ee83b4621ed5ceb53).

**Comment by iglocska** [comment]
Please update to the latest version

**Comment by smclinden** [comment]
I did. Now I am getting errors with Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Event.php, line 2342] and the workers won't start.

**Comment by smclinden** [comment]
This was fixed by adding a type cast (array) to the foreach argument.
