### ISSUE TITLE
Error: got response code 405 

### ISSUE THREAD

**Issue by jhidalgop** [MISP/MISP#3734]
Hi,

I need help!!, When executing the task jobs configured, We have error message in the logs, the error is:
**Error: got response code 405** 

This Jobs are the type Pulls.

I'attached the image with the error.
![misp](https://user-images.githubusercontent.com/19214297/46397661-0f3feb80-c6f3-11e8-9b0b-1d4294be7f63.PNG)

##############################
Currently installed version..... v2.4.57	
PHP Version (>5.6.0 recommended): 5.6.29-0+deb8u1 (Up to date)
PHP CLI Version (>5.6.0 recommended): 5.6.29-0+deb8u1 (Up to date)

Debian GNU/Linux 8 

###############################

Any solution?

regards,

**Comment by SteveClement** [comment]
This should be fixed by now.
