### ISSUE TITLE
Can't access Server setting and maintainance : I get an internal error on that.

### ISSUE THREAD

**Issue by lhirlimann** [MISP/MISP#3738]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Fedora
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4, d8d5031c80e615641f01c5696998158cece8613d

### Expected behavior
I'm able to set/see settings etc ...

### Actual behavior
I get an internal error.

### Steps to reproduce the behavior

I've installed MISP using ansible and @juju4 's script from https://github.com/juju4/ansible-MISP/ which I've modified to make it possible to use git behind proxies (eg I add a git config for proxies). I've commented out the gpg generation as it failed badly. haven't done it manually yet, I plan on doing it, but when I need to send/receive email.

Once the install is finished I log onto the machine. And I select Administration -> Server settings and ....

I get greeted with :  

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

### Logs, screenshots, configuration dump, ...
debug.log contains the following : 
2018-10-04 08:51:00 Notice: Notice (8): Undefined index: email in [/var/www/MISP/app/Controller/UsersController.php, line 1255]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::__extralog() - APP/Controller/UsersController.php, line 1255
UsersController::change_pw() - APP/Controller/UsersController.php, line 200
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

Attaching resque-worker-error.log and error.log as they are bigger.
[resque-worker-error.log](https://github.com/MISP/MISP/files/2445744/resque-worker-error.log)
[error.log](https://github.com/MISP/MISP/files/2445745/error.log)

I believe the the Cake workers are not launched
[root@misp1.xxxx logs]# ps aux |grep Cake
root     17986  0.0  0.0 112704   976 pts/0    S+   09:30   0:00 grep --color=auto Cake
[root@misp1.xxxx logs]#

What's missing in my install?

**Comment by juju4** [comment]
Thanks for using the role, @lhirlimann!
Can you check if you used a redis password? would recommend to disable this part as for now, it creates issue I had not time to address. See https://github.com/MISP/MISP/issues/3452

And seeing your log and "NOAUTH Authentication required" makes me think that's exactly that.
Disable it in redis config and in MISP config and should work.
Will disable it.
Feel free to open PR or issue on the other things you found.

**Comment by lhirlimann** [comment]
So https://github.com/MISP/misp-book/issues/36 seems to relate to the same issue.

I'll do some PR's once I'm done :p 

What's the best way to disable the password in ansible, just set it to something empty or I need to do more ?

**Comment by lhirlimann** [comment]
removing the password in redis fixed my issue.

**Comment by wkleinhenz** [comment]
Used the above ansible play book to install MISP, resulted with similar issues and found that removing requirepass from the redis.conf file appears to have fixed the issue

**Comment by rommelfs** [comment]
this is an acceptable workaround for localhost installations, but the root cause is not fixed. Reopened.

**Comment by iglocska** [comment]
It's acceptable for all installations. Redis should not be exposed via the network in the first place.

**Comment by 4ekin** [comment]
File app/Plugin/CakeResque/Config/config.php
```
$config['CakeResque'] = array(
'Redis' => array(
'host' => 'localhost', // Redis server hostname
'port' => 6379, // Redis server port
'database' => 0, // Redis database number
'namespace' => 'resque', // Redis keys namespace
'password' => null // Redis password
),
```

After change 'password' to mysecretpass, it fix problem
