### ISSUE TITLE
Feature Request: Bulk Import Objects

### ISSUE THREAD

**Issue by cybgit** [MISP/MISP#3741]
[Feature Request]
I was after a way to bulk import IPs & Domains with a relationship when they are provided as a side by side list.

e.g
185.230.124.246 truefashionnews.com
87.120.254.106 protonhardstorage.com
77.81.98.122 moldtravelgroup.com
etc

Speaking on the MISP Gitter i found this is acheived with Objects, but there is currently no way to bulk import a side by side list to create multiple objects. 

This would be a great feature, to be able to have the parameters needed for an object to be imported from CSV for example.

**Comment by ChilliSec** [comment]
👍 this; It would be great to configure the CSV header to match the Object template fields and bulk import those. I'm just about to manually create 400+ victim objects (this Feature Request turned up in my search to see if this could be done already).

Keep up the great work all!

**Comment by kahunakhan** [comment]
yeah a bulk object import feature is what is needed.
The objects can be created in json or xml format, but how do we import them using a script or manually to the backend?
currently an entire event can be imported but not objects.

**Comment by geekscrapy** [comment]
+1 for this request - I currently have a list of path, filename, hash and comments I would like to add as objects.

**Comment by adulau** [comment]
For the time being, there is a generic tool to import a list of objects (CSV) https://github.com/MISP/PyMISP/blob/master/examples/load_csv.py

**Comment by geekscrapy** [comment]
FYI, I started work on this and then noticed @adulau comment, but I thought I may as well finish it :'D

https://github.com/geekscrapy/misp-batchobjects

Fits my model of import well, hopefully it'll help others as well
