### ISSUE TITLE
API request asking event_timestamp doesn't work

### ISSUE THREAD

**Issue by crondaemon** [MISP/MISP#3744]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
| MISP version / git hash   | v2.4.92-1182-g54995ed
| Browser                   | no

### Expected behavior

I'd like to retrieve the events that have been modified in the last day. To achieve that, I've used this request:

__URL__: https://myserver/events/restSearch
__payload__: {"event_timestamp":1538901584}

Other requests like

{"last":"5d"}

are working.

### Actual behavior

{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}

### Steps to reproduce the behavior

curl -v -XPOST -H "Authorization: MYKEY" -H "Content-Type: application/json" -H "Accept: application/json" -d "{\"event_timestamp\":\"1538901584\"}" https://misp.local/events/restSearch

**Comment by iglocska** [comment]
Indeed, event_timestamp isn't really working on the /events/restSearch endpoint as timestamp does the exact same job there anyway, event_timestamp is meant to be an alternate parameter for the attribute level restSearch API. But I can alias it for the event level one just in case.

**Comment by iglocska** [comment]
Ah never mind, I saw it was fixed already, could you update to the latest MISP version? v2.4.96.

**Comment by crondaemon** [comment]
Running `git pull origin 2.4` brings me to `v2.4.92-1325-ge6e8a53`. Am I doing something wrong?

**Comment by crondaemon** [comment]
BTW using `git fetch` the latest tag I see is `v2.4.95`.

**Comment by crondaemon** [comment]
With revision 2.4.95 I don't get internal server error. I'm closing the issue, thanks.

**Comment by iglocska** [comment]
That is weird, 

https://github.com/MISP/MISP/releases/tag/v2.4.96

was pushed 2 hours ago, weird that it won't show up. 

Also, git pull origin should get you to:

```
iglocska@iglocska-ThinkPad-T480:/var/www/MISP# git log -1
commit e08f1e2f4b1ebf330ba8018c7f2caaa94fb976f0 (HEAD -> 2.4)
```

**Comment by crondaemon** [comment]
misp:/var/www/MISP# git fetch
misp:/var/www/MISP# git show e08f1e2f4b1ebf330ba8018c7f2caaa94fb976f0
fatal: bad object e08f1e2f4b1ebf330ba8018c7f2caaa94fb976f0
misp:/var/www/MISP#
