### ISSUE TITLE
storing user defined values related to tags

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3746]
we would like to assign TTL (time-to-live) values (e.g. an int for days) to specific tags and then write a PyMISP app that will sweep attributes (e.g. nightly) calculating the `TTL sum` based on tags for that attribute and compare that `TTL sum` to `attribute.timestamp` and remove some tags if TTL is exceeded.

is there any way to store a TTL within the MISP data model, or should we construct our own datastore (e.g. a config file) used by our PyMISP app mapping tag to TTL.

**Comment by github-germ** [comment]
i am about to implement this tag TTL app. since there's been no reply to this issue question, i will assume there is no way to store user-defined data related to tags within the MISP framework, i.e. i will create my own app config file with these settings. howoever, if anyone has suggestions, please let me know. thanks.

**Comment by adulau** [comment]
We are working on a complete implementation for expiration. The current model is described as a paper [Decaying Indicators of Compromise](https://arxiv.org/pdf/1803.11052.pdf) and we are working on a implementation for MISP.

**Comment by github-germ** [comment]
@adulau Very nice! We also now have an innovative solution for TTL aging-out. I will be implementing here this month with targeted completion by year-end. We'll be interested to see the MISP implementation when it's ready. Thanks.

**Comment by github-germ** [comment]
Btw, is there a prior PR github issue on your planned implementation that I can watch? if not, do you want to use this one, or close this issue now?
