### ISSUE TITLE
Generate export files is not working

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#3748]
Hello all,

Generate export files (https://XXXXX/events/export) is not working. The job status related to the export (https://XXXX/jobs/index) stays in "Running/Queued" during hours.

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.96 (commit: bd7172dd1de0daa84cfe50107d93a0f05cebaf0a)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | all
| MISP version / git hash   | 2.4.96, bd7172dd1de0daa84cfe50107d93a0f05cebaf0a
| Browser                   | Chrome, Firefox, all

### Expected behavior

Export files are generated.

### Actual behavior

Generate export files (https://XXXXX/events/export) is not working.

### Steps to reproduce the behavior

Click on "Event Actions" and select "Export". Next, click on one of the "generate" buttons (section Actions). Check the jobs status page (https://XXXXX/jobs/index) and logs files.

### Logs, screenshots, configuration dump, ...

Several errors/bugs: 

```
2018-10-09 10:11:04 Notice: Undefined variable: results in [/var/www/MISP/app/Model/Attribute.php, line 2976]
2018-10-09 10:11:04 Notice: Undefined variable: k in [/var/www/MISP/app/Model/Attribute.php, line 2921]
```

**Comment by iglocska** [comment]
Well that was a nasty copy-pasta snafu. Should be fixed now, thanks!

**Comment by devnull-** [comment]
> Well that was a nasty copy-pasta snafu. Should be fixed now, thanks!

Indeed, thank you for your reply. Now, the export job can be launched, but job doesn't finish. His status is still in "Running" (https://xxxxx/jobs/index -- Fetching events.) during hours/days. I checked the logs and no error/traces.

Could you double check if something can block the export job ?

Thank you for your help :)

MISP version / git hash: 4667f3e74e58eeeb67f7cfb905399edb00991165
