### ISSUE TITLE
API - Attributes Download Ignores TAGs

### ISSUE THREAD

**Issue by chrissommer** [MISP/MISP#3752]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug 
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Win 10
| PHP version               | 7.0.32
| MISP version / git hash   | 2.4.96
| Browser                   | Firefox

I tried to download attributes with a certain TAG via CLI and via the WebGUI REST Client,
but I always get all domains back (also Domains and Hostnames with other TAGs).

### Expected behavior
Only get the results with the wanted tags

### Actual behavior
Always get all Results and the tag gets ignored

### Steps to reproduce the behavior
Start an Attribute REST Search with tags and compare the results 

Do you need any other Debug Information?

BR
Chris

**Comment by adulau** [comment]
Indeed. Could you git pull the latest version? We did a fix. Thanks a lot.

**Comment by chrissommer** [comment]
Perfect - everything is working fine now :)
Thank you for the quick fix.

BR
Chris

**Comment by iglocska** [comment]
Thanks for the notification!
