### ISSUE TITLE
"manage_workers" variable treated as False by default after upgrade to v2.4.96

### ISSUE THREAD

**Issue by infosec-intern** [MISP/MISP#3755]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Windows 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.96, 40b1a4a2719d7579ceb1991126c62517c6f2fffb

### Expected behavior
"manage_workers" variable is treated as true by default if it doesn't exist in `config.php` (based on `config.default.php`)

### Actual behavior
"manage_workers" variable is treated as false if it isn't set in `config.php`

### Steps to reproduce the behavior
1. Update to v2.4.96
2. Navigate to Workers tab under Settings
3. See message at top: 
_Note:: You have set the "manage_workers" variable to "false", therefore worker controls have been disabled._
### Logs, screenshots, configuration dump, ...
* Command run while troubleshooting manage_workers
```
/var/www/MISP# grep -R "manage_workers" .
./app/Config/config.default.php:                        'manage_workers'                 => true,
./app/Model/Server.php:                        'manage_workers' => array(
./app/Model/Server.php:        $worker_array['controls'] = Configure::read('MISP.manage_workers');
```
![capture](https://user-images.githubusercontent.com/15183688/46812791-b4317880-cd32-11e8-9025-95a74c8b3c98.PNG)

### Extra Note
Ultimately, it's not a big deal because you can go into the MISP Settings, navigate to the very bottom of the page, and toggle the setting to force it to "true", but it seems like a small bug.

**Comment by iglocska** [comment]
This was fixed a few hours ago,
