### ISSUE TITLE
Issue with classification of IOCs using gTLDs

### ISSUE THREAD

**Issue by obikao** [MISP/MISP#3756]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Windows 8.1
| PHP version               | 7.0
| MISP version / git hash   | 2.4.92, 6eb4e49f2c62d05e671e3482ac1b21004ce58ee3

### Expected behavior
When importing feeds, indicators are classified as a domain, hostname, IP, etc

### Actual behavior
Certain TLDs are not being recognized as domains (.top for example) and are being classified as "files"

### Steps to reproduce the behavior
Import a csv feed of IOCs with www.test.top as an indicator. MISP will classify this is a filename

### Logs, screenshots, configuration dump, ...
![capture2](https://user-images.githubusercontent.com/3343457/46840320-0781e600-cd88-11e8-8e7c-073a154f74a1.PNG)

**Comment by obikao** [comment]
Any chance that, if a feed has a specific type of data in it, we could mark that feed as having a known datatype?

**Comment by iglocska** [comment]
Do you have the warnings loaded? That should greatly increase the chance of correct tld detection (just go to the warninglist page and hit update)

**Comment by obikao** [comment]
Yep, after I posted I continued looking around and saw another post on this. I loaded the warnings and refetched all the feeds, with delta merge enabled. Some were recognized as proper domains, but many others were still being categorized as filenames

**Comment by SteveClement** [comment]
@obikao can you try again with the latest version.
