### ISSUE TITLE
Cannot catch MISP connection errors

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#3759]
I'm new to MISP and I'm having an issue with the PyMISP API.  I was assigned a project where I need to create a user interface to access our MISP environment.  Step 1 for me is to create an interface and asks the user for the proper URL and Authkey.  It's a standalone Python script.  My issue is I cannot for the life of me figure out how to capture an incorrect Authkey.  I can get the following exceptions:

Good URL, but bad link
Bad URL

But I can't determine if a user enters a bad Authkey.

Here is my code so far:

```
import pymisp
import urllib3

assume_good_connection = 'y'
entered_url = <good URL>
entered_key = <bad Authkey>
          
try:
    api = pymisp.PyMISP(entered_url, 
                        entered_key, 
                        False)
except:
    the_type, the_value, the_traceback = sys.exc_info()
    
    # Look for bad connection
    if (str(the_value).find('10061') > -1):
        assume_good_connection = 'n'
        
        print('Bad URL route') 

    # Look for bad URL
    elif str(the_value).find('11001') > -1:
        assume_good_connection = 'n'
        
        print('Bad URL name') 

    # Print anything else
    else:
        print('Other exception: ' + str(the_value))
    
if  assume_good_connection == 'y':
    if api.test_connection() is True:
        print("Connection is verified")
    else:
        print("Connection not verified")
else:
    print("No connection made")
```

Now, when I run this, I get the following:

WARNING [api.py:100 - __init__() ] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.

Traceback (most recent call last):

  File "<ipython-input-54-7f627124f470>", line 1, in <module>
    runfile('Q:/MISP/MISP Python Scripts/xxxxxxxxxxx', wdir='Q:/MISP/MISP Python Scripts')

  File "C:\x\Python\Python36\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\x\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "Q:/MISP/MISP Python Scripts/myScript.py", line 193, in <module>
    if api.test_connection() is True:

  File "C:\x\Continuum\anaconda3\lib\site-packages\pymisp\api.py", line 315, in test_connection
    raise PyMISPError(response.get('errors')[0])

PyMISPError: Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.

I ~see~ the PyMISPError but can't trap it.  I've tried adding the "warnings.simplefilter('error')" line, but that doesn't work.

I'm simply trying to capture the "Authentification failed" message from PyMISP so I can send the user the correct error to fix.

Any insight or suggestions would be greatly appreciated.

**Comment by github-germ** [comment]
Instantiating the `PyMISP` class does not throw an exception when there's a invalid auth key. However, `test_connection` does. Here's some code and output that might help (notice that `pymisp.api.PyMISP` does use `logging` and outputs the `warning` to `stderr` (see https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L100).

This test is with `pymisp.__version__` `2.4.96`.

```
$ cat EdTest.py
#!/usr/bin/env python
import sys
import pymisp
import urllib3

# add this to avoind urllib sending to stderr
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

entered_url = 'https://localhost'
entered_key = '<bad Authkey>'

try:
    print('call PyMISP()...\n')
    api = pymisp.PyMISP(entered_url,
                        entered_key,
                        False)
except Exception as e:
    # PyMISP does not throw an exception for an invalid authkey
    sys.stderr.write('PyMISP exception="%s"\n' % (str(e)))
    sys.exit(1)

try:
    print('\ncall test_connection()...\n')
    api.test_connection()
except Exception as e:
    # it does throw the exception here!
    sys.stderr.write('test_connection exception="%s"\2' % (str(e)))
    sys.exit(2)

print('connected')
sys.exit(0)
$ 
$ python3 ./EdTest.py
call PyMISP()...

WARNING [api.py:100 - __init__() ] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.

call test_connection()...

test_connection exception="Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header."
$ 
```

**Comment by EdAtt** [comment]
github-germ, thanks for the insight.  I now have a 2-stage approach.  First I check for a good/bad connection with the api = pymisp.PyMISP() try/except block, and, if that's OK, add your second api.test_connection() try/except block.  This does what I need to do.  Thanks again.

**Comment by EdAtt** [comment]
Issue closed.
