### ISSUE TITLE
Event tags not included in export

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#3774]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04
| OS version (client)       | Win 7.
| PHP version               |  7.0
| MISP version / git hash   | 2.4.96, 35400ef3091e32b8f7b40f08e6857abfa66eff07

### Expected behavior
When exporting events with the option "includeContext":"True", the event tags are exported.

### Actual behavior
The event is exported but the field "event tag" is empty when using the GUI REST-client or a request. 
It seems that all output formats are affected.

Using the "download as.." option in the event view is not affected.

(Also in a csv file the field "date" is not a date anymore, but a timestamp. Don't know if this is intended.)

### Steps to reproduce the behavior
Make a csv or json export, either via the GUI Rest-Client or via request.

```
body = {"returnFormat":"csv", "eventid":"1234", "includeContext":"true"}
response = requests.post(url="https://misp.org/attributes/restSearch",headers=headers,json=body,verify=False, proxies=proxies)
```

Best regards

**Comment by mokaddem** [comment]
Hello,
The correct field to include event tags is ``includeEventTags``.
Rest client Documentation has been updated accordingly.

**Comment by iglocska** [comment]
@Kahuna01 is indeed correct. The correct key for the CSV return format is includeContext, however "True" is not a valid value for the field, try this instead:

```
{"returnFormat":"csv", "eventid":"1234", "includeContext":true}
```

or

```
{"returnFormat":"csv", "eventid":"1234", "includeContext":1}
```

**Comment by xme** [comment]
I'm facing the same kind of issues... Exported a bunch of attributes via the REST API in CSV.
I added "includeContext":1, "includeEventTags";1 but nothing! (the attribute_tag  column remains empty... (latest commit pulled from this morning)
Any idea?

**Comment by iglocska** [comment]
Are you sure the tags themselves are exportable? Have a look at the tag and
check if the exportable flag is set.

**Comment by Kahuna01** [comment]
I'm glad I'm not the only one... (;
At the moment, I can't test it with the up-to-date version, only with 2.4.96.

Yes, the event tags are exportable


![rest](https://user-images.githubusercontent.com/31033198/48824401-79c0ef80-ed64-11e8-894d-12274ff2934d.png)

![event](https://user-images.githubusercontent.com/31033198/48824345-4aaa7e00-ed64-11e8-9465-9dd969d63c37.png)

**Comment by xme** [comment]
Same here, tags are exportable. Just tried again. Here is my JSON config posted to the REST API:

```
{
"returnFormat":"csv",
"category", "Network activity",
"last": "15d",
"tags": "tag1&&tag2",
"includeContext":1,
"includeEventTags": 1
}
```

**Comment by xme** [comment]
In fact, I see the tags when exported in JSON... but not in CSV.

**Comment by Kahuna01** [comment]
Oh, I see.
Including `"includeEventTags":1` gets me the tags if I choose json as return format. It just doesn't work with csv.

**Comment by iglocska** [comment]
Indeed I see. I kept testing with attribute tags which are included, but the event tag is omitted. Will fix it.

**Comment by SteveClement** [comment]
@iglocska is this fixed?

**Comment by Dmitry-Vasin** [comment]
This still appears to be an issue, have there been any updates?

**Comment by mokaddem** [comment]
@Dmitry-Vasin thanks for bringing this matter up. Performing the request below should work now. Thanks!
```json
POST /attributes/restSearch
{
    "returnFormat": "csv",
    "includeContext": 1
}
```
