### ISSUE TITLE
No .iso file found in VM zip file 

### ISSUE THREAD

**Issue by fucgithub** [MISP/MISP#3777]
I want to install MISP v.2.4.96  VM on my vmware desktop for demo/training purpose.
(clarification, I'm using vmware, NOT virtual box).
I downloaded the 2gig zip file from circle from:
https://www.circl.lu/misp-images/latest/

after extracting the content of this zip file,
MISP_v2.4.96@53cf70a415368601cc624698f86035d26c8f9d84-vmware.zip
it creates several folders and disks,
I tried to install the MISP-vm from VMware-installer and it looks for an .iso file, 
no .iso image found!
see pic attached:
![misp-install-problem](https://user-images.githubusercontent.com/44247774/47170569-371a7c00-d2bb-11e8-8c60-6686499f19c1.jpg)

Any suggestions?

**Comment by SteveClement** [comment]
What happens if you import the .vmx file?

You generally do not install a VM but import it into your VM environment, like VM-ware.

I will test with VMWARE workstation and see if there are issues.

In practice there is no need for any ISO.

I fear the issues lies on your end but will check nevertheless.

**Comment by SteveClement** [comment]
@fucgithub  I tested it, it just works out of the box.

**Comment by fucgithub** [comment]
That's good to know, can you articulate the steps you took to import the  .vmx file and start up the MISP instance please.
The instructions on MISP aren't very clear to me.
Here's a screen shot of files I've extracted from the zip file:
 
![misp-zip-file-list](https://user-images.githubusercontent.com/44247774/47731719-e4798200-dc21-11e8-97ef-03eed7dc183b.jpg)
