### ISSUE TITLE
Offer a more suitable filename for Download As... Rest Search

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#3780]
When using the "Download as" feature of an Event, it'd be nice to have a nicer named filename, such as:
`misp.event.<event_id>.<fileformat>`

Taking the "Download as" -> "MISP JSON", this would be formatted:
`misp.event.<event_id>.json`

A few users are noting that it's time consuming to keep renaming the `true.<fileformat>` for each event they download. Possibly could pass the filename down the chain?

**Comment by iglocska** [comment]
Pretty sure this was fixed like a few days ago already, which version are you on?

**Comment by tomking2** [comment]
Oh really @iglocska?
Let me pull the latest and take a look. Seems to have stem from the restSearch change

**Comment by tomking2** [comment]
Doesn't look like it :(.

On the latest @ v2.4.96 (337de1600461c4d8d7df24784f0c88e0640c199f) 

From what I can see, issue is as a result of updating the EventsController.php to remove the filename generated from a restSearch (as MISP XML and MISP JSON "Download as..." use the restSearch now).
https://github.com/MISP/MISP/blob/337de1600461c4d8d7df24784f0c88e0640c199f/app/Controller/EventsController.php#L2999

Missing a 5th parameter which would be the filename, but the code no longer generates a suitable filename to be returned back to the user. Which is fine for a typical restSearch, but when using the "download as" feature on an event level, No filename is returned so it doesn't download the file, instead displays in browser (unless the browser can't handle rendering the content like IE).

Brings about another issue of that the original filename is:
`misp.event.<event_id>.<event_uuid>.<extension>`
EventID can be easily found (passed in the function call), but UUID is not obtained anywhere. To be done cleanly, would have to be returned from the Event model restSearch I guess?
