### ISSUE TITLE
"Could not fetch feed." on the 3 MISP feeds.

### ISSUE THREAD

**Issue by befrankt** [MISP/MISP#3790]
I am seeing "Could not fetch feed." in the Jobs list for the 3 MISP feeds.
All other (50+) feeds are fine, they are based on csv and freetext format.

Interestingly enough the MISP feeds do sometimes work, maybe once every few days. Is this error I am seeing expected behaviour indicating there is no new data or is there an issue with my MISP configuration? I am behind a proxy, but the URL's are all patched through and considering the feeds do work at times, connectivity doesn't seem to be the issue?

Is there a more detailed error log for this anywhere?

Running MISP v2.4.96 on Ubuntu 18.04

**Comment by lianemeth** [comment]
I'm also having problems with MISP feeds, only CSV and Freetext feeds seems to be working for me.

**Comment by lianemeth** [comment]
I think it would be very helpful to get more information on the jobs when they fail too. It seems that it just informs "job failed" to any scenario on the MISP feeds.

**Comment by iglocska** [comment]
Should be fixed now, could you git pull?

**Comment by iglocska** [comment]
Let us know if it persists and we'll reopen the issue.
