### ISSUE TITLE
How to report LastModified timestamp for malware?

### ISSUE THREAD

**Issue by dragonxtek** [MISP/MISP#3791]
I don't know if this attribute doesn't exist or I couldn't find it.
Some files have a xml that report LastModified timestamp like the following example:
![selection_464](https://user-images.githubusercontent.com/10552658/47369594-67e32280-d6ba-11e8-95e4-a1a5f8a63da3.png)

How I can report it in MISP? Which attribute and type I need to choose?

**Comment by SteveClement** [comment]
You could check out the various modules: 

https://github.com/MISP/misp-objects

And perhaps add a last-seen to the one you think might fit.

Or comb through the [Taxonomies](https://github.com/MISP/misp-taxonomies) and tag your attribute/event with a last-seen tag. (Or create a custom one)
