### ISSUE TITLE
g

### ISSUE THREAD

**Issue by ShimiCohen** [MISP/MISP#3792]

**Comment by FloatingGhost** [comment]
I just installed it on an entire fresh instance and followed my own install instructions. I was shocked to discover that it works fine.

Maybe try actually following instructions before opening issues for user support? Just a thought.

**Comment by shimi199393** [comment]
I follow the instructions , 
It worked for me in the past properly, but after I uninstalled and reinstalled the problem was created. When I removed I just deleted the folder of misp-taxi-server Could there be files left that interfere with the current installation?
