### ISSUE TITLE
Definitive guide to using LDAP to authenticate to MISP?

### ISSUE THREAD

**Issue by smclinden** [MISP/MISP#3796]
Is there a definitive answer as to how to add LDAP authentication to MISP?

I have read a number of previous posts going back to 2016 and have tried various iterations (getting the same errors as others), but have yet to achieve any success.

**Comment by smclinden** [comment]
To be more precise, I have used LDAP Authentication at the Apache level to gain access to the MISP site. But it still requires me to provide separate credentials to MISP. It is not clear how to pass the LDAP credentials to MISP to bypass the need for the second login.

**Comment by SteveClement** [comment]
The is no definite guide just yet.
A good start would be the external auth modules: https://www.circl.lu/doc/misp/appendices/

Then there is this in default config: https://github.com/MISP/MISP/blob/f3850747da103ca616a7dbaab955df373db272f7/app/Config/config.default.php#L126

More research can be done here: https://github.com/MISP/MISP/blob/f3850747da103ca616a7dbaab955df373db272f7/app/Controller/Component/Auth/ApacheAuthenticate.php#L42

Personally I have no setup running with LDAP and am rather clueless on that topic anyways.

But you are more or less on your own :frowning: 

You could always come by in [Gitter](https://gitter.im/MISP/MISP) and see if someone solved this, and I am quite sure some did but never contributed Documentation... :alien:

**Comment by smclinden** [comment]
I may do this (Gitter). As others have documented, the Apache LDAP module does not appear to set the $_SERVER environment variables therefore, the following (AppController.php) fails:

$envvar = Configure::read('ApacheSecureAuth.apacheEnv');
        if (isset($_SERVER[$envvar])) {
            $this->Auth->className = 'ApacheSecureAuth';
            $this->Auth->authenticate = array(
                'Apache' => array(
                    // envvar = field returned by Apache if user is authenticated
                    'fields' => array('username' => 'email', 'envvar' => $envvar),
                    'userFields' => $auth_user_fields
                )
            );
        } else {
            $this->Auth->authenticate['Form']['userFields'] = $auth_user_fields;
        }

**Comment by rbnor** [comment]
In PR#5349 im setting the $_SERVER[$envvar]  (this is the $_SERVER['REMOTE_USER'] from the $_SERVER['PHP_AUTH_USER'], which works with basicauth. Another option is to set this in the misp-ssl.conf, which would be the optimal. Anyway,the way i did it now, works. Also had an issue with ApacheAuthenticate.php looking for email from the ldapuser, so as its written now one needs to have an email ascociated with the user. Thats easily fixable as well if anyone has that problem.

**Comment by rbnor** [comment]
I  adopted the change in the config suggested by @JakubOnderka , setting the key to use in $_SERVER in ApacheSecureAuth.apacheEnv instead. So here changing  it to 'PHP_AUTH_USER'.

**Comment by trolldbois** [comment]
Some documentation in #6189 related to LDAP/Active Directory
