### ISSUE TITLE
MISP silently fails if the self signed certificate *in PEM* has an other extension

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#3797]
plz, make it an actual error.

**Comment by iglocska** [comment]
I get this:

![image](https://user-images.githubusercontent.com/3668672/47460895-bf2ee300-d7df-11e8-8655-532abe5c5699.png)

**Comment by Rafiot** [comment]
sooo we were 3 in front of the computer and didn't see it.

Can you make it *not* create the entry then? because I bet we didn't look

Also why not allowing *.crt? It is what firefox is exporting
