### ISSUE TITLE
CIQ identity ids have "example" prefix

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#380]
See app/files/scripts/misp2ciq.py
I'm not comfortable enough with XML to fix this myself.

**Comment by RichieB2B** [comment]
I think this was closed by mistake. The issue is still there: https://github.com/MISP/MISP/blob/2.4/app/files/scripts/misp2ciq.py#L20

**Comment by iglocska** [comment]
Indeed it was, fixed now! Thanks for the heads-up.
