### ISSUE TITLE
User without password can't login

### ISSUE THREAD

**Issue by mokaddem** [MISP/MISP#3806]
If an user is created with password set to empty string, he can't pass through the login form.
Even though it's not the recommended behavior, it should be allowed.

**Comment by adulau** [comment]
You want to log without password?

**Comment by iglocska** [comment]
Yeah, I'd put this in the "working as intended" category.

Also, how did you create a user with an empty password?

**Comment by mokaddem** [comment]
Some users do not wanted password for their instance...
To create an user without password: As an admin, go to ``add user``, then tick ``set password`` and let input field empty.

**Comment by iglocska** [comment]
Weird that shouldn't work unless you change the password requirements.
