### ISSUE TITLE
CSV download not working

### ISSUE THREAD

**Issue by asahcl** [MISP/MISP#3829]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Can you help me with csv download
{"tags":["tag1", "tag2", "!tag3"], "category":"Network activity", "type": "domain"} is not working as expected for the version v2.4.97 (), not able to filter by type. I am trying to export the IOC's based on type in csv format.

**Comment by mokaddem** [comment]
Hello,
Doing this on my instance v2.4.97 (a39aa685f17a94f8930f23026d16c8b4ed461a05) works fine.
```
{
    "returnFormat": "csv",
    "type": "domain",
    "category": "Network activity",
    "tags": ["workflow:state=\"incomplete\"", "!tlp:red"]
}
```

Could you please provide more information? An example of data along with your expected result or guidance to reproduce the issue would be helpful.

**Comment by asahcl** [comment]
thanks it worked for me expect the headerless option
