### ISSUE TITLE
Library check error in 2.4.97 for Cybox and maec

### ISSUE THREAD

**Issue by keram79** [MISP/MISP#3837]
After upgrade to 2.4.97, "Server Settings & Maintenance" shows incorrect cybox and maec versions installed, although they are up-to-date.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 16.04.05 LTS.
| PHP version               | 7.0
| MISP version / git hash   | 2.4.97, 027e66e3d8198e3a0ed49a0251a6cd4c67489959
| Browser                   | not relevant

### Expected behavior

Server Settings & Maintenance should only report library mismatches when there are newer libraries required by MISP.

### Actual behavior

```
Current libraries status…Some versions should be updated:
STIX library version…OK
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.17, expecting 2.1.0.18.dev0
MIXBOX library version…OK
MAEC library version…Incorrect maec version installed, found 4.1.0.13, expecting 4.1.0.14
```

According to https://pypi.org/project/cybox/, 2.1.0.17 is the latest released version.

### Steps to reproduce the behavior

Update MISP to 2.4.97 via git pull

**Comment by SteveClement** [comment]
Thanks for the report @keram79 but you can ignore this for the time being.

Those are "soft" errors. More bad would be to have a missing module.

In future versions this will be handled differently.
