### ISSUE TITLE
from/to bug?

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#384]
Hi Andras,

The following request

https://<MISP URL>/events/csv/download/false/false/false/url/2015-01-01/2015-02-01

will give an empty output. Is this foreseen?

Cheers

**Comment by iglocska** [comment]
Sounds like a bug, will have a look in the morning!

**Comment by adulau** [comment]
Indeed, thank you very much for the quick fix in the documentation. 

https://URL/events/csv/download/false/false/false/false/url/false/2015-01-01/2015-02-01

Cheers and enjoy your evening.

**Comment by iglocska** [comment]
No worries, you too :)

**Comment by iglocska** [comment]
Just a heads-up, I missed pushing a file that is required in that fix, please run a git pull to resolve it! (it breaks the automation xml export)
