### ISSUE TITLE
[Kali] MISP  Error "An Internal Error occured" - No Database Connection

### ISSUE THREAD

**Issue by nahasca** [MISP/MISP#3845]
I have installed MISP on Kali but the website does not open https://misp.local. It says Internal error has occured. Any help ishighly appreciated.

Nahas

Error.log has the following errors>
2018-11-05 10:27:23 Error: [MissingConnectionException] Database connection "Mys
ql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboS
ource->__construct(Array)
#1 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDa
taSource('default')
#2 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeF
ilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): Event
sController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEv
entManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controlle
r->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatche
r->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequ
est), Object(CakeResponse))

Mysql is  running

service mysql stat
Usage: /etc/init.d/mysql start|stop|restart|reload|force-reload|status|bootstrap
root@xxxxxx:/var/www/MISP/app/tmp/logs# service mysql status
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql; generated)
   Active: active (exited) since Mon 2018-11-05 10:19:24 +03; 23s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 27562 ExecStart=/etc/init.d/mysql start (code=exited, status=0/SUCCES

Nov 05 10:19:23 systemd[1]: Starting LSB: Start and stop the mysql databas
Nov 05 10:19:24 mysql[27562]: Starting MariaDB database server: mysqld alr
Nov 05 10:19:24 systemd[1]: Started LSB: Start and stop the mysql database

**Comment by SteveClement** [comment]
Interesting, I just tried the script and it works fine on my Kali 2018.3a

Downloading Latest 2018.4 to see if that is the issue.

Thanks for the report.

**Comment by SteveClement** [comment]
@nahasca - Tested on latest Kali. It just works.

I think you already had a database running and that your Kali environment was not "empty"

Added a note in the HowTo that it assumes a FRESH install.

Eventually this could be changed. BUT atm no one is working on that.
