### ISSUE TITLE
STIX export bug?

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#385]
With the recent updates, It seems that the STIX export fails. 

2015-02-04 14:35:39 Error: [Exception] The temporary MISP export file could not be read
Request URL: /events/stix/download/1234.xml
Stack Trace:
#0 [internal function]: EventsController->stix('download', '1818')
#1 MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#4 /MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by iglocska** [comment]
Hmm that is odd. It seems to work for me, do you have any special characters in your event? (Event info / attribute values / attribute comments). There was a bug with special characters and old versions of Mitre's STIX python package.

**Comment by adulau** [comment]
Interesting, I pull the latest version of STIX python packages:

latest commit 3764aaa6cfa3f13062772067986b78d10a185139 python-cybox
latest commit 312628315c73ca71a62a13b2340bec5c2ac540a9 python-stix

But I still have the errors. What's the best way to debug such issue? to see if the python script is failing as the export output file is not there.

Thanks a lot.

**Comment by RichieB2B** [comment]
If indeed the output file fails to generate, there should be errors in app/tmp/logs/error.log

**Comment by iglocska** [comment]
Does it fail with every event or just certain ones? If you go to administration -> server settings -> diagnostics tab, do you see any issues with the writeable directories?

**Comment by adulau** [comment]
For your information, the issue was related to the AppArmor profile and the python execution.  I'll close the issue.

**Comment by iglocska** [comment]
Ahh, nice catch!
