### ISSUE TITLE
add_object enable correlation on all attributes even if disabled in object template

### ISSUE THREAD

**Issue by l3m0ntr33** [MISP/MISP#3853]
I defined a proprietary object template and imported it to MISP. I disabled correlation in the object templates for some of its attributes.
-> After import the object template is well displayed in MISP web interface and "Disable correlation" is OK for chosen attributes.

I then build an object like that:
o = pymisp.AbstractMISPObjectGenerator("ids-event")
o.generate_attributes()
o.add_attribute("attack-src-ip",type="ip-src",value=src_ip)
o.add_attribute("ip-protocol",type="text",value="tcp")

And add ot to MISP:
misp.add_object(eid,template_id,o)

-> The issue is that correlation is then enabled on all attributes even for those where i disabled it in the template. In my example the "ip-protocol" attribute should not have correlation enable but it is.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| MISP version / git hash   | 2.4.96

**Comment by mokaddem** [comment]
Hello @l3m0ntr33,
We recently fixed an issue related to ``disable_correlation``. Can you please check that you still have the problem?
If the answer is yes, do you have the same behavior if you do it via the web interface?

**Comment by l3m0ntr33** [comment]
Hello @mokaddem,
I still have the issue using the API -> correlation enabled on all attributes. Tested on MISP 2.4.97 (51e5d9418bea04df80716f32c903de830868754e).
Using the web interface i do not have the same behavior, the correlation is disabled on corresponding attributes.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
