### ISSUE TITLE
ignore parameter not working in csv export

### ISSUE THREAD

**Issue by dawid-czarnecki** [MISP/MISP#3862]
When exporting to csv and using ignore parameter (deprecated method) in results there are attributes with and without ids flag.

## Example 1:
```
curl -X POST -k -H "Accept: application/json" -H 'Content-Type: application/json' --data '{"ignore": false, "type": "hostname", "last": "20d"}' -H "Authorization: xxx" "https://localhost/events/csv/download"
```
### Result 1:
```
uuid,event_id,category,type,value,comment,to_ids,date,object_relation,attribute_tag,object_uuid,object_name,object_meta_category
"5be58317-1384-4c48-aeca-17430a853728",17676,"Network activity","hostname","google.com","",0,1541767959,"","","","",""
```
## Example 2:
```
curl -k -H "Authorization: XXX" "https://localhost/events/csv/download/false/false/false/false/hostname/true/false/false/21d/hostname.csv"
```
### Result 2:
```
uuid,event_id,category,type,value,comment,to_ids,date,object_relation,attribute_tag,object_uuid,object_name,object_meta_category,event_info,event_member_org,event_source_org,event_distribution,event_threat_level_id,event_analysis,event_date,event_tag,event_timestamp
"5be58317-1684-4c48-aeca-17430a853728",17676,"Network activity","hostname","google.com","",0,1541767959,"","","","","","aaaaa","ORG","ORG",4,"High",0,"2018-10-29","",1541768699
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| OS version (server)       | RedHat
| OS version (client)       | 7.6
| PHP version               | 7
| MISP version / git hash   | 2.4.97

### Expected behavior
Not exporting attributes with ids_flag set to no

### Actual behavior
Exporting attributes with ids_flag set to yes

### Steps to reproduce the behavior
Add attribute
- Category: Network activity
- Type: Hostname
- Value: google.com
- IDS: no

Run:
```
curl -X POST -k -H "Accept: application/json" -H 'Content-Type: application/json' --data '{"ignore": false, "type": "hostname", "last": "20d"}' -H "Authorization: xxx" "https://localhost/events/csv/download"
```

**Comment by xme** [comment]
I'm facing the same issue. We were using this feature for a while (ignore=false) and now, we have plenty of FP due to IOC exported even if their flag to_ids is set to "No"!?

**Comment by iglocska** [comment]
Will try to fix it tonight, it's indeed frustrating, giving a training atm.

**Comment by xme** [comment]
Any news about this? This is really impacting a customer...

**Comment by iglocska** [comment]
This was actually fixed a while back but forgot to merge the branch. If you git pull it should be fixed, let me know if it isn't though!
