### ISSUE TITLE
Ubuntu Server 16.04 An Internal Error Has Occurred

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#3867]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04.05.
| PHP version               | 7.1
| MISP version / git hash   | hash of the commit
| Browser                   | Chrome

### Expected behavior
MISP Login screen on my https://[vm_ip_address]/ 

### Actual behavior
An Internal Error Has Occurred.

### Steps to reproduce the behavior
Follow the installing steps on https://github.com/MISP/MISP/blob/2.4/docs/archive/INSTALL.ubuntu1604.md
go to https://[vm_ip_address]/

**Comment by SteveClement** [comment]
Internal errors are usually in the Webserver Logs.

Please post what your /var/log/apache2 error logs say.
Further, please use something less spammy then zippyshare.
Pastebin will work just fine. Thanks.

**Comment by iglocska** [comment]
Correction, the error logs of Misp are in /var/www/MISP/app/tmp/logs

**Comment by SteveClement** [comment]
@XizzoR it is probably a MySQL connection issue.

Also, please re-share the Logs.

**Comment by XizzoR** [comment]
Thanks for the response guys.
[](url)
[](url)
[](url)
[](url)
[](url)

**Comment by ghost** [comment]
Thanks for the response guys.

### Logs, screenshots, configuration dump, ...

[debug.log](https://pastebin.com/xKNzvgzp)
[error.log](https://pastebin.com/39JNtEWD)
[resque-2018-11-12.log](https://pastebin.com/CEn94VLQ)
[resque-scheduler-error.log](https://pastebin.com/EaD1SuCP)
[error.log from apache2](https://pastebin.com/A1UEfmPa)
[misp.local_error.log](https://pastebin.com/d8iuE0bc)

my apache.24.misp.ssl looks like:
```
<VirtualHost *:443>
        ServerAdmin xizzor@gmail.com
        ServerName 10.0.13.53
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                                Require all granted
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/misp.crt
        SSLCertificateKeyFile /etc/ssl/private/misp.key
        SSLCertificateChainFile /etc/ssl/private/rootCA.crt

        LogLevel warn
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
        Header set X-Content-Type-Options nosniff
        Header set X-Frame-Options DENY
</VirtualHost>
```
Why server name 10.0.13.53? This is the IP of my VM.

my /var/www/MISP/app/Config/database.php
```
<?php
class DATABASE_CONFIG {
        public $default = array(
                'datasource' => 'Database/Mysql',
                //'datasource' => 'Database/Postgres',
                'persistent' => false,
                'host' => ‘127.0.0.1’,
                'login' => ‘misp’,
                'port' => 3306,
                //'port' => 5432,
                'password' => ‘**********’,
                'database' => ‘misp’,
                'prefix' => '',
                'encoding' => 'utf8',
        );
}
?>
```

**Comment by stansecurecom** [comment]
> Thanks for the response guys.
> 
> ### Logs, screenshots, configuration dump, ...
> [debug.log](https://pastebin.com/xKNzvgzp)
> [error.log](https://pastebin.com/39JNtEWD)
> [resque-2018-11-12.log](https://pastebin.com/CEn94VLQ)
> [resque-scheduler-error.log](https://pastebin.com/EaD1SuCP)
> [error.log from apache2](https://pastebin.com/A1UEfmPa)
> [misp.local_error.log](https://pastebin.com/d8iuE0bc)
> 
> my apache.24.misp.ssl looks like:
> 
> ```
> <VirtualHost *:443>
>         ServerAdmin xizzor@gmail.com
>         ServerName 10.0.13.53
>         DocumentRoot /var/www/MISP/app/webroot
>         <Directory /var/www/MISP/app/webroot>
>                 Options -Indexes
>                 AllowOverride all
>                                 Require all granted
>         </Directory>
> 
>         SSLEngine On
>         SSLCertificateFile /etc/ssl/private/misp.crt
>         SSLCertificateKeyFile /etc/ssl/private/misp.key
>         SSLCertificateChainFile /etc/ssl/private/rootCA.crt
> 
>         LogLevel warn
>         ErrorLog /var/log/apache2/misp.local_error.log
>         CustomLog /var/log/apache2/misp.local_access.log combined
>         ServerSignature Off
>         Header set X-Content-Type-Options nosniff
>         Header set X-Frame-Options DENY
> </VirtualHost>
> ```
> Why server name 10.0.13.53? This is the IP of my VM.
> 
> my /var/www/MISP/app/Config/database.php
> 
> ```
> <?php
> class DATABASE_CONFIG {
>         public $default = array(
>                 'datasource' => 'Database/Mysql',
>                 //'datasource' => 'Database/Postgres',
>                 'persistent' => false,
>                 'host' => ‘127.0.0.1’,
>                 'login' => ‘misp’,
>                 'port' => 3306,
>                 //'port' => 5432,
>                 'password' => ‘**********’,
>                 'database' => ‘misp’,
>                 'prefix' => '',
>                 'encoding' => 'utf8',
>         );
> }
> ?>
> ```

So, how did you solve the issue?

**Comment by ghost** [comment]
I apologize, I forgot to say why I closed the issue.
Problem still persists (after 5 installation attempts), so I switch my OS from 16.04 to 18.04.1, followed 18.04 installation guide and successfully installed MISP from first attempt.
