### ISSUE TITLE
Bug with Download as... JSON format

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#387]
When using the Download as... option, and choosing the JSON format, I end up on an URL like:
https://[REDACTED]/events/view/870json
where no data in json is presented. My guess is that it is probably a problem when generating the URL to link to JSON.

**Comment by adulau** [comment]
@elhoim World's smallest patch imported in the production MISP.

**Comment by iglocska** [comment]
Well at least nobody will max out their "fair use" download quota :)

**Comment by aaronkaplan** [comment]
When following the documentation and extrapolating the XML example to JSON you end up with a URL:

curl -H "Authorization: XXXXX(redacted)XXXX"   -H "Accept: application/json" --insecure https://[redacted]/events/json/download/868.json" or a variation of these. But this URL does not work. It works for XML (replace json by xml in the example above!) but not with json. 
So, this is not very consistent in the documentation. 

My recommendation is to fix this in the documentation and show an example on how to use the JSON RESTful API. Or... (even better) make the XML and json API symmetrical.

**Comment by iglocska** [comment]
Yeah indeed that is really clunky right now and it's a pretty easy fix to
have a similar json api. Right now the XML API simply accepts a JSON or an
XML object as filter parameters and always returns an XML (which isn't very
handy). I'll add a JSON equivalent.
