### ISSUE TITLE
MISP relative redirects

### ISSUE THREAD

**Issue by ag-michael** [MISP/MISP#3871]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |RHEL
| OS version (client)       | 7.6
| PHP version               | whatever comes with MISP_v2.4.97@671ff699699b7bdc05c1141bab9366e3c0ea8e84
| MISP version / git hash   | MISP_v2.4.97@671ff699699b7bdc05c1141bab9366e3c0ea8e84
| Browser                   | Chrome and Firefox

### Expected behavior

I would expect MISP to use the configured baseurl or the page's URL for redirects.

### Actual behavior

MISP UI redirects using the http HOST field. The NGINX rever proxy passes 

### Steps to reproduce the behavior

Consider this nginx config:

```
 location / {
            auth_request /authenticateusers;
            error_page 401 =200 /loginform;
            proxy_pass http://10.0.6.2:8080/;
        }
```
MISP UI will try to redirect to http://10.0.6.2:8080 , that's not good. 10.0.6.2 is accessible only by nginx itself.

**Comment by cvandeplas** [comment]
What have you configured as `MISP.baseurl`  in the MISP server settings?

**Comment by ag-michael** [comment]
@cvandeplas , MISP.baseurl is set to `https://10.0.6.106:9980` which is running the nginx authenticating reverse proxy. No matter what, MISP would use the `Host` header set by the browser (which is passed through to apache on the MISP vm). 

Right now, I'm using a hack where I'm doing `proxy_set_header Host 10.0.6.106:9080` ,  problem is, misp would do http anyways (not https), so, I'm having nginx listen on 9080 redirect to 9980 for all the non-https requests misp makes -- and only chrome and IE allow this, firefox blocks 301's from https sites to http. 

The main issue here is that, the MISP UI should use the baseurl,regardless of what the `Host` header is set to and respect the scheme(https) as well.

**Comment by SteveClement** [comment]
This might be solved with the following config parameter: 

MISP.external_baseurl
"The base url of the application (in the format https://www.mymispinstance.com) as visible externally/by other MISPs. MISP will encode this URL in sharing groups when including itself. If this value is not set, the baseurl is used as a fallback."

**Comment by mossholderm** [comment]
From what I can see, this does not resolve the issue. Regardless of the settings of MISP.baseurl or MISP.external_baseurl , MISP always redirects to HTTP.

In a containerized setting, this is less than optimal, as it is often useful to front end container-based applications with a reverse proxy. I agree with ag-michael that MISP should utilize MISP.baseurl for the redirects, but failing that, perhaps there could be a MISP.redirect_baseurl which could be used in situations with a reverse proxy?

**Comment by iglocska** [comment]
MISP should in general always use MISP.baseurl to prepend links, however, we might have some cases where we rely on relative paths instead, causing issues with proxy setups. Could you list the endpoints that cause issues to help us resolve them?

**Comment by mossholderm** [comment]
I was being unintentionally hyperbolic in my last comment, it seems. The problem URLs so far appear to be:

${MISP.baseurl}/users/routeafterlogin (after entering successful credentials)
${MISP.baseurl} (when ${MISP.baseurl}/users/routeafterlogin tries to return after the preceding)

After a quick check, once you are logged in it appears to use baseurl for everything else.

**Comment by iglocska** [comment]
OK, that makes more sense. Indeed the login/logout routing did not take the baseurl into account. Should be fixed now.
