### ISSUE TITLE
STIX import creates tag for each character in tlp label

### ISSUE THREAD

**Issue by david74552** [MISP/MISP#3872]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 4.4.0-62-generic
| OS version (client)       | Ubuntu 4.15.0-38-generic
| PHP version               | 7.0.22-0ubuntu0.16.04.1
| MISP version / git hash   |  v2.4.97 (68c34be107fc4da09f1cb161c156fd99b19a1830) 
| Browser                   | N/A - Firefox Quantum 63.0 (64-bit)

### Expected behavior
Imported STIX file should create a tag which reads "tlp:amber"

### Actual behavior
Generates a tag for each character in the tlp tag:
![broken up text](https://user-images.githubusercontent.com/14916887/48446588-62728700-e7e5-11e8-8db1-5b794040f95e.png)
Example taken from STIX v1.1.1 file with tag
<marking:Marking_Structure xsi:type='tlpMarking:TLPMarkingStructureType' color="AMBER"/>

### Steps to reproduce the behavior
Import a STIX 1.x file with the node:
<marking:Marking_Structure xsi:type='tlpMarking:TLPMarkingStructureType' color="AMBER"/>

### Logs, screenshots, configuration dump, ...
See above, the software is all up to date.

**Comment by chrisr3d** [comment]
Thank you for reporting this issue, and sorry for the inconvenience, I just fixed it.

With the very latest version, it should now be working

**Comment by iglocska** [comment]
The bug that made events look like a ransom note from a serial killer.
