### ISSUE TITLE
Issue when moving objects from an event to another

### ISSUE THREAD

**Issue by l3m0ntr33** [MISP/MISP#3874]
BUG REPORT
--------------
When moving objects from an event to another event the "attribute count" column on event index page is not updated.
I mean that the attribute count is not decreased in the source event and not incremented in the destination event but the object is well moved from src to dest.

You will find below the source code to reproduce the issue.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu Server 18.04
| PHP version               | 7.2
| pymisp | 2.4.96
| MISP version / git hash   | v2.4.97 (abbc0364369ec90b91445142ab6cd2317cd6b705) 

### Expected behavior
Attribute count decreased in source event.
Attribute count increment in destination event.

### Actual behavior
Attribute stay the same on event index listing "attribute count" column even after moving the object.

### Steps to reproduce the behavior
PyMisp code below
```
evt = myMisp.get_event(src_event_id)
myEvt = pymisp.MISPEvent()
myEvt.load(evt)
obj = myEvt.objects[0]
myMisp.add_object(dst_event_id,object_template_id,obj)
```

**Comment by iglocska** [comment]
Fixed, that shouldn't work as intended there in the first place. To get it working and actually move an object from event A to event B (you need to be the creator of both events), do the following:

1. retrieve the object from event A
2. Unset all uuids in the object and contained attributes
3. run add_object with the sanitised object
4. Delete the original object
