### ISSUE TITLE
Change storage engine used for some tables

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#388]
Some of the important tables are using MyISAM instead of innodb. 
Innodb has lots of advantages for caching (not emptied after any writes) and concurrency (row-level locking instead of table level locking) among others.

**Comment by iglocska** [comment]
It does indeed, but some of those tables have full-text search keys,
something that in innodb is not supported as of MySQL 5.5 which ships with
ubuntu 14.04. At one point all tables that had more reads than writes were
innodb briefly, but we started getting reports about it not working from
users with MySQL 5.5 :(

**Comment by elhoim** [comment]
v5.6.4 has been out since 2011 (http://forums.mysql.com/read.php?3,506409,506409)
But it seems you can install v5.6 on ubuntu 14.04 by doing an 
```
    sudo apt-get install mysql-server-5.6
```
source: http://www.tocker.ca/2014/04/21/installing-mysql-5-6-on-ubuntu-14-04-trusty-tahr.html

For CentOS 6+, there is an official yum repo from MySQL directly:
http://dev.mysql.com/doc/refman/5.6/en/linux-installation-yum-repo.html

**Comment by elhoim** [comment]
Could we put MySQL v5.6 as a requirement starting from some version of MISP in the future (v2.5, v2.6 or whatever) to handle this?

**Comment by elhoim** [comment]
This might also help with #481

**Comment by adulau** [comment]
I suppose this is fixed. Feel free to reopen the issue if this is not considered to be fixed.
