### ISSUE TITLE
How to trigger an action on event creation? 

### ISSUE THREAD

**Issue by joydragon** [MISP/MISP#3881]
Is there a way to generate actions on event creation?
For example triggering a ticket creation on a ticketing server, or something on that nature
I was looking on the scheduled tasks because the prio worker was executed on each publciation (when publishing by the web interface).
Is the best option to modify the "prio" worker? To add another worker/scheduled task?
Is there any plans on this feature for any future updates?

**Comment by iglocska** [comment]
The best is to monitor the publish topic on the ZeroMQ sub system. Simply enable it, have a python script that acts as a subscriber (there is a sample script included) and you can monitor incoming events.

**Comment by enjeck** [comment]
> The best is to monitor the publish topic on the ZeroMQ sub system. Simply enable it, have a python script that acts as a subscriber (there is a sample script included) and you can monitor incoming events.

@joydragon  Did this reply answer your qestion?
