### ISSUE TITLE
Adding more than 1 galaxy/attribute to an event at a time

### ISSUE THREAD

**Issue by keydet89** [MISP/MISP#3882]
Is it possible be able to add more than one galaxy or attribute to an event at a time?  

Right now, for every galaxy/attribute, I have to open the dialog, select the one I want, and adding it closes the dialog.  I then have to re-open the dialog all over again for the next one.

Would it be possible to have a text field with auto-complete capability, where I can add as many galaxies/attributes as I need, at once?

Thanks.

**Comment by mokaddem** [comment]
Hi!
This feature is now live on the latest version of MISP.
Enjoy!
