### ISSUE TITLE
STIX XML file import: No IOC?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3884]
When I try to import a STIX XML file using the Import function from the web interface, it creates the event correctly and returns no error but the event does not have any IOC's!?

In the logs, I see:

`/usr/local/lib/python3.5/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'StructuredTextList' object.
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)`

It is related to the format of the XML file? My STIX knowledge is very low...

**Comment by iglocska** [comment]
Ping @chrisr3d 

@xme, could you share an example file that fails?

**Comment by xme** [comment]
Sure! (from  Alienvault's website)
[5bef7b301127e83c3a0c31ea.txt](https://github.com/MISP/MISP/files/2591784/5bef7b301127e83c3a0c31ea.txt)

**Comment by chrisr3d** [comment]
The issue came from the uuids, which I was fetching the wrong way.
I pushed a fix, it should be working now

**Comment by cvandeplas** [comment]
@xme can you confirm it's working now?

**Comment by adulau** [comment]
@xme I'll close the issue as it should have been fixed. Feel free to reopen if this is not fixed ;-) Thanks a lot for the report.
