### ISSUE TITLE
Trouble with Redis , Getting Redis Server went Away Error

### ISSUE THREAD

**Issue by ankyjk** [MISP/MISP#3887]
Exception: : Redis server went away at line 
while using HMSET in loop

**Comment by adulau** [comment]
Could you review the following:

- Is your server running? Can you connect using redis-cli?
- Is your server accessible in IPv6 and IPv4? Did you review the local firewall rules?

A previous issue with some good references https://github.com/MISP/MISP/issues/2104

Thank you very much.
