### ISSUE TITLE
PyMISP Status Issue

### ISSUE THREAD

**Issue by Crimson18** [MISP/MISP#3889]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | RedHat 7
| OS version (client)       | 
| PHP version               | 7.1
| MISP version / git hash   | 2.4.96, (6b8f846a4ea885ecda4b08605f0ff78642e76c09) 
| Browser                   | 

### Expected behavior
Both PyMISP 2 and 3 are installed onto the MISP server and we expected that the MISP Admin Server Settings & Maintenance Diagnostic webpage to indicate in the Advance attachment handler section that pymisp was installed and show the current version.  Both PyMISP versions work with our test code on the server.

### Actual behavior
The MISP Admin Server Settings & Maintenance Diagnostic webpage indicates in the Advance attachment handler section that pymisp and the other applications are not installed.  
![screen shot 2018-11-19 at 11 45 03 am](https://user-images.githubusercontent.com/44879935/48725365-94bf2280-ebf1-11e8-81a0-37528ea42357.png)

How do we get the MISP status screen to properly display the current PyMISP version?

**Comment by Glhenn** [comment]
+1

**Comment by SteveClement** [comment]
If this is still actual, please re-open.
