### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by mgeorgy** [MISP/MISP#389]
When attempting to add several attributes via FreeText import I'm presented with:

The request has been black-holed
Error: The requested address '/events/saveFreeText/6' was not found on this server.

Any suggestions?

**Comment by RichieB2B** [comment]
Black-holed usually means the CSRF token has expired and you need to log back in. Does this happen every time, even when you fill in the form right away? I mean, is it always reproducible?

**Comment by mgeorgy** [comment]
It occurred just a few second after I submitted another set of attributes for the same event.

I have logged out and back in hoping to renew my CSRF token without any luck.  The issue continues to occur every time I attempt to add the list of IOCs.

I was finally able to add the attributes by splitting them into smaller chunks.  <100 attributes worked fine.  150+ generated the same error.

**Comment by iglocska** [comment]
Interesting, so 150+ iocs in a freetext export causes this? I'll
investigate this in the morning!

**Comment by iglocska** [comment]
That was indeed an annoying bug. Thanks for the heads-up! :)

**Comment by mgeorgy** [comment]
Just now caught your response.  Thank you for addressing the issue.

**Comment by iglocska** [comment]
My pleasure!
