### ISSUE TITLE
API filtering not working

### ISSUE THREAD

**Issue by T3asp0on** [MISP/MISP#3894]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04 LTS
| OS version (client)       | Windows, Linux
| PHP version               | 7.2
| MISP version / git hash   | 2.4.97
| Browser                   | Firefox, Postman, Vivaldi

Hello,

I got some trouble with the MISP API. Indeed, I was looking for a way to export only my domain IOC as a CSV file.

I tried this url with GET method :
https://<misp url>/events/csv/download/false/false/false/false/domain

I also tried to send a POST request by following the doc

Can assist me on this please ?

Regards,

### Expected behavior
I should get a CSV file containing only attributes of domain's type.

### Actual behavior
In both cases, I got a CSV file containing all types of attributes (ip-dst, domain, snort, …).

**Comment by mokaddem** [comment]
Hello @T3asp0on,
The MISP Rest client is the recommended way and is a nice playground to try different searches. It can event generate cURL and PyMISP queries for you.

Regarding your query, if you want all attributes ``IOC`` (``to_ids`` flag) of type ``domain``, something like that should do the trick:
URL: ``/attributes/restSearch``
Body:
```
{
    "returnFormat": "csv",
    "type": "domain",
    "to_ids": 1
}
```

Cheers
