### ISSUE TITLE
Warning for duplicate objects (or attribute in object)

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3897]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request

### Expected behavior
Have (at least) a warning message when creating similar/duplicate objects, or object where an attribute already exists in the event.
The warning could also appear next to similar attributes/object

### Actual behavior
There is no warning at all, and it is even possible to create the same object (with the same values) several times

### Steps to reproduce the behavior
There are three similar possibilities (maybe more)
1. Create an attibute, then an object containing the same attribute 
- Create an attribute of type A with a value α
- Create an object containing an attribute of type A with the same value α
![existingattribute](https://user-images.githubusercontent.com/17081497/48892732-017b2c80-ee3f-11e8-95fc-7e2391c546de.png)
![attributeobject](https://user-images.githubusercontent.com/17081497/48892730-017b2c80-ee3f-11e8-953b-29a6529d7213.png)
(In fact, the order of creation does not matter, there is no warning either way)

2. Create two objects containing the exact same values
- Create an object A containing an attribute of type A with the value α
- Create an object B containing an attribute of type A with the value α
![duplicateobject](https://user-images.githubusercontent.com/17081497/48892731-017b2c80-ee3f-11e8-93de-f6983d9d46ee.png)

3. Create an object then an object that can include it
- Create an Object A containing an attribute of type A with the value α
- Create an Object B containing an attribute of type A with the value α AND at least an other attribute of type B with the value β 
![similarobjects](https://user-images.githubusercontent.com/17081497/48892733-017b2c80-ee3f-11e8-8464-9fbf170cc93d.png)
(In fact, the order of creation does not matter, there is no warning either way)

Note: The warnings on the screenshots exist because I used hashes of empty files to create the illustrations, they are not relevant with the issue.

(Similar to #2663 and #2826)

**Comment by mokaddem** [comment]
Thanks for the great description!
Will see what can be done.
