### ISSUE TITLE
Synchronization problem - user permission error

### ISSUE THREAD

**Issue by dawid-czarnecki** [MISP/MISP#3899]
Not all events are synchronized. On all of the configured servers after sync I see info like that:
> Pull completed. 0 events pulled, 19 events could not be pulled, 0 proposals pulled. 
Example event uuid: `57bf0e78-a160-478c-9ca0-5f27ac1d4fa4` on CIRCL instance.
On both source and destination instance the event is there with some differences.
Here is the log:
> Failed to pull event #57bf0e78-a160-478c-9ca0-5f27ac1d4fa4. Reason:Event could not be saved: The user used to edit the event is not authorised to do so. This can be caused by the user not being of the same organisation as the original creator of the event whilst also not being a site administrator. 

User who runs sync is admin via console:
```
./cake server pull 1 7 update
```
One of the different things is member organization.

The issue appeared after updated from 2.4.94 to 2.4.97.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7
| PHP version               | 7.1
| MISP version / git hash   | 2.4.97, 5849fad9a860f71000b8d43dd120ec48b0de3a1a

### Expected behavior
> Pull completed. 19 events pulled, 0 events could not be pulled, 0 proposals pulled. 

### Actual behavior
> Reason:Event could not be saved: The user used to edit the event is not authorised to do so. This can be caused by the user not being of the same organisation as the original creator of the event whilst also not being a site administrator.
> Reason:Event could not be saved: The user used to edit the event is not authorised to do so. This can be caused by the user not being of the same organisation as the original creator of the event whilst also not being a site administrator. 
> ...
> Pull completed. 0 events pulled, 19 events could not be pulled, 0 proposals pulled.

**Comment by SteveClement** [comment]
Is this still relevant?
