### ISSUE TITLE
Error: SQLSTATE[HY000]: General error: 1364

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#3901]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Error
| OS version (server)       | Centos 7.5-1804
| OS version (client)       | Centos 7.5-1804
| PHP version               | 7.0.32 (cli)
| rh-php71                   | 7.1.8 (cli)
| MISP version / git hash   | 2.4.98
| MariaDB                    |  10.3.11-MariaDB

# sudo $RUN_PHP "$CAKE Admin updateGalaxies"
Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(GalaxyCluster), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Model/Galaxy.php(151): Model->save(Array, false)
#6 /var/www/MISP/app/Console/Command/AdminShell.php(45): Galaxy->update(NULL)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateGalaxies()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('updateGalaxies', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#11 {main}

During the installation of a new MISP server I go the above error message when running "sudo $RUN_PHP "$CAKE Admin updateGalaxies"". All other commands work fine expect this one. I thought it may have been because I moved the mysql database, but after rebuilding it and leaving the database in the /var/lib/mysql directory I still got the same error.

Any assistance on trying to figure out what is causing this issue would be appreciated.

**Comment by SteveClement** [comment]
Thanks for the report. There were issues with the command if you are too "fast" ;)


I will double check the install docs to make sure this is not something frequent.

But it will have no impact to your install.

When in doubt, log into the web interface, and check if the galaxies are present.

If not, just update.
