### ISSUE TITLE
[Error] Class 'Elasticsearch\ClientBuilder' not found

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#3911]
MISP version = 2.4.98
Ubuntu 16.04 LTS

Under server settings I configured and then changed the ElasticSearch plugin from false to true and received the following error in the web interface:
"Request failed for an unknown reason".

The error.log file under /var/www/MISP/app/tmp/logs reports:

2018-11-29 11:24:17 Error: [Error] Class 'Elasticsearch\ClientBuilder' not found
Request URL: /servers/serverSettingsEdit/Plugin.ElasticSearch_logging_enable/0/1
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1495): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1486): AppModel->loadElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(267): AppModel->getElasticSearchTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Controller/ServersController.php(1280): Model->save(Array)
#8 [internal function]: ServersController->serverSettingsEdit('Plugin.ElasticS...', '0', '1')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

Other plugins are working successfully such as ZeroMQ and Enrichment.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by FloatingGhost** [comment]
Follow the [installation instructions for elasticsearch logging](https://raw.githubusercontent.com/MISP/MISP/2.4/docs/CONFIG.elasticsearch-logging.md)

You didn't install the library.

**Comment by timhux123** [comment]
Thanks for the info! Looks like I have a permissions issue I need to track down.
I followed the steps at https://raw.githubusercontent.com/MISP/MISP/2.4/docs/CONFIG.elasticsearch-logging.md.
I'm logged into the server with my regular user (not root).
This step was successful --> export MISP_DIR=/var/www/MISP
This step failed with permission denied --> cd $MISP_DIR/app

www-data has ownership of /var/www/MISP/app:
drwxr-x--- 16 www-data www-data 4.0K Nov 26 08:59 app

**Comment by timhux123** [comment]
Got past the permissions issue but still get the original "Class 'Elasticsearch\ClientBuilder' not found" error.
After completing "sudo -u www-data php composer.phar require elasticsearch/elasticsearch" from the install steps at https://raw.githubusercontent.com/MISP/MISP/2.4/docs/CONFIG.elasticsearch-logging.md I get the following which I'm not for sure is part of the issue:

sudo -u www-data php composer.phar require elasticsearch/elasticsearch
Cannot create cache directory /home/user/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/user/.composer/cache/files/, or directory is not writable. Proceeding without cache
Using version ^6.0 for elasticsearch/elasticsearch
./composer.json has been updated
Cannot create cache directory /home/user/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/user/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

"user" in the above output is the logged in user.

**Comment by SteveClement** [comment]
Well, ignore the warnings, it looks like the install actually worked.

Re-open if more issues arise.
