### ISSUE TITLE
Bug: [model-data] types are missing in "Network activity" category

### ISSUE THREAD

**Issue by Sh3idan** [MISP/MISP#3915]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu (virtualbox image)
| MISP version / git hash   | 2.4.98

### Expected behavior
Cannot add x509-fingerprint-md5 and x509-fingerprint-sha265 via API with default category (Network Activity). It is cause by incoherence between type category and default category since very old version (according to git diff) but effective since 2.4.96 (may be before)

### Actual behavior
Add x509-fingerprint-md5 and x509-fingerprint-sha2556 in Network activity category.
**See PR**: https://github.com/MISP/MISP/pull/3912

### Steps to reproduce the behavior
From REST client:
- Template: [attributes] add
- Relative path to query: /attributes/add/1 (FOR EXAMPLE)
- Show result check
- Body:
```
{
    "value": "11111111111111111111111111111111"
    "type": "x509-fingerprint-md5"
}
```

### Logs, screenshots, configuration dump, ...
Server response:
```
{
[...]
   "errors": {
        "type:": [
            "options depend on the selected category"
        ]
    }
}
```

**Comment by iglocska** [comment]
Indeed, merged your PR, thanks a lot!
