### ISSUE TITLE
Add options to auto tag on MISP Server Imports

### ISSUE THREAD

**Issue by DFi-Security** [MISP/MISP#3923]
Hello,

We think it could be good to have a new options to add specific tags under the Sync Actions on List Server

Indeed we would like to add the possibility to automatically add tags on event sync from a Server. (Each imported event from Server will inherit from remote event tags and add the new tag)

It would help us running some jobs and exports based on this tags and also could give more granularity on trust level.

Best regards,

**Comment by patricksvgr** [comment]
Yes, this was already requested: https://github.com/MISP/MISP/issues/3620

**Comment by DFi-Security** [comment]
Great new, I will close this one and wait for the update :)
