### ISSUE TITLE
Bug: API: "/events/upload_sample" no sample with advanced extraction

### ISSUE THREAD

**Issue by DragonDev1906** [MISP/MISP#3925]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | 
| OS version (client)       | Windows 10
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.98 & 2.4.99
| Browser                   | Firefox

### Expected behavior
Adding the Sample like it is when advancd=0

### Actual behavior
No Sample gets added, only the Additional Information

### Steps to reproduce the behavior
- Create a new Event
- Use the REST client to upload a sample:
  `/events/upload_sample/<event-id>`
  ~~~
  {
	"to_ids": "True",
	"category": "Payload delivery",
	"comment": "None",
	"advanced": 1,
	"files": [
		{
			"filename": "SAMPLE",
			"data": "AAAA"
		}
	]
  }
  ~~~
- Alternatively you can use PyMISP
  ~~~ python
  from pymisp import PyMISP
  m = PyMISP(misp_url, misp_api_key)
  m.upload_sample('Test Sample', b'Content of the File', 257, advanced_extraction=True)
  ~~~
- In the Event you can see a file object with the Information from advanced=1 but there is no Sample to be downloaded.

### Additional Information
- If advanced=0, the Sample is added but of course no further Information is added
  `/events/upload_sample/<event-id>`
  ~~~
  {
	"to_ids": "True",
	"category": "Payload delivery",
	"comment": "None",
	"advanced": 0,
	"files": [
		{
			"filename": "SAMPLE",
			"data": "AAAA"
		}
	]
  }
  ~~~
- Alternatively you can use PyMISP
  ~~~ python
  from pymisp import PyMISP
  m = PyMISP(misp_url, misp_api_key)
  m.upload_sample('Test Sample', b'Content of the File', 257, advanced_extraction=False)
  ~~~

**Comment by geekscrapy** [comment]
I have this issue also - Is this a known bug, or should we update?

I'm using version 2.4.103

**Comment by Rafiot** [comment]
That's fixed now.
