### ISSUE TITLE
Server option: Disable quick edit

### ISSUE THREAD

**Issue by mokaddem** [MISP/MISP#3937]
Users report that when they want to copy data from an attribute, it triggers the quick-edit form, which could be annoying. Having an option in the config to disable this feature could be nice.

**Comment by iglocska** [comment]
Hmph, that's why they trigger via double click, but sure, a setting to
disable it would be a quick win.

**Comment by cvandeplas** [comment]
I'm not sure that a server-wide setting is the best for this. This will increase the UI-interaction differences between each MISP instance and might result in an overall worse user-experience. 

Some other ideas: (brainstorm)
- show the edit box after one click, when clicking away or pressing escape the "edit mode" disappears. An edit is only really done if the user presses the "v" to confirm editing.
- upon hover show a small edit icon that the user can click to easily edit.

I would try to apply the same edit technique on all the editable elements (event, attribute, type, category, ...)

**Comment by StefanKelm** [comment]
> 
>     * upon hover show a small edit icon that the user can click to easily edit.
> 

I like that.

**Comment by iglocska** [comment]
Indeed!

**Comment by iglocska** [comment]
Fixed by @mokaddem
