### ISSUE TITLE
Extended view does not display all tags

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#3938]
The extended view of an event should show all tags for the event. Only tags from the extended event are currently displayed.

**Comment by iglocska** [comment]
woah, that sounds weird. Will have a look.

**Comment by ancailliau** [comment]
No update?

**Comment by SteveClement** [comment]
Is this still an issue?

**Comment by ancailliau** [comment]
Yes. I still do not see all tags in extended view.

We are running the last released version,

Antoine

**Comment by ancailliau** [comment]
Cannot reproduce in 2.4.116.
