### ISSUE TITLE
Full STIX Export not working

### ISSUE THREAD

**Issue by BeyondDawn** [MISP/MISP#3944]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug or support.
| OS version (server)       | Debian 9.6 
| OS version (client)       | NA
| PHP version               | 7.0.33-0+deb9u1
| MISP version / git hash   | 2.4.99 / cfe3841d8dd6a8642cd4a44315a482e62dbf271f
| Browser                   | NA

### Expected behavior
Full Database STIX export is currently not working (on demand url or Generated) 

### Actual behavior
Full STIX Export NOT WORKING
https://misp.local/events/stix/download/<event id> -> WORKS !
Download as STIX from inside an event -> WORKS !

### Steps to reproduce the behavior

https://misp.local/events/stix/download/ or https://misp.local/events/stix/download-> Not working :result is internal error

Export/Generate STIX -> Not working, Job start with Fetching 0/** events, run a long time (86s) and mark the job as finished not failed.
Back to Export Download -> got a zero file length for the stix file 

### Logs, screenshots, configuration dump, ...

Configuration
python3 /var/www/MISP/app/files/scripts/stixtest.py
{"maec": "4.1.0.14", "mixbox": "1.0.3", "success": 1, "stix": "1.2.0.6", "cybox": "2.1.0.17", "pymisp": "2.4.99"}

STIX: 1.2.0.6
CyBox: **2.1.0.18.dev0**
mixbox: 1.0.3
maec: 4.1.0.14
PyMISP: >2.4.93
Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
PYMISP library version…OK

PHP Settings
max_execution_time (300)… OK (recommended: 300)
memory_limit (512M)… OK (recommended: 512M)
upload_max_filesize (50M)… OK (recommended: 50M)
post_max_size (50M)… OK (recommended: 50M)

file created in cached_stix folder 
 -rw-r--r--  1 www-data www-data    0 déc.  13 14:46 misp.stix.ADMIN.xml)

Error.log - URL Call

2018-12-13 14:44:14 Error: [Exception]
Request URL: /events/stix/download/
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

Error.log - Action Generate

2018-12-13 14:46:42 Warning: fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5608]

Resque-Worker-Error.log
...
2018-12-13 14:46:28 Notice: Undefined index: Attribute in [/var/www/MISP/app/Lib/Export/StixExport.php, line 24]
Notice Error: Undefined index: Attribute in [/var/www/MISP/app/Lib/Export/StixExport.php, line 24]

2018-12-13 14:46:28 Notice: Undefined index: Attribute in [/var/www/MISP/app/Lib/Export/StixExport.php, line 24]
Warning Error: fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5608]

2018-12-13 14:46:42 Warning: fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5608]

Hello,
I'm new on MISP. Fresh install on Debian 9 (follow instruction) with CIRCL events feed only activated and cached. I am not been able to install misp-modules correctly so launch them manually (Issue with Intel472.py/api.py but curl -s http://127.0.0.1:6666/modules OK). All other exports work fine except Bro and Stix2 too . Export are made with admin first install user.
Any help would be appreciate. Thank you !

PS : VMWARE/OVA from circl produced different errors but results are the same (no full STIX export)

**Comment by iglocska** [comment]
The /events/stix api is deprecated (but should still work so we'll look into it), could you try the following as a temporary fix? 

use:

url: `/events/restSearch`
body: 
```
{
  "returnFormat": "stix"
}
```

This should be producing the equivalent with the new API endpoint.

**Comment by BeyondDawn** [comment]
It seems i've got same error 

No return in REST API Client (Testing with ARC)
Response header from POST URL /events/restSearch with body {  "returnFormat": "stix" }

**_Response Header_**

date: Thu, 13 Dec 2018 16:25:33 GMT
server: Apache/2.4.25 (Debian)
set-cookie: CAKEPHP=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; CAKEPHP=n8q4nuqh42hr8bi73ti0te8180; expires=Fri, 14-Dec-2018 02:25:33 GMT; Max-Age=36000; path=/; secure; HttpOnly; CAKEPHP=t3j3078desvc4k5n6l2c4qgbd3; expires=Fri, 14-Dec-2018 02:25:33 GMT; Max-Age=36000; path=/; secure; HttpOnly
x-result-count: 1158  **<- Total events in MISP**
**content-length: 0**
content-type: application/xml; charset=UTF-8

_**error.log**_

Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2018-12-13 16:48:36 Warning: Warning (2): fread() [<a href='http://php.net/function.fread'>function.fread</a>]: Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5608]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fread - [internal], line ??
Event::restSearch() - APP/Model/Event.php, line 5608
EventsController::restSearch() - APP/Controller/EventsController.php, line 3050
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by RichieB2B** [comment]
You can check the exec-error.log for the errors of the misp2stix.py script.

**Comment by BeyondDawn** [comment]
Here full file exec-errors.log 

/var/www/MISP/venv/lib/python3.5/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.5/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.5/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 1640, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 1635, in main
    stix_builder.generateEventPackages()
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 187, in generateEventPackages
    stix_packages = [getattr(self.generate_package(self.json_event['Event']), to_call)(**args)]
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 207, in generate_package
    self.generate_stix_objects()
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 255, in generate_stix_objects
    self.resolve_objects(Tags)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 306, in resolve_objects
    self.resolve_objects2parse(tags)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 323, in resolve_objects2parse
    pe_headers, pe_sections = self.parse_pe_references(pe_object, to_ids_list)
  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 351, in parse_pe_references
    pe_section_object = self.objects_to_parse['pe-section'][reference['referenced_uuid']]
KeyError: 'e5f2a5b2-f9b6-4536-8068-1e610b0a5b17'

**Comment by chrisr3d** [comment]
Can you provide us the event you want to export so we can see where the issue is ?

**Comment by BeyondDawn** [comment]
Exporting a unique event is clearly working (STIX XML from an event). But I am not able to export "all events" (from CIRCL feeds for example - 1160 events today).

By using the "Generate" Action in the "Export" UI from Event Actions, it results in a 0 length file.
By using the "Event actions\REST Client" POST  with template [events] RestSearch with returnFormat: stix, it generates "An Internal Error Has Occurred." web page. Same error for /attributes/restSearch template

Due to some minor  problem with installation, i switched to another fresh install on Ubuntu Server 18.04 with a complete clean install (no problem). I'm facing the same errors. Here is my config \:
 
Currently installed version… v2.4.99 (dc0b8c1084553a3587078f6c4d415c864fffa9eb)
Latest available version… v2.4.99 (dc0b8c1084553a3587078f6c4d415c864fffa9eb)
Status… OK
Current branch… 2.4 
 
PHP Settings

PHP ini path:… /etc/php/7.2/apache2/php.ini
PHP Version (>7.0.16 recommended): 7.2.10-0ubuntu0.18.04.1 (Up to date)
PHP CLI Version (>7.0.16 recommended): 7.2.10-0ubuntu0.18.04.1 (Up to date)

The following settings might have a negative impact on certain functionalities of MISP with their current and recommended minimum settings. You can adjust these in your php.ini. Keep in mind that the recommendations are not requirements, just recommendations. Depending on usage you might want to go beyond the recommended values.
max_execution_time (300)… OK (recommended: 300)
memory_limit (512M)… OK (recommended: 512M)
upload_max_filesize (50M)… OK (recommended: 50M)
post_max_size (50M)… OK (recommended: 50M)
PHP Extensions
Web
redis:… OK

Cli
redis:… OK

Advanced attachment handler
The advanced attachment tools are used by the add attachment functionality to extract additional data about the uploaded sample.
pydeep:… OK
lief:… OK
magic:… OK
pymisp:… OK
STIX and Cybox libraries

Mitre's STIX and Cybox python libraries have to be installed in order for MISP's STIX export to work. Make sure that you install them (as described in the MISP installation instructions) if you receive an error below.
If you run into any issues here, make sure that both STIX and CyBox are installed as described in the INSTALL.txt file. The required versions are:
STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
maec: 4.1.0.14
PyMISP: >2.4.93
Other versions might work but are not tested / recommended.
Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
PYMISP library version…OK

Any help will be appreciate. Thank you.

**Comment by chrisr3d** [comment]
I see, can you then give us the complete body you use to query the API ?

**Comment by BeyondDawn** [comment]
the proposed one  :
```
{
    "returnFormat": "stix"
}
```

**Comment by chrisr3d** [comment]
There was indeed something going wrong which is now fixed with the latest update.

If you still have issues it may be related to the big amount of data, and in that case I will try to debug it and see with @iglocska what is going. 
For the moment I tested with some of the largest event of the CIRCL OSINT feed, and it worked.

Poke me again if it is still failing for you

**Comment by BeyondDawn** [comment]
Full STIX Export ( Generate from Event Actions/Export) seems now TO WORK with CIRCL OSINT feed and other feeds as well. Currently installed version… v2.4.99 (d26a61ba03b1c559a0932ca5b99c1913e0f5fcb4)

Export from REST API with "returnFormat": "stix" and an "eventid" parameter WORKS.

It seems i got a failure / timeout ? without an eventid parameter. I will reopen the case if needed.

Thank you for your work.

Have an happy end of year.

**Comment by reza** [comment]
For anyone who ends up reading this page and has problems in generating STIX objects in XML format, please make sure you send Accept header as text/xml,  it does not work with application/xml and returnFormat:'xml' or 'stix' does not override it.
