### ISSUE TITLE
"Search Attributes" using Attribute UUID

### ISSUE THREAD

**Issue by Vesiix** [MISP/MISP#3945]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 7, 10
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.98
| Browser                   | Chrome

### Expected behavior
When using the "Search Attribute"in the GUI with attribute UUID, I get back the attribute that matches the UUID searched.

### Actual behavior
When searching with an attribute UUID in the GUI, I am getting no results.

Seems related to Issue #3930

**Comment by iglocska** [comment]
Yeah started working on it but it's a bit of a can of worms. Definitely have this on my radar as it's annoying.

**Comment by neok0** [comment]
same behavior for the API as well. Still valid for version .100

**Comment by Vesiix** [comment]
Attribute UUID search seems to be working now. I will close this issue, thanks!

**Comment by iglocska** [comment]
Thanks for the feedback!
