### ISSUE TITLE
MISP complains on specifying port in BaseURL settings 

### ISSUE THREAD

**Issue by bluejade-lin** [MISP/MISP#3946]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu, 
| OS version (client)       | 18.04
| PHP version               |7.2
| MISP version / git hash   | 2.4.99, a56e1b44b51c464fe13f5c65beb50f0be9dedf53
| Browser                   | If applicable

Was the feature allowing for adding a port to the base url disabled in  v2.4.99 (f5af41239e289fb2408ba3ff84f1ff9ca7ab56af)? I had it working on  v2.4.97 (4462a72206a9cce39559c1facee90efdec2a308d) 

### Expected behavior
add the port to the "Base URL" in the settings

### Actual behavior
Error: Invalid baseurl, it has to be in the "https://FQDN" format.

**Comment by iglocska** [comment]
Should work fine, working on my dev instance atm @ http://localhost:5000 without issues.

**Comment by bluejade-lin** [comment]
I tried reinstalling and updating to v2.4.99 (5b4079637acd21e3e9762c75c06dc85ff92b9f7d) . Same error

**Comment by SteveClement** [comment]
Not reproducible on current v2.4.100

Please join gitter for more help in case it does not work.

https://gitter.im/MISP/MISP
