### ISSUE TITLE
Invalid OVF checksum algorithm: SHA1

### ISSUE THREAD

**Issue by vboboia** [MISP/MISP#3947]
I've been trying to deploy the MISP_v2.4.98@430ddcd79c5863a54424f4a178f79136aaef0f1a.ova in vCenter version 6.5.0.20000 Build 9451637 and keep getting the following error: 

The provided manifest file is invalid: Invalid OVF checksum algorithm: SHA1. 

Is there any way to get past this error with that version of MISP? If not, do you know a MISP version that is compatible with vCenter version 6.5.0.20000 Build 9451637?

**Comment by SteveClement** [comment]
Dear @vboboia 

Please use the VMWARE image for testing first: https://www.circl.lu/misp-images/latest/MISP_v2.4.99@b2b382f159d956d478d5825357d1b790b68a06ca-vmware.zip

If needed, there is [ovftool.exe](https://my.vmware.com/web/vmware/details?productId=352&downloadGroup=OVFTOOL350) for OVA conversions. I do not recommend that route.

Finally, here is a screen cast on [How to import to ESXi](https://www.youtube.com/watch?v=Z4pKlp43_CM)

[Text version](https://github.com/MISP/MISP/issues/3437#issuecomment-403080550)
