### ISSUE TITLE
checkIfLoggedIn not defined on login page

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#3952]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | 2.4.XX (a very recent one) 

### Actual behavior
When loading the page `/users/login` the browser throws:
```
Uncaught ReferenceError: checkIfLoggedIn is not defined
    at HTMLDocument.<anonymous> (login:96)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at Function.ready (jquery.js:3536)
    at HTMLDocument.completed (jquery.js:3552)
```

**Comment by SteveClement** [comment]
@cvandeplas not sure how to reproduce this :(

Perhaps Browser specific? Safari?

**Comment by cvandeplas** [comment]
Google Chrome.
Make sure you are logged out of MISP.
Then open the developer console (`CTRL+SHIFT+i`), and reload the page.

**Comment by SteveClement** [comment]
Indeed. Thanks.

@iglocska anything to worry about?
Seems jquery related.

**Comment by cvandeplas** [comment]
Actually it's because  the JS containing this function is not loaded. See `./app/View/Layouts/default.ctp:71`
```php
    if ($me) {
        echo $this->Html->script('misp.js?' . $queryVersion);
        echo $this->Html->script('keyboard-shortcuts.js?' . $queryVersion);
    }:        echo $this->Html->script('misp.js?' . $queryVersion);
```
Give me a moment.

**Comment by cvandeplas** [comment]
@SteveClement can you quickly review & merge the PR https://github.com/MISP/MISP/pull/3989 ? 
There was also a weird useless `sprintf()` that I took away.

**Comment by iglocska** [comment]
Merged, thanks a lot!
