### ISSUE TITLE
Add atttribute types for the whole SHA2 family

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#396]
Since NIST seems to consider MD5 and SHA1 as deprecated, they recommend the whole SHA2 family and not only SHA256. The whole family includes: SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224 and SHA-512/256.

Reference: http://csrc.nist.gov/groups/ST/hash/policy.html
Related to: #390

**Comment by iglocska** [comment]
Sounds good

**Comment by Rafiot** [comment]
Done.
