### ISSUE TITLE
Errors connect to MISP 2.4.99

### ISSUE THREAD

**Issue by TuLeox7Cb** [MISP/MISP#3961]
I download VMware images with version MISP_v2.4.99  on Url: https://www.circl.lu/misp-images.
I tried to connect MISP dashboard on website. It have a error:
![image](https://user-images.githubusercontent.com/44956276/50206733-e8fb2500-039e-11e9-9896-a52f63df08a6.png)

**Comment by iglocska** [comment]
Could you check /var/www/MISP/app/tmp/error.log to see what the error message produced is? Thanks!

**Comment by SteveClement** [comment]
@Nightmarekcatta please provide more info if this is still an issue.

Like: are you using VMware player or Virtualbox or VMware esx etc.
What do the logs say?

In the mean time I close, feel free to re-open or join [gitter](https://gitter.im/MISP/MISP)

**Comment by TuLeox7Cb** [comment]
I tried to deploy on VMware agian. It was successed

Vào Th 2, 7 thg 1, 2019 vào lúc 12:13 Steve Clement <
notifications@github.com> đã viết:
