### ISSUE TITLE
Error in BaseURL check

### ISSUE THREAD

**Issue by lcpdn** [MISP/MISP#3962]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | W10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.99-11-g2198ec339
| Browser                   | Either Google Chrome, Chromium or FF

### Expected behavior
Well, I guess it should not block using https:// instead of http://

### Actual behavior
The MISP.BaseURL in MISP Settings doesn't allow me to use https:// and force on http://
My MISP instance is on a LXC, behind a reverse-proxy, the reverse proxy is doing the https-magic. 
May be related to issue #3946 

### Steps to reproduce the behavior
Hum. Reproduce continuously on my instance since I installed MISP (v2.4.99) on a fresh new LXC.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/11770960/50217311-a0d10800-0388-11e9-95cc-a055a25c80e1.png)

**Comment by bluejade-lin** [comment]
Did you find a solution to this? I still have the error - got another web server listening on 443

**Comment by iglocska** [comment]
One of the checks MISP does is what entry point you've used to reach it as
it will use the setting's value to prepend all URLs. If your routing works
fine afterwards don't worry about the error, just use the value that you
want users to access MISP by.

**Comment by SteveClement** [comment]
In this case it would indeed be more of an "orange" alert.
Of course MISP has no clue about your overall setup and how you proxy around etc.

Thus as @iglocska said, you can safely ignore it, as always, if you know what you're doing ;)
