### ISSUE TITLE
Publishing Event doesn't work: output visible in resque-worker.log / resque-worker-error.log

### ISSUE THREAD

**Issue by uforia** [MISP/MISP#3964]
We're trying to publish an Event, and it won't work. We do not get any errors in the UI (not in debug mode either), but are seeing this output in the logfiles .../app/tmp/logs/... when attempting to Publish.

We've tried a git pull to the latest MISP (2.4.99), and there are no errors in the diagnostics. We can't find anything related by Googling so far, and are having problems tracking down the cause. Does anyone have any pointers on how to solve this or how to start tracking this down?

[...]
==> resque-2018-12-19.log <==
[2018-12-19 15:33:41] main.INFO: got {"queue":"email","id":"ba1b020044fba9fb53f471fc7fdd3619","class":"EventShell","args":[["alertemail","3","103555","11631","1523978425"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"email\",\"id\":\"ba1b020044fba9fb53f471fc7fdd3619\",\"class\":\"EventShell\",\"args\":[[\"alertemail\",\"3\",\"103555\",\"11631\",\"1523978425\"]]})","worker":"ctimisp:22660"} []
[2018-12-19 15:33:41] main.INFO: Processing ID:ba1b020044fba9fb53f471fc7fdd3619 in email {"type":"process","worker":"ctimisp:22660","job_id":"ba1b020044fba9fb53f471fc7fdd3619"} []

==> resque-worker-error.log <==
Error: syntax error, unexpected '$options' (T_VARIABLE)
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(160): Resque_Job_Creator::createJob('EventShell', Array)
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(191): Resque_Job->getInstance()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('email', 1, Object(MonologInit\MonologInit), '5')
#6 {main}
[...]

**Comment by iglocska** [comment]
Woah, that is nasty. Fixed, please git pull and thanks for the heads-up.

**Comment by RichieB2B** [comment]
Thanks, fix is in 435bf28df6209c5c1e02687d0e44f18678292a63

**Comment by uforia** [comment]
Outstanding; thank you for the quick fix. Publishing works again!
