### ISSUE TITLE
Use constant id's for STIX observables and CYBOX objects

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#397]
In the STIX exports, the id's of indicator:Observable and cybox:Object elements are generated by the create_id() helper function. This function creates id's containing a random uuid. This makes deduplication of attributes in a target system harder than it should be.

Since in the STIX export each stixCommon:Indicator contains a single indicator:Observable which contains a single cybox:Object, can't we just use the attribute['uuid'] for all of them?

**Comment by iglocska** [comment]
Unless I am mistaken we have several cases where an Indicator can contain several observables, which would create clashing UUIDs for them, but I'll look into this!

**Comment by RichieB2B** [comment]
I looked into this today as well, and the Cybox python library allows the id of indicator:Observable to be set but not when using the convenient functions that automatically convert objects to observables. For cybox:Object however there is no setter for the id_ member. It really looks like these id's are meant to contain a random uuid, at least when generated with the Cybox python library. I'll see if I can get some clarification on this from MITRE.

**Comment by iglocska** [comment]
Thanks for looking into it! :)
