### ISSUE TITLE
MISP.python_bin under Server Settings does not store a value

### ISSUE THREAD

**Issue by befrankt** [MISP/MISP#3978]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug / Question
| OS version (server)       | ubuntu 16.04 and 18.04
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.99 and 2.4.100

### Expected behavior
I want to set my virtual Environment under the Server Settings (in the GUI).
The new configuration item MISP.python_bin is to be used for this.

### Actual behavior
No matter what I put in, the value returns to blank when I enter it. For example when I enter /var/ww/MISP/venv (which exists and seems to have the right permissions), I click the apply button and it results in being completely blank again...
Tried on different machines and updated MISP to 2.4.100 but no luck...

**Comment by SteveClement** [comment]
@befrankt investigating.

**Comment by mik5z** [comment]
I can confirm, that on MISP 2.4.102, this issue is still there. Tried to set this on a clean installation, but it won't stick.

**Comment by SteveClement** [comment]
I cannot reproduce this.

Can you please do the following on the command line:

```
ls -la $PYTHON_BIN
```

Please replace PYTHON_BIN with whatever you try to enter in the GUI.


as an example:

```
ls -la /var/www/MISP/venv/bin/python
lrwxrwxrwx 1 www-data www-data 7 Feb  4 09:58 /var/www/MISP/venv/bin/python -> python3
```

**Comment by mik5z** [comment]
Setting /var/www/MISP/venv/bin/python as value for PYTHON_BIN works!

**Comment by SteveClement** [comment]
Good, under the hood it checks:

is it executable
is it some form of supported binary

any other issues, re-open with according debug messages :)

thanks again for the report.
