### ISSUE TITLE
Feature Request: bulk tag/untag attributes within an event

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3985]
**Use-Case**
* Event with 1000s of attributes (some over 100k)
* Need to tag/untag all or a subset of attributes within that event
* Currently, PyMISP requires tag/untag each attribute with separate API calls

**Feature-Request**
* Add a bulk method to tag/untag a batch of attributes within an event or a list attributes not associated with a specific event with a single API call

**Prior discussion from  https://github.com/MISP/PyMISP/issues/267#issuecomment-41631631**

* @github-germ commented on Aug 27
   * Using tag and untag is the recommended way, and isn't known to be slow. Yes, tag/untag is reasonably fast. However, the one event that triggered this issue had 37k attributes that needed to be tagged. Is there no way to tag the attributes added to the in-memory MISPEvent vs. having to add/update the event followed by 37k separate tag/untag calls in a loop.
   * In light of hitting MISP core server load limits, would be nice to do as above, or send a list of tag/untag data in one PyMISP API request.

* @iglocska commented on Aug 28
   * Just a question: Do you want to tag all 37k attributes with the same tag?

* @github-germ commented on Aug 28
   * Yes. We are using estimative-language to map confidence scores received in data feeds. For this particular feed and those new attributes in that event all 37k were to get the same tag initially based on their score. That tag could be removed and replaced with another est-lang tag if the score changes over time.

* @iglocska commented on Aug 28
   * Why not set the tag on the event level?

* @github-germ commented on Aug 29
   * The estimative-language tag relates to the current state of the attribute within the tag. Eg an event with a large set of IP attributes where each individual IP state represented by the tag changes over time—every attribute could have varying tags.

**Comment by github-germ** [comment]
@Rafiot -- just check back on this one... What I have works, just thought this might improve efficiency. Thx.

**Comment by mokaddem** [comment]
The initial feature request ``Feature Request: bulk tag/untag attributes within an event`` is now live starting from a74dcdf.

**Comment by github-germ** [comment]
@mokaddem -- thanks very much for the `bulk tag/untag attributes` feature. i assume this is now part of 2.4.102.

can you point me to some documentation on how, for example to `untag` one specific `tag` from a list of attributes? that was my use case motivating this PR. when i look at the latest code for `untag` (https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L523) the signature still appears to accept a singular `uuid`. if that's true, how would one delete the same tag from a list of `uuid`s?

**Comment by mokaddem** [comment]
This is how you can ``untag`` using the mass edit tool
![massedit](https://user-images.githubusercontent.com/6977223/52422191-e642c380-2af5-11e9-9baa-f4af8732a80c.gif)

As of now, PyMISP (and the API) can't use the mass edit tool as it is not exposed.

**Comment by github-germ** [comment]
> As of now, PyMISP (and the API) can't use the mass edit tool as it is not exposed.

OK, i will create a separate issue for API mass edit, which was the intent of my original reason for creating this issue.
