### ISSUE TITLE
Stix upload does not work in v2.4.100

### ISSUE THREAD

**Issue by calum-cgi** [MISP/MISP#3986]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.100 (0f8bc5aea1f572db2dd3e4d5a04a8029c311a3ef) 

### Expected behavior
`STIX document imported.`
STIX uploader works as expected in version v2.4.99 (083beae50271efc8ab960f07ae7563f3eff3bd94).
STIX file uploads and is converted to MISP.

### Actual behavior
I see an error: ` Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.`

### Steps to reproduce the behavior
Using the stix 2.0 uploader, add the below stix to a misp server running v2.4.100. 

```json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "indicator",
      "id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
      "created": "2014-06-29T13:49:37.079Z",
      "modified": "2014-06-29T13:49:37.079Z",
      "labels": [
        "malicious-activity"
      ],
      "name": "Malicious site hosting downloader",
      "pattern": "[url:value = 'http://x4z9arb.cn/4712/']",
      "valid_from": "2014-06-29T13:49:37.079000Z"
    },
    {
      "type": "malware",
      "id": "malware--162d917e-766f-4611-b5d6-652791454fca",
      "created": "2014-06-30T09:15:17.182Z",
      "modified": "2014-06-30T09:15:17.182Z",
      "name": "x4z9arb backdoor",
      "labels": [
        "backdoor",
        "remote-access-trojan"
      ],
      "description": "This malware attempts to download remote files after establishing a foothold as a backdoor.",
      "kill_chain_phases": [
        {
          "kill_chain_name": "mandiant-attack-lifecycle-model",
          "phase_name": "establish-foothold"
        }
      ]
    },
    {
      "type": "relationship",
      "id": "relationship--6ce78886-1027-4800-9301-40c274fd472f",
      "created": "2014-06-30T09:15:17.182Z",
      "modified": "2014-06-30T09:15:17.182Z",
      "relationship_type": "indicates",
      "source_ref": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
      "target_ref": "malware--162d917e-766f-4611-b5d6-652791454fca"
    }
  ]
}
```

I have reverted back to v2.4.99 for now. Thank you to whoever picks this up and fixes it 👍

**Comment by adulau** [comment]
Confirmed in 2.4.100

**Comment by chrisr3d** [comment]
The issue is related to the stix2 python library which should be installed from our [forked repository](https://github.com/MISP/cti-python-stix2.git) in the VM. I am trying to figure out why it is not this version of the library which is currently running on the latest MISP VMs generated.

For the moment, you can pull the latest updated version of MISP and install the right version of the stix2 library:
`cd /var/www/MISP`
`git pull origin 2.4`
`git submodule update`
`cd cti-python-stix2/`
`/var/www/MISP/venv/bin/pip install .`

Then it should not generate errors anymore, otherwise please show us the content of the file `/var/www/MISP/app/tmp/logs/exec-errors.log` so I can see what is going on.

**Comment by calum-cgi** [comment]
Thank you @chrisr3d - I followed your steps and it's working for me 👍

**Comment by chrisr3d** [comment]
The good version of the library is now install by default with the latest VMs, so everything should be ok.

Do not hesitate to ping us again if anything goes wrong.

Thank you

**Comment by mendickxiao** [comment]
cat /var/www/MISP/app/tmp/logs/exec-errors.log
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1421, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1391, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
