### ISSUE TITLE
[Error] Class 'Redis' not found

### ISSUE THREAD

**Issue by hccccchung** [MISP/MISP#3987]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Kail "2017.3"
| OS version (client)       | Any
| PHP version               | Default scripts install
| MISP version / git hash   | 2.4.100
| Browser                   | Any

### Expected behavior
New install. Can login.

### Actual behavior
Can loign, but after login, it only has bank page with HTTP ERROR 500

### Steps to reproduce the behavior
Just reinstall it in Kail. 

### Logs, screenshots, configuration dump, ...
2019-01-05 23:00:31 Error: [Error] Class 'Redis' not found
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1478): PubSubTool->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1469): AppModel->loadPubSubTool()
#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(NULL, Array)
#7 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(252): Model->save(NULL, Array)
#8 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(103): SysLogLogableBehavior->_saveLog(Object(AdminSetting), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SysLogLogableBehavior->afterSave(Object(AdminSetting), true, Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('afterSave')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#13 /var/www/MISP/app/Model/AppModel.php(1343): Model->save(Array)
#14 /var/www/MISP/app/Model/AppModel.php(1289): AppModel->__runCleanDB()
#15 /var/www/MISP/app/Controller/AppController.php(294): AppModel->runUpdates()
#16 /var/www/MISP/app/Controller/UsersController.php(30): AppController->beforeFilter()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): UsersController->beforeFilter(Object(CakeEvent))
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#21 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#22 {main}
2019-01-05 23:00:32 Error: Fatal Error (1): Uncaught Error: Class 'Redis' not found in /var/www/MISP/app/Lib/Tools/PubSubTool.php:34
Stack trace:
#0 /var/www/MISP/app/Model/AppModel.php(1478): PubSubTool->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1469): AppModel->loadPubSubTool()
#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(NULL, Array)
#7 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(252): Model->save(NULL, Array)
#8 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(103): SysLogLogableBehavior->_saveLog(Object(AdminSetting), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SysLogL in [/var/www/MISP/app/Lib/Tools/PubSubTool.php, line 34]
2019-01-05 23:00:32 Error: [InternalErrorException] Internal Server Error
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 34)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 34, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by adulau** [comment]
You are missing the Redis module in PHP.

`pecl install redis`
`echo "extension=redis.so" | tee /etc/php/7.2/mods-available/redis.ini`
`phpenmod redis`

don't forget to restart your HTTP server.

**Comment by hccccchung** [comment]
root@kali:/var/www/MISP# pecl install redis
pecl/redis is already installed and is the same as the released version 4.2.0
root@kali:/etc/php/7.0/mods-available# phpenmod redis
WARNING: Module redis ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module redis ini file doesn't exist under /etc/php/7.0/mods-available

I should use php 7.0 or 7.2? I think the version miss match. The redis is too new?

**Comment by adulau** [comment]
The install script for Kali was done for PHP 7.2 if I recall correctly.

**Comment by hccccchung** [comment]
Problem fix. I do not know why it using 7.0. 7.0 do not have redis. 

I uninstall 7.0. Than change the config in HTTP server to make use it uses 7.2.

**Comment by adulau** [comment]
Thanks for the feedback and have fun with MISP ;-)

**Comment by adhamai** [comment]
Hello,
I still have the same error,  I have tried the command above but now an only white blank page. 

[Fri Jan 25 12:07:49.662110 2019] [php7:error] [pid 5634] [client 127.0.0.1:60736] PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/MISP/app/Lib/Tools/PubSubTool.php:34\nStack trace:\n#0 /var/www/MISP/app/Model/AppModel.php(1508): PubSubTool->initTool()\n#1 /var/www/MISP/app/Model/AppModel.php(1499): AppModel->loadPubSubTool()\n#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()\n#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)\n#7 /var/www/MISP/app/Model/AppModel.php(1136): Model->save(Array)\n#8 /var/www/MISP/app/Model/AppModel.php(172): AppModel->updateDatabase(13)\n#9 /var/www/MISP/app/Model/AppModel.php(1333): AppModel->updateMISP(13)\n#10 /var/www/MISP/app/Controller/AppController.php(294): AppModel->runUpdates()\n#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeE in /var/www/MISP/app/Lib/Tools/PubSubTool.php on line 34
