### ISSUE TITLE
icon missing in Galaxies

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#3990]
As latest MISP uses not latest Awesome font version (Font Awesome 4.7.0) "open door" icon for Backdoor Galaxy is missing. Open door icon if found starting from Awesome font version 5.0.13

**Comment by SteveClement** [comment]
Instructions on how to upgrade: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by Turecky** [comment]
Need to update/fix Galaxies icon naming. Recommendation:
```
Malpedia
fa-shield => fa-shield-alt

Preventive Measure
fa-shiled => fa-shield-virus
```

**Comment by Turecky** [comment]
Still missing icons for `Preventive Measure` and `Malpedia`

**Comment by adulau** [comment]
@Turecky Thank you it's now fixed in the galaxy. It will be available in the next release.
