### ISSUE TITLE
Tag Collection - Missing permission and other issues

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3992]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.100

### Expected behavior
As an Org admin, being able to:
• Create a Tag Collection
• Add a Galaxy to a Tag Collection
• Delete a Galaxy from a Tag Collection
• Add a Tag to a Tag Collection
• Delete a Tag from a Tag Collection

### Actual behavior
As an Org admin, I am able to:
:heavy_check_mark:  Create a Tag Collection
:heavy_check_mark:   Add a Galaxy to a Tag Collection
:x: Delete a Galaxy from a Tag Collection
:x: Add a Tag to a Tag Collection (do not have the permission)
:x: Delete a Tag from a Tag Collection (Obviously)

### Steps to reproduce the behavior  
As an Org Admin:
• Create a Tag Collection
• Add a Tag to a Tag Collection

• Add a Galaxy to a Tag Collection
• Try to delete the added galaxy from the tag collection

### Logs, screenshots, configuration dump, ...
• Adding a Tag:
![screenshot from 2019-01-08 08-58-43](https://user-images.githubusercontent.com/17081497/50817431-1430be80-1324-11e9-823d-fb0099e390ed.png)

• Delete a galaxy:
![screenshot from 2019-01-08 09-23-25](https://user-images.githubusercontent.com/17081497/50818408-206a4b00-1327-11e9-8b39-3ae11fb4c7e1.png)

**Comment by Delta-Sierra** [comment]
Added issue about deleting galaxy from a tag collection

**Comment by mokaddem** [comment]
Thanks for the report!
This should be solved now.
