### ISSUE TITLE
Tag Collections - Tag replaced/hidden when a new galaxy cluster is added

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#3994]
- When a galaxy cluster (here CopyCat) is added, the matching tag is also added 
![screenshot from 2019-01-08 12-23-34](https://user-images.githubusercontent.com/17081497/50828038-80212000-1340-11e9-9bae-e2deda623e8f.png)

- When adding a second galaxy cluster (Poison Ivy), the matching tag is also added to the list of tags, and the tag matching the first galaxy cluster disappears (or is at least hidden)
![screenshot from 2019-01-08 12-23-57](https://user-images.githubusercontent.com/17081497/50828039-80212000-1340-11e9-875f-901da6c1d3e2.png)

- (As there is an issue on deleting galaxy cluster), deleting the visible tag delete also the matching galaxy cluster, and the previous tag is visible again. 
![screenshot from 2019-01-08 12-23-34](https://user-images.githubusercontent.com/17081497/50828038-80212000-1340-11e9-9bae-e2deda623e8f.png)

**Comment by Delta-Sierra** [comment]
Update: it may also hide a tag that is not related to a galaxy cluster

• Initial state
![001](https://user-images.githubusercontent.com/17081497/50884314-dd71ab80-13ea-11e9-8071-71758616d420.png) 

• Adding the CopyCat Cluster make the Veris tag disappear.
![002](https://user-images.githubusercontent.com/17081497/50884320-dfd40580-13ea-11e9-9c58-19e5228253fe.png) 
(The Veris tag is only invisible since it can not be added again)

 :warning: Adding a cluster (and its related tag) does NOT necessarily implies  that an other tag will be hidden

**Comment by mokaddem** [comment]
This issue is related to #4000. It is now fixed. Thanks!
