### ISSUE TITLE
Access API through browser Javascript (CORS)

### ISSUE THREAD

**Issue by alper** [MISP/MISP#3996]
If I try to access the MISP API using a bit of javascript served in a webpage, I get the predictable:
`Access to XMLHttpRequest at 'http://127.0.0.1/events/restSearch' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Is there a possibility to enable cross-site access to the API (since access is protected by the `Authentication` header anyway)? Or do I have to make our own passthrough API proxy using PyMISP?

**Comment by FloatingGhost** [comment]
Gonna +1 this

You're not actually hitting a CORS issue, but a non-200 response here

Currently MISP will check API key headers on `OPTIONS` requests and reject if there isn't one, and `OPTIONS` should not have any custom headers attached, hence we always hit a 403.

Browsers will always send an `OPTIONS` call if you set the `Content-Type` header (as you have to for MISP to recognise that you want JSON)

So the solution would be to add handling for `OPTIONS` requests and potentially customisable CORS origin headers

**Comment by alper** [comment]
Thanks for this. In the meantime I'm running something like this for development purposes:

```python
from flask import Flask, request
from flask_cors import CORS

import requests
import sys

app = Flask(__name__)
CORS(app)


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>', methods=["GET", "POST"])
def catch_all(path):
    if path == '':
        return open('index.html').read()
    else:
        headers = {
            'Authorization': 'SECRET',
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        }

        print("Requested path", path, file=sys.stderr)
        print(request.get_data(), file=sys.stderr)

        if request.method == "POST":
            r = requests.post('http://localhost/' + path, headers=headers, data=request.get_data())
        elif request.method == "GET":
            # GET requests do not get data passed in the body
            r = requests.get('http://localhost/' + path, headers=headers)

        # Dump whatever json is returned to disk for debugging
        if '/' in path:
            open(path.replace('/', '_') + '.json', 'w').write(r.text)

        return r.text


if __name__ == '__main__':
    app.run(debug=True)
```
