### ISSUE TITLE
Tag Collections - First added cluster does not add the equivalent tag

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/MISP#4000]
• Create a new Tag Collection
![001](https://user-images.githubusercontent.com/17081497/50886253-4ad40b00-13f0-11e9-8bc5-6ff6ae3c4133.png)

• Add a first cluster (no tag added)
![002](https://user-images.githubusercontent.com/17081497/50886254-4ad40b00-13f0-11e9-9c01-53f375251871.png)

• Add a second cluster (equivalent tag added)
![003](https://user-images.githubusercontent.com/17081497/50886255-4b6ca180-13f0-11e9-8a1f-55e80cc46b82.png)

Btw: since it's impossible for now to delete a galaxy cluster (cf issue #3992), it is in fact impossible to delete the first added cluster (while the tags can be used to delete other clusters)

**Comment by mokaddem** [comment]
Thanks again for the complete report.
It should be fix now.
