### ISSUE TITLE
Unable to group tag

### ISSUE THREAD

**Issue by Vesiix** [MISP/MISP#4003]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Support
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Windows 10/7
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.100
| Browser                   | Chrome

### Expected behavior
Able to select multiple attributes and tag them all at once as an "org admin".

### Actual behavior
Comes back with an error in the UI saying it was only able to add 1 tag.

### Steps to reproduce the behavior
1. Have an instance of MISP 2.4.100
2. Add user as "org admin"
3. Log in to org admin user account
4. Create an "Event"
5. Add several attributes to the Event
6. Select all attributes
7. Click the tag group icon on top left of Attribute section
8. Click through and select any tag

### Logs, screenshots, configuration dump, ...

MISP error.log:
```
2019-01-09 XX:XX:XX Error: [MissingViewException] View file "Events/ajax/event_lock.ctp" is missing.
Exception Attributes: array (
  'file' => 'Events/ajax/event_lock.ctp',
)
Request URL: /events/checkLocks/1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Events/ajax/eve...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render('/Events/ajax/ev...', NULL)
#2 /var/www/MISP/app/Controller/EventsController.php(5138): Controller->render('/Events/ajax/ev...')
#3 [internal function]: EventsController->checkLocks('1')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by mokaddem** [comment]
Hi!
A huge rewrite of the tag picking has been done and is now live on the latest version of MISP.
Feel free to open a new issue if you spot new bugs.
Thanks!
