### ISSUE TITLE
Tag assignment not working like it did 2.4.100

### ISSUE THREAD

**Issue by SparkyNZL** [MISP/MISP#4006]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Windows 10
| PHP version               | 7.1
| MISP version / git hash   | 2.4.100
| Browser                   | Firefox

### Expected behavior
When adding a tag to an event, you click on the "+" this will then bring up the search box, typing in "Ransomware" will list a bunch of ransomware items, but when you click on one it shows "Failed to add" in red.

If I do this the longer way, Click on "+" to add tag, search box appears, then click on custom tags then search for "ransomware" this then adds the tag.

I have attached screen shots

Cheers

### Logs, screenshots, configuration dump, ...
![search](https://user-images.githubusercontent.com/17818264/50991056-a6c99b80-1578-11e9-90eb-a0138a5f294f.jpg)
![screenshot2](https://user-images.githubusercontent.com/17818264/50991453-89e19800-1579-11e9-842c-9371f71459db.jpg)

**Comment by mokaddem** [comment]
Hi!
A huge rewrite of the tag picking has been done and is now live on the latest version of MISP.
Feel free to open a new issue if you spot new bugs.
Thanks!
