### ISSUE TITLE
Attribute Request - HASSH

### ISSUE THREAD

**Issue by malware-kitten** [MISP/MISP#4007]
This request is similar to the support built in for JA3.

HASSH is a fuzzy hashing method that is used for profiling SSH connections.  The attribute is simply a MD5 hash.

More can be found here.  
(https://github.com/salesforce/hassh)

**Comment by adulau** [comment]
Indeed, it sounds to be a very good idea. I will add those. Just to be sure, it would two different new attributes matching the MD5 hexadecimal representation: 

- "hassh" for the SSH client side fingerprint
- "hasshServer" for the SSH server side fingerprint

Thank you

**Comment by adulau** [comment]
`hassh-md5` and `hasshserver-md5` are now new types part of the MISP Project and included in the standard MISP format. Thank you very much for the idea.

**Comment by malware-kitten** [comment]
Thank you for considering and implementing this idea!
