### ISSUE TITLE
[Master ticket for automatic YARA rules creation] Export hashes using yara rules

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#401]
Offer an export format to have relevant hashes (with To IDS = True) in a yara rule since yara supports a module called hash that supports md5, sha1 and sha256.

Open-question being: one yara rule per event and/or one global yara rule?

Documentation:
http://yara.readthedocs.org/en/latest/writingrules.html#using-modules
http://yara.readthedocs.org/en/latest/modules/hash.html

**Comment by iglocska** [comment]
http://www.quickmeme.com/img/c2/c26809e3a038ae40c48384056be3891a0adcbf3ea2d13053e5ca83d8deb93798.jpg

Will look into this!

**Comment by Rafiot** [comment]
https://github.com/MISP/MISP/issues/348
https://github.com/MISP/MISP/issues/346
https://github.com/MISP/MISP/issues/345

**Comment by adulau** [comment]
Should we close this based on the existing export API tool? https://github.com/MISP/yara-misp/blob/master/yara_misp.py

**Comment by iglocska** [comment]
module after API rework imho

**Comment by adulau** [comment]
So we can move the issue to misp-modules then and close this one. 

Issue here: https://github.com/MISP/misp-modules/issues/182
