### ISSUE TITLE
php7.2-related packets installation error using INSTALL.kali.txt

### ISSUE THREAD

**Issue by DmitryJustDmitry** [MISP/MISP#4012]
https://github.com/MISP/MISP/blob/c7fd161d497a2a8c24f767acda3dc3f48d44610a/INSTALL/INSTALL.kali.txt#L102

Hi everyone.
Got some troubles using INSTALL.kali.txt. According to http://pkg.kali.org/pkg/php7.2# php7.2-related packages do not persist anymore in kali repos (from 2019-01-09). So I got plenty of errors trying to use this installation script. Looks like these should be changed to php7.3 versions.

**Comment by SteveClement** [comment]
Dear, indeed, I updated that recently, but there is still a redis bug I need to iron out.

The current script "works" in the sense that it actually installs all the dependencies but, again, Class Redis is missing.

I will let you know once I fixed it.

Sorry for the inconvenience.

**Comment by SteveClement** [comment]
This is fixed with the latest script.
