### ISSUE TITLE
Variable $MISP_USER is not used properly in INSTALL.kali.txt 

### ISSUE THREAD

**Issue by DmitryJustDmitry** [MISP/MISP#4013]
https://github.com/MISP/MISP/blob/c7fd161d497a2a8c24f767acda3dc3f48d44610a/INSTALL/INSTALL.kali.txt#L22

Hi everyone.
Looks like statiacl username 'misp' should be changed to $MISP_USER here and on the next line №23.

**Comment by SteveClement** [comment]
Thanks, will fix it.
