### ISSUE TITLE
Need Help With Sharing Model

### ISSUE THREAD

**Issue by finnam-cgi** [MISP/MISP#4015]
What's the correct way to share Events with a remote MISP instance and they being downgraded to "This Orgaqnisation Only" on the remote instance?

**Comment by RichieB2B** [comment]
The sharIng model is: connected communities -> this community -> organization only. The level decreases every time an event is shared with an external MISP. So if you want the event to be “organization only” when it is being shared out of your MISP set the event to “this community”.

**Comment by finnam-cgi** [comment]
Thanks.  I tried that, but "this community" doesn't get published to the remote MISP instance.

**Comment by finnam-cgi** [comment]
Testing this a bit more and we're seeing some inconsistent behaviour between pushing and pulling. Ideally, we would like to push from A-->B after publishing. 

1. Push on A, A-->B (this community) - doesn't get to B
2. Pull on B, A-->B (this community) - does get to B (distribution downgraded to Organisation)
3. Push on A, A-->B (connected community) - does get to B (distribution downgraded to community)
4. Pull on B, A-->B (connected community) - does get to B (distribution downgraded to community)

Ideally we want to get test 1 working in a similar behaviour to test 2 (i.e. we want to push to the community only).

**Comment by RichieB2B** [comment]
I think this is by design. The last step from This Community -> Organization only works on pull.

**Comment by iglocska** [comment]
Correct. The reason for that is that when you push you create the data with
your sync user on the far end. Creating it as community only when you push
data to someone else's instance and downgrading it to your org only
wouldn't make any sense.

**Comment by finnam-cgi** [comment]
Thanks!  That makes sense not you have explained it.
