### ISSUE TITLE
MISP Interface Blank - Unable to Login

### ISSUE THREAD

**Issue by briglewis** [MISP/MISP#4027]
Hi,

I've installed a local instance of MISP in Kali through VirtualBox and I can get to the login screen but when I use the default creds it returns a blank screen.

The error log reads:

php7:error] [pid 2764] [client 127.0.0.1:36108] **PHP Fatal error:  Uncaught Error: Class 'Redis' not found** in /var/www/MISP/app/Lib/Tools/PubSubTool.php:34\nStack trace:\n#0 /var/www/MISP/app/Model/AppModel.php(1505): PubSubTool->initTool()\n#1 /var/www/MISP/app/Model/AppModel.php(1496): AppModel->loadPubSubTool()\n#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()\n#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(NULL, Array)\n#7 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(252): Model->save(NULL, Array)\n#8 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(103): SysLogLogableBehavior->_saveLog(Object(AdminSetting), Array)\n#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SysLogL in /var/www/MISP/app/Lib/Tools/PubSubTool.php on line 34, referer: https://misp.local/users/login

---

Thanks!

![blank_page](https://user-images.githubusercontent.com/19641210/51363097-a0b05d80-1b2a-11e9-87ee-43be6a63770b.PNG)

**Comment by adulau** [comment]
As we can see in the logs you pasted, the Redis module in PHP is not installed/enabled. 

If you are using PHP 7.3 (replace the version if you are using a different one:

~~~~
apt install php7.3-redis
phpenmod -v 7.3 redis
~~~~

I hope this helps.

**Comment by briglewis** [comment]
Hi,

Everything is installed but I still get that same error:

`[Sun Jan 20 19:38:42.614243 2019] [php7:error] [pid 2921] [client 127.0.0.1:33890] PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/MISP/app/Lib/Tools/PubSubTool.php:34\nStack trace:\n#0 /var/www/MISP/app/Model/AppModel.php(1505): PubSubTool->initTool()\n#1 /var/www/MISP/app/Model/AppModel.php(1496): AppModel->loadPubSubTool()\n#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()\n#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(NULL, Array)\n#7 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(252): Model->save(NULL, Array)\n#8 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(103): SysLogLogableBehavior->_saveLog(Object(AdminSetting), Array)\n#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SysLogL in /var/www/MISP/app/Lib/Tools/PubSubTool.php on line 34, referer: https://misp.local/users/login
`
---

I'm using PHP 7.3 - redis is installed - what file path does it need to be installed in for the script to call it correctly? 

Thanks!
