### ISSUE TITLE
Add attribute type filename-pattern

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#403]
To support matching for filenames that are a partially or totally randomly generated.

Pattern being of type PCRE (not others more obscure, less supported variations of regular expressions).
Related to #120 

For syntax validation it would be great if the regex was evaluated with PHP regex library.

**Comment by iglocska** [comment]
This has some serious performance related consequences, but it would indeed
be handy. Same for IP range / subnet matching to IP addresses.

**Comment by iglocska** [comment]
As for PCRE, maybe a better option would be substring matching. The problem is that giving users access to creating regular expressions that would be introduced into frequent execution by all users would open up a whole new can of worms (think infinite loops).

**Comment by elhoim** [comment]
I was just talking from a point of view of adding that as attribute type, not necessarily to correlate events based on it.

**Comment by iglocska** [comment]
Ah that would indeed be easy to do!

**Comment by elhoim** [comment]
For the IP ranges, it is issue #126 :)

**Comment by iglocska** [comment]
As a side-note: You can add CIDR notation IP addresses already, though they won't be used in the correlation (or more accurately, it is still a simple string match).
