### ISSUE TITLE
Proper backup for current MISP

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#4030]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Help
| OS version (server)       | Debian
| OS version (client)       | Stretch
| PHP version               | 7.0
| MISP version / git hash   | 0f8bc5aea1f572db2dd3e4d5a04a8029c311a3ef
| Browser                   | Chrome

Actually just a question....as misp-backup.sh is getting worked on, what's the proper method to do a backup and restore of an misp instance?  Thank you.

**Comment by DigiAngel** [comment]
Any takers on this?  I need to redo a box and this is the only thing standing in my way..thank you!

**Comment by adulau** [comment]
The misp-backup.sh script should be ok. The important things to backup are the following:

- The dump of the database
- The associated samples of the files (which are outside the database)
- and the config files

**Comment by DigiAngel** [comment]
Thank you.  Sadly not in my case...it looks like the misp-backup.sh script needs some help after the latest update: [https://github.com/MISP/MISP/issues/3984](url)

**Comment by SteveClement** [comment]
closing and focusing on #3984

**Comment by DigiAngel** [comment]
That's appropriate..thank you!
