### ISSUE TITLE
Invalid username or password & Error: An Internal Error Has Occurred - local instance login 

### ISSUE THREAD

**Issue by briglewis** [MISP/MISP#4034]
Hi all,

Using Kali, still can't login - now I get a different error - this is my first login so I'm assuming I use the default creds:

MISP Installed, access here: https://misp.local
https://misp.local/users/login
User: admin@admin.test
Password: admin

I get to the login screen - enter the above and it throws user cred error and internal error - the error log is blank.

![internal_error](https://user-images.githubusercontent.com/19641210/51503075-2aaf3d80-1e2d-11e9-88ec-84428fc979d4.PNG)

**Comment by SteveClement** [comment]
This has been fixed upstream.

If you have a permanent install of Kali try to run the installer again.
