### ISSUE TITLE
MISP Interface blank - redis installed despite error - still blank screen

### ISSUE THREAD

**Issue by briglewis** [MISP/MISP#4035]
![php redis already installed](https://user-images.githubusercontent.com/19641210/51508188-568bec80-1e48-11e9-8784-d62f71542d73.PNG)
Hi,

I started again with a fresh install of Kali and MISP.

Redis-Server is running on startup as is Apache2

redis.ini is in php7.3 which is the version that runs, I've enabled it but I still get the same error:

`[Tue Jan 22 11:46:24.809371 2019] [php7:error] [pid 1109] [client 127.0.0.1:47716] PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/MISP/app/Lib/Tools/PubSubTool.php:34\nStack trace:\n#0 /var/www/MISP/app/Model/AppModel.php(1508): PubSubTool->initTool()\n#1 /var/www/MISP/app/Model/AppModel.php(1499): AppModel->loadPubSubTool()\n#2 /var/www/MISP/app/Model/Log.php(260): AppModel->getPubSubTool()\n#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)\n#7 /var/www/MISP/app/Model/AppModel.php(1136): Model->save(Array)\n#8 /var/www/MISP/app/Model/AppModel.php(172): AppModel->updateDatabase(13)\n#9 /var/www/MISP/app/Model/AppModel.php(1333): AppModel->updateMISP(13)\n#10 /var/www/MISP/app/Controller/AppController.php(294): AppModel->runUpdates()\n#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeE in /var/www/MISP/app/Lib/Tools/PubSubTool.php on line 34

-

I can access Viper and the live Dashboard. 

Thanks.

**Comment by SteveClement** [comment]
Dear

Thanks for the report.

I have indeed the same issue.

Will investigate.

**Comment by SteveClement** [comment]
Ok, the quick fix is:

```bash
sudo a2dismod php7.2
sudo a2enmod php7.3
systemctl restart apache2
```

But I had another issue with redis-server not being up...

Let me know if the above got you a little further.

**Comment by briglewis** [comment]
Hi Steve,

php7.3 is already enabled.

**Comment by briglewis** [comment]
Now I get a user blackholed error after attempting to login and it says: The requested address '/users/login' was not found on this server. I've refreshed and cleared my cache but the error still persists. 

The error log says: AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?).

Thanks - a colleague also tried to install it and he got a blank screen too after trying to login but it returned a Viper auth table error so different thing again I think.

**Comment by SteveClement** [comment]
Ok, I see.

Let me debug this today a little more and get back to you.

**Comment by briglewis** [comment]
Thanks - appreciate it Steve.

**Comment by SteveClement** [comment]
On a fresh Kali boot it should work now.

**Comment by briglewis** [comment]
Hurrah! Thanks!
