### ISSUE TITLE
Manual Import error of MISP json file

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#4036]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 9
| OS version (client)       | Windows 10
| PHP version               | 7.0
| MISP version / git hash   | v2.4.101 (cb41b4db38a06fde0fc6c4d80e937b1599da3842) 
| Browser                   | Chrome

### Actual behavior

Home --> "Import From" --> "MISP standard (recommended exchange format - lossless)"

When upload a MISP JSON file the following error occour (I've added debug option 1 to get more info:
```
The request has been black-holed
Error: The requested address '/events/add_misp_export' was not found on this server.

Stack Trace
APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 831 → AppController->blackhole(string)
APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 351 → SecurityComponent->_callback(EventsController, string, array)
APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php line 255 → SecurityComponent->blackHole(EventsController, string, SecurityException)
APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php line 128 → SecurityComponent->startup(EventsController)
APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 243 → ObjectCollection->trigger(string)
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

### Steps to reproduce the behavior
I've previously used the below sample MISP JSON file that can be downloaded from here:
http://evilcorp.dk/files/misp.php

**Comment by adulau** [comment]
I tried to import the MISP json file downloaded from your URL and I was successfully importing the event in MISP instance with the latest HEAD.

![imported](https://user-images.githubusercontent.com/3309/51800233-967a1780-222c-11e9-8ea3-8294951a0ce3.png)

Could you try with the latest version? Thanks a lot.

**Comment by eCrimeLabs** [comment]
I can confirm that after updating to v2.4.101 (be88ddc16d55013651c1e11635b1062bea9a487a)  I can't replicate the error any more. So should closed

**Comment by adulau** [comment]
Thanks for the quick feedback!
