### ISSUE TITLE
Install MISP by Docker on Redhat7.5

### ISSUE THREAD

**Issue by TuLeox7Cb** [MISP/MISP#4039]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

When i tried to install docker with command:  docker-compose -f docker-compose-nginx.yml build.
Have a error occur:
![nh](https://user-images.githubusercontent.com/44956276/51582030-f1de9980-1efc-11e9-8add-151705ce3b9f.png)

i don't do anything for this issue

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | RedHat, ...
| OS version (client)       | 
| PHP version               |  7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by adulau** [comment]
For docker related issues, could you an open issue in the corresponding repository depending of your docker. Such as https://github.com/MISP/docker-misp or https://github.com/MISP/misp-docker Thank you!
