### ISSUE TITLE
Allow to specify list of tokens in url

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#404]
Allow to specify a list of tokens of URLs that all need to be present to match.
In some cases, the domain is random/unique, same thing for the path and the script name, but not for the parameters.

This will need #27 to be implemented

The idea is to cover a case such as this from (operation [Arid Viper](http://www.trendmicro.com/cloud-content/us/pdfs/security-intelligence/white-papers/wp-operation-arid-viper.pdf)):

```
/new/all_file_info1.php?name=[SYSTEMID]&user=[NUM]&file=[DD-MM-YYYY HH-MM.uml]&type=msn
/new/all_file_info1.php?name=[SYSTEMID]&user=[NUM]&file=[DD-MM-YYYY HH-MM.rml]&type=log
/new/all_file_info1.php?name=[SYSTEMID]&user=[NUM]&file=[DD-MM-YYYY HH-MM.dll]&type=img
/new/all_file_info1.php?name=[SYSTEMID]&user=[NUM]&file=[DD-MM-YYYY HH-MM.rml]&type=tree
```

Which would result in a composition of attributes such as:
(**url contains** = /new/all_file_info1.php) AND (**url contains** name=) AND (**url contains** &file=) AND (**url contains** &type=) AND ( (**url contains** &type=msn ) OR (**url contains** &type=log ) OR (**url contains** &type=img ) OR (**url contains** &type=tree ) )

This can be specially useful if a generator of Network IDS rules can use those composition of attributes to generate a rule matching the different parts.

**Comment by iglocska** [comment]
Attribute compositions is planned for the datamodel overhaul in the version
following the upcoming one. The idea is to be close to what STIX/CyBox
allows for. The above mentioned example should be absolutely possible with
that!

**Comment by elhoim** [comment]
Depends on #27

**Comment by adulau** [comment]
Relations can now describe a kind of boolean relationship between objects and objects/attributes.

https://github.com/MISP/misp-objects/blob/master/relationships/definition.json

Can you review it to see if this solve your url example?

**Comment by adulau** [comment]
I'll close this issue. Feel free to reopen if this doesn't solve your issue or feel free to contribute an update in the relationship.
