### ISSUE TITLE
Issue installing misp_modules when following guide.

### ISSUE THREAD

**Issue by jwilczek** [MISP/MISP#4045]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       |  ubuntu
| OS version (client)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4
| Browser                   | If applicable

### Expected behavior
Installation of misp_modules

### Actual behavior
Getting an error when trying to install the modules

```
sudo -H -u www-data ${PATH_TO_MISP}/venv/bin/pip install -I -r REQUIREMENTS
Obtaining file:///usr/local/src/misp-modules (from -r REQUIREMENTS (line 2))
    Complete output from command python setup.py egg_info:
    running egg_info
    creating misp_modules.egg-info
    error: could not create 'misp_modules.egg-info': Permission denied
    
Command "python setup.py egg_info" failed with error code 1 in /usr/local/src/misp-modules/
```

### Steps to reproduce the behavior
Following guide https://misp.github.io/MISP/INSTALL.ubuntu1804/

### Logs, screenshots, configuration dump, ...

**Comment by adulau** [comment]
``` Permission denied``` It seems you did an installation previously with different permission (as root?) instead of the user executed (www-data). A `chmod -R www-data:www-data` on where misp-modules are installed would do the job. I hope this helps.

**Comment by jwilczek** [comment]
I was able to solve the issue. I should have been more clear. My point was that the install guide has you chown as `root:staff`. And this incompatible with the subsequent call as www-data.

`sudo -H -u www-data ${PATH_TO_MISP}/venv/bin/pip install -I -r REQUIREMENTS`

I think the install guide is wrong. Am I missing something?

**Comment by cowbe0x004** [comment]
Had the same issue with both ubuntu and debian guides, both failed to install REQUIREMENTS. So I did this instead,
sudo chown www-data:www-data /usr/local/src

**Comment by jwilczek** [comment]
Correct, I understand the issue and was able to get around it. My point was I think the install guide is incorrect.

**Comment by davehouser1** [comment]
Had the same problem as well. The install guide needs to be updated. 
More importantly INSTALL.sh -u, appears to exhibit the same problem.
This really needs to be reopened, and the guide needs to be fixed.

From This:
```
sudo apt-get install python3-dev python3-pip libpq5 libjpeg-dev tesseract-ocr libpoppler-cpp-dev imagemagick virtualenv libopencv-dev zbar-tools libzbar0 libzbar-dev libfuzzy-dev build-essential -y
sudo -u www-data virtualenv -p python3 /var/www/MISP/venv
cd /usr/local/src/
chown -R www-data .
sudo git clone https://github.com/MISP/misp-modules.git
cd misp-modules
sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
```

Needs to change to this:
```
sudo apt-get install python3-dev python3-pip libpq5 libjpeg-dev tesseract-ocr libpoppler-cpp-dev imagemagick virtualenv libopencv-dev zbar-tools libzbar0 libzbar-dev libfuzzy-dev build-essential -y
sudo -u www-data virtualenv -p python3 /var/www/MISP/venv
cd /usr/local/src/
sudo git clone https://github.com/MISP/misp-modules.git
sudo chown -R www-data: .
cd misp-modules
sudo -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
```

**Comment by webwolf3000** [comment]
Still not fixed; above solution seems to work!
