### ISSUE TITLE
tag/download automation URL: why this error and tag special chars

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4051]
2.4.100

2 questions re' specifying tags in a `text/download` automation URL:

1. i read that any colon (`:`) in a tag should be replaced with a semicolon (`;`). however, what about other special chars, e.g. `=` or double-quotes (`"`), etc.?
 * in https://github.com/MISP/MISP/issues/3325 i see the recommendation to use `HTTP POST` with a `JSON` body -- does this mean that this can not be done via `HTTP GET`, i.e. need to use `POST` which would require an `HTML form` or use of `curl`, `python`, etc.?
 * we were attempting to offer URLs to share with users to bookmark that perform standard queries based on our use cases.
2. why does the following URL:
```
https://localhost/attributes/text/download/url/foo/null/null/2019-01-04/2019-01-04
```
throw this exception in the `error.log`:
```
2019-01-24 21:08:52 Error: [ArgumentCountError] Too few arguments to function Attribute::set_filter_tags(), 2 passed in /var/www/MISP/app/Model/Attribute.php on line 2212 and exactly 3 expected
Request URL: /attributes/text/download/url/foo/null/null/2019-01-04/2019-01-04
Stack Trace:
#0 /var/www/MISP/app/Model/Attribute.php(2212): Attribute->set_filter_tags(NULL, Array)
#1 /var/www/MISP/app/Controller/AttributesController.php(1998): Attribute->text(Array, 'url', 'foo', false, false, '2019-01-04', '2019-01-04', false, false, false)
#2 [internal function]: AttributesController->text('download', 'url', 'foo', false, false, '2019-01-04', '2019-01-04')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
```

**Comment by github-germ** [comment]
disclaimer: i don't know php (yet), so i am taking a risk here, but in looking at the `error.log`:
```
Too few arguments to function Attribute::set_filter_tags(), 2 passed in /var/www/MISP/app/Model/Attribute.php on line 2212 and exactly 3 expected
```
i'm wondering if this part of the code might have 2 issues (snippet starts on line 2208 in `Attributes.php`):
```
	if ($eventId !== false) {
            $conditions['AND'][] = array('Event.id' => $eventId);
        } elseif ($tags !== false) {
            $passed_param = array('tags' => $tags);
            $conditions = $this->set_filter_tags($passed_params, $conditions);
        }
```

on the line:
```
$conditions = $this->set_filter_tags($passed_params, $conditions);
```
1. should that be `$passed_param` (no trailing `s`)?
2. does the function `set_filter_tags` need 3 args with the third expecting `$options`?

**Comment by iglocska** [comment]
Pushed a fix, but this is a deprecated function that should not be used any
longer in the first place for a while now. Please use the restSearch API.

**Comment by github-germ** [comment]
Thx for the fix! (https://github.com/MISP/MISP/commit/c38d553192d5f0394ec676c50e2d200a6ae0b891)

Yes, we realize this method was deprecated (although I don't see the word `deprecated` on https://localhost/events/automation :-)

However, we are looking for a method to share a URL with users that allows them to perform a query producing results based on a in-house standard set of use cases. Query Builder is way cool, but doesn't offer a simple "hey, bookmark this URL, and run it as needed during your threat analysis", for example (i.e. no way to save a template currently).

Is there some way to accomplish this other than sharing a `curl` command or `PyMISP` code?

Thanks.

**Comment by iglocska** [comment]
Pretty much all of the attributes for restsearch can also be passed as named url parameters. For example:

`https://path.to.my.server/attributes/restSearch/returnFormat:text/publish_timestamp:24h/tags:!tlp:red/type:ip-src`

**Comment by iglocska** [comment]
actually what I listed above wouldn't work because of the tlp:red (it would break the key:value format)... You can still use the tag ID-s though in that case IIRC

**Comment by github-germ** [comment]
That might do the trick!!
Is that method documented somewhere so I can share that within my team?

**Comment by github-germ** [comment]
duh, documented on automation page. thx...

**Comment by iglocska** [comment]
I was wrong about the returnFormat:text part, but it should work that way now. Added the description to the automation page below the rest of the restSearch description, just git pull and have a look.
