### ISSUE TITLE
Data Cleanup

### ISSUE THREAD

**Issue by gitnorty** [MISP/MISP#4055]
Is there a recommended way to cleanup the data stored within MISP?  To get rid of duplicates, old data, etc...  Thus far I haven't come across anything when searching.

I've found the 'Orphaned Attribute' tool; but if I understand correctly, this only addresses the content that isn't stored in the DB, but is save as files.

In case 'https://github.com/MISP/MISP/issues/2800' I see iglocska mentioned, "delete events that are duplicate feed pulls via the UI "; but I don't see where to do this.

Thanks.

**Comment by iglocska** [comment]
There's no automated way of doing it, I can add a tool for it but it will never be 100% bullet proof. The problem is this, each feed has a name, this name will be used in the event info of the events. We could have a script that collects all of those events and proposes to delete them, but if you add custom feeds with your own naming conventions or someone creates an event with a matching event info, you might end up accidentally removing legitimate non feed events.

**Comment by gitnorty** [comment]
Thank you for the feedback iglocska!  Based on this, sounds like it would be best to create an tool locally since we know exactly what has been ingested, what feeds we have, and what not.

**Comment by iglocska** [comment]
Ah if you know indeed. Basically just do a search for all events that match your criteria, loop through it and send an event delete command for each ID to MISP. Let us know if you guys get stuck!

**Comment by gitnorty** [comment]
If we want to wipe the DB but leave the user, role, organization, feeds, etc... intact do you have any preferred method you'd recommend?  If we use the script as suggested, it will take about 20 hours for about 24K events.  I saw the /var/www/MISP/tools/misp-wipe; but this appears to wipe everything.  I can surmise how to tweak it to keep the content above; but wasn't clear if anything else needed to be maintained if we just wanted to wipe the events and related attributes, but keep everything else as configured.

**Comment by iglocska** [comment]
20 hours? Did you truncate the correlations table first? That sounds like an awful lot.

Alternatively what you can do (but keep in mind this is rather dirty) is to truncate the following tables:


attribute_tags
attributes
correlations
event_delegations
event_graph
event_locks
event_tags
events
fuzzy_correlate_ssdeep
objects
object_references
posts
shadow_attribute_correlations
shadow_attributes
sightings
threads

That should cover everything - but again, it's not very clean (you'l for example have some oddities in regards to log entries pointing to elements that don't exist anymore, or once you reach the same ID pointing to elements that have been at that ID before).

Perhaps if you want to go down this route, also consider not truncating the tables but just deleting all elements, persisting the current ID pointers.

**Comment by gitnorty** [comment]
Thank you for the additional feedback.  No, we didn't truncate the correlations table first.  So if we delete the elements, this would be something like:

delete from events; 

or the various tables you mentioned above?  So if I understand correctly; all the current metadata is maintained, so all new entries will be started from where the counters were left off rather than afresh?

Thanks again for all your help!

**Comment by iglocska** [comment]
yeah if you run delete from events; and delete from [all other tables I've listed] You should end up with a clean MISP with the IDs maintained.

However, if you want to give the script route another chance, that is of course preferred. I'd just truncate the correlation table first, then disable correlations globally in MISP (in the server settings) - then execute the script that deletes the unwanted events. It should go MUCH faster after having the correlation table truncated.

**Comment by gitnorty** [comment]
Thanks for the follow-up details!  Good to have multiple methods to address issues.  FYI... deleting the correlations definitely speeds the cleanup process up.

**Comment by gitnorty** [comment]
One other thing we ran into, when running the cleanup via the delete scripts using PyMISP; it doesn't appear to cleanup the 'attributes' and 'attribute_tags' tables?  Can you shed some light if we are missing something or there may be some other issue here?  Thanks in advanced!

**Comment by iglocska** [comment]
What the hell. It should. Can you share your script so we can test it?

**Comment by github-germ** [comment]
> What the hell. It should. Can you share your script so we can test it?

See 
https://github.com/MISP/PyMISP/issues/327#issuecomment-458963474
