### ISSUE TITLE
tag/download automation URL:  Does not work correctly.

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#4056]
This issue is a continuation on the "tag/download automation URL: why this error and tag special chars #4051" issue.

I've been following the post mentioned above because I have a user set that could really use this function to do simple data extraction.  I've been trying to follow your example above and reading the "Automation" section of your documentation, but I can't seem to get things to work correctly.

My requirement is to use a simple restSearch URL command string and get back a list of ip-src, ip-dest, url or domain data.  This data needs to be filtered by specific dates, (to: and from:), and also some tags.  No matter how I try to configure the URL string, the result is the same huge amount of data returned in a json format.  It's as if none of the filters are working.  

An example of what I've done is below;
**`https://<MISP Host>/attributes/restSearch/returnFormat:csv/type:ip-dst/from:2019-01-04/to:2019-01-04/requested_attributes:ip-dst`**

I would like to see a list returned like this;
1.2.3.4
1.2.4.5

I get back: {"response": {"Attribute": [{"id":"2971481","event_id":"34082","object_id".......

 iglocska, you were giving a lot of help on issue 4051, can you help on this?

**Comment by iglocska** [comment]
Before I go further into it: URL parameters in general are discouraged so for anyone finding this issue: Use POST requests whenever possible.

It looks like returnFormat via the URL parameters was not ingested correctly, however there's a different syntax to pass it (/attriubtes/restSearch/csv/...) that works. I've pushed a patch so you should be able to use /returnFormat:csv/ once you update, or use the format above with the current version.

Further, you have two options, one is to indeed use the CSV format and select the value field, for that you need to change the query to this: 

`https://<MISP Host>/attributes/restSearch/csv/type:ip-dst/from:2019-01-04/to:2019-01-04/requested_attributes:value`

Or alternatively we have a flat value text export format that just grabs the values:

`https://<MISP Host>/attributes/restSearch/text/type:ip-dst/from:2019-01-04/to:2019-01-04`

Furthermore, you mentioned 4 different types that you would like returned. I've pushed some fixes to allow multiple values to be added to a list similar to POSTed JSON objects: This is possible by passing the parameter like this: 

`https://<MISP Host>/attributes/restSearch/text/type:ip-dst||domain||ip-src||url/from:2019-01-04/to:2019-01-04`

You also mentioned tags, you could further refine it with these: 

`https://<MISP Host>/attributes/restSearch/text/type:ip-dst||domain||ip-src||url/from:2019-01-04/to:2019-01-04/tags:!tlp:red||!tlp:amber||tlp:green||tlp:white`

For the from/to filters, keep in mind, these will use the date field of an event. Generally it's more useful to search for example for the publish timestamp (which can be a range between start_date_timestamp and end_date_timestamp as described below):

`https://<MISP Host>/attributes/restSearch/text/type:ip-dst||domain||ip-src||url/publish-timestamp:1546560000||1546646399/tags:!tlp:red||!tlp:amber||tlp:green||tlp:white`

If you just want to grab data between what happened 2 weeks ago and a week ago you could also do this:

`https://<MISP Host>/attributes/restSearch/text/type:ip-dst||domain||ip-src||url/publish-timestamp:14d||7d/tags:!tlp:red||!tlp:amber||tlp:green||tlp:white`

Hope this helps.
