### ISSUE TITLE
sighting example

### ISSUE THREAD

**Issue by jochman** [MISP/MISP#4057]
There is no example for `/sightings/add/` in the API docs (also for PYMISP). I'm getting only:
```
{
    "name": "Could not add Sighting",
    "message": "Could not add Sighting",
    "url": "\/sighting\/add",
    "errors": "No valid attributes found."
}
```

after trying multiple combinations including `type`, `value`, `sighting`, `id`. 

From the documentation I can only understand how to pass `attribute_id` or `attribute_uuid`.

Can I have an example for this post request?

**Comment by mokaddem** [comment]
Hello,
Have you tried to REST client query builder?
It can help you create queries and also provide a bit of additional documentation about API fields.
For example:

- Adding a sighting to a specific Attribute id
```
Endpoint: /sightings/add
Body:
{
    "id": 17
}
```
- Adding a sighting to all attribute having a value the value ``val1`` or ``val2``:
```
Body:
{
    "values": [
        "val1",
        "val2"
    ]
}
```

I hope that helps
