### ISSUE TITLE
Sighting an attribute destroys the order

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#4059]
1. Search for an attribute, e.g. 1AqbY9v2oFADgdH9A7dGPdGcT42F4dd2ak
2. click on the event
3. Ctrl-f 1AqbY9v2oFADgdH9A7dGPdGcT42F4dd2ak
4. sight
5. see the attribute 1AqbY9v2oFADgdH9A7dGPdGcT42F4dd2ak disappear

optional: 6. reload and the order is back fine.

**Comment by iglocska** [comment]
Should be fixed now.
