### ISSUE TITLE
Getting "An Internal Error Has Occurred." when trying to reach the MISP Web UI.

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#4060]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.100
| Browser                   | Chrome

### Expected behavior
A functioning webserver

### Actual behavior
Webpage loads, with "An Internal Error Has Occurred." on the page. Nothing else works

### Steps to reproduce the behavior
Apache with certificate works, no errors there.

### Logs, screenshots, configuration dump, ...
The error.log file in /var/www/MISP/app/tmp/logs isn't very descriptive. It gives the following error:
2019-01-28 15:47:58 Error: [ParseError] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

Looking at the debug.log file, a lot of "undefined variable" errors appear:
2019-01-28 16:04:44 Notice: Notice (8): Undefined variable: me in [/var/www/MISP/app/View/Layouts/default.ctp, line 109]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 109
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

2019-01-28 16:04:44 Notice: Notice (8): Undefined variable: baseurl in [/var/www/MISP/app/View/Layouts/default.ctp, line 100]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Layouts/default.ctp, line 100
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 963
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 292
ExceptionRenderer::error500() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 260
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 190
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

**Comment by iglocska** [comment]
That looks like a broken AppController file - could you pull the latest version and see if it works? Really weird.

**Comment by mik5z** [comment]
> That looks like a broken AppController file - could you pull the latest version and see if it works? Really weird.

How would I do that? I'll try right away and tell you if it worked

**Comment by AdrianCUCU** [comment]
I get the same error after a fresh install on ubuntu server, only that I can enter the page but welcomes me with this error "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)". If i try to do so it goes on with issue above "an internal error has ocured"

**Comment by saeeda12** [comment]
I am getting the same error - the "Internal Error Has Occurred" on my CentOS 7 server when I browse to my misp instance, with the below errors from the error.log. Don't have SSL (just trying to stand up test instance) and I generated the GPG encryption key.

```
Error: [ParseError] syntax error, unexpected '=', expecting function (T_FUNCTION) or const (T_CONST)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by iglocska** [comment]
It sounds like 3 different issues. I would need the stack trace to see what's going wrong in the other cases, @saeeda12 - it sounds like you have a misconfigured database.php file (/var/www/MISP/app/Config/database.php) - could you paste that here so we could have a look? (Make sure you redact your password and all internal info though please).

For everyone else: /var/www/MISP/app/tmp/logs/error.log will have the stack trace that I need to be able to help.

**Comment by mik5z** [comment]
> It sounds like 3 different issues. I would need the stack trace to see what's going wrong in the other cases, @saeeda12 - it sounds like you have a misconfigured database.php file (/var/www/MISP/app/Config/database.php) - could you paste that here so we could have a look? (Make sure you redact your password and all internal info though please).
> 
> For everyone else: /var/www/MISP/app/tmp/logs/error.log will have the stack trace that I need to be able to help.

2019-01-28 16:39:56 Error: [ParseError] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
#1 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

**Comment by SteveClement** [comment]
@mikemaassen is this a fresh install?

If it is you probably skipped one or the other step.

If you followed the official docu, this will update your MISP from the command line:

```bash
cd /var/www/MISP
sudo -H -u www-data git pull
sudo -H -u www-data git submodule update
```

In case this fails, your permissions might be wrong.

Out of interest, what does:

```bash
sudo -H -u www-data git status
```

tell you?

**Comment by SteveClement** [comment]
> I get the same error after a fresh install on ubuntu server, only that I can enter the page but welcomes me with this error "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)". If i try to do so it goes on with issue above "an internal error has ocured"

@AdrianCUCU Please open a new issue with the exact stack trace from your error log.
If both issues overlap we shall x-reference.

**Comment by SteveClement** [comment]
> > It sounds like 3 different issues. I would need the stack trace to see what's going wrong in the other cases, @saeeda12 - it sounds like you have a misconfigured database.php file (/var/www/MISP/app/Config/database.php) - could you paste that here so we could have a look? (Make sure you redact your password and all internal info though please).
> > For everyone else: /var/www/MISP/app/tmp/logs/error.log will have the stack trace that I need to be able to help.
> 
> 2019-01-28 16:39:56 Error: [ParseError] syntax error, unexpected '' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST)
> Request URL: /
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(83): ConnectionManager::_init()
> #1 /var/www/MISP/app/Controller/AppController.php(110): ConnectionManager::getDataSource('default')
> #2 /var/www/MISP/app/Controller/EventsController.php(34): AppController->beforeFilter()
> #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
> #7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #8 {main}

@mikemaassen double check your database configuration file, that might be it.

**Comment by mik5z** [comment]
Pulling the MISP folder again came back "already up to date."

git status:
On branch 2.4
Your branch is ahead of 'origin/2.4' by 3 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   PyMISP (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        INSTALL/dump.rdb
        app/Config/config.php.old
        app/files/scripts/python-maec/
        app/packages.json
        app/resolv.conf1
        venv/

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by mik5z** [comment]
> @mikemaassen double check your database configuration file, that might be it.

Which database file would that be? I can paste parts of the configuration if that helps.

**Comment by iglocska** [comment]
`/var/www/MISP/app/Config/database.php`

**Comment by mik5z** [comment]
> `/var/www/MISP/app/Config/database.php`

The database configuration looks fine: 

<?php
class DATABASE_CONFIG {
        public \$default = array(
                'datasource' => 'Database/Mysql',
                //'datasource' => 'Database/Postgres',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'misp',
                'port' => 3306, // MySQL & MariaDB
                //'port' => 5432, // PostgreSQL
                'password' => 'my password',
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}

**Comment by iglocska** [comment]
If you run this:

mysql -u misp -p misp

and then enter the password in the 'my password' string, can you log into the mysql console?

**Comment by mik5z** [comment]
> If you run this:
> 
> mysql -u misp -p misp
> 
> and then enter the password in the 'my password' string, can you log into the mysql console?

Yes

**Comment by iglocska** [comment]
Hmph. If you run `show tables;` what's the output

**Comment by mik5z** [comment]
+-------------------------------+
| admin_settings                |
| attribute_tags                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_blacklists              |
| event_delegations             |
| event_locks                   |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| fuzzy_correlate_ssdeep        |
| galaxies                      |
| galaxy_clusters               |
| galaxy_elements               |
| galaxy_reference              |
| jobs                          |
| logs                          |
| news                          |
| noticelist_entries            |
| noticelists                   |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| org_blacklists                |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightings                     |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| whitelist                     |
+-------------------------------+

**Comment by iglocska** [comment]
Wait what is this?

`Your branch is ahead of 'origin/2.4' by 3 commits.`

**Comment by iglocska** [comment]
Do you know what those 3 commits were? Mind getting rid of them?

**Comment by iglocska** [comment]
You can simply align your local repo with the remote this way:

`git reset --hard origin/2.4`

**Comment by mik5z** [comment]
Done, 

git status
On branch 2.4
Your branch is up to date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   PyMISP (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        INSTALL/dump.rdb
        app/Config/config.php.old
        app/files/scripts/python-maec/
        app/packages.json
        app/resolv.conf1
        venv/

**Comment by iglocska** [comment]
Perfect, any changes?

**Comment by iglocska** [comment]
Also something else, trying to re-read all the messages. The database.php file seems to be truncated, just to make sure, it's only a copy-paste issue right? 

`'Database/Mysql', //'datasource' => 'Database/Postgres', 'persistent' => false, 'host' => 'localhost', 'login' => 'misp', 'port' => 3306, // MySQL & MariaDB //'port' => 5432, // PostgreSQL 'password' => 'my password', 'database' => 'misp', 'prefix' => '', 'encoding' => 'utf8', ); }`

Should be: 
```
<?php
// Loads of comments
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => 'my password',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
	);
}

```

**Comment by mik5z** [comment]
No change sadly. Opening the web UI comes up with this in the body:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

**Comment by mik5z** [comment]
> Also something else, trying to re-read all the messages. The database.php file seems to be truncated, just to make sure, it's only a copy-paste issue right?
> 
> `'Database/Mysql', //'datasource' => 'Database/Postgres', 'persistent' => false, 'host' => 'localhost', 'login' => 'misp', 'port' => 3306, // MySQL & MariaDB //'port' => 5432, // PostgreSQL 'password' => 'my password', 'database' => 'misp', 'prefix' => '', 'encoding' => 'utf8', ); }`
> 
> Should be:
> 
> ```
> <?php
> // Loads of comments
> class DATABASE_CONFIG {
> 
> 	public $default = array(
> 		'datasource' => 'Database/Mysql',
> 		//'datasource' => 'Database/Postgres',
> 		'persistent' => false,
> 		'host' => 'localhost',
> 		'login' => 'misp',
> 		'port' => 3306, // MySQL & MariaDB
> 		//'port' => 5432, // PostgreSQL
> 		'password' => 'my password',
> 		'database' => 'misp',
> 		'prefix' => '',
> 		'encoding' => 'utf8',
> 	);
> }
> ```

Correct, couldn't get that right on Github. Apologies.

**Comment by iglocska** [comment]
OK, I'm a bit stumped but let's try something that's a bit of a long shot. Could you change the password in your database.php to 'Password1234' ? I don't expect it to work but expecting a different error message (my hunch: your password contains a `\` and php interprets it as a character escape)

**Comment by mik5z** [comment]
> OK, I'm a bit stumped but let's try something that's a bit of a long shot. Could you change the password in your database.php to 'Password1234' ? I don't expect it to work but expecting a different error message (my hunch: your password contains a `\` and php interprets it as a character escape)

I tried that, but that's not the case.

**Comment by iglocska** [comment]
It sounds like it's having an issue parsing the database.php file, not sure what is going wrong there really. Any chance you could send me the file as is to andras.iklody@circl.lu ? My pgp key should be available here: https://pgp.circl.lu/pks/lookup?op=get&fingerprint=on&search=0xBEA224F1FEF113AC

**Comment by mik5z** [comment]
What I have noticed when looking back at my installation steps, is that I was unable to perform the following command: 
`sudo -H -u www-data pear install ${PATH_TO_MISP}/INSTALL/dependencies/Console_CommandLine/package.xml`

It comes back with the error 
`Cannot install, php_dir for channel "pear.php.net" is not writeable by the current user`

Would that be relatable to my problems?

Executing the following command also gave errors:
`for key in upload_max_filesize post_max_size max_execution_time max_input_time memory_limit
do
    sudo sed -i "s/^\($key\).*/\1 = $(eval echo \${$key})/" $PHP_INI
done`

This came back with:
sed: no input files
sed: no input files
sed: no input files
sed: no input files
sed: no input files

**Comment by saeeda12** [comment]
@iglocska Here is my output of database.php

```cat database.php
<?php
class DATABASE_CONFIG {
        public  = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => '[login]',
                'port' => 3306,
                'password' => '[password]',
                'database' => '[db_name]',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}
```

Also tried the `git status` command which returned that I'm On branch 2.4 and changes not staged for commit.

Also tried logging into the mysql database as user misp and got in but when I tried `show tables;` it said:
```
MariaDB [(none)]> show tables;
ERROR 1046 (3D000): No database selected
```

When I tried the `use mysql;` command, I got an access denied for user misp to database mysql. Guessing this is an or the issue - any idea how to change permissions? Although I already did grant all privileges to the user as part of the installation process (https://github.com/MISP/MISP/blob/2.4/docs/xINSTALL.centos7.md). 

When I tried logging in with the admin account, I was able to go into the mysql database and run the command, which  returned 24 tables.

**Comment by iglocska** [comment]
The database name should be what you have redacted as [db_name]. So simply `use db_name` from the mariadb console or start it this way in the first place:

`mysql -u misp -p db_name` Where db_name is your chosen db_name.

**Comment by saeeda12** [comment]
Aha, here is my output of the `show tables;` command:
```
+-------------------------------+
| admin_settings                |
| attribute_tags                |
| attributes                    |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| event_blacklists              |
| event_delegations             |
| event_locks                   |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| fuzzy_correlate_ssdeep        |
| galaxies                      |
| galaxy_clusters               |
| galaxy_elements               |
| galaxy_reference              |
| jobs                          |
| logs                          |
| news                          |
| noticelist_entries            |
| noticelists                   |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| org_blacklists                |
| organisations                 |
| posts                         |
| regexp                        |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightings                     |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| whitelist                     |
+-------------------------------+
58 rows in set (0.00 sec)
```

**Comment by saeeda12** [comment]
I ran another `sudo -H git status` and this time got that my "branch is behind 'origin/2.4' by 453 commits, and can be fast-forwarded."

I didn't include the `-u www-data` in the command because it returned unknown user. (I'm on CentOS 7, so used `-u apache`).

So I ran `sudo -H git pull`, and it looks like it's working until Line 18:
```
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 19 (delta 15), reused 14 (delta 11), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/MISP/MISP
   d9608d2..b45eb09  2.4        -> origin/2.4
Fetching submodule cti-python-stix2
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 109 (delta 98), reused 109 (delta 98), pack-reused 0
Receiving objects: 100% (109/109), 17.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (98/98), completed with 32 local objects.
From https://github.com/oasis-open/cti-python-stix2
   29a4e2f..3912df2  master     -> origin/master
Updating ff0b81e..b45eb09
error: Your local changes to the following files would be overwritten by merge:
        .gitmodules
        .travis.yml
        INSTALL/INSTALL.kali.txt
        INSTALL/MYSQL.sql
        INSTALL/POSTGRESQL-data-initial.sql
        INSTALL/POSTGRESQL-structure.sql
        INSTALL/apache.24.misp.ssl
        INSTALL/apache.misp.centos7
        INSTALL/apache.misp.ubuntu
        VERSION.json
        app/Console/Command/AdminShell.php
        app/Console/Command/EventShell.php
        app/Console/Command/Populate023Shell.php
        app/Console/Command/ServerShell.php
        app/Console/Command/Task/RoleIdTask.php
        app/Console/Command/Task/RoleToAroAcoTask.php
        app/Console/Command/Task/RolesTask.php
        app/Console/Command/Task/UsersTask.php
        app/Console/Command/populate20Shell.php
        app/Controller/AttributesController.php
        app/Controller/Component/ACLComponent.php
        app/Controller/Component/RestResponseComponent.php
        app/Controller/EventsController.php
        app/Controller/FeedsController.php
        app/Controller/GalaxiesController.php
        app/Controller/GalaxyClustersController.php
        app/Controller/ObjectReferencesController.php
        app/Controller/ObjectTemplatesController.php
        app/Controller/OrganisationsController.php
        app/Controller/ServersController.php
        app/Controller/SightingsController.php
        app/Controller/TagsController.php
        app/Controller/TaxonomiesController.php
        app/Controller/UsersController.php
        app/Controller/WarninglistsController.php
        app/Lib/Export/BroExport.php
        app/Lib/Export/CacheExport.php
        app/Lib/Export/Stix1Export.php
        app/Lib/Export/Stix2Export.php
        app/Lib/Tools/ComplexTypeTool.php
        app/Locale/cze/LC_MESSAGES/default.po
        app/Locale/dan/LC_MESSAGES/default.po
        app/Locale/deu/LC_MESSAGES/default.po
        app/Locale/fra/LC_MESSAGES/default.po
        app/Locale/ita/LC_MESSAGES/default.po
        app/Locale/jpn/LC_MESSAGES/default.po
        app/Locale/kor/LC_MESSAGES/default.po
        app/Locale/pt_BR/LC_MESSAGES/default.po
        app/Locale/spa/LC_MESSAGES/default.po
        app/Model/AppModel.php
        app/Model/Attribute.php
        app/Model/AttributeTag.php
        app/Model/Feed.php
        app/Model/Galaxy.php
        app/Model/ObjectReference.php
        app/Model/Server.php
        app/Model/Sighting.php
        app/Model/Tag.php
        app/View/Attributes/add.ctp
        app/View/Attributes/ajax/attributeEditMassForm.ctp
        app/View/Attributes/ajax/attributeViewFieldForm.ctp
        app/View/Attributes/ajax/hover_enrichment.ctp
        app/View/Attributes/edit.ctp
        app/View/Attributes/index.ctp
        app/View/Elements/Events/View/row_attribute.ctp
        app/View/Elements/Events/View/sighting_field.ctp
        app/View/Elements/Events/eventIndexTable.ctp
        app/View/Elements/ajaxAttributeTags.ctp
        app/View/Elements/ajaxTags.ctp
        app/View/Elements/eventattribute.ctp
        app/View/Elements/eventdiscussion.ctp
        app/View/Elements/galaxyQuickView.ctp
        app/View/Elements/galaxyQuickViewMini.ctp
        app/View/Elements/global_menu.ctp
        app/View/Elements/side_menu.ctp
        app/View/Elements/sparkline.ctp
        app/View/Elements/view_mitre_attack_matrix.ctp
        app/View/Events/add.ctp
        app/View/Events/ajax/ajaxTags.ctp
        app/View/Events/ajax/eventPublishConfirmationForm.ctp
        app/View/Events/automation.ctp
        app/View/Events/json/index.ctp
        app/View/Events/view.ctp
        app/View/Events/view_mitre_attack_matrix.ctp
        app/View/Feeds/compare_feeds.ctp
        app/View/Feeds/index.ctp
        app/View/Feeds/preview_index.ctp
        app/View/Galaxies/ajax/cluster_choice.ctp
        app/View/Galaxies/ajax/galaxy_choice.ctp
        app/View/Galaxies/ajax/galaxy_namespace_choice.ctp
        app/View/GalaxyClusters/ajax/index.ctp
        app/View/Layouts/default.ctp
        app/View/Logs/admin_index.ctp
        app/View/ObjectReferences/ajax/add.ctp
        app/View/ObjectTemplates/ajax/object_choice.ctp
        app/View/Servers/add.ctp
        app/View/Servers/ajax/get_api_info.ctp
        app/View/Servers/edit.ctp
        app/View/Servers/index.ctp
        app/View/Servers/preview_index.ctp
        app/View/Servers/rest.ctp
        app/View/Sightings/ajax/quickAddConfirmationForm.ctp
        app/View/Tags/ajax/select_tag.ctp
        app/View/Tags/ajax/taxonomy_choice.ctp
        app/View/Tags/edit.ctp
        app/View/Tags/index.ctp
        app/View/Taxonomies/view.ctp
        app/composer.json
        app/files/feed-metadata/defaults.json
        app/files/scripts/misp2stix.py
        app/files/scripts/misp_framing.py
        app/files/scripts/stix2/misp2stix2.py
        app/files/scripts/stix2/misp2sti
Aborting
```

**Comment by iglocska** [comment]
Resolved via e-mail, database.php copy-paste fail. (For @saeeda12's issue)

**Comment by chandruHP** [comment]
hello,

I'm getting the same error "Error: An Internal Error Has Occurred." while assessing the site, this is a fresh installation. 

error.log

2020-04-22 03:54:21 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'misp\'@\'localhost\' (using password: YES)',
  'enabled' => true,



Can some one please help how to fix this. 

Thanks in advance.

**Comment by chandruHP** [comment]
also what would be the password for database login.?

Getting below for DB login. 


# mysql -u misp -p misp
Enter password:
ERROR 1045 (28000): Access denied for user 'misp'@'localhost' (using password: YES)
