### ISSUE TITLE
Warning: MISP is currently disabled for all users. 

### ISSUE THREAD

**Issue by AdrianCUCU** [MISP/MISP#4061]
After a fresh ubuntu server MISP install I can enter page but welcomes me with this error: "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)". If I try to reach Server Settings I get: "An Internal Error Has Occurred." Any other things seems to be working fine. Did anyone encountered/fixed this?

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by SteveClement** [comment]
If MISP is not live you did not run the Cake commands that activate your install.
Thus you missed some steps.

Closing this issue and continuing with #4060

**Comment by AdrianCUCU** [comment]
Hello and my apologies. I had no idea that you are so willing to help and that fast. I posted my problem where I found similar ones without giving much explanations.

my system is: ubuntu 18.04.1 LTS

This is the error that goes into the errorlog:

2019-01-28 17:43:53 Warning: Redis::srem(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php, line 538]

This is what's happening when I do a redis-cli:
root@misp-server:/var/www/MISP/app/tmp/logs# redis-cli
127.0.0.1:6379>

uvf status: 
root@misp-server:/var/www/MISP/app/tmp/logs# ufw status
Status: inactive

if you can give me ideas of what might be wrong it would be great.

P.S. I wasn't smart enough to install MISP by official ways so I took one of those "auto-MISP-ubuntu.sh" that you keep on site which I run it.

**Comment by AdrianCUCU** [comment]
I've rerun commands for cake. The error message when I enter page is gone, but if I try go to settings error persists. When running commands also got error below
Notice Error: Array to string conversion in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 909]

**Comment by AdrianCUCU** [comment]
and in addition - the galaxies are now populated.

**Comment by AdrianCUCU** [comment]
but - after a server reboot it now works. it's showing me some issues there but now it's my problem. Tks.
