### ISSUE TITLE
"You are not on a branch, Update MISP will fail"

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#4062]
Does this matter?  
I'm on 16.04.5 LTS (GNU/Linux 4.4.0-141-generic x86_64) and getting this message in the Diagnostics Tab.

Currently installed version… v2.4.101 (d7d3d3d6018a03b9b69401056a944efbd943eb28)
Latest available version… v2.4.101 (d7d3d3d6018a03b9b69401056a944efbd943eb28)
Status… OK
**Current branch… You are not on a branch, Update MISP will fail** 

Thank you!

**Comment by SteveClement** [comment]
This only matters if you want to update MISP via the Web Interface.

If you know what you are doing and go to the command line and update from there, this message can be ignored.

In case you struggle with permissions, and do not know as which user your web browser runs, you should consider fixing this issue together with your sysadmin.

More info can be found in the [FAQ Section](https://www.circl.lu/doc/misp/faq/#update-misp-fails) of MISP Book.
