### ISSUE TITLE
Web UI always has "The connection has timed out"

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#4063]
The Web UI works and allows me to login to the home page, but i always get a  "The connection has timed out" error when i try navigate to other pages.

Does anyone have a solution to this?

**Comment by iglocska** [comment]
Sounds like your baseurl is misconfigured. You can modify it via the CLI this way:

`/var/www/MISP/app/Console/cake Admin getSetting "MISP.baseurl" "https://path.to.my.misp"`

**Comment by ndhambi** [comment]
I modified it and still has the same problem, The thing is that the login page loads, I the enter email and password, it the logs me in and show the MISP dashboard page. The connection timed out pops up when i navigate to any other page

**Comment by SteveClement** [comment]
If you have any more logs, please provide them.

For the time being I will close this issue.

**Comment by andrew134598** [comment]
I have the same issue? Any ideas?

**Comment by FoxSca** [comment]
I have the same issue?
