### ISSUE TITLE
API returnFormat only delivers json after Upgrade to 2.4.101

### ISSUE THREAD

**Issue by chrissommer** [MISP/MISP#4064]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| MISP version / git hash   | 2.4.101

We are exporting Attributes via the API and since the Upgrade to 2.4.101 the export is always in json format  - csv and text are not working anymore.

 curl -X POST -k -H 'Accept: application/json' -H 'Authorization: xxxx' -H 'Content-Type: application/json' 'https://misp/attributes/restSearch' --data '{"returnFormat": "text", "last": "1d", "type": "md5"}'

### Expected behavior
returnFormat:text should deliver text, csv should deliver csv

### Actual behavior
returnFormat always delivers json

### Steps to reproduce the behavior
Start a curl and try to change the returnFormat:
 curl -X POST -k -H 'Accept: application/json' -H 'Authorization: xxxx' -H 'Content-Type: application/json' 'https://misp/attributes/restSearch' --data '{"returnFormat": "text", "last": "1d", "type": "md5"}'

**Comment by iglocska** [comment]
Woah, that's nasty. Should be fixed now, thanks!
