### ISSUE TITLE
500 server error after git pull

### ISSUE THREAD

**Issue by thedigitalmurph** [MISP/MISP#4067]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       |  ubuntu,
| OS version (client)       |  Ubuntu, 
| PHP version               | 7.0,
| MISP version / git hash   | 2.4
| Browser                   | chrome

### Expected behavior
git pull to update misp.

### Actual behavior
Unable to access MISP. getting 500 server error. 

looks like there are missing files. I tried to run ./composer.phar install, but get "[Composer\Downloader\TransportException] Content-Length mismatch" error. 

I am unable to get the web app working again. I'm not sure whats going on. 

What else would you need from me to help troubleshoot?

Thank you!

**Comment by adulau** [comment]
Did you do `git submodule sync` and then `git submodule --remote update`? Due to the pear server issue, we updated the submodules.

**Comment by thedigitalmurph** [comment]
git submodule sync looks to have worked, but git submodule --remote update didnt. also, when I to run start.sh, I get 
![image](https://user-images.githubusercontent.com/20444154/51943575-a6316180-23ce-11e9-90b1-fc09b1ca13a8.png)

**Comment by thedigitalmurph** [comment]
Whatever else you need, just let me know. I don't want mess anything else up even more with trying to fix it myself. I'm a bit in over my head with this one.

**Comment by thedigitalmurph** [comment]
I checked for autoload.php and it is not in there. I read in another issue to then run ./composer.phar install , but I just keep getting this. 
![image](https://user-images.githubusercontent.com/20444154/51946916-ef39e380-23d7-11e9-936b-039f2faccfca.png)

**Comment by samwakel** [comment]
I just did a fresh install of MISP overnight, and Cake cannot find autoload.php. I get 500 internal server error as well. After manually searching the directory, I can see that autoload.php hasn't even been created. This is on a fresh install of Ubuntu Server 16.04LTS.

PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 289
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 289

/var/www/MISP/app/Vendor$ l -a
./  ../  bin/  composer/  kamisama/  monolog/  pear/  psr/

**Comment by thedigitalmurph** [comment]
I now know a lot more about how MISP works. I almost fixed this issue. I basically had to rebuild everything.  For the missing config files, I opened up another misp vm and ncat some missing files over to the broken vm and made the necessary changes to those files. After a lot of file moving and trouble shooting error logs,  I now have the web app back up and I can log in and view my data. 

The only problem now is that the attachments are not showing up correctly. I can see them, but when I click on them I get an error. So either they are gone, or that the app can't find where they are. Does anyone know how the attachments are logged? I can't seem to figure this one out. I hope I didn't lose my attachments. 

Thanks!

**Comment by SteveClement** [comment]
@DigitalLeukocyte please open a new issue for that.

With screenshots etc.

**Comment by SteveClement** [comment]
@samwakel please open a seperate issue.
Also you certainly have missed a step along the way.

Perhaps try the first lines of this again:

https://misp.github.io/MISP/INSTALL.ubuntu1804/#4-cakephp

Ubuntu 16.04 is not actively supported anymore, so if it is an issue with that, please open a separate issue.

**Comment by samwakel** [comment]
> @samwakel please open a seperate issue.
> Also you certainly have missed a step along the way.
> 
> Perhaps try the first lines of this again:
> 
> https://misp.github.io/MISP/INSTALL.ubuntu1804/#4-cakephp
> 
> Ubuntu 16.04 is not actively supported anymore, so if it is an issue with that, please open a separate issue.

@SteveClement It's all good now, after reinstalling the day after I posted that everything works again, I forgot to post here, sorry. Thanks for the info on 16.04 LTS though, I'll make sure to migrate to 18.04 LTS at some point this week. Thanks.

**Comment by neildotwilliams** [comment]
I had to do this to get php composer.phar talking over the network:
sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
