### ISSUE TITLE
varying restSearch timestamp range OR (||) results

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4072]
testing with the latest code (2.4.101 +...) that supports `||` in `restSearch` as per https://github.com/MISP/MISP/issues/4056

not sure if i am doing something wrong, or perhaps misunderstanding `timestamp` and `publish_timestamp`, and `from` and `to`. would appreciate some clarification. **THANKS**!

(Note: `2019-01-29` is epoch `1548720000` to `1548806399`)

1. this `restSearch` returns 590 attributes:
```
/attributes/restSearch/csv/type:ip-dst/publish_timestamp:1548720000||1548806399
```

2. and this one returns 590 attributes:
```
/attributes/restSearch/csv/type:ip-dst/timestamp:1548720000||1548806399
```

3. and this returns 2112 attributes:
```
/attributes/restSearch/csv/type:ip-dst/from:2019-01-29/to:2019-01-29
```
4. however, the database says:
```
MariaDB [misp]> select count(*) from attributes where type='ip-dst'
    ->  and timestamp >= 1548720000 and timestamp <= 1548806399;
+----------+
| count(*) |
+----------+
|      616 |
+----------+
```

**Comment by github-germ** [comment]
only related somewhat: not sure how `requested_attributes` works. if i try:
```
attributes/restSearch/csv/type:ip-dst/from:2019-01-29/to:2019-01-29/requested_attributes:value
```
the reply seems to ignore that `requested_attributes`:
```
uuid,event_id,category,type,value,comment,to_ids,date,object_relation,at\
tribute_tag,object_uuid,object_name,object_meta_category
"18067b88-2364-47ad-8211-c658a39c2622",39833,"Network activity","ip-dst"\
,"1,1,1,1","{first_seen: 2018-03-01 18:09:21,last_seen: 2018-03-01 18:09\
:22}",1,1548803071,"","estimative-language:likelihood-probability=""very-likely\
"",nist-cyber-framework:function=""protect"",nist-cyber-framework:function=""de\
tect"",admiralty-scale:source-reliability=""a"",admiralty-scale:information-cre\
dibility=""1""","","",""
...
```
i was hoping to only see:
```
value
"1.1.1.1"
...
```
i can see that type of output using `restSearch/text`, but would still like to understand `restSearch/csv/requested_attributes`:
```
/attributes/restSearch/text/type:ip-dst/from:2019-01-29/to:2019-01-29
```
returns:
```
1.1.1.1
...
```

**Comment by iglocska** [comment]
Indeed requested attributes seems to not be included in the URL parameters (it's an export specific custom parameter which is not in the default list), I'll add it to the list of accepted parameters. (But as you said text is the better format to use for this)

**Comment by iglocska** [comment]
As for the first one, change this:

```
select count(*) from attributes where type='ip-dst' and timestamp >= 1548720000 and timestamp <= 1548806399;
```
to this:

```
select count(*) from attributes where type='ip-dst' and timestamp >= 1548720000 and timestamp <= 1548806399 and deleted = 0;
```

**Comment by github-germ** [comment]
> As for the first one, change this:

the numbers still don't match :-(
db=616, restSearch=590

```
select count(*) from attributes where type='ip-dst' and timestamp >= 1548720000 and timestamp <= 1548806399 and deleted = 0;
+----------+
| count(*) |
+----------+
|      616 |
+----------+
```

**Comment by github-germ** [comment]
> Indeed requested attributes seems to not be included in the URL parameters (it's an export specific custom parameter which is not in the default list), I'll add it to the list of accepted parameters. (But as you said text is the better format to use for this)

Super. Thanks!!

**Comment by iglocska** [comment]
I've pushed it so it should work already ;)

**Comment by github-germ** [comment]
> I've pushed it so it should work already ;)

With blazing speed... ;-)  Will look for it in what I believe is a forthcoming new release. Cool.

What to check our next re' `restSearch` and db validation counts not matching?? --> 
https://github.com/MISP/MISP/issues/4072#issuecomment-459749643

**Comment by iglocska** [comment]
I've pasted it above ;) It's not matching because your mysql query is missing things that are happening automatically. It's filtering out all deleted attributes for example that you still have in your DB with the soft delete flag set.

**Comment by iglocska** [comment]
Ah I see sorry I missed your previous response. There could be a lot of reasons for it (for example orphaned attributes if anything was modified via the DB).

**Comment by github-germ** [comment]
> There could be a lot of reasons for it (for example orphaned attributes if anything was modified via the DB).

All I want to do is be sure that what we have in the `restSearch` results are accurate. Hence, the db check.

We are rolling out to a wide set of enterprise system users a set of `restSearch` URLs for them to consume on-demand into their downstream systems, and in some cases triggering actions. So, we want to be sure we offer **true** results.

When I posted the count diff above, I ran the `restSearch` and the db count at the same time and the epoch is from` 2019-01-29`, not current).

So, how can we be sure all is **_good_**?

Thanks!!

**Comment by github-germ** [comment]
@iglocska -- we are really concerned that the count of a `restSearch` result and (what we think is an equivalent) mysql select differ. we need to prove **data integrity** within our team. as stated below, we ran both at the same time in our MISP instance. if there is NOT an issue here, can you put us at ease with an explanation please. thanks!!


> > There could be a lot of reasons for it (for example orphaned attributes if anything was modified via the DB).
> 
> All I want to do is be sure that what we have in the `restSearch` results are accurate. Hence, the db check.
> 
> We are rolling out to a wide set of enterprise system users a set of `restSearch` URLs for them to consume on-demand into their downstream systems, and in some cases triggering actions. So, we want to be sure we offer **true** results.
> 
> When I posted the count diff above, I ran the `restSearch` and the db count at the same time and the epoch is from` 2019-01-29`, not current).
> 
> So, how can we be sure all is **_good_**?
> 
> Thanks!!

**Comment by iglocska** [comment]
OK, perhaps what you can do to debug this yourself: 

1. Turn on debug mode 2 (so you get the SQL queries displayed)
2. Insert a break point in the execution ( for example here: https://github.com/MISP/MISP/blob/2.4/app/Controller/AttributesController.php#L1977)  - add `throw new Exception();` before the return statement.
3. Run the query in your browser with URL parameters.

You should get something like this:
![image](https://user-images.githubusercontent.com/3668672/52274846-26ffd880-294e-11e9-8243-f795d5938ff4.png)

Simply look through the queries to understand what happens and test against them. You'll see that sometimes we add some additional filters based on the context.

**Comment by github-germ** [comment]
BINGO... the disparity where the mysql query result count was greater than th equivalent restSearch was due to orphan attributes. case solved. thanks for all your help!
