### ISSUE TITLE
Misp-restore.sh issues

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#4079]
So...a few things that didn't get copied over/performed with misp-restore.sh:
~~~
database wasn't imported
gpg.asc 
~~~
after restoring gpg.asc from a backup, importing MYSQL.sql, and importing MISPbackupfile.sql I'm now at a username and password prompt, but current creds to not function.

_Originally posted by @DigiAngel in https://github.com/MISP/MISP/issues/4077#issuecomment-460043303_

**Comment by SteveClement** [comment]
Thanks for the report. This is still being actively investigated, honestly, I would not rely too much on it at this stage of development.
It assumes too many perfect conditions ATM.

**Comment by SteveClement** [comment]
re-open once tested with latest version.
