### ISSUE TITLE
Edit Defaulting to role "user" in user/edit controller.

### ISSUE THREAD

**Issue by Th4nat0s** [MISP/MISP#408]
When you edit a user, the role is always set back to «user»... If you save, you are really back to a «user» :)

**Comment by iglocska** [comment]
Never noticed that, I'll fix this asap, thanks for the heads-up!

**Comment by iglocska** [comment]
Found a case where I can reproduce this: This happens to org admins if they try to edit someone with special privileges. Looking into a way to fix this!

**Comment by Th4nat0s** [comment]
I do confirm, it's the right scenario for the issue, sorry to have missed to point it out.

**Comment by iglocska** [comment]
Have a fix ready, ran out of time today, will push it tomorrow :)

**Comment by adulau** [comment]
Thank you for the fix.

@Th4nat0s Can you perform the test on your account? It's pulled in the CIRCL MISP.

**Comment by Th4nat0s** [comment]
Work flawlessly

**Comment by iglocska** [comment]
Excellent, let me know if you run into any more broken stuff!
