### ISSUE TITLE
Non-admin user can't login to MISP Web UI.

### ISSUE THREAD

**Issue by whatthejay** [MISP/MISP#4081]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Windows 20
| PHP version               | 7.2+60ubuntu1
| MISP version / git hash   | 2.4.102
| Browser                   | Chrome

### Expected behavior
This MISP instance has been installed by using AutoMISP.
Non-admin user should be able to log in MISP web UI.

### Actual behavior
Non-admin user (inc. Org Admin) can't log in MSIP Web UI.
If I change the role to admin, then the account is able to log in.

### Steps to reproduce the behavior
Create MISP user account with "user" role assigned.
Try login.

### Logs, screenshots, configuration dump, ...

I can see the error log from /var/www/MISP/app/tmp/logs/error.log file.

2019-02-04 00:08:53 Error: [MethodNotAllowedException] Great things are happening! MISP is undergoing maintenance, but will return shortly. You can contact the administration at email@address.com.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/UsersController.php(30): AppController->beforeFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): UsersController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

**Comment by SteveClement** [comment]
Dear

I cannot reproduce this on my setup.

Supposedly you used this: https://github.com/da667/AutoMISP

If I get the time I will quickly try this in a VM and see if that reproduces the error.

**Comment by whatthejay** [comment]
Dear @SteveClement,
It works with no problem with the VM instance downloaded from circl.lu.
I can create non-admin user and login to MISP Web UI with no problem.

Commit checksum of VM (working): 7ff303ac08c2218994e1004a903dd442a97c86b7
Commit checksum of MISP (not working): 6a45f8e0596176b1edc05a97932040014633da98

**Comment by iglocska** [comment]
Yeah, MISP.live needs to be set by a site admin. By default, when you install MISP it is disabled for users so that admins go and look at the server settings that need to be modified (such as setting the baseurl etc). 

Just go to administration -> server settings -> MISP tab and change MISP.live to true and users will be able to log in.
