### ISSUE TITLE
Can I run MISP in RHEL now ? Please advise 

### ISSUE THREAD

**Issue by NandyRaja** [MISP/MISP#4082]
Team,

Currently I am running MISP in Ubuntu, can I run it in RHEL. Please let me know if there are any documentations.

**Comment by SteveClement** [comment]
Yes, there is a document here:

https://misp.github.io/MISP/INSTALL.rhel7/

It is WiP as I currently have no install to test this on. But 6 Months ago it worked.

Feel free to open issues if anything is wrong.
