### ISSUE TITLE
Tags selector shows incorrect tag 

### ISSUE THREAD

**Issue by giedriusramas** [MISP/MISP#4083]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug.
| OS version (server)       | Ubuntu,
| OS version (client)       |Win10
| PHP version               | 7.2.10-0ubuntu0.18.04.1
| MISP version / git hash   | 2.4.102
| Browser                   | Google Chrome Version 71.0.3578.98

### Expected behavior
When select tag expect to see selected tag 

### Actual behavior
![misp_tags](https://user-images.githubusercontent.com/8708094/52192776-6ea23980-2854-11e9-84eb-09b47f1f8121.gif)

**Comment by iglocska** [comment]
Ping @mokaddem

**Comment by mokaddem** [comment]
Thanks for the report. This should be fixed now!
