### ISSUE TITLE
Two-way connection

### ISSUE THREAD

**Issue by Pex16** [MISP/MISP#4087]
Hello guys,
I have a question for you.
In my scenario I have my MISP server that share events with other 6 MISP server.
Therefore I have created their Organisations and their Sync Users then they have connected to my instance.
However it could happen that they want to share an event with me. This would be a very rare situation.
I'm not part of their community, so I have to connect to them in some way. My question is how is the best way to be connected with their instances?
I found 2 solutions:
1) they must define in their instances my org., my sync user and then I connect with them;
2) they can define a sharing group with me and distribute events through the sharing group.

Also they can create the event with the distribution "Connected communities" but then my instance will automatically propagate that event with my community so it isn't the best solution.

Is there another way I have not thought about?
Thank you.

**Comment by iglocska** [comment]
Everything you've described is indeed correct. As a 4th way: They could generate a MISP feed and share the URL with you.
