### ISSUE TITLE
restSearch/.../requested_attributes working?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4089]
2.4.102

spun out from 
https://github.com/MISP/MISP/issues/4072#issuecomment-459516998

either we don't understand how `restSearch/.../requested_attributes` works or it's not working. thanks for helping with this...

1. this query:
```
https://localhost/attributes/restSearch/csv/type:ip-dst/from:2019-01-29/to:2019-01-29/
```
returns `2124` lines (including the `csv` header) with actual data on each line

2. and this query with `requested_attributes:value`:
```
https://localhost/attributes/restSearch/csv/type:ip-dst/from:2019-01-29/to:2019-01-29/requested_attributes:value
```
also returns `2124` empty lines, i.e. no text on the `csv` header line, no text at all for the remaining `2123` empty lines!

**Comment by adulau** [comment]
If you don't want to wake up the dragons, maybe you should test by using a JSON with a POST query ;-)

**Comment by github-germ** [comment]
Ha... this is a specific use case for some consumers of our MISP data where they wish to retrieve results via URLs (e.g. bookmarked in their browser).

**Comment by cvandeplas** [comment]
Please read the [automation](https://misp.gitbooks.io/misp-book/content/automation/) documentation describing how to interact with the exports and API. If this does not suffice, would you be open to paid support to help you resolve your issues?

**Comment by github-germ** [comment]
unless i missed something in the docs, this isn't working. however, we can work around it for now.

**Comment by jwilczek** [comment]
I'm seeing the same issue trying to use `requested_attributes` with ExpandedPyMISP. Anytime I specify `requested_attributes` I get X number of blank results where X is the number of things returned by the search with `requested_attributes`  not provided.

**Comment by Daiquiry** [comment]
Hi, 

I had the same issue but found the solution.

you're probably passing the argument as 'requested_attributes':'attribute'

But the argument "requested_attributes" requires an array of strings, instead of a string.

correct implementation would be
'requested_attributes': ['value']
'requested_attributes': ['value','uuid'] 
etc.. you get the idea

Hope it helps
Cheers
