### ISSUE TITLE
an internal error has occurred

### ISSUE THREAD

**Issue by github-dxa** [MISP/MISP#4090]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| OS version (server)       | Ubuntu 16.04.3 LTS
| OS version (client)       | Ubuntu 16.04.3 LTS
| PHP version               |7.0.32-0ubuntu0.16.04.1 (Up to date)
| MISP version / git hash   |v2.4.98 () 
| Browser                   | Chrome

### Expected behavior
Some users can log in without issues, others are seeing "An Internal has occurred", if trying to logout i get the error consistently.

### Steps to reproduce the behavior
Click on logout link and see the error.

### Logs, screenshots, configuration dump, ...

2019-02-04 20:10:04 Error: [Error] Class 'Elasticsearch\ClientBuilder' not found
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1495): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1486): AppModel->loadElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(267): AppModel->getElasticSearchTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Controller/AppController.php(235): Model->save(Array)
#8 /var/www/MISP/app/Controller/AttributesController.php(21): AppController->beforeFilter()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AttributesController->beforeFilter(Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2019-02-04 20:10:04 Error: Fatal Error (1): Uncaught Error: Class 'Elasticsearch\ClientBuilder' not found in /var/www/MISP/app/Lib/Tools/ElasticSearchClient.php:30
Stack trace:
#0 /var/www/MISP/app/Model/AppModel.php(1495): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1486): AppModel->loadElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(267): AppModel->getElasticSearchTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Controller/AppController.php(235): Model->save(Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->disp in [/var/www/MISP/app/Lib/Tools/ElasticSearchClient.php, line 30]
2019-02-04 20:10:04 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 30)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 30, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by github-dxa** [comment]
More information on workaround to the error.

I re-created the issue and reviewed the logs again, seeing this in the logs:
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
 
From /var/www/MISP/app/tmp/logs/error.log
#19 {main}
2019-02-05 03:35:54 Error: [Error] Class 'Elasticsearch\ClientBuilder' not found
Request URL: /users/logout
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1495): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1486): AppModel->loadElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(267): AppModel->getElasticSearchTool()
#3 /var/www/MISP/app/Model/Log.php(117): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Controller/UsersController.php(1269): Model->save(Array)
#8 /var/www/MISP/app/Controller/UsersController.php(1074): UsersController->__extralog('logout')
 
Found some references to Elasticsearch error in Github, which pointed me to the plugin - found the ElasticSearch plugin set to ‘true’; changed to ‘false’ and I’m not seeing the Internal Error during login/logout.  Modified back to ‘true’ and I can reproduce the error, have left this set to ‘false’.

**Comment by cvandeplas** [comment]
I understand the issues is now resolved and could have been related to a non-intended misconfiguration of the Elasticsearch log export. I will therefore close this issue.

Please note that you are running a rather old version of MISP containing also security vulnerabilities.  The latest version at writing is 2.4.102.
