### ISSUE TITLE
a daily query that can remove any attributes older than 30 days from fixed events

### ISSUE THREAD

**Issue by befrankt** [MISP/MISP#4091]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | ubuntu
| PHP version               | 7.2x...
| MISP version / git hash   | 2.4.99
| Browser                   | N/A

### Expected behavior
I have about 20 Fixed events fed by custom data feeds hourly adding more attributes such as domains and ip's (delta merge enabled)…
These events grow over time of course. I want to keep the data in the existing events for 30 days maximum.

Is there a daily query I could run on these 20 events, that would remove any attributes older than 30 days? It would need to leave the exiting event and the more recent attributes in place...

**Comment by github-germ** [comment]
One method (there may be others), write a PyMISP python script that searches for what you deem as expired candidates ready for deletion by attribute timestamp, loop through each and delete.

Something like this:
```
try:
    # if the response is "large", suggest looping
    # with the search using limit and page arguments
    responseDict = misp.search(
        controller = 'attributes',
        eventid    = yourFixedEventIDsList,
        date_to    = date30DaysAgo)
except Exception as e:
    # do as needed...

if 'attribute' in responseDict:
    for attr in responseDict['Attribute']:
        try:
            # read about hard_delete arg and decide
            response = misp.delete_attribute(
                attr['id'],
                hard_delete=True)
            # check response...
        except Exception as e:
            # do as needed...
```

**Comment by kelke** [comment]
sorry to bring up this old issue back up, but does fetching feeds not bring these old attributes back?
