### ISSUE TITLE
Minor usueability - add number of attributes in bottom of list of events

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#410]
Add count of attributes from the subset of events.
So instead of showing:
Page 1 of 3, showing 60 records out of 134 total, starting on record 1, ending on 60
Show:
Page 1 of 3, showing 60 records out of 134 total, starting on record 1, ending on 60 with a total of 10154 attributes.

**Comment by iglocska** [comment]
That is actually trickier than it sounds, it is definitely doable, but you
have to keep in mind that MISP at that point is not aware of the total
attributes visible in the index.

The pagination mechanism uses 3 main sets of filters when displaying the 60
events in the index:

1. Events that you are allowed to see (this means that a simple count()
won't help on the attribute table)
2. Events that match your search criteria (the user defined filters on the
index)
3. The current paginated subset (say records 61->120 from the result of the
subset generated by the above two)

What would be easy: to show the number of attributes in point 3. If that is
good enough for you, I can easily implement it, if you want the total
number of attributes for all pages, not just the paginated page shown, then
it becomes tricky and actually a more intensive task (intensive in a sense
that MISP has to recreate your query without the paginated subset and fetch
the attribute count from each event).

Would showing the actively displayed event list's attribute count be good
enough? (So the attribute count of the 60 events paginated)

**Comment by elhoim** [comment]
No implementation is also fine, I had no idea this would be so complicated, I just thought it could be a simple modification.
