### ISSUE TITLE
MISP Synchronzation problem on MISP v2.4.102

### ISSUE THREAD

**Issue by faimario** [MISP/MISP#4108]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | ubuntu
| OS version (client)       | Seven
| PHP version               | 7.0.22
| MISP version / git hash   | 2.4.102
| Browser                   | Chrome

I have two different MISP instances (MISP_1 and MISP_2), owned by different entities. Besides, I have two organisations, called Org_1 and Org_2, respectively belonging to MISP_1 and MISP_2

I would like to push in real time events from MISP_1 to MISP_2.

**MISP_2 set up:**

- Org_1 created as **local** organisation with the same uuid as in MISP_1

- a user called user_1@org_1.com has been created MISP_2, belonging to Org_1, as a sync user 

**MISP_1 set up:**

- Org_2 created as **local** organisation with the same uuid as in MISP_2 (Because in MISP_1 there is a user of MISP_2)

- a sync server has been created, specifying Org_2 as local organization, the IP address of the remote MISP instance (MISP_2) and the auth key of the sync user created in MISP_2 (who is an Org_admin in MISP_1 for Org_1). Only push is considered for this scenario, without specifying any rules

Synchronization test between the instances works fine.

### Expected behavior
Every time user_1@org_1.com creates a new MISP event on MISP_1 and published it, this event should be automatically pushed to MISP_2
### Actual behavior
The event is not sent to MISP_2, after user_1@org_1.com publishes it. The event is marked as published, but in the "Job" page, the job for handling the publish, handled by "prio" worker, is marked with Status: Failed. 
In order to send the event to MISP_2, a login with another user, called admin@org_1.com (which is a site-admin for MISP_1), belonging to Org_1, should be done, and manually force a push operation going to Sync Actions --> List Servers. Besides, also if I create an event with admin@org_1.com, forcing a push allows sending it to MISP_2 (which is weird, because, as far i understood, also the user associated to the auth key could do that)

### Steps to reproduce the behavior
Could be found above, where i described the problem

Maybe I am missing something with the configuration of the instances.
Is the expected behavior I specified the correct one, or i am misunderstanding something about how MISP synchronization works?

Thanks you very much for your help!!

**Comment by SteveClement** [comment]
In your Published event, what do you set the "Distribution" Level as?

Further refer to: https://www.circl.lu/doc/misp/sharing/#sharing-and-distribution
And: https://www.circl.lu/doc/misp/using-the-system#creating-an-event
