### ISSUE TITLE
Ability to change the URL in the sharing group if the baseurl is not set

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4111]
Ability to change the URL in the sharing group if the baseurl is not set. This is useful for organisations using multiple URL to access a MISP and the baseurl is unset.

**Comment by pettai** [comment]
+1

**Comment by iglocska** [comment]
Done via the new external_baseurl setting.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/fede678d5df8d90c02e9a12e5380603a99651974
