### ISSUE TITLE
HTTP Status 200 returned on bad input

### ISSUE THREAD

**Issue by FloatingGhost** [MISP/MISP#4116]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | N/A
| PHP version               | 7.1...
| MISP version / git hash   | 2.4.102
| Browser                   | N/A

### Expected behaviour
When an invalid event is attempted to be `POST`ed, the HTTP status code should be `400 Bad Request`

### Actual behavior
The status code is `200`, indicating a success

### Steps to reproduce the behavior
Post a JSON which does not validate. The easiest way is just to set `info` to `null` like so 

```bash
curl \
  --header "Authorization: <apikey>" \
  --header "Content-type: application/json" \
  --header "Accept: application/json" \
  --data-binary '{"Event": {"info": null}}' \
  -XPOST \
   -D- \
  https://misp.local/events/add
```

### Logs, screenshots, configuration dump, ...

```
HTTP/1.1 200 OK
Date: Wed, 06 Feb 2019 13:38:09 GMT
Server: Apache
Set-Cookie: CAKEPHP=abcdefg; expires=Wed, 06-Feb-2019 21:38:09 GMT; Max-Age=28800; path=/; secure; HttpOnly
Content-Length: 146
Strict-Transport-Security: max-age=15768000;includeSubDomains
Content-Type: application/json; charset=UTF-8

{"name":"Add event failed.","message":"The event could not be saved.","url":"\/events\/add","errors":{"Event":{"info":["Info cannot be empty."]}}}
```

**Comment by iglocska** [comment]
WTF

**Comment by iglocska** [comment]
BTW, this should have been fixed after you've reported it, thanks - weird behaviour for sure ;)

**Comment by FloatingGhost** [comment]
Hm, running on 9df8a8d4637684e2 it returns 403

Certainly better than 200 but not quite what it should be

```bash
> $ curl \                                                                            [±2.4 ●●]
  --header "Authorization: " \
  --header "Content-type: application/json" \
  --header "Accept: application/json" \
  --data-binary '{"Event": {"info": null}}' \
  -XPOST \
   -D- \
  http://localhost:8081/events/add
HTTP/1.1 403 Forbidden
Date: Tue, 12 Feb 2019 10:36:10 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: CAKEPHP=; expires=Tue, 12-Feb-2019 11:36:10 GMT; Max-Age=3600; path=/; HttpOnly
Content-Length: 231
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=UTF-8

{
    "name": "Could not add Event",
    "message": "Could not add Event",
    "url": "\/events\/add",
    "errors": {
        "Event": {
            "info": [
                "Info cannot be empty."
            ]
        }
    }
} 
```

**Comment by iglocska** [comment]
Indeed, we don't differentiate between not allowed and failed because of validation issues. That is a good point.
