### ISSUE TITLE
Unable to update MISP from GUI (CentOS 7)

### ISSUE THREAD

**Issue by saeeda12** [MISP/MISP#4120]
When I try to update MISP to the latest available version from the GUI, I get the below errors.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 7
| OS version (client)       | 7
| PHP version               | 7.1.8
| MISP version / git hash   | 2.4.98 (ff0b81efaa3551a25d23787d5f76ef90d0224a08) 
| Browser                   | Chrome

### Expected behavior
Update MISP to 2.4.102

### Actual behavior
Get a bunch of permission denied messages.

### Steps to reproduce the behavior
I made sure the permissions were set appropriately for the `.git` folder and `.git/FETCH_HEAD`, but still received the same errors.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/14843351/52355493-6850c080-2a00-11e9-84f1-b5d873f320eb.png)

**Comment by saeeda12** [comment]
When I tried doing it via command line:
```
cd /var/www/MISP
sudo git pull
#then switch to the 2.4 branch
sudo git checkout 2.4
#then another one
sudo git pull
```
I'd get an error that my local changes to the following files would be overwritten by the merge, then it lists all the files and says `Aborting` before exiting out.

**Comment by iglocska** [comment]
That sounds like you've used git with a root account and MISP (which is using the apache user) cannot read/write your .git directory. Please make sure that you recursively assign the apache user to the entire MISP directory.

```
chown www-data:www-data /var/www/MISP
```
assuming that www-data is your apache user.

Also, for the changes that are listed when using your root account: sounds like you've either made local modifications or git simply thinks that your (correct) changing of file permissions is a modification meant for git. To avoid the latter simply set git filemode to false (it's described how in the install documentation).

**Comment by saeeda12** [comment]
Thanks for your reply!

I believe I set git filemod to false when installing MISP code, but when I tried again I got:
```
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Trying with:
```
# Fetch submodules
sudo -u apache git submodule update --init --recursive
# Make git ignore filesystem permission differences for submodules
sudo -u apache git submodule foreach --recursive git config core.filemode false
```

**Comment by saeeda12** [comment]
I set the git filemode to false - had to change some permissions of files in the .git folder. And assigned apacher user to entire MISP directory, but I am still getting the aborting error.

**Comment by saeeda12** [comment]
I tried running the `sudo -u apache git submodule update --init --recursive` command again and it returned the following this time. I checked and confirmed the permissions on all the listed files/ directories, and I'm not sure which `index` file is being referred to here. 

![image](https://user-images.githubusercontent.com/14843351/52367069-3566f680-2a19-11e9-9be5-cd3850429b1b.png)

**Comment by iglocska** [comment]
Sounds like more permission issues. 

```
chown -r www-data:www-data /var/www/MISP
```

**Comment by saeeda12** [comment]
I ran `sudo chown -R apache:apache /var/www/MISP/*` and confirmed, but unfortunately, I'm still unable to update MISP. And running `sudo -u apache git submodule update --init --recursive` from the `/var/www/MISP` directory still gives the **fatal: Not a git repo error.**

**Comment by saeeda12** [comment]
Just for the sake of it, tried again and saw it worked, but updating failed again with the Aborting message:
```
sudo chown -R apache:apache /var/www/MISP
sudo -u apache git submodule update --init --recursive
```
```
sudo -u apache git submodule foreach --recursive git config core.filemode false
Entering 'Plugin/DebugKit'
Entering 'PyMISP'
Entering 'PyMISP/pymisp/data/misp-objects'
Entering 'app/Lib/cakephp'
Entering 'app/Lib/random_compat'
Entering 'app/files/misp-galaxy'
Entering 'app/files/misp-objects'
Entering 'app/files/noticelists'
Entering 'app/files/taxonomies'
Entering 'app/files/warninglists'
Entering 'cti-python-stix2'
Entering 'misp-vagrant'
```

In the UI it still says:
```
git checkout app/composer.json 2>&1

fatal: Unable to create '/var/www/MISP/.git/index.lock': Permission denied

git pull origin 2.4 2>&1

fatal: Unable to create '/var/www/MISP/.git/index.lock': Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied


=================================

git submodule update --init --recursive 2>&1

You need to run this command from the toplevel of the working tree.
```

**Comment by MumbarGit** [comment]
Having same issue. Why was this one closed when not solved?
It is connected to issue https://github.com/MISP/MISP/issues/4038 that was also not solved.

**Comment by MumbarGit** [comment]
After digging it seems to me that this was mentioned here:
https://github.com/MISP/misp-book/issues/146
and the UI error was fixed by follwing commands:

`semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/MISP(/.*)?`
`restorecon -R /var/www/MISP/`
