### ISSUE TITLE
Correlations table EXPLODING within two days

### ISSUE THREAD

**Issue by cgi1** [MISP/MISP#4122]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04.
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.103
| Browser                   | OS level

### Expected behavior

Not exploding mysql file sizes

### Actual behavior

MySQL file for correlation explodes.

### Steps to reproduce the behavior

Activate Open Source feeds for Download

### Logs, screenshots, configuration dump, ...

This still happens and breaks complete environments:

```
MariaDB [misp]> select count(*) from correlations;

+-----------+
| count(*)  |
+-----------+
| 629529974 |
+-----------+
1 row in set (3 min 16.49 sec)
```

<img width="328" alt="grafik" src="https://user-images.githubusercontent.com/18695252/52404520-80404700-2ac9-11e9-9d00-26e4d51183d4.png">

<img width="635" alt="grafik" src="https://user-images.githubusercontent.com/18695252/52404563-9cdc7f00-2ac9-11e9-93dc-f14d763fd502.png">

**Comment by iglocska** [comment]
Please make sure that you use "fixed event" as target for the open source feeds to avoid this.

**Comment by cgi1** [comment]
> Please make sure that you use "fixed event" as target for the open source feeds to avoid this.


Where can I find this settings? Can this be set globally for all feeds?

And if you are aware of this issue... Why dont you set it by default?

**Comment by cgi1** [comment]
**CLOSED**

*  If you are running into this issue Truncate the correlation table in MySQL. (to make it responsible again)
*  If the MISP instances should run as a _collection pool_ for information, just diable correlations globally (Administrator --> MISP settings)

If @iglocska answers how to set fixed event we could add it here.

**Comment by iglocska** [comment]
It should be the default for all newer installations. Sadly we can't retroactively change it for older instances as it may be the desired functionality.

Indeed, truncating the correlation table, deleting the duplicate feed events and re-enabling the correlation table is the best way to go.
