### ISSUE TITLE
Automate adding a new feed

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4132]
2.4.102

Is there a way to automate adding a new feed?

**Comment by cvandeplas** [comment]
Yes, you can do this using the REST API, or even easier using [PyMISP](https://github.com/MISP/PyMISP)

**Comment by github-germ** [comment]
thanks. i do see these `/feeds/` endpoints in the docs: `enable`, `disable`, `cacheFeeds`, `fetchFromFeed`, `fetchFeedFromAllFeeds`. and i see `PyMISP.add_feed()`,

**but do not see a REST API endpoint for adding a feed?**

**Comment by iglocska** [comment]
Really?

![image](https://user-images.githubusercontent.com/3668672/52555458-1a65ff00-2dea-11e9-8500-bc946c418cea.png)

**Comment by github-germ** [comment]
OK, nice. Thank you. Now, we realize (duh) we can look on the Query Builder page. Cool. (was looking on the automation page).
