### ISSUE TITLE
MISP on AWS

### ISSUE THREAD

**Issue by NandyRaja** [MISP/MISP#4143]
Team,

MISP can run on AWS - managed service RDS ? or MYSQL has to run local on EC2 ?

**Comment by FloatingGhost** [comment]
It literally doesn't matter, they're both mysql databases

If you have the budget for RDS, that's easier to maintain in the long run but there's nothing stopping you running it on EC2

**Comment by znb** [comment]
I'm currently setting up my MISP instance in AWS with RDS on the backend.

No issues on the AWS side so far, only with the installation.

I'm happy to share my Terraform scripts for this if anyone is interested.

**Comment by NandyRaja** [comment]
Hi @znb , That would be great. Please share them up. 

Whats the comparison results of RDS hosted vs EC2 hosted Mysql in cost, performance, etc... Let me know if you aware of...

**Comment by adulau** [comment]
I suppose you saw https://github.com/MISP/misp-cloud which are "Cloud-ready images of MISP" for AWS.

**Comment by NandyRaja** [comment]
@[adulau](/adulau) Yes ! I got requirement to build it on RHEL whereas the image is built on Ubuntu 18.x

**Comment by NandyRaja** [comment]
@znb Please let me know if you get a chance to post them.

**Comment by adulau** [comment]
@znb Feel free to share the script with us, we can put it in the generic installation script. Thank you very much.

**Comment by znb** [comment]
@adulau I shall put it online after I've done a little tidy up.

Hopefully I'll make some time over the weekend.

**Comment by znb** [comment]
Apologies for the delay here. Work + life is causing havoc.

https://github.com/znb/AWS_MISP

This script is currently untested but should work fine. 

I'll improve documentation when I get some more time.

**Comment by NandyRaja** [comment]
Much Appreciate your help !
