### ISSUE TITLE
UI change to provide more context for correlations/related events

### ISSUE THREAD

**Issue by davidljohnson** [MISP/MISP#4148]
When viewing an event's correlations, I believe it would be helpful to make a slight UI change. Instead of displaying only the date and local ID of events in the "Related Events" section of an event, I would like to see a more detailed view of the events that includes the title and contributing org (instead of needing to hover over the related events for more information).

Implementing this UI change would help triage correlations at a much faster rate. 

As a workaround, I have tried using the correlation graph to find related events of significance, but usually the events are clustered together and it can be hard to read them.

**Comment by adulau** [comment]
If I understand correctly, you would like to view the info/org (which is in the hover currently) directly without the need to hover the related event link. It makes a lot of sense. We just need to be a bit clever when a lot of related events are displayed without overloading the screen. We will discuss within the team. Thanks for the feedback.

**Comment by davidljohnson** [comment]
Exactly...I have a feeling that it would really improve the ability to triage significant correlations. I know it's a trade off between showing more detail (quality) and the amount of correlations shown on the screen (quantity), but I think it makes sense. 

Besides, if I wanted a list of all correlated attributes, I could also click on the correlations tab within the event. The way it exists now is helpful, but could be greatly improved by adding even just the even title, IMHO.

**Comment by mokaddem** [comment]
Fixed with #4570
