### ISSUE TITLE
Layout problem with the heatmap

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#415]
In the statistics page, when there are a lot of orgs

**Comment by adulau** [comment]
Confirmed on two instances close and above 100 orgs.

**Comment by iglocska** [comment]
I'll try to reproduce this one soon, we don't have enough orgs to see this.

On Sun, Mar 8, 2015 at 7:08 PM, Alexandre Dulaunoy <notifications@github.com

**Comment by Rafiot** [comment]
Fixed.

**Comment by adulau** [comment]
This has been fixed.
