### ISSUE TITLE
Delete Older Jobs from the queue?

### ISSUE THREAD

**Issue by peka8** [MISP/MISP#4150]
Hello,
Is it possible to delete queued jobs that are very old?
As you can see from the attached photo, I would like to eliminate the old jobs in the queue, because they take so much to download and there are many. Thank you
![cattura](https://user-images.githubusercontent.com/35296639/52715438-c3ecf200-2f9c-11e9-8b19-5efe1ca74f37.PNG)

Regards

**Comment by iglocska** [comment]
The job interface is more like a log than an actual representation of open jobs. Check your actual job queue size and empty it in the worker tab of the server setting tool (administration -> server settings -> workers -> little number and trash icon above each queue).

**Comment by peka8** [comment]
Thank you! This post can be closed!
