### ISSUE TITLE
Server Settings & Maintenance Error Configuration

### ISSUE THREAD

**Issue by peka8** [MISP/MISP#4151]
Hello, 
in my misp console of server settings, there are several errors, red and yellow, as in the image I attach. But how can I solve them?

![slide](https://user-images.githubusercontent.com/35296639/52717466-74f58b80-2fa1-11e9-87cf-a73e1a2d320a.PNG)

Do you show me the procedure to solve them?
Thank you

**Comment by iglocska** [comment]
It just says the value is not set and it shows you what default it would use. This may be correct for you, in which case you don't have to worry about it. If you want the error to go away, simply doubly click the value and confirm your choice.

**Comment by peka8** [comment]
thanks, this case can be closed.
