### ISSUE TITLE
Threat Actor Galaxy Tags Are Converted to Lower Case

### ISSUE THREAD

**Issue by jwilczek** [MISP/MISP#4154]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.102 (28e98b050b248f752ab2a44a40e80b655b3bdece) 
| Browser                   | N/A

### Expected behavior
When adding tags through pyMISP, parts of the tag seem to be automatically converted to lower case, possibly causing related Threat Actor Galaxies not be associated.

### Actual behavior
When adding the tag
`misp.tag(event['Event']['uuid'], 'misp-galaxy:threat-actor="DarkHotel"')`

In MISP it is changed to:
`misp-galaxy:threat-actor="darkhotel"`

### Steps to reproduce the behavior
Add a tag representing a threat actor through PyMISP or web UI.

**Comment by cvandeplas** [comment]
I can reproduce this issue on my test VM. But wasn't able (yet) to find another tag/galaxyclustervalue having the same behavior.

**Comment by cvandeplas** [comment]
To clarify, this also happens when using the webUI to add the darkhotel actor. Notice other Galaxies are added correctly as Galaxy.
The glitch is also in the JSON export where the tag does not appear in the Galaxies section.

![image](https://user-images.githubusercontent.com/1073662/52745075-83ae6380-2fde-11e9-8c65-c4b85b6d6a42.png)

**Comment by jwilczek** [comment]
Perhaps DarkHotel would prefer they not get tagged?

**Comment by jwilczek** [comment]
Anyone looking at this?

**Comment by iglocska** [comment]
Hmph, that's unfortunate. Tag names should always be lowercase in the first place. I can relax the automatic lower casing but not sure if that won't do more harm than good in the long run.
