### ISSUE TITLE
REST Client - API clarification for attributes/edit query template

### ISSUE THREAD

**Issue by thebitbucket123** [MISP/MISP#4159]
Hello, 

I'm using MISP v2.4.102.

I've been working to automate flagging of to_ids for existing MISP attributes based on tags added by users. While working through the various api calls to edit the attributes, I was directed by the query template to build my query with "attributes/edit/[event_id]", leading me to specify the attribute I wanted to edit via uuid. Regardless of the parameters I used (built via the query builder), I received an "Invalid attribute" error in return. After digging through the AttributesController.php edit function, I thought to try using the attribute_id instead of event_id while only specifiying {"to_ids":1} in the body, and it worked perfectly.

I believe that clarifying the text for the "attributes/edit" query template to require "[attribute_id]" instead of "[event_id]" would be helpful to others attempting to use this API call.

**Comment by iglocska** [comment]
Nice catch, thanks!
