### ISSUE TITLE
CSV events export ignores category

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP#4160]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian
| PHP version               | 7.0.33
| MISP version / git hash   | 2.4.102, 435ca8742434831f7220207eda97adaebd61299f

### Expected behavior
defining a category in /events/restSearch leads to output that only shows the selected category

### Actual behavior
defining a category in /events/restSearch leads to output that shows the selected category and other categories too

### Steps to reproduce the behavior
curl -k --header "Authorization:  AUTHKEY" --header "Accept: application/json" --header "Content-Type: application/json" -X POST https://misp.test/events/restSearch  -d '{"returnFormat": "csv", "category": "Network activity"}'

### Logs, screenshots, configuration dump, ...
Categories that show up in the output
"Network activity"
"Internal reference"
"Payload delivery"
"External analysis"

```
 # grep "Network activity" foo.csv |wc -l
122009
# grep -v "Network activity" foo.csv |wc -l
24298
```

**Comment by iglocska** [comment]
Just tried this:
```
curl \
 -d '{"returnFormat":"csv","page":"1","limit":"100","category":"Financial fraud"}' \
 -H "Authorization: MyAPIKey" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 -X POST https://my.dev.misp/attributes/restSearch
```

Works fine for me.

Looking at your query you are using /events/restSearch. What this does is it returns any full event that matches your search parameters. So if you use category: Network activity, it will return all data from ANY event that has at least one network activity attribute.

If you just want the network activity attributes in your CSV export, use /attributes/restSearch.
