### ISSUE TITLE
/attributes/restSearch is broken

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP#4162]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| PHP version               | 7.0.33
| MISP version / git hash   | 2.4.102, 435ca8742434831f7220207eda97adaebd61299f

### Expected behavior
/attributes/restSearch outputs the defined data

### Actual behavior
/attributes/restSearch outputs:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/attributes\/restSearch"}

### Steps to reproduce the behavior
curl -k --header "Authorization:  AUTHKEY" --header "Accept: application/json" --header "Content-Type: application/json" -X POST https://misp.test/attributes/restSearch  -d '{"returnFormat": "csv", "category": "Network activity"}'

### Logs, screenshots, configuration dump, ...

I get this error in the logs

```
2019-02-15 13:38:47 Error: Fatal Error (1): Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1273]
2019-02-15 13:38:47 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1273)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1273, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by worldopener** [comment]
setting the PHP max mem to 2048M

`memory_limit = 2048M`

 it was 1024M before still creates the same error



```
2019-02-15 14:04:42 Error: Fatal Error (1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1273]
2019-02-15 14:04:42 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1273)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 1273, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

**Comment by iglocska** [comment]
Your query might potentially return too much data and you're indeed running out of memory. You could instead paginate and flip through the data, simply change your query to this:

```
{
    "returnFormat": "csv",
    "category": "Network activity",
    "limit": 20000,
    "page": 1
}
```
and increment page until you get data back.

**Comment by SteveClement** [comment]
@worldopener did this solve your issue?

**Comment by worldopener** [comment]
yes, thanks
