### ISSUE TITLE
Why you have two Ways for Documentation?

### ISSUE THREAD

**Issue by 8ear** [MISP/MISP#4167]
Hi to all,
Why you have two different documentation sources?
What is the difference between both?

First Documentation: (git-book) 
- https://www.circl.lu/doc/misp/

Second Documentation (mkdcos):
- https://misp.github.io/MISP/

Isn't it better if there's just one documentary?

**Comment by SteveClement** [comment]
One is the documentation about how to use MISP.

The other on is a dedicated install documentation that also serves as basis for the installer.
