### ISSUE TITLE
incomplete installation instruction

### ISSUE THREAD

**Issue by IrootGeek** [MISP/MISP#4174]
Hello,
Some instructions are incomplete to install MISP in [Debian9](https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.debian9.md)the must important instuction is.
The most important instruction is to define the path of instalation of MISP  in /var/www/MISP/

## Define all variables
- PATH_TO_MISP="/var/www/MISP/"
- MISP_USER='misp'
- MISP_PASSWORD
- WWW_USER="www-data"
- PATH_TO_MISP='/var/www/MISP'
- FQDN="misp.local"
- DBHOST='localhost'
- DBNAME='misp'
- DBUSER_ADMIN='root'
- DBPASSWORD_ADMIN="$(openssl rand -hex 32)"
- DBUSER_MISP='misp'
- DBPASSWORD_MISP="$(openssl rand -hex 32)"
- OPENSSL_CN=$FQDN
- OPENSSL_C
- OPENSSL_ST
- OPENSSL_L
- OPENSSL_O='Organization'
- OPENSSL_OU='Organizational Unit'
- OPENSSL_EMAILADDRESS
- GPG_REAL_NAME='Autogenerated Key'
- GPG_COMMENT='WARNING: MISP AutoGenerated Key consider this Key VOID!'
- GPG_EMAIL_ADDRESS
- GPG_KEY_LENGTH='2048'
- GPG_PASSPHRASE
- upload_max_filesize=50M
- post_max_size=50M
- max_execution_time=300
- memory_limit=512M
- CAKE="$PATH_TO_MISP/app/Console/cake"

For authentication on MISP after install
usermail : admin@admin.test
password: admin

Thanks

**Comment by SteveClement** [comment]
Thanks for this, it is already fixed in an upcoming update to the Debian 9.8 procedure.

Thanks.

**Comment by IrootGeek** [comment]
You're welcome
