### ISSUE TITLE
Black-holed request on MISP import

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4178]
When trying to import a fairly large (70GB) MISP JSON I get the following error when the upload reaches 100%:

The request has been black-holed
Error: The requested address '/events/add_misp_export' was not found on this server.

Is there anything I am not seeing? Or should I just use smaller files to upload?

**Comment by adulau** [comment]
A single MISP event of 70GB? You really mean GB? In a single event?  How the file was generated?

**Comment by SteveClement** [comment]
@timonvds importing 70 GigaBytes will take a long time and all timeouts would need to be adapted.

This seems large.
