### ISSUE TITLE
email Config

### ISSUE THREAD

**Issue by mgeorgy** [MISP/MISP#418]
Are there instructions or suggested configuration for implementing email functionality in MISP?  I've attempted to modify the email.php file in the Config directory, but still do not see emails send from the server.

Thank you.

**Comment by RichieB2B** [comment]
There is nothing to configure in MISP regarding SMTP except the sender E-mail address in config.php All other configuration is done in php.ini, look at the [mail function] section there.

**Comment by iglocska** [comment]
Indeed, the email.php is obsolete and doesn't actually affect any of the
settings in MISP. Just set up postfix to either directly send e-mails /
relay it to your exchange server or whatever you'd like to use.

**Comment by mgeorgy** [comment]
Any suggestions on how to diagnose email issues?  I'm able to send test messages directly form the server, indicating postfix is working.  I'm not receiving messages from MISP when I publish an event.

I checked php.ini, [mail function] seems fine (localhost/25).

**Comment by iglocska** [comment]
Does anything show up in maillog? (/var/log/maillog)

**Comment by mgeorgy** [comment]
Only postfix delivery for other tasks (crontab).  Nothing from MISP.

**Comment by cudeso** [comment]
I have this in php.ini
`sendmail_path=/usr/sbin/sendmail -t -i`

1) Are the workers running?
2) Have you tried sending mails from a test PHP-script? F.e.:

`
<?php
$headers = 'From: me@example.be' . "\r\n" .
    'Reply-To: me@example.be' . "\r\n";
mail('me@example.be','subject','message',$headers);
?>
`

**Comment by elhoim** [comment]
mrgeorgy, any update? Can I close this ticket?

**Comment by luannguyen81** [comment]
I am having the same issue, that email is not sent evethought the MISP log shows email has sent.

**Comment by Rafiot** [comment]
And the postfix logs? Are they also showing the mails as sent?

**Comment by luann-trend** [comment]
Here is the logs 

May  9 15:34:26 misp-service-7c5cbdf79c-c44rt postfix/pickup[20511]: 06BF11844EE: uid=33 from=<www-data>
May  9 15:34:26 misp-service-7c5cbdf79c-c44rt postfix/cleanup[20574]: 06BF11844EE: message-id=<5af31502080c4172bbba042d0a3c0cdf@dn.com>
May  9 15:34:26 misp-service-7c5cbdf79c-c44rt postfix/qmgr[58]: 06BF11844EE: from=<www-data@d81289f9d10c>, size=2797, nrcpt=1 (queue active)
May  9 15:34:26 misp-service-7c5cbdf79c-c44rt postfix/smtp[20576]: fatal: unknown service: smtp/tcp
May  9 15:34:27 misp-service-7c5cbdf79c-c44rt postfix/qmgr[58]: warning: private/smtp socket: malformed response
May  9 15:34:27 misp-service-7c5cbdf79c-c44rt postfix/qmgr[58]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
May  9 15:34:27 misp-service-7c5cbdf79c-c44rt postfix/master[49]: warning: process /usr/lib/postfix/sbin/smtp pid 20576 exit status 1
May  9 15:34:27 misp-service-7c5cbdf79c-c44rt postfix/master[49]: warning: /usr/lib/postfix/sbin/smtp: bad command startup -- throttling
May  9 15:34:27 misp-service-7c5cbdf79c-c44rt postfix/error[20577]: 06BF11844EE: to=<myemail@dn.com>, relay=none, delay=1, delays=0.02/1/0/0.01, dsn=4.3.0, status=deferred (unknown mail transport error)
May  9 15:34:48 misp-service-7c5cbdf79c-c44rt postfix/qmgr[58]: 353701844CD: from=<www-data@d81289f9d10c>, size=2805, nrcpt=1 (queue active)
May  9 15:34:48 misp-service-7c5cbdf79c-c44rt postfix/error[20577]: 353701844CD: to=<myemail@dn.com>, relay=none, delay=412171, delays=412171/0/0/0, dsn=4.3.0, status=deferred (unknown mail transport error)

**Comment by CLD87** [comment]
I'm getting this error "Email to user@domain.ro, titled "test" failed. Reason: Emailing is currently disabled on this instance."
Can anyone help with the parameters that should be configured in order to be able to send e-mails to users?

**Comment by rommelfs** [comment]
By default, sending emails is disabled in MISP. You can enable it by setting MISP.disable_emailing to false in servers/serverSettings/MISP.

**Comment by rommelfs** [comment]
Also, I recommend to create new issues instead of pluging into historic ones.
