### ISSUE TITLE
Can't add plain tags to event

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4192]
Since upgrading to MISP 2.4.101 I can no longer add a plain, simple, non-taxonomy tag like OSINT to an event. The new tag picker has options for _Tag Collections, Taxononies_ and _All Tags_ but after selecting _All Tags_ only a list of all tags belonging to a taxonomy is displayed. The URL /tags/index does show all tags though.

Can plain, simple non-taxonomy tags still be used?

**Comment by mokaddem** [comment]
Maybe we should add a new option ``free text tag`` available in the picker to allow users to enter non-existing tags.

**Comment by RichieB2B** [comment]
This also happens when the plain tag already exists in the List Tags view. This bug is about not being able to add plain, simple, non-taxonomy tags to an event even when the tags already exist in the MISP instance.

Having a way to create new tags on the fly from the new tag picker is indeed a nice enhancement but not what this issue is about.

**Comment by RichieB2B** [comment]
Steps to reproduce:

1. add a plain, simple, non-taxonomy tag to MISP and call it OSINT (if not already present, it's very common)
2. edit an event
3. try to add the OSINT tag to the event
4. observe that the OSINT tag is not one of the options shown in the tag picker, even when _All Tags_ is selected

**Comment by RichieB2B** [comment]
Never mind, because of `incoming_tags_disabled_by_default` all tags were hidden. After unhiding everything works fine,
