### ISSUE TITLE
X.509 certificate fingerprint, serial number, DN and Issuer attributes.

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#420]
We are missing X.509 certificate fingerprint, serial number, DN and Issuer attributes in MISP.

**Comment by elhoim** [comment]
Mostly duplicate of #20

**Comment by adulau** [comment]
The SHA1 fingerprint attribute has been added (386dfc7ec8c42907af536d22da5499efb290c0d8) . For the whole X509 certificate, it will a full blown misp-object https://github.com/MISP/misp-objects/

**Comment by elhoim** [comment]
Probably going to need a x509-fingerprint-sha256 attribute type too since sha1 is soon enforced as deprecated

**Comment by adulau** [comment]
Objects are now implemented in MISP 2.4.80 and a X.509 object default exists.
