### ISSUE TITLE
OSError [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mbunde** [MISP/MISP#4208]
I have just started with MISP virtual machine, when i run **sudo -u www-data misp-modules** command I get an error OSError [Errno 98] Address already in use. The error is in bind_sockets sock.bind(sockaddr).
Any help with this will be greatly appreciated.

**Comment by rommelfs** [comment]
The error message from your operating system indicates that something is binding already on the port `misp-modules` want to bind on. The circumstances indicate that this is most probably `misp-modules`, which is already running.

Please verify with the `ps` command.

As described in https://github.com/MISP/misp-modules, you can kill the running process with the following command:
`sudo killall misp-modules`
