### ISSUE TITLE
Server Settings & Maintenance - Workers missing

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#4209]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 10
| PHP version               | 7.1
| MISP version / git hash   | v2.4.102 (c0427216899f714930b5782bc784349de9773677) 
| Browser                   | Chrome

Go into Administration --> Server Settings & Maintenance 

Here the "button" Workers is missing, but if you call the URL directly it is still there
/servers/serverSettings/workers

**Comment by adulau** [comment]
Oops. Fixed in 12ffbf991b48829a27f8f215a692b788a737ca00. Thank you.
