### ISSUE TITLE
New attribute type

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#421]
For the future: Domain|IP

**Comment by elhoim** [comment]
Unnecessary if #27 is implemented, or as temporary solution until then.

**Comment by iglocska** [comment]
Definitely a temporary solution. I want to do a quick round of adding new attribute types at the end of the cycle for the current version, before I begin work on the new datamodel, as a stop gap solution. I am collecting all the new attribute types that people are asking for!

**Comment by cvandeplas** [comment]
it seems that this type was added (domain|ip).
However the comparable hostname|ip is missing.

**Comment by jeff3877** [comment]
+1 for hostname|ip

**Comment by elhoim** [comment]
+1 for hostname|ip attribute type

**Comment by cvandeplas** [comment]
-1 for hostname|ip

The reasons are:
- IDS flag is not working well for combined attributes (you can't specify IDS on one of the 2)
- we already have domain|ip . .. actually, that should probably have been called hostname|ip ...
- having both hostname|ip and domain|ip will lead to more confusion for analysts

**Comment by adulau** [comment]
misp-object should be more appropriate to cover theses cases.

https://github.com/MISP/misp-objects/blob/master/objects/domain-ip/definition.json

**Comment by adulau** [comment]
Objects are now implemented in MISP 2.4.80. Feel free to add missing objects in the templates and do a PR.
