### ISSUE TITLE
Problem when pushing events

### ISSUE THREAD

**Issue by Kradma** [MISP/MISP#4214]
# Need support debuging MISP push

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | MISP not pushing events
| OS version (server)       | CentOs7
| OS version (client)       | Ubuntu
| PHP version               | 5.4
| MISP version / git hash   | 2.4.101
| Browser                   | If applicable

### Expected behavior
Each time I click on push all, all the events matching with the desired tags must be pushed.

### Actual behavior
When I click on Push All, no event is pushed, and the only feedback I get is under Audit > List logs.

There I can see the next message: 

> 0 events pushed or updated. 20 events failed or didn't need an update.

In this case I expected to push much more than 20 events. Also, on the other hand I must say that if I try to pull the events of the external misp works correctly.

Also I've been checking the connexion between both MISP with tcpdump and they see each other.
### Steps to reproduce the behavior

I'm not really sure about how to reproduce exactly the issue, we have just cloned our internal MISP and configured it as an external MISP.

### Logs, screenshots, configuration dump, ...

When I run the connection test it works perfectly:
![misptint-test](https://user-images.githubusercontent.com/15791908/53338208-6db87100-3903-11e9-9996-9998a5211c34.png)

This is the configuration we have for the sync server in our internal MISP:
![mispint- servconf](https://user-images.githubusercontent.com/15791908/53338253-8759b880-3903-11e9-9178-4e90ae53b8a2.png)

And this are the only useful logs I've been able to find:
![mispint-logs](https://user-images.githubusercontent.com/15791908/53338283-95a7d480-3903-11e9-925f-5613a61dc88d.png)

**Comment by adulau** [comment]
Are you the creator organisation of the modified events?

**Comment by Kradma** [comment]
Yes @adulau , I am the creator organisation, and also my org is set as the push rule one on "Events with the following organisations allowed". What puzzles me is that if I follow logic, there are at least 1000 events to upload, but when I do a push, nothing is sent. Also the other strange thing is that if I pull the data from the external MISP (to the internal one) it sends its data correctly so I think it's not a visibility problem.

I've followed the this method to create the sharing server and user:
1. I have created one internal org. called MISP-External on my internal server.
2. I have duplicated that internal org. as the main MISP org. on my external server, and then I've created a new sync user of that organisation on the external one.
3. Then with the api key of that sync user I've configured the sync server (on my internal MISP).
 
Finally, I've configured the sync server to send all the tlp:white events belonging to the main org or to a secondary one that we have on our MISP.

Thanks in advance.

**Comment by Kradma** [comment]
(Internal MISP) Resque logs when I try to push events:
 

> **==> resque-2019-03-06.log <**==
> [2019-03-06 13:24:09] main.INFO: got {"queue":"default","id":"73ea3e1bb1d9aee0292b1200e4095701","class":"ServerShell","args":[["push","64","2","3694"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"73ea3e1bb1d9aee0292b1200e4095701\",\"class\":\"ServerShell\",\"args\":[[\"push\",\"64\",\"2\",\"3694\"]]})","worker":"SRV1:12507"} []
> [2019-03-06 13:24:09] main.INFO: Processing ID:73ea3e1bb1d9aee0292b1200e4095701 in default {"type":"process","worker":"SRV1:12507","job_id":"73ea3e1bb1d9aee0292b1200e4095701"} []
> [2019-03-06 13:24:18] main.INFO: done ID:73ea3e1bb1d9aee0292b1200e4095701 {"type":"done","job_id":"73ea3e1bb1d9aee0292b1200e4095701","time":9521,"worker":"SRV1:12507"} []


(External MISP) misp.local_access.log
> 192.168.1.7 - - [06/Mar/2019:13:23:30 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:31 +0100] "POST /events/filterEventIdsForPush HTTP/1.1" 200 781 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:31 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:32 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:32 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:32 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:33 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:33 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:34 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:34 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:34 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:35 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:35 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:36 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:36 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:36 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:37 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:37 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:37 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:38 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:38 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:39 +0100] "GET /servers/getVersion HTTP/1.1" 200 38 "-" "CakePHP"
> 192.168.1.7 - - [06/Mar/2019:13:23:39 +0100] "POST /events/index HTTP/1.1" 200 2 "-" "CakePHP"

(Internal MISP) Nothing is recorded under the error logs when I try to push events. The last records there are:

> **error.log**
> 2019-03-06 12:41:03 Error: [MissingViewException] View file "Events/ajax/event_lock.ctp" is missing.
> Exception Attributes: array (
>   'file' => 'Events/ajax/event_lock.ctp',
> )
> Request URL: /events/checkLocks/2109
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('/Events/ajax/ev...')
> #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render('/Events/ajax/ev...', NULL)
> #2 /var/www/MISP/app/Controller/EventsController.php(5219): Controller->render('/Events/ajax/ev...')
> #3 [internal function]: EventsController->checkLocks('2109')
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
> #7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #8 {main}
> 2019-03-06 12:41:08 Error: [MissingViewException] View file "Events/ajax/event_lock.ctp" is missing.
> Exception Attributes: array (
>   'file' => 'Events/ajax/event_lock.ctp',
> )
> Request URL: /events/checkLocks/2109
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('/Events/ajax/ev...')
> #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render('/Events/ajax/ev...', NULL)
> #2 /var/www/MISP/app/Controller/EventsController.php(5219): Controller->render('/Events/ajax/ev...')
> #3 [internal function]: EventsController->checkLocks('2109')
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
> #7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #8 {main}
> 2019-03-06 12:41:13 Error: [MissingViewException] View file "Events/ajax/event_lock.ctp" is missing.
> Exception Attributes: array (
>   'file' => 'Events/ajax/event_lock.ctp',
> )
> Request URL: /events/checkLocks/2109
> Stack Trace:
> #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('/Events/ajax/ev...')
> #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(963): View->render('/Events/ajax/ev...', NULL)
> #2 /var/www/MISP/app/Controller/EventsController.php(5219): Controller->render('/Events/ajax/ev...')
> #3 [internal function]: EventsController->checkLocks('2109')
> #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
> #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
> #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
> #7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #8 {main}
>

**Comment by Kradma** [comment]
Problem solved, I had misunderstood the functioning of the distributions, all the events where in "this community only" rather than in "connected communities".
Thanks a lot for your support.
