### ISSUE TITLE
"request has been black-holed" when installed in subdir

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#423]
I have MISP installed in a subdirectory. When I try to login I get the message
"The request has been black-holed Error: The requested address '/misp/users/login?url=users%2Flogin' was not found on this server." When switching to an install without subdirectory (documentroot set to /var/www/MISP/app/webroot/) MISP is fully functional.

What are the correct .htaccess or config settings to get it working in a subdirectory?

Apache:

```
DocumentRoot /var/www/html/
Alias /misp /var/www/MISP/app/webroot
```

MISP/app/webroot/.htaccess:

```
  RewriteEngine On
  RewriteBase /misp
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]
```

I tried setting this in MISP/app/webroot/index.php but no luck either.

```
define('WEBROOT_DIR','misp');
define('BASE_URL','misp');
```

**Comment by iglocska** [comment]
Hello,

just to clarify: 

What you are looking for is having:

www.mysite.com -> something non-misp
www.mysite.com -> misp

Is this correct?

If so, I'll have a look haven't tried to set it up that way yet.

Best regards,
Andras

**Comment by cudeso** [comment]
Hi Andras,

In fact it should be
site.tld/MISP1 -> misp1
site.tld/MISP2 -> misp2
site.tld/MISP3 -> misp3
site.tld/xxx -> something none MISP

Ideally I'd also setup synced servers between 1&2 and 1&3.

Thanks,

koen

**Comment by elhoim** [comment]
If the plan is to handle multiple communities for selectively sharing,
there is a feature that should come in v2.4 (planned april/may IIRC) that
allows to selectively share some data with entities or group of entities.

**Comment by iglocska** [comment]
Indeed, also running several instances of MISP on the same server is highly
advised against because of the way the background workers work!

> site.tld/MISP -> misp
> site.tld/xxx -> something none MISP

This should be fine though, I'll look into it how to get it working.

**Comment by elhoim** [comment]
Do I mark it as wontfix because the v2.4 is sufficient for the described use or does it still needs fixing?

**Comment by elhoim** [comment]
No answer, closing.

**Comment by adulau** [comment]
Reopen on request of a user.
