### ISSUE TITLE
Update MISP 

### ISSUE THREAD

**Issue by WednesdayAd** [MISP/MISP#4232]
Hello.
I have some mistakes with version PyMISP after update MISP to v2.4.102. How can I return PyMISP to the 2.4.93?

```
Advanced attachment handler
The advanced attachment tools are used by the add attachment functionality to extract additional data about the uploaded sample.
pydeep:… OK
lief:… OK
magic:… OK
pymisp:… Please install pymisp: pip install pymisp
STIX and Cybox libraries
Mitre's STIX and Cybox python libraries have to be installed in order for MISP's STIX export to work. Make sure that you install them (as described in the MISP installation instructions) if you receive an error below.
If you run into any issues here, make sure that both STIX and CyBox are installed as described in the INSTALL.txt file. The required versions are:
STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
maec: 4.1.0.14
STIX2: 1.1.1
PyMISP: >2.4.93
Other versions might work but are not tested / recommended.

Current libraries status…Some of the libraries related to STIX are not installed. Make sure that all libraries listed below are correctly installed.
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
STIX2 library version…OK
PYMISP library version…Incorrect PyMISP version installed, found 0, expecting >2.4.93
GnuPG
This tool tests whether your GnuPG is set up correctly or not.

GnuPG installation and settings…OK
ZeroMQ
This tool tests whether the ZeroMQ extension is installed and functional.

ZeroMQ settings…ZeroMQ script not running.
```

**Comment by SteveClement** [comment]
Do not roll back to prior versions of PyMISP when your Core is newer.
That will result in issues.

Your issue is that you have done some manual magic that broke some parts of the system.

As you did not use the proposed template we have no clue what operating system you are using, thus we cannot help debug this properly.

**Comment by WednesdayAd** [comment]
I have instaled MISP Core on Ubuntu 18.04 using script 

> curl  -fsSL https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.debian.sh | bash -s -- -c -M

Before strating script I have created user `misp`  and completed installation under this user. Installation was completed successful. After install this way i have problems with ZeroMQ and pymisp.

![image](https://user-images.githubusercontent.com/47720601/53548689-d178af00-3b3a-11e9-881b-e6d0359afaee.png)

**Comment by SteveClement** [comment]
Ok, I see, I will reproduce this.

Maybe there is a bug in the installer for Core-only.

If that is the case I will let you know how to fix it!

**Comment by SteveClement** [comment]
@WednesdayAd thanks for testing, you might have found a Bbbuggg :)

**Comment by SteveClement** [comment]
Hmmm, I have a different issue ...

My misp-modules do not install :(

Can you try this:

```
cd /var/www/MISP/PyMISP
sudo -H -u www-data /var/www/MISP/venv/bin/pip install .
```

**Comment by WednesdayAd** [comment]
When  I used 

> sudo -H -u www-data /var/www/MISP/venv/bin/pip install

I had error

_ERROR: You must give at least one requirement to install (see "pip help install")_

and than I tried

> apt  install python-pip

something has been installed :). But nothing has changed

![image](https://user-images.githubusercontent.com/47720601/53726121-01df8680-3e76-11e9-9be4-8eb11662f66d.png)

**Comment by SteveClement** [comment]
Arg, ok, you really need to copy paste what I wrote you.

You typed:

```
sudo -H -u www-data /var/www/MISP/venv/bin/pip install
```

BUT you should type:

```
sudo -H -u www-data /var/www/MISP/venv/bin/pip install .
```

And please do not just copy paste this now but make sure you are in the PyMISP directory.

**Comment by WednesdayAd** [comment]
I have same good results :)
![image](https://user-images.githubusercontent.com/47720601/54033069-02e91e80-41bc-11e9-933e-8ce4db1d4fcf.png)
and not good with GnuPG, ZeroMQ, Cortex module system
![image](https://user-images.githubusercontent.com/47720601/54033103-185e4880-41bc-11e9-9cb7-1e9c04b272e2.png)

**Comment by WednesdayAd** [comment]
I managed to fix the situation with the module Cortex.  But with ZeroMQ I have some problem.
After executing the commands according to the settings instruction of ZMQ https://www.circl.lu/doc/misp/misp-zmq/
`sudo pip install pyzmq`
`sudo pip install redis`
install was successful but on the page of Diagnostics not so good
![image](https://user-images.githubusercontent.com/47720601/54086559-0fec4600-4353-11e9-92e6-9bebd2e5157c.png)
![image](https://user-images.githubusercontent.com/47720601/54086566-209cbc00-4353-11e9-9c87-798ca15be3a1.png)

and in mispzmq.error.log 

![image](https://user-images.githubusercontent.com/47720601/54086686-5bebba80-4354-11e9-87ac-fac06e5f5052.png)
But redis module was install.
Tell me please what I'm doing wrong.

**Comment by SteveClement** [comment]
Dear

I highly suggest you familiarize yourself with the concept of Python virtual environments: https://docs.python.org/3/tutorial/venv.html

Further try to lookup what it means if you install a python package, locally, globally or via an OS managed tool like apt/yum/rpm etc.

This is out of our scope at the moment, we cannot give that level of support with such a small team.

Nevertheless feel free to join the MISP-Support group on gitter: https://gitter.im/MISP/Support

**Comment by WednesdayAd** [comment]
All this errors fixed after reinstall MISP).

**Comment by iglocska** [comment]
Thanks a lot for the feedback!

**Comment by WganMe** [comment]
yum install jq jq-devel oniguruma oniguruma-devel zeromq3 zeromq3-devel -y
which jq
ldd /usr/bin/jq
sudo pip3 install pyzmq
sudo pip3 install redis
cd /var/wwwMISP/PyMISP
sudo -H -u userHERE /var/www/MISP/venv/bin/pip install .
cd /var/www/MISP/tools/misp-zmq
python3 -u sub.py  | jq .
