### ISSUE TITLE
Misp Update Issue

### ISSUE THREAD

**Issue by MichaelHuys** [MISP/MISP#4234]
Hi,

currently I'm trying to upgrade my MISP instance (version 2.4.86) installed on Red Hat Enterprise Linux Server release 7.5.
I first had a permission issue (.git folder) which I was able to solve by changing all permissions to the apache user recursively:

chown -R apache:apache /var/www/MISP

During the second try I received an output with all green text so I was under the impression that my update was succesful. But I don't see it reflected in the status bar logged on to my MISP instance. Still version 2.4.86 is displayed.

When I click the update button right now I receive below message:

git pull origin  2>&1

You asked to pull from the remote 'origin', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

=================================

git submodule init && git submodule update 2>&1___

Any idea how I can proceed with my update?

Kind regards,

Michael

**Comment by iglocska** [comment]
```
git checkout 2.4
git pull origin 2.4
git submodule update --init --recursive
```

**Comment by iglocska** [comment]
That should resolve it for you!

**Comment by MichaelHuys** [comment]
Hi,
so far so good but when I run the "git submodule update --init --recursive" command it fails with below error:

fatal: reference is not a tree: 469d17bceeed65373da3ac3b4f96600dfea8ca68
Unable to checkout '469d17bceeed65373da3ac3b4f96600dfea8ca68' in submodule path 'cti-python-stix2'

Please find the entire output in attachment.

Kind regards,

Michael
[Output.txt](https://github.com/MISP/MISP/files/2918496/Output.txt)

**Comment by iglocska** [comment]
`git submodule sync`

Then run it again please, should fix it. We ended up forking the STIX2 library, forgot about that.

**Comment by MichaelHuys** [comment]
Hi,
indeed, now we're on the latest version. Many thanks for the help!
Michael
