### ISSUE TITLE
git fatal: reference is not a tree

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#4236]
Not sure what I've done but I've messed up the upgrade somewhere
I usually do this 
```
$ sudo -i
$ cd /var/www/MISP
$ git pull origin 2.4
$ git submodule update --init --recursive
```
But now for some reason I'm getting this error 
```
root@misp:/var/www/MISP# git submodule update --init --recursive
fatal: reference is not a tree: 469d17bceeed65373da3ac3b4f96600dfea8ca68
Unable to checkout '469d17bceeed65373da3ac3b4f96600dfea8ca68' in submodule path 'cti-python-stix2'
```
I'm also getting this with git status
```
root@misp:/var/www/MISP# git status
HEAD detached from v2.4.87
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cti-python-stix2 (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

Is there anything I can do?  Thanks!

**Comment by SteveClement** [comment]
Well, if you run commands as the root user, things will break.

Reset the permissions: https://misp.github.io/MISP/INSTALL.ubuntu1804/#5-set-the-permissions

Then depending on what platform you are actually on you want to update the repository as the apache/nginx/yourWebsers user.

Also, there is a reason the MISP User Interface has a diagnostics page with an update button ;)

As you did not use the proposed template we have no clue what operating system you are using, thus we cannot help debug this properly.

**Comment by mathurin68** [comment]
Ech man really screwed it up this time... thought it was just something easy I was doing.  Hah, no worries, let me try to reset the permissions.  

Also, I did try the diagnostics that was the first one that all of a sudden said 'HEAD detached' 

I'll roll back the snapshot and play with it.   If I still have the problem I'll fill out the template.

**Comment by iglocska** [comment]
HEAD detached can be fixed with 

```
git checkout 2.4
```

**Comment by mathurin68** [comment]
Alright, closing this to open a proper ticket with OS version etc.
