### ISSUE TITLE
Update through browser, currently not on a branch

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#4245]
Trying to correct problems with not being on a branch. 

### Work environment

PHP Version (>7.0.16 recommended): 7.0.33-0ubuntu0.16.04.1 (Up to date)
PHP CLI Version (>7.0.16 recommended): 7.0.33-0ubuntu0.16.04.1 (Up to date)

Currently installed version… v2.4.102 (35b1db4746cf1057138ecf2149408c2bc16cb385)
Latest available version… v2.4.102 (f13b664563efdbe56b6acb963dcea89090185266) 

Firefox 

### Expected behavior
Want to switch to properly updating through browser

### Actual behavior
Problem:  
Currently installed version… v2.4.102 (35b1db4746cf1057138ecf2149408c2bc16cb385)
Latest available version… v2.4.102 (f13b664563efdbe56b6acb963dcea89090185266)
Status… OK
Current branch… You are not on a branch, Update MISP will fail 

### Logs, screenshots, configuration dump, ...
I've rerun permissions, etc with the following command 
find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP/
chown -R www-data:www-data /var/www/MISP/

 git status
HEAD detached at v2.4.102
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   ../../INSTALL/dependencies/Console_CommandLine (modified content)
        modified:   ../../INSTALL/dependencies/Crypt_GPG (modified content)
        modified:   ../../INSTALL/dependencies/Net_GeoIP (modified content)
        modified:   ../../Plugin/DebugKit (modified content)
        modified:   ../../PyMISP (modified content)
        modified:   ../Lib/cakephp (modified content)
        modified:   ../Lib/random_compat (modified content)
        modified:   ../files/misp-galaxy (modified content)
        modified:   ../files/misp-objects (modified content)
        modified:   ../files/noticelists (modified content)
        modified:   ../files/taxonomies (modified content)
        modified:   ../files/warninglists (modified content)
        modified:   ../../cti-python-stix2 (new commits, modified content)

Hah, appreciate any suggestions even if it's to just totally redo the whole server.

**Comment by mathurin68** [comment]
Also reran permissions with this - 
  sudo chown -R www-data:www-data /var/www/MISP
  sudo chmod -R 750 /var/www/MISP
  sudo chmod -R g+ws /var/www/MISP/app/tmp
  sudo chmod -R g+ws /var/www/MISP/app/files
  sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp

**Comment by adulau** [comment]
On what branch are you at? Could you just checkout to 2.4 branch?

**Comment by SteveClement** [comment]
@mathurin68 try:

```
cd /var/www/MISP
sudo -u www-data git stash
sudo -u www-data git checkout 2.4
```

And checkout the WebUI

**Comment by ktneely** [comment]
Hey @mathurin68, I had the same problem and this closed issue solved it for me: https://github.com/MISP/MISP/issues/4234
Specifically, the `git submodule sync` command fixed the problem.

**Comment by SteveClement** [comment]
@ktneely thanks for the pointer.
