### ISSUE TITLE
Mitre attack matrix UI missing

### ISSUE THREAD

**Issue by nyx0** [MISP/MISP#4246]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.3 LTS
| OS version (client)       | macOS, windows 7, Linux
| PHP version               | 7.0.30
| MISP version / git hash   |  v2.4.102 (c69969329d197bcdd04832b03310fa73f4eb7155)
| Browser                   | Safari, Chrome, FF

### Expected behavior

MITRE ATT&CK Matrice should appear when adding a galaxy

### Actual behavior

There is no MITRE ATT&CK button

### Steps to reproduce the behavior

add a galaxy > All namespaces > no button MITRE ATT&CK

### Logs, screenshots, configuration dump, ...

![screen shot 2019-02-28 at 3 32 28 pm](https://user-images.githubusercontent.com/1841500/53597489-529e6900-3b70-11e9-961f-a1daadfc3a79.png)

**Comment by iglocska** [comment]
![image](https://user-images.githubusercontent.com/3668672/53600300-88137880-3ba9-11e9-9a69-fb1f076215c2.png)

**Comment by nyx0** [comment]
My bad I wasn't clear maybe =)
![screen shot 2019-02-28 at 4 42 38 pm](https://user-images.githubusercontent.com/1841500/53600661-17079d00-3b78-11e9-8b87-ca9344db86b7.png)
This button is missing

**Comment by iglocska** [comment]
Just update your galaxy definitions:

list galaxies -> update

If that doesn't help, first pull in the latest submodules

`git submodule init --update --recursive`

and then update the galaxies.

**Comment by nyx0** [comment]
it works sync issue in the submodule
