### ISSUE TITLE
CakePHP Version

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4261]
Getting error:
Error: Connection test failed. Reason: "Unable to perform enableCrypto operation on CakeSocket" 

I'm trying to connect to vendor supplied MISP instance.

Tested with my own internal instance.  Ubuntu 16.04 and latest version of MISP. 
Recieved error: Error: Connection test failed. Reason: "Unable to perform enableCrypto operation on CakeSocket" 

Tested with a MISP instance I put out on digital ocean.
Used my old install notes.  Ubuntu 16.04 and latest version of MISP. 
Connected just fine. 

Built an new internal MISP instance to try with the Ubuntu 18.04 installation. 
Recieved error: Error: Connection test failed. Reason: "Unable to perform enableCrypto operation on CakeSocket" 

Tested to see if new internal server would work with old internal server. 
Connected just fine. 

I'm trying to see if the CakePHP versions are somehow different. 
However, I can't seem to find the version of Cake.
I've researched some articles and did find this in the /var/www/MISP/app folder:

{
    "prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "kamisama/cake-resque": "4.1.2"
    },
    "suggest": {
        "elasticsearch/elasticsearch": "For logging to elasticsearch",
        "aws/aws-sdk-php": "To upload samples to S3"
    },
    "config": {
        "vendor-dir": "Vendor"
    }
}

However, that's cake-resque.
Either way, I'm completely unfamiliar with Cake.
Also dug throught raw 18.04 install bash script, but only found references to cake-resque. 

How do I check CakePHP versions?
Or, is cake-resque the version I should be concerned with?

Jimbo

**Comment by ghost** [comment]
I believe I found it through this command:  git submodule status
Should be at version 2.10.9-6
If someone could please confirm this is the correct information that would be great. 
See below:

-Switchboard:/var/www/MISP/app# git submodule status
 40fca1d3dabbbb23e13b333bd5c615ca19d7d73f ../INSTALL/dependencies/Console_CommandLine (v1.2.2-1-g40fca1d)
 bf07ab51207446ed33ea0075083df9bbc2358617 ../INSTALL/dependencies/Crypt_GPG (v1.4.0b4-124-gbf07ab5)
 5ccc654f03086febbec95e3358b7bae80ca9af6f ../INSTALL/dependencies/Net_GeoIP (heads/trunk)
 8649a612001fa1caee82d9c432b8223cef221104 ../Plugin/DebugKit (2.2.8-4-g8649a61)
 166ef3866dfefbc2456a394b55fb5f9819f257b8 ../PyMISP (v2.4.103)
 ab5578dbc9f88e661d2b017489cd156fca961429 Lib/cakephp (2.10.9-6-gab5578dbc9)
 088c04e2f261c33bed6ca5245491cfca69195ccf Lib/random_compat (v2.0.2)
 f2159bfaa39c6b5c3243b96c823cdcabcf01ddff files/misp-galaxy (remotes/origin/restructure-1274-gf2159bf)
 d0886ba6aff1526868efcd59fccb99e920372f3b files/misp-objects (heads/master)
 028f569e26b5b47286167b7d39f81cd1791eb04e files/noticelists (heads/master)
 8b57a1bf144e6cfb9a65d7c15cba3ff1eccbc103 files/taxonomies (remotes/origin/init_tax_cccs-63-g8b57a1b)
 2b6b07b28a2937f658accc2f7eeb825396b8120c files/warninglists (2b6b07b)
 469d17bceeed65373da3ac3b4f96600dfea8ca68 ../cti-python-stix2 (v1.0.3-257-g469d17b)
 8622be9f3074ead2e315803aac94eec6f16461b5 ../misp-vagrant (8622be9)

**Comment by SteveClement** [comment]
For your reference.

```
40fca1d3dabbbb23e13b333bd5c615ca19d7d73f INSTALL/dependencies/Console_CommandLine (v1.2.2-1-g40fca1d)
 bf07ab51207446ed33ea0075083df9bbc2358617 INSTALL/dependencies/Crypt_GPG (v1.4.0b4-124-gbf07ab5)
 5ccc654f03086febbec95e3358b7bae80ca9af6f INSTALL/dependencies/Net_GeoIP (heads/trunk)
 8649a612001fa1caee82d9c432b8223cef221104 Plugin/DebugKit (2.2.8-4-g8649a61)
 166ef3866dfefbc2456a394b55fb5f9819f257b8 PyMISP (v2.4.103)
 ab5578dbc9f88e661d2b017489cd156fca961429 app/Lib/cakephp (2.10.9-6-gab5578dbc9)
 088c04e2f261c33bed6ca5245491cfca69195ccf app/Lib/random_compat (v2.0.2)
 f2159bfaa39c6b5c3243b96c823cdcabcf01ddff app/files/misp-galaxy (heads/master-60-gf2159bf)
 d0886ba6aff1526868efcd59fccb99e920372f3b app/files/misp-objects (remotes/origin/HEAD)
 028f569e26b5b47286167b7d39f81cd1791eb04e app/files/noticelists (heads/master)
 bb9cf757ed648786e424b9e2624905a7d0372aa5 app/files/taxonomies (remotes/origin/HEAD)
 d24febd23c17dc7c330672dd0a5b03e0d9ea6248 app/files/warninglists (remotes/origin/HEAD)
 469d17bceeed65373da3ac3b4f96600dfea8ca68 cti-python-stix2 (v1.0.3-257-g469d17b)
 8622be9f3074ead2e315803aac94eec6f16461b5 misp-vagrant (8622be9)
```

**Comment by ghost** [comment]
Hey Steve - 
Thanks for that. 

We found that it was definitely in the certificate configuration file. 
So one server is on older install instructions for 16.04. 
The other was using the new instructions. 
For whatever the reason there were differences in the cert (self-signed and signed) configs. 
We commented out a few things and Bingo! Bango! it all worked just fine. 
Noting those errors though for cakephp to be related to the cert config...at least for the installs that I have done. 

Jimbo
