### ISSUE TITLE
Correlation found is a float...

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#427]
It seems that there are some "half" correlations found ;-)

~~~~
Correlations found
    21687.5 
~~~~

**Comment by iglocska** [comment]
What the hell... That could happen in theory, though it shouldn't - the correlations table consists of 2 correlation entries for each correlation (from attribute A to B and then from B to A). This could happen if for whatever reason one of the entries is missing. There used to be a bug that could cause issues with the correlation but that was way, way back in 1.x or 2.0 or something. 

There is a tool that purges and then rebuilds the correlations from scratch. It is under admin tools -> generateCorrelation, you can access it as a site admin, but prepare for it to take a long, long time.

**Comment by elhoim** [comment]
Seems to be solved on CIRCL's MISPpriv instance.

Can I close?

Should this tool also be run after de-duplication of UUIDs from https://github.com/MISP/MISP/commit/a93807439d987543aa4f1b5e1d5479f6e0c83b55 ?

**Comment by iglocska** [comment]
No need to re-run it for the de-duplication, the de-duplication method deletes items using the regular model deletes, which will always trigger the appropriate changes in correlation.
