### ISSUE TITLE
Retrieve event list ordered and paginated via REST

### ISSUE THREAD

**Issue by alper** [MISP/MISP#4270]
It seems like the only things I can pass to `/events/index` are the things listed in:

```php
 $overrideAbleParams = array('all', 'attribute', 'published', 'eventid', 'datefrom', 'dateuntil',
  'org', 'eventinfo', 'tag', 'tags', 'distribution', 'sharinggroup', 'analysis', 'threatlevel', 'email',
  'hasproposal', 'timestamp', 'publishtimestamp', 'publish_timestamp', 'minimal');
```

I would like to be able to send something like `limit` and `page` and `order` in there as well so as to be able to walk the entire event list over the API. I see the code later does use those parameters to build a query.

Could those params be added to the overridable set? Or is there some other way to achieve what I want to do?

**Comment by iglocska** [comment]
Should be fixed now, thanks.
