### ISSUE TITLE
Schedule task error

### ISSUE THREAD

**Issue by peka8** [MISP/MISP#4274]
I have an Issue with "Scheduled Tasks" menu; 

| OS version (server)       | Ubuntu 17.10
| Browser                   | Chrome

![image](https://user-images.githubusercontent.com/35296639/53819886-1a7d9880-3f6b-11e9-8893-44319f765b70.png)

I can not schedule any activity because I receive the error shown in the image below.

### Actual behavior
![image](https://user-images.githubusercontent.com/35296639/53820270-b4454580-3f6b-11e9-9f6f-4bb9ac09397e.png)

Could you help me solve the problem? Thank you

**Comment by SteveClement** [comment]
I do not see an error, only a warning.

And you did not schedule the fetch feeds.

**Comment by SteveClement** [comment]
It will only schedule if the next run is in the future. FYI.
Double check your servers time.

**Comment by iglocska** [comment]
> It will only schedule if the next run is in the future. FYI.
> Double check your servers time.

This shouldn't be the case, it should auto fast forward. With that said, the scheduler is trash, use cron jobs instead, all of those tasks are exposed to the CLI.
