### ISSUE TITLE
Comparison between get_attributes_statistics and pymisp.search

### ISSUE THREAD

**Issue by itaykrk** [MISP/MISP#4278]
Hi,
I'm trying to understand why there is a difference in the numbers between 
pymisp.get_attributes_statistics() 
and 
pymisp.search(contoller='attributes', type_attribute='attribute_type')

Statistics always returning a greater number than the search. why is that?

**Comment by iglocska** [comment]
The statistics is running a simlper query without ACL to get a rough
estimate of the data volume. Search actually returns the data (so here we
already use the ACL).

**Comment by itaykrk** [comment]
So if I'm using the global admin user i should get the same number right?

**Comment by iglocska** [comment]
Yes, though not sure if the attribute statistics for example handles the exclusion of soft deleted attributes. But in theory yes.

**Comment by SteveClement** [comment]
Thanks for reaching out, feel free to re-open if this is still an issue.
