### ISSUE TITLE
Empty /servers/serverSettings page

### ISSUE THREAD

**Issue by RHormiere** [MISP/MISP#428]
Hello,

I have just installed MISP locally. The installation finished successfully (except that I couldn't install CakeResque) and i can play with events, etc.

However, when I try to access *Administration > Server Settings* page to complete configuration, it is totally empty (blank page with no header nor footer).

`/app/tmp/logs` folder is **empty**, and `/var/log/apache2/misp.local_error.log` contains no new error.

I tried a second installation without success.

Could it be linked to the fact I didn't install CakeResque ? (I understand it's just for workers, so I don't see the link).
Is this a known issue ? I am missing something obvious ? 

I was not able to see something related to this error in current reported issues, so, I'm asking for help !

Thanks in advance,

R.H

**Comment by RHormiere** [comment]
After looking at how Cake is working, i'm able to define the issue more precisely.

It appears that the controller doesn't rend the view `server_settings.ctp`. 
By replacing the content of `add.ctp` by `server_settings.ctp`, i was able to display the *Server Settings* view. So the problem don't come from the view, but from the Controller, which doesn't rend `server_setting.ctp` at the end of `serverSettings()` function.

Any idea why the rendering doesn't work ?

**Comment by iglocska** [comment]
I'll try to look into this soon, but what I suspect happens: Server
Settings runs diagnostics on the installed plugins, including CakeResque.
It probably simply fails on that, though it should handle it more
gracefully.

**Comment by iglocska** [comment]
One thing you could try is editing config.php in /var/www/MISP/app/Config
and flipping "MISP.background_jobs" to false. This will also disable the
worker check. Let me know if that doesn't solve the issue!

**Comment by RHormiere** [comment]
Thanks a lot for the answer, that actually solved my problem ;-)

Best regards
R.H

**Comment by iglocska** [comment]
Excellent news! :)
