### ISSUE TITLE
Describing distribution level in the query builder

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#4280]
Describing distribution level in the query builder

**Comment by mokaddem** [comment]
Do you mean that the field `distribution` is missing from the available parameters?

**Comment by iglocska** [comment]
It just shows up as a number, would be nice to have a text value instead of 0-5 in the builder :)

**Comment by mokaddem** [comment]
How I see.. Was looking at ``restSearch``... Sure it's doable ;)

**Comment by iglocska** [comment]
<3
