### ISSUE TITLE
MISP - Using Cloud Hosted Environment - Very Slow, Not Performing Well - Recommendations?

### ISSUE THREAD

**Issue by debkobza** [MISP/MISP#4283]
Need MISP community help.  

We have installed MISP in a cloud hosted environment, provided by Rackspace/Amazon.  

Results - MISP is running incredibly slow. 

In that the database is large and complex, and when it is installed in a cloud environment, it simply is not performing well.

Any comment mitigations or recommendations?

**Comment by iglocska** [comment]
Most of the time it's down to tuning / correct configuration, we know of quite a few organisations running MISP in such an environment. To get an idea of what sort of a data-set you're dealing with, could you provide some metrics on the number of attributes and correlations? They should be available via the statistics page (global actions -> statistics).

**Comment by SteveClement** [comment]
@debkobza and also the specs of the Cloud configuration?

Ram/CPU/DiskSpace etc...
