### ISSUE TITLE
Schedule Tasks automation (works, but produces lots of error-messages)

### ISSUE THREAD

**Issue by pettai** [MISP/MISP#4284]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | N/A
| PHP version               | Stock Ubuntu 7.2
| MISP version / git hash   | 2.4.102
| Browser                   | N/A

### Expected behavior

Console Task automation works but produces lots for error messages (from git?) 

### Actual behavior

Works, but produces lots of lines :
`fatal: not a git repository (or any of the parent directories): .git`

### Steps to reproduce the behavior

Install a MISP installation using the ubuntu18.04 guide https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.ubuntu1804.md (probably not the current version)

### Logs, screenshots, configuration dump, ...

```
root@misp:~# sudo -u www-data bash /var/www/MISP/app/Console/cake Server pull 2 2 full

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

[...]

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Pull completed. 46 events pulled, 0 events could not be pulled, 0 proposals pulled.
```

**Comment by iglocska** [comment]
It sounds like you messed up with the file permissions / probably updated misp via the command line as root. Please fix the file permissions for your .git directory (/var/www/MISP/.git).

**Comment by iglocska** [comment]
```
chown -R www-data:www-data /var/www/MISP/.git
```

Should get you sorted.

**Comment by pettai** [comment]
It's already owned by www-data:www-data 

```
ubuntu@misp:~$ sudo ls -ld /var/www/MISP/.git
drwxr-x--- 9 www-data www-data 4096 Feb 12 14:12 /var/www/MISP/.git
ubuntu@misp:~$ sudo find /var/www/MISP/.git -ls | grep root
ubuntu@misp:~$ sudo find /var/www/MISP/.git -ls | grep -v www-data
```

So this must be something else...
