### ISSUE TITLE
Setting attribute timestamp in the past

### ISSUE THREAD

**Issue by geekscrapy** [MISP/MISP#4287]
I am going through a transition to move an intel db to MISP. A requirement of this is to transition the date that an IOC was added to the database.

I am able to set the date a the Event level, however this cannot be done at the Attribute level. As it says in the comment: https://github.com/MISP/PyMISP/blob/b8759673b91e733c307698abdc0d5ed82fd7e0de/pymisp/abstract.py#L151

Would a workaround for this be to set the OS clock back for the initial import?!

**Comment by SteveClement** [comment]
Dear @geekscrapy, setting the OS clock back is NEVER a good idea on a server. A lot will go wrong.

It also seems that you can force the timestamp.

If you need more support feel free to open.
