### ISSUE TITLE
restSearch pagination performance

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4289]
2.4.102

Hello... question re' `restSearch` `page`+ `limit` keys...

Does the server perform the query for the full dataset requested, and then only pass back that `page` + `limit` or does it constrain the db lookup based on `page` + `limit`?

My experiments seem to indicate that a query which produces a large dataset result that may hit `max_time_execution` still times out when only requesting `page:1` + `limit:10`. I had to further restrict the query with interactive time slices with `from` + `to`.

I was hoping the server side db query would be constrained by `page` + `limit` to reduce execution time; however, seems to only spread the network traffic into segments.

Perhaps I am missing something?

**Comment by github-germ** [comment]
Any insight would be greatly appreciated.

**Comment by iglocska** [comment]
Does the server perform the query for the full dataset requested, 


No.
