### ISSUE TITLE
Disallow hashes of empty files

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#429]
Empty files generate a static known hash
It would be good to disallow those values at the validation stage of attributes.

For example for md5: d41d8cd98f00b204e9800998ecf8427e

**Comment by iglocska** [comment]
We have are blocking that via regex entries (as a site admin, go to Input
filters -> import regexp). Just create an entry with d41... in the regexp
field and leave the replacement field blank.

**Comment by elhoim** [comment]
Could it be added to the default import of data (and maybe to an upgrade script) so that it does not require admins to do it manually.

**Comment by elhoim** [comment]
Could we find a way to insert it by default for new installs but also for existing installs, so that admins don't have to add them manually.

Loki IOC Scanner has a [code snippet](https://github.com/Neo23x0/Loki/commit/8fb49fb5b459c7c297e25843afb08e04bf79dd52) to filter out md5/sha1/sha256 hashes of empty files

**Comment by iglocska** [comment]
Sure, I can enforce it via the build in validation if you want. Can there
be no case where the creation of an empty file can be of interest?

**Comment by elhoim** [comment]
From my point of view, those only happen because of problems of acquisition of files in the forensics process or in the analysis process.
If it is empty, it can't be malicious... :)

**Comment by iglocska** [comment]
Makes sense, I'll add it!

**Comment by Rafiot** [comment]
Fixed by the warning lists.
