### ISSUE TITLE
/img/custom/LOGO Error 

### ISSUE THREAD

**Issue by commander1** [MISP/MISP#4295]
Os: ubuntu
MISP version 2.4.103

When logging in -- 
Error: The requested address '/img/custom/MISP' was not found on this server.

- I believe this img was uploaded for an internal organization. However, that organization has been removed. 
- The dir /var/www/MISP/app/webroot/img/ cleaned --removed 

Issue remains

What other locations are used to store uploaded IMG >png

**Comment by SteveClement** [comment]
If this is still an issue, please re-open.
