### ISSUE TITLE
Setting base URL does not ask user

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4298]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, support
| OS version (server)       |ubuntu 18.04.2 server
| OS version (client)       | 10
| PHP version               | Not there yet
| MISP version / git hash   | 2.4
| Browser                   | If applicable

### Expected behavior
To request user to input the MISP_BASEURL

### Actual behavior
![image](https://user-images.githubusercontent.com/9196526/54272318-6ad5a580-45be-11e9-81e5-296a72963586.png)

### Steps to reproduce the behavior
Just follow the steps here https://misp.github.io/MISP/INSTALL.ubuntu1804/ 
The one talking about installing on a fresh ubuntu

### Logs, screenshots, configuration dump, ...
as attached above

**Comment by dharshanduck** [comment]
managed to install the platform, however i feel that this is a bug it did not prompt user input, straight went into installation

**Comment by SteveClement** [comment]
This was an issue with how to run the installer, fixed in documentation.
