### ISSUE TITLE
Cannot add "template editor" right to role

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#430]
It is a v2.2 upgraded to v2.3 latest hotfix (55).

I can edit a role, check the box to add the "template editor" right, and it saves fine, but it does not show up in the list of rights for that role.

I am site admin, and in the group admin.

**Comment by iglocska** [comment]
This is probably because MISP has the previous datamodel still cached. Make sure that you delete the cached models when you upgrade (basically it doesn't know about the new column)

**Comment by elhoim** [comment]
Indeed it was this.

Thanks!
