### ISSUE TITLE
Enrichment event window doesnt fit in the screen

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4307]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.2 LTS server
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/54417010-f0329480-473b-11e9-8edd-72ab41a01696.png)
| Browser                   | Firefox, Chrome

### Expected behavior
For the box to fit the screen and if its too big for the screen, to then include scrollbar. Even with many modules enabled.

### Actual behavior
With many Enrichment modules enabled, it does not display correctly as shown in the screenshot below.

### Steps to reproduce the behavior
1) Enable enrichment Modules
2) Turn on many modules (modules >=20) depending on your screen size.
3) Create a test event and include attributes.
4) Choose enrich event. 

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/9196526/54416632-ed836f80-473a-11e9-9996-1cc1988489f5.png)

Zooming out using the browser seems to allow the window to fit.
![image](https://user-images.githubusercontent.com/9196526/54417098-2a039b00-473c-11e9-9f4e-e1a575082498.png)

**Comment by smclinden** [comment]
To add to this, you cannot scroll, either, which means that if you cannot shrink the contents of the window to reach the Enrich button, you are stuck. Also, there is no box at the top to close the display.

**Comment by iglocska** [comment]
ok, that's just outright dumb. We need to switch that to the modern modals.
