### ISSUE TITLE
Syntax error: name 'yara' is not defined

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4317]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | Ubuntu 18.04.2 LTS server
| OS version (client)       | 10
| PHP version               | 7.2 
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/54458869-fd816a80-479f-11e9-965c-1c3427825d11.png)
| Browser                   | Firefox, Chrome

### Expected behavior
For the Yara modules to work and provide information/yara querries

### Actual behavior
![image](https://user-images.githubusercontent.com/9196526/54458929-26096480-47a0-11e9-976c-3165a1332d9d.png)
![image](https://user-images.githubusercontent.com/9196526/54459006-61a42e80-47a0-11e9-806a-6a810a231022.png)

### Steps to reproduce the behavior
Install misp-modules as guided for python virtualenvironment
Attempt to run enrichment for yara_query
Hover mouse over existing yara query for yara syntax validation

### Logs, screenshots, configuration dump, ...
as shown above

**Comment by adulau** [comment]
It seems you are missing the yara-python dependency. Did you install it your Python virtualenv?

**Comment by dharshanduck** [comment]
![image](https://user-images.githubusercontent.com/9196526/54502065-c065d580-4963-11e9-90a8-f6d9afeb9d35.png)


I believe that it is installed

**Comment by dharshanduck** [comment]
@adulau any advice/suggestions?

**Comment by SteveClement** [comment]
This is a potential bug. Investigating on my side.

**Comment by dharshanduck** [comment]
Got it.

**Comment by SteveClement** [comment]
Git pull and try again, this might have fixed it: https://github.com/MISP/MISP/commit/fc1f15c4c01c6a22fa589158709d09002e842542

**Comment by dharshanduck** [comment]
i dont think it did 
![image](https://user-images.githubusercontent.com/9196526/57345419-5b697780-717d-11e9-9fc5-a33f25693831.png)

ran git pull on misp-modules, ran pip install requirements from venv on that directory, and still getting the above.
![image](https://user-images.githubusercontent.com/9196526/57345494-a2f00380-717d-11e9-8667-eeac04ce92fb.png)

**Comment by SteveClement** [comment]
@dharshanduck as mentioned on gitter:

try:
```bash
$ sudo -u www-data /var/www/MISP/venv/bin/python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> print(yara.__version__)
3.8.1
```

**Comment by dharshanduck** [comment]
Here's the output
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Failed to import '/var/www/MISP/venv/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin;/v                                           ar/www/MISP/venv/lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/MISP/venv/lib/python3.6/site-packages/yara/__init__.py", line 7                                           , in <module>
    from yara.rules import compile
  File "/var/www/MISP/venv/lib/python3.6/site-packages/yara/rules.py", line 17,                                            in <module>
    from yara.libyara_wrapper import *
  File "/var/www/MISP/venv/lib/python3.6/site-packages/yara/libyara_wrapper.py",                                            line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /var/www/MISP/venv/lib/libyara.so: cannot open shared object file: No s                                           uch file or directory
```
checking the directory it is indeed missing, 
```
/var/www/MISP/venv/lib$ ls -la
total 12
drwxr-x--- 3 www-data www-data 4096 Mar 13 18:38 .
drwxr-x--- 9 www-data www-data 4096 May  3 11:43 ..
drwxr-x--- 5 www-data www-data 4096 Mar 13 18:38 python3.6
```
however pip has it:
```
misp@misp:~$ sudo -u www-data -H /var/www/MISP/venv/bin/pip list |grep yara
plyara                 2.0.2
yara                   1.7.7
yara-python            3.8.1
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
misp@misp:~$ sudo -u www-data -H /var/www/MISP/venv/bin/pip3 list |grep yara
plyara                 2.0.2
yara                   1.7.7
yara-python            3.8.1
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
 what am i missing here :(

**Comment by SteveClement** [comment]
Do:

```bash
sudo -u www-data -H /var/www/MISP/venv/bin/pip uninstall yara
```

and try again.

**Comment by dharshanduck** [comment]
So while uninstalling i found this 
```
sudo -u www-data -H /var/www/MISP/venv/bin/pip uninstall yara
Uninstalling yara-1.7.7:
  Would remove:
    /var/www/MISP/venv/bin/yara-ctypes
    /var/www/MISP/venv/lib/python3.6/site-packages/var/www/MISP/venv/lib/libyara.so
    /var/www/MISP/venv/lib/python3.6/site-packages/yara-1.7.7.dist-info/*
    /var/www/MISP/venv/lib/python3.6/site-packages/yara/*
Proceed (y/n)? y
  Successfully uninstalled yara-1.7.7
```

notice `/var/www/MISP/venv/lib/python3.6/site-packages/var/www/MISP/venv/lib/libyara.so` i dont think thats supposed to be there, but i uninstalled anyway and then reinstalled from the requirements file using pip from the venv

importing yara into python cli works
```
 sudo -u www-data /var/www/MISP/venv/bin/python
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> print(yara._version_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'yara' has no attribute '_version_'
>>> print(yara.__version__)
3.8.1
>>>
```
how ever i still get this error from attempting to query an enrichment for hash value in yara.
![image](https://user-images.githubusercontent.com/9196526/57828495-45436300-77de-11e9-9cb4-fd71738215c3.png)

**Comment by SteveClement** [comment]
This is end-of-the-line for me. I do not know what else to check.

/cc @chrisr3d @adulau @iglocska

**Comment by chrisr3d** [comment]
@dharshanduck just to be sure, did you restart your misp-modules ?

I had some issues with yara as well a couple of weeks ago, so I removed `yara` from the list of libraries installed. What @SteveClement did with `uninstall yara` to keep only `yara-python` is supposed to fix the import issue, and if you have no issue anymore using python or ipython and executing `import yara`, I don't see what else could go wrong

**Comment by dharshanduck** [comment]
Hey guys so the yara enrichment query works, after upgrading to the latest commit of misp, and redoing everything suggested by @SteveClement Thanks for the help yall :D

Now there seems to be problem with yara export, but im currently outstation, Maybe ill open a new issue, not before getting ideas from the gitter though
