### ISSUE TITLE
Warning lists not providing warnings in MISP 2.4.103

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4318]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       |  Ubuntu Server 18.04.1
| PHP version               | 7.2.15-0ubuntu0.18.04.1
| MISP version / git hash   | 2.4.103
| Browser                   | Version 72.0.3626.109 (Official Build) (64-bit)

### Expected behavior
Warning list icon added to IoC

### Actual behavior
Warning list icon is not added to IoC

### Steps to reproduce the behavior
1.) add attribute (or do free text import) "8.8.8.8" and flag it "for IDS"
2.) save 

### Logs, screenshots, configuration dump, ...
<img width="1410" alt="Screenshot 2019-03-17 at 10 58 46 AM" src="https://user-images.githubusercontent.com/9201937/54488644-77028100-48a4-11e9-9cef-673c63440730.png">

Don't mind the message box near the sighting, I got stuck on that "hover-after-click" bug :D

**Comment by iglocska** [comment]
Hmph, it works for me. Do you have the warninglists enabled?

![image](https://user-images.githubusercontent.com/3668672/54489821-c5b61800-48b0-11e9-8e8d-20907fad505b.png)

**Comment by ghost** [comment]
That's weird. Suddenly every warning list I have set to "Enabled" this morning was set to initial position (un-checked). Dunno what have I done in the meantime, but yes - no warninglists was enabled. After enabling, everything was back to normal. Thank you!

**Comment by dharshanduck** [comment]
Hi there, i cant seem to find the settings for the warning lists anywhere. hope you guys can point me in the right direction
