### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by GuillemGG** [MISP/MISP#4319]
Hello everyone!
I'm trying to install a fresh new misp on aws using an EC2 instance and a RDS DB. As I wanted to use the RDS on another instance, I didn't use the AMI from the MISP community because the install manual didn't take into account connecting to another db. 

I added the config file on the end of the issue for more information. The redirect from 80 to 443 works. 

What am I missing?

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian
| OS version (client)       | -
| PHP version               | 7.0
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | chrome/firefox

### Expected behavior
Fresh install on a new EC2 instance. Connected to the db successfully from the MISP instance and everything seems fine, but when I try to log in on the UI it returns a 404 error. Using port 80 it redirects to the 443, as configured on the misp-ssl.conf. The 404 is on port 443.

### Logs, screenshots, configuration dump, ...
Config file:
![image](https://user-images.githubusercontent.com/11855280/54491017-47ab3e80-48bb-11e9-8b73-0cdb753961d6.png)

Access logs example:
![image](https://user-images.githubusercontent.com/11855280/54491138-4d555400-48bc-11e9-9c03-06b11efe9936.png)

Error log example:
![image](https://user-images.githubusercontent.com/11855280/54491154-6827c880-48bc-11e9-8dad-104d0ba044bb.png)

I checked many related issues and tried to reproduce the solutions, but none worked. 

Thanks a lot,
GG.

**Comment by GuillemGG** [comment]
I noticed I am using /var/www/misp and on the other closed issues the common route is /var/www/MISP, so I renamed the directory (mv misp MISP) and now it shows a blank page, just an empty body html. 

Both following files look ok:
/var/www/MISP/app/Controller/UsersController.php 
 /var/www/MISP/app/View/Users/login.ctp

Which I read are part of the login handling. 

Further troubleshooting I've done:
The workers are running.
a2enmod rewrite enabled.
Couldn't get anything clear from the logs, even though there aren't many. All the logs I found were for restarting apache and the ones I posted before.
I repeated the part 3 of the install guide:
https://github.com/MISP/MISP/blob/2.4/docs/xINSTALL.debian9.md
But still giving an empty page.

What am I missing?

**Comment by iglocska** [comment]
Please look at both the apache logs as well as the misp logs (found in /var/www/MISP/app/tmp/logs)

**Comment by GuillemGG** [comment]
Thanks for the comment, @iglocska 

Here are the only logs in the folder:
![image](https://user-images.githubusercontent.com/11855280/54494601-640ba300-48dc-11e9-8763-a627056e2c63.png)

Most are empty, as you can see by the size. The ones which have some lines only say:
resque-2019-03-17.log:
![image](https://user-images.githubusercontent.com/11855280/54494613-80a7db00-48dc-11e9-945b-5ee405dc99a5.png)
resqueu-scheduler-2019-03-17.log:
![image](https://user-images.githubusercontent.com/11855280/54494633-b0ef7980-48dc-11e9-92a9-ad3be248af33.png)

Any more logs for troubleshooting?

Thanks!

**Comment by GuillemGG** [comment]
Hello,

It is now giving me the error code 500, so I browsed through all the logs again thinking there will be more stuff and there it is! Looks like there are some classes not installed:
![image](https://user-images.githubusercontent.com/11855280/54526516-522b0e00-4977-11e9-83dd-e8b1b4895243.png)

Looks like it is looking for the old misp route instead the new one named MISP. How can I solve this?

Thanks in advance!

**Comment by SteveClement** [comment]
This is a cake issue.

Which install document are you using?

I would suggest you start somehow afresh because this looks fishy.

also join the MISP Support gitter channel, perhaps some users have achieved what you try.

**Comment by GuillemGG** [comment]
Hello Steve,

Okay, thanks for the advice! I'll start a new one using ubuntu instead of debian. I noticed I was using one which has a warning on it... ^^'
https://github.com/MISP/MISP/blob/2.4/docs/xINSTALL.debian9.md

Thanks for the help.

GG.
