### ISSUE TITLE
An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by WednesdayAd** [MISP/MISP#4320]
Hello.
After following a link [(https://xx.xx.xx.xx/attributes/restSearch/json)] I get an error page with message
![image](https://user-images.githubusercontent.com/47720601/54514720-93b1be00-4963-11e9-8fbe-8790f31d5d96.png)

I will be glad to any help.

**Comment by SteveClement** [comment]
I cannot reproduce this.

Please check the log files:

https://www.circl.lu/doc/misp/administration/#misp-logs

Also make sure you are up to date, current MISP version: 2.4.105
