### ISSUE TITLE
GUI is not loading, apache default page is displayed

### ISSUE THREAD

**Issue by ESL482** [MISP/MISP#4328]
Hi , I have installed misp by following this link in ubutu 16.04:
https://github.com/MISP/MISP/issues/1195

But after doing all the steps they mentioned ,when i came to login page it is showing Apache default page.
and when i opened misp.error.log it showing below error
[Mon Mar 18 17:47:12.002519 2019] [ssl:error] [pid 6853] AH02217: **ssl_stapling_init_cert: can't retrieve issuer certificate!** [subject: emailAddress=admin@domain name,CN=IP_Address,OU=ABC,O=XYZ,L=EC,ST=DEF,C=IN / issuer: emailAddress=admin@DOMAIN=IP,OU=ABC,O=XYZ,L=ZX,ST=DEF,C=IN / serial: EF300CBB8B7D8CBF / notbefore: Mar 18 10:36:52 2019 GMT / notafter: Mar 17 10:36:52 2020 GMT]
[Mon Mar 18 17:47:12.002535 2019] [ssl:error] [pid 6853] AH02604: Unable to configure certificate 10.201.74.11:443:0 for stapling

My misp-ssl.conf (/etc/apache2/sites-available)

ano 2.5.3                     File: misp-ssl.conf                                                 

<VirtualHost Host_IP:80>
    ServerAdmin  mail@abc.com
   ServerName Host_IP
    DocumentRoot /var/www/MISP/app/webroot
    Redirect permanent / https://Host_IP
    <Directory /var/www/MISP/app/webroot>
        Options -Indexes
        AllowOverride all
       # Require all granted
        Order allow,deny
        allow from all
    </Directory>

    SSLEngine On
    SSLCertificateFile /etc/ssl/private/apache-selfsigned.crt
    SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
#   SSLCertificateChainFile /etc/ssl/private/misp-chain.crt

    LogLevel warn
    ErrorLog /var/log/apache2/misp.local_error.log
    CustomLog /var/log/apache2/misp.local_access.log combined

    ServerSignature Off

    </VirtualHost>

..please help me to sort this issue.

**Comment by SteveClement** [comment]
this is the wrong install document.

Consider this one: https://misp.github.io/MISP/INSTALL.ubuntu1804/

On a fresh install this line will install core and modules:

```
curl -fsSL https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.debian.sh | bash -s -- -c -M
```
