### ISSUE TITLE
Bookmark queries in the ReST client

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4331]
- Bookmark queries in the ReST client
- Proposing values depending on the dataset in your MISP instance

**Comment by mokaddem** [comment]
Bookmarking is indeed a good idea!
Could you briefly describe what `proposing values` means as well as its purpose?

**Comment by iglocska** [comment]
I'll take this one ;)

**Comment by mokaddem** [comment]
Will you do the integration with the query builder as well? :wink:

**Comment by iglocska** [comment]
Nope. Afaik it cannot read back any existing queries yet, once you fix that it will work out of the box ;)

Implemented btw.
