### ISSUE TITLE
Internal Error - Automation screen & Unable to generate exports cache

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#4343]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2.15
| MISP version / git hash   | 2.4.103, bcca86c468680b945a32338f5c9e90bfa5c089ab
| Browser                   | Chrome

### Expected behavior
1. To generate export caches when selecting "Generate" from the Export Page
2. Be able to view the Automation page when navigating to <baseurl>/events/automation

### Actual behavior
1. Job fails when attempting to generate cached exports (seemingly all - although Bro export initially worked)
2. Receive "An Internal Error Has Occurred." Error: An Internal Error Has Occurred. when attempting to go to automation screen.

### Steps to reproduce the behavior
1. Attempt to 'Generate' any exports. Looking in the jobs tab these have failed fairly instantly.
2. Attempt to navigate to automation page. With site_admin debug enabled, the error is:

syntax error, unexpected '$this' (T_VARIABLE), expecting ',' or ')'
Error: An Internal Error Has Occurred.

Stack Trace
[internal function] → App::load(string)
APP/Controller/EventsController.php line 2583 → spl_autoload_call(string)
[internal function] → EventsController->automation()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 499 → ReflectionMethod->invokeArgs(EventsController, array)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(EventsController, CakeRequest)
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

Additionally, from /var/www/MISP/tmp/logs/error.log:

2019-03-19 21:15:10 Error: [ParseError] syntax error, unexpected '$this' (T_VARIABLE), expecting ',' or ')'
Request URL: /events/automation
Stack Trace:
#0 [internal function]: App::load('BroExport')
#1 /var/www/MISP/app/Controller/EventsController.php(2583): spl_autoload_call('BroExport')
#2 [internal function]: EventsController->automation()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

### More information
This error occurred on an existing MISP instance, which I upgraded (via server diagnostics) at some point this afternoon, after which these errors started to occur. The automation page had been accessible prior to this (I do not recall if I had previously successful cached the exports).

Additionally, I have built a new box using the automated install script, where this error also occurs upon first log-in (i.e. without any changes to config). As such, it may be that a later commit has impacted this functionality.

**Comment by iglocska** [comment]
Thanks, should be fixed now.

**Comment by JamesSOC080** [comment]
> Thanks, should be fixed now.

@iglocska - thanks, this has resolved the navigation to automation issue.

However, I'm still unable to generate any exports other than the Bro export. Not sure if this perhaps then a separate issue...

When generating the export for JSON as an example, the job states it successfully completes, and the status in the export page is set to "Completed" - but no file has been created. 

Pressing 'Download' results in an error that the file cannot be found - and I've confirmed no file has been created in /var/www/MISP/app/tmp/cached_exports/json).

The output from the worker log, after attempting the JSON generate, is as follows:

[2019-03-20 10:27:00] main.INFO: got {"queue":"cache","id":"70ac3bfbdae3cbc3407c3db46c041dd5","class":"EventShell","args":[["cachebro","1","31","json"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"cache\",\"id\":\"70ac3bfbdae3cbc3407c3db46c041dd5\",\"class\":\"EventShell\",\"args\":[[\"cachebro\",\"1\",\"31\",\"json\"]]})","worker":"misp:4437"} []
[2019-03-20 10:27:00] main.INFO: Processing ID:70ac3bfbdae3cbc3407c3db46c041dd5 in cache {"type":"process","worker":"misp:4437","job_id":"70ac3bfbdae3cbc3407c3db46c041dd5"} []
[2019-03-20 10:27:00] main.INFO: done ID:70ac3bfbdae3cbc3407c3db46c041dd5 {"type":"done","job_id":"70ac3bfbdae3cbc3407c3db46c041dd5","time":319,"worker":"misp:4437"} []

The issue appears for all exports with the exception of the Bro export, which generates the file (and can be downloaded).

Appreciate any help. Thanks in advance.

**Comment by JamesSOC080** [comment]
Just a further thought - the above log shows that, despite running the 'JSON' generate button, it refers to "cachebro". I've confirmed that at 10:27, the Bro cache in /var/www/MISP/app/tmp/cached_exports/bro was modified.

Is it perhaps that the 'generate' buttons on the export page are all linking to the Bro cache?

Testing the theory, when generating the 'XML' export, the Bro cache again was modified at 10:39, with the following entry in the logs at 10:39 mirroring the above export whereby it references the args as "cachebro".
