### ISSUE TITLE
Menu bar when editing events don't work in IE11

### ISSUE THREAD

**Issue by cibermanchego** [MISP/MISP#4354]
Good morning, 
since the update to 2.4.103 we've found some issues in the UI when creating events.
Especifically the menu bar to add/remove Pivots-Galaxy-Event Graph don't work. When you click on the items nothing happens. 
This only happens with Internet Explorer, it works fine in Firefox.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | Windows 7
| PHP version               | 7.1
| MISP version / git hash   | 2.4.103
| Browser                   | Internet Explorer 11

### Expected behavior
when clicking on the menu bar items should be added/removed

### Actual behavior
Nothing happens

### Steps to reproduce the behavior
Create an event with Internet Explorer as browser.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/6847856/54817933-641ef080-4c98-11e9-8633-ff5055774cbd.png)

**Comment by RichieB2B** [comment]
IE11 was released in 2013. I know Microsoft still supports it but that doesn’t mean the rest of the world has to as well. Please consider using a more modern browser.

**Comment by cibermanchego** [comment]
I'm well aware of that. But in some situations IE11 is the only option available.

**Comment by SteveClement** [comment]
If this is an IE11 issue, we do not really support it.

**Comment by cibermanchego** [comment]
It works fine with Firefox, so I guess is IE11 specific. I really understand not supporting IE11. In some places is the only browser available, that's why I opened the issue.

**Comment by mokaddem** [comment]
Hello,
I honestly don't know if it is related or not (haven't tested on IE) but this commit https://github.com/MISP/MISP/commit/c64495d108f5b9090146a385cf4f9865392fbb54 could fix a concurrency issue.

**Comment by mokaddem** [comment]
Feel free to re-open if it's not the case.
