### ISSUE TITLE
MISP slow with highly correlated index page

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4356]
On a clean MISP install I only enabled the `https://www.circl.lu/doc/misp/feed-osint` feed and pulled in all the data. This results in the following statistics:
```
Events 1206
Attributes 242457 
Attributes / event 201 
Correlations found 472693
```
The first event index page of 60 events is very slow to load. The SQL debug show this query takes 6+ seconds:
```
SELECT `Correlation`.`1_event_id`, count(distinct(`Correlation`.`event_id`)) as count FROM `misp2`.`correlations` AS `Correlation` WHERE `Correlation`.`1_event_id` IN (1203, 1198, 1177, 1172, 1168, 1164, 1163, 1157, 1152, 1143, 1140, 1137, 1136, 1124, 1120, 1119, 1115, 1109, 1107, 1106, 1105, 1103, 1098, 1095, 1089, 1086, 1081, 1074, 1072, 1071, 1069, 1062, 1054, 1040, 1014, 1010, 1003, 1000, 996, 992, 991, 984, 981, 980, 962, 961, 957, 955, 953, 946, 931, 930, 923, 922, 916, 912, 910, 911, 900, 890) GROUP BY `Correlation`.`1_event_id`
```

The EXPLAIN of that query is:
```
+----+-------------+-------------+------------+-------+---------------+------------+---------+------+--------+----------+-------------+
| id | select_type | table       | partitions | type  | possible_keys | key        | key_len | ref  | rows   | filtered | Extra       |
+----+-------------+-------------+------------+-------+---------------+------------+---------+------+--------+----------+-------------+
|  1 | SIMPLE      | Correlation | NULL       | index | 1_event_id    | 1_event_id | 4       | NULL | 849330 |    61.42 | Using where |
+----+-------------+-------------+------------+-------+---------------+------------+---------+------+--------+----------+-------------+
```

There are total 3177 correlations on that first page. Page 10 with only 350 correlations is shown instantly.

Adding `FORCE INDEX (1_event_id)` to that query cuts it down to 2 seconds. Do we need https://github.com/cakephp/cakephp/issues/1847 to be able to fix this?

**Comment by iglocska** [comment]
Yeah cakephp's ORM not supporting index hints is quite a blocker at times. There are some dirty ways around it, will look into it. Which version of mysql / mariadb are you on? Surprisingly we've seen some utterly brain-damaged-stupid index choices in some cases by the engine as opposed to more modern versions.

**Comment by JakubOnderka** [comment]
Feed correlation code was updated and it should be faster new. Can you check latest MISP version if the problem is still same?
