### ISSUE TITLE
Organization size is limited to 10 characters in the server list

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#436]
Organization size is limited to 10 characters in the server list which can be an issue when you have organization with a longer name. Especially that the restriction is not the same in the other org fields. It would be wise to move the limit to the same limit that the default size of the organization field in the user forms.

**Comment by iglocska** [comment]
Wow, that's annoying. Updated the MYSQL.sql file and added an admin tool to update it on the fly. 

Just go to Administration -> Administrative tools and click on "Extend Organization length".
