### ISSUE TITLE
Advanced sharing network viewer misplaced on Safari

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#4366]
Advanced sharing network viewer is not shown at the correct place with Safari.
In contrast to some other browsers where it's shown on the right side, it's displayed underneath the attributes - far away from being in line of sight. That's not ideal.

**Comment by mokaddem** [comment]
I'll have a look if I manage to find someone that could lend a MAC for a few minutes. :)

**Comment by mokaddem** [comment]
Should be fixed by now
