### ISSUE TITLE
Trouble syncing via Push "2019-03-25 15:23:11 Error: [MethodNotAllowedException] Invalid JSON input."

### ISSUE THREAD

**Issue by derbananenkoenig** [MISP/MISP#4369]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug? Cannot Sync between Servers
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | 10
| PHP version               | Source Server for pushing:  7.2.10-0ubuntu0.18.04.1 (Up to date) || Target New Server receiving:  7.0.33-0ubuntu0.16.04.2 (Up to date)
| MISP version / git hash   | source: v2.4.102 (c9b70ae50cb620430f9086a5ddf6465529bb8990)  || Target: v2.4.102 (eb0abc44513fc619116be8d1d7b4439ce41b1131) 
| Browser                   | If applicable chrome

### Expected behavior
I had a new Misp Server, that is supposed to receive events. Configured it, setup syncing - unfortunately synced all of the events, except for those that tagged specifically ( missed inserting push rules). Used the Script misp-wipe to clear the instance. Then Setup the Org and Users again, entered them on the Source System by Add Servers as well as the auth-key for the sync user and added push rules. 
Push rules:
Events with the following tags allowed: Redacted
Events with the following organisations allowed: Redacted

Note, i have tried this only with the tags rule and another time with the tag rule + the org rule, since i thought it was unclear if both are needed or it would function when i only enter the tag. 

I do have one single event that has that tag, that i want to be synced. 

### Actual behavior
Not synced and the error log spit out (see lower log section)

Connection test working nicely. 

### Logs, screenshots, configuration dump, ...
Log output from the source server:
==> resque-2019-03-25.log <==
[2019-03-25 16:46:06] main.INFO: got {"queue":"default","id":"1ad8783847cee40469bd0e12f7bbcc0d","class":"ServerShell","args":[["push","12","8","4390"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"1ad8783847cee40469bd0e12f7bbcc0d\",\"class\":\"ServerShell\",\"args\":[[\"push\",\"12\",\"8\",\"4390\"]]})","worker":"misp:1266"} []
[2019-03-25 16:46:06] main.INFO: Processing ID:1ad8783847cee40469bd0e12f7bbcc0d in default {"type":"process","worker":"misp:1266","job_id":"1ad8783847cee40469bd0e12f7bbcc0d"} []
[2019-03-25 16:46:07] main.INFO: done ID:1ad8783847cee40469bd0e12f7bbcc0d {"type":"done","job_id":"1ad8783847cee40469bd0e12f7bbcc0d","time":404,"worker":"misp:1266"} []

log output from the target server:
==> /var/www/MISP/app/tmp/logs/error.log <==
2019-03-25 15:46:32 Error: [MethodNotAllowedException] Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.
Request URL: /events/filterEventIdsForPush
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(201): AppController->_isRest()
#1 /var/www/MISP/app/Controller/EventsController.php(54): AppController->beforeFilter()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

**Comment by iglocska** [comment]
Nice find thanks!

**Comment by iglocska** [comment]
Could you just git pull, log in and try again?

**Comment by keram79** [comment]
just to be on the safe side: The push rules defined above are linked by a logical AND, not by an OR, correct?

**Comment by derbananenkoenig** [comment]
i would also like to know, because it seems confusing.

it says choose tags (or) and ....

Am Do., 28. März 2019 um 06:24 Uhr schrieb keram79 <notifications@github.com
