### ISSUE TITLE
Mitre Attack matrix window too big

### ISSUE THREAD

**Issue by PaoloVecchi** [MISP/MISP#4371]
Adding a mitre-attack pattern, while editing an event it opens a matrix that is too big to fit in a laptop screen.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Visualisation / UX
| OS version (client)       | Ubuntu 18.04
| MISP version / git hash   | 2.4.104
| Browser                   | Firefox 66.01

### Expected behavior
Matrix positions in the middle of the screen with header visible

### Actual behavior
Matrix positions too high and top menu overlaps

### Steps to reproduce the behavior
Use a screen with 1366x768 resolution

**Comment by mokaddem** [comment]
Thanks for the report (and giving the resolution).
By the time it's fixed, you can use the galaxy picker as a replacement instead of the matrix.

**Comment by mokaddem** [comment]
This has been fixed with the improved version of the matrix.
