### ISSUE TITLE
STIX2 1.1.2 installed

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#4378]
Ubuntu 16.04
Currently installed version… v2.4.104 (f4936599b8548e3a52c7771c758fa32c5d7805db) 

I ran 'pip install stix2' and now my web interface shows stix 1.1.2 installed. Looking for recommendations on how to uninstall 1.1.2 and install 1.1.1.

![image](https://user-images.githubusercontent.com/8250365/55021436-ba58a000-4fc6-11e9-96c2-5ad56d795da3.png)

I ran 'pip uninstall stix2' and received back "successfully uninstalled stix2-1.1.2" but the misp web interface still reports the same as the screenshot above thinking stix 1.1.2 is still installed.

**Comment by seifreed** [comment]
Can we get any help from the MISP community here? @iglocska

**Comment by chrisr3d** [comment]
Indeed I forgot to change the value in the diagnostic tool, thanks for reporting it, it is fixed now.

Btw I am pretty sure we are using python3 with this kind of library, so if you want to keep yours up-to-date, I advise you to run `pip3 install -U .` from our fork you can find under `/var/www/MISP/cti-python-stix2` (replace `/var/www/` with your own directory to MISP if you have a different one)

Feel free to reach us again if you have any issue
