### ISSUE TITLE
STIX import issue (MAEC)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4382]
TA17-293A - https://www.us-cert.gov/sites/default/files/publications/TA17-293A%20_TLP_%20WHITE.xml

**Comment by adulau** [comment]
Another great namespace not officially declared

https://github.com/carbonblack/cbfeeds/commit/12b91e1e896ed2b904bc8b72b53fe58fa909ccaa

**Comment by chrisr3d** [comment]
Should be fixed after [7b7ddaa](https://github.com/MISP/MISP/commit/7b7ddaabb9d39f4426a1ae5638f2b38e036b7d63)
