### ISSUE TITLE
export API in OpenAPI

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4384]
export API in OpenAPI

**Comment by frikky** [comment]
Hey, I made a sample OpenAPI specification over here for MISP: https://github.com/frikky/OpenAPI-security-definitions/blob/master/misp.yaml

It uses this script to generate most of it: https://github.com/frikky/OpenAPI-security-definitions/blob/master/tools/misp_generator.py from https://github.com/MISP/misp-book/blob/master/automation/README.md.

**Comment by Wachizungu** [comment]
Hey,

I guess this issue can be closed, since openapi doc exists now?
Just referencing:
- https://www.misp-project.org/2021/06/07/MISP.2.4.144.released.html/
- https://www.misp-project.org/openapi/

**Comment by frikky** [comment]
> Hey,
> 
> I guess this issue can be closed, since openapi doc exists now? Just referencing:
> 
> * https://www.misp-project.org/2021/06/07/MISP.2.4.144.released.html/
> * https://www.misp-project.org/openapi/

Yep! We already have it imported and in use by loads of Open Source + Cloud users &customers on our end too: [https://shuffler.io/apps/misp](https://shuffler.io/apps/misp)

Would the default OpenAPI URL ever change? We will be polling it regularly to look for changes.

**Comment by adulau** [comment]
The one from misp-project.org is supposed to be fixed.
