### ISSUE TITLE
Function to merge same attributes types to a MISP object

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/MISP#4388]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Feature Request
| OS version (server)       | CentOS
| OS version (client)       | 7
| MISP version / git hash   | 2.4.104

### Expected behavior
I suggest to have a WebUI function to merge existing attributes (same type) into a MISP Object.
For example, if you export a case from TheHive to MISP, all IOCs will be added in bulk.
To have a function that merges the one you selected to a new object could be useful.

### Actual behavior
Today, to transform several existing attributes to an object, you must:
1. Add a new object to your event,
2. Copy/paste each attribute you want to add to the object,
3. Finally, remove all duplicate attributes

Not sure to be able to add this feature from scratch, but I can contribute obviously.
Thank you.

Regards,
Julien

**Comment by rommelfs** [comment]
Proposal:

Phase 1: Select attributes to be transformed 
Phase 2: MISP proposes matching objects
Phase 3: modifications 
Phase 4: accept (create object and delete attributes)

**Comment by Tux-Panik** [comment]
Feature embedded in the 2.4.109 release.
