### ISSUE TITLE
/var/www/MISP 100% Full

### ISSUE THREAD

**Issue by MichaelHuys** [MISP/MISP#4395]
Hi,

currently the /var/www/MISP filesystem on my test MISP instance is 100% full. When I compare with my production installation below directory seems to be the culprit:

/var/www/MISP/app/files/scripts/tmp

This folder consists of all subfolder with below content:

-rw-r--r--. 1 apache apache  48M Mar 23 23:05 N6asjUogOWUl
-rw-r--r--. 1 apache apache  20M Mar 23 23:05 vtUVpc1d8ZXk
-rw-r--r--. 1 apache apache    0 Mar 23 23:11 toauIjyObh5G.stix
-rw-r--r--. 1 apache apache  18M Mar 23 23:11 rxM2bDtHn2Wa
-rw-r--r--. 1 apache apache  14M Mar 23 23:11 sCZilbgN6PFu
-rw-r--r--. 1 apache apache  23M Mar 23 23:11 Yjuoru04xRf7
-rw-r--r--. 1 apache apache  23M Mar 23 23:11 QyzlkYqndTqh
-rw-r--r--. 1 apache apache  18M Mar 23 23:11 YFQdYWleSAox
-rw-r--r--. 1 apache apache  48M Mar 23 23:11 fWuUsr7baH9X
-rw-r--r--. 1 apache apache  20M Mar 23 23:11 Y2rOO7n7AiRn
-rw-r--r--. 1 apache apache    0 Mar 24 23:04 AK5N4JzGc4v7.stix
-rw-r--r--. 1 apache apache  18M Mar 24 23:04 kpkHV70KCMxD
-rw-r--r--. 1 apache apache  14M Mar 24 23:04 VF43n9Q4K2Uv
-rw-r--r--. 1 apache apache  22M Mar 24 23:04 7pyZrURzHxiA
-rw-r--r--. 1 apache apache 3.9M Mar 24 23:04 ZRNY3CZJlKaM

Is it safe to delete the content? And how can I prevent that this directory get's filled?

Kind regards,

Michael

**Comment by chrisr3d** [comment]
Hello,

We usually use temporary files like those ones to do many different things.
For instance I see there are some .stix files, so I suppose some STIX 1 or 2 export queries have been processed.
But I just checked on my side, and after each time the STIX scripts are called, the temporary files are deleted which means my '/var/www/MISP/app/files/scripts/tmp' directory remains empty at the end and it should remain empty except if one of the STIX scripts have issues.

As a first step, can you tell me which version of MISP you have ? is your instance up-to-date ?
Also do you have anything in the log file '/var/www/MISP/app/tmp/logs/exec-errors.log' ?

**Comment by MichaelHuys** [comment]
Hello,

apparently this issue is solved by rebooting my MISP instance. This is just FYI. I'll close this issue.

Michael

**Comment by ilmarh** [comment]
@chrisr3d can you help track down script (or maybe scripts), which leaves files in tmp dir? In exec-errors.log i have:
```Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1390, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1387, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 147, in handler
    i = self.__set_identity()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 126, in __set_identity
    identity_class="organization", interoperability=True)
  File "/usr/local/lib/python3.6/dist-packages/stix2/base.py", line 142, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).
```

MISP version  v2.4.113, Submodules status OK, directories and files OK, PHP and extentions OK, libraries:
```
pydeep:… OK
lief:… OK
magic:… OK
pymisp:… OK
STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
maec: 4.1.0.14
STIX2: 1.1.2
PyMISP: >2.4.93
```

**Comment by chrisr3d** [comment]
This issue comes from the stix2 python library.
I guess you do have the right versions installed, but for stix2 we are using our own fork.

Go to the stix2 sub-directory and get the latest version:
`cd /var/www/MISP/cti-python-stix2`
`git pull origin master`

Then check if you have a directory called `venv` within your MISP default directory and run the following:
`sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I .`
Otherwise, use pip3 instead:
`sudo -H -u www-data pip3 install -I .`

I assumed you are using the default MISP location `/var/www/MISP`, but replace with your own one if needed.

MISP is generating a temporary file each time the script is called. This file is representing a MISP event and is passed to the script. If it fails, the php function calling the script is stopped, and the part where the temporary file is deleted will not be executed. This is why you have then a lot of files in tmp dir.

I hope it helps, let me know if anything goes wrong

**Comment by ilmarh** [comment]
```/var/www/MISP/cti-python-stix2# git pull origin master
From https://github.com/MISP/cti-python-stix2
 * branch            master     -> FETCH_HEAD
Already up to date.
```
and i don't have venv, this is dedicated box with old MISP install, which was updated from time to time to the resent version. Right no it is 2.4.113. And i will update it to .114. MISP top directory layout looks like:
```/var/www/MISP# ls -l
total 140
drwxr-x--- 16 www-data www-data  4096 июл  6 11:03 app
-rwxr-x---  1 www-data www-data  2884 июн  5  2018 AUTHORS
drwxr-x---  2 www-data www-data  4096 июн  5  2018 build
-rwxr-x---  1 www-data www-data  3581 июн  5  2018 code_of_conduct.md
-rwxr-x---  1 www-data www-data  7775 июн  5  2018 CONTRIBUTING.md
drwxr-x---  5 www-data www-data  4096 июл 17 09:15 cti-python-stix2
drwxr-xr-x  5 www-data www-data  4096 авг 23 07:18 docs
drwxr-x---  6 www-data www-data  4096 июн  5  2018 format
drwxr-x--- 10 www-data www-data  4096 авг 23 07:18 INSTALL
-rwxr-x---  1 www-data www-data 34520 июн  5  2018 LICENSE
drwxr-x---  2 www-data www-data  4096 июн  5  2018 misp-vagrant
-rw-r--r--  1 www-data www-data  2693 июл 17 07:47 mkdocs.yml
-rw-r--r--  1 www-data www-data   445 июн  6 12:57 Pipfile
-rw-r--r--  1 www-data www-data  5340 июн  6 12:57 Pipfile.lock
drwxr-xr-x  3 www-data www-data  4096 июн  6 12:57 Plugin
drwxr-x--- 10 www-data www-data  4096 авг 23 07:18 PyMISP
-rw-r--r--  1 www-data www-data  9123 июн  6 12:57 README.md
-rw-r--r--  1 www-data www-data   140 июн  6 12:57 requirements.txt
drwxrwxr-x  5 www-data www-data  4096 июн  5  2018 ssdeep-2.13
drwxr-x---  2 www-data www-data  4096 авг 23 07:18 tests
drwxr-x---  7 www-data www-data  4096 авг 23 07:18 tools
drwxr-x---  2 www-data www-data  4096 авг 23 07:18 travis
-rw-r--r--  1 www-data www-data    37 авг 23 07:18 VERSION.json
```

Do i need to read some manual for deploying venv for MISP?
PS. And thank in advance

**Comment by chrisr3d** [comment]
The venv is what we install by default for a couple of months with the recent versions, but MISP is checking if it exists, so if it does not, it uses the python3 package installed on the machine, you do not have to worry about that.

> sudo -H -u www-data pip3 install -I .

Did you execute this one ? Once you are within the cti-python-stix2 directory you just need to update the python library with this command.

When you get the right version of this python library, it should stop filling the tmp directory with files (at least the stix2 script should stop doing that). If it still does, then we will watch again what is written in exec-errors.log

**Comment by ilmarh** [comment]
Oh, i misread your explanations first time, sorry.
pip3 installed some packages:
`Successfully installed antlr4-python3-runtime-4.7.2 certifi-2019.6.16 chardet-3.0.4 idna-2.8 python-dateutil-2.8.0 pytz-2019.2 requests-2.22.0 simplejson-3.16.0 six-1.12.0 stix2-1.1.2 stix2-patterns-1.1.0 urllib3-1.25.3`

I'll check how it worked tomorrow and let you know. Thanks again.

**Comment by ilmarh** [comment]
Nothing changed except tmp files amount (now < 10Gb) and exec-error content:
```Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 151, in handler
    getattr(self, mispTypesMapping[attribute['type']]['to_call'])(attribute)
KeyError: 'named pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1390, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1387, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 153, in handler
    self.add_custom(attribute)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 458, in add_custom
    class Custom(object):
  File "/var/www/.local/lib/python3.6/site-packages/stix2/v20/sdo.py", line 374, in wrapper
    return _custom_object_builder(cls, type, _properties, '2.0')
  File "/var/www/.local/lib/python3.6/site-packages/stix2/custom.py", line 13, in _custom_object_builder
    class _CustomObject(cls, STIXDomainObject):
  File "/var/www/.local/lib/python3.6/site-packages/stix2/custom.py", line 18, in _CustomObject
    "characters a-z (lowercase ASCII), 0-9, and hyphen (-)." % type,
ValueError: Invalid type name 'x-misp-object-named pipe': must only contain the characters a-z (lowercase ASCII), 0-9, and hyphen (-).
```

Can you give some directions what shell i try next?

**Comment by chrisr3d** [comment]
Ok for this one, it is just the script failing, I am going to fix it now because it is a specific attribute type that is not mapped. 

I will tell you soon when it is fixed

**Comment by chrisr3d** [comment]
The last issue you had should now be fixed with the latest changes.

if you have anything else popping the exact same way, with an error message in exec-error.log, just poke me again either here or in a new issue where you can @ me
