### ISSUE TITLE
Att&ck matrix broken after recent updated round #2

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#4397]
Please see:
~~~
https://github.com/MISP/MISP/issues/4393
~~~
So....my process for updating has been:

cd /var/www/MISP
git pull origin 2.4
git submodule update --init --force
chown -R www-data:www-data /var/www/MISP/

Iv'e never git pulled/cloned misp-galaxy. I followed:
install

how do I up install/update misp-galaxy? Thank you.

Also, unable to reopen tickets.
![2019-03-28 10_22_41-Att ck matrix appears broken after recent update · Issue #4393 · MISP_MISP](https://user-images.githubusercontent.com/947191/55174808-c322b080-5143-11e9-91fa-00f8ca25063a.png)

**Comment by mokaddem** [comment]
Once you have pulled your ``misp-galaxy`` to the latest version, you can update MISP with the latest version by clicking on the ``update galaxies`` button.
![image](https://user-images.githubusercontent.com/6977223/55217322-8a481180-51ff-11e9-9776-a3693ab3278e.png)

**Comment by DigiAngel** [comment]
Thank you @mokaddem ...looks like git submodule update --init --force does the pull instead of manually pulling...that and the Force Update Galaxies did the trick :)
