### ISSUE TITLE
Installation behind proxy fails

### ISSUE THREAD

**Issue by seldem** [MISP/MISP#4404]
Hi, 
I have been trying to install MISP to a Ubuntu 18.04 box which is behind a proxy.  I use the second curl command here https://misp.github.io/MISP/INSTALL.ubuntu1804/ . Installer goes well until core components install phase.  Then I get connection timeout messages. According to logs these commands does not go to proxy. 

My proxy settings are like below:
How can I continue this part of installation? Please help.

_ >cat /etc/apt/apt.conf
Acquire::http::Proxy "http://myproxy:8080";
Acquire::https::Proxy "https://myproxy:8080";_

_>env | grep proxy
export https_proxy=http://myproxy:8080
export http_proxy=http://myproxy:8080_

_>cat .wgetrc
http_proxy = http://myproxy:8080/
https_proxy = http://myproxy:8080/
use_proxy = on
wait = 15_

_git config --global http.proxy http://myproxy:8080
git config --global https.proxy http://myproxy:8080__

_Installing setuptools, pkg_resources, pip, wheel...done.
mkdir: cannot create directory â/var/www/.cache/â: File exists
Cloning into 'python-cybox'...
fatal: unable to access 'https://github.com/CybOXProject/python-cybox.git/': Failed to connect to github.com port 443: Connection timed out
Cloning into 'python-stix'..._

![Untitled](https://user-images.githubusercontent.com/36921239/55325647-5a626d80-548e-11e9-967f-49b567ff2282.png)

**Comment by seldem** [comment]
After several trials and errors, finally installation completed, but using proxy is somewhat troubled. Every component like curl, git, pip requires its own proxy settings defined. In additon to them SSL certificate problems sometimes pops up. This issue can be closed.

**Comment by SteveClement** [comment]
I will add a feature to the installer main issue.

**Comment by user4913** [comment]
Has this feature been added, I can't see any reference to configuring a proxy in the main installer?
