### ISSUE TITLE
Issue with MISP Certificate

### ISSUE THREAD

**Issue by bhuvan2099** [MISP/MISP#4405]
Hi Guys,

I recently installed MISP instance in my lab for testing the threat Intel feeds functionality. I'm planning to use the threat feeds in Hive instance which is a incident response solution, also installed on one of my lab VM's.

I have successfully integrated MISP and Hive but the MISP feeds are not getting imported to Hive solution because of the lack of certificate on the MISP instance. I'm running a lab environment and do not have a certificate authority to get the certificate part done. I have tried to use letsencrypt as mentioned on the link <https://github.com/MISP/MISP/issues/951> with no success since letsencrypt is used for providing certificates for public domains.

I don't have the budget to purchase private domain certificates from verisign or some other CA's.

Can some pls assist me on how do i proceed with the installing a valid certificate on my MISP instance.

Below are few details which might be helpful.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16
| OS version (client)       | Seven
| MISP version / git hash   | 2.4.100

**Comment by iglocska** [comment]
Not sure if the hive allows you to skip the SSL checks, but if not:

https://letsencrypt.org/ <- grab a certificate there for free

**Comment by iglocska** [comment]
Some info on how to get started:

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04

**Comment by bhuvan2099** [comment]
Hi iglocska,

I already tried using letscrypt and it gave me the below error. It seems letscrypt can be used to obtain certificates for public domain only and they require a registered public domain. Our is an internal instance used for test purposes.

![image](https://user-images.githubusercontent.com/49153798/55329340-f9499280-54ab-11e9-9f91-0df45357a7b0.png)

![letscrypt](https://user-images.githubusercontent.com/49153798/55329405-1bdbab80-54ac-11e9-9130-578e32bd5a8c.PNG)

Please suggest.

Regards

**Comment by bhuvan2099** [comment]
Hi,

The issue has been resolved and can be closed. The workaround was to remove https redirect and self signed certificate from MISP. Once on http everything syncs up.

Regards

**Comment by dharshanduck** [comment]
Hi, there is an alternative method, where you go to the application.conf  in thehive and put this at the top
`play.ws.ssl.loose.acceptAnyCertificate = true`  then at least you will have https running

**Comment by SteveClement** [comment]
Thanks for everyone involved.

**Comment by hojatifar** [comment]
> Hi, there is an alternative method, where you go to the application.conf in thehive and put this at the top
> `play.ws.ssl.loose.acceptAnyCertificate = true` then at least you will have https running

thanks a lot you save my time

**Comment by forghani77** [comment]
Second  solutions would be using mkcert to generate crt and key files in your local machine , then put those on misp virtual machine or misp docker.
Here is a great resource to do that:
https://pandora.sh/posts/deploy-misp-with-https/

But If you're using Misp virtual machine, and even, you solve the certificate problem it won't integrate with TheHive for some reason. 
So you have no choice but to install misp docker instead.
I test both and that was what I've got.
