### ISSUE TITLE
Add Tag to Event throws Error "Could not add Tag"

### ISSUE THREAD

**Issue by chrissommer** [MISP/MISP#4406]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Win 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.105

Clicking on the little + Button, brings the TAG selection - you select the TAG and click on Submit

### Expected behavior
Tag gets added to the Event.

### Actual behavior
Red Error on the bottom of the Screen (Could not add Tag)

### Steps to reproduce the behavior
Try to Add a Tag to an Event

### Logs, screenshots, configuration dump, ...
Dump of the Error Log shows, that the Request was BlackHoled:

2019-04-01 12:26:58 Error: [BadRequestException] The request has been black-holed
Request URL: /events/addTag/157735
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by iglocska** [comment]
Interesting, it's the second time we get this report in the past 2 days but I am having a hard time reproducing it, so I wonder what's different on my end. Could you try to force refresh the page to reload the cached javascript? (ctrl+f5 in chrome).

**Comment by chrissommer** [comment]
Hi,

Great - adding the Tag with Chrome works fine - only Firefox throws the Error. Even after clearing all Browser Data, and a new Login. Seems to be a browser related problem :)

Thank you for your help & BR
Chris

**Comment by iglocska** [comment]
Wow, ok that is weird. I'll give it a spin with the red panda.

**Comment by RichieB2B** [comment]
Very strange indeed. It is not for all tags. The above error triggers not 100% of the time but too often to be workable. We are using Firefox and can't install Chrome here. After ctrl+F5 it seems a little better until the issue returns.

Reverting back to v2.4.103 fixed this issue. 104 is also broken.

**Comment by iglocska** [comment]
Wow, ok digging into it. Weird.

**Comment by iglocska** [comment]
Hmph, I can't seem to be able to reproduce it. Wonder how I could force running into the same bug.

**Comment by iglocska** [comment]
@RichieB2B - could you share what version of firefox you're running and what addons you're using? Also, if you're up for it we could have a conf call to see if we can find a way to reproduce it / do a live debug session.

**Comment by RichieB2B** [comment]
We are running the latest ESR version (currently FF 60): https://www.mozilla.org/en-US/firefox/organizations/
I'll try to reproduce it in our test environment, then we can do a live debug session.

**Comment by iglocska** [comment]
Perfect, thanks! I'm refactoring some of the tagging code in the meanwhile, see if I can stumble on something.

**Comment by RichieB2B** [comment]
Using FF 66.0.2 I get a bunch of CSP
<img width="1217" alt="Screenshot 2019-04-03 12 40 48" src="https://user-images.githubusercontent.com/1461970/55473125-22823400-560e-11e9-9aa1-93a44bf8b60d.png">
 errors now and the + button for adding tags does nothing. 
After disabling `security.csp.enable` I get a bunch of ReferenceErrors and js that fail to load and eventually when I click the + button `popoverPopup` is not defined:
<img width="791" alt="Screenshot 2019-04-03 12 47 00" src="https://user-images.githubusercontent.com/1461970/55473392-ec917f80-560e-11e9-8c36-0d14b1787d50.png">
The failed *.js load fine when requested directly.

**Comment by RichieB2B** [comment]
I can't reproduce this on my test server with FF 60.6.1esr. Pretty weird..

**Comment by iglocska** [comment]
WTF

**Comment by iglocska** [comment]
Could you share your apache conf file? Just to see if you're using any directives that we don't that might add to the issue (via encrypted mail would be fine too ofc)

**Comment by iglocska** [comment]
Or show us the headers set, that would work too.

**Comment by RichieB2B** [comment]
I fixed the JS issue.. FF had NoScript installed, duh. I did not have any headers in apache.conf but now I added:
```
        Header always set X-Content-Type-Options nosniff
        Header always set X-Frame-Options DENY
        Header always unset "X-Powered-By"
```

**Comment by iglocska** [comment]
OK, noscript would explain it :) That was our suspicion at first, @adulau
had the same thing happen once with noscript.

**Comment by iglocska** [comment]
Are you still having the black hole issues with it disabled?

**Comment by RichieB2B** [comment]
No, I can't reproduce the blackhole-on-tagging issue on my test instance. I'm reluctant to test it again in production. Adding tags is core business there.

**Comment by SteveClement** [comment]
@chrissommer let us know if it reoccurs.

**Comment by RichieB2B** [comment]
I now see this happening on our test system running the latest commit 25d8d6cf94e4c25ea28bd166285a7c7389678b7b
Care to log in and take a look?

**Comment by mpurzynski** [comment]
I'm getting errors when trying to add a tag.

2019-06-07 09:39:49 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/addTag/4155714
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(AttributesController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by RichieB2B** [comment]
Which browser are you using? My problem went away after I switched from Firefox to Chrome.

**Comment by mpurzynski** [comment]
Firefox Nightly, I tested in Chrome stable and it works. How do we debug it further?

**Comment by mpurzynski** [comment]
Does not work from FF stable

**Comment by RichieB2B** [comment]
@iglocska is looking into a solution that works with Firefox as well

**Comment by iglocska** [comment]
Currently I need a way to reproduce it. Running Firefox (67.0) it all works as expected.

**Comment by iglocska** [comment]
It should be fixed now. Rejoice!

**Comment by RichieB2B** [comment]
\o/ thanks!

**Comment by iglocska** [comment]
Thanks for the help <3

**Comment by marcnil815** [comment]
Experiencieng the same problem with safari when addint attributes.
It happens randomly (worst kind).

Stack trace:
2019-11-14 14:02:50 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/add/125
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(AttributesController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by marcnil815** [comment]
Bah. Didn't see this was closed. Opening a new case.
