### ISSUE TITLE
running git submodule update causes error

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4407]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.2 LTS server
| OS version (client)       | 10
| PHP version               | 7.2.15
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/55380796-e094b780-5553-11e9-8813-75c9356eeb9c.png)
| Browser                   | Chrome

### Expected behavior
To update all the modules successfully

### Actual behavior
Running the update causes a couple errors such as permission denied and something about stash.
`misp@misp:/var/www/MISP$ sudo -u www-data git submodule update
warning: unable to access '/home/misp/.config/git/attributes': Permission denied
warning: unable to access '/home/misp/.config/git/ignore': Permission denied
error: Your local changes to the following files would be overwritten by checkout:
        tests/testlive_comprehensive.py
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '64bcaad0e578129543cdffad532a232722615f6c' in submodule path 'PyMISP'
`

Running the command `git submodule update` gives a permission denied error as below
`misp@misp:/var/www/MISP$ git submodule update
fatal: Unable to create '/var/www/MISP/.git/modules/PyMISP/index.lock': Permission denied
Unable to checkout '64bcaad0e578129543cdffad532a232722615f6c' in submodule path 'PyMISP'
`

### Steps to reproduce the behavior
Just run submodule update from CLI

**Comment by dharshanduck** [comment]
I have sorted out the permissions by running 
`sudo chown -R www-data:www-data .git`

However the submodules still fail to update.
![image](https://user-images.githubusercontent.com/9196526/55468687-81f43a00-5636-11e9-8200-0304b35c4d23.png)

**Comment by dharshanduck** [comment]
Issue resolved with recent updates by @mokaddem

**Comment by mathurin68** [comment]
How?
