### ISSUE TITLE
Fetch Feed not working after event ID is changed

### ISSUE THREAD

**Issue by shanto12** [MISP/MISP#4412]
Openphish feed fetch not working after changing the event id to a different one. the configuration is as follows.

Enabled: Yes
Caching Enabled: Yes
Target Event: Fixed Event
Exclusion Regex: Null
Auto Publish: No
Override IDS Flag: No
Delta Merge: Yes

Everything else is default. i tried all combinations of configurations but the feed is not getting fetched and stored in the new event

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 16.04.4
| PHP version               | 7.2.15
| MISP version / git hash   | 2.4.103 

### Expected behavior
Feed should be fetched and stored in the new event provided.

### Actual behavior
the jobs gets completed sucessfully when i click on fetch feed. but no attributes or values added to the new event

### Steps to reproduce the behavior
1. Create event 1
2. Change openphish feed to have target event as fixed event
3.  Add the event from step 1 to the Target Event ID feild
4. Fetch Feed. Everything works well and feed is fetched.
5. Create event 2
6. Delete event 1
7. Add event 2 to the Target Event ID field and save the fetch
8. Fetch feed again 
9. but this time nothing happens. job gets completed successfully. But no information is added to event 2

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/1020247/55461896-5034a080-5641-11e9-85c7-0d19294e3003.png)
![image](https://user-images.githubusercontent.com/1020247/55461900-56c31800-5641-11e9-8c66-27a1ba23dafa.png)

**Comment by shanto12** [comment]
Finding the below warning whenever I run the feed fetch from GUI. Log location:/var/www/MISP/app/tmp/logs/error.log

Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 882]

**Comment by SteveClement** [comment]
The feed system is being re-factored.

Not sure how far @iglocska has come along.

**Comment by JakubOnderka** [comment]
This should be fixed in #5052. Or at least error logs will provide more information what happened.
