### ISSUE TITLE
Number of attributes shows incorrectly for events fetched after update

### ISSUE THREAD

**Issue by MadGeckoo** [MISP/MISP#4414]
For all events fetched after update from 2.4.102 to 2.4.105 number of attributes doesn't show correctly in events list, even though event has attributes. 

You can see number slowly raise while worker fetches attributes, but after it finishes, it shows 0 attributes.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.2 
| OS version (client)       | Win 10
| PHP version               | 7.2
| MISP version / git hash   | dockerized 2.4.105, bb42cf79babb8afcf117ad46dd067ab446a04398
| Browser                   | Chrome

### Expected behavior

Events list shows actual number of atrributes.

### Actual behavior

Events list shows 0 instead of actual number of attributes.

### Steps to reproduce the behavior

1. manually fetch the feed
2. while fetching number of attributes in events list slowly raises
3. after fetching finishes, number of attributes is 0

### Logs, screenshots, configuration dump, ...

Events list
![misp_bug_1](https://user-images.githubusercontent.com/3979652/55469994-05963280-5607-11e9-8243-dc36a37ce600.png)

Event actually has attributes
![misp_bug_2](https://user-images.githubusercontent.com/3979652/55469995-05963280-5607-11e9-9d13-0c4e53770c1a.png)

**Comment by MadGeckoo** [comment]
We found one more discrepancy, this time in older event, where attribute count doesn't match the reality in event. This time event was created on 2019-02-18 and attribute count shows 187 in events list but 194 in the event. 7 attributes were added to the event in the days after the abovementioned update, but attribute count wasn't updated.

Event with ID 1383
![image](https://user-images.githubusercontent.com/3979652/55556451-ec18e780-56e7-11e9-950e-888a168a0055.png)

Different number of attributes
![image](https://user-images.githubusercontent.com/3979652/55556502-136fb480-56e8-11e9-9b1b-30d291aa1efc.png)

**Comment by MadGeckoo** [comment]
I've just built brand new instance from the same docker image. Version of MISP is (v2.4.105 (c484f014498708cc42fc2a02fa0afa0338761aec) ). I have enabled pre-installed Firehol feed and fetched all events from it. Same story. While it fetches attributes number slowly raises. When fetching is finished, number shows as 0 in events list, even though event has attributes.

This is view from the events list:
![image](https://user-images.githubusercontent.com/3979652/55572912-031c0180-5709-11e9-8e64-6f69a931f11b.png)

This is the event itself:
![image](https://user-images.githubusercontent.com/3979652/55572969-1af38580-5709-11e9-8f6e-892d91eb2a55.png)

And these are the logs created by fetching the event:
![image](https://user-images.githubusercontent.com/3979652/55573021-3494cd00-5709-11e9-9161-eb0f6de5e592.png)

I think the row with the ID 4813 has something to do with it.

**Comment by MadGeckoo** [comment]
The incorrect number of attributes shows also if we query the API for event metadata, for example the pictures below.

API response:
![API response](https://user-images.githubusercontent.com/3979652/55587155-045e2600-572b-11e9-99f2-9f2f5f70b5bf.png)

Events list:
![List of events](https://user-images.githubusercontent.com/3979652/55587176-1344d880-572b-11e9-8e0a-f23f86e0ae6c.png)

**Comment by iglocska** [comment]
Should be fixed now, thanks!
