### ISSUE TITLE
MISP backup $PATH_TO_MISP empty 

### ISSUE THREAD

**Issue by tom564** [MISP/MISP#4415]
https://github.com/MISP/MISP/blob/fcca264eb70e17ed3b280200f6f9c50df5700955/tools/misp-backup/misp-backup.sh#L130

Shouldn't this be outside the if statement checking if it needs to revert to manual? having issues with running the backup and believe this to be the cause.

**Comment by tom564** [comment]
https://github.com/MISP/MISP/blob/fcca264eb70e17ed3b280200f6f9c50df5700955/tools/misp-backup/misp-restore.sh#L146 - Looks like the same will be needed for the restore script.

**Comment by SteveClement** [comment]
Thanks for the fix.
