### ISSUE TITLE
Event with 100,000+ attributes loads slowly

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4424]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support, Enhancement
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | 10.
| PHP version               | 7.2.15
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/55555394-c4da0e80-5717-11e9-9257-91a07289813b.png)
| Browser                   | Chrome, Firefox, Edge, IE

### Expected behavior
To be able to load events with huge amounts of attributes under 10 seconds

### Actual behavior
Event(All current domains belonging to known malicious DGAs feed) with 353255 attributes takes about 3+ minutes to load

### Steps to reproduce the behavior
Fetch default(included upon installation) DGA feed http://osint.bambenekconsulting.com/feeds/dga-feed-high.csv  
Cache it. Ensure its a fixed event.
Open said event after fetching.

### Logs, screenshots, configuration dump, ...
php.ini config
![image](https://user-images.githubusercontent.com/9196526/55556313-d7554780-5719-11e9-865f-15c5534889fa.png)

/etc/mysql/mariadb.conf.d/50-server.cnf
![image](https://user-images.githubusercontent.com/9196526/55556934-48e1c580-571b-11e9-9cb5-8755c7b36c58.png)

**Comment by dharshanduck** [comment]
Let me know what else is needed to assist with this

**Comment by github-germ** [comment]
Seems related to https://github.com/MISP/MISP/issues/3632 which was closed being deemed a rather low priority use case. We still see this as an issue...

**Comment by SteveClement** [comment]
It still mostly seems to be an edge-case and the ongoing performance refactoring will eventually also take care of those issues.

**Comment by dharshanduck** [comment]
edge-case?? i dont understand 
performance refactoring on the PHP <-> mariadb?

**Comment by SteveClement** [comment]
Having events with 100k attributes is not common, yet, thus IMHO still an issue a minority might face.
If you have a recurring use-case and you think this would be something that everyone might eventually face, please do share.

It's not only PHP/DB related. There is a lot going on in the background when you add an attribute.

Fundamentally it might seem like a simple task but a lot of gears are grinding when processing an event.

**Comment by github-germ** [comment]
We also have events with > 100k attributes. This is not an edge-case for us.

**Comment by rommelfs** [comment]
Is this issue about viewing an event in the GUI?

**Comment by dharshanduck** [comment]
Ahh, @SteveClement I understand now. Well, the thing is there is one default feed which has 100,000+ attributes `(All current domains belonging to known malicious DGAs feed)`. I strongly agree that not everyone would have this issue. But let us wait and see if the performance and refactoring show improvement.

@rommelfs it's about load times of an event with a large number of attributes.

**Comment by rommelfs** [comment]
What does that mean? 
- Loading an event with 100k+ attributes into MISP?
- Loading an event with 100k+ attributes in MISP via web interface?
- Loading an event with 100k+ attributes from MISP via pyMISP?

**Comment by github-germ** [comment]
* Events with large number of attributes do not paginate well in WebUI. See https://github.com/MISP/MISP/issues/3632
* We have many events with well over 100k attributes. For us, this is mainstream, and not an edge-case.

**Comment by rommelfs** [comment]
Sorry, I'm probably the wrong person to talk to, I don't seem to understand the answer to my question, if that was supposed to be an answer.

**Comment by dharshanduck** [comment]
@rommelfs point 2 
- Loading an event with 100k+ attributes in MISP via web interface? 
it takes about 3-5 minutes to load, then display

**Comment by iglocska** [comment]
This is indeed an issue via the webUI, but one that is considered an edge case for most so it is low on the priority list. Most data shared definitely isn't in the 100k attribute/event region. As I've mentioned it countless times to @github-germ - we're aware, we'll fix it when we get around to it, but we consider other issues more urgent.

If you would like to fast-track the development of a reworked event view and would like to fund the development, reach out to us. If you have internal resources that can work on it then pull requests are welcome.

**Comment by packet-rat** [comment]
How would/does Devo help with scaling MISP to real world conditions (for large entities)?  We are looking at ingesting ~200 Millions attributes/day.

**Comment by packet-rat** [comment]
@rommelfs / dharshanduck :  We are seeing roughly 1 second/1,000 Attributes to open fully from the Web UI.

**Comment by github-germ** [comment]
> Having events with 100k attributes is not common, yet, thus IMHO still an issue a minority might face.
> If you have a recurring use-case and you think this would be something that everyone might eventually face, please do share.

Just enable some of the Default Feeds, e.g. osint.bambenekconsulting.com/feeds/dga-feed-high.csv, and it's quite easy to get Events with well over 100k attributes.

Also being a large telecom we get many Events approaching 1M attributes. These cannot easily span multiple Events at the risk of getting unwanted dups (i.e. deduping would take way too many cpu cycles pulling in events dedupping, and pushing back -- we tried that and no go -- and dups across events kill correlations).

We understand that this is not deemed a priority, but I did want to dispel the assertion that it is an edge case, at least not from our perspective.

Thanks.

**Comment by adastra247** [comment]
@github-germ - I have the same issue, primarily with the URLHaus feed. It has too many attributes and I get errors when I try to view and manage the feed using the UI or PyMISP. I'd like to avoid splitting this feed into multiple events if possible.

**Comment by JakubOnderka** [comment]
Loading events with a lot of attributes should be much faster now. Can you check latest MISP version?
