### ISSUE TITLE
Request: option for event expiration

### ISSUE THREAD

**Issue by InfosecGoon** [MISP/MISP#4429]
It would be wonderful to have an option to set an expiration date for an event at the time that it is created. We get weekly spreadsheets of threat IoCs that we organize using MISP and feed into our security tooling, but the useful lifespan of the intelligence is generally a couple of weeks. Rather than having to manually delete the old events it would be great to set a mass expiration data for all of the attributes.

I know that we could use the sightings function to set a per-attribute expiration, but these events contain thousands of attributes and setting individual expirations on them would be extraordinarily time consuming.

Thanks!

**Comment by mokaddem** [comment]
Related to #1310
Hi @InfosecGoon !
We started the development of this feature recently.
Briefly, the idea is to compute a score based on multiple parameters:
- sightings
- attached galaxies (to take into account reliability, confidence in the producer, ...)
- type of the Attribute
- and other parameters (to give control over the lifespan and decay rate)

Then, this score can be used to decay/expire indicators.
In the end, Events and Attributes will remain unaffected but can be filtered out thanks to the score and your threshold.
For more information, this ![paper](https://arxiv.org/abs/1902.03914) more or less describes what we want to achieve for the first iteration.

Of course, we really welcome any ideas or suggestions.

Thanks for your interest!

**Comment by SteveClement** [comment]
> Related to #1310
> Hi @InfosecGoon !
> We started the development of this feature recently.

Where is the branch where this is being developed?
This: ? https://github.com/MISP/misp-decaying-models ?

> Briefly, the idea is to compute a score based on multiple parameters:
> 
> * sightings

AFAIK, this is already done.
An example on how to use the expiration sighting would be welcome.

> For more information, this ![paper](https://camo.githubusercontent.com/a2f5a4c56fe38abe5839e0e8d4af22bfbef9d059/68747470733a2f2f61727869762e6f72672f6162732f313930322e3033393134) more or less describes what we want to achieve for the first iteration.
> 

not sure what that link is, but it is broken.

**Comment by adulau** [comment]
@SteveClement It's an ongoing work. @mokaddem will do a draft PR when this is ready for review. The JSON files are there to describe the decaying models for this feature.
