### ISSUE TITLE
Installer permissions error for www-data group

### ISSUE THREAD

**Issue by frostytobin** [MISP/MISP#4432]
When using the installer script (MISP/MISP/blob/2.4/INSTALL/INSTALL.sh) on Ubuntu 18.04

If the www-data user/group doesn't exist the script creates this successfully and adds the MISP user into its group.
However once /var/www/MISP has www-data:www-data permissions set the existing MISP user (now in the group, but not logged out -> in to pickup the new group membership) gets permission denied so the installer can't install MISP modules etc.

Could either delay running "# Main function to fix permissions to something sane" until the very end or perhaps add a facl for the $USER until the installer is finished?

**Comment by SteveClement** [comment]
This has been fixed in the latest installer.
