### ISSUE TITLE
"Download report" no longer available from the GUI...

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#4439]
...in 2.4.105 as app/View/Elements/healthElements/tabs.ctp points to

`        'url' => '/servers/serverSettings/diagnostics',
`

**Comment by iglocska** [comment]
Oops.

**Comment by SteveClement** [comment]
@iglocska I tried to make sense of it, but couldn't really understand what url it wants to point to.

Looking at this: 

https://github.com/MISP/MISP/commit/12ffbf991b48829a27f8f215a692b788a737ca00#diff-b6915c3c38f9035e5769741d98fc775d

Further confuses me as the Title is Download Report...
