### ISSUE TITLE
Pulling jobs  never end after having downloaded the events

### ISSUE THREAD

**Issue by RHormiere** [MISP/MISP#444]
Hello,

I am facing a new issue : when i launch a Pull request, the job download the events and stop at 50% or 67%. Each time, only one event had to be downloaded.

The events are fully downloaded, with all their attributes, and it doesn't seem to be a connection problem.

Nothing critical here though, but i'm just wondering if someone had already encouter this situation.

Regards,
R.Hormiere

**Comment by iglocska** [comment]
Weird, haven't seen this yet, are you running the latest version? Also, do you see anything weird in your logs? (/var/www/MISP/app/tmp/logs - especially error.log, worker-error.log, worker-[date].log)

**Comment by aaronkaplan** [comment]
On Mar 27, 2015, at 5:51 PM, RHormiere <notifications@github.com> wrote:

> Hello,
> 
> I am facing a new issue : when i launch a Pull request, the job download the events and stop at 50% or 67%. Each time, only one event had to be downloaded.
> 
> The events are fully downloaded, with all their attributes, and it doesn't seem to be a connection problem.
> 
> Nothing critical here though, but i'm just wondering if someone had already encouter this situation.

Yes, I did as well.
I usually just restart the workers.

**Comment by RHormiere** [comment]
Thanks for the replies.
Restarting the worker didn't do the trick, and i see no error in the logs...

But it seems the problem is solved : I have launched two tries this morning : the first one finished completely (except that the e-mail job is started but doesn't progress), and the second one is started but doesn't progress either. After a lot of time, all tasks are done.

I close this issue for now and i'll let you know if this happen again.

Regards,
R.H
