### ISSUE TITLE
request has been black-holed

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#4440]
My misp instance gives me the following error when i try to log in:

The request has been black-holed
Error: The requested address '/users/login' was not found on this server.

The error always happens if I enter a  password incorrect multiple times  or  if i open the login window and only login after some few minutes. What is causing this issue?

**Comment by iglocska** [comment]
Form tampering protection. 

All forms have a timeout (15min iirc) and all of them can only be submitted once. If you use your browser's "back" button and resubmit the form MISP will consider it as a potential attempt at form tampering.
