### ISSUE TITLE
[UI] Unfanging at attribute level

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4442]
# [UI] Unfanging at attribute level

When pasting values in attributes, it would be really cool to have a way to make an automatic "unfanging" of the value (via a small button next to the field). The unfanging code is part of the free-text import, not sure if we could reuse the same code for doing it at field level.

Related to #2892

**Comment by StefanKelm** [comment]
This is related to another really cool (TM) issue: #2892 :-)

**Comment by iglocska** [comment]
Why have a button? Why not do it automagically on beforeValidate?

**Comment by iglocska** [comment]
> This is related to another really cool (TM) issue: #2892 :-)

This one is tricky. The problem is that we might get some weird results based on the type of value we're searching for - I am not sure we should refang anything starting with meow to http - unless we know that we're dealing with a link/url

**Comment by adulau** [comment]
Even better thanks ;-)
