### ISSUE TITLE
Expiration field per attribute

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#445]
Following a discussion, we should have a way to expire an attribute (especially useful when a compromised site is fixed and not used any more by the adversaries).

An idea would be to set a TTL to an attribute per default.

**Comment by iglocska** [comment]
Makes sense, we definitely need a way to let attributes expire, though there are two major things to consider with this:

1. Do we want a global default value for attributes, or do we need a mapping between default TTL and certain attribute types (for example a file hash will most likely not need a TTL at all)? 
2. Should the default values be something configurable by the instance admin, or should they be pre-defined?

**Comment by RichieB2B** [comment]
This request came up at our end as well. My thoughts on your questions:

1. A global default should be fine. Even though a file hash will never change over time, a TTL still makes sense to avoid keep checking for malware that is no longer relevant. (The AV pattern DB size problem.)
2. If we go for a single default, configurable in the GUI makes sense. If there are separate defaults per attribute type I think adjusting them in config.php only (without GUI) is sufficient.

**Comment by iglocska** [comment]
The TTL / type sounds like the best option to  me, even though you may indeed not want to keep ancient hashes in your exports, some attribute types such as IPs should expire quicker.

Now the big remaining questions are:
1. What do we do with the TTL? I see two main options here: use the default TTL for the given type when creating the attribute and store it within the attribute itself? Or a better, though not as granular option: Use the TTL settings on export dynamically (by calculating the timestamps that should be included). This could then of course be overriden with a parameter. 

2. We would still need a default (list or single value) TTL that MISP would use if the admins don't specify otherwise. Any ideas for the default settings? :)

**Comment by cvandeplas** [comment]
The big problem I'm encountering with expiration is not knowing how long we
need to keep something.

I would (also) allow different decisions based on Event risk
(low/medium/high).

Perhaps also with an interface where you can see what attributes/events are
going to be marked as 'expired', and you can choose what event not to
expire.

If the database schema needs to be updated, it'd be good to see what naming
STIX uses in this case.

**Comment by iglocska** [comment]
That's a very good idea to include the the risk field in the calculation! I'll have a look at STIX if there is anything similar in place!

**Comment by elhoim** [comment]
Until the big DB re-organisation happens, could we go with a quick fix (yeah i know it might end up being too permanent) by having an optional expiration date on the event level?
It works for most cases & users that don't want to use it, are free to do just that.

I am asking since I get a whole category of false positives that are just waterholing cases that were valid, but are not anymore.

**Comment by elhoim** [comment]
Should I create separate tickets to handle the various aspects discussed here:
1. Quick fix / expiration date per event
2. Expiration date per attribute
3. Review mechanism with manual validation of expiration based on risk level (based on what @cvandeplas said)

I would be very interested to get number 1 (the quick fix) in v2.4, but I don't know if it is realistic.

**Comment by cvandeplas** [comment]
1. There is no quick fix. / expiration date per event. Don't ask questions to an analyst (producer) who doesn't know the answer. An analyst encoding the events doesn't know in 90% of the cases what expiration date he needs to enter. Additionally, all the existing events will still not have the value set. So it's not a "quick" fix as far as I see it.

2. same as 1.

3. I am convinced this is the only clean way to do this. Let the consumer (upon export) decide based on a kind of 'search' or configuration for him personally, with some sensible defaults.

**Comment by adulau** [comment]
Within the team at CIRCL, we discussed about the expiration date. This is indeed something very specific to the use of the event (as mentioned by @cvandeplas too). But if this is a matter of the consumer, why not providing a way to set the expiration of an event per user (this is something completely local)? Where a user (via GUI or an API) can set the expiration date for a specific event and the expiration field is use to hide (via GUI or API) the event.

**Comment by iglocska** [comment]
Having a / user (or probably better a / org) expiration would be a relatively easy solution. The only issue I see with it is a situation where an organisation acts as the primary producer of information for its community - they'd have no way of setting the expiration values for their consumer.

**Comment by elhoim** [comment]
1. If you have a producer of data, getting that _informational_ field on the event level can be useful, just like *Threat Level* is. To handle the case where the producer/encoder does not care, why not add a value *undefined*, just like Threat Level. You let user use it if they want.
The down-side is that it is one more field that can filled or not, depending on the user whishes... :(

2. The idea of a value for consumer is nice, and made me think of something else. Using the existing capabilities  at the event level: tags. If I do something structured but flexible (like [machine tags](http://www.foo.be/cgi-bin/wiki.pl/MachineTag) with a human-review process to tag things, this could do.
I am thinking tags like: *alert:expire:never* *alert:expire:after:6d*, etc... 
Plus it fits very well with the ideal of flexibility, and when tags become optionally exportable (v2.4+), you get the possibility for producers to add that information too.
The downside I see, is that for different orgs to have different policies for tagging, they each need their own MISP instance to tag their specific stuff there and not start tagging on an external community, which would not make sense for others.

**Comment by adulau** [comment]
Following a discussion with various users and @iglocska , we come with a proposal (first step) implementation for the first_seen and last_seen attributes in MISP:
- MISP now includes sighting support which allows to set and get at attribute level when the attribute was seen.
- Sighting is local to a MISP instance.
- The first implementation of first_seen and last_seen tags will be set locally at the attribute level.
- If there is no sighting on the attribute, the first_seen and last_seen tag value inherits from the event date.

Feedback welcome for this first implementation (for distributed sightings and first/last_seen it will be a next iteration).

**Comment by adulau** [comment]
With the recent 2.4.60 release with attribute-level tagging, this can be already tested as external scripts to create first_seen/last_seen.

**Comment by adulau** [comment]
With the recent 2.4.66 release, expiration is now implemented in the sighting. Testing and feedback is welcome.
