### ISSUE TITLE
glyphicons not rendered issue

### ISSUE THREAD

**Issue by kahunakhan** [MISP/MISP#4460]
# glyphicons not rendered in View Event

- I just did a fresh install of MISP from the provided script.
However the glyphicons are not being rendered in the event graph
- It is evident that the glyphicon takes the value since thier font awesome refrence are available.

- Also if i want to change the glyph for a particular object how can i define it in the object attribute?
![Capture](https://user-images.githubusercontent.com/34471708/56019760-1b9ca500-5d23-11e9-865b-fff7b417b98e.PNG)

**Comment by mokaddem** [comment]
Hello @kahunakhan!
have you tried to SHIFT-reload the page? Is the problem persistent.
To answer your question, it's not possible to select the icon for a specific object. The mapping is hard-coded in the [EventGraph's Javascript](https://github.com/MISP/MISP/blob/2.4/app/webroot/js/event-graph.js#L38)  as the object template do not accept an icon field.
If you have a particular mapping you want to add, do not hesitate to open an issue about it, or **even better** to create a pull request.

**Comment by SteveClement** [comment]
Is this still an issue?

I saw @mokaddem commiting some glyphs?

**Comment by mokaddem** [comment]
@SteveClement Oh right, It should be solved by now!
