### ISSUE TITLE
Install issue on ubuntu 18.04

### ISSUE THREAD

**Issue by migueljtc** [MISP/MISP#4463]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  ubuntu 18.04
### Expected behavior
Installing the providade [install script]( https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.debian.sh ) should go without errors. 

### Actual behavior
Throws  an error and MISP (at least gui) wont start.
Also the script should ask for the base URL and it does not, just goes through it.
(same happens when deleting -nuking- when queried if should delete the DB, does not prompt the user and uses default options) 

### Steps to reproduce the behavior
Installed fresh ubuntu 18.04 LTS. Installed openssh-server (via apt). Created user "misp" with root permissions. Executed the script:
`sudo curl -fsSL https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.debian.sh | bash -s -- -c -M
` 

### Logs, screenshots, configuration dump, ...
Redirect of stdout&stderr from install to the same file.
The file is here on pastbin -> [here](https://pastebin.com/kVvV9hHE) <-  due to readability issues pasting it here.  Just posting the error part:

> Collecting neobolt<1.8,>=1.7.3 (from py2neo->pymisp==2.4.103)
Collecting soupsieve>=1.2 (from beautifulsoup4->pymisp==2.4.103)
  Using cached https://files.pythonhosted.org/packages/c9/f8/e54b1d771ed4fab66b3fa1c178e137a3c73d84fb6f64329bddf0da5a371c/soupsieve-1.9-py2.py3-none-any.whl
Requirement already satisfied: pillow>=4.0.0 in /var/www/MISP/venv/lib/python3.6/site-packages (from reportlab->pymisp==2.4.103) (6.0.0)
Collecting decorator>=3.4.0 (from validators->pymisp==2.4.103)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.1,>=2.0.7->py2neo->pymisp==2.4.103)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Installing collected packages: click, neotime, wcwidth, prompt-toolkit, pygments, colorama, neobolt, py2neo, soupsieve, beautifulsoup4, decorator, validators, pymisp
  Found existing installation: pymisp 2.4.103
    Uninstalling pymisp-2.4.103:
      Successfully uninstalled pymisp-2.4.103
  Running setup.py develop for pymisp
Successfully installed beautifulsoup4-4.7.1 click-7.0 colorama-0.4.1 decorator-4.4.0 neobolt-1.7.4 neotime-1.7.4 prompt-toolkit-2.0.9 py2neo-4.2.0 pygments-2.3.1 pymisp soupsieve-1.9 validators-0.12.4 wcwidth-0.1.7
Cloning into '/var/www/MISP/PyMISP/tests/viper-test-files'...
E
======================================================================
ERROR: setUpClass (__main__.TestComprehensive)----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 101, in __init__
    response = self.get_recommended_api_version()
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 1414, in get_recommended_api_version
    response = self._prepare_request('GET', url)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 175, in _prepare_request
    prepped = s.prepare_request(req)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 50, in setUpClass
    cls.admin_misp_connector = ExpandedPyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 115, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP (""). Please make sure the API key and the URL are correct (http/https is required): Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?
Ran 0 tests in 0.007s
FAILED (errors=1)
No module named 'keys'

**Comment by SteveClement** [comment]
Does the install finish  successfully?

Meaning can you log in and go to the diagnostics page and all is "fine"?

I will investigate the tests-failing, that is indeed an issue.

**Comment by migueljtc** [comment]
The install finishes successfully yes.
I cannot logging, won't even respond to connections on https://my_ip:8443 (or 127.0.0.1:8443).

**Comment by ashim-mahara** [comment]
Has this been fixed yet? I am facing the same problem.

**Comment by SteveClement** [comment]
I will take care of this tomorrow, sorry for the delay.

**Comment by SteveClement** [comment]
Found the bug.

In theory this fixes it: https://github.com/MISP/MISP/pull/4558
Now testing before closing.

**Comment by SteveClement** [comment]
The installer is working again.

Thanks for the patience.
