### ISSUE TITLE
STIX2 or Cybox libraries diagnostic throwing error

### ISSUE THREAD

**Issue by dharshanduck** [MISP/MISP#4472]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | ![image](https://user-images.githubusercontent.com/9196526/56114209-c4047080-5f92-11e9-87f6-95d9cc058275.png)
| Browser                   | Chrome

### Expected behavior
For there to be no error and STIX2 version 1.1.2 successfully detected

### Actual behavior
STIX2 1.1.2 is installed, however misp detects version 1.1.1

### Steps to reproduce the behavior
Just run the diagnostic, and if you get the error, update stix2 to 1.1.2 and run diagnostic again. You will get the same error.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/9196526/56114161-9f0ffd80-5f92-11e9-9100-2be1ce3a7f71.png)

![image](https://user-images.githubusercontent.com/9196526/56114190-b5b65480-5f92-11e9-9b56-47756e55c73a.png)

**Comment by dharshanduck** [comment]
@chrisr3d i think you'd be able to assist me in this?  I believe that this is related to #4378 where after stix2-1.1.2 was uninstalled, misp still thought that 1.1.2 is still installed. It could be the same case here, but the other way around

**Comment by chrisr3d** [comment]
Hey, can you check if you have the directory `/var/www/MISP/venv` ?

If yes, then run the same command as you did, but using pip from the venv directory:

`sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U .`

If no, I am really confused because at this point it is the only reason why the update could not work that I see

**Comment by dharshanduck** [comment]
Well yes i have the directory, i ran the command, but to no avail.

![image](https://user-images.githubusercontent.com/9196526/56119357-91f90b80-5f9e-11e9-8d14-2f85e92b330b.png)

**Comment by chrisr3d** [comment]
Ah sorry I did not explain it properly, you should launch it from `/var/www/MISP/cti-python-stix2`

I did not mention it because you were already there in your first screenshot.

So, exact same command, but from `/var/www/MISP/cti-python-stix2`, and it should be fine

**Comment by dharshanduck** [comment]
Awesome it works now. Thanks @chrisr3d 
So to summarize for anybody experiencing this issue; 
1. `cd /var/www/MISP/cti-python-stix2`
1. `sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U .`
1. Do this if you ever get an error regarding CYBOX & STIX libraries from diagnostics
