### ISSUE TITLE
Rest API MISP Internal Server Error

### ISSUE THREAD

**Issue by MichaelHuys** [MISP/MISP#4475]
Hello,

currently I'm testing the rest API functionallity of our MISP instance (2.4.102). When I do some tests using the builtin REST Client I'm constantly getting an Internal Server Error. When I check the logs this is reflected as below:

_2019-04-15 11:02:48 **Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto**
stream_socket_client(): unable to connect to ssl://************** (Unknown error)
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(386): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('POST /attribute...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(514): HttpSocket->request(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1624): HttpSocket->post('*******...', '{\r\n    "returnF...', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(1543): ServersController->__doRestQuery(Array, 'curl \\\n -d '{"r...', 'misp_url = 'htt...')
#5 [internal function]: ServersController->rest()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2019-04-15 11:02:48 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(2)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
2019-04-15 11:02:48 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 261]
2019-04-15 11:02:48 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}_

Any idea how we can workaround this?

Kind regards,

Michael

**Comment by SteveClement** [comment]
I suppose this is in the Web UI?

If it is, make sure your servers' CA bundle knows about your self-signed certificate.

@iglocska is there a bypass to verify the Certificate?

If it is in PyMISP, you can workaround as follows:

```python
# Should PyMISP verify the MISP certificate
misp_verifycert = False
```

**Comment by MichaelHuys** [comment]
Hello Steve,

first of all thanks for the feedback!
By default our internal ROOT and Intermediate CA's are in our Servers truststore -> /etc/pki/ca-trust/extracted/java/cacerts. Or do I also need to insert the child certificate over there?

Or is MISP using a different CA bundle?

Kind regards,

Michael

**Comment by iglocska** [comment]
MISP is definitely not using the java trust stores, but rather its own. You can tell MISP to ignore the SSL validation altogether for REST queries, simply check the skip SSL validation checkbox.

![image](https://user-images.githubusercontent.com/3668672/56189458-4ee37a80-6028-11e9-9c38-147e92e1ed54.png)

**Comment by MichaelHuys** [comment]
Hello,

the issue is indeed only occuring using the REST client within MISP. This is because this REST client is using it's own truststore in which our Internal CA ROOT is NOT included. Checking the "Skip SSL validation" checkbox of course bypasses this issue.
When we try the REST call's through Curl or Soap Ui this is working perfectly.

Michael
