### ISSUE TITLE
Error: Plugin CakeResque could not be found.

### ISSUE THREAD

**Issue by ESL482** [MISP/MISP#4476]
Hi , 
I installed cake resque plugin by following https://misp.github.io/MISP/INSTALL.ubuntu1804/, i am using ubuntu 18.04 LTS
but when i am running this command  it giving me below error.
:/var/www/MISP/app$  **sudo -u www-data cp -fa ${PATH_TO_MISP}/INSTALL/setup/config.php ${PATH_TO_MISP}/app/Plugin/CakeResque/Config/config.php**
cp: cannot create regular file '/var/www/MISP/app/Plugin/CakeResque/Config/config.php': No such file or directory

there is no folder namedlike CakeResque in that path also but when i installed it didn'y showed any error,
And i am getting errors like this also when i started workers

$SUDO_WWW bash $PATH_TO_MISP/app/Console/worker/start.sh
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}
Error: Plugin CakeResque could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('CakeResque')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'CakeResque')
#2 [internal function]: App::load('CakeResqueShell')
#3 [internal function]: spl_autoload_call('CakeResqueShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(262): class_exists('CakeResqueShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('CakeResque')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#8 {main}

can any one please help me to understand and solve the issue.

**Comment by SteveClement** [comment]
You probably forgot to:

```bash
  cd ${PATH_TO_MISP}/app
  # Make composer cache happy
  # /!\ composer on Ubuntu when invoked with sudo -u doesn't set $HOME to /var/www but keeps it /home/misp \!/
  sudo mkdir /var/www/.composer ; sudo chown www-data:www-data /var/www/.composer
  sudo -H -u www-data php composer.phar require kamisama/cake-resque:4.1.2
  sudo -H -u www-data php composer.phar config vendor-dir Vendor
  sudo -H -u www-data php composer.phar install
```

**Comment by ESL482** [comment]
Hi steve,
Thanks for the information. I did the above steps that you mentioned already after that only it showed that error.when i executed above commands it doesn't showed any error.
