### ISSUE TITLE
Help with mysterious log errors

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4477]
2.4.102

We see lots of permission and other mysterious errors in log files. We followed the RH7 install instructions on https://misp.github.io/MISP/INSTALL.rhel7/ setting file `uid:gid:mode` as per:

```
5/ Set file permissions
...
If you do not require updates through the web interface to work, you can use the following more restrictive permissions :

chown -R root:apache /var/www/MISP
find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP
chown apache:apache /var/www/MISP/app/files
chown apache:apache /var/www/MISP/app/files/terms
chown apache:apache /var/www/MISP/app/files/scripts/tmp
chown apache:apache /var/www/MISP/app/Plugin/CakeResque/tmp
chown -R apache:apache /var/www/MISP/app/tmp
chown -R apache:apache /var/www/MISP/app/webroot/img/orgs
chown -R apache:apache /var/www/MISP/app/webroot/img/custom
```
We've checked that our running MISP instance indeed has all the settings as above.

Please let us know if any of these error signatures are related to file permissions; and in any case, what we can do to resolve these errors from occurring.

* `resque-worker-error.log`
```
Notice Error: Redis::rPush(): send of 8192 bytes failed with errno=104 Connecti\
on reset by peer in [/var/www/MISP/app/Lib/Tools/PubSubTool.php, line 147]

PHP Warning:  SplFileInfo::openFile(/var/www/MISP/app/tmp/cache/persistent/myap\
p_cake_core_cake_console_eng): failed to open stream: Permission denied in /var\
/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Engine/FileEngine.php on line 360

PHP Warning:  _cake_core_ cache was unable to write 'cake_console_eng' to File \
cache in /var/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Cache.php on line 327
```
*  `error.log` -- we see lots of there, likely from a PyMISP app we run; however, the events are `published=True` when examined in the WebUI
```
2019-04-14 03:35:09 Error: [MethodNotAllowedException] You don't have the permi\
ssion to do that.
Request URL: /events/publish/81244
Stack Trace:
#0 [internal function]: EventsController->publish('81244')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): Refle\
ctionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controll\
er->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatch\
er->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeReq\
uest), Object(CakeResponse))
#5 {main}
```
* `debug.log`
```
2019-04-14 03:31:03 Notice: Notice (8): Redis::rPush() [<a href='http://php.net\
/redis.rpush'>redis.rpush</a>]: send of 8192 bytes failed with errno=104 Connec\
tion reset by peer in [/var/www/MISP/app/Lib/Tools/PubSubTool.php, line 147]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, \
line 230
Redis::rPush() - [internal], line ??
PubSubTool::__pushToRedis() - APP/Lib/Tools/PubSubTool.php, line 147
PubSubTool::publishEvent() - APP/Lib/Tools/PubSubTool.php, line 111
Event::publish() - APP/Model/Event.php, line 3863
Event::_edit() - APP/Model/Event.php, line 3566
EventsController::edit() - APP/Controller/EventsController.php, line 1973
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php\
, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1\
93
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line \
167
[main] - APP/webroot/index.php, line 92
```
* output from `cake fetchFeed` for feed id 1 and 3 -- many lines with the `fatal git repo` error
```
/var/www/MISP/app/Console/cake Server fetchFeed 60 3

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: Not a git repository (or any of the parent directories): .git
...
```

**Comment by RichieB2B** [comment]
If the chmod/chown you quoted do not help, try step 7.02:
```
semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/MISP(/.*)?"
restorecon -R /var/www/MISP/
```

**Comment by github-germ** [comment]
Really appreciate your trying to help!!

SELinux is disabled. What else might you suggest?
```
$ getenforce
Disabled
$ 
```

**Comment by SteveClement** [comment]
I am re-working the CentOS and RHEL7 install documents.

Something resets the connection between you and the redis server.
What? Good question.

So far I cannot really help. Perhaps drop into the [Support Gitter](https://gitter.im/MISP/Support).

**Comment by SteveClement** [comment]
Just stumbled over this comment in the install docs:

```
# CakeResque normally uses phpredis to connect to redis, but it has a (buggy) 
# fallback connector through Redisent.
# It is highly advised to install phpredis using "yum install php-redis"
```

**Comment by liedekef** [comment]
@SteveClement : I already did a pull request (which was accepted) to change the doc for redhat7: 
https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.rhel7.md

However: there's older doc present in the INSTALL dir and on https://misp.github.io/MISP/INSTALL.rhel7/ , I think those should be consolidated

**Comment by github-germ** [comment]
Really appreciate the attention this is getting!

@SteveClement: I don't see `php-redis` mentioned in https://misp.github.io/MISP/INSTALL.rhel7/

1. Which doc are you referring to?
1. Is the suggestion that we `yum install php-redis` and then what else?
1. Here's what we have related to `redis` and `php`:
```
$ rpm -qa|egrep -i "redis|php"
rh-php71-php-cli-7.1.8-1.el7.x86_64
rh-php71-php-bcmath-7.1.8-1.el7.x86_64
rh-php71-php-xml-7.1.8-1.el7.x86_64
rh-php71-php-mbstring-7.1.8-1.el7.x86_64
rh-php71-php-json-7.1.8-1.el7.x86_64
rh-php71-php-pdo-7.1.8-1.el7.x86_64
rh-php71-php-mysqlnd-7.1.8-1.el7.x86_64
rh-php71-php-fpm-7.1.8-1.el7.x86_64
rh-redis32-2.3-1.el7.x86_64
rh-php71-php-zip-7.1.8-1.el7.x86_64
rh-php71-php-process-7.1.8-1.el7.x86_64
rh-php71-1-1.el7.x86_64
rh-php71-php-opcache-7.1.8-1.el7.x86_64
rh-redis32-redis-3.2.4-1.el7.x86_64
python36u-redis-2.10.6-1.ius.centos7.noarch
rh-php71-runtime-1-1.el7.x86_64
rh-php71-php-pear-1.10.4-1.el7.noarch
rh-redis32-runtime-2.3-1.el7.x86_64
rh-php71-php-common-7.1.8-1.el7.x86_64
rh-php71-php-devel-7.1.8-1.el7.x86_64
$ 
```

**Comment by liedekef** [comment]
It is in the doc (at least in https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.rhel7.md , which I advise to follow): yum install rh-redis32

**Comment by github-germ** [comment]
@liedekef: as you can see from https://github.com/MISP/MISP/issues/4477#issuecomment-483652173 above, we already have `rh-redis32-2.3-1.el7.x86_64` installed.

**Comment by liedekef** [comment]
Sorry, indeed. I talked about redhat redis, not php redis extension. See section 4.02 in the same doc for that.

**Comment by gitnorty** [comment]
I believe we have covered all the steps when we did the install originally, unless something was added later to the instructions.  We performed the original install about a year ago or more:

[root@md2nj08ta ~]# scl enable rh-php71 'pecl list'
Installed packages, channel pecl.php.net:
=========================================
Package Version State
redis   4.0.2   stable

[root@md2nj08ta ~]# grep extension /etc/opt/rh/rh-php71/php-fpm.d/redis.ini
extension=redis.so

[root@md2nj08ta ~]# ls -ltr /etc/opt/rh/rh-php71/php.d/99-redis.ini
lrwxrwxrwx 1 root root 40 Sep 28  2018 /etc/opt/rh/rh-php71/php.d/99-redis.ini -> /etc/opt/rh/rh-php71/php-fpm.d/redis.ini

[root@md2nj08ta ~]# grep UTC /etc/opt/rh/rh-php71/php-fpm.d/timezone.ini
date.timezone = "UTC"

[root@md2nj08ta ~]# ls -ltr /etc/opt/rh/rh-php71/php.d/99-timezone.ini
lrwxrwxrwx 1 root root 43 Sep 28  2018 /etc/opt/rh/rh-php71/php.d/99-timezone.ini -> /etc/opt/rh/rh-php71/php-fpm.d/timezone.ini

**Comment by liedekef** [comment]
I just reacted to the updated doc (and to the redis remark). If you (@gitnorty ) are the same person as @github-germ and you're not using selinux: check the permissions of all files and directories. Also: the doc has changed quite a bit since the original doc was not functional at all on redhat (and php 7.1 will not be supported for long anymore according to the misp site).
Next to that: the original bug stated permission issues with "/var/www/MISP/app/tmp/cache/persistent/", so check the owner and permissions of that dir.

**Comment by gitnorty** [comment]
Hi liedekef; we are not the same person; but are working together.  

For checking the permissions; is following section 5 of the installation doc sufficient to verify the permissions?

I'll revisit the differences between the original installation notes I have and what is present in the doc now to see what is different.

I did see that PHP 7.1 won't be supported at the end of the year; the transition is being planned.

Here are our permissions/ownership currently set on the directory mentioned:

[root@md2nj08ta ~]# ls -ld /var/www/MISP/app/tmp/cache/persistent/
drwxr-x--- 2 apache apache 188 Apr 16 16:25 /var/www/MISP/app/tmp/cache/persistent/

This appears to correspond to the permissions I see in section 5 of the install notes.

**Comment by gitnorty** [comment]
I went through the notes we had on the installation; the only differences I see is:

1. We didn't install 'rh-php72-php-gd'
2. We didn't install 'rh-git218'
3. As my coworker mentioned; we aren't using SELinux
4. We aren't using systemctl to manage the 'workers'; I tried to enable this, but it wasn't working properly.  I was seeing issues where it wasn't stopping the workers.  Multiple iterations of the workers were started, etc...  Currently sticking with the standalone script to manage the workers.

As far as I'm aware, none of these should cause the issues mentioned.

Thanks.

**Comment by liedekef** [comment]
Check that php-fpm is running with a user that can write into /var/www/MISP/app/tmp/cache/persistent/
The way your permissions are now, only user apache can write in /var/www/MISP/app/tmp/cache/persistent/ , so either run php-fpm as that user or correct the permissions.

**Comment by gitnorty** [comment]
Hi liedekef, thank you for your response!  Can you suggest a method to verify php-fpm can write as a user to the cache directory since the users are only configured in the MISP system not on the OS?  How would I know which user's other than apache need to be able to write to the cache directory?  Also, can you please clarify what permissions need to be set?  Based on the install documentation, the permissions appear to be correct; specifically:

find /var/www/MISP -type d -exec chmod g=rx {} \;
chown -R apache:apache /var/www/MISP/app/tmp

Also from what I can see, all the current php-fpm processes are running as either apache or root.

[root@md2nj08ta ~]# ps -ef |grep php-fpm
apache     395 32316  6 Apr16 ?        10:11:47 php-fpm: pool www
root      1185 30808  0 12:49 pts/0    00:00:00 grep --color=auto php-fpm
apache    1503 32316  6 Apr16 ?        10:06:55 php-fpm: pool www
apache    5643 32316  6 Apr16 ?        10:33:27 php-fpm: pool www
apache   14971 32316  5 Apr17 ?        08:18:08 php-fpm: pool www
apache   26233 32316  4 Apr22 ?        00:37:06 php-fpm: pool www
apache   26275 32316  3 Apr22 ?        00:32:02 php-fpm: pool www
apache   26314 32316  4 Apr22 ?        00:37:12 php-fpm: pool www
apache   26513 32316  5 Apr22 ?        00:44:59 php-fpm: pool www
apache   30123 32316  5 Apr17 ?        08:57:51 php-fpm: pool www
root     32316     1  0 Apr16 ?        00:00:19 php-fpm: master process (/etc/opt/rh/rh-php71/php-fpm.conf)
apache   32317 32316  5 Apr16 ?        09:26:08 php-fpm: pool www
apache   32318 32316  5 Apr16 ?        09:30:03 php-fpm: pool www
apache   32319 32316  6 Apr16 ?        09:57:55 php-fpm: pool www
apache   32320 32316  6 Apr16 ?        10:20:19 php-fpm: pool www
apache   32321 32316  6 Apr16 ?        10:02:55 php-fpm: pool www
apache   32322 32316  6 Apr16 ?        10:30:32 php-fpm: pool www

**Comment by liedekef** [comment]
Based on your info, php-fpm is running as the apache user, so that's ok. Make sure that all parent directories of /var/www/MISP/app/tmp/cache/persistent/ are accessible too for the apache user.

**Comment by gitnorty** [comment]
Thanks again for the feedback.

It looks like from the app directory up to the MISP directory, that they are not writeable, but are readable;

[root@md2nj08ta ~]# ls -ld /var/www/MISP/app/tmp/cache/persistent/
drwxr-x--- 2 apache apache 188 Apr 23 15:21 /var/www/MISP/app/tmp/cache/persistent/
[root@md2nj08ta ~]# ls -ld /var/www/MISP/app/tmp/cache/
drwxr-x--- 7 apache apache 4096 Apr 19 09:50 /var/www/MISP/app/tmp/cache/
[root@md2nj08ta ~]# ls -ld /var/www/MISP/app/tmp/
drwxr-x--- 16 apache apache 210 Apr 18 20:35 /var/www/MISP/app/tmp/
[root@md2nj08ta ~]# ls -ld /var/www/MISP/app/
drwxr-x--- 17 root apache 4096 Feb 11 14:35 /var/www/MISP/app/
[root@md2nj08ta ~]# ls -ld /var/www/MISP/
drwxr-x--- 18 root apache 4096 Feb  4 17:01 /var/www/MISP/

Should I change the group permissions to writeable or the ownership to apache?  or are these permissions ok?

**Comment by SteveClement** [comment]
> I went through the notes we had on the installation; the only differences I see is:
> 
> 1. We didn't install 'rh-php72-php-gd'

This is only needed to properly resize some screenshots as per @mokaddem changes to some screenshot-foo.

> 2. We didn't install 'rh-git218'

AFAIS this is only needed for LIEF.

> 3. As my coworker mentioned; we aren't using SELinux

This makes things "easier"(TM) but still, we are not using RHEL in prod, and I am only now re-testing all the RHEL/CentOS stuff, so I need more time to make it all work.

> 4. We aren't using systemctl to manage the 'workers'; I tried to enable this, but it wasn't working properly.  I was seeing issues where it wasn't stopping the workers.  Multiple iterations of the workers were started, etc...  Currently sticking with the standalone script to manage the workers.
> 

systemd units are independent of starting and stopping things in the GUI.

Gimme more time to fix this on this platform.

> As far as I'm aware, none of these should cause the issues mentioned.
> 

Also, this is the "master" issue for RHEL/CentOS: https://github.com/MISP/MISP/issues/4084

**Comment by SteveClement** [comment]
I also re-generated: https://misp.github.io/MISP/INSTALL.rhel7/
Search for: redis32
For a working redis.

**Comment by gitnorty** [comment]
Thanks for the information Steve!  I'll review the latest version of the install instructions and see if we are missing anything.

**Comment by chintamvijay** [comment]
Hi 
Am getting error while login the MISP below is the error.

![image](https://user-images.githubusercontent.com/129829209/236392496-3525bb70-71bf-4ecd-b5ae-1dfd7c89fc84.png)
