### ISSUE TITLE
STIX export Title

### ISSUE THREAD

**Issue by deralexxx** [MISP/MISP#448]
It would be nice to have a title for each observable in the taxi export.

e.g.:
 Network activity
ip-dst
8.8.8.8

-->

Title:
IP: 8.8.8.8

As well as description of the event is not used in the export stix file.

Makes sense?

**Comment by RichieB2B** [comment]
Absolutely! Check out this patch: #409

**Comment by deralexxx** [comment]
ok cool, then I can close my issue :)
