### ISSUE TITLE
Push request on a differen url than root

### ISSUE THREAD

**Issue by jhemp** [MISP/MISP#449]
The case is the following
The url specified in the server list is http://xxxxxx/MISP 
The first call for the push events is http://xxxxxx/MISP/events/filterEventIdsForPush which is fine 
the second however is http://xxxxxx/events/index

in my opinion it should be  http://xxxxxx/MISP/events/index.

**Comment by iglocska** [comment]
What is your baseurl set to in the MISP settings? It should be
http://xxxxx/MISP

**Comment by jhemp** [comment]
Actually my base url is http://xxxxxx/MISP (specified in the server list)

however the http://xxxxxx/events/index is called I just wonder why

**Comment by iglocska** [comment]
Just to clarify, on the http://xxxxx/MISP instance, in the server settings
- so administration->server settings->MISP settings tab->baseurl setting -
what's the current setting?

**Comment by jhemp** [comment]
Sorry I am bad in explaining, 
I have 2 servers server A is a non misp platform which should be compatible with misps pull push system.
and server B a std. misp instance

The settings in server B, you meantionned is http://ServerB/
When I now perform a push all op server B to Server A I see the follwing requests on the server A side

http://ServerA/MISP/events/filterEventIdsForPush
http://ServerA/events/index

when I perform a pull all on server B I see the request 
http://ServerA/MISP/events/index
as I expected.

I wonder why the "http://ServerA/events/index" is executed and why it does not have the base url of serverA in it

Hope that clears the issue

**Comment by iglocska** [comment]
OK, that is indeed very odd. I don't have any instances in my test
environment where MISP is accessed via http://<url>/MISP, so I cannot yet
reproduce the issue, but looking at the code, this is very odd.

Basically the sync works in this way on a push:

1. ServerA initiates a push to ServerB
2. ServerA sends a json object to ServerB/events/filterEventIdsForPush
including all eligible uuids / timestamps
3. ServerB looks through the list and throws anything away that should not
be edited (events that have the same or older timestamp, events that cannot
be edited)
4. ServerB sends a list of uuids back as a response
5. ServerA starts looping through the UUIDs:
    5.a. ServerA POSTs the next matched event to serverB/events/ where
serverB is taken from the server list
    5.b if ServerB already has that event, it returns a 302 with its
baseurl in the location header like this: serverB/events/found_event_id
    5.c if ServerA received a 302 it POSTs the event to
serverB/events/found_event_id

So in your case, you should see SeverA/MISP/events/filterEventIdsForPush
followed by a POST to ServerA/MISP/events. The error that I hinted at
earlier would only happen after this point in 5.c, if the other server has
an incorrect baseurl set and passes that back in the location header, but
this would look like this ServerA/MISP/events/event_id

I'll try to reproduce it over the weekend, I just need to set up a server
where MISP is accessible through a non-standard path, but after a first
glance this should not happen...

**Comment by jhemp** [comment]
I fiddled a long time with my sync system, but I think it was due do a response I gave at some point i.e Error 500. As now I've implemented the push completely I cannot reproduce it anymore.

**Comment by jhemp** [comment]
Thx for the explanation of the workings but will never throw a 302 error, will this cause troubles to misp?

I concentrate only on the uuids given an check if I know them, then remove them from the array wich I give after the post from server A.

**Comment by iglocska** [comment]
302 is not an error, it's basically just a response from MISP saying that
the event already exists.

So basically it works like this:

I push an event to MISP that already exists (UUID is already in the db) ->
MISP tells you that this already exists (302) and returns a location header
with the URL to the event (so for example https://mymisp.com/events/50
where 50 is the identified event's ID).

As a response, your application should repeat the POST, but instead of
targeting https://mymisp.com/events it should target
https://mymisp.com/events/50. Depending on the contents (who you are and
the event's orgc, whether the event is locked for sync editing, timestamp
differences, etc) it will try to update the event with your pushed content.

You can add new data without this mechanism, but updating won't work.

**Comment by jhemp** [comment]
interesting feature, however I am not there yet as I have to reconvert STIX to misp xml

**Comment by jhemp** [comment]
I found when it happens, it happens when the other side (ServerB) returns a 500

**Comment by iglocska** [comment]
Which one is the other side? MISP or the application that syncs with it? If it is MISP, what was the cause of the 500?

**Comment by jhemp** [comment]
ServerA = Pushing Misp
ServerB = Causes a 500

**Comment by iglocska** [comment]
Ah ok. Was it anything weird pushed by MISP that caused it? Let me know if you find any unexpected behaviour with the sync and I'll look into it! :)

**Comment by elhoim** [comment]
jhemp, any update?

**Comment by elhoim** [comment]
Ping again for an update.
Do I close or is it confirmed as a bug?

**Comment by jhemp** [comment]
sorry I could not get the chance to recheck it

**Comment by adulau** [comment]
FYI, the sync API is meant to be used between MISP instances. There are major changes in the next version of MISP including the community/group definition. The best is to rely only on the ReST API.

**Comment by jhemp** [comment]
in what way does this influence the process/workflow of the sync mechanism. 
If I understand it correctly i,e, if the event is not visible for my community/group the event will not be send when published, on pull request the fist thing you get is a list of the entries visible to my community/group. So I guess that the xml will change?

**Comment by iglocska** [comment]
There are going to be extra steps in the negotiation during the sync which
might break external application from using it. With the sync there is no
real need normally to keep it consistent, it just has to be consistent
within minor versions (as the sync in general will not work beyond that).

Your best bet is really using the REST API.

**Comment by jhemp** [comment]
Closing this issue as apparently it is point less.
