### ISSUE TITLE
filters / buttons not working on server edit

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#4491]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by mokaddem** [comment]
isn't it fixed on 44d2ead?

**Comment by mokaddem** [comment]
Push/Pull rules ``modify`` button in ``servers/edit`` work for me on 00b97458c453bc7221a60ca45cdcc92da6717f49.
