### ISSUE TITLE
MISP + TheHive Integration

### ISSUE THREAD

**Issue by saeeda12** [MISP/MISP#4508]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2.15-0ubuntu0.18.04.2 (Up to date)
| MISP version / git hash   | v2.4.105 (5ead9570c63305436121f1d650aa7648db1dee61)
| Browser                   | Chrome

In trying to integrate TheHive and MISP, I have been following https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#7-misp - but what is needed on the MISP side? 

The configuration changes needed (in `application.conf`) are all set to go in the Hive instance, but it requires an auth key for a sync user. Do I have to create a sync user in my MISP instance, and therefore a sync server for my Hive instance in MISP?

And how exactly are MISP event attributes mapped to Hive case observables and vice versa? Do the attribute type and observable type need to have an exact match before they get mapped, or how does that piece work?

Thank you.

**Comment by dharshanduck** [comment]
>  Do I have to create a sync user in my MISP instance, and therefore a sync server for my Hive instance in MISP?

Yes to both

**Comment by iosonogio** [comment]
You have to create a sync user in MISP and configure TheHive with MISP address and the auth key of the sync user you created in MISP.
But you do not have to create a sync server in MISP; it is TheHive that connects to MISP.

(will let more authoritative persons reply to your last questions)

**Comment by saeeda12** [comment]
Thank you @iosonogio ! 

Yes, if anyone can provide more insight into the mapping of attributes/ observables that would be helpful!

**Comment by rommelfs** [comment]
You might want to look here: https://blog.thehive-project.org/2017/06/19/thehive-cortex-and-misp-how-they-all-fit-together/
