### ISSUE TITLE
Import of double uuids

### ISSUE THREAD

**Issue by jhemp** [MISP/MISP#452]
When I import the following xmls

<?xml version="1.0" encoding="UTF-8"?>
<response><Event><id>1738</id><org>Other Organisation</org><date>2015-03-02</date><threat_level_id>3</threat_level_id><info>Ads Gone Bad</info><published>1</published><uuid>54f63b0f-0c98-4e74-ab95-60c718689696</uuid><attribute_count>30</attribute_count><analysis>2</analysis><timestamp>1425423511</timestamp><distribution>3</distribution><proposal_email_lock>0</proposal_email_lock><orgc>Yet an Other Organisation</orgc><locked>1</locked><publish_timestamp>1428430108</publish_timestamp><Attribute><id>200439</id><type>link</type><category>External analysis</category><to_ids>0</to_ids><uuid>54f63c97-a8e4-4d20-8a2a-611918689696</uuid><event_id>1738</event_id><distribution>3</distribution><timestamp>1425423511</timestamp><comment/><value>https://www.fireeye.com/blog/threat-research/2015/03/ads_gone_bad.html</value><ShadowAttribute/></Attribute><ShadowAttribute/><RelatedEvent><Event><id>1749</id><org>NCIRC</org><date>2015-04-09</date><risk>Undefined</risk><info>asfdasf</info><alerted>0</alerted><uuid>8dae9e1a-0f3a-48c8-809e-408aa4288b76</uuid><published>1</published><analysis>0</analysis><attribute_count>1</attribute_count><orgc>GOVCERT.LU</orgc><timestamp>1428431322</timestamp><distribution>2</distribution><proposal_email_lock>0</proposal_email_lock><locked>0</locked><threat_level_id>4</threat_level_id><publish_timestamp>1428431322</publish_timestamp></Event></RelatedEvent></Event><xml_version>2.3.0</xml_version></response>

<?xml version="1.0" encoding="UTF-8"?>
<response><Event><id>1749</id><org>CE1SUS</org><date>2015-04-09</date><threat_level_id>4</threat_level_id><info>Title</info><published>1</published><uuid>8dae9e1a-0f3a-48c8-809e-408aa4288b76</uuid><attribute_count>1</attribute_count><analysis>0</analysis><timestamp>1428431322</timestamp><distribution>2</distribution><proposal_email_lock>0</proposal_email_lock><orgc>Some Organisation</orgc><locked>0</locked><publish_timestamp>1428431322</publish_timestamp><Attribute><id>200486</id><type>link</type><category>External analysis</category><to_ids>0</to_ids><uuid>54f63c97-a8e4-4d20-8a2a-611918689696</uuid><event_id>1749</event_id><distribution>2</distribution><timestamp>1425423511</timestamp><comment/><value>https://www.fireeye.com/blog/threat-research/2015/03/ads_gone_bad.html</value><ShadowAttribute/></Attribute><ShadowAttribute/><RelatedEvent><Event><id>1738</id><org>NCIRC</org><date>2015-03-02</date><risk>Undefined</risk><info>OSINT Ads Gone Bad from FireEye</info><alerted>0</alerted><uuid>54f63b0f-0c98-4e74-ab95-60c718689696</uuid><published>1</published><analysis>2</analysis><attribute_count>30</attribute_count><orgc>Crimeware</orgc><timestamp>1425423511</timestamp><distribution>3</distribution><proposal_email_lock>0</proposal_email_lock><locked>1</locked><threat_level_id>3</threat_level_id><publish_timestamp>1428430108</publish_timestamp></Event></RelatedEvent></Event><xml_version>2.3.0</xml_version></response>

Misp does not complain however the uuid of the attribute is the same, this should no be as it could cause troubles if one relies on it. 

Seen on MISP version 2.3.0

**Comment by iglocska** [comment]
Great find, thanks for the heads-up. I'll look into it soon - for now I think the simplest solution is simply adding a unique key to the uuid field on a database level, but I'll do some testing whether it is handled gracefully or whether we need something on the application level.

**Comment by elhoim** [comment]
Fixed by https://github.com/MISP/MISP/commit/a93807439d987543aa4f1b5e1d5479f6e0c83b55
