### ISSUE TITLE
Errors after server and MISP upgrade/update

### ISSUE THREAD

**Issue by sysend** [MISP/MISP#4520]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue                   | Bug, Question, Feature Request, support...
| OS version (server)          | Ubuntu 18.04.2 LTS
| Server version                 |  Apache/2.4.29 (Ubuntu)
| PHP version                    | PHP 7.2.15
| MISP version / git hash   | v2.4.105 (ad66dc55d23915a07265fe6b2964a624e3fe8235)
| PHP Settings
PHP ini path:… /etc/php/7.2/apache2/php.ini
PHP Version (>7.2 recommended): 7.2.15-0ubuntu0.18.04.2 (Up to date)
PHP CLI Version (>7.2 recommended): 7.2.15-0ubuntu0.18.04.2 (Up to date)
| PHP Extensions
Web
redis:… OK
gd:… OK
Cli
redis:… OK
gd:… OK
---------------------------------------------------------------------------------------------------
I have upgraded Ubuntu 16.04 to Ubuntu 18.04.2 LTS. After the server reboot, while trying to login in the dashboard i was receiving the following error: dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding'))));

To fix it i did:
sudo apt-get remove libapache2-mod-php7.2
sudo apt-get install php7.2

Currently i can see the letter "y" at the top left side of my screen and on the left side bellow the title "Submodules version"

In the section Submodules version i can see that everything are outdated.
As an example: app/files/taxonomies -> Outdated version (210 days, 3 hours older than super project)

But from Event Actions -> List Taxonomies -> Update Taxonomies I get the message "All taxonomy libraries are up to date already."

Same for galaxies and i also triedn to update galaxies and force update galaxies.

Furtheremore, after the upgrade i get the error "ZeroMQ settings…Python ZeroMQ library not installed correctly."

When i try to Start ZeroMQ  i see the error: 
JSON.parse: unexpected character at line 1 column 1 of the JSON data

Last but not least, while I am logged in at the top where the tabs "Home""Galaxıes""Audıt" can be found is fixed and during scrolling i do see the page running behind it.

I understand thats a lot :) please let me know if you require further details!

**Comment by adulau** [comment]
Can you do a `git status` in your MISP directory?

**Comment by sysend** [comment]
Hi,
From git status i received the following:

On branch 2.4
Your branch is up-to-date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   Plugin/DebugKit (modified content)
        modified:   PyMISP (new commits, modified content)
        modified:   app/Lib/cakephp (new commits, modified content)
        modified:   app/files/misp-galaxy (new commits)
        modified:   app/files/misp-objects (new commits, untracked content)
        modified:   app/files/noticelists (new commits, untracked content)
        modified:   app/files/taxonomies (new commits, untracked content)
        modified:   app/files/warninglists (new commits, untracked content)
        modified:   cti-python-stix2 (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        app/Config/config.php.bk
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_0
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_1
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_2
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_3
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_4
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_5
        docs/xINSTALL.debian9-postgresql.md~2175f5c289e07f611bc415fc170f6a68bdf8                                                                                                                                                             def5_6
        docs/xINSTALL.debian9-postgresql.md~HEAD
        docs/xINSTALL.debian9-postgresql.md~HEAD_0
        docs/xINSTALL.debian9-postgresql.md~HEAD_1
        docs/xINSTALL.debian9-postgresql.md~HEAD_2
        docs/xINSTALL.debian9-postgresql.md~HEAD_3
        docs/xINSTALL.debian9-postgresql.md~HEAD_4
        docs/xINSTALL.debian9-postgresql.md~HEAD_5
        docs/xINSTALL.debian9-postgresql.md~HEAD_6

no changes added to commit (use "git add" and/or "git commit -a")

Thank you for the support.

**Comment by sysend** [comment]
following the above comment i did git commit -a and submodules version status now has been set to "OK".

But why did that happened? Can i have it configured as automated? :)
