### ISSUE TITLE
Questions re' signature whitelist

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4521]
I'm looking for insight about the behavior with signature whitelists. I understand how to add via the WebUI. A few newbie questions. Thanks!!

1. Will all methods of retrieving IOCs (e.g. WebUI search, API URLs, PyMISP) not include NIDs that match whitelisted signatures? https://github.com/MISP/MISP/issues/3772 seems to report issues with this.
2. Is this list visible through PyMISP so a custom ingestion client can filter out any matches and not ingest them? (As per https://github.com/MISP/MISP/issues/2313 seems like maybe not) We had a case where 8.8.8.8 came in from a premium feed and would like to avoid that in our PyMISP code.

**Comment by SteveClement** [comment]
For case 2. use warninglists, there are examples in the PyMISP repo.

1. I am not sure about the scope, @iglocska  knows that best.

**Comment by github-germ** [comment]
Referring to my original questions:
1. Is whitelisting working now as per #3772?
2. Thx, I do see the `PyMISP.search` has the `enforce_warninglist` arg, and that should meet our objective there.
