### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4522]
Hello, is there any default LDAP configuration someone can use to integrate MISP with LDAP. I’ve gone through all of the issues here related to LDAP and tried every single configuration, but none have worked. Should the changes for LDAP be made in the ssl.conf file or config.php or both?

If you have LDAP working could you please share your configuration files or a template that we can follow to have it working. 

Thanks.

**Comment by angarod** [comment]
Take a look at https://github.com/MISP/MISP/issues/1620

**Comment by rommelfs** [comment]
#1620 is the best we have for now. If you would like to document, let us know.

**Comment by trolldbois** [comment]
Go check #6189
