### ISSUE TITLE
API: Updating ORG value

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#453]
We had a request for PyMISP - https://github.com/CIRCL/PyMISP/issues/3 and we were wondering if the ORG value can be updated. As far as I know, changing the ORG value would break the overall MISP sharing model or is it something possible to do via the API.

**Comment by iglocska** [comment]
You are indeed correct, updating the org value should not be possible at all. The edit action simply ignores the field. The only way to do it is via the database directly.

**Comment by adulau** [comment]
Ok thank you. I'll close the two issues then.

**Comment by jaegeral** [comment]
Sorry to comment on an old issue, but i indeed would like to change the org of an event as well. The event has not been published to any remote MISp instances and it would at least be handy to change ownership if you delete the local org.

Btw. is there already a small script that interacts with the database directly to change org value?

**Comment by iglocska** [comment]
If you don't mind going through the database, you could do the following:
`UPDATE `events` SET `org_id` = [org_id] WHERE `id` = [event_id];`

As long as it hasn't been published, it should be no problem apart from the logs indicating the old organisation name on your local instance.

**Comment by jaegeral** [comment]
awesome, did it, worked out good, maybe we could implement that in case someone deletes an org.

find the password in
/var/www/MISP/app/Config/database.php 

```
mysql misp -u misp -p
Update events SET org_id = $NEW WHERE events.org_id LIKE $OLD;
```

replace $NEW witht he id of your new org and $OLD with the old ones.

In Case someone wants to do that.

Thx
