### ISSUE TITLE
Active Directory Integration

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4532]
We are trying to integrate MISP to allow users to use their government issued PIV cards  for Active Directory integration. Right now I am being prompted to enter my PIV pin. This then leads me to the MISP authentication page instead of going directly into MISP. WHen i enter the local account in MISP(admin@admin.test) with the password  I have been used an hour ago. It denied me access. Does anybody have any ideas how to remediate or steps to follow for AD integration? Any help is appreciated as we are implementing MISP for the first time.

thanks,

Doug Molina
Cyber Security Specialist (Threat Intelligence)
US Department of Veterans Affairs
douglas.molina@va.gov

**Comment by rommelfs** [comment]
This might help you to pass the correct headers: https://github.com/MISP/MISP/issues/1620

**Comment by dmolina213** [comment]
We got it to present us with PIV authentication, but it landed us into the MISP login page and had to login using a local admin account. Is there a way to bypass MISP's  login and get us directly into MISP after successfully authentication with AD? Otherwise we would have to have users use a secondary login using a local account.

**Comment by rommelfs** [comment]
Have you looked into the explanation in #1620? Your PIV authentication should be able to generate a header like REMOTE_USER containing the authenticated user name. This header has to be set up in MISP.
