### ISSUE TITLE
Unable to pull events from remote server

### ISSUE THREAD

**Issue by mahesh557** [MISP/MISP#4533]
Hi,

I have configured another misp server along with the corresponding pem file.

connection test to server says
```
Local version: 2.4.96
Remote version: 2.4.105
Status: Local instance outdated, update!
Compatiblity: Compatible
POST test: Received sent package
```
--

However when attempted to pull events, it gave below error.
can you throw some light why it failed to pull.

`Pull completed. 0 events pulled, 20 events could not be pulled, 0 proposals pulled. `

**Comment by adulau** [comment]
Before doing further test, I would strongly recommend to update your MISP instance to the latest version (it's super easy). Thanks a lot.
