### ISSUE TITLE
Add_attributes

### ISSUE THREAD

**Issue by Dryannykh** [MISP/MISP#4537]
I want to add attribute of event using command: "curl --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" -d "{"event_id":"1,"value":"1.2.3.4","category":"Network activity","type":"ip-dst"}" http://192.168.13.162/attributes/add/1"
In the end i get this error: ""name":"Invalid JSON input. Make sure that the JSON input is a correctly formated JSON string. This request has been blocked to avoid an unfiltered request.", message":"Invalid JSON input. Make sure that the JSON input is a correctly formated JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/attributes\//add\/1""
What I do not this way?

**Comment by rommelfs** [comment]
If you carefully analyse your string, you find out that it contains an error:
echo '{"event_id":"1,"value":"1.2.3.4","category":"Network activity","type":"ip-dst"}' | jq .
parse error: Invalid numeric literal at line 1, column 22

Close the opening quotation mark after the first '1' and you should be good.

**Comment by Dryannykh** [comment]
Hello. Thank you for you answer!
Can you tell me can i integrate MISP with GOSINT?
--
С уважением, Юлия Дрянных вторник, 30 апреля 2019г., 13:38 +07:00 от Sascha Rommelfangen  notifications@github.com :

**Comment by Alaa-HIjazi** [comment]
I have the same issue with this curl : 
curl -k --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" -d "{"event_id":"2","value":"1.2.3.4","category":"Network activity","type":"ip-dst"}" https://misp.local/Attributes/add/2/
```
curl: (3) [globbing] unmatched close brace/bracket in column 21
{"name":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","message":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/Attributes\/add\/2"}
```

**Comment by Rafiot** [comment]
Yes, you need to use single quotes: `'{"event_id":"2","value":"1.2.3.4","category":"Network activity","type":"ip-dst"}'`, as you're using double quotes in the JSON blob.

**Comment by Alaa-HIjazi** [comment]
Oh okay, i followed the documentation. Thank you @Rafiot

**Comment by Rafiot** [comment]
can you point me to the documentation you used? We need to update that.

**Comment by Alaa-HIjazi** [comment]
Yes of course, here you go : https://www.circl.lu/doc/misp/automation/#url-arguments under GET /attributes (Example).
I also opened a support issue if is it possible to help about NIDS, i used the documentation but can't get an answer, thank you !
