### ISSUE TITLE
Failed to get status of submodules

### ISSUE THREAD

**Issue by giedriusramas** [MISP/MISP#4538]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Windows 10
| PHP version               | 7.0.25-0ubuntu0.16.04.1 
| MISP version / git hash   | 2.4.105
| Browser                   | Google chrome Version 73.0.3683.103 (Official Build) (64-bit)

### Expected behavior
Get status of submodules at  Administration -> Server Settings & Maintenance -> Submodules version -> Diagnostics -> Submodules version

### Actual behavior
I see spinning wheel only

### Logs, screenshots, configuration dump, ...

error log: /var/www/MISP/app/tmp/logs/error.log

 Error: [Exception] DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character
Request URL: /servers/getSubmodulesStatus/
Stack Trace:
#0 /var/www/MISP/app/Model/Server.php(4603): DateTime->__construct('@')
#1 /var/www/MISP/app/Model/Server.php(4576): Server->getSubmoduleGitStatus('misp-galaxy')
#2 /var/www/MISP/app/Controller/ServersController.php(1148): Server->getSubmodulesGitStatus()
#3 [internal function]: ServersController->getSubmodulesStatus()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

**Comment by mokaddem** [comment]
Hello @giedriusramas,
Thanks for the report!
You issue should be solved. If it doesn't please re-open this issue.
Cheers
