### ISSUE TITLE
Interoperability with 3rd party ticketing systems

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4542]
This is not an issue but a question. Has anyone done any interoperability of MISP with 3rd party ticketing systems.

Not sure if this is the correct forum. If not, can someone provide me a link to the forum I can post questions like this.

thanks,

Doug

**Comment by rommelfs** [comment]
MISP has a great API which can be used for almost all purposes. Integration with your ticketing system depends on your expectation of an integration. If your ticket system is extensible, integration shouldn't be too hard. 

What we use for interaction/integration: ticket tools used for various interactions between MISP, RT and URLabuse: https://github.com/rommelfs/ticket-tools/

Takedown script (integrates RT and MISP): https://github.com/MISP/misp-takedown
