### ISSUE TITLE
Required flag on taxonomies

### ISSUE THREAD

**Issue by kalyparker** [MISP/MISP#4546]
Hello,

I added some taxonomies and force the usage of it.
When I create a new event, a message appeared when I'll try to **Publish (no email)**, which is good:
"Could not publish event - no tag for required taxonomies missing: <list taxo>"
But when I'll do the same using **Publish Event**, this alert message does not appeared and the event is published anyway. 

Is it a bug or is it normal?

If it is a bug, I'll have a look tomorrow.

FYI event I don't think it depends on it, I'll run the last version on misp on ubuntu 18.04

**Comment by iglocska** [comment]
That is definitely a bug, thanks for the heads-up!
