### ISSUE TITLE
Publish event links showing up even if user does not have rights

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#455]
When adding attributes via the AJAX box, I get the "publish event" and "Publish (no mail)" links showing  in the left column even though i don't have rights to publish events.
When the event is originally displayed those links don't show up.
When adding attributes via the add attribute page, those links don't show up.
When clicking on the links, they don't work, so it is really just a display bug and not a access rights bug.

**Comment by iglocska** [comment]
Completely missed that, thanks!

**Comment by iglocska** [comment]
This is resolved.
