### ISSUE TITLE
Jobs in stuck state at "33%"?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#4550]
No idea if it's a bug, an issue with the DB but for a few days all our sync jobs remain in a stuck-state... (around 33%). All workers are ok, MISP is running the latest version (106), redis is up, MySQL is up, no errors in the logs...
Any idea how to debug this?

**Comment by iglocska** [comment]
Anything in your logs? Especially in worker-[current-date].log and worker-error.log

**Comment by xme** [comment]
Multiple times to kind of entries:

```
[2019-04-30 14:15:25 Notice: Undefined index: uuid in [/var/www/MISP/app/Model/Event.php, line 3165]
Notice Error: Undefined index: name in [/var/www/MISP/app/Model/Organisation.php, line 150]

2019-04-30 14:15:25 Notice: Undefined index: name in [/var/www/MISP/app/Model/Organisation.php, line 150]
Notice Error: Undefined index: name in [/var/www/MISP/app/Model/Organisation.php, line 152]

2019-04-30 14:15:25 Notice: Undefined index: name in [/var/www/MISP/app/Model/Organisation.php, line 152]
Notice Error: Undefined index: uuid in [/var/www/MISP/app/Model/Event.php, line 3165]](url)
```

**Comment by iglocska** [comment]
Interesting, will look into it

**Comment by SteveClement** [comment]
@xme @iglocska is this still ongoing, I feel I save this issue more then once?

**Comment by xme** [comment]
When I checked later to try to understand what happened, all sync jobs were processed... No idea why but this issue can be closed. Tx!

**Comment by xme** [comment]
Sorry, I've to reopen this issue. I've the same behaviour again. All jobs are stuck at 9%.
I see that the worker is starting the sync process, I see traffic, I see (sometimes) one event coming but no relevant errors in logs. It seems that an event is blocking the sync process. How to debug this deeper?

**Comment by iglocska** [comment]
Could you check what your php memory_limit is set to and which instance
you're syncing with? Is it ours?

**Comment by iglocska** [comment]
Also, which version are you on?

**Comment by adulau** [comment]
@xme Could you also tell us the version of the remote instance? and if these are up-to-date?

**Comment by xme** [comment]
Both instances are running 2.4.112 (remote one is CERT.eu)
PHP memory_limit is 512M (as recommended).
I'll try with a higher value.

**Comment by iglocska** [comment]
Oh yes, 512 is definitely too little. I should change the recommended
value, that was enough ~5-6 years ago before galaxies, objects, etc, but
nowadays it's definitely not enough for large events :)

**Comment by xme** [comment]
Upgraded to 4GB, also rebooted the server, same behaviour! :(
I can pull events one by one while browsing remote events via the "List Servers" menu but I can't figure out which one could prevent the sync...

**Comment by xme** [comment]
Ok, I started to sync events one by one and finally found a SQL error:

failed: SQLSTATE[22001]: String data, right truncated; 1406 Data too long for column 'description' at row 1

Does it ring a bell to you?

**Comment by iglocska** [comment]
OK, that is definitely weird. Hmph. Will think of some extra debugging
options I can add.

**Comment by xme** [comment]
I'll compare two MISP instances and the DB schemas...

**Comment by iglocska** [comment]
Woaaaah. OK< that sounds more like it.

**Comment by iglocska** [comment]
Could you run the following sql query?

```
describe logs;
```

**Comment by iglocska** [comment]
Pushed a fix that might resolve it, could you git pull?

**Comment by xme** [comment]
Fix installed + altered manually the DB schema (table logs) and it seems ok now! Let's wait for the next sync...

**Comment by iglocska** [comment]
Eeek. The point of the fix was not having to alter the table. It now truncates input that is too long ;)

**Comment by xme** [comment]
Confirmed working after the latest hour sync!
Tx for your help!

**Comment by iglocska** [comment]
Thanks for the debug session and nice find!
