### ISSUE TITLE
Integration with Viper binary analysis framework

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#456]
Integrate with the Viper binary analysis framework (https://github.com/botherder/viper / http://viper.li/).
Integration areas I am thinking about (wild wish list):
- import sample from Viper to MISP
- export sample from MISP to Viper
- lookup samples hashes (MD5/SHA1/SHA256) from MISP into Viper
- lookup samples hashes (MD5/SHA1/SHA256) from Viper into MISP
- save output of analysis from a Viper binary into MISP attributes
- use yara rules from MISP in Viper

**Comment by adulau** [comment]
Initial integration of VIPER and MISP has been pushed by @Rafiot . https://github.com/viper-framework/viper/blob/master/modules/misp.py 

Based on discussions with @Rafiot and @iglocska we could benefit in MISP from all the other Viper modules.

**Comment by elhoim** [comment]
So, adding the magic "c-list" tag to the issue? :-)

**Comment by adulau** [comment]
I'll add the tag "c-list" after the 2.4 release ;-)

**Comment by iglocska** [comment]
Too much feature creeping? :D

**Comment by Rafiot** [comment]
I started to work on the import of MISP yara rules into Viper but I didn't find a way to get the rules of one single event: I'm not sure downloading all the rules makes much sense, but it would be implementable right now if you think the opposite. 
@iglocska: can you help me there?

Also, it would be good to be able to update an event with Viper rules, I'm going to look at it in the next days, an that should be implementable immediately too.

**Comment by iglocska** [comment]
Indeed there is no easy way to do it at the moment - restsearch really
needs an event ID parameter. Check back tomorrow for it and it will
magically appear!

For the Viper rules, do you have some examples on what we need to be able
to capture / what the format would look like?

**Comment by Rafiot** [comment]
Yay :) 

For the formal, I don't realy know. There are a few examples here: https://github.com/viper-framework/viper/tree/master/data/yara

But I didn't look at a regex but that would be great to make sure they are not broken. Beside that, I mostly want them "pretty printed" and readable by humans (so with good indentation).

**Comment by Rafiot** [comment]
FYI, this is the status of the wish list: 
- [x] import sample from Viper to MISP
- [x] export sample from MISP to Viper
- [x] lookup samples hashes (MD5/SHA1/SHA256) from MISP into Viper
- [x] lookup samples hashes (MD5/SHA1/SHA256) from Viper into MISP
- [ ] save output of analysis from a Viper binary into MISP attributes
- [ ] use yara rules from MISP in Viper

**Comment by iglocska** [comment]
What I am doing now is a simply change the restsearch so that you can
simply say:

I want any yara rule type attributes from event 50 and 52 - which will then
be returned as a json/xml attribute list. Is this OK for you as a first
step?

As a second step what would be really cool and something that people have
asked for many times before: A full blown Yara export, which would convert
all attributes to a yara rule set / event.

**Comment by iglocska** [comment]
That wish list looks really cool btw.

**Comment by iglocska** [comment]
"I started to work on the import of MISP yara rules into Viper but I didn't find a way to get the rules of one single event: I'm not sure downloading all the rules makes much sense, but it would be implementable right now if you think the opposite. "

So for this:

simply post this:
{"request": {"eventid":"223", "type":"yara"}}
to:
http://192.168.56.101/attributes/restSearch
to get:
{"response":{"Attribute":[{"id":"67369","event_id":"223","category":"Payload installation","type":"yara","to_ids":true,"uuid":"55d37210-c3f4-4ed4-be2e-1b48c0a83865","timestamp":"1439920656","distribution":"0","comment":"","value":"rule silent_banker : banker\r\n{\r\n    meta:\r\n        description = \"This is just an example\"\r\n        thread_level = 3\r\n        in_the_wild = true\r\n\r\n    strings:\r\n        $a = {6A 40 68 00 30 00 00 6A 14 8D 91}\r\n        $b = {8D 4D B0 2B C1 83 C0 27 99 6A 4E 59 F7 F9}\r\n        $c = \"UVODFRYSIHLNWPEJXQZAKCBGMT\"\r\n\r\n    condition:\r\n        $a or $b or $c\r\n}"}]}}

**Comment by Rafiot** [comment]
Excellent! I'll implement it tomorrow morning in the module.

Thank you very much.

**Comment by iglocska** [comment]
My pleasure! Let me know if anything goes bad!

**Comment by elhoim** [comment]
Details about yara rules format: http://yara.readthedocs.org/en/v3.4.0/writingrules.html

More rules if you want to test: https://github.com/Yara-Rules/rules

@Rafiot the use case for extracting all yara rules from a MISP instance is: *I have got a sample where no analysis has been done, does it match any known family or campaign (yara rule wise) in my MISP instance.*

@Rafiot I have posted an attempt at a regexp (in python) to match yara rules in https://github.com/MISP/MISP/issues/592

**Comment by Rafiot** [comment]
@elhoim good point. Then we need a better way to handle the yara rules in MISP, and make sure they are all valid: right now, if you export all the rules, you get a big file full of rules (with many broken ones: 5473429a-bc10-498d-a195-46e2950d2109 contains U+201C instead of ") and no context on the event it comes from.

It seems in fact to be painful to validate a yara rule.

**Comment by iglocska** [comment]
Yup. We should look into validating it though the way that David described
asap so we don't get more junk data in there. Could also be an interesting
first use case for an external python script used for data validation.

**Comment by elhoim** [comment]
The only way to get complete validation is to extract the rule and then run it in yara and then report if there is one of them not validating.
I have a small work-in-progress script that tries to do this: https://gist.github.com/elhoim/590fd6905fe24929db39

**Comment by iglocska** [comment]
That could be a bit of a nightmare to do on the fly while syncing though,
when the validation would occur :(

**Comment by Rafiot** [comment]
This one is mostly done. the only other issues we have here are Yara related, they are already listed here: https://github.com/MISP/MISP/issues/592

Closing.
