### ISSUE TITLE
MISP Updating

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4562]
Can anyone assist me with this error: I am trying to update misp using the diagnostic page and i get this
```
Currently installed version… () 
Latest available version… () 
Status… Could not retrieve version from github 
Current branch… You are not on a branch, Update MISP will fail 
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

sh: git: command not found

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

sh: git: command not found
sh: git: command not found

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

sh: git: command not found
```

**Comment by SteveClement** [comment]
You need to be more precise.

What Operating System are we talking about.

But I can already tell you, your machine has no access to the internetz.

**Comment by dmolina213** [comment]
I am using RHEL7. Let me check if our boxes have access to the internet. When we  were setting it up we know we did. Otherwise we would not be able to pull down the install for MISP. But operations might have put us in a vlan  post setup that does not have access. Let me check on that.
thank you for you swift response. We are trying to deploy misp at our agency and we are learning as we go.

Doug

**Comment by dmolina213** [comment]
We have internet access (http/https) from the server. Do we need specific ports opened for updating?

**Comment by rommelfs** [comment]
Since this discussion is spread throughout different media (Gitter and Github issue), I add the most recent information from you here too.

Your internet access works, you have successfully installed git on the machine.
MISP still can't call `git` from the web interface.

We asked the question (on Gitter) if SELinux is enabled and blocking access to `git`.
The answer to this question is pending.

**Comment by SteveClement** [comment]
Argh, ok, gimme' me some time to make a custom **test.php** to debug this *secure* RHEL/CentOS issue.

**Comment by SteveClement** [comment]
Also, please get way more acquainted with the operating of choice and their security policies and the ways how they work, we, MISP-core, are not your go-to sysadmins failing to properly install stuff...

We do NOT have a RHEL subscription, nor do we have the time to investigate random CentOS issues.

And finally, I (personally) will be angry if you did not follow the documentation properly!

**Comment by dmolina213** [comment]
Do you have that test.php script

**Comment by SteveClement** [comment]
@dmolina213 I am working on it.

I am re-doing my RHEL install and implement all the tests as I come along, but it will take me some more time :(
We had a weird bug today that munched up all my debug time.

**Comment by SteveClement** [comment]
I now have a very rudimentary test.php script, to try it:

```bash
sudo -u apache wget --no-cache -O /var/www/MISP/app/webroot/test.php https://raw.githubusercontent.com/SteveClement/misp-test/master/test.php
```

Then browser to your MISP_BaseURL/test.php

If this issue is not active anymore, please close.

**Comment by SteveClement** [comment]
closed due to inactivity.
