### ISSUE TITLE
potential memory issue with PyMISP tag functions

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4565]
@github-germ posted to gitter:

hi there... looking for some wisdom on how to find root cause of reported memory issues when simply a pymisp client is simply requesting `GET /tags/view/1388`

```
2019-05-01 15:25:00 Error: Fatal Error (1): Allowed memory size of 17179869184 bytes exhausted (tried to allocate 268435464 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 688]
2019-05-01 15:25:00 Error: [InternalErrorException] Internal Server Error
    Request URL: /tags/view/1388
    Stack Trace:
    #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 688)
    #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 688, Array)
    #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
    #3 [internal function]: App::shutdown()
    #4 {main}
```
php.ini has memory_limit set to 24G, not the 16G reported in the error above (17179869184).

and, webui diagnostics seems to think memory_limit is only 16M

```
PHP Settings

PHP ini path:… /etc/opt/rh/rh-php71/php.ini
PHP Version (>7.0.16 recommended): 7.1.8 (Up to date)
PHP CLI Version (>7.0.16 recommended): 7.1.8 (Up to date)

The following settings might have a negative impact on certain functionalities of MISP with their current and recommended minimum settings. You can adjust these in your php.ini. Keep in mind that the recommendations are not requirements, just recommendations. Depending on usage you might want to go beyond the recommended values.

max_execution_time (1800)… OK (recommended: 300)
memory_limit (16M)… Low (recommended: 512M)
upload_max_filesize (256M)… OK (recommended: 50M)
post_max_size (256M)… OK (recommended: 50M)
```

@iglocska replied

yeah sounds like a bug. It is probably loading some crazy associated data list

@github-germ that's ok. however, i do have a question as we do seem to be hitting the wall often on memory

@iglocska with 16G process memory?

@github-germ i have a simple client that grans the tags, then if it doesn't see one it wants, it creates it. the first GET can hang sometimes for 6 minutes, seemingly waiting on memory or sometimes if aborts and we see out of mem in error.log. if it does get past the first one b/c the mem might've freed up, same thing can happen on the next.
Andras Iklody

@iglocska think we use 1500M on our operational instance o.O

@github-germ now with 24G

@iglocska which API endpoints are you using? the GET especially

@github-germ PyMISP

@iglocska hmm. which function in pymisp?

@github-germ
```
[20190502-18:12:39 DEBUG (139881402533696)] https://localhost:443 "GET /tags HTTP/1.1" 200 534029
[20190502-18:12:39 DEBUG (139881402533696)] Starting new HTTPS connection (1): localhost
[20190502-18:18:31 DEBUG (139881402533696)] https://localhost:443 "GET /tags/view/1388 HTTP/1.1" 200 168
[20190502-18:18:31 DEBUG (139881402533696)] Starting new HTTPS connection (1): localhost
[20190502-18:18:31 DEBUG (139881402533696)] https://localhost:443 "POST /tags/edit/1388 HTTP/1.1" 200 266
[20190502-18:18:31 DEBUG (139881402533696)] Starting new HTTPS connection (1): localhost
[20190502-18:24:58 DEBUG (139881402533696)] https://localhost:443 "GET /tags/view/1388 HTTP/1.1" 200 168
[20190502-18:24:58 DEBUG (139881402533696)] mkTag{}: tag revised: {'id': '1388', 'name': 'Unvetted', 'colour': '#7de9de', 'exportable': False, 'org_id': '0', 'hide_tag': False, 'user_id': '0', 'numerical_value': None, 'count': 275, 'attribute_count': 0}
resulting tag: {'id': '1388', 'name': 'Unvetted', 'colour': '#7de9de', 'exportable': False, 'org_id': '0', 'hide_tag': False, 'user_id': '0', 'numerical_value': None, 'count': 275, 'attribute_count': 0}
```

`get_tags_list`, followed by either `edit_tag` and `get_tag` (b/c `edit_tag` does not return the revised tag dict) --or-- `new_tag` -- pretty straight forward!!

@iglocska will have a look tomorrow. sounds like something silly being loaded that really shouldn't be

**Comment by github-germ** [comment]
@Rafiot -- just retested this with 2.4.106 and the issue persists.

**Comment by github-germ** [comment]
possible hint... mysql `show processlist;` when nothing else appears to be active in MISP has the following. curious as to the `Creating sort index`...
```
| 4192 | root        | localhost | misp | Query   |    0 | init                     | SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`hide_tag |    0.000 |
| 4198 | root        | localhost | misp | Query   |   78 | Creating sort index      | SELECT `Attribute`.`id`, `Attribute`.`event_id`, `Attribute`.`object_id`, `Attribute`.`object_relati |    0.000 |
```

and while the client is still hanging the `SELECT Tag` query completed, but that other one is still going and accruing mysql process `Time`.

**Comment by Rafiot** [comment]
I trust you, the python method does a POST, nothing else. This is definitely not a bug related to PyMISP.

@iglocska when you have a sec, this one is for you.
