### ISSUE TITLE
Scheduled Tasks of type "pull_all" don't create jobs for pull activated servers.

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#457]
Reported by one of our user.

There is a bug in /var/www/MISP/app/Console/Command/ServerShell.php in function enqueuePull(), line 87

Proposed fix:

replace
$servers = $this->Server->find('all', array('recursive' => -1, 'conditions' => array('push' => 1)));
by
$servers = $this->Server->find('all', array('recursive' => -1, 'conditions' => array('pull' => 1)));

Hope this helps.

**Comment by iglocska** [comment]
Good catch, thanks!
