### ISSUE TITLE
Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)

### ISSUE THREAD

**Issue by ESL482** [MISP/MISP#4572]
Hi ,

I installed MISP on ubuntu 18.04 , all things working fine but i am getting one warning  the title one , when i tried to do that i am getting internal error.i checked many solutions but nothing works fine for me.please suggest something to solve this issue.

error logs :

2019-05-06 12:25:06 Error: [Error] Class 'ResqueStatus\ResqueStatus' not found
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Controller/ServersController.php(1044): Server->workerDiagnostics(0)
#1 [internal function]: ServersController->serverSettings()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#5 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}

Thanks

**Comment by iglocska** [comment]
Which installation guide did you use to install MISP?

**Comment by ESL482** [comment]
https://misp.github.io/MISP/INSTALL.ubuntu1804/ ... this one only

**Comment by iglocska** [comment]
Interesting. Perhaps a skipped step?

**Comment by ESL482** [comment]
no..i did all the steps mentioned there some where i got error & some how i resolved & finished it . can you please help me to know what went wrong .

**Comment by iglocska** [comment]
"got error & somehow i resolved & finished it" is a bit difficult to debug without invoking some demonic powers and engaging in human sacrifices. 

However, could you rerun this part?

```
# <snippet-begin 1_installCake.sh>
installCake () {
  debug "Installing CakePHP"
  # Once done, install CakeResque along with its dependencies 
  # if you intend to use the built in background jobs:
  cd ${PATH_TO_MISP}/app
  # Make composer cache happy
  # /!\ composer on Ubuntu when invoked with sudo -u doesn't set $HOME to /var/www but keeps it /home/misp \!/
  sudo mkdir /var/www/.composer ; sudo chown $WWW_USER:$WWW_USER /var/www/.composer
  $SUDO_WWW php composer.phar require kamisama/cake-resque:4.1.2
  $SUDO_WWW php composer.phar config vendor-dir Vendor
  $SUDO_WWW php composer.phar install

  # Enable CakeResque with php-redis
  sudo phpenmod redis
  sudo phpenmod gnupg

  # To use the scheduler worker for scheduled tasks, do the following:
  $SUDO_WWW cp -fa ${PATH_TO_MISP}/INSTALL/setup/config.php ${PATH_TO_MISP}/app/Plugin/CakeResque/Config/config.php

  # If you have multiple MISP instances on the same system, don't forget to have a different Redis per MISP instance for the CakeResque workers
  # The default Redis port can be updated in Plugin/CakeResque/Config/config.php
}
# <snippet-end 1_installCake.sh>
```

**Comment by SteveClement** [comment]
Is this still an issue.
