### ISSUE TITLE
I am unable to enter new events.

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4582]
I am unable to enter new events. When i hit submit it say internal error

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, 
| OS version (server)       | Red hat 7
| OS version (client)       |  10, 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.104hash of the commit
| Browser                   |Chrome

### Expected behavior
Supposed to add the event

### Actual behavior
Recieve Internal error instead

### Steps to reproduce the behavior
Enter and event

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/42444130/57322658-a88c1180-70c9-11e9-970f-e460d3c99489.png)

**Comment by SteveClement** [comment]
Dear, I think I have a similar issue.

Please do the following:

```
tail -f /var/www/MISP/app/tmp/logs/error.log 
```

Double check if redis is running and accessible.

**Comment by dmolina213** [comment]
tail -f /var/www/MISP/app/tmp/logs/error.log
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.1
Model::_doSave() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1970
Model::save() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1760
UsersController::login() - APP/Controller/UsersController.php, line 1011
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php9
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 13
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 7
[main] - APP/webroot/index.php, line 92

**Comment by SteveClement** [comment]
Can you please try and update MISP (via the GUI) and see if it is all good now?

**Comment by dmolina213** [comment]
Steve, Are you pushing some updates? I will try that today. but for some reason when I get to the diagnostic page. I get an Internal Error thrown at me. This is the output of the error log:
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHan)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::hand)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalEr)
#3 [internal function]: App::shutdown()
#4 {main}
 And I suspect, once I get that working I will still have that issue not being able to update because the GUI is unable to find the GIT command even if GIT is installed. But let me work on getting the diag page accessible.

**Comment by dmolina213** [comment]
Let me try to resolve the diagnostic page issue

**Comment by SteveClement** [comment]
You can always update on the command line:

```bash
cd /var/www/MISP
sudo -u apache git pull
```

**Comment by SteveClement** [comment]
And for good measure, to make sure the database is up to date:

```bash
sudo -u apache /usr/bin/scl enable rh-php72 -- /var/www/MISP/app/Console/cake Admin updateDatabase
```
