### ISSUE TITLE
Server settings

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4586]
### Work environment

| Questions                 | Answers
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Suppport 
| OS version (server)       | Red hat 7
| OS version (client)       |  10, 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.104 hash of the commit
| Browser                   |Chrome

### Expected behavior
Trying to configure in MISP Settings to the default value

### Actual behavior
Get an error 'request failed due to unknown reason

### Steps to reproduce the behavior
Go into MISP Settings
Set value for :

Recommended | MISP.python_bin
-- | --

to: /var/www/MISP/venv 

I get the error and value is not set.

**Comment by SteveClement** [comment]
You need to set it to the actual binary:
```
/var/www/MISP/venv/bin/python
```

**Comment by dmolina213** [comment]
I tried doing that. but for some reason the value would not set.

**Comment by SteveClement** [comment]
@dmolina213 that is interesting. Let's try doing this on the command line:

```bash
sudo -u apache /usr/bin/scl enable rh-php72 -- /var/www/MISP/app/Console/cake Admin setSetting "MISP.python_bin" "/var/www/MISP/venv/bin/python"
```
