### ISSUE TITLE
"Download as..." menu different if event is published or not published

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#459]
The "Download as..." menu is different if event is published or not published

**Comment by iglocska** [comment]
This is correct, the thought behind it is this: unpublished events are not yet fit for export / automation / redistribution (they are also not synced). XML / JSON exports always work, as they include the published tag, so the information is not lost that these are in fact not yet published events.

**Comment by elhoim** [comment]
Makes sense. I tried really hard now to find a use case where this would be useful to have other extracts, and could not find even a corner case one. I don't know what I was thinking... :)
