### ISSUE TITLE
Feed fetch job stucked at 50% 

### ISSUE THREAD

**Issue by anaike** [MISP/MISP#4596]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat Enterprise Linux 
| OS version (client)       | 7
| PHP version               | 7.1
| MISP version / git hash   | 2.4.101
| Browser                   | All

I enabled 5 feeds. Three of them are custom feeds (Simple CSV Parsed Feed with a fixed event); the other two are the CIRCL OSINT Feed and The Botvrij.eu Data feed.

I scheduled the feed_fetch job every 12h under the Scheduled Tasks section.

### Expected behavior

The feed_fetch jobs that start automatically reach the status "Completed" with the "Job done" message. New events are saved and the target events are updated.

### Actual behavior

The feed_fetch jobs that start automatically. The jobs related to the default feeds reach the status "Completed" with the "Could not fetch the feed message". The jobs related to the custom feeds remain blocked at 50%. The curious thing is that actually,  new events are saved and the target events are updated. After some days all the jobs that start remain in the "Queued" status. To restore the situation i have to restart all the workers. 

#### Jobs status:

Feeds 1 and 2 are the default feeds. The other ones are the custom feeds. As can be seen, even if the fetch feed job is blocked at 50%, the related event is updated and published.  

![image](https://user-images.githubusercontent.com/39911937/57378518-3be64500-71a5-11e9-9654-e134833ef8b8.png)

This is the situation after some days

![image](https://user-images.githubusercontent.com/39911937/57379531-60dbb780-71a7-11e9-94ad-f5e857f846b5.png)

#### Logs:

Under the list logs section can be seen that the attributes are added even if the job is stucked at 50%

![image](https://user-images.githubusercontent.com/39911937/57378850-e8c0c200-71a5-11e9-90b3-c8054402c341.png)

**Comment by mm4work** [comment]
Had a very similar problem on 2.4.102. and 2.4.106 that seems to be resolved by fixing the write status of /var/www/MISP/.git/ORIG_HEAD file. Go to Administration -> Server Settings and Maintenance -> Diagnotics and look at the "Writeable Directories and files" sections. If there are any errors listed there, correct them.

**Comment by SteveClement** [comment]
@anaike the feed backend is being re-worked by @iglocska and should start being more stable in the very near future.
Generally if you see data coming-in, all is good and there should be no reason for it to stop.
If it stops always at the same moment, there might be issues ingesting a particular event from your source feed, going through the logs will then shed some light onto the issue.
If it seems random, perhaps the network connection was unstable or the worker that handled that specific fetch quit unexpectedly.

**Comment by JakubOnderka** [comment]
This should be fixed in #5052.
