### ISSUE TITLE
YaraExport::getPythonVersion() not defined

### ISSUE THREAD

**Issue by julien-merle** [MISP/MISP#4614]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian,
| OS version (client)       | Debian
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, e9bc2a40f4c2191322cce9917a34f7f2327f1f5a

### Actual behavior

[This commit](https://github.com/MISP/MISP/commit/fc1f15c4c01c6a22fa589158709d09002e842542) contain bug : 

The YaraExport::getPythonVersion() is not defined ( app/Lib/Export/YaraExport.php L+131 : $this->getPythonVersion() )

The YaraExport has no inheritance and the method getPythonVersion() is not defined in class.

### Steps to reproduce the behavior

Just clic on export yara or yara-json in MISP web interface 

### Logs, screenshots, configuration dump, ...

Error: Call to undefined method YaraExport::getPythonVersion()
#0 /var/www/MISP/app/Lib/Export/YaraExport.php(90): YaraExport->__process_file(Array)
#1 /var/www/MISP/app/Model/Event.php(6136): YaraExport->footer(Array)
#2 /var/www/MISP/app/Console/Command/EventShell.php(74): Event->restSearch(Array, 'yara-json', Array, false, '5')
#3 /var/www/MISP/app/Console/Command/EventShell.php(63): EventShell->__runCaching(Array, Array, '5', 'yara')
#4 /var/www/MISP/app/Console/Command/AppShell.php(32): EventShell->cache()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('cache', 1, Object(MonologInit\MonologInit), '5')
#10 {main}

**Comment by SteveClement** [comment]
Can you please pull and try again?

This https://github.com/MISP/MISP/pull/4615 should have fixed it.
