### ISSUE TITLE
Add an option to set a threshold for email notification if an event is older than a specific time-frame

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4618]
Add an option to set a threshold for email notification if an event is older than a specific time-frame.

The idea is to avoid to send email notifications if an older event get synchronised.

**Comment by iglocska** [comment]
We have that. Check your server settings.

**Comment by adulau** [comment]
I know but it's either buggy or not applied on date but the timestamp ;-)

**Comment by iglocska** [comment]
Should be fixed now
