### ISSUE TITLE
Select subsets for mass-edits

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#462]
Allow for mass edits to select subsets of the attributes for editing.

The type of UI element I am thinking about is the gmail mass-select tool:
![gmail UI element](http://zdnet2.cbsistatic.com/hub/i/2014/10/04/8434bc0f-4bac-11e4-b6a0-d4ae52e95e57/c9890db077dcc884557a8c2a65627eec/how-to-mark-unread-emails-as-read-gmail-2.png)

The use cases I am thinking about are:
1. select attributes with a certain distribution level,
2. select attributes set as IDS
3. select attributes set as not IDS
4. select attributes of a certain type
5. select attributes of a certain category

**Comment by adulau** [comment]
It was implemented sometime ago. Feel free to reopen if you think that the issue was not solved.
