### ISSUE TITLE
Installer on Ubuntu 18.04: sudo prompt breaks the install

### ISSUE THREAD

**Issue by wasserman** [MISP/MISP#4620]
I tried to install using the curl method with options: -c -M -D.
I'm running Ubuntu 18.04 via the EC2 AMI.
When prompted to create the misp account, I agreed.
The installer later hangs at a "sudo" prompt.  I have no password set.  After failing 3 times I get an error that pointed me to this:
    https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh#L1424

Although the install continues and many subsequent steps fail along the way.

The line is: $SUDO_USER git clone https://github.com/MISP/misp-modules.git
The sudo command used is:  sudo -H -u ${MISP_USER} -g staff

The cloud sudoers doesn't require a password.  After deeper analysis I figured out that the "-g staff" was what is triggering the prompt.  I changed my sudoers from:
  ubuntu ALL=(ALL) NOPASSWD:ALL
to:
  ubuntu ALL=(ALL:ALL) NOPASSWD:ALL

This made the script work.  My recommendation is for the installer to do a "sudo -l" and verify that the sudoers is configured to allow passwordless groups or suggest how to do so.  Also, if the git clone fails then you may want to short-circuit it since there is no real benefit from continuing through the install since it just adds confusion later.

Thanks!

**Comment by SteveClement** [comment]
Spot on! I had the same issue on our automated builds.

Let me think how to mitigate this properly.

I basically do exactly what you did: https://github.com/MISP/misp-packer/blob/8c43ac0d30dd6f9af3acf78db11ecfac5af47fd6/scripts/users.sh#L9

But good catch! Thanks.

**Comment by SteveClement** [comment]
I implemented a fix. Let me know if it works for you.

**Comment by wasserman** [comment]
No, I get the same error.  The change allows the *misp* user to sudo with a group without a password, but I am running the script as the *ubuntu* user.  I think your staff group line (L144 and L399) could use a double sudo to not require changes to the account running the install, yet leveraging the misp account's ability to do it:
  SUDO_USER="sudo -u ${MISP_USER} sudo -H -u ${MISP_USER} -g staff"

I know this suggestion is a bit of a hack, but it avoids messing with the current user's sudo rules.

Then the only case that may be missing is if the misp account exists with an existing sudoers not allowing group passswordless sudo.

To handle this, L1806 could just check/grep "sudo -l" as the misp user for "(ALL : ALL) NOPASSWD: ALL"

I'm no bash guru, but the current line 1806 appears to create/overwrite the sudoers.d/misp regardless of if it already exists.  

Thanks for taking a look at this so quickly!  I'm new to MISP and this install script is a big help in getting started.

**Comment by jekil** [comment]
Still getting the same issue on EC2.

**Comment by JessScull** [comment]
I'm still getting the same issue with ubunutu

**Comment by systemxcom** [comment]
**Issue:**
Installer requring password for ubuntu cloud image (OpenStack Stein) that has no password and uses key pairs for authentication.  

**Installer Request That Cannot Be Fulfilled:**

```
Next step: Cloning misp-modules
[sudo] password for ubuntu:
``` 

**System:** Ubuntu 18.04, bionic-server-cloudimg-amd64.img

**Installer:**
```
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -A
```

**Attempted Solution 1:**
Build fresh image with root ubuntu user and ubuntu as username and added root password so image can be run in root without the key pair, (not advised).

Results: Can log into instance with without requiring the key using name and password but when installer runs it will not accept the known good password for ubuntu.

**Attempted Solution 2:**
Build fresh image and added to the /etc/sudoers described in the proposed solution above:
ubuntu ALL=(ALL:ALL) NOPASSWD:ALL
Rebooted Machine
Run Installer
Results: When installer runs it request a password for ubuntu and on empty return it complains:
```
[sudo] password for ubuntu: 
Sorry, try again.
[sudo] password for ubuntu:
```

Please advise.

In any case, MISP Rules!

Thank You!
