### ISSUE TITLE
misp-wipe ; starts at organizations id > 2

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#4625]
Why are the 'to delete' IDs of users and organizations in tools/misp-wipe/misp-wipe.sql set to > 3 and >2?

`
DELETE FROM `users` WHERE id > 3;
DELETE FROM `organisations` WHERE id > 2;
`

Seems to work perfectly well when both set to > 1

**Comment by SteveClement** [comment]
Good question, maybe @iglocska knows.

**Comment by iglocska** [comment]
1 will work fine. 0 should work too (it recreates the default org+user on the first login)

**Comment by SteveClement** [comment]
@cudeso feel free to send a PR with a default value that makes sense for the larger community.

Thanks for the contribution.
