### ISSUE TITLE
XML Import with an uspecified group

### ISSUE THREAD

**Issue by jhemp** [MISP/MISP#463]
If you want to import an xml via 'Add Misp xml' and the org/orgc are not present in the Misp instance causes the following error:

PDO error
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org' cannot be null

Error: An Internal Error Has Occurred.
Stack Trace

    APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 458 → PDOStatement->execute(array)
    APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 424 → DboSource->_execute(string, array)
    APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 1012 → DboSource->execute(string)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 1854 → DboSource->create(AppModel, array, array)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 2265 → Model->save(array, array)
    APP/Model/Attribute.php line 1010 → Model->saveMany(array)
    APP/Model/Attribute.php line 388 → Attribute->__afterSaveCorrelation(array)
    [internal function] → Attribute->afterSave(boolean, array)
    APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 240 → call_user_func_array(array, array)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 1883 → CakeEventManager->dispatch(CakeEvent)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 2265 → Model->save(array, array)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 2485 → Model->saveMany(array, array)
    APP/Model/Event.php line 1415 → Model->saveAssociated(array, array)
    APP/Controller/EventsController.php line 2127 → Event->_add(array, boolean, array)
    APP/Controller/EventsController.php line 1050 → EventsController->_addXMLFile()
    [internal function] → EventsController->add_xml()
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(EventsController, array)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 191 → Controller->invokeAction(CakeRequest)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 165 → Dispatcher->_invoke(EventsController, CakeRequest)
    APP/webroot/index.php line 96 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by iglocska** [comment]
Hmm, I am having a hard time reproducing it. Org should be set
automatically to whatever your user is using.

For example, I created a simple file that should work to test:

<Event>
<date>2015-04-14</date>
<threat_level_id>4</threat_level_id>
<info>new</info>
<published>0</published>
<analysis>0</analysis>
<distribution>1</distribution>
<Attribute>
<category>Network activity</category>
<type>ip-dst</type>
<value>7.6.5.4</value>
<to_ids>1</to_ids>
<distribution>1</distribution>
</Attribute>
</Event>

I've also tried one with the organisations embedded:

<Event>
<date>2015-04-14</date>
<threat_level_id>4</threat_level_id>
<orgc>Iglocska</orgc>
<org>Iglocska</org>
<info>new</info>
<published>0</published>
<analysis>0</analysis>
<distribution>1</distribution>
<Attribute>
<category>Network activity</category>
<type>ip-dst</type>
<value>7.6.5.4</value>
<to_ids>1</to_ids>
<distribution>1</distribution>
</Attribute>
</Event>

I upload it using the add xml button - seems to work fine.

Could you post an example of a file that fails so I can reproduce it?

**Comment by Rafiot** [comment]
Still broken?

**Comment by Rafiot** [comment]
No answer, assuming fixed.
