### ISSUE TITLE
Does not match the installer sum

### ISSUE THREAD

**Issue by hattek** [MISP/MISP#4637]
Something happened to the installer?

Tried to run on a newly installed Ubuntu 18.04 server:

curl -fsSL https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh | bash -s

Next step: Checking if we are run as the installer template
Next step: Checking if we are uptodate and checksums match
shasum: bash:
sha1: db6d3e754a83f26c5dcfde255506b02b5514c7e3 does not match the installer sum of:
Delete installer, re-download and please run again.

**Comment by Jtrombley-cr** [comment]
Same issue here. It's the same hash I see in https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh.sha1

**Comment by SteveClement** [comment]
The issue is with the pipe.

I changed the documentation and the installer shoudl henceforth be run like this:

```bash
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh
```

**Comment by SpencerLN** [comment]
Still having the same issue here, even when ran with the above alternate instructions.

`$ wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
--2019-05-24 05:35:59--  https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93945 (92K) [text/plain]
Saving to: ‘/tmp/INSTALL.sh’

/tmp/INSTALL.sh               100%[=================================================>]  91.74K  --.-KB/s    in 0.03s

2019-05-24 05:35:59 (3.22 MB/s) - ‘/tmp/INSTALL.sh’ saved [93945/93945]

$ sha1sum /tmp/INSTALL.sh
792029108d63c94996b250ab3cf228d23be05419  /tmp/INSTALL.sh

$ bash /tmp/INSTALL.sh
Next step: Checking if we are run as the installer template
Next step: Checking if we are uptodate and checksums match
sha1: 1216ca60a1ab9e707aa49f77bd051e4e8752b04b does not match the installer sum of: 792029108d63c94996b250ab3cf228d23be05419
Delete installer, re-download and please run again.`

I see that INSTALL.sh in the 2.4 branch was updated ~21 hours ago, but the INSTALL.sh.sha1 file was updated 7 days ago. I'm guessing this is causing the issue.

**Comment by SteveClement** [comment]
This is a regression, this PR https://github.com/MISP/MISP/pull/4639 broke the installer.

**Comment by SteveClement** [comment]
Will be fixed soon.

**Comment by elbrianmcdonald-dev** [comment]
Has this been fixed? I am having the same issue.

**Comment by joshbacker** [comment]
I'm also getting the same issue has it been fixed yet? If so what can I do?

**Comment by samsowa** [comment]
Is this issue be resolved? I have the same issue when running on CentOS7. Please help.

**Comment by elliottempest** [comment]
Ubuntu 18.04 still having this issue also

**Comment by ssdebruyn** [comment]
Any Luck with this. It works fine from my home PC. But when doing it behind a proxy I have this problem.

**Comment by SteveClement** [comment]
@ssdebruyn if it fails behind a proxy, chances are high something is cached. 

Try wget with '--no-cache'

**Comment by suleman924** [comment]
same issue need solution
