### ISSUE TITLE
Invalid plyara version / plyara not installed. 

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#4643]
With the new update, it requested me to install plyara. After doing so, it still keeps notifying that it's not installed. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Windows
| PHP version               | 7.2
| MISP version / git hash   | 2.4.107, 9f7cf9ffca9f65eec3fa85cdc7c916b2e0901e0b
| Browser                   | Chrome
### Expected behavior
Plyara is correctly installed, and should be confirmed by MISP's diagnostics page

### Actual behavior
Plyara should be installed, but is not detected by MISP's diagnostics page

### Steps to reproduce the behavior
Running the command "pip install plyara" in /var/www/MISP/venv/bin as root

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/42775319/57836520-2edade80-77c1-11e9-80c0-ffcdc049b13f.png)

**Comment by adulau** [comment]
pip needs to be run in the venv of MISP. Could you install it in the venv?

**Comment by mik5z** [comment]
> pip needs to be run in the venv of MISP. Could you install it in the venv?

That's what I did. I went to /var/www/MISP/venv/bin and ran the command pip3 install plyara. When doing so, it actually installs it in another directory, and not in the venv folder. It states the following: 

Requirement already satisfied: plyara in /usr/local/lib/python3.6/dist-packages (2.0.2)
Requirement already satisfied: ply>=3.11 in /usr/local/lib/python3.6/dist-packages (from plyara) (3.11)

Edit: typos

**Comment by SteveClement** [comment]
Please run:

```bash
sudo -u www-data /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/yaratest.py
```

**Comment by SteveClement** [comment]
> > pip needs to be run in the venv of MISP. Could you install it in the venv?
> 
> That's what I did. I went to /var/www/MISP/venv/bin and ran the command pip3 install plyara. When doing so, it actually installs it in another directory, and not in the venv folder. It states the following:
> 
> Requirement already satisfied: plyara in /usr/local/lib/python3.6/dist-packages (2.0.2)
> Requirement already satisfied: ply>=3.11 in /usr/local/lib/python3.6/dist-packages (from plyara) (3.11)
> 

In that case you might be doing it wrong.

This is the correct output:

```bash
sudo /var/www/MISP/venv/bin/pip install plyara 
Collecting plyara
  Downloading https://files.pythonhosted.org/packages/05/45/0d3d1c68fcf8a866b7dedfe875fb56a9e55bcd82bcfd1473c17264e51bd4/plyara-2.0.2-py2.py3-none-any.whl
Requirement already satisfied: ply>=3.11 in /var/www/MISP/venv/lib/python3.7/site-packages (from plyara) (3.11)
Installing collected packages: plyara
Successfully installed plyara-2.0.2
```
