### ISSUE TITLE
Audit logging for access to data (especially specific personal data)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4646]
Audit logging for access to data (especially specific personal data) on UI and API level

**Comment by iglocska** [comment]
How would we decide what would constitute as personal data?

**Comment by adulau** [comment]
From the notice list?

**Comment by adulau** [comment]
Thanks @iglocska (and thanks for the law enforcement agencies feedback for the idea during the enforce training) e89b4525ad2cfefc4a3a7fd90a9ea8ec1c9b9ee0
