### ISSUE TITLE
Integrate Cuckoo with Malware Information Sharing Platform (MISP)

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#465]
Related cuckoo ticket: https://github.com/cuckoobox/cuckoo/issues/525

**Comment by adulau** [comment]
Would a converter from MAEC ouput of cuckoo to MISP enough?

**Comment by adulau** [comment]
There is also the OpenIOC generator for cuckoo: https://github.com/iocaware/iocgen/tree/master/iocaware_openioc 

We will give a try.

**Comment by iglocska** [comment]
Looking at the samples it produces it won't really work. The OpenIOC import tool is pretty weak as it relies on there being little to no branching in the source file. We really need a hierarchical structure for attributes asap :)

**Comment by botherder** [comment]
From my side I feel that most work should probably be done on MISP side. From Cuckoo side I can facilitate introducing whatever reporting format might be more useful for MISP integration.

**Comment by elhoim** [comment]
For the MAEC part, there was a comment in #203 from botherder: <<I wouldn't rely on our MAEC support as in fact we (as core developers) are not supporting it for real. Unless there are solid and continuous external contributions on keeping that report alive, we're not going to bother keeping up with all the new versions that MITRE puts out.>>

For openIOC, Andras mentioned the problem, mostly related to internal data format limitation from MISP.

Two other alternatives:
1. parsing in MISP of JSON reporting format from cuckoo;
2. custom reporting module in cuckoo to output MISP compatible XML or JSON.

The second one has the benefit of additional visibility for MISP via the cuckoo project.

**Comment by seanthegeek** [comment]
I would like to write a Cuckoo export module for MISP. Should be pretty easy with pyMISP. Where is the JSON schema documented?

**Comment by Rafiot** [comment]
Merged upstream :) 
https://github.com/cuckoosandbox/cuckoo/blob/bb78d5deb1c868e50f84210302686f3a87bdd822/modules/reporting/misp.py
