### ISSUE TITLE
Import of new taxonomies

### ISSUE THREAD

**Issue by cudor** [MISP/MISP#4654]
When new taxonomies are added to https://github.com/MISP/misp-taxonomies, is a MISP instance able to detect them and is there a mechanism to import them into a MISP instance (either all new taxonomies or only selected ones that are wanted/needed)?

**Comment by SteveClement** [comment]
No, you have to click on update taxonomies, OR update the submodule in diagnostics.
OR on the CLI:

  $SUDO_WWW $RUN_PHP -- $CAKE Admin updateTaxonomies

You can then script around that.
