### ISSUE TITLE
Suricata, snort and text event download: content type is json

### ISSUE THREAD

**Issue by sebix** [MISP/MISP#4655]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | no idea
| OS version (client)       | irrelevant
| PHP version               | no idea
| MISP version / git hash   | 2.4.107
| Browser                   | Firefox

### Expected behavior
a text-content type or something more specialized one

### Actual behavior
Header sent by the server:
```
Content-Type: application/json; charset=UTF-8
```

### Steps to reproduce the behavior
Go to an event, Click on "Download as..." and choose either Suricata, Snort or Text. The browser tries to interpret it as JSON, as the server suggests, but fails of course.

**Comment by rommelfs** [comment]
Thanks, confirmed with Firefox.

**Comment by adulau** [comment]
Fixed in 0fd8cee84751f8e83bd6f24e930f39a116b07804 Thank you for reporting.
