### ISSUE TITLE
MissingTableException/ pdo exception sqlstate unknown column after update

### ISSUE THREAD

**Issue by reynas** [MISP/MISP#4658]
After updating 2.4.69 (not sure about the version before the update to 2.4.107)
I have the following errors when I go to an event or the "server settings & maintenance"

I tried updating via the webgui, but had several errors and thus tried the manual way.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Support
| OS version (server)       | Ubuntu
| OS version (client)       |  Ubuntu
| PHP version               | PHP 7.0.33-0ubuntu0.16.04.4 (cli)
| MISP version / git hash   | MISP 2.4.107 
| Browser                   | N/A

### Logs, screenshots, configuration dump, ...
2019-05-20 19:58:56 Error: [MissingTableException] Table tag_collections for model TagCollection was not found in datasource default.
Exception Attributes: array (
  'table' => 'tag_collections',
  'class' => 'TagCollection',
  'ds' => 'default',
)
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('tag_collections')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#3 /var/www/MISP/app/Model/TagCollection.php(75): Model->find('all', Array)
#4 /var/www/MISP/app/Model/Server.php(2928): TagCollection->fetchTagCollection(Array)
#5 /var/www/MISP/app/Controller/ServersController.php(842): Server->loadTagCollections(Array)
#6 /var/www/MISP/app/Controller/ServersController.php(922): ServersController->__loadTagCollections()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2019-05-20 19:59:03 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.extends_uuid' in 'field list'
Request URL: /events/view/6905
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Event`....', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Event.php(2018): Model->find('all', Array)
#7 /var/www/MISP/app/Controller/EventsController.php(1547): Event->fetchEvent(Array, Array)
#8 [internal function]: EventsController->view('6905')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by SteveClement** [comment]
This is a tricky one. @iglocska do you have a 2.4.6x setup handy to reproduce?

Latest I had was 2.4.70 and it was ok.

**Comment by reynas** [comment]
I'm not entirely sure about the previous version, can I check this somewhere, somehow?

**Comment by Tomasuh** [comment]
We tried to update today from v2.4.86 to 2.4.107 and observed similar issues, when we open an event we get the following error:
2019-05-22 14:49:10 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.extends_uuid' in 'field list'
Request URL: /events/view/47576
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Event`....', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Event`....', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Event.php(2026): Model->find('all', Array)
#7 /var/www/MISP/app/Controller/EventsController.php(1547): Event->fetchEvent(Array, Array)
#8 [internal function]: EventsController->view('47576')
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

To be noted is that we tried the same update process on a clone of this machine two weeks ago and everything went fine, so seems like a bug has been introduced in the latest version?

**Comment by SteveClement** [comment]
@iglocska this might be an important and "universal" one. Could you please check. I cannot reproduce it on my random setups (with NO data)

**Comment by reynas** [comment]
@SteveClement @iglocska any update on this? I can really use the help here, to fix my setup

**Comment by iglocska** [comment]
A few things to try:

1. remove the caches:
```
rm -f /var/www/MISP/app/tmp/cache/models/myapp*
rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*
```

2. If the above doesn't work, could you check what DB version your misp DB is at (assuming default db name/db-username) and report back with the results?
```
mysql -u misp -p misp
select value from admin_settings where setting = 'db_version';
describe tag_collections;
```

**Comment by reynas** [comment]
MariaDB [misp]> select value from admin_settings where setting = 'db_version';
+-------+
| value |
+-------+
| 34    |
+-------+
1 row in set (0.00 sec)

MariaDB [misp]> describe tag_collections;
ERROR 1146 (42S02): Table 'misp.tag_collections' doesn't exist
MariaDB [misp]>

**Comment by iglocska** [comment]
Are you sure your mysql user that misp used to connect to the db has the privileges to create and alter tables?

**Comment by reynas** [comment]
it should, not entirely sure though (as I took over this server to maintain from someone else).
Any commands that you suggest me to run to figure this out?

**Comment by reynas** [comment]
any input? I would love to get this sorted, I can't get my MISP back up and running 
thanks!

**Comment by iglocska** [comment]
connect to mysql via the CLI, using the account that MISP uses

```
mysql -u misp -p misp
```

Grab the permissions for the user

```
show grants for current_user;
```

Should give you:

```
GRANT ALL PRIVILEGES ON `misp`.* TO 'misp'@'localhost' 
```

**Comment by reynas** [comment]
MariaDB [(none)]> show grants for current_user;
+-------------------------------------------------------------------------------------------------------------+
| Grants for misp@localhost                                                                                   |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'misp'@'localhost' IDENTIFIED BY PASSWORD '*XXXXXXXXXXXXXXXXXXXX' |
| GRANT ALL PRIVILEGES ON `misp`.* TO 'misp'@'localhost'                                                      |
+-------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)

That is correct.

**Comment by iglocska** [comment]
that is indeed correct, weird. Could you do this?

```
update admin_settings set value = '2.4.86' where setting = 'db_version';
```

It should rerun all the updates from 2.4.86 -> 2.4.108

**Comment by iglocska** [comment]
Just log into MISP via the web interface afterwards to actually start the update.

**Comment by reynas** [comment]
I can now access the server settings again. The issue visiting a event is still present though:
2019-06-03 08:47:32 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.object_relation' in 'field list'
Request URL: /events/view/2833
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(Event), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Event), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#8 /var/www/MISP/app/Model/Event.php(2018): Model->find('all', Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1547): Event->fetchEvent(Array, Array)
#10 [internal function]: EventsController->view('2833')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

**Comment by iglocska** [comment]
Wow, that is even weirder. That is from before 2.4.86. 

It sounds like your MISP had issues from before even.

```
update admin_settings set value = '2.4.80' where setting = 'db_version';
```

**Comment by iglocska** [comment]
Let's see if that fixes it.

**Comment by reynas** [comment]
Great! Thank you very much.
Works perfectly again!

**Comment by iglocska** [comment]
Excellent, let me know if you still see something that might be fishy. 2.4.80 is the version that fixes your particular issue, but we don't know when your MISP started failing and when the first update was that got skipped. Just holler if you see something.
