### ISSUE TITLE
Workers issue

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4659]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RHEL7
| PHP version               | 5.4, 
| MISP version / git hash   | v2.4.107, hash of the commit
| Browser                   | If applicable

### Expected behavior
I tried to publish an event. But I guess this would can be of a general question

### Actual behavior
When i look at the logs it indicates the action i did failed and in the Progress Column it shows 'No worker'

1. Where can i go to to get more information on the problem?
2. What was the cause of worker being unavailable? were my resources depleted?
3. how to i fix this?
4. Let me know what you need me to provide as far as logs,etc
![image](https://user-images.githubusercontent.com/42444130/58053773-20bcf300-7b1e-11e9-8ec5-c6ebb19a6bb0.png)

**Comment by SteveClement** [comment]
Dear

Are your workers running?

Also, if you really use php 5.4 I cannot do any further support because all the tests I run are on currently supported php versions.
Maybe @iglocska has a setup or perhaps @rommelfs

**Comment by SteveClement** [comment]
This seems to be solved.
