### ISSUE TITLE
FR: "update all" button

### ISSUE THREAD

**Issue by garanews** [MISP/MISP#4663]
What do you think to have a single button to update everything from UI?
Currently people after update with git have to login and navigate UI through different pages in order to update:
object templates
list warninglist
list noticelist
list galaxies
list taxonomies
(and maybe other)

Sometimes something is forgotten, expecially when need to update multiple MISP instances.
Any thought?

**Comment by mokaddem** [comment]
It is there already! If you go to ``/servers/serverSettings/diagnostics``, you have a new table named ``Submodules version`` where you can pull all submodules and then do the update.

![image](https://user-images.githubusercontent.com/6977223/58235326-e1bab780-7d40-11e9-841f-1701f590599d.png)
 
Cheers!

**Comment by rommelfs** [comment]
That's only one part of the story. 
You still have to go through all pages and update the lists (like Galaxies -> Update Galaxies) to make the update effective. So this should remain a feature request and open.

**Comment by garanews** [comment]
Thanks :)

**Comment by SteveClement** [comment]
Well, I think this is more of a design question.
With a highly modular software, what update pattern do you want to use?

A "one-button" updates all? (Which in the current condition of said software will 85% of the time break things)

Or a more sequential, multi-step approach.
Where the user-burden is, perhaps, a little higher, but at least you have intermediate steps to debug whatever goes wrong. (85% straight out of my random fingers)

**Comment by mokaddem** [comment]
I improve the visibility of the update button (the one "injecting" the JSONs into the DB). By clicking on
``update all submodules`` and ``Load JSON into database`` buttons you should have all your submodules updated.

**Comment by garanews** [comment]
![immagine](https://user-images.githubusercontent.com/16938405/58312918-a38aca00-7e0c-11e9-812e-3dcc6e1554ea.png)

Big Thanks, now I see it! :)
