### ISSUE TITLE
feed generator doesn't include disable_correlation field

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#4665]
Example: 
Event 5ccadba6-6454-41dc-9a92-4fce950d210f contains no correlation on VT detection ratio.
However, in the OSINT export at https://www.circl.lu/doc/misp/feed-osint/5ccadba6-6454-41dc-9a92-4fce950d210f.json the disable_correlation field is not present.

**Comment by iglocska** [comment]
Resolved in PyMISP
