### ISSUE TITLE
New entries in app/files/feed-metadata/defaults.json

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4669]
Travis currently fails because of the two new entries ('cached_elements', 'force_to_ids') -> https://github.com/MISP/MISP/blob/2.4/app/files/feed-metadata/defaults.json#L1596

No idea if it is expected or not.

**Comment by adulau** [comment]
Can you just relax the test? It will become a default functionality of the feed to have custom keys. We just need to test if the required fields are there.

**Comment by Rafiot** [comment]
Sure. 
The main advantage to have strict tests is to avoid typos (that happened more than once in the past). But I can allow random keys. The users need to make sure they don't have typos, and when there is an issue by a 3rd party, we need to make sure they didn't do any mistake either.

If any of the keys are used by MISP core, we *must* have them in the file, because there will be typos and we will lose hours on that.

Are you sure we cannot list the authorized keys in the schema (without enforcing them, ofc)? Are users expected to put their own random keys in that file? That sounds like an edge case to avoid.

**Comment by iglocska** [comment]
I think it's best to check for the stuff that we know, anything else that's
there is not interesting.

**Comment by Rafiot** [comment]
ok. Which ones do we know? Are the two new ones known, or not?
