### ISSUE TITLE
Have the "for intrusion detection system" and "batch import" checkboxes in the same order

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#467]
Have the "for intrusion detection system" and "batch import" checkboxes in the same order for proposals and for adding attributes. In one case, it shows them in one order (IDS & batch import) and in another case it shows in the opposite order (batch import & IDS) which is slight confusing.

This is just a minor edit.

**Comment by iglocska** [comment]
Wow, I don't know how I haven't noticed that before...

**Comment by iglocska** [comment]
Thanks for the fix!

**Comment by elhoim** [comment]
Opened https://github.com/MISP/MISP/pull/10970 for this.

This one regressed. PR #468 fixed it in 2015 by touching only `app/View/ShadowAttributes/add.ctp`, putting `to_ids` before `batch_import` to match the attribute form as it stood then. The proposal form still has that order today, but `app/View/Attributes/add.ctp` has since drifted back to `batch_import` first (line 56) with `to_ids` after it (line 62) — most likely when that view was migrated to the `genericForm` element.

The PR moves the `batch_import` field definition after `to_ids` in the attribute form, restoring the order agreed in #468. View-only, no field names/ids/labels changed. Not reopening the issue.
