### ISSUE TITLE
enforceWarninglist via old API syntax?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#4679]
Is there a way to enforce warning lists via the old API?

I'm using a tool that supports only GET requests and the current MISP export is:

https://misp.xxxxx.net/events/nids/suricata/download/false/false/false/false/false/15d

According to the doc, it's possible to add an extra parameter that enable/disable enforcing warning lists:

https://misp.xxxxxx.net/events/nids/suricata/download/false/false/false/false/false/15d/false
=> Returns the same number of events

But:

https://misp.xxxxx.net/events/nids/suricata/download/false/false/false/false/false/15d/true
=> Returns 0 event

Any idea?

**Comment by iglocska** [comment]
Not sure, need to dig into it, but any reason why you use that over the modern APIs? :)

**Comment by xme** [comment]
The existing app can only specify a specific URL to grab data from MISP (GET). No POST possible... :-(
Or is there a way to use the new API through GET requests?

**Comment by iglocska** [comment]
There is indeed!

GET:
``` 
https://your.misp/attributes/restSearch/returnFormat:suricata/publish_timestamp:15d/enforceWarninglist:1
```

**Comment by rommelfs** [comment]
Looks like this can be closed. Please re-open if necessary.

**Comment by xme** [comment]
Great! I tried this but how to filter on event tags? I'm not sure about the syntax:

/includeEventTags:tlp_amber&&tlp_red/
/includeEventTags:!tlp_red/

Like the old API?
