### ISSUE TITLE
Deleted event synchronization

### ISSUE THREAD

**Issue by evial** [MISP/MISP#4681]
Dear MISP team,

I have two MISP instances belonging respectively to organizations A and B. All events from organization A must be propagated to organization B. So I have a sync server sync_B configured in instance A. Event creation and modification are working fine, published events from A are pushed properly to B. But what about the event deletion? Is there any way to configure the synchronization so that deleted events in A would be automatically deleted in B? Sorry for this newbee question, I didn't find anything about it in the MISP documentation but maybe I missed something.

Thanks in advance

**Comment by rommelfs** [comment]
In contrast to attributes (soft-delete), deletion of events is not propagated throughout servers.

To prevent propagation back from an already synchronised instance to yours, there is automatic event blacklisting integrated.

This is by design.
