### ISSUE TITLE
Audit Event Download

### ISSUE THREAD

**Issue by debernal** [MISP/MISP#4682]
When a user downloads an event, it is not logged on the audit list. Is there a way to enable this? Is there an alternative way to determine what users downloaded what events? Thanks

To reproduce it, just download an event, select "Download As", choose any type and list the logs, there is no event product with this action. Thanks.

**Comment by rommelfs** [comment]
The feature is already in HEAD and needs to be enabled in the server settings. Please see screenshot below.

![Screenshot 2019-05-28 at 08 28 20](https://user-images.githubusercontent.com/274748/58455736-b231f380-8122-11e9-8b7b-82546a1867a9.png)

**Comment by debernal** [comment]
Thanks for your help rommelfs, I have verified it works as expected, would it be possible to include logging just for event downloads, without having to enable paranoid logging that would log all page requests?, is this a valid feature request? Also, I noticed that there is a setting to disable logging the paranoid events into the database, if such setting is enabled, where are they logged? Thanks
