### ISSUE TITLE
MISP_BASEURL related setting problem

### ISSUE THREAD

**Issue by Applenice** [MISP/MISP#4687]
I encountered a problem, guess may be related to `MISP_BASEURL` settings. The situation is divided into virtual machine internal access and host access.

### virtual machine internal access
I downloaded the virtual machine: https://www.circl.lu/misp-images/latest/ , use Virtualbox 6.0

And installed the desktop environment.

After adding content to New Server, try editing it. 
virtual machine internal access https://127.0.0.1/servers/index
```
List Sever->Actions->Edit
```
url jump to: https://localhost:8443/servers/edit/2

But, Browser shows:`Unable to connect`, I am trying to modify the url to: https://localhost/servers/edit/2

Working fine at this time.

### host access
The situation is different when the host accesses the virtual machine.
host access https://192.168.56.1:8443/servers/index
```
List Sever->Actions->Edit
```
url jump to: https://localhost:8443/servers/edit/2
Browser also shows:`Unable to connect`, I am trying to modify the url to: https://192.168.56.1:8443/servers/edit/2

Working fine at this time.

In the port forwarding rule settings, I add in the host IP of each entry:`192.168.56.1`, Other settings have not been modified.

How can I change the settings to solve this problem?
Thanks.

**Comment by Applenice** [comment]
I found that the MISP Virtual Machine has been updated and downloaded `MISP_v2.4.107@b94e9b4.ova`. The port forwarding rules are the same as before, and the host IP is added to each entry:`192.168.56.1`.

But, I found host access: http://192.168.56.1:8443/ and use curl access in the virtual machine: 127.0.0.1, The page returns the result is `Apache2 Ubuntu Default Page`.

**Comment by Applenice** [comment]
The `MISP_v2.4.107@304358b.ova` version still has this problem, I am looking forward to solving this problem.
Thanks.

**Comment by Applenice** [comment]
I solved this problem. Saw this issue: https://github.com/MISP/MISP/issues/2983, this reminds me.

Trying to set:
```
sudo /var/www/MISP/app/Console/cake Baseurl ""
````
Of course, this is definitely not correct. It should not be set by root.

This operation can be performed successfully, but will result in:
```
Warning: app/Config/config.php is not writeable. This means that any setting changes made here will NOT be saved.
```
Therefore, the correct operation is to set it in the WebUI:
```
Server Settings & Maintenance -> MISP settings
```
The value of `MISP.baseurl` is set to https://localhost:8443, I think this is the cause of the problem, modify the value of `MISP.baseurl` to null. Working fine at this time.

Thanks.

**Comment by kunmukh** [comment]
Also, using the method showed in https://github.com/MISP/MISP/issues/2983 , one can do `sudo /var/www/MISP/app/Console/cake Baseurl https://<ip>:8443`

**Comment by raghuisin** [comment]
above options worked partially, I had a better alternate. changed following attributes in '/var/www/MISP/app/Config/config.php'
updated baseurl to VM IP -->   'baseurl' => 'https://x.x.x.x',
and commented  //'external_baseurl' => 'https://localhost:8443',
