### ISSUE TITLE
Add ability to add local tag to imported events

### ISSUE THREAD

**Issue by tom564** [MISP/MISP#4691]
Allow users with the tagger role to add local tags to events imported from a feed or server where they aren't the creator org. currently it appears only site admin is able to do this. 

use case# 

A custom tag is added to events where it it is intended for them to be exported to IDS systems.  local tuning should also be possible to remove the IDS flag from attributes. 

Is there any way to achieve this as it currently stands?

**Comment by certbe-trey** [comment]
This functionality is very important for us as well.

**Comment by adulau** [comment]
The local tag functionality has been merged in 2a059f7b3171e3f3f8b26de6b8e7b5594e4ac3ee and don't hesitate to reopen an issue if you see any bugs or alike. This feature will be in MISP 2.4.110.

**Comment by certbe-trey** [comment]
Thanks a mil, y'all rock!!!

**Comment by tom564** [comment]
Our local users are unable to add a local tag, the option is present on the front end but returns "You don't have permission to do that". they have both the perm_tagger, tag_editor permission and are publishers.

**Comment by iglocska** [comment]
In order to be able to add local tags you have to be in the host org. Make
sure that your users are of the same org as what is configured in your MISP
server settings under MISP.host_org_id

**Comment by tom564** [comment]
Hi,
Yep the users are part of the host org. When changing the users org to
something different  the option to add a local tag is no longer visible in
the front end.

The creator of the event is not the same as the host org but that is
exactly what this feature is for I believe.

**Comment by tom564** [comment]
`            // org should allow to (un)tag too, so that an event that gets pushed can be (un)tagged locally by the owning org
            if (
                (
                    (
                        $this->Auth->user('org_id') !== $event['Event']['orgc_id'] ||
                        (
                            $this->Auth->user('org_id') == Configure::read('MISP.host_org_id') &&
                            !empty($attributeTag['AttributeTag']['local'])
                        )
                    ) ||
                    !$this->userRole['perm_tagger']
                ) &&
                !$this->_isSiteAdmin()
            ) {
                return new CakeResponse(array('body'=> json_encode(array('saved' => false, 'errors' => 'You don\'t have permission to do that.')), 'status' => 200, 'type' => 'json'));
            }
`


Should this be negated? `$this->Auth->user('org_id')`` == Configure::read('MISP.host_org_id')`  as the error seems to be given if the if statement returns true. not familiar with php so could be way off
