### ISSUE TITLE
Attribute push possibly broken some time after tags/v2.4.107

### ISSUE THREAD

**Issue by fhubaer** [MISP/MISP#4697]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | Ubuntu 18.04, CentOS7
| OS version (client)       | macOS
| PHP version               | 7.2
| MISP version / git hash   | 2.4.107, HEAD (6a09fca7653c10b90117d27de92c238721063b64)
| Browser                   | Safari/FF/Chrome

### Expected behavior

A published event gets pushed with attributes to a remote instance (e.g with distribution level connected or all).

### Actual behavior
  
The published event gets pushed to the remote instance - but without attributes. Watching with tcpdump indicates that the pushing server simply does not include them.

### Steps to reproduce the behavior

* use 2 instances A and B, bidirectional setup
* checkout branch 2.4 on A, git pull, submodule update, restart apache and workers
* create or edit an event on A with distribution level > community
* ensure the event has attributes, distribution level inherit, publish it
* B receives the event, but without attributes
* falling back to tags/v2.4.107 on A and republishing the event fixes this behavior

Can someone confirm this? Drove me nuts on a set of fresh instances.

### Logs, screenshots, configuration dump, ...

... on demand, I did not find anything of interest in them.

**Comment by iglocska** [comment]
Confirmed and fixed, this one was nasty, thanks for the report! We'll do a bugfix release today.
