### ISSUE TITLE
Refanging URLs and domains/hostnames

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#470]
Some report editors are "de-fanging" URLs or domains/hostnames to avoid people accidently clicking on them.

Observed cases are:
meow://www.bad1.com
h[tt]p://www.bad2.com
hxxp://www.bad3.com
http://www[.]bad4[.]com
http://www.bad5[.]com
meows://www.bad6.com
h[tt]ps://www.bad7.com
hxxps://www.bad8.com
https://www[.]bad9[.]com
https://www.bad10[.]com
bad11[.]com
bad12[dot]com
really.bad13[.]com
reall.bad14[dot]com

Could the free-text importer try to detect this and highlight those.
Having an option to refang (e.g.: hxxp:// to http://) the whole pack could be nice to avoid an external editing step when importing data.
In a perfect world full of unicorns, the user could tick a checkbox to stop the refanging in the import page (or results page?) in case it is more an annoyance than a help.

**Comment by elhoim** [comment]
Additional syntax: baddomain[dot]com

**Comment by elhoim** [comment]
Just checked on a v2.4.56

**Does not seem to be implemented**:
meow://www.bad1.com
h[tt]p://www.bad2.com
meows://www.bad6.com
h[tt]ps://www.bad7.com

**Seem to be implemented**:
hxxp://www.bad3.com
http://www[.]bad4[.]com
http://www.bad5[.]com
hxxps://www.bad8.com
https://www[.]bad9[.]com
https://www.bad10[.]com
bad11[.]com
bad12[dot]com

**Comment by iglocska** [comment]
Seriously, meow?
