### ISSUE TITLE
Configuration support

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4700]
Questions | Answers
-- | --
Type   of issue | Post   installation Support...
OS   version (server) | RHEL   7
OS   version (client) | windows   7
PHP   version | :   7.2.10
MISP   version / git hash | v2.4.107   ()
Browser | Chrome

![image](https://user-images.githubusercontent.com/42444130/58651363-b999fe00-82d6-11e9-8e32-f8bcab9d3485.png)

**Comment by rommelfs** [comment]
point 2 is already part of other github issues (#4562 and #4564). Opening another one is not necessary.

**Comment by rommelfs** [comment]
point 1 is hopefully covered in the manual. Do you have specific questions for missing bits and pieces?

**Comment by rommelfs** [comment]
point 3: what does it mean "seem to have problems"?
What is 'do something'?

If no workers are started, please start workers.

**Comment by dmolina213** [comment]
For example when I try to publish an event. It would say in the page that it is being queued. Then when I would check the status in the jobs page. I would see that error. You have to be more specific and tell me how to start the workers. I am unable to start them on the GUI. Is this the correct way to start them in the CLI systemctl restart misp-workers or is there a preferred way. I think most of my problems revolve around background processes and workers.

**Comment by dmolina213** [comment]
The error I would see on on the job status page is 'no active workers'

**Comment by rommelfs** [comment]
" I am unable to start them on the GUI."  - What does that mean?

**Comment by dmolina213** [comment]
When i click on the button to start a worker or restart all workers nothing seems to happen. 
![image](https://user-images.githubusercontent.com/42444130/58709900-bf4c1e00-8380-11e9-814f-f00562c2275d.png)
Still indicating worker is not running. I am logged in as admin

**Comment by rommelfs** [comment]
Your installation doesn't seem to be correct. What can you find in the log files?

**Comment by dmolina213** [comment]
That's what I was thinking. This is what we used as a reference https://misp.github.io/MISP/INSTALL.rhel7/
Do you know what logs you want me to look at? And if you can provide the location as well. I am just beginning stages of understanding what is happening under the hood.

**Comment by SteveClement** [comment]
The RHEL/CentOS Install is still a massive WiP: https://github.com/MISP/MISP/issues/4084

As I neither have a RHEL support contract, nor live machines with MISP on CentOS installed, it is a slow and painful progress.

Sorry for that, I do my best.

**Comment by dmolina213** [comment]
thank you Steve

**Comment by SteveClement** [comment]
I updated the procedures for the modules, they should be working by now.
