### ISSUE TITLE
Error while trying to sync two instances - update

### ISSUE THREAD

**Issue by pabloes1337** [MISP/MISP#4705]
**Type of issue** - I have a problem while I try to connect to remote server, this server is client certificate to authorize.
**OS version (server)** RHEL 7.6 Maipo
**OS version (client)** NA
**PHP version** 7.1.8
**MISP version** v2.4.107 (304358b)
**Browser** Firefiox/Chrome

**Expected behavior:**
Full Synchronize between two instances.

**Actual behavior:**
When I upload client and ca certificate in .pem format(base64 encoded) and run test connection I recieve error in file /var/www/misp/app/tmp/log/error.log

2019-05-31 11:54:21 Warning: Warning (2): stream_socket_enable_crypto(): Unable to set private key file `/var/www/MISP/app/files/certs/1_client.pem' in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
stream_socket_enable_crypto - [internal], line ??
CakeSocket::enableCrypto() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490
CakeSocket::connect() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 247
CakeSocket::write() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 386
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 377
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 464
Server::runConnectionTest() - APP/Model/Server.php, line 3798
ServersController::testConnection() - APP/Controller/ServersController.php, line 1383
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by rommelfs** [comment]
#4684

**Comment by rommelfs** [comment]
Could you check if your pem file is correct? 
Reference: https://stackoverflow.com/questions/26890378/warning-stream-socket-client-unable-to-set-private-key-file

**Comment by pabloes1337** [comment]
Hi Sascha, thanks for the reply. 
So, I've converted from DER encoded to .pem but this DER doesnt contain priv key.
Is this neccessary that .pem client certyficate have to contains private key ?
If yes, I should generate PKCS#12 and then convert to .pem with priv key and certifacate, in one file ofcourse. 

Thanks in advance.

**Comment by pabloes1337** [comment]
I resolved my problems, first I converted .pfx cert file with this command:
openssl pkcs12 -in cert.p12 -out apple_push_notification_production.pem -nodes -clcerts 
and remove server ca form server synchronization settings. 
It works, thanks for help, regards.
