### ISSUE TITLE
MISP Hangs During Install - Ubuntu 18.04

### ISSUE THREAD

**Issue by open-source-rs** [MISP/MISP#4709]
OS Version 18.04

misp user with sudo access created

install hangs here:

Next step: Generating MISP config files

**Comment by seldem** [comment]
Same here.  OS: Ubuntu 18.04.2 LTS 
Edit: 20 minutes later I saw that setup was running, then finished.

**Comment by SteveClement** [comment]
Let me debug this ;)

**Comment by spookerlabs** [comment]
Same here! More then 30 min awaiting 

onolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
kamisama/php-resque-ex suggests installing fresque/fresque (A command line tool to manage your workers)
Generating autoload files
#####################################  (36%)
Next step: Setting permissions
#########################################  (40%)
Next step: Setting up database
#############################################  (44%)
Next step: Generating Apache config
#################################################  (48%)
#####################################################  (52%)
Next step: Generating MISP config files
#########################################################  (56%)

**Comment by open-source-rs** [comment]
ok - i missed the note that states to install this:

sudo apt install haveged -qy
sudo service haveged start

if i open another putty session to the box and start working in there it clears it up...

i actually have a much more pressing issue...the push/pull no longer sends attributes.

opening another ticket for that.

this one can be closed.

**Comment by Tu5k4rr** [comment]
> ok - i missed the note that states to install this:
> 
> sudo apt install haveged -qy
> sudo service haveged start
> 
> if i open another putty session to the box and start working in there it clears it up...
> 
> i actually have a much more pressing issue...the push/pull no longer sends attributes.
> 
> opening another ticket for that.
> 
> this one can be closed.

This fixed this issue for me thanks :)

**Comment by SteveClement** [comment]
I will add some debug output in the parts where it could be slow if not enough entropy is available, so it becomes clearer why it hangs.
