### ISSUE TITLE
Integrate MISP & Regripper

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#471]
[RegRipper](https://github.com/keydet89/RegRipper2.8) is an automated tool for digital forensics and incident response that allows to parse registry keys of windows systems and output a report. The tool is divided in a lot of plugins covering different cases.

I think if RegRipper was able to parse one of the dump formats of MISP export (json or XML) to check for all the registry keys attributes listed as useable for detection ("To IDS"), it would be great to help DF & IR cases using the malware information contained in MISP communities.

I am requesting this since i think there is a bit of a "chicken and egg" situation. Lots of data added to MISP communities is not registry keys which are very good artifacts probably because there is not easy way to leverage it from MISP (so far). If there was such a plugin, this would definitely help to make the case for storing and sharing registry keys IOCs in MISP.

**Comment by elhoim** [comment]
#118 & #402 will probably need to be solved for this.
#114 would be a nice to have re. this.

**Comment by adulau** [comment]
As mentioned in #402, can an object format from RegRipper would do the job? @elhoim could you have a look?

**Comment by adulau** [comment]
@elhoim Any news?
