### ISSUE TITLE
Offer pseudonymity

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#472]
Offering organisations the possibility to share data that are not attributable to them by using a pseudonym (e.g: Thermonuclear Green Giraffe).

The interesting part about using a pseudonym is that organisations can optionally decide to share (outside of MISP) with trusted parties that they are org "Thermonuclear Green Giraffe". It also allows other platform participants to correlate all events coming from a pseudonym are related, and if need be promote or ignore data posted under a specific pseudonym.

A big question raised by this, is: how to allow globally unique pseudonyms so that you don't get collisions in different MISP communities?

Other questions that come to mind:
Allowing multiple pseudonyms per org?

**Comment by Rafiot** [comment]
Done.
