### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4721]
Questions | Answers
-- | --
Type of issue | Post installation Support...
OS version (server) | RHEL 7
OS version (client) | windows 7
PHP version | : 7.2.10
MISP version / git hash | v2.4.107 ()
Browser | Chrome

I need assistance trying to determine the correct settings 

![image](https://user-images.githubusercontent.com/42444130/58887086-91314b80-86aa-11e9-924a-b78f91d9bc10.png)

**Comment by rommelfs** [comment]
What is the question?
