### ISSUE TITLE
C:\Users\username is replaced with %USERPROFILE% when adding a pdb Path. 

### ISSUE THREAD

**Issue by debernal** [MISP/MISP#4725]
PDB paths on Windows sometimes provide information about the Windows user account that the malware author used to write their malware, replacing it with %USERPROFILE% destroys this context. is there a way to disable this behavior? Thanks

### Steps to reproduce the behavior
Create an event and add an attribute of type atrifacts dropped, pdb with the following value:
C:\Users\threatactorname\dir\file.pdb, it will be replaced with %USERPROFILE%\dir\file.pdb. 

This feature makes sense when adding payload filepaths, but not pdb. 

*If you would like to report a bug, please fill the template bellow*

### Work environment
MISP version used: MISP 2.4.107 

### Expected behavior
Do not replace any data with %USERPROFILE% on PDB paths

### Actual behavior
PDB path has the username replaced with %USERPROFILE%

**Comment by rommelfs** [comment]
Good point.

**Comment by adulau** [comment]
I suppose you mean  %USERPROFILE% as this part of the default whitelist regexp. 

https://"yourmisp"/admin/regexp/index 

So you can disable the regexp for all and set the types where you want the regexp to be applied.

![whitelist](https://user-images.githubusercontent.com/3309/58985886-97bfe000-87dc-11e9-9812-7c416f3bba69.png)

This is indeed a good point and we will update the default whitelist. Thanks a lot for the feedback.

**Comment by debernal** [comment]
Yes you are right, I meant %USERPROFILE% I have updated the issue name, thanks for providing the procedure, I will apply it.

**Comment by debernal** [comment]
The provided procedure works perfectly, thank you :).
