### ISSUE TITLE
Events Come Over Empty

### ISSUE THREAD

**Issue by open-source-rs** [MISP/MISP#4726]
Primary Server Version .108
Pulling Server Version .106

I've never had this happen in the past so often.  Basically this: the communication test after hitting RUN goes fine.  No communication issues there.  However, when I try to pull the events from the Primary Server over to the Pulling Server, which is a fresh install, the events populate with zero attributes.  However, the basic event data (event info, tags, ect.) all come over.   

I did do some reading that all the boxes now have to be the same MISP version to Push/Pull or this will happen.  However, when I go into an event it will sometimes state that the owner didn't allow for sharing of the attributes.  Yet, if I go over to another box in my lab I have no issues.  All the event data comes over.

**Comment by open-source-rs** [comment]
Additionally, after I do a fresh install I'm constantly getting these in my black list...

These are not my events.  I didn't create them, nor import them, nor delete them.  Yet, there they are in the Blacklist.

![image](https://user-images.githubusercontent.com/50664502/58979584-5ad3f900-879c-11e9-9a50-c86714d39552.png)

**Comment by adulau** [comment]
Regarding the black list, it's the test events done during the [PyMISP comprehensive test](https://github.com/MISP/PyMISP/blob/583fb6592495ea358aad47a8a1ec92d43c13348a/tests/testlive_comprehensive.py). So it's fine.

Concerning the other point, it's indeed suspicious. @iglocska what do you think?

**Comment by iglocska** [comment]
Just tested it and tried to reproduce the issue, but no luck.

What I've tried:

2 instances A, B, create event on B with 3 attributes, pull from A, see if all 3 attributes are transferred. 

Tests performed:

A (108-HEAD), B (106-release): OK
A (108-release), B (106-release): OK
A (108-release), B (108-HEAD): OK

Could you describe the exact steps how to reproduce it?

**Comment by open-source-rs** [comment]
Sure - I've got a server that has around 2000+ events in it.
I'm trying to pull from that server to a completely new, fresh installed server.

About as simple as that.

So far what I can deduce is that it definitely has something to do with the versioning. 

Why I say that:

So those 2000+ events came from an older server.  I figured with all the reconfiguring it would simply be easier to build a new server and push all the events over.  

I put up the new server and conducted the push.  Old server was on older version.  I'd have to power it up to find out and the new server was on .108 latest build.  The push went fine from what I could tell.  Probably lost some information, but nothing major. 

So now I have this new server on latest build and I'm trying to pull from it to a server on an older build.

Why would I do that you ask?

Well the server I'm trying to pull from is my work's server.  

I'm trying to pull from here:  https://resource1.theosrs.org

When I try pulling the events come over, but the attributes do not.

**Comment by rommelfs** [comment]
Ok, would you agree we reproduced your test or is there something different?

**Comment by open-source-rs** [comment]
Yea we can reproduce...
I'm trying to think how.

One of the servers, which would be the primary server would need to be
depricated and the other on the latest version.
I could probably fire LabyrINTh back up and run a pull from a fresh .108
server.

Jimbo

**Comment by open-source-rs** [comment]
the test might not happen till this weekend though...

**Comment by open-source-rs** [comment]
Err no wait...
the depricated server would pull from a .108 server so i can't use
LabyrINTh...
I'll have to figure out how to run the bash script to download an earlier
version, but on to an 18.04 ubuntu box.

jimbo

**Comment by open-source-rs** [comment]
going to reproduce this today - figured out what systems i can use.
will document and take screen shots

jimbo

**Comment by iglocska** [comment]
Thanks a lot for all the effort man!

**Comment by open-source-rs** [comment]
No - thank you for making this tool!

Jimbo

**Comment by open-source-rs** [comment]
Running the recreation of activity now.  Will post a PDF with notes once the job completed. 

Jimbo

**Comment by open-source-rs** [comment]
[recreating the bug.pdf](https://github.com/MISP/MISP/files/3272829/recreating.the.bug.pdf)

**Comment by iglocska** [comment]
OK, went through some steps trying to debug this but couldn't reproduce it. However:

1. When you create the event on the 2.4.106 instance and publish it, are you sure that push to your 2.4.108 is disabled? If not then pulling from the 2.4.108 instance will already be too late as you already have the empty event.
2. Could you grab the git commit ID of the 2.4.106 instance? I am currently testing with the release version of 2.4.106, so you might have a different version (something between 2.4.106 and 2.4.107, still called 2.4.106 but ahead of the tagged version).
