### ISSUE TITLE
MISP does not keep a session anymore

### ISSUE THREAD

**Issue by mpurzynski** [MISP/MISP#4728]
Hey.

After logging in, when I click literally anywhere, MISP redirects me back to the login page. I just configured the Redis session backend - and it works for literally everything else but MISP (I checked with this small piece of PHP code)

https://pastebin.com/bvvaBAXf

**Comment by mpurzynski** [comment]
I think I know why I see this kind of behavior. This is the sequence of events.

1. I'm loading mymisppage and the server sends me a Set-Cookie in the header, while presenting the login screen
2. I can see the PHPREDIS_SESSION key with the cookie1 value in redis when doing "keys *"
3. When logging in (=typing a username + password and clicking the login button), server sends me another cookie replacing the first one
4. The second cookie gets saved in the browser
5. The second cookie is not saved in Redis at all
6. My browser sends a session cookie to the misp server but misp cannot find anything in redis, because it did not save it in step 3

**Comment by mpurzynski** [comment]
Interesting - it seems like MISP deletes the session cookie shortly after setting it (I was looking at the network traffic betwen redis and misp)

**Comment by xg5-simon** [comment]
I'm seeing the exact same behavior in the latest update.

**Comment by iglocska** [comment]
Should be fixed now, my bad! Just fetch the latest commit, it's meant to do it for API queries only, but the connectivity check executed every 5 seconds counted as one destroying the sessions. Added a check to only drop the session for queries executed with the API key set in the request.
