### ISSUE TITLE
Getting information about a malware

### ISSUE THREAD

**Issue by mahmoodn** [MISP/MISP#4729]
Recently, we have hit a ransomware and I want to know how can I get information about it via MISP community. For example, if someone has analyzed that or it is in progress by someone else. I ask that to see if we can reduce the analysis time.

**Comment by dharshanduck** [comment]
have you tried searching the hashes of the initial ransomware file?

can you elaborate on this: "we have hit a ransomware"

**Comment by mahmoodn** [comment]
I mean we got a suspicious file and found that it is a ransom.
It is [here](https://www.virustotal.com/gui/file/bb966a50449436af561df9fb818217ff2c72ef3eea5b2f52646e3befe7d20b54/detection).
I would like to know how MISP can help with this regard?

**Comment by dharshanduck** [comment]
well you could search up the hash within MISP, provided you have enabled the feed system and the various feeds.
you could create an event with the hash as a starting attribute and use the module system to enrich the event with data related to the hash

**Comment by rommelfs** [comment]
Are you connected to misppriv.circl.lu? Have a look at event UUID 5cffb200-f430-44b2-83a2-c922950d210f - it demonstrates what can be done with as few information as you initially had.

<img width="1410" alt="Screenshot 2019-06-11 at 16 39 19" src="https://user-images.githubusercontent.com/274748/59281441-93297a80-8c67-11e9-9bdd-e0e7a51241b9.png">

This is a good start, and from this point we could easily collaboratively add additional information.

**Comment by mahmoodn** [comment]
In our galaxy there are 34 records and I don't see any `*circl*`
I even updated the list (but didn't force).

As the name suggest, sharing platform, I expect to get updated news about newly detected malwares and analyses from the communities (galaxies or feeds) or in case of an indecent, informs others about that. Is my understanding correct?

**Comment by mahmoodn** [comment]
@rommelfs 
I opened ransomware galaxy and saw 11 pages but it seems there is no search link as I look to the columns and buttons. How did you opened the blue box in your picture?

**Comment by pchoobdar** [comment]
@dharshanduck  
I create an evetn with  hash atrribute but there is no possibility to search hasha also
 when enable feeds ,we can not see that events in my event list

**Comment by rommelfs** [comment]
> In our galaxy there are 34 records and I don't see any `*circl*`
> I even updated the list (but didn't force).
> 
> As the name suggest, sharing platform, I expect to get updated news about newly detected malwares and analyses from the communities (galaxies or feeds) or in case of an indecent, informs others about that. Is my understanding correct?

Since you didn't reply to my initial question (if you are connected to misppriv.circl.lu) I assume you are not. There are some obvious reasons that enable sharing only with selected partners. You as a maintainer of one instance of MISP select your partners with whom you want to share. If you don't share and you don't ingest data from others, you are in an island mode. There is no magic way events from our instance jump to your instance if you don't set this up.

For an understanding of what the purpose of galaxies is, please have a second look into the training material https://www.circl.lu/assets/files/misp-training/3.4-MISP-Galaxies.pdf or the documentation.

Galaxies do not transport threat indicators as you might have assumed.

**Comment by dharshanduck** [comment]
@pady12 Could you please elaborate further?

**Comment by rommelfs** [comment]
https://www.circl.lu/doc/misp/feed-osint/5cffb200-f430-44b2-83a2-c922950d210f.json

**Comment by mahmoodn** [comment]
> There is no magic way events from our instance jump to your instance if you don't set this up.
And that is the point.... we would like to communicate and contribute (if we can). 

Just want to be sure that adding that json should be done based on this [guide](https://www.circl.lu/doc/misp/galaxy/#adding-a-custom-galaxy-repository-in-misp-wip---notfunctional). Do you confirm that?
I have read about the vocabulary used for galaxies, but still there are some questions. I want to know who can (or is authorized) to create a galaxy/cluster? Then, in what circumstances, a new galaxy/cluster is created? What information should be supplied in order to be interesting for those that we are communicating. Don't know if my questions are tangible, but these were arose as I read about such vocabs.

**Comment by pchoobdar** [comment]
@dharshanduck 
Hello,
I hope this is not a too stupid question, in the first step
1 install fresh MISP 2.4 then 
2 add a event with 2 attribute (hash and name)
2 add sync server for publish my event  to another instance
but my attribute list have a many attribute that I did not create it ?????
Furthermore i would like to be able to search for a malware hash but i can not find any result for this 
@rommelfs
how we can connect to misppriv.circl.lu?
Thank you in advance for your support.

**Comment by rommelfs** [comment]
> > There is no magic way events from our instance jump to your instance if you don't set this up.
> > And that is the point.... we would like to communicate and contribute (if we can).
> 
> Just want to be sure that adding that json should be done based on this [guide](https://www.circl.lu/doc/misp/galaxy/#adding-a-custom-galaxy-repository-in-misp-wip---notfunctional). Do you confirm that?
> I have read about the vocabulary used for galaxies, but still there are some questions. I want to know who can (or is authorized) to create a galaxy/cluster? Then, in what circumstances, a new galaxy/cluster is created? What information should be supplied in order to be interesting for those that we are communicating. Don't know if my questions are tangible, but these were arose as I read about such vocabs.

The json is the MISP event I created based on your input. It is now part of our OSINT feed. If you import our OSINT feed, you have it already. You can also import just this event from the link I gave you.

This has absolutely nothing to do with galaxies.
Documentation about Galaxies is here: https://www.circl.lu/doc/misp/galaxy/#galaxies
You obviously have to have the correct permissions on the file system to generate new galaxies.
Also, you need to be admin on the MISP instance to add your galaxy.

If you have created a galaxy that you think is in the interest of others, feel free to create a pull request.

**Comment by rommelfs** [comment]
> @dharshanduck
> Hello,
> I hope this is not a too stupid question, in the first step
> 1 install fresh MISP 2.4 then
> 2 add a event with 2 attribute (hash and name)
> 2 add sync server for publish my event to another instance
> but my attribute list have a many attribute that I did not create it ?????
> Furthermore i would like to be able to search for a malware hash but i can not find any result for this
> @rommelfs
> how we can connect to misppriv.circl.lu?
> Thank you in advance for your support.

I don't think these questions belong into this Github issue. Please open another one or visit the Gitter chats:
https://gitter.im/MISP/Sharing  (General information sharing questions)
https://gitter.im/MISP/Support (MISP Support, not development related)
https://gitter.im/MISP/MISP      (MISP Developer channel)

**Comment by mahmoodn** [comment]
I tried some steps, but I am not sure if the result is correct or not.
1- "sync action"->"list feeds"->"import feeds from json". Then I pasted the json [file](https://github.com/MISP/MISP/issues/4729#issuecomment-501248106) you gave and clicked on "add".
2- "sync action"->"list feeds"->"list feeds"->"custom feeds". What I see is this picture
![Untitled](https://user-images.githubusercontent.com/11626212/59549799-143e8580-8f78-11e9-82c9-1aa2c3ccae80.png)
Did I correctly added the json file?

**Comment by mahmoodn** [comment]
Another thing that I tried was to manually add the event regarding the ransomware and get a graph similar to [yours](https://github.com/MISP/MISP/issues/4729#issuecomment-500872694).
1- "event"->"add event" and filled it with somm contents as below
![Untitled](https://user-images.githubusercontent.com/11626212/59549845-cd9d5b00-8f78-11e9-889b-c4f054d60844.png)


2- Then I clicked "view" as below
![Untitled](https://user-images.githubusercontent.com/11626212/59549857-ff162680-8f78-11e9-9c7b-117d2f548f3e.png


3- The result is not similar to yours.
![Untitled](https://user-images.githubusercontent.com/11626212/59549870-2836b700-8f79-11e9-9706-117929090741.png)


Event and correlation graphs are not meaningful. I think the red line which says "not published" means that it is not connected to virutotal or misppriv.circl.lu

Please let me know your comments. Thanks

**Comment by rommelfs** [comment]
> I tried some steps, but I am not sure if the result is correct or not.
> 1- "sync action"->"list feeds"->"import feeds from json". Then I pasted the json [file](https://github.com/MISP/MISP/issues/4729#issuecomment-501248106) you gave and clicked on "add".
> 2- "sync action"->"list feeds"->"list feeds"->"custom feeds". What I see is this picture
> ![Untitled](https://user-images.githubusercontent.com/11626212/59549799-143e8580-8f78-11e9-82c9-1aa2c3ccae80.png)
> Did I correctly added the json file?

No, absolutely not. This json contains an event, not a feed.

Most of these concepts are well covered in the documentation.

**Comment by rommelfs** [comment]
> Another thing that I tried was to manually add the event regarding the ransomware and get a graph similar to [yours](https://github.com/MISP/MISP/issues/4729#issuecomment-500872694).
> 1- "event"->"add event" and filled it with somm contents as below
> ![Untitled](https://user-images.githubusercontent.com/11626212/59549845-cd9d5b00-8f78-11e9-889b-c4f054d60844.png)
> 
> 2- Then I clicked "view" as below
> ![Untitled](https://user-images.githubusercontent.com/11626212/59549857-ff162680-8f78-11e9-9c7b-117d2f548f3e.png
> 
> 3- The result is not similar to yours.
> ![Untitled](https://user-images.githubusercontent.com/11626212/59549870-2836b700-8f79-11e9-9706-117929090741.png)
> 
> Event and correlation graphs are not meaningful. I think the red line which says "not published" means that it is not connected to virutotal or misppriv.circl.lu
> 
> Please let me know your comments. Thanks

Do I understand well that you did the following steps:

1. You created a new event
2. You added an attribute
3. You expected this specific event to magically display the event I created?


You can get this event by either of the following ways:
1. Import the json referenced earlier here via Import from... -> MISP standard
2. Import the CIRCL OSINT feed
3. Connect to CIRCL MISP via sync

All these other things like 'published' are well covered in the documentation. Please read it. MISP is rather complex and using the right terminology is as essential as understanding how the basic workflow is meant to be used.
CIRCL by the way frequently gives trainings about MISP. Perhaps that would be worth looking into.

**Comment by pchoobdar** [comment]
@rommelfs The main question is how we can enable feed to see the correlation my event and another  organization event, for example virus total or CIRIL? We enable feeds from sync action"->"list feeds,
but we did not see any changes and graph  for that  event? What should we do For connects to CIRCL MISP via sync that you mentioned in step 3?

**Comment by mahmoodn** [comment]
OK. I think I should at least setup a connection and sync with misppriv for the rest of the things. I will comeback then. Thank you.
