### ISSUE TITLE
Default hardcoded tags

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#473]
Since tags will soon be exportable (re #369 & #320 ), would not it be better to even some default hardcoded tags to avoid various communities re-invinting different tags with the same meaning (e.g.: "TLP:AMBER" & "TLP AMBER") but with slight changes in display.

This would avoid tag creep & duplication.

Those tags would need to be non-deletable even by instance admins.

Some proposed values for default tags:
TLP:WHITE
TLP:GREEN
TLP:AMBER
to cover #394. I am not suggesting TLP:RED since RED only makes sense if you specificy the individual(s) or group(s) to which you share it.
TLP:EX:CHR to support Chatham House Rule (aka Non-Attribution) extension from CIRCL (https://www.circl.lu/pub/traffic-light-protocol/)
Activity Type:Crimeware
Activity Type:Scanning
Activity Type:Targeted

**Comment by adulau** [comment]
+1

**Comment by iglocska** [comment]
We can definitely do that! I'll look into a way of adding this gracefully once I do the upgrade scripts for the upcoming version (we have to make sure that we don't create stuff that already exists on an instance).

Also, another new feature with tags will be that not all of them will be exportable. Tags will have a new optional setting that marks them to be exportable or not - so the question here would be, which of those tags would you like to default to local only and which to be exported?

**Comment by elhoim** [comment]
About tag duplication because of new hardcoded tags, a solution could be to offer a small script, based on PyMISP, to iterate over events and replace all tags with id X with tag with id Y.

**Comment by elhoim** [comment]
Additional hard-coded tag suggestion:
**Note:Do Not Action** for cases where you want to tell your consumers not to action (resolve domain names, ping IPs, etc...) the IOCs.

It might be necessary to find another way to express this, since it could also be understood as "do not take action in your constituency based on this information".

**Comment by elhoim** [comment]
Just wanted to mention that OSINT is also a good candidate to be hardcoded

**Comment by Rafiot** [comment]
Feature request for that bug: a method to get the list of existing Tags on the instance.

**Comment by iglocska** [comment]
Yeah would make sense to expose tags via the Rest interface completely (add/edit/delete/view/index at least).

**Comment by Rafiot** [comment]
+1

**Comment by elhoim** [comment]
@Rafiot added #622 to cover your request so it does not get lost in this thread.

**Comment by adulau** [comment]
Why don't use a specific attribute (other/tag) for the tag? So the sync of the tags will be part of the standard event and you can even do correlation as we do for the other attributes. This would also help to reduce complexity and code size regarding tag management. For the local tag, it would be the distribution level of the attribute setting the up the tag as local (my organisation only remains for the org). What do you think?

**Comment by iglocska** [comment]
Having tags separately allows us to do a lot of stuff such as searching for
attributes of events that carry a tag as well as allow for having tags that
are only relevant to the user base of an instance. I don't think it adds a
lot of complexity, completely exposing the tags would be very little effort
(both to the sync) - but I think that in many cases it is best to have the
ability to not share them. It would be weird if it changed over night for
sure at least.

For 2.4 you'll simply be able to set whether you want to include a tag in
the exports or not, but even if not, they can be used as an export
parameter as it works today.

**Comment by adulau** [comment]
It was just an open idea. No worries.

**Comment by adulau** [comment]
Following the discussion of having a separated repository of the tags, I did a first version with the Admiralty Scale (information and source credibility) taxonomy and created a standalone repository:

https://github.com/MISP/misp-taxonomies

The format of the tags are described in a simple JSON format to describe [Triple Tags](http://www.foo.be/cgi-bin/wiki.pl/MachineTag) and you can check the first version https://github.com/MISP/misp-taxonomies/blob/master/admiralty-scale/machinetag.json.

A sample Python tools showed how to list all the triple tags for a specific taxonomy. 

An example of machine tag :
~~~~
admiralty-scale:information-credibility="4"
~~~~
and the human readable version:
~~~~
admiralty-scale:Information Credibility="Doubtful"
~~~~ 

The proposal is to have a parser in 2.4 to support those tags following the admin configuration.

**Comment by Rafiot** [comment]
Done.
