### ISSUE TITLE
Workers tab in Server Settings and Administration

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4730]
Questions | Answers
-- | --
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | : 7.2.10
MISP version / git hash | v2.4.107 ()
Browser | If applicable

Reintalled MISP. However when i go to Server Settings and Adminstration I dont see the Workers tab
![image](https://user-images.githubusercontent.com/42444130/59199589-e9a99280-8b5b-11e9-8d7a-6fd5948cd98c.png)

Would that be an issue if we are using systemd to stop,start and check status workers?

**Comment by SteveClement** [comment]
@dmolina213 in theory no, but that is quite fascinating :)

Can you try to access the workers tab manually by appending: 

```
servers/serverSettings/workers
```

To your MISP URL.

**Comment by dmolina213** [comment]
After setting the options in Administration ..> Server Settings the tab magically appeared. However, I am still having problems starting workers from the tab itself. We have been relegated to starting them directly on the CLI
