### ISSUE TITLE
RHEL7/CENTOS setup

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4731]
Questions | Answers
-- | --
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

this part failed 
# TODO:"Investigate why the next one fails"
  #$SUDO_WWW $RUN_PHP -- $CAKE Admin setSetting "Plugin.Enrichment_asn_history_enabled" true

This is the error message
Invalid setting "Plugin.Enrichment_asn_history_enabled". Please make sure that t
he setting that you are attempting to change exists and if a module parameter, t
he modules are running.
Notice Error: Array to string conversion in [/var/www/MISP/app/Model/Server.php,
 line 3635]

2019-06-10 14:59:47 Notice: Array to string conversion in [/var/www/MISP/app/Mod
el/Server.php, line 3635]
Setting "Plugin.Enrichment_asn_history_enabled" changed to 1

just for reference this is the segment of code in Server.php
if ($settingSaveResult) {
                $result = $this->Log->save(array(
                        'org' => $user['Organisation']['name'],
                        'model' => 'Server',
                        'model_id' => 0,
                        'email' => $user['email'],
                        'action' => 'serverSettingsEdit',
                        'user_id' => $user['id'],
                        'title' => 'Server setting changed',
                        'change' => $setting['name'] . ' (' . $oldValue . ') =>
(' . $value . ')',
                ));

How do we fix this? Is this critical to be fixed

**Comment by rommelfs** [comment]
I cleaned up your github issue.

Can I assume you have read the following part carefully and checked accordingly?

> Please make sure that the setting that you are attempting to change exists and if a module parameter, the modules are running.

**Comment by dmolina213** [comment]
I finished going thru the procedure https://misp.github.io/MISP/INSTALL.rhel7/

My overarching question is has anyone followed the instruction on installing on RHEL and if there are things that you had to do differently?

We did receive some errors. I just wanted to see if these errors are critical:
1. In the section :
![image](https://user-images.githubusercontent.com/42444130/59308307-55782200-8c66-11e9-9766-956fde5ce953.png)
I got this error: 
![image](https://user-images.githubusercontent.com/42444130/59308340-72145a00-8c66-11e9-8fc9-fb0fbc468509.png)
Is this critical? If so how do we fix it?

2. On the Update Galaxies... section there is a note. Is this your todo or ours?
![image](https://user-images.githubusercontent.com/42444130/59308409-9bcd8100-8c66-11e9-9750-640709cc5ef4.png)

3. What this should be set to ? # TODO: Make sure $FLAVOUR is correct

4. when inspecting the error.log I see this:

tail -f ${PATH_TO_MISP}/app/tmp/logs/error.log. What is happening here and what is the fix?

2019-06-11 15:50:04 Error: Fatal Error (64): require_once() [<a href='http://php
.net/function.require'>function.require</a>]: Failed opening required 'Crypt/GPG
.php' (include_path='.:/opt/rh/rh-php72/root/usr/share/pear:/opt/rh/rh-php72/roo
t/usr/share/php') in [/var/www/MISP/app/Model/Server.php, line 4192]
2019-06-11 15:50:04 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHand
ler::handleFatalError(64, 'require_once() ...', '/var/www/MISP/a...', 4192)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handl
eError(64, 'require_once() ...', '/var/www/MISP/a...', 4192, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalErr
or()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by SteveClement** [comment]
should be ok by now.
