### ISSUE TITLE
Add Galaxy to event fails

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#4733]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04 LTS
| OS version (client)       | Windows 10
| PHP version               | 7.0.32-0ubuntu0.16.04.1
| MISP version / git hash   | v2.4.108 (36b43f1306873cff87b7aa30cdc1a30b38c9c16a) 
| Browser                   | Chrome - Version 75.0.3770.80 / Firefox 67.0.2 (64-bit)

### Expected behavior
Clicking the submit button after adding a galaxy to an event should add the galaxy to the event.

### Actual behavior
Clicking the submit button does not add the galaxy to the event.

### Steps to reproduce the behavior
Open an event.
Click the 'Add' button under the 'Galaxies' section.
Click 'misp' (or any of the others: 'all namespaces', 'deprecated', 'mitre-attack').
Select any galaxy and then select any one of the options.
Click 'Submit'.
The selected galaxy is not added to the event.
The issue happens with either Firefox or Chrome, on multiple MISP servers, and from multiple computers.
The issue appears to have started after updating from v2.4.107 to v2.4.108.

### Logs, screenshots, configuration dump, ...
Nothing in the MISP error.log.
The only error I can find is under the browsers 'inspect' feature. In Chrome, right click the page and select 'Inspect'. The following error appears under the Console tab after clicking the submit button to add the galaxy to the event.

misp.js?73:3645 Uncaught ReferenceError: selected_tag_ids is not defined
    at misp.js?73:3645
    at Object.success (misp.js?73:4297)
    at fire (jquery.js?73:3187)
    at Object.fireWith [as resolveWith] (jquery.js?73:3317)
    at done (jquery.js?73:8757)
    at XMLHttpRequest.<anonymous> (jquery.js?73:9123)
    at Object.send (jquery.js?73:9175)
    at Function.ajax (jquery.js?73:8656)
    at fetchFormDataAjax (misp.js?73:4294)
    at quickSubmitGalaxyForm (misp.js?73:3643)

**Comment by mokaddem** [comment]
Thanks for the report!

**Comment by cudeso** [comment]
Same issue, same MISP version, same output in Chrome and Safari (Version 12.1.1 ).
Ubuntu 18.04.2
