### ISSUE TITLE
Logs rotate or purge

### ISSUE THREAD

**Issue by kalyparker** [MISP/MISP#4735]
Hello,

I discovered that interesting information are logs in the db.
But I did not found the parameter for cleaning the db logs.

Did I miss it?

**Comment by kalyparker** [comment]
Hello,
Is there a way to properly clean logs (and events) from the db?
Does someone did that? 
If no, did you see limitation if I did that with an sql query?

**Comment by iglocska** [comment]
There's a tool called MISP wiper in the installation under tools/ - haven't used it myself but definitely know of users that did. Let us know if anything doesn't work with it!

**Comment by iglocska** [comment]
That is if you want to fully purge it. For log rotations the question is much trickier. There are certain types of log entries that we never want to purge (the event history is based on the modifications logged for example).

**Comment by kalyparker** [comment]
Thx,
Yep, I see the MISP wiper, but clean everything which is not what I want.
I did a bash script for cleaning logs older than X time. I do a backup for important logs on the run. We don't have the same needs :)
We'll see.
If you want the script, I can give it to you.
For events, I'll create something using pymisp, seems easier than doing manually especially for files :)

**Comment by SteveClement** [comment]
@kalyparker if you can share the script I might implement it in [misp-refresh](https://github.com/SteveClement/misp-refresh)

**Comment by kalyparker** [comment]
Ok, so I'll do the commit on your repo this week end :)

**Comment by SteveClement** [comment]
@kalyparker if you can share the script I might implement it in [misp-refresh](https://github.com/SteveClement/misp-refresh)

**Comment by RichieB2B** [comment]
I just did some `misp.logs` cleaning. I started with some simple analysis:
```
MariaDB [misp]> select model,count(*) as count from logs group by model order by count desc;
+-----------------------+---------+
| model                 | count   |
+-----------------------+---------+
| Server                | 5902564 |
| User                  | 3981333 |
| Attribute             | 2240043 |
| ShadowAttribute       | 1911928 |
| Event                 |  328265 |

MariaDB [misp]> select action, count(*) as count from logs where model='Server' group by action order by count desc;
+--------------------+---------+
| action             | count   |
+--------------------+---------+
| pull               | 5673205 |
| warning            |  211438 |
| error              |   16591 |
| update_database    |    1086 |
| serverSettingsEdit |      89 |
| push               |      82 |
| edit               |      62 |
| update_db_worker   |       6 |
| add                |       5 |
+--------------------+---------+
9 rows in set (16.09 sec)
```
etc, etc. I finally settled on:
```
delete from logs where model='Server' and created < '2019-01-01';
delete from logs where model='User' and action='auth' and created < '2019-01-01';
delete from logs where model='Attribute' and action='add' and created < '2019-01-01';
delete from logs where model='ShadowAttribute' and created < '2019-01-01';
optimize table logs;
```
That reduced the `logs.ibd` file by 50%.

**Comment by imidoriya** [comment]
@iglocska might you be able to clarify which logs we should avoid truncating?  My log table is at 65GB, which makes using the UI to view them impossible (timeout).
