### ISSUE TITLE
INSTALL.sh fails checksum

### ISSUE THREAD

**Issue by cmtdly** [MISP/MISP#4739]
Running INSTALL.sh fails checksum and exits
`Next step: Checking if we are run as the installer template
Next step: Checking if we are uptodate and checksums match
sha1: de23b5d224757a8ab2941d8e15d73f10872d5106 does not match the installer sum of: b8e5ea05c4fdb919a16a204dd1e16a4ac4ddad4c
Delete installer, re-download and please run again.`

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, commit 1716ca7da9d671a5e103069d4b74c867a17b1020

**Comment by SteveClement** [comment]
Indeed, there was a merge that changed the installer, it should work again now.

**Comment by vagner-instructor** [comment]
Hi, it happened again the issue INSTALL.sh fails checksum
sha1:  does not match the installer sum of: a1eec205071442b2c9b145e7b5a054ff24728ef4

**Comment by smarthive-skp** [comment]
Issue is back when trying to install on Ubuntu 20.04.

**Comment by righel** [comment]
Could you please try again @vagner-instructor @smarthive-skp 
Checksums look fine.

**Comment by ssdebruyn** [comment]
HI, I also have this problem. I have noticed from my home Fiber direct out it works well but behind a proxy it fails with the same error.

**Comment by Morad0o00** [comment]
you can solve this issue by removing checksum part from the script file
