### ISSUE TITLE
Have username displayed without having to go to profile page

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#474]
If you have multiple accounts in a MISP ('admin' / 'regular user') you can not immediately see with which user you're logged in.

Maybe it makes sense to have the username (email) displayed near the "Log out" button (next to the button or a single line dropdown menu)? Otherwise have it in the footer next to the download GPG key?

**Comment by iglocska** [comment]
That makes sense indeed. I'll look into a way of adding this type of information to the UI without generating too much clutter!

**Comment by Rafiot** [comment]
Fixed.
