### ISSUE TITLE
[BUG] Can't add attributes to object

### ISSUE THREAD

**Issue by joseluratm** [MISP/MISP#4746]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu,
| PHP version               | 7.2.6-1
| MISP version / git hash   | v2.4.109 (57766f03e1a11a8d6eda52b2a23d39de3d1583f1)  

### Description
On MISP v2.4.109 (57766f03e1a11a8d6eda52b2a23d39de3d1583f1)  when I try to add a pair of attributes to an object in an event, the menu show me an error: "Something went wrong - the queried function returned an exception. Contact your administrator for further details (the exception has been logged)."

If i check app/tmp/logs/error.log we find next error:

2019-06-14 13:09:15 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.ObjectTemplate.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /objects/proposeObjectsFromAttributes/10509/[2036333,2036332]?%2Fobjects%2FproposeObjectsFromAttributes%2F10509%2F%5B2036333%2C2036332%5D=&_=1560510504178
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `ObjectT...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `ObjectT...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `ObjectT...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(ObjectTemplate), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/MispObject.php(771): Model->find('all', Array)
#7 /var/www/MISP/app/Controller/ObjectsController.php(999): MispObject->validObjectsFromAttributeTypes(Array, '10509', Array)
#8 [internal function]: ObjectsController->proposeObjectsFromAttributes('10509', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ObjectsController), Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ObjectsController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by adulau** [comment]
Can you check if you have your object templates? Check https://yourmispurl/objectTemplates/index ? if not, can you update those?

**Comment by joseluratm** [comment]
HI,

I checked my object templates and I have all enabled. I have 126 and if I clck on "Update Object" a get a "All object templates are up to date already."

I update to v2.4.109 (fc528d9315221350180a548bdf09e3325b0c244f) and the bug continues.

Thanks for answers
Regards,

**Comment by mokaddem** [comment]
Hey @joseluratm,
I think I figured out your issue and pushed a fix. Don't hesitate to come back to us if this issue is still not solved.
Cheers

**Comment by joseluratm** [comment]
Hi, thanks mokaddem, it's resolved!!!
