### ISSUE TITLE
Event without attributes (due to different level of distribution)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#476]
It could happen that event without attributes are distributed. Would it be possible to check for such case? and hide those from UI and/or API?

**Comment by iglocska** [comment]
Definitely, or even better, block them from being synced in the first place.

**Comment by adulau** [comment]
If we have no use-case, I'm also in favour to block them from being synced. Do you think this could be implemented before the release?

**Comment by iglocska** [comment]
Yup, definitely!

**Comment by adulau** [comment]
Could we put this in the priority list? Thanks a lot.

**Comment by iglocska** [comment]
Sure, I'll start with it right away!

**Comment by adulau** [comment]
Cool. Thank you.
