### ISSUE TITLE
API: Adding an event with "published": "True" => Crash!

### ISSUE THREAD

**Issue by didelphodon** [MISP/MISP#477]
I'm trying to add an event via the MISP-API (REST) which I want to be set as published initially - therefore I added "published": "True" as well as "publish_timestamp". However, when I do this the request takes about half a minute to finish successfully (the event is added to the DB, actually) but returning with an error code 500 (internal server error). Here's what the error-log says ...

PHP Fatal error:  Uncaught exception 'InternalErrorException' with message 'Internal Server Error' in /home/test/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:266\nStack trace:\n#0 /home/test/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(256, '[CakeException]...', '/home/test/MIS...', 138)\n#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/home/test/MIS...', 138, Array)\n#2 /home/test/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)\n#3 [internal function]: ErrorHandler::handleException(Object(SocketException))\n#4 {main}\n  thrown in /home/test/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 266

It's definitely the "published": "True" which triggers the error, tried it without it and it works without any problems, besides the fact that the event is not in a published state then. Btw., I also tried "1" and 1 besides "True", no difference.

**Comment by iglocska** [comment]
Hello there, I've just tested it and for me it works fine on master. The
following values worked for the published field:

1, "1", true

True, "True" however did not work.

What could cause the issue for you: When you specify that the event is
published in the json/xml body, MISP will automatically try to publish the
event, so what could happen (and this is just a wild guess) is that either
the e-mail alerting or the sync to another instance fails. Make sure that
MISP can reach the interconnected instances and that there are no hiccups
with the e-mailing (though I'd assume that these should happen decoupled
from the publishing job in the background if background workers are
enabled).

If the issue persists, let me know. I am right now in the middle of a move
so I have limited access to internet / a system to work on, so sorry in
advance for slow replies!

**Comment by didelphodon** [comment]
We disabled outgoing e-mails, so maybe that's what's the problem - We'll check this out.

**Comment by Rafiot** [comment]
@didelphodon any update?

**Comment by Rafiot** [comment]
No answer, assuming fixed.
