### ISSUE TITLE
Clearing all events

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4770]
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

*If you would like to report a bug, please fill the template bellow*

### Work environment

Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

This is not a support issue. I would like to know how to clear all events from the database? This is a test platform and we would like to finalize our processes of ingesting feeds and events.

**Comment by iglocska** [comment]
We have a tool called MISP-wipe that will completely wipe a MISP instance:
https://github.com/MISP/MISP/tree/2.4/tools/misp-wipe

Additionally, @SteveClement has been working on something more flexible - but make sure you update your MISP installation first:
https://github.com/SteveClement/misp-refresh

**Comment by dmolina213** [comment]
This will just clear the database of events correct? and not nuke the entire server and wipe it all clean? ;-)

**Comment by SteveClement** [comment]
misp-refresh is not tested on RHEL/CentOS and will certainly not work as expected.

Use misp-wipe directly.

**Comment by iglocska** [comment]
It will nuke the entire server. If you only want to delete the events I
suggest a small python script - fetch the event index, iterate through
them, delete them one by one.

Make sure you clean out your event blacklist table afterwards if you intend to pull those events in again.
