### ISSUE TITLE
[API] Get state of the jobs/workers via the API

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#4773]
[API] Get state of the jobs/workers via the API

**Comment by iglocska** [comment]
Workers we can already get, cron jobs we cannot - meaning that if we schedule recurring tasks via crontab we won't be able to remotely manage them.

**Comment by FafnerKeyZee** [comment]
Hey,

@iglocska: Is it possible to start/stop/restart worker by the API ? And how can we access them ?

**Comment by iglocska** [comment]
It should be, but it's undocumented. Will do something about that now.

**Comment by iglocska** [comment]
Now implemented.

/servers/getWorkers
/servers/startWorker/[queue]
/servers/stopWorker/[pid]
