### ISSUE TITLE
An Internal Error Has Occured for Sync Actions

### ISSUE THREAD

**Issue by dpatanker** [MISP/MISP#4777]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  RedHat 7
| OS version (client)       | win10 
| PHP version               | PHP 7.2.18 
| MISP version / git hash   | 2.4. 711f9d398ee73dc43a489154fe009a969d2091d1
| Browser                   |FireFox,Chrome
### Expected behavior
list of feed and servers

### Actual behavior

internal error on web UI
### Logs, screenshots, configuration dump, ...
/var/www/MISP/app/tmp/logs/error.log

```
2019-06-18 17:16:34 Error: [RedisException] Connection refused
Request URL: /servers/index
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1776): Redis->connect('127.0.0.1', 6379)
#1 /var/www/MISP/app/Model/Server.php(4947): AppModel->setupRedis()
#2 /var/www/MISP/app/Controller/ServersController.php(73): Server->attachServerCacheTimestamps(Array)
#3 [internal function]: ServersController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-06-18 17:16:38 Error: [RedisException] Connection refused
Request URL: /feeds/index
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1776): Redis->connect('127.0.0.1', 6379)
#1 /var/www/MISP/app/Model/Feed.php(1086): AppModel->setupRedis()
#2 /var/www/MISP/app/Controller/FeedsController.php(76): Feed->attachFeedCacheTimestamps(Array)
#3 [internal function]: FeedsController->index()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by dmolina213** [comment]
I also have MISP on RHEL 7 and I am running into several problems

**Comment by SteveClement** [comment]
Your redis is not running.

Please re-check the install document on getting redis installed.

**Comment by iglocska** [comment]
If redis is installed and running and you still get that error make sure that you allow for this SELInux directive:
```
httpd_can_network_connect
```

**Comment by dpatanker** [comment]
Hi SteveClement & iglocska,

Thank you for your prompt reply. Yes the redis  service failed. I am not sure why but it looks like it failed quite some time ago. After restart - the issue has been fixed :)
sudo systemctl status --now rh-redis32-redis.service
● rh-redis32-redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/rh-redis32-redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/rh-redis32-redis.service.d
           └─limit.conf
   Active: failed (Result: exit-code) since Fri 2019-06-14 16:53:27 UTC; 4 days ago
 Main PID: 5525 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
