### ISSUE TITLE
Two local MISP instances returning an error when trying to connect them

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#4780]
When I try to connect two MISP instances that are on the same network, I get the following error: 

Error: Connection test failed. Reason: "stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed\nstream_socket_client(): Failed to enable crypto\nstream_socket_client(): unable to connect to ssl:\/\/misppub.asml.com:443 (Unknown error)"

I have a theory what might cause this, but I don't know how to solve it.

So, both MISP instances have an SSL certificate that is issued by our own CA, which is probably not listed in the default CA bundles. I believe this is why the servers are refusing the connection.

How can I solve this?

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.09
| PHP version               | 7.2
| MISP version / git hash   | 2.4.109
| Browser                   | n/a

### Expected behavior
Configuring the servers with corresponding sync user's auth key, and checking skip proxy should create a connection between the servers.

### Actual behavior
I get an SSL error, and the server is said to be unreachable

**Comment by iglocska** [comment]
You can upload the full certificate chain in the sync config for the remotes. Make sure you export the full chain (root, intermediaries, server cert) in .pem format and upload it there.

**Comment by mik5z** [comment]
That makes sense. I've tried doing that, but I have trouble understanding where I should put it! 

![image](https://user-images.githubusercontent.com/42775319/59833493-74517500-9346-11e9-8668-291e953a5cbd.png)

Is it possible for you to clarify what certificate I should put where?

**Comment by mik5z** [comment]
I keep coming back to the issue where it seems like php isn't trusting my company's issued certificate. Any help would be really appreciated, as I'm kind of stuck trying to tie my two servers togehter.

**Comment by mik5z** [comment]
> You can upload the full certificate chain in the sync config for the remotes. Make sure you export the full chain (root, intermediaries, server cert) in .pem format and upload it there.

I keep coming back to the issue where it seems like php isn't trusting my company's issued certificate. Any help would be really appreciated, as I'm kind of stuck trying to tie my two servers togehter.

**Comment by mik5z** [comment]
When I try to curl the servers from either side, I get this message:

`* Rebuilt URL to: https://misp-server/
*   Trying ip address...
* TCP_NODELAY set
* Connected to misp-server (ip address) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
`

**Comment by mik5z** [comment]
In the end, this was resolved by adding all my company's CAs to the /etc/ssl/certs. This way my servers' ssl certificates were successfully verified.

**Comment by angarod** [comment]
Have the same problem in my 18.04 docker install. I have imported the full chain certificate in pem. Doesn't work. The remote server is still unreachable.

**Comment by Srinivas0rch** [comment]
@angarod can you please tell how and from where you're importing those certs? I do have a similar issue on mu single MISP instance.

Something went wrong. stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl
