### ISSUE TITLE
Originator MISP instance cannot delete an event on a remote instance if Distribution level was "Connected Communities" or "All" and later decides to change it to "This Community" or "This Organization Only"

### ISSUE THREAD

**Issue by debernal** [MISP/MISP#4784]
Hi, 

I have two instances of MISP, M1 and M2, and enabled synchronization between them, by creating a sync USER on M2 and adding it in M1 under Sync Servers.

On M1 I created an event, published it and then pushed it to M2. 
When the distribution is Connected Communities or All, all syncronization works as expected, updating the attributes and data of the event. However if in M1 I chose to change distribution from Connected Communities to This Community or This Organization Only I expect the event to disappear on M2, because I changed the distribution to This Community Only or This Organization Only and therefore M2 should now not see this event. 

### Work environment
The MISP server used was the MISP Virtual Machine provided by MISP community. 

### Expected behavior
The event should be removed on M2 if the owner on M1 changes the distribution to This Community or This Organization Only and publishes the event.

If an organization mistakenly chooses the Distribution as Connected Communities or All and decides it to change that later, the current behavior allows the organization no way to remove the event from the remote instance. The only workaround that I found was to delete every attribute on M1 and sync it, while retaining distribution as Connected Communities or All, but this leaves an empty event on the other instance, and obligates to create a new event in M1 to keep this data.  

### Actual behavior
Changes are only synced if the distribution is Connected Communities or All on M1, If distribution is changed to Community or This Organization Only, then the changes are not synced and M2 retains a copy of the event as it looked when it was last synced. 

### Steps to reproduce the behavior
I downloaded MISP virtual machine, and made a copy to setup M2, created several organizations on both instances. On M2 I create a sync user or the ORGNAME organization, then I set this up on M2 under Sync Servers. The sync run test shows success. I added some attributes on the event and published the event on M1, then pushed it to M2 through the sync user.  Then I tried several distribution values for the event and see how it was reflected on M2. 

MISP 1   (pushed to MISP2)               MISP2
This Organization                             No synchronization
This Community                               No synchronization
Connected Community                    This community
All                                                      All

Is this a bug or is it by design that once an event was shared the owner organization has no control or option to pull it back and unshare it? Thanks for looking into this.

**Comment by adulau** [comment]
It's by design. We don't control deletion on remote server from third-parties. There are locally deleted and "black-listed".
