### ISSUE TITLE
Handle non-A types of DNS records

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#479]
Handle DNS record types other than A (list available at http://en.wikipedia.org/wiki/List_of_DNS_record_types ).

Maybe additional data types? It was raised in one of the comments in #117

**Comment by adulau** [comment]
As misp-objects are quickly approaching, could you review the following object to see if this solves your issue? 

https://github.com/MISP/misp-objects/blob/master/objects/passive-dns/definition.json 

I might add a series of proposed default for attributes like for rrtype which can be "A", "AAAA" and so on.

**Comment by adulau** [comment]
Objects are there. I suppose this issue is resolved. Feel free to reopen if this is not the case. Thank you.
