### ISSUE TITLE
Scheduler not auto fetching feeds

### ISSUE THREAD

**Issue by mahesh557** [MISP/MISP#4790]
Hi,

I am running MISP Version v2.4.106 
I could manually fetch feed by clicking http://<host>/feeds/fetchFromAllFeeds
But i am not able to schedule to run daily to pull feeds automatically.

I did go to scheduled tasks http://host/tasks
and edited frequency = 12 scheduled time = 12:00  next run = next day
and restarted all the workers

But nothing happens, Message in the scheduled tasks page says "Not scheduled yet"
even on the next day and feeds are not fetched automatically.

When i tried to invoke feed fetch on the box from command line, i get below error.
````
root@host:/home/padisetu> /var/www/MISP/app/Console/cake Server fetchFeed uma.padisetty@adp.com all
Error: Class 'PDO' not found
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(263): Mysql->enabled()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3646): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3673): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
````

I tried to run the command as apache user i find below message. 
I am the admin and tried ID, Email ID, AuthKey but no luck
````
For more details see runuser(1).
root@dc1prsecvcd0002.es.ad.adp.com:/home/padisetu> runuser -l apache /var/www/MISP/app/Console/cake Server fetchFeed uma.padisetty@adp.com all
This account is currently not available.
root@dc1prsecvcd0002.es.ad.adp.com:/home/padisetu> runuser -l apache /var/www/MISP/app/Console/cake Server fetchFeed 7 all
This account is currently not available.
root@dc1prsecvcd0002.es.ad.adp.com:/home/padisetu> runuser -l apache /var/www/MISP/app/Console/cake Server fetchFeed gfdCQYM3F9jS35t6BYEsFXs1axv3AEtyrkyKCRAu  all
This account is currently not available.
````

Can you help me how to schedule fetch_feeds to run automatically daily and pulled the feeds?

**Comment by adulau** [comment]
You are most probably running another version of PHP from the command line. Check the version and run with the same version used by MISP via Apache.
