### ISSUE TITLE
Attachment Hangs When Attempting To Open

### ISSUE THREAD

**Issue by open-source-rs** [MISP/MISP#4791]
increased file size and upload in php.ini as well as installed latest java on the box.

when clicking an uploaded attachment it just hangs.

![image](https://user-images.githubusercontent.com/50664502/59917617-635d3e00-93f0-11e9-8ad0-c9900a632507.png)

![image](https://user-images.githubusercontent.com/50664502/59917621-68ba8880-93f0-11e9-92b7-1216d4b35fe4.png)

**Comment by adulau** [comment]
Java? We don't use that in the MISP project ;-)

**Comment by adulau** [comment]
I suppose your upload is a screenshot and you have some blocking rules on your browser to avoid displaying the zoomed image.

**Comment by open-source-rs** [comment]
yea i didn't think so, but i was looking back on some of my old notes...
still strange how they hang...never had that issue before.
is there something in the php.ini besides upload size and file size i can
check out?

**Comment by open-source-rs** [comment]
ahh - interesting.
yes it is an uploaded screenshot.
i'll research some google blocking stuffs.
thanks!

**Comment by open-source-rs** [comment]
cleared cache and tried with firefox as well - same issue on both.
firefox is a fresh install.

**Comment by open-source-rs** [comment]
i have chrome set to show all images
here's an example of whats in the folder
[image: image.png]

**Comment by open-source-rs** [comment]
yea i can save image as, and open in new tab, but the old version i could
simply click on it and it would open up.
i haven't changed anything that i do accept to upgrade to version .108
