### ISSUE TITLE
Scheduled Tasks Status: Failed and Queued forever

### ISSUE THREAD

**Issue by mahesh557** [MISP/MISP#4792]
HI,

Feel pull requested are logged into jobs with status set to failed and progress set to 'queued' forever.

I am running on MISP v2.4.109
RHEL 7 PHP 7.1.8 

If it helps, diagnostic page says
````
Module System
This tool tests the various module systems and whether they are reachable based on the module settings.

Enrichment module system…Connection refused
Import module system…Connection refused
Export module system…Connection refused
Cortex module system…Invalid HTTP response.
````

**Comment by adulau** [comment]
Are your workers running? Did you start those? There is a worker tab in the configuration.

**Comment by SteveClement** [comment]
This is an UI quirk.
I have the same issues, just ignore the fail and fetch the feed again or redo whatever is stuck.

Every now and then I have that issue with the test suite that pymisp runs.
A published event is queued forever but failed.

**Comment by mahesh557** [comment]
> Are your workers running? Did you start those? There is a worker tab in the configuration.

Yes all the workers are running and appear to be healthy.

**Comment by dpatanker** [comment]
Hello I have the same issue. When using the fetch feed - for CIRCL it shows as system against the Organisation created when running as scheduler - any thoughts why and how to fix this
![fetch job running as System](https://user-images.githubusercontent.com/22086362/60094626-81a2a100-9744-11e9-9c68-42e2c19e5fb6.png)
?

**Comment by devnull-** [comment]
Good afternoon all,

I have also the same issue. All jobs (sync or export) progress set to 'queued' forever and the <code> php ./bin/resque</code> program took CPU resources without stopping.

**Comment by user4913** [comment]
have the same issue, any way to solve other than clearing queue? seems to continue to happens after that as well.

**Comment by mokaddem** [comment]
The scheduler is a kind of legacy tool that might not correctly work unfortunately..
We advice using CRON jobs to perform these jobs.
@user4913, what issue are you referring to?

**Comment by user4913** [comment]
Is there an example CRON job that can be used to fetch and cache all feeds? Just like the scheduled task? 

I keep running into the issue that when fetching data from feeds they get stuck "Queued" and never complete unless I reboot.

**Comment by mokaddem** [comment]
Please, have a look at that page `/events/automation/#console_admin_tasks`. It describes a variety of CLI command that you can put in your CRON jobs.
```
e.g.
MISP/app/Console/cake Server cacheFeed [user_id] all # cache all feeds
MISP/app/Console/cake Server fetchFeed [user_id] all # fetch all feeds
```

**Comment by criptk** [comment]
I am trying the cake server pull, what should i put in user id since the user id is remote ?

**Comment by iglocska** [comment]
The user ID of your local user that is going to be creating the event
locally - normally a site admin account / your own account.

**Comment by iglocska** [comment]
Also keep in mind the user ID is the user ID on the current instance, not
the remote that you pull from.
