### ISSUE TITLE
Allow for tags to be added at the same time as an attribute(s)

### ISSUE THREAD

**Issue by tomking2** [MISP/MISP#4793]
It'd be nice to be able to add tags when posting via REST or PyMISP. Currently when I bulk add IOCs I have to then follow up with tagging each of the attributes post-creation, increasing tenfold the number of API requests being made. Would be awfully clean to do all of this all in one.

I guess the same could be said for creating new events (unless that's already in place?)

**Comment by github-germ** [comment]
+1

related: https://github.com/MISP/PyMISP/issues/337

**Comment by Rafiot** [comment]
The thing you can do now (unless you're up for doing a PR in MISP), is to update event by event: if you pull an event from MISP, tag every attribute you want to tag and push the json back to MISP, it will tag all the attributes at once. 

Using PyMISP is the way to go for that.

**Comment by iglocska** [comment]
Indeed, Tom opened the issue based on our discussion on gitter, I'll add it straight to the attributes/add and attributes/edit functions - we have some neat convenience method internally which should make this rather straight forward.

**Comment by tomking2** [comment]
Hey @Rafiot, how are you proposing to manually add the tag into the JSON back via PyMISP? Is this the best solution as current?

```python
from pymisp import PyMISP

pm = PyMISP("url", "key")

e = pm.get(1234)
e['Event']['Attribute'][0]['Tag'].append({"name": "Example Tag"})

pm.update_event(e)
```

**Comment by Rafiot** [comment]
That would work if you pop the timestamps on Event and in the attribute you're modifying.

The cleaner way is to use the first `load` the json blob in a `MISPEvent`, then use the `add_tag` method on the attribute(s) you want to modify, and pass the `MISPEvent` pack to `update_event`.

You'll find sample code here: https://github.com/MISP/PyMISP/blob/master/docs/tutorial/FullOverview.ipynb

**Comment by Rafiot** [comment]
And I forgot to mention: Of you use ExpandedPyMISP  (requires python 3.6+) instead of PyMISP, you don't have to use `load`, it is done by default.

**Comment by tomking2** [comment]
Oh thanks for the tips, I'll take a look at the sample code. Too used to messing with the JSON, definitely time to look into using the objects a bit better.

Haven't found much documentation for ExpandedPyMISP and the changes it introduces, although it's been a while. Anything you can share with me?

**Comment by github-germ** [comment]
It will great to have this enhancement as it related to the request in `Feature Request: PyMISP bulk tag/untag attributes within an event` (https://github.com/MISP/PyMISP/issues/337). Let us know when it's in a release. THANKS.

**Comment by Rafiot** [comment]
@github-germ Yes, we know, like many other things we need to implement that have a higher priority, but as we didn't figure out how to make a day that has more than 24 hours, it might take a while. We're working on it too tho.

@tomking2 the documentation of PyMISPExpanded is here: https://pymisp.readthedocs.io/modules.html#pymispexpanded-python-3-6-only
I'll add deprecation warnings in PyMSIP, and recommendation how to port to the new one in July.

**Comment by github-germ** [comment]
> ...make a day that has more than 24 hours

:-)

**Comment by SteveClement** [comment]
Can we close this one?

**Comment by iglocska** [comment]
Nope, needs implementation.

**Comment by Rafiot** [comment]
That's implemented now.
