### ISSUE TITLE
Trouble Updating PHP

### ISSUE THREAD

**Issue by adastra247** [MISP/MISP#4795]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 
| OS version (client)       | Seven
| PHP version               | 5.6
| MISP version / git hash   | 2.4.109 12e76d7828f28fd86779229ecf741e8444a24567

### Expected behavior
I am trying to update PHP from 5.6 to 7.2. 

![image](https://user-images.githubusercontent.com/16085663/60045331-a0e0f600-9692-11e9-8353-7258e1337d8c.png)

On disk I see /etc/opt/rh-php72

![image](https://user-images.githubusercontent.com/16085663/60045434-df76b080-9692-11e9-84ea-510a765b375f.png)

I tried following this guide and updating the $RUN_PHP variable and restarting the workers - 

https://misp.github.io/MISP/INSTALL.rhel7/

sudo -u apache $RUN_PHP /var/www/MISP/app/Console/worker/start.sh

But the system is still using PHP 5.6. Any help would be appreciated.

**Comment by adastra247** [comment]
I was able to get MISP running with PHP 7.2, but now redis is complaining. 

![image](https://user-images.githubusercontent.com/16085663/60125442-ce44a700-9759-11e9-8246-c5e97b12b0e7.png)

**Comment by SteveClement** [comment]
@adastra22 what does "redis-cli" on the command line tell you?

Mine says:

```bash
steve@t480:~/MISP_Main/misp-test$ redis-cli
127.0.0.1:6379> 
```

**Comment by adastra247** [comment]
Hey @SteveClement here is what I have so far ... 

```
sudo yum install rh-php72 rh-php72-php-fpm rh-php72-php-devel rh-php72-php-mysqlnd rh-php72-php-mbstring rh-php72-php-xml rh-php72-php-bcmath rh-php72-php-opcache rh-php72-php-gd -y

systemctl stop rh-php56-php-fpm.service

systemctl enable --now rh-php72-php-fpm.service

su -s /bin/bash apache -c 'scl enable rh-php72 /var/www/MISP/app/Console/worker/start.sh'

[root@server ~]# redis-cli
127.0.0.1:6379>

[root@server ~]# systemctl status rh-php72-php-fpm.service
● rh-php72-php-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/usr/lib/systemd/system/rh-php72-php-fpm.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-06-26 08:31:33 EDT; 3min 47s ago
 Main PID: 82017 (php-fpm)
   Status: "Processes active: 0, idle: 6, Requests: 43, slow: 0, Traffic: 0req/sec"
   CGroup: /system.slice/rh-php72-php-fpm.service
           ├─82017 php-fpm: master process (/etc/opt/rh/rh-php72/php-fpm.conf)
           ├─82018 php-fpm: pool www
           ├─82019 php-fpm: pool www
           ├─82020 php-fpm: pool www
           ├─82021 php-fpm: pool www
           ├─82022 php-fpm: pool www
           └─82031 php-fpm: pool www

Jun 26 08:31:32 server systemd[1]: Starting The PHP FastCGI Process Manager...
Jun 26 08:31:33 server systemd[1]: Started The PHP FastCGI Process Manager.
Jun 26 08:31:49 server /var/www/MISP/app/tmp/logs/[82019]: 2019-06-26 12:31:49 Notice: User (2): user@domain.com -- login
```

Now in the GUI I see the following - 

![image](https://user-images.githubusercontent.com/16085663/60180267-9b4bf300-97ed-11e9-83f8-adf6d9010af8.png)

![image](https://user-images.githubusercontent.com/16085663/60180285-aa32a580-97ed-11e9-8c2b-3fd4ac5b9709.png)

**Comment by SteveClement** [comment]
If you can, please temporarily put this test.php in your webroot:

```
sudo -u apache wget --no-cache -O /var/www/MISP/app/webroot/test.php https://raw.githubusercontent.com/SteveClement/misp-test/master/test.php
```

It has a redis test, also, if you edit the test.php, on the bottome of the file, there is a comment about 'phpinfo();' this will show you which modules are installed if you remove the comment.

**Comment by adastra247** [comment]
Really appreciate the support @SteveClement - Here is the output - 

![image](https://user-images.githubusercontent.com/16085663/60182888-2c719880-97f3-11e9-892c-8e5b34918a5a.png)

**Comment by adastra247** [comment]
Forgot to include the phpinfo() part ... There is a lot more info I can provide if you need @SteveClement 

![image](https://user-images.githubusercontent.com/16085663/60188549-7bbcc680-97fd-11e9-891b-0536f3b5c207.png)

**Comment by SteveClement** [comment]
Perhaps your redis module needs to be built and linked:

```bash
sudo scl enable rh-php72 'yes no|pecl install redis'
echo "extension=redis.so" |sudo tee /etc/opt/rh/rh-php72/php-fpm.d/redis.ini
sudo ln -s /etc/opt/rh/rh-php72/php-fpm.d/redis.ini /etc/opt/rh/rh-php72/php.d/99-redis.ini
sudo systemctl restart rh-php72-php-fpm.service
```

**Comment by adastra247** [comment]
@SteveClement - You are the man! Thank you so much, that worked.

**Comment by arcsector** [comment]
If anyone is coming across this in 2021, note that PECL will fail if you're not installing for your specific version. To force the install for your specific php version, run:

```bash
pecl -d php_suffix=7.2 install -f redis
```

Then add it to your `php.ini`. You can also skip adding the `igbinary` to your redis extension, because that will give you headaches as well with different PHP versions.
