### ISSUE TITLE
[User assistance] Delegate publishing

### ISSUE THREAD

**Issue by kalyparker** [MISP/MISP#4799]
Hi,

I have a problem regarding the delegate publishing.

On my instance I have 2 orgs A and B.
I with to publish events only with A.
B could create event and is not supposed to publish events, just delegate events publication to A.

I have 2 users:
TestUserA which has the roles 'publisher'
TestUserB which has the roles 'User' (default role, modified for adding the additional permission 'Delegation access')

I follow this guide: https://www.circl.lu/doc/misp/delegation/

When I create an event with TestUserB with Distribution 'Org only', I did not see the button 'Delegate Publishing'

Did I miss something?

**Comment by kalyparker** [comment]
Find the problem.

There is a missing prerequisites on the documentation.
You need to activate the setting "MISP.delegation' on the instance.

**Comment by adulau** [comment]
Thank you for the feedback. Could you make a pull-request on misp-book?
