### ISSUE TITLE
More evolved correlation

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#480]
Extracted a comment from issue #126 to track it as a separate issue:

> If the correlation is changed from a simple equality of values to something more evolved:
> -    ip in IP range (like listed above);
> -   hostname from domain (as described in #117);
> -  overlap between a path with filename and a standalone filename;
> 
> then it does not break relational intelligence.
> This might require to have correlations not to be created exactly at the attribute creation time, but in a separate loop/queue that gets picked up by workers.

**Comment by adulau** [comment]
Advanced correlation does IP matching in CIDR block. We have also fuzzy correlation nowadays.
