### ISSUE TITLE
MISP Postfix mailing system

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#4804]
On my MISP isntance I configured Postfix to use Gmail as a relay and hat works fine to send MISP notification emails. I then configured Postfix to relay email via an external SMTP that i subscribed to (3rd party mailing server) and then does not relay MISP notification emails anymore. Is there something i may have to set on the MISP side?

I can send emails from the MISP server using the command line:  echo "subject:  test mail" | sendmail -v -v -r "user1@wakanda23.com" user2@gmail.com , but MISP notifcations  dont send.

**Comment by rommelfs** [comment]
Did you enable emailing in MISP server settings? It is disabled by default.

**Comment by ndhambi** [comment]
yes I enabled it, The mailing works when i  use my gmail account as the relay on the postfix settings, but doesnt when i use a 3rd party mailing server

**Comment by SteveClement** [comment]
As far as I know if it works for one, it will work for the other (if configured correctly)

For MISP this is transparent.

What does "/var/log/mail.log" tell you?

**Comment by ndhambi** [comment]
Finally got it to work, i was missing the Masquerading Postfix config, The emails were sent out with a from tag of  <linux-user>@mydomain and the SMTP server auth was rejecting it

**Comment by adirsabag** [comment]
Hi, how did you manage to configure Postfix to use Gmail as a relay? Thank you.

**Comment by adulau** [comment]
Not really related to MISP @adirsabag but it seems to be a very common question on Internet and there are many tutorial. The search for your question in Google gave About 666.000 results (0,32 seconds) and here is the second result: https://www.howtoforge.com/tutorial/configure-postfix-to-use-gmail-as-a-mail-relay/

**Comment by Kagee** [comment]
If you just want a really simple relay to Gmail, something simple like ssmtp may be an alternative.
