### ISSUE TITLE
Speed up correlations

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#481]
Related to a comment in #454, it might be necessary to find a way to speed up correlations.

Just some food for thought: 
Divide the correlation for multiple attribute in small actions (ie: one per attribute being added) put in a work queue and have workers to pick it up to hammer the DB to check for correlations in parallel.

Potential downsides:
- If the server does not run with multiple cores, then it will be useless.
- Correlations are not available directly in the UI for the user.

**Comment by elhoim** [comment]
Any other suggestions on what could be done to speed up correlation?

**Comment by adulau** [comment]
Related to the cache engine as already discussed.
