### ISSUE TITLE
Syncing with CIRCL takes 2:45 hours

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4814]
We are running 2.4.109 74d9567cf53a7d966328bbf4d17098c9c4b1bad2
Server 2 is misppriv, but the same happens with other large MISP servers. The pull task takes up to 3 hours even if there is nothing to sync.

![image](https://user-images.githubusercontent.com/1461970/60324366-e4827b00-9984-11e9-933b-524abd0bd7b6.png)

**Comment by iglocska** [comment]
It's on my list of things to debug asap, will be back from holidays in
Monday and pont you when I've got something!

**Comment by RichieB2B** [comment]
The sync time with misp.cirl.lu has increased to 4 hours now. 

I have found the culprit: 50542 out of 68906 (73%) of the events are from a single organisation that is on our Organisation Blacklist. So MISP pulls down 50542 full events on every sync just to discard them. Unfortunately the event index does not include the orgc_uuid. I see two ways to fix this:

1. Include the orgc uuid in the index when searchminimal=1
1. Submit a list of blacklisted orgc uuid's when pulling so the remote server can weed these out of the returned index

Please let me know which of these strategies I should implement.
If you think about troubleshooting this yourself I recommend applying #5115 because the sync logging is very broken at the moment.

**Comment by iglocska** [comment]
Woaaaaah, nice find!!! This explains what we are hearing from one or two orgs!!! Thanks a millions!

**Comment by iglocska** [comment]
Should be fixed now based on your suggestion. Thanks a lot!

**Comment by iglocska** [comment]
Fixed here:

https://github.com/MISP/MISP/commit/41f5c88c74fa9cf048c725248f625bc12960d0e5

**Comment by adulau** [comment]
We updated the various MISPs at CIRCL. @RichieB2B can you test? and let us know if it works.

**Comment by RichieB2B** [comment]
Will do! I made my own fix in #5115 but will test yours. ;-)

**Comment by RichieB2B** [comment]
Sync time on my test system (same OrgBlacklist as production) is now 49 seconds! Going to apply to production now.

**Comment by iglocska** [comment]
Awesome, that's more like it!

**Comment by RichieB2B** [comment]
Sync time in production is 36 seconds, down from 4 hours.

**Comment by iglocska** [comment]
Much better. Explains also why I couldn't reproduce it against misppriv!
Excellent find, much appreciated!
