### ISSUE TITLE
Already install elasticsearch but still get error

### ISSUE THREAD

**Issue by Knoxpix** [MISP/MISP#4817]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.3
| MISP version / git hash   | 2.4.109 (4d590160dae52cceb085060068f92a6782061e6e) 
| Browser                   | Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### Logs, screenshots, configuration dump, ...

misp@MISP:/var/www/MISP/app$ sudo -u www-data php composer.phar require elasticsearch/elasticsearch
Cannot create cache directory /home/misp/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/misp/.composer/cache/files/, or directory is not writable. Proceeding without cache
./composer.json has been updated
Cannot create cache directory /home/misp/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/misp/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing elasticsearch/elasticsearch (v7.0.1)
    Downloading: 100%         

Writing lock file
Generating autoload files

=========================================================

2019-07-01 12:49:38 Error: [Error] Class 'Elasticsearch\ClientBuilder' not found
Request URL: /servers/serverSettingsEdit/Plugin.ElasticSearch_logging_enable/0/1
Stack Trace:
#0 /var/www/MISP/app/Model/AppModel.php(1857): ElasticSearchClient->initTool()
#1 /var/www/MISP/app/Model/AppModel.php(1848): AppModel->loadElasticSearchTool()
#2 /var/www/MISP/app/Model/Log.php(273): AppModel->getElasticSearchTool()
#3 /var/www/MISP/app/Model/Log.php(118): Log->logData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(241): Log->beforeSave(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#7 /var/www/MISP/app/Model/Server.php(3654): Model->save(Array)
#8 /var/www/MISP/app/Controller/ServersController.php(1255): Server->serverSettingsEditValue(Array, Array, true, '1')
#9 [internal function]: ServersController->serverSettingsEdit('Plugin.ElasticS...', '0', '1')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}

![image](https://user-images.githubusercontent.com/5124273/60414166-95954980-9c01-11e9-9b51-8913d5a16298.png)

**Comment by SteveClement** [comment]
Can you try this:

https://github.com/elastic/elasticsearch-php/issues/516

**Comment by Knoxpix** [comment]
Here is my code

`<?php`
`use Elasticsearch\ClientBuilder;`
`require 'vendor/autoload.php';`
`$client = ClientBuilder::create()->build();`

### Output ###
PHP Fatal error:  Uncaught RuntimeException: Elasticsearch-PHP requires cURL, or a custom HTTP handler. in /var/www/MISP/app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php:207
Stack trace:
#0 /var/www/MISP/app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php(396): Elasticsearch\ClientBuilder::defaultHandler()
#1 /var/www/MISP/app/test.php(5): Elasticsearch\ClientBuilder->build()
#2 {main}
  thrown in /var/www/MISP/app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 207`

I think this code can call Class 'Elasticsearch\ClientBuilder'.

**Comment by axpatito** [comment]
+1 on Ubuntu 16.04. Still can't figure it out.

**Comment by Knoxpix** [comment]
What can i do to solve this issue?

**Comment by coolacid** [comment]
Have you loaded the PHP cURL module? Check your OS to install the requirement.
