### ISSUE TITLE
Enrichment Results / Unable to submit query report from a misp-module

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [MISP/MISP#4833]
I´m unable to submit/save the queried report from Joe Sandbox (misp-module). All results are fetched correct and displayed fine in MISP.  By pressing the button "Submit iou" the loading spinner is running for less then a second - that´s all. I´m still on the same page and nothing was added to the MISP Event. It is a very huge report. Enabled debug mode in misp server settings:

```
Notice (8): Undefined index: values [APP/Model/Event.php, line 5190]
Notice (8): Undefined index: values [APP/Model/Event.php, line 5191]
Notice (8): Undefined index: types [APP/Model/Event.php, line 5196]
Notice (8): Undefined index: types [APP/Model/Event.php, line 5197]
```
Also started misp-modules in debug mode - there was no entry.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, support
| OS version (server)       | Ubuntu Bionic
| OS version (client)       | Windows 10
| PHP version               | PHP 7.2.15-0ubuntu0.18.04.2
| MISP version / git hash   |  MISP 2.4.109
| Browser                   | Google Chrome

### Expected behavior
Add all queried IoC´s to the MISP Event

### Actual behavior
Nothing is added to the report

### Steps to reproduce the behavior
Query the results from the joe misp-module again and try to submit

### Logs, screenshots, configuration dump, ...
![59921535-4182ac00-942e-11e9-8962-a4638c7eab77](https://user-images.githubusercontent.com/50357205/60647413-f8732480-9e3d-11e9-8a27-9a2addc403be.png)
![59921533-4182ac00-942e-11e9-9f78-85e6eed3900b](https://user-images.githubusercontent.com/50357205/60647414-f8732480-9e3d-11e9-9fa4-a9ee72b8b000.png)
![59921534-4182ac00-942e-11e9-9e5f-42ea98d9bc22](https://user-images.githubusercontent.com/50357205/60647415-f8732480-9e3d-11e9-9ac4-3329172975cc.png)

**Comment by chrisr3d** [comment]
Indeed I accidentally forgot to put this feature on a feature branch when I started developing it.
So at the moment you updated your misp modules, this use case was available, and is reached whenever a new module is used.

But the feature is now included in the latest version of MISP and will be released very soon with a new tagged version.
Thus if you can update to the latest version it should work. Alternatively if you have to wait for the next tagged version, it will come by the end of the week.

**Comment by ITSEC-DACHSER** [comment]
Wow, that was a quick reply - thanks!
In that case i will wait for the next release and try it again.
