### ISSUE TITLE
Events keep being updated without any changes

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4838]
We have a lot of events that keep getting updated on external servers without any of the metadata or attributes actually changing. One example is 5a6f379d-3854-4457-949e-41bb950d210f with the event history clearly showing the problem: https://misp.circl.lu/logs/event_index/10616

A result of this is that the timestamp of these events are always recent while the attributes (and threats) are actually quite old. Any thoughts on why this is happening?

**Comment by uforia** [comment]
We are seeing the same behaviour, and it is quite confusing. Sometimes we get pushes from external parties that are basically 3+ updates to the same Event, without any difference between the three.

**Comment by iglocska** [comment]
Still couldn't quite figure out what causes it, but have a hunch. The latest release includes some changes that will hopefully resolve it. Will keep an eye on it in case it doesn't.

**Comment by RichieB2B** [comment]
Looking at https://misp.circl.lu/logs/event_index/10616 the issue is not fixed. Or do your changes need to be installed on the remote server as well? In that case it might take a while for everyone in the ecosystem to update their MISP servers..

**Comment by RichieB2B** [comment]
This is still happening. Consider the following scenario where there is a loop in the syncing (either push or pull) of MISP servers:

A -> B -> C -> A -> B -> C -> A -> etc

An event originating at one of these server will have locked=0 and thus not accept an update from an external server. This will break the loop. But what happens when one of the servers in the loop picks up an event from yet another MISP server D?

D -> A -> B -> C -> A -> B -> C -> A -> etc

The event will have locked=1 on server A, B and C so they will happily accept the update, even if the only thing changed is the timestamp. Since the timestamp is set to now() on the accepting server it is always increasing and the update loop will continue for ever.

**Comment by RichieB2B** [comment]
Ok, I think I found the cause of this nasty problem.
In app/Model/MispObject.php inside [Object->captureObject()](https://github.com/MISP/MISP/blob/2.4/app/Model/MispObject.php#L948) there is this:
```
            $this->Event->unpublishEvent($eventId);
```
Which causes the event timestamp to be set to now(). That might seem logical, but Object->captureObject() is called from [Event->_add](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L3694) which is used when pulling or pushing events from another server. So every time you receive an event containing an object from another server it is created locally with a fresh timestamp instead with the timestamp of the originating server. This does not happen for events without objects! They will have the same timestamp in the local server as in the originating server.

Updating the timestamp of an event on pull (or push) can cause the loop described in my [previous comment](https://github.com/MISP/MISP/issues/4838#issuecomment-559696554). 

Now I can create a PR to remove the unpublishEvent() but I'm not sure it might break other use cases. 
Object->captureObject() is also called at
[AttributesController->add_attachment()](https://github.com/MISP/MISP/blob/2.4/app/Controller/AttributesController.php#L480)
[EventsController->upload_sample()](https://github.com/MISP/MISP/blob/2.4/app/Controller/EventsController.php#L4388)
[MispObject->editObject()](https://github.com/MISP/MISP/blob/2.4/app/Model/MispObject.php#L982) first use
[MispObject->editObject()](https://github.com/MISP/MISP/blob/2.4/app/Model/MispObject.php#L1008) second use
