### ISSUE TITLE
 Could not update any of the taxonomy libraries

### ISSUE THREAD

**Issue by thirdeyeintelligence** [MISP/MISP#4839]
Having issues with private taxonomies

- have confirmed no error in JSON 
- all the fields are correctly mentioned

Everytime i try to update i get  "Could not update any of the taxonomy libraries"

**Comment by rommelfs** [comment]
Have you considered explaining all your steps and sharing your custom taxonomy? Your description won't probably be sufficient to let anyone help you.

**Comment by thirdeyeintelligence** [comment]
thanks Rommel i ended up creating issue after multiple attempts to get assistance on the gitter.
As its custom/private taxonomy will not be able to share. 

Steps i take : add machinetag.json under /var/www/MISP/app/files/privatetaxonomy and update from GUI. Not seeing the taxonomy i created and is giving me that error.

**Comment by rommelfs** [comment]
Just imagine for a moment I can’t have a look at your server. In this case I do absolutely not know what your failing input is. 
If you need help, do an abstract version of your private taxonomy, share it and explain all steps you have done. 
Thanks

**Comment by thirdeyeintelligence** [comment]
<img width="476" alt="Screen Shot 2019-07-07 at 10 04 47 pm" src="https://user-images.githubusercontent.com/12878182/60768019-803d8500-a103-11e9-9d70-a14e777d6ae4.png">

This is sample - but still not showing up and getting same error.

Steps:

1. mkdir privatetaxonomy
2. cd privatetaxonomy
3. vi machinetag.json
4. Update taxonomies on GUI

**Comment by SteveClement** [comment]
I have done the following, and it works:

```
mkdir /var/www/MISP/app/files/taxonomies/privatetaxonomy
echo '
{
  "namespace": "sample",
  "description": "Some descriptive words",
  "version": 1,
  "predicates": [
    {
      "value": "my-predicate",
      "expanded": "my-predicate"
    }
  ],
  "values": [
    {
      "predicate": "my-predicate",
      "entry": [
        {
          "value": "a-value",
          "expanded": "A value"
        }
      ]
    }
  ]
}' | tee /var/www/MISP/app/files/taxonomies/privatetaxonomy/machinetag.json
# update taxonomy in GUI
```

**Comment by iglocska** [comment]
> <img alt="Screen Shot 2019-07-07 at 10 04 47 pm" width="476" src="https://user-images.githubusercontent.com/12878182/60768019-803d8500-a103-11e9-9d70-a14e777d6ae4.png">
> 
> This is sample - but still not showing up and getting same error.
> 
> Steps:
> 
> 1. mkdir privatetaxonomy
> 2. cd privatetaxonomy
> 3. vi machinetag.json
> 4. Update taxonomies on GUI

Your predicate value is "value". Your reference to said predicate value is "Value". The two are two distinct strings so it will not work, change ["values"]["predicate"] from "Value" to "value" and it will work.

**Comment by thirdeyeintelligence** [comment]
worked like a charm thanks
