### ISSUE TITLE
When MISP is disabled, a broken link is in the message

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#4846]
If you have not set your MISP instance live, you get the following:

 Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live). An update might also be in progress, you can see the progress in [Advanced Update](servers/advancedUpdate/)

"Advanced Update" points to: servers/advancedUpdate/

Which is a non-existent route.

**Comment by wesinator** [comment]
this is fixed with `Update Progress`

The `Administration -> Server Settings -> MISP tab -> live` could still link to https://$this->baseurl/servers/serverSettings/MISP
https://github.com/MISP/MISP/blob/9d77a5b3f982ab0c91ff122d758eb375c7aea3da/app/Controller/AppController.php#L358


Happy new year,
