### ISSUE TITLE
Output RPZ -  Response Policy Zones Configuration export

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#485]
We got a feedback regarding RPZ format used in name-server. This would allow to create sinkhole, dns monitoring or security tools automatically from the DNS records (especially domain names attributes) available in MISP. 

https://dnsrpz.info/
http://www.zytrax.com/books/dns/ch7/rpz.html

There would be a kind of template configuration for RPZ defining the policy action (http://www.zytrax.com/books/dns/ch7/rpz.html#policy-defs) and a export function in the API and the web interface.

**Comment by iglocska** [comment]
I am looking into this now - so far it looks pretty simple. Just grab a merged list of ip-src and ip-dst and a merged list of hostnames and domain names. 

For ip-src/ip-dst it simply creates entries in the following format:

32.1.1.168.192.rpz-ip CNAME rpz-drop.

For any ip-src / ip-dst in CIDR format (example: 192.168.1.0/24):

24.0.1.168.192.rpz-ip CNAME rpz-drop.

for all domain names / hostnames (such as example.com)

example.com CNAME rpz-drop.
*.example.com CNAME rpz-drop.

Only attributes with the IDS flag active will get selected and the following filters can be used:

event id (to create the export for a single event)
from / to (restrtict on event date)
tags

Right now I am planning on doing it in a very simplistic way: The values will simply be dropped in the export file in two main segments (hostname/domain and IPs) - one thing that could be changed if we want some tracebility for the values is to instead group the values by event and have a comment above each block with the event ID and info. Not sure if this is useful information or just pollution though.

The advantage of the first solution is that we will avoid any duplicate values (as we can just retrieve all the unique values). Also the export will be leaner. On the other hand, it might be useful to be able to immediatley pinpoint false positives if you have the export commented with the IDs / event info.

Also, do we want to specify things such as TTL? Or do we leave it up to the consumer to prepend the file with it? We could also have the default TTL for the RPZ export as a server setting.

Let me know what you think, I'll keep working on the implementation in the meanwhile!

**Comment by iglocska** [comment]
OK, further progress:

Right now the API takes a policy setting (with 3 valid options, NXDOMAIN, NODATA and DROP) and it will be used for all items in the export. NXDOMAIN maps to ".", NODATA to "*.", DROP to "rpz-drop.".

Currently it generates 3 lists:

IP addresses (from ip-src / ip-dst that are IDS flagged) resulting in the following entry:
32.1.1.168.192 CNAME rpz-drop. # for 192.168.1.1
24.1.1.168.192 CNAME rpz-drop. # for 192.168.1.1/24

domain names:
google.com CNAME rpz-drop.
*.google.com CNAME rpz-drop.

hostnames:
host.google.com CNAME rpz-drop.

**Comment by adulau** [comment]
Looks great. Regarding the TTL, it could be nice to have it as server setting or even as user profile setting (as you can have different consumer of RPZ output). Thanks a lot.

**Comment by iglocska** [comment]
User profile setting is a little bit tricky on the short term (as it
requires a change in the data model) - in the long run we can create user
preference settings for things like exports / views. For now, would it be
enough to have a default server setting and a parameter in the export that
allows the user to override it?

**Comment by iglocska** [comment]
OK, it is now implemented and available on feature/rpz. 

What you can do now:

- set the header information in the server settings, some default values are used otherwise
- The settings include a policy setting for each of the values (whether they should result in a DROP, redirection to a walled garden, etc)
- use the API to generate an RPZ Zone file, either with the server settings, or overriding them via parameters (passed as url parameters or a JSON/XML object)
- The API allows filtering on event ID, date range, tags
- Per event export using the server settings available on the event page
- both cached full export / and non cached (= background workers disabled) export is available using the server settings

Let me know if you'd like me to change anything, I'll merge it shortly otherwise.

**Comment by iglocska** [comment]
This was implemented a while back.
