### ISSUE TITLE
POST on tags/edit/{tag_id} inconsistent

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4852]
Every other update calls accepts a json dict in that format:

```json

{"id": "<id>", ...}

```

Tag requires

```json

{"Tag": {
    "id": "<id>", ...
  }
}

```

It is also impossible to update a tag if the json doesn't contains the ID AND the name of the tag (ID only doesn't work)

**Comment by zaphodef** [comment]
For the second thing, the API requires to specify the id within the URL, same goes for the attributes (you can't edit a tag/attribute otherwise)
