### ISSUE TITLE
Bring the MISP backup script in the official repository

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#486]
Dave Stephens has created a MISP backup script:
https://github.com/daverstephens/The-SOC-Shop/blob/master/MISP-Stuff/misp-backup.sh

This would be a nice addition to the MISP official repository. Or alternatively, to link to it from the documentation.

**Comment by iglocska** [comment]
Very cool. I had something similar at NCIRC, but the credentials were not parsed from the config files. On the other hand, there is one thing missing from this: It does not back up the samples themselves.

**Comment by rotanid** [comment]
discussions continues in #999
