### ISSUE TITLE
MIssing object_uuid in response to POST on object_references/add

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4866]
That's how the response look like: 
```json
{
  "comment": "Section 0 of PE",
  "deleted": false,
  "event_id": "420",
  "id": "56",
  "object_id": "312",
  "referenced_id": "307",
  "referenced_type": "1",
  "referenced_uuid": "cd8bbe20-bf6f-4b47-8dcc-65cf59b49279",
  "relationship_type": "included-in",
  "timestamp": "1562930710",
  "uuid": "5d286e16-7598-44a9-b179-3a1d0a00020f"
}
```

It should contain `object_uuid` too.

**Comment by iglocska** [comment]
This is actually correct. "object_uuid" is a virtual field that is just created ad-hoc during the sync. With that said, added it in the response to make integration easier.

**Comment by Rafiot** [comment]
It doesn't fix it completely: 
https://github.com/MISP/MISP/commit/cad286d23943ce111f05a75b26b1d4af6c6136cd#r34573514
