### ISSUE TITLE
MISP Log-out Issue - Session Timeout

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#4871]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question / Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2.19-0ubuntu0.18.04.1
| MISP version / git hash   | 2.4.111, 26ecc638a6e1b5cb8a4633898d48fbc0055a9e47
| Browser                   | Chrome

### Expected behavior
Session log-out occurs (due to inactivity) only after the 'time-out' time specified in MISP settings is exceeded.

I.E. Current settings would imply sessions would not time out for 180 minutes.

Critical | Session.timeout | 180 | 
-- | -- | -- | -- | --
Critical | Session.cookieTimeout | 180 | 

### Actual behavior
Users are frequently logged out in < 15-30 minutes, sometimes even whilst in the process of using MISP.

This is despite the cookie in browser seemingly being set correctly (i.e. having an expiry time of +180 minutes)

### Steps to reproduce the behavior
Log in to MISP, use....and be logged out within the 180 minutes.

### Logs, screenshots, configuration dump, ...

Please advise which logs would be useful to help troubleshoot. Appreciate any guidance that can be given to rectify.

**Comment by SteveClement** [comment]
This specific issue should have been resolved.
