### ISSUE TITLE
documentation.pdf

### ISSUE THREAD

**Issue by didelphodon** [MISP/MISP#488]
The file "documentation.pdf" (MISP/INSTALL) Seems to be broken in some way - cannot open it when downloaded and it also seems broken via online-view.

**Comment by elhoim** [comment]
Acrobat Reader 11 on windows can open the file without problem.
I suppose it is a case of permissive parser though.

**Comment by didelphodon** [comment]
I get this error using Acrobat Reader 11 on Windows 7 ...
![image](https://cloud.githubusercontent.com/assets/10989525/7582055/561f6534-f88a-11e4-840b-dcbc9449184c.png)
The message says that the file could not be opened due to a corrupted content. I downloaded from MISP/INSTALL by right-clicking and "save link to ...".

**Comment by iglocska** [comment]
Hello Didelphodon,

that is expected, when you right click -> save link to, you are actually
downloading the github page that then tries to load the document. Just left
click on documentation.pdf on github and then click on "raw"  in the right
upper corner.

**Comment by didelphodon** [comment]
Ahhh, shame on me you're right - thx!

However, a left-click on the file leads me to this ...
![image](https://cloud.githubusercontent.com/assets/10989525/7582381/41697b90-f88d-11e4-8ef1-3e5379d5a77f.png)
A click on the raw-button - as you mentioned - downloads the viewable file, though.

**Comment by iglocska** [comment]
That is very odd, it seems to render fine for me :) Maybe different adobe
plugin version?

**Comment by didelphodon** [comment]
I'm using the most recent version of Chrome which I think has a builtin PDF viewer.

**Comment by elhoim** [comment]
Foxit reader latest and chrome latest both on win7 have no problem rendering it.

**Comment by elhoim** [comment]
@didelphodon can I close?
