### ISSUE TITLE
 CSV Export has same events everyday

### ISSUE THREAD

**Issue by MamrK29** [MISP/MISP#4883]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS, 
| OS version (client)       | 10
| PHP version               | 7.2.13
| MISP version / git hash   | 2.4.107

### Expected behavior
Using the url download: https://mispurl.com/events/csv/download/1d/apikey:<apikey>
should return a csv file that contains attributes that appears in 1 day time frame. Since this will be pulled daily, the expected behavior is for the file to contain different attributes 

###Actual behavior
Every single day the csv file contains the exact same attributes which means it is only pulling for a specific day and not other days. This was confirmed when multiple events and attributes were added but they did not appear in the csv download.

###Steps to reproduce the behavior
download csv using url and api as mentioned above.
next day do the same and the file contents will be the same.

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/11075698/61302111-39aaf300-a7b3-11e9-8d7f-279b26ccab5c.png)

![image](https://user-images.githubusercontent.com/11075698/61302121-3f083d80-a7b3-11e9-907c-dfb8260a2e82.png)

**Comment by iglocska** [comment]
That URL sounds wrong, not really sure where it comes from. It's a deprecated endpoint with parameters that will not work.

Use this:

POST to: `/events/restSearch`
payload:
```
{
  "returnFormat": "csv",
  "publish_timestamp": "1d"
}
```

With the headers set as:

```
Accept: application/json
Content-type: application/json
Authorization: <<<YOUR_API_KEY>>>
```

If you cannot do post requests you can do the following:

GET url: `/events/restSearch/returnFormat:json/publish_timestamp:1d`

With the headers set as:

```
Accept: application/json
Content-type: application/json
Authorization: <<<YOUR_API_KEY>>>
```
