### ISSUE TITLE
Delete and propagate deletions of attributes

### ISSUE THREAD

**Issue by didelphodon** [MISP/MISP#489]
Is it possible to remove an attribute from an event using the REST API? And if so, how?

**Comment by iglocska** [comment]
Sure,

just send a delete request to:

https://<myMISP>/attributes/<attribute_id>

**Comment by elhoim** [comment]
I will close in 2 days if there is no more questions on this

**Comment by didelphodon** [comment]
Ah ok, thx. And what happens if I send an update-request with one attribute of the according event missing in the JSON?

**Comment by elhoim** [comment]
If I try to rephrase your question:
- If I delete an attribute and then I sync the event, will the deleted attribute deleted from the event stored in connected MISP instances.

I think the answer is no, delete do no propagate via sync. I added @iglocska to confirm this or kick me for saying something stupid.

**Comment by elhoim** [comment]
Ping @iglocska

**Comment by iglocska** [comment]
Sorry, missed this: Indeed, a deleted attribute will currently not be propagated. We used to do it inline which caused a lot of issues - I'll look into a way to handle this better.

**Comment by adulau** [comment]
This has been resolved in 2016 with the introduction of the soft-deleted attributes (May 2016).

An additional feature has been introduced 61464e5385e8ceaf86459da2861c8c4158293d34 to  	Security.sanitise_attribute_on_delete (disabled by default).
