### ISSUE TITLE
Controllers not multibyte capable, searches fail

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#4901]
Derived from the discussion on https://github.com/MISP/MISP/issues/4888

Many thanks to @tkhr2019 for pointing to the root cause, and @SoheiMitsukawa for initially raising the issue.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Any
| PHP version               | 7.2.19
| MISP version / git hash   | 2.4.111

### Expected behavior
MISP should be able to accept multibyte values via the REST API

### Actual behavior
Searching for events having multibyte characters fails due to missing multibyte support in the Controllers.

### Steps to reproduce the behavior

Running this simple python script first creates an event with multibyte character string for the EventInfo field. After that, it searches the event, but does not find it:

```
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from pymisp import PyMISP

misp = PyMISP('https://misp.example.com', '***APIAUTH***', True, 'json')
misp.new_event(info='ÄÖÜ')
print(misp.search_index(eventinfo='ÄÖÜ'))
```
Executing this script return no matches, even though the event was correctly created.
```
{'response': []}
```
Looking at the querylog on the MySQL server, you find entries like these:

```
[...] WHERE lower(`Event`.`info`) LIKE '%ÄÖÜ%'
```
This proves that the Controller did not correctly convert it's input to lowercase.

By changing the last line of the script to
```
print(misp.search_index(eventinfo=('ÄÜÖ'.lower())))
```
the problem can be circumvented, because the failing conversion to lowercase is done in the REST client, before talkint to MISP.

### Root Cause
in `.../app/Controllers/EventsController.php`, string conversion to lowercase (and uppercase) is done using `strtolower`/`strtoupper`. However, **these are not multibyte aware** and fail to convert language-specific characters such as the German Ä, Ö, Ü to their lower case. In contrast to this, the databases `lower()` function works correctly for those characters, resulting in the SQL-Code 

``` 
WHERE 'äöü' LIKE '%ÄÖÜ%'
```

Proof of failure of the string conversion in PHP:
```
<?php
printf("%s\n",strtolower('ABC_ÄÖÜ'));
printf("%s\n",mb_strtolower('ABC_ÄÖÜ'));
?>
```
returns
```
abc_ÄÖÜ
abc_äöü
```

### Solution
The MISP source code should be reviewed to use the multibyte-aware string conversion routines such as `mb_strtolower`/`mb_strtoupper` in the appropriate places (=everywhere?)

**Comment by enjeck** [comment]
Since this issue hasn't been reported in over a year, I assume it's fixed. It can be reopened if I'm wrong.
