### ISSUE TITLE
block_old_event_alert not working

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4909]
We have a 2 server setup. Server A pushes to server B. Both servers have `MISP.block_old_event_alert = true` and `MISP.block_old_event_alert_age = 30`

We did a mass-update of 1000+ events using PyMISP on server A. The updates were pushed to server B upon publish (as normal). Server B sent 1000+ notifications to every user even though the date field of most of the events was well over 30 days ago.

**Comment by iglocska** [comment]
The age looks at the timestamp of the event, not the "date" field. If the 1000 events have recently been touched then this will not block it. I think I know which 1000+ events you're talking about and the producer of the data has indeed "touched" all those events so sadly it's valid alerts...

**Comment by RichieB2B** [comment]
The explanation of `MISP.block_old_event_alert_age` says:

> If the MISP.block_old_event_alert setting is set, this setting will  control how old an event can be for it to be alerted on. The "Date"  field of the event is used. Expected format: integer, in days

So at the very least this is a documentation bug. (I did not check the code yet.)

**Comment by iglocska** [comment]
Oh woops. Indeed, the documentation is wrong.

**Comment by RichieB2B** [comment]
Of course the documentation is easy to fix, but actually acting upon the Date of an event would make this feature much more useful IMHO.

**Comment by RichieB2B** [comment]
Continuing this in #4937
