### ISSUE TITLE
External sync user can change local attributes

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4911]
This is a data integrity issue. When server A has a user U from a remote organization that has the `Sync user` role, this user can overwrite attribute data from local events on server A. All user U has to do is setup his own server B, pull the data from server A, manipulate the timestamps of the data and push it back to server A.

Steps to reproduce:

1. Pull all data from server A
1. Manipulate the attribute timestamp and value1 plus corresponding event timestamp and publish_timestamp
1. Push all data back to server A

Result:
The new attribute value will be shown, even if the manipulated attribute belongs to an event not owned by user U (ie org_id of the event != org_id from the user).
This should only be allowed if the user U is part of the local `MISP.host_org_id` (if at all).

**Comment by RichieB2B** [comment]
After reading more of the code it appears this is how syncing works: sync users are allowed to push data to MISP even if they are not the part of the original org_id. I guess this allows updates to event to come in from another server than the original event. Taking that away would loose a lot of the dynamics of the MISP ecosystem.

**Comment by iglocska** [comment]
Correct! Sync users have to be able to propagate changes on behalf of others as you've found. We have an exception, the only time we block such edits happens when data was created locally (this is what locked == false means in an event).

**Comment by RichieB2B** [comment]
Makes sense. Does locked == false propagate as false on local == true servers?

**Comment by iglocska** [comment]
It should. If it doesn't it's a bug and needs to be resolved!

**Comment by RichieB2B** [comment]
Ok, I created #4920 for this.
