### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#4921]
Is there any possibility to disable the logging to the MySQL database?
We got some rather large feeds, which produce ~100MB logdata every day when updating them. It would be great if it was possible to disable the logging temporarily, so the logs won't be polluted by that kind of data.

**Comment by iglocska** [comment]
ok, DEFINITELY not something I'd recommend doing. But added a feature that allows you to do so, just use `MISP.log_skip_db_logs_completely` in administration -> server settings -> MISP tab
