### ISSUE TITLE
Diagnostics page not visible

### ISSUE THREAD

**Issue by dewiestr** [MISP/MISP#4922]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Mac OS 10.14.5
| PHP version               | PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
| MISP version / git hash   | 2.4.111, latest commit ed37dae1fe9b1a779865c82b4d4742a6b1ad8527
| Browser                   | Safari 

### Expected behavior

Page showing up.

### Actual behavior

After the upgrade to the latest MISP update (2.4.111), the diagnostics page is unable to load. the only error that I'm getting is in app/tmp/logs/debug:

==> app/tmp/logs/debug.log <==
2019-07-22 05:21:16 Notice: Notice (8): Undefined index: User in [/var/www/MISP/app/Controller/UsersController.php, line 1303]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UsersController::__extralog() - APP/Controller/UsersController.php, line 1303
UsersController::login() - APP/Controller/UsersController.php, line 1013
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

Might this have something to do with a User setting that is undefined in my admin user ? 

### Steps to reproduce the behavior

As ADMIN > Click the diagnostics page

**Comment by nyx0** [comment]
Same issue here

**Comment by iglocska** [comment]
On 2.4.113?

**Comment by nyx0** [comment]
Yes I pulled the latest.

**Comment by SteveClement** [comment]
As this is an older issues with no follow-ups I will close in the meantime.
In case it persists please re-open.
