### ISSUE TITLE
Unable to add local tags to events owned by other org

### ISSUE THREAD

**Issue by tom564** [MISP/MISP#4925]
Raising new issue to prevent commenting on closed issue https://github.com/MISP/MISP/issues/4691 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Win 10
| PHP version               |  7.2.19
| MISP version / git hash   | 2.4.111, bcb057832c597d99a6bb56863ad08c2aaea6f420

### Expected behavior
When a user is a member of the host org and has the perm_tagger permission they will be able to locally tag events from other orgs. in this case the user has the publisher role. 

![image](https://user-images.githubusercontent.com/14953124/61676215-75f3cb80-ad3e-11e9-9310-30c69b5a36ea.png)

### Actual behavior

the option to add local tag is available but fails with "You don't have permission to do that". the user is able to add local galaxies but no tags. 

https://github.com/MISP/MISP/issues/4691

### Steps to reproduce the behavior
Add user into the host org with publish and perm_tagger roles, try to add local tag to event from another org.

**Comment by iglocska** [comment]
Is this still the case? Should be fixed thanks to @mokaddem's patch!

**Comment by tom564** [comment]
Hi, yep still looks to be an issue in c87af6751f4214313740ede9c77e00c2597321e2

**Comment by certbe-trey** [comment]
Still an issue in 122ff89f2f008730126e70d5301563f698446f62
