### ISSUE TITLE
Clean logs db

### ISSUE THREAD

**Issue by kalyparker** [MISP/MISP#4926]
Hello,

After a chat with @Rafiot, please find below the ugly script I used for cleaning the logs in the db.
Having logs in db is definitively not a good idea. We export interesting logs every hour to a dedicated file (option syslog export everything in syslog, so twice the size: db and filesystem - again not what I want)
Because I backup the logs using another way, having logs in db is just not necessary.
Please found below an ugly script which delete logs from a date:

```
#!/bin/bash

folder_dest=/var/log/misp
dbname=misp
# secure your conf file using appropriate right
dbfile=/home/misp/.my.cnf

# get today minus 6 month
dateforcleaning=$(date +'%Y-%m-%d' --date='-6 month')
#now=$(date +'%Y-%m-%d %')

# purge logs
query1='select count(*) from logs where date(created) <"'$dateforcleaning'";'
query2='delete from logs where date(created) < "'$dateforcleaning'";'
#echo $query

tmp=$(mysql --defaults-file=$dbfile $dbname -N -e "$query1")
mysql --defaults-file=$dbfile $dbname -N -e "$query2"
if [[ $? != 0 ]]
then
    echo "Error in log purge"
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $tmp lines in logs table before $dateforcleaning - ERROR during delete" >> $folder_dest/cleaning_6month.log
    exit 1
else
    echo "$(date +'%Y-%m-%d %H:%M:%S') - $tmp lines in logs table before $dateforcleaning - No Error during deletion" >> $folder_dest/cleaning_6month.log
    exit 0
fi
```

This script is used on ubuntu and on misp 2.4 (when the column created exist, the script works :) )

That's all
Enjoy

**Comment by SteveClement** [comment]
I integrated it into misp-refresh

Thanks for the contrib!

https://github.com/SteveClement/misp-refresh/blob/d56c13a26caf76805e0f55ba4d42239e97fd3a3a/refresh.sh#L143
