### ISSUE TITLE
Uploaded image attachments do not display when clicked

### ISSUE THREAD

**Issue by open-source-rs** [MISP/MISP#4929]
Note: issue still ongoing and related to issue #4791 

MISP version: 2.4.110
OS: Ubuntu 18.04

Issue:  Uploaded image attachments do not display when clicked. 

Example: 
MISP Event 2940

File uploads just fine.
![image](https://user-images.githubusercontent.com/50664502/61713596-f7d7fa80-ad26-11e9-8aaa-2535663ea809.png)

However, when clicking on the file screen hangs in this phase of display:

![image](https://user-images.githubusercontent.com/50664502/61713638-0b836100-ad27-11e9-9a63-c09212db7966.png)

The image will open if right clicked on and set to open in new tab:
![image](https://user-images.githubusercontent.com/50664502/61713691-248c1200-ad27-11e9-99b2-e70507bdd780.png)

Image size in new tab is alwasy 200x200.

Same results in Mozilla.

Jimbo

**Comment by cvandeplas** [comment]
The functionality appears to work with Google Chrome and Firefox. This must be an issue specific to your browser setup.
