### ISSUE TITLE
VirusTotal integration

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#493]
A simple lookup button (with a cached result if the lookup was already one) to lookup an indicator against VirusTotal.

**Comment by iglocska** [comment]
This is definitely planned for the future - however it should also go through a similar modular design as what's planned for the import / export. The idea is that it should be easy to create enrichment tools like this without much prior knowledge of the MISP internals.

Also, some of the lookups should be optional (for example if they require a paid API key, etc).

**Comment by Rafiot** [comment]
Will be implemented with misp modules

**Comment by Rafiot** [comment]
https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/virustotal.py
