### ISSUE TITLE
'Update MISP' works but submodules don't 

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#4931]
| OS version (server)       | Ubuntu 18
| OS version (client)       |  Firefox on Windows 10
| PHP version               | 7.2.19-0ubuntu0.18.04..
| MISP version / git hash   |v2.4.111 (b27a5a188823092e259fd1ba49310062394a08d5)

Updated to the latest version of MISP using the GUI and 'Update MISP' button and it's giving me status OK, BUT all the submodules won't update and are telling me that I have local changes... but I don't have any local changes... it's a relatively fresh install. 

i.e. this one for 
error: Your local changes to the following files would be overwritten by checkout:
	MANIFEST.json
	dark-web/machinetag.json
	maec-malware-capabilities/machinetag.json
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '788371461432499007d558fc7acb4477c3d9a898' in submodule path 'app/files/taxonomies'

Is there something I"m doing wrong?  Thanks!

**Comment by mathurin68** [comment]
and from the command line I get -- 
```
 git status
On branch 2.4
Your branch is up to date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   INSTALL/dependencies/Console_CommandLine (modified content)
        modified:   INSTALL/dependencies/Crypt_GPG (modified content)
        modified:   INSTALL/dependencies/Net_GeoIP (modified content)
        modified:   Plugin/DebugKit (modified content)
        modified:   PyMISP (new commits, modified content)
        modified:   app/Lib/cakephp (modified content)
        modified:   app/Lib/random_compat (modified content)
        modified:   app/composer.phar
        modified:   app/files/misp-galaxy (new commits, modified content)
        modified:   app/files/misp-objects (new commits, modified content)
        modified:   app/files/noticelists (modified content)
        modified:   app/files/taxonomies (new commits, modified content)
        modified:   app/files/warninglists (modified content)
        modified:   cti-python-stix2 (new commits, modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        app/Config/config.php.bk

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by adulau** [comment]
`app/Config/config.php.bk` it seems that you have some untracked file in your repo. Just do a git reset if you don't mind to loose the files ;-)

**Comment by expl0it0473** [comment]
I get a similar error, but I don't want to lose my files, I tried git stash, but it says no "local changes to stash". 
Is there another git command I can use to solve the problem? 
I'm on the latest version v2.4.170 (c3f7077abe111154017b52fac504f293ea41a471) on RHEL 8.
