### ISSUE TITLE
Missing event from remote MISP server pulling 

### ISSUE THREAD

**Issue by mkatani** [MISP/MISP#4933]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | 10
| PHP version               | 7.1
| MISP version / git hash   | 2.4.111
| Browser                   | Chrome

### Expected behavior
Trying to pull events from one internal MISP to another internal MISP server. Connection test and explore the remote server works. 
Create a sync rule with some filter to pull only specific event from remote server, it works but not all events that i wanted. I didn't found the reason why some events (more than 100) not coming to Server. Then i have tried to explore the remote Server and pull some missing event manually, the result in log is "0 events and 0 proposals pulled or updated. 0 events failed or didn't need an update."   

### Logs, screenshots, configuration dump, ...

- resque-worker-error.log
Pull completed. 0 events pulled, 0 events could not be pulled, 0 proposals pulled.

**Comment by iglocska** [comment]
Are the events published?

**Comment by mkatani** [comment]
Yes the events are published and just FYI it is not because of Distribution level.

**Comment by iglocska** [comment]
I can't seem to be able to reproduce it. Could you update to the latest version and try again?

**Comment by mkatani** [comment]
Hi again and sorry for the late response.
I found the reason, the events were in "Event Blacklists" and after removing it from the list now it works.
Only one question that i like to know, why Balcklist? is there any reason for that?

**Comment by mokaddem** [comment]
We are using blacklists to avoid re-ingesting locally deleted events coming from another sync server. For example,
1. You create Event *A*
2. You synchronize with your peer
3. You delete Event *A*
4. You synchronize again with your peer
5. Without the blacklist, you would get Event *A* restored in your instance. Thanks to the blacklist, it is not.

I hope that clarify your question.
