### ISSUE TITLE
Do not send E-mails for updates on old threats

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#4937]
Make `MISP.block_old_event_alert` and `MISP.block_old_event_alert_age` act upon the Date of an event instead of the timestamp. The reasoning is: if someone updates an event that describes a threat in the (distant) past there is no need to send an E-mail alert.

**Comment by iglocska** [comment]
I think the timestamp one is definitely needed (for example: If an older threat gets new indicators / an update that might be interesting) - but adding a secondary alert blocker based on the date field would indeed make sense.
