### ISSUE TITLE
Feature Request: add support to include RelatedEvents in pymisp.search

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4940]
Would be a great help to add support to include the correlated `RelatedEvents` in the result returned from `pymisp.search`. Our need is with `controller='attributes'`, but `events` makes sense also.

This was explored in MISP/PyMISP#414 where we observed `RelatedEvents` included in other retrieval methods but not in `pymisp.search`.

**Comment by github-germ** [comment]
Thanks for re-opening!!

**Comment by packet-rat** [comment]
Andras,
Many thanks.  This is much appreciated!
Pat Maroney

On Aug 2, 2019, at 7:46 AM, Andras Iklody <notifications@github.com> wrote:

Closed #4940 via 7003faa.

**Comment by iglocska** [comment]
No worries!

**Comment by github-germ** [comment]
@Andras -- Wonderful. Thanks a ton!

I tested and indeed `RelatedEvents` looks great in the results for `pymisp.search(controller='events', includeCorrelations=1, ...)`. However, we also have a use case searching for `controller='attributes'` -- and as I'm sure you know it's not in that response.

Any chance it's not a big deal to roll into `attributes` also?

Or perhaps you can revise our use case logic... We ask for `attributes` as we want all that have had activity in a given period (e.g. `timestamp='90d'`). Our thought was this was more efficient vs. going at the `events` level, getting a much larger response, and then having to traverse every attribute and filter by its `timestamp`.

Your thoughts greatly appreciated. Thanks!

**Comment by packet-rat** [comment]
Seconding @github-germ:   The ability to query on an **Attribute** of interest and see the **Correlations** is a key value proposition.  

It would also be great if we could query on the 'count of correlations':  i.e.,  Give me all attributes with more than 25 correlations

**Comment by iglocska** [comment]
I've added it to attributes, events already had it

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/commit/7003faa00cdb38a4da78fa0e21675d6ce017f1b8

for more info.

**Comment by github-germ** [comment]
> I've added it to attributes, events already had it

i thought i pulled the latest including https://github.com/MISP/MISP/commit/7003faa00cdb38a4da78fa0e21675d6ce017f1b8 into my VM, the results from `controller='attributes'` had no `RelatedEvent` keys for attributes I know have correlations. I will look again.

**Comment by iglocska** [comment]
Tested it on MISP side at least and the correlations are definitely there ;)

**Comment by iglocska** [comment]
Keep in mind you do have to pass the parameters that I've described above. We will definitely not flood users with this by default, so make sure you pass "includeCorrelations":1 in the request object (as described in the commit and the other issue).

**Comment by github-germ** [comment]
Yes, i had that: `pymisp.search(controller='attributes', includeCorrelations=1, ...)` BUT apparently my earlier `git pull origin 2.4` didn't succeed. HOWEVER, now it did, and indeed, **IT WORKS!!!**

**A W E S O M E**

Details for other folks to see how it works. NOTE: when controller is events you get `RelatedEvents` and for attributes it's `RelatedAttributes`.

Here's what I did...

1. Pick an attribute and it's event that has correlations:
```
MariaDB [misp]> select count(*) from correlations where 1_attribute_id=457937;
+----------+
| count(*) |
+----------+
|       17 |
+----------+
1 row in set (0.00 sec)

MariaDB [misp]> select event_id,count(*) from correlations where attribute_id=457937;
+----------+----------+
| event_id | count(*) |
+----------+----------+
|    48493 |       17 |
+----------+----------+
1 row in set (0.00 sec)

MariaDB [misp]>
```

2. PyMISP code excerpt:
```
try:
    start = timer()
    sys.stderr.write('call search()\n')

    r = misp.search(
        controller          = 'attributes',
        includeCorrelations = 1,
        eventid             = 48493)

    sys.stderr.write('search() returned in secs=%.1f\n' % (timer()-start))
    for attr in r['response']['Attribute']:
        if attr['id'] == '457937':
            sys.stdout.write(json.dumps(attr, indent=2))

except Exception as e:
    sys.stderr.write('search() exception (secs=%.1f): %s\n'
                     % (timer()-start, str(e)))
    sys.exit(5)
...
```

3. Yes, `RelatedAttribute`...
```
$ cat j.json
{
  "id": "457937",
  "event_id": "48493",
  "object_id": "0",
  "object_relation": null,
  "category": "Network activity",
  "type": "url",
  "to_ids": true,
  "uuid": "fd79fb17-f1cd-42aa-9f69-699a20190d00",
  "timestamp": "1562617952",
  "distribution": "5",
  "sharing_group_id": "0",
  "comment": "url REDACTED",
  "deleted": false,
  "disable_correlation": false,
  "value": "http://REDACTED",
  "RelatedAttribute": [
    {
      "id": "427849",
      "event_id": "47998",
      "object_id": "0",
      "object_relation": null,
      "category": "Network activity",
      "type": "url",
      "uuid": "02af985a-4b74-4d9f-8875-38985858d0eb",
      "timestamp": "1550730200",
      "distribution": "5",
      "sharing_group_id": "0",
      "to_ids": true,
      "comment": "url REDACTED",
      "value": "http://REDACTED",
      "Event": {
        "id": "47998",
        "uuid": "5c6e43d1-8478-4f96-adf7-0763496a006a",
        "threat_level_id": "2",
        "analysis": "0",
        "info": "REDACTED",
        "extends_uuid": "",
        "distribution": "3",
        "sharing_group_id": "0",
        "published": true,
        "date": "2019-02-21",
        "orgc_id": "21",
        "org_id": "2"
      }
    },
   ...
$ 
```

**Comment by github-germ** [comment]
Lastly...

@packet-rat ... This is a super request. Fits one of our very important use cases!
> It would also be great if we could query on the 'count of correlations': i.e., Give me all attributes with more than 25 correlations

@iglocska ... Is this possible, and if so, should it be in a separate feature request issue?

**Comment by iglocska** [comment]
Separate one please, we currently can't query on counts at all, might make sense for other uses cases too (give me all events with > 100 attributes, etc)
