### ISSUE TITLE
MISp Dashboard

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4941]
Work environment
|Type of issue | support
|OS version (server) | RedHat
|MISP| Implemented on docker/ubuntu
|OS version (client) | windows 7
|PHP version | 7.2.10
|MISP version / git hash | v2.4.107 ()

I have a dockerized instance of MISP running on RHEL. I am trying to set up live dashboards using instructions from GIThub and https://www.vanimpe.eu/2017/10/31/misp-dashboard-real-time-visualization-misp-events/?unapproved=119326&moderation-hash=42c28b90ab7feb92001c20f2eebe64b6#comment-119326

Although I had some error /warning messages when running ./server.py see  MISP/misp-dashboard#119 . I am able to bring up the dashboard but no data appears. I even tried to publish an event to zmq
![image](https://user-images.githubusercontent.com/42444130/62166508-8f6cb880-b2e6-11e9-86c2-98c868267408.png)

Can anyone help me with this issue?

**Comment by iglocska** [comment]
This sounds like an issue for https://github.com/MISP/misp-dashboard. Closing it for now over here, could you open an issue over there?

**Comment by dmolina213** [comment]
I opened it there https://github.com/MISP/misp-dashboard/issues/120  can someone take a look
