### ISSUE TITLE
Local tags applied to events owned by my organization appear as global tags in the UI

### ISSUE THREAD

**Issue by certbe-trey** [MISP/MISP#4943]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.2 LTS
 OS version (client)       | Windows 10
| PHP version               | 7.2.19
| MISP version / git hash   | 2.4.111, 4345063456d3063ab31e208d1ca9f79e29380acc
| Browser                   | n/a

### Expected behavior
A local tag applied to an event (whether created by my organization or another) is displayed in the UI as a local tag and behaves as such (e.g., does not get propagated outside of my organization.)

### Actual behavior
A local tag applied to an event created by my organization is displayed in the UI as a global tag and behaves as such (e.g., does not get propagated outside of my organization.)

### Steps to reproduce the behavior
1. Create a test event.
2. Add a test attribute
3. Tag test event with a local tag.
4. Refresh the page. Local tag is now displayed as a global tag.

**Comment by iglocska** [comment]
I can't reproduce this. Are you using the UI to add said data?

**Comment by certbe-trey** [comment]
Yes. What user role are you testing as? (This behavior manifests both with a default user and default org admin.)

**Comment by iglocska** [comment]
Testing with default org admin next

**Comment by iglocska** [comment]
Works for me.

**Comment by iglocska** [comment]
After a debug session, this was resolved.
