### ISSUE TITLE
Question: how to "shrink/compress" tags in the Event list?

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#4945]
I have two MISP installations for testing, one a bit older, the other new.

In the event list, one has "expanded" tags, the other one "compressed". I can't find where I can configure the tag display. 

Can somebody please tell me more? Thank you.

Good:
![misp1](https://user-images.githubusercontent.com/50981940/62297100-d7b7e200-b470-11e9-9c9a-5ba757c9c717.png)

Not so good:
![misp2](https://user-images.githubusercontent.com/50981940/62297101-da1a3c00-b470-11e9-8674-bec7cea70881.png)

**Comment by iglocska** [comment]
Administration -> Server settings -> MISP.full_tags_on_event_index


However, there was briefly a bug that defaulted to the wrong value (the minimal cards in the first screenshot) if the setting was not configured as opposed to the full tag name that is normally the default. If you have that issue just update.

**Comment by adulau** [comment]
MISP.full_tags_on_event_index in the Server Settings.
