### ISSUE TITLE
Ubuntu 18.04.2 Script Install - localhost:8443 unable to connect 

### ISSUE THREAD

**Issue by JR-ship** [MISP/MISP#4954]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (client)       | Ubuntu 18.04.2
| MISP version / git hash   | 2.4
| Browser                   | Firefox

### Expected behavior
Initial installation and access web login page

### Actual behavior
Ubuntu 18.04.2 install, ran install script successfully and upon install I am unable to browse to https://localhost:8443. When I run netstat and check for 8443 I can see no service is listening on that port. 

When I run sudo su -l www-data -s /bin/bash -c "bash /var/www/MISP/app/Console/worker/start.sh" the workers successfully start but I am still not able to connect to the web interface. 

### Steps to reproduce the behavior
Clean Ubuntu 18.04.2 Installation
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
Try to browse to https://localhost:8443 upon completion.

**Comment by SteveClement** [comment]
There seems to be an inconsistency with the output.

The install script should have made port 443 available.

Can you browse to: https://localhost ?

**Comment by JR-ship** [comment]
I attempted to re-create the issue last night using another environment and everything worked as expected, something on my end.
