### ISSUE TITLE
Import fail

### ISSUE THREAD

**Issue by didniv18** [MISP/MISP#4957]
Hello, 
Im trying to export and import events from one misp to other( filtered by datefrom).
I get an error when trying to import:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

My code is : 

from requests.auth import HTTPBasicAuth
import requests
from datetime import date

i=2
url = "http://ipaddress:81/events/index"
headers = {"Authorization": "apikey","Accept": "application/json","Content-Type": "application/json"}
body = {"datefrom": '2019-07-30'}

req = requests.post(url, headers=headers,json=body)
a = req.text
filename = "ID%d.xml "%(i)
file = open(filename,"w")
file.write(a)
file.close()

**Comment by didniv18** [comment]
The code for export is above .
Im trying to import manually from the ui.
Im attaching example for my output file(cant upload XML) 

[ID2.txt](https://github.com/MISP/MISP/files/3471704/ID2.txt)

**Comment by adulau** [comment]
It's an index JSON. You have to import the JSON from the event itself.

**Comment by rommelfs** [comment]
Your endpoint should be 
url = "http://ipaddress:81/events/restSearch"

**Comment by rommelfs** [comment]
iterate over the events
exports one after the other via events/restSearch
import one after the other via /events/add

**Comment by didniv18** [comment]
you mean like that ? its not working.

from requests.auth import HTTPBasicAuth
import requests
from datetime import date
import json


url = "http://ipaddress:81/events/restSearch"
headers = {"Authorization": "apikey","Accept": "application/json","Content-Type": "application/json"}

body = {"datefrom": "2019-07-30"}
req = requests.post(url, headers=headers,json=body)
data = req.json()
with open('data.json', 'w') as f:
    json.dump(data, f)

**Comment by iglocska** [comment]
"datefrom" is not a valid filter for the restSearch API. Please make sure that you check the automation documentation (in your MISP go to event actions -> automation) to see a list and description of the possible filters.

**Comment by didniv18** [comment]
@rommelfs told me to use it, and it seems to work.
It looks like the output is not in the right format or something.
"searchDatefrom" as shown in documentation doesn't filter at all .

**Comment by rommelfs** [comment]
it's valid on events/index, not on events/restSearch
