### ISSUE TITLE
Inconsistencies in add/edit attribute

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4959]
* [ ] list of attributes
It returns a dictionary  like that
`{'0' : {<attribute>}, '1': {<attribute>}, 'errors': {attribute_0: <errorinfo>, attribute_4: <errorinfo>}}`
Instead of:
`{Attribute: [{<attribute>}, {<attribute>}], 'errors': {attribute_0: <errorinfo>, attribute_4: <errorinfo>}}`

* [ ] tags are an independent key (`AttributeTag`) instead of bundled in the attribute in the `Tag` key

**Comment by Rafiot** [comment]
Required for 2.4.113 => https://github.com/MISP/PyMISP/blob/master/pymisp/aping.py#L358

**Comment by iglocska** [comment]
Both should be fixed now

**Comment by Rafiot** [comment]
Yep.
