### ISSUE TITLE
E-mail alerts customized by user (subscription based)

### ISSUE THREAD

**Issue by morallo** [MISP/MISP#496]
Right now, a user can only receive alerts for all events or none at all. It is the publisher who chooses if the users will receive a notification (publish with or without e-mail).

IMHO, it would be a lot more flexible to allow users to "subscribe" to a certain set of events:
- By tag
- By threat level
- By Org
- By Distribution values

**Comment by morallo** [comment]
The subscription rules could include #4, #46 , #341, #225, #261

**Comment by advancedeng** [comment]
That would be a really useful feature!!

**Comment by adulau** [comment]
That would be a great functionality after the 2.4 release (at least starting with threat level).

**Comment by droe** [comment]
Would love to see this or #497 implemented; we are using MISP with users who have different areas of focus; it would help us if some of our users could only subscribe to the tags that are of relevance to them.

**Comment by axpatito** [comment]
I **have to** implement this function, anybody knows if someone made any progress? I will start working on this soon.

**Comment by SteveClement** [comment]
@axpatito as far as I know, not yet.
Make sure to join https://gitter.im/MISP/MISP too to make faster progress.

Looking forward to your contribution.

**Comment by Rafiot** [comment]
This is fixed in 2.4.118 (to be released very soon).
