### ISSUE TITLE
Default Feed https://zeustracker.abuse.ch out of business

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#4963]
The default feeds for https://zeustracker.abuse.ch do not work anymore, since zeustracker is out of business by 8th July, 2019.

Please update MISP (app/files/feed-metadata/defaults.json) and https://www.misp-project.org/feeds/

**Comment by SteveClement** [comment]
Thanks for this, PR created: https://github.com/MISP/MISP/pull/5377
