### ISSUE TITLE
Really weird (TM) gui issue wrt Tags

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#4967]
v2.4.112: Tags are not being fully displayed on the front page:
![tag1](https://user-images.githubusercontent.com/25325656/62691524-29abbb00-b9cf-11e9-9397-2dffe6a1484b.png)

whereas the view from within the event is fine:
![tag2](https://user-images.githubusercontent.com/25325656/62691571-3af4c780-b9cf-11e9-9d0f-30b46b2404e4.png)

Don't see anything inside the logs. Ideas anyone?

**Comment by iglocska** [comment]
git pull (tm)

**Comment by iglocska** [comment]
(It's a setting we had for ages, but I can't read and implemented the wrong default ;))

**Comment by StefanKelm** [comment]
Oh dear, I actually was aware of that setting for ages but didn't even think about that one...  ;)
