### ISSUE TITLE
Unable to delete event or object by UUID

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4974]
The same way we can get an event by UUID, it would be nice to delete an event or an object by UUID (it works for attributes).

**Comment by zaphodef** [comment]
It already works for events' UUID, sending `DELETE /events/{UUID}` no?

**Comment by iglocska** [comment]
I think that was a brainfart - it was true for attributes and objects, I think I pushed a fix for the attributes a few days ago and thanks to you both points are now covered :)
