### ISSUE TITLE
Setting of MISP.full_tags_on_event_index does not work

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#4977]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Win7
| PHP version               | 7.2.19-0Ubuntu0.18.04.01
| MISP version / git hash   | 2.4.111

### Expected behavior
Toggeling through the settings of `MISP.full_tags_on_event_index ` should control the verbosity of the tags in the event index view.

### Actual behavior
MIPS always shows the full tags (current setting: minimal tags):
![misp tags2](https://user-images.githubusercontent.com/50981940/62852440-b44f2b80-bce9-11e9-8d30-5ff46bb581c3.png)
![misp tags](https://user-images.githubusercontent.com/50981940/62852494-d5178100-bce9-11e9-8bf4-d6e7f760ebbb.png)

### Steps to reproduce the behavior
This seems **only to happen on upgraded versions of MISP**. Mine was installed by May 16th (unknown version, 2.4.109???), upgraded to 2.4.111.

A fresh 2.4.111 does not have this problem

**Comment by StefanKelm** [comment]
related to #4967 :-)

**Comment by ITServ-DE** [comment]
Thank you for linking, Steffen. 

In your issue, you did not mention if changing setting changes the behaviour of the page (it does not for me). 

Did you simply not know about it, ir did'nt it work for you, too?

And, by the way: [#4978](https://github.com/MISP/MISP/issues/4978) :-)

**Comment by iglocska** [comment]
Please update to the latest version, this should work as intended on HEAD :)

**Comment by ITServ-DE** [comment]
fixed in 2.4.112; closed
