### ISSUE TITLE
import events through api

### ISSUE THREAD

**Issue by didniv18** [MISP/MISP#4985]
Is it possible to import events with its attributes through the api ?

**Comment by mokaddem** [comment]
Hi, something like this should work.
```
{
    "info": "Event created via the API as an example",
    "threat_level_id": 1,
    "distribution": 0,
    "Attribute": [
        {
            "value": "9.9.9.9",
            "type": "ip-src"
        }
    ]
}
```
Cheers!

**Comment by didniv18** [comment]
What i mean is that i already exported a file from one misp and i want to import it to other misp.
Is it possible to push it ?

**Comment by iglocska** [comment]
How did you export it? Download as misp json?

**Comment by didniv18** [comment]
Iv'e created script that create XML with events from the date I decided.
Now I want to import those events to another misp - not by GUI.
I want to make this process automatic with api.

**Comment by Rafiot** [comment]
Don't use XML, it is deprecated and should never be used in new projects. Use json please.

**Comment by didniv18** [comment]
So how do import those events after export ?

**Comment by iglocska** [comment]
Just export them as JSON.

**Comment by didniv18** [comment]
OK i understood but i dont want to import from GUI I want to import through API.
I couldn't find what should be the commands for it.

**Comment by iglocska** [comment]
/events/add -> POST individual events there

**Comment by Rafiot** [comment]
... and import the file by clicking on `Import from... `
![Screenshot_20190820_093722](https://user-images.githubusercontent.com/248875/63327292-3369e280-c32e-11e9-9653-5a3c09ae0fa7.png)

Or use `add_event` if you're using python. 

Or POST the file to https://<domain>/events

**Comment by didniv18** [comment]
Ok iv'e tried to use the post with curl but it imports the event with no attributes : 
curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: apikey" --data "@data.json" -X POST http://ip:81/events

What am I doing wrong ?

**Comment by iglocska** [comment]
Could you send me a sample data.json that fails for you, so that I can help you troubleshoot it? andras@circl.lu

**Comment by didniv18** [comment]
[data.txt](https://github.com/MISP/MISP/files/3519360/data.txt)
