### ISSUE TITLE
Unable to update attribute by UUID 

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4990]
MISP doesn't let me update an attribute by passing it's UUID (it wants the ID)

**Comment by iglocska** [comment]
Works for me.

![image](https://user-images.githubusercontent.com/3668672/63010876-7f78db00-be87-11e9-97c3-7f37e09634d4.png)

**Comment by Rafiot** [comment]
Yeah, sorry, that's the fallback to proposals from attribute update if the user doesn't own the event.
