### ISSUE TITLE
Unable to get Sightings by Organisation UUID

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4992]
Not sure it is a bug tho (the key to pass to the controller is called `org_id`)

**Comment by iglocska** [comment]
Via restsearch? This is intentional, but we could add an org_uuid filter.

**Comment by iglocska** [comment]
the sighting restsearch is super simple actually, so added.

**Comment by Rafiot** [comment]
No, it was via `'sightings/listSightings'` and `to_post = {'id': misp_entity.id, 'context': context, 'org_id': <ORG_ID>}`
