### ISSUE TITLE
MISP sessions performs a refresh and redirects to the list of events

### ISSUE THREAD

**Issue by Shad0wleb** [MISP/MISP#4996]
I'm using MISP on amazon.
When the internet  session passes through a web proxy I have the following problem:

I noticed in versions later then 2.4.109  (for instance 2.4.111 and 112) when I open an event, few seconds after the page refreshes and goes back to the list of events, this interrupts my work and I cannot complete and event.
The issue disappears if I have a direct internet access and I do not pass through a web proxy.
Anyone had this problem?

**Comment by Shad0wleb** [comment]
is there a way to stop the page refreshing every 5 seconds?

**Comment by iglocska** [comment]
I have no idea why you get redirected, but you can disable the login check by enabling this setting:

`MISP.disable_auto_logout`

in administration -> server settings -> MISP tab

**Comment by Shad0wleb** [comment]
Thanks iglocska
your recommended solution solved the issue
I appreciate it a lot
best.

**Comment by iglocska** [comment]
Great, thanks for the feedback!
