### ISSUE TITLE
if there's an error at scheduled tasks, they don't run again

### ISSUE THREAD

**Issue by capile** [MISP/MISP#500]
Ola,

whenever there's an error on a scheduled task (lost connection with redis-server, for example), they stop running completely (next run is not updated).

It'd be good to have a backup for this — even if it means adding a restart on a cron job.

Thanks,

Guilherme Capilé

**Comment by iglocska** [comment]
Indeed, I'll keep this in mind, it's silly that it currently sets the next execution after the job finishes.

**Comment by iglocska** [comment]
Ignore the last comment, accidentally referenced this instead of issue #560 :)

**Comment by iglocska** [comment]
Fixed in b36c0da66a0246c871f9df559f834dc08ccb41d1
