### ISSUE TITLE
Bug with warninglists

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#5008]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18.04
| OS version (client)       | Win 10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.112, cf6bc6f2047284597aa3290f48235f91d2adef3e
| Browser                   | Firefox

Hey, we've just seen some unusual behaviour/bug since one of the latest releases.

### Expected behavior
Warninglists work as intended

### Actual behavior
Warninglists with type 'hostname' seem to be very sensitive regarding certain URLs.
Many URLs are flagged as a warning, even if they are legitimate. As far as I can see, it happens to URLs which end with [dot][number], eg. ".1"

### Steps to reproduce the behavior
Activate any warninglists with type hostname and matching on URLs.
Create an event, add any url ending with [dot][number]

### Logs, screenshots, configuration dump, ...
![warninglist bug](https://user-images.githubusercontent.com/31033198/63091221-fd0f1a80-bf5d-11e9-99e3-007056c73c2b.png)

**Comment by JakubOnderka** [comment]
Sorry, this bug was introduced in my pull request https://github.com/MISP/MISP/pull/4965. I will try to send fix tonight or tomorrow.

**Comment by iglocska** [comment]
Reverted it for now, so no rush! Should work again, @JakubOnderka - take your time!
