### ISSUE TITLE
Edit feeds - Returns Error: Invalid Feed.

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#5009]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Windows 10
| PHP version               | 7.0.33-0+deb9u3
| MISP version / git hash   | v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) 
| Browser                   | Chrme

### Steps to reproduce the behavior
After upgrading from v2.4.112 (c73be6ded045d754bc2936bd89d9c3953e3ac6f1)  to v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e)  I'm starting to get 404 errors when trying to access feeds edit

- Upgrade to v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) 
-  Sync Actions
- List Feeds
- Choose Edit "CIRCL OSINT Feed"

Returns:
```
Invalid Feed.
Error: The requested address '/feeds/edit/1' was not found on this server.
```

**Comment by eCrimeLabs** [comment]
It is the same for all feeds

**Comment by ITServ-DE** [comment]
Can't confirm. Sorry. 

After having upgraded my MISP from 2.4.111 to 2.4.112, I still can edit the feeds.

**Comment by eCrimeLabs** [comment]
> Can't confirm. Sorry.
> 
> After having upgraded my MISP from 2.4.111 to 2.4.112, I still can edit the feeds.

What hash value you have in version latest pull ?

**Comment by ITServ-DE** [comment]
I didn't update using git, I updated through the web interface. My versions are:

```
Currently installed version… v2.4.112 (3186b8781eefb79dbe389a1ce0354908290a8e7e) 
Latest available version… v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) 
```

**Comment by ITServ-DE** [comment]
I will take a snapshot of my host tonight and update it again. Read you tomorrow.

**Comment by zam89** [comment]
I'm using MISP v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) - updated thru web interface:
```
Currently installed version… v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) 
Latest available version… v2.4.112 (cf6bc6f2047284597aa3290f48235f91d2adef3e) 
Status… OK 
Current branch… 2.4 
```
I'm using MISP on **Ubuntu 18.04.3 LTS** with **PHP 7.2.19-0ubuntu0.18.04.2**.

When I try to edit feed, it will show page as below:
```
Invalid Feed.
Error: The requested address '/feeds/edit/1' was not found on this server.
```
This is what shown on debug.log when I try to edit feed:
```
2019-08-15 22:01:37 Notice: Notice (8): Undefined variable: id in [/var/www/MISP/app/Controller/FeedsController.php, line 269]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
FeedsController::edit() - APP/Controller/FeedsController.php, line 269
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```
I tried editing feed "CIRCL OSINT Feed", "blockrules of rules.emergingthreats.net", "Phishtank online valid phishing". Still giving same error.

**Comment by Rafiot** [comment]
We're reworking some of the calls, this one is broken right now and will most probably be fixed on Monday next week.

**Comment by iglocska** [comment]
This should work fine now.

**Comment by davealyn** [comment]
I am also having this problem on a fresh instance, have recently cached default feeds.
