### ISSUE TITLE
Updating attribute via API

### ISSUE THREAD

**Issue by UnderAway** [MISP/MISP#5011]
Ubuntu 18.04.2 LTS
MISP 2.4.110

Hello!

When I want to update attribute (comment) in event, I use method API - /attributes/uuid   

1) If in a new data I use "timestamp", I get response 405:
{'name': 'Attribute could not be saved: Attribute in the request not newer than the local copy.', 'message': 'Attribute could not be saved: Attribute in the request not newer than the local copy.', 'url': '/attributes/5d542009-cba8-474f-8828-3f9fc0a82094'}

2) If in a new data I don't use "timestamp", I get response 200:

{'response': {'Attribute': {'id': '11111', 'type': 'email-src', 'to_ids': False, 'category': 'Payload delivery', 'uuid': '5d542009-cba8-474f-8828-3f9fc0a82094', 'event_id': '111', 'distribution': '5', 'timestamp': '1565857854', 'comment': "TestComment1", 'disable_correlation': False, 'value': 'example@example.com'}}}

But in both cases, the attribute was updated. Example, comment.

Is it normal? I don't think so.

**Comment by iglocska** [comment]
Could not reproduce on HEAD, attribute only gets updated if timestamp is not set or newer via /attributes/edit. Could you update your MISP and try again?
