### ISSUE TITLE
Bug: push sync broken

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#5012]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (source server)       | Ubuntu
| OS version (destination server)       | Debian
| PHP version (source server)              | 7.2.19
| PHP version (destination server)              | 7.0.33
| MISP version / git hash   | 2.4.112

### Expected behavior
push syncronisation works

### Actual behavior
push syncronation fails when pushing events; other things work, for example browsing the remote MISP, connection test, even initial sync communication. But when it comes to transferring the events, I get an HTTP 403 (Permission denied) error.

From the apache logs (take special notice for the 403 errors):
```
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 3943 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "POST /events/filterEventIdsForPush HTTP/1.1" 200 4531 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:07 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events HTTP/1.1" 403 4317 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events HTTP/1.1" 403 4317 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "GET /servers/getVersion HTTP/1.1" 200 4226 "-" "CakePHP"
sourcehost - - [15/Aug/2019:08:45:08 +0200] "POST /events/index HTTP/1.1" 403 3873 "-" "CakePHP"
```

For further information, see https://github.com/MISP/MISP/issues/5007.

### Steps to reproduce the behavior
1. Set up two misp server (named source and target)
2. on the target host, create a user with the SYNC permission
3. on the target host, Login as sync user
4. on the target host,create sync config
5. Log in to the source hosts as admin
6. on the source host, choose *import server settings* and paste the settings from above
7. on the source host, edit the settings for the connection and enable "Push" sync mode
8. after saving, verify connection by performing a connection test (succeeds)
9. on the source host, force the sync by clicking the *push all* icon (arrow up)

Monitor the target servers web server log (for HTTP 403 errors) while reading the source host's `MISP/app/tmp/logs/error.log`.

Also by logging the authentication attemps, you will see that some sync auths work and some not.

**Comment by iglocska** [comment]
Reproduced exactly as described above and it all works as expected. Are both instances up to date?

**Comment by iglocska** [comment]
Closed the issue for now, leaving the duplicate open.
