### ISSUE TITLE
Updated to latest HEAD, but no version change

### ISSUE THREAD

**Issue by ITServ-DE** [MISP/MISP#5019]
Hi *!

I just updated my MISPs using *Diagnostics -> Update MISP*, and now I have the current commit version, but the version number did not update and MISP still claims I'm outdated. That happend on two out of two servers.

Any idea what happened and how I can fix this issue?

![Snag_3deca172](https://user-images.githubusercontent.com/50981940/63244219-131e2300-c25d-11e9-970d-87e292760e0e.png)
![Snag_3decdda6](https://user-images.githubusercontent.com/50981940/63244228-1b765e00-c25d-11e9-989e-98a8f6f504db.png)

**Comment by iglocska** [comment]
Someone with fat fingers may have mistyped git push and thus the version string update was not pushed. Fixed now. Cough.

**Comment by ITServ-DE** [comment]
Thank you for the extremely fast fix, updated again and now all is well. So I can go back to my Push-Sync problem and see if it's still there.

**Comment by iglocska** [comment]
Give me a holler if it is and we can look into it!
