### ISSUE TITLE
Free text import tools improvement

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#502]
If you have such list of MD5 + filename:

~~~
6545d2528460884b24bf6d53b721bf9e  5dro.exe
e339fce54e2ff6e9bd3a5c9fe6a214ea  AndroSpread.exe
9e208e9d516f27fd95e8d165bd7911e8  AndroSpread.exe
~~~

The free text import tools will only propose filename for the whole line. It would have been more interesting to have a split per "word" and do the regexp pattern matching on each "word". To have "md5" and "filename" attributes proposed.

Thanks a lot.

**Comment by elhoim** [comment]
Might be related to #300

**Comment by adulau** [comment]
I think it's related. I wonder if a simple "strtok" will do the job or if it needs to be more clever.

**Comment by iglocska** [comment]
I have it fixed locally today, will push it as a patch package later today, the simple solution was to not just split the input text on line breaks but also on whitespace. The above example now produces 6 attributes for me (3xMD5, 3x filename) :)

I am reworking the e-mailing and will push the two together!

**Comment by iglocska** [comment]
Ticket number 300 is a bit trickier but also doable - the solution would be to simply throw away values that don't at least satisfy the filename requirements of "^.*\..*$" . Actually I'll do that anyway, let's see if we run into any issues with it!
