### ISSUE TITLE
Missing index on event_delegations

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#5023]
It would be nice to be able to list all the delegations awaiting a review. Also, opening that to the API.

**Comment by Rafiot** [comment]
There is a perm problem: an org admin in the receiving org gets a forbidden when trying to open https://localhost:8443/event_delegations

**Comment by iglocska** [comment]
That should have been fixed like ~3 hours ago in this:

https://github.com/MISP/MISP/commit/209c4903dd57e2ee248026b3ffefe774bbda3267
