### ISSUE TITLE
Updating cakephp

### ISSUE THREAD

**Issue by gitnorty** [MISP/MISP#5028]
Recently I noticed that our cakephp version was out of date.

I was following option 1 of https://github.com/MISP/MISP/blob/2.4/docs/UPDATE.md to get the latest MISP software.  Yet I don't see any cakephp files being updated?

Based on the udpate page, I can run 'git submodule update --init --recursive' to get cake up to date; but it doesn't appear to have worked.

[root@md2nj10ta MISP]# git submodule update --init --recursive
Submodule path 'INSTALL/dependencies/Console_CommandLine': checked out '40fca1d3dabbbb23e13b333bd5c615ca19d7d73f'
Submodule path 'INSTALL/dependencies/Crypt_GPG': checked out 'bf07ab51207446ed33ea0075083df9bbc2358617'
Submodule path 'INSTALL/dependencies/Net_GeoIP': checked out '5ccc654f03086febbec95e3358b7bae80ca9af6f'
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 630 (delta 236), reused 244 (delta 226), pack-reused 372
Receiving objects: 100% (630/630), 335.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (450/450), completed with 73 local objects.
From https://github.com/MISP/PyMISP
 * [new branch]      deprecate  -> origin/deprecate
 * [new branch]      lenientResponseType -> origin/lenientResponseType
   767859c..101ec5f  master     -> origin/master
From https://github.com/MISP/PyMISP
 * [new tag]         v2.4.111   -> v2.4.111
 * [new tag]         v2.4.111.1 -> v2.4.111.1
 * [new tag]         v2.4.111.2 -> v2.4.111.2
 * [new tag]         v2.4.112   -> v2.4.112
 * [new tag]         v2.4.113   -> v2.4.113
Fetching submodule pymisp/data/misp-objects
remote: Enumerating objects: 222, done.
remote: Counting objects: 100% (222/222), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 311 (delta 159), reused 199 (delta 145), pack-reused 89
Receiving objects: 100% (311/311), 77.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), completed with 27 local objects.
From https://github.com/MISP/misp-objects
   53e67b0..81c37af  master     -> origin/master
 * [new branch]      rommelfs-patch-4 -> origin/rommelfs-patch-4
 * [new branch]      rommelfs-patch-5 -> origin/rommelfs-patch-5
Submodule path 'PyMISP': checked out '101ec5f9ed6d6871b99e1cb0e27d04ebe14f5a44'
Submodule path 'PyMISP/pymisp/data/misp-objects': checked out '8c445fe1a42ec88bf5e990ffcc48153c433c43e4'
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 465 (delta 216), reused 213 (delta 203), pack-reused 235
Receiving objects: 100% (465/465), 749.62 KiB | 751.00 KiB/s, done.
Resolving deltas: 100% (323/323), completed with 25 local objects.
From https://github.com/MISP/misp-galaxy
   82ebbc6..8c85d0c  master     -> origin/master
 * [new branch]      travis_test -> origin/travis_test
Submodule path 'app/files/misp-galaxy': checked out '6ca4e4cb1790a56b00c9e9d5b764da1079662a0b'
remote: Enumerating objects: 222, done.
remote: Counting objects: 100% (222/222), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 311 (delta 159), reused 199 (delta 145), pack-reused 89
Receiving objects: 100% (311/311), 77.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), completed with 27 local objects.
From https://github.com/MISP/misp-objects
   53e67b0..81c37af  master     -> origin/master
 * [new branch]      rommelfs-patch-4 -> origin/rommelfs-patch-4
 * [new branch]      rommelfs-patch-5 -> origin/rommelfs-patch-5
Submodule path 'app/files/misp-objects': checked out '81c37aff51c91bb511c5f8ed2cccc025b6d68fcf'
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 202 (delta 76), reused 100 (delta 67), pack-reused 89
Receiving objects: 100% (202/202), 60.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), completed with 12 local objects.
From https://github.com/MISP/misp-taxonomies
 * [new branch]      climate    -> origin/climate
   3d2b8b1..51db2dc  master     -> origin/master
Submodule path 'app/files/taxonomies': checked out 'd5f37d3dc23c8acfe080e7ff04ca5979f3e64625'
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 77 (delta 37), reused 66 (delta 29), pack-reused 0
Unpacking objects: 100% (77/77), done.
From https://github.com/MISP/misp-warninglists
   4d8ce39..bc1bcce  master     -> origin/master
Submodule path 'app/files/warninglists': checked out '554360add3b90335ec2a058680ae48c4602df1e8'
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Total 228 (delta 157), reused 157 (delta 157), pack-reused 71
Receiving objects: 100% (228/228), 44.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (173/173), completed with 44 local objects.
From https://github.com/MISP/cti-python-stix2
   92c0582..b204b9f  master     -> origin/master
Submodule path 'cti-python-stix2': checked out 'b204b9fddafed1a9688449b27e300855046b30b4'

------
NOTE:  The cake version still shows as 2.10.16; whereas 3.8.2 is available...

[root@md2nj10ta MISP]# /var/www/MISP/app/Console/cake

Welcome to CakePHP v2.10.16 Console

[root@md2nj10ta MISP]# /var/www/MISP/app/Lib/cakephp/app/Console/cake

Welcome to CakePHP v2.10.16 Console

[root@md2nj10ta MISP]# /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/cake

Welcome to CakePHP v2.10.16 Console

Any help would be appreciated...

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question, support...
| OS version (server)       | RedHat 7.4
| OS version (client)       | N/A
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.113
| Browser                   | N/A

**Comment by iglocska** [comment]
That is correct. 3.x is not compatible with 2.x and needs a considerable rework of the code-base. We have the move planned in our roadmap but we're not there yet.

**Comment by gitnorty** [comment]
Thanks for the quick response!  Have a great day!
