### ISSUE TITLE
add value to the sources (information)

### ISSUE THREAD

**Issue by ost89** [MISP/MISP#503]
# functionality

In the situation when you have many sources of information, it would be nice to have the attribute "value" (relevance) of the source. Highest is 4, for example, and i give it to the source that works in the same sector as i am, lowest is 1 and i give it to the source that is almost publicly available information or has less relevance for me.

Another feature could be the certainty level. Information about malware infection that was found during your own investigation has certainty "high", for example. Information found online, without prove = "low"

**Comment by adulau** [comment]
Attribute level tagging and taxonomies like ```admiralty-scale```, ```misp``` or ```estimative-language``` is now available. So I assume this solves this issue. Don't hesitate to re-open the issue if this is not the case.
