### ISSUE TITLE
Link to MISP home page after blackholed

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#504]
When the login form has been open a long time the CSRF token expires and any login (good or bad) will fail with the message:

```	
The request has been black-holed

Error: The requested address '/users/login' was not found on this server.
```

This is pretty confusing for users since the current URL will be /users/login and a simple reload will fix the problem.
It would be less confusing if the error message would contain a "home" button that links to the baseurl of the MISP instance. This way a user can click on this button and continue.

**Comment by iglocska** [comment]
That sounds like a good idea! I'll try to put it in the package that I will push today.
