### ISSUE TITLE
Multiple merging issues

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5041]
v2.4.113 after a fresh _git pull_:

When trying to add a new `domain-ip` object with the IP already in another `domain-ip` object, merging is indeed proposed but the object is not updated with the new domain:

![domain_ip1](https://user-images.githubusercontent.com/25325656/63510034-de6cce80-c4dd-11e9-80b7-8a4c6d5b3c59.png)
![domain_ip2](https://user-images.githubusercontent.com/25325656/63510042-e167bf00-c4dd-11e9-9e9e-389af7f21f16.png)
![domain_ip3](https://user-images.githubusercontent.com/25325656/63510045-e3ca1900-c4dd-11e9-831f-79d57c00b702.png)

When trying to add a new `file` object with the filename already in another `file` object the file size gets not overwritten:

![file1](https://user-images.githubusercontent.com/25325656/63510055-e6c50980-c4dd-11e9-9d4f-fb47cfe152cc.png)
![file2](https://user-images.githubusercontent.com/25325656/63510060-e88ecd00-c4dd-11e9-843d-02c8b49b8a96.png)

**Comment by mokaddem** [comment]
Hi @StefanKelm, Thanks for trying out the merge object feature and reporting the bug!
The two issues you reported should be fixed in 38db050.
If it's not the case or if you spot other bugs, please feel free to open a new issue.
Thanks a lot!
