### ISSUE TITLE
Custom email sent (not logged)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#505]
If you sent a custom email from the MISP interface, this actions is not logged. It would be nice to have it in the audit log.

**Comment by iglocska** [comment]
You'll love the patch that I am finishing off today :) All e-mails are
logged, together with the result (success / fail) and the reason for the
failure.

**Comment by adulau** [comment]
Next time, we see each other, you'll get a pack of chocolate ;-)

**Comment by aaronkaplan** [comment]
On May 27, 2015, at 11:14 AM, Alexandre Dulaunoy <notifications@github.com> wrote:

> Next time, we see each other, you'll get a pack of chocolate ;-)
> 


this is now a cryptographically secured promise ;-)
