### ISSUE TITLE
Which DB systems are supported?

### ISSUE THREAD

**Issue by 8ear** [MISP/MISP#5058]
He Guys,

I know MariaDB in a new version is supported.

But what is with original MySQL? Oracle? MSSQL?
Are these supported or not?

For MySQL in specific do you use any special features from MariaDB?

Kind regards

**Comment by adulau** [comment]
MySQL and MariaDB are the supported database. We recommend to use at least version 5.7 of MySQL (we know some users even using older version). We don't use special features from MariaDB. So it's quite standard.

**Comment by 8ear** [comment]
Hi @adulau 
Thanks for your very fast answer.

Kind regards
