### ISSUE TITLE
Something's fucked up with statistics attributehistogram

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#5064]
call 1: => returns a list 
call 2: => returns a dict 

:man_shrugging:

**Comment by zaphodef** [comment]
Do you have an example we can reproduce? I only get a list...

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/commit/5916de9d5e07bf1907f8333a34c567322e537d65

**Comment by iglocska** [comment]
Fixed in the commit above, thanks!
