### ISSUE TITLE
Disable correlation from attributes does not work.

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#5070]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | 2.4.112

### Expected behavior
- When viewing a list of attributes from an event, it is possible to uncheck the box **correlate** next to an attribute to disable correlation.

### Actual behavior
- receiving an error message <<Something went wrong - the queried function returned an exception. Contact your administrator for further details (the exception has been logged)>>

### Steps to reproduce the behavior
- Create an event with attribute with correlation set to true.
- From the event view, try to uncheck the **correlate** checkbox.

**Comment by iglocska** [comment]
I cannot reproduce this, works fine over here.

**Comment by iglocska** [comment]
Could you try it with the latest version?
