### ISSUE TITLE
Upcoming changes to JSON vulnerability feeds

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5076]
No issue - just passing on this as general info. Not sure whether or not this is relevant here (or over at misp-objects or misp-modules) at all but there will be changes to NIST's JSON vulnerability feeds next month as described here:

https://nvd.nist.gov/General/News/JSON-1-1-Vulnerability-Feed-Release

If this is irrelevant just close this issue, please.  ;)

**Comment by adulau** [comment]
Indeed, we did some work in the field

https://github.com/cve-search/cve-search/commit/5e78f0a7d83229f18964f8920699e67f977aa1ea

If you are using cve-search, let me know if you find anything. I did some changes after this initial commit but it should work as expected.

**Comment by StefanKelm** [comment]
Interesting, thanks for the reply! I guess this one can be closed.
