### ISSUE TITLE
Warning list Question

### ISSUE THREAD

**Issue by ariddi7** [MISP/MISP#5077]
So i have a question relating to warning lists. Either i am being very stupid or this feature isn't available. 

Is there a way to add entries into the provided warning lists or create my own warning list? i would have thought this would be a feature already, but i cant seem to find anything even with the API. 

Thanks.

**Comment by iglocska** [comment]
There's indeed nothing in the API, but the warninglists are simple JSON
lists, so you can edit them, add your own, etc.

By default you'll find them here:

/var/www/MISP/app/files/warninglists/lists/[warninglist_name]/list.json

Simply create a new directory in ..warninglists/lists to and add your own
list.json.

After that just tell your MISP to read the JSON definitions (go to your
warninglist index and click on update lists).

**Comment by ariddi7** [comment]
Thank you! I should have thought of that.
