### ISSUE TITLE
"New user" choice under "contact users" has disappeared

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#508]
Under "contact users" in the admin panel, there used to be a choice to create a new user.
This possibility has dissappeared, and I can trace it back to commit 620b7d1adbba2a39f2a72ebbc01a9b9486a6ab0c. It is still documented in the documentation on the page, so I am unsure if it is a conscious choice, thus the documentation needs to be updated or if it is an accidental removal.

Test on a 2.3.71.

**Comment by iglocska** [comment]
It was a conscious choice to remove it (communicating with people that are not users of the instance), I didn't think anyone actually used that feature, would you like me to re-enable it?

**Comment by elhoim** [comment]
I just wanted a quicker way to create accounts than the *Administration*\*New User* screen but it can be slow, and I need to generate a password in a tool, copy/paste it to the MISP user account, and then copy/paste it in an email to the user. It can be quite slow...
I never used that functionality before, I just stumbled on it recently.

From what I gather, I could have used it to create a user-account in one go, and the pass would have been auto-generated and an email would be sent automatically?
If that's the case, then it would help lighten the load for account creation, so yes please.

**Comment by iglocska** [comment]
Ah I see. The previous new user button was simply a way to communicate with potential new users, it didn't generate any accounts (you simply entered a pgp key, e-mail address, body, subject and it sent an e-mail, that's it).

What you have instead now:

You create a new user with any password (which will never be sent to the user, so just use whatever).

Go to administration -> contact users -> Welcome message. It will regenerate a new password and send it to the user using the welcome message defined in the server settings. 

Or even quicker, once you create the account, you have a new button on the left when viewing it called "Send credentials". This allows you to send a new welcome message (same as above) with a newly generated password. 

Though it could be useful to streamline the process and just have a checkbox on user creation that overrides the password boxes (something like generate passwords and alert user on creation).

**Comment by Rafiot** [comment]
You can sent a reset password mail from the user page.
