### ISSUE TITLE
Community format changes

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#5082]
The Json file describe a community, so it doesn't make sense to call the key `community_name` or `community_uuid` and it should simply be `name` and `uuid`.

And it will be more consistent with the other types (objects for exmaple).

**Comment by Rafiot** [comment]
Especially the community_uuid a problem because the community is **only** accessible over the UUID (and not the ID), so the only way to get a specific community over the API is to explicitly pass the `community_uuid`

**Comment by iglocska** [comment]
That is not entirely true, the "id" passed via the url is captured as the
community uuid if the format is of type uuid.

**Comment by iglocska** [comment]
It is also accessible via the "id" (which depends on its position in the
list - starting from 1), which you can get by listing the communities via
/index

**Comment by Rafiot** [comment]
.... sure. But the ID, starting from 1, based on the order on the index, is totally useless from the API.
And I could start playing with the keys and search for UUID in every single key in the json objects, but again, not exactly useful.

Should I just rename `community_uuid` => `uuid` and call it a day?

**Comment by iglocska** [comment]
To reiterate what was discussed offline for posterity - the humanly
readable IDs are there for humans. All these endpoints are both for the web
UI and the API. Or alternate web UIs in tools that use the MISP API under
the hood.

**Comment by Rafiot** [comment]
:+1:
