### ISSUE TITLE
Clarify documentation for MISP.disablerestalert

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#511]
For the setting **MISP.disablerestalert** the description is *This setting controls whether notification e-mails will be sent when an event is created via the REST interface. It might be a good idea to disable this setting when first setting up a link to another instance to avoid spamming your users during the initial pull.*

Clarifying it with something like: "_False_ = Emails are sent when new events are created via the REST interface. _True_ = Emails are **not** sent when events are created via the REST interface. It might be a good idea to set this setting to _True_ when first setting up a link to another instance to avoid spamming your users during the initial pull."

**Comment by iglocska** [comment]
Fixed in d4b72bd0cc301b28248c8388fdaf65014b17b50b
