### ISSUE TITLE
Import large MISP import fails

### ISSUE THREAD

**Issue by angarod** [MISP/MISP#5118]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu Docker from HarvardITSecurity
| OS version (client)       | Win10
| PHP version               | 7.2.19
| MISP version / git hash   | 2.4.111
| Browser                   | Firefox

### Expected behavior
Export a large amount of data : 6G
Import the json in another MISP succesfully.

### Actual behavior
The import failed
The MISP log `An error has occured while attempting to access file "".`

**Comment by angarod** [comment]
Possibly linked to #1806

**Comment by mokaddem** [comment]
Hey @angarod 
What is your ``memory_limit`` (docker & php) ? I guess it could work if you try to increase it a bit.

**Comment by angarod** [comment]
`memory_limit` is `16384m` for php
No specific memory limitation for docker in my conf

**Comment by iglocska** [comment]
Is this using the massive full JSON export via the export page? That indeed can create JSON that is not that easily parse-able. You could split it into individual events and have a small python script that POSTs those one by one to MISP, but with a full export ranging hundreds of megs it won't work in one shot.

For transfers of that sort you have some other options:

1. MISP to MISP sync
2. Feed export tool
3. Custom glue script using the REST apis of MISP

**Comment by angarod** [comment]
`#!/bin/bash`
`for i in {1..500}`
`do`
          `curl --header "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXX" --header "Accept: application/xml" --header "Content-Type: application/xml" https://misp/events/xml/download/$i -k > $i.xml`
  ` done`
Did the trick for me.
Same method for posting events with the help of https://www.circl.lu/doc/misp/automation/

**Comment by mokaddem** [comment]
Thanks for getting back!

**Comment by iglocska** [comment]
Just one thing, that endpoint is horribly outdated and the XML format is deprecated, so not sure how accurate the information is. You could do this instead:

```
#!/bin/bash
for i in {1..500}
do
curl --header "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXX" https://misp/events/view/$i.json -k > $i.json
done
```

Or alternatively:

```
#!/bin/bash
for i in {1..500}
do
curl --header "Authorization: XXXXXXXXXXXXXXXXXXXXXXXXX" https://misp/events/restSearch/returnFormat:json/eventid:$i.json -k > $i.json
done
```
