### ISSUE TITLE
[dacaying ] Data Loss during import

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5124]
Hello,

When we import a json template, we lost all the element of the template, and have an useless template, we can't edit it anymore. 

> You are editing a Default Model, only restricted edition is allowed.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
|Type of issue | Bug,
OS version (server) | Debian 10
|OS version (client) | N/A
|PHP version | PHP 7.3.4-2
|MISP version / git hash | v2.4.114 (1d378fd)  (From mokaddem:decaying)
|Browser | N/A

### Expected behavior
Get the full json stored and integrated in MISP

> {
  "uuid": "073fae4a-2377-4cfa-bd34-2516830d33c3",
  "name": "NIDS Simple Decaying Model",
  "formula": "Polynomial",
  "ref": [
    "https://arxiv.org/abs/1902.03914",
    "https://arxiv.org/abs/1803.11052"
  ],
  "authors": [
    "MISP Project"
  ],
  "parameters": {
    "lifetime": 120,
    "decay_speed": 2,
    "threshold": 30,
    "default_base_score": 80,
    "base_score_config": {
      "estimative-language": 0.25,
      "priority-level": 0.25,
      "retention": 0.25,
      "targeted-threat-index": 0.125,
      "false-positive": 0.125
    }
  },
  "description": "Simple decaying model for Network Intrusion Detection System (NIDS). ",
  "attribute_types": [
    "domain",
    "domain|ip",
    "hostname",
    "hostname|port",
    "ip-dst",
    "ip-dst|port",
    "ip-src",
    "ip-src|port",
    "url",
    "snort",
    "suricata",
    "zeek",
    "bro"
  ],
  "version": 1
}

### Actual behavior
Only some data are stored.

> {
    "DecayingModel": {
        "uuid": null,
        "name": null,
        "parameters": null,
        "attribute_types": [],
        "description": null,
        "enabled": true,
        "all_orgs": true,
        "ref": null,
        "formula": "polynomial",
        "version": "",
        "default": true
    }
}`

### Steps to reproduce the behavior
import a json template from https://github.com/MISP/misp-decaying-models

**Comment by mokaddem** [comment]
Hey, thanks for trying out this new feature!
I updated the import process 3 days ago. For a fresh instance, it worked out of the box.
Could you wipe your sql table
```
DELETE FROM decaying_models WHERE 1=1;
```
and try the import again?

**Comment by FafnerKeyZee** [comment]
Yep it's working now ! (I did the test friday morning, updated this week-end but didn't tried it again)

And yes it's working out of the box ;-)

**Comment by mokaddem** [comment]
Thanks for the feedback!
