### ISSUE TITLE
Sync connexion test

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5126]
Hello,

I dunno if it is a bug/feature or a misunderstanding, but when I try to sync my instance with an other instance, I got the  following result:

Local version: 2.4.114
Remote version: 2.4.115
Status: Local instance outdated, update!
Compatiblity: Compatible
POST test: Invalid body

What is expected for : POST test result ?

BR,

**Comment by iglocska** [comment]
It should be fixed now. Over-protective ACL tightening ;)
