### ISSUE TITLE
Column not found `Server.caching_enabled`

### ISSUE THREAD

**Issue by dynek** [MISP/MISP#5127]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 
| OS version (client)       | Mac OS
| PHP version               | 7.1
| MISP version / git hash   | 2.4.115 (6e78bb654fe0c32109f015afe698b62b73731760) 
| Browser                   | N/A

### Expected behavior

Display event details.

### Actual behavior

Error 500 - An Internal Error Has Occurred.

### Steps to reproduce the behavior

Login and click on an event's ID.

### Logs, screenshots, configuration dump, ...

```
2019-09-09 14:34:28 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Server.caching_enabled' in 'field list'
Request URL: /events/view/7443
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Server`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Server`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Server`...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Server), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Feed.php(337): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Event.php(2152): Feed->attachFeedCorrelations(Array, Array, Array, false, 'Server')
#8 /var/www/MISP/app/Controller/EventsController.php(1576): Event->fetchEvent(Array, Array)
#9 [internal function]: EventsController->view('7443')
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

I'm only maintaining the server running the application so I don't know for how long this has been broken:
- I have done cleanup tasks
- updated the OS & the application
- checked update logs for failures to update DB
- ran tasks available in admin > diagnostics (e.g. clean cache, reconstruct overwritten objects, ...)
but I'm still seeing the problem.

Google doesn't help, Github doesn't help. I can't see to understand where this Server.caching_enabled field is coming from.

Any help will be appreciated ;-)

Thank you

**Comment by dynek** [comment]
Erm, altering table "Servers" fixes it (next problem being Taxonomy.required), weird.

Is there some DB schema integrity check?

**Comment by SteveClement** [comment]
@dynek there is no integrity check after the updates are performed.
There were quite a few issues like that without clear-cut path to a working solution. (well telling MISP it was out of date and re-running the update sometime worked, but I feel that is dangerous)

Thus your issue is one of those "not really sure what goes on here" issues.

Sorry I could not help more.

**Comment by iglocska** [comment]
There is, as of now there's a tool that compares your db schema to the
expected schema. Look for it under diagnostics.

**Comment by dynek** [comment]
I finally took time to check it @iglocska and you are right!
Am fixing the differences as I send this comment.
Thank you!
