### ISSUE TITLE
Redis Connect Failed

### ISSUE THREAD

**Issue by holidayz1** [MISP/MISP#5138]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu 18.04.3
| PHP version               | 7.2.19
| MISP version / git hash   |  v2.4.115 (6e78bb654fe0c32109f015afe698b62b73731760) 

### Expected behavior

Fresh Install 

### Actual behavior

 Jobs for pulling default feeds fail 

### Steps to reproduce the behavior
Fresh Install on  Ubuntu 18.04.3
Downgrade  to monolog=1.24.0

### Logs, screenshots, configuration dump, ...
~~~
2019-09-10 11:58:01 *Warning: Redis::connect(): connect() failed: Connection refused in [/var/www/MISP/app/Model/AppModel.php, line 1793]*
2019-09-10 11:58:01 Error: Could not get freetext feed 44
[Exception] Could not reach Redis.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(801): Feed->getFreetextFeed(Array, Object(HttpSocket), 'freetext', 'all')
#1 /var/www/MISP/app/Console/Command/ServerShell.php(170): Feed->downloadFromFeedInitiator('44', Array, '345')
#2 /var/www/MISP/app/Console/Command/AppShell.php(32): ServerShell->fetchFeed()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#8 {main}
~~~

**Comment by holidayz1** [comment]
also 
~~~ 
sudo ufw status
Status: inactive
~~~

**Comment by holidayz1** [comment]
Redis is running

~~~
ps -aux | grep redis
redis       845  0.1  0.2  50152  4668 ?        Ssl  11:03   0:15 /usr/bin/redis-server 127.0.0.1:6379
www-data    907  0.0  0.1  50152  3220 ?        Ssl  11:03   0:09 redis-server 127.0.0.1:6250

~~~

**Comment by holidayz1** [comment]
~~~
#  redis-cli
127.0.0.1:6379>
~~~

**Comment by iglocska** [comment]
Did you by chance modify any of the settings in MISP in regards to your redis config?

MISP.redis_host, MISP.redis_port, MISP.redis_database, MISP.redis_password are the 4 settings that might affect this.

**Comment by holidayz1** [comment]
Nope,i did not changed anything

**Comment by holidayz1** [comment]
I am able to pull CIRCL and MalwareMustDie feeds , but fail to pull any other with the Earlier mentioned error

**Comment by holidayz1** [comment]
adjusting MISP.redis_host, MISP.redis_port, MISP.redis_database, MISP.redis_password fixed it thanks

**Comment by dragonyy** [comment]
@holidayz1 Can you paste how you adjust your 4 configurations? I encounter a problem which is very like yours.

> 2019-10-01 14:52:13 Warning: count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Console/Command/AdminShell.php, line 166]
2019-10-01 14:56:07 Warning: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]

And mine is the installer gave:

> config.php:    'redis_host' => '127.0.0.1',
config.php:    'redis_port' => 6379,
config.php:    'redis_database' => 13,
config.php:    'redis_password' => '',
config.php:    'ZeroMQ_redis_host' => 'localhost',
config.php:    'ZeroMQ_redis_port' => 6379,
config.php:    'ZeroMQ_redis_database' => '1',
config.php:    'ZeroMQ_redis_namespace' => 'mispq',
