### ISSUE TITLE
mispzmq doesn't start

### ISSUE THREAD

**Issue by 1earch** [MISP/MISP#5140]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Not applicable
| PHP version               | 7.2
| MISP version / git hash   | 2.4.115, ddeb9af29ee61b5a3fcb6791de534d3f348952dc

### Expected behavior
After a fresh install, `mispzmq` starts

### Actual behavior
After a fresh install, `mispzmq` doesn't start

### Steps to reproduce the behavior
1. Fresh install MISP
2. Go to "server settings & maintenance" > "diagnostics"
3. ZeroMQ section indicates that `mispzmq` isn't running

### Logs
In `/var/www/MISP/app/tmp/logs/mispzmq.error.log`:
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
```

### Fix
If you already installed MISP using `install.sh`, you can:
```
sudo -H -u www-data /var/www/MISP/venv/bin/pip install redis
```

**Comment by 1earch** [comment]
To fix this error permanently, the install script must be modified, but I don't know which modification must be performed, as this script is autogenerated.

The line [1314 of the final install file](https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sh#L1314) must be modified to:
```
 # install zmq & redis needed by mispzmq
 $SUDO_WWW ${PATH_TO_MISP}/venv/bin/pip install zmq redis
```

**Comment by SteveClement** [comment]
fixed
