### ISSUE TITLE
MISP install on ubuntu server

### ISSUE THREAD

**Issue by lemmou** [MISP/MISP#5151]
I installed MISP following the script mentioned here in https://misp.github.io/MISP/INSTALL.ubuntu1804/
the problem is that after login or actualization of the page i have on my firefox Unable to connect. The link after login is https://localhost:8443/users/login.
The same thing if i was connected from another machine to this server or i clicked on the home link in misp

thx

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by l3m0ntr33** [comment]
Try to modify 'baseurl' with the IP or hostname of your server in the following file :
/var/www/MISP/app/Config/config.php

**Comment by lemmou** [comment]
ok , i will test it 
Thx

**Comment by lemmou** [comment]
I repeated the installation of misp. At the end it worked correctly.
Changing the network setting of my vbox from NAT to host only adapter, the problem occurred.
Despite that i did your proposition, it didn't work i have the same thing as previously

**Comment by lemmou** [comment]
your solution works without the 8443 in the baseline
