### ISSUE TITLE
debug: Notice/Error when accessing to diagnostic page

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5156]
Hello,

When accessing to diagnostic page, it takes few dozen of seconds to open the page. In the debug.log I got the following message:

> 2019-09-13 10:33:08 Notice: Notice (8): Undefined index: count in [/var/www/MISP/app/Lib/cakephp/lib/Cake/View/Helper/PaginatorHelper.php, line 696]
> Trace:
> ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
> PaginatorHelper::counter() - APP/Lib/cakephp/lib/Cake/View/Helper/PaginatorHelper.php, line 696
> include - APP/View/Elements/genericElements/IndexTable/pagination_counter.ctp, line 5
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
> View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
> include - APP/View/Elements/genericElements/IndexTable/index_table.ctp, line 61
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
> View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
> include - APP/View/Elements/healthElements/diagnostics.ctp, line 223
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::_renderElement() - APP/Lib/cakephp/lib/Cake/View/View.php, line 1224
> View::element() - APP/Lib/cakephp/lib/Cake/View/View.php, line 418
> include - APP/View/Servers/server_settings.ctp, line 11
> View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
> View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
> View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
> Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
> Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
> Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
> [main] - APP/webroot/index.php, line 92

Best regards,

**Comment by iglocska** [comment]
Two separate things:
1. The delay is due to MISP checking github for the latest version
2. The notice errors are annoying but harmless, @mokaddem said he already has a fix ready so once he pushes it it should be gone.

**Comment by FafnerKeyZee** [comment]
Oh ok, I found it "by chance" while checking by log during my investagation about my worker :p

**Comment by iglocska** [comment]
Hehe, I have debug enabled, as such I have the pleasure of reading those darn notice errors each time I go to the diagnostic page ;)

**Comment by SteveClement** [comment]
Can this be closed? @mokaddem @iglocska

**Comment by iglocska** [comment]
Yep, resolved a while ago.
