### ISSUE TITLE
Sorting by date is broken when searching

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#5157]
The sorting by date is not working as expected when searching attributes.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.115

### Expected behavior

Search results are sorted by date.

### Actual behavior

Search results are not sorted by date.

### Steps to reproduce the behavior

1. Go to /attributes/search
2. Select an attribute type to search for
3. Click on date

**Comment by iglocska** [comment]
Fixed in https://github.com/MISP/MISP/commit/76b1b05a9ead48540596cfc10a6ce726bbcae344
