### ISSUE TITLE
PHP Fatal error:  Call to undefined method Redis::sAddArray()

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#5160]
After git pulling to 2.4.15  (git commit id: 1c9283f846f9c20de4ca89edc1d8193c2733fdfa )
I am seeing the following error message in /var/log/apache2/error.log whenever viewing an event.

```
[Sun Sep 15 10:23:48.972377 2019] [:error] [pid 26198] [client 172.21.48.50:59970] PHP Fatal error:  Call to undefined method Redis::sAddArray() in /home/aaron/MISP/app/Model/Warninglist.php on line 195, referer: https://misp.cert.at/events/index
```

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian jessie
| OS version (client)       | OS X
| PHP version               | 5.6.40+dfsg-0+deb8u5 
| MISP version / git hash   | 2.4.15, 1c9283f846f9c20de4ca89edc1d8193c2733fdfa
| Browser                   | doesnt matter

### Expected behavior

I should see events

### Actual behavior

A page "Error: An Internal Error Has Occurred." appears

### Steps to reproduce the behavior

click on any event

**Comment by JakubOnderka** [comment]
Hi @aaronkaplan. This was changed in commit https://github.com/MISP/MISP/commit/4d666092623a5368a0e1344bbf9d01cf21f499de. `sAddArray` method was added in phpredis 2.2.8 that was released in 2016 so I thought it is old enough and at that time I didnt know that [MISP team still support PHP5](https://github.com/MISP/MISP/pull/5105#issuecomment-530220883). So I will revert the change back.

**Comment by iglocska** [comment]
Reverted for now in a quick fix. Ideally we should just check for the existence of sAddArray() and use that if possible.

**Comment by iglocska** [comment]
> Hi @aaronkaplan. This was changed in commit [4d66609](https://github.com/MISP/MISP/commit/4d666092623a5368a0e1344bbf9d01cf21f499de). `sAddArray` method was added in phpredis 2.2.8 that was released in 2016 so I thought it is old enough and at that time I didnt know that [MISP team still support PHP5](https://github.com/MISP/MISP/pull/5105#issuecomment-530220883). So I will revert the change back.

Supporting it is a stretch, officially we haven't supported 5.6 for about a year, but reality always bites us in the arse so we still make it work. Only until the end of the year though, then we break compatibility with old versions for good.

**Comment by aaronkaplan** [comment]
yup, all fine on my side again - upgraded to php7.3  (which brought other issues) but hey, it's working again. Sorry for the noise.

**Comment by iglocska** [comment]
No worries, also it should now work with both 5.6 via the old slow method
and 7.0+ via the modern call.
