### ISSUE TITLE
Unable to run instalation Script on Ubuntu 19.04

### ISSUE THREAD

**Issue by CLD87** [MISP/MISP#5167]
I'm trying to run the script for installing MISP with all the components on UBUNTU SERVER 19.04 but I get the follwing error:

============

 Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/
root@MISP:~# uname -a

=================

uname -a
Linux MISP 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       |Ubuntu 19.04
| OS version (client)       | Linux Mint (Ubuntu 16.04)
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | latest
| Browser                   | If applicable

### Expected behavior

Install MISP

### Actual behavior

![Screenshot at 2019-09-16 15:32:33](https://user-images.githubusercontent.com/47886565/64958338-8e441a80-d897-11e9-861c-4be09dc9bbe7.png)

### Steps to reproduce the behavior
Just run the installer

**Comment by SteveClement** [comment]
Dear

That is a feature, not a bug ;)

We test and support 18.04 at the moment. (Only)
If you need/want 19.04/19.10 do a manual install.

But as far as I see, 19.04 should at least try to install.

I will check later.

**Comment by shilpajuet** [comment]
hi All, 

I am also not able to run the script on :

Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie
 and it throwing same error mentioned above. However, when I am trying to directly install the script it is showing : File or directory not found.

Please help me out in resolving this . 

BR,
