### ISSUE TITLE
Login Screen - The request has been black-holed

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#5168]
I get this error whenever I try to log in after it's been sitting for a while.

> **The request has been black-holed**
> Error: The requested address '/users/login' was not found on this server.

The logs show a 404.  If I refresh and submit again, it works fine.  If this is a CSRF token issue, maybe it should not be used on the login or perhaps grab a new token.  IDK, but it's annoying as heck.

**Comment by blabut** [comment]
Hi, do you have any updates on this ? I am running into this bug and couldn't find any work around. Thanks !

**Comment by adulau** [comment]
Check if your base url is properly setup.

**Comment by imidoriya** [comment]
@adulau My baseurl and external_baseurl are pointing to the correct host/domain.  I ended up changing the session timeout to a much longer value to try and avoid it, but never got it fixed.

**Comment by mokaddem** [comment]
The issue is caused because the token generated for the login form expired. Simply reloading the page if it `has been sitting there for a while` would solve the issue.
We could also regenerate the token every once in a while

**Comment by imidoriya** [comment]
If a token is expired, it should redirect back to the logon page, not a blackhole page.  And yes, it would probably make sense to add a meta tag on the logon page so the token doesn't get stale.

`<meta http-equiv="refresh" content="300">`

This would refresh the logon page every 5 minutes for example.

**Comment by mokaddem** [comment]
PR #6161 should fix the issue
