### ISSUE TITLE
Tags now shows Global symbol without tags content

### ISSUE THREAD

**Issue by hmnguyen1201** [MISP/MISP#5170]
Hi,

I wouldn't call this is an issue necessarily but more than a question for the community to confirm my thoughts. Looks like after version 2.4.110 the tags don't show the writings anymore but shows the global symbol for global tags instead now.

Is there away I can enable it to show the tags contents instead of just the global symbol? 

My current version is 24.112

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Centos
| OS version (client)       | CENTOS
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.112

| Browser                   | If applicable

### Expected behavior
<img width="237" alt="Screen Shot 2019-09-16 at 2 19 44 PM" src="https://user-images.githubusercontent.com/55410007/64986848-81222e00-d88d-11e9-840b-c29288be4a1f.png">

### Actual behavior
![Screen Shot 2019-09-16 at 2 19 38 PM](https://user-images.githubusercontent.com/55410007/64986864-8a12ff80-d88d-11e9-82f8-fce0fa94206a.png)

**Comment by iglocska** [comment]
Hello, yes the default for the tag display erroneously defaulted to this in 112, please update your misp.
