### ISSUE TITLE
Race condition in checkIfLoggedIn causes relogin

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#5172]
9f8e22e96ce27a472e8f8372b82fef377238ff44 introduced a redirect to `/users/login` when the jQuery get of `/users/checkIfLoggedIn.json` fails. This causes a race condition when a user clicks on a link in MISP at the same time the jQuery get call is made. What happens is:

1. jQuery call to `/users/checkIfLoggedIn.json` is made
1. User clicks on link in MISP at nearly the same time
1. `$.get()` is cancelled and `.fail()` is called
1. Browser gets redirected to `/users/login` instead of MISP link that was clicked on

This is driving our users nuts as it randomly cancels whatever they were doing. It is especially nasty when in the middle on an event edit. 

Is the .fail() redirect really needed to fix #4678 ? Setting `MISP.disable_auto_logout` also fixed that issue.

The logs below show the race condition. This user uses SSL client certificate authentication so a redir to `/users/login` simply redirects to `/users/routeafterlogin` and `/` in the end.

```
10.0.0.1 - - [17/Sep/2019:09:33:52 +0200] "GET /events/checkLocks/28003 HTTP/1.1" 200 - "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:53 +0200] "GET /users/checkIfLoggedIn.json HTTP/1.1" 200 2 "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:57 +0200] "GET /events/checkLocks/28003 HTTP/1.1" 200 - "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:58 +0200] "GET /events/edit/28003 HTTP/1.1" 200 20432 "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:58 +0200] "GET /users/login HTTP/1.1" 302 - "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:59 +0200] "GET /users/routeafterlogin HTTP/1.1" 302 - "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
10.0.0.1 - - [17/Sep/2019:09:33:59 +0200] "GET / HTTP/1.1" 200 762132 "https://misp.local/events/view/28003" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

**Comment by iglocska** [comment]
ah ok, so the fail is executed even if it's interrupted. OK I see. That should indeed be fixed.
