### ISSUE TITLE
[BUG] Server setting is not accessible after a fresh install (MissingTableException] Table tag_collections for model TagCollection was not found)

### ISSUE THREAD

**Issue by Firzum** [MISP/MISP#5180]
## OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
Linux lug 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## MISP:
{"major":2, "minor":4, "hotfix":116}
commit 65121816d527ae68fac2a47391f8f63989564e0d

## PHP and apache
ii  php-apcu              5.1.9+4.0.11-1build1                       amd64        APC User Cache for PHP
ii  php-apcu-bc           1.0.3-2ubuntu2                             amd64        APCu Backwards Compatibility Module
ii  php-cgi               1:7.2+60ubuntu1                            all          server-side, HTML-embedded scripting language (CGI binary) (default)
ii  php-cli               1:7.2+60ubuntu1                            all          command-line interpreter for the PHP scripting language (default)
ii  php-common            1:60ubuntu1                                all          Common files for PHP packages
ii  php-curl              1:7.2+60ubuntu1                            all          CURL module for PHP [default]
ii  php-dev               1:7.2+60ubuntu1                            all          Files for PHP module development (default)
ii  php-fpm               1:7.2+60ubuntu1                            all          server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
ii  php-gd                1:7.2+60ubuntu1                            all          GD module for PHP [default]
ii  php-gettext           1.0.12-0.1                                 all          transitional dummy package for php-php-gettext
ii  php-igbinary          2.0.5-1build1                              amd64        igbinary PHP serializer
ii  php-imagick           3.4.3~rc2-2ubuntu4                         amd64        Provides a wrapper to the ImageMagick library
ii  php-intl              1:7.2+60ubuntu1                            all          Internationalisation module for PHP [default]
ii  php-mbstring          1:7.2+60ubuntu1                            all          MBSTRING module for PHP [default]
ii  php-memcache          3.0.9~20160311.4991c2f-5build2             amd64        memcache extension module for PHP
ii  php-mysql             1:7.2+60ubuntu1                            all          MySQL module for PHP [default]
ii  php-pear              1:1.10.5+submodules+notgz-1ubuntu1.18.04.1 all          PEAR Base System
ii  php-php-gettext       1.0.12-0.1                                 all          read gettext MO files directly, without requiring anything other than PHP
ii  php-pspell            1:7.2+60ubuntu1                            all          pspell module for PHP [default]
ii  php-recode            1:7.2+60ubuntu1                            all          recode module for PHP [default]
ii  php-redis             3.1.6-1build1                              amd64        PHP extension for interfacing with Redis
ii  php-sqlite3           1:7.2+60ubuntu1                            all          SQLite3 module for PHP [default]
ii  php-tidy              1:7.2+60ubuntu1                            all          tidy module for PHP [default]
ii  php-xmlrpc            1:7.2+60ubuntu1                            all          XMLRPC-EPI module for PHP [default]
ii  php-zip               1:7.2+60ubuntu1                            all          Zip module for PHP [default]
ii  php7.2                7.2.19-0ubuntu0.18.04.2                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.2-cgi            7.2.19-0ubuntu0.18.04.2                    amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php7.2-cli            7.2.19-0ubuntu0.18.04.2                    amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common         7.2.19-0ubuntu0.18.04.2                    amd64        documentation, examples and common module for PHP
ii  php7.2-curl           7.2.19-0ubuntu0.18.04.2                    amd64        CURL module for PHP
ii  php7.2-dev            7.2.19-0ubuntu0.18.04.2                    amd64        Files for PHP7.2 module development
ii  php7.2-fpm            7.2.19-0ubuntu0.18.04.2                    amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.2-gd             7.2.19-0ubuntu0.18.04.2                    amd64        GD module for PHP
ii  php7.2-intl           7.2.19-0ubuntu0.18.04.2                    amd64        Internationalisation module for PHP
ii  php7.2-json           7.2.19-0ubuntu0.18.04.2                    amd64        JSON module for PHP
ii  php7.2-mbstring       7.2.19-0ubuntu0.18.04.2                    amd64        MBSTRING module for PHP
ii  php7.2-mysql          7.2.19-0ubuntu0.18.04.2                    amd64        MySQL module for PHP
ii  php7.2-opcache        7.2.19-0ubuntu0.18.04.2                    amd64        Zend OpCache module for PHP
ii  php7.2-pspell         7.2.19-0ubuntu0.18.04.2                    amd64        pspell module for PHP
ii  php7.2-readline       7.2.19-0ubuntu0.18.04.2                    amd64        readline module for PHP
ii  php7.2-recode         7.2.19-0ubuntu0.18.04.2                    amd64        recode module for PHP
ii  php7.2-sqlite3        7.2.19-0ubuntu0.18.04.2                    amd64        SQLite3 module for PHP
ii  php7.2-tidy           7.2.19-0ubuntu0.18.04.2                    amd64        tidy module for PHP
ii  php7.2-xml            7.2.19-0ubuntu0.18.04.2                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-xmlrpc         7.2.19-0ubuntu0.18.04.2                    amd64        XMLRPC-EPI module for PHP
ii  php7.2-zip            7.2.19-0ubuntu0.18.04.2                    amd64        Zip module for PHP
ii  pkg-php-tools         1.35ubuntu1 
ii  apache2                         2.4.29-1ubuntu4.11      amd64        Apache HTTP Server
ii  apache2-bin                     2.4.29-1ubuntu4.11      amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                    2.4.29-1ubuntu4.11      all          Apache HTTP Server (common files)
ii  apache2-doc                     2.4.29-1ubuntu4.11      all          Apache HTTP Server (on-site documentation)
ii  apache2-suexec-pristine         2.4.29-1ubuntu4.11      amd64        Apache HTTP Server standard suexec program for mod_suexec
ii  apache2-utils                   2.4.29-1ubuntu4.11      amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-fcgid            1:2.3.9-1               amd64        FastCGI interface module for Apache 2
ii  libapache2-mod-php              1:7.2+60ubuntu1         all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
ii  libapache2-mod-php7.2           7.2.19-0ubuntu0.18.04.2 amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-security2        2.9.2-1                 amd64        Tighten web applications security for Apache

## Browser:
Firefox 69 windows 10

### Expected behavior
To have a live MISP

### Actual behavior
Fresh install on a fresh server (only TheHive has been installed before), when I go to MISP it looks functional excepted this message: "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live). An update might also be in progress, you can see the progress in Update Progress"
But when I try to go to the server settings page I have a 500 Internal error.

### Steps to reproduce the behavior
Install on a fresh server, login on front end

### Logs, screenshots, configuration dump, ...
I have attempted to uninstall (DB and files removal) without being able to make a difference.

The error message from logs:
I found this error has been recorded in the log file "/var/www/MISP/app/tmp/logs/error.log

2019-02-03 22:55:12 Error: [MissingTableException] Table tag_collections for model TagCollection was not found in datasource default.
Exception Attributes: array (
'table' => 'tag_collections',
'class' => 'TagCollection',
'ds' => 'default',
)
Request URL: /servers/serverSettings

I have checked the database:

MariaDB [misp]> select value from admin_settings where setting = 'db_version';
+-------+
| value |
+-------+
| 38 |
+-------+
1 row in set (0.00 sec)

MariaDB [misp]> describe tag_collections;
+-------------+--------------+------+-----+---------+----------------+
| Field | Type | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+----------------+
| id | int(11) | NO | PRI | NULL | auto_increment |
| uuid | varchar(40) | YES | MUL | NULL | |
| user_id | int(11) | NO | MUL | NULL | |
| org_id | int(11) | NO | MUL | NULL | |
| name | varchar(255) | NO | | NULL | |
| description | text | NO | | NULL | |
| all_orgs | tinyint(1) | NO | | 0 | |
+-------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)

I gave a try to all solutions in #4658 without success

Any kind of help is welcome.

Thanks in advance.

Regards

**Comment by iglocska** [comment]
Could you go to your audit logs in misp, click on the updates tab and paste the entries you see there?

**Comment by Firzum** [comment]
I have no update tab:
![image](https://user-images.githubusercontent.com/4751946/65114180-1801fe00-d9e6-11e9-950d-4b73bb0566ac.png)

Here is the database update informations:
![image](https://user-images.githubusercontent.com/4751946/65114055-af1a8600-d9e5-11e9-8bee-848ad4229ebe.png)

**Comment by Firzum** [comment]
I seems that running update_thirdparty.sh from the app folder has fixed this issue.
