### ISSUE TITLE
MISP uses the wrong python version for detecting lief

### ISSUE THREAD

**Issue by crackytsi** [MISP/MISP#5183]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug or Question
| OS version (server)       | RHEL
| OS version (client)       | Seven
| PHP version               | 7.2
| MISP version / git hash   | 2.4.116

### Expected behavior
Instead of using the python3.6 version where /usr/bin/python3 points to, MISP uses the python3.4 version and tries to detect lief.
Is there a detection error?
How does the python version detection works and how can I change that?

Thanks a lot for any idear/help ;)

**Comment by SteveClement** [comment]
How/where do see that?

Also, RHEL... afaik you compile LIEF by hand and during the compilation you point it to the python binary.

**Comment by Rafiot** [comment]
Lief isn't compatible with legacy python (anything older than python 3.5), and the newer version requires 3.6+.

You can change the path to the python interpreter in the MISP settings. Note that it  may require you to compile Python, and, as @SteveClement says, lief.
