### ISSUE TITLE
Ubuntu 18.04 with py2neo installing conflict error

### ISSUE THREAD

**Issue by dragonyy** [MISP/MISP#5191]
On Ubuntu 18.04, totally new installed version of OS
Install step: 
bash INSTALL.sh -c -M
(core and modules)

Error Message:

> Collecting decorator>=3.4.0 (from validators->pymisp==2.4.114)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt_toolkit~=2.0.7->py2neo->pymisp==2.4.114)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Building wheels for collected packages: py2neo, validators, neobolt, neotime
  Building wheel for py2neo (setup.py) ... done
  Created wheel for py2neo: filename=py2neo-4.3.0-py2.py3-none-any.whl size=88307 sha256=adeae4aff553925c0b8865aea8cf3d24b6337e1ceaa7b9adc41eb7ecd765b70a
  Stored in directory: /var/www/.cache/pip/wheels/86/7d/e3/35bd456d80e796ba1f98730b629352ebab5294c942e8fdd826
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.14.0-cp36-none-any.whl size=17076 sha256=74152977d7ea3c202503dc393a798a326f3642910712b93c275123fca0e3120e
  Stored in directory: /var/www/.cache/pip/wheels/52/ad/d4/c5ddfd117381a9c46fdc4a1d15eb688a81e6e821f5c69d9056
  Building wheel for neobolt (setup.py) ... done
  Created wheel for neobolt: filename=neobolt-1.7.13-cp36-cp36m-linux_x86_64.whl size=517069 sha256=b0385b32b33e2e1f0c949779766ae48202046dbbc7185bcee9cdf48797cc6b1d
  Stored in directory: /var/www/.cache/pip/wheels/53/66/08/88253cffcc2a51a0adc022795487b68e013560fe2fd73352ae
  Building wheel for neotime (setup.py) ... done
  Created wheel for neotime: filename=neotime-1.7.4-cp36-none-any.whl size=20544 sha256=f3be99f6fada02158d600687249c4b02bfd915c5d405134404c7fe0b3786d3aa
  Stored in directory: /var/www/.cache/pip/wheels/d4/b4/c4/ab867cd0ac9e667f8cd269f9364fd1cb8ee75fe50f5ce97c79
Successfully built py2neo validators neobolt neotime
ERROR: py2neo 4.3.0 has requirement urllib3<1.25,>=1.23, but you'll have urllib3 1.25.3 which is incompatible.
Installing collected packages: lief, neobolt, neotime, wcwidth, prompt-toolkit, pygments, py2neo, decorator, validators, pymisp

In short, py2neo conflicts with urllib3!

I investigated this for previous version of installer, and manually copy/modify REQUIREMENTS or setup.py (like limit the urllib3 version in the previous step of Python library install) to avoid this issue. However, with the newest version released, the problem still exists. 

Since this error appeared in the relatively late phase of processing, I guess it comes from misp-modules installation. I don't know whether this will affect the normal operation of misp-modules, but I hope this 3rd party library conflict could be solved.

Further, there's an syntax error like this

> Cloning into '/var/www/MISP/PyMISP/tests/viper-test-files'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 110 (delta 0), reused 4 (delta 0), pack-reused 105
Receiving objects: 100% (110/110), 15.18 MiB | 696.00 KiB/s, done.
Resolving deltas: 100% (23/23), done.
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 39, in <module>
    from keys import url, key
  File "/var/www/MISP/PyMISP/tests/keys.py", line 1
    url = https://localhost:8443
               ^
SyntaxError: invalid syntax

It's strange that I didn't do anything about viper. And since the filename suggests it's related to "test", so I mention this just for your information only.

**Comment by SteveClement** [comment]
Thanks, for that, it should be fixed by now.
