### ISSUE TITLE
MISP Disable Correlation Limit not working

### ISSUE THREAD

**Issue by b00lpy** [MISP/MISP#5195]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| PHP version               | 7.1
| MISP version / git hash   | 2.4.114

I'm performing a very big insertion of events from an old db of alarms into misp, this was for have a little of correlation, but it's "exploding".  
I set limit to 1k into the setting `MISP.max_correlations_per_event` MISP Settings but it doesn't work.  

My correlation events are going on ignoring that.  

![image](https://user-images.githubusercontent.com/50588190/65315786-fc8b2480-db98-11e9-8936-0365fa6f2f74.png)

![image](https://user-images.githubusercontent.com/50588190/65315847-1f1d3d80-db99-11e9-8f16-1970144daef3.png)

**Comment by iglocska** [comment]
max_correlations_per_event does not affect the number of correlations saved, merely what is retrieved on an event view. It should prevent us from running into crazy memory caps when viewing overtly correlating events.
