### ISSUE TITLE
fatal: destination path '/var/www/MISP/PyMISP/tests/viper-test-files' already exists and is not an empty directory

### ISSUE THREAD

**Issue by FrazHackz** [MISP/MISP#5209]
I am installing MISP to download misp dataset for opencti, but while installation i'm getting error in destination path (server link to access misp data).

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue            | support
| OS version (client)    | Ubuntu
| PHP version              | 7.1...
| MISP version / git hash   | 2.4.XX, 
| Browser                   | Google

### Expected behavior
Server will run and i can access data
``
### Actual behavior
server is not working.

### Logs, screenshots, configuration dump, ...
![Screenshot from 2019-09-23 21-43-34](https://user-images.githubusercontent.com/44872960/65450710-338e5e00-de57-11e9-8a10-200205d7db61.png)

**Comment by Yuvraj-Takey** [comment]
I am also facing same issue, anyone got solution ?

**Comment by Rafiot** [comment]
It's not important and you can keep going with the installation. I'll look at the installation guide nad fix that.

**Comment by Rafiot** [comment]
In theory, that should fix both issues you have here.

@SteveClement can you regenerate the install script, please?

**Comment by SteveClement** [comment]
> In theory, that should fix both issues you have here.
> 
> @SteveClement can you regenerate the install script, please?

done.
