### ISSUE TITLE
Log message and gpg error

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#521]
The mail logging feature is great and helps a lot to debug any issue. Here is a specific one.

Not sure if the log message is truncated but we have one case for a specific key where it's always the following error while sending a notification

"the message could not be encrypted because there was an issue with the user's PGP key. The following error message was returned by gpg: Unknown error e"

I tried to import and use the key directly with GnuPG and this works.

**Comment by iglocska** [comment]
Wow, that is weird! Looking into it.

**Comment by iglocska** [comment]
Ah I see, the title field is capped at 255 chars by default, I'll write a script to increase it.

**Comment by iglocska** [comment]
Opened the issue again as this only allows you to view the actual error message, we still don't know what's wrong with the PGP key.

Could you run the upgrade script found in Administration -> Administrative Tools -> Convert log fields to text ? This should allow you to capture longer error messages, just try to e-mail the troublesome user again and let's see if anything interesting shows up in the logs after.

**Comment by adulau** [comment]
Thank you very much for the hotfix. I'll check the logs with the next round of notification because a simple password reset is not triggering the GnuPG error. I'll close this issue as the field size is extended.
