### ISSUE TITLE
php7.2-mbstring Dependency Problem

### ISSUE THREAD

**Issue by utkonos** [MISP/MISP#5218]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18.04.3
| OS version (client)       | Ubuntu
| PHP version               | 7.2?
| MISP version   | 2.4.116

### Expected behavior
Install completes without errors.

### Actual behavior
Install fails

### Steps to reproduce the behavior
```
apt install wget
adduser --disabled-password misp
usermod -a -G sudo misp
usermod -a -G staff misp
usermod -a -G www-data misp
mkdir /home/misp/.ssh
cp /root/.ssh/authorized_keys /home/misp/.ssh/
chown -R misp:misp /home/misp/.ssh
chmod 700 /home/misp/.ssh
chmod 600 /home/misp/.ssh/authorized_keys
su - misp
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
```

### Logs, screenshots, configuration dump, ...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php-mbstring : Depends: php7.2-mbstring but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory
sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory
sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory
sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory
sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory

**Comment by JakubOnderka** [comment]
Hi, can you check if do you have `php-mbstring` package installed?

**Comment by JakubOnderka** [comment]
Ahh, sorry, I thought it is problem with composer, but it is problem with your package system (apt). You can check for example https://askubuntu.com/questions/1062160/package-php7-2-mbstring-unmet-dependencies-in-ubuntu-18-04

**Comment by SteveClement** [comment]
I think this has been fixed by now. Sorry for the late answer.

**Comment by utkonos** [comment]
Confirmed. This is no longer a problem. Changing the package repos available according to the link provided by @JakubOnderka worked.

**Comment by iglocska** [comment]
Thanks for the feedback!
