### ISSUE TITLE
OTX pulses to MISP 

### ISSUE THREAD

**Issue by milannshrestha** [MISP/MISP#5223]
I used https://github.com/gcrahay/otx_misp for updating events with OTX pulses. The got this error: 
/usr/local/lib/python2.7/dist-packages/pymisp-2.4.114-py2.7.egg/pymisp/api.py:125: DeprecationWarning: Call to deprecated method get_local_describe_types. (Use Expanded

and 
I checked my MISP dashboard log, what it had logged was as
**Received a published event that was empty. Event add process blocked.**  

can anyone help me with this? 
How do i add events from otx using automation.

**Comment by adulau** [comment]
There is a patch for otx_misp available at the following location https://github.com/gcrahay/otx_misp/pull/35 but it needs to be merge be by otx_misp team.
