### ISSUE TITLE
"An Internal Error Has Occurred" while opening GUI web interface  

### ISSUE THREAD

**Issue by mohamedelbagory74** [MISP/MISP#5224]
"An Internal Error Has Occurred" message appeared while opening Gui web inetrface  for first time after installing the virtual image of misp 
also found some problems when access data base "mysql" directory with permission denied 
 can anyone help me ?

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             Question,support
| OS version (server)        Ubuntu,
| OS version (client)        10
| PHP version               5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash    2.4.XX, hash of the commit

**Comment by JakubOnderka** [comment]
Can you provide more information from error log? By default, it is located at `/var/www/MISP/app/tmp/logs/error.log`.
