### ISSUE TITLE
Could not import STIX document

### ISSUE THREAD

**Issue by Applenice** [MISP/MISP#5229]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question
| OS version (server)       | Ubuntu18.04
| OS version (client)       | Windows10
| PHP version               | 7.2
| MISP version / git hash   |  v2.4.116@d0b99bebda6
| Browser                   | Chrome 77.0.3865.90

### Expected behavior
Can be imported successfully

### Actual behavior
Could not import STIX document

### Steps to reproduce the behavior
I use the download file to test:
https://oasis-open.github.io/cti-documentation/examples/example_json/poisonivy.json

`Import From..`->`STIX 2.X format (lossy)`->`Import 2.x JSON file`

The results show:`Could not import STIX document`

### Logs, screenshots, configuration dump, ...
Diagnostics Info:
```
Current libraries status…OK
STIX library version…OK
CYBOX library version…OK
MIXBOX library version…OK
MAEC library version…OK
STIX2 library version…OK
PYMISP library version…OK
```

I view the log file, 
```
(venv) misp@misp:/var/www/MISP/app/tmp/logs$ cat exec-errors.log 
Unknown STIX 2.0 type: identity
Unknown STIX 2.0 type: campaign
Unknown STIX 2.0 type: campaign
Unknown STIX 2.0 type: campaign
(venv) misp@misp:/var/www/MISP/app/tmp/logs$ 
```
How can I solve this?

**Comment by chrisr3d** [comment]
I figured out the origin of the problem, it should be working again.
It fixed at least an issue I had too, so let me know if anything goes wrong

**Comment by Applenice** [comment]
I just finished testing, `STIX 1.1.1 format (lossy)` and `STIX 2.X format (lossy)` are working now😉Thank you
