### ISSUE TITLE
VM of MISP

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#524]
Hi,

Is there an interest of having a VM with a working instance of MISP?
I can prepare one, based on a Ubuntu install.

Any extra configuration requests?

kr,

koen

**Comment by packet-rat** [comment]
Howz about Docker and Vagrant (puppet/chef/salt) Instantiation methods to VirtualBox and VMWare?

Packet Rat


On Jun 5, 2015, at 3:41 PM, Koen Van Impe <notifications@github.com> wrote:

Hi,

Is there an interest of having a VM with a working instance of MISP?
I can prepare one, based on a Ubuntu install.

Any extra configuration requests?

kr,

koen

**Comment by elhoim** [comment]
There is a docker thing done by Kyle Maxwell and co. @ https://registry.hub.docker.com/u/eg5846/misp-docker/

Never tried it, so I cannot vouch for quality.

**Comment by cvandeplas** [comment]
An automated installation script might indeed be more valuable than a
ready-made VM.
The big risk with VMs is that they need to be updated regularly.
With the script we should btw also be able to regularly build a new VM.

**Comment by elhoim** [comment]
If you choose to go the way @cvandeplas recommends, then there is a good base [here](https://github.com/daverstephens/The-SOC-Shop/blob/master/MISP-Stuff/Ubuntu-MISP%20Install%20Script)

But I think it can be further automated.

**Comment by elhoim** [comment]
Closing because: https://github.com/xme/misp-docker
