### ISSUE TITLE
Misp installation - Crypt_GPG and Console_CommandLine

### ISSUE THREAD

**Issue by Just-Me-666** [MISP/MISP#5241]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Question
| OS version (server)       | CentOS
| OS version (client)       | Windows 10
| PHP version               | 7.2
| MISP version / git hash   |  v2.4.116 
| Browser                   | Firefox 

### Expected behavior
Installed required dependencies

### Actual behavior
Dependencies do not exist in INSTALL folder

### Steps to reproduce the behavior
Basic installation.

### Logs, screenshots, configuration dump, ...

What  happend to this part of installation?

  Install Crypt_GPG and Console_CommandLine
  sudo pear install ${PATH_TO_MISP}/INSTALL/dependencies/Console_CommandLine/package.xml
  sudo pear install ${PATH_TO_MISP}/INSTALL/dependencies/Crypt_GPG/package.xml
  
This worked fine in v2.4.114.

**Comment by JakubOnderka** [comment]
Installation of `Crypt_GPG` was moved to composer, so this two commands are not necessary anymore. 

You just need to run `php composer.phar install`.

**Comment by Just-Me-666** [comment]
Ok i see, thanks.
