### ISSUE TITLE
Redis/resque connect failed

### ISSUE THREAD

**Issue by dragonyy** [MISP/MISP#5246]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug|
|OS version (server)       | Ubuntu 18.04.3 Server|
| OS version (client)       | macOS Mojave|
| PHP version               | 7.2.19|
| MISP version / git hash   | 2.4.116|
| Browser                   | Google Chrome 77.0.3865.90|

### Expected behavior

Jobs listed with a successful-colored bar

### Actual behavior

Yellow bar with "No worker active"
![image](https://user-images.githubusercontent.com/34716/65946039-d0f51d80-e467-11e9-8242-ade195e9e914.png)

 

### Steps to reproduce the behavior

* enable the feeds by "Sync Actions" => List Feeds
* after the "Fetch all events" icon shows, click it (say, feed 1)
* From menu, "Administration" => Jobs

### Logs, screenshots, configuration dump, ...

in /var/www/MISP/app/tmp/logs directory, 
resque-scheduler-error.log file:

> Warning Error: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]

resque-worker-error.log file:

> Warning Error: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]

error.log file:

> 2019-10-01 14:52:13 Warning: count(): Parameter must be an array or an object that implements Countable in [/var/www/MISP/app/Console/Command/AdminShell.php, line 166]
2019-10-01 14:56:07 Warning: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::zRangeByScore(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/ResqueScheduler.php, line 248]
2019-10-01 14:56:07 Warning: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]
2019-10-01 14:56:07 Warning: Redis::lPop(): connect() failed: Connection refused in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php, line 136]

mispzmq.error.log file:

> Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'

### Other issue

It looks similar with #5138. However, There are too many errors in 4 files, with zmq's, resque's. So I decide to open a new issue. 

With #5138 in mind, I paste the config info below:
/var/www/MISP/app/Config/config.php file:

> 'redis_host' => '127.0.0.1',
'redis_port' => 6379,
'redis_database' => 13,
'redis_password' => '',
'ZeroMQ_redis_host' => 'localhost',
'ZeroMQ_redis_port' => 6379,
'ZeroMQ_redis_database' => '1',
'ZeroMQ_redis_namespace' => 'mispq',

redis-cli seems working:
127.0.0.1:6379>

**Comment by ancailliau** [comment]
Did you check the local firewall rules?

**Comment by dragonyy** [comment]
> Did you check the local firewall rules?

the firewall is inactive

**Comment by axpatito** [comment]
I just had this problem a moment ago, in my case it was a SELINUX problem. To solve this I ran:

```
  sudo chcon -t usr_t $PATH_TO_MISP/venv
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files/terms
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files/scripts/tmp
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/Plugin/CakeResque/tmp
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/Console/cake
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/Console/worker/start.sh
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/files/scripts/mispzmq/mispzmq.py
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/files/scripts/mispzmq/mispzmqtest.py
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/ps
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/grep
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/awk
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/gpg
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/gpg-agent
  sudo chcon -t httpd_sys_script_exec_t /usr/bin/whoami
  sudo chcon -t httpd_sys_rw_content_t /tmp
  sudo chcon -R -t usr_t $PATH_TO_MISP/venv
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/.git
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/.gnupg
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/tmp
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/Lib
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/Config
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/tmp
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/webroot/img/orgs
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/webroot/img/custom
  sudo chcon -R -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files/scripts/mispzmq
  sudo setsebool -P httpd_can_network_connect on

  # Allow httpd to send emails from php
  sudo setsebool -P httpd_can_sendmail on

  # Enable and start the httpd service
  sudo systemctl enable --now httpd.service

  # Open a hole in the iptables firewall
  sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
  sudo firewall-cmd --zone=public --add-port=443/tcp --permanent
  sudo firewall-cmd --reload
```

The above based on the install script.

**Comment by dragonyy** [comment]
@axpatito I tried to prepare your solution. However it seems not the (default) Ubuntu system ...

- There's no sestatus command, and I install policycoreutils package to use it
- SELinux status:                 disabled
- No firewall-cmd could be found (using apt)

**Comment by ancailliau** [comment]
Just to be sure, you have all the redis modules installed and working (i.e. php and python)?

**Comment by dragonyy** [comment]
> Just to be sure, you have all the redis modules installed and working (i.e. php and python)?

I used to trust the Ubuntu INSTALL.sh would help me to install all php/python modules that MISP core needs. But according to what you mention above, is it possible the INSTALL.sh would miss something really important?

In fact, yesterday I encountered python3-dev package miss ( it has to be installed myself before MISP core).

Or you can provide a list of such modules that MISP core needs to work?

**Comment by ancailliau** [comment]
No idea. I don't use that script, but it should install everything needed. 

But can you fix the following to be sure?
> Traceback (most recent call last):
> File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 5, in
> import redis
> ModuleNotFoundError: No module named 'redis'
