### ISSUE TITLE
Download of last xx events

### ISSUE THREAD

**Issue by Th4nat0s** [MISP/MISP#526]
I had read carefully the automation guide but I did'nt found a solution.

Is they're a way to get (csv xlm json what ever, ) a direct link to download the last XX days of events, of course I could use /datefrom/dateto but I need a "dynamic" url generation.

To be clear, If somewhere I could download the "last week", or "last x days" events with a unique and static request, it could ease my life for parsing it in IntelMQ for example :) Without the need of creating a new parser/fetcher.

bye.

**Comment by adulau** [comment]
On the "short-term" roadmap, we have this functionality that might help to include the MISP feed into [IntelMQ](https://github.com/certtools/intelmq) or other stream processing tools (like [AIL](https://github.com/CIRCL/AIL-framework)). 

The already discussed scheme is the following:

- For each new event (update or creation), a ZMQ message is send to a PUB-SUB receiver by MISP.
- Each interested systems is subscribed to the ZMQ PUB-SUB and receive the JSON updates of the MISP events.

Maybe we could split the issue in two parts? The ZMQ publisher and the ReST API "last 20 updates".

**Comment by Th4nat0s** [comment]
The final functionality seems really great, but in the meanwhile, you makes me the happier man in the world if someone could put in place the last 20 updates feed.  :) 

I could already parse the CSV output in IntelMQ, so I could integrate it in our evil machinery quickly.

**Comment by adulau** [comment]
I'll create a new issue for last update from the API and keep this opens for the ZMQ PUB-SUB.

**Comment by Th4nat0s** [comment]
Thanks.
