### ISSUE TITLE
Last n days via the ReST API

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#527]
Could we add a simple ReST API "/last/<n>" where n could be expressed in days (or hours) to get last updated events (in JSON, CSV, XML)?

**Comment by iglocska** [comment]
I have an implementation of this now locally, but will still run some tests on it before pushing it. Currently I've implemented it for all exports using the publish timestamp, though this is something that might be better to change.

We have 3 options for dates in an event:
1. date (the simple date field that the user sets) - this is what the from/to fields use and is not really suitable for this request.
2. timestamp: The date of the last edit of the event, at first I was using this for the new API parameter
3. publish-timestamp: What I ended up using, this is the timestamp of the last publish

Reasoning: Timestamp is great for fetching any changes that happened, but what we'd end up missing are events that got synced over from another instance. Also, anything that has been changed and published should get caught by the publish-timestamp anyway.

Let me know if you'd rather have timestamp though!

**Comment by Th4nat0s** [comment]
Hi, 

publish-Timestamp is effectively a good idea since if an ioc change it will be take in consideration again. Anyway on the feed itself they're is good idea to keep creation time, since (at least we) don't want to keep some ioc online for too many times since for fp reasons. And publish-timestamp could be updated just for "naming" a malware without any ioc move.

**Comment by iglocska** [comment]
Let me know if you run into any issues with it!

**Comment by Th4nat0s** [comment]
Nice, Waiting after our misp provider :) and keep you informed.

**Comment by adulau** [comment]
Can we merge it into the master branch? The MISP Provider is running on the master branch ;-)

**Comment by iglocska** [comment]
Eek, that's embarrassing!

On Sun, Jun 7, 2015 at 7:41 AM, Alexandre Dulaunoy <notifications@github.com

**Comment by iglocska** [comment]
Done!

**Comment by adulau** [comment]
Cool thanks! It's merged on all the production instances using the master branch.
