### ISSUE TITLE
POST - 405 Method Not Allowed

### ISSUE THREAD

**Issue by Just-Me-666** [MISP/MISP#5281]
### Work environment

Type of issue | Question
-- | --
OS version (server) | CentOS
OS version (client) | CentOS
PHP version | 7.2
MISP version / git hash | v2.4.116

### Expected behavior
Post events via curl in json format to misp.

### Actual behavior
Post not working.

### Steps to reproduce the behavior
curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization:  *** " --data "event.json" -X POST https://misp/events

### Logs, screenshots, configuration dump, ...
 This is the result i get, when i try to post the event to MISP using curl. 

HTTP/1.1 405 Method Not Allowed
Date: Tue, 08 Oct 2019 13:08:24 GMT
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 339
Content-Type: application/json; charset=UTF-8

{"name":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","message":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/events"}[

The error is the same if i try to post the json file i receive from other misp instance (also v2.4.116) and if i try to post event example as written in misp documentation.

The option in Event View -> Download as... MISP JSON (metadata + all attributes)  including attachment is not the correct format to post event to misp via curl?

**Comment by mokaddem** [comment]
Hello,
If I understood correctly, you don't manage to send JSON data defined in a file to MISP with CURL.
As described in the [CURL documentation](https://curl.haxx.se/docs/manpage.html#-d), to send data form a file, you have to prefix the filename with the `@` character.

So you should have something like this:
```
curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: *** " --data "@event.json" -X POST https://misp/events
```
Feel free to re-open the issue if I misunderstood.
