### ISSUE TITLE
Cannot export in STIX or STIXv2

### ISSUE THREAD

**Issue by debernal** [MISP/MISP#5282]
I am trying to export events as Stix 2 and the required libraries were not installed, I installed them according to the INSTALL guide by running pip clone and pip install .

After installing the libraries, stixtest.py reports the following:

python stixtest.py
{"pymisp": "2.2", "stix2": "0.3.0", "maec": "4.1.0.16", "stix": "1.2.0.7", "success": 1, "mixbox": "1.0.3", "cybox": "2.1.0.19.dev0"}

However MISP does not detect them, MISP disgnostic web page shows the following:

STIX: 1.2.0.6
CyBox: 2.1.0.18.dev0
mixbox: 1.0.3
maec: 4.1.0.14
STIX2: 1.1.2
PyMISP: >2.4.93
Other versions might work but are not tested / recommended.

Current libraries status…Some of the libraries related to STIX are not installed. Make sure that all libraries listed below are correctly installed.
STIX library version…Incorrect STIX version installed, found 0, expecting 1.2.0.6
CYBOX library version…Incorrect CyBox version installed, found 0, expecting 2.1.0.18.dev0
MIXBOX library version…Incorrect mixbox version installed, found 0, expecting 1.0.3
MAEC library version…Incorrect maec version installed, found 0, expecting 4.1.0.14
STIX2 library version…Incorrect STIX2 version installed, found 0, expecting 1.1.2
PYMISP library version…Incorrect PyMISP version installed, found 2.4.65, expecting >2.4.93

Could you please tell me how to fix this problem? Thanks in advance.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | 10
| PHP version               |  7.0.33-0ubuntu0.16.04.6
| MISP version / git hash   | v2.4.114 (11f717002d054f4dcf3dab0d90bd4dc4deba2b31)
| Browser                   | Chrome

**Comment by debernal** [comment]
I have found that MISP is using python3, so the modules installed with pip take no effect. I´ve reinstalled the modules using pip3 and how the diagnosics tool show that I have the current or more recent modules. Do I have to downgrade those that show a version mismatch? Thanks. 

Current libraries status…Some versions should be updated:
STIX library version…OK
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.19.dev0, expecting 2.1.0.18.dev0
MIXBOX library version…OK
MAEC library version…Incorrect maec version installed, found 4.1.0.16, expecting 4.1.0.14
STIX2 library version…Incorrect STIX2 version installed, found 1.2.0, expecting 1.1.2
PYMISP library version…OK

**Comment by iglocska** [comment]
No, the latest versions should work fine, feel free to ignore MISP's nagging in this case.

**Comment by debernal** [comment]
Thanks iglocska, 

I have installed the exact libraries that are requested in the MISP Diagnostics web page, which the exception to cybox, as I didn't find the exact one and chose the closest one. It currently shows the following:

Current libraries status…Some versions should be updated:
STIX library version…OK
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.18, expecting 2.1.0.18.dev0
MIXBOX library version…OK
MAEC library version…OK
STIX2 library version…OK
PYMISP library version…OK

However it still does not let me export the events as STIX2, is there anything else that should be checked?


If I download as STIX + XML it correctly exports correctly.
![image](https://user-images.githubusercontent.com/13055543/66523395-7e45e200-eab5-11e9-9588-6df71dca220c.png)

If I download as STIX + JSON, it still downloads an XML file, with xml extension.
![image](https://user-images.githubusercontent.com/13055543/66523575-de3c8880-eab5-11e9-9518-8d56c20fd96b.png)

If I download STIXv2, IT provides a file with a 0.
![image](https://user-images.githubusercontent.com/13055543/66523513-bea56000-eab5-11e9-9a47-dd0185b1d52c.png)

Could you please help me? Thank you, 
David

**Comment by chrisr3d** [comment]
For the STIX in json format I guess there is a copy paste issue somewhere where we have `xml` as for the xml format, instead of `json`, we can confirm that tomorrow and fix it if confirmed

Concerning the STIX2 issue, can you check if you have anything in the following log file: `/var/www/MISP/app/tmp/logs/exec-errors.log` ?

**Comment by debernal** [comment]
Thanks for your help Chris, here are the contents of the log file:

cat /var/www/MISP/app/tmp/logs/exec-errors.log
```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1390, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1387, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 147, in handler
    i = self.__set_identity()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 126, in __set_identity
    identity_class="organization", interoperability=True)
  File "/usr/local/lib/python3.5/dist-packages/stix2/base.py", line 142, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).
```

**Comment by chrisr3d** [comment]
Sorry for the late answer, I had a couple of meetings last week.

The STIX1 download in json should now be working as expected and return a json file.

Concerning STIX2, I had to merge the update of the python library into our own one so we have the latest version.

After you get the latest MISP update with a `git pull origin 2.4`, you need to update the submodules and update the stix2 python library:
```
git submodule sync
git submodule update --remote
cd cti-python-stix2
```
And then depending if you have a `venv` directory under `/var/www/MISP`:
`sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .` 
**OR**
`sudo -H -u www-data pip3 install -U .`

Let me know if anything goes wrong

**Comment by debernal** [comment]
Thank you, should I be running the MISP update (git pull origin 2.4)  from the web page diagnostics section and then running the rest of the commands as root user from the command line?

**Comment by chrisr3d** [comment]
Sure you can run the update from the diagnostic tool if you want to.
Basically what it does is pulling the latest version and update all the submodules, which includes the one you want to be up-to-date here to fix your issue, so we're good.

Then as the standard user, as long as you are under the directory `/var/www/MISP/cti-python-stix2` the pip install commands listed from my previous message above should do the job.

But let me know if you have any problem in this update process

**Comment by debernal** [comment]
Hi Chris, thanks for your help.

I have updated MISP from the diagnostic tool, I confirm that the STIX v1 export works as expected. 
Regarding STIXv2, as root I executed the provided commands and I got an error on pip3 command due to permissions. 

```
Installing collected packages: stix2
  Found existing installation: stix2 1.1.2
    Uninstalling stix2-1.1.2:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'LICENSE.txt'
Consider using the `--user` option or check the permissions.
```
Since I was unable to install it as user www-data, I installed as pip3 install . and it worked successfully, I am now able to download the event as STIXv2 and a json file is correctly created! :)

However, is there any risk of having done this as root, instead of www-data and what is the recommended fix? thank you,

I have checked that cti-python-stix2 belongs to www-data, yet it still throws permision denied error, what do you recommend? Thanks

/var/www/MISP/cti-python-stix2# ls -l
```
total 64
-rw-r--r-- 1 www-data www-data 5075 Oct  8 07:31 CHANGELOG
-rw-r--r-- 1 www-data www-data 7106 Oct  8 07:31 CONTRIBUTING.md
drwxr-xr-x 5 www-data www-data 4096 Oct  8 07:31 docs
drwxr-xr-x 2 www-data www-data 4096 Oct  8 07:31 examples
-rw-r--r-- 1 www-data www-data 1490 Oct  8 07:31 LICENSE
-rw-r--r-- 1 www-data www-data   65 Oct  8 07:31 MANIFEST.in
-rw-r--r-- 1 www-data www-data 8303 Oct  8 07:31 README.rst
-rw-r--r-- 1 www-data www-data   98 Oct  8 07:31 requirements.txt
-rw-r--r-- 1 www-data www-data  165 Oct  8 07:31 setup.cfg
-rw-r--r-- 1 www-data www-data 2283 Oct  8 07:31 setup.py
drwxr-xr-x 9 www-data www-data 4096 Oct 17 07:19 stix2
-rw-r--r-- 1 www-data www-data  776 Oct  8 07:31 tox.ini

```

**Comment by chrisr3d** [comment]
Usually to be sure everything is right with the permissions within the MISP repository, you can run as root: `chown -R www-data:www-data /var/www/MISP`
Then the pip install command mentioned above should not be a problem.
For the moment and until the next time you update the python library, there is no worry to have as long as you are updating the right python environment (either the virtual python3 environment already mentioned that you can find within `/var/www/MISP/venv` if you have it, or the built-in python3), which you seemed to do correctly.

If you still have issues, let me know, and feel free to close the issue here if it is fixed for you

**Comment by debernal** [comment]
Thanks for your help Chris, everything worked fine, I am now able to export events in stix2 format without any issues 👍 :)

**Comment by chrisr3d** [comment]
I am happy to help and glad it works :)
