### ISSUE TITLE
Issue/Bug: Text attribute showing &nbsp; instead of whitespace.

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#5286]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18.04
| OS version (client)       | Windows 10
| PHP version               | 7.2.19
| MISP version / git hash   | 2.4.116 - 54eccbfa3dccfd2b638f086c4b4af4f8617ba125
| Browser                   | Chrome

### Expected behavior
Entering text (with spaces) in the "text" attribute should read spaces as whitespace.

### Actual behavior
Entering text (with spaces) in the "text" attribute, once saved, displays the text with &nbsp; in place of whitespace.

Entering the same text as a "comment" attribute renders correctly.

Additionally, when 'editing' the text attribute, the rendering does not incorporate the &nbsp, but as soon as it is saved it does. See screenshots for detail.

### Steps to reproduce the behavior
Save a text attribute with text including spaces.

### Logs, screenshots, configuration dump, ...
Example of save text attribute with &nbsp:
![image](https://user-images.githubusercontent.com/48736003/66475176-b7b52800-ea8a-11e9-9920-10530424baf6.png)
Example of editing text attribute whereby &nbsp does not show:
![image](https://user-images.githubusercontent.com/48736003/66475303-edf2a780-ea8a-11e9-95d0-1c62b5967884.png)

Example of comment attribute with same text that renders correctly:
![image](https://user-images.githubusercontent.com/48736003/66475337-04006800-ea8b-11e9-9028-0a155780acb0.png)

**Comment by JakubOnderka** [comment]
Will be fixed after https://github.com/MISP/MISP/pull/5287 is merged, thanks for report!
