### ISSUE TITLE
Best method to "purge" old MISP data

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5300]
We have a requirement to delete Events and their Attributes that have not been revised in a year in order to keep the database trimmed for space and performance.

In order to maintain db referential integrity, I was considering writing a rather simple PyMISP API client app retrieving all events with old timestamps and deleting at the event level and running it once a day.

Is there a better method?

Thanks.

**Comment by github-germ** [comment]
Follow-up Question: Is the a recommended method to archive aged-out data vs. deleting. Not sure how to accomplish that from the PyMISP API. Would this have to be done at the mysql level and if so, do you have any suggestions?

**Comment by ion-storm** [comment]
I'd like to age out/exclude data from the attribute api, seeing data in feeds from 2015 is kinda crazy

**Comment by github-germ** [comment]
I'd appreciate some insight as I write a PyMISP app that will run nightly and delete all events and attributes with a timestamp older than a date (e.g. a year old). 

1. **Events** -- This works...

To get a list of older than `event_id` I was able to use the following logic (I'm leaving out error/exception code). I didn't see a way to specify older than `timestamp` with `search_index` (seems like only newer) -- if there's a faster method, please let me know.
```
...
eventDictList = misp.search_index()
for eventDict in eventDictList:
    if int(eventDict['timestamp']) < epoch:
        sys.stdout.write(eventDict['id'] + '\n')
...
```
which is relatively fast and offers the same list I can get with this SQL:
```
select id from events where from_unixtime(timestamp) < '2019-01-01';
```

----

2. **Attributes** -- Help please...

What PyMISP call(s) will return a list of `attribute_id` that have `timestamp` older than a specified date. For example, what is an _efficient_ method to something similar to this SQL? 
```
select id from attributes where from_unixtime(timestamp) < '2019-01-01';
```
I say _efficient_, as we have over 100M attributes which is growing; hence, it seems like the only method is to get all attributes (all because I'm not seeing how to do older than `timestamp`, only newer) with `search(controller='attributes',...)` in a paginated loop and traverse the huge list. This would produce way more data than needed, and likely take a very long time.

**Comment by iglocska** [comment]
There are definitely better ways of handling it. Need to poke @rafiot
regarding the pymisp implementation but:

Timestamp on the attribute restSearch accepts a single value or a list with
2 values. You could simply do something like this:

['3650d', '365d'] as your input, which would return all data older than a
year, newer than 10 years (so everything before a year ago).

**Comment by Rafiot** [comment]
That should be supported by PyMISP.

**Comment by github-germ** [comment]
Cool. Let me try that. Thx...

**Comment by github-germ** [comment]
What am I missing?
(note: same result with `timestamp=(0, 1546300800)`)
```
(Pdb) list 97,105
 97  	    # search for events older than date
 98  	    try:
 99  	        eventDictList = misp.search_index(timestamp=('3650d', '365d'))
100
101  	        if   isinstance(eventDictList, dict) \
102  	         and 'errors' in eventDictList:
103  	            raise Exception(str(eventDictList))
104  	    except Exception as e:
105  	        raise Exception('search for events failed: %s\n' % (str(e)))
(Pdb) b 99
Breakpoint 1 at /Users/mitch/att/git/misp/production/src/misp/cli/z.py:99
(Pdb) r
> /Users/mitch/att/git/misp/production/src/misp/cli/z.py(99)main()
-> eventDictList = misp.search_index(timestamp=('3650d', '365d'))
(Pdb) n
CRITICAL [aping.py:2060 - _check_response() ] Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.117 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '32', 'Authorization': 'CtmJMWppkG7l481Lwd1sO48XoO1PhGufhOJntWFW', 'content-type': 'application/json'}
Request body:
{"timestamp": ["3650d", "365d"]}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/index"}
pymisp.exceptions.MISPServerError: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/index"}
> /Users/mitch/att/git/misp/production/src/misp/cli/z.py(99)main()
-> eventDictList = misp.search_index(timestamp=('3650d', '365d'))
(Pdb) 
```

and here's `debug.log`
```
2019-10-28 15:29:18 Warning: Warning (2): preg_match() expects parameter 2 to be string, array given in [/var/www/MISP/app/Controller/EventsController.php, line 378]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
preg_match - [internal], line ??
EventsController::__setIndexFilterConditions() - APP/Controller/EventsController.php, line 378
EventsController::index() - APP/Controller/EventsController.php, line 696
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-10-28 15:29:18 Error: [PDOException] SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s)
Request URL: /events/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT COUNT(*)...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT COUNT(*)...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT COUNT(*)...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Event), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('count', Array)
#6 /var/www/MISP/app/Controller/EventsController.php(749): Model->find('count', Array)
#7 [internal function]: EventsController->index()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
Use misp.search() not search_index()

**Comment by github-germ** [comment]
Is this correct? If we get the `timestamp tuple` arg working in `search_index`, I assume that if I also need to retrieve attributes in that time quantum, that I will need to use `search(controller='attributes',...)` as `search_index` is performed at the event level. And `search` produces a larger response set than `search_index`, but seems like no other choice?

**Comment by github-germ** [comment]
Ah, we collided on the wires. OK, `search`... Will try.

**Comment by github-germ** [comment]
All set. Yes, using `search` with a `timestamp` time quantum `tuple` works with both controllers.

THANKS!!

Interesting to note the differing `search` response with:
* `controller=event` returns
   * a `list` of `dict`s with each event `dict` within an `Event` key.
* `controller=attributes` returns
   * a `dict` with one key, `Attribute` which contains a `list` of the attribute `dicts`.

**Comment by Rafiot** [comment]
Yeah, this is an old inconsistency, pretty hard to fix without breaking existing code.

If you use `pythonify=True`, you always get a list.

**Comment by github-germ** [comment]
All good now.
