### ISSUE TITLE
Best method to restart MISP services

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5301]
At times we must restart all services supporting MISP. I wrote the attached (quick-and-dirty) script which from its output to the shell appears to succeed. However, the WebUI reports issues (I'll attach a screenshot).

Do you have any suggested tweaks to my script or perhaps a totally different and better method?

- - - - - - - -
```
#!/bin/bash

# Check if run as root
if [ "${EUID}" -ne 0 ]
then
    echo 'Must run as root'
    exit 1
fi

sysServicesStrings='httpd|rh-php|rh-mariadb| rh-redis'
sclServicesStrings='rh-mariadb|rh-php rh-redis'

sysServices=$(systemctl list-unit-files | grep enabled | cut -d' ' -f1 | egrep "${sysServicesStrings}")
sclServices=$(systemctl list-unit-files | grep enabled | cut -d' ' -f1 | egrep "${sclServicesStrings}")

cmd="systemctl restart ${sysServices}"
echo ${cmd}
${cmd}

startMispWorkers='/var/www/MISP/app/Console/worker/start.sh'
su -s /bin/bash apache -c "${startMispWorkers}"

exit 0
```

![workers-after-restart](https://user-images.githubusercontent.com/8812009/66671238-9474af00-ec29-11e9-8ee3-e0d01850cd57.png)

**Comment by github-germ** [comment]
I should've added that this is on RH7.4. Thanks for any feedback.

**Comment by Rafiot** [comment]
So you have a few dead workers, but I see quite a few of the same type are also running. Do you have any problem with your MISP instance?

Also, this is an old issue, and afaik, we improved the workers in the last few months, do you still have the problem? Just having lines telling you that some workers are dead isn't an issue as-is (besides that you have a red line on the UI), if you have other of the same workers type running.
