### ISSUE TITLE
MISP Upgrade issue 

### ISSUE THREAD

**Issue by MichaelHuys** [MISP/MISP#5315]
Hi,

currently I try to upgrade my Misp instance from version v2.4.103  to the latest one. I first tried through the Web interface but because that was not working I tried the below commands (cfr. Update docu):

_cd /var/www/MISP
# Replace www-data with whoever is your webserver user (apache/httpd)
sudo -u apache git pull origin 2.4
sudo -u apache git submodule update --init --recursive_

But then I get below error message:

root@svlitcmi# sudo -u apache git submodule update --init --recursive
error: Your local changes to the following files would be overwritten by checkout:
	README.md
	objects/annotation/definition.json
	objects/course-of-action/definition.json
	objects/credential/definition.json
	objects/credit-card/definition.json
	objects/domain-ip/definition.json
	objects/file/definition.json
	objects/ip-port/definition.json
	objects/mactime-timeline-analysis/definition.json
	objects/microblog/definition.json
	objects/netflow/definition.json
	objects/network-connection/definition.json
	objects/original-imported-file/definition.json
	objects/paste/definition.json
	objects/pe-section/definition.json
	objects/person/definition.json
	objects/process/definition.json
	objects/python-etvx-event-log/definition.json
	objects/regripper-system-hive-general-configuration/definition.json
	objects/regripper-system-hive-service-drivers/definition.json
	objects/report/definition.json
	objects/sb-signature/definition.json
	objects/script/definition.json
	objects/timesketch-timeline/definition.json
	objects/vehicle/definition.json
	objects/virustotal-report/definition.json
	objects/x509/definition.json
	objects/yara/definition.json
	relationships/definition.json
	schema_objects.json
Please, commit your changes or stash them before you can switch branches.
Aborting
Unable to checkout 'ffc120106c4ba9ed3b2fd5ae18d41f730e61b3ab' in submodule path 'PyMISP/pymisp/data/misp-objects'
Failed to recurse into submodule path 'PyMISP'

Any idea on the root cause?

Kind regards,

Michael

**Comment by packetwatch** [comment]
You need to go into the /var/www/MISP directory and run stash. You'll need to set some parameters beforehand. I believe this should do it. The  process is set the required git variables, stash, update MISP, reset permissions.

git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
git stash
git pull origin 2.4
git submodule update --init --recursive
sudo find /var/www/MISP -type d -exec chmod g=rx {} \;
sudo chmod -R g+r,o= /var/www/MISP/
sudo chown -R www-data:www-data /var/www/MISP/

**Comment by MichaelHuys** [comment]
Hi,

first of all thanks for your answer!
I tried the steps you described but I run into the exact same issue. See logs in attachment.

Any idea how I can solve this?

Kind regards,

Michael
[MISP.txt](https://github.com/MISP/MISP/files/3749499/MISP.txt)

**Comment by packetwatch** [comment]
Looks like you're getting closer! The MISP files updated but I see it failed on PyMISP. I know it's not the preferred practice, but I ran the commands and used sudo with normal "misp" user account, not the web service account. I guess sudo effectively elevated me but it keeps the .gitconfig file in my local path for those settings. At the end I reset the permissions to the web server account directly. In my case it's www-data but I see in your it's apache. After it was successful I could see the updated version info under Administration - Server Settings... - Diagnostics.

Might be worth trying?
