### ISSUE TITLE
feed_cache runs into "out of memory" error

### ISSUE THREAD

**Issue by cudor** [MISP/MISP#5330]
We have configured a local feed with caching enabled. The input are events from another MISP instance generated by PyMISP's feed-generator.

The cache_feeds scheduled task is configured to run every 24 hours at 13:00. This job gets started every day and I see it as "Queued" in the Jobs view.

In the resque-worker-error.log, I find a seemingly daily error message
PHP Fatal error:  Out of memory (allocated -1405091840) (tried to allocate 70 bytes) in /var/www/MISP/app/Model/Feed.php on line 129
where the number of bytes to be allocated vary between 32 and 70.

The PHP memory_limit in /etc/php5/apache2/php.ini has already been set to -1M.

What else can I do to get this feed working? Or is the data to be read simply too large?

**Comment by JakubOnderka** [comment]
What is the size of `hashes.csv` file in your feed?

**Comment by cudor** [comment]
`# ls -l hashes.csv`
`-rw-r--r-- 1 www-data www-data 946187760 Jun  6 12:20 hashes.csv`

**Comment by JakubOnderka** [comment]
Thats really big hashes.csv. So the problem is probably that php process take the whole memory.

Can you try to replace `getCache` method in `app/Model/Feed.php` with this implementation and run cache feed again?

```php
   /**
     * @param array $feed
     * @param HttpSocket $HttpSocket
     * @return Generator[array]
     * @throws Exception
     */
    private function getCache(array $feed, HttpSocket $HttpSocket)
    {
        $uri = $feed['Feed']['url'] . '/hashes.csv';
        $data = $this->feedGetUri($feed, $uri, $HttpSocket);

        if (empty($data)) {
            throw new Exception("File '$uri' with hashes for cache filling is empty.");
        }

        // Use generator to take less memory during CSV parsing
        $start = 0;
        while (($end = strpos($data, "\n", $start)) !== false) {
            $line = trim(substr($data, $start, $end - $start));
            yield explode(',', $line);
            $start = $end + 1;
        }
    }
```

**Comment by cudor** [comment]
After replacing the `getCache` method in `app/Model/Feed.php` with the above code, the following error is recorded in `app/tmp/logs/resque-worker-error.log`:
`Warning Error: Argument 2 passed to Feed::getCache() must be an instance of HttpSocket, boolean given in [/var/www/MISP/app/Model/Feed.php, line 119]`

**Comment by JakubOnderka** [comment]
So the feed is local? Then you can use this implementation:

```php
    /**
     * @param array $feed
     * @param HttpSocket|bool $HttpSocket
     * @return Generator
     * @throws Exception
     */
    private function getCache(array $feed, $HttpSocket)
    {
        $uri = $feed['Feed']['url'] . '/hashes.csv';

        if ($this->isFeedLocal($feed)) {
            // File is local, so doesn't make sense to copy it to temp, we can open it directly.
            $file = fopen($uri, 'r');
            if ($file === false) {
                throw new Exception("Could not read local file '$uri'.");
            }

        } else {
            $data = $this->feedGetUri($feed, $uri, $HttpSocket);
            if (empty($data)) {
                throw new Exception("File '$uri' with hashes for cache filling is empty.");
            }

            // Because `hashes.csv` can be quite large (hundreds MB), we save the whole file to temp and then read file
            // line by line without wasting memory.
            $file = fopen('php://temp', 'r+');
            if ($file === false) {
                throw new Exception('Could not create hashes.csv temp file.');
            }
            if (fwrite($file, $data) === false) {
                throw new Exception('Could not write content to hashes.csv temp file.');
            }
            unset($data); // Remove data from memory, they are already in temp file.
            rewind($file);
        }

        while (!feof($file)) {
            $line = fgets($file);
            if ($line === false) {
                throw new Exception('Could not read line from hashes.csv temp file.');
            }
            yield explode(',', trim($line));
        }

        fclose($file);
    }
```

**Comment by cudor** [comment]
I had tried it both with a local feed and a remote server. Maybe the latter one is a different job type, though.

The new code doesn't generate an error message. There is nothing recorded in `app/tmp/logs/resque-worker-error.log` at all. The "feed_cache" jobs are still queued, though. Is there anything else that I can check?

**Comment by cudor** [comment]
This issue can be closed. I replaced the feed-cache with a server-cache.
