### ISSUE TITLE
preview event remotely - images broken

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#5334]
MISP is trying to load the thumbnails which it can't.

**Comment by JakubOnderka** [comment]
Fix is already waiting for merge ;)
https://github.com/MISP/MISP/pull/5306

**Comment by iglocska** [comment]
Ah bummer missed it. Was giving trainings/events all week so falling behind on everything ;) 

Thanks!

**Comment by adulau** [comment]
Merged
