### ISSUE TITLE
Send email from user details screen

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#534]
Allow admins to send email from user details screen, instead of needing to select the user in a pull down list on the "contact user(s)" page.

**Comment by iglocska** [comment]
If you mean to send an e-mail with a password reset / send an e-mail with the welcome message and credentials, you've already had this for a few days already, there is a button titled "Send Credentials" on the user view.

Also, there is an additional button on the user index for this.

**Comment by elhoim** [comment]
Closing this, then, this cover the requested feature by the user.
