### ISSUE TITLE
Organisation field list for new user creation

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#535]
When creating a new user account, for the organisation, display a dropdown list of existing orgs on the server, and at the beginning of the list "new org..." to make the field editable to put the name of an org not already present.

**Comment by iglocska** [comment]
This already exists in the upcoming version on feature/sg - Organisations will be objects that need to be created separately and you get a dropdown list when you create a user.

**Comment by elhoim** [comment]
Already covered by development needed for sharing groups that are upcoming in v2.4. Closing this issue.
