### ISSUE TITLE
Sharing Group and org v. orgc

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5356]
**Questions/Suggestions Re' how Sharing Groups are filtered by `org` and `orgc`**

Am I correct that authorized access to objects (e.g. events) controlled by a Sharing Group are filtered by `org` (and NOT `orgc`)?

If this is true, then we'd really appreciate your advice to help us migrate our current MISP data set, as the original design had not considered the impact on Sharing Groups. We will be rolling out initially 3 Sharing Groups supporting a 3-tiered model of access from most restrictive to least, i.e. some feeds are only accessible to users in orgs granted access to SG1, and so on.

We have implemented several custom feed PyMISP-based ingestion scripts for premium feeds. Our design had us set
* `Event.org  = <same_org_for_all_events_for_all_feeds>`
* `Event.orgc = <org_specific_to_that_feed>`.

One solution I see is to set both `org` and `orgc` to `<org_specific_to_that_feed>` for all events for each of these feeds.

Please let us know if you have another solution, or any other advice.

Thanks!!

p.s. the design as we have it now did make it a challenge to tag existing events, but we did get that to work.

**Comment by iglocska** [comment]
I am not entirely sure I understand this. Org/Orgc should in no way affect sharing group behaviour.

Basically:

Sharing groups define:

1. Who has access to data (if I am in a sharing group I should be able to get access if the data is marked as such)
2. Orgc defines who the original creator of the data is. They are the ones that can modify the data.
3. Org is the "local owner" of the data, the org of the user that has created the data on the given instance (only different from Orgc when data is arriving via sync). It also defines visibility of the data when it comes to "Your organisation only" as the distribution level.

Hope this clarifies it somewhat.

**Comment by github-germ** [comment]
Thanks. Our issue is that we thought Sharing Groups would select authorized access based on Orgc and Org. It appears it’s only Org. So if that’s true we need to change all our Event Org values to be the organisation that should have access.

**Comment by iglocska** [comment]
Still not entirely sure if I understand what you mean. Orgc / Org and sharing groups handle different parts of the access.

**Comment by github-germ** [comment]
I think the core issue is our realization that SG filtering l**ooks at the `org` of an event ONLY**, i.e. the filtering for user access **does NOT consider the `orgc`** of an event in any way.

True?

**Comment by iglocska** [comment]
True for "your org" only. Sharing groups don't care about orgc or org.

**Comment by github-germ** [comment]
Yes, the server-side sharing group logic to filter an event based on a user's `org` only looks at the event's `org` (not the event `orgc`).

**Comment by iglocska** [comment]
OK, I am trying to think of a scenario where the org field would ever be
interesting in this regard and the only one I can come up with is this:

SharingGroup1: Org A, Org B, Org C
Event1: distribution SharingGroup1, org: Org D

I have no idea how you ended up in this scenario as an Org D user shouldn't
be able to create events on behalf of a sharing group that doesn't involve
them.

Is this correct? If so, could you walk me through how you ended up in this
situation in the first place?

**Comment by github-germ** [comment]
We have not used SharingGroups and are now planning to define, enable them and retrofit pre-existing events.

**Comment by github-germ** [comment]
We had Events in two different Org and Orgc. We've now changed them all to have Org and Orgc the same. Sharing Groups works well now. Thx.
