### ISSUE TITLE
Change suggestion to Object - Financial - Bank-account 

### ISSUE THREAD

**Issue by Gudmo** [MISP/MISP#5358]
Object - Financial - Bank-account 

I would like to recommend a change to the requirements of this object.
Instead of 
"Required one of: account" 
     it should be 
"Required one of: account OR iban"

There are many times we get an IBAN but dissecting and/or guessing the account number of the local bank behind it and most systems match on either bank account or IBAN anyway.

**Comment by Gudmo** [comment]
Still uncommented, can someone please make this minor change or create a new object that is bank-iban instead of bank-account

**Comment by iglocska** [comment]
Done, thanks!
