### ISSUE TITLE
Bulk tagging in the event view broken

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#5359]
Throws 404

**Comment by andurin** [comment]
Note: Last working version for me was 2.4.116.

Since we rely heavily on attribute level tagging for our internal block list this is actual quiet annoying.

Some tipps for me where to start with debugging?

Update 1:
```
# After select attributes in question the GET parameter is empty.
/attributes/addTag/selected?[]&_=1573566000347
```

-Hendrik

**Comment by mokaddem** [comment]
Should be fixed ;)

**Comment by andurin** [comment]
> Should be fixed ;)

Acknowledged! Thank you!
