### ISSUE TITLE
Events will be unpublished when a local tag is removed

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#5363]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Windows 10
| PHP version               | 7.1 and 7.3
| MISP version / git hash   v2.4.117 (abfeb3af1064ef8f26c482e8f4bec646f098e13b)
| Browser                   | If applicable

### Expected behavior
When a local tag is added or removed it would be nice if it remained untouched, and not getting unpublished.

### Actual behavior
When adding a local tag to an event or attribute everything works as planned the event remains 
"untouched", however when a local tag is removed the event gets unpublished and the organisation would need to publish this.

**Comment by iglocska** [comment]
Nice catch, definitely a bug

**Comment by iglocska** [comment]
Should be fixed now, better late than never, *cough*.

Thanks!
