### ISSUE TITLE
INSTALL.sh script clears the screen at the end

### ISSUE THREAD

**Issue by crondaemon** [MISP/MISP#5368]
When the script hits the end, the screen is cleared and a report is shown. This clears up the logs as well, making impossible to cut/paste them here.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 18.04
| OS version (client)       | n.a.
| PHP version               | PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
| MISP version / git hash   | n.a.
| Browser                   | n.a.

### Expected behavior

The logs not to be cleared.

### Actual behavior

The logs are cleared.

### Steps to reproduce the behavior

Run the script: during the installation the logs are shown, at the end they're cleared.

**Comment by SteveClement** [comment]
Agreed, it assumes that there will be no problems on a stock Ubuntu server install.

What you can do is start the installer in "debug" mode, then it will ask you to hit enter every time an action completed, just run the installer with:

```
bash -x
```

But I still need to think on a good way to get around this issue.
From the 'clear' man-page:

```
       -x   do not attempt to clear the terminal's scrollback buffer using the extended “E3” capability.
```

**Comment by crondaemon** [comment]
Wouldn't that reduce the level of automation? I just would like to have the option to scroll back. What about, instead of clearing, add some space or a big banner like "installation summary"? This is what I found more often in CLI installations.

**Comment by arcsector** [comment]
Clearing the screen really should be the user's option; following most UX design philosophies, if its supposed to be run once, err on the side of more user empowerment (if they wanna clear, they can with a simple append), but if its supposed to be run more than once, make the experience as seemless as possible while still allowing for all use cases.

**Comment by SteveClement** [comment]
Fixed in upcoming commit.
