### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#537]
Re. https://github.com/MISP/MISP/commit/31b99c5ce1bcdc8081253ac70911529156e8993f, I am wondering, if it would be a good idea to update install & update docs to cover cases like this by specifying for each external repo, which release needs to be checked out.
This would avoid integration problems when checking out a master of a repo that might be not working or non-retrocompatible.

**Comment by iglocska** [comment]
Yeah indeed. The reason for it tracking the master branch in the past was
that the release versions of STIX / Cybox didn't have some necessary fixes
that were required to get MISP working (and some features well still in
progress).

We could now simply move to a fixed version, same as what's happening now
with Cybox.

**Comment by iglocska** [comment]
This should be sorted out now.
