### ISSUE TITLE
bulk entering user accounts

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5371]
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()

Is there a way to bulk enter users into MISP?

**Comment by iglocska** [comment]
Not really. You could of course script it and do it via the API in a loop, but other than that no.

**Comment by mokaddem** [comment]
I would suggest using the api. The restclient can help you build the query
endpoint: ``/admin/users/add``
You can also use PyMISP..

**Comment by dmolina213** [comment]
Are the user accounts defined in a json file or are they located in the mysql database?

**Comment by iglocska** [comment]
MySQL database. `users` table. Please don't do it directly through the DB
though, you'll run into issues :)

**Comment by adulau** [comment]
There is a sample script in PyMISP example directory: https://github.com/MISP/PyMISP/blob/master/examples/add_user.py
