### ISSUE TITLE
Can all default feed URLs use https?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5374]
Is there any reason that some of the default feeds use http? Are network team only allows our production MISP instance to talk to the public internet using https.

**Comment by adulau** [comment]
Because some feeds were not supporting TLS or they had broken certificate at some point. If you see some feeds now safely supporting TLS, don't hesitate to make a pull-request with the updated JSON.

**Comment by github-germ** [comment]
We are talking with our network team to see about making an firewall exception for those feeds that only support http URLs. Thx...
