### ISSUE TITLE
HOWTO improve the speed of the correlations table rebuild

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5379]
2.4.117

We are experimenting with enabling correlations in our dev lab, and decided to rebuild our `correlations` table via the WebUI. Granted we do have too many correlated indicators, and are working to make improvements as part of this effort.

**The rebuild is now in it's 11th day and still not complete!!**

* Yes, there are way too many rows, but why is this so slow?
* Is there something we can tune in the MySQL config to improve the process?
* Open to your suggestions.

Thanks.

```
MariaDB [misp]> select max(id) from correlations;
+------------+
| max(id)    |
+------------+
| 2460615880 |
+------------+
1 row in set (0.00 sec)

MariaDB [misp]> select date_created,progress,message from jobs where progress != 0 and job_type like '%enerate%';
+---------------------+----------+--------------------------+
| date_created        | progress | message                  |
+---------------------+----------+--------------------------+
| 2019-10-24 18:30:59 |       80 | Correlating Event 107938 |
+---------------------+----------+--------------------------+
1 row in set (0.00 sec)

MariaDB [misp]>
```

**Comment by adulau** [comment]
I had to read the output 3 times (ok count() versus max() might a bit different). We are talking about 2.4 billions of correlation? That's really a lot. Have you played with caching? and split the data among instances, feeds and so on.  What's your ratio of correlation over the number of attributes?
