### ISSUE TITLE
Default NIDS SID on user creation

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#538]
SID (Signature IDentification) is a unique ID for rules used in snort & suricata rules.
SourceFire VRT (now Cisco Talos) & Emerging Threats both have dedicated ranges allocated by convention.

When creating a user account in MISP, it is possible to add the SID range that will be used to generate IDS rules. It would be good to propose a valid default value.

It seems various ranges are allocated at least up to 2.999.999 (GPL, VRT & ET rulesets), so just be sure we could use 5.000.000 ?

Ref: http://doc.emergingthreats.net/bin/view/Main/SidAllocation

**Comment by adulau** [comment]
By default an SID is set when creating new users.

**Comment by elhoim** [comment]
Opened https://github.com/MISP/MISP/pull/10969 against `2.5`: the random base at `app/Model/User.php:283` goes from `mt_rand(1000000, 9999999)` to `mt_rand(5000000, 9999999)`, clearing the Talos/GPL/ET allocations below 3,000,000 as requested here. The three hardcoded `4000000` seeds (bootstrap admin, Apache and LDAP auto-provisioning) are moved to `5000000` for consistency.
