### ISSUE TITLE
galaxies showing up in taxonomy section of the event page

### ISSUE THREAD

**Issue by open-source-rs** [MISP/MISP#5384]
Had to go through and change my custom galaxy namespaces.
Once installed into MISP, for some reason some galaxies are now showing up in the section where taxonomy tags normally go.  This has never happened in the past.

What would cause this so I can troubleshoot further?

![image](https://user-images.githubusercontent.com/50664502/68414620-8188c800-015e-11ea-8be4-35e2c373a405.png)

![image](https://user-images.githubusercontent.com/50664502/68414637-8f3e4d80-015e-11ea-8aed-b3327d7dc7ca.png)

**Comment by iglocska** [comment]
This is basically a symptom of a galaxy not being loaded that is referenced via a tag. The system works like this:

Every galaxy is attached via a tag. For example, if I have a `Bar` cluster in the `Foo` galaxy, then MISP will internally generate a tag name for the galaxy to use as "glue" - in this case `misp-galaxy:Foo="Bar"`. 

Whenever you view an event, MISP retrieves all attached tags, including those used as glue for galaxies, meaning that `misp-galaxy:Foo="Bar"` will be included with your other tags. Before rendering the information for the user though, MISP will try to see if any of the tags are in fact valid galaxy clusters and try to replace them. If a cluster with the `tag_name` field of `misp-galaxy:Foo="Bar"` exists, it will remove the tag and append the galaxy cluster to the event.

In your case, MISP could not find a cluster with the `tag_name` of `misp-galaxy:osrs-event-type="Ransomware"` and thus decided that, though it looks like a galaxy cluster glue tag, it cannot resolve it.

Have a look if you in fact have the corresponding galaxy cluster in your DB and if there isn't a typo in your galaxy library. First to check if the cluster even exists in your MISP db, you could run this mysql query:

`SELECT id from galaxy_clusters where tag_name = 'misp-galaxy:osrs-event-type="Ransomware"';`

If this returns no hits then something went wrong and you should check your galaxy cluster JSON (capitalisation for example matters IIRC) and reload the galaxies in MISP (go to your galaxy index and click on update galaxies).

Hope this helps.

**Comment by open-source-rs** [comment]
thanks andras!

basically what i thought...
i pretty much tore the db in half when i forced the update of the name spaces so now MISP confused...

which i guess is fine
i've created so much in the way of custom galaxies that there's really no going back
it will eventually smooth itself out over time and data entry
just gonna have to be patient with it

jimbo

**Comment by open-source-rs** [comment]
fwiw - 

i have zero issues mining the data using MISP42 and Splunk
that MISP42 is a super life saver
also saw that ELK now has an official filebeat for MISP

super sweet

jimbo
