### ISSUE TITLE
Exporting Events by 'Internal Reference Text'

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#5385]
Is there anyway to grab the events from MISP that have been added like this:

![image](https://user-images.githubusercontent.com/5932961/68428656-970beb00-017a-11ea-9ff4-82dbf145aa7a.png)

On Home I can search for 'trickbot' and get all the events... but how do I download them or get them out without doing it one by one.  

Thanks!

**Comment by iglocska** [comment]
So one thing you could do is simply search on attribute value such as this:

POST to /events/restSearch
payload:
```
{
  "returnFormat": "json"
  "value": "%#trickbot%"
}
```
The problem with this will be that it will return any event that has
"#trickbot" in any of its attribute values, not only for internal
reference. If you want to ensure that it's restricted to those, you'd have
to have a small script that does it in two steps:

Step 1, find all attributes of type internal reference that contain
#trickbot:


POST to /attributes/restSearch
payload:
```
{
  "returnFormat": "json",
  "category": "Internal reference",
  "value": "%#trickbot%"
}
```

Step 2, extract all of the event IDs from the above:

Loop through the response's attribute list
(result["response"]["Attribute"]) and extract all unique event_ids

Step 3:

get all of the events that we found above:

POST to /events/restSearch
payload:
```
{
  "returnFormat": "json"
  "eventid": $event_ids
}
```

**Comment by mathurin68** [comment]
Oooh thanks @iglocska,  that will take me some time... MISP looks better all the time though!
