### ISSUE TITLE
inconsistent state in database after update to 2.4.118

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5388]
Hello,

I just updated my MISP from 2.4.117 to 2.4.118. In the diagnostics tab at the Schema status I got a critical warning:

Table name          | Description                         | Expected schema                        | Actual schema
decaying_models | Column `name` is different | name NO varchar 255   utf8_bin | name YES text 65535   utf8_general_ci

**Comment by mokaddem** [comment]
I guess someone checked out the development branch of the `decaying` feature.. ;)
The ``decaying_models`` table is indeed expected to have the **name** column defined as
```
name NO varchar 255 utf8_bin
```
But you have it defined as
```
name YES text 65535 utf8_general_ci
```

I guess a
 ```
ALTER TABLE `decaying_models` MODIFY COLUMN `name` varchar(255) COLLATE utf8_bin NOT NULL;
```
should solve your issue :)

**Comment by FafnerKeyZee** [comment]
Me ? checked out the dev branch ? Really ? :p Ok spotted!

Thanks for this explanation, was thinking about a modification for the master branch too.

**Comment by FafnerKeyZee** [comment]
Me ? checked out the dev branch ? Really ? :p Ok spotted!

grrrr got an error,

> MariaDB [misp]> ALTER TABLE `decaying_models` MODIFY COLUMN `name` varchar(255) COLLATE utf8_bin NOT NULL;
ERROR 1265 (01000): Data truncated for column 'name' at row 1
MariaDB [misp]>

**Comment by FafnerKeyZee** [comment]
Ok, working fine, just a model without name ^^ so NULL .
