### ISSUE TITLE
Missing X-Requested-With header causes double navbar and nav-list

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#539]
I just spent an hour troubleshooting an issue on my test MISP instance (over HTTP). It seems our proxy is stripping the X-Requested-With header from jquery Ajax requests. The result is that CakePHP's request->is('ajax') will always return false. This means the code in EventsController.php will return a full page instead of just the second page of attributes or discussion, resulting in a double navbar and nav-list. 

```
if ($this->request->is('ajax')) {
        $this->disableCache();
        $this->layout = 'ajax';
        if (!isset($this->params['named']['attributesPage'])) {
                $this->render('/Elements/eventdiscussion');
        } else {
                $this->set('page', $this->params['named']['attributesPage']);
               $this->render('/Elements/eventattribute');
        }
} else {
        $this->set('page', $page);
}
```

I am not sure if we should fix this in the MISP code. Obviously this is not an issue with MISP behind HTTPS because a proxy cannot strip anything from the encrypted data. I just wanted to document this somewhere and hopefully save someone some time.

**Comment by elhoim** [comment]
Addition to the diagnostics page?

**Comment by iglocska** [comment]
Sounds like a good idea, that must have been frustrating to figure
out, RichieB2B...

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
