### ISSUE TITLE
Critical warning! The MISP database seems to be in an inconsistent state. Immediate attention is required.

### ISSUE THREAD

**Issue by Gudmo** [MISP/MISP#5393]
After an automatic upgrade from 117 to 118 this error is in my Diagnostics

Table name | Description | Expected schema | Actual schema
-- | -- | -- | --
attributes
Column `comment` is different | comment YES text 65535 utf8_bin | comment NO text 65535 utf8_bin
feeds
Column `settings` is different | settings YES text 65535 utf8_general_ci | settings NO text 65535 utf8_general_ci
galaxies
Column `icon` is different | icon NO varchar 255 utf8_bin | icon YES varchar 255 utf8_bin
logs
Column `action` is different | action NO varchar 20 utf8_bin | action NO varchar 80 utf8_bin
Column `change` is different | change YES text 65535 utf8_bin | change NO text 65535 utf8_bin
Column `ip` is different | ip NO varchar 45 utf8_bin | ip YES varchar 45 utf8_bin
object_references
Column `object_uuid` exists but should not
Column `source_uuid` does not exist but should | source_uuid YES varchar 40 utf8_bin |  
object_template_elements
Column `disable_correlations` exists but should not
Column `object_relation` is different | object_relation YES varchar 255 utf8_bin | object_relation YES varchar 255 utf8_unicode_ci
Column `type` is different | type YES varchar 255 utf8_bin | type YES varchar 255 utf8_unicode_ci
Column `disable_correlation` does not exist but should | disable_correlation NO tinyint 3 |  
org_blacklists
Column `comment` is different | comment NO text 65535 utf8_unicode_ci | comment YES text 65535 utf8_unicode_ci
shadow_attributes
Column `proposal_to_delete` is different | proposal_to_delete NO tinyint 3 | proposal_to_delete YES tinyint 3

![image](https://user-images.githubusercontent.com/3922275/68689616-8e475a80-0568-11ea-8e72-33d1d23e3ad7.png)

**Comment by timhux123** [comment]
I too am seeing a similar issue after upgrading from 117 to 118.
Currently installed version… v2.4.118 (4f9e3ec6d3cbb31e581a2511f05f06bc9eb962bd) 
Ubuntu 16.04
PHP extension version: 5.0.2
Redis version: 5.0.5


![MISP_DB_Schema_Diagnostic_Error](https://user-images.githubusercontent.com/8250365/68901657-efebfe00-06fb-11ea-9b86-1c15f200e70a.PNG)

**Comment by Rafiot** [comment]
The warnings is a lot more scary than they actually should, and they aren't necessarily that critical: it just means that your database isn't exactly in line with the expected schema.
These differences didn't appear right now, they've always been here so if your MISP instance was working fine until now it will not get worse now.

The next release will provide more details, and the SQL commands recommended to fix the issues.
