### ISSUE TITLE
No valid UUID set

### ISSUE THREAD

**Issue by qaistem1** [MISP/MISP#5394]
Hi !

Whenever I create a new organisation but I keep receiving the error that says "No valid UUID set" in the server settings and maintenance page.

I tried to generate the UUID manually and automatically from MISP.

Thank you!

**Comment by mokaddem** [comment]
Hello,
Does the issue also happen if you press the ``Generate UUID`` button before submission?
Do you get the message after clicking the ``Submit`` button?

**Comment by qaistem1** [comment]
> Hello,



Hi Sami, thank you for your reply.

> Does the issue also happen if you press the `Generate UUID` button before submission?

Yes, it happens !

> Do you get the message after clicking the `Submit` button?

Yes

**Comment by mokaddem** [comment]
I'm a bit confused...
How creating an organization and the server settings and maintenance page are related?

**Comment by mokaddem** [comment]
I'm a bit confused...
How creating an Organization and ``server settings and maintenance page`` related?

**Comment by qaistem1** [comment]
When I create a new organization, a UUID will be generated auto/manually and will be assigned to the created organization.

And in the Server Setting page and in the Maintenence page, it shows that no valid UUID for the organization in the Org UUID column

**Comment by mokaddem** [comment]
Could you please post a screenshot of the page that shows ``no valid UUID for the organization in the Org UUID column``?
Thanks a lot!

**Comment by qaistem1** [comment]
![UUID no Valid Set](https://user-images.githubusercontent.com/35815021/69125589-cf7ec380-0aae-11ea-96d9-8aa4ef079237.PNG)

**Comment by iglocska** [comment]
Please ignore that, that's a bug. Basically if the row is not coloured there's no issue, it just seems to show the default error message even if everything's in order. Will push out a fix today.

**Comment by chrisinmtown** [comment]
Same reported as #6270, and I see this behavior today in v2.4.137.  @iglocska are you sure you pushed a fix?

**Comment by mangelsnc** [comment]
Any plans to fix it? We are already in 2024 and it is still not fixed.

**Comment by iglocska** [comment]
Sorry for the "slight" delay ;)
