### ISSUE TITLE
Bulk import threat intelligence

### ISSUE THREAD

**Issue by Tukali** [MISP/MISP#5397]
How can I import my own threat intelligence,I only found the API in the official documentation,there is no specific description of this,I wonder if there is any other way,or is more specific operation document,most of it says how do you export it

**Comment by adulau** [comment]
The ReST API can be used to add event, attributes, objects and so on to import any data you would like. 

In addition to that, you can also have a look at PyMISP which provides a higher-level in Python to use the ReST API and there are plenty of examples in the following directory:

https://github.com/MISP/PyMISP/tree/master/examples

**Comment by enjeck** [comment]
> The ReST API can be used to add event, attributes, objects and so on to import any data you would like.
> 
> In addition to that, you can also have a look at PyMISP which provides a higher-level in Python to use the ReST API and there are plenty of examples in the following directory:
> 
> https://github.com/MISP/PyMISP/tree/master/examples

@Tukali Did this information help?
