### ISSUE TITLE
Link events using different domains notations

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#54]
Reported by David Andre, Mar 27, 2012

Link events using different domains notations:
ie:
*.domain.com
domain.com
subdomain.domain.com

**Comment by adulau** [comment]
Can the regexp object solve the issue? Like the regexp example:

![](https://www.misp-project.org/assets/images/misp/blog/DGA-in-MISP.png)

I'll close the issue. Feel free to reopen if this issue is not solved.
