### ISSUE TITLE
Log everything to disk in JSON / STIX

### ISSUE THREAD

**Issue by mb-rack** [MISP/MISP#540]
Logging all events/attributes and system logs as JSON or STIX (or XML... etc) to a file or multiple files on disk would allow log forwarding through apps such as the splunk universal log forwarder and/or Logstash, etc.

**Comment by mb-rack** [comment]
It may be a good idea to do this when an event is published, that way it is more likely to push whole events to external destinations.

**Comment by adulau** [comment]
Thanks for the feedback. It's indeed in the pipe with the PUB-SUB publisher in MISP. https://github.com/MISP/MISP/issues/526#issuecomment-109552488 - A subscriber can be done to feed a local file-system or any other connector like Splunk universal log forwarder, AIL, IntelMQ...
