### ISSUE TITLE
Event Graph and ATT&CK map not showing

### ISSUE THREAD

**Issue by sunghhong** [MISP/MISP#5403]
I have recently (within last two weeks) installed MISP.  Upon its installation, it was displaying event graph and ATT&CK map.  But, it is now not filling event graph with the events.  It is basically empty.  Also, it is no longer showing ATT&CK map.  Any idea how to troubleshoot?

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | MISP Event Graph
| OS version (server)       | Centos7.7
| OS version (client)       | Centos7.7
| PHP version               | 7.2
| MISP version / git hash   | 2.4.118
| Browser                   | Chrome

**Comment by adulau** [comment]
Any error in the console of your browser that you could share?

**Comment by sunghhong** [comment]
I am not getting any error message showing on the scrren.  But, here is what I see on the screen.  Fetching data keeps circling and ATT&CK map is showing as a bar. 

![Picture1](https://user-images.githubusercontent.com/51897368/69075785-eb1e9700-09e6-11ea-82f4-dfd5949565a4.png)

**Comment by mokaddem** [comment]
Do you have your ``Galaxies`` and ``ObjectTemplates`` up-to-date?
You can update them by clicking the update button under their respective pages.

**Comment by sunghhong** [comment]
I have made them up-to-date.  And, I can see event graph and ATT&CK map properly loading.  Thank you so much!
