### ISSUE TITLE
Improvement for the API keys handling

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#5406]
# API key proposal change (new change/improvement) [TODO]

- Allowing a user to have multiple API keys
- Each API key should have a description/meta field where the user can add information about the use of the key
- Each API key should have the ability to have network filtering (IPv4/IPv6 addresses, CIDR or not)
- The ability to have expiring API keys
- History of the API key (including the disabled/reset ones)

**Comment by iglocska** [comment]
This is trickier than first anticipated and will need a lot more work. Issues identified during a quick bash at the issue:

- authenticating users with multiple API keys is quite straight forward
- the migration itself is rather straight forward - as long as we do not purge the previous keys
- all the reset functionalities (reset individual keys, all sync keys, all instance keys) raise questions though
- Dealing with disabled keys (when to load them, when to ignore them) is somewhat tricky and needs to be done on a case by case basis.

Initial bootstrap for the feature: https://github.com/MISP/MISP/tree/feature/multiple_authkeys

**Comment by cvandeplas** [comment]
this is already implemented for a while
