### ISSUE TITLE
Exported STIX2.0 object id format

### ISSUE THREAD

**Issue by ufo0531** [MISP/MISP#5410]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.112
| Browser                   | If applicable

### Expected behavior
When MISP events exported to STIX2.0, the id format of custom object in STIX2.0 does not follow the specification in STIX2.0.

The export STIX2.0:
```
{
  "id": "x-misp-object--5a6f3acb-08d4-4861-ae24-43aa950d210f",
  "x_misp_category": "Other",
  "labels": [
    "misp:type=\"comment\"",
    "misp:category=\"Other\"",
    "misp:to_ids=\"False\""
  ],
  "x_misp_timestamp": "2018-04-04 22:00:00",
  "x_misp_value": "pdb: Z:\\Projects\\Vermin\\TaskScheduler\\obj\\Release\\Licenser.pdb",
  "created_by_ref": "identity--55f6ea5e-2c60-40e5-964f-47a8950d210f",
  "type": "x-misp-object-comment",
  "created": "2019-11-19T07:18:43.408Z",
  "modified": "2019-11-19T07:18:43.408Z"
}
```
According to the specification [link](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709311), the id `x-misp-object--5a6f3acb-08d4-4861-ae24-43aa950d210f` should be `[object-type]--[UUIDv4]`.

So the id of custom objects in exported STIX2.0 should be `x-misp-object-comment--5a6f3acb-08d4-4861-ae24-43aa950d210f`.

Thanks.

**Comment by iglocska** [comment]
Makes sense.

Ping @chrisr3d

**Comment by chrisr3d** [comment]
Will have a look soon

**Comment by chrisr3d** [comment]
It should be working as intended now, thank you
If anything goes wrong, please tell me and reopen if necessary
