### ISSUE TITLE
MISP Block old event alert by date

### ISSUE THREAD

**Issue by qaistem1** [MISP/MISP#5411]
![MISP Block old event alert by date](https://user-images.githubusercontent.com/35815021/69155001-a92a4980-0ae9-11ea-863f-867ccbdabd17.PNG)

What does Block old event alert by date means? 

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by mokaddem** [comment]
If you configure this setting, and an old event (old is defined by the value you set for this setting) receives an update, emails will not be send out
