### ISSUE TITLE
F Write, Read, Stat Error

### ISSUE THREAD

**Issue by otgrkiss** [MISP/MISP#5414]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, 
| OS version (server)       |  CentOS, 
| OS version (client)       | Cent OS 7
| PHP version               | 7.3
| MISP version / git hash   | 2.4.118, 4f9e3ec6d3cbb31e581a2511f05f06bc9eb962bd
| Browser                   |  Firefox

Receiving Pushed Events from other MISP does not work. 
And Rest Client calls regarding Attributes or Events return empty Response Body.
Pymisp: ERROR [aping.py:2092 - _check_response() ] Got an empty response.
And the UI Rest Client does not return a result either. 

The following errors are from the error.log file:

 2019-11-20 15:01:53 Warning: Warning (2): fwrite() expects parameter 1 to be resource, bool given in [XX/MISP/app/Model/Attribute.php, line 4370]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fwrite - [internal], line ??
Attribute::restSearch() - APP/Model/Attribute.php, line 4370
AttributesController::restSearch() - APP/Controller/AttributesController.php, line 1904
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-11-20 15:01:53 Warning: Warning (2): fseek() expects parameter 1 to be resource, bool given in [XX/MISP/app/Model/Attribute.php, line 4371]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fseek - [internal], line ??
Attribute::restSearch() - APP/Model/Attribute.php, line 4371
AttributesController::restSearch() - APP/Controller/AttributesController.php, line 1904
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-11-20 15:01:53 Warning: Warning (2): fstat() expects parameter 1 to be resource, bool given in [XX/MISP/app/Model/Attribute.php, line 4372]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fstat - [internal], line ??
Attribute::restSearch() - APP/Model/Attribute.php, line 4372
AttributesController::restSearch() - APP/Controller/AttributesController.php, line 1904
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-11-20 15:01:53 Warning: Warning (2): fclose() expects parameter 1 to be resource, bool given in [XX/MISP/app/Model/Attribute.php, line 4377]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fclose - [internal], line ??
Attribute::restSearch() - APP/Model/Attribute.php, line 4377
AttributesController::restSearch() - APP/Controller/AttributesController.php, line 1904
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by otgrkiss** [comment]
2019-11-20 15:17:31 Notice: Notice (8): compact() [<a href='http://php.net/function.compact'>function.compact</a>]: Undefined variable: score in [XX/MISP/app/Controller/AttributesController.php, line 1880]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
compact - [internal], line ??
AttributesController::restSearch() - APP/Controller/AttributesController.php, line 1880
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by otgrkiss** [comment]
Some Events do seem to appear. But not all of them.
New error from Log File:
2019-11-21 08:33:00 Error: [MethodNotAllowedException] No valid event data received.
Request URL: /events
Stack Trace:
#0 [internal function]: EventsController->add()
#1 XX/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 XX/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 XX/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 XX/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by otgrkiss** [comment]
Is there anything I can do for now? @adulau 
We are basically out of order.

**Comment by Rafiot** [comment]
That sounds like a file system-level problem. Or maybe permissions.

Did your MISP instance ever work before?

**Comment by adulau** [comment]
Indeed, it seems to be a potential file permission issue.

**Comment by otgrkiss** [comment]
@Rafiot Our MISP Instance has been running for a year now. These Problems only occur since the update to the Version from 117 to 118. Update was Thursday last week. Problems occur Tuesday this week.

**Comment by otgrkiss** [comment]
@adulau Our diagnostics pages says it can't write to /tmp. But our Instance is running with the apache user and when i switched to the user apache i could write fine to /tmp

**Comment by iglocska** [comment]
It definitely can't. Those error messages show that it can't write to the
temp dir of MISP.

**Comment by otgrkiss** [comment]
Issue resolved. It was indeed a file permission error. 
"PrivateTmp" in /etc/systemd/system/multi-user.target.wants/httpd.service gave an alternative tmp directory which was not writable.
Thank you for your support

**Comment by iglocska** [comment]
Thanks for the feedback, closing the issue for now. If you run into any other issues feel free to open a new one.
