### ISSUE TITLE
doku bug: composer.phar install of gnupg

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#5419]
Following the installation guide at https://misp.github.io/MISP/xINSTALL.debian10/, we discovered that after the line 

```bash
$SUDO_WWW php composer.phar install

```
The documentation is missing a:
```bash
$SUDO_WWW php composer.phar update

```

Otherwise the pgp package wont' actually get installed.

Besides, the error messages for testing if pgp is working (Diagnostics page) are not very helpful in debugging. Suggestion: pass through the actual pgp error mesage.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian,
| OS version (client)       | 10
| PHP version               | 7.3

### Expected behavior
docs

**Comment by SteveClement** [comment]
@aaronkaplan there is a test.php script that helps you debug pgp issues: https://github.com/SteveClement/misp-test/

It will dump you the entire PGP stream.

Function in question: https://github.com/SteveClement/misp-test/blob/5be5b89bc948fa7dd454d9f25183b73198d9bd39/test.php#L254

**Comment by SteveClement** [comment]
fixed, a while ago.
