### ISSUE TITLE
MISP Object Related Events Duplicated for Each Object in an Event

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#5421]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | All Versions
| OS version (client)       | All Versions
| PHP version               | 5.6
| MISP version / git hash   | 2.4.118
| Browser                   | NA

### Expected behavior

For a given correlated attribute in an object, only one instance of a specific Related Event Reference/Link should be listed in the "Related Events" for that attribute.

### Actual behavior

Each correlated attribute lists multiple copies of every Related Event Reference/Link instance in another event.  If a given Event has 1,000 correlations to that attribute, 1000 copies of the same Event ID will be listed in the Related Event ID column.

Note that creates extreme performance impacts on ingesting Events with multiple embedded objects containing multiple instance of an attribute with the object.

For example, an Event that contains many embedded Botnet objects that contain different metadata for all attributes, but contain the same "Botnet Attribution" 

### Steps to reproduce the behavior

Create two events containing multiple objects containing the same values for a correlated attribute.

### Logs, screenshots, configuration dump, ...

![Snag_1c402ddd](https://user-images.githubusercontent.com/3220193/69394670-adea2b80-0caa-11ea-866a-ddc8a457f0a0.png)

![Snag_1c5f827f](https://user-images.githubusercontent.com/3220193/69396187-75991c00-0caf-11ea-8d53-6e6f09bf9673.png)

**Comment by iglocska** [comment]
Makes sense, thanks.
