### ISSUE TITLE
Log or alert on memory exhaustion

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#543]
I was reviewing the log of a big MISP instance, and I saw the following error:

    [Tue Jun 09 23:33:44 2015] [error] [client 1.2.3.4] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 46283535 bytes) in /var/www/MISP/app/Lib/Tools/XMLConverterTool.php on line 11

It would be good to log in the audit logs and/or alert members of the admin group that such an error occured.

**Comment by mgeorgy** [comment]
Not a global fix but one that worked for my install is increasing PHP's maximum allowed memory.

[on Ubuntu 14.04 LTS with Apache2]
- edit /etc/php5/apache2/php.ini
- update memory_limit = 128M with memory_limit = 256M
- restart apache

**Comment by Rafiot** [comment]
Recommendations in server settings now.
