### ISSUE TITLE
Schema status inconsistent after updating to 2.4.118

### ISSUE THREAD

**Issue by ostefano** [MISP/MISP#5432]
I have just updated using the UI to the following version: v2.4.118 (21c25f60c2f70376ad6c0ea58a8fbb0c4bbf9d37)

As a result (and for the first time) the schema status became inconsistent. What it's actually interesting is that the schema version expected seems to be an older version of the one that actually is installed. I wonder whether the master branch is not aligned after all?

![Screenshot 2019-11-28 at 11 03 00](https://user-images.githubusercontent.com/979520/69801612-8aa20d80-11cf-11ea-86b2-c4ae5e184739.png)

**Comment by iglocska** [comment]
Don't worry about it - it's all good. We need to work on this feature on our end, right now it's a bit overtly alarmist. Expect more refinemenets to the tool soon!

**Comment by ostefano** [comment]
Got it, thanks for the info @iglocska . Shall I close the issue?

**Comment by iglocska** [comment]
yep, your instnace looks clean, so all good, I'll close it :)
