### ISSUE TITLE
Critical warning! The MISP database seems to be in an inconsistent state. Immediate attention is required

### ISSUE THREAD

**Issue by Cebulek** [MISP/MISP#5437]
Hi,

After update MISP to version  v2.4.118 i recive:  

Ubuntu 16.04
PHP extension version: 3.1.6
Redis version: 4.0.9

Critical warning! The MISP database seems to be in an inconsistent state. Immediate attention is required.
⚠ This diagnostic tool is in experimental state - the highlighted issues may be benign. If you are unsure, please open an issue on with the issues identified over at https://github.com/MISP/MISP for clarification.

![base](https://user-images.githubusercontent.com/58330745/69865703-3fa4fa80-12a2-11ea-9fed-3c5ddb08d54f.PNG)

**Comment by mik5z** [comment]
My MISP instance produced exactly the same error after updating to  v2.4.118 (ca484ae1dc5eb650b615d0b3ea661d5b204e020c)

**Comment by iglocska** [comment]
Please ignore it, it's a bit of overzealous reporting from our side, your DBs are fine :) 

We'll be rolling out a fix later today that should be a bit more clear about its findings.

**Comment by Cebulek** [comment]
Thanks for this info.
Regards.
