### ISSUE TITLE
[2.4.118] Critical warning! The MISP database seems to be in an inconsistent state. Immediate attention is required.

### ISSUE THREAD

**Issue by Knoxpix** [MISP/MISP#5440]
After update i found this issue. How can i fix this issue

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Request
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.3
| MISP version / git hash   | 2.4.118 (be8201a2364f767a10138ffc54e90bfe25b3b504) 
| Browser                   | Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/5124273/69935266-ea1d5780-1506-11ea-8695-84998748f613.png)

**Comment by iglocska** [comment]
The message is a bit overly alarmist, update to the latest version and it will only warn you about things that should really be changed. Your DB looks fine the disable_correlation issue should be changed but it's not critical at all.

When you update to the latest version it will propose an SQL query to fix the issue.
