### ISSUE TITLE
Database schema diagnostic: False Positive status

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5441]
Hey,

Looks like there is a small bug in the Database schema diagnostic. There is some error with the single quote when parsing the result. If you check my screenshot, it appears that my default values are between single quotes, but if I check in mariadb, all is fine:

>   MariaDB [misp]> show columns from galaxies;
> +------------------+--------------+------+-----+---------+----------------+
> | Field            | Type         | Null | Key | Default | Extra          |
> +------------------+--------------+------+-----+---------+----------------+
> | id               | int(11)      | NO   | PRI | NULL    | auto_increment |
> | uuid             | varchar(255) | NO   | MUL | NULL    |                |
> | name             | varchar(255) | NO   | MUL | NULL    |                |
> | type             | varchar(255) | NO   | MUL | NULL    |                |
> | description      | text         | NO   |     | NULL    |                |
> | version          | varchar(255) | NO   |     | NULL    |                |
> | icon             | varchar(255) | NO   |     | NULL    |                |
> | namespace        | varchar(255) | NO   | MUL | misp    |                |
> | kill_chain_order | text         | YES  |     | NULL    |                |
> +------------------+--------------+------+-----+---------+----------------+
> 9 rows in set (0.001 sec)
> 
> MariaDB [misp]> 

So it could generate some confusion.

Best regards,

![status](https://user-images.githubusercontent.com/11160904/70044347-79d40c00-15c2-11ea-99cd-bd42b60d0058.png)

**Comment by iglocska** [comment]
ping @mokaddem

**Comment by mokaddem** [comment]
I also saw it on another instance.. Maybe we are being to strict on how we compare...
What is your MySQL version?

**Comment by FafnerKeyZee** [comment]
It's, Server version: 10.3.18-MariaDB-0+deb10u1 Debian 10
And it looks that since 10.2, we could have this issue...
