### ISSUE TITLE
Add attribute: eppn

### ISSUE THREAD

**Issue by pettai** [MISP/MISP#5448]
**Is your feature request related to a problem? Please describe.**
I'd like to add a new attribute for stolen digital identities in the higher education world, known as EPPN (EduPersonPricincipalName). And since everybody in the higher education world working with SSO and/or Security knows what a EPPN is, it would help to have a dedicated / standardized attribute for this data.

You could read about it in this thread or Google on "Shibboleth + EPPN" :)
https://shibboleth.1660669.n2.nabble.com/EPPN-and-eduPersonTargetedID-td7606266.html 

**Describe the solution you'd like**
Add new attribute "eppn" which should accept email-like input. 
(A valid EPPN is userid@realm format)

**Describe alternatives you've considered**
While it looks like an email address, EPPN != e-mail address.
EPPN is a unique attribute which is the basis for SSO (attribute exported by the IdP to the SP), and not used for email (which is what the "mail" attribute is for).
There are also other attributes/objects like uid, username, etc, but using one of those will just be confusing and you would most likely get a lot of mixed/wrong data then searching specifically for eppn.

**Comment by adulau** [comment]
Thank you for the proposal. It's now in the HEAD.
