### ISSUE TITLE
[decay:simulation] Simulating an ObjectAttribute does not work

### ISSUE THREAD

**Issue by mokaddem** [MISP/MISP#5449]
Simulating an ObjectAttribute does not work. The function used to fetch the Attribute alone does not allow returning an ObjectAttribute. Perhaps due to missing parameter.

**Comment by iglocska** [comment]
'flatten' => 1 ;)

**Comment by mokaddem** [comment]
Exactly. I have to change the function fetching the Attribute in the simulation page to use this parameter.
