### ISSUE TITLE
Add to diagnostics and/or admin tools for tables in innodb

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#545]
In https://github.com/MISP/MISP/commit/25e2a4e44f6448c6ce16d9249bb1a698bcebd46f#diff-fbad1855493e034de72558b403234fa5 a number of tables have been converted from MyISAM to InnoDB.

For legacy systems being upgraded and not installed form scratch, having a diagnostic showing that some tables (at least the most critical ones) are using MyISAM engine instead of InnoDB.

An admin tool to do the conversion could also be nice.

**Comment by adulau** [comment]
The majority of MISPs are now InnoDB. We haven't seen a significant number of requests regarding MySQL admin tooling.
