### ISSUE TITLE
Database schema diagnostic: Tables not found?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#5455]
I just upgraded to 2.4.119 and I'd like to test the database diagnostic feature.
It reports that **all** tables are missing!? (but MISP is working :-)
Any idea?
`

Table name | Description | Expected schema | Actual schema |  
-- | -- | -- | -- | --
admin_settings
Table `admin_settings` does not exist |  
attribute_tags
Table `attribute_tags` does not exist |  
attributes
Table `attributes` does not exist |  
bruteforces
Table `bruteforces` does not exist |  
cake_sessions
Table `cake_sessions` does not exist |  
correlations
Table `correlations` does not exist |  
decaying_model_mappings
Table `decaying_model_mappings` does not exist |  
decaying_models
Table `decaying_models` does not exist |  
event_blacklists
Table `event_blacklists` does not exist |  
event_delegations
Table `event_delegations` does not exist

`

**Comment by iglocska** [comment]
What the hell! How old of a version did you update from?

Run clean caches in the diagnostics page, just in case

**Comment by xme** [comment]
Caches cleared and same issue...
I've no idea... just upgrading my MISP instance when new versions are released...

**Comment by iglocska** [comment]
That obviously sounds like the tool is broken, you'd notice if the attributes table was missing... 😉 Are you coming to the belgomisp Meetup in Friday? We could have a look there if all else fails.

**Comment by xme** [comment]
Strange... My MISP is running fine :)
I *should* be present. I'll visit a customer far from Brussels and hope to be on time for the meetup... :-(

**Comment by xme** [comment]
I also found that the SQL database status was wrong (table columns was empty). This is due to this line:
in /app/model/Server.php: (line 5763). I changed to this:

`$temp[0]['table'] = $temp['tables']['TABLE_NAME'];
`

My field name is in upper case (maybe because I'm using MariaDB?)

It's the same problem here: (line 4508):

`$tables = HASH::extract($sqlResult, '{n}.tables.TABLE_NAME');
`

It's not perfect but that's clearly the source of the problem!

**Comment by mokaddem** [comment]
Oh! That's interesting, I honestly did not expect the name to change depending on the version..
I'll force it to be lower case.

**Comment by SteveClement** [comment]
@mokaddem to be closed?

**Comment by mokaddem** [comment]
Should be indeed. Please re-open if it's not the case. Thanks!
