### ISSUE TITLE
Add support for REST search on object controller

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5456]
2.4.118

How does one search for `MISPObjects` via the WebUI `REST client` or with `PyMISP`?

1.  So far, the only method I got to work is click through on `Download as...` on an event with objects. However, I need to automate retrieving object content via `PyMISP` to send to downstream systems.

2. It appears that the attributes within an object are not found when searching with the attributes controller. I tried this with no results via `pymisp.search` and the WebUI `REST client`.

2. The `REST client` WebUI page does not have `objects` as a choice under `attributes` in the `Query Builder` template menu. However, I if change the `Relative path to query` to be `/objects/restSearch` I get this error:
```
{"name":"Not Found","message":"Not Found","url":"\/objects\/restSearch"}
```

3. When I try `pymisp.search(controller='objects', ...)` I get this error:
```
{'errors': (405, {'name': 'You do not have permission to use this functionality.',
'message': 'You do not have permission to use this functionality.',
'url': '/objects/restSearch'})};
```

**Comment by github-germ** [comment]
Related to https://github.com/MISP/PyMISP/issues/254

**Comment by github-germ** [comment]
I hope I am missing something in my tests for retrieving objects. Bring on the magic... If they are available only via the WebUI export, then we will have to go to flat attributes and loose all the context relationships :-(

**Comment by Rafiot** [comment]
Querying the object controller *is not supported* at all, so this request won't work. In PyMISP, you should have an exception, I'll fix that.

**Comment by github-germ** [comment]
> Querying the object controller _is not supported_ at all

@Rafiot, Thx for the reply.

Does this mean that my observations that neither PyMISP nor REST client can retrieve `MISPObjects` stored in MISP, and the only method to pull objects is via the WebUI, i.e. no automated methods currently?

Knowing this answer will help direct our ingestion processes, as although we really do need the relationship context offered by objects, if they cannot be retrieved, we will postpone their use. Is this support on the roadmap for future features?

Thanks!!

**Comment by Rafiot** [comment]
The only thing that isn't supported is searching specifically for objects. You can get, add, update, and delete objects using the API: https://github.com/MISP/PyMISP/blob/master/pymisp/aping.py#L270

Regarding the roadmap, maybe beginning of Q2 2020? Again, we welcome PR, and contributions to speedup specific features.

**Comment by github-germ** [comment]
@Rafiot -- We are planning our future dev roadmap and just wanted to check back to see if you have a new ETA on adding REST search support for objects. Many thanks!!

**Comment by Rafiot** [comment]
yes, it will be implemented as soon as I find the time.

Funding or even better, pull requests, are always welcome.

**Comment by chrisinmtown** [comment]
@github-germ what is the requirement here? To find objects specifically (not the attributes they contain)? To limit a search to attributes within a specific object-attribute collection?  Or just to find any attributes, whether they are at the top level or nested with any object-attribute collection?

@Rafiot if you can please give a design for this, or possibly explain exactly which files must be extended, I may be able to contribute.

**Comment by JakubOnderka** [comment]
@Rafiot It should be supported on MISP side, see https://github.com/MISP/MISP/blob/693ef171c387872ebf7d0ae86a2ee1c8180f6fd0/app/Model/MispObject.php#L1324

Maybe just documentation and implementation on PyMISP side is missing?

**Comment by github-germ** [comment]
I hadn't tried accessing objects since May since this issue wasn't updated. I am happy to report that it appears that `pymisp.search` is now returning a `MISPObject` list with both the `events` and `objects` controllers. And the `attributes` controller returns a list of `MISPObjectAtribute`.

Wonder what MISP release added this support.

Many Thanks!!

**Comment by chrisinmtown** [comment]
So can this be closed Mitch?  It would be useful to add some documentation to the search() method, I'll be glad to contribute that if you suggest some aspects.

**Comment by github-germ** [comment]
I will close. Thx.

I am still curious to learn how I missed this getting supported. Perhaps I can do better when reading the changelog?

**Comment by iglocska** [comment]
> I will close. Thx.
> 
> I am still curious to learn how I missed this getting supported. Perhaps I can do better when reading the changelog?

Not sure either, think it was more of a bug-fix than a new feature though, so it might not have gotten the spotlight it probably deserved in the blog posts.
