### ISSUE TITLE
Upgrade from 2.4.118 to 2.4.119 database schema errors

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#5457]
I just updated to 2.4.119 from .118, ran the diagnotics and got a LOT of database schema errors.
Running on RHEL7.
Cleaned the model cache. no affect
Restarted the host after upgrade

Table name | Description | Expected schema | Actual schema |  
-- | -- | -- | -- | --
attributes
Column `object_relation` is different | object_relation YES varchar 255 utf8_bin | object_relation YES varchar 255 utf8_bin NULL |  
Column `comment` is different | comment YES text 65535 utf8_bin | comment YES text 65535 utf8_bin NULL |  
cake_sessions
Column `id` is different | id NO varchar 255 utf8_bin | id NO varchar 255 utf8_bin '' |  
decaying_models
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
Column `parameters` is different | parameters YES text 65535 utf8_general_ci | parameters YES text 65535 utf8_general_ci NULL |  
Column `attribute_types` is different | attribute_types YES text 65535 utf8_general_ci | attribute_types YES text 65535 utf8_general_ci NULL |  
Column `description` is different | description YES text 65535 utf8_general_ci | description YES text 65535 utf8_general_ci NULL |  
Column `org_id` is different | org_id YES int 10 | org_id YES int 10 NULL |  
Column `ref` is different | ref YES text 65535 utf8_unicode_ci | ref YES text 65535 utf8_unicode_ci NULL |  
Column `version` is different | version NO varchar 255 utf8_bin | version NO varchar 255 utf8_bin '' |  
event_blacklists
Column `comment` is different | comment YES text 65535 utf8_unicode_ci | comment YES text 65535 utf8_unicode_ci NULL |  
event_delegations
Column `message` is different | message YES text 65535 utf8_general_ci | message YES text 65535 utf8_general_ci NULL |  
Column `sharing_group_id` is different | sharing_group_id YES int 10 | sharing_group_id YES int 10 NULL |  
event_graph
Column `network_name` is different | network_name YES varchar 255 utf8_unicode_ci | network_name YES varchar 255 utf8_unicode_ci NULL |  
Column `preview_img` is different | preview_img YES mediumtext 16777215 utf8_general_ci | preview_img YES mediumtext 16777215 utf8_general_ci NULL |  
events
Column `extends_uuid` is different | extends_uuid YES varchar 40 utf8_bin | extends_uuid YES varchar 40 utf8_bin '' |  
feeds
Column `rules` is different | rules YES text 65535 utf8_bin | rules YES text 65535 utf8_bin NULL |  
Column `source_format` is different | source_format YES varchar 255 utf8_bin misp | source_format YES varchar 255 utf8_bin 'misp' |  
Column `settings` is different | settings YES text 65535 utf8_general_ci | settings YES text 65535 utf8_general_ci NULL |  
Column `input_source` is different | input_source NO varchar 255 utf8_bin network | input_source NO varchar 255 utf8_bin 'network' |  
Column `headers` is different | headers YES text 65535 utf8_bin | headers YES text 65535 utf8_bin NULL |  
galaxies
Column `name` is different | name NO varchar 255 utf8_bin | name NO varchar 255 utf8_bin '' |  
Column `icon` is different | icon NO varchar 255 utf8_bin | icon NO varchar 255 utf8_bin '' |  
Column `namespace` is different | namespace NO varchar 255 utf8_unicode_ci misp | namespace NO varchar 255 utf8_unicode_ci 'misp' |  
Column `kill_chain_order` is different | kill_chain_order YES text 65535 utf8_bin | kill_chain_order YES text 65535 utf8_bin NULL |  
galaxy_clusters
Column `tag_name` is different | tag_name NO varchar 255 utf8_bin | tag_name NO varchar 255 utf8_bin '' |  
Column `source` is different | source NO varchar 255 utf8_bin | source NO varchar 255 utf8_bin '' |  
Column `uuid` is different | uuid NO varchar 255 utf8_bin | uuid NO varchar 255 utf8_bin '' |  
galaxy_elements
Column `key` is different | key NO varchar 255 utf8_bin | key NO varchar 255 utf8_bin '' |  
jobs
Column `process_id` is different | process_id YES varchar 32 utf8_bin | process_id YES varchar 32 utf8_bin NULL |  
logs
Column `title` is different | title YES text 65535 utf8_bin | title YES text 65535 utf8_bin NULL |  
Column `change` is different | change YES text 65535 utf8_bin | change YES text 65535 utf8_bin NULL |  
Column `email` is different | email NO varchar 255 utf8_bin | email NO varchar 255 utf8_bin '' |  
Column `org` is different | org NO varchar 255 utf8_bin | org NO varchar 255 utf8_bin '' |  
Column `description` is different | description YES text 65535 utf8_bin | description YES text 65535 utf8_bin NULL |  
Column `ip` is different | ip NO varchar 45 utf8_bin | ip NO varchar 45 utf8_bin '' |  
noticelists
Column `ref` is different | ref YES text 65535 utf8_unicode_ci | ref YES text 65535 utf8_unicode_ci NULL |  
Column `geographical_area` is different | geographical_area YES varchar 255 utf8_unicode_ci | geographical_area YES varchar 255 utf8_unicode_ci NULL |  
object_references
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
Column `source_uuid` is different | source_uuid YES varchar 40 utf8_bin | source_uuid YES varchar 40 utf8_bin NULL |  
Column `referenced_uuid` is different | referenced_uuid YES varchar 40 utf8_bin | referenced_uuid YES varchar 40 utf8_bin NULL |  
Column `relationship_type` is different | relationship_type YES varchar 255 utf8_unicode_ci | relationship_type YES varchar 255 utf8_unicode_ci NULL |  
object_relationships
Column `name` is different | name YES varchar 255 utf8_unicode_ci | name YES varchar 255 utf8_unicode_ci NULL |  
object_template_elements
Column `object_relation` is different | object_relation YES varchar 255 utf8_bin | object_relation YES varchar 255 utf8_bin NULL |  
Column `type` is different | type YES varchar 255 utf8_bin | type YES varchar 255 utf8_bin NULL |  
Column `categories` is different | categories YES text 65535 utf8_bin | categories YES text 65535 utf8_bin NULL |  
Column `sane_default` is different | sane_default YES text 65535 utf8_bin | sane_default YES text 65535 utf8_bin NULL |  
Column `values_list` is different | values_list YES text 65535 utf8_bin | values_list YES text 65535 utf8_bin NULL |  
Column `description` is different | description YES text 65535 utf8_bin | description YES text 65535 utf8_bin NULL |  
Column `disable_correlation` is different | disable_correlation YES tinyint 3 | disable_correlation YES tinyint 3 NULL |  
object_templates
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
Column `name` is different | name YES varchar 255 utf8_unicode_ci | name YES varchar 255 utf8_unicode_ci NULL |  
Column `meta-category` is different | meta-category YES varchar 255 utf8_unicode_ci | meta-category YES varchar 255 utf8_unicode_ci NULL |  
Column `description` is different | description YES text 65535 utf8_bin | description YES text 65535 utf8_bin NULL |  
Column `requirements` is different | requirements YES text 65535 utf8_bin | requirements YES text 65535 utf8_bin NULL |  
objects
Column `name` is different | name YES varchar 255 utf8_unicode_ci | name YES varchar 255 utf8_unicode_ci NULL |  
Column `meta-category` is different | meta-category YES varchar 255 utf8_unicode_ci | meta-category YES varchar 255 utf8_unicode_ci NULL |  
Column `description` is different | description YES text 65535 utf8_unicode_ci | description YES text 65535 utf8_unicode_ci NULL |  
Column `template_uuid` is different | template_uuid YES varchar 40 utf8_bin | template_uuid YES varchar 40 utf8_bin NULL |  
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
Column `sharing_group_id` is different | sharing_group_id YES int 10 | sharing_group_id YES int 10 NULL |  
organisations
Column `description` is different | description YES text 65535 utf8_unicode_ci | description YES text 65535 utf8_unicode_ci NULL |  
Column `type` is different | type YES varchar 255 utf8_unicode_ci | type YES varchar 255 utf8_unicode_ci NULL |  
Column `nationality` is different | nationality YES varchar 255 utf8_unicode_ci | nationality YES varchar 255 utf8_unicode_ci NULL |  
Column `sector` is different | sector YES varchar 255 utf8_unicode_ci | sector YES varchar 255 utf8_unicode_ci NULL |  
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
Column `contacts` is different | contacts YES text 65535 utf8_unicode_ci | contacts YES text 65535 utf8_unicode_ci NULL |  
Column `restricted_to_domain` is different | restricted_to_domain YES text 65535 utf8_bin | restricted_to_domain YES text 65535 utf8_bin NULL |  
Column `landingpage` is different | landingpage YES text 65535 utf8_unicode_ci | landingpage YES text 65535 utf8_unicode_ci NULL |  
regexp
Column `type` is different | type NO varchar 100 utf8_bin ALL | type NO varchar 100 utf8_bin 'ALL' |  
rest_client_histories
Column `headers` is different | headers YES text 65535 utf8_general_ci | headers YES text 65535 utf8_general_ci NULL |  
Column `body` is different | body YES text 65535 utf8_general_ci | body YES text 65535 utf8_general_ci NULL |  
Column `url` is different | url YES text 65535 utf8_general_ci | url YES text 65535 utf8_general_ci NULL |  
Column `http_method` is different | http_method YES varchar 255 utf8_general_ci | http_method YES varchar 255 utf8_general_ci NULL |  
Column `bookmark_name` is different | bookmark_name YES varchar 255 utf8_general_ci | bookmark_name YES varchar 255 utf8_general_ci '' |  
roles
Column `created` is different | created YES datetime | created YES datetime NULL |  
Column `modified` is different | modified YES datetime | modified YES datetime NULL |  
Column `perm_add` is different | perm_add YES tinyint 3 | perm_add YES tinyint 3 NULL |  
Column `perm_modify` is different | perm_modify YES tinyint 3 | perm_modify YES tinyint 3 NULL |  
Column `perm_modify_org` is different | perm_modify_org YES tinyint 3 | perm_modify_org YES tinyint 3 NULL |  
Column `perm_publish` is different | perm_publish YES tinyint 3 | perm_publish YES tinyint 3 NULL |  
Column `perm_sync` is different | perm_sync YES tinyint 3 | perm_sync YES tinyint 3 NULL |  
Column `perm_admin` is different | perm_admin YES tinyint 3 | perm_admin YES tinyint 3 NULL |  
Column `perm_audit` is different | perm_audit YES tinyint 3 | perm_audit YES tinyint 3 NULL |  
Column `perm_full` is different | perm_full YES tinyint 3 | perm_full YES tinyint 3 NULL |  
Column `memory_limit` is different | memory_limit YES varchar 255 utf8_bin | memory_limit YES varchar 255 utf8_bin '' |  
Column `max_execution_time` is different | max_execution_time YES varchar 255 utf8_bin | max_execution_time YES varchar 255 utf8_bin '' |  
servers
Column `lastpulledid` is different | lastpulledid YES int 10 | lastpulledid YES int 10 NULL |  
Column `lastpushedid` is different | lastpushedid YES int 10 | lastpushedid YES int 10 NULL |  
Column `organization` is different | organization YES varchar 10 utf8_bin | organization YES varchar 10 utf8_bin NULL |  
Column `cert_file` is different | cert_file YES varchar 255 utf8_bin | cert_file YES varchar 255 utf8_bin NULL |  
Column `client_cert_file` is different | client_cert_file YES varchar 255 utf8_bin | client_cert_file YES varchar 255 utf8_bin NULL |  
shadow_attribute_correlations
Column `sharing_group_id` is different | sharing_group_id YES int 10 | sharing_group_id YES int 10 NULL |  
Column `a_sharing_group_id` is different | a_sharing_group_id YES int 10 | a_sharing_group_id YES int 10 NULL |  
shadow_attributes
Column `value1` is different | value1 YES text 65535 utf8_bin | value1 YES text 65535 utf8_bin NULL |  
Column `value2` is different | value2 YES text 65535 utf8_bin | value2 YES text 65535 utf8_bin NULL |  
Column `email` is different | email YES varchar 255 utf8_unicode_ci | email YES varchar 255 utf8_unicode_ci NULL |  
sightingdbs
Column `description` is different | description YES text 65535 utf8mb4_general_ci | description YES text 65535 utf8mb4_general_ci NULL |  
Column `owner` is different | owner YES varchar 255 utf8mb4_general_ci | owner YES varchar 255 utf8mb4_general_ci '' |  
Column `host` is different | host YES varchar 255 utf8mb4_general_ci http://localhost | host YES varchar 255 utf8mb4_general_ci 'http://localhost' |  
Column `namespace` is different | namespace YES varchar 255 utf8mb4_general_ci | namespace YES varchar 255 utf8mb4_general_ci '' |  
sightings
Column `uuid` is different | uuid YES varchar 255 utf8_bin | uuid YES varchar 255 utf8_bin '' |  
Column `source` is different | source YES varchar 255 utf8_bin | source YES varchar 255 utf8_bin '' |  
tag_collections
Column `uuid` is different | uuid YES varchar 40 utf8_bin | uuid YES varchar 40 utf8_bin NULL |  
tags
Column `user_id` is different | user_id NO int 10 0 | user_id NO tinyint 3 0 |  
Column `numerical_value` is different | numerical_value YES int 10 | numerical_value YES int 10 NULL |  
tasks
Column `scheduled_time` is different | scheduled_time NO varchar 8 latin1_swedish_ci 6:00 | scheduled_time NO varchar 8 latin1_swedish_ci '6:00' |  
Column `process_id` is different | process_id YES varchar 32 latin1_swedish_ci | process_id YES varchar 32 latin1_swedish_ci NULL |  
taxonomy_entries
Column `expanded` is different | expanded YES text 65535 utf8_bin | expanded YES text 65535 utf8_bin NULL |  
Column `colour` is different | colour YES varchar 7 utf8_bin | colour YES varchar 7 utf8_bin NULL |  
Column `description` is different | description YES text 65535 utf8_bin | description YES text 65535 utf8_bin NULL |  
Column `numerical_value` is different | numerical_value YES int 10 | numerical_value YES int 10 NULL |  
taxonomy_predicates
Column `expanded` is different | expanded YES text 65535 utf8_bin | expanded YES text 65535 utf8_bin NULL |  
Column `colour` is different | colour YES varchar 7 utf8_bin | colour YES varchar 7 utf8_bin NULL |  
Column `description` is different | description YES text 65535 utf8_bin | description YES text 65535 utf8_bin NULL |  
Column `numerical_value` is different | numerical_value YES int 10 | numerical_value YES int 10 NULL |  
threat_levels
Column `description` is different | description YES varchar 255 latin1_swedish_ci | description YES varchar 255 latin1_swedish_ci NULL |  
users
Column `authkey` is different | authkey YES varchar 40 utf8_bin | authkey YES varchar 40 utf8_bin NULL |  
Column `gpgkey` is different | gpgkey YES longtext 4294967295 utf8_bin | gpgkey YES longtext 4294967295 utf8_bin NULL |  
Column `certif_public` is different | certif_public YES longtext 4294967295 utf8_bin | certif_public YES longtext 4294967295 utf8_bin NULL |  
Column `expiration` is different | expiration YES datetime | expiration YES datetime NULL |  
Column `date_created` is different | date_created YES bigint 19 | date_created YES bigint 19 NULL |  
Column `date_modified` is different | date_modified YES bigint 19 | date_modified YES bigint 19 NULL |  
warninglists
Column `type` is different | type NO varchar 255 utf8_bin string | type NO varchar 255 utf8_bin 'string' |  
Column `warninglist_entry_count` is different | warninglist_entry_count YES int 10 | warninglist_entry_count YES int 10 NULL

**Comment by iglocska** [comment]
Interesting, it looks like your DB reports the current state slightly differently (note the quotation marks). 

@mokaddem - could you have a look?

**Comment by otgrkiss** [comment]
We are having the same error. Cent OS 7 and Maria DB

**Comment by RichieB2B** [comment]
I'm experiencing the same issue on CentOS 7. The DB report seems to not see the default NULL values:
```
MariaDB [misp]> describe objects;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| name             | varchar(255) | YES  | MUL | NULL    |                |
| meta-category    | varchar(255) | YES  | MUL | NULL    |                |
| description      | text         | YES  |     | NULL    |                |
| template_uuid    | varchar(40)  | YES  | MUL | NULL    |                |
| template_version | int(11)      | NO   | MUL | NULL    |                |
| event_id         | int(11)      | NO   | MUL | NULL    |                |
| uuid             | varchar(40)  | YES  | MUL | NULL    |                |
| timestamp        | int(11)      | NO   | MUL | 0       |                |
| distribution     | tinyint(4)   | NO   | MUL | 0       |                |
| sharing_group_id | int(11)      | YES  | MUL | NULL    |                |
| comment          | text         | NO   |     | NULL    |                |
| deleted          | tinyint(1)   | NO   |     | 0       |                |
+------------------+--------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)
```

<img width="1301" alt="Screenshot 2020-01-07 11 57 43" src="https://user-images.githubusercontent.com/1461970/71890606-f3709400-3144-11ea-9841-fa4c655b8393.png">

**Comment by SteveClement** [comment]
@mokaddem this good to be closed?

**Comment by jezkerwin** [comment]
What was the fix? I haven't seen a resolution.

**Comment by otgrkiss** [comment]
Have not updated yet. So I am not sure if the error is still present.
Going to check next week.

**Comment by mokaddem** [comment]
https://github.com/MISP/MISP/pull/5490 Marked NULL as being a benign error and therefore, should solve the issue. Please comment or re-open if it's not the case.
Thanks

**Comment by TaR7k1xPG84** [comment]
Hello,
I have exactly the same Database schema diagnostic situation.
So I am wondering if it is normal that this warning occurs after the fix you're mentioning in the previous messages and if it can affect the MISP server?
My MISP version is v2.4.129, MariaDB version is 10.3.22 and the OS is Ubuntu Server 20.04.
Thanks for your help.

**Comment by mokaddem** [comment]
@TaR7k1xPG84 are you referring to the `NULL` warning? Would you mind posting your schema diagnostic?
Thanks

**Comment by TaR7k1xPG84** [comment]
Precisely, I'm referring to the `NULL` warning.
I attached down below a screenshot of the schema diagnostic. It does not show every row but all of them are as in the screenshot, with the `NULL` warning or the `"` warning.

![db_schema](https://user-images.githubusercontent.com/67414684/88404412-253e0500-cdce-11ea-8a14-bb1862ed956a.png)

**Comment by mokaddem** [comment]
@TaR7k1xPG84 Oh i see. You checked the `Reveal benign deltas` checkbox.
These are just artifacts because the schema used for the comparison return `null` while your DB returns `'NULL'`.
So, this is totally benign and you can safely ignore them

**Comment by TaR7k1xPG84** [comment]
Ok, perfect, thank you!
