### ISSUE TITLE
New MISP Install - Large MySQL DB

### ISSUE THREAD

**Issue by BVapid** [MISP/MISP#5458]
Hi team,

I have a new MISP server and have had issues with MySQL filling up on correlations (I actually had the server crash and had to rebuild from a snap due to this)

Running v2.4.118 on Ubuntu Server 18.04.3 LTS

I have two scheduled tasks to fetch and cache feeds every 24 hours and am wondering if this is where some of the issues are coming from?

Looking for assistance on how to stop this happening and also suggest MISP has some cleanup logic built in to stop this happening in future versions.

Current DB Contents

Table | Used | Reclaimable
-- | -- | --
admin_settings | 0.02MB | 0MB
attributes | 4631.2MB | 6MB
attribute_tags | 0.34MB | 0MB
bruteforces | 0.02MB | 0MB
cake_sessions | 0.03MB | 0MB
correlations | 30556.84MB | 4MB
decaying_models | 0.11MB | 0MB
decaying_model_mappings | 0.03MB | 0MB
events | 0.81MB | 0MB
event_blacklists | 0.05MB | 0MB
event_delegations | 0.05MB | 0MB
event_graph | 0.08MB | 0MB
event_locks | 0.06MB | 0MB
event_tags | 0.36MB | 0MB
favourite_tags | 0.05MB | 0MB
feeds | 0.06MB | 0MB
fuzzy_correlate_ssdeep | 166.81MB | 5MB
galaxies | 0.08MB | 0MB
galaxy_clusters | 9.08MB | 4MB
galaxy_elements | 8.17MB | 4MB
galaxy_reference | 0.08MB | 0MB
jobs | 0.11MB | 0MB
logs | 6653MB | 5MB
news | 0.02MB | 0MB
noticelists | 0.05MB | 0MB
noticelist_entries | 0.03MB | 0MB
notification_logs | 0.05MB | 0MB
objects | 18.95MB | 4MB
object_references | 6.31MB | 4MB
object_relationships | 0.03MB | 0MB
object_templates | 0.14MB | 0MB
object_template_elements | 0.31MB | 0MB
organisations | 0.05MB | 0MB
org_blacklists | 0.02MB | 0MB
posts | 0.05MB | 0MB
regexp | 0.02MB | 0MB
rest_client_histories | 0.06MB | 0MB
roles | 0.02MB | 0MB
servers | 0.06MB | 0MB
shadow_attributes | 0.16MB | 0MB
shadow_attribute_correlations | 0.13MB | 0MB
sharing_groups | 0.08MB | 0MB
sharing_group_orgs | 0.05MB | 0MB
sharing_group_servers | 0.05MB | 0MB
sightingdbs | 0.08MB | 0MB
sightingdb_orgs | 0.05MB | 0MB
sightings | 0.11MB | 0MB
tags | 0.27MB | 0MB
tag_collections | 0.06MB | 0MB
tag_collection_tags | 0.05MB | 0MB
tasks | 0.02MB | 0MB
taxonomies | 0.05MB | 0MB
taxonomy_entries | 1.7MB | 4MB
taxonomy_predicates | 0.16MB | 0MB
templates | 0.02MB | 0MB
template_elements | 0.02MB | 0MB
template_element_attributes | 0.02MB | 0MB
template_element_files | 0.02MB | 0MB
template_element_texts | 0.02MB | 0MB
template_tags | 0.02MB | 0MB
threads | 0.08MB | 0MB
threat_levels | 0.02MB | 0MB
users | 0.06MB | 0MB
user_settings | 0.06MB | 0MB
warninglists | 0.02MB | 0MB
warninglist_entries | 10.03MB | 4MB
warninglist_types | 0.02MB | 0MB
whitelist | 0.02MB | 0MB

**Comment by iglocska** [comment]
> I have two scheduled tasks to fetch and cache feeds every 24 hours and am wondering if this is where some of the issues are coming from?

This can definitely be the cause. Make sure that your freetext and CSV parsed feeds are configured to pull into a fixed event instead of creating a new event each time.

**Comment by BVapid** [comment]
Thankyou. I'm only using the default feeds right now and it looks like half of them are set to a new event each pull. I'll set them to a fixed event and monitor.

Does caching help here or make the situation worse? The documentation isn't clear.

**Comment by likekabin** [comment]
I have the same issue, running MISP via docker, but the performance very slow when doing search direct in search bar on MISP or event query via API, it make my MISP server crash. My server resource (Disk, RAM CPU,...) is ok. can you suggest me how to improve performance for server?

**Comment by BVapid** [comment]
> I have the same issue, running MISP via docker, but the performance very slow when doing search direct in search bar on MISP or event query via API, it make my MISP server crash. My server resource (Disk, RAM CPU,...) is ok. can you suggest me how to improve performance for server?

Is your MySQL DB filling with correlations? If not, you're not suffering the same issue ;)

**Comment by iglocska** [comment]
Caching is an alternate thing. 

Basically, pulling feeds in is absolutely fine - if you use a fixed event it will keep that event up-to date with the new data appearing in the feed whenever you pull again. This will absolutely keep your db clean and sane.

Caching means that the data is not stored locally, it will not be made available for exports, via the API or via the UI. It will however be useful if you want to immediately see that a data-point you're encoding is already known.

So to explain the 3 different scenarios:

1. Feed fetch into fixed event:
    - MISP fetches all the data from the feed
    - Creates attributes from each value and stores it in a feed
    - if "delta merge" is selected in the feed config, it will also cull attributes that are no longer in the feed
    - data is available for exports, API

2. Caching:
    - MISP will fetch all the data from the feed
    - the data is immediately hashed (each value will become a sha1 hash)
    - the hashes are stored in redis for local lookups, no event/attribute data is created
    - on the event view, we can still see if there's a correlation with a feed (we basically hash all values on the fly that we look at and check if the redis cache knows about it - if yes we get a link to the feed)

3. Pull into new event each time
    - each time a pull of the feed is initiated MISP creates a brand new event with all contents of the feed encoded as attributes
    - since most feeds retain most of their indicators between feed pulls, this means that the same data is replicated over and over into new events
    - if a feed has 1000 values, this is how each consecutive pull will affect our elements in the DB:
      pull 1 :: attributes:1000, correlations: 0
      pull 2 :: attributes:2000, correlations: 1000
      pull 3 :: attributes:3000, correlations: 3000
      pull 4 :: attributes:4000, correlations: 6000
      pull 5 :: attributes: 5000, correlations: 10000
      .... etc

**Comment by iglocska** [comment]
> I have the same issue, running MISP via docker, but the performance very slow when doing search direct in search bar on MISP or event query via API, it make my MISP server crash. My server resource (Disk, RAM CPU,...) is ok. can you suggest me how to improve performance for server?

Please open a separate issue unless it's really the same thing please ;)

**Comment by BVapid** [comment]
So even after changing all feeds to output to a fixed event the correlations has still risen overnight.

Is there any best practice to cleaning up the DB apart from dumping the while table and starting again? This is basically a clean install.


Table | Used | Reclaimable
-- | -- | --
admin_settings | 0.02MB | 0MB
attributes | 5965.47MB | 5MB
attribute_tags | 0.34MB | 0MB
bruteforces | 0.02MB | 0MB
cake_sessions | 0.03MB | 0MB
correlations | 54868.84MB | 6MB
decaying_models | 0.11MB | 0MB
decaying_model_mappings | 0.03MB | 0MB
events | 0.81MB | 0MB
event_blacklists | 0.05MB | 0MB
event_delegations | 0.05MB | 0MB
event_graph | 0.08MB | 0MB
event_locks | 0.06MB | 0MB
event_tags | 0.36MB | 0MB
favourite_tags | 0.05MB | 0MB
feeds | 0.06MB | 0MB
fuzzy_correlate_ssdeep | 166.81MB | 5MB
galaxies | 0.08MB | 0MB
galaxy_clusters | 9.08MB | 4MB
galaxy_elements | 8.17MB | 4MB
galaxy_reference | 0.08MB | 0MB
jobs | 0.13MB | 0MB
logs | 8219MB | 4MB
news | 0.02MB | 0MB
noticelists | 0.05MB | 0MB
noticelist_entries | 0.03MB | 0MB
notification_logs | 0.05MB | 0MB
objects | 18.95MB | 4MB
object_references | 6.31MB | 4MB
object_relationships | 0.03MB | 0MB
object_templates | 0.14MB | 0MB
object_template_elements | 0.33MB | 0MB
organisations | 0.05MB | 0MB
org_blacklists | 0.02MB | 0MB
posts | 0.05MB | 0MB
regexp | 0.02MB | 0MB
rest_client_histories | 0.06MB | 0MB
roles | 0.02MB | 0MB
servers | 0.06MB | 0MB
shadow_attributes | 0.16MB | 0MB
shadow_attribute_correlations | 0.13MB | 0MB
sharing_groups | 0.08MB | 0MB
sharing_group_orgs | 0.05MB | 0MB
sharing_group_servers | 0.05MB | 0MB
sightingdbs | 0.08MB | 0MB
sightingdb_orgs | 0.05MB | 0MB
sightings | 0.11MB | 0MB
tags | 0.27MB | 0MB
tag_collections | 0.06MB | 0MB
tag_collection_tags | 0.05MB | 0MB
tasks | 0.02MB | 0MB
taxonomies | 0.05MB | 0MB
taxonomy_entries | 1.7MB | 4MB
taxonomy_predicates | 0.16MB | 0MB
templates | 0.02MB | 0MB
template_elements | 0.02MB | 0MB
template_element_attributes | 0.02MB | 0MB
template_element_files | 0.02MB | 0MB
template_element_texts | 0.02MB | 0MB
template_tags | 0.02MB | 0MB
threads | 0.08MB | 0MB
threat_levels | 0.02MB | 0MB
users | 0.06MB | 0MB
user_settings | 0.06MB | 0MB
warninglists | 0.02MB | 0MB
warninglist_entries | 10.03MB | 4MB
warninglist_types | 0.02MB | 0MB
whitelist | 0.02MB | 0MB

**Comment by iglocska** [comment]
OK, first of all, it sounds like you're still ingesting data from feeds that are not set to fixed event as target.

Step 1: ensure that all your CSV/freetext source_format feeds are using the fixed event setting. If you want to make sure this is the case, you can run this SQL query instead of doing it manually:

```
UPDATE feeds SET fixed_event = 1 WHERE source_format="csv" OR source_format="freetext";
```

Step 2: purge all of your correlations (this will make the next steps much faster), for which you have two methods at your disposal:
  - either go to your administration -> server settings -> MISP tab and set `MISP.completely_disable_correlation` to true
  - via MYSQL run `TRUNCATE correlations;`

Step 3: purge all of your feed data that have been pulled into multiple events. The easiest way of doing this: check which feeds are enabled (ignore misp source format feeds, they are not causing issues) and note down the IDs. Afterwards, use the CLI cleanup tool to remove all the feed events:

`/var/www/MISP/app/Console/cake Admin purgeFeedEvents [user_id] [feed_id]`

Execute this for each feed that you had enabled, replacing user_id with your admin user's ID and feed_id with the individual feed IDs on your list.

Step 4: recorrelate your data, depending on which method you've used in Step 2 you have two options:
  - either go to your administration -> server settings -> MISP tab and set `MISP.completely_disable_correlation` to false
  - recorrelate your current data-set via the recorrelate attributes tool on `/pages/display/administration`

**Comment by enjeck** [comment]
@BVapid Hey. Did you eventually resolve this issue?
