### ISSUE TITLE
403 forbidden when using misp.upload_stix() using all types of accounts

### ISSUE THREAD

**Issue by criptk** [MISP/MISP#5465]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       |  Jupyter (python)
| PHP version               | 7.0
| MISP version / git hash   | 2.4 (dfbb94efba3f83dc89b8583dc412c0872643ec36)
| Browser                   | PyMISP

### Logs, screenshots, configuration dump, ...

This is exactly what i am doing 
----
from pymisp import ExpandedPyMISP
import argparse
import os
import urllib3
import requests
from logging.handlers import RotatingFileHandler

misp_url = 'https://x.x.x.x/'
misp_key = '<SECRET>'
misp_verifycert = False
misp_client_cert = ''

misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=misp_client_cert)
response = misp.upload_stix("./2c820bcefc45d0883343fe8a4c5beabf.json", version=2)
print(response)
------

And i always get 403, looking at apache logs:
172.17.54.66 - - [12/Dec/2019:13:09:49 -0800] "POST /events/upload_stix/2 HTTP/1.1" 403 4604 "-" "PyMISP 2.4.119 - Python 3.6"
172.17.54.66 - - [12/Dec/2019:13:13:49 -0800] "POST /events/upload_stix/2 HTTP/1.1" 403 4604 "-" "PyMISP 2.4.119 - Python 3.6"

**Comment by chrisr3d** [comment]
I just tested on my side, and I have no way to reproduce, it works for me, can you by any chance share a sample of what you are trying to import ?

**Comment by criptk** [comment]
Sure, follows.

I have tried with other stix2 jsons , all yield the same result
[2c820bcefc45d0883343fe8a4c5beabf.json.zip](https://github.com/MISP/MISP/files/3962614/2c820bcefc45d0883343fe8a4c5beabf.json.zip)

**Comment by criptk** [comment]
I think it might be the same issue as this
https://github.com/MISP/MISP/issues/3986

You said the the stix2 library is somewhat not the one it should be ..

**Comment by criptk** [comment]
Just updated misp to the latest version but having the same issue, will try the building of stix lib from scratch like #3986

**Comment by chrisr3d** [comment]
I see there is something going wrong, I will have a look and let you know when it is fixed

**Comment by chrisr3d** [comment]
832a5fb should have fixed the issue, at least for the sample you gave me.
Let me know if you still ave any issue

**Comment by criptk** [comment]
It works ! thank you
