### ISSUE TITLE
Critical error when setting MISP.disable_emailing = True

### ISSUE THREAD

**Issue by bowserkn** [MISP/MISP#5468]
I don't want/need MISP to send emails, but when I try to set MISP.disable_emailing = True, I get this result "Critical settings incorrectly or not set | 1 incorrect settings. | MISP will not operate correctly or will be unsecure until these issues are resolved." in Server Settings & Maintenance. Please advise, thank you.

**Comment by SteveClement** [comment]
Dear

This is a bad UI/UX symptom.

You can, unfortunately, ignore it.

In version 2.5(for ever) it will be possibly maybe fixed.

Please open again if more details are needed.
