### ISSUE TITLE
REST Api Attributes rest Search by tags returns no result if Event has no attributes.

### ISSUE THREAD

**Issue by otgrkiss** [MISP/MISP#5472]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       | 7
| PHP version               | 7.3
| MISP version / git hash   | 2.4.118 - be8201a2364f767a10138ffc54e90bfe25b3b504
| Browser                   | Firefox

### Expected behavior

Rest API /events/restSearch

{
    "returnFormat": "json",
    "tags": "tlp:green"
}

returns all Events with the tag "tlp:green"

### Actual behavior

Only returns Events with attributes but not empty ones.

### Steps to reproduce the behavior

- Create empty Event with tag.
- Use the Rest Api to search for the event.
{
    "returnFormat": "json",
    "tags": "tlp:green"
}

response:

{"response": []}

**Comment by cudeso** [comment]
DB Scheme seems OK.

![2020-01-23 13_36_28-Servers - MISP](https://user-images.githubusercontent.com/256028/72985056-6cc6e280-3de5-11ea-85ff-6eca47359298.png)

**Comment by mokaddem** [comment]
Hi,
This is intended as Events are meant to be envelope around the actual data.
Do you have any use-cases in which returning empty events is useful for you?
