### ISSUE TITLE
Need help getting pydeep and lief working

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#5476]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat 7.7
| OS version (client)       | Ubuntu 18.04LTS
| PHP version               | 7.2.24 
| MISP version / git hash   | v2.4.119 (235e5a056212e95b3fac3d942489199c6b67f1d2)
| Browser                   | Chrome

### Support Questions
I'm having trouble getting MISP to "see" the pydeep amd lief modules on a new install on a Redhat 7.7 server.

I've followed the official install docs for Redhat/Centos and everything seems to install properly.

The diagnostics page lists them as not installed, but when I try loading the modules manually everything seems ok.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/28684289/71249177-de120200-231c-11ea-9695-859caf1a2362.png)

Manually loading the modules seem to work:
`[root@h1-misp ~]# su -s /bin/bash apache -c ". /var/www/MISP/venv/bin/activate; python"
Python 3.6.8 (default, Jun 11 2019, 15:15:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydeep
>>> import lief
>>> import doesnotexist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'doesnotexist'
>>> 
`

And as root:
`[root@h1-misp ~]# . /var/www/MISP/venv/bin/activate
(venv) [root@h1-misp ~]# python 
Python 3.6.8 (default, Jun 11 2019, 15:15:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydeep
>>> import lief
>>> import doesnotexist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'doesnotexist'
>>> 
`
Any suggestions would be appreciated.

**Comment by SteveClement** [comment]
I got this working, in theory.

Did you follow the manual activation of the module?

e.g: 

  cd $PATH_TO_MISP/app/files/scripts/lief
  $SUDO_WWW mkdir build
  cd build
  $SUDO_WWW scl enable devtoolset-7 "bash -c 'cmake3 \
  -DLIEF_PYTHON_API=on \
  -DPYTHON_VERSION=3.6 \
  -DPYTHON_EXECUTABLE=$PATH_TO_MISP/venv/bin/python \
  -DLIEF_DOC=off \
  -DCMAKE_BUILD_TYPE=Release \
  ..'"
  $SUDO_WWW make -j3 pyLIEF

**Comment by kuchynkap** [comment]
Same problem here, I have followed the activation of the module as a part of the installation guide.

**Comment by kuchynkap** [comment]
> I got this working, in theory.
> 
> Did you follow the manual activation of the module?
> 
> e.g:
> 
> cd $PATH_TO_MISP/app/files/scripts/lief
> $SUDO_WWW mkdir build
> cd build
> $SUDO_WWW scl enable devtoolset-7 "bash -c 'cmake3
> -DLIEF_PYTHON_API=on
> -DPYTHON_VERSION=3.6
> -DPYTHON_EXECUTABLE=$PATH_TO_MISP/venv/bin/python
> -DLIEF_DOC=off
> -DCMAKE_BUILD_TYPE=Release
> ..'"
> $SUDO_WWW make -j3 pyLIEF

How did you get this working, please? I already used the example you provided - it is a part of the installation guide.

Thank you :)

**Comment by ghost** [comment]
I actually got this working (I think).
Turns out the Linux team had activated SELinux. When I turned that off the
tests in MISP seem to be working.
Need to test more to be sure though.

Hans-Christian


fre. 7. feb. 2020 kl. 12:58 skrev kuchynkap <notifications@github.com>:

**Comment by RichieB2B** [comment]
You don’t want to disable SELinux but you should follow the chcon/restorecon/setsebool/semanage/checkmodule/semodule statements in the installation guide.

**Comment by ghost** [comment]
I did, but they are not complete. So until I have time to dig into
debugging this I have no real choice unfortunately.



lør. 21. mar. 2020 kl. 08:49 skrev Richie B2B <notifications@github.com>:

**Comment by RichieB2B** [comment]
I did a MISP install on CentOS 7 yesterday using https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.rhel7.md as a guide. SELinux is enabled and ssdeep and lief are working (according to the diagnostics page).

For ssdeep you'll need these commands (see #5706):

```
sudo ln -s /usr/lib64/libfuzzy.so /usr/lib/libfuzzy.so
sudo scl enable rh-php72 'pecl install ssdeep'
echo "extension=ssdeep.so" |sudo tee /etc/opt/rh/rh-php72/php.d/99-ssdeep.ini
```

This should do the trick to set the SELinux context correctly:

```
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files/terms
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/files/scripts/tmp
  sudo chcon -t httpd_sys_rw_content_t $PATH_TO_MISP/app/Plugin/CakeResque/tmp
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/Console/cake
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/Console/worker/*.sh
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/files/scripts/*.py
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/files/scripts/*/*.py
  sudo chcon -t httpd_sys_script_exec_t $PATH_TO_MISP/app/files/scripts/lief/build/api/python/lief.so
  sudo chcon -R -t bin_t $PATH_TO_MISP/venv/bin/*
  find $PATH_TO_MISP/venv -type f -name "*.so*" -or -name "*.so.*" | xargs sudo chcon -t lib_t
```

**Comment by SteveClement** [comment]
thanks for everyones input :)
