### ISSUE TITLE
MISP INSTALL.sh does not work 

### ISSUE THREAD

**Issue by luffykuroneko** [MISP/MISP#5478]
I got error message, when I use INSTALL.sh in MISP.

OS:Ubuntu 18.04
Use command:
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash INSTALL.sh -c -M -D

ERROR: py2neo 4.3.0 has requirement urllib3<1.25,>=1.23, but you'll have urllib3 1.25.7 which is incompatible.
Installing collected packages: neobolt, neotime, wcwidth, prompt-toolkit, pygments, py2neo, pymisp
  Found existing installation: pymisp 2.4.119
    Uninstalling pymisp-2.4.119:
      Successfully uninstalled pymisp-2.4.119
  Running setup.py develop for pymisp

**Comment by SteveClement** [comment]
First try this is not reproducible.
Will try again by hand.

**Comment by GlennHD** [comment]
@SteveClement, I actually experienced this issue today but it did not impact installation.  Error snippet is at the bottom.  Just appears to be a non-impacting bug.  I'll update if I run into any `urllib3` issues.

### My System details (Pretty standard)
<pre>
<b>misp@misp:~$ cat /etc/lsb-release</b>
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

<b>misp@misp:~$ uname -a</b>
Linux misp.web.site 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

<b>root@misp:~# lshw -short</b>
H/W path        Device     Class      Description
=================================================
                           system     Standard PC (i440FX + PIIX, 1996)
/0                         bus        Motherboard
/0/0                       memory     96KiB BIOS
/0/400                     processor  Common KVM processor
/0/401                     processor  Common KVM processor
/0/1000                    memory     64GiB System Memory
/0/1000/0                  memory     16GiB DIMM RAM
/0/1000/1                  memory     16GiB DIMM RAM
/0/1000/2                  memory     16GiB DIMM RAM
/0/1000/3                  memory     16GiB DIMM RAM
/0/100                     bridge     440FX - 82441FX PMC [Natoma]
/0/100/1                   bridge     82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1.1                 storage    82371SB PIIX3 IDE [Natoma/Triton II]
/0/100/1.2                 bus        82371SB PIIX3 USB [Natoma/Triton II]
/0/100/1.2/1    usb1       bus        UHCI Host Controller
/0/100/1.2/1/1             input      QEMU USB Tablet
/0/100/1.3                 bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/2                   display    VGA compatible controller
/0/100/3                   generic    Virtio memory balloon
/0/100/3/0                 generic    Virtual I/O device
/0/100/5                   storage    Virtio SCSI
/0/100/5/0                 generic    Virtual I/O device
/0/100/12                  network    Virtio network device
/0/100/12/0     ens18      network    Ethernet interface
/0/100/1e                  bridge     QEMU PCI-PCI bridge
/0/100/1f                  bridge     QEMU PCI-PCI bridge
/0/1            scsi2      storage
/0/1/0.0.0      /dev/sda   disk       1099GB QEMU HARDDISK
/0/1/0.0.0/1    /dev/sda1  volume     1023KiB BIOS Boot partition
/0/1/0.0.0/2    /dev/sda2  volume     15GiB EXT4 volume
</pre>
### My exact steps after fresh install/fully updating
```
# adduser misp
# usermod -aG sudo misp
# su - misp
$ cd ~/
$ sudo wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
$ sudo chmod +x /tmp/INSTALL.sh
$ bash /tmp/INSTALL.sh
$ bash /tmp/INSTALL.sh -c -M
> Enter base URL to:  https://misp.web.site
```
### Code snippet right before `INSTALL.sh` script finishes successfully ###
<pre>
Building wheels for collected packages: py2neo, neobolt, neotime
  Building wheel for py2neo (setup.py) ... done
  Created wheel for py2neo: filename=py2neo-4.3.0-py2.py3-none-any.whl size=88307 sha256=[MASKED]
  Stored in directory: /var/www/.cache/pip/wheels/86/7d/e3/[MASKED]
  Building wheel for neobolt (setup.py) ... done
  Created wheel for neobolt: filename=neobolt-1.7.16-cp36-cp36m-linux_x86_64.whl size=517028 sha256=[MASKED]
  Stored in directory: /var/www/.cache/pip/wheels/8e/51/2b/[MASKED]
  Building wheel for neotime (setup.py) ... done
  Created wheel for neotime: filename=neotime-1.7.4-cp36-none-any.whl size=20544 sha256=[MASKED]
  Stored in directory: /var/www/.cache/pip/wheels/d4/b4/c4/[MASKED]
Successfully built py2neo neobolt neotime
<b>ERROR: py2neo 4.3.0 has requirement urllib3<1.25,>=1.23, but you'll have urllib3 1.25.7 which is incompatible.</b>
Installing collected packages: neobolt, neotime, wcwidth, prompt-toolkit, pygments, py2neo, pymisp
  Found existing installation: pymisp 2.4.119
    Uninstalling pymisp-2.4.119:
      Successfully uninstalled pymisp-2.4.119
  Running setup.py develop for pymisp
</pre>
### After finishing setup, I checked `urllib3 `version with `pip3`
<pre>
<b>root@misp:~# pip3 show urllib3</b>
Name: urllib3
Version: 1.22
...
</pre>
