### ISSUE TITLE
Mapping of attributes (documentation)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#548]
Mapping of attributes (documentation) while doing an import. Maybe publishing the overall format in table with a check-box per type of import/export would do the job.

**Comment by elhoim** [comment]
Does it mean documentation on what type of data from import formats get imported in MISP, and to which attribute type it is mapped to?
Same thing with export (which MISP data type map to export format data types)?

**Comment by iglocska** [comment]
Indeed. The idea is to let content producers know what to expect will
happen to their data once MISP ingests it.

Also for content consumers, show them how attributes map to the data being
exported.

**Comment by Rafiot** [comment]
Done.
