### ISSUE TITLE
The MISP database state does not match the expected schema

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5480]
![Capture](https://user-images.githubusercontent.com/25611301/71675362-497cba80-2d86-11ea-9db0-87f3d2b9229e.PNG)

What should i do to solve it ?!

**Comment by yousefhawwari** [comment]
Any answers guys, please?

**Comment by iglocska** [comment]
Looking at that, we need to fix our schema. Organization as a field is no longer in use for a long time, so please ignore it for now.

**Comment by yousefhawwari** [comment]
> Looking at that, we need to fix our schema. Organization as a field is no longer in use for a long time, so please ignore it for now.

Okay, Thank You.

**Comment by SteveClement** [comment]
possibly fixed, re-open if not.
