### ISSUE TITLE
Verify bad link on attachments

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5481]
![Capture2](https://user-images.githubusercontent.com/25611301/71675683-fb1beb80-2d86-11ea-9c45-87495d9dbcc3.PNG)

What should i do ?

**Comment by yousefhawwari** [comment]
Any answers guys, please?

**Comment by yousefhawwari** [comment]
??????

**Comment by iglocska** [comment]
You have received 7 events from a 3rd party / feed / whatever where the attachments were missing. Not much you can do since you never got the data in the first place.
