### ISSUE TITLE
GnuPG installation and settings…FAIL: Issues with the key/passphrase

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5482]
![Capture3](https://user-images.githubusercontent.com/25611301/71675784-3e765a00-2d87-11ea-8dc2-25e354b2c2f2.PNG)

What should i do ?

**Comment by SteveClement** [comment]
Use this test.php script to debug: https://github.com/SteveClement/misp-test

**Comment by yousefhawwari** [comment]
> Use this test.php script to debug: https://github.com/SteveClement/misp-test

Thanks for your answer.
I used it, but the problem still the same!

![GnuPGproblem](https://user-images.githubusercontent.com/25611301/71780245-d3b46100-2fc8-11ea-8af8-ff75ed70e09e.PNG)

**Comment by yousefhawwari** [comment]
> Use this test.php script to debug: https://github.com/SteveClement/misp-test

can you please review it?

**Comment by iglocska** [comment]
You need to actually run it so that we can help :) Just go to https://path/to/your.misp/test and paste the output

**Comment by SteveClement** [comment]
@yousefhawwari you need to open your browser on to the "test_5002927.e.t.c.php"

**Comment by yousefhawwari** [comment]
![gnupg](https://user-images.githubusercontent.com/25611301/72508697-d592e580-384e-11ea-8f7b-293441579616.png)


@SteveClement

**Comment by SteveClement** [comment]
I wonder if you have a .gnupg directory.
This is how it should look:

```
$ sudo ls -la /var/www/MISP/.gnupg
total 28
drwx------  4 www-data www-data 4096 Dec  4 00:15 .
drwxr-x--- 18 www-data www-data 4096 Dec  3 23:18 ..
drwx------  2 www-data www-data 4096 Dec  3 23:18 openpgp-revocs.d
drwx------  2 www-data www-data 4096 Dec  3 23:18 private-keys-v1.d
-rw-r--r--  1 www-data www-data 2024 Dec  3 23:18 pubring.kbx
-rw-------  1 www-data www-data   32 Dec  3 23:18 pubring.kbx~
-rw-------  1 www-data www-data 1240 Dec  3 23:18 trustdb.gpg
```

the directory 'private-keys-v1.d' needs to have .key files.

Maybe permissions are wrong?

In any case, the GnuPG plugin cannot find your private key.

**Comment by yousefhawwari** [comment]
![gnupg2](https://user-images.githubusercontent.com/25611301/72515934-7a1a2500-3859-11ea-88c3-935db83b54ce.PNG)
 
'private-keys-v1.d' Directory already have the .key files

![key](https://user-images.githubusercontent.com/25611301/72515943-80100600-3859-11ea-840e-e1fc4b3b62ae.png)

**Comment by SteveClement** [comment]
Interesting.

Let's try the following:

```
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin getSetting GnuPG.homedir
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin getSetting GnuPG.email
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin getSetting GnuPG.binary
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin getSetting GnuPG.password
```

Careful with the .password part.

Double check if this is what you would expect.

Also, you use Ubuntu? Or CentOS/RHEL?

**Comment by yousefhawwari** [comment]
@SteveClement Ubuntu

**Comment by yousefhawwari** [comment]
@SteveClement 

![gnu3](https://user-images.githubusercontent.com/25611301/72676389-74128700-3a99-11ea-8369-1881a8aa704f.PNG)

**Comment by yousefhawwari** [comment]
@SteveClement any answer please?
