### ISSUE TITLE
Feeds  not being retrieved

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5487]
Questions | Answers
-- | --
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

I noticed the last time i was able to schedule a retrieval of a feed was on 12/13/2020.. It is supposed to retrieve once every 24h. Is there anything or any logs I can check to see what could be the problem

thanks

Doug

**Comment by packet-rat** [comment]
The following methods can provide valuable insights into MISP operations and failures:

Prior Failures:

- grep -i 'fail\|error\|cache\|SQLSTATE'  /var/www/MISP/app/tmp/logs/resque-[YYYY-MM-DD].log
- grep -i 'fail\|error'   /var/www/MISP/app/tmp/logs/debug.log
- grep -i 'fail\|error'   /var/www/MISP/app/tmp/logs/error.log

Active Monitoring

-  tail -f /var/www/MISP/app/tmp/logs/error.log /var/www/MISP/app/tmp/logs/debug.log /var/www/MISP/app/tmp/logs/resque-[YYYY-MM-DD].log


_Substitute Date(s) of interest for_  [YYYY-MM-DD]

For example, the following will show all errors for the month of December:

grep -i 'fail\|error\|cache\|SQLSTATE'  /var/www/MISP/app/tmp/logs/resque-2019-12-*.log

**Comment by dmolina213** [comment]
Thank you  very much for your suggestion. I will sure try it when i get to work in a few hours. In addition, do you know how the external feeds work under the hood. How is it configured in MISP, processes or scripts that are run, configuration files, etc? I am sure it is in a cron job somewhere.

**Comment by dmolina213** [comment]
I am able to get some feeds in. but some are not able to come in. how do we restart the feed process manually using the CLI?

**Comment by dmolina213** [comment]
Some are completed and some show 'Could not fetch Feed'. Any ideas why it is unable to fetch the feed and if that happens how can we manually trigger a fetch?
Id | Date created | Date modified | Process ID | Worker | Job type | Input | Message | Organisation name | Status | Retries | Progress
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2233 | 2020-01-06 15:44:22 | 2020-01-06 15:44:27 | d41c05371544c06045e260389a29591c | prio | publish_event | Event ID: 1626 | Event published. | CTI | Completed | 0 | Completed
2232 | 2020-01-06 15:44:11 | 2020-01-06 15:44:11 | Part of scheduled feed fetch | default | feed_fetch | Feed: 24 | Saving data. | CTI | Unknown | 0 | 50%
2231 | 2020-01-06 15:44:11 | 2020-01-06 15:44:11 | Part of scheduled feed fetch | default | feed_fetch | Feed: 18 | Job done. | CTI | Unknown | 0 | Completed
2230 | 2020-01-06 15:44:11 | 2020-01-06 15:44:12 | a35caba02d59b5310b15e0416a65cdc6 | prio | publish_event | Event ID: 1625 | Event published. | CTI | Completed | 0 | Completed
2229 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 5 | Saving data. | CTI | Unknown | 0 | 50%
2228 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 4 | Job done. | CTI | Unknown | 0 | Completed
2227 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 2 | Could not fetch feed. | CTI | Unknown | 0 | Completed
2226 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 1 | Could not fetch feed. | CTI | Unknown | 0 | Completed
2225 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed caching | default | feed_cache |   | Job done. | CTI | Unknown | 0 | Completed

**Comment by dmolina213** [comment]
Some are completed and some show 'Could not fetch Feed'. Any ideas why it is unable to fetch the feed and if that happens how can we manually trigger a fetch?


Id | Date created | Date modified | Process ID | Worker | Job type | Input | Message | Organisation name | Status | Retries | Progress
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2233 | 2020-01-06 15:44:22 | 2020-01-06 15:44:27 | d41c05371544c06045e260389a29591c | prio | publish_event | Event ID: 1626 | Event published. | CTI | Completed | 0 | Completed
2232 | 2020-01-06 15:44:11 | 2020-01-06 15:44:11 | Part of scheduled feed fetch | default | feed_fetch | Feed: 24 | Saving data. | CTI | Unknown | 0 | 50%
2231 | 2020-01-06 15:44:11 | 2020-01-06 15:44:11 | Part of scheduled feed fetch | default | feed_fetch | Feed: 18 | Job done. | CTI | Unknown | 0 | Completed
2230 | 2020-01-06 15:44:11 | 2020-01-06 15:44:12 | a35caba02d59b5310b15e0416a65cdc6 | prio | publish_event | Event ID: 1625 | Event published. | CTI | Completed | 0 | Completed
2229 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 5 | Saving data. | CTI | Unknown | 0 | 50%
2228 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 4 | Job done. | CTI | Unknown | 0 | Completed
2227 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 2 | Could not fetch feed. | CTI | Unknown | 0 | Completed
2226 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed fetch | default | feed_fetch | Feed: 1 | Could not fetch feed. | CTI | Unknown | 0 | Completed
2225 | 2020-01-06 15:44:00 | 2020-01-06 15:44:00 | Part of scheduled feed caching | default | feed_cache |   | Job done. | CTI | Unknown | 0 | Completed

**Comment by dmolina213** [comment]
Does anyone have an updated list of the feed url's? It may be the case that my MISP instance does not have the correct feed url's configured that could be causing some of my feeds to fail.

**Comment by mokaddem** [comment]
It could be that some of the feed don't work anymore. A PR addressing this issue has been merged recently, hopefully solving your issue.
You can find documentation on how to automate certain tasks and how to use the CLI on this page `/events/automation`.
Cheers
