### ISSUE TITLE
Background workers need restart to notice new configuration settings

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#5498]
[app/Model/Sighting.php](https://github.com/MISP/MISP/blob/2.4/app/Model/Sighting.php) reads `Plugin.Sightings_policy` from the config in `attachToEvent()` which is used for the `publish_sightings` job. Unfortunately the background workers do not see the actual value unless I add
```
Configure::load('config');
``` 
at the top of `Sighting.php`
However, this might cause the issue discussed in #5304. How should this be properly solved?

**Comment by iglocska** [comment]
That indeed makes sense and is a good point. The solution is to replicate the loading of the configuration on startup for the console scripts. Will have a look once I'm in a slightly more usable state

**Comment by RichieB2B** [comment]
I see now. Because the workers are long lived PHP processes, changes in the config are not noticed until the workers are restarted. Makes sense indeed and would be nice to resolve but not crucial.

**Comment by iglocska** [comment]
Indeed. Will have a look and will try to see if there's a hooking mechanism that could help. If not we'll add a new one.

**Comment by RichieB2B** [comment]
This just got a lot more important to me. I needed to mass update some events so I set `MISP.disable_emailing=true` and started pulling in the updated events. Of course server pulls run in a background worker and they sent out notification E-mails anyway. :`(

**Comment by RichieB2B** [comment]
Thanks! \o/

**Comment by iglocska** [comment]
Forgot to reply to this. This should hopefully be fixed as of yesterday, let me know if it persists!

**Comment by iglocska** [comment]
Oh just as I submit the message it refreshes and reveals your response. Argh.
