### ISSUE TITLE
414 Request-URI Too Long

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#5500]
When mass editing attributes, MISP does a GET request like:
```
https://misp.local/attributes/editSelected/28854/[2113775,2113833,2113834,2113835,2113830,2113831,2113832,2113827,2113828,2113829,2113824,2113825,2113826,2113821,2113822,2113823,2113818,2113819,2113820,2113815,2113816,2113817,2113812,2113813,2113814,2113791,2113792,2113793,2113809,2113810,2113811,2113806,2113807,2113808,2113803,2113804,2113805,2113800,2113801,2113802,2113797,2113798,2113799,2113794,2113795,2113796,2113785,2113786,2113787,2113788,2113789,2113790,2113782,2113783,2113784,2113779,2113780,2113781,2113776,2113777,2113778,2113774,2113773,2113772,2113764,2113771,2113770,2113769,2113768,2113767,2113766,2113765,2113763]?_=1578668575760
```
This can get quite long. Apache has a default [LimitRequestLine ](http://httpd.apache.org/docs/2.4/mod/core.html#limitrequestline)of 8190 bytes, but [CIS Apache Benchmark 1.10.1](https://www.cisecurity.org/benchmark/apache_http_server/) limits this to 512 bytes.

Perhaps MISP can use of POST for this?

**Comment by iglocska** [comment]
Yeah that should be converted to a POST.

**Comment by krayzpipes** [comment]
The same issue is present when merging objects representing x509 certificates.  It results in a GET request that is too long.

**Comment by mokaddem** [comment]
Attribute mass edit and merging object are both no longer passing data via the URL. Thanks for the report!
(@krayzpipes it's cool to see that you are using that feature :smiley:)
