### ISSUE TITLE
Model "Feed" is no longer available in [Search Logs] UI

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#5501]
#5245 # Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | Win10
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.118

### Expected behavior

When specifying  parameters for [Search Logs], Model Type **Feeds** should be available.

_This option was available previously, not precisely sure when issue appeared,  but estimate it was within the past three point releases._

### Actual behavior
[Search Logs], Model Type **Feeds** is not available 

### Steps to reproduce the behavior
Select [Search Logs]
Select [Models] Drop Down

### Logs, screenshots, configuration dump, ...

![2020-01-12_12-53-54](https://user-images.githubusercontent.com/3220193/72223385-21d2e280-353c-11ea-9a98-3d3e62de2955.png)

**Comment by iglocska** [comment]
Oh boy, that list is manually populated?...

Thanks for the heads-up, fixed ;)
