### ISSUE TITLE
Synchronisation issues

### ISSUE THREAD

**Issue by poornenduan** [MISP/MISP#5503]
Hi, I am trying to integrate 2 MISP instances A and B. I am the site admin in ORG A and am trying to receive events from ORG B. My fellow colleague(ORG A) has the sync user API key from the ORG B using which I have set up a new server in out instance to connect to the ORG B MISP instance. However I found that all shared group events in the MISP B instance is not flowing into our MISP A instance. Please tell me if I have done anything wrong.

I understand that the shared groups have to set up by MISP B when they are pushing events to us?

Please let me know your inputs

**Comment by mokaddem** [comment]
Hello,
Could you review the sharing group configuration on MISP B? Especially the `Organisation` and `MISP instances` sections?
Also be sure that the receiving ORG is part of the sharing group.

**Comment by poornenduan** [comment]
Hi, I got this working. This was a storage issue in my MISP instance. Thanks for you  help.
