### ISSUE TITLE
Adding Event/Thread/Link in discussion thread results in MALFORMED URL

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#5506]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.0.4
| OS version (client)       |  
| PHP version               | 7.2
| MISP version / git hash   | 2.4.119
| Browser                   | Latest chrome

### Expected behavior
Have a discussion thread with workable links for Event/Thread and Link

### Actual behavior
Adding a discussion with [Event][/Event][Thread][/Thread][Link][/Link] and adding existing Event ID, Thread ID or link returns "%MALFORMED URL%" in the thread window.

Editing the thread shows that the value is properly saved (ie. you get the eventid etc. in the edit box).

MISP.baseurl and MISP.external_baseurl are set.

### Steps to reproduce the behavior
Per actual behavior.

### Logs, screenshots, configuration dump, ...
![2020-01-14 13_24_28-Events - MISP](https://user-images.githubusercontent.com/256028/72344327-3dbbbd00-36d1-11ea-9b32-59bf9b5a803d.png)

**Comment by iglocska** [comment]
Thanks, indeed ;)
