### ISSUE TITLE
Invalid format of Domain & Hostname

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#551]
Hello all,

Some domains are refused by MISP as attribute. For example:
- *.schwarz
- *.school
- ay_c.sire.com
- etc.

In these cases, MISP displays the error : "Domain name has invalid format. Please double check the value or select "other" for a type."

In order to avoid this issue, we might use the "Public Suffix List" [1](https://publicsuffix.org/learn/) to correctly parse the domain name or host-name ?

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
Interesting, I'll have a look at this, I've just changed the validation for domains / hostnames / email addresses yesterday so you should be able to use custom TLDs now, but your ay_c.sire.com is indeed not accepted. As a quick fix, I'll change the validation to accept some allowed characters like "_" but I'll look into using the public suffix list you linked to as an alternative in the longer run.

Thanks for the heads-up!

**Comment by elhoim** [comment]
A library that might help: https://github.com/jeremykendall/php-domain-parser

**Comment by elhoim** [comment]
Simpler solution might be to have a locally cached version of http://data.iana.org/TLD/tlds-alpha-by-domain.txt that is authoritative.
Having a local, distributed with MISP allows users to have a default good enough/recent enough version.

Maybe include an optional worker to update it regularly.

**Comment by SteveClement** [comment]
Closing due to non-activity.

Feel free to re-open with updated content.
