### ISSUE TITLE
Question (For Experts) : Is MISP Feeds System enough?

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5517]
Dears,

 I have a quick question, Is MISP Feeds System enough? Do we need to add any other external & custom feeds?

What is your advice?

Best Regards.

**Comment by iglocska** [comment]
That depends on what feeds you want to ingest. There are definitely feeds in formats that are not supported, in which case you will probably want to find/write a script that converts the data into a format that MISP can ingest and subsequently push the data into MISP.

**Comment by yousefhawwari** [comment]
@iglocska Thank you :)
