### ISSUE TITLE
Details on how Role search rate limiting works

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5521]
On https://misp.github.io/MISP/Changelog/ I see:
```
[API] Added rate limiting option to the API. [iglocska]
```
And I see `Enforce search rate limit` on `admin/roles/add` when clicked has `# of searches / 15 min.` This seems like a useful feature. Thanks.

I was not able to find more details on how this works, e.g. is this for WebUI search, PyMISP API searches, etc. Is there an issue or a doc that explains more?

I did try a test setting up a Role with the limit set to 1, but was able to perform unlimited `PyMISP.search_logs()` requests with a user of the Role.

Note for others: there is a fix if you play with this. See https://github.com/MISP/MISP/pull/5445

**Comment by mokaddem** [comment]
Hi @github-germ,
You can find an explanation on the throttling [here](https://www.misp-project.org/2019/10/11/MISP.2.4.117.released.html).
For now, only two endpoints are rate-limited:
- `/attributes/restSearch`
- `/events/restSearch`

As `PyMISP.search_logs()` is not querying these endpoints, you are not rate-limited.
I hope that clarify it.
Cheers!

**Comment by github-germ** [comment]
@mokaddem ... Thanks. Got it.

I was also interested in the behavior also with `search` and `search_index`. I see `Rate limit exceeded` for `search` (endpoint `/restSearch`). It appears that `search_index` (endpoint `/index`) is not limited.

**Comment by iglocska** [comment]
Indeed, as Sami mentioned only the restSearch endpoints are rate limited.

**Comment by leonardo-moraes-movile** [comment]
Do we have any news about the limits?
