### ISSUE TITLE
Possible to add multiple tags to an event in single API call?

### ISSUE THREAD

**Issue by automationator** [MISP/MISP#5523]
Currently running on MISP 2.4.108, and I'm trying to figure out if there is a way to add multiple tags to an event in a single API call. I haven't found anything documented for this yet.

I'm attempting to minimize the total number of API calls required, and using individual calls to /events/addTag for each tag is slowing things down with the total number of events+tags that I have.

**Comment by github-germ** [comment]
related https://github.com/MISP/PyMISP/issues/337

**Comment by automationator** [comment]
I read through that issue prior to posting this one, and it seems as though that is requesting the ability to bulk tag attributes, not the events themselves, as one of the comments was "Why not set the tag on the event level?"

**Comment by github-germ** [comment]
> seems as though that is requesting the ability to bulk tag attributes, not the events themselves

Correct; however, bulk tagging in general for attributes and events would help.

> Why not set the tag on the event level?

Because various attributes within the same event may have different properties determining different tags. And we do tag at the event level when those tags apply to all attributes within.

**Comment by mokaddem** [comment]
> Currently running on MISP 2.4.108, and I'm trying to figure out if there is a way to add multiple tags to an event in a single API call. I haven't found anything documented for this yet.
> 
> I'm attempting to minimize the total number of API calls required, and using individual calls to /events/addTag for each tag is slowing things down with the total number of events+tags that I have.

Indeed, it would be neat and useful to make ``tags/attachTagToObject/`` supports an array of tag to be attached. In the meantime that this feature is implemented, a workaround could be to use the edit function.
*Example:* If you want to attach ``tlp:red`` and ``tlp:green`` to the Event X
```
https://your.misp.url/events/edit/X
{
    "Tag": [
        { "name": "tlp:red"},
        { "name": "tlp:green"}
    ]
}
```

**Comment by mokaddem** [comment]
#5534 will solve the issue.
