### ISSUE TITLE
Error while adding attachment

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#5528]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.120, beb0547ab25803e95a0e65a21ba1cdc3a0d24fc2
| Browser                   | Firefox

### Expected behavior
Add an attachment to the event

### Actual behavior
when adding an attachment, the file is marked as uploaded/added, but is never present in the event

### Steps to reproduce the behavior
Add a new attachment to an existing event

### Logs, screenshots, configuration dump, ...
From the audit section:

Model | Model ID | Action | Title | Change
-- | -- | -- | -- | --
 Object | 0 | add | Object dropped due to validation for Event 57118 failed: file | Validation errors: {"uuid":["Please provide a valid  UUID"]} Full Object:  {"Object":{"distribution":"5","sharing_group_id":"1","meta-category":"file","name":"file","template_version":"18","description":"File  object describing a file with  meta-information","template_uuid":"688c46fb-5edb-40a3-8273-1af7923e2215","event_id":"57118","comment":"","Attribute":[{"distribution":5,"category":"Payload   delivery","type":"malware-sample","to_ids":1,"disable_correlation":0,"object_id":false,"event_id":"57118","object_relation":"malware-sample","data":"UEsDBB
-- | -- | -- | -- | -- | --

**Comment by mokaddem** [comment]
Hey @FafnerKeyZee 
I tried to add attachment using the `Add attachment` button and via an Object and both succeeded on HEAD 6c5c585.
Could you please update your object templates and try again?
If you still have the issue afterward, could you please try to elaborate a bit on how to reproduce it?
Thanks a lot!

**Comment by FafnerKeyZee** [comment]
Hey,
Just installed your version, but I still have the same error. But with an other instance I do not have this error, the only difference between the both instance is the installation of MISP-Modules.
Whenb I check into the log on app/tmp/logs, I do not see any thing revealent...

BR,

Edit: after updating MISP-Modules, I still have the same error on my instance.

**Comment by FafnerKeyZee** [comment]
Small update after git pulling "misp-objects" sub project, I'm able to upload an attachment, but if I want to encrypt it, it fails..;( So guess, I've to manually update all sub misp-*

**Comment by mokaddem** [comment]
I also tried with encryption and everything goes fine. Please, come back to us if updating your sub-dependencies did not solve your issue!
