### ISSUE TITLE
BLOB/TEXT column 'comment' used in key specification without a key length

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#5529]
After the last update, the db index check stated.

Table name | Column name | Indexed | Description
-- | -- | -- | --
attributes | comment | X | Column `comment` should be indexed
objects | comment | X | Column `comment` should be indexed
shadow_attributes | comment | X |  Column `comment` should be indexed

When I went to manually add indexes, I get the message.
`BLOB/TEXT column 'comment' used in key specification without a key length`

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.2.24-0ubuntu0.18.04.2
| MISP version / git hash   | v2.4.120

**Comment by mokaddem** [comment]
Hey @imidoriya !
Thanks for the feedback! It is indeed an error, the ``comment`` field should not be indexed.
Please do not index it.
The database schema has been updated.
Thanks!
