### ISSUE TITLE
Add/remove tags via API

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#553]
From what I can read in the documentation, there is no specific API call to add or remove tags to an event.

**Comment by ligreman** [comment]
Hello.

Any news about this issue? I'm trying to create events automatically using the API and wanted to associate tags to the event.

Thanks!

**Comment by elhoim** [comment]
Solved with https://github.com/MISP/MISP/commit/01398b3aded744d557f2cf12ccd40098b0b25ffe . So updating should make it work.
