### ISSUE TITLE
Have a search option in the Taxonomies screen

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#5532]
**Describe the solution you'd like**
Have a search option in the taxonomies sreen. Allow a user to search for a given string, both in the taxonomy description and the tags.

**Describe alternatives you've considered**
Point to Github search in repository of misp-taxonomies, but this is "outside" the MISP interface.

**Comment by iglocska** [comment]
yeah we defo need this.

**Comment by mokaddem** [comment]
This feature will be implemented once the view will be updated to use the generic index factory.

**Comment by cudeso** [comment]
This is solved via the "Filter" search box in the taxonomy view.
