### ISSUE TITLE
Local tags should sync between internal instances

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#5533]
As discussed in https://github.com/MISP/MISP/pull/4836

**Comment by ancailliau** [comment]
Merge with #5362

**Comment by Wachizungu** [comment]
I believe this can be closed

Adding reference (MISP v 2.4.130 but a bunch of fixes later as well):
https://github.com/MISP/MISP/commit/17c46a8b254e129a207e272d3d5f6b02872898be

**Comment by iglocska** [comment]
Thanks for the feedback, I'll close it!
