### ISSUE TITLE
Class Diagram / blueprint

### ISSUE THREAD

**Issue by NetEyes** [MISP/MISP#5536]
Greetings,

If possible to send me the class diagram and/or blueprints of the backend worker of MISP. What I want to understand are where are the workers that retrieve feeds and where it store? 
If I am going to develop a .net UI dashboard but wants to connect to the backend of MISP, where do I start? Should I just connect to the backend MQ or talk to the API? Please advise.

**Comment by iglocska** [comment]
Could you describe what exactly you're after? Worker information? Data pulled from feeds?

**Comment by mokaddem** [comment]
Hey @NetEyes!
MISP is using Cake Resque to manage workers. I guess you can find lots of useful information about it [here](https://cakeresque.kamisama.me/).
I you want to retrieve the worker status, I would advice to perform API call on MISP itself.
If you have more questions, feel free to ask

**Comment by NetEyes** [comment]
My objective is to develop a MISP UI dashboard in .net platform (similar to misp-dashboard).
This misp-dashboard.net (C#/asp.net) should connect to MISP backend.

**Comment by iglocska** [comment]
We have a zeromq connector, that is also the one used by the misp dashboard. Best to use that.

**Comment by NetEyes** [comment]
> We have a zeromq connector, that is also the one used by the misp dashboard. Best to use that.

Ok. Thanks. Any doc on how to interact with zeromq connector?

**Comment by mokaddem** [comment]
The zeromq data format is very close to the MISP core format, so integration is pretty straightforward.
You can find more information [here](https://www.circl.lu/doc/misp/misp-zmq/)

**Comment by NetEyes** [comment]
> The zeromq data format is very close to the MISP core format, so integration is pretty straightforward.
> You can find more information [here](https://www.circl.lu/doc/misp/misp-zmq/)

Do you happen to know where is the actual python script that is responsible for storing feeds to 0mq?

**Comment by mokaddem** [comment]
This script is responsible for publishing data to a zeromq channel
https://github.com/MISP/MISP/blob/2.4/app/files/scripts/mispzmq/mispzmq.py

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/blob/2.4/tools/misp-zmq/sub.py

This one is an example subscriber script.

**Comment by NetEyes** [comment]
here's my sample C# using NetMQ library. Handshake established but i don't see any data from zeromq. The MISP is running in Oracle VM with port forward (50000)

string mqserver = @"tcp://remote_ip_address:50000";

            Console.WriteLine("Attempting handshake with - " + mqserver);
            #region Subscriber
            using (var subscriber = new NetMQ.Sockets.SubscriberSocket())
            {
                subscriber.Connect(mqserver);

                subscriber.Subscribe("mispq");
                Console.WriteLine("Handshake established - " + mqserver);

                while (true)
                {
                    if (subscriber.TryReceiveFrameString(out string topic))
                    {
                        topic = subscriber.ReceiveFrameString();
                        var msg = subscriber.ReceiveFrameString();
                        Console.WriteLine("From Publisher: {0} {1}", topic, msg);
                    }
                }
            }

**Comment by iglocska** [comment]
Do you see anything with the test script I've linked above?

**Comment by NetEyes** [comment]
> Do you see anything with the test script I've linked above?

Yes thank you. The C# code is similar to what that python script does but I don't see any data from the .net subscriber

**Comment by mokaddem** [comment]
Not sure what the ``subscriber.Subscribe("mispq");`` does but if you subscribe to a channel that doesn't contain data, it may not work.
The python test script subscribes to the channel ``''``

**Comment by NetEyes** [comment]
> Not sure what the `subscriber.Subscribe("mispq");` does but if you subscribe to a channel that doesn't contain data, it may not work.
> The python test script subscribes to the channel `''`

That's it! channel '' works!

**Comment by NetEyes** [comment]
Next steps, I need to display these feeds in a dashboard (Kibana or Grafana).
should I store these feeds to Grakn.ai first?
