### ISSUE TITLE
Cannot add new events - the threat level list does not populate

### ISSUE THREAD

**Issue by mpurzynski** [MISP/MISP#5537]
## Please consider the following notes
When trying to add a new event one is expected to choose a "threat level". I cannot do that - the list, when clicking on it, comes up empty.

I do not see any errors being generated in /var/www/MISP/app/tmp/log

How do I go about troubleshooting that?

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.2
| MISP version / git hash   | 2.4.120 (4100af2a301d832ec6964d3cbafadd91a308367e)

**Comment by mpurzynski** [comment]
Currently installed version… v2.4.120 "4100af2a301d832ec6964d3cbafadd91a308367e"

**Comment by iglocska** [comment]
That sounds really odd. Basically, they're taken from the database and the values are created during installation. Is this a new instance? Using the same DB user that you use for MISP, could you do the following?
````
mysql -u misp -p misp
mysql> SELECT * from threat_levels;
````
Does it return a list of 4 threat levels?
