### ISSUE TITLE
Attribute search via UI no longer working

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#5538]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | 
| PHP version               | 7.2
| MISP version / git hash   | 2.4.120
| Browser                   | 

### Expected behavior
Search for literal values in /attributes/search and get results

### Actual behavior
Search for a literal string in Search Attributes : No results found.
Searched for complete strings, and parts of a string, same result.

Searching via the RestAPI gives the expected results.

### Steps to reproduce the behavior
As per behavior.

**Comment by cudeso** [comment]
DB Scheme seems OK.

![2020-01-23 13_36_28-Servers - MISP](https://user-images.githubusercontent.com/256028/72985139-9849cd00-3de5-11ea-94c1-a3d5e249152a.png)

**Comment by mokaddem** [comment]
Hey,
Thanks for the report. 1e49cc6aabc67145138de85b914a26ec4badd974 fixed it.
