### ISSUE TITLE
Updated to v2.4.120 and search seems broken

### ISSUE THREAD

**Issue by carnak** [MISP/MISP#5539]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2.10
| MISP version / git hash   | 4100af2a301d832ec6964d3cbafadd91a308367e
| Browser                   | firefox

### Expected behavior

Just trying simple search for domain known to be an attribute of an existing event

### Actual behavior

Expected results not returned, and no errors in /var/www/MISP/app/tmp/logs/*

### Steps to reproduce the behavior

Do a simple domain search

**Comment by mokaddem** [comment]
Hello! I guess you are searching using the `attributes/search` endpoint.
We fixed a bug affecting the search this afternoon (1e49cc6aabc67145138de85b914a26ec4badd974).
If updating your MISP instance to the latest version does not solve your issue, feel free to re-open.
Thanks!

**Comment by carnak** [comment]
Yes!  That fixed it - thank you!!!
