### ISSUE TITLE
Kali Install Script

### ISSUE THREAD

**Issue by rameyst** [MISP/MISP#5545]
When running the kali install script on kali 2019.4 virtual box image, I receive the following error:
"Either your platform is not easily detecable or is not support by this installer script."

I was also able to replicate this error on kali 2019.1 virtual box image. 

Is there a work around to force detection? 

![image](https://user-images.githubusercontent.com/7735679/73018876-743fb900-3df0-11ea-9334-e0b6b6c49956.png)

**Comment by SteveClement** [comment]
Indeed, I just noticed too. Will fix it.

**Comment by SteveClement** [comment]
Fixed with https://github.com/MISP/MISP/pull/5586
