### ISSUE TITLE
Publish Alert Email Failed !

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5547]
Dears, 

I have a problem with Publish Alert Email => (Failed)!

![paef](https://user-images.githubusercontent.com/25611301/73035597-5ce4e800-3e51-11ea-9d0f-d01b62c49b33.PNG)

Publishing was done but it's failed ! (Publish_alert_email box was checked)

What should i do ?

Best Regards.

**Comment by yousefhawwari** [comment]
any answer ?

**Comment by iglocska** [comment]
Anything in your worker / error logs?

**Comment by yousefhawwari** [comment]
@iglocska No

**Comment by mokaddem** [comment]
Have the mails been sent out? If you are unsure, you can check the logs of your mail server

**Comment by iglocska** [comment]
> @iglocska No

That is weird. "Failed" should always generate an entry in /var/www/MISP/app/tmp/logs/worker-error.log - are you certain?

**Comment by yousefhawwari** [comment]
@iglocska yes! it was an empty file !

**Comment by mokaddem** [comment]
Empty logs? That's worrisome.. 
1. What log files do you have when you do:
``ls -l /var/www/MISP/app/tmp/logs/`` ?

2. Also, do you have background jobs enabled on your MISP instance?
``/servers/serverSettings/MISP`` then ``MISP settings`` tab. ``MISP.background_jobs`` is the setting name

3. Finally, if ``background_jobs`` is enabled, what is the status of your workers?
``/servers/serverSettings/workers``

**Comment by yousefhawwari** [comment]
1- 
![worker](https://user-images.githubusercontent.com/25611301/73177502-e1688c80-4117-11ea-848b-e6a50bfca795.PNG)

2- yes "MISP.background_jobs" was enabled.

3- worker status is running. "The worker appears to be healthy."

@mokaddem

**Comment by yousefhawwari** [comment]
@mokaddem 
any answer please?

**Comment by mokaddem** [comment]
Hey, for point 3
- Finally, if background_jobs is enabled, what is the status of your workers?
/servers/serverSettings/workers
Could you paste the update of the page? I want to make sure that diagnostic is correct and that mails are not stockpiling.

**Comment by yousefhawwari** [comment]
Dear @mokaddem ,

 All workers appears to be healthy (Especially Email Worker) : 

![emailworker](https://user-images.githubusercontent.com/25611301/74328680-048d7000-4d97-11ea-8b47-3f6b6f226003.PNG)

Everything apears good but no any email was sent! 

Is there an additional configuration on the Administration/ServerSettings/MISP Settings ?

Best Regards,
Yousef Hawwari

**Comment by yousefhawwari** [comment]
@mokaddem 

I tested it on Gmail (it sent successfully) , but on ProtonMail can't received it !

**Comment by mokaddem** [comment]
Everything seems fine on MISP side.
If you can send mail through Gmail but not through ProtonMail, it's definitely a misconfiguration. I invite you to have a look at your mail sever logs.
