### ISSUE TITLE
Domain tools module

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5550]
Work environment
|Type of issue | support
|OS version (server) | RedHat
|MISP| Implemented on docker/ubuntu
|OS version (client) | windows 7
|PHP version | 7.2.10
|MISP version / git hash | v2.4.107 ()

this is a support issue. I am trying to enable DomainTools in the enrichments module. I want to check whether it is using the correct url. Where can i find that config file in MISP

**Comment by iglocska** [comment]
For the DomainTools module:

Is your misp-modules already running? If so: 

Administration -> server settings -> plugin settings tab and set the following settings:

`Plugin.Enrichment_services_enable` -> true
`Plugin.Enrichment_services_url` -> the url through which MISP can reach the module system, if installed on the same box the default setting (http://127.0.0.1) is fine
`Plugin.Enrichment_services_port` the port through which MISP can reach the module system, if installed on the same box the default setting (6666) is fine

If the above is correctly configured, all the module config settings will be added to this list, revealing the following ones among others that you need to configure:

`Plugin.Enrichment_domaintools_enabled` -> true
`Plugin.Enrichment_domaintools_username` -> your username
`Plugin.Enrichment_domaintools_api_key` -> your API key

**Comment by dmolina213** [comment]
Those settings were configured. What i wanted to know, is where can i make changes to the url or verify the url is the same as what domaintools is exposing their api as. --> https://api.domaintools.com.

Also if i want to define a new enrichment module, for example infoblox. How do i go about it?

**Comment by mokaddem** [comment]
To see how the `domaintools` enrichment module works, have a look [here](https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/domaintools.py).
You will find a bunch of example and documentation to create a new module [here](https://github.com/MISP/misp-modules).
Enjoy!
