### ISSUE TITLE
Error fetching list of organisation via API

### ISSUE THREAD

**Issue by ykorkmaz** [MISP/MISP#5551]
# Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | CentOS
| PHP version               | 7.2.25
| MISP version / git hash   | 2.4.119 
| Browser                   | If applicable

### Support Questions
Hi,

I tried to use the API to retrieve list of organisations, but always got redirect to login page (see below the request and response headers).

Am I missing something or what is the correct way to use the API to get a list of all organizations with id and name remotely?

Regards,

Documentation:
https://www.circl.lu/doc/misp/automation/#organisation-management

### Logs, screenshots, configuration dump, ...
 
curl  -v -k --header "Authorization: <AUTH-KEY>" --header "Accept: appliation/json" --header "Content-Type: application/json" -X GET http://<MISP-IP>/organisations
* About to connect() to <MISP-IP> port 80 (#0)
*   Trying <MISP-IP>...
* Connected to <MISP-IP> (<MISP-IP>) port 80 (#0)
> GET /organisations HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <MISP-IP>
> Authorization: zSpD8x66XAnL5r05jWUVbmxo54QsS2YgIQpOVVKG
> Accept: appliation/json
> Content-Type: application/json
>
< HTTP/1.1 302 Found
< Date: Fri, 24 Jan 2020 16:07:06 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.25
< X-Powered-By: PHP/7.2.25
< Set-Cookie: MISP-5dfbab5c-6e14-46cb-9683-06ecc0a82084=cc4au4h413lk992h9pnlm9ecn4; expires=Fri, 24-Jan-2020 17:07:06 GMT; Max-Age=3600; path=/; HttpOnly
< Location: http://<MISP-IP>/users/login
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host <MISP-IP> left intact

**Comment by iglocska** [comment]
That is weird, it looks correct to me, but generally debugging curl queries is painful, so instead just use the following:

````
curl \
 -H "Authorization: YOUR_API_KEY" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 https://path.to.your.misp/organisations
````

How I got this: Go to the rest client in MISP (Event actions -> rest client), build the query that you want (in this case I simply types /organisations in the URL bar and left the HTTP method on get). Run the query, if the returned data is what you expect, simply click on the cURL tab below and it will generate a cURL script for you using your API key, baseurl, etc. 

Feel free to open a new issue if this doesn't solve it for you.

**Comment by ykorkmaz** [comment]
Thanks, it solved my problem (query looks still same, but this worked anyway).
