### ISSUE TITLE
Login page - The request has been black-holed

### ISSUE THREAD

**Issue by alepadua** [MISP/MISP#5552]
I keep getting this error [BadReqyestExeception] when I am trying to login via the web interface into MISP. 

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat
| OS version (client)       | Win10

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/22760077/73086891-3e620980-3eb0-11ea-91be-296415fcfc25.png)

**Comment by mokaddem** [comment]
Do you also have the issue after you hard refresh the login page?
Also, do you have any proxy configuration?

**Comment by alepadua** [comment]
Hello, 
The issue was related to the proxy. Thanks a lot!

**Comment by annetteshajan** [comment]
@alepadua @mokaddem 
Hey having same error
please let me know what was your fix for the proxy config
