### ISSUE TITLE
Repeated Error during Install Invalid setting Notice Error: Array to string conversion in [/var/www/MISP/app/Model/Log.php, line 211]

### ISSUE THREAD

**Issue by utkonos** [MISP/MISP#5554]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.3
| PHP version               | 7.2
| MISP version / git hash   | 2.4.120

### Expected behavior
Installed MISP

### Actual behavior
During install, an error occurs for many of the plugins with the same error type for each one.

### Steps to reproduce the behavior
```
apt install wget
adduser --disabled-password misp
usermod -a -G sudo misp
usermod -a -G staff misp
usermod -a -G www-data misp
su - misp


wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/v2.4.120/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M
```

### Logs, screenshots, configuration dump, ...
These errors repeat for multiple plugins, but not all.
```
Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Invalid setting "Plugin.Enrichment_cve_enabled". Please make sure that the setting that you are attempting to change exists and if a module parameter, the modules are running.
Notice Error: Array to string conversion in [/var/www/MISP/app/Model/Log.php, line 211]

2020-01-27 00:10:08 Notice: Array to string conversion in [/var/www/MISP/app/Model/Log.php, line 211]
Setting "Plugin.Enrichment_cve_enabled" changed to 1
```

**Comment by utkonos** [comment]
MISP install wasn't completing for a separate reason and that's fixed. This error doesn't appear to actually prevent the install.

**Comment by iglocska** [comment]
Interesting. Those settings can only be set if the MISP modules are running and are dynamically created on the fly - in this case they're not so the setting doesn't exist. We should have a cleaner way of handling that.

**Comment by JakubOnderka** [comment]
This change (https://github.com/MISP/MISP/pull/5555) will fix the notice message and exit with error code if setting doesn't exists.

**Comment by utkonos** [comment]
Thanks!!

**Comment by utkonos** [comment]
With the more recent versions, there are fewer errors. There is still the following message:

```
Invalid setting "Plugin.Enrichment_cve_enabled". Please make sure that the setting that you are attempting to change exists and if a module parameter, the modules are running.
```

https://gist.github.com/utkonos/de478d19a32c2b5f01af2157d04ef6f9

**Comment by iglocska** [comment]
That only works if the MISP modules are running. That setting is generated
dynamically by querying the enrichment system for configuration options. If
it's not enabled / running then the error message makes sense.
