### ISSUE TITLE
Case insensitive alphanumeric sort in organization name (admin/users)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#556]
In the admin/users interface, it can be difficult to handle a lot users especially when the sort for the organization is case sensitive. It would be easier to have case insensitive alphanumeric sort for organization names instead of a case sensitive one.

**Comment by elhoim** [comment]
If users have different org names *CIRCL* & *cIRCL* for example, it would also be consider different orgs for access rights, which is probably something you don't want. 
Should not you instead change the org names in the user profiles?

**Comment by adulau** [comment]
Sure. It's just the ordering of the organization in the user admin interface. I just would like to have a consistent list and not two lists with the upper-case org names and another list with the lower-case org names. It's easier like this to spot any mistake we could have done with the org names.
