### ISSUE TITLE
Export wrong URIs

### ISSUE THREAD

**Issue by MetallDoktor** [MISP/MISP#5563]
Greetings!

We have faced an interesting... bug, I think? Here's the thing: when going to Event Actions -> Export, there is a bunch of buttons at the bottom of the page which let us export certain attributes like source/destination IPs, hashes, etc. These buttons have URI like the following:

_https://[instance_ip]/events/downloadExport/yara-json/[attribute]_

Clicking on them (any of them, to be precise) leads to this not very promising message:

**The requested file was not found
Error: The requested address '/events/downloadExport/yara-json/[attribute]' was not found on this server.**

AFAIK there is also an URI like:

_https://[instance_ip]/attributes/restSearch/returnFormat:text/type:[attribute].json_

And this actually works just right - eventually, we get json file with exported attributes throughout all events. Moreover, if I would go it on our own instance, it also works as expected.

But we have wrong URIs on our buttons.

Are there any ideas about why it can be so? We have updated to 2.4.120 version, still, it has no effect on it. Perhaps there are some configurable options which can resolve our problem but we cannot find anything.

Many thanks in advance!

**Comment by mokaddem** [comment]
Hello,
I guess you have the issue because the file has not been generated yet. Could you try ``Generate`` before ``Download``?
Unfortunately, the feature `events/export` is deprecated and will be removed in the near future. We really encourage you to use the restSearch enpoint to export data. It is much more powerful than the export method and gives you access to filtering capabilities, pagination, expiration, etc.
Cheers

**Comment by MetallDoktor** [comment]
I'm not quite sure that this is the case. If you mean we should generate the TEXT export file before clicking the buttons (as stated in TEXT description) - it was done from the beginning. The result is the same, no matter if it is outdated or not.

Are there any possibilities to alternate buttons URI manually (by making some changes to corresponding php file or something like that)?

**Comment by packet-rat** [comment]
We see the same exact issue and have for a fact executed the [Generate]. 

.02:  Having a simple Web UI method for non-technical users is a very useful feature.  “I need the list of all bad IPs -> Just click here.”



Patrick Maroney


> On Jan 30, 2020, at 3:33 AM, MetallDoktor <notifications@github.com> wrote:
> 

﻿
I'm not quite sure that this is the case. If you mean we should generate the TEXT export file before clicking the buttons (as stated in TEXT description) - it was done from the beginning. The result is the same, no matter if it is outdated or not.

Are there any possibilities to alternate buttons URI manually (by making some changes to corresponding php file or something like that)?

**Comment by iglocska** [comment]
Ineed, the export page was broken for text exports, fixed now.

**Comment by MetallDoktor** [comment]
Yep, now it's all fine and dandy. Big thanks!

**Comment by iglocska** [comment]
No worries, thanks for the feedback!
