### ISSUE TITLE
MISP image not accessible (forbidden)

### ISSUE THREAD

**Issue by mnabilczf** [MISP/MISP#5566]
Hi,

Im new to MISP and somehow, https://www.circl.lu/misp-images/latest/ not accessible by me with forbidden error. Is there any working links to download vm image? 

3 different machines with the same result. forbidden

**Comment by mokaddem** [comment]
By the time CIRCL fixes it, you can download the latest version here:
https://www.circl.lu/misp-images/

**Comment by mnabilczf** [comment]
Thank you @mokaddem.
