### ISSUE TITLE
Database indexes

### ISSUE THREAD

**Issue by rmsferreira** [MISP/MISP#5567]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  Ubuntu
| OS version (client)       | Ubuntu 18.04
| MISP version / git hash   | 2.4.119

### Support Questions
After upgrade my MISP I have some alerts related to Column `xxxxx` should be indexed.

Can you help

Thanks
![Capture](https://user-images.githubusercontent.com/22968643/73352547-3ed01b00-4289-11ea-81a9-099c193c17ed.PNG)

**Comment by mokaddem** [comment]
These are not critical warning.
I'll add a query generator similar to the schema diagnostic soon. . If you want to fix them, have a look [there](https://www.w3schools.com/sql/sql_create_index.asp).

**Comment by mokaddem** [comment]
Query generator added as well as indexing automatically known true positive.
Cheers
