### ISSUE TITLE
Add ability to disable/enable correlations for default feeds

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5568]
Currently, there is no way to disable correlations for a default feed unless after the feed executes correlations are disabled in the event(s) the feed creates. This is problematic.

Can we add a `disable_correlation` column to the `feeds` db table and allow this to be set via the WebUI and PyMISP?

Thanks.

**Comment by github-germ** [comment]
Hi... Is disabling correlations for a default feed still a possibility? Thx.

**Comment by github-germ** [comment]
@righel I see you are working https://github.com/MISP/MISP/pull/8313 -- Thanks!!

**Comment by righel** [comment]
Hi @github-germ
it will be stored as an optional setting in the feed settings json so we avoid database changes, will do some more testing but it will be soon merged into `develop`

**Comment by righel** [comment]
merged to `develop`, will be available in next release.
