### ISSUE TITLE
TLP rating changes over time

### ISSUE THREAD

**Issue by cbakkers** [MISP/MISP#557]
I understand TLP ratings is one of the fields to be included in one of the next releases,
I think would be useful to insert a function bulk changing method for TLP ratings of an event  and its attributes(for example, lot of events initially as Red or Amber may turn into green/white once a public report is made available)

**Comment by elhoim** [comment]
You can always edit an event to reflect the change of TLP (or add data) and then publish it.
Then the changes would be propagated to other instances.

Another way is to create an event in TLP RED for the original publication, and then one in TLP WHITE when data is published. This works well also it allows to selectively share some things in TLP WHITE and other TLP RED or AMBER on the same subject. If you don't have overlapping data between the events, you can force correlation by using a "internal reference"\"text" attribute that has the same value in the two events.

**Comment by elhoim** [comment]
Is this way of working OK for you?
Can I close this?

**Comment by Rafiot** [comment]
No answer, closing.
