### ISSUE TITLE
Unable to pull back event that MISP instance pushed to another MISP instance

### ISSUE THREAD

**Issue by paulnshelly2000** [MISP/MISP#5570]
I have a MISP set up with an instance in production and one in a lab environment.  I have the production instance tied to the hive.  When we export a case from the Hive to Production MISP I would like to push this event to the Lab instance where the tags and attributes will be analyzed and then pull back to production.

Currently I created a sharing group so the Prod event goes to the Lab instance.  However after I update the attributes and tags in the Lab the Production instance will not pull the event back.  Is there a way I can do this and if so what am I missing?

I have also enabled delegation to the Lab instance for publishing the event.

Thank you.

Paul

**Comment by RichieB2B** [comment]
A MISP server where an event originated (either by hand or API or import) will not accept changes made to that event by another MISP server. This is by design to avoid remote servers to mess with local data.

**Comment by paulnshelly2000** [comment]
Thanks.
