### ISSUE TITLE
Update the tags associated to an attribute on attribute update

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#5576]
**Is your feature request related to a problem? Please describe.**

POSTing a complete MISP event will update all it's parts (tags, objects, attributes, attribute tags, ...). Posting an attribute with tags on update attribute will ignore the tags.

**Describe the solution you'd like**

Update the tags.

**Describe alternatives you've considered**

Currently, the way to go is to:
* Post the whole event again (pretty resource intensive)
* use `tags/attachTagToObject` (the `tag` method in PyMISP), but in tat case, we need to do 2 requests instead of one.

**Comment by github-germ** [comment]
+1

**Comment by ag-michael** [comment]
Any progress on fixing this?

**Comment by mokaddem** [comment]
@ag-michael It should have been done with #6143. If you are missing a feature or want to report a bug feel free to create a new issue.
Thanks!
