### ISSUE TITLE
"Interesting" status message upon db upgrade

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5578]
2.4.120: when the db upgrade is running the following status message is being displayed:

![update](https://user-images.githubusercontent.com/25325656/73540882-564a0800-4431-11ea-8fdd-b3838e4687e8.png)

Furthermore, the corresponding job entry is incomplete:

![command](https://user-images.githubusercontent.com/25325656/73540934-77aaf400-4431-11ea-94ce-c98f87560427.png)

**Comment by iglocska** [comment]
"Had a quick look. Nothing special here. 
Update progress page is normal
Log is normal too. You have all the info. An update was already in progress in another worker, so it stopped."

      - @mokaddem the (battery) powerless

**Comment by StefanKelm** [comment]
Ah... So, the _seenOnAttributeAndObject_ is what's expected here?

As for the Jobs I was referring to` command: ,,` which looks weird.

**Comment by iglocska** [comment]
Yeah apparently all good :) It indeed does look weird, I'll pester him once he has power to have a nicer message.
