### ISSUE TITLE
INSTALL.sh overwrites /etc/environment

### ISSUE THREAD

**Issue by ivocarv** [MISP/MISP#5582]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4,120 

### Expected behavior
INSTALL.sh should install with proxy settings on /etc/environment

### Actual behavior
Installation fails if viper is selected for install

### Steps to reproduce the behavior
1) Configure proxy in /etc/environment
2) Install core and viper: INSTALL.sh -c -M -V

### Logs, screenshots, configuration dump, ...
Problem is in this line:
  $SUDO_USER /usr/local/src/viper-web/viper-web -p 8888 -H 0.0.0.0 &
  echo 'PATH="/home/misp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/src/viper:/var/www/MISP/app/Console"' |sudo tee /etc/environment
  echo ". /etc/environment" >> /home/${MISP_USER}/.profile

tee should be used with "-a" to append the path to the file, not overwrite the entire file.

**Comment by SteveClement** [comment]
Thanks for the report. As Viper is broken anyways I will do that change but also remove the viper option until it works again.
