### ISSUE TITLE
remove unpractical file-sanitization 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#559]
In `AttributesController.php:361`, `AttributesController.php:369`, `TemplatesController.php:383` and maybe other places some sanitisation is used when uploading files. 

The reason for this sanitisation is only because of the zipping of malicious files. (the original filename is kept in the zip).
However this makes it very unpractical to upload files with special charsets and or symbols.

To solve both this functional and security issue I propose the following approach:
- allow all filenames (they are stored in the database, so that's not an issue as long as html/json/xml sanitisation is done before displaying the name to the user) 
- for malware samples, rename the file to it's ***checksum*** and put it in the zip. But also include an `info.txt` file inside the zip bundle containing the original filename.

**Comment by adulau** [comment]
+1 (especially for the checksum-based filesystem).

**Comment by iglocska** [comment]
Sounds like a very good solution indeed!
