### ISSUE TITLE
Alert if non correlated artifacts correlates to new Intel data in the future

### ISSUE THREAD

**Issue by seldem** [MISP/MISP#5592]
Suppose I have an Event with several artifacts but none of them correlated. I wish to be alerted in a way (mail etc.) , if any of artifacts of this event correlates to new Intel data in the future. I hope you guys implement it. Thanks.

**Comment by adulau** [comment]
Duplicate of #3622

**Comment by adulau** [comment]
Related to #1613

**Comment by iglocska** [comment]
My bad, I asked for the issue, thought we didn't have one yet for this ;)

**Comment by cvandeplas** [comment]
closing as this is a duplicate of many more. See #1613 for updates.
