### ISSUE TITLE
Update to MISP v2.4.120 has broken remote sync filters

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#5594]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.24-0ubuntu0.18.04.2
| MISP version / git hash   | 2.4.120, bb64a80b245fe16402d47e492add8e889c05f73f
| Browser                   | Chrome

### Expected behavior
When syncing with a remote server, the events pulled should only be those permitted by the filter set (e.g. of selected tags/organisations). This occurs when using the scheduled task to pull, or when manually starting the pull.

This was working as of v2.4.120 hash: 6c5c5855c5426807215be61858c196f529cbac12

### Actual behavior
When upgrading to later versions of 2.4.120, server pull appears to ignore the filters set on the server pull and instead begins to pull ALL events from that server.

Seemingly the filters are not being applied (or are being applied in a different way?) to previous commits.

This occurs when using the scheduled task to pull, or when manually starting the pull.

### Steps to reproduce the behavior
Upgrading from the earlier commit meant that the next time the server sync ran, ALL events from the remote server were pulled. No changes to the configuration of this server were made between commit updates. The filters set had remained unchanged for the previous ~6 months without issue, and the remote server does not appear to have changed (it is running on v2.4.118).

Turning off the scheduled sync and manually applying the filters again, then turning the scheduled sync back off still results in the same issue.

**Comment by iglocska** [comment]
What the hell. Looking into it.

**Comment by iglocska** [comment]
Should be fixed now on HEAD, well this one sucks. We'll do a release asap. 

Thanks a lot for reporting it!
