### ISSUE TITLE
MISP Upgrade issue - Column `numerical_value` should be indexed

### ISSUE THREAD

**Issue by jay-carter** [MISP/MISP#5599]
Hi,
I just updated to  v2.4.120, then ran the diagnotics and got a database schema errors.
Running on Ubuntu Srv 18.04.
![image](https://user-images.githubusercontent.com/18250473/73913363-24182a80-48b7-11ea-859b-367bd6e34ecf.png)

Restarted the host after upgrade.

Should there be a text value in the column name?

Kind regards,

Jarek

**Comment by cbboggs** [comment]
I see the same after updating to v2.4.120, although everything seems to be running fine.

I believe numerical_value might be the actual name of the column.

**Comment by mokaddem** [comment]
Fixed with 5408bb14f8a7b8be5ccaa515a6699eb1f8eddae5
Thanks!

**Comment by jay-carter** [comment]
It works. Thanks!
