### ISSUE TITLE
duplicate events when syncing from different platforms

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#56]
Let's say you have your (internal) instance, with two remote instance (group1, group2) from two different trust-groups.

One member of the other trust group posted the information on both group1 and group2, manually.  (so uuids are different)
When your internal instance downloads the events you will get two different events with identical attributes. 
All attributes will have a 1:1 relation with the other event.

This is annoying as it :
- fills your database with redundant data
- spams your related events list

We should find ways to be able to recognize similar events, keep a reference of both and merge them.

**Comment by advancedeng** [comment]
+1 for this one. The publisher is the same and all atributes are identical in my case.

**Comment by adulau** [comment]
If you have the same publisher, they would share the same event UUID? It should be a single event.

**Comment by cvandeplas** [comment]
On 21 August 2015 at 15:36, Alexandre Dulaunoy <notifications@github.com> wrote:
> If you have the same publisher, they would share the same event UUID? It should be a single event.

I've heard that some organisations parse MISP, transform it into their
own format and then publish it again using MISP but while not keeping
the UUID.

Advancedeng: could you check the UUIDs of the different events and
attributes? The UUID of the event is visible on the event page. To see
the UUIDs of attributes, just add .json or .xml to the path of your
url.

**Comment by iglocska** [comment]
I sure hope that organsiations are not doing that, it would clearly be an abuse of the way it is intended to work.

**Comment by advancedeng** [comment]
Hi both, I just checked the UUIDs of the events and attributes. They are indeed the same so it is a problem for my MISP installtion. Any idea why this is happening?

Thanks, 
Andreas

**Comment by adulau** [comment]
Hi Andreas,

Could you exchange privately the XML output? to have a look at the events?

Cheers.

**Comment by adulau** [comment]
Thank you for the XML files. We'll have a look with @iglocska .

**Comment by adulau** [comment]
@advancedeng Thank you for the report. This should be fixed in d94a8d04c780a206682a5d20b37799ababb06809 . Don't forget to run the administrative script in the administrative tool.

**Comment by advancedeng** [comment]
Almost forgot this one! Thanks again!

**Comment by adulau** [comment]
Regarding the initial @cvandeplas comment, we are working on #612 which could support the creation of a simple algorithm to check the ratio of similar attributes per event.

**Comment by advancedeng** [comment]
Got some problems with the administrative script. It is a permission issue, see below.

Warning (2): unlink(/var/www/MISP/app/files/1659/153700): Permission denied [APP/Model/Event.php, line 359]

Warning (2): chmod() [function.chmod]: Operation not permitted [APP/Model/Event.php, line 363]

Warning (2): unlink(/var/www/MISP/app/files/1659/153700) [function.unlink]: Permission denied [APP/Model/Event.php, line 359]

----

Delete of event file directory failed. Please report to administrator.

Error: An Internal Error Has Occurred.
Stack Trace

    [internal function] → Event->beforeDelete(boolean)
    APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php line 241 → call_user_func_array(array, array)
    APP/Lib/cakephp/lib/Cake/Model/Model.php line 2680 → CakeEventManager->dispatch(CakeEvent)
    APP/Controller/AppController.php line 403 → Model->delete(string)
    [internal function] → AppController->removeDuplicateEvents()
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(ServersController, array)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(ServersController, CakeRequest)
    APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by iglocska** [comment]
Hello there, that looks like a permission issue with the file directory
where the samples are stored. MISP is trying to delete your duplicate
events but it is running into a permission issue. Simply run this:

chmod -R g+ws /var/www/MISP/app/files

Also make sure that you check the diagnostics (Administration -> Server
settings -> diagnostics) to see which other directories MISP cannot write
to that it needs.

Let me know if this doesn't solve it!

**Comment by advancedeng** [comment]
Done! Thanks a lot iglocska!! Much appreciated :)

**Comment by iglocska** [comment]
Excellent, I'll close the issue for now, let me know if you run into anything! :)
