### ISSUE TITLE
How to disable Force-Sync for ObjectAttributes and parent Object?

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/MISP#5602]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| MISP version / git hash   | v2.4.120 (8738aab6b8d4b4cdf4da12c35ef0b80662b18d65)

### Support Questions

**TL;DR** - How do I update an Object's first/last seen values without stomping all the first/last seen values of the ObjectAttributes that belong to it?

Here's my scenario:

I have an object that I am using to keep track of a specific web page via a background script. The script polls the specific page and gets a hash of the content. That hash then gets added to the object as an ObjectAttribute. If the hash doesn't change the last_seen value of both the parent Object and the ObjectAttribute gets updated. If the hash **DOES** change then I want to add the new hash with new first_seen last_seen data and still update the parent Object's last_seen info, but I want to leave the old hash's first/last seen data intact.

The problem I'm running into is that whenever the parent Object has its first/last seen values updated it automatically stomps all the timestamps of its corresponding ObjectAttributes.

I believe the root of this issue lies here:
https://github.com/MISP/MISP/blob/eb9b60032e5a0979e876a17627ba866df2494bae/app/Model/MispObject.php#L585

Is there any way currently to tell the Object when it's being updated to set `applyOnAttribute` to **FALSE**?

If not, should it maybe default to False so as not to stomp all child timestamps, and then have a checkbox available on the Object Template page for those that do want to sync the ObjectAttribute first/last_seen with the parent Object's first/last_seen?

I would imagine something like that would show up here, but it doesn't appear to be implemented yet: https://github.com/MISP/MISP/blob/eb9b60032e5a0979e876a17627ba866df2494bae/app/Controller/ObjectsController.php#L565

### Logs, screenshots, configuration dump, ...

- Set object first_seen and last_seen
- Update ObjectAttribute first_seen and last_seen
- Dump Object and ObjectAttribute:

```
##### OBJECT #####


{'Attribute': [<MISPObjectAttribute(object_relation=text, value=Test Page Value),
               <MISPObjectAttribute(object_relation=domain, value=google.com),
               <MISPObjectAttribute(object_relation=md5, value=1d5920f4b44b27a802bd77c4f0536f5a)],
 'comment': '',
 'deleted': False,
 'description': 'My object description',
 'distribution': '5',
 'event_id': '2447',
 'first_seen': '2020-01-30T00:00:00.000000+00:00',
 'id': '38433',
 'last_seen': '2020-02-06T12:00:00.000000+00:00',
 'meta-category': 'misc',
 'name': 'site-watcher',
 'sharing_group_id': '0',
 'template_uuid': '6b55441c-3e6e-454f-1234-15a44a710095',
 'template_version': '2',
 'timestamp': '1580998917',
 'uuid': 'dd7d7086-cd4b-4d1a-1234-abe92818aa06'}


##### OBJECTATTRIBUTE #####


{'Tag': [<MISPTag(name=tag_1),
         <MISPTag(name=tag_2)],
 'category': 'Network activity',
 'comment': 'Google Hash',
 'deleted': False,
 'disable_correlation': True,
 'distribution': '5',
 'event_id': '2447',
 'first_seen': '2020-02-04T00:00:00.000000+00:00',
 'id': '544840',
 'last_seen': '2020-02-06T00:00:00.000000+00:00',
 'object_id': '38433',
 'object_relation': 'md5',
 'sharing_group_id': '0',
 'timestamp': '1580998917',
 'to_ids': True,
 'type': 'md5',
 'uuid': 'ebc5885f-685e-4e21-1234-70153690533a',
 'value': '1d5920f4b44b27a802bd77c4f0536f5a'}
```

- Update Obect first_seen and last_seen without touching ObjectAttribute.
- Dump Object and ObjectAttribute:

```
##### OBJECT #####


{'Attribute': [<MISPObjectAttribute(object_relation=text, value=Test Page Value),
               <MISPObjectAttribute(object_relation=domain, value=google.com),
               <MISPObjectAttribute(object_relation=md5, value=1d5920f4b44b27a802bd77c4f0536f5a)],
 'comment': '',
 'deleted': False,
 'description': 'My object description',
 'distribution': '5',
 'event_id': '2447',
 'first_seen': '2020-01-30T00:00:00.000000+00:00',
 'id': '38433',
 'last_seen': '2020-02-06T12:00:00.000000+00:00',
 'meta-category': 'misc',
 'name': 'site-watcher',
 'sharing_group_id': '0',
 'template_uuid': '6b55441c-3e6e-454f-1234-15a44a710095',
 'template_version': '2',
 'timestamp': '1580998917',
 'uuid': 'dd7d7086-cd4b-4d1a-1234-abe92818aa06'}


##### OBJECTATTRIBUTE #####


{'Tag': [<MISPTag(name=tag_1),
         <MISPTag(name=tag_2)],
 'category': 'Network activity',
 'comment': 'Google Hash',
 'deleted': False,
 'disable_correlation': True,
 'distribution': '5',
 'event_id': '2447',
 'first_seen': '2020-01-30T00:00:00.000000+00:00',
 'id': '544840',
 'last_seen': '2020-02-06T12:00:00.000000+00:00',
 'object_id': '38433',
 'object_relation': 'md5',
 'sharing_group_id': '0',
 'timestamp': '1580998917',
 'to_ids': True,
 'type': 'md5',
 'uuid': 'ebc5885f-685e-4e21-1234-70153690533a',
 'value': '1d5920f4b44b27a802bd77c4f0536f5a'}
```

**Comment by mokaddem** [comment]
Hey @TheDr1ver,
Thanks for the detailed use-case and valuable issue.
The reason behind why Object's Attribute are synchronized with the Object is because the ``first_seen`` & ``last_seen`` feature has been built with the timeline UI in mind. With the current implementation, it's not possible to view multiple ``fs``/``ls`` for one Object (This may change in the future tough ;) ).
 
The function 
https://github.com/MISP/MISP/blob/eb9b60032e5a0979e876a17627ba866df2494bae/app/Controller/ObjectsController.php#L565
was built this way because we changed our mind multiple time during the design of the feature.

Next version will allow you to achieve your use-case, as well as visualize it in the timeline.

Thanks a lot and thanks for your patience!

**Comment by TheDr1ver** [comment]
Thanks for the quick response!

With regards to the timeline, I understand that it takes the parent
object's first/last for the display and I definitely think that's the right
call. Maybe consider force-syncing the parent object's first/last seen
times based on its child ObjectAttributes?

I.E. The parent object's first/last seen becomes the minimum/maximum
first/last seen of all child ObjectAttributes.

Just a thought. Thanks again, and I'll be patiently waiting!

**Comment by TheDr1ver** [comment]
I just wanted to ping this issue again because I'd still very much like to execute the use-case I mentioned, and I wanted to make sure this doesn't get too buried in the sea of other issues :)

**Comment by iglocska** [comment]
Internal note: Perhaps one way to solve it would be a beforeValidate hook to evaluate whether the attribute's fs/ls are within the boundaries of the object's fs/ls. This may come at a heavy cost in terms of additional look-ups though (perhaps to ease the burden, only apply these rules when the object itself is saved with all attached attributes rather than on every attribute edit?).

**Comment by mokaddem** [comment]
@iglocska `BeforeValidate` is indeed a good place to adapt them. But I don't want to have inconsistencies in the dataset.
If an attribute is edited and it belongs to an object, we have to fetch the object anyway (no need to fetch the other attributes fortunately).
@TheDr1ver Your use case is totally valid and I would like to work on it but unfortunately, I'll not be able to work on it anytime soon. Unless there is suddenly a large amount of people/organisations willing to have this enhancement, I don't expect it to be live before 2021. :/

**Comment by TheDr1ver** [comment]
Sorry to beat a dead horse here, but I found another problem that seems to be related to this.

```
Object A (Timestamp 1601585063)
    Attribute X
        Timestamp 1601585063
    Attribute Y
        Timestamp 1601585063
        First_Seen 1601585063
```

If I either modify an attribute associated with Object A, or add an attribute to Object A, **all** attributes under Object A that have either their first_seen or last_seen values set will have their primary Timestamp stomped to match the time of the modification or addition. Attributes without first_seen or last_seen values will retain their primary timestamps as expected.

Adding ONLY Attribute Z and not touching anything else in Object A gives the following results:
```
Object A (Timestamp 1601586000)
    Attribute X
        Timestamp 1601585063
    Attribute Y
        Timestamp 1601586000
        First_Seen 1601585063
    Attribute Z
        Timestamp 1601586000
```

This is causing me problems because I have an object with multiple attributes that occur within the object's overall window of first_seen/last_seen, but simply because I recorded the first_seen and last_seen of the ObjectAttributes every time one of the ObjectAttributes gets updated or a new ObjectAttribute gets added it goes through and stomps every single ObjectAttribute's primary timestamp (as well as the primary timestamp of the parent object itself). So when I look at the object in MISP, it looks like everything occurred at the same, most-recent time, even though all ObjectAttributes happened at different times.

**Comment by iglocska** [comment]
Woah, ok that definitely sounds like a bug.

**Comment by mokaddem** [comment]
Hey @TheDr1ver,
Here is what I'm getting when reproducing the same steps as you described
- Create an Object with 3 attributes, then setting the Object's `first_seen` gives me
```
{
    "Object": {
        "timestamp": "1601990259",
        "first_seen": "2020-10-06T12:57:00.000000+00:00",
        "last_seen": null,
        "Attribute": [
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            }
        ]
    }
}
```
- Then adding a new attribute via the `quick add` button gives me
    - So it only update the `timestamp` of the Object and of course the new attribute
```
{
    "Object": {
        "timestamp": "1601990410",
        "first_seen": "2020-10-06T12:57:00.000000+00:00",
        "last_seen": null,
        "Attribute": [
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990230",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990410",
                "first_seen": null,
                "last_seen": null,
            }
        ]
    }
}
```
- Finally, editing an object and adding a new attribute gives me
```
{
    "Object": {
        "timestamp": "1601990959",
        "first_seen": "2020-10-06T12:57:00.000000+00:00",
        "last_seen": null,
        "Attribute": [
            {
                "timestamp": "1601990959",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990959",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990959",
                "first_seen": "2020-10-06T12:57:00.000000+00:00",
                "last_seen": null,
            },
            {
                "timestamp": "1601990959",
                "first_seen": null,
                "last_seen": null,
            },
            {
                "timestamp": "1601990959",
                "first_seen": null,
                "last_seen": null,
            }
        ]
    }
}
```

Which update all timestamps.
I don't see where the issue is in all cases.
- The `first_seen` is not overridden
- Bumping `timestamp` seems normal to me as `timestamp` should only be used to get last modified data or for the sync

**Comment by TheDr1ver** [comment]
Sorry, I should have specified that I'm doing all of my testing with PyMISP using `PyMISP.update_object()`, rather than using anything in the GUI. 

The final scenario you presented is the problem I'm running into. Let's say I have an object that consists of a domain and its associated DNS records.

```
domain-dns-object
    domain = example.com
    ns = ns1.example.com
        timestamp = 2020-10-01
        first_seen = 2020-09-01
        last_seen = 2020-10-01
```

Then, while monitoring that domain, I noticed that they changed the nameserver to `ns1.badguy.com`.

Right now if I update that object it will look like this: 

```
domain-dns-object
    domain = example.com
    ns = ns1.example.com
        timestamp = 2020-10-06
        first_seen = 2020-09-01
        last_seen = 2020-10-01
    ns = ns1.badguy.com
        timestamp = 2020-10-06
        first_seen = 2020-10-05
        last_seen = 200-10-06
```

But, I believe it should look like this:

```
domain-dns-object
    domain = example.com
    ns = ns1.example.com
        timestamp = 2020-10-01
        first_seen = 2020-09-01
        last_seen = 2020-10-01
    ns = ns1.badguy.com
        timestamp = 2020-10-06
        first_seen = 2020-10-05
        last_seen = 200-10-06
```

My reasoning behind this logic is that nothing about the `ns1.example.com` attribute has changed. It was first seen on 2020-09-01 and last seen on 2020-10-01, so setting its timestamp to 2020-10-06 doesn't make sense to me. 

With the current method, when looking at the event in MISP, if timestamp is getting overwritten it will appear to the user that `ns1.example.com` was added/modified on 2020-10-06 because it got time-stomped, when in reality `ns1.example.com` was last relevant to that object on 2020-10-01.

Your example using the `quick add` button illustrates how I would expect the timestamps to behave in all instances.

**Comment by mokaddem** [comment]
Hey @TheDr1ver ,
Changes have been done for fs/ls during `object/edit` operations (a0765628179589ea6ff7ba2c4f0801fe3a58cfaf). Feel free to read the commit note and try it out.
Please, get back to us if you notice other things that do not make sense or if the behavior is not the one you expect.
Thanks!

**Comment by TheDr1ver** [comment]
Thanks for getting back to this issue, @mokaddem - I finally had a chance to try it out using  v2.4.134 (17997e01e0773e50106359ed1755cc3e1c459d0a) and the latest version of PyMISP, but unfortunately I'm still seeing the issue where attribute timestamps are getting stomped (described in my comment from Oct 6). 

Let me know if you have trouble reproducing the issue and I'll be happy to provide the sample code I'm using to test.

**Comment by mokaddem** [comment]
Yes please, could you provide me the sample code you are using? Or at least how the object is fetched then pushed to MISP.
Thanks in advance!

**Comment by TheDr1ver** [comment]
Sure thing. First, create a new event with no attributes or objects attached to it. In this instance the event ID was 3145.

The first time you run the code it will generate an object with a domain and a text attribute attached to it. 

The second time you run it, it will generate a new "text" attribute to the existing object with explicitly defined first_seen and last_seen values. The original object attributes (which do not have first_seen or last_seen defined) will not have their timestamps modified.

Finally, the third time you run the script it will generate another attribute and attach it to the existing object with first_seen and last_seen defined. The first two attributes (domain and "Example text 1") will not have their timestamps modified because they do not have first_seen and last_seen defined. However, the "text" attribute that was added on the second run will now have an overwritten timestamp even though its first_seen and last_seen values remain the same.

```
# timestomping_test.py
from pymisp import PyMISP
from pprint import pprint

misp_url = "https://<your-misp-server>/" # CHANGE ME
misp_key = "<your-misp-api-key>>" # CHANGE ME
event_id = 3145 # CHANGE ME

misp = PyMISP(misp_url, misp_key, False)

from pymisp import MISPObject
from time import time

live_update = True
add_time_all = True

evt = misp.get_event(event_id, pythonify=True)

epoch = int(time())
value = str(epoch)

def check_timestamps(obj):
    print(f"\n#### RUNNING TIMESTAMP CHECK ####\n")
    pprint(obj)
    if hasattr(obj, 'timestamp'):
        print(f"Object timestamp: {obj.timestamp}")
    else:
        print(f"Object has no timestamp - must be new here...")
    if hasattr(obj, 'first-seen'):
        print(f"Object first_seen: {obj.first_seen}")
    if hasattr(obj, 'last_seen'):
        print(f"Object last_seen: {obj.last_seen}")
    for attr in obj.Attribute:
        pprint(attr)
        print(f"Attribute value: {attr.value} and UUID: {attr.uuid}")
        if hasattr(attr, 'timestamp'):
            print(f"Attribute timestamp: {attr.timestamp}")
        else:
            print(f"Attribute has no timestamp - must be new here...")
        if hasattr(attr, 'first_seen'):
            print(f"Attribute first_seen: {attr.first_seen}")
        if hasattr(attr, 'last_seen'):
            print(f"Attribute last_seen: {attr.last_seen}")
    return True

if len(evt.Object) > 0:
    print(f"Found an existing object! No need to create a new one!")
    obj = evt.Object[0]
    check_timestamps(obj)

    # Add attribute then check timestamps again
    
    if add_time_all:
        print(f"\nAdding attribute {value} with explicit first_seen, last_seen...")
        obj.add_attribute('Text', type='text', value=value, first_seen=epoch, last_seen=epoch)
    else:
        print(f"\nAdding attribute {value} without timestamps...")
        obj.add_attribute('Text', type='text', value=value)
    check_timestamps(obj)

    if live_update:
        print(f"\nUpdating object in MISP...")
        new_obj = misp.update_object(obj, pythonify=True)
        check_timestamps(new_obj)

else:
    print(f"Creating object without a template...")
    host_obj = MISPObject('random-obj')
    host_obj.add_attribute('example-domain', value=value+".example.com", type='domain', to_ids=False)
    host_obj.add_attribute('example-text', value="Example text 1", type='text', to_ids=False)
    host_obj.new_host = True
    evt.add_object(host_obj)
    check_timestamps(host_obj)
    new_evt = misp.update_event(evt, pythonify=True)
    check_timestamps(new_evt.Object[0])

```

**Example output after the 3rd run of the script:**

```
#### RUNNING TIMESTAMP CHECK ####

<MISPObject(name=random-obj)
Object timestamp: 2020-11-10 13:17:41+00:00
<MISPObjectAttribute(object_relation=example-domain, value=1605014197.example.com)
Attribute value: 1605014197.example.com and UUID: 27829f3a-40ac-418e-83e3-d52494d091e8
Attribute timestamp: 2020-11-10 13:16:38+00:00
<MISPObjectAttribute(object_relation=example-text, value=Example text 1)
Attribute value: Example text 1 and UUID: 641b1f75-721a-49cc-babc-f9203b7b01ec
Attribute timestamp: 2020-11-10 13:16:38+00:00
<MISPObjectAttribute(object_relation=Text, value=1605014213)
Attribute value: 1605014213 and UUID: cd7f6316-b47f-4304-a428-824f406a6192
Attribute timestamp: 2020-11-10 13:17:41+00:00              ######## <---- Problem here
Attribute first_seen: 2020-11-10 13:16:53+00:00
Attribute last_seen: 2020-11-10 13:16:53+00:00
<MISPObjectAttribute(object_relation=Text, value=1605014260)
Attribute value: 1605014260 and UUID: 132dc6ee-2b6a-42a9-aab6-ffc0ccdd5928
Attribute timestamp: 2020-11-10 13:17:41+00:00
Attribute first_seen: 2020-11-10 13:17:40+00:00
Attribute last_seen: 2020-11-10 13:17:40+00:00
```

I would expect the Text object with value 1605014213 to have the timestamp of `2020-11-10 13:16:53+00:00` (or + 1 second b/c of the way object updates are handled)

**Comment by mokaddem** [comment]
Thanks to your script, I have able to track down what was happening.
It turned out that whenever a object's attribute was provided, a textual comparison was done to deduce if something has changed or not
https://github.com/MISP/MISP/blob/17c793d10f00867d9a40f7039e86a2c13ccbfaa9/app/Model/MispObject.php#L796
However for the `first_seen` and `last_seen` case, we were not comparing their actual value but their representation.
```php
'2020-11-11T08:17:04.000000+00:00' != '2020-11-11T08:17:04+00:00'
```
Commit 774c4c104aa2982a2d6e17f31a23d6c771d27299 fixes it.

Please note that even though this timestamp bump was happening, it was completely benign for the usage of the system ;)

Was again, thanks for the detailed comments and feedback, it's much appreciated!

**Comment by TheDr1ver** [comment]
Woohoo! It works! Thanks so much for digging into this - I know it seems like an obscure bug, but for what I was trying to do it was driving me crazy!

Thanks again :)
