### ISSUE TITLE
[Blackhole] issue importing from json/xml generated from MISP

### ISSUE THREAD

**Issue by helium7** [MISP/MISP#5604]
O.S : Ubuntu 16.04.2 LTS
Browser : chrome
MISP : v2.4.119

Hi we recently set up 2 MISP, one at DMZ, to collect feeds, and other at OOB network
We exported the 160MB data (via MISP export) from the DMZ MISP but we got the follow issue when we try to import it into the OOB MISP:

The request has been black-holed
Error: The requested address '/events/add_misp_export' was not found on this server.

Both server are newly set up

**Error.log:**
2020-02-07 02:28:03 Error: [BadRequestException] The request has been black-holed
Request URL: /events/add_misp_export
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

We do not understand the error and any help would be great

**Comment by iglocska** [comment]
160MB data uploaded will be blocked by PHP (via the php.ini directives post_max_size and max_upload_size - or something similar), meaning that the body of the request arrives empty and the csrf protection will block the entry.

Make sure that your php.ini is configured to allow for uploads larger than what you're trying to upload (and make sure you change both the upload size and the post size limits as both are needed).

**Comment by helium7** [comment]
Thanks! it work after i edit the php file

**Comment by iglocska** [comment]
excellent, thanks for the feedback :)
