### ISSUE TITLE
Your software has no emoji support

### ISSUE THREAD

**Issue by InfoSecN00b42** [MISP/MISP#5605]
On testing virtual machine installation adding Emoji fails in comments.
Does also make server errors when adding a custom tag thing.

🤷

# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by mokaddem** [comment]
Thanks for the report,
This issue will be fixed once we transition to the new framework (we will also migrate the database to use `utf8mb4`)
Thanks for your patience

**Comment by SteveClement** [comment]
presumably done
