### ISSUE TITLE
Add comment to an attribute

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#561]
Hello all,

When you want to edit an attribute in order to add a comment, MISP displays the error :

"A similar attribute already exists for this event."

After a short analysis, the function "valueIsUnique" in the file app/Model/Attribute.php doesn't take into account the comment of an attribute. I quickly patched the variable "$conditions" of this function to take into account the comment.

```
diff --git a/app/Model/Attribute.php b/app/Model/Attribute.php
index aeb762c..5b6ba1a 100755
--- a/app/Model/Attribute.php
+++ b/app/Model/Attribute.php
@@ -500,12 +500,14 @@ class Attribute extends AppModel {
                $type = $this->data['Attribute']['type'];
                $toIds = $this->data['Attribute']['to_ids'];
                $category = $this->data['Attribute']['category'];
+               $comment = $this->data['Attribute']['comment'];
 
                // check if the attribute already exists in the same event
                $conditions = array('Attribute.event_id' => $eventId,
                                'Attribute.type' => $type,
                                'Attribute.category' => $category,
-                               'Attribute.value' => $value
+                               'Attribute.value' => $value,
+                               'Attribute.comment' => $comment
                );
                if (isset($this->data['Attribute']['id'])) {
                        $conditions['Attribute.id !='] = $this->data['Attribute']['id'];
```

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
That is weird, could you describe the steps you took to produce the error?
Did you edit it via the UI or REST?

**Comment by elhoim** [comment]
@devnull- any updates? If not, I would like to close this.

**Comment by devnull-** [comment]
Hello all,

Sorry for the delay of my reply. 

@iglocska : The bug happened via the UI


@elhoim & @iglocska : Me too, I didn't find a way to reproduce the bug. Until we can't find a way to reproduce the bug, I propose to close the ticket. I will reopen it if I find something new :) 

Don't hesitate to contact me if you need some help and if you have some question.

devnull-
