### ISSUE TITLE
Feed update process with core updates

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#5610]
A question to the "MISP Powers that Be", when you send a core update, how do you address feeds? Do you simply append changes to the database or do you create a new table? My reason for this question is, if we made changes to the existing feeds, do those changes carry or do we have to we have to start from scratch and add/delete activate/deactivate all our current changes?

**Comment by mokaddem** [comment]
Hello,
Whenever you update MISP, configuration file and data should not be altered in a way you lost something.
If you experience a bug or issue with your feed configuration after an update, that's definitely a bug that should be addressed.
Please, re-open the issue if applicable.
Thanks!
