### ISSUE TITLE
Export Events in STIX v1 in XML

### ISSUE THREAD

**Issue by mohlcyber** [MISP/MISP#5618]
I am using MISP 2.4.121 and looking for a way to export events in stix v1 in xml format.

Before the release of 2.4.120 i was able to export events in stix version 1.x in xml. With the current version i am only able to export stix in json. 

Is it correct that both return_formats (stix, stix-json) return a similar output? I was expecting to get stix in xml and stix-json in json. 

Unfortunately I need an STIX v1 XML output to get our SIEM integration working.
If you need any further details please let me know.

All the best,
Martin

**Comment by RichieB2B** [comment]
Are you using the web interface or API? How exactly are you doing the export?

**Comment by mohlcyber** [comment]
Apologies forgot to mention. I am talking about the API. 

https://<IP>/events/restSearch
{
    "returnFormat": "stix",
    "eventid": "1147"
}

Same applies to the PyMISP libraries. When I use a similar function like this:
self.misp.search(eventid=eid, tags=tags, return_format='stix')
I am receiving an JSON as an output.

Via the UI i can successfully export the event into a STIX XML file.
I just checked - when i use: https://<IP>/events/restSearch/stix/eventid:1147
I get the expected XML. Something strange.

**Comment by RichieB2B** [comment]
With the API you need to set the Accept header:
```
Accept: application/xml
```

**Comment by iglocska** [comment]
Interesting, that should work as before, sounds like a bug. For now until
we fix it, could you try to append .xml at the end of the url?

**Comment by mohlcyber** [comment]
I used the PyMISP libraries and the accepted XML header. 
I guess this might be more related to the PyMISP libraries.

Just seen in the change log of PyMISP the following.

**v2.4.120 (2020-01-17)**
.....
Search with the STIX output returns a json STIX. [Raphaël Vinot]
Was XML before.
.....
Is there any reason for this? Do you want me to create an issue on the PyMISP repo?
Might be more a question to Raphael why this has changed and if there is a way of exporting STIX1 in xml via the PyMISP libraries.
