### ISSUE TITLE
Force published status on event

### ISSUE THREAD

**Issue by Feldunost** [MISP/MISP#5619]
| Type of issue             | Support
| OS version (server)       Ubuntu 18.04
| MISP version 2.4.120

I am looking for an auto-publish for a specific event, since as soon as I add more artifacts manually, it goes automatically in unpublished state. This event is set onto my own organization only, so there is no need to put as unpublished every time I manually add an IOC.

It does exists in file or feeds import, but goes unpublished if it's trough API or manual adding.
I am pretty sure it's possible but not really explained around.

**Comment by mokaddem** [comment]
Hey,
In contrast to Feeds, there is no such Event auto-publish feature as of now.
However, one thing you can do to achieve that functionality could be to:
1. Create a local tag: ``action:auto-publish``
2. Add a CRON job running every ``x`` to publish your event
     - In the CRON job, use PyMISP or CURL to fetch all Events tagged with ``action:auto-publish``
     - Publish these Events

Cheers

**Comment by iglocska** [comment]
To expand on this: You can instead use a filter for published:0 and your own organisation, perhaps also distribution:0 if you just want to auto publish your org only data to avoid accidentally triggering a sync automatically.

So, assuming your local org_id is 1:

POST to:
`/events/restSearch`

body:
```
{
    "published": 0,
    "org_id": 1,
    "distribution": 0,
    "metadata": 1
}
```

This will return a JSON with the metadata of all events that need publishing, extract the local event IDs.
Iterate through them in your script, publish each by POSTing to `/events/publish/[event_id]`

**Comment by Feldunost** [comment]
Hello,

Thanks iglocska for additionnal informations.

As the first POST request does indeed effectively works and returns the information, it gives too much informations in the result anwer, below an example :

{"response": [{"Event":{"id":"1",   [.........]  "RelatedEvent":[{"Event":{"id":"18",   [........]  

As there are several EventIDs, I am unable to parse this result output since it gets confused with RelatedEvent. So i went directly to edit specific EventID, even if they are already published, it will be a check.

Below the CURL for anyone who gets this problem.

`curl -d '{}' -H "Authorization: Your API Key" -H "Accept: application/json" -H "Content-type: application/json" -X POST https://MISP-SERVER-IP/events/publish/eventID`

Currently faster than /edit/event POST since it returns whole batch of attributes.

Thanks a lot for the help guys.
