### ISSUE TITLE
composer.phar not compatible with PHP 7.3

### ISSUE THREAD

**Issue by iwitz** [MISP/MISP#5620]
# This template is meant for bug reports, if you have a feature request user the other template.
The composer.phar file cannot be used to install MISP's dependencies using PHP 7.3

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL 7.7
| OS version (client)       | N/A
| PHP version               | 7.3
| MISP version / git hash   | 2.4.120
| Browser                   | N/A

### Expected behavior
Composer dependencies should be installed by the following command :
`scl enable rh-php73 "php composer.phar install" `

### Actual behavior
The installation crashes :

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file


  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

Although the installation does work with a fresh PHP 7.2 installation.

### Steps to reproduce the behavior

1. Install PHP 7.3 from SCL as well as the other PHP packages mentioned by the documentation
2. Try to install the PHP dependencies using the aforementioned command

### Logs, screenshots, configuration dump, ...
Seems to me like this is related to a backwards-incompatible [change ](https://www.php.net/manual/en/migration73.incompatible.php) introduced in PHP 7.3 ; if that is the case, the "continue" statement in composer.phar should simply be replaced by "break". I cannot test it since the composer.phar file is signed, and I don't know how to disable signature verification.

**Comment by JakubOnderka** [comment]
There is already pull request for this: https://github.com/MISP/MISP/pull/5149

**Comment by Rafiot** [comment]
Merged :)

**Comment by iglocska** [comment]
Indeed missed the pr, thanks!
