### ISSUE TITLE
When viewing or creating some events I'm welcomed with "An Internal error has occurred"

### ISSUE THREAD

**Issue by Gudmo** [MISP/MISP#5621]
#5245 # Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 LTS
| OS version (client)       | Win10
| PHP version               | 7.2.24-0ubuntu0.18.04.2 
| MISP version / git hash   | 2.4.121
| Browser                   | Chrome

### Support Questions
After upgrading to 2.4.121 and going through the database cleanup demanded in the Diagnostic page I am met with an Internal Error when viewing some events and when creating events.
Even though the error occurs when creating the event, it is still in the database but I cannot view it anymore

I have a strong suspicion that this is related to the object_uuid column of the object_references (Since it was one of the columns the diagnosic page was whining about)
To resolve those errors I did this
ALTER TABLE `object_references` DROP COLUMN `object_uuid`;
ALTER TABLE `object_template_elements` DROP COLUMN `disable_correlations`;

### Logs, screenshots, configuration dump, ...
MariaDB [misp]> select * from events where id = '79098';
+-------+--------+------------+----------------+---------+--------------------------------------+-----------+----------+-----------------+---------+------------+--------------+------------------+---------------------+--------+-----------------+-------------------+--------------------+---------------------+--------------+
| id    | org_id | date       | info           | user_id | uuid                                 | published | analysis | attribute_count | orgc_id | timestamp  | distribution | sharing_group_id | proposal_email_lock | locked | threat_level_id | publish_timestamp | sighting_timestamp | disable_correlation | extends_uuid |
+-------+--------+------------+----------------+---------+--------------------------------------+-----------+----------+-----------------+---------+------------+--------------+------------------+---------------------+--------+-----------------+-------------------+--------------------+---------------------+--------------+
| 79098 |      1 | 2020-02-12 | Fraud - Police |       5 | 5e441ecc-64e0-4e2f-841b-085eac1a0141 |         0 |        0 |               4 |       1 | 1581522958 |            4 |                4 |                   0 |      0 |               1 |                 0 |                  0 |                   0 |              |
+-------+--------+------------+----------------+---------+--------------------------------------+-----------+----------+-----------------+---------+------------+--------------+------------------+---------------------+--------+-----------------+-------------------+--------------------+---------------------+--------------+
1 row in set (0.00 sec)

**Comment by Gudmo** [comment]
![image](https://user-images.githubusercontent.com/3922275/74353364-b8035e00-4db1-11ea-9b96-438e338a3f12.png)

**Comment by Gudmo** [comment]
![image](https://user-images.githubusercontent.com/3922275/74353465-dc5f3a80-4db1-11ea-884b-6b4860f7ab9e.png)

**Comment by Gudmo** [comment]
![image](https://user-images.githubusercontent.com/3922275/74353745-42e45880-4db2-11ea-8476-0005884d9d81.png)

**Comment by Gudmo** [comment]
I'm suspecting I can only view events that do not have objects

**Comment by Gudmo** [comment]
My current Indexes - possibly I have to recreate one of those.
+--------------+---------------------------------+---------------------------------+------------+------------+-------------------------------+
| index_schema | index_name                      | index_columns                   | index_type | is_unique  | table_name                    |
+--------------+---------------------------------+---------------------------------+------------+------------+-------------------------------+
| misp         | 1_attribute_id                  | 1_attribute_id                  | BTREE      | Not Unique | correlations                  |
| misp         | 1_event_id                      | 1_event_id                      | BTREE      | Not Unique | correlations                  |
| misp         | 1_event_id                      | 1_event_id                      | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | 1_shadow_attribute_id           | 1_shadow_attribute_id           | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | all_orgs                        | all_orgs                        | BTREE      | Not Unique | decaying_models               |
| misp         | attribute_id                    | attribute_id                    | BTREE      | Not Unique | attribute_tags                |
| misp         | attribute_id                    | attribute_id                    | BTREE      | Not Unique | correlations                  |
| misp         | attribute_id                    | attribute_id                    | BTREE      | Not Unique | fuzzy_correlate_ssdeep        |
| misp         | attribute_id                    | attribute_id                    | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | attribute_id                    | attribute_id                    | BTREE      | Not Unique | sightings                     |
| misp         | a_sharing_group_id              | a_sharing_group_id              | BTREE      | Not Unique | correlations                  |
| misp         | a_sharing_group_id              | a_sharing_group_id              | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | category                        | category                        | BTREE      | Not Unique | attributes                    |
| misp         | category                        | category                        | BTREE      | Not Unique | shadow_attributes             |
| misp         | chunk                           | chunk                           | BTREE      | Not Unique | fuzzy_correlate_ssdeep        |
| misp         | collection_uuid                 | collection_uuid                 | BTREE      | Not Unique | galaxy_clusters               |
| misp         | deleted                         | deleted                         | BTREE      | Not Unique | attributes                    |
| misp         | distribution                    | distribution                    | BTREE      | Not Unique | objects                       |
| misp         | email                           | email                           | BTREE      | Not Unique | users                         |
| misp         | enabled                         | enabled                         | BTREE      | Not Unique | decaying_models               |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | attributes                    |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | attribute_tags                |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | correlations                  |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | event_delegations             |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | event_graph                   |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | event_locks                   |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | event_tags                    |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | objects                       |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | shadow_attributes             |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | sightings                     |
| misp         | event_id                        | event_id                        | BTREE      | Not Unique | threads                       |
| misp         | event_orgc                      | event_orgc                      | BTREE      | Not Unique | event_blacklists              |
| misp         | event_org_id                    | event_org_id                    | BTREE      | Not Unique | shadow_attributes             |
| misp         | event_uuid                      | event_uuid                      | BTREE      | Not Unique | event_blacklists              |
| misp         | event_uuid                      | event_uuid                      | BTREE      | Not Unique | shadow_attributes             |
| misp         | expires                         | expires                         | BTREE      | Not Unique | cake_sessions                 |
| misp         | extends_uuid                    | extends_uuid                    | BTREE      | Not Unique | events                        |
| misp         | first_seen                      | first_seen                      | BTREE      | Not Unique | attributes                    |
| misp         | first_seen                      | first_seen                      | BTREE      | Not Unique | objects                       |
| misp         | first_seen                      | first_seen                      | BTREE      | Not Unique | shadow_attributes             |
| misp         | galaxy_cluster_id               | galaxy_cluster_id               | BTREE      | Not Unique | galaxy_elements               |
| misp         | galaxy_cluster_id               | galaxy_cluster_id               | BTREE      | Not Unique | galaxy_reference              |
| misp         | galaxy_id                       | galaxy_id                       | BTREE      | Not Unique | galaxy_clusters               |
| misp         | geographical_area               | geographical_area               | BTREE      | Not Unique | noticelists                   |
| misp         | host                            | host                            | BTREE      | Not Unique | sightingdbs                   |
| misp         | info                            | info                            | BTREE      | Not Unique | events                        |
| misp         | input_source                    | input_source                    | BTREE      | Not Unique | feeds                         |
| misp         | key                             | key                             | BTREE      | Not Unique | galaxy_elements               |
| misp         | last_seen                       | last_seen                       | BTREE      | Not Unique | attributes                    |
| misp         | last_seen                       | last_seen                       | BTREE      | Not Unique | objects                       |
| misp         | last_seen                       | last_seen                       | BTREE      | Not Unique | shadow_attributes             |
| misp         | meta-category                   | meta-category                   | BTREE      | Not Unique | objects                       |
| misp         | meta-category                   | meta-category                   | BTREE      | Not Unique | object_templates              |
| misp         | model_id                        | model_id                        | BTREE      | Not Unique | decaying_model_mappings       |
| misp         | name                            | name                            | BTREE      | Not Unique | decaying_models               |
| misp         | name                            | name                            | BTREE      | Not Unique | galaxies                      |
| misp         | name                            | name                            | BTREE      | Not Unique | noticelists                   |
| misp         | name                            | name                            | BTREE      | Not Unique | objects                       |
| misp         | name                            | name                            | BTREE      | Not Unique | object_relationships          |
| misp         | name                            | name                            | BTREE      | Not Unique | object_templates              |
| misp         | name                            | name                            | BTREE      | Not Unique | organisations                 |
| misp         | name                            | name                            | BTREE      | Not Unique | sightingdbs                   |
| misp         | name                            | name                            | BTREE      | Not Unique | tags                          |
| misp         | namespace                       | namespace                       | BTREE      | Not Unique | galaxies                      |
| misp         | noticelist_id                   | noticelist_id                   | BTREE      | Not Unique | noticelist_entries            |
| misp         | numerical_value                 | numerical_value                 | BTREE      | Not Unique | tags                          |
| misp         | numerical_value                 | numerical_value                 | BTREE      | Not Unique | taxonomy_entries              |
| misp         | numerical_value                 | numerical_value                 | BTREE      | Not Unique | taxonomy_predicates           |
| misp         | object_id                       | object_id                       | BTREE      | Not Unique | attributes                    |
| misp         | object_id                       | object_id                       | BTREE      | Not Unique | object_references             |
| misp         | object_relation                 | object_relation                 | BTREE      | Not Unique | attributes                    |
| misp         | object_relation                 | object_relation                 | BTREE      | Not Unique | object_template_elements      |
| misp         | old_id                          | old_id                          | BTREE      | Not Unique | shadow_attributes             |
| misp         | organisation_uuid               | organisation_uuid               | BTREE      | Not Unique | sharing_groups                |
| misp         | orgc_id                         | orgc_id                         | BTREE      | Not Unique | events                        |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | correlations                  |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | decaying_models               |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | events                        |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | event_delegations             |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | event_graph                   |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | notification_logs             |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | object_templates              |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | rest_client_histories         |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | servers                       |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | sharing_groups                |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | sharing_group_orgs            |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | sightingdb_orgs               |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | sightings                     |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | tags                          |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | tag_collections               |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | threads                       |
| misp         | org_id                          | org_id                          | BTREE      | Not Unique | users                         |
| misp         | owner                           | owner                           | BTREE      | Not Unique | sightingdbs                   |
| misp         | port                            | port                            | BTREE      | Not Unique | sightingdbs                   |
| misp         | post_id                         | post_id                         | BTREE      | Not Unique | posts                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | admin_settings                |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | attributes                    |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | attribute_tags                |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | cake_sessions                 |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | correlations                  |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | decaying_models               |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | decaying_model_mappings       |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | events                        |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | event_blacklists              |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | event_delegations             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | event_graph                   |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | event_locks                   |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | event_tags                    |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | favourite_tags                |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | feeds                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | fuzzy_correlate_ssdeep        |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | galaxies                      |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | galaxy_clusters               |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | galaxy_elements               |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | galaxy_reference              |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | jobs                          |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | logs                          |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | news                          |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | noticelists                   |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | noticelist_entries            |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | notification_logs             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | objects                       |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | object_references             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | object_relationships          |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | object_templates              |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | object_template_elements      |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | organisations                 |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | org_blacklists                |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | posts                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | regexp                        |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | rest_client_histories         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | roles                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | servers                       |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | shadow_attributes             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | shadow_attribute_correlations |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sharing_groups                |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sharing_group_orgs            |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sharing_group_servers         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sightingdbs                   |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sightingdb_orgs               |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | sightings                     |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | tags                          |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | tag_collections               |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | tag_collection_tags           |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | tasks                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | taxonomies                    |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | taxonomy_entries              |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | taxonomy_predicates           |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | templates                     |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | template_elements             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | template_element_attributes   |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | template_element_files        |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | template_element_texts        |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | template_tags                 |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | threads                       |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | threat_levels                 |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | users                         |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | user_settings                 |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | warninglists                  |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | warninglist_entries           |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | warninglist_types             |
| misp         | PRIMARY                         | id                              | BTREE      | Unique     | whitelist                     |
| misp         | priority                        | priority                        | BTREE      | Not Unique | servers                       |
| misp         | referenced_galaxy_cluster_id    | referenced_galaxy_cluster_id    | BTREE      | Not Unique | galaxy_reference              |
| misp         | referenced_galaxy_cluster_type  | referenced_galaxy_cluster_type  | BTREE      | Not Unique | galaxy_reference              |
| misp         | referenced_galaxy_cluster_value | referenced_galaxy_cluster_value | BTREE      | Not Unique | galaxy_reference              |
| misp         | referenced_id                   | referenced_id                   | BTREE      | Not Unique | object_references             |
| misp         | referenced_uuid                 | referenced_uuid                 | BTREE      | Not Unique | object_references             |
| misp         | relationship_type               | relationship_type               | BTREE      | Not Unique | object_references             |
| misp         | remote_org_id                   | remote_org_id                   | BTREE      | Not Unique | servers                       |
| misp         | server_id                       | server_id                       | BTREE      | Not Unique | sharing_group_servers         |
| misp         | server_id                       | server_id                       | BTREE      | Not Unique | users                         |
| misp         | setting                         | setting                         | BTREE      | Not Unique | user_settings                 |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | attributes                    |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | correlations                  |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | events                        |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | objects                       |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | shadow_attribute_correlations |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | sharing_group_orgs            |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | sharing_group_servers         |
| misp         | sharing_group_id                | sharing_group_id                | BTREE      | Not Unique | threads                       |
| misp         | sightingdb_id                   | sightingdb_id                   | BTREE      | Not Unique | sightingdb_orgs               |
| misp         | source                          | source                          | BTREE      | Not Unique | sightings                     |
| misp         | source_uuid                     | source_uuid                     | BTREE      | Not Unique | object_references             |
| misp         | sync_user_id                    | sync_user_id                    | BTREE      | Not Unique | sharing_groups                |
| misp         | tag_id                          | tag_id                          | BTREE      | Not Unique | attribute_tags                |
| misp         | tag_id                          | tag_id                          | BTREE      | Not Unique | event_tags                    |
| misp         | tag_id                          | tag_id                          | BTREE      | Not Unique | favourite_tags                |
| misp         | tag_name                        | tag_name                        | BTREE      | Not Unique | galaxy_clusters               |
| misp         | taxonomy_id                     | taxonomy_id                     | BTREE      | Not Unique | taxonomy_predicates           |
| misp         | taxonomy_predicate_id           | taxonomy_predicate_id           | BTREE      | Not Unique | taxonomy_entries              |
| misp         | template_uuid                   | template_uuid                   | BTREE      | Not Unique | objects                       |
| misp         | template_version                | template_version                | BTREE      | Not Unique | objects                       |
| misp         | thread_id                       | thread_id                       | BTREE      | Not Unique | posts                         |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | event_graph                   |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | event_locks                   |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | objects                       |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | object_references             |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | rest_client_histories         |
| misp         | timestamp                       | timestamp                       | BTREE      | Not Unique | user_settings                 |
| misp         | type                            | type                            | BTREE      | Not Unique | attributes                    |
| misp         | type                            | type                            | BTREE      | Not Unique | galaxies                      |
| misp         | type                            | type                            | BTREE      | Not Unique | galaxy_clusters               |
| misp         | type                            | type                            | BTREE      | Not Unique | notification_logs             |
| misp         | type                            | type                            | BTREE      | Not Unique | object_template_elements      |
| misp         | type                            | type                            | BTREE      | Not Unique | shadow_attributes             |
| misp         | type                            | type                            | BTREE      | Not Unique | sightings                     |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | event_graph                   |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | event_locks                   |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | favourite_tags                |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | object_templates              |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | rest_client_histories         |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | tags                          |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | tag_collections               |
| misp         | user_id                         | tag_id                          | BTREE      | Not Unique | tag_collection_tags           |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | threads                       |
| misp         | user_id                         | user_id                         | BTREE      | Not Unique | user_settings                 |
| misp         | uuid                            | uuid                            | BTREE      | Unique     | events                        |
| misp         | uuid                            | uuid                            | BTREE      | Unique     | sharing_groups                |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | attributes                    |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | decaying_models               |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | galaxies                      |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | galaxy_clusters               |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | objects                       |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | object_templates              |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | organisations                 |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | shadow_attributes             |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | sightings                     |
| misp         | uuid                            | uuid                            | BTREE      | Not Unique | tag_collections               |
| misp         | uuid                            | tag_collection_id               | BTREE      | Not Unique | tag_collection_tags           |
| misp         | value                           | value                           | BTREE      | Not Unique | correlations                  |
| misp         | value                           | value                           | BTREE      | Not Unique | galaxy_clusters               |
| misp         | value                           | value                           | BTREE      | Not Unique | galaxy_elements               |
| misp         | value1                          | value1                          | BTREE      | Not Unique | attributes                    |
| misp         | value1                          | value1                          | BTREE      | Not Unique | shadow_attributes             |
| misp         | value2                          | value2                          | BTREE      | Not Unique | attributes                    |
| misp         | value2                          | value2                          | BTREE      | Not Unique | shadow_attributes             |
| misp         | version                         | version                         | BTREE      | Not Unique | decaying_models               |
| misp         | version                         | version                         | BTREE      | Not Unique | galaxy_clusters               |
| misp         | warninglist_id                  | warninglist_id                  | BTREE      | Not Unique | warninglist_entries           |
+--------------+---------------------------------+---------------------------------+------------+------------+-------------------------------+

**Comment by StefanKelm** [comment]
Any hints in `resque-2020-02-xx.log` or `error.log` such as

`[PDOException] SQLSTATE[HY000]: General error: 1364 Field 'ip' doesn't have a default value`

?

**Comment by Gudmo** [comment]
Like this ? :)
2020-02-12 16:13:36 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ObjectReference.object_uuid' in 'field list'
Request URL: /events/view/79097
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `ObjectR...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `ObjectR...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `ObjectR...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(MispObject), 'SELECT `ObjectR...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1411): DboSource->queryAssociation(Object(MispObject), Object(ObjectReference), 'hasMany', 'ObjectReference', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(MispObject), 'hasMany', 'Object', Array, Array, true, Array, 2, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Event), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#9 /var/www/MISP/app/Model/Event.php(2135): Model->find('all', Array)
#10 /var/www/MISP/app/Controller/EventsController.php(1667): Event->fetchEvent(Array, Array)
#11 [internal function]: EventsController->view('79097')
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#15 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}

**Comment by iglocska** [comment]
Also keep in mind schema changes are not automatically reflected, you need to clean the model caches in server settings, diagnostics.

**Comment by Gudmo** [comment]
Whammo, that worked... TL;DR on that page :)

**Comment by SteveClement** [comment]
seemingly solved :)
