### ISSUE TITLE
Search attributes not having first seen or last seen.

### ISSUE THREAD

**Issue by di-iode** [MISP/MISP#5622]
### Work environment

| Questions         | Answers
|-----------------|--------------------
| MISP version    | 2.4.120,

### Support Questions

Hello, with version 2.4.120 of MISP, the function "search attributes" has changed slightly.
How search attributes not having first seen or last seen ?
It's a real problem for me, we have a big historical events without first seen or last seen.

Thank's for you help

**Comment by angarod** [comment]
I think this is related to https://github.com/MISP/MISP/commit/1e49cc6aabc67145138de85b914a26ec4badd974

**Comment by mokaddem** [comment]
@angarod precisely!
If `*_seen` is unset, you have everything.
@di-iode wanting to search for Attribute that doesn't have `*_seen` set seems a bit unusual for me. Do you have any use case in mind where it would be useful?
