### ISSUE TITLE
Updated to  v2.4.121 - never ending run_updates job

### ISSUE THREAD

**Issue by carnak** [MISP/MISP#5624]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.121 (413399611ed41665edab24422bdb1fdead5286be) 
| Browser                   | n/a

### Expected behavior

Don't expect to have jobs constantly running

### Actual behavior

Since the upgrade, system has not stopped running Job type: run_updates, Input: command:, Message: Updating.

### Steps to reproduce the behavior

Not sure how reproducible this is... short of standing a new instance, which I am on the verge of atm

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/1611753/74426965-37466f80-4e4e-11ea-8de2-fa324acdba71.png)

**Comment by carnak** [comment]
I seem to have been able to kill them all at this point, and they (thankfully) don't seem to be re-spawning now.

**Comment by mokaddem** [comment]
Glad you solved the issue!
By any chance, if you manage to find a way to make this bug reproducible, I would be very interested.
Thanks!

**Comment by criptk** [comment]
I have the same exact problem.
![image](https://user-images.githubusercontent.com/19441833/114618542-50b79700-9c5e-11eb-879a-9ef32d5b3f32.png)

Currently installed version… v2.4.140 (fe34ec7857aacf3525958021bfc444965ff0f2cf)
root@MISP:/var/www/MISP/app/tmp/logs# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
root@MISP:/var/www/MISP/app/tmp/logs#
CPU0: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (family: 0x6, model: 0x4f, stepping: 0x0)
root@MISP:/var/www/MISP/app/tmp/logs# vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 1030964 560700 21771300    0    0     6    42    1    0  1  0 99  0  0
root@MISP:/var/www/MISP/app/tmp/logs#
VM running on SSD

**Comment by mokaddem** [comment]
@criptk do you have entries each time you issue a request?
what does the diagnostic and update progress page tell? Is there something in progress?
Could you also restart workers - just to make sure?
Thanks
