### ISSUE TITLE
Date picker when adding event is displayed in a weird way

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#563]
The date picker used when adding an event is displayed in a weird way (partially and on top of the date field instead of under). Config: Mac OS X, Chrome latest.

![image](https://cloud.githubusercontent.com/assets/178521/8590922/01c07a8c-2625-11e5-8eda-4a55c40cf16c.png)

**Comment by Rafiot** [comment]
Works for me. Please reopen if it is still the case for you.
