### ISSUE TITLE
PHP Version (>7.4 recommended): 7.2.24-0ubuntu0.18.04.2 (Update highly recommended)

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#5634]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.121, 413399611ed41665edab24422bdb1fdead5286be

### Support Questions
You state that it is recommended to upgrade php to version 7.4 or higher. Default Ubuntu 18.04 LTS only has php 7.2 in its repositories. Could you provide support on how to install this correctly?

**Comment by iglocska** [comment]
7.2 will work fine with MISP. However, since 7.2 is approaching EOL we recommend upgrading - for the question on how to upgrade it for Ubuntu specifically (if you choose to do so, again, it's not required) is a question best asked on the Ubuntu support forums.
