### ISSUE TITLE
[Search Attributes] Searches by Event ID or Event UUID do not return matches

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#5636]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | Ubuntu
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.118
| Browser                   | All Browsers

### Expected behavior
Enter Event ID or UUID into [Search Attributes] Section:

_"Being attributes of the following event IDs, event UUIDs or attribute UUIDs"_
Have matching results returned

### Actual behavior

No results returned.

### Steps to reproduce the behavior

1. Get representative existing Event IDs and Event UUIDs
2. Enter each example one at a time in [Search Attributes] "Being attributes of the following event IDs, event UUIDs or attribute UUIDs"
3. Also try using mySQL "%" prefixes/suffixes

**Comment by github-germ** [comment]
I am seeing the same issue in 2.4.121

**Comment by StefanKelm** [comment]
Related to #3930 ?

**Comment by packet-rat** [comment]
Follow-up:  This is a big deficiency for us.  Can we please get it on the punch list for a fix or workaround?

**Comment by github-germ** [comment]
Anybody able look at this yet? If you need more info, give a shout. THANKS!

**Comment by packet-rat** [comment]
Can we PLEASE get a response to this?  Whatever the answer might be, we simply need to know.

**Comment by iglocska** [comment]
Should be fixed now.

**Comment by iglocska** [comment]
Needed some more work, should be fixed now (tm)

**Comment by packet-rat** [comment]
Many thanks Andras!
Pat Maroney




On Apr 2, 2020, at 1:05 AM, Andras Iklody <notifications@github.com> wrote:


Needed some more work, should be fixed now (tm)
