### ISSUE TITLE
STIX 1.1 import errors on certain files

### ISSUE THREAD

**Issue by sfinlon** [MISP/MISP#5637]
### Work environment 

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.2.24
| MISP version / git hash   |  v2.4.121 (6776ea2b26442d9dd09b5400c2d2631d63cd763f)
| Browser                   | Chrome 

### Expected behavior
File imported successfully

### Actual behavior
Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.

### Steps to reproduce the behavior
Import the STIX v1.1 file available here: https://www.us-cert.gov/ncas/analysis-reports/ar20-045a

### Logs, screenshots, configuration dump, ...
Diagnostic page shows everything is installed and working. Other STIX 1.1 files from US-CERT import fine, these new ones from them do not.

**Comment by chrisr3d** [comment]
Do you have anything in the log file you can find under `/var/www/MISP/app/tmp/logs/exec-errors.log`?
I cannot reproduce your issue right now, this file does not raise any issue or exception for me

**Comment by sfinlon** [comment]
```
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1446, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1441, in main
    stix_parser.build_misp_event(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 87, in build_misp_event
    self.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1206, in build_misp_dict
    self.parse_external_observable(self.event.observables.observables)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1317, in parse_external_observable
    attribute_type, attribute_value, compl_data = self.handle_attribute_type(properties, title=title)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 229, in handle_attribute_type
    return getattr(self, self.attribute_types_mapping[xsi_type])(*args)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 632, in handle_pe
    pe_uuid = self.parse_pe(properties)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 645, in parse_pe
    header_object = MISPObject('pe-section', misp_objects_path_custom=_MISP_objects_path)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 612, in __init__
    self._set_template(kwargs.get('misp_objects_path_custom'))
  File "/var/www/MISP/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 697, in _set_template
    self._known_template = self._load_template_path(self.misp_objects_path / self.name / 'definition.json')
  File "/var/www/MISP/venv/lib/python3.6/site-packages/pymisp/mispevent.py", line 652, in _load_template_path
    self._definition: Union[dict, None] = self._load_json(template_path)
  File "/var/www/MISP/venv/lib/python3.6/site-packages/pymisp/abstract.py", line 50, in _load_json
    data = load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/var/www/MISP/venv/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2310: ordinal not in range(128)
```

python version 3.6.9
stix 1.2.0.7
stix2 1.3.0

**Comment by sfinlon** [comment]
> Do you have anything in the log file you can find under `/var/www/MISP/app/tmp/logs/exec-errors.log`?
> I cannot reproduce your issue right now, this file does not raise any issue or exception for me

My version of pymisp is also the latest at 2.4.121.1

Is there a newer version of the stix2misp.py script?

**Comment by chrisr3d** [comment]
I try to reproduce the issue and will go back to you

**Comment by Rafiot** [comment]
Could it be that: https://github.com/docker-library/python/issues/13

**Comment by sfinlon** [comment]
> Could it be that: [docker-library/python#13](https://github.com/docker-library/python/issues/13)

My system locale was set to en_us.UTF-8, I changed it to C.UTF-8 and still am getting the same error.

**Comment by mdavis332** [comment]
This was caused by a json.load() call before encoding='utf-8' was added to the func call in a later version of PyMISP's abstract.py. The venv pymisp lib was not updating with the webUI update button, so I manually updated by following the directions here https://www.circl.lu/doc/misp/updating-python/.

This is probably safe to close if @sfinlon is good with it.

**Comment by enjeck** [comment]
> This is probably safe to close if @sfinlon is good with it.

@sfinlon Are you good with closing this issue?
