### ISSUE TITLE
MISP-Graph code not working

### ISSUE THREAD

**Issue by ClaraMS** [MISP/MISP#5638]
### Work environment

|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.120
| Browser                   | Mozilla Firefox v73.0

I'm trying to get the dot file from the XML files from a MISP event but when I use the misp-graph tool is giving me an empty .dot file. 
Maybe the code is a bit old so know the features from XML files are different, so I tried to download the .dot file directly from the graph viewer in the MISP event:
![imagen](https://user-images.githubusercontent.com/24474498/74717911-81a26480-5231-11ea-9e32-d45cb76492c4.png)
But again, it downloads an empty .dot file.

Is there any tool or way to get the graph from MISP so I could open it with gephi or other software available for viewing graphs in local? I would like to get the graph downloaded so I could expand it and view it in detail.

Thank you in advance!

**Comment by mokaddem** [comment]
Hey, From the screenshot, i can see that you don't have any relation in your event. All Attributes are unreferenced. That's why you have an empty file.
If after adding relation you still have an empty DOT file, feel free to re-open the issue.
Cheers
