### ISSUE TITLE
Question about PyMISP add_sighting method

### ISSUE THREAD

**Issue by carnak** [MISP/MISP#5642]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  CentOS
| OS version (client)       | Win10
| PHP version               | n/a
| MISP version / git hash   |  v2.4.121 (26fff7f0530ceb3ed127910e844143c49413cd5d)
| Browser                   | n/a

### Support Questions

Could you provide a simple example of how to use PyMISP function "add_sighting", as following code used to work, but just broke with the latest release:

    source=ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=False, proxies=proxies)
    for obj in correlated_attribute:
          source.add_sighting(0,obj)

In the example above, "obj" contains the UUID of attributes for which I want to add a sighting.

I am just trying to add sightings to attributes which are observed on my local network.

Would the correct invocation now be something like:
   
    source.add_sighting(obj)

Thanks,

**Comment by Rafiot** [comment]
You can find example on how to use the method there: https://github.com/MISP/PyMISP/blob/master/tests/testlive_comprehensive.py#L835

In you case, the call will be either
`source.add_sighting({'value': obj['value']})` if you want to add a sighting to all the attributes with that value
or 
`source.add_sighting({'value': obj['value']}, obj)` if you want to add a sighting to the specific attribute

**Comment by carnak** [comment]
Thanks Raphael!  Will adjust my code accordingly.

Best Regards,
Alan
