### ISSUE TITLE
Incorrect PyMISP version installed, found 2.4.96, expecting >2.4.120

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#5648]
| Type of issue | Support
| OS version (server) | Ubuntu
| OS version (client) | Win10
| PHP version | 7.2
| MISP version / git hash | v2.4.121 (0a605ed4d3673a4463cc6b2f11325c4eb1215029) 
| Browser | Mozilla Firefox v73.0.1

I upgraded MISP successfully from 2.4.120 to 2.4.121. The sub-modules updated successfully also but I see the following for PyMISP:

"PYMISP library version…Incorrect PyMISP version installed, found 2.4.96, expecting >2.4.120"

Just in case it was a permissions issue I reset MISP permissions using the following but this did not help:

sudo chown -R www-data:www-data /var/www/MISP
sudo chmod -R 750 /var/www/MISP
sudo chmod -R g+ws /var/www/MISP/app/tmp
sudo chmod -R g+ws /var/www/MISP/app/files
sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp

![image](https://user-images.githubusercontent.com/8250365/74789463-7a537900-527a-11ea-999b-0a686d3efaab.png)

**Comment by Rafiot** [comment]
Yes, PyMISP isn't updated automatically by MISP. It is probably unimportant, but if you want to fix that, you will need to update PyMISP either systemwide, or in the virtual environment, depending on how you installed MISP.

**Comment by timhux123** [comment]
Thanks for the quick response! If MISP does not update PyMISP then why is it listed in the sub-module section under the "Server Settings & Maintenance" page and allows you to update it from here? 

![image](https://user-images.githubusercontent.com/8250365/74849440-4f126d80-52fe-11ea-95b5-23189c25366b.png)

**Comment by Rafiot** [comment]
So yeah, it pulls it, but doesn't run the install script. This should definitely be changed.

**Comment by timhux123** [comment]
I see. Thanks for the great info. Closing case.
