### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by woodonggyu** [MISP/MISP#5657]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04 (VMware 15)
| PHP version               | 7.2.24
| MISP version / git hash   | f27125a2cd54b088b95072ff1d87c2a9edde3fdc
| Browser                   | Chrome

### Actual behavior
```
The request has been black-holed
Error: The requested address '/users/login' was not found on this server.
```
### Steps to reproduce the behavior
After login, I didn't work long time. and timeout works. 
and I tried to login again. but it didn't works. 

I searched a lot of similar issues. but I didn't find a way to reliably solve the problem. How can i solve it?

For example According to #4440, "All forms have a timeout (15min iirc) and all of them can only be submitted once. If you use your browser's "back" button and resubmit the form MISP will consider it as a potential attempt at form tampering."

How to login again to these problem? 

I had tried below methods to solve the problem
1. Clean up browser cache
2. Reset the password from the GUI
3. sudo /var/www/MISP/app/Console/cake Password user@domainname.com Password1234

Thanks.

**Comment by mokaddem** [comment]
Isn't just reloading the page (F5) before login-in solve the issue?

**Comment by woodonggyu** [comment]
Although not accurate, I think this issue is caused by logging in using multiple browers. sometimes, I tried to login many times. maybe relate with #2440. 

Anyway, currently I'm using very careful. 
If occur these problem again, I will open new issue with detail error log.

thank you for your help.
