### ISSUE TITLE
[BadRequestException] csrf

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#566]
Any idea about the following error?

Error: [BadRequestException] csrf
Request URL: /users/login
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(242): SecurityComponent->blackHole(Object(UsersController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(UsersController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by iglocska** [comment]
It's the cross site request forgery protection, it happens when you try to resubmit a form or if you have a form open too long and the csrf tokens have expired. Just ctrl+f5 on the form that you are trying to fill out and it should refresh the tokens.

**Comment by advancedeng** [comment]
Actually you are right, but this is not the original problem. My two admin account cannot login via the GUI. Yesterday I generated a new GPG encryption key and a new email address in the config.php configuration file. I also exported the new public key to the webroot. 

The problem is now that I cannot log in with my 2 admin account via the GUI. Is there a way to create an admin account from the terminal?

**Comment by iglocska** [comment]
That should not affect the login at all - are you sure you didn't also
change the salt key?

Either way, there is indeed a console command to reset the password of an
account. Just do the following:

cd /var/www/MISP/app/Console
./cake Password my@email.com myNewPassword1234

**Comment by advancedeng** [comment]
It worked :) 
Thank you so much. Much appreciated!!!

**Comment by iglocska** [comment]
My pleasure, let me know if you run into any other issues! :)
