### ISSUE TITLE
404 after LDAP auth

### ISSUE THREAD

**Issue by erpatrik** [MISP/MISP#5660]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 LTS
| OS version (client)       | Win10
| PHP version               | 7.4.2
| MISP version / git hash   | 2.4.121, 413399611ed41665edab24422bdb1fdead5286be

### Support Questions
Trying to setup LDAP auth, managed to get Apache popup, where I can enter credentials and after successful login I get 404 - https://misp.local/users/login Not found. Adding logs and config files down below. Rewrite module is ON and after commenting <Location> section or changing to <Location /debug.php> MISP is working normally. I use debug.php to check correct headers.
Begging for help.

##### /app/Config/config.php
```
'ApacheSecureAuth' => NULL,
	array (
		'apacheEnv' => 'PHP_AUTH_USER',
        'enabled' => true,
        'ldapServer' => 'ldaps://myldap:636',
        'ldapReaderUser' => 'readeruser',
        'ldapReaderPassword' => 'mypassword',
        'ldapDN' => 'OU=misp,DC=domain,DC=local',
        'ldapSearchFilter' => '(memberOf=CN=misp)',
        'ldapSearchAttribut' => 'mail',
        'ldapDefaultRoleId' => 1,
   ),
 );
```
##### /apache2/sites-available/misp-ssl.conf
```
<VirtualHost *:443>
    ServerAdmin serveradmin@misp.local
    ServerName misp.local
    DocumentRoot /var/www/MISP/app/webroot
    <Directory /var/www/MISP/app/webroot>
        Options -Indexes
        AllowOverride all
    </Directory>
    <Location /users/login>
        AuthType Basic
        AuthBasicProvider ldap
        AuthLDAPBindDN readeruser@my.domain
        AuthLDAPBindPassword "password"
        AuthUserFile /dev/null
        AuthLDAPURL "ldaps://myldap:636/dc=domain,dc=local?mail"
        AuthName "LDAP_Auth"
        Require valid-user
        RewriteEngine On
        RewriteCond %{REMOTE_USER} ^(.*)$
        RewriteRule ^(.*)$ - [E=R_U:%1]
        RequestHeader set X-Remote-User %{R_U}e
        SetEnv REMOTE_USER user
	</Location>
    SSLEngine On
...
```
##### log from /var/log/apache2/misp_access.log
```
ip - admin@domain.local [19/Feb/2020:10:57:42 +0100] "GET /var/www/MISP/app/webroot/users/login HTTP/1.1" 404 
```

**Comment by adulau** [comment]
There is now a standalone LDAP authenticator in MISP which could clearly help in such scenario.

https://github.com/MISP/MISP/tree/29993e516825b8ff35a72419fa61c40472eb1898/app/Plugin/LdapAuth
