### ISSUE TITLE
Correlations with attributes within events

### ISSUE THREAD

**Issue by cedmonds2** [MISP/MISP#5665]
has anyone ever had issues with MISP not picking up correlations with attributes within events?
![image](https://user-images.githubusercontent.com/61468927/75266673-b037b680-57c0-11ea-911b-9d69369bb22e.png)

**Comment by iglocska** [comment]
Confirmed, to be fixed today.

**Comment by cedmonds2** [comment]
How do I get this fix?

**Comment by mokaddem** [comment]
Hey, it's fixed in 2.4.123.
https://github.com/MISP/MISP/releases/tag/v2.4.123
Ping us if you still experience the issue.
Cheers!
