### ISSUE TITLE
Impersonate user as site-admin/org-admin

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#5667]
When logged in as site-/org-admin it is a bad habit to edit/change events that are not your own.

When debugging a user problem, instead of logging in as said user, it would be (preferable?) to use the account from the admin account.

Maybe a duplicate.

**Comment by iglocska** [comment]
Indeed, we had a discussion on this from a different perspective at the office, the idea was to be able to "fake" certain roles as a site admin. Would help with demonstrations when we want to have certain role based rules imposed on us, even when we have privileged accounts. Impersonating another user as a site admin would indeed also solve that.
