### ISSUE TITLE
Download event in other formats than XML or JSON through UI

### ISSUE THREAD

**Issue by thnyheim** [MISP/MISP#568]
Currently you can download an event through the UI as exports to XML or JSON. It would be really beneficial if you could also download as text, openioc, stix etc through the UI this way, as a way of exporting attributes manually (for instances where you need to share across mediums). 

Currently, this can only be done through the API as a per event thing. But it should be easy enough to implement as a button that uses the current API code.

**Comment by cvandeplas** [comment]
I'm not sure to understand.

The webUI has a button called "download as..."
this will bring a screen where you can choose in what format you want to
download the event: text, csv, openioc, xml,.json ...

**Comment by iglocska** [comment]
The download button will only list those two options if the event is not published. Just publish the event and you can use the download as... button to download in a bunch of other formats.

**Comment by thnyheim** [comment]
Ah, you're quite right. Can't believe I missed that, but then again we use our implementation offline. Thanks for the help!

**Comment by iglocska** [comment]
Glad that resolved it. The publishing is used internally too - for example if you do a full snort rule export any event that is not published will be ignored (publishing, apart from pushing the event to connected instances also signals that the event is ready to be used by the automation). 

I'll close the issue for now, let me know if you have any other issues / questions!
