### ISSUE TITLE
[Auditor role] Readonly access to admin data

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5685]
Is there a means to retrieve some administrative data via PyMISP other than accessing via a user with an `admin` role, e.g. `pymisp,feeds` or `pymisp.organisations`?

In general, we are not comfortable running `admin` enabled apps in our production data center.

1. Is there another role we can use?
1. If not, would it be possible to define a new role that has read-only access to these types of data?
1. As implemented now, is there a doc that describes which roles can retrieve which datasets?

Many thanks!

**Comment by github-germ** [comment]
Thank you.

**Comment by iglocska** [comment]
Definitely not possible currently, as Raphael has described it. 

To see the permissions of each individual role / see the descriptions of the permission flags, navigate to:

`/roles/admin_index`

and hover over the headers.

**Comment by github-germ** [comment]
Ah, ok... I see those in `Model/Role.php`
