### ISSUE TITLE
VMware image unable to fetech events

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [MISP/MISP#5686]
Hi, 
I am testing the MISP VMware Virtual appliance, tried latest and old ones both. But I am for some
reason unable to fetch events of the enabled feeds. 

The job runs, and then its queued and ultimately fails every time. 

What are the steps to successfully test the VMware image. TIA

**Comment by mokaddem** [comment]
Hello,
1. Could you make sure you VM has internet access?
2. Could you paste the workers log `app/tmp/logs`
Thanks!

**Comment by shehreyarahmedkohati** [comment]
@mokaddem thanks for the reply!
1) it has, but, it pings 8.8.8.8 successfully. Not google.com. Not changed any dns settings. 
2) can you tell me how to navigate to this? in the latest vmware appliance

**Comment by mokaddem** [comment]
Hey,
1. You have to fix your DNS issue as most of the feeds URL are based on a domain and not a static IP address
2. I guess the issue is linked to (1). But if you want to access the logs, SSH in your appliance, then navigate to the MISP installation folder and then `app/tmp/logs`

**Comment by shehreyarahmedkohati** [comment]
I tried making changes to the dns using the CLI of the testing vm, figured i dont have the correct rights to so.

**Comment by SteveClement** [comment]
@shehreyarahmedkohati is this issue resolved?
