### ISSUE TITLE
Email based OTP

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#5688]
**Is your feature request related to a problem? Please describe.**
Increased security for authentication using email based one time password (OTP) system. 

**Describe the solution you'd like**
- An authentication system allowing the users to enter their username / password, and on a following page enter the OTP token that was sent by email. Only then the user can be considered as fully authenticated.
- The (nicely formatted) email should mention the IP address you've been connecting from, (keep in mind X-Forwarded-For) and also a unique token (a few numbers, easy to type) that is valid for a few minutes.
- The configuration of the EmailOTP solution should allow the administrator to exclude certain users from the OTP.  (allowing them to login even if the emailing is down)

**Describe alternatives you've considered**
- LinOTP offers similar functionality, and can integrate with MISP using the LinOTP auth mechanism. This option requires the installation and maintenance of another (large) software package, and makes things to configure much more complex than needed for a simple email-based OTP solution which could work directly with MISP.   Integrating it immediately with MISP would make this feature accessible to everyone without much effort from their side.

**Comment by lfortemps** [comment]
I think this one can be closed as the email OTP PR was merged

**Comment by iglocska** [comment]
Indeed, thanks again!
