### ISSUE TITLE
DB Version Mismatch

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#5691]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Win10
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.122 (b83a238a806fd7603555fde7e9b1ce8798bf0d04)
| Browser                   | Chrome

I upgraded MISP from 2.4.121 to 2.4.122 today and notice under the Server Settings & Maintenance page the "Expected DB_version" is lower than the "Actual DB_version".
MISP appears to be working correctly but not for sure if this is an issue or not.

Expected DB_version: 48		Actual DB_version: 49

![MISP_DB_Version_Mismatch](https://user-images.githubusercontent.com/8250365/76235252-d9146e80-61f8-11ea-85ab-e6cdc4886725.PNG)

**Comment by mokaddem** [comment]
Thanks for the heads up. It's fixed now! :)

**Comment by int3dev** [comment]
Similar Issue, after updating from 2.4.123 to 2.4.126
![image](https://user-images.githubusercontent.com/12826953/82880180-ab1f0a80-9f5b-11ea-8e80-f33b5e2bbdaf.png)

**Comment by eowyn263** [comment]
Hello,

same issue after upgrading to 2.4.158
![image](https://user-images.githubusercontent.com/51202913/164413890-7c971250-a7a9-4411-bc79-d951c523542c.png)
