### ISSUE TITLE
unable to run installer on Debian 

### ISSUE THREAD

**Issue by shilpajuet** [MISP/MISP#5694]
hi Team,,

I am below issue while installing MISP on Debian ::
****
-2020-03-10 11:45:45--  https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.64.133, 151.101.128.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100109 (98K) [text/plain]
Saving to: ‘/tmp/INSTALL.sh’

/tmp/INSTALL.sh                         100%[==============================================================================>]  97.76K  --.-KB/s   in 0.02s

2020-03-10 11:45:46 (5.51 MB/s) - ‘/tmp/INSTALL.sh’ saved [100109/100109]

Next step: Checking if we are run as the installer template
Next step: Checking if we are uptodate and checksums match
sha1 matches
sha256 matches
sha384 matches
sha512 matches
Next step: Setting MISP variables
Next step: Setting generic MISP variables shared by all flavours
The following DB Passwords were generated...
Admin (root) DB Password: c704a0eeac8d749d0db8c6f583321ed2a41a111f0b2c57aca2d2d08d5922c6fa
User  (misp) DB Password: d24a1ccf16d5f8713a97a558fd26c219f9f3bda2867f1a12588a3c5a218e5ddf
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Debian
Next step: Checking for parameters or Unattended Kali Install
Next step: Setting install options with given parameters.
core
modules
    Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/

Environment 
****
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

Command used:
****
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M

Also, tried running installer directly and found:
: No such file or directory

Please help. 
Thanks in advance.

**Comment by SteveClement** [comment]
Unfortunately I have not gotten around yet to get it fully working.

There are still 2 pesky bugs I need to work around.

**Comment by shilpajuet** [comment]
hi Steve, 

Thanks for your response. When are you expecting this to get it done!!

Best regards, 
Shilpa

**Comment by SteveClement** [comment]
Debian 8/10 will not be supported in the installer. Only if 10/11 will be 95% compatible with ubuntu based installs it will be considered. For the rest, the manual install docs should be ok.
