### ISSUE TITLE
MISP Timeout issues

### ISSUE THREAD

**Issue by cedmonds2** [MISP/MISP#5698]
Using version MISP 2.4.120, Any reason timeouts don't seem to last up to specified timeout time? It's currently set to 180 minutes, but seems not to make it even close to that time limit.

**Comment by github-germ** [comment]
Have you also increased timeouts as follows? I'm using your 180 minutes value which is actually 10800 secs. The setting in MISP needs to also be increased in PHP and Apache if those values are lower. For example, here's where we set those on RedHat 7.4. Hope this helps...

* in `/etc/opt/rh/rh-php72/php.ini`
```
max_execution_time = 10800
```
* `/etc/httpd/conf/httpd.conf`
```
Timeout 10800
ProxyTimeout 10800
```

**Comment by cedmonds2** [comment]
I will give that a try. So the gui doesn't correspond with changing it on the actual server?

**Comment by github-germ** [comment]
> So the gui doesn't correspond with changing it on the actual server?

Correct: the WebUI does not change PHP nor Apache. The WebUI can show you those values from the `php.ini` with `.../servers/serverSettings/diagnostics` but does not show Apache.

**Comment by github-germ** [comment]
Here's Apache docs. I believe without the setting it defaults to 60 secs...
* https://httpd.apache.org/docs/2.4/mod/core.html#timeout
* https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxytimeout

**Comment by github-germ** [comment]
And the PHP setting:
* https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by enjeck** [comment]
@cedmonds2 Did you eventually resolve this?
