### ISSUE TITLE
WebUI access to users.external_auth*

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5701]
With 2.4.121 it seems that WebUI access on the User Add or Edit pages to `external_auth_required` and `external_auth_key` were removed. Can they be set somewhere else in the WebUI? I believe they were there in 2.4.118.

If this is correct, then is the only way to set those is to mysql them into the DB? That would be a problem for our data center OPs team, and we'd need to write a script for them. Would help to know how we should proceed.

Thanks!

**Comment by iglocska** [comment]
That definitely sounds like a bug, will have a look.

**Comment by github-germ** [comment]
THANKS!!

On Mar 14, 2020, at 11:49 AM, Andras Iklody <notifications@github.com<mailto:notifications@github.com>> wrote:


That definitely sounds like a bug, will have a look.

**Comment by github-germ** [comment]
THANKS... What do you think about only an admin having the ability to add/edit ext auth for a given user?

**Comment by iglocska** [comment]
Sorry just had a look at this, it seems to work as it did before for me, are you still seeing this issue?

**Comment by github-germ** [comment]
OK, probed a bit more. This is on 2.4.121.

If `Plugin.CustomAuth_required` is set `true`, `External authentication user` is no longer displayed in the WebUI.

The issue with this is when we go to create a new user, we can not set the `External Auth Key` via the WebUI. For now, I've written a PyMISP app that our OPs team uses to create new users; however, it would be _nice_ if the WebUI still had this setting.

**Comment by iglocska** [comment]
Hmm on mine it's still there. There are no local modifications on your
instance right? If you run git status there's no divergence?

**Comment by github-germ** [comment]
```
root@misp:/var/www/MISP# git status
HEAD detached from v2.4.121
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   PyMISP (untracked content)
	modified:   app/files/misp-objects (untracked content)
	modified:   app/files/taxonomies (untracked content)
	modified:   app/files/warninglists (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	INSTALL/dependencies/
	app/Config/config.php.bk
	venv/

no changes added to commit (use "git add" and/or "git commit -a")
root@misp:/var/www/MISP# 
```

**Comment by iglocska** [comment]
That looks clean. Weird... Will have another look tomorrow.

**Comment by github-germ** [comment]
While it is true there here with 2.4.143, that the WebUI Add or Edit User pages still do not include `external_auth_required` or `external_auth_key` we did develop command like tools to handle this.

If this is the intended WebUI behavior, then being that this isn't blocking us anymore, please feel free to close this issue.

**Comment by github-germ** [comment]
OK, I'll close it :-)

**Comment by chrisinmtown** [comment]
I don't think you should have closed this, because views like admin_edit.ctp still have edit controls for Custom (aka external) auth, for example:
```
        <div class="clear"></div>
        <div id="externalAuthDiv">
        <?php
            echo $this->Form->input('external_auth_key', array('type' => 'text'));
        ?>
        </div>
```
However their display is set to false even when config.php has Plugin.CustomAuth_enable = true.  The code is there on the HTML page but the controls don't appear in the UI

**Comment by iglocska** [comment]
It seems to work for me:

![image](https://user-images.githubusercontent.com/3668672/122014122-264d9b80-cdbf-11eb-940f-28fd10190b65.png)
