### ISSUE TITLE
Memory with MD5 generation

### ISSUE THREAD

**Issue by slcsecurity** [MISP/MISP#571]
I'm having trouble getting MD5 list to generate from the web interface. Here are the log files. 
Any help or pointers in the right direction would be greatly appreciated. I have attempted to increase PHP memory but the issue persist. 

==> resque-worker-error.log <==
Notice Error: Undefined variable: from in [/var/www/MISP/app/Model/Attribute.php, line 1203]

2015-07-16 22:05:41 Notice: Undefined variable: from in [/var/www/MISP/app/Model/Attribute.php, line 1203]
Notice Error: Undefined variable: to in [/var/www/MISP/app/Model/Attribute.php, line 1204]

2015-07-16 22:05:41 Notice: Undefined variable: to in [/var/www/MISP/app/Model/Attribute.php, line 1204]
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 85 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 277
Fatal Error Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 85 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 277]

2015-07-16 22:05:46 Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 85 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 277]

**Comment by elhoim** [comment]
268435456 is basically 256Megabytes of memory.
php has a setting in php.ini called memory_limit which describes what is the maximum memory that a script can use. Increase that value to something higher than 256M to see how it goes. Try doubling it for example.

Do you have lots of MD5?

**Comment by iglocska** [comment]
The MD5 export is also a bit inefficient. I already have a fix ready for it
locally, will push it today together with some other fixes!

**Comment by slcsecurity** [comment]
Thank you. Yes I have ALOT of MD5's. I'll let you know if the fix takes care of the issue.

**Comment by iglocska** [comment]
Excellent, curious whether it works. If not, I have another option :)

**Comment by slcsecurity** [comment]
It's still the same with the new pull request and code update. I tried increasing PHP memory but no joy. Seems to be something with arrays. If you want access to the server please email me kwetzel(at)slcsecurity.com and I'll give you an account so you can look around.

**Comment by iglocska** [comment]
I've sent you a mail!

**Comment by iglocska** [comment]
Patch c6e4b2dc61f336307d4d3a7ea6c4262952545402 addresses this issue (and does so for the NIDS exports too).

**Comment by slcsecurity** [comment]
The patch resolves the issue. Thank you for your attention to detail on this one.

**Comment by iglocska** [comment]
Excellent, let me know if you run into any other issues!

**Comment by slcsecurity** [comment]
I'll leave your account in place so you can view data if you want. Now if I
can get CIRCL to peer with us or give us a feed :-)

**Comment by slcsecurity** [comment]
Any chance we can do the same thing with text export. Now that there is alot of data in the instance text generation fails with the same php error memory exausted. What is weird is that I set a higher memory limit in php.ini but it doesn't affect the limit in CakeResque that shows as 128MB of memory regardless of what is set in the php.ini file.

**Comment by elhoim** [comment]
Under ubuntu, there are two php.ini available, one under */etc/apache2/* and one under */etc/cli/*
Don't know if it is the same for your distro.
Could you check if there is a 128M limit in the php.ini under */etc/cli/* and if changing it there helps.

**Comment by slcsecurity** [comment]
I have set them both to 256M but the issue persist. I'm using RHEL7. There is an apache php.ini and the normal /etc/php.ini. The issue persist. 

Here is the log:
2015-08-06 11:58:52 Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 46283646 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocketResponse.php, line 160]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Inflector.php on line 275
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 75 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 277

Let me know if there is any additional information needed to figure out how to resolve.

**Comment by iglocska** [comment]
Absolutely, will look into it soon. The goal is to move any export that hasn't gotten this treatment yet to the more memory efficient way. I'll do this in the next couple of days and let you know, thanks for the heads-up!

**Comment by slcsecurity** [comment]
This appears to be working now. Was the change implemented? If so I can close this issue.
