### ISSUE TITLE
information sharing statistics in the (new) dashboards

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#5713]
**Is your feature request related to a problem? Please describe.**
The MISP-dashboards give interesting information sharing statistics that could stimulate information sharing; but does not respect data confidentiality based on the distribution and SharingGroups

**Describe the solution you'd like**
The new (currently developed) dashboards built in MISP web UI could provide similar information sharing statistics as the MISP-dashboard does. By design these automatically follow the data confidentiality as they use internal APIs.

This feature-request is therefore to create nicely looking dashboards with statistics of information sharing on this instance.  Stats should (at least) be organisation centric.

**Comment by mokaddem** [comment]
What stats would you like to see in addition to Organisation activity (data creation/edition)?

**Comment by cvandeplas** [comment]
Similar as what you tried to do with the MISP-dashboards:
- stimulate info sharing by gamification / trends of contributions
- better insight in data with trends of data (tags/galaxies, ...) 
- use of misp-objects
- use of references (linking objects/attributes)
- ...

**Comment by cvandeplas** [comment]
As given by @mokaddem  in https://github.com/MISP/MISP/pull/6129#issuecomment-662298299 , which came from the [MISP dashboard](https://github.com/MISP/misp-dashboard) project that could also be interesting here:

- Specific badges and achievements for interacting with specific threat actors
- Rewards for discovering APT 41 C2, or new important TTPs
- Rewards for industry best champion (who produces the most/highest quality threat intel on actors targeting our industry)
    - Just be careful with the **most** as you want to avoid people submitting bad quality/junk content
- Better cross industry trends, filtering by industry
- Rewards or points for intra-industry collaboration, rather than analyst output

Not sure how to implement these point in a clean way, so food for thought

Credit @VVX7 ;)

**Comment by cvandeplas** [comment]
Was fixed by PR: https://github.com/MISP/MISP/pull/6142
