### ISSUE TITLE
MISP (old) Dashboard bug

### ISSUE THREAD

**Issue by erosseleth** [MISP/MISP#5716]
Sorry for say it but i really don't understand the reason after the elimination of MISP Dashboard (the old one). I think it is really simple to solve the bug caused by the new MaxMind policy. In fact I have done it in my test instances. The only thing necessary is to previously have a MaxMind key. Maybe I'm skipping something here. My apologies if so.

**Comment by mokaddem** [comment]
Hey,
What do you mean by elimination of MISP Dashboard?
You can still install it manually:
https://github.com/MISP/misp-dashboard

**Comment by SteveClement** [comment]
feel free to re-open in case of need.
