### ISSUE TITLE
Problem with scheduled tasks

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#572]
Hi all,

A have a new MISP instance and while  the workers seem to work pretty OK i think I experience some problems with the scheduler one.

I would like MISP to do the following periodic tasks on an hourly basis:
Pul
Push
Cache exports

The aforementioned tasks do not seem to be working and in the scheduled tasks tab (GUI) they seem to be "Not scheduled yet.". The status of the scheduler worker is OK and if I manual pull/push/cache export works pretty fine. Any ideas? Is there something that I am missing in the config files?

Thanks in advance,
Andreas

**Comment by iglocska** [comment]
When you set up the scheduled task, it is important to set both the next
execution time and the frequency - once that is done the job should
execute. Let me know if you've done that and it still doesn't work and
we'll dig deeper into what's wrong!

**Comment by elhoim** [comment]
#573 might be related to this.

**Comment by advancedeng** [comment]
OK, thanks. Everything seems to be working fine now! 
The problem was all about the next execution time and frequency and then let it run just once.

Cheers,
Andreas

**Comment by iglocska** [comment]
Excellent, I'll try to work on a bit more clarification for the scheduled
jobs in the future, as it's not too intuitive.

**Comment by advancedeng** [comment]
Thanks again for your time iglocska!!!

**Comment by iglocska** [comment]
My pleasure! :)
