### ISSUE TITLE
Error: Database connection "Mysql" is missing, or could not be created.

### ISSUE THREAD

**Issue by Vikings-Ivar** [MISP/MISP#5720]
Hello,

I'm trying to install MISP on Centos 7 following https://misp.github.io/MISP/INSTALL.rhel7/#initialize-misp-configuration-and-set-some-defaults

My database is a remote MySQL on another server, using SSL.

When I run the script mispmodulesRHEL, I've the following error : 
Error: Database connection "Mysql" is missing, or could not be created.

It happen with the command $SUDO_WWW $RUN_PHP -- $CAKE Admin setSetting "Plugin.Enrichment_services_enable" true and all the other

I don't understand how to solved it, and others subjects open on it doesn't help me.

    database.php
    <?php
    class DATABASE_CONFIG {
    public $default = array(
    'datasource' => 'Database/Mysql',
    //'datasource' => 'Database/Postgres',
    'persistent' => false,
    'host' => 'MYREMOTEHOST',
    'login' => 'MYUSER,
    'port' => MYPORTNUMBER, // MySQL & MariaDB
    //'port' => 5432, // PostgreSQL
    'password' => 'MYPASSWPRD',
    'database' => 'MYDATABASE',
    'prefix' => '',
    'encoding' => 'utf8',
    );
}

**Comment by Vikings-Ivar** [comment]
Duplicate with #5724

**Comment by valerianaroncero** [comment]
I´m having almost the same problem. 

I'm trying to install MISP on Centos 8 following https://misp.github.io/MISP/INSTALL.rhel8/#907-misp-modules-broken-on-rhel8

When the next fixed installation will be provide?

 $SUDO_WWW $RUN_PHP -- $CAKE Admin setSetting  "Plugin.Enrichment_services_enable" true

Error: syntax error, unexpected 'g' (T_STRING), expecting ')'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->re
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load('config')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstr
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): requ
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): Shel
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): Shell
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): Shell
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#9 {main}

Thanks in advanced.

**Comment by Sshahar** [comment]
Is there a solution yet?
Host machine running Ubuntu 20.04

**Comment by iglocska** [comment]
Could you open a separate issue describing your problem?

**Comment by IshanPE** [comment]
Any updates on this one ? i am facing the same issue  . I even did an rm on the installation of /tmp for misp user twice. but nothing helps. also tried to see any logs on the /var folder for misp/app. Can anyone assist , i am getting below errors. 

[Install]
WantedBy=multi-user.target
#############################################################  (60%)
Next step: Running core Cake commands to set sane defaults for MISP
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#10 /var/www/MISP/app/Model/AppModel.php(52): Model->__construct()
#11 /var/www/MISP/app/Model/User.php(231): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#17 /var/www/MISP/app/Console/Command/AppShell.php(35): Shell->initialize()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#20 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#21 {main}
Error: Database connection "Mysql" is missing, or could not be created.

**Comment by IshanPE** [comment]
Also i see blank base url . attaching the screenshot. i am very new to this kindly help.
![image](https://user-images.githubusercontent.com/101351327/157813845-92eb3270-bd76-479e-964a-2c72e6a6add2.png)

**Comment by FreddieWright** [comment]
> Any updates on this one ? i am facing the same issue . I even did an rm on the installation of /tmp for misp user twice. but nothing helps. also tried to see any logs on the /var folder for misp/app. Can anyone assist , i am getting below errors.
> 
> [Install] WantedBy=multi-user.target ############################################################# (60%) Next step: Running core Cake commands to set sane defaults for MISP Error: Database connection "Mysql" is missing, or could not be created. #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect() #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct() #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource() #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource() #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource() #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource() #6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema() #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup() #8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load() #9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init() #10 /var/www/MISP/app/Model/AppModel.php(52): Model->__construct() #11 /var/www/MISP/app/Model/User.php(231): AppModel->__construct() #12 [internal function]: User->__construct() #13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance() #14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init() #15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel() #16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels() #17 /var/www/MISP/app/Console/Command/AppShell.php(35): Shell->initialize() #18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize() #19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch() #20 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run() #21 {main} Error: Database connection "Mysql" is missing, or could not be created.

Have you done with that yet?
