### ISSUE TITLE
apiosintds 1.8.3 has requirement validators==0.14.0

### ISSUE THREAD

**Issue by utkonos** [MISP/MISP#5722]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.123

### Expected behavior
No install errors.

### Actual behavior
```
ERROR: apiosintds 1.8.3 has requirement validators==0.14.0, but you'll have validators 0.14.2 which is incompatible.
```

### Steps to reproduce the behavior
```
apt install haveged -qy
adduser misp
usermod -a -G sudo misp
usermod -a -G staff misp
usermod -a -G www-data misp
su - misp
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
```

### Logs, screenshots, configuration dump, ...
https://gist.github.com/utkonos/a7dd6598f037759c4a11df7c51aa6688

**Comment by GlennHD** [comment]
Also ran into apiosintds issues testing out Ubuntu 20.04 LTS.  Everything else appeared to work except for this... Oh DigitalSide...

```
ERROR: apiosintds 1.8.3 has requirement pytz==2019.3, but you'll have pytz 2020.1 which is incompatible.
ERROR: apiosintds 1.8.3 has requirement validators==0.14.0, but you'll have validators 0.14.3 which is incompatible.
```

**Comment by utkonos** [comment]
I'm still seeing the same two Python package errors.

```
apiosintds 1.8.3 requires pytz==2019.3, but you'll have pytz 2020.1 which is incompatible.
apiosintds 1.8.3 requires validators==0.14.0, but you'll have validators 0.14.2 which is incompatible.
```
