### ISSUE TITLE
AssertionError: 'ZMQ event publishing not enabled.' != 'Event published to ZMQ'

### ISSUE THREAD

**Issue by utkonos** [MISP/MISP#5723]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.123

### Expected behavior
No install errors.

### Actual behavior
```
FAIL: test_zmq (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 1364, in test_zmq
    self.assertEqual(r['message'], 'Event published to ZMQ')
AssertionError: 'ZMQ event publishing not enabled.' != 'Event published to ZMQ'
- ZMQ event publishing not enabled.
+ Event published to ZMQ
```

### Steps to reproduce the behavior
```
apt install haveged -qy
adduser misp
usermod -a -G sudo misp
usermod -a -G staff misp
usermod -a -G www-data misp
su - misp
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
```

### Logs, screenshots, configuration dump, ...
https://gist.github.com/utkonos/c5d9fda56fee75742959cf9e0a2ea1f2

**Comment by LoosiferMcG** [comment]
I have this same error using the -A install option - having install issuers further up the script which I'm still working through

**Comment by utkonos** [comment]
Whole new set of errors on install. This one is gone.
