### ISSUE TITLE
Connection to MySQL with SSL enforced fails

### ISSUE THREAD

**Issue by moutonjr** [MISP/MISP#5724]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| OS version (client)       | N/A (Windows)
| PHP version               | 7.2
| MISP version / git hash   | 2.4.122
| Browser                   | N/A

### Expected behaviour

Installation of part **9.07 misp modules** CentOS 7 exits successfully without errors.
More precisely, when launching any CakePHP Command.

### Actual behavior
This step fails with log dump below. Maybe it has something to do with CakePHP MySQL Connection in SSL forced?

Note that it's Azure PaaS, I can't change the hostname into real IP Address as explained [in some workarounds.](https://stackoverflow.com/questions/47995069/cakephp-3-mysql-connection-over-ssl)

### Steps to reproduce the behavior

Follow installation with CentOS 7, with remote MySQL database only accepting SSL.

Assuming then that MySQL connection canbe achieved using plain `mysql-client` works: 
```bash
mysql -u DBUser_MISP@SQLSERVER -h SQLSERVER.mysql.database.azure.com --port 3306 -p 'MYPASSWD' --ssl
```

Configuring `database.php` as follows : 
```php
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  //'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'SQLSERVER.mysql.database.azure.com',
                  'login' => 'DBUser_MISP',
                  'port' => 3306, // MySQL & MariaDB
                  //'port' => 5432, // PostgreSQL
                  'password' => ‘MYPASSWD’,
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
          );
  }
```

Source all install variables spread across steps

Try to launch `SUDO_WWW $RUN_PHP -- $CAKE Admin setSetting "Plugin.Enrichment_services_enable" true`

### Logs, screenshots, configuration dump, ...

Error dump when launching `SUDO_WWW $RUN_PHP -- $CAKE Admin setSetting "Plugin.Enrichment_services_enable" true`
```
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(268): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('User', Array)
#10 /var/www/MISP/app/Model/AppModel.php(48): Model->__construct(NULL, NULL, 'default')
#11 [internal function]: AppModel->__construct(Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#13 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(264): ClassRegistry::init('User')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(Event), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init('Event', Array)
#17 /var/www/MISP/app/Model/AppModel.php(48): Model->__construct(NULL, NULL, 'default')
#18 /var/www/MISP/app/Model/Event.php(381): AppModel->__construct(Array, NULL, NULL)
#19 [internal function]: Event->__construct(Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init('Event')
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel('Event')
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#24 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): Shell->initialize()
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#26 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#27 {main}
```

**Comment by moutonjr** [comment]
Similar but more precise than https://github.com/MISP/MISP/issues/5720

**Comment by garvsd** [comment]
Hey, do we have an update for this?

@moutonjr Did you find any resolve?

**Comment by moutonjr** [comment]
Hello @garv-sd ,
No, I don't, and gave up installing misp on Azure PaaS...

Workaround to build it in standalone.

**Comment by garvsd** [comment]
Hey @moutonjr, I was able to fix this with the addition of CA cert while setting database config and a flag in the MysqlExtendedLogging.php did this for me.

Config now has the cert.
`'database' => 'misp',
'prefix' => '',
'encoding' => 'utf8',
'ssl_ca' => '/var/www/MISP/BaltimoreCyberTrustRoot.pem',`
              
and this flag post L178.
`$flags[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT ] = false;`
                
Am good with  Azure PaaS based setup.

**Comment by moutonjr** [comment]
Hi Gary, great news! 
Is there a commit to track your patch ? No doubt that misp team will merge this as hotfix..

Blessings,

**Comment by righel** [comment]
Hello @moutonjr 
To specify a custom CA for the MySQL driver you should edit your `/var/www/MISP/app/Config/database.php` file:
```php
class DATABASE_CONFIG {
        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'YOUR_DB_HOST',
                'login' => 'misp',
                'port' => 3306, // MySQL & MariaDB
                'password' => 'YOUR_DB_PASS',
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
                'ssl_ca' => '/var/www/MISP/your_custom_ca.pem'
        );
}
```

The proposed solution:
`$flags[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT ] = false;`
Just ignores the CA verification, I would not recommend to do that.

Hope this helps, closing for now.
