### ISSUE TITLE
Scheduled tasks - next run time

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#573]
For scheduled tasks, if the next run time is in the past, update it to be in the future so that execution is not skipped.

I don't know where it would be best to add that (scheduler worker startup? other place?).

**Comment by iglocska** [comment]
This should be done automatically already - basically what happens is this:

Say you set the start date a week in the past and add a 24h frequency to
the task. The moment it is scheduled, the scheduler will pick it up as soon
as it polls (so every 5 secs) - it notices that is in the past and executes
it. For the next time it will keep adding 24h to the initial start date
until it's a time that is in the future.

If it does not work like this in reality let me know, it's a bug then!

**Comment by elhoim** [comment]
So it should add 24h every 5secs if the scheduler worker is running?

**Comment by iglocska** [comment]
nono after 5 secs it should loop through immediately!

**Comment by elhoim** [comment]
My bad, it works. It is just that I add the "worker not running"  problem again.
