### ISSUE TITLE
Interesting way to count related events

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5732]
v2.4.123: Just stumbled over an event which shows the following for related events:

![events1](https://user-images.githubusercontent.com/25325656/77663586-815a5f00-6f7d-11ea-943a-f07c0ac2af34.jpg)

Clicking on "Show (0) more" leads to one more entry being displayed:

![events2](https://user-images.githubusercontent.com/25325656/77663596-85867c80-6f7d-11ea-926e-63682919414d.jpg)

Well, I know us computer scientist always start counting at zero but this is probably not what we want...  :-)

**Comment by mokaddem** [comment]
:man_facepalming:

**Comment by mokaddem** [comment]
Thanks you! :)
