### ISSUE TITLE
Merge of objects fails

### ISSUE THREAD

**Issue by nerok** [MISP/MISP#5733]
# This template is meant for bug reports, if you have a feature request user the other template.
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS is the host, the container is Debian
| OS version (client)       | Win10
| PHP version               | 7.3.14-1~deb10u1
| MISP version / git hash   | 2.4.123, on modified version of [coolacid/docker-misp](https://github.com/coolacid/docker-misp):core-v2.4.123c
| Browser                   | Firefox and Chrome has been tried

### Expected behavior
When creating two similar objects, MISP suggests reviewing a merge, when pressing the button one should be transfered to a merge view.

### Actual behavior
When pressing the Review merge button MISP says "An internal error has occurred".

### Steps to reproduce the behavior
Create a event, add the person object with the following attributes:
last-name: Doe
first-name: John
phone-numer: 987654321
role: Accused.
Then save this object.
Now create a new person object with the same attributes except the first-name is Jane.
When submitting MISP should suggest reviewing a merge, press the Review merge button.

### Logs, screenshots, configuration dump, ...
The generated link in misp is: https://misp-server/objects/edit/25/revised_object:eyJPYmplY3QiOnsiZGlzdHJpYnV0aW9uIjoiNSIsImNvbW1lbnQiOiIiLCJmaXJzdF9zZWVuIjoiIiwibGFzdF9zZWVuIjoiIn0sIkF0dHJpYnV0ZSI6eyIxIjp7Im9iamVjdF9yZWxhdGlvbiI6Imxhc3QtbmFtZSIsInR5cGUiOiJsYXN0LW5hbWUiLCJjYXRlZ29yeSI6IlBlcnNvbiIsInZhbHVlIjoiRG9lIiwidG9faWRzIjoiMCIsImRpc2FibGVfY29ycmVsYXRpb24iOiIwIiwiZGlzdHJpYnV0aW9uIjoiNSIsImNvbW1lbnQiOiIiLCJmaXJzdF9zZWVuIjpudWxsLCJsYXN0X3NlZW4iOm51bGx9LCIzIjp7Im9iamVjdF9yZWxhdGlvbiI6ImZpcnN0LW5hbWUiLCJ0eXBlIjoiZmlyc3QtbmFtZSIsImNhdGVnb3J5IjoiUGVyc29uIiwidmFsdWUiOiJKYW5lIiwidG9faWRzIjoiMCIsImRpc2FibGVfY29ycmVsYXRpb24iOiIxIiwiZGlzdHJpYnV0aW9uIjoiNSIsImNvbW1lbnQiOiIiLCJmaXJzdF9zZWVuIjpudWxsLCJsYXN0X3NlZW4iOm51bGx9LCI3Ijp7Im9iamVjdF9yZWxhdGlvbiI6InBob25lLW51bWJlciIsInR5cGUiOiJwaG9uZS1udW1iZXIiLCJjYXRlZ29yeSI6IlBlcnNvbiIsInZhbHVlIjoiOTg3NjU0MzIxIiwidG9faWRzIjoiMCIsImRpc2FibGVfY29ycmVsYXRpb24iOiIwIiwiZGlzdHJpYnV0aW9uIjoiNSIsImNvbW1lbnQiOiIiLCJmaXJzdF9zZWVuIjpudWxsLCJsYXN0X3NlZW4iOm51bGx9LCIyOCI6eyJvYmplY3RfcmVsYXRpb24iOiJyb2xlIiwidHlwZSI6InRleHQiLCJjYXRlZ29yeSI6Ik90aGVyIiwidmFsdWUiOiJBY2N1c2VkIiwidG9faWRzIjoiMCIsImRpc2FibGVfY29ycmVsYXRpb24iOiIxIiwiZGlzdHJpYnV0aW9uIjoiNSIsImNvbW1lbnQiOiIiLCJmaXJzdF9zZWVuIjpudWxsLCJsYXN0X3NlZW4iOm51bGx9fX0=

Stack trace with debug on:
Argument 1 passed to Hash::extract() must be of the type array, null given, called in /var/www/MISP/app/Model/MispObject.php on line 1251

Error: An Internal Error Has Occurred.
Stack Trace

    APP/Model/MispObject.php line 1251 → Hash::extract(null, string)
    APP/Controller/ObjectsController.php line 401 → MispObject->reviseObject(array, array)
    [internal function] → ObjectsController->edit(string)
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 499 → ReflectionMethod->invokeArgs(ObjectsController, array)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(ObjectsController, CakeRequest)
    APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by mokaddem** [comment]
Hey,
Thanks for the report, it should be fixed now.
Cheers
