### ISSUE TITLE
Fresh MISP installation - Web GUI 'Internal error' 

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#5737]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue                 | Support
| OS version (server)       | Ubuntu 18.04.3 (Server)
| OS version (client)        | Ubuntu 18.04.3 9x64 AMD)
| MISP version                 | 2.4.123
| Browser                         | Firefox 74.0 (64-bit)

### Support Questions

Hi,

I'm a newbie with MISP and have tried to follow all instructions to install and configure MISP. Post installation when trying to access to GUI at http://xx.xx.xx.xx/users/login, I run into the below error: 

"An Internal Error Has Occurred. Error: An Internal Error Has Occurred."

Please could someone kindly advise on what I'm missing here or if any bit of config done wrong? I have also noticed the baseURL of http redirects to https by default in the browser. Is this expected or another issue?

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/62763192/77781761-0319bd80-704e-11ea-987b-d1728c282044.png)

**Comment by redbiker-svg** [comment]
Plot thickens.. Did some further digging into the error logs and found below. I'm pretty sure the installation was done fully and correctly. I remember seeing the Database setup stage completing without any errors.. 

![image](https://user-images.githubusercontent.com/62763192/77792741-d15e2200-7060-11ea-9c90-2055c8a6da18.png)

**Comment by redbiker-svg** [comment]
Hi @iglocska 
Apologies about the direct tag in there, but I found the incredibly great work you did into resolving https://github.com/MISP/MISP/issues/4060.. I have read through the comments and tried to replicate it, but no joy into resolving the issues I'm facing. 

Is this something you could assist with please?

**Comment by iglocska** [comment]
Ah good news, sounds like a simple invalid mysql credential. They are stored in `/var/www/MISP/app/Config/database.php`

Make sure that the credentials used in the database.php file are actually working - to test it simply run `mysql -u misp -p misp` and when prompted enter the password from the database.php file. If it doesn't work you'll have to fix either the config file or credentials in mysql itself.

**Comment by redbiker-svg** [comment]
Ah, sounds a simple fix then. Tried to tried it but failed authentication. Should I change the password in the database.php file with a random strong one and try that? Is there any other files that needs updating or sync via this php file?

**Comment by redbiker-svg** [comment]
Hi @iglocska 
I changed the password in database.php and on testing, encountered below error. 
ERROR 1045 (28000): Access denied for user 'misp'@'localhost' (using password: YES)

Though, I fail to understand why won't the Web GUI load for if there are any issues with db file?

**Comment by blad83** [comment]
I have the same issue too. Ran the command  mysql -u misp -p misp
Enter password:
ERROR 1045 (28000): Access denied for user 'misp'@'localhost' (using password: YES)

**Comment by SteveClement** [comment]
You have an invalid MySQL password.
(both of you) as a good excercise, redo the entire installation from scratch and make sure to note:

DB User MISP password
DB User root password

They are not the same.

**Comment by redbiker-svg** [comment]
> You have an invalid MySQL password.
> (both of you) as a good excercise, redo the entire installation from scratch and make sure to note:
> 
> DB User MISP password
> DB User root password
> 
> They are not the same.

This worked. Closing issue now
