### ISSUE TITLE
Installing misp-modules installs pymisp 2.4.119, but MISP wants >2.4.120

### ISSUE THREAD

**Issue by jmgnc** [MISP/MISP#5739]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2 (because misp-vagrant installs it)
| MISP version / git hash   | commit 6626e5bf2451cffed6ead2a0617f2ca947f4eecb (HEAD -> 2.4, origin/HEAD, origin/2.4)  
| Browser                   | N/A

### Expected behavior

That when installing misp-modules it will install the correct and required version for PyMISP.

### Actual behavior

misp-modules installs PyMISP 2.4.119.  From http://127.0.0.1:5000/servers/serverSettings/diagnostics:
PYMISP library version…Incorrect PyMISP version installed, found 2.4.119, expecting >2.4.120

### Steps to reproduce the behavior

If you do the steps per https://misp.github.io/MISP/INSTALL.ubuntu1804/#install-misp-modules-optional
```
cd /usr/local/src/
git clone https://github.com/MISP/misp-modules.git
cd misp-modules
pip3 install -I -r REQUIREMENTS > /dev/null
pip3 install -I . > /dev/null
```

### Logs, screenshots, configuration dump, ...

If you go to misp-modules/REQUIREMENTS (https://github.com/MISP/misp-modules/blob/master/REQUIREMENTS ), it has the line:
```
-e git+https://github.com/MISP/PyMISP.git@a26a8e450b14d48bb0c8ef46b32bff2f1eadc514#egg=pymisp[fileobjects,openioc,virustotal,pdfexport]
```

If you look at the PyMISP __init__.py that corresponds to that hash https://github.com/MISP/PyMISP/blob/a26a8e450b14d48bb0c8ef46b32bff2f1eadc514/pymisp/__init__.py#L1 , you see that it requires 2.4.119.

**Comment by Rafiot** [comment]
if you try again, it should be fine now.
