### ISSUE TITLE
Support STIX v1.1 and v1.2 concurrently and independently

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#574]
Installed STIX & CyBOX via **pip** on Ubuntu 14.04.2 LTS (latest pull of MISP).

`
STIX library version....Incorrect STIX version installed, found 1.2.0.0, expecting 1.1.1.4
`
`
CYBOX library version....Incorrect CyBox version installed, found 2.1.0.11, expecting 2.1.0.10
`

Does this pose any issues?

**Comment by iglocska** [comment]
1.1.1.4 / 2.1.0.10 is the last tested version, in general it should work
fine. I'll test it and change the diagnostics.

**Comment by RichieB2B** [comment]
STIX 1.2.0.0 gives some issues with the STIX export Python code, I haven't tested CyBOX 2.1.0.11. If we are going to support STIX 1.2.0.0 it will probably not be backwards compatible with 1.1.x. Also, most tools do not support the new STIX 1.2.x yet for import. I'm not sure what would be the best way to handle this. Perhaps ensure MISP can support both STIX 1.1 and 1.2 depending on the library installed so the MISP admin can decide.

**Comment by iglocska** [comment]
Yeah makes sense. Let's stick to 1.1 now and we'll look into adding 1.2 as
an alternative instead of aligning ourselves only with it.

Thanks for the heads-up!

**Comment by Rafiot** [comment]
MISP will not support multiple versions of STIX at once any time soon.
