### ISSUE TITLE
Re-implement LDAP authentication as a plugin

### ISSUE THREAD

**Issue by smclinden** [MISP/MISP#5742]
**Is your feature request related to a problem? Please describe.**
Using ApacheSecureAuth to handle the LDAP authentication seems to be unnecessarily cumbersome and non-portable. Further, solutions that require an LDAP URL for the authentication are bound by the limitations of the LDAP URL spec (no way to embed authentication).

**Describe the solution you'd like**
I'd like to try re-implementing LDAP authentication as a pure PHP LDAP solution a la CertAuth or ShibbolethAuth, rather than relying on Apache modules to do that.

**Describe alternatives you've considered**
None. It simply seems like a better idea that what is, currently, offered.

**Additional context**
I'm looking for reasons why this wouldn't be a good idea.

**Comment by righel** [comment]
implemented with https://github.com/MISP/MISP/pull/10038 and https://github.com/MISP/MISP/pull/10060
