### ISSUE TITLE
When sending a custom email to single user, warning says all users are reciver

### ISSUE THREAD

**Issue by nerok** [MISP/MISP#5745]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS is the host, the container is Debian
| OS version (client)       | Win10
| PHP version               | 7.3.14-1~deb10u1
| MISP version / git hash   | 2.4.123, on modified version of [coolacid/docker-misp](https://github.com/coolacid/docker-misp):core-v2.4.123c
| Browser                   | Firefox and Chrome has been tried

### Expected behavior
When messaging a single user with a custom message, there should be no warning of sending a message to all users.

### Actual behavior
Pressing submit shows a modal, see screenshot, asking for confirmation of sending a mail to all users of a MISP instance.

### Steps to reproduce the behavior
Have an instance with multiple users and go to Administration->Contact Users, fill out form with:
Action = Custom message,
Recipient = A single user
Subject, Recipient and message is arbitrary
Press submit

### Logs, screenshots, configuration dump, ...
![bilde](https://user-images.githubusercontent.com/1485970/77905675-f6cc7500-7286-11ea-8180-82e0238f6a98.png)

**Comment by mokaddem** [comment]
Hi @nerok,
Unfortunately, I cannot reproduce your issue.
For me picking a `single user` as recipient correctly show me only one user in the list and picking `all users` show them all, as expected.
Do you have any information in your logs that could be useful? (`app/tmp/logs`)
Thanks

**Comment by nerok** [comment]
Hi @mokaddem,
Sadly I can't find anything in the logs, but I added a print_r of conditions in UsersController.admin_email, right before the [preview check](https://github.com/MISP/MISP/blob/feec890c8c1bfa579348e41b5c0133393f499c1d/app/Controller/UsersController.php#L1420), and it shows that my condition is "Array ( [AND] => Array ( [0] => Array ( [User.disabled] => 0 ) ) )". I also tried printing the rest of the variables in UsersController.admin_email, but none of them had any variables. This was all tested with the following uri: https://misp-server/admin/users/email/true?recipient=0&recipientEmailList=2&orgNameList=2.

Can't say I know why this is, but I have checked with phpinfo, and there the parameters showed up in the  REQUEST_URI, so at least they are sent to php by NGINX.

![image](https://user-images.githubusercontent.com/1485970/78016234-d36afe00-734a-11ea-9b38-242f1de31eec.png)

Anyway, I have checked that MISP sends email correctly, so I can live with an incorrect warning.

**Comment by mokaddem** [comment]
Hey,
This is rather intriguing..
Looking at the ``request_uri``, it should indeed be correctly be populated with `recipient=0`.
But looking at the condition:
```
Array ( 
    [AND] => Array ( 
        [0] => Array ( [User.disabled] => 0 )
    )
)
```
It clearly misses the user ID, meaning the variable `$recipient` is set to `false`.

Do you mind checking that the parsing of the URI is done correctly?
Adding the line:
```debug($this->request->query);```
before:
https://github.com/MISP/MISP/blob/feec890c8c1bfa579348e41b5c0133393f499c1d/app/Controller/UsersController.php#L1420
should do the trick

Thanks a lot!

**Comment by nerok** [comment]
Hi,
Couldn't get debug() to write anywhere I could see, but used $this->log($this->request->query, 'debug');

Maybe not a surprise that the printed array was empty:
2020-04-06 11:37:54 Debug: Array
(
)
Everything else was done as described in earlier posts.

**Comment by mokaddem** [comment]
Have you tried turning debug mode on in the settings?
It's under ``/servers/serverSettings/Security`` and then ``debug`` setting.
Indeed, it's not a surprise.. Something is preventing cakephp to correctly parse the query url..
I hope enabling debug mode will reveal additional errors.

**Comment by nerok** [comment]
Ah, yes, forgot to check the settings.
Sadly it didn't do much, I added the debug statement right before the preview, and the only thing I can see is
`/app/Controller/UsersController.php (line 1552)
array()`
on the webpage. I checked both the debug and error log. And the logs thats handled by docker-compose, but can't find any thing.

**Comment by mokaddem** [comment]
Hey,
I changed how the parsing of parameter is done.
Instead of using the standard URL query parameters, I switched to cakephp's named parameters.
I hope it solved that weird parsing issue..
Cheers!
