### ISSUE TITLE
Enhance filter API/UI to search based on galaxies

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#5747]
**Is your feature request related to a problem? Please describe.**
When I search for events related to certain actors, ransomware families, TTPs or software, I don't seem to be able to filter based on the galaxies we use.

**Describe the solution you'd like**
If I want to search for an event based on a galaxy, I would like to be able to filter in the GUI and through the API. Now it doesn't seem to be possible to filter specifically on one or a combination of galaxies.

**Describe alternatives you've considered**
I tried using the clear text search but that doesn't seem to be specific enough and then I am unable to filter specifically on those events with the specified galaxies.

**Additional context**
/

**Comment by mokaddem** [comment]
Under the hood, galaxies are tags so if you want to search attributes being tagged with a galaxy, you have to use the `tags` parameter in `attributes/restSearch`.
```
"tags": [
        "misp-galaxy:mitre-attack-pattern=\"Command-Line Interface - T1059\"",
        "misp-galaxy:preventive-measure=\"Block Macros\""
    ]
```

MISP also supports wildcard searches
```
"tags": "misp-galaxy:mitre-attack-pattern=%"
```

And meta information at the cluster level
```
{
    "galaxy.cfr-suspected-victims": ["China", "Japan"],
    "galaxy.cfr-target-category" : ["Government"],
    "galaxy.synonyms": "APT29"
}
```
I hope this helps.
Feel free to ask if you have other questions!

**Comment by digihash** [comment]
Ok, I didn't know this and couldn't find it in the documentation. I'll search again and add it to it if it's not there :). Thank you for the explanation.
