### ISSUE TITLE
Information about current user with API

### ISSUE THREAD

**Issue by Braincoke** [MISP/MISP#5748]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| MISP version / git hash   | 2.4.119

### Support Questions

Given an API Token, how can I retrieve information about the user the API Token is linked to ?
Such as:

- the user id
- the user email
- the organisation id
- the organisation name

I have already read the documentation and more specifically the automation docs but I haven't found anything about it there.

**Comment by github-germ** [comment]
Should be possible with PyMISP if you have that ability.

**Comment by Rafiot** [comment]
Yep, here it is: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L1252

**Comment by Braincoke** [comment]
Wow ! Thanks for the swift response. After debugging PyMISP to understand how it retrieves info about the current user it appears that I just have to perform a GET request to `https://<misp instance>/users/view/me`.

**Comment by github-germ** [comment]
Nice.
