### ISSUE TITLE
Import Regexp Creation Issue

### ISSUE THREAD

**Issue by Xen0ph0n** [MISP/MISP#575]
Hi Team,
   When adding a new import Regexp to MISP as both a site admin, or when the user role is enabled to do so as outlined here (/pages/display/doc/administration#regexp) the result is no addition to the list of active regexes. 
 
  (/admin/regexp/add) will appear to operate as designed and also generate a proper flash success message, but the new regex is neither in the resulting list nor actively being applied to inputs. 

  No log issues are generated, but if this isn't a known issue I can run in debug mode and provide any desired output. Thanks for your attention this is a hugely valuable feature for parsing inputs! 

  Thanks!

**Comment by iglocska** [comment]
Hello Xen0ph0n,

just wondering, did you choose a type for it to be added under? I just checked and if you don't select anything it will show up as added (which isn't exactly a great solution, I'll patch that asap). Just select all if you want it to affect all types or select the type(s) that you'd like to get modified by the filter.

Also, make sure that you enclose the expression between "/"s. 

Let me know if this doesn't solve it for you!

**Comment by Xen0ph0n** [comment]
Ah excellent. Thank you very much for being so responsive. That squared it, I now remember editing my old fork to not need the delims.. It seemed to be passing validation without them on input but just getting dropped prior to insertion which created the above confusion.

**Comment by elhoim** [comment]
@iglocska was the patch done or do I re-open the issue for easier tracking?

**Comment by iglocska** [comment]
Should be good now!
