### ISSUE TITLE
cannot find misp-dashboard misp 2.4.124

### ISSUE THREAD

**Issue by sphereict** [MISP/MISP#5751]
Hi.
Installed the MISP 2.4.124 
used this install method https://misp.github.io/MISP/INSTALL.ubuntu1804/

I am trying to figure out how to get the misp-dashboard active.
Should I be running a script or something ? I am seeing the var/www/misp-dashboard on my install. 
Any help will be appreciated.
Tried these steps as well.
https://www.vanimpe.eu/2017/10/31/misp-dashboard-real-time-visualization-misp-events/

I cannot access the dashboard at all no matter what I try. I check to see if port 8001 is listening and it does but for the life of me it does not open when I visit the page.

**Comment by sphereict** [comment]
Tried these steps as well. 
https://www.vanimpe.eu/2017/10/31/misp-dashboard-real-time-visualization-misp-events/

I cannot access the dashboard at all no matter what I try.  I check to see if port 8001 is listening and it does but for the life of me it does not open when I visit the page.

**Comment by sphereict** [comment]
figured it out

**Comment by sphereict** [comment]
sorted

**Comment by scgsch** [comment]
Hi sphereict,
I have the same issue but with current version 2.4.135. Could you please share what did you do?
I will appreciate it.
Thanks in advance,
