### ISSUE TITLE
Adding a galaxy to an attribute should refresh an event page, not redirect to the main events list

### ISSUE THREAD

**Issue by seanthegeek** [MISP/MISP#5755]
In MISP 2.4.124, adding a galaxy (i.e. ATT&CK mapping) to an attribute will redirect the user back to the main events list. It should just refresh the current event page instead.

**Comment by mokaddem** [comment]
Hi @seanthegeek,
Could you provide more information on which page you are at and how you are adding the galaxy?
It seems working fine on my instance (add it, then fetches via ajax the new values)
Thanks!
