### ISSUE TITLE
SAML Authentication not available

### ISSUE THREAD

**Issue by daniele-spl** [MISP/MISP#5757]
I searched a lot for the possibility to use SAML with our local misp instance but cannot find a solution.
Is it possible and if so, what do i exactly need to do.

I think for most companies its a big issue if you cannot use SAML and need to creat local users.

Thanks

**Comment by kailaru** [comment]
I was able to get SAML working using [mod_auth_mellon](https://jdennis.fedorapeople.org/doc/mellon-user-guide/mellon_user_guide.html#_installing_configuring_mellon), [DUO](duo.com) and the CustomAuth plugin.

My apache2 config:
```
	<Location />
		MellonEnable info
		MellonEndpointPath /saml/
		MellonSPPrivateKeyFile /etc/apache2/mellon/https_misp.example.com_.key
		MellonSPCertFile /etc/apache2/mellon/https_misp.example.com_.cert
		MellonSPMetadataFile /etc/apache2/mellon/https_misp.example.com_.xml
		MellonIdPMetadataFile /etc/apache2/mellon/idp-metadata.xml
		MellonSetEnvNoPrefix REMOTE_USER NAME_ID
        </Location>
        <Location /users/login>
		AuthType Mellon
		MellonEnable auth
		Require valid-user
		RequestHeader set X-Remote-User %{REMOTE_USER}s
	</Location>     
```

The CustomAuth plugin configuration:
```
    'CustomAuth_disable_logout' => false,
    'CustomAuth_header' => 'X_REMOTE_USER',
    'CustomAuth_enable' => true,
    'CustomAuth_use_header_namespace' => true,
    'CustomAuth_header_namespace' => 'HTTP_',
    'CustomAuth_name' => 'SAML authentication',
```

**Comment by paletyp** [comment]
kailaru...Thank you for your post. I have the exact configuration as yours. My site is going in a loop with okta. Can you please suggest if you have done anything else or have seen the loop issue.

**Comment by psrivast31** [comment]
Have you solved your issue? Please help me as well.

**Comment by vineethsai** [comment]
Did anyone get Okta to work with MISP?

**Comment by paletyp** [comment]
I have solved the issue. For me it was a typo in the spmetadata file. At the end apache configuration looked almost exactly like above example. This article also helped https://www.richard-purves.com/2019/05/07/apache-saml-sso-the-hard-way/

**Comment by vineethsai** [comment]
@paletyp Thank you! Are you using Okta as well? or a Variation like Okta Access Gateway (OAG)?

**Comment by paletyp** [comment]
Okta

**Comment by otgrkiss** [comment]
I am currently developing a docker image. The image is an apache proxy that does the authentication against a saml idp and then sets the custom auth header for misp. 

If you are interested or have feedback, please have a look here:

https://github.com/otgrkiss/apache-mellon-saml-misp-proxy

**Comment by eljeffeg** [comment]
Can someone explain if user accounts are needed or how they are created on the local MISP as part of SAML.  I don't want to have to create all the users that might have to access it.  I just sort of want it passed through with a default org applied.  Is that how it works?

**Comment by eljeffeg** [comment]
And if anyone has advice on what to put for the EntityID and the MellonEndPoint, that would be great.  We really need a wiki on this or something.  I'm trying to work though it without any prior knowledge and it's tough to know what to do.

**Comment by qbolbk59** [comment]
@kailaru : I used the config that you have posted. I can see mellon cookie set properly post authentication from my IDP i.e., Okta. However after auth, it simply redirects me to the normal login page of MISP. Also it's not setting the Request header X-Remote-User. Also no error in the logs. 
Any idea what might be wrong or where to look for ?

**Comment by JoePJisc** [comment]
A step by step guide on setting the above up would be great, especially covering:

* User Account Limiting - Limiting MISP access to authorised users (i.e. not all SAML users should have access to MISP), ideally automatically based on the group/role information provided by SAML, failing that by a list of permitted users.
* MISP Org Mapping - Ensure all SAML users go to the correct (single in my case) organisation.
* MISP Role Mapping - Assigning SAML users to MISP (custom) roles, ideally automatically based on the group/role information provided by SAML, but failing an admin manually mapping users.

**Comment by jbuenoo** [comment]
@qbolbk59 were you able to make any progress?  I'm having the exact same issue as you

**Comment by cybgit** [comment]
Does this solution cater for MFA bypass? How would authkeys be known to the IDP or if the IDP handled MFA bypass, how would that map to the authkeys configured in MISP?

**Comment by pietrogu** [comment]
> 



> I was able to get SAML working using [mod_auth_mellon](https://jdennis.fedorapeople.org/doc/mellon-user-guide/mellon_user_guide.html#_installing_configuring_mellon), [DUO](duo.com) and the CustomAuth plugin.
> 
> My apache2 config:
> 
> ```
> 	<Location />
> 		MellonEnable info
> 		MellonEndpointPath /saml/
> 		MellonSPPrivateKeyFile /etc/apache2/mellon/https_misp.example.com_.key
> 		MellonSPCertFile /etc/apache2/mellon/https_misp.example.com_.cert
> 		MellonSPMetadataFile /etc/apache2/mellon/https_misp.example.com_.xml
> 		MellonIdPMetadataFile /etc/apache2/mellon/idp-metadata.xml
> 		MellonSetEnvNoPrefix REMOTE_USER NAME_ID
>         </Location>
>         <Location /users/login>
> 		AuthType Mellon
> 		MellonEnable auth
> 		Require valid-user
> 		RequestHeader set X-Remote-User %{REMOTE_USER}s
> 	</Location>     
> ```
> 
> The CustomAuth plugin configuration:
> 
> ```
>     'CustomAuth_disable_logout' => false,
>     'CustomAuth_header' => 'X_REMOTE_USER',
>     'CustomAuth_enable' => true,
>     'CustomAuth_use_header_namespace' => true,
>     'CustomAuth_header_namespace' => 'HTTP_',
>     'CustomAuth_name' => 'SAML authentication',
> ```

Hi,

to this, I add that is necessary to set the External Auth User for each user in MISP
