### ISSUE TITLE
copy-n-paste error in TrendingTagsWidget.php?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5761]
I believe there's a copy-n-paste error in `app/lib/Dashboard/TrendingTagsWidget.php`
Lines 37 and 38 are currently:
```
$rules['exclusions'] = empty($options['exclude']) ? array() : $options['exclude'];
$rules['inclusions'] = empty($options['exclude']) ? array() : $options['exclude'];
```
Shouldn't the second line read `include` twice instead of `exclude`? If yes, I'll happily open a PR.

**Comment by mokaddem** [comment]
Thanks for the heads up!
