### ISSUE TITLE
Ubuntu instance - disk encryption

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5762]
We are trying to harden Ubuntu to allow it to be used with MISP for our agency. One of the STIGS we need to apply is encryption at rest. Any issues running MISP if we encrypt the data partition prior to installing MISP? Has anyone tried running MISP on an encrypted partition?

**Comment by iglocska** [comment]
Yeah running full disk encryption (LUKS) on my dev system on too, should be no problem.

**Comment by SteveClement** [comment]
I can confirm on my side that FDE is working without known issues.
