### ISSUE TITLE
Unable to connect to TLS 1.3 only servers

### ISSUE THREAD

**Issue by coolacid** [MISP/MISP#5764]
This does not appear as a bug in MISP, but between PHP versions, and cake versions. This should serve as a NOTE more then a bug, and can be used to track support for connecting to TLS 1.3 servers in MISP. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| PHP version               | 7.3.14-1~deb10u1
| MISP version / git hash   | 2.4.124 CoolAcid-Docker

### Expected behavior
Should be able to sync to TLS 1.3 only servers

### Actual behavior
SSL Errors

### Steps to reproduce the behavior
Quickest way is to attempt to sync to a coolacid MISP docker core-v1.2.124a image, which sets TLS 1.3 as the only acceptable connection

------
MISP is currently using Cake v2.10.19 - Looking at https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/CakeSocket.php#L138-L142 Cake attempts to iterate all versions of TLS available to PHP. 

In attempting to identify TLS 1.3, by testing similar named items, this fails. Thus, this test would not function for TLS 1.3. 

https://www.php.net/manual/en/function.stream-socket-enable-crypto.php also does not list it's varients. 

Addtionally, TLS 1.3 was only added into PHP 7.4 (Which means I need to retest the `STREAM_CRYPTO_METHOD` defines in a PHP 7.4)

**Comment by coolacid** [comment]
PHP 7.4

```
PHP 7.4.4 (cli) (built: Mar 31 2020 18:15:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
root@9120a03ed694:/usr/src/myapp# php test.php 
STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT
STREAM_CRYPTO_METHOD_TLSv1_1_SERVER
STREAM_CRYPTO_METHOD_TLSv1_2_SERVER
STREAM_CRYPTO_METHOD_TLSv1_3_SERVER
root@9120a03ed694:/usr/src/myapp#
```

**Comment by coolacid** [comment]
CakePHP issue: https://github.com/cakephp/cakephp/issues/14422

**Comment by RichieB2B** [comment]
There is now a PR for this upstream: https://github.com/cakephp/cakephp/pull/14425
Can you try this:
```
cd app/Lib/cakephp
git pull
git checkout 50e0ca7f9d791f8e98b02c5a63ee79a932051b4b
```

**Comment by RichieB2B** [comment]
@iglocska Maybe bump CakePHP for MISP to [5ccb12354dfc08ca1b3e0a430e8668bf1610b5d3](https://github.com/cakephp/cakephp/commit/5ccb12354dfc08ca1b3e0a430e8668bf1610b5d3) ?

**Comment by IanGabes** [comment]
I have updated my MISP instance running PHP 7.4.4 with the CakePHP patch, and I am now able to talk over TLS 1.3, everything seems to be working well. I linked my fork above. There are changes in the CakePHP 2.x branch outside the scope of this issue, so I not sure about submitting it as a PR.

Thanks all!
