### ISSUE TITLE
Unable to download events using api

### ISSUE THREAD

**Issue by MamrK29** [MISP/MISP#5769]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| OS version (client)       | Win10
| PHP version               | 7.2.19
| MISP version / git hash   | v2.4.119 (a740d145938d6b35c84aadf49d9ab4aee1d869fe)
| Browser                   | If applicable

### Expected behavior
using the https://<domain>/events/restSearch/returnFormat:csv/publish_timestamp:2h/apikey:<apikey>

I was previously able to download events that were published within the last two hours.

### Actual behavior
I get an error saying an internal error has occured

### Steps to reproduce the behavior
Copy the URL mentioned above into a browser, the file would download, now I just an internal error has occured.

### Logs, screenshots, configuration dump, ...
2020-04-03 13:14:41 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 285]
2020-04-03 13:14:41 Error: [InternalErrorException] Internal Server Error
Request URL: /events/restSearch/returnFormat:csv/publish_timestamp:1d/apikey:<api>
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 285, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by MamrK29** [comment]
PHP settings now server are: 
max_execution_time (600)… OK (recommended: 300)
memory_limit (10240M)… OK (recommended: 2048M)
upload_max_filesize (50M)… OK (recommended: 50M)
post_max_size (5120M)… OK (recommended: 50M)

**Comment by MamrK29** [comment]
2020-04-06 21:34:36 Warning: Warning (2): Error while sending QUERY packet. PID=3126 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 715
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1226
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3053
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3025
User::getAuthUserByAuthkey() - APP/Model/User.php, line 641
AppController::checkAuthUser() - APP/Controller/AppController.php, line 809
AppController::beforeFilter() - APP/Controller/AppController.php, line 218
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

2020-04-06 21:36:19 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /events/restSearch/returnFormat:csv/publish_timestamp:2h/apikey:Zehh88orXouXie6F2ur3JMm0xl750hMrgp2yAfoz
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(Attribute), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1411): DboSource->queryAssociation(Object(Attribute), Object(AttributeTag), 'hasMany', 'AttributeTag', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Event), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#9 /var/www/MISP/app/Model/Event.php(2135): Model->find('all', Array)
#10 /var/www/MISP/app/Model/Event.php(6611): Event->fetchEvent(Array, Array, true)
#11 /var/www/MISP/app/Controller/AppController.php(1193): Event->restSearch(Array, 'csv', Array, false, false, 17, false)
#12 [internal function]: AppController->restSearch()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by mokaddem** [comment]
Hey,
I guess you have a lot of attributes in your instance.
A quick win and more efficient way would be to paginate over the data you are fetching.
```
{
    page: 1,
    limit: 1000
}
```
And then increase the page counter accordingly

**Comment by MamrK29** [comment]
Thanks Sami, This will work for a script based pull. We are trying to leverage Splunk ES and it native threat download functionality so I'm not sure if we can page over that. Is there a workaround for that, if not I'll try to go the script route.

**Comment by mokaddem** [comment]
It seems the issue is linked with #5817. Could you confirm?
Also, do you mind to share with us your instance load `/users/statistics.json`?

**Comment by MamrK29** [comment]
The pagination worked like a charm and it allows for the ingestion of more IoCs to the SIEM. We are reworking the method of ingestion to allow for a script.
Thanks.
