### ISSUE TITLE
Possible catch-22 with CustomAuth is enabled with users.change_pw

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5772]
2.4.121

We have `CustomAuth` fully enabled for WebUI user logins working with external authentication. We've noted that `users.change_pw` is set to `1` by default by both the WebUI Add User and PyMISP.

Then when a user attempts their first WebUI login, they are redirected to the change password page, which then displays that feature as being disabled. Hence, a dead end for the user's login.

Yes, we have mitigated this by ensuring to set `users.change_pw` to `0` in our SOP. However, just wanted to raise this catch-22 for others.

**Comment by RichieB2B** [comment]
We have CustomAuth enabled with on-the-fly MISP user creation on first login. The user change_pw flag is set to 0 when they are created by our CustomAuth module. If you are creating a user by hand with CustomAuth you have to manually set change_pw to 0.

**Comment by github-germ** [comment]
> .... If you are creating a user by hand with CustomAuth you have to manually set change_pw to 0.

Agreed, and that's what we do. It also appears that `termsaccepted` needs to be set to `1`.

So, we are OK now. I ahred this for others. And was also wondering if it made sense to have `change_pw` and `termsaccepted` automatically set when `external_auth_required` was enabled.

Thx...

**Comment by dynek** [comment]
> We have CustomAuth enabled with on-the-fly MISP user creation on first login.

@RichieB2B off-topic but how did you get MISP to create external users on the fly?

**Comment by github-germ** [comment]
Being that this is not a show stopped for us, and is stale, I am closing.
