### ISSUE TITLE
3rd party vendor feeds

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5774]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Redhat.
| OS version (client)       | Win10, 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   |Chrome

### Support Questions
We are trying to ingest logs from a 3rd party vendor (LookingGlass) using an API. We are able to retrieve the information using wget. How do we make this information available in the MISP GUI?

**Comment by Rafiot** [comment]
Well, you can add the URL you used wget on and add it as a new feed.

If you want to anything more complex, including mapping LookingGlass to MISP format, you can use PyMISP for example.

**Comment by dmolina213** [comment]
Do you have any sample scripts in PyMISP

**Comment by Rafiot** [comment]
Hmmm yes? https://github.com/MISP/PyMISP/tree/master/examples

Note that we do not have any mapping with LookingGlass, because we aren't customer, you will need to write it yourself, or ask your vendor to do it for you.

**Comment by dmolina213** [comment]
do you have any mapping for Cofense? I hear that it is being used a lot across the pond.  ;-)
I am sure we can figure it out for lookingglass.
Anyways, thanks for all your help

**Comment by iglocska** [comment]
Don't know if many that use it over here personally, but if they want to integrate with misp we can point then in the right direction :)

**Comment by dmolina213** [comment]
Andras, I was able to get the feed working. However, for some reason it started auto publishing the events and sending out email notifications to the users as soon as it was able to pull the data. I did not check the 'auto publish' box. Do you know why it behaved this way?

**Comment by Rafiot** [comment]
What is the type of the feed you're talking about. If it is in MISP format, and you have events marked as published, they will stay published.
@iglocska please jump in if I'm wrong.

**Comment by dmolina213** [comment]
I set it in MISP format. I **did not** mark it to the auto-publish option. It started pulling the feed and publishing and sending out email alerts. The feed is a Custom feed that is supposed to pull intelligence feeds from Cofense. If you want to test it, I can possible generate a token. But I need to get clearance from my managers. I had to delete the feed and shut down postfix to stop mail from being sent out.

**Comment by Rafiot** [comment]
Right, it makes sense from MISP perspective that the published feeds are kept as published when you import it.
We should find a way around it. @iglocska what do you think? Is there a way to silently add the events from a feed?

**Comment by dmolina213** [comment]
But I want to avoid spamming everyone with email alerts. I thought i could accomplish that by not checking the Auto Publish box. Is there an option publish without sending an email?

**Comment by Rafiot** [comment]
not from the feeds, afaik.

Andras will get back to you on that on Monday (it's late Friday afternoon in Europe now).

**Comment by iglocska** [comment]
There is no auto-publish option for the misp format feeds. I have no idea where you set/didn't set that option, the moment you select "MISP" as the feed format that option is gone and it adheres to the data found in the feed.
