### ISSUE TITLE
[MissingTableException] Table user_settings for model UserSetting was not found in datasource default

### ISSUE THREAD

**Issue by lcantelmo** [MISP/MISP#5778]
After update on GUI, I received an Internal Error and cannot login anymore.

error.log 

2020-04-08 17:31:31 Error: [MissingTableException] Table user_settings for model UserSetting was not found in datasource default.
Exception Attributes: array (
  'table' => 'user_settings',
  'class' => 'UserSetting',
  'ds' => 'default',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('user_settings')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#3 /var/www/MISP/app/Controller/AppController.php(528): Model->find('first', Array)
#4 /var/www/MISP/app/Controller/UsersController.php(30): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

Anyone knows how to solve that?

**Comment by mokaddem** [comment]
He @lcantelmo, can you perform the query below in mysql?
```
SELECT * FROM admin_settings WHERE setting='db_version';
```
Thanks

**Comment by lcantelmo** [comment]
@mokaddem Yes! Sure.

MariaDB [misp]> SELECT * FROM admin_settings WHERE setting='db_version';
+----+------------+-------+
| id | setting    | value |
+----+------------+-------+
|  1 | db_version | 50    |
+----+------------+-------+

**Comment by mokaddem** [comment]
May I ask from which version are you coming from (before the update)? Because `user_settings` was introduced a while ago.
Maybe cleaning the cache would solve the issue. Can you run the following command
```
/var/www/MISP/app/Console# ./cake Admin cleanCache
```

**Comment by lcantelmo** [comment]
I restored the snapshot and got the db_version

MariaDB [misp]> SELECT * FROM admin_settings WHERE setting='db_version';
+----+------------+-------+
| id | setting    | value |
+----+------------+-------+
|  1 | db_version | 8     |
+----+------------+-------+

Do I need to clear the cache before updating?

**Comment by mokaddem** [comment]
That's a lot of update to be done but it should be straightforward...
What is even more concerning is that you managed to get to `db_version` 50 with failing SQL queries.
Have you tried re-doing the update? Did you end up in the same state?

**Comment by lcantelmo** [comment]
@mokaddem Yes, I did, the issue occurs again.

**Comment by mokaddem** [comment]
Hey can you check that the table actually exists in you database?
```
MariaDB [misp]> desc user_settings;
```
If the table exists, it might be a cache issue. Usually it is file permissions.
Can you try checking these permission then cleaning the cache after the update?
```
/var/www/MISP/app/Console# ./cake Admin cleanCache
```

**Comment by snakuzzo** [comment]
Hi all,
Same problem upgrading from 2.4.x to 2.5.x.
I solved restarting Apache + PHP-FPM (maybe PHP cache problems)
