### ISSUE TITLE
External Authentication with Corporate Reverse Proxy doesn't work

### ISSUE THREAD

**Issue by lsoumille** [MISP/MISP#5780]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian (Docker https://github.com/coolacid/docker-misp)
| OS version (client)       | Win10
| PHP version               | 7.3
| MISP version / git hash   | v2.4.124 (939c8b45148b0d592c4b3c10562299fb73f3cf99)
| Browser                   | Chrome

### Support Questions

Hello MISP Team,

I have an issue when setting up External authentication with our corporate reverse proxy.

The reverse Proxy is sending the authenticated username in x-proxy-user header. I can see this header when I look at the access.log.

I have make this configuration in MISP Web UI:
![image](https://user-images.githubusercontent.com/9105500/78863578-3d199500-7a3a-11ea-887e-fa12f17930fd.png)

and then I create an user for testing with the checkbox enabled:
![image](https://user-images.githubusercontent.com/9105500/78863693-810c9a00-7a3a-11ea-87b2-eb7711c392dd.png)

I have followed the documentation and this issue https://github.com/MISP/MISP/issues/3059 to help me But it doesn't seem to work. I'm always redirected to the login page.
Moreover I don't have any logs to debug this issue.

Thanks in advance for your help,

Lucas

**Comment by marcnil815** [comment]
Check the config file, if the settings are actually reflected. Sometimes the GUI for some reason does not represent what the actual config is.
`sudo -u www-data vim /var/www/MISP/app/Config/config.php`

**Comment by lsoumille** [comment]
Hi @marcnil815 
Thanks for your answer
The file content seems ok to me or at least similar to configuration on the UI
 

> 'Plugin' =>
  array (
    'ZeroMQ_redis_host' => 'redis',
    'ZeroMQ_enable' => true,
    'Enrichment_services_enable' => true,
    'Enrichment_services_url' => 'http://misp-modules',
    'Import_services_enable' => true,
    'Import_services_url' => 'http://misp-modules',
    'Export_services_enable' => true,
    'Export_services_url' => 'http://misp-modules',
    'Cortex_services_enable' => false,
    'CustomAuth_disable_logout' => false,
    'CustomAuth_enable' => true,
    'CustomAuth_header' => 'x-proxy-user',
    'CustomAuth_header_namespace' => '',
    'CustomAuth_use_header_namespace' => true,
    'CustomAuth_name' => 'f5 authentication',
    'Enrichment_hover_enable' => true,
    'Enrichment_sigma_queries_enabled' => true,
    'Enrichment_sigma_syntax_validator_enabled' => true,
  ),

If you have any other ideas,

Thanks,

Lucas

**Comment by marcnil815** [comment]
The 'CustomAuth_use_header_namespace' is empty. Set to 'HTTP_'

(edit: typo)

**Comment by mokaddem** [comment]
@lsoumille  Has this been resolved?
