### ISSUE TITLE
Feeds created with "Caching Enabled" show "Not Cached" on feeds table

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#5782]
We have feeds that have "Caching Enabled" selected.  However, when looking at the "Cached" column on the Feeds table, there is "Not Cached" displayed.  This behavior is seen over multiple MISP instances.  Is this a bug?  If not, why is there a discrepancy?

**Comment by mokaddem** [comment]
By enabling `Caching enabled`, you can request MISP to cache the feed.
You can do it via the UI by clicking on the small RAM button icon in the `caching` column.
You can also trigger the caching by running the CLI command described here `/events/automation`.
