### ISSUE TITLE
MISP home page is not displayed

### ISSUE THREAD

**Issue by TossicissoT** [MISP/MISP#5786]
Hello,

first off thank you in advance for the support, I'm new in MISP and I have to use it for job reasons.

I have installed MISP on my Linux distro:

Description:	Kali GNU/Linux Rolling
Release:	2020.2
Codename:	kali-rolling

During the installation phase, I have provided the path for the access page, which was the one suggested by the installation procedure (https://my_private_ip_address).

The installation ended with the provision of all credentials.

When I tried to connect through Firefox, after having added the security exception, nothing is displayed on the page, which is completely blank, no error message, nothing.

Honestly I searched the Internet for a possible cause, but couldn't find that much.

Thank you for any help.

**Comment by iglocska** [comment]
Let's have a look at the logs to see what went wrong:

1. Apache access log, normally at /var/log/apache2/misp.local_access.log - do you see your connection attempt?
2. If yes, do you see an error on apache level? /var/log/apache2/misp.local_error.log
3. If yes and it's not https / webserver related, do you see a stack trace in /var/www/MISP/app/tmp/logs/error.log?

Could you paste the contents here?

**Comment by Rickozono** [comment]
I'm having the same issue, this is the content I have in misp.local_error.log.
How do I solve it?
Thanks you for any help

[Tue May 05 12:40:08.110424 2020] [php7:warn] [pid 73991] [client 127.0.0.1:44874] PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www>
[Tue May 05 12:40:08.110463 2020] [php7:error] [pid 73991] [client 127.0.0.1:44874] PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/>
[Tue May 05 12:46:28.094829 2020] [php7:warn] [pid 74003] [client 127.0.0.1:44882] PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www>
[Tue May 05 12:46:28.094867 2020] [php7:error] [pid 74003] [client 127.0.0.1:44882] PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/>
[Tue May 05 12:47:44.215379 2020] [ssl:warn] [pid 596] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:47:45.003007 2020] [ssl:warn] [pid 620] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:49:42.249806 2020] [php7:warn] [pid 642] [client 127.0.0.1:36008] PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/M>
[Tue May 05 12:49:42.249866 2020] [php7:error] [pid 642] [client 127.0.0.1:36008] PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/ph>
[Tue May 05 12:53:46.859169 2020] [php7:warn] [pid 640] [client 127.0.0.1:36012] PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/M>
[Tue May 05 12:53:46.859204 2020] [php7:error] [pid 640] [client 127.0.0.1:36012] PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/ph>
[Tue May 05 12:58:00.560693 2020] [ssl:warn] [pid 5113] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:58:00.589040 2020] [ssl:warn] [pid 5114] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:59:15.553900 2020] [ssl:warn] [pid 9015] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:59:15.589725 2020] [ssl:warn] [pid 9016] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 13:00:19.560433 2020] [php7:warn] [pid 9054] [client 127.0.0.1:36174] PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/>
[Tue May 05 13:00:19.560498 2020] [php7:error] [pid 9054] [client 127.0.0.1:36174] PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/p>

**Comment by mokaddem** [comment]
It seems to either be that something went wrong during the installation and you are missing some files or a file permission issue. Could you please check if the file are there and that they have the correct permission?
Thanks

**Comment by Rickozono** [comment]
I was installing it in kali 2020. I tried on an Ubuntu 18.04, and I was able to install it. Thanks for your help!

**Comment by MehdiMsa** [comment]
Hello everyone, I am currently facing the same issue with Ubuntu Server 22.04 LTS. the IP address directs me to a blank webpage.
I hope that this issue was fixed.
