### ISSUE TITLE
Can't reach login page

### ISSUE THREAD

**Issue by hitwh0071** [MISP/MISP#5787]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4
| Browser                   | Chrome

### Expected behavior

on ubuntu
 visit https://localhost:8443 show me login page

### Actual behavior

on ubuntu
Secure Connection Failed
An error occurred during a connection to localhost:8443. SSL received a record that exceeded the maximum permissible length.

### Steps to reproduce the behavior

1.Install misp
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c
2.visit https://localhost:8443
as above show,Secure Connection Failed.

### Logs, screenshots, configuration dump, ...
![mispinstalled](https://user-images.githubusercontent.com/50914668/79303043-82e5ca00-7f20-11ea-808e-cae085f3eb15.png)

![misp无法登陆](https://user-images.githubusercontent.com/50914668/79302824-fe934700-7f1f-11ea-8bc7-633eeb817ddc.png)
![curl](https://user-images.githubusercontent.com/50914668/79302830-0226ce00-7f20-11ea-9ebd-a19c406e50ef.png)

**Comment by mokaddem** [comment]
It seems that your apache is not correctly configured. Could you review it?
Also, do you get this error straight after the installation?

**Comment by hitwh0071** [comment]
ok. I will check it and this error just happen after i finish the installlation.I do nothing before I visit  https://localhost:8443 .

**Comment by enjeck** [comment]
> ok. I will check it and this error just happen after i finish the installlation.I do nothing before I visit https://localhost:8443 .

@hitwh0071 After this, did you reach the login page?
