### ISSUE TITLE
Feed is not removed when deleting from Feeds UI

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#5789]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | Ubuntu
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.118
| Browser                   | All Browsers

### Expected behavior

(1) Click on Delete Feed from Feed UI:   https://<<<My-MISP>>>/feeds/index
(2) Feed is Deleted

### Actual behavior

(1) Click on Delete Feed from Feed UI:   https://<<<My-MISP>>>/feeds/index
(2) Feed remains.

_Note_ 

_(3a) we also have witnessed previously deleted 'default' feeds reappear.  Have not determined what actions lead to this happening._  

_(3b) We also end up with duplicates of 'default' feeds that we have edited/modified to our needs._

### Steps to reproduce the behavior

(1) Click on Delete Feed from Feed UI:   https://<<<My-MISP>>>/feeds/index
(2) Feed remains
(3) (1) Click on Delete Feed from Feed UI.
(4) Feed remains
(5) Wash, Rinse, Repeat until such time as Einstein's Insanity Rule is satisfied ;-)

### Logs, screenshots, configuration dump, ...

![Feed Deletion Issue](https://user-images.githubusercontent.com/3220193/79340359-2f5f8600-7ef8-11ea-845a-49473421e41e.png)

**Comment by StefanKelm** [comment]
related to #2542?

**Comment by packet-rat** [comment]
I just noted when looking for any errors related to the deletion that a new feed is added right after the deletion:


Id | IP | Email | Org | Created | Model | Model ID | Action | Title | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

155303194 | <xxx>| <xxx>@local.net | <xxx>| 2020-04-15 13:35:20 | Feed | 221 | **delete** | IPsum (aggregation of all feeds) - level 3 - low false positives |  


155303196 | <xxx> | <xxx>@local.net | CSO<xxx>| 2020-04-15 13:35:20 | Feed | 229 | **add** | IPsum (aggregation of all feeds) - level 3 - low false positives | distribution () => (0), sharing_group_id () => (0), tag_id () => (1), default () => (1), source_format () => (freetext), fixed_event () => (1), event_id () => (0), input_source () => (network), lookup_visible () => (1), caching_enabled () => (1), name () => (IPsum (aggregation of all feeds) - level 3 - low false positives), provider () => (IPsum), url () => (https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt), settings () => ({"csv":{"value":"","delimiter":","},"common":{"excluderegex":""}})

**Comment by packet-rat** [comment]
> related to #2542?

_Yeah -- I was pretty sure I'd jumped in on this before.  For some reason my Issues List search for terms "Feed, Deletion/Delete, UI" did not return 2542_ 

This is truly a bug and creates all kinds of issues/time wasters  for us in our feed management processes.  Whether they come back as disabled is not the point,  We don't want them to come back when we delete them or duplicate themselves with original values if we edit them.  Willing to accept that an update might lead to the need to prune the current Feeds list -- that's completely acceptable.
