### ISSUE TITLE
OpenIOC import - SHA256 hashes

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#579]
When importing an openIOC file, SHA256 hashes were not imported. They were added as ccomments with this kind of content __FileItem/Sha256sum: e326ff4b3581b0c6cabdf973ad62a3feadad31f65bac975572f55cf1462bbab7__

File is hackingteam_openIOC1-1.ioc contained in [this](https://www.rooksecurity.com/wp-content/uploads/2015/07/Package_1.0.1.zip).

**Comment by iglocska** [comment]
This was fixed a while back.
