### ISSUE TITLE
Default Feed - URLHaus Malware URLs - Fails to import

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#5790]
We have URLHaus configured to collect data into MISP daily.  A file is downloaded in zip format.  Unfortunately, the following error is generated when the feed is accessed:

2020-04-15 10:31:09 Error: Could not save freetext feed data for feed 57.
[PDOException] SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\x8FP\xFB;\xDAq...' for column 'value1' at row 1
Stack Trace:

The CSV looks like this:
################################################################
# abuse.ch URLhaus Database Dump (CSV)                         #
# Last updated: 2020-04-15 15:07:33 (UTC)                      #
#                                                              #
# Terms Of Use: https://urlhaus.abuse.ch/api/                  #
# For questions please contact urlhaus [at] abuse.ch           #
################################################################
#
# id,dateadded,url,url_status,threat,tags,urlhaus_link,reporter
"340827","2020-04-15 15:07:33","http://219.155.171.170:33935/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340827/","Gandylyan1"
"340826","2020-04-15 15:07:30","http://124.67.89.40:49688/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340826/","Gandylyan1"
"340825","2020-04-15 15:07:26","http://218.21.171.207:42531/Mozi.m","offline","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340825/","Gandylyan1"
"340824","2020-04-15 15:06:34","http://183.215.188.45:47446/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340824/","Gandylyan1"
"340823","2020-04-15 15:06:31","http://123.4.53.153:46423/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340823/","Gandylyan1"
"340822","2020-04-15 15:06:28","http://117.87.66.235:58679/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340822/","Gandylyan1"
"340821","2020-04-15 15:06:23","http://222.141.103.12:55114/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340821/","Gandylyan1"
"340820","2020-04-15 15:06:19","http://42.225.236.90:33101/Mozi.m","online","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340820/","Gandylyan1"
"340819","2020-04-15 15:06:12","http://172.39.64.170:45740/Mozi.m","offline","malware_download","elf,Mozi","https://urlhaus.abuse.ch/url/340819/","Gandylyan1"

This is a MISP ~Default~ feed so did something change in MISP or the feed?

**Comment by EdAtt** [comment]
The data file is downloaded as a ".zip" file.  It is unknown if this is the cause of the problem or not.  After manually unzipping the downloaded file manually, the data looks to be OK.

**Comment by iglocska** [comment]
Yeah the format in which the feed is distributed has changed - they started zipping it. We'll try to update the parser to handle it in the near future.

**Comment by GlennHD** [comment]
I'd imagine we would want to be good stewards of resources from these free services.  I'd recommend doing a first time full CSV dump to "catch up" and then download events via the `https://urlhaus.abuse.ch/downloads/csv_recent/` 30-day URL.  We should probably do this for all abuse.ch feeds.
