### ISSUE TITLE
Send email to external server for requesting access

### ISSUE THREAD

**Issue by Genliese** [MISP/MISP#5792]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.124
| Browser                   | Chrome

### Support Questions
On web interface I Send email for requesting access to external server(every item of List Communities).But I get a error on page "An Internal Error Has Occurred.Error: An Internal Error Has Occurred."

### Logs, screenshots, configuration dump, ...
But Self-reg：Send email to "COVID-19 MISP community" successfully for requesting access.
![image](https://user-images.githubusercontent.com/28807542/79407660-1c1dea80-7fcc-11ea-97ca-7f9df72a057e.png)

![image](https://user-images.githubusercontent.com/28807542/79407668-20e29e80-7fcc-11ea-9ecd-27e67fcc623d.png)

![image](https://user-images.githubusercontent.com/28807542/79407683-26d87f80-7fcc-11ea-98c5-48f9c587b35a.png)

![image](https://user-images.githubusercontent.com/28807542/79407706-3a83e600-7fcc-11ea-9c34-1da56d8a7830.png)

![image](https://user-images.githubusercontent.com/28807542/79407727-4a032f00-7fcc-11ea-96a5-7c4125c7ed91.png)

**Comment by iglocska** [comment]
Will have a look, glad that you've opened the issue as I couldn't add your account on the COVID-19 instance - your address is @misp.local in the request so no mails will ever reach you, could you issue a new request with your own e-mail address? :)

**Comment by Genliese** [comment]
> Will have a look, glad that you've opened the issue as I couldn't add your account on the COVID-19 instance - your address is @misp.local in the request so no mails will ever reach you, could you issue a new request with your own e-mail address? :)

Firstly,Thanks.I have used my own e-mail address to send email to COVID-19 instance for requesting access.
Another question:
![image](https://user-images.githubusercontent.com/28807542/79521676-518a0d00-808c-11ea-8ac3-6220328d56dd.png)

![image](https://user-images.githubusercontent.com/28807542/79521774-8a29e680-808c-11ea-9c1b-5e5051c7a785.png)

**Comment by iglocska** [comment]
Seeing the error you get there - is your local MISP configured to send e-mails? That error generally means that no mail server is configured. The interface that worked for you is hosted on the remote instance (if you check the URL for the form you're filling out).
