### ISSUE TITLE
cake server pull/push error 

### ISSUE THREAD

**Issue by wisekhan** [MISP/MISP#5793]
Hi,
Our misp server info:
2.4.122/ubuntu 18.04.02
I wanted to schedule pull /push request through cake/cron jobs.

I got the following error
------------------------------------------------------
root@mispsrv:/var/www/MISP/app/Console# ./cake Server pull 3 4 full
Welcome to CakePHP v2.10.19 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Notice Error: Undefined property: ServerShell::$ConfigLoad in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]

2020-04-16 10:12:39 Notice: Undefined property: ServerShell::$ConfigLoad in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]
Error: Call to a member function execute() on null
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('pull', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher-
>dispatch()
#3 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#4 {main}
------------------------------------------------------
I have checked the case in https://gitter.im/MISP/Support?at=5e8435fcc5c3c32343bbae93
I did chwon -R www-data:www-data /var/www/MISP. it didn't work for me.

What can be the main reason?
git status output
root@mispsrv:/var/www/MISP/app/webroot# git status
On branch 2.4
Your branch is up to date with 'origin/2.4'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../cti-python-stix2 (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../../INSTALL/dependencies/
        ../Config/config.php.bk

Thanks

**Comment by mokaddem** [comment]
Hey,
Thanks for the report!
I believe the issue is now solved. If it's not, let us know!

**Comment by user4913** [comment]
I am currently getting the exact error message above. How was this resolved? I also tried chwon but it didn't work.

**Comment by mokaddem** [comment]
@user4913 are you up to date with the 2.4?

**Comment by wisekhan** [comment]
> @user4913 are you up to date with the 2.4?

Yes we are up to date if you check the output it is saying "Your branch is up to date with 'origin/2.4'"

**Comment by wisekhan** [comment]
> Hey,
> Thanks for the report!
> I believe the issue is now solved. If it's not, let us know!

no the issue has been solved yet!
I tried everything mentioned in the link https://gitter.im/MISP/Support?at=5e8435fcc5c3c32343bbae93 as I mentioned above, but no luck!
Please help!

**Comment by mokaddem** [comment]
> > @user4913 are you up to date with the 2.4?
> 
> Yes we are up to date if you check the output it is saying "Your branch is up to date with 'origin/2.4'"

Did you actually fetched data from the remote?

**Comment by user4913** [comment]
I just updated to the version that was released last night (2.4.125) and now it seems to work :) Thanks heaps.
