### ISSUE TITLE
MISP to Slack integration issue 

### ISSUE THREAD

**Issue by oz17il** [MISP/MISP#5794]
Hi all,
https://github.com/MISP/MISP/tree/2.4/tools/misp-zmq

I'm not sure if I'm missing anything in the settings but it seems to be missing out on MISP authentication. How does the script pull the events from MISP to publish them in slack?

Anyway, I'd love for someone to explain how to figure out what the problem is because it doesn't seem to be working.

```
channel_name = '#misp_alerts'
slack_token = 'xoxb-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

misp_url = 'https://misp.xxx.com'
misp_is_public = True   # set to False if your MISP instance is on a non-internet reachable location. Shows the org icon of the event owner.$

# filter for confidentiality
allowed_distributions = ['0', '1', '2', '3', '4']  # * = all, 0/ my org only, 1/ this community, 2/ connected communities, 3/ all communitie$
allowed_sharing_groups = ['*']  # put here the sharing_group_ids that you allow

max_value_len = 25  # truncate values longer than X chars
include_attr = True  # include attributes in the message
include_obj = True   # include objects in the message
```

**Comment by SteveClement** [comment]
ping @cvandeplas I havent tested this myself yet.

**Comment by cvandeplas** [comment]
Hi there, the script is using the ZeroMQ subscription system to receive the information. So it must have a network connection with the MISP server and access to the ZeroMQ port.

It can therefore not be used by any user who has an API key, but needs to be set up by the organisation who is running that MISP specific instance/community.

If you're just a user there are different options:
1/ run yourself a MISP server syncing with the other, and use this script in conjunction with your own MISP server/ ZeroMQ.

2/ make a new polling script using pymisp, and glue with slack

3/ other creative solutions such as having a websockets-based push system for MISP developed, limited with your user-rights.

**Comment by enjeck** [comment]
@oz17il Did you eventually succeed doing this integration?
