### ISSUE TITLE
Update users.last_login with external auth user login

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5797]
2.4.121

We are now using `CustomAuth` external authenticated user logins into MISP. Works real nicely: thanks!

Would it be possible to have the db `users.last_login` updated? Also, perhaps a login row in the `logs` table?

I do see that the db `logs` table gets a new row for every WebUI click where
```
logs.title = "Successful authentication using MyLogins External authentication key"
```
However, it is difficult to deduce which one is an initial login. I believe a non-auth user login does cause a distinct row insert into `logs`, but not for ext auth.

Open to suggestions on how we may collect external auth user login stats. Thanks...

**Comment by chrisinmtown** [comment]
hello CIRCL team, surprised to see no comments for 10 months.  It's important for us to know who is using the systems. Please give some BRIEF guidance of how this might be implemented, then I can develop a first draft for your review.

First a requirements question: should a successful API request be treated as a login and cause update of the user's last_login field? Or is "login" strictly a successful web UI authentication?

Another requirements question - how to determine that a new login has occurred on the web UI when using custom auth? In other words, can the MISP server detect the transition from not-authenticated to authenticated?   For example, in our case we use a script that checks for presence of a cookie.  Probably don't want to update last_login at every page request.

I was thinking that the users table last_login field needs to be updated from somewhere in the AppController.php beforeFilter() method when it decides the user has been authenticated. I expect the normal non-custom-auth path also updates the last_login field, but so far I cannot figure out how/where.

I see UsersController.php defines _postlogin() function which updates the last_login field. That function is called from the UsersController.ph login() function.  I'm not an expert in PHP but I cannot find any invocations of that function from AppController.
 
Less promising, I see that UsersController.php defines function updateLoginTime().  However the last line of that method redirects the user to the Dashboard.  The only match on updateLoginTime I can find is in file View/Elements/dashboard/dashboard_events.ctp which seems to publish a link to an endpoint /users/updateLoginTime, but I cannot find that link on the Dashboard view.  Maybe this is a distraction, that last login can be updated via a visit to the Dashboard?
