### ISSUE TITLE
An Internal Error Has Occurred

### ISSUE THREAD

**Issue by tigers99** [MISP/MISP#5798]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 
| OS version (client)       | Win10
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Support Questions
After several months of non-use, get "An Internal Error Has Occurred" for any page I request.
Please see some logs below.
Thank you for your assistance.

### Logs, screenshots, configuration dump, ...
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-47-generic x86_64)
  System information as of Sat Apr 18 12:48:31 UTC 2020

  System load:  0.0                 Processes:             117
  Usage of /:   97.8% of 195.81GB   Users logged in:       1
  Memory usage: 5%                  IP address for ens160: 193.218.48.35
  Swap usage:   0%

  => / is using 97.8% of 195.81GB

FROM error.log:

2020-01-18 08:33:49 Warning: Warning (2): session_write_close() [<a href='http://php.net/function.session-write-close'>function.session-write-close</a>]: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2020-01-18 08:33:49 Warning: Warning (2): session_write_close(): write failed: No space left on device (28) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2020-01-18 08:33:49 Warning: Warning (2): session_write_close() [<a href='http://php.net/function.session-write-close'>function.session-write-close</a>]: Failed to write session data (files). Please verify that themisp@XXXXXXXXX:/var/www/MISP/app/tmp/logs$

df -h
misp@XXXXXXXXX:/var/www/MISP/app/tmp/logs$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               3.9G     0  3.9G   0% /dev
tmpfs                              798M  1.1M  797M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  196G  192G     0 100% /
tmpfs                              3.9G     0  3.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0                          87M   87M     0 100% /snap/core/4917
/dev/loop1                          90M   90M     0 100% /snap/core/6673
/dev/sda2                          976M  142M  767M  16% /boot
tmpfs                              798M     0  798M   0% /run/user/1000
misp@myt-dmz-misp00:/var/www/MISP/app/tmp/logs$

**Comment by Rafiot** [comment]
Well, as the logs say you, your disk is full and you need to do something about it in order to get your MISP back on.

**Comment by tigers99** [comment]
Hello Rafiot, thanks for your message, can you give any pointers on what should be deleted ? Any relevant reference ? Thanks again.

**Comment by Rafiot** [comment]
Well, first of all, I guess you wanted to do `du -sh` from `/var/www/MISP/app/tmp/logs`, because `df -h` is literally just saying that your disk is full.

and then, maybe you want to look at the content of `/var/log` too? and maybe the size of your mysql database `/var/lib/mysql`?

if you need such support, please allow me to point you to our professional services page: https://www.misp-project.org/professional-services/

**Comment by tigers99** [comment]
Rafiot, thanks for pointing to your professional services.
For now, you may reopen this as it is unresolved.

**Comment by Rafiot** [comment]
The problem you're having is crystal clear, and the way to solve it is a trivial sysadmin task (and may not even be related to MISP itself, as other things can fill a disk).

If you need more support from us, please **open an other issue** with the information I asked above, or ask the system administrator of this machine to support you.

**Comment by tigers99** [comment]
So Rafiot, the message is related to a full disk, that is your opinion ? Why not let someone else have a say ?

**Comment by tigers99** [comment]
Well Rafiot, I will take your advice after all and work on the disk problem. And return with a new request if at all necessary. Thanks for your time.

**Comment by Rafiot** [comment]
> So Rafiot, the message is related to a full disk, that is your opinion ? Why not let someone else have a say ?

because it is what the log, **and** the df -h output says, and these are the only two data points you gave us to work with.
