### ISSUE TITLE
FreeText Import - allow mass recategorization of file hashes

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#580]
When using FreeText Import, file hashes have the category "Payload Delivery" selected by default. Would it be possible to have a way to mass recategorize those to other possible categories (Payload Installation, Artifacts Dropped and External Analysis)?
Exactly like what was done with hostname/domain/URL.

**Comment by elhoim** [comment]
Daring to change it to v2.4-hotfix. :)

**Comment by Rafiot** [comment]
Fixed :)
