### ISSUE TITLE
is there a way to see sync api authkey in local instance.

### ISSUE THREAD

**Issue by wisekhan** [MISP/MISP#5805]
Hi,
Gui is hiding the sync api authkey for server synchronization
Is there a easy way to see the sync api authkey?

Many Thanks

**Comment by iglocska** [comment]
Not very convenient but you can append ".json" at the end of the URL to get the JSON representation of the server index - look for the authorization key in the server object.

**Comment by wisekhan** [comment]
can you elaborate a bit which url to add .json. can you give an example
Let me describe more: 
I am asking the auth key in sync actions --> list servers -> edit one of the server -> auth key
which is saying (you can see it in remote profile). But if you dont have browser access you cannot see it.

![image](https://user-images.githubusercontent.com/37660337/80700692-70ea5680-8ade-11ea-8d49-c95ca17a2850.png)

**Comment by mokaddem** [comment]
The URL @iglocska is referring to is `/servers/index.json` . You should be able to see your sync api keys in `[].Server.authkey`.
Alternatively, you can use the API:
```
GET /servers/index
```
