### ISSUE TITLE
Question about warning list

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#5808]
Hello, I can't understand can I remove all attributes that are marked as occurring in the warning lists. For example I have event, generated based on feed with 500 and more attributes, can I delete all attributes that matches at warning list automatically?I understand that I can use filtering, but can I do it automatically?

**Comment by mokaddem** [comment]
Hey,
You can't delete automatically Attribute matching warninglists.
However, you can filter out attributes matching the enabled warning in your instance by passing `enforceWarninglist: 1` in a `restSearch` endpoint.
I hope that helps.
