### ISSUE TITLE
SSL verification between sync server - 'real' cert with multiple alt. DNS names

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#581]
Hi,

When I synced to a server that had multiple alternate DNS names (not a self-signed certif) I got the error
`stream_socket_client(): Peer certificate CN='mainif.abc.be' did not match expected CN='if.abc.be'`

Based on [https://github.com/MISP/MISP/issues/178] in Lib/Cake/Network/Http/HttpSocket.php I set 
`'ssl_verify_peer' => false,`
That solved it. I assume this is because of an underlying Cake issue? 
Are there any other ways to get by this error instead of changing the Cake code?

thanks,

koen

**Comment by cvandeplas** [comment]
Setting ssl_verify_peer to False is kinda removing the S from HTTPS/SSL.

To validate it's a Cake problem we'd need to look into that code or the
issue tracking system of CakePhp

**Comment by elhoim** [comment]
CakePHP related ticket: https://github.com/cakephp/cakephp/issues/2050, they mention that it cannot be solved in CakePHP, but it might be solved by PHP patches.

In PHP repo, they mention in [this ticket](https://github.com/php/php-src/pull/482) that they added verification in PHP v5.6.0alpha2 in commit https://github.com/rdlowrey/php-src/commit/1970b964430a357d9c9acf01268849d86a99f4ec which has been merged in php-master in  2013.

Do you use a PHP version >5.6?

**Comment by cudeso** [comment]
No, PHP 5.5.9.
I'll ask for a copy of the machine, upgrade to PHP to 5.6 and check if that solves the issue.

**Comment by cudeso** [comment]
Solved with upgrading PHP to 5.6
