### ISSUE TITLE
Request acccess to community

### ISSUE THREAD

**Issue by Genliese** [MISP/MISP#5814]
#3377 # Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Win10..
| PHP version               | 7.2
| MISP version / git hash   | 2.4.124
| Browser                   | Chrome

### Support Questions
I generate a new pair of pgp keys and fiil in the form and sent a e-mail to "CIRCL Private Sector Information Sharing Community - aka MISPPRIV" for requesting sync access successfully.But I receive a mail which title is "We don't have your public key or it's invalid".

What happen?Your help is requested.

I use following command to generate a new pair of pgp keys.:
rm -rf /var/www/MISP/.gnupg
sudo -u www-data mkdir /var/www/MISP/.gnupg
sudo chmod 700 /var/www/MISP/.gnupg
sudo -u www-data gpg --homedir /var/www/MISP/.gnupg --gen-key

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/28807542/80198417-9e548180-8652-11ea-9af1-4aa50f1374ea.png)

![image](https://user-images.githubusercontent.com/28807542/80198486-b5936f00-8652-11ea-94ed-64a5de33b58f.png)

![image](https://user-images.githubusercontent.com/28807542/80198513-bdebaa00-8652-11ea-8410-18a714e513a7.png)

**Comment by Genliese** [comment]
TOP

**Comment by mokaddem** [comment]
I can see on the first screenshot that your emailing is currently disabled.
How did you send the generated mail?
Also it seems weird that you have your message unencrypted despite having chosen MISPPriv which has a PGP key attached.

**Comment by mokaddem** [comment]
But anyway. The message tells you explicitly that you don't have to worry or react.

**Comment by Genliese** [comment]
> I can see on the first screenshot that your emailing is currently disabled.
> How did you send the generated mail?
> Also it seems weird that you have your message unencrypted despite having chosen MISPPriv which has a PGP key attached.


1.How did I send the generated mail?
Click "submit".Though MISP show me following:
![image](https://user-images.githubusercontent.com/28807542/81242473-cde68f00-903f-11ea-82a8-790f94cb0147.png)


Sent successfully
![image](https://user-images.githubusercontent.com/28807542/81242485-da6ae780-903f-11ea-9da4-27835f8dd5f8.png)


2.How to fill in the form "PGP public key" in the correct format?

Can I use self-generated PGP public key?

"PGP public key" in the correct format?

-----BEGIN PGP PUBLIC KEY BLOCK-----

this?

mQGNBF6iq4EBDADPMw/sVFsqQ4FBpGqVW4OO/nFtpHY7V1eKxz31JbskGZPF5ecF
fjFyvo56iJFqSfb4pLcqw6ZHko7gS4/31keRIokZGMHfbdreRw+XGqfr5o6fr9yA
.......
-----END PGP PUBLIC KEY BLOCK-----

Or this?

mQGNBF6iq4EBDADPMw/sVFsqQ4FBpGqVW4OO/nFtpHY7V1eKxz31JbskGZPF5ecF
fjFyvo56iJFqSfb4pLcqw6ZHko7gS4/31keRIokZGMHfbdreRw+XGqfr5o6fr9yA
.......

**Comment by Genliese** [comment]
> But anyway. The message tells you explicitly that you don't have to worry or react.

Sascha Rommelfangen tell me that their team will handle my request as soon as possible.But I send this request on April 24rd.It's been 13 day.I don't know When can I receive the result of the request.

**Comment by adulau** [comment]
It's up to the community handling the request. MISP Project issue is for the open source software.
