### ISSUE TITLE
CSV feed Target Event mode lost

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#5815]
When defining a new CSV feed and selecting `New Event Each Pull` as the `Target Event` mode this information is lost when saving the feed. It is reset to `Fixed Event` instead. After editing the new feed the mode can be changed to `New Event Each Pull` and saved correctly.

This was observed while running 2.4.124 commit 9ca3fafca4f2907aba038b5f6cc865bb325f4c9b

**Comment by mokaddem** [comment]
Thanks for the report!
