### ISSUE TITLE
RestSearch API - max_allowed_packet

### ISSUE THREAD

**Issue by MamrK29** [MISP/MISP#5817]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS7.7
| OS version (client)       | Win10
| PHP version               | 7.2.19
| MISP version / git hash   | v2.4.119 (a740d145938d6b35c84aadf49d9ab4aee1d869fe)
| Browser                   | If applicable

### Expected behavior
/events/restSearch/returnFormat:csv/publish_timestamp:2h/apikey:<Apikey>

Show download the csv of all events published within the last 2 hours

### Actual behavior
Internal Server error generated

### Steps to reproduce the behavior
https://<url>/events/restSearch/returnFormat:csv/publish_timestamp:2h/apikey:<Apikey>

### Logs, screenshots, configuration dump, ...
2020-04-24 15:31:31 Error: [PDOException] SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
Request URL: /events/restSearch/returnFormat:csv/publish_timestamp:2h/apikey:<apikey>
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(Attribute), 'SELECT `Attribu...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1411): DboSource->queryAssociation(Object(Attribute), Object(AttributeTag), 'hasMany', 'AttributeTag', Array, Array, true, Array, 1, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(Event), Object(Attribute), 'hasMany', 'Attribute', Array, Array, true, Array, 2, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Event), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#9 /var/www/MISP/app/Model/Event.php(2135): Model->find('all', Array)
#10 /var/www/MISP/app/Model/Event.php(6611): Event->fetchEvent(Array, Array, true)
#11 /var/www/MISP/app/Controller/AppController.php(1193): Event->restSearch(Array, 'csv', Array, false, false, 27, false)
#12 [internal function]: AppController->restSearch()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
2020-04-24 15:31:31 Warning: Warning (2): Error while sending QUERY packet. PID=14748 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
PDOStatement::execute() - [internal], line ??
DboSource::_execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502
DboSource::execute() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 468
DboSource::fetchAll() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 715
DboSource::read() - APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1226
Model::_readDataSource() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3053
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3025
User::getAuthUserByAuthkey() - APP/Model/User.php, line 641
AppController::checkAuthUser() - APP/Controller/AppController.php, line 809
AppController::beforeFilter() - APP/Controller/AppController.php, line 218
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
ExceptionRenderer::_getController() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 158
ExceptionRenderer::__construct() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 95
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 126
[main] - [internal], line ??

**Comment by MamrK29** [comment]
MariaDB [misp]> show global variables like 'max_allowed_packet';
+--------------------+---------+
| Variable_name      | Value   |
+--------------------+---------+
| max_allowed_packet | 4194304 |
+--------------------+---------+
1 row in set (0.00 sec)

**Comment by mokaddem** [comment]
Could you try to increase the `max_allowed_packet`? 4Mb seems a bit low in my opinion, especially if you have lots of events.
If it doesn't solve your issue, we might have to dig deeper. Is it a production instance? Do you have lot of users?

**Comment by MamrK29** [comment]
Looks like the issue has been resolved. thanks
