### ISSUE TITLE
Error to insert tag in a new template

### ISSUE THREAD

**Issue by hitlp** [MISP/MISP#5826]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Windows 10
| PHP version               | 7.4.5
| MISP version / git hash   | v2.4.124, b3256c8e1ad4e71022aa19505a8c417f1a046ca5
| Browser                   | Chrome 80.0.3987.132

### Expected behavior
When creating a new model, it is allowed, through the "+" button in Tags, to add tags referring to the model being created.

### Actual behavior
When adding a new template, when clicking the "+" button in Tags, the template is created. The action of clicking the "+" button is the same as the "Create" button.

### Steps to reproduce the behavior
Event Actions, Add Template, "+" in Tags.

**Comment by mokaddem** [comment]
Thanks for the report!
