### ISSUE TITLE
Sync Issue with MISP on CentOS 7

### ISSUE THREAD

**Issue by ddurvaux** [MISP/MISP#583]
Hello,

Whenever I try to start a synchronisation with a remote MISP server, I got the following error:

stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://misp.foo.bar:443 (Unknown error) 

I search MISP logs without finding anything special.  I try to allow/disallow self-signed certificate without success.  Any idea?

Kr,

David

**Comment by iglocska** [comment]
Hello David,

If it's a self signed certificate you need to upload the certificate file.
Just go to the server connection (Sync actions -> List Servers -> edit the
server that is causing the issues) and upload it there.

Let me know if this doesn't fix it for you!

Best regards,
Andras

**Comment by ddurvaux** [comment]
Hello Andras,

Unfortunately I already did import the certificate and it's not a self-signed one :(.  It's the certificate of a well known MISP instance on which you should have access.  I'm online to give more details if I can :).

I suspect that the issue is related to PHP version.  CentOS 7 come with PHP5.3 by default.  I force upgrade to version 5.5 by using Red Hat Software Collection (https://www.softwarecollections.org/en/scls/rhscl/php55/).  I hope it will solve the issue.

Kr,

David

**Comment by ddurvaux** [comment]
I tried upgrade to PHP 5.5 and 5.6 (https://www.softwarecollections.org/en/scls/rhscl/rh-php56/).  Still no success :(

**Comment by iglocska** [comment]
Is it signed by a signing authority not included in the mozilla certificate
store? Is it the well known MISP instance that I am thinking of? :)

If so you actually need to create a certificate file containing the whole
chain and upload that!

**Comment by ddurvaux** [comment]
Seems to work now.  Thanks to @adulau.

The solution was:
1) upgrade PHP from standard PHP to PHP5.6
2) configure server without setting the option "Self Signed" and without giving any .pem file.

Point 2) was used as a temporary solution to bypass the issue with certificate validation.  It seems that it also cause issues even with PHP upgraded.

**Comment by ddurvaux** [comment]
The following article is interesting and give some hint on the issue:
http://forums.famillecollet.com/viewtopic.php?id=3107

**Comment by ddurvaux** [comment]
@iglocska It's one signed by LuxTrust CA.  Probably the one you are thinking of ;).

Actually, uploading no chain at all help :) :+1:

**Comment by iglocska** [comment]
I was thinking of a more problematic case, with them it's easy, "it just
works" :)

**Comment by ddurvaux** [comment]
as long as you use PHP5.6 ;)

**Comment by iglocska** [comment]
Wait, just to get this straight:

If you don't specify a certificate file, don't check self-signed
certificate then with PHP versions < 5.6 it fails?

**Comment by ddurvaux** [comment]
Yes.

On CentOS 7 with default PHP:
If you don't specify a certificate file & don't check self-signed -> it failed

If you upgrade to PHP5.6 -> it works.

**Comment by iglocska** [comment]
Very odd will have to check what's going on there. I just tried the same
server with Ubuntu and PHP 5.5.9 and it works fine, so not sure what's
different with the CentOS version. CakePHP automatically feeds the mozilla
CA file into the request so the issue @
http://forums.famillecollet.com/viewtopic.php?id=3107 should not happen for
MISP.

**Comment by ddurvaux** [comment]
At least, I fix my problem by updating PHP from the default version to 5.6.
Don't know if it was due to a side effect or something else.

If you want, I can send you the VM :).  I have snapshots with initial installation then upgrade of PHP.  So I can reproduce each step.

**Comment by iglocska** [comment]
Thanks, I have a Centos 7 clean VM, will just throw it on that and give it
a whirl soonish. Would be interesting to find out what combination of
things causes this. Thanks for the heads-up! :)

**Comment by ddurvaux** [comment]
And actually, offering a virtual appliance could be interested for certain organisation.  MISP INSTALL guide is well done but some steps are not that easy if the server has no direct access to the Internet (in particular all the steps where pear is used.

Some organisation are using local repository or RedHat Satellite server and the MISP server could have not Internet connection except for synchronisation with other instances.  Manually installing all the packages and their dependencies could be painful then.

**Comment by ddurvaux** [comment]
If you need help to reproduce, I would be please to help.  I recorded all my commands.  I can easily reproduce (I hope I can ;)).

**Comment by iglocska** [comment]
Thanks, I'll nudge you if I run into any issues!

As for the appliance: It's definitely something on the todo list :)

**Comment by adulau** [comment]
There is a docker app for MISP: https://github.com/eg5846/misp-docker not sure if this is still maintained but this could be a good start.

**Comment by elhoim** [comment]
Be also aware of https://github.com/MISP/MISP/issues/524 and

**Comment by Danko90** [comment]
Hi,
I had the same issue, solved by downloading and installing the client certificates in both systems (as trusted), removing them from MISP Dashboard and checking "Self Signed" box, if the certificate has been generated by yourself. Therefore, the problem seems to be still present.
