### ISSUE TITLE
List Tags Sort Order

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#5830]
2.4.121

What is the sort order when one clicks on `.../tags/index/sort:name/direction:asc`?

**Comment by mokaddem** [comment]
Not sure to get the question but I would say sort tags by name with ascending order.

**Comment by github-germ** [comment]
We are just trying to understand the sort order as it does not _appear_ to be in an intuitive order. See my screenshot please. Seems to be follow ASCII lower and then upper, but only after the first page, which include a bunch of tags before that order starts that do not follow that sort order.

![Screen Shot 2020-04-28 at 10 14 28 AM](https://user-images.githubusercontent.com/8812009/80497975-2b405900-8939-11ea-9121-749a8f95222e.png)

**Comment by github-germ** [comment]
Being that this is not a showstopper and unanswered from a year ago, I am closing the issue.
