### ISSUE TITLE
Adding attribute to event via REST API fails 

### ISSUE THREAD

**Issue by swarajd** [MISP/MISP#5831]
Hey all, I'm trying to add an attribute to an event through PyMISP, but it fails. This action succeeds through the UI, but not through PyMISP. Any idea why?

### Work environment
Questions | Answers
-- | --
Type of issue | Support
OS version (server) | Ubuntu
OS version (client) | 18.04 LTS
PHP version | 7.4
MISP version / git hash | 2.4.124

### Expected behavior

I expected the attribute to be added to the event.

### Actual behavior

the following stack trace occurs:

```
2020-04-27 21:06:45 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /attributes/add/b01dfab6-269b-46e2-92d6-837e6a0035e6
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(914): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(2216): Mysql->insertMulti()
#2 /var/www/MISP/app/Model/Attribute.php(715): Attribute->__afterSaveCorrelation()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#6 /var/www/MISP/app/Model/Attribute.php(4084): Model->save()
#7 /var/www/MISP/app/Controller/AttributesController.php(181): Attribute->captureAttribute()
#8 [internal function]: AttributesController->add()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#13 {main}
2020-04-27 21:15:51 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /attributes/add/bbbee239-50fd-4a07-9381-ac8c31e92a5b
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(914): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Attribute.php(2216): Mysql->insertMulti()
#2 /var/www/MISP/app/Model/Attribute.php(715): Attribute->__afterSaveCorrelation()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#6 /var/www/MISP/app/Model/Attribute.php(4084): Model->save()
#7 /var/www/MISP/app/Controller/AttributesController.php(181): Attribute->captureAttribute()
#8 [internal function]: AttributesController->add()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#13 {main}
```

I checked the database itself and the attribute table DOES have auto-increment turned on and it's set to a value that is larger than the largest ID in that table. Any idea as to what is going on?

**Comment by mokaddem** [comment]
Could you paste the query or the PyMISP code?
Thanks!

**Comment by swarajd** [comment]
To boil it down the query looks like this:

```
misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, cert=<REDACTED>, proxies=proxies)
event = MISPEvent()
new_event = misp.add_event(event)

attributes = []
for domain in domains:
    attribute = {'type': 'domain', 'value': domain, 'category': 'Network activity', 'to_ids': True, 'comment': 'Source: <REDACTED>'}
    attributes.append(attribute)

misp.add_attribute(new_event, attributes)

```

**Comment by swarajd** [comment]
One more detail I can provide is that the code fails when it tries to add an attribute that already exists.

**Comment by swarajd** [comment]
Also the `attributes` table itself doesn't have an item that has ID "0"

**Comment by mokaddem** [comment]
The only issue I notice with your script is that you cannot create an event without the info field.
Also, it's by design that MISP rejects a query that tries to duplicate an attribute inside the same event.
And AFAIK, IDs in the database start at 0.
Could you provide more insight on how to reproduce your issue? A REST query would be ideal but a complete python script would work too.
Thanks in advance!

**Comment by swarajd** [comment]
Hey @mokaddem, I DMed you a more complete script on gitter, and as for the duplicate attribute the attribute isn't actually duplicated in the same event, but the URL of the attribute exists on another event. Another detail I can add is that adding an attribute with a URL that already exists just in general fails both through PyMISP and through the UI. For example:

If I have event `1234` with an attribute with url `abc.com`, and I try to add an attribute with url `abc.com` to event `2345`, then it will throw the exact same internal error as the original post through both PyMISP and the UI.

**Comment by iglocska** [comment]
The issue seems to be coming from your correlations table. Could you do a `describe correlations;` and paste the results via the mysql CLI?

**Comment by iglocska** [comment]
Specifically my worry is that your `id` field is missing the auto_increment flag.

**Comment by swarajd** [comment]
That was it! Thank you so much for the help!
