### ISSUE TITLE
update MISP

### ISSUE THREAD

**Issue by HugoP87** [MISP/MISP#5839]
Hello,

When I try to update from Server Settings > Diagnostics, I get the following message:
Currently installed version… (d2ed0c89566c9e6f6adf8789377ecdb8b73ed40a)
Versão mais recente disponível… ()
Status… Não foi possível recuperar a versão do github
Current branch… You are not on a branch, Update MISP will fail 

and

cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

fatal: unable to access 'https://github.com/MISP/MISP.git/': Failed to connect to github.com port 443: Connection timed out

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

my OS :

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

I don't know what can I do. Thank you for your help!

## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by mokaddem** [comment]
Hello,
Could you make sure that the server on which MISP is installed has access can actually connect to Github?
Because it seems to be the root cause of the issue:
```
fatal: unable to access 'https://github.com/MISP/MISP.git/': Failed to connect to github.com port 443: Connection timed out
```
Thanks!

**Comment by HugoP87** [comment]
Hello, 
yes, I know.... 

I put it as proxy information through the interface, and in addition, I did the test, allowed to access the page. The wget works without problems.
This page also follows https://misp.github.io/MISP/UPDATE/, but it looks like it got worse. I don't know what else to try. Can you help me? thanks

**Comment by mokaddem** [comment]
Throwing some ideas:
- I see `Current branch… You are not on a branch, Update MISP will fail` Can you switch back to `2.4`
- Could you try the solution described here: https://github.com/MISP/MISP/issues/5192
- If you updated via the command line, please make sure that your files still have the correct permissions

**Comment by HugoP87** [comment]
Thank you, the solution un #5192 solved my problem.
