### ISSUE TITLE
Parse semicolon separated values in the freetext import import tool

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#584]
For example in [this report](http://www.slideshare.net/CrowdStrike/crowd-casts-monthly-you-have-an-adversary-problem), there are some small lists of IOCs like:
```
fbi.sexxxy.biz; u1.FartIT.com; jj.mysecondarydns.com; 54.241.13.219; 184.169.176.71; 114.80.96.8
```
When I paste it in the freetext import tool, only the last IP is proposed as an attribute to add.

My ideal scenario would be to have all the listed values parsed.

**Comment by Rafiot** [comment]
Works.
