### ISSUE TITLE
Potential fresh install fail

### ISSUE THREAD

**Issue by pankajdhankar** [MISP/MISP#5844]
Hi ,

I have installed fresh MISP instance on Ubuntu 18.04 by using below script but while trying to access via web it fails.

This will install MISP Core and misp-modules # $ wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M. 

Please suggest

**Comment by mokaddem** [comment]
Could you be more specific on what fails?
Did the installation succeeded?
Is apache running and serving the correct application?
Do you have any log entries that we could use?
Thanks

**Comment by Rickozono** [comment]
I'm having the same issue, this is the content I have in misp.local_error.log.
How do I solve it?
Thanks you for any help

[Tue May 05 12:40:08.110424 2020] [php7:warn] [pid 73991] [client 127.0.0.1:44874] PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www>
[Tue May 05 12:40:08.110463 2020] [php7:error] [pid 73991] [client 127.0.0.1:44874] PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/>
[Tue May 05 12:46:28.094829 2020] [php7:warn] [pid 74003] [client 127.0.0.1:44882] PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www>
[Tue May 05 12:46:28.094867 2020] [php7:error] [pid 74003] [client 127.0.0.1:44882] PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/>
[Tue May 05 12:47:44.215379 2020] [ssl:warn] [pid 596] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:47:45.003007 2020] [ssl:warn] [pid 620] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:49:42.249806 2020] [php7:warn] [pid 642] [client 127.0.0.1:36008] PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/M>
[Tue May 05 12:49:42.249866 2020] [php7:error] [pid 642] [client 127.0.0.1:36008] PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/ph>
[Tue May 05 12:53:46.859169 2020] [php7:warn] [pid 640] [client 127.0.0.1:36012] PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/M>
[Tue May 05 12:53:46.859204 2020] [php7:error] [pid 640] [client 127.0.0.1:36012] PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/ph>
[Tue May 05 12:58:00.560693 2020] [ssl:warn] [pid 5113] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:58:00.589040 2020] [ssl:warn] [pid 5114] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:59:15.553900 2020] [ssl:warn] [pid 9015] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 12:59:15.589725 2020] [ssl:warn] [pid 9016] AH01906: misp.local:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue May 05 13:00:19.560433 2020] [php7:warn] [pid 9054] [client 127.0.0.1:36174] PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/>
[Tue May 05 13:00:19.560498 2020] [php7:error] [pid 9054] [client 127.0.0.1:36174] PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='.:/usr/share/p>

**Comment by SteveClement** [comment]
@Rickozono what OS are you using?

It says that the file "/var/www/MISP/app/Vendor/autoload.php" does not exist.
Does it exist?
If yes, you have a permission problem.

This is not an installer issue per se.

**Comment by Rickozono** [comment]
@SteveClement thanks for your answer.
I'm using kali linux 2020.
I checked the path, but I don't have the "Vendor" folder in /var/www/MISP/app/.
Do you know how to solve this? This is the content I have in that path
![path](https://user-images.githubusercontent.com/51711170/81297195-4bfb6380-9049-11ea-9a81-8f5d9c6fb739.jpg)

**Comment by SteveClement** [comment]
Ah, Kali, ok, now we are talking.

Kali 2020 is not yet supported, I still need to fix it.

**Comment by SteveClement** [comment]
Fixed: https://github.com/MISP/MISP/pull/5913
