### ISSUE TITLE
Passwords starting with "." cause error

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#585]
Hi,

When you change the password (tested with various pw-lengths) of a user to a password starting with a dot "."  I get the message "Password complexity requirement not met.".

kr,

koen

**Comment by elhoim** [comment]
@cudeso  Solved?

**Comment by Rafiot** [comment]
Just tested, not solved.

I think it is because the default regex should look like that: 

``` patch
< /(?=.*[0-9])(?=.*[!@#$%^&*_-])(?=.*[A-Z])(?=.*[a-z]).*$/
> /(?=.*[0-9])(?=.*[!@#$%^&*_-.])(?=.*[A-Z])(?=.*[a-z]).*$/
```
