### ISSUE TITLE
DB diagnostic doesn't support `AUTO_INCREMENT`

### ISSUE THREAD

**Issue by mokaddem** [MISP/MISP#5860]
Add support of `AUTO_INCREMENT` in the `db_diagnostic` tool.
And in general, add support for all `Extra` in the mysql schema.

**Comment by swarajd** [comment]
I noticed this too, when we updated MISP from v2.4.116 to v2.4.124 the diagnostic tool told us to run this command:

![image](https://user-images.githubusercontent.com/1250084/81106019-e2614500-8ee2-11ea-9336-f475e8f145a2.png)

it didn't include the auto_increment tag and caused this issue: https://github.com/MISP/MISP/issues/5831

**Comment by mokaddem** [comment]
Oh that explains the issue indeed. Do you have any ideas on how you ended-up having a modified correlations table? Did you do some manual changes yourself?

**Comment by swarajd** [comment]
We had MISP running with v2.4.116 and I guess the schema for that differed a little bit from v.2.4.124. Either that or what could have happened was when we dumped the DB from the RDS instance and restored it to another RDS instance the `auto_increment` details, among other details, could have not been carried over. I don't know with full confidence what the exact reason is but these two reasons could be it.
