### ISSUE TITLE
Attachments Marked as Malware Sample fail to Upload

### ISSUE THREAD

**Issue by Hestat** [MISP/MISP#5864]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.4 LTS
| OS version (client)       | Win10, Ubuntu
| PHP version               | PHP 7.2.24
| MISP version / git hash   | v2.4.125 (690f2adf07f9148b13815bd61c4082d3e0612663)
| Browser                   | Chrome and Firefox

### Expected behavior
Uploads marked as malware samples upload successfully

### Actual behavior
Uploads not marked as malware samples upload successfully, but if the malware sample box is checked to following error occurs (see below). These uploads were occurring successfully prior to the most recent version.

### Steps to reproduce the behavior
Update to most recent version and try to upload a file marked as malware.

This has occurred on 2 MISP instances administer.

### Logs, screenshots, configuration dump, ...

```
2020-05-05 11:48:50 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'captureObject' at line 1
Request URL: /attributes/add_attachment/30430
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('captureObject', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('captureObject', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(648): DboSource->fetchAll('captureObject', Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(834): DboSource->query('captureObject', Array, Object(AppModel))
#5 /var/www/MISP/app/Controller/AttributesController.php(482): Model->__call('captureObject', Array)
#6 [internal function]: AttributesController->add_attachment('30430')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by patriziotufarolo** [comment]
Same problem happened to me. I'm looking into it.

Seems to be related to commit a1810a313c2bd2ae0ac4fcc1af7f601dc6f0bd52 by @iglocska 

More precisely I reverted the changes at lines 470, 479 and 483, and now seems to work fine again; for some reason with the changes made by Andras it fails to build the SQL query

**Comment by patriziotufarolo** [comment]
Seems that MispObject is not initialized in Attribute model, adding ClassRegistry::init("MispObject") in Attribute model's construct seems to fix the problem as well, but I think it would be heavier than the old approach

**Comment by mokaddem** [comment]
@patriziotufarolo Thanks for the analysis!
Indeed the commit from @iglocska cleaned a bit but it's not the root cause of the issue.
The bug comes from the fact that `mispObject` class was not loaded in the controller but was wrongly loaded in the Attribute's model, thus overriding the non-initialized link with the Object's model.
Calling `ClassRegistry::init` does nothing if the class is already loaded so in that case, it's not heavier.
Anyway, it should be fixed now. ;)
Thanks!

**Comment by patriziotufarolo** [comment]
> 
> 
> @patriziotufarolo Thanks for the analysis!
> Indeed the commit from @iglocska cleaned a bit but it's not the root cause of the issue.
> The bug comes from the fact that `mispObject` class was not loaded in the controller but was wrongly loaded in the Attribute's model, thus overriding the non-initialized link with the Object's model.
> Calling `ClassRegistry::init` does nothing if the class is already loaded so in that case, it's not heavier.
> Anyway, it should be fixed now. ;)
> Thanks!

You are welcome :) I'm not so good with CakePHP, I try to do my best :P For this reason I didn't submit a PR. 
Thank you for fixing it!
