### ISSUE TITLE
Question about RESTful search

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#5867]
Hello! I have question about RESTful search. When I use RESTful making requests something like that "https://<misp>/attributes/restSearch/json/type:ip-dst/" I receive duplicates of attributes (same attributes in different events). Is any way to work with duplicates in RESTful search? Can I request only duplicates or only attributes that haven't duplicates?
P.S. One more question appeared. I can use "include_correlations" in pymisp like so "misp.search(controller='attributes',type_attribute='ip-dst',include_correlations=1)". Is it possible to do same in RESTful search?

**Comment by mokaddem** [comment]
Hello!
Indeed, duplicate attributes are normal and needed if you want to have correlations.
What you consider as an duplicate attribute depends on the event you are referring to. If you wish to get all 'duplicate' attribute as the one in event X, you can do it in different ways:
#### Negate the event from which you want to see correlating attributes
```
/attributes/restSearch
{
    "returnFormat": "json",
    "value": "your_attribute_value",
    "eventid": "!x"
}
```

#### Use the `includeCorrelations` parameter that attach correlations to the attribute
```
{
    "returnFormat": "json",
    "value": "your_attribute_value",
    "includeCorrelations": 1
}
```

Do not hesitate if you have more questions
