### ISSUE TITLE
Download by hash - support SHA1/SHA256

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#587]
Related to https://github.com/MISP/MISP/commit/5273c2c5aa625a84314f981fe28d430a7ca6df9f

Some places/data sources only have sha1 or sha256, but no md5 available.

**Comment by iglocska** [comment]
Never with samples in MISP, each sample will have an MD5. This feature allows you to pass an MD5 hash to MISP and receive the associated sample

**Comment by elhoim** [comment]
Yep, but if a user only knows the SHA1 of a sample that is potentially stored in MISP, then he has no way of trying to find it.

**Comment by iglocska** [comment]
Indeed, but MISP does not directly bundle sha1s with the samples - at least
not until we move to the new datamodel that will allow file objects with
several attributes.

For now what a user can do is pass a sha1 along with the download by hash
feature and tell it to grab all samples from the event.

**Comment by elhoim** [comment]
But when samples are uploaded via the web interface, they get autogenerated filename|sha1, filename|sha256 and filename|md5; I don't know if the sample upload API call generates those or not.

**Comment by iglocska** [comment]
That is true, but you can also create filename|sha1s yourself.

We can try to be smart about it an resolve it, but we might run into cases
where you don't get what you expect:

For example you add two malware samples with the same filename to the same
event then you'll end up with two filename|sha1s and filename|sha256s and
no direct relation to the actual sample. Maybe a solution would be to throw
an error message if the lookup is inconclusive?

**Comment by elhoim** [comment]
My bad, I did not read the full code, only the beginning and the first comment mentioning "download by md5". While the code has been doing all along what I was pushing for: being able to lookup by md5 or sha1 or sha256. :)

Once again, you did the perfect thing from the start.

**Comment by iglocska** [comment]
Hehe it's far from perfect, you can look up every sample in an event since
it cannot be sure that it finds the right one. Another one of those "the
new datamodel will fix it" issues :)
