### ISSUE TITLE
[Exception] Class Redis doesn't exists

### ISSUE THREAD

**Issue by er587** [MISP/MISP#5872]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  RedHat
| OS version (client)       | MacOS
| PHP version               | 7.2
| MISP version / git hash   | MISP 2.4.125 
| Browser                   | If applicable

New install following these steps outline in https://misp.github.io/MISP/INSTALL.rhel7/ 

I'm having a problem with updating Feeds. If I click on the "fetch All Feeds", the job fails with the error below.  If I view the "Explore Feed Remotely", the select on the indicator, and Fetch Selected, the job pulls in one event into the fixed event as the feed. Then, I go back to the same feed, select "fetch All Feeds", it works. 

Errors in the log.  You can see the Job Failed, then Job done, Job done.

[Exception] Class Redis doesn't exists.
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(250): AppModel->setupRedisWithException()
#1 /var/www/MISP/app/Model/Feed.php(842): Feed->getFreetextFeed(Array, Object(HttpSocket), 'csv', 'all')
#2 /var/www/MISP/app/Console/Command/ServerShell.php(209): Feed->downloadFromFeedInitiator('3', Array, '1443')
#3 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#9 {main}
Job failed.
Job done.
Job done.

The default Feeds "CIRCL OSINT Feed" & "The Botvrij.eu Data" work flawlessly. Any new feeds work with the above behavior.

**Comment by JakubOnderka** [comment]
Can you please check if Redis PHP extensions is correctly installed? You can check it at Diagnostic page under *PHP Extensions* heading.

**Comment by er587** [comment]
Diag page shows:
Web
redis:… OK
gd:… OK
ssdeep:… OK

Cli
redis:… Not loaded
gd:… OK
ssdeep:… Not loaded


cat /etc/opt/rh/rh-php72/php-fpm.d/www.conf | grep redis
env[PATH] = /opt/rh/rh-git218/root/usr/bin:/opt/rh/rh-redis32/root/usr/bin:/opt/rh/rh-php72/root/usr/bin:/usr/local/bin:/usr/bin:/bin

**Comment by er587** [comment]
This issue was due to permissions in the install guide. 

-rw-r-----.  1 root root   19 May  4 19:06 99-gnupg.ini
-rw-r-----.  1 root root   19 May  4 19:05 99-redis.ini
-rw-r-----.  1 root root   20 May  4 19:06 99-ssdeep.ini 

The Fix was to apply read permissions. 
sudo chmod o+r /etc/opt/rh/rh-php72/php.d/99*

**Comment by er587** [comment]
Fixing the redis path and permissions did not fix the issue.

**Comment by RichieB2B** [comment]
Your system probably has an umask of 027 for root. A situation the install guide does not account for. 

Did you restart `rh-php72` and the MISP workers?

**Comment by er587** [comment]
Restarting the rh-php72 and the MISP workers fixed the issue. I'll add this issue to the install guide notes for the maintainer.
