### ISSUE TITLE
Install Script don't work completly

### ISSUE THREAD

**Issue by obstgit** [MISP/MISP#5873]
Hey, 
i'm trying to isntall a new MISP Instance.
At the very end of the installation there is a error while doint stuff with python.
I'm not sure if i can use the installation.
I also remember that the Installer asks for a FQDN, this time it doesn't and the field at the final output is empty?
Thank you in advance.

### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Freshly installed Ubuntu 18.4-4

### Logs, screenshots, configuration dump, ...
```
Successfully built validators
Installing collected packages: soupsieve, beautifulsoup4, pillow, reportlab, decorator, validators, pymisp
  Attempting uninstall: pymisp
    Found existing installation: pymisp 2.4.125
    Uninstalling pymisp-2.4.125:
      Successfully uninstalled pymisp-2.4.125
  Running setup.py develop for pymisp
Successfully installed beautifulsoup4-4.9.0 decorator-4.4.2 pillow-7.1.2 pymisp reportlab-3.5.42 soupsieve-2.0 validators-0.14.3
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 40, in <module>
    from keys import url, key  # type: ignore
  File "/var/www/MISP/PyMISP/tests/keys.py", line 2
    key = "cnX4uEasfNw5BonF3wHWQIVX0E6sqg7kWVnr7Ri1"
                                                   ^
SyntaxError: EOF while scanning triple-quoted string literal
#########################################################################################  (88%)
-----------------------------------------------------------------------------------------------------
Admin (root) DB Password: ....
```

**Comment by obstgit** [comment]
I did the same install steps in a virtual machine on my notebook using virtual box. Interestingly there the installation works better (no python errors, just 2 test failures).
The only differences between my local machine and the remote machine (on ESXi) is that the remote machine has a fixed IP.

**Comment by SteveClement** [comment]
Yeah, weird indeed. The only thing I can tell you is that this has no impact on your install.

So no worries.

**Comment by obstgit** [comment]
The file key.py looks like this (im using VMWare):
url = """"
key = "WjMxA2PtSm1f8Kk1ipjj3cb64ud4a7Bs8RUpWHYd"

I think the four quotes are the problem here.
