### ISSUE TITLE
MISP volume keeps expanding

### ISSUE THREAD

**Issue by JoachimDP6** [MISP/MISP#5874]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian 9 (stretch)
| MISP version    | 2.4.122
| Implementation | Docker

### Support Questions
I'm fairly new to MISP. I created a MISP instance where I collect all my feeds (at the moment I just enabled some feeds from the Feed List for testing). I created 2 different MISP instances on other servers and I connected them through a sharing server (and sync user) to share the feeds. This all worked but since I added the second sharing server, my original MISP instance, where I collect the feeds, keeps on growing even though I'm not pulling, pushing, or creating any events. It's at a rate of 10MB/min.

This behavior stopped after restarting the server (had to, to increase my partition).

Can someone help me by explaining why this happens and how I can prevent it?

Many thanks!

**Comment by iglocska** [comment]
Without additional feed pulls I have no idea how that happened. Can you check the sizes of your MISP tables or if it's something else that blew up in size, figure out what's actually growing?
