### ISSUE TITLE
Can't add object to existing event

### ISSUE THREAD

**Issue by JDPey** [MISP/MISP#5875]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| MISP version / git hash   | 2.4.122

### Code
`
```python
def create_misp_object(self, log_object):
        endpoint = '/objects/add/'
        relative_path = str(1356)

        body = {
            "name": "ip-port",
            "meta-category": "network",
            "description": "log that triggered x",
            "template_uuid": "9f8cea74-16fe-4968-a2b4-026676949ac6",
            "event_id": str(1356),
            "timestamp": "1558702173",
            "distribution": "0",
            "sharing_group_id": "0",
            "comment": "",
            "deleted": False,
            "ObjectReference": [],
            "Attribute": [
                {
                    "type": "ip-src",
                    "category": "Network activity",
                    "to_ids": False,
                    "event_id": str(1356),
                    "distribution": "0",
                    "timestamp": "1558702173",
                    "comment": "",
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_relation": "post",
                    "value": str(log_object["src"]),
                    "Galaxy": [],
                    "ShadowAttribute": []
                }
            ]
        }

        res = self.misp.direct_call(endpoint + relative_path, body)`

```

### Support Questions
I try to add an object containing one attribute (the ip-src) to a specific event. The code above is a function of my python script where I use PyMISP. I can add attributes so connecting to my MISP instance isn't the problem. However, I keep receiving the following error when I try to add an object:

### Error
DEBUG [api.py:2221 - _prepare_request() ] POST - https://cti.ey-cyber.be/objects/add/1356
DEBUG [api.py:2223 - _prepare_request() ] {"name": "ip-port", "meta-category": "network", "description": "log that triggered x", "template_uuid": "9f8cea74-16fe-4968-a2b4-02                                                                                                                                6676949ac6", "event_id": "1356", "timestamp": "1558702173", "distribution": "0", "sharing_group_id": "0", "comment": "", "deleted": false, "ObjectReference": [], "Attribute"                                                                                                                                : [{"type": "ip-src", "category": "Network activity", "to_ids": false, "event_id": "1356", "distribution": "0", "timestamp": "1558702173", "comment": "", "sharing_group_id":                                                                                                                                 "0", "deleted": false, "disable_correlation": false, "object_relation": "post", "value": "10.225.30.1", "Galaxy": [], "ShadowAttribute": []}]}
DEBUG [api.py:2242 - _prepare_request() ] {'User-Agent': 'PyMISP 2.4.122 - Python 3.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep                                                                                                                                -alive', 'Content-Length': '620', 'Authorization': '***************************************', 'content-type': 'application/json'}
ERROR [api.py:2178 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Object', 'message': 'Could not add Object', 'url': '/objects/add                                                                                                                                ', 'errors': 'Object could not be saved.\n'}

**Comment by Rafiot** [comment]
`"value": str(log_object["src"])` is not a valid IP address.

**Comment by JDPey** [comment]
yes I think so. In my error you can see that the value is IP "10.255.30.1"

**Comment by Rafiot** [comment]
sorry, I totally misread your message. I updated it so it is a python block

**Comment by Rafiot** [comment]
There are many things that could go wrong there, and most of the parameters you have in your python dict are not needed. Also `"object_relation": "post",` is incorrect. I guess you meant port, and you're posting an IP.


I'd recommend to do the following:

``` python
def create_misp_object(self, log_object):
    obj = MISPObject('ip-port')
    obj.add_attribute('ip', value=log_object["src"])
    misp.add_object(1356, obj)
```

I didn't test the code, but that should mostly work.

**Comment by JDPey** [comment]
it worked! thanks a lot!!

**Comment by Rafiot** [comment]
\o/
