### ISSUE TITLE
IPv6 CIDR correlations incorrect

### ISSUE THREAD

**Issue by ivocarv** [MISP/MISP#5877]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | N/A
| PHP version               | 7.2 
| MISP version / git hash   | 2.4.125 (be946bf09baf3d2543596bb1586d3e2d72e6c2c5)
| Browser                   | N/A

### Expected behavior
MISP should correlate IPv6 /32 networks with the corresponding hosts

### Actual behavior
MISP correlates hosts with different networks

### Steps to reproduce the behavior
1. Enable advanced correlations
2. Create a event with a IPv6 host  (Ex: 2804:14d:1491:90b0:c4f4:b73e:f86c:a653)
3. Create a 2nd event with a CIDR /32 network (Ex: 2804:5330::/32)

### Logs, screenshots, configuration dump, ...

see comment below

**Comment by ivocarv** [comment]
The problem is on this part of app/Model/Attribute.php. function __inet_to_bits should receive a in_addr (network order binary format) of the IPv6 address, instead of human representation. The original code on stackoverflow uses "inet_pton" to do this. Quick fix would be change __expandIPv6Notation to inet_pton, but not sure about performance issues:

```
// using Snifff's solution from http://stackoverflow.com/questions/7951061/matching-ipv6-address-to-a-cidr-subnet
    private function __ipv6InCidr($ip, $cidr)
    {
HERE>        $ip = $this->__expandIPv6Notation($ip);
        $binaryip = $this->__inet_to_bits($ip);
        list($net, $maskbits) = explode('/', $cidr);
HERE>        $net = $this->__expandIPv6Notation($net);
        if (substr($net, -1) == ':') {
            $net .= '0';
        }
        $binarynet = $this->__inet_to_bits($net);
        $ip_net_bits = substr($binaryip, 0, $maskbits);
        $net_bits = substr($binarynet, 0, $maskbits);
        return ($ip_net_bits === $net_bits);
    }

    private function __expandIPv6Notation($ip)
    {
        if (strpos($ip, '::') !== false) {
            $ip = str_replace('::', str_repeat(':0', 8 - substr_count($ip, ':')).':', $ip);
        }
        if (strpos($ip, ':') === 0) {
            $ip = '0'.$ip;
        }
        return $ip;
    }

    private function __inet_to_bits($inet)
    {
        $unpacked = unpack('A16', $inet);
        $unpacked = str_split($unpacked[1]);
        $binaryip = '';
        foreach ($unpacked as $char) {
            $binaryip .= str_pad(decbin(ord($char)), 8, '0', STR_PAD_LEFT);
        }
        return $binaryip;
    }
```

**Comment by iglocska** [comment]
Nice catch, thanks!

**Comment by ivocarv** [comment]
Here is a patch suggestion: 
```

--- Attribute_orig.php  2020-05-08 14:54:04.491241847 -0300
+++ Attribute.php       2020-05-08 16:16:45.243452301 -0300
@@ -1914,15 +1914,18 @@
     }

     // using Snifff's solution from http://stackoverflow.com/questions/7951061/matching-ipv6-address-to-a-cidr-subnet
+    // Patch by peixinho.icp
     private function __ipv6InCidr($ip, $cidr)
     {
         $ip = $this->__expandIPv6Notation($ip);
+        $ip=inet_pton($ip); // addded by peixinho.icp
         $binaryip = $this->__inet_to_bits($ip);
         list($net, $maskbits) = explode('/', $cidr);
         $net = $this->__expandIPv6Notation($net);
         if (substr($net, -1) == ':') {
             $net .= '0';
         }
+        $net=inet_pton($net); // added by peixinho.icp
         $binarynet = $this->__inet_to_bits($net);
         $ip_net_bits = substr($binaryip, 0, $maskbits);
         $net_bits = substr($binarynet, 0, $maskbits);
```

**Comment by JakubOnderka** [comment]
I will send PR that refactor CIDR correlations, there is more problems with current implementation.

**Comment by ivocarv** [comment]
I applied the patch above on a test MISP and it worked. The problem now is force MISP to redo the correlations. My production server has a lot of wrong IPv6 correlations

**Comment by JakubOnderka** [comment]
> I applied the patch above on a test MISP and it worked. The problem now is force MISP to redo the correlations. My production server has a lot of wrong IPv6 correlations

You can try to check `Server Settings & Maintenance` -> `Diagnostics` -> `Legacy Administrative Tools` and click `Recorrelate attributes`. 

I just check this function on my instance and it works.
