### ISSUE TITLE
Pusblish event without sending email alert

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5878]
I have this script that pull a feed from one of our 3rd party vendor. In the script I have a call to publish the event, without sending an alert email. According to pymisp this call is supposed to suppress the alert emails. But for some reason, emails are still being generated. 

# Lastly, publish the event without sending an alert email.
    # This command expects the event ID instead of a MISPevent as argument.
    misp_instance.publish(event['id'], alert=False)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |RHEL, with MISP running on a docker container..
| OS version (client)       | MacOS, Win10, 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior
event published without email alerts

### Actual behavior
event is published, mail is sent out by MISP

### Steps to reproduce the behavior
python3 PySight.py

**Comment by dmolina213** [comment]
If i can add. I enabled a custom feed via the GUI. everytime it pulls the feeds it automatically publishes the events and send out an email. How do i configure it such that it publishes but does not send an email?

**Comment by dmolina213** [comment]
Where in MISP does the attribute to send an email alert is set when an event from a feed is published?

**Comment by dmolina213** [comment]
anyone, anyone?

**Comment by mokaddem** [comment]
Hey,
```
# This command expects the event ID instead of a MISPevent as argument.
misp_instance.publish(event['id'], alert=False)
```
This is correct. You should provide an ID and putting alert to False will push the event without sending emails.
Also, when feeds are published, they should not send emails. Are you sure you are receiving the mail from the instance that pulled the feed and not from a connected instance?

**Comment by dmolina213** [comment]
We are actually getting spammed with email. Something to do with how the fireeye scripts are written. Scripts can be viewed here : https://github.com/jaegeral/PySight2MISP.  I have actually developed a work around by disabling emailing and disabling all email workers prior to manually running the python3 script from the CL. At the end I go into the MySQL database and delete the email jobs on the jobs table.  Very cumbersome and not good if you want to use a cron job to automate.

**Comment by mokaddem** [comment]
That indeed seems not practicable.
However, from what I can see, the script you mentioned is publishing with the correct parameters. Do you still have the issue?
