### ISSUE TITLE
FAIL: bad GnuPG.*

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#588]
Hi all, 

Just updated my MISP instance to v2.3.106  but now I get the following error
"
 GnuPG
This tool tests whether your GnuPG is set up correctly or not.
GnuPG installation and settings....FAIL: bad GnuPG.*	
"

Any idea?

Thanks in advance,
Andreas

**Comment by iglocska** [comment]
It sounds like a permission issue, could you check if your apache user has access to the gnupg directory?

**Comment by advancedeng** [comment]
Yeap, absolutely right. It was just an access problem to the gnupg directory.

Cheers,
Andreas

**Comment by iglocska** [comment]
Excellent, thanks for the heads-up! :)
