### ISSUE TITLE
Misp-modules could not be executed and failed

### ISSUE THREAD

**Issue by easrml** [MISP/MISP#5881]
Hi guys, I installed misp on a Centos 7 server, but when I try to restart Apache it shows me a message in the journal stating the error below, could you help me please?

#### Error journal with restart apache service

May 08 16:10:28 centos-server systemd[31799]: Failed at step EXEC spawning /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s: No such fi

#### Error when I run on manually

[root@centos-server ~]# /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s
Unable to import URLObject, pyfaup missing
2020-05-08 16:10:57,801 - misp-modules - INFO - Launch MISP modules server from package.
INFO:misp-modules:Launch MISP modules server from package.
2020-05-08 16:10:57,806 - misp-modules - INFO - Helper loaded cache
INFO:misp-modules:Helper loaded cache
2020-05-08 16:10:57,806 - misp-modules - INFO - Unable to load MISP modules from package.
INFO:misp-modules:Unable to load MISP modules from package.
[root@centos-server ~]#

**Comment by er587** [comment]
I had the same problem with a recent RedHat 7 build. I resolved the issue by installing faup manually in the MISP enviornment.

**Comment by easrml** [comment]
Hi @er587, could you give me more details about a faup installation manual? Tk u for your help.

**Comment by er587** [comment]
My install is on RHEL 7 

From my history file, this is what I have noted:

working dir - /usr/local/src/misp-modules/
sudo git clone https://github.com/stricaud/faup.git
cd faup/
sudo cmake3
sudo make
sudo make install
cd src/lib/bindings/python/
$SUDO_WWW $PATH_TO_MISP/venv/bin/pip install -U .

**Comment by Rafiot** [comment]
Partially related, but PyFaup has an issue right now: https://github.com/MISP/misp-modules/issues/398

**Comment by easrml** [comment]
> From my history file, this is what I have noted:

Tk u, I will try... :)
