### ISSUE TITLE
Error configuring SightingDB connection

### ISSUE THREAD

**Issue by clopmz** [MISP/MISP#5887]
Hi all,

 MISP release: 2.4.125
 OS: RHEL 8.2
 
When I try to configure SightingDB connection, the following error appears in web console:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

 Under /var/www/MISP/app/tmp/logs/error.log, the following messages appears:

root@stonehaven:/var/www/MISP/app/tmp/logs# cat error.log
2020-05-11 07:39:05 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'timestamp' doesn't have a default value
Request URL: /sightingdb/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Sightingdb), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/SightingdbController.php(31): Model->save(Array)
#6 [internal function]: SightingdbController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(SightingdbController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SightingdbController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by mokaddem** [comment]
Hey, thanks for the report.
It should be fixed now. If it isn't please get in touch again!
