### ISSUE TITLE
malware sample added to GFI sandbox submission leads to  "An Internal Error Has Occurred"

### ISSUE THREAD

**Issue by nicolasvillatte** [MISP/MISP#589]
Action: Add Event > GFI Sandbox > Add
Error message:	

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

**Comment by iglocska** [comment]
What were you trying to upload? For the GFI Sandbox event creation, you
need to add the archive that you export from GFI, not just the xml report.
Do you still get that error message?

**Comment by nicolasvillatte** [comment]
Ok thank you problem solved.

**Comment by iglocska** [comment]
Excellent, let me know if you run into any other issues!
