### ISSUE TITLE
Search for events or attributes containing + character is not working

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#5890]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 19.04
| OS version (client)       | Win10
| PHP version               | 7.2
| MISP version / git hash   |  v2.4.125 (43d95e22125279409e314f06f1102c0fc07f86c9)

### Expected behavior
Gettings results for events where the eventinfo or if an attribute contains + character.

### Actual behavior
Does not return results.

### Steps to reproduce the behavior
Case 1 (for eventinfo in an event):

1. Create a misp event with `testString1 + testString2` for the eventinfo.
1. Search for `testString1 + testString2` in the event index search builder.
You don't get any results, but if you search just for `testString1` or `testString2,` you get a result.

Steps to fix it: edit the URL to replace the `+` with `%2b` (it's quoted hex value), and it works.

Case 2 (for the value of an attribute):

1. Create a misp event with an attribute value of `testString1 + testString2`, attribute type does not matter (as long as it can have a string with spaces and a + in it).
1. Go to the event, in the quick full-text search search for `testString1 + testString2`.
You don't get any results, but if you search just for `testString1` or `testString2,` you get a result.

I have the impression it is due to the + character not being escaped somewhere, but I am not sure where.

**Comment by mokaddem** [comment]
Thanks for the report.
Indeed, it was not possible to search for values containing `+`.
Now it's fixed.
