### ISSUE TITLE
Multiple Private Taxonomies

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#5893]
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.124 (c3fd409d7d145e2bb583fcf3f3f9c95cbe492014) 

Is it possible to have 2 private taxonomies? From what I can tell this is not possible since you can only have one machinetag.json under /var/www/MISP/app/files/taxonomies/privatetaxonomy. Ref: https://www.circl.lu/doc/misp/taxonomy/#adding-a-private-taxonomy

**Comment by mokaddem** [comment]
`privatetaxonomy` is actually the name of the private taxonomy.
So in your case, you could have:
```
/var/www/MISP/app/files/taxonomies/privatetaxonomy/machinetag.json 
/var/www/MISP/app/files/taxonomies/privatetaxonomy2/machinetag.json 
```
