### ISSUE TITLE
Allow disabling correlation setting not taken into account

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#5898]
Running MISP 2.4.124

Despite having the setting MISP.allow_disabling_correlation set to True. When a user attempts to untick the correlation box, he gets an error. I can see in the logs :
[MethodNotAllowedException] Disabling the correlation is not allowed on this instance
/attributes/toggleCorrelation(...) 

I'm willing to work on the resolution of this bug and to submit a PR. Hence creating this issue for tracking purposes.

**Comment by iglocska** [comment]
Nice catch, looking forward to the PR!
