### ISSUE TITLE
Filter event replication and black-list of UUIDs

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#590]
It happens quite often that you might have events on a specific instance that you don't want any more.

If the contributor delete the events and the events is already synchronised on other MISP, you'll get back the event.

It would be nice to be able to control or black-list UUIDs. Like delete and black-list the UUIDs for a specific event.

**Comment by iglocska** [comment]
Makes sense. Is this something that you want to be able to manage, (lift the restriction for example) or is a simple "if I delete it it gets blacklisted" enough?

**Comment by adulau** [comment]
Managing the list of UUID would be great especially when you want to lift the restriction for some specific events or delay an import.

**Comment by elhoim** [comment]
Is this fully covered by https://github.com/MISP/MISP/commit/a93807439d987543aa4f1b5e1d5479f6e0c83b55 ?

**Comment by iglocska** [comment]
This is indeed implemented.
