### ISSUE TITLE
Freetext import results "similar attributes" for ip|port type is too broad

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#5901]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.124

### Expected behavior

1. Highlight in the "freetext import results page" only relevant similar attributes for an attribute of type ip|port added via freetext import

### Actual behavior

1. Highlighting too many irrelevant similar attributes in the "freetext import results page" for an attribute of type ip|port added via freetext import

I have the impression the selection of similar attributes is done based on a OR between the two attribute sub-types of the composed attribute. This might be relevant in some cases (filename|md5, etc...) for ip|port it is generating too much noise if the port is a frequently used one (80, 443, etc...).

### Steps to reproduce the behavior

1. Create an event.
2. Use the freetext import tool, and add a value like `1.2.3.4:443`.
3. Go to the freetext import results page, you will get lots of irrelevant attributes highlighted in the "similar attributes" column.

Proposal for fix: 
For ip|port composed attributes (and other composed attribute types), only highlight similar attributes based on the relevant part (ip for this case).

**Comment by mokaddem** [comment]
Fixed with proposal for fix in https://github.com/MISP/MISP/commit/97d63a0989dc57f3da18119b656f14d56a7fa308
