### ISSUE TITLE
Schema Error

### ISSUE THREAD

**Issue by jstnk9** [MISP/MISP#5918]
Hi,

I have just updated my MISP instance to version 2.4.125. It seems that everything worked correctly, but there is an inconsistency error with the database schema.

![image](https://user-images.githubusercontent.com/7794663/82202256-f30db400-9901-11ea-9d40-b0db1c8b1ae1.png)

And viewGalaxyMatrix in events doesn't work. Show a black bar.

![image](https://user-images.githubusercontent.com/7794663/82202389-1f293500-9902-11ea-8a6b-0a12484ab42c.png)

![image](https://user-images.githubusercontent.com/7794663/82202602-716a5600-9902-11ea-8cea-1783a6670737.png)

Can you help me please? thanks!!

**Comment by mokaddem** [comment]
Hey,
Could you update your MISP instance to the latest version? We recently fixed one bug affecting galaxy matrices.
As far as your database schema is concerned, could you also check the diagnostic output after the update.
If you still have warning, could you restart the updates starting from version 29.
```sql
update admin_settings set value='29' where setting='db_version';
```
and then let the updates run.
Thanks!
