### ISSUE TITLE
[Master ticket for sanitizing YARA rules] Add regexp for yara rules import

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#592]
[Yara](http://yara.readthedocs.org/en/v3.4.0/) rules are often featured in reports.
The syntax is defined [here](http://yara.readthedocs.org/en/v3.4.0/writingrules.html).

It could help a bit for validation, but since the language is so flexible that it does not help a lot.
It is mostly for being able to import a list of yara rules via the free-text importer and/or via templates, without the need to add them one attribute at a time.

Here is my attempt in a regexp that works in python:

```
expression = re.compile(r'''
                                ^(
                                \s*
                                rule
                                \s*
                                ([A-Za-z0-9_-]*)
                                \s*
                                :{0,1}
                                \s*
                                ([A-Za-z0-9_\s-]*){0,1}
                                .*?
                                \{
                                .*?
                                condition
                                .*?
                                \})
                                ''',
                                re.MULTILINE|re.VERBOSE|re.DOTALL)
```

Integration might not work since it needs to use [multiline](https://docs.python.org/2/library/re.html#re.MULTILINE) and [dotall](https://docs.python.org/2/library/re.html#re.DOTALL) options.

**Comment by adulau** [comment]
We now have a Yara parser validator as misp-module https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/expansion/yara_syntax_validator.py
