### ISSUE TITLE
Import MISP Event JSON Files Fail with "The request has been black-holed"

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#5921]
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | Ubuntu
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.125
| Browser                   | All Browsers

### Expected behavior
Importing MISP Event JSON file creates new event with contents of previously exported Event

### Actual behavior

When Importing MISP Event JSON files over a certain size, import operation fails and does not create new Event.  

```
The request has been black-holed
Error: The requested address '/events/add_misp_export' was not found on this server.
```

### Steps to reproduce the behavior
(1) Export MISP Event in JSON Format from System A (Open Event, Select [Download as], choose 
(2) Import MISP JSON File into System B 

### Logs, screenshots, configuration dump, ...

![Snag_239bb660](https://user-images.githubusercontent.com/3220193/82232836-23068880-98fd-11ea-967e-e2233fe3b702.png)

![Snag_239bf1c3](https://user-images.githubusercontent.com/3220193/82232863-2c8ff080-98fd-11ea-9666-cd7f21a4c63e.png)

![Snag_239c2de1](https://user-images.githubusercontent.com/3220193/82232899-37e31c00-98fd-11ea-8779-bb1d4260ac73.png)

![image](https://user-images.githubusercontent.com/3220193/82233931-b42a2f00-98fe-11ea-8e1a-fa3f31c1dc5c.png)

**Comment by github-germ** [comment]
Just tested this on 2.4.131 and the export/import from instance A to B worked.

**Comment by mokaddem** [comment]
@packet-rat can you confirm @github-germ observation or are you still experiencing the blackhole?
