### ISSUE TITLE
[question]how to add attribute tag #5920

### ISSUE THREAD

**Issue by SoheiMitsukawa** [MISP/MISP#5922]
Hi.
I have a question about ExpandedPyMISP.
Please tell me that how to add attribute tag.
I am Japanese, so I use automatic translation to write messages.
I'm sorry if I made a mistake.
And I use PyMISP version 2.4.123.
I created this python code, but I couldn't add tag.
>>from pymisp import ExpandedPyMISP
>>MISP_URL = 'https://hogehoge'
>>MISP_APIKEY = 'hogehoge'
>>misp = ExpandedPyMISP(MISP_URL, MISP_APIKEY, ssl=False, debug=False)
>>attr_id = xxx
>>tag_id = yyy
>>a = misp.get_attribute(attr_id, True)
>>print(a.value)
fuga
>>t = misp.get_tag(tag_id, True)
>>print(t.name)
fugafuga
>>print(a.tags)
[]
>>a.add_tag(t)
>>print(a.tags)
[<MISPTag - please define me>]
>>now_epoch = zzzz
>>a.timestamp = now_epoch
>>misp.update_attribute(a)
>>a = misp.get_attribute(attr_id, True)
>>print(a.tags)
[]
I hoped it would show up as fugafuga at the end.
Best regards,

**Comment by Rafiot** [comment]
Makes sense, this is a limitation on MISP side at this point, you cannot add a tag to an attribute with the `update_attribute` method.

You want to use the `tag` method: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L2185

**Comment by SoheiMitsukawa** [comment]
Oh, thanks for your comment.
I tried, and I succeed!
I'm glad to know that.
Thanks so much!
