### ISSUE TITLE
MySQL install files are out of date

### ISSUE THREAD

**Issue by fatalglitch** [MISP/MISP#5927]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2
| MISP version / git hash   | v2.4.126 (3274778d35de93da9508005ae20abcfff5ce963c)
| Browser                   | N/A

### Expected behavior
Proper database schema is installed from the GIT repo pull, as declared in the installation instructions

### Actual behavior
DB Schema in INSTALL/MYSQL.sql looks to be out of date

### Steps to reproduce the behavior
Follow the base installation instructions for Ubuntu 18.04, and upon running the DB import for a new database, you get an older schema.

### Logs, screenshots, configuration dump, ...
![Screen Shot 2020-05-20 at 5 08 58 PM](https://user-images.githubusercontent.com/1149566/82497911-16309300-9abd-11ea-823c-1ed209dd2f55.png)

**Comment by fatalglitch** [comment]
It looks like upon install, there's a lock on the update process and it is blocking any DB updates

**Comment by mokaddem** [comment]
Indeed, `INSTALL/MYSQL.sql ` is not up to date but it's not an issue since it's updated to the correct version once you log in.
Based on the screenshots, it looks like the DB diagnostic was taken during an update process. Could you please check that page again once this process finishes?
