### ISSUE TITLE
CLI Enrichment not working

### ISSUE THREAD

**Issue by RevoStryder** [MISP/MISP#5931]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | NA
| PHP version               | 7.4
| MISP version / git hash   | 2.4.126, ec8ab2e23d5a96626f9fefddc7f4eff64c7f1032
| Browser                   | NA

### Expected behavior
`sudo /var/www/MISP/app/Console/cake Event enrichEvent 7 74 {"module": "urlscan"}`
or
`sudo /var/www/MISP/app/Console/cake Event enrichEvent 7 74 {"modules": "urlscan"}`

Expect this to run urlscan on event 74 with user 7 calling the action.

### Actual behavior
The following is returned
```Usage:
cake event [-h] [-v] [-q]

Options:

--help, -h     Display this help.
--verbose, -v  Enable verbose output.
--quiet, -q    Enable quiet output.
```

### Steps to reproduce the behavior
Use command as described in Events -> Automation -> Automating Certain console tasks

**Comment by mokaddem** [comment]
Thanks for the report. It seems to be a typo in the documentation. Please use instead
```
MISP/app/Console/cake Event enrichment [user_id] [event_id] [modules]
```
