### ISSUE TITLE
Add ability to clone an event?

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#5939]
What do you guys think of being able to simply clone an existing event into a new one?
Consider the following use case: we have an event containing lots of IOCs which was never meant to be shared. Now, we'd like to be able to share a large sub-set of those IOCs. One idea would be to clone the event and remove the not-to-be-shared IOCs from the new one before sharing.
Does that make sense at all or do we already have anything similar?

**Comment by RichieB2B** [comment]
Create a new event and select "Merge attributes from..." see #5820

**Comment by StefanKelm** [comment]
Awesome. That feature is at least a workaround we can live with (it doesn't keep object, for example). Thank you!
