### ISSUE TITLE
Update Event with the REST API is not working with a JSON object

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#594]
Always returns:

```
{"name":"Event could not be saved: Could not find the local event.","message":"Event could not be saved: Could not find the local event.","url":"\/event\/1725"}
```

I simply exported a JSON event and tried to reimport it. Doing the same with an XML export works fine.

**Comment by Rafiot** [comment]
You can try out with get.py and up.py from PyMISP :)

**Comment by iglocska** [comment]
In transit, will take a look asap

**Comment by iglocska** [comment]
Getting close, I think I see what's causing this!

**Comment by iglocska** [comment]
I've sent a pull request.

The issue is this: get.py dumps the contents of r['Event'] instead of r. The result will be a JSON that looks like this:

{"id": 5, "info":...}

what MISP expects:

{"Event":{"id": 5, "info":...}}

The pull request fixes this.

**Comment by Rafiot** [comment]
Fixed, closing.
