### ISSUE TITLE
where do i find my misp instance key?

### ISSUE THREAD

**Issue by NetEyes** [MISP/MISP#5944]
I just installed the latest version of MISP from fresh Ubuntu server. 
I am creating connector from OpenCTI and I need to define in the docker file the misp instance key.
Can you please tell me where do I find in the misp my instance key?

**Comment by iglocska** [comment]
Either go to Global actions -> my profile or directly to this url: `/users/view/me`

**Comment by iglocska** [comment]
This will get you your user's key. Keep in mind, you are most like a site administrator at that point, so depending on how much data you would like to push out of MISP / what restrictions you want to have in place, you might want to create an automation user for the task. Site administrators circumvent all distribution restrictions.
