### ISSUE TITLE
Install MISP on Centos 7

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#5946]
Hello, everyone. I have some questions again. I have MISP installed on Ubuntu, but for some reason I want to have MISP on Centos 7. I'm not very experencied in linux and I can't understand what I should do, to install MISP on Centos 7 using instructions from here : https://misp.github.io/MISP/INSTALL.rhel7/. 
Is this a scripts for bash? But if so why it's look like functions from programming language? I tried extract console commands from this and launch like a scripts, but this approach wasn't successfull.
The question is: How I can succesfully install MISP on Centos 7?

**Comment by SteveClement** [comment]
Ideally you read the instructions. I will make it more clear in the upcoming documentation update.
