### ISSUE TITLE
Soft delete of attributes don't propagate across MISP instance syncing when they originate from a feed

### ISSUE THREAD

**Issue by cyber288** [MISP/MISP#5949]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu0.18.04.3 
| OS version (client)       | Win10
| PHP version               | 7.2.24-0
| MISP version / git hash   | 2.4.124

### Expected behavior
MISP instance A is ingesting external feeds such as Firehol level 1 using the delta-merge functionality to a static event. Attributes associated with that event are syncing as expected with new ones added and dead ones being soft deleted.

MISP instance A does a push/pull sync with MISP instance B.

It is expected that the event corresponding with the feed will be mirrored on MISP instance B.

### Actual behavior
New attributes associated with the feed event on instance A are being propagated on instance B as expected.
Dead attributes associated with the feed are being soft-deleted on instance A. Those soft deletes do not propagate on instance B.

### Steps to reproduce the behavior
Configure syncing between two MISP instances.
Configure feed event on the first instance.
Allow feed event to propagate on the second instance.
Update feed to remove some of the original attributes.
Allow first instance to perform delta-merge with feed.
Allow second instance ton sync with the first instance.

**Comment by cyber288** [comment]
I worked on recreating the issue in a lab environment with two fresh instances of MISP.
This is the path for the attributes for my event:    Feed A -> MISP A -> MISP B (through pull sync from MISP B)
This is an example from a feed based event that originally had 4 attributes and where one was removed:
![image](https://user-images.githubusercontent.com/43047272/83184193-151fe700-a0f7-11ea-89c8-7ace5bbfbf34.png)
In the event list, on MISP A, it shows up as having 4 attributes.
When we click on the event on MISP A, we see there are now only 3 attributes:
![image](https://user-images.githubusercontent.com/43047272/83184385-6334ea80-a0f7-11ea-8192-2df115c6910a.png)

![image](https://user-images.githubusercontent.com/43047272/83184448-7c3d9b80-a0f7-11ea-8d1e-9e5d3b08e82f.png)

The dead attribute has been removed and is not accessible anymore. (but shows up the summary???)

On MISP B, there are still 4 attributes active:
![image](https://user-images.githubusercontent.com/43047272/83184638-ba3abf80-a0f7-11ea-8daa-2062b8e8ef6e.png)

The deleted attribute has not been propagated after syncing.
![image](https://user-images.githubusercontent.com/43047272/83184700-d76f8e00-a0f7-11ea-87e4-b2f8d1cddd19.png)

Everything works as expected if you create and update attributes associated with an event through the GUI.

**Comment by mokaddem** [comment]
Hello @cyber288,
Thanks a lot for the detailed issue.
It's indeed a bug. The `delta_merge` is actually hard-deleting Attribute and not soft-deleting them.
I'll try to push a fix.
