### ISSUE TITLE
OpenIOC import problem

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#595]
As mentioned in this [discussion](https://groups.google.com/forum/#!topic/misp-users/xiTXQqwiDGE), openIOC fails. The user on the google groups has more details in the screenshot since debug messages were enabled.

I reproduced it on CIRCL's MISP instance, but it fails silently, but I don't know at which hotfix level it is.

**Comment by iglocska** [comment]
Should be fixed in ce2e6a769d23f88d5536bea60e4452698fd2cec4

**Comment by adulau** [comment]
@elhoim Merged into the various CIRCL MISP instances. Feel free to test it.

**Comment by elhoim** [comment]
Thanks!

**Comment by elhoim** [comment]
It works with openioc v1.0 but not v1.1.
Be ware the links on the page are inverted (the link mentioning v1.1 links to v1.0 and the link mentioning v1.0 links to v1.1).

**Comment by mariuskagc** [comment]
Hi guys,
I just tried with v1.0 right now and it only adds it as a attachment instead of every attribute in it. Is that how it is supposed to work? Also I only can add one of them, not more than one.
Thank you!

**Comment by iglocska** [comment]
That is odd - did you check that it's indeed the correct file? As elhoim says, the links are inverted, what you want is the one called openioc1-0.zip

For me it imports a long list of filenames / various hashes.

Let me know if that solves it!

**Comment by mariuskagc** [comment]
Yes, it is. I attach a screenshot: 
![openioc](https://cloud.githubusercontent.com/assets/8927685/9350319/ebd6129a-464f-11e5-90fd-b65e3063798e.jpg)

**Comment by iglocska** [comment]
Those are the 1.1 files, the ones that you are looking for are called ht_medium_low.ioc.xml and ht_malicious-high.ioc.xml

You can grab them here: https://www.rooksecurity.com/wp-content/uploads/2015/07/openioc1-0.zip

**Comment by mariuskagc** [comment]
Oh, that's right! They are inverted, my fault. Thank you! (I deleted the other comment :) )

**Comment by iglocska** [comment]
Excellent, let us know if it's not doing what it should! :)

**Comment by Rafiot** [comment]
Fixed.
