### ISSUE TITLE
MISP: Snort Rules Download - Correct Size and Path

### ISSUE THREAD

**Issue by KZcsirtCY** [MISP/MISP#5950]
|---------------------------|--------------------
| Type of issue                | Support
| OS version (server)       | Ubuntu 16.04
| OS version (client)        | Ubuntu 16.04.5 LTS
| PHP version                 | N/A
| MISP version               | 2.4.125
| Browser                       | Chromium

### Ticket Info
Dear Support,

Please, be informed about the below support ticket:
We have automated the downloading of Snort Rules from our misp instance, making the below curl command:
curl -d '{"returnFormat":"snort", "limit":10000, "page":1}' -H "Content-Type: application/json" -H Authorization:"****API***" -H "enforceWarninglist:1" -X POST https://[misp_instance_url]/attributes/restSearch 
The size of the file is the below:
>>ls -l
5601586 Μάι  28 09:16 [name_of_the_automated_rules_file]

When following the manual export of rules, we get the below(image attached):
Export->Snort (file size 1GB)
>>ls -l
1113036165 Μάι  28 09:22 [name_of_the_manually-exported_rules_file]
![image](https://user-images.githubusercontent.com/62246794/83130939-be5ee100-a0e7-11ea-871a-e990f82c3997.png)

### Support Questions
Which is the correct Snort Rules file to download?
Is it available on restSearch path call?

**Comment by mokaddem** [comment]
Hello,
Using the restSearch is the correct way to download them. We are slowly deprecating the export page.
By looking at your script
```
curl -d '{"returnFormat":"snort", "limit":10000, "page":1}' -H "Content-Type: application/json" -H Authorization:"API_KEY" -H "enforceWarninglist:1" -X POST https://[misp_instance_url]/attributes/restSearch
```
If there is more data than 10000 (the limit you set), you might want to go to the next page to get the remaining data.
You can check the number of return entries by looking at the response header `X-Result-Count`.
