### ISSUE TITLE
Impossible to change someone else's password as admin

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#5962]
POSTing the following on `users/change_pw` as admin will change admin's password, which is super confusing:

```json
{
  "id": "44",
  "password": "Password123456",
  "org_id": "30",
  "server_id": "0",
  "email": "testusr@user.local",
  "autoalert": false,
  "authkey": "TctCaYilJwuZAdJbMgn0tGNhnsxwuX4UTFtqKNYM",
  "invited_by": "1",
  "gpgkey": "",
  "certif_public": "",
  "nids_sid": "8946062",
  "termsaccepted": false,
  "newsread": "0",
  "role_id": "3",
  "change_pw": "1",
  "contactalert": false,
  "disabled": false,
  "current_login": "0",
  "last_login": "0",
  "force_logout": false,
  "date_created": "1591003101",
  "date_modified": "1591003101"
}
```

**Comment by iglocska** [comment]
change_pw is the endpoint where you change your own password when prompted on login. If an admin wants to edit the password of a user they should go through /admin/users/edit

**Comment by iglocska** [comment]
Posting a full user object is definitely not expected or supported by that endpoint, it changes your password because it only expects the "password" field, which is also present in a user object.

**Comment by Rafiot** [comment]
:+1:
