### ISSUE TITLE
MISP Functional/technical architecture for a SOC

### ISSUE THREAD

**Issue by PakitoSec** [MISP/MISP#5966]
Dear Community,

We are going to build a MISP in our SOC service and we have a few questions about the functional / technical architecture best practices.

**Our needs are:**
- Share events inside and outside the company.
- Feed our SIEM from MISP.
- Feed MISP from our sources (SIEM included).

**Our questions are:**
- Should we have 2 MISPs: one DMZ and one internal? or just an internal MISP connected via a PROXY to the internet is enough?
- An organisation by type of user / use? Example: One for the Analysts, One for the SIEM where all attributes will be pushed in correlation rules ? Does that make sense or it's not the purpose of an "organisation" in MISP ? My fear is to have too many false positive if I do not check all my events before.
- Should I add a sighting DB if want to use it with my SIEM ? (increment sighting for example)
- Also, I'm not sure to understand this part of the documentation. Is it possible to have more information ?
![image](https://user-images.githubusercontent.com/1663786/83455326-02424500-a45e-11ea-9874-1ceb1ffc5780.png)

Thank you for your help and do not hesitate to indicate me towards documentation that I will not have seen

**Comment by mokaddem** [comment]
> Should we have 2 MISPs: one DMZ and one internal

We like to have this architecture as it allows us to cherry pick Event from both the internal and external MISP instance.

> An organisation by type of user / use?

I would use different user roles instead. Otherwise you will surely confused third parties as an organisation is unique by it's UUID and not it's name. If you give the `publisher` role to certain users, they will be able to review the event before publishing it.

> Should I add a sighting DB if want to use it with my SIEM 

I you plan to place a sighting every time you see something, definitely.

> Also, I'm not sure to understand this part of the documentation. Is it possible to have more information ?

What it describes is the following topology
```
(SECOps | internal )  ---- [Sync rules with tags] ----> (Staging | external) --------> Other MISPs
```

Do not hesitate if you have more questions.

**Comment by PakitoSec** [comment]
Thanks for the quick answer.

Regarding:
`(SECOps | internal )  ---- [Sync rules with tags] ----> (Staging | external) --------> Other MISPs`

Why the below model with only SecOps instance is more limited than the SecOps/Staging instances ?

`(SECOps | internal )  ---- [Sync rules with tags] ----> Other MISPs`

**Comment by mokaddem** [comment]
If you plan to only push data to `Other MISPs` (option 2), they are basically the same.
However, if `Other MISPs` have users on your instance, they will still be able to pull data even with the sync rules set.
Another advantage to have this setup (option 1) is the existence of a *workbench* and a clean place where your partners can pull vetted data.
There is nothing wrong with option 2 though.
