### ISSUE TITLE
Fetching the 'https://labs.snort.org/feeds/ip-filter.blf' failed with HTTP error 403: Forbidden

### ISSUE THREAD

**Issue by GlennHD** [MISP/MISP#5969]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version       | Ubuntu 18.04 LTS
| PHP version               | 7.2.24-0ubuntu0.18.04.6

### Expected behavior
Should be able to fetch Talos Intelligence IP-Blacklist (https://talosintelligence.com/documents/ip-blacklist)

### Actual behavior
I have not been able to fetch `https://labs.snort.org/feeds/ip-filter.blf` since the feed source was introduced.  Might be related to the MISP User Agent string or the the inability to follow the 302 redirect between Talos > AWS. 
https://labs.snort.org/feeds/ip-filter.blf > 301 Redirect to Talos
https://talosintelligence.com/documents/ip-blacklist > 302 Redirect to AWS
https://talos-intelligence-site.s3.amazonaws.com/production/document_files/files/...

### Steps to reproduce the behavior
Enable and click "fetch feeds" for default feed "ip-filter.blf - labs.snort.org"

### Logs, screenshots, configuration dump, ...
Screenshots:  https://imgur.com/a/wPJfQON

**Comment by LaZyDK** [comment]
Might relate to this: https://github.com/MISP/MISP/issues/2774

**Comment by mokaddem** [comment]
Hey,
The above commit should solve this issue.
If it's not the case, let us know!

**Comment by GlennHD** [comment]
Confirmed fixed in v2.4.129.  Thanks!
