### ISSUE TITLE
Update warninglists from source

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#5970]
Hello everyone. If I understand correctly, "Update warninglists" button just loads warninglists from local folder.
![изображение](https://user-images.githubusercontent.com/29750691/83609907-4d607300-a598-11ea-8104-30f7a7a79f5d.png)
If it possible to make updating warninglists from source of this lists? And maybe make schedulled tasks for this? 
P.S. And can I ask how often updates warninglists at their sources? I think it should be feeds like, am I right?

**Comment by mokaddem** [comment]
Hello,
You are right, `Update Warninglists` loads the warning lists from the local folder.
These warning list are coming from [this repository](https://github.com/MISP/misp-warninglists). So each time you pull, you can update them.
You can find more information on how to update the warning lists via the CLI [here](/events/automation).

**Comment by sustefil** [comment]
Hello @mokaddem,

so there is actually no other way than updating the lists with the provided generate scripts manually?

At least I haven't found any other way.
The `MISP/app/Console/cake Admin updateWarningLists` seems to be doing exactly the same as the button mentioned above. (just update from local folders)

It is quite confusing that the "Update warning lists" doesn't really keep them updated..

Thanks

**Comment by NailBash** [comment]
> Hello @mokaddem,
> 
> so there is actually no other way than updating the lists with the provided generate scripts manually?
> 
> At least I haven't found any other way.
> The `MISP/app/Console/cake Admin updateWarningLists` seems to be doing exactly the same as the button mentioned above. (just update from local folders)
> 
> It is quite confusing that the "Update warning lists" doesn't really keep them updated..
> 
> Thanks

At the folder with warninglists you can find folder named "tools". Here scripts, that make requests to source of warninglists. Some of them work properly and updates lists, some not :-( If you know python well you can try to modify them to work as you need.
