### ISSUE TITLE
Update Private Taxonomy

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#5976]
| Type of issue             | Support
| OS version (server)       | Ubuntu 16.04
| PHP version               | 7.4.4
| MISP version / git hash   | v2.4.126 (69f606a6c09d0c8b6bda23f7559757492fa5cecc)

I created a private taxonomy which is working. I opened machinetag.json and edited the description and value under the predicate. I also increased the version number of the file.
Performed a "Update Taxonomies" which updated the private taxonomy but it created a new tag. Is there a way to edit machinetag.json without a new tag being created?
This is causing me to have to go back and re-tag all of the attributes with the new tag.

**Comment by RichieB2B** [comment]
This is by design. The machinetag.json does not have an id for tags, just a name. If you want to change the name of existing tags you will need to do it in the MySQL database.

**Comment by timhux123** [comment]
Thanks for the update. I see what I did. I changed the name of the predicate which caused the new tag to be created.
