### ISSUE TITLE
Simpler way of closing distribution graph popup

### ISSUE THREAD

**Issue by blabut** [MISP/MISP#5978]
When opening the distribution graph popup (clicking on the "i" button at the "distribution" row when viewing an event), it doesn't seem very intuitive to me that you have to click the button again in order to close the popup.

Ideally, I would like the popup window to close when I click anywhere outside of it. This seems a good solution because it is the easiest, and accidentally triggering it would not expose to any loss of information. 

If this solution is technically complicated, I would create a clearly identifiable close button at the top right corner of the pop up itself. 

If possible, those two solutions could coexist.

**Comment by mokaddem** [comment]
Thanks for the suggestion!
