### ISSUE TITLE
Simpler way of selecting an event to view from the /events/index page

### ISSUE THREAD

**Issue by blabut** [MISP/MISP#5979]
On the main event list page (/events/index), there is (according to my limited MISP experience) no way of jumping to a given event details page than clicking on the publish status indicator (either a cross or a tick), which I find quite counter-intuitive.

I think it would be nicer for the UX to only have to click anywhere on the corresponding row (of course, outside of any other button/link such as a tag, org etc...) to be directed to the event detail page.

**Comment by mokaddem** [comment]
Haven't realized that you can click on the `publish` status to access the event.
Double clicking on the row opens the `event/view` page too.
Anyway, this part of the UI is planned to be refactored at some point.
