### ISSUE TITLE
CLI Enrichment Not Working 

### ISSUE THREAD

**Issue by RevoStryder** [MISP/MISP#5980]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | NA
| PHP version               | 7.4
| MISP version / git hash   | 2.4.126, 95d81bd0f36f4c7bcf71757a5bbe5f1a7617b954
| Browser                   | NA

### Expected behavior
Running either of the following commands should result in urlscan being run against the even with id 1448

`sudo /var/www/MISP/app/Console/cake Event enrichment 7 1448 {"module": "urlscan"}`
or
`sudo /var/www/MISP/app/Console/cake Event enrichment 7 1448 {"modules": "urlscan"}`

### Actual behavior
Running the above results in 
```
Welcome to CakePHP v2.10.21 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: %s not set
#0 /var/www/MISP/app/Console/Command/EventShell.php(318): Event->enrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->enrichment()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#5 {main}
```
### Steps to reproduce the behavior
Try to run as expected.

### Logs, screenshots, configuration dump, ...
NA

**Comment by mokaddem** [comment]
Thanks for the report. I improved the error reporting in ff7ef393c524bb8f08bba6d191f90378585c7777.
Note the enclosing quote `'` for the JSON.
```
./cake Event enrichment x y '{"modules": "z"}'
```

**Comment by RevoStryder** [comment]
Thanks for the swift reply,

`sudo /var/www/MISP/app/Console/cake Event enrichment 7 1448 '{"modules": "urlscan"}'`

I entered it with enclosed quotes as you showed and now I'm getting this error:

```
Welcome to CakePHP v2.10.21 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: Object of class stdClass could not be converted to string
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->enrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#4 {main}
```

**Comment by mokaddem** [comment]
@RevoStryder Where you finally able to solve your issue?
For me everything is working as expected on version `v2.4.129`

**Comment by RevoStryder** [comment]
Hey, Yep it works now in the latest release.

Thanks!
