### ISSUE TITLE
An Internal Error has occured

### ISSUE THREAD

**Issue by MySickSi** [MISP/MISP#5982]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.4.6 (cli)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | Google Chrome

### Support Questions
When I attempt to access the GUI at my local address, I am presented with "An internal error has occurred"

### Logs, screenshots, configuration dump, ...
```
2020-06-04 16:14:23 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/MISP/app/Controller/AppController.php(619): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/AppController.php(146): AppController->_setupDatabaseConnection()
#3 /var/www/MISP/app/Controller/EventsController.php(59): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

**Comment by MySickSi** [comment]
Ok I just ran: sudo killall -u mysql & sudo service mysqld start. I am now receiving a new error. 

`2020-06-04 17:09:41 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'misp\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(619): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(146): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/EventsController.php(59): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}`

**Comment by mokaddem** [comment]
Is seems mysql credentials are wrong. Please fix it in `/var/www/MISP/app/Config/database.php`

**Comment by MySickSi** [comment]
Yep, that fixed it. I had installed MISP again by accident over an already existing version of MISP while trying to add modules. There were still other issues, so I had the server reimaged and put a fresh install on it.
