### ISSUE TITLE
Integration from MISP to Cisco ESA

### ISSUE THREAD

**Issue by ser-storchak** [MISP/MISP#5983]
Hello, everyone!

I would like to integrate my MISP-platform with Cisco ESA External Threat Feeds: receive IoC from MISP Taxii-server (domains, IP addresses, email) in STIX format.

When you try to connect to the Cisco ESA, the following error is issued:

`THREAT_FEEDS: Unable to fetch the observables from the source: MISP after 3 failed attempts. Reason for failure: Taxii Error: HTTPSConnectionPool(host='misp.tmk-group.com', port=9000): Max retries exceeded with url: /services/poll (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2a1a6bac>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

![2020-06-05 10_38_55-Cisco Email Security](https://user-images.githubusercontent.com/2908781/83850327-71978d80-a719-11ea-9ce5-a2bd74d3c048.png)

logs push.log:
```
2020-06-04 23:57:52,690 - __main__ - INFO - Starting...
2020-06-04 23:57:52,694 - __main__ - INFO - Subscribing to tcp://localhost:50000
2020-06-04 23:57:52,694 - __main__ - INFO - Waiting...
2020-06-04 23:57:56,876 - __main__ - INFO - Recieved a message!
2020-06-04 23:57:56,877 - __main__ - INFO - Ignoring misp_json_self...
2020-06-04 23:57:56,877 - __main__ - INFO - Waiting...
2020-06-04 23:58:07,001 - __main__ - INFO - Recieved a message!
2020-06-04 23:58:07,002 - __main__ - INFO - Ignoring misp_json_self...
...
[config.yaml.txt](https://github.com/MISP/MISP/files/4734702/config.yaml.txt)
[data-configuration.yaml.txt](https://github.com/MISP/MISP/files/4734715/data-configuration.yaml.txt)


```
Any suggestion is welcome!

Best Regards

**Comment by mokaddem** [comment]
Hello,
Not sure to see on which side the error is, but it clearly seems that one tool cannot reach the other.

**Comment by ser-storchak** [comment]
> Not sure to see on which side the error is, but it clearly seems that one tool cannot reach the other.

Maybe you have any idea why this might be happening?

**Comment by mokaddem** [comment]
Can you ping the services from one machine to the other?
Are there any FW rules blocking requests?
