### ISSUE TITLE
OpenIOC imported IOCs are not marked as to IDS

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#599]
OpenIOC imported IOCs such as hashes are not marked as "To IDS".
Could you please change that? The same logic (to decide which attribute types will be flagged as to IDS  by default) as for free-text import would be perfect!

**Comment by iglocska** [comment]
Makes sense, will look into it!

**Comment by iglocska** [comment]
I went with a simple list based on type, should work fine, let me know if you want to tweak it!
