### ISSUE TITLE
CLI Enrichment Not Working

### ISSUE THREAD

**Issue by RevoStryder** [MISP/MISP#5995]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | NA
| PHP version               | 7.4
| MISP version / git hash   | 2.4.126, 95d81bd0f36f4c7bcf71757a5bbe5f1a7617b954
| Browser                   | NA

### Expected behavior
Running either of the following commands should result in urlscan being run against the event with id 1448

` sudo /var/www/MISP/app/Console/cake Event enrichment 7 1448 '{"modules": "urlscan"}'`

### Actual behavior

```
Welcome to CakePHP v2.10.21 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: Object of class stdClass could not be converted to string
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->enrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#4 {main}
```

### Steps to reproduce the behavior
Use command as instructed.

**Comment by mokaddem** [comment]
Related to https://github.com/MISP/MISP/issues/5980
