### ISSUE TITLE
MISP Redis Configuration Always localhost?

### ISSUE THREAD

**Issue by lillypad** [MISP/MISP#5998]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.126, hash of the commit
| Browser                   | N/A

### Support Questions
Where is the configuration for redis?

I've changed the host in the following files:
```text
app/Lib/Tools/PubSubTool.php
app/Model/AppModel.php
app/Plugin/CakeResque/Config/config.php
INSTALL/setup/config.php
```

I also followed this issue #5138.

No matter where I change these settings, it appears it always wants to connect to `127.0.0.1` / `localhost`. 

I've been grepping around the entire code base looking for this, do you know where to set it properly?

Thanks for the help.

:smile:

**Comment by mokaddem** [comment]
Hello and sorry for the late reply,
We highly discourage people to modify the source code for configuration issues as it could lead to unexpected behavior and will prevent you to upgrade your instance.
You can configure the redis settings in the web interface under `/servers/serverSettings/MISP` and then `MISP.redis_*` or also in the configuration file located here `MISP/app/Config/config.cfg`.
Cheers

**Comment by adv4000** [comment]
You will need to add the following setting into `MISP/app/Config/config.php` file:
```
<?php
$config = array (
  'MISP' =>
  array (
    'baseurl' => 'https://misp.xxxxxx.xyz',
    'redis_port' => '6795',
    'redis_host' => 'misp.cache.amazonaws.com',
    [.....]
 );
```
