### ISSUE TITLE
Pull job stuck at 75%

### ISSUE THREAD

**Issue by xme** [MISP/MISP#6000]
I've a MISP instance linked to another one. 'Pull' jobs are stuck at 75% with always the same message in logs:

```
Failed to pull event #<uuid>
Reason: Event could not be saved: Event in the request not newer than the local copy. 
```
Any idea how to fix/debug this?

**Comment by mokaddem** [comment]
Hey,
It basically means that you are trying to pull an event that you already have and the timestamp or your local event is >= of the remote one.
I guess the issue has been solved since then?

**Comment by enjeck** [comment]
@xme 

Did you eventually solve this?
