### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#6002]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

Questions | Answers
-- | --
Type of issue | Support
OS version (server) | RHEL, with MISP running on a docker container..
OS version (client) | MacOS, Win10,
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

### Support Questions
I need some assistance or if anyone can point me in the right direction or if the can share code fragments. I would like to be able to get events using REST API that would output events and their associated IOCs, content based on a specific tag. For example events tagged with COVID-19. Events would be have already been tagged as they are entered manually or thru a feed.

**Comment by meditadvisors** [comment]
Some documentation here on:
[Automation](https://www.circl.lu/doc/misp/automation/#example)
[PyMISP](https://www.circl.lu/doc/misp/pymisp/)

Example:
```
curl \
 -d '{"returnFormat":"csv","limit":10,"type":"ip-dst","tag":"COVID-19"}' \
 -H "Authorization: blabla" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 -X POST https://misp.local/events/restSearch
```
Is that what you are looking for?
