### ISSUE TITLE
Possible to re-add an existing entry in an event

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#601]
It is possible to update an event and to add the exact same hash or URL for example, that should throw an exception (tested via the viper module).

**Comment by iglocska** [comment]
Looking into it!

**Comment by elhoim** [comment]
Is it fixed by https://github.com/MISP/MISP/commit/a93807439d987543aa4f1b5e1d5479f6e0c83b55 ?

**Comment by iglocska** [comment]
Yup should be fixed indeed!
