### ISSUE TITLE
Delete all attributes on event

### ISSUE THREAD

**Issue by Feldunost** [MISP/MISP#6010]
Hello,

I'm looking for a way to do this task in API through curl, or any other automation way.
I have several events that gets automatic feeding, but there is a need for whole event's attributes cleanup/deletion time to time (once per month for example).

Any proper way to do that ?
I saw this, but can't grasp the basis of it.
https://www.circl.lu/doc/misp/automation/index.html#post-/attributes/delete/

Thanks for your help.

**Comment by Feldunost** [comment]
Anyone has an idea ?

**Comment by tlansec** [comment]
You could use pymisp and first list all attributes for event, and then delete each attribute using its uuid:

https://pymisp.readthedocs.io/en/latest/modules.html

```
misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
results = misp.search('attributes', eventid=args.event, pythonify=True)
for r in results:
    misp.delete_attribute(r['uuid']) 
```

^ something like this.

Alternatively, you could just delete the entire event, and create a new one, since you're going to be scrapping all its attributes anyway.

**Comment by Feldunost** [comment]
> Alternatively, you could just delete the entire event, and create a new one, since you're going to be scrapping all its attributes anyway.

Actually it's not an option because the event_id is widely used on other scripts. 
I rather wish to cleanup the current event whitout deleting it as whole.

I'm going to try it out and see if i can do something with your code, not an expert in dev actually.

**Comment by Feldunost** [comment]
Ok this code currently works however it's extremely long ~630 attributes deletion each minute, i currently got about 300 000 !
So approximately 8 hours to do that, not really an efficient method, but still it works for now.

Actually i think we need to add a multi-task concurrent process in that script.
I will check Mysql workers, because it's in a constant 15% usage.

By the way, it doesn't delete soft-deleted attributes that are stored on event (grey) ones, and so the attribute count still remains wrong. I'm searching for that but it seems i can't delete them ...

Edit: Apparently search method, i could show up deleted attributes with below parameter, but doesn't delete at all :
`results = misp.search('attributes', deleted=[0, 1], eventid=555, pythonify=True)`



**Current code :**

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pymisp import ExpandedPyMISP

misp = ExpandedPyMISP("https://serverIP", "APIKEYTOPASTE", ssl=False, debug=False, proxies={}, cert=None, auth=None, tool='', timeout=None)
results = misp.search('attributes', eventid=555, pythonify=True)
for r in results:
    misp.delete_attribute(r['uuid'], hard=true)
```

**Comment by Feldunost** [comment]
It seems there is a bug on an event that retrieve feeds from alienvault for example, i checked the following :
- soft deleted attributes : 0 (deleted : both as filter)
- normal attributes : 0
- event count attributes : 144000-ish

I am unable to empty it properly, did i miss something ?

**Comment by mokaddem** [comment]
I don't think it's supported by PyMISP already but posting a list of IDs to this endpoint should delete them
```
/attributes/deleteSelected/[event_id]/[hard]
[id1, id2, id3]

e.g.
attributes/deleteSelected/41/1
[12, 14]
```

**Comment by chrisinmtown** [comment]
Thanks @mokaddem for explaining the server already supports deleting a batch of attributes by ID!  I wrote a PyMISP issue to add a method for deleting a list of attributes by ID.
