### ISSUE TITLE
Deleting Events Doesn't Shrink Database

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#6011]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 LTS
| OS version (client)       | Windows 10
| PHP version               |  7.2.24-0ubuntu0.18.04.4
| MISP version / git hash   | 2.4.126,  (d379a16666f619ed21c19bcfdb80c6ec12c62272) 
| Browser                   | If applicable

### Support Questions
I've got a script to delete events per recommendations on here 

```
from keys import misp_url, misp_key
import json
from pymisp import ExpandedPyMISP, MISPEvent, MISPObject
import datetime
import time
import sys
import os
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

now = datetime.datetime.now()
then = now - datetime.timedelta(days=7)
epoch = then.timestamp()

startTime = datetime.datetime.now()

# create pymisp object
def init(url, key):
    return ExpandedPyMISP(url, key, False)

misp = init(misp_url, misp_key)

eventDictList = misp.search_index()
for eventDict in eventDictList:
    if int(eventDict['timestamp']) < epoch:
        event_id = (eventDict['uuid'])
        event = misp.get_event(event_id)
        id = (eventDict['id'])
        print('Deleting ID:%s'%(id))
        misp.delete_event(event)

print(datetime.now() - startTime)
```
Besides being really slow it doesn't seem to be having an effect on disk space. 

Is there something else I can do?  Or anything else recommended?

Thanks!

**Comment by iglocska** [comment]
This sounds like more of a mysql level question than MISP. A quick explanation: Deletes in mysql don't actually free up space on disk themselves, they just mark the data as deleted. You can run `optimize table` to reclaim the unusable space, but if you have the `innodb_file_per_table` directive set to off, you can't optimize the tables though.

**Comment by mathurin68** [comment]
:(  MariaDB [misp]> truncate correlations;

and then of course cleaning up some of the duplicates... the answers are almost always in here somewhere.
