### ISSUE TITLE
Timestamp of attribute does not get updated after a soft-delete through a feed delta-merge

### ISSUE THREAD

**Issue by cyber288** [MISP/MISP#6013]
Attributes associated with an event originating from a feed were previously being hard deleted when they disappeared from a feed being delta-merged. This caused issues when syncing with other MISP instances since hard deleted attributes don't propagate.

Following issue #5949, @mokaddem issued a fix that replaced those hard deletes with soft deletes.

Following the fix, we did some testing locally and identified that soft-deleted attributes were not propagating properly. I opened issue #5989 regarding this.

Further investigation allowed us to understand what was really happening. The timestamp of soft-deleted attributes through delta-merge are not being updated. It seems this timestamp is used when syncing across MISP instances. Attributes older than last sync time are not being propagated. This means that the soft deleted attributes don't replicate properly in most instances.

Soft-deleted attributes should have their timestamp updated. This is what happens when a soft-delete is performed through the GUI or through pyMISP.

I will close issue #5989 since it is less precise.

**Comment by cyber288** [comment]
Further testing reveals that the corresponding event timestamp and sighting_timestamp value in the database must also be updated accordingly.

We have taken a soft-deleted attribute from a delta-merge that wasn't propagating to our other MISP instance and fixed it in the db. After the fix, it propagated as expected.

**Comment by mokaddem** [comment]
@cyber288 Thanks again for the thorough analysis.
The issue should be definitively fixed now.
