### ISSUE TITLE
MISP PUSH is not working as expected

### ISSUE THREAD

**Issue by srikanthprathi** [MISP/MISP#6030]
MISP Version: 2.4.126

I am having 45K events in my local MISP Instance and I tried to push them to the remote MISP instance but it is not happening.
I am able to test the connection with the target remote MISP instance and used the AuthKey of the SyncUser role.
When I push the events, the job is getting created and it is getting completed just in 5 seconds but in the target remote MISP instance, the events are not getting created.

Note: When there were 10k events, it worked fine but I am facing this issue when tried with 45k events.

**Comment by stricaud** [comment]
Could you please give some colors on how you are pushing?

**Comment by srikanthprathi** [comment]
![misp_push_issue](https://user-images.githubusercontent.com/58368040/85042052-59f3e680-b1a8-11ea-8ddb-b155ce163081.JPG)
I have configured the server under List servers and clicked on the "Push All" under the actions.

**Comment by srikanthprathi** [comment]
Any update on this?

**Comment by mokaddem** [comment]
@srikanthprathi Do you see anything unusual in your log files when you push?
What is the result of the job?
Thanks in advance
