### ISSUE TITLE
Can't update MISP

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#6039]
Hello, everyone. I have troubles with my MISP running on Centos 7. I see infromation that my MISP is outdated.
![изображение](https://user-images.githubusercontent.com/29750691/85253391-7f6a4400-b477-11ea-9043-671d8644aa5c.png)
But when I try to update it I get error:
![изображение](https://user-images.githubusercontent.com/29750691/85253471-a88ad480-b477-11ea-93e4-83757fd1740a.png)
Do you know any solution of this problem?

**Comment by adulau** [comment]
Looking at the error, your git installation is not complete (curl Library is missing). Can you try to run git from the command line and install the missing libraries/packages ?

**Comment by NailBash** [comment]
Which commands I should write to command line to do it? I don't know how to work with git good enough

**Comment by adulau** [comment]
It depends of your distribution.  While googling for your error, I found this:

https://bugzilla.redhat.com/show_bug.cgi?id=1785720

**Comment by NailBash** [comment]
Thank you for your help. For now updated using:
sudo -u apache git pull origin 2.4
sudo -u apache git submodule update --init --recursive
