### ISSUE TITLE
Bruteforce protection not working?

### ISSUE THREAD

**Issue by 54m4n** [MISP/MISP#6040]
Hi, I set the SecureAuth.amount to 3, and the SecureAuth.expire to 600 which means you can try to login 3 times, and after that you will block out for 600 seconds.
After you fail 3 times, the website says: 
"You have reached the maximum number of login attempts. Please wait 600 seconds and try again.
Error: The requested address '/users/login' was not found on this server."

After that you can refresh the main page, and continue your bruteforcing.

At the misp database the 'bruteforces' table shows correctly the ip, username, expire. I read about an issue which is caused by the time-shifting between the server&client, or the mysql database&apache, but now it is correct. 

Is this a bug, or something?

**Comment by SteveClement** [comment]
Dear I cannot reproduce this behaviour. Try to update to latest.
