### ISSUE TITLE
MISP update problem from v v2.4.120 to  v2.4.127

### ISSUE THREAD

**Issue by antonmalae** [MISP/MISP#6041]
Hello,

When trying to update from version v2.4.120 to version v2.4.120 from GUI it fails, 
```
_cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1



cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

error: Your local changes to the following files would be overwritten by merge:
	tools/misp-wipe/misp-wipe.sql
Please, commit your changes or stash them before you can merge.
Aborting_
```

What do you recommend? Thank you

Currently installed version… v2.4.120 (0b31062d4c6dc29a303603d35661cf4d6dd17e62)
Latest available version… v2.4.127 (6c7c481419ec04e7770eece139bb567d9865369a)
Status… Outdated version
Current branch… 2.4

**Comment by RichieB2B** [comment]
You changed the file `tools/misp-wipe/misp-wipe.sql` which you can show with`git diff` and  fix with `git stash`

**Comment by SteveClement** [comment]
@antonmalae on your server, go to the command line and to the following:

```
cd /var/www/MISP 
sudo -u www-data git stash
(now do the update and after that drop back to the cmd-line)
sudo -u www-data git stash pop
```
