### ISSUE TITLE
The request has been black holed

### ISSUE THREAD

**Issue by annetteshajan** [MISP/MISP#6042]
Hello team

When I login to MISP for the first time I get this output after logging in:

> The request has been black-holed
> Error: The requested address '/users/login' was not found on this server.

It does not even check whether the email and password are correct. It gives this output no matter what I enter.
Here is my error log:

```
2020-06-22 07:12:43 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(UsersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(UsersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

I have configured the system with a reverse proxy, but I'm not sure what the fix is,so that I can log in successfully.
Please suggest a fix, have been struggling with this for a while

**Comment by legoguy1000** [comment]
have u run the `/var/www/MISP/app/Console/cake userInit -q` command.  We had the same issue with our docker image and found that having that command run on first start solves that problem.  If you don't then when u try to login, the user account `admin@admin.test` doesn't exist and it gives this error.  However MISP has logic to detect when u try to login that the default account doesn't exist and should make it after that.

**Comment by SteveClement** [comment]
Please let us know if the above mentioned fixed the issue.

**Comment by mkulicke** [comment]
I am experiencing the same issue, just in a different flavor: 
- the instance is already set up, with an existing database
- the blackhole only occurs with Google Chrome
- with Microsoft Edge it just works fine
- as the instance is already used, the script `/var/www/MISP/app/Console/cake userInit -q` aborts with `Script aborted: MISP instance already initialised.`
- the error.log is identical to the one above

EDIT:
- I read elsewhere that adblockers could be a cause and that the nosniff header in apache2 should be set. Spoiler alert: That's already the case
- The Chrome only has the ublock origin plugin installed but the blackhole also occurs with that deactivated.

EDIT2: 
Damnit! After the update to version 84 of Chrome the blackhole does NOT occur anymore...

**Comment by YashvirGaming** [comment]
First I get this 
![image](https://user-images.githubusercontent.com/64865096/169390685-7c2b14f7-5b8b-43c9-ae5a-f3bd88334033.png)

Next i mess around with login api  for example adding `%2Fmember%2Fdashboard `
etc etc some tricky Html URL Encoding there...

Then success 
![image](https://user-images.githubusercontent.com/64865096/169391392-361864a8-43bd-4dc8-b74d-f8c410489daa.png)
