### ISSUE TITLE
STIX2 export doesn't work when object name contains `_` char

### ISSUE THREAD

**Issue by JakubOnderka** [MISP/MISP#6046]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| PHP version               | 7.4
| MISP version / git hash   | 2.4.128

### Expected behavior

STIX2 export generates JSON.

### Actual behavior

Error message is generated:

```
Error while processing your query: Invalid type name 'x-misp-object-intelmq_event': must only contain the characters a-z (lowercase ASCII), 0-9, and hyphen (-).
```

### Steps to reproduce the behavior

1. Create new event
2. Add `intelmq_event` object to event
3. Click Download as....
4. Click STIX2
5. See generated file

**Comment by chrisr3d** [comment]
Should be fixed, but let me know if anything goes wrong
