### ISSUE TITLE
Module saved enriched data to event ID 0

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#6051]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu Bionic 18.04
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.126@150b66d
| Browser                   | Firefox

### Expected behavior
Enriched data should be saved into the event ID where the module (Shodan) was ran from or MISP should raise an error when a module tries to push data into non-existing event ID e.g. event ID being empty like it looks like according to the logs below.

### Actual behavior
Enriched data is saved in following manner according to the MISP logs:

Id | Email | Org | Created | Model | Model ID | Action | Title
-- | -- | -- | -- | -- | -- | -- | --
144725 | SYSTEM | SYSTEM | 2020-06-23 08:08:25 | Attribute | 121363 | add | Attribute (121363) from Event (): Network activity/domain [value redacted]
144724 | SYSTEM | SYSTEM | 2020-06-23 08:08:25 | Attribute | 121362 | add | Attribute (121362) from Event (): Network activity/ip-dst [value redacted]

### Steps to reproduce the behavior
1. I am using the ready made virtual image available from [here](https://www.circl.lu/misp-images/MISP_v2.4.126@150b66d/).
2. I have enabled the Shodan module from the settings and given it an API key.
3. I have an event that I have given some attributes to. Namely IP addresses, domains, emails etc.
4. From the Enrich Event menu I chose the shodan option and let it ran. Noticed the issue when the UI showed a correlation in event ID 0.

### Logs, screenshots, configuration dump, ...

Screenshot from the event page. Results are filtered by correlation. This is how they are showing:

![image](https://user-images.githubusercontent.com/5585477/85438449-b2eec080-b594-11ea-8168-9838363b11c4.png)

When I mouse over the event ID 0 it shows like this:

![image](https://user-images.githubusercontent.com/5585477/85439015-36a8ad00-b595-11ea-9989-6c1f807db0f9.png)

If I click on it I get the following error page: 

```
Invalid Event.
Error: The requested address '/events/view/0/1/477' was not found on this server.
```

If I try to get the event ID 0 with curl: `curl -k --header "Authorization: [API KEY REDACTED]" --header "Accept: application/json" --header "Content-Type: application/json" https://<misp url>/events/0`

I get the following response: `{"name":"Invalid Event.","message":"Invalid Event.","url":"\/events\/0"}`

If I try to delete the event ID 0 with curl: `curl -k --header "Authorization: [API KEY REDACTED]" --header "Accept: application/json" --header "Content-Type: application/json" -X "DELETE" https://<misp url>/events/0`

I get the following response: `{ "saved": false, "name": "Could not delete Event", "message": "Could not delete Event", "url": "\/events\/delete", "errors": "Event was not deleted."}`

The Jobs page had this in it:

![image](https://user-images.githubusercontent.com/5585477/85448442-5cd34a80-b59f-11ea-82d4-358ec3e89241.png)

I thought to file this bug report on this project instead of MISP/misp-modules since it would make more sense, to me atleast, that the MISP would for example raise an error when something like this happens.

Also any ideas how would I be able to delete those attributes from the problematic event ID?

**Comment by iglocska** [comment]
Woah, ok that looks nasty.

**Comment by samitainio** [comment]
Answer to my own question on how to delete those attributes in case someone else has this problem in the future:

1. Go to Server Settings & Maintenance page.
2. Open Diagnostics.
3. At Orphaned attributes section click the "Check for orphaned attributes" button.
4. Click "Remove orphaned attributes" and then "Remove published empty events".

**Comment by mokaddem** [comment]
@samitainio Thanks for answering your own question.
Do you have this `Event 0` behavior with other enrichment modules?

**Comment by samitainio** [comment]
@mokaddem `Event 0` only happened with the `Shodan` module. Afterwards of writing this bug report I did notice that running `farsight_passivedns` module has similar effect but without that `Event 0` popping up in correlation. With the `farsight_passivedns` module this however happens:

![image](https://user-images.githubusercontent.com/5585477/87979046-1d364a80-cada-11ea-8cc1-045ba0c3ef76.png)

Then at the event page there are no new attributes added to the event.

If I then go check the orphaned attributes I get this:

![image](https://user-images.githubusercontent.com/5585477/87979272-743c1f80-cada-11ea-82d2-70465be5010a.png)

This `farsight_passivedns` module enrichment was tested with the same setup but I have upgraded my MISP instance to v2.4.129 (b2a2acd8866b6cea6fafa907cc3510787e9111f7) since of writing the original bug report. 

For sake of testing I tried to create another test run with the `Shodan` module with the above MISP version.

![image](https://user-images.githubusercontent.com/5585477/87980273-0133a880-cadc-11ea-9aa4-93ea2d2c81cf.png)

There was a difference to the original bug report this time. No `Event 0` correlations but no new added attributes to the test event either. I checked the orphaned attributes and they are all there again.

![image](https://user-images.githubusercontent.com/5585477/87980435-4b1c8e80-cadc-11ea-81ae-9bc8c2378f50.png)

However if I run VirusTotal module that works just fine without any problems `¯\_(ツ)_/¯`

**Comment by chrisr3d** [comment]
Forgot to mention the issue in the commit, but it should be working since a531e9c0b6b1240207ccd6bc09d4b36e687c0d86
Be aware that I also updated the shodan module to have a better parsing of the results, the module itself parses json format returned by the query to shodan, and gives some MISP attributes and objects instead of giving back to MISP the results as freetext.

Let me know if you still face any issue and reopen if needed
