### ISSUE TITLE
Wrong Stix Version in requirements.txt

### ISSUE THREAD

**Issue by garrit-schroeder** [MISP/MISP#6056]
https://github.com/MISP/MISP/blob/364ca9d9d8ca8206cac5daebeadb18c52452f0e1/requirements.txt#L4

Hello guys,

the diagnostics tab requires as newer Stix version (1.2.0.9) than listed in the requirements.txt (1.2.0.6)

Should be: stix == 1.2.0.9

**Comment by chrisr3d** [comment]
I just aligned it with the requirements listed in the Pipfile, which is the one used to set the virtual env' up.
So it is set to the latest version now
