### ISSUE TITLE
Feed import shown as done but no event imported

### ISSUE THREAD

**Issue by TaR7k1xPG84** [MISP/MISP#6057]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu (OVA MISP) 
| OS version (client)       | 4.15
| PHP version               | 7.2
| MISP version / git hash   | 2.4.126, 150b66da2fb7b2cfe45477f62c12ac8716d247d7

### Support Questions
Hi, 

I'm trying to import a feed into a MISP but I've got an issue I can't solve. I'm doing the feed creation and import on the same MISP instance as I'm just trying to grasp its mechansme.

The feed was generated using PyMISP (it's last version as of yesterday) with those following settings:

- entries = 200
- filters = {'published':'true'} 
- valid_attribute_distribution_levels = ['3']

Everything worked as expected, I got 200 files with events plus the manifest and the hashes file. 

I then tried to import it again in the MISP, using the Web interface. I created a feed with the following settings:

- Enabled: true
- Lookup: True
- Caching enabled: True
- Name: test
- Provider: test
- input source: local
- header: "Authorization: xxx" 
- URL: /var/www/MISP/app/tmp/feed-generator/output
- source format: MISP feed
- distribution: all communities
- default tag: test

I also tried with the setting "caching enabled" set to false but got the same result. 

After the creation of the feed, I went back into it to edit it and modified those following settings:

- organisation creator: ORGNAME
- target event: new event each pull
- target id: [empty] 
Delta merge: true

I also tried with the settings "target event" set to fixed event, "target event id" set and "delta merge" set to false but got the same result. 

In the end, when I start the feed pull, the task complete itself successfully but no event are shown on the home page. I checked the logs (/var/www/MISP/app/tmp/logs/resque-2020-*.log and /var/www/MISP/app/tmp/logs/resque-worker-error.log) but there is not error. In the apache logs, the Get /feeds/fetchFromFeeds/[feedID] gets a 302 and gets redirected on the /feeds. 

I get no error on the webUI, so I don't understand. Would any of you have any clue on the matter? 

Thanks for your help.

**Comment by adulau** [comment]
If it's the same MISP instance, you might have already the event. So it won't import anything new.

**Comment by TaR7k1xPG84** [comment]
Thank you for your quick answer.

I forgot to write this. I took care of it beforehand by deleting everything, even in the blacklist.

**Comment by JakubOnderka** [comment]
Did you try to preview feed by URL `/feeds/previewIndex/[feedID]`?

**Comment by TaR7k1xPG84** [comment]
I just tried and I saw the events from the feed. I tried to import one from this view but I got the same result, no event on the home page.

**Comment by adulau** [comment]
Can you check the error logs and share it it with us?

**Comment by TaR7k1xPG84** [comment]
Here are the logs. 

[error.log](https://github.com/MISP/MISP/files/4836386/error.log)
[resque-2020-06-26.log](https://github.com/MISP/MISP/files/4836387/resque-2020-06-26.log)
[resque-worker-error.log](https://github.com/MISP/MISP/files/4836388/resque-worker-error.log)

Please tell me if you need anything else.

**Comment by JakubOnderka** [comment]
Logs look fine for me, errors are probably related to other feeds. Can you please also check Audit logs?

**Comment by TaR7k1xPG84** [comment]
Ok course I didn't check there... There are logs saying "Received a published event that was empty. Event add process blocked".

I forgot to mention that the hashes.csv file is empty, I don't know if it matters at all in this situation. 

Moreover, the events I'm trying to import are events that I pulled from another MISP instance, coming from the CIRCL, CUDESO, ESET, etc... So they are not empty, or at least do not seem to be. What is considered to be an empty event?

**Comment by TaR7k1xPG84** [comment]
One more thing, when I look at the feed settings or export them as a json file, the settings parameter is set with a csv object, even though I did not configure a csv feed but a misp object feed. Even if I modify this in the interface, it does not take into consideration my changes. However, the source_format is still misp in the exported json configuration. 

Here is the settings parameter:
Settings: {"csv":{"value":"", "delimiter":""}, "common":{"excluderegex":""}}

Could it have any influence?

**Comment by JakubOnderka** [comment]
> I forgot to mention that the hashes.csv file is empty, I don't know if it matters at all in this situation.

This file is used just for feed caching, for pull is not used.

> Could it have any influence?

This should be OK, important is `source_format` field.

> What is considered to be an empty event?

Empty event is published event that doesn't contains Attribute or Object.

> There are logs saying "Received a published event that was empty. Event add process blocked".

For all events that you want to import?

**Comment by TaR7k1xPG84** [comment]
> For all events that you want to import?

Yes.

> Empty event is published event that doesn't contains Attribute or Object.

This should be the source of the issue, the feed's events do not have attributes (nor objects). At first I did not thought it would be an issue but I'll look into why they were generated without any.

> This should be the source of the issue, the feed's events do not have attributes. At first I did not thought it would be an issue but I'll look into why they were generated without any.

But with this in mind, it raises a question: if we want to generate a feed of events without attributes (or objects), I suppose it would be impossible to import it afterwards, even if it would be legitimate?

Anyway, I'll update the ticket when I have more info if it solve the upload issue.

Thanks for your help!

**Comment by TaR7k1xPG84** [comment]
Ok, I ran once again the feed generator and got some attributes in my events (I think I did not get attributes before because of the configuration of the valid_attribute_distribution_levels being wrongly set).

I tried again to import the feed in the MISP (I tried with two different MISP instances this time) and it worked like a charm. So thank you for your indication, it solved my issue.

But I'm still wondering, in the case where we have events without attributes or object, it's not possible to publish them in a feed and to upload them somewhere else then?

**Comment by mokaddem** [comment]
@TaR7k1xPG84 Glad you managed to make it work!

> But I'm still wondering, in the case where we have events without attributes or object, it's not possible to publish them in a feed and to upload them somewhere else then?

No it's not possible. MISP will reject empty events
