### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by kaien** [MISP/MISP#6059]
I think that we need to modify file "/usr/local/src/mail_to_misp/requirements.txt".

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.128

### Expected behavior
No install errors.

### Actual behavior
ERROR: apiosintds 1.8.3 has requirement pytz==2019.3, but you'll have pytz 2020.1 which is incompatible.
ERROR: apiosintds 1.8.3 has requirement validators==0.14.0, but you'll have validators 0.14.3 which is incompatible.

Successfully built flask-bootstrap defang pydeep pyfaup pyrsistent validators visitor wrapt
ERROR: mail2misp-0-1-0 0.1.0 has requirement defang<0.6.0,>=0.5.3, but you'll have defang 0.2.4 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement flask<2.0.0,>=1.1.2, but you'll have flask 1.1.1 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement gunicorn<21.0.0,>=20.0.4, but you'll have gunicorn 19.9.0 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement pyfaup<2.0,>=1.2, but you'll have pyfaup 1.0 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement pymisp<3.0.0,>=2.4.126, but you'll have pymisp 2.4.111.1 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement python-magic<0.5.0,>=0.4.18, but you'll have python-magic 0.4.15 which is incompatible.
ERROR: mail2misp-0-1-0 0.1.0 has requirement validators<0.16.0,>=0.15.0, but you'll have validators 0.13.0 which is incompatible.

#######################################################################################  (86%)
url = """"
Entering 'pymisp/data/misp-objects'
fatal: couldn't find remote ref master
fatal: run_command returned non-zero status for pymisp/data/misp-objects
.
Obtaining file:///var/www/MISP/PyMISP

### Steps to reproduce the behavior
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M -m -S

**Comment by SteveClement** [comment]
In theory fixed with the latest mail_to_misp PR.

Thanks for the feedback.
