### ISSUE TITLE
One attribute with malformed data leads MISP to throw away all attributes

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#606]
If one of the added attributes contains a Hash (md5, sha1, sha256) or an IP (ip-src, ip-dst) which does not match the appropriate regex patterns in MISP, the REST API does not add any attribute in the list.
```python
new_event = {'Event': {'info': 'testevent', 'date': '2015-01-01', 'distribution': '0',
					   'threat_level_id': '1', 'analysis': '0',
					   'Attribute': [{'category': 'Network activity', 'type': 'domain',
									  'value': 'test.com', 'distribution': '0'},
									 {'category': 'Payload installation', 'type': 'md5',
									  'value': '098f6bcd4621d373cade4e832627b4fz',
									  'distribution': '0'}]}}
event = json.loads(misp.add_event(new_event).text)
```
The attribute list in the response and in the web interface is empty.

**Comment by elhoim** [comment]
I suppose the desired outcome is to add the valid attributes and reject the others?

**Comment by thomai** [comment]
Indeed! That's supposed to be.

**Comment by iglocska** [comment]
There is another option, to block adding the event altogether and return the reason for why it failed. The problem with just adding everything else is that whoever pushes the data doesn't know about some of the data being dropped.

**Comment by thomai** [comment]
Why is it handy to do a pattern check for these types anyway? Probably a malware contains an invalid IP string just to obfuscate the code or something like that?

**Comment by iglocska** [comment]
In that case it's probably best to add it as a comment instead of an IP.
You can feed a bunch of various tools with the data in MISP such as IDSes,
firewalls, host scanners, etc. Pushing invalid indicators to those tools
could have unexpected results.

Also, most of the time when invalid data pops up in MISP it's because of
issues such as copy-pasta failures and so on.

**Comment by thomai** [comment]
I see! Then I think the best way would be to decline the add/update action for the whole event with a 4xx status code.

**Comment by iglocska** [comment]
Yup, looking into cleaning it up. The plan is to just not save any data when the package is partially invalid and instead return the validation errors. I'll keep you updated in here on how it's progressing!

**Comment by thomai** [comment]
Excellent. Thanks for the quick answers.

**Comment by Rafiot** [comment]
@iglocska is it fixed?

**Comment by Rafiot** [comment]
Fixed.
