### ISSUE TITLE
STIX2 v. 1.4.0 requiers at least six v. 1.13.0

### ISSUE THREAD

**Issue by marcnil815** [MISP/MISP#6076]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.4 LTS
| PHP version               | PHP 7.2.24-0ubuntu0.18.04.6
| MISP version / git hash   | v2.4.128 (d14ce7de709cdde3ecc9433e38e14c682894e88a

### Expected behavior
STIX2 imports corretly

### Actual behavior
STIX2 doesn't import.

### Steps to reproduce the behavior
Upgrade to latest .128 release.
Check diagnostics page, STIX2 not found.

Start python shell in MISP .venv
>>> import six
>>> six.__version__
'1.12.0'

>>> from six.moves.collections_abc import Mapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'six.moves.collections_abc'

The collections_abc  import was added to STIX2 in version 1.4.0 when creating the versioning.py file (28.05.2020).
This requires a six version of 1.13.0
https://github.com/benjaminp/six/commit/0dc54ead62c7fb06edabf1ff22fb71c0c6d958e1#diff-ec00a44e8e04e1bb5d34c296bdd1e9eb

**Comment by marcnil815** [comment]
Force upgrade of six library fixed this.
The problem is of course that dependencies are not updated unless it is required. The STIX2 library fails to include a requirement that six should at least be version 1.13 so it fails to update it. Cybox for instane is happy with six 1.12.

[edit: typo]

**Comment by chrisr3d** [comment]
Python libraries are not automatically updated with MISP, but right now if you update your stix2 library you should get the latest six version as well.
You can check if you have the recommended version in the diagnostic page.

```
cd /var/www/MISP
sudo -H -u www-data git pull origin 2.4
sudo -H -u www-data git submodule update --init
cd cti-python-stix2
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .
```
Alternatively you can check [how to update your python dependencies here](https://www.circl.lu/doc/misp/updating-python/#updating-the-python-dependencies)
