### ISSUE TITLE
Reset Auth Key through UI

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#6082]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       |  Win10
| PHP version               | 7.3.14-1~deb10u1
| MISP version / git hash   | v2.4.126, 95d81bd0f36f4c7bcf71757a5bbe5f1a7617b954
| Browser                   | Chrome

### Expected behavior
When I click the "Reset Auth Key" button/link in the GUI, it should be reset for that user.
![image](https://user-images.githubusercontent.com/1122246/86347915-38423700-bc5f-11ea-943b-11387a5f9b31.png)

### Actual behavior
I get the following error when I click that link with debug mode enabled:
![image](https://user-images.githubusercontent.com/1122246/86347969-53ad4200-bc5f-11ea-9abe-23b3c3913a64.png)

### Steps to reproduce the behavior

1. Go to edit page of a user
1. Click the "Reset Auth Key" link

**Comment by SteveClement** [comment]
Tested on latest, same result.
