### ISSUE TITLE
Issue with updating object templates

### ISSUE THREAD

**Issue by StefanKelm** [MISP/MISP#6083]
2.4.128 (and a fresh git pull): when editing objects we sometimes get notified of new object templates:

![obj1](https://user-images.githubusercontent.com/25325656/86364379-63855000-bc78-11ea-974a-f5dc0da5d2da.jpg)
![obj4](https://user-images.githubusercontent.com/25325656/86364412-6e3fe500-bc78-11ea-9f02-2ebbe66895ec.jpg)

Klicking on _Update template_ seems to be successful:
![obj2](https://user-images.githubusercontent.com/25325656/86364501-8adc1d00-bc78-11ea-9cea-535c740c4f88.jpg)

However, after _Submit_ and then _Create new object_ the template apparently has not been updated when I try to edit the same object again (or the information being displayed is incorrect). And yes: "All object templates are up to date already." :-)

(maybe related to #5184 ?)

PS: What's the meaning of the following?
![obj3](https://user-images.githubusercontent.com/25325656/86364901-12299080-bc79-11ea-878d-05e0c142af29.jpg)

**Comment by mokaddem** [comment]
Thanks for the report @StefanKelm!
This should be fixed. Let us know if you spot other issues!

In regards to your question, this is a widget to help you perform the update (or merge) if fields disappeared or if it can't be merged automatically.
In your case, everything was done automatically. You can see an example of a non-trivial merge here https://github.com/MISP/MISP/pull/4545
I rephrased the title `Pre-update object's template`  into `Current Object state on older template version`. I hope it will be less confusing. But if you have a suggestion for another wording, feel free to share :)

**Comment by StefanKelm** [comment]
This is awesome! Thanks so much @mokaddem for the explanation and the fix!
