### ISSUE TITLE
An Internal Error Has Occurred

### ISSUE THREAD

**Issue by kpiersonSEC** [MISP/MISP#609]
I am receiving the following error on the homepage:
   "An Internal Error Has Occurred."
    "Error: An Internal Error Has Occurred."

when I navigate to /user/login I am seeing this error:
     "Not Found"
     "Error: The requested address '/user/login' was not found on this server."

I made sure "a2enmod rewrite" is enabled, I am using the default_ssl .conf for apache from the INSTALL folder, and I have combed through the installation guide. Any help would be greatly appreciated.

**Comment by iglocska** [comment]
MISP by default is not very verbose about errors through the interface, but the reason for the error is logged. Could you have a look at /var/www/MISP/app/tmp/logs/error.log and paste the stack trace of the error here?

**Comment by kpiersonSEC** [comment]
As you requested:

Request URL: /user/login
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResp$
#1 {main}
2015-08-21 14:25:39 Error: [MissingControllerException] Controller class UserController could not be $
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/login
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResp$
#1 {main}

**Comment by iglocska** [comment]
It should be users/login not user/login, but you should get redirected there anyway. 

What happens if you simply navigate to https://<mymisp>/ ?

**Comment by kpiersonSEC** [comment]
So the issue may stem from mysql. This is the stack for https://

2015-08-21 14:37:56 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'Selected driver is not enabled',
  'enabled' => false,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3617): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3644): Model->setSource('logs')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1387): Model->getDataSource()
#5 /var/www/MISP/app/Plugin/Assets/models/behaviors/LogableBehavior.php(113): Model->schema()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): LogableBehavior->setup(Object(User), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('User', Array)
#9 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#10 [internal function]: AppModel->__construct(Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#12 /var/www/MISP/app/Plugin/Assets/models/behaviors/LogableBehavior.php(109): ClassRegistry::init('User')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): LogableBehavior->setup(Object(ShadowAttribute), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('ShadowAttribute', Array)
#16 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#17 /var/www/MISP/app/Model/ShadowAttribute.php(284): AppModel->__construct(Array, NULL, NULL)
#18 [internal function]: ShadowAttribute->__construct(Array)
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(741): ClassRegistry::init(Array)
#21 /var/www/MISP/app/Controller/AppController.php(228): Controller->loadModel('ShadowAttribute')
#22 /var/www/MISP/app/Controller/AppController.php(192): AppController->_getProposalCount()
#23 /var/www/MISP/app/Controller/EventsController.php(36): AppController->beforeFilter()
#24 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#25 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#27 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#28 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#29 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#30 {main}

**Comment by iglocska** [comment]
Excellent, that should make it a lot easier. 

sudo apt-get install php5-mysql

should solve your issue hopefully. Let me know if it doesn't!

**Comment by kpiersonSEC** [comment]
Wonderful! That did the trick. Thank you for all your help.

**Comment by iglocska** [comment]
Great news, closing the ticket then. If you run into anything else let me know.
