### ISSUE TITLE
Download samples API passing an hash always returns all the samples in the instance

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#610]
Query: 
```
{'request': {'hash': "<existing MD5 hash>", 'allSamples': false}}
```

**Comment by iglocska** [comment]
What the hell, looking into it

**Comment by Rafiot** [comment]
actually, it always returns all the samples, with a valid hash or without

**Comment by iglocska** [comment]
Turned out to be a really stupid mistake, should be good now, just git pull. Let me know if you find anything else!

**Comment by Rafiot** [comment]
Excellent, thank you :)
