### ISSUE TITLE
feed ingested with sharing group as distribution 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#6101]
The feed distribution currently only allows a distribution of `all communities`, `this community` , `connected community` and `my organisation only`. It is not possible to select a `Sharing group`.

This request is about the addition of this feature. 

Why? In some cases you can have a feed provided as commercial subscription. Multiple  (MISP-level) organisations within your company might be eligible to see that information. Ingesting it as `my org only` would therefore prevent eligible organisations to see the data.

**Comment by lfortemps** [comment]
It seems to have been fixed in the latest version. Sharing Group can be selected for a feed distribution.

**Comment by Hestat** [comment]
This bug appears to have returned in  v2.4.148 (3822521d2ceeb7dcccaf53ea3052a8a2209f0433) as I'm trying to create a new feed with a Sharing group as the distribution, but after selecting Sharing Group nothing allows setting the group in the Feed Create/Edit menus.

**Comment by rvanderhorst** [comment]
> This bug appears to have returned in v2.4.148 ([3822521](https://github.com/MISP/MISP/commit/3822521d2ceeb7dcccaf53ea3052a8a2209f0433)) as I'm trying to create a new feed with a Sharing group as the distribution, but after selecting Sharing Group nothing allows setting the group in the Feed Create/Edit menus.

Can confirm, it is not possible to select a 'Sharing Group' as this field isn't visible after selecting 'Sharing Group'. Can anyone confirm that this is fixed in the latest release (2.4.158)?
