### ISSUE TITLE
Edit view for shadow attributes is missing

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#6102]
Since the update to 2.4.128. Users are experiencing issues when they want to "Propose edit" on an attribute. This brings them to the URL misp.example.org/shadow_attributes/edit/<attribute_id>.

This triggers a 500 with message: view file ShadowAttributes/edit.ctp is missing.

I saw that this view was recently removed at commit https://github.com/MISP/MISP/commit/df6916a312e2f051b118458106238fcb199c0741

### Expected behavior

Allow users to propose an edit on an attribute

### Actual behavior

Application Crash

### Steps to reproduce the behavior

As a regular user, go to an event and next to one of the attribute, click the "propose edit" button (icon is a text bubble)

**Comment by iglocska** [comment]
Re-added, nice catch, thanks!
