### ISSUE TITLE
Invalid Event - Event not found (Sharing Group Permissions Issue)

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#6107]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.128, 6dca14a6b06b7b2be455c8700690f8828696716d
| Browser                   | Chrome

### Expected behavior
MISP Sync set-up with an external server applying sharing group rules. The local (host) organisation is a member of this sharing group, hence receives the events.

All users that are members of the local organisation should be able to view the sync events.

### Actual behavior
The sync successfully creates/updates the events from the remote server to the local server.

All users as members of the local organisation are able to see the sync events on the Events homepage, but receive an "Invalid Event" error when attempting to open the event.

Only site admins can view the entire event - suggesting this is a permissions error in which org users can see the event on the event page, but not the individual event details.

None of the sync settings/sharing group permissions appear to have changed. An update to the server (from 2.4.127 to 2.4.128) was performed earlier this week.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/48736003/87144830-4c5de800-c2a0-11ea-9e34-e06e20ea1166.png)
![image](https://user-images.githubusercontent.com/48736003/87144629-f5f0a980-c29f-11ea-8be0-6977404f7fad.png)
![image](https://user-images.githubusercontent.com/48736003/87144698-16206880-c2a0-11ea-9b9d-14e5720b369b.png)

**Comment by mokaddem** [comment]
Linked to #6033
