### ISSUE TITLE
Can I set default publish parametr on "1" ?

### ISSUE THREAD

**Issue by WingerHusar** [MISP/MISP#6111]
Hi,
I would like to have default publish parametr as "1" . I don't want do anything because i need to received event and immediately send to other resources.
It is possible ?

**Comment by mokaddem** [comment]
Hey,
I'm not sure to understand what you want to do.
If you receive a published event and you have valid connections with other instances, it sync will happen automatically.

**Comment by SteveClement** [comment]
@WingerHusar the best would be to automate this with PyMISP or, as Sami mentioned, on sync it just happens automagically.

**Comment by enjeck** [comment]
> Hey,
> I'm not sure to understand what you want to do.
> If you receive a published event and you have valid connections with other instances, it sync will happen automatically.

> @WingerHusar the best would be to automate this with PyMISP or, as Sami mentioned, on sync it just happens automagically.

@WingerHusar Hey. Did these suggestion help you?
