### ISSUE TITLE
Correlation engine improvement - caching

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#612]
After a quick discussion about the correlation table with @Rafiot 

~~~
+----------------+--------------+------+-----+---------+----------------+
| Field          | Type         | Null | Key | Default | Extra          |
+----------------+--------------+------+-----+---------+----------------+
| id             | int(11)      | NO   | PRI | NULL    | auto_increment |
| value          | text         | NO   |     | NULL    |                |
| 1_event_id     | int(11)      | NO   | MUL | NULL    |                |
| 1_attribute_id | int(11)      | NO   | MUL | NULL    |                |
| 1_private      | tinyint(1)   | NO   |     | 0       |                |
| event_id       | int(11)      | NO   |     | NULL    |                |
| attribute_id   | int(11)      | NO   | MUL | NULL    |                |
| org            | varchar(255) | NO   |     | NULL    |                |
| private        | tinyint(1)   | NO   |     | NULL    |                |
| date           | date         | NO   |     | NULL    |                |
| info           | text         | NO   |     | NULL    |                |
+----------------+--------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

~~~

The table can be easily expressed in a series of sets in a key-value store that could be used a cache engine. Here is a potential representation:

set hash(value) => set of (uuid)
set uuid => set of hash(value)
k/v hash(value) => value of (value)

hash uuid => info => value of (info)
                 => org => value of (org)

set distribution => set of (uuid)
(for each group of distribution / private) - a check of correlation visibility can be done with SDIFF

**Comment by adulau** [comment]
Initial experiment available https://github.com/MISP/misp-redis-datastore

**Comment by elhoim** [comment]
Nice idea! This can also be useful for bulk verification cases, e.g. you hash all the files of a machine and you throw them at MISP to see if they are known.

**Comment by adulau** [comment]
Yes. That's the idea. The web services has been added:

https://github.com/MISP/misp-redis-datastore/blob/master/backend/webservice.py

The idea is to do fast lookup of attributes and check if these are known by MISP. If yes, you'll get back the UUID and can do an URL to MISP for the user having an access.

**Comment by Rafiot** [comment]
This will be supported by misp-redis-datastore, closing.
