### ISSUE TITLE
How to update stix libary

### ISSUE THREAD

**Issue by qanniej** [MISP/MISP#6122]
Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 LTS
| MISP version / git hash   | 2.4.129
| Browser                   | Chrome

### Support Questions

Hello, I'm getting error in MISP that my STIX Library version expected is > 1.2.0.9 but currently it's 1.2.0.8 

I ran the commands listed in MISP guide as mentioned below but STIX is not updating for some reason. 

# Update the STIX dependencies (PICK THE ONE.S YOU NEED TO UPDATE)
# STIX
cd /var/www/MISP/app/files/scripts/python-stix
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .

any idea what could be causing the issue? 

### Logs, screenshots, configuration dump, ...
![stix issue2](https://user-images.githubusercontent.com/53413533/87489780-806f3b00-c609-11ea-8e6c-6e857dea9821.jpg)
![stix issue](https://user-images.githubusercontent.com/53413533/87489617-18205980-c609-11ea-8cf7-e6156b429f73.jpg)

**Comment by RichieB2B** [comment]
Did you do a "git pull" inside the python-stix directory before the install?
