### ISSUE TITLE
 Requested URL /users/login was not found

### ISSUE THREAD

**Issue by Waseem-farooqui** [MISP/MISP#613]
I did fresh installation of MISP on running the webpage I am getting **404 Not Found** with **The requested URL /users/login was not found on this server.** detail.
I don't have any folder with `users` in `app` directory.
I have not specified username or password in any configuration file because of default credentials.
Where I am wrong ?
Don't see any thing in error logs.

**Comment by iglocska** [comment]
MISP does URL rewriting, the actual login action is located in /var/www/MISP/app/Controller/UsersController.php with the rendered view being in /var/www/MISP/app/View/Users/login.ctp

Make sure that you have mod rewrite enabled by running the following:
a2enmod rewrite

MISP has its own error logs, could you check in /var/www/MISP/app/tmp/logs/error.log if you have anything?

**Comment by Waseem-farooqui** [comment]
I have both `login.ctp` and `UsersController.php` and also `a2enmod rewrite` enabled and there is noting in error log.

**Comment by iglocska** [comment]
Hmm that is odd, did you set the correct apache configuration file pointing
the webroot to the MISP webroot (/var/www/MISP/app/webroot)?

Also, when you get the 404 error message, do you get it within MISP (do you
see the MISP UI) or is it your browser's standard 404 page?

**Comment by Waseem-farooqui** [comment]
Its a browser's Standard 404, One thing I have changed while installation is the location of MISP directory its in `/var/www/html/` and I did the whole installation according also change the apache configuration according.

**Comment by iglocska** [comment]
That should be fine as long as the apache file reflects that as you've
mentioned.

Could you paste your .conf file in here (with anything you don't want
shared redacted of course)?

Also, a silly question but it can happen: did you restart apache after
enabling mod rewrite and enabling the new configuration?

**Comment by Waseem-farooqui** [comment]
Ohhh I got it, Sorry you was right it was problem with my **apache configuration** file I missed `/webroot` in **DocumentRoot**.
Thankyou very much @iglocska for your time.

**Comment by iglocska** [comment]
Excellent, glad it works now! :) Let me know if you run into any other issues!
