### ISSUE TITLE
Not all attributes are returned from automation api when using returnType suricata

### ISSUE THREAD

**Issue by jmakar** [MISP/MISP#6133]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.120

### Expected behavior

Automation queries with returnType suricata should have the same attributes as those with returnType json.

### Actual behavior

Only some attributes are returned.

### Steps to reproduce the behavior

I don't know the root cause (so some of this may be unnecessary) but it has occurred with the following:
- create an event with some attributes
- publish the event
- add more attributes

Now only some attributes will appear with returnType json, not necessarily those added publishing.  See the following example and note the timestamps:

### Logs, screenshots, configuration dump, ...

```
$ curl -s -H "Authorization: $auth" -H 'Content-Type: application/json' -d '{"returnFormat":"suricata","eventid":"264"}' 'https://$server/events/restSearch' | grep events/view/264
alert ip 5.31.7.79 any -> $HOME_NET any (msg: "MISP e264 [tlp:amber] Incoming From IP: 5.31.7.79";   classtype:trojan-activity; sid:6699907; rev:1; priority:1; reference:url,https://$server/events/view/264;) 
alert ip 23.83.128.249 any -> $HOME_NET any (msg: "MISP e264 [US,tlp:amber] Incoming From IP: 23.83.128.249";   classtype:trojan-activity; sid:6699917; rev:1; priority:1; reference:url,https://$server/events/view/264;) 
alert ip $HOME_NET any -> 205.134.250.206 any (msg: "MISP e264 [tlp:amber] Outgoing To IP: 205.134.250.206";   classtype:trojan-activity; sid:6699967; rev:1; priority:1; reference:url,https://$server/events/view/264;) 

$ curl -s -H "Authorization: $auth" -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"returnFormat":"json","eventid":"264"}' 'https://$server/events/restSearch' | jq -c '.response[0].Event.timestamp,.response[0].Event.publish_timestamp,[.response[0].Event.Attribute[] | [.timestamp,.value]]'
"1594273904"
"1594273921"
[["1594273355","5.31.7.79"],["1594273882","23.83.128.249"],["1594273355","https://benson-jack.esclick.me"],["1594273901","34.249.143.122"],["1594273904","52.209.238.55"],["1594273355","https://netlabs.mx"],["1594273356","205.134.250.206"]]
```

**Comment by mokaddem** [comment]
Lots of export require the event to be in a ready-to-use state which is usually described by the publish flag.
Also, depending on the export chosen, the `to_ids` flag must be set on the attribute to be exported
