### ISSUE TITLE
Redis Memory Usage

### ISSUE THREAD

**Issue by nbyt3** [MISP/MISP#6139]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.128

27551 Events
303470 Attributes

### Actual behavior
Redis is immediately consuming 57 percent of memory of the MISP instance around 19GB of 32GB of Memory. 

### Steps to reproduce the behavior
Upon reboot of MISP Redis consumes memory. Causes issues with search against MISP using PyMISP due to memory constraints. 

### Logs, screenshots, configuration dump, ...
max_execution_time (7200)… OK (recommended: 300)
memory_limit (8048M)… OK (recommended: 2048M)
upload_max_filesize (500M)… OK (recommended: 50M)
post_max_size (500M)… OK (recommended: 50M)

2020-07-21 01:06:50 Error: Fatal Error (1): Allowed memory size of 8438939648 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 1616]
2020-07-21 01:06:50 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch

**Comment by RichieB2B** [comment]
There must be a lot of data in redis. You can clear out everything using:
```
redis-cli flushall
```

**Comment by nbyt3** [comment]
Thank you for the quick reply. That command indeed flushed the redis cache memory.

**Comment by chrisinmtown** [comment]
Maybe @nbyt3  you would like to close this issue, if the problem has been resolved by clearing the cache?

**Comment by nbyt3** [comment]
Yes we can close this issue out. The flushall command worked to clear the cache.
