### ISSUE TITLE
Proposal model at event level

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#614]
A nice to have would be to allow users to create proposal at the event level (just like we do for the attributes) especially for the following "attributes":
- Threat Level
- Analysis
- Description
- Date

Maybe something for 2.5

**Comment by adulau** [comment]
I modified the release to release-2.4-hotfix because it's becoming a recurring requests for various users.

**Comment by adulau** [comment]
@iglocska Just wondering about the complexity regarding this one. I suppose the major complexity lies in the sync proposal.

**Comment by iglocska** [comment]
Definitely. We can implement it, but we should lump it together with the other stuff that will break the sync.

**Comment by adulau** [comment]
Proposal needs some additional rework for tags or alike. I'll close this one.
