### ISSUE TITLE
Strange behavior when fetching events by UUID

### ISSUE THREAD

**Issue by patriziotufarolo** [MISP/MISP#6145]
Hi,
I would like to report that fetching events  by UUID now causes stranges behaviors resulting in: 
- memory exhaustion
- fetching event with id=1
- error 500
when a non-existent event's UUID is provided.

This happens both through web UI and APIs/PyMISP library, because of changes introduced with commit decbb360ea9fdfc4e4416b724615b1a51132bec5

Could you please check?

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Not relevant
| OS version (client)       | Not relevant
| PHP version               | 7.3
| MISP version / git hash   | 2.4.129, 4056f3ea00d9d25ac546ec5d2784ad72fbcd7b9c
| Browser                   | Not relevant

### Expected behavior
"Invalid event" should appear

### Actual behavior
MISP returns the event with ID=1 or crashes

### Steps to reproduce the behavior
Go to /events/view/'randomly-generated-non-existent-event-uuid`

**Comment by JakubOnderka** [comment]
Thanks for providing exact commit. It should be fixed in latest 2.4 branch. Can you check it?

**Comment by patriziotufarolo** [comment]
Hello Jakub,
thanks for fixing this bug in a few hours :) 
I can confirm that the problem is solved. 

Regards,
Patrizio
