### ISSUE TITLE
How to sync my MISP instance with a commercial one

### ISSUE THREAD

**Issue by vandir** [MISP/MISP#6149]
Hi all,

I've bought a premium subscription and I would like to automatically download all the events they create.

They provided me with a the Base URL and the Authkey so I've created a Sync Server in this way:

![Capture](https://user-images.githubusercontent.com/14293194/88635318-d2a76600-d0b7-11ea-95e6-89c1c6b4c721.JPG)

After that, I can correctly navigate the remote instance and manually fetch the events but how can I do that automatically?

**Comment by iglocska** [comment]
You can schedule the pull process using cron jobs using the `MISP/app/Console/cake Server pull [user_id] [server_id] [full|update]` CLI command. For more similar commands, have a look at the /events/automation page in your MISP.

**Comment by vandir** [comment]
I've tried that command (with "update" param) but I obtain the following output:

![Capture2](https://user-images.githubusercontent.com/14293194/88636939-d5a35600-d0b9-11ea-9a3e-88001b864e9f.JPG)

Should I run the command with "full" param before "update"? The problem is that the remote sync has millions of events.
