### ISSUE TITLE
Create disk space by clearing old events

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#6152]
Questions | Answers
-- | --
Type of issue | Bug
OS version (server) | RHEL, with MISP running on a docker container..
OS version (client) | MacOS, Win10,
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

We would like to clear some disk space by clearing old events. Looking at the MySQL database we noticed that the Correlations table is taking a lot of space and we want to start downsizing  this table. Is there a way to safely delete entries on this table other than a complete delete? Should we delete entries in the events table and will it translate to making deletions on the correlations table? Is there a mysql script we can run?

Please advise

thanks

Doug

**Comment by adulau** [comment]
The easiest is to truncate the correlation table and trigger the correlation again (https://<YOURMISP>/pages/display/administration).
