### ISSUE TITLE
Local feeds failing to cache

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#6155]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.6
| OS version (client)       | RHEL, Win10
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.129 (dcd372bd93ae8328284a8fe88a2d87c6fe8c3d75)

### Expected behaviour
Clicking cache on feed should change the cache status from Not cached to the time of last cache.

### Actual behaviour
When manually clicking cache on a feed the job fails and progress remains in queued, status of cache remains Not cached

### Steps to reproduce the behaviour
Add local feed with cache enabled, screenshot of feed configuration is attached.

### Logs, screenshots, configuration dump, ...

Job status:
![image](https://user-images.githubusercontent.com/68913145/88684525-e3be9a00-d0ec-11ea-81b0-5e9681888a7e.png)

Feed configuration:
![image](https://user-images.githubusercontent.com/68913145/88685672-17e68a80-d0ee-11ea-8d23-d0a8bbfefecb.png)

resque-worker-error.log  produces the following error when attempting a cache

Error: Argument 3 passed to Feed::__cacheFreetextFeed() must be an instance of HttpSocket, boolean given, called in /var/www/MISP/app/Model/Feed.php on line 1126
#0 /var/www/MISP/app/Model/Feed.php(1126): Feed->__cacheFreetextFeed(Array, Object(Redis), false, '13')
#1 /var/www/MISP/app/Model/Feed.php(1095): Feed->__cacheFeed(Array, Object(Redis), '13')
#2 /var/www/MISP/app/Console/Command/ServerShell.php(326): Feed->cacheFeedInitiator(Array, '13', '70')
#3 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->cacheFeed()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#9 {main}

**Comment by JakubOnderka** [comment]
Can you please try to checkout this PR https://github.com/MISP/MISP/pull/6156 and check if is it fixed?

**Comment by ghost** [comment]
That has fixed the problem, thanks.
