### ISSUE TITLE
Publish Timestamp set to '0' when using REST API

### ISSUE THREAD

**Issue by JamesSOC080** [MISP/MISP#6160]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.129, 1d6517c7a4140bde42976f1bf3be40a126a59222
| Browser                   | Chrome

### Expected behavior
When using the REST API, either through curl CLI or the REST Client, to publish an event should publish the event and set a timestamp (defaulting to the current time).

### Actual behavior
When using the REST API, either through curl CLI or the REST Client, to publish an event, the event will show as published but the timestamp will be set to '0'. 

Consequently, when searching for events based on the published timestamp (e.g. events published in the last 1 hour), the events will not return (in effect - they act as if they are **unpublished**).

### Steps to reproduce the behavior
Example REST query and result:

Query to publish event 13333:
curl \
 -d '{"published":"1"}' \
 -H "Authorization: <redacted>" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 -X POST https://<redacted>/events/edit/13333

Results:

{
    "Event": {
        "id": "13333",
        "orgc_id": "1",
        "org_id": "1",
        "date": "2020-07-29",
        "threat_level_id": "4",
        "info": "<redacted>",
        "published": true,
        "uuid": "e3b5d26c-2d6d-40b6-85c1-58cba6551064",
        "attribute_count": "4",
        "analysis": "0",
        "timestamp": "1596107780",
        "distribution": "1",
        "proposal_email_lock": false,
        "locked": false,
        **"publish_timestamp": "0",**
<rest of result removed>

### Logs, screenshots, configuration dump, ...
Before the query - showing the event (which was originally published by a script using the publish query):
![image](https://user-images.githubusercontent.com/48736003/88916680-66b33200-d25e-11ea-8250-5ce33eb3686d.png)

And after the query:
![image](https://user-images.githubusercontent.com/48736003/88917108-230cf800-d25f-11ea-9a2c-f5ce8b5bbe2e.png)

**Comment by mokaddem** [comment]
Hello,
I'm not sure to get what's wrong with the screenshot you sent.
For the 2nd picture, I can see that the event is published and the `Last change` field is updated.

For the `publish_timestamp` issue, could you go fetch the JSON again and check this field?
You can do it via the API or if you append `.json` at the end of the URL like this:
```
https:///events/edit/13333.json
```
Thanks

**Comment by JamesSOC080** [comment]
Hi there,

So the issue in the screenshot is to do with the 'published' field - it is showing as 'Yes N/A' - meaning that, whilst published, it does not have a timestamp set (as shown in the JSON "publish_timestamp": "0",". 

When published correctly (e.g. manually through the UI), it will appear in the UI as (for example) 'Yes (2020-07-30 12:05:23)"

This appears to have only happened recently, as we use the MISP42Splunk app which pulls back events based on the published timestamp and was working fine until we upgraded to 2.4.129. After this, when publishing events via the REST API, the events still publish but without setting a published timestamp.

The json for an event with the published date set correctly looks like:

{
    "Event": {
        "id": "8433",
        "orgc_id": "2",
        "org_id": "1",
        "date": "2020-02-18",
        "threat_level_id": "1",
        "info": "<redacted>",
        "published": true,
        "uuid": "5e4bc8e3-74c8-4e60-a9a3-26130a09d489",
        "attribute_count": "23",
        "analysis": "2",
        "timestamp": "1596036316",
        "distribution": "4",
        "proposal_email_lock": false,
        "locked": true,
        **"publish_timestamp": "1596036368",**
<rest of json removed>

As such, it appears that amending the published flag through the API is no longer also setting a publish_timestamp (or is setting it to 0).

**Comment by JakubOnderka** [comment]
The correct way how to publish event is trough `publish` API. See https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.publish

**Comment by enjeck** [comment]
> The correct way how to publish event is trough publish API. See https://pymisp.readthedocs.io/en/latest/modules.html#pymisp.PyMISP.publish

@JamesSOC080 Did you use the `publish` API? Did it help?
