### ISSUE TITLE
Request black-holed when logging in on page that's open too long

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#6165]
I searched for this kind of bug in the issues but couldn't find something related immediately.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian.
| OS version (client)       | Windows 10
| PHP version               | 7.3.19-1~deb10u1
| MISP version / git hash   | 2.4.129, ded8ed50a5c8ceb757111d720faa062d3762e6e5
| Browser                   | Brave or Chrome

### Expected behavior
When I don't use MISP for too long, the session ends and I go back to the login screen which is perfect. But then the browser sometimes stays open for hours on end and when then I come back to my laptop, with the MISP login screen still open. When I try to login then, I should actually login on the system and see the main page.

### Actual behavior
But when this happens, it doesn't login and just shows this page with the error:
![image](https://user-images.githubusercontent.com/1122246/89101990-5be6d180-d405-11ea-9a43-6e5d190ecd04.png)

Then I have to remove the /users/login and go to the main link which will show me the login page again. When I login then, it works.

### Steps to reproduce the behavior

1. Wait long enough for the session to end
2. Wait another couple of hours (for me it's mostly when my system stays online at night and I try to login in the morning so I didn't touch that page for over 12 hours. I don't know how long it actually takes before this happens.
3. Try to login
4. You'll see the error page
5. Remove /users/login in the address bar so you only have the main link like https://misp.circl.lu left and hit enter to go to that link.
6. Login again and it should work now.

**Comment by mokaddem** [comment]
Hey,
This issue should now be solved with the merge of https://github.com/MISP/MISP/pull/6161.
If after updating to the latest version you still experience this behavior (or similar) could you please update this issue?
I'm closing it in the meantime.
Thanks in advance!
