### ISSUE TITLE
Proposal can be accepted multiple times and then cannot be deleted

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#6166]
# Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.129

### Expected behavior
- Proposals cannot be accepted/inserted multiple times.
- If accepted multiple times, it is possible

### Actual behavior
- Proposal was accepted multiple times.
- Cannot delete the created attributes (not any of them).

### Steps to reproduce the behavior
- Use org A to create and publish an event with some attributes.
- Use org B to create a proposal with the same value as one of the existing attributes but using a different type.
- Use org A to click multiple times on 
The multiple insertion might be due to the background processing of the deletion of proposal + creation of attribute.

Event 63120 on MISPpriv is the event that triggered this bug report (created attributes 10027975 & 10027976). The multiple values created are 100% me clicking multiple times.

**Comment by mokaddem** [comment]
Hey @elhoim,
I was able to reproduce (via API) the double proposal acceptance and a fix for preventing UUID duplication is on its way.
However, it's concerning that you triggered it via the interface as the `accept` button is using a protected form (and there is no background job for this feature).
Was the proposal accepted on MISPPriv or on an instance with the CRSF protection disabled?
