### ISSUE TITLE
Easily allow to open multiple tabs to review proposals

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#6167]
As a data publisher using MISP, I want to be able to open multiple proposals for review in different tabs from the "view proposals" page so that I can quickly and efficiently review multiple of them.

For the moment it is not possible, because the link seem to be generated by Javascript and it is only possible to left click on a proposal to go to a page instead of right cliking and then opening a new tab.

**Comment by mokaddem** [comment]
Fixed with commit https://github.com/MISP/MISP/commit/f5b8dd687a9c7b7359678429a4337d43a3cac94c.
Thanks for the report!
