### ISSUE TITLE
Automatically apply admin tools according to current hotfix level

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#617]
This might be considered a variation of #122 .
The idea is as follows:
- Store the "effective" hotfix level also in DB (or other file)
- Have a generic upgrade script to run after git pulling the latest code
- Check which hotfix level of code was checked out from VERSION.json, if this higher, then apply all necessary admin scripts.
- Update the "effective" hotfix level in DB

For example after hotfix 115 (from version 2.3 - https://github.com/MISP/MISP/commit/8ab674e1df57c24ad5fc39b04c5f554e8290c2f7), apply the added administrative tool *removeDuplicateEvents*.

**Comment by iglocska** [comment]
Yeah this is something we definitely need. The one thing that needs to be figured out is what should trigger the check (any time a user loads a page? A background worker running a check every x hours?)

**Comment by elhoim** [comment]
A script to be run by the admin upgrading his install?
So something like this *git pull && /var/www/MISP/app/Console/upgrade-internals.sh* is possible
Then you don't have to manage the hell of a delayed run, and multiple code bases (before and after upgrade).

**Comment by iglocska** [comment]
That is true, that's an easy fix!

**Comment by elhoim** [comment]
Kind of what i was thinking: [DB migrations](http://bakery.cakephp.org/2012/11/24/Versioned-DbMigrations.html)

**Comment by iglocska** [comment]
That is indeed a neat way of doing it and it solves a part of what the upgrade scripts do. I'll look into building that into the upgrade system in the future.

**Comment by adulau** [comment]
Auto-updates was introduced in MISP 2.4 sometime ago. So I suppose we can close this issue.
