### ISSUE TITLE
Block or warn event based on custom blacklist

### ISSUE THREAD

**Issue by BrunoMCBraga** [MISP/MISP#6173]
### Support Questions
Hello guys, my question is simple and so i will go to the point. I am aware of correlation of events with warninglists and even feeds.

However, what i would like to have is a means two:
- Create an internal black list of IPs that a Research Team as deemed benign
- Block or warn other researcher when he is creating some event with a blacklisted IP/domain/hostname

I have tried to use event block rules with:
```
{
"type":"ip-src",
"value":"[SOME_IP]"
}
``` 
but i am still able to add this IP to the event. Any ideas on how to implement what i mentioned above on MISP?

**Comment by mokaddem** [comment]
Hello,
*Warninglists* have been designed for this purpose.
You have to create a new *warninglist* containing all the IPs you want to ignore/get notified. Doing so will allow you to:
- Filter out these IPs if they are contained in an event by passing the `enforceWarninglist` parameter
- Get a UI notification if these IPs are contained in an event and have the `to_ids` flag set
Note that it will not prevent you to add these IPs to an event.
I hope this helps

**Comment by BrunoMCBraga** [comment]
It would be great to have warninglists active with or without IDS flag set. I may want to have MISP to keep intel but not use it for signatures at least directly. Also, if during some campaign i see google being used, i will add it to the event data but i know beforehand that it is legit. MISP should confirm that for me.

**Comment by mokaddem** [comment]
> I may want to have MISP to keep intel but not use it for signatures at least directly

That can be achieved by filtering data or by using the warninglists

> MISP should confirm that for me

I'm not sure to get what you want because from what I understand, that's exactly what MISP already do.

Could it be that you are asking for a feature request for another kind of list that would highlight (or notify) users if the value  being saved is contained in the list?
