### ISSUE TITLE
ZMQ fails to publish full event if MISP.org is invalid

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/MISP#6174]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | N/A
| OS version (client)       | N/A
| PHP version               | N/A
| MISP version / git hash   | v2.4.129 (5d8f32a955af427333198814cff5f9c85cefbd3d) 

### Expected behavior

See my comment in #5702 for the full details, but the TL;DR is that it is expected that publishing an event under any circumstances should also send the full event's worth of data (misp_json) to the ZMQ listener.

### Actual behavior

All ZMQ features work as expected, except for sending the full event's worth of data (misp_json) to the listener. 

I was able to trace this back to https://github.com/MISP/MISP/blob/e41ffb5c9ed2d436244a2f2d49f0c6fc8d0f17b1/app/Model/Event.php#L4380 where it appears to require a valid hosting organization in order to proceed. I'm not sure if this is by design, but considering all other ZMQ features work independently of this requirement, I feel that the misp_json notifications should work the same way. 

At the very least, something should be presented to the user (perhaps in the settings menu?) to indicate if MISP.org is not tied to a valid/known organization then the ZMQ/Kafka publishing will not work properly.

During testing, under Organizations I had changed the default ORGNAME to MYORG, but in the MISP settings I had left it as ORGNAME or MYORG-TEST since that setting only references it as being used as part of an email notification's subject line:
`"The organisation tag of the hosting organisation. This is used in the e-mail subjects"`

However, if it is not set to a valid organization that the MISP instance already is aware of, the final event in its entirety (misp_json) will never be sent to ZMQ or Kafka.

This issue affects the GUI `Publish Event` and `Publish (no email)` side bar links, as well as attempting to publish using PyMISP.

### Steps to reproduce the behavior

- Make sure your ZMQ server is running and you are listening to its feed.
- Change your MISP.org setting to an invalid org (e.g. ORGNAMEXYZ).
- Attempt to publish an event using any option *EXCEPT FOR* `Publish event to ZMQ` (that option calls the pubSubTool directly and bypasses the org check in Event.php).
- Watch the ZMQ messages send misp_json_event but not the full event.
- Unpublish the event you just published
- Change your MISP.org setting to a valid org name
- Attempt to publish an event using any option *EXCEPT FOR* `Publish event to ZMQ`
- Watch the ZMQ messages successfully publish the full event (misp_json).

**Comment by iglocska** [comment]
Nice catch. That's not even the host org flag anymore.

**Comment by iglocska** [comment]
Should be fixed now, thanks for digging into it!
