### ISSUE TITLE
CentOS 8 MIPS install procedure

### ISSUE THREAD

**Issue by uncleAntik** [MISP/MISP#6182]
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 8.2.2004
| OS version (client)       | N/A
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.129
| Browser                   | N/A

### Support Questions
Hi MISP. I`m running MISP install in accordance to manual https://misp.github.io/MISP/INSTALL.rhel8/ on my CentOS server
and I'm stuck on step "9.06a/ Create a systemd unit for the workers"
The command gives me an error:
```
# checkmodule -M -m -o /tmp/workerstartsh.mod $PATH_TO_MISP/INSTALL/worker/startsh.te
checkmodule:  unable to open /var/www/MISP/INSTALL/worker/startsh.te
```
What is more the folder $PATH_TO_MISP/INSTALL/worker/ doesn't exist either the file /tmp/workerstartsh.mod.
I checked for whole filesystem - there is no  workerstartsh.mod file.
I guess I`ve missed some step before this one and can't find the way out cuz misp-workers.service service doesn't start. I've read the docs and find none other mentions for workerstartsh.mod. Would you please help me to find out to that step file /tmp/workerstartsh.mod (or $PATH_TO_MISP/INSTALL/worker/startsh.te) belongs to?
P.S. selinux is up and running
### Logs, screenshots, configuration dump, ...
![misp_error](https://user-images.githubusercontent.com/28868069/89548072-3dbb1000-d80f-11ea-9875-f53aad07f39d.png)

**Comment by JKD32332** [comment]
I am having the exact same problem. Not sure what to do here now.

**Comment by iglocska** [comment]
No idea where they should be coming from, @SteveClement ?

**Comment by valerianaroncero** [comment]
> I am having the exact same problem. Not sure what to do here now.

I'm with the same problem and the other that come next is this one [#6183](https://github.com/MISP/MISP/issues/6183)

**Comment by SteveClement** [comment]
I will look at it today.

**Comment by SteveClement** [comment]
The file was missing and there was a typo in the path. Fixed in https://github.com/MISP/MISP/pull/6187

But there are certainly more things that are not working.

**Comment by JKD32332** [comment]
But what else is not working? I was able to get past this part thanks to you adding the missing workerstartsh.te file but now when I'm in the misp-modules section (9.07), I'm trying to do the pip install, $SUDO_WWW $PATH_TO_MISP/venv/bin/pip install -U -I -r REQUIREMENTS command, and I'm getting the error that there is no file or directory with the name REQUIREMENTS... 

Is this section not working as well? If I have a choice to choose between a centos 7 and centos 8 for deploying MISP, should I stick with centos 7? @SteveClement @iglocska

**Comment by uncleAntik** [comment]
> 
> 
> But what else is not working? I was able to get past this part thanks to you adding the missing workerstartsh.te file but now when I'm in the misp-modules section (9.07), I'm trying to do the pip install, $SUDO_WWW $PATH_TO_MISP/venv/bin/pip install -U -I -r REQUIREMENTS command, and I'm getting the error that there is no file or directory with the name REQUIREMENTS...
> 
> Is this section not working as well? If I have a choice to choose between a centos 7 and centos 8 for deploying MISP, should I stick with centos 7? @SteveClement @iglocska

Hi. Did you try to disable Selinux? It did the trick for me. But later I found more errors under installation steps so I`ve decided to install MISP on ubuntu 20.04. So far so good

**Comment by SteveClement** [comment]
@JKD32332 

From the docs: 9.07/ misp-modules (Broken on RHEL8)¶

Which probably also means that it is broken on CentOS8 by now.

There is a lot that happened between 8.0 and 8.2 thus I need to re-investigate that malarkey.

Use Ubuntu if your insurance policy allows it.

**Comment by JKD32332** [comment]
Thank you so much for your help and response. Really appreciate it. Last thing I wanted to ask was if there is any document on the database structure and architecture of MISP? Specifically how to know the general maintenance of the database for MISP. I’ve looked, but no success. Any ideas @SteveClement @iglocska?

**Comment by demiscuzz** [comment]
Hello, I am about to embark on my jorney to install MISP on centos8. 
At the beginning of the guide "https://misp.github.io/MISP/INSTALL.rhel8/" it talks of "MISP configuration variables" and then has a bunch of commands. 
Can any one tell me what to do with this bit? anything I can read to get me upto speed? 
Thanks in advance.
