### ISSUE TITLE
CAKE -- Error: syntax error, unexpected 'g' (T_STRING), expecting ')'

### ISSUE THREAD

**Issue by valerianaroncero** [MISP/MISP#6183]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 8.1
| PHP version               | 7.2.11
| MISP version / git hash   | 2.4.125

### Support Questions

Hi, MISP! 

I didnt find out what are these errors in CAKE commands.

How can I configurate $RUN_PHP on CentOS 8 since I do not have scl ?

### Logs, screenshots, configuration dump, ...
$  $SUDO_WWW -- $CAKE userInit -q
Error: syntax error, unexpected 'g' (T_STRING), expecting ')'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->re                                                                                                                                                           ad('config')
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load('config')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/                                                                                                                                                             www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstr                                                                                                                                                             ap(true)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): requ                                                                                                                                                             ire('/var/www/MISP/a...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): Shel                                                                                                                                                             lDispatcher->_bootstrap()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): Shell                                                                                                                                                             Dispatcher->_initEnvironment()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): Shell                                                                                                                                                             Dispatcher->__construct(Array)
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#9 {main}

$ $SUDO_WWW -- $CAKE
Error: syntax error, unexpected 'g' (T_STRING), expecting ')'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read('config')
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load('config')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct(Array)
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#9 {main}

Thanks in advance!
Valeriana

**Comment by SteveClement** [comment]
Until now, CentOS 8 is not fully supported (documented)

I will try and ease out the major blockers.

**Comment by SteveClement** [comment]
I cannot reproduce this.

```
$ $SUDO_WWW $RUN_PHP -- $CAKE userInit -q
YDNGJZDSQ5NcGyBrPRS6MOUdhpqgx1yrD9E4dJDp
```

$RUN_PHP should be empty. I think you have another issue.

By the looks of it something is wrong with you config. Please double check.

**Comment by dogoniyat** [comment]
Actually, there probably is a problem in the config. However, it's unclear how to define what file is being read; I added a lot of echo and get this:
```# php /var/www/MISP/app/webroot/index.php
Before Configure::bootstrap(isset($boot) ? $boot : true);
Configure::read("App");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("debug");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
Configure::read("debug");
return from config::read()
config=default, key=config
Before App::uses(PhpReader,Configure);
After App::uses(PhpReader,Configure);
before read("config");
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Config.language");
return from config::read()
Configure::read("Cache.disable");
return from config::read()
**Error: syntax error, unexpected '/'**
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read()
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap()
#4 /var/www/MISP/app/webroot/index.php(88): include('/var/www/MISP/a...')`
#5 {main}`
Configure::read("Error.extraFatalErrorMemory");`
return from config::read()
```
For me, it looks there is a problem on the line between Cache.disable and Error.extraFatalErrorMemory, but where? How to pinpoint what file and what variable is faulty?
