### ISSUE TITLE
Users Index does not pick up the external authentication flag

### ISSUE THREAD

**Issue by paletyp** [MISP/MISP#6184]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment : Production

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       |Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.129
| Browser                   | Any

### Expected behavior
Prerequisite: Eternal Authentication enabled
Users Index (list)  pick up the external authentication flag for user after enabled and saved
### Actual behavior
Database correctly show  that external auth key and the external authentication is enabled.
But the UI on the users index page and admin edit user page is not picking up the change after the initial save. 

### Steps to reproduce the behavior
1. From admin user page select the flag "External authentication" and enter the external auth key
2. Save the page
3. Go back to the admin edit user page. The previous changes will not show.

**Comment by mokaddem** [comment]
That's indeed weird. Can you see the `External Auth` field in the `/users/index` or `/users/view`?
If not, maybe clearing the cache would solve the issue.
- Go to `/servers/serverSettings/diagnostics` then click on the `clean cache` button
- You can also do it via the CLI: `./cake Admin cleanCaches`

Thanks

**Comment by paletyp** [comment]
Thank you for your response. Clearing the cache resolved the issue.
