### ISSUE TITLE
CentOS 8 Installation Trouble

### ISSUE THREAD

**Issue by JKD32332** [MISP/MISP#6185]
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 8..
| OS version (client)       | N/A
| PHP version               | N/A
| MISP version / git hash   | 2.4.129
| Browser                   | Chrome

### Support Questions
Hello, I am having trouble with installing and deploying MISP on CentOS 8. Since the Installer script doesn't support CentOS 8, I went proceeded with the manual install. I have copied the .sh files for installation and made sure that each file is executable so that I can run the scripts. Every time I run the scripts, NOTHING happens. Whether it's the MISP configuration variables, the base system dependencies, and the MISP code itself, nothing happens. I would really appreciate it if someone pointed me to the right direction and any help that I can get. 

### Logs, screenshots, configuration dump, ...
Here are the executable scripts in my directory.
![Executable Scripts](https://user-images.githubusercontent.com/39170974/89702631-35e39480-d911-11ea-9963-0b8f6803aec7.PNG)

After I run the command to run the script, nothing happens. Absolutely nothing. 
![Command](https://user-images.githubusercontent.com/39170974/89702647-65929c80-d911-11ea-8eae-0a1ecd2261e7.PNG)
I know everything in the file is correct because I copied and pasted from the MISP website itself. I would really appreciate any help. Thank you so much.

**Comment by TryingMyBestOnMISP** [comment]
Hi,
It is because you need to call the function itself in the script for example in the script :

```
# <snippet-begin 0_yumInstallCoreDeps8.sh>
yumInstallCoreDeps8 () {
  # Install the dependencies:
  PHP_BASE="/etc/"
  PHP_INI="/etc/php.ini"
  # If the install group @httpd is not existent, fallback to httpd
  sudo dnf install @httpd -y || sudo dnf install httpd -y
  sudo dnf install gcc git zip unzip \
                   httpd \
                   mod_ssl \
                   moreutils \
                   redis \
                   mariadb \
                   mariadb-server \
                   python3-devel python3-pip python3-virtualenv \
                   python3-policycoreutils \
                   policycoreutils-python-utils \
                   langpacks-en glibc-all-langpacks \
                   libxslt-devel zlib-devel ssdeep-devel -y
  readlink -f /usr/bin/python | grep python3 || sudo alternatives --set python /usr/bin/python3

  # Enable and start redis
  sudo systemctl enable --now redis.service

  # Install PHP 7.4 from Remi's repo, see https://rpms.remirepo.net/enterprise/8/php74/x86_64/repoview/
  sudo dnf install php php-fpm php-devel \
                   php-mysqlnd \
                   php-mbstring \
                   php-xml \
                   php-bcmath \
                   php-opcache \
                   php-zip \
                   php-pear \
                   php-brotli \
                   php-intl \
                   php-gd -y

  # cake has php baked in, thus we link to it if necessary.
  [[ ! -e "/usr/bin/php" ]] && sudo ln -s /usr/bin/php74 /usr/bin/php

  sudo systemctl enable --now php-fpm.service
}
yumInstallCoreDeps8

# <snippet-end 0_yumInstallCoreDeps8.sh>

```
See how I called the function by adding its name "yumInstallCoreDeps8" in the end of the script. Now the script will be exectued.
