### ISSUE TITLE
Tag colors not applied correctly when returned by an expansion module

### ISSUE THREAD

**Issue by hildenjohannes** [MISP/MISP#6186]
Like the title states, I am unable to get tag colors to be applied correctly when returned by an expansion module. I found the issue when developing the [recordedfuture](https://github.com/MISP/misp-modules/blob/main/misp_modules/modules/expansion/recordedfuture.py) module. 

After checking logs, it looks like the module output is correctly formatted and includes tags with the desired colors set, however, the desired colors are not applied. The tags **DO** get the desired colors in the proposal form, but once they are accepted into the event, the desired colors are replaced with random colors. Images showing an example of this is attached at the bottom.

I have made sure to try this on a 'fresh' MISP instance with no previously saved tags (which could technically mess up colors)

This to me seems like a bug but please let me know if I have missed something obvious.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 16.04.6 LTS
| OS version (client)       | Ubuntu 18.04.3 LTS
| PHP version               | 7.2.32
| MISP version / git hash   |  2.4.129
| Browser                   | Chrome

### Expected behavior
Tags get the colors set in the output of a module

### Actual behavior
Tags get assigned random colors

### Steps to reproduce the behavior
Use any expansion module returning an attribute with a tag with a specific color set. The tag will not retain the set color after the proposal to add the returned attribute to the event has been accepted. 

### Logs, screenshots, configuration dump, ...
Example of the bug doing an expansion enrichment on the IP 89.20.135.204 using the Recorded Future enrichment module:

The raw module output includes the correct color coding:
{
    'uuid': '9ea6bb91-b4b2-455a-b460-2236f4164503', 
    'Tag': [
        {'name': 'recorded-future:risk-score="99"', 'colour': '#CF0A2C'}, 
        {'name': 'recorded-future:risk-rule="Historical Honeypot Sighting"', 'colour': '#CCCCCC'}, 
        {'name': 'recorded-future:risk-rule="Historical Open Proxies"', 'colour': '#CCCCCC'}, 
        {'name': 'recorded-future:risk-rule="Historically Reported in Threat List"', 'colour': '#CCCCCC'}, 
        {'name': 'recorded-future:risk-rule="Recent Open Proxies"', 'colour': '#FFCE00'}, 
        {'name': 'recorded-future:risk-rule="Current C&C Server"', 'colour': '#CF0A2C'}
     ], 
     'object_relation': 'Enriched attribute', 
     'value': '103.221.254.102', 
     'type': 'ip-src', 
     'disable_correlation': False, 
     'to_ids': True, 
     'category': 'Network activity', 
     'distribution': '0'
}

The proposal form properly displays the desired colors:
![tag_color_error_propose](https://user-images.githubusercontent.com/8577552/88936654-6a0ce480-d283-11ea-89ee-450b06444f3c.png)

Once the proposal is accepted, the tags lose the desired colors and are assigned random colors:
![tag_color_error_submit](https://user-images.githubusercontent.com/8577552/88936685-75601000-d283-11ea-9fbe-0aeeda4f87a5.png)

**Comment by mokaddem** [comment]
Hey,
It should be fixed now.
Thanks for the report!

**Comment by hildenjohannes** [comment]
I can confirm that it works, thank you very much!
