### ISSUE TITLE
Failure to extract CSV based on a specific tag

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#619]
Hi all,

I am trying to wget some attributes based on a specific tag.
I use the following URL:
https://MISP/events/csv/download/false/false/OSINT/Network%20activity/domain
The output that I get is all the Network activity domains within MISP and not the ones that belong to an event tagged as OSINT (I have tested a couple of tags). 

Do you experience this one as well?

Regards,
Andreas

PS. In the automation page of MISP, at the CSV Export section you should replace the following: 
https://MISP/events/csv/download/false/false/tag1&&tag2&&!tag3/Network%20Activity/domain
with this one (Network%20Activity -> Network%20activity):
https://MISP/events/csv/download/false/false/tag1&&tag2&&!tag3/Network%20activity/domain

**Comment by iglocska** [comment]
Just tried it, indeed it looks like a bug, I'll push a patch for it today! Thanks for the heads-up!

**Comment by iglocska** [comment]
It is fixed now, just git pull!
