### ISSUE TITLE
Update MISP's ATT&CK Matrix to Add New Sub-Techniques

### ISSUE THREAD

**Issue by fossilos** [MISP/MISP#6194]
The current ATT&CK matrix available directly in MISP is outdated: https://www.misp-project.org/2018/06/27/MISP.2.4.93.released.html

It needs to be updated to include the new sub-techniques added in Mitre's recent update to ATT&CK: https://attack.mitre.org/matrices/enterprise/ 

Please update MITRE's ATT&CK matrix. Thanks.

**Comment by timhux123** [comment]
Any update on this?

**Comment by cvandeplas** [comment]
Subtechniques have been implemented on 18 Oct in commit https://github.com/MISP/misp-galaxy/commit/2334676e6410e3413116d80df4ebae26dfffdf99

**Comment by fossilos** [comment]
Thank you!!
