### ISSUE TITLE
mysql service keeps stopping....

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#6195]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.4 
| OS version (client)       | Windows
| PHP version               | PHP 7.4.8 (cli) (built: Jul 13 2020 16:45:47) ( NTS )
| MISP version / git hash   | 2.4.129, 8207149b4c8b11f178d61428b745245724286e12
| Browser                   | Firefox
MISP Server Hardware - 32GB RAM and 8 CPU

### Support Questions
Almost every morning I get an 'Internal Error Occurred' that seems to be due to mariadb being down.  If I restart the service it seems to work fine all day until I come in the next am.  

I was wondering if this was a problem others are having or something I've done.  Definitely not a DB expert so I wasn't sure how else to troubleshoot this.  

Thanks!

### Logs, screenshots, configuration dump, ...
  Process: 9710 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 9706 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 27249 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 27146 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-enviro
  Process: 27137 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 27122 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 27249 (code=exited, status=0/SUCCESS)
   Status: "MariaDB server is down"

Aug 14 02:02:12 MISP systemd[1]: Starting MariaDB 10.1.44 database server...
Aug 14 02:02:15 MISP mysqld[27249]: 2020-08-14  2:02:15 140313062943872 [Note] /usr/sbin/mysqld (mysqld 10.1.44-MariaDB-0ubuntu0.18.04.1) starting as process
Aug 14 02:20:16 MISP systemd[1]: mariadb.service: Start operation timed out. Terminating.
Aug 14 02:20:27 MISP systemd[1]: mariadb.service: Failed with result 'timeout'.
Aug 14 02:20:27 MISP systemd[1]: Failed to start MariaDB 10.1.44 database server.

excerpt from  mysql log
root@MISP:/var/www/MISP/app/tmp/logs# tail -f /var/log/mysql/error.log
2020-08-14 13:03:43 139833590671104 [Note] InnoDB: Rollback of trx with id 415912009 completed
2020-08-14 13:03:43 139833590671104 [Note] InnoDB: Rollback of non-prepared transactions completed
2020-08-14 13:07:44 139833590671104 [Note] InnoDB: Dumping buffer pool(s) not yet started
2020-08-14 13:07:44 139852746017920 [Note] Plugin 'FEEDBACK' is disabled.
2020-08-14 13:07:44 139852746017920 [Note] Recovering after a crash using tc.log
2020-08-14 13:07:44 139852746017920 [Note] Starting crash recovery...
2020-08-14 13:07:44 139852746017920 [Note] Crash recovery finished.
2020-08-14 13:07:44 139852746017920 [Note] Server socket created on IP: '127.0.0.1'.
2020-08-14 13:07:44 139852746017920 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.44-MariaDB-0ubuntu0.18.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Ubuntu 18.04

**Comment by mathurin68** [comment]
Or I'm getting the following...
2020-08-14 13:57:51 Error: [PDOException] SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Request URL: /users/view/me
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Post`.`...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Post`.`...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1564): DboSource->fetchAll('SELECT `Post`.`...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1398): DboSource->_fetchHasMany(Object(User), 'SELECT `Post`.`...', Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation(Object(User), Object(Post), 'hasMany', 'Post', Array, Array, true, Array, 0, Array)

**Comment by adulau** [comment]
It seems your MariaDB is crashing at some point (doing a rollback is usually the sign of that). Various potential reasons:

- Out of space on the disk
- Permission on specific files in the MariaDB backend (not accessible by MariaDB)
- I/O issues

Could you check the above on your system and let us know?

**Comment by mathurin68** [comment]
Hmmm, I think I found the culprit in one of our many feeds coming in. Thanks!
