### ISSUE TITLE
Add pe rich header hash as attribute type

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#6205]
As a user, when adding data about pe files in MISP, I would like to be able to add riche pe headers hash to the data to avoid leaving a type of IOC/contextual information out.

More details on rich header from pe files:
https://www.virusbulletin.com/virusbulletin/2020/01/vb2019-paper-rich-headers-leveraging-mysterious-artifact-pe-format/

Example of pythong library implementing the hash:
https://github.com/RichHeaderResearch/RichPE

The result looks is an md5 hash.

**Comment by iglocska** [comment]
https://github.com/MISP/misp-objects/commit/4a671ca739d7ea06567ca21b2a99333ab915cfa9

Think since it's using an md5 hash (or equivalent output) as the format, we can for now just use md5 via objects where the object relation will give it the additional context.
