### ISSUE TITLE
Add rich pe headers type in templates 

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#6207]
Pre-scriptum: Requires #6205 to be implemented.
As a user adding data with rich pe headers hash, I would like to be able to add rich pe headers hash as an optional attribute to the object types of **file** & **pe** in order to avoid leaving  IOC/contextual information out.

**Comment by iglocska** [comment]
https://github.com/MISP/misp-objects/commit/4a671ca739d7ea06567ca21b2a99333ab915cfa9

Added to pe
