### ISSUE TITLE
INSTALL.sh hanging at "Generating a default key"

### ISSUE THREAD

**Issue by edwardspbe** [MISP/MISP#6209]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug in INSTALL.sh -c when following instructions in INSTALL.ubuntu1804.md
| OS version (server)    | Ubuntu "18.04.5 LTS (Bionic Beaver)" VM (VirtualBox) booting to the console only.

### Actual behavior

The "INSTALL.sh -c" was hanging at "Generating a default key".  

My guess was GPG...  I assumed it was not getting enough entropy so followed the instructions at the following link to get around the problem. https://delightlylinux.wordpress.com/2015/07/01/is-gpg-hanging-when-generating-a-key/

After this, I performed the command#  bash INSTALL -N -c  
...and the install completed properly (or at least I think :)

### Logs, screenshots, configuration dump, ...

Hope this helps improve the install experience for others.  

Paul

**Comment by iglocska** [comment]
Indeed this is expected on installations on a VM where entropy can be an issue. Perhaps it's indeed a good idea to add a note of this in the installation (running haveged for example helps).

**Comment by SteveClement** [comment]
It does mention it if you go manual.

On kali linux I install the RNG: https://github.com/MISP/MISP/blob/9c077fbd548127651a75a5bd9b685fb8d51834cc/INSTALL/INSTALL.sh#L747

I will think on how to "accurately" guesstimate entropy.

**Comment by MySickSi** [comment]
Just wanted to add that I had the same issue. I had no issue installing before at work and on my home PC a few months ago but when I tried to install tonight on my home dedicated server it just hung. I followed @edwardspbe advice and it worked.

**Comment by SteveClement** [comment]
Fixed in #6952
