### ISSUE TITLE
Flexibility to create an event via the API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#621]
As of now, if I want to create a new event, via a Json object, it should work, right? Right now, the API only does that when you upload a malware sample, it was implemented for Viper. I'll try to implement that functionality ASAP.

But I've been looking at the old issues opened on PyMISP[1] and I'm wondering if it is possible, and if now, how ard would it be to implement? 

[1] https://github.com/CIRCL/PyMISP/issues/4

**Comment by iglocska** [comment]
Not sure I understand - you just want to create a new event via JSON? That works, just post it to /events

Example:
{"Event":{"date":"2015-01-01","threat_level_id":"1","info":"testevent","published":false,"analysis":"0","distribution":"0","Attribute":[{"type":"domain","category":"Network activity","to_ids":false,"distribution":"0","comment":"","value":"test.com"}]}}

This will create an event with an attribute.

**Comment by Rafiot** [comment]
That's what I wanted to make sure. Now, the next question: can I remove an attribute from an event?

**Comment by iglocska** [comment]
You can but it responds with an error (it tries to view the deleted
attribute...), but the deletion works. I'll fix the response for it.

simply DELETE /attributes/id where id is a number

or

POST anything to /attributes/delete/id

**Comment by Rafiot** [comment]
Fixed.
