### ISSUE TITLE
Email OTP fails to send with enforced encryption 

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#6213]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7
| OS version (client)       | Win10
| PHP version               |  7.2.27
| MISP version / git hash   |  v2.4.129 (c0bc1a0c67bffc91cfa7382bb5df3d6bb39a42cd)
| Browser                   | Google Chrome

### Expected behavior

When a user has a PGP key saved to their account, and GnuPG.onlyencrypted is set to true, the user recieves their OTP via PGP encrypted email.

### Actual behavior

The user receives the message "The email couldn't be sent, please reach out to your administrator."
Loging in as the admin@admin.test user, exempted from OTP, the audit log reads: "Email to [removed], titled "[MISP] Email OTP" failed. Reason: encrypted messages are enforced and the message could not be encrypted for this user as no valid encryption key was found."

A valid encryption key is available as the welcome message was successfully sent to the user.

### Steps to reproduce the behavior

1. Clean install from RPM
2. Set `GnuPG.onlyencrypted` to `true`
3. Set `Security.email_otp_enabled` to `true`
4. Add a user with a PGP key (welcome email successfully delivered)
5. In a new browser log in as the new user
6. Get redirected to OTP Screen with error

### Logs, screenshots, configuration dump, ...

Email to [removed], titled "[MISP] Email OTP" failed. Reason: encrypted messages are enforced and the message could not be encrypted for this user as no valid encryption key was found.

```
...
'GnuPG' =>
  array (
    'onlyencrypted' => true,
    ...
    'homedir' => '/var/www/MISP/.gnupg',
    ...
    'sign' => true,
    'binary' => '/usr/bin/gpg',
  ),
...
'Security' =>
  array (
    ...
    'email_otp_enabled' => true,
    'email_otp_exceptions' => 'admin@admin.test',
    'email_otp_length' => 6,
    'email_otp_text' => '$otp',
    'email_otp_validity' => 5,
    ...
  ),
```

```bash
$ gpg --homedir /var/www/MISP/.gnupg --list-keys
/var/www/MISP/.gnupg/pubring.gpg
--------------------------------
pub   4096R/[keyid] 2020-08-19
uid                  MISP <[MISP Email Address]>
sub   2048R/[keyid] 2020-08-19

pub   4096R/[keyid] 2020-08-19
uid                  MISP <[MISP Email Address]>
sub   4096R/[keyid] 2020-08-19

pub   2048R/[keyid] 2019-10-09
uid                  [User Name] <[User Email]>
sub   2048R/[keyid] 2019-10-09
```

**Comment by JakubOnderka** [comment]
Thanks for very clear report. Can you try to test it with branch from PR https://github.com/MISP/MISP/pull/6214?

**Comment by JoePJisc** [comment]
I cannot currently test the PR as the RPM is still at v2.4.129 (c0bc1a0) and the PR updates `app/Lib/Tools/SendEmail.php` which appears to be created in v2.4.130.

I have tried spinning up a test VM however access to our mail relay is restricted by IP, so it cannot relay mail.

I'll see if I can find a way to test...

**Comment by JakubOnderka** [comment]
> I cannot currently test the PR as the RPM is still at v2.4.129 ([c0bc1a0](https://github.com/MISP/MISP/commit/c0bc1a0c67bffc91cfa7382bb5df3d6bb39a42cd)) and the PR updates `app/Lib/Tools/SendEmail.php` which appears to be created in v2.4.130.
> 
> I have tried spinning up a test VM however access to our mail relay is restricted by IP, so it cannot relay mail.
> 
> I'll see if I can find a way to test...

Actually change in `app/Lib/Tools/SendEmail.php` is not important and you can skip it.

**Comment by JoePJisc** [comment]
I have replaced the other two files with the updated ones in the PR and the OTP sreen now says:

> An Internal Error Has Occurred.
> Error: An Internal Error Has Occurred.

Log entry:

```
2020-08-21 10:17:29 Error: [Error] Call to undefined method GpgTool::initializeGpg()
Request URL: /users/email_otp
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(749): User->initializeGpg()
#1 /var/www/MISP/app/Controller/UsersController.php(1742): User->sendEmail(Array, '698309', false, '[MISP] Email OT...')
#2 [internal function]: UsersController->email_otp()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
```

Maybe it depends on something in v2.4.130?

**Comment by lfortemps** [comment]
Yes you probably miss some other changes that were introduced between the 2.4.129 and 2.4.130 tag. I replicated the issue on my lab and by doing a checkout from the branch, this works as expected. Let's get the PR merged :+1:

**Comment by JoePJisc** [comment]
Thanks for doing the testing @Golbark

**Comment by JoePJisc** [comment]
I can confirm this is now working as expected, having upgraded to v2.4.132.
