### ISSUE TITLE
Problem with MISP update

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#6215]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| PHP version               | 7.2
| MISP version / git hash   | 2.4.129/2.4.130

I always had troubles with updating MISP, because of errors https://github.com/MISP/MISP/issues/6039

Today I tried solve it using solution from here : https://bugzilla.redhat.com/show_bug.cgi?id=1785720

![изображение](https://user-images.githubusercontent.com/29750691/90851991-b97c9700-e38f-11ea-8d28-75399a1c79c2.png)

And then I started updating MISP, but got many of permissions errors [not screenshoted them :-( ]. Now I can't open "diagnostic page" - 
![изображение](https://user-images.githubusercontent.com/29750691/90852162-36a80c00-e390-11ea-9756-a5e652331a5e.png)

Internal error
![изображение](https://user-images.githubusercontent.com/29750691/90852190-458ebe80-e390-11ea-926b-6e44eb6be80c.png)

Also I tried update from CLI but it not helped
![изображение](https://user-images.githubusercontent.com/29750691/90853445-9b189a80-e393-11ea-9a8a-32314493ec17.png)

![изображение](https://user-images.githubusercontent.com/29750691/90852240-70791280-e390-11ea-93e1-032163b3c234.png)

![изображение](https://user-images.githubusercontent.com/29750691/90852761-d6b26500-e391-11ea-84a2-0815ab4707f2.png)

Looks like MISP not updated
![изображение](https://user-images.githubusercontent.com/29750691/90852867-1aa56a00-e392-11ea-82a6-d4fe69ae1b1c.png)

**Comment by NailBash** [comment]
Well, with some tricks I resolve problem with 'Internal error'. But I still can't update MISP
![изображение](https://user-images.githubusercontent.com/29750691/90858216-33684c80-e39f-11ea-9b70-c71740481597.png)

I would be happy if someone will help me

**Comment by iglocska** [comment]
````git checkout app/View/Events/add.ctp````

Then you can update.

**Comment by NailBash** [comment]
Thank you for your fast answer. But sadly it didn't help.

![изображение](https://user-images.githubusercontent.com/29750691/90862138-6530e180-e3a6-11ea-83e2-bf982e6fb382.png)

**Comment by iglocska** [comment]
hmm. Does `git reset --hard HEAD` solve it?

**Comment by iglocska** [comment]
Also, could you check if your git filemode is set correctly?

`git config core.fileMode`

It should return false, if it doesn't:

`git config core.fileMode false`

**Comment by NailBash** [comment]
After git reset --hard HEAD pull executed sucessfully, git config core.fileMode returned false

![изображение](https://user-images.githubusercontent.com/29750691/90875388-86033200-e3ba-11ea-8a51-1be33efd052f.png)
but 
![изображение](https://user-images.githubusercontent.com/29750691/90875475-a4692d80-e3ba-11ea-8075-84624e989afc.png)
I made script that downloading and updating warninglists every day, I think problem cause by this.

P.S. I resolved this by changing directory to /var/www/MISP/app/files/warninglists and executing git reset --hard HEAD

**Comment by NailBash** [comment]
After succesful update I have now this error
![изображение](https://user-images.githubusercontent.com/29750691/90878160-a9c87700-e3be-11ea-84b1-ca30c1866327.png)
by the way I have this issues with submodules from summer's begin.
![изображение](https://user-images.githubusercontent.com/29750691/90878633-32471780-e3bf-11ea-8f63-bb2856366f2a.png)

**Comment by NailBash** [comment]
OMG, I for some reason again pushed "update" button at Web-UI, and now have almost same problem that I can't resolve with git checkout, git reset commands
![изображение](https://user-images.githubusercontent.com/29750691/91836250-f5eba500-ec63-11ea-82c2-c7ca9dca029f.png)
![изображение](https://user-images.githubusercontent.com/29750691/91836601-75797400-ec64-11ea-90f6-fd9beb962e1b.png)
![изображение](https://user-images.githubusercontent.com/29750691/91836689-95a93300-ec64-11ea-974a-ec8658e82682.png)

**Comment by NailBash** [comment]
Ok, I resolve it: git clean  -d  -f .
Then git pull

**Comment by NailBash** [comment]
Thank you for help
