### ISSUE TITLE
Docker and docker-compose file

### ISSUE THREAD

**Issue by transilience** [MISP/MISP#6216]
**Is your feature request related to a problem? Please describe.**
Dockerfile and docker-compose.yml file currently do not exist for setup of MISP

**Describe the solution you'd like**
A dockerfile and a docker-compose file which will setup all the required components on different dockers.

**Comment by JakubOnderka** [comment]
You can find everything in [separate repo](https://github.com/misp/misp-docker).

**Comment by enjeck** [comment]
> You can find everything in separate repo.

@transilience Is this what you were looking for? I'll like to know whether this issue should be closed now.

**Comment by transilience** [comment]
Yes, this found it thanks.
Issue may be closed.
