### ISSUE TITLE
User not able to see all events

### ISSUE THREAD

**Issue by DavidF7** [MISP/MISP#6217]
I'm using the newest version v.130 and ran into issues with event view permissions.
As an admin I can see all events. However, having changed nothing in MISP configuration or settings, MISP "user" as well as "org admin" can not now see events from some remote organisations (even though they could see everything before upgrade from v.124).
Our instance is part of remote org sharing group.
The only record I found in logs is 

<email> | fetchEvent | Event | User was able to fetch the event but not the sharing_group it belongs to | 2020-08-19 08:40:25
-- | -- | -- | -- | --

Did MISP involved some event view permissions? 

Thank you

**Comment by iglocska** [comment]
Indeed, there was a tightening of the permissions - basically it has to do with the wrong organisation uuid being used to denote a remote server connection vs the actual org uuid used by the remote. The new rule basically blocks any non admin users from seeing an event that they may even be the local owners for - if it has a sharing group attached and the given user isn't part of the sharing group. Ask the owner of the sharing group to involve the correct organisation that you are part of to make it visible.

**Comment by DavidF7** [comment]
Thank you for a quick and helpful response. Fixed it merging my Org in remote Sharing group with my local Org.
