### ISSUE TITLE
Initial PULL from other MISP: Status:Failed

### ISSUE THREAD

**Issue by icepaule** [MISP/MISP#6218]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.0.4
| OS version (client)       |  Win10
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | v2.4.130 (7d253f87fdc452a1224097cbaa80078caf46e141)
| Browser                   | Chrome

### Expected behavior
Initial pull from foreign MISP servers get data into MISP

### Actual behavior
Initial PULL 10590 Events from CERTLU fails.
Initial PULL 60100 Events from BSI fails.
Pull event stays in status unknown for quite a while and the changes to FAILED. 
![2020-08-21 14_08_16-Jobs - MISP](https://user-images.githubusercontent.com/21141691/90889273-60b8f880-e3a7-11ea-9df8-317ae843ccbe.png)

### Steps to reproduce the behavior
Fresh setup of MISP and add a new MISP server to pull from

### Logs, screenshots, configuration dump, ...

**rescue-xxxx.log:**
[2020-08-21 13:56:39] main.INFO: got {"queue":"default","id":"e1c3457ec0f25b6e2ed88c861c52cb82","class":"ServerShell","args":[["pull","2","4","full","6106"]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"default\",\"id\":\"e1c3457ec0f25b6e2ed88c861c52cb82\",\"class\":\"ServerShell\",\"args\":[[\"pull\",\"2\",\"4\",\"full\",\"6106\"]]})","worker":"misp:1580"} []
[2020-08-21 13:56:39] main.INFO: Processing ID:e1c3457ec0f25b6e2ed88c861c52cb82 in default {"type":"process","worker":"misp:1580","job_id":"e1c3457ec0f25b6e2ed88c861c52cb82"} []
[2020-08-21 13:56:54] main.ERROR: {"queue":"default","id":"e1c3457ec0f25b6e2ed88c861c52cb82","class":"ServerShell","args":[["pull","2","4","full","6106"]]} failed: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by {"type":"fail","log":"SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by","job_id":"e1c3457ec0f25b6e2ed88c861c52cb82","time":15277,"worker":"misp:1580"} []

**error.log**
2020-08-21 13:58:33 Notice: Error during GPG signing.
[Crypt_GPG_KeyNotFoundException] Cannot sign data. Private key not found. Import the private key before trying to sign data.
Stack Trace:
#0 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(1824): Crypt_GPG_ProcessHandler->throwException(2)
#1 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/Engine.php(861): Crypt_GPG_Engine->_closeSubprocess()
#2 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1792): Crypt_GPG_Engine->run()
#3 /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG.php(1024): Crypt_GPG->_sign('test', false, NULL, 2, true, false)
#4 /var/www/MISP/app/Model/Server.php(5086): Crypt_GPG->sign('test', 2)
#5 /var/www/MISP/app/Controller/ServersController.php(1086): Server->gpgDiagnostics(1)
#6 [internal function]: ServersController->serverSettings('diagnostics')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

Please also see: https://github.com/MISP/MISP/issues/5981#issuecomment-668095827_

**Comment by icepaule** [comment]
Thanks very, very much for your help.  ;-)

**Comment by JakubOnderka** [comment]
You need to disable only_full_group_by mode in MySQL. You can try to do that by this solution: https://stackoverflow.com/a/36033983.

**Comment by iglocska** [comment]
That’s a temporary fix to get it running again, but we need to fix the offending query on our side and be more careful with adhering to full  group by requirements. I’ll try to dig into this tomorrow

**Comment by icepaule** [comment]
Thanks a lot @JakubOnderka 
I've executed the mysql statement and wait for the result during the future poll's. But right now it looks pretty good.

Anyway, thx again for the help.  ;-)

Cheers
Marcus

**Comment by github-germ** [comment]
2.4.131

We are seeing this MySQL error also triggered by PyMISP clients: `error.log` excerpt below. We will try the temp fix to disable `only_full_group_by` mode in MySQL.
```
2020-09-14 13:17:08 Error: Could not save freetext feed data for feed 143.
[PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.Attribute.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Attribu...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Attribu...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Attribute), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('list', Array)
#6 /var/www/MISP/app/Model/Attribute.php(3925): Model->find('list', Array)
#7 /var/www/MISP/app/Model/Attribute.php(3940): Attribute->__getCIDRList()
#8 /var/www/MISP/app/Model/Attribute.php(3959): Attribute->setCIDRList()
#9 /var/www/MISP/app/Model/Attribute.php(2056): Attribute->getSetCIDRList()
#10 /var/www/MISP/app/Model/Attribute.php(2104): Attribute->__cidrCorrelation(Array)
#11 /var/www/MISP/app/Model/Attribute.php(737): Attribute->__afterSaveCorrelation(Array, false, Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Attribute->afterSave(true, Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#15 /var/www/MISP/app/Model/Feed.php(1041): Model->save(Array)
#16 /var/www/MISP/app/Model/Feed.php(893): Feed->saveFreetextFeedData(Array, Array, Array, '938858')
#17 /var/www/MISP/app/Console/Command/ServerShell.php(245): Feed->downloadFromFeedInitiator('143', Array, '938858')
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('fetchFeed', Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#21 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#22 {main}
```

**Comment by icepaule** [comment]
Disabling only_full_group_by mode in MySQL did the trick.
I can now inital poll my other MISPs.

Thaaanks so much for your help guys.
Realy, realy appreciated.

**Comment by github-germ** [comment]
Yes, same here. The temp fix disabling `only_full_group_by` has stopped those errors. THANKS!

QUESTION: WIll it be wise to re-enable `only_full_group_by` once the MISP server-side queries are revised?
