### ISSUE TITLE
Add tags related functions in the API

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#622]
To list tags, as requested in #473 by @Rafiot and to edit/delete/add/remove as mentioned by @iglocska

**Comment by iglocska** [comment]
I'll try not to do this until next week at least... :)

**Comment by AndreC10002** [comment]
I have the same requirement: to be able to add tags during event creation via the REST API (JSON or XML file).

There was some chatter on #473 about predefined tags,  It is a great idea and I'd suggest considering tags for reliability and credibility of the data in addition to TLP.

https://en.wikipedia.org/wiki/Admiralty_code

**Comment by AndreC10002** [comment]
Almost forgot to mention that multiple tags are expected to be assigned to events during creation or edits.  Thi N-to-N relationship between events and tags is important to us.

**Comment by adulau** [comment]
+1 for the Admiralty code as hard-coded tags. I assume for the 2.4 milestone is still fine @iglocska ?

**Comment by iglocska** [comment]
Can do. Will add these tomorrow on the 2.4 branch.

**Comment by adulau** [comment]
Hi @AndreC10002 I did a first proposal for the "hardcoded"/machine tags of Admiralty code as external taxonomy. https://github.com/MISP/misp-taxonomies to be included in 2.4 or 2.4 hotfixes - Feedback welcome.

**Comment by Rafiot** [comment]
Fixed.
