### ISSUE TITLE
Count number of attributes added in specific timestamp using Rest API

### ISSUE THREAD

**Issue by tinamina12** [MISP/MISP#6233]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.1
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Support Questions
I am trying to get the attribute count with pymisp using two different ways, but the count returned is not same. Please help me in understanding what exactly is meant by timestamp?
The code is below:

from pymisp import ExpandedPyMISP,PyMISP,MISPEvent, MISPOrganisation, MISPAttribute 

***Method-1 (Returns: 26167)***

misp = PyMISP('url', 'apikey ', False)
result = misp.search('attributes', pythonify=True, timestamp="10d")
print(len(result))

***Method-2 (Returns:26123)***

misp_url = url
misp_key = apikey
misp_verifycert = False
relative_path = 'attributes/restSearch'
body = {
    "returnFormat": "text",
    "timestamp":"10d"
}
misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert)
result = misp.direct_call(relative_path, body)
fetched_alerts = result.split("\n")
print(len(fetched_alerts)-1)

**Comment by tinamina12** [comment]
@iglocska please help. Shouldn't there be a count API too which can return attribute count?

**Comment by iglocska** [comment]
If you don't mind it being the same speed as the other search APIs I can easily add one ;)

**Comment by iglocska** [comment]
well why not.

Just use:

````
{
    "returnFormat": "count",
     ....
}
````

Works on the /events/ and /attributes/ scopes for restsearch.

**Comment by tinamina12** [comment]
one issue is that if i do { "returnFormat": "count"}  , the GUI does not return result. However, when using API the total attribute count is returned. Any idea? @iglocska

**Comment by tinamina12** [comment]
and btw count is returning count of orphaned attributes as well :/

**Comment by iglocska** [comment]
Woah several things here: Can you describe the entire query that you're doing / a screenshot of the GUI of it not working (please redact the API key).

Also, orphaned attributes?... How did you end up with those?

**Comment by tinamina12** [comment]
for the query, i tested again. The result is returned after 2,3 minutes. 
And for orphaned attributes, i deleted few events and i thought attributes are also deleted but they are still present in database. :/ and the count result includes the count of those orphaned attributes.

**Comment by iglocska** [comment]
How did you delete the events? Also, the query will be just as slow as the normal export, without returning the data just the count instead. I think as a first step it would be interesting to identify how you ended up with orphans and fix that.
