### ISSUE TITLE
Problems entering indications using free text import

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#6236]
Questions | Answers
-- | --
Type of issue | Bug
OS version (server) | RHEL, with MISP running on a docker container..
OS version (client) | MacOS, Win10,
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

I am having problems entering indicators that have correlations with other events. I am not able to enter these indicators using the freetext import. The job status indicates it has failed

![image](https://user-images.githubusercontent.com/42444130/91214005-1651b780-e6d8-11ea-8606-b6c7c7f6c2f0.png)

Job status shows as queued, eventually it will fail

![image](https://user-images.githubusercontent.com/42444130/91214102-3bdec100-e6d8-11ea-8769-be30b4136c81.png)

any ideas what is causing and how to resolve? does not happen if indicator does not find a match with other existing events

**Comment by JakubOnderka** [comment]
Hello. Did you check error log if contains any error message?

**Comment by dmolina213** [comment]
what error log should i look at?

**Comment by JakubOnderka** [comment]
Most probably the `app/tmp/logs/error.log`
