### ISSUE TITLE
Cache feed CLI not working

### ISSUE THREAD

**Issue by cyber288** [MISP/MISP#6238]
# This template is meant for bug reports, if you have a feature request user the other template.

We want to create cron jobs to automate syncing. Certain functionalities like Push and Pull are working as advertised.

Cachefeed does not work.

### Work environment
Version 2.4.129 running in docker container environment

### Expected behavior
Feed would get cached 

### Actual behavior
Error happens. We have tried to cache all feeds or specific feeds. We always get the same error message of "too few arguments".

### Steps to reproduce the behavior
Run app/Console/cake Server cacheFeed 2 all

### Logs, screenshots, configuration dump, ...
root@499d0da26218:/var/www/MISP# app/Console/cake Server cacheFeed 2 all

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Warning Error: vsprintf(): Too few arguments in [/var/www/MISP/app/Lib/cakephp/lib/Cake/I18n/I18n.php, line 697]

**Comment by cyber288** [comment]
Cache feeds works through the scheduled tasks in the GUI...

**Comment by mokaddem** [comment]
It should be fixed now, thanks for the report!
