### ISSUE TITLE
Script to change the salt and reset the admin password

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#624]
I managed to lock me out a MISP instance where I'm the only admin. I would like to reset my password via the database but it seems non-trivial because of the salt.

TODO: a script that directly communicate to MYSQL, ask for the user, salt and new password and change the corresponding entry in the database.

Would also be very useful in case you have to change the salt.

**Comment by Rafiot** [comment]
(no hurry for me, I recovered my access, but still, would be a nice to have :) )

**Comment by elhoim** [comment]
[This](https://github.com/MISP/MISP/blob/master/app/Console/Command/PasswordShell.php) can probably help.

**Comment by iglocska** [comment]
Indeed the password shell can reset the PW for you if you have command line access!

**Comment by iglocska** [comment]
Simply do this:

cd /var/www/MISP/app/Console/cake Password email newpassword

**Comment by Rafiot** [comment]
Excellent, let's add it in the doc then :)

**Comment by iglocska** [comment]
That would indeed be handy... :)
