### ISSUE TITLE
Log Retention Time / Clear Old Logs

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#6244]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.128 (470fd47b4021a9547b063ddb17c6f2514f2d5013)
| Browser                   | Google Chrome

### Support Questions

Is there a **supported** way to set a log retention limit and / or clear old logs from the database? If not, would something like the below be safe to run, potentially on a dialy schedule?

```mysql
DELETE FROM `logs` WHERE `created` < DATE_SUB(NOW(), INTERVAL 90 DAY);
OPTIMIZE TABLE `logs`;
```

The logs table on our install has grown to over 4.25GB, dating right back to the original install date nearly 3 years ago; we have no requirement for such a long retention.

Thanks

### Logs, screenshots, configuration dump, ...

n/a

**Comment by mokaddem** [comment]
Indeed logs tables can grow large if you have lots of stuff going on on your instance.
Unfortunately, logs are used for the event history, tag creation, attribute edition, synchronization and so on.
So truncating the `logs` table will discard these information.
Could you check the distribution of your logs in terms of `model` and `action` to see if something not relevant can be pruned?

Anyway, if you don't care about recovery, history and debugging, you can go for it

**Comment by JoePJisc** [comment]
Thanks for letting me know about the cross dependencies on the `logs` table.

It looks like the main models would not be suitable for pruning?

```SQL
MariaDB [misp]> SELECT model,count(*) AS count FROM logs GROUP BY model ORDER BY count DESC;
+--------------------+---------+
| model              | count   |
+--------------------+---------+
| Attribute          | 5963776 |
| User               | 3009672 |
| Event              |  755485 |
| Server             |  130678 |
| MispObject         |  102343 |
| ObjectReference    |   17106 |
| ShadowAttribute    |    6934 |
| Tag                |    1341 |
| ObjectTemplate     |     501 |
| Organisation       |     354 |
| AdminSetting       |     122 |
| Feed               |     112 |
| Taxonomy           |     104 |
| Warninglist        |      97 |
| EventBlacklist     |      87 |
| ObjectRelationship |      67 |
| Thread             |      12 |
| UserSetting        |      11 |
| Post               |       6 |
| Role               |       5 |
| SharingGroup       |       4 |
| Noticelist         |       2 |
| Whitelist          |       1 |
| Log                |       1 |
+--------------------+---------+
24 rows in set (21.34 sec)
```

**Comment by mokaddem** [comment]
Could you have a look at the `action` field for the `User` model. Maybe something can be done here

**Comment by JoePJisc** [comment]
```sql
SELECT action,count(*) AS count FROM logs WHERE model='User' GROUP BY action ORDER BY count DESC;
+---------------------+---------+
| action              | count   |
+---------------------+---------+
| auth                | 3157440 |
| email               |   25660 |
| login               |    1855 |
| logout              |      89 |
| edit                |      61 |
| login_fail          |      56 |
| add                 |      25 |
| remove_dead_workers |      22 |
| change_pw           |      17 |
| auth_fail           |       3 |
| reset_auth_key      |       3 |
+---------------------+---------+
11 rows in set (36.73 sec)
```

**Comment by mokaddem** [comment]
It seems that you have the setting `MISP.log_auth` enabled. This will log  all successful authentications using the API key which can lead to a huge amount of entries if you are using scripts.
If you do not have any use of these `auth` actions, you can safely deletes their associated entries.

**Comment by imidoriya** [comment]
@mokaddem thanks for the tip.  I just deleted 275911855 User `auth` entries, which should hopefully reduce the size of my 113G logs table by a good bit.  What other entries are safe to delete or perhaps which ones are not safe to delete?  My next largest table entry is Attribute `add` at 53551786.

**Comment by abdulkadirakinsola** [comment]
Hello, currently my server disk space has been filled up, how do i clear logs that i dont need

-----------------------+----------+
| model                 | count    |
+-----------------------+----------+
| Attribute             | 56590661 |
| Object                |  6148861 |
| User                  |    80138 |
| Event                 |    44260 |
| GalaxyClusterRelation |    37509 |
| GalaxyCluster         |    31465 |
| Tag                   |    19212 |
| ObjectReference       |    10458 |
| ObjectTemplate        |      686 |
| AdminSetting          |      467 |
| Server                |      366 |
| Feed                  |      211 |
| Galaxy                |       84 |
| EventReport           |       84 |
| Organisation          |       33 |
| AuthKey               |       11 |
| EventBlocklist        |        6 |
| UserSetting           |        2 |
+-----------------------+----------+
