### ISSUE TITLE
Unable to change default [star] home page

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#6245]
# Unable to change default [star] home page

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | v2.4.130 (c3d6054409ac781bdfb04785b0c8e6c0edebe53b)
| Browser                   | Chrome

### Expected behavior
Change default "home page" to current page

### Actual behavior
No changes

### Steps to reproduce the behavior
Fresh install using imported database from older misp instance

### Logs, screenshots, configuration dump, ...
```
2020-08-27 10:15:11 Error: [MissingViewException] View file "UserSettings/set_home_page.ctp" is missing.
Exception Attributes: array (
  'file' => 'UserSettings/set_home_page.ctp',
)
Request URL: /userSettings/setHomePage
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): View->render()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#5 {main}
```

**Comment by mokaddem** [comment]
Hey, thanks for the report. It's fixed on head
