### ISSUE TITLE
Scheduled fetch_feeds task is stuck for some feeds

### ISSUE THREAD

**Issue by ArnoldSpyros** [MISP/MISP#6247]
I have enabled 12  feeds and scheduled a fetch_feeds task to run every 24 hours.  
When I fetch feeds manually all tasks are completed successfully without any issue. Nevertheless, when I schedule the fetch_feeds task, the scheduled fetch_feeds task is stuck for some feeds

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 
| OS version (client)       | 20.04
| PHP version               | 7.4.9
| MISP version / git hash   | 2.4.130, hash of the commit
| Browser                   | all

### Expected behavior
Fetch all feeds and complete all jobs.

### Actual behavior
The scheduled fetch job is stuck for some of the enabled feeds.

### Steps to reproduce the behavior
Enable feeds and schedule a fetch_feeds task

### Logs, screenshots, configuration dump, ...
![MISP_scheduled_task](https://user-images.githubusercontent.com/21114687/91530566-01616800-e914-11ea-9d8b-8ccc1655eb2e.png)

**Comment by ArnoldSpyros** [comment]
@iglocska Any idea regarding the cause of this bug?

**Comment by mokaddem** [comment]
@ArnoldSpyros Any interesting entries from the logs in `/app/tmp/logs/*`?
Also, if you have the opportunity, I would recommend to switch from the scheduler to CRON jobs as the built-in scheduler is slowly being deprecated.
