### ISSUE TITLE
Database sanity checks potentially lead to unwanted actions from admins

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#6248]
Currently the DB sanity check lists a set of fixes to bring the db schema up to date - however, if the db_version is lagging behind it should instead tell the admin to fix the lock on the update process / start an update worker.

Admins are otherwise falsely encouraged to implement the changes introduced by the update mechanism manually, leading to missing data level changes that should follow via the normal process.

**Comment by mokaddem** [comment]
Fixed in 5a3f50e3a606a9b58ce1f5dd524f2d6828c0a00d
