### ISSUE TITLE
Error 500 on fresh install - RHEL.  

### ISSUE THREAD

**Issue by SirSpectacles** [MISP/MISP#6253]
**Environment**

Type of issue | support
OS version (server) | RHEL 7
OS version (client) | Windows 10
PHP version | 7.2.7
MISP version / git hash | fresh pull
Browser | Chrome and IE

_The following packages were installed_ 

yum install -y php php-mysql php-opcache misp misp-modules

This error has been seen before in https://github.com/MISP/MISP/issues/2253 but there is no resolution.

**Expected behavior**
Having installed on RHEL I am unable to browse to the console through the browser.  

**Actual behavior**
Error 500

**Error message**
PHP Fatal erro                   r:  Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/E                   rror/ErrorHandler.php:261\nStack trace:\n#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.                   php(212): ErrorHandler::handleFatalError(256, '[MissingPluginE...', '/var/www/MISP/a...', 138)\n#1 [in                   ternal function]: ErrorHandler::handleError(256, '[MissingPluginE...', '/var/www/MISP/a...', 138, Arra                   y)\n#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[MissingPlug                   inE...', 256)\n#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::ha                   ndleException(Object(InternalErrorException))\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHa                   ndler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)\n#5                    /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Inte                   rn...', '/var/www/MISP/a...', 261, Array)\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943)                   : App::_checkFat in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 261

**Comment by NailBash** [comment]
Are you fully followed this install guide https://misp.github.io/MISP/INSTALL.rhel7/? It's say that should be installed this packages too
![изображение](https://user-images.githubusercontent.com/29750691/91834271-3eee2a00-ec61-11ea-905f-d516dde89cd8.png)

**Comment by SirSpectacles** [comment]
Yes all of those packages have been installed :
sudo yum install rh-php72 rh-php72-php-fpm rh-php72-php-devel rh-php72-php-mysqlnd rh-php72-php-mbstring rh-php72-php-xml rh-php72-php-bcmath rh-php72-php-opcache rh-php72-php-zip rh-php72-php-gd 

as well as the ones mentioned in the Misp-modules:
sudo yum install openjpeg-devel gcc-c++ poppler-cpp-devel pkgconfig python-devel redhat-rpm-config -y

Im still getting the same error message.

**Comment by NailBash** [comment]
Are you shure that you php package is 7.2?

**Comment by SirSpectacles** [comment]
yup 

-bash-4.2$ php -v
PHP 7.2.27 (cli) (built: Feb 14 2020 16:37:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.27, Copyright (c) 1999-2018, by Zend Technologies

**Comment by NailBash** [comment]
Well, I can't help you. In my case problem was in wrong php package version. Sorry.

**Comment by NailBash** [comment]
Also you can check memory settings in php.ini of rh-php. It may be too little memory values.

**Comment by iglocska** [comment]
Sounds like you're missing a plugin - are you sure you didn't miss some steps in the installer? Can you see CakeResque in /var/www/MISP/app/Plugin ?

**Comment by SirSpectacles** [comment]
Hey all - turns out we made an error in one of our sed expressions

How we knew that was by running the worker threads:  

sudo -u apache /var/www/MISP/app/Console/worker/start.sh

    Error: syntax error, unexpected '''' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read('config')
#1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load('config')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct(Array)
#8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
 
The change was 👍 
sed -i "s/'baseurl'.* /'baseurl' => 'https:\/\/$hostname\/'/" /var/www/MISP/app/Config/config.php
sed -i "s/'baseurl'.*/'baseurl' => 'https:\/\/$HOSTNAME\/'**,**/" /var/www/MISP/app/Config/config.php

**Comment by SirSpectacles** [comment]
The missing plugin part was a bit of a red herring it seemed

**Comment by iglocska** [comment]
Interesting, thanks for the follow-up! :)

**Comment by chrisinmtown** [comment]
@SirSpectacles if this is resolved, you may wish to close this issue.

**Comment by SirSpectacles** [comment]
closing out with thanks
