### ISSUE TITLE
PyMISP error when fetching vendor feed

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#6260]
Questions | Answers
-- | --
Type of issue | Bug
OS version (server) | RHEL, with MISP running on a docker container..
OS version (client) | MacOS, Win10,
PHP version | 5.4, 5.5, 5.6, 7.0, 7.1...
MISP version / git hash | 2.4.XX, hash of the commit
Browser | If applicable

I am getting this error when i am running a python3 script to fetch a vendor feed. It happened to me before but i forgot the fix. Something simple i think.

oot@c4c24591fa41:/var/www/MISP/PyMISP-doug# python3 PySight3.py
WARNING [__init__.py:48 - <module>() ] Unable to load pymisp properly: No module
 named 'deprecated'
Traceback (most recent call last):
  File "PySight3.py", line 20, in <module>
    from pymisp import ExpandedPyMISP, MISPEvent, MISPObject
ImportError: cannot import name 'ExpandedPyMISP'

**Comment by Rafiot** [comment]
Hmmm what is PySight3.py? Can you share it?

**Comment by dmolina213** [comment]
I think you help me once before.


https://github.com/dmolina213/PyMISP-doug/blob/master/PySight3.py

**Comment by Rafiot** [comment]
okay, I'll not dig into it much more tonight, but if you just rename ExpandedPyMISP -> PyMISP, it may just work.

**Comment by dmolina213** [comment]
If I remember, I thought I added the name of the module in one of the files that got it to work

V/R
Help Me, Help You
Douglas P Molina, MBA, CISSP, C|EH, CySA+,CCSK,GCTI
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 202 779 2034
UNCLASS: douglas.molina@va.gov<mailto:douglas.molina@va.gov>
[cid:image001.jpg@01D67FA9.05DA1FF0]

**Comment by Rafiot** [comment]
Wait, I misread the error message. 
=> `No module named 'deprecated'` 
how did you install pymisp? That look like the module `deprecated` is not there, and I bet it is the first module it tries to load, so it will fail on all the subsequent ones.

**Comment by dmolina213** [comment]
We have misp running on a docker container and for some reason it crashed. We brought up a new container. However, I noticed the directory where all my PyMISP scripts are located was missing. We were able to grab it from the old container. It was a simple copy and paste. Should i re-install PyMISP? BTW, no were in my script I am using a moduile named 'deprecated'

**Comment by Rafiot** [comment]
yes, `deprecated` is used by PyMISP, and should be installed in order for you to be able to use the module. You can also do `pip install deprecated`, rerun your script, and see which other depending is missing.

**Comment by dmolina213** [comment]
that worked, Thank you for your help
