### ISSUE TITLE
Some vhash cannot be added to MISP

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#6266]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | v2.4.130 (d9605eebd5634e0b1acfbfaedd32a3a813f80803)

Certain vhash are not accepted by MISP.

This one is accepted: 035056655d15751018z5oz8fz

This one is not accepted and produces the error below: 156056151d1515cz805&z1

![vhash_not_accepted](https://user-images.githubusercontent.com/8250365/91862256-54e4f600-ec33-11ea-8d47-20c1074d8edf.JPG)

**Comment by rmkml** [comment]
Hello @timhux123 , thx for your report, Im curious what is sha256 for vhash 156056151d1515cz805&z1 please ? Best Regards @rmkml

**Comment by timhux123** [comment]
Hello - The vhash is for many hashes. Here are a few:

4daded32bdf46a5298c40fefedb2726d4ea22997f45dff24e81c1a65ff6cbd09
cc9c10c18cd5eb47bdb5564f0559aaad85e26b641996e9bea6b581156510060f
9718035ed3ec4d00dc41a263f4798169aed07535b8d42e1deb21dc40bde1d2cd

**Comment by rmkml** [comment]
ok push #6325 for fix this.
Thx for your report.
Best
@rmkml

**Comment by samitainio** [comment]
@adulau @rmkml 

I came across another two vhashes that are not accepted after the initial fix in #6325

vhash: `035066655d1d15556018z76!z`
sha256: `eb8883d23bca4d9be3423db41b417c2dce4e1ba5cf2a317fc2d460d99006765f`

vhash: `034036551d1bz22e=z`
sha256: `c9d5dc956841e000bfd8762e2f0b48b66c79b79500e894b4efa7fb9ba17e4e9e`

| Test case | `filename\|vhash` | `vhash` |
| :--- | :---:  | :---: |
| Previous fix | `#^.+\\|[a-zA-Z0-9&]+$#` | `/^[a-zA-Z0-9&]+$/` |
| Proposed fix | `#^.+\\|[a-zA-Z0-9&!=]+$#` | `/^[a-zA-Z0-9&!=]+$/` |
