### ISSUE TITLE
Get Taxonomy Exclusivity via API

### ISSUE THREAD

**Issue by TheDr1ver** [MISP/MISP#6269]
I would like to be able to query (and enforce) a tag's exclusivity property via the API. Currently almost everything about a taxonomy is returned via API request except for the exclusivity values.

My use case is semi-related to syncing and tag-deletion ( See #2223 ).

**Setup**
- I have two internal servers, `ServerA` and `ServerB`. Both belong to the same org and are syncing as internal servers.
- I have a custom taxonomy deployed and activated on both servers that includes the exclusive predicate "label" such that an attribute cannot be tagged as `org:label="malicious"` and `org:label="safe"` at the same time.

**Scenario**
- `ServerA/Event_1/badguy[.]com` I tag as `org:label="safe"`
- I publish `ServerA/Event_1` and it syncs with `ServerB`, creating `ServerB/Event1` where `badguy[.]com` is tagged as `org:label="safe"`
- Later, I change my mind. I remove `org:label="safe"` from `ServerA/Event_1/badguy[.]com` and change it to `org:label="malicious"`
- I republish `ServerA/Event_1` and it syncs with `ServerB`.
- `ServerB/Event_1/badguy[.]com` is now tagged as both `org:label="safe"` and `org:label="malicious"`, breaking the exclusivity model.

**Proposed work-around**

Since tag-deletion is not yet covered by syncing ( #2223 ), I figured I could run a ZMQ listener on each server such that whenever it sees `action="attached to attribute"` with an associated tag it could query the taxonomy and determine if there are any exclusivity conflicts between the newly attached tag and any existing tags. Then, if a conflict is presented, I could have the newly attached tag stay attached while the old, conflicting tag would be removed. Ideally this taxonomy exclusivity data could be captured by the API.

Alternatively (and what I might do in the meantime), I could have my ZMQ listener read the raw taxonomy JSON from disk to determine if a predicate (or a namespace for that matter) is supposed to be mutually exclusive, but that seems kinda sloppy compared to all the other actions currently available via API.

**Comment by mokaddem** [comment]
Hey @TheDr1ver, 
Commit 60d1adb1cffd19ff9719dcaa36fa6b3162153784 added a new behavior to the `/taxonomies/view/[id]` endpoint. It returns the `exclusive` flag for both the whole taxonomy or for individual predicates (new behaviors).
You can try out the output for these taxonomies:
- `misp` taxonomy: mixes predicates with `exclusive` flag
- `tlp` taxonomy: `exclusive` flag on the whole taxonomy

Also, commit 106fa7300a623ee5d8b1f9b747353a4591e10172 introduces a new feature `runTaxonomyExclusivityCheck`. By querying `/events/runTaxonomyExclusivityCheck/[id]`, you can check if there is a conflict in the event. It looks at both the event and attribute's tags distinguishing `local` and `global` scope.

Fell free to try out the feature on this test event
[misp.event.167.zip](https://github.com/MISP/MISP/files/5495247/misp.event.167.zip)

**Comment by TheDr1ver** [comment]
This Taxonomy update looks great, thanks!
