### ISSUE TITLE
Display a warning about RFC1918, RFC6761 and a list of local IP addresses

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#627]
A lot of users when entering attributes might enter IP addresses or domain names that are special use (like localhost, localdomain, private IP addresses or some "golden/stable" networks (e.g. 8.8.8.8). The proposal is to block the addition of such network but to provide a warning when an event contains such attribute. The administrator of the system could also have a list of local IP addresses that could generate such warning in the interface.

**Comment by iglocska** [comment]
Interesting, indeed right now the only way is to block them with blacklists, I'll look into a way of having a secondary list that will only be used for warning.

**Comment by Rafiot** [comment]
Fixed with warning lists.
