### ISSUE TITLE
CSV download empty

### ISSUE THREAD

**Issue by max2204** [MISP/MISP#6273]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | MacOS
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.130, bab68641aa4fc5a8b209a07c2a98293de4ad0567
| Browser                   | Firefox, Chrome

### Expected behavior
Download CSV of an event including attributes according to https://www.circl.lu/doc/misp/automation/#csv-export

### Actual behavior
Download with authenticated Browser via /events/csv/download/event-id results in 
CSV with just having the header, no attribute data.

Notes:
CSV download via /events/restSearch/returnFormat:csv/eventid:event-id works fine.
CSV download in event context with "Download as" => CSV works fine.

### Steps to reproduce the behavior
Used clean install of MISP 2.4.130 with Ubuntu 18.04. and documentation https://misp.github.io/MISP/INSTALL.ubuntu1804/
with parameter Core install.

**Comment by mokaddem** [comment]
Hello,

`/events/csv/download/[event-id]` is indeed deprecated and `events/restSearch` should be used instead.

Just as a side note, the csv file is probably empty because your event is not published or your attributes don't have the `to_ids` flag set.
