### ISSUE TITLE
MISP Install

### ISSUE THREAD

**Issue by guaar** [MISP/MISP#6283]
Hi,
I am trying to install MISP, I have installed MISP in the past and it has been a very straight forward process, however this time I am facing some issues. 
In past, I have only had to to perform the below to install misp.

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

However, this time around, the above doesn't work. Although the core dependencies download,however when navigating to the IP of MISP, it shows default Ubuntu Apache Page.  
I don't see any conf files under sites-available directory .

Can anyone please tell me what I am doing wrong here?

Thanks.

**Comment by chrisinmtown** [comment]
you might want to post what linux version you're using.

**Comment by jamesgarside** [comment]
I too am experiencing this on Ubuntu 20.04.
