### ISSUE TITLE
PUSH to remote server hangs at 97%

### ISSUE THREAD

**Issue by healthrage** [MISP/MISP#6285]
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RHEL7

| PHP version               | 7.2
| MISP version / git hash   | 2.4.130
| Browser                   | If applicable

### Support Questions
Brand new build on RHEL7. I can preview the server and pull down events but I cannot push them to the remote server.

### Logs, screenshots, configuration dump, ...
Error: Argument 1 passed to Server::getEventIdsFromServer() must be of the type array, boolean given, called in /var/www/MISP/app/Model/Server.php on line 3129
#0 /var/www/MISP/app/Model/Server.php(3129): Server->getEventIdsFromServer(false, true, Object(HttpSocket), true)
#1 /var/www/MISP/app/Model/Server.php(3029): Server->syncProposals(Object(HttpSocket), false, NULL, NULL, Object(Event))
#2 /var/www/MISP/app/Console/Command/ServerShell.php(172): Server->push('1', 'full', '12', Object(HttpSocket), Array)
#3 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->push()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#9 {main}
Pull completed. 2 events pulled, 0 events could not be pulled, 0 proposals pulled, 0 sightings pulled.
Error: Argument 1 passed to Server::getEventIdsFromServer() must be of the type array, boolean given, called in /var/www/MISP/app/Model/Server.php on line 3129
#0 /var/www/MISP/app/Model/Server.php(3129): Server->getEventIdsFromServer(false, true, Object(HttpSocket), true)
#1 /var/www/MISP/app/Model/Server.php(3029): Server->syncProposals(Object(HttpSocket), false, NULL, NULL, Object(Event))
#2 /var/www/MISP/app/Console/Command/ServerShell.php(172): Server->push('1', 'full', '1', Object(HttpSocket), Array)
#3 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->push()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#9 {main}

![image](https://user-images.githubusercontent.com/55511466/92159840-0afb3c00-edfc-11ea-9a14-5b9ffef081f8.png)

**Comment by joepitt91** [comment]
Same issue on 

Ubuntu 20.04
MISP v2.4.131 (69955d2fc62cea8263776870c2734a319ae2fe18)
PHP 7.4.3

Clean install from `INSTALL.sh` today, initially syncing worked, then suddenly stopped with no obvious cause, ironically I set up some boxes to test out sharing groups

```bash
/var/www/MISP/app/Console/cake Server push 1 2

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
bool(false)
Error: Argument 1 passed to Server::getEventIdsFromServer() must be of the type array, bool given, called in /var/www/MISP/app/Model/Server.php on line 3130
#0 /var/www/MISP/app/Model/Server.php(3130): Server->getEventIdsFromServer()
#1 /var/www/MISP/app/Model/Server.php(3029): Server->syncProposals()
#2 /var/www/MISP/app/Console/Command/ServerShell.php(172): Server->push()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->push()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run()
#7 {main}
```

The above fix now returns
```bash
$ /var/www/MISP/app/Console/cake Server push 1 2

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

and the jobs page shows it as done, but the 2 new community level events do not appear on the remote servers.

**Comment by joepitt91** [comment]
Ah, the new events from Server A were not showing on Server B, as the sync user on Server B being used to push belongs to Server A's org, so when it got ot Server B it was being set to org only.

Above fix appears to work as expected

**Comment by JakubOnderka** [comment]
Thanks for testing @joepitt91!

**Comment by healthrage** [comment]
Am I supposed to test something to see if it works with my instance. I am not sure where to look for these logs to determine why it is hanging or if it finishes without pushing anything.

**Comment by joepitt91** [comment]
There shouldn't be any need to rest, as the changes have been merged and should be included in the next release.

**Comment by enjeck** [comment]
> There shouldn't be any need to rest, as the changes have been merged and should be included in the next release.

@healthrage Can you please confirm if this issue no longer exists?
