### ISSUE TITLE
LDAP Authentication 

### ISSUE THREAD

**Issue by adthomson** [MISP/MISP#6292]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.2
| MISP version / git hash   | MISP 2.4.130 
| Browser                   | Chrome / Safari

### Support Questions
I've followed the guide in #6189, I can successfully authenticate through LDAP then I'm redirected to https://localhost/users/login and presented a 500 with the message: "An Internal Error Has Occurred".  Every time I attempt to authenticate the error logs suggest that the email column cannot be null. My initial thoughts are that an email address isn't being retrieved from AD when the LDAP query runs, can I verify what data is being returned from the LDAP query?

Are there any other idea around why this may be happening?

### Logs, screenshots, configuration dump, ...
**default-ssl.conf**
        <Location "/">
                AuthType Basic
                AuthBasicProvider ldap
                AuthName "LDAP Authentication"
                AuthLDAPURL "ldap://my-domain.co.uk:389/dc=domain,dc=co,dc=uk?userPrincipalName?sub?(objectclass=*)"
                AuthLDAPInitialBindAsUser on
                Require valid-user
        </Location>

**config.php**
array(
                        'apacheEnv'          => 'REMOTE_USER', 
                        'ldapServer'         => 'ldap://my_domain.co.uk:389',
                        'ldapProtocol'       => 3,
                        'ldapNetworkTimeout' => -1,  
                        'ldapReaderUser'     => 'CN=me,OU=test,OU=test,DC=domain,DC=co,DC=uk', 
                        'ldapReaderPassword' => 'Password',
                        'ldapDN'             => 'CN=Users,DC=domain,DC=co,DC=uk',
                        'ldapSearchFilter'   => '',
                        'ldapSearchAttribut' => 'userprincipalname',  
                        'ldapFilter'         => array('mail',),
                        'ldapDefaultRoleId'  => 3, 
                        'ldapDefaultOrg'     => '1',     
                        'ldapAllowReferrals' => false,
                        'ldapEmailField' => array('mail'),
        ),

**/var/www/MISP/app/tmp/logs/error.log**
`2020-09-07 15:40:27 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(User), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/Component/Auth/ApacheAuthenticate.php(164): Model->save(Array, false)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): ApacheAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#8 /var/www/MISP/app/Controller/UsersController.php(1136): AuthComponent->login()
#9 [internal function]: UsersController->login()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}`

**misp_ssl_access.log**
`172.17.0.1 - me@mydomain.com [07/Sep/2020:15:38:19 +0000] "GET /users/login HTTP/1.1" 500 6221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:39:08 +0000] "GET / HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:39:09 +0000] "GET / HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:39:09 +0000] "GET / HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:39:10 +0000] "GET / HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:39:10 +0000] "GET / HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:39:24 +0000] "GET / HTTP/1.1" 302 813 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:39:24 +0000] "GET /users/login HTTP/1.1" 500 5710 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:40:26 +0000] "GET /events/index HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - - [07/Sep/2020:15:40:27 +0000] "GET /events/index HTTP/1.1" 401 3420 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /events/index HTTP/1.1" 302 813 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /users/login HTTP/1.1" 500 5710 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/bootstrap-datepicker.css?110 HTTP/1.1" 200 3040 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/bootstrap-colorpicker.css?110 HTTP/1.1" 200 4073 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/bootstrap.css?110 HTTP/1.1" 200 21551 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/jquery-ui.css?110 HTTP/1.1" 200 11554 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/chosen.min.css?110 HTTP/1.1" 200 3196 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/famfamfam-flags.css?110 HTTP/1.1" 200 5076 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /js/misp-touch.js?110 HTTP/1.1" 200 835 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/main.css?110 HTTP/1.1" 200 9668 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/jquery-jvectormap-2.0.5.css?110 HTTP/1.1" 200 3923 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/distribution-graph.css HTTP/1.1" 200 1295 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /css/vis.css HTTP/1.1" 200 4744 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /js/chosen.jquery.min.js?110 HTTP/1.1" 200 7130 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/network-distribution-graph.js HTTP/1.1" 200 5282 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /css/font-awesome.css?110 HTTP/1.1" 200 13036 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/bootstrap-colorpicker.js?110 HTTP/1.1" 200 7383 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/bootstrap.js?110 HTTP/1.1" 200 11764 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/bootstrap-timepicker.js?110 HTTP/1.1" 200 6529 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/keyboard-shortcuts.js?110 HTTP/1.1" 200 1881 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /webfonts/fa-solid-900.woff2 HTTP/1.1" 304 204 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /css/print.css?110 HTTP/1.1" 200 593 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/bootstrap-datepicker.js?110 HTTP/1.1" 200 14025 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /js/jquery.js?110 HTTP/1.1" 200 85868 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /js/vis.js HTTP/1.1" 200 175819 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:28 +0000] "GET /js/misp.js?110 HTTP/1.1" 200 35521 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"
172.17.0.1 - me@mydomain.com [07/Sep/2020:15:40:27 +0000] "GET /js/jquery-ui.js?110 HTTP/1.1" 200 125691 "https://localhost/events/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15"`

**misp_ssl_error.log**
`[Mon Sep 07 15:39:24.422058 2020] [authnz_ldap:debug] [pid 2239] mod_authnz_ldap.c(523): [client 172.17.0.1:44772] AH01691: auth_ldap authenticate: using URL ldap://my-domain:389/dc=xxxx,dc=co,dc=uk?userPrincipalName?sub?(objectclass=*)
[Mon Sep 07 15:39:24.422106 2020] [authnz_ldap:debug] [pid 2239] mod_authnz_ldap.c(620): [client 172.17.0.1:44772] AH01697: auth_ldap authenticate: accepting user@mydomain.co.uk
[Mon Sep 07 15:39:24.422122 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of Require valid-user : granted
[Mon Sep 07 15:39:24.422147 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of <RequireAny>: granted
[Mon Sep 07 15:39:24.422233 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Mon Sep 07 15:39:24.422245 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Mon Sep 07 15:39:24.422263 2020] [authnz_ldap:debug] [pid 2239] mod_authnz_ldap.c(523): [client 172.17.0.1:44772] AH01691: auth_ldap authenticate: using URL ldap://my-domain:389/dc=xxxxx,dc=co,dc=uk?userPrincipalName?sub?(objectclass=*)
[Mon Sep 07 15:39:24.422292 2020] [authnz_ldap:debug] [pid 2239] mod_authnz_ldap.c(620): [client 172.17.0.1:44772] AH01697: auth_ldap authenticate: accepting user@mydomain.co.uk
[Mon Sep 07 15:39:24.422307 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of Require valid-user : granted
[Mon Sep 07 15:39:24.422322 2020] [authz_core:debug] [pid 2239] mod_authz_core.c(809): [client 172.17.0.1:44772] AH01626: authorization result of <RequireAny>: granted
[Mon Sep 07 15:39:24.684225 2020] [ssl:debug] [pid 2239] ssl_engine_io.c(1106): [client 172.17.0.1:44772] AH02001: Connection closed to child 1 with standard shutdown (server localhost@local:443)`

**Comment by moqua** [comment]
Hi mate!

I am at the same point, getting "Column 'email' cannot be null"

Did you find a solution?

Kind regards,
Clemens

**Comment by adthomson** [comment]
Hi @moqua, 

Check your config.php and validate that your configuration is correct - that's what was causing my issues. I was able to debug the configuration issue by printing out the variables from  app/Controller/Component/Auth/ApacheAuthenticate.php. 

Its worth trying to print out the $ldapUserData array as this should contain the mail field and work back from here until you find out which piece of configuration is causing the problem: https://github.com/MISP/MISP/blob/34a1671e8af5916f578db3565c86151fceb51745/app/Controller/Component/Auth/ApacheAuthenticate.php#L96

**Comment by moqua** [comment]
Hey @adthomson,

thanks for the input. In the meantime i got it working, switching back from ldaps to ldap and using ldapsearch + wireshark.

In our case the AD object "mail" does not exist, i needed to use "name". Here the working example:

ApacheSecureAuth' => array(
 'apacheEnv'          => 'REMOTE_USER', // user123@domain234.com
 'ldapServer'         => 'ldaps://server',
 'ldapProtocol'       => 3,
 'ldapNetworkTimeout' => -1,
 // Note that we need a service account here.
 'ldapReaderUser'     => 'CN=user456,OU=User,DC=w,DC=x,DC=domain234,DC=com',
 'ldapReaderPassword' => 'superpassword',
 'ldapDN'             => 'OU=Administrator,OU=User,DC=w,DC=x,DC=domain234,DC=com',
 'ldapSearchFilter'   => '', // I don't use that. Maybe you should
 'ldapSearchAttribut' => 'userPrincipalName',  // user123@domain234.com
 'ldapFilter'         => array('name',), // user123
 'ldapDefaultRoleId'  => 3,   // this will create users
 'ldapDefaultOrg'     => '1',      // uses 1st local org in MISP if undefined,
 'ldapEmailField' => array('name'), // user123
),

Thanks and kind regards,
Clemens

**Comment by Mixtol** [comment]
Same case, fixed by using lower case

```
    'ldapEmailField' =>
    array (
      0 => 'userprincipalname',
      1 => 'UserPrincipalName',
    ),

```
