### ISSUE TITLE
orgc_id column indexed on 2.4.130

### ISSUE THREAD

**Issue by konradx** [MISP/MISP#6295]
Fresh install 2.4.130 on Debian 10.5.
This could be somehow related to https://github.com/MISP/MISP/issues/6229 except that: column orgc_id is indexed but the message says it shouldn't.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| PHP version               | 7.3
| MISP version / git hash   | 2.4.130
| Browser                   | Chrome

### Logs, screenshots, configuration dump, ...
![misp_orgc_id](https://user-images.githubusercontent.com/5104596/92413571-02cf3380-f151-11ea-9602-c1ddb2f49819.png)

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in latest `2.4` branch.
