### ISSUE TITLE
Undefined offset in caching file

### ISSUE THREAD

**Issue by JessScull** [MISP/MISP#6299]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.05
| PHP version               | 7.4.9
| MISP version / git hash   | 2.4.131
| Browser                   | N/A

### Expected behavior
Until today I could access 'diagnostics' and 'jobs' on the GUI

### Actual behavior
After a reboot I am getting the "Internal Server Error" when I try to connect to diagnostics and jobs. I have looked in the logs on the CLI and have found the following. The issue started around 15:00 so matches the errors in the error.log regarding caching.ctp. I have made no amendments to this file

### Steps to reproduce the behavior
Accessing diagnostics *& jobs on the GUI
Checking the logs 

### Logs, screenshots, configuration dump, ...

Error on server settings & maintenance

![image](https://user-images.githubusercontent.com/59572037/92492663-84739f80-f1eb-11ea-8cd3-3b922477e4d2.png)

Errors.log
![image](https://user-images.githubusercontent.com/59572037/92492583-63ab4a00-f1eb-11ea-92e0-132ea1a6996a.png)

This is a screenshot of the ctp file
![image](https://user-images.githubusercontent.com/59572037/92492599-686ffe00-f1eb-11ea-89fa-1e18a0901e0a.png)

**Comment by mokaddem** [comment]
Hello,
Sorry for not getting back to you.
Could you please update your MISP instance to the latest version and check that all files have the correct permissions?

> Error on server settings & maintenance

These are not errors, they are warning that some MISP setttings should be changed (it's not required to have a running MISP instance)

> Errors.log

After updating, could you try again and come back to us if you spot this issue again?

> This is a screenshot of the ctp file

Screenshot like this are welcome but providing entries of your `errors.log` along with your current commit id is much more helpful! ;)

Thanks a lot!
