### ISSUE TITLE
connecting from misp ec2 to RDS

### ISSUE THREAD

**Issue by dazed51** [MISP/MISP#6302]
Hello, 

I was wondering what is the best way for the misp app to talk to the RDS instance. I migrated the local sql database from the mysql database that was installed and configured on the ec2 via the misp install script.

I installed misp using the script, but wanted to leverage RDS. Not finding any clear way for misp application to talk to the RDS instance. 

Any insight would be great, Thanks

**Comment by adulau** [comment]
Maybe you want to open an issue for Amazon related question to https://github.com/misp/misp-cloud @0xtf might be a good contact for such question. Thank you.
