### ISSUE TITLE
Installing MISP Module

### ISSUE THREAD

**Issue by guaar** [MISP/MISP#6303]
Hi,
I am trying to get the recorded future enrichment working in MISP. I can see that the Recorded Future script exists in the misp-modules directory. I have followed this guide to install and start misp modules: https://github.com/MISP/misp-modules

When I perform command:  /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & #to start the modules
I get prompt that misp module service is still running as PID. When I attempt to kill that PID, it then prompts that there is no such process. 

Can anyone help, how can I get this enrichment module to appear under plugin options?

OS Version: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

Thanks.

**Comment by guaar** [comment]
Any help on this please?

**Comment by adulau** [comment]
"I get prompt that misp module service is still running as PID. When I attempt to kill that PID, it then prompts that there is no such process." It sounds like you have an issue on your operating system.  Can you share the exact commands and output? I will close the issue until such output are provide. Thank you very much.
