### ISSUE TITLE
Add LDAP config in the generic config system, update FAQ

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#6306]
* [ ] Add LDAP/AD config in the generic config system instead of hafing to do it manually
* [ ] Great documentation there: https://github.com/MISP/MISP/issues/6189#issuecomment-673767583

**Comment by adulau** [comment]
There is now a standalone LDAP authenticator in MISP which could clearly help in such scenario.

https://github.com/MISP/MISP/tree/29993e516825b8ff35a72419fa61c40472eb1898/app/Plugin/LdapAuth
