### ISSUE TITLE
Date Picker on Add Event not showing up

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#6309]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.4.9
| MISP version / git hash   | v2.4.131 (80fa3bd4166b73d2db10b0d61d73e8208fdcf64c)
| Browser                   | Chrome

### Expected behavior
![before-update-version-number](https://user-images.githubusercontent.com/71141213/92943480-688b2a80-f485-11ea-8a3a-d476eff4ef43.PNG)
Before update version

![before-update-datepicker-ok](https://user-images.githubusercontent.com/71141213/92943541-7b9dfa80-f485-11ea-8da4-80c79ee1cd17.PNG)
The datepicker is showing up.

### Actual behavior
![after-update-version-number](https://user-images.githubusercontent.com/71141213/92943592-8a84ad00-f485-11ea-9afd-9fe1f8893bbb.PNG)
After update version

![after-update-datepicker-not-ok](https://user-images.githubusercontent.com/71141213/92943611-91132480-f485-11ea-860d-98ea0546039d.PNG)
The datepicker is not showing up

### Steps to reproduce the behavior
Event Actions > Add Event > Click on Date

### Logs, screenshots, configuration dump, ...
After comparing both version's at the inspect element.
It seems like the styles for datepicker-days is missing.
![diff](https://user-images.githubusercontent.com/71141213/92943784-c91a6780-f485-11ea-8bf4-0e20001a61e7.PNG)

If change it at inspect element, the datepicker is showing up.
![inspect-element](https://user-images.githubusercontent.com/71141213/92943686-a9833f00-f485-11ea-8fa6-16d93d8dbc7d.PNG)

Kindly assist on this. Thank you.

**Comment by BurakOzgen** [comment]
Yes this problem occured in 2.4.131 for us too. We are using the date picker quite lot. I hope this will be fixed as soon as possible.

Best Regards,

**Comment by mokaddem** [comment]
This was due to the recent update of jquery.
The picker has been updated to the latest version in ff9f14d1f98c63c3a00fab385a9446a4e3532ced
Thanks for the notification!
