### ISSUE TITLE
Job Type Push not working

### ISSUE THREAD

**Issue by TrustedForce** [MISP/MISP#631]
I am currently testing MISP, and am having trouble pushing data to other MISP instances. It also looks like "publish_alert_email" is not working. Could you please point me to which logs I should look at?

**Comment by cvandeplas** [comment]
You should be able to find logs in the app/tmp/logs folder.

Also in the web-interface there's the Administration > Server Settings page
that should give you a view of issues with your installation.

**Comment by TrustedForce** [comment]
I've gone though the logs in /tmp/logs and found no helpful information, and I've checked the diagnostics for the server, which comes back clean. Is there anything you can think of that would prevent me from pushing an event?

**Comment by cvandeplas** [comment]
Do you see network traffic going out of your server?
(tcpdump or wireshark)

**Comment by TrustedForce** [comment]
Good question. Let me check.

**Comment by TrustedForce** [comment]
While I'm diving into this I should mention that pull and publish_event currently work. They are able to reach 100% on the progress bar without "Connection timed out".

**Comment by iglocska** [comment]
Could you try manually sending an e-mail using the contact users feature (Administration -> contact users)? Does that work?

**Comment by elhoim** [comment]
@TrustedForce ping

**Comment by elhoim** [comment]
@TrustedForce Any update? If not, I will consider this handled and close.
