### ISSUE TITLE
2.4.131 - Freetext import tool - the queried function returned an exception

### ISSUE THREAD

**Issue by LuckyS3v3n** [MISP/MISP#6312]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 18.04 LTS Bionic
| PHP version               | 7.4
| MISP version / git hash   | v2.4.131 (5d3dee3ba20be9950324943e5f8787ecb9a8522f)
| Browser                   | Chrome

### Support Questions
After upgrade to v2.4.131 got following error "Something went wrong - the queried function returned an exception. Contact your administrator for further details." when try to add data using "Freetext import tool"

No errors seen on error.log for this issue.

Currently installed version… v2.4.131 (5d3dee3ba20be9950324943e5f8787ecb9a8522f)
Latest available version… v2.4.131 ()
Status… OK
Current branch… 2.4

PHP Settings
PHP ini path:… /etc/php/7.4/apache2/php.ini
PHP Version (>7.4 recommended): 7.4.10 (Up to date)
PHP CLI Version (>7.4 recommended): 7.4.10 (Up to date)

**Comment by LuckyS3v3n** [comment]
**Upgraded to v2.4.132, error still appears, free text import tool cannot be used.**

Currently installed version… v2.4.132 (abb981dbe5b236c55116e15eb47d4b269d77f3a0)
Latest available version… v2.4.132 ()
Status… OK
Current branch… 2.4

**Comment by JakubOnderka** [comment]
What data you trying to enter? Is this bug there also for example for `8.8.8.8`?

**Comment by LuckyS3v3n** [comment]
the error happens just before

![image](https://user-images.githubusercontent.com/29771706/93358382-ae5b4080-f841-11ea-8290-f2d83076b02c.png)

**Comment by iglocska** [comment]
Right after it does that, could you check the last entries in
/var/www/MISP/app/tmp/log/error.log?

**Comment by LuckyS3v3n** [comment]
Hi iglocska,
As i said, no errors regarding this issue are found under error.log or debug.log.

meanwhile i just found this:
![image](https://user-images.githubusercontent.com/29771706/93433827-9deda900-f8c7-11ea-8c53-5615ec78f33f.png)

Content is being partially blocked by CORS policy
![image](https://user-images.githubusercontent.com/29771706/93434853-f1acc200-f8c8-11ea-900b-6426f6f6218b.png)

Trying to open MISP without CORS policy doesn´t work.
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --disable-gpu

Content is being partially served in plain text
![image](https://user-images.githubusercontent.com/29771706/93435175-5536ef80-f8c9-11ea-85a9-060609a5be00.png)

**Comment by iglocska** [comment]
Interesting, what is your baseurl in MISP set to? administration -> server config -> MISP settings tab -> MISP.baseurl

**Comment by LuckyS3v3n** [comment]
NICE! that´s the problem, base url was overwritted to http from https during upgrade

![image](https://user-images.githubusercontent.com/29771706/93472873-980ebc80-f8f5-11ea-965b-4b499f1d8627.png)

**Comment by iglocska** [comment]
that should never happen during an update, very curious how that happened o.O

**Comment by LuckyS3v3n** [comment]
yes, i think so
