### ISSUE TITLE
Help with 2FA (using privacyidea)

### ISSUE THREAD

**Issue by icepaule** [MISP/MISP#6314]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.24-0ubuntu0.18.04.6 (Update highly recommended)
| MISP version / git hash   | v2.4.131 (5d3dee3ba20be9950324943e5f8787ecb9a8522f)
| Browser                   | Chrome

### Support Questions
Could you please explain or hint me to a solution how to enable 2FA for user-logins preferably using [privacyidea](https://www.privacyidea.org/) or any other opensource OTP solution?

Thanks so much for your help and the great stuff you are doing with the MISP. - I'm loving it. ;-)

**Comment by joepitt91** [comment]
TOTP and / or Yubikey would be really useful options to have; many people will already have TOTP apps on their phones.

**Comment by adulau** [comment]
There is a native TOTP/HOTP solution in MISP starting from 2.4.172.
