### ISSUE TITLE
Please provide a valid UUID

### ISSUE THREAD

**Issue by Derekt2** [MISP/MISP#6317]
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | API
| MISP version / git hash   | 2.4.131

### Expected behavior
Event created with specified UUID

### Actual behavior
Error of "Please provide valid UUID", event is not created

### Steps to reproduce the behavior
Create a misp event with pymisp via the API with a UUID of de38ef4c-af25-a4e1-793d-04f3143a4970. Worked in 2.4.129 prior to upgrade to 2.4.131

### Logs, screenshots, configuration dump, ...
`Making event with uuid: de38ef4c-af25-a4e1-793d-04f3143a4970
ERROR [api.py:2297 - _check_response() ] Something went wrong (403): {'saved': False, 'name': 'Could not add Event', 'message': 'Could not add Event', 'url': '/events/add', 'errors': {'Event': {'uuid': ['Please provide a valid UUID']}}}`

**Comment by Derekt2** [comment]
if I upload the exact same event without the uuid specified, it works fine. But I'm using UUIDs to fingerprint data going in to prevent duplicates events from being made from streaming sources.

**Comment by Derekt2** [comment]
I can use UUID 01305348-h4b1-4cc5-8c96-9e3bac1bc1b9 but not UUID 
                         01305348-d4b1-4cc5-8c96-9e3bac1bc1b9 with the same error as above. both are valid sha256 hashes however, and as you can see, the only difference is one character.

**Comment by JakubOnderka** [comment]
Hello, how do you generate UUID? Because your string is not valid RFC 4122 UUID:

```
python
>>> uuid.UUID("de38ef4c-af25-a4e1-793d-04f3143a4970").variant
'reserved for NCS compatibility'
```

**Comment by Derekt2** [comment]
ah I was generating them based on hashes. I'll use RFC 4122 UUIDs instead. Thanks.
