### ISSUE TITLE
Undefined index: ip in [/var/www/MISP/app/View/Logs/admin_index.ctp, line 87]

### ISSUE THREAD

**Issue by Tomasuh** [MISP/MISP#6319]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16.04.4
| OS version (client)       | unknown/multi
| PHP version               | 7.3.6
| MISP version / git hash   | v2.4.132
| Browser                   | not applicable

### Support Questions

We are repeatedly seeing the following error message:

```
2020-09-17 14:07:05 Notice: Notice (8): Undefined index: ip in [/var/www/MISP/app/View/Logs/admin_index.ctp, line 87]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Logs/admin_index.ctp, line 87
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

The "Schema status" in the Diagnostics section makes no mention of this.

Can it be remedied in any easy way by adding an index?

**Comment by chrisinmtown** [comment]
When you say "adding an index" are you thinking about the database?  I don't think that's the right path to investigate.

I pasted the relevant code block from file app/View/Logs/admin_index.ctp below. You might check your MISP configuration for its log_client_ip setting, set it temporarily to False, which will almost certainly stop this error, but that probably isn't what you want.

My guess is that the code fails when it tries using key 'ip' to query a key-value store. Maybe the error message shouldn't say "index" but that's a different issue.  If you can figure out which request leads to the error it will probably be easy to solve. 

```
 83             <?php
 84                 if (Configure::read('MISP.log_client_ip')) {
 85                     echo '<td>';
 86                     if (isset($ipSearch) && $ipSearch != null) echo nl2br($this->Highlight->highlighter(h($item['Log']['ip']), $ipSearchReplacePairs));
 87                     else echo h($item['Log']['ip']);
 88                     echo '</td>';
 89                 }
 90             ?>
```
