### ISSUE TITLE
Decay model

### ISSUE THREAD

**Issue by Yaels17** [MISP/MISP#6320]
I've been trying to understand the decaying process in MISP for quite some time without much success.
my need from this platform is to DELETE all the indicators that have expired (for example in my organisation IPs should have an expiration date of 3 months).  
I have yet to uncover whether the decaying models actually delete the attributes or if there is a simpler way to just set an expiration date in which the attribute will be actually deleted from the system.

appreciate the help

**Comment by mokaddem** [comment]
The decaying in MISP never touches at the data itself. It just provides an overlay with the result of the decaying computed by the available (or requested models).
Of course, you can filter out decayed IoCs when querying `attributes/restSearch`.
I encourage you to check out these [slides](https://www.misp-project.org/misp-training/a.5-bis-decaying-indicators-light-version.pdf) presenting the feature in more details.

**Comment by adulau** [comment]
If the issue is not resolved, you can reopen the ticket. Thank you very much.
