### ISSUE TITLE
UI: add a button to kill all workers at once 

### ISSUE THREAD

**Issue by C00kie-** [MISP/MISP#6329]
Hello, this is a request for when you need to kill all workers in order to restart them.
For the page /servers/serverSettings/workers

thanks!

**Comment by iglocska** [comment]
ok that's kind of stupid that we didn't have that, thanks!

Also added a force kill all workers button in case you want to stop an unwanted ongoing process.

**Comment by C00kie-** [comment]
thanks a lot! 
have a good day
