### ISSUE TITLE
Outdated administration doc on circl.lu last updated March 2020; e.g., uses "blacklist" not "blocklist"

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6332]
The admin documentation shown at https://www.circl.lu/doc/misp/administration/ seems to be out of date.  At the top the page shows "Last modified: Tue Mar 10 2020 14:01:03 GMT+0100 (CET)".  For example, the "blocklist" feature is still labeled "blacklist" in that doc. But I see that file github/MISP/app/View/Pages/doc/administration.ctp seems to be up to date, so I think the work has been done, maybe you just need to regenerate the doc for this web site?  Thanks for listening

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | all
| OS version (client)       | all
| PHP version               | all
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior

Circl.lu has updated doc

### Actual behavior

Circl.lu has outdated doc

### Steps to reproduce the behavior

Visit https://www.circl.lu/doc/misp/administration/

visit ### Logs, screenshots, configuration dump, ...

**Comment by chrisinmtown** [comment]
hey Circl peeps, I think fixing this must be a trivial regenerate-doc command for you. Would you please do that then we can close this issue?

**Comment by iglocska** [comment]
The documentation is indeed woefully outdated, sadly the built in administration page is not converted automatically for inclusion in MISP book so it's a manual process.

**Comment by pramos** [comment]
@iglocska this should be changed in https://github.com/MISP/misp-book or in the documentation within this repo?

**Comment by chrisinmtown** [comment]
https://www.circl.lu/doc/misp/administration/ was regenerated March 2021 so the original problem that caught my eye is gone.
