### ISSUE TITLE
Get altered events based on timestamps

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#634]
Is it possible to implement a feature in the REST API to fetch all altered events between two timestamps?

**Comment by iglocska** [comment]
Yeah, that would make sense. I am planning on reworking the APIs after the next release and that is definitely something that should be there. We can now set the lower bound of the results (using 'last'), but not the upper bound. I'll definitely keep this in mind!

**Comment by thomai** [comment]
Thank you very much for the quick response :+1:

**Comment by iglocska** [comment]
Doable via the rest API, simply use "timestamp": [ts1, ts2]

**Comment by SteveClement** [comment]
@thomai is this still something you are interested in?

We have some means to achieve what you want to do via PyMISP
