### ISSUE TITLE
MISP incorrectly states base URL is incorrect

### ISSUE THREAD

**Issue by todonaki** [MISP/MISP#6342]
MISP appears to be functioning normally, but gives critical error.

Error received: **Critical**
MISP.baseurl: https://misp.XXXXXXXX.global
**The  base url of the application (in the format  https://www.mymispinstance.com or https://myserver.com/misp). Several  features depend on this setting being correctly set to function. | Invalid baseurl, it has to be in the "https://FQDN" format.**

Type of issue: Bug
OS: Ubuntu 18.04 LTS
PHP version: 7.4
MISP version / git hash   | 2.4.132

**### Expected behavior**
No error from properly formatted base URL

**### Actual behavior**
Properly formatted base URL shows as critical error

**### Logs, screenshots, configuration dump, ...**
<img width="1465" alt="misp_error_25_09_2020" src="https://user-images.githubusercontent.com/57256761/94321013-70a29a00-ff5c-11ea-912f-53de1ec6f4df.png">

MISP appears to be working correctly despite this error.

**Comment by chrisinmtown** [comment]
Can you show the full hostname in that URL? File app/Model/server.php, line 3624 checks the URL using this regex:

    $regex = "%^(?<proto>https?)://(?<host>(?:(?:\w|-)+\.)+[a-z]{2,5})(?::(?<port>[0-9]+))?(?<base>/[a-z0-9_\-\.]+)?$%i";

I'm not entirely familiar with all the features used this regex, so it will help to know the input string exactly.

There's also the chance that the host portion of that URL doesn't match the result of the getHost() function, see line 3580 of that same file.

**Comment by todonaki** [comment]
I think you may be on to something here.  Line 3624 regex allows for **2-5** characters for TLD, but the **.GLOBAL extension is 6 characters** in length.  The regex doesnt allow for many of the new TLD's.  I'm going to try editing the regex in the file to allow for 6 characters and see if the problem is resolved.

**Comment by todonaki** [comment]
That was it.  Regex does not allow for enough characters for all TLD types.  I would consider this a bug.  I did not experience this behavior until the latest (132) release. @chrisinmtown, appreciate the assistance and helping point me to the right location where I could make the change.

**Comment by chrisinmtown** [comment]
Great.  Sounds like a bug to me too. Instead of changing 5 to 6, I suggest removing the 5 entirely so the pattern requires 2 or more letters with no upper limit. I'm not certain what is the proper upper limit, there are a *lot* of gTLD names these days and many are long like 'accountants' and 'basktball', see https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

Here's my proposed one-line change for the MISP project to consider:
```
diff --git a/app/Model/Server.php b/app/Model/Server.php
index 539b72468..28b198147 100644
--- a/app/Model/Server.php
+++ b/app/Model/Server.php
@@ -3621,7 +3621,7 @@ class Server extends AppModel
         if ($this->testForEmpty($value) !== true) {
             return $this->testForEmpty($value);
         }
-        $regex = "%^(?<proto>https?)://(?<host>(?:(?:\w|-)+\.)+[a-z]{2,5})(?::(?<port>[0-9]+))?(?<base>/[a-z0-9_\-\.]+)?$%i";
+        $regex = "%^(?<proto>https?)://(?<host>(?:(?:\w|-)+\.)+[a-z]{2,})(?::(?<port>[0-9]+))?(?<base>/[a-z0-9_\-\.]+)?$%i";
        if ( !preg_match($regex, $value, $matches)
                 || strtolower($matches['proto']) != strtolower($this->getProto())
                 || strtolower($matches['host']) != strtolower($this->getHost()) ) {
```

**Comment by todonaki** [comment]
@chrisinmtown, agree with your assessment of removing the '5' in the regex to allow for longer TLD's.  That would be a good fix, but would leave room for mischief if the upper limit were abused.

I dont know either what a proper upper limit would be.  Maybe find the longest gTLD and arbitrarily set that as the upper limit?
For example, the gTLD accountants = 11 characters.  If there are no gTLD's longer than that, set the upper limit to 11.

Just my random thoughts.  Again, appreciate your help and the feedback above!  **THANK YOU**

**Comment by RichieB2B** [comment]
Makes sense to me. PR coming up.
