### ISSUE TITLE
after installation of MISP can not login to the system

### ISSUE THREAD

**Issue by olegzhr** [MISP/MISP#6354]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | Chrome

### Expected behavior

after installation MISP, the system should ask to change the password

### Actual behavior

system crash: 
PHP Parse error:  syntax error, unexpected ']', expecting ',' or ')' in /var/www/MISP/app/Model/Attribute.php on line 1199, 

### Steps to reproduce the behavior

install a new system

### Logs, screenshots, configuration dump

please, check module - Attribute.php
seems there is a syntax error at 1199 line:

if (preg_match("#^.+\|[a-zA-Z0-9&!="]+$#", $value)) {

**Comment by mokaddem** [comment]
Thanks a lot for the report!
