### ISSUE TITLE
JA3 hashes in rules export

### ISSUE THREAD

**Issue by rbnor** [MISP/MISP#6355]
**Is your feature request related to a problem? Please describe.**
JA3 is a very effective means to detection of malicious traffic, or for tracking threat actors activity, much more than IPs and domains alone. 

I would love to have JA3 md5 fingerprints added to the rules export of suricata/bro. 

**Describe the solution you'd like**
For bro intel JA3 fingerpritns would be added with  the indicator_type set to Intel::JA3

For suricata it would mean rules on the follwoing format: 

alert tls any any -> any any (msg:"match JA3 hash"; \
    ja3_hash; content:"e7eca2baf4458d095b7f45da28c16c34"; \
    sid:100001;)

as per https://suricata.readthedocs.io/en/suricata-4.1.0/rules/ja3-keywords.html

**Describe alternatives you've considered**
extracting the JA3 hashes manually and add the rules manually, however this breaks the current pipeline and way of working, and is not a good solution.

**Comment by adulau** [comment]
Thank you very much, it's indeed a good point.

In order to support this feature, the following might need to be updated:

- Update the Suricata export to include the `ja3-fingerprint-md5` attribute
- Update the Bro export to include the `ja3-fingerprint-md5`in indicator_type

**Comment by legoguy1000** [comment]
I'm looking to do the same for my org.  I don't know much about zeek rules but I can work on the suricata rule code.  I just checked and i don't think that Snort can use JA3 hashes.  I also think adding a `ja3s-fingerprint-md5` type would be good too but 1 thing at a time.
