### ISSUE TITLE
Auto Push/Pull not working

### ISSUE THREAD

**Issue by KodySEC** [MISP/MISP#636]
I currently having MISP running between two instances, and things are working great, except for auto push/pull as soon as a new Event is published. I will say that it worked for an hour or so yesterday.

**Comment by elhoim** [comment]
Does the scheduler worker works?

Is everything OK on the diagnostics page?

**Comment by KodySEC** [comment]
I apologize for taking so long to respond to this. I was able to get everything working. Thanks for the help.

**Comment by iglocska** [comment]
Thanks for the heads-up! :)
