### ISSUE TITLE
Deduce the id of the feed if an indicator comes via the API

### ISSUE THREAD

**Issue by Dmitry-Vasin** [MISP/MISP#6363]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |Ubuntu
| OS version (client)       | Ubuntu
| MISP version / git hash   | Most recent

### Support Questions
My question is in regards to the API. What we are looking to do is disable feeds if a certain volume of indicators gets added within a specified period of time. There is an API to disable feeds, however that requires a feed_id parameter. I cannot find any way to obtain this feed_id given an event id, name, or indicator. Is there a way to do this?

**Comment by mokaddem** [comment]
Have you tried checking the logs or job status?
Also, if the feed has its own organisation, you can check the delta before/after the feed ingestion and deduce the # of added attributes

**Comment by Dmitry-Vasin** [comment]
@mokaddem Thanks, but what I am actually looking for is just a way to get feed_id from an event id or feed name automatically. I already have a way to check the amount of ingested attributes but I can't automatically disable a feed based on that information from what I can see.

**Comment by mokaddem** [comment]
What you can also do is tag the feed with a custom tag using the `default tag` option in the feed configuration and based on this information deduce the feed ID.
Would that help?

**Comment by github-germ** [comment]
You might get all feeds with `PyMISP.feeds`, and then use the `Events.info` (which has `' feed'` appended) to match `Feeds.name` to get `Feeds.id`. This method can get you multiple matches depending on whether your feeds use `fixed_event` and if you have duplicated `Feeds.name`. All depends on how your feeds are setup, but might get you close...

**Comment by enjeck** [comment]
> What you can also do is tag the feed with a custom tag using the default tag option in the feed configuration and based on this information deduce the feed ID.
> Would that help?

> You might get all feeds with PyMISP.feeds, and then use the Events.info (which has ' feed' appended) to match Feeds.name to get Feeds.id. This method can get you multiple matches depending on whether your feeds use fixed_event and if you have duplicated Feeds.name. All depends on how your feeds are setup, but might get you close...

@Dmitry-Vasin Did any these suggestions help?
