### ISSUE TITLE
2.4.231 and 2.4.232 uses enormous amount of memory for /tags/index endpoint

### ISSUE THREAD

**Issue by mike1703** [MISP/MISP#6366]
Using the PyMISP tags() method it showed that we get an HTTP 500 error due to memory exhaustion.

```
Error: Fatal Error (1): Allowed memory size of 17179869184 bytes exhausted (tried to allocate 4096 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 502]
```

Previously we had max. 8GB for the PHP process but after the update we could not retrieve the tags anymore. Trying with more RAM (~160GB) showed that this is also not going to work on our instances.

Note that we have more unique tags than others in their environment (around ~22k unique tags)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4
| MISP version / git hash   | 2.4.132 (but also 2.4.131)
| Browser                   | curl ;) or pymisp
### Expected behavior

receive all tags from the instance

### Actual behavior

memory usage goes over the top and even ~160GB RAM usage was not enough.

### Steps to reproduce the behavior
Have ~22000 tags in your MISP instance and execute the following:

```bash
$ curl -H "Accept: application/json" -H "content-type: application/json" "https://<misp-instance>/tags/index"
```

### Logs, screenshots, configuration dump, ...
We tried to figure out where the problem might be and found the following diff
[v2.4.130...v2.4.131](https://github.com/MISP/MISP/compare/v2.4.130...v2.4.131#diff-7b9cfe00be12ccde2686e7f2db585818L75)

```patch
--- TagsController.php	2020-09-30 14:22:06.445586459 +0000
+++ /var/www/MISP/app/Controller/TagsController.php	2020-09-30 13:56:16.408222006 +0000
@@ -74,6 +74,8 @@
         }
         if ($this->_isRest()) {
             unset($this->paginate['limit']);
+            unset($this->paginate['contain']['EventTag']);
+	     unset($this->paginate['contain']['AttributeTag']);
             $paginated = $this->Tag->find('all', $this->paginate);
         } else {
             $paginated = $this->paginate();
```

With that patch in place the endpoint is working again so I presume that this is the source of the memleak but I'm not entirely sure what the impact of this hotfix is.
Version 2.4.130 works as intended though.

**Comment by iglocska** [comment]
I’ve reverted the patch that introduced this, so should be safe to update again

**Comment by adulau** [comment]
Feel free to reopen if the revert patch didn't solve the issue.
