### ISSUE TITLE
Filter events action should show Processing/wait indicator on UI

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6367]
On the events page, type a string into the box ("Enter value to search"), click Filter button, then wait. Sometimes a long time.  Finally the screen changes to show filtered results.

**Is your feature request related to a problem? Please describe.**

The problem is that the user has no visual confirmation that a search is running.

**Describe the solution you'd like**

After clicking filter, the screen should change, possibly show a progress indicator, while the result from the back end is constructed.

**Describe alternatives you've considered**

I can watch the browser dot bipping back and forth, which isn't a satisfactory solution.  

**Additional context**

MISP version 2.4.131

**Comment by mokaddem** [comment]
Fixed with e6f05d40a604731ab5c2429af3b6fc069bfc47a2. Let us know if it's not satisfactory!
