### ISSUE TITLE
tag method's UnboundLocalError 

### ISSUE THREAD

**Issue by SoheiMitsukawa** [MISP/MISP#6369]
Hello.

I found UnboundLocalError in the PyMISP's tag method.
It happens when I pass a dictionary without uuid to misp_entity.
I use the latest versions of both the server and PyMISP.

Here is a simple example.

----------------------------------------

from pymisp import ExpandedPyMISP, MISPTag

MISP_URL = 'https://hoge'
MISP_AUTHKEY = 'fuga'

if __name__ == '__main__':
	print('Start')

	# MISP connect
	misp = ExpandedPyMISP(MISP_URL, MISP_AUTHKEY, ssl=False, debug=False)

	# Add tag
	test_tag = MISPTag()
	test_tag.from_dict(name='test')
	print(misp.tag({}, test_tag))

	print('Finish')

exit()

----------------------------------------

result:
Start
Traceback (most recent call last):
  File "git.py", line 27, in <module>
    print(misp.tag({}, test_tag))
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 2320, in tag
    to_post = {'uuid': uuid, 'tag': tag, 'local': local}
UnboundLocalError: local variable 'uuid' referenced before assignment

----------------------------------------

I read the source code of PyMISP.
And I added some code.
If possible, I would like you to reflect the following contents.

----------------------------------------

    def tag(self, misp_entity: Union[AbstractMISP, str, dict], tag: Union[MISPTag, str], local: bool = False) -> Dict:
        """Tag an event or an attribute. misp_entity can be a MISPEvent, a MISP Attribute, or a UUID"""
        if isinstance(misp_entity, AbstractMISP) and 'uuid' in misp_entity:
            uuid = misp_entity.uuid
        elif isinstance(misp_entity, dict) and 'uuid' in misp_entity:
            uuid = misp_entity['uuid']
        elif isinstance(misp_entity, str):
            uuid = misp_entity
        # following added by me.
        else:
            raise Exception(f'Not found UUID: {misp_entity}')

        if isinstance(tag, MISPTag):
            tag = tag.name
        to_post = {'uuid': uuid, 'tag': tag, 'local': local}
        response = self._prepare_request('POST', 'tags/attachTagToObject', data=to_post)
        return self._check_json_response(response)

----------------------------------------

Best regards,

**Comment by chrisinmtown** [comment]
The first argument for the tag() method must be a MISP entity.  You've passed in an empty dictionary.  This is a case of garbage in, garbage-out.  Still, I like your change and suggest you submit it as a PR to make this method more robust.  In your PR you probably should extend the untag() method similarly since it uses the same algorithm.

**Comment by SoheiMitsukawa** [comment]
Thank you for your comment.
As you suggested, I certainly felt that PR was more appropriate than issue.
Also, thank you for the information on untag method.
For the time being, this issue is closed.
Thanks,
