### ISSUE TITLE
Allow to add atributes without requiring a timestamp

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#637]
Would fix that issue, and avoid dirty workarounds in the API: https://github.com/CIRCL/PyMISP/issues/18

It would create problems with the sync with other platforms so the better solution is probably to make the timestamp a float and have microseconds (time.time() in python), this way, every new attribute sent will have a newer timestamp. 

What do you think?

**Comment by iglocska** [comment]
I'll look into it, it won't necessarily be an issue with the sync at all,
the sync requires the timestamp to be set - if none is set it can just
generate one for the current time. I'll make the changes!

**Comment by Rafiot** [comment]
Probably fixed by: e7b54c2c6131a7ab7806bb12c0293057007d0d39

**Comment by Rafiot** [comment]
Yep, fixed.
