### ISSUE TITLE
Need help troubleshooting 403 Client Error: Forbidden when using the REST-API: [misp-instance]/events/restSearch

### ISSUE THREAD

**Issue by mik5z** [MISP/MISP#6390]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.132, 9ca82a568efe5cea38801d9927be94e6ec75e286
| Client                   | MISP42Splunk

### Support Questions

I'm having issues connecting my MISP instance to our Splunk environment, where it's showing the following error:
External search command 'mispgetevent' returned error code 1. Script output = "error_message=HTTPError at "/opt/splunk/etc/apps/misp42splunk/bin/lib/aob_py2/requests/models.py", line 940 : 403 Client Error: Forbidden for url: https://misppriv.asml.com/events/restSearch ".

I believe it's an issue on the MISP server's end, that's why I'm trying my luck here. 

I have configured the correct API key, but somehow the server is not allowing the connection.

When trying to connect to https://[misp-instance]/events/restSearch, I'm also getting "An Internal Error Has Occurred.", where I'm sure that this used to return a json file with {"response": []} in it.

I'm running a second MISP server using version 2.4.129 with a nearly identical configuration, and it still works on that system.

Do you have any suggestions on where to look for a potential issue?

### Logs
I've found the following error in /var/log/apache2/misp.local_error.log:

`[Tue Oct 06 14:32:18.731523 2020] [php7:error] [pid 1647] [client 10.240.5.26:57917] PHP Fatal error:  Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261\nStack trace:\n#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[RedisException...', '/var/www/MISP/a...', 138)\n#1 [internal function]: ErrorHandler::handleError(256, '[RedisException...', '/var/www/MISP/a...', 138, Array)\n#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[RedisException...', 256)\n#3 [internal function]: ErrorHandler::handleException(Object(MissingConnectionException))\n#4 {main}\n  thrown in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 261, referer: https://[misp-instance]/events/restSearch`

`[Tue Oct 06 14:32:19.250038 2020] [php7:error] [pid 1647] [client 10.240.5.26:57917] PHP Fatal error:  Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261\nStack trace:\n#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[RedisException...', '/var/www/MISP/a...', 138)\n#1 [internal function]: ErrorHandler::handleError(256, '[RedisException...', '/var/www/MISP/a...', 138, Array)\n#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[RedisException...', 256)\n#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::handleException(Object(InternalErrorException))\n#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261)\n#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/var/www/MISP/a...', 261, Array)\n#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFat in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 261, referer: https://[misp-instance]/events/restSearch`

**Comment by mokaddem** [comment]
In the error trace, I can see a redis exception. Could you make sure that 
- MISP has the correct credential to access the redis server
- And that redis is working correctly?

You may also find more information in the MISP logs located here: `app/tmp/logs/*`

**Comment by mik5z** [comment]
> In the error trace, I can see a redis exception. Could you make sure that
> 
> * MISP has the correct credential to access the redis server
> * And that redis is working correctly?
> 
> You may also find more information in the MISP logs located here: `app/tmp/logs/*`

How would I check if redis is working correctly, and that the server has access to the redis server (which is hosted locally)? I haven't had any issues before.

**Comment by mokaddem** [comment]
- You can ping the redis server using the redis-cli tool
- You can verify the credential in your MISP server settings
Although if you can connect to MISP via your web interface it should be fine.

**Comment by mik5z** [comment]
> * You can ping the redis server using the redis-cli tool
> * You can verify the credential in your MISP server settings
>   Although if you can connect to MISP via your web interface it should be fine.

The redis-cli command seems to be working: 
misp@misp:# redis-cli
127.0.0.1:6379>

Everything else in my MISP instance works, it's only the REST API part that's causing these errors.

**Comment by mokaddem** [comment]
Alright.
Anything interesting here: `app/tmp/logs`?

**Comment by mik5z** [comment]
[debug.log](https://github.com/MISP/MISP/files/5334084/debug.log)
[error.log](https://github.com/MISP/MISP/files/5334085/error.log)
 So it tells me to "Please make sure you pass the API key of an API enabled user along in the Authorization header"
The strange thing is, that I made sure of that.

**Comment by mik5z** [comment]
> Alright.
> Anything interesting here: `app/tmp/logs`?

Actually, I was able to solve the problem by re-taking the configuration steps from the install file. It seems to work now.

Thanks for your time!
