### ISSUE TITLE
Help Diagnosing Dashboard Errors

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#6392]
2.4.131

We are seeing the following messages seemingly related to the Dashboard. Can anyone shed some light on how we can try to isolate what is triggering these? Thanks in advance!!

* `error.log`
```
2020-09-25 20:15:04 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Lib/Dashboard/TrendingTagsWidget.php, line 61]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
TrendingTagsWidget::checkTag() - APP/Lib/Dashboard/TrendingTagsWidget.php, line 61
TrendingTagsWidget::handler() - APP/Lib/Dashboard/TrendingTagsWidget.php, line 42
DashboardsController::renderWidget() - APP/Controller/DashboardsController.php, line 170
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

* `debug.log`
```
2020-09-25 20:20:32 Notice: Notice (8): Trying to access array offset on value of type bool in [/var/www/MISP/app/Lib/Dashboard/MispAdminResourceWidget.php, line 26]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
MispAdminResourceWidget::handler() - APP/Lib/Dashboard/MispAdminResourceWidget.php, line 26
DashboardsController::renderWidget() - APP/Controller/DashboardsController.php, line 170
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by mokaddem** [comment]
> - `error.log`

It seems that the configuration you passed to this widget is incorrect. Could you paste it here just to be sure?

> - `debug.log`

Could you connect make sure that
- The user connecting to the redis instance has the permission to execute the `memory stats` command
- Could you check to output of the `memory stats` command
Out of curiosity, what is the version of redis

**Comment by chrisinmtown** [comment]
Thanks for the nudge to look at the widget config.  The problem with the Trending Tags widget was just bad config data on our side.

As for the Misp Admin Resource widget, here's some redis-cli output with version and memory:
```
127.0.0.1:6379> INFO
# Server
redis_version:3.2.4
...
# Memory
used_memory:392073384
used_memory_human:373.91M
used_memory_rss:617156608
used_memory_rss_human:588.57M
used_memory_peak:2004548464
used_memory_peak_human:1.87G
total_system_memory:405241176064
total_system_memory_human:377.41G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.57
mem_allocator:jemalloc-4.0.3
```
I see that file MispAdminResourceWidget.php, line 26 tries to run command "memory stats".  From what I can find online, this command was first made available in Redis 4.0. 

Is Redis version 4.0 or later required? We are running version 3.2.4. If MISP requires version 4 or later, is it warning us somewhere to say that? I checked the server diagnostics and don't see any warnings about Redis version.

**Comment by chrisinmtown** [comment]
Thanks for the change to the memory stats query, I guess this means Redis version 3 will again be sufficient even if its memory usage & performance is not as optimized & fast as the latest version 6.

**Comment by github-germ** [comment]
Thx folks. We now understand root cause.
