### ISSUE TITLE
Integrating MISP with Microsoft Graph Security API

### ISSUE THREAD

**Issue by bunnHHA** [MISP/MISP#6399]
Hi team, I used script to integrate  MISP to Microsoft Graph security API, however, indicators from MISP can be sent successfully, but no response from Microsoft Graph Security API. Below is  the output of running the script. Is there any way to do  this right?. Thanks for your efforts.
![image](https://user-images.githubusercontent.com/61225598/95301298-69598580-08a6-11eb-88ce-9f22e4b72f2f.png)

**Comment by adulau** [comment]
Not sure how we can help there. You mention a script, is a it script bundled by MISP project? and mention the use of a third party API which are not managed by MISP Project. If you have more details, you can reopen the issue and share more information there. Thank you.

**Comment by bunnHHA** [comment]
@adulau thanks for your reply. but it is not third party script that I used to integrate with Microsoft graph security API. Below is the script I used "https://github.com/microsoftgraph/security-api-solutions/tree/master/Samples/MISP/script.py" and it is  script from "MISP to Microsoft Graph Security Script" document. Thanks for your reply though.

**Comment by adulau** [comment]
Yes but the script is done by Microsoftgraph. Could you open an issue over there? we don't have any mean or access to Microsoft Graph security API for testing. I would advise from your side to debug the script to add some print statement when the information is pushed in Microsoft Graph security API.
