### ISSUE TITLE
Integrating MISP with Microsoft Graph Security API

### ISSUE THREAD

**Issue by bunnHHA** [MISP/MISP#6401]
Hi team, I used script to integrate  MISP to Microsoft Graph security API, however, indicators from MISP can be sent successfully, but no response from Microsoft Graph Security API. Below is  the output of running the script. Is there any way to do  this right?. Thanks for your efforts.
![image](https://user-images.githubusercontent.com/61225598/95301298-69598580-08a6-11eb-88ce-9f22e4b72f2f.png)

Here is the script that I used from official repository of "MISP to Microsoft Graph Security Script". 
"https://github.com/microsoftgraph/security-api-solutions/tree/master/Samples/MISP/".
What I trying to achieve is to push threat indicators from MISP to azure sentinel. But got this error as shown in above figure. Any ideas or comments will be much appreciated. Thanks.

**Comment by adulau** [comment]
Duplicate of #6399

**Comment by bunnHHA** [comment]
@adulau can u please help me sir?
