### ISSUE TITLE
Help Diagnosing DB schema errors

### ISSUE THREAD

**Issue by seldem** [MISP/MISP#6403]
I have just updated MISP version from 2.4.131 to 2.4.132 and got the following schema errors. I have no idea whether it is benign or not. Please advice.

![misp1](https://user-images.githubusercontent.com/36921239/95348977-3f648b00-08c7-11eb-9c95-633278d6ad7c.png)
![misp2](https://user-images.githubusercontent.com/36921239/95349009-48555c80-08c7-11eb-9bc0-e0e2157686af.png)

**Comment by mokaddem** [comment]
The diagnostic tool shows that you are on version 56 and the system expect version 58. Could you make sure that all updates are installed?
Thanks

**Comment by seldem** [comment]
Thanks for the reply. I did rerun updates and problem solved.
