### ISSUE TITLE
STIX version always 0 

### ISSUE THREAD

**Issue by vertering** [MISP/MISP#6404]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS7
| MISP version / git hash   | v2.4.132 (34a1671e8af5916f578db3565c86151fceb51745)

### Support Questions
Hi,

I'm trying to get STIX to work on our MISP instance, but the diagnostics page always reports that "Incorrect STIX version installed, found 0, expecting >1.2.0.9". Because of this, I tried updating STIX, yet it turns out that there is already a STIX 1.2.0.10 installation, which gets reinstalled and reinstalled.  After this, the diagnostics page still reports that the STIX version is null.
Can anyone point me in the right direction?
Thanks in advance! 

### Logs, screenshots, configuration dump, ...
![Screen1](https://user-images.githubusercontent.com/6614007/95350777-d4b05100-08c0-11eb-8452-5f14eef218b8.PNG)
![Screen2](https://user-images.githubusercontent.com/6614007/95350791-d7ab4180-08c0-11eb-9bb9-685f0c4db263.PNG)

**Comment by Kagee** [comment]
While most used to MISP og Ubuntu, I would do the following:
* Make sure that MISP is set to use the venv (MISP.python_bin in settings)
* Set file permission to make sure these are correct https://misp.github.io/MISP/INSTALL.rhel7/#5-set-file-permissions
* Make sure to properly activate the venv before installing (i.e. sudo -H -u apache bash -c 'source ......./venv/bin/activate; pip install -U'
* Set file permission again https://misp.github.io/MISP/INSTALL.rhel7/#5-set-file-permissions

**Comment by vertering** [comment]
Thanks for the reply, but I've switched to Ubuntu!
