### ISSUE TITLE
Specific events(or multievent) STIX v1 export fails validation by stix-validator.py (and other tools)

### ISSUE THREAD

**Issue by pettai** [MISP/MISP#6406]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04 latest
| OS version (client)       | curl
| PHP version               | 7.2
| MISP version / git hash   | 2.4.132 / abb981dbe5b236c55116e15eb47d4b269d77f3a0

### Expected behavior

Single event export mostly works fine:
```
ubuntu@misp:~$ stix-validator.py Emotet.xml
[-] Performing xml schema validation on Emotet.xml
================================================================================
[-] Results: Emotet.xml
[+] XML Schema: True
```
### Actual behavior

Then exporting multiple events or certain (what looks like) larger events, there are always some that breaks stix-validation, and thus makes the STIX export unusable in the tools they where suppose to be imported into.
```
ubuntu@misp:~$ stix-validator.py troublesome-event.xml
[-] Performing xml schema validation on troublesome-event.xml
================================================================================
[-] Results: troublesome-event.xml
[!] XML Schema: False
    [!] STIX-MISP.xml:102:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://cybox.mitre.org/cybox-2}Properties', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'CustomObj:CustomObjectType' has no corresponding namespace declaration in scope.
    [!] STIX-MISP.xml:102:0:ERROR:SCHEMASV:SCHEMAV_CVC_TYPE_2: Element '{http://cybox.mitre.org/cybox-2}Properties': The type definition is abstract.
    [!] STIX-MISP.xml:125:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://cybox.mitre.org/cybox-2}Properties', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'CustomObj:CustomObjectType' has no corresponding namespace declaration in scope.
    [!] STIX-MISP.xml:125:0:ERROR:SCHEMASV:SCHEMAV_CVC_TYPE_2: Element '{http://cybox.mitre.org/cybox-2}Properties': The type definition is abstract.
    [!] STIX-MISP.xml:148:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://cybox.mitre.org/cybox-2}Properties', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'CustomObj:CustomObjectType' has no corresponding namespace declaration in scope.
    [!] STIX-MISP.xml:148:0:ERROR:SCHEMASV:SCHEMAV_CVC_TYPE_2: Element '{http://cybox.mitre.org/cybox-2}Properties': The type definition is abstract.
```

### Steps to reproduce the behavior

```
ubuntu@misp:~$ curl -d '{"returnFormat":"stix","last":"1d","enforceWarninglist":"true","to_ids":"true"}'  -H "Authorization: YOUR_API_KEY_GOES_HERE"  -H "Accept: application/xml"  -H "Content-type: application/json"  -X POST http://misp.local:/events/restSearch > multi-event.xml
ubuntu@misp:~$ stix-validator.py multi-event.xml
[...]
```

I know of at least some events coming from MISPPriv that breaks the STIX validation (Hint: Rouge DNS)
No sure if I can post them here, but I have some of them exported which I can point at for debugging help.

### Logs, screenshots, configuration dump, ...

relevant Python packages:
ubuntu@misp:~$ pip list | egrep -i "stix|cybox|taxi|pymisp|maec|mix"
cybox                  2.1.0.21
libtaxii               1.1.117
maec                   4.1.0.16
misp-stix-converter    0.2.11
mixbox                 1.0.3
pymisp                 2.4.131
stix                   1.2.0.10
stix-validator         2.5.0
stix2                  2.0.2
stix2-patterns         1.3.1

Probably not relevant for this issue, just a headsup
```
ubuntu@misp:~$ cat app/tmp/logs/exec-errors.log
/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
```

Question is where it goes wrong... is it the MISP event(s) themselves (a few of them have thousand(s) of attributes), or is it the conversion to STIX that structure them data wrong...

**Comment by chrisr3d** [comment]
Since it was probably an issue with the STIX header, I updated the framing to include the CustomObject namespace.
It should be working now, let me know if anything goes wrong

**Comment by pettai** [comment]
I've updated and tested a scope that should cover the old events, and the error seems gone.
Thx, closing this one.
