### ISSUE TITLE
i can't set up virtual machine to work propertly

### ISSUE THREAD

**Issue by jolubedju** [MISP/MISP#6408]
After i download the "MISP_v2.4.132@20fd5c9" ova, i try to run it in several ways and i have always the same problem:

After login, it send me to the change password page, but is blank. I've read that could be a TLS missconfiguration, but why isn't this propertly working in a pre-configured vm?

Could you help?

Thanks.

**Comment by mokaddem** [comment]
Could you try to pull the latest version via the command line and try again? It could be that the code on the VM present a bug.
Thanks

**Comment by JakubOnderka** [comment]
Yes, probably the same bug as https://github.com/MISP/MISP/issues/6426
