### ISSUE TITLE
Attribute "port number"

### ISSUE THREAD

**Issue by ost89** [MISP/MISP#642]
I think it would be interesting to add "port number" as extra attribute

**Comment by elhoim** [comment]
Port attribute alone would not be useful, but when we have the possibility of storing attributes with boolean operators (#27), then it would useful to combine it for example with an IP or a hostname.

**Comment by adulau** [comment]
The tuple IP:port would be useful for release2.4

**Comment by elhoim** [comment]
+1 for the addition of a new ip:port composite attribute type

**Comment by adulau** [comment]
Fixed in v2.4.57 https://github.com/MISP/MISP/tree/v2.4.57
