### ISSUE TITLE
Adding SMIME user-cert fails due to purpose check

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6424]
I recently tried to activate SMIME and noticed that the users certificate part is rejected by MISP as
`This certificate cannot be used to encrypt email.`

However the cert is actually fine.
Already hunted it down to the purpose validation of the certificate in this line:
https://github.com/MISP/MISP/blob/2a9feb7cd399c0fae7dfa92aca2bd5ab75e2db94/app/Lib/Tools/SendEmail.php#L485

For some reason the parsed purpose fields seem to not be identical (===) to the expectation. Using double-equals instead of triple-ones allowed me to add the certificate and receiving smime-ecrypted mails.

Since it might be relevant, unfortunately i'm currently still on php 7.2.

**Comment by JakubOnderka** [comment]
Sorry, my mistake. Can you please check also proposed solution from https://github.com/MISP/MISP/pull/6425 if it also works as expected?

**Comment by marjatech** [comment]
> 
> 
> Sorry, my mistake. Can you please check also proposed solution from #6425 if it also works as expected?

Wow, that was fast.
Just checked it, also works as expected 👍
