### ISSUE TITLE
HTTP ERROR 500 after login on MISP_v2.4.132@20fd5c9-VMware

### ISSUE THREAD

**Issue by taratine** [MISP/MISP#6426]
solved:

/var/www/MISP/app/Model/Attribute.php on line 1199 replace

if (preg_match("#^.+\|[a-zA-Z0-9&!="]+$#", $value)) 
with
if (preg_match("#^.+\|[a-zA-Z0-9&!=]+$#", $value))

========================================================
## Work environment
MISP_v2.4.132@20fd5c9-VMware
| Browser                   | Chrome | Firefox

### Logs, screenshots, configuration dump, ...
Chrome: HTTP ERROR 500 after login 
Firefox: a white screen with no errors

misp.local_error.log
[Mon Oct 12 22:53:32.080712 2020] [php7:emerg] [pid 742] [client 192.168.214.1:50734] PHP Parse error:  syntax error, unexpected ']', expecting ',' or ')' in /var/www/MISP/app/Model/Attribute.php on line 1199, referer: https://192.168.214.129/users/login
[Mon Oct 12 22:53:32.080729 2020] [php7:error] [pid 742] [client 192.168.214.1:50734] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0, referer: https://192.168.214.129/users/login

misp.local_access.log
192.168.214.1 - - [12/Oct/2020:22:23:45 +0200] "GET / HTTP/1.1" 302 3478 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /users/login HTTP/1.1" 200 3107 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /css/bootstrap.css HTTP/1.1" 200 18933 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /css/bootstrap-datepicker.css HTTP/1.1" 200 2665 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /css/bootstrap-colorpicker.css HTTP/1.1" 200 1455 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /css/famfamfam-flags.css HTTP/1.1" 200 2458 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:46 +0200] "GET /css/font-awesome.css HTTP/1.1" 200 13163 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /css/jquery-ui.css HTTP/1.1" 200 8936 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /css/chosen.min.css HTTP/1.1" 200 2811 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /css/main.css HTTP/1.1" 200 9821 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /css/jquery-jvectormap-2.0.5.css HTTP/1.1" 200 4050 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/jquery.js HTTP/1.1" 200 85995 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/misp-touch.js HTTP/1.1" 200 962 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/jquery-ui.js HTTP/1.1" 200 125818 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/chosen.jquery.min.js HTTP/1.1" 200 7257 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/bootstrap.js HTTP/1.1" 200 11891 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/bootstrap-timepicker.js HTTP/1.1" 200 6656 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/bootstrap-datepicker.js HTTP/1.1" 200 15500 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/bootstrap-colorpicker.js HTTP/1.1" 200 7510 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:47 +0200] "GET /js/misp.js HTTP/1.1" 200 36326 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /js/keyboard-shortcuts.js HTTP/1.1" 200 2008 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /img/misp-logo.png HTTP/1.1" 200 10834 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /css/print.css HTTP/1.1" 200 720 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /shortcuts/global_menu.json HTTP/1.1" 200 721 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /favicon.ico HTTP/1.1" 200 1686 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:23:48 +0200] "GET /favicon.ico HTTP/1.1" 200 1686 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:24:15 +0200] "GET /users/login?[]&_=1602534227351 HTTP/1.1" 200 2090 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:24:15 +0200] "POST /users/login?_=1602534227351 HTTP/1.1" 302 887 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:24:15 +0200] "GET /users/routeafterlogin HTTP/1.1" 302 438 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:24:16 +0200] "GET /users/change_pw HTTP/1.1" 500 334 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:26:23 +0200] "GET /users/change_pw HTTP/1.1" 500 3250 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:26:24 +0200] "GET /users/change_pw HTTP/1.1" 500 845 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:22:53:27 +0200] "GET /users/routeafterlogin HTTP/1.1" 302 3512 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:27 +0200] "GET /users/login HTTP/1.1" 200 2946 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/bootstrap.css HTTP/1.1" 200 18933 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/bootstrap-datepicker.css HTTP/1.1" 200 3177 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/famfamfam-flags.css HTTP/1.1" 200 2970 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/bootstrap-colorpicker.css HTTP/1.1" 200 1967 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/font-awesome.css HTTP/1.1" 200 13675 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/chosen.min.css HTTP/1.1" 200 2811 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/jquery-ui.css HTTP/1.1" 200 9448 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/jquery-jvectormap-2.0.5.css HTTP/1.1" 200 4050 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/print.css HTTP/1.1" 200 720 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /css/main.css HTTP/1.1" 200 9821 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/chosen.jquery.min.js HTTP/1.1" 200 7257 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/misp-touch.js HTTP/1.1" 200 962 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/bootstrap-timepicker.js HTTP/1.1" 200 6656 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/bootstrap-colorpicker.js HTTP/1.1" 200 7510 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/bootstrap.js HTTP/1.1" 200 11891 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/keyboard-shortcuts.js HTTP/1.1" 200 2008 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/bootstrap-datepicker.js HTTP/1.1" 200 15500 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/misp.js HTTP/1.1" 200 36326 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/jquery.js HTTP/1.1" 200 85995 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /js/jquery-ui.js HTTP/1.1" 200 125818 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /img/misp-logo.png HTTP/1.1" 200 10834 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /favicon.ico HTTP/1.1" 200 1686 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:28 +0200] "GET /shortcuts/global_menu.json HTTP/1.1" 200 721 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:31 +0200] "GET /users/login?[]&_=1602536008133 HTTP/1.1" 200 1575 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:31 +0200] "POST /users/login?_=1602536008133 HTTP/1.1" 302 887 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:32 +0200] "GET /users/routeafterlogin HTTP/1.1" 302 438 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:22:53:32 +0200] "GET /users/change_pw HTTP/1.1" 500 334 "https://192.168.214.129/users/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:23:07:40 +0200] "GET /users/routeafterlogin HTTP/1.1" 302 3355 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:23:07:40 +0200] "GET /users/change_pw HTTP/1.1" 500 334 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.214.1 - - [12/Oct/2020:23:08:10 +0200] "GET / HTTP/1.1" 302 3355 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
192.168.214.1 - - [12/Oct/2020:23:08:10 +0200] "GET /users/change_pw HTTP/1.1" 500 334 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

**Comment by JakubOnderka** [comment]
Sorry, v2.4.132@20fd5c9 contains that bug. Can you please use current commit 5d994f879996c42137299895e56bbe04ce82bc6c?

**Comment by enjeck** [comment]
I believe this issue is fixed now. If you believe I'm wrong, it can be reopened.
