### ISSUE TITLE
In global_menu.ctp => 'User Guide' url is broken as trying to append the baseurl by default even for external urls

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#6427]
- In global_menu.ctp => 'User Guide' url is broken as trying to append the baseurl by default even for external urls

**Comment by JakubOnderka** [comment]
Already fixed in `2.4` branch :) https://github.com/MISP/MISP/blame/5d994f879996c42137299895e56bbe04ce82bc6c/app/View/Elements/global_menu.ctp#L238

**Comment by adulau** [comment]
Thank you, I missed this commit. All good then! I'll notify the user to update their MISP ;-)
