### ISSUE TITLE
Update timestamp when adding a new tag

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#643]
When I add a new tag to an event, the event timestamp remains constant.

**Comment by thomai** [comment]
Same thing should happen when a tag has been removed.

**Comment by Rafiot** [comment]
The tag is (for now) not synchronized so the timestamp isn't updated. 

It is planned to have exportable tags -> https://github.com/MISP/MISP/issues/369

**Comment by thomai** [comment]
We read data directly out of the database because the Feature #369 is not yet implemented. So, the altered timestamp would be very useful for us anyways.

**Comment by adulau** [comment]
This has been fixed in recent version of MISP.
