### ISSUE TITLE
STIX2 Export failed - Unexpected properties for _CustomObject: (x_misp_values)

### ISSUE THREAD

**Issue by crfrancesco** [MISP/MISP#6430]
STIX2 Export failed: 

exporting MISP events in STIX2 format returns the following error: Unexpected properties for _CustomObject: (x_misp_values)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.5 LTS
| OS version (client)       | Win10, Ubuntu 
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.132 
| Browser                   | Firefox, Chrome

### Expected behavior

Export events in stix2 format

### Actual behavior

STIX2 exported files contain only the following error:
Error while processing your query: Unexpected properties for _CustomObject: (x_misp_values).

### Steps to reproduce the behavior

* Install MISP on Ubuntu : https://github.com/MISP/docker-misp
* Import event in MISP
* Export tab-> STIX2 Generate -> Download ->the downloaded file only contains the error string

**Comment by chrisr3d** [comment]
I can see in the [Dockerfile](https://github.com/MISP/docker-misp/blob/d954df2b201e87eb8ab806128bf0f183d3a2e28f/container/Dockerfile#L62) the correct python STIX2 library is installed, which is already a good point.

However, I cannot reproduce the issue on my side right now but I remember I fixed at some point an issue with this property in custom objects.
Can you by any chance check first if the latest version of the python library is installed, and if needed, update it to be sure?

**Comment by crfrancesco** [comment]
Hi, I checked the version of the STIX2 python library and I confirm that the latest version is installed, that is 2.0.2.

**Comment by crfrancesco** [comment]
Do you have any idea what the cause may be? could you help me resolve this error?

**Comment by chrisr3d** [comment]
I just tested again to be sure, and I can see my Custom object is created correctly:
```
{
    "id": "x-misp-object-weakness--13f1e6e7-87ab-4ced-bb84-d9461b3eb36a",
    "x_misp_values": {
        "text_id": "CWE-119",
        "text_name": "Improper Restriction of Operations within the Bounds of a Memory Buffer",
        "text_description": "The software performs operations on a memory buffer, but it can read from or write to a memory location that is outside of the intended boundary of the buffer.The software performs operations on a memory buffer, but it can read from or write to a memory location that is outside of the intended boundary of the buffer.",
        "text_status": "Usable",
        "text_weakness-abs": "Class"
    },
    "created": "2019-08-12T12:20:13.000Z",
    "modified": "2019-08-12T12:20:13.000Z",
    "labels": [
        "misp:type=\"weakness\"",
        "misp:category=\"vulnerability\"",
        "misp:to_ids=\"False\"",
        "from_object"
    ],
    "x_misp_category": "vulnerability",
    "created_by_ref": "identity--5a8e935e-5484-488c-852c-776f7c7cf985",
    "type": "x-misp-object-weakness"
}
```
I just bumped the latest version of the stix2 python library to be sure we are on the same base.
Can you update both MISP and the python library with the following?
```
cd /var/www/MISP
sudo -u www-data -H git submodule update --init
cd cti-python-stix2
sudo pip3 install -U .
```
I guess you simply have `python3` runnning without a virtual environment if I follow what is in the Dockerfile.
But if there is still an issue, then you probably have another python environment running instead

Let me know how it goes
