### ISSUE TITLE
Sending E-Mails using S/MIME encryption fails

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#6431]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.132

### Expected behavior
Creating new users and sending credentials automatically succeeds with a valid S/MIME certificate.

### Actual behavior
Fails, because:

> [SendEmailException] The message could not be encrypted because the provided key is either expired or cannot be used for encryption.

### Steps to reproduce the behavior
Create new users with S/MIME certificates and check "send credentials".

### Logs, screenshots, configuration dump, ...
```
[Deleted]
```
Edit: removed error message, because it's not tied to this behaviour

**Comment by JakubOnderka** [comment]
Hello, that weird, because this exception should be raised if user has invalid PGP key, not S/MIME certificate. Is PGP key for this user also set or just S/MIME certificate?

**Comment by 3c7** [comment]
The exception was raised during user creation and there was only the S/MIME certificate added.

**Comment by JakubOnderka** [comment]
I just tested it on my instance and it works fine. Can you please try to add user withnout checking "Send credentials automatically" and then send him initial password by clicking Password reset?

**Comment by 3c7** [comment]
Unfortunately, that doesn't work either, but the above error message seems not to be tied to this error. I assumed it is because of the timestamp, but this error does not get logged.

**Comment by JakubOnderka** [comment]
So what error is displayed? Can you also check application logs in Audit section?

**Comment by 3c7** [comment]
Sorry for the late answer. This seems to be related to #6424. If the bug is not fixed, I'm going to report back. :)
