### ISSUE TITLE
Fresh Install MISP 2.4

### ISSUE THREAD

**Issue by plex2012** [MISP/MISP#6437]
Doing fresh install on 

Linux XXXXXX 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

using the following commands:

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh

bash /tmp/INSTALL.sh -c –D

All seems to go ok until ---

#################################################################  (64%)
Next step: Running core Cake commands to set sane defaults for MISP
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/va                                                                                                                         r/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/va                                                                                                                         r/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/va                                                                                                                         r/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/va                                                                                                                         r/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/va                                                                                                                         r/www/MISP/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory                                                                                                                          in /var/www/MISP/app/Config/core.php on line 297

Then further on:

Found existing installation: pymisp 2.4.131
    Uninstalling pymisp-2.4.131:
      Successfully uninstalled pymisp-2.4.131
  Running setup.py develop for pymisp
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/www/MISP/                                                                                                                         PyMISP/setup.py'"'"'; __file__='"'"'/var/www/MISP/PyMISP/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__f                                                                                                                         ile__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'                                                                                                                          develop --no-deps
         cwd: /var/www/MISP/PyMISP/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
  Rolling back uninstall of pymisp
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/CHANGELOG.txt
   from /tmp/pip-uninstall-eu7lqs92/CHANGELOG.txt
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/README.md
   from /tmp/pip-uninstall-eu7lqs92/README.md
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/pymisp-2.4.131.dist-info/
   from /var/www/MISP/venv/lib/python3.6/site-packages/~ymisp-2.4.131.dist-info
  Moving to /var/www/MISP/venv/lib/python3.6/site-packages/pymisp/
   from /var/www/MISP/venv/lib/python3.6/site-packages/~ymisp
ERROR: Command errored out with exit status 1: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokenize;                                                                                                                          sys.argv[0] = '"'"'/var/www/MISP/PyMISP/setup.py'"'"'; __file__='"'"'/var/www/MISP/PyMISP/setup.py'"'"';f=getattr(to                                                                                                                         kenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(c                                                                                                                         ode, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 40, in <module>
    from keys import url, key  # type: ignore
  File "/var/www/MISP/PyMISP/tests/keys.py", line 2
    key = ""
           ^
SyntaxError: EOF while scanning triple-quoted string literal
#########################################################################################  (88%)

Thanks

**Comment by GeoMal86** [comment]
I am hitting the same error on tests/testlive_comprehensive.py.

**Comment by SteveClement** [comment]
Well that sounds like the tests on pyMISP are failing.

In theory, and this is a gut feeling, this should not impact your actual install.

After the install was finished, were you able to login?

**Comment by SantiagoSerrao** [comment]
Hi i have the same issue , i cant login to my misp instance

**Comment by SantiagoSerrao** [comment]
Hi my problem was with the internet connection. The page https://repo.packagist.org/packages.json could not be reached. That is why the problem is generated! Check your connections or else check if with a curl you can reach the url that is from which the package json file is downloaded and it is in Canada.
