### ISSUE TITLE
INSTALL.sh with -M error on Ubuntu 20.04

### ISSUE THREAD

**Issue by makakin** [MISP/MISP#6448]
I am performing a new installation (with Module install) on Ubuntu 20.04

./INSTALL.sh -c -M

it works fine for the MISP Core, until the mispmodules (), it shows a lot of error.

Setting "Plugin.Export_timeout" changed to 300

+ sudo -H -u www-data /var/www/MISP/app/Console/cake Admin setSetting Plugin.Export_pdfexport_enabled true

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
yyyy-mm-dd hh:mm:ss **Error: Failed to query module Enrichment**
**[SocketException] Connection refused**

**Comment by makakin** [comment]
I found that this problem caused by the MISP-Module could not be started.
Port 6666 did not listen.
Follow the instruction: https://github.com/MISP/misp-modules/issues/354 to fix the issue.

**Comment by QTFsniper** [comment]
> I found that this problem caused by the MISP-Module could not be started.
> Port 6666 did not listen.
> Follow the instruction: [MISP/misp-modules#354](https://github.com/MISP/misp-modules/issues/354) to fix the issue.

The script currently does not work as is - or the workaround. The URL called out for the git clone should be https://github.com/stricaud/faup.git not git://github.com/stricaud/faup.git
