### ISSUE TITLE
Export files

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#646]
I am trying to donwload an export file, namely: /events/downloadExport/text/hostname .
From what I understand from the text above: "Click one of the buttons below to download all the attributes with the matching type. This list can be used to feed forensic software when searching for suspicious files. Only published events and attributes marked as IDS signature are exported" I should only get attributes marked as "To IDS".
I also get attributes that are not marked as "To IDS".

**Comment by iglocska** [comment]
Looking into this.

**Comment by elhoim** [comment]
@iglocska ping? :)

**Comment by iglocska** [comment]
woops, forgot about this. Will include it together with the other export issue you posted about!
