### ISSUE TITLE
Can't add a PGP key for an user

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#6462]
Hey, got a some bug after upgrading my install.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 10
| PHP version               | 7.3
| MISP version / git hash   | v2.4.133 (396dedfcfaea6af97c5e595cfd65d8c2c06fd13c) 

### Actual behavior
Got an internal error when trying to add a pgp key for an user.

### Logs, screenshots, configuration dump, ...
2020-10-19 14:23:47 Error: [Error] Call to undefined method CryptGpgExtended::_prepareInput()
Request URL: /admin/users/edit/45
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/GpgTool.php(97): CryptGpgExtended->keyInfo('-----BEGIN PGP ...')
#1 /var/www/MISP/app/Model/User.php(325): GpgTool->validateGpgKey('-----BEGIN PGP ...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationRule.php(275): User->validateGpgkey(Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationSet.php(135): CakeValidationRule->process('gpgkey', Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(268): CakeValidationSet->validate(Array, true)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(99): ModelValidator->errors(Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3502): ModelValidator->validates(Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1838): Model->validates(Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#9 /var/www/MISP/app/Controller/UsersController.php(956): Model->save(Array, true, Array)
#10 [internal function]: UsersController->admin_edit('45')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by JakubOnderka** [comment]
Can you please check your `crypt_gpg` version?

```
cat /var/www/MISP/app/Vendor/pear/crypt_gpg/package.php | grep releaseVersion
```

**Comment by FafnerKeyZee** [comment]
Yep;

$releaseVersion = '1.6.3';
$package->setReleaseVersion($releaseVersion);

**Comment by JakubOnderka** [comment]
Thats weird, thats correct version. But I am afraid, that your system contains more Crypt_GPG and older version is loaded. Can you please send me what command `pear list` returns?

**Comment by FafnerKeyZee** [comment]
Hey, 
Thanks,
Installed packages, channel pear.php.net:

=========================================
Package             Version State
Archive_Tar         1.4.3   stable
Console_CommandLine 1.2.2   stable
Console_Getopt      1.4.1   stable
Crypt_GPG           1.6.0   stable
PEAR                1.10.6  stable
PEAR_Manpages       1.10.0  stable
Structures_Graph    1.1.1   stable
XML_Util            1.4.3   stable

I reinstalled all pear modules and restarted the system. I can again update PGP keys for users. So we can close it.
An idea could be to add a check in the diagnostic page ;-)

Best regards,

**Comment by JakubOnderka** [comment]
Great, thanks for cooperation. In #6463 I will add that check, so it will also show error at diagnostic page.
