### ISSUE TITLE
Backslashes in Snort attributes?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#647]
Why do Snort attributes have trailing backslashes while YARA attributes do not?
Is there a reason? This is quite annoying when you reconstruct the Snort rule on a single line with a "join" operation. Also, the Snort rules exported via the REST API are broken due to the multiple '\'...

Ex:

alert tcp $HOME_NET any -> $EXTERNAL_NET any ( \ 
msg:"CrowdStrike PUTTER_PANDA HTTPCLIENT Request 4"; \ 
flow:to_server, established; \
content: "/Microsoft/update"; http_uri; \ 
content: "/debug"; http_raw_uri; within: 20; \
content: "/default.asp?tmp="; within: 30; http_raw_uri; \ 
classtype: trojan-activity; metadata: service http; \ 
sid: 171400105; rev: 20140401;)

**Comment by iglocska** [comment]
Is that from the Snort rules generated by MISP or simply a snort rule format attribute? If it's the latter than that is a question to the content producer.

**Comment by xme** [comment]
It's a copy paste of the Snort attribute in the event... Check event #417 in miscpriv.circl.lu as a good example.

**Comment by iglocska** [comment]
You can make an edit proposal to the affected attributes if you'd like, or just get in contact with the event creator (using the contact reporter button). Currently Snort rule type attributes have very limited input validation so it is up to the content producer. I'll look into building proper validation for it in the future.

**Comment by cvandeplas** [comment]
Multiline Snort rules need to be ended by a backslash.

So you should not need to join them together.

**Comment by xme** [comment]
But the API outputs single-line Snort rules, including the backslashes. My goal is to import rules into a FireEye IDS and their parser rejects rules with '\' (invalid format). I think that I'll have to drop them via my import script...

**Comment by cvandeplas** [comment]
Would you be able to give a detailed example with the code you are using?
You can send this out of band if you want. You have our contact info

**Comment by xme** [comment]
Working on my import script... I successfully loaded 1000 Snort rules into the FireEye box. It seems that it does not like a file with 97K rules :)
Let's discuss about this OOB sure!

**Comment by Rafiot** [comment]
Related to: https://github.com/MISP/MISP/issues/592

**Comment by elhoim** [comment]
@Rafiot not really related to #592. Reference to Yara was just as a comparison point.

@xme I can see three cases: 
1) attributes of type snort that contain backslashes
2) attributes of type snort that do not contain backslashes
3) autogenerated rules based on some attribute types (from memory: ip-dst, ip-src, hostname, domain)

For 1), you need to edit the attributes or make proposals to change it in an upstream MISP instance; for 2) you are all set and for 3) they seem to be generated as one-liners.

**Comment by Rafiot** [comment]
@elhoim I was thinking sanitizing of the rules but yes, it is not the main point there.
