### ISSUE TITLE
What version of Redis is required for MISP; e.g., for 2.4.133?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6472]
I searched the MISP INSTALL docs and I see that file INSTALL.rhel7.md says install core dependencies including rh-redis32, which brings Redis version 3.2.4. However, as noted in #6392, the Dashboard widget runs a command "memory stats" that was first available in Redis version 4.0, if I have done my research correctly. So it appears to me that Redis version 3.2 is too old at this point, no longer in sync with the MISP code.  I cannot find any other statements about the required version of Redis, please point me if I'm unusually blind today. Thanks in advance.

**Comment by adulau** [comment]
Good question. For MISP core (feed caching, sessions handling), Redis 4 is the minimal version. Nevertheless everything should work with a Redis version 3 beside the monitoring issue with the widget. I would strongly recommend to use a recent Redis 6 as the memory optimizing is quite significant and can be a great improvement while ingesting a lot of feeds.

Looking at the EPEL repository,

https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/r/ and they still use this very old version of Redis.

So the core functionalities will still work...

If you have access to Red Hat Software Collection, you can install the version 5 of Redis. https://developers.redhat.com/blog/2019/06/21/redis-5-now-available-on-red-hat-enterprise-linux-7/

I hope this helps.

**Comment by chrisinmtown** [comment]
Thanks for the answer. Would you me to open a bug/issue on the RHEL7 install that uses Redis version 3.2, which is insufficient? But I see that you just merged a change for the widget memory stats issue, so now 3.2 should work again without trouble, so maybe not.  Please advise.
