### ISSUE TITLE
Expose new Event-Report as Attribute via REST API 

### ISSUE THREAD

**Issue by ChristianParedesTR** [MISP/MISP#6477]
My understanding from the latest MISP blog post update is that the new Event-Report should behave like an attribute. However, it seems like this new attribute type is not available in the current REST API 

**Steps**

- Attempted an attributes search for an Event containing an event-report. The listed attributes did not include the report. 
- Attempted to build a query using the GUI REST client; the /attributes/restSearch API does not show event-report as an available attribute to search.

**Comment by mokaddem** [comment]
Sorry if the blog post was confusing.
What 'behave like an attribute' actually means is it behave like an attribute regarding distribution levels and synchronization.
For example, event report can have their distribution level set to `Inherit event`.

Right now, there is no restSearch for event reports. However, you can use the API to add/edit/deletes reports.
Let us know if you have use cases for having a restSearch for reports.

**Comment by ChristianParedesTR** [comment]
Thank you! That makes sense now. 

I do see a potential use case for having a restSearch for reports. Primarily: "I want to be able to pull all reporting captured in events from X to Y date" and "I want to be able to pull all reporting from events with X or Y tag." 

Process: 

- Capture written intelligence in Event Reports 
- Retrieve all Event Reports to automate summary reporting and/or as an input into other reporting 
- Retrieve all Event Reports for a given event Tag: "I want all reporting we have for events tagged with "Ransomware." 

Thank you again!

**Comment by mokaddem** [comment]
Closing this as it's already feasible to do via `events/restSearch`.
All the search criteria described above are related to the event itself. Thus, filtering events then collecting their associated event report can be done.
Feel to re-open another issue if something not already feasible is needed.
Thanks!

**Comment by joash2808** [comment]
Hi! How do you extract the information out of a event report into a JSON format?
