### ISSUE TITLE
i see NATO still disagrees w/ me to also note the origin of an attack. how stupid.

### ISSUE THREAD

**Issue by noud** [MISP/MISP#6480]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by enjeck** [comment]
This doesn't appear to be a valid bug report. I'm closing this as `invalid`. If you believe I'm wrong, give a reason why and this issue may be reopened. Thank you!
