### ISSUE TITLE
How to import events by STIX 2?

### ISSUE THREAD

**Issue by XueQinliang** [MISP/MISP#6482]
i has tried many ways but don't succeed till now, i use malware pattern in my stix2 json file, but the system showed that "Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool."

**Comment by adulau** [comment]
As mention in the error log, you are missing Python libraries in your MISP installation and you should have a look at the diagnostic tool.
