### ISSUE TITLE
MISP download - Ignoring type filter

### ISSUE THREAD

**Issue by muralivenkataraman** [MISP/MISP#6486]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7.8.0023
| Curl Version               | 7.29
| PHP version               | 7.2.27
| MISP version / git hash   | 2.4.132, hash of the commit
| Browser                   | If applicable

### Expected behavior
Download misp feed based on types ("ip-dst", "domain", "sha256" for a specific tag "osint:source_type="block-or-filter-list"

### Actual behavior
Downloading all types (ignoring the filter).

### Steps to reproduce the behavior
`
curl -k -v -XPOST https://hostname/events/csv/download -H "Authorization: token" -H "Content-Type: application/json" -d @misp.json

{"ignore": "True", "tags": ["osint:source_type=\"block-or-filter-list\""], "type": ["ip-dst", "domain", "sha256", "ip-dst|port"],
 "last": "30d"}

`

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/51952725/96910132-06065080-146d-11eb-9cba-338f21d6bc44.png)

**Comment by muralivenkataraman** [comment]
Hi,

Anyone had a chance to look at this bug?

Thanks
Murali

**Comment by mokaddem** [comment]
@muralivenkataraman Using the restSearch is more appropriate for what you are trying to do:
```
/attributes/restSearch
{
    "returnFormat": "csv",
    [other filtering]
}
```

**Comment by muralivenkataraman** [comment]
Hi Sami,

Thank you for the input.  I will try it out.

Thanks
Murali

**Comment by muralivenkataraman** [comment]
Hi Sami,

I tried the restsearch as per your suggestion and the output is similar to the one above.  It's ignoring the type filter(s).  Here is the sample request/response.

`{
    "returnFormat": "csv",
    "type": {
        "OR": [
            "ip-dst",
            "domain"
        ]
    },
    "last": "15d"
}
`

`"c82e30a6-27e1-4df8-81b9-c16f50967298",3,"Payload delivery","ssdeep","6144:jfsTC8amAXJeZP6BPjIDeLkigDxcvAHjVXjhtBGshMLa1Mj7rtlkiP
60dwtudIye:jvg+Rg1cvAHtE0MLa07rt5POui6","",0,1554925257,"ssdeep","","02f5bf02-c1ac-4142-be6b-978554a19a90","file","file"
"565eeaa1-a469-41ff-bec9-258eabcefa3c",3,"Payload delivery","filename","rdpproto.dll","",0,1554925257,"filename","","02f5bf02-c1a
c-4142-be6b-978554a19a90","file","file"
"f4d7e926-6061-4557-9af1-b498c87fdb5f",3,"Other","size-in-bytes",391680,"",0,1554925257,"size-in-bytes","","02f5bf02-c1ac-4142-be
6b-978554a19a90","file","file"
"03002130-d985-472d-a528-9719d016feec",3,"Other","float",7.893665,"",0,1554925257,"entropy","","02f5bf02-c1ac-4142-be6b-978554a19
a90","file","file"
"ed42d50c-d0b6-4c3c-bdc7-fa1ecdb2f0ee",3,"Artifacts dropped","mime-type","PE32+ executable (DLL) (console) x86-64, for MS Windows
","",0,1554925257,"mimetype","","02f5bf02-c1ac-4142-be6b-978554a19a90","file","file"
"06c3dfcd-ff56-433f-b0c4-f0d3f9267690",3,"Other","text","NetRange:       21.0.0.0 - 21.255.255.255
CIDR:           21.0.0.0/8
`

Thanks
Murali

**Comment by muralivenkataraman** [comment]
Hi Sami,

I am able to download after I included one more condition for the type attribute.  

{"returnFormat":"csv","type":{"NOT":["comment"],"OR":["ip-dst","domain","ip-dst|port"]},"timestamp":"
3d"}

Thanks
Murali

**Comment by iglocska** [comment]
I just tested it and can't reproduce it, are you sure that the request was correct otherwise? What I tested with:

```
{
    "returnFormat": "csv",
    "page": 1,
    "limit": 50,
    "type": {"OR": ["ip-src", "ip-dst"]}
}
```

**Comment by muralivenkataraman** [comment]
Hi Andras,

Thanks for your quick response.  If I remove the CONDITION for the comment, my csv file is populated with all types including the comment type.  

Could this be due to the version that I am running? MISP - 2.4.132 

Thanks
Murali

**Comment by iglocska** [comment]
Yeah it could be, I retested it on the current version with 

```
{
    "returnFormat": "csv",
    "page": 1,
    "limit": 50,
    "type": ["domain", "ip-dst"]
}
```

and it all works as expected. Could you update to the latest version?

**Comment by muralivenkataraman** [comment]
I will try with the latest version and let you know.

**Comment by muralivenkataraman** [comment]
Can you point me to instructions on how to update MISP version ?  I tried the UI -> Server Settings and it complains about not a valid repository.  I also tried from the /var/www/MISP folder, having similar issue.

I used the RPM to install the 2.4.132 version.  I will reach out to the MISP/RPM team as well.

Thanks
Murali

**Comment by iglocska** [comment]
Ah yeah, for the RPM best to reach out there indeed!

**Comment by muralivenkataraman** [comment]
Hi Andras,

Yes, it was the version.  The newer version has no such issues.  It works like a charm.

Thanks
Murali

**Comment by iglocska** [comment]
Awesome, thanks for the feedback!
