### ISSUE TITLE
[Event-reports] State not in sync when adding attributes

### ISSUE THREAD

**Issue by gallypette** [MISP/MISP#6502]
When writing a report and adding attributes at the same time, both views are not in sync. It would be useful to have a notice that new attributes have been added to the event and that the user should reload his page to have access to these through auto-completion.

**Comment by mokaddem** [comment]
The only (not too costly) solution I see would be to use something like eventStream or websocket to trigger the reload. As this is not done anywhere in MISP (yet?) I'll not go down that road.
That left us to frequently poll from the browser but I feel like this is too costly for the result.

**Comment by iglocska** [comment]
An option would be to query the event's state via the timestamp only. This shouldn't be too costly, if the event.timestamp has been modified, it's time to warn the user (we already do something similar for the event edits in general).
