### ISSUE TITLE
[Event-reports] Automagically list attributes corresponding to a tag in a table

### ISSUE THREAD

**Issue by gallypette** [MISP/MISP#6504]
Let's say I have list of attributes that I want to list in my report but I don't want to add them all manually?
For this purpose maybe we could have some special kind of markup to fill in tables automatically depending on tags.

So I would tag all the attributes I want in my report as 'inreport' for instance. And then in the report, I would have something like:
```
|        header         | 
| { @[tag](inreport) }  |
```

**Comment by mokaddem** [comment]
This PR https://github.com/MISP/MISP/pull/6493 to be merged includes the possibility to replace attributes value by their attribute reference (if it exists) or to create new attributes.
So pasting a list of attributes values and getting replaced becomes trivial ;)

**Comment by gallypette** [comment]
neat :)
