### ISSUE TITLE
[Event-reports] Have easier access to attributes

### ISSUE THREAD

**Issue by gallypette** [MISP/MISP#6505]
When adding attributes, the auto-completion sometimes never propose the attribute we want (happened to me with an network-activity / http-method attribute) and the list of attributes is limited to 10 elements, which is a bit frustrating because we know this attribute is out there.

The workaround is the use the attribute's uuid but the user has to remember the "context" tab in the attribute list of the event view.

So maybe it would be useful to have a way to list all attributes when adding an attribute. 
Somthing like hitting TAB when presented `@[attribute]()` could do?

**Comment by mokaddem** [comment]
I increased (#6493) the base number of hints shown and increase this number further for each suggestions typed. It's not exactly tackling this issue but it somehow tries to solve it.
We will see if something more clever like a 'show more hints' is needed.
