### ISSUE TITLE
-D switch in INSTALL.sh is not working

### ISSUE THREAD

**Issue by faisalusuf** [MISP/MISP#6509]
### Expected behavior

INSTALL.sh -D should trigger misp-dashboard installation

### Actual behavior

-D switch is found commented in the INSTALL.sh script 

### Steps to reproduce the behavior

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh

bash /tmp/INSTALL.sh -D

### Logs, screenshots, configuration dump, ...

Refer to line 159 in INSTALL.sh

` ## FIXME: The current state of misp-dashboard is broken, disabling any use.
  ##echo -e "                -D | ${LBLUE}MISP${NC} dashboard"      # dashboard
  ## FIXME: The current state of Viper is broken, disabling any use.
  ##echo -e "                -V | Viper"                            # viper`

**Comment by SteveClement** [comment]
As stated in the script, its broken ATM.

Working on a fix. soon(tm)

Workaround: install only core, and add Dashboard manually as per: https://github.com/MISP/misp-dashboard/blob/master/README.md
