### ISSUE TITLE
Allow search of attributes with GET parameters to allow integration of external script

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#651]
Thinking about an integration case like this:
https://isc.sans.edu/forums/diary/Querying+the+DShield+API+from+RTIR/20113/1#35117

**Comment by xme** [comment]
This is something I'll indeed investigate... :)

**Comment by elhoim** [comment]
I would be very happy if i could do a get like: http://mispinstance.example.com/search/expressions/1.2.3.4+google.com and get the same results on the page as if I was searching in the web app.

**Comment by adulau** [comment]
I suppose the [expansion modules](https://www.github.com/MISP/misp-modules) introduced this ability. I'll close the issue.
