### ISSUE TITLE
Can't log into mysql misp db

### ISSUE THREAD

**Issue by rpiazza** [MISP/MISP#6517]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu..
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.133, hash of the commit
| Browser                   | If applicable

### Support Questions

I'm having various issues trying to install MISP on a ubuntu 18.04.5 VM.

Right now I having problems with the mysql database

```
"Error: Database connection "Mysql" is missing, or could not be created."
```

Here is my database config file

```
rpiazza@misp:/var/www/MISP/app/Config$ more database.php 
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  //'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  'port' => 3306, // MySQL & MariaDB
                  //'port' => 5432, // PostgreSQL
                  'password' => 'e3ab94e2863a7d8e121b6de0f224e6c532a42097bc0d1b2fc81c42af9ff16110',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
          );
  }
```

Here is what happens when I try to look at the db:

```
rpiazza@misp:~$ $SDO_WWW mysql misp -u misp -pe3ab94e2863a7d8e121b6de0f224e6c532a42097bc0d1b2fc81c42af9ff16110
ERROR 1045 (28000): Access denied for user 'misp'@'localhost' (using password: YES)
```

Any ideas?

**Comment by chrisinmtown** [comment]
It looks to me that the mysql database does not have the user and password entry you expect.  First thing to check, if you have root access to the database,  is the users that you have defined:
```
use mysql;
select user, host, plugin from user;
```
And hopefully you'll see something like this:
```
+------------------+---------------+-----------------------+
| user             | host          | plugin                |
+------------------+---------------+-----------------------+
| misp             | localhost     | caching_sha2_password |
+------------------+---------------+-----------------------+
```
This is only scratching the surface of course, because there are so many possibilities here.

**Comment by rpiazza** [comment]
Thanks @chrisinmtown 

Yes - it had an old password.  Once I deleted it and recreate it I was able to log in.
