### ISSUE TITLE
Reverse Proxied MISP not showing X-Forwarded IP

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#6526]
A MISP behind a reverse proxy is only showing the reverse proxy IP address.
It should be able to make it aware of the situation and display the original IP address.

**Comment by iglocska** [comment]
It has been a setting for some time

![image](https://user-images.githubusercontent.com/3668672/97672340-298f5380-1a8a-11eb-9e7a-97aa0810666c.png)

Just change it to the header you wish to use.

**Comment by amady3381** [comment]
The logs shows only the reverse proxy IP. To troubleshoot API connection, this is not helping.

Please provide the exact configuration needed to show the real IP address of the remote users.

**Comment by hkelley** [comment]
I am seeing the same.   I set this option and now I don't have source IP in logs:
```

serverSettingsEdit | Server setting changed | MISP.log_client_ip_header () => (x-forwarded-for)

```

**Comment by amady3381** [comment]
> I am seeing the same. I set this option and now I don't have source IP in logs:
> 
> ```
> 
> serverSettingsEdit | Server setting changed | MISP.log_client_ip_header () => (x-forwarded-for)
> ```

Thank you very much. With these configuration I can see the real IP addresses now.
