### ISSUE TITLE
Unable to upgrade from v2.4.123

### ISSUE THREAD

**Issue by makakin** [MISP/MISP#6545]
Hi Support,

I am using Ubuntu 18.04, currently want to upgrade from 2.4.123 to 2.4.134. However, it seems to have some issues. I tried to fix the permission issue but no luck. Would you please help to take a look? Thanks a lot. 

Currently installed version… v2.4.123 (HEAD)
Latest available version… v2.4.134 (557c4f59e3df7b108cf6f4dabbe5ac7a0ee7efa2)
Status… **Outdated version**
Current branch… **You are not on a branch, Update MISP will fail**
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

**error: pathspec 'app/composer.json' did not match any file(s) known to git.**

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

error: pathspec 'app/composer.json' did not match any file(s) known to git.
You asked to pull from the remote 'origin', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

**Comment by chrisinmtown** [comment]
Difficult to guess; maybe cd to your MISP area, type "git status" and post the result here.

**Comment by iglocska** [comment]
It sounds like you're not on a branch (probably manually checked out 2.4.123):
```
cd/var/www/MISP
git checkout 2.4
git pull origin 2.4
git submodule update --init --recursive
chown -R www-data:www-data /var/www/MISP
```
Something like the above should switch to the correct branch and update your MISP (it assumes that www-data is your apache user). 

From then on you should be able to update via the interface in the future.

**Comment by makakin** [comment]
> Difficult to guess; maybe cd to your MISP area, type "git status" and post the result here.

After run the git status, shows below message.

misp@misp:/var/www/MISP$ sudo -u www-data git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .coveragerc
        .gitchangelog.rc
        .github/
        .gitignore
        .gitmodules
        .travis.yml
        AUTHORS
        CONTRIBUTING.md
        LICENSE
        Pipfile
        Pipfile.lock
        Plugin/
        PyMISP/
        README.debian
        README.md
        VERSION.json
        app/
        build-deb.sh
        build/
        code_of_conduct.md
        cti-python-stix2/
        db_schema.json
        debian/
        docs/
        format/
        misp-vagrant/
        mkdocs.yml
        requirements.txt
        tests/
        tools/
        travis/
        venv/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by makakin** [comment]
> It sounds like you're not on a branch (probably manually checked out 2.4.123):
> 
> ```
> cd/var/www/MISP
> git checkout 2.4
> git pull origin 2.4
> git submodule update --init --recursive
> chown -R www-data:www-data /var/www/MISP
> ```
> 
> Something like the above should switch to the correct branch and update your MISP (it assumes that www-data is your apache user).
> 
> From then on you should be able to update via the interface in the future.

I ran the **git checkout 2.4** with below error message: 

misp@misp:/var/www/MISP$ sudo -u www-data git checkout 2.4
error: The following untracked working tree files would be overwritten by checkout:
        .coveragerc
        .gitchangelog.rc
        .github/ISSUE_TEMPLATE/bug_report.md
        .github/ISSUE_TEMPLATE/feature_request.md
        .github/ISSUE_TEMPLATE/support_request.md
        .github/PULL_REQUEST_TEMPLATE.md
        .gitignore
        .gitmodules
        .travis.yml
        AUTHORS
        CONTRIBUTING.md
        LICENSE
        Pipfile
        Pipfile.lock
        README.debian
        README.md
        VERSION.json
        app/.htaccess
        app/Config/bootstrap.default.php
        app/Config/config.default.php
        app/Config/core.default.php
        app/Config/database.default.php
        app/Config/email.php
        app/Config/routes.php
        app/Console/AppShell.php
        app/Console/Command/AdminShell.php
        app/Console/Command/AppShell.php
        app/Console/Command/AuthkeyShell.php
        app/Console/Command/BaseurlShell.php
        app/Console/Command/EventShell.php
        app/Console/Command/LiveShell.php
        app/Console/Command/PasswordShell.php
        app/Console/Command/ServerShell.php
        app/Console/Command/SupportShell.php
        app/Console/Command/Task/ConfigLoadTask.php
        app/Console/Command/TrainingShell.php
        app/Console/Command/UserInitShell.php
        app/Console/Command/training.default.json
        app/Console/cake
        app/Console/cake.php
        app/Console/dumpDBSchema.sh
        app/Console/worker/start.sh
        app/Console/worker/start_dynamic.sh
        app/Console/worker/stop.sh
        app/Controller/AppController.php
        app/Controller/AttributesController.php
        app/Controller/CommunitiesController.php
        app/Controller/Component/ACLComponent.php
        app/Controller/Component/AdminCrudComponent.php
        app/Controller/Component/ApacheSecureAuthComponent.php
        app/Controller/Component/Auth/ApacheAuthenticate.php
        app/Controller/Component/DeprecationComponent.php
        app/Controller/Component/IOCExportComponent.php
        app/Controller/Component/IOCImportComponent.php
        app/Controller/Component/IndexFilterComponent.php
        app/Controller/Component/RateLimitComponent.php
        app/Controller/Component/RestResponseComponent.php
        app/Controller/Component/RestSearchComponent.php
        app/Controller/Component/ToolboxComponent.php
        app/Controller/DashboardsController.php
        app/Controller/DecayingModelController.php
        app/Controller/DecayingModelMappingController.php
        app/Controller/EventDelegationsController.php
        app/Controller/EventGraphController.php
        app/Controller/EventsController.php
        app/Controller/FavouriteTagsController.php
        app/Controller/FeedsController.php
        app/Controller/GalaxiesController.php
        app/Controller/GalaxyClustersController.php
        app/Controller/GalaxyElementsController.php
        app/Controller/JobsController.php
        app/Controller/LogsController.php
        app/Controller/ModulesController.php
        app/Controller/NewsController.php
        app/Controller/NoticelistsController.php
        app/Controller/ObjectReferencesController.php
        app/Controller/ObjectTemplateElementsController.php
        app/Controller/ObjectTemplatesController.php
        app/Controller/ObjectsController.php
        app/Controller/OrganisationsController.php
        app/Controller/PagesController.php
        app/Controller/PostsController.php
        app/Controller/RegexpController.php
        app/Controller/RestClientHistoryController.php
        app/Controller/RolesController.php
        app/Controller/ServersController.php
        app/Controller/ShadowAttributesController.php
        app/Controller/SharingGroupsController.php
        app/Controller/SightingdbController.php
        app/Controller/SightingsController.php
        app/Controller/TagCollectionsController.php
        app/Controller/TagsController.php
        app/Controller/TasksController.php
        app/Controller/TaxonomiesController.php
        app/Controller/TemplateElementsController.php
        app/Controller/TemplatesController.php
        app/Controller/ThreadsController.php
        app/Controller/UserSettingsController.php
        app/Controller/UsersController.php
        app/Controller/WarninglistsController.php
        app/Lib/Dashboard/Custom/empty
        app/Lib/Dashboard/MispAdminResourceWidget.php
        app/Lib/Dashboard/MispAdminSyncTestWidget.php
        app/Lib/Dashboard/MispAdminWorkerWidget.php
        app/Lib/Dashboard/MispStatusWidget.php
        app/Lib/Dashboard/TrendingTagsWidget.php
        app/Lib/Dashboard/WhoamiWidget.php
        app/Lib/Export/AttackExport.php
        app/Lib/Export/AttackSightingsExport.php
        app/Lib/Export/BroExport.php
        app/Lib/Export/Cac
**Aborting**
misp@misp:/var/www/MISP$

**Comment by iglocska** [comment]
It looks like you made some modifications to those files and git won't let you check out until either they're reverted, stashed or committed.

Good news is, in your case you probably just changed the file ownership / chmod on the files.

You can tell git to not worry about such changes by issueing the following command:

`git config core.fileMode false`

Then redo the steps above and you should be good to go.

**Comment by makakin** [comment]
> It looks like you made some modifications to those files and git won't let you check out until either they're reverted, stashed or committed.
> 
> Good news is, in your case you probably just changed the file ownership / chmod on the files.
> 
> You can tell git to not worry about such changes by issueing the following command:
> 
> `git config core.fileMode false`
> 
> Then redo the steps above and you should be good to go.

Thanks iglocska, I tried the above command, but the same error message was show. T^T

**Comment by iglocska** [comment]
If you didn't make any modifications willingly to your repo you can do this (obviously if you made any modifications to the code base those will be lost):

`git reset --hard HEAD`

Then the update should work after.

**Comment by makakin** [comment]
@iglocska Thank you so much for your help.

Finally, I need to checkout with the parameter -f when checkout and it works.
cd/var/www/MISP
git checkout **-f** 2.4 
git pull origin 2.4
git submodule update --init --recursive
chown -R www-data:www-data /var/www/MISP
