### ISSUE TITLE
Unclear error message when re-adding the same attribute

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#655]
This bug has been found by @kevthehermit when using the Viper MISP module (https://github.com/viper-framework/viper/pull/344#issuecomment-139895277). 

To reproduce the bug: 
1. upload the sample (add samples + all the hashes)
2. add the hashes 

Consequence:
- MISP returns {u'message': u'Error'} 
- an attribute of the type filename|md5 has been added (which is the same as the one of type malware-sample already present)

What should happen:
- clearer error message
- not adding the attribute again

**Comment by Rafiot** [comment]
duplicate attribute => https://github.com/MISP/MISP/issues/338

**Comment by iglocska** [comment]
fiename|md5 vs malware-sample are separate attributes and we don't block "duplicates" in that sense.

For the error message this has been fixed since with error messages in the following format:

```
{
    "name": "Could not add Attribute",
    "message": "Could not add Attribute",
    "url": "\/attributes\/add",
    "errors": {
        "value": [
            "A similar attribute already exists for this event."
        ]
    }
}
```
