### ISSUE TITLE
MISP update problem from v2.4.132 to v2.4.134

### ISSUE THREAD

**Issue by DashCarlos** [MISP/MISP#6553]
I cannot update the service from the web interface. I don't know how to proceed to commit the changes for the Attribute.php file.
There is a very similar post, but it has not worked for me
I appreciate your help

**--- This is the result of launching the update request ---**

cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

From https://github.com/MISP/MISP
   557c4f59e..a3d966824  2.4        -> origin/2.4
error: Your local changes to the following files would be overwritten by merge:
	app/Model/Attribute.php
Please commit your changes or stash them before you merge.
Aborting
Updating 20fd5c95b..a3d966824

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

**Comment by iglocska** [comment]
Did you modify Attribute.php on purpose? If no just do the following:

`git checkout app/Model/Attribute.php`

Then it will work.

**Comment by DashCarlos** [comment]
> Did you modify Attribute.php on purpose? If no just do the following:
> 
> `git checkout app/Model/Attribute.php`
> 
> Then it will work.

I changed that file on purpose. Should I use your command and reconfigure it?

**Comment by iglocska** [comment]
git basically tells you that your uncommitted modifications prevent it from pulling the latest version from the remote. First of all, it is highly recommended that you do not modify the code-base of MISP as that may lead to unforeseen consequences.

Second - and this part is crucial - if you do want to run a modified version of MISP whilst still pulling in the latest changes, I highly recommend familiarising yourself with git, especially commits, merging, forking. 

In order not to run into issues like this every time you fetch the latest version of MISP, you should look into forking the upstream repository and maintaining it by regularly merging the upstream version (which will often require manual merging especially when modifying files that are updated frequently, such as Attribute.php).

**Comment by DashCarlos** [comment]
> git basically tells you that your uncommitted modifications prevent it from pulling the latest version from the remote. First of all, it is highly recommended that you do not modify the code-base of MISP as that may lead to unforeseen consequences.
> 
> Second - and this part is crucial - if you do want to run a modified version of MISP whilst still pulling in the latest changes, I highly recommend familiarising yourself with git, especially commits, merging, forking.
> 
> In order not to run into issues like this every time you fetch the latest version of MISP, you should look into forking the upstream repository and maintaining it by regularly merging the upstream version (which will often require manual merging especially when modifying files that are updated frequently, such as Attribute.php).

The official .ova that I downloaded contains a syntax error on line 1199 of that file, without fixing that I can't access the web interface, so how am I supposed to do it without touching said line? I can provide more information about that error
Sorry for my inexperience and thank you for your answer

https://gyazo.com/baa478db7897ffecd87ea87a86f6e4dd Log file - /var/log/apache2/misp.local_error.log
https://gyazo.com/1d31a07f2eacde3d8ab3b514be9295af Line 1199 - /var/www/MISP/app/Model/Attribute.php
Line correction - https://gyazo.com/f7ec2c2bc8bfa9da8aca100f5de8e951
If I don't apply this change, the service can't work

**Comment by mokaddem** [comment]
@DashCarlos 
First, make sure you have not modified files by doing a
```bash
git status
```
Revert any modified files by checking them out. e.g:
```bash
git checkout app/Model/Attribute.php
```
Finally, you can manually update your MISP instance with these commands
```bash
git pull origin 2.4
git submodule update --init --recursive
chown -R www-data:www-data /var/www/MISP
```
Afterward, you will be able to use the `update MISP` button again.
