### ISSUE TITLE
Checkbox-Lists require page reloads to edit multiple items 

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6563]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.2
| MISP version / git hash   |  v2.4.133 (396dedfcfaea6af97c5e595cfd65d8c2c06fd13c) 
| Browser                   | Firefox

### Expected behavior
Enabling/Disabling several Warninglists in View `/warninglists/index` should not raise an error.
Same for `/tags/index` and the Checkboxes for 'Favourite'

### Actual behavior
First Checkbox-Change will be successfull. Every additional change will be declined with `Request failed due to an unexpected error.`
After reloading the complete page, another (single) edit is possible.

### Steps to reproduce the behavior
- Switch to view `/warninglists/index`
- Try to activate/deactivate more than one Checkbox

### Logs, screenshots, configuration dump, ...
![grafik](https://user-images.githubusercontent.com/72734273/98525017-2fe6b200-2278-11eb-889b-3a981d448a4e.png)

**Comment by mokaddem** [comment]
Hey @marjatech, do you mind posting the commit ID you are on? Because I can't reproduce it on the current HEAD. Thanks!

**Comment by marjatech** [comment]
Hey @mokaddem, here it is:
 v2.4.133 (396dedfcfaea6af97c5e595cfd65d8c2c06fd13c) 

However, i think I saw it even on earlier versions.

**Comment by garanews** [comment]
I confirm I have same issue enabling warninglists:
enable first: ok
enable second: get Request failed due to an unexpected error.
do refresh page 
enable second: ok
enable third: get Request failed due to an unexpected error.
do refresh page
enable third: ok

etc etc
![image](https://user-images.githubusercontent.com/16938405/98970728-8ec65880-2510-11eb-8984-799a8e9882a4.png)

**Comment by garanews** [comment]
2.4.134 fix this behavior

**Comment by mokaddem** [comment]
@marjatech can you try the solution of @garanews and and see if it fixes after the update? Thanks!

**Comment by marjatech** [comment]
@mokaddem I'm unfortunately not able to do the update until end of this week. 
But i'll report as soon as I know.

**Comment by marjatech** [comment]
Can confirm, no issues with this anymore. 
- Not in warningslists (since there even are no checkboxes any more 😄)
- But neither in the Tag-List with the Favourites.

Thank you @mokaddem @garanews
