### ISSUE TITLE
Stop attachTagToObject error back to PyMISP client when tag association already exists

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#6569]
2.4.133

Can `attachTagToObject` in `TagsController.php` not trigger a failed condition when the tag association already exists?

This is causing an error back to the PyMISP client for Events and Attributes that already have the tag. This was previously changed to not trigger that error with https://github.com/MISP/MISP/issues/3245 in May-2018 [here](https://github.com/MISP/MISP/commit/74e77b051106e2c4530a9077ec3a26ac86456a2f#diff-7be251e640d6ce77293f0690f33e1f9ce6263bc983b5c04bb9b468e8394fd3a0).

E.g.
```
ERROR [api.py:2960 - _check_response() ] Something went wrong (403): \
{'saved': False, 'name': 'Could not attachTagToObject Tag', 'message': \
'Could not attachTagToObject Tag', 'url': '/tags/attachTagToObject', \
'errors': 'Failed to attach 1 tags. Reasons: \
{"0":"Event  already has the requested tag attached, no changes had to be made."}'}
```

Appears that it was changed back to a failure this July-2020 [here](https://github.com/MISP/MISP/commit/18f11dd079d9666fe751c3404e2be7f22c69a161#diff-7be251e640d6ce77293f0690f33e1f9ce6263bc983b5c04bb9b468e8394fd3a0R1002})

**Comment by github-germ** [comment]
Could line 850 simply be removed in `TagsController.php` (2.4.143)?
```
  849             if (!empty($existingAssociation)) {
  850                 $fails[] = __('%s already has the requested tag attached, no changes had to be made.', $objectType);
  851                 continue;
  852             }
```

**Comment by ghost** [comment]
Agree, can this be updated to avoid error please? Thanks

**Comment by github-germ** [comment]
Thx

**Comment by ghost** [comment]
Great, thanks!
