### ISSUE TITLE
Add Attribute: Domain -- PunyCode Translation

### ISSUE THREAD

**Issue by getChester** [MISP/MISP#657]
I've had some issues adding attributes to an event where the domain has been translated from punycode.  

xn--80aaagge2acs2agf3bgi.xn--p1ai
xn--80ab7baj4b.xn--p1ai

These domains are also in the Black Hole DNS Sinkhole (http://www.malwaredomains.com) list.

**Comment by getChester** [comment]
Further testing shows that all older TLDs seems to validate properly but not punycode TLDs.

Good: xn--ghq549cb2anjl2suxo.com
Bad: xn--lbrs59br5a.xn--fiqs8s

**Comment by Rafiot** [comment]
hmm, good catch, we need to fix it. It goes in the whole normalisation work to come.
2.5 I would say.

**Comment by pdbcbc** [comment]
I'd like to raise this issue again, as this is still a problem.  More feeds use punycode and there are more unicode domains names than there were 3 years ago.
