### ISSUE TITLE
Import STIX 2 event from IBM X-Force doesn't work

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#6571]
I'm not sure why, but importing IBM X-Force STIX 2 packages doesn't work anymore and it did until a couple of weeks ago. Here is an example of a file that doesn't work and I'm not sure if it's just a mistake in the X-Force export or if it's in the MISP importer.
[xfe-collection_5e714ecc694164f02cbe7a4ff9404ab8.zip](https://github.com/MISP/MISP/files/5517659/xfe-collection_5e714ecc694164f02cbe7a4ff9404ab8.zip)

This is the page where I exported the STIX 2.0 package. https://exchange.xforce.ibmcloud.com/collection/Ransomware-Attacks-on-US-Hospitals-5e714ecc694164f02cbe7a4ff9404ab8

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian.
| OS version (client)       |  Win10
| PHP version               | 7.3.19-1~deb10u1
| MISP version / git hash   | v2.4.134 (158036f525fb494079efb01d35246a3eced184ea)
| Browser                   | Doesn't matter, tried with multiple browsers

### Expected behavior
I expect to have a MISP event created after uploading the file as I did before.

### Actual behavior

When trying to upload a STIX 2.0 JSON file (lossy), I get this error: Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.

### Steps to reproduce the behavior

Upload the file attached after choosing Events > Import from... > STIX 2.0 format (lossy)

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/1122246/98682087-c9d75900-2363-11eb-873d-5192facada8a.png)

**Comment by chrisr3d** [comment]
The import script fails because the stix2 python library returns an exception while loading the content of the file:
`stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': No values for required properties for Report: (labels, object_refs).`
It happens because within the Report object, both labels and object_refs fields are empty and should not be

**Comment by digihash** [comment]
Alright, I'll contact IBM about this and ask them to fix this. Thanks for the investigation @chrisr3d
