### ISSUE TITLE
Error: Invalid Event

### ISSUE THREAD

**Issue by muralivenkataraman** [MISP/MISP#6583]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2.27
| MISP version / git hash   | 2.4.134
| Browser                   | If applicable

### Support Questions
I cleaned up the MISP events by searching and deleting them from the web interface as I wanted to start fresh with the feed.   One of the feeds, AlienVault, I am getting an Error and it says Invalid Event.  I did clear up the events_blocklist table.  I had followed similar steps with 2.4.132 without any issues.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/51952725/99110573-993c2d00-25b8-11eb-8afe-d47dc7e62631.png)

Thanks
Murali

**Comment by muralivenkataraman** [comment]
I had to export the feed info, delete the existing one, and reimport from the json export to get the feed populate again.

**Comment by mokaddem** [comment]
Thanks for getting back to us!
