### ISSUE TITLE
Object template index page should show filter string on results like Event screen

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6595]
The object template page accepts a filter string and searches for matches.  But when the filtered result is on the screen, there is no indicator of the filter string that was applied.  This is different from other screens like Event index, which mark a filtered result with a button on top that has text like "Filters: All: foo" and an X that can be clicked to clear the filter.

**Describe the solution you'd like**

The filter feature on the object templates screen should behave like the filter feature on the event index screen, show a clear indicator of the filter string that was applied and allow clearing the filter.

**Comment by JakubOnderka** [comment]
Thanks for report! This will be fixed after https://github.com/MISP/MISP/pull/6589 is merged.

**Comment by chrisinmtown** [comment]
Wow thanks, totally lucky for me you are already working on this!

**Comment by chrisinmtown** [comment]
The change seems to say, the search string will appear in the filter textbox.  Yes that would be useful.  But that's not how the events index page works. I like the button-like UI thing that appears on the events index screen showing the filter string and especially how it allows me to clear that filter string with a single click.

**Comment by enjeck** [comment]
I see  #6589 is merged, so this should be in progress now

**Comment by chrisinmtown** [comment]
Well it's better in 2.4.141, I'll stop hoping for this screen to become as fancy as the event index page.
