### ISSUE TITLE
MispObject method saveObject returns string on error instead of array

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6598]
In version 2.4.133 I am trying to create objects from custom object templates.  This revealed a failure in MispObject class, saveObject method.  It is supposed to return an array on error, but in this one case it returns a plain string instead, which confuses other code.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | v2.4.133
| Browser                   | n/a

### Expected behavior

On attempt to add a custom object to an event, but botching it, I get a reasonable error message.

### Actual behavior

The PyMISP client gets 403. 

### Steps to reproduce the behavior

See bug https://github.com/MISP/PyMISP/issues/658 for code.

**Comment by chrisinmtown** [comment]
Please consider this patch to line 361, which uses the approach taken on line 346.
```
diff --git a/app/Model/MispObject.php b/app/Model/MispObject.php
index 4911c33..b5a278e 100644
--- a/app/Model/MispObject.php
+++ b/app/Model/MispObject.php
@@ -361,7 +361,7 @@ class MispObject extends AppModel
         } else {
             foreach ($templateFields as $k => $v) {
                 if (!isset($object['Object'][$k])) {
-                    return 'No valid template found and object lacking template information. (' . $k . ')';
+                    return array('value' => array($msg = 'No valid template found and object lacking template information. (' . $k . ')'));
                 }
             }
         }
```

**Comment by mokaddem** [comment]
Thanks a lot for the detailed issue

**Comment by chrisinmtown** [comment]
You're welcome, thanks for taking action so quickly.
