### ISSUE TITLE
Impossible to check the "Is malware" checkbox on file upload page

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#660]
Impossible to check the "Is malware" checbox on file upload page but it works via templates.
Tested on a v2.3 hotfix 124 and MISPpriv

**Comment by iglocska** [comment]
The is malware checkbox depends on your category choice. Did you try changing it to something like payload installation?

**Comment by elhoim** [comment]
I withdraw what I said about MISPpriv (even though I would swear it was the case). But from a private instance v2.3 hotfix 214, it is still the case.
I tried with access both by IP and by , and on a different port than 443 from a Firefox 34.0.5 or a Firefox 40.0.3. That instance is on a closed network.
It does not work when I load the page, if i reload it (CTRL+R or F5), and then it works. But for example if I try to select "Antivirus detection" category it does not revert back to disallowing checking the box.

What the blip....

**Comment by iglocska** [comment]
What the hell? That sounds weird to say the least... On my test instance it
works as expected, but it would be great if I could reproduce that issue.
I've heard of a similar oddity at a certain other organisation that we're
both very familiar with where something odd happens too and ajax stuff
doesn't get refreshed correctly unless you ctrl+f5. Creating the conditions
to reproduce it would be great (in their case it's an older version of
IE...).

**Comment by iglocska** [comment]
Did this issue pop up since last time?

**Comment by elhoim** [comment]
Tried it again, now I am getting problems with other dropdowns, including the ones in add attributes.
When checking the firefox web developer tools console, i get:
![untitled](https://cloud.githubusercontent.com/assets/178521/10137030/c86f5b96-65f7-11e5-9e31-76931700449a.png)

So it is kind of like if Javascript is not working, either for the popover or filtering some values out of the **type** drop down. From a Firefox 38.2 ESR

**Comment by iglocska** [comment]
I know that MISP is using a different code-path in the JS for the pop-overs
under FF. I'll have a look at this tomorrow, right now I am knee deep in
2.4 :)

**Comment by Rafiot** [comment]
Fixed for me.
