### ISSUE TITLE
Make restSearch with returnFormat 'text' to return unique values

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6603]
**Is your feature request related to a problem? Please describe.**
We use the restSearch with returnFormat 'text' to create plain-text IoC-Lists.
However it would be much more convenient if the returned lists would not contain duplicates, since every additional information anyway got stripped when returned in plain-text.

**Describe the solution you'd like**
The restSearch endpoint could do a deduplication of values, only for requested returnFormat 'text'.

**Describe alternatives you've considered**
Deduplication can be done on client side of course, but as I don't see downsides doing it in the server, this sounds much more performant and convenient.
I even think it's kind of what someone using this API would expect from it.

**Comment by mokaddem** [comment]
Hey this is fix for the attribute scope (so `attributes/restSearch`)
