### ISSUE TITLE
Unable to Fetch Feeds and Dead Workers

### ISSUE THREAD

**Issue by PandaLyfe** [MISP/MISP#6608]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Redhat 
| OS version (client)       | 7
| MISP version / git hash   | 2.4.120

### Support Questions
When I try to fetch feeds, all of the jobs would fail. Note that I only have three feeds enabled. (Feed ID 1, 23, and 62) 
I would go to Sync Actions -> List Feeds -> Fetch and store all data feed
Next, I would go to Administration -> Jobs and the page displays all jobs have failed. 
Next, I would also go to Audit -> List Logs and no logs were created from failed fetch attempts. 

It is worth noting that I deleted workers thinking that new ones could be generated when a new task was created. I tried to "start a new worker" and a new one would start, but when I refresh the page, all of them are dead. I'm pretty sure this is the source of the problem. 

As of now, no new feeds are being fetched and all workers are dead. 

### Logs, screenshots, configuration dump, ...

Failed Jobs
![image](https://user-images.githubusercontent.com/26508991/99455802-59e24900-28f6-11eb-937d-7ef146473f1d.png)

Dead Workers
![image](https://user-images.githubusercontent.com/26508991/99455825-623a8400-28f6-11eb-9311-54c1e096a339.png)

**Comment by mokaddem** [comment]
Hello,
Could you update your MISP instance to the latest version and try again?
Quite a few improvements have been made since version 2.4.120.
Thanks!
