### ISSUE TITLE
cached IDS-checkboxes show wrong state when attribute order changed

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6610]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.2
| MISP version / git hash   |  v2.4.134 (360dadc35f4164d2b12c0363c44dca8739724161) 
| Browser                   | Firefox

### Expected behavior
When editing an attribute's IDS-Flag in `/events/view`:
- after a reload in the browser, even if attributes order changes due to the new timestamp of the edited one, IDS-Flags should still show the state of the belongin attribute
- ideally it should be visible, if the event got unpublished due to this change, so no reload is required

### Actual behavior
In the scenario above, the edited IDS-Checkbox stays in place while attribute order changes, which leads to a wrong state beeing shown for the the attribute which now got the position of the edit.
A reload with completely disabled caching (Shift+F5 in Firefox) fixes the view.

### Steps to reproduce the behavior
- open any event with >2 attributes
- toggle IDS for any attribute which is **not the first** in the list, and confirm
- Hit F5 -> IDS checkboxes do not represent real state
- Hit Shift+F5 -> IDS Flags are shown as expected

### Logs, screenshots, configuration dump, ...
![grafik](https://user-images.githubusercontent.com/72734273/99528055-ff9cc300-299d-11eb-87f0-15105f619945.png)

**Comment by mokaddem** [comment]
@marjatech I can't reproduce your issue. Do you have any warnings/errors in your browser console while performing the steps described above?

**Comment by marjatech** [comment]
@mokaddem Only warning is:  `This page uses the non standard property “zoom”.`

I have the same on two independent instances in different networks. 
I just did a test with Chrome, and can't reproduce it there. So seems to only happen with Firefox.

**Comment by mokaddem** [comment]
Hey. I tried with both Chrome and Firefox and everything is working fine.
Do you any suspicious entries in your logs (`/app/tmp/logs/errors.log`)

**Comment by marjatech** [comment]
looks like this could be fixed by switching option `Security.disable_browser_cache` to `true`
