### ISSUE TITLE
Allow pulling for All communities and Connected communities only

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#6614]
Hi all.
We synced two servers by allowing pulling only, i want to allow pulling event when distribution level is all communities (3) or connected communities(2).

I tried to create custom rule by add additional sync parameters {"distribution":"2","distribution":"3"} but it is taking the last one only.

**Comment by ahmedxuae91** [comment]
Update: tried to clone how OR operator works for TAGs and ORGs but still didn't work: {"OR": [{"distribution": ["2","3"]}]}.

Appreciate if anyone can help me in this

**Comment by mokaddem** [comment]
Hey @ahmedxuae91 ,
The filtering sync rule are based on the same rule as the index filter. You can use the index filtering widget to check how they should be encoded
So for you, it would be
```json
{
    "distribution": "2|3"
}
```
Note that `"distribution": [2,3]` can now be used if the remote end updated their instance on the latest version. So to be sure, just use the pipe `|` separated parameter.
