### ISSUE TITLE
PyMISP's search_index

### ISSUE THREAD

**Issue by SoheiMitsukawa** [MISP/MISP#6616]
Hello.

I have a question about PyMISP's search_index.
I wrote the following code.
However, I was not able to get the desired event.
Perhaps it doesn't seem to hit the search if it contains \.
How can I get the event I want?

------------------------------

\#!/usr/bin/env python3
\# -*- coding: utf-8 -*-
from pymisp import ExpandedPyMISP, MISPEvent

\# Const:
MISP_URL = 'https://hoge'
MISP_AUTHKEY = 'fuga'

if __name__ == '__main__':
    sample_info = r'C:\Windows\System32\notepad.exe'

    \# MISP Connect
    misp = ExpandedPyMISP(MISP_URL, MISP_AUTHKEY, ssl=False, debug=False)

    \# Add event
    e = MISPEvent()
    e.info = sample_info
    print(misp.add_event(e, pythonify = True))
    \#Output: <MISPEvent(info=C:\Windows\System32\notepad.exe)

    \# Search event
    print(misp.search_index(eventinfo=sample_info, pythonify = True))
    \#Output: []

exit()

**Comment by Rafiot** [comment]
So it's a bit of a weird one: you need to escape the `\` in the search (but not in the info field).

The following one will work:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pymisp import ExpandedPyMISP, MISPEvent

# Const:
MISP_URL = 'https://hoge'
MISP_AUTHKEY = 'fuga'

if __name__ == '__main__':
    sample_info = r'C:\Windows\System32\notepad.exe'

    # MISP Connect
    misp = ExpandedPyMISP(MISP_URL, MISP_AUTHKEY, ssl=False, debug=False)

    # Add event
    e = MISPEvent()
    e.info = sample_info
    print(misp.add_event(e, pythonify = True))

    # Search event
    print(misp.search_index(eventinfo=r'C:\\Windows\\System32\\notepad.exe', pythonify = True))
```

cc @MISP/developers

**Comment by SoheiMitsukawa** [comment]
Thank you for telling me.
From now on, I will escape and search.
Thanks,
