### ISSUE TITLE
Incorrect proposed database fix command for users table on newsread column

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#6618]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian buster
| OS version (client)       | -
| PHP version               | 9.3.19
| MISP version / git hash   | 2.4.134 / 5a29fcc3703af536ce27eec436ee396e807d7b83
| Browser                   | -

The Diagnostic page shows for the Schema status:

Table name | Description | Expected schema | Actual schema
-- | -- | -- | --
users | Column `newsread` is different | newsread YES int  10  int(11) unsigned 0 | newsread YES int  10  int(11) 0

The proposed fix is:
```sql
ALTER TABLE `users` MODIFY COLUMN `newsread` int(11) DEFAULT "0" NULL ;
```
but it should be:
```sql
ALTER TABLE `users` MODIFY COLUMN `newsread` int(11) UNSIGNED DEFAULT "0" NULL ;
```

**Comment by mokaddem** [comment]
Thanks for the report, I added support of `unsigned` in the recovery query
