### ISSUE TITLE
No log entry for events when altering associated attributes

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#662]
A few weeks ago, I recognized, that every changing attribute (add, edit, delete) causes a log entry for the altered attribute as well as for the associated event because its timestamp has changed.
The timestamp is still updating but there are no log entries for the events anymore. Is this no longer the case because it was a bug or did you change the logging accidently?

**Comment by iglocska** [comment]
I didn't remember that I have fixed that, but indeed, the timestamp update
should not be logged, so that is the correct behaviour!

**Comment by elhoim** [comment]
Answered. Closing.
