### ISSUE TITLE
MISP database is broken 

### ISSUE THREAD

**Issue by CeesMandjes** [MISP/MISP#6622]
Hi,

I just performed a fresh install of the new version of MISP. However, when I login, I get the following message:
`Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live). An update might also be in progress, you can see the progress in Update Progress`

When I check the progress of the update, it is stuck on 100% on the following task:
"Database Update progress for update destroyAllSessions"

Also, If I check diagnotiscs it says the following:
```
Warning The MISP database state does not match the expected schema. Resolving these issues is recommended.
⚠ This diagnostic tool is in experimental state - the highlighted issues may be benign. If you are unsure, please open an issue on with the issues identified over at https://github.com/MISP/MISP for clarification.
```

I have initialized the MISP database with the following command:
`mysql -D misp < /var/www/MISP/INSTALL/MYSQL.sql`

Is the problem known? Does someone know how I can fix this?

**Comment by CeesMandjes** [comment]
I've also encountered this problem on other machines on which we are running MISP instances on....

**Comment by CeesMandjes** [comment]
I actually did found an error in /var/www/MISP/app/tmp/logs:
`2020-11-19 19:00:35 Warning: Warning (2): include_once(/var/www/MISP/app/Config/database.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include_once - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::_init() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::getDataSource() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 83
AppController::_setupDatabaseConnection() - APP/Controller/AppController.php, line 623
AppController::beforeFilter() - APP/Controller/AppController.php, line 143
ServersController::beforeFilter() - APP/Controller/ServersController.php, line 37
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-11-19 19:00:35 Warning: Warning (2): include_once() [<a href='http://php.net/function.include'>function.include</a>]: Failed opening '/var/www/MISP/app/Config/database.php' for inclusion (include_path='/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:/var/www/MISP/app/Vendor/pear/pear_exception:.:/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include_once - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::_init() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::getDataSource() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 83
AppController::_setupDatabaseConnection() - APP/Controller/AppController.php, line 623
AppController::beforeFilter() - APP/Controller/AppController.php, line 143
ServersController::beforeFilter() - APP/Controller/ServersController.php, line 37
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-11-19 19:00:35 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /servers/updateProgress
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 /var/www/MISP/app/Controller/AppController.php(623): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/AppController.php(143): AppController->_setupDatabaseConnection()
#3 /var/www/MISP/app/Controller/ServersController.php(37): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2020-11-19 19:00:38 Warning: Warning (2): include_once(/var/www/MISP/app/Config/database.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include_once - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::_init() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::getDataSource() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 83
AppController::_setupDatabaseConnection() - APP/Controller/AppController.php, line 623
AppController::beforeFilter() - APP/Controller/AppController.php, line 143
ServersController::beforeFilter() - APP/Controller/ServersController.php, line 37
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-11-19 19:00:38 Warning: Warning (2): include_once() [<a href='http://php.net/function.include'>function.include</a>]: Failed opening '/var/www/MISP/app/Config/database.php' for inclusion (include_path='/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:/var/www/MISP/app/Vendor/pear/pear_exception:.:/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include_once - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::_init() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 67
ConnectionManager::getDataSource() - APP/Lib/cakephp/lib/Cake/Model/ConnectionManager.php, line 83
AppController::_setupDatabaseConnection() - APP/Controller/AppController.php, line 623
AppController::beforeFilter() - APP/Controller/AppController.php, line 143
ServersController::beforeFilter() - APP/Controller/ServersController.php, line 37
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-11-19 19:00:38 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /servers/updateProgress
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 /var/www/MISP/app/Controller/AppController.php(623): ConnectionManager::getDataSource('default')
#2 /var/www/MISP/app/Controller/AppController.php(143): AppController->_setupDatabaseConnection()
#3 /var/www/MISP/app/Controller/ServersController.php(37): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ServersController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}`

It seems it cannot open `/var/www/MISP/app/Config/database.php`. However, the file is present:
`/var/www/MISP/app/Config# ls
bootstrap.default.php  bootstrap.php  config.default.php  config.php  config.php.bk  core.default.php  core.php  database.default.php  database.php  email.php	routes.php`

The content of the file is as follows:
`/var/www/MISP/app/Config# cat database.php
<?php
class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'misp',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => '<40 charss>',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
	);
}`

**Comment by DISREL** [comment]
It seems like your database was not properly initialised and your instance is not configured properly. Try doing these steps again, assuming you have Ubuntu 20.04

https://misp.github.io/MISP/INSTALL.ubuntu2004/#set-up-db-user-and-import-empty-misp-db

https://misp.github.io/MISP/INSTALL.ubuntu2004/#9-misp-configuration

**Comment by CeesMandjes** [comment]
I am still facing the same issue. Also, the MISP instance still works; I can login and create events which are stored in the Mysql database. Do you still think it has to do with the database then?

**Comment by DISREL** [comment]
I think you are not facing an issue then. What does the database diagnostics say?

**Comment by CeesMandjes** [comment]
It says the following:
![Screenshot 2020-11-20 at 9 28 23 AM](https://user-images.githubusercontent.com/17592619/99777535-be79ef80-2b12-11eb-9f4b-3caffe16a607.png)

**Comment by CeesMandjes** [comment]
![Screenshot 2020-11-20 at 9 29 24 AM](https://user-images.githubusercontent.com/17592619/99777623-e23d3580-2b12-11eb-9f91-44be077617da.png)

**Comment by CeesMandjes** [comment]
Hmmm, I fixed the problem. The first time when I login I get this error in the UI:
![Screenshot 2020-11-20 at 10 55 04 AM](https://user-images.githubusercontent.com/17592619/99786487-d9526100-2b1e-11eb-813a-df9fae04164c.png)

When I go to `server settings -> MISP settings`  and set:
MISP.live = true

Logout, and log back in; the error disappears.

**Comment by DISREL** [comment]
It does say "The highlighted issues may be benign" as the Diagnostic Tool is in BETA.

Do not put set MISP.live = true until you're sure that everything is set up properly. Unless this is a localhost only environment, you are welcome to do as you like.

You can close the issue now.

**Comment by mokaddem** [comment]
@DISREL is totally right! benign issue are.. benign. No need to worry about them. This is mostly due to a difference between the RDBMS used to export de schema your instance is comparing onto. I added a small notice about it.

**Comment by CeesMandjes** [comment]
Thank y'all for helping me out :)
