### ISSUE TITLE
internal error when generating a report from an event.

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#6631]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.1 LTS
| OS version (client)       | 
| PHP version               | 7.4
| MISP version / git hash   | v2.4.134 (5656771a95885b1a2a4de587c1fd0332307cca7a) 
| Browser                   | 

### Expected behavior
Generate a report

### Actual behavior
When generating a report, after selecting the filters, we got an internal error. If we remote the "tag" filter, it works fine.

### Steps to reproduce the behavior
CF Actual behavior

### Logs, screenshots, configuration dump, ...

> 2020-11-20 09:25:36 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'where clause'
Request URL: /eventReports/reportFromEvent/72231
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/Attribute.php(3490): Model->find()
#7 /var/www/MISP/app/Lib/EventReport/ReportFromEvent.php(44): Attribute->fetchAttributes()
#8 /var/www/MISP/app/Lib/EventReport/ReportFromEvent.php(66): ReportFromEvent->getAttributes()
#9 /var/www/MISP/app/Model/EventReport.php(905): ReportFromEvent->generate()
#10 /var/www/MISP/app/Controller/EventReportsController.php(347): EventReport->getReportFromEvent()
#11 [internal function]: EventReportsController->reportFromEvent()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#15 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#16 {main}

**Comment by mokaddem** [comment]
Thanks a lot for the report!
