### ISSUE TITLE
Query the running instance to know the API version

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#664]
We need the following options to avoid weird crashes on the API:
* knowing the exact version of the code running on the server. I see there is the hotfix version on the webpage but it would be nice to do a query through the API and as the API will evolve slower than the hotfixes, we probably need a new code for that. What do you think?
* knowing the most recent version of the code available on github (VERSION.json is the best one to fetch, possibly with the API version added).

**Comment by iglocska** [comment]
You can see the exact version on the diagnostics page (this fetches VERSION.json and the one on github and tells you whether you should upgrade), and as of earlier today on the footer. 

With 2.4 version mismatches during the pull/push are logged (you'll get a log entry that the other server is ahead / behind with the exact version they are running).

**Comment by iglocska** [comment]
If you mean adding a simple API to query the local version - that would make sense, I'll add that!

**Comment by Rafiot** [comment]
yes, adding a simple API to query the local version would be nice: it will be important if/when there will be a non-backward compatible change in the API and we have to inform the viper user

**Comment by iglocska** [comment]
Sounds good will implement it tomorrow.

**Comment by iglocska** [comment]
Guess it's technically tomorrow already...

**Comment by Rafiot** [comment]
haha. I'm also doing some code on viper, but I'm not sure I'll implement it right away :)
