### ISSUE TITLE
Event index search with parameter published=True returns unpublished events

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6642]
Searching the event index page with published=True unexpectedly returns both published and unpublished events.  

First logged here: https://github.com/MISP/PyMISP/issues/455

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  RedHat,
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133
| Browser                   | Firefox

### Expected behavior

Browsing to https://my-misp-server/events/index/searchpublished=True

Should yield a list of published events only.

### Actual behavior

Yields a list of published and unpublished events.

### Steps to reproduce the behavior

Browse to the URL shown above after fixing it up for your instance and inspect the list, setting the sort on the published field helps.

### Guesses

This feature is implemented in the EventController index() function which calls function __setIndexFilterConditions.  That has suspicious code about line 289, I don't think the Boolean parameter 'published' can ever have value 2, so I wonder if a copy-paste error is lurking here?

```
                    case 'published':
                        if ($v == 2) {
                            continue 2;
                        }
                        $this->paginate['conditions']['AND'][] = array('Event.' . substr($k, 6) . ' =' => $v);
                        break;
                    case 'hasproposal':
                        if ($v == 2) {
                            continue 2;
                        }
                        $proposalQuery = "exists (select id, deleted from shadow_attributes where shadow_attributes.event_id = Event.id and shadow_attributes.deleted = 0)";
                        if ($v == 0) {
                            $proposalQuery = 'not ' . $proposalQuery;
                        }
                        $this->paginate['conditions']['AND'][] = $proposalQuery;
                        break;
```

**Comment by mokaddem** [comment]
What you are describing is correct.
`/events/index/searchpublished=True` is not a valid way to pass parameters and this defaults to `/events/index`.
I think what you are actually looking for is `/events/index/searchpublished:1`.

Now for your guess, it may look wrong but it's actually a hack. `searchpublished:2`will returns events regardless of their publish state (so, published=0 & published=1).

PS: I noticed that you are referencing code quite often (which is great!). GitHub offers the possibility to reference lines of code by using their permalink feature. Issues will look better and will stay accurate as it's tied with the commit ID.
e.g.:
https://github.com/MISP/MISP/blob/2c29b7809815f70d84bf4538307c347ba02b16c2/app/Controller/EventsController.php#L289-L294

Cheers!

**Comment by chrisinmtown** [comment]
Thanks for explaining. I confirm that https://my-misp:12345/events/index/sort:published/direction:desc/searchpublished:0 yields only unpublished events and https://.../searchpublished:1 yields only published events.
