### ISSUE TITLE
MD5 - SHA1 - SHA256 + VT links

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#665]
Hi all,

I have observed in some MISP instances that when you provide a simple MD5, MISP queries VT, adds the link as external analysis and finally adds the respective SHA1 and SHA256 values. 
Is this feature available for our MISP instances? 

Cheers,
Andreas

**Comment by adulau** [comment]
Sure, It's part of the viper.li MISP module ( https://github.com/viper-framework/viper/blob/master/modules/misp.py ).

We do it automatically using viper for some of our MISP instances. If you have a viper.li session running with a MISP module, you can simply do for auto expansion of hashes:

~~~
 misp check_hashes -e <EVENT ID> -p
~~~

Let us know if you need additional information.

Cheers

**Comment by advancedeng** [comment]
Thanks a lot. Just spotted it! Cheers!

PS. As far as I remember the next version of MISP will have some enrichment capabilities (VT, pDNS, whois etc.. ) Am I right?

**Comment by Rafiot** [comment]
In a first time, those enrichment capabilities will be available through viper, but yes, it would be great to have them bundled in the distribution.

**Comment by advancedeng** [comment]
Thanks a lot both of you! 

Cheers

**Comment by Rafiot** [comment]
This functionality will be implemented using misp-modules
