### ISSUE TITLE
Even more vhash cannot be added to MISP

### ISSUE THREAD

**Issue by jsman** [MISP/MISP#6651]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.135

### Expected behavior
All vhash values found on VirusTotal can be added to MISP

### Actual behavior
Due to the current input validation being performed valid vhash values are rejected.

For previous issues regarding vhash, please see #6266 #6336 

Since there is no public specification on the vhash format I would suggest dropping input validation since it is not possible to know what characters are used to form the vhash. Anything else would just be a gamble, but a regex that probably covers all possible vhash values would be printable characters like: `^[\x21-\x7E]+$`

Pulling in @rmkml to discuss this as he wrote the code.

### Steps to reproduce the behavior
Try to add any of these vhash values to MISP:

- [htm:4b2a513d0525c4bf3e547a4537d3d15e](https://www.virustotal.com/gui/file/3116f21acd3c77293d0a0a9550fde2c60cb32b16fed358573f69ab1a66386caa/details)
- [0360366d051)z723z](https://www.virustotal.com/gui/file/ce59b27d8dea322a3f642043fa2f66aededaa4e2390f76aad03738034ed39f1f/details)
- [173066541d1d10541bz9?z1](https://www.virustotal.com/gui/file/5d3f433824b324807366d6426b720c8541a8cd7f82000c2b96191292fd7e3f67/details)
- [01601c7"z](https://www.virustotal.com/gui/file/5e7bb527406790827b7d0bf5911f2584c2b76fddd600c246059b08c606fd99a8/details)
- [0540365d05\[z3c3z](https://www.virustotal.com/gui/file/998d4d8d6a64511c7e43338104a9c50aa8620dba5c9d92dae83d1d89c6cb36da/details)
- [016{z](https://www.virustotal.com/gui/file/6ba4ffe92c500eb9674394930c04f5685c249517c88add250c282c82f9de0191/details)
- [1160976d555c055d5d1dbz3811#zc05](https://www.virustotal.com/gui/file/235752f22f1a21e18e0833fc26e1cdb4834a56ee53ec7acb8a402129329c0cdd/details)

**Comment by iglocska** [comment]
yeah - at this point dropping the validation altogether seems like the best option. I'd wish they'd share the documentation of the format....

**Comment by iglocska** [comment]
Should be fixed via 953f0444819fc8724f4d9e9cc1d6d4ef5ff7e15f
