### ISSUE TITLE
Taxonomies CLI update

### ISSUE THREAD

**Issue by maro584** [MISP/MISP#6654]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat 7
| OS version (client)       | None
| PHP version               | 7.4
| MISP version / git hash   | 2.4.134, hash of the commit
| Browser                   | None

### Support Questions

Please advise how to update MISP taxonomies / warninglists  via CLI not from GUI

I have check a docs and there is no info about that or maybe I missed something.

http://circl.lu/doc/misp/taxonomy/

Appreciate help.

**Comment by mokaddem** [comment]
You can use this command to update the taxonomies
```bash
MISP/app/Console/cake Admin updateTaxonomies
```

You can find documentation and more commands at this on your instance `/events/automation`

Cheers
