### ISSUE TITLE
Migration to new API key fails

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#6659]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Red Hat 7.9
| OS version (client)       | MacOS
| PHP version               | 7.2
| MISP version / git hash   | 2.4.135

### Expected behavior
After having enabled the enhanced auth key setting in Security, the migration of existing api keys via the tool in Diagnostic should migrate all keys.

### Actual behavior

It fails with an error 500.

### Steps to reproduce the behavior

1. Update existing instance to 2.4.135
2. Enable advanced auth keys
3. Try to migrate keys using the tool accessible in the diagnostic page

### Logs, screenshots, configuration dump, ...
```
2020-11-27 12:01:47 Warning: Warning (512): Model "User" is not associated with model "AuthKey" in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Behavior/ContainableBehavior.php, line 342]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
ContainableBehavior::containments() - APP/Lib/cakephp/lib/Cake/Model/Behavior/ContainableBehavior.php, line 342
ContainableBehavior::beforeFind() - APP/Lib/cakephp/lib/Cake/Model/Behavior/ContainableBehavior.php, line 123
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 129
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Model::buildQuery() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3110
Model::find() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3020
UsersController::updateToAdvancedAuthKeys() - APP/Controller/UsersController.php, line 2705
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2020-11-27 12:01:47 Error: [Error] Call to a member function create() on null
Request URL: /users/updateToAdvancedAuthKeys
Stack Trace:
#0 [internal function]: UsersController->updateToAdvancedAuthKeys()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```
### Attempts to solve it

It works if we uncomment the line 212 in Model/User.php and clean the cache. So I believe commit https://github.com/MISP/MISP/commit/68fc0eca7dcf1eeed04249ad75f2433508fe0d58 is not fully working in that scenario.

**Comment by lfortemps** [comment]
This was solved in a recent commit

**Comment by iglocska** [comment]
Yeah it was an annoying chicken vs egg issue. Basically the Authkey table was missing in the db, but expected by the user model - so the login would actually fail. This is annoying as the update process is initiated once a user logs in.

The workaround before was to launch the update script via the CLI, but that was not obvious at all. Since the fix, the authkey model is only associated with the user model ad hoc on initialisation of the model - and only if the table already exists.
