### ISSUE TITLE
Going directly to the proposal at the attribute level

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#667]
When you have quite large event with a lot of attributes, it can be difficult to find back a proposal. Would it be possible to show an event with just the proposal proposed without the attributes?

**Comment by elhoim** [comment]
Hmmm sounds better than my idea in https://github.com/MISP/MISP/issues/275 . I am closing the one I opened before then.

**Comment by iglocska** [comment]
Or both, right now there is no filtering on the attribute list within an event. I'll look into adding some filters for it in the future.

**Comment by adulau** [comment]
quick-filter is there!
