### ISSUE TITLE
PHP Version Update Issue

### ISSUE THREAD

**Issue by luna7391** [MISP/MISP#6678]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat, ...
| OS version (client)       | Win10
| PHP version               | PHP ini path:… /etc/opt/rh/rh-php71/php.ini
||PHP Version (>7.4 recommended): 7.1.8 (Version unsupported, update ASAP)
||PHP CLI Version (>7.4 recommended): 7.4.13 (Up to date)
| MISP version / git hash   | v2.4.135 (15f819a2162d51e46714d18aa32697a6cc459850)
| Browser                   | All

### Support Questions
Hi, I'm trying to update PHP to the latest version but see the issue shown in the screenshot below, the following commands were used (please bear with as my Linux experience isn't good):

yum   install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum-config-manager --enable   remi-php74
yum install php php-common   php-opcache php-mcrypt php-cli php-gd php-curl php-mysql -y
(I re-ran the above command to include php-mbstring php-xml et al).

Are you able to advise what additional commands I need to run, and if required, which config files need to be updated? Many thanks

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/38982979/100763920-b3b23b00-33ed-11eb-8729-7ecb7788a92a.png)

**Comment by mokaddem** [comment]
Hi,
I'm not familiar with the OS you are using, so sorry in advance.
Did you encounter any issues while trying to update to a newer PHP version?
If the newer PHP version installation complete, did you restart apache?
Thanks

**Comment by luna7391** [comment]
Hi Sami, thanks for your response.

No there weren't any issues running the PHP update other than after running "yum install php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql -y" I checked the PHP Extensions in Diagnostics and could see some of the CLI PHP Extensions hadn't updated, I re-ran this command to include those extensions (such as mbstring and xml) which resulted in the above status. However the issue I'm experiencing is the Web PHP Extensions haven't updated to 7.4, possibly because the PHP ini Path (as shown above) is still pointing to the PHP 71 ini. It's this bit I'm struggling with to get MISP to point to 7.4.  Thanks.

**Comment by mokaddem** [comment]
Throwing a wild guess but could it be that you have to enable the newer PHP version on apache side?
With something like this
```bash
/usr/bin/scl enable rh-php74
```

**Comment by luna7391** [comment]
Hi, PHP 7.4 seems to be installed ok as shown in the screenshots. It looks the "PHP ini path:…" needs changing from "/etc/opt/rh/rh-php71/php.ini" to 7.4, do you know where this is changed?

![MISP Dev PHP Version](https://user-images.githubusercontent.com/38982979/107676498-1bf48700-6c91-11eb-904d-dbd92be994ed.PNG)
![MISP Dev PHP Version GUI](https://user-images.githubusercontent.com/38982979/107676507-20b93b00-6c91-11eb-88ce-79cfe24bc701.PNG)

Thanks.

**Comment by luna7391** [comment]
Hi, anybody able to provide an answer to the above regarding the PHP.ini path? Many thanks.

**Comment by SteveClement** [comment]
This is an OS question, I am not familiar enough with RHEL to further help, sorry.

Feel free to reach out to the community on the [support channel](https://matrix.to/#/!lRaWhVOeOWwxejNuQo:gitter.im?via=gitter.im&via=matrix.circl.lu&via=matrix.org).
