### ISSUE TITLE
Support for installation of MISP behind proxy & using "https" instead of "git"

### ISSUE THREAD

**Issue by mik0w** [MISP/MISP#6679]
Hello,

Recently I have been trying to install MISP in a highly protected environment, and finally I've managed to do that, so in *Additional context* of this feature request I've included a guide on how to install MISP, when you have strict network policy in your organization.

## Feature request

**Is your feature request related to a problem? Please describe.**
Installation of MISP required me to do all of the steps described in *Installing MISP behind proxy etc.* below, and `fatal: unable to connect to github.com` error while some of the `git clone`s almost made me give up this installation.

**Describe the solution you'd like**
That would be nice if there was a possibility of configuring proxy in the INSTALL.sh script, and what is more, if `https://` was used instead of `git://` in installation script. 

**Describe alternatives you've considered**
Alternative approach is described below:

### Installing MISP behind proxy etc.

So, let's say you have a client who have highly secured network and uses proxy, and it's network operations team has a big inertion, so it's hard to make them open possibility of i.e. ssh connections to some external resources for your machine. This description is made for Ubuntu Server, but maybe one can use them to find a solution of their problem on other operating systems.  

1. Set system-wide proxy in `/etc/environment`: 

```
http_proxy="http://myproxy.server.com:8080/"
https_proxy="http://myproxy.server.com:8080/"
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
HTTP_PROXY="http://myproxy.server.com:8080/"
HTTPS_PROXY="http://myproxy.server.com:8080/"
NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"
```
2. Set proxy for apt: 

Create or edit the following file: `/etc/apt/apt.conf.d/proxy.conf` as shown below: 

```
Acquire::http::proxy "http://myproxy.server.com:8080/";
Acquire::ftp::proxy "ftp://myproxy.server.com:8080/";
Acquire::https::proxy "https://myproxy.server.com:8080/";
```
3. set proxy for git: 

`git config --global --add http.proxy http://USERNAME:PASSWORD@PROXY_ADDRESS:PROXY_PORT`
`git config --global --add https.proxy http://USERNAME:PASSWORD@PROXY_ADDRESS:PROXY_PORT`

If `INSTALL.sh` script used only `git clone` with `https://(...)`, the steps above would do the work. But, unfortunately there are two clones that for some reason use `git://` form of URL,  which uses git protocol. 
```
cd /tmp
false; while [[ $? -ne 0 ]]; do [[ ! -d "faup" ]] && ${SUDO_CMD} git clone git://github.com/stricaud/faup.git faup; done
false; while [[ $? -ne 0 ]]; do [[ ! -d "gtcaca" ]] && ${SUDO_CMD} git clone git://github.com/stricaud/gtcaca.git gtcaca; done
```
For some reason, I've had errors in my installation related to the cloning of this repos: 
```
Cloning into 'faup'...
fatal: unable to connect to github.com:
```
In order to finish MISP install with no errors I've had to do the following:
```
cd /tmp
git clone https://github.com/stricaud/faup.git faup
git clone https://github.com/stricaud/gtcaca.git gtcaca
```

Then, I was able to install MISP without errors and fatals from git.

**Comment by SteveClement** [comment]
done, since a while ;)
