### ISSUE TITLE
Export CSV & Text including non IDS flagged attributes

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#668]
Exports in CSV & Text formats are including non IDS flagged attributes even though the "Include non-IDS marked attributes" checkbox is not ticked.

**Comment by iglocska** [comment]
Is this on the latest version? This was a bug that was fixed last week.

**Comment by iglocska** [comment]
Oh course if the silly developer doesn't push the fix upstream, you might not have it fixed on your end. Please git pull when you can :)

**Comment by adulau** [comment]
The operator of some MISP platforms merged the fixes. Thank you for the quick fixes.

**Comment by iglocska** [comment]
Thank you! :)
