### ISSUE TITLE
Issue with GPG encryption/validation

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#6681]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 7.2
| MISP version / git hash   | 2.4.135

### Expected behavior
gpg version 2.0.22 which is the latest version available on EPEL should be sufficient to handle all MISP gpg operations

### Actual behavior
I've noticed, thanks to https://github.com/JakubOnderka/MISP/commit/54efe760a4b9d5bd3dc71ab726a442f246f87fca#diff-81373a799b15293925278e6f33f8bef5dce9de4c5d7da68659dec981ef58659b that some functions rely on parameters available as of gpg version 2.1.23 such as the "show-only" import option. Therefore no output is fetched and the validation of the key fails despite a valid key.

After "fixing" this one, running the Admin tool to check in batch all the gpg keys gives me errors for all of them saying that no subkey can be used for encryption(but only to sign). Any idea what that can be? I guess it can also be related to the first issue.

### Steps to reproduce the behavior

Install MISP 2.4.135 on RHEL 7 with gpg from the EPEL repo.
Try to add a GPG key to a user

**Comment by JakubOnderka** [comment]
Should be fixed by https://github.com/MISP/MISP/pull/6697. Can you please test it with that patch applied and reopen if it didn't help?

**Comment by lfortemps** [comment]
Thanks a lot @JakubOnderka , issue is indeed fixed now.
