### ISSUE TITLE
Scheduled Tasks

### ISSUE THREAD

**Issue by DashCarlos** [MISP/MISP#6683]
I have tried adding a scheduled task for automatic update of the feeds, but the changes have no effect after pressing "update all", any ideas? Thank you 
![imagen_2020-12-03_135409](https://user-images.githubusercontent.com/31094207/101020575-049d6d00-356f-11eb-896f-06a5293a2954.png)

**Comment by mokaddem** [comment]
Hey @DashCarlos,
Schedule tasks are deprecated. Please use CRON jobs instead.
More information can be found in the link of the red sentence in the screenshot you posted.
Thanks

**Comment by DashCarlos** [comment]
> Hey @DashCarlos,
> Schedule tasks are deprecated. Please use CRON jobs instead.
> More information can be found in the link of the red sentence in the screenshot you posted.
> Thanks

I have tried doing this and it has been running for several days but it has not worked

![image](https://user-images.githubusercontent.com/31094207/101155281-2eb26600-3627-11eb-925b-094c3a0ccd83.png)
