### ISSUE TITLE
Post Requests to Search Attribute

### ISSUE THREAD

**Issue by amemkdm** [MISP/MISP#6684]
### Test Environemnt

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             |  REST API taking too long a time to respond
| OS version (server)       | Ubuntu
| OS version (client)       | Windows
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.132, hash of the commit

### Support Questions
Trying to get attributes from my MISP instance using the rest api but I keep getting errors saying maximum response size reached by using a rest client such as postman and if I use the built in rest client the web page just crashes after some time if I limit the result to 100 its fine but I want to pull all the attributes from my instance to ingest into Elasticsearch.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/20220580/101023005-2bbc6480-3598-11eb-97c6-4738edee01c2.png)

**Comment by mokaddem** [comment]
You diagnosed the problem correctly. You are trying to fetch too much data at the same time.
The best would be to paginate over the data and feed Elasticsearch with small batches.
You can paginate using the standard SQL pagination parameter
```json
{
    "page": 1,
    "limit": 1000
}
```

The response will include a result header that can be used to know when there is nothing else to fetch.
