### ISSUE TITLE
MISP Installed, access here: "" - No access to MISP after install..

### ISSUE THREAD

**Issue by mikecybersec** [MISP/MISP#6685]
I'm installing MISP core on Ubuntu 18.04 using the commands:

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

MISP Installed, access here: ""

As you can see, the above is blank. When I try browsing to Localhost 8443 or 8080, I've tried both, I get nothing.

Can you please advise? It's a brand new Ubuntu box.

**Comment by DashCarlos** [comment]
Can you show the content of the following file? /var/log/apache2/misp.local_error.log
