### ISSUE TITLE
Extend object controller delete method to accept $hard parameter from REST POST request

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6689]
The object controller's delete method supports hard delete via parameter $hard. The PyMISP team recently extended their client to pass the hard-delete parameter for removing an object, please see https://github.com/MISP/PyMISP/issues/666  

However, the controller method does not read this parameter from a POST request.  For that to happen I think the following code is needed, which I copied from the delete_attribute method in the same controller:
```
        if (isset($this->params['named']['hard'])) {
            $hard = $this->params['named']['hard'];
        }
        if (isset($this->request->data['hard'])) {
            $hard = $this->request->data['hard'];
        }
```
Thanks in advance.

**Comment by chrisinmtown** [comment]
I propose this change, please consider it, hope you all can find time for this.  I am not at all certain how to contribute the test case, sorry:
```
index a61a41f..d5c7fc1 100644
--- a/app/Controller/ObjectsController.php
+++ b/app/Controller/ObjectsController.php
@@ -787,6 +787,12 @@ class ObjectsController extends AppController
         if (!$this->userRole['perm_modify']) {
             throw new ForbiddenException(__('You don\'t have permissions to delete objects.'));
         }
+        if (isset($this->params['named']['hard'])) {
+            $hard = $this->params['named']['hard'];
+        }
+        if (isset($this->request->data['hard'])) {
+            $hard = $this->request->data['hard'];
+        }
         $object = $this->MispObject->find('first', array(
             'recursive' => -1,
             'fields' => array('Object.id', 'Object.event_id', 'Event.id', 'Event.uuid', 'Event.orgc_id', 'Event.us
```

**Comment by chrisinmtown** [comment]
happy new year, I hope someone will please find a minute to look at my proposed change to implement the extension, thanks in advance.

**Comment by mokaddem** [comment]
Hey
Thanks! It's done

**Comment by chrisinmtown** [comment]
Thanks for accepting (a revised version of :) my proposal but .. this still needs an automated test case.
