### ISSUE TITLE
API to get the MISP statistics

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#670]
It would be interesting to get the MISP statistics of an intance via the API: 

https://<MISP>/users/statistics

This can be also used for monitoring MISP instance.

**Comment by iglocska** [comment]
Sounds like a good idea, will keep it in mind!

**Comment by adulau** [comment]
Recently implemented in 2.4.63:

- https://<instance>/users/statistics/tags.json
- https://<instance>/users/statistics.json
- https://<instance>/users/statistics/attributehistogram.json
- https://<instance>/users/statistics/orgs.json

Thanks to @iglocska for the quick and late implementation while watching German TV shows.

**Comment by iglocska** [comment]
Watching US TV shows in German is truly an inspiration to just get some
work done instead.

**Comment by cristianbell** [comment]
ah, ok.. was wondering what German TV show u were watching.. :)
