### ISSUE TITLE
Edit user roles gets blackholed

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#6704]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.135, c3c79b31d7901c9ff4f258f8043f7b3d5c0bbb84

Hi,
recently I can't edit our user roles anymore. I can still create new roles, but changing existing ones is not possible anymore.

### Expected behavior
User roles can be edited

### Actual behavior
When trying to edit a user role, the request gets blackholed. That happens on all our MISPs.

### Steps to reproduce the behavior
Got to Administration --> List Roles --> select edit for a user of your choice --> check a random checkbox --> click edit

### Logs, screenshots, configuration dump, ...
![edit role](https://user-images.githubusercontent.com/31033198/101344171-5d2d7c80-3885-11eb-9415-3625ea6ba2bb.png)

**Comment by JakubOnderka** [comment]
Hello, the reason is double `//` in URL. Fixed in https://github.com/MISP/MISP/pull/6706
