### ISSUE TITLE
Delete an event through the API returns... a lot of stuff

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#671]
I'm not completely sure what the object returned is, but it is huge, and should probably not :)

**Comment by iglocska** [comment]
I think it might return the index simply (incorrectly), I'll have a look!

**Comment by elhoim** [comment]
Fixed in https://github.com/MISP/MISP/commit/4a16fb3941140d7422895b645cb2754bd1ffa616
Closing.
