### ISSUE TITLE
Database schema diagnostics produces false positives because of different column default.

### ISSUE THREAD

**Issue by begunrom** [MISP/MISP#6712]
After an upgrade from Ubuntu 18.04 LTS to 20.04 LTS, the Mysql version is updated and there are now warnings in Schema status/Database schema diagnostic: 

### Expected behavior
It is very clumsy that there are many warnings that are false positives.
I can see 2 types of warnings
1) column_default = NULL, while an empty value is expected
![image](https://user-images.githubusercontent.com/420528/101619304-62203680-3a13-11eb-85b5-feb707ce06af.png)
2) column_default = '' or 'misp' (string enclosed by quotes) , while an empty value is expected
![image](https://user-images.githubusercontent.com/420528/101619692-e672b980-3a13-11eb-9d21-e2c92fd3ee92.png)

In my case it generates  200 warnings. I will never see a real database problem.

### Actual behavior
Idealy only real warnings to be shown

### Steps to reproduce the behavior
original DB version : Server version: 10.1.47-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
Current DB version : Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

**Comment by mokaddem** [comment]
@begunrom I believe you saw these entries by checking the `Debug mode: Reveal benign deltas` button.
If this is the case, feel free to ignore these.
