### ISSUE TITLE
It's possible to delete a role that's assigned to a user

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#6713]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.135
| Browser                   | If applicable

### Expected behavior

Receive an alert / made impossible when deleting a role that is assigned to a user.

### Actual behavior

Roles can be deleted, even if they are assigned to a user.

**Comment by JakubOnderka** [comment]
Fixed in https://github.com/MISP/MISP/pull/6788, thanks for report.
