### ISSUE TITLE
After delete of object template, web UI shows deleted AND could not be deleted notifications

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6718]
We are using MISP version 2.4.133.  I'm working with object templates and had to delete one.  The resulting screen is confusing, it shows a pale green notification box at the top "ObjectTemplate deleted" and immediately below that, a pale pink notification box "ObjectTemplate could not be deleted".  Upon refresh of the screen both vanish, and the object template truly is gone, so I think the pale green one is correct and the pale pink one is an imposter :) 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133
| Browser                   | Firefox 83.0

### Expected behavior

Only see one notification, either that the delete worked or that the delete failed.

### Actual behavior

See two notifications.

### Steps to reproduce the behavior

From the Global Actions menu, pick object templates, select one, click the trash-can icon on the right, and confirm the delete.

### Logs, screenshots, configuration dump, ...

<img width="932" alt="Screen Shot 2020-12-09 at 11 11 06 AM" src="https://user-images.githubusercontent.com/10234212/101655791-02745c00-3a10-11eb-8f22-789ae7d630da.png">

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in develop branch.

**Comment by chrisinmtown** [comment]
Thanks for the quick action.  This was only open a few hours?  How do I get that same treatment for my other issues? :)
