### ISSUE TITLE
Download hung up at 'Composer installation successfully created'

### ISSUE THREAD

**Issue by Crusherton** [MISP/MISP#6726]
I have tried a few times on a few different ubuntu 18.04 desktop iso's to install MISP. However, each one of the install gets hung up at Composer installation successfully completed. I have waited multiple hours but no luck.

For reference i am using this guide to install: https://www.techrepublic.com/article/how-to-install-malware-information-sharing-platform-on-ubuntu-server-18-04/

Any idea how to get pass this would be much appreciated. 

![image](https://user-images.githubusercontent.com/44026944/101683464-f51c9900-3a32-11eb-9182-09e2598f98a0.png)

**Comment by SteveClement** [comment]
Dear

We do not support 3rd party install guides.

Our own are rather complete, please use them.

Also, we have an installer.

**Comment by ooffiirr** [comment]
This installer does not show the rest if the progress and is updating only at the end that the installation is finished,
You should wait for almost 2 hours for this kind of install to be finished.
