### ISSUE TITLE
disable_correlation with POST

### ISSUE THREAD

**Issue by kedrole** [MISP/MISP#6731]
Hello!
I want to add event with POST /events. How can i add "disable_correlation = True" param to attribute?

**Comment by mokaddem** [comment]
Hi,
You can disable the correlation for a specific attribute by passing the `disable_correlation` flag set to false.
i.e.:
```json
{
    "type": "comment",
    "category": "Other",
    "to_ids": false,
    "disable_correlation": false,
    "value": "csa"
}
```
