### ISSUE TITLE
Inconsistencies in the messages returned by the API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#674]
Every time there is a key 'message' in the object returned by the API, it is an error message, except in the upload API: it will contain "Success, saved all attributes." if everything went well.

Would be nice to make everything more consistent in the future (maybe not for 2.4)

Proposal: using the same keys as viper: 
* "error"
* "warning"
* "info"
* "success"

**Comment by iglocska** [comment]
This would indeed be something for a later version as it requires some serious reworking. 

Right now message is used in any API action that doesn't return record(s), both for errors or for successful actions. The best way to check whether something was successful right now is simply checking the HTTP response code.

**Comment by Rafiot** [comment]
hmmm, ok, I'll use it then. Probably the best way to do it then.

**Comment by iglocska** [comment]
That would be best, the message part is set automatically when an exception
is raised. The way it works now internally, if MISP throws an exception for
an unauthorised action, it will do the following:

1. return code 403
2. depending on the content type, either render the error page with a set
message, or use the same message in an XML / JSON object.

On success, it should:

1. return code 200
2. either return a message or return the requested object in the
appropriate format

**Comment by Rafiot** [comment]
excellent. handling it that way in the API then :)

**Comment by iglocska** [comment]
It may be inconsistent in some places though - if you run into any of that
let me know!

**Comment by Rafiot** [comment]
will do :)
