### ISSUE TITLE
Log addition and removal to event blacklist by UUIDs

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#675]
Please also log the user name so that it is possible to identify who added or removed an entry to the blacklist.

**Comment by elhoim** [comment]
Seems to be there now but in the description field not the change field, but the description field is not displayed.
Email of the user is also part of the log, so this is sufficient for my intended purpose.

**Comment by cristianbell** [comment]
Yep when looking with @elhoim at this we saw that `EventBlacklist (event_blacklist.id) added by User "users.email" (users.id).` is logged in the description field of the log table. But the description field is not displayed in the UI. Why is that?
