### ISSUE TITLE
"Import from URL" functionality is unavailable under Event Reports

### ISSUE THREAD

**Issue by r0ny123** [MISP/MISP#6751]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu 20.4
| OS version (client)       | Ubuntu 20.4
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.135, https://github.com/MISP/MISP/commit/d25025d664452dfbb35fe8234d6ccf8cf6d262e1

### Expected behavior
`Import from URL` should be available as mentioned [here](https://www.misp-project.org/assets/images/misp/blog/event-report-demo-extraction-from-url2.mp4).

### Actual behavior
`Import from URL` is not viewable as can be seen in the following screenshot (MISP modules are enabled).

![image](https://user-images.githubusercontent.com/49360849/102020353-c25e0200-3d9e-11eb-9ee5-4eb6a818a6b1.png)

**Comment by adulau** [comment]
You need to enable the misp-modules and have the html2markdown module enabled.

**Comment by r0ny123** [comment]
Ah, thanks, can see it now.
