### ISSUE TITLE
Database schema diagnostic: Proposed SQL Statement Syntax Error

### ISSUE THREAD

**Issue by Daniel-CS-Team** [MISP/MISP#6762]
The database schema diagnostic on our instance proposes some columns to be added:
![Bildschirmfoto 2020-12-16 um 14 50 18](https://user-images.githubusercontent.com/66005732/102357049-3ae6dd80-3fae-11eb-9cc5-e3750f88a71d.png)
The proposed SQL statement ist:
`ALTER TABLE `logs` ADD COLUMN `ip` varchar(45) UNSIGNED DEFAULT "" NOT NULL COLLATE utf8_bin ;`
However, if I paste this into the mysql console the following error is shown:
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNSIGNED DEFAULT "" NOT NULL COLLATE utf8_bin' at line 1`

Versions in use:
MySQL:
`Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04`
MISP:
`Currently installed version… v2.4.136 (06bbde71418bd0c279f3252e5227be5f33b1efb2)`

**Comment by mokaddem** [comment]
Thanks for the report!
