### ISSUE TITLE
Event Report - Allow scope for attributes in extended events

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#6766]
**Describe the solution you'd like**
Actually, I can`t add on event reports, an attribute from an extended event, as it returns invalid scope error

**Additional context**
A practice of mine is to create a main event for investigation I`m doing and extend the original event when I have separate campaigns.
Usually, the reports stay on the main event, where I would point correlations between campaigns and write related attributes.

**Comment by mokaddem** [comment]
Hey,
I fixed a bug that could be related to your issue (in af482e7eaf617bce40ba9775e41e2cc2c54b7d69).
If the fix doesn't work for you, here are the step I took and are working as intended:
- Create an event `A`
- Create an event `B` extended `A`
- Create an attribute in event `A` and another in event `B`
- Create an event report `X` in event `B`
- Event report `X` has access to all attributes in both event `A` and `B`

Please come back to us if you expected something different or if it doesn't work.
Thanks!
