### ISSUE TITLE
Inconsistent changelogs

### ISSUE THREAD

**Issue by sustefil** [MISP/MISP#6769]
Hi there :)

We are using this changelog to track the changes and for automatic notifications, but it's not updated (only 134 version there):

https://www.misp-project.org/Changelog.txt

Whereas here it's updated (version 136):

https://misp.github.io/MISP/Changelog/

Which changelog is "more official" then? :) 

Thanks

**Comment by chrisinmtown** [comment]
+1 from me on the request to be consistent and timely.

If I were guessing, I'd say that MISP/Changelog only applies to core MISP features like the server, but excludes changes to PyMISP, misp-modules etc.  The misp-project Changelog.txt should cover everything.  It's pretty frustrating that the project-level file is so out of date.

**Comment by hlijan** [comment]
Hello,

It seems that the Changelog is broken for the 2.4.153 version of MISP again: https://raw.githubusercontent.com/MISP/MISP/2.4/docs/Changelog.md 

The linked Changelog from [Releases page](https://github.com/MISP/MISP/releases) is outdated completely: https://www.misp-project.org/Changelog.txt 

Many thanks for any update on this one, as we are using it for change analyzis etc.

**Comment by adulau** [comment]
We moved the website recently and that was indeed an issue. It should be updated and inline with the recent release: 

https://www.misp-project.org/Changelog.txt 

the docs directory should be also inline with the official release.

Thanks a lot for the notification.

**Comment by hlijan** [comment]
Ok, many thanks. Just to mention that the link you provided is also not updated.

The only updated I found is this one: https://raw.githubusercontent.com/MISP/MISP/2.4/docs/Changelog.md
