### ISSUE TITLE
ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting'

### ISSUE THREAD

**Issue by jloehel** [MISP/MISP#6773]
Stack Trace:
```
2020-12-18 05:05:28 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/view/335
Stack Trace:
#0 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Sightin...', Array)
#2 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Sightin...', Array, Array)
#3 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Sightin...', Array)
#4 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Sighting), Array)
#5 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP-2.4.136/app/Model/Sighting.php(331): Model->find('all', Array)
#7 /var/www/MISP-2.4.136/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings(Array, Array)
#8 /var/www/MISP-2.4.136/app/Controller/EventsController.php(1436): Sighting->eventsStatistic(Array, Array)
#9 /var/www/MISP-2.4.136/app/Controller/EventsController.php(1655): EventsController->__viewUI(Array, false, NULL)
#10 [internal function]: EventsController->view('335')
#11 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP-2.4.136/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP-2.4.136/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
```

https://github.com/MISP/MISP/blob/9d537c989a1a9ff7de75bf5b4a0e1d72a92304a2/app/Model/Sighting.php#L335

I guess this is a leftover of a previous change and it should be now `date` instead of `date_sighting`.

**Comment by torsolaso** [comment]
Same error here when updated from 135 to 136 version.

`2020-12-21 13:47:33 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/view/14677
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find()
#7 /var/www/MISP/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings()
#8 /var/www/MISP/app/Controller/EventsController.php(1436): Sighting->eventsStatistic()
#9 /var/www/MISP/app/Controller/EventsController.php(1655): EventsController->__viewUI()
#10 [internal function]: EventsController->view()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#15 {main}
`

**Comment by JakubOnderka** [comment]
Sorry for problems, it should be fixed now in `develop` branch. 

Please reopen if it still doesn't work.

**Comment by torsolaso** [comment]
Hi JaKub,

I upgrade version and i am getting same error.

**Comment by jloehel** [comment]
> Sorry for problems, it should be fixed now in `develop` branch.
> 
> Please reopen if it still doesn't work.

Thanks. I patched it locally. It works fine with the change. When will you release again?
