### ISSUE TITLE
FAIL: bad GnuPG.*

### ISSUE THREAD

**Issue by ricardo-dias** [MISP/MISP#678]
Hello all,

I'm having trouble configuring GnuPG MIPS on a CentOS 7.0 (x64). I've followed the CentOS7 install guide, but when running diagnostics I get the following GnuPG error:
FAIL: bad GnuPG.*

I did a quick search and found the issue could be related with permissions, but in my case the .gnupg is already owned by 'apache':
drwx------.  2 apache apache    6 Sep 26 15:10 private-keys-v1.d
-rw-------.  1 apache apache 1184 Sep 26 15:11 pubring.gpg
-rw-------.  1 apache apache 1184 Sep 26 15:11 pubring.gpg~
-rw-------.  1 apache apache  600 Sep 26 15:11 random_seed
-rw-------.  1 apache apache 2562 Sep 26 15:11 secring.gpg
-rw-------.  1 apache apache 1280 Sep 26 15:11 trustdb.gpg

I've also checked the config.php and all settings seem fine: email, password and path.
Can anyone give me a hint?

Thanks in advance!
RD

**Comment by adulau** [comment]
Hi Ricardo,

Which version of GnuPG do you use?

**Comment by ricardo-dias** [comment]
I'm using GnuPG 2.0.22 with libgcrypt 1.5.3.

**Comment by iglocska** [comment]
Are you using a passphrase by any chance?

**Comment by ricardo-dias** [comment]
I was at the beginning but now is an empty one, the GnuPG section in config.php is as follows:
<snip>
  array (
    'onlyencrypted' => false,
    'email' => 'admin@misp.local',
    'homedir' => '/var/www/MISP/.gnupg',
    'password' => '',
    'bodyonlyencrypted' => false,
  ),
</snip>

**Comment by ricardo-dias** [comment]
Ok, I've just finished setting up MISP on Ubuntu and everything runs out of the box. Ubuntu GnuPG is  1.4.16, so eventually CentOS gpg might be the problem. Going to try later on as I *really* need to stick with CentOS.

**Comment by iglocska** [comment]
Could you try to install CryptGPG 1.4.0b4 beta?

pear install Crypt_GPG-1.4.0b4

This might fix it for you. Let me know if it does!

**Comment by ricardo-dias** [comment]
I've installed Crypt_GPG-1.4.0b4 but still no luck. Also installed GnuPG 1.4.19, modified the binary path setting in config.php, but the issue remains.

**Comment by jigsawsecurity** [comment]
We had the same issue until we started a GPG listener for that home directory. 
Try running the following:

gpg-agent --homedir=/var/www/MISP/.gnupg --daemon &

That will start a socket which is required to pass the credentials to GPG to actually accept a passphrase.

**Comment by ricardo-dias** [comment]
Yeah we did that too in order to finish the pgp section of the install.

We opted to move on and rebuild the server with Ubuntu.
