### ISSUE TITLE
Import feeds does not save the headers defined in the feed json

### ISSUE THREAD

**Issue by dionita-bd** [MISP/MISP#6780]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | Win10, Ubuntu
| MISP version / git hash   | MISP 2.4.135 

### Expected behavior

When importing a json feed I want all the fields to be saved.

### Actual behavior

The headers field is not saved.

### Steps to reproduce the behavior

Import any feed that contains a "headers" definition.

### Logs, screenshots, configuration dump, ...

The patch would require a small change in app/Model/Feed.php, in function importFeeds:

                if (!$this->save($feed, true, array('name', 'provider', 'url', 'rules', 'source_format', 'fixed_event', 'delta_merge', 'override_ids', 'publish', 'settings', 'tag_id', 'default', 'lookup_visible'))) {

'headers' is not present in the list of fields to save. After adding 'headers' the fields are saved as expected.

**Comment by dionita-bd** [comment]
Anything I can do to speed this up? I'd push the changes into develop, but I don't have write access. We need this for a project we're working on at my company. Thanks!

**Comment by iglocska** [comment]
Should be fixed, thanks for the report and providing the fix!
