### ISSUE TITLE
'-' is not allowed in the domain for the base URL

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#6784]
Hello,

With the actual regex in app/Model/Server.php, we are not allowed to have a '-' inside the BaseURL. I did a quick fix in ordel to allow it. https://github.com/MISP/MISP/pull/6783

Best regards

**Comment by adulau** [comment]
Fixed in fb7c98ebcf24bfa52e1b7179b6a86764e5b5034a
