### ISSUE TITLE
Error during MISP module upgrade 

### ISSUE THREAD

**Issue by Airborne1974** [MISP/MISP#6796]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS7
| MISP version / git hash   | 2.4.136

### Support Questions
During upgrade procedure to latest version 2.4.136, I also did MISP module upgrade but error occurred during execution of command:
sudo -u apache /var/www/MISP/venv/bin/pip install -I -U -r REQUIREMENTS

Please help me get back to the track and upgrade properly.

EDIT: Same error output happens on 3 different MISP instances.

### Logs, screenshots, configuration dump, ...

Collecting importlib; python_version <= "3.7"
  Downloading importlib-1.0.4.zip (7.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/www/MISP/venv/bin/python3 -c 'import sys, setuptools, tokeniz      e; sys.argv[0] = '"'"'/tmp/pip-install-840qzr8k/importlib/setup.py'"'"'; __file_      _='"'"'/tmp/pip-install-840qzr8k/importlib/setup.py'"'"';f=getattr(tokenize, '"'      "'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"')      ;f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /t      mp/pip-pip-egg-info-kgnnmhv4
         cwd: /tmp/pip-install-840qzr8k/importlib/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/MISP/venv/lib/python3.6/site-packages/setuptools/__init__.p      y", line 10, in <module>
        import distutils.core
      File "/var/www/MISP/venv/lib64/python3.6/distutils/__init__.py", line 4, i      n <module>
        import imp
      File "/var/www/MISP/venv/lib64/python3.6/imp.py", line 19, in <module>
        from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_n      ame
    ModuleNotFoundError: No module named 'importlib._bootstrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th      e logs for full command output.

**Comment by adulau** [comment]
Can you git pull the latest version of the misp-modules?

**Comment by Airborne1974** [comment]
Just did it and same error.

**Comment by Airborne1974** [comment]
Fixed with next versions.
