### ISSUE TITLE
Error during MISP update

### ISSUE THREAD

**Issue by roberto-carlos-leonardo** [MISP/MISP#6798]
### Work environment

| Questions                      | Answers
|----------------------------------------------|
| Type of issue                 | Support
| OS version (server)        |CentOS 7
| OS version (client)         |Win10
| PHP version                   | 7.2.24 
| MISP version / git hash | 2.4.129
| Browser                         | Microsoft Edge 87.0.664.66

### Support Questions

During the update procedure to version 2.4.136, we received "error loading shared libraries: libcurl-httpd24.so.4"

Has anyone had this problem?
Please can you help me with this error?

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/36730270/103007579-6ae43280-4512-11eb-9696-08166208dfc7.png)
![image](https://user-images.githubusercontent.com/36730270/103007606-79324e80-4512-11eb-9d28-538d5729d0af.png)
![image](https://user-images.githubusercontent.com/36730270/103007623-80f1f300-4512-11eb-9cab-6ed4da070575.png)

**Comment by adulau** [comment]
It sounds like a RedHat issue potential solution described here: https://bugzilla.redhat.com/show_bug.cgi?id=1785720#c5

I'll close the issue. Feel free to reopen if required. Thank you.
