### ISSUE TITLE
MISP An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by IrArTr** [MISP/MISP#6802]
Hello everyone, I'm new using MISP and I have a problem, when I want to  view an event created and the same when I create a tag and want to see the list of tags I get the following error:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

I am using MISP in a docker container and it is this: https://github.com/MISP/misp-docker

someone could please help me

**Comment by achillesheald** [comment]
Also experiencing this error. 

Testing out a MISP instance and have enabled/cached the CIRCL feed. Attempting to view any event yields the internal error described above, as does attempting to import STIXv1.
