### ISSUE TITLE
What is the ideal page size limit (value of "limit" parameter) for attributes' restSearch API endpoint?

### ISSUE THREAD

**Issue by jigneshpatel2208** [MISP/MISP#6805]
My use case is to pull the MISP attributes periodically and I'm using "/attributes/restSearch" endpoint with required query parameters. I am using "limit" as 10,000, which is 10,000 attributes per page. But while pulling, occasionally, I get following errors:

`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

or even sometimes I get an invalid JSON response, which results in the following error while converting into JSON in my script:

`JSONDecodeError('Unterminated string starting at: line 1 column 110968826 (char 110968825)')`

So I think one possible reason might be the page size ("limit" parameter), which might be too large for MISP to handle the large amount of data every time properly.

If that's the reason, what should be the ideal value of the "limit" parameter? I couldn't find anything regarding this in API documentations. I set it some higher value like 10,000 to reduce the number of API calls so that the data retrieval becomes faster.

Note that I'm not using any library like PyMISP to interact with MISP APIs.

**Comment by mokaddem** [comment]
That's a tough question as it may vary from one instance to another. For examples, here is a non-exhaustive list of points that might affect the upper limit:
- Server hardware (CPU, SDD/HDD, memory, ...)
- Server configuration (max allowed PHP memory, ...)
- Type of data in the instance
    - Lots of connected (via correlation) elements
    - Highly contextualized data (taxonomies, galaxies)
    - Type of data (binary, small text, ...)
- ...

I would start from the bottom, let's say a limit of 1000 and periodically increase this number until you start encountering issues.
