### ISSUE TITLE
Being able to edit event report title after first publication

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#6808]
Being able to edit event report title after a report creation.

**Comment by mokaddem** [comment]
In order to change the name of the report or the distribution, you have to
- Edit an event report via the special edit view
- Click on the `Edit Event Report` button in the sidemenu. This will redirect the user to `eventReports/edit/[eventReportID]` and allow the edit of said fields

**Comment by adulau** [comment]
Ok I'll update the doc then ;-)
