### ISSUE TITLE
Problems in creating new whitelist

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#681]
Hi all,

When I try to create a new signature whitelist (domain, host, IP address) I get the following errors:

-Name not in the right format. Please double check the name.
-The whitelist could not be saved. Please, try again.
- Warning (2): preg_match(): Delimiter must not be alphanumeric or backslash [APP/Model/Whitelist.php, line 70] 
preg_match - [internal], line ??
Whitelist::validateValue() - APP/Model/Whitelist.php, line 70
CakeValidationRule::process() - APP/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationRule.php, line 275
CakeValidationSet::validate() - APP/Lib/cakephp/lib/Cake/Model/Validator/CakeValidationSet.php, line 135
ModelValidator::errors() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 268
ModelValidator::validates() - APP/Lib/cakephp/lib/Cake/Model/ModelValidator.php, line 99
Model::validates() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 3460
Model::_doSave() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1829
Model::save() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1751
AdminCrudComponent::adminAdd() - APP/Controller/Component/AdminCrudComponent.php, line 17
WhitelistsController::admin_add() - APP/Controller/WhitelistsController.php, line 37
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

Am I missing something here?

Thanks in advance,
Andreas

**Comment by iglocska** [comment]
Whitelist entries have to be enclosed by a valid php delimiter (which can
be most non-alphanumeric / non-whitespace character).

Basically instead of putting "8.8.8.8" into the field, just use "/8.8.8.8/".

**Comment by iglocska** [comment]
I'll add a note about this to the view so it's more obvious as right now
it's not shown anywhere.

**Comment by advancedeng** [comment]
What can I say... Thanks again :)

**Comment by jaegeral** [comment]
It is even not shown right in the documentation:

https://www.circl.lu/doc/misp/administration/index.html#managing-the-signature-whitelist

;-)

**Comment by Rafiot** [comment]
Fix merged.
