### ISSUE TITLE
Attribute Search in Event-View not working

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6814]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | v2.4.136 (f7d5bc272bd457e5f216b9c5aea19ccb30b492b3) 
| Browser                   | Firefox

### Expected behavior
Using the Search Form-Field above the list of attributes in event-view, i would expect the attribute list below gets filtered by a searchall filter.
Think this still was ok in 2.4.135

### Actual behavior
event view is left, and some weired eventReport search Url is opened. usually not giving any result for me.
for example: https://misp.tld/eventReports/index/event_id:10/index_for_event:1/searchall:searchterm

### Steps to reproduce the behavior
enter any event-view and search something via the field above the list of attributes on the right.

### Logs, screenshots, configuration dump, ...
![grafik](https://user-images.githubusercontent.com/72734273/103521358-e4681300-4e78-11eb-9199-ac951a2f5e10.png)

**Comment by JakubOnderka** [comment]
Already fixed in `develop` branch.
