### ISSUE TITLE
Download feed data from MISP

### ISSUE THREAD

**Issue by usedtire** [MISP/MISP#6819]
Is there a way using the API to download feeds that are currently in the MISP instance?  I see options to upload with different tools, but nothing to download all feeds.  It would be easy enough to download them individually from the sources, but I'd like a single source where I aggregate all feed sources.

**Comment by chrisinmtown** [comment]
What exactly are you asking? PyMISP offers method feeds() to get all the feed details from the server.  I am not aware of any API method to kick the server to download all feed DATA.
