### ISSUE TITLE
Export to csv based on Threat Level

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#682]
Hi all,

Is there an option for exporting the IoCs based on the Threat Level (just like category, tags, type, etc..)? 

Thanks in advance,
Andreas

**Comment by iglocska** [comment]
Good point, there isn't will look into adding this!

**Comment by advancedeng** [comment]
That's great! Thanks a lot!

**Comment by advancedeng** [comment]
A workaround exists though-> export using includeContext=true and then filter based on the threat level.

**Comment by adulau** [comment]
I suppose this issue has been resolved. If not, feel free to reopen the issue. Thank you.
