### ISSUE TITLE
How to automate MISP events in firewall

### ISSUE THREAD

**Issue by meghakumawat1** [MISP/MISP#6823]
I am learning MISP. Can you please let me know if there is any process to automate MISP events for example Once the IOCs are in MISP, automation will take care of publishing them to the security tools(IDS/SIEM).

**Comment by mokaddem** [comment]
Hi,
Please have a look at these resources:
- `/events/automation`
- `/servers/rest`
Using the API and particularly the REST Search endpoint (for attributes) might be interesting for you.
When you have IoCs in MISP, you can easily export them with the MISP API to your favorite tool.
