### ISSUE TITLE
Upgrade from 2.4.134 to 2.4.136 causes misp.Sighting.date_sighting SQL error

### ISSUE THREAD

**Issue by chrisnewmanuk** [MISP/MISP#6824]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  Ubuntu
| OS version (client)       |  Win10
| PHP version               | 7.4
| MISP version / git hash   | 2.4.136

Related to #6671 

### Expected behavior
Event and attributes are listed

### Actual behavior
Internal Server Error

### Steps to reproduce the behavior
Upgrade from 2.4.134 to 2.4.136, open an event of 1+ attributes and it returns internal server error with the log entry below 

### Logs, screenshots, configuration dump, ...

root@misp:/var/www/MISP/app/tmp/logs# tail error.log -f
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings(Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(1436): Sighting->eventsStatistic(Array, Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1655): EventsController->__viewUI(Array, false, NULL)
#10 [internal function]: EventsController->view('10315')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2021-01-06 11:55:40 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/view/10314
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Sightin...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Sightin...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Sightin...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Sighting), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings(Array, Array)
#8 /var/www/MISP/app/Controller/EventsController.php(1436): Sighting->eventsStatistic(Array, Array)
#9 /var/www/MISP/app/Controller/EventsController.php(1655): EventsController->__viewUI(Array, false, NULL)
#10 [internal function]: EventsController->view('10314')
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

![image](https://user-images.githubusercontent.com/7243321/103887621-43c55d80-50db-11eb-94d1-60c5c72369a3.png)

**Comment by chrisnewmanuk** [comment]
This is the SQL statement I believe could be related to the issue

![image](https://user-images.githubusercontent.com/7243321/103889504-71f86c80-50de-11eb-8b51-aadc9d16ff18.png)

GROUPBY is missing date_sighting ?

**Comment by chrisnewmanuk** [comment]
![image](https://user-images.githubusercontent.com/7243321/103891826-69099a00-50e2-11eb-9e03-df03320cd8c5.png)

**Comment by Stefan249** [comment]
Got the same issue

**Comment by passuf** [comment]
Had the same issue, I manually fixed the corresponding line in `/var/www/MISP/app/Model/Sighting.php` but there seemed to be similar problems in different files.

Reverted to 2.4.135 and things work again as expected.

**Comment by Sp-TT** [comment]
Having the same issue, and notice failed to pull attributes with sightings

**Comment by JakubOnderka** [comment]
Fixed, thanks for report.
