### ISSUE TITLE
Outlook reports invalid S/MIME-Signature

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6829]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | v2.4.136 (9d537c989a1a9ff7de75bf5b4a0e1d72a92304a2)
| Browser                   | ---

### Expected behavior
Received S/MIME mail would be shown as properly signed by MISP, after decryption.

### Actual behavior
Outlook will not open the E-Mail unless explicitly told. It claims the content of the message might have changed, or the signature is invalid. However all certificates have been totally fine, and trusted.

### Steps to reproduce the behavior
Setup S/MIME public-key and signing private-key, as well as users public encryption-key.
Try to send an email to this user via 'Contact Users'
check your Outlook mailbox

### Suggestion for a fix
I already did some research on this topic, and found a possible fix. 
If the Signature would be generated with PKCS7_DETACHED-Flag Outlook will accept it and report a properly signed message.
There were only two minor modifications needed to make it work. See them in this `git diff `:
```
diff --git a/app/Lib/Tools/SendEmail.php b/app/Lib/Tools/SendEmail.php
index 0779feae4..4c90cdaf4 100644
--- a/app/Lib/Tools/SendEmail.php
+++ b/app/Lib/Tools/SendEmail.php
@@ -727,14 +727,14 @@ class SendEmail
         }

         list($inputFile, $outputFile) = $this->createInputOutputFiles($body);
-        $result = openssl_pkcs7_sign($inputFile->pwd(), $outputFile->pwd(), $certPublicSign, $keySign, array(), 0);
+        $result = openssl_pkcs7_sign($inputFile->pwd(), $outputFile->pwd(), $certPublicSign, $keySign, array(), PKCS7_DETACHED);
         $inputFile->delete();

         if ($result) {
             $data = $outputFile->read();
             $outputFile->delete();
             $parts = explode("\n\n", $data);
-            return $parts[1] . "\n";
+            return $parts[4] . "\n";

         } else {
             $outputFile->delete();
```

**Comment by adulau** [comment]
Thanks a lot. That's indeed a good point (we don't use that much S/MIME) so having feedback from actual users, it's great.

@JakubOnderka @iglocska ok with you if I do the update?

**Comment by marjatech** [comment]
Any Update on this?

**Comment by marjatech** [comment]
Still waiting for this 😞 
Since I already did a PR, can someone merge this, please?

**Comment by iglocska** [comment]
Apologies, it's merged into the develop branch as of now, it will be included in the next release. Thanks for the fix!
