### ISSUE TITLE
Calendar not displayed correctly

### ISSUE THREAD

**Issue by pszemekd** [MISP/MISP#683]
During creation of new event (Add New Event) it is mandatory to filled in Date field. If field is clicked calendar is displayed, but about top 20% of the calendar is hidden.
MISP version 2.3.135
Checked with IE9, IE11, Edge, Firefox.
![missing calendar ff](https://cloud.githubusercontent.com/assets/12171981/10387196/adb56064-6e5f-11e5-88d7-9d6a8b799738.png)

**Comment by iglocska** [comment]
The issue was fixed in 2.3.135, if you run into this issue just ctrl+f5 to refresh the javascript files. I'll start versioning them whenever they get changed to avoid this in the future.
