### ISSUE TITLE
MISP Warnings after upgrade

### ISSUE THREAD

**Issue by muralivenkataraman** [MISP/MISP#6832]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Database schema diagnostic as indicated in subject line
| OS version (server)       | CentOS.
| MISP version / git hash   | 2.4.136, hash of the commit
| Browser                   | If applicable

### Support Questions
I updated MISP to the latest version and I am seeing the following warning messages when I login.

a) Warning The MISP database state does not match the expected schema. Resolving these issues is recommended.
b) Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live). An update might also be in progress, you can see the progress in Update Progress

### Logs, screenshots, configuration dump, ...
Checked the permissions on config.php file and it's at 750 and apache is the owner.

Thanks
Murali

**Comment by muralivenkataraman** [comment]
Hi there,

I see Server Settings and Maintenance option but do not have the ability to update them using the web interface.

Thanks
Murali

**Comment by muralivenkataraman** [comment]
Hi there,

I was able to change the setting for MISP.live from false to true (user error).  But I still need assistance with the warning messages.

Thanks
Murali

**Comment by muralivenkataraman** [comment]
Hi there,

I looked at this link - https://github.com/MISP/MISP/issues/5480.  It looks like the warning message can be safely ignored?

Thanks
Murali

**Comment by mokaddem** [comment]
That most probably means that your MISP instance is performing an update.
Please, wait for it to finish before undertaking manual steps.
Thanks
