### ISSUE TITLE
CakePHP 2.7 compatibility

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#684]
Since CakePHP 2.6 is no longer being maintained, will MISP switch to CakePHP 2.7 ? Some minor code tweaks are probably needed, like changing the use of String::uuid() and setFlash(), see
http://bakery.cakephp.org/2015/07/11/cakephp_2_7_0_released.html

**Comment by iglocska** [comment]
Yeah I saw the Sting::uuid() changes, I'll migrate it soon to 2.7.
