### ISSUE TITLE
How to import events from csv files

### ISSUE THREAD

**Issue by horialex** [MISP/MISP#6847]
Hello, I am using csv files as feeds, the csv has a lot of rows  each representing a certain event or a website that is attacked or compromised. I would like to import the csv into MISP but at the moment it only creates 1 big event with a lot of attributes column  is mapped to an attribute but not correctly.
How can I make misp create an event out of each row from the csv?

Also I have a column with the data of the event in the csv file but in MISP it imports it as an attribute and it's sees it as a phone number.

Thanks

**Comment by mokaddem** [comment]
Hi,
You probably want to use the MISP API for that kind of tasks: `/servers/rest`. There is also a python wrapper for MISP API: https://github.com/MISP/PyMISP
Cheers!

**Comment by horialex** [comment]
Thanks, also do you need to do something in particular to receive an email every time an event / attribute is created? or you just need to set your email address for the account
Thanks.

**Comment by mokaddem** [comment]
You can setup your profile in MISP to send emails to the associated email address whenever an event is published.
Just make sure you have the `Receive email alerts when events are published` flag turned on in your user profile.
