### ISSUE TITLE
Kali install script error

### ISSUE THREAD

**Issue by rusuvalentin** [MISP/MISP#6850]
Hello,

I am trying to install MISP on a Kali virtual machine from azure. 
I get the following error:

> Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/

Kali version:

> lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2019.2
Codename:       n/a

![image](https://user-images.githubusercontent.com/22794731/104316453-27635f80-54e5-11eb-8394-79feb5407992.png)

I've seen the same issue here https://github.com/MISP/MISP/issues/5545#issue-554372090, but it doesn't work for me. 
Thanks

**Comment by SteveClement** [comment]
I will try to fix this in the coming week.

**Comment by SteveClement** [comment]
This is now fixed, Kali 2019 is not supported, please use 2020.4

Fixed in #6952

**Comment by gilbert-beep** [comment]
Hi, I'm having the same problem using Kali 2021.3. Is it possible to get it working? Thank you.
