### ISSUE TITLE
stix2 to misp convert scripts - Missed observed-data parsing method

### ISSUE THREAD

**Issue by denny-lclin** [MISP/MISP#6855]
In MISP/app/files/scripts/stix2/stix2misp_mapping.py , the observed-data type to parse method map has a parse method  ```parse_ip_address_observable``` for type 'ipv4-addr'. However, there's no   ```parse_ip_address_observable```  in MISP/app/files/scripts/stix2/stix2misp.py, result in throwing exception.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 68596db5be2262ff2bb32e5832b63ce1576178b9
| Browser                   | If applicable

### Expected behavior
Import Stix2 without error 

### Actual behavior
Can't import stix2 with observed-data having only type 'ipv4-addr' objects

### Steps to reproduce the behavior
Import an stix2 file with observed-data having only type 'ipv4-addr' objects, i.e
{
      "created": "2021-01-12T12:00:14.495Z",
      "first_observed": "2021-01-12T12:00:14.495Z",
      "id": "observed-data--e395ba1d-3f29-47f2-b311-54d2b37fe245",
      "last_observed": "2021-01-12T12:00:14.495Z",
      "modified": "2021-01-12T12:00:14.495Z",
      "number_observed": 1,
      "objects": {
        "0": {
          "type": "ipv4-addr",
          "value": "1.2.3.4"
        }
      },
      "type": "observed-data"
}

**Comment by steves2020** [comment]
Hi,
I can confirm this is a bug in MISP 2.4.140. The mapping here:

https://github.com/MISP/MISP/blob/46a3772a60126d3d2c5b144ae1196ac99dcceba1/app/files/scripts/stix2/stix2misp_mapping.py#L137

Crashes during the lookup here 
https://github.com/MISP/MISP/blob/46a3772a60126d3d2c5b144ae1196ac99dcceba1/app/files/scripts/stix2/stix2misp.py#L1211

As it tries to call the function `parse_ip_address_observable` which is not implemented in `app/files/scripts/stix2/stix2misp.py`

```
sh-4.2$ grep "def parse" stix2misp.py | grep observable | grep ip
    def parse_domain_ip_observable(observable):
    def parse_ip_port_observable(self, observable):
    def parse_domain_ip_observable(self, observable):
    def parse_domain_ip_network_traffic_observable(self, observable):
    def parse_ip_network_traffic_observable(self, observable):
```

I've patched my local copy with this which fixes the problem but would rather it was fixed at source:

```
def parse_ip_address_observable(self, observable):
    self.add_attributes_from_observable(observable, 'ip-dst', 'value')
```

**Comment by chrisr3d** [comment]
I think 8e7a55d fixes the issue, but let me know if anything goes wrong and reopen if needed
