### ISSUE TITLE
Clarification of Licensing and IP in MISP

### ISSUE THREAD

**Issue by matthieu-farcot** [MISP/MISP#686]
Hi all

I crawled through the various licensing mentions in the MISP archive (as made available, my screening archive was downloaded on October the 10th 2015), and I have various issues/suggestions for improvement.

Summary(study done using fossology):

File Count  License Name
498             No License Found
43              MIT-style
25              Misc-Copyright
9               Apache_v2.0
4               MIT-possibility
3               Affero_v3
2               CCA-SA
1               Authorship-inference
1               ndemnity (Note: False Positive)
1               LikelyNot (Note: False Positive)
1               UnclassifiedLicense (Note: False Positive)

Issues (very brief summary):
- Licensing information: Although license for MISP main archive is clearly mentioned (Affero GNU GPL v3), licenses of third party components distributed in the archive are missing (example: bootstrap-timepicker.css, which is licensed under a MIT license missing in the main MISP archive).
  SOLUTION: (a) Identify ALL third party components (including version and download place information). Have a list kept up to date and include such list (including basic licensing information) in a README.TXT file at root of the MISP archive. (b) edit the LICENSE.TXT file at same level to reproduce not only the text of the Affero GNU GPL v3 but also all of the licenses of third parties components distributed within MISP.
- AUTHOR.TXT file is incomplete. SOLUTION: Please acknowledge accordingly all third party contributors.
- 2 files within this archive are licensed under a CC-BY-SA 3.0 license (misp-database-01.svg and misp-flows.svg, both available in  MISP-master/ INSTALL/ logos/ diagram/). Copyright holder is Alexandre Dulaunoy. SOLUTION: Alexandre, please double license your creations in order for them to be either single licensed under the Afero Gnu GPL v3 or dual licensed CC-BY-SA 3.0 and Affero GPL v3.

Finally, I would suggest the edition of headers on all files within the archive just resuming the fact that MISP is licensed under the Affero GNU GPL v3, and a short copyright mention.

**Comment by iglocska** [comment]
Thanks for the heads-up, will update them accordingly!

**Comment by adulau** [comment]
Thank you for the careful analysis, this is really appreciated. Regarding the header on all the files, I would go something really simple like "This file is part of the MISP project licensed under... ". 

For the contributors, we can generate the list from Git:

~~~
git shortlog -s | cut -c8-
Aaron Kaplan
AaronK
Alexander J
Alexandre Dulaunoy
Alexandru Ciobanu
Andras
Andras Iklody
Andrzej Dereszowski
Bâkır Emre
Charlie Root
Chris Clark
Christophe Vandeplas
David André
Guilherme Capilé
Gábor Molnár
Iglocska
Koen Van Impe
L. Aaron Kaplan
Noud de Brouwer
Raphaël Vinot
Richard van den Berg
deresz
git
iglocska
noud
nullprobe
remg427
root
~~~

We might need to review some "standard" Unix account.

**Comment by adulau** [comment]
This has been fixed.
