### ISSUE TITLE
Public MISP with OSINT

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#688]
There is no public MISP with OSINT information.

What we need is a server or VM with:
* 100 Mbit internet
* ubuntu OS with root access
* 4 GB of RAM
* 100 GB of disk

**Comment by aaronkaplan** [comment]
There is one at FIRST. The question is iff (!!) we should reduce its contents to OSINT and make it public. We could that if that's the wish of the community. 
Need to talk with our upstream misp provider. 

Anyway, I believe an org such as FIRST could be a good host for such a MISP instance. 


---
Mobile

**Comment by adulau** [comment]
@aaronkaplan Why not, this seems a good idea. That could much easier event if the risk (as the FIRST advisor mentioned) is still there (but lower) from third-party contributions.

**Comment by Rafiot** [comment]
Fixed with the feeds.
