### ISSUE TITLE
UI improvement: add a space between event contributors

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#6882]
There is no visual seperation between the list of contributors to an event. If the contributors are not represented with an icon then this clutters the event interface (contributors are listed as one long string).

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| Type of issue             | Bug
| MISP version / git hash   | 2.4.136

### Expected behavior

Have a space or seperator (fe. |) between contributors.

### Logs, screenshots, configuration dump, ...

```
<tr>
<td class="meta_table_key  " title="" data-original-title="">Contributors</td>
<td class="meta_table_value  " data-original-title="" title=""><a href="https://MISP/logs/event_index/1173/Contr1"><span class="welcome" data-original-title="" title="">Contr1</span></a><a href="https://MISP/logs/event_index/1173/Contr2"><span class="welcome" data-original-title="" title="">Contr2</span></a></td>
</tr>
```

**Comment by JakubOnderka** [comment]
Thanks for report, this is already fixed in `develop` branch and it will be included in next release.
