### ISSUE TITLE
Support for pipe type

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#69]
A lot of malicious software are using named pipe for communication, it might be interesting to add the pipe type. The only issue is to normalize the pipe to allow matching between various malware.

The format is described at the following location:

http://msdn.microsoft.com/en-us/library/windows/desktop/aa365783%28v=vs.85%29.aspx

Escaping can be tricky.

**Comment by Rafiot** [comment]
Pipe is already supported, isn't it?

**Comment by elhoim** [comment]
Yep at least in 2.3 hotfix 124.
