### ISSUE TITLE
Server builds but fails to send complete output on event with 2M attributes

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6901]
I cannot fetch a large event with the PyMISP get_event method, where "large" means the event has 36,266 attributes plus another 672,653 soft-deleted attributes. The server's reply is truncated mysteriously. This is 100% reproducible, please suggest what to check, I'll definitely collect more information to narrow this down.

The runtime from start to failure is about 70 seconds of wall time.  While this script is running I watch the server's php-fpm process, it gets large, here's a snapshot from top:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                      
71865 apache    20   0   13.4g  12.4g  13840 R 100.0  3.3   0:50.72 php-fpm                                                      
```
But we have our execution-time and memory limits in php.ini set *very* large so I don't think the server is exceeding either limit. And since the client pulls over 1GB of character data, I think the server finished building its reply just fine.

If I set the deleted flag to false, the client can fetch the event and its 36K active attributes perfectly fine, requires about 12 seconds.  

I am running the client on the same host as the web server to eliminate any network interference like proxy servers etc etc etc.

I checked the MISP server's debug.log and error.log files, they show absolutely no entries at the relevant timestamp. So the MISP/PHP server seems unaware of the failure. I checked the Apache server's error_log file, absolutely no entry at the timestamp. The Apache server's access.log file shows the request:
```
127.0.0.1 - - [21/Jan/2021:16:04:49 +0000] "POST /events/view/180277 HTTP/1.1" 200 1253226039 "-" "PyMISP 2.4.133 - Python 3.6"
```

We are using version 2.4.133 on both sides. I know we need to upgrade, that's in the works.

The python client failure looks like this:
```
2021-01-21 16:04:49.671439: Getting event ID 180277
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.133-py3.6.egg/pymisp/api.py", line 2966, in _check_response
    response_json = response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Unterminated string starting at: line 28606408 column 41 (char 1253226031)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getEvent.py", line 14, in <module>
    resp = misp.get_event(event=eid, deleted=True, pythonify=False)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.133-py3.6.egg/pymisp/api.py", line 302, in get_event
    event_r = self._check_json_response(r)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.133-py3.6.egg/pymisp/api.py", line 2942, in _check_json_response
    r = self._check_response(response, expect_json=True)
  File "/usr/lib/python3.6/site-packages/pymisp-2.4.133-py3.6.egg/pymisp/api.py", line 2975, in _check_response
    raise PyMISPUnexpectedResponse(f'Unexpected response from server: {response.text}')
pymisp.exceptions.PyMISPUnexpectedResponse: Unexpected response from server: {
    "Event": {
        "id": "180277",
        "orgc_id": "33",
        "org_id": "33",
        "date": "2020-07-01",
        "threat_level_id": "4",
...a zillion lines deleted...
```
Here's the trivial script I use on the client side:
```
#!/usr/bin/env python3
from datetime import datetime
import urllib3
from pymisp import PyMISP


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(
    url='https://my-companuy.com:48752',
    key='mykey',
    ssl=False)
eid = '180277'
print('{}: Getting event ID {}'.format(datetime.now(), eid))
resp = misp.get_event(event=eid, deleted=True, pythonify=False)
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | RedHat
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133
| Browser                   | n/a

### Expected behavior

I expect the client to read the entire contents of a large event including deleted attributes, even if it takes 20 minutes.

### Actual behavior

The client request fails, but the server seems unaware.

### Steps to reproduce the behavior

This may require an event with a very large number of soft-deleted attributes.

**Comment by chrisinmtown** [comment]
The PyMISP team tried to help me with this problem in https://github.com/MISP/PyMISP/issues/685, that issue is now closed since it doesn't seem to be a PyMISP problem.

**Comment by chrisinmtown** [comment]
I've further narrowed this down with cURL to eliminate a PyMISP client problem. I'm running curl on the same machine where the web/REST server runs. Just like with PyMISP I can fetch the event contents using cURL without the soft-deleted attributes, but the server fails to send the whole JSON if I request the soft-deleted attributes. Here's the run including the error message from curl.  You can see that the MISP server told curl to expect lots of bytes but didn't deliver them:
```
$ curl -k --header "Authorization: my-auth-key" \
    --header "Accept: application/json" \
    --header "Content-Type: application/json" \
    --data '{ "deleted": true }' \
    https://misp/events/view/180277 \
    > curl-event-180277-del.out 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 21 5217M   21 1121M    0    19  22.9M      0  0:03:47  0:00:48  0:02:59     0
curl: (18) transfer closed with 4294967296 bytes remaining to read
```
The resulting file is large but not valid JSON:
```
[me@misp ~]$ ls -lh curl-event-180277-del.out
-rw-r--r-- 1 me guest 1.1G Jan 22 13:42 curl-event-180277-del.out
[me@misp ~]$ jq . curl-event-180277-del.out > /dev/null
parse error: Unfinished JSON term at EOF at line 26832566, column 9
```
I again checked the MISP server's debug.log and error.log files, there is *absolutely* no entry for this.

@PROTechThor I know I started this one with PyMISP, but after this new evidence I think the PyMISP tag is not appropriate here anymore.

**Comment by chrisinmtown** [comment]
Latest attempt at narrowing down the problem. This does not appear to be caused by soft-deleted attributes, the problem seems to be related to the size of the data only. Below is the output when I fetch an event that has 2,063,233 active attributes without requesting the deleted ones. The server sends *no* data at all. The debug and error log files remain silent.
```
[me@misp ~]$ curl -s -S -k --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" https://misp/events/view/180269 > curl-event-180269.out 
curl: (18) transfer closed with 6591564126 bytes remaining to read
[me@misp ~]$ ls -lh curl-event-180269.out
-rw-r--r-- 1 me guest 0 Jan 22 14:37 curl-event-180269.out
```
Again please suggest ways to gather evidence, I can reproduce this failure every time.

**Comment by iglocska** [comment]
Interesting, haven't seen the truncation happen yet, though that event seems utterly massive.

**Comment by iglocska** [comment]
I know you mentioned that you didn't update yet, but could you update your instance and try it again? @JakubOnderka recently reimplemented the way we serve large events via the API and it is now streamed instead of sent in one shot, so with extremely large events this should go a long way.

**Comment by chrisinmtown** [comment]
We are scheduled to update to 2.4.137 at the end of January, I will retest this then.

**Comment by JakubOnderka** [comment]
Hello, did you also check php-fpm error logs?

**Comment by chrisinmtown** [comment]
Thanks @JakubOnderka for the suggestion but our php.ini file has these entries:
```
display_errors = Off
;error_log = php_errors.log
```
I think I should change both of those and re-run the fetch operation.  Anything else I should turn on, configure or enable?

**Comment by JakubOnderka** [comment]
@chrisinmtown: Thats OK, but PHP-FPM has own logs. Usually they are stored in `/var/log/php-fpm/`.

**Comment by chrisinmtown** [comment]
Thanks @JakubOnderka on my RHEL7 system I found config file `/etc/opt/remi/php74/php-fpm.conf` that specifies error log file `/var/opt/remi/php74/log/php-fpm/error.log`. In that directory I also found file `www-err.log`.  So I re-ran curl to reproduce the get-large-event failure, but unfortunately neither of those two files changed.  :(  Anywhere else to look for log files?

**Comment by chrisinmtown** [comment]
Here's the result with MISP version 2.4.137, running curl on the same physical host (not a VM, not a docker) as the web server:
```
$ curl -s -S -k --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" https://misp/events/view/180269 > curl-event-180269.out 
curl: (18) transfer closed with 2458726588 bytes remaining to read
```
Again there are no entries in the MISP debug.log/error.log files, nor on the php-fpm error.log or www-error.log files.  I don't think this problem has been fixed.

**Comment by iglocska** [comment]
Stupid question - there's no proxy in the middle that might be truncating the response right? Can you try to curl it from the server itself? If it's already the case, then back to the drawing board...

**Comment by chrisinmtown** [comment]
Not a stupid question @iglocska bcos there are SO MANY proxy servers out there, we are afflicted with one also, but I thought of that :) see this in the description:

> I am running the client on the same host as the web server to eliminate any network interference like proxy servers etc etc etc.

**Comment by chrisinmtown** [comment]
Rechecked this after upgrade to version 2.4.141.  Fetched an event with 800K attributes without complaint, curl wrote a 6.4GB file. So I guess this one is fixed.
