### ISSUE TITLE
PyMISP throws critical error for missing optional dependency (lief)

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6908]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| PyMISP version             | 2.4.137

### Expected behavior
fileobjects (lief) beeing an optional dependency for PyMISP
No Critical Warnings if it's missing.

### Actual behavior
Since PyMISP 2.4.137 I get a critical Error-Output on any PyMISP Script.
`CRITICAL [create_misp_object.py:28 - <module>() ] You need lief >= 0.11.0. The quick and dirty fix is: pip3 install --force pymisp[fileobjects]` 

Think I actually don't need lief, since I never needed, and actually all functionality seems to be ok, just this very confusing error message.
Even worse, something in lief install doesn't work for me too, so installing it is not an option.

### Steps to reproduce the behavior
Try to use PyMISP without [fileobjects] dependencies. (Without lief installed)

**Comment by Rafiot** [comment]
You can ignore it, and it will be gone in the next release.

Lief is only useful if you import PE/ELF/Mach-O files over the web interface. If you do not do that, it is totally optional, and if you do that, it will just skip the PE/ELF/Mach-O parsing.

Out of curiosity, why is lief not working for you?

**Comment by marjatech** [comment]
I rolled back pymisp by one version in the meantime, since i got a lot of error output by my automation ;) 
I already noticed it can be ignored, but I don't really want to skip critical error-outputs too.

About lief:
It somehow got stuck always at wheel build in some kind of endless build, just turning the indicator.
Checked on two machines and also updated setuptools before, but no success.

**Comment by Rafiot** [comment]
Right, that's weird, I've seen it taking a very long time on some machines, but not always. In theory, the wheel is directly downloaded, no need to build it.

I'll have a look at it.
