### ISSUE TITLE
Document the Load default feed metadata feature

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6910]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  RedHat,
| OS version (client)       | all
| PHP version               | 7.4
| MISP version / git hash   | 2.4.133
| Browser                   | all

### Support Questions

Please advise of the right way to update default feeds as stored in file app/files/feed-metadata/defaults.json at upgrade time  For example, feed URLs change over time, the format changes over time, etc. and we need to keep up with the version in your github.  Sure, I can go thru each one by hand, checking every URL and CSV parsing rule, but I'm hoping there's a better way.

I see that the web UI has button "Load default feed metadata".  Clicking that button definitely reads the defaults.json file. That action appears to create some feed duplicates, but not a dupe for every entry in the JSON.  Still trying to understand exactly what happens in the server PHP `app/Moodel/Feed.php
load_default_feed` function.  One particular concern I have is how to handle the distribution entry for a feed.  When the default feeds are first loaded they show "internal only".  But we have chosen different distributions for some of those feeds.

I checked https://www.circl.lu/doc/misp/managing-feeds/ but didn't see anything relevant to this scenario.

Thanks in advance.

**Comment by mokaddem** [comment]
I believe the `load default feed metadata` could be improved to merge divergences.
However, users should be the authority in deciding what to keep as merge conflict will happen.

**Comment by chrisinmtown** [comment]
Thanks @mokaddem but would you please say more, or point me to documentation of the `load default feed metadata` feature?  Of course we need to decide what feeds to keep. We are trying to develop a local procedure for accepting CIRCL changes in upgrades. For example, should we delete all the default feeds and start afresh each time?

**Comment by chrisinmtown** [comment]
Let me clarify my support request.  Please tell me, exactly what does the `load default feed metadata` feature do today when identical or similar rows exist in the feeds table?  I suppose I will have to go read the code, but I'm not a PHP expert.  Thanks in advance.

**Comment by chrisinmtown** [comment]
I propose this text for your documentation/user guide:

The 'Load default feed metadata' feature creates new feeds by importing the entries in file `app/files/feed-metadata/defaults.json` to the database.  Existing feeds are not changed.  The feature checks for duplicates using the feed URL.  If a feed with the same URL already exists in the database, that entry is not imported. This ensures that local modifications such as name, distribution or enabled status are never overwritten.

**Comment by chrisinmtown** [comment]
Opened in the wrong repo.  Please see https://github.com/MISP/misp-book/issues/206
