### ISSUE TITLE
Drop the AlienVault reputation generic feed from defaults.json

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6911]
Would you please check the default feed named "alienvault reputation generic" ?

In the latest commit on branch 2.4, file app/files/feed-metadata/defaults.json defines a feed with that name and URL https://reputation.alienvault.com/reputation.generic. That URL now answers an empty document, not the expected CSV data. The last data we were able to pull from that feed is dated 2020-06-10. Grasping at straws, I tried URLs https://reputation.alienvault.com (blank page) and https://www.alienvault.com (an AT&T cybersecurity page).

Maybe this explains it: https://cybersecurity.att.com/who-we-are/press-releases/att-completes-acquisition-of-alienvault

Thanks in advance.

**Comment by JakubOnderka** [comment]
Hello, thanks for report, but It works for me from command line by `curl` and also in MISP:

```
% curl https://reputation.alienvault.com/reputation.generic

###
# Alienvault IP Reputation Database
# https://reputation.alienvault.com/
###

# Generic format

46.4.123.15 # Malicious Host DE,,51.2993011475,9.49100017548
49.143.32.6 # Malicious Host KR,,37.5111999512,126.974098206
45.248.192.48 # Malicious Host IN,Sikar,27.6166992188,75.1500015259
185.174.195.137 # Malicious Host RU,Samara,53.1834983826,50.1181983948
```

**Comment by chrisinmtown** [comment]
Thanks for checking  @JakubOnderka.  Must be something on the network I'm using.  Sorry to waste your time here.
