### ISSUE TITLE
Fresh Install of misp on ubuntu 20.04 has minor issues

### ISSUE THREAD

**Issue by demiscuzz** [MISP/MISP#6913]
### Work environment

| Questions                        | Answers
|----------------------------|--------------------
| Type of issue                   | Support
| OS version (server)          | Ubuntu
| OS version (client)           | Win10
| PHP version                     | 7.4
| MISP version / git hash   | 2.4.137 (b86c58c8ae24747da06878de178de1cb067a53e0)

### Support Questions

In the Diagnostics section I get a bunch of errors. 
One of the writable Files is not found.  can i just make it? how can i find the complete name of the file? 
![Capture](https://user-images.githubusercontent.com/50229490/105970367-34558680-6081-11eb-9e3a-09d7a6743ae5.PNG)

Do i need to enable these modules? 
![capture2](https://user-images.githubusercontent.com/50229490/105971219-33712480-6082-11eb-9abc-e59917060fd3.PNG)

Also the database schema doesn't match what is expected, is that an issue ?
![Capture3](https://user-images.githubusercontent.com/50229490/105971386-60253c00-6082-11eb-8b79-b2877c7690dd.PNG)

This is a fresh install on a updated and upgraded system with nothing else installed on the server. 
Thanks in advance for the support.

I have just gone through the install log and can see a issue with the install. This was at the very end of the install.
Successfully installed beautifulsoup4-4.9.3 decorator-4.4.2 pillow-8.1.0 pymisp reportlab-3.5.60 soupsieve-2.1 validators-0.18.2
E
======================================================================
**ERROR:** setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 130, in __init__
    response = self.recommended_pymisp_version
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 186, in recommended_pymisp_version
    response = self._prepare_request('GET', 'servers/getPyMISPVersion.json')
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 3131, in _prepare_request
    prepped = self.__session.prepare_request(req)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/var/www/MISP/venv/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 61, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 151, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (terrasecure.uk). Please make sure the API key and the URL are correct (http/https is required): Invalid URL 'servers/getPyMISPVersion.json': No schema supplied. Perhaps you meant http://servers/getPyMISPVersion.json?

**Comment by chrisinmtown** [comment]
it's probably a good idea to list the database issues - what parts of the schema don't match. Also post the version of MariaDB that your Ubuntu uses.

**Comment by demiscuzz** [comment]
My miradb version is: 10.3.25-MariaDB .  If I click the debug button it shows the schema differences.  The only difference I can see is that its set to null.  There are hundreds that have this same discrepancy. Do I have to log into the Database and manual run the recommended code for every one?
![Capture5](https://user-images.githubusercontent.com/50229490/105978628-aaaab680-608a-11eb-93bb-56e8bfce9007.PNG)

![Capture4](https://user-images.githubusercontent.com/50229490/105978393-63bcc100-608a-11eb-8db3-c5ede8fec601.PNG)

**Comment by iglocska** [comment]
Those are benign differences, safe to ignore.

**Comment by iglocska** [comment]
For the git issue, make sure that /var/www/MISP/.git is assigned to the apache user. This happens typically when you clone / update with the root user. 

As for the modules - they're optional, but recommended, they allow you to run enrichment services, import/export in some additional formats, etc.

**Comment by demiscuzz** [comment]
Thank you for the advice and help. set my mind at ease.
