### ISSUE TITLE
MISP Automation , not working properly. event wise data is not getting downloaded.

### ISSUE THREAD

**Issue by vaibhavpandey86** [MISP/MISP#6919]
Hello,

I am trying to automate the process of suricata rules export . I am trying this API format :
https://[misp url]/events/nids/[format]/download/[eventid]/[frame]/[tags]/[from]/[to]/[last]

my final API would be, let say if I want to export just for event 6:
https://[misp url]/events/nids/suricata/download/6

the above event wise api is not working for any specific event id, it is exporting all the rules from all events.

even when I am trying to export all the suricata rules with the api:

https://[misp url]/events/nids/suricata/download

it is leaving my eventa 6, 4, 1207..  to download the suricata rule for. means it is not completed. though these evens contains IDS published attributes.

please let me have a solution here.

**Comment by vaibhavpandey86** [comment]
Hello Any update please?

**Comment by iglocska** [comment]
Those endpoints are horribly outdated, please use restSearch instead, for your particular queries:

POST to `/attributes/restSearch`
Body: 
```
{
    "returnFormat": "suricata"
    "eventid": 6
}
```

If you cannot do post requests for whatever reason:

GET `/attributes/restSearch/returnFormat:suricata/eventid:6`

Hope this helps!

**Comment by vaibhavpandey86** [comment]
Hello @iglocska am sorry for late reply.

I did try your method with GET /attributes/restSearch/returnFormat:suricata/eventid:6
 it is not giving me anything, but when I manually open the event 6 it contains almost 11K attributes with IDS box enabled. and I am able to download Suricata rules manually with "Download as..." option on the left. 
![40F02187-7329-4FDA-9150-032FFF4C4F34_1_105_c](https://user-images.githubusercontent.com/27011344/108666034-3bdf4280-74fc-11eb-9047-319c7f4a78ec.jpeg)

Any help here.???

**Comment by mokaddem** [comment]
Hey,
Is your event published?

**Comment by vaibhavpandey86** [comment]
Hello @mokaddem 
it says "No" to published.
![Screenshot 2021-02-22 at 3 57 17 PM](https://user-images.githubusercontent.com/27011344/108695853-c63c9c00-7526-11eb-8b37-0d5f0a1342c5.png)

**Comment by mokaddem** [comment]
Could you try to publish it and try again?
(There is a `Publish Event` button on the side panel)
Thanks!

**Comment by vaibhavpandey86** [comment]
Hello @mokaddem,
while publishing event 6 it asking for missing taxonomies, got an error
"Could not publish event - no tag for required taxonomies missing: CERT-XLM" ( visible in my last attached image )
tried to add tags, but couldn't find the proper place. I have dropped an email to reporter. waiting for their response, if I get any.
Do you have any idea for the same?!?
Thanks,
Vaibhav

**Comment by adulau** [comment]
As mentioned in the error message, your MISP instance is configured with some required taxonomy to be set in this case CERT-XLM. If the tag is not set, you won't be able to publish. If you manage your MISP instance, you can also disable the required taxonomy.

We are organising a training the 2nd March on how to use MISP, maybe you would like to participate in order to get the concept of MISP: https://www.xing.com/events/3315431

**Comment by vaibhavpandey86** [comment]
Hello @adulau I didn't receive any link for the event you suggested, I have successfully registered myself in there.
