### ISSUE TITLE
Trouble with restricting ports

### ISSUE THREAD

**Issue by RudyFlyer** [MISP/MISP#692]
Currently troubleshooting an issue with an instance, does anyone have a list of ports that need to be open?

**Comment by bane0** [comment]
As far as I know , only http (80) or https (443) depending on your setup.

**Comment by cvandeplas** [comment]
I'm not sure what you mean with troubleshooting an instance. If you could
be more specific it would help us to help you.

* For sync to work you need tcp/443 to be open to the other MISP instance.
(assuming the other side runs MISP over https)
* tcp25 for outgoing email.
* If you run redis and mysql on the same box, then no extra ports should be
required, except the standard things that any normal OS needs.

**Comment by Rafiot** [comment]
@RudyFlyer Did you manage to get your instance working?

**Comment by elhoim** [comment]
No answer, closing. Please re-open if you still have trouble.

**Comment by GIJosh2687** [comment]
For anyone that happens about this post. Go ahead and verify that your ingress and egress rules are good. You need to open 80/443 ingress. You need to allow the ephemeral ports egress to allow for standard HTTP/ HTTPS traffic.
