### ISSUE TITLE
/var/www/MISP/app/Console/cake Admin updateGalaxies fails on clean install of MISP

### ISSUE THREAD

**Issue by garrit-schroeder** [MISP/MISP#6921]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 
| PHP version               | 7.3
| MISP version / git hash   | 2.4.137
| Browser                   | If applicable

### Expected behavior

/var/www/MISP/app/Console/cake Admin updateGalaxies runs successfully on first try.

### Actual behavior

/var/www/MISP/app/Console/cake Admin updateGalaxies only runs successfully after a galaxy update is triggered by the web interface first. Then the command works fine.

### Steps to reproduce the behavior
1. Clean install of MISP
2. Run command /var/www/MISP/app/Console/cake Admin updateGalaxies. Fails
3. Update Galaxies by using the web interface
4.Run command /var/www/MISP/app/Console/cake Admin updateGalaxies. Successful

### Logs, screenshots, configuration dump, ...

```
Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: Table galaxy_cluster_relations for model GalaxyClusterRelation was not found in datasource default.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource('galaxy_cluster_...')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1260): Model->schema()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1219): Model->_setAliasData(Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ModelValidator.php(214): Model->set(Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2413): ModelValidator->validateMany(Array, Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2330): Model->validateMany(Array, Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2280): Model->saveMany(Array, Array)
#8 /var/www/MISP/app/Model/GalaxyClusterRelation.php(406): Model->saveAll(Array)
#9 /var/www/MISP/app/Model/Galaxy.php(247): GalaxyClusterRelation->bulkSaveRelations(Array)
#10 /var/www/MISP/app/Console/Command/AdminShell.php(164): Galaxy->update(false)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateGalaxies()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateGalaxies', Array)
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#15 {main}

```

**Comment by garrit-schroeder** [comment]
Updating the ObjectTemplates seems to be broken too

root@a5caaa24a75a:/var/www/MISP/app/Console# /var/www/MISP/app/Console/cake Admin updateObjectTemplates

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Usage: /var/www/MISP/app//cake Admin updateObjectTemplates [user_id]

**Comment by garrit-schroeder** [comment]
After a bit more investigating the problem:

The command does succeed **but only after** one successful user login from the web interface.

**Comment by garrit-schroeder** [comment]
The command works after the web interface is loaded once. It has something to do with the db version, I think.

**Comment by mokaddem** [comment]
Indeed, it could be that your instance wasn't up-to-date when you ran the `updateGalaxies` script.
Thanks for the feedback!

**Comment by SteveClement** [comment]
Maybe a race condition somewhere. I would say this is an outlier.
