### ISSUE TITLE
HOWTO Manage Retention of Soft Deleted Attributes?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#6929]
Is there any documentation on the value proposition of MISP attribute soft deletion and more importantly how best to manage the retention and purge of these soft deleted attributes?

Perhaps soft deletion exists for GDPR purposes. However, we are not aware of any method to age-out purge, or disable soft deletion that occurs with Delta Merge Fixed Event Feed processing.

We have various custom Fixed Event Delta Merge Feeds we've configured with millions of soft deleted attributes due the nature of this premium feed provider's indicator states.

We find that writing a PyMISP app providing an age-out deletion process can take an enormous amount of time, i.e. days, to run, as our MISP has been collecting from these feeds for well over a year, and only now did we realize the huge amount of soft-deletes.

Any guidance is greatly appreciated.

Some related references:
* https://www.misp-project.org/compliance/gdpr/information_sharing_and_cooperation_gdpr.html
* https://github.com/MISP/MISP/pull/5973
* https://github.com/MISP/misp-compliance/issues/2
* https://github.com/MISP/PyMISP/issues/689

**Comment by chrisinmtown** [comment]
Hard-delete operations on soft-deleted attributes can require as much as 1-3 seconds.  The speed seems to correlate well with the number of non-deleted attributes on the event: it's very slow to hard-delete an attribute on events with 100K+ attributes; fairly quick to hard-delete an attribute on events with 1K attributes.

**Comment by iglocska** [comment]
It has nothing to do with compliance and everything to do with revocations. MISP is built as a sharing platform, as such if I delete an attribute on my end, my peers have no way of knowing that this attribute needs to be removed. Soft deleted attributes are propagated the same way as regular attributes, informing the other MISPs that they need to flag the attribute as deleted.

**Comment by github-germ** [comment]
Thanks. OK, that does make sense. For those sites that are not sharing, is there a method to make the Delta Merge deletions hard vs. soft? If not, might that be a new feature?

**Comment by iglocska** [comment]
Should be a new feature and it would make a lot of sense. We have something similar for the regular delete, where if an event has not been published yet it hard deletes by default. Maybe something to think about would be an instance wide toggle for hard deletes, your use case of just ingesting data would fit in well.

**Comment by github-germ** [comment]
Excellent. Do you want to create a feature request to get the wording accurate or suggest herein and I'll be happy to create?

Also, any chance of a solution to a more expeditious method to delete soft-deletes, e.g. "delete all soft deletes on a specified event" or agreeing to move forward with #689, something more swift done in bulk on the server side?

**Comment by github-germ** [comment]
Closing this issue since I've spun out this Feature Request as per @iglocska recommendation from this discussion. Thanks.

* https://github.com/MISP/MISP/issues/6933

**Comment by github-germ** [comment]
Also created this Feature Request: https://github.com/MISP/MISP/issues/6934
