### ISSUE TITLE
HTTP:500 for extended event-view

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6946]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137, 2b5b5f97d

### Expected behavior
switching from atomic view to extended view would show the same event, with additional attributes etc.

### Actual behavior
MISP returns HTTP-Status 500 - Internal Server Error in addition to an incomplete Page. (obviously missing style-sheets etc.)

### Steps to reproduce the behavior
Create an event A and extend it by event B.
While viewing event A, try to switch to extended view next to `Currently in atomic view.`

### Logs, screenshots, configuration dump, ...
Tried on two completely separate instances.
Looks like this:
![misp-dev_events_view_1_extended_1](https://user-images.githubusercontent.com/72734273/106623026-7cd6dd80-6574-11eb-89a2-bcf837998276.png)

**Comment by JakubOnderka** [comment]
Hello, can you please provide exception message from MISP error log?

**Comment by iglocska** [comment]
It looks like the function for fetching org logos changed, should be fixed now.
