### ISSUE TITLE
Add login attempts with source IP address to the logs

### ISSUE THREAD

**Issue by pszemekd** [MISP/MISP#695]
It would be handy to have logs functionality extended with all login attempts (not only successful ones) including source IP address from which login att. was performed.
This info should be accessible only for administrator of the MIPS instance.

**Comment by iglocska** [comment]
You can now enable this along with another seperate setting to enable logging of successful API calls to MISP.

**Comment by elhoim** [comment]
Would it be possible to add a flag (disabled by default) for logging of failed API calls?

**Comment by iglocska** [comment]
It's there already :) If you mean failed because of auth issues.

**Comment by iglocska** [comment]
This is how it will show up:

161722 	192.168.56.1	SYSTEM 	SYSTEM 	2015-11-09 08:34:51 	auth_fail 	Failed authentication using API key (mabfFjft0auFM3bj2FhJQGmclxT3ASvW2HcH0rb2)

**Comment by elhoim** [comment]
Ok, my bad!

Super!
