### ISSUE TITLE
Upload attachment (PDF) ; editing object gives error "Object cannot be edited, no valid template found."

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#6954]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| MISP version / git hash   | 2.4.137

### Expected behavior
Upload an attachment (PDF file), set as malware sample. Creates an object. Editing the object allows you to edit the object data elements.

### Actual behavior
Upload an attachment (PDF file), set as malware sample. Creates an object. Editing the object results in an error "Object cannot be edited, no valid template found.".
File is properly attached and analyzed in MISP event.

Tried with "Update objects": same error

Creating an object file manually, adding the attachment and afterwards editing the object works. But this method (via object) does not do the "advanced extraction".

**Comment by cudeso** [comment]
If you Add attachment, enable "malware sample" but disable "Advanced extraction" then the editing of the object works.

**Comment by cudeso** [comment]
Also noticed that adding attachment with malware sample + advanced extraction does not save the data put in the comment field. It does save the comment when disabling "advanced extraction".

**Comment by mokaddem** [comment]
Hey, could it be that your object templates used by PyMISP are not up-to-date?
In the meantime, a7834a291b0e3cc38ceb457551674e91aa930d33 allows you to update object to the newer known template even if MISP doesn't know the original template.

**Comment by cudeso** [comment]
@mokaddem indeed, that will be the cause. Thanks for https://github.com/MISP/MISP/commit/a7834a291b0e3cc38ceb457551674e91aa930d33 . I'll close this issue.
