### ISSUE TITLE
Input validation in the GnuPG field of a user

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#696]
If a user enters invalid GnuPG data in the field, the application crashes when parsing the GnuPG field like sending an email from the web interface. To reproduce the bug:

- Create a user
- Put a random string in the GnuPG field
- and send a custom email from the MISP web interface to this user.

The bug is quite annoying especially when you send a custom message to all the users (as it will stop in the middle of the sending).

**Comment by iglocska** [comment]
That sounds bad, on it!

**Comment by Rafiot** [comment]
fixed by 675ceb2e0e9c4d81d206c2d4b83b149316b7b2ed
