### ISSUE TITLE
Fresh Install of misp on ubuntu 20.04 

### ISSUE THREAD

**Issue by demiscuzz** [MISP/MISP#6960]
Questions | Answers
-- | --
Type of issue | Support
OS version (server) | Ubuntu
OS version (client) | Win10
PHP version | 7.4
MISP version / git hash | 2.4.137 (b86c58c)

I attempted to add an enrichment and found that there were none to add. 
![enrichment1](https://user-images.githubusercontent.com/50229490/106763382-ae13e400-662e-11eb-9d64-9b3e892866a4.PNG)

diagnostics show:
![enrichment2](https://user-images.githubusercontent.com/50229490/106763518-d4d21a80-662e-11eb-961c-ba81d4485c25.PNG)

After reading a few other similar issues I had a look in /var/www/MISP/venv/bin/ 
and found that there was no folder named /misp-modules/
Is there a way to install them after installing an instance of misp or is it the case i need to do a fresh install? 
Thank you in advance for any suggestion, help or solutions.

**Comment by chrisinmtown** [comment]
misp-modules is a submodule.  You have to do the usual git incantations to fetch it as directed by the INSTALL*.txt file that's right for your OS.  Mine has this:
```
  # Fetch submodules
  $SUDO_WWW git submodule update --init --recursive
  # Make git ignore filesystem permission differences for submodules
  $SUDO_WWW git submodule foreach --recursive git config core.filemode false
  # Make git ignore filesystem permission differences
  $SUDO_WWW git config core.filemode false
```

**Comment by adulau** [comment]
misp-modules is an autonomous software part of MISP. To do the installation you can go at the following location: 

https://github.com/MISP/misp-modules#how-to-install-and-start-misp-modules-in-a-python-virtualenv-recommended

and start misp-modules then go back to misp enable it and the associated modules.

**Comment by demiscuzz** [comment]
Super stuff. Thank you both.
