### ISSUE TITLE
Cannot get any engagement to repeated requests to purchase support contracts

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#6963]
We have tried for many many months to get a response to our RFIs to establish a Support Agreement.  I tried for a couple of months and gave up.  My colleague has been trying for a month or so and is similarly giving up.

Your organisation is breaking Pat's #1 Rule of Business:  **"NEVER make your Customer wait in line to give you their money"**

I'm not going to go into details here as this is obviously an inappropriate place to discuss such matters.  However, nothing else has worked so this _our last ditch effort to purchase a Support Agreement from your Team_.

**Comment by adulau** [comment]
You should have received a personal email regarding the matter. Thank you very much.

**Comment by chrisinmtown** [comment]
@adulau thank you for replying here, yes you and I chatted via Gitter and I was hoping for a note, but nothing has arrived at my email address that's recorded in the PyMISP git log at aa206d0009. Will you please resend?

**Comment by packet-rat** [comment]
@adulau -  Thank you very much for your timely and effective response. We've received the proposal & T&Cs.
