### ISSUE TITLE
"Download Bro Rules" fails

### ISSUE THREAD

**Issue by emmekappa86** [MISP/MISP#6966]
Since version 2.4.135, "Download as"->"Download Bro Rules" fails for apparently every Event with "An Internal Error Has Occurred."

**Comment by chrisinmtown** [comment]
For what it's worth, in version 2.4.137 I picked an event with a small number of attributes (14), clicked on Download As, clicked the Bro Rules, and my browser downloaded a plain-text file called "misp.all.event_1234567.intel" with this first line:
```
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
```
I repeated this on an event with 845 attributes, same sort of result (no error).

I don't have a 2.4.135 system I can try.

**Comment by iglocska** [comment]
Should be fixed now, it was an invalid group by statement (for the OP)

@chrisinmtown - make sure the events are published and have valid attribute types with the IDS flag set. For me it correctly populates the export that way.

**Comment by chrisinmtown** [comment]
Thanks @iglocska I don't know how to interpret the Bro Rules output anyhow :) I didn't want to paste a bunch of junk, just showed the header to say that it seems to be working fine.

you say "should be fixed now" will you paste the commit sha when you close this?

**Comment by iglocska** [comment]
Sure, 83e9580b97a2a4f0494d2819160fd209dc137141
