### ISSUE TITLE
Dashboards: save template fails with CSRF error

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6974]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | v2.4.137 (99b405b73e34ff3fc84af642d14d4e8c99eff7ba) 
| Browser                   | Firefox

### Expected behavior
Saving a Dashboard Template will success.

### Actual behavior
Any attempt to save a dashboard as template for other users fails with a CSRF error.
`You have tripped the cross-site request forgery protection of MISP`

### Steps to reproduce the behavior
Just try to save any Dashboard Template via `Save Dashboard Config`
Didn't resubmit, just trying to save my freshly reloaded Dashboards.

### Logs, screenshots, configuration dump, ...

**Comment by mokaddem** [comment]
Hey @marjatech,
I can't reproduce the issue. Could you please update to the latest version available and try again?
Thanks!

**Comment by marjatech** [comment]
Hey @mokaddem, 
just updated to 2.4.139
It's fine now. 
Thank you anyway!
