### ISSUE TITLE
Dashboards: store widget config fails without notifying for invalid JSON

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#6975]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.4
| MISP version / git hash   |  v2.4.137 (99b405b73e34ff3fc84af642d14d4e8c99eff7ba) 
| Browser                   | Firefox

### Expected behavior
Some error message notifying the user, that what he just tried wasn't done, because of invalid JSON.
This can be quite frustrating, since invalid JSON often is not obvious to the user.

### Actual behavior
No error and widget configuration won't change.

### Steps to reproduce the behavior
Edit the configuration for some widget. Just forget some `,` or `"`. 

### Logs, screenshots, configuration dump, ...

**Comment by marjatech** [comment]
@mokaddem:
Thank you for this fix!
will it also affect the widget-config, or only the full dashboard-import from JSON?

**Comment by mokaddem** [comment]
Only the widget-config

**Comment by mokaddem** [comment]
I just added a similar check if when importing the full dashboard in 7b3be9362b0e6d2bfaa0c4ebf76257d174349cfc
