### ISSUE TITLE
Repair duplicate feed name in file app/files/feed-metadata/defaults.json (minor)

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6978]
Please repair a duplicate feed name. In version 2.4.137, file app/files/feed-metadata/defaults.json, the ids 57 and 58 both use the same name but have different URLs.  

https://github.com/MISP/MISP/blob/7dfe92655f2cb2c79728b95a7e3b928dccae1d01/app/files/feed-metadata/defaults.json#L964

This can cause user confusion. I know that the system is fine with duplicate entries in the name column.  Thanks for considering this minor issue.

My view of the content is pasted below.

```
{
    "Feed": {
      "id": "57",
      "name": "http://cybercrime-tracker.net",
      "provider": "http://cybercrime-tracker.net hashlist",
      "url": "https://cybercrime-tracker.net/ccamlist.php",
      "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
      "enabled": true,
      "distribution": "3",
      "sharing_group_id": "0",
      "tag_id": "0",
      "default": false,
      "source_format": "freetext",
      "fixed_event": true,
      "delta_merge": false,
      "event_id": "0",
      "publish": false,
      "override_ids": false,
      "settings": "{\"csv\":{\"value\":\"\",\"delimiter\":\",\"},\"common\":{\"excluderegex\":\"\"}}",
      "input_source": "network",
      "delete_local_file": false,
      "lookup_visible": true,
      "cache_timestamp": "1514750887"
    }
  },
  {
    "Feed": {
      "id": "58",
      "name": "http://cybercrime-tracker.net",
      "provider": "http://cybercrime-tracker.net gatelist",
      "url": "https://cybercrime-tracker.net/ccamgate.php",
      "rules": "",
      "enabled": true,
      "distribution": "3",
      "sharing_group_id": "0",
      "tag_id": "0",
      "default": false,
      "source_format": "freetext",
      "fixed_event": true,
      "delta_merge": false,
      "event_id": "0",
      "publish": false,
      "override_ids": false,
      "settings": "{\"csv\":{\"value\":\"\",\"delimiter\":\",\"},\"common\":{\"excluderegex\":\"\"}}",
      "input_source": "network",
      "delete_local_file": false,
      "lookup_visible": true,
      "cache_timestamp": "1514750887"
    }
  },
```

**Comment by chrisinmtown** [comment]
One more very minor feed name issue: some are very long like "This list contains all domains - A list for administrators to prevent mining in networks".  If you start making revisions, please consider abbreviating that kind of thing.

**Comment by chrisinmtown** [comment]
I think this has been fixed but I'm waiting for confirmation

**Comment by github-germ** [comment]
> Please repair a duplicate feed name. In version 2.4.137, file app/files/feed-metadata/defaults.json, the ids 57 and 58 both use the same name but have different URLs.
>       "url": "https://cybercrime-tracker.net/ccamlist.php",


This appears to be fixed in 2.4.139 with that `url` included only once:
https://github.com/MISP/MISP/blob/v2.4.139/app/files/feed-metadata/defaults.json#L966

**Comment by chrisinmtown** [comment]
@github-germ the problem of duplicate feed name remains in the very latest tip of branch 2.4, only now they've added goofy backslashes to the URL, look:

https://github.com/MISP/MISP/blob/8233f0f6143472be376ab31ea7ca6d18d670b5fd/app/files/feed-metadata/defaults.json#L670

https://github.com/MISP/MISP/blob/8233f0f6143472be376ab31ea7ca6d18d670b5fd/app/files/feed-metadata/defaults.json#L690

**Comment by chrisinmtown** [comment]
I propose this change
```
diff --git a/app/files/feed-metadata/defaults.json b/app/files/feed-metadata/defaults.json
index 68ab37ef2..374909e20 100644
--- a/app/files/feed-metadata/defaults.json
+++ b/app/files/feed-metadata/defaults.json
@@ -961,7 +961,7 @@
   {
     "Feed": {
       "id": "57",
-      "name": "http://cybercrime-tracker.net",
+      "name": "http://cybercrime-tracker.net hashlist",
       "provider": "http://cybercrime-tracker.net hashlist",
       "url": "https://cybercrime-tracker.net/ccamlist.php",
       "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
@@ -986,7 +986,7 @@
   {
     "Feed": {
       "id": "58",
-      "name": "http://cybercrime-tracker.net",
+      "name": "http://cybercrime-tracker.net gatelist",
       "provider": "http://cybercrime-tracker.net gatelist",
       "url": "https://cybercrime-tracker.net/ccamgate.php",
       "rules": "",
```
Because the URL has not changed, this will not change any existing systems when people click on "Load default feeds", so I believe the risk of breaking anything is very low.

**Comment by chrisinmtown** [comment]
I hope you'll consider my proposal, it seems like a low-risk change since the URLs remain *unchanged*, thanks.

**Comment by iglocska** [comment]
Good point, thanks!

**Comment by chrisinmtown** [comment]
Thanks @iglocska
