### ISSUE TITLE
REST API search for not decayed attributes is very slow

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#6981]
Hi,

i am trying to query MISP using REST API to return all the attributes marked as not decayed (based on our decaying model), but the search is very slow and if I use a time range greater than 15d it return me an error code 1.

I'm using a search like the following one:

{ "timestamp":"365d","excludeDecayed": "1","type":{"OR": ["ip-src","ip-dst","domain"]}}

In my MISP instance i have more than 300k attributes.

Can someone help me to find a solution (eg. a more efficient query)?

Thanks and regards,
Pietro

**Comment by chrisinmtown** [comment]
Please state your version of MISP.  Also it would help if you quantify "very slow".  Does that mean it takes a minute, an hour, a day?  If you get error code 1, did you check the server's error.log file to get more information? 

Performance is difficult to guess about.  Altho 300K attributes is relatively small (our instance has millions), you didn't mention anything about the amount of memory the database has, the amount of memory available to PHP, etc.

**Comment by pietrogu** [comment]
Hi,

my MISP is at version  v2.4.137 (b86c58c8ae24747da06878de178de1cb067a53e0)
The machine is a VM with 8 GB RAM and 2 CPUs.

I don't know how to check the amount of memory the database has and the amount of memory available to PHP. Could you help me? I should inform you that when i installed MISP the machine had just 2 GB of RAM. Is it possible that the configuration is still based on that RAM value?

With "very slow" i mean that i must wait for about 8 minutes for the results (if I use timestamp <= 15d)

In error.log I have this:

Error: Fatal Error (1): Maximum execution time of 300 seconds exceeded in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php, line 2657]
2021-02-05 17:52:49 Error: [InternalErrorException] Internal Server Error
Request URL: /attributes/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Maximum executi...', '/var/www/MISP/a...', 2657)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Maximum executi...', '/var/www/MISP/a...', 2657, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

Thank you,
Pietro

**Comment by chrisinmtown** [comment]
@pietrogu my first guess is that your database needs lots of time for queries.  That may be caused by using a default DB configuration with very little memory, or caused by a slow VM filesystem. I hope you can get help locally from an expert to confirm or disprove this guess.

**Comment by pietrogu** [comment]
How can i check DB memory?

**Comment by pietrogu** [comment]
Hi,

in my php.ini file i have these settings:

max_execution_time (300)
memory_limit (2048M)

What will be the effect on my MISP if I raise one of both of them?
Maybe if i raise the memory_limit i would have a faster search?

**Comment by pietrogu** [comment]
Ok seems that raising max_execution_time did te job.
I close the issue
