### ISSUE TITLE
XSS fix breaks HTML included in config.php

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#699]
Hi,

Since the XSS fix in 
https://github.com/MISP/MISP/commit/bc06362d199bfa4dd0280e2af216a5dbf9abe740
any HTML included in config.php to style loginpage, headers and footers is broken. 
The call to "h($string)" replaces html with html entities ("<" -> &lt; ; &copy; -> &amp;copy;).

Any suggestions for a quick fix?

kr,

koen

**Comment by iglocska** [comment]
The easiest is to just replace &copy; with © in the footer field in the admin settings, that should work fine.

**Comment by cudeso** [comment]
Thanks. Works for © but not if <strong> ; <img or other html tags are included.

**Comment by iglocska** [comment]
Ah I see, you are including actual HTML in there. Hmph. The idea was to
prevent any actual tags being put in there, but I guess we have two
options:

1. (Dirty) simply remove the sanitazation
2. I can add some basic parsing for [URL] and [IMG] tags for those fields
(though this would have to wait a bit)

**Comment by elhoim** [comment]
3. Option to allow HTML in the footer? And disabled by default.

**Comment by elhoim** [comment]
Solved?

**Comment by cvandeplas** [comment]
Closing this as this is by design. If you really need full-blown html the solution is to change the html templates. Please re-open the issue if this is still relevant. A possible solution could be the use of markdown.

**Comment by cudeso** [comment]
This https://github.com/MISP/MISP/wiki/Frequently-Asked-Questions#17-how-can-i-change-the-theme in fact provided an answer for theming MISP.
