### ISSUE TITLE
How to get an overview of sightings?

### ISSUE THREAD

**Issue by acj014** [MISP/MISP#6990]
Hello together,

I work with your MISP Product in combination with dovehawk module and zeek to scan IoT devices in my network.

It's part of my thesis and I thinks I need some help with your product.

I let Misp run in background with zeek and about 12000 indicators, (that came from 3 TI Feeds) for like 7 days.

Now i dont know how to see if there were any sightings at all in my network from those automatically created iocs?

I checked your documentation https://www.circl.lu/doc/misp/sightings/ but im not really sure where to find an overview.

The REST-API also doesnt seem to work right, is there any other way not to click through 1000+ events to see which iocs where triggered with a sighting?

I used CIRCL, Malwaredomainlist and Phishtank, (Phistank is one event with 1400 attributes, but the other TI's are distributed over a lot events, where i cannot get an adequate overview from).

Thanks in advance for your help!

**Comment by mokaddem** [comment]
Hello,
I don't know how the module you are using is integrated with MISP, however, if it creates sightings, you can fetch them via the API.
Please have a look at `/servers/rest` in your MISP instance. This page lists a lots of endpoints along with their documentation.
You might particularly be interested in `/sightings/restSearch/[context]` which allows you to fetch sightings with their respective attributes.
Cheers!
