### ISSUE TITLE
[new-api-key-auth] add a last used API key timestamp

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#6998]
[new-api-key-auth] add a last used timestamp in the new API key handler. 

We don't need a significant precision if we don't write too often on the table as it's creating a bit of overhead.

**Comment by JakubOnderka** [comment]
Already implemented :) You need to enable `MISP.log_user_ips` and `MISP.log_user_ips_authkeys`, then key usage is stored in Redis also with last usage timestamp. Then you can check key usage in key information view. 

<img width="502" alt="Snímek obrazovky 2021-02-11 v 14 58 02" src="https://user-images.githubusercontent.com/163343/107645858-8bf71300-6c79-11eb-9cea-a865da83dc7f.png">

**Comment by adulau** [comment]
This is great ;-) I completely miss that it was already in the new API key handler.
