### ISSUE TITLE
Enable/disable individual galaxies

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#7019]
Currently all galaxies are always enabled, unlike taxonomies. Sure made a lot of sense when we had about a dozen of them, but it's time to allow admins to manage what galaxies their users use.

**Comment by mokaddem** [comment]
Should it also apply on cluster as well?
And if yes, should the orgc of the cluster be able to control this enabled state or should it be for the admin only?

**Comment by iglocska** [comment]
I'd say no, custom clusters are a different story, but indeed something we need to think about.

**Comment by iglocska** [comment]
But yeah as discussed offline - let's keep it galaxy level only.

**Comment by Wachizungu** [comment]
Thanks a lot! Pretty excited about this one
