### ISSUE TITLE
Feed CIRCL missing trailing slash on URL in app/files/feed-metadata/defaults.json

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7022]
At the tip of branch 2.4, the CIRCL feed is defined in file app/files/feed-metadata/defaults.json with URL `https://www.circl.lu/doc/misp/feed-osint` and a curl of that url yields this:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.circl.lu/doc/misp/feed-osint/">here</a>.</p>
</body></html>
```

I squinted long and hard at the message before I finally noticed the trailing slash.  Please update the defaults.json appropriately to have the trailing slash.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | All
| PHP version               | 7.4
| MISP version / git hash   | 2.4.139
| Browser                   | If applicable

### Expected behavior

The defaults.json file provides the right URL for the CIRCL OSINT feed.

### Actual behavior

The defaults.json file provides a slightly defective URL for the CIRCL OSINT feed.

### Steps to reproduce the behavior

Run cURL on the URL provided in the file.

**Comment by chrisinmtown** [comment]
This problem still lingers. I propose this fix:
```
diff --git a/app/files/feed-metadata/defaults.json b/app/files/feed-metadata/defaults.json
index 68ab37ef2..d41fc1ec1 100644
--- a/app/files/feed-metadata/defaults.json
+++ b/app/files/feed-metadata/defaults.json
@@ -4,7 +4,7 @@
       "id": "1",
       "name": "CIRCL OSINT Feed",
       "provider": "CIRCL",
-      "url": "https://www.circl.lu/doc/misp/feed-osint",
+      "url": "https://www.circl.lu/doc/misp/feed-osint/",
       "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]}}",
       "enabled": true,
       "distribution": "3",
```

**Comment by chrisinmtown** [comment]
This may almost be the easiest bug-fix ever :) I hope you'll accept my proposed change

**Comment by chrisinmtown** [comment]
Thanks.

**Comment by iglocska** [comment]
No, thank you! ;)
