### ISSUE TITLE
Edit reference button / functionality in event graph is broken

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#7028]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.5 LTS
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4139, 8233f0f6143472be376ab31ea7ca6d18d670b5fd
| Browser                   | Brave, Edge

### Expected behavior
The button does something (I guess allow you to change reference type and comment)

### Actual behavior
Nothing happens when you click it

### Steps to reproduce the behavior

1. Go to an event with an existing object reference in the event graph or add one.
2. Select a reference and click edit reference

Notes:

- You can still delete and recreate the reference with new values as a workaround

**Comment by mokaddem** [comment]
Hello!
Indeed, the edit button created by the graphing library is a bit confusing as it implies that you can edit object references.
However, it's not the case as there is no way to edit a reference right now.
The only way currently is to delete and create a new one as you pointed out

**Comment by Wachizungu** [comment]
Hi!

Okay, good to know :)
