### ISSUE TITLE
PyMISP and urllib3 error

### ISSUE THREAD

**Issue by SoheiMitsukawa** [MISP/MISP#7031]
When I tried to use PyMISP 2.4.138, I got an error.

First, the code is below:

--------------------

from pymisp import ExpandedPyMISP
MISP_AUTHKEY = 'hoge'
MISP_URL = 'https://hoge'
misp = ExpandedPyMISP(MISP_URL, MISP_AUTHKEY, ssl=False, debug=False)

--------------------

The details of the error are as follows:
>Traceback (most recent call last):
>  File "git.py", line 10, in <module>
>    misp = ExpandedPyMISP(MISP_URL, MISP_AUTHKEY, ssl=False, debug=False)
>  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 142, in __init__
>    if brotli_supported():
>  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 97, in brotli_supported
>    major, minor, patch = urllib3.__version__.split('.')  # noqa: F811
>ValueError: not enough values to unpack (expected 3, got 2)

I use urllib3 1.22:
$ pip3 show urllib3
Name: urllib3
Version: 1.22
...

And, when I updated PyMISP, I saw the following message:
>Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0,>=2.25.0->pymisp) (1.22)

Could you resolve this error?

**Comment by Rafiot** [comment]
It is fixed on PyMISP, but not in the package yet: https://github.com/MISP/PyMISP/commit/e52263b75a47414fdfe405547d75cfad5f5df654

I'll bump PyMISP in the repo.

**Comment by SoheiMitsukawa** [comment]
Thank you for your prompt response.
I understand.
Now, waiting to be added to the package.
Thanks,
