### ISSUE TITLE
[Enhancement] - Can you please define a ZeroMQ parameter for the "host"

### ISSUE THREAD

**Issue by joydragon** [MISP/MISP#7040]
**Is your feature request related to a problem? Please describe.**
Whenever you activate the ZeroMQ plugin it'll always start with 0.0.0.0

**Describe the solution you'd like**
Can you please define a ZeroMQ parameter for the "host" that's going to be listen to on the plugin settings page?
It wouldn't be a huge change, and it'll prevent the server to be open to everyone everytime.
The change would be needed at:
/MISP/app/files/scripts/mispzmq/mispzmq.py line 105-106

```
self.socket.bind("tcp://*:{}".format(self.settings["port"]))
self._logger.debug("ZMQ listening on tcp://*:{}".format(self.settings["port"]))
```
for something like:
```
self.socket.bind("tcp://{}:{}".format(self.settings["host"], self.settings["port"]))
self._logger.debug("ZMQ listening on tcp://{}:{}".format(self.settings["host"],self.settings["port"]))
```

**Describe alternatives you've considered**
Making the change on my own on the line considered above.
I've already setup the server to start as 127.0.0.1, but it'd be better if you can change it on the MISP interface.

**Comment by adulau** [comment]
This is a very good point.

**Comment by adulau** [comment]
Related to #7039
