### ISSUE TITLE
MISP no space on /var/www/MISP/app

### ISSUE THREAD

**Issue by Tyrell20** [MISP/MISP#7047]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Red Hat Enterprise Linux Server release 7.9 (Maipo)
| MISP version / git hash   | 2.4.137

### Support Questions
Hello,
we are facing an issue about the space left on /var/www/MISP/app.
The file stored here take up the following space:

> 4.0K    composer.json
4.0K    composer.license
92K     composer.lock
2.2M    composer.phar
84K     Config
176K    Console
1.8M    Controller
3.0G    files
4.0K    index.php
13M     Lib
12M     Locale
4.0K    Makefile
2.5M    Model
356K    Plugin
36K     Test
1.2G    tmp
4.0K    update_thirdparty.sh
12M     Vendor
3.8M    View
15M     webroot

The more space is located on the following path:

/var/www/MISP/app/files/scripts/tmp
Here I found also event in stix format.
It is not clear if I can to delete these file.

Could you please indicate me how to manage the file stored here?

Many thanks

**Comment by tomking2** [comment]
If I'm not mistaken, usually this is one of two things:
1. There is a bug in the stix generation script which causes it to crash prematurely and not remove files upon completion (possibly attribute mapping issue)
2. A client terminates a connection before the response is sent back

Might be worth testing a stix export while checking the logs and raising an issue/pr of you spot a problem. 

However these are safe to delete. Worst case is any active API request using a file will receive an error. 

Similar to #6159

Can just set up a periodic cron job to clear these outside of standard hours if you want to keep it maintained

**Comment by iglocska** [comment]
Yeah, been seeing something similar to what @tomking2 describes above - though it seems to have dropped recently, was having issues with a space constrained server until recently. Could you update your MISP and see if your /var/www/MISP/app/files/scripts/tmp directory still keeps growing? 

Also, yes, you can delete the files there.

**Comment by Tyrell20** [comment]
Many thanks. Unfortunately the update did not solve the issue. I scheduled a cron job in order to delete these files

**Comment by iglocska** [comment]
Ping @chrisr3d -could be a bug in the STIX export

**Comment by Tyrell20** [comment]
Hello,

any feedback about this problem, still present on 2.4.146 version? 
Thank you

**Comment by chrisr3d** [comment]
Hey,
I ran a few tests on my side and did not find anything wrong.
As mentioned already above and in another similar issue, usually files could stack up in `/var/www/MISP/app/files/scripts/tmp` if there is an issue with a STIX export.
Do you have anything in `var/www/MISP/app/tmp/logs/exec-errors.log`? And do you still have files stacking up?
If something goes wrong with the STIX export, `exec-error.log` should contain the debugging message returned by the export script if it is failing.

**Comment by wjddnjs33** [comment]
Who are u?

나의 iPhone에서 보냄
