### ISSUE TITLE
Mixbox Versioning mismatch during MISP Installation

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7054]
### Work environment
| Type of issue                   | Support
| OS version (server)          | Ubuntu OS
| OS version (client)           | Ubuntu, 18.04 LTS
| MISP version / git hash   | 2.4.138, hash of the commit
| Browser                          | Google Chrome

### Support Questions
Hello!

I am following the official documentation to update the python dependencies: https://www.circl.lu/doc/misp/updating-python/. After a fresh MISP installation I've noticed error with mixbox default installation version vs expected as below:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54234520/108629058-8f5b7d00-7477-11eb-842d-9676b363f90b.png)

By default **Mixbox version 1.0.5** is installed and the expected version is **1.0.3**.

I've so rectified this error by installing mixbox version 1.0.3 and the below error appears in CLI:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/54234520/108629160-16105a00-7478-11eb-86ef-ed2a38816555.png)

Please let me know how I can resolve this.

Thanks.

**Comment by ghost** [comment]
At least version 1.0.4 works fine, I would assume 1.0.5 is Ok as well.

**Comment by War10ck3** [comment]
How do I resolve the UI issue as the latest Mixbox version is 1.0.5 which should work fine. According to the UI error message, the issue is that this latest version is not compatible with the STIX version during the fresh installation. I am trying to understand why there is a mismatch in the fresh build?

**Comment by StefanKelm** [comment]
We've been using mixbox 1.0.5 for ages and everything seems to work fine.

If noone disagrees I would make the necessary change in https://github.com/MISP/MISP/blob/2.4/app/Model/Server.php#L3298 and issue a PR.

PS: This is related to #6920

**Comment by SteveClement** [comment]
@chrisr3d can you bump the version please?

**Comment by chrisr3d** [comment]
I just updated the requirements, let me know or reopen the issue if you still get errors with this

**Comment by StefanKelm** [comment]
Hey @chrisr3d, thanks a lot but shouldn't it be `'mixbox' => '>1.0.4'`?

**Comment by chrisr3d** [comment]
It looks like the `>` is inclusive, the diagnostic is happy with it 
![image](https://user-images.githubusercontent.com/16307976/130802406-305050fc-d7ca-474d-992d-51b923a96011.png)

**Comment by StefanKelm** [comment]
Awesome! Thanks for the swift clarification, @chrisr3d
