### ISSUE TITLE
api add_ipsrc

### ISSUE THREAD

**Issue by r3dlight** [MISP/MISP#706]
I'm trying to add an ipsrc to an existing event but I cannot find out how to properly do it via the API. May I ask you to add a function like the following one (but add_ipsrc) ?

add_ipdst(self, event, ipdst, category='Network activity', to_ids=True, comment=None, distribution=None, proposal=False)

thanks

**Comment by r3dlight** [comment]
get.py just works fine for this event

**Comment by Rafiot** [comment]
Sure, fixed by: https://github.com/CIRCL/PyMISP/commit/d1db9a74eeaaf8e8f40ae924ebd5b7eade69d6b2
