### ISSUE TITLE
Enable "Send credentials automatically" for User Via API

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#7075]
Hi All,

i am trying to create new user using API and everything works fine.

However, i am not able to find any option for "Send credentials automatically"

Kindly let me know how to achieve this.

Here what i can see only:

`
  "mandatory_fields": [
        "email",
        "org_id",
        "role_id"
    ],
    "optional_fields": [
        "password",
        "external_auth_required",
        "external_auth_key",
        "enable_password",
        "nids_sid",
        "server_id",
        "gpgkey",
        "certif_public",
        "autoalert",
        "contactalert",
        "disabled",
        "change_pw",
        "termsaccepted",
        "newsread"
    ],
    "url": "\/admin\/users\/add"
`

Thanks.

**Comment by ahmedxuae91** [comment]
Hi Team, May i request you please if you can use this API query in any of your MISP systems that has postfix configured and confirm if you are receiving a welcome email after sending the below request?

curl -k https://URL/admin/users/add -H "Authorization:**********" -H "Content-Type: application/json" -H "Accept: application/json" --data '{ "email":"xxxx@xxx.xxx","autoalert":false,"contactalert":false,"role_id":"1","change_pw":"0","org_id":"1","termsaccepted":false}'

--------------
Update: tested and didn't get an email

**Comment by ahmedxuae91** [comment]
Hi Team, i was thinking about alternative solution if i can use password reset option after creating the user.

Do MISP support API for password reset?

**Comment by cudeso** [comment]
An alternative option is to create users with a default password and set it so that they are required to change it after first login (option 'change_pw'). Send the default password via another channel or via email.

Also have a look at REST call "/users/change_pw"
