### ISSUE TITLE
MISP with Suricata

### ISSUE THREAD

**Issue by yehias** [MISP/MISP#708]
how I can link MISP with suricata so can suricata running in IPS mode (af-packet) read files checksum from MISP and used with proper rule? thanks.

**Comment by yehias** [comment]
Please any help will be great

**Comment by iglocska** [comment]
MISP has an API for suricata that you can access at https://my_misp_url/events/nids/suricata/download

You need to use a user with the auth_key permission (superuser default role covers this) and to pass along your API key via the Authorization header. You can further refine what sort of data should be included via a set of parameters that you can pass via the URL or by POSTing it to the above url with the parameters as JSON or XML in the body. For further documentation on this, navigate to https://my_misp_url/events/automation.

Keep in mind that only network related indicators are included in the suricata API, so file hashes won't be in there. However, this could be interesting as an improvement to the suricata export.

**Comment by yehias** [comment]
OK great now I have issue I cant open MISP Web interface it redirect me to
suricata interface btw I have scirius on my debian so I installed MISP with
it

**Comment by iglocska** [comment]
That sounds like a misconfiguration of your apache - you could make MISP accessible on a different port or a subdomain.

For example, to have MISP listen on a different port, just edit your misp.conf file (from port 80 / 443) to a different port and make sure your apache listens on that port.

So if you change it to port 50000, you will be able to access suricata via https://your_url and MISP via https://your_url:50000

**Comment by yehias** [comment]
Can you assist me with that please? Thanks

**Comment by iglocska** [comment]
Is this system going to be internet facing or is it just for internal use?

**Comment by yehias** [comment]
It will be for internal use but of course it will have Internet connection
so it can be updated

**Comment by iglocska** [comment]
OK, in that case the easiest is to just use one of the conf files that
ships with MISP (/var/www/MISP/app/INSTALL/apache.misp for http and
apache.misp.ssl for https). Just copy it into your
/etc/apache2/sites-available directory as misp.conf.

To get it to be accessible via a different port, change the start of the
file from:

<VirtualHost 192.168.1.1:443>

to

Listen 50000
<VirtualHost *:50000>

After that, run the following:

a2ensite misp
service restart apache2

If you are using ssl make sure you point the config file to your
certificate files

**Comment by yehias** [comment]
Already made everything and stil working and btw on running a2ensite misp
it gibe me already enabled

**Comment by iglocska** [comment]
If you've made the changes to the config file, just restart apache2

**Comment by yehias** [comment]
So I changed port 80 to 5000 and did everything still I cant access it I
still access scirius and I tried to restart Apache even the Machine is
there anything else I can do?

**Comment by regit** [comment]
Hi @yehias 

What is you scirius related apache configuration ? It seems it takes precedence over the MISP configuration.

**Comment by yehias** [comment]
Im out of work tomorrow im gonna send you my httpd confirmation file and
really big thanks for your help in advance

**Comment by yehias** [comment]
@regit @iglocska  I just want to know thank you a lot I just figure out how since selks run on nginx and by default on port 80 and 443 this make misconfiguration therefore I just edit ports.conf for apache and let apache2 listen to desired ports and nginx on ports 80 and 443 I just have one question since my suricata run in IPS mode not IDS (af-packet) still my  suricata useful with MISP? if not I'm gonna to run bro IDS it's possible to link it with MISP? thanks in advance

**Comment by elhoim** [comment]
@yehias did you finish the integration? Did it work fine? Could share some details/comments about it?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
