### ISSUE TITLE
"Workers" stop working?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#709]
I've 3 sheduled tasks (the default ones). Two are disabled (frequence: 0) and one has a frequency of "1" (pull_all). Scheduled jobs are properly executed but after some time (non regular), the tasks is not executed anymore. If I go to the admin page and I restart all the workers, jobs are executed again until...
Any idea how to debug this?

/x

**Comment by iglocska** [comment]
Before you restart the workers, can you check if they have any jobs in the queue? This should be visible from the admin page (this will let us know whether it is the scheduler worker or the regular workers that are bugging out). 

Also, could you check the logs and error logs of the schedule worker and the regular workers from the timeframe when they stopped working?

**Comment by adulau** [comment]
@xme any news?

**Comment by Rafiot** [comment]
@xme Can we close the ticket?

**Comment by elhoim** [comment]
No answer, closing. Please re-open if you still have trouble.
