### ISSUE TITLE
No data from API call when requesting timestamp range.

### ISSUE THREAD

**Issue by erpatrik** [MISP/MISP#7096]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.139, (add5882d8b9bbc1de1b21d137e723d01be1e6dce)

### Expected behavior
When requesting attributes via an API with timestamp=['2021-01-01','2021-01-30'] I should get attributes with timestamp between specified two dates. (It works same with timestamp=['60d','30d'] and so on with epoch)

### Actual behavior
It does not return anything, if event.timestamp is NOT in the requested interval, because of the SQL query. (I did debug and you can see the problem in attached screenshots).

### Steps to reproduce the behavior
Have an event with different event.timestamp than you are requesting in API call.
For example if you want attributes between timestamp>=1609527635 and timestamp<=1612119635 and your event has timestamp=1614263518 it will return nothing.

### Logs, screenshots, configuration dump, ...
PyMISP call - `pymisp.search(return_format='csv', controller='attributes', eventid=2606, timestamp=['2021-01-01', '2021-01-30'])`
![image](https://user-images.githubusercontent.com/1679305/109208606-ccdb4580-77aa-11eb-816a-e80567a92e5c.png)

**Comment by mokaddem** [comment]
Hi @erpatrik,
It's fixed on the develop branch.
`timestamp` filtering conditions on attributes will no longer propagates to event.
Thanks for the feedback!

**Comment by erpatrik** [comment]
Thanks for it!
Will try to check it!
