### ISSUE TITLE
Error while exporting to CSV (includeContext=true)

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#710]
Hi all,

While this one is exported successfully  (includeContext=false)
https://XXX/events/csv/download/false/false/false/false/false/false/false/false/30d/

The following one is not (includeContext=true):
https://XXX/events/csv/download/false/false/false/false/false/true/false/false/30d/

The output is the following:
Notice (8): Undefined offset: 4 [APP/Model/Event.php, line 1062]
Code Context
Event::attachEventInfoToAttributes() - APP/Model/Event.php, line 1062
Event::csv() - APP/Model/Event.php, line 1026
EventsController::csv() - APP/Controller/EventsController.php, line 1950
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by iglocska** [comment]
Will have a look at this tomorrow, sounds like a bug.

**Comment by advancedeng** [comment]
Works like a charm ;). Thanks!!

Cheers,
Andreas

**Comment by advancedeng** [comment]
The event_info filed in the exported CSV causes some troubles e.g. some new line characters break the CSV. 
See example   uuid   5638f0c3-177c-4a36-953b-338218689696  in CIRCL's MISP instance.

**Comment by iglocska** [comment]
Thanks for the heads up, will push a fox asap

**Comment by advancedeng** [comment]
Thanks Andras

**Comment by advancedeng** [comment]
I appreciate the speed that you provided the fix. Also love the fact that comment filed was added ;)

Thanks again, 
Andreas

**Comment by iglocska** [comment]
Hehe, completley missed that it wasn't there until I was playing around
with it :) Let me know if you run into anything else!

Best regards,
Andras
