### ISSUE TITLE
Maximum execution time of 30 seconds exceeded 

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#711]
Hi again,

Is there a way to set the maximum execution time while trying to export via the API?

Thanks in advance,
Andreas

**Comment by iglocska** [comment]
It is controlled by the max execution time set in your php.ini, just raise
that and you should be fine. Which api is causing  this and how many
attributes does your instance have?

**Comment by advancedeng** [comment]
I was trying to extract a CSV (with includeContext-true) for the whole dataset (all attribute ~  211199 total)

**Comment by iglocska** [comment]
Give it another shot, includeContext was bugged - should be fixed if you git pull. If it still times out let me know!

**Comment by advancedeng** [comment]
Works again like a charm :)

Thansk again,
Andreas

**Comment by iglocska** [comment]
Excellent! :)
