### ISSUE TITLE
How to customize MISP Web GUI Theme

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#7110]
Hi,

in the MISP guide i found this:

> To replace the current theme with a theme you found on bootsplash, run: wget https://bootswatch.com/2/readable/bootstrap.css -O /var/www/MISP/app/webroot/css/bootstrap.css , replacing the URL as needed.

I did as indicated, but i could not change my theme.

In particular, i tried to upload this one: https://bootswatch.com/2/amelia/

So I expected to have an interface like the one reported, but instead nothing happened.

Can someone provide a correct guide for how to change the default MISP theme with another one?

Thanks,
Pietro

**Comment by pietrogu** [comment]
Anyone?

**Comment by Wachizungu** [comment]
For me it works as described, I did:

sudo -u www-data wget https://bootswatch.com/2/amelia/bootstrap.css -O /var/www/MISP/app/webroot/css/bootstrap.css

and now my eyes are burning :)

What is the output you get from the command? is /var/www/MISP the directory you installed MISP in? Which OS are you using?

**Comment by Wachizungu** [comment]
@pietrogu any update?

**Comment by pietrogu** [comment]
Hi, i am using Ubuntu 18.04 and MISP is updated to latest version
Actually i didn't specify the user www-data, i'll try it :)

**Comment by pietrogu** [comment]
It worked!

Thank you!
