### ISSUE TITLE
MISP/app/Console/cake Server pushAll [user_id] [full|update]

### ISSUE THREAD

**Issue by garrit-schroeder** [MISP/MISP#7115]
**Is your feature request related to a problem? Please describe.**
I like to pull and push to/from every sync server via a crontab. A pullAll Method is available in cake but what about a pushAll method?

**Describe the solution you'd like**

I like to have the possibility to pushAll from cake. Because I am not aware of added sync servers and want to the crontab to function always. Using the push id server_id is not really an option for me.

**Describe alternatives you've considered**

**Additional context**

**Comment by garrit-schroeder** [comment]
Is this a good idea to add, or not?

**Comment by garrit-schroeder** [comment]
And  MISP/app/Console/cake Server list seems to be broken. Depending on the output of this command this could be a workaround for me. 

![image](https://user-images.githubusercontent.com/12541078/109638973-eb489480-7b4e-11eb-8a64-bdaf1e82029c.png)

**Comment by iglocska** [comment]
Added the list function, output looks like this:

Server #3 :: misppriv :: https://misppriv.circl.lu
Server #31 :: 2021 Training instance :: https://iglocska.eu

There's also the older (mislabeled) listing via `cake Server listServers`, which produces a JSON of the same data.
