### ISSUE TITLE
EventTag does not have an effect when creating new events

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#7118]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| MISP version / git hash   | 2.4.139

### Expected behavior

Supplying the tags in EventTag adds the tags when creating an event.

### Actual behavior

Event is created but EventTag is ignored.

```
curl \
 -d '{"info":"new","EventTag":["PAP:WHITE"]}' \
 -H "Authorization: ABC" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 -X POST https://MISP/events/add
```

**Comment by mokaddem** [comment]
Hey,
Sorry for the late reply.
The `EventTag` key expect a list of `Tag` with the MISP's `Tag` format.

So, the correct format is the following:
```json
{
    "info": "new",
    "EventTag": [
        {"Tag": {"name": "PAP:WHITE", "colour": "_optional_"}}
    ]
}
```
