### ISSUE TITLE
Incorrect PHP Version in install.sh

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7121]
Work environment

| Type of issue | Support
| OS version (server) | Ubuntu OS
| OS version (client) | Ubuntu, 18.04 LTS
| MISP version / git hash | 2.4.138, hash of the commit
| Browser | Google Chrome

### Expected behavior

Php 7.2 installation over install.sh script from MISP documentation. php 7.4 is the recommended version upon successful installation.
Ideally, MISP install.sh should deploy the right PHP version.

### Actual behavior

Install version of PHP should be >7.4 in the recommended MISP installation. 

https://misp.github.io/MISP/INSTALL.ubuntu1804/

### Steps to reproduce the behavior

Followed instruction as per MISP install documentation. 

https://misp.github.io/MISP/INSTALL.ubuntu1804/

**Comment by SteveClement** [comment]
I see the concern, but as it is only a warning and a good solution would require too much tinkering, I mark this as wontfix.
