### ISSUE TITLE
MISP Module Installation Failure: Declared Panda Version Incorrect

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7122]
Work environment

| Type of issue | Support
| OS version (server) | Ubuntu OS
| OS version (client) | Ubuntu, 18.04 LTS
| MISP version / git hash | 2.4.138, hash of the commit
| Browser | Google Chrome

### Expected behavior:

Panda package version obsolete in the default installation script recommended by CIRCL. As per "REQUIREMENTS" alphabetic sequence any module after "Panda" fails to install because pip searches for Panda version 1.2.1 and fails to get this version. 

Script used: sudo -H -u www-data /var/www/MISP/venv/bin/python3 -m pip install -I -r REQUIREMENTS

ERROR:
![Panda Error](https://user-images.githubusercontent.com/54234520/109642301-3a50f280-7b6c-11eb-9876-5a7b385b2b20.png)

**Comment by SteveClement** [comment]
@chrisr3d can you confirm?

**Comment by War10ck3** [comment]
@chrisr3d - I've faced similar issues moving from v2.4.137 to the latest version 2.4.140 using **Update MISP** button in the diagnostic tab. Please refer to the below screenshot:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54234520/111439397-c5121f80-871e-11eb-8d2d-e9f7c8e82fc0.png)

Also, I'd like to indicate that if I click on "**Update MISP**" once again after the above I see that PyMISP status in the "**Submodule Version**" is **OK** while the error in green text last line states **Failed to recurse into submodule path 'PyMisp'**.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/54234520/111440301-a3fdfe80-871f-11eb-9fed-74bfc10a2eb5.png)

**Comment by SteveClement** [comment]
This should be fixed by now.
