### ISSUE TITLE
Admin UI fails to detect running workers

### ISSUE THREAD

**Issue by seanthegeek** [MISP/MISP#713]
![UI Screenshot](https://i.imgur.com/r69oJie.png)
------------------------------------

    $ ps -aux | grep MISP
	misp     21428  0.0  0.0  12484  2800 ?        S    11:54   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='default'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14472608738766'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
	misp     21446  0.0  0.0  12484  2792 ?        S    11:54   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14472608742512'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
	misp     21464  0.0  0.0  12484  2796 ?        S    11:54   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='email'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/1447260874625'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
	misp     21482  0.0  0.0  12484  2800 ?        S    11:54   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler';     VERBOSE=true  QUEUE='default'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14472608749997'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=3  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque-scheduler.log'  php './bin/resque-scheduler.php'  >> '/var/www/MISP/app/tmp/logs/resque-scheduler-error.log'  2>&1
	misp     21611  0.0  0.0  18020  2888 ?        S    11:57   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14472610349311'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
	misp     21659  0.0  0.0  18020  2888 ?        S    11:59   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/14472611550202'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1

-----------------------

All error logs are blank.

**Comment by seanthegeek** [comment]
Any suggestions on how to debug this? Being new to all things PHP, I have no idea.

**Comment by iglocska** [comment]
Hello Sean,

I'll look into this over the weekend, sorry for the slow response, am a bit
swamped atm. Which Linux distro / version are you on and which MISP version
are you running?

Best regards,
Andras

**Comment by seanthegeek** [comment]
I'm running Ubuntu Server 15.10. I have other applications running on that server, so my setup is a little unique.

- Apache for MISP is behind a NGINX reverse proxy, which causes MISP to think the base URL is set wrong, even though I'm passing the host name

    location / {
            proxy_pass http://127.0.0.1:8042;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

- I'm running my own compiled Redis 3.0.5 to have the latest bug fixes
- The workers are run by a `misp` user that I created, because `www-data` does not have a shell set in later versions of Ubuntu for security reasons. The files in `/var/www/MISP are owned by `www-data:misp`, and the group has read/write access

**Comment by seanthegeek** [comment]
*bump* any updates?

**Comment by 4formaggi** [comment]
Hi,

I have the same problem with current version of misp (v2.3.177) but I'm using Ubuntu 14.04 into a docker container.

The workers are active but the UI is not able to detect them ... I gave a shell to www-data user (which is not so great) to be able to launch the workers ... no log errors and problems in the diagnostic tabs.

I even checked the permissions on /proc folder as www-data user and again no problems. 

Do you have any suggestions guys ?

Thank you so much

**Comment by iglocska** [comment]
seanthegeek, that is indeed a very custom setup, there are several things in there that I have never tested. As for the workers not being detected correctly, that is expected since you are running the workers and apache off of different users. The way that MISP checks on the worker process is by looking for the PID in /proc - something that won't be visible to the apache user if it was started by the misp user. It should however not affect whether it runs or not, just the diagnostic tool. Are things working fine otherwise?

4formaggi: That sounds weird, your issue sounds different from seanthegeek's. Do you have the open_basedir directive set?

**Comment by 4formaggi** [comment]
Hi iglocska,

Thank you for your timely response, I agree that my problem sounds different ... open_basedir is not set in my php.ini.
Basically, as I said, I set a shell (/bin/bash) to the www-data user and I'm able now to spawn processes from it (even manually with the command su www-data -c 'bash /var/www/MISP/app/Console/worker/start.sh'). I'm even able to restart the workers from the UI, but still It's not working.

You're that It seems so weird ...

**Comment by 4formaggi** [comment]
You're right ... that It seems so weird. My workers tab is like the screenshot above.

**Comment by rfortress** [comment]
@4formaggi can you share your Dockerfile? eg5846's fails to build. (https://hub.docker.com/r/eg5846/misp-docker/)

**Comment by the4tress** [comment]
@4formaggi can you share your Dockerfile? [eg5846](https://hub.docker.com/r/eg5846/misp-docker/)'s fails to build.

**Comment by xme** [comment]
+1 for the Docker file.
I'm also investigating the way to run MISP in a Docker... Let's put our efforts together?

**Comment by 4formaggi** [comment]
I made a fully functional Docker image ... Let me remove some personal information and I'll share it with you guys. The trick is to follow the official installation guide and install some extra packages that are not present in the default OS Docker images (e.g. Ubuntu 14.04) .

Eu

**Comment by seanthegeek** [comment]
Forgot to follow up to say that the workers are indeed working fine on my setup.

Looking at the code, I should see an error about the workers not running as the correct user, but the UI does not detect the running workers at all. Maybe something changed with /proc in Ubuntu 15.10?

**Comment by xme** [comment]
FYI,
I'm also working on a docker image (fully automated build). I should be able to share it today or tomorrow.

@4formaggi: We could cross check our setup?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
