### ISSUE TITLE
"Could not update Taxonomies" via cake 

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#7132]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP        | 7.4.3
| MISP version / git hash   | 2.4.139

### Expected behavior

Updating the taxonomies via cake should be succesful.

### Actual behavior

Updating taxonomies via cake returns an error.

### Steps to reproduce the behavior

```
root@misp:/var/www/MISP/app/Console# sudo -u www-data ./cake Admin updateTaxonomies

Welcome to CakePHP v2.10.24 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Could not update Taxonomies
```

Updating the taxonomies via the web interface works.

Updating the taxonomies via `sudo -u www-data ./cake Admin updateJSON` also works

```
...
Galaxies updated.
Noticelists updated.
Warninglists updated.
Taxonomies updated.
ObjectTemplates updated.
...
```

**Comment by mokaddem** [comment]
Thanks for the feedback!
It's fixed on develop branch
