### ISSUE TITLE
Incorrect file permissions

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#7134]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4.3
| MISP version / git hash   | v2.4.140 (2e4ff3837783ed71c4c15cf05414e72801928df4)
| Browser                   | Chrome
### Expected behavior
If change config values from web page not change or set correct file permissions to 640

### Actual behavior
config.php file permissions set to 644

### Steps to reproduce the behavior
Change any config parameter. In Diagnostics window Security Audit section show:

File permissions config.php config file is readable for any user.

**Comment by SteveClement** [comment]
dupe
