### ISSUE TITLE
Mistspell Security Audit message

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#7135]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4.3
| MISP version / git hash   | v2.4.140 (2e4ff3837783ed71c4c15cf05414e72801928df4)
| Browser                   | Chrome

### Expected behavior
Browser cache is enabled. Attacker can obtain sensitive data from user cache. You can disable cache by setting `Security.disable_browser_cache` to `true`.

### Actual behavior
Browser cache is enabled. Attacker can obtain sensitive data from user cache. You can disable cache by setting `Security.disable_browser_cache` to `false`.

**Comment by JakubOnderka** [comment]
Fixed, thanks!
