### ISSUE TITLE
Error when import event in json format via REST API 

### ISSUE THREAD

**Issue by Tyrell20** [MISP/MISP#7136]
Hello,

I'm trying to import a MISP Export File in json format via REST API. 

When the same event is imported via web interface or via CURL in XML format works fine but when importing the json format with CURL it fails. 

Please could you give me some clue? Thanks in advance.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Red Hat Enterprise Linux Server release 7.9 (Maipo)
| MISP version / git hash   | 2.4.139

### Logs, screenshots, configuration dump, ...
#curl  -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: auth_key" --data @2220067.json -k -X POST https://misp_hostname/events

HTTP/1.1 403 Forbidden
Date: Wed, 03 Mar 2021 10:09:52 GMT
Strict-Transport-Security: max-age=31536000; includeSubdomains;
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.2.27
Set-Cookie: MISP-5ed76dda-6dd0-43e5-a3cb-112c0a1ea115=e6vig9fa81gvq8sb86lo678i8g; expires=Wed, 03-Mar-2021 11:09:52 GMT; Max-Age=3600; path=/; secure; HttpOnly
Set-Cookie: MISP-5ed76dda-6dd0-43e5-a3cb-112c0a1ea115=e6vig9fa81gvq8sb86lo678i8g; expires=Wed, 03-Mar-2021 11:09:52 GMT; Max-Age=3600; path=/; secure; HttpOnly
Content-Length: 243
Content-Type: application/json; charset=UTF-8

{
    "saved": false,
    "name": "Could not add Event",
    "message": "Could not add Event",
    "url": "\/events\/add",
    "errors": {
        "Event": {
            "info": [
                "valueNotEmpty"
            ]
        }
    }
}

**Comment by cudeso** [comment]
This might be related to https://github.com/MISP/PyMISP/issues/533#issuecomment-788258194

**Comment by cudeso** [comment]
As temporary workaround I filter it in a Python script with `event = json.loads(e)['response'][0]`

**Comment by Tyrell20** [comment]
> This might be related to [MISP/PyMISP#533 (comment)](https://github.com/MISP/PyMISP/issues/533#issuecomment-788258194)

Hello cudeso,
I think it is a different problem because with CURL I have error even editing the exported JSON and removing "Response" tag (error message: invalid json).
Unfortunately I can import the events only with CURL because in my system I can't use python.
Thank you

**Comment by Tyrell20** [comment]
Hello,
just for information, the problem seems still present with the 2.4.140 MISP version also.
Thank you

**Comment by chrisinmtown** [comment]
Did you check the server's error.log file?  Also you might want to post the JSON that fails to load, after removing proprietary info of course.

**Comment by Tyrell20** [comment]
On "/var/www/MISP/app/tmp/logs/error.log" no error.

Attached the json (renamed in txt and anonymized) that I'm trying to add on MISP with the following command:
`curl  -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: Auth_Key" --data @2221889.json -k -X POST https://misp-hostname/events/add.
`

[2221889.txt](https://github.com/MISP/MISP/files/6110997/2221889.txt)

Thank you

**Comment by chrisinmtown** [comment]
The data file 2221889.txt has an outer tag "response" with a list. Possibly the server looks for an object containing the key "Event" and if that's not present, simply does nothing?  Try removing that outer object.

**Comment by Tyrell20** [comment]
I already tried this solution (as suggested by @cudeso  and indicated on https://github.com/MISP/PyMISP/issues/533#issuecomment-788258194) but I receive the following error:

{"name":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","message":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/events\/add"}

In addition, as indicated by @cudeso, the Response tag is present in both MISP XML and MISP JSON "Download as...".

Thank you

**Comment by chrisinmtown** [comment]
You might post here exactly the JSON input that you tried.  Perhaps it truly is invalid?  Obviously there's no sense sending non-parseable JSON to the server with CURL.

**Comment by iglocska** [comment]
I can confirm, this works fine with the current version as long as you indeed strip the encapsulation.

````
{
  "response": [
    {
      "Event": {
        // ...
       }
    }
  ]
}
````

Needs to be converted to 

````
{
  "Event": {
     //...
  }
}
````

Be mindful of the response being a list, so in addition to removing {"response": ... } you also need to remove the list []. You have probably forgotten to remove one of the two from the end of the document hence it not producing a valid JSON.

**Comment by Tyrell20** [comment]
Hello @iglocska,

you're right, I forgotten to remove one bracket from the end of the file, now it works.

Anyway, it is correct that the system will not allow me to import the file as it is exported directly from MISP (with  {"response": ... }?

Thank you

**Comment by Tyrell20** [comment]
Hello @iglocska,

any feedback about this?
Thank you

**Comment by iglocska** [comment]
That's correct, the response part needs to be stripped. There is an import event endpoint with which it should work.

**Comment by Tyrell20** [comment]
Perfect, many thanks
