### ISSUE TITLE
Database schema issue

### ISSUE THREAD

**Issue by dpreuveneers** [MISP/MISP#7137]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.140

### Expected behavior

After upgrading MISP, the diagnostics tool reports that the database schema is inconsistent, but the 
the recommended action to fix the schema does not work.

### Actual behavior

The MariaDB client returns an error when attempting to manually fix the schema.

### Steps to reproduce the behavior

The recommend action to fix the schema is: 
`ALTER TABLE cerebrates MODIFY COLUMN description text DEFAULT "NULL" NULL COLLATE utf8mb4_unicode_ci ;`

The MariaDB client returns the error message: 
`ERROR 1101 (42000): BLOB/TEXT column 'description' can't have a default value`

Not sure if this is a proper fix, but the https://github.com/MISP/MISP/blob/2.4/db_schema.json file defines at line 710 for the `description` column in `cerebrates` a `column_default` property with the value `"NULL"` (i.e. with double quotes). After changing `"NULL"` to `null`, i.e. similar to other columns, the schema inconsistency is gone.

**Comment by enjeck** [comment]
Duplicate of #7137. Closing this one since it has fewer comments.

**Comment by chrisinmtown** [comment]
This may have fewer comments than #7200 but it has better information/diagnosis of the problem. :/

**Comment by enjeck** [comment]
@chrisinmtown Good point. I'll copy the details from here into a comment at #7200
