### ISSUE TITLE
Broken travis build

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#714]
For some reason, the build on travis is broken: https://travis-ci.org/MISP/MISP/branches

No idea why, but has to be fixed.

**Comment by adulau** [comment]
It seems to be just after the update of the PyMISP submodule.

**Comment by iglocska** [comment]
Just took a quick look, it could be this assertion:

        to_check = {u'Event': {u'info': u'This is a test', u'locked': False,
                               u'attribute_count': u'0', u'analysis': u'0',
                               u'ShadowAttribute': [], u'published': False,
                               u'distribution': u'0', u'Attribute': [],
u'proposal_email_lock': False,
                               u'threat_level_id': u'1'}},

attribute_count seems to be null not u'0' when no attributes are present.
Just a guess though at first sight.

**Comment by iglocska** [comment]
Never mind. I think it's simply that the assertion is lacking a bunch of dynamically created fields.

`{u'Event': {u'info': u'This is a test', u'locked': False, u'uuid': u'5645a9a8-b9bc-468b-8af0-0e68c0a8380d', u'timestamp': u'1447405992', u'attribute_count': u'0', u'RelatedEvent': [], u'analysis': u'0', u'orgc': u'CIRCL', u'ShadowAttribute': [], u'published': False, u'date': u'2015-11-13', u'org': u'CIRCL', u'distribution': u'0', u'Attribute': [], u'proposal_email_lock': False, u'id': u'278', u'threat_level_id': u'1', u'publish_timestamp': u'0'}}`

vs 

`{u'Event': {u'info': u'This is a test', u'locked': False,
                               u'attribute_count': u'0', u'analysis': u'0',
                               u'ShadowAttribute': [], u'published': False,
                               u'distribution': u'0', u'Attribute': [], u'proposal_email_lock': False,
                               u'threat_level_id': u'1'}}`

**Comment by iglocska** [comment]
My bad, I am blind, just saw _clean_event :)

**Comment by Rafiot** [comment]
Yeah, I guess it is related to the update of PyMISP, but I cannot understand why. I'll look at it later.

**Comment by iglocska** [comment]
Pull request sent.

**Comment by adulau** [comment]
Fixed
