### ISSUE TITLE
Redis password not used

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#7143]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4.3
| MISP version / git hash   | v2.4.140 (9f18cec0ca48533eb8e590717cd1e00232a179a6)
| Browser                   | Chrome

### Expected behavior
Set password in redis server. Set password for redis in config file directly on from web interface. Web page continue working as normal

### Actual behavior
If set password in MISP there is no changes. Only no error message in Diagnostics and Security Alert section. In Redis info section get error:
PHP extension version: 5.1.1
Redis is not available. Could not authenticate to Redis: ERR Client sent AUTH, but no password is set

When set password in redis server get internal error.
![Screenshot from 2021-03-03 16-04-31](https://user-images.githubusercontent.com/4244630/109820055-51134a00-7c3d-11eb-8b90-306ee9bae986.png)

### Steps to reproduce the behavior
Set password in redis server.

### Error log
```
2021-03-03 15:59:43 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 126]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
ResqueStatus\ResqueStatus::getWorkers() - APP/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 126
Server::workerDiagnostics() - APP/Model/Server.php, line 3391
ServersController::serverSettings() - APP/Controller/ServersController.php, line 1145
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2021-03-03 15:59:43 Error: [RedisException] NOAUTH Authentication required.
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(153): Redis->lLen()
#1 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(342): Resque::size()
#2 /var/www/MISP/app/Model/Server.php(3432): CakeResque::getQueueSize()
#3 /var/www/MISP/app/Controller/ServersController.php(1145): Server->workerDiagnostics()
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#9 {main}
```

**Comment by JakubOnderka** [comment]
Hello, you have to also set this password to CakeResque  config, that is located in `/var/www/MISP/app/Plugin/CakeResque/Config/config.php`.

**Comment by Turecky** [comment]
Thanks for hint. 
Now all works!!!

**Comment by hack2802** [comment]
Hello. Please I have the same issue. In my case i set the redis passwaord from the redis-cli command line. I set the same password in the /var/www/MISP/app/Plugin/CakeResque/Config/config.php file using single cote like 'mypassword'. But the error page is still there. Can some one help please.
![image](https://user-images.githubusercontent.com/77747905/193109545-2fc0b986-000a-4335-9e7b-68c3ca1daf47.png)
