### ISSUE TITLE
Finding back the relationship between an auth key and an user

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#715]
I would like to find back the link between an API key and an user:

~~~~
609062  	SYSTEM  	SYSTEM  	2015-11-15 10:04:41  	auth_fail  	Failed authentication using API key (AbracaDaBra)
~~~~

The issue is the following. As a user can request the change of an auth key, we cannot find back which key was compromised/abused and to who the auth key was linked.

We have maybe two options to solve this issue:

- (without changing the data model) Logging all change of auth key in the system to keep track of the changes of any auth key (from - to). Then we can search in the audit log directly to who the key was previously assigned to.

- (changing the data model) In the users table, we keep a trace of all the auth key assigned to  a user.

I'm more in favour in the first option which just a matter of audit logs without increasing the complexity of the data model.

**Comment by RichieB2B** [comment]
Doesn't it make more sense to make a new table to link all issued api keys to a userid + username + timestamp when issued?

**Comment by iglocska** [comment]
Both options work, though as Alexandre mentioned, if we can avoid changing
the datamodel on a hotdogs then I'd be in favour of that option

**Comment by iglocska** [comment]
Hotfix, not hotdogs, sank autocorrect

**Comment by adulau** [comment]
Ok so option one for the hotdog^H^H^Hhotfix in 2.3 and maybe 2.4-hotfix for the more advanced audit logs in the database as mentioned by Richard.

**Comment by iglocska** [comment]
Sounds good!
