### ISSUE TITLE
Financial indicators: improvement to display lookup of bank identification number

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#716]
A public repository of Issuer Identification Numbers (IIN) also called the "Bank Identification Numbers" (BIN) for the debit/credit cards is available:

- https://github.com/binlist/binlist-data

For the IBAN prefixes or BIC/SWIFT numbers, it seems there is no public and open database. If someone has a pointer, let us know.

**Comment by advancedeng** [comment]
To my knowledge there is no such open database. It may worth reaching Team Cymru for more information on IINs -> http://www.team-cymru.org/BIN-Feed.html

**Comment by adulau** [comment]
Here is a list of SWIFT bank code that we could use:

https://github.com/PeterNotenboom/SwiftCodes

**Comment by adulau** [comment]
The SWIFT codes are now available in this repo as JSON and could be used as a submodule in MISP:

https://github.com/MISP/SwiftCodes
