### ISSUE TITLE
Freetext import doesn't support bracketed value

### ISSUE THREAD

**Issue by mokaddem** [MISP/MISP#7163]
Freetext import doesn't support bracketed value.
Example: (2.2.2.2)

**Comment by iglocska** [comment]
Fixed on develop

**Comment by StefanKelm** [comment]
related to #6386 ? ;)

**Comment by JakubOnderka** [comment]
@mokaddem Can you provide exact example? It should be already supported, I just tested.

@iglocska Brackets should be already removed in https://github.com/MISP/MISP/blob/4a4722a30c24a556e382581c2ce8df432a5bae33/app/Lib/Tools/ComplexTypeTool.php#L206

**Comment by iglocska** [comment]
Indeed, it looks like the issue had to do with the trailing period, when a bracketed value was at the end of a sentence.

`we also saw an IP address (8.8.8.8).`

This is resolved by the patch, however, the bracket removal indeed shouldn't be needed.
