### ISSUE TITLE
When pushing event, sharing group is not created

### ISSUE THREAD

**Issue by JakubOnderka** [MISP/MISP#7165]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.140

### Expected behavior

When pushing event from instance `A` to `B` with Sharing group `SG` that doesn't exists on instance `B`, sharing group `SG` is created at instance `B` and event is attached to that sharing group.

### Actual behavior

When pushing event from instance `A` to `B` with Sharing group `SG` that doesn't exists on instance `B`, sharing group `SG` is **not** created at instance `B` and event is attached to distribution **Organisation only**.

### Steps to reproduce the behavior

This happens after instance `B` was updated to 2.4.140. I think that the problem is this condition:

https://github.com/MISP/MISP/blob/4a4722a30c24a556e382581c2ce8df432a5bae33/app/Model/SharingGroup.php#L716

Sharing group `SG` has `releasability` field empty, since it is not required. Is this intentional?

**Comment by iglocska** [comment]
As discussed offline - indeed this looks like a bug. I always assumed that releasability was mandatory, looks like it's not. So best to relax the requirement.
