### ISSUE TITLE
Azure AD module reports errors at https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token, 400 Bad Request

### ISSUE THREAD

**Issue by sdzhangtao** [MISP/MISP#7169]
I followed the document on App registration. However each time I choose Login with Azure AD, after being forwarded to Azure for authentication, after successful authentication, it was forwarded back to MISP login page again. 

https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token was requested three times based on server log. The first time was OK, access token was granted. However errors reported on 2nd and 3rd time.

The server side log displays following error message.

file_get_contents(https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]

I managed to get the detailed error message.

2021-03-07 04:13:06 Warning: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 87996aab-255e-45dc-9ecd-8306c2e81100\r\nCorrelation ID: cfa6bccb-ef8f-4c7f-a29c-9a5c5e07027d\r\nTimestamp: 2021-03-07 04:13:07Z","error_codes":[54005],"timestamp":"2021-03-07 04:13:07Z","trace_id":"87996aab-255e-45dc-9ecd-8306c2e81100","correlation_id":"cfa6bccb-ef8f-4c7f-a29c-9a5c5e07027d"}

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       Ubuntu
| OS version (client)      Win10
| PHP version               5.5
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior
I should be able to login with Azure AD

### Actual behavior

I was forwarded back to MISP login page again.

**Comment by sdzhangtao** [comment]
I think I found the problem, I was using my own Azure subscription for testing. I assume the gmail address I sign into Azure is the same as the user name I should register for MISP.

After some painful debugging,  the userPrincipalName is returned from Azure is admin@xxxxxxx.onmicrosoft.com
The onmicrosoft.com is the email that I have to register for MISP

**Comment by legoguy1000** [comment]
Sounds like this could be closed and maybe an update to the documentation would be the best remedy for this.
