### ISSUE TITLE
Can't download events when using Apache authentication

### ISSUE THREAD

**Issue by iwitz** [MISP/MISP#7178]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL 7
| OS version (client)       | Windows 10
| PHP version               | 7.3
| MISP version / git hash   | 2.4.140
| Browser                   | Any
| Server   | Apache 2.4.6 

### Expected behavior
Events can be downloaded.

### Actual behavior
Events cannot be downloaded because the user's API key isn't sent to the server.

### Steps to reproduce the behavior
* Enable Apache authentication
* Login to MISP
* Try to download an event

### Logs, screenshots, configuration dump, ...
When using Apache authentication with the ApacheSecureAuth module (but I'd assume the issue exists anytime Apache authentication is used), an event cannot be downloaded in the "View event -> Download as" button, no matter the download type.
The error message is "**Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.**"

I analyzed the headers :
1. The client sends "Authorization: Basic XXXX" with XXX being the auth token received from Apache during the initial login
2. If I edit it to 'Authorization: YYY" with YYY being the current user's API key, the request is denied by Apache
3. If I disable Apache authentication on the requested route only ( /events/eventSearch ) the client still sends the wrong header and the aforementioned error message appears.
4. If I both edit the header and disable Apache authentication on the route, the download works

As far as configuration goes, I can configure Apache not to require basic authentication on the routes that require an API key to be sent ; however, I'd still end up in situation 3 where clients would be required to edit the headers sent by their browsers to be able to download events. For the issue to be fixed entirely it seems some code might need to change.

It seems to me that the issue is that once an Authorization header is sent by a client, the MISP server-side code reuses it, in some cases as if it were an API key. It seems like the `__loginByAuthKey()` function in `/var/www/MISP/app/Controller/AppController.php`  might be guilty ? 

Also, **important :** normal API requests and API requests through the built-in API client work (since the header is properly set).

Here's the relevant part of my Apache configuration file in situation 2 :

```
# Forward Authentication header
        <IfModule !mod_php5.c>
                SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
                DirectoryIndex /index.php index.php
                <FilesMatch \.php$>
                        SetHandler "proxy:fcgi://127.0.0.1:9000"
                </FilesMatch>
        </IfModule>

        <Location />
                # For API requests (where an Authorization header is already provided), skip Basic authentication
                <If "-n %{HTTP:Authorization} && ! %{HTTP:Authorization} =~ /Basic/ ">
                </If>
                <Else>
                        AuthType Basic
                        AuthBasicProvider ldap
                        LDAPReferrals Off
                        AuthLDAPBindDN "myuser"
                        AuthLDAPBindPassword "mypassword"
                        AuthLDAPURL "myurl"
                        RequestHeader set REMOTE_USER %{AUTHENTICATE_uid}e
                        Require valid-user
                </Else>
        </Location>
```
 
And in situation 3 I just add the following snippet before the configuration above :
```
<Location "/events/restSearch">
    Allow from all
</Location>
```

**Workaround :** The "Security.allow_unsafe_apikey_named_param" configuration key looks like it may :

- Allow downloads to work in situation 3
- It should even allow downloads to work without having to add specific permissions to some paths such as /events/restSearch since the Authorization header and the API key could be sent simultaneously. It doesn't solve the bug at hand but it would still be an okay workaround.

However, either this parameter doesn't do what I thought it might or it doesn't work, I'll create another issue about it.

**Comment by iwitz** [comment]
The issue was introduced between 2.4.136 and 2.4.139, I was able to downgrade to version 2.4.136 and the download worked. It doesn't work in 2.4.139.
I can't say for versions 2.4.137 and 2.4.138 because when I try to downgrade to those, MISP gets stuck on a refresh loop.

**Comment by patriziotufarolo** [comment]
This was the very same as #7128 I created.
Unfortunately my patch makes some authentication plugins not to work correctly, because of conflicting approaches in the implementation of the authentication flows

**Comment by iwitz** [comment]
@patriziotufarolo It is indeeed, thank you. I didn't find it when looking for similar problems. I will close this issue since it is a duplicate.
