### ISSUE TITLE
Event attribute filtered by allowedlist in search, not filtered in get_event results

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7209]
Attributes returned when fetching an event by ID are different when processed by get_event vs search. Our MISP server's allowedlist has a pattern for "google.com".  An event has an attribute with "google.com" in its value. When I use get_event, the event's attr list is complete.  When I use search, the event's attr list is incomplete. Just to be sure, I checked the server's debug.log and error.log files, there is no entry at the time I run my queries.

I'm not quite certain whether this is a bug or a feature. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL 7
| OS version (client)       | Linux
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | If applicable

### Expected behavior

I expect the number of items in the Attribute collection to match the attribute_count field.

### Actual behavior

The number of items in the Attribute collection is different than the attribute_count field.

### Steps to reproduce the behavior

* Add an entry to the allowed list such as /google.com/. 
* Add a new event
* Add an event attribute with a value that matches an entry in the allowed list
* Search for that event by ID using code pasted below
* Get that event using by ID code pasted below

The results are different for me.

Here's the first bit of code, get_event.py, it always returns the attribute (ignores the allowedlist):
```
#!/usr/bin/env python3
import urllib3
from pymisp import PyMISP


urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(
    url='https://misp.my-company.com:48752',
    key='key',
    ssl=False)
print('Fetching event')
event = misp.get_event(event='223461', pythonify=False)
print('Event key=val:')
for key, val in event['Event'].items():
    if type(val) in [dict, list]:
        print(f"\t**Skipping {key} of len {len(val)}")
    else:
        print(f"\t{key}={val}")
```

Here's the second bit of code, search_event.py, this seems to honor the allowedlist:
```
#!/usr/bin/env python3
import urllib3
from pymisp import PyMISP

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
misp = PyMISP(
    url='https://misp.my-company.com:48752',
    key='key',
    ssl      = False)
response = misp.search(eventid=223461, pythonify=False)
for event in response:
    print('Event key=val:')
    for key, val in event['Event'].items():
        if type(val) in [dict, list]:
            print(f"\t**Skipping {key} of len {len(val)}")
        else:
            print(f"\t{key}={val}")
```

Here's the output from get_event:
```
% python3 get_event.py             
Fetching event
Event key=val:
	id=223461
	orgc_id=2
	org_id=2
	date=2021-03-15
	threat_level_id=4
	info=Chris Test Event
	published=False
	uuid=802c7e97-e217-4c91-8f2e-f313dd8bab06
	attribute_count=1
	analysis=0
	timestamp=1615838661
	distribution=4
	proposal_email_lock=False
	locked=False
	publish_timestamp=0
	sharing_group_id=11
	disable_correlation=False
	extends_uuid=
	event_creator_email=cl778h@att.com
	**Skipping Org of len 4
	**Skipping Orgc of len 4
	**Skipping SharingGroup of len 16
	**Skipping Attribute of len 1
	**Skipping ShadowAttribute of len 0
	**Skipping RelatedEvent of len 1
	**Skipping Galaxy of len 0
	**Skipping Object of len 0
	**Skipping EventReport of len 0
```

Here's the output from search_event.py
```
% python3 search_event.py 
Event key=val:
	id=223461
	orgc_id=2
	org_id=2
	date=2021-03-15
	threat_level_id=4
	info=Chris Test Event
	published=False
	uuid=802c7e97-e217-4c91-8f2e-f313dd8bab06
	attribute_count=1
	analysis=0
	timestamp=1615838661
	distribution=4
	proposal_email_lock=False
	locked=False
	publish_timestamp=0
	sharing_group_id=11
	disable_correlation=False
	extends_uuid=
	event_creator_email=cl778h@att.com
	**Skipping Org of len 4
	**Skipping Orgc of len 4
	**Skipping SharingGroup of len 16
	**Skipping Attribute of len 0                         <----- hey where's my attribute!?
	**Skipping ShadowAttribute of len 0
	**Skipping RelatedEvent of len 1
	**Skipping Galaxy of len 0
	**Skipping Object of len 0
	**Skipping EventReport of len 0
```

**Comment by chrisinmtown** [comment]
I forgot to post the data for missing attribute, here it is:
```
Network activity | url | https://sites.google.com/site/paypalinclivenew/
```
This does not seem to be especially weird to me. The "IDS" flag is not checked.

However, critically, the value matches a pattern in the server's signature allowedlist. That effectively blocks Pymisp from getting the full event attribute list by search.

**Comment by chrisinmtown** [comment]
<img width="867" alt="Screen Shot 2021-03-15 at 3 40 40 PM" src="https://user-images.githubusercontent.com/10234212/111211491-d800e480-85a4-11eb-88f5-f8728ea118be.png">

**Comment by chrisinmtown** [comment]
I tested further by adding another attribute with the URL shown above plus an extra suffix to make it unique. Now the event has 896 attributes, the search_event method returns 894 attribute, and the get_event method returns 896.

What is special about value "https://sites.google.com/"!?

**Comment by iglocska** [comment]
This is indeed intended. Basically the restsearch API is a combination of all of our prior export APIs (/events/nids, /events/hids, /events/csv, etc) which were using the allowedlist as a way to globally remove unwanted values from the exports when feeding the various tools hooked up to MISP. 

This subsystem (allowlists) is not used by the normal REST API. 

With that said, this is something we should definitely improve - perhaps treating it equal to warninglists (which they most closely resemble, apart from being ad hoc editable). This would mean that the default behaviour would change to NOT exclude values in the allow list, unless the enforceWarninglist flag is passed.

**Comment by chrisinmtown** [comment]
I'm baffled that you describe "restsearch API" as "not the normal REST API".  I didn't realize there were such fine divisions among the various endpoints.

+1 vote for adding a new parameter to all the search methods, enforceAllowedWarningAndEveryOtherConfusingList, default True for backward compatibility.

**Comment by iglocska** [comment]
Basically the search API is separate altogether and doesn't follow the normal REST api's usage.

The regular REST api is all the /add /edit /view /delete /index endpoints of the API, whilst /restSearch is a special case. With that said, the /index APIs have their own filtering capabilities, hence the confusion that often comes of this.

With that said, ignore my previous comment, we were planning on scrapping the allowlist sooner or later anyway, so let's focus on that instead, created an issue for tracking it:

https://github.com/MISP/MISP/issues/7210

**Comment by chrisinmtown** [comment]
Thanks. Would you like me to close this, since the system seems to be behaving as per your design?  Need some material in misp-book about this *badly*.

**Comment by iglocska** [comment]
I'd rather people used this system less. I'll add a notice about both that and what it does directly on the allowlist page.

**Comment by chrisinmtown** [comment]
Which system would you prefer that people use less?  Github?  Allowedlist?  Restsearch?

**Comment by iglocska** [comment]
Obviously Github.
