### ISSUE TITLE
Server settings (Salt error, edit buttons missing)

### ISSUE THREAD

**Issue by abulhol** [MISP/MISP#721]
I am testing MISP following the installation instruction for Ubuntu14.04.

If I check the "Server settings", they complain about too short Salt value ("The salt has to be a 32 byte long string."), even with a value like: 
<i>qa~t](84z<1t<1oz:ik.@IRNyhG=8q(odfrdr99dfdsss<\i>

In addition, I cannot find any buttons to edit the Server Settings, so I have to do it directly in the config.php

**Comment by iglocska** [comment]
Double clicking a value should bring up the edit interface of any value in there except for the salt value (which can only be edited via the config.php file).

I'll have a look at your specific salt key and why it doesn't work later on.

**Comment by abulhol** [comment]
OK, double clicking works as you write (it is not very intuitive, you should add this info to the manual).

**Comment by abulhol** [comment]
Hi Andras, 
I just figured it out: The salt has to be **exactly** 32 characters long. 
The installation guide says
<i>"# The salt key must be an at least 32 byte long string."</i>
which is not correct.
"32 bytes" is also a pretty difficult concept. I can see in Server.php that you are testing the byte count using strlen (http://php.net/manual/en/function.strlen.php), so in order to get this right, one has to test his salt against strlen beforehand to make sure it is really exactly 32 bytes long. ;-)

**Comment by iglocska** [comment]
Hello Benjamin,

ah that's a great find. I will change the validation for this, indeed it
should be 32 chars or longer. Thanks for the heads-up!

Best regards,
Andras

On Wed, Nov 18, 2015 at 3:13 PM, Benjamin Gathmann <notifications@github.com

**Comment by abulhol** [comment]
I noticed that edited values are not displayed. I.e. the old value is displayed until a complete reload of the page. (only in the Server settings tabs)

**Comment by iglocska** [comment]
It's not just a complete reload, it can take a second or two for the new
settings to kick in.

**Comment by abulhol** [comment]
Nope, sorry. I can see the value gets saved in config.php, but the page still shows the old value (also after 1 minute).

**Comment by iglocska** [comment]
I mean you will still need to reload the page but sometimes it will take a
short time for it to actually be the value used by MISP. I originally had a
script that reloaded the value after setting it, but it would often end up
being the old value.
