### ISSUE TITLE
Make the images created in EventGraph available via the API

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#7211]
**Describe the solution you'd like**
Have an option (via the API) to request the images (JPG, PNG) or export (JSON, DOT) created in the EventGraph. For example show all "expanded" and referenced objects/attributes. An option might be to refer to one of the "history" elements.
This would allow to include these images automatically in external resources/reports.

**Comment by mokaddem** [comment]
Hey,
Pictured saved in the event graph history are now (a1b5141a5a9933433a79fc413b01f3a482040ae1) exposed to the API.
Here is the format:
`/event_graph/viewPicture/[event_id]/[event_graph_id]`
Thanks for the suggestion!

**Comment by cudeso** [comment]
Sweet! Thank you!
