### ISSUE TITLE
Embedded backslashes in attribute value vanish on server after adding to event

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7214]
How can I preserve backslashes in attribute values when I add an attribute to an existing event? The backslashes don't make it to the database. I don't see any messages in debug.log/error.log, and the PyMISP.add_attribute() invocation returns success. I'm using MISP server 2.4.137, PyMISP 2.4.137 and the code is below.

Here is an example of a troublesome value that I get from an external source, I suppose they saw it in an attack:
```
http://googlechromeupdater.twilightparadox.com/html?DVXNSTHORF=fd6f240590734406be3bd35ca3622ea0;GRIBOOZ0LN=a3bf23855b0b40dda08f709fabb60d32;\..\..\..\./mshtml,RunHTMLApplication
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  RedHat
| OS version (client)       | Linux
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | n/a

### Expected behavior

When I store an IOC sent by a premium supplier as an attribute, I just want MISP to store & display it faithfully without modification.

### Actual behavior

MISP strips backslashes from within attribute values

### Steps to reproduce the behavior

Fix the URL and authkey, then run this self-contained code example:
```
#!/usr/bin/env python3

import sys
import urllib3
from pymisp import PyMISP, MISPAttribute, MISPEvent
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def check_misp_response(resp: dict, msg: str):
    """Check a MISP response for error; show error and exit if found"""
    if isinstance(resp, dict) and 'errors' in resp:
        print('{} failed: {}'.format(msg, resp['errors']), file=sys.stderr)
        raise Exception('check_misp_response exiting')


misp_client = PyMISP(
    url='https://misp.mycompany.com:48752',
    key='key',
    ssl=False)
if not misp_client:
    print('PyMISP() failed\n', file=sys.stderr)
    sys.exit(1)

event = MISPEvent()
event.distribution = 0  # internal
event.published = False
event.info = 'Test event for attribute values with backslashes'
event = misp_client.add_event(event, pythonify=True)
check_misp_response(event, 'add_event')
print('created event:\n{}'.format(event.to_json(sort_keys=True, indent=4)))
attr = MISPAttribute()
attr.category = 'Network activity'
attr.type = 'url'
attr.value = r'http://forward.com/foo\.\.\.'
attr = misp_client.add_attribute(event, attr, pythonify=True)
check_misp_response(attr, 'add_attribute')
print('created attr:\n{}'.format(attr.to_json(sort_keys=True, indent=4)))
response = misp_client.delete_event(event)
check_misp_response(attr, 'delete_event')
```

### Logs, screenshots, configuration dump, ...

Here's what I see when I run the code shown above.

```
% python3 create_attr_backsl.py
created event:
{
    "Org": {
        "id": "2",
        "local": true,
        "name": "ABC",
        "uuid": "5a6a4161-b2e0-46b6-b12e-1bca0a6b037c"
    },
    "Orgc": {
        "id": "2",
        "local": true,
        "name": "ABC",
        "uuid": "5a6a4161-b2e0-46b6-b12e-1bca0a6b037c"
    },
    "analysis": "0",
    "attribute_count": "0",
    "date": "2021-03-16",
    "disable_correlation": false,
    "distribution": "0",
    "event_creator_email": "me@mycompany.com",
    "extends_uuid": "",
    "id": "223510",
    "info": "Test event for attribute values with backslashes",
    "locked": false,
    "org_id": "2",
    "orgc_id": "2",
    "proposal_email_lock": false,
    "publish_timestamp": 0,
    "published": false,
    "sharing_group_id": "0",
    "threat_level_id": "4",
    "timestamp": "1615921539",
    "uuid": "052c2bc9-5c92-446c-a94c-95a510b71345"
}
created attr:
{
    "category": "Network activity",
    "comment": "",
    "deleted": false,
    "disable_correlation": false,
    "distribution": "5",
    "event_id": "223510",
    "id": "154932165",
    "object_id": "0",
    "sharing_group_id": "0",
    "timestamp": "1615921539",
    "to_ids": true,
    "type": "url",
    "uuid": "0b774606-3012-4851-a5bf-b4c6c41b25c6",
    "value": "http://forward.com/foo...",
    "value1": "http://forward.com/foo...",
    "value2": ""
}
```
Originally opened as https://github.com/MISP/PyMISP/issues/723 but they suggested I move the issue to this repo.

**Comment by iglocska** [comment]
They do indeed. `\` is an escape character in JSON and needs to be encoded via `\\`.

**Comment by iglocska** [comment]
From a quick test in MISP directly:

`\` added in an attribute value via the UI correctly gets saved as `\\`

Passing `\\` in the value of a JSON will correctly be rendered as `\`

**Comment by chrisinmtown** [comment]
Ok thanks but please note I'm using PyMISP - just assigning values in Python.  If you wanna turn it into JSON to pump it around that's fine, but I should not have to worry about (il)legal JSON escape characters. So is this really a PyMISP issue after all?

**Comment by iglocska** [comment]
Yep, my point was from MISP's perspective both the input and output is as expected.

**Comment by chrisinmtown** [comment]
Ok thanks @iglocska I will shuttle my little complaint back to the PyMISP repo.

**Comment by iglocska** [comment]
Oooor I was wrong. Looks like it's something else altogether indeed on MISP side.

**Comment by iglocska** [comment]
I was indeed wrong and it's special to certain types. It's a refanging algorithm going wrong, pushing a fix now. Apologies, my tests should have been more accurately mimicing what you were doing, it wasn't an encoding issue at all but a rather dumb refanging.

**Comment by chrisinmtown** [comment]
Thanks for the quick response Andras @iglocska!  Refanging?  Don't know that word :)

**Comment by Rafiot** [comment]
@chrisinmtown sometimes, people don't want to share "active" indicators (typically, in a email), so for example `http://evilsite.com` will be turned into `hxxp://evilsite.com` (that's defanging). What MISP tries to do is the opposite and turns `hxxp://evilsite.com` into `http://evilsite.com` (refanging).

As you can imagine, it's not really failsafe, and in this case, the regex was refanging an indicator that didn't need it because somewhere, someone was sharing IP adresses this way: `127\.0\.0\.0`, refanged to `127.0.0.0`
