### ISSUE TITLE
S/MIME certificate can not be imported

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#7218]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.4
| MISP version / git hash   | 89a42b1a7c86c9be249c57d6c1d6616043a02191

### Expected behavior
Accepts a valid (`openssl x509 -in test.pem -text` works) certificate, throws error and writes to log in case the certificate is not valid. 

### Actual behavior
Throws error in the UI (`This S/MIME certificate cannot be used to encrypt email.`) and writes **no errors to log**.

### Steps to reproduce the behavior
Can provide affected S/MIME certificate via mail, won't post it publicly here.

**Comment by JakubOnderka** [comment]
Hello, what are your certificate purposes?

```
openssl x509 -noout -text -purpose -in test.pem
```

**Comment by 3c7** [comment]
Hi Jakub,

TIL that people create S/MIME certificates for signing only. Even so the error message is absolutely correct, due to some recent mail encryption issues, I haven't really paid attention to it and assumed a bug. Closing this (non-) issue.
