### ISSUE TITLE
Add MISP XML - specs?

### ISSUE THREAD

**Issue by abulhol** [MISP/MISP#722]
I discovered an item "Add MISP XML" below "Add event". This is not described anywhere in the MISP book, so probably a new feature.
Is the MISP XML schema specified anywhere? Or do I have to figure it out myself from the XML downloads from existing reports?

**Comment by iglocska** [comment]
There are some samples but the spec itself is not published yet. I'll push the schema later today.

**Comment by abulhol** [comment]
Great. Is this the same schema I can use for POSTing requests to /events then?

**Comment by iglocska** [comment]
Yup!

**Comment by abulhol** [comment]
Hi Andras,
I saw that adelau pushed the JSON schema to the repo: https://github.com/MISP/MISP/commit/1cd7f6bd04cc1d262cd293c0a5bd8113c43067f2
I guess the XML schema is also going to go there?

**Comment by iglocska** [comment]
That's the plan but it requires a bit more work than I had anticipated (it
was a rather old schema from 2013 and has some inaccuracies even for the
datamodel back then). I'll try to push it soonish.

On Mon, Nov 23, 2015 at 8:50 AM, Benjamin Gathmann <notifications@github.com

**Comment by abulhol** [comment]
That would be great. I would like to use "Add MISP XML" functionality to import our reports. I.e. I would first convert our report to your XML format and then import it via the web interface. 
In particular, it would be important to know which fields are mandatory. E.g. is it necessary to provide UUIDs, or are these created by MISP upon import?
I have made a few tests, but often the attributes failed to import, without any failure notice. Also, after the import, MISP should redirect to the event and not stay on the import page.

**Comment by abulhol** [comment]
It would also be helpful to be able to leave fields like "org" and "orgc" empty, these can then be taken from the currently logged in user then.

**Comment by iglocska** [comment]
Ah ok, that is pretty simple. You can indeed leave org and orgc empty and MISP will automatically set them for you, here is a minimalistic example of what MISP requires to validate an event:

`<?xml version="1.0" encoding="UTF-8"?>
<Event>
	<date>2015-04-14</date>
	<threat_level_id>1</threat_level_id>
	<info>This is a sample event</info>
	<analysis>0</analysis>
	<distribution>1</distribution>
	<Attribute>
		<type>ip-src</type>
		<category>Network activity</category>
		<distribution>1</distribution>
		<value>8.8.8.8</value>
	</Attribute>
</Event>`

This should be the absolute bare minimum to push an event with a single attribute (though I'd highly advise to also set the "to_ids" flag on the attribute manually, even if it is not required as it will assume 0).

**Comment by abulhol** [comment]
Hi Andras,
The MISP importer chokes on some files, but there is no error output. 
I have gone through the PHP code and it seems there is a lot to be fixed, e.g.:
* Redirect to new event does not work (EventsController line 1091 mentions it, but there is no implementation)
* If an attribute fails, nothing is saved, and no exception is thrown (Event.php line 1368). The method returns false, but this is not evaluated by the caller. No log is written at all, which makes it very hard to find out which attribute caused the failure.
* If I don't select anything at all in "Import from MISP XML" and click "Upload", the page still says "The event has been saved".  

After some testing, I found that this attribute here lets the import fail: 
``` xml
      <Attribute>
         <category>Payload installation</category>
         <type>filename</type>
         <value>C:\Users\admin\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\PN3IRREK\39483c[1].gif</value>
         <distribution>0</distribution>
      </Attribute> 
```
Maybe it is the dot before IE5 or the curly brackets? I can't tell.
If I knew more about Cake, I could probably fix this, but I'll leave it to you for now. ;-)

**Comment by iglocska** [comment]
Hmm let me have a look. The upload XML thing is an ancient replacement for the API - would it be possible to go through that instead in the meanwhile? That generally handles situations like this much better. I'll look into that specific attribute in the meanwhile.

**Comment by abulhol** [comment]
I don't need this functionality immediately, but if you manage to fix it within the next days would be great, then I can continue working on the import.

**Comment by iglocska** [comment]
Sure! Just wondering, what tool are you building a connector for? Are you willing to share the connector afterwards? We're always looking for connectors to other tools :)

**Comment by abulhol** [comment]
I am creating the import for the Joe Sandbox report.

**Comment by iglocska** [comment]
That sounds great! If you are interested, we'll be adding a modular import/export feature to MISP in the future to make interconnecting it with other tools easier, maybe we could use that in the future to automate the process and have an interface between Joe Sandbox -> MISP directly.

**Comment by abulhol** [comment]
Yes, that would be great! For the time being though, let's use what we have. :-)
I have tried POSTing new events with PyMISP now (my sample is called mispreport.xml), but I get a similar behavior to the manual upload. The HTTP response is:
{u'url': u'/events/view/44', u'message': u'Success, saved all attributes.', u'name': u'Success', u'id': u'44'}
But the only attributes that get created are:  	
filename|sha1 mispreport.xml | 027ca914fec41a4bf33b106dca7ca0007e96c0f1
filename|sha256 mispreport.xml | etc.
and malware-sample  mispreport.xml | etc.
:-(

**Comment by iglocska** [comment]
Ah when you post a file like that MISP thinks you are posting a sample, so it zips it and creates a malware sample attribute and the related hashes. 

Via simple REST you can simply POST the contents of that XML (as the body of the request) to `https://mymisp/events/` with the following headers:

`Authorization: myauthkey`
`Accept: application/xml`
`Content-Type: application/xml`

**Comment by abulhol** [comment]
Good morning Andras,
Thanks for the explanation. I have managed to upload events this way, but the behavior is the same as in the manual upload, i.e. attribute imports fail silently, the HTTP response and logs contain no respective message. 
Btw, what does the attribute to_ids in Events signify?

**Comment by iglocska** [comment]
Morning Benjamin!

to_ids allows an attribute to be sent to certain exports (such as
snort/suricata, HIDS exports) and in some cases it will be represented
differently (indicator vs observable in the STIX export) - it basically
signals that an attribute is an indicator that is actionable by the
automation systems.

I'll try to resolve the issue with the silent drops today!

Best regards,
Andras

On Tue, Nov 24, 2015 at 9:59 AM, Benjamin Gathmann <notifications@github.com

**Comment by iglocska** [comment]
Just a heads-up, have the Add XML completely reworked and the reason that this:

`<Attribute>
         <category>Payload installation</category>
         <type>filename</type>
         <value>C:\Users\admin\AppData\Local\Microsoft\Windows\Temporary Internet Files\Content.IE5\PN3IRREK\39483c[1].gif</value>
         <distribution>0</distribution>
      </Attribute>`

fails is finally revealed in the new tool: That path is blocked by a regular expression. Temporary internet files are on the blocked list. I'll try to push it tonight before going to bed.

**Comment by abulhol** [comment]
That's great! Do you ever sleep? ;-)

2015-11-30 1:43 GMT+01:00 Andras Iklody <notifications@github.com>:

**Comment by abulhol** [comment]
Hi Andras,
I just pulled your changes, they are great.
I have a problem left with empty file hashes. E.g. I have a file¦md5 pair:
C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\cdndisp.tmp|D41D8CD98F00B204E9800998ECF8427E
Right now, the import fails completely if it encounters this. 
Can you please make the importer simply skip the "empty file" hashes? (MD5, SHA1, SHA256)
In general, it would be best if the importer imports everything that is good and logs the failed attributes, because it is annoying if everything fails because of one erroneous attribute.

One more (minor) thing: The web interface reports "The event has been saved" (red message bar).

**Comment by abulhol** [comment]
Btw, can you merge my pull request regarding domain|ip?
https://github.com/MISP/MISP/pull/727

**Comment by iglocska** [comment]
Hmm, the first issue will be a problem. I could do it with a small trick for for the import on the UI, but for the REST interface it's tricky as we have to go around the framework mechanisms for it. 

For the flash message + the pull request, will try to get it done asap today.

**Comment by abulhol** [comment]
OK, I'll try to change my report so that it does not contain empty file
hashes then.

2015-11-30 10:38 GMT+01:00 Andras Iklody <notifications@github.com>:

**Comment by iglocska** [comment]
Actually wait with it. It's kind of crap that it doesn't handle it better so I am implementing it now.

**Comment by abulhol** [comment]
Yes, that's cool! I'll delete them from our XML anyway.

2015-11-30 11:19 GMT+01:00 Andras Iklody <notifications@github.com>:

**Comment by iglocska** [comment]
I've updated it in the latest commit (both via the UI and the REST interface). Will have a look at the pull request soon too but have a few other issues to resolve first. Let me know if you have any issues with it!

**Comment by abulhol** [comment]
Hi Andras,
This commit is superb- you've done a great job! The upload works fine both via the browser and the API, and non-fitting events such as empty file hashes are just skipped. No further action needed here. Thumbs up!
