### ISSUE TITLE
Installer doesn't set permissions on config.php correctly (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#7220]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.2 LTS
| OS version (client)       | N/A
| PHP version               | N/A
| MISP version / git hash   | 2.4.140, 89a42b1a7c86c9be249c57d6c1d6616043a02191
| Browser                   | If applicable

### Expected behavior
config.php is not readable by all after initial install using installation script

### Actual behavior
config.php is readable by all (permission 644) after initial install using installation script

### Steps to reproduce the behavior
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

Note:
Running the installer a second time after the initial install ends up fixing the permissions on  config.php

Tried to figure out what causes the issue but didn't find it yet

**Comment by Wachizungu** [comment]
Hmm, might be related to #7134 (if setting of config via cake somehow changes the permissions)?

**Comment by imidoriya** [comment]
As a note, I tried to manually set the permission of this file, but when the configuration is saved again via the web GUI, it reverts back to the readable by all.

**Comment by chrisinmtown** [comment]
Now being worked as issue #7229, @iglocska found a bug in how the file is re-created after an update on the web GUI.

So you might consider closing this, altho I'm not 100% certain how the CIRCL team prefers to handle dupe issues.

**Comment by Wachizungu** [comment]
See #7229, will reopen if issue persists. Thanks for the heads up @chrisinmtown
