### ISSUE TITLE
Unable to open Misp events

### ISSUE THREAD

**Issue by maro584** [MISP/MISP#7225]
Questions | Answers
-- | --
Type of issue | Support
OS version (server) | RedHat, 7
OS version (client) | Win10
PHP version | 7.4
MISP version / git hash | 2.4.135, hash of the commit / 752a31d

Support Questions
When I am trying to open any event like this:
https://<fqdn>/events/view/56790

I have got following error:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

Logs, screenshots, configuration dump, ...
[root@xxxx tmp]# tail -f /var/www/MISP/app/tmp/logs/error.log

2021-03-19 12:40:22 Error: [PDOException] SQLSTATE[42S02]: Base table or view not found: 1932 Table 'misp.sightings' doesn't exist in engine
Request URL: /events/view/56790
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find()
#7 /var/www/MISP/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings()
#8 /var/www/MISP/app/Controller/EventsController.php(1436): Sighting->eventsStatistic()
#9 /var/www/MISP/app/Controller/EventsController.php(1655): EventsController->__viewUI()
#10 [internal function]: EventsController->view()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#15 {main}

**Comment by maro584** [comment]
I have reboot a workers, but without success for the events
Diagnostic tab not show any errors which could caused this problem.

**Comment by iglocska** [comment]
Can you check if the table actually exists?

`mysql -u [misp_mysql_user] -p misp`

`describe sightings;`

If that exists:
```
rm -f /var/www/MISP/app/tmp/cache/persistent/myapp_*
rm -f /var/www/MISP/app/tmp/cache/cache/myapp_*
```

**Comment by maro584** [comment]
I have logged in to DB and I can not list a table "sightings":

MariaDB [misp]> describe sightings;
ERROR 1932 (42S02): Table 'misp.sightings' doesn't exist in engine

But when I am displaying all the tables I can find table "sightings":

MariaDB [misp]> show tables;
+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| admin_settings                |
| allowedlist                   |
| attachment_scans              |
| attribute_tags                |
| attributes                    |
| auth_keys                     |
| bruteforces                   |
| cake_sessions                 |
| correlations                  |
| dashboards                    |
| decaying_model_mappings       |
| decaying_models               |
| event_blocklists              |
| event_delegations             |
| event_graph                   |
| event_locks                   |
| event_reports                 |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| fuzzy_correlate_ssdeep        |
| galaxies                      |
| galaxy_cluster_blocklists     |
| galaxy_cluster_relation_tags  |
| galaxy_cluster_relations      |
| galaxy_clusters               |
| galaxy_elements               |
| inbox                         |
| jobs                          |
| logs                          |
| news                          |
| noticelist_entries            |
| noticelists                   |
| notification_logs             |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| org_blocklists                |
| organisations                 |
| posts                         |
| regexp                        |
| rest_client_histories         |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sightingdb_orgs               |
| sightingdbs                   |
| sightings                     |
| tag_collection_tags           |
| tag_collections               |
| tags                          |
| tasks                         |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| user_settings                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
+-------------------------------+
75 rows in set (0.00 sec)


Should I proceed with Your instructions?

**Comment by mokaddem** [comment]
@maro584 clearing the cache is harmless, so feel free to proceed.
However, I find it strange that executing the command `describe sightings;` fails despite the fact that the `sightings` table can be found when doing the `show tables;` command.
Could you also make sure that you haven't reduced the permission of the misp database user for this particular table?

**Comment by maro584** [comment]
It turns out that permissions for below files changes from mysql to root:
sightings.ibd
sightings.frm

I have assign a mysql user to this files and restart a mariadb service.

Now when I am trying to open any event in GUI I am still getting internal server error but logs looks different:

/var/www/MISP/app/tmp/logs/error.log
2021-03-26 12:39:29 Error: [PDOException] SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Request URL: /events/view/57324
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find()
#7 /var/www/MISP/app/Model/Sighting.php(311): Sighting->fetchGroupedSightings()
#8 /var/www/MISP/app/Controller/EventsController.php(1436): Sighting->eventsStatistic()
#9 /var/www/MISP/app/Controller/EventsController.php(1655): EventsController->__viewUI()
#10 [internal function]: EventsController->view()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#15 {main}


/mariadb.log

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7fc2e0011060): SELECT `Sighting`.`org_id`, `Sighting`.`attribute_id`, `Sighting`.`type`, (DATE(FROM_UNIXTIME(`Sighting`.`date_sighting`))) AS  `Sighting__date_sighting`, (COUNT(id)) AS  `Sighting__sighting_count`, (MAX(date_sighting)) AS  `Sighting__last_timestamp` FROM `misp`.`sightings` AS `Sighting`   WHERE `Sighting`.`event_id` = 57324  GROUP BY org_id, attribute_id, type, (DATE(FROM_UNIXTIME(`Sighting`.`date_sighting`)))  ORDER BY (DATE(FROM_UNIXTIME(`Sighting`.`date_sighting`))) ASC
Connection ID (thread ID): 8
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Uses event mutexes
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Compressed tables use zlib 1.2.7
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Using Linux native AIO
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Number of pools: 1
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Using SSE2 crc32 instructions
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Completed initialization of buffer pool
2021-03-26 13:40:36 140349218248448 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Highest supported file format is Barracuda.
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Starting crash recovery from checkpoint LSN=2333672402984
2021-03-26 13:40:36 140349989546176 [Note] InnoDB: Starting final batch to recover 413 pages from redo log.
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: 128 out of 128 rollback segments are active.
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: Waiting for purge to start
2021-03-26 13:40:37 140349989546176 [Note] InnoDB: 5.7.19 started; log sequence number 2333672403084
2021-03-26 13:40:37 140348575700736 [Note] InnoDB: Loading buffer pool(s) from ***********/mysql/ib_buffer_pool
2021-03-26 13:40:37 140348575700736 [Note] InnoDB: Buffer pool(s) load completed at 210326 13:40:37
2021-03-26 13:40:37 140349989546176 [Note] Plugin 'FEEDBACK' is disabled.
2021-03-26 13:40:37 140349989546176 [Note] Recovering after a crash using tc.log
2021-03-26 13:40:37 140349989546176 [Note] Starting crash recovery...
2021-03-26 13:40:37 140349989546176 [Note] Crash recovery finished.
2021-03-26 13:40:37 140349989546176 [Note] Server socket created on IP: '::'.
2021-03-26 13:40:37 140349989546176 [Note] Reading of all Master_info entries succeded
2021-03-26 13:40:37 140349989546176 [Note] Added new Master_info '' to hash table
2021-03-26 13:40:37 140349989546176 [Note] /opt/rh/rh-mariadb102/root/usr/libexec/mysqld: ready for connections.
Version: '10.2.8-MariaDB'  socket: '**************'  port: 3306  MariaDB Server




So I have realize that maybe there is something wrong with executed query so I have loggged to DB and execute below queries:

MariaDB [misp]> select * from sightings;
ERROR 2013 (HY000): Lost connection to MySQL server during query

MariaDB [misp]> select count(*) from sightings;
ERROR 2013 (HY000): Lost connection to MySQL server during query

When I am limiting a select query to 10 results I have got results and query do not fails, which means that there is a problem with memory I guess.

In mariadb-server.cnf file in [mysqld] section I do not have any specific memory configuration.

**Comment by mokaddem** [comment]
That indeed sounds like a configuration/memory issue.
Did you try to increase the available memory?
Does your server have enough memory all together?

Also, are you heavily pushing sightings to your MISP instance? Do you have an idea on how many sightings you have in your DB?
The following query might give an idea:
```sql
select max(id) from sightings;
```
Thanks

**Comment by maro584** [comment]
There is only 20% memory used on server so this is no issues.
I have changed a configuration for DB in file my.cnf and restart a db service
`key_buffer_size = 1280M
max_allowed_packet = 1280M
thread_stack = 1M
thread_cache_size = 16
innodb_buffer_pool_size = 8G
read_buffer_size = 128M
read_rnd_buffer_size = 256M
sort_buffer_size = 4G`

But it has not helped. The result is the same.

Also I can not execute this command:
select max(id) from sightings;

**Comment by iglocska** [comment]
Keep in mind that PHP doesn't really care about the amount of available
system memory, but rather how much memory is available for each process.
This is governed by the memory_limit directive in your php.ini and it
defaults to a pitiful 128M (we recommend 2048M by default, but you may be
exceeding that).

Have a look at your MISP diagnostic page (administration -> server settings
-> diagnostics) for guidance and for the currently set values.

Best regards,
Andras

**Comment by iglocska** [comment]
With that said, I should have read the rest of the thread instead of blindly replying, that has nothing to do with your PHP memory and indeed something going wrong on the mysql level. Wow.

**Comment by iglocska** [comment]
I would consider raising the question with mariadb's support channels.

**Comment by maro584** [comment]
I have openned a case on MariaDB support but in the meantime I have made another troubleshooting steps I finds out that probably problem is not related to too large query because table sightings is not the biggest table in my MISP and when I am executing a queries to some tripple times larger table there is no issues with query, so I think there might be a bug only with the table sightings. I am sure that there is no issues with query timeout to table sightings because query is immediatelly killed after execution, maybe there is some limitation in configuration files.

**Comment by maro584** [comment]
I can not display any sightings when I am using any argument from result of query.

MariaDB [misp]> select * from sightings LIMIT 1;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    8
Current database: misp

+----+--------------+----------+--------+---------------+--------------------------------------+--------+------+
| id | attribute_id | event_id | org_id | date_sighting | uuid                                 | source | type |
+----+--------------+----------+--------+---------------+--------------------------------------+--------+------+
|  2 |          218 |       13 |      2 |    1543493879 | 5bffd8f7-8bf4-423e-8919-xxxxxxxxxxxx |        |    0 |
+----+--------------+----------+--------+---------------+--------------------------------------+--------+------+
1 row in set (0.05 sec)

MariaDB [misp]> select * from sightings where uuid like '5bffd8f7-8bf4-423e-8919-xxxxxxxxxx';
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by maro584** [comment]
MariaDB [misp]> describe sightings;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | int(11)      | NO   | PRI | NULL    | auto_increment |
| attribute_id  | int(11)      | NO   | MUL | NULL    |                |
| event_id      | int(11)      | NO   | MUL | NULL    |                |
| org_id        | int(11)      | NO   | MUL | NULL    |                |
| date_sighting | bigint(20)   | NO   |     | NULL    |                |
| uuid          | varchar(255) | YES  | MUL |         |                |
| source        | varchar(255) | YES  | MUL |         |                |
| type          | int(11)      | YES  | MUL | 0       |                |
+---------------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

**Comment by chirazbenhassine** [comment]
Comment vous allez accéder à MariaDB [misp]> svp ??

**Comment by chirazbenhassine** [comment]
How you can access to MariaDB [misp]> please?

**Comment by maro584** [comment]
Just use this command
/opt/rh/rh-mariadb102/root/usr/bin/mysql -u misp -p misp

It is really strange that I can execute this query:
select * from sightings LIMIT 10000;

But I can not execute simple select with where containing one row:
select * from sightings where uuid like '5e5d06d6-1e98-4a16-966f-xxxxxxxxxxx';

**Comment by chirazbenhassine** [comment]
Thanks it's work, but i put sudo mysql -u misp -p misp 
mariadb is a database of misp ? if i would access to database of misp to add another database , I should install mysql ??

**Comment by jloehel** [comment]
Have you installed mariadb from the official RH repos? Have you already triggered a mysqlcheck? Just to exclude any data corruptions. Weird issues on RH smell like SELinux. Anything in `/var/log/audit/audit.log`? Can you pls try `sudo semanage permissive -a mysqld_t`.

**Comment by maro584** [comment]
The issue is solved , I have just delete a table sightings and recreate a structure of it using databases engine memory. When I have triggered mysqlcheck then the script stops in the moment where sightings table was checked
