### ISSUE TITLE
Untagging strangeness

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#7226]
This started happening about a week / 2 weeks ago.  I'm running into an occasional situation where the removal of a tag does not remove the tag.  For example, I'm finding events with both tlp:green and tlp:amber, even though when I add tlp:green the next command is to remove tlp:amber.  I have other tags that I only create as local tags, but on these events when the local tag should be deleted, it's converted into a global tag (even though I never create them as global).  It's as if removing the tag triggers it to be recreated, adding them back as global (I wouldn't notice with tlp:amber as it's already global).  It's not something I've been able to easily reproduce, but it happens a several times a day and I have to manually go in and delete them.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | MacOS
| PHP version               | 7.4.15
| MISP version / git hash   | v2.4.140 (6a8f7ff3361b608a114fafa832ffd89939a521ec)

### Expected behavior
Tag is deleted

### Actual behavior
Tag is not deleted (Tag is deleted / added back?)

### Steps to reproduce the behavior
Unknown at this time.  tlp:green taxonomy trigger?  I also change the sharing group at the same time.
I created another misp instance which only does a pull on tlp:green around the same time.  Don't believe this would have any effect, but thought I would include it.

### Logs, screenshots, configuration dump, ...
Let me know what I can produce to help

**Comment by chrisinmtown** [comment]
Probably dumb questions, but are you using PyMISP, and do you check the response from the server on each delete_tag() method call?

**Comment by imidoriya** [comment]
I am using PyMISP but I do not check the response.  I'll start logging the response to see if anything is happening.

**Comment by imidoriya** [comment]
This is the response for a tag that was "converted" from a local tag to a global tag after I issued the `untag`.
`{'saved': True, 'success': True, 'name': 'Tag my:tag(12) successfully removed from Event(415519).', 'message': 'Tag my:tag(12) successfully removed from Event(415519).', 'url': '/tags/removeTagFromObject'}
`

**Comment by JamesSOC080** [comment]
I've also noticed the same issue when attempting to remove tags (via the GUI), that have previously been added via PyMISP (as part of an ingest script). Some tags seem to get stuck/return an exception when I try to remove them.

The error received is: "Something went wrong - the queried function returned an exception. Contact your administrator for further details".

Sometimes adding an unrelated tag to the event seems to help and then allow the removal of the offending tag. Not sure if they're related but seems possible - would appreciate guidance for where to look in the logs to see where an exception is being raised.

Note: Removing the same tag from the event via the REST API works fine.

**Comment by imidoriya** [comment]
This is driving me crazy - please help!  I came in Monday to over 500 tags I have to delete manually.  I can't have this as a daily process.  All the tags that I'm having to delete had a `success: True` return.  What could cause them to be added back as global tags?  I can roll back my commit to a certain point to see if it helps or provide any logs.

What sucks is I can't find any regular cause - sometimes it works perfectly fine (all tags removed) and others not.. it's the same process removing the tags in either case and they all return successfully removed via json response.

**Comment by mokaddem** [comment]
@JamesSOC080 you can find the log files here `MISP/app/tmp/logs`

@imidoriya this is indeed concerning. I just had a look at the `removeTagFromObject` function and I don't see how the tag could be converted from local to global. The only action touching at the DB is a deletion.
Moreover, I haven't managed to reproduce it on my instance.

If you could check your logs and search for possible errors that would be great. Or event better, if you find a reliable way to reproduce it, that would be fantastic!

Thanks for your help!

**Comment by JamesSOC080** [comment]
> @JamesSOC080 you can find the log files here `MISP/app/tmp/logs`
> 
> @imidoriya this is indeed concerning. I just had a look at the `removeTagFromObject` function and I don't see how the tag could be converted from local to global. The only action touching at the DB is a deletion.
> Moreover, I haven't managed to reproduce it on my instance.
> 
> If you could check your logs and search for possible errors that would be great. Or event better, if you find a reliable way to reproduce it, that would be fantastic!
> 
> Thanks for your help!

Thanks - response to my issue, the log seems to suggest the request is being blackholed:

2021-03-24 15:27:55 Error: [BadRequestException] The request has been black-holed
Request URL: /events/removeTag/19328/14
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

**Comment by imidoriya** [comment]
@mokaddem would love to find a reliable way to reproduce it, but no luck so far unfortunately.  Not sure if it's caching, race condition or what.  I do push a regular volume though, so if I wait 10-20 min, I'll usually get several.  Here is my research thus far...

I don't think it's having an issue deleting the tag.  All indications and checks show the tags are, in fact, being removed.  What I'm seeing is that the tag is being added back and I've verified that by logging the SQL. The tag is removed and then at some point after, not initiated by me tagging, I see the INSERT with local 0.  I've also logged my event updates and none of them include the "Tags" section.  From what I can tell in one review, I didn't even update the even after removing the tag, which is pretty confusing.  I did publish the event though, so maybe it's in that process.

Still trying to track it down, but based on the SQL statements (included below) which includes the `localtag2` being inserted as a global tag (after a prior delete), I believe the INSERT might be done by these lines in Event.php.  My next step is to verify that (add some logging to the PHP) and try to understand why `resolved_data` would have stale event data.
https://github.com/MISP/MISP/blob/a8e08a6892977a3b6cc82887267c478869a09011/app/Model/Event.php#L6412-L6419

```sql
572948 Query	SELECT `Attribute`.`id`, `Attribute`.`event_id`, `Attribute`.`object_id`, `Attribute`.`object_relation`, `Attribute`.`category`, `Attribute`.`type`, `Attribute`.`value1`, `Attribute`.`value2`, `Attribute`.`to_ids`, `Attribute`.`uuid`, `Attribute`.`timestamp`, `Attribute`.`distribution`, `Attribute`.`sharing_group_id`, `Attribute`.`comment`, `Attribute`.`deleted`, `Attribute`.`disable_correlation`, `Attribute`.`first_seen`, `Attribute`.`last_seen`, (CASE WHEN `Attribute`.`value2` = '' THEN `Attribute`.`value1` ELSE CONCAT(`Attribute`.`value1`, '|', `Attribute`.`value2`) END) AS  `Attribute__value` FROM `misp`.`attributes` AS `Attribute`   WHERE `Attribute`.`uuid` = 'c15fa33b-a312-4f1c-9b57-2acd18dc9167'   ORDER BY `Attribute`.`event_id` DESC  LIMIT 1
572948 Query	SELECT `AttributeTag`.`id`, `AttributeTag`.`attribute_id`, `AttributeTag`.`event_id`, `AttributeTag`.`tag_id`, `AttributeTag`.`local` FROM `misp`.`attribute_tags` AS `AttributeTag`   WHERE `AttributeTag`.`attribute_id` = (29421881)
572948 Query	SELECT `Attribute`.`id`, `Attribute`.`event_id`, `Attribute`.`object_id`, `Attribute`.`object_relation`, `Attribute`.`category`, `Attribute`.`type`, `Attribute`.`value1`, `Attribute`.`value2`, `Attribute`.`to_ids`, `Attribute`.`uuid`, `Attribute`.`timestamp`, `Attribute`.`distribution`, `Attribute`.`sharing_group_id`, `Attribute`.`comment`, `Attribute`.`deleted`, `Attribute`.`disable_correlation`, `Attribute`.`first_seen`, `Attribute`.`last_seen`, (CASE WHEN `Attribute`.`value2` = '' THEN `Attribute`.`value1` ELSE CONCAT(`Attribute`.`value1`, '|', `Attribute`.`value2`) END) AS  `Attribute__value` FROM `misp`.`attributes` AS `Attribute`   WHERE `Attribute`.`uuid` = 'd562b5ff-1404-4e9a-873a-9deac246c4fb'   ORDER BY `Attribute`.`event_id` DESC  LIMIT 1
572948 Query	SELECT `AttributeTag`.`id`, `AttributeTag`.`attribute_id`, `AttributeTag`.`event_id`, `AttributeTag`.`tag_id`, `AttributeTag`.`local` FROM `misp`.`attribute_tags` AS `AttributeTag`   WHERE `AttributeTag`.`attribute_id` = (29421944)
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = 'b3b8da55-a1c8-44b7-9e7d-9d1a9d7206b7'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '52349eb5-fbe2-483e-ae9d-a37939e35e2b'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '45182775-ce73-4d4a-9168-6aca5624bcf0'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '6922e780-5a69-4e63-bec2-1c281a0022d0'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '79c38bdd-69c5-492f-af6f-dbaacc433497'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = 'da748b93-3913-489b-b66d-3e3b7bb997e5'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '84ec4993-9302-454d-dc05-7d35f3bfb537'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = 'cdc34362-2acc-4ce2-8b9f-fa9b1bce67e6'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '70117996-0767-480a-89a9-c8ddd53b0a53'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '03f1a0b4-816c-4adf-a3ed-a6ba73d6dfe0'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '101c4b12-897f-48ea-afc3-8eb085a7254f'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '768faf43-c434-44ee-aaac-5b00c62a7a67'    LIMIT 1
572948 Query	SELECT `Object`.`id`, `Object`.`name`, `Object`.`meta-category`, `Object`.`description`, `Object`.`template_uuid`, `Object`.`template_version`, `Object`.`event_id`, `Object`.`uuid`, `Object`.`timestamp`, `Object`.`distribution`, `Object`.`sharing_group_id`, `Object`.`comment`, `Object`.`deleted`, `Object`.`first_seen`, `Object`.`last_seen` FROM `misp`.`objects` AS `Object`   WHERE `Object`.`uuid` = '0beb919a-7cb3-4873-a184-ff58ea021c94'    LIMIT 1
572948 Query	SELECT `ObjectReference`.`id`, `ObjectReference`.`uuid`, `ObjectReference`.`timestamp`, `ObjectReference`.`object_id`, `ObjectReference`.`event_id`, `ObjectReference`.`source_uuid`, `ObjectReference`.`referenced_uuid`, `ObjectReference`.`referenced_id`, `ObjectReference`.`referenced_type`, `ObjectReference`.`relationship_type`, `ObjectReference`.`comment`, `ObjectReference`.`deleted` FROM `misp`.`object_references` AS `ObjectReference`   WHERE `ObjectReference`.`uuid` = 'e34bc6bb-1bf9-4889-93d8-f585d6d49d11'    LIMIT 1
572948 Query	SELECT `ObjectReference`.`id`, `ObjectReference`.`uuid`, `ObjectReference`.`timestamp`, `ObjectReference`.`object_id`, `ObjectReference`.`event_id`, `ObjectReference`.`source_uuid`, `ObjectReference`.`referenced_uuid`, `ObjectReference`.`referenced_id`, `ObjectReference`.`referenced_type`, `ObjectReference`.`relationship_type`, `ObjectReference`.`comment`, `ObjectReference`.`deleted` FROM `misp`.`object_references` AS `ObjectReference`   WHERE `ObjectReference`.`uuid` = '71b42602-6d96-47d6-b05e-678534cb1533'    LIMIT 1
572948 Query	SELECT `ObjectReference`.`id`, `ObjectReference`.`uuid`, `ObjectReference`.`timestamp`, `ObjectReference`.`object_id`, `ObjectReference`.`event_id`, `ObjectReference`.`source_uuid`, `ObjectReference`.`referenced_uuid`, `ObjectReference`.`referenced_id`, `ObjectReference`.`referenced_type`, `ObjectReference`.`relationship_type`, `ObjectReference`.`comment`, `ObjectReference`.`deleted` FROM `misp`.`object_references` AS `ObjectReference`   WHERE `ObjectReference`.`uuid` = '6ec1bcf4-4526-489f-b7fd-f377794d83d0'    LIMIT 1
572948 Query	SELECT `ObjectReference`.`id`, `ObjectReference`.`uuid`, `ObjectReference`.`timestamp`, `ObjectReference`.`object_id`, `ObjectReference`.`event_id`, `ObjectReference`.`source_uuid`, `ObjectReference`.`referenced_uuid`, `ObjectReference`.`referenced_id`, `ObjectReference`.`referenced_type`, `ObjectReference`.`relationship_type`, `ObjectReference`.`comment`, `ObjectReference`.`deleted` FROM `misp`.`object_references` AS `ObjectReference`   WHERE `ObjectReference`.`uuid` = '3ae2e45e-932a-4e19-846e-cd8e5afc3bb1'    LIMIT 1
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'tlp:amber'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 3 AND `event_id` = 422851    LIMIT 1
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'tlp:ex:chr'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 6 AND `event_id` = 422851    LIMIT 1
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'localtag1'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 9 AND `event_id` = 422851    LIMIT 1
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'localtag2'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 12 AND `event_id` = 422851    LIMIT 1
572948 Query	START TRANSACTION
572948 Query	INSERT INTO `misp`.`event_tags` (`local`, `event_id`, `tag_id`) VALUES ('0', 422851, 12)
572948 Query	COMMIT
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'localtag3'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 19 AND `event_id` = 422851    LIMIT 1
572948 Query	SELECT `Tag`.`id`, `Tag`.`name`, `Tag`.`colour`, `Tag`.`exportable`, `Tag`.`org_id`, `Tag`.`user_id`, `Tag`.`hide_tag`, `Tag`.`numerical_value`, `Tag`.`is_galaxy`, `Tag`.`is_custom_galaxy` FROM `misp`.`tags` AS `Tag`   WHERE LOWER(name) = 'localtag4'    LIMIT 1
572948 Query	SELECT `EventTag`.`id`, `EventTag`.`event_id`, `EventTag`.`tag_id`, `EventTag`.`local` FROM `misp`.`event_tags` AS `EventTag`   WHERE `tag_id` = 15 AND `event_id` = 422851    LIMIT 1
572948 Query	SELECT `SharingGroupServer`.`sharing_group_id` FROM `misp`.`sharing_group_servers` AS `SharingGroupServer`   WHERE `all_orgs` = '1' AND `server_id` = 0
572948 Query	SELECT `SharingGroupOrg`.`sharing_group_id` FROM `misp`.`sharing_group_orgs` AS `SharingGroupOrg`   WHERE `org_id` = 1
572948 Query	SELECT `EventDelegation`.`id`, `EventDelegation`.`event_id` FROM `misp`.`event_delegations` AS `EventDelegation`   WHERE `EventDelegation`.`org_id` = 1
```

**Comment by mokaddem** [comment]
Regarding `resolved_data`, this is used whenever you are using the enrichment system.
Could it be that you have enrichment processes running (CRON/PyMISP) that keep on enriching events and thus, adding these tags back?

I'm also interested in the timeline at which these events occur. What does the logs say about it?
You can search logs at `/admin/logs/search` and use the `action=tag`, then look for entries of the type:
```Attached tag (151) "TAGNAME" to attribute (1571)```
and
```Removed tag (151) "TAGNAME" from attribute (1571)```
Thanks!

**Comment by mokaddem** [comment]
@JamesSOC080 I'm not sure your issue is the same as @imidoriya 
- Do you always have blackholes when you try to untag via the interface?
- Are you using a proxy in front of your MISP?
- Do you have browser extension blocking JS?

**Comment by imidoriya** [comment]
@mokaddem Sorry for the delay, was working other things, but still dealing with this issue and regularly having to delete the tags.  I'm not even sure what the enrichment system is.  I'm not aware of anything I'm doing - is there a setting I need to check.  One thing I've done is disable all correlations - it took up too much storage and I wasn't using it.

I can no longer search my logs or events without getting a 504 Time-out. Too much data.  My log table is 44Gig, so if it's safe, I'll probably delete everything before 2021.  lol.  But doing a search via direct SQL, I didn't find any results for action="tag" on event 422851.  Does the log just record GUI tagging?

I wasn’t able to get the logging working using `file_put_contents()` as suggested by @iglocska writing into the `/tmp` - not sure why.  Happy to try and troubleshoot further, but just need a little guidance.

**Comment by imidoriya** [comment]
I no longer think the enrichment code is the cause based on my logging.  I think @mokaddem may have identified and fixed the local -> global issue via https://github.com/MISP/MISP/commit/e72579f5a92074bad0fc5c13fd3efe60f120c1a6

I'm not sure if that fixes why the events are being created, but it helped confirm my findings.  The tag is removed via `removeTagFromObject`, but later `handleEventTag` is called, which triggers an `attachTagToEvent` for the tag, recreating it.

I have verified when `attachTagToEvent` is called, the issue occurs and verified that `handleEventTag` precedes that containing the tag.

The only place I see handleEventTag called is here:
https://github.com/MISP/MISP/blob/92f2631c44e8f86924e51ec2e7413dd8e559c08d/app/Model/Event.php#L4140

Logging the event from `_edit` via $data, I can see the contents contain the tag that was deleted.  Reviewing my code, I can not find any place where I am editing the event where it contains would contain Tags.  Next step would be to figure out what is triggering it and why / where is it getting that old data from.

**Comment by imidoriya** [comment]
The second half of the issue has been solved and was my fault.  When I get an event to update it, I include the option `include_event_tags=False` to prevent this very thing (old tags getting added back in an event update).  Turns out:

![Inigo-Montoya-WORD-MEANS](https://user-images.githubusercontent.com/45568592/113722195-33af2100-96be-11eb-8538-5c7e75ded848.jpeg)

For anyone else finding this issue, `include_event_tags` or `includeEventTags` only applies to Attributes and if to include the Event Tags on them (as they inherit from the Event).  It doesn't exclude including them from the Event itself.  You can remove them though prior to update to make sure they are not pushed back (it will not mass delete events).  So doing something like this before updating `event.tags = []` can remove the possibility.

**Comment by mokaddem** [comment]
Wow indeed! Glad you managed to find out the root cause..
Thanks for getting back and updating the issue.
Cheers!
