### ISSUE TITLE
Config.php Error in Security Audit Tool

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7229]
Work Environment

| Type of issue | Support
| OS version (server) | Ubuntu OS
| OS version (client) | Ubuntu, 18.04 LTS
| MISP version / git hash | 2.4.140, hash of the commit
| Browser | Google Chrome

**### Expected behavior**

In the security audit tool there is an error for config.php as below:

![image](https://user-images.githubusercontent.com/54234520/111903266-d9298a00-8a5a-11eb-9330-647665691fd2.png)

**config.php** should have no permissions for other users.

**### Actual behavior**

Upon restart of services after a certain time interval the permissions are reverted back giving other users **read permission** to **config.php.**

**### Steps to reproduce the behavior**

Change the config.php permissions and restart apache to see the error is still available in the Security Audit Tool in the Diagnostic Tab. Also the permissions are reverted back to default.

Thanks,
SB

**Comment by chrisinmtown** [comment]
You think the security audit tool changes the permissions on config.php to give other-users read perms? I.e., `chmod o+r `

Similar issue reported in #7134 and #7220

**Comment by War10ck3** [comment]
@chrisinmtown 

To mitigate the Security Audit - for config.php read permissions to other user. 
	
- Permissions were changed using "chmod o-r" for config.php. 
- Upon restart of apache2- service.  Security Audit - File Permissions disappears for a certain time interval. 
- File permissions are reverted back , giving read permissions to other users for config.php . 

We want to understand if there is any service reverting this permissions on config.php ? If so, how do we ensure to mitigate this security audit risk since it is on higher level ?

**Comment by iglocska** [comment]
Fixed it on develop, will be merged for the next release.

Quick explanation: config.php isn't actually changed when you make a modification. It gets copied to a backup file and a new config.php is created under a temporary name. The new temp file is then renamed to config.php. 

This means that the new file creation will follow umask and as such ignore the previous file permission. The above patch will capture the previous permissions and set the new file to be in line.
