### ISSUE TITLE
Scirius crash on deleting source

### ISSUE THREAD

**Issue by yehias** [MISP/MISP#723]
when I try to delete a source scirius crash 

DoesNotExist at /rules/source/18/delete

SourceAtVersion matching query does not exist.

Request Method: 	POST
Request URL: 	https://hq-ips/rules/source/18/delete
Django Version: 	1.8.4
Exception Type: 	DoesNotExist
Exception Value: 	

SourceAtVersion matching query does not exist.

Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 334
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
 '/opt/selks/scirius',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap']

 /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response

                                    response = wrapped_callback(request, *callback_args, **callback_kwargs)

     ...

▶ Local vars
/opt/selks/scirius/rules/views.py in delete_source

                        source.delete()

     ...

▶ Local vars
/opt/selks/scirius/rules/models.py in delete

                        self.needs_test()

     ...

▶ Local vars
/opt/selks/scirius/rules/models.py in needs_test

                        sourceatversion = SourceAtVersion.objects.get(source = self, version = 'HEAD')

     ...

▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py in manager_method

                                return getattr(self.get_queryset(), name)(*args, **kwargs)

     ...

▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get

                                self.model._meta.object_name

     ...

▶ Local vars

**Comment by adulau** [comment]
Are you sure this is related to MISP?  It seems to be related  https://github.com/StamusNetworks/Scirius maybe you should check with @regit

**Comment by yehias** [comment]
My apologies its my mistake yes it's related to stamus

**Comment by adulau** [comment]
Thank you for the feedback. No worries. I'll close the issue then. Cheers.
