### ISSUE TITLE
OpenIOC import fails

### ISSUE THREAD

**Issue by abulhol** [MISP/MISP#724]
I have tested the OpenIOC import, and it failed.
I used an example file from the OpenIOC website:
http://openioc.org/iocs/c32ab7b5-49c8-40cc-8a12-ef5c3ba91311.ioc
First, I received an internal server error and checked the log:

    Error: Fatal Error (1): Call to a member function generateUuid() on a non-object in [/var/www/MISP/app/Controller/EventsController.php, line 2133]
This refers to the part where the .ioc gets saved as an attachment. I put this $saveEvent part into block comment and tried again. 

Now I get the same kind of error related to generateUuid() from another controller:

    Fatal Error (1): Call to a member function generateUuid() on a non-object in [/var/www/MISP/app/Controller/Component/IOCImportComponent.php, line 564]
What could be wrong here?

**Comment by iglocska** [comment]
Have a fix ready, will push it soon.

**Comment by abulhol** [comment]
Thanks for the quick bugfixes!

**Comment by iglocska** [comment]
Thank you for the bug-reports :)
