### ISSUE TITLE
[QUESTION] Send emails without attributes when new event is published possible?

### ISSUE THREAD

**Issue by torsolaso** [MISP/MISP#7240]
Hello everyone,

I am configuring the sending of emails in MISP, and I am wondering if it would be possible to send notification emails when events are published, but without including attributes. I can't find anything about it in the documentation. Is it possible to configure that?

regards,
thanks in advanced

**Comment by JakubOnderka** [comment]
Hello, it will be possible when MISP 2.4.141 will be released by setting `MISP.event_alert_metadata_only` to `true`.

**Comment by torsolaso** [comment]
Thanks @JakubOnderka is working.
