### ISSUE TITLE
how to create certificate for MISP

### ISSUE THREAD

**Issue by yehias** [MISP/MISP#726]
I'm getting error SSLCertificateFile: file '/etc/ssl/private/misp.local.crt' does not exist or is empty
and apache2 not startup while I already generate a certificate using openssl

**Comment by adulau** [comment]
This is the certificate for the HTTP server.  Nothing directly related to MISP.

For your information, here is a tutorial: http://www.akadia.com/services/ssh_test_certificate.html

I hope this helps.
