### ISSUE TITLE
Attribute dropped log entry omits details about the failure

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7279]
Log entries lack critical detail about validation failure causing an attribute to be dropped when using MISP version 2.4.137.
Here's an example of a terse message:
```
Attribute dropped due to validation for Event 224456 failed: N/A/url online-reverse-login.com 
```
I think "N/A" means it received no category.  The message originates from one of these lines of code in app/Model/Attribute.php:
```
./app/Model/Attribute.php:                    'title' => 'Attribute dropped due to validation for Event ' . $eventId . ' failed: ' . $attribute_short,
./app/Model/Attribute.php:                'title' => 'Attribute dropped due to validation for Event ' . $eventId . ' failed: ' . $attribute_short,
```
Is the missing category the problem? Is it a dupe?  This log message does not pinpoint the problem.

Please extend the error message that is logged when an attribute is dropped to show the reason why it was dropped.  Thanks for considering it.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | N/A

### Expected behavior

The log shows exactly why the attribute was dropped

### Actual behavior

The log omits critical detail

### Steps to reproduce the behavior

Add an attribute to an event that's a duplicate.

**Comment by chrisinmtown** [comment]
I'm pretty certain (altho not 100%) that these attributes are being dropped because they are duplicates.  But it would be really useful to know that for certain, and confirm that no information is lost because I sent an invalid type-value combination or something like that.

**Comment by mokaddem** [comment]
@chrisinmtown What does the `change` field in the logs says? You should have a JSON encoded string of the validation error there.

**Comment by chrisinmtown** [comment]
Thanks @mokaddem for pointing me to the change field.  Temporary blindness I guess, now I see the detail there, for example:
```
Validation errors: {"value":["A similar attribute already exists for this event."]} 
Full Attribute: {"uuid":"c38bffee-5373-4d4d-97cb-5b99f2172073","type":"other",
"value":"21-00009253","category":"Internal reference","to_ids":false,"disable_correlation":false,
"comment":"PySight21-00009253","event_id":"172479","object_id":0,"distribution":5} 
```
Sorry to bother you with this.
