### ISSUE TITLE
Distribution level event - attributes

### ISSUE THREAD

**Issue by abulhol** [MISP/MISP#728]
Suppose I import an event with attributes via the API, and the distribution is set to 0 for all. 
Later on, I decide to publish my event to everybody, setting the Distribution for the Event to "All communities". However, the attributes remain set on 0 ("Your organisation only"), so what will happen? 
Is the event published without attributes?
Is there a way to synchronize the distribution level between the event and the attributes?

**Comment by iglocska** [comment]
In 2.3 the Attribute are completely controlled separately. Via the interface, you can mass edit all of the attributes quickly (on the event view click View all to see all attributes), check the checkbox in the attribute table header, click edit selected attributes and change the distribution level.

In the upcoming version there is a new distribution level called inherit event that should help with your use-case.

**Comment by abulhol** [comment]
Thank you, that is good to know. I do not see any item labeled "View all", but I managed to select all attributes using the first checkbox on the attributes table, and then edited the distribution.

**Comment by iglocska** [comment]
Ah the view all only shows up if you have more attributes than what fit on
one page by default (think it's 50 or 60).

On Tue, Nov 24, 2015 at 4:22 PM, Benjamin Gathmann <notifications@github.com
