### ISSUE TITLE
AbstractMISP is not defined

### ISSUE THREAD

**Issue by mihdim777** [MISP/MISP#7284]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 20.04
| PHP version               | 7.4
| MISP version / git hash   | Currently installed version… v2.4.141 (e3325a1fe16374369f90c4a7c513848b5bfa8a64)

Hello!

I have checked the logs in debug.log and I have noticed that it get an error with AbstractMISP. I don't know if it supposed to be like this. Attached a screenshot:
![image](https://user-images.githubusercontent.com/81242256/113274042-e90c5e00-92e5-11eb-9cbb-f6ae35df6a25.png)

Thank you!

**Comment by Rafiot** [comment]
it is a python script, and you need PyMISP installed for it to run.

I'm worried your MISP installation is incomplete, but please refer to the install guide (search for PyMISP): https://misp.github.io/MISP/INSTALL.ubuntu2004/

**Comment by chrisinmtown** [comment]
Installing PyMISP from source is not for the faint of heart .. nor for people behind proxy servers.

**Comment by mihdim777** [comment]
I have installed PyMISP in venv and it works fine now. Thank you very much guys!
