### ISSUE TITLE
[QUESTION] How to add new fill forms on event create page?

### ISSUE THREAD

**Issue by sarybas1998** [MISP/MISP#7290]
![misp](https://user-images.githubusercontent.com/33090228/113409883-ff90e300-93d3-11eb-870a-bd74e0c45699.PNG)

**Comment by mokaddem** [comment]
Hello,
Have you tried using tags (preferably coming from taxonomies) to classify event by `incident type`?
This is considered as the best practice.

Feel free to have a look at what is offered by default on a MISP instance (https://github.com/MISP/misp-taxonomies) and let us know if your use case is not covered.
Thanks!
