### ISSUE TITLE
Update feed REST API call sets fixed-feed event_id value to zero 

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7293]
In version 2.4.137 using the REST API to update a feed, the MISP server sets the fixed event ID to zero on any update to a CSV or freetext-format fixed-event feeds-table entry. The update data sent includes the event_id field.  For example, I tested by fetching a feed object from the server, changing that feed's distribution only, and sending back the changed object. So I was shocked when the feed's fixed event_id value, with 20695 attributes hanging from it, was zeroed out.

In contrast, if I edit the feed entry on the web UI, I can change properties like sharing group and the event_id is preserved, *NOT* lost. I can even restore the lost event_id caused by the REST API update.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.137
| Browser                   | n/a

### Expected behavior

Fixed-event csv/freetext feed's event_id is left intact on an update.

### Actual behavior

Fixed-event csv/freetext feed's event_id is set to zero on an update.

### Steps to reproduce the behavior

Use PyMISP to get the server's feed dict, change the sharing group, then send it back as an update.

### Logs, screenshots, configuration dump, ...

I'll work on a SSCCE.

**Comment by chrisinmtown** [comment]
Here's code to reproduce the problem.
```
#!/usr/bin/env python3
"""
Show that updating a CSV/freetext fixed-event feed entry zeros out its event_id field
"""
import sys
import urllib3
from pymisp import PyMISP

FEED_ID = 9
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
pymisp = PyMISP(url='https://misp.my-company.com:48752', ssl=False,
                key='my-key')
print(f'Fetching feed {FEED_ID}')
outer_feed = pymisp.get_feed(feed=FEED_ID)
feed = outer_feed['Feed']
print('Feed key=val:')
for key, val in feed.items():
    print(f"\t{key}={val}")

if feed['source_format'] != 'csv' or not feed['fixed_event']:
    print('Not a CSV, fixed event; exiting')
    sys.exit(1)

D = 'distribution'
if feed[D] == '3':
    feed[D] = '4'
else:
    feed[D] = '3'

print(f'Updating feed for distribution {feed[D]}')
# send the inner feed only
# this avoids 'Tags' in the original result
updated = pymisp.update_feed(feed)
for key, val in updated['Feed'].items():
    print(f"\t{key}={val}")
```

**Comment by chrisinmtown** [comment]
Here's output showing the unexpected behavior
```
Fetching feed 9
Feed key=val:
	id=9
	name=Tor exit nodes
	provider=TOR Node List from dan.me.uk
	url=https://www.dan.me.uk/torlist/?exit
	rules={"tags":{"OR":[],"NOT":[]},"orgs":{"OR":[],"NOT":[]}}
	enabled=True
	distribution=4
	sharing_group_id=13
	tag_id=1388
	default=True
	source_format=csv
	fixed_event=True
	delta_merge=True
	event_id=180306
	publish=True
	override_ids=False
	settings={"csv":{"value":"","delimiter":""},"common":{"excluderegex":""}}
	input_source=network
	delete_local_file=False
	lookup_visible=True
	headers=
	caching_enabled=True
	force_to_ids=False
	orgc_id=33
	cached_elements=1696
	coverage_by_other_feeds=94.22%
Updating feed for distribution 3
	id=9
	name=Tor exit nodes
	provider=TOR Node List from dan.me.uk
	url=https://www.dan.me.uk/torlist/?exit
	rules={"tags":{"OR":[],"NOT":[]},"orgs":{"OR":[],"NOT":[]}}
	enabled=True
	distribution=3
	sharing_group_id=0
	tag_id=1388
	default=True
	source_format=csv
	fixed_event=True
	delta_merge=True
	event_id=0                                            <<<<<-------- LOOK!
	publish=True
	override_ids=False
	settings="{\"csv\":{\"value\":\"\",\"delimiter\":\"\"},\"common\":{\"excluderegex\":\"\"}}"
	input_source=network
	delete_local_file=False
	lookup_visible=True
	headers=
	caching_enabled=True
	force_to_ids=False
	orgc_id=33
```

**Comment by chrisinmtown** [comment]
Here's why:

https://github.com/MISP/MISP/blob/0269ebd0fb9542b34f468d99cfa64bdd80150351/app/Controller/FeedsController.php#L351

The FeedsController's edit() method gives special treatment to REST requests for fixed-event CSV/freetext feeds. It looks for a secret, completely undocumented feed dict attribute named 'target_event'.  If that is present, it sets the event_id to that value; if not present, it zeroes it out.

This quirky 'target_event' attribute is never mentioned or used, not even once, in file Model/Feed.php. Nor does that string occur in PyMISP.  But it's used in a bunch of places in Controller/FeedsController.php.

This is really *STRANGE*.  But it seems like a feature.  Please advise if I should be changing this issue to a documentation issue, or if you would like to treat it as a bug.

**Comment by chrisinmtown** [comment]
For anyone who has this problem, here's a patch to the SSCCE above that makes it work as expected
```
# HACK
if ('fixed_event' in feed
        and feed['fixed_event']
        and 'source_format' in feed
        and (feed['source_format'] == 'csv'
             or feed['source_format'] == 'freetext')
        and 'event_id' in feed):
    feed['target_event'] = feed['event_id']
    del feed['event_id']
```

**Comment by mokaddem** [comment]
Hey, I pushed the fix on the dev branch.
This should solve your issue.
Thanks a lot for all the details!

**Comment by chrisinmtown** [comment]
Thanks @mokaddem for the comment but in your commit 10efa54 I do not see any change to the behavior that looks for rest, csv/freetext, field target_event; and no change to the code that zeroes out the event_id field. Please explain what you're telling me here or what I am missing.

**Comment by mokaddem** [comment]
Sure thing!
If you pay close attention, this line has been removed
https://github.com/MISP/MISP/commit/10efa547f4591896d0865ac4ce8dd96f57df9769#diff-7d4b6532f48d9b0b77703cd051e3efb5caa63240e5ef9fe05eb93fa87c30562dL375

What it was previously doing was resetting the object to be saved, then injecting the provided data. This means that if you were to execute the following query, you would in fact wipe out anything not provided in the query.
```javascript
// /feeds/edit/[ID]
{
    "enabled": true
}
```

Now with this line removed, the query's data will only override fields that have been provided. This means that you have to provide the field if you want it to be updated, otherwise, it will remain untouched.

I hope it clears out any concerns!

**Comment by chrisinmtown** [comment]
Thanks Sami @mokaddem for explaining, but as you can see in the code posted in this issue, the feed-update operation provides the event_id field in the update (which I think you are calling the query).  The existing block of code in FeedsController that explicitly zeroes out the event_id field remains untouched by this recent change. Does this make sense?

**Comment by mokaddem** [comment]
@chrisinmtown Indeed, if you wanted to change the `event_id` field of a feed, you had to pass the ID via the `target_event` property, otherwise it would zero it out. Now, if you don't pass it, it will recover the ID from the already saved feed, thus, keeping it as is.
Thanks for the report!

**Comment by chrisinmtown** [comment]
Thanks @mokaddem please post here the version where this is fixed (or will be fixed).

**Comment by chrisinmtown** [comment]
I think the answer to my question is, v2.4.142.
