### ISSUE TITLE
download MISP data base on my localhost ??

### ISSUE THREAD

**Issue by aymenbnl** [MISP/MISP#7295]
Hi,
I want to download MISP data base on my localhost but I don't know with which data base MISP work or how to download it.
Can someone help me ??
Thank you !

**Comment by mokaddem** [comment]
Hello,
You can download data from the feeds (in the UI, `Sync action -> list feeds`) or setup a sync connection with another community.
Feel free to have a look here https://www.misp-project.org/communities
