### ISSUE TITLE
Text Export - restrict by result count

### ISSUE THREAD

**Issue by pl-gl** [MISP/MISP#730]
When exporting data using Text Export, there are lots of useful ways to limit the query. One thing we would find useful would be to limit to the most recent X rows returned by the query. 

For instance, return the most recent 100 ip-dst values from the DB.

**Comment by adulau** [comment]
The last option might help you in such case.  If you want to get the last ip-dst from the last 5 days.

~~~~
https://<YOUR MISP>/attributes/text/download/ip-dst/null/null/null/null/null/5d
~~~~

**Comment by Rafiot** [comment]
@pl-gl Does it work for you?
