### ISSUE TITLE
How to change events date??

### ISSUE THREAD

**Issue by Sue1990** [MISP/MISP#7310]
when I uploaded my events, it created today's timestamp. (below picture)
But I wish it can change to last day timestamp, How could I change it ?
I have ever try below programming:

attri = MISPAttribute()
attri.timestamp = indicator['timestamp']  or attri.date = indicator['timestamp']

all of these not work.

How could I change the date
<img width="287" alt="截圖 2021-04-07 下午2 54 18" src="https://user-images.githubusercontent.com/39720327/113823360-26269380-97b1-11eb-9a1c-8921c1734721.png">

**Comment by mokaddem** [comment]
Hello,
The attribute `timestamp` is primarily meant for synchronization and `last_edit` time. It's viewed as bad practice to try to enforce it.
If you want to describe that and `ip-src` has been seen at a particular date, or for a specific period, please use the `first_seen` and `last_seen` fields.
They are available both in the UI and in PyMISP.
I hope that helps!
