### ISSUE TITLE
Could not use crontab to add event?

### ISSUE THREAD

**Issue by Sue1990** [MISP/MISP#7311]
I have already finished my programming in python.
I tried the command 『python3 xxx.py』in my environment and it does work.
But when I used crontab to run my script to upload events automating, it does not work.
I checked my Syslog, I am sure my crontab has worked, but the MISP website doesn't show any events created.
I searched method in 『Automating certain console tasks』and I tried 『path/MISP/app/Console/cake event import event --publish user_id 』, it described file should use JSON file. 

path/MISP/app/Console/cake event import event --publish user_id  << Is  this method correct?

and why can't run the script in crontab directly?

**Comment by chrisinmtown** [comment]
We run many PyMISP-based scripts from crontab just fine.  One thing to check, if you are using a venv, is that the crontab must run your script with the appropriate virtual environment activated.

**Comment by Sue1990** [comment]
@chrisinmtown  thanks , I resolved the problem.
