### ISSUE TITLE
CSRF prevents deleting event from Event display screen left sidebar link

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7329]
I'm using MISP 2.4.141. On a freshly loaded view-event screen I cannot delete that event, the result is a cross-site request forgery request-blackholed screen.  But if I use the event list screen, check the box on the row with my event, click the trash-can icon at the top, then confirm the action I can delete the event every time -- so I know I have the required privileges.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.141
| Browser                   | Firefox

### Expected behavior

I can delete the event using the left sidebar link.

### Actual behavior

```
You have tripped the cross-site request forgery protection of MISP

CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.

Alternatively, click here to continue to the start page.
```

### Steps to reproduce the behavior

1. Add event, enter event info, click Submit
2. In the events list, click on the new event
3. View the new event, then in the left sidebar click the Delete event link
4. In the dialog box "Are you sure you want to delete event #12345" click OK. 

### Logs, screenshots, configuration dump, ...

The error.log file shows this:
```
2021-04-12 17:21:58 Error: [BadRequestException] The request has been black-holed
Request URL: /events/delete/225730
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(EventsController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(EventsController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(104): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```

I used my browser's inspector to check the form that has the Delete Event link.  I see a token is present:
```
<input type="hidden" name="data[_Token][key]" value="bea0387e2981ad429c00be2b4928389ee1b36ab0fbb6f9fa41af67d22736b38bb06c91b82e6d89313dd75fd62c1fe07e90625c153f6d5f24650615b23e27abe2" id="Token1270920382" autocomplete="off">
```
So I definitely see a token coming across to my browser. But what gets back to the server?

To answer that, I extended  file /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php near line 784 with these lines:
```
                if (is_null($token)) {
                        CakeLog::write('debug', 'SecComp._valCsrf: sess tokens null');
                }
                else {
                        CakeLog::write('debug', 'SecComp._valCsrf: sess tokens ' . json_encode($token['csrfTokens']));
                }
                CakeLog::write('debug', 'SecComp._valCsrf: reqst token ' . $requestToken);
```
Then I click the delete link and OK in the dialog, result is that the debug log shows this:
```
2021-04-12 18:32:49 Debug: SecComp._valCsrf: sess tokens {"ee85d67647c5282d2bf7bb3bbece80ecdf925fa8d6e715a032d7bd614a9740bc549fa1bc6f89e00f1a2e3130b269151a057a1a43c96bcc27f12fcce521fefb1d":1618254081,"37eecfedacd3c15fad5d695504ed2834b5e22f5fc7bd72647edd230ace6d81352e020a769c2dec168f6220b3f823a3797b87e32b21309d29a1919db8f3928293":1618254166}
2021-04-12 18:32:49 Debug: SecComp._valCsrf: reqst token bea0387e2981ad429c00be2b4928389ee1b36ab0fbb6f9fa41af67d22736b38bb06c91b82e6d89313dd75fd62c1fe07e90625c153f6d5f24650615b23e27abe2
2021-04-12 18:32:49 Debug: SecComp.startup: CSRF token mismatch
```

This output confirms for me that the PHP server receives back from my browser exactly the token it put in the web form.

So I guess you can ask many questions here.  Why does my server session not have the expected token?  Or, why does MISP send out in the browser form something different than the latest session token? Please suggest any ideas for debugging *that*.

**Comment by chrisinmtown** [comment]
In a gitter.im chat @iglocska  suggests:

>andras
@andras:matrix.circl.lu
[m] 14:43
Basically the form contained in the delete button gets its tokens invalidated by Ajax calls generating follow up requests
I started refactoring all in-line forms

**Comment by bartblaze** [comment]
I have seen the same thing - appears to happen also when you display/show the potential false positives in an event, then try to delete it. Just remove the trailing # after the event ID and refresh, it should work.

**Comment by chrisinmtown** [comment]
Worked once for me in version 2.4.147, did you all fix this bug but forget to mark this issue?

**Comment by iglocska** [comment]
Yeah, it was fixed a while back.

**Comment by chrisinmtown** [comment]
@iglocska we upgraded to 2.4.147 yesterday and I swear this worked once for me, but it has failed 5 times in a row.  Are you really 100% certain you fixed this?  I do this: click Add Event, type an event info string, submit; then on the view event detail screen I click Delete Event link on the left, then OK I am sure.  Every single time I get "You have tripped the cross-site request forgery protection of MISP". 

Is there some other setting that might influence the behavior here?  If not I'd like to reopen this issue, but I don't have that privilege.
