### ISSUE TITLE
documentation bug: $baseurl/events/automation is wrong concerning the JSON url

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#733]
To quote the automation page:

```
JSON:

https://example.com/events/xml/download.json
```

However, this does not download JSON data. It downloads XML.
Even when setting the accept header to application/json, this will not change. 
The correct way to query would be:

```
curl -H "Accept: application/json" -H Authorization:XXX https://example.com/events
```

**Comment by iglocska** [comment]
No, you are indeed correct, that API in general is utterly terrible and only kept for legacy reasons. I'll remove it from the documentation soon, as it's been superseded by the search API. 

GET on /events /events/id will indeed get you the event in json format, but the original idea behind the /xml/ api was that you could pass along an object with filter parameters to get a set of events that match the criteria. If you append .json at the end of the url you can pass a json object along and get an XML of the filtered events back, which doesn't make much sense.

I'll deprecate the /xml api and rework the automation documentation to make a bit more sense.

**Comment by elhoim** [comment]
@iglocska by deprecating the /xml/ API do you mean retiring it? For v2.4? Because my $dayJob ArcSight integration is based on XML for the moment...

**Comment by iglocska** [comment]
Is it based on /xml or just the XML format APIs? Also, the future plan is
to have 1 API that allows you to define a return format and parameters for
filtering / scoping. Once we have that we can still set up routing rules
for the old APIs though.
