### ISSUE TITLE
Export events in STIX 2 via REST API

### ISSUE THREAD

**Issue by stmtstk** [MISP/MISP#7335]
**Is your feature request related to a problem? Please describe.**
I could not find any related problems in issues.

**Describe the solution you'd like**
MISP allows end-users to export an event in STIX 2.1 via Web console.
It is very useful to share CTI among humans, but not particularly convenient for systems.
However, unfortunately, MISP can not export it via REST API.
We should add a REST API endpoint to export in STIX 2 format.

**Describe alternatives you've considered**
We can export events in STIX 1 format from MISP, using REST API.
After export, we can convert them from STIX 1 to STIX 2.
However, it is not cool.

**Additional context**
N/A

**Comment by iglocska** [comment]
What? The MISP API allows you to get responses in STIX format just the same, an example:

POST to:

`/events/restSearch`

body:
```
{
    "returnFormat": "stix2",
    "eventid": 666
}
```


or 

```
{
    "returnFormat": "stix2",
    "timestamp": "7d"
}
```

etc

**Comment by chrisinmtown** [comment]
@stmtstk are you using PyMISP?

@iglocska here's what the PyMISP docstring offers:

>         :param return_format: Set the return format of the search (Currently supported: json, xml, openioc, suricata, snort - more formats are being moved to restSearch with the goal being that all searches happen through this API). Can be passed as the first parameter after restSearch or via the JSON payload.

but I believe STIX2 format is optional and must be enabled by adding the Python package. Is there a way to query the REST API for a list of export formats are available to the restSearch interface??

**Comment by iglocska** [comment]
Hmm good question. I mean STIX2 is a default format and should always be available (unless you messed up during the setup as you mentioned. I'll add an endpoint to query for a definitive list based on what's currently available.

**Comment by chrisinmtown** [comment]
A new endpoint that answers available restSearch returnFormat strings would help. I hope the MISP system page /events/automation somehow uses that to display the available return formats (instead of a static string).

**Comment by stmtstk** [comment]
Thanks all!!

I will try to use a `/events/restSearch`endpoint or pymisp.
It is very useful information for me.

Thank you again!

**Comment by stmtstk** [comment]
I tried the `/events/restSearch` and got a STIX 2.0 bundle.
I also understand that MISP returns multiple MISP events in a single STIX 2.0 bundle.

Thank you again.
Please close this issue.

**Comment by chrisinmtown** [comment]
@stmtstk since you opened this issue, you should also be able to close it :)

**Comment by stmtstk** [comment]
OK.

I would be very happy if the STIX version is 2.1, but I will open an issue at another time.
Thank you all.

**Comment by iglocska** [comment]
2.1 is on its way, @chrisr3d is working on it :)

**Comment by iglocska** [comment]
Also, whether it returns a single event or multiple events in the bundle depends on the parameters you pass.

**Comment by stmtstk** [comment]
@iglocska 

Great!!
I am looking forward to using the new REST API feature!!

I will check the REST API POST parameters.
