### ISSUE TITLE
Feeds from intelmq

### ISSUE THREAD

**Issue by mav8140** [MISP/MISP#7337]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Support Questions
I want to feed misp from intelmq
I have selected end bot in intelmq misp output bot there bot is working but considering the other side in misp feeds are not getting collected. 

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/44388752/114834824-92774780-9dee-11eb-969d-4b0e8c937005.png)
![image](https://user-images.githubusercontent.com/44388752/114835472-39f47a00-9def-11eb-82b4-670f1fe4eb80.png)

**Comment by mokaddem** [comment]
Hi,
According to the [intelMQ documentation](https://intelmq.readthedocs.io/en/latest/user/bots.html#misp-feed), the output bot will dump the feed to the `output_dir` feed parameter. Then you just need to point the correct path (or URL if the content is on another server) on MISP side while creating the feed.
I hope that helps!
