### ISSUE TITLE
Cake setSetting CLI set organisation restriction to zero like web UI in config.php

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7346]
I need to clear a plugin (misp-module) setting in config.php, `Plugin.Enrichment_xforceexchange_restrict` should be zero to indicate "No organisation selected".  The web UI lets me do this. The CLI does not. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat 7.4
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.141
| Browser                   | Firefox

### Expected behavior

The cake Admin setSetting CLI gives me a way to set the value to zero just like the web UI.

### Actual behavior

If I send value 0 on the CLI, the server picks an organisation from the table, the one with id 1 (one), and uses that as the restriction.  I think this might be some oddity of treating 0/False, 1/True, but not at all certain.

### Steps to reproduce the behavior

Run this command:
```
/var/www/MISP/app/Console/cake Admin setSetting Plugin.Enrichment_xforceexchange_restrict 0
```
Then check the server, Server Settings & Maintenance, Plugin settings tab, Enhancement section, filter on xforce. 

### Logs, screenshots, configuration dump, ...

```
(venv) [apache@misp Config]$ grep Enrichment_xforceexchange_restrict config.php
    'Enrichment_xforceexchange_restrict' => 1,
(venv) [apache@misp Config]$ /var/www/MISP/app/Console/cake Admin setSetting Plugin.Enrichment_xforceexchange_restrict 0

Welcome to CakePHP v2.10.24 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
No organisation selected
(venv) [apache@misp Config]$ grep Enrichment_xforceexchange_restrict config.php
    'Enrichment_xforceexchange_restrict' => 1,
```

**Comment by righel** [comment]
adding some details.
actually the error is thrown in the web UI too, but ignored, since the method is called with $forceSave='1':
https://github.com/MISP/MISP/blob/bd5aecdfd1fb17319b02bcdd9ed3f649255c6132/app/Controller/ServersController.php#L1487

while when it's called via CLI, $forceSave has it's default value (false):
https://github.com/MISP/MISP/blob/bd5aecdfd1fb17319b02bcdd9ed3f649255c6132/app/Console/Command/AdminShell.php#L349
https://github.com/MISP/MISP/blob/bd5aecdfd1fb17319b02bcdd9ed3f649255c6132/app/Model/Server.php#L2119

**Comment by chrisinmtown** [comment]
Thanks @righel for the assist!

**Comment by chrisinmtown** [comment]
Are you all considering a way for the Cake setSetting feature to support the forceSave option?  Or is there another solution?

**Comment by chrisinmtown** [comment]
Did PR https://github.com/MISP/MISP/pull/7366 address this completely?  I.e., can this be closed now?

**Comment by righel** [comment]
Yes @chrisinmtown, you can now do this without errors:
`/var/www/MISP/app/Console/cake Admin setSetting Plugin.Enrichment_xforceexchange_restrict 0`

On top of that, if you have some validation errors, but you are pretty sure you want to set that value anyway, you can add the `--force` flag to override checks.
