### ISSUE TITLE
Are there any methods to automate populating correlation_exclusions

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#7348]
2.4.141

Other than using the WebUI are there any methods to automate managing the content of correlation_exclusions?

Thanks.

**Comment by github-germ** [comment]
Same question for the `Clean` function. Thx...

**Comment by chrisinmtown** [comment]
I'm sure the server exposes an API, but I don't see it written up here:

https://misp.gitbooks.io/misp-book/content/administration/

nor here:

https://misp.gitbooks.io/misp-book/content/automation/

And I don't see any convenient method in PyMISP either.

**Comment by righel** [comment]
Hello,
Indeed these endpoints are not documented yet, OpenAPI spec is on the way. Here I listed the endpoints currently available for handling correlation_exclusions and sample responses, hope it helps.

**get correlation exclusions list:**
```
curl --location --request GET 'https://misp_base_url/correlationExclusions' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: api_auth_token'
```
sample response:
```json
[
    {
        "CorrelationExclusion": {
            "id": "1",
            "value": "foobar",
            "from_json": false
        }
    }
]

```
**view correlation exclusion by id:**
```
curl --location --request GET 'https://misp_base_url/correlationExclusions/view/[correlation_exclusion_id]' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: api_auth_token'
```
sample response:
```json
{
    "CorrelationExclusion": {
        "id": "1",
        "value": "foobar",
        "from_json": false
    }
}
```

**add correlation exclusion:**
```
curl --location --request POST 'https://misp_base_url/correlationExclusions/add' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: api_auth_token' \
--data-raw '{
    "value": "foobar"
}'
```
sample response:
```json
{
    "CorrelationExclusion": {
        "id": "2",
        "value": "foobar",
        "from_json": false
    }
}
```

**delete a correlation exclusion by id:**
```
curl --location --request POST 'https://misp_base_url/correlationExclusions/delete/[correlation_exclusion_id]' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: api_auth_token' 
```
sample response:
```json
{
    "saved": true,
    "success": true,
    "name": "CorrelationExclusion deleted.",
    "message": "CorrelationExclusion deleted.",
    "url": "/correlation_exclusions/delete/1"
}
```

**initiate correlations cleanup:**
```
curl --location --request POST 'https://misp_base_url/correlationExclusions/clean' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: api_auth_token'
```
sample response:
```json
{
    "saved": true,
    "success": true,
    "name": "Correlations cleanup initiated, based on the exclusion rules.",
    "message": "Correlations cleanup initiated, based on the exclusion rules.",
    "url": "/correlation_exclusions/clean"
}
```

**Comment by github-germ** [comment]
@righel Much appreciated!! I will play with these.

**Comment by iglocska** [comment]
The endpoints are a bit half baked - iirc adding exclusion items is fine, but removing them doesn't recorrelate them correctly yet, so just a warning (for us it was a quick need to be able to block some offending values for which it works though).

I have a new version of that frozen for like a month need to find some time to finish it, that one handles the recorrelation on removal from the exclusion list correctly.

**Comment by github-germ** [comment]
Can I assume that with a fresh install of 2.4.137 or greater that out-of-the-box there are no `correlation_exclusions` pre-populated?

**Comment by iglocska** [comment]
Yep, always empty by default

**Comment by github-germ** [comment]
OK, then I will proceed with an automated add of several followed by a clean which will meet my roll out use case. Thanks!

**Comment by iglocska** [comment]
No worries, let us know if you run into trouble with it, curious if there are any other kinks I might have overlooked.

**Comment by chrisinmtown** [comment]
The version 2.4.141 web UI and the response messages posted above both show URLs with "correlation_exclusions" (snake case with underscore) but @righel shows "correlationExclusions" (camel case).  Are they equivalent?

**Comment by chrisinmtown** [comment]
is the user_id part of `/add/[user_id]'` for real or just a typo?

**Comment by github-germ** [comment]
> is the user_id part of `/add/[user_id]'` for real or just a typo?

just tested, and it's not required.

**Comment by righel** [comment]
> The version 2.4.141 web UI and the response messages posted above both show URLs with "correlation_exclusions" (snake case with underscore) but @righel shows "correlationExclusions" (camel case). Are they equivalent?

Yes, they are equivalent, Cake does some magic supporting bot snake case and camel case for resources names.

> is the user_id part of `/add/[user_id]'` for real or just a typo?

Yes, it was a typo, updated the comment. Thanks for the call out.

**Comment by chrisinmtown** [comment]
Now supported in PyMISP so you might want to close this issue, see https://github.com/MISP/PyMISP/issues/732

**Comment by github-germ** [comment]
Thank you very much for the swift enhancement!
