### ISSUE TITLE
RHEL install docs missing dependency moreutils for sponge in misp-objects/jq_all_the_things.sh

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7353]
The misp-installed utility jq_all_the_things.sh requires command-line utility sponge from the moreutils package. But this dependency is missing from the RHEL7/8 install docs. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | 7.4
| PHP version               | n/a
| MISP version / git hash   | 2.4.141
| Browser                   | n/a

### Expected behavior

All expected utilities are installed.

### Actual behavior

jq_all_the_things.sh fails because the sponge utility is missing.

I propose this change:
```
diff --git a/docs/INSTALL.rhel7.md b/docs/INSTALL.rhel7.md
index 141b6d574..5b36992ee 100644
--- a/docs/INSTALL.rhel7.md
+++ b/docs/INSTALL.rhel7.md
@@ -158,6 +158,7 @@ yumInstallCoreDeps7 () {
   PHP_INI="/etc/php.ini"
   sudo dnf install gcc git zip unzip \
                    mod_ssl \
+                   moreutils \
                    redis \
                    libxslt-devel zlib-devel ssdeep-devel -y
 
diff --git a/docs/INSTALL.rhel8.md b/docs/INSTALL.rhel8.md
index 1932ec6b6..b15e02c2c 100644
--- a/docs/INSTALL.rhel8.md
+++ b/docs/INSTALL.rhel8.md
@@ -151,6 +151,7 @@ yumInstallCoreDeps8 () {
   sudo dnf install gcc git zip unzip \
                    httpd \
                    mod_ssl \
+                   moreutils \
                    redis \
                    mariadb \
                    mariadb-server \
```

**Comment by adulau** [comment]
Thank you!
