### ISSUE TITLE
MISP add multiple events?

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#736]
Not sure if this is possible...
I'm trying to add JSON with more than one event and it doesn't seem to want to work --

One event works ... or one event with multiple attributes - ex: 
{
"Event":{
"date":"2015-11-25",
"threat_level_id":"1",
"info":"TEST",
"analysis":"0",
"distribution":"0",
"orgc":"Malware, Inc", 
"Attribute": [
{
"type":"md5",
"category":"Payload delivery",
"to_ids":true,
"distribution":"3",
"value":"35b759347aee663e36f5b91877749349"},
{
"type":"ip-dst",
"category":"Network activity",
"to_ids":true,
"distribution":"3",
"value":"1.1.1.1"}]
}
}

Looks great in MISP but if I do two events - ex: -
{
"Event":{
"date":"2015-11-25",
"threat_level_id":"1",
"info":"TEST",
"analysis":"0",
"distribution":"0",
"orgc":"Malware, Inc", 
"Attribute": [
{
"type":"md5",
"category":"Payload delivery",
"to_ids":true,
"distribution":"3",
"value":"35b759347aee663e36f5b91877749349"},
{
"type":"ip-dst",
"category":"Network activity",
"to_ids":true,
"distribution":"3",
"value":"1.1.1.1"}]
},
"Event":{
"date":"2015-11-25",
"threat_level_id":"1",
"info":"test event",
"analysis":"0",
"distribution":"0",
"orgc":"Money, Inc", 
"Attribute": [
{
"type":"comment",
"category":"Other",
"to_ids":false,
"distribution":"3",
"value":"5.5.5.5"}]
}
}

It doesn't want to work and just pulls the second event ignoring the first.  

I'm sure I'm just doing something wrong just not sure what... but I haven't seen anyone else using it like this so I wasn't sure.

**Comment by mathurin68** [comment]
Oh, forgot to mention I was using curl --
curl -i -k -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: lL1R1mTH6A6EKQNgfGJazywetMCMMMpbnr2pOW6V" --data "@hybridexample.json" -X POST https://192.168.1.8/events

**Comment by iglocska** [comment]
That is indeed correct, you have to create a separate POST request for each individual event.

**Comment by mathurin68** [comment]
Cool, many thanks, I've learned a lot with this!!
