### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by chirazbenhassine** [MISP/MISP#7361]
I try to consume l'API of misp with ruby, but i can't fix this error  when i execute the file2.rb, please any help! 
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)

![Capture](https://user-images.githubusercontent.com/76632477/115553670-f9dd3d80-a2ad-11eb-8393-c5c6bc6d54f7.JPG)
![2](https://user-images.githubusercontent.com/76632477/115553686-fea1f180-a2ad-11eb-88b2-e64c14956650.JPG)

**Comment by Rafiot** [comment]
You should probably start by searching with the error message before opening issues => https://blog.engineyard.com/ruby-ssl-error-certificate-verify-failed

In your case, you're trying to connect to a HTTPs site with self signed certificate, so you need to force the lib to ignore that (see the **Bad Solutions** section in the link above).

**Comment by righel** [comment]
unrelated to the error, but also the API key goes in the `Authorization` header, not `api_key`.
