### ISSUE TITLE
Taxonomies with ampersand are discarded 

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#737]
Predicates with ampersand in the values are discarded in the interface to add the taxonomy (cf. taxonomies/view/5 on mispbeta). Not sure if this is intended or not.

Regarding escaping in the https://github.com/MISP/misp-taxonomies repository, let me know if there is something that would need to be changed.

**Comment by iglocska** [comment]
Fixed here: 184949cc9f3a2a5132b95ffdff778888e2e59552
