### ISSUE TITLE
"Unexpected Error" when syncing 2 instances

### ISSUE THREAD

**Issue by danvelc** [MISP/MISP#7372]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.2
| OS version (client)       | Kali 2021.1
| PHP version               | PHP 7.4.3
| MISP version / git hash   |  v2.4.142
| Browser                   | Firefox

Hello I've been trying to Sync these two MISP instances. The Ubuntu instance is planned to be the one that uploads feeds, share, etc. so that the Kali instance can pull said feed or events from their server.

When trying to Sync the servers and running a connection test I am getting a 'Unexpected Error'
![image](https://user-images.githubusercontent.com/81994050/116151079-c897af80-a6a9-11eb-8d0b-6330ea56b7f3.png)

What could be the fix for this situation?

Also these instances are connected on the same network. I am virtualizing them on my computer with a Bridged network connection and they can ping each other.

**Comment by mokaddem** [comment]
Hello,
If you hover the error message `Unexpected error`, does it display this text?
```
The server returned an unexpected result. Make sure that the provided URL (or certificate if it applies) are correct.
```
If that's the case, you may have entered an incorrect URL. Most common error is that this URL actually redirect to another one.

Could you check on your side?
Thanks

**Comment by danvelc** [comment]
The URL seems to be correct seems I'm copying the Sync server configuration from the sync user 'Create Sync Config'
![image](https://user-images.githubusercontent.com/81994050/116633246-a0fd4d00-a91e-11eb-9e47-0a101a60e6cf.png)

**Comment by danvelc** [comment]
I'm getting a 302 error as it seems from the logs
```
response () => (<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://192.168.1.116/servers/getVersion">here</a>.</p>
</body></html>
), response-code () => (302) 
```

**Comment by danvelc** [comment]
I am extremely sorry. While I don't know the actual fix I got it to work after setting up a domain and a SSL certificate for my Ubuntu instance now the Kali instance can sync without any issues. Thank you so much for your reply.
