### ISSUE TITLE
Issue Updating to 2.4.142 - Moving files is requested.

### ISSUE THREAD

**Issue by servicepac** [MISP/MISP#7380]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)      | Ubuntu 18.04
| PHP version               |  7.2.24-0ubuntu0.18.04.7 
| MISP version / git hash   | Currently installed version… v2.4.141 (bd5aecdfd1fb17319b02bcdd9ed3f649255c6132)
                                            Latest available version… v2.4.142 (7d4abe0042dd49ad8dccc29225c3e2a9552c14aa) 
| Browser                   | Firefox

### Support Questions
When attempting to press the "update MISP" button on the diagnostics page - i'm getting a lot of unknown files that should be moved/removed. 

in the past i've had to do a git stash but this one is different.

I even tried a hard reset. 

Not sure how to proceed. Server is still working fine - need a way to clear this - tried moving the files to home directory too and it just came back anyway. 

### Logs, screenshots, configuration dump, ...

cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

cd $(git rev-parse --show-toplevel) && git pull origin '2.4' 2>&1

From https://github.com/MISP/MISP
 * branch                2.4        -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
	CODINGSTYLE.md
	GITWORKFLOW.md
	app/Console/Command/APIShell.php
	app/Controller/CorrelationsController.php
	app/Lib/Dashboard/OrgsEvolutionWidget.php
	app/Lib/Dashboard/UsageDataWidget.php
	app/Lib/Dashboard/UsersEvolutionWidget.php
	app/Model/Correlation.php
	app/View/CorrelationExclusions/top_correlations.ctp
	app/View/Correlations/top.ctp
	app/View/Elements/genericElements/IndexTable/Fields/postlink.ctp
	app/View/Elements/genericElements/IndexTable/stupid_pagination_links.ctp
	app/View/Elements/genericElements/ListTopBar/element_text.ctp
	app/View/Elements/serverRuleElements/rules_widget.ctp
	docs/API_Doc.md
Please move or remove them before you merge.
Aborting
Updating bd5aecdfd..7d4abe004

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

fatal: could not open '/var/www/MISP/Plugin/DebugKit/.git' for writing: Permission denied
Failed to clone 'Plugin/DebugKit'. Retry scheduled
fatal: could not open '/var/www/MISP/Plugin/DebugKit/.git' for writing: Permission denied
Failed to clone 'Plugin/DebugKit' a second time, aborting

**Comment by servicepac** [comment]
adding a git status output in case that helps.

MISP# git status
On branch 2.4
Your branch is behind 'origin/2.4' by 223 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   app/files/misp-objects (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        CODINGSTYLE.md
        GITWORKFLOW.md
        INSTALL/dependencies/
        app/Config/config.php.bk
        app/Console/Command/APIShell.php
        app/Controller/CorrelationsController.php
        app/Lib/Dashboard/OrgsEvolutionWidget.php
        app/Lib/Dashboard/UsageDataWidget.php
        app/Lib/Dashboard/UsersEvolutionWidget.php
        app/Model/Correlation.php
        app/View/CorrelationExclusions/top_correlations.ctp
        app/View/Correlations/
        app/View/Elements/genericElements/IndexTable/Fields/postlink.ctp
        app/View/Elements/genericElements/IndexTable/stupid_pagination_links.ctp
        app/View/Elements/genericElements/ListTopBar/element_text.ctp
        app/View/Elements/serverRuleElements/rules_widget.ctp
        app/files/scripts/python-maec/
        docs/API_Doc.md
        python-cybox/
        venv/

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by servicepac** [comment]
Ended up backing up the app/Config directory and doing this - this seem to get it updated:

# WARNING: this can't be undone!

git reset --hard HEAD
git clean -f -d
git pull

make sure you save any files - and it looks like now i'll have to reinstall all the cybox/pymisp/stix stuff as well.

**Comment by iglocska** [comment]
Just a note for posterity: You should never have to git stash / make any modifications in general when updating misp, if you feel the need to make any changes based on the feedback it's a smell of a permission issue or something gone awry with your MISP installation.

**Comment by servicepac** [comment]
Thanks for the info. Don't know why it happens - I sometimes do have to fix permissions too. I've been up and running for 5 years so some of it might be artifacts.  Perhaps it's time for a fresh rebuild.

**Comment by diogodaz** [comment]
Hi,
do you have any idea how to fix this issue in the update?

![image](https://user-images.githubusercontent.com/62973257/138780231-98095019-7cf3-4b10-8f3a-d9e0c702e9d7.png)

**Comment by iglocska** [comment]
That look like a connectivity issue. Make sure that your server can reach github.com on port 443.
