### ISSUE TITLE
Events list always empty after elimination 

### ISSUE THREAD

**Issue by CyRix76** [MISP/MISP#7381]
Hello,
I installed the misp server on 3 different distros, a debian 10, kali linux 2021.1 and Ubuntu server 20.04, after fetching the feeds the events list was populated correctly. Later I cleared the events list by deleting them by selecting all. I then had the need to re-download the same feeds, the job is completed correctly but the list of events is no longer populated for those feeds, only if I fetch from other repositories it is populated, this problem does not arise if the misp server install it on a ubuntu.
The version of misp server is 2.4.141 for all linux distros

Best regards

**Comment by adulau** [comment]
Check the event block list. Everytime an event is deleted in MISP it's added there to avoid getting back unwanted events.

`https://<yourinstanceurl>eventBlocklists` to manage it.

I hope this helps.

**Comment by CyRix76** [comment]
Thank you very much, it works!!!!!!
On debian and kali the eventblocklist is present and I have emptied it now, it works, on ubuntu this list is not populated and each fetch did not present the problem.

Thank you very very much!!!!!
