### ISSUE TITLE
Keep original event ID

### ISSUE THREAD

**Issue by mryayap** [MISP/MISP#7382]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Gentoo
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.140
| Browser                   | Firefox

### Support Questions

Hi All,

I have two instances of MISP (let's say MISP01 and MISP02).
When MISP02 retrieve the events from MISP01, the original ID of the events are lost.

Is there a way to keep the original ID ? (for example create a custom fields "original ID")

Best Regards,

**Comment by mokaddem** [comment]
Hello,
What you are after is the `uuid` field. Its value is kept even after synchronization.
By design, `ID`s are not meant to be kept as is after synchronization.
