### ISSUE TITLE
Question: Adding indicators without an event - scripted import

### ISSUE THREAD

**Issue by jezkerwin** [MISP/MISP#739]
I've started to evaluate MISP and I'm liking what I see so far.

One question I do have. Is it possible to add indicators without needing to assign an 'event' to them.

In my particular use case, I receive an API feed of indicators from a third party vendor and would like to script the import of those indicators to store within MISP.

Is this at all possible.

**Comment by elhoim** [comment]
Nope. But you could create a stub-event that contains all the data from your feed. Then you can either hardcode the event id, or  create & use a specific tag to get the event from the API.

**Comment by iglocska** [comment]
Yeah, think of events as collections of indicators with contextual data, how they are organised into an event (either by being the result of analysis, a received indicator list from a partner, etc) is up to you for interpretation. 

So in your case, @elhoim 's first suggestion would probably be the easiest, have a "living" event that you keep up to date with indicators as they come in and tag it.

**Comment by Rafiot** [comment]
@jezkerwin what do you think about it? Can you consider the issue as resolved?
