### ISSUE TITLE
Correlation Logic Discrepancy 

### ISSUE THREAD

**Issue by jwilczek** [MISP/MISP#7391]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | N/A
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.142, 24185cdba33913ac12724cb3f3bd413e81a1edd4
| Browser                   | N/A

### Expected behavior
Attributes that correlate in MISP should be related in some fashion.

### Actual behavior
Attributes containing binary data seem to be erroneously correlated with otherwise unrelated attributes. For example, we have x509 objects in MISP that contain an attribute of type:text, category:other, objection_relation:serial-number. The value assigned to these attributes is usually a binary number (0x01, 0x07, etc). For some reason, these binary values are correlating with 100,000+ other attributes that are completely unrelated. If I hover over an item in the Related Events column, I see correlating values that are IP addresses, dates, email addresses, domain names, strings, etc, etc.

This is resulting in millions of unnecessary and bogus correlations.

### Steps to reproduce the behavior
Add a binary value to the serial-number attribute of the x509 object. My guess is that this problem extends beyond the x509 object, but I was unable to locate the specific code performing the correlations.

**Comment by iglocska** [comment]
This is indeed weird. I'll have a look, could you paste the full attribute value of a sample that causes that?

**Comment by jwilczek** [comment]
The binary value of `0x01`, as stated in the actual behavior, is a full attribute value that causes this issue. I'm not sure how this data is being added to MISP (I'm not the originator of the information). My guess is either pymisp or automated parsing of a x509 certificate uploaded to MISP. I doubt you can add a binary value using the web UI as I'm guessing it will interpret everything as text.

Possibly adding an attribute through raw SQL with `unhex('1')` as the value would be a good way to test?

**Comment by iglocska** [comment]
Interesting that sounds like a falsey comparison being misunderstood, will play around with it!

**Comment by jsman** [comment]
@iglocska Any luck playing around with this?

I have run into this issue too. In in my case it was the cause for a sync pull to stall. I believe I have this narrowed down to a MySQL comparison operator and the chosen `utf8_unicode_ci` collation for the database fields.

Using this Test event [test_event.txt](https://github.com/MISP/MISP/files/6648425/test_event.txt) I observed the following query in the MySQL query log:
```
SELECT `Attribute`.`event_id`, `Attribute`.`id`, `Attribute`.`distribution`, `Attribute`.`sharing_group_id`, `Attribute`.`value1`, `Attribute`.`value2`, `Event`.`id`, `Event`.`date`, `Event`.`info`, `Event`.`org_id`, `Event`.`distribution`, `Event`.`sharing_group_id` FROM `misp`.`attributes` AS `Attribute` LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event_id` = `Event`.`id`)  WHERE ((`Attribute`.`value1` = '^A') OR (((`Attribute`.`value2` = '^A') AND (NOT (`Attribute`.`type` IN ('ip-src|port', 'ip-dst|port', 'hostname|port')))))) AND (NOT (`Attribute`.`event_id` = 1) AND NOT (`Attribute`.`type` IN ('comment', 'http-method', 'aba-rtn', 'gender', 'counter', 'port', 'nationality', 'cortex', 'boolean', 'anonymised'))) AND `Attribute`.`disable_correlation` = '0' AND `Event`.`disable_correlation` = '0' AND `Attribute`.`deleted` = '0'
```

If the value2 column in the attributes table is an empty string, the comparison '' = _utf8 0x01 ([^A](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#SOH) among many others) evaluate true if using the utf8_unicode_ci collation:
```
MariaDB [misp]> SELECT '' = _utf8 0x01 COLLATE 'utf8_unicode_ci';
+-------------------------------------------+
| '' = _utf8 0x01 COLLATE 'utf8_unicode_ci' |
+-------------------------------------------+
|                                         1 |
+-------------------------------------------+
1 row in set (0.00 sec)
```

In my situation this results in every IOC in the database to be returned and added to a huge query to insert them into the correlations table.

**Comment by iglocska** [comment]
ok that's interesting, how did you end up with this value in the first place?

```
"value": "\u0001",
```

**Comment by iglocska** [comment]
Ah I see, forgot about the rest of the issue. That's an interesting issue.

**Comment by iglocska** [comment]
Hmm the weird thing is I still can't seem to be able to reproduce this. What I've tried:

Added the above test_event.txt, indeed ending up with `"value": "\u0001",` in my new event.
Checked and made sure that I use utf8_unicode_ci for the attribute value1/value2 fields' collations.
No correlations are created when I add attributes without a value2.

**Comment by iglocska** [comment]
Also tried directly manipulating the row in mysql via unhex(1) but got the same result. Which mariadb version are you all using?

**Comment by jsman** [comment]
> ok that's interesting, how did you end up with this value in the first place?

Copy the rendered value of `&#0001;` from a webpage and paste it into the attribute value field in the MISP UI worked for me.

> Which mariadb version are you all using?

I am testing on Ubuntu 18.04 with MariaDB version `10.1.48-MariaDB-0ubuntu0.18.04.1`

**Comment by iglocska** [comment]
OK, I see indeed. If you purely paste a control character it will fail. I'll add additional validation as this should never happen and should have been caught by the not empty clause of attribute validation. Nice find, thanks!

**Comment by iglocska** [comment]
This should remedy future entries:

https://github.com/MISP/MISP/commit/b0272b0a0c4b0820801cbd8ad37addb3b098867b

**Comment by jsman** [comment]
I am trying the fix and running into some [errors](https://github.com/MISP/MISP/files/6655317/errors.txt).

Did you forget to define `$compositeTypes` like a few lines above?
https://github.com/MISP/MISP/blob/b0272b0a0c4b0820801cbd8ad37addb3b098867b/app/Model/Attribute.php#L624

Also stating value1 and value2 indexes are undefined.

I noticed when trying to replace a control code value with a regular value:
<img width="959" alt="Screenshot 2021-06-15 at 13 27 43" src="https://user-images.githubusercontent.com/76534/122047261-34f87a80-cde0-11eb-942e-92e68ac61e04.png">

**Comment by iglocska** [comment]
Should be better now!

**Comment by jsman** [comment]
Ha, it is. Thanks!

Devil's advocate: you removed the composite value validation code all together, so it's still possible to add control codes in composite fields and trigger the bug (for example regkey|value)

Was the reason you chose to fix it at entry, through validation, performance?

Would preventing comparing to an empty string when searching for attributes to correlate around here:
https://github.com/MISP/MISP/blob/e80e7c63483ce0cc15773b3403a646a7d6f5fa0c/app/Model/Correlation.php#L116
cause too much of a performance penalty?

**Comment by iglocska** [comment]
Indeed regkey|value probably needs the same thing applied as that's one of the rare cases where in a composite attribute we do not validate the second component. 

Modifying the lookup for correlations indeed has a potentially larger impact on performance though.
