### ISSUE TITLE
Status failed on job

### ISSUE THREAD

**Issue by devdandi** [MISP/MISP#7393]
# This template is meant for bug reports, if you have a feature request user the other template.

![failed](https://user-images.githubusercontent.com/45485349/117101519-928cb680-ada0-11eb-967d-db4ed0f5e79d.PNG)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.2

### Logs, screenshots, configuration dump, ...

the job always showing failed, but worker has been alive

**Comment by adulau** [comment]
Are the workers running? You should check first if the workers are running. 

`https://<yourmispinstanceurl>/servers/serverSettings/workers`

**Comment by devdandi** [comment]
@adulau of course, all worker has been running and showing alive=>true, ok => true, but job is showing 0

**Comment by devdandi** [comment]
I am using php 7.2 and ubuntu 18.4

**Comment by devdandi** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/45485349/117104283-109f8c00-ada6-11eb-889b-e54a9746826d.png)

**Comment by mokaddem** [comment]
Did you find anything particular in the error logs?
They are in `app/tmp/logs/`

**Comment by devdandi** [comment]
Thank you everyone, i had solved this problem.

**Comment by qbolbk59** [comment]
@devdandi Can you share how you fixed the issue ?

**Comment by devdandi** [comment]
@qbolbk59 you should run on the terminal " sudo -u www-data /var/www/MISP/app/Console/cake Admin startWorker [nameworker]"
