### ISSUE TITLE
Sync through proxy

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#740]
Trying to sync through a proxy.
Connecting to another MISP using HTTPS. No SNI, but the certificate is for **\*.domain.com** and I try to connect to **misp.domain.com**.

The error message on the job page is "Unable to perform enableCrypto operation on CakeSocket".
No additional messages in resque-worker-error.log / resque-scheduler-error.log / error.log or debug.log
No additional messages in MISP app logs.
Enabling debug does not help since it is executed in a job.

Wgetting the page, after adding the same copy/pasted proxy credentials in the shell; works to get the homepage on the same server.

Using debian wheezy latest, php v5.4.45, cakephp v2.7.7, MISP v2.3.169.

**Comment by iglocska** [comment]
Do you have the proxy set up in MISP itself?

**Comment by RichieB2B** [comment]
You can try to use tcpdump to see what MISP actually sends to the proxy. IIRC the CakePHP proxy code does not handle all possible scenario's like authentication problems gracefully.

**Comment by elhoim** [comment]
Thanks for the idea @RichieB2B !
The result is that credentials to the proxy don't get sent.
We try to connect via a proxy on a non-standard port (8102); the HTTP connect gets issued correctly but the basic authentication headers are not present, so the proxy gives a 407 Authentication required.
The credentials are correct, since I used them (copy/paste to be sure to have exactly the same thing) with wget on the command line to fetch the homepage of the remote MISP instance I am trying to sync to.

**Comment by RichieB2B** [comment]
In MISP all communication with external servers is done through the SyncTool class (app/Lib/Tools/SyncTool.php). The code there is pretty straight forward:
```
$proxy = Configure::read('Proxy');
if ($proxy) $HttpSocket->configProxy($proxy['host'], $proxy['port'], $proxy['method'], $proxy['user'], $proxy['password']);
```
So this appears to be an issue with HttpSocket from CakePHP, see
http://book.cakephp.org/2.0/en/core-utility-libraries/httpsocket.html
http://api.cakephp.org/2.7/class-HttpSocket.html#_configProxy

**Comment by RichieB2B** [comment]
What have you set as the proxy.method in the MISP config.php? This should be either Basic or Digest depending on your proxy.

**Comment by elhoim** [comment]
I used Basic since it is what we use.

**Comment by RichieB2B** [comment]
I think I fixed the issue. After overcoming a general issue with SSL via proxies in https://github.com/cakephp/cakephp/pull/7834 I managed to add the Proxy-Authorization header to the CONNECT request in https://github.com/cakephp/cakephp/pull/7836

You can try this fork that includes above PRs: https://github.com/RichieB2B/cakephp/tree/2.7+fixes

**Comment by RichieB2B** [comment]
https://github.com/cakephp/cakephp/pull/7836 has been merged so you can just use the latest CakePHP 2.7 branch: https://github.com/cakephp/cakephp/tree/2.7

**Comment by Rafiot** [comment]
excellent, I update the branch to get the HEAD of cakephp 2.4

**Comment by elhoim** [comment]
Could you also please do this to master branch so 2.3 users can also benefit from it?

**Comment by elhoim** [comment]
@RichieB2B I owe you a beer if it works!

**Comment by adulau** [comment]
@elhoim go for the 2.4 branch (which is now the default branch) ;-)

**Comment by Rafiot** [comment]
Considering as fixed :)

**Comment by RichieB2B** [comment]
Expecting that beer then from @elhoim ;-)
