### ISSUE TITLE
Configuring Attachment Scans

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#7401]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.142 (MISP-RPM)
| Browser                   | Brave Browser

### Support Questions

I am trying to configure attachment scanning on a MISP instance; I've not been able to find any documentation of how to do the MISP configuration, this is what I've got so far.

I have installed and started ClamAV on Socket `/run/clamd.scan/clamd.sock`, per [this guide](https://www.hostinger.com/tutorials/how-to-install-clamav-centos7).

#### Plugin Settings

Recommended | Plugin.Enrichment_clamav_enabled | true | Enable or disable the clamav module.
-- | -- | -- | --
Recommended | Plugin.Enrichment_clamav_restrict | No organisation selected. | Restrict the clamav module to the given organisation.
Recommended | Plugin.Enrichment_clamav_connection | unix:///run/clamd.scan/clamd.sock | Set this required module specific setting.

#### MISP Settings

Optional | MISP.attachment_scan_module | clamav | Name of enrichment module that will be used for attachment malware scanning. This module must return av-signature or sb-signature object.
-- | -- | -- | --

When I upload an attachment, the Jobs page shows that the scan failed with the below error. 

### Logs, screenshots, configuration dump, ...

```
Failed at: Mon May 10 11:42:09 UTC 2021
Exception: Exception
Error: Malware scanning module is not configured.

#0 /var/www/MISP/app/Console/Command/AdminShell.php(687): AttachmentScan->scan('Attribute', '4025964', '171048')
#1 /var/www/MISP/app/Console/Command/AppShell.php(35): AdminShell->scanAttachment()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#7 {main}
```

Any guidance on what else I need to do would be much appreciated.

**Comment by righel** [comment]
Hello @JoeP-oss 
In order to get it working in my environment I did the following:
1. Set the following settings in `/var/www/MISP/app/Config/config.php`:
```
'MISP' => array(
    ...,
    'attachment_scan_module' => 'clamav'
),
'Plugin' =>  array(
     ...,
     'Enrichment_clamav_connection' => 'unix:///var/run/clamav/clamd.ctl'
)
```
In your case replace `unix:///var/run/clamav/clamd.ctl` with `unix:///run/clamd.scan/clamd.sock`.

2. Ensure `clamav` `misp-module` is running:
```bash
$ curl -s http://127.0.0.1:6666/modules | jq '.[] | select(.name=="clamav")'
```
You should have an output like the following:
```json
{
  "name": "clamav",
  "type": "modules",
  "mispattributes": {
    "input": [
      "attachment",
      "malware-sample"
    ],
    "format": "misp_standard"
  },
  "meta": {
    "version": "0.1",
    "author": "Jakub Onderka",
    "description": "Submit file to ClamAV",
    "module-type": [
      "expansion"
    ],
    "config": [
      "connection"
    ]
  }
}
```
If there is no output, update your `misp-modules`.

3. Check `ClamAV` is working on the instance running `misp-modules`:
```bash
$ clamscan ~/Downloads/eicar.com 
/home/lucho/Downloads/eicar.com: Win.Test.EICAR_HDB-1 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8573557
Engine version: 0.103.2
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 13.238 sec (0 m 13 s)
Start Date: 2021:11:02 15:03:15
End Date:   2021:11:02 15:03:28
```
You can get the sample malware file from [here](https://www.eicar.org/?page_id=3950).

Also, you can find some extra info in the original PR/comments of this feature: https://github.com/MISP/MISP/pull/6411

Let me know if that helps,
sorry for the late reply.

**Comment by JoePJisc** [comment]
I missed the above reply at the time, but it does indeed get the attachment scanner to work.
