### ISSUE TITLE
Timestamp enforcement logic is wrong

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#7404]
Recently there was the commit 269253aa78c1230d18c6cf5a4b14afb958ac5c84 which has the following if conditions:

app/Model/Attribute.php
Line 735: `if ($converted['Attribute']['first_seen'] >= $converted['Attribute']['last_seen']) `

app/Model/MispObject.php
Line 203: `if ($converted['Object']['first_seen'] >= $converted['Object']['last_seen'])`

app/Model/ShadowAttribute.php
Line 471: `if ($converted['ShadowAttribute']['first_seen'] >= $converted['ShadowAttribute']['last_seen'])`

However if something has been seen only once then the first-seen and the last-seen can be equal. Currently this implemented logic will return false for that scenario even though it should not.

It only makes sense to check if the first-seen is greater than the last-seen then return false.

**Comment by mokaddem** [comment]
Hey,
`first_seen` == `last_seen` might be pretty common indeed.
Thanks for the feedback!
