### ISSUE TITLE
Events Search By Tag - Please add a View All-Button

### ISSUE THREAD

**Issue by jloehel** [MISP/MISP#7406]
**Is your feature request related to a problem? Please describe.**
I'd like to delete more than 60 events at once by tag. 

**Describe the solution you'd like**
A `View All` Button for events. Something like this would be cool: `https://misp.***/events/index/all/searchtag:1026`

**Describe alternatives you've considered**
A `Delete All` Button

**Additional context**
Deleting a lot of events through the UI is too time-consuming.

**Comment by chrisinmtown** [comment]
For what it's worth, you can fiddle the size of the page shown to you in the UI by adding the path parameters `/page:1/limit:500` (or whatever size you like) to the end of the URL, so for example the URL might be `https://misp.my-company.com/events/index/searchtag:123/page:1/limit:500`. Once you have them all on the screen it's easy to click the select-all box then delete them.

You could also vote on this related issue: https://github.com/MISP/MISP/issues/7151

HTH

**Comment by jloehel** [comment]
> For what it's worth, you can fiddle the size of the page shown to you in the UI by adding the path parameters `/page:1/limit:500` (or whatever size you like) to the end of the URL, so for example the URL might be `https://misp.my-company.com/events/index/searchtag:123/page:1/limit:500`. Once you have them all on the screen it's easy to click the select-all box then delete them.
> 
> You could also vote on this related issue: #7151
> 
> HTH

Thanks a lot. That's not obvious. If the limit is too high the deletion is not possible but 500 is possible. I guess the query string `https://misp.foo/events/delete/[12345,12346,12347,...]` gets too long. Passing some filter to the backend would be nice. I am closing the issue.
