### ISSUE TITLE
How to represent message part data in MISP object-attribute 'email' ?

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7407]
I'm trying to capture some IoC data about emails within a MISP object-attribute.  To state the obvious, every email message may have multiple body parts. For example, it's common for the first body part to be text/plain, the second body part to be text/html, and so on.  Each body part (basically an attachment) has a mime-type, sha256 code, file name, etc. Mostly I'd like to capture that metadata about the attachments, not the actual attachment text or content.

Please suggest the right way to use the MISP "email" object that's defined here:

https://www.misp-project.org/objects.html#_email

The field that seems to be most promising for this is "attachment", which is allowed to appear multiple times.  I suppose I could use that to store the "name" value of the "Content-Type" header from each message part? But I also want to store the sha256 code of each attachment. I don't want to repeat an "attachment" item with different data types like file name and sha256 code. The email object-attribute has no "sha256" field right now. And fields like 'eml' and 'msg' cannot appear multiple times. 

Please suggest better ideas.  I could contribute new (optional) field definitions for the email object if you think that would be useful.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.141
| Browser                   | any

### Support Questions

How to represent data items from blocked (or clicked-on) email attachments?

**Comment by chrisinmtown** [comment]
I'll add a closely related question. I see that some of the email object-attribute facets allow multiple occurrences.  This makes sense for items like `header` but I completely don't understand why items like ip-src allow multiple occurrences:
```
    "ip-src": {
      "description": "Source IP address of the email sender",
      "misp-attribute": "ip-src",
      "multiple": true,
      "ui-priority": 0
    },
```
Would someone please help me understand the intent?  Can a single message really originate from multiple IP addresses?

**Comment by chrisinmtown** [comment]
Was really hoping for a hint here, but after 3 weeks I am not confident further waiting is sensible.

**Comment by adulau** [comment]
You should have a look at the [PyMISP tool/function which does the email import](https://github.com/MISP/PyMISP/blob/main/pymisp/tools/emailobject.py).
