### ISSUE TITLE
Sharing Group membership does not update

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#7408]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   |  2.4.142 (94ebb627c347a8e4faf05f25342a371a3e6759df) 
| Browser                   | Firefox

### Expected behavior

When the owner of a sharing group adds a member organisation to the group, at the next sync all existing members should see the new organisation added both to the event distribution map and to the `sharingGroups/view/1` page.

### Actual behavior

Only the new organisation sees the full list of participant organisations, even if the new member publishes an event to the group, the existing members see the event from the new member, but the new member does not appear in either of the views.

### Steps to reproduce the behavior

1. Set up 3 test instances (OrgA, OrgB, OrgC)
2. As OrgA create the SG1 sharing group
3. As OrgA create and publish an event shared to SG1
4. As OrgB add OrgA as a **local** org and create a Sync User in OrgA
5. As OrgA add OrgB as a **remote** organisation
6. As OrgA add OrgB's server, setting remote org to OrgB
7. As OrgA add OrgB to SG1
8. As OrgA push to OrgB's server (OrgB now sees the event and their view of SG1 correctly shows OrgA and OrgB)
9. As OrgC add OrgA as a **local** org and create a Sync User in OrgA
10. As OrgA add OrgC as a **remote** organisation
11. As OrgA add OrgC's server, setting remote org to OrgC
12. As OrgA add OrgC to SG1
13. As OrgA push to OrgC (OrgC now sees the event and their view of SG1 correctly shows OrgA, OrgB and OrgC)
14. As OrgA push to OrgB's server (OrgB's view of SG1 incorrectly shows just OrgA and OrgB)
15. As OrgC publish an event to SG1
16. As OrgA pull from OrgC's server (OrgA now see's OrgC's event)
17. As OrgA push to OrgB's server (OrgB now sees OrgC's event, but their view of SG1 still incorrectly shows just OrgA and OrgB)

### Logs, screenshots, configuration dump, ...

N/A

**Comment by mokaddem** [comment]
Hello,

Apologies for the late reply.
Thanks a lot for the detailed steps to reproduce your issue.
I tried to follow it while paying close attention to step 12 ad 14 and everything was working as expected.

Just a side note, I modified the event at step 13.B to make sure to event propagate to instance B.
If you also did step 13.B when you tried, would you mind trying once again? Substantial changes have been done on sharing group synchronization since May and this issue might have been resolved in the meantime.

Thanks again!

**Comment by JoePJisc** [comment]
Thanks for the update, I'll try and get a lab back up and running in the next week or two to re-test this.

**Comment by JoePJisc** [comment]
Forgot to update this, yes this now seems to work as expected.
