### ISSUE TITLE
Event Deletion not Replicated by Sync

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#7409]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.142 (94ebb627c347a8e4faf05f25342a371a3e6759df)
| Browser                   | Firefox

### Expected behavior

When an event is deleted by the creating organisation (e.g. due to accidental publication or discovering it to be a false positive) the deletion is replicated to connected servers by the next push/pull.

### Actual behavior

The deleted event remains on the connected servers indefinitely.

Likewise if an event is accidently created as Connected Communities and then switch to Org Only no deletion is triggered.

### Steps to reproduce the behavior

1. Create and publish an event
2. Push it to a remote server
3. Delete the Event
4. Run another Push to the remote server

### Logs, screenshots, configuration dump, ...

N/A

**Comment by gacyn** [comment]
MISP does not sync deleted events. It only pulls the new or updated events from the remote server. You may refer to the pull function here: https://github.com/MISP/MISP/blob/94ebb627c347a8e4faf05f25342a371a3e6759df/app/Model/Server.php#L469

There is no such marking telling which server the event comes from (although you may put a tag on it). MISP can't delete your event just by matching the creator organization.

**Comment by JoePJisc** [comment]
Thanks for confirming; this is what I suspected was the case.

So, to withdraw a shared event, it needs to be edited to mark it as a false positive, e.g. through tagging or removing all attributes and adding a single "Withdrawn" comment attribute, and republishing?

**Comment by gacyn** [comment]
Hmm. I am not sure is it a good workaround but make sure the event has at least one attribute, otherwise the event will be ignored.
