### ISSUE TITLE
Mass Edit Attributes on 2.4-beta

### ISSUE THREAD

**Issue by koenigswinter** [MISP/MISP#741]
Dear all,

On the current 2.4-beta version the "Mass Edit Attributes" function (change distribution | For Intrusion Detection System | Contextual Comment of event attributes) does not work on my test setup.

The circle keeps rotating and does not change the values. A cross check on the current 2.3 version works fine.

Tested Browser on Linux:
Chrome Version 46.0.2490.86
Firefox 42.0

**Comment by iglocska** [comment]
Hello Heiko,

that is weird. I cannot reproduce that, could you check what error message you are getting? After attempting to do the mass edit check if anything pops up in:

/var/www/MISP/app/tmp/logs/error.log

**Comment by koenigswinter** [comment]
Hello Andras,

Yes, it does pop up in /var/www/MISP/app/tmp/logs/error.log

--snip--
2015-12-02 18:32:22 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/editSelected/6
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
--snip--

**Comment by Rafiot** [comment]
@koenigswinter do you still have the problem on the most recent version of MISP 2.4?

**Comment by eCrimeLabs** [comment]
I have just upgraded from version 2.3 to the latest version 2.4 following the upgrade guide.

I experience the error when doing mass updates of e.g. Distribution. I can change it if I'm doing it one at a time,

2016-01-17 14:05:23 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/editSelected/2376
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by eCrimeLabs** [comment]
Just as a follow up this is for:
{"major":2, "minor":4, "hotfix":7}

**Comment by iglocska** [comment]
I can't seem to be able to reproduce this, your request seems to be blackholing (this can be due to an authentication issue or a violation of the CSRF protection). 

Let's have a look at a few things:
Could you check the CakePHP version that you are on? 

cd /var/www/MISP/app/Lib/cakephp 
git status
note down the commit ID

Also, are you using anything non standard in your setup? (Proxy settings, etc).

For your MISP settings, do you see any issues by the configuration tool ( Administration -> settings)? Is the MISP.baseurl setting set correctly?

**Comment by eCrimeLabs** [comment]
git status:
HEAD detached at 7aa6908
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .editorconfig
        modified:   .gitattributes
        modified:   .gitignore
        modified:   .htaccess
        modified:   .travis.yml
        modified:   CONTRIBUTING.md
        modified:   README.md
        modified:   app/.htaccess
.......

        modified:   lib/Cake/bootstrap.php
        modified:   plugins/empty
        modified:   vendors/empty

no changes added to commit (use "git add" and/or "git commit -a")



- No proxy settings
- MISP.baseurl is correct 
- None critical in the Admin settings.

**Comment by Rafiot** [comment]
Did you try to update MISP to the most recent version? If yes, do you still have the issue?

**Comment by amuehlem** [comment]
Hi Raphaël

I've got the same issue (posted it in issue 1055, but we can track it here as this issue was opened first).

Updated my MISP instance to 2.4.33, cakephp commit is 4de9212, followed the standard setup in your documentation. CentOS7, rh-php56, fcgi, ...

Best
Andreas

**Comment by koenigswinter** [comment]
Hi all! Sorry for my late reply. The issue is resolved on my current MISP 2.4.33 instance (test case: mass import of > 1000 attributes via freetext import tool, mass change of distribution).
