### ISSUE TITLE
Cant open Server Diagnostics after updating from 2.4.135 to 2.4.143

### ISSUE THREAD

**Issue by glanzerp15** [MISP/MISP#7411]
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Win10
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.143
| Browser                   | Google Chrome

After updating to the latest version, I can no longer open the server diagnostics.
On the website I get the following error message:
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

The file error.log logs following error message:
Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.tables.DATA_LENGTH' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3489): DboSource->query()
#5 /var/www/MISP/app/Model/Server.php(2645): Model->query()
#6 /var/www/MISP/app/Controller/ServersController.php(1119): Server->dbSpaceUsage()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#12 {main}

**Comment by chrisinmtown** [comment]
FWIW we just upgraded to 2.4.143 (altho not from 2.4.135) and our server shows the diagnostics page just fine. I know this is no help.

**Comment by jloehel** [comment]
Same issue here.

https://github.com/MISP/MISP/blob/282a9c404783f0dadbb401ec57af4dd95d65b7bc/app/Model/Server.php#L2642

The SQL query uses again non-aggregated columns which are not part of the group by. Why do you not write standard/portable SQL queries?

Edit: Why is the group by necessary? It should now work also without a group by.

**Comment by iglocska** [comment]
Should be fixed now, thanks for digging into it!

**Comment by Rafiot** [comment]
As the diagnostic page is unreachable, in there a way to trigger an update from the UI?

**Comment by iglocska** [comment]
Ha, good point. POST something like `{}` to /servers/update via the rest client using a site admin user.
