### ISSUE TITLE
Decay Model Help

### ISSUE THREAD

**Issue by soc-ti** [MISP/MISP#7412]
I have two MISP instances running, one which collects events/attributes and one where I push events into for alerting purposes. Is there a way to use the decay feature to prevent decayed attributes being pushed from one instance to the other?

**Comment by iglocska** [comment]
No, this is not possible and breaks the sharing model of MISP.

**Comment by mokaddem** [comment]
Hey,
There is no way to synchronize data based on the **on-the-fly** calculated decay.
The main reason is if something is not marked as expired, it may be tomorrow. The opposite is also true if context was to be changed or sighting were to be added.
What org usually do is they have two MISP instances. One staging which contains a lot of data (and sometime "junk" data), and another one (sometime called production) which synchronize on this staging only fetching vetted events or by cherry-picking them.
So if you were to modify data on the staging, it will be propagated to the production.
Finally, the decaying for alerting/feeding tools/... should be use on the production instance were the latest version of the data will be residing.
I hope that helps.
Feel free to comment further if this setup does not cover your use-case.
Cheers!

**Comment by adulau** [comment]
Just a complementary information, you can import decay models between instances. This could also help in your case.
