### ISSUE TITLE
How to use correctly Additional Sync Parameters to filter events pull

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#7414]
Hi, 

i would like to know how to use correctly the additional sync parameters that can be found in the Sync configuration.
I would like, for example, to pull only the event that contains the word "Spam" in the event info.
I thought that doing something like **{"info":"%Spam%"}**  would have done the job, but all the events are imported instead.

Can someone help me?

Thanks,
Pietro

**Comment by mokaddem** [comment]
Hi,
You can find the available parameters and a description in the rest client (/servers/rest).
Pick the template `Events->index` and the parameters will appear.
Cheers!
