### ISSUE TITLE
Use API with a txt extention

### ISSUE THREAD

**Issue by ibyf0r3ns1cs** [MISP/MISP#7417]
Hi, there is an option to integrate with MISP API but with a .txt extension ? 
Thank you for the help.

**Comment by iglocska** [comment]
Not sure I understand what you are trying to do, can you give me an example of what you'd request and what result you'd expect?

**Comment by ibyf0r3ns1cs** [comment]
> Not sure I understand what you are trying to do, can you give me an example of what you'd request and what result you'd expect?

Hi, thank you for replaying and sorry for the delay ..
What i am trying to do is integrating between two systems.
The system try to take information from the MISP and i want to use an API with txt extension, for example:
https://<MISP-IP>/attributes/text/download/apikey:<KEY>/domain
https://<MISP-IP>/attributes/text/download/apikey:<KEY>/ip-dst
https://<MISP-IP>/attributes/text/download/apikey:<KEY>/url

same as above but with the .txt extension.
Thank you very much.

**Comment by iglocska** [comment]
First of all, those endpoints are deprecated, you should instead be using restsearch:

POST to /attributes/restSearch

post body:

```
{
    "returnFormat": "text",
    "type": ["domain"]
}
```

For example.

Also, I still don't get the .txt extension, what you receive back is a line separated text file, so still not sure what you'd expect would change by appending .txt...

**Comment by ibyf0r3ns1cs** [comment]
> First of all, those endpoints are deprecated, you should instead be using restsearch:
> 
> POST to /attributes/restSearch
> 
> post body:
> 
> ```
> {
>     "returnFormat": "text",
>     "type": ["domain"]
> }
> ```
> 
> For example.
> 
> Also, I still don't get the .txt extension, what you receive back is a line separated text file, so still not sure what you'd expect would change by appending .txt...

Hi iglocska , thank you again for replaying and trying to assist.
I will explain my self better.
I would like to connect MISP to big data security analytics product to get IOCs into the product that will check network matches in addition to its existing capabilities.
Product's ability to receive threat intel as a TXT or CSV file in API.
MISP knows how to produce it without a problem, but the problem is that they require .TXT or .CSV extension at the end of the API URL.
For example, instead of:
https: // misp url / attributes / text / download / domain
The product receives:
https: // misp url /attributes/text/download/domain.txt
Do you have the ability to help us with this?

**Comment by ibyf0r3ns1cs** [comment]
Any help please ?

**Comment by mokaddem** [comment]
Hey I don't understand what's blocking you here.
@iglocska already replied how you can request different format in MISP.
Doing such query should work out of the box:
```js
// POST /attributes/restSearch.csv
{
    "returnFormat": "csv",
    "type": ["domain"]
}
```
