### ISSUE TITLE
Error When Trying to Connect to Remote Database

### ISSUE THREAD

**Issue by collinh21** [MISP/MISP#7423]
Hello,

I am trying to establish a remote connection between my MISP application server and a MySQL Azure Resource. I have pasted the error message I am receiving.

![image](https://user-images.githubusercontent.com/79159837/117459026-8cb5e300-af10-11eb-9678-ef988155cee3.png)

Here is my database.conf file:
<img width="726" alt="Screenshot 2021-05-07 090128" src="https://user-images.githubusercontent.com/79159837/117461221-ed461f80-af12-11eb-8851-612774e3a262.png">

This is my first post here so let me know if I am missing anything that you need. We are struggling to find a lot of documentation on how to set up a connection with a remote database, but if some exists direction to that may also be helpful.

Thanks!

**Comment by mokaddem** [comment]
Hi,
I'm not familiar with Azure but by the look of it, it seems that something is badly configured on Azure's side.
