### ISSUE TITLE
Report History to avoid mistakes while editing

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#7430]
**Is your feature request related to a problem? Please describe.**
It's possible for an analyst to accidentally erase a report's content. A suggestion would de keep at least two saved history versions to avoid human mistakes.

**Describe the solution you'd like**
A place where a user can visualize raw saved versions of an event report.

**Describe alternatives you've considered**
Education and awareness but are not enough to avoid accidental mistakes.

**Comment by JakubOnderka** [comment]
Hello, this is already possible. Just enable new audit log - `log_new_audit`. Then in audit log you can find whole event report history.
<img width="1481" alt="Snímek obrazovky 2021-05-24 v 10 33 45" src="https://user-images.githubusercontent.com/163343/119320948-6a47f780-bc7c-11eb-9622-24e6fb5469c6.png">
