### ISSUE TITLE
MISP Schedular is not enabled

### ISSUE THREAD

**Issue by krishnamohan152** [MISP/MISP#7442]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.1
| MISP version / git hash   | 2.4.142

## MISP Schedular is not enabled
I recently installed the MISP, in the workers section i am able to see the following are enabled except schedular
![image](https://user-images.githubusercontent.com/28926789/119486459-e114eb80-bd75-11eb-94fc-c8a44a9539c5.png)

Although i did check the systemd process, because ui not able to update and I am getting following status below
● misp-workers.service - MISP background workers
   Loaded: loaded (/etc/systemd/system/misp-workers.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-05-24 12:08:32 IST; 1 day 4h ago
  Process: 21439 ExecStart=/var/www/MISP/app/Console/worker/start.sh (code=exited, status=0/SUCCESS)
    Tasks: 11 (limit: 19660)
   CGroup: /system.slice/misp-workers.service
           ├─ 21490 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='default'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/16
           ├─ 21491 php ./bin/resque
           ├─ 21508 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='prio'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/16218
           ├─ 21509 php ./bin/resque
           ├─ 21526 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/1621
           ├─ 21527 php ./bin/resque
           ├─ 21544 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='email'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/1621
           ├─ 21545 php ./bin/resque
           ├─ 21562 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='update'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/162
           ├─ 21563 php ./bin/resque
           └─115537 php ./bin/resque

May 24 12:08:31 HOST start.sh[21439]: Starting worker ... Done
May 24 12:08:31 HOST start.sh[21439]: Creating workers
May 24 12:08:31 HOST start.sh[21439]: Starting worker ... Done
May 24 12:08:31 HOST start.sh[21439]: Creating workers
May 24 12:08:31 HOST start.sh[21439]: Starting worker ... Done
May 24 12:08:31 HOST start.sh[21439]: Creating workers
May 24 12:08:32 HOST start.sh[21439]: Starting worker ... Done
May 24 12:08:32 HOST start.sh[21439]: Creating the scheduler workers
May 24 12:08:32 HOST start.sh[21439]: Scheduler Worker is not enabled
May 24 12:08:32 HOST systemd[1]: Started MISP background workers.

Ill tried to run manually to execute and getting the same response below
![image](https://user-images.githubusercontent.com/28926789/119487778-6b118400-bd77-11eb-85ec-76fd1d9ea57f.png)

Kindly help me out to resolve these issue.

**Comment by adulau** [comment]
There is no need any more to use the scheduler. We recommend to use the system crontab. The [cli](https://www.misp-project.org/misp-training/a.b-cli.pdf) provides an easy interface to automate many actions from MISP.

~~~
Administering MISP via the CLI

Certain administrative tasks are exposed to the API, these help with maintaining and configuring MISP in an automated way / via external tools.:
Get Setting: MISP/app/Console/cake Admin getSetting [setting]
Set Setting: MISP/app/Console/cake Admin setSetting [setting] [value]
Get Authkey: MISP/app/Console/cake Admin getAuthkey [email]
Set Baseurl: MISP/app/Console/cake Baseurl [baseurl]
Change Password: MISP/app/Console/cake Password [email] [new_password] [--override_password_change]
Clear Bruteforce Entries: MISP/app/Console/cake Admin clearBruteforce [user_email]
Run Database Update: MISP/app/Console/cake Admin updateDatabase
Update All JSON Structures: MISP/app/Console/cake Admin updateJSON
Update Galaxy Definitions: MISP/app/Console/cake Admin updateGalaxies
Update Taxonomy Definitions: MISP/app/Console/cake Admin updateTaxonomies
Update Object Templates: MISP/app/Console/cake Admin updateObjectTemplates
Update Warninglists: MISP/app/Console/cake Admin updateWarningLists
Update Noticelists: MISP/app/Console/cake Admin updateNoticeLists
Set Default Role: MISP/app/Console/cake Admin setDefaultRole [role_id]
Get IPs For User ID: MISP/app/Console/cake Admin UserIP [user_id]
Get User ID For User IP: MISP/app/Console/cake Admin IPUser [ip]
Automating certain console tasks

If you would like to automate tasks such as caching feeds or pulling from server instances, you can do it using the following command line tools. Simply execute the given commands via the command line / create cron jobs easily out of them.:
PullAll: MISP/app/Console/cake Server pullAll [user_id] [full|update]
Pull: MISP/app/Console/cake Server pull [user_id] [server_id] [full|update]
Push: MISP/app/Console/cake Server push [user_id] [server_id]
Cache Feeds For Quick Lookups: MISP/app/Console/cake Server cacheFeed [user_id] [feed_id|all|csv|text|misp]
Fetch Feeds As Local Data: MISP/app/Console/cake Server fetchFeed [user_id] [feed_id|all|csv|text|misp]
Run Enrichment: MISP/app/Console/cake Event enrichment [user_id] [event_id] [json_encoded_module_list]
Test: MISP/app/Console/cake Server test [server_id]
List: MISP/app/Console/cake Server list
Managing the background workers

The background workers can be managed via the CLI in addition to the UI / API management tools:
Get List Of Workers: MISP/app/Console/cake Admin getWorkers [all|dead]
Start A Worker: MISP/app/Console/cake Admin startWorker [queue_name]
Restart A Worker: MISP/app/Console/cake Admin restartWorker [worker_pid]
Kill A Worker: MISP/app/Console/cake Admin killWorker [worker_pid]
~~~
