### ISSUE TITLE
Object could not be saved. template_uuid: Please provide a valid RFC 4122 UUID

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#7445]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               | 7.4.18
| MISP version / git hash   |  v2.4.143 (ce93848deaeb43ee8e5794ef2dea8febb5ae6148) 
| Browser                   | Tried with Chrome and Firefox

### Expected behavior

Add Geo object to existing event.

### Actual behavior

Attempting to add the object fails.

### Steps to reproduce the behavior

Attempting to add a "Geolocation Object" to an event fails with error "Object could not be saved. template_uuid: Please provide a valid RFC 4122 UUID".
The issue started after the upgrade of MISP from 2.4.142 to 2.4.143 and is reproducible on multiple MISP servers.
I deleted and reimported the Geo object template, but this did not help.
Clearing the cache under the Diagnostics page did not help.
Nothing is being logged in the MISP logs.
The error appears at the top of the browser after clicking "Create new object".
The error happens if I try to add a city (New York), region (North America), or country (US) to the object.
Object Template: Geolocation v5

### Logs, screenshots, configuration dump, ...

![misp_object_template_error](https://user-images.githubusercontent.com/8250365/119548880-4c51c400-bd5c-11eb-9ec7-9be1fd9abbfb.JPG)

**Comment by adulau** [comment]
Thank you for the bug report. It should be fixed. It was the UUID of the object template. You can git pull the latest version from 2.4 and update the MISP objects template.
