### ISSUE TITLE
Install script hangs

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#7446]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4. install script for ubuntu 20
| Browser                   | If applicable

### Expected behavior
Finish install

### Actual behavior
Sits at:
~~~
#############################################################################  (76%)
Next step: Updating Galaxies, ObjectTemplates, Warninglists, Noticelists and Templates

Welcome to CakePHP v2.10.24 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
~~~

### Steps to reproduce the behavior
run:
~~~
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M
~~~

**Comment by Rafiot** [comment]
This step takes a very long time, especially if you're running it on a machine with not lot of resources. 

How long have you been waiting?

**Comment by DigiAngel** [comment]
It had been about 20 minutes....cpu and IO was practically nothing, but I'll start it up again if need be..thanks for the quick response...is there a way to "resume" the install?

**Comment by DigiAngel** [comment]
Welp...indeed it did take a LONG time...finally continued on with this error along the way:
~~~
Notice Error: Undefined variable: result in [/var/www/MISP/app/Model/Warninglist.php, line 252]
2021-05-26 13:58:56 Notice: Undefined variable: result in [/var/www/MISP/app/Model/Warninglist.php, line 252]
62 warninglists updated, 1 fails
~~~
