### ISSUE TITLE
LDAP Authentication 

### ISSUE THREAD

**Issue by estebanramos** [MISP/MISP#7447]
My LDAP authentication fails, it doesn't even sends the request to my ldap server. I'm using this conf on config.php. Do i need to configure sites-available on Apache too? 

```
 'ApacheSecureAuth' => array(
                        'apacheEnv'          => 'REMOTE_USER', 
                        'ldapServer'         => 'ldap://your_domain_controller',
                        'ldapProtocol'       => 3,
                        'ldapNetworkTimeout' => -1,  
                        // Note that we need a service account here.
                        'ldapReaderUser'     => 'CN=service_account_name,OU=Users,DC=domain,DC=net', 
                        'ldapReaderPassword' => 'password',
                        'ldapDN'             => 'OU=Users,DC=domain,DC=net',
                        'ldapSearchFilter'   => '', // I don't use that. Maybe you should
                        'ldapSearchAttribut' => 'userprincipalname',  // Make sure this match and works for you
                        'ldapFilter'         => array('mail',),
                        'ldapDefaultRoleId'  => 3,   // this will create users
                        'ldapDefaultOrg'     => '1',      // uses 1st local org in MISP if undefined,
                        'ldapAllowReferrals' => false,   // allow or disallow chasing LDAP referrals - see what works for you. default is true
                        'ldapEmailField' => array('mail'), // whatever works for you
      ),
```

**Comment by Kagee** [comment]
Apache needs to authenticate the user and send the REMOTE_USER-variable to PHP, are you sure this is working as expected? The ApacheSecureAuth-code will only trigger if the REMOTE_USER-variable (technically `$_SERVER['REMOTE_USER']`) is set in PHP.

**Comment by estebanramos** [comment]
Yes, now it's working as expected. The only flaw is sometimes I need to log as a local user. How can I bypass Apache auth and log as normal MISP user?

**Comment by Kagee** [comment]
Any Apache config (source IP, different hostname, etc.) that results in the required header not getting set will make MISP render the normal login form.

**Comment by estebanramos** [comment]
Understood, one solution was open the service in another port and bypass the auth if I have a cookie set but I can't get it to work. One last issue, with Apache auth I can't log out from the page, how can I accomplish that?

**Comment by Kagee** [comment]
That depends on the method you use to authenticate with Apache. As long as Apache sends a header with valid info, a logout will just log you right in again.

**Comment by estebanramos** [comment]
But I can't logout from system. I click "Logout" but I still can use the application like I've never logged out.

**Comment by Kagee** [comment]
You press log out -> Misp logs you out (deleting cookies etc). Then you are sendt to user/login, and because your Apache server is still sending headers with your username, you are logged back in.

**Comment by estebanramos** [comment]
How can I fix that? Maybe a directive when calling the logout route do something to eliminate those headers?

**Comment by mokaddem** [comment]
@estebanramos Unfortunately, there is no clean way to remove the `Authentication` header sent by the browser https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by adulau** [comment]
There is now a standalone LDAP authenticator in MISP which could clearly help in such scenario.

https://github.com/MISP/MISP/tree/29993e516825b8ff35a72419fa61c40472eb1898/app/Plugin/LdapAuth
