### ISSUE TITLE
Allow Org Admins to Create Sync Users

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#7448]
**Is your feature request related to a problem? Please describe.**
On a multi-organisation environment only users with the admin role can create sync users in hosted organisations.

**Describe the solution you'd like**
I think Org Admins (or a new similar role) should be able to create and manage sync users within their organisation, giving greater flexibility.

From my understanding, the only difference is that it allows them to push and pull events automatically, rather than having to do manually, and doesn't grant access to any additional events, etc.

**Describe alternatives you've considered**
The only alternative I can see is continuing to rely on individuals with the admin role to create sync accounts for each organisation.

**Additional context**
This would be particularly useful where sharing arrangements use a central server, which other members connect to in a Star topology (i.e. to remove the need for a full mesh of sync partnerships), while keeping ability to log into the central server if a partner doesn't have a MISP instance yet, or has an issue with their instance.

**Comment by mokaddem** [comment]
Hey,
Just as additional information, sync-users have a special ability to that other roles do not have:
The possibility to create data on behalf of other organisation.
afaik, the restrictions regarding this role have been put in place because of this.
