### ISSUE TITLE
Distribution and Modification map grow while viewing event

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#7449]
### Work environment
This is after I imported my misp.sql file from a different machine

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu Focal
| OS version (client)       | Ubuntu Focal
| PHP version               | 7.4
| MISP version / git hash   | afa0ffd33c24940585194d7c9bc395829034f368
| Browser                   | Chrome

### Expected behavior
Not to grow :)

### Actual behavior
Those entries just get larger and larger.

### Steps to reproduce the behavior
Sit and look at any event.

### Logs, screenshots, configuration dump, ...
Initial view:
![Screenshot from 2021-05-26 12-49-35](https://user-images.githubusercontent.com/947191/119717323-686c6880-be23-11eb-9e3c-07a995756c93.png)

after a minute of viewing:
![Screenshot from 2021-05-26 12-50-46](https://user-images.githubusercontent.com/947191/119717405-7de19280-be23-11eb-8329-e7719c7d4a5c.png)

eventually it crashed the tab.

**Comment by DigiAngel** [comment]
Closed due to lack of community interest (and razing the box for the 3rd time).

**Comment by mokaddem** [comment]
Hey @DigiAngel!
Just going trough the backlog of issues.
Did you manage to solve this issue? I'm very curious to know the reason why this was happening!

**Comment by DigiAngel** [comment]
Nope...had to import from from an exported json file.

**Comment by mokaddem** [comment]
Importing from exported json file is pretty standard. And it should not affect in anyway the issue you have with the UI.
Do you have any entries in your browser console?
What's weird for me is that these UI elements are rendered once and are not refreshed by any means.

**Comment by DigiAngel** [comment]
So the the solution was to import everything from json.  My initial method of importing the sql file from the old instance to the new instance is what caused this to occur.
