### ISSUE TITLE
Run Script on Alert Email | Purpose: Notification System Extension

### ISSUE THREAD

**Issue by geudrik** [MISP/MISP#745]
Currently, I have a cron that reads a mailspool for alerts and pastes them into a slack channel, as the email-based workflow doesn't work for everyone (and it slows collaboration down).

Ideally, I would love to see an option for being able to either manually call a script in the background, or just have a simple configurable module that allows for some kind (slack, in our case) of configurable notifications.

The API for Slack is super easy to integrate with. I'm literally just using regex to rip out info and format a pretty string that allows for a link to our local MISP install. This method allows teams to take action quickly, and collaborate when an alert comes up in channel.

In python, this is the gist of what I'm doing / would love to see as a built-in feature

```
url = re.search('^URL\s*:\s(https://.*/\d*)$', payload, re.MULTILINE).group(1)
rep = re.search('^Reported\sby\s:\s(.*)$', payload, re.MULTILINE).group(1)
lev = re.search('^Threat\sLevel:\s(.*)$', payload, re.MULTILINE).group(1)
des = re.search('^Description\s:\s(.*)$', payload, re.MULTILINE).group(1)
...
sendMessage("[ Alert Level: *{0}* ] {1} reports <{2}|{3}>".format(lev, rep, url, des))
```

**Comment by geudrik** [comment]
Did this ever get implemented? <3

**Comment by dspruell** [comment]
+1 here: would be really cool to have new events in MISP pop to Slack channel.

**Comment by geudrik** [comment]
@dspruell  ping me off list (personal email) and I'll toss you my current hack-n-slash email alerter for slack.

**Comment by tweemeterjop** [comment]
+1 for MISP events in a Slack channel :)

**Comment by adulau** [comment]
Workflow in version [2.4.160](https://www.misp-project.org/2022/08/08/MISP.2.4.160.released.html/) was implemented included some example of notification such as MatterMost via misp-modules or you can also make webhooks or send_mail. In the 2.4.162 will be also have some example with Microsoft Teams webhook.  Feel free to reopen if this doesn't solve your issue.
