### ISSUE TITLE
Sync rules menu and org menu not showing

### ISSUE THREAD

**Issue by csirt-pj** [MISP/MISP#7451]
# This template is meant for bug reports, if you have a feature request user the other template.

As titled, menu is not showing:

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.127
| Browser                   | Safari, Firefox

### Expected behavior
Sync rules menu showing
Orgs menu showing

### Actual behavior
Sync rules menu showing
Orgs menu not showing

### Steps to reproduce the behavior
Create new sync server

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/61319436/119830315-6aeec100-befc-11eb-83d4-25e1ccc520cb.png)

**Comment by mokaddem** [comment]
Hey, we indeed slightly changed the UI of this part recently. Could you update to the latest version and try again?
Thanks!

**Comment by csirt-pj** [comment]
Yes, it did the job, thanks!
