### ISSUE TITLE
importing STIX v.1 to MISP

### ISSUE THREAD

**Issue by Yaels17** [MISP/MISP#7453]
I've been trying to figure out how to do it (via the GUI mainly) and could not find the option

would love for help understanding how to import (either via the GUI or the API)

thanks!

**Comment by adulau** [comment]
There is a menu on the left side on MISP "Import from..." where you can import STIX. 

You can also use the API for more info - https://github.com/MISP/MISP/tree/2.4/tools/ingest_stix

**Comment by Yaels17** [comment]
I've tried uploading an .xml file but got the error : _Could not import STIX document: Issues while loading the stix file. Please check whether the dependencies for STIX are met via the diagnostic tool._
![image](https://user-images.githubusercontent.com/71444851/120104093-860b3c00-c15b-11eb-8c98-15b577416453.png)

all our STIX dependencies are met 
![image](https://user-images.githubusercontent.com/71444851/120104129-aa671880-c15b-11eb-96e4-41699efeb6e4.png)

**Comment by iglocska** [comment]
Could you send us a sample of what is failing for you? Either share it directly here, or if that is not something that you can share publicly send a mail to info@misp-project.org . Thank you in advance.

**Comment by Yaels17** [comment]
I've sent the file via email
thank you
