### ISSUE TITLE
Not able to install from script

### ISSUE THREAD

**Issue by maxifjaved** [MISP/MISP#7457]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 8.0.6
| MISP version / git hash   | 2.4, 845ba86ba54950e422d47e675a1744e7cb132085
| Browser                   | If applicable

### Expected behavior
Should install the MISP

### Actual behavior

```
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 20.04
Next step: Checking if we are uptodate and checksums match
sha1: d560285eff4ef709fd094256982f149b8c8e4110 does not match the installer sum of: 1be149517abf010bbdb4d7cfe03352610df093c8
Delete installer, re-download and please run again.

```
### Steps to reproduce the behavior

1. Clone the Repo
2. Go to INSTALL and run ./INSTALL.tpl.sh
3. Try install ./INSTALL.sh

### Logs, screenshots, configuration dump, ...

![Screenshot from 2021-05-31 23-19-13](https://user-images.githubusercontent.com/17304812/120229467-a4aa2980-c266-11eb-8b0b-453cc151dfdb.png)

**Comment by stevelogik** [comment]
I'm also having a problem installing with their script. It doesn't work

**Comment by maxifjaved** [comment]
@adulau will you please guide me about this.

**Comment by chrisinmtown** [comment]
I suggest you post the Ubuntu version you used.  I also believe that PHP version 8 *does* *not* *work*, is not yet supported.

**Comment by rommelfs** [comment]
I guess some more information about the environment (OS version for instance) would be useful.
Closing for the moment - feel free to re-open.
