### ISSUE TITLE
Can't install on Ubuntu 18.04 with script

### ISSUE THREAD

**Issue by stevelogik** [MISP/MISP#7458]
Trying to install you all's script that you provided on github. Installing on Ubuntu 18.04. It won't install. This is a fresh installation of Ubuntu and when running the script it goes into an endless loop of:

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

It will do this forever until I cancel out. How can I fix this or get MISP installed on Ubuntu, you all's script does not work and I can't find another solution online

**Comment by stevelogik** [comment]
@adulau @sfossen @bemre @liedekef If you know of a solution please let me know

**Comment by stevelogik** [comment]
After canceling I used the following command: systemctl reload apache2

Then the MISP login came up. Did the installation not complete fully?

**Comment by adulau** [comment]
It depends of your system. If you are able to login with the default credentials, you can safely assume the install was successful.  I would strongly suggest to go `/servers/serverSettings/diagnostics` to see the state and install any missing dependencies.

**Comment by stevelogik** [comment]
@adulau  I'm getting this: "Warning The MISP database state does not match the expected schema. Resolving these issues is recommended." any idea how to resolve this?

I highly recommend testing out you all's script on an ubuntu 18.04 it won't install fully with that git pull <remote> <branch> loop.
