### ISSUE TITLE
Impossible to change the orgc of an event

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#7460]
A while ago, it was possible to update the orgc of an event, it's not the case anymore. 

Reference: https://github.com/MISP/PyMISP/issues/744

**Comment by dragsu** [comment]
@Rafiot I was looking at a similar issue and if `orgC `change is allowed it is going to break the sharing model. Also found https://github.com/MISP/MISP/issues/453 highlighting the downside of this.

**Comment by iglocska** [comment]
Correct, this is working as intended.
