### ISSUE TITLE
Install.sh script hangup

### ISSUE THREAD

**Issue by maxifjaved** [MISP/MISP#7462]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.4
| MISP version / git hash   | 2.4, 478be522d2c0495d8b7512c5454c3613d35e0120
| Browser                   | 

### Expected behavior
Should install the MISP

### Actual behavior
Hangs while install dependency.

### Steps to reproduce the behavior
run `./INSTALL.sh -A`

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/17304812/120390289-f88c3f80-c346-11eb-9b9e-955ca24df3d0.png)

**Comment by rommelfs** [comment]
I guess some more information about the environment (OS version for instance) would be useful.
Closing for the moment - feel free to re-open.
