### ISSUE TITLE
Default 'CIRCL OSINT Feed' and 'The Botvrij.eu Data' are not working

### ISSUE THREAD

**Issue by sabyasachisamanta** [MISP/MISP#7463]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Red Hat Enterprise Linux
| OS version (client)       | 8.3 (Ootpa)
| PHP version               | 7.4.19
| MISP version / git hash   | 2.4
| Browser                   | If applicable

### Expected behavior
Events should be downloaded after configuration of proxy. However the feed jobs are getting failed. 

### Actual behavior
However the feed jobs are getting failed with the error message:  "Fetching the 'https://www.circl.lu/doc/misp/feed-osint/manifest.json' failed with exception: Unable to perform enableCrypto operation on CakeSocket" and "Fetching the 'https://www.botvrij.eu/data/feed-osint/manifest.json' failed with exception: Unable to perform enableCrypto operation on CakeSocket"

### Steps to reproduce the behavior
Click on the pull option for fetching events against the mentioned default feeds.

### Logs, screenshots, configuration dump, ...
2021-06-02 07:49:39 Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 504]
2021-06-02 07:49:39 Error: Could not get new event uuids for feed 1.
[Exception] Fetching the 'https://www.circl.lu/doc/misp/feed-osint/manifest.json' failed with exception: Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(200): Feed->feedGetUri()
#1 /var/www/MISP/app/Model/Feed.php(144): Feed->downloadManifest()
#2 /var/www/MISP/app/Model/Feed.php(958): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(270): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}[SocketException] Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(261): CakeSocket->enableCrypto()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(108): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Model/Feed.php(1856): HttpSocket->get()
#6 /var/www/MISP/app/Model/Feed.php(1810): Feed->getFollowRedirect()
#7 /var/www/MISP/app/Model/Feed.php(200): Feed->feedGetUri()
#8 /var/www/MISP/app/Model/Feed.php(144): Feed->downloadManifest()
#9 /var/www/MISP/app/Model/Feed.php(958): Feed->getNewEventUuids()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(270): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#17 {main}

2021-06-02 07:50:20 Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 504]
2021-06-02 07:50:20 Error: Could not get new event uuids for feed 2.
[Exception] Fetching the 'https://www.botvrij.eu/data/feed-osint/manifest.json' failed with exception: Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(200): Feed->feedGetUri()
#1 /var/www/MISP/app/Model/Feed.php(144): Feed->downloadManifest()
#2 /var/www/MISP/app/Model/Feed.php(958): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(270): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}[SocketException] Unable to perform enableCrypto operation on CakeSocket
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(261): CakeSocket->enableCrypto()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(108): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Model/Feed.php(1856): HttpSocket->get()
#6 /var/www/MISP/app/Model/Feed.php(1810): Feed->getFollowRedirect()
#7 /var/www/MISP/app/Model/Feed.php(200): Feed->feedGetUri()
#8 /var/www/MISP/app/Model/Feed.php(144): Feed->downloadManifest()
#9 /var/www/MISP/app/Model/Feed.php(958): Feed->getNewEventUuids()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(270): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#17 {main}

**Comment by chrisinmtown** [comment]
I suggest you first check the network path outside MISP. Verify that your machine can fetch data from the URL using a basic command-line tool like curl or wget on your MISP machine.  For example:
```
% curl https://www.botvrij.eu/data/feed-osint/manifest.json
```
An error of failing to verify a certificate suggests another server is in the network path, possibly a corporate proxy server?

**Comment by sabyasachisamanta** [comment]
Finally got it resolved. The issue was due to the expired certificate of the proxy.
