### ISSUE TITLE
Ok I give up...how do I get a cuckoo json file into MISP

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#7465]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |Ubuntu
| OS version (client)       | Ubuntu
| MISP version / git hash   | 39666c8b115f39835715f08133bbe7b4af07a1d2
| Browser                   | If applicable

### Support Questions
I've got the misp-modules service running.  I've got cuckoo import enabled and set to the org name.  So...how am I supposed to import the actual json file?  I've searched this morning...there's nothing about actually using it.  Do I just to to Import?  Because there's nothing there besides the MISP and Stix options.

**Comment by iglocska** [comment]
Create a MISP event. Click on "populate from..." It should be listed there as long as MISP can access the modules and the module is enabled.

**Comment by DigiAngel** [comment]
Thank you that helps...sadly my 10.9 meg json from cape sand box got me:
~~~
Something went wrong, look in the server logs for details
~~~
and an empty event.  Any idea which logs to check?  /var/log/apache had nothing in regard to the even.

**Comment by chrisinmtown** [comment]
Log files to check are /var/www/MISP/app/tmp/error.log and .../debug.log

**Comment by DigiAngel** [comment]
Thanks...those are empty.  Looks like I'll take this up in the modules section, thanks all.
