### ISSUE TITLE
Pull Sync DB Error

### ISSUE THREAD

**Issue by BurakOzgen** [MISP/MISP#7467]
# This template is meant for bug reports, if you have a feature request user the other template.
While syncing between two Misp(full sync) instance Cake throws an DB error. This exception occurs randomly whıle getting events. Remote Misp instance version is: 2.4.142
![image](https://user-images.githubusercontent.com/49974892/120599761-94ee3900-c450-11eb-9116-04c7f652233d.png)
![image](https://user-images.githubusercontent.com/49974892/120599991-e4cd0000-c450-11eb-851d-44de82ca2a89.png)

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 18.04
| PHP version               | 7.4.10
| MISP version / git hash   | 2.4.137
| Browser                   | Chrome

### Expected behavior
No DB Error

### Actual behavior
captureSighting DB Error occurs randomly while getting events.

### Steps to reproduce the behavior
sudo -u www-data /var/www/MISP/app/Console/cake Server pull 1 2 full

### Logs, screenshots, configuration dump, ...
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'captureSighting' at line 1
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()

**Comment by JakubOnderka** [comment]
This was already fixed in #6951, you have to update to latest MISP.
