### ISSUE TITLE
Import failed of a CISA STIX file

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#7472]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.5 LTS
| OS version (client)       | Win10
| PHP version               | 7.2.24-0ubuntu0.18.04.7
| MISP version / git hash   | v2.4.143 (19aa7e23bf1014856e89c6bbdc98255dd75217ea)

### Expected behavior

https://us-cert.cisa.gov/sites/default/files/publications/MAR-10322463-5.v1.WHITE_stix.xml

Importing of the above mentioned stix file would be succesful.

### Actual behavior

Importing fails without errors in `exec-errors.log`.

The UI shows an error:
`Could not import STIX document: Issues while loading the stix file. Please check whether the dependencies for STIX are met via the diagnostic tool.`

### Steps to reproduce the behavior

1. Try to import the file.

### Logs, screenshots, configuration dump, ...

Logs in `/var/www/MISP/app/tmp/logs/` were checked with `tail -f *.log` and nothing was seen during the attempt to import the file.

**Comment by chrisinmtown** [comment]
I can offer some very basic items you might check and post back here:
1. Is that file stix1 or stix2?  
2. Are the required Python packages to import stix1 and/or stix2 installed? They are delivered as a git submodule within MISP. A separate step is required to install those packages into the python venv used by MISP.

**Comment by samitainio** [comment]
@chrisinmtown @chrisr3d 

Thank you for the quick response!

1. According to the information provided by the linked file the specific version is 1.1.1. Generally speaking when stix file is XML it is always stix1 and when it is in JSON format it is stix2.
2. Yes they are. Regardless just for troubleshooting purposes I also now did the steps 3 and 4 as documented [in the MISP guide](https://misp.github.io/MISP/UPDATE/#3-update-mitres-stix-and-its-dependencies). Also to note that doing those steps doesn't update the venv side so I ran the commands:

```
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install --upgrade stix
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install --upgrade stix2
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install --upgrade stix2-patterns
```

The Python package versions were checked with `pip3 list` and `sudo -H -u www-data /var/www/MISP/venv/bin/pip3`. Both sides are at versions stated below:

|Package|Version|
| - | - |
|cybox|2.1.0.21|
|mixbox|1.0.5|
|stix|1.2.0.11|
|stix2|2.1.0|
|stix2-patterns|1.3.2|

Please do let me know if I have missed some package? Those were the ones I was able to identify relevant for this issue. After this I rebooted the server for good measure and tried to import the file again but unfortunately the issue remains. No new symptoms to report at this time.

**Comment by samitainio** [comment]
@chrisr3d

Any additional tips or pointers as for what I could check or do in the meanwhile?

**Comment by chrisr3d** [comment]
The issue here is the stix python library is not happy with the `[Redacted]` values you can find here and there in the file.
I tried to find a way to deal with it but no success yet... It looks like the stix-validator is ok with it but `STIXPackage.from_xml` definitely barfs with such kind of value
