### ISSUE TITLE
Problem with getting feeds and event enrichment behind proxy

### ISSUE THREAD

**Issue by fink08** [MISP/MISP#7486]
Even after changing the proxy settings, I can't get the feeds to work properly, no events are created. I've seen similar issues being raised (especially #4653) but the solutions proposed don't seem to apply to my case so I am probably missing something. 

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS 7
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | 2.4.143

### Expected behaviour

The Events are created automatically.

### Actual behaviour

The Events can be fetched manually and individually from the feeds but the feeds themselves are not functional, the logs show time out errors every time. 

### Steps to  reproduce behaviour

- Change the proxy settings under "Server settings and maintenance" ==> the diagnostics show no problem. 
- Click "Explore the events remotely" for each feed. It is possible to manually fetch the events one by one with no problems as can be seen below :

![Annotation 2021-06-08 165056](https://user-images.githubusercontent.com/78410529/121325019-8d77d580-c911-11eb-85c5-8484ae6944d8.jpg)

- Click "Fetch all events" then go to the jobs : "Job failed". No events created in the MISP instance.

### Comments

I have verified via the CLI that the feed websites are reachable through the proxy, so this doesn't seem to be the problem. 

Tcpdump seems to indicate that the feed requests are ignoring the proxy. 

The error logs indicate that the connection timed out. 

My proxy settings look like something like this (all the fields are filled in my actual setup) : 

<img width="370" alt="Screenshot_2021-06-09 Servers - MISP" src="https://user-images.githubusercontent.com/78410529/121328359-8c947300-c914-11eb-96b2-c08acbd3b0fa.png">

I am guessing that different proxy settings are being used for the feeds, but I admit I don't know where to find those, or whether that is actually the problem or not. I would be grateful for any help I can get.

Thanks !

**Comment by fink08** [comment]
Hi,

Just a follow up, I think I have narrowed down my problem, but I can't seem to find a solution. 

Looking at the source code and the documentation, it seems the python module "requests" is being used to establish a connection with external websites. The documentation for that indicates that when the proxy information is not overridden in code, it uses the "HTTP_PROXY" and "HTTPS_PROXY" environment variables to redirect traffic. I have those set up and confirmed that they are being taken into account as can be seen below :

![image](https://user-images.githubusercontent.com/78410529/121859216-bb855d00-ccf7-11eb-843d-93b04c60f03e.png)

(Using CURL also works)

However when I try to do the same from the UI, I still have no luck with the "fetch all events" button (in red below). 

![image](https://user-images.githubusercontent.com/78410529/121859811-757cc900-ccf8-11eb-9d20-3cde3db42ae9.png)

The job gets sent to the queue and eventually times out : 

![image](https://user-images.githubusercontent.com/78410529/121859951-a4933a80-ccf8-11eb-82a6-ec2e00fbef70.png)

![image](https://user-images.githubusercontent.com/78410529/121860196-e7551280-ccf8-11eb-9c77-0859ac5ef793.png)

Meanwhile I can still load the events remotely in the UI and fetch them individually : 

![image](https://user-images.githubusercontent.com/78410529/121860677-61859700-ccf9-11eb-8db5-dca642d054e3.png)

![image](https://user-images.githubusercontent.com/78410529/121860762-77935780-ccf9-11eb-9170-1b86281cd10a.png)

I tried tweaking the proxy settings in the MISP UI, even erasing them altogether in case the "requests" module would just use the environment variables instead but no luck on that front. Am I missing something ? I'd be grateful for any advice on how to troubleshoot this issue. Thanks !

**Comment by righel** [comment]
Hello @fink08 ,
Did you manage to fix your proxy issues? Could you please attach any relevant contents of your MISP error logs after you try to download a feed/enrich an event?
The error log is located in /var/www/MISP/app/tmp/logs/error.log

I created this guide that may help too: https://github.com/MISP/MISP/wiki/Proxy

Let me know if that helps.

**Comment by 00willo** [comment]
@fink08 I noticed that in your screenshot of the proxy settings, you did not set the proxy port, only the proxy host.  I've been testing using a proxy, and if I remove the proxy port from my settings leaving just a proxy host defined, the sync fails.

**Comment by adulau** [comment]
The issue will be closed. Feel free to reopen if the issue is still present.

**Comment by franklinsandoval-equifax** [comment]
Hi! I have the same issue, someone found the way to fix it? @adulau
