### ISSUE TITLE
Server throws error Call to undefined function ldap_set_option()

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7489]
While trying to configure external authentication in version 2.4.143 of MISP I botched something and somehow revealed an undefined function.  Here is the stack trace:
```
2021-06-09 11:46:52 Error: [Error] Call to undefined function ldap_set_option()
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): ApacheAuthenticate->authenticate()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#2 /var/www/MISP/app/Controller/UsersController.php(1193): AuthComponent->login()
#3 [internal function]: UsersController->login()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#8 {main}
```
Here's the first usage of that function:

https://github.com/MISP/MISP/blob/81543d05d43d709a38230d208199f525cb28ab10/app/Controller/Component/Auth/ApacheAuthenticate.php#L68

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  RedHat
| OS version (client)       | MacOS
| PHP version               | 7.4
| MISP version / git hash   | 2.4.143
| Browser                   | Firefox

### Expected behavior

When I have misconfigure Apache authentication, the server should complain and show a relevant error.

### Actual behavior

Server method fails due to undefined method

### Steps to reproduce the behavior

Add CustomAuth and ApacheSecureAuth lines to Config/config.php for example:
```
  'ApacheSecureAuth' => 
  array (
    'apacheEnv' => 'REMOTE_USER',
    'ldapServer' => 'ldap://ldap.my-company.com',
    'ldapProtocol' => 3,
    'ldapReaderUser' => 'user',
    'ldapReaderPassword' => 'password',
    'ldapDN' => 'dc=org,dc=my-company,dc=com',
    'ldapSearchAttribut' => 'uid',
    'ldapFilter' => 
    array (
      0 => 'mail',
    ),
    'ldapDefaultRoleId' => 3,
    'ldapDefaultOrg' => 'MYORG',
  ),
```

**Comment by JakubOnderka** [comment]
You have to install ldap PHP extension and restart PHP daemon.

**Comment by chrisinmtown** [comment]
Thanks for explaining.  I had no intent of actually using LDAP and cannot test your solution, so I'm closing this issue.
