### ISSUE TITLE
Syntax error in query for "Events with proposals"

### ISSUE THREAD

**Issue by I-am-Sherlocked** [MISP/MISP#749]
Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.ShadowAttribute.type' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/proposalEventIndex

Seems to be an issue with changes in MySQL 5.7.5+ .  Plans to fix?

**Comment by I-am-Sherlocked** [comment]
Also happens when querying for "Members List"

**Comment by iglocska** [comment]
Thanks for the heads up, looks like it's indeed a change with MYSQL 5.7+ (they made only_full_group_by default). I'll try to fix it soon.
