### ISSUE TITLE
Viewing Event index gives error

### ISSUE THREAD

**Issue by scareh** [MISP/MISP#7490]
Hello,

I'm having issues after adding a few default misp feeds to my instance.

When opening the event index list to view all imported events it just loads and ends up with a gateway timeout.

Gateway Timeout

The gateway did not receive a timely response from the upstream server or application.

My guess is that the server can't handle the request to load the list of events, are there any server setting that needs to be adjusted?

**Comment by chrisinmtown** [comment]
First thing is to check the server's error.log file. This is just a SWAG, but there's a chance the server's php process ran out of memory while loading the event list, or possibly timed out waiting for the database to respond.  You can change memory and timeout limits in your php.ini file.

**Comment by rommelfs** [comment]
Please provide exact steps of what you were doing, on which MISP version, and provide meaningful log lines to be able to understand the problem. Closing for the moment.
