### ISSUE TITLE
Org logo not displayed on organisations/index

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#7491]
With 2.4.141 on `organisations/index` the Org logo is displayed in the list. Don't see that in 2.4.143. Is there a way to enable the logo display, or is this a bug?

**Comment by chrisinmtown** [comment]
In version 2.4.141 the columns on the Organisations page are Id, Logo, Name, Description, Nationality, Sector, Type, Contacts, Local, Users, Restrictions, Actions.

In version 2.4.143 the columns on that page are ID, Name, UUID, Description, Nationality, Sector, Type, Contacts, Added By, Local, Users, Restrictions, Actions

I'm guessing someone decided that adding the UUID column left no room for the Logo?  That's too bad, it's useful to see what logo is uploaded (or not) for each org.

**Comment by github-germ** [comment]
Thx @chrisinmtown -- also, user friendly to look for logos when scrolling thru Orgs vs. reading the names.

**Comment by chrisinmtown** [comment]
The Logo column was removed from the view by @mokaddem in this commit:

https://github.com/MISP/MISP/commit/77e68c5a076c74ef6d73a3e152f0340f1a4d5700

**Comment by chrisinmtown** [comment]
Thanks @iglocska
