### ISSUE TITLE
AadAuth Module bug

### ISSUE THREAD

**Issue by BillClarksonAntill** [MISP/MISP#7496]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu  20.04.2
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.143
| Browser                   | Google Chrome

### Expected behavior
AadAuth Module integration and configuration based on documentation provided
When browsing to the MISP URL i expect to be able to login without spamming the "Login Azure Auth" way

### Actual behavior
Logging into MISP using the aadauth module, you can click as many times as required to successfully auth against MISP. This only works if you have created the account in MISP manually and added the user to the groups in Azure

To give context to this issue, MISP has been deployed into an Azure Container Instance with a PaaS MYSQL DB and App Gateway sitting in front of the container. 

Logs are below to give context to what is happening

### Steps to reproduce the behavior
deployed MISP to Azure Container Instance
created app registration for aadauth based on documentation and module provided
when logging into MISP get some unusual behavior, if you have an account in MISP already. You click as many times as it needs to sign in
if there is no account created in MISP, you cant sign in

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/66821277/121846145-a41b9380-cd3a-11eb-87f7-b4b9b4174ac5.png)

447691 | &nbsp; | SYSTEM | 2021-06-16 01:02:33 | User | 0 | auth | Attempt authentication for user@myorg.co.nz | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | --
447690 | &nbsp; | SYSTEM | 2021-06-16 01:02:31 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447689 | &nbsp; | SYSTEM | 2021-06-16 00:58:55 | User | 0 | auth | Error received during user data fetch. | &nbsp;
447688 | &nbsp; | SYSTEM | 2021-06-16 00:57:54 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447687 | &nbsp; | SYSTEM | 2021-06-16 00:57:53 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447686 | &nbsp; | SYSTEM | 2021-06-16 00:57:53 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447685 | &nbsp; | SYSTEM | 2021-06-16 00:57:52 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447684 | &nbsp; | SYSTEM | 2021-06-16 00:57:51 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447683 | &nbsp; | SYSTEM | 2021-06-16 00:57:49 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447682 | &nbsp; | SYSTEM | 2021-06-16 00:57:48 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447681 | &nbsp; | SYSTEM | 2021-06-16 00:57:47 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447680 | &nbsp; | SYSTEM | 2021-06-16 00:57:45 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447679 | &nbsp; | SYSTEM | 2021-06-16 00:56:48 | User | 0 | auth | Fetching user group data from Azure. | &nbsp;
447678 | &nbsp; | SYSTEM | 2021-06-16 00:56:47 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447677 | &nbsp; | SYSTEM | 2021-06-16 00:56:44 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447676 | &nbsp; | SYSTEM | 2021-06-16 00:56:43 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447675 | &nbsp; | SYSTEM | 2021-06-16 00:56:39 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447674 | &nbsp; | SYSTEM | 2021-06-16 00:56:38 | User | 0 | auth | Redirect to Azure for authentication. | &nbsp;
447673 | &nbsp; | SYSTEM | 2021-06-16 00:56:36 | User | 0 | auth | Error received during Bearer token fetch (context). | &nbsp;
447672 | &nbsp; | SYSTEM | 2021-06-16 00:56:35 | User | 0 | auth | Redirect to Azure for authentication.

2021-06-16 00:57:53 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/----mytokennumber----/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: operation failed in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 305
AppController::_loadAuthenticationPlugins() - APP/Controller/AppController.php, line 1327
AppController::beforeFilter() - APP/Controller/AppController.php, line 236
EventsController::beforeFilter() - APP/Controller/EventsController.php, line 62
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by BillClarksonAntill** [comment]
Just wondering if this could be based on my config of MISP also, unfortunately the aadauth module documentation seems a bit light in this area if there is further configuration that you have to perform in the MISP Portal. Can someone clarify if possible?

**Comment by BillClarksonAntill** [comment]
i assume this has gone into a dark void of "dont feel like looking at this thing"

**Comment by mokaddem** [comment]
Hello,
Could you please provide your configuration file?
Thanks

**Comment by BillClarksonAntill** [comment]
this can be closed, new version of MISP has resolved this
