### ISSUE TITLE
Page Layout issue under Galaxies

### ISSUE THREAD

**Issue by BillClarksonAntill** [MISP/MISP#7499]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.5.4
| MISP version / git hash   | 2.4.1
| Browser                   | Google Chrome

### Expected behavior
To see Import Galaxy Clusters and Export Galaxy Clusters when clicking from View Galaxy to Add Cluster

### Actual behavior
Clicking from View Galaxy to Add Cluster, Export Galaxy Disappears from the Link List

### Steps to reproduce the behavior
![page layout bug](https://user-images.githubusercontent.com/66821277/121950130-5a1fc580-cdad-11eb-99de-a19e5058f917.PNG)
![page layout bug2](https://user-images.githubusercontent.com/66821277/121950138-5b50f280-cdad-11eb-80ca-e6cdc0846e2c.PNG)

**Comment by rommelfs** [comment]
I can't reproduce on MISP 2.4.144 
Can you demonstrate exact steps on this software version please?

**Comment by BillClarksonAntill** [comment]
Sorry rommelfs, should have put a better description

Follow the steps below

Click **Galaxies** > **List Galaxies**
Select a **Galaxy ID** it doesn't matter which one
On the left side panel, click **Add Cluster** on the Add Cluster page the Export Galaxy Clusters Page link disappears
Click back to **View Galaxy** Export Galaxy Clusters Page is available

Its pretty minor, unsure if this is by design or not

**Comment by rommelfs** [comment]
ha, nice :) Thanks for the clarification.
