### ISSUE TITLE
Misp installed: doesn't work web interface

### ISSUE THREAD

**Issue by Kairat-ifeb** [MISP/MISP#7509]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|----------------------------|--------------------
| Type of issue                   | Support
| OS version (server)          | Ubuntu 18.04
| OS version (client)           | Windows 7
| PHP version                     | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                           |Google Chrome

### Support Questions
Hello!
I have install MISP using:
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -A

i wanted to install all modules.
But while MISP was installing i had a question: install with administaror accounts or with new user us misp. I chose a new user misp. After the finishing insrall. I tried to open web site, but i got some php script (which i рфму atteched). 
Could you help me to fix this issue?

### Logs, screenshots, configuration dump, ...
![MISP](https://user-images.githubusercontent.com/63206327/122741413-bfd8e980-d2a6-11eb-872d-e6195cb5119a.png)

**Comment by adulau** [comment]
If you have PHP scripts returned in your web client, it's most often a misconfiguration of the Apache server. Do you have enable PHP, are the PHP engine enabled and the execution configured in the virtual host.

**Comment by Kairat-ifeb** [comment]
I have installed PHP 7.2, after that i got server error 500 and error_log:
![cghe](https://user-images.githubusercontent.com/63206327/122880589-f9b7f780-d35b-11eb-8db9-74aa13a79d93.png)
As you said in issue #4067 i follow and tried to laung following script:
https://misp.github.io/MISP/INSTALL.ubuntu1804/#4-cakephp
but anything didn't happen.
Can you help to solve this issue? What i should to do?
