### ISSUE TITLE
Internal Error has occurred - when viewing "Diagnostic"

### ISSUE THREAD

**Issue by NetEyes** [MISP/MISP#7513]
Hi,

I am unable to view "Diagnostic" section. I am getting Internal Error .

Server Settings & Maintenance -> Diagnostics
![image](https://user-images.githubusercontent.com/20463433/122926306-b64a9280-d335-11eb-960e-de8f489346be.png)

**Comment by mokaddem** [comment]
Do you have anything interesting in the logs?
(`MISP/app/tmp/logs/)

**Comment by NetEyes** [comment]
I ended up re-installing MISP
