### ISSUE TITLE
MISP Feed Sync

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#7516]
Hi, 

My MISP feeds don't sync automatically and only way I get new events / attributes in a fixed event is my manually clicking on "Fetch events". 

Is this a known bug in 2.4 or a config issue on my end?  

Also, what does the caching age (in days) mean?

**Comment by redbiker-svg** [comment]
Hi @RichieB2B @iglocska 
Could either you gents help me out with this?

**Comment by mokaddem** [comment]
Hello,
Fetching is not done automatically, you have to trigger the action yourself. Either by clicking on the UI or by using the API/CLI.
The best way to do it is via a CRON job.
Please have a look at `/events/automation`, especially the section `Automating certain console tasks`.
> Also, what does the caching age (in days) mean?

This means that the local cache of the feed you are looking to is `x` days old.
Cheers!
