### ISSUE TITLE
Client Certificate Error

### ISSUE THREAD

**Issue by maverickvn360** [MISP/MISP#7521]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.144, 2fde6476dc3173affc61874ba2adb35400a8fda5
| openSSL version           | 1.1.1f - 31 Mar 2020

### Expected behavior
Sync Test passes

### Actual behavior
Sync Test fails with the error:
`Error: Couldn't read certificate: error:0909006C:PEM routines:get_name:no start line`

### Steps to reproduce the behavior
1. Upgraded to the latest version of MISP.
2. Generate a normal sync scenario, (A & B) - A having the sync user and the local org set up and B setting up the server to A, syncing B with A.
3. Uploaded the private key (pem/csr/key) files to client cert and public key to (pem) to server cert files
4. Client cert fails to upload.

I tried to set up another VM, but keep getting the same error.

In my scenario, I've setup three VMs (A, B, C) -> B syncs with C, and A with B, all three have the same versions and hashes

It works fine for the same configuration between B and C, I also tried modifying the pem files for any whitespaces or normal text issues, and all the certs are self signed (so no cert chaining required). A warning is also generated in the error log file, which I assume can be safely ignored.

Have just modified the internal and external url of the misp server, w.r.t. the configuration.

### Logs, screenshots, configuration dump, ...
error.log:
`Warning: Warning (2): openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate! in [/var/www/MISP/app/Lib/Tools/SyncTool.php, line 131]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
openssl_x509_read - [internal], line ??
SyncTool::getClientCertificateInfo() - APP/Lib/Tools/SyncTool.php, line 131
SyncTool::getServerClientCertificateInfo() - APP/Lib/Tools/SyncTool.php, line 92
Server::runConnectionTest() - APP/Model/Server.php, line 2385
ServersController::testConnection() - APP/Controller/ServersController.php, line 1669
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92`

resque-scheduler-error.log
`Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(538): Redis->srem()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php(48): Resque_Worker->unregisterWorker()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(68): ResqueScheduler\Worker->work()
#3 {main}`

Thanks in advance :)

**Comment by maverickvn360** [comment]
Please let me know if there's an update.
Thanks

**Comment by maverickvn360** [comment]
I generated certificates (client) using these standard commands:

`openssl genrsa -out server.key`
 `openssl req -new -key server.key -out server.csr`
 `cp server.key server.key.org`
 `openssl rsa -in server.key.org -out server.key`
 `openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt`

**Comment by mokaddem** [comment]
Hello,
It seems there is an error with the provided certificate you created. It's likely a format issue.
Keep in mind that both the server and client certificates must be under the PEM format.
I tried the following command and it worked as expected
```bash
# Generate server certificate and key
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
    -keyout misp.key -out misp.crt -subj "/CN=misp.test" \
    -addext "subjectAltName=DNS:misp.test"
# Create server PEM file
cat misp.crt misp.key > misp.pem

# Generate Client key
openssl genrsa -out client.key 4096
# Generate Client cert request
openssl req -new -key client.key -out client.req
# Sign request with server key to get Client certificate
openssl x509 -req -in client.req -CA misp.crt -CAkey misp.key -set_serial 101 -extensions client -days 365 -outform PEM -out client.crt
# Create clien PEM file
cat client.key client.crt misp.crt > client.pem
```

Let us know if it works for you!

**Comment by maverickvn360** [comment]
Thanks for replying, Sami..

Yep, they're in PEM format.

Apparently client certificates have gotten stricter in openssl recently. I
get the following output:

`Client certificate:`
`Subject: C=CA, ST=State_Name, O=Org, CN=url.url1
Issuer: C=CA, ST= State_Name  , O=Org_2, CN=url.url2
Serial number: XY
Valid from: 2021-07-14T19:59:36+00:00
Valid to: 2022-07-14T19:59:36+00:00
Public key: RSA (2048 bits)`

`Authentication failed`

Thanks for resolving the issue. This seems like a different one

Is it possible that the certs are incorrect as of now? I verified the size of the RSA keys (2048) and doubly verified the certificate I'm signing with. Would you know the cause of the above error?

Thanks :)

**Comment by maverickvn360** [comment]
In addition to that, there are no errors..

**Comment by maverickvn360** [comment]
And there's something wrong on the other instance(s) communication - which WORKS when it shouldn't normally. I don't know why - when I specify no client certificate, even when I remove the *_client.pem files, the server authentication passes, when it should fail. As in this issue, I specified that - one of the sync situations work, while the other being the same scenario - doesn't. Is this another bug?

**Comment by maverickvn360** [comment]
Apparently, the issue was - I wasn't using correct API Key. As mentioned on the server page, we need to use one of the API/Auth keys mentioned in the profile page under Global Settings > My Profile.

Thanks for following up team. Appreciate it.

But I still don't understand why the incomplete certificate upload works in the above scenario.
