### ISSUE TITLE
Undefined variable when clicking on event view

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#753]
When logged in as "Admin" and clicking on the 'View' icon on any event I see following notice in debug.log:

2015-12-15 09:29:02 Notice: Notice (8): Undefined variable: post_id in [/var/www/MISP/app/View/Elements/eventdiscussion.ctp, line 174]
Trace:
include - APP/View/Elements/eventdiscussion.ctp, line 174
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 948
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 910
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 471
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 954
ThreadsController::view() - APP/Controller/ThreadsController.php, line 183
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 92

**Comment by iglocska** [comment]
Hmm, I thought that was resolved, which version are you on?

**Comment by h122015** [comment]
2.4. I pulled it yesterday evening
