### ISSUE TITLE
phpunit/php-token-stream abandoned, warning from composer

### ISSUE THREAD

**Issue by Kagee** [MISP/MISP#7534]
Putting this here for documentation, not sure if it is a bug yet

### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| MISP version / git hash   | 2.4.145 da0b99213d0a090d1b7d49028f118bec553a526a

### Expected behavior
Not using abandoned php packages

### Actual behavior
Using abandoned packages. phpunit/php-token-stream is abandoned upstream.

### Steps to reproduce the behavior
* https://github.com/MISP/MISP/blob/v2.4.145/app/composer.json requires phpunit/phpunit version 8.*
* phpunit 8.5.17 requires php-code-coverage
* php-code-coverage 7.0.12 requires php-token-stream

### Possible solution
* Upgrade to phpunit 9.3.0 (Aug 7, 2020), it requires php-code-coverage 9.0.0, that is te first version of php-code-coverage that does not require php-token-stream

### Logs, screenshots, configuration dump, ...
```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

phpunit/php-token-stream 4.0.4 Wrapper around PHP's tokenizer extension.
`--phpunit/php-code-coverage 7.0.14 (requires phpunit/php-token-stream ^3.1.1 || ^4.0)
   `--phpunit/phpunit 8.5.17 (requires phpunit/php-code-coverage ^7.0.12)
      `--__root__ (requires (for development) phpunit/phpunit ^8)
```

* https://packagist.org/packages/phpunit/phpunit#9.3.0
* https://packagist.org/packages/phpunit/php-code-coverage#9.0.0
* https://packagist.org/packages/phpunit/php-token-stream

**Comment by Wachizungu** [comment]
Just adding for tracking purposes:
https://gitter.im/MISP/MISP?at=60dc8f60bcb3e8060ef1de61

**Comment by iglocska** [comment]
Indeed, closing for now, thanks!
