### ISSUE TITLE
MISP localhost page: Connection Refused

### ISSUE THREAD

**Issue by ickgr** [MISP/MISP#7542]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 20.04
| MISP version / git hash   | 2.4.144 (latest)
| Browser                   | Firefox, server's native version

### Support Questions
Hello,
Some days back I performed a fresh clean MISP installation on virtualbox.
The installation was performed simply by following the procedure that it was initiated through the command below:

**wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c -M**

When the installation finished, I was normally able to enter MISP default page (https://localhost:8443)
However after restarting the server the default page does not open.

Currently the MISP page should be accessible only through server's browser.

Any suggestions how to bypass this blocking point?

Thank you,

### Logs, screenshots, configuration dump, ...

![Capture](https://user-images.githubusercontent.com/86368607/124293407-4cb15c00-db5f-11eb-876b-05a65dc7a800.JPG)
![Capture1](https://user-images.githubusercontent.com/86368607/124293413-4d49f280-db5f-11eb-9e5b-7a1507b93e60.JPG)

**Comment by righel** [comment]
Hello,
At first glance looks like Apache is not running. Could you paste the output of this command?
`sudo service apache2 status`
If the service is not running, try restarting it by running:
`sudo service apache2 restart`

**Comment by ickgr** [comment]
Hi @righel 

Below is command's output.

![Capture](https://user-images.githubusercontent.com/86368607/124443583-77312e00-dd86-11eb-87f8-32bd329c0d40.JPG)

**Comment by ickgr** [comment]
Dear Support,

Can someone assist me on this? Do you know if the instructions write something that can I advice me how to overcome this?


Thank you,

**Comment by righel** [comment]
Hello @ickgr ,
Are you trying to access MISP from the same virtualbox VM/guest or via your host machine?

Can you attach/paste the contents of these logs?
`/var/log/apache2/error.log`
`/var/log/apache2/misp.local_access.log`

The output of:
`sudo apache2ctl -S`
`sudo lsof -i -P -n | grep LISTEN`

**Comment by ickgr** [comment]
Hi @righel 

I'm trying to access MISP from the same virtual server.
[commands.txt](https://github.com/MISP/MISP/files/6789406/commands.txt)

**Comment by righel** [comment]
Seems Apache is listening on port 443 not 8443, according to the logs this configuration changed at some point after 29/Jun/2021:14:23:39 +0000. 
Could you try accessing MISP via https://127.0.0.1 and see if it works?

edit:
You might want to check that in the config file:
`/var/www/MISP/app/Config/config.php`
The setting `MISP.baseurl` is set to `https://localhost` or `https://127.0.0.1`

**Comment by ickgr** [comment]
If a hit the https://127.0.0.1/ the page opens to put my credentials but after that all the following page redirections fails since the URL change to localhost:8443/xxxxxxx

:~$ sudo more /var/www/MISP/app/Config/config.php | grep 443
    'baseurl' => 'https://localhost:8443',
    'external_baseurl' => 'https://localhost:8443',


So, what actions do i have to perform to solve this annoying behavior?

**Comment by righel** [comment]
**option 1:**
update those two settings in the `config.php` file with `https://127.0.0.1` value instead of `https://localhost:8443`.


**option 2:**
change back Apache SSL port to 8443:
1. edit misp virtual host.
`sudo vim /etc/apache2/sites-enabled/misp-ssl.conf`:
change `<VirtualHost *:443>` to `<VirtualHost *:8443>`
and then run:
`sudo a2ensite misp-ssl.conf`
3. update Apache ports:
`sudo vim /etc/apache2/ports.conf`
    change:
    ```
    <IfModule ssl_module>
            Listen 443
    </IfModule>
    
    <IfModule mod_gnutls.c>
            Listen 443
    </IfModule>
    ```
    to:
    ```
    <IfModule ssl_module>
            Listen 8443
    </IfModule>
    
    <IfModule mod_gnutls.c>
            Listen 8443
    </IfModule>
    ```
4. restart Apache:
   `sudo service apache2 restart`

**Comment by ickgr** [comment]
Everything seems to be ok now.

@righel Thank you for your effort in assisting me on this issue.


Have a nice day!

**Comment by d6pd6p** [comment]
Hey I don't know if you remember this but I have the same problem today... After replacing everything you said @righel I get this message. How can I solve it?

![Image](https://github.com/user-attachments/assets/afd0bef4-b6e7-45f1-9ba1-ed633fa724ff)
