### ISSUE TITLE
APP/Model/Warninglist.php, line 191 prevents events to be published

### ISSUE THREAD

**Issue by mikkster** [MISP/MISP#7546]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu.
| OS version (client)       | Win10
| PHP version               | 7.1.
| MISP version / git hash   | v2.4.146 , 0c25b720724c0fc8dbc064b0cdfcf6e4d66a2ce1
| Browser                   | Mozila Firefox

### Expected behavior
When clicking on publish event or publish event with no email, a pop-up box should appear to confirm the choice

### Actual behavior
When clicking on publish event or publish event with no email, The pop-up box does not appear to confirm the choice. The following error message is on top of MISP however - "Notice (8): Undefined index: category [APP/Model/Warninglist.php, line 191]"

### Steps to reproduce the behavior
Add event with an attribute that has an IP in the warning list click publish or publish event

### Logs, screenshots, configuration dump, ...

Warninglist::attachWarninglistToAttributes() - APP/Model/Warninglist.php, line 191
Event::fetchEvent() - APP/Model/Event.php, line 2214
EventsController::view() - APP/Controller/EventsController.php, line 1697
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101

**Comment by JakubOnderka** [comment]
Hello, try to delete Model cache in *Administation* -> *Server Settings & Maintenance* -> *Diagnostics* -> *Clean model cache*.

**Comment by mikkster** [comment]
Hello, I have tried to delete Model cache issue still persists.

**Comment by mokaddem** [comment]
Hello, could you please update your warninglists?
You can do it by clicking on the `Update warninglists` button on the side panel.
It seems the warninglist cached in redis were not reloaded.

**Comment by mikkster** [comment]
This resolved the issue thank you
