### ISSUE TITLE
Text in hint is not accurate

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#755]
In version 2.4 whenever a user selects the type "Attachment" through the "Add Attribute" pop-up  for any of the valid categories for that attribute (Antivirus detection, Payload delivery, Artifacts dropped, Payload installation, Network activity, External analysis), there is a hint stating "Please upload files using the <em>Upload Attachment</em> button."  but such button is nowhere to be found. The text should point to the "Add Attachment" link located on the left bar.

**Comment by adulau** [comment]
Clarified in recent version *2.4.63". "Add Attachment" is there and the attribute "Attachment" has been removed to clarify the upload. The issue has been closed. If you think that is not resolved, feel free to reopen.
