### ISSUE TITLE
Invalid JSON input

### ISSUE THREAD

**Issue by yanerosolitario** [MISP/MISP#7552]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 20.04 LTS
| OS version (client)       | Centos Stream
| MISP version / git hash   |  MISP 2.4.146

### Support Questions
Tried to perform the following query:
{
  "request": {
    "type": [
      "ip-src",
      "ip-dst"
    ],
    "category": "Network activity",
    "last": "1d",
    "enforceWarnlinglist": "True"
  }
}
The result is as follows:
{"name": "Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.", "message": "Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request. "," url ":" \ / attributes \ / restSearch \ / json "}

URL = https://x.x.x.x/attributes/restSearch/json

Accept: application/json

Content-Type: application/json

Command (curl --insecure -s --header "Authorization: xxxxxx" --header "Accept: application/json" --header "Content-Type: application/json" -d /root/file.json https://x.x.x.x/attributes/restSearch/json
)

The sensitive part was replaced with x.

This same test was performed from the misp provides the following error [API>REST API:
{"name": "An Internal Error Has Occurred.", "message": "An Internal Error Has Occurred.", "url": "\ / attributes \ / restSearch"}

**Comment by righel** [comment]
Hello @yanerosolitario 
The JSON is valid.
The curl request is missing an `@` at the beginning of the file name <sup>1</sup>, in your example you are sending the value `/root/file.json` as the request body. It should be like this:
`curl --insecure -s --header "Authorization: xxxxxx" --header "Accept: application/json" --header "Content-Type: application/json" -d @/root/file.json https://x.x.x.x/attributes/restSearch/json`

<sup>[1]</sup> - https://curl.se/docs/manpage.html#-d
