### ISSUE TITLE
How to connect MISP to an external STIX/TAXII Server?

### ISSUE THREAD

**Issue by WebBotMaster** [MISP/MISP#7554]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Any necessary OS.
| OS version (client)       | Win10
| PHP version               | not relevant
| MISP version / git hash   | newest version

### Support Questions
Hey, I wrote the MISPProject Account on Twitter and the person answering told me I should ask my question here.

This is basically a question on how to get started with a personal project on Threat Intelligence, I am currently doing. Situation is, that I got a up and running MISP Instance. It contains a ton of TI, but it is located in a save enviroment, and therefor shouldn't be directly exposed to the internet. So what I want to do is installing and configurating a remote Stix/Taxii Server (like https://github.com/eclecticiq/OpenTAXII). It should be connected to the MISP Instance, so that information can be passed to the OpenTaxii Server from the MISP Instance. (Its ok if there is outgoing and incoming connections to the MISP for this purpose) On the other hand it should be giving people the possibility of connecting to the Taxii Server and polling its data to whatever stix1.1 supporting device they got. Example would be a Splunk Instance doing an automated Stix import.

A good example of what I want to accomplish would be: http://hailataxii.com/

Sadly I can't find a good way to get started as the OpenTaxii Docu mainly focuses on "how to install" rather then "how to use"... I am relatively fluent in python though, so if there is a script needed to export the data from MISP to the Taxii Server I would probably able to do this. Anybody could show a way to go ?

I have also asked this question here:
https://stackoverflow.com/questions/68284824/how-to-configurate-a-remote-taxii-server
So if anybody prefers answering on Stackoverflow, feel free to do so :)
I know this question is only partialy related to MISP itself, but as MISP is one of the leading projects in TI, my best guess was that someone over here already tried to acomplish the same thing.
Best regards
Chris

**Comment by mokaddem** [comment]
Hello!
Right now MISP can ingest and export data from/to STIX. To do so, we rely on these libraries (also developed by the misp-project team) https://github.com/MISP/misp-stix.
However, despite our best efforts, importing and exporting between these formats is not lossless. Fortunately, lots of tool integrate with the MISP API directly thus, removing this additional layer.
If there are no direct integration with MISP for your tools or if your use-cases still require to use a Taxii server, you can still export data using our STIX exporter and feed the data to other tools via Taxii.
I hope that helps!
