### ISSUE TITLE
Bunch of error in Database schema diagnostic

### ISSUE THREAD

**Issue by Pirlo-logi** [MISP/MISP#7556]
[MISP DATABASE ISSUE.pdf](https://github.com/MISP/MISP/files/6779040/MISP.DATABASE.ISSUE.pdf)
Hello All,
Hope you are doing well.
I have a bunch of error on misp Database schema diagnostic
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support/Bug
| OS version (server)       | Debian, Ubuntu 20.04.2 LTS
| PHP version               | 7.4.3
| MISP version / git hash   | 2.4.146, hash of the commit
| Browser                   | If applicable

### Support Questions
Please can you have a look and help me fix that issue?
Thanks.

### Logs, screenshots, configuration dump, ...
![MISP DATABASE ISSUE](https://user-images.githubusercontent.com/9124126/124804612-c9c34380-df5a-11eb-8229-24bfcf20ebbb.JPG)

**Comment by mokaddem** [comment]
Hey,
As described as a notice just below the `Debug mode` checkbox you checked, these are benign deltas that can be safely ignored.
Cheers!
