### ISSUE TITLE
Initially created auth key of sync user not working

### ISSUE THREAD

**Issue by Passimist** [MISP/MISP#7557]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Win10
| MISP version / git hash   | 2.4.146

### Expected behavior
I set up two fresh MISP instances and wanted to sync them. I added the org of one instance as a local org on the other. Then created a sync user in this newly created org and generate an auth key during the user creation.
When I use this auth key to set up a sync server I get an authentication error.
Generating a new key and using this it works fine.

**Comment by Passimist** [comment]
I used fresh Ubuntu 20.04 VMs and installed MISP according to this manual: https://misp.github.io/MISP/INSTALL.ubuntu2004/

# Please check the installer options first to make the best choice for your install
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh

# This will install MISP Core
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

**Comment by mokaddem** [comment]
Hey,
I guess by
> [...] generate an auth key during the user creation.

You mean the one displayed in clear text when adding a new user on the page `/users/add`?
If that's the case, the observed behavior is normal.
You probably have the setting `Security.advanced_authkeys` turned on. This system by-pass the "primary" authkey and relies on authkeys generated by users then hashed and saved in the DB.
I understand that the interface showing an authey during user creation may be confusing in that regards.

Thanks for the feedback!

**Comment by Passimist** [comment]
Hi,

thank you for your answer! That makes sense I have indeed not noticed such a setting.
