### ISSUE TITLE
Using the INSTALL.SH script without installing the database

### ISSUE THREAD

**Issue by stevengoossensB** [MISP/MISP#7561]
**Is your feature request related to a problem? Please describe.**
I would like to install MISP and use a database on a different server. Therefore, there is no need to install the database on the server.

**Describe the solution you'd like**
Add a flag to the install script so it doesn't install the database and configure a remote database

**Comment by mokaddem** [comment]
The install guide is quite extensive in this regard. It allows you to cherry pick exactly what you want to install or configure quite easily https://misp.github.io/MISP/INSTALL.ubuntu2004/#for-ubuntu-200420-server
Let us know if you spot issues or are having trouble using it.
Thanks!
