### ISSUE TITLE
Pulling Feeds from OpenCTI to MISP

### ISSUE THREAD

**Issue by realzacharycheng** [MISP/MISP#7565]
**Is your feature request related to a problem? Please describe.**
Right now I want to pull feeds from OpenCTI to MISP, but at this moment there is only a OpenCTI connector pulling event and IoC from MISP to OpenCTI.

**Describe the solution you'd like**
A plug in that allow to pull result from OpenCTI to MISP.

**Comment by mokaddem** [comment]
Hello,
MISP can ingests `MISP format`, `STIX 1/2` and `unstructured text`.
I'm not aware of any connector on OpenCTI side to be able to push data to MISP directly, so your best bet would be to export in either in the MISP (if possible?) or STIX format, then feed the data to MISP directly.
Alternatively, you could also get in touch with the OpenCTI guys and request such connector. 
Cheers!
