### ISSUE TITLE
Feed ingestion pull limit - new MISP instance

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#7567]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | N/A
| MISP version / git hash   | 2.4.144
| Browser                   | Chrome, Firefox 

### Support Questions

Hi, I've just had to setup MISP from scratch. 

Wanted to know how I can limit the feed ingestion / pull to be just the most recent? Say just the last 30d? 

Is adding "timestamp" in Filter rules of each feed the only way to do it? That would be quite tedious and manual. Any other way to achieve this?

**Comment by mokaddem** [comment]
Hello,
So if I understand correctly, this is a feature request to have a setting to be applied globally for all feeds?
Thanks

**Comment by redbiker-svg** [comment]
Hey, it'll be great to get a feature for this; however, I'd like to know how to achieve this before feature is created & pushed.

**Comment by redbiker-svg** [comment]
Hi @mokaddem - any updates on this?

**Comment by mokaddem** [comment]
@redbiker-svg If you are pulling a `misp` format feed, you can limit it using parameters. However for CSV/freetext feeds, this is not possible.
So indeed, currently the only way is to add the filtering criteria for all `misp` feed you are pulling.

**Comment by DefenceLogicAdm** [comment]
Can you provide an example filter is achieved as #7968 and #7998 indicate that this is not possible. Do you use the "Timestamp" field only?

**Comment by UFOSmuggler** [comment]
according to my testing, using a timestamp of now (or a day ago) will retrieve events from that point onwards only.  this is also reflected in the feed preview.

format it like: `{"timestamp": 1696386576}`
