### ISSUE TITLE
Pull from a specific date

### ISSUE THREAD

**Issue by toolost9** [MISP/MISP#7569]
Hello,

i connected two misp, when pull events start running events dating back to 2019. Is there a way to pull events from a specific date?

Thx for the support!

**Comment by mokaddem** [comment]
Hello,
You can add PULL rules in the server settings.
1. Click on `modify` in the Pull rules section
2. In `Addiction sync paramters` add your filtering rules. For example:
```json
{
    "timestamp": "365d"
}
```
3. Click on `Submit` to save
