### ISSUE TITLE
Integrity constraint violation when starting a discussion

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#758]
In version 2.4, when starting a discussion via "Discussions -> Start discussion" an upon clicking the button "Submit" after filling out the form, the following message error is displayed on the screen:

	
An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

In the error log there is the following trace:

2015-12-16 08:25:51 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sharing_group_id' cannot be null
Request URL: /posts/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1012): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1854): DboSource->create(Object(Thread), Array, Array)
#4 /var/www/MISP/app/Controller/PostsController.php(132): Model->save(Array)
#5 [internal function]: PostsController->add()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}

**Comment by adulau** [comment]
Confirmed on the testing instance.

**Comment by iglocska** [comment]
Let me know if it's not resolved with the last patch!
