### ISSUE TITLE
Sync Actions: additional pull rules doesn't work

### ISSUE THREAD

**Issue by remydewa** [MISP/MISP#7582]
# This template is meant for bug reports, if you have a feature request user the other template.

I'm trying to sync my misp server with another misp server of mine using addtional pull rules but it doesn't work.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian
| PHP version               | 7.3
| MISP version / git hash   | 2.4.144
| Browser                   | If applicable

### Expected behavior

 Follow the additional pull rules when I click on the "pull all" button or when I use cake command.

### Actual behavior

All events are synced (pulled), regardless of the additional pull rules filter

### Steps to reproduce the behavior

I have two MISP servers. I want to sync my server 2 with the events stored on my server 1 using additional pull rules. It's written in the "Set PULL rules"  popin:
"Additional sync parameters (based on the event index filters)"

So I'm going to the "events/automation" page to see what it is possible to do and I read:
- "searchDatefrom: Filters on the date, anything newer than the given date in YYYY-MM-DD format is taken - non-negatable"
- "publish_timestamp: Restrict the results by the timestamp of the last publishing of the event. The input can be a timetamp or a short-hand time description (7d or 24h for example). You can also pass a list with two values to set a time range (for example ["14d", "7d"])."
- " searchDatefrom: Filters on the date, anything newer than the given date in YYYY-MM-DD format is taken - non-negatable"
- ....

None of these filters workc when I click on the "pull all" button of my server from my servers list page or when I run the command:
"/var/www/MISP/app/Console/cake Server pull 9 2" (where 9 is my user id and 2 my server id)

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/53039170/126392174-1761cbfa-87e5-483e-985d-7e3f265532f4.png)
too much events are pulled...
![image](https://user-images.githubusercontent.com/53039170/126395875-2c711ae9-9426-43a0-9094-76de573c6779.png)

What I'm doing wrong?

Thanks for your help!

**Comment by righel** [comment]
Hello,
Please correct the JSON payload, the additional sync parameters should look like this:
```
{
   "searchDatefrom": "2021-07-19"
}
```

**Comment by remydewa** [comment]
thanks a lot! I'm pretty sure I tried it too. I must have been wrong somewhere....but now it's working! thanks :)
