### ISSUE TITLE
MISP DB location

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#7585]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4

### Support Questions
Where can I find the database of my MISP instance and is there a DB Schema available?

Is it possible to create an additional user on the DB with custom access to tables (as required)? 

I'm planning on ingesting Event & IOC logs via an App that'd connect into the DB. 

Any thoughts / issues on this from by the community? 

### Logs, screenshots, configuration dump, ...
None for now

**Comment by mokaddem** [comment]
On Ubuntu, the MISP installer uses MySQL. You should be able to get the schema and create additional user by having a look at the MySQL documentation https://dev.mysql.com/doc/refman/8.0/en/
