### ISSUE TITLE
Attribute::__construct(): Argument #1 ($flags) must be of type int, array given

### ISSUE THREAD

**Issue by chrisnewmanuk** [MISP/MISP#7588]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| Python | 3.9
|MISP|latest
### Expected behavior
attributes are added form freetext

### Actual behavior
attributes fail to add

### Steps to reproduce the behavior
new event and add IOCs using free text tool
34[.]3[.]2[.]1
116[.]3[.]2[.]1
88[.]3[.]2[.]1
74[.]3[.]2[.]1
180[.]3[.]2[.]1
142[.]3[.]2[.]1

adding 3 or 4 attributes at a time adds  them ok as it doesnt post it as a job

(I've edited the IPs but even this list fails)

### Logs, screenshots, configuration dump, ...
Error: Attribute::__construct(): Argument  ($flags) must be of type int, array given
 [internal function]: Attribute->__construct()
 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
 /var/www/MISP/app/Console/Command/AppShell.php(34): Shell->initialize()
 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
 {main}

![image](https://user-images.githubusercontent.com/7243321/126502277-7e5caa6d-fb79-4fe8-b7bf-8612fa513267.png)

**Comment by panpietrek** [comment]
Same thing here when trying to fetch events from a networked MISP feed.
resque-worker-error.log:

```
Error: Attribute::__construct(): Argument #1 ($flags) must be of type int, array given
#0 [internal function]: Attribute->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#5 /var/www/MISP/app/Console/Command/AppShell.php(34): Shell->initialize()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#11 {main}
```

![obraz](https://user-images.githubusercontent.com/13390324/126767108-cab69f31-a370-4c63-9aab-69d5230a5417.png)

**Comment by righel** [comment]
Hello,
I could not reproduce your issue. Can you share which MISP version are you using? Please update to the latest version and check again.

**Comment by righel** [comment]
Ensure background jobs are not using php-cli version +8, that can trigger this error.

**Comment by vikasbadolainfi** [comment]
I am getting the same issue alfter login in every page of my misp instance
is someone help me to resolve this issue
