### ISSUE TITLE
Changing feed and event to another user/organization

### ISSUE THREAD

**Issue by Ian-Costa18** [MISP/MISP#7591]
Hello,

I imported a lot of feeds (~70) and fetched them all into the database. It's very hard to look at the event list as it has over 2,000 different events and I can't filter it out because they are assigned to me and are in my organization. I want to put all of the feed events into another organization and under a different user. I tried to edit the org_id using PyMISP but when I run misp.update_event gives the error "Event in the request is not newer" so it didn't seem to be possible.

Is there another way to transfer all of these feed events to another org/user?

**Comment by mokaddem** [comment]
Ownership is a sensitive component in MISP. If you really have to give these events to another orgs, you can still rely on the delegation functionality. However, given the amount of events you have to transfer ownership, you'll have to automate this task via PyMISP/API.
