### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by qbolbk59** [MISP/MISP#7592]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2
| MISP version / git hash   | 2.4.141
| Browser                   | Chrome

### Support Questions
My MISP instance was working fine since for last 7-8 weeks but now all of a sudden it's throwing error "503 Service Unavailable". The login page itself is not accessible. If i check the error log, i can see the below error:

```
2021-07-22 08:30:40 Error: [PDOException] SQLSTATE[HY000]: General error: 9001 Max connect timeout reached while reaching hostgroup 1 after 600471ms
Request URL: /
Stack Trace:
#0 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /app/MISP/app/Model/User.php(232): Model->find()
#7 [internal function]: User->__construct()
#8 /app/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#9 /app/MISP/app/Controller/AppController.php(133): ClassRegistry::init()
#10 /app/MISP/app/Controller/EventsController.php(62): AppController->beforeFilter()
#11 /app/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#12 /app/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#13 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#15 /app/MISP/app/webroot/index.php(92): Dispatcher->dispatch()
#16 {main}
```

I have two instances load balanced over F5. On the other instance i can access the UI and can login but can't open any Event. Both instances share the same MySQL database in the backend. 
But this instance is not accessible at all.

Any idea how to fix this ?

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/43533246/126598557-83641429-a8b7-4141-bfb1-b2c8f8642fbb.png)

**Comment by robben-ar** [comment]
Same issue.-

**Comment by mokaddem** [comment]
Hello,
It seems to be a configuration issue with your MySQL load balancing setup rather than a MISP bug.
Would you mind making sure that everything is configured correctly?
Thanks!

**Comment by qbolbk59** [comment]
The issue was indeed with the ProxySQL config which we are using to loadbalance the backend MYSQL servers. Fixed long ago but updating now.
Sorry  for late response !
