### ISSUE TITLE
[Filtering Tool Issue] Attribute warning: This event doesn't have any attributes visible to you

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#7594]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS, Windows
| PHP version               |7.4.21
| MISP version / git hash   |  MISP 2.4.146 
|Browsers  | Firefox, Chrome, Safari

### Expected behavior

Using Filtering Tool , select [Show Correlation Only] and [Show 
![2021-07-17_10-00-27](https://user-images.githubusercontent.com/3220193/126628303-310ac4f6-a8ea-4c17-aa63-b4ec2e361c00.png)
![2021-07-17_10-00-47](https://user-images.githubusercontent.com/3220193/126628388-9746d853-dc36-41af-a374-7ce82106680f.png)
Related Tags]
See a list of Attributes with Correlations and their Related Tags

### Actual behavior

Receive error:

Attribute warning: This event doesn't have any attributes visible to you. Either the owner of the event decided to have a specific distribution scheme per attribute and wanted to still distribute the event alone either for notification or potential contribution with attributes without such restriction. Or the owner forgot to add the attributes or the appropriate distribution level. If you think there is a mistake or you can contribute attributes based on the event meta-information, feel free to make a proposal

### Steps to reproduce the behavior

  (1) Open Event
  (2) Click on Filtering Tool
  (3) Select:
-     Show Correlation Only
-     Show Related Tags

### Key Observation
If one just specifies the resultant URL the expected results are displayed (i.e., https://<URL>/events/view/267882/correlation:1/includeRelatedTags:1

**Comment by packet-rat** [comment]
Hey folks - this is a pretty serious defect.  What's it take to get on your radar?

**Comment by packet-rat** [comment]
Just checked MISP 2.4.148: **Filtering Tool is still broken**.  This serious bug should be a simple one to find and fix.   I have to presume other filer combinations are likely broken as well, returning false negatives.  Even if not, this is a primary filtering Use Case for us.

**What's it take to get it on your radar?**

**Comment by mokaddem** [comment]
Hello,
I tried to reproduce the issue following the described steps without success.
Everything is working as intended on my end.
However, I found an inconsistency about how the `deleted` flag is being handled if not specified.
The commit above should solve this particular issue.
Let us know if it also solves yours.
Thanks.

**Comment by packet-rat** [comment]
Passed on to our Dev Team - will advise.
