### ISSUE TITLE
Object Template Tsk-web-search-query v1 wrong type of field domain - thus fails with error "failed validation - not the right type/format"

### ISSUE THREAD

**Issue by vibenas** [MISP/MISP#7599]
Object Template Tsk-web-search-query v1  requires domain as mandatory fieldof type link, thus default options are not in format https://, thus fails.

probably should be modified as "other", rather than "link".

Error: "Could not save object as at least one attribute has failed validation (domain). {"value":["Value not in the right type\/format. Please double check the value or select type \"other\"."]}"

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.146

### Expected behavior

possibility to save the Object from object Template Tsk-web-search-query v1  

### Actual behavior

run into error, listed above.

### Steps to reproduce the behavior

try to create an object and fill the domain.

### Logs, screenshots, configuration dump, ...

![Screenshot 2021-07-25 093733](https://user-images.githubusercontent.com/85502124/126890117-0b6ccc47-2451-4b0b-b0c8-c9ef25df734f.jpg)

**Comment by adulau** [comment]
Thanks for the report. Object template has been fixed https://github.com/MISP/misp-objects/commit/7d7cea0459ff7c8ec5e0d8e798b6ee85db6698b5 and updated on the core repositories.
