### ISSUE TITLE
MISP event syncronization failed

### ISSUE THREAD

**Issue by DavidXie10** [MISP/MISP#7604]
Hello everyone! I am new to MISP and I have a problem. I currently have a testing environment where I have 2 synchronized MISP instances, which I will call MI1 and MI2 to explain the problem.

The situation is the following: when I create and publish an event from the MI1 instance with an attribute and a tag of some taxonomy, it arrives to MI2, but if I try to add more attributes or tags from MI2 to the same event, these are not updated in the MI1 event (even after publish it). I wanted to know if it is possible to update the event in MI1 (the original event) and if so, how could it be done.

First I do a push from MI1 so that the event is distributed to MI2, then after adding attributes in MI2 I do a pull from MI1, but in the log I get that no event has been pulled.

I am happy to provide any additional information that you need.

Thank you in advance.

**Comment by mokaddem** [comment]
Hello,
Indeed, MISP has a mechanism to avoid other MISP instances overriding the data that was originally created on the initial instance.
Usually, if you need to update data from an event created on another MISP instance (or from another organisation) you have to use `proposals` which get synchronised back if the event came from another instance.

Another solution could be to mark the synchronisation of the two instances to be `internal` (more info [here](https://www.circl.lu/doc/misp/sharing/)).
If you want to stick to your use-case, could you make sure that:
1. Both instances have the same `orgc` and `org` used for the event (the UUID must be the same, the name is irrelevant)
2. The synchronisation connection for both instances have the `internal` flag checked

Then, **M1** and **M2** will act as if they are the same instance and thus, you should be able to propagate modifications from **M2** to **M1**.

Let us know if it's not the case.
Cheers!
