### ISSUE TITLE
/attributes/restSearch is broken on splunk with misp

### ISSUE THREAD

**Issue by ParastouRazi** [MISP/MISP#7605]
Hi ,I install MISP OVA Virtual Machine but splunk with misp42splunk apps don't get data from MISP ,i have this error on splunk with misp ,please help me
External search command 'mispgetioc' returned error code 1. Script output = "error_message=Exception at "F:\Splunk\etc\apps\misp42splunk\bin\mispgetioc.py", line 453 : [IO302] ERROR mispgetioc failed for url=https://192.168.5.55/attributes/restSearch with HTTP Error=403. Check search.log for details ".

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Splunk on Windows server
| OS version (client)       | Win 10
| MISP version / git hash   | 2.4.146 ova virtual machine
| Browser                   | google chrome
| misp42splunk

**Comment by adulau** [comment]
HTTP error code is 403. It could be an incorrect API key or an Apache misconfiguration.

**Comment by ParastouRazi** [comment]
> HTTP error code is 403. It could be an incorrect API key or an Apache misconfiguration.

hi,thanks for your reply but i download MISP OVA and MISP work ok but the data can'nt recieve splunk side

**Comment by adulau** [comment]
Did you check your API key? Create a new API key and update it on misp42splunk.

**Comment by ParastouRazi** [comment]
> Did you check your API key? Create a new API key and update it on misp42splunk.

Thanks very much ,api key wasn't set correct
now my problem solved
