### ISSUE TITLE
restSearch is broken

### ISSUE THREAD

**Issue by masual** [MISP/MISP#7611]
It seems after the transition to OpenAPI the RestSearch endpoint is completely messed up.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| PHP version               |  7.4
| MISP version / git hash   | 2.4.147
| Browser                   | Postman

### Expected behavior
When using `restSearch` from `events `and `attributes `endpoints (`events/restSearch` and `attributes/restSearch`), it is expected to return events and attributes respectively. 
When stablishing `returnFormat` to `suricata`, it is expected to return a Suricata rule file.

### Actual behavior
The current API is returning only events in both endpoints. Moreover, the returnFormat parameter is broken, and it seems the only two values that are being considered are `json `and `xml`. It is not posible to generate a Suricata rule file at the moment.

Previous versions of the API allowed for obtaining a Suricata ruleset by querying this endpoints, and at the moment this functionality is completely broken.

### Steps to reproduce the behavior
Migrate from MISP v2.4.132 to v2.4.147 and query restSearch endpoints.

**Comment by righel** [comment]
Hello @masual ,
The OpenAPI was a new documentation added, it didn't change the API implementation. Are you reporting an error in the docs? if so, could you elaborate a bit more?

If it's an API issue, can you share your API request payloads? I did a quick check and suricata exports seem to work OK both via attributes and events endpoint.

**Comment by masual** [comment]
Thank you for your fast response @righel 

```
curl -X POST \
  https://misp/events/restSearch \
  -H 'Authorization: xxxx' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{"returnFormat": "suricata", "timestamp": "1d"}'
```


The same request to  https://misp/attributes/restSearch returns the same response, both seems to be returning only events and in JSON format.

**Comment by masual** [comment]
After messing arround with Postman I found the problem was other. As you suggested the API seems to be working exactly as before. Somehow the Postman request was being performed as follows:

```
curl -X POST \
  'https://misp?Authorization=xxx' \
  -H 'Accept: application/json' \
  -H 'Authorization: xxx' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: cac3c703-1533-4183-b3ea-94ad65e28e3b' \
  -H 'cache-control: no-cache' \
  -d '{"returnFormat": "suricata", "timestamp": "1d"}'
```


This malformed request returns a response with events. If I changed the `returnFormat `value from `suricata  to `xml` or `json` it was returning the results with the specified format and that was what was driving me crazy. I was also changing the endpoint on Postman but it was being ignored in the actual request, thats why I thought both `events/restSearch` and `attributes/restSearch` were returning only events.

Thank you very much and sorry for the missunderstanding.

**Comment by righel** [comment]
No problem, glad it worked!

**Comment by masual** [comment]
Just in case you want to dig arround this strange behaviour of the API, the same request without the `Accept` header is returning a 401 error.

```
curl -X POST \
  'https://misp?Authorization=xxx' \
  -H 'Authorization: xxx' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: cac3c703-1533-4183-b3ea-94ad65e28e3b' \
  -H 'cache-control: no-cache' \
  -d '{"returnFormat": "suricata", "timestamp": "1d"}'
```
