### ISSUE TITLE
Schema inconsistency errors for table 'audit_logs'

### ISSUE THREAD

**Issue by dpreuveneers** [MISP/MISP#7618]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.147

After updating MISP, I get an error that the database schema is inconsistent for the table `audit_logs`, and this more specifically for the 3 columns `model_title`, `event_id` and `change`. 

I was able to fix the inconsistent schema by updating the entry for `audit_logs` in the  `/var/www/MISP/db_schema.json` file (or  [https://github.com/MISP/MISP/blob/2.4/db_schema.json](https://github.com/MISP/MISP/blob/2.4/db_schema.json)) and changing the `column_default` field for the above 3 columns from `"NULL"` to `null`.

Although I do not get any errors, I noticed that the columns `request_id` and `ip` of the same table have a similar `"NULL"` value for the field `column_default`. Perhaps these default values should also be updated to `null`?

I have reported a similar issue like this before with a similar fix (see #7137)

**Comment by mokaddem** [comment]
Hello, it seems the `"NULL"` issue was fixed in the meantime.
Would you mind to update your instance and check again?
Thanks!

**Comment by dpreuveneers** [comment]
Indeed, I was able to upgrade my MISP instance and the above issues appear to have been resolved.
