### ISSUE TITLE
How can i see/copy my API Auth Key from my MISP instance? Auth Key is Hidden

### ISSUE THREAD

**Issue by Panagiss** [MISP/MISP#7621]
When i go to my profile page or the auth key's list, i cannot see the full API Auth Key. Security reasons of course but i need somehow to take in order to make the requests to the API.

I know there must be a way, but either the docs are poor about that problem( from what i saw docs seemed really good) or there must be a bug or I'm doing something wrong here.

Well i have an auto generated auth key where i can see only the first and the last characters only. So how I'm supposed to get it anyways?
I have gone to the Automation page and the My profile page and List auth keys page but with no luck.

Thanks in advance.

**Comment by righel** [comment]
Hello @Panagiss,
As an admin you can see your users API keys on this page: `/admin/users/index`.
As a regular user you can see your API key on this page: `/users/view/me` and clicking in the eye icon:
![image](https://user-images.githubusercontent.com/1659902/127997538-0f95df72-af31-4d1e-8dfe-6ba52d573365.png)

The API key is also visible in the `/events/automation` page.

**Comment by Panagiss** [comment]
Hi @righel,
I don't know why but i haven't the eye icon in there. Take a look:
![Screenshot from 2021-08-03 13-05-30](https://user-images.githubusercontent.com/56695201/127998498-20072ecb-0f53-4ceb-9444-466d6e722d48.png)

The far-right eye icon you see, when i click it, it goes to `/auth_keys/view/1` and from there again there is not an eye icon to reveal the auth key.

Also take in mind that the pic above is form `/users/view/me`

**Comment by iglocska** [comment]
@Panagiss - there are two authentication key schemes in MISP, you are using the "advanced auth keys" - these are hashed and not recoverable from the system. You can however always add more keys / revoke previous keys from the auth key management of each user.

**Comment by Panagiss** [comment]
> @Panagiss - there are two authentication key schemes in MISP, you are using the "advanced auth keys" - these are hashed and not recoverable from the system. You can however always add more keys / revoke previous keys from the auth key management of each user.

Thanks for the info. I couldn't find good doc about the differences of advanced and simple keys. That's why i was unaware of this. 
Thanks again.

**Comment by jufirst** [comment]
how to unmask the api key
PQkt••••••••••••••••••••••••••••••••xfTU

**Comment by jufirst** [comment]
![image](https://github.com/MISP/MISP/assets/33620474/d8906513-3d8e-4b8e-9bcc-301ca9ab2490)

**Comment by jufirst** [comment]
I can't full api key that plain string

**Comment by Kagee** [comment]
This key was converted from a old API key system to the new auth key system. If you did not note down the key before the convertion there is on purpose no way to recover it, and you will have to make a new key.

If the is from a misp-docker instance, the key was printed to the logs on the first startup. 

Please create a ticket of your own if you have questions, and do not add to old tickets.
