### ISSUE TITLE
Controller class Apple-touch-icon-precomposed.pngController could not be found

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#763]
I see the following in the error log. I don't have more infos

2015-12-16 10:55:23 Error: [MissingControllerException] Controller class Apple-touch-icon-precomposed.pngController could not be found.
Exception Attributes: array (
  'class' => 'Apple-touch-icon-precomposed.pngController',
  'plugin' => NULL,
)
Request URL: /apple-touch-icon-precomposed.png
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-12-16 10:55:24 Error: [MissingControllerException] Controller class Apple-touch-icon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Apple-touch-icon.pngController',
  'plugin' => NULL,
)
Request URL: /apple-touch-icon.png
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

**Comment by iglocska** [comment]
This is simply someone (or most likely a bot) probing your site for https://www.yourmisp.com/Apple-touch-icon-precomposed.png

MISP does URL rewriting and the first parameter is the controller name - which in this case is invalid and MISP correctly throws an exception.
