### ISSUE TITLE
Workers cannot start; Redis connection refused

### ISSUE THREAD

**Issue by ggrocott** [MISP/MISP#7630]
## Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.4.10
| MISP version / git hash   | 2.4.148

### Support Questions

I have an issue with the Workers all showing Red and cannot start them. I am new to this so unsure where to start troubleshooting. 

### Logs, screenshots, configuration dump, ...
ps -aux | grep redis
redis    32335  0.1  0.9 205804 161244 ?       Ssl  10:53   0:08 /usr/bin/redis-server 127.0.0.1:6270

sudo ufw status
Status: inactive

redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3

/var/www/MISP/app/Console/cake CakeResque.CakeResque stop --all
Error: Connection refused
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run()
#9 {main}

![MISP Workers Dead](https://user-images.githubusercontent.com/41739093/128516212-a16afa03-8f8b-4aa4-b7ed-c705ac2696d0.PNG)

**Comment by righel** [comment]
Hello @ggrocott,
Was it working before and it stopped?
Have you changed anything in the following configuration file: `app/Plugin/CakeResque/Config/config.php`? Check if the values there are correct.
Check in your main config file `Config/config.php` the following settings and their values:
* `MISP.redis_host`
* `MISP.redis_port`
* `MISP.redis_database`
* `MISP.redis_password`

**Comment by ggrocott** [comment]
Hi @righel,

Nothing was changed before in the configuration for those settings. They remained as-is before it broke. When i try manual start, I get the following:

#9 {main}
Error: Connection refused
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run()
#9 {main}

I have looked in the logs while i ran the command and nothing comes up.

Is there anything else to look at?

**Comment by righel** [comment]
Could you please you output the status of `sudo service redis status` ?
Seems your redis server is running on the 6270 port rather the default port 6379.
Could you please double check `app/Plugin/CakeResque/Config/config.php:L69-L71` matches this conf?
$config['CakeResque'] = array(
```
'host' => 'localhost',		// Redis server hostname
'port' => 6370,			// Redis server port
```

**Comment by ggrocott** [comment]
redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-08-11 12:39:27 UTC; 20min ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 8385 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 8479 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
 Main PID: 8492 (redis-server)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/redis-server.service
           └─8492 /usr/bin/redis-server 127.0.0.1:6270

Yes, but i or anyone else haven't changed this. V.Weird

Output from config:

 *
 * @see CakeResque::init(), CakeResque::loadConfig().
 */
$config['CakeResque'] = array(
        'Redis' => array(
                'host' => 'localhost',          // Redis server hostname
                'port' => 6379,                         // Redis server port
                'database' => 0,                        // Redis database number
                'namespace' => 'resque',        // Redis keys namespace

**Comment by righel** [comment]
So changing your config.php setting:
`'port' => 6379, // Redis server port` -> `'port' => 6270, // Redis server port` 
 should solve it.

Let me know if that works.

**Comment by ggrocott** [comment]
Perfect.... yes they are now....

Thanks for your assistance.
