### ISSUE TITLE
MISP database broken?

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#7642]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.144 (I believe) 
| Browser                   | Chrome, Firefox

### Support Questions

Hi @iglocska 

Sorry about direct tag, but hoping you're the saviour. 

I ran into an issue with my MISP and had to make some changes on disk space. I cloned the working VM, expanded disk size and got those bits sorted. 

As a test before following same expansion in production, I wanted to test MISP and unfortunately I've run in the below Database connection issue. I have literally made no changes to any configs as such. 

Do you know what causing this? Screenshot below is from error.Log

Additionally, when accessing MISP GUI, I'm constantly running into "An Internal Error has occurred" page which led me to check error.log file and found the below 

Or did anything in the disk expanse break any MISP bits - I doubt? 

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/62763192/129010304-96ee69d8-70d0-4d71-852a-41234002423b.jpeg)

**Comment by righel** [comment]
Hello @redbiker-svg,
1. Is MySQL up? 
check: `sudo service mysql status`
2. Are you sure the credentials are ok? check connecting via CLI using the values from `Config/database.php`
check: `mysql -h xx.xx.xx.xx -u "misp" -p`
3. Do you use ssl certificates for connecting to the MySQL server or any kind of special configuration? If so, are there cert/keys files in the specified directories and `www-data` has read permissions on them?

**Comment by redbiker-svg** [comment]
Hi @righel 

1. MySQL is not up :(
![image](https://user-images.githubusercontent.com/62763192/129039145-f5922403-1237-441a-a808-3d9c5e737d7a.png)

Checked error.log once again and below was seen
![image](https://user-images.githubusercontent.com/62763192/129039216-1a8b9d68-f312-486c-9335-4bb28d0cb88c.png)

below is from systemctl status mysql.service
![image](https://user-images.githubusercontent.com/62763192/129039914-e0ab006b-3ba2-4617-95f6-5228900fefdc.png)


Alos, if i try starting my workers, below is seen
![image](https://user-images.githubusercontent.com/62763192/129039487-ad1589fb-efff-4fe9-9270-73f3e04c7936.png)

2. Checked and connection was refused - I haven't changed any config so unsure why connections would be refused; but this to me looks like some IP config issue?

![image](https://user-images.githubusercontent.com/62763192/129042240-bea92c7a-15fa-45f5-ac91-27c84987a4b3.png)

3. Nope, nothing of this sort

**Comment by righel** [comment]
Can you attach your mysql error log file `/var/log/mysql/error.log`, or check if there's anything relevant there?
If you can't find any logs, modify your mysql settings file `/etc/mysql/my.cnf`, add the following lines at the bottom:
```
log-bin=/var/log/mysql/mysql-bin.log
general-log=/var/log/mysql/mysql.log
log-error=/var/log/mysql/mysql-error.log
```
Then try to start the mysql server again and check the error logs.
This guide might help too: https://dev.mysql.com/doc/refman/5.6/en/starting-server-troubleshooting.html

For the workers showing "Operation not permitted" probably you have to run that `start.sh` script as sudo.

**Comment by redbiker-svg** [comment]
Hi, here's the output from mysql error.log before adding those 3 lines in my.cnf

![image](https://user-images.githubusercontent.com/62763192/129055519-577bb90d-a4e3-4463-b1df-3ffaabf0d9bf.png)

And the output post adding 3 lines is practically the same as above. I used `sudo system service mysql start`

**Comment by redbiker-svg** [comment]
Hi @righel 

Hazarding a guess here, but, has the disk expansion altered any permissions or corrupted the database in any way that's causing it to not start? 

Or any other script maybe?

**Comment by righel** [comment]
This seems to be relevant:
```
[Note] Recovering after a crash using tc.log
[ERROR] Can't init tc log
[ERROR] Aborting
```

What it seems is that your databases [transaction log](https://mariadb.com/kb/en/transaction-coordinator-log-overview/) got corrupted when the server run out of space and now it's failing to parse that file in order to recover the lost/hanged transactions when the server crashed.
After a quick google search, this articles may help you to resolve it:
https://en.danielrosiles.com/mysql-error-database-tc-log/
https://dba.stackexchange.com/questions/151183/mariadb-cant-init-tc-log

Let me know if you are able to fix it, even though this is not a MISP issue, it may be helpful for other user that run in the same problem.

**Comment by redbiker-svg** [comment]
Ah! That's a great spot. Thank you. 

I'll try these steps and update the thread. Really appreciate all the help so far

**Comment by redbiker-svg** [comment]
Ok, this has worked. SQL service has now started and I can finally see the login page on MISP GUI - Thanks a ton for all the help on this (*＾-‘) 乃. 

I should setup an alert for when disk space is over X%

Is there anything else that needs to be done now? My login is stuck in a loop with user account I've always used.. Hoping the above steps didn't clear off data? (´･_･`)

Don't want to try using the inital login incase that'd trigger a fresh MISP instance..

I also tried `mysql -h xx.xx.xx.xx -u "misp" -p` and now ended with `"ERROR 1130 (HY000): Host 'xx.xx.xx.xx' is not allowed to connect to this MariaDB server"`

**Comment by redbiker-svg** [comment]
Additionally, are these of concerns from /var/www/MISP/app/tmp/logs/error.log?

![image](https://user-images.githubusercontent.com/62763192/129175092-f1f3ab02-b7f5-4441-ab81-28692af4b9f3.png)

From resque-scheduler-error.log

![image](https://user-images.githubusercontent.com/62763192/129177766-b9b68b27-a573-46e5-a664-a834bf7cb8f9.png)

From  resque-worker-error.log

![image](https://user-images.githubusercontent.com/62763192/129178616-1eb20511-68f9-4c31-87ef-b153f7e49b96.png)

**Comment by righel** [comment]
Do you have MISP codebase and MariaDB server installed on different hosts? If not, why are you accessing the database using a IP instead of localhost/127.0.0.1? Maybe you need to adjust the `host` in `app/Config/database.php` .

Check if your database credentials stored in `app/Config/database.php` are correct, could be that the `misp` user does not have access via remote host check: https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/

For the Redis errors, check the following:
1. Is Redis running? `sudo service redis status`
2. Check in your main config file Config/config.php the following settings and their values:
      ```
      MISP.redis_host
      MISP.redis_port
      MISP.redis_database
      MISP.redis_password
      ```
3. If settings from 2. are not set, check if the values in `app/Plugin/CakeResque/Config/config.php:L69-L71` are correct.

**Comment by redbiker-svg** [comment]
Update - I did finally log in, however it was super super slow. Over maybe 15 mins before I was in. Any further clicks are still stuck in loading loop.

**Comment by redbiker-svg** [comment]
> Do you have MISP codebase and MariaDB server installed on different hosts? If not, why are you accessing the database using a IP instead of localhost/127.0.0.1? Maybe you need to adjust the `host` in `app/Config/database.php` .
> 
> Check if your database credentials stored in `app/Config/database.php` are correct, could be that the `misp` user does not have access via remote host check: https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/
> 
> For the Redis errors, check the following:
> 
> 1. Is Redis running? `sudo service redis status`
> 2. Check in your main config file Config/config.php the following settings and their values:
>    ```
>    MISP.redis_host
>    MISP.redis_port
>    MISP.redis_database
>    MISP.redis_password
>    ```
> 3. If settings from 2. are not set, check if the values in `app/Plugin/CakeResque/Config/config.php:L69-L71` are correct.

Will check and udpate

**Comment by redbiker-svg** [comment]
> Do you have MISP codebase and MariaDB server installed on different hosts? If not, why are you accessing the database using a IP instead of localhost/127.0.0.1? Maybe you need to adjust the `host` in `app/Config/database.php` .
> 
> Check if your database credentials stored in `app/Config/database.php` are correct, could be that the `misp` user does not have access via remote host check: https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/
> 
> For the Redis errors, check the following:
> 
> 1. Is Redis running? `sudo service redis status`
> 2. Check in your main config file Config/config.php the following settings and their values:
>    ```
>    MISP.redis_host
>    MISP.redis_port
>    MISP.redis_database
>    MISP.redis_password
>    ```
> 3. If settings from 2. are not set, check if the values in `app/Plugin/CakeResque/Config/config.php:L69-L71` are correct.

1. Redis looks fine and running

![image](https://user-images.githubusercontent.com/62763192/129210327-cc282bfb-afe5-4f0a-90b8-d67c8b5b3554.png)

2. Redis config looks okay as well; given I didn't change anything before / after disk & db issues. However, was researching on this and found #5138. Do I need to add those 4 lines of 

```
config.php: 'ZeroMQ_redis_host' => 'localhost',
config.php: 'ZeroMQ_redis_port' => 6379,
config.php: 'ZeroMQ_redis_database' => '1',
config.php: 'ZeroMQ_redis_namespace' => 'mispq',
```

![image](https://user-images.githubusercontent.com/62763192/129210624-ed1672c5-cae6-42de-8749-3499eb4b4bb3.png)


3. Settings in 2 are in place and okay; but is a password needed for Redis?

**Comment by redbiker-svg** [comment]
I can now login into MISP, however, its extremely slow. 

On successful login, I'm taken to the List Events page, but any other clicks from there are stuck in a constant loading loop as well. 

Is this expected / known? 

![image](https://user-images.githubusercontent.com/62763192/129211295-9de5126e-6343-4858-a0b0-2e5e4f0f0b15.png)

**Comment by righel** [comment]
ZeroMQ settings are not required if you don't plan to use that [feature](https://www.circl.lu/doc/misp/misp-zmq/).
Some resources that might help you troubleshoot the database:
* to check what's running on the database run: `mysqladmin -u root -p processlist`
* diagnose slow queries: https://mariadb.com/kb/en/slow-query-log-overview/
* check if there's enough free space in the data-dir directory partition

**Comment by megupta** [comment]
Run mysqlcheck on your database

**Comment by redbiker-svg** [comment]
We can close the case. Got it working now. Thanks @righel - massively helped me.
