### ISSUE TITLE
I am trying get data from misp using auth key

### ISSUE THREAD

**Issue by dipenpatel235** [MISP/MISP#7647]
## I have install python module pymisp on my Ubuntu Linux system and trying to get data from misp URL using auth key but somehow it is giving me 405 error.

ERROR:
Something went wrong (405): {'name': 'You do not have permission to use this functionality.', 'message': 'You do not have permission to use this functionality.', 'url': '/feeds/index'}

Does anyone have solution about this?

**Comment by righel** [comment]
Hello @dipenpatel235 ,
Seems that the user linked to the auth key you are using doesn't have permissions required to list the Feeds.
To list the feeds your User needs to either have the `admin` Role or be a User belonging to the Organisation specified in the `MISP.host_org_id` setting.
