### ISSUE TITLE
API issue - time representation

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#765]
On the 2.4, if you use the API, if you specify 2 days as 2d doesn't give any output. But the other hand, if you specify as 2da or 2day or 2days. 

Tested on fresh installation of 2.4 with PHP 5.5.9+dfsg-1ubuntu4.14.

**Comment by iglocska** [comment]
It works but it's based on the publish time not the date field. It's kind of counter intuitive and not well enough described but:

from and to fields work on the event date field
the "last" parameter works on the publish timestamp.

**Comment by adulau** [comment]
This was clarified in the documentation.
