### ISSUE TITLE
Sync from Remote MISP Server Silently Failing

### ISSUE THREAD

**Issue by geudrik** [MISP/MISP#766]
I've scrubbed the prior box that was giving me issues. Moving forward, I've got everything back up and running, minus one thing - remote sync with another MISP server

I have flushed the `jobs` table in MySQL after stopping the workers, and having cake clear and reset the cache. 

I have `straced` and `tcpdump`d and watched TLS traffic go back and forth.

I spun up a `netcat` listener and added a remote server to my local host to see what the worker was requesting. Using that info, I manually requested from the remote server and was able to pull XML back.

The worker never fails, but it never does anything, either. The logs show nothing other than the worker spun up, and `strace` / `tcpdump` simply shows minimal TLS traffic going back and forth, but certainly not enough data to be the mass XML dump I get when I use wget.

Any thoughts? I'm running the latest out of `master`

**Comment by Rafiot** [comment]
Do you still have the same problem on the HEAD of the branch 2.4?

**Comment by geudrik** [comment]
I did, yes, though I don't have that VM spun up at this point.. :S

**Comment by geudrik** [comment]
Closing this issue as I'm building a 2.4 instance from scratch, using a DB dump I have. Will reopen if I continue to have the issue on the 2.4 branch.

**Comment by geudrik** [comment]
Am now testing on a fresh 2.4 (latest from HEAD) install and I'm still not able to pull from a source. The source is running 2.3 latest, however. I am only trying to pull. Same symptoms as described in the initial post.

Happy to provide logs / dig deeper if I can get some guidance.

**Comment by Xen0ph0n** [comment]
Additional context, in 2.4 connection test is successful, indicating that the server is available for pull, you can browse the remote server (great feature BTW) and select an event for pulling. However none of these jobs begin working beyond what is outlined above. They simply hang at zero percent.

**Comment by iglocska** [comment]
I am looking into it and will push a patch later today. I have a feeling that this is actually 2.3 related (found a bug that causes too many log entries on 2.3 when API logging is enabled that slows down the event view enough to cause the effect described). I'll update this thread once it's resolved!

**Comment by geudrik** [comment]
The new server we have stood up successfully completes both Full and Update Only pulls from the local server. TCPDump shows significant traffic during this process, but it's painfully slow, and after it finally completes, no new events are created (the logs seem to confirm this).

The remote server is running 2.3.178 and we're running 2.4.0 (so pull only, which is all we want anyway)

Looking at `htop -u www-data` shows an average 10ish% cpu time for a resque process, so I assume that's the worker. It also takes a painfully long time for any kind of progress to be displayed in the progress bar after the job has been picked up.

**Comment by iglocska** [comment]
That is indeed correct I am working on a fix. I have a feeling we're
looking at the same remote server and the issue is the remote server timing
out on event views due to an oversaturated log db. Will try to have the fix
for this asap.

**Comment by geudrik** [comment]
I was actually wondering about that.. though since I have no direct access to the server, I'm not able to see logs or anything.

Feel free to ping me directly if you want/need further diagnostic info - I suspect you're right in your suspicion :smile:

**Comment by iglocska** [comment]
Hehe I was talking to @elhoim already about it, he'll push the fix once it's ready. It has to do with the damn contributors field which is parsing the logs to find the contributors (sure seemed like a good idea at the time!...) - with the API logging enabled and the really frequent and verbose proposal UUID lookup it has 10M entries that are being parsed on each event view. Terrible for performance but it will go away tonight or tomorrow :)

**Comment by geudrik** [comment]
Baha, those `hey this seems like a good idea` patches :P No sweat man, seriously appreciate you guys looking into this :)

If there's anything I can do to help, let me know!

**Comment by iglocska** [comment]
Will do! :)

**Comment by Xen0ph0n** [comment]
@iglocska rockstar! I also pinged @elhoim and I'm sure he hates me even more now.. as does @geudrik  for me blaming him. Thanks again all.

**Comment by Xen0ph0n** [comment]
Post logs flush on remote, it looks like the jobs process quickly (full sync or pulling specific events via remote browse). 

Logs on remote appear to show proper access to the events, however post completion nothing new is inserted into the DB on the local end. We'll troubleshoot further locally next week. I'm wondering if other 2.4 instances are syncing properly post fix?

**Comment by iglocska** [comment]
Hello Chris,

There was a patch for 2.4 earlier today, is this with that applied? I'll
have a look tonight and will try to reproduce it.

Best regards,
Andras

**Comment by geudrik** [comment]
I updated our codebase to latest and the job picks up quickly as expected, I'm able to see the TLS traffic etc, but no events are inserted into the database (still).

**Comment by iglocska** [comment]
I just tried a pull from the CIRCL instance and I am getting events in as expected, I'll try later on tonight with the instance that you are pulling from to see what's going on, but I have to run off for a few hours.

**Comment by geudrik** [comment]
It would appear that the DBs that I was working with were all .. broken. That is, at this point, the only conclusion that I can come to...

I reverted to a DB from an old migration and now imports from our mutual remote server are working as expected. I .. I got nothin'...

I would love to know what the difference is between the two database, so if you've got some ideas, I'd love to hear them. I'm going to diff the schemas tonight for shits and see if there's any discrepancy.

Thanks for all the help with this, Andras :) You're a champ!

**Comment by iglocska** [comment]
Oooh, I'd love to know what the difference was too. The upgrade script has gone through a series of revisions, so if we could pinpoint the issue I could write a tool that fixes it for anyone that runs into the same issue.

Glad it worked out in the end! B-)

**Comment by geudrik** [comment]
I diff'd the schemas, and the only differences were auto increment defaults :S So unfortunately that tells us nothing other than the schemas between the working and broken DBs are identical.

Other ideas?

**Comment by iglocska** [comment]
Hmph. Maybe one thing to check: Could you check if there was a difference in the role permissions between the users'  roles that you used to initiate the pull with? This is as much of a long shot as it gets though...
