### ISSUE TITLE
Invalid scope or id in event report

### ISSUE THREAD

**Issue by devdandi** [MISP/MISP#7660]
![errir](https://user-images.githubusercontent.com/45485349/129511241-2094e56a-ff25-4e27-8986-70bea36eb9e1.PNG)

Hello everyone. I got error when i am trying to see detail of event report. I did not understand about this error. Maybe MISP team or everybody else can help me. Thank you

**Comment by mokaddem** [comment]
Hey,
Can you check the following:
1. Verify that the markdown format used to reference the data point is correct
2. Verify that these UUIDs exist inside the event this report is linked to

Thanks!
