### ISSUE TITLE
Diagnostic schema status helper tool

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#7662]
Below is a DB fix that is not working.

![oneDb](https://user-images.githubusercontent.com/362025/129578861-646829e8-b6ea-42d9-82a0-0f4571389c81.png)

![twoDb](https://user-images.githubusercontent.com/362025/129578892-6acf7a6d-dffd-467a-bc31-bc2343c87ce0.png)

MariaDB [misp]> ALTER TABLE `audit_logs` MODIFY COLUMN `authkey_id` int(11) DEFAULT "NULL" NULL ;
ERROR 1067 (42000): Invalid default value for 'authkey_id'

**Comment by mokaddem** [comment]
Pushed a fix on develop that should make the entry disappear from the diagnostic widget.
Thanks!
