### ISSUE TITLE
How to remove double quote inside query 

### ISSUE THREAD

**Issue by devdandi** [MISP/MISP#7668]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Logs, screenshots, configuration dump, ...

![double_quote](https://user-images.githubusercontent.com/45485349/129834916-ba2216b9-3925-4087-a5bf-0a3cd9f8e035.PNG)

I am using PostgreSQL in MISP. But there are error when running some feature, because there is double quote inside query and then i am try to copy query and execute the query using pgAdmin app and remove double quote on query. There is no error after removing double quote. I found my problem are a double quote on query. Can MISP team or everybody else help me ? i am looking for where all the query are executed. I am have  planned to remove manually double quote

**Comment by mokaddem** [comment]
Hello,
Would you mind describing what you are trying to achieve?
Also, why would you need to us pgAdmin to use MISP?
Thanks
