### ISSUE TITLE
Option to register a sighting only if the IDS flag is set to true on the said attribute.

### ISSUE THREAD

**Issue by gallypette** [MISP/MISP#7669]
I would like to add sightings only to the attributes that have the IDS flag set.

ATM unless I am mistaken, to do that I have to fetch the attributes first to check their flags, and then push sightings of the IDS=true ones. This not very convenient if I wish to push several sightings at once.

My use case is involves he IDS flag but others may have a use to filter on other things I don't know, so in the end the request we could send could look like this:
```
{"values":["teamliquid.net", "173.231.136.216"], "filters":["ids":true]}
```

**Comment by mokaddem** [comment]
Hey!
Thanks for the very nice example and the cool idea!
I Pushed the feature on `develop`.
You should be able to do something like this:
```json
{
    "values": ["teamliquid.net"],
    "filters": {
        "to_ids": 1,
        "tags": ["PAP:RED"]
    }
}
```
Where `filters` takes most parameters exposed in `/attributes/restSearch`
