### ISSUE TITLE
CSV export broken in v2.4?

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#767]
I've noticed that since upgrading to version 2.4, the CSV export functionality doesn't work as it used to. I'm interested in exporting only the events from the previous day (today's date is 17.12.2015) but if run the following command against my 2.4 instance, it gives me back all the events regardless of the date:

$ curl -H "Authorization: redacted" https://server/events/csv/download/false/false/false/false/ip-dst/true/null/null/1d | head -n2
uuid,event_id,category,type,value,comment,to_ids,date,event_info,event_member_org,event_source_org,event_distribution,event_threat_level_id,event_analysis,event_date
55dc61f9-6040-49db-bb0c-5dd0ac100567,47,Payload delivery,ip-dst,"217.97.216.17","DNS resolution for e-projekt.ns1.internetdsl.pl",1,**20150825**,[IOC]_Invoice 26949 from I - SPI Ltd,Org,Org,2,Low,2,**2015-08-25**

If I try the same against a 2.3 instance, it gives me back the events from the previous day, which is actually what I wanted:

$ curl -H "Authorization: redacted" https://misppriv.circl.lu/events/csv/download/false/false/false/false/ip-dst/true/null/null/1d | head -n2 
uuid,event_id,category,type,value,comment,to_ids,date,event_info,event_member_org,event_source_org,event_distribution,event_threat_level_id,event_analysis,event_date
5671846e-707c-4c3c-825c-d0b8950d210b,2701,Network activity,ip-dst,"192.254.189.98","C&C",1,**20151216**,"TeslaCrypt - new infection vector (macro in .doc)",,,All communities,Low,Initial,**2015-12-16**

Also the Analysis and Distribution fields got replaced by numbers in version 2.4.

**Comment by iglocska** [comment]
It's not very intuitive, but the last field depends on the publish date,
not the date field of the event, which is a bit counter intuitive. The from
and to fields restrict on event date. The idea behind this was that a
freshly updated event should be just as relevant as a new event for exports
of the past n days / hours etc.

We need to 1. document this better or/and 2. change the API in the future
so that we can narrow down both dates in the same way.

**Comment by advancedeng** [comment]
I can see as well that the response time for exporting CSVs in 2.4 is quite different from the one in 2.3 for some reason.

**Comment by iglocska** [comment]
I've just pushed a patch that should change this. Tested it on our live
server and the performance now is around 12 seconds for 300k attributes :)

Let me know if this doesn't fix it for you!

**Comment by advancedeng** [comment]
Still got lots of problems (export time and csv itself) when exporting a CSV with includeContext enabled. I think we had the same problems in 2.3 and they were fixed at some point.

**Comment by iglocska** [comment]
Ah ok, so it's includeContext that's causing it? Probably a fix that didn't
get ported to 2.4, will have a look today during the day. Will let you know
here once it's fixed!

**Comment by Rafiot** [comment]
Fixed
