### ISSUE TITLE
Are there attributes export include decaying score ?

### ISSUE THREAD

**Issue by woodonggyu** [MISP/MISP#7670]
I tried to found these function but i didn't found.

I would like to export attributes include decaying score when export event info.
The attributes to which Decaying Score is applied was not found on DB.

Are there currently related features?

**Comment by mokaddem** [comment]
Hey,
If you want to export attribute and include the computed decaying score, you can use the following parameters:
```json
{
    "includeDecayScore": 1
}
```
You can find more information about the feature and accepted parameters [here](https://www.misp-project.org/misp-training/a.5-bis-decaying-indicators-light-version.pdf)
