### ISSUE TITLE
MISP-UI shows "An Internal Error Has Occurred" after a fresh installation

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7680]
### Work environment

| Questions                 | Answers
|----------------------|--------------------
| Type of issue           | Support
| OS version (server) | Ubuntu
| OS version (client)  | 18.04 LTS
| PHP version           | 7.4
| MISP version / git hash | Latest version downloadable from MISP repository
| Browser                 | Chrome/IE/Firefox

### Support Questions

Issue: Fresh MISP install 2.4 , UI sows internal server error.

Screenshot 1: from UI

![MicrosoftTeams-image](https://user-images.githubusercontent.com/54234520/130398373-73190550-5abd-40f2-83f7-b97027df2337.png)

Screenshot 2: /var/www/MISP/app/tmp/error.log

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/54234520/130398437-96fb47b7-cde8-4eed-9845-0281c9d7dc13.png)

Screenshot 3: /var/log/apache2/misp.local_error.log  

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/54234520/130398489-a6e3e92a-92e9-4eb9-8256-30a6787ad290.png)

Request support to understand how to resolve the issue of "An internal error has occurred"

Thanks

**Comment by adulau** [comment]
It seems Resque is not installed on your system.

**Comment by righel** [comment]
Hello @War10ck3,
Try running composer to install missing php dependencies:
`/var/www/MISP/app/composer.phar install`

**Comment by SteveClement** [comment]
Closing due to inactvity.
