### ISSUE TITLE
Php installation error during new installation

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7681]
### Work environment

| Questions                 | Answers
|----------------------|--------------------
| Type of issue           | Support
| OS version (server) | Ubuntu
| OS version (client)  | 18.04 LTS
| PHP version           | 7.4
| MISP version / git hash | Latest version downloadable from MISP repository
| Browser                 | Chrome/IE/Firefox

### Support Questions

I am attempting a new MISP deployment and am unable to install the PHP repo. I also attempted to install it manually using install.sh during the MISP installation process, but I received a gpg error. How can I troubleshoot this?

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/54234520/130399304-8017f96d-6885-47ef-9b44-efef8ab4feb2.png)

Request support to resolve this issue.

Thanks

**Comment by SteveClement** [comment]
These are transitional errors and can happen if the ubuntu side is "flakey".
