### ISSUE TITLE
Event reports generating - extremely long run

### ISSUE THREAD

**Issue by lu-chi** [MISP/MISP#7698]
The "Generate event from event" function takes a very long time to generate report based on relatively small event (a little amount of attributes) blocking/freezing other MISP activities.

**Comment by mokaddem** [comment]
Hey,
Would you mind sharing an event that generates this behavior in the MISP format?
Thanks!

**Comment by lu-chi** [comment]
Hi - thanks for reaching out that quickly. Unfortunately I can't give you the details but it happens every time I am either adding any new event or generating the report out these that already exist - regardless of amount of attributes.
I was just wondering if that might be somehow related to the correlations or maybe this is something else and if it's I basically should expect (observable by anyone else?).

**Comment by mokaddem** [comment]
Dear,
I think I managed to reproduce your issue.
My guess is that you tried to generate the report from the event without using the template for filtering presented by default on the UI (thus fetching much more data than you should).
Now (starting from https://github.com/MISP/MISP/commit/08986712e131bdfef9a6cd32d01148e480b290fa) empty filtering rules are ignored.
Could you please report back when you update?
Thanks for your help!
