### ISSUE TITLE
Fetch feed doesn't work (getaddrinfo failed: Name or service not known)

### ISSUE THREAD

**Issue by lightman63** [MISP/MISP#7699]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat
| OS version (client)       | 8.2
| PHP version               | 7.4
| MISP version / git hash   | 2.4.148
| Browser                   | Chrome

Behind a proxy to go to Internet.

### Support Questions
Fetch feed doesn't work (getaddrinfo failed: Name or service not known).

### Logs, screenshots, configuration dump, ...

![fetch1](https://user-images.githubusercontent.com/61386677/130936714-fda49228-adfc-4fea-87db-11849c91cf05.png)

cat /var/www/MISP/app/tmp/logs/error.log

![fetch2](https://user-images.githubusercontent.com/61386677/130937232-b78d2444-1ec5-412d-96f8-7ed0e56f199b.png)

Test with curl with root:

curl https://www.circl.lu/doc/misp/feed-osint/manifest.json -> Ok

Test with curl with apache user:

sudo -H -u apache curl https://www.circl.lu/doc/misp/feed-osint/manifest.json -> Ok

Proxy configured and working on MISP GUI.

SeLinux is disabled.

Thanks for your help.

**Comment by adulau** [comment]
Looking at the error from your screenshot, it's clearly a DNS resolution issue. Are you sure that the Apache where PHP is running is able to resolve names? Did you check the resolv.conf or the current resolver?

**Comment by lightman63** [comment]
If the following curl command works with the apache user running, I think the resolv is ok, no ?
sudo -H -u apache curl https://www.circl.lu/doc/misp/feed-osint/manifest.json

**Comment by lightman63** [comment]
Issue resolved.
The proxy configuration on MISP doesn't need schema.
Example : http://proxy.mycompany doesn't work. You must have proxy.mycompany.
