### ISSUE TITLE
Question...Using pymisp to get returned data into MISP?

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#770]
Still learning python... if I have data that I have already normalized, i.e. I can take the data returned from my function and 'curl' it into MISP.  But I really want to do it automatically using pymisp but I'm new to python and have no idea where to start --

This is the end of the program with the data I've normalized, I can take what's returned from print json.dumps(data) and 'curl' this into MISP.  My question is I have no idea where to go from here if I want import pymisp and add the results of the def process_item(self, item, spider) function through pymisp how do I do this?  I know I need post, request, add_event etc.  but how do I call api.py, etc.  

```
import scrapy
from scrapy.http import Request
import requests 
import json
import jsonpickle
from collections import defaultdict
from hybridanalysis.items import HybridAnalysis
from pymisp import PyMISP
from keys import misp_url, misp_key


class HybridanalysisPipeline(object):
        def process_item(self, item, spider):
            data = {}
            data['Event'] = dict(item)
            attributes = data["Event"]["Attribute"]
            data["Event"]["Attribute"] = []
            for attribute in attributes:
             for value in attribute["value"]:
                 new_attr = attribute.copy()
                new_attr["value"] = value
                print "value added to new_attr"
                data["Event"]["Attribute"].append(new_attr)
                print type(data["Event"]["Attribute"])
        print json.dumps(data)
```

**Comment by Rafiot** [comment]
I'm not sure to understand the question, but in order to help you understanding the code, I'd recommend you to look at this module: `https://github.com/Rafiot/viper/blob/master/modules/misp.py`

And especially the add function that uses PyMISP and normalize the attributes to add.

If you look for a shorter example, this one will also be helpful: `https://github.com/CIRCL/PyMISP/blob/master/examples/create_events.py`

And in order to be able to get this script to run, you need to install the module:
`pip install pymisp` or in the directory where you cloned the repository: `python setup.py install`

**Comment by mathurin68** [comment]
Yeah, I think I'm making this way more complicated than it needs to be but all the examples look like they are referring to command line(argparse).  I've already got the data normalized, in the right json form/structure and I can curl it to misp;  I just can't seem to get a request post method to work 


    class HybridanalysisPipeline(object):
            def process_item(self, item, spider):
                data = {}
                data['Event'] = dict(item)
                attributes = data["Event"]["Attribute"]
                data["Event"]["Attribute"] = []
                for attribute in attributes:
                 for value in attribute["value"]:
                     new_attr = attribute.copy()
                     new_attr["value"] = value
                     data["Event"]["Attribute"].append(new_attr)
                    eventdata =  json.dumps(data)
           yield requests(url, method='POST', body=eventdata, headers={"Accept": "application/json","Content-Type":"application/json","Authorization": "RL1R1mTH6A6EKQNgfGJazywetMCjPCpbnr2pOW6S"})

**Comment by mathurin68** [comment]
Can I get a hint?  data does the right information in the right form but I don't understand how to pass it to another function that posts it to misp - 
    import json
    import jsonpickle
    from collections import defaultdict
    from hybridanalysis.items import HybridAnalysis
    from pymisp import PyMISP
    from keys import misp_url, misp_key



    def init(url, key):
        return PyMISP(url, key, False, 'json')

    class HybridanalysisPipeline(object):
	    def process_item(self, item, spider):
		    data = {}
		    data['Event'] = dict(item)
		    attributes = data["Event"]["Attribute"]
				    new_attr = attribute.copy()
				    new_attr["value"] = value
				    data["Event"]["Attribute"].append(new_attr)
				    print type(data["Event"]["Attribute"])
				    print data
				    print "*********************************************************************************************************"
				yield data

    def add_event(self):
		    print "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
		    misp = init(misp_url, misp_key)
		    event = data 
		    print event
		    print type(event)
		    event = misp.add_event(event)
		    print "This is eventjson"
		    print event.json()

**Comment by Rafiot** [comment]
Yeah, the complexity of creating a valid json object is hidden by the API.
To help you, I'll need a non-working json object you try to push (`eventdata` in your case) and if you can dump the error message you receive from the server and the logerror, that would be very helpful.

Also, if you're not already doing it, please use MISP 2.4

**Comment by mathurin68** [comment]
If you could help me that would be the best gift I could get this holiday season!  (Keep in mind I'm a total novice and am probably just doing something whacky, please feel free to tap out anytime). 

Upgraded MISP to 2.4; I'm not really seeing any errors, I worked through all the ssl errors(fixed with verify=False), etc.  I tailed all the logs in app/tmp and didn't see any changes.  I thought the json object i was getting from my code ('scrapy) was correct but maybe it's not and is missing the translation somewhere; when I test the type it does come back as string which I though was ok.  

In scrapy I am using this spider(attached in spider_pipeline.txt) to scrape a page on hybridanalysis and then pull items.json. 
[[{"info": "HybridAnalysis", "orgc": "Malware", "analysis": 0, "Attribute": [{"category": "Network activity", "type": "ip-dst", "distribution": "3", "to-ids": true, "value": ["50.87.227.239"]}, {"category": "Network activity", "type": "domain", "distribution": "3", "to-ids": true, "value": []}, {"category": "Payload delivery", "type": "md5", "distribution": "3", "to-ids": true, "value": ["f0eeaa8a8f7c2cde748e07932c938c86"]}], "date": "2015-12-20 12:10", "distribution": 0, "threat_level_id": "1"}]

But it's not in the right format, as far as attributes etc are concerned so I have to send it to pipelines(bottom of spider_pipelines.txt ) to structure and because there can be multiple attributes and each attribute has to be it's own 'object'.  

spider_pipelines.txt contains both the spider and pipelines.  

Thank you so much for your help or any hints you can give me, I've been working on this for awhile and at a loss where to go from here.

**Comment by Rafiot** [comment]
A few more things then on the use of the API
* there is now a debug switch in the API: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L92 so you can do: `PyMISP(url, key, False, 'json', True)` and get a full dump of everything you send and receive
* Use `_prepare_full_event` to initialise the event object you want to send (it will make sure your new event has the necessary fields) https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L267
* Use `_prepare_full_attribute` to add an attribute to the event you just created (same, it will help you make sure you're trying to push a valid event) https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L284
* do not use requests directly, `add_event` to create a new event or `update_event` to update en event https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L215 https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L231

**Comment by mathurin68** [comment]
Thanks Rafiot, I've been reading up a little on modules and importing functions; vacation starts tomorrow and this is my main goal!!!

I will try and have something together for you to critique by the end of the day tomorrow!

**Comment by mathurin68** [comment]
Ugh I just don't get how I'm supposed to pass the data to the parameters of the functions in pymisp.  

For example, this is the class that gives me data that certainly looks correct but I can't get it into misp...

    class HybridanalysisPipeline(object):
	def process_item(self, item, spider):
		global data
		data = {}
		data['Event'] = dict(item)
		attributes = data["Event"]["Attribute"]
		data["Event"]["Attribute"] = []
		print data
		for attribute in attributes:
			for value in attribute["value"]:
				new_attr = attribute.copy()
				new_attr["value"] = value
				data["Event"]["Attribute"].append(new_attr)
    #			print type(data["Event"]["Attribute"])
    #			eventdata = json.dumps(data)
    #			print type(eventdata)
				print "*********************************************************************************************************"
				print data

gives me this data - 
{'Event': {'info': 'HybridAnalysis', 'orgc': 'Malware', 'analysis': 0, 'Attribute': [{'category': 'Network activity', 'type': 'ip-dst', 'distribution': '3', 'to-ids': True, 'value': u'50.87.227.239'}, {'category': 'Payload delivery', 'type': 'md5', 'distribution': '3', 'to-ids': True, 'value': u'f0eeaa8a8f7c2cde748e07932c938c86'}], 'date': '2015-12-25 19:49', 'distribution': 0, 'threat_level_id': '1'}}

Lol, I just don't get how to get the data(or any data) above to match the parameters of the prepare_full_event function, to initialize it?  I mean I've used pymisp from the command line but how do you pass the data if it's not from the command line? 

    def _prepare_full_event(self, distribution, threat_level_id, analysis, info, date=None, published=False):
            to_return = {'Event': {}}

Appreciate any hints you could give me, just really need to take a break for a couple of hours.  Probably just something simple and just basic python but learning this on my own is tough.

**Comment by Rafiot** [comment]
Sorry for the late answer. Did you continue working on it?

**Comment by mathurin68** [comment]
Got it working, ugh sorry.  I am a slooooow coder.  Anyone wants to know what we did I'm happy to share.

**Comment by Rafiot** [comment]
Sure, can you please share your code, please? The easiest way is a pull request in PyMISP.

**Comment by mathurin68** [comment]
Here is the scrapy code I used to pull from threatexpert.com and upload to our MISP instance. --

So I had to pump everything to the pipeline in scrapy to modify the data once I pulled it from the website.  The pipeline worked like this - 

```
 `class ThreatExpertPipeline(object):
    def process_item(self, item, spider):
    data = {}
    data['Event'] = dict(item)
    print data
    print "$$$$$$$"
    attributes = data["Event"]["Attribute"]
    data["Event"]["Attribute"] = []
    for attribute in attributes:
        for value in attribute["value"]:
                if value == " ":
                    pass
                else:
                    new_attr = attribute.copy()
                    new_attr["value"] = value
                    data["Event"]["Attribute"].append(new_attr)

    print type(data)
    eventdata = json.dumps(data)
    print eventdata
    return requests.post(url, headers=headers, data=eventdata, verify=False)`
```

And then parsing the data from threatexpert we had to manipulate it a little even before it went to the pipleine - 

```
`def parse_items(self, response):       
    self.log("Hi, this is an item page! %s" % response.url)
    item = ThreatExpert()
    item["date"] = now.strftime("%Y-%m-%d")
    item["threat_level_id"] = "1"
    item["info"] = "ThreatExpert"
    item["analysis"] = 0
    item["distribution"] = 3
    item['published'] = True
    item["orgc"] = "Malware"
    item["Attribute"] = []
    item["Attribute"].append({'type': "md5"})
    item["Attribute"][0]["category"] ="Payload delivery"
    item["Attribute"][0]["to-ids"] = True
    item["Attribute"][0]["distribution"] = "3"
    item['Attribute'][0]['published'] = True
    item["Attribute"][0]['value']= response.xpath('//html/body/ul[1]/ul/ul/li[1]/text()').re(r"File MD5: 0x([\w, ]+)")
    item["Attribute"].append({'type': "domain"})
    item["Attribute"][1]["category"] ="Network activity"
    item["Attribute"][1]["to-ids"] = True
    item["Attribute"][1]["distribution"] = "3"
    item['Attribute'][1]['published'] = True
    item["Attribute"][1]['value'] = response.xpath('//*[contains(text(), "The following Host Names were requested from a host database:")]/following-sibling::ul/li/text()').extract()`
```

Probably a lot more work than I needed to do but I did get a lot better at python!

We are using MISP as our IOC database at work by the way!

**Comment by Rafiot** [comment]
Great! 
I'll look at the code and see how we can implement it in the module

**Comment by Rafiot** [comment]
Sorry, I totally forgot about it.

@mathurin68 are you still using this code? Or did you update it? Also, if I add it to PyMISP, I'll need a few sample files, can you send me some?

Thank you very much
