### ISSUE TITLE
Push not updating all attributes of Event

### ISSUE THREAD

**Issue by qbolbk59** [MISP/MISP#7703]
We have two MISP instances running, one on-prem while the other is on Cloud. I have created a sync user on Cloud MISP and use that user from on-prem misp to push events to cloud MISP. 

I can see all events are properly pushed except one event where only half of the attributes are being pushed. It would have been understandable if the event is not pushed completely so that i can check the distribution. But in this case, only half of the attributes are being pushed.

I perform the sync using cron job. Couldn't find anything relevant in the logs as well. 

Can someone help me where i can find the reason why the event is getting synced partially ?

**Comment by mokaddem** [comment]
Hello,
Have you checked the logs of the two instances?
Also, do you have some synchronization filtering rules in place that would prevent the missing attributes to flow?
I guess the distribution of the missing attributes is the same as the ones that flowed?
Thanks

**Comment by qbolbk59** [comment]
@mokaddem :  Thanks for responding. 
Yes, i checked the logs (error, diagnostics..) but couldn't find any issue related to the jobs. There are no filters added in the sync jobs. Everything from the on-prem MISP to be synced and updated on the cloud MISP as it is. The distribution is also the same.
