### ISSUE TITLE
deleted attributes logs

### ISSUE THREAD

**Issue by Yaels17** [MISP/MISP#7711]
I need to pull all the attributes I deleted via the API.

I can find the log itself in MISP platform under "logs", but cant find an explanation on where I can pull the deleted attributes via the API.

what query do I need to write to find where all the deleted attribute logs are stored?

thanks!

**Comment by righel** [comment]
Hello @Yaels17,
You can get this data via the API with the following request:
```
curl --location --request POST 'https://[YOUR_MISP_HOST]/admin/logs' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: YOUR_AUTH_TOKEN' \
--data-raw '{
    "limit": 10,
    "page": 1,
    "action": "delete",
    "model": "Attribute",
    "created": ["2021-01-01 00:00:00+02", "2021-09-02 00:00:00+02"]
}'
```

You can use pagination and/org filter by date intervals if required.
I will update the API docs for this endpoint soon.

Let me know if that helps.

**Comment by righel** [comment]
You can now find information regarding this endpoint and available filters in here:
https://www.misp-project.org/documentation/openapi.html#operation/getLogs
