### ISSUE TITLE
API Key vs Auth Key

### ISSUE THREAD

**Issue by maverickvn360** [MISP/MISP#7717]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Support Questions
I just want to know the difference between Auth key under the user profile (edit user) and API keys which the user can make/reset (My profile)..

**Comment by righel** [comment]
Hello @maverickvn360
The are two API auth keys management mechanisms in MISP, the default basic and advanced. 
The auth key you see under `/users/edit` is the basic auth key and only works if `Security.advanced_authkeys` is set to `false`. 
The list of auth keys you can make/reset under `/users/view/me` (My profile) require `Security.advanced_authkeys` set to `true`. 
The underlying authentication code is the same in both cases, but the advanced mode provides extra key management features via the UI and API.

Let me know if that helps.

**Comment by maverickvn360** [comment]
Thanks @righel ,

But I couldn't understand why two authentication mechanisms are needed, and what's the difference between them?

**Comment by righel** [comment]
The `advanced_authkeys` is optional, but recommended, keep in mind these are mutually exclusive, only one is active at a given time. 
A sample use-case would be having different auth_keys depending on the role/actions they are used for, a script using MISP API to export data to another system could use a read-only auth_key, thus reducing it's privileges to a bare minimum.

**Comment by maverickvn360** [comment]
Got it, Do we have a page where we can configure access for each API key? And lastly, do we have any supporting documentation?

Thanks 👍

**Comment by righel** [comment]
Yes, you can browse the existing auth keys in `/auth_keys/index`.
There's only a small description about it on the release notes of the version that included this feature:
https://www.misp-project.org/2020/12/16/MISP.2.4.135.released.html

**Comment by maverickvn360** [comment]
Thanks a lot!

Closing!
