### ISSUE TITLE
Update 2.3 to 2.4 Error

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#772]
Hello all,

I followed the instructions [1] to update a MISP instance 2.3.178 to 2.4. Unfortunately, an error ("SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null") occurs when I launch the final step "Upgrade to 2.4 " (Administration -> Administrative Tools -> Upgrade to 2.4).

The Strack trace is the following:
```
2015-12-18 23:36:02 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null
Request URL: /servers/upgrade2324
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(460): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(426): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1012): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1928): DboSource->create(Object(Job), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/AppController.php(516): Model->save(Array)
#6 [internal function]: AppController->upgrade2324()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```
Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
Weird, did you run the SQL script first (upgrade_24.sql)?

**Comment by devnull-** [comment]
Yes. I launched the script "upgrade_24.sql"

**Comment by geudrik** [comment]
By 'launched' do you mean you ran the command `mysql -uuser -hdbhost -p misp_database < upgrade_2.4.sql` per the upgrade instructions [here](https://github.com/MISP/MISP/blob/2.4/INSTALL/UPGRADE.txt)?

**Comment by devnull-** [comment]
@geudrik Yes. I followed the upgrade instructions here [1]

[1]: https://github.com/MISP/MISP/blob/2.4/INSTALL/UPGRADE.txt

**Comment by iglocska** [comment]
OK, let's try to debug this. 

First of all, you should get a series of log entries during the upgrade procedure in your audit log - what is the last line before the failure? 

Basically MISP executes a series of SQL queries and they all go through the same code path, so it's difficult to pinpoint it from the stack trace. However, knowing the last successfully executed query should tell us more.

**Comment by devnull-** [comment]
Hello all,

I (re)tried today to update my MISP instance to 2.4 and the error has disappear. 

I didn't check or review the modifications related to "upgrade_2.4.sql" but the issue appears to be fixed :)

Thank you and have nice evening.
