### ISSUE TITLE
Jobs page with non completed publish_event, push, pull jobs

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#774]
Not sure if this is a bug but the jobs page showed a lot of non completed publish_event, push, pull jobs. Is it this normal?

**Comment by iglocska** [comment]
Hmph, was there a restart of the server? All the workers are dead.

**Comment by iglocska** [comment]
Looks like it's on both instances - was redis flushed at some point?

**Comment by adulau** [comment]
It was a recent push/pull and the Redis instances were running without being flushed. Not sure if this is due to a never complete jobs (timeout?) or a simple issue with the logging.

**Comment by iglocska** [comment]
It was not a logging issue, the jobs were gone from the queue and the workers were dead on both instances, so something's definitely fishy. Going through the worker logs now.

**Comment by iglocska** [comment]
It looks like MISP lost connection to Redis at 11:07

**Comment by adulau** [comment]
Indeed but that should not matter as the jobs were started after.

2015-12-19 15:41:12  	2015-12-19 15:41:12 

Now they seem completed. What is the action performed to make them completed? and how to ensure that they were running? Maybe keeping track of the return code of a job would be nice for debugging or maybe there are other way to check the output of a job.

**Comment by adulau** [comment]
Maybe the best would be link the logs between Job and audit log via the job id?

**Comment by iglocska** [comment]
Yeah that's a good idea. I'll look into adding some connection between log entries and the jobs themselves. 

I've just restarted the workers and they picked up the waiting scheduled jobs.

**Comment by adulau** [comment]
Cool. Thank you.
