### ISSUE TITLE
An odd request:  access via ssh tunnel.

### ISSUE THREAD

**Issue by DigiAngel** [MISP/MISP#7743]
So usually I'd fill out all the spiffy info, but in this case it's not super relevant.  My situation:

Host machine is 192.168.1.14
SSH tunneled from remote site, so redirecting port 443 to 192.168.1.14
IP on the browser is and has to be 127.0.0.1

I can get to the initial login, but after that nothing works.  Is there a way to accomplish this?  Thanks.

**Comment by mokaddem** [comment]
Would setting the MISP `baseurl` to the correct value help?
You can do it from the web interface or the CLI:
``` MISP/app/Console/cake Baseurl [baseurl]```

**Comment by DigiAngel** [comment]
And that's my question.  Here's what I have so far:
~~~
MISP.baseurl == https://<machinename>
MISP.external_baseurl == <blank>
~~~

So what would I set these to?  Internally https://machinename works great...I wouldn't want to break that.  Thank you.

**Comment by mokaddem** [comment]
`external_baseurl` should be the URL that other MISP instance should use to contact your MISP instance. If this is not relevant for your setup, you can leave it blank.
What do you mean by "nothing works"? Do you have log entries? Does the redirect fails?
Thanks

**Comment by DigiAngel** [comment]
I'll get some logs soon...need to be off net in order to test and that hasn't happened yet ( thanks covid :( )

**Comment by DigiAngel** [comment]
Ok...had time to look...and as of now, when I go to:
~~~
https://127.0.0.1/
~~~
I get the login page.  As soon as I enter creds and go forward I get:
~~~
https://<machinename>/
~~~
and the browser is unable to resolve.

**Comment by samitainio** [comment]
@DigiAngel It seems from the information you have provided that the `<machinename>` is something that your client side device doesn't know how to resolve to an IP-address (127.0.0.1 in this case) so you could try to edit the `/etc/hosts` file on that client side device and add a line:

`127.0.0.1 <machinename>`

**Comment by DigiAngel** [comment]
Thanks...adding to the hosts file (windows no less) fixed this up...appreciate it!
