### ISSUE TITLE
Server sync filters stopped working

### ISSUE THREAD

**Issue by rbnor** [MISP/MISP#7749]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

ubuntu, using coolacid/misp-docker:core-latest so should be the latest misp. 

### Expected behavior
Filters for syncing towards other servers should work just as they did the last months

### Actual behavior
filters does not work anymore and the amount of indicators have gone up 30x. we did no changes what so ever at our local misp that week, except for a restart. 

### Steps to reproduce the behavior
Im not sure as it appeared arond 3rd of september, totally unexpected. 

### Logs, screenshots, configuration dump, ...
Im aware this is a reallys shit bugreport but im not sure where the error lies, if its even with our server or if misp changed the way the filters works or something so not sure what logs to post here that would make sense.

**Comment by JakubOnderka** [comment]
Hello, can you please provide more info? What filters do you use? And do you use filters for pulling or pushing?

**Comment by rbnor** [comment]
Yes for sure, ill try to be as helpfull as possible of course! 

We just used the filters for pulling, we have two server sync configs for the misp we are syncing from, one for certain orgs and one for certain threat actors and tags. Suddenly it seemed to ignore that and just sync everything without us performing any actions that would indicate such behavior. 

The sync does seem to work again now, it stopped pulling everything during the weekend as it probably just broke down and the db ran out of ram etc, so seems to just temporarily have ignored the sync configs. I have no idea how to reproduce it. So i guess the odds of finding out what really happened is kind of low.. Anyways if you have the slightest idea about what might have happened please do share.

**Comment by rbnor** [comment]
Never figured out what went wrong.
