### ISSUE TITLE
Which permission is required for user's to view event from another instance?

### ISSUE THREAD

**Issue by Tommi852** [MISP/MISP#7763]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server&client)       | Ubuntu 18.04.4 LTS x86_64
| MISP version / git hash   | v2.4.148 (020f96b2e17f16fd12a2ba9ed27174c38e347cd3) 
| Browser                   | Firefox

### Support Questions
Which permission or right is required to allow users to see correlated event from another internal MISP server?

#### The problem
Currently I can see the "Feed hits" correlation on attributes when I'm using admin account and I can open it in the event preview at "/servers/previewEvent/". 
![image](https://user-images.githubusercontent.com/31437167/134015948-7b32a4ee-8c7c-4338-bfdb-28363646c2d5.png)

But when I use normal user I can see that it has "Feed hits", but the indicator is not a hyperlink to the event preview. 
![image](https://user-images.githubusercontent.com/31437167/134015873-d3ed38c7-5685-4886-a89b-026efb126cd1.png)

Which permission does the user need, so they can view the event on the other server?

The related server window does appear as hyperlink, but it gives error:
"You do not have permission to use this functionality.
Error: You don't have permission to access '/servers/previewIndex/4'."

#### Additional note:
I'm trying to use one server as a public facing server with all the feeds being collected there and then using another private MISP instance as just a investigation platform wihtout the feed events.
I planned on using caching from the public facing server to correlate events between the instances. This way I wouldn't waste space by having all the feed events also on the private instance, but I could still correlate the events to see if some of the attributes have been seen on the public instance/feeds. This is where the problem comes. Normal user's can't view the events on the other instance.
If this is not correct way to do it or this is not possible, then can you please point me to right direction. Thank you. :)

**Comment by Tommi852** [comment]
Is the permission or function only limited to admin accounts?
I checked all additional rights for a non-admin user and they still didn't get the feed hits link, but when I added site admin right, then they could see the link and could check events on the other instance.

If it's not currently possible to view events on another internal instance as user at the moment, are there any plans to implement such access in the future?

**Comment by mokaddem** [comment]
Indeed, contrary to feeds, viewing servers date is restricted to site admin accounts only.
As far as I know, there is not plans to implement this feature.
You can still open a new feature request so that you we keep a trace of it and you can track when it will be implemented.
Thanks!
