### ISSUE TITLE
MISP Workers dead

### ISSUE THREAD

**Issue by redbiker-svg** [MISP/MISP#7764]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | MacOS
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.148
| Browser                   | Chrome, FF

### Support Questions

I updated my MISP instance to 2.4.148 last week via the MISP GUI and all went okay (well, appeared to have) 

Logged in today and couldn't view my Jobs page as it returned an "Internal Error" page. Checked other settings and found that all workers were dead and no way to restart / add a new worker

Based on the page, have checked MISP settings for manage_workers and this is set to TRUE.

What am I missing now and what's broken?

### Logs, screenshots, configuration dump, ...

Workers page 

![image](https://user-images.githubusercontent.com/62763192/134166978-16eab066-bea2-4e6f-b508-7ff15546370f.png)

MISP Settings

![image](https://user-images.githubusercontent.com/62763192/134167116-724b583c-d6af-40fb-bbd0-ac19540d36b2.png)

**Comment by righel** [comment]
Hello @redbiker-svg 

You can try the following the things:

1. Restart workers and check again:
`/var/www/MISP/app/Console/cake Admin restartWorkers`
2. Check is up and running:
`service redis status`
3. Check for relevant information in the following log files:
```
/var/www/MISP/app/tmp/logs/error.log
/var/www/MISP/app/tmp/logs/resque-worker-error.log
/var/www/MISP/app/tmp/logs/resque-scheduler-error.log
```
4. Check if permissions were not changed in /var/www/MISP dir/subdirs, if so, re-run these:
```
  sudo chown -R www-data:www-data /var/www/MISP
  sudo chmod -R 750 /var/www/MISP
  sudo chmod -R g+ws /var/www/MISP/app/tmp
  sudo chmod -R g+ws /var/www/MISP/app/files
  sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp
  /var/www/MISP/app/Console/cake Admin restartWorkers # restart workers
```

Let me know if that helps.

**Comment by redbiker-svg** [comment]
Hi @righel 

Thanks for the inputs. 

1. Restarting workers returns the below error 

![image](https://user-images.githubusercontent.com/62763192/134393808-64f5c093-d870-42e3-8518-63e305632ce4.png)


2. Redis is running

![image](https://user-images.githubusercontent.com/62763192/134393633-89088c54-8463-4973-aa9f-9a7c4d88a6d9.png)


3. I see a lot of connection refused errors from 21 and then a all working on 22nd, but back to the same connection refused 

**Error.log**

![image](https://user-images.githubusercontent.com/62763192/134393925-28cd3c0c-615c-4bf2-ab69-18268c30de7c.png)

![image](https://user-images.githubusercontent.com/62763192/134393899-558d7c36-5922-42f2-abb1-e379a4e082d0.png)

![image](https://user-images.githubusercontent.com/62763192/134393876-efbda871-0241-422b-b9e5-7afc9959bb48.png)

**Worker-error:**

![image](https://user-images.githubusercontent.com/62763192/134393721-967b22e7-ff68-4261-ade0-1454f83524b7.png)

**Scheduler error**

![image](https://user-images.githubusercontent.com/62763192/134393653-6bf8df9c-6e6f-4698-b5c0-da5ba6a5f2d0.png)

4. There were no changes, but still ran these and restarted workers to no avail

![image](https://user-images.githubusercontent.com/62763192/134393615-a6bb2c2b-297a-4737-9c16-4a98b85794b0.png)

Moreover, I've checked the config file in `/var/www/MISP/app/Plugin/CakeResque/Config` and appears to be okay?

![image](https://user-images.githubusercontent.com/62763192/134393432-9038cd6c-0eba-429d-ae2b-b13da619010f.png)

**Comment by righel** [comment]
Could you please check the redis settings in the main config file?
Check the following settings:
```
    # /var/www/MISP/app/Config/config.php
    'redis_host' => '127.0.0.1',
    'redis_port' => 6379,
    'redis_database' => 13,
    'redis_password' => '',
```

**Comment by redbiker-svg** [comment]
Hi @righel 

Settings in config as below. I tried accessing MISP & re-tried the above steps, no joy this time around either

![image](https://user-images.githubusercontent.com/62763192/135258893-eaaaa506-1735-4c2c-9e5e-1c7c81860f80.png)

**Comment by redbiker-svg** [comment]
Hi @righel sorry to bother. Do you know what checks / fixes to apply next? I'm literally not receiving any IOC's from any feeds due to this issue impacting production system

**Comment by righel** [comment]
Hello @redbiker-svg , sorry to hear the problem persists.
* If you run `redis-cli` on the MISP instance host are you able to connect?
* Does your host resolves localhost to 127.0.0.1 correctly? check:
`host localhost`
* try changing `/var/www/MISP/app/Plugin/CakeResque/Config/config.php` `localhost`-> `127.0.0.1` and try again.
* check if the the firewall is enabled and allows this connection:
 `ufw status`
* check network traffic when you trigger a redis connection from MISP:
`tcpdump -n -i lo port 6379`
* restart redis service.

Hope this helps.

**Comment by redbiker-svg** [comment]
Hi @righel - many thanks for these additional steps. 

I've performed it all, but workers are still dead and feeds are not updated. 

Here's a list of all checks and outcomes:

**Unable to connect to redis-cli**

![image](https://user-images.githubusercontent.com/62763192/135761872-668a28ac-8e09-449f-9818-766f9564779e.png)

**Host does correctly resolve to 127.0.0.1** 

![image](https://user-images.githubusercontent.com/62763192/135761977-6e67d445-37de-48ca-a8bf-5188912eb9b6.png)

**CakeResque config file did have localhost in there, but updated to 127.0.0.1**

![image](https://user-images.githubusercontent.com/62763192/135761952-eddd404c-5074-4c4a-9397-ed91279494b2.png)

**Firewall is inactive**

![image](https://user-images.githubusercontent.com/62763192/135762012-3a8d6a2f-29ea-48bb-aa11-d2cf0ae9742b.png)

**Snapshot of tcpdump** 

![image](https://user-images.githubusercontent.com/62763192/135762018-e6eb6c80-96c1-43ac-89ba-82c933a1f38e.png)

On restarting redis, it does appear to restart, however, checking status the very next seconds shows it failed to restart as it failed to start Advanced key-value store

![image](https://user-images.githubusercontent.com/62763192/135762079-96ccd7f5-de6c-48a1-8464-a2fbd3a26696.png)

Trying to restart workers to check if there's a new error returns the same error as before

![image](https://user-images.githubusercontent.com/62763192/135762115-3c3b36e3-b5d5-42e5-adc7-f9aad7feee61.png)

**Comment by righel** [comment]
Hi @redbiker-svg ,
It seems that you have an issue with your redis installation, I would try to reinstall it or debug it. 
There are some info online about the issue, which can be due to multiple reasons.
Check if you can find more details about the error in the redis log file`/var/log/redis/redis-server.log`.

Check the following also:
https://stackoverflow.com/questions/49670211/failed-to-start-advanced-key-value-store-redis-server-service-control-process-e
https://stackoverflow.com/questions/61726646/redis-wrong-signature-trying-to-load-db-from-file/65258594#65258594

**Comment by righel** [comment]
Closing it for now, feel free to re-open the ticket if you are still having issues.
