### ISSUE TITLE
Undefined index: s_time

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#778]
From time to time I see the following in my logs:

==> resque-scheduler-error.log <==
Notice Error: Undefined index: s_time in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php, line 90]

Notice Error: Undefined index: s_time in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php, line 89]

Notice Error: Undefined index: s_time in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php, line 90]

Notice Error: Undefined index: s_time in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php, line 89]

Notice Error: Undefined index: s_time in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/lib/ResqueScheduler/Worker.php, line 90]

**Comment by iglocska** [comment]
This is weird, that error should be changed by a newer version of php-resque-ex-scheduler. Is this an upgrade of an older MISP installation? Could you check the php-resque-ex version (should be 1.2.4 or newer for the issue to be gone). I'll update the documentations tomorrow to include updating CakeResque and its dependencies.

**Comment by h122015** [comment]
This is an upgrade of an older MISP installation. I already updated CakeResque and the alerts seem now to be gone

**Comment by Rafiot** [comment]
I close the issue then.

Thank you!
