### ISSUE TITLE
MISP cake plugin issue

### ISSUE THREAD

**Issue by ojaschauhan** [MISP/MISP#7781]
Guide says:
Automating certain console tasks

If you would like to automate tasks such as caching feeds or pulling from server instances, you can do it using the following command line tools. Simply execute the given commands via the command line / create cron jobs easily out of them.:
PullAll: MISP/app/Console/cake Server pullAll [user_id] [full|update]
Pull: MISP/app/Console/cake Server pull [user_id] [server_id] [full|update]

But i am getting an error saying no plugin found.

error:
$: :/var/www/MISP/app/Console# ./cake pullAll
Error: Plugin PullAll could not be found.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(227): CakePlugin::path('PullAll')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(549): App::path('Console/Command', 'PullAll')
#2 [internal function]: App::load('PullAllShell')
#3 [internal function]: spl_autoload_call('PullAllShell')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(267): class_exists('PullAllShell')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(213): ShellDispatcher->_getShell('pullAll')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#8 {main}

Any suggestions?

**Comment by ojaschauhan** [comment]
Also having a tough time in creating a scheduled job for pulling feeds. Any help would be appreciated.

**Comment by righel** [comment]
Hello @ojaschauhan ,
The correct syntax for the command is the following:
`./cake Server pullAll [user_id] [full|update]`

You can see all commands usages in here:
https://github.com/MISP/MISP/blob/2.4/app/Model/Server.php#L142

**Comment by ojaschauhan** [comment]
@righel  thanks for that. I am trying to build a automation to fetch feeds at regular internal. Any help with that?
I am not able to see anything for it in automation tasks of MISP

**Comment by righel** [comment]
This one is probably what you are looking for:
`./cake Server fetchFeed [user_id] [feed_id|all|csv|text|misp]`

**Comment by amitxroshan** [comment]
hi @righel @adulau @sfossen 
I tried to fetch events from all my enabled feeds by doing automation through the below command.
`root@misp:/var/www# MISP/app/Console/cake Server pullAll user@admin.com``
I am getting error like Error: User ID do not match an existing user.
What should I try here so that all the events from my enabled feeds can come to my console daily without me clicking manually on fetch all events button.

**Comment by righel** [comment]
@amitxroshan it should be the numeric ID of the user, not the email.
