### ISSUE TITLE
How could I write login failed to syslog file?

### ISSUE THREAD

**Issue by Sue1990** [MISP/MISP#7783]
I only see the login / logout in apache2/error.log file, but the website (Logs) can show login / logout / Failed login (I known it show form database data) .

If I want to write "Failed login" into error.log file , how to configure ?

**Comment by mokaddem** [comment]
A failed login is not consider as an application error. If you want to fetch this info, the best way for you is to use the API to get this data.
Cheers!

**Comment by Sue1990** [comment]
@mokaddem thanks.
