### ISSUE TITLE
MISP issue

### ISSUE THREAD

**Issue by mkamkhan** [MISP/MISP#7785]
Hi everyone,
I installed MISP standalone instance on Ubuntu 20 and I want to integrate it with arcsight SIEM.
I installed the connector on arcsight server. Arcsight connector is successfully communicating with MISP server but no feeds are coming into arcsight threat intelligence fields.
Further what is the purpose of port 6666 on MISP as this port is not connecting and also I go to diagnostic's in MISP and there it says import and export module refuses connection.
Kindly suggest and guide a way around to resolve this issue.

**Comment by mokaddem** [comment]
Hello,
Do you have data in your MISP instance? If you don't, you can enable feeds and fetch them locally at `/feeds/index`.
By default, the MISP-modules app uses the port 6666.
Maybe something went wrong during the instance of the MISP-modules.
