### ISSUE TITLE
Tags on attributes within objects are not exposed via API or JSON

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#7793]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Python
| PHP version               | 7.4
| MISP version / git hash   | 2.4.148

### Expected behavior
Tags attached to attributes which are a member of an object get exposed over the API, too, e.g. in the JSON export or via PyMISP.

### Actual behavior
Tags seem to be only visible in the GUI, both PyMISP and the JSON export of an event do not show the attribute tags.

### Steps to reproduce the behavior
Set tag within an attribute, check API output on that specific event.

### Logs, screenshots, configuration dump, ...
![Bildschirmfoto 2021-09-30 um 15 56 52](https://user-images.githubusercontent.com/2846609/135469319-9d8371ed-1a24-4f1e-b946-a8946ddf1847.png)
![Bildschirmfoto 2021-09-30 um 15 57 42](https://user-images.githubusercontent.com/2846609/135469324-8f8b9b8f-2584-4255-b35b-47b96fa3bc2e.png)

**Comment by Wachizungu** [comment]
probably worth adding evidence / screenshot showing that your tag is configured as 'exportable'

**Comment by 3c7** [comment]
Indeed. Or configure it as such.
