### ISSUE TITLE
News not found

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#780]
In 2.4 branch, if I try to see what's in the News page (Global Actions -> (Any item) -> News) I received the following error:

Not found.
Error: The requested address '/users/news' was not found on this server.

In the logs I see the following:

2015-12-22 12:10:20 Error: [MissingActionException] Action UsersController::news() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'news',
)
Request URL: /users/news
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}

**Comment by iglocska** [comment]
Indeed, the news page was removed, guess a merge brought it back in the menu at least, will remove it from the menu asap.
