### ISSUE TITLE
Sharing Group Distribution in Feeds Unselectable

### ISSUE THREAD

**Issue by Hestat** [MISP/MISP#7807]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  Ubuntu 20.04.3 LTS
| OS version (client)       | N/a
| PHP version               | 7.4.3
| MISP version / git hash   |  v2.4.148 (3822521d2ceeb7dcccaf53ea3052a8a2209f0433) 
| Browser                   | N/a

### Expected behavior
When creating a new feed and choosing Sharing Group option to set which sharing group.

### Actual behavior
When Sharing group is chosen, no option to set which sharing group appears so defaults to Sharing Group 0

### Steps to reproduce the behavior
Try to add new feed with Sharing group Distribution.

### Logs, screenshots, configuration dump, ...
![sharingbug](https://user-images.githubusercontent.com/22892300/136207452-99d85cd4-396c-477c-8da5-07a270e7ebd2.png)

**Comment by righel** [comment]
Hello @Hestat ,
Thanks for reporting, indeed it was a regression introduced by https://github.com/MISP/MISP/pull/7520.
Pushed a [fix](https://github.com/MISP/MISP/commit/4df55d99c8c2c10fc17a038f9ceb06e873e8347c) to the `develop` branch, you may need to hard refresh your browser to get the javascript changes.
Please let me know if that works for you now.

**Comment by Hestat** [comment]
With the update to v2.4.150 (1e930903b27c802df093787ee5674ca33a84340b) the pull down selector has returned.
