### ISSUE TITLE
Upgrade to 2.4 administrative script takes too long

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#781]
Hi all,

Is it normal that the Administration->Administrative tools-> Upgrade to 2.4 scripts takes more than 5 hours to be executed? Just wondering...

Cheers,
Andreas

**Comment by iglocska** [comment]
Sadly yes, I'll look into speeding it up, but right now it's recorrelating
all of the attributes in the db which is pretty slow.

**Comment by advancedeng** [comment]
OK, thanks for thr reply iglocska!

Cheers,
Andreas

**Comment by geudrik** [comment]
Confirming that this takes a painfully long time, but I also totally understand _why_

**Comment by iglocska** [comment]
I have a fix for it locally that reduces the time to about a minute, will
try to push it tonight!

**Comment by iglocska** [comment]
If you've started it already though then it's best if you let it finish.

**Comment by iglocska** [comment]
Just a heads-up this should now be fixed.
