### ISSUE TITLE
Local tags get global upon org-interal sync (Push/Pull)

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#7810]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.4
| MISP version / git hash   | v2.4.148 (52cda9736ce893b39895b9655990dd7a9f7425a8) 
| Browser                   | Firefox

### Expected behavior
Syncing two internal MISP instances, either local tags would not be synced at all, or if synced they should at least be local again. Preferably even this could be choosen in sync-config. 

### Actual behavior
 - Pulling events from instance A to instance B, creates events on instance B with global tags, that have been local on A before
 - Pushing the other way around leads to the same result 

### Steps to reproduce the behavior
 - setup two MISPs for internal sync
 - create an event and attach some global as well as local tags
 - sync this event
 - check global/local state of the tags in the other instance

### Logs, screenshots, configuration dump, ...
![grafik](https://user-images.githubusercontent.com/72734273/136810514-abc0f477-819b-4262-b092-529f6891f4cd.png)

**Comment by JakubOnderka** [comment]
If server A is marked as `internal` in instance, this is I think intentional.

**Comment by marjatech** [comment]
so state-change from `local: 1` on A to `local: 0` on B is intended? 
global tags should only be set by the creator org shouldn't they?
