### ISSUE TITLE
Don't create a config backup with extension other than PHP

### ISSUE THREAD

**Issue by paalbra** [MISP/MISP#7813]
This isn't exactly a feature or bug. Please do fix the report if it should have been reported elsewhere.

**Is your feature request related to a problem? Please describe.**
There is some times created a backup file of `config.php`. This backup is called `config.php.bk`. Even though this file isn't accessible in the webroot, changing extension of php-files could be dangerous. If the file somehow is exposed through the webserver, the webserver would probably serve the file in plain text (not ran as a PHP-file). This will lead to exposed secrets.

This is hypothetical, but it's still a real, potential issue.

**Describe the solution you'd like**
Call the backup file something like `config.backup.php` instead.

**Describe alternatives you've considered**
None

**Additional context**

https://github.com/MISP/MISP/blob/5911e031c4893bcf46360777ed893a70810b8bea/app/Model/Server.php#L2216-L2220

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in `develop` branch.
