### ISSUE TITLE
upgrade_24 script Errors

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#782]
Hi there, 

When the scripts starts running I got these ERRORs:

SYSTEM  	SYSTEM  	2015-12-21 17:24:46  	upgrade_24  	[ERROR] - Detected empty string organisation identifier during the upgrade  	Detected entries in table `jobs` where `org` was blank. This has to be resolved manually! 

SYSTEM  	SYSTEM  	2015-12-21 17:24:45  	upgrade_24  	[ERROR] - Detected empty string organisation identifier during the upgrade  	Detected entries in table `threads` where `org` was blank. This has to be resolved manually! 

SYSTEM  	SYSTEM  	2015-12-21 17:24:45  	upgrade_24  	[ERROR] - Detected empty string organisation identifier during the upgrade  	Detected entries in table `shadow_attributes` where `event_org` was blank. This has to be resolved manually! 

SYSTEM  	SYSTEM  	2015-12-21 17:24:45  	upgrade_24  	Upgrade initiated  	Starting the migration of the database to 2.4 

Any idea?

**Comment by iglocska** [comment]
Interesting, I'll look into what could be causing this when I go through the upgrade scripts tonight / tomorrow.

**Comment by iglocska** [comment]
Guess it will have to be tomorrow, got too caught up with some other bug fixes. For the issues above: 
1. Did you run the upgrade script more than once by any chance?
2. Did you create any new data in MISP after installing 2.4 but before running the upgrade script?

Also, could you run the following mysql queries for me and paste the results?

select count(id) from shadow_attributes where event_org="";
select count(id) from threads where org="";
select count(id) from jobs where org="";

**Comment by advancedeng** [comment]
so, 
1. the update script stopped the first time (somewhere in th middle of the process) , so I had to run it again.
2. I do not think that I did it, although not 100% sure.

mysql> select count(id) from shadow_attributes where event_org="";
+-----------+
| count(id) |
+-----------+
|      4161 |
+-----------+
1 row in set (0.01 sec)

mysql>  select count(id) from threads where org="";
+-----------+
| count(id) |
+-----------+
|        30 |
+-----------+
1 row in set (0.03 sec)

mysql>  select count(id) from jobs where org="";
+-----------+
| count(id) |
+-----------+
|         3 |
+-----------+
1 row in set (0.88 sec)

Hope this helps.

Andreas

**Comment by iglocska** [comment]
I am just working on the upgrade script - from what I can tell those are
from earlier MISP versions (especially the shadow attribute one). I will
look into addressing it in a separate script, for now it shouldn't be
causing any issues though.

**Comment by advancedeng** [comment]
I restored my MISP instance to 2.3, rerun the initial upgrade script (just once this time...) and upgrade was successful this time.

Thanks,
Andreas
