### ISSUE TITLE
MISP version in diagnostics tab

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#783]
Hi all,

In Administration -> Server Settings-> Diagnostics I do get the following one (see jpg attached)

![misp_version](https://cloud.githubusercontent.com/assets/8973767/11960947/3a044c04-a8cd-11e5-8d57-aeb2adc217b2.JPG)

Is it something that I can manually change by provided the new MISP github branch?

Cheers,
Andreas

**Comment by iglocska** [comment]
That is normal, I haven't pushed any tags for 2.4 yet. I will do it as soon as the upgrade scripts are a bit more efficient, hopefully by tomorrow.

**Comment by iglocska** [comment]
I've pushed the first two 2.4 tags, so this should be fixed now.
