### ISSUE TITLE
Unable to edit existing event in 2.4

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#784]
Hi there, 

When I am trying to edit an event (from my org) and change the Threat Level , I get a notification 
"Please select an item in the list."

Cheers,
Andreas

**Comment by iglocska** [comment]
Hello Andreas,

this one I cannot seem to be able to reproduce... Does this happen every time or was it only once?

Best regards,
Andras

**Comment by advancedeng** [comment]
It does happen every time! Definitely cannot edit any existing event.

**Comment by adulau** [comment]
Maybe same bug as #788?
