### ISSUE TITLE
INSTALL.ubuntu1404.txt: /etc/rc.local & redis Python package

### ISSUE THREAD

**Issue by koenigswinter** [MISP/MISP#785]
Hi folks,

On my MISP 2.4 instance, I had to change two steps in the INSTALL.ubuntu1404.txt installation documentation. Please check if the installation documentation based on Ubuntu should be adapted.

1) Line 179 (/etc/rc.local)
-- su www-data -c 'bash /var/www/MISP/app/Console/worker/start.sh'
++ sudo -u www-data bash /var/www/MISP/app/Console/worker/start.sh

On a default Ubuntu installation, the Apache user "www-data" has no shell in "/etc/passwd" (/usr/sbin/nologin). The "sudo -u www-data bash <script>" way worked for me. Otherwise the workers won't start after rebooting the machine.

2) After line 219
++ pip install redis

If the Python package "redis" is not installed, the start of the ZeroMQ extension (Web Frontend "Administration", "Server settings", "Diagnostics", "Start ZeroMQ") fails with the following error in "/var/www/MISP/app/tmp/logs/mispzmq.error.log":

--snip--
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/mispzmq/mispzmq.py", line 3, in <module>
    import redis
ImportError: No module named redis
--snip--

Best regards and Season's greetings,
Heiko

**Comment by geudrik** [comment]
+1 I hadn't gotten around to creating a PR for this, but yes. This is correct

**Comment by geudrik** [comment]
While we're at it, let's use `pip` to install python dependencies, and ensure that we actually get all required software installed during initial `apt-get`

* Add `php5-mysql`, `gnupg-agent`, and `postfix` to the initial `apt-get install`
* `pip install cybox==2.1.0.10` and `pip install stix==1.1.1.4` for intalling dependencies installing of cloning releases locally

I'm not 100% sure that postfix is required (it was in 2.3)

**Comment by adulau** [comment]
A MTA (like Postfix) is required for the email notification. Thanks for the feedback, we will update the documentation. We are also working on misp-book https://github.com/MISP/misp-book) to update it for version 2.4, feedback welcome too.

**Comment by geudrik** [comment]
@adulau I assumed an mta was required, though it seems as though some emails go out regardless of whether or not postfix is running (eg: single user emails), which was where my questioning stemmed from.

I'll spend some time rooting around in the book and pr my suggestions for installation upstream

**Comment by Rafiot** [comment]
@geudrik Did you find out in which case mails have been sent?

**Comment by geudrik** [comment]
@Rafiot honestly, I can't recall. I think the moral is just install postfix and be happy? :smile:  I expect that I had sendmail doing the legwork for the partials I was seeing at one point. Having no issues to date!

**Comment by Rafiot** [comment]
Hehe, closing then :)
