### ISSUE TITLE
Could not save progress for sighting jobs

### ISSUE THREAD

**Issue by LaZyDK** [MISP/MISP#7853]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | v2.4.150 (48a03c4f20272ef5faea09427c730169981f8e20)

### Steps to reproduce the behavior
We are seeing a log of these errors in the worker log.
`tail -f /var/www/MISP/app/tmp/logs/resque-worker-error.log`
Job id is increasing fast.

### Logs, screenshots, configuration dump, ...
```
2021-10-18 10:32:26 Notice: Could not save progress for job 6712912
[PDOException] SQLSTATE[HY000]: General error: 1364 Field 'worker' doesn't have a default value
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Job.php(159): Model->save()
#6 /var/www/MISP/app/Console/Command/EventShell.php(437): Job->saveStatus()
#7 /var/www/MISP/app/Console/Command/AppShell.php(36): EventShell->publish_sightings()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
```
https://github.com/MISP/MISP/blob/2.4/app/Console/Command/EventShell.php#L437

**Comment by JakubOnderka** [comment]
Hello, can you please check if you can see job with ID 6712912 in list of jobs?

**Comment by LaZyDK** [comment]
Hey

It is not. I do add sightings over the API though, but these do not seem to reach the "jobs" page.

At this time I only have a single pull job running.
![MISP](https://user-images.githubusercontent.com/9623973/137722268-07e5b4a5-a1ec-4fb2-a377-4cfd9f6f0e1a.png)

**Comment by JakubOnderka** [comment]
Did you purge job entries? Because it is weird that your database contains just one entry.

**Comment by LaZyDK** [comment]
I did. 
Will the jobs not be purged at the same time, so that I will only get new jobs in?

**Comment by LaZyDK** [comment]
After removing the jobs in the queue, the error stopped. 
I will close this issue, if the error does not appear again when new sightings come in.

**Comment by LaZyDK** [comment]
No errors until now. I will give it a few more days, and then close the issue if nothing shows up.

**Comment by LaZyDK** [comment]
I will close the issue. This was probably caused by me. :)
