### ISSUE TITLE
Worker fails to execute publish_galaxy_clusters

### ISSUE THREAD

**Issue by hartek** [MISP/MISP#7865]
# Cannot publish new galaxy clusters - worker fails to execute _publish_galaxy_clusters_
When trying to publish a new galaxy cluster, the job never actually executes. In the WebUI, the jobs appears as _Running_ indefinitely. 

![137955979-d1ed86c2-d22b-40fb-bbb5-3daad7961bc0](https://user-images.githubusercontent.com/11649585/138086675-02f92dc4-3055-4b91-9f57-89333b62c506.png)

When inspecting the logs, I could see that the following appears at `/var/www/MISP/app/tmp/logs/resque-worker-error.log`:

```
Usage: MISP/app/Console/cake Event publish_galaxy_clusters [cluster_id] [job_id] [user_id] [pass_along]
```

![Screenshot 2021-10-19 at 18 50 36](https://user-images.githubusercontent.com/11649585/137956114-3f6664be-c964-4c90-a59a-067d990e2518.png)

It would seem like the worker is using the command with wrong arguments. 

I am able to make that job finish by manually executing the cake command manually:
```
sudo -H -u apache ${RUN_PHP} -- /var/www/MISP/app/Console/cake Event publish_galaxy_clusters 17468 28659 3 1
```

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat Enterprise Linux 8
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.150 (dc7103ca0ed020b2a06016d4717b3aba387f331f) 
| Browser                   | Firefox 93.0 64 bit 

### Expected behavior
The _prio_ worker just publishes the cluster. 

### Actual behavior
The event shows as _Running_ but never actually ends. 

### Steps to reproduce the behavior
- Create a new galaxy cluster on a galaxy (I am using Ransomware). 
- Try and publish the galaxy cluster. 
- Look at the job never finishing. 

### Logs, screenshots, configuration dump, ...

Included above. 

Hopefully this gets fixed soon :) Cheers!

**Comment by JakubOnderka** [comment]
Fixed in `develop` branch. Thanks for report.
