### ISSUE TITLE
Possibility do define "local only" tags and galaxies

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#7876]
**Is your feature request related to a problem? Please describe.**
Some tags, taxonomies and galaxies are made to only be used internally and we would like to avoid spreading them to external MISP. One way to do it is to add local tags, taxonomies and galaxies to an event or an attribute. Unfortunately it is not possible to enforce a specifc tag, taxonomy or galaxy to only be used as local. (the user can always make a mistake)

**Describe the solution you'd like**
Ideally a new checkbox next to tags, taxonomies and galaxies in the UI "Local only" that would be enforced on the UI and on the backend to make sure that these taxonomies and galaxies cannot be added as global.

**Describe alternatives you've considered**
Making the tags not exportable does not help because we still want to access the tags via the API on our own instance.

**Comment by adulau** [comment]
Thanks again for the contribution!
