### ISSUE TITLE
A LOT OF MISP FEEDS (JOBS) FALIED EVERY DAY

### ISSUE THREAD

**Issue by lucacyber** [MISP/MISP#7898]
Hi, I use OpenApi to import Misp feeds----->  (url --insecure -H "Authorization: CODE" -H "Accept: application/json" -H "Content-type: application/json" -X POST https:/MYIP/feeds/fetchFromAllFeeds) and it works.

I planned a cronjob that every night at 00.00 run the script to import MISP FEEDS, but the problem is that a lot of job falied to import every day...

This is the screenshot of today ....

![Screenshot (36)](https://user-images.githubusercontent.com/88714034/139402200-615e5cc7-ef8a-46f7-a1ed-df299dd39b2d.png)

![Screenshot (39)](https://user-images.githubusercontent.com/88714034/139402930-a3248f7f-0d0b-4c28-bf13-ed2b64156df2.png)

How can i do ?

Luca

**Comment by JakubOnderka** [comment]
Please check error logs, there should be more information.

**Comment by lucacyber** [comment]
> Please check error logs, there should be more information.

Ok, in /var/log i can't find logs about jobs... where can i search ?


thank u

**Comment by github-germ** [comment]
Look in `/var/www/MISP/app/tmp/logs/error.log`

Feeds could be failing if you're not on 2.4.150 as there was an issue requiring a revision to the Certificate Authority SSL certificate which could cause SSL failures. See https://github.com/MISP/cakephp/issues/1

**Comment by lucacyber** [comment]
> issue requiring a revision to the Certificate Authority S

yes a lot of errors has this -->

 [Exception] Fetching the ?URL' failed with exception: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://home.nuug.no:443 (Unknown error)



how can i solve?

thank u

**Comment by github-germ** [comment]
I believe 2.4.150 has a revised CA. Otherwise, if oyu have a current CA cert, you can configure this in the MISP WebUI `Admin > Server Settings & Maintenance` with `MISP.ca_path`

**Comment by adulau** [comment]
I suppose we can close the issue. If you see the error persists with a recent version of MISP, feel free to reopen.
