### ISSUE TITLE
API Export Only Items Starting with a Number are Exported

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#790]
Just testing 2.4 and noted that with the API regardless of what is requested md5, domain, etc. 

The results only include items that start with a number. Also noted that generally the export feature is not available at all from the UI but the API works. Don't know if you guys are aware of it. Maybe we can fork and start helping you fix some of these issues. 

Thanks again for a great product.

**Comment by cvandeplas** [comment]
A fork with pull-requests fixing those would definitely be welcome, so don't hesitate.

I'm not really sure to understand what exactly is happening in your instance. Could you describe with a simple example (the requests you do to the API, or code using PyMISP) with some (fake) data?

**Comment by jigsawsecurity** [comment]
After running export job in the export panel or when using the API (doesn't matter which method) only values that start with a number are exported. For example a domain of 1test.com would export but not test1.com since that starts with a letter. The same holds true for hostnames as well. It's almost like it is ignoring anything in the database that starts with a letter. Looking at the CIRLC instance it has the same issue as I think they are now on 2.4 as well. 

Hopefully my description makes sense. I'll start looking tomorrow to see why this is happening but it's not just my instance. A few of the other ones that I peer with that are on 2.4 are exhibiting the same behavior on exports and API requested values. 

I will start having my team work on some things in the new branch that may be of interest to the user community.

**Comment by iglocska** [comment]
Thanks for the heads-up, that was a silly issue indeed. Should be fixed now.

**Comment by jigsawsecurity** [comment]
It appears to be resolved in the new release and CIRCL is also fixed.
