### ISSUE TITLE
Failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 297

### ISSUE THREAD

**Issue by grassman80bz** [MISP/MISP#7906]
Good morning,
I am trying unsuccessfully to install MISP.
After a few steps forward, installing php74 etc, now the installation script crashes when working on "cake".

The error is this and despite searching online I can't find a solution:

[root@misp-p ~]# bash -x /tmp/INSTALL.sh -A
[...]
Debug Mode, press enter to continue...

exec

read

sudo -H -u apache -- /var/www/MISP/app/Console/cake userInit -q
PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297

sudo -H -u apache -- /var/www/MISP/app/Console/cake Admin runUpdates
PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297

sudo -H -u apache -- /var/www/MISP/app/Console/cake Admin setSetting MISP.python_bin /var/www/MISP/venv/bin/python
PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297

sudo -H -u apache -- /var/www/MISP/app/Console/cake Admin setSetting Session.autoRegenerate 0

PHP Warning: require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 297
PHP Fatal error: require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 297

and on and on for many, many more lines.

In fact, that file does not exist, nor does the folder "Vendor".
[root@misp-p ~]# ll /var/www/MISP/app/Vendor/autoload.php
ls: cannot access /var/www/MISP/app/Vendor/autoload.php: No such file or directory

If I also try to install the Vendor folder via "composee" other problems begin with the proxy, then with ipv6 which is not in use but only tests that.

In short, I'm stuck.

[root@misp-p app]# which php
/usr/bin/php
[root@misp-p app]# php --version
PHP 7.4.25 (cli) (built: Oct 19 2021 15:18:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

[root@misp-p app]# php composer.phar require kamisama/cake-resque:4.1.2
https://repo.packagist.org could not be fully loaded (Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.), package information was loaded from the local cache and may be out of date

[Composer\Downloader\TransportException]
Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] []...

[root@misp-p app]# php composer.phar config vendor-dir Vendor
[root@misp-p app]# php composer.phar install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
https://repo.packagist.org could not be fully loaded (Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.), package information was loaded from the local cache and may be out of date

[Composer\Downloader\TransportException]
Connecting to a secure proxy using curl is not supported on PHP versions below 7.3.0.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] []...

How can I solve this?
Thank you very much

**Comment by jmmyroger** [comment]
I have the same problem !

**Comment by Kairat-ifeb** [comment]
I also have the same promleb. Can anybody help?

**Comment by s3cr3search** [comment]
Bumping. I also have this issue on a fresh install today

**Comment by SantiagoSerrao** [comment]
I am having the same issue in a fresh install with ubuntu 20.04

**Comment by SteveClement** [comment]
Tested on 18.04.6 with php 7.4.27

It worked, please try again and in case it does not work include the full debug of the installer.

Thanks.

**Comment by waldeckerthefirst** [comment]
Hello,
i have the same issue with php version
PHP 7.4.32 (cli) (built: Sep 28 2022 09:09:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.32, Copyright (c), by Zend Technologies
During the installation with the INSTALL.sh script i get 
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/opt/misp/www/MISP/app/Vendor/autoload.php' (include_path='/opt/misp/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in /opt/misp/www/MISP/app/Config/core.php on line 298
PHP Warning:  require_once(/opt/misp/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /opt/misp/www/MISP/app/Config/core.php on line 298

[root@soc app]# php composer.phar diagnose
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.kamisama/cake-resque : exact version constraints (4.1.2) should be avoided if the package follows semantic versioning
require.pear/crypt_gpg : exact version constraints (1.6.7) should be avoided if the package follows semantic versioning
require.monolog/monolog : exact version constraints (1.24.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.9 => 2.4.3)
Composer version: 2.0.9
PHP version: 7.4.32
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1k  FIPS 25 Mar 2021
cURL version: 7.61.1 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present
[root@soc app]# php composer.phar self-update --update-keys
Open https://composer.github.io/pubkeys.html to find the latest keys
Enter Dev / Snapshot Public Key (including lines with -----): ^C^X^C^C^C
[root@soc app]# php composer.phar self-update
Upgrading to version 2.4.3 (stable channel).
   
Use composer self-update --rollback to return to version 2.0.9
[root@soc app]# php composer.phar diagnose
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
composer/installers contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "composer/installers" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.kamisama/cake-resque : exact version constraints (4.1.2) should be avoided if the package follows semantic versioning
require.pear/crypt_gpg : exact version constraints (1.6.7) should be avoided if the package follows semantic versioning
require.monolog/monolog : exact version constraints (1.24.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK git version 2.31.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.4.3
PHP version: 7.4.32
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1k  FIPS 25 Mar 2021
cURL version: 7.61.1 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present, 7-Zip not available

[root@soc app]# cd Config/
[root@soc Config]# ls
bootstrap.default.php  config.default.php  core.default.php  database.default.php  email.php
bootstrap.php          config.php          core.php          data
