### ISSUE TITLE
New Install Puts Export Data in Root of OS Drive

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#791]
Just a quick note that on a new install it appears as though the exported data gets dropped in the root of the filesystem instead of the export directory. Creating the directory fixes the issue.

**Comment by iglocska** [comment]
Hmm that is weird. For me it drops it in /var/www/MISP/app/tmp/cached_exports/[export_type]

Is it a standard installation or did you modify anything? The path should be relative from APP.

Also, which export is causing this?

**Comment by jigsawsecurity** [comment]
Standard install from scratch on Ubuntu. I'll keep going through our checklist to see if I discover anything else. The new version looks good.

**Comment by jigsawsecurity** [comment]
It's not creating the directories even though permissions are set correctly. 

root@misp24:/var/www/MISP/app/tmp# ls
cache           csv_all  files  md5       sha1   suricata  text
cached_exports  csv_sig  logs   sessions  snort  tests     xml

and then this... 

root@misp24:/var/www/MISP/app/tmp/cached_exports/rpz# ll
total 3456
drwxr-s--- 2 www-data www-data    4096 Dec 25 05:09 ./
drwxr-s--- 3 www-data www-data    4096 Dec 24 13:37 ../
-rwxrwx--- 1 www-data www-data       0 Dec 24 13:37 empty*
-rw-r----- 1 www-data www-data 3527728 Dec 25 09:58 misp.rpz..txt


Notice the filename is misp.rpz..txt

That's kind of weird also.

**Comment by iglocska** [comment]
That is odd indeed. I just tried to reproduce it but I get misp.rpz.CIRCL.txt on my dev machine as expected. 

Is this on 2.4?

**Comment by jigsawsecurity** [comment]
Yes only on 2.4. On 2.3 it works fine. 

I built another instance and I'm seeing the same thing on both. Both are Ubuntu 14.04. Let me build it on CentOS7 and see what I get.

**Comment by iglocska** [comment]
Will install a fresh machine tomorrow and try to debug it. All my instances
are migrated from 2.3 so it could be something going wrong during
installation.

**Comment by jigsawsecurity** [comment]
These are both fresh 2.4 installs. We have a main instance in which we input events, the second instance is synced with the first and that is the instance we allow feeds from. Both are doing exactly the same thing. When we install we take the install script and we basically run all the commands minus the comments of course as a batch to avoid installation errors.

**Comment by jigsawsecurity** [comment]
It's writing the data to the root of the filesystem. It's definitely weird. I'll look and see if I can figure out what is going on.

**Comment by iglocska** [comment]
Great, if you can't I'll have a look in the morning. Let me know if you
find it before that!

**Comment by jigsawsecurity** [comment]
So after researching I noted that the directory's are not being created under Ubuntu. If you create the directories manually and set the permissions the exports start working as they did in previous versions. I didn't look to see where the directories are created but if you do a fresh install it will give you similar results. 

It's working now after manually creating the directories.

**Comment by iglocska** [comment]
I've pushed a patch for it, if you don't have the dirs created MISP will now create it for you. I still cannot reproduce a situation where it puts the export files into root though, that could be potentially dangerous, so if you could describe the steps how to reproduce it that would be great. Thanks for all the help!

**Comment by jigsawsecurity** [comment]
This is definitely somethings strange in Ubuntu only. It does not behave this way on CentOS. If you build an Ubuntu system from scratch (pre patch) it would do it. I build 3 separate instances and it did the same thing. The patch did fix the issue though. 

I reviewed the code and did not see a clear reason why it would do this as the PHP code was correct.
