### ISSUE TITLE
Delegation of publication - proposal

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#792]
Delegation of publication to delegate the ownership (and publication) of an event to another organization. The purpose is to have a third party organization that publishes an event instead of the initial organization who initially created the unpublished event. This would allow organization to delegate ownership and publication and avoid to be named for an event.

The functionality would only be used on a local MISP instance and don't need to be distributed.

- The user will create an event as delegation to a local organization (the event will not be seen by anyone before the delegation is accepted (it's before publication)).
- The local organization will accept or refuse the publishing of the event.
- If refused, the user who initially fill the event for delegation will get back the event in the initial state (non visible to anyone and unpublished).
- If accepted, it will be a standard event owned by the third party organization.

Feedback more than welcome.

**Comment by elhoim** [comment]
Nice idea!

About the event being invisible when not published, do you see it as something different than the ***unpublishedprivate*** setting or making it disappear and act if the value was set to true?

If this is implemented, would render #472 unecessary since it is the same goal.
Maybe also #550.

**Comment by adulau** [comment]
Indeed, the state visibility would be as similar as the *unpublished private setting* but I suppose this would be in addition as some admin would still be able to have events unpublished to be visible for everyone while keeping the event "with delegation pending" not visible to not leak the name of the orgs.

**Comment by iglocska** [comment]
The easiest way to do this would be simply to create an event as your organisation only and then have a mechanism to request another org to take ownership of the event. So in this case: If you are the original creator of an event, you can create a request to another organisation to take ownership, at which point said organisation would be able to review the event and say yes or no. If the requested organisation says yes then the orgc_id and org_id field are altered to the new org.

The original org loses access (and visibility) to the event, until the new org raises the distribution level and makes it accessible to other organisations.

Does this sound ok?

**Comment by iglocska** [comment]
The only pitfall I can see is that the event after the move should probably have a new ID to destroy any associations to the origina event in the log (so that users don't see who created it via the event history for example).

**Comment by adulau** [comment]
@iglocska Nice. Looks good to me without changing the data-model itself.  If the event is never accepted by the requested organization, the event will stay forever there as your organization only.

**Comment by iglocska** [comment]
Yup indeed. We do need a small data model modification, but only in the
shape of a new table, I don't want to touch the current event / attribute
tables for this.

So we'd have a new table that simply links event ID, original org, target
org.

**Comment by elhoim** [comment]
You also need to have a flag at Event level to override the value of ***unpublishedprivate*** even if it set to false. If an org wants to delegate publication under another name, it probably does not want to have its draft event being public.

**Comment by iglocska** [comment]
If an event is org only then it is only visible to the creator org. The
idea is to be able to show it to a second organisation and tell them you
can have this if you accept and then you can do with it what you want. If
they accept, they can raise the distribution level.

**Comment by elhoim** [comment]
Will the originating org have any, structured or not, way to mention what level of distribution they would like to be set on the data by the publishing org?

**Comment by iglocska** [comment]
The original org can include a message, but we can also add a desired
distribution level if you'd like, I am just coding it.

**Comment by iglocska** [comment]
This is now implemented since 2.4.18
