### ISSUE TITLE
Fresh install on Ubuntu No Link Provided

### ISSUE THREAD

**Issue by alsilor** [MISP/MISP#7922]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version        | 20.04
| Browser                   | Firefox

### Support Questions
I recently installed MISP on Ubuntu 20.04. I can't seem to access the GUI through the usual web, misp.local, as no link was provided after installing.

![image](https://user-images.githubusercontent.com/22878039/140278390-b5842ef7-fe73-49be-8cbf-ac9ae4c4633c.png)

**Comment by SteveClement** [comment]
If it is on your local machine https://localhost should work.

If not: ```ip a```

And see what IPs are available.
