### ISSUE TITLE
Error adding attributes with template (2.4.0)

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#795]
When trying to populate an event with template, we obtain the following output in app/tmp/logs/errors.log

2015-12-28 14:26:12 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Event.orgc' in 'field list'
Request URL: /templates/templateChoices/8?_=1451309075067
Stack Trace:
#0 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Event`....', Array)
#2 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `Event`....', Array, Array)
#3 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `Event`....', false)
#4 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Event), Array)
#5 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#6 /home/misp/MISP/app/Controller/TemplatesController.php(230): Model->find('first', Array)
#7 [internal function]: TemplatesController->templateChoices('8')
#8 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TemplatesController), Array)
#9 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /home/misp/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TemplatesController), Object(CakeRequest))
#11 /home/misp/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by FafnerKeyZee** [comment]
Solve by fixing : app/Controller/TemplatesController.php
change : (l229) 'fields' => array('orgc', 'id'),
to : (l229) 'fields' => array('orgc_id', 'id'),

**Comment by iglocska** [comment]
Thanks for the heads-up, just pushed a fix.

**Comment by FafnerKeyZee** [comment]
It's working ;-) thanks for the fast answer & fix

**Comment by iglocska** [comment]
Let me know if you run into any other bugs! :)

**Comment by FafnerKeyZee** [comment]
There are few 'orgc' instead of 'orgc_id' into the file too, can you change them please ?
