### ISSUE TITLE
An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by Tukaram1992** [MISP/MISP#7951]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  Ubuntu,..
| OS version (client)       | 18.04...

### Support Questions

Hi Team ,

I have installed new MISP on ubuntu 18.04. Now i am getting error as "An Internal Error Has Occurred. " Also asking for down loading PGP public key.

Please find below error.log . Request you to help me to resolve this issue.

2021-11-11 07:15:13 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Controller/AppController.php(807): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Controller/AppController.php(132): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
2021-11-11 07:15:23 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)

Database.php file 

root@stlmisptest:~#  cat /var/www/MISP/app/Config/database.php
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  //'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  'port' => 3306, // MySQL & MariaDB
                  //'port' => 5432, // PostgreSQL
                  'password' => 'c29de71577cb8ff73dbbb200bacfaf3c18450c4231c7f7f5f7d00a2b43851016',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
                  'unix_socket' => '/Applications/MAMP/tmp/mysql/mysql.sock',
          );
  }

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/43696516/141256783-2a1e5083-e3b7-4c99-b67c-89f81edb2a52.png)
![MISP](https://user-images.githubusercontent.com/43696516/141256878-4ee73630-b716-4927-a2d6-305725d8c364.JPG)

**Comment by iglocska** [comment]
Can you log into mysql using those data-points with the CLI client?

**Comment by righel** [comment]
Hello @Tukaram1992 
Seems to be a issue connecting to the database.
Please check the following file looks like this:
`/var/www/MISP/app/Config/database.php`
```php
<?php
  class DATABASE_CONFIG {
          public $default = array(
                  'datasource' => 'Database/Mysql',
                  //'datasource' => 'Database/Postgres',
                  'persistent' => false,
                  'host' => 'localhost',
                  'login' => 'misp',
                  'port' => 3306, // MySQL & MariaDB
                  //'port' => 5432, // PostgreSQL
                  'password' => 'YOUR_PASSWORD',
                  'database' => 'misp',
                  'prefix' => '',
                  'encoding' => 'utf8',
          );
  }
```


Check MySQL is effectively running in your host:
`sudo service mysql status`
Also, verify the password in your config file is the correct.
```
$ mysql -u misp -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
...
```
