### ISSUE TITLE
Freetext import fails, unable to read file in /tmp

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#7960]
When adding attributes (about 100) via the freetext import the import sometimes fails. 
Restarting the prio worker solves the problem but only temporarily. The problem reoccurs after a while.

The system has sufficient disk space and system resources (no memory, cpu or disk issues).

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.4
| MISP version / git hash   | 2.4.150

### Expected behavior

Successfully adding attributes via freetext

### Actual behavior

Adding attributes via freetext import fails

### Steps to reproduce the behavior

* New event
* Free text import
* Paste column with attributes
* Submit, Submit attributes

### Logs, screenshots, configuration dump, ...

`
[2021-11-15 11:34:03] main.ERROR: {"queue":"prio","id":"01e4953e3651971ca2314c0b97d0dc28","class":"EventShell","args":[["processfreetext","\/tmp\/MISP8othWh"]]} failed: An error has occurred while attempt to read file `/tmp/MISP8othWh`: file doesn't exists. {"type":"fail","log":"An error has occurred while attempt to read file `/tmp/MISP8othWh`: file doesn't exists.","job_id":"01e4953e3651971ca2314c0b97d0dc28","time":68,"worker":"misp:89754"} []
`

`
Failed at: Mon Nov 15 11:29:32 CET 2021
Exception: Exception
Error: An error has occurred while attempt to read file `/tmp/MISPKcXoZn`: file doesn't exists.
(Click to hide stack trace)
#0 /data/www/MISP/app/Console/Command/EventShell.php(531): FileAccessTool::readFromFile()
#1 /data/www/MISP/app/Console/Command/AppShell.php(36): EventShell->processfreetext()
#2 /data/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#3 /data/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#4 /data/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#5 /data/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#6 /data/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#7 {main}
`

**Comment by JakubOnderka** [comment]
Hello, check https://github.com/MISP/MISP/issues/7868

**Comment by marcnil815** [comment]
+1. Same observatio here.
We set the workers to restart every 10 minutes and it still happens, so it seems either like a race condition or a particular attribute triggering it, although the latter explanation is much less likely.

**Comment by marcnil815** [comment]
> Hello, check #7868

That fix also fixed this.

**Comment by cudeso** [comment]
https://github.com/MISP/MISP/issues/7868 fixed this
