### ISSUE TITLE
Showing cakePHP text

### ISSUE THREAD

**Issue by dgr3atSy** [MISP/MISP#7962]
<img width="960" alt="Screenshot 2021-11-16 113510" src="https://user-images.githubusercontent.com/62403586/141891292-e0a1e67d-5dc4-4150-ae49-5508945b020b.png">

Hi, can someone help, when open my localhost, It's show cakePHP text.

**Comment by righel** [comment]
Hello @syukrismsuri 
How did you install MISP? Which OS? Are you using Nginx or Apache?
At first glance seems you are missing the php module in your Apache installation.

If you are using Apache, try with these commands:
```
sudo apt install -qy \
libapache2-mod-php7.4 \
php7.4 php7.4-cli \
php7.4-dev \
php7.4-json php7.4-xml php7.4-mysql php7.4-opcache php7.4-readline php7.4-mbstring php7.4-zip \
php7.4-redis php7.4-gnupg \
php7.4-intl php7.4-bcmath \
php7.4-gd
sudo a2enmod php7.4
sudo systemctl restart apache2
```

Let me know if that helps.

**Comment by dgr3atSy** [comment]
Hi @righel, thank you for reply. Im using Ubuntu 20.04 and Apache. 
After try ur suggestion, it showing like this below : 
<img width="960" alt="Screenshot 2021-11-16 172757" src="https://user-images.githubusercontent.com/62403586/141958989-f7a48acc-2a16-440c-a046-0435fb56e84a.png">

Do you know why?

**Comment by righel** [comment]
Could please answer which steps you took to install MISP?
Have you followed the install guide?
https://misp.github.io/MISP/INSTALL.ubuntu2004/

**Comment by dgr3atSy** [comment]
Yess, im follow installation guide on that website, which is "following on a clean supported distribution".

**Comment by righel** [comment]
I would suggest to try to re-install, seems there was an issue during the install. 
If possible, could you check the install logs? There should be a hint on what when wrong in there.

**Comment by dgr3atSy** [comment]
Hello @righel , do u have suggestion what should i check first, like version of php or anything else? Because I already re-install and its still get same error. Can i know how to check the install logs?

**Comment by righel** [comment]
By installation logs I mean the terminal output when you run the install script.
Some further checks:

Check php module is loaded.
```
$ sudo apache2ctl -M | grep php
 php7_module (shared)
```
Load the correct php module.
```
$ sudo a2dismod php7.2
$ sudo a2enmod php7.4
$ sudo service apache2 restart
```

Run composer:
```
$ cd /var/www/MISP/app
$ php composer.phar composer global update
$ php composer.phar composer dump-autoload
$ php composer.phar install --no-dev
```

Let me know if that helps.

**Comment by dgr3atSy** [comment]
@righel , it's solved now! the problem is my php module don't exist. Thank you for ur help!

**Comment by righel** [comment]
Awesome!
