### ISSUE TITLE
Attribute search result missing links to related events

### ISSUE THREAD

**Issue by jalmarikalmari** [MISP/MISP#7963]
# This template is meant for bug reports, if you have a feature request user the other template.

When performing an Attribute search the result show attributes with related Event per each attribute.
There was a link to Event in the Event field of results at least before  going to MISP Version 2.4.148.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04 & 20.04
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.2 & 7.4
| MISP version / git hash   | 2.4.150 (fb6408dd4faa028c41aaadfb604461badde7717d)
| Browser                   | Chrome 

### Expected behavior

After successful Attribute search Event ID in the result should have link to related Event

### Actual behavior

After successful Attribute search  there is Event ID shown in the result correctly, but link to Event seems to be missing.

### Steps to reproduce the behavior
1. Open Search Attribute
2. Search any Attribute
3. The result shows Attributes based on search, but links to related Events are missing

**Comment by 3c7** [comment]
Yep, same here. Digged a bit in the source code, but didn't find the change responsible. Would be good to have this fixed, as it breaks the typical workflow for searching attributes via GUI and getting context via the attribute's events.

**Comment by righel** [comment]
Hello, this bug was already fixed in `develop` branch by commit c1d69b7b69f09fd98b0616791d40ebcfb0fa6c83, the regression was introduced by 82ec738770377f53cc0425397455a9165741f741.
The fix will be included in the next release.

**Comment by 3c7** [comment]
Great! Thanks @righel @JakubOnderka.
