### ISSUE TITLE
Attributes' tags within a MISPObject not pushed

### ISSUE THREAD

**Issue by nyx0** [MISP/MISP#7964]
When pushing MISPObject using PyMISP or cURL attributes tagged within the object are not applied.

### Work environment

| MISP version / git hash   | latest

### Expected behavior
Pushing a MISPObject with attributes tagged and see those attributes tagged within MISP.

### Actual behavior
Pushing a MISPObject with attributes tagged and those attributes are *not* tagged within MISP.

### Steps to reproduce the behavior
Create a MISPObject.
Add an attribute.
Add a tag to the attribute.
Push the object.

### Logs, screenshots, configuration dump, ...
n/a

**Comment by JakubOnderka** [comment]
Hello, can you please provide example of your code? It will help us to debug this problem.

**Comment by nyx0** [comment]
hello, my code is quite simple:
```
for ev_obj in event.objects:
  if ev_obj.name != 'internal':
    response = misp.add_object(
      event_id,
      ev_obj,
      break_on_duplicate=True)
```

**Comment by nyx0** [comment]
Hi I found a workaround:
```
int_event = misp.get_event(event_id)
ext_event = pymisp.MISPEvent()
ext_event.from_dict(**int_event)
```
