### ISSUE TITLE
Cake CLI partially broken after update to 2.4.151

### ISSUE THREAD

**Issue by patricksaladino** [MISP/MISP#7980]
Hi there,

I applied the 2.4.150 to 2.4.151 update this morning using the web diagnostics page at https://misp.domain.tld/servers/serverSettings/diagnostics. The CakePHP CLI interface is now raising errors when called, for example :

**/var/www/MISP/app/Console/cake Server --help**
Error: Argument 1 passed to BackgroundJobsTool::__construct() must be of the type array, null given, called in /var/www/MISP/app/Console/Command/ServerShell.php on line 23
#0 /var/www/MISP/app/Console/Command/ServerShell.php(23): BackgroundJobsTool->__construct(NULL)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): ServerShell->initialize()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#4 {main}

**/var/www/MISP/app/Console/cake test** also crashes with the following message :

Warning Error: include(PHPUnit/Autoload.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Lib/cakephp/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 180]

2021-11-22 09:15:53 Warning: include(PHPUnit/Autoload.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Lib/cakephp/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 180]
Warning Error: include(): Failed opening 'PHPUnit/Autoload.php' for inclusion (include_path='/var/www/MISP/app/Vendor/phpunit/phpunit:/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:/var/www/MISP/app/Vendor/pear/pear_exception:/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 180]

2021-11-22 09:15:53 Warning: include(): Failed opening 'PHPUnit/Autoload.php' for inclusion (include_path='/var/www/MISP/app/Vendor/phpunit/phpunit:/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:/var/www/MISP/app/Vendor/pear/pear_exception:/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/pear:/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php, line 180]
Error: Please install PHPUnit framework v3.7 (http://www.phpunit.de)
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): TestShell->initialize()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#3 {main}

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Red Hat Enterprise Linux release 8.5 (Ootpa) x64
| OS version (client)       | Not relevant
| PHP version               | PHP 7.4.19
| MISP version / git hash   |  v2.4.151 (e0ca2789a40c6cf70aea499c325d0402aaa4617f)
| Browser                   | If applicable

**Comment by righel** [comment]
Hello,
Thanks reporting, working on the fix.
You can circumvent this error by adding the following a top-level setting to your `/var/www/MISP/app/Config/config.php` file:
```
  'SimpleBackgroundJobs' => 
  array (
    'enabled' => false,
  ),
```
Fix will be ready soon.

**Comment by righel** [comment]
Just pushed a fix both on `develop` 531676620585454c6172019719e7b3ff13235864 and `2.4`  45532ed0bf54a8a1a0e353799819a68f7be43bdf

Let me know if it works.

EDIT: version 2.4.151 was re-tagged.

The `/var/www/MISP/app/Console/cake test` error is unrelated, and we don't rely on those tests.

**Comment by patricksaladino** [comment]
> Hello, Thanks reporting, working on the fix. You can circumvent this error by adding the following a top-level setting to your `/var/www/MISP/app/Config/config.php` file:
> 
> ```
>   'SimpleBackgroundJobs' => 
>   array (
>     'enabled' => false,
>   ),
> ```
> 
> Fix will be ready soon.

Hi. Thank you for your quick reply. The workaround unfortunately didn't work for me.

**Comment by righel** [comment]
Could you try updating again from the Diagnostics page? and try again the command:
**/var/www/MISP/app/Console/cake Server --help**

**Comment by patricksaladino** [comment]
MISP has just been updated to  v2.4.151 (45532ed0bf54a8a1a0e353799819a68f7be43bdf)

**/var/www/MISP/app/Console/cake Server --help** now works as expected

/var/www/MISP/app/Console/cake Server --help
Usage:
cake server [-h] [-v] [-q]

Options:

--help, -h     Display this help.
--verbose, -v  Enable verbose output.
--quiet, -q    Enable quiet output.

Thank you !

**Comment by righel** [comment]
Thanks for reporting!

**Comment by imidoriya** [comment]
I'm getting this same error, but looks like it's on `StartWorkerShell.php`
Latest `v2.4.151 (b869ff91549436ce189be9ff76aa4d1581384f3f) `
```
deku@mispy:/var/www/MISP/app/Console$ ./cake start_worker default
Error: Argument 1 passed to BackgroundJobsTool::__construct() must be of the type array, null given, called in /var/www/MISP/app/Console/Command/StartWorkerShell.php on line 23
#0 /var/www/MISP/app/Console/Command/StartWorkerShell.php(23): BackgroundJobsTool->__construct(NULL)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): StartWorkerShell->initialize()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#4 {main}
deku@mispy:/var/www/MISP/app/Console$ ./cake start_worker prio
Error: Argument 1 passed to BackgroundJobsTool::__construct() must be of the type array, null given, called in /var/www/MISP/app/Console/Command/StartWorkerShell.php on line 23
#0 /var/www/MISP/app/Console/Command/StartWorkerShell.php(23): BackgroundJobsTool->__construct(NULL)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): StartWorkerShell->initialize()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#3 /var/www/MISP/app/Console/cake.php(44): ShellDispatcher::run(Array)
#4 {main}
```

I'm trying to upgrade to the new Background Job process, but all my supervisor workers look like this and my normal workers are dead stating `Queue status: Issues prevent jobs from being processed. Please resolve them below. `
> sudo supervisorctl status
```
misp-workers:cache_00            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_01            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_02            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_03            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_04            FATAL     Exited too quickly (process log may have details)
misp-workers:default_00          FATAL     Exited too quickly (process log may have details)
misp-workers:default_01          FATAL     Exited too quickly (process log may have details)
misp-workers:default_02          FATAL     Exited too quickly (process log may have details)
misp-workers:default_03          FATAL     Exited too quickly (process log may have details)
misp-workers:default_04          FATAL     Exited too quickly (process log may have details)
misp-workers:email_00            FATAL     Exited too quickly (process log may have details)
misp-workers:email_01            FATAL     Exited too quickly (process log may have details)
misp-workers:email_02            FATAL     Exited too quickly (process log may have details)
misp-workers:email_03            FATAL     Exited too quickly (process log may have details)
misp-workers:email_04            FATAL     Exited too quickly (process log may have details)
misp-workers:prio_00             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_01             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_02             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_03             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_04             STARTING  
misp-workers:update_00           FATAL     Exited too quickly (process log may have details)
```

**Comment by righel** [comment]
Hi @imidoriya 
If you are trying the new background jobs backend please follow this guide:
https://gist.github.com/righel/8ebc6c84341f2aea7d0bfa124e535ef8

It seems you are missing the required settings in your `config.php` file, check: https://gist.github.com/righel/8ebc6c84341f2aea7d0bfa124e535ef8#misp-config

The settings should something like this:
```
  'MISP' => [
    ...,
  ],
  'SimpleBackgroundJobs' => [
    'enabled' => true,
    'redis_host' => 'localhost',
    'redis_port' => 6379,
    'redis_password' => '',
    'redis_database' => 1,
    'redis_namespace' => 'background_jobs',
    'max_job_history_ttl' => 86400,
    'track_status' => false,
    'supervisor_host' => 'localhost',
    'supervisor_port' => '9001',
    'supervisor_user' => 'supervisor',
    'supervisor_password' => 'supervisor',
  ], 
```

If you still encounter issues, feel free to open a separate issue.
