### ISSUE TITLE
Cannot edit existing objects to add new attributes (no uuid set in saving?)

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#7987]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 20.04.3 LTS
| OS version (client)       | Win10
| PHP version               | 7.4.3
| MISP version / git hash   | v2.4.151 (3abe0594047500a6c11a9a61e26406e3bc508d5e)

### Expected behavior
I would be able to edit an existing object to add new attributes and values.

I was editing an email object when I noticed something which currently seems like that if the object already contains some values I can't save the new value because it doesn't get an uuid value? I'm not exactly sure but it looks that way with some quick tests. I can edit singular attributes which are not part of an object so it looks like it has something to do with the attributes in objects. This started after updating to the current version of MISP.

### Actual behavior
See the screenshots below.

### Steps to reproduce the behavior
See the screenshots below.

### Logs, screenshots, configuration dump, ...

I don't get any printout to the logs under `/var/www/MISP/app/tmp/logs/` when saving the object.

Example object before editing:

![A test email object](https://user-images.githubusercontent.com/5585477/143073415-299b7a49-d4b7-4b45-a845-968f16f17fee.PNG)

Object pre-save review:

![Object pre-save review](https://user-images.githubusercontent.com/5585477/143073520-a1a5be8c-a0af-4912-b43e-3339fa655860.PNG)

Another test another field:

![image](https://user-images.githubusercontent.com/5585477/143074411-a51d75e6-832e-4af1-90cf-a10bc7048176.png)

Another object another field:

![image](https://user-images.githubusercontent.com/5585477/143074762-dba3258d-658e-40a8-96f9-3ca406f4278b.png)

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in `develop` branch.

**Comment by samitainio** [comment]
@adulau would it be possible to have this fix available in the main `2.4` branch?
