### ISSUE TITLE
MariadB is not starting

### ISSUE THREAD

**Issue by aldoarreolaAZ** [MISP/MISP#7989]
below my error:
Nov 23 21:19:50 servername.privorg.net mysqld[3689]: /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f57261d5555]
Nov 23 21:19:50 servername.privorg.net mysqld[3689]: /usr/sbin/mysqld(+0x39c83d)[0x7f57286e983d]
Nov 23 21:19:50 servername.privorg.net mysqld[3689]: The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains
Nov 23 21:19:50 servername.privorg.net mysqld[3689]: information that should help you find out what is causing the crash.
Nov 23 21:19:52 servername.privorg.net systemd[1]: mariadb.service: main process exited, code=dumped, status=6/ABRT
Nov 23 21:19:52 servername.privorg.net systemd[1]: Failed to start MariaDB 10.1.46 database server.
Nov 23 21:19:52 servername.privorg.net systemd[1]: Unit mariadb.service entered failed state.
Nov 23 21:19:52 servername.privorg.net systemd[1]: mariadb.service failed.
Nov 23 21:19:57 servername.privorg.net systemd[1]: mariadb.service holdoff time over, scheduling restart.
Nov 23 21:19:57 servername.privorg.net systemd[1]: Starting MariaDB 10.1.46 database server...
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] /usr/sbin/mysqld (mysqld 10.1.46-MariaDB) starting as process 3970 ...
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, incre
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Using mutexes to ref count buffer pool pages
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: The InnoDB memory heap is disabled
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Compressed tables use zlib 1.2.7
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Using Linux native AIO
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Using SSE crc32 instructions
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Initializing buffer pool, size = 128.0M
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Completed initialization of buffer pool
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Highest supported file format is Barracuda.
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Starting crash recovery from checkpoint LSN=10399888813
Nov 23 21:19:57 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:57 140100636944640 [Note] InnoDB: Restoring possible half-written data pages from the doublewrite buffer...
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:58 140100636944640 [Note] InnoDB: Starting final batch to recover 113 pages from redo log
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:58 140100636944640 [ERROR] InnoDB: Trying to access page number 14 in space 26 space name misp/logs, which is outside the tablespace bounds. Byte offset 0, len
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: 2021-11-23 21:19:58 7f6bb8b2a900  InnoDB: Assertion failure in thread 140100636944640 in file ha_innodb.cc line 21944
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: We intentionally generate a memory trap.
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: If you get repeated assertion failures or crashes, even
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: immediately after the mysqld startup, there may be
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: corruption in the InnoDB tablespace. Please refer to
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: InnoDB: about forcing recovery.
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: 211123 21:19:58 [ERROR] mysqld got signal 6 ;
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: This could be because you hit a bug. It is also possible that this binary
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: or one of the libraries it was linked against is corrupt, improperly built,
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: or misconfigured. This error can also be caused by malfunctioning hardware.
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: To report this bug, see https://mariadb.com/kb/en/reporting-bugs
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: We will try our best to scrape up some info that will hopefully help
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: diagnose the problem, but since we have already crashed,
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: something is definitely wrong and this may fail.
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: Server version: 10.1.46-MariaDB
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: key_buffer_size=134217728
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: read_buffer_size=131072
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: max_used_connections=0
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: max_threads=153
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: thread_count=0
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: It is possible that mysqld could use up to
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 467156 K  bytes of memory
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: Hope that's ok; if not, decrease some variables in the equation.
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: Thread pointer: 0x0
Nov 23 21:19:58 servername.privorg.net mysqld[3970]: Attempting backtrace. You can use the following information to find out
[mariadberror.txt](https://github.com/MISP/MISP/files/7592474/mariadberror.txt)

**Comment by SteveClement** [comment]
You probably to run the DB on a machine that has not enough memory and tries to allocate too much of it.

Please upgrade your HW specs.
