### ISSUE TITLE
MISP Feed events published to a sharing group result is "Feed of Death" for sync

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#7992]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| PHP version               | 7.4
| MISP version / git hash   | 2.4.251, 3abe0594047500a6c11a9a61e26406e3bc508d5e
| Browser                   | Chrome

### Expected behavior
When a feed is created and sharing group is added, or any Distribution for that sake the main event should have the distribution chosen, but all attributes should have "Inherit Event"

### Actual behavior
When an event is created with the below steps it will result in Sync from this server is failing, on the receiving server, the following error occurs.
```
Error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/Tools/HttpSocketExtended.php, line 107]
``` 
Additionally the event will become bloated based on that the feed is adding the "Sharing Group" to each event, instead of using "Inherit Event", as a result the sharing group members is added to each event.

In our case this means that an event with around 120.000 attributes of domains, and 42 members of a sharing group, resulted when an event being exported to JSON to fill 1GB 

### Steps to reproduce the behavior

**Setting up Feed of Death** 
- Create feed (has to be able to create around 120.000 attributes)
- Target Events: Fixed
- Distribution: Sharing Group containing around 42 organizations

**Comment by iglocska** [comment]
Nice catch, thanks for the report!

**Comment by adulau** [comment]
Should we assign a CVE ?

**Comment by eCrimeLabs** [comment]
> 

It could be a potential Denial-of-Service, but I would let it be up to you 😉

**Comment by iglocska** [comment]
Think it's "just" a bug, but a rather nasty one. Similar to the "pull event as new event on each pull" snafu.
