### ISSUE TITLE
Feed pull limit

### ISSUE THREAD

**Issue by yV11** [MISP/MISP#7998]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | MacOS
| PHP version               | N/A
| MISP version / git hash   | 2.4.151
| Browser                   | Chrome, Firefox

### Support Questions
Hi, I just had to set up MISP from scratch.
After configuring the service, I tried to add a feed with the following specifications:

- type of feed: urlhaus
- source format: MISP Feed

As a filter rule, I added the following line of code:
`{"timestamp": "7d"}`
and I also tried this loc:
`{"timestamp": "7 d"}`
or this:
`{"timestamp": "7 days"}`

Regardless of which configuration I use, all events from "urlhaus" are getting pulled (250+).

My question would be the following: How can I limit the feed ingestion by date?

**Comment by JakubOnderka** [comment]
Duplicates #7968

**Comment by yV11** [comment]
@JakubOnderka It is a similar problem yes but is there a solution on how to do this? Like I asked in my request? 

And for what can you use the normal 'timestamp' field then?
