### ISSUE TITLE
Graph for related events in iBase format (external tool)

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#80]
The tool should be able to build a the necessary to be compatible with the iBase tool to show the events around around one single event and all the relations to it.

Publish this external tool as new repository inside the github MISP org.

**Comment by adulau** [comment]
@cvandeplas Just wondering, do you have any public reference for the iBase format?

**Comment by adulau** [comment]
If we don't have any specification of the iBase format, it will be difficult to create a simple export module. I'll close this issue until a format is known.
