### ISSUE TITLE
Bug: Sorting by ORG does not work on /events/index/

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#8011]
### Expected behavior

The events are sorted by ORG (so all ORG events are listed in succession). 

I expect results like:
ORG1 3 Event XXX
ORG1 7 Event XXX
ORG2 1 Event XXX
ORG2 4 Event XXX
ORG3 2 Event XXX
ORG3 8 Event XXX
ORG3 9 Event XXX

### Actual behavior

The events are not properly sorted.

### Steps to reproduce

Sort the events by clicking on "Creator Org" in the header of the table.

### Version

2.4.150

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Fixed in #8019
