### ISSUE TITLE
Feature Request: Filter & display the hour of the event creation

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#8012]
### Is your feature request related to a problem? Please describe.

We cannot filter the events taking hour into account. Producing an overview list for all events published between two SITREPs is then more difficult since all events need to be opened. 

### Describe the solution you'd like

Filter on the time in addition to the date.
Display the time in the event list (when hovering the date for example)

### Describe alternatives you've considered

Opening all events 1 by 1 to check the time. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @ancailliau 
The `date` column is stored as `DATE`, so we cannot get further details there.
However, Events keep the timestamp of the last modification and when they were published.

Do you think any of these last two attributes would be relevant to add in the events index view and filters?

**Comment by ancailliau** [comment]
Yes, definitely!

**Comment by righel** [comment]
PR #8019 implements this functionality, merged to `develop`.
