### ISSUE TITLE
Trying to Updated MISP - Unable to access 'https://github.com/MISP/MISP.git/' 

### ISSUE THREAD

**Issue by R1SK72** [MISP/MISP#8014]
### Support Questions

Hi Folks, 

Trying to update MISP instance but getting the following error. The misp instance is able to reach out to pull events through the proxy but appears to have an issue connecting to github on git.  

_____________________________________________________________
Currently installed version… v2.4.134 
Latest available version… v2.4.151 ()
Status… Outdated version
Current branch… 2.4
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1
cd $(git rev-parse --show-toplevel) && git pull origin  2>&1
fatal: unable to access 'https://github.com/MISP/MISP.git/': Failed to connect to github.com port 443: Connection timed out
=================================
cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1
_____________________________________________________________

I created the following to try and resolve the issue and believe they relate : 

Creating a proxy on Git-
**@**:/etc# git config -l
http.proxyauthmethod=basic
http.proxy=http://*.*.*.*:8080
https.proxy=http://*.*.*.*:8080

Host file entry for Github (prior to this the error was a dns lookup )
**@**:/etc# cat hosts
127.0.0.1       localhost.localdomain   localhost
::1             localhost6.localdomain6 localhost6
140.82.121.3 github.com

Any help will be greatly appreciated. 

Thanks

### MISP version

2.4.134

### Operating System

ubuntu

### Operating System version

18.04.1

### PHP version

tbc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
If I understand correctly you have a proxy configured, so the DNS lookup takes place at the proxy level. Looking at the error, it seems to be an error on the proxy level. Can you try to use `curl` with the proxy on the MISP server?

**Comment by R1SK72** [comment]
Hi Adulau, 

I tried the following  : 
curl "https://github.com"
curl "http://github.com"

and get the following response : 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to *.*.*.*:8080

Any suggestion greatly appreciated.

**Comment by adulau** [comment]
It's clearly an issue between your proxy and the TLS initial handshake. Even if it's not related to MISP, I would advise to review the config of your proxy or client. it could be the encryption handshake failing or alike. I would do `curl -v` to have more debug or even use the openssl client to see the full handshake,
