### ISSUE TITLE
Tagging at attributes level

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#802]
It would be nice to be able to tag at attributes level. This would support the ability to tag specific malware
based on their attributes, classify specific information at attribute level...

It might require a small data-model change in the table event_tags to add the UUID of an attribute in addition to the id of an event. This could be just an optional option if not set, the tag is on the whole event.

**Comment by rotanid** [comment]
https://github.com/MISP/MISP/tree/feature/attribute-tagging

**Comment by jaegeral** [comment]
cannot wait to see the merge of that branch @rotanid :-)

**Comment by iglocska** [comment]
It's my fault, taking ages getting around to testing it (even though I doubt anything needs changing). Will try to do it asap!

**Comment by adulau** [comment]
It's merged and released in [MISP 2.4.60](https://www.misp.software/2017/01/17/MISP.2.4.60.released.html).
