### ISSUE TITLE
syntax error, unexpected '['...

### ISSUE THREAD

**Issue by georgedumitru** [MISP/MISP#804]
Hello!

I've just configured MISP on a CentOS 6.7 machine (I already have a functional instance set up a few months ago on another VM and I checked the configurations) but in this case I'm getting server error 500 when accessing the web interface.

The output of tail -f /var/www/MISP/app/tmp/logs/error.log when accessing the URL is shown below. What is the issue in this situation?

Thank you,
George

![image](https://cloud.githubusercontent.com/assets/13255884/12089136/4507d568-b2ea-11e5-8ed1-e4445b3f9d61.png)

**Comment by iglocska** [comment]
Hello George,

You are using an unsupported version of php which doesn't support the direct access of array elements from a function that returns an array, please update to a supported PHP version (such as 5.5 or 5.6).

For a list of PHP versions and their support status see: https://secure.php.net/supported-versions.php

**Comment by georgedumitru** [comment]
Thank you for the tip, this solved the issue for me  :)

**Comment by iglocska** [comment]
Excellent, let me know if you run into any other issues!
