### ISSUE TITLE
Bug: Navigating to MISP Server settings and jobs page throws internal server error

### ISSUE THREAD

**Issue by djha983** [MISP/MISP#8044]
### Expected behavior

It shoud display the server seeting or jobs page

### Actual behavior

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

login to MISP web console and navigate to Administration-> Server settings and maintenance or jobs.

### Version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox,Chrome

### Browser version

95

### Relevant log output

```shell
2021-12-22 09:43:02 Error: [Error] Class 'fXmlRpc\Client' not found
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(599): BackgroundJobsTool->createSupervisorConnection()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(282): BackgroundJobsTool->getSupervisor()
#2 /var/www/MISP/app/Model/Server.php(7184): BackgroundJobsTool->getWorkers()
#3 /var/www/MISP/app/Model/Server.php(3401): Server->getWorkers()
#4 /var/www/MISP/app/Controller/ServersController.php(1166): Server->workerDiagnostics()
#5 [internal function]: ServersController->serverSettings()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
2021-12-22 09:43:06 Error: [Error] Class 'fXmlRpc\Client' not found
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(599): BackgroundJobsTool->createSupervisorConnection()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(282): BackgroundJobsTool->getSupervisor()
#2 /var/www/MISP/app/Model/Server.php(7184): BackgroundJobsTool->getWorkers()
#3 /var/www/MISP/app/Model/Server.php(3401): Server->getWorkers()
#4 /var/www/MISP/app/Controller/JobsController.php(26): Server->workerDiagnostics()
#5 [internal function]: JobsController->index()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @deepak-eventtracker 
Seems you enabled the new backend for Background Jobs, you are missing some required php packages, you should follow this guide before enabling them:
https://gist.github.com/righel/8ebc6c84341f2aea7d0bfa124e535ef8

If you enabled it by mistake, set `SimpleBackgroundJobs.enabled` to `false` in `/var/www/MISP/app/Config/config.php`

Let me know if that helps.

**Comment by djha983** [comment]
Thank You, setting SimpleBackgroundJobs.enabled to false in /var/www/MISP/app/Config/config.php resolved the issue.

Best Regards,
Deepak Jha | Technical Product Manager
T: 443.241.9568 M: +91 9844792276
Netsurion | Secure and Resilient Networks
EventTracker | Actionable Security Intelligence
