### ISSUE TITLE
Bug: SimpleBackgroundJobs configuration needs to be explicitly set

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#8050]
### Expected behavior

As mentioned in #8015 all the SimpleBackgroundJobs configuration needs to be explicitly set.

Since the settings in https://misp.local/servers/serverSettings/SimpleBackgroundJobs are all green the expected behavior is that they only need to be changed when a non-default value is set.

### Actual behavior

All settings in https://misp.local/servers/serverSettings/SimpleBackgroundJobs need to be explicitly set.

### Steps to reproduce

Set `SimpleBackgroundJobs.enabled` to false without defining any other SimpleBackgroundJobs parameters.

### Version

2.4.152

### Operating System

CentOS

### Operating System version

7

### PHP version

7.2

### Browser

Edge Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @RichieB2B 
Just merged https://github.com/MISP/MISP/pull/8053 to `develop` to make this more clear, thanks for the report.
Will look like this:
![image](https://user-images.githubusercontent.com/1659902/147250355-5a041be2-1735-499a-ab3c-40f7c5674690.png)

Let me know if that helps.

**Comment by RichieB2B** [comment]
Looks good, thanks!
