### ISSUE TITLE
Bug: cake Server pullAll no longer working

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#8051]
### Expected behavior

All servers should be pulled

### Actual behavior

PHP stack trace

### Steps to reproduce

This is because of #8050 
Even when Resque is still used `cake Server pullAll` is broken:
```
# su -s /bin/bash apache -c "/bin/scl enable rh-php72 '/var/www//MISP/app/Console/cake Server pullAll 12'"
Notice Error: Undefined property: ServerShell::$BackgroundJobsTool in [/var/www//MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]

2021-12-23 13:38:50 Notice: Undefined property: ServerShell::$BackgroundJobsTool in [/var/www//MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]
Error: Argument 1 passed to BackgroundJobsTool::__construct() must be of the type array, null given, called in /var/www//MISP/app/Console/Command/ServerShell.php on line 616
#0 /var/www//MISP/app/Console/Command/ServerShell.php(616): BackgroundJobsTool->__construct(NULL)
#1 /var/www//MISP/app/Console/Command/ServerShell.php(83): ServerShell->getBackgroundJobsTool()
#2 /var/www//MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pullAll()
#3 /var/www//MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('pullAll', Array)
#4 /var/www//MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#5 /var/www//MISP/app/Console/cake.php(45): ShellDispatcher::run(Array)
#6 {main}
```
After setting all the `SimpleBackgroundJobs` config item explicitly in `config.php` the command works again, but with PHP errors:
```
#  su -s /bin/bash apache -c "/bin/scl enable rh-php72 '/var/www//app/Console/cake Server pullAll 12'"
Notice Error: Undefined property: ServerShell::$BackgroundJobsTool in [/var/www//app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]

2021-12-23 13:35:21 Notice: Undefined property: ServerShell::$BackgroundJobsTool in [/var/www//app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]
Enqueued pulling from remote1 server as job 2dda7ae87b8e35bd4ee3b6031a9ea02b
Enqueued pulling from remote2 server as job 72632e2bfd374a33e7bff9ad83701d49
```
### Version

2.4.152

### Operating System

CentOS

### Operating System version

7

### PHP version

7.2

### Browser

Edge Chormium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jalmarikalmari** [comment]
Just started to type about similar issue but after upgrade to 2.4.151.

After upgrade MISP A and MISP B both from 2.4.150 to 2.4.151 the "cake server pull" stopped working.
No errors found (thought didn't try debug). The Pull request starts and stops OK, but no events transfered from MISP A to MISP B.
Once reverted MISP A back to 2.4.150 the pull worked.

We tried following cases:
1) Both MISPs upgraded to 2.4.151:
MISP B (2.4.151) --- pull request from B to A ---> MISP A (2.4.151)  - Pull not working

2) Reverted MISP B to 2.4.150
MISP B (2.4.150) --- pull request from B to A ---> MISP A (2.4.151) - Pull not working

3) Reverted MISP A to 2.4.150 and lifted B back to .151
MISP B (2.4.151) --- pull request from B to A---> MISP A (2.4.150) Pull STARTED to work

**Comment by righel** [comment]
Hello @RichieB2B ,
Just merged https://github.com/MISP/MISP/pull/8053 to `develop` regarding the docs to make the settings required and link the guide, as the root cause of the issue seems to be a configuration problem. 
`Notice Error: Undefined property: ServerShell::$BackgroundJobsTool in [/var/www//app/Lib/cakephp/lib/Cake/Console/Shell.php, line 514]` 
This error is actually a notice and should not affect the functionality, however it's fixed in this PR also.
Thanks for reporting.

Hello @jalmarikalmari :
Have you enabled `SimpleBackgroundJobs` also? 
If so, check the settings are properly set. Otherwise please attach some logs or create a new issue as it's probably not related.

Let me know if that helps.

**Comment by RichieB2B** [comment]
Looks good, thanks!
