### ISSUE TITLE
Can't use function return value in write context in /var/www/MISP/app/Controller/UsersController.php on line 632

### ISSUE THREAD

**Issue by zachsis** [MISP/MISP#808]
CentOS7 build following https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.centos7.txt (and https://groups.google.com/forum/#!topic/misp-users/VprS_APtsX8 to solve other bugs). does not load the application successfully. 

http://localhost:8080/ 

returns: 

Unauthorised access.
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

logs: 

==> /var/log/httpd/misp.local_error.log <==
[Mon Jan 04 23:12:59.766227 2016] [:error] [pid 5230] [client 10.0.2.2:40481] PHP Fatal error:  Can't use function return value in write context in /var/www/MISP/app/Controller/UsersController.php on line 632

==> /var/log/httpd/misp.local_access.log <==
10.0.2.2 - - [04/Jan/2016:23:12:59 +0000] "GET /users/login HTTP/1.1" 500 4267 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/roboto.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/bootstrap.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/datepicker.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/bootstrap-timepicker.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/bootstrap-colorpicker.min.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/main.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/jquery-2.1.0.min.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /css/print.css HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/bootstrap.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/bootstrap-timepicker.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/bootstrap-datepicker.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/bootstrap-colorpicker.min.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/main.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"
10.0.2.2 - - [04/Jan/2016:23:13:00 +0000] "GET /js/ajaxification.js HTTP/1.1" 304 - "http://localhost:8080/users/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36"

**Comment by iglocska** [comment]
It sounds like you are using an unsupported PHP version, please make sure that you upgrade to at least PHP 5.5. https://secure.php.net/supported-versions.php

**Comment by zachsis** [comment]
will test that out. thanks!  Also, you may want to update this doc: https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.centos7.txt as php5.5+ is not in epel or the default repo's for centos7.2.
