### ISSUE TITLE
Support: How can I use the endpoint https://<instance_url>/attributes/restSearch and get only attributes that have the specified tags.

### ISSUE THREAD

**Issue by PA-Rweins** [MISP/MISP#8081]
### Support Questions

Hi, I'm using MISP API endpoint `https://<instance_url>/attributes/restSearch` in order to retrieve attributes from MISP.
I'm using the tags parameter and I expected that the returned attributes will only be attributes that have the specified tags, however I see that some of the attributes don't have the tags and are just part of an event that have the tags.

Is there a way to make a request to the API with tags in the query such that the returned attributes will be only attributes that have the specified tags themselves?

I saw the parameter `includeEventTags`, which I'm not sure is related, but it doesn't give me the wanted behaviour as described above.

### MISP version

2.4.144 

### Operating System

Amazon Linux

### Operating System version

2

### PHP version

7.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @PA-Rweins,
This is not possible with our current implementation. Attributes inherit the Tags from their parent Event and it's equivalent to

**Comment by righel** [comment]
Hello @PA-Rweins,
This is not possible with our current implementation. Attributes inherit the Tags from their parent Event and it's equivalent to the tag actually being applied to the Attribute.
Setting `"includeEventTags": false` in the request will hide the Event Tags from the response but Attributes with a tag matching at Event level will still be returned.
