### ISSUE TITLE
maintenance admin page issue

### ISSUE THREAD

**Issue by dazed51** [MISP/MISP#8087]
### Expected behavior

I usually update the misp application via admin interface, but after the last patch I get  the error:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

This after I try and navigate to www.abc.com/servers/serverSettings/diagnostics

### Actual behavior

I normally go this this link to update this misp

 www.abc.com/servers/serverSettings/diagnostics

### Steps to reproduce

Tried to manually pull patches via git

sudo -u www-data git pull origin 2.4

sudo -u www-data git submodule update --init --recursive
 
chk'ed logs

### Version

 2.4.152 

### Operating System

Ubuntu 

### Operating System version

20.04

### PHP version

7.4.3

### Browser

firefox, chrome

### Relevant log output

```shell
2022-01-10 09:54:37 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sub' in 'field list'
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3489): DboSource->query()
#5 /var/www/MISP/app/Model/Server.php(3008): Model->query()
#6 /var/www/MISP/app/Model/Server.php(3058): Server->checkIfColumnContainsJustUniqueValues()
#7 /var/www/MISP/app/Model/Server.php(2712): Server->compareDBIndexes()
#8 /var/www/MISP/app/Controller/ServersController.php(1122): Server->dbSchemaDiagnostic()
#9 [internal function]: ServersController->serverSettings()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#14 {main}
2022-01-10 14:19:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sub' in 'field list'
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(641): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3489): DboSource->query()
#5 /var/www/MISP/app/Model/Server.php(3023): Model->query()
#6 /var/www/MISP/app/Model/Server.php(3073): Server->checkIfColumnContainsJustUniqueValues()
#7 /var/www/MISP/app/Model/Server.php(2727): Server->compareDBIndexes()
#8 /var/www/MISP/app/Controller/ServersController.php(1166): Server->dbSchemaDiagnostic()
#9 [internal function]: ServersController->serverSettings()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
```
--------

also getting this error when running the git cmd:

sudo -u www-data git submodule update --init --recursive

error: Your local changes to the following files would be overwritten by checkout:
	.bumpversion.cfg
	.travis.yml
	mixbox/compat.py
	mixbox/vendor/six.py
	mixbox/version.py
	setup.cfg
	setup.py
	test/dates_tests.py
	test/namespaces_tests.py
	tox.ini
Please commit your changes or stash them before you switch branches.
Aborting
error: Your local changes to the following files would be overwritten by checkout:
	.travis.yml
	CHANGES.txt
	docs/index.rst
	maec/utils/comparator.py
	maec/utils/deduplicator.py
	maec/version.py
	setup.cfg
	setup.py
	tox.ini
Please commit your changes or stash them before you switch branches.
Aborting
error: Your local changes to the following files would be overwritten by checkout:
	CHANGES.txt
	docs/index.rst
	setup.cfg
	setup.py
	stix/base.py
	stix/common/profiles.py
	stix/common/references.py
	stix/common/structured_text.py
	stix/version.py
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '8c17cb1ca1951380d70a4a001a43a768b9e5635b' in submodule path 'app/files/scripts/mixbox'
Unable to checkout '13e66105c9646156060d0896a4d54970ea358f44' in submodule path 'app/files/scripts/python-maec'
Unable to checkout '34f24261b70c7d02ddf0f5696d3919e771dbd32f' in submodule path 'app/files/scripts/python-stix'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kara-1234** [comment]
+1

**Comment by kara-1234** [comment]
Fixed this by clearing the cache and killing all workers before starting them back up. 

rm -f /var/www/MISP/app/tmp/cache/models/myapp*
rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*

**Comment by dazed51** [comment]
Thanks, ill give that a try. How do you start the workers again?

**Comment by kara-1234** [comment]
on the GUI: Settings -> Workers -> I did a kill all workers and then I started all of them again from that same page.

**Comment by dazed51** [comment]
Awesome, fix worked me as well. Can close this issue. Thanks again.
