### ISSUE TITLE
Feature Request: Run Enrichement module once a new attribute is added

### ISSUE THREAD

**Issue by security-intel** [MISP/MISP#8088]
### Is your feature request related to a problem? Please describe.

A lot of cool enrichment modules are currently available in misp-modules that provide quite an insight over the available iocs. In order to use any of them, a manual step is needed through the hover function, or using the "Enrich Event" option from the top left menu. The latest one allows you select the desired enticements and adds new attributes to the event, as per module capability.

The problem that this feature would fix is the need of manual intervention for each events/attributes added to the platform. Adding the option of running it automatically after the attribute was added through the UI or API, would greatly enhance the ease of use and would avoid some human error, where attributes could have been enriched, but the user simply forgot to go through the last step. As described in the next part, this will work as an optional feature, so it won't change the current workflow of the app.

### Describe the solution you'd like

When:
1) Manually adding an attribute, add the enrichment modules checkbox list at the bottom of the form, and allow the user to select any enrichment he/she may want to run automatically, right after the attribute is created. Any new data will automatically be added to the event, and for any later added attribute, there will be no need of running the "Enrich Event' option, and loop over all attributes again.

2) Using the api, to have possibility of adding a list of enrichment modules names, modules that will automatically run right after the attribute was created.

Only for the UI, a nice to have is to retain in system config the default enrichment modules that would be automatically checked when adding a new attribute - decided by the admin, considering the organization external API subscriptions, etc. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
We now have a [workflow feature in MISP](https://www.misp-project.org/2022/08/08/MISP.2.4.160.released.html/) which allows such kind of behaviour. There is a detailed[video](https://www.youtube.com/watch?v=XSvUwwu1Ku0) about the feature. I'll close the issue but feel free to reopen it.
