### ISSUE TITLE
Bug: Unable to add objects using expansion module

### ISSUE THREAD

**Issue by hildenjohannes** [MISP/MISP#8094]
### Expected behavior

After using the "Add Enrichment" action on an attribute, the attribute is enriched and the response attached to the Event as a custom object.

### Actual behavior

The job fails with the following message: 
**Processing complete. 1 object could not be saved. Reason for the failure: {"template_uuid":["Please provide a valid RFC 4122 UUID"]}**

### Steps to reproduce

This was specifically tested using the Recorded Future expansion module, but I expect any expansion module which returns an object to have this issue. This issue first appeared after upgrading our MISP environments to 2.4.152. No recent changes have been made to the Recorded Future expansion module. 

Seems quite similar to this issue: #7445 

### Version

2.4.152

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Relevant log output

```shell
Processing complete. 1 object could not be saved. Reason for the failure: {"template_uuid":["Please provide a valid RFC 4122 UUID"]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Good catch! 

It's indeed a new enforcement in MISP core.

We just updated the recorded future module (as there is no fixed MISP object template for recorded future):

https://github.com/MISP/misp-modules/commit/2874c41f7f34d1233c6f266af83f0d291100fee1

Could you update your MISP modules and do a test? As we don't have any account on recorded future, we cannot really test.

Let us know if this works for you.

**Comment by hildenjohannes** [comment]
Will do and get back to you!

**Comment by mattiasr** [comment]
Hi, Co-worker to @hildenjohannes , I updated our misp-modules and now i it's working

**Comment by hildenjohannes** [comment]
@adulau Thank you very much!

**Comment by adulau** [comment]
Thanks a lot for your feedback and glad everything went fine. Enjoy your weekend.
