### ISSUE TITLE
Bug: Taxonomy Library: Nothing to pick

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#8097]
### Expected behavior

Existing and updated tags available for use in taxonomy dropdown.

### Actual behavior

Nothing to pick shown instead of taxonomy dropdown.

### Steps to reproduce

1. Make spelling corrections to a taxonomy file (no structural changes).
2. Incrementing the version number.
3. Install the updated `machinetag.json` over the top of the existing
4. Fix file ownership and SELinux context if required.
5. Click Update Taxonomies in `/taxonomies`
6. Click Enable All next to tag count
7. Create a new event and try to use the taxonomy.

### Version

2.4.152

### Operating System

CentOS

### Operating System version

7.9.2009

### PHP version

7.4.27

### Browser

Chrome

### Browser version

97.0.4692.71

### Relevant log output

```shell
No mention of taxonomy name in any logs in /var/www/MISP/app/tmp/logs/
```

### Extra attachments

Taxonomy on taxonomies page:
![image](https://user-images.githubusercontent.com/60189659/149555481-af29c1c5-0ab7-405b-a4af-79dddd2d177a.png)

Taxonomy Library on event page:
![image](https://user-images.githubusercontent.com/60189659/149555572-5a7608c8-b440-43d0-b1a1-b05b354bf4fa.png)

I have tried deleting the taxonomy in MISP and rerunning update with the same result.
Opening the taxonomy from `/taxonomies` shows all the tags and all have a tick under enabled, suggesting the file is valid.
Clicking on a tag from the taxonomy correctly searches for events with that tag, but even those events show 'Nothing to pick' when the taxonomy is selected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoePJisc** [comment]
Browsing the database manually I can see my taxonomy correctly loaded into the `taxonomies`, `taxonomy_predicates` and `taxonomy_entries` tables - including the spelling corrections made in the version.

**Comment by marjatech** [comment]
Have you checked the according tags for restrictions to org/user or hidden/local_only?

**Comment by JoePJisc** [comment]
Hi @marjatech, sorry for the delay, I've just had a look and they are all showing as local-only; how do I clear this?

Thanks

**Comment by JoePJisc** [comment]
More accurately, how do I clear this for the whole taxonomy without clicking into each tag, unticking, saving and repeating.
