### ISSUE TITLE
Graph for related events for Maltego integration 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#81]
The goal is to be able to generate mgtx files (Maltego) that are compatible with Maltego to be imported.

This can be done in a separate tool or inside MISP.

**Comment by adulau** [comment]
I suppose this can now be done as an export misp-module. There is also the correlation graph too. Not sure if we want to keep this issue or not.

**Comment by adulau** [comment]
I suppose the following tools solved the issue:

- https://github.com/MISP/MISPego
- https://github.com/MISP/MISP-maltego/

I'll close the issue. Feel free to reopen if the above external tools are not solving the issue.
