### ISSUE TITLE
Bug: Adding sharing group selection option to feeds

### ISSUE THREAD

**Issue by Sru3l** [MISP/MISP#8101]
### Expected behavior

When adding a new FEED, i am not able to select to which sharing group i would like the feed data to be shared with 
For example i can only select SHARING GROUP but i do not know which group it will select and how to change that
![image](https://user-images.githubusercontent.com/97922086/149846859-614a35e4-9e3a-49aa-838b-2b6e17f034ad.png)

### Actual behavior

Would like to have another menu added beside the sharing group in the feed option to select a sharing group like when adding a MISP EVENT 
Actual
![image](https://user-images.githubusercontent.com/97922086/149846903-999dcb5d-4282-4b84-9afe-76978d183876.png)

Desired (for new FEED)
![image](https://user-images.githubusercontent.com/97922086/149846940-1cc843ff-d4a2-45d4-9398-987de0f4c01f.png)

### Steps to reproduce

Add the sharing group menu

### Version

2.4.147

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @Sru3l 
This issue was already reported: https://github.com/MISP/MISP/issues/7807 and fixed in MISP version `2.4.150`.
I suggest you to update your MISP version and it will be fixed.

I'll close the issue, if the error persist, feel free to re-open it.
