### ISSUE TITLE
An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by thansau239** [MISP/MISP#811]
I am receiving the following error on the homepage:
"An Internal Error Has Occurred."
"Error: An Internal Error Has Occurred."

when I navigate to events/export.
This is log:
2016-01-06 14:10:28 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'org' in 'where clause'
Request URL: /events/export
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Job`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `Job`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `Job`.`i...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Job), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/EventsController.php(1579): Model->find('first', Array)
#7 [internal function]: EventsController->export()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-01-06 14:10:38 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'org' in 'where clause'
Request URL: /events/export
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Job`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `Job`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1118): DboSource->fetchAll('SELECT `Job`.`i...', false)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Job), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/EventsController.php(1579): Model->find('first', Array)
#7 [internal function]: EventsController->export()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by iglocska** [comment]
That looks like an outdated version, which version are you on?

**Comment by thansau239** [comment]
Hi @iglocska  i'm running version 2.4.0

**Comment by iglocska** [comment]
That version is a bit outdated, could you git pull and retest it whether the issue is still there?

**Comment by thansau239** [comment]
HI @iglocska How to upgrade? please help me

**Comment by thansau239** [comment]
@iglocska thank for your suport, it's run smooth
