### ISSUE TITLE
Unable to edit user if using external authentication

### ISSUE THREAD

**Issue by chais0n** [MISP/MISP#8116]
### Expected behavior
Edit local MISP user while being authenticated via external mechanism. I would expect the "Confirm with current password" field to either query the OAuth backend since I'm logged in via that method. Or I would expect that it is not required for external authentication types.

### Actual behavior
Password confirmation for the editor fails with the following error "Please enter your current password to continue.". As a result, if we need to update the role we have to delete the account and recreate which breaks any apps using teh API token until they update their app with the new user's token. 

### Steps to reproduce
1. Confirgure MISP to use OAuth authentication. (we use Keycloak)
2. Log in as a user with administrator privs
3. Create a local api/sync user account
4. Assign the necessary role and click save
5. Edit user and change role
6. Any modification to the user fails due to not being able to confirm the editors password (Oauth)
7. Leaving confirmation password blank also results in an error

### Version
2.4.151

### Operating System
Ubuntu (Docker)

### Operating System version
20.04

![misp-error](https://user-images.githubusercontent.com/69157314/151531546-411a0458-eb34-48ef-9323-e1ad67ec7ed9.PNG)

**Comment by JakubOnderka** [comment]
Hello, you can disable this confirmation by setting `MISP.require_password_confirmation` to `false`.

**Comment by chais0n** [comment]
@JakubOnderka I was looking for an option like this, but couldn't find it. Thank you!
