### ISSUE TITLE
Feature Request: Add IP in authentication logs in MISP 

### ISSUE THREAD

**Issue by yodresh** [MISP/MISP#8119]
### Is your feature request related to a problem? Please describe.

The IP of the user is logged only when authentication is failed, but never when authentication is successful.

Only Successful Login
![image](https://user-images.githubusercontent.com/1607556/151998888-24098152-f085-403e-baf3-5332a6751b6a.png)

Failed & Successful login
![image](https://user-images.githubusercontent.com/1607556/151999163-69da5e7b-a0e3-4094-9bb0-4e8ec948ed56.png)

### Describe the solution you'd like

Log the IP for all authentications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Enable the `MISP.log_client_ip` setting in administration -> server settings -> MISP tab.

**Comment by yodresh** [comment]
Thank you for the quick feedback didn't found this by myself...
