### ISSUE TITLE
Bug: [RedisException] Connection refused Request URL: /servers/serverSettings

### ISSUE THREAD

**Issue by clopmz** [MISP/MISP#8138]
### Expected behavior

Access to "Server Settings" and "Jobs" options

### Actual behavior

I can not access to "Server Settings" and "Jobs" options

### Steps to reproduce

Login in MISP and try to access "Server Settings" or "Jobs" options

### Version

2.4.153

### Operating System

RedHat Enterprise Linux 

### Operating System version

8.5

### PHP version

7.4.27

### Browser

Edge, Chrome and Firefox

### Browser version

Any version

### Relevant log output

```shell
error.log output:

2022-02-09 18:01:44 Error: [RedisException] Connection refused
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect()
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct()
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(153): Resque::redis()
#5 /var/www/MISP/app/Plugin/CakeResque/Lib/CakeResque.php(342): Resque::size()
#6 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(321): CakeResque::getQueueSize()
#7 /var/www/MISP/app/Model/Server.php(3497): BackgroundJobsTool->getQueueSize()
#8 /var/www/MISP/app/Controller/ServersController.php(1210): Server->workerDiagnostics()
#9 [internal function]: ServersController->serverSettings()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
```

### Extra attachments

redis-cli monitor output:

1644429945.922589 [0 172.22.58.6:39828] "SELECT" "12"
1644429945.922842 [12 172.22.58.6:39828] "EXISTS" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls"
1644429945.923051 [12 172.22.58.6:39828] "SELECT" "12"
1644429945.923280 [12 172.22.58.6:39828] "SET" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls_LOCK" "mispsrv.mydom.org|26688" "NX" "PX" "30000"
1644429945.923495 [12 172.22.58.6:39828] "GET" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls"
1644429945.924542 [0 172.22.58.6:39830] "SELECT" "13"
1644429945.924806 [13 172.22.58.6:39830] "SETEX" "misp:ip_user:172.22.55.4" "2592000" "1"
1644429945.924820 [13 172.22.58.6:39830] "SADD" "misp:user_ip:1" "172.22.55.4"
1644429945.928021 [13 172.22.58.6:39830] "GET" "misp:live"
1644429945.931429 [13 172.22.58.6:39830] "SETEX" "misp:ip_user:172.22.55.4" "2592000" "1"
1644429945.931444 [13 172.22.58.6:39830] "SADD" "misp:user_ip:1" "172.22.55.4"
1644429945.933043 [13 172.22.58.6:39830] "GET" "misp:live"
1644429945.941200 [12 172.22.58.6:39828] "SELECT" "12"
1644429945.941439 [12 172.22.58.6:39828] "GET" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls_LOCK"
1644429945.941645 [12 172.22.58.6:39828] "SETEX" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls" "3600" "\x00\x00\x00\x02\x14\x04\x11\x06Config\x14\x03\x11\tuserAgent\x11 7e94aa2444f53fb9990bead3fd943a97\x11\x04time\nb\x04\x10\x89\x11\tcountdown\x06\n\x11\x06_Token\x14\x05\x11\x03key\x11 a8ec26d382cde6f10f2b9e61400abe7a\x11\x12allowedControllers\x14\x00\x11\x0eallowedActions\x01\x03\x11\x0eunlockedFields\x01\x03\x11\ncsrfTokens\x14 \x11 612fb89def2eb31326df9d28331bc945\nb\x04\x02\x9a\x11 319327196b79c37087d6db38139a4c2b\nb\x04\x03T\x11 4cd5ab0ccb3afb4a0d3e7f03f2d69c4b\nb\x04\x03`\x11 5b0b305e06337169267633a63bf5b27b\nb\x04\x03`\x11 8f58f0e2bbaea4c779dce045c748e463\nb\x04\x03`\x11 f4f319a401269329d6e3a24d34d208b5\nb\x04\x03j\x11 95544579ca9745aed7abe94f354383f1\nb\x04\x03m\x11 799fec67018b6c26f599ae6a6a205e77\nb\x04\x03p\x11 40569c7f291199771246c04897d92f6f\nb\x04\x03\x7f\x11 f679594d789b83f73404d444b99ff698\nb\x04\x03\x8f\x11 5904049b1138f6f5ed6a5774e3caee85\nb\x04\x03\xe1\x11 4836bb72cd449f078ea4e6a7a195905e\nb\x04\x03\xec\x11 2254d689f6c6aa55d7abc0782cb453dd\nb\x04\x03\xff\x11 b7b694930634f549fc064a0b92101e29\nb\x04\x048\x11 063737cb1dfab1d8bd260a0907db775f\nb\x04\x04B\x11 aee187dc246ca21e49031049e214c7e2\nb\x04\x04B\x11 14c1f7f40a42a995ba8c9014de4ce0f7\nb\x04\x04V\x11 8e2519707e64522db9630c005096a5d3\nb\x04\x04V\x11 ea668ec5499e32c16cd350322c54c4b5\nb\x04\x04\xac\x11 fb510039451b496dd722fdc97951dcbf\nb\x04\x04\xb7\x11 8b312a21bfbbcf6a08062e9c8e27d451\nb\x04\x04\xbc\x11 43d8489ea4eb7c2ee6ed5afca44c78d6\nb\x04\x04\xe7\x11 81e2cb628fac9a3eac70e7ebe0c84927\nb\x04\x05\xa5\x11 2120d1e94031f945de0555d90c1057d0\nb\x04\x05\xa5\x11 2f9fe8c4915355062b46210afb1ce54c\nb\x04\x05\xa5\x11 457378d74a1db88380f4f9bedffee3cf\nb\x04\x05\xaa\x11 15acc6e9fdf01621e82a740f7b4cfdcd\nb\x04\x05\xad\x11 e2a8b939bb7743725f52a48a2460cc57\nb\x04\x05\xaf\x11 bec08c58818925c8f1e51e4f6b7bf639\nb\x04\x05\xb1\x11 7d68eb653cb4a1fbd1c1f061c10f28f3\nb\x04\x05\xba\x11 d5be80e095f3f2de5be0288e182c9456\nb\x04\b\x90\x0e\a\nb\x04\t\x81\x11\x04Auth\x14\x01\x11\x04User\x14\x17\x11\x02id\x11\x011\x11\x06org_id\x0e.\x11\tserver_id\x11\x010\x11\x05email\x11\x17admin.cti@mydom.org\x11\tautoalert\x04\x11\ninvited_by\x0e1\x11\bnids_sid\x11\a4000000\x11\rtermsaccepted\x04\x11\bnewsread\x0e1\x11\arole_id\x0e.\x11\tchange_pw\x04\x11\x0ccontactalert\x04\x11\bdisabled\x04\x11\nexpiration\x00\x11\rcurrent_login\x11\n1644425475\x11\nlast_login\x0e1\x11\x0cforce_logout\x04\x11\x0cdate_created\x00\x11\rdate_modified\x11\n1644425521\x11\x03sub\x00\x11\x04Role\x14 \x0e-\x0e.\x11\x04name\x11\x05admin\x11\acreated\x11\x132022-02-09 16:35:05\x11\bmodified\x0eK\x11\bperm_add\x05\x11\x0bperm_modify\x05\x11\x0fperm_modify_org\x05\x11\x0cperm_publish\x05\x11\rperm_delegate\x05\x11\tperm_sync\x05\x11\nperm_admin\x05\x11\nperm_audit\x05\x11\tperm_auth\x05\x11\x0fperm_site_admin\x05\x11\x12perm_regexp_access\x05\x11\x0bperm_tagger\x05\x11\rperm_template\x05\x11\x12perm_sharing_group\x05\x11\x0fperm_tag_editor\x05\x11\rperm_sighting\x05\x11\x14perm_object_template\x05\x11\x0cdefault_role\x04\x11\x0cmemory_limit\r\x11\x12max_execution_time\r\x11\x18restricted_to_site_admin\x04\x11\x10perm_publish_zmq\x05\x11\x12perm_publish_kafka\x05\x11\rperm_decaying\x05\x11\x12enforce_rate_limit\x04\x11\x10rate_limit_count\x0e1\x11\x12perm_galaxy_editor\x05\x11\x10perm_warninglist\x04\x11\x0cOrganisation\x14\x0e\x0e-\x0e.\x0eH\x11\nUXDom Ltd.\x0eC\x11\x132022-02-09 16:47:29\x0eD\x0ek\x11\x0bdescription\x11*Automatically generated admin organisation\x11\x04type\x11\x05ADMIN\x11\x0bnationality\r\x11\x06sector\x00\x11\ncreated_by\x0e1\x11\x04uuid\x11$6f20f72d-b6f8-4ec4-a464-c77f34921a32\x11\bcontacts\x00\x11\x05local\x05\x11\x14restricted_to_domain\x00\x11\x0blandingpage\x00\x11\x06Server\x14\x19\x0e-\x00\x0eH\x00\x11\x03url\x00\x11\aauthkey\x00\x0e/\x00\x11\x04push\x00\x11\x04pull\x00\x11\x0epush_sightings\x00\x11\x14push_galaxy_clusters\x00\x11\x14pull_galaxy_clusters\x00\x11\x0clastpulledid\x00\x11\x0clastpushedid\x00\x11\x0corganization\x00\x11\rremote_org_id\x00\x11\x15publish_without_email\x00\x11\x0funpublish_event\x00\x11\x0bself_signed\x00\x11\npull_rules\x00\x11\npush_rules\x00\x11\tcert_file\x00\x11\x10client_cert_file\x00\x11\binternal\x00\x11\nskip_proxy\x00\x11\x0fcaching_enabled\x00\x11\bpriority\x00\x11\aMessage\x14\x00"
1644429945.942353 [12 172.22.58.6:39828] "SELECT" "12"
1644429945.942535 [12 172.22.58.6:39828] "EVALSHA" "b70c2384248f88e6b75b9f89241a180f856ad852" "1" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls_LOCK" "mispsrv.mydom.org|26688"
1644429945.942567 [12 lua] "get" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls_LOCK"
1644429945.942581 [12 lua] "del" "PHPREDIS_SESSION:ul9fbijt3m9rij4bhrvf3ap3s755qpls_LOCK"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
SE linux is most likely blocking you, don’t forget to set the following:

‘ sudo setsebool -P httpd_can_network_connect on’

**Comment by clopmz** [comment]
Thanks @iglocska but selinux is disabled in this host.

**Comment by clopmz** [comment]
Problem is solved @iglocska .... Issue was with 'Redis' => array in /var/www/MISP/app/Plugin/CakeResque/Config/config.php file ... Changing 127.0.0.1 by my real redis server, it works!

But my question is why?

**Comment by iglocska** [comment]
Ah ok yeah that makes sense. By default (for the default installation instructions) we assume that redis is reachable via 127.0.0.1 - in case that's not possible MISP will not be able to connect to your redis server. It could be related to how redis is binding.

**Comment by clopmz** [comment]
Ok, perfect. Issue solved.
