### ISSUE TITLE
Problems in export functionality

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#815]
Hi there, 

Using MISP 2.4.5 in the export functionality, all types seem to be queued and are not updated via the scheduled task. Any ideas?

Thanks in advance,
Andreas

**Comment by elhoim** [comment]
Do you  have the scheduler worker running?
What is the date of the last run of the export scheduled task?

**Comment by advancedeng** [comment]
Yes, scheduler worker is running.
Next run is scheduled for tomorrow (it is done on a daily basis).
Last run of the export scheduled task : 54 job(s) started at 23/12/2015 - 10:47:50

**Comment by iglocska** [comment]
Looking into this now!

**Comment by jigsawsecurity** [comment]
The export appears to work but the status in the Export window when the jobs is running does not show the percentage when the jobs are running.

**Comment by iglocska** [comment]
Will look into that at a later point in time, the issue that advancedeng describes has to do with an invalid job call by the task scheduler. I am working on a fix for it.

**Comment by adulau** [comment]
Is this issue still applicable? Could you test with a recent version? I'll close the issue but feel free to reopen if the issue persists. Thank you.
