### ISSUE TITLE
Support: Blank page is showing

### ISSUE THREAD

**Issue by bilalsarwar16** [MISP/MISP#8150]
### Support Questions

page showing blank after MISP installatio
![error](https://user-images.githubusercontent.com/99896232/154515176-e6cf20d9-c0bd-4038-924e-363286214eb7.PNG)
n.

### MISP version

2.4.153

### Operating System

Ubuntu

### Operating System version

20.04.3

### PHP version

7.4.3

### Browser

Firefox

### Browser version

97.0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @bilalsarwar16
Could you please attach the relevant bits of the error log file located in `/var/www/MISP/app/tmp/logs/error.log` ?

**Comment by bilalsarwar16** [comment]
issue has been resolved.
    On Thursday, March 3, 2022, 02:40:33 PM GMT+5, Luciano Righetti ***@***.***> wrote:  
 
 


Hello @bilalsarwar16
Could you please attach the relevant bits of the error log file located in /var/www/MISP/app/tmp/logs/error.log ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
