### ISSUE TITLE
MISP Configuration UI Issue

### ISSUE THREAD

**Issue by jigsawsecurity** [MISP/MISP#816]
Had a report today on a server and confirmed on 2 other instances that when making configuration changes it takes entering the changes in the MISP configuration UI twice for it to actually write the changes to the config.php file. 

Appears to only be an issue with 2.4.x.

**Comment by iglocska** [comment]
It is enough to enter it once, but the setting won't immediately take. If
you refresh the page 1-2 seconds after making the change it will show up.

**Comment by advancedeng** [comment]
I can confirm what iglocska says, have seen it many times

**Comment by cvandeplas** [comment]
This UI behaviour should be considered as minor bug.

**Comment by Rafiot** [comment]
Or if it never changes, it is probably related to this bug (permissions): https://github.com/MISP/MISP/issues/837

**Comment by Rafiot** [comment]
Cake related, not sure we can fix it.
