### ISSUE TITLE
[Bug] Warning list update not reflected in search

### ISSUE THREAD

**Issue by 01dr1ch** [MISP/MISP#8171]
### Expected behavior

Once user updates (no matter if org admin, site admin or plain user with Warning Lists permissions) particular Warning list, an entry added should be visible in search results and in Event Attributes (triangle with exclamation mark).

### Actual behavior

Unless administrator clicks "Update warninglists" on left menu, the added items are not reflected in search results.

### Steps to reproduce

List updated:
![image](https://user-images.githubusercontent.com/82970780/155721362-13f60907-47e2-4a2f-97ae-3393713b2494.png)

Search results don't contain the item:
![image](https://user-images.githubusercontent.com/82970780/155721091-5fbf910e-4018-49d8-86ec-0af54290cdb1.png)

Updating warninglists:
![image](https://user-images.githubusercontent.com/82970780/155721449-8e45ef05-b2b6-4def-b0a3-c46613ef075c.png)
![image](https://user-images.githubusercontent.com/82970780/155721477-6bf6fa26-ede1-49c2-b343-9dd82a2ff0d3.png)

Ta-daa:
![image](https://user-images.githubusercontent.com/82970780/155721610-86b256a6-3555-4a2a-bbeb-e1feef5415b3.png)

I waited 1 hour and the item was still not reflected until I updated warninglists through left menu.

### Version

2.4.152

### Operating System

RHEL

### Operating System version

7.9

### PHP version

7.4.26

### Browser

Chrome

### Browser version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Fixed in develop branch, thanks for report!
