### ISSUE TITLE
Irrelevant events in exported CSV (includeContext=true)

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#818]
Hi Andras, 

While trying to export to CSV (includecontext=true) the indicators of the last 150 days, I get a lot of irrelevant ones (e.g. event with uuid = 53f59e0c-ae18-495d-b574-a57b950d2109).
This event is dating back to 19/08/2014 and the last date of all its indicators is 21/08/2014.

Any idea why the exported CSV contains these events?

Cheers,
Andreas

**Comment by iglocska** [comment]
Looking at that particular event, it was updated in december 2015. The "last" field in the exports uses the timestamp (which is based on the last modification instead of the date field that is set).

**Comment by advancedeng** [comment]
Yes, this might be the case. My question is what was the update?

- additional tags maybe?
- upgrade24 script?
- viper script for checking VT links (although this one was not enriched with VT information)?

Andreas

**Comment by iglocska** [comment]
I see what you mean. Weird, from the logs it looks like it was just
republished. Do you see the same behaviour with more than one event?

**Comment by iglocska** [comment]
Looking around it seems to be an isolated case of the event being
republished.

**Comment by elhoim** [comment]
What about the following cases:
- an attribute is added then deleted?
- subject is changed?
- proposal to the event was added then deleted?

**Comment by iglocska** [comment]
Attribute added then deleted counts as an event change.
Subject changed is an event change.
Proposal added then deleted is not an event change (an accepted proposal is though.

I think this is pretty ok, but from what I can tell the event was manually edited (with no actual changes, just edit -> submit) and then published. I think we need a mechanism that would block such a situation from updating the event timestamp.

**Comment by elhoim** [comment]
@advancedeng any update on this?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
