### ISSUE TITLE
Bug: v2.4.154: update db_schema.json to version 80

### ISSUE THREAD

**Issue by skalvaro** [MISP/MISP#8181]
### Expected behavior

Database schema diagnostic would use the actual version '80' after update.

### Actual behavior

Database schema diagnostic is still using version '79' to compare with giving a mismatch.
expected db_version:79
actual db_version:80

### Steps to reproduce

Update a version prior to v2.4.154 to v2.4.154 (c66d718a0904e08fc66b4e13bed2270be8db700f)

### Version

2.4.154

### Operating System

RedHat

### Operating System version

7

### PHP version

7.2

### Extra attachments

![image](https://user-images.githubusercontent.com/10258537/156356692-4d66269a-b66b-4231-a680-2ec46ce7665f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 01dr1ch** [comment]
See #8000 please. Missing perm_warninglist (tab: roles) in the schema.

**Comment by skalvaro** [comment]
Updating to v2.4.155 solves this particular issue.
