### ISSUE TITLE
Bug: Feed can't be changed from Fixed Event to New Event and vie versa

### ISSUE THREAD

**Issue by josephka3** [MISP/MISP#8192]
### Expected behavior

On List Feeds page, when we try to edit a feed and change the Target Event value between "New Event Each Pull" and  "Fixed Event", we should be able to switch between them.

### Actual behavior

The edit does not take effect although it says feed updated.
It will show "New Event Each Pull" and  "Fixed Event" depending upon what it was set to during Add feed phase.
So basically edit doesn't work in this case

### Steps to reproduce

try switching it on a test feed

### Version

2.4.153

### Operating System

centos

### Operating System version

7

### PHP version

PHP 7.4.27 

### Browser

chrome

### Browser version

99.0.4844.51

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @josephka3 
Thanks for reporting, there was indeed a bug that prevented the `fixed_event` and `target_event` properties to be updated on Feeds. 

Pushed a fix in `develop` branch: https://github.com/MISP/MISP/commit/e33ac3d7d0be9ff3124e861506cb1374412b97ab
