### ISSUE TITLE
Bug: Background jobs starting with error

### ISSUE THREAD

**Issue by amuehlem** [MISP/MISP#8195]
### Expected behavior

the background jobs should start without any errors, so supervisord can start them.

### Actual behavior

manually trying to start a worker, throws an exception:

2022-03-07 12:58:13 Info: [WORKER PID: 130625][cache] - starting to process background jobs...
Error: Call to a member function blpop() on null
#0 /var/www/MISP/app/Console/Command/StartWorkerShell.php(65): BackgroundJobsTool->dequeue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(462): StartWorkerShell->main()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#5 {main}

### Steps to reproduce

try to start a background job manually

e.g. su - apache -s /bin/bash -c "/var/www/MISP/app/Console/cake start_worker cache"

### Version

2.4.155

### Operating System

RHEL

### Operating System version

8.5

### PHP version

7.4.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @amuehlem 
Seems there is some issue with your Redis connection. Please check the redis connection settings under `/servers/serverSettings/SimpleBackgroundJobs` are set and correct:
![image](https://user-images.githubusercontent.com/1659902/157040217-7adb44f2-49f1-4901-9cdd-b6922aba304f.png)
Exact values can be different in your setup.

If those are OK, I would suggest checking if Redis is running, this comment can help you with that: https://github.com/MISP/MISP/issues/8003#issuecomment-984444927

The migration guide can be found here: 
https://github.com/MISP/MISP/blob/2.4/docs/background-jobs-migration-guide.md

Let me know if that helps.

**Comment by JoePJisc** [comment]
I'm experiencing this issue too.

Clean install of MISP v2.4.157 on RHEL8 using MISP-RPM.

Post install I've done the following per https://github.com/MISP/MISP/blob/2.4/docs/background-jobs-migration-guide.md

* Created the Supervisor Listener: `sudo vi /etc/supervisord.d/misp-server.ini`

```ini
[inet_http_server]
port=127.0.0.1:9001
username=supervisor
password=securePasswordHere
```

* Enable and start supervisord:

```sh
sudo systemctl enable supervisord
sudo systemctl start supervisord
```

* checking supervisor status

```sh
sudo supervisorctl status
misp-workers:cache_00            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_01            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_02            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_03            FATAL     Exited too quickly (process log may have details)
misp-workers:cache_04            FATAL     Exited too quickly (process log may have details)
misp-workers:default_00          FATAL     Exited too quickly (process log may have details)
misp-workers:default_01          FATAL     Exited too quickly (process log may have details)
misp-workers:default_02          FATAL     Exited too quickly (process log may have details)
misp-workers:default_03          FATAL     Exited too quickly (process log may have details)
misp-workers:default_04          FATAL     Exited too quickly (process log may have details)
misp-workers:email_00            FATAL     Exited too quickly (process log may have details)
misp-workers:email_01            FATAL     Exited too quickly (process log may have details)
misp-workers:email_02            FATAL     Exited too quickly (process log may have details)
misp-workers:email_03            FATAL     Exited too quickly (process log may have details)
misp-workers:email_04            FATAL     Exited too quickly (process log may have details)
misp-workers:prio_00             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_01             BACKOFF   Exited too quickly (process log may have details)
misp-workers:prio_02             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_03             FATAL     Exited too quickly (process log may have details)
misp-workers:prio_04             FATAL     Exited too quickly (process log may have details)
misp-workers:update_00           FATAL     Exited too quickly (process log may have details)
```

`/var/log/supervisor/supervisord.log` shows these three lines over and over for each worker:

```log
INFO spawned: 'prio_01' with pid 11617
INFO success: prio_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO exited: prio_01 (exit status 1; not expected)
```

and there are some lines like this one:

```log
INFO gave up: default_00 entered FATAL state, too many start retries too quickly
```

`/var/www/MISP/app/tmp/logs/misp-workers-errors.log` is also full of:

```log
Error: Call to a member function blpop() on null
#0 /var/www/MISP/app/Console/Command/StartWorkerShell.php(65): BackgroundJobsTool->dequeue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(462): StartWorkerShell->main()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
```

`SimpleBackgroundJobs.enabled` is still set to False per the above doc, but all settings are correct - the Redis settings match the `MISP.redis...` settings, and the Diagnostics page show the main connection to redis is operational; `curl` also shows that the supervisord listener is up.

**Comment by JoePJisc** [comment]
Ignoring the FATAL statuses and setting `SimpleBackgroundJobs.enabled` to True, has fixed the issue.

`sudo supervisorctl status` now shows:


```misp-workers:cache_00            RUNNING   pid 27596, uptime 0:00:07
misp-workers:cache_01            RUNNING   pid 27597, uptime 0:00:07
misp-workers:cache_02            RUNNING   pid 27598, uptime 0:00:07
misp-workers:cache_03            RUNNING   pid 27599, uptime 0:00:07
misp-workers:cache_04            RUNNING   pid 27614, uptime 0:00:07
misp-workers:default_00          RUNNING   pid 27586, uptime 0:00:07
misp-workers:default_01          RUNNING   pid 27587, uptime 0:00:07
misp-workers:default_02          RUNNING   pid 27588, uptime 0:00:07
misp-workers:default_03          RUNNING   pid 27589, uptime 0:00:07
misp-workers:default_04          RUNNING   pid 27590, uptime 0:00:07
misp-workers:email_00            RUNNING   pid 27591, uptime 0:00:07
misp-workers:email_01            RUNNING   pid 27592, uptime 0:00:07
misp-workers:email_02            RUNNING   pid 27593, uptime 0:00:07
misp-workers:email_03            RUNNING   pid 27594, uptime 0:00:07
misp-workers:email_04            RUNNING   pid 27595, uptime 0:00:07
misp-workers:prio_00             RUNNING   pid 27615, uptime 0:00:07
misp-workers:prio_01             RUNNING   pid 27616, uptime 0:00:07
misp-workers:prio_02             RUNNING   pid 27617, uptime 0:00:07
misp-workers:prio_03             RUNNING   pid 27619, uptime 0:00:07
misp-workers:prio_04             RUNNING   pid 27620, uptime 0:00:07
misp-workers:update_00           RUNNING   pid 27626, uptime 0:00:07
```

**Comment by righel** [comment]
Hello @JoeP-oss
There was probably something wrong with the configuration. Did you check the `/var/www/MISP/app/tmp/logs/error.log` log file? There might be something there.

Glad it worked in the end.
