### ISSUE TITLE
Update 2.3->2.4 cakephp checkout error

### ISSUE THREAD

**Issue by west791** [MISP/MISP#820]
Hello, 

I had the following error updating my 2.3 to 2.4 in step "git submodule update" (line 9):
Konnte '4de92123fa453f5e5eedd001a8918ad2976436af' in Submodul-Pfad 'app/Lib/cakephp' nicht auschecken.
(Couldn't checkout '<number>' in submodule path 'app/Lib/cakephp')
Unfortunately this seems to be necessary, as the instance now returns an empty web page. 

Greetings

west

**Comment by iglocska** [comment]
That is very odd.

Could you try to remove your cakephp lib first (rm -R /var/www/MISP/app/Lib/cakephp) and then reinitialise the submodule?

git submodule init
git submodule update

Does this fix it for you?

**Comment by west791** [comment]
Thanks for the fast response!

Actually, it does, the module gets checked out. But when continuing the update, the instance continues to show me the empty page (so I cannot access the upgrade script in the application).

**Comment by iglocska** [comment]
Could you check /var/www/MISP/app/tmp/error.log what the last entry is and paste that here? Might be some permission issues.

**Comment by west791** [comment]
The problem seems to be somewhere here I think: 

2016-01-07 09:42:13 Warning: Warning (2): include() [<a href='http://php.net/function.include'>function.include</a>]: Failed opening '/var/www/MISP/app/Controller/EventsController.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php, line 547]
Trace:
App::load() - APP/Lib/cakephp/lib/Cake/Core/App.php, line 547
App::load() - APP/Lib/cakephp/lib/Cake/Core/App.php, line 547
spl_autoload_call - [internal], line ??
class_exists - [internal], line ??
Dispatcher::_loadController() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 266
Dispatcher::_getController() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 235
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 158
[main] - APP/webroot/index.php, line 92

2016-01-07 09:42:13 Error: [MissingControllerException] Controller class EventsController could not be found.
Exception Attributes: array (
  'class' => 'EventsController',
  'plugin' => NULL,
)
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2016-01-07 09:42:13 Warning: Warning (2): include() [<a href='http://php.net/function.include'>function.include</a>]: Failed opening '/var/www/MISP/app/View/Layouts/default.ctp' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php, line 961]
Trace:
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 961
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 961
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 923
View::renderLayout() - APP/Lib/cakephp/lib/Cake/View/View.php, line 546
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 481
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 960
ExceptionRenderer::_outputMessage() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 289
ExceptionRenderer::error400() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 233
ExceptionRenderer::render() - APP/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php, line 187
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 127
[main] - [internal], line ??

**Comment by iglocska** [comment]
That sounds a lot like permission issues, could you run this?

chown -R root:www-data /var/www/MISPfind /var/www/MISP -type d -exec chmod
g=rx {} \;chmod -R g+r,o= /var/www/MISPchown www-data:www-data
/var/www/MISP/app/fileschown www-data:www-data
/var/www/MISP/app/files/termschown
www-data:www-data /var/www/MISP/app/files/scripts/tmpchown
www-data:www-data /var/www/MISP/app/Plugin/CakeResque/tmpchown -R
www-data:www-data /var/www/MISP/app/tmpchown -R www-data:www-data
/var/www/MISP/app/webroot/img/orgschown -R www-data:www-data
/var/www/MISP/app/webroot/img/custom

**Comment by west791** [comment]
This fixed it. I can now access the page. One tiny final question : how do I set the Misp.live option? It wont change if I set it in the admin page, is there a file I can set it in?

**Comment by iglocska** [comment]
The file is in /var/www/MISP/app/Config/config.php, make sure that MISP has write access to this.

Also, it takes a few seconds for the setting to take, so just refresh the page.

**Comment by west791** [comment]
That did it for me. Thanks a lot!
