### ISSUE TITLE
Bug: encryption.jar possible log4j vulnerbility 

### ISSUE THREAD

**Issue by dazed51** [MISP/MISP#8200]
### Expected behavior

scanner not to detect old versions of log4j vulnerability in encryption.jar file

### Actual behavior

scanner detected old version of encryption.jar file that could be prone to log4j vulnerability 

### Steps to reproduce

scanner picked up the following files and their locations:

    Path             : /opt/flare-misp-service/misp-trans-client-rest-service/config/Encryption.jar

Installed version : 2.5
Fixed version    : 2.12.4

    Path             : /opt/flare-misp-service/misp-trans-client-rest-service/deploy/config/Encryption.jar

Installed version : 2.5
Fixed version    : 2.12.4

    Path             : /opt/mtc/config/Encryption.jar

	Installed version : 2.5
Fixed version    : 2.12.4

### Version

2.4.153

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox, Chrome

### Browser version

latest

### Relevant log output

```shell
Files there were discovered during log4j scan. Not sure if an updated version will be included in later releases of misp. If that is the case then please close ticket.


    Path             : /opt/flare-misp-service/misp-trans-client-rest-service/config/Encryption.jar

Installed version : 2.5
Fixed version    : 2.12.4

    Path             : /opt/flare-misp-service/misp-trans-client-rest-service/deploy/config/Encryption.jar

Installed version : 2.5
Fixed version    : 2.12.4

    Path             : /opt/mtc/config/Encryption.jar

	Installed version : 2.5
Fixed version    : 2.12.4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
AFAIK, this is related to https://github.com/cisagov/flare-misp-service and has nothing to do with MISP itself. Based on their commit history, they fixed it.

If you still have the vulnerability on your systems, you need to update them.

**Comment by dazed51** [comment]
ok, thank you
