### ISSUE TITLE
Support: Issue with MISP and Azure Sentinel Integration

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#8203]
### Support Questions

Hi Everyone,

We're trying to integrate MISP with Azure Sentinel as per the below documentation:

- https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/integrating-open-source-threat-feeds-with-misp-and-sentinel/ba-p/1350371

We've deployed the below script and scheduled a "cron":

- https://github.com/microsoftgraph/security-api-solutions/tree/master/Samples/MISP

Every time MISP pushes some indicators, there is an error that the script is unable to read. We've given the necessary permissions, but there is still no success in pushing MISP indicators to Azure Sentinel.

Any assistance will be greatly appreciated.

Many thanks.

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

Ubuntu 18.04.6 LTS

### PHP version

7.4

### Browser

Chrome, Firefox

### Browser version

97.0.1 Version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmedxuae91** [comment]
The problem was in the configurations added for the script.

After changing it is fixed.

You may close the ticket.
