### ISSUE TITLE
MISP 2.4.155 - No worker active

### ISSUE THREAD

**Issue by alainsilva** [MISP/MISP#8223]
After upgrade MISP from 2.4.143 to 2.4.155 version Workers cannot start. I cannot push events.

Exampe:
Worker type: default
Jobs in the queue: 1
Queue status: Issues prevent jobs from being processed. Please resolve them below.

 sudo -u apache bash /var/www/MISP/app/Console/worker/start.sh
Stopping workers
   There is no workers to stop ...

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
Starting scheduler worker ..................... Fail

 misp-workers.service - MISP workers
   Loaded: loaded (/etc/systemd/system/misp-workers.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2022-03-17 18:29:15 -03; 32min ago
  Process: 3703 ExecStart=/var/www/MISP/app/Console/worker/start.sh (code=exited, status=0/SUCCESS)

rpm -qa | grep misp*
misp-2.4.155-1.el7.x86_64
python36-pymisp-2.4.119-1.el7.noarch
misp-stix-converter-0.2.10-2.el7.noarch
misp-release-1.1-2.el7.noarch
misp-python-3.9.9-4.el7.x86_64
misp-python-virtualenv-2.4.155-1.el7.x86_64
misp-modules-2.4.150-1.el7.x86_64

Log file: resque-worker-error.log

[31;4mError:[0m Call to undefined function json_encode()
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(107): Resque_Worker->registerLogger(Object(MonologInit\MonologInit))
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('update', 1, Object(MonologInit\MonologInit), '5')
#2 {main}

Log file: resque-scheduler-error.log

[31;4mError:[0m Call to undefined function json_encode()
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex-scheduler/bin/resque-scheduler.php(58): Resque_Worker->registerLogger(Object(MonologInit\MonologInit))
#1 {main}

**Comment by righel** [comment]
Hello @alainsilva 
Which PHP version are you running?
The error **Call to undefined function json_encode()** looks unrelated to a MISP version update, have you changed your PHP version?

**Comment by alainsilva** [comment]
Hello @righel

Follows PHP version.

# php -version
PHP 7.4.28 (cli) (built: Mar  7 2022 13:37:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

php74-php-pecl-igbinary-3.2.7-1.el7.remi.x86_64
php74-php-7.4.28-1.el7.remi.x86_64
oniguruma5php-6.9.7.1-1.el7.remi.x86_64
php74-php-mbstring-7.4.28-1.el7.remi.x86_64
php-cli-7.4.28-1.0.3.el7.x86_64
php74-php-mysqlnd-7.4.28-1.el7.remi.x86_64
php74-php-pecl-ssdeep-1.1.0-5.el7.remi.x86_64
php74-php-cli-7.4.28-1.el7.remi.x86_64
php74-php-gd-7.4.28-1.el7.remi.x86_64
php74-php-xml-7.4.28-1.el7.remi.x86_64
php-mysqlnd-7.4.28-1.0.3.el7.x86_64
librdkafka1php-1.8.2-1.el7.remi.x86_64
php74-php-pecl-zip-1.20.0-1.el7.remi.x86_64
php74-php-json-7.4.28-1.el7.remi.x86_64
php74-php-sodium-7.4.28-1.el7.remi.x86_64
php74-php-intl-7.4.28-1.el7.remi.x86_64
php74-php-brotli-0.13.1-1.el7.remi.x86_64
php-common-7.4.28-1.0.3.el7.x86_64
php74-php-pdo-7.4.28-1.el7.remi.x86_64
php74-php-pecl-apcu-5.1.21-1.el7.remi.x86_64
php74-php-bcmath-7.4.28-1.el7.remi.x86_64
php74-php-pecl-redis5-5.3.7-1.el7.remi.x86_64
php74-php-opcache-7.4.28-1.el7.remi.x86_64
php-opcache-7.4.28-1.0.3.el7.x86_64
php74-runtime-1.0-3.el7.remi.x86_64
php74-php-pecl-rdkafka5-5.0.2-1.el7.remi.x86_64
php74-php-common-7.4.28-1.el7.remi.x86_64
php74-php-pecl-msgpack-2.1.2-1.el7.remi.x86_64
php74-php-pecl-gnupg-1.5.1-1.el7.remi.x86_64
php-pdo-7.4.28-1.0.3.el7.x86_64
gd3php-2.3.3-4.el7.remi.x86_64
php74-php-process-7.4.28-1.el7.remi.x86_64
php-gd-7.4.28-1.0.3.el7.x86_64
_____________________________

*Alain Delon*

Em sex., 18 de mar. de 2022 às 06:03, Luciano Righetti <
***@***.***> escreveu:

**Comment by alainsilva** [comment]
More information about PHP Version.

![image](https://user-images.githubusercontent.com/55547807/158998489-abe8e946-61a3-43ec-93b3-24b30d32ad69.png)

Redis info

![image](https://user-images.githubusercontent.com/55547807/158998695-cd3a7a59-da27-4fe5-8925-3f4aeabcc8da.png)

Workers Stoped

![image](https://user-images.githubusercontent.com/55547807/158998169-bf4556bb-fcb1-4a80-a883-b24d8011a2ee.png)

**Comment by righel** [comment]
Are you using CentOS?
Try running:
`yum install php-json`
And restart the workers.

**Comment by alainsilva** [comment]
Hello man! Thanks for your help!

I use Oracle Linux 7

I installed php-json. Please, see results:

# sudo systemctl restart httpd
# sudo systemctl restart misp-workers
# sudo systemctl status misp-workers
 misp-workers.service - MISP workers
   Loaded: loaded (/etc/systemd/system/misp-workers.service; enabled;
vendor preset: disabled)
   Active: active (running) since Fri 2022-03-18 10:16:01 -03; 6s ago
  Process: 4049 ExecStart=/var/www/MISP/app/Console/worker/start.sh
(code=exited, status=0/SUCCESS)

Mar 18 11:18:09 myserver     start.sh[12335]: Starting worker ... Done
Mar 18 11:18:09  myserver    start.sh[12335]: Creating workers
Mar 18 11:18:09  myserver    start.sh[12335]: Starting worker ... Done
Mar 18 11:18:09  myserver    start.sh[12335]: Creating workers
Mar 18 11:18:10  myserver    start.sh[12335]: Starting worker ... Done
Mar 18 11:18:10  myserver    start.sh[12335]: Creating workers
Mar 18 11:18:10  myserver    start.sh[12335]: Starting worker ... Done
Mar 18 11:18:10  myserver    start.sh[12335]: Creating the scheduler workers
Mar 18 11:18:10  myserver    start.sh[12335]: The scheduler worker is already running
Mar 18 11:18:10  myserver    systemd[1]: Started MISP workers.

Config.php file:

'Scheduler' => array(
// Enable or disable delayed job
'enabled' => true,

I restarted Dead Worker, but...

Worker type: default
Jobs in the queue: 0
Queue status: Issues prevent jobs from being processed. Please resolve them
below.

Worker PID User Worker process Information Actions
N/A N/A N/A Worker not running!
Start a worker

This is normal?

![image](https://user-images.githubusercontent.com/55547807/159022048-44982963-ba1e-454a-91ee-b1909218e9cf.png)

Log File: resque-2022-03-18.log

2022-03-18 14:22:47] main.INFO: Starting worker myserver:12881:default
{"type":"start","worker":"myserver:12881:default"} []
[2022-03-18 14:22:47] main.INFO: Starting worker myserver:12902:prio
{"type":"start","worker":"myserver:12902:prio"} []
[2022-03-18 14:22:48] main.INFO: Starting worker myserver:12922:cache
{"type":"start","worker":"myserver:12922:cache"} []
[2022-03-18 14:22:48] main.INFO: Starting worker myserver:12942:email
{"type":"start","worker":"myserver:12942:email"} []
[2022-03-18 14:22:48] main.INFO: Starting worker myserver:12963:update
{"type":"start","worker":"myserver:12963:update"} []

Log File: resque-worker-error.log
Is empty

_____________________________

*Alain Delon*


Em sex., 18 de mar. de 2022 às 09:58, Luciano Righetti <
***@***.***> escreveu:

**Comment by righel** [comment]
Anything new in `/var/www/MISP/app/tmp/logs/error.log` ?

Please check if this helps: https://github.com/MISP/MISP/wiki/Frequently-Asked-Questions#23-i-have-issues-with-misp-workers-how-do-i-solve-them
You probable have to change `www-data` -> `apache` if that's the webserver user in your OS.

**Comment by righel** [comment]
Anything new in `/var/www/MISP/app/tmp/logs/error.log` ?

Please check if this helps: https://github.com/MISP/MISP/wiki/Frequently-Asked-Questions#23-i-have-issues-with-misp-workers-how-do-i-solve-them
You probable have to change `www-data` -> `apache` if that's the webserver user in your OS.

**Comment by alainsilva** [comment]
See results:

[root@myserver ~]# sudo chown -R apache:apache /var/www/MISP
[root@myserver ~]# sudo chmod -R 750 /var/www/MISP
[root@myserver ~]# sudo chmod -R g+ws /var/www/MISP/app/tmp
[root@myserver ~]# sudo chmod -R g+ws /var/www/MISP/app/files
[root@myserver ~]# sudo chmod -R g+ws /var/www/MISP/app/files/scripts/tmp
[root@myserver ~]# sudo service redis restart # restart redis
Redirecting to /bin/systemctl restart redis.service
[root@myserver ~]# /var/www/MISP/app/Console/cake Admin restartWorkers # restart workers
Notice Error: unserialize(): Error at offset 0 of 4 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]

2022-03-18 14:59:06 Notice: unserialize(): Error at offset 0 of 4 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]
Notice Error: unserialize(): Error at offset 0 of 5 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]
...
2022-03-18 14:59:07 Notice: Trying to access array offset on value of type bool in [/var/www/MISP/app/Model/Server.php, line 3642]

**Workers restarted.**

**Same problem:**

Worker type: default
Jobs in the queue: 0
Queue status: Issues prevent jobs from being processed. Please resolve them below.

Worker PID	User	Worker process	Information	Actions
N/A	N/A	N/A	**Worker not running!**


**Log File: error.log**

2022-03-18 12:32:00 Error: [BadRequestException] The request has been black-holed
Request URL: /servers/startWorker/default
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}

**Log File:resque-worker-error.log**

[31;4mNotice Error:[0m fwrite(): send of 40 bytes failed with errno=32 Broken pipe in [/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Redisent/Redisent.php, line 77]

[31;4mError:[0m Failed to write entire command to stream
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(154): Redisent->__call('lpop', Array)
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(136): RedisApi->__call('lpop', Array)
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(100): Resque::pop('update')
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(302): Resque_Job::reserve('update')
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(205): Resque_Worker->reserve()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('update', 1, Object(MonologInit\MonologInit), '5')
#7 {main}

**Comment by righel** [comment]
Just a side note: when interacting with MISP cli, it is recommended to use the same user as the webserver:
For example:
`sudo -u apache /var/www/MISP/app/Console/cake Admin restartWorkers`
Otherwise it can create issues due to permissions.

I suspect the issue is related to Redis being miss-configured or not running:
Please check this guide: https://github.com/MISP/MISP/wiki/Frequently-Asked-Questions#22-how-do-i-solve-the-connection-refused-error-with-redis--cakeresque

**Comment by alainsilva** [comment]
See new results:

[root@myserver ~]# sudo -u apache /var/www/MISP/app/Console/cake Admin restartWorkers
Notice Error: unserialize(): Error at offset 0 of 4 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]

2022-03-18 16:06:01 Notice: unserialize(): Error at offset 0 of 4 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]
Notice Error: unserialize(): Error at offset 0 of 5 bytes in [/var/www/MISP/app/Vendor/kamisama/resque-status/src/ResqueStatus/ResqueStatus.php, line 127]

2022-03-18 16:06:01 Notice: Trying to access array offset on value of type bool in [/var/www/MISP/app/Model/Server.php, line 3638]
Notice Error: Trying to access array offset on value of type bool in [/var/www/MISP/app/Model/Server.php, line 3639]

2022-03-18 16:06:01 Notice: Trying to access array offset on value of type bool in [/var/www/MISP/app/Model/Server.php, line 3639]
Notice Error: Trying to access array offset on value of type bool in [/var/www/MISP/app/Model/Server.php, line 3642]

**REDIS is running**. I restarted again:

[root@myserver ~]# systemctl restart redis
[root@myserver ~]# systemctl status redis
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Fri 2022-03-18 13:07:49 -03; 10s ago
  Process: 23682 ExecStop=/usr/libexec/redis-shutdown (code=exited, status=0/SUCCESS)
 Main PID: 23699 (redis-server)
   Status: "Ready to accept connections"
   CGroup: /system.slice/redis.service
           └─23699 /usr/bin/redis-server 127.0.0.1:6379

**PHP Settings**
PHP ini path:… /etc/opt/remi/php74/php.ini
PHP Version (>7.4 recommended): 7.4.28 (Up to date)
PHP CLI Version (>7.4 recommended): 7.4.28 (Up to date)

![image](https://user-images.githubusercontent.com/55547807/159040948-cd384e9a-0341-4749-b189-1f64f72b159f.png)

![image](https://user-images.githubusercontent.com/55547807/159041031-9ec9aeab-ef61-44ca-b2c8-379d5a5aea0c.png)

![image](https://user-images.githubusercontent.com/55547807/159041092-2050aaac-f519-4f49-ad1a-37ebb133006e.png)

![image](https://user-images.githubusercontent.com/55547807/159041213-c88e4217-d676-451e-b522-7bdd25d4f396.png)

**Comment by alainsilva** [comment]
Misp-workers running and working fine.

**Solution:**
Install php-json
yum install php-json

Renamen file /usr/bin/php
mv /usr/bin/php php.bkp

Link PHP74 to PHP path
ln -s /opt/remi/php74/root/usr/bin/php /usr/bin/php

Reboot to make sure all services are started correctly.

Reference: https://github.com/amuehlem/MISP-RPM/blob/master/INSTALL.md

Thanks @righel [righel](https://github.com/righel)

Evidence:

![image](https://user-images.githubusercontent.com/55547807/159290970-da1b8db7-25e9-48ac-a188-78783884030c.png)
