### ISSUE TITLE
Support: Problem on misp with redis

### ISSUE THREAD

**Issue by MrDuckBr** [MISP/MISP#8226]
### Support Questions

Initially misp had a problem with workers, which did not start, but received external information normally, when checking the logs, I realized that there was an error with Redis, when trying to fix it, I lost access to the settings page, analyzing the logs again and checking redis, the logs now show the problem that the redis class is not working, I followed some other issues but the problem still persists.

<img width="394" alt="Screen Shot 2022-03-18 at 15 42 28" src="https://user-images.githubusercontent.com/35766926/159064717-e22ded7b-16b3-48aa-8979-3701a85956df.png">
<img width="809" alt="Screen Shot 2022-03-18 at 15 34 19" src="https://user-images.githubusercontent.com/35766926/159064728-26bb8a04-9c8d-47cd-b354-36a6cacf2654.png">
<img width="848" alt="Screen Shot 2022-03-18 at 15 26 16" src="https://user-images.githubusercontent.com/35766926/159064746-c7badb69-4a91-4357-95a1-fa52f426b372.png">

### MISP version

2.4.XX

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.2.34

### Relevant log output

```shell
2022-03-18 15:44:54 Error: [Error] Class 'Redis' not found
Request URL: /events/add/metadata:1
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/PubSubTool.php(21): PubSubTool->createRedisConnection(Array)
#1 /var/www/MISP/app/Model/AppModel.php(2615): PubSubTool->initTool()
#2 /var/www/MISP/app/Model/Organisation.php(154): AppModel->getPubSubTool()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): Organisation->afterSave(false, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#6 /var/www/MISP/app/Model/Organisation.php(250): Model->save(Array)
#7 /var/www/MISP/app/Model/Event.php(3429): Organisation->captureOrg(Array, Array)
#8 /var/www/MISP/app/Model/Event.php(3776): Event->__captureObjects(Array, Array, Array)
#9 /var/www/MISP/app/Controller/EventsController.php(2204): Event->_add(Array, true, Array, '', NULL, false, NULL, 0, Array)
#10 [internal function]: EventsController->add()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
php redis is not installed.
```
sudo apt install php-redis
```

If you have multiple PHP versions installed and are using an alternate PHP
version installed as say php 7.4:

```
sudo apt install php7.4-redis
```

Don't forget to restart apache afterwards:

```
service apache2 restart
```

**Comment by iglocska** [comment]
php redis is not installed.

`sudo apt install php-redis`


If you have multiple PHP versions installed and are using an alternate PHP
version installed as say php 7.4:

`sudo apt install php7.4-redis`


Don't forget to restart apache afterwards:


`service apache2 restart`
