### ISSUE TITLE
Bug: Missing "Publish Event" button for regular users

### ISSUE THREAD

**Issue by 3c7** [MISP/MISP#8233]
### Expected behavior

When viewing unpublished events of the own organisation as a regular user, there should be a publish button on the left hand side menu, if the user is allowed to publish events based on the user role.

### Actual behavior

There (most of the times?) isn't. However, the small publish button on the event index page is there. For administrators, the button on event pages is available.

### Steps to reproduce

Login as user and try to publish an event from the event view.

### Version

2.4.156

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks, indeed, that was stupid!
