### ISSUE TITLE
Feature Request: Option to disable logging for non-security features such as attribute modifications and object references

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#8236]
### Is your feature request related to a problem? Please describe.

Background on the issue: I am running a custom made enrichment script to pull in more data to the event and this enrichment script creates objects with attributes and references between objects. Sometimes there can be up to thousands of objects with attributes per event. All these objects and attributes with their changes are then logged by MISP to the database table "logs" by default.

Issue: I recently noticed that in my personal MISP instance I kept running out of disk space frequently. I looked into the matter and noticed that the database table "logs" is over 18gb in size.

![image](https://user-images.githubusercontent.com/5585477/159435104-ce607868-5d06-45dd-9ce0-c9aed90e2fc4.png)

When I inspected the table contents it was mostly "irrelevant" logs which for example stated when a attribute had been created, modified or deleted or when a object was created or changed etc.

I understand that there might be use-cases for this level of detail but in my opinion it should be enabled only if logging would be set to level debugging or similar where this level of accuracy would be indicated.

### Describe the solution you'd like

More options to the UI to

A) disable all non-security related logging to mysql table "logs".
B) set logging by different levels.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
In general we consider these as essential as they're used to build the event history.

With that said, I totally see your point and we should have a way of disabling CRUD action logs on demand if you don't care about them. I'll keep this in mind and will check if it's something we can do on the quick!

**Comment by JakubOnderka** [comment]
You can enable new audit log system, that stores events changes like attribute modification in different table. So then you can sometimes truncate just `audit_logs` table and security logs will still stay in `logs` table.
