### ISSUE TITLE
Support: MISP Behind Azure App Gateway

### ISSUE THREAD

**Issue by Nate-09** [MISP/MISP#8238]
### Support Questions

Hi Everyone,

I've recently deployed an instance of MISP in Azure and attempting to run it behind Azure Web Application Gateway.

After getting the host functional, I ran into issues running behind the WAF, this ends in too many redirects on the MISP Server.

The installation was done using the install.sh from https://github.com/MISP/MISP/tree/2.4/INSTALL.

We are using the misp core and misp-modules only. The entire system will be placed behind the WAF for added protection and simplified management of the front-end.

Any help would be greatly appreciated

### MISP version

MISP 2.4.156

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

 7.4.3

### Browser

All browsers

### Browser version

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
We know some MISP instances behind WAF and reverse proxies. This usually works. It's important to set the base url to the proper url handled by the final client. 

Can you share your configuration of Azure Web Application Gateway ? It's difficult to test as we don't have access to such infrastructure.

**Comment by Nate-09** [comment]
Hi Adulau,

I was able to get this operational.

thenissue I had was in azure the internal DNS for the backend was the issue.

By using Azure Private DNS and updating the base URL and updating the local certificate to match the correct vhost configured in the Apache ssl conf resolved the issue.

**Comment by adulau** [comment]
Thanks for the feedback. If you are able to do a documentation, feel free to share it with us.

**Comment by Nate-09** [comment]
Not a problem adulau, I’m actually working on a terraform deployment for to automate this. Once done I’m hoping I will be able to share it with the community alongside the deployment documentation.

**Comment by honey4sec** [comment]
@Nate-09 i have the same problem so awsome if you share your solution

**Comment by Nate-09** [comment]
> @Nate-09 i have the same problem so awsome if you share your solution

In order to run MISP behind the Azure WAF, there is two methods, I cannot go into details for the first option which is to utilize Azure Private DNS, as I'm still working on this solution.

The second option which is what I have operational is to apply a valid SSL Certificate to the Host, and update the apache ssl conf with the new SSL and the server name.

By doing this I solved receiving a too many redirect issue, then in Azure WAF to solve the health and receive a 200 status response, I use the actual path MISP redirects to /users/login like in the image below

![image](https://user-images.githubusercontent.com/87747569/166165947-9754a984-d8a0-47aa-b4ad-4c7e1af87cfe.png)

**Comment by lnfernux** [comment]
@Nate-09 did you ever finish the guidance on using private dns?

**Comment by lnfernux** [comment]
Or @honey4sec if you managed to get it working?
