### ISSUE TITLE
Bug: Broken push sync for events with sharing groups

### ISSUE THREAD

**Issue by zpevma** [MISP/MISP#8239]
### Expected behavior

Events with sharing groups are being pushed.

### Actual behavior

Events are not pushed.

### Steps to reproduce

- Just call pymysp `misp.add_event(event)` where event has any sharing group set as distribution, you will get 500 error: `{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/add"}
`.
- [This line](https://github.com/MISP/MISP/blob/ab1305cc18ef23a8d0c2d7d354d6fc8901ab19ad/app/Model/Event.php#L1038) will never be executed because `$server['RemoteOrg']['uuid']` doesn't not exists.
- Deleting [this line](https://github.com/MISP/MISP/blob/ab1305cc18ef23a8d0c2d7d354d6fc8901ab19ad/app/Model/Event.php#L4432) should solve this issue (tested as hotfix in our environment).

### Version

2.4.156

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox

### Relevant log output

```shell
2022-03-24 14:26:31 Error: Error when pushing event <UUID> to remote server 4: org not found in sharing group.
2022-03-24 14:26:31 Error: Could not push event '' to remote server #4
[Exception] This should never happen.
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(4484): Event->uploadEventToServer()
#1 /var/www/MISP/app/Model/Event.php(4671): Event->uploadEventToServersRouter()
#2 /var/www/MISP/app/Model/Event.php(4163): Event->publish()
#3 /var/www/MISP/app/Controller/EventsController.php(2692): Event->_edit()
#4 [internal function]: EventsController->edit()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}
2022-03-24 14:26:31 Error: [TypeError] Argument 2 passed to Event::__logUploadResult() must be of the type array, int given, called in /var/www/MISP/app/Model/Event.php on line 1011
Request URL: /events/edit/ecba795b-c5a7-4601-975d-a1b533b88da1
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(1011): Event->__logUploadResult()
#1 /var/www/MISP/app/Model/Event.php(4484): Event->uploadEventToServer()
#2 /var/www/MISP/app/Model/Event.php(4671): Event->uploadEventToServersRouter()
#3 /var/www/MISP/app/Model/Event.php(4163): Event->publish()
#4 /var/www/MISP/app/Controller/EventsController.php(2692): Event->_edit()
#5 [internal function]: EventsController->edit()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
This was just fixed a half an hour ago, make sure you git pull.

also we’ll do a full release later tonight to address this.

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/commit/15820bb5af4b8edb360e1595eddce9f40d9032af

The relevant fix

**Comment by zpevma** [comment]
Perfect, thanks!
