### ISSUE TITLE
Bug: rate limit error without any rate limit set for the role

### ISSUE THREAD

**Issue by EulogyMondata** [MISP/MISP#8241]
### Expected behavior

We have a private internal MISP where we may request many calls in a short time to /attributes/restSearch. So we must not have any rate limite. The API Key is generate through admin user/role , without rate limit [check].

### Actual behavior

Sometime we have a error : api - _check_response: Something went wrong (429): {'name': 'Rate limit exceeded', "message': 'Rate limit exceeded.', 'url': '/attributes/restSearch'}, then we need to restart the pods to get back a authorized connection to the API.

### Steps to reproduce

poke '/attributes/restSearch' til get error 

### Version

1.4.153

### Operating System

Docker version

### Operating System version

coolacid/misp-docker

### PHP version

7.4

### Browser

api

### Browser version

pyMISP

### Relevant log output

```shell
api - _check_response: Something went wrong (429): {'name': 'Rate limit exceeded', "message': 'Rate limit exceeded.', 'url': '/attributes/restSearch'}
```

### Extra attachments

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/69516294/160141862-b8f6c34b-157b-4269-b1b8-36282718fc0f.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/69516294/160142207-ca101888-03f6-467c-a0c8-b01559e61e92.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/69516294/160142265-6d2063ee-7503-42fa-8c34-ad9baa4b0aa2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
I can't seem to reproduce this on 2.4.157. 

What I tried:

Select a role with rate limiting disabled.

Created a bash script to curl the instance (429.sh):

```
curl \
 -d '{"returnFormat":"json","page":1,"limit":1}' \
 -H "Authorization: k3A2R5ccj1CL8QoroudkttaWCU9ioQNpCN54pmPY" \
 -H "Accept: application/json" \
 -H "Content-type: application/json" \
 -X POST http://localhost:5006/attributes/restSearch
```

Started hammering the instance with it:

`watch -n 0.1 ./429.sh`

It seemed to be happy to keep serving the responses for minutes.

So I tried to see if I can mess with some of the role configuration to reproduce it:

```
 update roles set rate_limit_count = 15 where id = 4;
```

Added a rate limit count when rate limiting was disabled, hoping that would reproduce it, but no dice. Tried with NULL but the schema enforces NOT NULL. 

Not entirely sure how you ended up with that situation.
