### ISSUE TITLE
Support: Problem with adding references in Event graph: Relationship type list appear empty

### ISSUE THREAD

**Issue by q-modus-p** [MISP/MISP#8243]
### Support Questions

I am trying to establish relationships between objects in the Event graph view, but as I draw the link between them, then in the pop-up window I am unable to select any relationship types other than _Custom_. There is nothing else in the list.

I have performed a couple of fresh installations with the Ubuntu 20.04 installation script and they all finish having this "limitation."
I also have an older version of MISP running in which I can establish object relationships and in that the relation ship types list has plenty to choose from.

I attached a couple screenshots showing 1) the initial view, 2) complete relationship types list in my old MISP and 3) the same, now incomplete list in the new installation.
How could I verify is this simply missing configuration, misconfiguration or a bug?

1)
 <img width="1233" alt="1" src="https://user-images.githubusercontent.com/75488076/160232982-168dd525-1162-481f-b0fa-923af02fe4de.png">

2)
<img width="1073" alt="2" src="https://user-images.githubusercontent.com/75488076/160232996-dd348ec9-0adf-4bbe-94c3-0255a69a02c4.png">

3)
<img width="1069" alt="3" src="https://user-images.githubusercontent.com/75488076/160233006-f04c836f-87ff-41d7-89d4-e8d6e9a128a6.png">
 

### MISP version

2.4.157

### Operating System

Ubuntu

### Operating System version

20.04 LTS

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @q-modus-p
Could you please check if you see some errors in your `/var/www/MISP/app/tmp/logs/error.log` logs after you try to create the relationship and the pop-up is shown?

Could you check that your `object_relationships` db table is not empty?
```
SELECT * FROM misp.object_relationships; 
```

Just checked and its working for without issues in version 2.4.157 for me, there must be something else going on.

**Comment by iglocska** [comment]
Make sure that you tell MISP to ingest the object template libraries, the
relationships are ingested together with them. Go to your object template
index (global actions -> list object templates) and hit update objects on
the left side with a site admin account.

**Comment by q-modus-p** [comment]
> Hello @q-modus-p Could you please check if you see some errors in your `/var/www/MISP/app/tmp/logs/error.log` logs after you try to create the relationship and the pop-up is shown?
> 
> Could you check that your `object_relationships` db table is not empty?
> 
> ```
> SELECT * FROM misp.object_relationships; 
> ```
> 
> Just checked and its working for without issues in version 2.4.157 for me, there must be something else going on.

Thank you @righel for looking into the issue I was having. As I attempted to establish a relationship between the objects, nothing appeared in the error.log file, no errors whatsoever.

**Comment by q-modus-p** [comment]
> Make sure that you tell MISP to ingest the object template libraries, the relationships are ingested together with them. Go to your object template index (global actions -> list object templates) and hit update objects on the left side with a site admin account.
> […](#)

Thank you @iglocska, this solved it for my installation! 
After updating the object templates as per your suggestion I now can establish relationships with full set of relationship types.
Thanks again to you and everyone on this project for your great work!

**Comment by Nicolas-Pellletier** [comment]
Hello, 
@iglocska and @righel , 
I've got the same issue than @q-modus-p but this time i've not data in the mysql database regarding object_relationships.
I don't know what to do in order to populate it to be able to create link between object.

**------- Post update --------**
The solution that worked for me:
Go to object template index as an administrator and hit update. Do the same for galaxy clusters

**Comment by Nicolas-Pellletier** [comment]
> Hello, @iglocska and @righel , I've got the same issue than @q-modus-p but this time i've not data in the mysql database regarding object_relationships. I don't know what to do in order to populate it to be able to create link between object
The solution that worked for me:
 Go to object template index as an administrator and hit update. Do the same for galaxy clusters
