### ISSUE TITLE
Bug: Can't download deleted attributes from MISP

### ISSUE THREAD

**Issue by rupiewicz** [MISP/MISP#8249]
### Expected behavior

hello i cant search delete atribute from misp . 
I find similar issue 
https://github.com/MISP/MISP/issues/2222 but i dont know what is the resolve  ? 

### Actual behavior

/attributes/restSearch/json
{
    "returnFormat": "txt", 
    "eventid": "15",
    "deleted":"true"
}

 resolve only search with delete: false 

### Steps to reproduce

??? 

### Version

2.4.157

### Operating System

ubuntu LTE

### Operating System version

20.04

### PHP version

7.4.3

### Browser

firefox

### Browser version

98.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @rupiewicz 
The `deleted` filter is of boolean type, not string.
Try with:
```json
{
   "returnFormat": "txt",
   "eventid": "15",
   "deleted": true
}
```

On a side note, in the URL you specify JSON as expected return format and in your request payload you set `"returnFormat": "txt"`. What is your expected resturn format?

Let me know if that helps.

**Comment by rupiewicz** [comment]
Thanks for your help  confirm it's ok

**Comment by rupiewicz** [comment]
i mean text  not txt sorry :)
