### ISSUE TITLE
Mass-update attributes to add comments

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#825]
Does not seem to work.

Test on a MISP v2.4.5 (MISPpriv), tried from a Firefox v38.2 ESR.

Tried to edit two attributes to add a comment on event 2913.

**Comment by iglocska** [comment]
hmph just tried it on my dev instance and it works fine. Can you check what the response is in your browser's console?

**Comment by iglocska** [comment]
Just found it, looks like a black hole. Did you try to refresh and try it again? It sounds like the CSRF protection kicked in.

**Comment by elhoim** [comment]
Tried multiple times.
Retried now also by going directly to the event page, select two attributes, and then clicking on mass-edit after changing the comment, still no luck.

**Comment by iglocska** [comment]
hmm
looking into it

**Comment by iglocska** [comment]
Hmph, I cannot reproduce it :S Could you point out the exact changes you wanted to make (in an e-mail to me) and I'll give it a shot? :)

**Comment by Rafiot** [comment]
@elhoim can I close this issue?
