### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by qbolbk59** [MISP/MISP#8251]
### Support Questions

Post upgrdaing MISP to 2.4.157, i am unable to open any events. This is probably due to the new feature of Cryptographic keys that can be added to protect the event. The error is provided below:

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

The following error was found in the error log:

`2022-03-30 14:35:16 Error: [MissingTableException] Table cryptographic_keys for model CryptographicKey was not found in datasource default.
Exception Attributes: array (
  'table' => 'cryptographic_keys',
  'class' => 'CryptographicKey',
  'ds' => 'default',
)
Request URL: /events/view/256
Stack Trace:
#0 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2663): Model->schema()
#3 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1886): DboSource->fields()
#4 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1377): DboSource->generateAssociationQuery()
#5 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation()
#6 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#7 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#8 /app/MISP/app/Model/Event.php(2115): Model->find()
#9 /app/MISP/app/Controller/EventsController.php(1825): Event->fetchEvent()
#10 [internal function]: EventsController->view()
#11 /app/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /app/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}`

### MISP version

2.4.157

### Operating System

CentOS

### Operating System version

7.x

### PHP version

7.4.3

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Looks like an incomplete database update, could you run the following command:

~/var/www/MISP/app/Console/cake Admin updateDatabase~
```
/var/www/MISP/app/Console/cake Admin runUpdates
```

Let me know if that works.

**Comment by qbolbk59** [comment]
@righel My apologies for late response. I tried that the updateDatabase command as well but no luck. There's no subcommand available as "updateDatabase". Only the following subcommands are available for "cake admin"

`Usage:
cake admin [subcommand] [-h] [-v] [-q]

Subcommands:

updateJSON -Update the JSON definitions of MISP.
setSetting  -Set setting in PHP config file.
live -Set if MISP instance is live and accessiblefor users.
reencrypt -Reencrypt encrypted values in database(authkeys and sensitive system settings).
dumpCurrentDatabaseSchema -Dump current database schema to JSON file.
removeOrphanedCorrelations  -Remove orphaned correlations.
optimiseTables  -Optimise database tables.
redisMemoryUsage  -Get detailed information about Redis memory usage.
redisReady -Check if it is possible connect to Redis.
securityAudit -Run security audit.
securityAuditTls -Run security audit to test enabled/disabled ciphers and protocols in TLS connections.
configLint -Check if settings has correct value.`

**Comment by righel** [comment]
Sorry, wrote it wrong. Try with:
```
/var/www/MISP/app/Console/cake Admin runUpdates
```

**Comment by qbolbk59** [comment]
@righel That indeed worked. Thanks a lot ! 

I can view the events now. But i think the issue with the new feature of cryptographic_keys still persists as in the event i don't see the option to move the event into Protected mode. 

![image](https://user-images.githubusercontent.com/43533246/162128809-6c2c1071-3716-4199-93f0-0fed6449b785.png)

**Comment by adulau** [comment]
Did you setup the PGP key of the instance?

**Comment by qbolbk59** [comment]
@adulau Yes, PGP key is created for the instance.

**Comment by qbolbk59** [comment]
@adulau but i do see this error in diagnostics

![image](https://user-images.githubusercontent.com/43533246/162418647-f590fd11-2699-48c6-872d-9fe0af557f23.png)


Could this be relevant ?

**Comment by righel** [comment]
> @righel That indeed worked. Thanks a lot !
> 
> I can view the events now. But i think the issue with the new feature of cryptographic_keys still persists as in the event i don't see the option to move the event into Protected mode.
> 
> ![image](https://user-images.githubusercontent.com/43533246/162128809-6c2c1071-3716-4199-93f0-0fed6449b785.png)

How does this look like when editing a Event created by you? 
You cannot switch to protected an event that was not created by your organisation or it's locked.

> @adulau but i do see this error in diagnostics
> 
> ![image](https://user-images.githubusercontent.com/43533246/162418647-f590fd11-2699-48c6-872d-9fe0af557f23.png)
> 
> Could this be relevant ?

Could you check the error log `/var/www/MISP/app/tmp/logs/error.log` after running the diagnostics and share any GnuPG related errors here?

**Comment by qbolbk59** [comment]
@righel I get the same issue with the events that i create. I don't see the option to move the event to a Protected mode. 
I don't see any error specifically for GnuPG itself but every but this is the error that i see in the error.log

2022-04-12 10:06:08 Error: [MissingTableException] Table cryptographic_keys for model CryptographicKey was not found in datasource default.
Exception Attributes: array (
  'table' => 'cryptographic_keys',
  'class' => 'CryptographicKey',
  'ds' => 'default',
)
Request URL: /events/view/257
Stack Trace:
#0 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#2 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(2663): Model->schema()
#3 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1886): DboSource->fields()
#4 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1377): DboSource->generateAssociationQuery()
#5 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1257): DboSource->queryAssociation()
#6 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#7 /app/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#8 /app/MISP/app/Model/Event.php(2115): Model->find()
#9 /app/MISP/app/Controller/EventsController.php(1825): Event->fetchEvent()
#10 [internal function]: EventsController->view()
#11 /app/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#12 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#13 /app/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /app/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}

**Comment by qbolbk59** [comment]
@righel  I think there was a confusion at my side. Just to give you an overview, i have two MISP instances which talk to the same database. This is created to have High availability of MISP. 
The database is not local but hosted on remote server that both MISP talk to.

Post upgrading the MISP instances to the current version i.e., 2.4.157, one of the MISP instance is simply not able to open any event and throws the error that i provided in the previous comment.

While in the other MISP, i am able to open the events, but i don't see the option to move event to Protected mode.

I guess something went wrong during upgrade.

**Comment by eowyn263** [comment]
@righel 
`/var/www/MISP/app/Console/cake Admin runUpdates` 
worked for me, thank you!!
