### ISSUE TITLE
Typo: In the dialog of Unpublish Event the "Yes" option has the hover text set as "Publish" instead of "Unpublish"

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#8257]
### Expected behavior

The hover text over the "Yes" option should say "Unpublish" when you are trying to unpublish an event.

### Actual behavior

![image](https://user-images.githubusercontent.com/5585477/161035478-3fd39c49-c48e-433a-9493-fddd667d87c7.png)

### Steps to reproduce

Try to unpublish an event and hover the mouse cursor over the "Yes" option, see the screenshot above.

### Version

v2.4.157

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Thanks for report, fixed in `develop` branch.
