### ISSUE TITLE
Support: I have one MISP-instance in my school project for three different companies. How to not show events to each other? 

### ISSUE THREAD

**Issue by ponkape** [MISP/MISP#8260]
### Support Questions

Hello MISP peeps!

I'm fairly new with this MISP tool, and must say it looks great and huge! I faced the following issue when trying to share MISP events with each "organization":

I created three different Organizations in MISP and thought that when I make a new event, I can just assign it to Company A, and while I make MISP-account (read-only access) to Company A _ONLY_ Company A would see the events. But, while I made this same setup for Company B also, it seems Company A users sees also Company B MISP events?

I tried to understand with documentation the difference between "Local" / "Remote" organizations, but could not figure out how example this "Remore" organization would see the events, without having a MISP-account?  

Have a super weekend MISP-people and waiting for answers to my noob-questions 

Regards
ponkape

### MISP version

2.4.66

### Operating System

CentOS

### Operating System version

7

### PHP version

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
First of all: _**MISP 2.4.66 is from 2017 and is it strongly encouraged to upgrade/reinstall.**_

> I created three different Organizations in MISP and thought that when I make a new event, I can just assign it to Company A, and while I make MISP-account (read-only access) to Company A ONLY Company A would see the events. But, while I made this same setup for Company B also, it seems Company A users sees also Company B MISP events?

You do not normally "assign" events to organizations. You either don't share, share with some, or share with all. When you create an event ([see "Creating an event" in the MISP Book](https://www.circl.lu/doc/misp/using-the-system/#creating-an-event)) you select the events Distribution. The default depends on your MISP configuration, but for your example with three organizations that should not see each others events, you want to set distribution to "Your organization only" for the events. 

> I tried to understand with documentation the difference between "Local" / "Remote" organizations, but could not figure out how example this "Remore" organization would see the events, without having a MISP-account?

Local organizations have a precence on your MISP instance. Remote organizations are i.e. organizations that are the original creators of MISP events that you have pulled down from other MISP instances.

**Comment by ponkape** [comment]
Thank you @Kagee for the response, I will totally take a look at these 🙏
