### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by omb62** [MISP/MISP#8263]
### Support Questions

Users could not login 

We have set in config to point to a specific plugin (even we have set it explicitly, e.g. copied the OidcAuth plugin in /var/www/MISP/app/Plugin and rename it to for example OurOidcAuth) but somehow the configuration could be changed and the config still referring to the default OidcAuth.

Can anyone assist me on this?

Thank you

### MISP version

2.4.148

### Operating System

Centos

### Operating System version

7

### PHP version

7.4.28

### Relevant log output

```shell
2022-03-31 10:02:21 Error: [RuntimeException] Config option `OidcAuth.provider_url` is not set.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(147): OidcAuthenticate->getConfig()
#1 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(29): OidcAuthenticate->prepareClient()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#4 /var/www/MISP/app/Controller/UsersController.php(1188): AuthComponent->login()
#5 [internal function]: UsersController->login()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
`Config option `OidcAuth.provider_url` is not set.` I think the error message is pretty clear. You need to setup the parameters for your OIDC providers.
