### ISSUE TITLE
Support: MISP openid integration not work

### ISSUE THREAD

**Issue by yash22091** [MISP/MISP#8264]
### Support Questions

MISP openid integration not work. No logs are appearing in server . Openid login page comes but after login blank page comes. Kindly help us

### MISP version

2.4.151

### Operating System

Centos

### Operating System version

7.09

### PHP version

7.1

### Browser

Firefox

### Browser version

latest

### Relevant log output

```shell
no logs
```

### Extra attachments

![Screenshot (57)](https://user-images.githubusercontent.com/34241504/162137617-516253f5-6cff-437b-ad8f-2bf212af735f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Did you check the MISP specific logs, found under /var/www/MISP/app/tmp/logs/ ?  the most interesting log files are `error.log` and `debug.log`. Especially to double check if your OIDC configuration is correct.

**Comment by yash22091** [comment]
We have already checked but there are no error logs

**Comment by yash22091** [comment]
kindly please provide Apache openid conf file and config.php of example files of configuration.
