### ISSUE TITLE
Bug: supervisord not functional

### ISSUE THREAD

**Issue by Daniel-CS-Team** [MISP/MISP#8265]
### Expected behavior

After following the instructions here (https://github.com/MISP/MISP/blob/2.4/docs/background-jobs-migration-guide.md) enabling SimpleBackgroundJobs.enabled true should work fine.

### Actual behavior

Internal Server Error.

### Steps to reproduce

Follow instructions, enable SimpleBackgroundJobs, reload page.

### Version

2.4.157

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.27

### Relevant log output

```shell
# tail -n 7 /var/www/MISP/app/tmp/logs/misp-workers-errors.log 
Error: Call to a member function blpop() on null
#0 /var/www/MISP/app/Console/Command/StartWorkerShell.php(65): BackgroundJobsTool->dequeue()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(462): StartWorkerShell->main()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#4 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#5 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @Daniel-CS-Team 
Could you please share the last bits of your MISP error log located in `/var/www/MISP/app/tmp/logs/error.log` ?

Is `php-redis` installed?
If not, try after installing it via:
`sudo apt install php-redis`

If issues persist, check this troubleshooting guide steps 1 - 4:
https://github.com/MISP/MISP/wiki/Frequently-Asked-Questions#22-how-do-i-solve-the-connection-refused-error-with-redis--cakeresque

Let me know if that helps.
