### ISSUE TITLE
Bug: Version 2.4.157 Warninglist (show) action filter does not work

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#8280]
### Expected behavior

Clicking on (show) in an event page beside "Warning: Potential false positive" will filter the attributes to only show warninglist hits.

It looks as though the button is trying to use Waringlist as a filter when it is now Warning. See screenshot.

### Actual behavior

Filter does not work.

### Steps to reproduce

Clicking on (show) in an event page beside "Warning: Potential false positive" in version 2.4.157 with events that have both matches and not matches to enabled warninglists. 

### Version

2.4.157

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Extra attachments

![image](https://user-images.githubusercontent.com/20773170/163526204-92694777-d0bb-46ac-86ef-8d21fa33484d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Thanks for report, already fixed in #8274.
