### ISSUE TITLE
Support: Any way to do MFA on users?

### ISSUE THREAD

**Issue by teward** [MISP/MISP#8282]
### Support Questions

This is a question revolving around user logins and security.  LinOTP is a mostly dead project (python2 is dead people!) and no longer free for 'updated' versions.

As such, is there an alternative for multifactor authentication we can implement in MISP for multifactor authentication for users?

### MISP version

2.4.156

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4 (Ubuntu)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UFOSmuggler** [comment]
Email based OTP is configurable in /servers/serverSettings/Security and works well.  Otherwise there's a plugin for Azure AD which also works well.  Beyond this you will probably need to do some work to integrate with whatever.

**Comment by teward** [comment]
> Email based OTP is configurable in /servers/serverSettings/Security and works well. Otherwise there's a plugin for Azure AD which also works well. Beyond this you will probably need to do some work to integrate with whatever.

Email OTP will work for our case.  Thank you!
