### ISSUE TITLE
restSearch API "Internal Server Error" Error after 2.4 upgrade

### ISSUE THREAD

**Issue by karttoon** [MISP/MISP#829]
Upgraded from 2.3 to 2.4 [2.4.3] and having some issues with doing searches via the Restful API.

Old method that I used with the Requests module in Python for 2.3:

mp_url = "https://<site>/events/restSearch/download/" + search_value
mp_headers = {"Authorization": mp_apikey, "Accept": "application/xml"}
mp_response = requests.post(mp_url, headers=mp_headers, verify=False)

This was showing being "black-holed" in the return so I modified it based on the 2.4 documentation. Using curl to test I get "An Internal Error Has Occurred" now.

curl --insecure -H "Content-Type: application/xml" -H "Accept: application/xml" -H "Authorization: <key>" --data "{'request': {'value': '<md5hash>', 'searchall': 1}}" -X POST https://<search>/events/restSearch/download/

I've tried XML and JSON for Content-Type/Accept, along with variations of GET/POST, trailing slash after "download", and variations on the URI but haven't been able to get it to work.

<?xml version="1.0" encoding="UTF-8"?>
<response><name>An Internal Error Has Occurred.</name><message>An Internal Error Has Occurred.</message><url>/events/restSearch/download/</url></response>

**Comment by FafnerKeyZee** [comment]
I add the same issue, no information into app/tmp/error.log, but when I check into apache2 logs I have this error:
```
[Fri Jan 08 10:07:06 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 273
[Fri Jan 08 10:09:23 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 3149
[Fri Jan 08 10:10:30 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 79 bytes) in /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 277
[Fri Jan 08 10:12:26 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 82 bytes) in /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php on line 277
[Fri Jan 08 10:13:55 2016] [error] [client xxx.xxx.xxx.xxx] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 64 bytes) in /home/misp/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 720
```

**Comment by iglocska** [comment]
I've just pushed some fixes which should help, but if you are running a full export via the API you may want to increase the execution time / allowed memory size.

**Comment by FafnerKeyZee** [comment]
Solve for me. Need to ajust execution time & allowed memory size for php

**Comment by Rafiot** [comment]
@karttoon: did it fix the issue for you?

**Comment by karttoon** [comment]
@Rafiot Unfortunately we won't be able to apply any changes to our environment for another week or so. Thank you for the quick turn around and I will test it when able and update here.

**Comment by elhoim** [comment]
@karttoon any update?

**Comment by Rafiot** [comment]
No news, please reopen if you still have a problem.
