### ISSUE TITLE
Bug: STIX 2 import fails for files with tag "misp:tool=\"misp2stix2\"" and attribute type link.

### ISSUE THREAD

**Issue by abhijeetasawant** [MISP/MISP#8291]
### Expected behavior

STIX 2.0 file should get imported and attribute of type link with category as External analysis should be created.

### Actual behavior

Following message displayed :+1: 

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

1. Click on 'Import from' option
2. Select STIX 2.0
3. Select file and import.

### Version

2.4.153

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2074, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2068, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 82, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 356, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 383, in _parse_observable
    self.parse_observable_attribute(observable)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 513, in parse_observable_attribute
    value = self.parse_single_attribute_observable(objects, attribute['type'])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 821, in parse_single_attribute_observable
    return getattr(self, stix2misp_mapping.attributes_mapping[attribute_type])(observable)
KeyError: 'link'
```

### Extra attachments

Sample File.
{
	"type": "bundle",
	"spec_version": "2.0",
	"id": "bundle--626b667b-1ce3-4152-999f-1039e5de6d24",
	"objects": [
		{
			"type": "identity",
			"id": "identity--4746942c-63ef-4584-8a9f-6bc141da66cc",
			"created": "2022-04-20T11:20:03.000Z",
			"modified": "2022-04-20T11:20:03.000Z",
			"name": "ORGNAME",
			"identity_class": "organization"
		},
		{
			"type": "report",
			"id": "report--1c29d3dd-c9a2-4f09-b6ea-b73060d7225f",
			"created_by_ref": "identity--4746942c-63ef-4584-8a9f-6bc141da66cc",
			"created": "2022-04-20T11:20:03.000Z",
			"modified": "2022-04-20T11:20:03.000Z",
			"name": "custom",
			"published": "2022-04-20T11:20:03Z",
			"object_refs": [
				"observed-data--6066cd67-3e95-474e-bf2c-7ceeeec4f0d3",
				"x-misp-attribute--55fa2083-d7f3-4f89-a499-5c422a8bde2b"
			],
			"labels": [
				"Threat-Report",
				"misp:tool=\"misp2stix2\"",
				"misp:tool=\"MISP-STIX-Converter\""
			]
		},
		{
			"type": "course-of-action",
			"id": "course-of-action--5d94e280-4741-4ff9-afba-f5a365105638",
			"created_by_ref": "identity--89fabd16-606a-4398-852b-f398cffd83d7",
			"created": "2021-06-22T10:42:11.000Z",
			"modified": "2021-06-22T10:42:11.000Z",
			"name": "Microsoft Security Bulletin MS17-010 - Critical",
			"description": "Apply Patch - https://docs.microsoft.com/en-us/security-updates/securitybulletins/2017/ms17-010",
			"labels": [
				"misp:category=\"misc\"",
				"misp:name=\"course-of-action\""
			],
			"x_misp_cost": "Medium",
			"x_misp_efficacy": "High",
			"x_misp_stage": "Remedy",
			"x_misp_type": "Patching"
		},
		{
			"type": "observed-data",
			"id": "observed-data--6066cd67-3e95-474e-bf2c-7ceeeec4f0d3",
			"created_by_ref": "identity--4746942c-63ef-4584-8a9f-6bc141da66cc",
			"created": "2022-04-20T11:14:08.000Z",
			"modified": "2022-04-20T11:14:08.000Z",
			"first_observed": "2022-04-20T11:14:08Z",
			"last_observed": "2022-04-20T11:14:08Z",
			"number_observed": 1,
			"objects": {
				"0": {
					"type": "url",
					"value": "https://www.hybrid-analysis.com/sample/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa?environmentId=100"
				}
			},
			"labels": [
				"misp:type=\"link\"",
				"misp:category=\"External analysis\""
			]
		}
	]
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Thanks, it should be fixed with a3d87b6854f8a9d8bffe7dac3da69afa569ff208
Let me know if anything goes wrong and reopen if needed

**Comment by abhijeetasawant** [comment]
Yes. its fixed.

**Comment by abhijeetasawant** [comment]
It has fixed for attribute type link.
But now its failing for  "type": "course-of-action"

Logs:
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2074, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2068, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 82, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 356, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 389, in _parse_undefined
    getattr(self, self._special_mapping[stix_object._type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 433, in parse_course_of_action
    self.fill_misp_object(misp_object, course_of_action, 'course_of_action_mapping',
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 409, in fill_misp_object
    misp_object.add_attribute(**attribute)
  File "/usr/local/lib/python3.9/dist-packages/pymisp/mispevent.py", line 1031, in add_attribute
    attribute.from_dict(object_relation=object_relation, **{**self._default_attributes_parameters, **value})
  File "/usr/local/lib/python3.9/dist-packages/pymisp/mispevent.py", line 2269, in from_dict
    super().from_dict(**{**self, **kwargs})
  File "/usr/local/lib/python3.9/dist-packages/pymisp/mispevent.py", line 495, in from_dict
    raise NewAttributeError('{} is invalid, type has to be in {}'.format(self.type, (', '.join(self.known_types))))
pymisp.exceptions.NewAttributeError: cost is invalid, type has to be in AS, aba-rtn, anonymised, attachment, authentihash, bank-account-nr, bic, bin, boolean, bro, btc, campaign-id, campaign-name, cc-number, cdhash, chrome-extension-id, comment, community-id, cookie, cortex, counter, country-of-residence, cpe, dash, date-of-birth, datetime, dkim, dkim-signature, dns-soa-email, domain, domain|ip, email, email-attachment, email-body, email-dst, email-dst-display-name, email-header, email-message-id, email-mime-boundary, email-reply-to, email-src, email-src-display-name, email-subject, email-thread-index, email-x-mailer, eppn, favicon-mmh3, filename, filename-pattern, filename|authentihash, filename|impfuzzy, filename|imphash, filename|md5, filename|pehash, filename|sha1, filename|sha224, filename|sha256, filename|sha3-224, filename|sha3-256, filename|sha3-384, filename|sha3-512, filename|sha384, filename|sha512, filename|sha512/224, filename|sha512/256, filename|ssdeep, filename|tlsh, filename|vhash, first-name, float, frequent-flyer-number, full-name, gender, gene, git-commit-id, github-organisation, github-repository, github-username, hassh-md5, hasshserver-md5, hex, hostname, hostname|port, http-method, iban, identity-card-number, impfuzzy, imphash, ip-dst, ip-dst|port, ip-src, ip-src|port, issue-date-of-the-visa, ja3-fingerprint-md5, jabber-id, jarm-fingerprint, kusto-query, last-name, link, mac-address, mac-eui-64, malware-sample, malware-type, md5, middle-name, mime-type, mobile-application-id, mutex, named pipe, nationality, other, passenger-name-record-locator-number, passport-country, passport-expiration, passport-number, pattern-in-file, pattern-in-memory, pattern-in-traffic, payment-details, pdb, pehash, pgp-private-key, pgp-public-key, phone-number, place-of-birth, place-port-of-clearance, place-port-of-onward-foreign-destination, place-port-of-original-embarkation, port, primary-residence, process-state, prtn, redress-number, regkey, regkey|value, sha1, sha224, sha256, sha3-224, sha3-256, sha3-384, sha3-512, sha384, sha512, sha512/224, sha512/256, sigma, size-in-bytes, snort, special-service-request, ssdeep, ssh-fingerprint, stix2-pattern, target-email, target-external, target-location, target-machine, target-org, target-user, telfhash, text, threat-actor, tlsh, travel-details, twitter-id, uri, url, user-agent, vhash, visa-number, vulnerability, weakness, whois-creation-date, whois-registrant-email, whois-registrant-name, whois-registrant-org, whois-registrant-phone, whois-registrar, windows-scheduled-task, windows-service-displayname, windows-service-name, x509-fingerprint-md5, x509-fingerprint-sha1, x509-fingerprint-sha256, xmr, yara, zeek
