### ISSUE TITLE
Feature Request: Attribute Galaxy/Tag toggle to duplicate at event level

### ISSUE THREAD

**Issue by JCMarques15** [MISP/MISP#8303]
### Is your feature request related to a problem? Please describe.

Hi all, so its not a problem per se, but more of a frustration. Me and my team disseminate a lot if information about threat actors and the tools they use. We quite often complement attributes with for example mitre att&ck techniques in the form of adding a galaxy directly to the attribute. Unfortunately there is also the need to have such techniques at the event level rather than just at the attribute level for the various consumers of the information we push. It becomes quite a frustrating task to add these techniques twice (one to the event, one to the attribute), as it is a relatively slow and 'clicky' process, worse when the number of such techniques is high for any given event. We know perhaps this stems from how we use MISP and might not be true for everyone, and that is why we came up with the solution described below.

### Describe the solution you'd like

After some though we came to the conclusion that perhaps when adding galaxies/tags to attributes, there could be a simple checkbox in the prompt that would toggle if the galaxy/tag is also to be added to the event at the same time. This way it would be as least intrusive to people that do have the need to keep event and attribute galaxies/tags separate. Hopefully it would not require extensive changes to the MISP codebase either.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
This was implemented in https://github.com/MISP/MISP/commit/c4f7a6e4f0bcaf7a08b9fc6c767d935bda3a3a65 and it will be available in the next release. We hope this helps.
