### ISSUE TITLE
Remove or hide org name while publishing

### ISSUE THREAD

**Issue by lu-chi** [MISP/MISP#8307]
Hi!
Is that possible to either remove/strip off the creator/owner name while publishing the event? I don;'t want that to be published when pushed to the other instances within community.

**Comment by adulau** [comment]
Nope but you can delegate the publishing to another organisation which can hide the original one. You just need first to create the event as your own organisation and check on the left side menu, you can delegate the publication to someone else. So you can create a fake org for publishing. I hope this helps.
