### ISSUE TITLE
Error: Could not get new event uuids for feed 2

### ISSUE THREAD

**Issue by gitingua** [MISP/MISP#8308]
### Support Questions

2022-04-27 19:11:24 Error: Could not get new event uuids for feed 2.
[Exception] Fetching the 'https://www.botvrij.eu/data/feed-osint/manifest.json' failed with exception: Connection timed out
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(268): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(172): Feed->getRemoteManifest()
#2 /var/www/MISP/app/Model/Feed.php(1141): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(43): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}[SocketException] Connection timed out
<img width="1433" alt="Снимок экрана 2022-04-27 в 19 32 57" src="https://user-images.githubusercontent.com/66623895/165568781-46bfe719-3ad0-4e4d-b56f-062addd3ca02.png">

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
I just checked the feed with the recent version of MISP and I was able to fetch it. I'll close the issue but don't hesitate to re-open the issue if the issue persists.
