### ISSUE TITLE
Update 2.3 to 2.4: Please, commit your changes or stash them before you can switch branches

### ISSUE THREAD

**Issue by pbo02** [MISP/MISP#831]
I'm upgrading from 2.3 to 2.4.

I first updated my 2.3 instance to be sure I'm up to date and then started the upgrade (as described in INSTALL/UPGRADE.txt).

I get an error when performing "git submodule init":
error: Your local changes to the following files would be overwritten by checkout:
        README.md
        pymisp/__init__.py
        pymisp/api.py
**Please, commit your changes or stash them before you can switch branches.**
Aborting
error: Your local changes to the following files would be overwritten by checkout:
        .htaccess
        .travis.yml
        CONTRIBUTING.md
        app/.htaccess
        app/Config/Schema/db_acl.php

        [...]

        lib/Cake/Model/Model.php
        lib/Cake/Model/ModelValidator.php
        lib/Cake/Model/Validator/CakeVal
Aborting
Cloning into 'app/files/taxonomies'...
remote: Counting objects: 156, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 156 (delta 66), reused 156 (delta 66), pack-reused 0
Receiving objects: 100% (156/156), 41.54 KiB | 0 bytes/s, done.
Resolving deltas: 100% (66/66), done.
Checking connectivity... done.
Submodule path 'app/files/taxonomies': checked out 'ad11b8b225697fd26c38969484cf33ec9e6cb898'
Unable to checkout '3a2414bc8c01687290245f186cfa72d29b99d09e' in submodule path 'PyMISP'
Unable to checkout '4de92123fa453f5e5eedd001a8918ad2976436af' in submodule path 'app/Lib/cakephp'

What should I do ?
Thanks !!

**Comment by Rafiot** [comment]
Is is probably a permission issue in the submodules.

Can you please try the following:

```
git submodule foreach git stash
git submodule foreach git pull
```

**Comment by pbo02** [comment]
`"git submodule foreach git stash"` solved the issue.
I then tried "git submodule foreach git pull" but got an error : 
   `Entering 'PyMISP'`
   `You are not currently on a branch. Please specify which`
   `branch you want to merge with. See git-pull(1) for details.`
    `   git pull <remote> <branch>`
   `Stopping at 'PyMISP'; script returned non-zero status.`
Instead I continued the upgrade procedure with `git submodule update` and it ran without error this time. So I think that the issue is solved.

FYI, I had another error later with the following section of the upgrade procedure : 
`    # clear the old submodule cached entry for CakeResque`
`   cd /var/www/MISP`
`   git rm --cached app/Plugin/CakeResque/`
I got the error :
`   fatal: pathspec 'app/Plugin/CakeResque/' did not match any files`
Perhaps this error just means that there is nothing to remove ?
Or perhaps I should have changed the command into ` "git rm --cached app/Plugin/CakeResque/*" `?

I expect I have not messed my installation ...
I had no any other error during the update procedure. I have now I error when performing a "sync" with another instance, but I will cover that in another post.

Thank you very much for your advice !

**Comment by Rafiot** [comment]
No worries, you had this error because there was nothing to remove.

I'm looking forward to read your next post :)

**Comment by Bahmad92** [comment]
1: git stash
2: git pull (remoteurl)
3: git stash apply
