### ISSUE TITLE
Visual CSV import

### ISSUE THREAD

**Issue by deresz** [MISP/MISP#832]
Implement a CSV import with a preview, on which a user could define the format of the CSV, similar to Excel CSV import. So for example, if you have a file like this:

1.1.1.1 \t This is a sinkholed IP
2.2.2.2 \t This is a C&C IP

A user could tell the MISP that the file is a TAB-separated CSV and that the first column should be treated with FreeText import to create a value of the attribute, and the second column should be added as a comment.

**Comment by adulau** [comment]
The feed functionality include a CSV parser and a preview. Does this solve your issue? I'll close the issue and feel free to reopen if this doesn't solve your issue. Thank you.
