### ISSUE TITLE
Feature Request: Add attributes.timestamp database index for performance improvement

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8329]
### Is your feature request related to a problem? Please describe.

We do a lot of PyMISP client apps looking at `Attributes` qualified by their `timestamp`. Some of these apps take a very long time to process.

We see that `attributes.timestamp` is not a database index.

Testing the query time for a database query like the following we see:
**a 50 fold improvement with the index!!**
- 5 minutes: no index (with `db_version=85` now in 2.4.158)
- 5 **seconds**: with an index

```
SELECT COUNT(*) AS `count` FROM `misp`.`attributes` AS `Attribute` 
LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event_id` = `Event`.`id`) 
LEFT JOIN `misp`.`objects` AS `Object` ON (`Attribute`.`object_id` = `Object`.`id`) 
WHERE ((`Attribute`.`timestamp` >= 1651331183) AND (`Attribute`.`deleted` = '0'))
```

### Describe the solution you'd like

Can the `timestamp` column in the `attributes` table be an index?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
WOAH. That's a nice catch. I just checked and the index is indeed missing, we'll add this in the next release.

**Comment by github-germ** [comment]
THANKS!!

**Comment by packet-rat** [comment]
Can we get first_seen, last_seen indexed as well (if not currently)?

**Comment by github-germ** [comment]
`first_seen` and `last_seen` are already indexes in the `attributes` table.
