### ISSUE TITLE
Installation/updating issues in Ubuntu 14.04 (workers + cybox/styx libs). MISP 2.4

### ISSUE THREAD

**Issue by sn8doc** [MISP/MISP#833]
Hey guys,

Clean installation in a Ubuntu 14.04.3 box : 

I had to do "apt-get install snmp-mibs-downloader" (not mentioned in the guide) in order to make the workers function correctly.  I didn´t analyze this further, but before installing the mibs  I got several errors like this when restarting the workers : 

Cannot adopt OID in UCD-SNMP-MIB: ssSysContext ::= { systemStats 8 }

In addition, following the INSTALL.ubuntu14 guide all is working fine, except : 
1. Cybox + Stix Libraries : The diagnostics page keeps showing "STIX or CyBox library not installed correctly" no matter what. I installed the libraries following the guide (no errors) AND through pip install ...the problem persist. 
2. When updating and trying : 
   cd /var/www/MISP/app/Lib/cakephp
   git fetch origin
   git checkout 2.6

I get :  error: pathspec '2.6' did not match any file(s) known to git

Although I don´t see any symptoms that could indicate that Cake is not working.

**Comment by iglocska** [comment]
That is weird, I'll try to do a fresh install soon and see what's causing that. Especially snmp-mibs-downloader - never had this issue before, so maybe one of the dependencies changed. I'll have a look.

For the first one: Not sure yet, will test it.
For the second, 2.6 is now obsolete, go with 2.7 or if all else fails just remove your cakephp directory  and run the following from /var/www/MISP:

git submodule init
git submodule update

**Comment by elhoim** [comment]
@bane0 do you have another PHP application running that is trying to do something with SNMP?

**Comment by bane0** [comment]
Nope, it was an installation from scratch, no other apps/services running.

**Comment by grolinet** [comment]
FWIW:
I had the same Problem with stix after upgrading MISP from Version 2.3. 
The "STIX or CyBox library not installed correctly" was showed and trying to export a stix export got me an internal Server error. (well, that was no surprise after the message ;) )
However the stixtest.py (/var/www/MISP/app/files/scripts/stixtest.py) could successfully load both the stix and the cybox library.

This fixed it for me:
1. delete/rename the whole python-stix directory. (in /var/www/MISP/app/files/scripts/)
2. From the Installation doc:
```
git clone https://github.com/STIXProject/python-stix.git
cd /var/www/MISP/app/files/scripts/python-stix
git checkout v1.1.1.4
python setup.py install
```

**Comment by Rafiot** [comment]
Thank you for the feedback.

**Comment by adulau** [comment]
I suppose this issue has been resolved. If not, feel free to reopen the issue. Thank you.
