### ISSUE TITLE
Bug: Import Stix2 causes Error: [ProcessException]

### ISSUE THREAD

**Issue by Rogueit** [MISP/MISP#8330]
### Expected behavior

Import stix2 json file
```
{
  “type”: “bundle”,
  “id”: “bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  “spec_version”: “2.0",
  “objects”: [
    {
      “type”: “indicator”,
      “id”: “indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f”,
      “created”: “2014-06-29T13:49:37.079000Z”,
      “modified”: “2014-06-29T13:49:37.079000Z”,
      “labels”: [
        “malicious-activity”
      ],
      “name”: “Malicious site hosting downloader”,
      “pattern”: “[url:value = ‘http://x4z9arb.cn/4712/’]“,
      “valid_from”: “2014-06-29T13:49:37.079000Z”
    },
    {
      “type”: “malware”,
      “id”: “malware--162d917e-766f-4611-b5d6-652791454fca”,
      “created”: “2014-06-30T09:15:17.182Z”,
      “modified”: “2014-06-30T09:15:17.182Z”,
      “name”: “x4z9arb backdoor”,
      “labels”: [
        “backdoor”,
        “remote-access-trojan”
      ],
      “description”: “This malware attempts to download remote files after establishing a foothold as a backdoor.“,
      “kill_chain_phases”: [
        {
          “kill_chain_name”: “mandiant-attack-lifecycle-model”,
          “phase_name”: “establish-foothold”
        }
      ]
    },
    {
      “type”: “relationship”,
      “id”: “relationship--6ce78886-1027-4800-9301-40c274fd472f”,
      “created”: “2014-06-30T09:15:17.182Z”,
      “modified”: “2014-06-30T09:15:17.182Z”,
      “relationship_type”: “indicates”,
      “source_ref”: “indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f”,
      “target_ref”: “malware--162d917e-766f-4611-b5d6-652791454fca”
    }
  ]
}
```

### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

```
2022-05-03 14:43:39 Error: [ProcessException] Command '/var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPbe1cxG 1 event /var/www/MIS>
STDERR: ''
STDOUT: ''
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(5793): ProcessTool::execute()
#1 /var/www/MISP/app/Controller/EventsController.php(2414): Event->upload_stix()
#2 [internal function]: EventsController->upload_stix()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#7 {main}
```

### Steps to reproduce

Event Actions => Add Event => Import from => stix 2 Format => Choose file => upload

### Version

v2.4.158

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

PHP 7.4.3 

### Browser

Chrome

### Browser version

Current

### Relevant log output

```shell
2022-05-03 14:43:39 Error: [ProcessException] Command '/var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPbe1cxG 1 event /var/www/MIS>
STDERR: ''
STDOUT: ''
Request URL: /events/upload_stix/2
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(5793): ProcessTool::execute()
#1 /var/www/MISP/app/Controller/EventsController.php(2414): Event->upload_stix()
#2 [internal function]: EventsController->upload_stix()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#7 {main}
```
```


### Extra attachments

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Hello,
I looked at it and used the sample to reproduce the issue.

On my side what is raising an issue are the `"` and `'` characters that are not the standard ones.
It actually fails when the script calls the loading method from the STIX 2 python library, and even the standard JSON library does not accept it since the `"` and `'` that are used are not the standard quote and double quote characters that should be used, as you can see in the following:

![image](https://user-images.githubusercontent.com/16307976/168272294-2097fff7-acf2-40a7-a4c4-12e87a813457.png)

Would it be possible you can get this data encoded with the valid quote and double quote characters? 
I also tested by replacing the characters that cause the issue with the valid ones and encountered no further issue to import the sample in MISP

**Comment by sholland-bamboohealth** [comment]
Can you confirm that this sample has been cleared of any non standard quotes and double quotes? I am still getting the error after finding and replacing the non standard characters
`{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "indicator",
      "id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
      "created": "2014-06-29T13:49:37.079000Z",
      "modified": "2014-06-29T13:49:37.079000Z",
      "labels": [
        "malicious-activity"
      ],
      "name": "Malicious site hosting downloader",
      "pattern": "[url:value = 'http://x4z9arb.cn/4712/']",
      "valid_from": "2014-06-29T13:49:37.079000Z"
    },
    {
      "type": "malware",
      "id": "malware--162d917e-766f-4611-b5d6-652791454fca",
      "created": "2014-06-30T09:15:17.182Z",
      "modified": "2014-06-30T09:15:17.182Z",
      "name": "x4z9arb backdoor",
      "labels": [
        "backdoor",
        "remote-access-trojan"
      ],
      "description": "This malware attempts to download remote files after establishing a foothold as a backdoor.",
      "kill_chain_phases": [
        {
          "kill_chain_name": "mandiant-attack-lifecycle-model",
          "phase_name": "establish-foothold"
        }
      ]
    },
    {
      "type": "relationship",
      "id": "relationship--6ce78886-1027-4800-9301-40c274fd472f",
      "created": "2014-06-30T09:15:17.182Z",
      "modified": "2014-06-30T09:15:17.182Z",
      "relationship_type": "indicates",
      "source_ref": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
      "target_ref": "malware--162d917e-766f-4611-b5d6-652791454fca"
    }
  ]
`

**Comment by chrisr3d** [comment]
Never mind, it goes right with the python scripts that converts the STIX data into MISP format, but fails then to import the `indicator` object.

I discovered the issue comes during the data validation.
Since the conversion to MISP keeps the UUIDs, the indicator id `d81f86b9-975b-bc0b-775e-810c5ad45a4f` does not pass the validation process.

The issue here is the following:
MISP only accepts RFC 4122 compliant UUIDs

I'll fix the scripts to generate valid UUIDs when the ones provided are not

**Comment by Rogueit** [comment]
Sorry I'm just getting around to replying...I appreciate the follow up. Will I just need to update misp internally from http://misp/servers/serverSettings/diagnostics?

**Comment by chrisr3d** [comment]
Hey, I updated the stix2 python library to make sure there would not be any further issue while loading a stix file (at least there should not)
And I updated the import script to keep the reference of the initial id when it is not valid for MISP

It was waiting on a develop branch to be merged and it is now available with the last release.
So make sure to pull the latest version and update your submodules (especially `app/files/scripts/misp-stix` in our case here) and it should be good

Let me know if anything goes wrong after this update

**Comment by Rogueit** [comment]
I've updated and am getting files imported from the feed. I noticed a lot of files are not getting based on the name or pattern listed in the file, but that is a different issue. Thank you for your time on this.
