### ISSUE TITLE
Support: ¿how can I enable the "Extract Entities" option?

### ISSUE THREAD

**Issue by jdcardona07** [MISP/MISP#8333]
### Support Questions

how can I enable the "Extract Entities" option.

I do not have the option enabled to automatically extract indicators, threat intelligence as a threat actor from the reports.

![image](https://user-images.githubusercontent.com/98642593/166724027-f887d9df-b659-4b8e-9a1b-53afab42bad4.png)

### MISP version

2.4.158

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Chrome

### Extra attachments

![image](https://user-images.githubusercontent.com/98642593/166724097-ed26a75a-1898-4d62-96fd-05965286e35d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jdcardona07** [comment]
enabled modules:
![image](https://user-images.githubusercontent.com/98642593/166724987-2b359f6b-1615-48de-b7dd-04cfd9b82d79.png)

**Comment by adulau** [comment]
Indeed, it was a bug. It's now fixed in https://github.com/MISP/MISP/commit/5d86dd0f808e39b6f0a95605dcdc0760453a327d

Thank you for the notification.
