### ISSUE TITLE
Bug: Extract entities not showing.

### ISSUE THREAD

**Issue by nyx0** [MISP/MISP#8334]
### Expected behavior

Extract entities menu available.

### Actual behavior

Extract entities does not appear in the menu `Markdown parsing rules`

### Steps to reproduce

Import From URL
Menu
...

MISP-modules is up and running

### Version

v2.4.158 (e608ee5cd774009709a838d9d0285f2f38d539a9) 

### Operating System

Debian

### Operating System version

10

### PHP version

7.3.31-1

### Browser

Safari

### Browser version

15.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Indeed, it was a bug. It's now fixed in https://github.com/MISP/MISP/commit/5d86dd0f808e39b6f0a95605dcdc0760453a327d

Thank you for the notification.
