### ISSUE TITLE
Bug: Some characters in event info rendered in browser as html entities

### ISSUE THREAD

**Issue by UFOSmuggler** [MISP/MISP#8335]
### Expected behavior

Creating an event with event info "\<hello\>" and pressing submit should result in an event rendering in the browser with an event title of "\<hello\>".

### Actual behavior

In the browser the event title appears as "\&lt;hello\&gt;".  However, lower in the page, in the event info section, it is rendered correctly.

Examining the json shows the event info to be < and >, not the html entities.

I am not sure if other characters also do this, but I assume so.

### Steps to reproduce

Create an event with <> chars.

### Version

2.4.158

### Operating System

Ubuntu and rhel

### Operating System version

20.04 and rhel 7.9

### PHP version

7.4

### Browser

chrome

### Browser version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Hello, thanks for report. It is already fixed in `develop` brach, so It will be fixed in next version.
