### ISSUE TITLE
Support: misp-modules - VT enrichment blocked

### ISSUE THREAD

**Issue by lightman63** [MISP/MISP#8338]
### Support Questions

Hello,

I have an issue on MISP about misp-modules VT.
Normally it's worked but sometimes it's blocked with this following message : "Module results ingestion queued for background processing. Related data will be added to the event as it is being processed." 
![image](https://user-images.githubusercontent.com/61386677/166961717-f43844fe-15ed-4f01-8af0-a66c721996af.png)

I tried to reboot daemon httpd, php-fpm, misp-modules, misp-workers with no effect.
I tried to reboot MISP server with no effect.

error.log : 
Request URL: /cgi/mid.cgi
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#1 {main}
2022-05-05 13:56:16 Error: [MethodNotAllowedException] Attribute not found or you are not authorised to see it.
Request URL: /events/queryEnrichment/5343546/virustotal/Enrichment
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}

It's the only event from error.log. Other try doesn't have error in log.

On MISP jobs page I have this result for all enrichment requests.
![image](https://user-images.githubusercontent.com/61386677/166961540-a5d24289-42e4-45cb-90b2-9f636732544a.png)

Do you have some solution to reinitialize misp-modules engines?

Thank you

### MISP version

2.4.150

### Operating System

RedHat

### Operating System version

8.2

### PHP version

7.4

### Browser

Firefox

### Browser version

78.9

### Relevant log output

```shell
error.log : 
Request URL: /cgi/mid.cgi
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#1 {main}
2022-05-05 13:56:16 Error: [MethodNotAllowedException] Attribute not found or you are not authorised to see it.
Request URL: /events/queryEnrichment/5343546/virustotal/Enrichment
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lightman63** [comment]
Hello,

Do you have somes work around about this issue?

**Comment by lightman63** [comment]
Resolved.
Indicator used to enrich ever exists but soft deleted.
Close issue.

**Comment by MU-03** [comment]
I am having issue with enrichment module in  MISP , there are no options available to select for enrichment , I am attaching the snapshot of modules, do you know what might the problem be?
Regards
![01](https://user-images.githubusercontent.com/118333194/210974674-b8538be1-4ba4-446f-ad6d-42f9e73276d9.PNG)

**Comment by adulau** [comment]
@MU-03 you need also to enable each of the module you want, not only the expansion module service. I bet that's why you don't have any in the list.  Next time, it would be nicer to open an new issue instead of reply on an unrelated issue. Thank you.

**Comment by MU-03** [comment]
> @MU-03 you need also to enable each of the module you want, not only the expansion module service. I bet that's why you don't have any in the list. Next time, it would be nicer to open an new issue instead of reply on an unrelated issue. Thank you.

I am so sorry , I am new to both  github and misp i'm still learning the process. I'll definitely keep this in mind next time. Thank you.
