### ISSUE TITLE
Bug: proc_open error when using SimpleBackgroundJobs

### ISSUE THREAD

**Issue by hartek** [MISP/MISP#8359]
### Expected behavior

A job is started and dispatched by one of the currently running workers that `supervisord` shows as running. 

### Actual behavior

The job is created in MISP, but it never gets started. The following error appears on `/var/www/MISP/app/tmp/logs/misp-workers-errors.log`: 

![imagen](https://user-images.githubusercontent.com/11649585/167657993-53bead13-00af-4deb-a84c-968b48d81e72.png)

It would seem as if `proc_open` would be invoked wrong. The error points to line 88 under `/var/www/MISP/app/Lib/Tools/BackgroundJobs/BackgroundJob.php`, which has the following content under the function `run()`: 

![imagen](https://user-images.githubusercontent.com/11649585/167658693-66e8614a-4214-4164-90ca-1c88e913b780.png)

Additionally, the following appears on the `supervisord` logs under `/var/log/supervisor/supervisord.log`, reflecting the `prio` worker failing and then restarting via Supervisor:

![imagen](https://user-images.githubusercontent.com/11649585/167661303-fb67799b-c2b7-4943-a7da-d552234abbd2.png)

### Steps to reproduce

- I configured `SimpleBackgroundJobs` to be used, and check the user and password does indeed work and the workers are running under `supervisord`. I can check these by tunnelling into the machine's port `9001/tcp`. 

![imagen](https://user-images.githubusercontent.com/11649585/167659224-563b6a53-5bb1-4e20-8db4-7a9b75c8bcc6.png)

- I create any job, for instance publishing an event without email. The job appears as running with an Unknown status forever. 

![imagen](https://user-images.githubusercontent.com/11649585/167662182-d1d56d1b-e634-400b-b2bc-8387eb69ac8d.png)

If I revert back to "classic" background jobs, the issue does not appear and jobs are completed correctly. 

### Version

2.4.158

### Operating System

RedHat Enterprise Linux 8

### Operating System version

8.2

### PHP version

7.3

### Browser

Firefox

### Browser version

99

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @hartek 
This feature requires PHP >=7.4.
see: https://www.php.net/manual/en/function.proc-open.php

As PHP 7.3 reached EOL, I recommend you to update to PHP 7.4 and try again.

Hope this helps.
