### ISSUE TITLE
Bug:  v2.4.158 "Contact Users" feature shows "Internal Error Has Occurred"

### ISSUE THREAD

**Issue by bpavesi** [MISP/MISP#8363]
### Expected behavior

With "Contact Users" feature,  administrator can send mail messages to MISP users .

### Actual behavior

When sending a message, the following error is shown:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

1. Select "Contact Users" from "Administration" menu
2. Fill the fields  as following:
  - Action: Custom message
  - Subject: test
  - Recipient: A single user
  - Recipient mail: select a mail address
  - Message: test
3. Click "Submit"   

### Version

v2.4.158

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Browser version

101.0.4951.54

### Relevant log output

```shell
2022-05-12 13:30:46 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'adminMessageResolve' at line 1
Request URL: /admin/users/email
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(648): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(834): DboSource->query()
#5 /var/www/MISP/app/Controller/UsersController.php(1640): Model->__call()
#6 [internal function]: UsersController->admin_email()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bpavesi** [comment]
Hello,
the fix will be avaiable in the next release?

**Comment by bpavesi** [comment]
Hi @JakubOnderka,
the fix will be avaiable in the next release?

Thank you

**Comment by adulau** [comment]
Yes it will be. Thanks @JakubOnderka for the fix.
