### ISSUE TITLE
Feature Request: Add a test if the PHP session handler is file based

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#8366]
### Is your feature request related to a problem? Please describe.

Feature Request: Add a test if the session is file based

### Describe the solution you'd like

Add a test in the settings to find out if the sessions are handled by files in PHP instead of Redis. (as it can be a significant performance issue)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
merged to develop via #8393
