### ISSUE TITLE
Feature Request: Abilty to hide organisation names in Sharing Groups.

### ISSUE THREAD

**Issue by RoyClark992** [MISP/MISP#8368]
### Is your feature request related to a problem? Please describe.

Currently when organisations are added to a sharing everyone is able to see other organisation names. There is no way
of hiding other organisations in sharing groups.

### Describe the solution you'd like

A MISP setting similar to 'MISP.showorg' maybe called .MISP.ShowSG' and if set to false it will hide the organisations names within sharing groups. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Hello. You can try to use `MISP.hide_organisations_in_sharing_groups` and `MISP.hide_organisation_index_from_users` options.

**Comment by RoyClark992** [comment]
Brilliant I will try it out

**Comment by RoyClark992** [comment]
Will use above setting
