### ISSUE TITLE
Check permissions on config files

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#837]
If the permissions of the config files is wrong (the user of the webserver doesn't have the right to edit), trying to edit them should fail with an error message on the web interface and in the logs instead of silently as it does now.

**Comment by RichieB2B** [comment]
I would argue those permissions (webserver can only read config files, not write them) are correct in a corporate environment. But I agree an attempt to change the config using the web UI in this situation should produce a visible error.

**Comment by Rafiot** [comment]
@RichieB2B well, the access to the config is only possible for admin accounts only anyway. But yeah, you should not be able to edit them if your webserver doesn't have the write perms.

**Comment by Rafiot** [comment]
I see 710828d3973811adc519f58be10d6254ad9fec49 partially fixes the issue. I'd still like to see a message informing me that I'm in read only mode directly in the config page, so I'll not try to edit the file.

**Comment by iglocska** [comment]
Yup this was one of those changes that I did while I was touching that part
of the code already, we definitely should have it on the config pages too.

**Comment by adulau** [comment]
@iglocska Thank you.
