### ISSUE TITLE
Support: MISP sending reset packet when establishing session to list feed server.

### ISSUE THREAD

**Issue by mwdearing** [MISP/MISP#8371]
### Support Questions

On Wednesday this week an issue started occurring where one of our custom list feed were failing to connect. From the host I am able to pull the feed down through a python script without issues and upon doing a packet capture I see the following: 

![image](https://user-images.githubusercontent.com/63065566/168320431-f2cd5af6-8586-46a2-85ae-36ec7a727290.png)

### MISP version

2.4.158

### Operating System

RedHat

### Operating System version

7.9

### PHP version

7.4.24

### Relevant log output

```shell
2022-05-13 15:30:39 Error: Could not get new event uuids for feed 72.
[Exception] Fetching the 'https://fp.tools/api/v4/indicators/misp-feed/manifest.json' failed with exception: Connection timed out
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(268): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(172): Feed->getRemoteManifest()
#2 /var/www/MISP/app/Model/Feed.php(1141): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#8 {main}[SocketException] Connection timed out
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Could you share with us the manifest.json generated by FlashPoint ?

**Comment by mwdearing** [comment]
Here is the manifest.json file generated by FP.

[manifest_json.txt](https://github.com/MISP/MISP/files/8833445/manifest_json.txt)
