### ISSUE TITLE
Audit logs to Syslog

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#838]
It could be useful o meet some security requirements by being able to add a Syslog export for the audit log.

It seems that @cvandeplas mentioned something similar in:

https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.sysop.txt

"To supply the NATO STANAG AACP-2 VOLUME 9
MISP writes (audit) log lines to syslog."

But not sure if this is really up to date or if it was at implemented at some point.

**Comment by adulau** [comment]
Maybe the best would add in the audit layer of MISP a configuration to send the logs in addition to Syslog or a Redis Pub/Sub channel.

Not sure about this current code coverage and usage: https://github.com/MISP/MISP/blob/0548820a35c6339ae499027cb69228a9a0150c98/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php @iglocska any idea?

**Comment by iglocska** [comment]
It logs some things but it's far from complete. We'd need to either build on top of it or just rework the logging altogether (which would probably be better).

**Comment by adulau** [comment]
Following a feedback during a training, why not using the pub-sub channel to publish the logs in a channel and especially the very verbose log like the audit log.

**Comment by iglocska** [comment]
We could indeed try it!

**Comment by adulau** [comment]
This has been fixed with the introduction of the ZMQ audit feed.
