### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by tknudsec** [MISP/MISP#8386]
### Support Questions

Hello,

We are trying to install MISP with just the basic function (-c) using the MISP installation guide for Ubuntu 20.04 by following these steps here: https://misp.github.io/MISP/INSTALL.ubuntu2004/

We are installing in our test environment from scratch right after we set up a fresh Ubuntu 20.04 vm. To connect to the internet we need to configure the proxy settings for everything thats needed to install and download from the script. We were able to set the proxy (http and https) for git global config, path variable, wget conf, and apt conf, (are we missing any locations that need to have the proxy set for?)

It seems we always get stuck  at the same error when it tries to clone in the script: 
"Cloning into '/var/www/MISP'...
fatal: unable to access 'https://github.com/MISP/MISP.git/': gnutls_handshake() failed: Error in the pull function."

we tried googling this error which led to posts mentioning that we need to set the proxy for git which we did (for http and https).. not sure how to proceed at all and we would like to request assistance.. please help.

### MISP version

2.4.158

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

NA (Should install when running the script)

### Relevant log output

```shell
Cloning into '/var/www/MISP'...
fatal: unable to access 'https://github.com/MISP/MISP.git/': gnutls_handshake() failed: Error in the pull function.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Looks like your proxy is not supporting TLS handshake. It's not directly related to MISP. You need to export the proper HTTP_PROXY env value.

**Comment by tknudsec** [comment]
how do we do this exactly (to verify we are doing properly) , should it be http or https proxy?
