### ISSUE TITLE
Support: 504 GATEWAY_TIMEOUT when getting events via API

### ISSUE THREAD

**Issue by m4rb3n** [MISP/MISP#8388]
### Support Questions

I am having an error when getting events from the database. Since there are a lot of events, it will use lots of memory. 
I know how to increase memory to solve this error and that is what I am being doing until now. But now I am questioning how MISP handles retrieving lots of events from the database.
Is there any way to get lots of events with increase memory limits anymore?
The restapi have an argument that limits the number of events retrieved but it does not seem to be working.

I am missing something here?

Thanks

### MISP version

2.4.148

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox

### Browser version

latest

### Relevant log output

```shell
2022/05/18 13:48:49 [error] 267#267: *576 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 69632 bytes) in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php on line 728" while reading response header from upstream, client: 10.143.77.126, server: , request: "GET /events/restSearch/returnFormat:json/type:ip-dst/type:ip-dst%7Cport/from:2022-05-17/to:2022-05-19 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "mymisp.local"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Could you review your API queries and to include a `limit` and `page` to ensure that you limit the returned values to avoid such kind of issue.  The header `X-Result-Count` allow you to know the upper limit. If you are using `limit` and `page`, could you share your query? 

PS: Could you also update your MISP to the latest version?

**Comment by m4rb3n** [comment]
Hey, the query I am using is this one. 
wget -O misp_output.json --header="Authorization: <api_key>" "https://misp.local/events/restSearch/returnFormat:json/type:ip-dst/type:ip-dst|port/last:4h"

We installed MISP on kubernetes and unfortunately doing the update is not as easy as it seems.

**Comment by adulau** [comment]
As I mentioned above, you might need to paginate with `limit`and `page` especially if your dataset is large.
