### ISSUE TITLE
Add check for values on diagnostics page

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#839]
For values of PHP max execution time, and max memory allowed.

To help solve issues like #829.

Sub-ideas:
- Suggest higher default value? 
- Suggest higher value based on a rule of thumb & number of indicators in instance?

**Comment by iglocska** [comment]
I've added 4 settings for now to it with some hard coded values. Having something based on the number of indicators would be fantastic! We do need to do a bunch of load testing to get some sane numbers though. For now I went with the following:

max_execution_time: 300
memory_limit: 512M
upload_max_filesize: 50M
post_max_size: 50M

**Comment by Rafiot** [comment]
Fixed, right? More granularity in the recommendations doesn't seems particularly important.

**Comment by iglocska** [comment]
We can get back to this at a later point in time, but this is really a nice to have.
