### ISSUE TITLE
Support:  Error when import STIX2 json file.

### ISSUE THREAD

**Issue by ServSlack** [MISP/MISP#8404]
### Support Questions

Today I do a fresh install with Ubuntu 20.04 and MISP Modules, but when try to import some STIX2 file in JSON format 
I receiving the message " An Internal Error Has Occurred. " I also search for some resolution inside " gitter " and I have followed all steps from this document " https://www.circl.lu/doc/misp/updating-python/ " check all dependencies and misp modules, but according images attached apparently I don´t have any problem and all library status are OK.

Can you please give some path to follow and try solve this problem ?

### MISP version

v2.4.158

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox

### Browser version

100.0.2

### Relevant log output

```shell
root@96eb72c0c479:/var/www/MISP/app/tmp/logs# tail -f exec-errors.log
[2022-05-24 19:02:15 69] Running command /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPgeVodq 1 event /var/www/MISP/app/files/scripts/tmp/synonymsToTagNames.json
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2083, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2075, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
[2022-05-24 19:02:16 69] Process finished with return code 1
```

### Extra attachments

![image](https://user-images.githubusercontent.com/32932095/170139557-1377d611-9f53-4013-85e9-de6185602b22.png)
![image](https://user-images.githubusercontent.com/32932095/170139616-e9e3ea9f-a3d1-4c86-b1a7-a8d0ab5e4a4a.png)
![image](https://user-images.githubusercontent.com/32932095/170139881-a971a291-9393-4dd0-b502-48d0ca098eaf.png)
![image](https://user-images.githubusercontent.com/32932095/170140171-1725f92c-0489-4428-88bf-9d233ca6bd30.png)
![image](https://user-images.githubusercontent.com/32932095/170140226-7c579271-6943-49f5-89c7-38c14b3cc86b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
It seems a recent bug was introduced and fixed in the meantime. 

https://github.com/MISP/cti-python-stix2/commit/625576622f3e7f2541d2e788d70ed4997e134837

If you get pull the latest version on 2.4 branch, it should work.

**Comment by adulau** [comment]
I'll close the issue. If it's not solved, please re-open it. Thank you

**Comment by ServSlack** [comment]
I have done the update manually and works fine here, but only to let you know I do another test trying update using botton " Action " to " Update all Submodules " and don´t work.

Thanks.

![image](https://user-images.githubusercontent.com/32932095/170481076-2695deda-b804-4251-9418-a4ff3d8a0c25.png)
