### ISSUE TITLE
Messages from getGenerateCorrelationProgess in error.log

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#841]
Today while performing a scheduled pull I saw the following message in my error.log many times:

==> error.log <==
Request URL: /jobs/getGenerateCorrelationProgress/4353
Stack Trace:
#0 /var/www/MISP/app/Controller/JobsController.php(21): AppController->beforeFilter()
#1 [internal function]: JobsController->beforeFilter(Object(CakeEvent))
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(JobsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

**Comment by Rafiot** [comment]
Does it still happen?

**Comment by h122015** [comment]
Yes, it still happens, but I just noticed that it is always preceded by the following line:

2016-02-05 16:07:35 Error: [ForbiddenException] Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.

**Comment by h122015** [comment]
I haven't seen this error lately.

**Comment by Rafiot** [comment]
Thanks, closing then :)
