### ISSUE TITLE
Undefined index: distribution

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#842]
Today while doing an scheduled pull I saw the following message in resque-worker-error.log:

Notice Error: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]

2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]
Notice Error: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]

2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]

**Comment by iglocska** [comment]
OK, that definitely sounds wrong. Would be interesting to see the event that caused this.

**Comment by elhoim** [comment]
@h122015 could you provide, privately if needed, the event that cause this error?

**Comment by h122015** [comment]
Sorry for the slow answer. I tried to single out the event that caused this but I wasn't able to do so. This is all that I found in my logs when looking for that timestamp:

$ grep '2016-01-11 18:38:14' *.log
debug.log:2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]
debug.log:2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: done ID:e377ffdfa98d7c66fd114088937cba93 {"type":"done","job_id":"e377ffdfa98d7c66fd114088937cba93","time":31858699,"worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: got {"queue":"default","id":"d912d202b8f6b231beda9a18194c688a","class":"ServerShell","args":[{"0":"enqueuePull","1":1420965000,"2":"1","3":"2","s_time":1452502048}]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"d912d202b8f6b231beda9a18194c688a","class":"ServerShell","args":[{"0":"enqueuePull","1":1420965000,"2":"1","3":"2","s_time":1452502048}]})","worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: Processing ID:d912d202b8f6b231beda9a18194c688a in default {"type":"process","worker":"misp.my.org:8933","job_id":"d912d202b8f6b231beda9a18194c688a"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: done ID:d912d202b8f6b231beda9a18194c688a {"type":"done","job_id":"d912d202b8f6b231beda9a18194c688a","time":45,"worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: got {"queue":"default","id":"b977e6e7e98c9bd6ce5820be8b30c5be","class":"EventShell","args":[["publish","749",null,"4355","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"b977e6e7e98c9bd6ce5820be8b30c5be","class":"EventShell","args":[["publish","749",null,"4355","1"]]})","worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: Processing ID:b977e6e7e98c9bd6ce5820be8b30c5be in default {"type":"process","worker":"misp.my.org:8933","job_id":"b977e6e7e98c9bd6ce5820be8b30c5be"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: done ID:b977e6e7e98c9bd6ce5820be8b30c5be {"type":"done","job_id":"b977e6e7e98c9bd6ce5820be8b30c5be","time":100,"worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: got {"queue":"default","id":"fc6a524f57449c8d9f3f6d01e590bbeb","class":"EventShell","args":[["publish","769",null,"4357","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"fc6a524f57449c8d9f3f6d01e590bbeb","class":"EventShell","args":[["publish","769",null,"4357","1"]]})","worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: Processing ID:fc6a524f57449c8d9f3f6d01e590bbeb in default {"type":"process","worker":"misp.my.org:8933","job_id":"fc6a524f57449c8d9f3f6d01e590bbeb"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: done ID:fc6a524f57449c8d9f3f6d01e590bbeb {"type":"done","job_id":"fc6a524f57449c8d9f3f6d01e590bbeb","time":100,"worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: got {"queue":"default","id":"16bed140202b5950aeeb6a7d094895c8","class":"EventShell","args":[["publish","1625",null,"4413","1"]]} {"type":"got","args":"[object](Resque_Job: {"queue":"default","id":"16bed140202b5950aeeb6a7d094895c8","class":"EventShell","args":[["publish","1625",null,"4413","1"]]})","worker":"misp.my.org:8933"} []
resque-2016-01-11.log:[2016-01-11 18:38:14] main.INFO: Processing ID:16bed140202b5950aeeb6a7d094895c8 in default {"type":"process","worker":"misp.my.org:8933","job_id":"16bed140202b5950aeeb6a7d094895c8"} []
resque-worker-error.log:2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]
resque-worker-error.log:2016-01-11 18:38:14 Notice: Undefined index: distribution in [/var/www/MISP/app/Model/Event.php, line 2138]

While we are at it, I've noticed also the following messages in the same log:

Notice Error: Undefined index: event_uuid in [/var/www/MISP/app/Model/Event.php, line 2006]
2016-02-11 11:00:14 Notice: Undefined index: event_uuid in [/var/www/MISP/app/Model/Event.php, line 2006]

This time I could find some information regarding the event:

$ grep '2016-02-11 11:00:14' *.log
debug.log:2016-02-11 11:00:14 Notice: Undefined index: event_uuid in [/var/www/MISP/app/Model/Event.php, line 2006]
resque-worker-error.log:/var/www/MISP/app/tmp/logs/[8094]: 2016-02-11 11:00:14 Notice: Attribute "2c4aeacd3f7b587c599c2c4b5c1475da" (226289) added by User "SYSTEM" (0). -- distribution () => (5), type () => (md5), category () => (Payload delivery), uuid () => (56bc3cb3-a5ec-470b-8783-6af1950d210f), event_id () => (2115), comment () => (https://securelist.com/blog/research/73673/poseidon-group-a-targeted-attack-boutique-specializing-in-global-cyber-espionage/), value1 () => (2c4aeacd3f7b587c599c2c4b5c1475da)
resque-worker-error.log:/var/www/MISP/app/tmp/logs/[8094]: 2016-02-11 11:00:14 Notice: Attribute "f821eb4be9840feaf77983eb7d55e5f6" (226290) added by User "SYSTEM" (0). -- distribution () => (5), type () => (md5), category () => (Payload delivery), uuid () => (56bc3cb4-e540-4f2e-ad20-6af1950d210f), event_id () => (2115), comment () => (https://securelist.com/blog/research/73673/poseidon-group-a-targeted-attack-boutique-specializing-in-global-cyber-espionage/), value1 () => (f821eb4be9840feaf77983eb7d55e5f6)
resque-worker-error.log:2016-02-11 11:00:14 Notice: Undefined index: event_uuid in [/var/www/MISP/app/Model/Event.php, line 2006]
resque-worker-error.log:/var/www/MISP/app/tmp/logs/[8094]: 2016-02-11 11:00:14 Notice: ShadowAttribute "https://securelist.com/blog/research/73673/poseidon-group-a-targeted-attack-boutique-specializing-in-global-cyber-espionage/" (24573) added by User "SYSTEM" (0). -- type () => (link), category () => (External analysis), uuid () => (56bc4126-bd84-49e0-a97b-6af9950d210f), event_id () => (2174), old_id () => (0), org_id () => (16), event_org_id () => (18), value1 () => (https://securelist.com/blog/research/73673/poseidon-group-a-targeted-attack-boutique-specializing-in-global-cyber-espionage/)
resque-worker-error.log:/var/www/MISP/app/tmp/logs/[8094]: 2016-02-11 11:00:14 Notice: Event (2115) updated by User "SYSTEM" (0). -- publish_timestamp (1455026415) => (1455184814)

Hope this helps

**Comment by Rafiot** [comment]
@h122015 Do you still have the problem?

**Comment by h122015** [comment]
I haven't seen this error in a while, seems to be solved :)

**Comment by Rafiot** [comment]
Thanks for the feedback! :)
