### ISSUE TITLE
Support: Updating feeds and situation with the olds.

### ISSUE THREAD

**Issue by jajco997** [MISP/MISP#8420]
### Support Questions

Hi,

I have questions about lifecycle of events from turned on feeds and work of MISP. When I turn on some feeds, and update them in some time, they will only updated events for new attritbutes/created new events or all database will be delete and import once again with new data. 
Currently I have MISP connected to microsoft sentinel and threat intelligent system and I'm afraid about duplications IOCs in the future.

Second question what is happen with old events and attributes. I mean, if some attributes verified as FP by community will disappear? Are legacy events deleted or stayed for historical reason?

### MISP version

2.4

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Maybe you want to have a look at the decaying indicators functionality in MISP:

- [https://www.misp-project.org/2019/09/12/Decaying-Of-Indicators.html/](https://www.misp-project.org/2019/09/12/Decaying-Of-Indicators.html/)
