### ISSUE TITLE
CSV empty

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#843]
Hello all,

An empty file is returned when you want to download the attributes in CSV format (click "Download as..." -> "CSV").

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.6

**Comment by advancedeng** [comment]
I can confirm it. I see this one as well (MISP 2.4.6)

**Comment by iglocska** [comment]
I've just pushed a fix, should work correctly now.

**Comment by adulau** [comment]
Commit 17c09157a1dc645ba479ed16c49d36387b3f5268 solved the issues of the single event export. Thank you.

**Comment by adulau** [comment]
I'll close the issue as it seems solved. Tested on 3 prods servers.

**Comment by devnull-** [comment]
Thank you :)

Have a nice day

devnull-

**Comment by iglocska** [comment]
Thanks a lot for the bug report!
