### ISSUE TITLE
Bug: Import Stix2 file via web gui or command line

### ISSUE THREAD

**Issue by Rogueit** [MISP/MISP#8431]
### Expected behavior

Import Stix2 file via web gui or command line

### Actual behavior

[2022-06-03 11:24:53 59928] Running command /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPzeUUTE 1 event /var/www/MISP/app/files/scripts/tmp/synonymsToTagNames.json
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2111, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2103, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
[2022-06-03 11:24:55 59928] Process finished with return code 1

### Steps to reproduce

Running the following command on the below stix2 file.
`
 /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPZ7BkVg
`
`
{
    "type": "bundle",
    "id": "bundle--18f5791d-a810-4b8f-8955-aa5ffba72ca7",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "indicator",
            "id": "indicator--07a8e8b3-483f-4a91-a0b8-853ae73cd8f5",
            "created_by_ref": "identity--0887d73a-92fb-4a90-b2e9-ba72cb582831",
            "created": "2022-05-25T20:24:07.676Z",
            "modified": "2022-05-25T20:24:07.676Z",
            "name": "ipv4: 59.148.253.194",
            "pattern": "[ipv4-addr:value = '59.148.253.194']",
            "valid_from": "2022-05-25T20:24:03.499297Z",
            "labels": [
                "anomalous-activity",
                "Emotet"
            ],
            "object_marking_refs": [
                "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
            ]
        },
        {
            "type": "report",
            "id": "report--212aa03e-5067-4372-bc6f-8ae004c58129",
            "created": "2022-06-02T15:09:30.010Z",
            "modified": "2022-06-02T15:09:30.010Z",
            "name": "ipv4: 59.148.253.194",
            "published": "2022-05-25T20:24:07.676Z",
            "object_refs": [
                "indicator--07a8e8b3-483f-4a91-a0b8-853ae73cd8f5"
            ],
            "labels": [
                "indicator"
            ]
        }
    ]
}
`

### Version

v2.4.159 

### Operating System

ubuntu

### Operating System version

20.04.4 LTS

### PHP version

7.4

### Browser

chrome

### Browser version

101

### Relevant log output

```shell
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2111, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2103, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=False)
TypeError: parse() got an unexpected keyword argument 'interoperability'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakubOnderka** [comment]
Duplicates #8404
