### ISSUE TITLE
Bug: STIX 2 import fails for files with tag "misp:tool=\"misp2stix2\"" with attribute type attachment.

### ISSUE THREAD

**Issue by MitaliLamkhade** [MISP/MISP#8447]
### Expected behavior

STIX 2.0 file should get imported and attribute of type attachment with category as External analysis should be created.

### Actual behavior

Following message displayed

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

1. Click on Export
2. Generate STIX2 file and download
3. Click on 'Import from' option
4. Select STIX 2.0
5. Select file and import.

### Version

2.4.153

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Relevant log output

```shell
Running command /usr/bin/python3 /var/www/MISP/app/files/scripts/stix2/stix2misp.py /tmp/MISPwgECUO 1 event /var/www/MISP/app/files/scripts/tmp/synonymsToTagNames.json
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2111, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2105, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 83, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 357, in parse_event
    getattr(self, self._stix2misp_mapping[object_type])(stix_object)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 384, in _parse_observable
    self.parse_observable_attribute(observable)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 521, in parse_observable_attribute
    value = self.parse_single_attribute_observable(objects, attribute['type'])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 855, in parse_single_attribute_observable
    return getattr(self, stix2misp_mapping.attributes_mapping[attribute_type])(observable)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 639, in _parse_attachment
    return self._parse_name(observable, index='1'), self._parse_payload(observable)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 798, in _parse_payload
    return observable['0'].payload_bin
  File "/var/www/MISP/app/files/scripts/cti-python-stix2/stix2/base.py", line 270, in __getattr__
    raise AttributeError(
AttributeError: 'File' object has no attribute 'payload_bin'
[2022-06-15 10:29:06 35] Process finished with return code 1
```

### Extra attachments

**Sample File:**
{"type": "bundle", "spec_version": "2.0", "id": "bundle--7b998515-bf92-44a3-82f3-7c72f90a5216", "objects": [{"type": "identity", "id": "identity--34f6d002-d8f1-4fce-8b64-eb79a1905299", "created": "2022-06-15T06:01:56.000Z", "modified": "2022-06-15T06:01:56.000Z", "name": "ORGNAME", "identity_class": "organization"}, {"type": "report", "id": "report--b84f82e5-14b0-4982-94b7-1584c76e6fb6", "created_by_ref": "identity--34f6d002-d8f1-4fce-8b64-eb79a1905299", "created": "2022-06-15T06:01:56.000Z", "modified": "2022-06-15T06:01:56.000Z", "name": "Event Created from Scanned Document", "published": "2022-06-15T06:02:10Z", "object_refs": ["observed-data--64fa3022-85b0-45e2-ae73-66def0ee8041"], "labels": ["Threat-Report", "misp:tool=\"MISP-STIX-Converter\"", "misp:tool=\"misp2stix2\""]}, {"type": "observed-data", "id": "observed-data--64fa3022-85b0-45e2-ae73-66def0ee8041", "created_by_ref": "identity--34f6d002-d8f1-4fce-8b64-eb79a1905299", "created": "2022-06-15T06:01:42.000Z", "modified": "2022-06-15T06:01:42.000Z", "first_observed": "2022-06-15T06:01:42Z", "last_observed": "2022-06-15T06:01:42Z", "number_observed": 1, "objects": {"0": {"type": "file", "name": "ScannedDoc.pdf", "content_ref": "1"}, "1": {"type": "artifact", "payload_bin": "JVBERi0xLjUKJcOkw7zDtsOfCjIgMCBvYmoKPDwvTGVuZ3RoIDMgMCBSL0ZpbHRlci9GbGF0ZURlY29kZT4+CnN0cmVhbQp4nC3KuwrCQBBG4X6e4q+FjDOTbHYWli0ELdIFBlKInZcukDS+voJy4KuOsOJNGwTCYo5UEltO8EHZR8X+oOWA9Xd82190CkojO3LuuXhB3HG8KNQQz2sVbZ1VsaZV+mZ/hnaLic5BM834AJA4GLgKZW5kc3RyZWFtCmVuZG9iagoKMyAwIG9iagoxMTEKZW5kb2JqCgo1IDAgb2JqCjw8L0xlbmd0aCA2IDAgUi9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoMSA4MTc2Pj4Kc3RyZWFtCnic5Th7UBtnfr9vVwKBsCUIcMIy6FPWEFMe4mEcvzAyIAEGG5lHItmJ0SItSAlIOkngc9JrSJuHT44bn5smdeJpfJ27m8yVGS8hvZJMLuZ6yT0m7SXX3nTy8oWZy810pnbtPK+TnKG/79sFg+Mkc53+14Xv29/7/S27pJMTCuTBFIjgDo3LiUKjQQCAfwYgBaHJNG3uLdqJ8AKA8K8jidHxJ//xjo8ADM8BZD83OnZ05FumH74FkBcBEH8eUeTwuw1iNYC1Dm1sjSChe/FoNuLIh02R8fQ3BPLTQsQfQbxwLB6Sf0PeI4ifRTxvXP5GosiwA/1bpxGnMXlc+e/HfhJGHOMxpxLxVDoMx5YANroZP5FUEj1PDr+CeBD9n0QawR925SGYxXBBNMD/58t4Aoqg09gMFkjwfc0lTkMJnAZYusiwa/tiz9Kn/5dRmLTb38D34Tk4AW/CnTrDCz6IwgRSVl8/hl8hlV0+OAg/gMwXmJ2GOeRrckF4lGVyw8sHT8As/GyNFx+Mw70Yyz/Am6QefoGjEocPiAnuh1fQ6gdI23cjU8J63EY4OLKK+jY8JRyHvcJ7iJxmHMElWOFlOEMOo+U05nliJeNdnzP6MHwT936IwCTC/DI2/+EtyFn6ELP6JuyFP4c9MLZK40XytJiL/RuAp7GmP+Y01zIzu1O8S/ihIFz9K0S+DaO4ZIK5CyfEPV9QoT/6EgdhHakUyyHnRlxhC1gWPxUalj4SN0EuDC5dWaYtdS99KMqLMcOQYaOx2fDql/nI+rZhHLVh6XeL9y6GjfuN38duPQPg7jh0MOAfHOjvO+Dr3b+vp3tvV2eH19Pe1rrH3bK7edfOHdu33bq1qb7OVVtTvfmWivJN0s1Oh60w32pZv86cm2PKzjIaRIFANVVJ0KOK5TTfK0seSe6sqaYeW6S9ptojeYMqlamKN0OF1NnJSZKs0iBVK/AmryIHVTdKjlwn6dYk3SuSxEp3wS7mQqLqv7RLdI4cPOBH+ES7FKDqJQ7v47ChgiPrEHE6UYNHxaKlHtU7Gcl4ghgjmTHntkltSm5NNczkmhE0I6RulhIzZPNuwgFhs2fHjACmdcwtZuqRw6rvgN/Tbnc6AzXVXep6qZ2zoI2bVLPa1GxukkZZ6HCczlTPZx6Zs8JwsCovLIXlO/yqKKNuRvRkMg+r+VVqpdSuVt7zng0zV9Rqqd2jVjGr3X0rfrqvuSSqsdwq0czHgOlIly6upcg6Javc+jEwUBXaVNLnd7LL7sVaZzJeiXozwYw8tzQ1LFGrlJnJy8skPFhu8PnRxNzSC8ftqveRgGoNRsiOgJ66t69bvenAIb8qlHtpREYK/rZIzm12Z/6KjO+L2IBlweJghZ1OVobjc24YRkSdOuDXcArD9mfB7aoKqEKQceaXOUWDjDO1zFlRD0rY2+5+f0Y1lHeFJQ9W/LisTg3jdN3FGiNZ1fWf2J1SpiCfbncFuCzFqLrCUaoaK7BIqLVaAeeGqWSsHFn/iXa7ZEcHFfkFdLuEZpgdj+QJ6r+TERsaoFjoziptEAb8qrsdAbesd8wzU+dCDTmIDYu282aqLimhFkqtK91lYXmi/X6uoquphW0qBEO6lury8HNFPZlguxYCsyUd8D8PjUsLM1uofbYRtkCgnQkXt+GUVXgy/vCI6gjaw3juRqjf7lTdAexwQPIrATZ2WKHKBTsfjgCflQF/d7/UfeCgf5seiMZg5gzlnuvMSH67ZgYHUDWVm6hfsIsBFLQigXoRkFp34a5ml5twWbHgnMoGt3UX9RM7LEtjGGol9SjtuhzD1xg1snFq61y2lsVQtNPWaXcGnNpVUy0gm+qOUcPEitq5zMLHFDJMOJ9tnZzEamljQ0/9kiIFpAhV3T4/y42Vh1dZLwavud6rgTXYqmJhmcCJ7GWEFVP1VtlXF1ft4PgK2nkdu2uZTTMmqbs/w4xLukHAyLtUYCPs3pZv588CdqAlfPZSKx5pfqAzM243O8yRHcyI1BXOSP3+XVwanyfftN/DfBVAN+keaK2pxkdb64xEjh2YcZNj/Qf9z1vxvfDYgP9ZgQhtwdbAzCbk+Z+n+EeDUwVGZUSGUIYwS32ImLi8/Xk3wBTnGjiB46E5ApxmWqYRCM0JGs2qOargjtwgIMegcdzL0gakmTTaFKfxawZYydy5RrfJnePOE9YJ9hnCSM8i5QV8j80hMJtH1hH7DGr1cfIcmZrJcds1iSmUcGsRHhu85nrwoH82D/862/mOjlrZheNii2Cz8c+Kh4bZoPxpIJIJBthhg2JsDf4SlUi7sU3SbgwkK0/NlZRW1Sy1MnoLo7do9CxGz8YRJcUE1aew9z6VsAk45HfikaQbfmHPWC+xTgXwoZKx/q4GK4bfEcbj+A5qh3PuWG5xcX5OSYmQL5RuzLEFA5aclpzeHNEs5uSA0Wo2iUZxKLDOKJYU5wsgDAUKoWBLKdlUSgpLiaGU7Hi5lIRLSfsy/lEpeY+jmtBCKRFeLyVnS0milPhKyZ14Dd35dXYl2XWYEaCloSofGhsbbS2NGpBfsN3mGjp8Z1V+Adm+Pb9R+6mva2y6Nf+WJmdRdr5Tv3+tyIk0J953Tk8LJdPCkWnBNj199T+mr35ruslu+NsNTU0brr4vWNj9s2F7U5NdaLr6qr0Jm+Rbuih6xVfwvXwjnHAfLCHEssFUZCkqLSsBX8BS4igR8sSSkryCgmJfoMCaZzwQyCueLyNqGTlbRk6WkakykigjwTLiKyNQRnbjzV1G6soILSPWMnKFy6HQmmzv1FKuAlsLpgdrE9XzJEWFZaSxYeutReuJdHNF/patjTS/iNycVeTcUkEMzfeNbn2sru57t7396i/Pk+jiE5E4OXUHebMgc9pXYN7mqL1IjJ98sDjSR848893Z0+xrrBLf+6z4DZIDf+dOGPHdK8sXwDdGo2j0BcSiX5vJy2bynJl810weM5MHzCRtJmEz2WQmhWZiMJPtH3GJk2YiJMwkaCY+M3GbybyZqGZylqNWMwEzucJRlFstpif99ZW+D60pBi8H9p0XhGyvryvXuoodJvHvLJacPUu83pKamhKjYKvBvu3Hvj2LfcuFYnjBfX++0QxG+JrNtN4XMFmFQl9AKKY2AjayYCM+G6mzEauNXOHo6zYybyOqjZy1kZM2MmUjCRsJ2ojbRjSVnU9zko+T6jjVyhmr9c9yTU0Ndz0xvcnXpaalnUyudFwfaGyy1XlzRRO2tqE4e0uFhM0tLMaei88udv76jTfe+fe3nvuzh/5i4sj9D0yRtxfzF9//rz/8/sM3/umFhd/+6GX2Us6+r4WS03v/XjkzZNn1MTi0b7uft7/+y2tv7ksX8aSzLx4TCDoJ9bKdix64fUWIXPe6b8zajtvPYKd4AnzCdqjEL/f9nPMAfEqC5D2uYYRS3aYAVvzmuQOBn4g/BZFzy0hsxe5tKz4ISt6mwwJk4/eZBov4LBrXYQPKHNNhI6zDb1UNzsJv5u/pcDbcg9+vGmyCQlKrwzmwnrTqcC6JEZ8Om2Gj8NLKfyRqhbd0eB00iSYdXg8bxGYWvYF9SU2Lt+swAWoQdViA9QZJh0XYaqjXYQPKjOqwETYYHtbhLCgzfEeHs+Ejw3kdNsFm46wO58BG49s6nCu8Y/y9Dpthm+nfdDgP7sgx6/A6uCtn2dd62JLzq/boaDQdvUcJ07CclmkonjiajI5G0nRzqJI21NXX0Y54fHRMoW3xZCKelNPReKw2t+16sQbahyY65XQ17YqFanuiw4omS/uVZHSkTxmdGJOTe1IhJRZWkrSGXi9xPX6bkkwxpKG2vrbuGvN62WgKv+7SSTmsjMvJu2l8ZG0cNKmMRlNpJYnEaIwO1vbXUp+cVmJpKsfCdGBFsXdkJBpSODGkJNMyCsfTEYz0rolkNBWOhpi3VO1KAquq0Z9WJhW6T06nlVQ81iqn0BdGNhCNxVPV9EgkGorQI3KKhpVUdDSGzOGjdK0ORa6MucRi8Uk0OalUY9wjSSUVicZGaYqlrGvTdEROs6THlXQyGpLHxo5iy8YTqDWMPToSTUfQ8biSovuVI7QvPi7HflCrhYK1GcGa0uh4Ihmf5DHWpEJJRYmhMzksD0fHomm0FpGTcggrhmWLhlK8IlgImpBjNZ6JZDyhYKS3d/RcE8QAtWqm4mOT6JlJxxQlzDxi2JPKGCqh47F4/G6Wz0g8iYGG05GaVZGPxGNpVI1TORzGxLFa8dDEOOsTljm9HJwcSsaRlxiT02hlPFUbSacTO1yuI0eO1Mp6a0LYmVq07PoyXvpoQtH7kWRWxsd6sP0x1roJ3l+WRH9XD+1NYH28GBzVBarp8mTW19brLrCM0UQ6VZuKjtXGk6OuXm8PtEMURnGlcd0DCoSB4pIRlxEKQRwScBSSXCqCVAqbkVqJ9waog3pcFDpQKo78MdSn0IZwErXYLnO7cYhBLf4ha/tKaw0I9elRdHLtaoS6UD+EFnpQbxi5q+1S6OeUKD5mmeYoTGAcMlL2QAq1FJQJcwkKNbi+ysZX8W/jUGqF04Bx1eOqu6HmV9mNoiXKK53mHBbpOI/+bqTFUe/L6kFRTuHdSyFH4ViYW2W2B1Gin0v5uCarRJp7i3GpgRt47EWPI6gf4p1clgxx22wiNMtxhCN6Te/Ceid5BGGut5xbCj1/vgM3no1+Ht0k97mP0xme4rxWxFN6XlrNBngUcaSyWhzBSJjfCIdlXs8w12YzFtM1h3Hq6Jf6obqurPclxn1M6lEynWq93iN8T3G/MfRBeXxal9f6prxOMq+61ulx5Ka5bAjpY/hzVD9l41gVzdewfo6O8FMZ0TMe53YpvqIoyGFTEed9izlv5j2+VhVtbkb0OaVcN4FwnGexXMca3huWicIjZZDMT/4waoxx31psET4dMu+tovc6zTNYrldYz5RFneCUGvDwuWDnXdFrejs+J3puaFGr4OrZZD0Z4/GmVtmO8WjDKzlq1WZSY7onLeMx/jy6e6U/I3zetIqGubWaL6j5CK9NWvca5xGF8UfruDZbcdSd4P3QzpM2zenPVU7m9Y3regn+VErrsYzz8xHhE5iAHfhi6cLo2E8tn8PVpyakn5laPWbX/1qPxZXgFVx9PpIrsYxjjD366Y+tnLqJVed3uRP9+Azq4c+LhD4/Xr1y9DoL7NRc/8ys58/MtVlo0xhFPM3jSfFa1vIcRpHfix562Du09sb/IIZ0g2smx7dnmChASISMwk3gIEHYT4ZgkOyBZuLGuxt5rXhvQ5zda0kzTKFcM9J3I74L6Tvx2enAvQVXL65HcRlwaRJ1KOHCu0vHaxCvRo3XcCd8MWoLUtl9L+KdeO/Q716ke/Du0fEuxPEOQZKNL+EtfD9PDO5ZsnCVvHaV0Kvkvs+I7zMy9cHJD4T3r1Q6zl05f0XovTx0+dxlse4ysVwmJrhkveS7FLyUuHT2Ulau5SLJg/8k+b9d2OZ4t/nC4G+a3xmEC5jZhboLvgtTF9QLxgtEHHxHLHZY5+l83Xxifmr+9fmF+SvzpqmXTr4k/OhFl8PyouNFwTHbO3vfrBh8hliecTwj+J4KPiWcPEMsZxxnXGfEJ0/XOk53lDmeePwWx8LjVx4X5pbmZx9fl+99kfSSHmjGGu6fFZcc5/YUkX2YlgV3By4Xrl5ccVyP4sJvHhR34HKRHvc2ceivifmU/VTVqXtPHT9lTDw09dDJh8SpB08+KJybPD8ppHyVjnisyhHr+BNHSaNtMLtRHMxCN+jd3TVcvtkbHHI7hlDo0ME6x8GOSsdNjQWDRkzYgIIW0SG2iL1iXHxUPC9mm/p8ZY4DuBZ8V3yC25eT57X0OnpdveLc0oJb6Xaitb2JvVN7xS5vpaOzY5vD0uHocHW81vFux+WOrKEO8jT+es95z3tFt7fS5XV7y5zejZ32weLGosF8Yhm0NloGBYKNboRBl2XJIlgsQ5b7LKIFWkCYKiZGMkdOzgz0V1V1z2Uv9XWrJt8hlRxTy/vZ7j5wUM06psLgwUP+GUL+MvDgiRPQWtqtNvT71WBpoFsNI+BmwBQC1tKZYmgNpFLpKn6RqiqEJ3CHqokqJB5OaVRY4UNViqTwEZXiSqSKCWg4wb2K8ZDA9AhqH04B2xizSlNi2indHFfWNg7YDv8P9XomnwplbmRzdHJlYW0KZW5kb2JqCgo2IDAgb2JqCjQ2MTQKZW5kb2JqCgo3IDAgb2JqCjw8L1R5cGUvRm9udERlc2NyaXB0b3IvRm9udE5hbWUvQkFBQUFBK0xpYmVyYXRpb25TZXJpZgovRmxhZ3MgNAovRm9udEJCb3hbLTU0MyAtMzAzIDEyNzcgOTgxXS9JdGFsaWNBbmdsZSAwCi9Bc2NlbnQgODkxCi9EZXNjZW50IC0yMTYKL0NhcEhlaWdodCA5ODEKL1N0ZW1WIDgwCi9Gb250RmlsZTIgNSAwIFIKPj4KZW5kb2JqCgo4IDAgb2JqCjw8L0xlbmd0aCAyMzkvRmlsdGVyL0ZsYXRlRGVjb2RlPj4Kc3RyZWFtCnicXVC7asQwEOz1FVveFYdkxwkpjODwceAiD+LkA2Rp7QhiSchy4b+PHpcEUkjMMDvD7NKuv/RGB/rqrRwwwKSN8rjazUuEEWdtSFWD0jLcWP7lIhyh0Tvsa8ClN5NtW0LforYGv8PhrOyIR0JfvEKvzQyHj26IfNic+8IFTQBGOAeFU8x5Eu5ZLEiz69SrKOuwn6Llb+B9dwh15lWpIq3C1QmJXpgZScsYh/Z65QSN+qc1xTFO8lP4OFnFScaaRx5xnfHDfcJ3BXcJNwWXvJszJafVfxqD3LyPbfN9cs1UUBv8PaGzLrny+wbC9XSFCmVuZHN0cmVhbQplbmRvYmoKCjkgMCBvYmoKPDwvVHlwZS9Gb250L1N1YnR5cGUvVHJ1ZVR5cGUvQmFzZUZvbnQvQkFBQUFBK0xpYmVyYXRpb25TZXJpZgovRmlyc3RDaGFyIDAKL0xhc3RDaGFyIDQKL1dpZHRoc1s3NzcgNzIyIDQ0MyAyNzcgNTAwIF0KL0ZvbnREZXNjcmlwdG9yIDcgMCBSCi9Ub1VuaWNvZGUgOCAwIFIKPj4KZW5kb2JqCgoxMCAwIG9iago8PC9GMSA5IDAgUgo+PgplbmRvYmoKCjExIDAgb2JqCjw8L0ZvbnQgMTAgMCBSCi9Qcm9jU2V0Wy9QREYvVGV4dF0KPj4KZW5kb2JqCgoxIDAgb2JqCjw8L1R5cGUvUGFnZS9QYXJlbnQgNCAwIFIvUmVzb3VyY2VzIDExIDAgUi9NZWRpYUJveFswIDAgNTk1LjMwMzkzNzAwNzg3NCA4NDEuODg5NzYzNzc5NTI4XS9Hcm91cDw8L1MvVHJhbnNwYXJlbmN5L0NTL0RldmljZVJHQi9JIHRydWU+Pi9Db250ZW50cyAyIDAgUj4+CmVuZG9iagoKNCAwIG9iago8PC9UeXBlL1BhZ2VzCi9SZXNvdXJjZXMgMTEgMCBSCi9NZWRpYUJveFsgMCAwIDU5NSA4NDEgXQovS2lkc1sgMSAwIFIgXQovQ291bnQgMT4+CmVuZG9iagoKMTIgMCBvYmoKPDwvVHlwZS9DYXRhbG9nL1BhZ2VzIDQgMCBSCi9PcGVuQWN0aW9uWzEgMCBSIC9YWVogbnVsbCBudWxsIDBdCi9MYW5nKGVuLUlOKQo+PgplbmRvYmoKCjEzIDAgb2JqCjw8L0NyZWF0b3I8RkVGRjAwNTcwMDcyMDA2OTAwNzQwMDY1MDA3Mj4KL1Byb2R1Y2VyPEZFRkYwMDRDMDA2OTAwNjIwMDcyMDA2NTAwNEYwMDY2MDA2NjAwNjkwMDYzMDA2NTAwMjAwMDM2MDAyRTAwMzQ+Ci9DcmVhdGlvbkRhdGUoRDoyMDIyMDYxNTExMzEyMyswNSczMCcpPj4KZW5kb2JqCgp4cmVmCjAgMTQKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDA1NzA1IDAwMDAwIG4gCjAwMDAwMDAwMTkgMDAwMDAgbiAKMDAwMDAwMDIwMSAwMDAwMCBuIAowMDAwMDA1ODc0IDAwMDAwIG4gCjAwMDAwMDAyMjEgMDAwMDAgbiAKMDAwMDAwNDkxOSAwMDAwMCBuIAowMDAwMDA0OTQwIDAwMDAwIG4gCjAwMDAwMDUxMzUgMDAwMDAgbiAKMDAwMDAwNTQ0MyAwMDAwMCBuIAowMDAwMDA1NjE4IDAwMDAwIG4gCjAwMDAwMDU2NTAgMDAwMDAgbiAKMDAwMDAwNTk3MyAwMDAwMCBuIAowMDAwMDA2MDcwIDAwMDAwIG4gCnRyYWlsZXIKPDwvU2l6ZSAxNC9Sb290IDEyIDAgUgovSW5mbyAxMyAwIFIKL0lEIFsgPDU4MjA0NTMyMUQ2NjJCRjlEMjhFQTc2RDRDRTEwM0IwPgo8NTgyMDQ1MzIxRDY2MkJGOUQyOEVBNzZENENFMTAzQjA+IF0KL0RvY0NoZWNrc3VtIC81MDJFRTA3QjZDMEQ3NzFEREUxNTMwQzk3NzkwNkQ5Rgo+PgpzdGFydHhyZWYKNjI0NQolJUVPRgo="}}, "labels": ["misp:type=\"attachment\"", "misp:category=\"External analysis\""]}]}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
It should be working as expected now with the changes mentioned above, but let me know if anything goes wrong
