### ISSUE TITLE
Bug: MD5 indicator is not being imported into MISP by stix2misp.py

### ISSUE THREAD

**Issue by Rogueit** [MISP/MISP#8459]
### Expected behavior

File properly imported.

### Actual behavior

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2111, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2105, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 86, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1232, in parse_event
    self.handle_markings()
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 146, in handle_markings
    attribute.add_tag(self.marking_definition[marking_uuid]['object'])
KeyError: 'f88d31f6-486f-44da-b317-01333bde0b82'

### Steps to reproduce

Run Command:
/var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPEAc0Y1

Contents of MISPEAc0Y1 can be found below.
{
    "type": "bundle",
    "id": "bundle--b1046b43-8dcd-4e38-a4a4-7bb4797e2d46",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "indicator",
            "id": "indicator--384f53ff-5af4-4764-9d47-974eb06405ab",
            "created_by_ref": "identity--9b6ad3d0-a43b-48d4-8c59-8e320dba6251",
            "created": "2022-06-13T20:41:14.624Z",
            "modified": "2022-06-13T20:41:14.624Z",
            "name": "file_hash: 161b10e95c2f6723ce267e2fb7961b4b",
            "pattern": "[file:hashes.MD5 = '161b10e95c2f6723ce267e2fb7961b4b']",
            "valid_from": "2022-06-13T20:40:42.48143Z",
            "labels": [
                "anomalous-activity",
                "Emotet"
            ],
            "object_marking_refs": [
                "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
            ]
        },
        {
            "type": "report",
            "id": "report--194fa9a3-7e12-44f6-88df-a7cbc734091d",
            "created": "2022-06-22T18:07:33.342Z",
            "modified": "2022-06-22T18:07:33.342Z",
            "name": "file_hash: 161b10e95c2f6723ce267e2fb7961b4b",
            "published": "2022-06-13T20:41:14.624Z",
            "object_refs": [
                "indicator--384f53ff-5af4-4764-9d47-974eb06405ab"
            ],
            "labels": [
                "indicator"
            ]
        }
    ]
}

### Version

v2.4.159

### Operating System

ubuntu

### Operating System version

20.04.4 LTS

### PHP version

7.4

### Browser

N/A

### Browser version

N/A

### Relevant log output

```shell
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2111, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2105, in main
    stix_parser.handler(event, filename, args[2:])
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 86, in handler
    self.parse_event(event)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1232, in parse_event
    self.handle_markings()
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 146, in handle_markings
    attribute.add_tag(self.marking_definition[marking_uuid]['object'])
KeyError: 'f88d31f6-486f-44da-b317-01333bde0b82'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Hey,
The script was not handling the possibility that there could be objects referencing other objects where the referenced objects are not present in the bundle.
-> In your sample, there is a `marking_ref` and the referenced `marking-definition` object does not exist in the bundle.

I am currently working on the rework of the [STIX -> MISP import feature](https://github.com/MISP/misp-stix/tree/main/misp_stix_converter/stix2misp) (and will keep notes of this "missing referenced objects" case to avoid issues in the future), so I quickly checked in stix2misp.py if there could be any other similar issue, it should be ok for now with d2ddef68ab9abf01ae0e24e0d3d6bb196a80cfea
But if I missed anything and/or you face any further issue let me know.

**Comment by sholland-bamboohealth** [comment]
I have a ton of failures from different stix files from the h-isac feed. I was just going to work my way through them one bug at a time. If you need specific stix files types...I will be happy to provide. Thanks for working on this.

**Comment by chrisr3d** [comment]
@sholland-bamboohealth I'm always happy to get samples in order to see how the different STIX objects are built by different producers. It really helps me adapting the code to cover the different cases for a better support
Thanks

**Comment by sholland-bamboohealth** [comment]
getting this when trying to import the file with the following command

`/var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPAKjotS
`

/var/www/MISP/app/tmp# /var/www/MISP/venv/bin/python /var/www/MISP/app/files/scripts/stix2/stix2misp.py /var/www/MISP/app/tmp/MISPAKjotS
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2146, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 2138, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'

**Comment by chrisr3d** [comment]
This one is a pretty easy one to fix, it simply comes from a different version of the STIX 2 python library
We use a slightly changed version that I maintain to avoid validation issues with UUIDs while loading STIX bundles.
The straight forward way of fixing this is described in the [dedicated part of our user guide](https://github.com/MISP/misp-book/tree/main/updating-python#updating-misp-and-its-dependencies).
The important points in your case are to make sure you have the latest submodule versions and then to update the python library:
~~~shell
# Update MISP and its submodules
cd /var/www/MISP
sudo -H -u www-data git pull origin 2.4
sudo -H -u www-data git submodule update --init --recursive

# Update the STIX 2 python library
cd /var/www/MISP/app/files/scripts/cti-python-stix2
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -U .
~~~

**Comment by sholland-bamboohealth** [comment]
That fixed any problems I was having with any of the stix files I was getting from h-isac. Thanks for your work.
