### ISSUE TITLE
Materials required for MISP

### ISSUE THREAD

**Issue by Linow974** [MISP/MISP#8461]
Hello,

I looked at the FAQ and the documentation on this subject, because I want to buy a server on OVH to host MISP there. So I want to know what technical specifications I need.
I've seen 8gb, 16gb, in RAM and 250gb on disk, but I don't know how to adapt it to my case.

In fact, at the level of events, I would receive every day about twenty events + those that I would publish myself. This may increase in the future.

However, I don't know how the old IOCs/events deletion rule works, does it exist on MISP? Is there a way to delete events from a certain date?

In this case, I think 250gb could be more than enough with a certain deletion policy.

**Comment by adulau** [comment]
We recently published a quick sizing guide https://www.misp-project.org/sizing-your-misp-instance/ which might help you. Feel free to re-open the issue if it doesn't answer your question.
