### ISSUE TITLE
Support: correlations too large, yet again

### ISSUE THREAD

**Issue by deMasus** [MISP/MISP#8463]
### Support Questions

Hi,
my correlations table is something like 25G and truncate correlations isn't helping, it says 0 rows affected.
any advice on how to reclaim some space? What i 've done is disabling correlations at all and deleting some old events.
![image](https://user-images.githubusercontent.com/100416469/176162388-70146611-fd67-4c0e-a49c-3ed943cf9563.png)
mysql> select count(*) from correlations;
+----------+
| count(*) |
+----------+
|  7333578 |
+----------+
1 row in set (0.92 sec)
mysql> truncate correlations;
Query OK, 0 rows affected (0.30 sec)

### MISP version

2.4.159

### Operating System

dockered misp on centos

### Operating System version

20.04

### PHP version

7.4

### Browser

no matter

### Relevant log output

```shell
mysql> select count(*) from correlations;
+----------+
| count(*) |
+----------+
|  7333578 |
+----------+
1 row in set (0.92 sec)
mysql> truncate correlations;
Query OK, 0 rows affected (0.30 sec)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Another important, after your deleted the potential highly correlating event, is to update the MISP object template too. We saw some feeds still using old templates where correlation was not disabled. 

There is also a new tool to ease the deletion of unwanted events. [eCrimeLabs MISP Purge Events tool](https://github.com/eCrimeLabs/MISP-PurgeEvents)

I'll close the issue but don't hesitate to reopen it if you have a specific finding on the highly correlating events.

**Comment by deMasus** [comment]
thanks a lot, Alexandre, will give it a try!
