### ISSUE TITLE
Support: Action EventsController::attributes() could not be found

### ISSUE THREAD

**Issue by shinobu55** [MISP/MISP#8476]
### Support Questions

Hello,

I tried to add an attribute over the API (Post: /events/attributes/174), but got a 404 Not Found back. After looking into the error Log it showed me the following error:

2022-07-05 18:45:04 Error: [MissingActionException] Action EventsController::attributes() could not be found.
Exception Attributes: array (
  'controller' => 'EventsController',
  'action' => 'attributes',
)
Request URL: /events/attributes/174
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#2 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#3 {main}

I hope you can help me out.

Best Regards.

### MISP version

2.4.159

### Operating System

CentOs

### Operating System version

7

### PHP version

7.4.26

### Browser

Chrome/Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @shinobu55 
For adding attributes to an event the endpoint is: `/attributes/add/:event_id` 
You can find the API documentation here:
* https://www.misp-project.org/openapi/#operation/addAttribute

Hope this helps.
