### ISSUE TITLE
Add indication of logged in user identity

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#848]
It would be useful if there was a top toolbar indication of the logged in user identity or dropdown for the profile + logout link so that it's clear when logged in, which user you are logged in as. Helps for not doing too much (e.g. data entry) when logged in as a user limited to setup/administration.

**Comment by dspruell** [comment]
Missed it before, realized this was related to/dupe of #474.

**Comment by adulau** [comment]
Thank you. It will be soon implemented as @iglocska works on a rework of the notification part including proposal info, new event and logged information. This should come in the next days.

**Comment by Rafiot** [comment]
Fixed.
