### ISSUE TITLE
Export as bloomfilter (external tool)

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#85]
Convert the attributes to a bloomfilter so it can be shared with other people without violating the classification/TLP.

Publish this external tool as new repository inside the github MISP org.

**Comment by elhoim** [comment]
More details on the feature from #86: allow selected types of attributes to be exported.

**Comment by iglocska** [comment]
This is something for the bloomfilter project, if there are any requests for it best to open an issue over there ;)
