### ISSUE TITLE
External modules for MISP using the future scheme 

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#850]
This is the list of the external modules we need to implement in order to ease the use of MISP:
- [x] Live DNS lookup
- [x] Viper integration for PSSL
- [x] Viper integration for PDNS
- [x] Viper integration for Virustotal
- [x] CVE search lookup
- [x] Cache of external links

**Comment by aaronkaplan** [comment]
> On 13 Jan 2016, at 16:13, Raphaël Vinot <notifications@github.com> wrote:
> 
> This is the list of the external modules we need to implement in order to ease the use of MISP:
> 
> 	•  Live DNS lookup
> 	•  Viper integration for PSSL
> 	•  Viper integration for PDNS

could we use this format for it?

https://datatracker.ietf.org/doc/draft-dulaunoy-kaplan-passive-dns-cof/

**Comment by adulau** [comment]
@aaronkaplan This is foreseen ;-)

**Comment by aaronkaplan** [comment]
I wonder why. :) cool!

---
Mobile

**Comment by adulau** [comment]
All modules were implemented in [misp-modules](https://github.com/MISP/misp-modules) and the Viper implementation is also implementing the above listed modules and even more functionalities nowadays. We can close this issue.
