### ISSUE TITLE
Bug: The 'Target Event ID' field is not changed when edit MISP feed

### ISSUE THREAD

**Issue by woodonggyu** [MISP/MISP#8503]
### Expected behavior

When I fetch specific feeds, I want to set "Target Event ID" field.

### Actual behavior

When I edit MISP specific feed, I couldn't change "Target Event ID".

### Steps to reproduce

1. Set to enable specific default feeds.
2. after or before fetch, try to change "target event id".

### Version

2.4.159

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Thanks for reporting, fixed via af0aef7db7cbccf75945403bc0737b1cdfc6dede
