### ISSUE TITLE
Bug: Error: Undefined index: is_galaxy

### ISSUE THREAD

**Issue by LumberJohn6** [MISP/MISP#8507]
### Expected behavior

The event should be pulled from instance without error

### Actual behavior

2022-07-25 11:48:34 Notice: Undefined index: is_galaxy in [/var/www/MISP/app/Model/Event.php, line 2232]
Notice Error: Undefined index: is_galaxy in [/var/www/MISP/app/Model/Event.php, line 2232]

### Steps to reproduce

Just go to the servers page on sync actions tab and click on pull on the server list

### Version

MISP 2.4.159

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
thanks for reporting, fixed via baad056b241ed794beb5215df67b5d7244312049
