### ISSUE TITLE
Editing attributes fails and causes high browser load

### ISSUE THREAD

**Issue by dspruell** [MISP/MISP#851]
MISP 2.4.0
PHP 5.5.9
Apache 2.4.7
MySQL 5.5.46
Ubuntu 14.04 64-bit

When selecting one or more attributes on an event and clicking *Edit selected Attributes* to modify a field in the attribute, editing the field and saving the modification fails seems to put the browser into a loop. The spinning "Loading" indicator is displayed indefinitely, and the edits are not made to the selected attribute(s). On my client, it did cause the browser to take 20+ % CPU so I believe there may be a client-side issue. No log of interest seems to be generated when this occurs.

**Comment by adulau** [comment]
Thanks for the report. Which browser do you use? Chromium or Firefox?

**Comment by iglocska** [comment]
If you open the console (f12 -> console) of your browser and try again, could you check what the error code and the contents of the body are of the response? Could you paste it in here?

**Comment by advancedeng** [comment]
I was about to report the same error.  I am using Firefox and I get the following error

GET https://MISP/attributes/fetchEditForm/305174/category?_=1452855734106
404 Not Found

Cheers,
Andreas

**Comment by dspruell** [comment]
@adulau Firefox 43.0.1 on OS X.

@iglocska From the console, it looks like when I toggle the checkbox to select the attribute, it outputs:

`Empty string passed to getElementById(). jquery-2.1.0.min.js:2:23965`

**Comment by Rafiot** [comment]
@advancedeng @dspruell Do you still have the problem?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
