### ISSUE TITLE
Bug: AadAuth with Group Auth enabled fails if MISP group not in first 100 groups

### ISSUE THREAD

**Issue by ntnco** [MISP/MISP#8516]
### Expected behavior

User gets authenticated

### Actual behavior

User does not get authenticated

### Steps to reproduce

- Create at least 100 Azure AD groups. 
- Add another group for `misp_siteadmin` and assign it to your user.
- Enable AadAuth by following the [documentation](https://github.com/MISP/MISP/tree/2.4/app/Plugin/AadAuth).
- Try to login with `AzureAD` button and observe that it fails.

### Version

2.4.159

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ntnco** [comment]
Thanks to @righel 's [logging improvements](https://github.com/MISP/MISP/commit/8b7b53975d45899ede6560633acbfcd287d46a26), I was able to pinpoint that the 100+ groups were causing the bug, because MS Graph's results are paginated.

I was able to fix the bug by implementing a simple while loop. I will submit a PR

**Comment by righel** [comment]
thanks for the fix, https://github.com/MISP/MISP/pull/8552 was merged.
