### ISSUE TITLE
feature request: when a pgp key exists for a user, send a password reminder encrypted

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#852]
Subject says it all.

If a user already has a pgp key stored, it might make sense to use this and send the user an encrypted email with a new password.

**Comment by iglocska** [comment]
We already have that. It's on the event index (looks like a recycle icon) or if you view a user's profile, on the left side, send credentials. 

Both will automatically reset the password of the user and send them new temporary credentials that they will be forced to change on the first login.

**Comment by adulau** [comment]
The encrypted notification is part of MISP including send new credentials, custom message or alike.
