### ISSUE TITLE
Feature Request: DB schema update

### ISSUE THREAD

**Issue by patricksaladino** [MISP/MISP#8525]
### Is your feature request related to a problem? Please describe.

Dear team. I've recently updated MISP to v.2.4.160 (commit 4c8e184a858203198aa7ae0be6677dd8ec076d1a). The update came with a database schema update (version 86 to 90). The diagnostic tool now reveals 400+ warnings in the actual DB schema, which should obviously be fixed.

### Describe the solution you'd like

An easier way to correct the DB schema, through a feature in the web UI or via the command line.

### Describe alternatives you've considered

Having access to all the recommendations at once (in a textbox) or exporting the recommended fixes to a plain text file would also do the trick. At present, the recommendations are only displayed one by one when you click on the wrench icon (which triggers a JS event)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Don't worry too much about the output of the schema delta, something has indeed gone wrong on our side and the difference comes from it being generated on a different dialect of the db. Feel free to ignore the deltas for now!

**Comment by patricksaladino** [comment]
Thank you for your feedback. I'm closing the issue.

**Comment by iglocska** [comment]
Thanks and sorry about the extremely confusing feedback in the diagnostics, we were just as puzzled when we first saw it!
