### ISSUE TITLE
Bug: Cannot Search value <ip>|<port> with rest api

### ISSUE THREAD

**Issue by m4rb3n** [MISP/MISP#8527]
### Expected behavior

curl --location -g --request POST 'https://misp.local/attributes/restSearch/' \
--header 'Authorization: <API_KEY>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "page": 0,
    "limit": 10,
    "from": "2022-08-09",
    "to": "2022-08-10",
    "type": "ip-dst|port",
    "value": "IP|PORT"
}'

should return values.

### Actual behavior

No values returned 

### Steps to reproduce

First query with only the IP defined:
curl --location -g --request POST 'https://misp.local/attributes/restSearch/' \
--header 'Authorization: <API_KEY>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "page": 0,
    "limit": 10,
    "from": "2022-08-09",
    "to": "2022-08-10",
    "type": "ip-dst|port",
    "value": "IP"
}'

it returns results.

When query with IP|PORT it does not return any results.
curl --location -g --request POST 'https://misp.local/attributes/restSearch/' \
--header 'Authorization: <API_KEY>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "page": 0,
    "limit": 10,
    "from": "2022-08-09",
    "to": "2022-08-10",
    "type": "ip-dst|port",
    "value": "IP|PORT"
}'

### Version

2.4.159

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @m4rb3n ,
We just merged #8530 to the `develop` branch, and you that will allow you to search for composite attributes types using a search request like this one:
```json
{
  "page": 0,
  "limit": 10,
  "from": "2022-08-09",
  "to": "2022-08-10",
  "type": "ip-dst|port",
  "value1": "IP",
  "value2": "PORT"
}
```

Hope this helps.
