### ISSUE TITLE
Support: New Correlations Engine first recorrelate failed

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8528]
### Support Questions

We installed 2.4.160 yesterday. After approx. 6 hours the job was seen as failed with WebUI Jobs. Prior to the failure we were seeing default feed ingestions failing with db deadlock (see sample excerpt from `error.log` below). Similar HTTP 500 were seen in some ron jobs custom PyMISP ingestion scripts.

1. How can we share more information with you to try to isolate root cause?
2. We've started a `Recorrelate` job for the active (new) engine via the WebUI and will monitor, and report back in this issue with results.
3. The failure was seen in the WebUI jobs; however, the corresponding row in the db `jobs` table still had a `status: 0`. Is there a mysql query that will reveal the failure in the `jobs` table? THis is a much easier way to find the failure vs. traversing the WebUI jobs.

### MISP version

2.4.160

### Operating System

RedHat

### Operating System version

8.4

### PHP version

7.4.28

### Relevant log output

```shell
120030 [PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock fou\
nd when trying to get lock; try restarting transaction
120031 Stack Trace:
120032 #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php\
(502): PDOStatement->execute()
120033 #1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php\
(468): DboSource->_execute()
120034 #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysq\
l.php(459): DboSource->execute()
120035 #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2848): Mysql->\
delete()
120036 #4 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(173):\
 Model->deleteAll()
120037 #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(2\
38): DefaultCorrelationBehavior->runBeforeSaveCorrelation()
120038 #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): Behavior\
Collection->dispatchMethod()
120039 #7 /var/www/MISP/app/Model/Correlation.php(261): Model->__call()
120040 #8 /var/www/MISP/app/Model/Attribute.php(418): Correlation->beforeSaveCo\
rrelation()
120041 #9 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute\
->afterSave()
120042 #10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): Better\
CakeEventManager->dispatch()
120043 #11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1754): Model-\
>_doSave()
120044 #12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2352): Model-\
>save()
120045 #13 /var/www/MISP/app/Model/Feed.php(1303): Model->saveMany()
120046 #14 /var/www/MISP/app/Model/Feed.php(1189): Feed->saveFreetextFeedData()
120047 #15 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downlo\
adFromFeedInitiator()
120048 #16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): Serve\
rShell->fetchFeed()
120049 #17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(2\
22): Shell->runCommand()
120050 #18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(6\
6): ShellDispatcher->dispatch()
120051 #19 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
120052 #20 {main}
```

### Extra attachments

Here's the `jobs` row that started but then was reported failed in the WebUI Jobs page:
```
mysql> select * from jobs where job_type like '%correlation%' order by id asc limit 1 \G
*************************** 1. row ***************************
           id: 1358491
       worker: default
     job_type: generate correlation
    job_input: All attributes
       status: 0
      retries: 0
      message: Correlating Event 193178 (20 MB used)
     progress: 1
       org_id: 0
   process_id: 27778066884972c4d8decefbc31134b6
 date_created: 2022-08-08 20:28:40
date_modified: 2022-08-09 02:30:51
1 row in set (0.02 sec)

mysql>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
The second attempt via the WebUI click to build with the new engine failed this time
* after 18 hours
* with progress=2
* 2.6M `default_correlations` rows
* 950k `correlation_values` rows.

There were also feed db deadlocks seen along the way.

Approx scale of this MISP instance:
* 235k events
* 135M attributes (90k deleted=1)

We'd really appreciate some assistance in finding root cause.

In the interim, so that we can use 2.4.160, we will regress back to the legacy correlation engine.

Thanks.

**Comment by github-germ** [comment]
Hmmm, I thought we could still enable the legacy correlation engine with 2.4.160; however, perhaps I'm missing the HOWTO or it isn't possible. Don't see it in the WebUI nor mentioned on https://github.com/MISP/MISP/blob/2.4/docs/correlations.rework.md

If not possible, we will need to go back to 2.4.159 which I imagine will cause us to restore the database form before the upgrade due to `db_version` schema going from 86 to 90.

Please advise. Thanks!

**Comment by iglocska** [comment]
It's not possible to enable the legacy one, though the issues would probably be the same there.

I've pushed some changes on the develop branch that could potentially help with the recorrelation, could you give that a shot and restart with that?

**Comment by iglocska** [comment]
In particular: 

DefaultCorrelationBehavior->runBeforeSaveCorrelation()   <- this was causing issues for us too, on the develop branch it skips that step altogether and uses something much more lightweight.

**Comment by github-germ** [comment]
Thanks. I will build from `develop`, try again, and report back.

**Comment by github-germ** [comment]
I'm likely missing something. I built from `develop` and launched. I do not see a newly auto started `job_type: generate correlation` in the db `jobs` table; nor do I see the new Correlation WebUI menu to start it manujally.

How do I relaunch the new correlations engine to start building?

**Comment by iglocska** [comment]
You should absolutely be able to see the new correlation UI under /servers/serverSettings/correlations - along with the button to relaunch the correlations.

**Comment by iglocska** [comment]
Also, indeed, switching to the other branch will not automatically relaunch the job, you will have to trigger it manually.

**Comment by github-germ** [comment]
Aha, the endpoint `/servers/serverSettings/correlations` works; however, the new `Correlations` top menu entry that was seen in the `v2.4.160` tagged branch is not there in `develop`.

OK... rebuilding with the new engine has commenced. I'll report back. Thx...

**Comment by iglocska** [comment]
I am puzzled why it's not there to be honest o.O I'm seeing it on the dev branch under administration -> server settings -> correlations. Let me know how it goes, we're prepping a bugfix release with the changes from develop (with some new things being added).

**Comment by github-germ** [comment]
OK, more coffee being order here. My bad... it's there. I was looking at the top level menus, not within Admin...

SORRY

**Comment by iglocska** [comment]
Ok, that makes sense :) Plenty of time for more coffee seeing how long the recorrelation takes sadly...

**Comment by github-germ** [comment]
@iglocska I see 2.4.161 was just released. Is the change you made herein included? So far, the rebuild is running. However, if your fix is in 2.4.161, I'd rather build that version and run the rebuild there. Thanks!

**Comment by iglocska** [comment]
Yep it is!

**Comment by github-germ** [comment]
**Super!!**

**Comment by iglocska** [comment]
Let me know how it goes! Also curious about metrics once the correlation is
done (especially space / memory use as well as general performance), since
you guys probably have the highest volume instance I know of.

**Comment by github-germ** [comment]
G'day... We are 12+ hours and still running successfully:
```
mysql> select count(*) from default_correlations;
+----------+
| count(*) |
+----------+
|  5422920 |
+----------+
1 row in set (0.05 sec)

mysql> select * from jobs where job_type='generate correlation' order by id desc limit 1 \G
*************************** 1. row ***************************
           id: 1359136
       worker: default
     job_type: generate correlation
    job_input: All attributes
       status: 0
      retries: 0
      message: Correlating Event 241429 (64 MB used)
     progress: 2
       org_id: 0
   process_id: 2e45a1e654d2d213e531ac9403423637
 date_created: 2022-08-11 23:48:49
date_modified: 2022-08-12 12:26:28
1 row in set (0.00 sec)

mysql> select count(*) from correlation_values;
+----------+
| count(*) |
+----------+
|   963643 |
+----------+
1 row in set (0.02 sec)

mysql> 
```

**Comment by github-germ** [comment]
One observation that may be related to the rebuilding process or something else in 2.4.161. Let me know if you have any thoughts on root cause.

We see more db deadlock conditions from a variety of our custom PyMISP client ingestion apps as well as MISP Built-In processes. In these cases, these aborted feeds, especially the premium ones cause issues for us. Once correlations rebuilding is completed we can see if these persist.

For example:
```
2022-08-12 08:50:48 Error: Could not save freetext feed data for feed 94.
[PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

2022-08-12 09:35:08 Error: Could not save freetext feed data for feed 44.
[PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

2022-08-12 09:50:09 Error: [PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
Request URL: /events/edit/288309/metadata:1

2022-08-12 09:52:09 Error: [PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
Request URL: /tags/removeTagFromObject
```

**Comment by github-germ** [comment]
btw, in `/etc/my.cnf` we have: `innodb_lock_wait_timeout = 900`

**Comment by iglocska** [comment]
The deadlocks are somewhat more "expected" - I remember you were already prone to those before with the concurrency. The recorrelation is crazy heavy on both writes and reads (though that was the case with the old engine too) - once the process is complete it will hopefully become a non-issue. How much is left percentage wise if you check the job itself?

**Comment by iglocska** [comment]
Though looking at the specific calls that cause the deadlocks I am not entirely sure it's related. I'd expect the correlation table to be heavily impacted, but removeTagFromObject should not even touch it...

**Comment by github-germ** [comment]
> How much is left percentage wise if you check the job itself?

`progress: 2` which we know is not really predictable as to wall clock time remaining since that's 2% of total events, and for use we have some events with 1M attrs, others with 1.

**Comment by github-germ** [comment]
I do see calls seemingly related to correlations with `removeTagFromObject` as below.
```
2022-08-12 10:32:52 Error: [PDOException] SQLSTATE[40001]: Serialization failur\
e: 1213 Deadlock found when trying to get lock; try restarting transaction
Request URL: /tags/removeTagFromObject
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): \
PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): \
DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(4\
25): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2672): Mysql->update(\
)
#4 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(584): Model-\
>updateAll()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): De\
faultCorrelationBehavior->updateContainedCorrelations()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollect\
ion->dispatchMethod()
#7 /var/www/MISP/app/Model/Event.php(441): Model->__call()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Event->afterSave\
()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEven\
tManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSav\
e()
#11 /var/www/MISP/app/Model/Event.php(5661): Model->save()
#12 /var/www/MISP/app/Controller/TagsController.php(970): Event->unpublishEvent\
()
#13 [internal function]: TagsController->removeTagFromObject()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): Refl\
ectionMethod->invokeArgs()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Control\
ler->invokeAction()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatc\
her->_invoke()
#17 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#18 {main}
```

**Comment by github-germ** [comment]
Same for a Built-In feed:
```
2022-08-12 10:32:16 Error: Could not save freetext feed data for feed 20.
[PDOException] SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when\
 trying to get lock; try restarting transaction
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): \
PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): \
DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(4\
25): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2672): Mysql->update(\
)
#4 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(584): Model-\
>updateAll()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): De\
faultCorrelationBehavior->updateContainedCorrelations()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollect\
ion->dispatchMethod()
#7 /var/www/MISP/app/Model/Event.php(441): Model->__call()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Event->afterSave\
()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEven\
tManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSav\
e()
#11 /var/www/MISP/app/Model/Feed.php(1333): Model->save()
#12 /var/www/MISP/app/Model/Feed.php(1189): Feed->saveFreetextFeedData()
#13 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromF\
eedInitiator()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell-\
>fetchFeed()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Sh\
ell->runCommand()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): She\
llDispatcher->dispatch()
#17 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#18 {main}
```

**Comment by github-germ** [comment]
And with `/events/edit/xxxxxx/metadata:1`
```
2022-08-12 10:06:11 Error: [PDOException] SQLSTATE[HY000]: General error: 1205 \
Lock wait timeout exceeded; try restarting transaction
Request URL: /events/edit/288309/metadata:1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): \
PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): \
DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(4\
25): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2672): Mysql->update(\
)
#4 /var/www/MISP/app/Model/Behavior/DefaultCorrelationBehavior.php(584): Model-\
>updateAll()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): De\
faultCorrelationBehavior->updateContainedCorrelations()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollect\
ion->dispatchMethod()
#7 /var/www/MISP/app/Model/Event.php(441): Model->__call()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Event->afterSave\
()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEven\
tManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSav\
e()
#11 /var/www/MISP/app/Model/Event.php(3810): Model->save()
#12 /var/www/MISP/app/Controller/EventsController.php(2696): Event->_edit()
#13 [internal function]: EventsController->edit()
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): Refl\
ectionMethod->invokeArgs()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Control\
ler->invokeAction()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatc\
her->_invoke()
#17 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#18 {main}
```

**Comment by iglocska** [comment]
Ha, I see! That's a nice catch! 

It looks like the correlation is being updated for all correlations of an event when it's edited. This somewhat makes sense if the distribution was changed, but only in that case. However, currently it fires in every case!

**Comment by github-germ** [comment]
These use cases do not revise distribution/sharing_group. Would it make sense, and would it be difficult to add logic to bypass correlation processing when no change is made in distribution?

**Comment by iglocska** [comment]
No this is definitely a bug and I'd expect that behaviour. I'll push something to 2.4 within a few minutes, we absolutely shouldn't recorrelate in those cases.

**Comment by iglocska** [comment]
ok hopefully this solves it, damn that was a nice find. Thanks for digging into the logs! Let me know if it persists with this change, basically it will only trigger that behaviour now if the distribution/sharing_group_id of the event changed.

**Comment by github-germ** [comment]
Cool!! I've included the revised `Event.php` in my Dev docker container. I will monitor, and report back.

**Comment by iglocska** [comment]
Cheers!

**Comment by github-germ** [comment]
Still running: about 6M correlations spanning about 1M values so far.

**Comment by github-germ** [comment]
Will update over the weekend: Running 25 hours, 4% events processed, 7.1M correlations, 1.1 values

Many custom and built-in feeds will run overnight. Will see about db deadlocks with the revised `Event.php` in place.

**Comment by github-germ** [comment]
Progress:
* 37 hours, 5%, 17.6M correlations, 3.0M values
* No db deadlocks with many ingestion apps running last night !!

**Comment by adulau** [comment]
Thanks for the info. It looks good. I was just wondering something which kind of HDD do you run the MySQL/MariaDB back-end on?

**Comment by iglocska** [comment]
> Progress:
> 
> * 37 hours, 5%, 17.6M correlations, 3.0M values
> * No db deadlocks with many ingestion apps running last night !!

Hell yeah! So they fix took. Thanks again for investigating it!

**Comment by github-germ** [comment]
Great news! ... The rebuilding process completed with success as follows:
* 45 hours, 100%, 22M correlations, 3.0M values

**Comment by iglocska** [comment]
Cheers, fantastic news. Did you by any chance compare the disk space use before and after the switch to the new engine? Just out of curiosity 😎

**Comment by github-germ** [comment]
I didn't capture before, but could do on another test system when we roll there. What specifically would you like me to measure?

**Comment by iglocska** [comment]
Disk space used by the engine (so the correlations.ibd file's size) before compared to the new correlations table size after (default_correlations.ibd)

We're doing similar comparisons and the size differences vary wildly from instance to instance (depending on how over-correlated the data is), but it's really just more of a curiosity :)
