### ISSUE TITLE
Copyright sign in footer double encoded

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#853]
In the MISP footer the copyright sign is double encoded:
```
Powered by MISP version 2.4.7 &amp;copy; Belgian Defense CERT &amp; NCIRC
```
So the copyright sign does not show.

**Comment by iglocska** [comment]
Replaced it in the default config, however this will not alter settings in instances already installed - it's a setting in the admin panel, so just replace it with the copyright sign in there for now please :)
