### ISSUE TITLE
Bug: trying to access array offset on value of type null when using "Import from URL" in the MISP report feature 

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#8531]
### Expected behavior

Use the MISP report feature with "Import from URL", fetches the HTML and converts it to MD.

### Actual behavior

```
2022-08-10 12:44:37 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/Model/Module.php, line 243]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
Module::__prepareAndExectureForTrigger() - APP/Model/Module.php, line 243
Module::queryModuleServer() - APP/Model/Module.php, line 266
EventReport::downloadMarkdownFromURL() - APP/Model/EventReport.php, line 919
EventReportsController::importReportFromUrl() - APP/Controller/EventReportsController.php, line 308
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 9
```

### Steps to reproduce

Create a MISP event, Reports, use "Import from URL".

### Version

2.4.160

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Extra attachments

Also added this as a MISP-module issue.
https://github.com/MISP/misp-modules/issues/573

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cudeso** [comment]
Seems $triggerData['Attribute'] is not set?

If you return true before https://github.com/MISP/MISP/blob/2.4/app/Model/Module.php#L243 then the error is gone and it's again possible to use the "Import from URL". But this beats the purpose of  __prepareAndExectureForTrigger

**Comment by cudeso** [comment]
$triggerData is empty. 
queryModuleServer(array $postData, $hover = false, $moduleFamily = 'Enrichment', $throwException = false, $triggerData=[])

Called in downloadMarkdownFromURL: $result = $this->Module->queryModuleServer($modulePayload, false);

**Comment by iglocska** [comment]
Ended up with a different fix - the reason it's not set there seems to be because you fall inbetween two cases - the module is not enabled, thus no data is fetched. 

Added a check for the module being enabled and we GTFO from the function if it's not immediately, no need to continue.
