### ISSUE TITLE
Bug: 2.4.160 requires an older db version

### ISSUE THREAD

**Issue by megupta** [MISP/MISP#8533]
### Expected behavior

Should require version 91

### Actual behavior

Requires version 90

### Steps to reproduce

1. Install 2.4.159
2. Upgrade that instance to 2.4.160
3. Visit diagnostics page and look at schema status
4. Compare expected vs actual columns, scroll to the bottom and compare expected vs actual db versions

### Version

2.4.160

### Operating System

Centos

### Operating System version

7.x

### PHP version

7.3

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
fixed via c764bb0e8f59d7f96f6730f01112e16fc0f3091c
