### ISSUE TITLE
Support: Error during MISP Install Apt is maybe locked, waiting 3 seconds.

### ISSUE THREAD

**Issue by W4lker19** [MISP/MISP#8539]
### Support Questions

My MISP install stays stuck in this

I have pip instaled !!

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox

### Extra attachments

![image](https://user-images.githubusercontent.com/62023102/184192770-cc6cacc2-b5ad-4bc7-8969-72842503502a.png)
![image](https://user-images.githubusercontent.com/62023102/184193195-01340a62-4ace-43aa-af6f-e51afdfa910d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Could not reproduce.
I would suggest you check if there is any other `apt` process running before you run the install.
Check:
```
sudo ps aux | grep -i apt
```

If so, you can kill these processes and try again.
```
sudo killall apt apt-get
```

Hope this helps.

**Comment by romarito90** [comment]
Hello @Leonardo1924  @righel , someone find a solution i have the same problem with my instance of MISP, I have an error in the part of the venv/bin/pip command not found and begin the count of 3 seconds like a loop

**Comment by L33V** [comment]
wondering if anyone has made any progress with this - or found a workaround as I amalso experiencing the same issue on 
PRETTY_NAME="Oracle Linux Server 8.8"

bash /tmp/INSTALL.sh -c
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ol
Next step: Checking if we are uptodate and checksums match
apt is maybe locked, waiting 3 seconds.
apt is maybe locked, waiting 6 seconds.
apt is maybe locked, waiting 9 seconds.

**Comment by W4lker19** [comment]
I change the OS VERSION of Ubuntu and the problem as been fixed.

**Comment by fehdkh** [comment]
@L33V i have the same probleme
i tried to install the RHEL 8.X version but the misp modules didn't work
and i think for this script RHEL doesn't work with apt
If you have found a solution can you help me

**Comment by L33V** [comment]
@fehdkh sorry for the delay - like @Leonardo1924 we switched to Ubuntu and everything worked as it was supposed to. I think the RHEL 8.x version still has some issues.
