### ISSUE TITLE
Support: An error on the cheking of the checksum sha1

### ISSUE THREAD

**Issue by dsalazarCazanhas** [MISP/MISP#8541]
### Support Questions

Hello I'm trying to install a Misp instance for testing purpose, I already installed two of them a couple of months ago and they worked fine, I used Ubuntu server 20.04 LTS. Now I tried on a Debian distribution 11 (Bullseye) and got the checksum error, try with ubuntu 20.04 and 22.04 and got the same error on both of them. I'm in a virtual environment using Proxmox, behind a no-authenticated proxy, in order to get de INSTALL.sh script I use wget and proxychains4 for simulate a sock connection to GitHub and it works fine but I don't know if maybe this affects the download along with the integrity of the file.

### MISP version

2.4

### Operating System

Ubuntu Server

### Operating System version

22.04

### PHP version

8.1.2

### Relevant log output

```shell
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 22.04
Next step: Checking if we are uptodate and checksums match
sha1:  does not match the installer sum of: 4296d40b11b3002df3fdfd69a508ed5ecacb8c13
Delete installer, re-download and please run again.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello,
Current installer checksums are correct, I cannot determine whether your proxy is modifying the contents of the files or not.
As a sidenote, MISP won't work with PHP 8.

Hope this helps.
