### ISSUE TITLE
Where are installation log stored for MISP

### ISSUE THREAD

**Issue by guaar** [MISP/MISP#8546]
Our MISP installation has failed and we noticed that during install some packages were not installed. I would like to review the installation logs again. 

Where are the installation or setup logs stored for misp? Thanks.

**Comment by righel** [comment]
Logs are not saved to a file, you should capture the terminal output/redirect Stdout to a file if you want to review them later again.
Keep in mind this output contains credentials in clear text.

Hope that helps.
