### ISSUE TITLE
Bug: Error on Event import (fetchEvents)

### ISSUE THREAD

**Issue by Benni0** [MISP/MISP#8549]
### Expected behavior

Events should be imported without errors and should be published when published = true in the MISP feed source events.

### Actual behavior

The import process throws errors because of not found user (the user indeed exists) and some events are not published.
It is interesting that some events are published correctly, but not all.

The user, which id is specified in the call of `fetchFeeds`  is passed in the `Event->_add()` function call, but not in the `Event->publish()` function call. In the `Event->publish()` function, the current user should be retrieved using `Configure::read('CurrentUserId');` which returns nothing (Event.php line 4410). For this reason, the getAuthUser call fails.

Log output is from the latest version of `Event.php`

### Steps to reproduce

Enable a MISP feed and execute fetchFeeds

### Version

2.4.161

### Operating System

CentOS

### Operating System version

8

### PHP version

7.4.30

### Relevant log output

```shell
2022-08-18 09:07:37 Error: Could not add event '553ea363-7aa4-426b-8f54-ad70950d210b' from feed 1.
[InvalidArgumentException] Invalid user ID.
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(4411): User->getAuthUser()
#1 /var/www/MISP/app/Model/Event.php(3669): Event->publish()
#2 /var/www/MISP/app/Model/Feed.php(1075): Event->_add()
#3 /var/www/MISP/app/Model/Feed.php(681): Feed->__addEventFromFeed()
#4 /var/www/MISP/app/Model/Feed.php(1159): Feed->downloadFromFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(233): Feed->downloadFromFeedInitiator()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Benni0** [comment]
My idea for fixing this bug is, to set the `CurrentUserId` setting, using `Configure::write` before calling `Event->publish()` - but I don't know which function is the best to define the setting.

**Comment by Benni0** [comment]
Hi @mokaddem,
thank you for merging my pull requests.
Can you please have a look on this issue?
This is the most problematic for me, because this prevents synced Events from being published.

**Comment by Benni0** [comment]
HI @mokaddem, Hi @adulau,
can please someone have a look at this issue?
This issue still exists in v2.4.162.

If you want I can create a pull request and implement a bugfix in `downloadFromFeedInitiator()` function, but I don't know, if this is the best place to set the userId.

`2022-09-13 08:01:07 Error: Could not add event '543b7c14-ec70-446e-b2f7-4620950d210b' from feed 1.
[InvalidArgumentException] Invalid user ID.
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(4445): User->getAuthUser()
#1 /var/www/MISP/app/Model/Event.php(3702): Event->publish()
#2 /var/www/MISP/app/Model/Feed.php(1086): Event->_add()
#3 /var/www/MISP/app/Model/Feed.php(681): Feed->__addEventFromFeed()
#4 /var/www/MISP/app/Model/Feed.php(1170): Feed->downloadFromFeed()
#5 /var/www/MISP/app/Console/Command/ServerShell.php(233): Feed->downloadFromFeedInitiator()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#10 {main}`

**Comment by righel** [comment]
thanks for the provided fix, merged.
