### ISSUE TITLE
Feature Request: Add send email action block to Workflow

### ISSUE THREAD

**Issue by vincenzocaputo** [MISP/MISP#8550]
### Is your feature request related to a problem? Please describe.

This request is related to a use case that is not covered by the new Workflow feature.
the idea is to send an email notification to all, or specific users when a certain event occurs (for example when a specific tag is added to a MISP event).

### Describe the solution you'd like

Add a new action block to workflows that could allow to send an email notification when one or more conditions are satisfied.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Hey, currently work in progress but a new `send-email` module is available on the `develop` branch (https://github.com/MISP/MISP/commit/d22e4263648faf17ae4c220f48ba6856bfb5e6b8)
Feel free to try it out! ;)
