### ISSUE TITLE
Bug: Event Block Rules don't seem to work anymore

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#8551]
### Expected behavior

When pulling from a remote MISP instance, events containing tags listed in "Administration" -> "Event Block Rules" shoudn't be blocked( should not be created). 

### Actual behavior

I regularly pull from https://misppriv.circl.lu. 
In my Event Block Rules, I have:
```
{
    "tags": ["pandemic:covid-19=\"health\""]
}
```
Since MISP 2.4.160 or 2.4.161 (I don't know since I directly jumped from 2.4.159 to 2.4.161), events like "[2022-08-18] CSSE COVID-19 daily report" are created back on our instance, while I don't need them. 

### Steps to reproduce

See above for the explanations. 
Note that I have no rule specified in "Sync actions" => "List servers".

### Version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Uh oh, that sounds bad. Will try to investigate this asap.

**Comment by righel** [comment]
Fixed via 5d4f73fcbbef577e39390cba0e38d7281de6cc4e

Thanks for reporting.
