### ISSUE TITLE
Admin password sent for new users during registration

### ISSUE THREAD

**Issue by amady3381** [MISP/MISP#8556]
### Expected behavior

Random password shall be sent to the new users for completing the registration.

### Actual behavior

Admin  passwords has been sent to the new users during registration.

### Steps to reproduce

1- add new user to the platform
2- choose send credentials automatically
3- user will receive email to complete the registration.
4- The email will contain the email address as a username and password (the password is admin password not random password)

### Version

 2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
Thank you very much for this report. Can you confirm which browser (and version) you are using?

**Comment by amady3381** [comment]
Firefox 
version: 101.0 (64-bit)

Google Chrome:
version: 104.0.5112.102 (64-bit)

**Comment by cvandeplas** [comment]
I believe this should fix the issue. On some browsers your credentials might autocomplete and when not being cautious this could result in your password being sent.

**Comment by amady3381** [comment]
The issue has been fixed in the new updated release 2.4.162 and higher versions

**Comment by cvandeplas** [comment]
excellent, thank you for the update
