### ISSUE TITLE
Bug: Problem with re-correlation feature

### ISSUE THREAD

**Issue by de-caen** [MISP/MISP#8558]
### Expected behavior

The result of initial correlation and re-correlation are the same.

### Actual behavior

The result of initial correlation and re-correlation are different.

### Steps to reproduce

1. Add 3 or more events.
2. Add attributes with the same value for each events.
    Let these be attr_a, attr_b, attr_c.
    Correlation is automatically set as attr_a->attr_b, attr_a->attr_c, attr_b->attr_c
    (This is expected behavior.)
3. Run re-correlate job.
   After job finished, correlation is set as attr_a->attr_b, attr_a->attr_c
    (Correlation attr_b->attr_c is not set.)

### Version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by de-caen** [comment]
I checked the MySQL general log in above situation.
As a result, it was found that the following SQL query was executed.
1. TRUNCATE TABLE default_correlations;
2. INSERT INTO \`misp\`.\`default_correlations\` (\`value_id\`, \`1_event_id\`, \`1_object_id\`, \`1_attribute_id\`, \`1_org_id\`, \`1_distribution\`, \`1_event_distribution\`, \`1_object_distribution\`, \`1_sharing_group_id\`, \`1_event_sharing_group_id\`, \`1_object_sharing_group_id\`, \`event_id\`, \`object_id\`, \`attribute_id\`, \`org_id\`, \`distribution\`, \`event_distribution\`, \`object_distribution\`, \`sharing_group_id\`, \`event_sharing_group_id\`, \`object_sharing_group_id\`) VALUES  (1, 2, 0, 2, 1, 5, 1, 0, 0, 0, 0, 1, 0, 1, 1, 5, 1, 0, 0, 0, 0), (1, 3, 0, 3, 1, 5, 1, 0, 0, 0, 0, 1, 0, 1, 1, 5, 1, 0, 0, 0, 0);
3. INSERT INTO \`misp\`.\`default_correlations\` (\`value_id\`, \`1_event_id\`, \`1_object_id\`, \`1_attribute_id\`, \`1_org_id\`, \`1_distribution\`, \`1_event_distribution\`, \`1_object_distribution\`, \`1_sharing_group_id\`, \`1_event_sharing_group_id\`, \`1_object_sharing_group_id\`, \`event_id\`, \`object_id\`, \`attribute_id\`, \`org_id\`, \`distribution\`, \`event_distribution\`, \`object_distribution\`, \`sharing_group_id\`, \`event_sharing_group_id\`, \`object_sharing_group_id\`) VALUES  (1, 2, 0, 2, 1, 5, 1, 0, 0, 0, 0, 1, 0, 1, 1, 5, 1, 0, 0, 0, 0), (1, 3, 0, 3, 1, 5, 1, 0, 0, 0, 0, 2, 0, 2, 1, 5, 1, 0, 0, 0, 0);
4. INSERT INTO \`misp\`.\`default_correlations\` (\`value_id\`, \`1_event_id\`, \`1_object_id\`, \`1_attribute_id\`, \`1_org_id\`, \`1_distribution\`, \`1_event_distribution\`, \`1_object_distribution\`, \`1_sharing_group_id\`, \`1_event_sharing_group_id\`, \`1_object_sharing_group_id\`, \`event_id\`, \`object_id\`, \`attribute_id\`, \`org_id\`, \`distribution\`, \`event_distribution\`, \`object_distribution\`, \`sharing_group_id\`, \`event_sharing_group_id\`, \`object_sharing_group_id\`) VALUES  (1, 3, 0, 3, 1, 5, 1, 0, 0, 0, 0, 1, 0, 1, 1, 5, 1, 0, 0, 0, 0), (1, 3, 0, 3, 1, 5, 1, 0, 0, 0, 0, 2, 0, 2, 1, 5, 1, 0, 0, 0, 0);

It looks good. But I ran these SQL queries manually and got the following results.
1. Query OK, 0 rows affected (0.028 sec)
2. Query OK, 2 rows affected (0.001 sec)
    Records: 2  Duplicates: 0  Warnings: 0
3. **ERROR 1062 (23000): Duplicate entry '1-2-1' for key 'unique_correlation'**
4. **ERROR 1062 (23000): Duplicate entry '1-3-1' for key 'unique_correlation'**

Queries 3 and 4 resulted in errors and no records were inserted.

So, it was probably caused by the following line in [`app/Model/Behavior/DefaultCorrelationBehavior.php`:](https://github.com/MISP/MISP/blob/2.4/app/Model/Behavior/DefaultCorrelationBehavior.php#L150)

            $db = $this->Correlation->getDataSource();
            // Split to chunks datasource is is enabled
            if (count($correlations) > 100) {
                foreach (array_chunk($correlations, 100) as $chunk) {
                    $db->insertMulti('default_correlations', $fields, $chunk);
                }
                return true;
            } else {
                return $db->insertMulti('default_correlations', $fields, $correlations);
            }

This code does not work as expected due to the unique key constraint in `default_correlations` table:
`UNIQUE KEY 'unique_correlation' ('attribute_id','1_attribute_id','value_id')`

**Comment by adulau** [comment]
Could you tell which version of MISP (`commit-id`) you are using?

**Comment by de-caen** [comment]
I use MISP v2.4.161 (`5be42812dd3913f91dd78a00d2a40ff653f6b942`).

**Comment by de-caen** [comment]
Thank you for fixing!
