### ISSUE TITLE
Bug: Workflow Module_push_zmq not working

### ISSUE THREAD

**Issue by bcampru** [MISP/MISP#8559]
### Expected behavior

This module should push the received data to zmq after extracting the value specified on the `data_extraction_path` attribute.

### Actual behavior

It's not working beacuse it's sending the data to the function `push_zmq` Json encoded when it shouldn't it should be `$this->push_zmq($extracted);` instead of $this->push_zmq(JsonTool::encode($extracted));`.

There is also an error when getting the data extraction path, it should be `$params["data_extraction_path"]["value"];` instead of `$params['match_condition']['value'];`

### Steps to reproduce

Create a workflow that pushes an attribute to zmq every time an attribute is saved

### Version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Chrome

### Extra attachments

Fixed code (located at Model/WorkflowModules/action/Module_push_zmq.php):

```php
    public function exec(array $node, WorkflowRoamingData $roamingData, array &$errors=[]): bool
    {
        parent::exec($node, $roamingData, $errors);
        $params = $this->getParamsWithValues($node);
        #$path = $params['match_condition']['value'];
        $path = $params["data_extraction_path"]["value"];
        $data = $roamingData->getData();
        $extracted = $this->extractData($data, $path);
        if ($extracted === false) {
            $errors[] = __('Error while trying to extract data with path `%s`', $path);
            return false;
        }
        #$this->push_zmq(JsonTool::encode($extracted));
        $this->push_zmq($extracted);
        return true;
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Did you restart your ZMQ service in MISP? It's usually the origin of this as the configuration changed. Feel free to reopen if the issue persists.
