### ISSUE TITLE
Bug: commit c932717 did not change db_version in db_schema.json

### ISSUE THREAD

**Issue by skalvaro** [MISP/MISP#8561]
### Expected behavior

No errors reported on diagnostics page when updating to v2.4.161 (c9327174b969edad2c4ddf276c1051b04438f918).

### Actual behavior

DB version warning and column delta entries on table `over_correlating_values` after update to v2.4.161 (c9327174b969edad2c4ddf276c1051b04438f918).

### Steps to reproduce

Update to v2.4.161 (c9327174b969edad2c4ddf276c1051b04438f918).

### Version

2.4.161

### Operating System

RedHat

### Operating System version

7.9

### PHP version

7.4

### Extra attachments

![image](https://user-images.githubusercontent.com/10258537/187461938-4e6094a2-df43-4c77-a5b6-47f5024c0464.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ostefano** [comment]
I am not sure the database version check fails because of those errors on that table. I am seeing the same issue on a fresh installation.

**Comment by righel** [comment]
Hello @skalvaro ,
Just pushed a commit (687a558c0d70d7d9d3bc1b03b2667b60e1179198) fixing this issue. 
Thanks for reporting.

**Comment by ostefano** [comment]
@righel note that the proposed change does not address the fact that the expected schema expects a nullable field. See below:
<img width="1010" alt="Screenshot 2022-08-31 at 10 06 47" src="https://user-images.githubusercontent.com/979520/187642080-2a3fcd84-b3d9-4690-a32a-2deecf316d50.png">

**Comment by righel** [comment]
Hello @ostefano 
The expected is to `over_correlating_values`.`value` to be not null, see: https://github.com/MISP/MISP/commit/c9327174b969edad2c4ddf276c1051b04438f918#diff-f5612e5237fac98d81298f75cf21487e0930c39f1ded9da2f44eaf520f6957fcR1860

Since your instance already run the update to db version 94

**Comment by righel** [comment]
Hello @ostefano ,
Just pushed another fix (47674a80511f058ea35fff0a423b62d69e7139f9) the default value and encoding were not correct.
Let me know if it shows no deltas now.

**Comment by ostefano** [comment]
All good, no errors anymore (using mariadb 10.9.2)
