### ISSUE TITLE
MISP logs shows reverse proxy IP only

### ISSUE THREAD

**Issue by amady3381** [MISP/MISP#8563]
### Support Questions

We have configured MISP with MISP.log_client_ip_header : REMOTE_ADDR

However all the logs shows only the reverse proxy IP. To troubleshoot API connection, this is not helping.

Please provide the exact configuration needed to show the real IP address of the remote users.

### MISP version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

firefox

### Browser version

101.0 (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
MISP wull just use whatever your webserver puts in REMOTE_ADDR. This would i.e. be done with mod_remoteip in Apache2. Exact configuration depends on what headers your reverse proxy sends. https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html

**Comment by righel** [comment]
also check similar thread: https://github.com/MISP/MISP/issues/6526#issuecomment-719349793

hope that helps.
