### ISSUE TITLE
How best to Export/Import MISP-A Event into MISP-B avoiding org_NNNN creation on B

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8566]
### Support Questions

...Looking for advice on this use case...

1. 3 MISP Instances with no network connection to each other, e.g.
   Dev, Test, Production.
2. Each run independently pulling in the same feeds separately.
3. Orgs are pretty similar on all 3 instances, but all have different
   id's and uuid's.
4. Same for Sharing Groups
5. At times, data is pulled into MISP-A and once vetted in Dev we
   export the Events via WebUI 'Download as...' JSON, and import
   via WebUI "Import from..." into MISP-B.
6. Since the Org.uuid and SharingGroup.uuid are different on MISP-A
   and MISP-B, MISP-B imports the Event content fine, but creates
   a new Org as ORG-A.name_NNNN (i.e. 4 random digits); likewise
   for the SharingGroup.
7. This now causes lots of similar, but actually different Orgs and
   SharingGroups on MISP-B when the goal was for this imported Event
   in MISP-B to have same content with the Org and SharingGroup that
   already existed on MISP-B. (Note these *_NNNN are only created
   because there is no matching local Org.uuid)
8. MISP-B is now "dirty".

...What is the best way to avoid this mess?...

For example,

1. use a different export format on MISP-A, e.g. something that
   does not carry the Org/SG details, and then after importing
   into MISP-B, we can set Org/SG as needed via the WebUI?
2. do we need make all Org.uuid and SharingGroup.uuid the same on all
   3 instances, i.e. a one-time edit across instance, and make
   sure when adding new Orgs/SGs that uuid are set same?
3. do we need to grant network connections to all 3 instances, and
   if so, how would this help to align Orgs and SGs, e.g. would using
   local/remote help and if so how do we configure?
4. other??

...Cleaning up our mess: Is there a better way?...

We do now need to prevent the continued creation of *_NNNN Orgs and SGs
followed by cleaning house by moving all those Events back to the
correct local pre-existing Org and SG. So far we've not been able
to get PyMISP to reset Orgc/orgc_id from MISP-B.Org.name_NNNN back
to MISP-B.Org.name in the existing Event. So we are now contemplating
pulling those Events into PyMISP, revising, pushing back as new
Events and deleting the old. And finally, deleting the Org_NNNN
once all those member Events are gone.

### MISP version

2.4.161

### Operating System

RedHat

### Operating System version

8.4

### PHP version

7.4.28

### Browser

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UFOSmuggler** [comment]
i wrote a thing (that i unfortunately cant share, done for work), which looks at the event for existing owner org, uses an administrative auth key to check for the existence of that org, and then for a sync user for that org, and then generates and caches a new auth key for that org.  then it inserts the event with that auth key, thus the owner is the original org.

if the org, sync user dont exist it just creates them.

you end up with a lot of local organisations, but maybe that's ok for you, or you can clean them up after.

**Comment by github-germ** [comment]
Thx. We are writing a daily housecleaning PyMISP cron job that will do something similar: Realign the org_NNNN and sg_NNNN to the non_NNNN selections in a memory image of the Event, add that revised Event back to MISP, delete the original Event, remove those org_NNNN, sg_NNN if possible.

The bigger unanswered question is there a better way in our use case to execute export/import without those NNNN being created so that we don't need this housecleaning cron job?

For example, I did mention above aligning org and sg uuid's.

Are we the only folks experiencing this?

**Comment by UFOSmuggler** [comment]
you're just gonna have to overstamp the org/orgc uuids to whatever you want it to show up as on that misp, before you add it to the misp.  the sharing group should create on the misp once only though, assuming you overstamp the orgs there too.

**Comment by github-germ** [comment]
Yes, we can edit the exported JSON before importing. However, our use case is threat intelligence analysts only doing export /import with WebUI clicks without editing JSON. 

So our hack is this nightly cron job to perform the realignment housecleaning.

**Comment by UFOSmuggler** [comment]
good idea:  create an org for all possible valid uuid4s with the same org name.  great victory.

actual good idea: create mysql triggers BEFORE INSERT and BEFORE UPDATE to change the org id and org uuid to whatever you want it to be:

```
CREATE TRIGGER IF NOT EXISTS override_event_org_id
  BEFORE INSERT on events
    FOR EACH ROW 
      SET NEW.org_id = 1;
      SET NEW.orgc_id = 1;
      and so on....
END; 
```

something like that anyway, i forget the exact syntax.  also need one for the organisations table too, and SGs etc....

**Comment by github-germ** [comment]
We've implemented a nightly cronjob to mitigate these cases. Thanks!
