### ISSUE TITLE
Cannot remove global attribute tag unless site admin v2.4.161

### ISSUE THREAD

**Issue by midpipps** [MISP/MISP#8567]
### Expected behavior

If you own the even or have the correct permissions for an org owned event you should be able to remove the tag.

### Actual behavior

Edge case but if the first event in the system was created by another org.  You can no longer remove global tags due to the attribute controller removetag function pulling the first event in the system rather then the current event.

### Steps to reproduce

prereqs.
Non site admin
In an org different then first event in system org.

Steps
Create event
Add attribute to event
Add global tag to attribute
Attempt to remove global tag

Caused by
  AttributesController.php in the removetag function.
  Conditions  is misspelled conditions causing system to grab first record instead of first record with event.id
                'conditons' => ['Event.id' => $attribute['Attribute']['event_id']]

### Version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.2

### Browser

All

### Relevant log output

```shell
No logs found.  Will show popup error.
You do not have permission to do that.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks for digging into this, nice catch, it was my bad!

**Comment by iglocska** [comment]
Thanks for digging into this, nice catch, it was my bad!

**Comment by midpipps** [comment]
Thanks for fixing it and for helping get me started in looking for it.  You rock.

  I would have done a fix pull request but haven't been back near a computer.
