### ISSUE TITLE
Bug: Wrong database "wrench" diagnostics DEFAULT "NULL" NULL 

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#8587]
### Expected behavior

When clicking on the Diagnostics page and then on the database Schema status, you will see lots of wrench symbols with the recommendation on how to fix something in the schema.

However, the SQL statement there is wrong.

Example:
```sql
ALTER TABLE `attributes` MODIFY COLUMN `last_seen` bigint(20) DEFAULT "NULL" NULL ;
```

Should be:
```sql
ALTER TABLE `attributes` MODIFY COLUMN `last_seen` bigint(20) DEFAULT NULL ;
```

Note the redundant `"NULL"`

### Actual behavior

Example:
```sql
ALTER TABLE `attributes` MODIFY COLUMN `last_seen` bigint(20) DEFAULT "NULL" NULL ;
```

### Steps to reproduce

upgrade to 2.4.162

### Version

2.4.162

### Operating System

Debian

### Operating System version

bullseye

### PHP version

n/a

### Browser

n/a

### Browser version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
fixed via https://github.com/MISP/MISP/pull/8618

thanks for reporting.
