### ISSUE TITLE
Attachments not being pulled?

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#862]
I've noticed on two different instances (mine running 2.4.7 and a remote one running 2.4.5) that the attachments for the events pulled are not available. If I have a look on my instance at the event with the name "Suspicious sample" published by CIRCL yesterday and pulled onto my instance, I see that there should be a malware sample ( 	
c9962796633aa24b3dc71403b9d9b42e4f58a383) but when I click on the link I see the following on my error.log:

==> error.log <==
Stack Trace:
#0 /var/www/MISP/app/Controller/AttributesController.php(313): CakeResponse->file('files/1988/2087...', Array)
#1 /var/www/MISP/app/Controller/AttributesController.php(292): AttributesController->__downloadAttachment(Array)
#2 [internal function]: AttributesController->download('208763')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2016-01-19 12:41:28 Error: [NotFoundException] The requested file was not found
Request URL: /attributes/download/208763
Stack Trace:
#0 /var/www/MISP/app/Controller/AttributesController.php(313): CakeResponse->file('files/1988/2087...', Array)
#1 /var/www/MISP/app/Controller/AttributesController.php(292): AttributesController->__downloadAttachment(Array)
#2 [internal function]: AttributesController->download('208763')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

On my instance the directory /var/www/MISP/app/files and all its subdirectories are owned by www-data.

On another instance running 2.4.5, if I have a look at the event 'Dridex of the day (2016-01-15)' which was published by CIRCL, there should be also a malware-sample (08g7g6r56r.exe) but when I click on the link, I receive the following message on screen:

The requested file /var/www/MISP/app/files/68/2400 was not found or not readable

Error: The requested address '/attributes/download/2400' was not found on this server.
Stack Trace

    APP/Controller/AttributesController.php line 313 → CakeResponse->file(string, array)
    APP/Controller/AttributesController.php line 292 → AttributesController->__downloadAttachment(array)
    [internal function] → AttributesController->download(string)
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(AttributesController, array)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(AttributesController, CakeRequest)
    APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by iglocska** [comment]
Indeed, damn that's not an issue. I've pushed a fix for this, the samples should now correctly get pulled.

If you have any pulled events with the sample missing, just delete it and pull it again and it will download it. 

Sorry for the inconvenience!

**Comment by h122015** [comment]
I deleted the event on my instance and pulled it again from misppriv, but I doesn't get pulled. The same happened yesterday when I deleted an event on my instance which was pulled from a remote instance. I tried pulling that same event again and again (using the explorer function) but it never got pulled to my instance. The scheduled pulled didn't pulled it either

**Comment by iglocska** [comment]
Do you have event blacklisting enabled by any chance? That will
automatically blacklist an event if you delete it.

**Comment by h122015** [comment]
Yep, the blacklist was the problem and the attachments are now working fine. Thank you very much :)

**Comment by iglocska** [comment]
Excellent, glad that it worked out. Thanks for finding all the bugs! :)

**Comment by h122015** [comment]
I think I still have some problems with the attachments. It seems to me that new events (events created after the date the fix was committed) created with attachments are being properly pulled to my instance along with the attachment, but apparently old events aren't. 
Today on my instance I noticed that the event "OSINT - TLP: WHITE - Opertation "Ke3chang" Targeted Attacks Against Ministries of Foreign Affairs TLP:AMBER - Samples" which was created on 2013-12-10 and modified yesterday to add some attributes has also some attachments (US_military_options_in_Syria.zip and US_military_options_in_Syria.pdf.exe created on 2013-12-11) which are not being transfered to my instance. I delete this event on my instance and pulled it again and the attachments are not being transferred,

**Comment by adulau** [comment]
Nice finding. I think the issue is from our side. I cannot get the samples too. We'll check.
