### ISSUE TITLE
Bug: CIRCL OSINT Feed sync creates new Event every time 

### ISSUE THREAD

**Issue by djha983** [MISP/MISP#8630]
### Expected behavior

I have enabled CIRCL OSINT Feed to pull the feed daily.However i expect it to create one event and insert IOC to same event everytime.

### Actual behavior

I have enabled CIRCL OSINT Feed to pull the feed daily.However i expect it to create one event and insert IOC to same event everytime.However it is creating new event every time.How can i configure it to insert IOC to same event every time.Same issue for any feed source which is published in MISP format.

### Steps to reproduce

Enable any MISP Firmat feed.

### Version

2.4.161

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
The CIRCL OSINT feed is in MISP format. You should have by default unique MISP event. There is no need of fixed event in such case.

**Comment by djha983** [comment]
Ok,so that is expected behavior.Thanks
