### ISSUE TITLE
Bug: Revisiting MysqlExtended DboSource to support index query hints

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8633]
### Expected behavior

Fast WebUI `Search Attributes` queries.

### Actual behavior

Slow: 5-6 minutes, when it should be 1-2 seconds.

### Steps to reproduce

Perform a search query on 1.6k IPs.

@righel I'm sure you recall https://github.com/MISP/MISP/pull/8390 and https://github.com/MISP/MISP/issues/3321 where in 2.4.159 you added `MysqlExtended` index query hinting to greatly improve the performance of WebUI `Search Attribute` queries. All was good back then in 2022-May. However, our Production MISP instance is once again experiencing very slow query response time. 

When I hacked `/var/www/MISP/app/Model/Datasource/Database/MysqlExtended.php` to replace `USE INDEX` with `FORCE INDEX`, the query responds again very fast.
```
    private function __buildIndexHint($useIndexHint = null): string
    {
        $index = '';
        if (isset($useIndexHint)) {
            /*$index = 'USE INDEX ' . $useIndexHint;*/
            $index = 'FORCE INDEX ' . $useIndexHint;
        }
        return $index;
    }
```

I do notice that on my Development MISP instance running 2.4.163 that the exact same query with `USE INDEX` (not `FORCE INDEX`) performs very fast also. I reviewed the db changes applied in `app/Model/AppModel.php` from `db_version` `87` to `93` and didn't notice anything that would affect this query.

1. We are not updating Production to >= 2.4.163 until November. Are there any changes, other than the hack to `MysqlExtended.php` that can fix this, e.g. something in the db?
2. Why did this change on 2.4.159 when it was fast and now is slow, e.g. db heuristics?
3. Do you have any idea why our 2.4.163 MISP instance is fast with the same query that is slow on 2.4.159?

Thanks!!

### Version

2.4.159

### Operating System

RedHat

### Operating System version

8.6

### PHP version

7.4.30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hi,
I has to be related to the data composition and heuristics of your prod database.

Regarding 3, are you comparing the same database but different codebase?

I think it's safe to change the hint to be `FORCE` instead of `USE` so we ensure the db engine does not discard it.

**Comment by github-germ** [comment]
Hey @righel ... Thanks a lot for your quick reply and insight.

Heuristics makes sense. Re' 3, the db content on both is not the same, but iis being feed by similar automation.

Are you cool with making the change to go with `FORCE`?

**Comment by righel** [comment]
This index hint hack was introduced for solving this particular issue and it's not currently used elsewhere, so makes sense to move it to `FORCE` in my opinion.

**Comment by github-germ** [comment]
EXCELLENT. Many thanks!

**Comment by github-germ** [comment]
@righel I know you don't like to advertise ETAs for the next release date. We only deploy your "official" releases to our Production system. Would be a great help if 2.4.164 was released in the next week or so to match up with our next deployment. If not, then I will work a patch for this for 2.4.163. Any insight appreciated!
