### ISSUE TITLE
Bug: Newly created users with "External auth key" set should not be forced to change password on first login (via CustomAuth)

### ISSUE THREAD

**Issue by pettai** [MISP/MISP#8636]
### Expected behavior

Summary: 
Then a new user with "External Auth Key" configured is created, "User must change Password" should be disabled by default.

Background:
New fresh MISP installation + CustomAuth configured (and Apache + OpenIDC as reverse proxy infront of MISP)
Then new users are created with external authentication ("External Auth Key" configured, MISP should be passwordless for them on first login, as no password is set (Enabling "External Auth Key" also disables/removes the "Set password" option)
This older issue https://github.com/MISP/MISP/issues/7488 shows earlier somewhat related issues with CustomAuth vs regular user/passwords in MISP

### Actual behavior

Then a newly created user logs into MISP via CustomAuth, they are greeted with the "Change your password" view, and can't continue (as there is no know password set for the new MISP user)

This happens because "User must change Password" is set then the user was created (but is hidden from the administrator in the add user view. 

<img width="1011" alt="Screenshot 2022-10-04 at 13 09 02" src="https://user-images.githubusercontent.com/3317462/193820346-325746e1-9769-4b91-84d8-31f6fac9ddf1.png">

(Even if Plugin.CustomAuth_required = 1 is set, newly created users are still treated like they have a (known) password that needs to be changed at first login.)

### Steps to reproduce

1) Install MISP
2) Configure CustomAuth
3) Create user with CustomAuth enabled (External Auth Key enabled)
4) Login as the new user via CustomAuth
5) Get the Change your Password page in your face

### Version

2.4.163

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.3

### Browser

All of them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pettai** [comment]
@righel thanks for looking into this.
I think it's a bad idea to require password-change for users then login via external auth in general.
(I see your linked chg removes password-change, but only then custom_auth is a requirement)

**Comment by righel** [comment]
Hello @pettai
If you decide to still allow regular password logins (`CustomAuth_required` set to `false`) I believe we should not lower MISP default security measures. 

As an admin you can edit users and override the change password requirement right after you create them:
![image](https://user-images.githubusercontent.com/1659902/194268424-db297549-e03d-4f79-8d7b-3fd509198b4c.png)

Hope this helps, closing for now.
