### ISSUE TITLE
An Internal Error Has Occurred.  Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### ISSUE THREAD

**Issue by JERAR1337** [MISP/MISP#8644]
Today I followed instructions on https://misp.github.io/MISP/UPDATE/ to update my MISP server from 2.4.143 to the latest version 2.4.163 (current).

1. cd /var/www/MISP
2. sudo -u apache git pull origin 2.4
3. sudo -u apache git submodule update --init --recursive

Everything went smooth until I wanted to test out the server (webGUI)

I get an error (see title) when I go to the webGUI.

I looked into the following *.log files, but I don't see any errors.

/var/log/httpd/
/var/www/MISP/app/tmp/logs
- error.log
- debug.log
- resque-*

Source: https://wlcg-soc-wg-doc.web.cern.ch/misp/troubleshooting.html

I restarted the complete server to make sure.

Currently running:
Red Hat Enterprise Linux Server release 7.9 (Maipo)

MISP was working perfect before I try updating it.

Any ideas where I can look?

**Comment by JERAR1337** [comment]
**Update:**

I found the following error in /var/www/MISP/app/tmp/logs/error.log

**Error: [InvalidArgumentException] Invalid background job queue , must be one of: [default, email, cache, prio, update, scheduler]**
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(320): BackgroundJobsTool->validateQueue('')
#1 /var/www/MISP/app/Model/Server.php(3623): BackgroundJobsTool->getQueueSize('')
#2 /var/www/MISP/app/Model/AppModel.php(2378): Server->workerDiagnostics(106)
#3 /var/www/MISP/app/Controller/AppController.php(237): AppModel->runUpdates()
#4 /var/www/MISP/app/Controller/UsersController.php(31): AppController->beforeFilter()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 /var/www/MI

**Comment by righel** [comment]
Hello @JERAR1337
By any chance have you updated your PHP version ?

Could you please check if this solves your issue? 
https://github.com/MISP/MISP/issues/1204#issuecomment-871360030

Hope this helps.

**Comment by syloktools** [comment]
Same issue here:
```
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#2 /var/www/MISP/app/Model/Server.php(7611): BackgroundJobsTool->getWorkers()
#3 /var/www/MISP/app/Model/Server.php(3586): Server->getWorkers()
#4 /var/www/MISP/app/Controller/ServersController.php(1204): Server->workerDiagnostics()
#5 [internal function]: ServersController->serverSettings()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
2022-10-06 21:00:36 Error: [Error] Class 'fXmlRpc\Client' not found
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(611): BackgroundJobsTool->createSupervisorConnection()
#1 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(286): BackgroundJobsTool->getSupervisor()
#2 /var/www/MISP/app/Model/Server.php(7611): BackgroundJobsTool->getWorkers()
#3 /var/www/MISP/app/Model/Server.php(3586): Server->getWorkers()
#4 /var/www/MISP/app/Controller/ServersController.php(1204): Server->workerDiagnostics()
#5 [internal function]: ServersController->serverSettings()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

**Comment by syloktools** [comment]
Fix it. Upgrading these older instances that had the background jobs migrated to supervisor made something break. Honestly not sure what. But to fix I did the following:

```
sudo apt-get install composer
```
```
cd /var/www/MISP/app
sudo -u www-data composer require supervisorphp/supervisor \
    guzzlehttp/guzzle \
    php-http/message  \
    lstrojny/fxmlrpc
```
```
sudo service supervisor restart
```
```
sudo service apache2 restart
```


Hope this helps someone else. I think this happened because I updated CakeResque and its dependencies as well after converting to background jobs.

**Comment by JERAR1337** [comment]
> pe this helps someone el

Hi,

Thank you for the fast reply.

I did not update anything separate, just followed the instructions mentioned on the[ official update page](https://misp.github.io/MISP/UPDATE/) . (Option 1)

- cv /var/www/MISP
- sudo -u apache git pull origin 2.4
- sudo -u apache submodule update --init --recursive

Will let you know tomorrow.

**Comment by JERAR1337** [comment]
> Hello @JERAR1337 By any chance have you updated your PHP version ?
> 
> Could you please check if this solves your issue? [#1204 (comment)](https://github.com/MISP/MISP/issues/1204#issuecomment-871360030)
> 
> Hope this helps.

Hey [righel](https://github.com/righel),

No, I did not update my PHP version. My MISP instance was working fine until I update to the latest version.

**Comment by intellifense** [comment]
Hi Everyone
#7319 I have the following problem in /var/www/MISP/app/tmp/logs/error.log

2025-02-12 15:06:43 Error: [TypeError] BackgroundJob::__construct(): Argument https://github.com/MISP/MISP/issues/1 ($properties) must be of type array, string given, called in /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php on line 345
Request URL: /jobs/index
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(345): BackgroundJob->__construct()
https://github.com/MISP/MISP/issues/1 /var/www/MISP/app/Controller/JobsController.php(197): BackgroundJobsTool->getJob()
https://github.com/MISP/MISP/issues/2 /var/www/MISP/app/Controller/JobsController.php(43): JobsController->__getJobStatus()
https://github.com/MISP/MISP/issues/3 [internal function]: JobsController->index()
https://github.com/MISP/MISP/issues/4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(500): ReflectionMethod->invokeArgs()
https://github.com/MISP/MISP/issues/5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
https://github.com/MISP/MISP/issues/6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
https://github.com/MISP/MISP/issues/7 /var/www/MISP/app/webroot/index.php(107): Dispatcher->dispatch()
https://github.com/MISP/MISP/issues/8 {main}

Could someone help me, please?
