### ISSUE TITLE
Feature Request: Add option to add a local tag via workflow Tag operation module

### ISSUE THREAD

**Issue by syloktools** [MISP/MISP#8657]
### Is your feature request related to a problem? Please describe.

During workflows there are times when you want to add a tag set to local instead of global. 

### Describe the solution you'd like

Add a check box to the Tag operation (add tag) module to make the tag added Local.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Implemented in the latest version of MISP.
