### ISSUE TITLE
Support: Is it possible to add plugins in the MISP platform?

### ISSUE THREAD

**Issue by Aledangelo** [MISP/MISP#8667]
### Support Questions

In the project directory there is a folder called “Plugin”, is it possible to add functionality to the MISP by creating custom plugins?

### MISP version

2.4.15

### Operating System

Linux

### Operating System version

20.4

### PHP version

7.4.30

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samitainio** [comment]
@Aledangelo I'm not exactly sure what you have in mind but I recommend taking a look at the MISP modules first there are quite a lot of different modules available and you can also create your own. I don't know what is the history for the plugin folder maybe the devs can elaborate on that.

More details here https://github.com/MISP/misp-modules

**Comment by Aledangelo** [comment]
Thanks a lot, that's just what I needed
