### ISSUE TITLE
fresh install errors Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by honey4free** [MISP/MISP#870]
The thing wont work.
i get a when trying to access http://ip/MISP/app/

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.
Download: PGP/GPG key
Powered by MISP
Loading

2016-01-21 09:16:09 Error: Fatal Error (1): Call to undefined method App::checkMISPVersion() in [/var/www/MISP/app/Controller/AppController.php, line 82]
2016-01-21 09:16:09 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP/app/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 82)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

2016-01-21 09:16:31 Error: Fatal Error (1): Call to undefined method App::checkMISPVersion() in [/var/www/MISP/app/Controller/AppController.php, line 82]
2016-01-21 09:16:31 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP/app/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 82)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

2016-01-21 09:16:44 Error: Fatal Error (1): Call to undefined method App::checkMISPVersion() in [/var/www/MISP/app/Controller/AppController.php, line 82]
2016-01-21 09:16:44 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP/app/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 82)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

2016-01-21 09:19:31 Error: Fatal Error (1): Call to undefined method App::checkMISPVersion() in [/var/www/MISP/app/Controller/AppController.php, line 82]
2016-01-21 09:19:31 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP/app/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 82)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

2016-01-21 09:20:51 Error: Fatal Error (1): Call to undefined method App::checkMISPVersion() in [/var/www/MISP/app/Controller/AppController.php, line 82]
2016-01-21 09:20:51 Error: [InternalErrorException] Internal Server Error
Request URL: /MISP/app/webroot/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/MISP/a...', 82)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/MISP/a...', 82, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

2016-01-21 09:21:02 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[28000] [1045] Access denied for user \'mispadmin\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /MISP/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3626): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3653): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1387): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(267): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('User', Array)
#10 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#11 [internal function]: AppModel->__construct(Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#13 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(263): ClassRegistry::init('User')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(Event), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('Event', Array)
#17 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#18 /var/www/MISP/app/Model/Event.php(259): AppModel->__construct(Array, NULL, NULL)
#19 [internal function]: Event->__construct(Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(741): ClassRegistry::init(Array)
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(367): Controller->loadModel('Event')
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(405): Controller->__isset('Event')
#24 /var/www/MISP/app/Controller/AppController.php(82): Controller->__get('Event')
#25 /var/www/MISP/app/Controller/EventsController.php(41): AppController->beforeFilter()
#26 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#27 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#28 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#29 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#30 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#31 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#32 {main}

2016-01-21 09:21:34 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[28000] [1045] Access denied for user \'mispadmin\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /MISP/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3626): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3653): Model->setSource('logs')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1387): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(267): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(User), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('User', Array)
#10 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#11 [internal function]: AppModel->__construct(Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#13 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(263): ClassRegistry::init('User')
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup(Object(Event), Array)
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('SysLogLogable.S...', Array)
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(774): BehaviorCollection->init('Event', Array)
#17 /var/www/MISP/app/Model/AppModel.php(44): Model->__construct(Array, NULL, NULL)
#18 /var/www/MISP/app/Model/Event.php(259): AppModel->__construct(Array, NULL, NULL)
#19 [internal function]: Event->__construct(Array)
#20 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(741): ClassRegistry::init(Array)
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(367): Controller->loadModel('Event')
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(405): Controller->__isset('Event')
#24 /var/www/MISP/app/Controller/AppController.php(82): Controller->__get('Event')
#25 /var/www/MISP/app/Controller/EventsController.php(41): AppController->beforeFilter()
#26 [internal function]: EventsController->beforeFilter(Object(CakeEvent))
#27 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#28 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(676): CakeEventManager->dispatch(Object(CakeEvent))
#29 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#30 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#31 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#32 {main}

**Comment by iglocska** [comment]
You are trying to access http://ip/MISP/app/ - just go to http://ip

**Comment by iglocska** [comment]
Also, from the error messages further down, it looks like your database.php file is not set up correctly (found in /var/www/MISP/app/Config/database.php)

**Comment by honey4free** [comment]
Hmm still cant find the error.
Used the script under to install MISP.
https://github.com/daverstephens/The-SOC-Shop/blob/master/MISP-Stuff/Ubuntu-MISP%20Install%20Script

My databse.php

class DATABASE_CONFIG {

```
    public $default = array(
            'datasource' => 'Database/Mysql',
            'persistent' => false,
            'host' => 'localhost',
            'login' => 'mispadmin',
            'port' => 3306,
            'password' => 'Same as in my installation',
            'database' => 'misp',
            'prefix' => '',
            //'encoding' => 'utf8',
    );
```

---
- MySQLRUser=root
- head -n 1
- fold -w 30
- tr -dc a-zA-Z0-9
- cat /dev/urandom
- MySQLRPass=Masked
- echo MySQL Root User: root with password Masked
  MySQL Root User: root with password Masked
- MySQLUUser=mispadmin
- head -n 1
- fold -w 30
- tr -dc a-zA-Z0-9
- cat /dev/urandom
- MySQLUPass=Masked
- echo MySQL MISP User: mispadmin with password Masked
  MySQL MISP User: mispadmin with password Masked
- MISPDB=misp
- cut -b -32
- md5sum
- date +%N
- Salt=Masked
- Orgname=misp.secumatrix.com
- DB_Port=3306
- AdminEmail=admin@misp.secumatrix.com
- BaseURL=http://192.168.177.200
- GnuPGEmail=admin@misp.secumatrix.com
- GnuPGHomeDir=/var/www/MISP/.gnupg
- GnuPGPassword=Masked

---

After looking over my installation log file it seams that everything is in "order" pw, db, dbname are in order.
Also checked that my db is running.

Maby this is part of the problem or does it matter
BaseURL=http://192.168.177.200

---

I also see that MIPS is not my default root. it is placed under (http://192.168.177.200/MISP/)
I can move it myself but i want to test it before.

Is there maby another installation script that works ?.
Im kind of a lazy guy.

**Comment by iglocska** [comment]
That script is very old and for a different version of MISP. I don't know
of any similar scripts for 2.4, so I'd highly suggest following the
installation instructions for 2.4 located here:
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1404.txt

If MISP is running from http://192.168.177.200/MISP/ then make sure the
baseurl is http://192.168.177.200/MISP

Let me know if that works.

**Comment by iglocska** [comment]
As for the db settings, if you run

mysql -u mispadmin -p misp

and use the password that you've supplied in the database.php file - do you
get an access denied or does it work?

**Comment by iglocska** [comment]
Something that could make it a lot easier is the Travis script that @Rafiot developed: https://github.com/MISP/MISP/blob/2.4/.travis.yml

**Comment by honey4free** [comment]
I reverted the changes and configured the system based on the guide you sent iglocska.
ref: https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1404.txt
Thanks, i'm a little embarrassed i didn't just follow the installation guide to begin with.
But i assumed the script would work.
Im currently writing a new script based on the original installation guide for 2.4 Ubuntu 14.04 and will post it here when it is done. :)
Thanks for fast and awesome support.
Have have an amazing weekend with a lot of fun.
Her in Norway it is snowing and about -20c so i have to shoveling snow...

**Comment by iglocska** [comment]
Glad it worked and looking forward to the script! 

-20c, wow, where abouts? Makes Oslo look warm in comparison... :)

**Comment by honey4free** [comment]
Grimstad,
Just checked the temperature again now.
and I seem to have misinformed, it is now only -7C.
Temprature goes up and down all the time, tonight was the -20 at its worst if I should believe thermometers
Is not so bad anymore.
But I must still out shoveling snow.
You are from Oslo yes.
Cool, but you work with circl from Norway?
Thought it was placed in Luxumburg

**Comment by iglocska** [comment]
It is indeed, I work remotely :)

Yeah it's been crazy cold lately!

**Comment by honey4free** [comment]
<img width="960" alt="misp" src="https://cloud.githubusercontent.com/assets/16814715/12514909/0cd19a40-c126-11e5-8c09-e0ef0ddbdf3b.png">
[MISP_error.txt](https://github.com/MISP/MISP/files/101007/MISP_error.txt)

**Comment by honey4free** [comment]
Just logged on and found another problem
[php.ini.txt](https://github.com/MISP/MISP/files/101014/php.ini.txt)

**Comment by honey4free** [comment]
Maybe you have seen this problem before ?

**Comment by iglocska** [comment]
Can you check what the error message is? You can see it in /var/www/MISP/app/tmp/logs/error.log

**Comment by honey4free** [comment]
I found the first problem.
I forgot to install redis-server silly me

**Comment by honey4free** [comment]
Sweet it looks like everything works now.
I just have to import my pgp key(s) and setup ssl and im good to go i think :).

**Comment by iglocska** [comment]
Excellent, let me know if anything goes south!

**Comment by honey4free** [comment]
Hi again.
Can MISP do some automagic to create suricata rules form events?.
And how do i connect my mist instance to the world.
I want some public data to play with in my lab to see if this is something for us.

**Comment by iglocska** [comment]
Yeah, you can either download the suricata rules of a single published event (download as on the left), get the full rule set of all the events on the instance (via the export page) or use the API to download all or a subset of the rules based on search parameters. You can read more about that on the automation page.

**Comment by iglocska** [comment]
As for connecting it to the world: There is no central MISP repository or anything like that, there are however MISP sharing communities out there where organisations interconnect their MISPs and exchange data.

For example, CIRCL runs a MISP community for the private sector, I don't know what organisation you're working for, but have a read through this and get in touch via the e-mail address provided there: https://www.circl.lu/services/misp-malware-information-sharing-platform/

**Comment by adulau** [comment]
@honey4free Can we close this issue? Thank you.

**Comment by honey4free** [comment]
Close IT :)

Mvh
Kim Eigil Wiig Ytredal
Sykehuspartner
