### ISSUE TITLE
Support:  INSTALL.sh fails checksum on Ubuntu  22.04.1 LTS

### ISSUE THREAD

**Issue by mekhaleraj** [MISP/MISP#8703]
### Support Questions

INSTALL.sh fails checksum on Ubuntu  22.04.1 LTS. What would be the alternative option to update the installer?

### MISP version

2.4.158

### Operating System

Ubuntu 

### Operating System version

22.04

### PHP version

7.4

### Relevant log output

```shell
sudo bash /tmp/INSTALL.sh 
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 22.04
Next step: Checking if we are uptodate and checksums match
sha1:  does not match the installer sum of: 4296d40b11b3002df3fdfd69a508ed5ecacb8c13
Delete installer, re-download and please run again.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mekhaleraj** [comment]
$ sha1sum /tmp/INSTALL.sh
4296d40b11b3002df3fdfd69a508ed5ecacb8c13  /tmp/INSTALL.sh
:~$ sudo bash /tmp/INSTALL.sh
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 22.04
Next step: Checking if we are uptodate and checksums match
sha1:  does not match the installer sum of: 4296d40b11b3002df3fdfd69a508ed5ecacb8c13
Delete installer, re-download and please run again.

**Comment by h4m5t** [comment]
> $ sha1sum /tmp/INSTALL.sh 4296d40b11b3002df3fdfd69a508ed5ecacb8c13 /tmp/INSTALL.sh :~$ sudo bash /tmp/INSTALL.sh Next step: Checking if we are run as the installer template Next step: Checking Linux distribution and flavour... Next step: We detected the following Linux flavour: Ubuntu 22.04 Next step: Checking if we are uptodate and checksums match sha1: does not match the installer sum of: 4296d40b11b3002df3fdfd69a508ed5ecacb8c13 Delete installer, re-download and please run again.

How did you solve the problem？

**Comment by mekhaleraj** [comment]
Redownloaded the application.
