### ISSUE TITLE
Support: Failed at step EXEC spawning /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s: No such file or directory

### ISSUE THREAD

**Issue by JERAR1337** [MISP/MISP#8725]
### Support Questions

Hi,

I have a freshly installed CentOS (up-to-date) environment where I installed MISP core, and this works perfectly. But when I install the extra MISP Modules I get the following error.

_Failed at step EXEC spawning /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s: No such file or directory_

The directory does exist as you can see here.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/9665235/198978451-941e3ca8-cd72-48c9-a6df-56b324100b95.png">

I disabled SElinux just to make sure, but this did not change anything. Did anyone here experience this issue? Or do you know how to fix this?

### MISP version

2.4.164

### Operating System

CentOS

### Operating System version

7.9.2009

### PHP version

7.4.32

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Sounds strange. Did you try to run `misp-modules` alone just to see what's the execution output is especially inside the venv and outside? To see if it's not installation outside the venv.

**Comment by JERAR1337** [comment]
I forgot to close this issue. Closed now.
