### ISSUE TITLE
Bug: Related Events column lists invalid Events 

### ISSUE THREAD

**Issue by KreshnikArapi** [MISP/MISP#8738]
### Expected behavior

When searching for attributes the results under the "Related Events" column should be a list of related events that contain that attribute. 

### Actual behavior

When searching for attributes the results under the "Related Events" column are a list of invalid events. When clicking the event links listed under the "Related Events" column the following error is received.

_Invalid event
Error: The requested address '/events/view/148356' was not found on this server._

### Steps to reproduce

Search for an attribute that is present on several events and click the links under the "Related Events" column.

### Version

2.4.164

### Operating System

Ubuntu

### Operating System version

18.04.6

### PHP version

7.4.32

### Browser

Chrome

### Browser version

107.0.5304.88

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KreshnikArapi** [comment]
![Screenshot 2022-11-07 171127](https://user-images.githubusercontent.com/3027316/200359527-db5e3227-9649-46dd-8d36-450635689d01.png)

**Comment by packet-rat** [comment]
We're seeing this issue as well on 2.4.164.  This is a non-trivial issue for us.

**Comment by packet-rat** [comment]
![image](https://user-images.githubusercontent.com/3220193/205454671-a629fcc9-cbc9-42fc-ad1a-6e3233b39633.png)

![image](https://user-images.githubusercontent.com/3220193/205454693-fadae67c-4334-46be-9a84-4bd9be205666.png)

![2022-12-02_16-04-18](https://user-images.githubusercontent.com/3220193/205454718-036ab8b6-3751-4417-aebd-6fd889271805.png)

**Comment by github-germ** [comment]
Seeing same issue in 2.4.166
Apparently, the IDs displayed under `Related Events` are the matching `attribute_id` in the related event when it used to be and should be the `event_id`.

**Comment by packet-rat** [comment]
This remains an active problem for us - any estimate on which release will address this bug?

**Comment by github-germ** [comment]
Ouch... This was NOT fixed in 2.4.167 !!

**Comment by github-germ** [comment]
This is creating rather big impact to our use cases. Any possibility this can be fixed in 2.4.168? Thanks!!

**Comment by packet-rat** [comment]
Hey folks - This is still broken and causing frequent impacts to our users/processes:

![image](https://user-images.githubusercontent.com/3220193/216117525-aa0031d2-41f7-4095-828f-97b80f9b8afb.png)

**Comment by github-germ** [comment]
Issue persists in 2.4.168

**Comment by iglocska** [comment]
It's fixed on develop, should be in the next release.

**Comment by github-germ** [comment]
Thanks!

**Comment by github-germ** [comment]
Looks like this was fixed in #8930

**Comment by github-germ** [comment]
Thx. Fixed in 2.4.169.

**Comment by iglocska** [comment]
Great, thanks for the feedback!
