### ISSUE TITLE
Support: Connection timed out, Internal server error, MISP Azure AD Authentication

### ISSUE THREAD

**Issue by mekhaleraj** [MISP/MISP#8741]
### Support Questions

Hi

I'm currently having some issue's getting the Azure AD authentication plugin to work properly.

MISP is running behind the proxy. Proxy connection tested OK.

I implemented the following guide: https://github.com/MISP/MISP/tree/2.4/app/Plugin/AadAuth
I created users with the same username as their upn in Azure AD.
They are created as a regular User.
I have set no password when creating the MISP user.

I have added the user to the  group in Azure AD. (The group that is also configured in the config file in MISP)

My Observed Behaviour:
When I use the "login with azure AD" the authentication flows start.
I'm forwarded the tenant Azure Ad sign-in experience
On completion, I'm being forwarded to the sign-in page of the MISP instance with a token in the URL bar.
But I'm not signed in and  redirects back to MISP with error **"Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator."**

I have also included some error logs from the MISP instance.

No white spaces in the config file. Tried disabling group lookup, same error.

### MISP version

2.4.164

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox and Chrome

### Relevant log output

```shell
error.log
Error: [SocketException] Connection timed out
Request URL: /users/login?code=DELETED&state=DELETED&session_state=DELETED
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
https://github.com/MISP/MISP/issues/1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
https://github.com/MISP/MISP/issues/2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request()
https://github.com/MISP/MISP/issues/3 /var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php(217): HttpSocket->post()
https://github.com/MISP/MISP/issues/4 /var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php(158): AadAuthenticateAuthenticate->_getUserAad()
https://github.com/MISP/MISP/issues/5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(698): AadAuthenticateAuthenticate->getUser()
https://github.com/MISP/MISP/issues/6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
https://github.com/MISP/MISP/issues/7 /var/www/MISP/app/Controller/AppController.php(1147): AuthComponent->startup()
https://github.com/MISP/MISP/issues/8 /var/www/MISP/app/Controller/AppController.php(226): AppController->_loadAuthenticationPlugins()
https://github.com/MISP/MISP/issues/9 /var/www/MISP/app/Controller/UsersController.php(31): AppController->beforeFilter()
https://github.com/MISP/MISP/issues/10 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
https://github.com/MISP/MISP/issues/11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
https://github.com/MISP/MISP/issues/12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
https://github.com/MISP/MISP/issues/13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
https://github.com/MISP/MISP/issues/14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
https://github.com/MISP/MISP/issues/15 {main}
Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode()
https://github.com/MISP/MISP/issues/1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400()
https://github.com/MISP/MISP/issues/2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
https://github.com/MISP/MISP/issues/3 [internal function]: ErrorHandler::handleException()
https://github.com/MISP/MISP/issues/4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
https://github.com/MISP/MISP/issues/1 [internal function]: ErrorHandler::handleError()
https://github.com/MISP/MISP/issues/2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error()
https://github.com/MISP/MISP/issues/3 [internal function]: ErrorHandler::handleException()
```

### Extra attachments

<img width="685" alt="Screenshot 2022-11-07 at 15 26 55" src="https://user-images.githubusercontent.com/3139317/200334577-30cbab86-6dda-46cb-95c5-64ffc3dfe8c4.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mekhaleraj** [comment]
**error.log**
 Error: [SocketException] Connection timed out
Request URL: /users/login?code=DELETED&state=DELETED&session_state=DELETED
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request()
#3 /var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php(217): HttpSocket->post()
#4 /var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php(158): AadAuthenticateAuthenticate->_getUserAad()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(698): AadAuthenticateAuthenticate->getUser()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#7 /var/www/MISP/app/Controller/AppController.php(1147): AuthComponent->startup()
#8 /var/www/MISP/app/Controller/AppController.php(226): AppController->_loadAuthenticationPlugins()
#9 /var/www/MISP/app/Controller/UsersController.php(31): AppController->beforeFilter()
#10 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): UsersController->beforeFilter()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#14 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#15 {main}
 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException()
#4 {main} in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 138]
 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError()
#1 [internal function]: ErrorHandler::handleError()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error()
#3 [internal function]: ErrorHandler::handleException()

**Comment by deepamshah** [comment]
Hi. Not sure if its the same issue or not however our issue with MISP and AAD auth was resolved by adding the GROUPMEMBER.READ.ALL permissions in our environment. Our issue was similar where the AAD plugin was configured exactly as described however after authenticating the user, the request was redirected back to login page, with a login code and etc details returned.

I modified the application code to spit out entire "auth request" with all the claims back to MISP and found that the group information wasnt being returned back to MISP after the auth request. After some digging around, found that the following link mentions that for Graph to return "memberOf" - the required permissions are GROUPMEMBER.READ.ALL (there's others too listed - eg. DIRECTORY.READ.ALL which could also produce the same result) https://learn.microsoft.com/en-gb/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http . 

Our issue was fixed as soon as we added the delegated permission - GROUPMEMBER.READ.ALL.

**Comment by mekhaleraj** [comment]
Enabled additional permissions too but same error. Is your instance is also running behind the proxy?

Any additional changes required in case of proxy?

Thanks

**Comment by righel** [comment]
Hello @mekhaleraj , currently the AadAuth plugin does not take into account the MISP proxy settings, I created this PR: https://github.com/MISP/MISP/pull/8762 to address this.

Feel free to test it out, I will do so but need some time to set the test env.

**Comment by mekhaleraj** [comment]
@righel 

I've implemented a workaround in the same file and I'm able to login now.

issue is $proxy array is empty. I'm looking for the cause of this. Will keep you posted.

**Comment by righel** [comment]
ugh, missed one line, sorry about that. updated the PR, could you check again?

**Comment by mekhaleraj** [comment]
I just added the same line to fetch proxy config.

Working fine. Thanks. Issue can be closed now.
