### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by SurajPatel06** [MISP/MISP#8742]
### Support Questions

Unable to acess MISP Feeds using the command feeds=misp.feeds(),
The error message which occurs when this command is executed is:
 {'errors': (405, {'name': 'You do not have permission to use this functionality.', 'message': 'You do not have permission to use this functionality.', 'url': '/feeds/index'})} Can anyone please guide me to fix this.
Unable to fix it even after trying to acess it with a Sync user

### MISP version

2.4.163

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.0

### Relevant log output

```shell
{'errors': (405, {'name': 'You do not have permission to use this functionality.', 'message': 'You do not have permission to use this functionality.', 'url': '/feeds/index'})} Can anyone please guide me to fix this.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @SurajPatel06 
Sync users do not have permission to list feeds, try with a user with User, Org Admin or Site Admin roles.

Hope this helps.

**Comment by SurajPatel06** [comment]
Hello @righel I followed your advise and tried to access the feeds with User and Org Admin roles but I am still receiving the same error as before: 
 {'errors':(403, 
{'name': 'You are not authorised to do that.',
'url':
'/events/edit/a6c2dc2b-4daf-a20c-b89a7cb379bd'}}}}

**Comment by SurajPatel06** [comment]
It would be of great help if you could help me resolve this @righel

**Comment by righel** [comment]
The error message you pasted shows an attempt to edit a event. Can you share the code you are trying to execute?

**Comment by SurajPatel06** [comment]
The right error message was 
{'errors':(405,
{'name': 'You do not have permission to use this functionality.',
'message': 'You do not have permission to use this functionality.',
'url':'/feeds/edit/1'})}

I am able to acess the feeds but not able to update them, the script I am using is:
x=misp.feeds()
misp.update_feed(x[0])

I am using this code along with the authorisation keys of users with "user" and "org admins" as roles.

**Comment by righel** [comment]
Only Site Admins can create, enable, disable, update, cache or delete feeds

**Comment by SurajPatel06** [comment]
@righel will the credentials of the admin account have acess to update feeds?
