### ISSUE TITLE
upgrade to 2.4 is not present in Administrative Tools

### ISSUE THREAD

**Issue by Deventual** [MISP/MISP#876]
After making all the procedures in the upgrade from 2.3 to 2.4 guide,
I enter to Administration -> Administrative Tools and the link for upgrade to 2.4 is not present.

**Comment by iglocska** [comment]
That is weird, it should be there at the bottom. Could you post a screenshot of the administrative tools view? 

Also, can you check what version you are on? (Should be in the footer, or alternatively administrationg->server settings -> diagnostics).

**Comment by Deventual** [comment]
![screenshot from 2016-01-24 15 33 41](https://cloud.githubusercontent.com/assets/7035285/12536498/f25b41ee-c2af-11e5-9ba2-645f7544f66b.png)
My MISP version is 2.3

**Comment by Deventual** [comment]
My MISP version is 2.3.0
![screenshot from 2016-01-24 15 33 41](https://cloud.githubusercontent.com/assets/7035285/12536515/5bcbabd2-c2b0-11e5-9d7d-95a66220ff6c.png)

**Comment by Deventual** [comment]
My MISP version is 2.3.63
![screenshot from 2016-01-24 15 33 41](https://cloud.githubusercontent.com/assets/7035285/12536522/8c818abc-c2b0-11e5-9fbb-a5fdc9cbe63c.png)

**Comment by iglocska** [comment]
You are on a very outdated version of MISP and need to upgrade it first.

Simply git pull to get to the latest version of the 2.3 branch 

cd /var/www/MISP
git pull

then switch to the 2.4 branch
git checkout 2.4

After that you need to follow the upgrade procedure in the UPGRADE.txt file. 

You can find that file online here too: 

https://github.com/MISP/MISP/blob/2.4/INSTALL/UPGRADE.txt

**Comment by Deventual** [comment]
OK, 
I will follow your instructions.

Thanks a lot!!

**Comment by iglocska** [comment]
No worries, let me know if you run into any trouble!

**Comment by Deventual** [comment]
Hi there,

I followed your instructions, actually i did the full guide for update,
and right after it i did the upgrade guide and still i have same issue that the upgrade to 2.4 is missing from the Administrative Tools.
The weird thing that the version stayed the same at the diagnose page.

Also the VERSION.json stated {"major":2, "minor":4, "hotfix":12}

**Comment by Rafiot** [comment]
@Deventual Did you manage to get 2.4 to work?

**Comment by Deventual** [comment]
yes

**Comment by csirt-rymtech** [comment]
We have the same problem here. We are trying to upgrade 2.4 to 2.5 with all requirements satisfied, but we haven't the Administrative Tool Menu. Upgrading from CLI reported some minor warnings related to the rewrite /varwwwMISP/app/index.php file.
