### ISSUE TITLE
Bug: The /galaxies/attachCluster API call does not work

### ISSUE THREAD

**Issue by eric-ooi** [MISP/MISP#8764]
### Expected behavior

When executing a call successfully, it should return:

`{
  "saved": true,
  "success": "Cluster attached.",
  "check_publish": true
}`

### Actual behavior

Instead, the JSON response is:

`{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/galaxies\/attachCluster\/95644\/event\/local:0"}`

### Steps to reproduce

Tried executing a POST to /galaxies/attachCluster/95644/event/local:0 using the built in web-based MISP REST client.  I did notice that when trying to add a Galaxy cluster via the web interface, it appeared that MISP instead uses /galaxies/attachMultipleClusters.  I tried this as well but there is no JSON response to confirm success or failure. 

### Version

2.4.165 (a0d3e1dd096c2f6338a3e1e6961e83228252eafd)

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by junior-skater** [comment]
i have the same error and sometimes the response is success but when i check the event the cluster is not attached

**Comment by JakubOnderka** [comment]
Can you please check error and debug logs located in `app/tmp/logs` folder?

**Comment by eric-ooi** [comment]
I see this in error.log:

```
2022-11-28 10:39:25 Error: [TypeError] Argument 3 passed to Galaxy::attachCluster() must be of the type array, string given, called in /var/www/MISP/app/Controller/GalaxiesController.php on line 528
Request URL: /galaxies/attachCluster/95644/event/local:0
Stack Trace:
#0 /var/www/MISP/app/Controller/GalaxiesController.php(528): Galaxy->attachCluster()
#1 [internal function]: GalaxiesController->attachCluster()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#5 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#6 {main}
```

I had previously used something like this in the HTTP Body to attach a galaxy:

```
{
    "Galaxy" : {
        "target_id": 18454
    }
}
```

Based on that error I tried doing this, but still get the same message:

```
{
    "Galaxy" : {
        "target_id": [18454]
    }
}
```

**Comment by eric-ooi** [comment]
Confirmed working again in 2.4.167 (b8463ebbbf47b49d9bd1da145725d68852c308b9) Thanks for the quick turnaround!
