### ISSUE TITLE
Support: INSTALL.sh fails checksum on Ubuntu 22.04

### ISSUE THREAD

**Issue by h4m5t** [MISP/MISP#8766]
### Support Questions

INSTALL.sh fails checksum on Ubuntu 22.04，How to solve this problem？

### MISP version

2.4.164

### Operating System

Ubuntu

### Operating System version

Ubuntu 22.04

### PHP version

7.4

### Relevant log output

```shell
Next step: Checking if we are run as the installer template
Next step: Checking Linux distribution and flavour...
Next step: We detected the following Linux flavour: Ubuntu 22.04
Next step: Checking if we are uptodate and checksums match
sha1:  does not match the installer sum of: 4296d40b11b3002df3fdfd69a508ed5ecacb8c13
Delete installer, re-download and please run again.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by toolost9** [comment]
Hello, Delete installer, re-download and please run again.

**Comment by h4m5t** [comment]
I didn't re-download,but run INSTALL.sh many times, Now it's OK!amazing...
