### ISSUE TITLE
Support: CSP Blocking requests originated from App Gateway

### ISSUE THREAD

**Issue by mekhaleraj** [MISP/MISP#8768]
### Support Questions
<img width="359" alt="image" src="https://user-images.githubusercontent.com/3139317/203062741-1397728e-0fd3-439b-bd60-e3e3a98727e4.png">

CSP Blocking requests originated from App Gateway.

I've App Gateway in front of MISP instance in Azure.

baseurl = https://misp.internal
external_baseurl = https://misp.external

While trying to access misp.external CSP blocking some requests (Not All) and redirecting to misp.internal
See attached screenshot. All CSP blocked requests were redirected to internal url
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3139317/203061897-632638ba-c958-42da-9669-cbeead0965f8.png">

### MISP version

2.4.164

### Operating System

Ubuntu 

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox and Chrome

### Relevant log output

```shell
2022-11-21 10:38:32 Error: CSP reported violation from IP X.X.X.X: {
"document-uri": "https://misp.external/users/login",
"referrer": "",
"violated-directive": "script-src-elem",
"effective-directive": "script-src-elem",
"original-policy": "default-src 'self' data: 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'none'; worker-src 'none'; child-src 'none'; frame-src 'none'; base-uri 'self'; img-src 'self' data:; font-src 'self'; form-action 'self'; connect-src 'self'; manifest-src 'none'; report-uri /servers/cspReport; upgrade-insecure-requests",
"disposition": "report",
"blocked-uri": "https://misp.internal/js/keyboard-shortcuts.js",
"status-code": 200,
"script-sample": ""
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WinterIsCommin** [comment]
Any updates?

**Comment by mekhaleraj** [comment]
After setting relevant headers issue is resolved. e.g X_Forwarded_for
