### ISSUE TITLE
Blackhole and/or CSRF exception

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#877]
I'm trying to add some attributes to an event (Category: Network Activity, Type: URL) with the following contents:

http://gammus.com/73.exe?1  
http://actuvillage.com/images/thumbs/73.exe  
http://betterhealth4us.com/wp-includes/fonts/73.exe?1  
http://74.117.183.84/73.exe?1  
http://baneyconstruction.com/kldf/cachec50da2243ebb9d634cfad3427cafcc61/73.exe?1  
http://bfcaterers.com/wp-includes/certificates/73.exe?1  
http://5.39.222.196/73.exe?1  
http://bellychef.com/wp-includes/theme-compat/73.exe?1  
http://bereanbibledenver.com/wp-admin/js/73.exe?1  
http://bauelementeberater.info/73.exe  
http://autocraftmedia.com/mappalachian/tmp/73.exe?1

In contextual comment I entered: "TeslaCrypt gets downloaded from these URLs"

The boxes "for IDS" and "Batch import" are ticked and upon clicking on "Submit", it just hangs.

In my error.log I see the following:

2016-01-25 14:03:38 Error: [BadRequestException] csrf
Request URL: /attributes/add/2021
Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(242): SecurityComponent->blackHole(Object(AttributesController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}

**Comment by cvandeplas** [comment]
MISP has CSRF - Cross Site Request Forgery - tokens for security.
So when you go on the "add new attribute" page, and wait for too long the tokens expire and you will trigger the CSRF protection.

On a MISP installation with no debug enabled you will see a clear error message explaining what happened (and why), telling the user to try again without waiting for so long.

**Comment by h122015** [comment]
But I'm not waiting for too long, I just logged in and started adding attributes right away. Normally if I wait too long or something I receive a clear error message explaining what happened, but in this case I'm not getting anything.
If I click on other parts of MISP, I get to the desired functionality. If my sessions somehow expired, I would see this message.

**Comment by h122015** [comment]
I just deleted the event, logged out and in again, started creating the events and its attributes and I got the same at a later point

**Comment by iglocska** [comment]
Hmm just tried to add the same attributes with the same settings and it went fine, I'll try a few more things

**Comment by iglocska** [comment]
What I tried: 

Chrome, as admin user create event -> add attribute, paste the list of values, tick to IDS, tick batch import -> submit

Worked fine

in Firefox, as a regular user, repeated the same steps, works fine. 

What browser / version are you using?

**Comment by h122015** [comment]
I'm trying to add the following attributes and I have already the information ready, so filling up the attributes shouldn't take long:

1.- Category: Payload delivery, Type: malware-sample 
2.- Category: Payload delivery, Type: filename|md5
3.- Category: Network activity, Type: url
4.- Category: Artifacts dropped, Type: malware-sample
5.- Category: Artifacts dropped, Type: filename|md5
6.- Category: Payload installation, Type: filename|md5
7.- Category: Targeting data, Type: Comment
8.- Category: Artifacts dropped, Type: filename
9.- Category: Network activity, Type: url
10.- Category: Persistence mechanism, Type: comment
11.- Category: Other, Type: comment
12.- Category: Antivirus detection, Type: Link

Right now it hung at 5. I'm using IE11

**Comment by h122015** [comment]
I was able to enter all the attributes using FF.

**Comment by iglocska** [comment]
Hmm, just tried it with IE11 and it worked fine... Not sure how to reproduce it...

**Comment by iglocska** [comment]
Could you try clearing the cookies on IE11 if it keeps happening to see if it resolves it?

**Comment by Rafiot** [comment]
@h122015 any news?

**Comment by h122015** [comment]
It still happens even after clearing cookies. My work around is to use FF

**Comment by Rafiot** [comment]
Ok, I'll close then, and don't hesitate to reopen if needed.
