### ISSUE TITLE
Don't display options to users for which they don't have the rights to use

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#880]
This is merely a suggestion. I've logged in to misp-priv as a regular user and I was looking at the templates (Event actions -> List templates) and I've noticed that next to the template there are icons for editing the template and delete it. If I click on those icons I get the following message:

No template with the provided ID exists, or you are not authorised to edit it.
Error: The requested address '/templates/edit/4' was not found on this server.

Which is OK since I don't have the "Template editor" permission. 

Wouldn't be better to show those icons only to the users that have the "Template editor" permission?

**Comment by iglocska** [comment]
Definitely, that's a bug! Will fix it asap.
