### ISSUE TITLE
Bug: Remote MISP connection test return notice error if server is down after UPDATE to 2.4.166

### ISSUE THREAD

**Issue by shaworee** [MISP/MISP#8819]
### Expected behavior

While testing remote MISP connection test via console:
/var/www/MISP/app/Console/cake Server test 2

I am expecting returned json with status code without procedural error.

### Actual behavior

**AFTER UPDATE to 2.4.166**
While testing remote MISP connection test via console:
/var/www/MISP/app/Console/cake Server test 2

MISP returns json but also an ERROR **if remote MISP is down**:
Notice Error: Undefined index: REMOTE_ADDR in [/var/www/MISP/app/Model/AppModel.php, line 3916]

### Steps to reproduce

Run connection test with command:
/var/www/MISP/app/Console/cake Server test IDofRemoteMISP

### Version

2.4.166

### Operating System

Ubuntu

### Operating System version

18.04 and 20.04 and 22.04

### PHP version

7.4

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @shaworee 
This was already fixed via https://github.com/MISP/MISP/commit/097275ec9660205a7f40342dcac08883bcb5d13e
Please update to the latest version `2.4.167`

**Comment by shaworee** [comment]
Everything is fine after update. Thank you.
