### ISSUE TITLE
Make sync between v2.3 and v2.4 fail explicitly and loudly

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#882]
It seems that when I try to sync a v2.3 & a v2.4, it just fails silently.
Could it be possible to add in the logs some warning message in what is logged for "pull" messages so that it is clear it is not working and is not going to work.

The idea is to do it on both v2.4 and v2.3 code bases so that both sides can diagnose this.

**Comment by iglocska** [comment]
Is 2.4 pulling from 2.3 failing too?

**Comment by elhoim** [comment]
The other way, v2.3.175 pulling from a v2.4.12

**Comment by Rafiot** [comment]
Should we consider it as fixed?

**Comment by Rafiot** [comment]
Assuming nobody has 2.3 by now.
