### ISSUE TITLE
Support: Performance Issues - Attributes takes minutes to load/ API timeouts

### ISSUE THREAD

**Issue by bizzarecontacts** [MISP/MISP#8823]
### Support Questions

We've been facing a big issue with our misp instance where loading (GUI) the attribute page takes lots of minutes, likewise our API requests simply faid away persumably because of that. 
I've read earlier articles way back in 2019 etc of similiar issues, apparently due to events having 100k+ attributes, this is more or less what also seems to be our issue.

Im currently using a script to wipe clean all events in the hopes that we can get a fresh start instead of re-installing misp ( which is abit of a hassle since its a AWS instance ) which takes a long time as i suppose the mariadb can't handle so many deletions at once.

Our specs are unlimited but are currently : 8GB RAM, 4vCpus, 512SSD
Is there a way to avoid this in the future, as well as tweaks that can be done to improve the performance? We intend to push the instance intro prod at some point and send the attributes to our SIEM, as well as the intention to have more then two feeds enabled at all times.

### MISP version

Latest

### Operating System

Ubuntu

### Operating System version

Latest

### PHP version

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by goodlandsecurity** [comment]
have you tried increasing the memory limit and/or max execution time on the user role performing the searches within MISP to see if that helps? (located here: https://MISP/roles/index)

**Comment by bizzarecontacts** [comment]
Thank's, tried that - didn't help.
Turns out the issue was that deleting events did not delete it's references in the DB, i noticed this when i checked the attribute table, as well as the objects table and realized they were still populated by old events, i waited aprox 30 minutes for the attribute page in the UI to load and confirmed it as well.
truncating those tables immediatly fixed the issue. I think there are two take aways

1. need to improve the db performance
2. Increase mem limit both to php and in mariadb inodb as well ( just incase )
3. dont add feeds that bring 100k attributes per event like abuse.ch, it seems that it just can't handle it ?
