### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#8827]
### Support Questions

I enabled the misp-modules from the directions here with no errors, https://github.com/MISP/misp-modules. However, I'm not sure if I it's working correctly?? 
curl doesn't come back with anything, but it appears to be running - 
![image](https://user-images.githubusercontent.com/5932961/209012857-b6c08c8a-92e3-48ad-bfdc-5d11ece4bb1a.png)

If I go into the plugins and enable a few to test, they appear to come back with information, at least a few do. If I try the 'Enrich Event' with Virustotal it seems to work great! 

Is there reason I should be worried about the curl test not working? 
 
Thanks!

### MISP version

2.4.166

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox

### Browser version

108.0.1 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Can you share the detail about the `curl` command run?

**Comment by mathurin68** [comment]
Hey @adulau 
Thanks for the response! 
This is it, it just sits there...and then comes back with nothing. 
![image](https://user-images.githubusercontent.com/5932961/209163226-6bb60553-d086-497f-ac14-1c28e062170c.png)

...everything else seems to be working?  I haven't gotten results back for a few of them, but I've only been playing with it for a couple days.

**Comment by mathurin68** [comment]
Got it... I swear I thought I added our proxy cert to everything but apparently not.  I added it to here and it seems to work great. 
```
 vim /var/www/MISP/venv/lib/python3.8/site-packages/certifi/cacert.pem
```
