### ISSUE TITLE
Feature Request: Workflows action to enrich matched attrbuite and not the whole event

### ISSUE THREAD

**Issue by m5050** [MISP/MISP#8833]
### Is your feature request related to a problem? Please describe.

Workflows action "Enrich Event" is enriching every attribute in the event. When this action is combined with a high overhead trigger (Attribute After Save as an example) the whole event enriching process is a time and resource consuming repetitive task.

### Describe the solution you'd like

Having a Workflows action to enrich attribute similarly to the action "Enrich Event", but specified only to the matched attribute to be enriched and not the whole event.

### Describe alternatives you've considered

using the workflow action "Enrich Event" to enrich all attributes contained in event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Hey,
Actually you can already do it using the "module filtering feature".
By configuring a workflow like this, I'm able to only perform the `dns` enrichment on Attribute tagged with `tlp:white`.
![image](https://user-images.githubusercontent.com/6977223/228799475-fdc3c5c4-2d9a-4de8-a4a5-94639d4041d2.png)
![image](https://user-images.githubusercontent.com/6977223/228799549-c58a4a2b-480b-45a4-9db2-9f11a8837ac3.png)

Adding a filter on a node will only execute the module on the data matched by the provided rules. Please note that currently:
- You can only add one filtering condition per node
- The data being passed from module is not changed. The filters are only there to choose on which portion of the data you want the module to be applied to.

This behavior might changed in the future.

Side note: I noticed a bug when tying to the example above. Fixed it in 7ab9eab622e8dec7f35ec26bf65d7af0b600992d
