### ISSUE TITLE
Support: Background Job Error Browser

### ISSUE THREAD

**Issue by 00gxd14g** [MISP/MISP#8836]
### Support Questions

Error: Notice Error: Undefined index: REMOTE_ADDR in [/var/www/MISP/app/Model/AppModel.php, line 3916]
Notice Error: Undefined index: REMOTE_ADDR in [/var/www/MISP/app/Model/AppModel.php, line 3916]

Notice Error: Undefined index: REMOTE_ADDR in [/var/www/MISP/app/Model/AppModel.php, line 3916]

Error: Connection refused
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request()
#3 /var/www/MISP/app/Model/Workflow.php(1423): HttpSocket->post()
#4 /var/www/MISP/app/Model/Workflow.php(529): Workflow->sendRequestToDebugEndpoint()
#5 /var/www/MISP/app/Model/Workflow.php(504): Workflow->__runWorkflow()
#6 /var/www/MISP/app/Model/Workflow.php(471): Workflow->executeWorkflowForTrigger()
#7 /var/www/MISP/app/Model/AppModel.php(3770): Workflow->executeWorkflowForTriggerRouter()
#8 /var/www/MISP/app/Model/Event.php(4607): AppModel->executeTrigger()
#9 /var/www/MISP/app/Console/Command/EventShell.php(410): Event->publish()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->publish()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#13 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#14 {main}

### MISP version

 v2.4.167

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4.3

### Browser

Chrome

### Relevant log output

```shell
Error: Connection refused
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(510): HttpSocket->request()
#3 /var/www/MISP/app/Model/Workflow.php(1423): HttpSocket->post()
#4 /var/www/MISP/app/Model/Workflow.php(529): Workflow->sendRequestToDebugEndpoint()
#5 /var/www/MISP/app/Model/Workflow.php(504): Workflow->__runWorkflow()
#6 /var/www/MISP/app/Model/Workflow.php(471): Workflow->executeWorkflowForTrigger()
#7 /var/www/MISP/app/Model/AppModel.php(3770): Workflow->executeWorkflowForTriggerRouter()
#8 /var/www/MISP/app/Model/Event.php(4607): AppModel->executeTrigger()
#9 /var/www/MISP/app/Console/Command/EventShell.php(410): Event->publish()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): EventShell->publish()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#13 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#14 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hi @00gxd14g 
Could you update your MISP instance and try again? 
This error was already fixed via https://github.com/MISP/MISP/commit/097275ec9660205a7f40342dcac08883bcb5d13e
