### ISSUE TITLE
Support: Request for misp integration with a sislog, or send events to a specific port

### ISSUE THREAD

**Issue by fernandourbano123** [MISP/MISP#8838]
### Support Questions

For some time I have been trying to do some kind of sending events automatically or manually to a specific port to some other machine but it has not been possible and I would like to know if you could help me, or I would also like to know if it is It is possible to integrate it with some syslog so that it receives the events automatically.
The idea of this integration is that the misp is integrated in this way with the Trelix Helix since it uses a commbroker and it has not been possible.

Thank you

### MISP version

2.4.166

### Operating System

ubuntu

### Operating System version

20.04

### PHP version

7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fernandourbano123** [comment]
I need help please🙏

**Comment by rommelfs** [comment]
I don't think syslog would be an appropriate transport for entire events. 
Wouldn't https://www.circl.lu/doc/misp/misp-zmq/ be working for you?
