### ISSUE TITLE
Available tags and organisations missing when defining pulling rules?

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#884]
I've noticed that in the list of servers (Sync actions -> List servers), if I click on edit and then on "Modify" in "Pull Rules", the column in the middle is empty, that is, not even the titles "Available Tags" or  "Available Organisations" are shown and the input fields are empty. 

If I click on "Modify" in "Push Rules", the titles are shown and the input fields contain the appropriate information.

**Comment by iglocska** [comment]
Indeed, it is a text field where you can type in the names of orgs / tags.
The idea is that the tags / orgs existing on the remote instance will not
correspond to the ones available locally. In the future it would be a cool
idea to improve this and have a lookup service to populate a list similar
to the push.

**Comment by h122015** [comment]
Ah ok, I thought there was a problem because not even the titles are shown. That means, in the tags input field, can I enter something like "tlp:*" and the only those tags will be pulled?

**Comment by iglocska** [comment]
Yup, that's the idea!

**Comment by iglocska** [comment]
Without the \* that is, just write "tlp:" and it should work.

**Comment by elhoim** [comment]
Seems to be answered. Closing.
