### ISSUE TITLE
Bug: restSearch does not take limit into account

### ISSUE THREAD

**Issue by hazcod** [MISP/MISP#8841]
### Expected behavior

When specifying the following payload, which includes `limit`, I get 166184 results from `/attributes/restSearch`.

```json
{
    "returnFormat": "json",
    "timestamp": "2023-01-02",
    "published": 1,
    "page": 0,
    "limit": 100
}
```

### Actual behavior

Get 166184 results instead of 100.

### Steps to reproduce

Send the payload.

### Version

2.4.166

### Operating System

Unsure

### Operating System version

Unsure

### PHP version

Unsure

### Browser

HTTP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @hazcod 
Could you please share the complete http request you are sending to the server?
Check if the `Content-Type: application/json` header is present in the POST request, otherwise it will not take into account the filters in your request payload.

Hope this helps.

**Comment by hazcod** [comment]
Welp, that actually seemed to do the trick. Thank you @righel !
