### ISSUE TITLE
Support: No Enrichment Options In MISP

### ISSUE THREAD

**Issue by MU-03** [MISP/MISP#8847]
### Support Questions

I am very new to MISP and I want to enrich the events. I have attached my Plug-ins-> enrichment section below. I have tried to run misp-modules.service but still nothing is showing, although I can see all the enrichment files in my /usr/local/src/misp-modules/misp-modules  folderand misp-modules.service is in /etc/systemd/system folder of ubutu.
Regards

### MISP version

2.4.165

### Operating System

Ubuntu 

### Operating System version

22.04

### PHP version

7.0

### Browser

FireFox

### Extra attachments

![02](https://user-images.githubusercontent.com/118333194/210755170-c80805e2-03ea-4662-9b96-562946cb6619.PNG)
![01](https://user-images.githubusercontent.com/118333194/210755188-36e2e926-f3b0-437f-8ac3-6c8d3dec251d.PNG)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
@MU-03 you need also to enable each of the module you want, not only the expansion module service. I bet it's that as you don't have any in the list.

**Comment by MU-03** [comment]
How can I enable that , can you please guide me. I did ran the commands you have mentioned:
sudo cp etc/systemd/system/misp-modules.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now misp-modules
sudo service misp-modules start

Regards

**Comment by MU-03** [comment]
> @MU-03 you need also to enable each of the module you want, not only the expansion module service. I bet it's that as you don't have any in the list.

Yeah that was it , I was missing the next step. Thank you so much.
