### ISSUE TITLE
[module] IntelMQ module to send abuse/take-down request via MISP

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#885]
IntelMQ provides a Redis queue service where you can send JSON format messages. The idea is to be able to handle abuse creation to IntelMQ from MISP. The JSON would contain the IP to report (minimal).

**Comment by aaronkaplan** [comment]
For a description of intelmq JSON: https://github.com/certtools/intelmq/blob/master/docs/Data-Harmonization.md and
https://github.com/certtools/intelmq/blob/master/docs/Harmonization-fields.md

**Comment by adulau** [comment]
Maybe a direction integration with AbuseIO should be part of the same module - https://github.com/AbuseIO/AbuseIO/

**Comment by adulau** [comment]
Solved via [misp-takedown](https://github.com/rommelfs/misp-takedown)
