### ISSUE TITLE
Feature Request: Multiple Sentinel integrations from a single MISP

### ISSUE THREAD

**Issue by BillClarksonAntill** [MISP/MISP#8852]
### Is your feature request related to a problem? Please describe.

Just wondering if this is possible and could be a question for the wider community. Is it possible to integration MISP into Multiple Sentinels and how would you go about doing it

Taxii server or could we integrate directly using an app registration?

### Describe the solution you'd like

MISP to multiple MS sentinel integrations

### Describe alternatives you've considered

TAXII Server has been considered, but unsure of how MISP could be configured 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BillClarksonAntill** [comment]
any update on this

**Comment by adulau** [comment]
Concerning Microsoft Azure sentinel integration, you should have a look at this recent post https://www.misp-project.org/2023/04/03/MISP-Sentinel.html/
