### ISSUE TITLE
Bug:  CRITICAL:pymisp:Unknown error: the response is not in JSON. Something is broken server-side, please send us everything that follows (careful with the auth key):

### ISSUE THREAD

**Issue by shahidakhter786** [MISP/MISP#8897]
### Expected behavior

Was working fine couple of days and data was exporting

### Actual behavior

CRITICAL:pymisp:Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.167 - Python 3.10', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=fsgdsgfgfgfdgfgg-randomvalue-', 'Content-Length': '335', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "page": 1, "limit": 50, "withAttachments": 0, "metadata": 0, "timestamp": 1674576553, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0, "excludeDecayed": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
ERROR:root:Error fetching misp event again: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
INFO:root:Connector successfully run (0 events have been processed), storing state (last_run=2023-02-02T12:06:50.958109+00:00, last_event=2023-01-24T16:09:12+00:00, last_event_timestamp=1674576552)
INFO:root:Reporting work update_received work_d8428951-e1db-4904-96b3-c91e96c2f88c_2023-02-02T12:06:50.963Z

### Steps to reproduce

MISP -Opencti connector 

### Version

 MISP 2.4.167

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

PHP 7.4.3 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
Can you check the logs on the MISP server? There should be and exception in the error logs.

**Comment by shahidakhter786** [comment]
where will be these errors logs? i cant see any folder  or file name error.log. I am using docker container and there' s no error in container

**Comment by shahidakhter786** [comment]
oh Okay , Got it , here are some of the logs from error.log.


2023-02-03 10:23:32 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Event.php(7291): Model->save()
#6 /var/www/MISP/app/Model/Event.php(7188): Event->clusterEventIds()
#7 /var/www/MISP/app/Controller/AppController.php(1294): Event->restSearch()
#8 [internal function]: AppController->restSearch()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#13 {main}
2023-02-03 10:24:32 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Event.php(7291): Model->save()
#6 /var/www/MISP/app/Model/Event.php(7188): Event->clusterEventIds()
#7 /var/www/MISP/app/Controller/AppController.php(1294): Event->restSearch()
#8 [internal function]: AppController->restSearch()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#13 {main}
2023-02-03 10:24:32 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
Request URL: /events/restSearch
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/Event.php(7291): Model->save()
#6 /var/www/MISP/app/Model/Event.php(7188): Event->clusterEventIds()
#7 /var/www/MISP/app/Controller/AppController.php(1294): Event->restSearch()
#8 [internal function]: AppController->restSearch()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#12 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()

**Comment by shahidakhter786** [comment]
2023-02-02 07:31:09 Notice: Notice (8): Undefined variable: fieldDesc in [/var/www/MISP/app/View/Attributes/search.ctp, line 25]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Attributes/search.ctp, line 25
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-02-02 07:31:09 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/View/Attributes/search.ctp, line 25]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Attributes/search.ctp, line 25
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-02-02 07:31:09 Notice: Notice (8): Undefined variable: fieldDesc in [/var/www/MISP/app/View/Attributes/search.ctp, line 37]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Attributes/search.ctp, line 37
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-02-02 07:31:09 Notice: Notice (8): Trying to access array offset on value of type null in [/var/www/MISP/app/View/Attributes/search.ctp, line 37]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Attributes/search.ctp, line 37
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-02-02 07:31:09 Notice: Notice (8): Undefined variable: categoryDefinitions in [/var/www/MISP/app/View/Attributes/search.ctp, line 76]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include - APP/View/Attributes/search.ctp, line 76
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

**Comment by shahidakhter786** [comment]
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID:  id here
INFO:root:Starting ping alive thread
INFO:root:Initiate work for id here
INFO:root:Connector last run: 2023-02-03T10:41:38.730521+00:00
INFO:root:Connector latest event: 2023-01-24T16:09:12+00:00
INFO:root:Fetching MISP events with args: {"timestamp": 1674576553, "limit": 50, "page": 1}
INFO:root:MISP returned 16 events.
INFO:root:Processing event id here
INFO:root:Sending event STIX2 bundle
INFO:root:Update action expectations work_id herec_2023-02-03T10:48:02.475Z - 142674
ERROR:root:[SEARCH] Error updating elastic (update)
ERROR:root:Cannot report expectation
INFO:root:Processing event id here

**Comment by shahidakhter786** [comment]
Simple reboot has solved the problem.
never mind.
It was elasticsearch issue, updated and resolved
