### ISSUE TITLE
Feature Request: PHP 8 support

### ISSUE THREAD

**Issue by epol** [MISP/MISP#8919]
### Is your feature request related to a problem? Please describe.

At the moment MISP depends on [`PHP >= 7.2.0,8.0.0`](https://github.com/MISP/MISP/blob/v2.4.168/app/composer.json#L5) so only PHP 7.2, 7.3 and 7.4 can be used.

All this versions no longer receive security support from the vendor (see [here](https://www.php.net/supported-versions.php)). The version installed by the MISP installer is the 7.4 whose support ended the 28th of November 2022.

### Describe the solution you'd like

Support for `PHP >=8.0.0`, for example PHP 8.2 will receive security support until 8 Dec 2025.

### Describe alternatives you've considered

I've looked into the code to undestand why the limitation to PHP 7, it seems that's something inherited from the cakePHP framework. The support for PHP 8 has been introduced in cakePHP 4.0.0, but MISP is using a forked version of cakePHP 2.10.24.

So I don't know how to implement the use of a newer version of PHP.

### Additional context

Many vulnerability scanners consider the use of a unsupported version of PHP as a very dangerous vulerability.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jade1420** [comment]
Hi,
I'm currently dealing with the same problem...
Does the newer versions of PHP (=PHP 8.0 - PHP 8.2) work on MISP without the installation of the obsolete PHP 7.4?
I'm following the manual installation instruction for an Ubuntu 22.4-server and I'm stuck at this point.
@epol if you find a substitute or a functional solution, would you mind sharing it?

**Comment by adulau** [comment]
Yep the current branch is for PHP 7.4. There is an ongoing work to support > PHP 8.0 with the new CakePHP framework. For the time being, you need to use PHP 7.4.

**Comment by epol** [comment]
Hi, is there any way to be informed on the progress of the ongoing work for PHP 8.x? Maybe [this project](https://github.com/orgs/MISP/projects/2/)? Is there any ETA?

Thank you.

**Comment by Daisy001964** [comment]
Hi, we are facing the same issue here since some vulnerability scanners consider the use of a unsupported version of PHP as a high risk vulnerability. Is there a timeline for PHP 8.x support? Thank you.

**Comment by 4quarks** [comment]
We have the same problem...

**Comment by AndreC10002** [comment]
Seems to still be an issue. Our Debian 12 updated to PHP 8.3 and it broke the latest version of MISP completely.

**Comment by iglocska** [comment]
MISP 2.5? That should work fine on php 8.3. Though the upgrade process is manual and catering to ubuntu - so you may need some minor modifications in the upgrade script.

**Comment by AndreC10002** [comment]
> MISP 2.5? That should work fine on php 8.3. Though the upgrade process is manual and catering to ubuntu - so you may need some minor modifications in the upgrade script.

Thanks for the quick response. I've upgraded MISP via the UI, not manually.  MISP was complaining about PHP > 7.4 but I could access the UI. After the automatic upgrade it is completely broken.

So, the way around this is to update MISP manually with the latest version from git?

**Comment by iglocska** [comment]
There are two options basically: Either install PHP 7.4 (I would recommend against this) or indeed, upgrade to 2.5. 

Keep in mind that Debian isn't officially supported for 2.5 (yet) - so please adapt the Ubuntu 24.04 upgrade script instead:

https://github.com/MISP/MISP/blob/2.5/INSTALL/UPGRADE.ubuntu2404.sh

**Comment by AndreC10002** [comment]
> There are two options basically: Either install PHP 7.4 (I would recommend against this) or indeed, upgrade to 2.5.
> 
> Keep in mind that Debian isn't officially supported for 2.5 (yet) - so please adapt the Ubuntu 24.04 upgrade script instead:
> 
> https://github.com/MISP/MISP/blob/2.5/INSTALL/UPGRADE.ubuntu2404.sh

Thank you for the response.

Moving from Debian to Ubuntu is a no-go for us. All our servers are Debian and we intend to maintain consistency.

With the latest automatic updated version being 2.4.200, the decision was to install PHP 7.4 for now.
