### ISSUE TITLE
How to identify common attributes between events

### ISSUE THREAD

**Issue by enzokrr** [MISP/MISP#8925]
### Support Questions

Hello All,
I imported in my MISP instance a text file containing an IP address list (so I have an event containing a set of attributes each corresponding to an IP address).
I would like to identify the attributes of this event, which are also present in at least one other event in my organization.
Of course I have the "related events" panel on the right of my event, showing me which events have common attributes, but I don’t know how to identify these attributes.
![image](https://user-images.githubusercontent.com/126159148/220884248-a112adec-bf40-4c47-8ab5-6fc4edbe0deb.png)
I specify that my event contains 7731 attributes (IP addresses) so I need something automated.

Thanks

### MISP version

2.4.121

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Microsoft Edge

### Browser version

110.0.1587.46 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
That's easy if you click on the number, you'll see a filter view of the correlating attributes on the MISP event. 

By the way, your MISP version sounds to be very old....

**Comment by enzokrr** [comment]
I can't click on the number
<img width="237" alt="image" src="https://user-images.githubusercontent.com/126159148/220889279-b438dff1-5de5-4347-a338-b87288509985.png">
Is it because of the version?
