### ISSUE TITLE
Support: ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by giomke** [MISP/MISP#8928]
### Support Questions

Hi.
I'm getting the following error "ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry" after I'm pulling from the remote servers.

How I can fix this ?

### MISP version

2.4.167

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sva-mk** [comment]
Hey,
I can confirm this error occurs with version 2.4.168 as well.

**Comment by kherio** [comment]
I have the same error on 2.4.170 on Debian 11.

**Comment by github-germ** [comment]
Seeing also in 2.4.170 here. Thanks.

**Comment by swebster96** [comment]
During a recent Server Feed sync I am also seeing the Integrity constraint violation in version 2.4.167.  Is there a fix or work around yet?

**Comment by Barteck197** [comment]
Tactital comment, as I also see this issue on my instance.
- MISP `v2.4.170`
- Ubuntu Server 20.04.6
- php `v7.4.3`

On a sidenote:
This message: `ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '<entry>' for key '<key>'` is shown only when I try to do "Pull All". The job is being executed for some time (ca. 2hrs), and - after reaching ~20% - gets Status - Failed and Progress - Failed.

When "pulling updates to events that exist locally", the job is finishing and gets the "Progress" - Completed and "Status" - "Unknown"

**Comment by davidlife52** [comment]
I'm getting the same error with a fresh install on Ubuntu 22.04 and on Ubuntu 20.04. Also, the Pulling of 58552 events takes hours to to reach 20 percent.

**Comment by github-germ** [comment]
2.4.170
Sync pull aborts!
```
/var/www/MISP/app/tmp/logs/[19882]: add -- Attribute (360867882) from Event (669206): Attribution/threat-actor AlphaV -- Attribute "AlphaV" (360867882) added by User "SYSTEM" (0).
Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AlphaV' for key 'over_correlating_values.value'
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Model/Datasource/Database/MysqlExtended.php(142): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): MysqlExtended->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/OverCorrelatingValue.php(50): Model->save()
#6 /var/www/MISP/app/Model/Correlation.php(503): OverCorrelatingValue->block()
#7 /var/www/MISP/app/Model/Attribute.php(470): Correlation->afterSaveCorrelation()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#11 /var/www/MISP/app/Model/Attribute.php(2512): Model->save()
#12 /var/www/MISP/app/Model/Event.php(3759): Attribute->captureAttribute()
#13 /var/www/MISP/app/Model/Server.php(493): Event->_add()
#14 /var/www/MISP/app/Model/Server.php(571): Server->__checkIfPulledEventExistsAndAddOrUpdate()
#15 /var/www/MISP/app/Model/Server.php(654): Server->__pullEvent()
#16 /var/www/MISP/app/Console/Command/ServerShell.php(147): Server->pull()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#20 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#21 {main}
```

**Comment by github-germ** [comment]
Some db details
```
mysql> desc over_correlating_values;
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int unsigned | NO   | PRI | NULL    | auto_increment |
| value      | varchar(191) | NO   | UNI | NULL    |                |
| occurrence | int unsigned | YES  | MUL | NULL    |                |
+------------+--------------+------+-----+---------+----------------+
3 rows in set (0.02 sec)

mysql> select * from over_correlating_values where value='AlphaV';
+------+--------+------------+
| id   | value  | occurrence |
+------+--------+------------+
| 4450 | ALPHAV |          0 |
+------+--------+------------+
1 row in set (0.00 sec)

mysql> select count(*) from over_correlating_values;
+----------+
| count(*) |
+----------+
|     4373 |
+----------+
1 row in set (0.12 sec)

mysql> 
```

**Comment by github-germ** [comment]
@iglocska This seems like a high priority issue as many are seeing their Syncs abort. Is there something needed from the WebUI to mitigate bad table data or is this a bug not noticing that the row already exists in the table or ...?

**Comment by iglocska** [comment]
Yeah this is indeed annoying, as discussed I'll try to resolve this today. Pretty sure it's a capitalisation issue and the check happening case sensitive then the insert being allowed in a CI table.

**Comment by iglocska** [comment]
A fix is now pushed via 2252d16c912889e141ab30cc8a810def183e11d8

**Comment by Barteck197** [comment]
Thanks, after getting v 2.4.171 the error is gone.

**Comment by github-germ** [comment]
We still see this in one of our sync pull from a partner with 2.4.171.

**Comment by sva-mk** [comment]
Unfortunately, we continue to see the error on 2.4.171 as well. Do we need to adjust the database after the update?
