### ISSUE TITLE
Bug: Display issues in objects for correlations

### ISSUE THREAD

**Issue by matthijsvp** [MISP/MISP#8929]
### Expected behavior

**Situation:**
- Have event A and B. 
- Event A contains object A:1 with attribute of type ip with value "1.2.3.4"
- Event B contains attribute of type ip-dst with value "1.2.3.4"

**Expected behaviour:**
Event A shows a correlation to Event B, event B shows a correlation to event A.

### Actual behavior

When logged in as a Publisher, my list of events shows A and B, A having 1 correlation, B having 0. Looking at A shows me that it's correlated to B. Now, looking at event B, that attribute shows no correlations.
When I log in as an admin, A shows a correlation with B, but now B also shows a correlation with A.

### Steps to reproduce

According to @iglocska, this is a display bug having to do with Objects, so to reproduce I suppose using Objects would be enough.

### Version

2.4.168

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks for the notification, confirmed, there was an invalid check in the correlation engine, requiring correlated object attributes be not in an object with the distribution set to "inherit" - otherwise they would be incorrectly hidden. It's fixed on develop now.
