### ISSUE TITLE
Bug: Searching for related events from attribute shows attribute IDs instead of event IDs

### ISSUE THREAD

**Issue by matthijsvp** [MISP/MISP#8930]
### Expected behavior

When I use the "search" button in the "Related events" column in the attribute list, it shows all events that have a similar attribute. The Related Events columns should then show related Event IDs.

### Actual behavior

Instead of related Event IDs, I get Attribute IDs.

### Steps to reproduce

Use the search, Luke.

### Version

2.4.168

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Extra attachments

![image](https://user-images.githubusercontent.com/14289956/221117995-28d386d6-d9d5-4653-b690-9168e86d220d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
This was originally report 2022-Nov in https://github.com/MISP/MISP/issues/8738 occuring in 2.4.164 and still is an open issue. Actually, it is quite an issue for our users also.
