### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by KaidoLogi** [MISP/MISP#8938]
### Support Questions

 Since installing 2.4.168, been unable to push indicators using "python3 script.py" over to Sentinel

The warning message:

![unsuccessful push](https://user-images.githubusercontent.com/119605448/221933195-1d5f0a8e-78b3-4bff-b6d9-a96e40725ffc.png)

 Is now different to when it was running successfully:

![successful push](https://user-images.githubusercontent.com/119605448/221933275-210b4c76-42bb-476b-97a2-25284e209e42.png)

It would actually run a couple of times and out of nowhere pack up with the "Killed" at the end of the warning message rather than confirm sending of TI.

Is there a reason why this happening?

How do i revert to 2.4.167?

Any help would be great, thank you!

### MISP version

2.4.168

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KaidoLogi** [comment]
![successful push](https://user-images.githubusercontent.com/119605448/221932940-2b41f3c7-ba23-45f2-849c-10454ad994e9.png)

New message when TI doesn't send 

![unsuccessful push](https://user-images.githubusercontent.com/119605448/221932971-bd90e236-5368-4483-b8ef-6e62abb94447.png)

**Comment by adulau** [comment]
Maybe you should have a look at this new integration to Microsoft Azure Sentinel https://www.misp-project.org/2023/04/03/MISP-Sentinel.html/
