### ISSUE TITLE
Bug: Users - Last Login field updated for disabled accounts

### ISSUE THREAD

**Issue by dd1b** [MISP/MISP#8942]
### Expected behavior

Disabled users will not have updates on Last Login field on Administration - Users page.

### Actual behavior

Last login field on Administration - Users page is updated even for disabled users in case of login attempt (more specifically failed login attemp)

### Steps to reproduce

Disable one account.
Try to login.
The login will fail.
The Last Login field will be updated with failed login attempt date.

### Version

2.4.168

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Noticed same behavior on 2.4.198 and also found it counterintuitive.
Had to look at audit logs to confirm they didn't have a successful login after disable date.

**Comment by iglocska** [comment]
This should now be fixed on develop, the login messages indeed showed up when the user was disabled. It will be in the next release.

**Comment by Wachizungu** [comment]
Should be fixed by commit b6e2600

**Comment by dd1b** [comment]
Thank you!
