### ISSUE TITLE
Support: Only site admins able to apply tags

### ISSUE THREAD

**Issue by dwe2e** [MISP/MISP#8945]
### Support Questions

Since upgrading to 2.4.168, only Site Admins are able to add global tags to own events. Attempting with Org Admin or below results in 'No Tags Found'. This applies to user-created tags, those alreay in MISP standalone or part of a collection.

### MISP version

2.4.168

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Browser

Chrome

### Browser version

110.0.5481.178 (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dwe2e** [comment]
Is there anything i can do to progress this please?

**Comment by adulau** [comment]
I was not able to reproduce it. Is there something specific or updated in the roles in your MISP instance?

**Comment by dwe2e** [comment]
Hi, no roles are as standard install.

**Comment by dwe2e** [comment]
User error, tags had been incorrectly restricted to one user.
