### ISSUE TITLE
Support: file location

### ISSUE THREAD

**Issue by BobPeralta** [MISP/MISP#8947]
### Support Questions

Can someone tell me what happend to the files I add to my event as evidence?

### MISP version

2.4.168

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
You mean in the backend? The file is stored on the file-system and the hash is stored in the database. If it's a malware sample, it's zipped with a password. If it's just a supporting file, the file is kept as is. The file are part of the core format and when synced it's then stored locally on each MISP instances (as described before) if the distribution allows its distribution.

**Comment by BobPeralta** [comment]
Okay thanks @adulau was just wondering that the malware files were just chilling on the server without any protection.

**Comment by BobPeralta** [comment]
@adulau can u also take a look at one of my other support requests #8940?
