### ISSUE TITLE
[URGENT] The installer documentation pages are FUBAR

### ISSUE THREAD

**Issue by teward** [MISP/MISP#8954]
This is not a bug in MISP, it's a bug in the site/documentation - the install script and the MD files are UNUSABLE as they stand, documentation 404s, and the script link(s) are missing.  This prevents use of the installer script to create a new MISP instance.

THis needs rectified urgently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fukusuket** [comment]
I also encountered the same problem:(  and added only the top page link in a hurry.
- https://github.com/MISP/MISP/pull/8951

However, each markdown has many broken links and cannot be installed just by reading the markdown. 
May be a bug in the page build process?

**Comment by cvandeplas** [comment]
Some broken links are fixed in https://github.com/MISP/MISP/commit/fba5a6c8b54adc681d2dc3e9c0ee936dadccf59b . 
The rest is due to github.io that stopped to include subfiles. 
We'll need to see how we can fix that.

**Comment by righel** [comment]
If someone can check #8970 and see if I'm not missing something it would be great:
You can check the changes by pointing to my forks ghpage, for example:

https://misp.github.io/MISP/xINSTALL.ubuntu2204 -> https://righel.github.io/MISP/xINSTALL.ubuntu2204
