### ISSUE TITLE
Bug: Galaxy tag missing in the IF :: Tag logic 

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#8959]
### Expected behavior

MISP galaxy list missing from the tag selection

### Actual behavior

The list of galaxy tags should be there

### Steps to reproduce

Go to the workflow and select a IF :: Tag logic

### Version

2.4.169

### Operating System

Ubuntu

### Operating System version

20.4

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Hey
It looks like the committed fix might have an issue. I can select clusters and save, but it doesn't seem to actually match the added galaxy clusters (my test workflow which should block execution, doesn't).

looking at the code, it saves the readableTagName (removing the misp-galaxy:)
$readableTagName = substr($tag['Tag']['name'], 12);
$clusters[] = $readableTagName;

but when doing the comparison / evaluation, this is not accounted for.
As a test I removed the substr part, recreated the workflow, and then it worked as expected.

**Comment by adulau** [comment]
Indeed it sounds logical.

@mokaddem what do you think?

**Comment by mokaddem** [comment]
Absolutely! Thanks for the catch @Wachizungu (76868d1e6469219aea70aafae3f1d76409a69994)
