### ISSUE TITLE
feature request: add automatic testing for the UPDATE.txt scripts

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#896]
As discussed with @iglocska right now: it would be very handy to have an automatic test for a minor MISP update (see UPDATE.txt file for the steps). So the test could be:
1. install MISP (old, previous version) on platform $p
2. define a list of tests which still need to work after the update
3. do a UPDATE
4. run the tests and compare the data / functionality

This can be done for any platform.

Note: in this text, "UPATE" refers to a minor version update, "UPGRADE" to a major version upgrade.
(for example: 2.4.6 -> 2.4.14 is an UPDATE. 2.3 -> 2.4 is an UPGRADE)
This ticked only targets minor UPDATEs.

**Comment by Rafiot** [comment]
UPDATE.txt is irrelevant now (2.3 related)
