### ISSUE TITLE
Ubuntu 22.04 install link invalid

### ISSUE THREAD

**Issue by imidoriya** [MISP/MISP#8960]
The install for Ubuntu 2204 https://github.com/MISP/MISP/blob/2.4/docs/xINSTALL.ubuntu2204.md says to [click here](https://misp.github.io/MISP/INSTALL.ubuntu2004/) to display the correct format.  That page doesn't exist.

**Comment by minisephirot** [comment]
Heya, the page https://misp.github.io/MISP/xINSTALL.ubuntu2204 seems to be up right now

**Comment by righel** [comment]
Fixed via [#8970](https://github.com/MISP/MISP/pull/8970)
