### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by fpsilva-source** [MISP/MISP#8961]
### Support Questions

Hello,

I received an email with the encrypted credential and I would like to know how I perform the decryption procedure.

If necessary, can I generate a new PGP key and send it to you to replace it in my Org?

Thanks for the feedback.

[circl.lu #3178502] Re: MISP access

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.0

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
This place is only for issues related to the MISP Threat Sharing software. It is not related to any MISP community.
Please get in touch with your community for your question.
