### ISSUE TITLE
Bug: SimpleBackgroundJobs fails to get worker status (Supervisor API returns 301 errcode)

### ISSUE THREAD

**Issue by ServSlack** [MISP/MISP#8962]
### Expected behavior

SimpleBackGround should start without error.

### Actual behavior

When enable SimpleBackGroundJobs the Workers startk propertly looking inside Supervisorctl, but on Workers tab I receive the follow message:

" MISP cannot connect to Supervisord API, check the follow settings are coorrect. supervisor_host, supervisor_port, supervisor_user, supervisor_password, supervisor_host and restart the the service. For details check MISP error logs. "

![image](https://user-images.githubusercontent.com/32932095/226087457-bde018d2-3f52-4a5e-a879-4c1e6adb5ecc.png)

# SimpleBackGroundJobs:
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.enabled" false
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_host" 127.0.0.1
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_port" 6379
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_database" 13
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_password" ""
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_namespace" background_jobs
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.max_job_history_ttl" 86400
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.supervisor_host" "127.0.0.1"
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.supervisor_port" 9001
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.supervisor_user" supervisor
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.supervisor_password" supervisor
sudo -Hu www-data /var/www/MISP/app/Console/cake Admin setSetting "SimpleBackgroundJobs.redis_serializer" JSON

![image](https://user-images.githubusercontent.com/32932095/226087158-71dafc6c-7ed2-467e-9037-9c8b8c3301dc.png)

### Steps to reproduce

php composer.phar require --with-all-dependencies lstrojny/fxmlrpc guzzlehttp/guzzle php-http/message jakub-onderka/openid-connect-php aws/aws-sdk-php elasticsearch/elasticsearch supervisorphp/supervisor

### Version

2.4.169

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.3

### Browser

Firefox

### Browser version

102.9.0esr

### Relevant log output

```shell
2023-03-18 00:53:29 Error: An error occurred when getting the workers statuses via Supervisor API: An HTTP error occurred: Moved Permanently
2023-03-18 00:54:09 Error: Error getting supervisor status.
[fXmlRpc\Exception\HttpException] An HTTP error occurred: Moved Permanently
Stack Trace:
#0 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Transport/HttpAdapterTransport.php(58): fXmlRpc\Exception\HttpException::httpError()
#1 /var/www/MISP/app/Vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php(154): fXmlRpc\Transport\HttpAdapterTransport->send()
#2 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(94): fXmlRpc\Client->call()
#3 /var/www/MISP/app/Vendor/supervisorphp/supervisor/src/Supervisor.php(112): Supervisor\Supervisor->call()
#4 /var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php(560): Supervisor\Supervisor->__call()
#5 /var/www/MISP/app/Model/Server.php(3714): BackgroundJobsTool->getSupervisorStatus()
#6 /var/www/MISP/app/Controller/ServersController.php(1203): Server->workerDiagnostics()
#7 [internal function]: ServersController->serverSettings()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
```

### Extra attachments

 v2.4.169 (aa9dffb03fb109f73120c2b22e89e04729d5ca83) 

![image](https://user-images.githubusercontent.com/32932095/226086972-6f44045b-2fd4-4a28-ba4f-3620aa2ce389.png)

![image](https://user-images.githubusercontent.com/32932095/226086511-af9ee071-67ca-408c-89f2-6d0971a3bab7.png)

![image](https://user-images.githubusercontent.com/32932095/226086497-a3a98dd7-9808-400b-8ff0-c0860a6ceb4a.png)

![image](https://user-images.githubusercontent.com/32932095/226086518-f9eddd4f-be76-4305-b736-3e97225fc7a2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Troubleshooted via chat, issue was incorrectly setting in `/etc/supervisor/supervisord.conf`:
```
[supervisorctl]
serverurl=127.0.0.1:9001
```
instead of:
```
[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket
```
