### ISSUE TITLE
Bug: Deleting events/attributes with a sync server

### ISSUE THREAD

**Issue by BobPeralta** [MISP/MISP#8977]
### Expected behavior

If I delete a event/attribute it also deletes to the server I sync my ellements to.

### Actual behavior

If I delete a event/attribute its still on the sync server.

### Steps to reproduce

Install two MISP servers and create a connection between them.

### Version

2.4.169

### Operating System

Ubuntu

### Operating System version

20.4

### PHP version

7.4

### Browser

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
- If you soft delete an attribute, this will be propagated /updatedto the other instances.
- If you hard delete an attribute, it won't be propagated to the other instances.
- If you delete an event, it will be added in the black list of event from the instance where you deleted it to not be synced back. 

You have to see it has a delivery mechanisms for synchronisation. It was delivered to the other instance,  the remote instance won't delete an event. Updates and soft-delete are propagated.

**Comment by BobPeralta** [comment]
@adulau when I hard delete an attribute its still on the remote servers.

Why do tags, galaxies, event reports also not get deleted when removed from the original server and republished to the remote ones?
