### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by BobPeralta** [MISP/MISP#8978]
### Is your feature request related to a problem? Please describe.

We wanted to check the threat level of an event and if its high send a message to teams.

### Describe the solution you'd like

A logic IF block to check the threat level of the event thats being published.

### Describe alternatives you've considered

None at the moment

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Hello @BobPeralta,
You can either use the `IF :: Generic` conditional module to express the condition or wait until the PR #8983 gets merged.
Cheers!

**Comment by BobPeralta** [comment]
Is a existing feature now in 2.4.170.
