### ISSUE TITLE
Cannot add tags to template

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#898]
Happens on MISPpriv (v2.4.14). I have **org admin** role which has the **template editor** permission.
I cannot add tags when creating the template or when editing it.

**Comment by elhoim** [comment]
Also tested on a private v2.4.14 and it works fine, but I have **admin** role, so it might be a permission problem.

**Comment by iglocska** [comment]
Yup, definitely sounds like it. Will look into it in a few mins.
