### ISSUE TITLE
Support: API restSearch always giving json error

### ISSUE THREAD

**Issue by far00s** [MISP/MISP#8981]
### Support Questions

Hi, I'm trying to get some data from my MISP server using API calls.
I've started using the REST client on the misp GUI to understand MISP API.
Now I'm tryng to call using curl command, but I costantly obtain the same error.
What am I doing wrong?

here the command (obw I have replaced key & url with my private data): 

curl -d '{"returnFormat":"json","tags":"CERTFin:IoF"}' -H "Authorization: MY_API_KEY" -H "Accept: application/json" -H "Content-type: application/json" -k -X POST https://<myURL>/attributes/restSearch 

output: 
{"name":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","message":"Invalid JSON input. Make sure that the JSON input is a correctly formatted JSON string. This request has been blocked to avoid an unfiltered request.","url":"\/attributes\/restSearch"}

### MISP version

2.4.168

### Operating System

Red Hat 

### Operating System version

7.1

### PHP version

7.4.26RC1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @far00s 
I tested your curl command and (after completing the API_KEY and hostname) it worked without issues.

**Comment by far00s** [comment]
hello @righel, 
thank you fir the quick support. 
Have you changed something in the JSON filters or it worked as it is?

**Comment by righel** [comment]
No, I used them exactly as you shared it:
![image](https://user-images.githubusercontent.com/1659902/227587379-999904c3-a43c-41c8-b777-80f4eb5ee125.png)

```
curl -d '{"returnFormat":"json","tags":"CERTFin:IoF"}' \
	-H "Authorization: API_KEY" \
	-H "Accept: application/json" \
	-H "Content-type: application/json" \
	-k -X POST https:///localhost:8443/attributes/restSearch -s | jq '.'
```

**Comment by far00s** [comment]
I can't figure out why this format isn't working for me...

I managed to obtain the result in another way:
`
curl --header "Authorization: YOUR_API_KEY" --header "Accept: application/json" --header "Content-Type: application/json" https://_Servername_/attributes/restSearch/returnFormat:json/tags:CERTFin:IoF `
