### ISSUE TITLE
Bug: Error: Blackhole exception when accessing /events/saveFreeText/<eventid>

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8991]
### Expected behavior

Submitting a WebUI `freeTextImport` should populate the event with the attributes.

### Actual behavior

Clicking `Submit attributes` on `MISP/events/freeTextImport/<eventid>?_<sessionid>` yields a red error message bottom right of display::
* `Something went wrong - the queried function returned an exception. Contact your administrator for further details.`

### Steps to reproduce

1. Create a new event
2. `Populate from...`
3.  `Freetext Import`
4.  Paste text into the `Freetext Input Tool` pop-up
5. Click `Submit attribute` on the `Freetext Import Results` page (i.e. `MISP/events/freeTextImport/<eventid>?_<sessionid>`)
6. The error appears with WebUI remaining on the same page.

### Version

2.4.169

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Browser

Chrome

### Browser version

111.0.5563.110 (Official Build) (arm64)

### Relevant log output

```shell
2023-03-30 19:23:49 Error: Blackhole exception when accessing /events/saveFreeText/2002558 (isRest: 0, action: saveFreeText, unlockedActions: ["viewEventAttributes"]): CSRF token mismatch
2023-03-30 19:23:49 Error: [BadRequestException] The request has been black-holed
Request URL: /events/saveFreeText/2002558
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Interestingly, if we paste in a single line in the import pop-up the attribute is imported into the eventworks. However, seemingly with 2 or more text lines, the error occurs.

For example, these 2 lines produce the error:
```
URL:  hxxps://1270[.]3cx[.]cloud/webclient/api/app/windows
SHA1:  0d890267ec8d6d2aaf43eaca727c1fbba6acd16e
```
However, importing either of those lines by themself succeeds.

**Comment by github-germ** [comment]
Btw, we experience the same error with 2.4.167.

**Comment by github-germ** [comment]
@righel And we reported same March-2022 in #8204 which was resolved back then with a patch adding `MISP.disable_event_locks` which is still set `true` here along with other revisions. I collaborated a lot with you for that fix. Not sure if it's related now??!

Recall that we use `external_auth` for access.

Here's where you were able to reproduce what might be related back then: https://github.com/MISP/MISP/issues/8204#issuecomment-1077796638

Thanks...

This issue is **showstopper** currently delaying our release planned deployment to our Production MISP.

**Comment by github-germ** [comment]
Additional symptoms:
1. `Add Event > Populate from...` paste in MISP JSON  event -- succeeds to create event; however, **the 2 attributes in the JSON are not in the event.** No output to any file in `/var/www/MISP/app/tmp/logs/*.log` (note: no change in results with `Regenerate UUIDs` checked or not)
2. `Import from...` selecting same MISP JSON file pasted above --  event created and **the 2 events are included** in the event.

**Comment by righel** [comment]
Hi @github-germ 
I think this is a duplicate of #8204, the outcome of that discussion was that these two settings had to be set to `true`:

* `'MISP.disable_event_locks'` => `true`
* `'Security.authkey_keep_session'` => `true`

I cannot reproduce the issue with these two settings as above. Have you set `'Security.authkey_keep_session'` to  `true` ?

Hope this helps.

**Comment by github-germ** [comment]
Hi @righel -- Thanks for playing back those settings from #8204. Unfortunately, problem exists with both being `true`:
```
(app-root) bash-4.4# grep -E "disable_event_locks|authkey_keep_session" /var/www/MISP/app/Config/config.php
    'disable_event_locks' => true,
    'authkey_keep_session' => true,
(app-root) bash-4.4#
```

**Comment by righel** [comment]
Sorry, I misread the description and thought the CSRF error was triggered before submitting the list of attributes. 
I was able to reproduce the error, working on a fix ATM.

**Comment by righel** [comment]
Pushed a fix e88a64db521102f2f14f3eb5c15ed2250338836b for the freeTextImport issue.

**Comment by righel** [comment]
Regarding this:
> Additional symptoms:
> 
>     1. `Add Event > Populate from...` paste in MISP JSON  event -- succeeds to create event; however, **the 2 attributes in the JSON are not in the event.** No output to any file in `/var/www/MISP/app/tmp/logs/*.log` (note: no change in results with `Regenerate UUIDs` checked or not)
> 
>     2. `Import from...` selecting same MISP JSON file pasted above --  event created and **the 2 events are included** in the event.

I was not able to reproduce it and seems not related to the freeTextImport bug.
1. If the attributes have an existing attribute `uuid` and the `Regenerate UUIDs` is not checked, the attributes will not be added. Tested checking it and they were added with no issues.

Could you provide a sample MISP json event that fails for you so I can try to reproduce the issue?

**Comment by github-germ** [comment]
@righel Super!

Your https://github.com/MISP/MISP/commit/e88a64db521102f2f14f3eb5c15ed2250338836b fixed `Populate from... > Freetext Import`

I had suspected when you said you couldn't reproduce that our use of `CustomAuth` was a likely root cause This does beg the question for us to remember this when we report other CSRF issues going forward. Your fix is nice and simple, and we do trigger CSRF with other feature at times.

Let me play with MISPEvent JSON import next and report back.

**Comment by github-germ** [comment]
OK, I attempted `Populate from...` for the attached `misp.event.2017322,json` which was created by exporting an existing event and then deleting that event.

There are only two attributes. Neither are populated into the event with or without `Regenerate UUIDs`.

The event and attribute uuids do not exist:
```
mysql> select * from events where uuid='c49bf99c-38ce-4984-84fe-8e835360f1ab';
Empty set (0.00 sec)

mysql> select * from attributes where uuid in ('db80dc1e-c033-4a83-859d-f8a41d2cef5f', '605d4bc4-19f9-4b29-957e-dda31c3d21aa');
Empty set (0.00 sec)

mysql>
```

Please let me know what else I can test or collect to share with you.

Thanks!
[misp.event.2017322.json.txt](https://github.com/MISP/MISP/files/11212116/misp.event.2017322.json.txt)

**Comment by github-germ** [comment]
@righel GOOD NEWS... My mistake

As you can see in the JSON I originally attached, that was a `response` from an event export. When I remove that and only include the enclosed event, the import works!

i.e.
* removed:
```
{
    "response": [
```
* so we have:
```
           "Event": {
                "id": "2017322",
                "orgc_id": "2",
                 ...
```

**Comment by github-germ** [comment]
Hi @righel 

As per my mention above with `CustomAuth` we do see other WebUI features triggering CSRF over time. Can this "fix" be pondered for these endpoiints?
```
$ grep -i 'blackhole exception' error* | cut -d' ' -f8 | sed -e "s;/[0-9][0-9]*$;;" -e "s;/[0-9][0-9]*$;;" | sort -u
/admin/users/edit
/attributes/add
/attributes/deleteSelected
/dashboards/saveTemplate
/dashboards/updateSettings
/events/addIOC
/events/saveFreeText
/objects/createFromFreetext
# 
```

**Comment by github-germ** [comment]
Thanks
