### ISSUE TITLE
OidcAuth plugin sending null role claim "Role property `roles` is missing in claims"

### ISSUE THREAD

**Issue by Ah-U3** [MISP/MISP#9008]
### Dear Team, MISP didn't parse the roles key value from the JWT when integrating with keycloak
****All MISP configuration is done as below and added to the config.php file 
```

JWT Decode:
"iss": "https://keycloak.com/realms/MISPAuth",
  "sub": "528624f3-aafa-41bb-b903-8a8ecd2e6656",
  "typ": "Bearer",
  "azp": "misp-tr",
  "session_state": "b0278b7f-b090-4302-8c10-39a2b418febf",
  "acr": "misp-admin",
  "allowed-origins": [
    "/*"
  ],
  "scope": "openid email profile",
  "sid": "b0278b6f-b090-4302-8c10-39a2b418febf",
  "email_verified": false,
  "roles": [
    "misp-user"
  ],
  "name": "adam adam",
  "preferred_username": "admin01",
  "given_name": "adam",
  "family_name": "adam",
  "email": "adam@misp.local"
}
```

### Misp config.php
........
 array (
      0 => 'OidcAuth.Oidc',
    ),
............
` 'OidcAuth' =>
  array (
    'provider_url' => 'https://keycloak.com/realms/MISPAuth/.well-known/openid-configuration',
    'client_id' => 'misp-tr',
    'client_secret' => '*************',
    //'roles_property'=> 'resource_access.misp-trust.roles',
    'unblock' => 'true',
    'offline_access' => 'true',
    'check_user_validity' => 300,
    'role_mapper' =>
    array (
      'misp-admin' => 1,
      'org-admin' => 2,
      'misp-user' => 3,
      'misp-publisher' => 4,
      'misp-sync' => 5,
      'misp-readonly' => 6,
    ),
    'default_org' => 'Training',
  ),
`
### KeyCloak Config
Realm Created 
Client Roles created
Users created and assigned to one of the mapped roles.
Misp is successfully redirecting to Keycloak for authentication 

### Version

2.4.168

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox, Chrome

### Browser version

Latest

### Relevant log output

```shell
Trying to find user org by name `Training10`.
User organisation `Training10` found with ID 2.
Role property `resource_access.misp-access.roles` is missing in claims.

Trying to find user org by name `Training05`.
User organisation `Training05` found with ID 3.
Role property `roles` is missing in claims.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ah-U3** [comment]
### Problem Resolved
It was a keycloak configuration issue.
After editing the  acr field in the client scope and added my misp roles under : acr---> Scope MISP was able to read the role claims and issue resolved.
Thank you All

**Comment by asabolansky** [comment]
> /'roles_property'

@AdmU3 can you show me with images how did you configure Keycloak to solve this issue?

**Comment by Mumu237** [comment]
@AdmU3 Hello. Please i facing the same issue with the "role_property is misssing in claims". Please could you help me to fix my Keycloak configuration?
