### ISSUE TITLE
Bug: Reduce CSRF Blackhole exception when CustomAuth is enabled

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9015]
### Expected behavior

When `CustomAuth` is enabled some WebUI features trigger CSRF disallowing that transaction. This was resolved in #8991 specifically for the `/events/saveFreeText` use case. is it possible to investigate other endpoints that experience CSRF and apply similar resolution?

### Actual behavior

Hi @righel

As per my mention in https://github.com/MISP/MISP/issues/8991#issuecomment-1505291361  with `CustomAuth` we do see other WebUI features triggering CSRF over time. Can this "fix" be pondered for these endpoiints?
```
$ grep -i 'blackhole exception' error* | cut -d' ' -f8 | sed -e "s;/[0-9][0-9]*$;;" -e "s;/[0-9][0-9]*$;;" | sort -u
/admin/users/edit
/attributes/add
/attributes/deleteSelected
/api/rest
/dashboards/saveTemplate
/dashboards/updateSettings
/events/addIOC
/events/saveFreeText
/objects/createFromFreetext
# 
```

### Steps to reproduce

Enable `CustomAuth` and test WebUI features, some of which are listed above.

### Version

2.4.169

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Relevant log output

```shell
2023-04-04 13:31:52 Error: Blackhole exception when accessing /events/saveFreeText/2002560 (isRest: 0, action: saveFreeText, unlockedActions: ["viewEventAttributes"]): CSRF token mismatch
2023-04-04 13:31:52 Error: [BadRequestException] The request has been black-holed
Request URL: /events/saveFreeText/2002560
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
For example, the very important WebUI `API > REST client` feature, has not worked under `CustomAuth` "forever":
```
2023-04-13 12:46:18 Error: Blackhole exception when accessing /api/rest (isRest: 0, action: rest, unlockedActions: ["getApiInfo"]): CSRF token mismatch
2023-04-13 12:46:18 Error: [BadRequestException] The request has been black-holed
Request URL: /api/rest
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback()
#2 /var/www/MISP/app/Controller/Component/BetterSecurityComponent.php(22): SecurityComponent->blackHole()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): BetterSecurityComponent->blackHole()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup()
#5 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): ObjectCollection->trigger()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): BetterCakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

![image](https://user-images.githubusercontent.com/8812009/231765354-c872889e-f742-4fe2-a126-8d5303e3b19a.png)

**Comment by righel** [comment]
Hi @github-germ 
I will try to solve the underlying issue that causes this (regenerating the session on each action [here](https://github.com/MISP/MISP/blob/093e7708a6e9f22ac227a493ad5e83e4ac54f8fe/app/Controller/AppController.php#L1101)) rather than circumventing the security measures.

Whilst I do not recommend turning this setting to `true`, the `Security.disable_form_security` may be what you are asking for here.

**Comment by github-germ** [comment]
Great. We will assess if we can temporarily set `Security.disable_form_security true`

Really appreciate you working on this as it has been a longstanding issue here.

**Comment by github-germ** [comment]
@righel We enabled `Security.disable_form_security` and `API > REST client` still triggers CSRF. As you can imagine thus feature not working causes huge impact to our users. If there's a more focused fix to that while implementing the more general solution, let us know. Many thanks for looking at this CSRF as we only use MISP with `CustomAuth` and all these CSRF are a big issue for us.

**Comment by github-germ** [comment]
Related prior issue: https://github.com/MISP/MISP/issues/8305

**Comment by github-germ** [comment]
@righel What next to continue to find and fix root cause triggering CSRF with WebUI `API > REST client`? Thanks!

**Comment by github-germ** [comment]
Hello again @righel -- here's the latest endpoints with CSRF triggers in our `error.log` now running 2.4.172:
```
$  grep -i 'blackhole exception' error* | cut -d' ' -f8 | sed -e "s;/[0-9][0-9]*$;;" -e "s;/[0-9][0-9]*$;;" | sort -u
/admin/organisations/delete
/api/rest
/attributes/add
/attributes/deleteSelected
/dashboards/import
/dashboards/saveTemplate
/dashboards/updateSettings
/events/add
/events/merge
/favourite_tags/toggle
/sightings/add/
$ 
```

**Comment by github-germ** [comment]
@iglocska just presented a great talk to the GSMA community on the extremely useful WebUI dashboard and REST client features. All of our MISP instances must use CustomAuth for access which triggers CSRF for both of those features. This has been a long standing issue for us and is starving our user community of these essential tools.

**Comment by iglocska** [comment]
Should be fixed via https://github.com/MISP/MISP/commit/26ad0ef607f182ae93fe5a074c1742e95112fe28

**Comment by iglocska** [comment]
Looks like it was a partial success only, back to the drawing board.

**Comment by github-germ** [comment]
@iglocska Running test cases with 2.4.174 (finally had some time). So far, not seeing "`blackhole`" message in `error.log` and `MISP/api/rest` is not throwing CSRF. I'm checking with another power user to see if there's been any CSRF's experienced. Will report back soon.

So far, so good! Thanks!!!
