### ISSUE TITLE
CSV export at CIRCL MISP server stalls at 0%

### ISSUE THREAD

**Issue by CmdrMichael** [MISP/MISP#902]
When I try to generate the "CSV_ALL" export on https://misp.circl.lu/events/export the progress bar stalls at 0% and stays there even after > 60 Minutes.

Perhaps it is because of the large database, perhaps it is just a bug. 
On another MISP Server with >200000 attributes the export of the CSV_All works normally and is finished in about 1-2 minutes.

**Comment by iglocska** [comment]
I've just checked on misp.circl.lu, your job should be finished. I think it was an error on the progress bar itself, did you try to refresh the page?

**Comment by CmdrMichael** [comment]
Yes, if I refresh the page the Progress tab displays "Queued." for CSV_ALL.
But the "Last Update" tab says "25 minutes ago".

I just checked with CSV_SIG, there is the same problem. It is good to know that it is just a display bug.

**Comment by iglocska** [comment]
Yeah, the export itself should work fine, I'll look into why the message is not updated, that's definitely a bug.

Thanks for letting us know!
