### ISSUE TITLE
Support: Jinja2 template email workflow

### ISSUE THREAD

**Issue by BobPeralta** [MISP/MISP#9030]
### Support Questions

Can anyone tell me how I can change the template inside the send mail module from the workflow?

### MISP version

2.4.170

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BobPeralta** [comment]
@adulau Could u please assit me with this problem I can't figure out how this works?

**Comment by adulau** [comment]
Hi Bob, It's using a default expansion misp module [jina_template_rendering](https://github.com/MISP/misp-modules/blob/c1168ac627ee06ec352d632bf6f298b4d68d5de5/misp_modules/modules/expansion/jinja_template_rendering.py#L4) you can change the template there if you want.

**Comment by BobPeralta** [comment]
O okay thanks I didn't know u needed the misp-modules for that.

**Comment by BobPeralta** [comment]
@adulau do you have any idea how to list attributes using jinja?
