### ISSUE TITLE
Bug: ERR_TOO_MANY_REDIRECTS with (1) WebUI Filter by Event Info contains space(s), (2) pymisp.get_organisation

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9033]
### Expected behavior

**In WebUI any string including space in the Filter by Event Info triggers this condition.**

Would expect the WebUI to retrieve/display a list of events when on the List Events page first doing filter by an organisation and following that by entering text in the filter event info.

### Actual behavior

WebUI displays:
```
The page isn't working right now
misp.x.y.z redirected you too many times
To fix this issue, try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

### Steps to reproduce

1. `Event Actions > List Events`
2. Click magnifying glass and rule `Organisation` selecting one of our local orgs, click `Add` and then `Apply`
3. This does display the list as per the org filter: in our case 40 records
4. Enter a substring that exists in some of the Event Infos on the display in the filter textbox top-right above the events listed and click `Filter`
5. This triggers the `ERR_TOO_MANY_REDIRECTS` as above.

### Version

2.4.170

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Browser

Chrome

### Browser version

112.0.5615.49 (Official Build) (arm64)

### Relevant log output

```shell
No output in log files in /var/www/MISP/app/tmp/logs/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
**This is a critical error issue preventing top level event searches!!**

This `ERR_TOO_MANY_REDIRECTS` issue also occurs on the WebUI `/events/index` home page with the filter resulting `/events/index/searcheventinfo:string` page.

Not yet sure what strings are triggering this issue, e.g. in our case `CnC` is fine, but `Cnc -` triggers.

**Comment by github-germ** [comment]
Also seeing `TooManyRedirects` exception in `pymisp.get_organisations` when including a space in the search string, e.g.
```
(Pdb) pymisp.__version__
'2.4.170'
(Pdb) xx=misp.get_organisation('foo')
(Pdb) pp(xx)
{'errors': (404,
            {'message': 'Invalid organisation',
             'name': 'Invalid organisation',
             'url': '/organisations/view/foo'})}
(Pdb) xx=misp.get_organisation('foo bar')
*** requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
(Pdb) 
```

**Comment by github-germ** [comment]
@iglocska Something is strange with spaces and perhaps other chars in search strings in WebUI filters, and now also seeing it in `pymisp.get_organisations`. This has escalated into a big issue for us. Any ideas on what else I can collect and share here would be very helpful. Thanks.

Note: there is no output seen with this issue in `/var/www/MISP/app/tmp/logs/*log`

**Comment by github-germ** [comment]
@righel Are we doing something wrong our end?

**Comment by righel** [comment]
I cannot reproduce this, and it sounds quite weird.
What I would check:
* Proxy settings / logs in case there's some redirect loop going on.
* The redirect rules of your apache mod_rewrite/.htaccess or nginx rewrite rules. nothing in the apache/nginx logs?

**Comment by iglocska** [comment]
Yeah the redirect loop sounds weird, could be an http vs https routing issue? 

As for the spaces: Indeed, that is an issue as it's using URL parameters rather than POST requests with the search terms being in the body. We could alternatively url encode the strings from the search to combat this.

**Comment by github-germ** [comment]
**Re' the redirect..**. I don't recall this being an issue before 2.4.170 -- actually, I've never seen this error. Nothing has changed in our MISP instances nor Apache nor proxy (I have no access to proxy logs).

**Re' spaces...** URL encoding, e.g. `%20` is not interpreted as a `space` when attempted, i.e. the search returns no match.

Anything else to look for?

Thanks!

**Comment by github-germ** [comment]
With a little debugging I can report that `OrganisationsController->view` is not getting called. What can I look at leading up to that that's triggered the redirect loop?

**Comment by github-germ** [comment]
I do not have a prior version before 2.4.170 available these days, but I gotta believe I've used spaces in the filter before this.

Can you reproduce?

Any chance this getting fixed in 2.4.171?

If I can collect any evidential data here, let me know.

**Comment by github-germ** [comment]
@iglocska Problem persists in 2.4.171. :-(

**Comment by iglocska** [comment]
I'm pretty sure this was always an issue with url parameters - I'll check
on Monday, ideally we should be able to pass the string via a posted JSON
object

**Comment by github-germ** [comment]
@iglocska Would be great to have this fixed in 2.4.172 :-)
* Big issue for our WebUI Analysts who need the filter working
* We also have cron jobs that now fail due to the `pymisp.get_organisation` failure.

THANKS!!

**Comment by github-germ** [comment]
@iglocska Por favor...

**Comment by github-germ** [comment]
@iglocska pushed a fix for MISP encoding spaces as `+` instead of `%20` in the URL and this seems to work.

https://github.com/MISP/MISP/commit/7853cf70c27755975a7b8771da6fc9cc05e50295

He suggests PyMISP needs the same change. I'll create an issue for @Rafiot 
* https://github.com/MISP/PyMISP/issues/1014

**Comment by iglocska** [comment]
Just as an update on this, %20 will now also work
