### ISSUE TITLE
Support: Fast URL Singular Attribute Exact Match Search: events/index/searchattribute:str too slow since wildcards mysql

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9036]
### Support Questions

**Would like to a URL that produces a fast result for a single attribute exact match search.**

Have tried `https://MISP/events/index/searchattribute:<indicator>` with that URL embedded on a web page. However, the mysql query wildcards the IP which then takes 7+ minutes (query example below). I understand the wildcarding makes sense in this context.

**HOWEVER, is there a way to qualify this search or another URL where an exact attribute value match is requested?**

The `Search Attributes` page can do a singular attribute search with an instant result. But we need a link to put on a web page in another system and I don't see how to make that page work with a single URL. I did play with `curl` as a prototype with the `form`, but that triggers CSRF since there's no valid token.

For example, here's one wildcard query triggered with `searchattribute:<IP>`:

```
SELECT DISTINCT Attribute.event_id, Event.id, Object.idFROMmisp.attributes AS Attribute 
LEFT JOIN misp.events AS Event ON (Attribute.event_id=Event.id)
LEFT JOIN misp.objects AS Object ON (Attribute.object_id=Object.id) 
WHERE ((((Attribute.value1 LIKE '%13.107.136.9%')
OR (Attribute.value2 LIKE '%13.107.136.9%')))
AND (Attribute.deleted = '0'))
```

### MISP version

2.4.170

### Operating System

RH

### Operating System version

8.7

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Here's possibly a simple resolution...
* Make the mysql query do an exact match to the string passed in the `searchattribute` URL, i.e. no longer wildcard the query value with `%string%`'
* This would be a change for users of this URL to explicitly include the wildcards when that's what's desired.
 
Examples:
* in our use case where we want a specific IP match: 
```
URL: https://MISP/events/index/searchattribute:1.2.3.4

MySQL -- this returns results instantly!

SELECT DISTINCT `Attribute`.`event_id`, `Event`.`id`, `Object`.`id` FROM `misp`.`attributes` AS `Attribute` LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event_id` = `Event`.`id`) LEFT JOIN `misp`.`objects` AS `Object` ON (`Attribute`.`object_id` = `Object`.`id`)  WHERE ((((`Attribute`.`value1` LIKE '1.2.3.4') OR (`Attribute`.`value2` LIKE '1.2.3.4'))) AND (`Attribute`.`deleted` = '0'));
```
* somebody want to find all names ending in `%google.com`
```
URL: https://MISP/events/index/searchattribute:%google.com

MySQL: yes, it will take time, but the user is doing wildcarding

SELECT DISTINCT `Attribute`.`event_id`, `Event`.`id`, `Object`.`id` FROM `misp`.`attributes` AS `Attribute` LEFT JOIN `misp`.`events` AS `Event` ON (`Attribute`.`event_id` = `Event`.`id`) LEFT JOIN `misp`.`objects` AS `Object` ON (`Attribute`.`object_id` = `Object`.`id`)  WHERE ((((`Attribute`.`value1` LIKE '%google.com') OR (`Attribute`.`value2` LIKE '%google.com'))) AND (`Attribute`.`deleted` = '0'))

**Comment by github-germ** [comment]
Thinking a bit more, it would be great to have 2 methods yielding the string exact matches on either of these possible results pages:

### 1. **List of matching attributes** -- Like the `Search Attributes` page displays:

![image](https://user-images.githubusercontent.com/8812009/234561679-0876979d-8588-4344-9a41-78f24b4aa158.png)

________________________________________________________________________________________________
________________________________________________________________________________________________

### 2. **List of matching parent events** -- Like the one from the Automation URL `searchattribute:string`:

![download](https://user-images.githubusercontent.com/8812009/234563155-764d438d-ec39-4dae-ac87-adb67a1ed286.png)

**Comment by iglocska** [comment]
That would indeed make sense, we use that strategy for restsearch - however, the issue is backwards compatibility. If we were to change it in a new release it would introduce some odd behaviours for those relying on the previous behaviour. 

Instead a cleaner approach (at least for backwards compatibility...) would be to introduce a new keyword that searches as described (perhaps calling it searchvalue or something).

**Comment by github-germ** [comment]
Yes, I agree not to break backwards compatibility.

If 2 results pages are deemed good, would it be possible to define a new `searchvalue` parameter with an additional parameter, e.g. `result` which could be set to `events` or `attributes`?

**Comment by righel** [comment]
Hello @github-germ 
Could you check if [this PR](https://github.com/MISP/MISP/pull/9050) suits your needs?

You can use this urls for search by a exact match on attributes values:
* `https://MISP_URL/attributes/index/searchvalue:2.2.2.2`
* `https://MISP_URL/events/index/searchvalue:2.2.2.2`

**Comment by github-germ** [comment]
Hi @righel Excellent. They both work! **Thanks**.

I know this wasn't what we discussed, but I imagine somebody will try this and ask me... 
* _Can I use a `%` wildcard in the string to match and if not, how can I search for a string that contains a percent?_

As is now, this yields:
* `Your browser sent a request that this server could not understand.`

Other than `how to search for a percent sign` I'm OK with this as is since these endpoints are supposed to be exact matches (i.e. `=`, not `like`).

**Comment by righel** [comment]
Interesting, will have a look a this, thanks for reporting.

**Comment by righel** [comment]
So it seams that if you prepend the `%` the request fails (400 error) because it's a malformed url as it tries to interpret a url encoded entity.
For searching for a `%` value, the user should use the url encoded entity (`%25`), just tested it and it works, maybe not intuitive, but you could implement this logic in your external system when generating the MISP urls.

I think it's not something I can fix from MISP codebase, since it's not the one generating the search urls.

**Comment by github-germ** [comment]
Thanks. Aha, duh... that makes perfect sense! Then we are good to go. Any idea when this might get into a new 2.4.171? I ask as we can only deploy "official" releases into our production systems.

**Comment by righel** [comment]
Cool, I'll merge it into `develop` then.
Yes, by the end of this week we'll tag 2.4.171 with the latest fixed/improvements.

**Comment by github-germ** [comment]
Bravo!
