### ISSUE TITLE
Bug: Workflow send email

### ISSUE THREAD

**Issue by BobPeralta** [MISP/MISP#9045]
### Expected behavior

I created a workflow that checks the threat level of an event when it gets published, if it is high it sends an email to specific users.

### Actual behavior

It doesn't send an email even though the email service is setup correctly cause just publishing with email works.

### Steps to reproduce

Set up an email server.
Create a workflow using the event publish trigger:
![image](https://user-images.githubusercontent.com/119043466/235106736-562a2ac2-0def-4887-8e9a-9afb23e073b6.png)

### Version

2.4.170

### Operating System

Ubuntu

### Operating System version

20.4

### PHP version

7.4

### Extra attachments

It worked before but from one day to another it stopped functioning.
The logs don't show any output of it not working it just says succeed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Thanks for the report. Could it be possible that you have log entries in `/logs/index` looking like this:
> Node `send-mail` (xx) from Workflow `Workflow for trigger event-publish` (yy) returned the following error: The mail template is empty.,

Because from the provided screenshot, I see the mail subject & body being empty.
In the meantime, I'll close the issue. Let us know if setting the templates still doesn't work for you.
