### ISSUE TITLE
Bug: Adding custom workflow doesn't work | no errors comes up 

### ISSUE THREAD

**Issue by Nicolas-Pellletier** [MISP/MISP#9049]
### Expected behavior

According to the documentation ([slides source](https://www.misp-project.org/misp-training/a.12-misp-workflows.pdf), [video1](https://www.youtube.com/watch?v=OyLE2g4zii0), [video2](https://www.youtube.com/watch?v=BsggY7-X_6o)):

We just have to place our new `PHP action module` in `/var/www/MISP/app/Lib/WorkflowModules/action/[module_name].php` and "MISP will automatically pick it up. it's almost drag and drop". 

### Actual behavior

I've got a blank page and error 500 to the GET request: `127.0.0.1 - - [30/Apr/2023:13:38:57 +0200] "GET /workflows/triggers HTTP/1.1" 500 675 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"`.
Nothing in `/var/www/MISP/app/tmp/logs/*.log`. 

### Steps to reproduce

I've just copy an existing module found in `/var/www/MISP/app/Module/WorkflowModules/action/[module_name].php` (So it's a valid module). I've set a different name and put it in `/var/www/MISP/app/Lib/WorkflowModules/action/[module_name].php`.

I've also tried  to delete  the following function: 
```
public function __construct()
    {
        parent::__construct();
    }
```  
because it is not present in the `Module_blueprint_action_module.php` example action module but nothing. I've also try to copy the `Module_blueprint_action_module.php` with different name but get the same error as above

### Version

2.4.169

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Hello!
Thanks for the feedback. Could it be that you forgot to rename the class of the module after copy/pasting it? PHP doesn't like class name collision.
I pushed a small change (on `develop`) that avoid suppressing errors while importing module. Hopefully that will help finding out the reason if the solution above doesn't work.
Let us know if it's still not solved and we'll re-open the issue.
Thanks!

**Comment by Nicolas-Pellletier** [comment]
Hello @mokaddem 

Thanks for your response, i'm going to check right away

**Comment by Nicolas-Pellletier** [comment]
I think it works now with keeping the same class name as the filename. 
Thanks again for you response !
