### ISSUE TITLE
Unable to Enable Server Settings

### ISSUE THREAD

**Issue by efensive** [MISP/MISP#905]
Finished installation to the tee following every instruction for Ubuntu (14.04). Got the message: "Warning: MISP is currently disabled for all users. Enable it in Server Settings (Administration -> Server Settings -> MISP tab -> live)" So I went to enable it and got:     

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

Tried going to /var/log/ and checked both error.log, and misp.local_error.log and there is nothing in them at all.

**Comment by iglocska** [comment]
Odd, so you didn't have any errors until you enabled the "live" setting? 

Could you check the error logs in /var/www/MISP/app/tmp/logs/error.log?

**Comment by efensive** [comment]
I didn't have any errors at all. Here is that log (hooray Redis):

2016-02-03 10:33:41 Error: [RedisException] Redis server went away
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2079): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(696): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by iglocska** [comment]
Could you check if your Redis is still running? It looks like MISP doesn't see Redis.

Type redis_cli and see if it works.

**Comment by efensive** [comment]
Negative. 

redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused

I restarted the server going BACK through the walkthrough to see what I had missed.

**Comment by AdrianCUCU** [comment]
same problem here. any solve?
