### ISSUE TITLE
Forgot Admin Password. HELP!!

### ISSUE THREAD

**Issue by chimera0garden** [MISP/MISP#9055]
I changed the password for admin@admin.test and forgot what the new password is and now I cannot login. Could anyone please help with how I can reset the password back to the default one or at least a way I can completely uninstall MISP and reinstall? I initially installed it as a docker container. Thank you

**Comment by Wachizungu** [comment]
You can reset the password via the command line by using:
/var/www/MISP/app/Console/cake Password [email] [password]

**Comment by righel** [comment]
Try:
`/var/www/MISP/app/Console/cake user change_pw [email] [password]`

**Comment by freitasthiago** [comment]
I also tried resetting the [admin@admin.test](mailto:admin@admin.test) password with the commands below:

sudo /var/www/MISP/app/Console/cake Password admin@admin.test [mypassword]

I also tried:
sudo /var/www/MISP/app/Console/cake user change_pw admin@admin.test [mypassword]

as explained in https://github.com/MISP/MISP/issues/1160 and https://github.com/MISP/MISP/issues/9055, but that didn't help... reinstalling the instance isn't a good option.

Is there a new procedure?

**Comment by Wachizungu** [comment]
Please say what the result was when you ran the command(s). Did you get any output, if so what?
You can also check if you get errors in the logs (typically at /var/www/MISP/app/tmp/logs)
Whenever you ask for support in the future, in this project or another, please include that info.

As for some potential issues know of:
Make sure the password meets the complexity requirements you have in your config file.
Choose special characters in the password that can't cause issues. Avoid having ! or ' in the password, for example.

I hope this helps.

**Comment by freitasthiago** [comment]
For this command, "sudo /var/www/MISP/app/Console/cake Password admin@admin.test [mypassword]" => ERROR

For this command, "sudo /var/www/MISP/app/Console/cake user change_pw admin@admin.test [mypassword]" => Changed successfully.

I had to reinstall the entire instance, but these commands don't work.
