### ISSUE TITLE
Bug: Required "version" field missing in OpenAPI spec

### ISSUE THREAD

**Issue by jbrouault** [MISP/MISP#9058]
### Expected behavior

The OpenAPI spec **info** object must contain a **version** field, as stated in the [specification](https://spec.openapis.org/oas/v3.0.0#info-object):

version | string | REQUIRED. The version of the OpenAPI document (which is distinct from the OpenAPI Specification version or the API implementation version).
-- | -- | --

One should be able to import the MISP OpenAPI spec as is in tools supporting it (Postman in my specific case).

### Actual behavior

Importing the OpenAPI spec fails in Postman because of the missing "version" field.

Current info object:
https://github.com/MISP/MISP/blob/c3f7077abe111154017b52fac504f293ea41a471/app/webroot/doc/openapi.yaml#L2-L54

### Steps to reproduce

Download the OpenAPI spec at MISP_INSTANCE_BASEURL/doc/openapi.yaml and try to import it in Postman.
I guess the problem exists with other tools, https://editor.swagger.io/ reports the following error for example:

> Structural error at info
> should have required property 'version'
> missingProperty: version
> Jump to line 2

### Version

2.4.170

### Operating System

N/A

### Operating System version

N/A

### PHP version

N/A

### Browser

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 01dr1ch** [comment]
This is accepted by latest Postman version:
![image](https://github.com/MISP/MISP/assets/82970780/cd67ca32-e985-481a-96b8-285de0cd598d)

**Comment by adulau** [comment]
@righel what do you think?
