### ISSUE TITLE
Edit of attributes via AJAX is blackholed

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#907]
When trying to mass-edit attributes, the AJAX request gets blackholed. The error message can be seen in the CakePHP error.log.

Tested on v2.4.16 instances.

**Comment by iglocska** [comment]
I cannot seem to be able to reproduce this.

What I tried: Mass select all attributes in an event, change the distribution and IDS flag, accept. All attributes get changed. (v2.4.16)

**Comment by msoria** [comment]
Hello!

Exact issue:
Select all attribute, then unselect one, in our case an internal reference. Edit change sharing to all communities. Save.

Actually, i wondern if the "select all" check box was still checked even if i unselect one afterwards. Cannot verify right now :(
Miguel

**Comment by iglocska** [comment]
That is weird as hell. For when you guys can check: Which cakePHP version are you guys on? Also, is the baseurl setting in the configuration set correctly?

**Comment by elhoim** [comment]
That should be it!
We had problems resolving the hostname, so we switched to using the ip but the baseurl has not been changed!

**Comment by iglocska** [comment]
Yay, great success!

**Comment by elhoim** [comment]
Tested with correct baseurl but still does not work.

**Comment by iglocska** [comment]
Argh... Can you check the CakePHP version?

**Comment by elhoim** [comment]
v2.7.8

**Comment by elhoim** [comment]
Full error message if it helps:

```
2016-02-04 10:07:11 Error: [BadRequestException] The request has been black-holed
Request URL: /attributes/editSelected/6647
Stack Trace:
#0 [internal function]: AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(239): SecurityComponent->blackHole(Object(AttributesController), 'auth')
#4 [internal function]: SecurityComponent->startup(Object(AttributesController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by iglocska** [comment]
This is weird as hell. Can you try it on the CIRCL instance with the same browser and see if you get the same issues?

**Comment by elhoim** [comment]
Same thing on CIRCL's MISPpriv.

Test event id I tried to edit was 3105, that should help you search the logs.

**Comment by msoria** [comment]
It works in our instance now. I do not know why and how.

**Comment by iglocska** [comment]
Very curious. I kept trying to reproduce it including the event you mentioned @elhoim, but I am not able to do so. Frustrating :)

**Comment by elhoim** [comment]
@iglocska Did you find some error in the logs on MISPpriv mentioning event 3105?

**Comment by adulau** [comment]
Just checked on misppriv but cannot find logs entries in debug.log or error.log for event 3105.

**Comment by iglocska** [comment]
Yeah, checked that a while back too and I can't find anything nor reproduce
it :( Not sure what's going on. If you have any steps on how to exactly
reproduce it let me know (including every step you've taken, browser
version, heck I'll install whatever OS you are using to test it, because
it's slowly driving me nuts - unless it's OS X :))

**Comment by Rafiot** [comment]
@elhoim @msoria do you still have the issue?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
