### ISSUE TITLE
Support: Threat Level: adding critical

### ISSUE THREAD

**Issue by h-adwan** [MISP/MISP#9077]
### Support Questions

Hello team, 

In the Threat Level, there are now:
high
Medium
Low
Undefined

Can you add Critical to the list?
To be aligned with other sources categorization

Thanks

### MISP version

2.4.151

### Operating System

RedHat

### Operating System version

8

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
As can be seen in the tooltip and [MISP-book](https://www.circl.lu/doc/misp/using-the-system/#creating-an-event), the MISP levels are associated to 
- low means mass-malware, 
- medium means APT malware, 
- high means sophisticated APT malware or 0-day attack

Perhaps Critical of somewhere else maps adequately with high on MISP level.

**Comment by adulau** [comment]
Threat Level is an outdated field in MISP.  I would recommend to create a taxonomy, extend an existing and propose a change in https://github.com/MISP/misp-taxonomies. 

Concerning criticality there is a good example in https://www.misp-project.org/taxonomies.html#_csirt_case_classification 

Let us know if you have a complete list and see if we can adapt an existing taxonomy or create a special one.
