### ISSUE TITLE
Support: Bug: GUI shows active workers while CLI getWorkers showing they are down

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#9079]
### Support Questions

Hello MISP Community,

I am facing some issue that is confusing me as GUI shows all workers are healthy and working fine but CLI getWorkers showing all of them with false status.
However, all feeds pulling, sync actions, publishing ..etc. are working fine.

Not sure if it is a bug or an issue from my side.

GUI

![image](https://github.com/MISP/MISP/assets/21212837/e7467e7f-625b-411f-ada6-24fa3c3799db)

CLI

`# /var/www/MISP/app/Console/cake Admin getWorkers
{
    "cache": {
        "ok": false,
        "workers": [
            {
                "pid": 24778,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            },
            {
                "pid": 24663,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ],
        "jobCount": 0
    },
    "default": {
        "ok": false,
        "workers": [
            {
                "pid": 24627,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ],
        "jobCount": 0
    },
    "email": {
        "ok": false,
        "workers": [
            {
                "pid": 24681,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ],
        "jobCount": 0
    },
    "prio": {
        "ok": false,
        "workers": [
            {
                "pid": 24645,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ],
        "jobCount": 0
    },
    "update": {
        "ok": false,
        "workers": [
            {
                "pid": 24699,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ],
        "jobCount": 0
    },
    "scheduler": {
        "ok": false,
        "workers": [
            {
                "pid": 24717,
                "user": "www-data",
                "alive": false,
                "correct_user": false,
                "ok": false
            }
        ]
    },
    "proc_accessible": true,
    "controls": true
}
`

### MISP version

2.4.167

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
What user are you running the CLI command with? Is it the same as the
apache user?

**Comment by ahmedxuae91** [comment]
@iglocska It turned out i am checking with different user.. changed to www-data and showing up now :) .. Thanks
