### ISSUE TITLE
Log archival

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#910]
I have activated all logging option (including all API accesses) on an instance, it has generated quite a bit of logs (>17 000 000).
I played around with some MySQL features to archive data but still have it accessible if I want to do some reporting from them.
What I did was:

```
create table logs_archive like logs;
alter table logs_archive engine=archive;
insert logs_archive select * from logs order by id LIMIT 1000000;
delete from logs order by id LIMIT 1000000;
```

Which gives me a nice 28M compressed (zipped) table with the first 1million lines of logs.

Do you think it would be sensible to add that as a "archive logs" feature or admin tool?

**Comment by iglocska** [comment]
Sounds like a good idea. 17M log entries was this on 2.4 or 2.3?

**Comment by elhoim** [comment]
I think most of it came from v2.3 because of 1 API access auth per attribute/shadow_attribute

**Comment by iglocska** [comment]
Yeah, in 2.4 it might not be as relevant. Also, the main issue with it in
2.3 was that you were doing lookups against the log table for the
contributors list (which is a nightmare).

However, if you have a very busy instance (especially for API access) with
full logging it might make sense anyway.

**Comment by adulau** [comment]
@elhoim Can we close this one?

**Comment by elhoim** [comment]
Yep!
