### ISSUE TITLE
Feature Request: HOTP support for authentication

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#9107]
### Is your feature request related to a problem? Please describe.

In some cases TOTP cannot be used as it requires software or a phone. 
HOTP are single use tokens that can be printed on a paper and are an option in those cases.
This use-case was identified during a MISP community meeting.

### Describe the solution you'd like

Implement HOTP so that a user can choose between TOTP or HOTP when strong authentication is required.

User profile allows for generation of the HTOP tokens in addition to the TOTP.
If the HOTP tokens were generated, provide these as authentication method, in addition to the TOTP form.  (so both options on one page if the user has both enabled)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
Implemented in  cb74ad507f0aa2709cf7e9ad1bdb9053e932be58 in PR #9085

**Comment by adulau** [comment]
Thanks. Everyone is super happy with the new feature!
