### ISSUE TITLE
Bug: "read only" auth keys are returning 405 and Permission Denied to /sightings/restSearch/.*

### ISSUE THREAD

**Issue by teward** [MISP/MISP#9116]
### Expected behavior

When using a read-only auth key and reaching an endpoint that does NOT have write privileges such as `/sightings/restSearch/` or any contextual URL on this, the expected behavior would be you do not get a 405 response and receive a response from the endpoint like this for an empty sightings set:

`{"response": []}` (with HTTP 200)

or a response that the query is invalid:

`{"name":"An ID or UUID must be provided if the context is set.","message":"An ID or UUID must be provided if the context is set.","url":"\/sightings\/restSearch\/event"}` (with HTTP 405)

### Actual behavior

When using a read-only auth key, permissions are outright denied to the endpoint, which returns this:

`{"name":"You do not have permission to use this functionality.","message":"You do not have permission to use this functionality.","url":"\/sightings\/restSearch\/event"}`

### Steps to reproduce

1. Create an event as organization A
2. Add event to sharing group that organization B has access to view.
3. Add user to organization B with a read-only auth key
4. Run following query to endpoint with read-only auth key from user B  (cURL on linux command line is here):

```
curl --verbose --insecure --header 'Authorization: AUTHKEY' --header 'Accept: application/json' --header 'Content-Type: application/json' --write-out '\n\nHTTP-code=%{http_code} Time-total=%{time_total}\n' --data '{"returnFormat": "json","last": 500,"includedUuid": true,"uuid":"7251cd78-3b05-434b-abd9-067a0bcc144b"}' https://MISPURL/sightings/restSearch/event
```
5. Check response that is output, it should look like this if the bug is reproduced:

```
{"name":"You do not have permission to use this functionality.","message":"You do not have permission to use this functionality.","url":"\/sightings\/restSearch\/event"}

HTTP-code=405 Time-total=0.325797
```

### Version

2.4.170

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Hey @iglocska -- @teward  and I collabed on #9065 that I shared with you. Root cause to the MISP Sync pull sightings HTTP 405 has been isolated.

**Comment by github-germ** [comment]
@iglocska This is still an issue in 2.4.172. If you need us to provide any additional evidence from our side, please let us know. Thanks!

**Comment by crym** [comment]
There may be more to this.
When using a R/W AuthKey, it works when sending a request with a numeric ID, but I get a 405 when sending a request with a UUID:
```
{
    "message": "An ID or UUID must be provided if the context is set.",
    "name": "An ID or UUID must be provided if the context is set.",
    "url": "/sightings/restSearch/event"
}
```
