### ISSUE TITLE
Bug: official LDAP authentication support

### ISSUE THREAD

**Issue by Thus0** [MISP/MISP#9132]
### Expected behavior

I've configured LDAP authentification with this documentation : 
https://www.circl.lu/doc/misp/appendices/#appendix-f-ldap-authentication

But when I try to login, it only works with local accounts.

On the login page, I should have a list (?) to choose my authentication method (local user or ldap user)

### Actual behavior

The login page does not change.

I launched tcpdump and did not see any outgoing connexions to my LDAP server.

Is the documentation accurate ? https://www.circl.lu/doc/misp/appendices/#appendix-f-ldap-authentication
In config.default.php, there is only a mention on 'Apache LDAP authentication' (which is not official) and not 'LdapAuth'
https://github.com/MISP/MISP/blob/19e969892fc9c3765456a5f491af392e7d20adeb/app/Config/config.default.php#L219

### Steps to reproduce

Configure app/Config/config.php

```
'LdapAuth' => array(
   'enabled' => true,
   'name' => 'My Identity provider',
   'ldapServer' => 'ldap://$IP:$PORT',
   'ldapDN' => 'cn=accounts,dc=foo,dc=fr',
   'ldapSearchFilter' => '(objectclass=inetuser)',
   'ldapReaderUser' => 'uid=test,cn=users,cn=accounts,dc=foo,dc=fr',
   'ldapReaderPassword' => '$PASSWORD',
   'ldapUserGroup' => '$MISP_GROUP',
   'updateUser' => true,
 );
```

### Version

2.4.171

### Operating System

Alma Linux

### Operating System version

9

### PHP version

7.4

### Browser

firefox

### Browser version

firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xme** [comment]
Hello all,
Setting up a brand new instance... Same problem here. Any tip/idea?
LDAP module installed, Config.php changed, ... nada!?

[Edit 1]
While diving in the code, I found that a HTTP_REMOTE_USER must be passed by Apache to trigger ApacheSecureAuth. Does it mean that LDAP authentication must be performed at Apache level first and the LDAP lookup in MISP is just used to fetch the user's email address and populate the local DB?

**Comment by Brandon-Wiley** [comment]
I'm fairly certain this occurs because the new docker images don't leverage Apache as the webserver and instead are built around Nginx.

Apache originally performed the basic ldap authentication to populate the REMOTE_USER data. However now that the images are using nginx, the initial LDAP authentication is missing thus no data is passed to next step which is the PHP authorization step.

**Comment by Kagee** [comment]
> Hello all, Setting up a brand new instance... Same problem here. Any tip/idea? LDAP module installed, Config.php changed, ... nada!?
> 
> [Edit 1] While diving in the code, I found that a HTTP_REMOTE_USER must be passed by Apache to trigger ApacheSecureAuth. Does it mean that LDAP authentication must be performed at Apache level first and the LDAP lookup in MISP is just used to fetch the user's email address and populate the local DB?

For docker, yes, this is correct.

**Comment by adulau** [comment]
There is now a standalone LDAP authenticator in MISP which could clearly help in such scenario.

https://github.com/MISP/MISP/tree/29993e516825b8ff35a72419fa61c40472eb1898/app/Plugin/LdapAuth
