### ISSUE TITLE
Tags/taxonomies not being displayed without activating

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#914]
Hey,

I am running 2.4.14 and facing some issues with tags.
All taxonomies are enabled, but I can only see a limited amount of tags:

```

Select Tag Source
Custom Tags
Taxonomy Library: admiralty-scale
Taxonomy Library: circl
Taxonomy Library: ecsirt
Taxonomy Library: tlp
Taxonomy Library: veris
```

And even within the lists most of them are deactivated.
Is there a reason behind not activating most of them? E.g. TLP:red is not available unless you activate them.
My guess is: tag are activated as soon as an event is synced that has a specific tag.

**Comment by iglocska** [comment]
They can be activated in two ways:
1. by receiving an event with the tag
2. by having a site admin activate the tags

For #2, go to event actions -> list taxonomies as a site admin, and you'll be able to activate a taxonomy library. When you do that you can view the library and activate the tags that you want to make selectable for your users.

For example, you might only be interested in a subset of the Veris taxonomy library, so you can simply enable the portion that you are interested in.

**Comment by jaegeral** [comment]
Understood, cost around 5 minutes to understand the way it is being handled.
Maybe it would be nice to add another button in the Tax. Overview to just enable all of the tags in a list, or display x/y are currently activated.

(I understood it is not an Bug, but there might be some space for user exp. here)

**Comment by iglocska** [comment]
Definitely and sounds like a good idea.
