### ISSUE TITLE
Bug: Entering multiple search terms in Eventinfo Web UI fails with ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#9146]
### Expected behavior

(1) Enter multiple terms (i.e., a phrase) into the Search constructor or Search window to the upper right of Event Index.
(2) Click Apply
(3) Search returns Events with matching phrase if found

Notes:

This functionality has always worked in the Web UI up until several releases ago.  
Others have reported it in various contexts.
This is a serious breaking issue for several Analyst Workflows for us.

### Actual behavior

(1) Enter multiple terms (i.e., a phrase) into the Search constructor or Search window to the upper right of Event Index.
(2) Click Apply
(3) ERR_TOO_MANY_REDIRECTS

### Steps to reproduce

<img width="896" alt="image" src="https://github.com/MISP/MISP/assets/3220193/ff085107-5023-45eb-a540-0235e31fa069">

<img width="778" alt="image" src="https://github.com/MISP/MISP/assets/3220193/e71d1576-9d3f-4f96-8773-20898169ac75">

<img width="783" alt="image" src="https://github.com/MISP/MISP/assets/3220193/76e01860-d000-4025-b304-d9046fc1a192">

<img width="832" alt="image" src="https://github.com/MISP/MISP/assets/3220193/b9e6f2f5-3c91-4726-9739-10458ddb6eb8">

<img width="599" alt="image" src="https://github.com/MISP/MISP/assets/3220193/a5f5c45d-f740-4a09-89ea-514adc8f5392">

### Version

2.4.171

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

PHP Settings PHP ini path:… /etc/php.ini PHP Version (>7.4 recommended): 7.4.33 (Up to date) PHP CLI Version (>7.4 recommended): 7.4.33 (Up to date)

### Browser

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks for the detailed description, it was indeed a bug with the way we did url rewriting. 

It should be resolved now via these 2 commits:

48c8357c00083078ed04743b2e440832a05817d2
736d794681fb93e86833ca074a003a900e004168

I've made it a bit restrictive still, it will specifically allow for spaces but might still fail on some other characters - if you come across anything that should be handled in rewrites without decoding, don't be shy!
