### ISSUE TITLE
Bug: Attributes index paginator displays incorrect "last" page number

### ISSUE THREAD

**Issue by briggjo** [MISP/MISP#9156]
### Expected behavior

"last>>" link should take you to the last page of attributes

### Actual behavior

Clicking the "last>>" link takes you to a page not found error. 
"Last >>" link in the paginator points to page:153722867280912928, which appears to be PHP_MAX_INT divided by the page limit of 60.

### Steps to reproduce

Have more than 60 attributes present (across any number of events) so that pagination occurs on the List Attributes page.
Navigate to Event Actions -> List Attributes
Observe/click the "Last>>" link

I believe this issues was introduced by switch to LightPaginator:
https://github.com/MISP/MISP/commit/709a9e270aef06b9b8d61c3973338ef0e47a5f68

### Version

2.4.172

### Operating System

RHEL

### Operating System version

8

### PHP version

7.4

### Browser

Chrome

### Browser version

114

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
fixed via https://github.com/MISP/MISP/commit/ff5707cd652c387a65d4b8065991b85aaecc1192, last button should not be shown if using light paginator
