### ISSUE TITLE
Bug: MISP/attributes/search no pagination: only displays page 1 when there are 29k attribute matches

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9157]
### Expected behavior

When searching a long list of IPs inserted into the `"Containing the following expressions"` textbox on `MISP/attributes/search` the `MISP/attributes/search/results` page should display a paginated set of results pages.

### Actual behavior

With 2.4.172 the `MISP/attributes/search/results` page displays only page 1 without an pagination. However, the `"Export found attributes as…"` button on the bottom of that results page creates a JSON download file containing 29k matches.

### Steps to reproduce

As above.

### Version

2.4.172

### Operating System

RH

### Operating System version

8.8

### PHP version

7.4.33

### Relevant log output

```shell
Nothing is written to any log files in `/var/www/MISP/app/tmp/logs`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Btw, this bug was introduced in 2.4.172 as the paginated result set works fine in 2.4.171. Thanks.

**Comment by github-germ** [comment]
This lack of pagination bug persists in 2.4.173. Any chance to get to it for 2.4.174? Thanks.

**Comment by righel** [comment]
Fixed by https://github.com/MISP/MISP/pull/9211

**Comment by github-germ** [comment]
@righel I applied your patch to those 2 files manually (base version is 2.4.173), ran my test case of 29k IPs in search attrs, and still no pagination.

**Comment by github-germ** [comment]
@righel Indeed this patch does work. Sorry, I was looking for the full paginator with all the pages shown. Now with the loght paginator we see a simpler navogation with
![image](https://github.com/MISP/MISP/assets/8812009/076379f0-8f20-43d2-8789-e23a9dbb8d1a)

**Comment by righel** [comment]
FYI the last button will be removed too in the new release (as it does not make sense anymore because we don't know how many pages there are)

**Comment by github-germ** [comment]
@righel This works. Thanks. I do see this warning in `error.log` when pasting in my test case 29k IPs into the search expression:
```
2023-07-29 13:36:16 Warning: Warning (2): array_map() [<a href='http://php.net/function.array-map'>function.array-map</a>]: Expected parameter 2 to be an array, null given in [/var/www/MISP/app/View/Attributes/search.ctp, line 76]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
array_map - [internal], line ??
include - APP/View/Attributes/search.ctp, line 76
View::_evaluate() - APP/Lib/cakephp/lib/Cake/View/View.php, line 971
View::_render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 933
View::render() - APP/Lib/cakephp/lib/Cake/View/View.php, line 473
Controller::render() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line\
 968
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99
```

**Comment by righel** [comment]
This seems to be unrelated, does it happen all the time? Or only with big searches?
29k IPs is definitely a lot and would create an immense sql query as a result, can you split the task in smaller searches?

**Comment by github-germ** [comment]
Just installed 2.4.174. Not seeing that warning for large or small search attribute data sets now. Thanks!!
