### ISSUE TITLE
Create three composite attributes (filename|md5, filename|sha1 & filename|sha256) + separate malware sample attribute

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#916]
Create three composite attributes (filename|md5, filename|sha1 & filename|sha256) + a malware sample with just the file as attachement.

The use case if for an organisation wants to share externaly the metadata but not the malware samples themselves by keeping the distribution of malware file to _your org only_.

**Comment by adulau** [comment]
It's maybe something to review within the current upload model and the changes introduced in 2.4.80 with objects.
