### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#9181]
### Support Questions

I need advice on keeping the 'logs' table to a reasonable size, it seems to grow to 55GB or so in just a week or two. 

Fighting through mysql timeouts, after some work I'm able to clear the table down to 10 days with this script -- 

```
#!/bin/bash
echo "Running Script to delete logs"
mysql -u root  << EOF
use misp;
DELETE FROM logs WHERE created < DATE_SUB(NOW(), INTERVAL 10 DAY);
EOF
```

And then reclaiming the space with one of these:
```
ALTER TABLE logs ENGINE=InnoDB;
(or)
OPTIMIZE TABLE `logs`;
```

I don't want to totally disable the logs, but I can't figure out what's going on.  

I'll clear it down to 10 days of logs and then after a week or so it bounces back up to 55GB.

![image](https://github.com/MISP/MISP/assets/5932961/5237218c-95b5-45e1-865b-545eb1eae392)

Does anyone have a script they're using or anything that could help me?  I'd appreciate or take any suggestions.  

Thanks! 

### MISP version

2.4.171

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincenzocaputo** [comment]
I would suggest you to pull out more statistics on the log table by filtering by 'model' and 'action' columns. This information might give some hints on which operation logs the most.

See also [#4735](https://github.com/MISP/MISP/issues/4735#issuecomment-644058669).

**Comment by mathurin68** [comment]
Thanks @vincenzocaputo, I'll take a look!

**Comment by mathurin68** [comment]
This seems to be working for me, fingers crossed! 

```
#!/bin/bash
echo "Running Script to delete logs"
mysql -u root  << EOF
use misp;
DELETE FROM logs WHERE created < DATE_SUB(NOW(), INTERVAL 7 DAY);
ALTER TABLE logs ENGINE=InnoDB;
EOF
```
I have it set on a cronjob every 24 hours, seems to be working, but I haven't turned all our feeds back on.  

Thanks again for the help!!
