### ISSUE TITLE
Feature Request: Create custom warninglist from GUI / API

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#9184]
### Is your feature request related to a problem? Please describe.

Hi,

one of my use cases with MISP is to use custom warninglists.
I am able to create a warninglist and add/remove values from terminal

### Describe the solution you'd like

I would like to create new warninglist and add/remove entries from the web UI or (even better) using APIs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Good news. You can absolutely do that. When you view the warninglists, you have an add warninglist button on the right side menu. Also, you can edit any custom warninglists you have created and change the list of values within the list.

**Comment by pietrogu** [comment]
Is it also possible using APIs?

**Comment by cudeso** [comment]
Maybe this is useful? It demonstrates how to create or update a warninglist via Python code, interacting with the API: https://github.com/MISP/misp-playbooks/blob/main/misp-playbooks/pb_create_custom_MISP_warninglist-with_output.ipynb

**Comment by iglocska** [comment]
Sure is. 

POST to /warninglists/add

```
{
    "Warninglist": {
        "name": "my new test warninglist2",
        "matching_attributes": ["ip-dst", "ip-src"],
        "type": "string",
        "version": 1,
        "description": "my brand new warninglist for testing",
        "entries": "8.8.8.8\n8.8.4.4\n1.1.1.1"
     }
}
```

To update the list, POST to /warninglists/edit/[id]

```
{
    "entries": "8.8.8.8\n8.8.4.4\n1.1.1.1\n9.9.9.9"
}
```

**Comment by iglocska** [comment]
Ah damn, @cudeso - just saw your message, that's a much cleaner way of showing it, thanks!

**Comment by pietrogu** [comment]
Thank you!
