### ISSUE TITLE
Issue with filter taxonomies details

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#920]
If you browse a certain taxonomy like:
https://misp/taxonomies/view/1

and filter the list of results and the result list has more then one page and then trying to access the second page will delete the filter.

MISP Version: 2.4.14
Tested with: VERIS Taxonomy Library

```
taxonomies/view/9/filter:asset
```

Because the link for page two is:

```
taxonomies/view/9/page:2
```

but should be:

```
taxonomies/view/9/page:2/filter:asset
```

Guess that should be easy to fix but have no time to find the right spot in code, but it should be in:

```
app/View/Taxonomies/view.ctp
```

For events it is doing right

**Comment by iglocska** [comment]
thanks for the heads-up!
