### ISSUE TITLE
Bug: TOTP initialization seed is always the same

### ISSUE THREAD

**Issue by Tr33beard0** [MISP/MISP#9220]
### Expected behavior

I was showing the new MISP feature of TOTP (https://www.misp-project.org/2023/06/13/MISP.2.4.172.released.html/) to my team. I was sharing screen and one of my colleagues out of fun did a screenshot of QR code for TOTP. I did not finished TOTP initialization and cancel it. When I was trying it again it gave me same QR code (=same initialization seed for TOTP).
I would expect that this would be generated at moment of initialization and not fixed.

### Actual behavior

Initial seed for account is fixed and not changing.So it seems that initial seed for TOTP is same and not changing in a time for a user. I believe it should be generated in every initialization and not be fixed forever.

It is also tied of missing feature of regenerating of TOTP in case I would find out that somebody stole my initial seed/QR code for TOTP. I would like to be able to cancel TOTP and generate new one.

### Steps to reproduce

Go to Global Actions -> My Profile -> TOTP Generate
See the secret or QR code and then do not finish initialization.
If you go back to Global Actions -> My Profile -> TOTP Generate
You will see same secret/QR code.

### Version

2.4.173

### Operating System

Ubuntu

### Operating System version

20.04.6 LTS

### PHP version

7.4.3

### Browser

Not related to specific browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
Thank you for finding and reporting this. The key was indeed not changed if a user logged out and another user used the same browser. This has been corrected by @iglocska at ninja-speed.
