### ISSUE TITLE
Support: Clarification about the new password forgot feature

### ISSUE THREAD

**Issue by ahmedxuae91** [MISP/MISP#9223]
### Support Questions

Hi Team,

I have a question regarding the below statement for the new password reset feature:

"The feature requires the user to have a valid encryption key "

What this means exactly and how user can generate an encryption key?

I have tested the new feature but didn't receive any email in my inbox although mails are configured properly and I am getting the email when clicking on reset password manually from the admin user.

### MISP version

2.4.173

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Hello,

I haven't used this new feature myself yet, but I believe what they mean is that you need to have a pgp key for the user to be able to use this feature. This will ensure that the e-mail with the temporary password is sent as encrypted mail.

You can set the PGP key when adding/editing a user:
![image](https://github.com/MISP/MISP/assets/9868873/72910af6-4c80-4a42-9cc7-c76db5884b31)

For how to create and use pgp keys, I would recommend you to google / search guides online. Depending on your OS and e-mail client the options are different.

Hope this helps.
