### ISSUE TITLE
Support: WebHook header for Authentication

### ISSUE THREAD

**Issue by marcoportoni** [MISP/MISP#9231]
### Support Questions

When using Workflow and in particular Webhook to send a published event, how can I add an authentication header to the Webhook? I haven't found a way to add custom header to the request in order to authenticate it. Is there something I am missing? 

### MISP version

2.4.169

### Operating System

MacOS

### Operating System version

Ventura 13.4.1

### PHP version

7.4.3

### Browser

Firefox

### Browser version

115.0.3

### Extra attachments

![Screenshot 2023-08-03 alle 09 08 16](https://github.com/MISP/MISP/assets/53291043/45518e47-6928-4ae3-b6fa-928f82bec39b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Solved in #9321
