### ISSUE TITLE
MISP cannot connect to the Supervisord API

### ISSUE THREAD

**Issue by sys2733** [MISP/MISP#9232]
Error: Error getting supervisor status.
[LogicException] You cannot use "Http\Message\MessageFactory\GuzzleMessageFactory" as the "php-http/message-factory" package is not installed. Try running "composer require php-http/message-factory". Note that this package is deprecated, use "psr/http-factory" instead

The package psr/http-factory is installed but I still get this message.

![2023-08-03_11-12](https://github.com/MISP/misp-book/assets/50989056/27120d1f-4a20-4806-879e-d8fc2e65b6f7)

'supervisor_host`, `supervisor_port`, `supervisor_user`, `supervisor_password` are correctly configured

Any tips?

**Comment by righel** [comment]
Have you followed the install instructions?
https://github.com/MISP/MISP/blob/2.4/docs/background-jobs-migration-guide.md#install-requirements
The error clearly shows you are missing a php dependency

**Comment by sys2733** [comment]
The installation was done according to the instructions. I have just done the installation again, unfortunately the same problem...

I guess the best thing to do is to start again.... Or are there any other tips?

**Comment by sys2733** [comment]
> The installation was done according to the instructions. I have just done the installation again, unfortunately the same problem...
> 
> I guess the best thing to do is to start again.... Or are there any other tips?

Unfortunately, a complete reinstallation of the server did not help either... What I forgot to say is that the server is running CentOS Stream. Does anyone have experience with a Misp environment and CentOS Stream?
