### ISSUE TITLE
Support: Will last PyMISP 3.8 supported version still work with MISP Server Jan 2024

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9234]
### Support Questions

We have many users of PyMISP across many systems here that in order to move to Python 3.10 will need to upgrade to RH8: a rather large impact.

**Will the last supported PyMISP version that is based on Python 3.8 still work from the client side talking to MISP after the 1/1/2024 cutover?**

This would allow some extra time for systems that are challenged to meet the 12/31/2023 deadline.

We imagine that there might be some new features that may not be available in the older, last PyMISP 3.8 version, but this may still work for us for those needing a bit more time.

Thanks!

### MISP version

2.4.174

### Operating System

RH

### Operating System version

8.8

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
Python 3.8 is EOL on 14 Oct 2024. Please make sure you update your systems on time. If you can't, it might be possible to do something until end of 2024 via the professional services, but no promises. And definitely not in 2025.

If worse comes to worse, the very last PyMISP version compatible with Python 3.8 will still be available on pip and will keep working with the similar version of MISP.

**Comment by github-germ** [comment]
@Rafiot Thx for your reply. Clarifying question please.
* If some systems using PyMISP here are delayed after 1/1/2024 by say a month or two (at most), if they use the last PyMISP 3.8 version will that only work with the MISP server version that paralleled that PyMISP, e.g. PyMISP is 2.4.199, then MISP server cannot be 2.4.200?

**Comment by Rafiot** [comment]
[This only applies for MISP 2.4.X] We won't remove support for Python 3.8 immediately on 1/1/2024. This warning is there to make sure people don't sleep on it for too long, my guess is that we won't completely remove the python 3.8 package before it becomes EOL.

At worse, if you use a PyMISP version older than MISP, you'll not have the new functionalities offered by the new MISP release, but it won't break.

**Comment by github-germ** [comment]
Thanks
