### ISSUE TITLE
Feature Request: Increase db event_reports.content from type text to mediumtext

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9236]
### Is your feature request related to a problem? Please describe.

We are storing `mardownify`:ed reports as Event Reports. Currently, the `content` column in the db `event_reports` table is type `text` with max of 64k chars. We have reports that are larger which triggers this error and the `pymisp.add_event_report` fails.
```
Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1
```

### Describe the solution you'd like

Would you consider changing the type of the `content` column in the `event_reports` table from `text` (64k) to the next size of `mediumtext` (16M)?

### Describe alternatives you've considered

An alternative is to sklice the incoming report into multiple Event Reports. We'd prefer to have it all in one report.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by github-germ** [comment]
Revisiting... Any chance of getting this 2.4.178? Thanks.

**Comment by XGREENi3** [comment]
Following, as I am sufering from the same issue

**Comment by github-germ** [comment]
Schema change in 2.4.182 possible? Thanks!!

**Comment by iglocska** [comment]
That's quite the oversight indeed. We'll increase it

**Comment by iglocska** [comment]
Should be fixed

**Comment by github-germ** [comment]
Aha, yes it is fixed. Thanks...
```
mysql> desc event_reports content;
+---------+------------+------+-----+---------+-------+
| Field   | Type       | Null | Key | Default | Extra |
+---------+------------+------+-----+---------+-------+
| content | mediumtext | YES  |     | NULL    |       |
+---------+------------+------+-----+---------+-------+
```
