### ISSUE TITLE
Support: Why does a 2nd browser request hang until the first completes?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9239]
### Support Questions

**Is there some sort of single threading lock mechanism in place that prevents two browser requests from the same user on the same client computer to run concurrently and independently without one waiting for the other?**

- If so, is that implemented fully on the server side or perhaps via browser javascript token or the like? And curious on how long this has been the normal behavior (I've not seen it before, but some of our power users are now reporting this).
- If this is NOT the expected behavior, i.e. both browsers should process and respond independently, then what can we collect and share to try to find root cause?

**Use Case:**
1. Open two browsers accessing MISP WebUI (two windows or two tabs).
2. Browser-1: Initiate a request that requires a long processing time, e.g. viewing a very large event.
3. Browser-2: While Browser-1 is processing its request, initiate a request that usually responds fast, e.g. List Tags.

**Observations:**
A. Browser-1 is spinning wheel processing long request.
B. Browser-2 is spinning wheel also, but should've responded already.
C. Browser-1 response completes.
D. Only after Browser-1 completes does Browser-2 complete.

### MISP version

2.4.174

### Operating System

RH

### Operating System version

8.8

### PHP version

7.4.33

### Browser

Chrome

### Browser version

Version 115.0.5790.170 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eowyn263** [comment]
Check what you have as Session Handler in the Diagnostic page. It can happen if you're using files. Don't have this problem when using redis

**Comment by github-germ** [comment]
@eowyn263 Thanks! Indeed we are using files. We had trouble in the past moving to redis. We will revisit. Prior issue: #8993 -- any advice on getting redis working is appreciated.

**Comment by righel** [comment]
I think we can close this and keep working on a solution for redis on #8993
