### ISSUE TITLE
Bug: MISP core and modules install are getting flagged by Defender EDR as Malware

### ISSUE THREAD

**Issue by 1holygrail** [MISP/MISP#9241]
### Expected behavior

Clean install of MISP without EDR flagging files as malware!

### Actual behavior

- On 2 separate clean Ubuntu 22.04 LTS Server boxes installed MISP core and MISP with all modules etc. respectively following these guidelines:
https://misp.github.io/MISP/xINSTALL.ubuntu2204

However after installing MISP, as above, ran a Defender AV scan which is flagging below files as malware:
=============================
/var/www/.cache/pip/wheels/b3/2c/1a/39948bb3cf574f3df6d49f5ebe957ad3ec657bd8be46ee603a/misp_stix-2.4.172-py3-none-any.whl

/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/data/cti/enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json

/var/www/MISP/venv/lib/python3.10/site-packages/misp_stix_converter/data/cti/enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json

/var/www/MISP/PyMISP/tests/viper-test-files/test_files/9afa90370cfd217ae1ec36e752a393537878a2f3b5f9159f61690e7790904b0d

/var/www/MISP/PyMISP/tests/viper-test-files/test_files/Douglas-Resume.doc

/var/www/MISP/PyMISP/tests - [all email tests and viper tests folder files]
=============================

Can someone please shed light on this issue? Have you faced this issue?

The only solution I can think of is to install MISP core on a fresh box, then manually remove all the files mentioned above. This seems counterproductive

Keen to hear anyones thoughts and how you have solved this issue

Is it possible to repackage the MISP app without the files above?

Most importantly, can someone confirm that MISP installation, regardless of Core or with All Modules is safe to use in production environment?

Please and thank you!

### Steps to reproduce

- Create a Ubuntu 22.04 VM
- Install MISP core following steps on link : https://misp.github.io/MISP/xINSTALL.ubuntu2204 [wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh ; bash /tmp/INSTALL.sh -c]
- Run Defender or CrowdStrike EDR scan on the machine
- You will get hits for malware for files mentioned above

### Version

2.4.174

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Issue is with files on Linux box not on browser

### Browser version

N?A

### Relevant log output

```shell
Files in locations below flagged by Defender AV as malware:

=============================
/var/www/.cache/pip/wheels/b3/2c/1a/39948bb3cf574f3df6d49f5ebe957ad3ec657bd8be46ee603a/misp_stix-2.4.172-py3-none-any.whl

/var/www/MISP/app/files/scripts/misp-stix/misp_stix_converter/data/cti/enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json

/var/www/MISP/venv/lib/python3.10/site-packages/misp_stix_converter/data/cti/enterprise-attack/relationship/relationship--2610bdef-0b08-46a8-94f5-cf253f11e5fc.json

/var/www/MISP/PyMISP/tests/viper-test-files/test_files/9afa90370cfd217ae1ec36e752a393537878a2f3b5f9159f61690e7790904b0d

/var/www/MISP/PyMISP/tests/viper-test-files/test_files/Douglas-Resume.doc

/var/www/MISP/PyMISP/tests - [all email tests and viper tests folder files]
=============================
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1holygrail** [comment]
For anyone reading this, it might help to know that I solved my problem using the below steps:

- Install Ubuntu server
- onboard EDR solution of your choice
- install MISP Core only
- removed unwanted files and folder from locations [as per my post above]
- ran full AV scan [no threat warnings]
- logged on web GUI of MISP
- enabled and fetched a few feeds
- ran AV scan again on Linux box [no threats were found]


Request: whoever is maintaining the build, it would be great if you could remove the files i mentioned above and repackage the MISP install files, for everyone's benefit

Many thanks

**Comment by righel** [comment]
See https://github.com/MISP/MISP/issues/9252#issuecomment-1691260469
