### ISSUE TITLE
Support: Update Failing

### ISSUE THREAD

**Issue by CrzyDvl** [MISP/MISP#9243]
### Support Questions

Hi Team,
Our MISP is failing to be updated to the latest version it shows and I am not really sure how to get it updated. Am looking for some assistance here. 
Thanks

### MISP version

v2.4.172

### Operating System

RHEL

### Operating System version

8.7

### PHP version

7.4.33

### Relevant log output

```shell
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

Updated 0 paths from the index

cd $(git rev-parse --show-toplevel) && git pull origin '2.4' 2>&1

Updated 0 paths from the index
From https://github.com/MISP/MISP
 * branch                2.4        -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	app/composer.phar
Please commit your changes or stash them before you merge.
Aborting
Updating 648c1c9ea..3c097f820

=================================

cd $(git rev-parse --show-toplevel) && git submodule sync 2>&1

Synchronizing submodule url for 'PyMISP'
Synchronizing submodule url for 'app/Lib/cakephp'
Synchronizing submodule url for 'app/files/misp-decaying-models'
Synchronizing submodule url for 'app/files/misp-galaxy'
Synchronizing submodule url for 'app/files/misp-objects'
Synchronizing submodule url for 'app/files/misp-workflow-blueprints'
Synchronizing submodule url for 'app/files/noticelists'
Synchronizing submodule url for 'app/files/scripts/cti-python-stix2'
Synchronizing submodule url for 'app/files/scripts/misp-opendata'
Synchronizing submodule url for 'app/files/scripts/misp-stix'
Synchronizing submodule url for 'app/files/scripts/mixbox'
Synchronizing submodule url for 'app/files/scripts/python-cybox'
Synchronizing submodule url for 'app/files/scripts/python-maec'
Synchronizing submodule url for 'app/files/scripts/python-stix'
Synchronizing submodule url for 'app/files/taxonomies'
Synchronizing submodule url for 'app/files/warninglists'
Synchronizing submodule url for 'misp-vagrant'

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrzyDvl** [comment]
Currently installed version… v2.4.172 (648c1c9ea21b85e2d360033a65882fe33c8b9bbe)
Latest available version… v2.4.174 (3c097f82021c745583ee2e142853c521ccd49118)
Status… Outdated version
Current branch… 2.4

**Comment by adulau** [comment]
`error: Your local changes to the following files would be overwritten by merge: app/composer.phar`

You have local changes in your repo. You can reset to the previous state and `git pull` again.

**Comment by CrzyDvl** [comment]
Thank you for your response mate.

I am not sure how to reset to the previous state? Can you please provide more info on that.

Thanks

**Comment by adulau** [comment]
if you have nothing important uncommitted, a `git reset --hard` will do the job

**Comment by CrzyDvl** [comment]
Is it possible to have a UI based solution? Not much familiar with using git

**Comment by CrzyDvl** [comment]
Also, will it be possible to check what is uncommitted using the UI?

**Comment by adulau** [comment]
There is the update via the UI but if you touch the local files ;-) it's not really up to us what you did on your local installation.
