### ISSUE TITLE
Bug: Audit log navigation to subsequent page fails with 'An Internal Error Has Occurred.'

### ISSUE THREAD

**Issue by dwe2e** [MISP/MISP#9245]
### Expected behavior

Using the 'Next' navigation button at the bottom of an Audit log page (example: https://<fqdn>/audit_logs/eventIndex/<eventid> should navigate to the next page of Audit log entries.

### Actual behavior

Page redirects to https://<fqdn>/audit_logs/eventIndex/page:2 (omitting the event reference) and displays the  'An Internal Error Has Occurred.' message.

### Steps to reproduce

Log in to MISP instance with any account level (tested with 'Publisher, Org Admin & Site Admin roles); navigate to Audit logs and select specific event; click 'Next' at the bottom of the page. Page redirects to https://<fqdn>/audit_logs/eventIndex/page:2 (omitting the event reference).

### Version

2.4.174

### Operating System

Ubuntu 

### Operating System version

22.04LTS

### PHP version

7.4.33

### Browser

Chrome

### Browser version

115.0.5790.171 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dwe2e** [comment]
Also re-created in Firefox 116.0.2 (64-bit)

**Comment by righel** [comment]
fixed on  `develop` via https://github.com/MISP/MISP/commit/7c3914a4be626f7d311c857e8ca16f2762fcd767
