### ISSUE TITLE
Support: 2FA Doesn't work, locked out

### ISSUE THREAD

**Issue by iluzdd** [MISP/MISP#9249]
### Support Questions

Hello,

I enabled OTP with email and wanted to check if it works, so I logged out and tried to login again and there is a problem with sending the OTP to my email "The email couldn't be sent, please reach out to your administrator."
Now, I'm locked out of my MISP account, and I'm the administrator and the creator of the environment.

It is important to note that the environment is still new and empty, so if there is a solution to just reset the whole thing, that's also fine with me.

What to do?
Update: I couldn't wait, so I've tried to reinstall MISP and now the MISP is not working and I'm stuck on installation phase
"cmake is already the newest version (3.16.3-1ubuntu1.20.04.1).
libcaca-dev is already the newest version (0.99.beta19-2.1ubuntu1.20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
"

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
You can disable OTP using the CLI by running the following command:
`sudo -u www-data /var/www/MISP/app/Console/cake Admin setSetting Security.email_otp_enabled 0`

Hope this helps.

**Comment by saymynameapoorv16** [comment]
Thanks, this was a life saver !!
