### ISSUE TITLE
Import module to get MISP JSON files from HTTP/TLS servers

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#925]
Import module to get MISP JSON files to sync events.

The proposal is to provide a public MISP OSINT feed that can be an nice import module configured
by default that user can enable to use and test their MISP instances.

The import module is a simple HTTP/TLS client to get a directory of JSON files and import all the listed JSON files. That would also allow some organization to publish MISP JSON events pub

**Comment by elhoim** [comment]
No ACL for it? Then will it only publish events with distribution "all communities"?

**Comment by iglocska** [comment]
I guess it would make sense to have that as a configuration for the module,
so the admin pulling the OSINT feed can set the distribution level.

**Comment by elhoim** [comment]
Might be related to #677 depending on how you want to implement it.

**Comment by iglocska** [comment]
Feed system implemented a while ago.
