### ISSUE TITLE
Feature Request: MISP artefacts stored in DB rather than on filesystem

### ISSUE THREAD

**Issue by 1holygrail** [MISP/MISP#9252]
### Is your feature request related to a problem? Please describe.

Hi All,

Happy to be corrected if my thinking is not right here.

I have Defender deployed on a Linux box that has MISP instance installed. My understanding is that any IOCs, artefacts etc that you collect from the modules are stored on the Linux boxes' filesystem and not in the MISP DB. Is this correct?

If yes, then my problem is that every time I run a full AV scan, my Defender screams there are threats on the box and quarantines artefacts.

Can this be rectified easily by a configuration setting in MISP itself, or is there more to this?

Ideally, I would want to continue using MISP but also have Defender or CrowdStrike EDR installed on the box without getting false positive alerts.

I believe the other issue I posted is linked to this feature above, happy to close the below bug if the above is answered :)
https://github.com/MISP/MISP/issues/9241

Thank you

### Describe the solution you'd like

Any recommendations from the community is welcome

### Describe alternatives you've considered

I have disabled attachments storing location in MISP to _null_ and also changed the "download_attachments_on_load" to _false_

Hoping this is sufficient for attachments not to be downloaded from modules used, hence no alerts generated via EDR

But is this enough?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
I would suggest you to add the files included in the MISP repository into the ignore list of the EDR/AV systems, MISP relies on this files being accessible in the filesystem. 
For malware samples they should be check the "Is a malware sample (encrypt and hash)" checkbox so the attachment is stored a as zip file with password.
Keep in mind the MISP platform is meant to shared and store malware.
