### ISSUE TITLE
Support: MISP interface not accessible 

### ISSUE THREAD

**Issue by areebazaidi** [MISP/MISP#9257]
### Support Questions

I have installed MISP on Ubuntu 22.04 using script in https://misp.github.io/MISP/xINSTALL.ubuntu2204

# This will install MISP Core
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c

when I tried to visit https://192.168.x.x (ubuntu VM IP) it generates following errors in /var/www/MISP/app/tmp/logs/error.log

2023-08-22 07:11:08 Error: Fatal Error (1): Uncaught Error: Class "PDO" not found in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php:218
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(270): Mysql->enabled()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(863): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/AppController.php(140): AppController->_setupDatabaseConnection()
#4 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): AppController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): BetterCakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(Error))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(Error))
#9 [internal function]: ErrorHandler::handleException(Object(Error))
#10 {main}
  thrown in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 218]
2023-08-22 07:11:08 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 218)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 218, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

I think the issue is with self signed certificate, I am not familiar with self signed certificate generation, any help would be appreciated

### MISP version

v2.4 maybe? How do I check this

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Seems something went wrong during the install, I would suggest to run:
```
sudo apt install -qy \
  libapache2-mod-php \
  php php-cli \
  php-dev \
  php-json php-xml php-mysql php-opcache php-readline php-mbstring php-zip \
  php-redis php-gnupg \
  php-gd
  ```
  
  And see if that fixes it, otherwise re-run the installer.

**Comment by adulau** [comment]
Maybe some addition input for debugging:

`Uncaught Error: Class "PDO" not found in ` usually means the installation failed or it's not complete. You are most probably missing php-pdo.  You can check by running `php -M` to see if you the module `PDO` is there. If not, it could be the module not loaded (via `extension=pdo_mysql.so`) in php.ini or you are missing the dependency `php-pdo`.
