### ISSUE TITLE
Support: Unable to load new instance of misp on fresh install of Ubuntu

### ISSUE THREAD

**Issue by bradfireborn** [MISP/MISP#9260]
### Support Questions

Unable to load new instance of misp on fresh install of Ubuntu
Receiving error message
After updating system I also receive a new message >  error starting userland proxy 0.0.0.0;80 bind: address already in use

### MISP version

3

### Operating System

Ubunto

### Operating System version

20.04

### PHP version

8.1.2-1ubuntu2.13

### Browser

Firefox

### Browser version

115.0.2

### Relevant log output

```shell
exit status 127 on multiple services
However after updating I noticed a PHP update created a new issue
```

### Extra attachments

<img width="1488" alt="Screenshot 2023-08-22 at 15 43 38" src="https://github.com/MISP/MISP/assets/7088106/8a9aac20-5b68-45a4-9dbe-03a2cfcf2b64">
<img width="1404" alt="Screenshot 2023-08-22 at 15 43 58" src="https://github.com/MISP/MISP/assets/7088106/2dd71d07-ce3a-4d6d-bbe4-7b312c61b4bd">
<img width="1416" alt="Screenshot 2023-08-22 at 15 44 14" src="https://github.com/MISP/MISP/assets/7088106/467bb956-6662-4c90-8eb5-c39406a7dfd8">
<img width="1189" alt="Screenshot 2023-08-22 at 15 44 47"
<img width="1499" alt="Screenshot 2023-08-22 at 15 48 14" src="https://github.com/MISP/MISP/assets/7088106/b1c7da71-1bf4-4a80-9cff-fa6bb3930a53">
 src="https://github.com/MISP/MISP/assets/7088106/164eb6ba-3b0b-4d9c-b47c-d25e729f0099">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hi @bradfireborn 
Are you using https://github.com/coolacid/docker-misp? If not, which one?

Seems you already have something running on port 80 on your host, comment that port mapping in the `docker-compose.yml` file or stop the webserver thats running in your host machine.

Regarding the workers errors, could you please share the contents of the `./logs/error.log` file?

**Comment by bradfireborn** [comment]
I am using > https://github.com/ostefano/docker-misp

Regarding port 80 - where could I redefine another port? I don't see that specific line

**Comment by righel** [comment]
You can change the port mapping here:
https://github.com/ostefano/docker-misp/blob/master/docker-compose.yml#L43
For example for mapping the containers port 80 into port 8080 in your host machine, use:
```yml
ports:
  - "8080:80"
  - "443:443"
```

**Comment by bradfireborn** [comment]
port 8080 confirmed configured and thank you
rest of the issues still persist
<img width="1800" alt="Screenshot 2023-08-22 at 20 45 43" src="https://github.com/MISP/MISP/assets/7088106/ef216a2d-66e4-4dde-8b35-5f387008ffdd">

**Comment by righel** [comment]
Could you please  run this command and share the output?
`docker-compose exec misp tail /var/www/MISP/app/tmp/logs/error.log -n 500`

**Comment by bradfireborn** [comment]
parallels@ubuntu-linux-22-04-desktop:~/docker-misp$ docker-compose exec misp tail /var/www/MISP/app/tmp/logs/error.log -n 500
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by righel** [comment]
any idea what's going on here @ostefano ?

**Comment by ostefano** [comment]
Why the bug is flagged affecting MISP 3 and php 8?

@bradfireborn  can you remove (not just stop, remove also) all containers and start from a freshly cloned repo?

Also can you post the .env file and docker-compose you are using (after cloning the repo).

**Comment by ostefano** [comment]
Also @bradfireborn why are you running Docker inside Linux inside OSX? That is unnecessarily complicated. Just run Docker natively and run the container from OSX.

**Comment by bradfireborn** [comment]
Hi @ostefano 
Following your instructions
Using Docker dashboard i pulled and set up the docker
The docker is running on 0.0.0.0:6666
However when I visit localhost:port the page is blank

<img width="1125" alt="Screenshot 2023-08-24 at 19 49 19" src="https://github.com/MISP/MISP/assets/7088106/daabfd9c-dc1b-4ae4-848c-dcc4c613a784">
<img width="1509" alt="Screenshot 2023-08-24 at 19 51 10" src="https://github.com/MISP/MISP/assets/7088106/8b2d05b7-86a6-4eff-934f-e2bf00e70d98">

**Comment by ostefano** [comment]
That's the misp-modules container. The misp container is another one.

**Comment by bradfireborn** [comment]
Went back to 0 and RTFM

Pulled ostefano modules, up and running 0.0.0.0:6666 [can i change this port somehow to prevent unsafe port error?]
Followed instructions here https://blogs.vmware.com/security/2023/01/how-to-deploy-a-threat-intelligence-platform-in-your-data-center.html
Did pull/build

adjusted port to 6666:80 in docker-compose.yml

<img width="1233" alt="Screenshot 2023-08-24 at 20 32 35" src="https://github.com/MISP/MISP/assets/7088106/d1e957d0-e261-4642-bca2-47b38785d68c">

@MacBook-Pro docker-misp % sudo docker-compose exec misp tail /var/www/MISP/app/tmp/logs/error.log -n 500
WARN[0000] The "MISP_COMMIT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MODULES_COMMIT" variable is not set. Defaulting to a blank string.
tail: cannot open '/var/www/MISP/app/tmp/logs/error.log' for reading: No such file or directory

**Comment by ostefano** [comment]
I haven't tested it with a different port mapping and AFK atm. Can you test it without changing the port?

**Comment by bradfireborn** [comment]
Output of docker-compose.yml

@MacBook-Pro docker-misp % cat docker-compose.yml
version: '3'
services:
  # This is capable to relay via gmail, Amazon SES, or generic relays
  # See: https://hub.docker.com/r/ixdotai/smtp
  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"

  redis:
    image: redis:5.0.6

  db:
    # We use MariaDB because it supports ARM and has the expected collations
    image: mariadb:10.8.2
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log

  misp:
    image: ostefano/misp-docker:core-latest
    build:
      context: server/.
      args:
          - MISP_TAG=${MISP_TAG}
          - MISP_COMMIT=${MISP_COMMIT}
          - PHP_VER=${PHP_VER}
    depends_on:
      - redis
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files/"
      - "./ssl/:/etc/nginx/certs/"
      - "./gnupg/:/var/www/MISP/.gnupg/"
      # customize by replacing ${CUSTOM_PATH} with a path containing 'files/customize_misp.sh'
      # - "${CUSTOM_PATH}/:/custom/"
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "CRON_USER_ID=${CRON_USER_ID}"
      # standard settings
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      # sync server settings (see https://www.misp-project.org/openapi/#tag/Servers for more options)
      - "SYNCSERVERS=${SYNCSERVERS}"
      - |
        SYNCSERVERS_1_DATA=
        {
          "remote_org_uuid": "${SYNCSERVERS_1_UUID}",
          "name": "${SYNCSERVERS_1_NAME}",
          "authkey": "${SYNCSERVERS_1_KEY}",
          "url": "${SYNCSERVERS_1_URL}",
          "pull": true
        }

  misp-modules:
    image: ostefano/misp-docker:modules-latest
    build:
      context: modules/.
      args:
        - MODULES_TAG=${MODULES_TAG}
        - MODULES_COMMIT=${MODULES_COMMIT}
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis

volumes:
    mysql_data:

**Comment by bradfireborn** [comment]
output of template.env

@MacBook-Pro docker-misp % cat template.env
MISP_TAG=v2.4.174
MODULES_TAG=v2.4.174
PHP_VER=20190902

# MISP_COMMIT takes precedence over MISP_TAG
# MISP_COMMIT=c56d537
# MODULES_COMMIT takes precedence over MODULES_TAG
# MODULES_COMMIT=de69ae3

# Email/username for user #1, defaults to MISP's default (admin@admin.test)
ADMIN_EMAIL=
# name of org #1, default to MISP's default (ORGNAME)
ADMIN_ORG=
# defaults to an automatically generated one
ADMIN_KEY=
# defaults to MISP's default (admin)
ADMIN_PASSWORD=
# defaults to 'passphrase'
GPG_PASSPHRASE=
# defaults to 1 (the admin user)
CRON_USER_ID=
# defaults to 'https://localhost'
HOSTNAME=

# optional and used by the mail sub-system
SMARTHOST_ADDRESS=
SMARTHOST_PORT=
SMARTHOST_USER=
SMARTHOST_PASSWORD=
SMARTHOST_ALIASES=

# optional comma separated list of IDs of syncservers (e.g. SYNCSERVERS=1)
# For this to work ADMIN_KEY must be set, or AUTOGEN_ADMIN_KEY must be true (default)
SYNCSERVERS=
# note: if you have more than one syncserver, you need to update docker-compose.yml
SYNCSERVERS_1_URL=
SYNCSERVERS_1_NAME=
SYNCSERVERS_1_UUID=
SYNCSERVERS_1_KEY=

# These variables allows overriding some MISP email values.
# They all default to ADMIN_EMAIL.

# MISP.email, used for notifications. Also used
# for GnuPG.email and GPG autogeneration.
# MISP_EMAIL=

# MISP.contact, the e-mail address that
# MISP should include as a contact address
# for the instance's support team.
# MISP_CONTACT=

# Enable GPG autogeneration (default true)
# AUTOCONF_GPG=true

# Enable admin (user #1) API key autogeneration
# if ADMIN_KEY is not set above (default true)
# AUTOGEN_ADMIN_KEY=true

**Comment by bradfireborn** [comment]
Status
<img width="1283" alt="Screenshot 2023-08-25 at 09 13 50" src="https://github.com/MISP/MISP/assets/7088106/e4a73394-9d62-4911-98e4-8369c6ace8fc">

**Comment by bradfireborn** [comment]
@MacBook-Pro docker-misp % sudo docker-compose exec misp tail /var/www/MISP/app/tmp/logs/error.log -n 500
WARN[0000] The "MISP_COMMIT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MODULES_COMMIT" variable is not set. Defaulting to a blank string.
tail: cannot open '/var/www/MISP/app/tmp/logs/error.log' for reading: No such file or directory

**Comment by bradfireborn** [comment]
hello @ostefano @righel any updates here by chance? thanks

**Comment by ostefano** [comment]
It's on my todo list 👍

**Comment by ostefano** [comment]
@bradfireborn please format config files appropriately, otherwise I can't see what is commented.

The file `docker-compose.yml` has no modifications, is that intended?

Did you you copy the file `template.env` to `.env` (you are showing the output of `template.env` hence the question)?

**Comment by ostefano** [comment]
@bradfireborn any update here?

**Comment by bradfireborn** [comment]
Hi @ostefano > yes i copied template.env to .env > which output would you like to have?
I have not made modifications to docker-compose as I'm not sure what to change specifically and have kept it without too many modifications as I'm unsure on dependencies, any advice here would be appreciated

**Comment by bradfireborn** [comment]
The intention pre-set up is to get the server + modules itself up and running. 
From there go into further config like access creds etc
however at this point getting the server up and running is the primary issue

**Comment by ostefano** [comment]
> I have not made modifications to docker-compose as I'm not sure what to change specifically and have kept it without too many modifications as I'm unsure on dependencies

Your sentence is not clear.
Specifically `I have not made modifications` and `have kept it without too many modifications` seem to contradict each other.

**Comment by ostefano** [comment]
Having said that, I am not sure I can help. If you followed the guide, the dockerization should work.
Maybe try some alternative as listed here https://www.misp-project.org/download/ ?

**Comment by bradfireborn** [comment]
Yes - so to clarify - I didn't make modifications on the second re-up of the docker following the guide - should it not work from it's basic state?

If not 
what modifications should I make?

If yes
I still can't get it up and running and is showing the same error messages

**Comment by ostefano** [comment]
Once you copy the template file, there is no modification required.

Maybe try to remove all containers, images, and volumes from Docker and try again?

**Comment by bradfireborn** [comment]
@ostefano sure - I will remove everything and start from scratch based on your guide.

**Comment by bradfireborn** [comment]
Hi @ostefano 
Status update
Removed ALL dockers / Images / Containers 
Clean slate

Then followed your guide step by step
I ensured to make no changes to the template and yml 
Unfortunately still unable to deploy
<img width="1178" alt="Screenshot 2023-09-16 at 11 32 07" src="https://github.com/MISP/MISP/assets/7088106/7f3f8f59-b1bc-4ca5-9e8a-f5a2fa2b78be">

Please let me know what I need to provide for support

**Comment by bradfireborn** [comment]
This is as far as I get

<img width="1106" alt="Screenshot 2023-09-16 at 11 45 55" src="https://github.com/MISP/MISP/assets/7088106/665dc7b0-0644-4d0e-993b-b450d6da07ee">

**Comment by ostefano** [comment]
No idea sorry 🤷‍♂️

**Comment by bradfireborn** [comment]
Hello all - are there new instructions for loading up the new MISP updated version on Mac via Docker?

**Comment by ostefano** [comment]
@bradfireborn No, but you can try updating Docker before trying again

**Comment by bradfireborn** [comment]
Understood - attempting now

**Comment by bradfireborn** [comment]
Build successful :-)

**Comment by ostefano** [comment]
@bradfireborn But does it run successfully? :)

In any case, make sure to use the new repository https://github.com/MISP/misp-docker

Note that some variables changed name, so you need to create a brand new `.env` file.

And it might make sense to close this issue, and in case of problems, open one in the misp-docker project.

**Comment by bradfireborn** [comment]
Yes, it's running successfully, I've launched as well as added feeds - so far further than i have ever gone :)

**Comment by ostefano** [comment]
Awesome news :) Let's close this issue then
