### ISSUE TITLE
Support: 

### ISSUE THREAD

**Issue by bradfireborn** [MISP/MISP#9261]
### Support Questions

Unable to launch MISP off Kali - exiting at standing up docker

### MISP version

3

### Operating System

Kali Linux

### Operating System version

latest rolling

### PHP version

8.1.5

### Browser

Firefox

### Browser version

115.0.2esr

### Relevant log output

```shell
misp_web | ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/aarch64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

### Extra attachments

<img width="628" alt="Screenshot 2023-08-22 at 15 52 56" src="https://github.com/MISP/MISP/assets/7088106/bc87a4a2-c472-4410-9afe-143797717780">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Please open this issue in the docker-misp related repository, it is not linked to MISP itself. Also, there is no ongoing effort to support MISP on Kali.
