### ISSUE TITLE
Feature Request: Enforce tags and descriptions to an event or attribute

### ISSUE THREAD

**Issue by adirsabag** [MISP/MISP#9264]
### Is your feature request related to a problem? Please describe.

Our workflow requires specific custom tags for a newly created event, and a description for every attribute. Those have to be mandatory for creating an event/attribute.

### Describe the solution you'd like

I would like to have an option of enforcing tags for events and description for attributes. Every time that someone creates an events, it would be a mandatory to set a specific tag, and the same way for a description while adding an attribute.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Hello @adirsabag 

Regarding required tags, you can currently do this by going to `https://MISP_HOST/taxonomies` and set the tags you want to `required`, the event wont be published unless this tags are present.
![image](https://github.com/MISP/MISP/assets/1659902/614b45bd-fa07-4a50-aeab-b18cb1875abc)
 Additionally you can set some tags as "highlighted" so they are rendered on top of the rest of the tags, see:
https://www.circl.lu/doc/misp/taxonomy/#setting-a-taxonomy-as-highlighted
Alternatively, you can achieve this by using Workflows, see this comment:
https://github.com/MISP/MISP/issues/2067#issuecomment-1234156080

For checking if an attribute description is not empty, the only way to enforce this this is via workflows. I suggest you to take a look of that feature:, some online resources:
https://www.youtube.com/watch?v=OyLE2g4zii0
 
There are also some sample workflow bluprints available, go to  `https://MISP_HOST//workflowBlueprints` click on `Update Default Blueprints` on the menu on the left and check them out.

Hope this helps.
