### ISSUE TITLE
Bug: After updating to v2.4.175 the Add enrichment button for singular attributes returns "Not allowed"

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#9267]
### Actual behavior

1. Save an attribute to the event.
2. Click the Add enrichment button.
3. Pop-up message "Not allowed." appears for few seconds.
4. Error message gets generated to `/var/www/MISP/app/tmp/logs/error.log` file. See below for the error message.

### Expected behavior

I would see the enrichment menu pop-up where I can choose the module to run.

### Steps to reproduce

1. Save an attribute to the event.
2. Click the Add enrichment button.
3. Pop-up message "Not allowed." appears for few seconds.
4. Error message gets generated to `/var/www/MISP/app/tmp/logs/error.log` file. See below for the error message.

### Version

Currently installed version… v2.4.175 (8015ab121a2c49ffe61b540c3cf8c49bcb9ed845)

### Operating System

Ubuntu

### Operating System version

22.04.3 LTS

### PHP version

PHP Version (>7.4 recommended): 7.4.33 (Up to date) PHP CLI Version (>7.4 recommended): 7.4.33 (Up to date)

### Relevant log output

```shell
==> /var/www/MISP/app/tmp/logs/error.log <==
2023-08-24 21:10:11 Error: [MethodNotAllowedException] Attribute services are not enabled.
Request URL: /events/queryEnrichment/1205073/Enrichment/Attribute?_=1692900428260
Stack Trace:
#0 [internal function]: EventsController->queryEnrichment()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#5 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Thanks for the report. There is a indeed an issue. We will look into it.
