### ISSUE TITLE
Support: The notifications title does not contain the description

### ISSUE THREAD

**Issue by isaeed22** [MISP/MISP#9268]
### Support Questions

Hello Everyone,
When an event is published an email will be sent to users and inform them but it does not contain the description in the subject of the email.
In Administration --> Server Settings & Maintenance --> MISP, I have:

Optional | MISP.threatlevel_in_email_subject | true | Put the event threat level in the notification E-mail subject. |  
-- | -- | -- | -- | --
Optional | MISP.email_subject_TLP_string | tlp:amber | This is the TLP string for e-mails when email_subject_tag is not found. |  
Optional | MISP.email_subject_tag | tlp | If this tag is set on an event it's value will be sent in the E-mail subject. If the tag is not set the email_subject_TLP_string will be used. |  
Optional | MISP.email_subject_include_tag_name | true | Include in name of the email_subject_tag in the subject. When false only the tag value is used.

In addition, I do not know how to use "tlp" tag. How a tag can contain a value? 

### MISP version

2.4.175

### Operating System

Ubuntu 

### Operating System version

20.04

### PHP version

7.4.29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
`MISP.extended_alert_subject` is the option you are looking for.
