### ISSUE TITLE
Support: MISP growing in size, feeds are duplicated

### ISSUE THREAD

**Issue by Bilal-SG** [MISP/MISP#9270]
### Support Questions

Hello MISP team!

My MISP instance is growing in size.. I think it happens because feeds are duplicated over and over again into events after each performed update...

Could you please advise how to ensure that feeds aren't duplicated while updating them? Knowing this is the [feeds ](https://raw.githubusercontent.com/MISP/MISP/2.4/app/files/feed-metadata/defaults.json) file I use in my environment and I perform feeds update with REST API command scheduled in a cronjob as in below:

0 1 * * * /usr/bin/curl -XPOST --insecure   --header "Authorization: **YOUR_API_KEY**" --header "Accept: application/json"   --header "Content-Type: application/json"   https://**YOUR_MISP_ADDRESS**/feeds/fetchFromAllFeeds

Thanks!
 

### MISP version

2.4.173

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Have you enabled pulling from all feeds? This no doubts will generate a lot of data, be mindful of which feeds you choose to enable. Additionally you can enable pull rules to pull only recent data (filtering on the `timestamp`).

You can read more about this here: https://www.circl.lu/doc/misp/managing-feeds/

**Comment by Bilal-SG** [comment]
Hello Righel,

Can we add (timestamp filter) to the API request in the cronjob? because if update jobs are reoccurring then timestamp need to be changed based on the interval between fetching requests. 

My point is that I need to automate feeds fetching while ensuring no duplicated events are fed back to the database..

Thank you,

**Comment by righel** [comment]
If the feed is in MISP format, you can add a pull rule (filter) on the timestamp. If its in other format such as CSV, you can't.

**Comment by Bilal-SG** [comment]
Dear Righel,

Can you show me an example of the rule to be configured, please?

**Comment by righel** [comment]
1. Click on `modify` in the Pull rules section
2. In `Addiction sync parameters` add your filtering rules. For example:
Only last 7 days:
```json
{
    "timestamp": "7d"
}
```
After a given date:
```
{
   "searchDatefrom": "2023-09-04"
}
```

Let me know if that helps.

**Comment by Bilal-SG** [comment]
It worked, thanks! 

For other formats such as CSV I just noticed that if we can download the source data file from the feed source and filter on the new attributes, with some scripting, then we can add the new attributes to the corresponding event by initiating such API request as below to update the event with the new attributes:

`curl --header "Authorization: YOUR API KEY " --header "Accept: application/json" --header "Content-Type: application/json" -d '{"event_id":"3542","value":"1.2.3.4","category":"Network activity","type":"ip-dst"}' http://10.50.13.60/attributes/add/3542
`
I think this will be as an acceptable workaround for other formats unless you have better suggestions/advice.. 

Thanks!

**Comment by righel** [comment]
> It worked, thanks!
> 
> For other formats such as CSV I just noticed that if we can download the source data file from the feed source and filter on the new attributes, with some scripting, then we can add the new attributes to the corresponding event by initiating such API request as below to update the event with the new attributes:
> 
> `curl --header "Authorization: YOUR API KEY " --header "Accept: application/json" --header "Content-Type: application/json" -d '{"event_id":"3542","value":"1.2.3.4","category":"Network activity","type":"ip-dst"}' http://10.50.13.60/attributes/add/3542 ` I think this will be as an acceptable workaround for other formats unless you have better suggestions/advice..
> 
> Thanks!

Yes, for CSV feeds thats the only way. If you want to simply the scripting side, I would recommend you to take a look at https://github.com/MISP/PyMISP.

You are welcome.
