### ISSUE TITLE
Connecting 2 misp instances

### ISSUE THREAD

**Issue by Moorocks** [MISP/MISP#9271]
### Support Questions

Hi,
I'm new to MISP and appreciate your help.

I have 2 misp instances which are hosted locally.

Both instances have their emails as admin@admin.test.
Instance A has less threat feeds while Instance B has more threat feeds and events. I want to import all the threat feeds and events from Instance B to Instance A.

As per your documentation, I followed the below steps:

1. Add OrgB as a local organisation on ServerA (OrgB.ServerA) using OrgB's existing UUID from their local organisation on 
ServerB --- I have added local organisation with ID 1 of Instance B to Instance A with the help of UUID.

2. Add a Sync User(syncuser@OrgB.ServerA) in the organisation OrgB.ServerA on the MISP ServerA. -- I have added the user with role of sync user to instance A as test2@admin.test and also setup the password. I used this account to login into instance A and it is working. After this I also created an authkey for this account.

3. Set up a sync server on MISP ServerB using the key (called Authkey) from the sync user (syncuser@OrgB.ServerA) created on MISP ServerA. -- I did this by creating a new server and giving the base url and the api key and setting the organisation type to local.

After doing all of this, it still did not work.
Request your help in fixing it. Thanks in advance for the help.
<img width="2075" alt="step 1" src="https://github.com/MISP/MISP/assets/143619572/a501b191-74bd-4a39-a315-49339cf3d832">
<img width="2192" alt="step 2" src="https://github.com/MISP/MISP/assets/143619572/ef14ad4c-b2b2-43e7-ab77-46061e2b520f">
<img width="2098" alt="step 3" src="https://github.com/MISP/MISP/assets/143619572/666f02fe-0e17-4be0-87c6-07503e73b2a9">

### MISP version

2.4.151

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Extra attachments

<img width="2287" alt="Final Result" src="https://github.com/MISP/MISP/assets/143619572/247a8226-de08-4389-948c-22372d47c1db">
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moorocks** [comment]
This is the output that I got after trying to test the server
<img width="2287" alt="Final Result" src="https://github.com/MISP/MISP/assets/143619572/69691499-70ed-4f00-ac91-3b6828cec444">

**Comment by Moorocks** [comment]
I was able to connect it by myself. If anyone has any issues, feel free to drop a comment here, I can help you with this kind of issues.

Cheers!

**Comment by Bantraaa** [comment]
I have the same problem, can you tell how you fixed it?

**Comment by snephub** [comment]
Why not just post the answer here right away instead of saying "you fixed it"??? I have the same problem, earlier commenter as well, assume many others do too...

**Comment by iglocska** [comment]
Just guessing what could have been: It looks like the server is accessed via https and an IP address, which will obviously make the certificate validation fail. 

1. connect via the FQDN, not the IP address
2. Have a valid TLS certificate by a known signing authority on the remote instance, matching the domain of the server
3. If you want to use self-signed certificates, tell MISP that that's what you're doing.
4. If you have your own CA that is not known by the mozilla CA store, you can upload the full certificate chain (from CA to the server cert) in a .pem file when encoding the connection.

(5. If it's purely an internal setup / you are testing things locally and you don't want to bother with any of the above, use http for your instances (obviously please don't expose this to others, don't run it as your operational instance, etc, etc))
