### ISSUE TITLE
Bug: MISP.online_version_check causing An Internal Error

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#9277]
### Actual behavior

The diagnostics page shows

MISP version

Every version of MISP includes a JSON file with the current version.

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Expected behavior

Diagnostics page loads as normal - showing if MISP is up to date or not

### Steps to reproduce

1. Install MISP without git being available (e.g. using the instructions given on https://hub.docker.com/r/jisccti/misp-web)
2. Enable `MISP.online_version_check`
3. Go to diagnostics page

### Version

2.4.175

### Operating System

Debian

### Operating System version

Bullseye (docker)

### PHP version

7.4

### Browser

Firefox

### Browser version

117.0 (64-bit)

### Relevant log output

```shell
---debug.log---
2023-09-07 17:00:05 Notice: Could not get current git commit
[Exception] An error has occurred while attempt to read file `/var/www/MISP/.git/HEAD`: file doesn't exists.
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/GitTool.php(49): FileAccessTool::readFromFile()
#1 /var/www/MISP/app/Model/AppModel.php(3260): GitTool::currentCommit()
#2 /var/www/MISP/app/Model/Server.php(4190): AppModel->checkMIPSCommit()
#3 /var/www/MISP/app/Controller/ServersController.php(1135): Server->getCurrentGitStatus()
#4 [internal function]: ServersController->serverSettings()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#9 {main}

---error.log---
2023-09-07 17:00:08 Error: [Error] Call to undefined function _()
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(1224): View->_render()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(418): View->_renderElement()
#4 /var/www/MISP/app/View/Servers/server_settings.ctp(11): View->element()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(971): include('/var/www/MISP/a...')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(933): View->_evaluate()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/View/View.php(473): View->_render()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(968): View->render()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
```

### Extra attachments

When `MISP.online_version_check` is `false`, the diagnostics page reports that all required and optional dependencies are met.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoePJisc** [comment]
Issue remains in v2.4.177

**Comment by Kagee** [comment]
This is more of a feature request than a bug. 

The setting is to turn *off* the version check (default is on) for firewalled/airgapped MISPs. Thus a normal MISP install expects the git metadata to remain.

While it could be fixed, it is rather something the Dockerfile creator should fix, as that is where the git metadata is removed.

At least one other MISP docker has fixed this by just keeping the minimal required files in the .git directory.

**Comment by Kagee** [comment]
That said, turning a setting off should probably not kill the diag page...

**Comment by JoePJisc** [comment]
Raised as a bug as the version checks used to work without the .git directory remaining, i.e. it would show the installed and latest version without issue - this has broken with the introduction of the new settings.

The Docker image does disable online checks so the diag page loads properly, but showing current and latest version like before, just without the "Update MISP" button would be strongly preferred.

**Comment by JoePJisc** [comment]
Turns out this was due to `gettext` and `sockets` extensions not being installed in PHP.

After a bit of digging, the git files are not needed for the version checks the use `VERSION.json` and a call to the GitHub API - it was the latter that was failing due to the missing extensions.

It may be sensible to check for these extensions on the diag page and handle their absence in the version check

## Aside

Anyone wanting to avoid the git error and traceback that gets logged every time the diag page is loaded if `.git/` is removed, can spoof the required data like this during setup / container build / etc.:

```sh
git clone -q --branch ${MISP_VERSION} --single-branch https://github.com/MISP/MISP 
cd MISP
# install as normal
git rev-parse ${MISP_VERSION} > .git_commit_version
find . -type d -name .git -exec rm -r {} +
mkdir .git
mv .git_commit_version .git/HEAD
cp .git/HEAD .git/ORIG_HEAD
```
