### ISSUE TITLE
Bug: STIX 2.1 Import Error: Could not import STIX document: 'Malware' object has no attribute 'name' 

### ISSUE THREAD

**Issue by packet-rat** [MISP/MISP#9279]
### Actual behavior

1. [Import from] STIX 2.1 Package
2. Operation Fails With: 

Bug: STIX 2.1 Import Error: Could not import STIX document: 'Malware' object has no attribute 'name' 

### Expected behavior

1. [Import from] STIX 2.1 Package
2. MISP Event created with Attributes and Context

### Steps to reproduce

![image](https://github.com/MISP/MISP/assets/3220193/6f47955e-821c-4f9a-90e0-23b9f96d6405)

### Version

2.4.174 

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.33

### Browser

Any

### Extra attachments

[MAR-10454006.r5.v1.CLEAR_stix2.json.zip](https://github.com/MISP/MISP/files/12562888/MAR-10454006.r5.v1.CLEAR_stix2.json.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
This has been fixed in 2.4.175 via https://github.com/MISP/misp-stix/commit/335a61ddcd41fc020f0e4cdf5f5683bd3115258b
