### ISSUE TITLE
Same filename when you want to export an event in MISP format (XML & JSON)

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#928]
Hello all,

The file-name used (misp.search.events.results.xml or misp.search.events.results.json) is always the same when you want to download the attributes of an event in MISP format (click "Download as..." -> "MISP XML" or "Download as..." -> "MISP JSON").

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.16

**Comment by elhoim** [comment]
I suppose you mean that instead of using "misp.search.events.results.xml" for XML MISP export & "misp.search.events.results.json" for JSON MISP export from event page, it should use the event ID in the filename like it is doing for CSV, openIOC, STIX XML, STIX JSON, etc... ?

**Comment by devnull-** [comment]
Hello @elhoim 

Indeed, It's exactly what I mean :) (I apologize if my previous message wasn't clear enough). 

The event ID was always part of the file-name. The previous file-name structure was "misp.eventXXXX.export.xml". I didn't check the code but something have changed since the 2016-02. 

Could you re-add the event ID in the file-name for the JSON & XML MISP export ?

 Don't hesitate to contact me if you need some help and if you have some question.

devnull-

**Comment by iglocska** [comment]
Wow, that's annoying no idea when that changed. Will change it back.

**Comment by Rafiot** [comment]
@iglocska fixed?

**Comment by adulau** [comment]
Duplicate with #1515

**Comment by adulau** [comment]
Fixed in 7a0f0c4aecc56db94722ee7c13f9c59feab60123
