### ISSUE TITLE
Support: Decay Score in Splunk

### ISSUE THREAD

**Issue by Moorocks** [MISP/MISP#9286]
### Support Questions

Hello there,

I recently created a decay model in misp instance. After creating it, I verified the model by check decay scores of few attributes and it worked.

We (security team) integrated splunk and misp. Now I want to see the decay score in splunk, but I'm unable to see it.
If I can see the decay score in splunk, then we can write a query in splunk to ignore the attributes/iocs with score '0'.

I referred to one of the github post of yours (adding "includeDecayScore":1 paramater), but this did not work.

Can you please let me know how to fix this issue? ( attached the screenshot below)
![misp](https://github.com/MISP/MISP/assets/143619572/059c40d1-5d3b-4787-b68e-ee267e992198)

Also is there any way to add a tag to attribute once it is expired? If the decay score is 0, is there any automatic process that adds a tag to the attributes?

### MISP version

2.4.151

### Operating System

RedHat

### Operating System version

20.04

### PHP version

7.0

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moorocks** [comment]
Hi @iglocska 

Requesting your help on this. I'm not sure if the approach is right.

It would be helpful if you can help me with this. 

All i want to see is decay score in splunk and at the moment I'm unable to see it.

**Comment by adulau** [comment]
As mentioned, you need to have the support of the additional attributes search in misp42splunk https://github.com/remg427/misp42splunk/ and supporting the output of the decaying model results.
