### ISSUE TITLE
Support: How to migrate data to another instance

### ISSUE THREAD

**Issue by pietrogu** [MISP/MISP#9302]
### Support Questions

Hi,

I need to move my MISP db from the instance we are using to a new one.
In particular, i would like to export only a part of the database (entries from the last 30 days).
Also I need to export only the data without the db structure: this because after years my db has a lot of differences with the newest structure.

Could someone please help me in provividing me the correct sequence of actions and mysql commands to do this?

Thank you in advance
Pietro

### MISP version

2.4.177

### Operating System

Ubuntu

### Operating System version

18.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pietrogu** [comment]
Any help?

**Comment by pietrogu** [comment]
Anyone?

**Comment by Kagee** [comment]
It is probably best to setup a sync between the two MISP, and transfer the events like that. Remember to set the same ORG uuid as owner of both MISPS, and select "internal MISP" when setting up the sync connection.
