### ISSUE TITLE
Bug: FLOWMON integration is not showing hits from MISP feeds after update

### ISSUE THREAD

**Issue by mardaquat** [MISP/MISP#9307]
### Actual behavior

After the MISP update, there are no hits detected from the MISP feeds in Flowmon, despite the configuration and feeds remaining the same.

### Expected behavior

Before the MISP update, Flowmon has been detecting hits from the MISP feeds and logging events accordingly. After the update, we expect the hits to continue being detected and logged in Flowmon. In flowmon we were able to see that events description was containting "MISP" and specific "Event ID", now we are detecting only feed hits from default flowmon feeds.

### Steps to reproduce

Update MISP, 

### Version

2.4.177

### Operating System

Ubuntu 

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Can you share the queries done by flowmon against the ReST API of MISP?

**Comment by mardaquat** [comment]
> Can you share the queries done by flowmon against the ReST API of MISP?
![API](https://github.com/MISP/MISP/assets/108662427/b0f44200-e6f7-4a83-bb32-d174321d5627)
I have blacked out some items

**Comment by mardaquat** [comment]
I think here is the problem "Update the database after PULLing the submodule(s)" this job is still running and its unable to finish

**Comment by mardaquat** [comment]
Solved, problem was in Flowmon.

**Comment by mardaquat** [comment]
Solved, problem was in Flowmon.
