### ISSUE TITLE
How to use an external Redis instance?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#932]
Hi *,

I need to use an external Redis instance. I searched the code, config files. I found several occurences of variables like "redis_host". Changed them from "localhost" to "fqdn" but it does not work. MISP constantly returns an error 500... Where do we need to change this setting?

/x

**Comment by Rafiot** [comment]
Do you still ave the problem? We never tried his setup, and I'm not sure redis server listen on anything else than localhost by default.

**Comment by sfossen** [comment]
we've successfully used it with remote redis, we had to change the cakeresque and zmq settings.

**Comment by Rafiot** [comment]
Great, good to know, thanks for the feedback!
