### ISSUE TITLE
Cannot see the MatterMost Module in my MISP Workflow

### ISSUE THREAD

**Issue by Moorocks** [MISP/MISP#9338]
### Support Questions

I'm  unable to see MatterMost module in my MISP Workflow.

### MISP version

2.4.177

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Extra attachments

<img width="2038" alt="Screenshot 2023-10-18 at 11 29 53 pm" src="https://github.com/MISP/MISP/assets/143619572/c26cd664-c3c6-4b12-9430-7e38bafd604e">
<img width="1956" alt="Screenshot 2023-10-18 at 11 30 16 pm" src="https://github.com/MISP/MISP/assets/143619572/d6f47a71-4db5-41ca-bd62-aa252506c57a">
<img width="1772" alt="Screenshot 2023-10-18 at 11 35 31 pm" src="https://github.com/MISP/MISP/assets/143619572/9eb56b25-cf2b-44bf-90cf-10a25e69959d">

<img width="1768" alt="Screenshot 2023-10-18 at 11 35 40 pm" src="https://github.com/MISP/MISP/assets/143619572/997df553-8a1a-490f-92a1-9da98a635542">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Hi,

That action module is available via MISP-modules, https://github.com/MISP/misp-modules/tree/main
I'd suggest checking that your misp-modules are up to date.
You'll also have to set this:
![image](https://github.com/MISP/MISP/assets/9868873/4023da2a-ae00-4d7a-9cf3-500b81354965)

**Comment by mokaddem** [comment]
In complement to @Wachizungu reply, you can find more documentation starting slide 15 [here](https://www.misp-project.org/misp-training/a.12-misp-workflows.pdf).

**Comment by Moorocks** [comment]
Hi @Wachizungu @mokaddem ,

Can you please address the below issues:

1. I'm using a docker container image with 2.4.175, how can i update the misp modules?
2. I get an warning saying that 'MISP Modules Action Services is not reachable! Some modules might not be available.' . But I enabled the Plugin.Action_services_enable to 'true' and restarted the docker container. But I'm still facing the issue.
3.  I'm unable to see mattermost module despite enabling this parameter and restarting the docker container.

Do i need to stop and start the container in order to get the changes?
Your help is much appreciated. 

Cheers
