### ISSUE TITLE
Feature Request: Workflow "Attach Warninglist" should support multifield

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/MISP#9343]
### Is your feature request related to a problem? Please describe.

In the Workflow "Attach Warninglist" you can only choose either "ALL" or a specific warninglist, but in some events you would like to choose more Warninglists
![Screenshot 2023-10-19 173748](https://github.com/MISP/MISP/assets/14878613/990bc5b8-ad15-403d-b320-59218760157f)

### Describe the solution you'd like

If you are able to multi select warningslists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Done in https://github.com/MISP/MISP/commit/612d40a15e6af96418f1cf46bf79ed9ae4a04101. Cheers
