### ISSUE TITLE
Support: Sending messages through Telegram

### ISSUE THREAD

**Issue by SkodaLoco12** [MISP/MISP#9346]
### Support Questions

Hi all,

I'm trying to set a workflow to send a message through Telegram. I saw that, from the actions available, there is the action "Telegram send alert". I set the chat id and the telegram token and a simple textual message. After I publish an event, trigger of the workflow, I don't receive any message. I'm sure that the telegram token and chat id are correct because I tryed it with the python-telegram-bot python module. I'm also sure that the workflow is successfull from the logs. 

Any advice?

![image](https://github.com/MISP/MISP/assets/148569907/4693a59c-f9b7-4077-ad0a-c9ea7a107f20)

### MISP version

v2.4.176

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincenzocaputo** [comment]
Hi, thanks for the report. It should be fixed in #9347.
