### ISSUE TITLE
Mattermost module issue

### ISSUE THREAD

**Issue by Moorocks** [MISP/MISP#9356]
Hi @Wachizungu @mokaddem ,

Can you please address the below issues:

1. I'm using a docker container image with 2.4.175, how can i update the misp modules?
2. I get an warning saying that 'MISP Modules Action Services is not reachable! Some modules might not be available.' . But I enabled the Plugin.Action_services_enable to 'true' and restarted the docker container. But I'm still facing the issue.
3.  I'm unable to see mattermost module despite enabling this parameter and restarting the docker container.

Do i need to stop and start the container in order to get the changes?
Your help is much appreciated. 

Cheers

_Originally posted by @Moorocks in https://github.com/MISP/MISP/issues/9338#issuecomment-1787057713_

**Comment by kanekennedy** [comment]
I can never get any of the modules to run in the core docker container as they just don't start.  I compile and run the modules in a separate docker container.  I then lifted and modified a set of cake commands into a batch file to set the url for MISP to find them and various other things.

eg
```
docker exec misp_web /var/www/MISP/app/Console/cake Admin setSetting "Plugin.Import_services_enable" true
docker exec misp_web /var/www/MISP/app/Console/cake Admin setSetting "Plugin.Import_services_url" "http://misp-modules"
docker exec misp_web /var/www/MISP/app/Console/cake Admin setSetting "Plugin.Import_services_port" 6666
```

**Comment by Moorocks** [comment]
Hi @kanekennedy ,

Tried this method too, still not working!!

**Comment by Moorocks** [comment]
Hi @kanekennedy, 
This issue is solved.
All you need to do is go to server settings and maintenance and navigate to plugins.
There set Plugin.Action_services_url=http://misp-modules
<img width="1793" alt="Screenshot 2023-11-05 at 10 45 00 pm" src="https://github.com/MISP/MISP/assets/143619572/bf7b1aa2-e94f-4e52-9847-913861d32070">

**Comment by kanekennedy** [comment]
That would be the middle line I posted where it sets the url ;)

**Comment by Moorocks** [comment]
Hi @kanekennedy 
You mentioned that you run the modules in a different container and execute these commands right?
When i do docker-compose up, I see that modules are already in a different container.

When i execute your set of cake commands on the module container, my misp ui is not responding. It says 'Internal Error Occured'.
