### ISSUE TITLE
Install errors Ubuntu 14.04 LTS 

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#936]
I'm experiencing an issue with the installation of MISP on a fresh install server, running Ubuntu 14.04.

I've taken a look at the logs, and they are coming up with the following:

2016-02-12 10:24:08 Error: [MissingControllerException] Controller class MISPController could not be found.
Exception Attributes: array (
  'class' => 'MISPController',
  'plugin' => NULL,
)
Request URL: /MISP/
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}

2016-02-12 10:24:08 Error: Fatal Error (4): syntax error, unexpected '[', expecting ')' in [/var/www/MISP/app/Controller/AppController.php, line 193]
2016-02-12 10:24:08 Error: [FatalErrorException] syntax error, unexpected '[', expecting ')'
Request URL: /MISP/
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/MISP/a...', 193)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/MISP/a...', 193, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/MISP/a...', 193, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

Can't quite determine what is throwing this error, any ideas?

**Comment by Rafiot** [comment]
You need to set a base url: https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1404.txt#L152

Please let us know if it solves the problem.

**Comment by iglocska** [comment]
What URL did you try to access? From the error it looks like you were trying to get to 

https://my_misp.com/MISP instead of https://my_misp.com

The first parameter after the baseurl is always the "controller" that you are calling (with the full syntax being baseurl/controller/action/parameters) and it complains about not finding the MISP controller.

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
