### ISSUE TITLE
Bug: Cannot add new users after updating to v2.4.178

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#9362]
### Actual behavior

Admins cannot create new users.

Web UI says: "The user could not be saved. Please, try again."

REST API admin/users/add:

`{
    "saved": false,
    "name": "Could not add User",
    "message": "Could not add User",
    "url": "/admin/users/add",
    "errors": {
        "authkey": [
            "A authkey of a minimum length of 40 is required."
        ]
    }
}`

PyMISP examples/add_user.py:

`Something went wrong (403): {'saved': False, 'name': 'Could not add User', 'message': 'Could not add User', 'url': '/admin/users/add', 'errors': {'authkey': ['A authkey of a minimum length of 40 is required.']}}
{'errors': (403, {'saved': False, 'name': 'Could not add User', 'message': 'Could not add User', 'url': '/admin/users/add', 'errors': {'authkey': ['A authkey of a minimum length of 40 is required.']}})}`

However the key is 40 characters long and it works with other RESTAPI calls.

### Expected behavior

Admins can create new users.

### Steps to reproduce

We updated to the v2.4.178 (c15c88ed75de4c5d26388078958691b0b9a97611).

After that we tried adding users but with no success.

### Version

v2.4.178 (c15c88ed75de4c5d26388078958691b0b9a97611)

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Relevant log output

```shell
We have not observed any relevant output to logs regarding this issue e.g. we get nothing with the following command while attempting to create a new user:

tail -f /var/www/MISP/app/tmp/logs/*.log

The Diagnostics page Schema status does not hilight any database schema issues at this time.

We tried with two different admin accounts and both are having same results.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samitainio** [comment]
I now had the time to test with a clean MISP install and I cannot reproduce the issue with it. Any ideas where I could start debugging and hopefully fixing the issue on the affected system?

**Comment by iglocska** [comment]
Interesting. The authkey field should get auto populated on creation, I guess the new system you tried it on might be more laxly configured on the mysql side. Let me try to see if I can reproduce it.

**Comment by iglocska** [comment]
Hmm for me it gets set correctly, this is funky. Could you try purging your model caches? (administration -> server settings -> diagnostics -> clean model cache).

**Comment by samitainio** [comment]
@iglocska I ran it and then tried to create the user. No change, same error.

I've also ran the following command just in case to see if there is something wrong with the tables:

`sudo mysqlcheck -c misp`

Result was OK status for all tables.

Diagnostics page schema tool does not hilight any issues but here are the current column definitions regardless:

`MariaDB [misp]> show full columns from auth_keys;`

| Field         | Type             | Collation          | Null | Key | Default | Extra          | Privileges                      | Comment |
|---------------|------------------|--------------------|------|-----|---------|----------------|---------------------------------|---------|
| id            | int(10) unsigned | NULL               | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| uuid          | varchar(40)      | utf8mb4_unicode_ci | NO   |     | NULL    |                | select,insert,update,references |         |
| authkey       | varchar(72)      | ascii_general_ci   | NO   |     | NULL    |                | select,insert,update,references |         |
| authkey_start | varchar(4)       | ascii_general_ci   | NO   | MUL | NULL    |                | select,insert,update,references |         |
| authkey_end   | varchar(4)       | ascii_general_ci   | NO   | MUL | NULL    |                | select,insert,update,references |         |
| created       | int(10) unsigned | NULL               | NO   | MUL | NULL    |                | select,insert,update,references |         |
| expiration    | int(10) unsigned | NULL               | NO   | MUL | NULL    |                | select,insert,update,references |         |
| read_only     | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| user_id       | int(10) unsigned | NULL               | NO   | MUL | NULL    |                | select,insert,update,references |         |
| comment       | text             | utf8mb4_unicode_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| allowed_ips   | text             | utf8mb4_unicode_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| unique_ips    | text             | utf8mb4_unicode_ci | YES  |     | NULL    |                | select,insert,update,references |         |

`MariaDB [misp]> show full columns from users;`

| Field                  | Type             | Collation          | Null | Key | Default | Extra          | Privileges                      | Comment |
|------------------------|------------------|--------------------|------|-----|---------|----------------|---------------------------------|---------|
| id                     | int(11)          | NULL               | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| password               | varchar(255)     | utf8mb3_bin        | NO   |     | NULL    |                | select,insert,update,references |         |
| org_id                 | int(11)          | NULL               | NO   | MUL | NULL    |                | select,insert,update,references |         |
| server_id              | int(11)          | NULL               | NO   | MUL | 0       |                | select,insert,update,references |         |
| email                  | varchar(255)     | utf8mb3_unicode_ci | NO   | UNI | NULL    |                | select,insert,update,references |         |
| autoalert              | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| authkey                | varchar(40)      | utf8mb3_bin        | YES  |     | NULL    |                | select,insert,update,references |         |
| invited_by             | int(11)          | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| gpgkey                 | longtext         | utf8mb3_bin        | YES  |     | NULL    |                | select,insert,update,references |         |
| certif_public          | longtext         | utf8mb3_bin        | YES  |     | NULL    |                | select,insert,update,references |         |
| nids_sid               | int(15)          | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| termsaccepted          | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| newsread               | int(11) unsigned | NULL               | YES  |     | 0       |                | select,insert,update,references |         |
| role_id                | int(11)          | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| change_pw              | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| contactalert           | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| disabled               | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| expiration             | datetime         | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| current_login          | int(11)          | NULL               | YES  |     | 0       |                | select,insert,update,references |         |
| last_login             | int(11)          | NULL               | YES  |     | 0       |                | select,insert,update,references |         |
| force_logout           | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| date_created           | bigint(20)       | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| date_modified          | bigint(20)       | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| sub                    | varchar(255)     | utf8mb3_bin        | YES  | UNI | NULL    |                | select,insert,update,references |         |
| external_auth_required | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| external_auth_key      | text             | utf8mb3_bin        | YES  |     | NULL    |                | select,insert,update,references |         |
| last_api_access        | int(11)          | NULL               | YES  |     | 0       |                | select,insert,update,references |         |
| notification_daily     | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| notification_weekly    | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| notification_monthly   | tinyint(1)       | NULL               | NO   |     | 0       |                | select,insert,update,references |         |
| totp                   | varchar(255)     | utf8mb3_bin        | YES  |     | NULL    |                | select,insert,update,references |         |
| hotp_counter           | int(11)          | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| last_pw_change         | bigint(20)       | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |

I went back to Diagnostics page and enabled the debug mode for schema:

| Table name | Description | Expected schema | Actual schema |
| --- | --- | --- | --- |
| users | Column `authkey` is different | authkey YES varchar 40  utf8mb3_bin varchar(40) NULL | authkey YES varchar 40  utf8mb3_bin varchar(40) 'NULL' |

It gives this as a fix for it:

```
ALTER TABLE `users` MODIFY COLUMN `authkey` varchar(40) DEFAULT "NULL" NULL COLLATE utf8mb3_bin ;
```

However that command did not change anything and it also remains in the debug section even after its execution.

Also tried to create a new user after that but no change in the end result. We also tested with org_admin accounts and they are also unable to create new users.

**Comment by iglocska** [comment]
That fix looks indeed incorrect, could you try with this:

```
ALTER TABLE `users` MODIFY COLUMN `authkey` varchar(40) NULL COLLATE utf8mb3_bin ;
```

And then clean the model cache again? I have no idea how you ended up with 'NULL' o.O

**Comment by samitainio** [comment]
@iglocska Thank you so much! That fixed it. I owe you :beers:

**Comment by iglocska** [comment]
Glad it worked out, curious how you ended up with the issue in the first place, there's also something obviously wrong with the fix recommendation. Holler if you run into other issues!
