### ISSUE TITLE
redis server went away and don t want to come back

### ISSUE THREAD

**Issue by raphg51** [MISP/MISP#937]
Hie,

I ve a fresh VM running ubuntu 14.04 i ve already install successfully a MISP in V 2.3 but i ve lost my VM and i want to try V2.4.
I ve followed every instruction in the install instruction file but it seems that the redis module dont want to work...

I ve first think that i ve made a mistake so i ve deleted my VM and retry from a new fresh VM but the same erro occur!

So i trig a redis exception when i want to go to admin server setting view of the website which work fine (except server_setting). Same error occur when i try to launch workers (error : redis server wen away).

Ive look at the redis config file to find the port used, and i cant connect to port used by redis.

I ve repass thrue commands : 

CakeResque normally uses phpredis to connect to redis, but it has a (buggy) fallback connector through Redisent. It is highly advised to install phpredis
pecl install redis
apt-get install php5-redis
Note that the php5-redis package in Debian stable (wheezy) only exists in the backports repository: http://backports.debian.org/Instructions/
After installing it, enable it in your php.ini file
vim /etc/php5/apache2/php.ini
add the following line:
extension=redis.so

to use the scheduler worker for scheduled tasks, do the following:
cp -fa /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php

But no changes... I ve reset permissions rights and no effect too...

This is my error.log extract :+1: 
Error : [RedisException] Redis server went away
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(28): Redis->setOption(2, 'resque:')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('localhost', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('localhost', '6379', NULL)
#4 /var/www/MISP/app/Model/Server.php(2088): Resque::redis()
#5 /var/www/MISP/app/Controller/ServersController.php(705): Server->workerDiagnostics(0)
#6 [internal function]: ServersController->serverSettings()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

Am i the only one with this issue?

Thx for your help!

**Comment by elhoim** [comment]
Is redis-cli command line connection to your redis server working?

Do you have a redis-server < v2.8?

**Comment by raphg51** [comment]
I think i ve a ghost in my computer.

I ve find after 2 H of debugging.

I ve all configured well for redis EXCEPT the installation.

I ve try to install all dependencies in one command like:
apt-get install gcc zip php-pear git redis-server make python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev php5-dev libapache2-mod-php5 curl
pear install Crypt_GPG

one shot install.
And you believe or not but this one shot command dont install redis-server properly on my computer. this command prompt 'after this operation blablabla do you want to continue? (yes/no)' 
And if you enter 'yes' the command end with 'abort'.

Ive first intall dependancy with only one eye on the screen so i ve dont seen this error message...

My mistake.

Solved.

Thx for your return.

**Comment by iglocska** [comment]
Great that you've managed to work it out, maybe it could be handy to have a
script that checks all of the dependencies in the future, it can indeed be
frustrating when you miss an error that gets returned by one of the many
prerequisites.

**Comment by raphg51** [comment]
Yeah why not and what about an installation script?

If you look user only set data base name and Password and URL. A script that ask for this parameters with interactive commande can do thé job Quickly and save à lot of time.

By thé way thx for your amazing job MISP is awesome I wait for ioc enrichement in 3.0 à lot.
