### ISSUE TITLE
Graceful maintenance page

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#939]
Have a way to enable a static page mentioning maintenance when there is some maintenance happening on a MISP instance.

Because now when there is an upgrade that takes place, you can get some pages that don't load, or some that load with errors, etc...

Maybe the "is live" switch can be used as a trigger for this displaying that page?

**Comment by cvandeplas** [comment]
MISP has a maintenance mode feature that the admin can set in the configuration. This prevents users to authenticate on MISP and probably resolves the original question of @elhoim .

However the thing that is missing is a notification to the user (trying to authenticate) saying the server is in maintenance mode and he is not allowed to login.  Today the user tries to authenticate and is just redirected to the login page without notification. 
This could be done either before authentication, or after having entered his credentials.  Importantly the authentication page needs to stay available as admins need to be able to login.

**Comment by cristianbell** [comment]
So the whole functionality is already there, in beforeFilter() - line 252. If MISP is not live, it reads the MISP.maintenance_message or uses the built-in message. 
The message is created but not really displayed - due to the redirect MethodNotAllowedException($message) is not helping. Sending the message as a $this->Session->setFlash($message);

**Comment by iglocska** [comment]
Indeed, that would solve it.

**Comment by cristianbell** [comment]
should be fixed by 7b65a52a4409e81e998c6f44b8c8378c9e09b2d5. Shouldn't this be closed?

**Comment by iglocska** [comment]
Yes it should. When you create a PR for an issue, just have the commit message in this format:

`fix: maintenance message was not showing up for users, fixes #939`

and it will close it when we accept the PR.

**Comment by cristianbell** [comment]
thanks! and sorry, was sure I filled in the fix and the issue number part..

**Comment by iglocska** [comment]
I mean if you do that it will automagically close the issue when I accept the PR ;) Github is pretty cool.
