### ISSUE TITLE
Getting error while running start.sh

### ISSUE THREAD

**Issue by xsallowed** [MISP/MISP#940]
I am getting following issue 

./start.sh: line 3: ../cake: Permission denied
./start.sh: line 4: ../cake: Permission denied
./start.sh: line 5: ../cake: Permission denied
./start.sh: line 6: ../cake: Permission denied
./start.sh: line 7: ../cake: Permission denied

**Comment by iglocska** [comment]
Sounds like a file permission issue on /var/www/MISP/app/Console/cake

Make sure your apache user can execute it.

**Comment by elhoim** [comment]
@xsallowed  any update?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
