### ISSUE TITLE
An Internal Error Has Occurred. Error: An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by xsallowed** [MISP/MISP#941]
Hi 
I am sorry to report earlier problem but now i am getting this error on Login:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

**Comment by adulau** [comment]
Have you checked the logs?

The logs are located in app/tmp/logs especially the error.log and debug.log?

Thank you.

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
