### ISSUE TITLE
Bug: MISP 2.4.179 Server Settings & Maintenance page does not work

### ISSUE THREAD

**Issue by m-kas** [MISP/MISP#9414]
### Actual behavior

Administration / Server Settings & Maintenance does not work.

Following error is displayed:

<img width="932" alt="image" src="https://github.com/MISP/MISP/assets/1783088/1d4484b6-18e8-43b8-8464-58cce0f7c852">

### Expected behavior

Administration / Server Settings & Maintenance page works properly.

### Steps to reproduce

After updating to MISP 2.4.179  I am unable to get to Administration / Server Settings & Maintenance page.

### Version

2.4.179

### Operating System

Ubuntu

### Operating System version

20.04.3 LTS

### PHP version

7.4.3

### Browser

every browser

### Relevant log output

```shell
2023-11-24 09:08:45 Error: [Error] Call to a member function editAttributeBulk() on null
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Model/WorkflowModules/action/Module_attribute_comment_operation.php(2): include_once()
#1 /var/www/MISP/app/Model/Workflow.php(1080): include_once('/var/www/MISP/a...')
#2 /var/www/MISP/app/Model/Workflow.php(1010): Workflow->__getClassFromModuleFile()
#3 /var/www/MISP/app/Model/Workflow.php(872): Workflow->__getClassFromModuleFiles()
#4 /var/www/MISP/app/Model/Workflow.php(1110): Workflow->loadAllWorkflowModules()
#5 /var/www/MISP/app/Model/Server.php(1474): Workflow->getModulesByType()
#6 /var/www/MISP/app/Model/Server.php(1423): Server->readModuleSettings()
#7 /var/www/MISP/app/Model/Server.php(1555): Server->getCurrentServerSettings()
#8 /var/www/MISP/app/Controller/ServersController.php(1055): Server->serverSettingsRead()
#9 [internal function]: ServersController->serverSettings()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
```
```


### Extra attachments

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gotshell** [comment]
Hello, facing the same issue on RHEL 8.8 right after the update to the last version.

/var/www/MISP/app/tmp/logs/error.log

2023-11-24 18:36:38 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/WorkflowModules/action/Module_attribute_edition_operation.php, line 71]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
include_once - APP/Model/WorkflowModules/action/Module_attribute_edition_operation.php, line 71
include_once - APP/Model/WorkflowModules/action/Module_attribute_comment_operation.php, line 2
Workflow::__getClassFromModuleFile() - APP/Model/Workflow.php, line 1080
Workflow::__getClassFromModuleFiles() - APP/Model/Workflow.php, line 1010
Workflow::loadAllWorkflowModules() - APP/Model/Workflow.php, line 872
Workflow::getModulesByType() - APP/Model/Workflow.php, line 1110
Server::readModuleSettings() - APP/Model/Server.php, line 1474
Server::getCurrentServerSettings() - APP/Model/Server.php, line 1423
Server::serverSettingsRead() - APP/Model/Server.php, line 1555
ServersController::serverSettings() - APP/Controller/ServersController.php, line 1055
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2023-11-24 18:36:38 Error: [Error] Call to a member function editAttributeBulk() on null
Request URL: /servers/serverSettings
Stack Trace:
#0 /var/www/MISP/app/Model/WorkflowModules/action/Module_attribute_comment_operation.php(2): include_once()
#1 /var/www/MISP/app/Model/Workflow.php(1080): include_once('/var/www/MISP/a...')
#2 /var/www/MISP/app/Model/Workflow.php(1010): Workflow->__getClassFromModuleFile()
#3 /var/www/MISP/app/Model/Workflow.php(872): Workflow->__getClassFromModuleFiles()
#4 /var/www/MISP/app/Model/Workflow.php(1110): Workflow->loadAllWorkflowModules()
#5 /var/www/MISP/app/Model/Server.php(1474): Workflow->getModulesByType()
#6 /var/www/MISP/app/Model/Server.php(1423): Server->readModuleSettings()
#7 /var/www/MISP/app/Model/Server.php(1555): Server->getCurrentServerSettings()
#8 /var/www/MISP/app/Controller/ServersController.php(1055): Server->serverSettingsRead()
#9 [internal function]: ServersController->serverSettings()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
2023-11-24 18:42:30 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/WorkflowModules/action/Module_attribute_edition_operation.php, line 71]

**Comment by mdhirt** [comment]
This could be a similar issue to https://github.com/MISP/MISP/issues/9411
See if you can implement the fix in as yet unmerged pull request https://github.com/MISP/MISP/pull/9413

**Comment by m-kas** [comment]
Yeah, I saw that issue and manually applied the patch, however, unfortunately it did not help in my case.

**Comment by m-kas** [comment]
In my case, it helped to manually fetch the latest changes from git.

**Comment by gotshell** [comment]
Same, thanks @m-kas. 
_____________________________________

> cd /var/www/MISP 
> git pull
_____________________________________
