### ISSUE TITLE
Feature Request: Add an additional header for API authentication

### ISSUE THREAD

**Issue by simonbjorzen-ts** [MISP/MISP#9418]
### Is your feature request related to a problem? Please describe.

When running MISP behind a authentication proxy that uses the Authorization header for Bearer authentication, the MISP API is inaccessible due to both services using the same header. 
It is possible to solve using header rewrite in the webserver, but I'd like a permanent solution in MISP.

### Describe the solution you'd like

Add an additional header for authentication, for example: X-MISP-AUTH.
MISP should look at the Authorization header first, if that is invalid, it should look for the X-MISP-AUTH header.

### Describe alternatives you've considered

Rewrite headers in Apache/NGINX, but a more permanent solution would be nice.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
That's a good idea. Will look into it.
