### ISSUE TITLE
Bug: Existing workflows do not work and other performance issue after update to 2.4.179

### ISSUE THREAD

**Issue by vincenzocaputo** [MISP/MISP#9423]
### Actual behavior

Hi,

After updating to 2.4.179 I've experienced several issues with Workflows.  My workflows (that works correctly in 2.4.178) do not work anymore with the new version. According to the logs, the workflows are executed correctly and no errors are produced, but actually no operations are performed.

I've tried to create a workflow from scratch and it worked without any problems, so I think the problem only occurs with pre-existing workflows

In addition, I have experienced some performance issues while editing workflows. It can take more than 5 minutes to open a workflow and a couple of minutes to add a new block to a workflow.

### Expected behavior

Workflows should keep working after updates.

### Steps to reproduce

Update to the latest version

### Version

2.4.179

### Operating System

RedHat

### Operating System version

release 8.5 (Ootpa)

### PHP version

7.4.30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincenzocaputo** [comment]
Probably, the issue could have been caused by this change: https://github.com/MISP/MISP/commit/20b473c99bf0d7bbd38d2eab016cd0731e04f454#diff-148bb0a1de1c22f168b6b451f0ff1e105be027d96971fb886595b1589afb774bR18-R21

https://github.com/MISP/MISP/blob/20b473c99bf0d7bbd38d2eab016cd0731e04f454/app/Model/WorkflowModules/logic/Module_organisation_if.php#L18-L21

Existing workflows are still using the "equals" operator in the "IF :: Organisation" logic blocks:
```JSON
  "433": {
    "id": 433,
    "name": "IF :: Organisation",
    "data": {
      "indexed_params": {
        "org_type": "orgc",
        "condition": "equals",
        "org_id": "2"
      },
```

**Comment by mokaddem** [comment]
This was long overdue..
Thanks for the report!
