### ISSUE TITLE
Bug: Undefined variable: loginProfile in [/var/www/MISP/app/Controller/UserLoginProfilesController.php, line 150]

### ISSUE THREAD

**Issue by skalvaro** [MISP/MISP#9424]
### Actual behavior

Unable to set the trust for the user login profile. As a result every login results in a New sign in email being sent.

### Expected behavior

Able to set trust/malicious on the login profile.

### Steps to reproduce

Update to [v2.4.180](https://github.com/MISP/MISP/commit/a41f7cbcf6d2b24ad906e2e9b142636c41c274a9).
Login, go to /users/view_login_history and try to either trust the profile or report as malicious.

### Version

2.4.180

### Operating System

RedHat

### Operating System version

7

### PHP version

7.4.33

### Browser

Firefox

### Relevant log output

```shell
2023-11-30 18:33:37 Notice: Notice (8): Undefined variable: loginProfile in [/var/www/MISP/app/Controller/UserLoginProfilesController.php, line 150]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
UserLoginProfilesController::__setTrust() - APP/Controller/UserLoginProfilesController.php, line 150
UserLoginProfilesController::trust() - APP/Controller/UserLoginProfilesController.php, line 104
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Could you got pull and try it again? Does it persists?

**Comment by cvandeplas** [comment]
There was indeed a bug in the code triggering the `undefined variable` error, fixed now, please update your MISP. T

**Comment by skalvaro** [comment]
Just updated to [02c1c30](https://github.com/MISP/MISP/commit/02c1c30ab948dc7633b757c36dd9c6e898c3b7ad) and can confirm it is working now.

**Comment by cvandeplas** [comment]
thanks for the update !
