### ISSUE TITLE
Bug: /var/www/MISP/app/Vendor/autoload.php file is missing

### ISSUE THREAD

**Issue by donatasiv** [MISP/MISP#9430]
### Actual behavior

Application failing to start, due to missing file: '/var/www/MISP/app/Vendor/autoload.php' 

### Expected behavior

Application starts

### Steps to reproduce

Running installation script

### Version

2.4.181

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Relevant log output

```shell
PHP Warning:  require_once(/var/www/MISP/app/Vendor/autoload.php): failed to open stream: No such file or directory in /var/www/MISP/app/Config/core.php on line 298
PHP Fatal error:  require_once(): Failed opening required '/var/www/MISP/app/Vendor/autoload.php' (include_path='/var/www/MISP/app/Lib/cakephp/lib:.:/usr/share/php') in /var/www/MISP/app/Config/core.php on line 298
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
I just finished installing using the installer (https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh) on a 20.04 system, and did not experience this error.

I assume an error happened during your install. If you do not have the installer output avaliable, I would recommend nuking the misconfigured system and installing MISP from fresh

**Comment by donatasiv** [comment]
Reinstallation solved issue.
