### ISSUE TITLE
Bug: [userloginprofiles] View login history page is broken on system with php version 7.4.3

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#9433]
### Actual behavior

![image](https://github.com/MISP/MISP/assets/9868873/1e77a277-f9ff-4ed4-8251-9e6ab1780669)

Looks like str_contains function which is used in view_login_history.ctp is only supported as of php version 8.

### Expected behavior

You can view the login history, or in case there is no support for it, you get a clean message in the GUI.

### Steps to reproduce

Go to your profile and click the 'Review user logins' button.

### Version

2.4.181

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Just adding as context:
With the currently required php dependencies installed, this problem does not present itself so if you run into this issue remember to run (equivalent of the below for your system):
sudo -u www-data sh -c "cd /var/www/MISP/app;php composer.phar update"

Looks like browscap/browscap-php might be doing the trick, having symfony/polyfill-php80 in dependency tree at the moment

**Comment by cvandeplas** [comment]
fixed, thank you for the report !
