### ISSUE TITLE
Bug: `deleted` param in /attributes/restSearch endpoint behaves differently than expected

### ISSUE THREAD

**Issue by mdavis332** [MISP/MISP#9437]
### Actual behavior

When `"deleted": true` is passed in the POST body to the `/attributes/restSearch` endpoint, the results _only_ include deleted attributes (attributes where a proposal has been made and accepted to "soft-delete" the attribute). 

### Expected behavior

Based on the description of the `deleted` parameter [here](https://github.com/MISP/MISP/blob/2.4/app/Controller/Component/RestResponseComponent.php#L1055) and [here](https://github.com/MISP/MISP/blob/2.4/docs/API_Doc.md?plain=1#L119) I would expect the `deleted` param to include attributes marked as deleted:true AND deleted:false. 

If that is not desired, I would suggest changing the docs and tooltip to read more like that for the `to_ids` param, e.g., "the state of the `deleted` flag. Further, I would then request something like an `includeDeleted` param that functions as I described returning attributes marked both deleted and not. 

Just a tangential note: I would have expected deleted Events to also get soft-deleted but it appears they are actually removed from the database. Therefore, searching `/attributes/restSearch` with `deleted: true` with the expectation to find attributes included in deleted Events will not yield anything. 

### Steps to reproduce

```
HTTP/1.1 POST /attributes/restSearch

{
    "returnFormat": "json",
    "enforceWarninglist": "true",
    "last_seen": ["30d", "0s"],
    "limit": "1000",
    "deleted": true
}
```

### Version

2.4.179

### Operating System

CentOS

### Operating System version

Stream 8

### PHP version

7.4

### Browser

Edge, Chrome, Firefox

### Browser version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Hi there,

Looks like this is not properly documented indeed. I had made modification here a while back: https://www.circl.lu/doc/misp/automation/

Think this about covers it:
deleted: Default value 0. If set to 1, only deleted attributes will be returned. If set to [0,1] , both deleted and non-deleted attributes wil be returned.

I'll see to create a PR next weekend for the other doc locations (the ones you mentioned and openAPI). Personally I'm hoping the OpenAPI will become the main reference going forwards. You can find it in the GUI or at https://www.misp-project.org/openapi/#tag/Attributes/operation/restSearchAttributes

**Comment by mdavis332** [comment]
> I'm hoping the OpenAPI will become the main reference going forwards

This sounds good but even the link you referenced mentions that the `deleted` param accepts a single boolean attribute (no mention of taking an array of integers like you noted). 

Though I agree with the sentiment that a single, automatically generated documentation page would be much better than multiple, manual pages of documentation that become stale/incorrect over time.

Thanks for the heads up on setting `deleted` to [0,1] to return both. I'll give that a shot.

**Comment by mdavis332** [comment]
The recommendation provided by @Wachizungu worked and I see his PR was merged last week, so I'm resolving this issue. Thanks!
