### ISSUE TITLE
Support: Users cannot use MISP after integration with AAD

### ISSUE THREAD

**Issue by row098** [MISP/MISP#9443]
### Support Questions

I have successfully configured the integration of my MISP instance with Azure AAD, following all the steps in here: https://github.com/MISP/MISP/tree/2.4/app/Plugin/AadAuth

The authentication is working successfully since I (site admin) can authenticate via AAD without issues and, actually, the rest of the users can too, however, the difference is I can navigate the portal but they, wherever they click, get the following message:

"User password change has been disabled on this instance.
Error: You don't have permission to access '/users/change_pw'."

I am site admin. The users that ate getting the issue are one org admin, and two normal users.

What am I missing?
TIA

### MISP version

2.4.179

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3-4ubuntu2.19

### Browser

Any browser

### Browser version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
That is weird, how are you enrolling the users? Basically there's a flag that can be set when you create a user, as described here:

Disable users password change
By default MISP will still create a password for the user, when enrolling a new user on MISP, uncheck the "Send credentials automatically" checkbox.

Are you unchecking that?

**Comment by row098** [comment]
Hi,
First of all, thank you for your answer. 

Yes, I am unchecking that box when creating users. In the meantime, I noticed that when editing an already created user profile, there is an option that is checked: "User must change password". 
When I try to modify it (Site admin that can navigate without issues) and try to apply the changes, I get the "Invalid password. Please enter your current password to continue.", even though I am using the same password of my AAD account. Is this normal behavior? Should I use a local account for this kind of change?

**Comment by iglocska** [comment]
Ah ok, that password check will be annoying when using external authentication methods, I'd just disable the security feature for it: 

Administration -> settings -> Security -> Security.require_password_confirmation to false

**Comment by row098** [comment]
I was able to perform the change and it solved the issue.
Thank you for the help!
