### ISSUE TITLE
Support: Facing Issue while installing MISP in Ubuntu 22.04

### ISSUE THREAD

**Issue by suleman924** [MISP/MISP#9450]
### Support Questions

hello team,
i hope everyone is fine,
i don't know how much time i install components and upgrade the ubuntu machine but i miss something when i used the command of "Install.SH" iT'S SHOW THAT COMMAND NOT FOUND  or give me bash error if i copy paste the scripts i need it or want it to integerate with my logsign SIEm Kindly help me to do it .
Thank You 
Muhammad Suleman 

### MISP version

22.04

### Operating System

ubuntu

### Operating System version

20.04

### PHP version

i don't know 

### Browser

edge

### Browser version

updated

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Sorry, it's not very clear and lacking actual input and output errors.

**Comment by suleman924** [comment]
sir I need documentation to install misp in ubuntu latest document.
kindly if it's possible.
thank you so much for response.
