### ISSUE TITLE
Bug: stix2misp.py fails with missing timestamp

### ISSUE THREAD

**Issue by maciej-lech** [MISP/MISP#9453]
### Actual behavior

stix2misp.py fails with missing timestamp

### Expected behavior

stix2misp.py should not fail with missing timestamp as this field is optional
![image](https://github.com/MISP/MISP/assets/693906/c21bcdbb-a949-427b-bba9-3c46b1e517c2)

### Steps to reproduce

Try to convert stix1 indicator with missing optional timestamp.

### Version

2.4.182

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Do you have a sample file to share with us? you can also send it privately to info@circl.lu.

**Comment by maciej-lech** [comment]
I just tried to reproduce it with the latest `misp-docker` version, and it looks like the problem is no longer there, so I guess it was fixed between some versions. I am closing the ticket. Thank you for a quick replay!
