### ISSUE TITLE
Bug: No access to /api/openapi in 2.4.181/182

### ISSUE THREAD

**Issue by xme** [MISP/MISP#9463]
### Actual behavior

MISP 2.4.181, brand new, authentication is performed via AD/LDAP.
It's not possible to access /api/openapi/, the following error is displayed:
```
Something went wrong...
Unsupported OpenAPI Version: 3.1.0

Stack trace

m@https://10.243.x.x/js/redoc.standalone.js?v=157:37:52464
g/<@https://10.243.x.x/js/redoc.standalone.js?v=157:92:94509
r</<@https://10.243.x.x/js/redoc.standalone.js?v=157:92:94165
r<@https://10.243.x.x/js/redoc.standalone.js?v=157:92:93910
g@https://10.243.x.x/js/redoc.standalone.js?v=157:92:94389
t.bundle/<@https://10.243.x.x/js/redoc.standalone.js?v=157:92:97540
a@https://10.243.x.x/js/redoc.standalone.js?v=157:92:93967

ReDoc Version: 2.0.0-rc.53
Commit: 5c8524d
```

Note that the REST API works smoothly...

### Expected behavior

On a regular MISP (local auth), the page loads safely.

### Steps to reproduce

1. Log in
2. Go to Automation, click on the REST API link

### Version

2.4.181

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox

### Browser version

111.0.1

### Relevant log output

```shell
No error reported in logs :(
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
I'm not convinced this is actually related to the AD/LDAP auth, is it possible it is broken for all?

**Comment by iglocska** [comment]
Correct, one of the libraries needs to be updated on our side.

**Comment by xme** [comment]
Tx for the quick feedback! Yes, I mentioned the AD/LDAP because that was the main difference between the two servers, one was working, the 2nd not but it seems to not be related.

**Comment by iglocska** [comment]
This should be solved, make sure you ctrl f5 if you still have the issue!
