### ISSUE TITLE
Feature Request: Offer datasource merge of MysqlExtended and MysqlObserver

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#9469]
### Is your feature request related to a problem? Please describe.

Not a problem but rather an enhancement. As is now, we can only use `MysqlExtended` for the db query optimizations. Adding the ability to see `user_id` on those queries would be nice.

### Describe the solution you'd like

`MysqlExtended` does a great job optimizing some db queries. Likewise `MysqlObserver` providing `user_id` info with the db queries helps with issue diagnosis. Having a `datasource` offering both features would be quite useful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
This is since available as "MysqlObserverExtended"
