### ISSUE TITLE
Check "Encode Attachments" box on default

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#947]
So an export + import on a different MISP instance creates a new event with references to non-existing attachments. It would be nice if the attachments could be represented (base64?) inside the XML.

**Comment by elhoim** [comment]
I thought that "Download as..." links presented from the view of each event allowed to optionally export the attachments.
So I suppose what you want is to avoid references to non-existing attachments if the user does not choose to export the attachments in base64 in XML?

**Comment by RichieB2B** [comment]
I totally missed the "Encode Attachments" button, my bad. But yes, importing an export that does not contain the encoded attachments leads to dead references. The generic "The requested file was not found" error is factual correct, and I can live with that.

It would be more intuitive to have the "Encode Attachments" button checked by default IMHO.
