### ISSUE TITLE
Question: restSearch using `enforceWarninglist' filter returning the same result despite filter value 

### ISSUE THREAD

**Issue by trizzosk** [MISP/MISP#9487]
### Support Questions

Hello,

My objective is to create HTTP feed which will be used by firewall appliance for blocking. (Fortinet -> FortiOS -> HTTP simple text limited to 10MB).

My MISP instance is fully patched and up to date. I use `restSearch`:

```
curl --request POST \
  --url https://[REDACTED]/attributes/restSearch \
  --header 'Accept: application/json' \
  --header 'Authorization: [REDACTED]' \
  --header 'Content-Type: application/json' \

  --data '{
	"returnFormat": "text",
	"type": {
		"OR": [
			"ip-src",
			"ip-dst",
			"domain"
		]
	},
	"to_ids": 1,
	"enforceWarninglist": 1,
	"category": "Network activity",
	"tags":
	[
		"to-block"
	]
}'
```

For troubleshooting purpose I choose one event (`eventid` filter) where I see that some of the attributes are on some of active warninglists. Let's say we have eventid `8104` and we use `enforceWarninglist`

```
curl --request POST \
  --url https://[REDACTED]/attributes/restSearch \
  --header 'Accept: application/json' \
  --header 'Authorization: [REDACTED]' \
  --header 'Content-Type: application/json' \
  --data '{
	"returnFormat": "text",
	"eventid": "8104",
	"type": {
		"OR": [
			"ip-src",
			"ip-dst",
			"domain"
		]
	},
	"to_ids": 1,
	"enforceWarninglist": 1,
	"category": "Network activity",
	"tags":
	[
		"to-block"
	]
}'
```

It does not matter if I use `enforceWarninglist` set to `0` or `1`, I get the same result (total number of records returned are stored in response header `X-Result-Count`):

| enforceWarninglist | number of results |
| --- | --- |
| 0 |  6548 |
| 1 | 6548 |

If I open the event (8104) in browser, I see clearly that the event contains attributes of `network activity` (ip-src, ip-dst or domain) which are on warninglist (one or several). If I use filtering tool (warning exclude) in the list of attributes these, these are correctly filtered out. However using restSearch I get incorrect result. I am doing something wrong???

### MISP version

2.4.183

### Operating System

Ubuntu

### Operating System version

Ubuntu 20.04.6 LTS

### PHP version

PHP 7.4.3-4ubuntu2.19

### Browser

Chromium 

### Browser version

120.0.6099.199 (Official Build) built on Debian 12.4, running on Debian 12.4 (64-bit)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trizzosk** [comment]
P.S.: I searched forum and everyone says that this works. But seems to me that this not work.

**Comment by minisephirot** [comment]
Hello, I concur with @trizzosk :

This is my noise that I want removed in my extracts:
![image](https://github.com/MISP/MISP/assets/22344585/7b9fbbed-3efd-40f3-81f8-30d2b34eb7fa)

Using the rest search eventsearch route
`
{
    "returnFormat": "json",
    "eventid": "38744",
    "enforceWarninglist": "1"
}
`

This shows up in my rest response:
![image](https://github.com/MISP/MISP/assets/22344585/0e1f7817-c289-483a-9f24-e4e9231ae235)
This might be tied with the idea that my attribute is in an object...

Am I (-we-) doing something wrong @iglocska ?

**Comment by trizzosk** [comment]
In the last build 2.4.184, released recently, the search seems to be working properly. the search returns only attributes which are not in any from enabled warning lists.

**Comment by minisephirot** [comment]
Hi ! I concur with @trizzosk , upgrading to 2.4.184 fixed the filter on warning list (no idea why tho', the changelog was not explicit)
