### ISSUE TITLE
Date MISP Version 3.0?

### ISSUE THREAD

**Issue by perez1987** [MISP/MISP#949]
Is there an approximate date of version 3.0 of MISP?

**Comment by iglocska** [comment]
Nothing fixed date as of yet, it depends a lot on how priorities for other features shift, @adulau is already working on the objects for 3.0 over at https://github.com/MISP/misp-objects

**Comment by perez1987** [comment]
Thank you @iglocska. One question, can we contribute wit new objets to the proyect MISP-objects with our use cases?

**Comment by iglocska** [comment]
It's an ongoing process, all input is much appreciated. Just open a github issue if you have any additional ideas or create pull requests for it, whichever is more convenient for you!

**Comment by perez1987** [comment]
Thanks @iglocska ! Please close the issue

**Comment by adulau** [comment]
Don't hesitate to send PR to https://github.com/MISP/misp-objects if you have specific use cases. By the way, what's the missing feature in the current 2.4? Thanks a lot.

**Comment by iglocska** [comment]
Eeek, sorry about that, didn't realise I've closed this.

**Comment by perez1987** [comment]
Thanks for your answer @iglocska @adulau 

We will contribute our use cases the project so that you have in mind :-).

We we miss two main features in 2.4:
- Schema STIX (version 3.0)
- Import / Export automated file OpenIOC. We generate thousands of openioc daily and we need to automate the process to create community engagement indicators.
  https://github.com/MISP/MISP/issues/929

**Comment by perez1987** [comment]
@iglocska @adulau Do you know anything about the release date of version 3.0?

We are interested to import in stix by Rest API and Cyber Threat Intelligence Support structures: such as Campaigns, Threat Actors, TTPs, ...
