### ISSUE TITLE
SSL setup

### ISSUE THREAD

**Issue by Watnegutten** [MISP/MISP#951]
Hi there - just setting up my first MISP installation.
I realise that there's a small config script here: https://github.com/MISP/MISP/blob/2.4/INSTALL/apache.misp.ssl
although, there is no easy guide on how to get a valid ssl certificate.

I'm thinking of using letsencrypt for this - https://letsencrypt.org/howitworks/
Should you perhaps write some sort of howto or refer to one?

I feel encryption is important when setting up MISP especially when communicating with other MISP installations - so it's an important part of the infrastructure.

cheers
Watnegutten

**Comment by adulau** [comment]
It's indeed a very good point.  There is a good tutorial for letsencrypt at the following location:

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

Let us know if you have any feedback on your install. Like this we can update the configuration manuals to include letsencrypt.

Thank you very much.

**Comment by Watnegutten** [comment]
Well, this was easy... All i did was the following (running on CentOS 7.1):
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
./letsencrypt-auto

the final command brought me through a clean and easy installation asking me which http service I wanted to create certificates for, and whether or not I wanted https only and redirect http requests.

note that the domain azure.com which is where my server is deployed, was not happily accepted by letsencrypt. You might want to update your dns in order to have a specific domain name that will be accepted by letsencrypt.

all in all, this was surprisingly easy, but should be documented somewhere in the installation of MISP.

**Comment by Rafiot** [comment]
Thank you for the feedback, we will update the documentation.

**Comment by adulau** [comment]
The best nowadays is to use certbot (for letsencrypt). It works out-of-the-box with any public MISP instance. I'll close the issue. Feel free to reopen if the issue persists.
