### ISSUE TITLE
Bug: tag filter of galaxy_clusters/restsearch doesn't work

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#9511]
### Actual behavior

No filtering is applied based on this filter if provided.

### Expected behavior

Only the galaxy cluster with the specified connector tag is returned, if it exists.

### Steps to reproduce

On an instance with all default galaxies import, while logged in, go to:
https://<misp>/galaxy_clusters/restsearch/tag:misp-galaxy:threat-actor=%22Lazarus%20Group%22/limit:2

You'll see other clusters are returned as well / the filter is not applied.

### Version

2.4.183

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvandeplas** [comment]
fixed in PR #9512
