### ISSUE TITLE
Bug: Internal Error On Login

### ISSUE THREAD

**Issue by Turecky** [MISP/MISP#9526]
### Actual behavior

After press Login get onscreen error:
```
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.
```

### Expected behavior

Go to MISP Home page

### Steps to reproduce

Make login into system

### Version

v2.4.183 (c5737d6f676454db6f65ec1618b619a36c23c5e8)

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Chrome

### Browser version

120.0.6099.224

### Relevant log output

```shell
2024-01-29 08:12:27 Error: [TypeError] Argument 1 passed to User::checkIfUserIsValid() must be of the type array, null given, called in /var/www/MISP/app/Model/User.php on line 864
Request URL: /users/login?_=1706508694218
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(864): User->checkIfUserIsValid()
#1 /var/www/MISP/app/Model/UserLoginProfile.php(258): User->sendEmail()
#2 /var/www/MISP/app/Controller/UsersController.php(1373): UserLoginProfile->emailNewLogin()
#3 /var/www/MISP/app/Controller/UsersController.php(1245): UsersController->_postlogin()
#4 [internal function]: UsersController->login()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#9 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trizzosk** [comment]
This happens on my instance as well while I am using authentication with external identity provider (MS Entra ID, formerly Azure AD).
If I click on Events Actions - List Events, I can continue without any additional error.

**Comment by trizzosk** [comment]
Update: once I disable "Security.alert_on_suspicious_logins" the error disappears.

**Comment by Turecky** [comment]
@trizzosk Did you upgate to v2.4.184 (88f83ea295a7720037725ec415af0eb1e093fbf8)
Looks like it's fixed in new version.

**Comment by trizzosk** [comment]
@Turecky Thx, here I confirm that update to 2.4.184 fixed this.
