### ISSUE TITLE
Bug: Error in MISP Integration with IntelOwl

### ISSUE THREAD

**Issue by keid2000** [MISP/MISP#9560]
### Actual behavior

I Have this issues when I try connect IntelOwl with MISP.

I am sure that API and URL is correct.

![xasxaxaxaxaxasxasxaxasx](https://github.com/MISP/MISP/assets/159165053/e4b7529d-ac2d-48d6-9aa1-a14662530a37)

### Expected behavior

To run without error.

### Steps to reproduce

 Nothing

### Version

v2.4.184

### Operating System

Ubuntu

### Operating System version

22

### PHP version

idk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
This is happening because (quite clear from the error message), you are using a self-signed certificate for HTTPS on your MISP instance. You either have to use a certificate the machine you run pymisp on trusts (recommended), or tell pymisp not to verify certificates (not recommended).

**Comment by keid2000** [comment]
How I do that?
Which file that i can edit and make it to not verify the certificate 
I installed the MISP as docker compose.

**Comment by keid2000** [comment]
It works when I did this step in IntelOwl

![fasle](https://github.com/MISP/MISP/assets/159165053/e08674f9-4f0f-4d7b-9b4a-ddd3ead67fcc)
