### ISSUE TITLE
Bug: Some links point to /https:/

### ISSUE THREAD

**Issue by KhaledEid020** [MISP/MISP#9567]
### Actual behavior

I run MISP as a docker in the production environment. 
everything works normally, but when I choose some tabs, I get these errors.

![image](https://github.com/MISP/MISP/assets/46486159/50caa235-53cc-4e6a-83c6-289f62ee6c1f)

![sa](https://github.com/MISP/MISP/assets/46486159/540147c9-5196-4170-838d-a455027a8a3b)

![da](https://github.com/MISP/MISP/assets/46486159/f5c50478-dd34-427d-8700-45d2aeb0f34b)

### Expected behavior

To work normally 

### Steps to reproduce

none

### Version

2.4.184

### Operating System

Ubuntu

### Operating System version

22.2

### PHP version

idk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
The bug is triggered because MISP.baseurl is not set properly. If this is a bug in misp-docker or in MISP itself, i am not 100% sure. What are the env vars you use when starting the container? 
@ostefano

**Comment by ostefano** [comment]
@KhaledEid020 if you are using https://github.com/MISP/misp-docker post here the content of your `.env` file.

**Comment by KhaledEid020** [comment]
That is true. I found the error in the base URL; I did not include the **https://**.

Now what I need is to pull the docker again to save the updates in .env file?

**Comment by ostefano** [comment]
Just stop the containers, save the file, and start them again.

**Comment by KhaledEid020** [comment]
Thanks, it works.
