### ISSUE TITLE
An interface to extract artefacts from PDF/Text

### ISSUE THREAD

**Issue by Maijin** [MISP/MISP#957]
Don't know if that already is implemented but I doubt. Re-using https://github.com/armbues/ioc_parser by uploading a pdf || copy/pasting content in a textarea within MISP could quickly allow to extract all important information and correlate them in MISP then ask if the user want to add them in a new issues or not, it could even be extended to catch CVE and may more.

**Comment by iglocska** [comment]
We have something similar, we have a freetext import tool using our own parser on the event view that allows you to paste any text in there which will be parsed and converted to MISP attributes automatically. 

It's kind of well hidden, above the attributes, the middle icon in the second block of icons (Import from freetext).

**Comment by Maijin** [comment]
Very hard to find indeed, this could be enhanced :) OK then for the importing, but then it should also be possible to do a freetext search/correlation.

**Comment by iglocska** [comment]
Freetext search on the attributes? Within the event or overall?

**Comment by Maijin** [comment]
Yep, It should extract all the hashes, domain, and so from a bunch of text in a temporary event/interface and correlate them within the existing event.

**Comment by Rafiot** [comment]
Fixed
