### ISSUE TITLE
External Auth feature additions

### ISSUE THREAD

**Issue by wroersma** [MISP/MISP#960]
Is there any plan to add in ldap authentication support, or any other external authentication support?

**Comment by adulau** [comment]
There is an external authentication plug-in for X.509 client side authentication:

https://github.com/MISP/MISP/tree/2.4/app/Plugin/CertAuth

Similar module of authentication can be designed following that plug-in. Let us know if you have any question.

**Comment by negotrucky** [comment]
Hi, here a kerberos authentification : 
https://github.com/MISP/MISP/pull/976

Have fun

**Comment by serpap79** [comment]
I followed the guide, but shows no correct message authentication or validation error against the ad. Is there any way to that in the logs appear if it has been validated against ad or an error occurs. Thank you very much.

**Comment by truckydev** [comment]
Hi,

I have had some correction (fwrong php file name, add comment for error and add a variable for easy conf ) can you try ?
In my side all good this time :)

You can see wath's wrong in you apache logfile define in your site-available/misp.conf

**Comment by wroersma** [comment]
Could someone possibly provide me an example of their config for this? I think I'm doing something really stupid but can't figure it out.

**Comment by wroersma** [comment]
this is my current config if anyone can see anything that sticks out please let me know 

```
<?php
$config = array (
  'debug' => 0,
  'Security' =>
  array (
    'level' => 'medium',
    'salt' => 'somesaltkey',
    'cipherSeed' => '',
    'auth'=>array('ApacheSecureAuth'), // additional authentication methods
  ),
  'MISP' =>
  array (
    'baseurl' => 'https://misp.my-domain.com',
    'footermidleft' => '',
    'footermidright' => '',
    'org' => 'my-domain',
    'showorg' => true,
    'background_jobs' => true,
    'cached_attachments' => true,
    'email' => 'wroersma@my-domain.com',
    'contact' => 'wroersma@my-domain.com',
    'cveurl' => 'http://cve.circl.lu/cve/',
    'disablerestalert' => false,
    'default_event_distribution' => '1',
    'default_attribute_distribution' => 'event',
    'tagging' => true,
    'full_tags_on_event_index' => true,
    'footer_logo' => '',
    'take_ownership_xml_import' => false,
    'unpublishedprivate' => false,
    'disable_emailing' => false,
    'live' => true,
  ),
  'GnuPG' =>
  array (
    'onlyencrypted' => false,
    'email' => '',
    'homedir' => '',
    'password' => '',
    'bodyonlyencrypted' => false,
  ),
  'SMIME' =>
  array (
    'enabled' => false,
    'email' => '',
    'cert_public_sign' => '',
    'key_sign' => '',
    'password' => '',
  ),
  'Proxy' =>
  array (
    'host' => '',
    'port' => '',
    'method' => '',
    'user' => '',
    'password' => '',
  ),
  'SecureAuth' =>
  array (
    'amount' => 5,
    'expire' => 300,
  ),
   'ApacheSecureAuth' => // Configuration for kerberos authentification
    array(
        'apacheEnv' => 'REMOTE_USER', // If proxy variable = HTTP_REMOTE_USER
        'ldapServer' => 'ldap://my-ad-server.my-domain.com',    // fqdn or ip
        'ldapProtocol' => 3,
        'ldapReaderUser' => 'cn=mispreaduser,ou=cdnuser,dc=my-domain,dc=com', // DN ou RDN LDAP with reader user right
        'ldapReaderPassword' => 'password', //the ldap reader user password
        'ldapDN' => 'dc=my-domain,dc=com',
        'ldapSearchAttribut' => 'samaccountname', // filter for search. Maybe can be "samacountname"
        'ldapFilter' => array(
            'mail',
        ),
        'ldapDefaultRoleId' => 3,   // 3:User-1:admin. Maybe good to make 1 for the first user
        'ldapDefaultOrg' => '1',     // if not define default org = 1 misp org
    ),
);
```

**Comment by truckydev** [comment]
hi there,

I think it will be better to make 

``` php
'ldapDefaultOrg' => 'my-domain',
```

Next, take care of your misp.conf in apache2 if you want to use API.

But for your config.php, I don't see any mistake.

If you have any truble, don't hesitate :)

**Comment by wroersma** [comment]
Do you happen to have an updated version of what is mentioned here https://github.com/MISP/MISP/pull/976? maybe the edited file I could just pull down?

**Comment by wroersma** [comment]
Yeah It just doesn't work for me the page just has an error and doesn't prompt me for a login. I'm guessing I don't have my misp.conf in apache2 configured properly then. Right now I get the following error and can't figure anything out from the logs. No matter where I go it redirects me to https://misp.my-domain.com/users/login
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

```
<VirtualHost *:443>
        ServerAdmin me@me.local
        ServerName misp.my-domain.com
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                Order allow,deny
                allow from all
                  AuthLDAPBindDN "CN=ldapbinduser,OU=user,DC=my-domain,DC=com"
                  AuthLDAPBindPassword "ldapbindpassword"
                  AuthLDAPURL "ldap://my-ad-server-fqdn.my-domain.com/ou=user,dc=my-domain,dc=com?sAMAccountName?sub?(objectClass=*)"
                  AuthType Basic
                  AuthName "Use LDAP creds (XMPP server creds)"
                  AuthBasicProvider ldap
                  AuthUserFile /dev/null
                  require valid-user
                  AuthLDAPRemoteUserAttribute sAMAccountName
                  RewriteEngine On
                  RewriteCond %{LA-U:REMOTE_USER} (.+)
                  RewriteRule .* - [E=RU:%1]
                  RequestHeader set REMOTE_USER %{RU}e

        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/private/apache.crt
        SSLCertificateKeyFile /etc/ssl/private/apache.key

        LogLevel debug
        ErrorLog /var/log/apache2/misp.local_error.log
        CustomLog /var/log/apache2/misp.local_access.log combined
        ServerSignature Off
</VirtualHost>
```

**Comment by truckydev** [comment]
Here a sample I use : 

``` ini
<VirtualHost *:XXX>
        ServerAdmin me@me.local
        ServerName misp.local
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride FileInfo
        </Directory>
        <Location /users/login>
            AuthType Kerberos
            KrbMethodK5Passwd off
            KrbLocaluserMapping on
            KrbServiceName HTTP/my-ad-server@domain.com
            Krb5Keytab /protect/directory/krb5.keytab
            require valid-user
        </Location>
        LogLevel info
        ErrorLog /my/directory/log/misp.error.log
        CustomLog /my/directory/log/misp.access.log combined
        ServerSignature Off
</VirtualHost>
```

Can you take a look in your misp.local_error.log. 
If needed make apache log in debug mod :).

With this sample configuration, you use sso with apache. You just protect /user/login with the <location> directive because misp don't folow the standard and the API is not in /api/ URI for exemple. If you d'ont use this trick, you can't acces to Misp by using the API.

Your rewrite rules conf is normaly in .httaccess file, no ?

Hope this will helpful.

**Comment by wroersma** [comment]
we actually got this working thanks for all the help!

**Comment by rjzak** [comment]
For some reason, I am getting this in /var/www/MISP/app/tmp/logs/error.log:

`016-05-25 16:50:05 Error: [CakeException] Authentication adapter "ApacheSecureAuth" was not found.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(689): AuthComponent->constructAuthenticate()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#2 /var/www/MISP/app/Controller/AppController.php(193): AuthComponent->startup(Object(UsersController))
#3 /var/www/MISP/app/Controller/UsersController.php(31): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): UsersController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
`

My config.php:
`'Security' =>
  array (
    'level' => 'medium',
    'salt' => 'blahblahblah',
    'cipherSeed' => '',
    'password_policy_length' => 6,
    'auth'=>array('ApacheSecureAuth'), // additional authentication methods
  ),
...
  'ApacheSecureAuth' => // Configuration for kerberos authentication
    array(
        'apacheEnv' => 'REMOTE_USER',           // If proxy variable = HTTP_REMOTE_USER
        'ldapServer' => 'ldap://removed.my.org',   // FQDN or IP
        'ldapProtocol' => 3,
        'ldapReaderUser' => 'removed', // DN ou RDN LDAP with reader user right
        'ldapReaderPassword' => 'removed', // the LDAP reader user password
        'ldapDN' => 'dc=removed',
        'ldapSearchAttribut' => 'uid',          // filter for search
        'ldapFilter' => array(
            'mail',
        ),
        'ldapDefaultRoleId' => 3,               // 3:User, 1:admin. May be good to set "1" for the first user
        'ldapDefaultOrg' => 'myorg',      // uses 1st local org in MISP if undefined

`

My apache config for user login works, and I can see in the logs that my username appears. So it's a PHP/Cake issue I think.

**Comment by rjzak** [comment]
It seems the issue is that CakePHP is trying to handle ApacheSecureAuth by looking for the class in `/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/` but the code that handles ApacheSecureAuth is in `/var/www/MISP/app/Controller/Component/`. How can this be remedied?

**Comment by truckydev** [comment]
Hi,

In your config.php, you don't need this line and you can remove it.

``` php
'auth'=>array('ApacheSecureAuth'), // additional authentication methods
```

because, in appControler.php you have this test : 

``` php
if (isset($_SERVER[$envvar])) {
            $this->Auth->className = 'ApacheSecureAuth';
```

if apache return 'apacheEnv' => '**REMOTE_USER**', as your conf file,

ApacheSecureAuth class will be use for authentification else, it's the classque methode.

**Comment by giedriusramas** [comment]
Hi, @wroersma 
Could you please share your config that is working for you , as I cannot get working MISP with LDAP/Kerberos.

**Comment by masual** [comment]
> Hi, @wroersma
> Could you please share your config that is working for you , as I cannot get working MISP with LDAP/Kerberos.

@giedriusramas
Do you manage to get it working?

**Comment by bpavesi** [comment]
Hello,
it's also possibile to integrate google Authenticator? If yes, how? It's necessary to develop an authentication plugin or use a reverse proxy?
Somewhere it's avaiable a guide regarding this topic?
