### ISSUE TITLE
Problem with NAT address?

### ISSUE THREAD

**Issue by infracritical** [MISP/MISP#961]
I am trying to implement the MISP application onto CentOS v6.x (the documentation for the install is _very_ well done -- thank you).  I have the server _behind_ several firewalls (three, actually).  With each firewall, the IP address is changed via NAT.

From an externally-facing IP address, the server is (the IP address and port numbers are **FAKE** 162.32.214.35:10914 whereby the IP address is the external IP address, the port number "10914" is the external service port.  This gets translated (finally) to 192.1.214.35:443.

Accessing the server is NO problem.

However...

When I attempt at accessing any of the pull-down menus on the top, or the side menus on the left, they all show 192.1.214.35:10914.  This is completely incorrect.

Is there any method of fixing this?

-rad

**Comment by infracritical** [comment]
BTW, I am running the latest version of the software.

Also, I have RTFM'd the documentation regarding NAT'd addresses -- Honestly, I couldn't find anything.

**Comment by infracritical** [comment]
Nevermind....I didn't fully RTFM...._DOH_!!!

**Comment by iglocska** [comment]
Quickest issue resolution ever!  :) 

For anyone looking for this, you can set the MISP.baseurl setting in the config file found at /var/www/MISP/app/Config/config.php
