### ISSUE TITLE
Support: Proxy issue for pull data

### ISSUE THREAD

**Issue by enzok00** [MISP/MISP#9611]
### Support Questions

I have a MISP instance located behind a proxy.
The proxy is correctly configured in the MISP settings + in the .bashrc of the misp user, which works because in diagnostics I have: Proxy settings…OK

The problem is that some of the flows leaving the application pass through the proxy, while others do not. Indeed, when I do a "Connection test", a "Sync user", or an "Explore" on a remote server, I see with tcpdump that the outgoing flows go through the proxy. However, when I try "pull all", the streams try to access the remote server's url directly. Same thing when I try to fetch feeds, the feeds go direct to the URLs, and are therefore blocked, giving a curl error 28 'Timeout was reached'.

When I click on connection test (work):
09:41:48.561788 IP _my-misp-incstance_.52890 > _proxy-ip_.http-alt: Flags [S], seq 254750140, win 64240, options [mss 1460,sackOK,TS val 1704315371 ecr 0,nop,wscale 7], length 0

When I click on pull all (don't work):
09:42:28.607514 IP _my-misp-incstance_.55916 > _remote-server-ip_.https: Flags [S], seq 2656786906, win 64240, options [mss 1460,sackOK,TS val 2321234548 ecr 0,nop,wscale 7], length 0

### MISP version

2.4.186

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Microsoft Edge

### Browser version

122.0.2365.66

### Relevant log output

```shell
2024-03-07 09:42:58 Error: Could not get remote server `EATM-CERT` version.
[SocketException] curl error 28 'Timeout was reached': Connection timed out after 30001 milliseconds
Stack Trace:
#0 /var/www/html/MISP/app/Lib/Tools/CurlClient.php(81): CurlClient->internalRequest()
#1 /var/www/html/MISP/app/Lib/Tools/ServerSyncTool.php(510): CurlClient->get()
#2 /var/www/html/MISP/app/Lib/Tools/ServerSyncTool.php(370): ServerSyncTool->get()
#3 /var/www/html/MISP/app/Model/Server.php(610): ServerSyncTool->info()
#4 /var/www/html/MISP/app/Console/Command/ServerShell.php(149): Server->pull()
#5 /var/www/html/MISP/app/Console/Command/AppShell.php(48): ServerShell->pull()
#6 /var/www/html/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#7 /var/www/html/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#8 /var/www/html/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#9 /var/www/html/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#10 /var/www/html/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#11 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
A very similar bug to this was fixed in, i think, .185. Please make sure you have restarted all your workers since upgrading.

**Comment by enzok00** [comment]
That's it, restart the workers just solved the problem.
Thank you Kagee
