### ISSUE TITLE
Bug: Event view, attribute focus not working

### ISSUE THREAD

**Issue by DemBackfisch** [MISP/MISP#9617]
### Actual behavior

When opening an event URL with the focus towards a specific attribute, e.g. `https://misp-domain.example/events/view/{event-id}/focus:{attribute-uuid}`, the event view is opened correctly but the focus is not shifted towards the attribute related to the attribute-uuid.

### Expected behavior

The last version I know where this is working is 2.4.176. I did not test this with any other version between 2.4.176 and 2.4.186.
In v2.4.176, when opening an event URL with the focus towards a specific attribute, e.g. `https://misp-domain.example/events/view/{event-id}/focus:{attribute-uuid}`, the event view is opened correctly and the focus is also automatically shifted on the attribute related to the attribute-uuid.

### Steps to reproduce

Open Event Actions > Search Attribute and search for any attribute thats attached to any MISP event in your instance. After the search is done click on the first event ID that comes up to open the event view for this event. Your browser will open a URL in the format `https://misp-domain.example/events/view/{event-id}/focus:{attribute-uuid}`.

### Version

2.4.186

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marjatech** [comment]
Same issue here on 2.4.188. Might be related to the new feature added to load Event View faster for big Events?

**Comment by marjatech** [comment]
@iglocska can you or someone have a look here? 
Think it might be an easy fix..

**Comment by marjatech** [comment]
ah, nevermind. Seems to be working again with v2.4.192 👍
