### ISSUE TITLE
Feature Request: Upgrade PHP for 8.X version

### ISSUE THREAD

**Issue by tutueh** [MISP/MISP#9625]
### Is your feature request related to a problem? Please describe.

Currently, MISP is using PHP 7.4, but it's at the end of its life cycle, and this version presents vulnerabilities that will not be corrected.

### Describe the solution you'd like

Upgrade to a supported version.

### Additional context

Many companies are not using MISP because of policies; they can't use software that is based on an end-of-life version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kagee** [comment]
7.4 is still part of supported LTS Linux releases.
MISP 2.4 can not support PHP > 7.4.
MISP 3 (currently in development) supports PHP 8.*.
