### ISSUE TITLE
You have tripped the cross-site request forgery protection of MISP

### ISSUE THREAD

**Issue by gritty-Kitty** [MISP/MISP#9629]
### Support Questions

Currently installed version… v2.4.187 (661b238b3f4b8aecc25f32915a74a8eb0514f775)
Fresh installation within Ubuntu 22.04 LTS/Docker/Portainer using https://github.com/MISP/misp-docker project.

---

We find that MISP does not refresh the webpages after submitting forms, i.e., login, adding new users, etc. Pressing F5 will yield the "You have tripped the cross-side request forgery protection of MISP" warning, but then we are able to navigate away and verify that we were able to log in, that new users were indeed created, etc.

Behaviour appears on multiple workstations with Edge/CHROME (so far tested).

Any insight is appreciated.

Has anyone seen/resolved 

### MISP version

2.4.187

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Browser

Edge, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thetechhouse** [comment]
check /var/www/MISP/app/tmp/logs/error.log for clues. I had a similar issue which was down to php being unable to talk to the redis server, which in turn was due to funky characters in the redis password.

**Comment by gritty-Kitty** [comment]
Thank you for the feedback. The issue has mysteriously evaporated.
