### ISSUE TITLE
style problem with filters on view event page with firefox

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#963]
When using Firefox (44.0.2) there is a style problem with the filters on the view event page.
![screenshot from 2016-02-22 09-08-33](https://cloud.githubusercontent.com/assets/1073662/13212783/26a119a6-d944-11e5-8068-eb57aed64a6a.png)

With chrome it is displayed correctly
![screenshot from 2016-02-22 09-13-20](https://cloud.githubusercontent.com/assets/1073662/13212813/88a4c45e-d944-11e5-927e-935154145fa6.png)

**Comment by iglocska** [comment]
Weird, looks like this to me on 44.0.2:

https://i.imgur.com/GYHsZQ9.png

Could you ctrl+f5 in case you still have the old css cached?

**Comment by cvandeplas** [comment]
Silly me. That fixed it. 
Thanks !

**Comment by iglocska** [comment]
Not silly at all, this is a good point that we should look into appending the version number as a query string when loading the css / js to avoid this!
