### ISSUE TITLE
An Internal Error Has Occurred

### ISSUE THREAD

**Issue by infracritical** [MISP/MISP#964]
Tried adding in an event.  Didn't matter what was typed; regardless, always got the following message below:

**An Internal Error Has Occurred.
Error:  An Internal Error Has Occurred.**

**Comment by iglocska** [comment]
Could you check your error log in /var/www/MISP/app/tmp/logs/error.log what
the latest entry and attach stack trace is?

**Comment by infracritical** [comment]
2016-02-22 15:16:57 Error: [Exception] DateTime::__construct() [<a href='http://php.net/datetime.construct'>datetime.construct</a>]: It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(1809): DateTime->__construct()
#1 /var/www/MISP/app/Controller/EventsController.php(902): Event->_add(Array, false, Array, '', NULL, false, NULL, 0, Array)
#2 [internal function]: EventsController->add()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2016-02-22 15:18:10 Warning: Warning (2): strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128 call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167 [main] - APP/webroot/index.php, line 92

2016-02-22 15:18:10 Warning: Warning (2): date() [<a href='http://php.net/function.date'>function.date</a>]: It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php, line 1852]
Trace:
date - [internal], line ??
call_user_func - [internal], line ??
Model::_doSave() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1852
Model::save() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1751
UsersController::__extralog() - APP/Controller/UsersController.php, line 895
UsersController::logout() - APP/Controller/UsersController.php, line 701
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167 [main] - APP/webroot/index.php, line 92

2016-02-22 15:18:10 Warning: Warning (2): date() [<a href='http://php.net/function.date'>function.date</a>]: It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Plugin/SysLog/Lib/SysLog.php, line 82]
Trace:
date - [internal], line ??
SysLog::write() - APP/Plugin/SysLog/Lib/SysLog.php, line 82
UsersController::__extralog() - APP/Controller/UsersController.php, line 901
UsersController::logout() - APP/Controller/UsersController.php, line 701
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167 [main] - APP/webroot/index.php, line 92

2016-02-22 15:18:10 Warning: Warning (2): strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128 call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167 [main] - APP/webroot/index.php, line 92

**Comment by infracritical** [comment]
BTW, I _did_ set the timezone accordingly.  My question is this: why would it complain about the timezone, then fault out?

**Comment by infracritical** [comment]
Also...

This was the initial error, which is what I think caused MISP to puke...

2016-02-22 15:09:16 Warning: Warning (2): date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php, line 134]
Trace:
date - [internal], line ??
FileLog::write() - APP/Lib/cakephp/lib/Cake/Log/Engine/FileLog.php, line 134
CakeLog::write() - APP/Lib/cakephp/lib/Cake/Log/CakeLog.php, line 442
ErrorHandler::_log() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 188
ErrorHandler::handleException() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 118 [main] - [internal], line ??

2016-02-22 15:09:16 Error: [BadRequestException] csrf Request URL: /events/add Stack Trace:
#0 [internal function]: AppController->blackhole('csrf')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(622): call_user_func_array(Array, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(337): SecurityComponent->_callback(Object(EventsController), 'blackHole', Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(242): SecurityComponent->blackHole(Object(EventsController), 'csrf')
#4 [internal function]: SecurityComponent->startup(Object(EventsController))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#6 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#11 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2016-02-22 15:09:18 Warning: Warning (2): strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128 call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167 [main] - APP/webroot/index.php, line 92

**Comment by infracritical** [comment]
Tried this with other variations.  I noticed on the last test of warnings were all precipitated by an error:

2016-02-22 16:43:00 Error: [Exception] DateTime::__construct() [<a href='http://
php.net/datetime.construct'>datetime.construct</a>]: It is not safe to rely on t
he system's timezone settings. You are _required_ to use the date.timezone setti
ng or the date_default_timezone_set() function. In case you used any of those me
thods and you are still getting this warning, you most likely misspelled the tim
ezone identifier. We selected the timezone 'UTC' for now, but please set date.ti
mezone to select your timezone.
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(1809): DateTime->__construct()
#1 /var/www/MISP/app/Controller/EventsController.php(902): Event->_add(Array, fa
lse, Array, '', NULL, false, NULL, 0, Array)
#2 [internal function]: EventsController->add()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): Reflec
tionMethod->invokeArgs(Object(EventsController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controlle
r->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatche
r->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequ
est), Object(CakeResponse))
#7 {main}
2016-02-22 16:43:03 Warning: Warning (2): strtotime(): It is not safe to rely on
 the system's timezone settings. You are _required_ to use the date.timezone set
ting or the date_default_timezone_set() function. In case you used any of those
methods and you are still getting this warning, you most likely misspelled the t
imezone identifier. We selected the timezone 'UTC' for now, but please set date.
timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Con
troller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Compone
nt/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/Sec
urityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.
php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.p
hp, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.ph
p, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 18
9
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1
67
[main] - APP/webroot/index.php, line 92

2016-02-22 16:55:00 Warning: Warning (2): strtotime(): It is not safe to rely on
 the system's timezone settings. You are _required_ to use the date.timezone set
ting or the date_default_timezone_set() function. In case you used any of those
methods and you are still getting this warning, you most likely misspelled the t
imezone identifier. We selected the timezone 'UTC' for now, but please set date.
timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Con
troller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Compone
nt/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/Sec
urityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.
php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.p
hp, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.ph
p, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 18
9
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1
67
[main] - APP/webroot/index.php, line 92

2016-02-22 16:55:00 Warning: Warning (2): date() [<a href='http://php.net/functi
on.date'>function.date</a>]: It is not safe to rely on the system's timezone set
tings. You are _required_ to use the date.timezone setting or the date_default_t
imezone_set() function. In case you used any of those methods and you are still
getting this warning, you most likely misspelled the timezone identifier. We sel
ected the timezone 'UTC' for now, but please set date.timezone to select your ti
mezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php, line 1852]
Trace:
date - [internal], line ??
call_user_func - [internal], line ??
Model::_doSave() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1852
Model::save() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 1751
UsersController::__extralog() - APP/Controller/UsersController.php, line 895
UsersController::logout() - APP/Controller/UsersController.php, line 701
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php,
 line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 19
3
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1
67
[main] - APP/webroot/index.php, line 92

2016-02-22 16:55:00 Warning: Warning (2): date() [<a href='http://php.net/functi
on.date'>function.date</a>]: It is not safe to rely on the system's timezone set
tings. You are _required_ to use the date.timezone setting or the date_default_t
imezone_set() function. In case you used any of those methods and you are still
getting this warning, you most likely misspelled the timezone identifier. We sel
ected the timezone 'UTC' for now, but please set date.timezone to select your ti
mezone. in [/var/www/MISP/app/Plugin/SysLog/Lib/SysLog.php, line 82]
Trace:
date - [internal], line ??
SysLog::write() - APP/Plugin/SysLog/Lib/SysLog.php, line 82
UsersController::__extralog() - APP/Controller/UsersController.php, line 901
UsersController::logout() - APP/Controller/UsersController.php, line 701
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php,
 line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 19
3
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1
67
[main] - APP/webroot/index.php, line 92

2016-02-22 16:55:00 Warning: Warning (2): strtotime(): It is not safe to rely on
 the system's timezone settings. You are _required_ to use the date.timezone set
ting or the date_default_timezone_set() function. In case you used any of those
methods and you are still getting this warning, you most likely misspelled the t
imezone identifier. We selected the timezone 'UTC' for now, but please set date.
timezone to select your timezone. in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Con
troller/Component/SecurityComponent.php, line 552]
Trace:
strtotime - [internal], line ??
SecurityComponent::generateToken() - APP/Lib/cakephp/lib/Cake/Controller/Compone
nt/SecurityComponent.php, line 552
SecurityComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/Sec
urityComponent.php, line 245
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.
php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.p
hp, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.ph
p, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 18
9
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 1
67
[main] - APP/webroot/index.php, line 92

**Comment by infracritical** [comment]
I've managed to fix the problem.

Under "/var/www/MISP/app/Model", within the "Event.php" file, at the top of the file, I added one line:

date_default_timezone_set('America/Chicago');

This was inserted within the code thus:

<?php
**date_default_timezone_set('America/Chicago');**
App::uses('AppModel', 'Model');
App::uses('CakeEmail', 'Network/Email');
App::import('Controller', 'Attributes');
Configure::load('config'); // This is needed to load GnuPG.bodyonlyencrypted

As such, I was able to correct the problem.  The "/var/www/MISP/app/tmp/logs/error.log" showed this:

2016-02-23 13:26:43 **Error: [Exception] DateTime::__construct() [<a href='http://**
**php.net/datetime.construct'>datetime.construct</a>]: It is not safe to rely on t**
**he system's timezone settings. You are _required_ to use the date.timezone setti**
**ng or the date_default_timezone_set() function. In case you used any of those me**
**thods and you are still getting this warning, you most likely misspelled the tim**
**ezone identifier. We selected the timezone 'UTC' for now, but please set date.ti**
**mezone to select your timezone.**
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(1809): DateTime->__construct()
#1 /var/www/MISP/app/Controller/EventsController.php(902): Event->_add(Array, fa
lse, Array, '', NULL, false, NULL, 0, Array)
#2 [internal function]: EventsController->add()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): Reflec
tionMethod->invokeArgs(Object(EventsController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controlle
r->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatche
r->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequ
est), Object(CakeResponse))
#7 {main}

# 

I suspect that I will have to modify the other files as well.  Do any of you know what other files that I should work on?  If you could give me a listing of .php files, I could confirm this, and report the results here.

**Comment by iglocska** [comment]
Woah, you really shouldn't have to do that.

Did you try to do this from the install guide?

echo 'date.timezone = "Europe/Amsterdam"' >
/etc/opt/rh/rh-php56/php-fpm.d/timezone.ini
ln -s ../php-fpm.d/timezone.ini /etc/opt/rh/rh-php56/php.d/99-timezone.ini

Let me know if this doesn't fix it for you!

**Comment by infracritical** [comment]
Nope.  Still get the same error.

**Comment by infracritical** [comment]
Just so you know...

[root@server /etc/opt/rh/rh-php56/php-fpm.d]# echo 'date.timezone = "America/Chicago"' > timezone.ini
[root@server php.d]# more 99-timezone.ini
date.timezone = "America/Chicago"
[root@server php.d]# ln -s /etc/opt/rh/rh-php56/php-fpm.d/timezone.ini /etc/opt/rh/rh-php56/php.d/99-timezone.ini

Still the same results.  Am I doing something wrong here?

Either way, the clusterkludge that I did appears to work...

**Comment by iglocska** [comment]
Weird, should work. You could also just set it in your php.ini (the one
used by php5.6) by adding the following:

date.timezone = "America/Chicago"

Alternatively, if all else fails, you could add

date_default_timezone_set('America/Chicago');

as the first line in /var/www/MISP/app/Config/bootstrap.php

Let me know if that works!

**Comment by infracritical** [comment]
I wonder if the choice of O/S has anything to do with this?

As I know that you both are based out of Europe, usually Debian-flavours of Linux (such as Ubuntu) are the more preferred choice.  I am running CentOS 6.7 (recently patched for the 'glibc' vulnerability).

**Comment by infracritical** [comment]
Made the change to 'bootstrap.php'....yup...that did the trick.  Thanks!  ;)

**Comment by infracritical** [comment]
I am certain that, because the date.timezone feature is global, that it would make much better sense to put it into a globalized .php script.  Having it within 'bootstrap.php' is the most logical choice.

Again...thanks for that tidbit!

**Comment by RichieB2B** [comment]
Debian and Ubuntu provides a date.timezone in php.ini out of the box. RedHat/CentOS does not. This effectively breakes all php apps. Strange the steps from the MISP CentOS installation guide did fix this.

**Comment by infracritical** [comment]
I don't know, but somehow, it didn't work.

What I had to resort to was entering in a single-lined entry within "/var/www/MISP/app/Config/bootstrap.php".  That seemed to do the trick.

I am running this application on CentOS 6.7.  Our 'customers' use slightly older version of Version 6.

BTW, I am going to go thru the installation steps again with a fresh copy of the application onto another server, and see if I encounter the same problem (again).  If I do, it might be a good idea to modify the installation instructions for CentOS 6.

Additionally, I prefer Red Hat/CentOS over Ubuntu, mostly because I do active development for Red Hat.  Our 'customers' **only** use Red Hat because of its stability (not that I am inferring that Ubuntu isn't stable; but for our 'customers', their standard is "Red Hat").

**Comment by RichieB2B** [comment]
Did you restart php after changing the ini files? I think they are only read at startup.

**Comment by infracritical** [comment]
I removed the entry out of the "bootstrap.php" file, and kept the "timezone.ini" file (and its link) in place.  Then I restarted Apache.

Survey says???

"X X X"

No-go.  Same error message.  When I put the entry back into "bootstrap.php" -- hahzah -- it worked!  This is probably something goofy with RH/CentOS 6.

**Comment by infracritical** [comment]
I didn't think about this until now...

Because this application is using "rh-php56", I checked to see if there were now 2 copies of "php".  Yup, there is.

I am running CentOS 6.7.  It was recently patched for the "glibc" vulnerability.

"php -v" reveals:

PHP 5.3.3 (cli) (built: Feb  9 2016 10:36:17)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

...whereas "/etc/opt/rh/rh-php56/root/usr/bin/php -v" reveals:

PHP 5.6.5 (cli) (built: Jun 29 2015 08:20:04)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

So...I am thinking that there is some confusion perhaps?  Then again, RH/CentOS does do some screwy things... :(

**Comment by RichieB2B** [comment]
Absolutely. MISP is using php 5.6 through the rh-php56-php-fpm service which needs to be restarted when you make changes. The php 5.3 will typically be used with mod_php which only requires an Apache restart because the web server loads mod_php which starts php. Restarting Apache does not restart the php 5.6 workers. You need to restart the rh-php56-php-fpm service instead.

**Comment by infracritical** [comment]
Man...do I feel foolish.  Then again...I've never used "rh-php56" before...first time.
