### ISSUE TITLE
Sync servers - push rules not functional

### ISSUE THREAD

**Issue by west791** [MISP/MISP#967]
Hi

I tested if an event would be blocked to be pushed if it has a special tag on it, the push rules in the sync server settings. When I initiated a push, the event was pushed. Is this meant to be like this or shouldn't it rather be blocked from the push? 

Greetings

west

**Comment by Rafiot** [comment]
Did you mark the tag as not to push in the sync config? If yes, it is a bug. 

Can you please post here a print screen of the configuration screen?

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
