### ISSUE TITLE
Feature Request: Suricata API 

### ISSUE THREAD

**Issue by gordnhoo** [MISP/MISP#9699]
### Is your feature request related to a problem? Please describe.

I dont know if this is a problem currently but im trying to fetch https://<misp url>/events/nids/suricata/download for suricata unfortunetly im not getting anything back i need to use this API because suricata uses suricata-update and doesn't allow for POST requests is this an error ?

### Describe the solution you'd like

On the other hand i'm able to use curl -X POST -k -H 'Accept: application/json' -H 'Authorization: API_KEY' -H 'Content-Type: application/json' -o misp.suricata.rules 'https://misp/attributes/restSearch' --data '{ "returnFormat": "suricata"}'
and i get the rules needed.
Right now it's prefered to use suricata-update for suricata rules updating so i wanted to keep that principle instead of creating a script to make sure suricata was updated.

### Describe alternatives you've considered

Would it be possbile to create or fix the API point i'm trying to use

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
You can work around that with restsearch, it actually allows for passing the parameters in the URL and using a GET request:

GET `https://misp/attributes/restSearch/returnFormat:suricata`

should get the trick done.

**Comment by gordnhoo** [comment]
Ah thank you I didn't see that in the documentation ,is there a way to limit the amount of data i fetch with this command? right now i'm getting more rules than what i need and i only want from the last 7 days.once again thank you  for responding so quickly

**Comment by gordnhoo** [comment]
Ah got it thank you.
https://misp.restena.lu//attributes/restSearch/returnFormat:suricata/publish_timestamp:7d

**Comment by gordnhoo** [comment]
https://misp/attributes/restSearch/returnFormat:suricata/publish_timestamp:7d
