### ISSUE TITLE
Bug: Turning on Plugin.Benchmarking breaks web interface when MISP.system_setting_db=true

### ISSUE THREAD

**Issue by microblag** [MISP/MISP#9702]
### Actual behavior

When using MISP.system_setting_db=true if the new benchmarking plugin is enabled then the web interface is broken.

### Expected behavior

Turning on the the benchmarking when using MISP.system_setting_db=true does not break the web interface

### Steps to reproduce

1. in config.php set MISP.system_setting_db to true
2. from the Server Settings & Maintenance->Plugins set Plugin.Benchmarking_enable to true

### Version

2.4.190

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome

### Browser version

122

### Relevant log output

```shell
2024-04-22 04:11:56 Error: [Error] Call to a member function stopBenchmark() on null
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(23): AppController->afterFilter()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(697): BetterCakeEventManager->dispatch()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(204): Controller->shutdownProcess()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#4 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#5 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microblag** [comment]
I believe the cause of the problem is when the benchmarking state is checked in the AppController->beforeFilter method, settings have not yet been loaded from the db. As such benchmarking is always set as disabled and the Benchmark property of AppController is never set. However when the afterFilter is run, db settings have been loaded so benchmarking is set as enabled and so there is an attempt to call stopBenchmark on the Benchmark property.

**Comment by iglocska** [comment]
I couldn't reproduce the issue, though I can see it being an issue due to the reason described by @microblag - so I've pushed a speculative fix, please let me know if it persists for you.

The fix rearranges the order of beforefilter(), loading the settings as well as including a fallback to not execute the stopBenchmarking() function if the benchmarking suite isn't loaded for whatever reason.
