### ISSUE TITLE
Bug: MISP.default_event_threat_level not used when creating Event from UI 

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#9714]
### Actual behavior

Adding a new event, the default value for the threat level will always be `High`. 

### Expected behavior

The default of the dropdown would take over the configuration value from MISP.default_event_threat_level

### Steps to reproduce

- configure MISP.default_event_threat_level as e.g. `Low`
- Click on Add Event 

### Version

2.4.191

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Fixed on develop, it will be in the release today.

**Comment by iglocska** [comment]
Thanks for the notification, must have been a pretty damn long lasting regression!
