### ISSUE TITLE
Bug: When ZeroMQ is enabled, the Publish Event workflow action does not work and generates an error

### ISSUE THREAD

**Issue by microblag** [MISP/MISP#9722]
### Actual behavior

When ZeroMQ is enabled and the Publish Event workflow task runs the below error is seen in the application log:

Execution encountered an error but continued.
Node `publish-event` (5) from Workflow `Workflow for trigger event-after-save-new` (5) returned the following error: Error while executing module publish-event. Error: Invalid user ID. 

### Expected behavior

No Error

### Steps to reproduce

1. Enable ZeroMQ
2. create a workflow which has a Publish Event task in it.
3. Trigger the publish event task using an event-after-save-new trigger

### Version

2.4.191

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

All

### Browser version

N/A

### Relevant log output

```shell
Execution encountered an error but continued.
Node `publish-event` (5) from Workflow `Workflow for trigger event-after-save-new` (5) returned the following error: Error while executing module publish-event. Error: Invalid user ID.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microblag** [comment]
We've had a dig into the code and suspect the problem is caused due to the Configuration value 'CurrentUserId' not being set in background job contexts. Which causes line 4760 of app/Model/Event.php `$currentUserId = Configure::read('CurrentUserId');` to fail. This code is only evaluated if ZeroMQ is enabled or Kafka is enabled and has publish notifications enabled or the Workflow Publish trigger is enabled and has a listener.

A possible solution may be to add an extra parameter containing the 'CurrentUserId' value when enqueue a background job for executeWorkflowForTrigger.

starting on line 456 of app/Model/Workflow.php
```
            $this->Job->getBackgroundJobsTool()->enqueue(
                BackgroundJobsTool::PRIO_QUEUE,
                BackgroundJobsTool::CMD_WORKFLOW,
                [
                    'executeWorkflowForTrigger',
                    $trigger_id,
                    JsonTool::encode($data),
                    JsonTool::encode($logging),
                    $jobId,
                    JsonTool::encode(Configure::read('CurrentUserId'))
                ],
                true,
                $jobId
            );
```
add below line 19 of app/Console/Command/WorkflowShell.php
```
Configure::write('CurrentUserId', JsonTool::decode($this->args[4]));
```

However we aren't sure if this would violate the security design of background jobs.

**Comment by mokaddem** [comment]
Hey there,
Thanks for the bug report and the provided fix.
It's been merged in `develop` (https://github.com/MISP/MISP/commit/b5ce3e99a4eca0c965b9e87f7d85557a5c2fbe9e).
Cheers!
