### ISSUE TITLE
Upgrade from 2.3.178 to 2.4 removes src-orgs and member-org

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#973]
Hi,

Started upgraded from 2.3.178. 
One of the steps
`git rm --cached app/Plugin/CakeResque/`
caused
`fatal: pathspec 'app/Plugin/CakeResque/'` 
did not match any files

Afterwards in the inferface (debug on) there was
`
Notice (8): Undefined index: perm_sharing_group [APP/Controller/AppController.php, line 268]
Notice (8): Undefined index: org_id [APP/Model/AppModel.php, line 436]
`
and the columns with Source org & Member org are empty.

kr,
koen

**Comment by iglocska** [comment]
Interesting, I think I know what's up.

Could you run the two following commands and try again after? 

rm /var/www/MISP/app/tmp/cache/persistent/myapp*
rm /var/www/MISP/app/tmp/cache/model/myapp*

**Comment by cudeso** [comment]
No win :(
The notice of perm_sharing_group is gone but undefined index remains.

Also when trying to run servers/upgrade2324 I get
`Notice (8): Undefined index: org_id [APP/Model/AppModel.php, line 436]`

**Comment by iglocska** [comment]
And you ran this before, right?

upgrade_2.4.sql
https://github.com/MISP/MISP/blob/2.4/INSTALL/upgrade_2.4.sql

**Comment by cudeso** [comment]
If I remember correctly I ran it both before and after. Tried a new run and also killed the running workers first.
Upgrade seems to work out, organisations are listed.

Thanks!

**Comment by iglocska** [comment]
Glorious victory!
