### ISSUE TITLE
Support: Proxy Issue in misp

### ISSUE THREAD

**Issue by bilalsarwar16** [MISP/MISP#9730]
### Support Questions

Proxy in not working in Misp. Connection timed out error is occured when i try ti fetch any feed. It looks like Misp in unable to direct its traffic to proxy.

### MISP version

2.4.191

### Operating System

20.

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Firefox

### Browser version

125.0.3 (64 bit)

### Relevant log output

```shell
[SocketException] curl error 28 'Timeout was reached': Failed to connect to csp.infoblox.com port 443: Connection timed out 6704
Stack Trace: 
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(89): CurlClient->internalRequest()
#1 /var/www/MISP/app/Model/Feed.php(2136): CurlClient->get()
#2 /var/www/MISP/app/Model/Feed.php(2096): Feed->getFollowRedirect()
#3 /var/www/MISP/app/Model/Feed.php(343): Feed->feedGetUriRemote()
#4 /var/www/MISP/app/Model/Feed.php(382): Feed->getFreetextFeedRemote()
#5 /var/www/MISP/app/Model/Feed.php(1229): Feed->getFreetextFeed()
#6 /var/www/MISP/app/Console/Command/Servershell.php(411): Feed->downloadFromFeedlnitiator()
#7 /var/www/MISP/app/Console/Command/AppShell.php(60): ServerShell->fetchFeed()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#13 {main}
```

### Extra attachments

![proxy](https://github.com/MISP/MISP/assets/99896232/ac3016c9-8476-494f-adc1-cf2c257b6ee2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalsarwar16** [comment]
ubuntu version is 20.04

**Comment by Wachizungu** [comment]
Can you try leaving out the http://?

**Comment by bilalsarwar16** [comment]
Already tried and even tried with proxy IP but didn't work but it works with authentication and i have access on proxy without authentication.

**Comment by Kagee** [comment]
1. Is this an actual proxy, or a webserver?
2. Have you confirmed that you can connect to this proxy from the command line of the machine MISP is running on?

**Comment by bilalsarwar16** [comment]
this is actual proxy and i have confirmed through cli by running curl same request which i am trying from misp gui to fetch feeds.

**Comment by Wachizungu** [comment]
It might be pointless but since it doesn't really hurt:
Did you try killing all workers and restarting them after updating this config? If not, can you try that?

**Comment by Kagee** [comment]
No, it is not pointless, it is a common issue that workers must be restarted after some config changes.
