### ISSUE TITLE
Feature Request: Allow access to attribute warninglist objects in workflows.

### ISSUE THREAD

**Issue by UFOSmuggler** [MISP/MISP#9735]
### Is your feature request related to a problem? Please describe.

If I try this:

![image](https://github.com/MISP/MISP/assets/85923673/75d36cba-e1ff-4ab7-af50-3fd88824e53c)
![image](https://github.com/MISP/MISP/assets/85923673/9560729b-8169-45c8-9246-6c2849ddf131)

It doesn't work.  iglocska speculates that its because warnings are generated at the end of execution, and may not be attached when read back after saving.

It's also possible I'm just doing it wrong.

### Describe the solution you'd like

I'd like to be able to access warninglist objects applied to attributes via hash paths in workflows, the use case like in my pictures would be mighty helpful for developing analyst workflows and procedures.

### Describe alternatives you've considered

could just do it in a python script i guess.  but this would be nicer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincenzocaputo** [comment]
I think you should use the "Attach Warninglist" module before accessing to warnings properties.

**Comment by UFOSmuggler** [comment]
> I think you should use the "Attach Warninglist" module before accessing to warnings properties.

Thanks Vincenzo, I did actually try that, but only on the "event after save" trigger, where it does not work.  After your suggestion i retried it on the "attribute after save" trigger, with exactly the same configuration, and it does work.

Strange that it does not work on the event based trigger though, maybe I need to filter the scope or something before I can use that one.

Event | Attribute
:-:|:-:
![image](https://github.com/MISP/MISP/assets/85923673/b909e0e6-7125-439c-b630-cac956fe9c2c)|![image](https://github.com/MISP/MISP/assets/85923673/7c27a61f-df50-4327-a960-f4a5d8a52fe6)

The attribute trigger is good enough anyway, thank you very much for your advice.
