### ISSUE TITLE
Bug: Inconsistency in EventReport Updates

### ISSUE THREAD

**Issue by dragsu** [MISP/MISP#9738]
### Actual behavior

Scenario A: When `add_event` is called with an event report, the `Event` and the `EventReport` get created with the specified timestamps in the event and report.
Scenario B: When `update_event` is called with an update to the event report, it is not updated.
Scenario C: When `update_event_report` is called, the event report is updated but it puts the current timestamp instead of the specified timestamp in the report (_force_timestamp set to True_)

### Expected behavior

Scenario A:  Ok
Scenario B: Call to `update_event` should update the event report, if there is an update. 
Scenario C: Call to `update_event_report` should use the specified timestamp in the report

If updates are meant to be done in two calls (event updates using `update_event` and report updates using `update_event_report`, not sure how this can be done using the same timestamp value in an incoming event). I feel reports are not tightly integrated with Event's ecosystem.
### Steps to reproduce

- ScenarioA code snippet:

```
t = 1704751865
event = MISPEvent(force_timestamps=True)    
event.uuid = "30ebd9f6-ee46-496e-93cf-0a75b32e58f3"
event.distribution = 1
event.threat_level_id = 1
event.info = 'test_event'
event.timestamp = t
report = event.add_event_report(
    "reportA", "hello world", uuid="30ebd9f6-ee46-496e-93cf-0a75b32e58f3")
report.timestamp = t
report.force_timestamp = True
event = misp.add_event(event)
```

- ScenarioB code snippet
```
t = 1704751867
event = MISPEvent(force_timestamps=True)
event.uuid = "30ebd9f6-ee46-496e-93cf-0a75b32e58f3"
event.distribution = 1
event.threat_level_id = 1
event.info = 'test_event'
event.timestamp = t
report = event.add_event_report(
    "reportA", "hello world - updated", id="<report_id_of_previously_created_report>")
report.timestamp = t
report.force_timestamp = True
event = misp.update_event(event)
```
- ScenarioC code snippet
```
t = 1704751869
event = MISPEvent(force_timestamps=True)
event.uuid = "30ebd9f6-ee46-496e-93cf-0a75b32e58f3"
event.distribution = 1
event.threat_level_id = 1
event.info = 'test_event'
event.timestamp = t
report = event.add_event_report(
    "reportA", "hello world - updated", id="<report_id_of_previously_created_report>")
report.timestamp = t
report.force_timestamp = True
misp.update_event_report(report)
```

### Version

2.4.173

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dragsu** [comment]
I thought about this again and I think the current behaviour is correct.

**Comment by dragsu** [comment]
I did bit more testing with synch setup and noticed a discrepancy in the last modified timestamps in local and remote instance. It looks like when event report get created in local instance, it updates the event with the local time. 

### Steps to Reproduce

- Create a synch setup between two instances
- Create an event with an attribute
-  Publish the event, and compare Event's last updated timestamp between the two instances ( OK)
-  Updated the attribute value and re-publish the event and compare timestamps (OK)
-  Now create an event report and publish it. Compare the timestamps (OK)
-  Finally update the event report and publish it. Compare the timestamps (**NOK**)

**Comment by mokaddem** [comment]
Thanks for the very detailed issues and providing the code snippet to test the issue.
- **Scenario A**: Ok
- **Scenario B**: Couldn't reproduce, see below
- **Scenario C**: Couldn't reproduce, see below

Calling the PyMISP function `add_event_report` effectively creates a new event report (with a new UUID). This means you are not actually updating an existing report using that function.
To update an existing report, you'll have to fetch it (or get it's UUID) like so:
```python
event = misp.get_event(eventid)
t = 1704751868
report = event.event_reports[0]
report.timestamp = t
report.force_timestamp = True
report.content = 'hello world - updated again'
report = misp.update_event_report(report)
# or
# event = misp.update_event(event)
```

However, your feedback for the timestamp in the context of synchronisation is a very nice finding ! The issue should be solved in https://github.com/MISP/MISP/commit/76322cdbfbf614dacd12b41d159d6618e4c7c7d8.

Thanks you!

**Comment by dragsu** [comment]
@mokaddem Thank you for the quick fix 🙌. I redid my testing with your code suggestion and it worked. Also now timestamps are behaving as expected. Below is the code snippet for completeness.

```
# create an event with a report
t = 1704751865
event = MISPEvent(force_timestamps=True)
event.uuid = "30ebd9f6-ee46-496e-93cf-0a75b32e58f3"
event.info = 'test_event'
event.timestamp = t
report = event.add_event_report(
    "reportA", "hello world", uuid="30ebd9f6-ee46-496e-93cf-0a75b32e58f3")
event = misp.add_event(event)

# Update to the report
t = 1704751866 # adding a 1 sec to the event created timestamp
event = misp.get_event("30ebd9f6-ee46-496e-93cf-0a75b32e58f3", pythonify=True)
event.force_timestamp = True
event.timestamp = t
report = event.event_reports[0]
report.content = 'hello world - updated again'
misp.update_event(event)
```

**Comment by mokaddem** [comment]
Awesome and thanks for the feedback!
Cheers!
