### ISSUE TITLE
Bug: New feed feature "Unpublish events" is actually inverted, publishing them

### ISSUE THREAD

**Issue by UFOSmuggler** [MISP/MISP#9739]
### Actual behavior

If I check the "Unpublish events" checkbox on a feed, the events always arrive published.

![image](https://github.com/MISP/MISP/assets/85923673/e41943e9-5c36-48d6-be37-653c911457e0)

This appears to be caused by the logic found [here](https://github.com/MISP/MISP/commit/c4c395af3125623596ce22fb4a55350d2d14fc39).

It says if the setting is not empty, set the event publishing state to true if the setting is enabled.  This is the inverse of what is anticipated.

I have tested this on feeds that come unpublished and published, and in all instances, the events arrive published when the checkbox is checked.

### Expected behavior

I would expect this to unpublish the events, not publish them.

### Steps to reproduce

1. Pull a feed that arrives published with the "Unpublish events" checkbox checked
2. Observe result

When you fix this, can you please also add a mutually exclusive checkbox for "Publish events" as I request [here](https://github.com/MISP/MISP/issues/9721)?

### Version

2.4.192

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Chrome

### Browser version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks, the fix will be in the upcoming release!
