### ISSUE TITLE
Bug: Errors, Pip conflicts in the ubuntu 22.04 installation script

### ISSUE THREAD

**Issue by stevenpine-fsisac** [MISP/MISP#9748]
### Actual behavior

Using a fresh ubuntu 22.04 and running the install script here https://misp.github.io/MISP/xINSTALL.ubuntu2204

Install command:
bash /tmp/INSTALL.sh -c -M -m

The following PIP errors are generated during the installation:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
misp-stix 2.4.188 requires pymisp<3.0.0,>=2.4.187, but you have pymisp 2.4.175 which is incompatible.
misp-lib-stix2 3.0.1.1 requires pytz<2023.0.0,>=2022.2.1, but you have pytz 2023.3 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
misp-lib-stix2 3.0.1.1 requires pytz<2023.0.0,>=2022.2.1, but you have pytz 2023.3 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vysion 1.0.10 requires pymisp==2.4.175, but you have pymisp 2.4.190 which is incompatible.
~~

Is this expected? I am confused why the pymisp version is changing, being listed as both version 2.4.190 and 2.4.175. 

thank you for any assistance

### Expected behavior

the expectation is no dependency pip errors.

### Steps to reproduce

Standard ubuntu 22.04 image from aws
adduser misp
usermod -aG sudo misp
usermod -aG www-data misp
usermod -aG staff misp
# exit shell, reconnect, become misp user, cd  /home/misp

sudo apt-get install postfix dialog -qy
wget --no-cache -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M -m

### Version

2.4.192

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Browser

n/a

### Browser version

n/a

### Relevant log output

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
misp-stix 2.4.188 requires pymisp<3.0.0,>=2.4.187, but you have pymisp 2.4.175 which is incompatible.
misp-lib-stix2 3.0.1.1 requires pytz<2023.0.0,>=2022.2.1, but you have pytz 2023.3 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
misp-lib-stix2 3.0.1.1 requires pytz<2023.0.0,>=2022.2.1, but you have pytz 2023.3 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vysion 1.0.10 requires pymisp==2.4.175, but you have pymisp 2.4.190 which is incompatible.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vercheck** [comment]
Yep, even if you install the correct versions, this script would update the dependencies to the newest version, then complain.

**Comment by stevenpine-fsisac** [comment]
I ran the script again last night with fresh install, skipping the initial postfix install, and did not have the same pip errors. Since I'm not having this issue anymore I will close this out. Thank you.
