### ISSUE TITLE
Feature Request: Option to select more than one sharing group when sharing the event

### ISSUE THREAD

**Issue by linozinho** [MISP/MISP#9763]
### Is your feature request related to a problem? Please describe.

The problem with sharing to more than one sharing group at the same time

### Describe the solution you'd like

It would be cool if there were checkboxes on the sharing groups so we could choose which ones we want to select to share the event

### Describe alternatives you've considered

![image](https://github.com/MISP/MISP/assets/93954491/1b7bbd35-aebc-454d-9de3-bbe49d3b1e9f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Whilst this is not possible (and we don't plan on adding this option for complexity / performance reasons) - there is a way around it using the sharing group blueprints. 

You can create a reusable sharing group that inherits all the organisations of a set of sharing groups. 

![image](https://github.com/MISP/MISP/assets/3668672/0c588133-5211-43c3-ae00-1ce4d8c842f4)

A quick example of such a rule based sharing group blueprint. It will generate a sharing group with all organisations matching the criteria (so in this case, org_nationality = international + any org being part of sharing group 4, 5, 6 or 7). 

The sharing group can be kept up to date with a single API/CLI call, which can be cron jobbed to be kept up to date continuously.

**Comment by linozinho** [comment]
Thank you for your help

**Comment by iglocska** [comment]
No worries!
