### ISSUE TITLE
Bug: MISP report fails to properly display tag and galaxy elements.

### ISSUE THREAD

**Issue by RR19MR** [MISP/MISP#9774]
### Actual behavior

![image](https://github.com/MISP/MISP/assets/172469872/1688997a-cb08-4112-9ce3-21142cdfd1a7)

![image](https://github.com/MISP/MISP/assets/172469872/db9b26af-6ef3-4dce-a701-e8ef05cb50e5)

### Expected behavior

load properly

### Steps to reproduce

just create report

### Version

2.4.193

### Operating System

Ubuntu

### Operating System version

.

### PHP version

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Thanks, nice find indeed. Should be fixed in the upcoming version
