### ISSUE TITLE
MISP not switching to live mode?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#978]
Despites the parameter 'MISP.live' set to 'true', MISP continues to display the classic red banner and prevent non-admin users to log in.
Checked in config.php -> the value is correct!
Any idea?
PS: Latest version, out of the box.

**Comment by adulau** [comment]
It should work. I did a test on the recent version and this works. Did you refresh/reload the page?

**Comment by xme** [comment]
Cleanup cache, tested with a second "clean" browser. Same.
Started admin session, no banner,
=> Logout
=> Log with a regular user
=> Password accepted (no red banner) but back to the login page again and again
=> Login with admin account
=> List users
=> The red banner "MISP is not in live mode" is back

Voodoo? ;-)

**Comment by xme** [comment]
Ok, now I was able to log in with a regular user after I checked the option "Terms Accepted" in his profile.

**Comment by elhoim** [comment]
@xme I will consider this as fixed. Feel free to re-open if not.
