### ISSUE TITLE
Implement unit testing 

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#98]
As the code becomes bigger and bigger it seems that some things break when other things are changed. Today testing is done manually, but not all test scenarios are tested.

Implement CakePHP unit testing with many test cases to help us not break things when making changes in the code. 

This will raise the quality of the code and in the end make us win time. 

CakePHP comes with comprehensive testing support built-in. CakePHP comes with integration for PHPUnit. In addition to the features offered by PHPUnit, CakePHP offers some additional features to make testing easier. This section will cover installing PHPUnit, and getting started with Unit Testing, and how you can use the extensions that CakePHP offers.

More info: http://book.cakephp.org/2.0/en/development/testing.html

**Comment by Rafiot** [comment]
Travis is now mostly there (the installation works). Now, we need test cases :)
