### ISSUE TITLE
Bug: Hovering above a tag no longer displays corresponding taxonomy / tag description

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#9804]
### Actual behavior

In older versions of MISP (at least in 2.4.182), in the event details, if you hovered above a tag that was part of a taxonomy it displayed the taxonomy details and tag description.
In newer versions (at least in 2.4.194) this is no longer the case. 
Is this a configurable option or a bug?

### Expected behavior

Taxonomy and tag description when hovering above a tag

### Steps to reproduce

Open event details, hover above a tag part of a taxonomy

### Version

2.4.194

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Firefox, Chrome and Edge

### Extra attachments

<img width="762" alt="1" src="https://github.com/MISP/MISP/assets/256028/53ec7b9f-d43b-43e4-92ab-6231ad649195">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment]
Could be this is fixed with https://github.com/MISP/MISP/pull/9888/commits/bc5720aa29733fea1b9f1117ed1acc4ba097a027 perhaps, could you check?

**Comment by cudeso** [comment]
Indeed, seems to be fixed in >=2.4.197.
Closing.
