### ISSUE TITLE
Support: LDAP issue in MISP Docker 

### ISSUE THREAD

**Issue by Friddrick** [MISP/MISP#9810]
### Support Questions

Hi! 
While deploying MISP in Docker, I encountered a problem with LDAP customization. 
After entering the config into the .env file, the web gives an error SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null. 

The config in .env looks like this: 

 LDAP_ENABLE=true
 LDAP_APACHE_ENV="REMOTE_USER"
 LDAP_SERVER="ldap://10.10.10.10:389"
 LDAP_STARTTLS=false
 LDAP_READER_USER="CN=misp,OU=LdapUsers,DC=QB,DC=ua"
 LDAP_READER_PASSWORD="P@ssw0rdP@ssw0rd"
 LDAP_DN="DC=QB,DC=ua"
 LDAP_SEARCH_FILTER=""
 LDAP_SEARCH_ATTRIBUTE="mail"
 LDAP_FILTER="[\"mail\"]"
 LDAP_DEFAULT_ROLE_ID="3"
 LDAP_DEFAULT_ORG="1"
 LDAP_EMAIL_FIELD=["mail"]
 LDAP_OPT_PROTOCOL_VERSION="3"
 LDAP_OPT_NETWORK_TIMEOUT="-1"
 LDAP_OPT_REFERRALS=false

No parsing errors were found when checking with .jq.
Are there any other ways to solve the problem? Maybe ldap plugin is wrong or underinstalled ?  

### MISP version

2.4.193

### Operating System

Oracle Linux 

### Operating System version

9

### PHP version

7.0

### Browser

Chrome

### Relevant log output

```shell
PDO error
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null
Error: An Internal Error Has Occurred.

Stack Trace
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 502 → PDOStatement->execute()
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 468 → DboSource->_execute()
APP/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php line 1132 → DboSource->execute()
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1942 → DboSource->create()
APP/Lib/cakephp/lib/Cake/Model/Model.php line 1760 → Model->_doSave()
APP/Controller/Component/Auth/ApacheAuthenticate.php line 171 → Model->save()
APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 772 → ApacheAuthenticate->authenticate()
APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 612 → AuthComponent->identify()
APP/Controller/UsersController.php line 1239 → AuthComponent->login()
[internal function] → UsersController->login()
APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 499 → ReflectionMethod->invokeArgs()
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction()
APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke()
APP/webroot/index.php line 101 → Dispatcher->dispatch()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tdportW** [comment]
@Friddrick  We are experiencing the same issue. Did you ever find a resolution to this issue?

**Comment by adulau** [comment]
There is now a standalone LDAP authenticator in MISP which could clearly help in such scenario.

https://github.com/MISP/MISP/tree/29993e516825b8ff35a72419fa61c40472eb1898/app/Plugin/LdapAuth
