### ISSUE TITLE
Support: MISP server setting and jobs not showing in GUI

### ISSUE THREAD

**Issue by Joshmoore8991** [MISP/MISP#9816]
### Support Questions

help me fix misp

### MISP version

 2.4.194

### Operating System

ubuntu

### Operating System version

22.04

### PHP version

0.0

### Browser

chrome

### Relevant log output

```shell
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

get this for it - cant browse to jobs either but get the same error - can i restart settings or reset  ? 

the rest of MISP is fine everything is the correct version
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Could you check your error log? /var/www/MISP/app/tmp/logs/error.log

**Comment by Joshmoore8991** [comment]
redis connection refused

**Comment by Joshmoore8991** [comment]
it was working and then stopped

**Comment by Joshmoore8991** [comment]
it was working then a setting changed and broke it
