### ISSUE TITLE
Support:  deleted MISP fixed event

### ISSUE THREAD

**Issue by Joshmoore8991** [MISP/MISP#9820]
### Support Questions

had events in misp fixed events 1-6 with ioc's needed to bring tags in to recorralte - now feeds not pullling in how can i fix

### MISP version

2.4

### Operating System

ubuntu 

### Operating System version

22.04

### PHP version

latets

### Browser

chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Edit the feed, delete the ID of the fixed event.

**Comment by UFOSmuggler** [comment]
or if you mean you deleted events from a feed, and now when you pull the feed again you don't get the events, try removing them from the event blocklist in the administration area.
