### ISSUE TITLE
Typo whois-registar

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#984]
Hello all,

A tiny typo "whois-registar" (instead of whois-registrar) is present in the file [app/Model/Attribute.php](https://github.com/MISP/MISP/search?utf8=%E2%9C%93&q=whois-registar&type=Code).

Credits: Etienne M :)

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.23

**Comment by adulau** [comment]
Fixed and thank you for the notification.

A side note, previous events created with this attribute with this typographical error will remain.
