### ISSUE TITLE
Support: Apache2 Browsable Web Directories

### ISSUE THREAD

**Issue by mbell85** [MISP/MISP#9845]
### Support Questions

Good day! I have a vulnerability finding from Nessus Tenable stating that I have browsable web directories located here:

- {mispsite}.com/manual/images/
- {mispsite}.com/manual/style
- {mispsite}.com/manual/style/css

I attempted to make them non-browsable by editing Apache2 main conf file (Ubuntu Server 22.04.6 LTS), and Apache2/sites-available conf file, but that hasn't seemed to work (and I restarted apache2 after every edit). 

This is what final edit looks like to attempt to remove browsability: 

<Directory /var/www/>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

Any help appreciated! 

### MISP version

2.4.195

### Operating System

Ubuntu

### Operating System version

20.04.6 LTS

### PHP version

7.4.3-4ubuntu2.23

### Browser

All

### Browser version

All

### Relevant log output

```shell
Vulnerabilities
40984 - Browsable Web Directories-
Synopsis
Some directories on the remote web server are browsable.
Description
Multiple Nessus plugins identified directories on the web server that are browsable.
See Also
http://www.nessus.org/u?0a35179e
Solution
Make sure that browsable directories do not leak confidential information or give access to sensitive resources. Additionally, use access restrictions or disable directory indexing for any that do.
Risk Factor
Medium
CVSS v3.0 Base Score
5.3 (CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N)
CVSS v2.0 Base Score
5.0 (CVSS2#AV:N/AC:L/Au:N/C:P/I:N/A:N)
Plugin Information
Published: 2009/09/15, Modified: 2021/01/19
Plugin Output
tcp/443/www

The following directories are browsable :

https://{mispurl}/manual/images/
https://{mispurl}/manual/style/
https://{mispurl}/manual/style/css/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
Simply run: a2disconf apache2-doc
then: systemctl reload apache2

**Comment by mbell85** [comment]
elvidence: That did it, my friend. I really appreciate you.
