### ISSUE TITLE
Bug: /attributes/restSearch returning 0 results after v2.4.195

### ISSUE THREAD

**Issue by mdavis332** [MISP/MISP#9866]
### Actual behavior

I do an HTTP POST against /attributes/restSearch in **v.2.4.189** and get back expected results. I do the same search in **v2.4.195** and get back 0 results (even after incorporating @iglocska's changes in 2702dd40c409063a06b8f25a1773adfae6205752 and 6d5846cfcd155ea9abdecddcc3b0ade0847c266c). ` This is true across 2 separate v2.4.195 instances in different environments (one local and one in AWS). 

### Expected behavior

v2.4.195 continues to return results as expected. 

### Steps to reproduce

Using `HTTP POST` against `/attributes/restSearch` endpoint with correct `Authorization` header, and the following 2 additional HTTP headers:
```
Accept: application/json
Content-type: application/json
```

And the following HTTP POST body
```
{
    "returnFormat": "json",
    "includeEventTags": true,
    "enforceWarninglist": true,
    "limit": 10,
    "to_ids": true,
    "tags": [ "list", "of", "specific", "tags", "i", "want"],
    "type": [ "domain", "email", "hostname", "ip-src", "ip-dst", "ip-dst|port", "ip-src|port"],
    "timestamp": ["2024-07-02T13:59:31", "2024-08-15T13:03:14.421164Z"],
    "deleted": [0, 1]
}
```

On a v2.4.189 MISP instance, I immediately get back my limit of 10 results. On v2.4.195, it takes a few seconds and returns an empty list. Same feeds with roughly same data tagged the same in both instances. 

### Version

2.4.195

### Operating System

CentOS

### Operating System version

Stream 8

### PHP version

7.4

### Browser

Firefox, Chrome, Edge

### Browser version

latest

### Relevant log output

```shell
v2.4.195: {"response": {"Attribute": []}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdavis332** [comment]
On a whim, I removed the `"deleted": [0, 1]` from the POST body and I'm getting results back as expected. Seems like something changed regarding this param when moving from v2.4.189 to v2.4.195. The in-UI hint for that param in the in-UI REST client at `/api/rest` still shows `[0, 1]` as the options to pass to get both deleted and non-deleted attributes. However, this has stopped working correctly.

**Comment by shakedmor** [comment]
I also experience this issue (version v2.4.197) , the problem appears to be when searching for deleted=true via the attribute search.

**Comment by adulau** [comment]
Thanks for the report. Can you check on the current 2.4 branch? It should be fixed.

**Comment by iglocska** [comment]
Was indeed correct, by fixing a bug, it introduced a worse one. The deleted flag prior to the initial "fix" ignored the deleted state of the objects the attributes might have been contained in, whilst the "fix" introduced a new bug that caused non object attributes to never be exported if the deleted flag was set in the request. The current commit on 2.4 should resolve both issues.
