### ISSUE TITLE
Filter on List Users page doesn't work correctly

### ISSUE THREAD

**Issue by pszemekd** [MISP/MISP#988]
Filter on the List User page redirects to filterUserIndex page if filter parameters are missing.

How to get there:
Go to Adminitration -> List Users.
In the filter choose email, click on the text field and press Enter - you will be redirected to another web page with message: No filters set.

**Comment by iglocska** [comment]
Argh, incorrect issue referenced.

**Comment by iglocska** [comment]
Guess this was fixed at some point.
