### ISSUE TITLE
Support: Warning The MISP database state does not match the expected schema. Resolving these issues is recommended. ⚠ This diagnostic tool is in experimental state - the highlighted issues may be benign. If you are unsure, please open an issue on with the issues identified over at https://github.com/MISP/MISP for clarification.

### ISSUE THREAD

**Issue by Joshmoore8991** [MISP/MISP#9908]
### Support Questions

how can i fix - Warning The MISP database state does not match the expected schema. Resolving these issues is recommended.
⚠ This diagnostic tool is in experimental state - the highlighted issues may be benign. If you are unsure, please open an issue on with the issues identified over at https://github.com/MISP/MISP for clarification.

### MISP version

v2.4.197

### Operating System

ubuntu 

### Operating System version

22.04

### PHP version

7.4.33

### Browser

chrome

### Browser version

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
The most recent version 2.4.198 presented a similar warning, which pertained to comments. MISP itself provided a solution—simply click the wrench icon to view the resolution to the issue. 

In my case I logged in to the db
`mysql -h Location_of_Your_DB -u misp -p -P 3306` then, `USE misp`; and
`ALTER TABLE `bookmarks` MODIFY COLUMN `comment` text NOT NULL COLLATE utf8mb4_unicode_ci ;` which fixed the issue.

**Comment by ostefano** [comment]
@iglocska let's fix this before the next release if possible.

**Comment by iglocska** [comment]
Done, please update and you should be good to go.
