### ISSUE TITLE
Bug: Workflow event Publish does not remove IDS check

### ISSUE THREAD

**Issue by jmartingo** [MISP/MISP#9914]
### Actual behavior

I have a workflow whose trigger is “Event-Publish” and what it does is to take the attributes of the event and in case they are in a warninglist, it adds a series of tags and disables the ids check.

The real behavior is that in 90% of the occasions it does not remove the IDS check.
![resultado_workflow_ids](https://github.com/user-attachments/assets/d3268ee7-6e97-445a-8c88-7f148ad01faf)

### Expected behavior

The expected behavior is to remove the IDS check.

### Steps to reproduce

-Create a workflow with the following structure:
![workflow_ids](https://github.com/user-attachments/assets/c575bafc-f166-4d7b-aa2d-15ea36bee2e3)

{
    "1": {
        "id": 1,
        "name": "Event Publish",
        "data": {
            "id": "event-publish",
            "scope": "event",
            "name": "Event Publish",
            "description": "This trigger is called just before a MISP Event starts the publishing process",
            "icon": "upload",
            "inputs": 0,
            "outputs": 1,
            "blocking": true,
            "misp_core_format": true,
            "trigger_overhead": 1,
            "trigger_overhead_message": "",
            "is_misp_module": false,
            "is_custom": false,
            "expect_misp_core_format": false,
            "version": "0.1",
            "icon_class": "",
            "multiple_output_connection": false,
            "support_filters": false,
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "module_type": "trigger",
            "html_template": "trigger",
            "disabled": true,
            "node_uid": "1pk3llkn01a09hmorrxqxad",
            "indexed_params": [],
            "previous_module_version": "0.1",
            "module_version": "0.1"
        },
        "class": "block-type-trigger",
        "typenode": false,
        "inputs": [],
        "outputs": {
            "output_1": {
                "connections": [
                    {
                        "node": "2",
                        "output": "input_1"
                    }
                ]
            }
        },
        "pos_x": 227.46153846153845,
        "pos_y": 0
    },
    "2": {
        "id": 2,
        "name": "Attach warninglist",
        "data": {
            "indexed_params": {
                "warninglists": [
                    "ALL"
                ]
            },
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "node_uid": "1pp0edvgdmzlb",
            "module_type": "action",
            "id": "attach-warninglist",
            "name": "Attach warninglist",
            "multiple_output_connection": false,
            "previous_module_version": "0.2",
            "module_version": "0.2"
        },
        "class": "block-type-default expect-misp-core-format",
        "typenode": false,
        "inputs": {
            "input_1": {
                "connections": [
                    {
                        "node": "1",
                        "input": "output_1"
                    }
                ]
            }
        },
        "outputs": {
            "output_1": {
                "connections": [
                    {
                        "node": "3",
                        "output": "input_1"
                    }
                ]
            }
        },
        "pos_x": 730.4712697285752,
        "pos_y": -211
    },
    "3": {
        "id": 3,
        "name": "Filter :: Generic",
        "data": {
            "indexed_params": {
                "filtering-label": "A",
                "selector": "Event._AttributeFlattened.{n}",
                "value": "false_positive",
                "value_list": [],
                "operator": "in",
                "hash_path": "warnings.{n}.warninglist_category"
            },
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "node_uid": "1pw7776vo0f03apurttsenr",
            "module_type": "logic",
            "id": "generic-filter-data",
            "name": "Filter :: Generic",
            "multiple_output_connection": false,
            "previous_module_version": "0.2",
            "module_version": "0.2"
        },
        "class": "block-type-default block-type-logic",
        "typenode": false,
        "inputs": {
            "input_1": {
                "connections": [
                    {
                        "node": "2",
                        "input": "output_1"
                    }
                ]
            }
        },
        "outputs": {
            "output_1": {
                "connections": [
                    {
                        "node": "5",
                        "output": "input_1"
                    }
                ]
            }
        },
        "pos_x": 1261.9473684210527,
        "pos_y": -342.7368421052632
    },
    "5": {
        "id": 5,
        "name": "Tag operation",
        "data": {
            "indexed_params": {
                "scope": "attribute",
                "action": "add",
                "locality": "local",
                "tags": [
                    "false-positive:risk=\"high\"",
                    "misp-workflow:action-taken=\"ids-flag-removed\"",
                    "misp-workflow:analysis=\"false-positive\""
                ],
                "relationship_type": ""
            },
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "node_uid": "1q2sssrio1p039gekg66ttc",
            "module_type": "action",
            "id": "tag_operation",
            "name": "Tag operation",
            "multiple_output_connection": false,
            "previous_module_version": "0.2",
            "module_version": "0.2"
        },
        "class": "block-type-default expect-misp-core-format",
        "typenode": false,
        "inputs": {
            "input_1": {
                "connections": [
                    {
                        "node": "3",
                        "input": "output_1"
                    }
                ]
            }
        },
        "outputs": {
            "output_1": {
                "connections": [
                    {
                        "node": "9",
                        "output": "input_1"
                    }
                ]
            }
        },
        "pos_x": 1701.0847013166313,
        "pos_y": -333
    },
    "6": {
        "id": 6,
        "name": "Filter :: Remove filter",
        "data": {
            "indexed_params": {
                "filtering-label": "all"
            },
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "node_uid": "dvm0a5bigdjc6zt",
            "module_type": "logic",
            "id": "generic-filter-reset",
            "name": "Filter :: Remove filter",
            "multiple_output_connection": false,
            "previous_module_version": "0.1",
            "module_version": "0.1"
        },
        "class": "block-type-default block-type-logic",
        "typenode": false,
        "inputs": {
            "input_1": {
                "connections": [
                    {
                        "node": "9",
                        "input": "output_1"
                    }
                ]
            }
        },
        "outputs": {
            "output_1": {
                "connections": []
            }
        },
        "pos_x": 2656.9312795386436,
        "pos_y": -69.09312795386434
    },
    "9": {
        "id": 9,
        "name": "Attribute IDS Flag operation",
        "data": {
            "node_uid": "dvo3llkn01a0ezilva60t6l",
            "indexed_params": {
                "action": "remove"
            },
            "saved_filters": {
                "selector": "",
                "value": "",
                "operator": "",
                "path": ""
            },
            "module_type": "action",
            "id": "attribute_ids_flag_operation",
            "name": "Attribute IDS Flag operation",
            "multiple_output_connection": false,
            "previous_module_version": "0.1",
            "module_version": "0.1"
        },
        "class": "block-type-default expect-misp-core-format",
        "typenode": false,
        "inputs": {
            "input_1": {
                "connections": [
                    {
                        "node": "5",
                        "input": "output_1"
                    }
                ]
            }
        },
        "outputs": {
            "output_1": {
                "connections": [
                    {
                        "node": "6",
                        "output": "input_1"
                    }
                ]
            }
        },
        "pos_x": 2167.0847013166313,
        "pos_y": -146.0847013166313
    },
    "_frames": []
}

- Create an event with 1 ioc that is inside an active warninglist of false positive type.
- Publish the event
- Check if you have added tags and removed IDS  
 

### Version

2.4.183

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.2

### Browser

Chrome

### Browser version

128.0.6613.120

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by framontb** [comment]
Solved in [Bug: Module attribute_ids_flag_operation > Toggle IDS flag (and Remove IDS flag) not working properly](https://github.com/MISP/MISP/issues/9955)
