### ISSUE TITLE
Bug: Unable to add attribute with correlations enabled to event with correlations enabled

### ISSUE THREAD

**Issue by Parasdeepkohli** [MISP/MISP#9921]
### Actual behavior

Adding an attribute with correlations enabled to an event with correlations enabled fails and MISP responds with "An internal error has occurred"

### Expected behavior

Attributed is added to event successfully.

### Steps to reproduce

Try to add any attribute with correlation enabled to an event with correlations enabled. Note that the below combinations of correlation settings work as expected:

- Attribute with correlations disabled can be added to an event with correlations enabled.
- Attribute with correlations disabled can be added to an event with correlations disabled.
- Attribute with correlations enabled can be added to an event with correlations disabled. But if you try to enable correlations on the event AFTER this attribute was successfully added, MISP returns the same error.

### Version

2.4.198

### Operating System

Ubuntu LTS

### Operating System version

18.04

### PHP version

7.4

### Relevant log output

```shell
2024-09-19 10:27:02 Error: [MissingTableException] Table correlation_rules for model CorrelationRule was not found in datasource default.
Exception Attributes: array (
  'table' => 'correlation_rules',
  'class' => 'CorrelationRule',
  'ds' => 'default',
)
Request URL: /attributes/add/25512
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#3 /var/www/MISP/app/Model/AppModel.php(4302): Model->find()
#4 /var/www/MISP/app/Model/CorrelationRule.php(92): AppModel->find()
#5 /var/www/MISP/app/Model/CorrelationRule.php(81): CorrelationRule->__loadRuleCache()
#6 /var/www/MISP/app/Model/Correlation.php(487): CorrelationRule->attachCustomCorrelationRules()
#7 /var/www/MISP/app/Model/Attribute.php(481): Correlation->afterSaveCorrelation()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#11 /var/www/MISP/app/Model/Attribute.php(565): Model->save()
#12 /var/www/MISP/app/Model/Attribute.php(2725): Attribute->save()
#13 /var/www/MISP/app/Controller/AttributesController.php(164): Attribute->captureAttribute()
#14 [internal function]: AttributesController->add()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#18 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#19 {main}
```

### Extra attachments

The 'MISP.completely_disable_correlation' is set to False in MISP.
The correlation_rules table does exist in the DB. Below is the output of 'Show tables' command in mysql:

+-------------------------------+
| Tables_in_misp                |
+-------------------------------+
| access_logs                   |
| admin_settings                |
| allowedlist                   |
| analyst_data_blocklists       |
| attachment_scans              |
| attribute_tags                |
| attributes                    |
| audit_logs                    |
| auth_keys                     |
| bookmarks                     |
| bruteforces                   |
| cake_sessions                 |
| cerebrates                    |
| collection_elements           |
| collections                   |
| correlation_exclusions        |
| correlation_rules             |
| correlation_values            |
| correlations                  |
| cryptographic_keys            |
| dashboards                    |
| decaying_model_mappings       |
| decaying_models               |
| default_correlations          |
| event_blocklists              |
| event_delegations             |
| event_graph                   |
| event_locks                   |
| event_reports                 |
| event_tags                    |
| events                        |
| favourite_tags                |
| feeds                         |
| fuzzy_correlate_ssdeep        |
| galaxies                      |
| galaxy_cluster_blocklists     |
| galaxy_cluster_relation_tags  |
| galaxy_cluster_relations      |
| galaxy_clusters               |
| galaxy_elements               |
| inbox                         |
| jobs                          |
| logs                          |
| news                          |
| no_acl_correlations           |
| notes                         |
| noticelist_entries            |
| noticelists                   |
| notification_logs             |
| object_references             |
| object_relationships          |
| object_template_elements      |
| object_templates              |
| objects                       |
| opinions                      |
| org_blocklists                |
| organisations                 |
| over_correlating_values       |
| posts                         |
| regexp                        |
| relationships                 |
| rest_client_histories         |
| roles                         |
| servers                       |
| shadow_attribute_correlations |
| shadow_attributes             |
| sharing_group_blueprints      |
| sharing_group_orgs            |
| sharing_group_servers         |
| sharing_groups                |
| sighting_blocklists           |
| sightingdb_orgs               |
| sightingdbs                   |
| sightings                     |
| tag_collection_tags           |
| tag_collections               |
| tags                          |
| tasks                         |
| taxii_servers                 |
| taxonomies                    |
| taxonomy_entries              |
| taxonomy_predicates           |
| template_element_attributes   |
| template_element_files        |
| template_element_texts        |
| template_elements             |
| template_tags                 |
| templates                     |
| threads                       |
| threat_levels                 |
| user_login_profiles           |
| user_settings                 |
| users                         |
| warninglist_entries           |
| warninglist_types             |
| warninglists                  |
| workflow_blueprints           |
| workflows                     |
+-------------------------------+
98 rows in set (0.00 sec)

Additionally, the Schema Status section in the diagnostics tab also confirms that the table exists. Please check the records below:

<html>  
<body>  
<table border="1">  
  <tbody>  
    <tr>  
      <td rowspan="3">correlation_rules</td>  
      <td>Column `comment` is different</td>  
      <td>comment YES text 65535 utf8mb3_bin text NULL</td>  
      <td>comment YES text 65535 utf8_bin text</td>  
      <td></td>  
    </tr>  
    <tr>  
      <td>Column `selector_list` is different</td>  
      <td>selector_list YES text 65535 utf8mb3_bin text NULL</td>  
      <td>selector_list YES text 65535 utf8_bin text</td>  
      <td></td>  
    </tr>  
    <tr>  
      <td>Column `created` is different</td>  
      <td>created NO int 10 int(11) unix_timestamp()</td>  
      <td>created NO int 10 int(11)</td>  
      <td></td>  
    </tr>  
  </tbody>  
</table>  
</body>  
</html>  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cyber-cyril** [comment]
Having the same issue in my non-prod MISP instance (currently on v2.4.198). 

I first noticed [500] "An internal error has occurred" responses after updating non-prod to version 2.4.195 so left my prod instance on v2.4.194 which is fine. Got round to digging into the issue today and identified the same issue as @Parasdeepkohli. Only difference is for me, the attributes were part of objects being added within an Event.

My log below:

```php
2024-09-19 16:19:52 Error: [MissingTableException] Table correlation_rules for model CorrelationRule was not found in datasource default.
Exception Attributes: array (
  'table' => 'correlation_rules',
  'class' => 'CorrelationRule',
  'ds' => 'default',
)
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#3 /var/www/MISP/app/Model/AppModel.php(4302): Model->find()
#4 /var/www/MISP/app/Model/CorrelationRule.php(92): AppModel->find()
#5 /var/www/MISP/app/Model/CorrelationRule.php(81): CorrelationRule->__loadRuleCache()
#6 /var/www/MISP/app/Model/Correlation.php(487): CorrelationRule->attachCustomCorrelationRules()
#7 /var/www/MISP/app/Model/Attribute.php(481): Correlation->afterSaveCorrelation()
#8 /var/www/MISP/app/Lib/Tools/BetterCakeEventManager.php(21): Attribute->afterSave()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): BetterCakeEventManager->dispatch()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#11 /var/www/MISP/app/Model/Attribute.php(565): Model->save()
#12 /var/www/MISP/app/Model/Attribute.php(2725): Attribute->save()
#13 /var/www/MISP/app/Model/MispObject.php(1143): Attribute->captureAttribute()
#14 /var/www/MISP/app/Model/Event.php(3944): MispObject->captureObject()
#15 /var/www/MISP/app/Controller/EventsController.php(2205): Event->_add()
#16 [internal function]: EventsController->add()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#20 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#21 {main}
```

**Comment by enzo70747** [comment]
I have the same error
![misp error](https://github.com/user-attachments/assets/3e52e799-2214-49f9-b0e4-c420f60b1eb9)

**Comment by enzo70747** [comment]
Does anyone have a solution, after updating I can't load new attributes
![image](https://github.com/user-attachments/assets/0a78e5a4-2b2a-4737-8dde-1f585cf69cc9)

**Comment by Parasdeepkohli** [comment]
@enzo70747 A temporary workaround is to disable correlations on any events/attributes that you add to MISP. You could also set 'completely disable correlations' in settings to True and this should work.

**Comment by iglocska** [comment]
It sounds like you folks are missing some DB updates. 

`/var/www/MISP/app/Console/cake Admin runUpdates`

should sort you out.
