### ISSUE TITLE
Support: You have tripped the cross-site request forgery protection of MISP

### ISSUE THREAD

**Issue by LintStalker** [MISP/MISP#9922]
### Support Questions

I'm trying to do the initial login and I get this message every time.  I have tried Chrome, Firefox and Edge.

I tried resetting the admin password, using this command: 

sudo -u www-data /var/www/MISP/app/Console/cake Password admin@admin.test Password1234

and I get this response:  

sudo: unknown user: www-data
sudo: error initializing audit plugin sudoers_audit

### MISP version

2.4.51

### Operating System

Redhat 

### Operating System version

9

### PHP version

7.4.33 

### Browser

Chrome, Firefox, Edge

### Browser version

Chrome Version 129.0.6668.59 (Official Build) (64-bit)

### Relevant log output

```shell
The following is in the /var/www/MISP/app/tmp/logs/error.log:
 2024-09-20 18:23:14 Error: Blackhole exception when accessing /users/login (isRest: 0, action: login, unlockedActions: []): The request has been black-holed
2024-09-20 18:23:14 Error: [BadRequestException] The request has been black-holed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
I'd run `getent passwd www-data` to check if it exists, then try `getent passwd misp` a you could have installed MISP under different user.

**Comment by elvidence** [comment]
P.S. `cat /etc/apache2/envvars | grep USER` and/or `ps aux | grep MISP` also might help

**Comment by LintStalker** [comment]
Here's what I see when I run those:

 getent passwd www-data
www-data:x:5009:5009::/home/www-data:/bin/bash

getent passwd misp  - this displays nothing, which seems concerning?

cat /etc/apache2/envvars | grep USER
cat: /etc/apache2/envvars: No such file or directory

222520  3456 ?        S    Sep20   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='default'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/17268427336591'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
apache      2987  0.0  0.0 222520  3456 ?        S    Sep20   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='prio'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/17268427343125'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
apache      3301  0.0  0.0 222520  3456 ?        S    Sep20   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='cache'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/1726842735307'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
apache      3839  0.0  0.0 222520  3456 ?        S    Sep20   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='email'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/17268427369252'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1
apache      3918  0.0  0.0 222520  3456 ?        S    Sep20   0:00 bash -c cd '/var/www/MISP/app/Vendor/kamisama/php-resque-ex';     VERBOSE=true  QUEUE='update'  PIDFILE='/var/www/MISP/app/Plugin/CakeResque/tmp/17268427375338'  APP_INCLUDE='/var/www/MISP/app/Plugin/CakeResque/Lib/CakeResqueBootstrap.php'  RESQUE_PHP='/var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php'  INTERVAL=5  REDIS_BACKEND='localhost:6379'  REDIS_DATABASE=0  REDIS_NAMESPACE='resque'  REDIS_PASSWORD=''  CAKE='/var/www/MISP/app/Lib/cakephp/lib/Cake/'  APP='/var/www/MISP/app/'  COUNT=1  LOGHANDLER='RotatingFile'  LOGHANDLERTARGET='/var/www/MISP/app/tmp/logs/resque.log'  php './bin/resque'  >> '/var/www/MISP/app/tmp/logs/resque-worker-error.log'  2>&1

**Comment by elvidence** [comment]
apache 2987 0.0 0.0 222520 3456 ? S Sep20 0:00 bash -c cd ...
apache 3301 0.0 0.0 222520 3456 ? S Sep20 0:00 bash -c cd ...
etc … it seems MISP is running under the apache user, not www-data or misp. Try run MISP Commands as apache `sudo -u apache /var/www/MISP/app/Console/cake Password admin@admin.test Password1234` 

Check permissions on /var/www/MISP/ , you may need to  `sudo chown -R apache:apache /var/www/MISP/`
I hope you are not building the production system.

**Comment by LintStalker** [comment]
We missed one of the installation steps while setting up the server.  Seems to be working now
