### ISSUE TITLE
Support: misp-modules.service issue

### ISSUE THREAD

**Issue by rahulmanoj98** [MISP/MISP#9938]
### Support Questions

i had installed misp on my server,
during installation it showed no directory error for misp-modules.service.

it completed installation and showed 88%.
the console is accessible.
i went to server maintainence and settings and saw that there are only 25 plugins with an error symbol on it showing critical misconfigurations

### MISP version

2.4

### Operating System

ubuntu

### Operating System version

22.04

### PHP version

7.4.33

### Relevant log output

```shell
cp: cannot stat '/usr/local/src/misp-modules/etc/systemd/system/misp-modules.service': No such file or directory
Failed to enable unit: Unit file misp-modules.service does not exist.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Maybe the best would be to install the misp-modules independently as describe here -> https://misp.github.io/misp-modules/install/

**Comment by rahulmanoj98** [comment]
i installed using the manual you sent me, but when i check the status of misp-modules its shown as failed.
stays failed even if restarted.
