### ISSUE TITLE
Event filter window doesn't display correct information

### ISSUE THREAD

**Issue by pszemekd** [MISP/MISP#994]
When event filters rules are added to the filter they are not displayed correctly in the filter windows. Filter works correctly.

To replay:
go to List Events, start Filter. As Rule choose eventid, fill in the ID and click Add. No Rule will be added to the table below, URL for future searches will be modified correctly. When click Apply button - correct filter will be applied to the events.

**Comment by Rafiot** [comment]
Works for me, might have been fixed in the mean time.

@pszemekd Do you still have the issue?

**Comment by iglocska** [comment]
He is right, fixed.
