### ISSUE TITLE
Bug: Install.ubuntu 2404 fails on syntax error

### ISSUE THREAD

**Issue by blackrogan** [MISP/MISP#9967]
### Actual behavior

I am trying to install MISP 2.5.0 with you script INSTALL.ubuntu2404.sh but it doesnt work. I am getting syntax error ./install.sh: 70: Syntax error: "(" unexpected

### Expected behavior

Expected that shell works

### Steps to reproduce

Download the script and start with sh ./INSTALL.ubuntu2404.sh

### Version

2.5.0

### Operating System

Ubuntu

### Operating System version

24.04.1

### PHP version

8.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
I can't seem to be able to reproduce this, but tried a speculative fix, could you give it a go?

**Comment by blackrogan** [comment]
Hello yes I tried the same thing still was receiving the same error

**Comment by blackrogan** [comment]
Hello same error still occurs ./install.sh: 70: Syntax error: "(" unexpected

are there any requirements before starting the sh?

**Comment by blackrogan** [comment]
okay find out it was an issue on my side i started the command with sh ./INSTALL.ubuntu2404.sh not just ./INSTALL.ubuntu2404.sh you can close it
