### ISSUE TITLE
 Sync servers - push/pull rules not functional

### ISSUE THREAD

**Issue by west791** [MISP/MISP#997]
Hi

I tested if an event would be blocked to be pushed/pulled if it has a special tag on it, the push rules in the sync server settings. When I initiated a push, the event was pushed. Is this meant to be like this or shouldn't it rather be blocked from the push?
Usage scenario is that in our organization, we would like to have special tags which prevent events to be pulled/pushed to other MISPs. 

Greetings

west

**Comment by adulau** [comment]
Thank you for your request. This should work as you describe. Could you let us know which version of MISP that you are using? I remember some issues in the early version of 2.4 but those should have been fixed.

**Comment by iglocska** [comment]
Basically there are 2 ways to filter using tags: 
1. Set the allowed tags to be synced, if you set anything here then only events that are tagged will be synchronised
2. Block certain tags. If you do this then any event with the given tag will be blocked from being synchronised.

The more restrictive option is always chosen.

If this isn't the case let me know and especially if you have the steps to reproduce it.

Thanks in advance!

**Comment by Rafiot** [comment]
(cleaning up issues with no answers)
