### ISSUE TITLE
Support: Main page displays "Page isn't redirecting properly" after upgrade to 2.5 using Upgrade Script, seemingly no errors. 

### ISSUE THREAD

**Issue by mathurin68** [MISP/MISP#9985]
### Support Questions

I followed the following steps... 
```
sudo add-apt-repository ppa:ondrej/php
sudo add-apt-repository ppa:ondrej/apache2
sudo apt update
sudo apt upgrade
```
and then ran the script from here.. 
https://github.com/MISP/MISP/blob/2.5/INSTALL/UPGRADE.ubuntu2404.sh 

I didn't get any errors on anything except ssdeep, which I didn't care about, and I didn't see that any of the apache config files had changed?? 

Now, however, I can't get to my main page... it gives me an error 
"The page isn’t redirecting properly"

I rolled it back to my working install 2.4.198 on Ubuntu 24 BUT I would like to upgrade at some point. 

Has anyone else gotten this error after upgrading?  Appreciate it!! 

### MISP version

2.4.198

### Operating System

Ubuntu

### Operating System version

24.04

### PHP version

7.4

### Browser

Firefox

### Browser version

131.0.3

### Relevant log output

```shell
I didn't see ANY errors in the logs???? 
tail -f /var/log/apache2/error.log
tail -f /var/www/MISP/app/tmp/logs/error.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Keep in mind the installer also generates it's own logs, best to check in there!

`/var/log/misp_install.log`

**Comment by mathurin68** [comment]
Ugh.. daggonit, I'll try it again on Monday. Thank you!
